### ISSUE TITLE
inconsistencies between docker native image and docker jvm image

### ISSUE THREAD

**Issue by jphautin** [quarkusio/quarkus#10024]
**Describe the bug**
I would like to use both jvm and native image with the same code and configuration.
I have found 2 inconsistencies in the images provided by default:
- TimeZone
- file location

**Actual behavior**

I would like to use both jvm and native image with the same code and configuration.
I have found 2 inconsistencies in the images provided by default:
- in native image, the timezone used is relative to the system one which in my case is GMT+2 (Paris,Europe). In jvm image, the timezone is UTC. Theses lead to some headache when using @Scheduled annotations 
- in native image, the running directory is /work meaning you can access config directory with a relative path. In jvm image, is is /deployment. If using relative path, this make access to file working in one case (in my case native image) and failing in the other. It make use of @ConfigProperty(name = "myfile", defaultValue = "config/myfile.txt") broken on jvm image by example.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Have the same default behavior on both type of docker images (native and jvm) making switch from one to other easy.

**To Reproduce**
1. create a default project
2. build both native and jvm
3.  for timezone, check any logs, you will see the timezone is not the same
4. for file, try to create a file in 'config/file.txt'. this will work in native and fail on jvm

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux XXX 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.4.2 and 1.5.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /home/user/.m2/wrapper/dists/apache-maven-3.6.2-bin/795eh28tki48bv3l67maojf0ra/apache-maven-3.6.2
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /home/user/Development/graalvm-ce-java11-20.0.0
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-8-amd64", arch: "amd64", family: "unix"

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Closing for lack of feedback
