### ISSUE TITLE
Getting LAST_INSERTED_ID in mysql_reactive_client

### ISSUE THREAD

**Issue by obbyK** [quarkusio/quarkus#10029]
Is it possible to get the last inserted id with mysql reactive client using transactions? @geoand 

Example:
database table is person(id,firstname,lastname) where id is auto incremented.

    return this.client.begin()
       .flatMap(tx -> tx
               .preparedQuery("INSERT INTO person (firstname,lastname) VALUES ($1,$2)")
               .execute(Tuple.of(person.getFirstName(),person.getLastName()))
               .onItem().produceUni(id-> tx.query("SELECT LAST_INSERT_ID()"))
               .onItem().produceUni(res -> tx.commit())
               .onFailure().recoverWithUni(ex-> tx.rollback())
       );
This returns Void. How would I get the last inserted id without getting out of the transaction?

**Comment by geoand** [comment]
This isn't my wheelhouse, @tsegismont can you help out?

**Comment by tsegismont** [comment]
I'll reply on [SO](https://stackoverflow.com/questions/62406005/how-can-i-insert-and-get-last-inserted-id-in-mysql-with-transactions-using-quark)

**Comment by geoand** [comment]
Great, I'll close this then
