### ISSUE TITLE
Quarkus vision

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1003]
Explain in one or two paragraph the idea of:

* Graal VM and HotSpot tailored
* ecosystem of extensions
* best of breed of frameworks and standards
* cohesive experience
* opinionated (but optional) happy path (80% usage), smoothly transitioning to vanilla usage of the best of breed frameworks and standards for more powerful usages

**Comment by Sanne** [comment]
To close?

**Comment by emmanuelbernard** [comment]
No we need to publish it. 
@n1hility was working on some parts.

**Comment by gsmet** [comment]
@emmanuelbernard should we close this one now? Either we act on it or we close it but it's counter productive to keep it open indefinitely.

**Comment by gsmet** [comment]
I'm closing this one. We can still open a new one or reopen it if we feel it necessary.
