### ISSUE TITLE
Support for Logback using XML configuration

### ISSUE THREAD

**Issue by ahamed-k** [quarkusio/quarkus#10035]
Appreciate if you could add support for Logback and configuration in XML format in Quarkus

**Comment by lferna** [comment]
Is there any way to use logback with Spring libraries? Although it is not implemented for jvm, thanks.

**Comment by mamadaliev** [comment]
Is the question still relevant? Already added support? 
I have not found.

**Comment by stuartwdouglas** [comment]
This is being added as a Quarkiverse extension here: https://github.com/quarkiverse/quarkus-logging-logback

**Comment by stuartwdouglas** [comment]
First release of quarkus-logging-logback is done, any issues report them on the quarkiverse repo.
