### ISSUE TITLE
LDAP security - Documentation - Missing example code and LDAP data

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#10049]
The Quarkus Security LDAP documentation at  https://quarkus.io/guides/security-ldap requires a few updates:

The docuemnt referenced her does not exist:
  The solution is located in the security-ldap-quickstart directory. -> 
   https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-ldap-quickstart

The documentation makes certain assumptions about what OUs, users and groups exist in the LDAP server, but nowhere is shown what the LDAP server actually contains.

**Comment by sberyozkin** [comment]
CC @hartimcwildfly

**Comment by shoebxsiddiqui** [comment]
I want to work on this

**Comment by Rajib-Mardi** [comment]
Hi, @sberyozkin!
I want to work on this issue. May I go for it?

**Comment by sberyozkin** [comment]
A newer issue has been created at #10049 so I'll close this one as a duplicate
