### ISSUE TITLE
Support for Specifying the default namespace in application.properties

### ISSUE THREAD

**Issue by rohit-s8** [quarkusio/quarkus#10046]
**Description**
The [kubernetes extension for quarkus](https://quarkus.io/guides/deploying-to-kubernetes) always generates the resource definitions for the default namespace and there is no way to configure this during build time.
It would be great if we could have a system property like `quarkus.kubernetes.namespace` and set the namespace of the app without having to edit the generated sources each time

**Comment by geoand** [comment]
To be clear, the generated manifests do not reference the `default` namespace, they omit it completely which means that when you apply them, they are applied to whatever namespace is used in your current `kubectl` context

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/10674 adds this capability
