### ISSUE TITLE
OpenJ9 images not recognized as using run-java.sh

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#10056]
**Description**
Quarkus has a hard-coded list of base S2I images known to use the `run-java.sh` mechanism: https://github.com/quarkusio/quarkus/blob/1.5.1.Final/extensions/container-image/container-image-s2i/deployment/src/main/java/io/quarkus/container/image/s2i/deployment/S2iBaseJavaImage.java#L11-L19

This list doesn't include the Red Hat OpenJ9 images, which makes for a sub-par experience.

**Implementation ideas**
Just add the known OpenJ9 images to the `S2iBaseJavaImage` enum:

- https://catalog.redhat.com/software/containers/openj9/openj9-8-rhel7/5ddfdbf75a13461646f8171a
- https://catalog.redhat.com/software/containers/openj9/openj9-11-rhel7/5ddfdb26dd19c71643b652d5
- https://catalog.redhat.com/software/containers/openj9/openj9-8-rhel8/5ddfdbb8bed8bd164a0b1fa1
- https://catalog.redhat.com/software/containers/openj9/openj9-11-rhel8/5ddfdb765a13461646f816f0

**Comment by Ladicek** [comment]
CC @iocanel @geoand

**Comment by geoand** [comment]
@iocanel do you want to take this one?

**Comment by Ladicek** [comment]
It's rather easy, but I currently don't have time to spare, so I'd prefer if you guys could take over it :-)

**Comment by geoand** [comment]
@iocanel if you can do it that would be great. Otherwise I'll squize it in tomorrow

**Comment by iocanel** [comment]
I am not sure if I'll have the time tommorow

**Comment by geoand** [comment]
OK, I'll take a super quick look tomorrow morning then

**Comment by ejba** [comment]
@iocanel @geoand Perhaps I can help, if you don't mind. It's just add those images to the enum, right?

**Comment by geoand** [comment]
That's how I understand it, so feel free to take it and ping me and @Ladicek on the PR :)
