### ISSUE TITLE
Quarkus LDAP Security - on loglevel DEBUG, the username & password are dumped

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#10050]
**Describe the bug**
The debug log dumps passwords. Maybe it is a good idea to censor them, or else at least give only a hash of that password?  An example:

2020-06-16 10:47:09,259 DEBUG [io.qua.ver.htt.run.sec.BasicAuthenticationMechanism] (vert.x-eventloop-thread-14) Found basic auth header USERNAME:PASSWORD (decoded using charset UTF-8)

**Expected behavior**
The password should not be logged

**To Reproduce**
1.  Create a project with security based on plain authentication
2.  Change application.propêrties to set the loglevel to debug
3.  Surf, log on, enter username and password

**Comment by sberyozkin** [comment]
CC @hartimcwildfly

**Comment by gsmet** [comment]
Right, passwords should never be logged. Please replace that with `*****`.
