### ISSUE TITLE
GraalVM: Native Image Build fails

### ISSUE THREAD

**Issue by Auties00** [quarkusio/quarkus#10074]
When I try to build the native image for my quarkus project using the command mvn package -Pnative I get an unexpected error that causes the build to fail:
`
Error: Cannot run program "C:\Program Files\Java\graal\bin\java.exe": CreateProcess error=206, Name or extension is too long
`
 - java version "13.0.1" 2019-10-15
   Java(TM) SE Runtime Environment (build 13.0.1+9)
   Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
 - java version 11 
 - Latest
 - Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: C:\maven\bin\..
Java version: 13.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13.0.1
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

If you need the full log tell me, it's really long and github won't let me upload it

**Comment by geoand** [comment]
Hi,

It would be great if you could upload the log to gist or pastebin or something so we can take a look.

**Comment by Auties00** [comment]
> Hi,
> 
> It would be great if you could upload the log to gist or pastebin or something so we can take a look.

https://hastebin.com/wexiqidoda.sql

**Comment by geoand** [comment]
Can you perhaps attach the output of `mvn -X package -Dnative`?

**Comment by Auties00** [comment]
[output.txt](https://github.com/quarkusio/quarkus/files/4803931/output.txt)
Kind of long

**Comment by geoand** [comment]
My guess from the output is that you the path you are running from is causing problems, I see `C:\Users\Ale\Desktop\Coding\Java\6) Backend\hytaleshosting`

Can you try using a path that doesn't have weird characters in it please?

**Comment by Auties00** [comment]
> My guess from the output is that you the path you are running from is causing problems, I see `C:\Users\Ale\Desktop\Coding\Java\6) Backend\hytaleshosting`
> 
> Can you try using a path that doesn't have weird characters in it please?

Just tried(C:/hytaleshosting), same thing. Also the error refers to: "C:\Program Files\Java\graal\bin\java.exe", should I try to move the jdk to C:\?

**Comment by geoand** [comment]
Can you try executing 

```
C:\Program Files\Java\graal\bin\native-image.cmd -J-Dsun.nio.ch.maxUpdateArraySize=100 ...
```

from you command line from inside `target/...-native-image-source-jar`?

**Comment by jaikiran** [comment]
This actually is a known issue in Graal VM which is being tracked here https://github.com/oracle/graal/issues/2387. There's a PR open for it https://github.com/oracle/graal/pull/2443

**Comment by geoand** [comment]
Ah, that's nice! Thanks @jaikiran

**Comment by quintesse** [comment]
The PR https://github.com/oracle/graal/pull/2443 for the Graal issue has finally been merged,

**Comment by Auties00** [comment]
> The PR [oracle/graal#2443](https://github.com/oracle/graal/pull/2443) for the Graal issue has finally been merged,

Thanks :)
