### ISSUE TITLE
Propagate custom main class to manifest

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#10086]
Based on [a discussion](https://twitter.com/maxandersen/status/1273525669247492096) with @maxandersen on Twitter. If there's a custom main method in a `@QuarkusMain` class, it'd be useful to set that class as the main class in the JAR manifest. I hope it's doable in the light of rules described [here](https://quarkus.io/guides/command-mode-reference#multiple-main-methods) for finding the right main method.

**Comment by maxandersen** [comment]
@stuartwdouglas and @quarkusio/devtools - any objections to this idea ?

**Comment by geoand** [comment]
Weird that we don't do that already... I don't see why we wouldn't do it

**Comment by geoand** [comment]
Let me play with it real quick

**Comment by geoand** [comment]
I tried out our quickstart and it the main class is in the manifest. Can you show me an example of something that doesn't work properly?

**Comment by gunnarmorling** [comment]
Interesting, maybe I'm doing something stupid :) Here's my code: https://github.com/gunnarmorling/search.morling.dev. Run this:

```
mvn clean package -DskipTests=true
jar -xvf target/quarkus-lucene-1.0.0-SNAPSHOT-runner.jar META-INF/MANIFEST.MF
```

And observe how the generated main class is set.

**Comment by geoand** [comment]
I see Stuart self assigned, so I'll let him investigate or I can take it if he is doing something for the time being
