### ISSUE TITLE
Not expected behaviour when using http.* or https.* proxy system properties

### ISSUE THREAD

**Issue by paolocarta** [quarkusio/quarkus#10096]
**Describe the bug**

At the moment in order to set an http/https proxy one uses system properties like:
```-Dhttp.proxyHost=localhost -Dhttp.proxyPort=9090 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -Dhttp.nonProxyHosts=dummy.example.com```

However, the behaviour is not as expected. For instance:

- If you specify just https.* properties, they are not picked up.

- If you specify both http and https properties and a http.nonProxyHosts, the latter is not picked up, forcing everything through the proxy.

**Expected behavior**
What I would expect:

- If you specify https.* proxy properties, they should be picked up for https calls.

- If you use both http and https properties with http.nonProxyHosts, the latter should be picked up to avoid going through the proxy.

**To Reproduce**
1. Clone and compile the test repo: https://github.com/paolocarta/microprofile-rest-clients-http-proxy
2. Start the app with: ```java -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -jar target/rest-client-quickstart-1.0-SNAPSHOT-runner.jar``` , the https proxy is not picked up.
3. Start the app with: ```java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=9090 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=9090 -Dhttp.nonProxyHosts=dummy.restapiexample.com -jar target/rest-client-quickstart-1.0-SNAPSHOT-runner.jar``` , the nonProxyHosts property is ignored.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro 19.5.0 Darwin Kernel Version 19.5.0
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14, OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
 - Quarkus version or git rev: for sure starting with 1.3.2 and above.
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3

**Comment by gastaldi** [comment]
Might be fixed by https://github.com/quarkusio/quarkus/pull/10069
