### ISSUE TITLE
Vertx native transport always false

### ISSUE THREAD

**Issue by Biratus** [quarkusio/quarkus#10095]
No matter the value in quarkus.vertx.prefer-native-transport there is always this in the logs:

DEBUG [io.qua.ver.cor.run.VertxCoreRecorder] (main) Vertx has Native Transport Enabled: false

**Comment by tsegismont** [comment]
@Biratus I can't reproduce. I created a new project with `code.quarkus.io`, added these to config:

```
quarkus.log.level=DEBUG
quarkus.vertx.prefer-native-transport=true
```

And to the POM:

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <classifier>linux-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-kqueue</artifactId>
      <classifier>osx-x86_64</classifier>
    </dependency>
```

After starting with `quarkus:dev`:

```
2020-06-25 12:04:43,337 DEBUG [io.qua.ver.cor.run.VertxCoreRecorder] (Quarkus Main Thread) Vertx has Native Transport Enabled: true
```

**Comment by tsegismont** [comment]
Can you please share a minimal reproducer?

**Comment by marziman** [comment]
hello colleagues,

we are using native images and want to enable also native transport for vertx.
We are seeing the following output in logs:
"Vertx has Native Transport Enabled: false"

@cescoffier @tsegismont is this intended behaviour or are we doing sth. wrong?
We really would like to make use of native transport with native images.

Thanks for all your great work and help
Mehmet

**Comment by tsegismont** [comment]
@marziman please share a minimal reproducer

**Comment by galderz** [comment]
@cescoffier and I have been looking into this. We've reproduced the issue in [this small example](https://github.com/galderz/mendrugo/tree/master/epoll). For epoll native transport to work in native image, it'd seem that we need to pre-register some classes/field/methdos for JNI access, plus we also need Netty's `AbstractReferenceCounted` to be initialized at build time. We haven't fully settled on a solution yet, but the example above shows one way to make it work.

**Comment by cescoffier** [comment]
At the moment, native transport is disabled in native mode. We may reconsider this in the near future. If you have a need for supporting native transport in native, let's open another issue (and track it as a feature request).
