### ISSUE TITLE
CI job failures - FormAuthCookiesTestCase#testCredentialCookieRotation fails on slow systems

### ISSUE THREAD

**Issue by jaikiran** [quarkusio/quarkus#10106]
FormAuthCookiesTestCase#testCredentialCookieRotation has been recently failing in some CI runs [1][2]. The failures aren't really genuine issues with the feature being tested but instead have to do with the kind of timing checks that are in place in that test. On slow systems, these checks can lead to spurious failures. The test could be improved to avoid these checks and yet test the feature being tested.

[1] https://github.com/quarkusio/quarkus/pull/10088/checks?check_run_id=783871953
[2] https://github.com/quarkusio/quarkus/pull/10093/checks?check_run_id=784883612

**Comment by geoand** [comment]
I propose that for the time being we disable this test. When someone looks into it and comes up with a fix, we can reenable it

**Comment by geoand** [comment]
Let's close this as we have not received any additional complaints
