### ISSUE TITLE
SSL client authentication for consul-config extension

### ISSUE THREAD

**Issue by crissi98** [quarkusio/quarkus#10117]
**Description**
There should be a way to provide a keystore with a client certificate for the consul-config extension to use for client authentification with the consul agent.

**Implementation ideas**
By now, there is a config property called ```quarkus.consul-config.agent.key-store```. This property is used to provide a truststore. In my opinion, this property should be renamed to ```quarkus.consul-config.agent.trust-store``` and the property ```quarkus.consul-config.agent.key-store``` should be used to provide a keystore with the client certificate.
I already implemented these changes on my own fork which you can find here: https://github.com/crissi98/quarkus/tree/consul-key-store/extensions/consul-config

**Comment by geoand** [comment]
Makes sense,

would you like to provide a PR? 
Also, have you tried your code in native mode?

**Comment by crissi98** [comment]
I did not try it in native mode yet. I will verify that it is working in native mode and then i would like to provide a PR.

**Comment by crissi98** [comment]
I tested it in native mode and it does also work

**Comment by crissi98** [comment]
Closing this since it is fixed by #10145
