### ISSUE TITLE
QuarkusClassLoader makes the slf4j log backend initialize the second time

### ISSUE THREAD

**Issue by zolyfarkas** [quarkusio/quarkus#10118]
I have a custom TestExecutionListener that uses slf4j for logging. This listener runs before the Quarkus junit Extension kicks in and loads the slf4j backend (singleton)

The quarkus junit extension uses QuarkusClassLoader with                     .setIsolateDeployment(true) which causes slf4j backend to load again.

would there be interest to make setIsolateDeployment() configurable? 
The same for DevModeMain ?

**Comment by stuartwdouglas** [comment]
Are you using 


		<dependency>
			<groupId>org.jboss.slf4j</groupId>
			<artifactId>slf4j-jboss-logging</artifactId>
		</dependency>

Or are you trying to use normal slf4j?

**Comment by zolyfarkas** [comment]
No, I was using:

```
    <dependency>
      <groupId>org.spf4j</groupId>
      <artifactId>spf4j-slf4j-test-junit5</artifactId>
      <scope>test</scope>
      <version>8.8.4</version>
    </dependency>
```

which is a [slf4j backend](http://www.spf4j.org/spf4j-slf4j-test/index.html) that does a few useful things for my unit tests. (like failing them if they log an error that is unasserted)

This resulted in a logging init issueat netty's InternalLoggerFactory:

```
    @SuppressWarnings("UnusedCatchParameter")
    private static InternalLoggerFactory newDefaultFactory(String name) {
        InternalLoggerFactory f;
        try {
            f = new Slf4JLoggerFactory(true);
            f.newInstance(name).debug("Using SLF4J as the default logging framework");
        } catch (Throwable ignore1) {
            try {
                f = Log4J2LoggerFactory.INSTANCE;
                f.newInstance(name).debug("Using Log4J2 as the default logging framework");
            } catch (Throwable ignore2) {
                try {
                    f = Log4JLoggerFactory.INSTANCE;
                    f.newInstance(name).debug("Using Log4J as the default logging framework");
                } catch (Throwable ignore3) {
                    f = JdkLoggerFactory.INSTANCE;
                    f.newInstance(name).debug("Using java.util.logging as the default logging framework");
                }
            }
        }
        return f;
    }
```

the above exception handling is questionable, and made finding the issue very difficult.

The above code was failing at Slf4JLoggerFactory.newInstance.debug with an exception that a class does not implement an interface. This was because the interface was loaded with a different class-loader than the current context class loader(quarkus).

The resolution was [a fix](https://github.com/zolyfarkas/spf4j/commit/be66d199e13590dce25eba604e413c86d39c5d65) in spf4j lib. 

however other similar class loading issues could happen, and having the class loader isolation configurable would help.

**Comment by stuartwdouglas** [comment]
The ClassLoader isolation is necessary to make transformers work, without
it a lot of features won't work in tests.

Can you try adding a META-INF/quarkus-extension.properties file to your
application, and putting the following line in it:

parent-first-artifacts=org.spf4j\:spf4j-slf4j-test-junit5,org.slf4j\:slf4j-api

No idea if this will work, but in theory it will tell Quarkus to not use
class loader isolation for those artifacts. We use this mechanism for our
extensions, we have not actually tested using this inside a user
application but in theory it should work (I think).

Stuart

**Comment by stuartwdouglas** [comment]
Did you try my suggested workaround?

**Comment by geoand** [comment]
Closing as there has been no user update
