### ISSUE TITLE
ldap - setRecursive

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#10110]
**Description**
As described in the chat:
I'm trying to use quarkus LDAP integration withactive directory, and I'm running in some snags:

I started with https://quarkus.io/guides/security-ldap

REMARK 1:
io.quarkus.elytron.security.ldap.LdapRecorder:createRealm seems to have no configuration option to call setRecursive(true)
Hence quarkus requires all users in LDAP to be in the same organizational unit..  

This is untenable for all but the smallest organizations: If you have different buildings or even different teams, you'll organize these people in different OUs

**Implementation ideas**
I assume this is straightforward for someone with basic knowledge of the code base (which is not me,  our corporate proxy can't even do git to external orgs, sorry) - add a config flag in application.properties which maps to setRecursive

**Comment by sberyozkin** [comment]
From the chat: `HartiMcWildfly: LdapRecorder under identityMapping() add a .searchRecursive()`

**Comment by antonwiens** [comment]
@gsmet I would like to contribute this. I would also like to provide the ability to use the CachingSecurityRealm wrapper for caching the ldap results. I would make the caching (enabling it) and caching properties (maxEntries and maxAge) configurable.
