### ISSUE TITLE
Introduce label for tracking native image related issues

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#10120]
Introduce label for tracking native image related issues and PRs.

At this moment there is no way to search for native image related issues.
There is graalvm-java11 label, but that's specific for JDK 8 -> JDK11 move.

https://quarkusio.zulipchat.com/#narrow/stream/191168-core-team/topic/GH.20issues.20-.20native.20image/near/201252952

**Comment by rsvoboda** [comment]
@gsmet / @maxandersen fyi

**Comment by maxandersen** [comment]
+1 for a "area/native" or "area/native-image" issues and pull-requests.

**Comment by geoand** [comment]
Has been fixed by the introduction of `area/native-image`
