### ISSUE TITLE
Allow QuarkusTest to override base URL of REST client

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#10126]
As [discussed on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/help.20with.20PACT.20extension) it could be useful if a test could override the base URL of a given REST client.

One use case (as discussed on Zulip) would be for a PACT consumer test, where the test invokes some method on a REST client (directly or indirectly through some service in the application under test), which in turn should direct its request to some PACT mock server, which records the request and returns a canned response.

As a workaround the test currently has to create a REST client manually using `RestClientBuilder`.

**Comment by geoand** [comment]
I have a technical way to do this (using a lot of reflection), but the best way for a user to use this isn't clear to me.

Would you like to open start a quarkus-dev mailing thread discussion where you will present this use case to folks and ask what they think the best API is?

Thanks

**Comment by geoand** [comment]
The simplest thing I can think of is to expose a class like `RestClientTest` that would have a `useBaseUrl` method where the user (or in the future a test extension) would set a base URL given a rest-client class (very similar to what `QuarkusMock` does).

WDYT?

**Comment by knutwannheden** [comment]
> The simplest thing I can think of is to expose a class like `RestClientTest` that would have a `useBaseUrl` method where the user (or in the future a test extension) would set a base URL given a rest-client class (very similar to what `QuarkusMock` does).

Yes, something like that sounds good to me. I can't really say if it should be `setBaseUrl()` or `setBaseUri()`. And possibly the `Test` suffix in `RestClientTest` is a bit confusing. Maybe something like `RestClientSupport`?

**Comment by geoand** [comment]
> Maybe something like `RestClientSupport`?

Yeah, makes sense

**Comment by geoand** [comment]
I'll go ahead and close this as https://github.com/quarkusio/quarkus/pull/9933 has been merged and is part of 1.6

**Comment by stephan-strate** [comment]
@knutwannheden How did you ultimately solve this problem? The TestProfiles need the config properties at build time, right? But the Pact mockserver url is only available at runtime. Thats why I would love to see the `RestClientTestSupport` implementation: https://github.com/geoand/quarkus/commit/888a36f7e2cd3b02d183bf004901a05a1039d4d8#diff-a1f19a532def9abaf3e8cfbc57a80b5bf20309dc4c584db1d1b2bd3fef15415c
