### ISSUE TITLE
ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10128]
Quarkus 1.5 as a native executable - together with sendgrid-java 4.6.0.

And there I am getting:

Getting:
Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
web_1  | 	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
web_1  | 	at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
web_1  | 	at java.security.AccessController.doPrivileged(AccessController.java:81)
web_1  | 	at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
web_1  | 	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
web_1  | 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
web_1  | 	at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
web_1  | 	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
web_1  | 	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
web_1  | 	at com.sendgrid.Client.<init>(Client.java:62)
web_1  | 	at com.sendgrid.BaseInterface.<init>(BaseInterface.java:61)
web_1  | 	at com.sendgrid.SendGrid.<init>(SendGrid.java:13)

As I can see, sendgrid-java is using: 
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.10</version>
</dependency>

It has a commons logging dependency defined as:
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <scope>compile</scope>
    </dependency>

So I do not understand why commons logging would be missing - and I saw similar issues from other users of Quarkus online as well.. could it be that commons logging is removed, as there is already a logging library in place?

**Comment by jaikiran** [comment]
Hello @MarcusBiel, is there an application that you can share which reproduces this issue? Preferably as a github repo? I'm interested in the `pom.xml` to see what extensions and dependencies are in place for your project.

**Comment by MarcusBiel** [comment]
I am trying to set up a sample application to reproduce the issue, however that's not so easy as it is a native executable, using ssl, jwt, database, sendgrid... 

As a first go, here is the pom.xml. It has the org.jboss.logmanager.LogManager,
maybe that's a first thing I need to replace with a different LogManager?

<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.myproject</groupId>
    <artifactId>myartifact</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus-plugin.version>1.5.0.Final</quarkus-plugin.version>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>1.5.0.Final</quarkus.platform.version>
        <surefire-plugin.version>2.22.2</surefire-plugin.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency>
            <groupId>com.sendgrid</groupId>
            <artifactId>sendgrid-java</artifactId>
            <version>4.6.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-agroal</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mariadb</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemProperties>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemProperties>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build/>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>
</project>

**Comment by MarcusBiel** [comment]
Ok, here is a sample application with the described bug: 
https://github.com/MarcusBiel/quarkus-sample

I have also committed the target folder with the native executable (mac) that show cases the Exception thrown form SendGrid.

**Comment by MarcusBiel** [comment]
Ok, I was able to fix the ClassNotFoundException by adding a reflection-config.json. However, now I still get an error when sending out emails - the external library uses it's own version of Jackson it seems, this is not working in native mode, and therefore the body send to the external endpoint is empty. 
Updated the reproducer here:  https://github.com/MarcusBiel/quarkus-sample

**Comment by MarcusBiel** [comment]
Tried to exclude Jackson, so that the quarkus-jackson dependencies are used instead. No success yet:
        <dependency>
            <groupId>com.sendgrid</groupId>
            <artifactId>sendgrid-java</artifactId>
            <version>4.6.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>com.fasterxml.jackson.core</artifactId>
                    <groupId>jackson-core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>com.fasterxml.jackson.core</artifactId>
                    <groupId>jackson-annotations</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>com.fasterxml.jackson.core</artifactId>
                    <groupId>jackson-databind</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by jaikiran** [comment]
I have been a bit busy with some of my other work. If no one else gets to this first, I'll try and take a look at this in the next few days.

**Comment by oztimpower** [comment]
Hi @MarcusBiel , I downloaded your project. It doesn't compile, so I changed the response to String.

The issue you mention is documented in building a native image, you need to add the JBoss Logging to your project, and remove the `application.properties` reference to `reflection-config.json` and `resources-config.json`. 

Note: I updated to the latest `Quarkus` version `1.5.2.Final` 

I was looking for where this was in the documentation, then I realised I know this because I've encountered the error, when adding the AWS SDK to my native applications, and it was added to an issue like this one.  I'll add this to the documentation, so others don't experience this!

**Appreciate if you could validate this works for your project, and close this issue if successful**

```
# quarkus.native.additional-build-args=-H:ResourceConfigurationFiles=resources-config.json, -H:ReflectionConfigurationFiles=reflection-config.json
```

Add dependency to `pom.xml`
```
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>commons-logging-jboss-logging</artifactId>
            <version>1.0.0.Final</version>
        </dependency>
```


Native executable:
```
$ ./target/myartifact-1.0-SNAPSHOT-runner 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-07-04 10:53:22,048 INFO  [io.quarkus] (main) myartifact 1.0-SNAPSHOT native (powered by Quarkus 1.5.2.Final) started in 0.008s. Listening on: http://0.0.0.0:8080
2020-07-04 10:53:22,048 INFO  [io.quarkus] (main) Profile prod activated. 
2020-07-04 10:53:22,048 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jackson]
```

**Comment by MarcusBiel** [comment]
Hi @ oztimpower, thanks for your reply!
1)remove the application.properties reference to reflection-config.json and resources-config.json

I don't understand. I need  reflection-config.json so I can define third party reflection usage. I need resources-config.json so I can define json files that need to be added. 

Have you read my recent replies -
1) I FIXED the ClassNotFoundException by adding a reflection-config.json
2) To send out emails, the sendgrid third party dependency uses jackson - which again uses reflection - and they use a non quarkus compatible version. I was not able to exclude their jackson version so that the quarkus specific version is used.. long story short... due to all those problems with native, I have given up on native... too much hassle still. Without native all is working fine.

**Comment by oztimpower** [comment]
I was able to get your sample project working. 

The logging issue is resolved by using the maven dependency hence I didn’t need what you had hand crafted. 

Noted that you were sticking with the JVM version.

Can I suggest at least you close this, as I have updated the documentation on PR #10474 to demonstrate how to overcome the Commons Logging issue with native image.

**Comment by MarcusBiel** [comment]
Well I think there is still an issue... but as I am not using native anymore... I may close this.

**Comment by sorin-costea** [comment]
The solution suggested here (and in the documentation) doesn't work - the 'commons-logging-jboss-logging' doesn't have 'LogFactoryImpl'

**Comment by gsmet** [comment]
@sorin-costea What it needs is the `LogFactory`. It doesn't need `LogFactoryImpl` as the `LogFactory` uses JBoss Logging instead.

What's your issue exactly?

**Comment by sorin-costea** [comment]
@gsmet see #13528
