### ISSUE TITLE
Problem with Unit Tests (H2 DB)

### ISSUE THREAD

**Issue by danilomeneghel** [quarkusio/quarkus#10136]
I did a project with Quarkus, but I'm having difficulties with the Tests part.

I used the H2 as a bench (because it is more practical for testing), but even though I made the settings (the system running and saving the data), in the unit test this does not happen.
The following error message is returning for all classes that are tested:

`"Connect Connection refused: connect"`

I have also changed the connection to another bank (postgresql), but the error persists.
The test I'm running via the terminal, and I see that the tables are created in the bank, however when adding, editing or deleting some data via Rest, it gives this error, as if it were not connecting the bank, but it doesn't make sense , because the tables are created when running the test (drop-and-create).

Follow my project on Github:
https://github.com/danilomeneghel/votacao-pautas

I appreciate anyone who can help with the tests.

**Comment by famod** [comment]
It seems you have not set the `db-kind` property: https://quarkus.io/guides/datasource#default-datasource

**Comment by danilomeneghel** [comment]
Thanks for the feedback.
I have now added this "quarkus.datasource.db-kind = h2" to the application.properties file, however the error persists.

I will add this here as a Bug.

**Comment by danilomeneghel** [comment]
It's Solved.
