### ISSUE TITLE
slf4j (jboss) logging doesn't work when native-image isolates are used

### ISSUE THREAD

**Issue by AndreiYu** [quarkusio/quarkus#10157]
**Describe the bug**
Logger (default Quarkus Jboss logger wrapped with slf4j) doesn't generate output when invoked from isolates.
When no isolates are used (either from native-image or from hotspot dev mode), log output is present as expected

**Expected behavior**
Logger defined as static final field in the class generates output when invoked from Isolate context.

or:
Logger created as new instance inside a method generates output when invoked from Isolate context.

as described in GraalVM native spec: https://github.com/oracle/graal/blob/master/substratevm/LOGGING.md

**Actual behavior**
Logs not shown when logger invoked from Isolate context.

**To Reproduce**
1. define and initialize static final LOGGER field inside a class (or inside a method)
`private static final Logger LOGGER = LoggerFactory.getLogger(SomeClass.class);`
2. call LOGGER.Log() from inside main context (logs are shown in console)

```
void myMethod() {
  LOGGER.info("abc");
}
```
3. Create IsolateThread in some method

`var isolateThread = Isolates.createIsolate(params);`

call LOGGER.Log() from inside a method marked as `@CEntryPoint
myMethod2(@CEntryPoint.IsolateThreadContext IsolateThread isolateThread)`

```
@CEntryPoint
private static void myMethod2(@CEntryPoint.IsolateThreadContext IsolateThread isolateThread) {
  LOGGER.info("not shown");
}
```
**Configuration**
```properties
# Add your application.properties here, if applicable.
`quarkus:
  vertx:
    event-loops-pool-size: 24
  http:
    host: 127.0.0.1
    port: 8080
  native:
    native-image-xmx: 12g
    additional-build-args: "--language:js, -H:ReflectionConfigurationFiles=reflection-config.json,--enable-https,--enable-http,-H:+SpawnIsolates"
  index-dependency:
    slf4j:
      group-id: org.slf4j
      artifact-id: slf4j-api


"%prod":
  quarkus:
    log:
      level: DEBUG
      console:
        level: DEBUG`
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 19.5.0: root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
 - Quarkus version or git rev: 1.5.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): gradle 6.4

**Additional context**
I tried to use java.util.logger without Quarkus and faced the same issue. The problem was related to different classLoaders that applied for loading the Logger (in main context it was System classLoader, in isolates - Bootstrap classloader), so I performed the steps defined in GraalVM manual https://github.com/oracle/graal/blob/master/substratevm/LOGGING.md and initialized new logger by reading logging.properties and initializing Logger with different classloaders in runtime.

When switching to Quarkus and slf4j and trying the same it appeared that Quarkus wraps this behavior and uses it's own logic, it initializes Jboss logger by default and uses separate ApplicatinClassloaders either for main context or for isolate. (https://quarkus.io/guides/class-loading-reference).
System.out gave me this output for loggers called from main and isolate context:

> Classloader: jdk.internal.loader.ClassLoaders$AppClassLoader@1242e2120, calling class: Processor
> logger::: org.jboss.logmanager.LoggerLogger 'com.server.Processor' in context org.jboss.logmanager.LogContext@124083d30 **(result not printed in console since invoked from isolate context)**

> Classloader: jdk.internal.loader.ClassLoaders$AppClassLoader@11d4fa120, calling class: Processor
> logger::: org.jboss.logmanager.LoggerLogger 'com.server.Processor' in context org.jboss.logmanager.LogContext@11d29bd30 **(result printed in console since invoked from main context)**

Tried to switch back to Quarkus + java.util.logger (providing logging.properties file config and -Djava.util.logging.manager=java.util.logging.LogManager), but with the same result.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
