### ISSUE TITLE
ConstraintViolation(CheckedException can't be properly handled as BAD_REQUEST

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10154]
SQLIntegrityConstraintViolationException  is a checked exception, so Arc needs to wrap it in a RuntimeException. Now this can't be properly handled as BAD Request anymore. 

More you can also find in this issue: https://github.com/quarkusio/quarkus/issues/3949
including code to reproduce the issue: https://github.com/abelsromero/quarkus-issue3949

Following this approach I wrote an exception mapper:
```
public class ApplicationExceptionHandler
        implements ExceptionMapper<ApplicationException> {

    private final Logger log = LoggerFactory.getLogger(ApplicationExceptionHandler.class);

    @Override
    public Response toResponse(ApplicationException applicationException) {
        String errorId = errorId();
        RuntimeException runtimeException = applicationException;

        Response.Status responseStatus = Response.Status.INTERNAL_SERVER_ERROR;
        SQLIntegrityConstraintViolationException constraintViolationException = findConstraintViolationException(applicationException);
        if (constraintViolationException != null) {
            runtimeException = new RuntimeException(constraintViolationException);
            responseStatus = Response.Status.BAD_REQUEST;
        }
        logError(errorId, runtimeException, responseStatus);

        return Response.status(responseStatus)
                .entity(new ErrorDto(errorId, runtimeException.getMessage()))
                .type(MediaType.APPLICATION_JSON)
                .build();
    }

    private SQLIntegrityConstraintViolationException findConstraintViolationException(Throwable exception) {
        while (exception.getCause() != null && exception.getCause() != exception) {
            exception = exception.getCause();
            if (exception.getClass().equals(SQLIntegrityConstraintViolationException.class)) {
                return (SQLIntegrityConstraintViolationException) exception;
            }
        }
        return null;
    }
```

However the problem with this is now ALL ApplicationException are caught. Now a NotFoundException is handled as a 500 error. So now basically I would have to manually handle all kinds of possible user exceptions.

There should be a better way to handle user exceptions.

**Comment by ahofmeister** [comment]
I talked with @FroMage about this topic in and he created this issue: https://issues.redhat.com/browse/RESTEASY-2603 No one yet picked it up.

**Comment by MarcusBiel** [comment]
This issue is over one year old now. Stil quarkus does not offer a decent way to handle exceptions :(

**Comment by geoand** [comment]
Closing his as RESTEasy Reactive's `@ServerExceptionMapper` can handle this
