### ISSUE TITLE
-Dquarkus.args cannot handle more than one argument in command line

### ISSUE THREAD

**Issue by rt-chang** [quarkusio/quarkus#10166]
**Describe the bug**
When running applications in Maven with more than one command line argument for `-Dquarkus.args`, Quarkus is not capable of handling those arguments and passing them to the application

**Expected behavior**
In the example code linked below in reproduction steps, the expected behaviour is for the program to take 2 arguments (`--name` and `--day`) which should produce a message of `Hello {name}! Today is {day}`

**Actual behavior**
The console outputs help text for either Java or Maven

**To Reproduce**
1. Clone example [repo](https://github.com/rt-chang/quarkus-command-line-demo)
2. Enter the command `./mvnw quarkus:dev -Dquarkus.args="--name=Bob --day=Monday"` (or any other values for the arguments)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.17763.1282]`
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - GraalVM version (if different from Java): `20.1.0`
 - Quarkus version or git rev: `Quarkus 1.5.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
Also tried the following:
- Attempted to escape the quotes as suggested by @geoand in the Zulip chat (ie. ` ./mvnw quarkus:dev -Dquarkus.args=\"--name=Bob --day=Monday\"`
- Attempted to use commas as delimiters between arguments

**Comment by geoand** [comment]
I wonder if this is a Windows cmd issue... In any case we probably should be going the extra mile to split the arguments

**Comment by gastaldi** [comment]
I can confirm this fails in Fedora 32 too

**Comment by geoand** [comment]
Interesting!

**Comment by gastaldi** [comment]
I managed to make it work by changing this line: 

https://github.com/takari/maven-wrapper/blob/7039b05cfec0e8a729d6d84670433912e00c6aa5/mvnw#L301

to 
```
MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG \"$@\""
```

@rt-chang can you perform this change locally and let me know if that works for you?

**Comment by rt-chang** [comment]
I was unable to get it to work locally. It produced the help text for Java's CLI

**Comment by rt-chang** [comment]
I noticed when looking at the [related PR for this feature](https://github.com/quarkusio/quarkus/pull/8433), that Quarkus handles the arguments differently for [quarkus.args](https://github.com/38leinaD/quarkus/blob/4a9495b95e290a285ca77ef1141ab480222362e0/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L648) versus [jvm args](https://github.com/38leinaD/quarkus/blob/4a9495b95e290a285ca77ef1141ab480222362e0/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L298). Not sure if this is the root cause though

**Comment by gastaldi** [comment]
@rt-chang Good catch! I reused the same class to parse the JVM args and apparently it works. Let me provide a PR

**Comment by hummerpj** [comment]
I see this was closed but the linked merge seems to reference "not working on windows".

Just wanted to confirm that is the case or to expect this to be working on windows for Quarkus 1.6

Thank you for your time.

**Comment by gastaldi** [comment]
@hummerpj I don't think there is one specifically for Windows, mind creating one? Thanks

**Comment by hummerpj** [comment]
@gastaldi 

I think I spoke too soon, I was working on creating a separate project to recreate it but appears to be working fine on windows.

Carry on :D

**Comment by fleigm** [comment]
I'm still having this issue using quarkus version 1.8.1.FINAL on my ubuntu 20.04 machine.
Can sombody confirm this?

**Comment by gastaldi** [comment]
@fleigm I don't have Ubuntu. Can you open a new issue with a reproducer? Thanks!

**Comment by gavinz8** [comment]
In my way, I just remove quotes in head and trail, eg. -Dquarkus.arg --name --day
