### ISSUE TITLE
Allow logging with timestamps at UTC

### ISSUE THREAD

**Issue by ctron** [quarkusio/quarkus#10193]
**Description**

It should be possible to configure the timestamps for logging to UTC. Having the option to show the timezone is fine, but for aggregated logging, it should be possible to configure the logging system to UTC (for the logs only, not the full JVM).

Most logging frameworks can to this out of the box (Logback, JBoss Logging, Log4J2, …) Quarkus should be able to do that too.

**Implementation ideas**

Re-use the `EnhancedPatternLayout` from JBoss logging: https://docs.jboss.org/jbossas/javadoc/7.1.2.Final/org/apache/log4j/EnhancedPatternLayout.html … which can do `%d{HH:mm:ss}{GMT+0}`.

**Comment by jamezp** [comment]
This should already be possible. The patterns for the pattern formatter are documented here https://docs.wildfly.org/20/Admin_Guide.html#pattern-formatter. I should migrate that to some documentation for the log manager, but I digress. 

Anyway the pattern is `%z{UTC}` so something like `%z{UTC}%d{yyyy-MM-dd'T'HH:mm:ssSSSXXX}` should work.

**Comment by jaikiran** [comment]
I followed @jamezp's instructions and just gave this a try against a simple Quarkus application:

```
quarkus.log.console.enable=true
quarkus.log.console.format=%z{UTC}%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.console.color=false

quarkus.log.category."io.quarkus".level=DEBUG
```
```
mvn clean quarkus:dev
```
It all works as expected, the log messages have the UTC times.

**Comment by jaikiran** [comment]
I'll let @gsmet close this, since I'm unsure whether we mark requests like this as `triage/invalid` or something else.

**Comment by gsmet** [comment]
I make them `question` :).

BTW, it looks like something we could document in the logging guide?

**Comment by gastaldi** [comment]
Ah, I missed that kind, thanks @gsmet! Yeah, I think that would be nice to have
