### ISSUE TITLE
Unable to set logfile name/path for QuarkusTests

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#10202]
**Describe the bug**
When executing tests (via maven surefire), `quarkus.log.file.enable=true` (via `-D` or `application.properties`/`.yaml`) enables logging to `target/quarkus.log` (default). So far so good.
But setting `quarkus.log.file.path=quarkus-test.log` has _no_ effect, Quarkus always seems to log to `quarkus.log` for tests.

**Expected behavior**
`quarkus.log.file.path` shoul be picked up just as it is being picked up in dev-mode etc.

**Actual behavior**
When file logging is activated, test _always_ log to `quarkus.log`, not the configured file.

**To Reproduce**
1. Clone https://github.com/quarkusio/quarkus-quickstarts
2. `cd getting-started`
3. `mvn clean test -Dquarkus.log.file.enable=true -Dquarkus.log.file.path=quarkus-test.log` (or create a corresponding `application.properties`)

**Configuration**
```properties
quarkus.log.file.enable=true
quarkus.log.file.path=quarkus-test.log
```

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
    ```MINGW64_NT-10.0-18363 XXX 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys```
 - Output of `java -version`:
    ```
    openjdk version "11.0.7" 2020-04-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
    ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `1.4.2.Final` or `1.5.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
`quarkus.log.file.rotation.file-suffix: .yyyy-MM-dd` seems to work as expected.

**Comment by famod** [comment]
cc @tkalmar & @harthorst

**Comment by famod** [comment]
I guess that explains it:
https://github.com/quarkusio/quarkus/blob/1.5.2.Final/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L367

https://github.com/quarkusio/quarkus/blob/1.5.2.Final/test-framework/common/src/main/java/io/quarkus/test/common/PropertyTestUtil.java

But why?

cc @geoand

**Comment by geoand** [comment]
> But why?

An oversight most likely. https://github.com/quarkusio/quarkus/pull/10205 should fix the issue (for system properties, for `application.properties` it doesn't have an effect)

**Comment by famod** [comment]
Oh wow, very quick PR. Thanks!

Do see any chance to make it work for app properties as well?

**Comment by geoand** [comment]
Yeah, we probably could make it work, but it's more work that I am not sure is worth the trouble 😁

**Comment by famod** [comment]
Thanks for (partially) fixing it!

> Yeah, we probably could make it work, but it's more work that I am not sure is worth the trouble

The thing is that I lost time trying to figure out what is going on and this might also happen to others.
I'll create another ticket then so that other users can find the problem more quickly.

**Comment by famod** [comment]
Just wanted to confirm that the system property is now working as expected. We are creating a `quarkus-test-X.log` per Maven Surefire test fork:
```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemPropertyVariables>
            <quarkus.log.file.path>quarkus-test-${surefire.forkNumber}.log</quarkus.log.file.path>
        </systemPropertyVariables>
    </configuration>
</plugin>
```

**Comment by geoand** [comment]
:+1:
