### ISSUE TITLE
Allow Quarkus Scheduler to handle concurrent execution

### ISSUE THREAD

**Issue by pcasaes** [quarkusio/quarkus#10203]
**Description**
According to the docs Quarkus Scheduler allows concurrent execution

https://quarkus.io/guides/scheduler
> The invocation of the scheduled method does not depend on the status or result of the previous invocation.

It would be nice to be able to prevent concurrent execution.

**Implementation ideas**

We can add a property to the `Scheduled` annotation that would control this. It would default to the concurrent behavior of course.

**Comment by mkouba** [comment]
Sounds reasonable. We could add `concurrentExecution() default true` to `@Scheduled`. For simple scheduler we'll add a mutable flag to the trigger. For Quartz this would be mapped to a job class annotated with `org.quartz.DisallowConcurrentExecution`.

**Comment by mkouba** [comment]
I've finished the implementation but I'm still struggling to write a proper test.

**Comment by mkouba** [comment]
Hm, actually the contract of `@DisallowConcurrentExecution` is a bit different compared to what I would expect. The job execution is not skipped but delayed until the previous job finished. That's a bit more complex to implement. We need to think about it...

**Comment by McIntozh** [comment]
Hi,
I postet a simmilar request some days ago, where, in a possible workaround, I received the wanted behaviour by adding the synchronized modifier to the scheduled method: https://github.com/quarkusio/quarkus/issues/9883

**Comment by mkouba** [comment]
I've created a draft PR here: https://github.com/quarkusio/quarkus/pull/10338

**Comment by mkouba** [comment]
@pcasaes @McIntozh does the aforementioned PR fix your problem?

**Comment by pcasaes** [comment]
Being able to SKIP is very much what I was looking for. Thank you!
