### ISSUE TITLE
Integration Tests for command mode apps

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#10212]
**Description**
Currently IT tests assumes the app being tested are a long running serving apps leaving users of command mode in the dark.

Right now if you add a `@NativeImageTest` it launches the command mode app which with zero arguments which then abruptly exits making the test fails as expected it launches.
 
I'm wondering if we should introduce a way to test command mode apps and I can see two variations - maybe both are interesting.

1) have some environment set to let the app know it is being run for testing - in that case the app could keep running and provide a way to interact with it for testing.

2) Make a more dedicated "CliTesting" integration where we inject something that can be used to run the app, give it parameters and then collect the output streams to do verification on.

Something like:

```

@CommandLineTest
class MyAppTestIT {

  @Inject Launcher launch;

  @Test
  void testNoArgs() {
	assert(-1, launch.runAndWait().exitcode());
  }

  @Test
  void testVersion() {
	var result = launch.runAndWait("--version");

	assert(0, result.exitcode());
	assertThat(result.out()).containsString("version: 1.0.2"));
  }


  @Test
  void testLongRunning() {
	var result = launch.run("some arg to make it long running");

	assertThat(result.out().<some code to express read stream, but timeout after 5 seconds>).containsString("some output");

	assertThat(result.signal(-9).exitCode(), -2); }

}

```

Writing this actually make me thing this kind of testing library would be useful outside of quarkus - but lets see where we bring it.

**Comment by janmaterne** [comment]
```
@Test
void testReadingFromStdin() {
    String stdin = """
        multiple
        lines
        to read
        from STDIN
    """; 
    var runningApp = launch.stdin(stdin).run("-copy-stdin2stdout");
    asserThat(runningApp.out())
        .is(stdin);
}
```


The Launcher provides a uniform API for interacting with a command mode application.
That launcher must be configured - most important: which class to start?

Multiple ideas:

1. Automatic
Searches the current classpath (project) for a class annotated with
`@io.quarkus.runtime.annotations.QuarkusMain`. Fail if there are more than one.

2. Specify the start class

```
@QuarkusMain // reuse the existing annotation
Class<?> clazz = MyMainClass.class;
```

3. Specify the whole application

```
@QuarkusMain // or reuse the name of Arquillian: @Deployment 
JarArchive createApp() {
    return ShrinkWrap...
} 
```
 

What else should the launcher do?
- starting the app
  -- provide command line arguments
  -- provide environment variables
  -- provide system properties
- redirecting STDIN from a kind of StringSupplier
- capturing STDOUT and STDERR
- wait until exit or keep it running
- sending signals to the app
- capturing the exit code

```
Launcher {
    Application startAsync(String... args) { ... }
    Application start(String... args) { ... }
    Launcher withEnvironment(String key, String value) { ... }
    Launcher withEnvironment(Map<String,String> env) { ... }
    Launcher withEnvironment(Properties env) { ... }
    Launcher withSystemProperty(String key, String value) { ... }
    Launcher withSystemProperties(Map<String,String> props) { ... }
    Launcher withSystemProperties(Properties props) { ... }
    Launcher redirectStderrToStdout() { ... }
}

Application {
    int exitCode() { ... }
    String out() { ... }
    String err() { ... }
    void signal(int value) { ... }
    boolean isRunning() { ... }
}
```

What should the launcher framework support?
- providing alternate cdi beans for overriding standard behaviour, e.g. mocking external network traffic

**Comment by AmsterdamFilho** [comment]
This would be very interesting to have. Is there any workaround for now?

**Comment by arvid-villen-adtoox** [comment]
+1
