### ISSUE TITLE
Update Rest Client Guide on how to register a provider

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#10224]
**Description**
Update [Rest Client Guide](https://quarkus.io/guides/rest-client) on how to intercept Rest Client API calls by registering a provider.

**Implementation ideas**
Per [this Zulip thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/RestClient.20Intercept.20request), brief topic description and [link to the RestEASY docs](https://docs.jboss.org/resteasy/docs/4.5.5.Final/userguide/html_single/index.html#d4e3775).

I'll submit a pull request.

**Comment by geoand** [comment]
The docs now contain the necessary [info](https://quarkus.io/guides/rest-client-reactive#customizing-the-request).
