### ISSUE TITLE
Dev-mode: Add property/parameter to define extra files to watch for changes

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#10234]
**Description**
As discussed here with @geoand: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Dev.20mode.20not.20reloading.20.22application-shared.2Eyaml.22/near/198171450

> I wonder if it makes sense to expose an property that would take a list of extra files that should be watched in dev mode

**Implementation ideas**
AFAICS a regex would be the most versatile solution. Or even a list of regex.

**Comment by gsmet** [comment]
I think I would stick to the existing mechanism (i.e. no regexps, just a simple path) for a first version.

That would be quite easy to do IMHO.

**Comment by famod** [comment]
I left posted some questions about this in the chat: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/BuildStep.20based.20on.20config.3F.20(implementing.20.2310234)
