### ISSUE TITLE
quarkus.log.file.path cannot be set for QuarkusTests via application.properties or .yaml

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#10233]
See #10202 which contains all necessary context and info.

The PR for #10202 fixed `-Dquarkus.log.file.path=...`, but not configuration via application.properties or .yaml (https://github.com/quarkusio/quarkus/issues/10202#issuecomment-648659695).

**Comment by geoand** [comment]
Is this still an issue?

**Comment by famod** [comment]
Seems to have been fixed for a very long time, given that I went all the way back to 3.9 and still couldn't reproduce.

**Comment by geoand** [comment]
🎉
