### ISSUE TITLE
Difficulty in endpoint Authentication with JWT

### ISSUE THREAD

**Issue by danilomeneghel** [quarkusio/quarkus#10241]
I can generate the token, however when passing the token in the header to access the other page, it does not authenticate.
Here is my code:

> String token = service.generateUserToken (existingUser.email, lg.name);

> return Response.created (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer" + token) .build ();

I also tried to do it in another way, saving the token in the Session, but I couldn't do it either.

> request.getSession (). setAttribute ("token", token);

I did it that way, only that the error in HttpServletRequest and Quarkus doesn't recognize it.

`
RESTEASY003880: Unable to find contextual data of type: javax.servlet.http.HttpServletRequest
`

Does anyone know how to login (complete) using JWT on Quarkus?

I've spent hours searching the internet for ways to do this, but the codes are incomplete, they only show tests via the terminal and it doesn't show how to do this in the App.

**Comment by sberyozkin** [comment]
I think you need to either use `quarkus-oidc`, example, https://quarkus.io/guides/security-openid-connect-web-authentication, or set this JWT as a cookie. @stuartwdouglas has some ideas discussed at the forum

**Comment by danilomeneghel** [comment]
Thanks for the reply sberyozkin!

However, I still don't understand how to do it heheheh

I test my code on Postman and it's working fine.
You are logging in and after generating token, so much so that if I take that same token, go Postman and put in the Header "Authorization" and "Bearer TOKEN" the page loads in the body, including the user's name.

Except that when I'm going to test this on my App, it doesn't load the page after login :(

HTTP ERROR 401

Any good souls who know how to do this simply?

I tested it in another way and it didn't work either.

> return Response.seeOther (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer" + token) .build ();

**Comment by tkalmar** [comment]
> > return Response.seeOther (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer" + token) .build ();
Isn`t there an space missing between Bearer and token?
`return Response.seeOther (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer " + token) .build ();`

**Comment by sberyozkin** [comment]
`Authorization` is sent by the client, it is not returned by the server as part of the redirect

**Comment by sberyozkin** [comment]
@danilomeneghel See the comment above, you can't use `Authorization` to return the token to the browser and expect it be auto-propagated back. So, you can 1) return it for example as part of the service response body, ex, `{"token":"..."}` or 2) set is as a cookie 3) or rely on the Quarkus OIDC or in the simpler cases on Form auth...

**Comment by danilomeneghel** [comment]
Hi tkalmar
`Isn't there an space missing between Bearer and token?`

I put the space, yes, it is that here when commenting, it did not appear.

> > return Response.seeOther (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer" + token) .build ();
> 
> Isn't there an space missing between Bearer and token?
> `return Response.seeOther (URI.create ("/")). header (HttpHeaders.AUTHORIZATION, "Bearer " + token) .build ();`

**Comment by danilomeneghel** [comment]
> @danilomeneghel See the comment above, you can't use `Authorization` to return the token to the browser and expect it be auto-propagated back. So, you can 1) return it for example as part of the service response body, ex, `{"token":"..."}` or 2) set is as a cookie 3) or rely on the Quarkus OIDC or in the simpler cases on Form auth...

Okay, the difficulty is getting Java to "read" this token to free access to the protected endpoint.
If simply just adding the token to Json's body won't do anything, I need to throw it in the Header so that the other endpoint receives and authenticates.

As I understand it, it will not be possible to do this only using Java (at least in Quarkus), you will have to use Javascript, for example, to throw this token in the browser header and thus load the page, is that it?

**Comment by sberyozkin** [comment]
Returning JSON will require some script processing and then posting the token back. You can put it into header but it has to be a set-cookie if you want the other service to pick it up as Cookie. 
I think we can close this issue, you prefer to have some custom solution, so there is not much Quarkus itself can do. Agreed ?

**Comment by danilomeneghel** [comment]
OK, thanks for the help.

I am trying to do this now by sending the token via javascript (using Jquery), however I am having problems with CORS.
I have already enabled it in application.properties and I have also put it in jquery, but apparently it is not working.
Every time I try to send the form data to the backend (java) via ajax (jquery), in the browser I return the following error:
Status Code: 405 Method Not Allowed

Can you tell me how it can be done to correct this?

**Comment by sberyozkin** [comment]
@danilomeneghel No problems. I propose to move the conversation to the Zulip users forum now. 405 is not really a CORS error, sounds like a HTTP method mismatch, given that you enable CORS (incl all the methods probably).
Thanks
