### ISSUE TITLE
REST Client does not encode multi character code points correctly

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#10245]
If you attempt to encode a string that contains code points that don't fit into a single char (e.g. emojis) RESTEasy will fail to encode it correctly.

**Comment by jaikiran** [comment]
Hello @stuartwdouglas, I guess this is in context of https://github.com/quarkusio/quarkus/issues/10134?

**Comment by stuartwdouglas** [comment]
Oops, I did not realize there was already an issue for it.

**Comment by haseemisaac** [comment]
Hi @stuartwdouglas, has this been fixed? If not in the mean time, what would be the way to go around it?

**Comment by stuartwdouglas** [comment]
It won't be fixed until there is a RESTEasy release that includes my PR and this is integrated into Quarkus.

**Comment by gastaldi** [comment]
Fixed in 1.9.0.CR1 with 6c08bcdbe906fec6c30a68631aca59400ced9ec6
