### ISSUE TITLE
quarkus-oidc causes java.lang.ClassFormatError when using @RolesAllowed annotation and application-type 'web-app'

### ISSUE THREAD

**Issue by sschellh** [quarkusio/quarkus#10255]
Running the [quarkus-oidc example](https://quarkus.io/guides/security-openid-connect) results in `java.lang.ClassFormatError`. 
This seems to be related to the `@RolesAllowed` annotation.

## Java Version

> openjdk version "11.0.7" 2020-04-14 LTS
> OpenJDK Runtime Environment Zulu11.39+16-SA (build 11.0.7+10-LTS)
> OpenJDK 64-Bit Server VM Zulu11.39+16-SA (build 11.0.7+10-LTS, mixed mode)

#### 1) Checkout the example project on https://quarkus.io/guides/security-openid-connect
```
mvn io.quarkus:quarkus-maven-plugin:1.5.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=security-openid-connect-quickstart \
    -Dextensions="oidc, resteasy-jsonb"
cd security-openid-connect-quickstart
```

#### 2) Configure OIDC (using KeyCloak)
```
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/master
quarkus.oidc.token.issuer=http://localhost:8180/auth/realms/master
quarkus.oidc.client-id=****
quarkus.oidc.credentials.secret=****
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.application-type=web-app
```

#### 3) Compile and run the application
`mvn package && java -jar target/my-application-runner.jar`

This results in the following error:

> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>         at java.base/java.lang.Class.newInstance(Class.java:584)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
>         at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
> Caused by: java.lang.RuntimeException: Failed to start quarkus
>         at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:166)
>         ... 9 more
> Caused by: java.lang.RuntimeException: Failed to initialize Arc
>         at io.quarkus.arc.Arc.initialize(Arc.java:26)
>         at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:35)
>         at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy_0(ArcProcessor$generateResources-1120260799.zig:72)
>         at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy(ArcProcessor$generateResources-1120260799.zig:36)
>         at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:133)
>         ... 9 more
> Caused by: java.lang.ClassFormatError: Illegal class name "/UserResource_Subclass" in class file UserResource_Bean
>         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
>         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>         at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:414)
>         at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
>         at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:106)
>         at io.quarkus.arc.Arc.initialize(Arc.java:20)
>         ... 13 more

## Observation

When you remove the `@RolesAllowed` annotation, then the example works as expected.

**Comment by sberyozkin** [comment]
@sschellh I can't reproduce it with these settings:
```
export GRAALVM_HOME=~/work/graalvm-ce-java11-20.1.0
export JAVA_HOME=$GRAALVM_HOME
```
The only difference is that I copied the application.properties from the existing quickstart because they point to the `quarkus` realm, but it does not really matter.
What GraalVM version do you use ?

**Comment by sberyozkin** [comment]
@sschellh I can't reproduce it with these settings:
```
export GRAALVM_HOME=~/work/graalvm-ce-java11-20.1.0
export JAVA_HOME=$GRAALVM_HOME
```
The only difference is that I copied the application.properties from the existing quickstart because they point to the `quarkus` realm, but it does not really matter.
What GraalVM version do you use ?

**Comment by sschellh** [comment]
@sberyozkin I did not use it in native mode, but JVM mode.

**Comment by sberyozkin** [comment]
@sschellh Me too, It is still the JVM mode, just the stock java 11 shipped with the GraalVM is used.

**Comment by sberyozkin** [comment]
Can you try it too ?

**Comment by sschellh** [comment]
@sberyozkin Changing to `OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)` made no difference.

However, I noticed that in my demo project, I had the `UsersResource` in the root folder. When moving it into any package (e.g. `com.example`), the error is gone.

**Comment by sberyozkin** [comment]
@sschellh thanks. I'm not sure we should keep this issue open. @gsmet @mkouba, should Quarkus support the user code in the root package ? Or we say that the user code must be in some package ?

**Comment by sberyozkin** [comment]
Hi @sschellh Let me close this one. I think it is fair to say that the users will want their classes be packaged-scoped :-), if you'd like, please consider creating a dedicated issue about the root-package and the class transform issue. Thank you

**Comment by mkouba** [comment]
> should Quarkus support the user code in the root package ?

Well, it's not forbidden but I would strongly encourage all users to avoid using the unnamed packages because it could break things and brings no additional benefits.
