### ISSUE TITLE
LDAP Security - configuration needs to be modifiable at runtime

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#10259]
**Description**
See https://quarkus.io/guides/security-ldap#configuration-reference  

All properties are fixed at build time.  But in a realistic enterprise, these will differ between dev preprod prod environments (otherwise your dev credentials would also work in prod).  There will be individual server URLs with individual bind credentials,  users and groups are probably stored in different placess o the base dn's and filters will differ, etc..

As a bonus, the bind credentials should not be required, ldap has the concept of an anonymous bind.
-> quarkus.security.ldap.dir-context.principal and quarkus.security.ldap.dir-context.password can be null

**Comment by hartimcwildfly** [comment]
This is a presentation error. The config can be changed at runtime. Even if the documentation says it's fixed at build time. I don't know why this is the case.

On your second point I fully aggree.

**Comment by gsmet** [comment]
Could you try https://github.com/quarkusio/quarkus/pull/10334 ?

Tips from https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master might be useful in order to test the PR.

**Comment by hyperman1** [comment]
I can't try much.  Our corporate proxy does not allow acces to your snapshots or git.  I'll see if I can find a workaround
