### ISSUE TITLE
quarkus.kubernetes.annotations gets not applied to ingress

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#10260]
**Describe the bug**
I'm using the kubernetes extension to deploy to kubernetes. 
I'm setting `expose` to `true` to get an ingress resource generated (`target/kubernetes/kubernetes.xml`).
My annotation `quarkus.kubernetes.annotations."kubernetes.io/ingress.class"=addon-http-application-routing` gets not applied to the generated ingress but to all other resources.

**Expected behavior**
Labels and annotations gets applied to ingress too.

**Actual behavior**
Can not apply annotations via application.properties to generated ingress resource.

**To Reproduce**
1. Bootstrap a new Quarkus project using the kubernetes extension
2. Add the following application.properties

```
quarkus.kubernetes.deployment-target=kubernetes
quarkus.kubernetes.expose=true
quarkus.kubernetes.annotations."kubernetes.io/ingress.class"=addon-http-application-routing
```

3. Call maven `mvn package`
4. Open `target/kubernetes/kubernetes.xml` file to see the generated resources.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.5.2.Final

**Comment by geoand** [comment]
Good catch!

**Comment by haraldatbmw** [comment]
I think same is true for openshifts route.

**Comment by geoand** [comment]
@iocanel I tried to add this in Quarkus, but ran into various issues, so I think it should be handled in dekorate (which is the correct approach anyway)

**Comment by geoand** [comment]
> I think same is true for openshifts route.

Yeah, and if I'm not mistaken, I think the custom labels are also missing

**Comment by iocanel** [comment]
Most probably the decorators are executed out of order. I'll have a look.
