### ISSUE TITLE
Upgrade Yasson to a version not raising JDK warnings

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10273]
See 
https://github.com/eclipse-ee4j/yasson/issues/412

Either 1.0.8+
Or the 2.x series

**Comment by gastaldi** [comment]
It looks like 1.0.8 is not released yet. Is it possible to cut a release with this fix @aguibert ?

**Comment by aguibert** [comment]
yep, I can work on a release within the next week or so.

It will be 1.0.8, since the 2.x series uses the `jakarta.*` package namespace and wont' be officially released for a few more months

**Comment by aguibert** [comment]
Yasson 1.0.8 is released this morning and we should be seeing a PR from dependabot within the next 24 hours
