### ISSUE TITLE
Introduce config refresh for consul-config

### ISSUE THREAD

**Issue by crissi98** [quarkusio/quarkus#10287]
**Description**
There should be a way to refresh the runtime configuration read from consul without needing to restart the application.

**Implementation ideas**
You can use ```javax.inject.Provider``` to inject properties that should be changeable at runtime. With that, only the ConfigSources created by consul-config need to have a refresh mechanism.
IMO there are two ways to implement such a refresh mechanism:
1. Using TimeToLive (TTL) - When you access a config source, you need to check if the TTL of the config has expired. If so, reload the config from consul.
2. Introduce a refresh-Endpoint - The config is refreshed when a request happens to said input. This is particularly interesting in combination with consul, since you can define so called watches in consul, that notify the application automatically when its config was changed.

**Implementation proposal**
I implemented both ways to refresh the config here: https://github.com/crissi98/quarkus/tree/consul-config-refresh/extensions/consul-config. It is already tested in java- and native mode and I can provide a PR if you want.

**Comment by geoand** [comment]
Thanks for taking the time to look into this. From our side, we are somewhat reluctant to add such a feature.

**Comment by crissi98** [comment]
Ok, I understand but what do you mean by "people will expect configuration wherever it's being used". Do you mean they think it is updated everywhere, even without using the ```javax.inject.Provider```?

**Comment by geoand** [comment]
Yes exactly

**Comment by crissi98** [comment]
Ok, but wouldn‘t it be ok, if you describe the behavior in the Javadoc for the required properties and to extend the guide for the extension?

**Comment by geoand** [comment]
I personally don't think it will be enough. Moreover no other config source provides this capability, so it would be very confusing IMHO.

But here is my suggestion: send and email to the quarkus-dev mailing list and describe what you are trying to do (and link to this discussion).
That way you can get more opinions on the matter.

**Comment by crissi98** [comment]
Closing this after discussion on quarkus-dev mailing list: https://groups.google.com/forum/#!topic/quarkus-dev/eUDWv19kVMI

@geoand Thanks for taking your time looking into this. I hope I didn´t annoy you too much with this

**Comment by geoand** [comment]
> @geoand Thanks for taking your time looking into this. I hope I didn´t annoy you too much with this

Not at all! Thanks for reporting and taking the time to discuss the issue on the mailign list as well
