### ISSUE TITLE
RequestScoped beans keeping property values from previous requests when using kotlin.

### ISSUE THREAD

**Issue by leandrobortoli** [quarkusio/quarkus#10290]
**Describe the bug**
When using kotlin and injecting a RequestScoped bean, on each new request a new bean instance is initialized, but for some reason, the property values from the previous request bean are kept, this seems to be an issue only with the kotlin extension, because I couldn't reproduce the issue using Java.

**Expected behavior**
The new request bean should not contain previous property values

**Actual behavior**
A new bean instance is created on each request, but the same property values from previous requests are propagated.

**To Reproduce**
I've created a project to reproduce the issue here: [https://github.com/leandrobortoli/quarkus-issue-request-scoped](https://github.com/leandrobortoli/quarkus-issue-request-scoped)

On each request, it checks if the bean property has been initialized and if not initializes it with a random value, as a result, we can see that only the first request initializes the properties and the values are propagated in the subsequent requests.

```
@Path("/ping")
class PingController {

    @Inject
    lateinit var requestScopedBean: RequestScopedBean

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun ping(): String {
        if(requestScopedBean.myProperty == null) {
            println("Setting requestScopedBean.myProperty")
            requestScopedBean.myProperty = java.util.Random().nextInt()
        }
        if(requestScopedBean.myStringProperty == null) {
            println("Setting requestScopedBean.myStringProperty")
            requestScopedBean.myStringProperty = StringUtils.randomString()
        }
        println("requestScopedBean ref: $requestScopedBean")
        println("requestScopedBean.myProperty: ${requestScopedBean.myProperty}")
        println("requestScopedBean.myStringProperty: ${requestScopedBean.myStringProperty}")
        return "pong"
    }
}
```

```
@RequestScoped
open class RequestScopedBean {

    var myProperty: Int? = null
    var myStringProperty: String? = null

    init {
        println("Initializing RequestScopedBean")
    }
}
```

**Screenshots**
OUTPUT WITH 3 CONSECUTIVE REQUESTS:
![image](https://user-images.githubusercontent.com/1148245/85818991-2b45b500-b740-11ea-91f1-a6fc71b251a1.png)

**Environment (please complete the following information):**
 - Microsoft Windows [Version 10.0.18362.900]
 -Java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
 - Quarkus version 1.5.2.Final
 - Gradle 6.4.1

**Comment by mkouba** [comment]
It's very likely that you get/set the values from the client proxy and not the real bean instance. I'm no kotlin expert but I thought that kotlin generates getters/setters for properties automatically, i.e. `if(requestScopedBean.myProperty == null)` is translated to something like `if(requestScopedBean.getMyProperty() == null)`. @geoand Any idea?

**Comment by geoand** [comment]
Sounds reasonable @mkouba although I don't know exactly why that would be happening - we would need to look at the bytecode.

@evanchooly do you plan to look at this or should I check it out when I have some time?

**Comment by evanchooly** [comment]
I can dig in to it but wouldn't be bothered if you got there first.  I have a bit of a back log but I'm about to take a big one off that list.

**Comment by geoand** [comment]
I'll see if I can squeze it in sometime next week. I'll update here in any case.

**Comment by leandrobortoli** [comment]
When doing some more tests, I validated that when injecting a bean interface instead of the implementation, the problem does not seem to occur.

**Comment by youngplugins** [comment]
Hi there. Im new here, and use your wonderfull software.

I can verify the same  problem also happens with @SessionScoped.

@leandrobortoli , may I ask, how do you inject a bean interface, instead of implementation?

**Comment by geoand** [comment]
I am pretty sure I can come up with a fix for this one. Will let you know by tomorrow

**Comment by geoand** [comment]
#10497 takes care of the issue
