### ISSUE TITLE
Quarkus kubernetes sidecars configs do not work 

### ISSUE THREAD

**Issue by vishalgoel1988** [quarkusio/quarkus#10308]
**Describe the bug**
Hi,

I am trying to generate sidecar configs using quarkus application.properties. I have below in my application.properties.

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

It is supposed to configure abc sidecontainer in kubernetes.yml. But it is not. Main app container is correctly there along with other manifests (e.g. Service, ServiceAccount etc.) in the kubernetes.yml
Is there any issue with my properties? or it is not supported in Quarkus.

Reference:
https://quarkus.io/guides/deploying-to-kubernetes

**Expected behavior**
Sidecar container should be created in kubernetes.yml

**Actual behavior**
No sidecar container is created in kubernetes.yml

**To Reproduce**
1. Copy below configs in application.properties of a quarkus kubernetes project

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

2.Build the project 

**Configuration**
```properties

quarkus.kubernetes.sidecars.abc.image=def/abc
quarkus.kubernetes.sidecars.abc.ports[0].containerPort=3000
quarkus.kubernetes.sidecars.abc.arguments[0]=--config=/etc/abc/abc.conf
quarkus.kubernetes.sidecars.abc.mount[0].path=/etc/abc

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Hi,

I don't think we support sidecar generation, may I ask what made you think we do?

**Comment by vishalgoel1988** [comment]
Hi,

Please check reference in my question: https://quarkus.io/guides/deploying-to-kubernetes
This has configs for sidecar deployment:

quarkus.kubernetes.sidecars | Map<String, Container>

**Comment by geoand** [comment]
That looks like a bug in the documentation then. @iocanel I assume it was added by accident?

**Comment by vishalgoel1988** [comment]
Just curious that dekorate provides the sidecar functionality. Should it be not included in quarkus automatically?

**Comment by geoand** [comment]
Not all things from dekorate work (nor do we want all of them to). We pick
and choose what we want.

In this case, I think we just overlooked the sidecar configuration

**Comment by vishalgoel1988** [comment]
Ok.

Is it possible to have it in next release. This is quite helpful.

**Comment by geoand** [comment]
I am not sure we can make it for 1.6, most likely it will be 1.7

**Comment by vishalgoel1988** [comment]
Ok.
Is there any expected release date for 1.7?

**Comment by geoand** [comment]
Should be early August if all goes well

**Comment by geoand** [comment]
What's more, the properties aren't even using the proper syntax. 
@iocanel this should just be a matter of defining the configuration and adding the proper decorators right? If possible, I would like to fix this in time for 1.6 since we already have it in the docs.
I just need your confirmation that there is nothing more to it before starting to look into it.

**Comment by vishalgoel1988** [comment]
Hi @geoand 
Can you please help in correcting the syntax?

**Comment by geoand** [comment]
There is no correct syntax yet, because there is no dedicated configuration support for sidecars. But I assume it will be similar to what we have with env vars

**Comment by vishalgoel1988** [comment]
Ok.
Also, following property creates a volume in yml but with defaultMode=384 (I think dekorate has it set as 384), though quarkus documentation says default is 0600.
quarkus.kubernetes.config-map-volumes.keycloak-config1-volume.config-map-name=config1

It would be really helpful if we can get sidecars configs in 1.6

Thanks.

**Comment by geoand** [comment]
@vishalgoel1988 the issue should be fixed in #10333.

See https://github.com/geoand/quarkus/blob/ae5485672bddfe66f710dfd766ee80dfb1ef02c8/integration-tests/kubernetes/quarkus-standard-way/src/test/resources/kubernetes-with-sidecar-and-jib.properties to see what the proper use of `sidecars` should be (after the PR has been merged).

**Comment by vishalgoel1988** [comment]
Thanks @geoand 
One little question. How can we give multiple arguments? by comma separated?

quarkus.kubernetes.sidecars.sc.arguments=-a,-b

**Comment by geoand** [comment]
> quarkus.kubernetes.sidecars.sc.arguments=-a,-b

Exactly
