### ISSUE TITLE
Unable to perform a count operation on a named query

### ISSUE THREAD

**Issue by fwgreen** [quarkusio/quarkus#10319]
This is probably less of a bug and more of a gap in my Hibernate/HQL knowledge.  Basically my named query works with `find` but throws when I add `count`.
```Java
@Entity
@DiscriminatorValue("RN")
@NamedQuery(name="Nurse.available", 
            query="select n from Nurse n, Availability av where n.id = av.teamMember and av.onShift = true")
public class Nurse extends TeamMember {

    public static List<Nurse> onShift() {
        return find("#Nurse.available"); //works fine
    }

    public static long onShiftCount() {
        return find("#Nurse.available").count(); //throws exception
    }
}
```
```
org.jboss.resteasy.spi.UnhandledException: io.quarkus.panache.common.exception.PanacheQueryException: Unable to perform a count operation on a named query
```
The immediate workaround to use the query directly:
```Java
public static long onShiftCount() {
    return find("select n from Nurse n, Availability av where n.id = av.teamMember and av.onShift = true").count(); //this works!
}
```

Java 14
Quarkus 1.5.2

**Comment by geoand** [comment]
cc @Sanne

**Comment by Sanne** [comment]
I'll pass it to @FroMage  :)

**Comment by FroMage** [comment]
Yeah, the way we handle them is not by replacing the body of the method with the text of the query, but just passing it on to ORM, which doesn't support that.

Now, granted, in some cases we could actually make this work by using the named query text itself and applying the same transformation we do for regular queries to be able to count them.

@loicmathieu since you did the named queries, would you be interested in looking at this?

**Comment by loicmathieu** [comment]
I can have a look.

Another implementation would be to offer the user a way to pass it's own countQuery, but this will defeat the simplicity of Panache regarding the `count()` method.

**Comment by GithubSre** [comment]
io.quarkus.panache.common.exception.PanacheQueryException: The named query must be defined on your JPA entity or one of its super classes. Does anyone know how to fix this?

**Comment by GithubSre** [comment]
if yes please let me know.

**Comment by loicmathieu** [comment]
@GithubSre this means that the named query annotation was not found.

This issue is closed, please ask on stackoverfow or Zulip for help or open a new issue with a reproducer.

**Comment by GithubSre** [comment]
thanks @loicmathieu

**Comment by GithubSre** [comment]
this helped solve the problem.
Thanks @loicmathieu.
