### ISSUE TITLE
Error: Image build request failed with exit status 137 - Linux Mint

### ISSUE THREAD

**Issue by arilsonsantos** [quarkusio/quarkus#10318]
**Describe the bug**
Error when try to generate a native image. I have been a lot of messages like that but with Windows or IOS

![quarkus_error](https://user-images.githubusercontent.com/1520348/85913903-46332a80-b80f-11ea-99ed-c6516f6ddb84.png)

In the IOS I have needed to change Docker memory and I works, but now Im using Linux... I thought It would be faster and I also thought that it  wouldn't have that problem again

---
 - GraalVM version 19.3.1
 - Quarkus version 1.5.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/arilson/desenvolvimento/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /home/arilson/.sdkman/candidates/java/19.3.1.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-39-generic", arch: "amd64", family: "unix"

**Comment by littlebeeper** [comment]
Hi @arilsonsantos 

Exit status 137 indicates an out of memory error. 
Could you please try increasing quarkus xmx value (quarkus.native.native-image-xmx) for native image generation?

**Comment by gsmet** [comment]
Yeah, it's definitely the usual OOM issue. I'm closing this one as it's really about local configuration.
