### ISSUE TITLE
Webjars-locator only works in quarkus:dev mode

### ISSUE THREAD

**Issue by mejlholm** [quarkusio/quarkus#10313]
**Describe the bug**
New extension quarkus-webjars-locator in 1.6.0.CR1 should be fairly straightforward to use. It works as expected in 
quarkus:dev mode, but in a jar/docker container it doesn't seem to work (if I'm not missing something). 

Reproducer can be found here: 
https://github.com/mejlholm/webjars-locator-reproducer

**Expected behavior**
Web application on localhost:9080/index.html finds all webjar included dependencies without versions. 

**Actual behavior**
404 - not found. 

**To Reproduce**
Build and run jar/container.

**Configuration**
Nothing special.

**Screenshots**
In dev mode
![billede](https://user-images.githubusercontent.com/31166597/85883369-27b63a80-b7e1-11ea-8875-3e7c8f5cdb9a.png)
In jar/docker container
![billede](https://user-images.githubusercontent.com/31166597/85883422-3ef52800-b7e1-11ea-9038-8c7a8df07bb9.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Microsoft Windows [Version 10.0.19041.329]

 - Output of `java -version`: 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

 - Quarkus version or git rev: 
1.6.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: C:\dev\tools\apache-maven-3.6.2\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: en_US, platform encoding: Cp1252

OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
(Add any other context about the problem here.)

**Comment by gastaldi** [comment]
I can confirm I can reproduce this problem in Fedora 32

**Comment by gastaldi** [comment]
@mejlholm [This PR](https://github.com/quarkusio/quarkus/pull/10317) should fix your issue, please give it a try and let me know how it goes. 

Thanks!

**Comment by mejlholm** [comment]
@gastaldi the PR fixes the issue for me.

**Comment by gastaldi** [comment]
Thanks for checking
