### ISSUE TITLE
enable promtheus scraping when using metrics

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#10336]
**Description**
Discussed in https://groups.google.com/g/quarkus-dev/c/WqvGjKIOXrE/m/esRFB6LJAQAJ?pli=1 it was noticed that when enabling metrics and kubernetes/openshift it was still necessary to go and add prometheus annotations to see scraping.

**Implementation ideas**
hook into dekorate and generate the proper annotations (check if differences between prometheus in openshift and plain kubernetes).

**Comment by geoand** [comment]
@survivant pointed me to #10301, so I'll close this as a duplicate
