### ISSUE TITLE
Unexpected sequence generator behaviour on existing database table

### ISSUE THREAD

**Issue by florian-schneider-40** [quarkusio/quarkus#10331]
**Describe the bug**
We have a simple entity (it does not inherit from PanacheEntity) that has a SequenceGenerator annotation. It used to work but all of a sudden it is returning values that are lower than the current value of the database sequence in our PostgreSQL database.

```
@Entity
@Table(name = "T_EXAMPLE")
@SequenceGenerator(name = "seq", sequenceName = "S_EXAMPLE")
public class Example implements Serializable {
....
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    private Long id;
```

**Expected behavior**
We expect that the sequence generator is in sync with the respective database sequence.

**Actual behavior**
The current value of our sequence in the database is 935, but the service attempts to create new records with id e.g. 890.

**To Reproduce**
Currently not possible to specify.

**Configuration**
```properties
# GLOBAL
quarkus.datasource.driver=org.postgresql.Driver
quarkus.flyway.schemas=some_svc
quarkus.hibernate-orm.database.default-schema=some_svc


# Activate in case of using flyway
quarkus.flyway.baseline-version=1.0.0
quarkus.flyway.baseline-description=Initial version
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.table=[redacted]_FLYWAY_METADATA


quarkus.resteasy.path=/api

```
**Environment**
 - OS: Alpine Linux 3.8
 - GraalVM: 19.1.1
 - Hibernate: 5.1.0
 - Flyway: 6.3.3
 - Quarkus version: 1.4.2

**Comment by gsmet** [comment]
By any chance did you load data manually leading to the sequence to be incremented outside of Hibernate ORM? IIRC, sequences are by default allocated 50 by 50 and that could lead to this issue.

**Comment by florian-schneider-40** [comment]
I fear I can't rule out somebody did this. Do you see a way to address the issue anyhow?

**Comment by gsmet** [comment]
First thing I would do would be to set the `allocationSize` of the `SequenceGenerator` to 1 and then restart everything properly.

**Comment by florian-schneider-40** [comment]
Thanks, that did it! So not really a Quarkus issue but rather our  switch to Hibernate (implicitly via Quarkus) on a prepopulated database.
