### ISSUE TITLE
http codes when returning possibly null Uni or empty Multi in reasteasy?

### ISSUE THREAD

**Issue by obbyK** [quarkusio/quarkus#10340]
I have found out that returning a possibly null Uni returns http status 204 (no content) when using a get request such as `/users/123`. Shouldn't this return 404?

Where can I find docs for the http codes when returning a possibly null or empty Uni/Multi? How can i modify the http status codes when using mutiny before returning results? Here is the question at [stackoverflow](https://stackoverflow.com/questions/62613983/what-are-http-codes-when-returning-possibly-null-uni-or-empty-multi-in-reasteasy), no answer yet there.

**Comment by jaikiran** [comment]
Perhaps @cescoffier would know?

**Comment by cescoffier** [comment]
What's the behavior when your return `null` in a regular Jax-RS endpoint. It should do the same.

**Comment by obbyK** [comment]
Confirmed it is a `resteasy` implementation. Opted to throw a custom `webapplicationexception` with code 404.
