### ISSUE TITLE
Can't update a PanacheEntity converted from a @FormParam

### ISSUE THREAD

**Issue by fwgreen** [quarkusio/quarkus#10357]
Updates made to an `PanacheEntity` converted from a `@FormParam`, either using the `valueOf/fromString` approach or using a `ParamConverter` and `ParamConverterProvider`, are ignored.  No errors are thrown.  ~~Conversions from a `@PathParam` work as expected~~ (1.6.1).  On further reading, I thought this might be related to https://github.com/quarkusio/quarkus/issues/3261, as my form has only `boolean` fields, but it seems more like a variation on https://github.com/quarkusio/quarkus/issues/10466.

Quarkus 1.5.2
Java 14

**Comment by gsmet** [comment]
@fwgreen could you prepare a reproducer in the form of a simple Maven project? Thanks!

**Comment by fwgreen** [comment]
Here's an example using `@FormParam`: https://github.com/fwgreen/PathConversionTest.  The issue is in the DetailResource class.  Thanks for taking the time to look at this.

**Comment by stuartwdouglas** [comment]
The converter is invoked outside the scope of the current transaction, so the Person is a detached entity.

**Comment by fwgreen** [comment]
I'm wondering what was allowing `@PathParam` to work until recently.  Did Panache automatically merge the entity?

**Comment by stuartwdouglas** [comment]
I am surprised either of them worked at any point.

**Comment by fwgreen** [comment]
`@FormParam` never worked, just `@PathParam`, which is why I thought it was a bug.  At any rate, thanks for taking the to clear this up for me.  That said, if Panache automatically persists changes, why wasn't an exception thrown when I tried to alter a detached entity?

**Comment by fwgreen** [comment]
Closing this issue:  My root problem is design related and already under discussion here https://github.com/quarkusio/quarkus/issues/2244 and here https://github.com/quarkusio/quarkus/issues/3969
