### ISSUE TITLE
Override property quarkus.security.users.embedded.users.<username>

### ISSUE THREAD

**Issue by bindu-variam** [quarkusio/quarkus#10359]
**Description**
I have a quarkus based webapp that uses **Basic Authentication** with **Embedded Realm Configuration**. The webapp runs in a docker container. The authentication properties are specified in **application.properties** like this:

```
quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.test=mypass
quarkus.security.users.embedded.roles.test=admin
```
I would like to override **quarkus.security.users.embedded.users.test** to specify a password at docker runtime. 

I tried to do this by overriding the quarkus property using an environment variable at docker runtime.
```
docker run -p 9999:9999 -e QUARKUS_SECURITY_USERS_EMBEDDED_USERS_TEST=newpasswd mywebapp 
```
This does not work. When I access mywebapp using http://locahost:9999 I must login using **test/mypass**. I expected to login using **test/newpasswd**.

**Expected behavior**
When I access mywebapp using http://locahost:9999, I expected to login using **test/newpasswd**.

**Actual behavior**
When I access mywebapp using http://locahost:9999, I must login using **test/mypass**.

**To Reproduce**
See **Description**

**Configuration**
See **Description**

**Screenshots**
Not Applicable

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux L02520-Ubuntu 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
``` 
 - GraalVM version (if different from Java): 
```
None
```
 - Quarkus version or git rev: 
```
1.4.2.Final
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.2.1
------------------------------------------------------------

Build time:   2020-02-24 20:24:10 UTC
Revision:     aacbcb7e587faa6a8e7851751a76183b6187b164

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 5.3.0-61-generic amd64
```

**Additional context**
None

**Comment by geoand** [comment]
As can be seen in https://quarkus.io/guides/all-config#quarkus-elytron-security-properties-file_quarkus.security.users.embedded, the properties are **build time** properties, which means that they cannot be changed at runtime.

**Comment by sberyozkin** [comment]
Just to add to this issue, @bindu-variam, see https://quarkus.io/guides/security#identity-providers for the links to the production-quality identity providers, the embedded properties approach is for the testing only
