### ISSUE TITLE
Improve Security documentation to open a unauthenticated subpath

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10361]
As described in the documentation, I have globally set my api as authenticated:
quarkus.http.auth.permission.authenticated.paths=/api/*

Now however, for a webhook I need a public endpoint. The documentation was not clear (enough) that I needed to
open a path again like this:
quarkus.http.auth.permission.public.paths=/api/noauth/*

I was expecting it would be enough to just leave out the @Authenticated and allowed roles annotations from the open endpoint, but that doesn't work in case of a globally authenticated api path.

**Comment by MarcusBiel** [comment]
@sberyozkin @emmanuelbernard

**Comment by sberyozkin** [comment]
@MarcusBiel It will be fixed as part of #10937

**Comment by sberyozkin** [comment]
@MarcusBiel I've added this section to https://github.com/quarkusio/quarkus/pull/10937/files#diff-689b1c7c00fe208f51cb51c79d6a8949R86
