### ISSUE TITLE
Improve Authentication Documentation

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10363]
The Authentication documentation is spread over several separated guides:
https://quarkus.io/guides/security-jwt
https://quarkus.io/guides/security-openid-connect
https://quarkus.io/guides/security-openid-connect-web-authentication
https://quarkus.io/guides/security-openid-connect-multitenancy
https://quarkus.io/guides/security-keycloak-authorization
 https://quarkus.io/guides/security-oauth2

It's hard to follow, to see the differences, and a lot is still missing in the documentations,
especially about (integration) testing a secured endpoint.

**Comment by MarcusBiel** [comment]
@sberyozkin @emmanuelbernard

**Comment by albert0815** [comment]
We are also struggeling with implementing integration tests using Quarkus tests. We are currently using our central Keycloak instance to generate a token and then test the endpoint which is from my point of view not useful as part of maven integration tests. Actually I would like to avoid generating a token and somehow mock the authentication. But we didn't find a solution for this. In the quarkus samples for oidc there is also a communication with a oidc provider involved.

In addition it would also be useful to add some hints on how to use the integrated swagger-ui when using oidc.

**Comment by emmanuelbernard** [comment]
One option @sberyozkin could be to repurpose https://quarkus.io/guides/security so be a landing page for everything security. It would explain at high level the various options and then point to the specific guide. Thoughts?

**Comment by sberyozkin** [comment]
@emmanuelbernard, Hi,

> One option @sberyozkin could be to repurpose https://quarkus.io/guides/security so be a landing page for everything security. It would explain at high level the various options and then point to the specific guide

Does make sense. I'l take care of it once I finish some pending PRs.

In meantime, @MarcusBiel, here is a short summary:
1. https://quarkus.io/guides/security-openid-connect : Bearer token, JWT or opaque (from 1.6.0), is supplied with HTTP `Authorization` 
2. https://quarkus.io/guides/security-openid-connect-web-authentication : OIDC Authorization Code Flow, service gets both ID and access tokens, uses ID token to get the user info, can propagate AT to the downstream services, ID token is always JWT, AT - can be either JWT or opaque (from 1.6.0)
Both 1 and 2 verify the JWT tokens locally with the JWK key set fetched from OIDC server at the startup, starting from 1.6.0 - can verify both opaque/binary and JWT tokens against the OIDC introspection endpoint.   
3. https://quarkus.io/guides/security-openid-connect-multitenancy : multiple tenants, allows combining 1 and 2 dynamically or statically in a single service (ex - let your users login with Keycloak, Auth0, LinkedIn, Google, etc)
4. https://quarkus.io/guides/security-jwt - alternative to 1 and can only accept JWT (non opaque) tokens. Note both 1. and 2. use 3. to convert JWT tokens into MP JWT `JsonWebToken`
5. https://quarkus.io/guides/security-keycloak-authorization - it is built on top of 1 and is all about having the bearer token permissions be controlled by Keycloak server
6. https://quarkus.io/guides/security-oauth2 - light weight alternative to 1 to get the bearer tokens verified against the OAuth2/OIDC introspection endpoint. Until 1.6.0 it is the only option to verify the opaque/binary tokens

**Comment by MarcusBiel** [comment]
thanks

**Comment by sberyozkin** [comment]
Hi @MarcusBiel, @emmanuelbernard I've opened #10653 to resolve this issue. Note I think a dedicated PR of its own will have to be created to re-purpose the `security.adoc`, as there is much in Quarkus security beyond OIDC/OAuth2 (Vault, path based control, etc, etc). I'l deal with it in the next phase once the authentication docs are improved (they are now interlinked, their purpose is better described, etc)

**Comment by sberyozkin** [comment]
@MarcusBiel, @emmanuelbernard I'll CC you once I open a security page update PR
