### ISSUE TITLE
Explain how to configure embedded authentication for integration testing

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10364]
Would be great if you could extend the documentation so that it explains
how to set up an introspect endpoint of an OAuth2 server via Wiremock, as 
seen here:
https://github.com/quarkusio/quarkus/blob/master/integration-tests/elytron-security-oauth2/src/test/java/io/quarkus/it/elytron/oauth2/ElytronOauth2ExtensionResourceTestCase.java

@loicmathieu

**Comment by loicmathieu** [comment]
Thanks to report it. I'll take care of it.
