### ISSUE TITLE
Generated manage.sh script not executable

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#10386]
**Describe the bug**
When following the instructions in https://quarkus.io/guides/amazon-lambda#create-the-function, the generated manage.sh script is not executable.

**Expected behavior**
I can run the script.

**Actual behavior**
./target/manage.sh
zsh: permission denied: ./target/manage.sh

**To Reproduce**
Follow the guide

**Comment by gunnarmorling** [comment]
Slightly related: the invoke part of that script contains a call to _base64 -d_, which needs to be _base64 -D_ on macOS.

**Comment by ejba** [comment]
Hi, can I peek this one?

**Comment by jaikiran** [comment]
> Slightly related: the invoke part of that script contains a call to base64 -d, which needs to be base64 -D on macOS.

For me, on macOS, it seems that command supports both (and does the same thing):

```
base64 --help
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

**Comment by gunnarmorling** [comment]
Interesting, seems they added this recently then. For me only -d is supported.

```
base64 --help
Usage: base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

On the permission issue, the guide runs the commands via the `sh` command which circuments the issue. I still think it'd make sense to make that file executable.

**Comment by jaikiran** [comment]
> Interesting, seems they added this recently then. For me only -d is supported.

Perhaps better to use `--decode` then to avoid these version issues.

**Comment by ejba** [comment]
> Perhaps better to use --decode then to avoid these version issues.

Do you want me include this change in the PR?

**Comment by jaikiran** [comment]
> Do you want me include this change in the PR?

Better do it in a separate PR, IMO.
