### ISSUE TITLE
Field jaeger.version is empty when using quarkus-jaeger

### ISSUE THREAD

**Issue by ctron** [quarkusio/quarkus#10399]
**Describe the bug**
(Describe the problem clearly and concisely.)

The field `jaeger.version` is empty.

**Expected behavior**

The field should contain the version of the Jaeger tracing library.

**Actual behavior**

The field value is empty.

**To Reproduce**
1. Using qauarkus-jaeger
2. 
3. 

**Screenshots**

![image](https://user-images.githubusercontent.com/202474/86235850-60fff900-bb99-11ea-88cd-0d3f76189f73.png)

**Environment (please complete the following information):**

~~~
$ uname -a
Linux brocken 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode, sharing)
~~~

 - GraalVM version (if different from Java): 19.3.1
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

    ~~~
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: /home/jreimann/tools/maven/apache-maven-current
    Java version: 11.0.7, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc32.x86_64
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"
    ~~~

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
cc @pavolloffay

**Comment by pavolloffay** [comment]
This should be set to the version of the Jaeger client library.

**Comment by geoand** [comment]
Shouldn't that be done automatically?

**Comment by pavolloffay** [comment]
it should, there is bug in jaeger client or quarkus.

**Comment by geoand** [comment]
Do you plan to look into it @pavolloffay ?

**Comment by ctron** [comment]
I think this is the root cause: https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/graal/Target_JaegerTracer.java#L1-L14

**Comment by geoand** [comment]
@ctron oh... so this happens only in native mode?

**Comment by pavolloffay** [comment]
`io.jaegertracing.client.Version.get()` returns correct version for Jaeger 0.34.0 that is used in Quarkus. 

The version is obtained from properties file https://github.com/jaegertracing/jaeger-client-java/blob/release-0.34/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L672. The prop file should be in the jar. Can this cause any problems in Quarkus?

**Comment by geoand** [comment]
Based on what @ctron posted, I am assuming the problem only occurs in native mode and that JVM mode works fine.

Let me come up with a real quick fix for this so we can get it in 1.6

**Comment by geoand** [comment]
I have a fix, let me just write a quick test so we can be sure this doesn't break in the future

**Comment by geoand** [comment]
#10405 should fix the issue

**Comment by ctron** [comment]
> @ctron oh... so this happens only in native mode?

Indeed, sorry. I forgot to mention that.

**Comment by geoand** [comment]
No worries, I found out easily via testing.
