### ISSUE TITLE
Startup and memory performance hunt

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10409]
**Description**

The idea is to get a general performance hunt, especially in startup and memory usage.
Since we tend to add features, it's good to set up some tasks to hunt down some work to move things to build time etc.

It's inspired by one of @Sanne 's comment

**Comment by n1hility** [comment]
@Sanne has been doing a lot of work here recently. Using this to capture his work. After that's complete I think we should close this task.

**Comment by geoand** [comment]
@Sanne I know you do this work periodically. Do you think we should close this issue? I don't think it brings much value to have it hanging around

**Comment by Sanne** [comment]
Ok right let's close this as it doesn't fit very well with our work flow.

However to be clear while I've recently been looking at overall memory consumption and memory leaks, I haven't been checking startup times at all.
