### ISSUE TITLE
Loading native OpenCV library doesn't work with quarkusDev but with build

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#10448]
**Describe the bug**
To be able to use OpenCV in a Java application, you have to load the native library with `System.loadLibrary(Core.NATIVE_LIBRARY_NAME)`. I tried to do this in a basic quarkus service (see reproducer below). The library seems to be loaded (no error is thrown when `System.loadLibrary(...)` is called.

However, when running `gradlew quarkusDev`, the library is not available when it is actually used and then causes a crash with `Caused by: java.lang.UnsatisfiedLinkError: 'long org.opencv.core.Mat.n_Mat()'`. 

When running the same code as a jar application after it was build with `gradlew assemble`, everything works fine. 

**Expected behavior**
The native library loading should work fine with quarkusDev as well.

**Actual behavior**
Native library loading only works with a build of the quarkus application but fails with quarkusDev.

**To Reproduce**
1. Download the reproducer project and unzip it. 
[opencv-not-loading.zip](https://github.com/quarkusio/quarkus/files/4868545/opencv-not-loading.zip)
2. Install OpenCV 4.1.0 (it must be this version, because the java wrapper is built for this version). Have a look at the opencv installation instructions. For Windows, prebuilt binaries exist. For linux, you might have to build it from the sources. If so, make sure to include the Java wrapper.
3. In the reproducer project, run `OPENCV_SO=<PATH to the directory containing your opencv_java410.dll/libopencv_java410.so> ./gradlew quarkusDev`. The server tries to load the native libary and use it on startup (see `ServerMain.kt`). It will crash with an `java.lang.UnsatisfiedLinkError`.
4. Run `./gradlew assemble` and then `java -Djava.library.path=<PATH to the directory containing your opencv_java410.dll/libopencv_java410.so> -jar build\code-with-quarkus-1.0.0-SNAPSHOT-runner.jar`. The application starts and shows a log like the following

```
Going to load native library...
Did load native library.
Going to use native library...
2265572378912
Successfully used native library.
...
```

**Environment (please complete the following information):**
 - Windows 10 x64 
- Quarkus 1.5.2.Final & Quarkus 1.6.0.CR1
- OpenCV 4.1.0
- gradle
- Kotlin

**Comment by gsmet** [comment]
Any chance you would have the time to check if it's a Gradle-specific problem or also happens with Maven?

**Comment by andreas-eberle** [comment]
@gsmet: I just checked and it behaves the same with maven. While it works if you first package the application and run the jar, it doesn't work if you run `./mvnw quarkus:dev`.

**Comment by jaikiran** [comment]
Hello @andreas-eberle, given that reproducing this requires building OpenCV, could you paste the complete exception stacktrace that you see with quarkus:dev? That will make it easier for some of us to see if we can spot some obvious issues.

Furthermore, which vendor and version of Java are you using?

Finally, I see that you pass the `-Djava.library.path` to `java -jar` way of launching the app, but in `quarkus:dev` mode, I don't see you passing `-Djvm.args=-Djava.library.path=<PATH to the directory containing your opencv_java410.dll/libopencv_java410.so>`. Is that intentional? Have you tried passing it that?

**Comment by andreas-eberle** [comment]
@jaikiran: You can find the complete stacktrace of `./gradlew quarkusDev` here: https://gist.github.com/andreas-eberle/2c395658acbe363cf2316d27d750e73a

My JDK (`java -version`):
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

I pass in the java.library.path differently since just setting `java.library.path` for `./gradlew quarkusDev` only sets the library path for gradle but not for the actual application. Therefore I added a line in the gradle script adding the contents of the `OPENCV_SO` variable to the library path for the application. I verified that the path is actually set (if you don't set the path, the `System.loadLibrary()` command fails instead of the usage of the library). Alternatively you can add the path to the opencv java library to your `PATH` variable.

**Comment by sshaaf** [comment]
I am having the same issue with my maven project.

I am using the OpenPnP build of the library.         
```
<!-- https://mvnrepository.com/artifact/org.openpnp/opencv -->
<dependency>
    <groupId>org.openpnp</groupId>
    <artifactId>opencv</artifactId>
    <version>4.3.0-2</version>
</dependency>
```

If I use the standard way of loading a native library; quarkus:dev complains of UnsatisfiedLink (*this works with native quarkus build)
```
System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
```

However OpenPnP also has the following method, which is using reflection to inject the java.library.path forcefully. This works for quarkus:dev: but it doesnt work for my quarkus native binary. 

```
 OpenCV.loadShared();
```

**Comment by gsmet** [comment]
@andreas-eberle did you end up getting OpenCV working?

**Comment by gsmet** [comment]
I created an extension here: https://github.com/quarkiverse/quarkus-opencv .

It works in native and AFAICS dev mode is working too.
