### ISSUE TITLE
Problem with rendering the "page not found" template

### ISSUE THREAD

**Issue by danilomeneghel** [quarkusio/quarkus#10467]
Here is the code created:

```
import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;

import javax.ws.rs.NotFoundException;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

import com.google.common.io.Resources;

@Provider
public class NotFoundExeptionMapper implements ExceptionMapper<NotFoundException> {
    
    @Override
    public Response toResponse(NotFoundException exception) {
        URL url = Resources.getResource("/templates/pageNotFound.html");
        String text = null;

		try {
			text = Resources.toString(url, StandardCharsets.UTF_8);
		} catch (IOException e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).entity(text).build();
		}

        return Response.status(Status.NOT_FOUND).entity(text).build();
    }    
}
```

When I test on my (local) computer, it redirects to the template created for error 404.
However, when testing in production (on the internet) it doesn't work.
Quarkus does not load the template and displays the following error message:

> Internal Server Error
Error id fd4183f5-1c86-4d92-ac93-8863ff0507bd-1

**Comment by gsmet** [comment]
And you don't have anything in the log of the production server?

**Comment by danilomeneghel** [comment]
I don't have access to the production server's log.

**Comment by geoand** [comment]
@danilomeneghel do you perhaps have a small project that reproduces this behavior we can look at?

**Comment by danilomeneghel** [comment]
Yes, this is the project:
https://github.com/danilomeneghel/votacao-pautas

If you try to open this link, for example, you will see that the "page cannot be found" template is not being rendered.

http://votacao-pautas.herokuapp.com/auth/asdasasd

Now if you try to access the project on localhost, for example this url below, you will see that the template loads.

http://localhost:8080/auth/asdasasd

**Comment by geoand** [comment]
Instead of using `Resources.getResource("/templates/pageNotFound.html")`, `Resources.getResource("templates/pageNotFound.html")` will work.

A more general comment however is to use `Thread.currentThread().getContextClassLoader().getResource("templates/pageNotFound.html");` to obtain a URL.
That is guaranteed to work in all Quarkus modes.

**Comment by danilomeneghel** [comment]
That's right, thanks @geoand !

**Comment by geoand** [comment]
YW!
