### ISSUE TITLE
Allow for custom generated resources to be added to Lambda function.zip

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#10479]
There's support for adding contents from _src/main/zip.jvm_ to the resulting Lambda function.zip. It should also be possible to add other resources which have been generated during the build, i.e. contenst from _target_.

**Comment by oztimpower** [comment]
What do you suggest? How would this work, i.e how would you declare what you wanted to include?

**Comment by gunnarmorling** [comment]
I think some simple naming patterns could do the trick, e.g. like so:

```
<configuration>
    <additionalFunctionResources>target/somedir/**,target/anotherdir/test.txt</additionalFunctionResources>
</configuration>
```

There might be precedence for other cases in Quarkus, in which case the same pattern should be followed.

**Comment by patriot1burke** [comment]
IMO, you're better off using the maven assembly plugin in this instance.  I dont' think we need to recreate it.
