### ISSUE TITLE
Support src/main/webapp for web applications

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1049]
People often have stuff placed in `src/main/webapp` - e.g. index.html.
With Quarkus I have to put it to `src/main/resources/META-INF/resources/index.html`, @stuartwdouglas pointed that META-INF/resources is a standard location according to the servlet spec

This can be unpleasant change for end-user and Quarkus plugin could be enhanced to cover src/main/webapp scenario.

**Comment by Ladicek** [comment]
To me, `src/main/webapp` means Maven WAR plugin. Which wouldn't be the case here. If the directory is supposed to be processed by the Quarkus Maven plugin, it should have a different name IMHO.

**Comment by rsvoboda** [comment]
Sure, but on the other hand `webapp` directory is de facto standard and we should make the transition for users as easy as possible.
Stuart said it could be relatively easy to cover webapp directory too in Quarkus Maven plugin.

**Comment by masini** [comment]
This is not only a matter of developer's habit.

Is a common pattern to have the static part of a system on another module in Maven and thanks to WAR overlay during build this is merged inside the real application.

I don't care to continue to use this plugin, but I need another way to achieve the same goal.

**Comment by gsmet** [comment]
@stuartwdouglas I don't think we plan to do anything about this? Can we close?
