### ISSUE TITLE
Check out impact of GraalVM no longer initializing all of the JDK at build time

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10495]
**Description**

See https://github.com/oracle/graal/issues/2650

Would be good to get a Mandrel / Quarkus joint effort.
CC @galderz @stuartwdouglas

**Comment by galderz** [comment]
These changes are already part of GraalVM 20.2. I'm not aware of any regressions, anything else to do here?

**Comment by geoand** [comment]
Seems pretty far out of date, so I'll close it.
If there is still something to be done, feel free to reopen
