### ISSUE TITLE
Issue debugging kotlin based project

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#10509]
[project.zip](https://github.com/quarkusio/quarkus/files/4882934/project.zip)

1. `docker-compose up -d` from the project root
2. `./mvnw compile quarkus:dev`
3. Navigate to http://localhost:8080/graphql-ui/
4. Put the breakpoint @ OrderService::deleteOrderItem line 37
5. Issue the following command from the ui:

    ```
    mutation delete {
      deleteOrderItem(orderItemId: "5f0348bef06e9b7fd8042094")
    }
    ```

I prepared debug configuration in intellij, to attach to localhost@5005

I'm using JDK 11, Linux Ubuntu, Latest IntelliJ Community

Unfortunately, for some reason, the debugger doesn't stop at given breakpoint. 

It's probably something at my side. Please, let me know if I can provide more info

Thanks!

**Comment by dodalovic** [comment]
Any thoughts by anyone?

**Comment by geoand** [comment]
I just tried it and the breakpoint worked perfectly
