### ISSUE TITLE
 No timezone mapping entry for 'CST'

### ISSUE THREAD

**Issue by 362228416** [quarkusio/quarkus#10501]
**Describe the bug**
(Describe the problem clearly and concisely.)

 ./gradlew quarkusDev run it ok。

when I package with native image and run print this

```java
Caused by: com.mysql.cj.exceptions.WrongArgumentException: No timezone mapping entry for 'CST'
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
        at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2134)
        at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2143)
        at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
        ... 13 more
```

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

run it will be ok.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

error

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin lin.local 19.4.0 Darwin Kernel Version 19.4.0
 - Output of `java -version`: java version "1.8.0_211"
 - GraalVM version (if different from Java):  OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)
 - Quarkus version or git rev: quarkusPluginVersion=1.5.2.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.5.2.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.4.1
 - Mysql version : mysql  Ver 14.14 Distrib 5.7.21

**Additional context**
(Add any other context about the problem here.)

In china

**Comment by jaikiran** [comment]
> GraalVM version (if different from Java): OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)

Are you sure you are using Graal 20.1.0? That version is supposed to include all timezones by default.

> Quarkus version or git rev: quarkusPluginVersion=1.5.2.Final
> quarkusPlatformArtifactId=quarkus-universe-bom
> quarkusPlatformGroupId=io.quarkus
> quarkusPlatformVersion=1.5.2.Final
> 

Can you please try with:
```

quarkusPluginVersion=1.6.0.CR1
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.6.0.CR1
```
We have improved the native image building logging with Gradle in this version. So when you trigger the native image you should see a bit more output in the build log. Please attach that log here.

**Comment by 362228416** [comment]
yeah
```bash
echo $GRAALVM_HOME
.../graalvm-ce-java8-20.1.0/Contents/Home
```
I have now solved this problem by changing the application.properties configuration file and adding all-Timezones

**Comment by zhfeng** [comment]
@362228416 can you share how did you change the applicaion.properties ? I met the same issue with the mysql connection.

**Comment by jaikiran** [comment]
Hello @zhfeng, this really shouldn't be happening against 20.1.0 GraalVM. But if it is indeed happening then you can set `quarkus.native.includeAllTimeZones` to `true`. This is the config property https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L56

**Comment by zhfeng** [comment]
Hi @jaikiran I took a look into the Mysql java connector deeply. The exception throws with the [NativeProtocol.java]( https://github.com/mysql/mysql-connector-j/blob/33f65445a1bcc544eb0120491926484da168f199/src/main/protocol-impl/java/com/mysql/cj/protocol/a/NativeProtocol.java#L2134)
```
//
// The Calendar class has the behavior of mapping unknown timezones to 'GMT' instead of throwing an exception, so we must check for this...
//
if (!canonicalTimezone.equalsIgnoreCase("GMT") && this.serverSession.getServerTimeZone().getID().equals("GMT")) {
       throw ExceptionFactory.createException(WrongArgumentException.class, Messages.getString("Connection.9", new Object[] { canonicalTimezone }),
       getExceptionInterceptor());
}
```

The cannoicalTimeZone is retired from the mysql server which is "CST"
```
MariaDB [(none)]> show variables like '%zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | CST    |
| time_zone        | SYSTEM |
+------------------+--------+
```

I wrote a simple reproducer to check the condition in the NativeProtocl
```
import java.util.Arrays;
import java.util.TimeZone;

public class TestTimeZone {
        static public void main(String[] args) {
                System.out.println("Java Timezone IDs contains CST is " + Arrays.asList(TimeZone.getAvailableIDs()).contains("CST"));
                System.out.println("CST timezone getID is " + TimeZone.getTimeZone("CST").getID());
        }
}
```
Compile and run it with the JVM
```
[zhfeng@192 ~/tmp] $ java -version && javac TestTimeZone.java && java TestTimeZone
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
Java Timezone IDs contains CST is true
CST timezone getID is CST
```
Compile and run it with Graal VM
```
[zhfeng@192 ~/tmp] $ ~/Applications/graalvm-ce-java8-20.1.0/bin/native-image -H:+ReportExceptionStackTraces -H:+IncludeAllTimeZones --no-server TestTimeZone 
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
[testtimezone:170252]    classlist:   2,415.90 ms,  0.96 GB
[testtimezone:170252]        (cap):     636.70 ms,  0.96 GB
[testtimezone:170252]        setup:   2,015.63 ms,  1.06 GB
[testtimezone:170252]     (clinit):     116.32 ms,  1.21 GB
[testtimezone:170252]   (typeflow):   3,370.07 ms,  1.21 GB
[testtimezone:170252]    (objects):   2,949.16 ms,  1.21 GB
[testtimezone:170252]   (features):     201.88 ms,  1.21 GB
[testtimezone:170252]     analysis:   6,829.81 ms,  1.21 GB
[testtimezone:170252]     universe:     242.26 ms,  1.21 GB
[testtimezone:170252]      (parse):     631.87 ms,  1.21 GB
[testtimezone:170252]     (inline):     879.72 ms,  1.22 GB
[testtimezone:170252]    (compile):   4,722.84 ms,  1.42 GB
[testtimezone:170252]      compile:   6,546.69 ms,  1.42 GB
[testtimezone:170252]        image:     412.75 ms,  1.42 GB
[testtimezone:170252]        write:     113.82 ms,  1.42 GB
[testtimezone:170252]      [total]:  18,863.27 ms,  1.42 GB
[zhfeng@192 ~/tmp] $ ./testtimezone 
Java Timezone IDs contains CST is true
CST timezone getID is GMT
```
There is a different of the result. The ```getID``` in the native image resturns ```GMT``` which causes the mysql connector-J throws the Exception. A workaround is to set the ```time_zone``` in the mysql server with ```+08:00```.

**Comment by jaikiran** [comment]
That looks wrong (at the Graal VM level). Any chance you can try this against Java 11 variant of 20.1.0 of Graal VM?

**Comment by zhfeng** [comment]
yeah, the result is the same.
```
[zhfeng@192 ~/tmp] $ ~/Applications/graalvm-ce-java11-20.1.0/bin/native-image -H:+ReportExceptionStackTraces -H:+IncludeAllTimeZones --no-server TestTimeZone 
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
[testtimezone:183837]    classlist:   1,896.15 ms,  0.96 GB
[testtimezone:183837]        (cap):     682.95 ms,  0.96 GB
[testtimezone:183837]        setup:   2,273.60 ms,  0.96 GB
[testtimezone:183837]     (clinit):     247.90 ms,  1.20 GB
[testtimezone:183837]   (typeflow):   4,412.35 ms,  1.20 GB
[testtimezone:183837]    (objects):   4,066.84 ms,  1.20 GB
[testtimezone:183837]   (features):     235.08 ms,  1.20 GB
[testtimezone:183837]     analysis:   9,214.44 ms,  1.20 GB
[testtimezone:183837]     universe:     489.37 ms,  1.21 GB
[testtimezone:183837]      (parse):   1,233.18 ms,  1.21 GB
[testtimezone:183837]     (inline):   1,232.54 ms,  1.66 GB
[testtimezone:183837]    (compile):   7,135.78 ms,  2.25 GB
[testtimezone:183837]      compile:  10,329.67 ms,  2.25 GB
[testtimezone:183837]        image:     855.30 ms,  2.25 GB
[testtimezone:183837]        write:     154.14 ms,  2.25 GB
[testtimezone:183837]      [total]:  25,422.83 ms,  2.25 GB
[zhfeng@192 ~/tmp] $ ./testtimezone 
Java Timezone IDs contains CST is true
CST timezone getID is GMT
```

**Comment by jaikiran** [comment]
@zhfeng Thank you for trying that out. This indeed looks like an issue in Graal VM itself. I have opened https://github.com/oracle/graal/issues/2692 for getting their inputs.
