### ISSUE TITLE
Upgrade to MP Config 2.0

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#10517]

**Comment by jmartisk** [comment]
@radcortez I can't assign you to this but suppose this will be your area :)

**Comment by radcortez** [comment]
@gastaldi should be able to assign it to me.

Anyway, this may probably take a while until we have MP final releases out.

**Comment by jmartisk** [comment]
PR to the `microprofile-4` branch: https://github.com/quarkusio/quarkus/pull/13620
