### ISSUE TITLE
Upgrade to MP Fault Tolerance 3.0

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#10519]

**Comment by Ladicek** [comment]
I have a WIP branch locally which is up to date with latest MP FT 3.0-SNAPSHOT / SRye FT 4.3.1-SNAPSHOT, so I'm quite ready :-) Whenever MP FT 3.0 is out, it won't take long.

**Comment by jmartisk** [comment]
resolved in the `microprofile-4` branch for now, will be merged to master soon
