### ISSUE TITLE
Upgrade to MP Health 3.0

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#10518]

**Comment by xstefank** [comment]
microprofile-4 branch PR: https://github.com/quarkusio/quarkus/pull/13877

**Comment by cescoffier** [comment]
@xstefank does this include `@Startup` (startup health checks)?

**Comment by xstefank** [comment]
@cescoffier yes, but we renamed it to @Startness - https://github.com/smallrye/smallrye-health/blob/3.0.0-RC2/api/src/main/java/io/smallrye/health/api/Startness.java.

**Comment by jmartisk** [comment]
Done (in the microprofile-4 branch for now, will move to master soon)
