### ISSUE TITLE
Support configuration with nested interfaces

### ISSUE THREAD

**Issue by harthorst** [quarkusio/quarkus#10511]
**Description**
Actually it's possible to have nested configuration classes. It would be nice to have this opportunity for interfaces too.

Something like this:

```
@ConfigProperties(prefix = "acme")
public interface MyConfig {

    Greeting getGreeting();

    @ConfigProperties
    interface Greeting {
        String getHelloString();
    }
}
```

**Comment by geoand** [comment]
I opened https://github.com/quarkusio/quarkus/pull/10534 to address this.

Basically you would just write your code like so:

```
@ConfigProperties(prefix = "acme")
public interface MyConfig {

    Greeting getGreeting();

    interface Greeting {
        String getHelloString();
    }
}
```
