### ISSUE TITLE
Improve CDI guide

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#10510]
**Description**
The CDI guide didn't introduce the technology, it mainly describe the differences between the spec and what Quarkus implements and introduce some Quarkus specific features.

"Getting started" informations should exists somewhere inside the Quarkus documentation to introduce the CDI spec and it's various annotations are people are more used to Spring injection than CDI.

**Implementation ideas**
Add an introduction section inside the current guide or create a new guide.
If a new guide is created, it should be this guide linked from the website instead of the existing one that can be linked from the getting started guide;

**Comment by mkouba** [comment]
See https://github.com/quarkusio/quarkus/pull/10529
