### ISSUE TITLE
Upgrade to MP Rest Client 2.0

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#10520]

**Comment by ferinoc** [comment]
what is the timeline for MP Rest Client 2.0 please? thank you.

**Comment by jmartisk** [comment]
@ferinoc we're in the process of upgrading Quarkus to MicroProfile 4 right now, so if it goes well it should all be done in the 1.11 release (January)

**Comment by vsevel** [comment]
apparently it will not make 1.11?

**Comment by jmartisk** [comment]
Yeah, unfortunately it looks it will have to wait for 1.12

**Comment by vsevel** [comment]
will it make 1.12?

**Comment by radcortez** [comment]
Unfortunately, no. We are aligning this work with the Vert.x 4 update.

**Comment by radcortez** [comment]
Yes.
