### ISSUE TITLE
Dynamically insert a list of Service Implementations

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10553]
In Micronaut, you can do the following (and I think in SpringBoot as well):
    
` @Inject
    public MyService(List<MyHandlerInterface> myHandlers) {
        this.myHandlers = myHandlers.stream()
                .collect(Collectors.toMap(MyHandlerInterface::type, myHandler -> myHandler));
    } `

This will dynamically search for all Implementations of "MyHandlerInterface" and then create a dictionary for lookup.
In Quarkus I was not able to do the same, so I have taken a more simpler, static approach instead:

`@Produces
    public Map<EventType, EventHandler> getHandlers(MyHandlerImpl1 myHandlerImpl1,
                                                    MyHandlerImpl2 myHandlerImpl2,
                                                    MyHandlerImpl3 myHandlerImpl3,
                                                    MyHandlerImpl4 myHandlerImpl4) {

        return Stream.of(myHandlerImpl1, myHandlerImpl2, myHandlerImpl3, myHandlerImpl4)
                .collect(Collectors.toMap(StripeEventHandler::type, eventHandler -> eventHandler));
    }`

However, this doesn't scale to well - I already have 4 handler implementations, and whenever we add a new handler, we must not forgot to manually add it to the configuration.

**Comment by geoand** [comment]
Hey Marcus.

This is possible with CDI (and therefore Quarkus) as well - just use `javax.enterprise.inject.Instance` and iterate over it.

See https://github.com/quarkusio/quarkus/blob/6499b4bd00d62fd9430750de2486a3b5d082f7c3/extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/GrpcClientInterceptorContainer.java#L18 for example.

**Comment by MarcusBiel** [comment]
Is there a limit on the number of handlers allowed? It worked fine for the given case with 4 handlers. Now I have a different case with 13 handlers, and it's not working.. the map stays empty at runtime.
