### ISSUE TITLE
Configuring The POJO Codec per Collection

### ISSUE THREAD

**Issue by ShqiprimBunjaku** [quarkusio/quarkus#10563]
**Description**
Right now @BsonDiscriminator annotation can be used to register a class, but there are cases when you want to make such configurations per collection. In different collections can be similar _DiscriminatorValues_, but mapped to different types.

**Implementation ideas**
It can be similar with Mongo's Official Driver, 
`mongoClient.getCollection(COLLECTION_NAME,POJO.class).withCodecRegistry(configurations...) `

**Comment by loicmathieu** [comment]
Can your provide a more complete use case, possibly with not-working code, so we can have a better idea of where the issue lies.

**Comment by ShqiprimBunjaku** [comment]
Suppose we have following hierarchy: 

**Company hierarchy** 
`@BsonDiscriminator(value = "Base")
public class BaseCompany {
}
`
`@BsonDiscriminator(value = "CompanyType1")
public class CompanyType1 extends BaseCompany{
}`
`@BsonDiscriminator(value = "CompanyType2")
public class CompanyType2 extends BaseCompany{
}
`

**Update Logs hierarchy**
`@BsonDiscriminator(value = "Base")
public class UpdateLogs{
}
`
`@BsonDiscriminator(value = "CompanyType1")
public class CompanyType1UpdateLogs extends UpdateLogs{
}`
`@BsonDiscriminator(value = "CompanyType2")
public class CompanyType2UpdateLogs extends CompanySnapshots{
}
`

for Companies we have _companies_ collection, and for Update Logs we have  _updatelogs_  collection. Both of hierarchies have the same  _DiscriminatorValues_.  Now, when getting data from collection _companies_, they won't be mapped to the correct types since we have more than one type for the same _DiscriminatorValue_.  
In Mongo's Official Driver, you have the option to register these configurations per collection. Also, another thing, which I think it's important, is that you can also specify ReadPreferences (primary, secondary) per collection. It would be great to have these options in Quarkus Driver for MongoDb.

**Comment by ShqiprimBunjaku** [comment]
@loicmathieu  any update on this?

**Comment by loicmathieu** [comment]
@ShqiprimBunjaku I'm very surprised that different discriminator hierarchies with the same value will be an issue.
As I understand it, a discriminator will be used to defines, based on a docment property, wich classes of a hierarchy will be choosed to instanciate the result object.

Mayeb there is something I dont' understand in your use case, so please can you provide an example project with the non-working solution so we can find a way to fix it ?

For your request to sepcify `ReadPreferences` per collection, can you open another issue ?

**Comment by ShqiprimBunjaku** [comment]
@loicmathieu Here you have a snippet code from mongodb driver class that handles this: 

```
package org.bson.codecs.pojo;

import org.bson.codecs.configuration.CodecConfigurationException;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import static java.lang.String.format;

final class DiscriminatorLookup {
    private final Map<String, Class<?>> discriminatorClassMap = new ConcurrentHashMap<String, Class<?>>();
    private final Set<String> packages;

    DiscriminatorLookup(final Map<Class<?>, ClassModel<?>> classModels, final Set<String> packages) {
        for (ClassModel<?> classModel : classModels.values()) {
            if (classModel.getDiscriminator() != null) {
                discriminatorClassMap.put(classModel.getDiscriminator(), classModel.getType());
            }
        }
        this.packages = packages;
    }

    public Class<?> lookup(final String discriminator) {
        if (discriminatorClassMap.containsKey(discriminator)) {
            return discriminatorClassMap.get(discriminator);
        }

        Class<?> clazz = getClassForName(discriminator);
        if (clazz == null) {
            clazz = searchPackages(discriminator);
        }

        if (clazz == null) {
            throw new CodecConfigurationException(format("A class could not be found for the discriminator: '%s'.",  discriminator));
        } else {
            discriminatorClassMap.put(discriminator, clazz);
        }
        return clazz;
    }

```
As you can see DiscriminatorValue and Class pair is saved on Map and one instance of DiscriminatorLookup is used through all collections. If more than one class share the same DiscriminatorValue the latest one will be registered in Map.  

For `ReadPreferences `  I will open a new issue.

**Comment by loicmathieu** [comment]
@ShqiprimBunjaku I would say this is a limitation of how discriminator is used, they are intended to be unique across all classes defined inside a single PojoCodec instance.
Usually, the value of the discriminator is the name of the class so it should be unique.
I don't see what we can do about it, the PojoCodec is registered at the client level.

Now, you can always access the collection from the entity or repository (the method is `mongoCollection()` and register a PojoCodec by yourself in it. Not sure it will works but you can try.

**Comment by ShqiprimBunjaku** [comment]
Since Quarks Driver has the similar interfaces for database and collection with Mongo's Driver, and they are more like adapters to use Mutiny, it would be good to adapt or implement other methods that are in Mongo's Driver interfaces for collections and database. This would also be helpful when migrating to Quarks from other frameworks that use Mongo's official Driver.

**Comment by loicmathieu** [comment]
@ShqiprimBunjaku I didn't understand your last comment. If you don't use MongoDB with Panache, you can inject a MongoClient  or a Reactive variant.
The MongoClient comes from the MongoDB official driver without any customization, but the Reactive variant is a Mutiny based wrapper on top of the `com.mongodb.reactivestreams.client.MongoClient` there is an `unwrap()` method to access it so I don't understand what's missing here.

**Comment by loicmathieu** [comment]
The reactive variant also wrap the reactive `MongoDatabase` and `MongoCollection`, again with `unwrap()` method to accessing the underlying ones.

**Comment by loicmathieu** [comment]
@ShqiprimBunjaku are my last comments OK for you ?
Can we close this one or do you suggest something to be done on Quarkus side ?

**Comment by shqiprimbkodelabs** [comment]
@loicmathieu Yes, you can close it.

**Comment by loicmathieu** [comment]
Thanks. Closed
