### ISSUE TITLE
Quarkus native image process doesn't allow additional environment variable during docker build

### ISSUE THREAD

**Issue by nfrankel** [quarkusio/quarkus#10566]
**Describe the bug**

I'm using Quarkus Hazelcast integration. Because Quarkus uses Java 11, Hazelcast warns me during the native image compilation process I should open some modules according to JPMS.

```
12:34:13,002 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
```

To fix this, I use the `quarkus.native.additional-build-args` option.

**Expected behavior**

By using the `quarkus.native.additional-build-args` option in the POM (or in `application.properties`), I could add `-e JAVA_OPTS="--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"`.

This way, the docker build would use the `JAVA_OPTS` environment variable, and open/export the required JPMS modules.

**Actual behavior**

The way it's coded (cf. [NativeImageBuildStep](https://github.com/quarkusio/quarkus/blob/d3bedb554ee7a7def9f0c342052219d0bfa4dfcd/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L172)), additional build arguments are **appended** after the image name. Docker cannot parse environment variables at this point, and I get the following message:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/nico/projects/hazelcast/quarkus-integration/target/url-shortener-1.0-native-image-source-jar:/project:z --env LANG=C --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -e JAVA_OPTS="--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED" --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar url-shortener-1.0-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace url-shortener-1.0-runner
Error: Unrecognized option: -e JAVA_OPTS="--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
```

**To Reproduce**

1. Try to add any environment variable to the Docker build via `quarkus.native.additional-build-args`, either in the POM or in `application.properties`

**Configuration**

This is not configuration-dependent.

**Environment:**

 - Output of `uname -a` or `ver`: `Darwin Nico 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`
 - Output of `java -version`:

    ```
    openjdk 11.0.7 2020-04-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
    ```
 - GraalVM version (if different from Java): It's using GraalVM from the Docker image
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
 
    ```
    Maven home: /Users/nico/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
    Java version: 11.0.7, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
    ```

**Comment by geoand** [comment]
Thanks for reporting.

Interesting use case indeed. 
`quarkus.native.additional-build-args` was definitely not meant for passing environment variables, but instead for passing arguments into the `native-image` command line (whether one is using `quarkus.native.container-build` or not).

That means that we need to figure out an alternative means of allowing such a use case.

**Comment by nfrankel** [comment]
Thanks for the quick feedback @geoand.

I wondered whether to consider it a "bug" or a "feature", and decided for the former because I thought it would "just" need a reordering of the arguments. Feel free to move it to a category that makes sense to your team.

But in general, I'd really boost this issue, because I think it's pretty important for a lot of use-cases, not only JPMS.

**Comment by geoand** [comment]
Yeah, this should be simple to do if we add another configuration knob.

Here is a related question though: Say you weren't using `quarkus.native.container-build=true` and were relying on having GraalVM locally, how would expect to go about configuring `--add-exports` etc?

**Comment by nfrankel** [comment]
Something like `-e JAVA_OPTS="--add-modules java.se"`

**Comment by geoand** [comment]
I guess I wasn't clear, I mean't that when `quarkus.native.container-build=false` no docker container is run, and the `native-image` command is just run as a regular (Java) process. 
How do you expect to pass in  `--add-modules ...` in that case? 
 
Also somewhat related, I am not sure that `JAVA_OPTS` is even consulted when building the native image. Have you seen relevant documentation or do you have an example that shows that it actually works?

**Comment by nfrankel** [comment]
Given that the code is executed at AOT-build, I inferred that execution paths that may depend on system properties will be evaluated depending on those system properties at build time.

I inferred that modules would likewise be checked at compile time.

But in all honesty, that's what I expect, I've no guarantee of that as I'm not a GraalVM expert.

**Comment by geoand** [comment]
Thanks @nfrankel.  

@jaikiran do you know if the native-image generation honors `JAVA_OPTS`? My guess is that it does not

**Comment by jaikiran** [comment]
Hello @geoand, the `native-image` command has the `-J` option which allows users to pass along any JVM specific options to the native image builder Java process:

```
native-image --help
...
-J<flag>              pass <flag> directly to the JVM running the image generator
```
So from what I understand of this use case, @nfrankel doesn't really need to set the `JAVA_OPTS` environment variable.
@nfrankel, in Quarkus application to pass the `-J` option to native image generator, you can use something like the following command (FYI - the `\` character before the `-J` option has to be used to prevent Maven from throwing a command parsing error):

```
mvn clean install -Dquarkus.package.type=native -Dquarkus.native.additional-build-args="\-J--add-modules=java.se, \-J--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED, \-J--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED, \-J--add-opens=java.base/java.lang=ALL-UNNAMED, \-J--add-opens=java.base/java.nio=ALL-UNNAMED, \-J--add-opens=java.base/sun.nio.ch=ALL-UNNAMED, \-J--add-opens=java.management/sun.management=ALL-UNNAMED, \-J--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED"
```
I haven't given this a try against Hazelcast Quarkus application, but against a simple Quarkus application this worked fine (the image got generated - I didn't test the modularity of that image though).

**Comment by geoand** [comment]
Thanks @jaikiran.

That's what I thought, although I had never tested `-J` for anything other than passing system properties to the image generation process.

**Comment by nfrankel** [comment]
Thanks @geoand!

I am currently on vacations, I'll try it when I get back.

**Comment by geoand** [comment]
Have fun 😎

**Comment by sdehors-ibm** [comment]
Hello, 
is there any updates on this ?
I'm trying to set environment variables in the build container for my app as well and hit the same problem. Passing java props instead works with the -J-Dxxx. Still, would be good to be able to pass environment variable.

**Comment by geoand** [comment]
Let's close this as `native-image` has the `-J` option for exactly this reason
