### ISSUE TITLE
Using fast-jar without uber-jar results in no runner.jar beeing built

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#10608]
**Describe the bug**
When using only the `quarkus.package.type=fast-jar` config in the `application.properties` file no `*-runner.jar` is built. Only if you also specify the `quarkus.package.uber-jar=true` property, a fast uber-jar is built.

This behavior is the same for maven and gradle.

**Expected behavior**
It should be enought to specify the `quarkus.package.type=fast-jar` option. If this option only makes sense when creating an uber-jar, then the uber-jar option should be set implicitly. Otherwise, this option alone is not working. 

**Actual behavior**
No `*-runner.jar` is built when only `quarkus.package.type=fast-jar` is set in application.properties.

**To Reproduce**
1. Create a new project with code.quarkus.io (it doesn't work for gradle as well as for maven)
2. Set `quarkus.package.type=fast-jar` in the `application.properties` files
3. Run `./mvnw package` or `./gradlew assemble`
4. no `*-runner.jar*`
 

**Configuration**
```properties
#quarkus.package.uber-jar=true
quarkus.package.type=fast-jar
```

**Environment (please complete the following information):**
 - Windows 10
- Quarkus 1.6.0

**Comment by gsmet** [comment]
So fast-jar is totally different from the existing approaches and put everything in the `target/quarkus-app/` directory. That's why you don't find the runner jar.

The problem here IMHO is that we should throw an error if you specify both fast-jar and uberjar as it doesn't make sense. @stuartwdouglas WDYT?

**Comment by andreas-eberle** [comment]
Is there some documentation on the fast-jar stuff? I haven't really found some. This would be an important thing to mention.

**Comment by andreas-eberle** [comment]
@gsmet: Maybe it would make sense to use the same property (`quarkus.package.type`) for both (fat-jar and fast-jar). Both options are packaging types and this would make it obvious that you cannot use both at the same type but only choose one packaging option.
