### ISSUE TITLE
Resteasy artifact partially considered for CDI during tests

### ISSUE THREAD

**Issue by 50846731925714380692** [quarkusio/quarkus#10635]
**Describe the bug**
I have created an example project to demonstrate the bug [here](https://github.com/50846731925714380692/tmp-qrks)
quarkus-resteasy artifact contains an Exception Mapper implementation for 404 Not Found responses (io.quarkus.resteasy.runtime.NotFoundExceptionMapper). 

When we register our own ExceptionMapper<Throwable> then:

The Provider(NotFoundExceptionMapper) is registered when executing:
`./gradlew qD`
The Provider(NotFoundExceptionMapper) is not registerd when executing:
`./gradlew test`

If there is a manual entry in application properties for the test profile to explicitly build a jandex index on the artifact - the problem is sloved.
Only the NotFoundExceptionMapper is not registered, i.e. ForbiddenExceptionMapper (ootb) is registered properly.

**Expected behavior**
Register artifacts on the classpath the same way for all profiles (dev, test, prod) - when a custom provider(ExceptionMapper<Throwable>) present ?!

**Actual behavior**
Artifacts on the test classpath are not (fully) registered for CDI - when a custom provider(ExceptionMapper<Throwable>) is present.

**To Reproduce**
1. clone the [project](https://github.com/50846731925714380692/tmp-qrks)
2. ./gradlew qD
3. curl --location --request GET http://localhost:8080/hello123 -I 
4. returns 404
5. stop quarkus
6. ./gradlew test
7. test fails due to received 500 http status, instead of 404 as in step 3
8. Uncomment application.properties
9. ./gradlew test
10. Test is ok

**Configuration**
```properties

# we have to manually register the package because it is not scanned for tests...
#%test.quarkus.index-dependency.reseasty-exception-notfound.group-id=io.quarkus
#%test.quarkus.index-dependency.reseasty-exception-notfound.artifact-id=quarkus-resteasy

```

**Screenshots**

**Environment (please complete the following information):**
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
quarkusPlatformVersion=1.6.0.Final

**Additional context**

**Comment by geoand** [comment]
Hi,

This the expected behavior: 

https://github.com/quarkusio/quarkus/blob/7da2dce5b602b4c27bfda431d39a0898a95eb33c/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/NotFoundExceptionMapper.java

is only registered in dev mode: https://github.com/quarkusio/quarkus/blob/770dbae2a93876bee33d52fb3c275c5549bc6aab/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyBuiltinsProcessor.java#L81
