### ISSUE TITLE
Warning with kotlin constructor injection

### ISSUE THREAD

**Issue by Gui-Yom** [quarkusio/quarkus#10640]
**Describe the bug**
I get warnings about 'unrecommended usage of private members in application beans'. I should not get those warnings since those members are declared public (same behavior when I declare them public explicitly). However, the injection works fine since I can use the object after.

**Expected behavior**
No warnings.

**Actual behavior**
Warnings
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-07-10 13:34:29,110 INFO  [io.qua.arc.pro.BeanProcessor] (build-11) Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field playground.DummyEndpoint#mapper
2020-07-10 13:34:30,114 INFO  [io.quarkus] (Quarkus Main Thread) playground 0.1.0 on JVM (powered by Quarkus 1.6.0.Final) started in 2.155s. Listening on: http://0.0.0.0:8080
2020-07-10 13:34:30,115 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-07-10 13:34:30,115 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kotlin, mutiny, resteasy, security, sentry, smallrye-context-propagation, smallrye-jwt, vertx, vertx-web]
```

**To Reproduce**
Example :
```kotlin
@ApplicationScoped
@RouteBase(path = "/dummy", produces = ["application/json"])
class DummyEndpoint(@Inject val mapper: ObjectMapper) {

    @Route(path = "/pair", methods = [HttpMethod.GET])
    fun pair(re: RoutingExchange) {
        re.ok(mapper.writeValueAsString(object {
            val result = Pair("a", "b")
        }))
    }
}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [version 10.0.18363.900]`
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: `1.6.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `gradle 6.5`

**Comment by geoand** [comment]
Hi,

The way the constructor of the  Route has been written

```
class DummyEndpoint(@Inject val mapper: ObjectMapper)
```

means that Kotlin will add the  `@Inject` annotation to the `mapper` field. I presume what you wanted to do was add  `@Inject` to the constructor - you could do that like so:

```
class DummyEndpoint public @Inject constructor(val mapper: ObjectMapper)
```

However doing that is redundant in Quarkus, because the `DummyEndpoint` class only has one constructor and therefore the `@Inject` annotation is not needed.

So the easiest way to achieve what you want is:

```
class DummyEndpoint(val mapper: ObjectMapper)

```
