### ISSUE TITLE
`Malformed input or input contains unmappable characters` with paths containing UTF-8 characters in native

### ISSUE THREAD

**Issue by pjeanjean** [quarkusio/quarkus#10646]
**Describe the bug**
When compiling a Quarkus project with the native profile and running it in a Docker container, it becomes impossible to use either `java.io` or `java.nio` with paths that contain UTF-8 characters.
It works fine when running the same project with maven's `compile` command.

**Expected behavior**
Being able to access paths that contain UTF-8 characters with the native image.

**Actual behavior**
`java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters`

**To Reproduce**
1. Start from the `getting-started` example
2. Add the following to GreetingResource.hello:
```java
try {
    java.nio.file.Paths.get("/files", "–/hello"); // '–' is a UTF-8 character
} catch (Exception e) {
    e.printStackTrace();
}
```
3. `./mvnw package -Pnative -Dquarkus.native.container-build=true`
4. `docker build -f src/main/docker/Dockerfile.native -t quarkus-quickstart/getting-started .`
5. `docker run -i --rm -p 8080:8080 quarkus-quickstart/getting-started`
6. `curl 127.0.0.1:8080/hello`
7. Get the exception

The only way I managed to actually access such files is by wrapping their paths in URIs, but then it became quite bothersome when I needed to access zip files using Java's zip API (the only solution I have right now is to copy the files in `/tmp` everytime I need to access them)

**Comment by jaikiran** [comment]
Hello @pjeanjean, which version of Quarkus is this?

**Comment by jaikiran** [comment]
> ./mvnw package -Pnative -Dquarkus.native.container-build=true

Can you try this instead:

> ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.additional.build.args="-J-Dsun.jnu.encoding=UTF-8"

and then do the rest of the steps and test the invocation?

**Comment by pjeanjean** [comment]
Hello,

I am running the version currently set with the `getting-started` example : 1.6.0.Final.

I still have the issue when I add the argument (the right parameter was `-Dquarkus.native.additional-build-args` by the way)

**Comment by jaikiran** [comment]
Hello @pjeanjean, can you please post the complete command the the logs that you see on the console when you build the native image using the additional property I noted above? That might give us some hint on what's going wrong.

**Comment by pjeanjean** [comment]
Sure
[log.txt](https://github.com/quarkusio/quarkus/files/4913198/log.txt)
