### ISSUE TITLE
Failed to create project: expected START_TAG or END_TAG

### ISSUE THREAD

**Issue by rahmanusta** [quarkusio/quarkus#10658]
**quarkus-maven-plugin** doesn't generate pom.xml correctly

![image](https://user-images.githubusercontent.com/1158804/87233846-6f38eb00-c3cb-11ea-9927-84bfa92643ba.png)
![image](https://user-images.githubusercontent.com/1158804/87233855-87a90580-c3cb-11ea-85c4-04fdcad9aead.png)

**Expected behavior**
${maven_repositories}${maven_plugin_repositories}  placeholders should be replaced properly.

**Actual behavior**
${maven_repositories}${maven_plugin_repositories} placeholders weren't replaced by plugin.

**Configuration**
```
usta@Rahmans-MacBook-Air first-quarkus % java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
```
usta@Rahmans-MacBook-Air first-quarkus % mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/usta/apps/apache-maven-3.5.6
Java version: 11.0.7, vendor: GraalVM Community, runtime: /Users/usta/apps/graalvm-ce-java11-20.1.0/Contents/Home
Default locale: en_TR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Comment by famod** [comment]
I can reproduce this on Windows 10 with Maven 3.6.3 and AdoptOpenJDK 11.0.7.

**Comment by famod** [comment]
Can you try 1.6.0.Final? Seems to work for me.

**Comment by rahmanusta** [comment]
It has worked, thanks

**Comment by famod** [comment]
@rahmanusta Thanks for your feedback. Can you please close this issue then? Thanks!

**Comment by JapoDeveloper** [comment]
Using version 1.6.0.Final work for me. Thanks!
