### ISSUE TITLE
quarkus-mongodb-client - More control over connections pool

### ISSUE THREAD

**Issue by Neirth** [quarkusio/quarkus#10661]
**Description**
I was implementing your mongodb driver when I realized that there is no way to control or avoid the connection pool, I understand that your intention is that each connection is injected into the classes that need it, but in the projects in which we have our Connection pool itself is a serious problem, especially when we have the connections numbered so that another connection pool creates them as it wishes.

**Implementation ideas**
 So I think that your thing would be to implement some parameter that allows you to enable or disable it, or that you can obtain minimum connections through a get method, at least so that when we are making a for to integrate that connection with our classes, we can control it.

**Comment by loicmathieu** [comment]
@Neirth sorry for a very late reply.
We use the official MongoDB driver and it uses a connection pool, there is nothing Quarkus specific here.
We create the client when the application starts, if the client is used (if it's not used but configured, we didn't create it as we have an CDI engine that remove unused CDI bean).
You can control the connection pool of MongoDB using the following parameters:
```
quarkus.mongodb.min-pool-size
quarkus.mongodb.max-pool-size
```
There is more configuration options available, see https://quarkus.io/guides/mongodb#configuration-reference

If you think something more should be done, please explain what should be done to control the connection pool.

If you want to avoid connection pooling, you can configure min/max to one but in this case you will need to create one client per thread, so I strongly advise not to do it.

**Comment by geoand** [comment]
Closing this as we didn't get feedback
