### ISSUE TITLE
Reactive Routes should contribute to the OpenAPI descriptor

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#10670]
**Description**

Reactive Routes do not contribute to the OpenAPI descriptor, so it's not possible to document them that way or call them using Swagger.

**Comment by phillip-kruger** [comment]
Hi @cescoffier. I can look at this if no one else is.

**Comment by cescoffier** [comment]
Great @phillip-kruger! It's yours!

**Comment by phillip-kruger** [comment]
#8435 is a duplicate.
