### ISSUE TITLE
Native build failed with Class initialization and UnresolvedElementException exceptions while using Jasper Report

### ISSUE THREAD

**Issue by Mahaswami** [quarkusio/quarkus#10684]
**Describe the bug**
Native build failed with class initialization exception and UnresolvedElementException for many classes in the jasperreports library.

```
Error: Class initialization of net.sf.jasperreports.data.http.HttpDataService failed. Use the option --initialize-at-run-time=net.sf.jasperreports.data.http.HttpDataService to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/apache/http/auth/Credentials
Caused by: java.lang.ClassNotFoundException: org.apache.http.auth.Credentials

Error: Class initialization of net.sf.jasperreports.engine.data.ExcelDataSource failed. Use the option --initialize-at-run-time=net.sf.jasperreports.engine.data.ExcelDataSource to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook

Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time.A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.   To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.

Error: No instances of sun.nio.ch.FileChannelImpl are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: net.sf.jasperreports.data.http.HttpDataService.(net.sf.jasperreports.engine.ParameterContributorContext, net.sf.jasperreports.data.http.HttpDataLocation). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
at parsing net.sf.jasperreports.data.BuiltinDataFileServiceFactory.createService(BuiltinDataFileServiceFactory.java:57)
Call path from entry point to net.sf.jasperreports.data.BuiltinDataFileServiceFactory.createService(ParameterContributorContext, DataFile):
at net.sf.jasperreports.data.BuiltinDataFileServiceFactory.createService(BuiltinDataFileServiceFactory.java:51)

```
Included --initialize-at-run-time build option and specified all jasperreports classes for which there were errors to delay their initialization to run time. 

```
quarkus.native.additional-build-args=--initialize-at-run-time=net.sf.jasperreports.data.http.HttpDataService\,net.sf.jasperreports.engine.data.ExcelDataSource\,net.sf.jasperreports.engine.data.JRXlsxDataSource\,net.sf.jasperreports.engine.data.XlsDataSource\,net.sf.jasperreports.renderers.AbstractSvgDataToGraphics2DRenderer\,net.sf.jasperreports.engine.export.XmpWriter\,net.sf.jasperreports.web.util.AbstractWebResourceHandler\,net.sf.jasperreports.renderers.util.SvgDataSniffer
```

After this the class initialization exceptions are gone. But the other exceptions remain.

[Jasper Native Build Error2.txt](https://github.com/quarkusio/quarkus/files/4913057/Jasper.Native.Build.Error2.txt)
[Jasper Native Build Error1.txt](https://github.com/quarkusio/quarkus/files/4913058/Jasper.Native.Build.Error1.txt)

Refer Jasper Native Build Error1.txt for complete stack trace of the error. 

Refer Jasper Native Build Error2.txt for complete stack trace of error after adding the build argument below

**Expected behavior**
Native build should succeed and should be able to generate jasper report from native build.

**Actual behavior**
Native build fails. 
Runs in JVM mode successfully and generates jasper report.

**To Reproduce**

Reproducer project can be found at https://github.com/MahaswamiSoftware/quarkus-jasper-report

**Configuration**
```
quarkus.native.additional-build-args=--initialize-at-run-time=net.sf.jasperreports.data.http.HttpDataService\\,net.sf.jasperreports.engine.data.ExcelDataSource\\,net.sf.jasperreports.engine.data.JRXlsxDataSource\\,net.sf.jasperreports.engine.data.XlsDataSource\\,net.sf.jasperreports.renderers.AbstractSvgDataToGraphics2DRenderer\\,net.sf.jasperreports.engine.export.XmpWriter\\,net.sf.jasperreports.web.util.AbstractWebResourceHandler\\,net.sf.jasperreports.renderers.util.SvgDataSniffer
```
**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:   Linux msuser1 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 11.0.7

 - GraalVM version (if different from Java): 20.1.0 

 - Quarkus version or git rev: 1.5.0.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.2

**Additional context**
(Add any other context about the problem here.)

**Comment by michalszynkiewicz** [comment]
hi @Mahaswami , running Jasper Reports with Quarkus is not supported.

You can create a Quarkus extension for it. 
If you would like to try, check out https://quarkus.io/guides/building-my-first-extension or https://quarkus.io/guides/writing-extensions for more details.

Feel free to ping us on Zulip (https://quarkusio.zulipchat.com/) if you need any help.
