### ISSUE TITLE
Infra/CI: Archive **/target/**/*.log and maybe more

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#10696]
**Description**
CI is currently not archiving all logs that are needed to analyze failures. E.g. in https://github.com/quarkusio/quarkus/pull/10647#issuecomment-657698281 I am missing `integration-tests/maven/target/test-classes/projects/multimodule-resources-classpath/build-multimodule-resources-classpath.log`.
This is especially obstructive when flaky tests are involved and/or your local operating system differs from CI.

**Implementation ideas**
I propose to create for each build/job an archive (or add to the existing one) with all logfiles under `target` (however deeply nested).

Furthermore I propose to archive `**/target/surefire-reports/*` and `**/target/failsafe-reports/*`. Not sure about Gradle, though.

I also propose the set `trimStackTrace` to `false` for the entire repo.
See also: https://lists.apache.org/thread.html/r9030808273c82ac6d7b9602d34d446c7d8c4e8aa02c41bca164df1c5%40%3Cdev.maven.apache.org%3E (meaning that even the Maven maintainers suggest to disable it)

**Comment by gsmet** [comment]
Makes sense.

**Comment by famod** [comment]
_Update_:
- Surefire reports are being archived for a while now ✔️ 
- I switched off `trimStackTrace` recently (except for `independent-projects`) ✔️ 

So the only thing left are those logfiles.
