### ISSUE TITLE
error with @QuarkusMain java.nio.file.FileSystemNotFoundException 

### ISSUE THREAD

**Issue by wmacibnc** [quarkusio/quarkus#10704]
**Describe the bug**
When I generate the .jar with @QuarkusMain and Quarkus.run (args) the error occurs:

Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileSystemNotFoundException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:50)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:93)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at br.com.bb.sgn.microservice.utils.Main.main(Main.java:10)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:35)
	... 5 more

**Expected behavior**
java -jar myapp.jar run with Quarkus.

**Actual behavior**
When a java -jar myapp.jar not start Quarkus.

**To Reproduce**
1. Create main:
```java
@QuarkusMain
public class Main{
	
	public static void main(String[] args) throws Exception {
		  Quarkus.run(args);
	}
}
```
2.  Export .jar with plugins maven:

```xml
<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<id>primeiro</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<finalName>myApp</finalName>
							<archive>
								<manifest>
									<addClasspath>true</addClasspath>
									<classpathPrefix>lib/</classpathPrefix>
									<mainClass>br.com.myApp</mainClass>
								</manifest>
							</archive>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-help-plugin</artifactId>
				<version>2.2</version>
			</plugin>
		</plugins>
	</build>
```
3. 
```cmd
java -jar myApp.jar
```

**Comment by stuartwdouglas** [comment]
You still need to launch the -runner jar and let the Quarkus maven plugin build your application, you can't attempt to use the copy-dependencies plugin to manually create the same structure and expect it to work.

**Comment by geoand** [comment]
I'll close this since it's not a feature we support

**Comment by wmacibnc** [comment]
OK! Thanks!
