### ISSUE TITLE
1.6.0.Final K8S ImagePullPolicy not used anymore

### ISSUE THREAD

**Issue by UnvirtualHH** [quarkusio/quarkus#10710]
Since using Quarkus 1.6.0.Final the kubernetes imagePullPolicy is not used anymore. It is always IfNotPresent generated into the final kubernetes.yml

Obviously the parameter name changed to image-pull-secret (such changes should be documented in upgrade.md) but it is not working with new or old typo of the param. 

Really annoying when previous working stuff breaks my build.

**Comment by UnvirtualHH** [comment]
Well, actually trying to reproduce it with a new project and not able to get the error then. I'll try to give a reproducer or more info where the error could come from.

**Comment by geoand** [comment]
I tried and could not reproduce the problem.

`quarkus.kubernetes.image-pull-policy=IfNotPresent` and `quarkus.kubernetes.image-pull-policy=Always` were being properly honored.

Also when the value was not configured, `Always` was being set

**Comment by UnvirtualHH** [comment]
So, needed some time to find the dependency that creates the failure. 

Just add 

<dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-container-image-jib</artifactId>
 </dependency>

**Comment by geoand** [comment]
I still can't reproduce it (I was already using jib as well). 

Can you perhaps upload the project you are using to reproduce the error?

**Comment by UnvirtualHH** [comment]
Sure.

[reproducer.zip](https://github.com/quarkusio/quarkus/files/4917314/reproducer.zip)

**Comment by geoand** [comment]
The build output gives a clear indication of why you are seeing what you are:

```
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesProcessor] No registry was set for the container image, so 'ImagePullPolicy' is being force-set to 'IfNotPresent'.
```

**Comment by UnvirtualHH** [comment]
Haha, ok....so always the same...Pebcak error....sorry for that error report.

**Comment by geoand** [comment]
No worries :)
