### ISSUE TITLE
Kakfa-Streams dependency injection issue

### ISSUE THREAD

**Issue by leandro-rouberte** [quarkusio/quarkus#10724]
**Describe the bug**
I'm attempting to inject a KafkaStreams object using Quarkus CDI by having a Topology provider method.
I then use this injected KafkaStreams to iterate through some Kafka-Streams metrics. Sometimes the application run, sometimes it throws a NPE when trying to access the injected KafkaStreams object.

**Expected behavior**
The KafkaStreams object would be built before being referenced by other classes.

**Actual behavior**
Sometimes KafkaStreams object gets built in time, and sometimes does not throwing a NPE.

**To Reproduce**
1. Clone this project https://github.com/leandro-rouberte/quarkus-kafka-streams-issue
2. From project root run the following a couple of times until it gives a NPE: `./mvnw compile quarkus:dev`

**Configuration**
```properties
quarkus.kafka-streams.application-id = data-publisher-test
quarkus.kafka-streams.bootstrap-servers = localhost:9092
quarkus.kafka-streams.topics = test-topic
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin **** 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by pcasaes** [comment]
It seems that the cause is order the order of instantiating ApplicationScope beans during start up. Sometimes the producer for the Stream will be started first, sometimes not.

**Comment by maeh2k** [comment]
I believe I just ran into the same issue trying to follow this tutorial for Streams metrics: https://quarkus.io/blog/kafka-streams-applications-with-quarkus-and-microprofile/

Great bug report, Leandro.
