### ISSUE TITLE
@Liveness probe doesn't work with @Path

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#10720]
Quarkus 1.6.0.FINAL

the health probe annoted with @Liveness and @Path   won't be returned when we call http://localhost:8080/health/

I took the example : quarkus-quickstarts\microprofile-health-quickstart 

and when I do

mvn quarkus:dev
http://localhost:8080/health/

the output is : 

```
{
    "status": "UP",
    "checks": [
        {
            "name": "Simple health check",
            "status": "UP"
        },
        {
            "name": "Health check with data",
            "status": "UP",
            "data": {
                "bar": "barValue",
                "foo": "fooValue"
            }
        },
        {
            "name": "Database connection health check",
            "status": "UP"
        }
    ]
}
```

but if I add @Path in a class : SimpleHealthCheck that have @Liveness, the output became

```

{
    "status": "UP",
    "checks": [
        {
            "name": "Health check with data",
            "status": "UP",
            "data": {
                "bar": "barValue",
                "foo": "fooValue"
            }
        },
        {
            "name": "Database connection health check",
            "status": "UP"
        }
    ]
}
```

**Comment by mkouba** [comment]
Hm, I wonder what is the use case for annotating a health check with `@javax.ws.rs.Path`? Anyway, you're right. I've been able to reproduce the issue locally.

**Comment by survivant** [comment]
my usecase is that I have a variable that I used to set the return as UP and DOWN.  Mostly for testing or disabling a probe.  I use the endpoint to change that value

**Comment by mkouba** [comment]
Anyway, I found the problem - JAX-RS root resources are automatically annotated with `@javax.enterprise.inject.Typed(RootResource.class)` to workaround some problems with JAX-RS sub-resource locators. And so the `org.eclipse.microprofile.health.HealthCheck` is removed from its set of bean types.

You'll need to use a separate bean for the healh check, inject the bean in the resource and change its state via the endpoint methods.

**Comment by geoand** [comment]
Perhaps we just want to log a warning when `@Path` is used together with `@Liveness` or `@Readiness`?
