### ISSUE TITLE
fast-jar (v1.6.0) doesn't work with Alexa skill

### ISSUE THREAD

**Issue by max-grigoriev** [quarkusio/quarkus#10733]
**Describe the bug**
Alexa skill can't be invoked.

**Expected behavior**
Alexa skill should be invoked without any errors.

**Actual behavior**
The exception is thrown:
```
Class not found: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

**To Reproduce**
Create a simple Alexa skill and enable `fast-jar` feature.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.package.type=fast-jar
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin Maksyms-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
 - GraalVM version (if different from Java): GraalVM Version 20.1.0 (Java Version 11.0.7)
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Maven 3.6.3

**Comment by gsmet** [comment]
@max-grigoriev could you create a simple reproducer? That would be helpful.

/cc @oztimpower

**Comment by gsmet** [comment]
I'm not entirely sure we support anything else than uberjar though but I will let @oztimpower confirm.

**Comment by geoand** [comment]
If we don't support anything other than uber-jar for the alexa skill, we should fail the build with the appropriate warning

**Comment by oztimpower** [comment]
Amazon Lambda requires an uber-jar, and Alexa is merely a form of this. Does the fast-jar option not provide all dependencies in an uber-jar?

**Comment by geoand** [comment]
> Amazon Lambda requires an uber-jar, and Alexa is merely a form of this. Does the fast-jar option not provide all dependencies in an uber-jar?

It does not. It's closer in layout to regular Quarkus runner jar than the uber-jar.

**Comment by oztimpower** [comment]
Ok... @patriot1burke had changed the Amazon Lambda extension to force an uber-jar by default via the deployment package.  I would agree then that fast-jar should not be an option in this case.

**Comment by oztimpower** [comment]
On my own Amazon Alexa project I tried to set the fast-jar property and did get a build exception as below, which I would expect, with 999-SNAPSHOT.  Everything looks ok to me?

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project alexa-personalise: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.RuntimeException: Cannot set quarkus.package.uber-jar=true and quarkus.package.type, if you want an uber-jar set quarkus.package.type=uber-jar.
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:181)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by geoand** [comment]
That error looks good to me

**Comment by geoand** [comment]
Closing as per comments above
