### ISSUE TITLE
@ConfigProperties does not work in @QuarkusTest environment

### ISSUE THREAD

**Issue by aksth** [quarkusio/quarkus#10735]
I have a class that uses @ConfigProperties as shown below:

```
@ConfigProperties(prefix = "oidc")
public class OIDCProperties {

    String serverUrl;
    String applicationRealm;
    String adminRealm;
    .......
}
```
I also tried with @Inject @ConfigProperty, as it is related to this issue: [#2061](https://github.com/quarkusio/quarkus/issues/2061)
```
@Inject
@ConfigProperty(name = "server-url")
String serverUrl;
```

I have injected it following way to use those configs:

```
@Inject
OIDCProperties oidcProperties;
```

It works as it should in the normal run, but in the test environment, I'm getting the injected oidcProperties as null.

In my application.properties, I have:

```
oidc.server-url=%{oidc_server_url:http://localhost:8180/auth}
```

**Environment:**
 - Output of `uname -a` or `ver`: 
 - openjdk version "11.0.6" 2020-01-14
 - OpenJDK Runtime Environment GraalVM CE 20.0.0
 - Quarkus version: 1.4.1.Final
 - Maven 3.6.3

**Comment by aksth** [comment]
This issue is should have been solved by the #2061, but maybe isn't.

**Comment by geoand** [comment]
Interesting, I'll take a look

**Comment by geoand** [comment]
I couldn't reproduce the problem.

I tried 

```java
@ConfigProperties(prefix = "dummy")
public interface DummyConfig {

	String getName();

	Integer getAge();

	SubDummy getSubDummy();

	interface SubDummy {

		@ConfigProperty(name = "foo")
		String getFooBar();
	}
}

@Path("/dummy")
public class DummyResource {

	@Inject
	DummyConfig dummyConfig;

	@GET
	@Path(("/parent"))
	public String foobar() {
		return dummyConfig.getSubDummy().getFooBar();
	}
}
```

and then test:

```java
@QuarkusTest
public class DummyResourceTest {

    @Inject
    DummyConfig dummyConfig;

    @Test
    public void testHelloEndpoint() {
        given()
                .when().get("/dummy/parent")
                .then()
                .statusCode(200)
                .body(is("bar"));
    }

    @Test
    public void testConfig() {
        Assertions.assertEquals("bar", dummyConfig.getSubDummy().getFooBar());
    }

}
```

and everything worked as expected when I set the properties:

```
dummy.age=34
dummy.name=geo
dummy.sub-dummy.foo=bar
```

**Comment by geoand** [comment]
Also, I saw you are using an old version of Quarkus, can you try with `1.6.0.Final`?

**Comment by aksth** [comment]
@geoand Hey thanks. Yes, it does work in the scenario that you provided above. I think everything's fine with Aquarius. It may be due to mistake from my side. I have replicated my scenario here. Could you have a look at it? [https://github.com/aksth/quarkus-configproperty-test/blob/master/src/test/java/org/acme/ExampleResourceTest.java] Why does the second test fail here?

**Comment by geoand** [comment]
Did you try with Quarkus `1.6.0.Final`? Even if there is a bug with 1.4.x, we don't support it anymore :)

**Comment by chinnaxs** [comment]
Same problem here:
openjdk version 11.0.04"
Quarkus version: 1.6.Final
Maven 3.6.3

**Comment by geoand** [comment]
The problem with your code :

```
@QuarkusTest
public class ExampleResourceTest {

    @Inject
    OIDCProperties oidcProperties;

    private final TestProperty test = new TestProperty(oidcProperties);

...

}
```

is that `private final TestProperty test = new TestProperty(oidcProperties);` is executed before Quarkus injects the value into `oidcProperties`.

To best populate the field in a JUnit `@BeforeEach` method

**Comment by aksth** [comment]
@geoand Thank you very much.

**Comment by geoand** [comment]
You are welcome

**Comment by wilbertjoosen** [comment]
If a config property is injected by the resource I get the same error reported by @aksth, how can I solve this?

**Comment by geoand** [comment]
@wilbertjoosen best to ask on the chat for help.
In any case, you'll need to provide details about what your code looks like and what the exact error is
