### ISSUE TITLE
Jandex warning at boot time about JsonString

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#10742]
**Describe the bug**

At system start, the following warning is printed:

```
2020-07-15 11:54:34,465 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-32) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.json.JsonString (source: com.redhat.cloud.policies.app.rest.PolicyCrudService[javax.ws.rs.core.Response validateName(@NotNull javax.json.JsonString policyName, java.util.UUID id)])
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.

```

Code looks like

```
  @POST
  @Path("/validate-name")
  public Response validateName(@NotNull JsonString policyName, @QueryParam("id") UUID id) {

```

`JsonString` is pulled into Quarkus via 

* io.quarkus:quarkus-resteasy-jsonb:1.6.0.Final
** org.jboss.resteasy:resteasy-json-binding-provider:4.5.5.Final
*** org.glassfish:jakarta.json:1.1.6

so I would expect that this is already registered in Quarkus by default. 
This warning was not printed before 1.6 

**Expected behavior**

Print no warning, as it is already registered

**Comment by mkouba** [comment]
It seems that we produce the fi`ReflectiveHierarchyBuildItem` twice. One backed by the `CombinedIndexBuildItem` and the other one backed by the `BeanArchiveIndexBuildItem`. And the one backed by `CombinedIndexBuildItem` results in the warning. I'll send a PR to fix this particular issue but the overall "reflection registration strategy" would probably deserve some refactoring...
