### ISSUE TITLE
Dependabot pull requests in quarkus forks

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#10743]
**Dependabot pull requests in quarkus forks**
I don't know whether this is intended but after I rebased my fork (xstefank/quarkus) master today I started to get dependabot update PRs into my fork for which I don't see the reasoning.

https://github.com/xstefank/quarkus/pulls

![2020-07-15-1594807102_1726x643](https://user-images.githubusercontent.com/9353101/87532079-ebb11f80-c692-11ea-9aff-5986369ba3d0.png)

**Comment by famod** [comment]
Maybe related to #10681?

/cc @gastaldi 

PS: What I also find irritating is that once I push to `master` of my fork, the entire CI-chain is triggered.

**Comment by gastaldi** [comment]
Thanks for reporting this, I'll investigate

**Comment by gastaldi** [comment]
In https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-version-updates-on-forks it says that 
> Version updates are not automatically enabled on forks when a dependabot.yml configuration file is present. 

But I wonder if this is only valid for new forks. In this case can you try recreating your fork to see if that works?

**Comment by gastaldi** [comment]
> PS: What I also find irritating is that once I push to `master` of my fork, the entire CI-chain is triggered. But that has been like this for a long time.

@famod Ah yes, AFAIK this is a GitHub actions feature. You can disable it by removing the `.github/workflows` directory from your master branch

**Comment by famod** [comment]
> > PS: What I also find irritating is that once I push to `master` of my fork, the entire CI-chain is triggered. But that has been like this for a long time.
> 
> @famod Ah yes, AFAIK this is a GitHub actions feature. You can disable it by removing the `.github/workflows` directory from your master branch

@gastaldi Ah, good to know. But wouldn't I then get merge conflicts each time something changes in that file?

**Comment by gastaldi** [comment]
I rarely push to my master branch in my fork so I don't really have this problem TBH :smile: Just make sure to keep your cloned master branch synch'ed with the original master :wink:

**Comment by xstefank** [comment]
yes, reforking worked. Thanks!

**Comment by famod** [comment]
@gastaldi Maybe this should be pinned for a while so that other contributors see this directly? (I mean the GH pinning feature, not the label).

**Comment by gastaldi** [comment]
@famod good idea, just did that. Let's see if it helps

**Comment by famod** [comment]
@gastaldi ...and @sberyozkin unpinned it - maybe you guys should talk. 😆

**Comment by jaikiran** [comment]
> Maybe related to #10681?
> 
> /cc @gastaldi
> 
> PS: What I also find irritating is that once I push to `master` of my fork, the entire CI-chain is triggered. But that has been like this for a long time.

Hello @famod, this can be disabled in your fork settings. Go to Settings -> Actions and then select the "Disable actions for this repository" radio button.

**Comment by famod** [comment]
@jaikiran Thanks, but that would disable actions for all branches, not just `master`, wouldn't it?

**Comment by famod** [comment]
Have there been any changes? I recreated my fork not long ago but still keep getting dependabot PRs.

**Comment by gastaldi** [comment]
@famod try force pushing to your master a commit similar to what I have in github.com/gastaldi/quarkus

**Comment by famod** [comment]
@gastaldi Dependabot it checking such a file? 😮 

Seems many users are affected by this (in general): https://github.com/dependabot/dependabot-core/issues/2198
