### ISSUE TITLE
Metrics are not being presented

### ISSUE THREAD

**Issue by wmacibnc** [quarkusio/quarkus#10758]
**Describe the bug**
We are creating metrics programmatically, but they are not being presented in url /metrics.

**Expected behavior**
When we create metrics programmatically they are not being presented.

**Actual behavior**
Metrics populated programmatically in url /metrics are not being presented

**To Reproduce**
1. Create métricas programmatically, method not use Http Request.

```java
MetricRegistry registry = MetricRegistries.get(MetricRegistry.Type.APPLICATION);
	    Metadata metadata = Metadata.builder()
                .withType(MetricType.COUNTER)
                .withName("abc")
                .withDescription("abc")
                .withDisplayName("abc")
                .withUnit("abc")
                .reusable()
                .build();
	    registry.counter(metadata).inc(1);
```

2. View metrics in /metrics

**Configuration**
```properties
Nothing
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/3158954/87552353-f3b79200-c687-11ea-921a-fdc5e3c76db4.png)

**Environment (please complete the following information):**
- Build with `@QuarkusMain` and `Quarkus.run()`

**Additional context**
Nothing

**Comment by geoand** [comment]
cc @jmartisk

**Comment by jmartisk** [comment]
I can't reproduce this. 
While I haven't tested metrics in `@QuarkusMain` mode before, I tried it now and everything worked to my expectations - a programmatically added metric is present in the `/metrics/application` output. Could you share a runnable reproducer or some more details?

**Comment by jmartisk** [comment]
I basically tried a runnable main method like this
```

@QuarkusMain
public class QuarkusScript implements QuarkusApplication {
    @Override
    public int run(String... args) throws Exception {
        MetricRegistry registry = MetricRegistries.get(MetricRegistry.Type.APPLICATION);
        Metadata metadata = Metadata.builder()
                .withType(MetricType.COUNTER)
                .withName("abc")
                .withDescription("abc")
                .withDisplayName("abc")
                .withUnit("abc")
                .build();
        registry.counter(metadata).inc(1);
        TimeUnit.MINUTES.sleep(300);
        return 0;
    }
}
```
that creates a metric and then makes the application sleep so I can check the `/metrics` output. The metric was there. Does your application do something fundamentally different?

**Comment by wmacibnc** [comment]
Thanks! But I need after to execute Quarkus.run() is execute my metrics. 

```java
@QuarkusMain
public class Main{
	
	public static void main(String[] args){
		System.out.println("teste-1");
		Quarkus.run(MyApp.class, args);
		System.out.println("teste-2");
		new Main().teste();
		System.out.println("teste-3");
	}
	public static class MyApp implements QuarkusApplication {

		@Override
		public int run(String... args) throws Exception {
			System.out.println("teste-a");
			new Main().teste();
			System.out.println("teste-b");
			Quarkus.waitForExit();
			System.out.println("teste-c");
			return 0;
		}
		
		  
	}
	
	public void teste(){
		MetricRegistry registry = MetricRegistries.get(MetricRegistry.Type.APPLICATION);
        Metadata metadata = Metadata.builder()
                .withType(MetricType.COUNTER)
                .withName("abc")
                .withDescription("abc")
                .withDisplayName("abc")
                .withUnit("abc")
                .build();
        registry.counter(metadata).inc(1);
	}
```

```Log
teste-1
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-07-28 10:57:31,831 INFO  [io.quarkus] (main) sgn-componente-entrada-api 1.0.12 on JVM (powered by Quarkus 1.6.0.Final) started in 1.133s. Listening on: http://0.0.0.0:8084
2020-07-28 10:57:31,839 INFO  [io.quarkus] (main) Profile prod activated. 
2020-07-28 10:57:31,840 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, resteasy, resteasy-jsonb, smallrye-health, smallrye-metrics]
teste-a
teste-b

```

![image](https://user-images.githubusercontent.com/3158954/88675701-9416a900-d0c1-11ea-84e9-c41e66d2e081.png)

**Comment by wmacibnc** [comment]
Thanks! But I need after to execute Quarkus.run() is execute my metrics. 

```java
@QuarkusMain
public class Main{
	
	public static void main(String[] args){
		System.out.println("teste-1");
		Quarkus.run(MyApp.class, args);
		System.out.println("teste-2");
		new Main().teste();
		System.out.println("teste-3");
	}
	public static class MyApp implements QuarkusApplication {

		@Override
		public int run(String... args) throws Exception {
			System.out.println("teste-a");
			new Main().teste();
			System.out.println("teste-b");
			Quarkus.waitForExit();
			System.out.println("teste-c");
			return 0;
		}
		
		  
	}
	
	public void teste(){
		MetricRegistry registry = MetricRegistries.get(MetricRegistry.Type.APPLICATION);
        Metadata metadata = Metadata.builder()
                .withType(MetricType.COUNTER)
                .withName("abc")
                .withDescription("abc")
                .withDisplayName("abc")
                .withUnit("abc")
                .build();
        registry.counter(metadata).inc(1);
	}
```

```Log
teste-1
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-07-28 10:57:31,831 INFO  [io.quarkus] (main) sgn-componente-entrada-api 1.0.12 on JVM (powered by Quarkus 1.6.0.Final) started in 1.133s. Listening on: http://0.0.0.0:8084
2020-07-28 10:57:31,839 INFO  [io.quarkus] (main) Profile prod activated. 
2020-07-28 10:57:31,840 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, resteasy, resteasy-jsonb, smallrye-health, smallrye-metrics]
teste-a
teste-b

```

![image](https://user-images.githubusercontent.com/3158954/88675701-9416a900-d0c1-11ea-84e9-c41e66d2e081.png)

**Comment by wmacibnc** [comment]
I Resoled with Thread, but is no cool.

```java
public static void main(String[] args){
		System.out.println("teste-1");
		new Thread(new Runnable() {
			@Override
			public void run() {
		Quarkus.run(MyApp.class, args);
			}
		}).start();
		System.out.println("teste-2");
		new Main().teste();
		System.out.println("teste-3");
	}
```

**Comment by jmartisk** [comment]
The problem is that you're using the Quarkus command mode wrong. You need to execute `Quarkus.run(MyApp.class, args);` from the `main` method and that has to be the last (and optimally the only) thing in the `main` method, because Quarkus will then take control of the thread that calls it. Anything after that in your `main` method will probably never execute. Running the `Quarkus.run` method in a different thread makes it work in this particular case, but it is still not how you should use Quarkus.

Any interaction with your metrics then needs to be in the application (`MyApp`) itself, that means called as a result of executing `MyApp.run()`, not in your `main` method, which should serve ONLY as an entry point for starting the application, nothing else.

See the documentation at https://quarkus.io/guides/command-mode-reference#main-method, specifically this note:
> It is recommended that a Java main perform very little logic, and just launch the application main.

**Comment by wmacibnc** [comment]
Ok! Thanks!
