### ISSUE TITLE
Quarkus classloader doesn't support multi-release jars

### ISSUE THREAD

**Issue by jaikiran** [quarkusio/quarkus#10756]
As noted in a recent Quarkus dev mail discussion[1], the `JarClassPathElement` used by the Quarkus classloading infrastructure doesn't currently support multi-release jar files.

[1] https://groups.google.com/d/msg/quarkus-dev/nnKFDiTBlR4/uRksUDDpCAAJ

**Comment by gastaldi** [comment]
I created https://github.com/smallrye/smallrye-common/pull/36 to include @Ladicek's `JarFiles` in Smallrye Commons
