### ISSUE TITLE
Cannot inject ApplicationScoped inside ApplicationScoped with Kotlin

### ISSUE THREAD

**Issue by toubacol** [quarkusio/quarkus#10771]
**Describe the bug**
Let's say we have three beans (Entry, GreetingService and GreetingService2) all annotated with `@ApplicationScoped`
```kotlin
@ApplicationScoped
open class Entry {
  @Inject
  lateinit var greetingService :GreetingService 
  
  @Produces
  fun build(): MyBean {
    greetingService.foo() // greetingService is well injected 
  }
}
```
```kotlin
@ApplicationScoped
open class GreetingService{
    @Inject
    lateinit var greetingService2: GreetingService2

    fun foo() = greetingService2.hello() // greetingService2 (not injected)
}
```
```kotlin
@ApplicationScoped
open class GreetingService2{
    fun hello() = "hello"
}
```
`GreetingService2` is injected inside `GreetingService`, and `GreetingService` is injected inside `Entry`.
`Entry `declares a `@Produces` method which is invoked directly at start up.

 `GreetingService` is well injected but not `GreetingService2`

**Expected behavior**
`GreetingService2` should be injected inside `GreetingService`

**Actual behavior**
`GreetingService2` is not injected inside `GreetingService` and we got a late init issue:
`Caused by: kotlin.UninitializedPropertyAccessException: lateinit property greetingService2 has not been initialized`

**Additional context**
When we use constructor injection like this:

```
@ApplicationScoped
open class Entry() {

  @Produces
  fun build(greetingService :GreetingService): MyBean {
     greetingService.foo()
  }

}
```
and GreetingService like so:

```
@ApplicationScoped
class GreetingService(private val greetingService2: GreetingService2) {

    fun hello() = greetingService2.hello() // greetingService2 is null (not injected)
}
```
and

```
@ApplicationScoped
class GreetingService2 {

    fun hello() = "hello"
}

```

GreetingService2 is null (not injected) and lead to NullPointerException.

Thank you for help.

**Comment by geoand** [comment]
Thanks for reporting.

Please upload the test project to github so we can make sure we check the same thing you are using to reproduce the issue

**Comment by geoand** [comment]
Closing as we never got feedback
