### ISSUE TITLE
Override properties during testing made easier

### ISSUE THREAD

**Issue by Serkan80** [quarkusio/quarkus#10783]
I saw that in Quarkus 1.6.0 QuarkusTestProfile was added to override properties and more. But this is quite cumbersome for situations when you only need to change 1 property. 

**Description**
So we have the following in src/test/resources/application.properties:

  - appId=tOpS3cretId290380
  - %fake.appId=1234

And this gets injected in MyService via @ConfigPropert(name="appId").

**Implementation ideas**
And in the integration test, we want to use both appId's, as follows:

     @QuarkusTest
     class MyTest {
      @Inject MyService service;

      @Test
      public void callOK() {
       // uses the real appId = tOpS3cretId290380 from application.properties and this gets injected in MyService
      }

     @Test
     @UseProfile("fake")
      public void wrongKey_ShouldThrow403Error() {
        // should use:  %fake.appId = 1234 in application.properties and this should get injected in MyService
      }
     }

**Comment by lordofthejars** [comment]
This is already supported in some way (not directly as you mention) look at https://quarkus.io/blog/quarkus-test-profiles/

**Comment by Serkan80** [comment]
> This is already supported in some way (not directly as you mention) look at https://quarkus.io/blog/quarkus-test-profiles/

Yes I know that. But my suggestion is to make it simpler without writing any code and just using an annotation on the test method.

**Comment by lordofthejars** [comment]
:+1: sorry then :)

**Comment by geoand** [comment]
One reason we went with `@TestProfile` is that it makes it very easy for users to know to API.
I would really like to avoid a situation (as occurs in other frameworks) where you could have a host of different annotations contributing to the test environment, thus making it hard for a user to know which annotation to use in which case.

**Comment by lordofthejars** [comment]
fair point too.

**Comment by geoand** [comment]
Closing as `won't fix` since there has not been demand for this
