### ISSUE TITLE
Arc container does not work with Producer methods and Qualifiers

### ISSUE THREAD

**Issue by arielcarrera** [quarkusio/quarkus#10793]
**Describe the bug**
When you have a producer method with @Produces and a qualifier (@MyQualifier)... Quarkus registers a bean with @Default and @Any qualifiers instead.

**Expected behavior**
A bean registered with MyQualifier

**Actual behavior**
A bean is registered with @Default and @Any

**To Reproduce**
1. Write a Producer like this:
```
@ApplicationScoped
public class MyProducer {	
	@Produces @MyQualifier @Unremovable
	public MyBean produce(BeanManager beanManager, TransactionManager transactionManager) {
		return new MyBean(beanManager, transactionManager);
	}
}
```
	
2.  Write a Qualifier:
```
@Target({ TYPE, METHOD })
@Retention(RUNTIME)
@Documented
@Qualifier
public @interface MyQualifier {
	public static final class Literal extends AnnotationLiteral<MyQualifier>
			implements MyQualifier {
		public static final Literal INSTANCE = new Literal();
		private static final long serialVersionUID = 1L;
	}
}
```

3. Add MyBean class:
```
public class MyBean  {
	public MyBean(BeanManager beanManager, TransactionManager transactionManager) {
        super();
    }
}	
```

4. Run in a service:
```
		Set<Bean<?>> beans = Arc.container().beanManager().getBeans(Object.class, Any.Literal.INSTANCE);
	        for (Bean<?> bean : beans) {
	        	if (bean.getBeanClass().equals(MyProducer.class)) {
	        		String name = bean.getName();
	        		Set<Annotation> qualifiers = bean.getQualifiers();
	        		Class<? extends Annotation> scope = bean.getScope();
	        		Set<Class<? extends Annotation>> stereotypes = bean.getStereotypes();
	        		Set<Type> types = bean.getTypes();
	        		System.out.println("Bean name: " +  String.valueOf(name) + ", qualifiers: " + qualifiers.toString()
	        		+ ", scope: " + bean.getScope().toString() + ", stereotypes: " + bean.getStereotypes() + ", types: " + types.toString());
	        	}
	            System.out.println(bean.getBeanClass().getName());
	        }
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
System out:

Bean name: null, 
qualifiers: [@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()], 
scope: interface javax.enterprise.context.Dependent, 
stereotypes: [], 
types: [class java.lang.Object, class x.y.z.MyBean]

class x.y.z.MyProducer

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin MacBook-Pro-de-Ariel.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.6.0.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/..../apache-maven-3.6.0
Java version: 11.0.7, vendor: GraalVM Community, runtime: /Users/..../.sdkman/candidates/java/20.1.0.r11-grl
Default locale: es_AR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Additional context**
I'm developing an extension and my code is inside my runtime module.

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by mkouba** [comment]
Hi @arielcarrera, it would be really helpful if you could share your extension code. My guess is that `@MyQualifier` is not part of the bean archive index and so it's not recognized as a qualifier. To fix this just produce an `AdditionalBeanBuildItem` for the `MyQualifier` class. You probably already register `MyProducer` via this build item anyway, so you can just add the qualifier class to the existing build item.

TIP: In the dev mode, you can inspect all registered beans at http://localhost:8080/quarkus/arc/beans.

**Comment by arielcarrera** [comment]
Oh!, thank you @mkouba. It works.
I thought that registering the producer class in that build item would be enough.
On the other hand, if the producer class is annotated with a scope qualifier, I understand that it should not be needed to add it to the build item... right?
If there is a rule ... what do you think it would be to determine which classes to put in that index?

**Comment by mkouba** [comment]
> I thought that registering the producer class in that build item would be enough.

Hm, actually it should be enough. We do attempt to index all annotations declared on a class registered with an `AdditionalBeanBuildItem`. Could you try to build an app with your extension with `mvn install -X` and see if there are some debug log messages like `Could not index annotation: org.acme.Foo (missing class or dependency)`?

> On the other hand, if the producer class is annotated with a scope qualifier, I understand that it shouldn't be necessary to add it to the build item... right?

Built-in scope annotations are added automatically by Quarkus.

> ...what do you think it would be to determine which classes to put in that index?

If you want to be safe, then put all bean classes, qualifiers, interceptor bindings, stereotypes there ;-).

**Comment by arielcarrera** [comment]
There is no message `Could not index annotation` ... but I can see the messages `Stale source detected` and `Deleting file`.
So my problem is that as you said I don't have all interceptor, producer and annotation classes registered with an `AdditionalBeanBuildItem` and quarkus removed them ... Thanks.
