### ISSUE TITLE
Dev mode log viewing HTTP handler

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1081]
When in dev mode and there is an HTTP listener, it would be nice to have a log viewer service URL that will show a continuous view of the last N log messages.  This is also a natural fit for SSE.

This should be done by adding a public singleton `org.jboss.logmanager.handlers.QueueHandler` to the root logger inside of `LoggingSetupTemplate` as one of the handlers along side file and/or console.  The log service would simply query the `QueueHandler` by adding itself as a child handler (see [QueueHandler in upstream](https://github.com/jboss-logging/jboss-logmanager/blob/master/ext/src/main/java/org/jboss/logmanager/ext/handlers/QueueHandler.java#L128), which would have to be backported to our fork for now).  The sub-handler would be removed when the SSE stream is broken.  The web page would maintain a maximum number of messages, defined by configuration.  The queue would maintain some maximum number of messages, also defined by configuration.

**Comment by stuartwdouglas** [comment]
We have this now in the dev console.
