### ISSUE TITLE
Podman Support

### ISSUE THREAD

**Issue by 2er0** [quarkusio/quarkus#10815]
**Add podman for image building**

Podman would be a nice alternative to docker for building container images.

Currently, only docker is supported by checking if the docker executable/service is available and if the server version is available.
Podman and other container runtimes should further be supported.

**Comment by jaikiran** [comment]
Hello @2er0, you can use `-Dquarkus.native.container-runtime=podman` when launching your native image build through Quarkus.

**Comment by 2er0** [comment]
Hi @jaikiran, nice to know.
Is this somewhere in the documentation? (Could not find it)

**Comment by famod** [comment]
Hi @2er0 
> Is this somewhere in the documentation? (Could not find it)

https://quarkus.io/guides/building-native-image#creating-a-container (it is in the first "Tip" box).

**Comment by 2er0** [comment]
Sorry - my fail - was searching for it in the wrong documentation, since I wanted to have a JVM image/container build
https://quarkus.io/guides/container-image
