### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by ravirajb** [quarkusio/quarkus#10827]
**Describe the bug**
mvn  io.quarkus:quarkus-maven-plugin:1.0.1.Final:create fails

**Expected behavior**
Should create the project ideally.

**Actual behavior**
With jdk14, I am unable to build the project.

**To Reproduce**
1. Set the java to jdk14
2. Execute the command:  mvn io.quarkus:quarkus-maven-plugin:1.0.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=hello-quarkus     -DclassName="org.acme.quickstart.GreetingResource"     -Dpath="/hello"
3. It fails with the error

_[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.0.1.Final:create (default-cli) on project standalone-pom: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...ties>\n    ${maven_repositories}${maven_plugin_repositories}\n    <d... @23:7)  -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException_

**Comment by famod** [comment]
Seems like a duplicate of #10658.
Any reason why you are using such an "ancient" version of `quarkus-maven-plugin`? The most recent one is 1.6.0.Final.

**Comment by ravirajb** [comment]
Thanks for pointing that out.
I was following an old tutorial, didn't see this. 

It's working now. 

Thanks
