### ISSUE TITLE
Build failing with newly generated Optaplanner App

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkusio/quarkus#10834]
**Describe the bug**
I generated a Quarkus app with your start coding tool. Look [here](https://code.quarkus.io/?g=de.dammeier&a=course-timetabling&v=0.0.1&b=GRADLE&c=de.dammeier.ctt.ExampleResource&s=pV1.CPa.ARC.FBQ.qiu.HNL.PHF.bapn&cn=code.quarkus.io) for my configuration.

**Expected behavior**
New app can be built and tested.

**Actual behavior**
Optaplanner fails while testing.
```
PS ...\course-timetabling> .\gradlew build

Welcome to Gradle 6.4.1!
...
> Task :test

ExampleResourceTest > testHelloEndpoint() FAILED
    java.lang.RuntimeException at QuarkusTestExtension.java:390
        Caused by: java.lang.RuntimeException at AugmentActionImpl.java:246
            Caused by: io.quarkus.builder.BuildException at Execution.java:115
                Caused by: java.lang.IllegalStateException at OptaPlannerProcessor.java:184

1 test completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
...
BUILD FAILED in 7s
```

**To Reproduce**
1. download my configured app
2. try to build it with `.\gradlew build`

Maybe the problem occurs because there are no optaplanner annotations present yet?

**Comment by geoand** [comment]
cc @ge0ffrey

**Comment by ge0ffrey** [comment]
Looking at this. cc @triceo in case this spills over to next week when I am on PTO already.

**Comment by ge0ffrey** [comment]
> Maybe the problem occurs because there are no optaplanner annotations present yet?

Probably, that's an open issue (see https://issues.redhat.com/browse/PLANNER-1957 ). The IllegalStateException occurs if you add the optaplanner extension but don't add any domain etc in the current version.
That being said, it's a big pita - and I presumed gsmet we 'd fix it. It just got pushed out a few times.

**Comment by ge0ffrey** [comment]
@geoand @alexander-dammeier I believe this issue was fixed a long time ago. Please close it.

**Comment by gsmet** [comment]
Thanks @ge0ffrey !
