### ISSUE TITLE
Bean validation in class annotated with ConfigProperties doesn't work

### ISSUE THREAD

**Issue by Rutzzzz** [quarkusio/quarkus#10848]
I was following the guide for Quarkus configuration - https://quarkus.io/guides/config#using-configproperties. The example with bean validation using class annotated with ConfigProperties doesn't seem to work as no errors are thrown when property violates bean validation annotations.

**Expected behavior**
An error is displayed when a property in application.properties has value violating bean validation annotation.

**Actual behavior**
No error is displayed.

**To Reproduce**

1. Create the project
```code
mvn io.quarkus:quarkus-maven-plugin:1.6.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=config-quickstart \
    -DclassName="org.acme.config.GreetingResource" \
    -Dpath="/greeting"
cd config-quickstart
```

2. Create the configuration class with following content:
```code
@ConfigProperties(prefix = "greeting")
public class GreetingConfiguration {
    @Size(min = 20)
    public String message;
    public String suffix = "!";
}
```

3. Add the following property to application.properties:
```code
greeting.message = hello
```

4. Inject the configuration to GreetingResource class
```code
@Inject
GreetingConfiguration greetingConfiguration
```

5. Output the configuration
```code
@GET
@Produces(MediaType.TEXT_PLAIN)
public String hello() {
     return greetingConfiguration.message + greetingConfiguration.suffix;
}
```

6. Run the application
```code
./mvnw quarkus:dev
```

**Configuration**
```properties
greeting.message = hello
```

**Environment:**
 - Output of `uname -a` or `ver`: Linux localhost.localdomain 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
 - Quarkus version: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by geoand** [comment]
Hi,

This turns out to be a docs problem. You need to add the `quarkus-hibernate-validator` extension to make it work. I opened #10854 to fix the docs.
