### ISSUE TITLE
MP RestClient timeouts not honoured in Quarkus 1.6

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#10846]
**Describe the bug**

I am using the MP RestClient for some remote calls 

I have set timeouts in application.properties for connection and then the remote read:

```
rbac/mp-rest/connectTimeout=1000
rbac/mp-rest/readTimeout=1000

```

With Quarkus 1.5.1.Final, those are (more or less) honored: 

```
2020-07-20 11:24:06,426 INFO  [RbacFilter] (executor-thread-1) Timeout calling RBAC
2020-07-20 11:24:06,434 WARNING [RbacFilter] (executor-thread-1) Call to RBAC took 1977ms
```

Quarkus 1.6 does not abort the call after the expected 2s (2*1000ms) as 1.5 does, but seems to have a different timeout impl:

```
2020-07-20 11:29:14,294 INFO  [RbacFilter] (executor-thread-1) Timeout calling RBAC
2020-07-20 11:29:14,300 WARNING [RbacFilter] (executor-thread-1) Call to RBAC took 4998ms
```

Code is like in #10804 

```
  @Inject
  @RestClient
  RbacServer rbac;

  [...]

    long t1 = System.currentTimeMillis();
    try {
      result = getRbacInfo(user.getRawRhIdHeader());
    } catch (Throwable e) {
      if (e.getCause()!= null && e.getCause() instanceof SocketTimeoutException) {
        log.info("Timeout calling RBAC");
      }
      requestContext.abortWith(Response.status(Response.Status.FORBIDDEN).build());
      return;
    } finally {
      long t2 = System.currentTimeMillis();
      if (warnSlowRbac.get() && (t2 - t1) > 500) {
        log.warning("Call to RBAC took " + (t2 - t1) + "ms");
      }
    }


//  @CacheResult(cacheName = "rbac-cache")   // <<-- disabled on purpose
  RbacRaw getRbacInfo(String xrhidHeader)  {
    RbacRaw result;
    result = rbac.getRbacInfo("policies", xrhidHeader);
    return result;
  }
```

**Expected behaviour**

Configured timeouts are honored like in Quarkus 1.5 and earlier

**Comment by geoand** [comment]
Thanks for reporting.

Questions, does this same erroneous behavior happen with `1.5.2.Final` as well?

**Comment by geoand** [comment]
Moreover, does the erroneous behavior in 1.6 persist if you set a system property called `org.jboss.resteasy.microprofile.defaultToURLConnectionHttpClient` to `true`?

**Comment by pilhuhn** [comment]
I could not reproduce the bad behaviour with 1.5.2.Final. And setting the property to true seems to help.
I have just tried to mock the remote with a mock-server (for test containers) and there the timeout seems to be ok, so my guess is that it is the connect-timeout that is problematic and not the read-timeout.

**Comment by geoand** [comment]
Thanks for the information. It seems to be a problem in RESTEasy, I'll have to take a closer look

**Comment by geoand** [comment]
I looked into this and it seems that it comes down to the fact that the Apache HTTP Client will try all the IP addresses that DNS returns for the specified host when a connection timeout occurs, whereas URLConnection will only use the first one.

There doesn't seem there is anything we can do on the Quarkus side of things.

@pilhuhn can you try using an IP address instead of a hostnmame in order to confirm this behavior?

**Comment by geoand** [comment]
I'll go ahead and close this - but feel free to reopen and/or comment @pilhuhn
