### ISSUE TITLE
Docker multistage build still necessary for native image?

### ISSUE THREAD

**Issue by FloGa** [quarkusio/quarkus#10852]
In https://quarkus.io/guides/building-native-image, there are the sections "Creating a container" and "Creating a container with a multi-stage Docker build". As it is written, one could assume, that in the first section, with

    ./mvnw package -Pnative -Dquarkus.native.container-build=true

you can build a native image for containers on your local machine, so that GraalVM needs to be installed locally. If not, one should use the multistage build as described in the second section.

However, by using the above command from the first section, the Maven plugin seems to start up a Docker container to build the native image, exactly like described in the second section.

My questions are: Are those two sections redundant? Is the explicit multistage build obsolete since it will be handled by the plugin anyway? If not, which method is preferred, what is the difference?

**Comment by geoand** [comment]
What the multi-stage build does, is in **addition** to building the native binary without needing GraalVM, it created a **new** container image based on the generated binary.

It's not redundant, although one could argue that building the container is a lot easier to do using using `quarkus-container-image-docker` or `quarkus-container-image-jib` - see [this](https://quarkus.io/guides/container-image) part of the documentation.
