### ISSUE TITLE
Typo error in INFO message when @Alternative bean is ignored 

### ISSUE THREAD

**Issue by tnmtechnologies** [quarkusio/quarkus#10862]
**Describe the bug**
When an Alternative bean is going to be ignored, the INFO message contains the word AlernativePriority instead of AlternativePriority. 

**Expected behavior**
[INFO] [io.quarkus.arc.processor.Beans] Ignoring bean defined via _fully-qualified class name_ - declared as an \@Alternative but not selected by \@Priority, \@AlternativePriority or quarkus.arc.selected-alternatives

**Actual behavior**
[INFO] [io.quarkus.arc.processor.Beans] Ignoring bean defined via _fully-qualified class name_ - declared as an @Alternative but not selected by \@Priority, \@AlernativePriority or quarkus.arc.selected-alternatives

**To Reproduce**
1. Annotate a bean with  @Alternative annotation (no @AlternativePriority annotation, no update of property quarkus.arc.selected-alternatives).
2. During the project build, an INFO message as described in Actual behavior section should be displayed.

**Configuration**
not applicable

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Quarkus version 1.6.0.Final

**Additional context**
https://github.com/quarkusio/quarkus/blob/a75f2db39e3025a5c38884f716614c19a0c050ad/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java#L139

**Comment by gsmet** [comment]
Looks like you're ready to provide a PR? :)

**Comment by tnmtechnologies** [comment]
I will provide the PR.

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkusio/quarkus/commit/5486b569c195d567ef0814288da7a718899be1be
