### ISSUE TITLE
Provide support for composite primary key in Spring Data JPA

### ISSUE THREAD

**Issue by lferna** [quarkusio/quarkus#10870]
**Describe the bug**
Composite primary key with @Id and @EmbeddedId annotation are not allowed because there is an error about the mandatory use of an @Id annotation.

```
@Entity
public class Profile {
	
	@EmbeddedId
	private ProfileId profileId;
	
	@Column(name = "name")
	String name;
}
```
And:

```
@Embeddable
public class ProfileId  implements Serializable{	
	private static final long serialVersionUID = 1L;
	@Column(name = "id")
	private String id;

	@Column(name = "number")
	private Long number;
	
	@Column(name = "code")
	private String code;
}
```
```
public interface IProfileRepository extends JpaRepository<Profile, ProfileId> {
	
}

```
**Expected behavior**
The use of composite primary key through annotation @EmbeddedId. 
**Actual behavior**
This is the console error:
Caused by: java.lang.IllegalArgumentException: Currently only Entities with the @Id annotation are supported. 

**To Reproduce**
1. Create new Quarkus app with: Hibernate ORM and Quarkus Extension for Spring Data JPA API dependencies. For DB I used Oracle (but the behaviour is the same at PostgreSQL)
2. Add these classes
3. run mvn quarkus:dev

**Configuration**
```properties
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.username=user
quarkus.datasource.password=pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/demo
quarkus.hibernate-orm.database.generation=drop-and-create

```

**Screenshots**
None

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Microsoft Windows [Version 10.0.17763.1282]
 - Output of `java -version`:  openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
Libraries:
quarkus-hibernate-orm
quarkus-jdbc-postgresql / ojdbc8
quarkus-spring-data-jpa

**Comment by hivl** [comment]
is there some progress on this issue?

**Comment by delmobispo** [comment]
is there some progress on this issue?

**Comment by famod** [comment]
I'm having a look!
