### ISSUE TITLE
AWS/S3 Transport TrustStore configuration

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#10888]
**Description**
Currently you can only configure the KeyStore for the AWS/S3 Client. But i would also like to configure the TrustStore in the same way.

**Comment by antonwiens** [comment]
I think the field tlsManagerProvider should be split in keyTlsManagersProvider and trustTlsManagersProvider, so you can specify stores seperatly in [SyncHttpClientConfig](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-services/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/SyncHttpClientConfig.java).

Similar to [this](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-services/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientTransportRecorder.java#L64) line in the AmazonClientTransportRecorder, the tlsTrustManagerProvider needs to be set.

I don't know how to implement a test for this, yet. But maybe with some guidance or examples to look at i could implement these fast. 


@gsmet Do you think i could try to implement this?

**Comment by gsmet** [comment]
@antonwiens sure, I would say you could start by implementing it. We have a few tests around implementing trust stores but it might not be easy to test them with the Amazon infrastructure.

If we don't break the current behavior and you can check manually things work, that would be good enough as a first step.

**Comment by antonwiens** [comment]
@gsmet I closed this issue, but do you want to add a milestone to it or something else?

**Comment by gsmet** [comment]
@antonwiens done, thanks!
