### ISSUE TITLE
Reactive Routes result are not registered for reflection

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#10893]
When a reactive route returns:

* any non-string, non-buffer, non-Uni, non-Multi return type - the class must be registered for reflection
* any Uni or Multi of non-string, non-buffer - the class must be registered for reflection (`T` in `Uni<T>`

**Comment by mkouba** [comment]
Hm, we should also process a non-string, non-buffer method parameter annotated with `@Body`.
