### ISSUE TITLE
Regression: Various YAML configuration issues in 1.6.1.Final

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#10916]
Please allow me to skip the issue-template for this since it has already been taken care of in `smallrye-config` 1.8.5 which Quarkus should update to ASAP when that version is released.
See:
- https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/1.2E6.2E1.3A.20config.20yaml.20problems
- https://github.com/smallrye/smallrye-config/pull/360
- https://github.com/smallrye/smallrye-config/pull/361
- https://github.com/smallrye/smallrye-config/pull/362

C&P of two manifestion of those problems:
```
11:36:10,778 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[2]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,778 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[1]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,778 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[4]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,778 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[3]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[5]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.protocols.[1]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.protocols.[0]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.log.category.liquibase.changelog.ChangeSet.level" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.log.category.com.somecompany.someproject.middleware.level" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
11:36:10,779 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.ssl.cipher-suites.[0]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo
```
Those `.[x]`-warnings are actually false negatives but the loglevel related warnings are correct.

**Temporary Workaround:**
Add this to your Maven `dependencyManagement`, _before_ `quarkus-bom` or `quarkus-universe-bom`:
```
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-yaml</artifactId>
    <version>1.8.1</version>
</dependency>
```

/cc @radcortez @geoand @gsmet

**Comment by geoand** [comment]
@radcortez are you planning on looking into this or should I?

**Comment by radcortez** [comment]
@geoand already did. 

These issues are localised only in the YAML Config Source, so it is easy to workaround by downgrading to the last dependency like stated by @famod without affecting the configuration core.

All the reported issues are already fixed in SmallRye Config and just require a release and minor bump in the Quarkus dependency.

@famod Thank you for all the help and report!

**Comment by geoand** [comment]
Excellent, thanks @radcortez

**Comment by famod** [comment]
> @famod Thank you for all the help and report!

You're welcome! We also have to thank @tkalmar for his support.
And thank you for reacting so quickly!

**Comment by wjglerum** [comment]
Thanks for reporting and finding the underlying issue, we were also encountering the same behaviour after upgrading to 1.6.1

**Comment by radcortez** [comment]
@famod @tkalmar @wjglerum did any of you find anything else? If not, I can push a release of SmallRye Config.

**Comment by famod** [comment]
@radcortez not on my side, but we updated just yesterday. I am not "at work" today so I don't know whether anything new popped up.
Since there is a workaround and @gsmet assigned it to 1.7.0 (and not flagged it with `backport?`), I personally could wait until next week or so.

**Comment by radcortez** [comment]
Ok :)

**Comment by gsmet** [comment]
Yeah, unless something critical with no workaround comes up, I won't do an 1.6.2.

**Comment by famod** [comment]
@radcortez I just realized that 1.7.0.CR1 is already slated for the day after tomorrow.

I guess it is not a showstopper if it misses CR1 (and lands in Final instead), but it would be great if you could manage to get the update of SmallRye Config into CR1.

**Comment by gsmet** [comment]
Note that I will be a bit nervous to upgrade SmallRye Config post CR1 so let's try to get this in before CR1 please.

**Comment by radcortez** [comment]
Yes, all the fixes are in. I just need to push the release and do the update. @famod you were able to confirm that the fixes, did indeed solve the problems, right?

**Comment by famod** [comment]
> I just need to push the release and do the update. @famod you were able to confirm that the fixes, did indeed solve the problems, right?

Unfortunately I have not yet checked your fixes. Do you have a SNAPSHOT-release somewhere?
I would need to focus on the first two fixes since my team is not affected by the third one.

**Comment by radcortez** [comment]
Yes, I can push one to Central.

**Comment by radcortez** [comment]
Ok 1.8.5-SNAPSHOT should be available here: https://oss.sonatype.org/content/repositories/snapshots/

**Comment by tkalmar** [comment]
@radcortez I can confirm, that this snapshot fixes the regressions. Excellent work.

**Comment by radcortez** [comment]
@tkalmar Thank you very much for checking. Ok pushing a stable release!

**Comment by wjglerum** [comment]
Can confirm that the snapshot release fixes the regressions indeed, thanks @radcortez!

**Comment by radcortez** [comment]
@wjglerum Thanks for checking :)

**Comment by famod** [comment]
Thanks all! This is how the community should work.

**Comment by radcortez** [comment]
> Thanks all! This is how the community should work.

Indeed :)
