### ISSUE TITLE
Create new Project should use the Extension Registry API

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#10922]
**Description**
`quarkus:list-extensions` and `quarkus:add-extension` already use the Extension Registry API. It would be nice if the `quarkus:create` also used it. 
 
**Implementation ideas**

This part is basically what needs to be revisited: 

https://github.com/quarkusio/quarkus/blob/103498de0a55364cd07533c4c78613c569405d2e/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/CreateProjectCommandHandler.java#L64-L87

Check `ListExtensionsCommandHandler.java` and `AddExtensionCommandHandler.java` to understand how to use the `ExtensionRegistry` API.

**Comment by sladyn98** [comment]
@gastaldi Working on this if its not taken up yet :+1:

**Comment by viveksahu26** [comment]
I am beginner in this issue, Can you please suggest me, how to get started..

**Comment by gastaldi** [comment]
@viveksahu26 I think @sladyn98 is already working on it? Can you confirm @sladyn98?

**Comment by gastaldi** [comment]
@viveksahu26 anyway, I'd suggest you to read https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md first and then see if the instructions in https://github.com/quarkusio/quarkus/issues/10922#issue-664152770 help

**Comment by ejba** [comment]
Hi everyone,

@sladyn98 @viveksahu26 are you already working on this issue?

**Comment by viveksahu26** [comment]
> Hi everyone,
> 
> @sladyn98 @viveksahu26 are you already working on this issue? 

No I am not working on it..

**Comment by gastaldi** [comment]
Closing as this should be fulfilled by @aloubyansky's work in #12422
