### ISSUE TITLE
[jsonb] enum collection serialization with an enum value starting with _

### ISSUE THREAD

**Issue by tnmtechnologies** [quarkusio/quarkus#10942]
**Describe the bug**
An enum value name starts with an underscore charater (eg _4TEST("4test") ).
4test is the string we want in the json payload.
A JsonbTypeAdapter is defined in order to translate values from and to json.
Translation works fine for an enum type attribute :
- enum value _4TEST is translated to json 4test
- 4test json value is translated to enum value _4TEST

Unfortunately, it doesn't work for collections of the enum type.

**Expected behavior**

````json
[{"description":"Winter fruit","families":["simple","complex","aggregate","4test"],"family":"simple","name":"Apple"},
{"description":"Tropical fruit","families":["simple","complex","aggregate","4test"],"family":"complex","name":"Pineapple"},
{"description":"Unknown fruit","families":["simple","complex","aggregate","4test"],"family":"4test","name":"Unknown"}]

````

**Actual behavior**

````json
[{"description":"Winter fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"simple","name":"Apple"},
{"description":"Tropical fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"complex","name":"Pineapple"},
{"description":"Unknown fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"4test","name":"Unknown"}]

````

**To Reproduce**
For our tests, we use the example in he module rest-json-quickstart in quarkus-quickstarts repository.
We added 2 attributes to the Fruit bean, a family attribute (enum Family) and a families attribute (Set<Family)>).
The branch https://github.com/tnmtechnologies/quarkus-quickstarts/tree/issue/enum_serialization_collections
The commit https://github.com/tnmtechnologies/quarkus-quickstarts/commit/97de35a6bf60905cfb74cee8153b6beeb0735c2a

We didn't update the tests. So they fail.

**Configuration**

**Screenshots**
A wireshark capture
```
GET /fruits HTTP/1.1
Accept: */*
Host: localhost:8081
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.12 (Java/1.8.0_242)
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Content-Length: 361
Content-Type: application/json

[{"description":"Winter fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"simple","name":"Apple"},{"description":"Tropical fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"complex","name":"Pineapple"},{"description":"Unknown fruit","families":["SIMPLE","COMPLEX","AGGREGATE","_4TEST"],"family":"4test","name":"Unknown"}]
```

**Environment (please complete the following information):**
 - Quarkus version 1.6.1.Final 

**Additional context**
The enum value cannot be renamed because it is automatically generated from OpenAPI 3.x files we don't master.

**Comment by geoand** [comment]
cc @aguibert

**Comment by ketoketo** [comment]
@tnmtechnologies 
It seems to me that you need to define and configure JsonbTypeAdapter in your collections of the enum type as well.
If you do so, the behavior is as expected.
I've written [sample code](https://github.com/ketoketo/quarkus-quickstarts/blob/issue/enum_serialization_collections/rest-json-quickstart/src/main/java/org/acme/rest/json/Fruit.java#L21-L22) to illustrate this.

**Comment by tnmtechnologies** [comment]
Thank you very much @ketoketo for your fix. I missed the JsonArray for the BeanAdapter. 
Final source code is available in this branch https://github.com/tnmtechnologies/quarkus-quickstarts/tree/issue/enum_serialization_collections .
