### ISSUE TITLE
Update Protocol Buffer library

### ISSUE THREAD

**Issue by mthmulders** [quarkusio/quarkus#10947]
**Description**
The Quarkus Universe BOM declares version 3.6.1 of the `com.google.protobuf:protobuf-java` artifact. This version uses illegal reflective access, which causes warnings in Java 9 and up. According to https://github.com/protocolbuffers/protobuf/issues/3781, fixed in January 2019.

**Implementation ideas**
Update the version declaration of `com.google.protobuf:protobuf-java` to the most recent version, 3.12.3 at this moment. I'm willing to provide a pull request for this, if necessary. Just need a pointer where the version is defined :-)

**Comment by mthmulders** [comment]
Maybe a duplicate of #10214 since that already upgrades Protocol Buffers to 3.11.x...

**Comment by jaikiran** [comment]
> Update the version declaration of com.google.protobuf:protobuf-java to the most recent version, 3.12.3 at this moment

Perhaps @michalszynkiewicz would know if we should move to 3.12.x of this library?

**Comment by michalszynkiewicz** [comment]
updating all grpc-related things is on my todo list, I am testing an update to 3.12.2/3.12.3, will do a PR if it works

**Comment by mthmulders** [comment]
Amazing, thanks a lot!
