### ISSUE TITLE
Absolute paths in pom.xml

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#10953]
**Description**
In https://github.com/quarkusio/quarkus/blob/master/integration-tests/maven/src/test/resources/projects/project-with-extension/runner/pom.xml there are 3 instances of absolute paths.

https://github.com/quarkusio/quarkus/blob/42dbdd05cd20ef1e82ad62e6617a48e8ea9100c8/integration-tests/maven/src/test/resources/projects/project-with-extension/runner/pom.xml#L52

https://github.com/quarkusio/quarkus/blob/42dbdd05cd20ef1e82ad62e6617a48e8ea9100c8/integration-tests/maven/src/test/resources/projects/project-with-extension/runner/pom.xml#L115

https://github.com/quarkusio/quarkus/blob/42dbdd05cd20ef1e82ad62e6617a48e8ea9100c8/integration-tests/maven/src/test/resources/projects/project-with-extension/runner/pom.xml#L117

**Implementation ideas**
`maven.home` should probably be `<maven.home>${maven.home}</maven.home>` and `native.image.path` should probably be `<native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>`

**Comment by geoand** [comment]
@aloubyansky seems like an oversight :)

**Comment by aloubyansky** [comment]
omg

**Comment by gsmet** [comment]
@aloubyansky can you make sure we fix this before Thursday? Thanks!

**Comment by aloubyansky** [comment]
PR opened @gsmet
