### ISSUE TITLE
[container-image-docker] Add additional params to docker build command

### ISSUE THREAD

**Issue by panchitoboy** [quarkusio/quarkus#10966]
**Description**

It would be helpfull to have the option to configure the build command.

In my enteprise, we use gitlab. And for benefit from the docker layer cache we need to call the command docker build with --cache-from 

https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#making-docker-in-docker-builds-faster-with-docker-layer-caching

**Implementation ideas**

I think that would be great to add :

quarkus.docker.cache-from or quarkus.docker.build (for a more generic solution)

**Comment by geoand** [comment]
#10978 adds support for `--cache-from`. 

I prefer to add explicit support for flags because it makes it a lot easier for users to see the available options and not end up with an invalid `docker build` command.
