### ISSUE TITLE
Can't inject ManagedExecutor since quarkus 1.6.0

### ISSUE THREAD

**Issue by parkee** [quarkusio/quarkus#10963]
**Describe the bug**
I'm trying to inject a ManagedExecutor (using Kotlin and injecting into `@Singleton` bean that extends `MutinyExampleServiceGrpc.ExampleServiceImplBase` if that matters) and get 
```
Parameter specified as non-null is null: method com.example.Example.<init>, parameter managedExecutor"
```
I tried both constructor injection as well as field injection via `lateinit var`

**Expected behavior**
ManagedExecutor is injected

**Actual behavior**
ManagedExecutor is not injected to my bean (both 1.6.0.Final and 1.6.1.Final)
But it's injected successfully if I change the version to 1.5.2.Final

**Comment by stuartwdouglas** [comment]
Does your project depend on quarkus-smallrye-context-propagation? I think there were some fixes around this where previously is may have been accidentally included as a transitive dep in 1.5.

**Comment by parkee** [comment]
@stuartwdouglas 
yes, basically as soon as I switch from 1.6.1 to 1.5.2 version (without any other changes) it starts working as expected, so I suppose my configuration is correct.

**Comment by geoand** [comment]
Seems similar to: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Sporadic.20CDI.20NPE
