### ISSUE TITLE
add a way to configure "plugins" and "listeners" for the quartz scheduler 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#10962]
**Description**

Quartz has two concepts of listeners and plugins which I think can be useful to add things like Logging, Tracking job execution history in an event store, database etc: 

Example of the common used plugin is the [LoggingHistoryPlugin](https://github.com/quartz-scheduler/quartz/blob/d42fb7770f287afbf91f6629d90e7698761ad7d8/quartz-plugins/src/main/java/org/quartz/plugins/history/LoggingJobHistoryPlugin.java)

**Implementation ideas**

Add the two entries i.e "listeners" and "plugins" in [QuartzBuildTimeConfig](https://github.com/quarkusio/quarkus/blob/ac788aafbf9f01908aa379a29d91d0d67dec36f9/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java). Their type can be a "Map<String, Map<String, String>>", allowing for customization of different properties a listener / plugin can have.  

We just have to be add a validation that the "class" key is there in the second Map cause this is what will define the listener / plugin class which will have to be registered for reflection so that it works in native mode.

The configuration will need to be mapped to corresponding Quartz configuration see https://github.com/quarkusio/quarkus/blob/ac788aafbf9f01908aa379a29d91d0d67dec36f9/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L288. 

See Quartz listener / plugin configuration references:
- http://www.quartz-scheduler.org/documentation/quartz-2.2.2/configuration/ConfigListeners.html
- http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigPlugins.html

/cc @mkouba

**Comment by mkouba** [comment]
I think that programmatic registration during application startup would make more sense, i.e. something like:

```java
@IfBuildProfile("prod") // only register the listener if in production mode
class MyListenerManager {

   void onStart(StartupEvent event, org.quartz.Scheduler scheduler, @ConfigProperty(name = "myListerner.propName") String propValue) {
      scheduler.getListenerManager().addJobListener(new MyJobListener(propValue));
   }
}
```
BTW no registration for reflection should be needed if registering listeners this way.

**Comment by machi1990** [comment]
> I think that programmatic registration during application startup would make more sense, i.e. something like:
 
> ```java
> @IfBuildProfile("prod") // only register the listener if in production mode
> class MyListenerManager {
> 
>    void onStart(StartupEvent event, org.quartz.Scheduler scheduler, @ConfigProperty(name = "myListerner.propName") String propValue) {
>       scheduler.getListenerManager().addJobListener(new MyJobListener(propValue));
>    }
> }
> ```

I think this can be achieved even now, but having it done via the our configuration system is a plus too for users not looking to interact directly with the quartz  `Scheduler`.
 
> BTW no registration for reflection should be needed if registering listeners this way.

Agreed.

**Comment by mkouba** [comment]
> I think this can be achieved even now

Yes, this snippet should work fine.

> but having it done via the our configuration system is a plus too for users not looking to interact directly with the quartz Scheduler

My point is that the "config way" is more error-prone, requires reflection registration, and possibly some validation whether a class implements the expected interface would be needed. And since there exists a "programmatic way" that covers all required use cases (profiles, additional config properties, etc.) I don't see a big value in adding more quartz-specific config stuff.

Alternatively, we could automatically register all listeners and plugins that are also beans. But this would not work for third-party libs of course.

**Comment by machi1990** [comment]
> > but having it done via the our configuration system is a plus too for users not looking to interact directly with the quartz Scheduler
> 
> My point is that the "config way" is more error-prone, requires reflection registration, and possibly some validation whether a class implements the expected interface would be needed. And since there exists a "programmatic way" that covers all required use cases (profiles, additional config properties, etc.) I don't see a big value in adding more quartz-specific config stuff.

The value was for having the plugin / listener registration work out of the box (and users not having to think how they do) and all that's needed is correct configuration. I do not see any issue with performing validations, that's what the build time phase is for and it certainly will not cost a thing.

Finally, this is not a pressing thing to have though as it can be achieved programmatic. Happy to point users in this direction.

**Comment by mkouba** [comment]
> Finally, this is not a pressing thing to have though as it can be achieved programmatic. Happy to point users in this direction.

I don't want to sound like I want to "stop this effort" ;-). I'm just trying to understand the use case and pros and cons. 

Speaking of `Map<String, Map<String, String>>` - what would a properties file example look like?

**Comment by machi1990** [comment]
> > Finally, this is not a pressing thing to have though as it can be achieved programmatic. Happy to point users in this direction.
> 
> I don't want to sound like I want to "stop this effort" ;-). I'm just trying to understand the use case and pros and cons.
> 

Sure :-) 

> Speaking of `Map<String, Map<String, String>>` - what would a properties file example look like?

I think something like: 

```
# first listener
quarkus.quartz.listeners.<listener1-name>.class=org.acme.MyListerner
quarkus.quartz.listeners.<listener1-name>.<listener1-property-1>=property-value-1
quarkus.quartz.listeners.<listener1-name>.<listener1-property-2>=property-value-2

# another listener
quarkus.quartz.listeners.<listener2-name>.<listener2-property-2>=org.acme.MyOtherListener
quarkus.quartz.listeners.<listener2-name>.<listener2-property-2>=property-value-2
quarkus.quartz.listeners.<listener2-name>.<listener2-property-2>=property-value-2
```

The same for plugins.

**Comment by marcelorubim** [comment]
I thought of using Map<String, Map<String, String>, but in the end, I did this way. I think it's better for reading the code, and I can keep the class name property apart from the real Map (props names and values)

```java
    /**
     * The named trigged listeners list
     */
    @ConfigItem(name = "triggerListener")
    @ConfigDocMapKey("namedTriggerListener")
    public Map<String, QuartzAdditionalPropsConfig> triggerListeners;
```


```java
@ConfigGroup
public class QuartzAdditionalPropsConfig {
    /**
     * Class name for the configuration.
     */
    @ConfigItem(name = "class")
    public String clazz;

    /**
     * The props name and the values for the props.
     */
    @ConfigDocSection
    @ConfigDocMapKey("propsAndValue")
    @ConfigItem(name = ConfigItem.PARENT)
    public Map<String, String> propsValue;
}
```

**Comment by machi1990** [comment]
> Ok, I understand now. So I think that we should document both approaches (config and programmatic). And we should definitely validate the class values (e.g. whether the required interface is implemented).

Right!

> 
> > We could also make "listeners" properties runtime configurable by moving them in the Runtime config object.
> 
> That way you would not be able to register the class for registration though. Or am I missing something?

I was only thinking of other properties, not the "class". I.e split the proposed configuration into runtime overridable properties (the rest) and build time ones (in this case the "class" property). As most of the other properties can be overriden during runtime.

**Comment by marcelorubim** [comment]
![image](https://user-images.githubusercontent.com/32526483/88529935-0c547000-cfd7-11ea-95cb-e0275fae1bd9.png)
