### ISSUE TITLE
Remote development does not resync on application.properties change

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#10969]
**Describe the bug**
`mvn quarkus:remote-dev` does not recognize when only an application.properties file changes (and no other changes). Therefore, no code sync happens. However, if I change source code and application.properties, the property file does get synced.

JDK 11, Quarkus 1.6.1.Final

**Expected behavior**
When I change an application.properties file and hit the REST endpoint, I expect to see the new property applied.

**Actual behavior**
The property does not get synced and therefore is not applied.

**To Reproduce**
Feel free to start [here](https://github.com/jclingan/quarkus-remote-dev), which is a bare-minimum remote-dev project. Just add code to inject the greeting ("Hello") from a value in the application.properties. Once that works, just change the greeting in application.properties and reload the endpoint. application.properties will not be re-synced.

**Additional context**
I'm a really nice guy.

**Comment by stuartwdouglas** [comment]
I could not reproduce this reliably, but I think it may be a manifestation of the pre scan step being registered multiple times.
