### ISSUE TITLE
Add lombok to the bom

### ISSUE THREAD

**Issue by juanmbellini** [quarkusio/quarkus#10971]
**Description**
Add lombok as a managed dependency in quarkus-bom. This allows using lombok in a quarkus project without specifying its version.

**Implementation ideas**
Just add a version and the dependency in https://github.com/quarkusio/quarkus/blob/master/bom/application/pom.xml, similar to what spring boot does in https://github.com/spring-projects/spring-boot/blob/2.2.x/spring-boot-project/spring-boot-dependencies/pom.xml

**Comment by gsmet** [comment]
We don't specify versions in the BOM unless there is a strong reason i.e. we have the component included in one of our extensions.

It doesn't have sense to enforce versions if we don't have a reason to do so.

Spring maybe has some sort of dependencies to Lombok but we don't at the moment.
