### ISSUE TITLE
Offer a Redis extension based on Lettuce

### ISSUE THREAD

**Issue by l2dy** [quarkusio/quarkus#10976]
**Describe the extension**
Offer a Redis extension based on [Lettuce](https://github.com/lettuce-io/lettuce-core), which has official support for GraalVM Native Images since v[5.3.2](https://github.com/lettuce-io/lettuce-core/releases/tag/5.3.2.RELEASE).

Lettuce development started earlier and I think it's more mature than the Vert.x Redis client.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Additional context**
See also https://github.com/quarkusio/quarkus/issues/4453.

**Comment by geoand** [comment]
Hi,

Quarkus 1.7 will ship with a Redis extension based on Vert.x - see https://github.com/quarkusio/quarkus/blob/76a6fcbf267f6e2646266420135166b13ab5aee0/docs/src/main/asciidoc/redis.adoc.

Is there a specific reason why you would like to have a Lettuce based one?

**Comment by l2dy** [comment]
Because I believe Lettuce is more mature for production than the Vert.x Redis client. Reasons below.

1) Lettuce has more commits, active contributors, and probably more production users.
2) The Vert.x Redis client went through a major refactor and got it backported to 3.9 in March this year, so less production users would have been able to test it thoroughly.
3) The Vert.x Redis client can't handle authentication in cluster mode, as [reported](https://github.com/vert-x3/vertx-redis-client/issues/177#issuecomment-614683857) in their issue tracker. Meanwhile, Lettuce has support for SSL and authentication in cluster mode since 4.2 (released in 2016), and many bugs have been fixed since.

**Comment by geoand** [comment]
Thanks for the input.

I think it's unlikely we will offer a second Redis extension (although anyone interested could code up such an extension if they think it's worth it).

cc @vietj @pmlopes to get their pespective on vert.x vs lettuce and shed some more light :)

**Comment by machi1990** [comment]
@l2dy thanks for opening the issue. I agree with what @geoand. 

A bit of context, early on when https://github.com/quarkusio/quarkus/issues/4453 was opened, I considered using Lettuce and offering a Redis Client on top of it,  https://github.com/quarkusio/quarkus/pull/4882. I managed to come up with a working version both in native and JVM mode (even before the recent added GraalVM support in v5.3.2) but I ran through some issues and the main ones being:
- We wanted to have only one Netty EventLoop and I could not find a way to configured it at that time.
- Lettuce usage of Reactor, we had plans for Mutiny 

After a chat with the team, we decided to go with Vert.x Redis Client. 

The code for Lettuce integration is still available on my branch https://github.com/machi1990/quarkus/tree/feat/redis-extension and functional, if you are looking to integrate Lettuce on your project.

**Comment by l2dy** [comment]
Thanks for explaining the background, I was not aware of that chat.

> I think it's unlikely we will offer a second Redis extension (although anyone interested could code up such an extension if they think it's worth it).

> @l2dy thanks for opening the issue. I agree with what @geoand.

Should we close the issue then? There seems to be no intention to support another Redis extension officially.
