### ISSUE TITLE
offer full fledged, simple to use Permissions

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#10988]
Hi,

I have read:
https://quarkus.io/guides/security-keycloak-authorization
https://quarkus.io/guides/security
https://github.com/quarkusio/quarkus/pull/4487

What's the current state of permissions? I would want to make STRONG use of permissions. Basically, for every button / page / functionality on the frontend, the frontend should send a request to the backend asking if the currently locked in, authenticated user (token) has sufficient PERMISSIONS to access it. But it seems permissions have just been implemented recently by @stuartwdouglas ?

```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public CompletionStage<List<Permission>> get() {
        return identity.checkPermission(new AuthPermission("{resource_name}"))
                .thenCompose(granted -> {
                    if (granted) {
                        return CompletableFuture.completedFuture(doGetState());
                    }
                    throw new ForbiddenException();
                });
```

So I would have to create a NEW permission object every time a permission request comes in, is that correct?

**Comment by sberyozkin** [comment]
@MarcusBiel Is it a question or an enhancement request ? Can you clarify please what exactly you'd like to be enhanced ? CC @stuartwdouglas

**Comment by MarcusBiel** [comment]
Sorry, to be honest I am not so deep into Quarkus Permissions myself yet, this was based on information I got from a freelancer working for me - from a more abstract point of view, what I would want is something like:
boolean hasPermission = identity.hasPermission(WRITE_EMAIL_PERMISSION);

**Comment by ydalekorey** [comment]
Actually I would not say that we need permissions in quarkus
We need some general purpose mechanism that can be adapted by developers to theirs needs
It would be nice to have some annotation with more general name like @Secured or @Authorized or @HasAuthority
And the developers would be able to adapt such mechanism for Auth0 permissions as well.
I can easily make quarkus @Role annotation to accept permissions but it will look weird.
Maybe Quarkus already have some extension points to implement our own security checks but we do not know about them

**Comment by sberyozkin** [comment]
@ydalekorey In Quarkus one can register a custom `SecurtyIdentityAugmentor`, for example:

https://quarkus.io/guides/security-customization#security-identity-customization

The main idea behind it is to enhance the identity but one can easily check the existing token, example, with something like `identity.getTokenCredential(IdTokenCredential.class)` and check some individual claims and throw `AuthenticationFailedException` if needed, etc. Maybe this should be documented as well.

**Comment by ydalekorey** [comment]
Thanks @sberyozkin . Looks like in addition to an Augumentor that extracts auth0 permissions and adds it into SecurityIdentity I also need to create my custom PermissionsAllowed annotation that behaves just like RollesAllowed one but uses extracted permission instead of roles to restrict access. How can I register my own custom security annotation in Quarkus security engine?

**Comment by MarcusBiel** [comment]
This issue is over one year old now. Still no updates? :(

**Comment by stuartwdouglas** [comment]
So what would you actually want here?

Something like:

`@RequiresPermission(value=MyPermission.class, params = {"my", "permission", "ctor", "params"})`

Then SecurityIdentity.checkPermission would be invoked with the specified permission, and it is up to the user to provide permission checkers through SecurityIdentityAugmentor?

**Comment by ydalekorey** [comment]
I think string values for permission will be enough.
Something like this:
@RequiresPermissions({"users:add", "users:edit"})

But maybe it will be even better to some more general purpose word like "authority" because "permission" is too specific and some systems have notion of permissions and some ones have not. So it would be perfect to  have SecurityIdentity.checkAuthority and SecurityIdentity.getAuthorities methods. Then Quarkus users can adjust authorities according to theirs needs: in some cases "authority" will mean "role", in other cases it will mean "permission" or "policy" or whatever. For those "authorities" it would be nice to have something like @HasAuthorities or @RequiresAuthorities annotation that works just like @RolesAllowed but check authorities instead of roles.

**Comment by stuartwdouglas** [comment]
If it is just a string how is it different to a role (I know conceptually you can say they are different, but from an implementation point of view)?

In my approach above `MyPermission` is an instance of `java.security.Permission`, and permission checks would be done via `implies` which allows you to use custom logic. 

We could also support method parameters in the permission constructor, so you could have:

```
class EditUserPermission extends Permission {
EditUserPermission(User user) {...
}
```

Then the method:

```
@RequiresPermission(value=EditUserPermission.class, params="${theUser}")
public void edit(User theUser) {

}
```

This allows you to do permission checks based on the actual objects being passed into the method (i.e. you could potentially be able to edit some users, but not all of them).

@MarcusBiel does this sound like what you are after?

**Comment by MarcusBiel** [comment]
I am fully with @ydalekorey

**Comment by stuartwdouglas** [comment]
So if you just defined your permissions as roles namespaced as permission: (e.g permission:user:add) what is the difference between a role and a permission?

**Comment by stuartwdouglas** [comment]
But from a functionality standpoint I could just copy/paste the @RolesAllowed code and re-name it @PermissionsAllowed, add a `hasPermission(String)` method to `SecurityIdentity`. I.e. the functionality is exactly the same, you are just calling them permissions instead of roles?

If so you can totally make this work at the moment, e.g. define a permission as a role that starts with `permission:`, and use a `SecurityIdentityAugmentor` to map from the IDP roles to app specific permissions.

**Comment by ydalekorey** [comment]
Thanks @stuartwdouglas I think that will be nice.

**Comment by v-patil** [comment]
Any plans to add this? Or a good example showing how `SecurityIdentityAugmentor`can be used to achieve this.

**Comment by kmmraj** [comment]
Any plans to add this? For the client_credentials grant type, we have a robotic user, where we need permissions more than ever. There are no different user roles for the robotic user

**Comment by michalvavrik** [comment]
Hi, I think the idea @stuartwdouglas described above with `java.security.Permission` is pretty cool and would also allow greater customization options if need. I'll have a look into this. @sberyozkin no objections against `java.security.Permission` solution (please see Stuart's comments), or do you have another suggestion?

**Comment by sberyozkin** [comment]
Hey @michalvavrik Thanks for starting working on this issue, can you please clarify one thing.

For example, with keycloak authorization, we get a token , it is sent to Keycloak and an authorization decision is returned, and then we checks the permissions, example, https://quarkus.io/guides/security-keycloak-authorization#checking-permissions-programmatically.

What is the goal here, offer a mechanism to simplify checking the permissions returned from the custom SecurityIdentity augmentors, Checks, etc, just by adding adding `@PermissionAllowed("user:read")` ?

Or are we talking about mapping the roles found in SecurityIdentity to permissions like `user:read` ? If yes - how are we going to do it ?

By the way, as far as OIDC tokens are concerned, they can have a roles claim like `admin` but also a scope claim, like `read`/etc. I think we should factor it into the design of this solution, for example, if I write `@PermissionAllowed("admin:print") void printIt()`  then `printIt()` can only be invoked if a token has a role `admin` and a scope `print`

Thanks

**Comment by michalvavrik** [comment]
> Hey @michalvavrik Thanks for starting working on this issue, can you please clarify one thing.
> 
> For example, with keycloak authorization, we get a token , it is sent to Keycloak and an authorization decision is returned, and then we can check the permissions, example, https://quarkus.io/guides/security-keycloak-authorization#checking-permissions-programmatically.
> 

ATM Keycloak authorization permissions are only used for HTTP policy or the programmatic check mentioned by you; if we implement this, you could also use `@PermissionsAllowed` annotation on the endpoints. It could be more comfortable at some cases (for similar reasons as you use RBAC annotations, you could do that programmatically too, after all).

But if I understand it, you can use `quarkus.oidc.webapp-tenant.roles.source=accesstoken` to map permissions to role and than use `@RolesAllowed`, right? That could bring quite a confusion, I don't know how to implement it till I do more research. For that reason and the PR complexity, Keycloak authorization part can't be done in the first PR.

> What is the goal here, offer a mechanism to simplify checking the permissions returned from the custom SecurityIdentity augmentors, Checks, etc, just by adding adding `@PermissionAllowed("user:read")` instead of having to write the code like https://quarkus.io/guides/security-keycloak-authorization#checking-permissions-programmatically ?
> 

Here we must divide reasons I'm looking into this and reasons mentioned in the issue description and comments above:

- my understanding of comments/issue desc.: 
  - permissions are conceptually different, so you can use permissions as roles via `SecurityIdentityAugmentor`, but you need to tell your colleague that it's a hack 
  - `SecurityIdentityAugmentor` gives you option to map permissions to roles or add permissions, but you can only secure methods with roles
- my reasons:
  - we could allow users to pass their own `java.security.Permission` implementation. I think that is something you can't do at the moment unless you implement security yourselves. Providing your own `Permission` gives you options.
  - roles -> permission -> action hierarchy provides clearer granularity than mapping everything to roles; it is also concept known from other frameworks (which is not a reason why we should do it, but the reason to ask question - why does it exists there?)
  - it gives an option to pass inside request/method parameters, which is similar to what I was doing when writing Spring microservices - we used AOP & Spring EL expressions and you could secure method based on passed params etc. (please see Stuart's comment https://github.com/quarkusio/quarkus/issues/10988#issuecomment-902230311). I don't think it's very efficient as using constructor forces you to create a new permission instance every single time you perform a check, but it gives you an option you do not have right now unless you write it yourselves. We could do:
    - for security checks performed by CDI interceptor, you can pass in method params
    - for RESTEasy Reactive endpoints, you can pass in request parameters (I realize that's confusing, maybe we won't go there at all!)


> Or are we talking about mapping the roles found in SecurityIdentity to permissions like `user:read` ? If yes - how are we going to do it ?

I though about it a long time before I started implementing the issue - way I understand comments above is `user:read` is permission `user` and action `read` as based on `java.security.Permission` you always need a permission name and you may add permission actions.

I think you are hinting to https://github.com/quarkusio/quarkus/issues/12219#issuecomment-1370850578, my intention (which is subject to change based on our discussion in this issue) was to provide 2 ways to add permission that can be used with `@PermissionsAllowed`:

- add an example how to add permissions to the identity using `SecurityIdentityAugmentor`, this will require change change in the `io.quarkus.security.identity.SecurityIdentity` is there is no permissions getter (you can add permissions, but you can't get them)
- add configuration option that should close https://github.com/quarkusio/quarkus/issues/12219, I was thinking:
```
quarkus.security.roles."my-role-name".permissions.permission-name-123.classes=org.acme.CustomPermission,io.quarkus.security.identity.StringPermission
quarkus.security.roles."my-role-name".permissions.permission-name-123=action1,action2,action3
# no permission class -> default to StringPermission
quarkus.security.roles."my-role-name".permissions.permission-name-456=action1,action2,action9
```

> By the way, as far as OIDC tokens are concerned, they can have a roles claim like `admin` but also a scope claim, like `read`/etc. I think we should factor it into the design of this solution, for example, if I write `@PermissionAllowed("admin:print") void printIt()` then `printIt()` can only be invoked if a token has a role `admin` and a scope `print`

Sure, we can configure actions too, but I'm sorry, I need more time with OIDC before I can reply to this properly.

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, I'd propose to start with supporting this mapping at the already available HTTP security namespace level, a more generic security namespace support can be added later.
For example, we can already do this for roles:
```
quarkus.http.auth.policy.role-policy1.roles-allowed=user,admin                      

quarkus.http.auth.permission.roles1.paths=/roles-secured/*,/other/*,/api/*          
quarkus.http.auth.permission.roles1.policy=role-policy1
```

so perhaps:

```
quarkus.http.auth.policy.policy1.roles-allowed=user,admin
quarkus.http.auth.policy.policy1.roles-permissions=user:read,print admin:read,write,print

#or/and
quarkus.http.auth.policy.policy1.roles-allowed=user,admin
quarkus.http.auth.policy.policy1.admin-permissions=read,write.print
quarkus.http.auth.policy.policy1.user-permissions=read,print
quarkus.http.auth.policy.policy1.roles-permissions=user:user-permissions admin:admin-permissions
#or something neater :-)

quarkus.http.auth.permission.roles1.paths=/roles-secured/*,/other/*,/api/*     
# RolesAllowed("user") works, but also a finer grained @PermissionAllowed("user:read"), etc works
quarkus.http.auth.permission.roles1.policy=policy1
```

>Sure, we can configure actions too, but I'm sorry, I need more time with OIDC before I can reply to this properly.

Np at all, sure, we can discuss later

**Comment by michalvavrik** [comment]
Sounds good, I'll think about it during the research & implementation (I'm already drafting something).

**Comment by sberyozkin** [comment]
>add an example to docs how to add permissions to the identity using SecurityIdentityAugmentor, this will require change in the io.quarkus.security.identity.SecurityIdentity as there is no permissions getter (you can add permissions, but you can't get them)

That should not be necessary, as we can do
```
QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder(currentIdentity);
builder.addPermission(...);
``` 
but is worth highlighting it indeed.

But what should be possible, I guess, is to create the mapping in `SecurityIdentityAugmentor`, now `SecurityIdentity` has roles, and has permissions, but no relationship can be defined at this level, only at the HTTP Sec policy configuration level.

So IMHO we need to also consider how to enhance SecurityIdentity to allow such a mapping, and then I can for example update `quarkus-oidc` to create a role to scope mapping, etc. Perhaps,
```
QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder(currentIdentity);
builder.addRolePermission("user", "read") - throws ISA if `user` role is not already set, etc
```

**Comment by michalvavrik** [comment]
> That should not be necessary, as we can do
> 
> ```
> QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder(currentIdentity);
> builder.addPermission(...);
> ```

you can add permission (checker), but you can't keep permission checkers added by previous augmentation. There is no limit to number of `SecurityIdentityAugmentor`, so if you adds one, he should have an option to keep permissions added by previous augmentor (e.g. Quarkus one, don't know). That's why we need `List<Function<Permission, Uni<Boolean>>> getPermissionCheckers()` in identity.

**Comment by michalvavrik** [comment]
> So IMHO we need to also consider how to enhance SecurityIdentity to allow such a mapping, and then I can for example update `quarkus-oidc` to create a role to scope mapping, etc. Perhaps,
> 
> ```
> QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder(currentIdentity);
> builder.addRolePermission("user", "read") - adds the `user` role as well if is not already set, etc
> ```

I like that, that could be useful for users.

**Comment by sberyozkin** [comment]
@michalvavrik By the way, I'm not sure now assuming in `@PermissionAllowed("user:read") means that a `user` is a role is a good idea. If both role and permissions should be checked then one just does `@RolesAllowed("user") @PermissionAllowed({"read", "write"})`. Otherwise we'll have problems when real app permissions are named like "user:read"

**Comment by sberyozkin** [comment]
Hmm, but then it won't work if a method can only be invoked by either `user` or `admin` roles, but different permissions available for these roles. So may be we should stick to this convention that `user:read` means that a role `user` needs to have an associated `read` permission

**Comment by michalvavrik** [comment]
> @michalvavrik By the way, I'm not sure now assuming in @PermissionAllowed("user:read")  means that a user is a role is a good idea. If both role and permissions should be checked then one just does @RolesAllowed("user") @PermissionAllowed({"read", "write"}). Otherwise we'll have problems when real app permissions are named like "user:read"
 
&

> Hmm, but then it won't work if a method can only be invoked by either user or admin roles, but different permissions available for these roles. So may be we should stick to this convention that user:read means that a role user needs to have an associated read permission

I thought `@PermissionAllowed({"read", "write"})` is roughly parsed as `var permissionName = "user";String[] actions = new String[] {"read", "write"};` because otherwise what would be a syntax for actions? When you are using permissions, you don't really need to combine it with roles in terms of access of one secured method because we can say _role Admin grants you permission 'resource' with actions 'read', 'write'_.

**Comment by michalvavrik** [comment]
We should leverage `java.security.Permission` that contains actions and currently RBAC annotations can't be combined, so I suppose they should not be combined with `@PermissionsAllowed` either to reduce complexity.
