### ISSUE TITLE
Custom configuration converter for arrays are ignored

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#11012]
**Describe the bug**

You cannot create a configuration converter for an array type. For example, to convert strings to a byte array by decoding base64.

**Expected behavior**

Custom configuration converters for array types are honored.

**Actual behavior**

Custom configuration converters for array types are ignored.

**To Reproduce**
1. Create a converter for `byte[]` by decoding the string value using a base64 decoder.
2. Add configuration value with base64 encoded string.
3. Run application to failure due to the builtin "array of bytes" converter attempting conversion of base64 data.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
        
       Darwin XXX 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

 - Output of `java -version`: 

       java version "11.0.6" 2020-01-14 LTS
       Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
       Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

 - GraalVM version (if different from Java):

       N/A

 - Quarkus version or git rev:

       1.6.1

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

       ------------------------------------------------------------
       Gradle 6.4.1
       ------------------------------------------------------------

       Build time:   2020-05-15 19:43:40 UTC
       Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

       Kotlin:       1.3.71
       Groovy:       2.5.10
       Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
       JVM:          11.0.6 (Oracle Corporation 11.0.6+8-LTS)
       OS:           Mac OS X 10.15.6 x86_64

**Additional context**

**Comment by kdubb** [comment]
It appears this might be a simple fix in `smallrye-config` because `SmallRyeConfig.getConverter` checks if type is an array before looking up custom converters.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Let me have a proper look into this. For now as a workaround, you could call `io.smallrye.config.SmallRyeConfig#getValue(java.lang.String, org.eclipse.microprofile.config.spi.Converter<T>)` and pass in the Converter directly to bypass Converters resolution.
