### ISSUE TITLE
After updating Quarkus from 1.4.1.Final to 1.6.1.Final, org.apache.* is not found

### ISSUE THREAD

**Issue by aksth** [quarkusio/quarkus#11024]
In Quarkus 1.4.1.Final, to use commons-io utilities such as IOUtils, I didn't have to use Apache Commons IO maven dependency. But after updating Quarkus to 1.6.1.Final, I'm getting `org.apache.commons.io.IOUtils` cannot be resolved. So now I have to use `commons-io` maven dependency. Did something related to Apache's commons-io change in between the version 1.4.1.Final and 1.6.1.Final?

**Comment by famod** [comment]
I am pretty sure that this is the reason: There have been some changes to the IDE launcher that has been leaking various dependencies until 1.5.1:

See:

- #9865
- #10067

Works as designed I'd say. Maybe this should be added to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.5 @gsmet?

**Comment by gsmet** [comment]
Yeah, I think it's normal you have to add the dependency yourself.

Dunno if it's really worth a note in the release notes. We don't really track our dependencies and they come and goes.

**Comment by aksth** [comment]
Okay. Thank you.
