### ISSUE TITLE
Securing Quarkus's Prometheus/Microprofile API Endpoint

### ISSUE THREAD

**Issue by edwin** [quarkusio/quarkus#11034]
For a better security, i usually use a different port and a username/password for Prometheus/Microprofile api endpoint.
In other framework, i can use below configuration,
```
management.server.port=8081

management.security.enabled=true
security.user.name=admin
security.user.password=secret
```
Is it possible to achieve the same feature with Quarkus?

**Comment by geoand** [comment]
I wonder if we should allow for easy security configuration of some endpoints like this.

@sberyozkin @stuartwdouglas WDYT?

**Comment by sirAlexander** [comment]
@edwin https://github.com/quarkusio/quarkus/issues/7893

**Comment by edwin** [comment]
> @edwin looks like a replica of #7893

yes, you are correct for the `different management port` part @sirAlexander 
i was hoping if we cannot differentiate the port, at least give some security measurements such as `basic_auth` so that my prometheus can pull the metrics without have to worrying other malicious people might do the same

**Comment by stuartwdouglas** [comment]
You can use the normal permission system to apply security to an endpoint, see https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration

We will likely support multiple endpoints at some point, but it is a fair bit of work and adds a bit of complexity, so I want to make sure there is sufficient demand before implementing it.

**Comment by edwin** [comment]
> You can use the normal permission system to apply security to an endpoint, see https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration

hi @stuartwdouglas got it, 
ive come up with a simple, but hopefully, working solution

```
https://github.com/edwin/quarkus-secure-prometheus-api
```

by using this workaround
```
https://quarkus.io/guides/security-properties
```

thanks for the info
