### ISSUE TITLE
Native image build shows `-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated` message

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#11054]
Native image build shows `-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.` message

I think we should remove these arguments, I will prepare PR for it.

**Comment by machi1990** [comment]
Is this on master? I thought https://github.com/quarkusio/quarkus/pull/10840 should have fixed it. 

/cc @Sanne

**Comment by rsvoboda** [comment]
I'm just looking at that code changes. I see it with my sample apps, but not in all cases, I will check `includeAllTimeZones` is or is not set. Some module didn't throw this warning.

**Comment by rsvoboda** [comment]
I don't do any setup for native arguments, using just defaults

I see this:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /var/lib/jenkins/beefy-scenarios/201-large-static-content/target/201-large-static-content-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 994:992 --rm quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.1.Alpha2-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar 201-large-static-content-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx4g -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace 201-large-static-content-1.0.0-SNAPSHOT-runner
Warning: Ignoring server-mode native-image argument --no-server.
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
[201-large-static-content-1.0.0-SNAPSHOT-runner:68]    classlist:   4,330.75 ms,  0.96 GB
```

mvn clean verify -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g -pl '!002-quarkus-all-extensions' -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.1.Alpha2-java11

**Comment by rsvoboda** [comment]
I will double check on my local machine. But in ~1h on call now.

**Comment by rsvoboda** [comment]
I see it with current Quarkus master - e013d6279c

Steps to reproduce:
```
rm -rf getting-started
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DplatformArtifactId=quarkus-bom \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
cd getting-started
mvn clean verify -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.1.Alpha2-java11
```

**Comment by rsvoboda** [comment]
command string contains `... -H:-AddAllCharsets -H:-IncludeAllTimeZones ...` so @Sanne's change kicks in
But native-image complains about `-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.`

**Comment by geoand** [comment]
I saw this as well. Is someone looking at it?

**Comment by gsmet** [comment]
I'm having a look. So my understanding is that we should drop this entirely?

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/11065 .
