### ISSUE TITLE
Large numbers of security annotations will cause deployment to fail

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#11075]
I noticed this when playing around with my large deployment generator, if you have more than around 1k security annotations you will get the following:

    [ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: org.objectweb.asm.MethodTooLargeException: Method too large: io/quarkus/security/runtime/interceptor/SecurityCheckStorage_878ea92f854303317df5146707e738a696454a31_Synthetic_Bean.create (Ljavax/enterprise/context/spi/CreationalContext;)Lio/quarkus/security/runtime/interceptor/SecurityCheckStorage;

**Comment by stuartwdouglas** [comment]
@geoand I made a start on this here: https://github.com/stuartwdouglas/quarkus/tree/11075 but I need a bit of advice on how to handle the spring security stuff as I am not 100% sure what the semantics are supposed to be.

**Comment by geoand** [comment]
Looking now
