### ISSUE TITLE
In tooling, do not install any extension when there are multiple matches

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#11086]
**Describe the bug**
I think that by default we shouldn't install any extension when there are multiple matches:

We only list then and tell the user that they can use a flag to "accept" installing all

Example of case where you may not want all installed in the end:

```
addExtensions(asList("jdbc"));

✅ Extension io.quarkus:quarkus-agroal has been installed
✅ Extension io.quarkus:quarkus-jdbc-db2 has been installed
✅ Extension io.quarkus:quarkus-jdbc-postgresql has been installed
✅ Extension io.quarkus:quarkus-jdbc-h2 has been installed
✅ Extension io.quarkus:quarkus-jdbc-mariadb has been installed
✅ Extension io.quarkus:quarkus-jdbc-mssql has been installed
✅ Extension io.quarkus:quarkus-jdbc-mysql has been installed
✅ Extension io.quarkus:quarkus-jdbc-derby has been installed
✅ Extension io.quarkus:quarkus-elytron-security-jdbc has been installed
```

**Expected behavior**
Fail and list the matching extensions

**Actual behavior**
They are installed

This new behavior has appeared with the new registry.

**Comment by maxandersen** [comment]
this is broken behavior and should not go out in CR1. needs fixing.

**Comment by ia3andy** [comment]
I had to tweak a test in my PR to be ok with that behavior, depending on which one gets first, this test need to be changed:
https://github.com/ia3andy/quarkus/blob/codestarts-v0/integration-tests/devtools/src/test/java/io/quarkus/devtools/commands/AbstractAddExtensionsTest.java#L166

**Comment by gastaldi** [comment]
I don't think the tests were changed, so it's hard to find this behavior. Also `mvn quarkus:add-extension -Dextensions="Sm??lRye**"` works in 1.6.1.Final, so this behavior is a bit inconsistent

**Comment by ia3andy** [comment]
@gastaldi the behavior was quite consistant:
- pattern search: allow multiple (the user intend to use a pattern, this is not hazardous)
- partial matches, name, ...: fail with the list of matches and tell the user to use a pattern or be more precise

**Comment by ia3andy** [comment]
@gastaldi what does that emoticon mean?

**Comment by gastaldi** [comment]
That I am having a look 😉
