### ISSUE TITLE
Multiple instances of named log handler extention

### ISSUE THREAD

**Issue by zhymke** [quarkusio/quarkus#11089]
**Describe the bug**
I created a named log handler extention. My deployment module returns NamedLogHandlersBuildItem.
Application starts and the handler does it job.

After hot reload one more instance of the handler is register and the job is done twice. On each reload one additional handler instance is created and the handler code is runned multilple times.

**Expected behavior**
After hot reload only single instance of named handler should exists.

**Actual behavior**
After hot reload additional instance of handler is created.

**To Reproduce**
Deployment module:
```java
class NamedLoggingHandler {

    private static final String FEATURE = "amqp";

    @BuildStep
    FeatureBuildItem feature() {
        return new FeatureBuildItem(FEATURE);
    }

    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    NamedLogHandlersBuildItem addCustomHandler(HandlerFactory handlerFactory , Config config) {
        return new NamedLogHandlersBuildItem(handlerFactory .constructHandler(config));
    }

}
```
Runtime module

```java
@Recorder
public class HandlerFactory {
    public RuntimeValue<Map<String, Handler>> constructHandler(Config config) {
        return new RuntimeValue<>(Stream.of(
            new AbstractMap.SimpleEntry<>("handler_name", new LoggingHandler(config)))
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)));

    }
}
```
LoggingHandler - POJO class which extends ExtHandler
Config - quarkus configuration class

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: javac 11.0.7
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.2

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
