### ISSUE TITLE
Externalize default builderImage URL for native image

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#11096]
Currently the default container image for building the native image is hardcoded: https://github.com/quarkusio/quarkus/blob/ee7b838b9929df19ca83565e16e102c30fe5c815/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L137

For product we'd want a different default one. We need to figure out a way to easily modify the property for the product.
E.g. move the the default URL to some easily modifiable properties file.

**Comment by gastaldi** [comment]
Maybe I am missing something, but we could define the `quarkus.native.build-image` property in the _pom.xml_ directly?

**Comment by gsmet** [comment]
Is this sorted out?

**Comment by michalszynkiewicz** [comment]
We have a workaround for the product but we don't have a proper solution for this yet to my knowledge

**Comment by geoand** [comment]
Removing the milestone for the time being
