### ISSUE TITLE
Runner jar is deployed with a classifier that does not match quarkus.package.runner-suffix when building uber-jar

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#11102]
**Describe the bug**

when using the property
```
quarkus.package.runner-suffix=-fitnesse
```
the jar is created with the right suffix (my-artifactId-1.0.0-SNAPSHOT-fitnesse.jar), but it is installed in the local repository as  my-artifactId-1.0.0-SNAPSHOT-runner.jar

mvn install logs: 

```
[INFO] Installing /Projets/my-artifactId/target/my-artifactId-1.0.0-SNAPSHOT-fitnesse.jar to /home/loic/.m2/repository/my-groupId/my-artifactId/1.0.0-SNAPSHOT/my-artifactId-1.0.0-SNAPSHOT-runner.jar
```

This make it impossible to create two jars with different build time configuration.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
either the runner is not attached and it is responsibility of the user to attach it with the build-helper-maven-plugin, either the classifier used to attach the artifact match the quarkus.package.runner-suffix value

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

the classifier is always runner

**To Reproduce**
1. create an empty quarkus project
2. add quarkus.package.uber-jar=true in application.properties
2. mvn install -Dquarkus.package.runner-suffix=-fitnesse
3. observe the local repository content

Edit: this only occurs when quarkus.package.uber-jar=true in application.properties. if not, the runner is not attached.

**Comment by rmanibus** [comment]
it's in io.quarkus.maven.BuildMojo

```
                    if (result.getJar().isUberJar()) {
                        projectHelper.attachArtifact(project, result.getJar().getPath().toFile(), "runner");
                    }
```

https://github.com/quarkusio/quarkus/blob/598e750eb09554411e895158efe63f7a349ff89d/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L236

**Comment by gsmet** [comment]
@stuartwdouglas WDYT, should we take the suffix into account? We would need to drop the leading `-` but I suppose that would be best that ignoring it.

**Comment by gsmet** [comment]
The good news is that we already have a PR: https://github.com/quarkusio/quarkus/pull/11124 :)

**Comment by rmanibus** [comment]
the PR drop the leading "-" if it exist yes :)
