### ISSUE TITLE
Introduce Quarkus Extension Codestart project type

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#11130]
**Description**
It will let user generate Quarkus extension using the Codestart system.

Even if project type exist in Codestart, it may need a few change/renaming to allow this.

**Comment by maxandersen** [comment]
how would this be invoked? -Dcodestart.type=extension or ?

**Comment by ia3andy** [comment]
I guess it would be a new command since the params would be different `create-extension`

**Comment by ia3andy** [comment]
Duplicate of https://github.com/quarkusio/quarkus/issues/12522
