### ISSUE TITLE
InjectMock does not work in combination with @ServerEndpoint

### ISSUE THREAD

**Issue by WouterOet** [quarkusio/quarkus#11143]
**Describe the bug**
Mocking using io.quarkus.test.junit.mockito.InjectMock does not work in combination with javax.websocket.server.ServerEndpoint (in combination with Kotlin).

Given the following beans:

(Websocket ServerEndpoint) -> (Bean B) -> (Bean A)

Where the arrow stand for invocation.

**Expected behavior**
When I mock bean A using InjectMock and the appropriate mockito setup, and I send a message to the endpoint. Then I expect the mocked bean to be invoked.

**Actual behavior**
The real bean is invoked.

**To Reproduce**
1. Checkout https://github.com/WouterOet/quarkus-mocking (1 file example)
2. Run FullTest
3. Output should contain mock-a but is real-a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin fancy-brick 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/wouter/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
Default locale: en_NL, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Comment by stuartwdouglas** [comment]
The mocks are cleared at the end of the test. As you send a message and don't wait to close the connection or receive a response the mocks are immediately cleared, and by the time the server has processed the message they are no longer installed.

To make this work you need to wait for the result of the server side processing somehow, either by closing the connection afterwards, waiting for the server to respond to a message, or some other mechanism.
