### ISSUE TITLE
Provide an api to test Quarkus Command Mode apps

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#11198]
**Description**
We should provide an api to test Quarkus Command Mode application.

@stuartwdouglas pointed me to some internal testing tool that we could use as inspiration:
https://github.com/quarkusio/quarkus/blob/11a529e9595f33d22bd4c77082b4d2a07509c5cd/core/test-extension/deployment/src/test/java/io/quarkus/commandmode/SimpleCommandModeTestCase.java

IMHO, testing a Command Mode app should be made as easy as testing rest service as they are pretty similar.

**Comment by janmaterne** [comment]
I think issue 10212 is related to this.

**Comment by ia3andy** [comment]
yeah I guess we can close that one a it's a duplicate of #10212
