### ISSUE TITLE
JsonNode not in Jandex after upgrade to 1.7.0.CR1

### ISSUE THREAD

**Issue by jorsol** [quarkusio/quarkus#11208]
**Describe the bug**
In 1.6.1.Final the maven build don't show any warning, but changing the version to 1.7.0.CR1 triggers a WARNING about `com.fasterxml.jackson.databind.JsonNode` that is not in the index.

Is a multi-module project using RESTEasy, so I would assume there is the ignore for ReflectiveHierarchyStep set.

**Expected behavior**
No log warning message.

**Actual behavior**
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- com.fasterxml.jackson.databind.JsonNode (source: io.fabric8.kubernetes.api.model.HasMetadata)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```
**To Reproduce**
** Not sure how to reproduce it easily **

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux qk 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.7.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  3.6.3

**Comment by gsmet** [comment]
This is definitely not expected. Could you try to debug what's going on? It should pass through the `ResteasyDotNames.IgnoreForReflectionPredicate`.

If not, it might be interesting to know who created the `ReflectiveHierarchyStep` in question.

**Comment by gsmet** [comment]
A reproducer would definitely help, it's probably something related to the Kubernetes client.

**Comment by jorsol** [comment]
I could try to make a reproducer, but it will probably take me some time...

The change I see that could affect between 1.6.1.Final and 1.7.0.CR1 is https://github.com/quarkusio/quarkus/commit/567d9cfcb550a48aeca274a618e6e94d847c2e09#diff-ededdffcf80522897a5e8aab2c124a05 but I can't be sure there is the issue.

**Comment by gsmet** [comment]
Good catch. Could you try that PR: https://github.com/quarkusio/quarkus/pull/11209 ?

https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master might help (but in this case, you need to get my branch from the PR)

**Comment by jorsol** [comment]
Yes!, it looks like your branch solves the issue. Thanks!

Just a small note: `javax.ws.rs.container.AsyncResponse` is missing.
