### ISSUE TITLE
Quarkus does not support for java commndline parameter -cp, -classpath. --class-path

### ISSUE THREAD

**Issue by akhapre** [quarkusio/quarkus#11207]
Java commandline parameter like -cp, -classpath, --classpth not support. I tried adding a directory as classpath with some additional resources and then tried to read them in the code as `Thread.currentThread().getContextClassLoader().getResource(<resource-path>)`, which returns null. Whereas a simple commandline program correctly recognized them and return correct path.

**Expected behavior**
Directory specified in classpath should be recognized and resources like (.class files), non-class resources like properties file, should be loaded/found by the Quarkus.

**Actual behavior**
Quarkus application returns null.

**To Reproduce**
1. Run simple quarkus application @ https://github.com/akhapre/quarkus-classpath-support.git as follows. Codebase contains extra dirctory called www-root which will be added to classpath while running.
1.1. `mvn clean install`
1.2. `java -classpath www-root/ -jar target\code-with-quarkus-1.0.0-SNAPSHOT-runner.jar`
1.3  open web browser "http://localhost:8080/hello".
1.4. System.out (console) will report the location of resources 'org/acme/Example2Resource.class', 'META-INF/resources/index2.html' as not found.
2. Run standlaone java program as follows.
2.1 `java -classpath www-root;target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar org.acme.Main`
2.2. System.out (console) will report the location of resources `org/acme/Example2Resource.class`, `META-INF/resources/index2.html` correctly.

**Environment (please complete the following information):**
- java version "11.0.6" 2020-01-14 LTS
- Quarkus 1.6.1
- Windows 10 (version 2004)
- Maven 3.6.3

**Comment by famod** [comment]
Unfortunately, this is a limitation of `java`. You cannot specify a (custom) classpath via `-cp` etc. when also using `-jar`.
See also: https://stackoverflow.com/questions/15930782/call-java-jar-myfile-jar-with-additional-classpath-option/15930980
