### ISSUE TITLE
Agroal - Allow to configure transaction isolation level

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1122]

**Comment by gsmet** [comment]
@machi1990 if you're looking for some issues, this one shouldn't be too hard and it's in another subsystem.

Note that there is a `DefaultDataSourceConfigTest` in which you should add a check for the new property.

Tell me if you're interested.

**Comment by machi1990** [comment]
Hey @gsmet, sure I am interested. I'll take a look at this. Your ping was probably lost in my inbox that's why I took a little longer to get back.
