### ISSUE TITLE
Missing documentation for using configMaps with native-image on OCP

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#11230]
**Describe the bug**
Currently, the community documentation describes usage of `configMap` with Quarkus on kubernetes in a standalone article in a fragmented fashion. There is no documentation available for user with a work flow that would allow them to build a native image, deploy it on kubernetes/OpenShift and configure it via `configMap`

**Expected behavior**
Describe the following:
1. What builder image is to be used
2. What base image is to be used on kubernetes/OpenShift 
3. Where the `configMap` volume is supposed to be mounted to be picked up by native-image application

User should ideally be walked through in both the source S2I workflow as well as when working with Quarkus kubernetes/OpenShift plugin.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by mjurc** [comment]
I think all of this has been added to https://quarkus.io/guides/deploying-to-kubernetes in the meantime, so I'll close the issue for the time being.

**Comment by geoand** [comment]
🙏
