### ISSUE TITLE
Response format produced is not valid HAL

### ISSUE THREAD

**Issue by odrotbohm** [quarkusio/quarkus#11237]
According to the guide presented [here](https://quarkus.io/guides/rest-data-panache#get-people1) the response produced for a request with an `Accept` header of `application/hal+json` looks like this:

```javascript
{
  "id": 1,
  "name": "John Johnson",
  "birth": "1988-01-10",
  "_links": {
    "self": "http://example.com/people/1",
    "remove": "http://example.com/people/1",
    "update": "http://example.com/people/1",
    "add": "http://example.com/people",
    "list": "http://example.com/people"
  }
}
```

The `_links` section is not valid HAL as [according to the spec](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5), each link is an object and the target URI is held in an `href` property. I.e. the `_links` element would have to look like this:

```javascript
{
  …,
  "_links" : {
    "self" : {
      "href" : "…" // Nested href attribute
    },
    …
  }
}

**Comment by gytis** [comment]
Thank you for reporting it @odrotbohm. It's a mistake in a guide. The generated endpoint returns an object just like in your example. I'll raise a PR to fix the guide.

**Comment by gytis** [comment]
Feel free to assign this to me @gsmet

**Comment by odrotbohm** [comment]
That's great to hear. Thanks for the quick turnaround!
