### ISSUE TITLE
Qurkus 1.6.1 using deprecated java options

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#11241]
**Describe the bug**
I know Quarkus is based on Java 11, but of you try it with Java 14 with Gradle's  quarkusDev task, you get this:
```
Task :demo:quarkusDev
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

Maybe time to stop using these options altogether now?

**Comment by famod** [comment]
This has already been fixed via #11120 which is included in 1.7.0.CR2.
