### ISSUE TITLE
Give warning when REST Data HAL endpoint cannot be exposed properly

### ISSUE THREAD

**Issue by gytis** [quarkusio/quarkus#11246]
REST Data extension supports generating endpoints that return `application/hal+json` content. However, it requires a custom serialiser implementation which depends on `quarkus-resteasy-jackson` or `quarkus-resteasy-jsonb` being defined in an application's pom. This requirement is listed in an extension guide, but Quarkus won't give any warning when an actual application is build without such dependencies. Application would silently expose a hal endpoint, but the returned object would not be serialised in a correct format.
It would be helpful and less confusing for a user if an extension would print a warning and not expose a HAL endpoint if not all prerequisites are met.

**Comment by gytis** [comment]
I'll fix this problem, so please assign it to me.

**Comment by geoand** [comment]
This has already been fixed
