### ISSUE TITLE
jax-rs - exception mapper - `Unable to extract parameter` doesn't show the value of the parameter, just {1}

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#11252]
Quarkus master / Quarkus 1.7.0.CR2 - `Unable to extract parameter` doesn't show the value of the parameter, just {1} for case of exception in conversion of `@QueryParam` to the expected type - String to Integer in my case

Regression comparing to 1.3.4.Final and 1.6.1.Final, found it when experimenting with https://github.com/gastaldi/resteasy-xss example
It's REASTEasy issue for sure, I have possible fix for it.
Want to track it here too so as it's regression and is connected to https://github.com/quarkusio/quarkus/issues/7248

What I see: `RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("paging") value is {1} for public java.lang.Integer org.acme.UsersResource.page(java.lang.Integer)`

Expectation: `RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("paging") value is 'asd' for public java.lang.Integer org.acme.UsersResource.page(java.lang.Integer)`

Request: http://localhost:8080/users?paging=asd

**Comment by rsvoboda** [comment]
RESTEasy issue: https://issues.redhat.com/browse/RESTEASY-2674
Possible fix: https://github.com/resteasy/Resteasy/pull/2490

**Comment by geoand** [comment]
It appears from the RESTEasy version where this was fixed that it is no longer an issue

**Comment by rsvoboda** [comment]
+1, the issue is fixed now, checked with Quarkus 2.1.0.Final
