### ISSUE TITLE
Amazon client requires both transport client implementations for native compilation

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#11264]
**Describe the bug**
The [AmazonClientTransportRecorder](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-services/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientTransportRecorder.java)
has both UrlConnectionHttpClient and ApacheHttpClient Code in the Runtime Recorder which seems to require both the respective dependencies during native image compilation.

**Expected behavior**
Only one of the dependencies is required during native image build time.

**Actual behavior**
Both of the dependencies are needed, which increases build time.

**Comment by gsmet** [comment]
@antonwiens I **think** splitting it in 2 specific methods and moving the test to the processor might be sufficient to fix the issue. Would you like to give it a try?

**Comment by antonwiens** [comment]
I'll give it a try.
