### ISSUE TITLE
More flexible quarkus configuration

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#11273]
**Description**
Currently Quarkus configuration fails to implement a very flexible way to specify a run-time configuration source  on the command line, where the source does not have to be in pre-defined location. Requiring "special locations" for configuration files is tricky when developers need to avoid accidentally checking in passwords in Git, preserve configuration files between compile/clean and running docker images with mounted data volumes for runtime configuration.

**Implementation ideas**
Spring handles this already very nicely, no need to re-invent the hot water and the wheel here. In SpringBoot I can use **spring.config.location** system property for that:

        java -jar myproject.jar --spring.config.location=file:/tmp/myapplication.config

See section ["24.3 Application Property Files" in Spring docs](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html) for more details.

... So Quarkus just need **quarkus.config.location** system property (perhaps no need for command line at all) and the  flexible mini-language (regex?) to describe the various configuration sources  to merge from (file, url, inside zip/jar). See Spring, they got it right.

Also see:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20configuration

**Comment by hrstoyanov** [comment]
@radcortez FIY.

**Comment by radcortez** [comment]
We maybe be able to support this with SR Config `FileSystemConfigSource`, with some additional tweaks.

**Comment by hrstoyanov** [comment]
Also, is Quarkus the right place to fix this, or MP Config? I know it is too late for MicroProfile 4, so maybe Quarkus?

**Comment by radcortez** [comment]
Not everything has to go to MP Config and I think it is good to try out the features first in the wild, before moving it into the spec.

Moving forward, we can add this to SR Config. My idea was to use this as a base, enhance it and support it here: https://github.com/smallrye/smallrye-config/blob/master/sources/file-system/src/main/java/io/smallrye/config/source/file/FileSystemConfigSource.java

**Comment by hrstoyanov** [comment]
@radcortez thanks. I just want to make sure you are not fixated on file in the file system only, and this is possible:
```java -jar myproject.jar --spring.config.location=file:/tmp/myapplication.config;http://githib.com/myproject/myother.config```
e.g configurations are merged  from files or urls in the order of enumerating them on the command line

**Comment by radcortez** [comment]
Well, I think that we should probably start with the file system first, simple because we already have most of the work to support it. 

Adding more url handlers requires additional work that we can do later.
