### ISSUE TITLE
Better error message when already exists

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#11309]
When you run the codestart from maven and the directory already exists it gives a big long stack trace.  This should be cleaned up so that only an error message is generated and not the big stack trace.  Should look into other places where errors are thrown and not spit out a stack trace.

**Comment by ia3andy** [comment]
I would say it's an enhancement and not a bug :)

**Comment by aloubyansky** [comment]
I believe this is out-of-date.
