### ISSUE TITLE
Nested configuration class with Confiuration suffix does not work

### ISSUE THREAD

**Issue by Rutzzzz** [quarkusio/quarkus#11301]
While standalone Configuration classes annotated with @ConfigProperties can have both -Config and -Configuration suffixes, nested configuration classes seem to accept only -Config suffix.

**Expected behavior**
I would expect that nested classes can have -Configuration suffix, same as standalone classes.

**Actual behavior**
Configuration suffix cannot be used (java.lang.NoSuchFieldError is thrown if attempted).

1. generate a simple jax-rs project (https://code.quarkus.io/)

2. Create the following Configuration class:
```
@ConfigProperties
public class GreetingConfiguration {
    public HiddenConfiguration hidden;
    public static class HiddenConfiguration {
        public String value;
    }
}
```
3. Add the following to application.properties:
`greeting.hidden.value=hi
`
4. Update the resource class:
```
@Path("/hello")
public class ExampleResource {
    @Inject
    GreetingConfiguration greetingConfiguration;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return greetingConfiguration.hidden.value;
    }
}
```

5. request to the endpoint /hello will fail:
2020-08-10 14:41:54,071 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-198) HTTP Request to /hello failed, error id: 80b832e6-cec9-4db2-b873-393171eb6dc8-4: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchFieldError: hidden

Linux localhost.localdomain 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/omachala/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: GraalVM Community, runtime: /home/omachala/.sdkman/candidates/java/20.1.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.13-100.fc30.x86_64", arch: "amd64", family: "unix"

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
I can't reproduce this. Do you have an example project that exhibits this behavior?

**Comment by Rutzzzz** [comment]
My bad. It turns out the nested class can have any class name. I was running into this issue, because I was using a dev mode without the clean maven goal. Closing this.
