### ISSUE TITLE
Change in the vault bootstrap between version 1.5.X and 1.6.X

### ISSUE THREAD

**Issue by etonzera** [quarkusio/quarkus#11329]
**Describe the bug**
I think there was some significant change in the bootstrap and in the order of priority of loading files and classes between version 1.5.X and version 1.6.x. Because when trying to use the vault by configuring the properties file to use the kube's configMap settings in version 1.6.1-final, quarkus does not seem to understand both the configMap variables and the environment variables.

**Expected behavior**
It should work as in version 1.5.2-final which read the configMap settings before making other classloaders and with that we were able to upload the application using the vault by reading the Kube variables. The problem with version 1.5.2-final is that there is no quarkus.vault.authentication.kubernetes.auth-mount-path property so this value is fixed in the code as auth/kubernetes and as I use kubernetes and multicluster this needs to be dynamic, something that was corrected in version 1.6.1-final, so this version does not load the environment variables in the startup or at least with the wrong priority order (wow I got in a loop :confused:).

**To Reproduce**
1. Set environment variables or configure vault configMap in kube
2. Configure the property files by setting the property values using the environment variables
3. Use version 1.6.1-final of quarkus.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.vault.url = http://${VAULT_SERVER}:$ {VAULT_PORT}
quarkus.vault.authentication.kubernetes.role=${VAULT_ROLE}
quarkus.vault.authentication.kubernetes.auth-mount-path = auth/${CLUSTER_NAME}
quarkus.vault.kv-secret-engine-version = 1
quarkus.vault.secret-config-kv-path = ${VAULT_KV_PATH_DB}, ${VAULT_KV_PATH_APP}
```

@radcortez could you help us with that?

**Comment by akruel** [comment]
Guys, initially thank's for amazing work!

Any news for this issue?

**Comment by vsevel** [comment]
we need to drop the special property loading that is done in the vault extension today.
we are waiting for a release of the smallrye config project as discussed here https://github.com/quarkusio/quarkus/issues/9991#issuecomment-656816961, which should solve https://github.com/quarkusio/quarkus/issues/11921, and hopefully this issue too.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
