### ISSUE TITLE
Failures when accessing uninitialized RUNTIME_INIT synthetic beans during STATIC_INIT

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#11337]
Recently, there were several issues following the same pattern: 

1. An extension **A** provides a _RUNTIME_INIT_ synthetic bean for type `Foo`
   - such a bean is initialized during the _RUNTIME_INIT_ bootstrap phase
   - see also `io.quarkus.arc.deployment.SyntheticBeanBuildItem.ExtendedBeanConfigurator.setRuntimeInit()`
2. An extension **B** initializes a CDI component `Bar` during _STATIC_INIT_; and `Bar` depends on `Foo`
3. If `Foo` is a normal scope (e.g. `@ApplicationScoped`) the injection works fine unless `Bar` attempts to use `Foo`, i.e. call a method
   - in this case we throw an exception with message: `Synthetic bean instance not initialized yet`
4. If `Foo` is `@Singleton` then the injection always fails with `Synthetic bean instance not initialized yet`

So far I saw JAX-RS providers ~and gRPC endpoints~ to fail because of this limitation, i.e. a JAX-RS provider ~gRPC~ injects a bean that touches the injected `Vertx` instance.

**Comment by mkouba** [comment]
UPDATE: A similar problem appears when a RUNTIME_INIT synthetic bean is accessed BEFORE the `SyntheticBeansProcessor.initRuntime()` build step is finished, i.e. the supplier map does not contain relevant suppliers yet.

**Comment by mkouba** [comment]
Actually, there is already the `SyntheticBeansRuntimeInitBuildItem` that should be consumed by `RUNTIME_INIT` build steps that access a `RUNTIME_INIT` synthetic bean.

**Comment by wangyuanhang111** [comment]
Has this been fixed? I'm having a generic problem where I can't inject Vertx objects because the rpc must be @Singletion How do I fix this?

**Comment by mkouba** [comment]
> Has this been fixed? I'm having a generic problem where I can't inject Vertx objects because the rpc must be @Singletion How do I fix this?

You can try to inject `javax.enterprise.inject.Instance<Vertx>` instead and access the bean lazily via `Instance#get()`. But of course, this will only work if you start using the `Vertx` bean at runtime.

**Comment by think01** [comment]
I have this same problem with gRPC and quarkus-smallrye-reactive-messaging-kafka extension:

```
2021-06-03 14:36:39,393 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-06-03 14:36:39,389 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): javax.enterprise.inject.CreationException: Synthetic bean instance for io.agroal.api.AgroalDataSource not initialized yet: io_agroal_api_AgroalDataSource_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
        at io.agroal.api.AgroalDataSource_af92c027c2ee73cb5a9eda77a40bc4f296965f25_Synthetic_Bean.create(AgroalDataSource_af92c027c2ee73cb5a9eda77a40bc4f296965f25_Synthetic_Bean.zig:129)
```

In the initial post I see gRPC is striked out. Does it mean there's a solution for gRPC?

**Comment by mkouba** [comment]
> In the initial post I see gRPC is striked out. Does it mean there's a solution for gRPC?

@think01 Hm, what version of quarkus do you use? AFAIK the gRPC server is now started at runtime so it should not be the problem anymore.

**Comment by mkouba** [comment]
Actually, you're right that the gRPC server can be started before the RUNTIME_INIT synthetic beans are initialized. I believe that the `io.quarkus.grpc.deployment.GrpcServerProcessor.initializeServer()` should consume the `SyntheticBeansRuntimeInitBuildItem` in order to start the gRPC server after all RUNTIME_INIT synthetic beans are initialized.

**Comment by think01** [comment]
@mkouba latest available now.
I made several tests and I'm sure the problem arises when I add the extension `io.quarkus:quarkus-smallrye-reactive-messaging-kafka` AND use @Singleton. If I change Singleton to ApplicationScope, the kafka reactive listener starts without issues (but then gRPC doesn't work).

I'm still new to all of this: do you know if there's a quick solution to this problem? I'm not calling directly anything of/about the gRPC server, I'm using a very basic gRPC configuration, as per the official Quarkus guide https://quarkus.io/guides/grpc-getting-started

**Comment by think01** [comment]
> Actually, you're right that the gRPC server can be started before the RUNTIME_INIT synthetic beans are initialized. I believe that the `io.quarkus.grpc.deployment.GrpcServerProcessor.initializeServer()` should consume the `SyntheticBeansRuntimeInitBuildItem` in order to start the gRPC server after all RUNTIME_INIT synthetic beans are initialized.

I don't understand anything you've said here :-D
Do you mean I should modify someway the gRPC server boostrapping? How can I do this? As I said, I'm not calling anything from it, my configuration is very simple:

1. I have a single protobuf file to define my service.
2. I run quarkusGenerateCode (gradle) to have stubs.
3. I implement my own gRPC service extending the ImplBase class produced in previous step.
4. So far it works fine. Then...
5. I add Quarkus extension `io.quarkus:quarkus-smallrye-reactive-messaging-kafka` -> above error.

Any help is GREATLY appreciated ^_^

**Comment by mkouba** [comment]
> Do you mean I should modify someway the gRPC server boostrapping? How can I do this?

Not really. We need to fix this ;-). I'm going to send a PR shortly...

> If I change Singleton to ApplicationScope, the kafka reactive listener starts without issues  (but then gRPC doesn't work).

What exactly does not work?

**Comment by think01** [comment]
> What exactly does not work?
The gRPC service, but it's expected: from the gRPC-quarkus documentation, you cannot use `@ApplicationScoped` annotation but must use `@Singleton` since the gRPC service implementation cannot be proxied.

**Comment by mkouba** [comment]
> The gRPC service, but it's expected: from the gRPC-quarkus documentation, you cannot use `@ApplicationScoped` annotation but must use `@Singleton` since the gRPC service implementation cannot be proxied.

I see. Well, you can try to `@Inject javax.enterprise.inject.Instance<AgroalDataSource> ds` and then `ds.get()` in your gRPC service as a workaround.

**Comment by think01** [comment]
> I see. Well, you can try to `@Inject javax.enterprise.inject.Instance<AgroalDataSource> ds` and then `ds.get()` in your gRPC service as a workaround.

Great! It works! Yes, as a workaround I can use this, thanks a lot!

**Comment by Felk** [comment]
I'm encountering a similar issue. I have a custom validator (hibernate validation) that accesses the database. The validator gets initialized during `STATIC_INIT` by quarkus-hibernate-validator, but the datasources are not initialized at that time. The stacktrace looks something like this:
```
javax.enterprise.inject.CreationException: Synthetic bean instance for io.agroal.api.AgroalDataSource not initialized yet: io_agroal_api_AgroalDataSource_951cc0ce51a3a5c1485926b1f383ae61e7b47fab
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
        at io.agroal.api.AgroalDataSource_5456707908d6a045ad3a66d229adc231bbebd29b_Synthetic_Bean.create(AgroalDataSource_5456707908d6a045ad3a66d229adc231bbebd29b_Synthetic_Bean.zig:179)
        ...
        at io.agroal.api.AgroalDataSource_5456707908d6a045ad3a66d229adc231bbebd29b_Synthetic_Bean.get(AgroalDataSource_5456707908d6a045ad3a66d229adc231bbebd29b_Synthetic_Bean.zig:250)
        at com.example.PersistenceProducers_Bean.create(PersistenceProducers_Bean.zig:187)
        ...
        at com.example.MyValidator_Bean.get(MyValidator_Bean.zig:12345)
        ...
        at io.quarkus.hibernate.validator.runtime.ArcConstraintValidatorFactoryImpl.getInstance(ArcConstraintValidatorFactoryImpl.java:29)
        ...
        at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:433)
        ...
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:347)
        ... 17 more
```
With the relevant code looking something like this in a simplified form:
```java
public class PersistenceProducers {
    private final EntityManager entityManager;

    @Inject
    public PersistenceProducers(@Named("my-datasource") EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    @Produces
    @MyCustomQualifier
    public EntityManager getEntityManager() {
        return entityManager;
    }
}
```

```java
@Dependent
public class MyValidator implements ConstraintValidator<MyConstraintAnnotation, MyConstraintContainer> {

    private final EntityManager entityManager;

    @Inject
    public MyValidator(@MyCustomQualifier EntityManager entityManager) {
        this.entityManager= entityManager;
    }

    @Override
    public void initialize(final MyConstraintAnnotation constraintAnnotation) {
        // NOP
    }

    @Override
    public boolean isValid(@Nullable final MyConstraintContainer container, final ConstraintValidatorContext context) {
        return true; // actually do stuff on the database using the entity manager
    }
}
```

Any recommendations on how to avoid this problem?

**Comment by mkouba** [comment]
@Felk does the `MyValidator` inject the `AgroalDataSource` directly? If so then replace the injection point with `@Inject javax.enterprise.inject.Instance<AgroalDataSource>` and then `Instance.get()` to obtain the DS instance. You can even try [`@WithCaching`](https://quarkus.io/guides/cdi-reference#caching-the-result-of-programmatic-lookup) if you need better performance.

**Comment by mkouba** [comment]
I'm going to close this issue because there's not much we can do about it. The `SyntheticBeansRuntimeInitBuildItem` is documented in the [CDI integration guide](https://quarkus.io/guides/cdi-integration#synthetic_beans) and the error message contains all relevant information.
