### ISSUE TITLE
Native Build Failing 

### ISSUE THREAD

**Issue by anujgupta1601** [quarkusio/quarkus#11347]
Hi,

I am using quarkus in my applications, it works fine in dev mode using jar, now I am trying to build a native image.
I am getting RuntimeException: Image generation failed. Exit code: 1

Attaching detailed logs here:
[log.txt](https://github.com/quarkusio/quarkus/files/5062819/log.txt)

What am I missing? Any help would be much appreciated. 
Thanks in advance!

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?

**Comment by geoand** [comment]
Closing as we did not receive feedback
