### ISSUE TITLE
@ConfigProperties system doesn't allow using @ConfigProperty on class fields, only on interface methods

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#11367]
**Describe the bug**
If I use the `@ConfigProperties` annotation on an `interface`, I can customize config property names for the interface methods using the `@ConfigProperty` annotation.

I expect to be able to do the same for a `class` annotated with `@ConfigProperties`, but `ClassConfigPropertiesUtil.populateConfigObject` says `'@ConfigProperty' is ignored when added to a field of a class annotated with '@ConfigProperties'.`

This is not documented and is certainly unexpected. I don't even call this an enhancement proposal, but a bug -- I consider feature parity between `@ConfigProperties` classes and interfaces a natural expectation.

CC @geoand, as @mkouba said he's the author of the `@ConfigProperties` system :-)

**Comment by geoand** [comment]
Yeah, this was intentional, but I don't remember why.

I'll need to go think about it again when I get back

**Comment by geoand** [comment]
I remember why I did this:

Basically I didn't want `@ConfigProperty.defaultValue` to come into play when using classes, as the default value should just be set in code. 
@Ladicek I assume that you want to be able to customize the field names, right? If so, then I guess we can relax the constraint and just disallow `defaultValue`. WDYT?

**Comment by Ladicek** [comment]
For complex types (with `Converter`s), expressing default values in code doesn't necessarily have to be possible, so I'd say `defaultValue` should work as well. (And if it's set, then it should take precedence.) But yes, when I stumbled upon this, I was mainly after customizing the configuration key.

**Comment by geoand** [comment]
OK, I'll add this to the list of things I need to do (the name part at least) :)
