### ISSUE TITLE
@ConfigProperties system doesn't know anything about Optional{Int,Long,Double}

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#11366]
**Describe the bug**
I'm looking at the code of the `@ConfigProperties` system (`io.quarkus.arc.deployment.configproperties`), and I noticed that it has many special cases for `Optional`, but nothing about `Optional{Int,Long,Double}`. These should be treated equivalently, as they are in MicroProfile Config.

(Perhaps there's no special casing needed for them? I don't know. I know there are no `Optional{Int,Long,Double}` tests.)

CC @geoand, as @mkouba said he's the author of the `@ConfigProperties` system :-)

**Comment by Ladicek** [comment]
@radcortez says special casing for `Optional` is needed for figuring out the type argument, which obviously isn't necessary for `Optional{Int,Long,Double}`. So this might be an invalid issue.

**Comment by radcortez** [comment]
Yes, we still need your PR here: https://github.com/quarkusio/quarkus/pull/11363, to make sure the additional Optional types are handled by the ConfigProducer.

Of course, we should add some tests to `@ConfigProperties` and make sure it plays nice. I believe it should work OOTB.

**Comment by Ladicek** [comment]
I think the test failures I've seen were all caused by #11367. Using `OptionalInt` worked fine when used on an interface (because I used `@ConfigProperty`), and would probably also work on a class if I had a corresponding config property.

So we can close this one, at least for now.
