### ISSUE TITLE
Missing mockito-junit-jupiter in quarkus-junit5-mockito

### ISSUE THREAD

**Issue by juanmbellini** [quarkusio/quarkus#11361]
**Description**
The `io.quarkus:quarkus-junit5-mockito` testing extension depends on `io.quarkus:quarkus-junit5` and `org.mockito:mockito-core`. I think that it should also depend on `org.mockito:mockito-junit-jupiter` as this library is the one containing classes to make mockito work with the jupiter api (e.g here lives the MockitoExtension, for instance).

**Implementation ideas**
Add the following dependency 

```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-junit-jupiter</artifactId>
</dependency>
```

to the following `pom.xml`: https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5-mockito/pom.xml

**Comment by jaikiran** [comment]
Hello @juanmbellini, is this showing up as an issue in some manner when you are running your application tests? Could you share those details?

**Comment by juanmbellini** [comment]
Hello @jaikiran . It does not affect in any manner my tests. I just add the dependency myself to my project. 
The thing is that `org.mockito:mockito-junit-jupiter` is a required dependency when using JUnit 5 if you want to use the Mockito Extension. Here more info: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#45. 
And here more data about Junit 5 extension model: https://junit.org/junit5/docs/current/user-guide/#extensions.

**Comment by juanmbellini** [comment]
Here more info: https://stackoverflow.com/a/40962941/5373655

**Comment by jaikiran** [comment]
Thank you for those details. I'll let @geoand take a look at this once he's back from vacation, since he's more knowledgable in this area than me.

**Comment by geoand** [comment]
I am in favor of leaving it as is, as the `quarkus-junit5-mockito` extension does not interact with the mockito junit5 extension in any way - it depends on mockito core only and ties into the Quarkus test lifecycle.

We should avoid coupling this extension to another dependency unless there is a very good reason to do so.
