### ISSUE TITLE
Native-Image Failed | java.lang.RuntimeException: Image generation failed. Exit code: 1

### ISSUE THREAD

**Issue by ashish82** [quarkusio/quarkus#11371]
**Describe the bug**
Hi,
I am using quarkus in my applications, it works fine in dev mode using jar, now I am trying to build a **native image**.
**I am getting RuntimeException: Image generation failed. Exit code: 1**

Attaching detailed logs here:
[debug-log.txt](https://github.com/quarkusio/quarkus/files/5069420/debug-log.txt)

What am I missing? Any help would be much appreciated.
Thanks in advance!

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. Checkout the project
2.  mvn package -Pnative -Dquarkus.native.container-build=true -X
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
#############################################
# Delaying class initialization                        #
#############################################
quarkus.native.additional-build-args=--initialize-at-run-time=com.couchbase.client.encryption.errors.CryptoProviderEncryptFailedException,com.couchbase.client.java.transcoder.crypto.JsonCryptoTranscoder
# ===================================================================
# Quarkus Configuration properties
# ===================================================================
#quarkus.package.uber-jar=true
quarkus.http.port=9090
quarkus.http.root-path=/
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  
Linux ip-10-114-11-22.ap-south-1.compute.internal 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)

 - GraalVM version (if different from Java): graalvm-ce-java8-20.1.0
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
mvn package -Pnative -Dquarkus.native.container-build=true

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Closing for lack of feedback
