### ISSUE TITLE
Configurable remote development reconnect retries

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#11382]
**Description**
When running remote development with the backend on Kubernetes, the retry attempts to stop before I want them to (30 seconds? 10 attempts?). Sometimes it takes longer than the default number of retry attempts. It would be good to make this configurable, either by a time allotment (`quarkus.live-reload.retry-time=30s`), by attempts (`quarkus.live-reload.retry-attempts=30`), and/or both. While this is already a need IMHO, it is exacerbated by proposed feature issues #11381 and #11379.

Perhaps, when running in Kubernetes, the remote-development client may not have to be a poll. The remote-development client could use the quarkus-kubernetes-client API to detect if a pod is restarting, wait for the new pod to start, and then reconnect. Polling may be easier and more reliable though :-)

**Comment by geoand** [comment]
cc @stuartwdouglas
