### ISSUE TITLE
Template extension generating java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mahieddine** [quarkusio/quarkus#11390]
**Describe the bug**
I'm trying to play with the template extension feature, so I created a sample template extension like this 

TemplateExtension.java

```java
public final class TemplateExtensions {
  @TemplateExtension(namespace = "str", matchName = ANY)
  public static String sayHello(String val) {
    return "hello " + val;
  }
}
```

In my template i have this 

hello.html 

```html
<div>{str:quarkus}</div>
```
but keep getting NoClassDefFoundError xxx/TemplateExtensions

**Expected behavior**
I was expecting to get a "hello quarkus"

**Actual behavior**
I'm getting a  NoClassDefFoundError xxx/TemplateExtensions

**To Reproduce**
Just with the example mentioned above 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
 - Quarkus version or git rev: 1.7.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Mac OS X 10.15.6 x86_64

**Comment by mahieddine** [comment]
Ok so after some digging it appears that this issue occurs only with quarkusDev, if we build and launch the runner it works perfectly.

**Comment by mahieddine** [comment]
It seems like in dev mode, value resolvers classes are not generated hence causing this issue. When i build my jar and extract the value resolvers from it copy/paste them into the class folder it works.

**Comment by glefloch** [comment]
are those compiled class placed in `build/classes/main/kotlin` ?

**Comment by mahieddine** [comment]
I'm using java so i put them next to my extension class yes in build/classes/main/java 

```
/- TemplateExtension.class
 - TemplateExtension_Namespace_Extension_ValueResolver61d28b9c49fe6bd41e16f0703f3cf81ed9aa8f8e.class
```

**Comment by glefloch** [comment]
@mahieddine I just tried to reproduce your error with quarkus 1.7.2.Final and I'm not able to. 
I created this project https://github.com/glefloch/quarkus-gradle-qute which reproduce your extension and it's working. Are you able to reproduce the error with quarkus 1.7.2.Final ?

**Comment by mahieddine** [comment]
@glefloch i just tried with quarkus 1.7.2.Final and the issue is resolved ! thank you ! i'll close this issue as it's not happening anymore.
