### ISSUE TITLE
1.7.0.Final quarkus.package.output-directory causes NPE running tests

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#11400]
**Describe the bug**
NPE running JUnit test when `quarkus.package.output-directory` is set:

    java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#outputTarget threw an exception: java.lang.NullPointerException
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.lambda$outputTarget$0(JarResultBuildStep.java:147)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.outputTarget(JarResultBuildStep.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)

**Environment**
 - Quarkus version or git rev: 1.7.0.Final
 
**Additional context**
`io.quarkus.deployment.pkg.steps.JarResultBuildStep` is blowing up here because `packageConfig.outputDirectory` has a value but `bst.getOutputDirectory()` does not.  

    @BuildStep
    OutputTargetBuildItem outputTarget(BuildSystemTargetBuildItem bst, PackageConfig packageConfig) {
        String name = packageConfig.outputName.orElseGet(bst::getBaseName);
        Path path = packageConfig.outputDirectory.map(s -> bst.getOutputDirectory()*NPE*.resolve(s))
                .orElseGet(bst::getOutputDirectory);
        return new OutputTargetBuildItem(path, name, bst.isRebuild(), bst.getBuildSystemProps());
    }

Using `%test.quarkus.package.output-directory=` to clear the setting allows the tests to run.

**Comment by jimbogithub** [comment]
Other modes work fine.

**Comment by jaikiran** [comment]
Hello @jimbogithub,

> NPE running JUnit test when quarkus.package.output-directory is set:

what value is it set to?

**Comment by jimbogithub** [comment]
> what value is it set to?

It doesn't matter what it is set to.  Any non-null value causes an NPE here: `bst.getOutputDirectory()*NPE*.resolve(s)`.  I looked around the code a bit and it appears that `bst.getOutputDirectory()` is blank because the `targetDir` is never set on the `Builder` for a `@QuarkusTest` run.

The fact that it runs OK with `%test.quarkus.package.output-directory=` suggests that neither of these values is needed for the test (it didn't place anything in the default build directory that I wasn't expecting).  So maybe `bst.getOutputDirectory()` is deliberately not set, in which case that bit of code needs to be changed to also ignore the `quarkus.package.output-directory`?

**Comment by jimbogithub** [comment]
P.S.  This was not a problem in prior versions.

**Comment by jaikiran** [comment]
I had assigned this to myself in the hopes of working on a fix. But I've been swamped with some other work this week and probably won't be able to get to this sooner and my investigation into this so far has indicated that I might anyway need some help from @aloubyansky or other folks familiar with this part of the code to get this working.
What's happening is that when the tests are run, (as you note) the `BuildSystemTargetBuildItem.getOutputDirectory()` is returning `null`, which I think should never have happened.
