### ISSUE TITLE
JAX-RS Providers in RESTEasy are not initialized unless a @Path is present in the Application

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#11424]
**Describe the bug**
A RESTEasy deployment is only produced if something with a `@Path` is found:

https://github.com/quarkusio/quarkus/blob/69ba3184ecd511fe7232ad6c4a852db6399baa2e/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L205-L208

This works fine for most cases. There is one case where this doesn't work:

If we have a Quarkus app, using a simple `ClientBuilder.newClient()`, annotated Providers are not automatically registered with the client, because the RESTEasy deployment was not initialized:

https://github.com/quarkusio/quarkus/blob/73d39594b469d31240bcc2dc1fca2121f5bcdf9e/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/ResteasyStandaloneRecorder.java#L68-L74

Which causes the Providers to not being registed with the client.

If we add a simple endpoint or even a dummy rest client interface with `@Path`, it works!

**Expected behavior**
Consistent behaviour of Providers with `ClientBuilder.newClient()` independent of other classes in the application.

**Actual behavior**
Providers are only registered if a `@Path` class exists in the application.

**Environment (please complete the following information):**
- Quarkus version or git rev: 1.7.0.Final

**Additional context**
Providers can still be registered manually in the `ClientBuilder` to workaround this issue. Also RESTEasy is clear regarding Providers registration and the Client: https://docs.jboss.org/resteasy/docs/3.7.0.Final/userguide/html/Client_Providers_With_Provider_Annotation.html

**Comment by radcortez** [comment]
To fix this issue, I'm wondering if we should always start the RESTEasy Deployment anyway. Or maybe we just need to start it if we find user defined Providers.

**Comment by marcelorubim** [comment]
Wouldn't be better a configuration to force it to start?

Like the Quartz extension does:

https://quarkus.io/guides/quartz#quarkus-quartz_quarkus.quartz.force-start

**Comment by radcortez** [comment]
Might be another options, yes.

**Comment by radcortez** [comment]
Another possible issue:

The programmatic client is part of the main JAX-RS spec and the type safe client part of the MP spec. All client integration is done in the rest-client extension, so you are required to add both dependencies to make it work, even if the client programmatic API is available just by adding the main RESTEasy extension.

**Comment by radcortez** [comment]
A possible resolution for this: https://github.com/quarkusio/quarkus/pull/11448

**Comment by radcortez** [comment]
An additional update:

The `ResteasyDeployment.start();` performs the registration of the `ResteasyProviderFactory` which is used to add the required `Providers`. The `ResteasyProviderFactory` may also be initialized directly via `ResteasyProviderFactory.setInstance`.

If we do it for clients, independently if there is an app it work. It an app is deployed, is just overrides the instance and it works as well.
