### ISSUE TITLE
declarative way of assigning roles with client certificate authentication

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#11434]
**Description**
When I use client certificate authentication, there's no declarative/configuration way of assigning roles for authorization. The only way I was able to find is by implementing a custom `SecurityIdentityAugmentor`. It would be nice to have at least some basic declarative support. It probably doesn't have to cover all cases, because customizing is so easy.

I know WildFly has this feature, both with legacy security and Elytron. With legacy security, it's very basic, AFAIK it only allows assigning roles based on the certificate's CN. On the other hand, with Elytron, it's extremely generic, but the configuration is really crazy. I certainly don't propose we go the Elytron way.

If we decide we don't do this at all, I propose at least we include the following code sample in the documentation.

**Implementation ideas**
The `SecurityIdentityAugmentor` I built is quite generic, so I'm adding it here in case it helps anyone:

```java
@Singleton
public class CertificateRolesAugmentor implements SecurityIdentityAugmentor {
    @Override
    public int priority() {
        return 0;
    }

    @Override
    public Uni<SecurityIdentity> augment(SecurityIdentity identity, AuthenticationRequestContext context) {
        return Uni.createFrom().item(() -> {
            QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder()
                    .setPrincipal(identity.getPrincipal())
                    .addAttributes(identity.getAttributes())
                    .addCredentials(identity.getCredentials())
                    .addRoles(identity.getRoles());
            CertificateCredential certificate = identity.getCredential(CertificateCredential.class);
            if (certificate != null) {
                builder.addRoles(extractRoles(certificate.getCertificate()));
            }
            return builder.build();
        });
    }

    private Set<String> extractRoles(X509Certificate certificate) {
        String name = certificate.getSubjectX500Principal().getName();

        switch (name) {
            case "CN=client":
                return Collections.singleton("user");
            case "CN=guest-client":
                return Collections.singleton("guest");
            default:
                return Collections.emptySet();
        }
    }
}
```

**Comment by Ladicek** [comment]
CC @pedroigor @stuartwdouglas

**Comment by sberyozkin** [comment]
@Ladicek At the very least I can update the security authorization or customization doc with your example.
And it would be nice, instead of 
```
QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder()
                    .setPrincipal(identity.getPrincipal())
                    .addAttributes(identity.getAttributes())
                    .addCredentials(identity.getCredentials())
                    .addRoles(identity.getRoles());
``` 
be able to do 
```
QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder(identity);
```
as it is likely all the users do this code

**Comment by Ladicek** [comment]
Agree @sberyozkin, that would be nice!

**Comment by pedroigor** [comment]
I can update docs if you want @sberyozkin.

**Comment by sberyozkin** [comment]
@pedroigor Hey Pedro, thanks. I'm on it during the last couple of hours :-) hope you haven't done much yet. thanks for offering to help :-), just aboutto open the PR

**Comment by sberyozkin** [comment]
I've also updated the builder as discussed with Ladislav, with a small unit test

**Comment by sberyozkin** [comment]
@Ladicek @pedroigor please see #11446

**Comment by sberyozkin** [comment]
@Ladicek hey, closing as a duplicate of #23683
