### ISSUE TITLE
Annotation processors fail during "mvn quarkus:dev"

### ISSUE THREAD

**Issue by jglink** [quarkusio/quarkus#11436]
After upgrading to Quarkus 1.7.0.Final, our _**mvn quarkus:dev**_ commands are not working anymore.

We are using some annotation processors (like Mapstruct).
Starting with Quarkus 1.7.0.Final, calling _**mvn quarkus:dev**_ after a _**mvn clean install**_ call fails with following errors:

`Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Attempt to recreate a file for type xxxx.xxxxx.Xxxxxx    at org.mapstruct.ap.internal.
processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:59)   at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:39)     at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:29)       at org.mapstruct.ap.internal.processo
r.MapperRenderingProcessor.process(MapperRenderingProcessor.java:24)    at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:283)         at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:263)        at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:221)`

Only when calling _**mvn clean compile quarkus:dev**_ the annotation processor is able to create the files again.

I think this is due to the latest change of the io.quarkus.maven.CodeGenMojo (revision 8b8bdfebf1eda5b5e7be16bd48145d3d043f0f29) where the generatedSourcesDir is no longer added to the sourceRegistrar.

How to reproduce:
- create a project with e.g. a Mapstruct Mapper definition
- call _mvn clean install_
- call _mvn quarkus:dev_
- --> will fail

**Comment by famod** [comment]
This is strange. I am 99% certain I tested @michalszynkiewicz's fix (#11328) [with my reproducer](https://github.com/quarkusio/quarkus/issues/11253#issue-674274864): https://github.com/quarkusio/quarkus/pull/11328#issuecomment-672287656

I'll have a look...

**Comment by famod** [comment]
Ok, I was a litte confused. The fix for #11253 is targeted for 1.7.1.Final.

Workaround: https://github.com/quarkusio/quarkus/issues/11253#issuecomment-670155833

Closing as a duplicate...

**Comment by jglink** [comment]
@famod thank you for the fast reply. I haven´t seen #11253. Sorry...

**Comment by famod** [comment]
@jglink No worries! It is better to report an issue twice than not at all. 😉
