### ISSUE TITLE
Calling method on target bean from interceptor invokes interceptor again; leads to StackOverflowException

### ISSUE THREAD

**Issue by 38leinaD** [quarkusio/quarkus#11447]
We have an aroundInvoke interceptor defined for our beans to do some application-specific permission checks:

```
@MyPermissionCheck
@Interceptor
@Priority(Interceptor.Priority.APPLICATION)
public class PermissionInterceptor implements Serializable {
	@AroundInvoke
	public Object beforeInvokation(InvocationContext invocationContext) throws Exception {
		BaseBean bean = (BaseBean) invocationContext.getTarget();
		boolean allowed = bean.performCheck(); // Leads to StackOverflowException
		if (allowed) {
			return invocationContext.proceed();
		}
		else {
			throw new RuntimeException("not allowed);
		}
	}
}
```

```
@MyPermissionCheck
@Named
@ViewScoped
public class TraceLogSettingsBean extends BaseBean {
}
```

When this interceptor is called for our bean, it internally, calls a performCheck-method on the bean by getting a bean reference via invocationContext.getTarget().
This bean reference is the Arc proxy and when performCheck is called, it will call the interceptor again and lead to a StackOverflowException. 

**Expected behavior**
As per the handling in Weld and other CDI implementations, when the bean method is called from an interceptor, the interceptor should not be called again.

**Actual behavior**
StackOverflowException

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.7.0.Final

**Comment by manovotn** [comment]
I can see how this is happening in ArC, but I don't know how to prevent it yet. Every intercepted bean implements a subclass which adds interception logic to methods; what I am not seeing is how can we tell if an invocation of such method was made within an intercepted call.
Maybe @mkouba has some ideas?

**Comment by famod** [comment]
Maybe `invocationContext.getContextData()` could be utilized to work around this on the user side. The idea is:
- `PermissionInterceptor` checks if the flag already exists in the map
- if exists: don't call `bean.performCheck()`
- if not exists: add the flag and call `bean.performCheck()`

Btw, @38leinaD could it be that your example interceptor is missing `invocationContext.proceed()`?

**Comment by 38leinaD** [comment]
@famod 
You are right, the example misses the invocationContext.proceed(). I update the example to show the full scenario.

I am not sure i understand how to solve this from the user-side only. For the "if not exists" branch in your explanation, you say "call bean.performCheck()". So, here i will encounter the said problem again. Maybe i dont fully understand you proposed solution.

I actually think, the Arc implementation itself needs to keep some context to know if it is already within an interceptor-chain and based on that, call the bean method without calling the interceptors again.

**Comment by manovotn** [comment]
Another way to workaround this is to avoid marking `performCheck()` method for interception. E.g. placing your interceptor binding (`@MyPermissionCheck`) directly on methods instead of the bean class. OFC this only works so long as you don't need that method intercepted for some other calls.

**Comment by 38leinaD** [comment]
> Another way to workaround this is to avoid marking `performCheck()` method for interception. E.g. placing your interceptor binding (`@MyPermissionCheck`) directly on methods instead of the bean class. OFC this only works so long as you don't need that method intercepted for some other calls.

Yes, understand what you mean. But as this is a generic mechanism that should intercept all calls, this is not an option in our case. Actually, it would be an option to explicitly exclude a certain method from interception (here: performCheck); but i am unaware that this possible in a JavaEE standard way. I can either annotate the whole class or each method, but i cannot annotate the class and somehow exclude certain methods by writing some annotation on that method !?

**Comment by famod** [comment]
> I am not sure i understand how to solve this from the user-side only. For the "if not exists" branch in your explanation, you say "call bean.performCheck()". So, here i will encounter the said problem again. Maybe i dont fully understand you proposed solution.

In theory, your interceptor _will_ be called again but will then find the flag in the map and will _not_ call `performCheck()` again.

**Comment by manovotn** [comment]
@38leinaD the first workaround suggestion by @famod should work as well - the context data can be used to stored anything during the whole interceptor chain. So you could have a flag saying that you already performed `bean.performCheck()` within this chain and you'd not invoke it again. Something like this:

```
@AroundInvoke
        public Object mySuperCoolAroundInvoke(InvocationContext ctx) throws Exception {
            Map<String, Object> contextData = ctx.getContextData();
            if (contextData.containsKey("my_key")) {
                // within this interceptor chain, the method was already called, no need to do it again
                ctx.proceed();
            } else {
                // the check wasn't invoked yet; set a flag and perform it
                contextData.put("my_key", true);
                BaseBean bean = (BaseBean) invocationContext.getTarget();
                boolean allowed = bean.performCheck(); // Leads to StackOverflowException
                if (allowed) {
                    return invocationContext.proceed();
                }
                else {
                    throw new RuntimeException("not allowed);
                }
            }
        }
```

**Comment by 38leinaD** [comment]
Sounds like i viable solution/workaround in general if this is a JEE standard-compliant approach; and it looks like it!

But it does not work currently. I tried, like you described but on each self-invokation of the interceptor, the map seems to be reset and the entry i put in before is gone. In fact, the map always only contains this key: io.quarkus.arc.interceptorBindings. my_key is gone.

**Comment by manovotn** [comment]
Ah, I see. Just tried it locally. It won't work because each of those method invocations triggers a separate interceptor chain (meaning each of them has their own context data therefore you cannot see the flag you store there). Context data are only shared within one interceptor chain, you would use that, for instance, to carry information between several of your interceptors within one chain. Sadly it won't help here.

As a side note, the key `io.quarkus.arc.interceptorBindings` is automatically added to all of them.

So you are down to the other workaround I described [above](https://github.com/quarkusio/quarkus/issues/11447#issuecomment-676079707).

**Comment by 38leinaD** [comment]
Hm, as I already described above, the other workaround is not an option for us as this is a generic mechanism in our application that does some security checks and it cannot be left to the person implementing the bean to add the annotation to each method that needs it.

What is the argument against adopting the behavior of Weld and other CDI implementations? I under stand that Arc is not fully CDI compliant and, to be honest, I am not sure this is mandated by the spec or an implementation detail, but I would hope that, where possible, Arc behaves similar to the popular CDI implementations. Otherwise, people migrating from JEE / CDI will face migration issues like these.

**Comment by manovotn** [comment]
> What is the argument against adopting the behavior of Weld and other CDI implementations?

None at all. This needs to be fixed. We were just suggesting temporary workarounds for you in the meantime :-)

**Comment by famod** [comment]
Too bad the context map doesn't work here. What about unwrapping the proxy (`io.quarkus.arc.ClientProxy`)?
PS: I know such things should be avoided whenever possible.

**Comment by 38leinaD** [comment]
In the best case, I would like a workaround where the interceptor can run on a regular JEE appserver as well as on Quarkus.
I was thinking to use a ThreadLocal variable to keep track if the interceptors has already been call (using a ThreadLocal instead of the InvocationContext.getContext()). This should be safe as the interceptors are always called on the same thread, right?

**Comment by mkouba** [comment]
> What about unwrapping the proxy (io.quarkus.arc.ClientProxy)?

@famod That would not help in this case. The instance returned by `InvocationContext#getTarget()` is not a client proxy but an intercepted subclass (internal container construct as defined by [Contextual instance of a bean](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#contextual_instance)).

I believe that this behavior is not defined by the spec but I've found a very old TCK test that seems to test the invocation of an instance returned from `InvocationContext#getTarget()`:
https://github.com/eclipse-ee4j/cdi-tck/blob/2.0/impl/src/main/java/org/jboss/cdi/tck/interceptors/tests/contract/invocationContext/Interceptor1.java#L28 

A threadLocal-based workaround should work. The problem is that if we decide to "fix" it we would have to find another solution for "self invocation interception" which we currently support (although it's another open question/undefined behavior, see for example https://issues.redhat.com/browse/CDI-414).

**Comment by manovotn** [comment]
> "self invocation interception" which we currently support

I don't think we state this anywhere officially and due to it being a grey area, I don't think we are bound to keep it that way.

Also, just for any onlookers, here is a comparison of Weld to ArC in these two aspects:
* Weld - self invocations are *not* intercepted && invocation of intercepted method via `InvocationContext#getTarget()` does *not* trigger interception
* ArC - self invocations are intercepted && invocation of intercepted method via `InvocationContext#getTarget()` triggers interception

Also note that Weld has a pretty huge construct built around interceptor invocations to make this work. Some relevant bits are [CombinedInterceptorAndDecoratorStackMethodHandler](https://github.com/weld/core/blob/3.1/impl/src/main/java/org/jboss/weld/bean/proxy/CombinedInterceptorAndDecoratorStackMethodHandler.java) or [InterceptionDecorationContext](https://github.com/weld/core/blob/3.1/impl/src/main/java/org/jboss/weld/bean/proxy/InterceptionDecorationContext.java). All in all it is a beast that I am not sure we want to bring over to ArC.

**Comment by leonardowestphal** [comment]
@manovotn 
I have the same problem. I'm migrating a legacy Java EE application to Quarkus...
Will any implementation be done to solve it?

I believe that my problem would be solved if the limitation "Interceptor methods on superclasses are not implemented yet" mentioned in https://quarkus.io/guides/cdi-reference#limitations was implemented. Or maybe if there was an annotation similar to '@ javax.interceptor.ExcludeClassInterceptors'.

Legacy code example (Works on Wildfly):

```
public class UserDAO extends GenericDAO {
  
  public User find(String name) {
    //find...
    return user;
  }
  //other methods...  
}

```

```
public abstract class GenericDAO {

  @PersistenceContext(unitName = "replica")
  private EntityManager emReplica;

  @PersistenceContext(unitName = "master")
  private EntityManager emMaster;

  private EntityManager em;
  
  @AroundInvoke
  public Object failoverInterceptor(InvocationContext ctx) throws Exception {
    try {
      setEm(emReplica);
      return ctx.proceed();
    } catch (Exception e) {
      //on sql serialization failure...
      //some logic here to retry 3 times on replica
      return retryReplica(ctx);
      //if it was not possible try master
      setEm(emMaster);
      return tryMaster(ctx);
    }
  }
  
  public EntityManager getEm() {
    return em;
  }

  private void setEm(EntityManager em) {
    this.em = em;
  } 
    
  ... 
}
```

For now, I will try to use ThreadLocal as workaround...Annotate each desired method would be impracticable and dangerous...

**Comment by manovotn** [comment]
Hmm I thought we don't even support around invoke declared on the bean instead of interceptor class.
At least that's what I understood from https://github.com/quarkusio/quarkus/issues/11942

I'd need to check that though; not in front of my PC now.

**Comment by manovotn** [comment]
I am going to close this issue because the original problem (self-invocation and interception) is a grey specification area and the current implementation was a design choice - in other words, it is intentional that self-invocation triggers interception.

@leonardowestphal I think your report is unrelated to this issue - please create a separate issue and apart from this code also include a stacktrace so that we can see the error you are getting. The problem seems to be with inheritance rather than self-invocation in your case.

**Comment by leonardowestphal** [comment]
> I am going to close this issue because the original problem (self-invocation and interception) is a grey specification area and the current implementation was a design choice - in other words, it is intentional that self-invocation triggers interception.
> 
> @leonardowestphal I think your report is unrelated to this issue - please create a separate issue and apart from this code also include a stacktrace so that we can see the error you are getting. The problem seems to be with inheritance rather than self-invocation in your case.

@manovotn 
The code I posted is just an example of the legacy code that I'm migrating and, as it doesn't work, I had to separate it into a "standard" interceptor, just like the one mentioned in this issue, so my problem became identical to this one.

If Quarkus supported interceptor methods on superclasses, I could maintain the structure of the legacy code, but if the self-invocation continues to occur, it would not solve it in the same way.

**Comment by leonardowestphal** [comment]
Would it be possible to think of an alternative to resolve the issue of self-invocation?

**Comment by manovotn** [comment]
> The code I posted is just an example of the legacy code that I'm migrating and, as it doesn't work, I had to separate it into a "standard" interceptor, just like the one mentioned in this issue, so my problem became identical to this one.

I see. I don't think we are planning to support interceptors declared on target class (or it's superclasses) as that brings a lot of complexity and frankly speaking is super-rarely used. It also stands out from other interception as it doesn't even use bindings and the specification mentions it very briefly.

> Would it be possible to think of an alternative to resolve the issue of self-invocation?

I don't think that's planned, at least not now. The fact that self-invocation triggers interception can be thought of as a design choice (much like it was design choice for Weld to *not* trigger interception with self-invocation). Relying on either of the two behavioral patters lies outside of what specification guarantees to be portable.

**Comment by mkouba** [comment]
> I'm migrating a legacy Java EE application to Quarkus...

Well, Quarkus is simply not another Java/Jakarata EE application server and you'll hit incompatibilities here and there. We do try to keep things aligned with the specs where possible but we also made some design decisions that (we believe) fit better the Quarkus goals and architecture.

**Comment by leonardowestphal** [comment]
Ok, Thanks guys!
I will try to use Threadlocal as a workaround.

To reset the Threadlocal could I use a mechanism similar to this?

```
public class ThreadLocalAwareThreadPool extends ThreadPoolExecutor {

    @Override
    protected void afterExecute(Runnable r, Throwable t) {
        // Call remove on each ThreadLocal
    }
}

```
Could you advise me on the best way to do this using Quarkus?
After each Thread execute I need to make sure that Threadlocal is clean.
