### ISSUE TITLE
Unable to extract null to numerical parameter

### ISSUE THREAD

**Issue by alexkuku** [quarkusio/quarkus#11464]
**Describe the bug**
```
    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    public Object hello(@QueryParam Long userId) {
        return userId;
    }
```
if my request param is nothing and the url will be 
http://localhost:8080/hello?userId= 

**Expected behavior**
return null
or 
return 0

**Actual behavior**
return nothing 
the error is
Unable to extract parameter from http request: javax.ws.rs.QueryParam("userId") value is '' for public java.lang.Object xxx

**To Reproduce**
above

**Configuration**
```properties
1.before try to cast QueryParam, if the value is '',then give null value.
2.before try to cast QueryParam, if the value is '', check the type first, if the type is numerical, give 0.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 11-20.2.0
 - Quarkus version or git rev: 1.7.0.final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by jaikiran** [comment]
Hello @alexkuku, would you be able to paste the complete exception stacktrace please? That will help some of us to quickly see which area needs a fix.

**Comment by alexkuku** [comment]
RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("userId") value is '' for public java.lang.Object com.test.ResultController.getAttendanceResultList(java.lang.Long,java.lang.Long,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer)

**Comment by alexkuku** [comment]
RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("userId") value is '' for public java.lang.Object com.test.ResultController.getAttendanceResultList(java.lang.Long,java.lang.Long,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer)

**Comment by alexkuku** [comment]
I've tried to avoid this exception by set new uri to containerRequestContext in ContainerRequestFilter, but failed, 
and the exception is : RESTEASY003125: Can't set URI after match.

**Comment by bchapuis** [comment]
I'm encountering the same issue with `@FormParam`. When the param is of type Integer or Long, I get the following error:

```
RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.FormParam("param") value is ''
```

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?

**Comment by geoand** [comment]
Closing for lack of feedback
