### ISSUE TITLE
QuarkusSecurityTestExtension fails to read class annotation

### ISSUE THREAD

**Issue by egore** [quarkusio/quarkus#11465]
**Describe the bug**
In QuarkusSecurityTestExtension#beforeEach() the code tries to load the TestSecurity annotation from the method and falls back to the class if not present on the method. The variable "test" unfortunately is a subclass (e.g. if the test is "mypackage.MyTest" the class will be "mypackage.MyTest_Subclass". Therefore the annotations on the class level is not evaluated.

**Expected behavior**
The class-annotation should be read. A solution for doing so properly in JUnit 5 was described in https://stackoverflow.com/questions/59068813/how-to-obtain-a-field-from-my-test-in-a-junit-5-jupiter-extension

**Actual behavior**
The annotations on the class level is not evaluated.

**To Reproduce**
```
@QuarkusTest
@TestSecurity(user = "tom", roles = { "A","B" })
public class MyTest {
  @BeforeEach
  void beforeEach() {
    // Manual way to show what will fail as this.getClass() return _Subclass
    assertNotNull(this.getClass().getAnnotation(TestSecurity.class));
  }
  @Test
  void mytest() {
    // code showing the effect of trying to read the annotation from _Subclass where it is not present.
    assertNotNull(CDI.current().select(SecurityIdentity.class).get());
  }
}
```

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by sberyozkin** [comment]
@egore If you have a bit of time to help Stuart with the PR then it would be appreciated
