### ISSUE TITLE
Optional nested configuration issue

### ISSUE THREAD

**Issue by nbuesing** [quarkusio/quarkus#11475]
**Describe the bug**
I have a Bean annotated with @ConfigProperties with a nested element; which seems to work. However, if I make that nested element optional, I get a missing converter exception.

**Expected behavior**
I would expect that an optional element would not need to be defined in my application.yml, but if the nested element is defined then I would expect the validation within that nested element would apply to those fields.

**Actual behavior**
On startup, I get the following exception:
 java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class dev.buesing.config.Cluster$SslEmbedded

**To Reproduce**
I have a sample project I can include to show the error

1. Create a bean with @ConfigProperties
2. Add a nested element making it Optional<>, e.g. Optional<Ssl>
3. Do not include any entry in the application.yml for that optional element
4. start the application

Cluster (with the SslEmbedded static inner class)
```
package dev.buesing.config;

import io.quarkus.arc.config.ConfigProperties;
import lombok.Data;

import javax.validation.constraints.Min;
import java.util.List;
import java.util.Optional;

@Data
@SuppressWarnings("unused")
@ConfigProperties(prefix = "cluster")
public class Cluster {

    @Data
    @SuppressWarnings("unused")
    public static class SslEmbedded {
        private String truststoreLocation;
        private String truststorePassword;
        private String keystoreLocation;
        private String keystorePassword;
        private String keyPassword;
    }

    private List<String> bootstrapServers;
    private Optional<List<String>> schemaRegistryServers;
    private String securityProtocol = "SSL";
    private Optional<Ssl> ssl;
    private Optional<SslEmbedded> sslEmbedded;

    @Min(1)
    private Integer linger;
}
```

Ssl (separate class)
```
package dev.buesing.config;

import lombok.Data;

@Data
@SuppressWarnings("unused")
public class Ssl {
    private String truststoreLocation;
    private String truststorePassword;
    private String keystoreLocation;
    private String keystorePassword;
    private String keyPassword;
}
```

build.gradle
```
plugins {
    id 'idea'
    id 'io.quarkus' version '1.7.0.Final' apply false
}


repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

version = '1.0'


apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'eclipse'
apply plugin: 'io.quarkus'

group = 'dev.buesing'
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

idea {
    module {
        inheritOutputDirs = false
        outputDir = compileJava.destinationDir
        testOutputDir = compileTestJava.destinationDir
    }
}

dependencies {

    implementation "javax.validation:validation-api:${validation_api_version}"

    implementation 'io.quarkus:quarkus-resteasy-server-common'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    // lombok dependencies
    compileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"

    testCompileOnly "org.projectlombok:lombok:${lombok_version}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok_version}"
}

// only one SL4J should be part of runtime classpath, logback.
configurations.all {
    exclude group: "org.slf4j", module: "slf4j-log4j12"
}
```

gradle.properties
```
quarkusPluginVersion=1.7.0.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.7.0.Final
org.gradle.logging.level=INFO
validation_api_version=2.0.1.Final
lombok_version=1.18.12
quarkus_plugin_version=1.7.0.Final
```

In addition I am not seeing Hibernate Validation working (linger has @Min(0) annotation, but that isn't being honored)

**Configuration**
```properties
cluster:
  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  security-protocol: PLAINTEXT
  linger: -10
```

**Screenshots**

**Environment (please complete the following information):**

uname -a
Darwin Neils-MacBook.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64

java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

Not using GraalVM yet

Quarkus 1.7.0.Final

./gradlew --version
Initialized native services in: /Users/buesing/.gradle/native

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.15.1 x86_64

**Additional context**
(Add any other context about the problem here.)

**Comment by nbuesing** [comment]
sample code:

[quarkus-config.tar.gz](https://github.com/quarkusio/quarkus/files/5098570/quarkus-config.tar.gz)

**Comment by radcortez** [comment]
Hi @nbuesing. I'm sorry for this very late reply. I think this issue got lost somewhere (or at least I didn't notice it).

This is related with https://github.com/quarkusio/quarkus/issues/14847. This is now supported with SmallRye Config @ConfigMapping, so I will consider there is an option to support the expected behaviour (even if it requires to use a different API).
