### ISSUE TITLE
Add optional FIPS mode

### ISSUE THREAD

**Issue by liavyona** [quarkusio/quarkus#11489]
**Description**
As part of choosing framework to work with, some organisations need to be FIPS complaint with their products. Quarkus has no FIPS mode. A FIPS mode will be a great ability and will make Quarkus the easiest choice when it comes to choosing framework.

**Links**
[Zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Fips.20complaint)

**Comment by sberyozkin** [comment]
Looks like we need a CI job which can be run with the FIPS mode enabled

**Comment by liavyona** [comment]
@sberyozkin  Does the framework itself support it at all? Or, should GraalVm or `java` it self should support it in order to be treated as FIPS Compliant?
