### ISSUE TITLE
respect config_ordinal in microprofile-config.properties files

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#11492]
A `ConfigSource` can specify an ordinal (cf. `ConfigSource#getOrdinal()`) for ordering. And according to the [spec](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc) the ordinal can be specified manually using the `config_ordinal` property. Thus I think it should be possible to create a `META-INF/microprofile-config.properties` file in a Quarkus project and add a `config_ordinal` property to specify the ordinal for that particular file / config source.

When I look at the implementation I can see that Quarkus creates a `io.quarkus.runtime.configuration.QuarkusPropertiesConfigSourceProvider.PropertiesConfigSource` object which ultimately inherits from SmallRye Config's `AbstractConfigSource`, which in turn overrides `getOrdinal()` to return a fixed value (in this case `ConfigSource.DEFAULT_ORDINAL`) and will thus never check if the file defines `config_ordinal`, as described in the spec and implemented in the default method `ConfigSource#getOrdinal()`.

https://github.com/quarkusio/quarkus/blob/7a1826dc3a72b2319cc140b171982133795b70ed/core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigUtils.java#L81-L83

I would like to use this mechanism inside a custom Quarkus extension to override some default values of other Quarkus extensions 😬 As a workaround I can implement a custom `ConfigSource`, where I override `getOrdinal()`.

**Comment by knutwannheden** [comment]
Possibly this should instead / also be raised as an issue against SmallRye Config's `AbstractConfigSource` implementation.

**Comment by radcortez** [comment]
Yes, this is SmallRye Config specific. I'll have a look.

**Comment by knutwannheden** [comment]
Works as designed.
