### ISSUE TITLE
Quarkus CLI should look in parent directories to find maven and gradle wrappers

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#11516]
**Description**
In multi-module project you don't want to have the wrappers everywhere, right? at least I don't :), but also you want your command to work in sub-modules.

It would be nice if the new Quarkus CLI would look in parent folders to find `mvnw` or `gradlew` (and their windows equivalent) :)

**Comment by TomasHofman** [comment]
@maxandersen @ia3andy do you mind if I work on this, or has anybody started?

**Comment by maxandersen** [comment]
@ebullient is rewamping the cli but would be interesting to have this. So +1 for me

**Comment by ebullient** [comment]
Code looking for wrappers has been consolidated.. so this should be easier .. go for it
