### ISSUE TITLE
Add a new config category quarkus.hibernate-orm.fetch

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#11527]
The options `quarkus.hibernate-orm.batch-fetch-size` and `quarkus-hibernate-orm.max-fetch-depth` both configure Hibernate's fetching logic and it would thus make sense to move them to a new config category `quarkus.hibernate-orm.fetch`. Of course for some time the original properties should be available as deprecated properties.

See also discussion in #11526.

**Comment by knutwannheden** [comment]
> I like @gavinking's suggestion in [#11526 (comment)](https://github.com/quarkusio/quarkus/issues/11526#issuecomment-678524665)

I have updated the issue title and description accordingly.

**Comment by abhisht51** [comment]
Hi, 
I am beginner at this issue. I get the idea of what we are try to achieve here but it would help if you can let me know what files I need to keep in mind @knutwannheden. Thanks

**Comment by rquinio** [comment]
@abhisht51 That would be in https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java#L73-L89

My understanding is you need to find any reference to these in the extension, use the new properties but fallback to the deprecated ones if the new ones are not set, so it stays backward compatible.

**Comment by mkrzywanski** [comment]
Are there any test classes that test that those properties are actually set? Because I cannot find it.
