### ISSUE TITLE
Quarkus GRPC with blocking objects such as Hibernate EntityManager

### ISSUE THREAD

**Issue by danielochoaglobant** [quarkusio/quarkus#11535]
**Description**
Hi! we're evaluating quarkus + grpc for a set of microservices that access a relational database using jpa/hibernate. So far the POCs have failed apparently because of the gcrp implementation usage of IO threads. When we use the entity manager to execute a query we have the following error:
"java.lang.IllegalStateException - You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread."

We would like to have support for objects that perform blocking operations when working with GRPC services, without creating ManagedExecutors or other hacky approaches. 
Thanks.

**Comment by danielochoaglobant** [comment]
@Sanne @cescoffier Thanks for your responses, we created a workaround similar to what you described, delegating the job to another thread. 
We will move forward with this until reactive Hibernate is available.
Kind regards.

**Comment by michalszynkiewicz** [comment]
Note from the meeting: maybe we could add a `@Blocking` annotation similar to reactive messaging.
Can interceptors be used to offload to a different pool?

**Comment by sebstr1** [comment]
> The gRPC services are called on the I/O thread. We may introduce a way to delegate to the worker pool, but it's not done yet (@michalszynkiewicz). As gRPC is exposing an asynchronous development model, using the I/O thread offers a few benefits.
> 
> So, until the support of blocking is done, you can switch to the worker thread pool using `
> 
> ```
> uni
> .emitOn(Infrastructure.getDefaultPool())
> .invoke(item -> {
>   // can use blocking operation as you are not on the I/O thread anymore
> });
> ```
> 
> More details:
> 
> * https://smallrye.io/smallrye-mutiny/#_how_do_i_control_the_threads
> * https://smallrye.io/smallrye-mutiny/#_how_do_wrap_blocking_calls
> * https://smallrye.io/smallrye-mutiny/#_emiton_vs_runsubscriptionon
Im unable to get data from DB in my GRPC service.

Im using Quarkus 1.9.0.final and javax.persistence.EntityManager

I've tried using Executor, ManagedExecutor and just running the dao call inside a thread. Also tried what is suggested in https://smallrye.io/smallrye-mutiny/#_how_do_wrap_blocking_calls

```
Uni.createFrom().item(dao.getAll())
                    .runSubscriptionOn(Infrastructure.getDefaultWorkerPool());
```

Just to see if I can make the call to db.. In every diffrent attempt I've made it complains about using blocking operation on a IO thread. 

Do you think the @Blocking annotation will make this possible?

**Comment by cescoffier** [comment]
Yes, it will. 
However, I don't understand why it would complain here as you are not accessing the database with the I/O thread.

**Comment by cescoffier** [comment]
wow... sorry, missed it! 

Use:
```
Uni.createFrom().item(() -> dao.getAll()) // Must be a supplier
                    .runSubscriptionOn(Infrastructure.getDefaultWorkerPool());
```

**Comment by cescoffier** [comment]
That is a dumb example but works:

```
@Override
    @Transactional
    public Uni<HelloReply> sayHello(HelloRequest request) {

        return Uni.createFrom().item(() -> {
            return Todo.listAll().size(); // Panache entity
        })
                .runSubscriptionOn(Infrastructure.getDefaultExecutor())
                .onItem().transform(i -> HelloReply.newBuilder().setMessage(Integer.toString(i)).build());

    }
```

**Comment by sebstr1** [comment]
@cescoffier Many thanks for your help! I will make a new attempt with your helpful information

**Comment by cescoffier** [comment]
Closing this issue as the support for blocking has been merged in the master branch.
