### ISSUE TITLE
[io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure

### ISSUE THREAD

**Issue by gema20hd** [quarkusio/quarkus#11537]
**Describe the bug**
(Describe the problem clearly and concisely.)

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
This is the error that is printed if you have a problem in your application (e.g. unresolvable dependency injection, configuration error). You need to fix the error that will be in the logs above this.

**Comment by gema20hd** [comment]
Buenas tardes, tengo error el desplegar.
Subio el proyecto sin problemas.
Error
 at=error code=H10 desc="App crashed" method=GET path="/" host=zumba-distribuida41.herokuapp.com


Ayuda por favor .




Saludos cordiales,


Gema Zumba A.

________________________________
De: Stuart Douglas <notifications@github.com>
Enviado: lunes, 24 de agosto de 2020 18:50
Para: quarkusio/quarkus <quarkus@noreply.github.com>
Cc: Gema Zumba Acosta <gemacostzhd@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [quarkusio/quarkus] [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure (#11537)


Closed #11537<https://github.com/quarkusio/quarkus/issues/11537>.
