### ISSUE TITLE
Error when forwarding request from reverse proxy with Host header

### ISSUE THREAD

**Issue by JChrist** [quarkusio/quarkus#11543]
**Describe the bug**
If the quarkus application is behind a reverse proxy that sets the Host header, then some(?) JAX-RS endpoints fail with a bad request error and the message saying:
```
RESTEASY003320: Failed processing arguments of public java.util.List gr.cytech.TestCaseResource.getCases(long,int,boolean,javax.ws.rs.core.UriInfo)
```
The same endpoint works as expected if hit directly or without the Host header set from the reverse proxy.

**Expected behavior**
The endpoint should work normally regardless of any Host header.

**Actual behavior**
A reverse proxy setting the Host header causes Resteasy to fail the request.

**Comment by sberyozkin** [comment]
@JChrist Hi, can you please provide more info about it or reproducer ?

**Comment by JChrist** [comment]
Sure, let me try to create a minimal project and I will get back to you

**Comment by JChrist** [comment]
It took me quite a while to isolate the required parts to reproduce this, as it is quite weird.
The main point is that the `Host` header was wrong, as it was prefixed with the `\` character, which made resteasy complain (in a very peculiar way though).

In any case, a sample minimal resource is:
```java
package gr.jchrist.resources;

import javax.annotation.security.RolesAllowed;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;

@Path("/hosterror")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class HostErrorResource {
    @GET
    @Path("/here") // <---- 1
    @RolesAllowed("**") //<---- 2
    public String get(@QueryParam("prm") String prm) { // <------ 3
        return "{\"msg\":\"hi there\"}";
    }
}
```

and the reproducing test:
```java
package gr.jchrist.resources;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;

import static io.restassured.RestAssured.given;

@QuarkusTest
public class HostErrorResourceTest {
    @Test
    public void test() throws Exception {
        given().header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                .header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON)
                .header(HttpHeaders.HOST, "\\localhost")
                .get("/hosterror/here")
                .then().statusCode(200);
    }
}
```

The strange part is that if the `QueryParam` (commented as part 3) is removed from the endpoint, then it works OK.
If any of the `@Path` (//point 1) or `@RolesAllowed(**)` (//point 2) is removed, then it doesn't work, but the error thrown is very descriptive of the problem.
When run with all 3 parts, then the error thrown is similar to the originally reported one: 
`RESTEASY003320: Failed processing arguments of public java.lang.String gr.jchrist.resources.HostErrorResource.get(java.lang.String)`

In any case, it all happens when the Host header is invalid (starts with a `\` character), so the issue is that in some cases it doesn't get reported as such.

**Comment by sberyozkin** [comment]
@JChrist Thanks it should probably be reported to the RestEasy team. Re `QueryParam` - it is only a guess, perhaps in RestEasy the headers and the queries processing is inter-related.

**Comment by ralph089** [comment]
Hit the same issue.

**Comment by Cikla38** [comment]
I hit the same issue.
My resource ->
`	@POST
	@Path("/a")
	public Response a(
			@FormParam("aa") String aa,
			@FormParam("aaa") String aaa) {
		
		return Response.ok(true).status(200).build();
	}`

When request body sent with `"form-data"` i get the same message.
It fixed when i sent request body with `"x-www-form-urlencoded"`.

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
