### ISSUE TITLE
Queries in import.sql can't be split to multiple lines anymore

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#11566]
With the latest snapshot (`019f4e7e63`; it doesn't happen in 1.7.0), I noticed that if I have queries in my `import.sql` that are split into multiple lines like
```
insert into Person (gender, name, id)
values ('MALE', 'Jimbo', nextval('hibernate_sequence'));
```
Then each line is executed as if it were a full query, and the application breaks in this case. 
For preserving readability, we should keep allowing splitting queries into multiple lines.

**Comment by gsmet** [comment]
@Sanne looks like your patch didn't work as expected?

**Comment by gsmet** [comment]
I think the issue is there: https://github.com/quarkusio/quarkus/pull/11353/files#diff-62f3a6c6771d8f3a4819eb119de072ecR12 .

The `INSTANCE` should be an instance of `QuarkusImportSqlCommandExtractorInitiator`.

Let me work on a patch (and add a test).
