### ISSUE TITLE
Create Kotlin compiler plugin for open classes

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#1157]
We should create a Kotlin compiler plugin that will stand in place of the all-open plugin and will contain pre-configured all the annotations that result in classes that must not be final (much the same way that the Kotlin spring does).
~~This will also solve [this](https://github.com/jbossas/protean-shamrock/pull/1155#discussion_r261866936) issue.~~

**Comment by geoand** [comment]
I opened an initial PR: https://github.com/JetBrains/kotlin/pull/2163

**Comment by geoand** [comment]
We will need to update the kotlin compiler dependency to `1.3.40` once it is released (currently in EAP) to pick up the necessary changes

**Comment by geoand** [comment]
So it looks like there was extra work that needed to be done: https://github.com/JetBrains/kotlin/pull/2421

**Comment by Dufgui** [comment]
@geoand it's seems they forget you PR. :(

**Comment by geoand** [comment]
Indeed... If you would like to also ping on the Kotlin GitHub to show that is has some activity, that would be great!

**Comment by maxandersen** [comment]
If someone want to pick this up then :

1) find all places we pass manually compiler options in our pom's like  [<option>all-open:annotation=javax.ws.rs.Path</option>](https://github.com/quarkusio/quarkus/blob/0e58d4b1fb532a9002f8379dca8e573e86addf41/devtools/platform-descriptor-json/src/main/resources/templates/basic-rest/kotlin/pom.xml-template.ftl#L116
)  and remove them.

2) see tests fail - especially [this one](https://github.com/quarkusio/quarkus/blob/master/integration-tests/kotlin/src/test/java/io/quarkus/kotlin/maven/it/KotlinDevModeIT.java#L17)

3) research how to make a kotlin compiler plugin

4) implement and enable kotlin compiler plugin

5) enable it and see the tests now pass.

Success!

**Comment by KaenDagger** [comment]
Baiscally this compiler would be extension which would provide preconfigured open classes for these annoataions `@ApplicationScoped, @RequestScoped`. This is what AFAIU

**Comment by geoand** [comment]
Well basically for the annotations we already configure when we generate a Kotlin project.
Other than that, yes you have the correct idea

**Comment by KaenDagger** [comment]
> Well basically for the annotations we already configure when we generate a Kotlin project

by adding annoations in `all-open` plugin ?

**Comment by geoand** [comment]
Exactly.

You can see the ones we add in the pom.xml "template" of the generated Kotlin projects

**Comment by KaenDagger** [comment]
@geoand according to @mkouba comment we should open the classes which are annotated with with these annotations like `@ApplicationScoped, @RequestScoped`, I didn't understand other functions which this compiler plugin has to perform. If we can directly add these annoations in `all-open` plugin

**Comment by geoand** [comment]
@KaenDagger the idea is to have our own compiler plugin so that we don't have to configure the `all-open` plugin for every Quarkus application using Kotlin.
If we had the plugin, all we would do is configure that plugin and everything would be taken care of. 

It makes things easier in the following ways:

* Less configuration in `pom.xml` (or `build.gradle`)
* By having a plugin we can update it in the future with whatever else we might need
* Dev mode setup becomes since you don't have to pass of ton of configuration options around (we have this working for Maven, but not Gradle but if we didn't have to do it all it would be great), we would just pass the the name of the plugin to the Kotlin compiler.

Does that make sense?

**Comment by KaenDagger** [comment]
I get it now. I myself added some options to configure. Developer of the project has to manage those options themselves. By making the compiler plugin we would make that work easy for that developer of the project.
I get it now. thanks

**Comment by geoand** [comment]
Exactly :+1:

**Comment by KaenDagger** [comment]
i have gone through the spring wrapper of all-open

In the maven version. They have added this [KotlinSpringMavenExtension](https://github.com/JetBrains/kotlin/blob/d73e6c855baa6066ba784bf2c77a1ca5854e70fc/libraries/tools/kotlin-maven-allopen/src/main/kotlin/AllOpenMavenPluginExtensions.kt#L43)

For gradle they created [SpringGradleSubPlugin](https://github.com/JetBrains/kotlin/blob/d73e6c855baa6066ba784bf2c77a1ca5854e70fc/libraries/tools/kotlin-allopen/src/main/kotlin/org/jetbrains/kotlin/allopen/gradle/KotlinSpringSubplugin.kt#L22)

As far as I see. for quarkus-kotlin plugin we have to add support in kotlin
And for the list of supported presets , they have added in AllOpenCommandLineProcessor, two annotations have already been added to presets by @geoand

**Comment by geoand** [comment]
Yes that's what we tried to do and the Kotlin team prefered to go a different route... See https://github.com/JetBrains/kotlin/pull/2421

**Comment by KaenDagger** [comment]
I see. I will contact yanex for more info

**Comment by geoand** [comment]
I'm closing this since @KaenDagger worked on it and encountered Kotlin issues and since we have since decided to go another route.
