### ISSUE TITLE
Make GraalVM 20.2.0 the default version

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#11576]
Release notes: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.2.0

**Comment by gsmet** [comment]
@gastaldi FWIW, you might have to tweak what @galderz did to support multiple versions. I don't think we should drop support for 20.1 yet.

**Comment by gastaldi** [comment]
@gsmet if what you're referring to is this: 

https://github.com/quarkusio/quarkus/commit/6190179febd50d71db17fd80392c67ec3275191c#diff-99b0ae6b0ce4104e45b9c9d5f6d3b8a6R275-R285

Rest assured that I haven't changed that in my PR :wink:
