### ISSUE TITLE
Lazy loading fails if an entity appears twice in the object graph

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#11589]
Hibernate lazy loading will fail if a given entity is referenced twice in the object graph (e.g. a diamond pattern, where A lazily loads B and C and both B and C reference an entity D).

A reproducer is here: https://github.com/quarkusio/quarkus/compare/master...stuartwdouglas:lazy-load-problem

In the reproducer a lazily loaded Supervisor class has two Manager's, which both reference the same CEO. The second time the CEO is referenced org.hibernate.engine.internal.TwoPhaseLoad#initializeEntityEntryLoadedState attempts to reload the entity, however the Long ID has been replaced by the actual entity instance in the hydratedState array.

Initially I thought this may be related to the proxy work I did, however I think it is likely actually a hibernate problem, however I need some input from @Sanne as it may be related to something Quarkus specific.

I was initially asked about this by a community user looking at migrating an app from WildFly, so this pattern does work in WildFly.

**Comment by Sanne** [comment]
thanks @stuartwdouglas ! Yes this looks like an upstream bug related to build-time enhancement and the use of enhanced proxies; neither of these features is enabled on WildFly, so that could explain the portability problem.

We'll need to solve it in Hibernate ORM.  cc/ @dreab8

**Comment by dreab8** [comment]
Hi @stuartwdouglas, yes it is definitively an Hibernate problem, created https://hibernate.atlassian.net/browse/HHH-14187 and working on it.

**Comment by Sanne** [comment]
This will be resolved when we upgrade to ORM 5.4.21
