### ISSUE TITLE
Documentation about OIDC: quarkus.oidc.application-type=web_app or quarkus.oidc.application-type=web-app

### ISSUE THREAD

**Issue by evialle** [quarkusio/quarkus#11586]
**Description**

The documentation https://quarkus.io/guides/security-openid-connect#quarkus-oidc_quarkus.oidc.application-type says that only the value web-app or service are accepted.
But in OIDCTenantConfig.java in the enum of ApplicationType, we can see WEB_APP, SERVICE.

**Implementation ideas**
Fix in documentation _ instead of -

**Comment by sberyozkin** [comment]
@evialle You can see in section `2.4.8` at https://quarkus.io/guides/writing-extensions#configuration that `WEB_APP` would be an equivalent of `web-app`, etc. You can probably type `WEB_APP` as well but it is certainly not something I'd like the users to type.
Do you have some IDE erros like invalid enum value, etc ?

**Comment by sberyozkin** [comment]
There is this Visual Studio plugin feature: https://quarkus.io/blog/vscode-quarkus-1.2.0/#quick-fix-for-invalid-enum-value, but I've had that with IntelliJ this can be reported as well.
There is no any problem with the OIDC docs (`WEB_APP` is too technical to recommend setting in the user properties), but perhaps there is some scope for improving the Quarkus IDE integration (assuming this is the reason you opened this issue). If it is the case then please create a dedicated issue suggesting to have the Quarkus enum converter integrated with the IDE plugins closer.

Closing this issue, thanks

**Comment by evialle** [comment]
This is the case with IntelliJ, this is what led me to create that issue...

**Comment by evialle** [comment]
Bug Report on https://github.com/redhat-developer/intellij-quarkus/issues/220
