### ISSUE TITLE
Integrate Mutiny 0.8.0

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#11614]
**Description**

Mutiny 0.8.0 is coming _soon_, and it will require a bit of integration code:

* [ ] Integrate the dropped exception hook

@jponge volunteered to implement this once Mutiny 0.8.0 is released!

**Comment by jponge** [comment]
🥳

**Comment by Sanne** [comment]
@gavinking could you look at impact on Hibernate Reactive? Thanks!

**Comment by gavinking** [comment]
OK will do.

**Comment by gavinking** [comment]
Does Mutiny have a snapshot repo?

**Comment by cescoffier** [comment]
@gavinking yes: https://oss.sonatype.org/content/repositories/snapshots/io/smallrye/reactive/

**Comment by gavinking** [comment]
Thanks. Well, I just ran the HR tests on 999-SNAPSHOT and nothing broke ... so that's a good start!

**Comment by gavinking** [comment]
And I was able to remove all the `onItem()` calls...

**Comment by gavinking** [comment]
> And I was able to remove all the `onItem()` calls...

... and most of the `onTermination()` calls. Great!

**Comment by jponge** [comment]
@cescoffier perhaps we should also integrate a caller thread check for Vert.x event-loops and blocking calls?

**Comment by cescoffier** [comment]
Yes, the blocking code check is going to help a lot.

**Comment by jponge** [comment]
- [ ] Dropped exception hook
- [ ] Blocking thread checker
- [ ] Update documentation references to deprecated APis

**Comment by jponge** [comment]
I have an integration for the exception hook, see the WIP branch at https://github.com/jponge/quarkus/tree/mutiny-0.8.0

**Comment by jponge** [comment]
Regarding the blocked thread checker: are there other kind of threads than Vert.x event loops in Quarkus that cannot be blocked?

**Comment by cescoffier** [comment]
No, just check if it’s en event loop (VertxThread won’t be enough)

**Comment by jponge** [comment]
I haven't spotted documentation with deprecated APIs. That being said it'd be easier if snippets were included from actual sources like we do in Vert.x, so we could more easily track changes when APis move.
