### ISSUE TITLE
empty create should not generate commandmode examples

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#11628]
**Description**
create with no extensions currently generates commandmode .java files.  This should be removed as users may want to create a completely empty project.  commandmode should be its own specific example.

**Comment by mkouba** [comment]
Hm, I've just tried `mvn io.quarkus:quarkus-maven-plugin:create -DcodestartsEnabled -DprojectGroupId=org.acme -DprojectArtifactId=go-go-commando` and `src/main/java` in the generated project is empty; plugin version used: 0.21.2.

**Comment by mkouba** [comment]
CC @ia3andy

**Comment by ia3andy** [comment]
@mkouba you need to add `-DskipExample` if you want an empty app.

**Comment by mkouba** [comment]
Well, in my case it was empty even without `-DskipExample`. See the snippet above.

**Comment by ia3andy** [comment]
@mkouba I don't really get what you mean here, by default and without any extension selected command mode example is activated per spec, if you want an empty app you will need `skipExample`.

**Comment by ia3andy** [comment]
We don't have any "command mode" extension so this is kind of the "default" one.

**Comment by mkouba** [comment]
Sorry, an ancient version of `quarkus-maven-plugin` is automatically used if no version is specified. It works as described with 1.7.0.Final.

Do you happen to know why Maven used this ancient version?

**Comment by ia3andy** [comment]
@aloubyansky 👆?

**Comment by ia3andy** [comment]
maybe cache?

**Comment by ia3andy** [comment]
Can we close?

**Comment by patriot1burke** [comment]
I don't agree that a command mode example should be added if no extensions are specified.  It should be explicit that you want that code.

**Comment by patriot1burke** [comment]
You can't assume that somebody wants commandmode example code if they do not specify any extensions when they "create"

**Comment by ia3andy** [comment]
> You can't assume that somebody wants commandmode example code if they do not specify any extensions when they "create"

@patriot1burke why not?

TBH, I am not a total fan either, but since there is no command-mode extension, we don't have a lot of options.

@maxandersen 👆

**Comment by patriot1burke** [comment]
why not?  Because most people aren't going to know WTF command mode is.  They might assume that a @QuarkusMain app is required.  Also, is there any side effect of having a @QuarkusMain in a service app? 

if extensions.contains("commandmode") generate command mode .java files.

**Comment by ia3andy** [comment]
> Because most people aren't going to know WTF command mode is. They might assume that a @QuarkusMain app is required.

Well having a psvm "hello world" in java is very common, command mode is very similar to that

> is there any side effect of having a @QuarkusMain in a service app?

no they are compatible, you could have REST API for a service, and also provide access to it from command line for example.

> if extensions.contains("commandmode") generate command mode .java files.

very inconsistant, bad idea IMO

**Comment by mkouba** [comment]
> if extensions.contains("commandmode") generate command mode .java files.

I think that we should support this because a user may need to add extensions and still use the command mode...

**Comment by ia3andy** [comment]
> I think that we should support this because a user may need to add extensions and still use the command mode...

@mkouba well, I also think this is a problem, but I don't think this is the solution since we don't have command mode extension.

**Comment by maxandersen** [comment]
`quarkus create --no-example` would be my suggestion for the cli syntax.

we've discussed supporting `quarkus crate --example=<tag/explicit named starters>` to "force" specific starter - but that would ignore extensions.

And @patriot1burke commandmode is equivalent to normal launch - no sideeffects.

**Comment by mkouba** [comment]
> I don't think this is the solution since we don't have command mode extension.

Ok, I understand. Is there any other flag that can be used to generate stuff in codestarts? I mean other then `-Dextensions`. It could be useful, e.g. for fine-grained configuration for extensions. Let's say you would like add RESTEasy extension to generate a simple endpoint. But then you can have an example of a JAX-RS `ExceptionMapper`...

**Comment by patriot1burke** [comment]
Sorry guys, I just don't agree...but...whatever :-)  You just shouldn't generate .java code for something you didn't ask for :)  But...Again...whatever :)
