### ISSUE TITLE
Overall CI improvement

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#11622]
- [x] Get maven controlled execution of docker containers (avoid starting unused images during build) - TestContainers is a good option. (https://github.com/quarkusio/quarkus/pull/13134)
- [x] For pull-request based builds, introduce a Maven build extension to trigger the build only for modules that are affected by the changes introduced in the pull-request (Trigger the build for downstream projects) (#6260)
	 - [This PR](https://github.com/quarkusio/quarkus/pull/11331) enables `*-deployment` modules during reactor projects resolution for integration tests
     - Tools like GIB (https://github.com/vackosar/gitflow-incremental-builder) can reason about our build without special quarkus knowledge

**Comment by maxandersen** [comment]
> * Check if master builds are deployed to a central location (the Sonatype Snapshot Repository?) to avoid rebuilding all sources from scratch on each pull-request

This does not sound right...you would need those snapshots to be from same base master branch...or do you mean that we would have the build use sha1 named versions ?

**Comment by n1hility** [comment]
> > * Check if master builds are deployed to a central location (the Sonatype Snapshot Repository?) to avoid rebuilding all sources from scratch on each pull-request
> 
> This does not sound right...you would need those snapshots to be from same base master branch...or do you mean that we would have the build use sha1 named versions ?

Yeah I think we should skip this idea. We already cache the maven repository. We could cache the local build artifacts as well but this would only save 13 minutes. I think we have bigger problems.

**Comment by gastaldi** [comment]
Ok, I removed it, for now :)
