### ISSUE TITLE
@CircuitBreaker failOn doesnt work on Custom exceptions thrown by the method - For reactive downstream code

### ISSUE THREAD

**Issue by harry9111985** [quarkusio/quarkus#11632]
**Describe the bug**
@CircuitBreaker failOn doesnt work on Custom exceptions thrown by the method - For reactive downstream code

**Expected behavior**

The assumption of the failOn functionality is that if the execution failure count is greater than requestVolumeThreshold for a  CustomException thrown by the method where the CustomException is part of the failOn exception List. 

When the next API call calls the same downstream code , A circuit breaker open exception should be thrown.

**Actual behavior**

Circuit Breaker Open is never triggered.

**To Reproduce**
1.  Have a reactive method and annotate the method with  @CircuitBreaker(requestVolumeThreshold = 5, delay = 1000,failOn = {XYZRuntimeException.class,CompositeException.class,RuntimeException.class})
   
2.  have mutiny onFailure block which throws XYZRuntimeException consecutively for 5 times not at the same time but one after the other.

3. 6th call still throws the same XYZRuntimeexception instead of CircuitBreaker open exception.

Sample reactive method 

```
@CircuitBreaker(requestVolumeThreshold = 5, delay = 1000, failOn = {XYZRuntimeException.class,CompositeException.class,RuntimeException.class})
    public Mono<String> processString(String myString) {
        return Uni.createFrom().item(myString)
                .convert()
                .with(UniReactorConverters.toMono())
                .map(str -> {
                    if ("abc".equals(str)) {
                        throw new RuntimeException();
                    } else {
                        return str;
                    }
                })
                .onErrorMap(Throwable.class,throwable -> new XYZRuntimeException("Something wrong happened while processing request"));
     }
```

or 

```
@CircuitBreaker(requestVolumeThreshold = 5, delay = 1000, failOn = {XYZRuntimeException.class,CompositeException.class,RuntimeException.class})
    public Uni<String> processString(String myString) {
        return Uni.createFrom().item(myString)
                .map(str -> {
                    if ("abc".equals(str)) {
                        throw new RuntimeException();
                    } else {
                        return str;
                    }
                })
                .onFailure()
                .transform(throwable -> new XYZRuntimeException("Something wrong happened while processing request"));
                
     }
```

In the above request If i have API which sends string "abc" 5 times one after the other , XYZRuntimeException is thrown every single time. The 6th time I expect a CircuitBreakerOpen exception because `XYZRuntimeException` is part of the `failOn` exception list and the requestVolumeThreshold is `5`.

**Comment by mkouba** [comment]
CC @Ladicek @michalszynkiewicz @cescoffier

**Comment by Ladicek** [comment]
SmallRye Fault Tolerance doesn't support "reactive" return types, just `CompletionStage` for now. Tracked in https://github.com/smallrye/smallrye-fault-tolerance/issues/219

**Comment by harry9111985** [comment]
Thanks @Ladicek .. is there a timeline for releasing this feature ? is it part of the next 1,2 or 3 month roadmap ?

**Comment by Ladicek** [comment]
There's no roadmap, but this seems to be requested more and more often. I'm currently busy with another project, but I'll try to find some time to work on this.

**Comment by harry9111985** [comment]
@Ladicek : thank you so much for your reply. It would be really helpful if you could get sometime to look into this feature as it would greatly help us to implement Circuit Breaker on Reactive routes with Mutiny/Webflux objects . This would help have heavy multi-downstream business service methods protected by Circuit breaker in the reactive space.

**Comment by gsmet** [comment]
@Ladicek I think we could focus on the Mutiny types first. That's what we recommend in Quarkus.

**Comment by Ladicek** [comment]
I need to lay down some ground work, after that it doesn't matter what async types we want to support. So far, it's very `CompletionStage`-specific, and while it can be used as an interop type, it's not really a good fit.

**Comment by harry9111985** [comment]
Thanks @Ladicek  . one of the other things which i can suggest would be to have exceptions part of the fallback method signature.I did not find that when i was trying out fallback methods with small-rye-fault-tolerance/Quarkus 1.6.1.

something like this 

```
@CircuitBreaker(requestVolumeThreshold = 5, failOn = {NumberFormatException.class})
@Fallback(fallBackMethod = "fallback")
public Uni<String> method(String param1) {
    return Uni.createFrom().failure(new NumberFormatException());
}

private Uni<String> fallback(String param1, IllegalArgumentException e) {
    return Uni.createFrom().item("test");
}

private Uni<String> fallback(String param1, RuntimeException e) {
    return Uni.createFrom().item("test");
}
```
or 

```
@CircuitBreaker(requestVolumeThreshold = 5, failOn = {NumberFormatException.class})
@Fallback(fallBackMethod = "fallback")
public Mono<String> method(String param1) {
    return Mono.error(new NumberFormatException());
}

private Mono<String> fallback(String param1, IllegalArgumentException e) {
    return Mono.just("test");
}

private Mono<String> fallback(String param1, RuntimeException e) {
    return Mono.just("test");
}
```

This will help us on getting control of the exceptions being thrown by circuit breaker and do decision making based on the exceptions. Sometimes we may need to return a fallback but sometimes we may need to throw exception back.

**Comment by Ladicek** [comment]
I'm not sure if I understand, but if you want access to the "causing" exception in a fallback, you can use `FallbackHandler`.

In any case, any and all suggestions can be submitted in the SmallRye Fault Tolerance issue tracker: https://github.com/smallrye/smallrye-fault-tolerance/issues. I took the liberty of filing https://github.com/smallrye/smallrye-fault-tolerance/issues/274 for your fallback suggestion.

**Comment by harry9111985** [comment]
Thanks @Ladicek for filling in the suggestion .

**Comment by cescoffier** [comment]
Closing as fixed in 2.0.

**Comment by ambition-consulting** [comment]
Is this documented anywhere? Took me forever to find out about the required annotations when guarding Unis.

**Comment by Ladicek** [comment]
Starting with SmallRye Fault Tolerance 5.2.0, which will be available since Quarkus 2.1.0.Final, there's a non-compatible mode that doesn't require extra annotations for async methods. The MicroProfile Fault Tolerance specification explicitly says that this shouldn't work (which is why I originally went for extra annotations), but I find that less and less appropriate. So even if SmallRye Fault Tolerance has the non-compatible mode disabled by default, the Quarkus integration enables it by default. See https://smallrye.io/docs/smallrye-fault-tolerance/5.2.1/usage/extra.html#_non_compatible_mode for more info.

**Comment by cescoffier** [comment]
For existing documentation, there is: https://smallrye.io/docs/smallrye-fault-tolerance/5.2.1/usage/extra.html#blocking-nonblocking

**Comment by ambition-consulting** [comment]
For completeness, this is the JDK 11 error associated with not using the annotations:
java.lang.ClassCastException: class io.smallrye.context.Jdk9CompletableFutureWrapper cannot be cast to class io.smallrye.mutiny.Uni (io.smallrye.context.Jdk9CompletableFutureWrapper and io.smallrye.mutiny.Uni are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader

Same for JDK 15 with Jdk12CompletableFutureWrapper
