### ISSUE TITLE
auto-service-loader-registration=true does not work in quarkus/integration-tests

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#11655]
**Describe the bug**
I'm creating a project in devtools/cli where I want to build a native image and set auto-service-loader-registration=true within src/main/resources/application.properties.  This flag is completely ignored.

**To Reproduce**

You can reproduce by going to quarkus/integration-tests/amazon-lambda and adding auto-service-loader-registration=true to that project's application.properties and running -Dnative.  Notice that -H:+UseServiceLoaderFeature  IS NOT set, but -H:-UseServiceLoaderFeature  is.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux localhost.localdomain 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "11.0.5" 2019-10-15

**Comment by geoand** [comment]
cc @dmlloyd @radcortez

**Comment by jaikiran** [comment]
I think this https://github.com/quarkusio/quarkus/pull/11659 should fix it.
