### ISSUE TITLE
Debug mode that analyses unsafe reflection calls

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#1166]
When debugging native image issues it would be great if we could instrument calls to the reflection API, and report on any problematic ones. The current trial and error approach is really slow.

**Comment by dmlloyd** [comment]
This was contributed within the last week: https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md

**Comment by gsmet** [comment]
@stuartwdouglas isn't this the agent you developed?

**Comment by stuartwdouglas** [comment]
Yea, but the agent definitely needs some love, as it has been neglected since the initial contribution, and is not really documented. It's also fairly difficult to write tests for. Improving it is fairly low on my priority list though, so it is unlikely to happen until I actually need it to get something working on native. 

The problem with the native Graal one is that it will report way too many false positives as it does not take into account things we would already register. 

I would say it is only partially complete but is something we want to improve, so should stay open for now.
