### ISSUE TITLE
Missing logs produced inside QuarkusTestResource

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#11680]
**Describe the bug**
Using logger inside classes wrapped with `QuarkusTestResource`produces no logs. Is this a known issue or is there something wrong with the configuration? (Note that using `System.out.print` works as expected)

Example (anything logged inside `PostgresTestResource` is not in standard output):

```
@QuarkusTestResource(PostgresTestResource.class)
@QuarkusTest
@Tag("integration")
public class AppConfigResourceTest {

    ....
}


@Slf4j
public class PostgresTestResource {

    ...log here somewhere
}
```

Its a gradle project which includes the following section in `build.gradle`:
```java
    test {
        systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
        testLogging.showStandardStreams = true
    }
```

**Environment (please complete the following information):**
 - Output of `java -version`: 13
 - Quarkus version or git rev: 1.6.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.6.1

If this is new and if required I can prepare a reproducer.

**Comment by famod** [comment]
This is a known limitation. See #10885 
There is a hint in the class Javadoc of `QuarkusTestResourceLifecycleManager` starting with 1.7.0: test-framework/common/src/main/java/io/quarkus/test/common/QuarkusTestResourceLifecycleManager.java
