### ISSUE TITLE
Interceptor bindings must not be inherited from interfaces implemented by a bean

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#11704]
https://github.com/quarkusio/quarkus/commit/d2321964a08e3cfd8583767d590be842e4679b61 introduced a regression where interceptor bindings are inherited from interfaces implemented by a bean.

The spec is very clear that this should not be possible. See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#inheritance for more info. JSR-250 also mentions in the "General Guidelines for Inheritance of Annotations":
> The interfaces implemented by a class never contribute annotations to the class itself or any of its members.

**Comment by famod** [comment]
FTR, this came up here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40Interceptors.3F
