### ISSUE TITLE
updating an entity does not work using the repository pattern

### ISSUE THREAD

**Issue by ealcantara22** [quarkusio/quarkus#11733]
**Describe the bug**
I'm writing a REST API in quarkus and today I've noticed that all the update methods stop working.  As mentioned in the issue title I'm using the [repository pattern](https://quarkus.io/guides/hibernate-orm-panache#defining-your-entity-2) (personal choise).

Basically, performing a `PUT` or `PATCH` request does not save the changes into the database no matter if the action is marked as `Transactional`.

**To Reproduce**

```java
@Entity
public class Department {

    @Id
    @GeneratedValue
    public Long id;

    @NotBlank(message = "Department name is required")
    @Column(nullable = false)
    public String name;

}
```
```java
@ApplicationScoped
public class DepartmentRepository implements PanacheRepository<Department> {
}
```
```java
// DepartmentService Class
public Department update(Department department, DepartmentDto data) {
   departmentMapper.map(data, department);  //MapStruct
   validateDepartment(department); //ConstraintValidator
   departmentRepository.persist(department);
   return department;
}
```
```java
@Path("/departments")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class DepartmentResource {
   @Inject
   DepartmentMapper departmentMapper;

   @Inject
   DepartmentService departmentService;

   @PUT
   @Path("/{id}")
   @Transactional
   public DepartmentDto update(@PathParam("id") Long id, DepartmentDto data) {
       Department department = departmentService.getById(id);

       if (department == null)
            throw new NotFoundException("Department not found");

       return departmentMapper.toDto(departmentService.update(department, data));
    }
}
```

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = *********
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/quarkus

quarkus.hibernate-orm.database.generation = update
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux OP790 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk 11.0.8 2020-07-14

**Additional context**
I adjusted the logic above to use the `active record pattern` and it worked without problems.

Thanks for the great work!! 👍🏼

**Comment by loicmathieu** [comment]
@ealcantara22 if your entity didn't extends `PanacheEntity` or `PanacheEntityBase` it must be a valid JPA entity with it's getters and setters. If you don't want to write those getters and setters you can have your entity extends `PanacheEntity` or `PanacheEntitybase` even if you are using the repository pattern.
More info in the guide: https://quarkus.io/guides/hibernate-orm-panache#solution-2-using-the-repository-pattern

**Comment by ealcantara22** [comment]
I see, yeah both suggestions worked just fine. Thanks @loicmathieu

**Comment by loicmathieu** [comment]
OK, so I close the issue
