### ISSUE TITLE
FileNotFoundException for /import.sql when running native executable standalone

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#11773]
Elytron JDBC native tests build natives with application.properties containing:

```
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:elytron_jdbc_test;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:import.sql'
```

However, when you take that native executable and run it on it's own, you see:

```
❯ quarkus-elytron-security-jdbc-integration-test-999-SNAPSHOT-runner
    -Dquarkus.http.port=8081 
    -Dquarkus.http.ssl-port=8444 \
    -Dtest.url=http://localhost:8081 \
    -Dquarkus.log.level=TRACE \
    -Dquarkus.log.console.level=TRACE \
...
2020-09-01 08:24:17,976 DEBUG [io.agr.pool] (Agroal_17881124031) Cause: : org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.FileNotFoundException: resource /import.sql"; "classpath:import.sql"; SQL statement:
```

Where is Quarkus expecting import.sql to be? Isn't it inside the binary itself? If you expect it in a classpath, the classpath of what? In this case the client is running in a different host.

I worked around this by copying the `import.sql` to a folder and then calling the native executable as:

```
❯ quarkus-elytron-security-jdbc-integration-test-999-SNAPSHOT-runner \ 
    -Dquarkus.http.port=8081 
    -Dquarkus.http.ssl-port=8444 \
    -Dtest.url=http://localhost:8081 \
    -Dquarkus.log.level=TRACE \
    -Dquarkus.log.console.level=TRACE \
    -Dquarkus.datasource.jdbc.url="jdbc:h2:tcp://localhost/mem:elytron_jdbc_test;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM './import.sql'"
```

See [longer output](https://gist.github.com/galderz/16a5d105584cf89b009686f4afd8d160).

It helps reproducing issues more quickly and effectively if the native executable invocation works as is, without reshuffles likes this.

Discovered in #11768

**Comment by geoand** [comment]
Is this still an issue?

**Comment by galderz** [comment]
Doubt it. I'll reopen if I see it happen again.
