### ISSUE TITLE
Command line app ignores SIGINT (Ctrl+C)

### ISSUE THREAD

**Issue by ivangreene** [quarkusio/quarkus#11792]
**Describe the bug**
Quarkus command line apps do not respond to SIGINT

**Expected behavior**
A Quarkus command line app should initiate shutdown when passed SIGINT (Ctrl+C on a terminal)

**Actual behavior**
The signal is ignored, nothing happens

**To Reproduce**
1. Clone https://github.com/ivangreene/my-quarkus-cli
2. Run `mvn clean package`
3. Run `java -jar target/my-quarkus-cli-1.0-SNAPSHOT-runner.jar`
4. Press Ctrl+C

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin ivan.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin`
 - Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.7.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

**Comment by gastaldi** [comment]
@ivangreene The recommended procedure is to call `Quarkus.waitForExit()` instead of using `Thread.sleep` in a loop. See https://quarkus.io/guides/command-mode-reference#the-command-mode-lifecycle for more details.

**Comment by gastaldi** [comment]
@stuartwdouglas any clue?

**Comment by gastaldi** [comment]
Found the issue, there is a shutdown hook holding the application. I'll send a PR soon

**Comment by gastaldi** [comment]
@ivangreene can you give it a shot with https://github.com/quarkusio/quarkus/pull/11797 and let me know if that works for you?

**Comment by ivangreene** [comment]
@gastaldi tested this out with my reproducer, works great
