### ISSUE TITLE
SseEventSink#send invalid SSE message

### ISSUE THREAD

**Issue by emfataliev** [quarkusio/quarkus#11824]
**Describe the bug**
In the case of large sse message (±30 Kb), body writer divide the message into blocks and sent it in the wrong sequence. 

**Expected behavior**
Outbound SSE message should be equals SseEventSink#send argument

**Actual behavior**
Outbound SSE message does not equal SseEventSink#send argument

**To Reproduce**
1. Create SSE endpoint
2. Send SSE message (size should be ±30 Kb) via SseEventSink#send

Look at repository https://github.com/emfataliev/quarkus-sse-bug ([Test](https://github.com/emfataliev/quarkus-sse-bug/blob/master/src/test/java/ru/sse/SseExampleTest.java))

**Configuration**
By default

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  
```
Darwin macbook-efataliev 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - Quarkus version: `1.7.1.Final`
 - Build tool:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 11.0.7, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
Default locale: ru_RU, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

**Comment by cescoffier** [comment]
CC @FroMage @asoldano

**Comment by FroMage** [comment]
Yeah, sorry I don't have time for that ATM, perhaps @asoldano can find someone else?

**Comment by asoldano** [comment]
CC @jimma

**Comment by emfataliev** [comment]
Perhaps the error occurs at SseEventOutputImpl.java:233-234
```java
CompletionStage<Void> a = aos.asyncWrite(SseConstants.DOUBLE_EOL);
CompletionStage<Void> b = aos.asyncFlush();
```

`io.quarkus.resteasy.runtime.standalone.VertxOutputStream#asyncWrite` writes response by 8 kb chunks

**Comment by Savalek** [comment]
cool!

**Comment by emfataliev** [comment]
#https://github.com/resteasy/Resteasy/pull/2510

**Comment by asoldano** [comment]
https://issues.redhat.com/browse/RESTEASY-2689

**Comment by emfataliev** [comment]
@asoldano, thanks for fixing this important bug! @D01B thanks to you too! 
when will these fixes be in quarkus?

**Comment by asoldano** [comment]
@emfataliev , see https://github.com/quarkusio/quarkus/pull/12232
