### ISSUE TITLE
JPA Form Based Authentication don't work if username is incorrect

### ISSUE THREAD

**Issue by webfolderio** [quarkusio/quarkus#11833]
**Describe the bug**
Form based JPA authentication hangs if username is incorrect.

**Expected behavior**
Quarkus should be return HTTP 403.

**Actual behavior**
HTTP request ends due to timeout.

**To Reproduce**
1. git clone https://github.com/webfolderio/quarkus-quickstarts
2. cd quarkus-quickstarts/security-jpa-quickstart
3. mvn test

**Configuration**
```properties
quarkus.datasource.url=jdbc:postgresql:elytron_security_jpa
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus

quarkus.http.auth.form.enabled=true

quarkus.hibernate-orm.database.generation=drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

```
Microsoft Windows [Version 10.0.19041.450]
```

 - Output of `java -version`: 

```
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

 - Quarkus version or git rev: 

1.7.1.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\maven\bin\..
Java version: 12.0.1, vendor: Oracle Corporation, runtime: C:\java\jdk-12.0.1
Default locale: en_US, platform encoding: utf-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**

Sample problem reported at [#8734](https://github.com/quarkusio/quarkus/pull/8734#issuecomment-643397784)

**Comment by sberyozkin** [comment]
Hi @webfolderio I think #11808 may have fixed it

**Comment by webfolderio** [comment]
Thanks @sberyozkin 

This is duplicate issue, please see #11807

**Comment by sberyozkin** [comment]
Hi @webfolderio thanks, hopefully it does fix it, please double check if you can get a bit of time
