### ISSUE TITLE
gelf takes about 2 minutes to start

### ISSUE THREAD

**Issue by wjsgzcn** [quarkusio/quarkus#11875]
**Describe the bug**
When using gelf and debug my quarkus application,  I find my app takes very long time (about 2 minutes) to start. 

**Expected behavior**
My app should be started in several seconds.

**Actual behavior**
My app is started in several minutes.

**To Reproduce**
1.  WSL2
2.  OpenJDK 11
3.  Adding gelf to dependency and set quarkus.log.handler.gelf.enabled=true
4.  RUN mvn quarkus:dev, and it spend 2 minutes to start.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=example
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jinfeng
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.default-schema=topic
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=localhost
quarkus.log.handler.gelf.port=12201
quarkus.flyway.schemas=topic
quarkus.log.console.level=ALL
```

**Screenshots**
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-09-04 11:01:51,672 INFO  [io.qua.fly.FlywayProcessor] (build-25) Adding application migrations in path '/home/jason/projects/jinfeng/jinfeng-topic/target/classes/db/migration/' using protocol 'file'
2020-09-04 11:04:28,416 INFO  [io.quarkus] (Quarkus Main Thread) topic 1.0.0 on JVM (powered by Quarkus 1.7.1.Final) started in 158.763s. Listening on: http://0.0.0.0:8080
2020-09-04 11:04:28,425 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-09-04 11:04:28,427 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-search-elasticsearch, jdbc-postgresql, logging-gelf, mutiny, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-openapi, swagger-ui]

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux X395 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk 11.0.8 2020-07-14
 - GraalVM version (if different from Java): no
 - Quarkus version or git rev:  1.7.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by wjsgzcn** [comment]
It is happened in WSL, when I move the jar file to Windows, it start very quick.

**Comment by geoand** [comment]
Hi,

Can you please run `mvn -Dquarkus.debug.print-startup-times=true quarkus:dev` and augment the description of the issue with this information?

**Comment by gsmet** [comment]
My guess would be a network configuration issue leading to a timeout.

**Comment by wjsgzcn** [comment]
I run `mvn -Dquarkus.debug.print-startup-times=true quarkus:dev`:
```
LogManager error of type GENERIC_FAILURE: Port localhost:12201 not reachable
java.net.PortUnreachableException
```
It seems the gelf port is not ok.

When I change the gelf address from localhost to 0.0.0.0, everything seems good.

So that is a network issue.
