### ISSUE TITLE
Native Image Compressed Executable Size

### ISSUE THREAD

**Issue by yampug** [quarkusio/quarkus#11905]
**Description**
The binary that native-image generates, is compressing quite well. For example, in the case of my app (no bundled resources) it is about 39 Mb in size, it does not have many dependencies but compresses with gzip from 39Mb down to 14Mb (default level 6 compression). Wouldn't that mean that there should be some room to optimize and trim the binary size? (as it seemingly implies lots of repetition)

I understand that this feature request/question may be better addressed to the GraalVM team but since Red Hat is also on the consortium, it may also fit here.

As I understand it, the main hook for Quarkus/Native-Images are the fast startup times (for serverless), which means generating compressed binaries would be counter-productive (decompression overhead). Just wanted to hear if you explored this direction before and are there plans to address the size of the executable?

**Comment by geoand** [comment]
We now have integration with ubx (which the GraalVM team recommends to use with native-image), so I'll close this as done
