### ISSUE TITLE
Can't shut up logs

### ISSUE THREAD

**Issue by ambition-consulting** [quarkusio/quarkus#11914]
When running Quarkus as thin jar, I cannot get the logs to shut up. Other modes might also be affected.

When disabling the logs, I would expect no more logs to show up. Considering how console logs can affect performance, I wonder why nobody else complains.

**To Reproduce**

```
quarkus:
  log:
    console:
      enable: false
      level: 'OFF'
    file:
      enable: true
      async: true
```

java -Dquarkus-profile=prod -Dquarkus.http.port=8083 -jar target/whatever-1.0.0-SNAPSHOT-runner.jar

I also tried configuration via prod profile, no difference.

**Configuration**
jdk 14 for maven build with plugin and execution
quarkus 1.7.2.RELEASE
added dependency	io.quarkus:quarkus-config-yaml to maven
configuration is being used successfully for jdbc configuration also

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/4218334/92290601-f52d6a00-ef14-11ea-83ea-95bba0f11222.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MSYS_NT-6.1 LF-21132 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
 - Output of `java -version`: 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
 - GraalVM version (if different from Java): comes with maven via quarkus dependency manager
 - Quarkus version or git rev: 1.7.2, but also confirmed for 1.6.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Java version: 14.0.2, vendor: Oracle Corporation, runtime: C:\Users\yaya\tool\jdk-14.0.2
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Additional context**
(Add any other context about the problem here.)

**Comment by dmlloyd** [comment]
Looks like the log manager didn't get set up properly for some reason.  A workaround may be to manually set `-Djava.util.logging.manager=org.jboss.logmanager.LogManager`.

**Comment by maxandersen** [comment]
it didn't get set up properly as the command used was `java -Dquarkus-profile=prod -Dquarkus.http.port=8083 -jar target/whatever-1.0.0-SNAPSHOT-runner.jar`

As documented at https://quarkus.io/guides/logging#how-to-configure-logging-for-quarkustest when launching quarkus manually (or during tests) you need to set this property manually.

thus if you run it with `java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=prod -Dquarkus.http.port=8083 -jar target/whatever-1.0.0-SNAPSHOT-runner.jar` you should be good.

**Comment by ambition-consulting** [comment]
You are right, adding the LogManager helped. Thank you. :-)
