### ISSUE TITLE
default code gen not working in 1.8.0.CR1

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#11915]
**Describe the bug**
following guide at https://quarkus.io/guides/redis using command:

```
mvn io.quarkus:quarkus-maven-plugin:1.7.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=redis-quickstart \
    -Dextensions="redis-client, resteasy-jsonb, resteasy-mutiny"
cd redis-quickstart
```

the resulting project does not have any files in java nor test.

```shell
❯ tree
.
├── README.md
├── mvnw
├── mvnw.cmd
├── pom.xml
└── src
    ├── main
    │   ├── docker
    │   │   ├── Dockerfile.fast-jar
    │   │   ├── Dockerfile.jvm
    │   │   └── Dockerfile.native
    │   ├── java
    │   └── resources
    │       ├── META-INF
    │       │   └── resources
    │       │       └── index.html
    │       └── application.properties
    └── test
        └── java

9 directories, 9 files
```

**Expected behavior**
There should be a working example as in previous version.

**Comment by gsmet** [comment]
Needless to say this is highly critical and is a blocker.

**Comment by gsmet** [comment]
Also, we need to check if it's an issue in 1.7 too.

**Comment by ia3andy** [comment]
Having a quick look, but I won't be able to spend long

**Comment by ia3andy** [comment]
Ok I can reproduce on 1.7.2.Final, 1.8.0.CR1 and master

**Comment by ia3andy** [comment]
className is null, I need to find why..

**Comment by ia3andy** [comment]
this doesn't seem to be due to the codestarts, I don't see where the className default value is set.. When this is no className we don't generate the classes..

**Comment by ia3andy** [comment]
Well this seems to be expected I see everywhere in the code: `// If className is null, we won't create the REST resource,`

And by default this is null...

```Java

    @Parameter(property = "className")
    private String className;
```

I let you see for the rest.

**Comment by ia3andy** [comment]
Ok I can reproduce on `1.6.0.Final` this has been there forever.. going back to WE

**Comment by maxandersen** [comment]
Ahh. That's "fun" so we've had "empty" project gen I just never by chance not send without class name. 

Closing as working as expected.
