### ISSUE TITLE
Wrong work is parsing configuration VaultRuntimeConfig

### ISSUE THREAD

**Issue by xumk** [quarkusio/quarkus#11921]
Class VaultConfigSource used it own parser for read app configuration with help regexp.
`
public static final Pattern SECRET_CONFIG_KV_PATH_PATTERN = Pattern
            .compile("^quarkus\\.vault\\.secret-config-kv-path\\.([^.]+)$");
`
VaultRuntimeConfig
`
    @ConfigItem(name = "secret-config-kv-path.\"prefix\"")
    public Map<String, List<String>> secretConfigKvPrefixPath;
`
It regex does not parsing prefix string with dot char, example wrong work:
`
quarkus.vault.secret-config-kv-path."mp.jwt.verify"=myapps/app1
`

I think, need fix this regex or rewrite all class in microprofile style, similarly LogConfig class.
`
    @ConfigItem(name = "category")
    @ConfigDocSection
    public Map<String, CategoryConfig> categories;
`

What do you think about this?

**Comment by sberyozkin** [comment]
CC @vsevel

**Comment by vsevel** [comment]
the plan is to move away from a dedicated parser. some support is expected fro the smallrye config project, as discussed here https://github.com/quarkusio/quarkus/issues/9991#issuecomment-656816961
@radcortez when do you think a 1.9 release might be available?

**Comment by radcortez** [comment]
We were having a few issues with native mode that required a few changes. I think most of the work is done, so hopefully by the end of this week or next week.

**Comment by xumk** [comment]
@radcortez @vsevel 
Hello, when can someone start solving this problem?

**Comment by radcortez** [comment]
Hi @xumk.

Sorry for the delay. This is not forgotten and just recently we started another discussion with some ideas here: https://github.com/quarkusio/quarkus/issues/12515

I should be able to dedicate some time next week. Cheers!
