### ISSUE TITLE
quarkus:dev - Lift external dependency into application-classloader

### ISSUE THREAD

**Issue by 38leinaD** [quarkusio/quarkus#11962]
**Description**
External libraries might be keeping state in some statics that does not play nicely with quarkus dev-mode reloads. This is because everything external to the main maven/gradle project goes into the application base classloader that stays the same between dev-mode runs/reloads.
With the gradle plugin not supporting composite builds and also in general, it would be nice to somehow tell quarkus that certain external dependencies/libs should be lifted up into the application-classloader (which is discarded and reloaded during dev-mode runs).

cc @stuartwdouglas: I asked for this during quarkus insights

**Comment by stuartwdouglas** [comment]
I had a stab at this here: https://github.com/quarkusio/quarkus/compare/master...stuartwdouglas:11962?expand=1

Unfortunately I ran into a chicken and egg problem, where we need to know the dependency information before the config has been read/setup. I need to have a bit more of a think about how to actually configure this.
