### ISSUE TITLE
Allow configuration of JAX-RS application-class if multiple exist

### ISSUE THREAD

**Issue by 38leinaD** [quarkusio/quarkus#11966]
**Description**
Quarkus does not support multiple JAX-RS applications to be deployed (see https://github.com/quarkusio/quarkus/issues/11415). 
In situations, where a more monolithic JEE application is ported to Quarkus, it is helpful if multiple JAX-RS applications will not immediately fail the build of the Quarkus application but offer an configurable way to denote one of the rest applications to be used/deployed.
By this, JEE applications can still retain the isolation between different JAX-RS application for some time, while when deployed/migrated to Quarkus, either one JAX-RS application can be promoted to be deployed (e.g. a Quarkus-specific JAX-RS application class that is only present in the Quarkus project).
Note that this means that all rest resource classes of all applications are merged into a single application. Which should be ok, as this is the final step when migration to Quarkus anyway.

**Implementation ideas**
Offer a property in the application.properties to denote the JAX-RS application to be used/deployed.

**Comment by 38leinaD** [comment]
Thinking about it now some more. As application classes in Quarkus today do not really offer anything exception setting the @ApplicationPath, another option would be to offer a config "quarkus.resteasy.ignoreApplicationClasses=true", so the extension will fall back to the case that there is no explicit application-class at all...

Another alternative, would be a way to veto an application-class from within a custom extension, but this does not seem to be possible today because ResteasyServerCommonProcessor works on the CombinedIndexBuildItem.
Is there a reason why CombinedIndexBuildItem is is used for getting the ApplicationPath but BeanArchiveIndexBuildItem is used to get the rest resources in the same build step?

**Comment by 38leinaD** [comment]
@gsmet @kenfinnigan could you have a look at this? for a quarkus migration i need a way to control the multiple jax-rs applications we have in our JEE application. As multiple jax-rs applications seem not easily possible in quarkus (https://github.com/quarkusio/quarkus/issues/11415), this would provide an easy way to at least "merge" multiple rest applications into one without giving up the seperation when still deployed on a regular appserver for some transition period.
I.e. when setting this:
quarkus.resteasy.ignore-application-classes=true
quarkus.resteasy.path=/rest

all rest applications will be merged into a single one under /rest.

**Comment by geoand** [comment]
So basically what you are looking for here is to have a flag that will allow the Quarkus build to proceed in the presence of multiple `javax.ws.rs.Application.Application` classes, by essentially ignoring those classes altogether?

**Comment by 38leinaD** [comment]
> So basically what you are looking for here is to have a flag that will allow the Quarkus build to proceed in the presence of multiple `javax.ws.rs.Application.Application` classes, by essentially ignoring those classes altogether?

Yes, exactly. Because in quarkus the application class does not provide anything except the path; all dynamic features like the getClasses method are not used anyway. So, it would be a pragamtic option for a migrating project to just ignore the different application classes altogether so the quarkus default application is used. So, all rest applications are merged under one path.

For a migration of a JEE application we are currently doing this would be very helpful to not immediately seperate all our rest applications into seperate microservices.

AFAIK, there simply is no way today to work around this. Multiple applications will most likely not be supported, and there is also no way today to do a @Vetoed or such from our own custom quarkus extension.

**Comment by geoand** [comment]
I'm personally fine with this option.

@gsmet @kenfinnigan @FroMage WDYT?

**Comment by gsmet** [comment]
I don't have a strong opinion about this. If it helps, is properly documented and is not in the way of future developments, why not...

**Comment by kenfinnigan** [comment]
My main concern is it's a "slippery slope". What happens when other issues related to multiple `@ApplicationPath`'s arise?

I think @n1hility, @maxandersen, @gavinking need to weigh in

**Comment by gavinking** [comment]
> My main concern is it's a "slippery slope".

That's exactly right. There is zero point zero probability of this feature stopping here, and thus if you put one foot over the edge, you should expect to find yourself slipping and sliding in no time at all.

**Comment by 38leinaD** [comment]
On the one hand i totally can understand your concerns, on the other hand, supporting and checking for an application-class in the build is also a slippery slope already. The JAX-RS application-class in Quarkus does not have a purpose today beyond defining the @ApplicationPath annotation. Implementing a getClasses method on the application does nothing; so, I don't see it as such a bad idea to offer a way to veto or remove the jax-rs application classes from being used altogether.

I am also open for a more general approach to "veto" some class from the CombinedIndex for example instead of making this a reasteasy specific config property. E.g. a buildItem that allows to remove a class from the CombinedIndex.

Let me know what you think; i am happy to update the pull-request to provide some documentation as part of https://quarkus.io/guides/rest-json#whats-different-from-jakarta-ee-development or contribute to some alternative approach.

**Comment by 38leinaD** [comment]
Anyone up for suggestions/guidance if we can get this in or find an alternative approach that would solve my problem? (@geoand , @gsmet, @kenfinnigan , @gavinking , @mkouba , @gastaldi )
I have updated the PR with some additional documentation. So, at least it is well documented.
As said, an alternative approach might be to offer some way that classes from the CombinedIndex can be "vetoed". I am putting vetoed in quotes because as I understand the combined index contains any application-class and not just CDI beans (different to beanIndex). Unfortunately, the JAX-RS application-classes are read from the combined index. If there would be a way to veto some classes in it in some way (like a IgnoredIndexClassBuildItem), this would also provide some hook to solve my issue.
