### ISSUE TITLE
Time to first OK request increased (doubled) for MP application between 1.3.4.Final and 1.7.2.Final

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#12002]
We have testing application which is using all MP specs - https://github.com/quarkus-qe/quarkus-startstop/blob/master/app-full-microprofile/pom.xml. I'm using beefed up bare metal machine with Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (24 processors reported, 12 cores) and 32 GB RAM. This bare metal machine is running on RHEL 7.8.

Time to first OK request doubled for this MP application between 1.3.4.Final and 1.7.2.Final 

Times for 1.3.4.Final are ~36 ms for the first OK request.
Times for 1.7.2.Final are ~71 ms for the first OK request.

There are 2 factors that can influence this diff 
 - different GraalVM version - 19.3 vs. 20.1
 - different Quarkus version - 1.3.4.Final and 1.7.2.Final

Reproducer:
```
git clone https://github.com/quarkus-qe/quarkus-startstop.git
cd quarkus-startstop

alias setJdkGraalVM='sdk use java 20.1.0.r11-grl && export GRAALVM_HOME=$JAVA_HOME'
alias setJdkGraalVM19='sdk use java 19.3.1.r11-grl && export GRAALVM_HOME=$JAVA_HOME'

setJdkGraalVM
mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.7.2.Final
cat testsuite/target/archived-logs/io.quarkus.ts.startstop.StartStopTest/fullMicroProfileNative/measurements.csv

setJdkGraalVM19
mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.3.4.Final
cat testsuite/target/archived-logs/io.quarkus.ts.startstop.StartStopTest/fullMicroProfileNative/measurements.csv
```
You can search for `AVG timeToFirstOKRequest without min and max values` in console output to get the number without looking at measurements.csv.

Details from my bare metal machine:
```
## 1.3.4.Final
cat testsuite/target/archived-logs/io.quarkus.ts.startstop.StartStopTest/fullMicroProfileNative/measurements.csv
App , Mode , buildTimeMs , timeToFirstOKRequestMs , startedInMs , stoppedInMs , RSSKb , FDs
FULL_MICROPROFILE , NATIVE , 119838 , 41 , 37 , 4 , 93112 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 35 , 28 , 4 , 94664 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 36 , 29 , 3 , 94772 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 38 , 31 , 4 , 101112 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 36 , 30 , 3 , 97132 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 37 , 29 , 3 , 100844 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 37 , 29 , 4 , 98552 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 35 , 28 , 3 , 109104 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 36 , 30 , 3 , 94712 , 175
FULL_MICROPROFILE , NATIVE , 119838 , 35 , 28 , 3 , 94960 , 175

## 1.7.2.Final
cat testsuite/target/archived-logs/io.quarkus.ts.startstop.StartStopTest/fullMicroProfileNative/measurements.csv
App , Mode , buildTimeMs , timeToFirstOKRequestMs , startedInMs , stoppedInMs , RSSKb , FDs
FULL_MICROPROFILE , NATIVE , 121474 , 68 , 37 , 4 , 98260 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 71 , 36 , 3 , 104248 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 72 , 37 , 3 , 120580 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 69 , 36 , 4 , 110680 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 71 , 38 , 3 , 108200 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 75 , 40 , 3 , 118844 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 70 , 36 , 3 , 112772 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 72 , 37 , 3 , 112372 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 69 , 35 , 4 , 106216 , 174
FULL_MICROPROFILE , NATIVE , 121474 , 69 , 35 , 3 , 114800 , 174
```

**Comment by rsvoboda** [comment]
Just for the record, I have tried Mandrel 20.1 too.
GraalVM 20.1 and Mandrel 20.1 have same results

**Comment by gsmet** [comment]
Well, first, I would:
- try in JVM mode and see what happens
- if reproducible in JVM mode, I would use
https://github.com/quarkusio/quarkus/blob/master/TROUBLESHOOTING.md to
profile things

If not reproducible in JVM mode, then there's a good chance it's native
only and it's going to be more tricky.

**Comment by gsmet** [comment]
Also, could you either use a different CSV separator or a different decimal separator because numbers are not really readable when using commas for everything.

**Comment by rsvoboda** [comment]
Sure, I will run JVM mode and provide the data

**Comment by rsvoboda** [comment]
JVM ... 1.7.2
AVG timeToFirstOKRequest without min and max values: 1861

JVM ... 1.3.4
 AVG timeToFirstOKRequest without min and max values: 1531

**Comment by rsvoboda** [comment]
JVM ... 1.7.2
App    Mode    buildTimeMs    timeToFirstOKRequestMs    startedInMs    stoppedInMs    RSSKb    FDs
FULL_MICROPROFILE    JVM    6816    1843    1251    44    543512    349
FULL_MICROPROFILE    JVM    6816    1834    1233    44    554380    349
FULL_MICROPROFILE    JVM    6816    1874    1224    43    545664    347
FULL_MICROPROFILE    JVM    6816    1852    1251    42    555080    349
FULL_MICROPROFILE    JVM    6816    1839    1235    45    556820    347
FULL_MICROPROFILE    JVM    6816    1943    1313    39    545492    347
FULL_MICROPROFILE    JVM    6816    1840    1242    45    552924    347
FULL_MICROPROFILE    JVM    6816    1902    1295    42    548400    347
FULL_MICROPROFILE    JVM    6816    1828    1226    45    546380    347
FULL_MICROPROFILE    JVM    6816    1904    1259    42    550096    349

JVM ... 1.3.4
App    Mode    buildTimeMs    timeToFirstOKRequestMs    startedInMs    stoppedInMs    RSSKb    FDs
FULL_MICROPROFILE    JVM    6123    1550    1237    57    538992    339
FULL_MICROPROFILE    JVM    6123    1514    1178    60    536616    339
FULL_MICROPROFILE    JVM    6123    1540    1233    54    538212    339
FULL_MICROPROFILE    JVM    6123    1533    1184    59    539656    339
FULL_MICROPROFILE    JVM    6123    1512    1170    60    536612    339
FULL_MICROPROFILE    JVM    6123    1538    1198    55    536132    339
FULL_MICROPROFILE    JVM    6123    1541    1250    60    540436    339
FULL_MICROPROFILE    JVM    6123    1537    1171    59    545032    339
FULL_MICROPROFILE    JVM    6123    1534    1244    58    531392    339
FULL_MICROPROFILE    JVM    6123    1506    1184    60    533212    339

**Comment by rsvoboda** [comment]
@gsmet  / @johnaohara can Quarkus 1.7 (with some patches) run with GraalVM 19.3 ?

**Comment by rsvoboda** [comment]
Here are details from troubleshooting runs, I had to quick patch a bit quarkus-startstop project

[Archive.zip](https://github.com/quarkusio/quarkus/files/5195090/Archive.zip)
GH doesn't support attaching .svg files :/  Zip includes 
 - startup-cpu-profile-1.3.4.Final.svg
 - startup-alloc-profile-1.7.2.Final.svg
 - startup-alloc-profile-1.3.4.Final.svg
 - startup-cpu-profile-1.7.2.Final.svg

**Comment by johnaohara** [comment]
@rsvoboda looking

**Comment by johnaohara** [comment]
One significant change is that QuarkusJagerTracer is being initialized in the event loop in 1.7.2.Final, whereas in 1.3.4 this was occurring in the worker pool. The event loop is a SingleThreadEventExecutor and QuarkusJagerTracer initialization is doing a whole bunch of loading key stores, intializing SSLCiphers and loading classes.  This will add overhead to the startup of the application.

**Comment by galderz** [comment]
As already hinted, there's a lot of differences in the variables above to narrow down this: different Quarkus source, different GraalVM version, different underlying JDK version.

@rsvoboda On the Mandrel side, I'll take a loot at trying to run Quarkus 1.7.x with GraalVM 19.3.1 and report back.

**Comment by galderz** [comment]
I've done some running with [this branch](https://github.com/galderz/quarkus/tree/t_graalvm193), which sets minimum GraalVM version to 19.3.1 and I've seen [this liquibase failure](https://gist.github.com/galderz/05c07b05a368d889d432af5005d4fbf9). A somehow similar exception was reported with Kotlin, but I've not seen it before. Also, it could already be fixed in 19.3.3...

Anyway, in spite of this, a fair few tests before seemed to run fine, so it's probably worth a try to try to narrow down variables. I'll give the perf tests a go in the next couple of days and see.

**Comment by rsvoboda** [comment]
To check diff between GraalVM 19.3 and 20.1 I applied patch Galder mentioned in previous comment and executed `mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=999-SNAPSHOT` command twice for each version.

**19.3.1.r11-grl**
AVG timeToFirstOKRequest without min and max values: 64
AVG timeToFirstOKRequest without min and max values: 64

**20.1.0.r11-grl**
AVG timeToFirstOKRequest without min and max values: 71
AVG timeToFirstOKRequest without min and max values: 72

There is 10%+ difference in this measurement between 19.3 and 20.1

**Comment by rsvoboda** [comment]
mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.3.0.Final
36 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.3.4.Final
36 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.4.0.CR1
63 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.4.0.Final
65 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.4.1.Final
63 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.4.2.Final
63 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.5.0.Final
63 ms

mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.6.1.Final
62 ms

**Comment by rsvoboda** [comment]
@tqvarnst this is the perf issue if you have time to experiment with disabling MP/SRye extensions.

**Comment by geoand** [comment]
To add some data to this, I was **not** able to reproduce the problem on my setup.

```
mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.3.4.Final
77 ms
```

and

```
mvn clean test -Dtest=StartStopTest#fullMicroProfileNative -Ptestsuite -Dquarkus.version=1.4.0.CR1
78 ms
```

**Comment by rsvoboda** [comment]
Please share more details about your setup.

**Comment by johnaohara** [comment]
@geoand do you see a delta in JVM mode?

**Comment by geoand** [comment]
CPU: `AMD Ryzen 9 3950X 16-Core Processor`
RAM: 32GB
SSD: Corsair MP600
OS: Ubuntu 18.04

**Comment by geoand** [comment]
Which maven command do I run to use JVM mode?

**Comment by geoand** [comment]
@johnaohara 

```
mvn clean test -Dtest=StartStopTest#fullMicroProfileJVM -Ptestsuite -Dquarkus.version=1.3.4.Final
1010 ms
```

and

```
mvn clean test -Dtest=StartStopTest#fullMicroProfileJVM -Ptestsuite -Dquarkus.version=1.4.0.CR1
1148 ms
```

**Comment by tqvarnst** [comment]
I could somewhat reproduce the issues (approx difference was 20ms vs 30ms). However, when I modified the test and excluded opentracing and commented out the quarkus.jaeger settings I got the following results:

```sh
### GraalVM Version 19.3.3 CE
App,Mode,buildTimeMs,timeToFirstOKRequestMs,startedInMs,stoppedInMs,RSSKb,FDs
FULL_MICROPROFILE,NATIVE,197432,28,21,2,45984,56
FULL_MICROPROFILE,NATIVE,197432,16,11,2,43868,56
FULL_MICROPROFILE,NATIVE,197432,24,17,2,46072,56
FULL_MICROPROFILE,NATIVE,197432,21,15,1,43756,56
FULL_MICROPROFILE,NATIVE,197432,20,14,2,44124,56
FULL_MICROPROFILE,NATIVE,197432,16,11,2,43928,56
FULL_MICROPROFILE,NATIVE,197432,17,11,2,43776,56
FULL_MICROPROFILE,NATIVE,197432,18,12,2,45216,56
FULL_MICROPROFILE,NATIVE,197432,22,13,1,43924,56
FULL_MICROPROFILE,NATIVE,197432,23,16,2,44056,56
```
Average 20.5 ms

```sh
###  GraalVM Version 20.1.0.1.Final 287bbb343e (Mandrel Distribution) (Java Version 11.0.8)
App,Mode,buildTimeMs,timeToFirstOKRequestMs,startedInMs,stoppedInMs,RSSKb,FDs
FULL_MICROPROFILE,NATIVE,260670,27,23,2,53564,55
FULL_MICROPROFILE,NATIVE,260670,30,22,2,53632,56
FULL_MICROPROFILE,NATIVE,260670,23,14,2,51988,55
FULL_MICROPROFILE,NATIVE,260670,23,14,2,52060,55
FULL_MICROPROFILE,NATIVE,260670,27,18,2,51540,55
FULL_MICROPROFILE,NATIVE,260670,20,13,2,52952,55
FULL_MICROPROFILE,NATIVE,260670,23,15,2,52004,55
FULL_MICROPROFILE,NATIVE,260670,20,14,2,51532,55
FULL_MICROPROFILE,NATIVE,260670,19,13,2,51536,55
FULL_MICROPROFILE,NATIVE,260670,19,13,2,52156,55
```
Average 23.1 ms

That is about 10% and probably well within the standard deviation. So it makes me feel like there could be something with opentracing that has changed between the releases.

**Comment by johnaohara** [comment]
I made some modifications to https://github.com/quarkus-qe/quarkus-startstop 

- Added async profiler agent to JVM MvnCmds [1] to profile startup time to first request 
- Removed `testing web page content` tests as these requests are not included in the time to first response times

There was also an issue with the previous flamegraphs where the frame buffer's were not sufficiently sized. I have attached the flamegraphs I captured with the modified test. [2]

The flamegraphs show that differences in startup time come from;

1)  1.4.0.CR1 (and subsequent releases) is intializing `QuarkusJaegerTracer.tracer` 1.3.4.Final does not initialize `QuarkusJaegerTracer` for the startup test.  This added 87.5 - 350 ms (depending on the degree of parallelism) to JVM mode start time
2) More time is spent in C2 compiler for 1.4.0.CR1.  This added 192.25 - 769ms (again depends on degree of parallelism).  I suspect that this increase in C2 compiler time is probably related to intializing `QuarkusJaegerTracer.tracer`


In native mode, the C2 compiler will not have an impact on start time.  However, `QuarkusJaegerTracer.tracer` appears to make some potentially expensive calls loading and parsing certs and SSL ciphers. These calls probably add the overhead to the native binary startup.


1 - `-agentpath:/home/johara/Work/projects/async-profiler/build/libasyncProfiler.so=start,event=cpu,framebuf=5000000,file=/tmp/startup-cpu-profile.svg,interval=1000000,width=1600,simple`


2 - [startup-cpu-profile.zip](https://github.com/quarkusio/quarkus/files/5219992/startup-cpu-profile.zip)

**Comment by johnaohara** [comment]
Looks like @tqvarnst commented just before me :)  So, I think that Thomas's experiment confirms what I saw in the profiles I captured

**Comment by johnaohara** [comment]
What is happening post 1.4.0.CR1 is Mutiny is making a call to SmallRye Context Propagation, which is initializing Jaeger.  It looks like it is probably related to a change that @mkouba found: https://github.com/quarkusio/quarkus/commit/2ad8937c7d455b7b2e98c34c2811ac8dc4176a03#diff-a5ae6f5664db00329790d786b562e873

**Comment by stuartwdouglas** [comment]
So in JVM mode if you test with an endpoint that does use tracing (such as http://localhost:8080/data/secured/test) then you get almost identical results in JVM mode. I don't know if this would explain the native difference though, as the tracing seems to be initialized through UniCreate.<clinit> so should be run at build time.

**Comment by stuartwdouglas** [comment]
testing native http://localhost:8080/data/secured/test locally I see basically the same time to first request (51 vs 53), looks within the margin of error.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/12101 helps with the JVM tests.

**Comment by rsvoboda** [comment]
> testing native http://localhost:8080/data/secured/test locally I see basically the same time to first request (51 vs 53), looks within the margin of error.

@stuartwdouglas How many cores do you have, what's the frequency?

I'm wondering why I see such a difference and you or @geoand see much smaller diff in native.
The server I used for my runs uses https://en.wikipedia.org/wiki/List_of_Intel_Ivy_Bridge-based_Xeon_microprocessors#Xeon_E5-2695_v2

**Comment by stuartwdouglas** [comment]
This was on a Ryzen 3900X.

**Comment by geoand** [comment]
@rsvoboda can we close this? These versions are pretty old at this point

**Comment by rsvoboda** [comment]
I was checking 2.1.0.Final. It has similar timeToFirstOKRequestMs like 1.7.2.Final, the app uses less memory (rssKb). Used GraalVM 20.3 for the comparison and StartStopTest#fullMicroProfileNative test.

Also tried 2.1.0.Final StartStopTest#fullMicroProfileNative test with GraalVM 21.0.0.2 and 21.2.0, similar results as with GraalVM 20.3. Checked on my local MBP, so definitely not a performance environment.

As part of the discussion around this issue Jaeger initialization was identified as the key element in the increase.

I think we can close this issue. We will need to run the round of tests in Perf lab with Quarkus 1.11.7.Final, 2.1.0.Final and "ancient" 1.7.6.Final. @mjurc, @johnaohara fyi.
