### ISSUE TITLE
Add support for reactive client for Google Pub/Sub service

### ISSUE THREAD

**Issue by esteveavi** [quarkusio/quarkus#12021]
**Describe the extension**
It should be great if there were an extension for Google Pub/Sub service equivalent of the AWS SNS.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```projectName, topic, subscriber, auth file location.
# Add your application.properties here, if applicable.

```

**Additional context**
(Add any other context about the proposal here.)

**Comment by loicmathieu** [comment]
There is already on openned PR for this : #9745

**Comment by loicmathieu** [comment]
The PR #9745 has been closed.

Google Cloud Services extension has been moved to it's own repository (inside the Quarkiverse, Quarkus third party extensions).
See https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/1

**Comment by gastaldi** [comment]
Closing as mentioned above
