### ISSUE TITLE
Sending transfer-encoding headers over HTTP2

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#12023]
**Describe the bug**
I access quarkus over SSL, negotiating HTTP2. RESTeasy (?) adds the `transfer-encoding` header to some calls even though this goes over HTTP2 where this header is not allowed, resulting in errors in Chrome (`net::ERR_HTTP2_PROTOCOL_ERROR`) or curl (`http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [transfer-encoding], value: [chunked]`). Firefox can handle this without errors.

The code that results in response with these headers is actually quite simple:
```
@GET
@Produces(MediaType.APPLICATION_JSON)
...
return Response.ok(Change.list("variable", v)).build();
```
where `Change` extends `PanacheEntityBase`.

**Expected behavior**
The offending header should not be included when running over HTTP2.

**Environment (please complete the following information):**
 - Quarkus version or git rev: master branch

**Comment by rvansa** [comment]
CC @johnaohara

**Comment by johnaohara** [comment]
This occurs when the payload in `Response.ok()` is large enough to be chunked, smaller payloads are returned correctly

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus-http/pull/43

**Comment by rvansa** [comment]
I guess this issue can be closed, is that correct @stuartwdouglas ?
