### ISSUE TITLE
Dependency on slf4j-jboss-logging violates Apache license

### ISSUE THREAD

**Issue by dejanb** [quarkusio/quarkus#12024]
**Description**

org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final is still LGPL licensed and quarkus-core use it as a dependency. This prevents Quarkus to pass IP due diligence process (in Eclipse projects for example). 

**Implementation ideas**
Other JBoss logging modules moved to Apache license, so it seems reasonable to do it for this one as well if possible. If it is not, use some of the other backend by default.

**Comment by gastaldi** [comment]
@dejanb where do you see that information? The sources in https://github.com/jboss-logging/slf4j-jboss-logging/tree/1.2.0.Final indicate it's ASL (it's inherited from jboss-parent)

**Comment by gsmet** [comment]
https://github.com/jboss-logging/slf4j-jboss-logging/blob/1.2.0.Final/pom.xml#L8

**Comment by gastaldi** [comment]
@gsmet thanks, should've checked the sources first, I was looking at the pom.xml only :)

**Comment by jamezp** [comment]
Resolved with https://github.com/jboss-logging/slf4j-jboss-logging/pull/12
