### ISSUE TITLE
Gelf in native image takes too long time to start

### ISSUE THREAD

**Issue by wjsgzcn** [quarkusio/quarkus#12020]
**Describe the bug**
Using gelf, when build and run in NATIVE mode, my app takes about 15 second to start. Running app using -Dquarkus.debug.print-startup-times=true, and find the gelf takes very long time to "build".
```
$ target/topic-1.0.0-runner -Dquarkus.debug.print-startup-times=true
Build step NettyProcessor.eagerlyInitClass completed in: 0ms
Build step BootstrapConfigSetupBuildStep.setupBootstrapConfig completed in: 0ms
Build step HttpSecurityProcessor.initBasicAuth completed in: 0ms
Build step RuntimeConfigSetupBuildStep.setupRuntimeConfig completed in: 9ms
Build step VertxCoreProcessor.eventLoopCount completed in: 0ms
Build step GelfLogHandlerProcessor.build completed in: *14709ms*
Build step AgroalProcessor.generateDataSourceBeans completed in: 1ms
Build step VertxCoreProcessor.build completed in: 0ms
Build step VertxHttpProcessor.cors completed in: 0ms
Build step BannerProcessor.recordBanner completed in: 0ms
```

In JVM mode,  "GelfLogHandlerProcessor.build" takes only 1ms.

**Environment (please complete the following information):**
 - Output of `java -version`:  11
 - GraalVM version (if different from Java):  20.1.0
 - Quarkus version or git rev:  1.7.1

**Comment by loicmathieu** [comment]
Just tested this one on my local computer with Quarkus main and GraalVM `GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)`

In JAR mode:
```
Build step GelfLogHandlerProcessor.build completed in: 197ms
```

In native mode:
```
Build step GelfLogHandlerProcessor.build completed in: 277ms
```

It's longer on native (and ratther long overall) but not close to what you experienced.

Can you try with later Quarkus (2.0.0.CR3) and GraalVM 21.1 to see if it fixes your issue ?

**Comment by loicmathieu** [comment]
Closing it as no answer from the issuer since more than one month and it has been tested by myself with no issue.
@wjsgzcn please re-open the issue with some feedback if needed.
