### ISSUE TITLE
CI status page

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#12042]
**Description**
form @gsmet: 
"I would like to have a CI Status page with everything CI in
Quarkus (Quarkus itself, CI Ecosystem, Quickstarts, Snapshots publication and so on). I know I can get the information by having a look at several
specific places, but a simple and unified status page hosted somewhere with
proper links would be extremely helpful. I will prepare the UI and collect
the things we need to monitor in case someone wants to give it a shot on
the GH API side."

One very simple way is to just have one page of status badges for these locations - but can we get the full list of things we want tracked ? seems to be more than just github....

**Comment by geoand** [comment]
This has been implemented by @gsmet for a while now (see https://status.quarkus.io/).
