### ISSUE TITLE
Quarkus maven extension - list of available targets + details

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1204]
For Quarkus maven extension we should have document with list of available targets + details for the targets.

`mvn io.quarkus:quarkus-maven-plugin:help` gives some guidance but it's pretty limited and users need to know about that command. At this moment help command is not mentioned in the docs.

**Comment by Dufgui** [comment]
If you talk about something like this: https://www.eclipse.org/tycho/sitedocs/index.html
it's more a problem of hosting. 
And maybe css if you want something close to the official web site.

**Comment by famod** [comment]
I closed my issue #9424 since this seems more or less the same.

FTR:
> AFAIK, the only way to see all parameters of a goal, e.g. `dev`, is to look them up in the source code, e.g. https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java
> 
> Ideally, a Maven plugin should have a "site" somewhere which contains all the goals and parameters, e.g.: https://www.mojohaus.org/flatten-maven-plugin/plugin-info.html
