### ISSUE TITLE
Non-standard proxy forwarded headers are not being parsed

### ISSUE THREAD

**Issue by alsasian** [quarkusio/quarkus#12055]
**Describe the bug**

Non-standard proxy forwarded headers are not being parsed, even though both standard and non-standard forwarded headers configurations are enabled. This behavior contradicts information at https://quarkus.io/guides/vertx#running-behind-a-reverse-proxy. 

The corresponding implementation at [ForwardedParser.java](https://github.com/quarkusio/quarkus/blob/1.7.3.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java) shows that it will not parse non-standard headers when `allowForwarded` config is enabled.

**Expected behavior**

It should work as stated in the documentation 

> Both configurations related with standard and non-standard headers can be combine. In this case, the Forwarded header will have precedence in presence of both set of headers.

**Actual behavior**

With both configurations enabled, quarkus server did not parse non-standard header from request.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus:
  http:
    proxy:
      proxy-address-forwarding: true
      allow-forwarded: true
      enable-forwarded-host: true
      enable-forwarded-prefix: true
```

**Comment by sberyozkin** [comment]
@alsasian Hi, but were the standard headers available in the forwarded request ?

**Comment by ejba** [comment]
Hi @alsasian, 

I don't know if I getting the real question here but I interpret that according with the documentation, when both configurations (i.e. standard or non-standard headers) are combine, quarkus parses *only*  the Forwarded header (not both).

**Comment by ejba** [comment]
Having second thoughts about it, @alsasian is right! The documentation as it is does not follow the implementation. The idea was to describe that when both combine, *only* forwarded header is parsed (as the original implementation did before my PR). @sberyozkin It's a matter of fixing doc.

**Comment by alsasian** [comment]
@ejba thanks for the clarification. Indeed, I was expecting some kind of failover mechanism to parse custom header when standard header is not provided. I was not sure whether the issue is with the doc or the implementation.

Thanks again for checking :thumbsup:.

**Comment by ejba** [comment]
@alsasian I am the one should say thanks here! ;)
