### ISSUE TITLE
Add native test for the mailer extension

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#12069]
**Description**
Add integration tests for the mailer extension.
There are "mock" mail servers that can be used:

```java
 @Rule
 public GenericContainer<?> container = new GenericContainer<>("digiplant/fake-smtp:latest")
        .withExposedPorts(25)
        .withFileSystemBind("target", "/tmp/fakemail", BindMode.READ_WRITE);
```

**Test**

- [x] Send text email
- [x] Send HTML email
- [x] Send email with attachment
- [x] Send email from template
- [x] Send email with custom headers
- [x] Send email with multiple recipients
- [ ] Send emails with the blocking client

**Comment by geoand** [comment]
I am going to close this as looking at `quarkus-integration-test-mailer`, it seems to be done
