### ISSUE TITLE
Add an integration test section to the getting started testing doc

### ISSUE THREAD

**Issue by kottmann** [quarkusio/quarkus#12093]
Quarkus has support for integration testing, but it takes a bit of time until there is a working test case by googling the required information. Being able to follow an example in the getting started guide would have made this easier for me doing it the first time.

I would like to propose to add an integration testing section to this documentation file:
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/getting-started-testing.adoc

**Comment by loicmathieu** [comment]
There is now a section about QuarkusIntegrationTest, see https://quarkus.io/guides/getting-started-testing#quarkus-integration-test.

Can we close this issue ?

**Comment by kottmann** [comment]
Yes.
