### ISSUE TITLE
No suitable driver found for Postgresql with TestContainers since Quarkus 1.8

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#12116]
**Describe the bug**

I have a TestContainers test that pings a Postgres DB. This test does not actually use Quarkus but I realized that it was working in 1.7.3 and failing in 1.8.

It is not a stopper for me (as I said, I realized I should have taken the `@QuarkusTest` annotation) but it sounds that something has been introduced that it makes this test fail (this test has been working since Quarkus 1.6 at least).

**Expected behavior**

The test should pass as in 1.7.3

**Actual behavior**

The test fail with:

```
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:32831/vintageStoreDB?loggerLevel=OFF
        at org.acme.PingPostgreSQLTest.shouldPingPostgreSQL(PingPostgreSQLTest.java:32)
```

**To Reproduce**

Generate a brand new Quarkus 1.7.3-Final  app with the Postgres extension. Then, add the TestContainers dependency:

```
  <properties>
   ...
    <testcontainers.version>1.14.3</testcontainers.version>
  </properties>

    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
```

Now create a new Test

```
@QuarkusTest
@Testcontainers
public class PingPostgreSQLTest {

  @Container
  public static PostgreSQLContainer pg = new PostgreSQLContainer<>("postgres:12.4")
    .withDatabaseName("vintageStoreDB")
    .withUsername("vintage")
    .withPassword("vintage")
    .withExposedPorts(5432);

  @Test
  public void shouldPingPostgreSQL() throws Exception {
    pg.start();

    try (Connection con = DriverManager.getConnection(pg.getJdbcUrl(), pg.getUsername(), pg.getPassword());
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("SELECT VERSION()")) {

      if (rs.next()) {
        assertTrue(rs.getString(1).contains("PostgreSQL 12"));
      } else {
        throw new Exception();
      }
    }

    pg.stop();
  }
}
```

This test just uses TestContainers to ping a Postgres db. It doesn't use any Quarkus. In fact, if you leave the `@QuarkusTest` annotation it also works. Then, move to Quarkus 1.8.0, it fails.

**Configuration**

The test with 1.7.3 works even without any `application.properties` file declaring a Postgres driver or JDBC URL. 
Because it is now failing with 1.8 I tried to add `quarkus.datasource.db-kind=postgresql` and so on.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin iMac-Pro-de-Antonio.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "11.0.6" 2020-01-14 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.0-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3_1

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
@gsmet does this ring a bell?

**Comment by gsmet** [comment]
No. It doesn't. Given there's nothing Quarkus in it, I don't think it's related to any of my changes.

@agoncal please provide a reproducer. Going through steps is cumbersome and generates unnecessary noise. Thanks.

**Comment by geoand** [comment]
Yeah, the reproducer also makes it trivial to actually debug and compare between the 2 versions

**Comment by agoncal** [comment]
Here it is : https://github.com/agoncal/agoncal-bug-quarkus-testcontainers

It is the exact same code. The only thing that changes is the Quarkus version. If you run a `mvn test` on the root, the Postgres test of Quarkus 1.7.3 succeeds, while the 1.8 fails.

**Comment by gsmet** [comment]
I can reproduce the issue. I wonder if it could be a CL issue as I don't see how other changes could be related to that considering how level this is.

@stuartwdouglas does it ring a bell?

**Comment by stuartwdouglas** [comment]
This will work if you call DriverManager.getDrivers() before the getConnection call. Weirdly it will also work if you try and call getConnection a second time. 

The root cause of this is the DriverRemover, which calls getDriver and initializes it with a ClassLoader that is being closed.

**Comment by agoncal** [comment]
Hum... I've tried to invoke `DriverManager.getDrivers()` before getting the connection, but it does not work.

**Comment by agoncal** [comment]
Just tested with Quarkus 1.8.2 and its ok now.
