### ISSUE TITLE
Test log cluttered with "Connection to node -1 ... could not be established. Broker may not be available."

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#12120]
**Description**
Test logs are full of warnings like this:

```
WARN: [AdminClient clientId=...-8cd9c56a-1348-4528-87a8-265035d94965-admin] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
WARN: [Producer clientId=...-8cd9c56a-1348-4528-87a8-265035d94965-StreamThread-1-producer] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

I have tests which only use TopologyTestDriver, so there is no need to instantiate Kafka. Furthermore I cannot "unset" kafka-streams.bootstrap-servers.

Is there any way to get rid of those messages?

I've seen I could use [KafkaTestResource](https://github.com/quarkusio/quarkus/blob/master/integration-tests/kafka/src/test/java/io/quarkus/it/kafka/KafkaTestResource.java#L12), but I think it would be better to have a way to prevent it completely.

Thanks,
Antonio

**Comment by rquinio** [comment]
Indeed KStreams TopologyTestDriver tests (whitebox testing without creating any Kafka connections) are run via `@QuarkusTest` today (ex: [TopologyProducerTest](https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-streams-quickstart/aggregator/src/test/java/org/acme/kafka/streams/aggregator/streams/TopologyProducerTest.java#L34-L38) ) which starts the application (including TCP connections, thread pools, ...) and rather more suitable for blackbox testing. 

I don't know if it would be possible to have a lesser version of `@QuarkusTest` that only does the initialization (dependency injection, config injection, ...), but does not start the app (i.e. never calls StartupEvent / `@Startup` producers) ?

**Comment by antoniomacri** [comment]
In my tests I'm actually using beans which `@Observes StartupEvent`, so I'd need something different.

**Comment by cescoffier** [comment]
This issue is rather outdated. It has been fixed in SmallRye Reactive Messaging.

**Comment by rquinio** [comment]
I think this may have been closed by mistake, as it's quarkus-kstream extension question/issue.

Anyway I've found a solution for this: simply inject a mock of KafkaStreams - a class that extends KafkaStreams and overrides start() to do nothing. The bean being singleton scope, it has to be done via QuarkusTestProfile CDI alternatives.

I'll do a PR to demonstrate that via https://github.com/quarkusio/quarkus-quickstarts/blob/main/kafka-streams-quickstart/aggregator/src/test/java/org/acme/kafka/streams/aggregator/streams/TopologyProducerTest.java

**Comment by pantaoran** [comment]
@cescoffier How has this been fixed? I'm using the latest version of Quarkus with the `quarkus-kafka-streams` dependency, and my logs are still full of these warnings when I'm running unit tests with the `TopologyTestDriver`. Do I need to configure something to make those go away?

**Comment by ngc4579** [comment]
Any progress / further hints on this?

**Comment by antoniomacri** [comment]
I stil see those logs on Quarkus 3.13.0...

@cescoffier Could it be reopened?

**Comment by cescoffier** [comment]
@antoniomacri can you open a new issue with a reproducer?

**Comment by cescoffier** [comment]
(BTW, this was fixed for the reactive messaging connector, not kafka streams - not sure you can do anything in kafka streams without modifying kafka streams itself).
