### ISSUE TITLE
JAXP extension

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#12129]
**Describe the extension**

The current JAXB extension contains some JAXP stuff:

* https://github.com/quarkusio/quarkus/blob/1.8.0.Final/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L196-L199
* https://github.com/quarkusio/quarkus/blob/1.8.0.Final/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L205-L206
* https://github.com/quarkusio/quarkus/blob/1.8.0.Final/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L210-L214

It would be handy to have separate JAXP-only extension

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**

None

**Additional context**

https://github.com/apache/camel-quarkus/issues/1796

**Comment by ppalaga** [comment]
I can prepare a PR if there is a general agreement that this is a good idea?

**Comment by gsmet** [comment]
@ppalaga I think it makes sense, we already discussed that a few times. So go with it!

**Comment by geoand** [comment]
I like the idea
