### ISSUE TITLE
Allow the use of podman for creating a container-image

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#12135]
**Description**
Currently we have `container-image-jib` and `container-image-docker` for building container images and pushing them to a registry (`container-image-s2i` is openshift specific).

It would be nice to provide a similar experience for `podman` (it can currently be used if the user aliases `docker` to `podman` and used the `container-image-docker` extension).

**Implementation ideas**
The basic question is, do we provide another extension (which would basically do exactly what the docker extension does), or just provide a config switch in `DockerConfig`?

**Comment by maxandersen** [comment]
i would start with a config switch that allow to change the name of the binary used to execute/call and see if it works. podman should in this usecase work as pure standin.

**Comment by geoand** [comment]
Yeah, that's what I'm thinking as well.

**Comment by gastaldi** [comment]
You can install `podman-docker` that makes `docker` as an alias to `podman`: 

```
sudo dnf install podman-docker
```

**Comment by maxandersen** [comment]
yes that would nice way to test it @gastaldi but wont work on all platforms and what if you want to have both installed ;)

**Comment by gastaldi** [comment]
Podman doesn't install in Windows, if that's what you mean :)

Unless you run as a remote client, but I am not sure if that's the case here: https://www.redhat.com/sysadmin/podman-clients-macos-windows

**Comment by maxandersen** [comment]
It would be. Also Crc going to set it up for both Mac and win.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/12157 is first step towards this
