### ISSUE TITLE
Consider converting the transaction guide and Hibernate ORM guide into quickstart guide

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1216]
Hey @gsmet @Sanne , the data guides are the few one not to follow the quistart approach with the quickstart code to clone. If you guys have nothing to do :)
This is not a first-public-release mandatory

**Comment by loicmathieu** [comment]
Hi @emmanuelbernard I stumble upon this old issue about quickstart and guides, the Hibernate ORM guide has a quickstat, I oppened #18035 to add it to the guide.
Reading the transaction guide, I don't think adding a quickstart will add any value, the `Transactional` annotation is present on the Hibernate guide and maintaining a guide with only transaction seem not worth it.

Do you still think a quickstart is worth adding for the transaction guide or can we close this one ?

**Comment by emmanuelbernard** [comment]
Thanks for the ping Loic, let's close this one.
