### ISSUE TITLE
Test and document ConfigMap property overriding via SmallRye Config

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1217]

**Comment by kenfinnigan** [comment]
Or maybe implement a new `ConfigSource` -> https://github.com/smallrye/smallrye-config/issues/145

**Comment by radcortez** [comment]
This is now documented in SmallRye Config via an example:
https://github.com/smallrye/smallrye-config/tree/master/examples/configmap

It can also be done for Quarkus if required. The config related code should not be different.
