### ISSUE TITLE
DevMojoIT hangs for a long time and eventually fails during build

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#1219]
Test `testThatTheApplicationIsReloadedOnKotlinChange` seems to get stuck in "await" for a long time and eventually fails.

Apparently this is only happening on my machine ?  However it's very consistent here. Couldn't investigate more yet, so tracking as issue.

**Comment by darranl** [comment]
Looking into this failure for myself the timeout was caused by a slow download from Maven, the workaround that worked for me was execute the following before the build to pre-populate my local repository.

mvn dependency:get -Dartifact=org.jetbrains.kotlin:kotlin-compiler:1.3.21

**Comment by Sanne** [comment]
Thanks @darranl , I'll change the timeouts. Feeling a bit dirty though :)
