### ISSUE TITLE
No way to use vertx-stomp

### ISSUE THREAD

**Issue by AlexKovynev** [quarkusio/quarkus#12212]
**Describe the bug**

I need to find a way to use existing http server but can't. Maybe it's not a bug, can be question or some. Do i have any opportunity?
       
        var stompServer = StompServer
                .create(vertx,
                        new io.vertx.ext.stomp.StompServerOptions().setSecured(false).setPort(-1)
                                .setWebsocketBridge(true).setWebsocketPath("/stomp"))
                .handler(StompServerHandler.create(vertx));

        vertx.createHttpServer(
                new HttpServerOptions().setWebSocketSubProtocols(Arrays.asList("v10.stomp, v11.stomp, v12.stomp")))
                .webSocketHandler(stompServer.webSocketHandler()).listen(8080, ar -> {
                    if (ar.failed()) {
                        logger.info("Failing to start the STOMP server : " + ar.cause().getMessage());
                    } else {
                        logger.info("Ready to receive STOMP frames");
                    }
                });

**Comment by cescoffier** [comment]
Vert.x Stomp is not supported yet. It would need a specific extension.

**Comment by sabinaisayeva** [comment]
Hi. The same issue here. Is it supported already? Or still not? Is there any way to find stomp client for quarkus?

**Comment by cescoffier** [comment]
There is no real integration , but it should work with the plain vertx code.

**Comment by sabinaisayeva** [comment]
Thanks. I am testing now and getting no host exist. However I checked with postman and it found the host. Maybe I am missing something..

**Comment by cescoffier** [comment]
How are you starting the Stomp server? 
Are you using the web socket bridge, is so how?

**Comment by cescoffier** [comment]
The following code works:

```java
public GreetingResource(Vertx vertx) {
        client = StompClient.create(vertx, new StompClientOptions().setPort(PORT));
        client.connect()
                .chain(c -> {
                    return c.subscribe("/q", frame -> {
                        last = frame.getBodyAsString();
                    });
                })
                .subscribe().with(s -> System.out.println("subscribed!"), Throwable::printStackTrace);

        client.connect()
                .onItem().transformToMulti(c -> {
                    return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
                            .onItem().transformToUniAndConcatenate(l -> c.send("/q", Buffer.buffer("hello-" + l)));
                })
                .subscribe().with(x -> {
                    // Noop
                }, Throwable::printStackTrace);
    }
```

It uses:

```xml
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-stomp</artifactId>
    </dependency>
```

**Comment by cescoffier** [comment]
@mkouba, I have a question for you: Do you think we could integrate the Stomp server with WebSocket Next?
It would require sub-protocols, but that's not what concerns me. I'm more concerned because it seems the WebSocketHandler from the Stomp server wants to be the only handler. (I'm pretty sure I wrote that code, like nine years ago...)

**Comment by mkouba** [comment]
> I have a question for you: Do you think we could integrate the Stomp server with WebSocket Next?

Do we really want some integration or just make it possible to live side by side?

> I'm more concerned because it seems the WebSocketHandler from the Stomp server wants to be the only handler.

@cescoffier Hm, this could be indeed a problem. The WS handler set by `HttpServer.webSocketHandler(Handler<ServerWebSocket>)` takes precedence over the HTTP request handler that calls `HttpServerRequest#toWebSocket()` which is used by WS Next. I wasn't quite sure but I did a quick test and it's really the case.

Also the Stomp WS handler rejects a connection on an invalid path (configured with `StompServerWebSocketConnectionImpl#setWebsocketPath()`).

However, I think that we could register a route for `StompServerOptions#getWebsocketPath()` and use the `Handler<ServerWebSocket>` produced by `StompServer#webSocketHandler()` inside the route, after upgrade, something like:

```java
public void init(@Observes Router router) {
    Handler<ServerWebSocket> h = stompServer.webSocketHandler();
    router.get(stompOptions.getWebsocketPath()).handler(rc -> {
       Future<ServerWebSocket> future = rc.request().toWebSocket();
       future.onSuccess(h);
    });
}
```

This way a Stomp server can live side by side with WS Next.

**Comment by cescoffier** [comment]
That's cool!

Let's close this issue,  the last comment explains the way forward.
