### ISSUE TITLE
RestClientProcessor does not handle classes/interfaces generated during build

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#12216]
**Describe the bug**
Rest Client extension does not generate rest clients for interfaces/classes that are produced during build by another extension 

**Expected behavior**
Classes/interfaces generated during build should be found by 'RestClientProcessor'

**Actual behavior**
Missing rest client implementation

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin  19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
 - Quarkus version or git rev: 1.17 and 1.18
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): maven-3.6.3

**Additional context**
It is a matter of using BeanArchiveIndex instead of CombinedIndexBuildItem, see PR https://github.com/quarkusio/quarkus/pull/12215

**Comment by kenfinnigan** [comment]
As PR was merged I think this is resolved
