### ISSUE TITLE
Conform to changes to RESTEasy 4.5.7.Final

### ISSUE THREAD

**Issue by ronsigal** [quarkusio/quarkus#12210]
**Description**

Changes to

  *  org.jboss.resteasy.plugins.providers.sse.client.SseEventSourceImpl (resteasy-core)
  *  org.jboss.resteasy.links.ClassLinksProvider (resteasy-links)
  *  org.jboss.resteasy.links.ObjectLinksProvider (resteasy-links)

entail small changes to

  *  io.quarkus.resteasy.mutiny.common.runtime.MultiRxInvokerImpl (quarkus-resteasy-mutiny-common)
  *  io.quarkus.rest.data.panache.runtime.resource.ResourceLinksProvider (quarkus-rest-data-panache)

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkusio/quarkus/commit/9c742302558f15582ae12958adb91ad4565c093d
