### ISSUE TITLE
reactive routes don't work in abstract classes

### ISSUE THREAD

**Issue by fiorenzino** [quarkusio/quarkus#12222]
**Description**
Using an abstract class with some methods annotated with @Route, they will ignored on the scanning of the implementor classes.

Example code
abstract class
`public abstract class RsRepositoryService<T> {

    @Route(methods = GET, path = "/:id")
    public Uni<T> fetch(@Param Optional<String> id) {
       ....
    }

    @Route(methods = GET, path = "/")
    public Uni<List<T>> getList(
            @Param("startRow") Optional<String> startRow,
            @Param("pageSize") Optional<String> pageSize,
            @Param("orderBy") Optional<String> orderBy,
            RoutingExchange routingExchange) {
       ....
        return list;
    }

     public abstract void applyRestictions(StringBuffer sb, MultiMap multiMap, Map<String, Object> parameters);

    @Route(path = "/*", type = FAILURE)
    public void error(RoutingContext context) {
       ....
    }

}`
implementor class
`@RouteBase(path = ACTIONS_PATH, produces = APPLICATION_JSON)
public class ActionServiceRs extends RsRepositoryService<Action> {

    @Override
    public void applyRestictions(StringBuffer sb, MultiMap multiMap, Map<String, Object> parameters) {

    }
}`

Asking on the forum, the answer is: 
This is not supported ATM:
https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/VertxWebProcessor.java#L154

It's not supported by design because inheritance rules usually bring
additional complexity we orginally wanted to avoid.

**Comment by geoand** [comment]
I am going to close this as `won't fix` since we are putting all our effort into RESTEasy Reactive when it comes to our HTTP stack
