### ISSUE TITLE
Field annotated with @TestHTTPResource is not properly set if running in native mode with random http port

### ISSUE THREAD

**Issue by tisoft** [quarkusio/quarkus#12237]
**Describe the bug**
`@TestHTTPResource` is not properly set if running in native mode with random http port

**Expected behavior**
Field annotated with `@TestHTTPResource` should contain the resoved port

**Actual behavior**
Field annotated with `@TestHTTPResource` contains port 0, which is the random port

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
https://github.com/tisoft/code-with-quarkus-issue-11891

1. sdk use java 20.2.0.r11-grl
2. ./mvnw clean verify -Pnative

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.test-port=0

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux linux-ytxx.suse 5.3.18-lp152.41-default #1 SMP Thu Sep 3 23:02:59 UTC 2020 (a4d139b) x86_64 x86_64 x86_64 GNU/Linu
 - Output of `java -version`: openjdk version "11.0.8" 2020-07-14
 - GraalVM version (if different from Java): 20.2.0
 - Quarkus version or git rev: OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
Releated to: https://github.com/quarkusio/quarkus/issues/11891#issuecomment-690318536

**Comment by tisoft** [comment]
I could work around this in my project by not using a `@TestHTTPResource` annotated field, but grab the port out of `RestAssured.port`, which is correctly set to the captured port.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19002 fixes the issue. We'll try to get it in `2.1.1.Final`

**Comment by geoand** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/19002
