### ISSUE TITLE
Can't use an environment variable as the value for quarkus.vault.authentication.app-role.secret-id option

### ISSUE THREAD

**Issue by vaughnmb** [quarkusio/quarkus#12243]
**Describe the bug**
Can't use an environment variable as the value for quarkus.vault.authentication.app-role.secret-id option in the application.properties file.  It works as expected if I paste the actual value into the application.properties file for the quarkus.vault.authentication.app-role.secret-id option.

**Expected behavior**
Environment Variable to be resolved and to be used as the value set for the quarkus.vault.authentication.app-role.secret-id option

**Actual behavior**
Looks like the environment variable is not resolved.  Here is the error I get

io.quarkus.vault.runtime.client.VaultClientException code=400 body={"errors":["invalid secret id"]}

**To Reproduce**

Set up a project using vault approle authentication.  Try to use an environment variable as the value for the quarkus.vault.authentication.app-role.secret-id  option

https://quarkus.io/guides/vault-auth#approle-authentication

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.vault.url=http://localhost:8200
quarkus.vault.kv-secret-engine-version=1
quarkus.vault.kv-secret-engine-mount-path=secret
quarkus.vault.authentication.app-role.role-id=a01bb784-940b-475b-8a47-3e5446322f9a
quarkus.vault.authentication.app-role.secret-id=${SECRET_ID}

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
Maven properties:

    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus-plugin.version>1.8.1.Final</quarkus-plugin.version>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>1.8.1.Final</quarkus.platform.version>
        <surefire-plugin.version>2.22.1</surefire-plugin.version>
    </properties>

**Comment by vaughnmb** [comment]
Same result occurs if I pass in the value of ${SECRET_ID} as a system property.  Same error.

**Comment by sberyozkin** [comment]
CC @vsevel

**Comment by danielalejandrin** [comment]
> 
> 
> **Describe the bug**
> Can't use an environment variable as the value for quarkus.vault.authentication.app-role.secret-id option in the application.properties file. It works as expected if I paste the actual value into the application.properties file for the quarkus.vault.authentication.app-role.secret-id option.
> 
> **Expected behavior**
> Environment Variable to be resolved and to be used as the value set for the quarkus.vault.authentication.app-role.secret-id option
> 
> **Actual behavior**
> Looks like the environment variable is not resolved. Here is the error I get
> 
> io.quarkus.vault.runtime.client.VaultClientException code=400 body={"errors":["invalid secret id"]}
> 
> **To Reproduce**
> 
> Set up a project using vault approle authentication. Try to use an environment variable as the value for the quarkus.vault.authentication.app-role.secret-id option
> 
> https://quarkus.io/guides/vault-auth#approle-authentication
> 
> **Configuration**
> 
> ```ini
> # Add your application.properties here, if applicable.
> quarkus.vault.url=http://localhost:8200
> quarkus.vault.kv-secret-engine-version=1
> quarkus.vault.kv-secret-engine-mount-path=secret
> quarkus.vault.authentication.app-role.role-id=a01bb784-940b-475b-8a47-3e5446322f9a
> quarkus.vault.authentication.app-role.secret-id=${SECRET_ID}
> ```
> 
> **Screenshots**
> (If applicable, add screenshots to help explain your problem.)
> 
> **Environment (please complete the following information):**
> Maven properties:
> 
> ```
> <properties>
>     <compiler-plugin.version>3.8.1</compiler-plugin.version>
>     <maven.compiler.parameters>true</maven.compiler.parameters>
>     <maven.compiler.source>11</maven.compiler.source>
>     <maven.compiler.target>11</maven.compiler.target>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
>     <quarkus-plugin.version>1.8.1.Final</quarkus-plugin.version>
>     <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
>     <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
>     <quarkus.platform.version>1.8.1.Final</quarkus.platform.version>
>     <surefire-plugin.version>2.22.1</surefire-plugin.version>
> </properties>
> ```

I have the same issue but only in the vault url property, it throws a _java.net.MalformedURLException: no protocol: ${VAULT_URL:https://localhost:8243}_. So I have to override it with the environment variable QUARKUS_VAULT_URL.
I'm using quarkus **1.9.2.Final**

```
quarkus.vault.url=${VAULT_URL:https://localhost:8243} ->before 
%dev.quarkus.vault.url=https://localhost:8243 ->after
quarkus.vault.tls.skip-verify=${VAULT_TLS_SKIP_VERIFY:false}
quarkus.vault.authentication.app-role.role-id=${VAULT_ROLE_ID}
quarkus.vault.authentication.app-role.secret-id=${VAULT_SECRET_ID}
```

**Comment by sberyozkin** [comment]
Hi Vincent @vsevel  - can you please check if this issue has now been resolved ?
