### ISSUE TITLE
Integration with frontend frameworks and libraries

### ISSUE THREAD

**Issue by mifabricadigital** [quarkusio/quarkus#12248]
**Description**
When starting the quarkus application we should be able to integrate with an frontend library or framework as react, angular, vue and svelte. When using the maven extention for npm we have problems when using the router because by default resteasy looks for it on the back and not on the front

**Implementation ideas**
A new maven npm dependency to integrate the backend and frontend project without this problem, it could also have an aditional path like /api to identify back from front

**Comment by geoand** [comment]
I am going to close this as we now have https://quarkus.io/blog/quinoa-modern-ui-with-no-hassle/.

You can follow up with requests for improvement on that front in https://github.com/quarkiverse/quarkus-quinoa
