### ISSUE TITLE
Quarkus logging with compress option

### ISSUE THREAD

**Issue by mcrose** [quarkusio/quarkus#12260]
**Description**
add support to compress logs like [logback](http://logback.qos.ch/) is in [SLF4J](https://www.slf4j.org/)
and/or add documentation example for correct configuration

**Comment by MrJustreborn** [comment]
Is there any update to this?

**Comment by dmlloyd** [comment]
This should already be possible by setting the file suffix on the log rotation configuration something that ends with `.gz` (`quarkus.logging.file.rotation.suffix=.yyyy-MM-dd.gz` for example).

**Comment by geoand** [comment]
@sag1 does the workaround mentioned by @dmlloyd not satisfy your needs? If not, what is missing?

**Comment by sag1** [comment]
I have a doubt whether it does really compression or just adding suffix. I will try it

**Comment by geoand** [comment]
Your doubts are unfounded :)

**Comment by sag1** [comment]
I confirm that compression works !
