### ISSUE TITLE
compilation error when injecting restclient in viewscoped bean using myfaces-quarkus extension

### ISSUE THREAD

**Issue by aosama** [quarkusio/quarkus#12275]
the below code examples generates a compilation error for unsatisfied CDI dependency.
 
import org.eclipse.microprofile.rest.client.inject.RestClient;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;
@Named
@ViewScoped
public class SomeClass implements Serializable {
private static final long serialVersionUID = 2174143885608958202L;
@Inject
@RestClient
SomeRestClient someRestClient;
public String saySomething()
{ 
String result = someRestClient.dowork();
 return "blablalba " + result;
 }
}
gives the below compilation error
 
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.demo.restservices.SomeRestClient and qualifiers [@Default] - java member: com.example.SomeClass#someRestClient - declared on CLASS bean [types=[java.io.Serializable, java.lang.Object, com.example.SomeClass], qualifiers=[@Named, @Default, @Any], target=com.example.SomeClass] at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:990) at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:234) at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:122) at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:391) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932) at io.quarkus.builder.BuildContext.run(BuildContext.java:277) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452) at java.base/java.lang.Thread.run(Thread.java:834) at org.jboss.threads.JBossThread.run(JBossThread.java:479)Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.demo.restservices.someClient and qualifiers [@Default] - java member: com.example.SomeClass#someTblTranslationRestClient - declared on CLASS bean [types=[java.io.Serializable, java.lang.Object, com.example.SomeClass], qualifiers=[@Named, @Default, @Any], target=com.example.SomeClass] at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:494) at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362) at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:226) ... 14 more

**Comment by aosama** [comment]
@tandraschko Hi Thomas, first thanks for your efforts to make JSF available in quarkus, hope you can look at the above, it is as simple as injecting a microprofile restclient in a viewscoped beans and then the above error happens during compile. let me know how can i help in that regards? thanks again

**Comment by tandraschko** [comment]
I dont know the internals that good, so someone from the quarkus guys should Check it.
Nevertheless i would provide a small reproducer application.

**Comment by aosama** [comment]
pom was missing 
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
