### ISSUE TITLE
OIDC Session Cookie does not allow configuration of Domain

### ISSUE THREAD

**Issue by funcbro** [quarkusio/quarkus#12281]
**Describe the bug**
We have several Quarkus-Services and several Angular Applications, deployed separately but within the same sub-domain:
e.g.
- Quarkus-Service A URL: https://whatever.wherever.company.net/
- Quarkus-Service B URL: https://another.address.company.net/
- Angular-App URL: https://something.else.company.net

The Quarkus-Services use Code-Authentication-Flow (quarkus.oidc.application-type=web-app)
We use a custom redirect endpoint which is called by the Angular-App to redirect back to the UI after authentication is done.

The generated Session Cookie is placed e.g. in Domain "whatever.wherever.company.net", though is not usable from the other services/apps. 

**Expected behavior**
Similar to the Cookie-Path (quarkus.oidc.authentication.cookie-path), also the Cookie-Domain should be configurable, to make the Cookie valid for e.g "company.net"

**Actual behavior**
The generated Session and Auth Cookies have no configured Domain and are though set with the Host-name in the Browser-Cache.

**Configuration**
```properties
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.xhr-auto-redirect=false
quarkus.oidc.authentication.force-redirect-https-scheme=true
quarkus.oidc.authentication.redirect-path=/auth/callback
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.authentication.remove-redirect-parameters=true
quarkus.oidc.authentication.cookie-path=/
```

**Screenshots**
See https://github.com/quarkusio/quarkus/blob/cb32eeff4a489cc340b01dbb5941df357e76fb07/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L409
-> I would expect the possibility for domain configuration here

**Environment (please complete the following information):**
- Output of uname -a or ver:
- Output of java -version:
  openjdk version "11.0.7" 2020-04-14
  OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
  OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
- GraalVM version (if different from Java):
- Quarkus version or git rev: 1.8.1
- Build tool (ie. output of mvnw --version or gradlew --version): 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@funcbro thanks, I used some of your problem description (non existing uris in the docs :-))

**Comment by funcbro** [comment]
@sberyozkin , it's me to say thanks! I really appreciate this rapid feedback and fixing =)
