### ISSUE TITLE
Upgrade to Debezium 1.2.5.Final

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#12315]
@gsmet, @geoand, we've applied Guillaume's fix in Debezium's outbox extension and released this as 1.2.5.Final. I.e. you can upgrade to that version and should be able to re-enable the test disabled via https://github.com/quarkusio/quarkus-platform/pull/126.

**Comment by gunnarmorling** [comment]
For reference, the code change in Debezium is here: https://github.com/debezium/debezium/pull/1821.

**Comment by geoand** [comment]
See: https://github.com/quarkusio/quarkus-platform/pull/127
