### ISSUE TITLE
"quarkus.container-image.*" entries not showing in the "All Configuration Options" guide.

### ISSUE THREAD

**Issue by someth2say** [quarkusio/quarkus#12316]
**Describe the bug**
When looking for "container-image" entries in the "All Configuration Options guide", the only entries that appear are some "quarkus.knative" and "quarkus.openshift" entries, as they default to "quarkus.container-image" values.
No entry for "quarkus.container-image" is shown.

**Expected behavior**
Include the "quarkus.container-image" entries like in https://quarkus.io/guides/container-image#container-image-options

**Actual behavior**
Expected entries not show.

**To Reproduce**
1. Go to "https://quarkus.io/guides/all-config" and wait for the complete page to load.
2. Type "container-image" in the search box.
3. 

**Configuration**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/13310156/94130463-fb9c6b00-fe5c-11ea-8095-51c9e5e710fa.png)

**Environment (please complete the following information):**
N/A

**Additional context**
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.22quarkus.2Econtainer-image.2E*.22.20not.20in.20the.20all-configs.20guide

**Comment by geoand** [comment]
@machi1990 any idea why this is?

**Comment by machi1990** [comment]
> @machi1990 any idea why this is happening?

Hi @geoand, I've not checked into details but I suspect that it could be same issue as https://github.com/quarkusio/quarkus/issues/5214

**Comment by geoand** [comment]
That's weird :)

If you have to look into this, it would be great. Otherwise, I'll add it to my queue :)

**Comment by machi1990** [comment]
> That's weird :)
> 
> If you have to look into this, it would be great. Otherwise, I'll add it to my queue :)

A quick fix I can think of is to add an empty `container-image` runtime module to make the `container-image-deployment`  recognizable as an extension. The empty module could contain the extension.yml file with the `unlisted:true` metadata for it to not be published.

**Comment by machi1990** [comment]
> > That's weird :)
> > If you have to look into this, it would be great. Otherwise, I'll add it to my queue :)
> 
> A quick fix I can think of is to add an empty `container-image` runtime module to make the `container-image-deployment` recognizable as an extension. The empty module could contain the extension.yml file with the `unlisted:true` metadata for it to not be published.

@geoand I can open a draft PR for you to have a quick look. WDYT?

**Comment by geoand** [comment]
That would be great, thanks!
