### ISSUE TITLE
quarkus:add-extension should report multiple extensions match

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1232]
quarkus:add-extension should report multiple extensions match, now it picks any extension that matches name or GAV.

```
mvn quarkus:add-extension -Dextensions="SmallRye"
...
Adding extension io.quarkus:quarkus-smallrye-fault-tolerance-deployment
...
```

https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/java/io/quarkus/cli/commands/AddExtensions.java#L44

**Comment by Dufgui** [comment]
I do a MR but i remove name resolution. Not sur it’s a Good idea

**Comment by Dufgui** [comment]
I think we can clone this one, since PR #2385
@gsmet

**Comment by Dufgui** [comment]
Please close it
@FroMage

**Comment by FroMage** [comment]
Well, that's more a question for @rsvoboda no?

**Comment by rsvoboda** [comment]
Now I get error saying: ❌ Multiple extensions matching 'SmallRye'
