### ISSUE TITLE
Remove unnecessary code in RestClientRecorder wrt ResteasyProviderFactory

### ISSUE THREAD

**Issue by ronsigal** [quarkusio/quarkus#12325]
As of https://issues.redhat.com/browse/RESTEASY-2684 "Set providerFactory on ResteasyClientBuilderImpl", the code in io.quarkus.restclient.runtime.RestClientRecorder which configures ResteasyProviderFactory.instance is no longer necessary.

**Comment by kenfinnigan** [comment]
Here's the PR: https://github.com/quarkusio/quarkus/pull/12326
