### ISSUE TITLE
Provides an easy way to set the test profile

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#12339]
**Description**
Currently, tests using `@QuarkusTest` uses by default the `test` profile.
When you want to use a different profile for different tests, you need to pass the profile as a JVM options in the command line or by creating a class that implements `QuarkusTestProfile` and override the `getTestProfile` method.

This is not very convenient and have one big caveat: the profile is not visible from the test class, this can leads to easy to chase bugs when you think that your case use a profile and it's not the case.

**Implementation ideas**
There is already multiples test annotations provided by Quarkus, we can add a `profile` attribute to one of them:
- `@QuarkusTest(profile="testcontainers")`
- `@QuarkusTestProfile(profile="testcontainers")`

We need to disallow setting both the profile in this way and via a profile class, or documenting a clear rule (annotation parameter takes precedence over test profile class).

**Comment by geoand** [comment]
Relevant zulip discussion is at: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Setting.20the.20test.20profile

**Comment by radcortez** [comment]
We now have many ways to set the config for tests:
https://quarkus.io/blog/overriding-configuration-from-test-code/

I think we don't need additional ways to do it.
