### ISSUE TITLE
Issue when using xmlrpc

### ISSUE THREAD

**Issue by thomas-mc-work** [quarkusio/quarkus#12350]
**Describe the bug**

I'm using XMLRPC via the dependency `org.apache.xmlrpc:xmlrpc-client:3.1.3`. This was wokring perfectly fine outside of Quarkus so far. But with quarkus I'm ending with this exception when invoking the client:

    java.lang.NoClassDefFoundError: Could not initialize class org.apache.xmlrpc.util.SAXParsers

**Expected behavior**

Should just work out of the box.

**To Reproduce**

It's a bit hard to provide since you need a server and a client implementation.

Or attach an archive containing the reproducer to the issue.

1. Create a client using the `org.apache.xmlrpc.client.XmlRpcClient`
2. Invoke a client request

**Configuration**

Nothing relevant.

**Environment (please complete the following information):**

```
$ uname -a
Linux desktop 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

 - GraalVM version (if different from Java): Not yet used
 - Quarkus version or git rev: `1.8.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

**Comment by thomas-mc-work** [comment]
I've created a reproducer now:

    https://github.com/thomas-mc-work/xmlrpc-demo

It has a single REST endpoint:

    curl http://localhost:8080/demo

**Comment by thomas-mc-work** [comment]
Maybe an `mvn dependency:tree` would be helpful to get an idea of the root problem. But unfortunately I'm not able myself to read something useful out of the result. Couldn't someone of the @quarkusio/quarkus please have a look at it?

**Comment by gastaldi** [comment]
Your xmlrpc-client dependency should exclude xml-apis. See https://stackoverflow.com/questions/17360000/provider-for-javax-xml-parsers-documentbuilderfactory-cannot-be-found/32766405

```xml
        <dependency>
            <groupId>org.apache.xmlrpc</groupId>
            <artifactId>xmlrpc-client</artifactId>
            <version>3.1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by thomas-mc-work** [comment]
Funny, I found exactly the same answer! I just didn't find the time to answer here. Thank you anyways. @gastaldi !

**Comment by samkeeleyong** [comment]
@gastaldi , just stumbled upon this thread and it fixed my issue. Can you explain why `xml-apis` need to be excluded? I'm wondering there are any side effects

**Comment by gastaldi** [comment]
@samkeeleyong `xml-apis` conflicts with the JRE’s rt.jar’s `javax.xml` stuff
