### ISSUE TITLE
@ConfigProperty with default value and ignoreIfNotPresent

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#12379]
I have a class that will execute initialization code that is not required for junit 

In my class I used

@ConfigProperty(name = "autostart-codec-disabled")
boolean autoStartDisable;

by default the value is "false"

but I want to know if I could just declare the variable only for junit ("test profile)

%test.autostart-codec-disabled=true

if the property is not present in application.properties, it could use the default value ?

like

@ConfigProperty(name = "autostart-codec-disabled", defaultvalue="false")
boolean autoStartDisable;

or

@ConfigProperty(name = "autostart-codec-disabled", ignoreIfNotPresent="true")
boolean autoStartDisable;

The goal is to avoid putting too much properties in application.properties in the default profile if only needed in a specific profile

Should I open a issue/feature request ?

**Comment by survivant** [comment]
I tried this (without the property in application.properties)


@ConfigProperty(name = "autostart-codec-disabled", defaultValue = "true")
Boolean autoStartDisable;


and autoStartDisable is always false

but this works
@ConfigProperty(name = "autostart-codec-disabled")
Optional<Boolean> autoStartDisable;

**Comment by famod** [comment]
I would have suggested `Optional<Boolean>` but maybe @radcortez has a better suggestion.

**Comment by dmlloyd** [comment]
Do you mean that it is putting the value in the generated default configuration, and you don't want it there?

**Comment by radcortez** [comment]
> I would have suggested `Optional<Boolean>` but maybe @radcortez has a better suggestion.

That was my suggestion on the mailing list :)

> I tried this (without the property in application.properties)
> 
> @ConfigProperty(name = "autostart-codec-disabled", defaultValue = "true")
> Boolean autoStartDisable;
> 
> and autoStartDisable is always false
> 
> but this works
> @ConfigProperty(name = "autostart-codec-disabled")
> Optional autoStartDisable;

This one is weird. I don't see a reason why the first option wouldn't work. I've just tried it out and I get a `true`, unless I'm missing something.

**Comment by survivant** [comment]
I think, we can close this issue.  I did some cleanup and rebuild everything and the default value works now and Optional works too.

**Comment by radcortez** [comment]
Great! Thank you :)
