### ISSUE TITLE
Customize logging in quarkus

### ISSUE THREAD

**Issue by RajatKumar-git** [quarkusio/quarkus#12388]
Description:
In terms of json logging the i have to add some custom fields in the console logs( like logback.xml provide in springboot) , and need to remove some of them from the logs like hostname ,processId and loggerClassName.
I have used extension quarkus-logging-json which gives json format logging now but i am unable to remove those fields from the console and add my custom fields there.
Suggest some ideas or enhancement with which we can add some new fields to the console logging

Thanks in advance..

**Comment by SlyngDK** [comment]
You can take a look at this https://github.com/quarkiverse/quarkiverse-logging-json, just released today.

It support using both jsonb and jackson, I also working on support to configure each field.

**Comment by geoand** [comment]
Closing per the previous comment
