### ISSUE TITLE
Jackson annotations RestEasy client

### ISSUE THREAD

**Issue by kiwiidb** [quarkusio/quarkus#12380]
**Describe the bug**
When using Jackson annotations for request bodies, the annotations do not seem to be picked up. 
```
package org.acme.rest.client;

import com.fasterxml.jackson.annotation.*;
public class TestRequest {

    @JsonProperty("test_prop")
    public String testProp;
}
```
-> This serializes to "testProp" instead of "test_prop"
**Expected behavior**
Jackson annotations are taken into account when serializing.

**To Reproduce**
I have made a modification to the REST-client quickstart project which reproduces my issue:

https://github.com/kiwiidb/quarkus-quickstarts/commit/da1965d4c41c2d10db3a4a22ecbfcb923752fd4e

I listen with a simple mock server on localhost and log the requests as they come in.
Or attach an archive containing the reproducer to the issue.

1.  mvnw quarkus:dev
2. set-up mock server at localhost:8080 or use another way to intercept the request before it gets send.
3. curl localhost:8081/country/name-uni/something

**Comment by stachera** [comment]
I had a similar problem using the annotation @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class).

After I trying to simulate this behaviour with previous versions like 1.8.0.Final and 1.7.4.Final and the problem still happen, I've starting to see another configurations in pom.xml, when I saw that my project was configured with _quarkus-resteasy-jsonb_ lib, but without _quarkus-resteasy-jackson_ lib. So, I decided to remove _quarkus-resteasy-jsonb_ and added _quarkus-resteasy-jackson_. 

And after that, my code works as expected o/

**Comment by kiwiidb** [comment]
To be clear my issue is with the REST _client_. Quarkus-resteasy-jackson is for the server serialization if I understand correctly.

**Comment by kiwiidb** [comment]
Sorry, the reproducing code works when you remove the `resteasy-jsonb` dependency. Closing this

**Comment by gsmet** [comment]
Yeah, both the clients and the servers use RESTEasy. If one of them brings the JSON-B provider, it takes the precedence.

You need to use a consistent stack for both.
