### ISSUE TITLE
Exception Handling/Mapping When Running Quarkus Command Mode Applications

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#12397]
**Description**
Currently, command mode applications are unable to handle exceptions when executing the application but only provide a `Consumer<Integer>` to perform custom logic based on the exit code.

Applications should be able to catch any exception thrown during startup/execution in order to customize behavior or just shown better messages.

**Implementation ideas**
If we could change the [Quarkus.run](https://github.com/quarkusio/quarkus/blob/f98e0393664788f56169d055d585335f845ab8dd/core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java#L52) method to accept a `BiConsumer` instead of a `Consumer`, applications could handle both exit code (as used today) as well as the exception that occurred.

I'm not sure about this line on [Quarkus.run](https://github.com/quarkusio/quarkus/blob/f98e0393664788f56169d055d585335f845ab8dd/core/runtime/src/main/java/io/quarkus/runtime/Quarkus.java#L67) which seems to indicate that exception mappers are expected to allow the proposed behavior. However, that catch block does not seem to be executed considering that the application exits at [ApplicationLifecycleManager.run](https://github.com/quarkusio/quarkus/blob/b95f4e494b26e9ae632fa8d927999dfff26b2d7b/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L152).

**Comment by stuartwdouglas** [comment]
Originally I was thinking that this would be something like RESTEasy exception mappers, where you could create something like:

`class MyMapper implements StartExceptionMapper<SomeException>` and Quarkus would automatically discovery them.

That said maybe the BiConsumer approach is simpler and more flexible.

**Comment by pedroigor** [comment]
@stuartwdouglas Thanks, I'm going to prepare a PR.
