### ISSUE TITLE
Make it easier to load additional config properties files at build time

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#12419]
**Description**
We have (generated) additional config properties files that we would like to load like `application.properties`. It would be really nice o be able to load them without having to define a `ConfigSource` and doing the SPI registration, etc.

See discussion at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Additional.20config.20properties.20at.20build.20time

**Implementation ideas**
I guess some options are:

- Something similar to Spring's `@PropertySource`
- Define which additional files to load in a property in `application.properties`

**Comment by radcortez** [comment]
Just to clarify, this is for runtime, not build time, right? We need to be careful at build time since the resources may not be available at runtime, since the class path may be different.

**Comment by xtaixe** [comment]
@radcortez build time would work for our current use case, but runtime should be fine too. Not sure how resources work with Quarkus/GraalVM, but would be nice to not have to define additional parameters when building/running if the resource is already defined somewhere.

**Comment by radcortez** [comment]
Ok, I may have some ideas. I'll have to prototype and experiment with them first. I'll update later.
