### ISSUE TITLE
review and enable registry mechanism

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#12422]

**Comment by aloubyansky** [comment]
Here is my proposal https://groups.google.com/g/quarkus-dev/c/xI9N_4dMrsk

**Comment by aloubyansky** [comment]
The live doc is https://docs.google.com/document/d/1dZufN0EZ_jW-An_P09WpdvLzk6GJtCZ_OamzSCi2q88/edit#heading=h.ljvqoc686804
