### ISSUE TITLE
Create a blog post explaining how Quarkiverse works

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#12433]

**Comment by maxandersen** [comment]
i didn't manage to get this in place before my pto - put some of it in https://github.com/quarkiverse/quarkiverse/pull/5 but missing the pictures/context I wanted to add about what is the full quarkus universe, platforms and quarkus core and then link that to their "home" 3rd party, quarkiverse, "participting" quarkus repos (i.e. platform/camel/kogito) and quarkus core.

Feel free to make that happen before my return - for now i've unassigned me this one.

**Comment by gastaldi** [comment]
Created in https://quarkus.io/blog/quarkiverse/
