### ISSUE TITLE
Allow to disable redirections from Form Based Authentication

### ISSUE THREAD

**Issue by rolintoucour** [quarkusio/quarkus#12457]
**Description**
Using form based authentication, there are 3 pages urls that we can define:
- quarkus.http.auth.form.login-page
- quarkus.http.auth.form.error-page
- quarkus.http.auth.form.landing-page

We can also disable the redirection to landing page: `quarkus.http.auth.form.redirect-after-login`. In this case the landing page isn't used anymore (as far as I know), after a successfull login the user simply receives a 200 with the cookie.

As I use the authentication for a SPA (angular), I don't need redirection but return codes: login is fine but for error management  I have to check the redirection urls...

**Implementation ideas**
It would be more consistent if we could disable the redirect for other pages: after a disconnection or a login failure, receive the appropriate error code.

We could add 2 properties like:
- quarkus.http.auth.form.redirect-after-login-failure
- quarkus.http.auth.form.redirect-after-login-expired

Or we could replace the existing redirect property with a more general one:
- quarkus.http.auth.form.redirect

* Note *
Please also note that when  a secured endpoint is requested with an outdated cookie, then we are redirected to the login url. In this request there is a cookie `quarkus-redirect-location` in order to repeat the initial request. This cookie isn't documented at all and it cannot be customized (I don't need it but FYI).

**Comment by MartinX3** [comment]
I can confirm that.
I use a VueJS-Frontend and quakus can't simply acces the pages via GET, because the vue-router returns a 404.

**Comment by itatdcer** [comment]
Agree. What's worst, from my point of view, is that a call to a jaxrs endpoint that accepts and produces a JSON (for instances, get's redirected to the login page (returning HTML). Jaxrs should return a 401, right? Otherwise, how can a client work?

**Comment by itatdcer** [comment]
It turns out to be quite simple to "override" the default behavior. Based on FormAuthenticationMechanism and HttpAuthenticationMechanism code, I created the following custom Auth Mecanism:
`@Alternative
@Priority(1)
@ApplicationScoped
public class CustomAuthMechanism implements HttpAuthenticationMechanism {

    @Inject
    FormAuthenticationMechanism delegate;
    
    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        return delegate.authenticate(context, identityProviderManager);
    }

    @Override
    public Uni<ChallengeData> getChallenge(RoutingContext context) {
        Uni<ChallengeData> rValue = delegate.getChallenge(context);
        
        return rValue.onItem().transform(challendgeData -> {
            if(challendgeData.status == 302) {
                return new ChallengeData(401, null, null);
            }
            
            return challendgeData;
        });
        
    }

    @Override
    public Set<Class<? extends AuthenticationRequest>> getCredentialTypes() {
        return delegate.getCredentialTypes();
    }

    @Override
    public HttpCredentialTransport getCredentialTransport() {
        return delegate.getCredentialTransport();
    }

    @Override
    public Uni<Boolean> sendChallenge(RoutingContext context) {
        return getChallenge(context).map(new ChallengeSender(context));
    }
    
}`

Now, the redirect vs Unauthorized could easily be controlled by a configuration property...

**Comment by iriikoad** [comment]
In Quarkus 2.11.3, I see in FormAuthenticationMechanism, method 'authenticate';
```
context.put(HttpAuthenticationMechanism.class.getName(), this);
```
And this line is forcing the use of FormAuthenticationMechanism instance, not the custom one. So it is not using our method 'getChallenge'.

I fixed this with:
```
    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        return delegate.authenticate(context, identityProviderManager).onFailure().invoke(() -> {
            // make sure it use our instance in case of error login
            context.put(HttpAuthenticationMechanism.class.getName(), this);
        });
    }
```

**Comment by iriikoad** [comment]
Note: you may have to fix this also as 'getCredentialTransport()' is deprecated:
``` java
    @Override
    public Uni<HttpCredentialTransport> getCredentialTransport(RoutingContext context) {
        return delegate.getCredentialTransport(context);
    }
```
