### ISSUE TITLE
kafka very noisy in dev mode (master)

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#12454]
**Describe the bug**
This is a follow-on from #12435 

While debugging that, I unzipped and ran the reproducer, and that was lovely. Immediate error, woohoo!

**Expected behavior**

Kafka starts up (maybe a few messages as things warm up). If I leave dev mode, Kafka cleans itself up.

**Actual behavior**

Constant chatter (WARN) from org.apache.kafka.client.NetworkClient on both a kafka-admin-client-thread and a kafka-producer-network-thread. When I exit dev mode, activity and messages continue. If I wait long enough, it eventually stops, but it it is longer than a slow count to 30: 

2020-10-01 11:26:19,419 INFO  [io.quarkus] (Shutdown thread) code-with-quarkus stopped in 55.839s

gradle dev mode is ironically better behaved than maven devmode, but not by much.

**To Reproduce**

Reproducer (w/ both maven and gradle, adjusted for 999-SNAPSHOT): 
https://drive.google.com/file/d/1dypJM5RbYDBcjRKujOZjjoLhwVuzVd9i/view?usp=sharing

**Comment by cescoffier** [comment]
I fixed it upstream (in reactive messaging) already. 
I'm going to update the version in Quarkus Today.
