### ISSUE TITLE
Only JAR dependencies are copied to the target/lib directory

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#12472]
**Describe the bug**
When building an application with `mvn package` only JAR dependencies are copied to the `target/lib` directory.

If we have other kind of libraries (for example native libraries that are `.so` or `.dll`), these will not be copied.

Maybe we can relax the "only jar" check to "jar and native libraries".
Or maybe we can add some logging to it.

**Additional context**
Some background this has been discussed on Zulip and the limitation to JAR file was because of some limitation with native image build: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20didn't.20add.20native.20libraries.20to.20the.20target.2Flib.20dir

**Comment by geoand** [comment]
Is this still an issue?

**Comment by loicmathieu** [comment]
Let's close it, it's very old and nobody else seems to be annoyed by that so even if it's still true it's not a big deal.

**Comment by geoand** [comment]
🙏🏽
