### ISSUE TITLE
Setting quarkus.http.cors.origins in application.yml

### ISSUE THREAD

**Issue by rinmalavi** [quarkusio/quarkus#12480]
When setting properties

    quarkus:
      http:
        cors: true
        "cors.origins": '*'

I would expect "quarkus.http.cors.origins" to be set to "*"

However

    WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http."cors.origins"" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo

1.  set in `application.yaml` (use `quarkus-config-yaml`)

    quarkus:
      http:
        cors: true
        "cors.origins": '*'

2.  watch for output in application logs

quarkus:1.8.1

you can however set `quarkus.http.cors.origins` in yml.

**Comment by sberyozkin** [comment]
@rinmalavi should it be just `origins` ?

**Comment by rinmalavi** [comment]
Well it works with `quarkus.http.cors.origins` in .yml as well as .properties
Not sure i undrestood "just `origins`"?
https://quarkus.io/guides/http-reference#cors-filter

**Comment by sberyozkin** [comment]
@rinmalavi Oh I see what is the probllem, `.cors` is overloaded (used to enable and also acts as a segment key)

May be we should have `quarkus.http.cors.enabled=true`...

**Comment by gastaldi** [comment]
You need to do: 

```yaml
quarkus:
  http:
    cors:
      ~: true
```

See https://quarkus.io/guides/config#configuration-key-conflicts for more details.

Closing now

**Comment by sberyozkin** [comment]
@gastaldi super :-)

**Comment by micheljung** [comment]
If this was documented, it's not anymore

**Comment by gastaldi** [comment]
Looks like it was moved to https://quarkus.io/guides/config-reference#configuration-key-conflicts

**Comment by sylvainpolletvillard** [comment]
Moved again to https://quarkus.io/guides/config-yaml#configuration-key-conflicts

**Comment by tsprlng** [comment]
This is quite a frustrating "solution" as for almost all applications that accept YAML, you can generate JSON as a strict subset to avoid most of YAML's nightmarish complexity. However, `null` as a key is not allowed in JSON (only strings), making Quarkus a quite difficult special case.
