### ISSUE TITLE
Pick a profile config properties automatically in @TestProfile

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#12507]
I updated myself to the latest Quarkus 1.8.1.Final, obviously the testing feature is improved.

I have tried to use `@TestProfile` to test my Repository against an embedded H2 database instead of the default Postgres database.

Now my working example is like this.

* Java 11
* Windows 10 64bit
* only test on jvm

The profile class is simple, try to create an H2 data source here.

```java
public class H2Profile implements QuarkusTestProfile {
    @Override
    public Map<String, String> getConfigOverrides() {
        return Map.of(
                "quarkus.datasource.url", "jdbc:h2:tcp://localhost/mem:test",
                "quarkus.datasource.driver", "org.h2.Driver",
                "quarkus.hibernate-orm.database.generation", "drop-and-create",
                "quarkus.hibernate-orm.log.sql", "true"
        );
    }

    @Override
    public String getConfigProfile() {
        return "h2";
    }
}
```
And the test class.

```java
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource.class)
@TestProfile(H2Profile.class)
public class PostRepositoryTest {

    private final static Logger LOGGER = Logger.getLogger(PostRepositoryTest.class.getName());

    @Inject
    private PostRepository posts;

    @Test
    public void testPersistence() {
        this.posts.listAll().forEach(p -> System.out.println("Post:" + p));
        Assertions.assertTrue(this.posts.findAll().list().size() == 2, "result list size is 2");
    }

}
```

I would like to use an *application.properties* file to override the config at runtime when running a test. I hope there are some improvements.

1. The `H2Profile` has a unique config profile name(**h2**), by convention,  the test will scan the classpath if there is an *application-h2.properties* for this profile.
2. In the `@TestProfile` add a configFile attribute to accept a custom properties file located in the classpath. eg. "propertiesFile= test-datasources.properties".

**Comment by radcortez** [comment]
I guess we could try to load a profile based file in `getConfigOverrides` default implementation. 

There are some other issues related with profile aware files that may be related with this as well.
