### ISSUE TITLE
Create Extension mojo should allow creating the project structure from the current working directory

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#12500]
**Description**
The mojo creates a directory named after the provided `artifactId` to place the generated files. It would be nice if the generated files were placed directly in the directory where it was executed.

**Implementation ideas**
Add a flag to skip the generation of the directory based on the `artifactId`

**Comment by aloubyansky** [comment]
This is actually consistent with `create-project`

**Comment by geoandri** [comment]
Hi @gastaldi ,

I have opened an MR for this. Who should I ping for a review?

**Comment by gastaldi** [comment]
@geoandri thank you very much! I added a few people that recently used that command.

**Comment by geoandri** [comment]
Many thanks @gastaldi .
