### ISSUE TITLE
QuarkusTest and RegisterExtension create multiple instances with inconsistent state during test

### ISSUE THREAD

**Issue by hacst** [quarkusio/quarkus#12511]
**Describe the bug**
I'm seeing some unexpected behavior with Junit 5 extensions in QuarkusTest. The extension is registered with a static field on the class annotated with QuarkusTest.
```java
@QuarkusTest
public class MyTest {
    public static class MyExt implements BeforeAllCallback, AfterAllCallback { // Inner class for conciseness. Makes no difference to have it separate
       String state = "unchanged";
       ...
       @Override
       public void beforeAll(ExtensionContext extensionContext) throws Exception {
            ...
            state = "initialized";
       }
    }
    ...
    @RegisterExtension
    static final MyExt myext = new MyExt();

    @Test
    void test() {
        ...
        assertEquals(myext.state, "initialized");
    }
}
```
It has a before all callback that sets an internal value on the extension class instance. When executing the test I see the extension class being constructed twice (even though the field is static). Then one of the instances has the before all callback called. In the actual Test method however the other instance which never had its callback called is available. It looks like some class load shenanigans are involved to get two instantiations of the static.

**Expected behavior**
The RegisterExtension annotation should correctly initialize the object the test methods are executing on. Ideally the static class should only construct once.

**Actual behavior**
The annotated static object is initialized in a class loader different from the one tests methods are executed with. This leaves the object available in the test uninitialized.

**To Reproduce**
See https://pastebin.com/yQs5hAr5 for a full example with debug output.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.8.1.Final

**Comment by hacst** [comment]
Forgot to mention that separate `@BeforeAll` and `@AfterAll` annotations actually execute in the expected context. My current workaround is use those to manually call the extension `beforeAll` and `afterAll` methods. That's not a generic solution though as usually these functions require an `ExtensionContext` not available with this workaround.

**Comment by famod** [comment]
Well, this is a known but also documented limitation:
https://quarkus.io/guides/getting-started-testing#enrichment-via-quarkustestcallback
Especially:
> While it is possible to use JUnit Jupiter callback interfaces like BeforeEachCallback, you might run into classloading issues because Quarkus has to run tests in a custom classloader which JUnit is not aware of.

See also: #10623

PS: Please beware that there is no real "BeforeAll" Quarkus variant, yet. See also: #12544

So, I think we'll have to close this issue. But thanks for reporting it!

/cc @geoand

**Comment by geoand** [comment]
> 
> PS: Please beware that there is no real "BeforeAll" Quarkus callback, yet. See also: #12544
> 

There will be with https://github.com/quarkusio/quarkus/pull/12549 :)

> So, I think we'll have to close this issue. But thanks for reporting it!
> 

Indeed I agree

**Comment by geoand** [comment]
Thanks for reporting this!

I closed it because @famod's analysis is spot on
