### ISSUE TITLE
Test Slice like feature with @QuarkusTest

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#12512]
The `@InjectMock` is great to isolate the dependencies when testing a Quarkus component.

The following is [a working example](https://github.com/hantsy/quarkus-sample/blob/master/post-service/src/test/java/com/example/PostResourceTest.java) from my Github.

```java
@QuarkusTest
public class PostResourceTest {

    @InjectMock
    PostRepository postRepository;

    @Test
    public void getNoneExistedPost_shouldReturn404() {
        when(this.postRepository.findByIdOptional(anyString()))
                .thenReturn(Optional.ofNullable(null));
        given()
                .when().get("/posts/"+ UUID.randomUUID().toString())
                .then()
                .statusCode(404);

        verify(this.postRepository, times(1)).findByIdOptional(anyString());
        verifyNoMoreInteractions(this.postRepository);
    }

    @Test
    public void getExistedPost_shouldReturn200() {
        var data = Post.builder().title("Hello Quarkus").content("My first post of Quarkus")
                .createdAt(LocalDateTime.now())
                .id(UUID.randomUUID().toString())
                .build();
        when(this.postRepository.findByIdOptional(anyString()))
                .thenReturn(Optional.ofNullable(data));
        given()
                .when().get("/posts/test")
                .then()
                .statusCode(200)
                .log().all()
                .body("title", is("Hello Quarkus"));

        verify(this.postRepository, times(1)).findByIdOptional(anyString());
        verifyNoMoreInteractions(this.postRepository);
    }

    @Test
    public void testPostsEndpoint() {
        var data = Post.builder().title("Hello Quarkus").content("My first post of Quarkus")
                .createdAt(LocalDateTime.now())
                .id(UUID.randomUUID().toString())
                .build();
        when(this.postRepository.findByKeyword(anyString(), isA(int.class), isA(int.class)))
                .thenReturn(
                        List.of(data)
                );
        given()
                .when().get("/posts?q=")
                .then()
                .statusCode(200)
                .log().all()
                .body(
                        "size()", is(1),
                        "[0].title", is("Hello Quarkus")
                );

        verify(this.postRepository, times(1)).findByKeyword(anyString(), isA(int.class), isA(int.class));
        verifyNoMoreInteractions(this.postRepository);
    }

}
```

But when I run this test, it will assemble all dependent CDI beans of this application in the background, if I do not run a Postgres server in my case, it will fail.

If possible to introduce a test `slice` feature like Spring Boot(eg. `DataJpaTest`, `RestClientTest`, `WebMvcTest`, `WebFluxTest`, etc ) to load essential CDI beans for the purpose of running the tests. 

And Spring `@ComponentScan`, Spring Boot `XXXAutoConfigurer` has its own options to filter components,  eg.  `excludeFilters` , hope there is an equivalent mechanism in Quarkus, and work seamlessly with  `@QuarkusTest`.

**Comment by geoand** [comment]
We don't plan on introducing test slices like in Spring Boot, but for the use case you mention with the missing database, Quarkus 1.13 will automatically start a database for you using testcontainers if none has been configured.

**Comment by vipseixas** [comment]
> We don't plan on introducing test slices like in Spring Boot, but for the use case you mention with the missing database, Quarkus 1.13 will automatically start a database for you using testcontainers if none has been configured.

@geoand Any chance of changing this plan? 

Starting containers to keep unused features from failing (and bootstrapping the features themselves) seems sub-optimal. 

As an example, I have a service that uses PGSQL, RabbitMQ and MinIO so I have to start 3 server containers just to test business classes that don't use them.

**Comment by geoand** [comment]
> > We don't plan on introducing test slices like in Spring Boot, but for the use case you mention with the missing database, Quarkus 1.13 will automatically start a database for you using testcontainers if none has been configured.
> 
> @geoand Any chance of changing this plan?
> 

It's rather unlikely at this point

> Starting containers to keep unused features from failing (and bootstrapping the features themselves) seems sub-optimal.
> 
> As an example, I have a service that uses PGSQL, RabbitMQ and MinIO so I have to start 3 server containers just to test business classes that don't use them.

I understand the use case, but the complexity this would entail on the Quarkus side just doesn't seem warranted IMHO

**Comment by hantsy** [comment]
@geoand I would like to provide an approach like Weld Junit 5(also provide simple mocking and alternative beans replacement by programmatic approach) and Arquillian, let developers decide the beans be packaged into the deployment unit for testing purposes. I saw some facilities in the Quarkus source codes, but the tools are not available for developers? not seeing them in the Guides.

If possible to category the beans for deployment unit into a TestProifle?

**Comment by geoand** [comment]
> @geoand I wish that Quarkus provides an approach like Weld Junit 5(also provide simple mocking and alternative beans replacement by programmatic approach) and Arquillian, let developers decide the beans be packaged into the deployment unit for testing purposes. I saw some facilities in the Quarkus source codes, but the tools are not available for developers? not seeing them in the Guides.
> 

That's essentially what `@QuarkusUnitTest` does (and it is used extensively by extesion authors) but we don't see it as something user facing, which is why you won't find it in the guides.

> If possible to category the beans for deployment unit into a TestProifle?

I don't see how that would work
