### ISSUE TITLE
No longer possible to have Qualifiers on default EntityManager

### ISSUE THREAD

**Issue by jw941** [quarkusio/quarkus#12569]
We used a resource producer field to add a Qualifier to our default EntityManager that we configure using persistence.xml:

```@Produces```
@PersistenceContext
```@Unsecured```
EntityManager entityManager;

We do this so we can wrap the entity manager to enforce entity level permissions (the wrapped EntityManager has no Qualifiers).

This worked up until the support for multiple persistence units, now it seems like when you use persistence.xml the default EntityManager bean is always created. This code
here https://github.com/quarkusio/quarkus/blob/026b1a1935/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmCdiProcessor.java#L112 seems
to be the culprit. 

Would it be possible to add an option to use the PU name in persistence.xml even if there is only a single persistence unit defined?

**Comment by mkouba** [comment]
CC @gsmet

**Comment by gsmet** [comment]
@jw941 any chance you could prepare a simple Maven project showing what doesn't work anymore exactly.

It could help me to compare the previous behavior with the one we have now.

**Comment by gsmet** [comment]
IIRC, I added this because the new stuff broke a test that was working before.

**Comment by jw941** [comment]
Hi @gsmet 

I just made an example.
https://github.com/jw941/bug12569/blob/main/src/main/java/org/acme/commandmode/EmProducer.java

It doesn't need to be work exactly the same but better to have a way to allow a qualifier to the default entity manager.

Thanks for your help!

**Comment by gsmet** [comment]
@jw941 is there a good reason why you're using a `persistence.xml`? Pondering my options :).

**Comment by jw941** [comment]
> @jw941 is there a good reason why you're using a `persistence.xml`? Pondering my options :).

Because of another issue https://github.com/quarkusio/quarkus/issues/12412

**Comment by gsmet** [comment]
Could you try something like:

```
@Inject
private EntityManager entityManager;

@Produces
@PersistenceContext
@UnWrapped
EntityManager unwrapped() {
    return entityManager;
}

@Produces
@AlternativePriority(100)
EntityManager delegate(@UnWrapped EntityManager entityManager) {
    return new WrappedEntityManager(entityManager);
}
```

**Comment by mkouba** [comment]
Just to explain a bit:
```java
@Produces
@AlternativePriority(100) // -> this one makes your producer an alternative which takes precedence during the type-safe resolution, i.e. when an injection point of type EntityManager (and @Default or none qualifier) is being injected this producer method is called
EntityManager delegate(@UnWrapped EntityManager entityManager) {
    return new WrappedEntityManager(entityManager);
}
```

**Comment by jw941** [comment]
I tried but it didn't work.

**Comment by gsmet** [comment]
"didn't work" meaning?
