### ISSUE TITLE
Version is hardcoded in a lot of source files

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1257]
We should really not be doing this.  It complicates the release, at the least.  If a run time piece needs the version, it should pull it from a resource that is substituted at build by Maven.

**Comment by stuartwdouglas** [comment]
Is this still an issue?

**Comment by gsmet** [comment]
I don't think so, otherwise the release process fails.

The few versions we have are replaced during the release process (we have some in the Amazon Lambda archetypes typically).
