### ISSUE TITLE
Error handling does not work with blocking event bus consumers

### ISSUE THREAD

**Issue by tsegismont** [quarkusio/quarkus#12599]
**Describe the bug**
Error handling does not work with blocking event bus consumers: `@ConsumeEvent(blocking=true)`

**Expected behavior**
If the consumer body throws an exception, the sender should get a `ReplyException`.

**Actual behavior**
The exception thrown by the consumer is reported to the uncaught exception handler.

**To Reproduce**

In `MessageConsumerFailureTest`, set all `@ConsumeEvent` annotations `blocking` attribute to `true` and run the test.
The test will fail.

**Comment by cescoffier** [comment]
Thanks @tsegismont, I will have a look.
