### ISSUE TITLE
NoProxy settings for quarkus RestClient

### ISSUE THREAD

**Issue by bonocore** [quarkusio/quarkus#12658]
**Description**
Hello, as per 

https://github.com/quarkusio/quarkus/issues/6522

It is possible to set http proxy settings into RestClient.

However, it seems that the underlying RestEasy config does not allow to configure a "no-proxy" list of host, for which proxy should not be used. This is a very useful feature for some enterprise setup

**Implementation ideas**
It whould be great to have a configuration in application properties similar to the one provided by DynamoDB client:

org.acme.rest.client.CountriesService/mp-rest/proxy.enabled=true
org.acme.rest.client.CountriesService/mp-rest/proxy.endpoint=myproxy:1234
org.acme.rest.client.CountriesService/mp-rest/proxy.username=myuser
org.acme.rest.client.CountriesService/mp-rest/proxy.password=mypass
org.acme.rest.client.CountriesService/mp-rest/proxy.non-proxy-hosts=myinternalhost1, myinternalhost2

**Comment by bonocore** [comment]
Added related issue on RestEasy: https://issues.redhat.com/browse/RESTEASY-2729

**Comment by gsmet** [comment]
I'm closing this one as it's really a RESTEasy issue, we can't do anything about it in Quarkus.

**Comment by shibinkai** [comment]
@bonocore 

via analysis redhat RestEasy source code,multi non-proxy hosts config need  '|' split ,this solution is ok for me, for example

org.acme.rest.client.CountriesService/mp-rest/proxy.non-proxy-hosts=myinternalhost1|myinternalhost2
