### ISSUE TITLE
Unable to add a channel config property from an environement variable inside smallrye reactive messaging Kafka

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#12678]
**Describe the bug**
When using smallrye reactive messaging Kafka and channels on multiple broker, the configuration of the broker must be done on each channel and not on the global `kafka.*` configuration properties.

In typical developement process, you use a local broker on dev and an SSL secured broker on production, in this case you will only have the needed configuration properties on your `application.properties` and add the extra ones (the one for SSL configuration) using env variable.

This didn't work for per channel configuration. A workaround to add them with fake value inside `application.properties` works so the issue is that when using per channel configuration, you cannot **add** config property via env variable but only **overrides** the one that exist inside `application.properties`.

Background discussion here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Kafka.20config.20issue

**To Reproduce**

Example application.properties:

```
# Configure the Kafka sink / consumer
mp.messaging.incoming.kafka-in.connector=smallrye-kafka
mp.messaging.incoming.kafka-in.topic=in-topic
mp.messaging.incoming.kafka-in.bootstrap.servers=localhost:9092
# Configure the Kafka source / producer
mp.messaging.outgoing.kafka-out.connector=smallrye-kafka
mp.messaging.outgoing.kafka-out.topic=out-topic
mp.messaging.outgoing.kafka-out.bootstrap.servers=localhost:9092
```

Example k8s secret with env varibale not declared inside aplication.properties:

```
kubectl create secret generic my-config \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_BOOTSTRAP_SERVERS=broker1.url:12658 \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SECURITY_PROTOCOL=SSL \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_TRUSTSTORE_LOCATION=/etc/config/broker1/kafka.truststore.jks \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_TRUSTSTORE_PASSWORD= \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_KEYSTORE_TYPE=PKCS12 \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_KEYSTORE_LOCATION=/etc/config/broker1/kafka.keystore.p12 \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_KEYSTORE_PASSWORD= \
    --from-literal MP_MESSAGING_INCOMING_KAFKA_IN_SSL_KEY_PASSWORD= \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_BOOTSTRAP_SERVERS=broker2.url:12658 \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SECURITY_PROTOCOL=SSL \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_TRUSTSTORE_LOCATION=/etc/config/broker2/kafka.truststore.jks \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_TRUSTSTORE_PASSWORD= \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_KEYSTORE_TYPE=PKCS12 \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_KEYSTORE_LOCATION=/etc/config/broker2/kafka.keystore.p12 \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_KEYSTORE_PASSWORD= \
    --from-literal MP_MESSAGING_OUTGOING_KAFKA_OUT_SSL_KEY_PASSWORD= \
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Debian
 - Output of `java -version`: 15
 - Quarkus version or git rev: 1.8.3.Final

**Comment by cescoffier** [comment]
@loicmathieu Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/801.

**Comment by loicmathieu** [comment]
Cool thanks. 
Will it be part of Quarkus 1.10 ?

**Comment by cescoffier** [comment]
Yes.
