### ISSUE TITLE
maven-tooling and gradle-tooling adoc - no info about java application build, just native app info

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1267]
maven-tooling and gradle-tooling adoc have no info about java application build, just native app info

For maven getting-started-guide.html#packaging-and-run-the-application can be linked or reused
No info for Gradle.

On the other hand those are standard commands people could handle by default.
So question is should be the tooling docs advanced or not ?

**Comment by stalep** [comment]
Not sure I understand what you think of regarding "no info about java application build". What do you think is missing from the Gradle tooling guide?

**Comment by gsmet** [comment]
Let's close this one. Please open a PR with improvements if you think some are needed.
