### ISSUE TITLE
Truststore should be added but replaces default one

### ISSUE THREAD

**Issue by anthonydahanne** [quarkusio/quarkus#12697]
**Describe the bug**
Hello all,
Following the documentation at : https://quarkus.io/guides/native-and-ssl  /. https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/native-and-ssl.adoc , I have created a new truststore with my company certificates.

**Expected behavior**

According to the documentation using:

    quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=/tmp/mycerts,-J-Djavax.net.ssl.trustStorePassword=changeit

I should **add** to my native binary the certificates included in `/tmp/mycerts` 

**Actual behavior**

Only the certificates in `/tmp/mycerts` are trusted

If I try to connect to https://google.ca , I'll get:
```
2020-10-13 21:05:20,299 INFO  [GetResource] (executor-thread-1) About to load the following url: https://www.google.ca
2020-10-13 21:05:20,515 INFO  [GetResource] (executor-thread-1) That did not go well, printing exception now
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Environment (please complete the following information):**
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 20.1.0-java11
 - Quarkus version or git rev: 1.8.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by geoand** [comment]
Is this still an issue>

**Comment by shawkins** [comment]
@geoand this can be closed, the docs clearly state -J-Djavax.net.ssl.trustStore will be used instead of the default, not in addition to.

**Comment by geoand** [comment]
Thanks for the follow @shawkins
