### ISSUE TITLE
At create from command line are have wrong version dependency

### ISSUE THREAD

**Issue by xumk** [quarkusio/quarkus#12703]
If create quarkus project from command line like indicated on site
for gradle:
```mvn io.quarkus:quarkus-maven-plugin:1.8.3.Final:create \
    -DprojectGroupId=com.test \
    -DprojectArtifactId=create-test-gradle \
    -DprojectVersion=my-version \
    -DclassName="org.my.group.MyResource" \
    -Dextensions="resteasy-jsonb" \
    -DbuildTool=gradle
```
for maven:
```mvn io.quarkus:quarkus-maven-plugin:1.8.3.Final:create \
    -DprojectGroupId=ru.aleksey \
    -DprojectArtifactId=create-test-maven \
    -DprojectVersion=my-version \
    -DclassName="org.my.group.MyResource"
```
we getting created by `gradle.properties` and `pom.xml` files with 1.9.0.CR1 version instead 1.8.3.Final

**Comment by xumk** [comment]
@gastaldi what you think about it

**Comment by gsmet** [comment]
@aloubyansky didn't we fix this behavior recently?

**Comment by aloubyansky** [comment]
Ah, no, we still need to adjust the upper boundary. It's up to "final" exclusive, so the CR got included.

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/pull/12710 should fix it. Thanks @xumk !
