### ISSUE TITLE
Quiting quarkus:dev with Ctrl+C doesn't allow @PreDestroy hooks to finish

### ISSUE THREAD

**Issue by derekm** [quarkusio/quarkus#12723]
**Describe the bug**
When exiting `quarkus:dev` mode with Ctrl+C, `@PreDestroy` hooks rarely have enough time to complete.

**Expected behavior**
Other CDI containers I've used trap the Ctrl+C signal to finish completion of all `@PreDestroy` hooks before exiting the container.

**Actual behavior**
`@PreDestroy` appear to be called, but it looks like thread pools are terminated before they're done executing. I only rarely see the results of print statements I have in my `@PreDestroy` hooks.

**To Reproduce**
Set up a `@PreDestroy` hook with some print statements. Exit from an `mvn compile quarkus:dev` session, and see that the print statements infrequently execute.

**Comment by stuartwdouglas** [comment]
Are you sure they are not actually running? Ctrl + C will kill the outer maven process, which has forked the dev mode process. It is likely that what is happening is the threads that read the output from the forked process and print it to stdout are being shutdown, so the output does not get printed. If you change it to writing to a file rather than stdout does this change the effect?

**Comment by mkouba** [comment]
I can confirm that Stuart is right. I've modified the [lifecycle quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/lifecycle-quickstart):
```java
@ApplicationScoped
public class MyOtherBean {
  
    @PreDestroy
    void destroy() throws InterruptedException {
        for (int i = 0; i < 10; i++) {
            System.out.println("Destroying... " + i);
            Thread.sleep(200l);
        }
    }
}
```
And run `mvn quarkus:dev` and then hit CTRL+C:
```
2020-10-15 08:36:58,044 INFO  [ListenerBean] (Quarkus Main Thread) The application is starting...hello
2020-10-15 08:36:58,087 INFO  [io.quarkus] (Quarkus Main Thread) lifecycle-quickstart 1.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.750s. Listening on: http://0.0.0.0:8080
2020-10-15 08:36:58,089 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-10-15 08:36:58,089 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy]
^C2020-10-15 08:37:00,032 INFO  [ListenerBean] (Shutdown thread) The application is stopping... bye bye
Destroying... 0
Destroying... 1
mkouba@myhost: /opt/source/protean/quickstarts/lifecycle-quickstart  Destroying... 2
Destroying... 3
Destroying... 4
Destroying... 5
Destroying... 6
Destroying... 7
Destroying... 8
Destroying... 9
2020-10-15 08:37:02,041 INFO  [io.quarkus] (Shutdown thread) lifecycle-quickstart stopped in 2.009s
```

**Comment by mkouba** [comment]
@stuartwdouglas would it be possible to wait for the dev mode process to finish after CTRL+C?

**Comment by stuartwdouglas** [comment]
I think we just need to catch InterrupedException in DevMojo and then stop the Runner, which will wait for it to finish.
