### ISSUE TITLE
oidc use Programmatically Resolving Tenants Configuration BUT hangs

### ISSUE THREAD

**Issue by xiaomogu1** [quarkusio/quarkus#12754]
Hi
@sberyozkin
@pedroigor

regarding to this: 
https://quarkus.io/guides/security-openid-connect-multitenancy#programmatically-resolving-tenants-configuration

if i used configuration ways, it works fine and can redirect to keycloak,

BUT when uses programmatically way it hangs there and keep waiting.

//////////////////////////
I use intellj debug mode and dive into the source code, I found the issue is in this part,

in DefaultTenantConfigResolver.java

if (tenantContext == null) {
if (create) {
synchronized (dynamicTenantsConfig) {
tenantContext = dynamicTenantsConfig.computeIfAbsent(tenantId,
clientId -> tenantConfigBean.getTenantConfigContextFactory().apply(tenantConfig));
}
} else {
tenantContext = new TenantConfigContext(null, tenantConfig);
}
}
=======>>>>>

synchronized (dynamicTenantsConfig) {
tenantContext = dynamicTenantsConfig.computeIfAbsent(tenantId,
clientId -> tenantConfigBean.getTenantConfigContextFactory().apply(tenantConfig));
}

this one looks the root issue cause,
when reach this line, it terminated.

can you please have a look?

BTW here is show that
I used the programmtical way this is my application code level:

@ApplicationScoped
public class CustomTenantConfigResolver implements TenantConfigResolver {

@Override
public OidcTenantConfig resolve(RoutingContext context) {
    String path = context.request().path();
    String[] parts = path.split("/");

    if (parts.length == 0) {
        // resolve to default tenant configuration
        return null;
    }

    if ("tenant-a".equals(parts[1])) {
        OidcTenantConfig config = new OidcTenantConfig();
         config.setTenantId("tenant-a");
        config.setAuthServerUrl("http://localhost:8180/auth/realms/tenant-a");
        config.setClientId("multi-tenant-client");
        config.applicationType = OidcTenantConfig.ApplicationType.WEB_APP;
        return config;
    }

    // resolve to default tenant configuration
    return null;
}
}

can you please have a look, thanks!

**Comment by sberyozkin** [comment]
@xiaomogu1 What version of Quarkus is it ? There are a few tests passing where a custom `TenantConfigResolver` is used, and other users have it working as well AFAIK. Is it a dev mode ? Having a reproducer would help

**Comment by xiaomogu1** [comment]
Hi @sberyozkin 

I used the 1.8.1.Final and in a dev Mode

Only the programmtical way is not working,  

https://quarkus.io/guides/security-openid-connect-multitenancy#programmatically-resolving-tenants-configuration

for TenantConfigResolver, do you have any samples so that i can have a look?

after the server started, http://localhost:8080/default worked fine coz it used the default quarkus config,

but when when trigger http://localhost:8080/tenant-a its not working.

if ("tenant-a".equals(parts[1])) {
    OidcTenantConfig config = new OidcTenantConfig();
     config.setTenantId("tenant-a");
    config.setAuthServerUrl("http://localhost:8180/auth/realms/tenant-a");
    config.setClientId("multi-tenant-client");
    config.applicationType = OidcTenantConfig.ApplicationType.WEB_APP;
    return config;
}

**Comment by sberyozkin** [comment]
@xiaomogu1 Does it work in the JVM Mode ? And can you please try the latest `1.9.0.CR1` ?

**Comment by xiaomogu1** [comment]
Hi @sberyozkin 

Still not working even if I uplift to 1.9.0.CR1
this is my pom https://github.com/xiaomogu1/getting-started-oicd/blob/master/pom.xml

I have other mode 
1. ./mvnw package and then with java -jar ./target/getting-started-1.0-SNAPSHOT-runner.jar 
2. native mode ./mvnw package -Pnative and then ./target/getting-started-1.0-SNAPSHOT-runner

I also committed my latest code regarding the change you suggested 

https://github.com/xiaomogu1/getting-started-oicd

any other ideas?

**Comment by xiaomogu1** [comment]
some updates:
@sberyozkin  && @pedroigor 

I dive into the code into the class OidcRecorder

found this line 

I tried to bypass getJwkPath() (By setting onfig.setDiscoveryEnabled(false);)
It no longer hangs but keep looping redirect after authentication and never ends the redirect

if I manually set JwkPath （the value set to .well-known/jwks.json）
it still hangs 

private static OAuth2Auth setOidcEndpoints(Vertx vertx, OAuth2ClientOptions options) {
        if (options.getJwkPath() != null) {
            return Uni.createFrom().emitter(new Consumer<UniEmitter<? super OAuth2Auth>>() {
                @SuppressWarnings("deprecation")
                @Override
                public void accept(UniEmitter<? super OAuth2Auth> uniEmitter) {
                    OAuth2Auth auth = OAuth2Auth.create(vertx, options);
                    auth.loadJWK(res -> {
                        if (res.failed()) {
                            uniEmitter.fail(toOidcException(res.cause()));
                        }
                        uniEmitter.complete(auth);
                    });
                }
            }).await().indefinitely();
        } else {
            return OAuth2Auth.create(vertx, options);
        }
    }

**Comment by sberyozkin** [comment]
So, looks like it is hanging if there was an error during the auto-discovery; probably some exception has to be caught correctly, will have to be fixed; probably the same reason with the wrong jwk path

**Comment by xiaomogu1** [comment]
![jwk](https://user-images.githubusercontent.com/5001581/96409841-aa03b800-1231-11eb-977d-0ba809c3057c.png)

Hi @sberyozkin 
thanks your helping, is it possible to open a to-do ticket so that I can closed this ticket? or just simply leave it here to wait for your fix.

BTW
I have attached a screenshot to show I actually provide the VALID JWK path, should be correct and help you just wonder even if I pass a correct jwk path, still hanging

Again thanks for your help!

**Comment by xiaomogu1** [comment]
Hi @sberyozkin 

any updates for the actions about this issue？For above comments?

Thanks

**Comment by sberyozkin** [comment]
@xiaomogu1 Hi, I'll look into making sure the exception reported during the tenant connection init is correctly reported.

**Comment by sberyozkin** [comment]
@xiaomogu1 I've reproduced the problem and hopefully have a fix ready soon. There is a real problem here which you detected, it is impossible to create the `web-app` tenants from `TenantConfigResolver`. We have tests where the `service` tenants are created, but no `web-app` tenants.

**Comment by sberyozkin** [comment]
The only workaround is to use the introspection only for now and no discovery which is what you've also confirmed.

**Comment by xiaomogu1** [comment]
Thanks for that!! @sberyozkin 

So by work flow 
  can I close MY ticket? or Simply you close it for me.

**Comment by sberyozkin** [comment]
@xiaomogu1 It will be closed once the PR has been merged

**Comment by sberyozkin** [comment]
The original PR was faulty, a new one will fix it soon
