### ISSUE TITLE
Add option to @InjectMock/QuarkusMock.installMock() services with Generics

### ISSUE THREAD

**Issue by asodja** [quarkusio/quarkus#12761]
**Description**
Currently it is not possible to use `@InjectMock` with services with generic interface. For example check this case:
https://github.com/asodja/quarkus-generic-mock/blob/master/src/test/java/org/my/group/MyResourceTest.java

When running test you get:
```
Caused by: java.lang.IllegalStateException: Invalid use of io.quarkus.test.junit.mockito.InjectMock - could not determine bean of type: interface org.my.group.service.Service. Offending field is service of test class class org.my.group.MyResourceTest
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.getBeanInstance(CreateMockitoMocksCallback.java:61)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.afterConstruct(CreateMockitoMocksCallback.java:27)
```

To workaround this you have to use rawtypes everywhere (also in production code) which is not nice.

It would be great if there is some way of Injecting Mocks for services that use generics.

**Comment by diogenes1oliveira** [comment]
Yes, that's annoying. I managed to work around it because my generic is an interface and so I can just inject the mock of the concrete one.

```java
public interface Parser<T> {
    T parse(HttpRequest request) throws IOException;
}

@ApplicationScoped
public class SomeTodoParser implements Parser<Todo> {
    
...
}

@Inject
Parser<Todo> parser;

```

Doesn't work as expected in tests:

```java
@InjectMock
Parser<Todo> parser; // fails with could not determine bean of type

@InjectMock
SomeTodoParser parser; // works 
```

It's quite annoying because it sends a wrong signal in the test code. Could I try to propose a PR?

**Comment by asodja** [comment]
This seems to be still an issue. Any plan to try to add workaround?

It would be great that injection would atleast work with `@Named` or `@Qualifier` and Quarkus would ignore generics for tests.

**Comment by geoand** [comment]
This fell off my radar completely. 

I'll try and have a look for `2.1`

**Comment by geoand** [comment]
> Could I try to propose a PR?


@diogenes1oliveira contributions are always welcome!

**Comment by geoand** [comment]
This was actually fixed in https://github.com/quarkusio/quarkus/pull/18030
