### ISSUE TITLE
Missing documentation for agroal datasource configuration property

### ISSUE THREAD

**Issue by rohit-s8** [quarkusio/quarkus#12768]
https://github.com/quarkusio/quarkus/blob/5c5410e9834febc90b4252a3a507b075119033e2/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcRuntimeConfig.java#L112

There is no documentation for this configuration property in any of the guides in https://quarkus.io/guides

**Comment by geoand** [comment]
I don't think there is value in adding this property to the guides as thttps://quarkus.io/guides/all-config#quarkus-agroal_quarkus.datasource.jdbc.additional-jdbc-properties-additional-jdbc-properties gives one all the information necessary
