### ISSUE TITLE
Quarkus:dev is unkillable if StartupEvent has infinite loop

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#12769]
To reproduce, put this in a quarkus project:

```
@ApplicationScoped
public class FactorioDataGenerator {

    public void generateDemoData(@Observes StartupEvent startupEvent) {
           while (true) {
               // If needed Do something to avoid this code getting optimized away.
           }
    }
}
```

and then run `mvn quarkus:dev` in the terminal (I used the IntelliJ terminal). As your computer starts acting wierd, hit `ctrl-c`, which will give you back your terminal prompt. Then look at your OS task navigator. Notice that a process is still running at full CPU usage and it refused to die: that ctrl-c didn't kill it.

**Comment by rmanibus** [comment]
I think you should not block quarkus threads.
instead you can do something like:
```
@ApplicationScoped
public class Demo {

    ExecutorService executor = Executors.newSingleThreadExecutor();

    public void generateDemoData(@Observes StartupEvent startupEvent) {
        executor.submit(this::execute);
    }

    void execute(){
        while (true) {
            // If needed Do something to avoid this code getting optimized away.
        }
    }
}
```

**Comment by ge0ffrey** [comment]
Writing that infinite loop in the startup event was not intentional :)

Trying to kill it when I realized my mistake, was intential, yet quarkus:dev didn't actually kill it.

**Comment by famod** [comment]
Maybe #12805 helps here as well?

**Comment by stuartwdouglas** [comment]
I don't know if there is much we can do about this, and still guarantee a clean shutdown (we need to wait for beans to be created before we destroy them, so we need to wait for the creation process to complete).

**Comment by ge0ffrey** [comment]
Maybe create a thread with a high priority that listen to the ctrl-c event? If that event happens, pas a poison pill to the child processes?
Does quarkus:dev have child processes? Or did I just see multiple because I ran it multiple times?

**Comment by stuartwdouglas** [comment]
If a thread is in an infinite loop there is no way to stop it, other than Thread.stop() which is hugely problematic, and in this case would stop a clean shutdown as Quarkus would be expecting that thread to run the shutdown tasks.

**Comment by ge0ffrey** [comment]
If ctrl-c is hit for quarkus:dev, can't you just call `System.exit(1)` inside the process? Maybe sleep 5 seconds to give it to opportunity to shutdown gracefully? In that case, it doesn't matter if a Thread is stick in an infinite loop.

Reproduce this issue to experience how it feels like a user: I had hit "ctrl-c" and I did get back my terminal prompt back, but I did know that the rogue Quarkus:dev process was still running consuming a LOT of CPU resources. It took me 3 runs for me to figure out I had an infinite loop, and then I started noticing that my system was grinding to a halt, and it turns out that quarkus:dev was to blame. It felt like it had infected my computer :)

Even better, when the gracefull shutdown fails and System.exit(1) must be called, print something to the console (that still works, it show up between the command prompt) that says: "Non-gracefull shutdown, you probably created an infinite loop!")

**Comment by stuartwdouglas** [comment]
System.exit(1) won't exit if there is a non-daemon thread stuck in an infinite loop. Your only options are Thread.stop() which is deprecated for very good reason, and kill -9.

We could use a shutdown hook in Maven to wait X seconds then kill the process I guess. It's only dev mode, so that might be ok.

**Comment by famod** [comment]
> We could use a shutdown hook in Maven to wait X seconds then kill the process I guess. It's only dev mode, so that might be ok.

And so should the Gradle plugin and any IDE integration (that is not based on Maven)?

Btw, just killing the process right away (without a grace period) on CTRL+C doesn't seem like a good idea since that would prevent shutdown hooks from running (e.g. see #12577).

**Comment by stuartwdouglas** [comment]
> 
> Btw, just killing the process right away (without a grace period) on CTRL+C doesn't seem like a good idea since that would prevent shutdown hooks from running (e.g. see #12577).

Exactly, from a production point of view you just can't really do this. You can have an infinite loop in other threads as well, you just can't guard against this. 

I am going to close this, basically you can only have one of the following guaranteed:

a) That all shutdown code that should run is being run (i.e. that you can do a clean shutdown)
b) That shutdown completes in a given time period

I think it is more important to guarantee a) than to try and do b) to guard against developer mistakes.
