### ISSUE TITLE
Quarkus Crash during runtime with web3j dependency

### ISSUE THREAD

**Issue by mmaryo** [quarkusio/quarkus#12770]
Hello 

I provide you a simple project with 
Gradle 6.6.1
Kotlin 1.4 (Java 11 is set in IntelliJ)
Quarkus 1.8.3.Final
Resteasy
SwaggerUi
Health
Web3j

And one rest route 

[quarkus-bug-web3j.zip](https://github.com/quarkusio/quarkus/files/5395569/quarkus-bug-web3j.zip)

I compile and start with gradle quarkusDev
No error
Then I go to http://localhost:8080/swagger-ui
And see this stacktrace 

![quarkus-web3j](https://user-images.githubusercontent.com/1669985/96336201-4b4a0d00-107e-11eb-978f-95a6c0b98184.png)

It may related to https://github.com/quarkusio/quarkus/issues/12680

Regards

**Comment by mmaryo** [comment]
Try to remove this dependcy 
'org.jboss.logmanager:log4j2-jboss-logmanager:1.0.0.Beta1'

And at startup that throw exception 

Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?

**Comment by geoand** [comment]
Closing for lack of feedback.
