### ISSUE TITLE
[OIDC Multi tenant] Environment variable doesn't take when not present in application.properties

### ISSUE THREAD

**Issue by DorianMaliszewski** [quarkusio/quarkus#12794]
**Describe the bug**
I'm working on a multi tenant application. I find that when you don't put any properties for a tenant in the application.properties file (like quarkus.oidc.test.auth-server-url), then compile it and when launching the application with the environment variables, Quarkus doesn't take care of them:

Application.properties file :
```properties
# OIDC configuration
quarkus.oidc.auth-server-url=http://localhost:8081/auth/realms/test-a
quarkus.oidc.client-id=api
quarkus.oidc.credentials.secret=ab49118d-f9d0-42b2-bee6-f9bc1501595d
```

Environment variables :
```
QUARKUS_OIDC_ENABLED=true
QUARKUS_OIDC_AUTH_SERVER_URL=http://localhost:8081/auth/realms/test-a
QUARKUS_OIDC_CLIENT_ID=api
QUARKUS_OIDC_CREDENTIALS_SECRET=ab49118d-f9d0-42b2-bee6-f9bc1501595d

QUARKUS_OIDC_TEST_B_TENANT_ENABLED=true
QUARKUS_OIDC_TEST_B_TENANT_ID=test-b
QUARKUS_OIDC_TEST_B_AUTH_SERVER_URL=http://localhost:8081/auth/realms/test-b
QUARKUS_OIDC_TEST_B_CLIENT_ID=api
QUARKUS_OIDC_TEST_B_CREDENTIALS_SECRET=1499a028-05aa-4903-bdf7-b89c540ca4b9
```

**Expected behavior**
Quarkus is taking the environment variables same If there are not present when compiling the application. Then I can identify users of other tenants without recompiling my application.

**Actual behavior**
Quarkus doesn't take care of my additional tenant which is not in the application.properties file. It doesn't load test-b configuration since I had `quarkus.oidc.test-b.tenant-enabled=true` in my application.properties file then recompiling then add environment variable.

**To Reproduce**

1. Generate project with oidc extension.
2. Launch Keycloak server with 2 realms
3. Put configuration of the first realm in the application.properties file
4. Build docker image 
5. Launch the container from the image you built with additional tenant configuration

**Configuration**
```properties
# OIDC configuration
quarkus.oidc.auth-server-url=http://localhost:8081/auth/realms/test-a
quarkus.oidc.client-id=api
quarkus.oidc.credentials.secret=ab49118d-f9d0-42b2-bee6-f9bc1501595d

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux NOPLACELIKEHOME 5.4.67-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:20:18 UTC 2020 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15 (AdoptOpenJdk)
 - Quarkus version or git rev: 1.8.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by latyaodessa** [comment]
I had the same issue. 
You need to specify "test-b-tenant" tenant in application.properties like

```
quarkus.oidc.test-b-tenant.enabled=true
quarkus.oidc.test-b-tenant.client-id=blabla
....
and so on
```

basically you need to specify every property and then it will be overridden by env. variables.

**Comment by sberyozkin** [comment]
@DorianMaliszewski Which property in from the original configuration is not overridable ? Adding the new tenant via the system properties is not even possible. Please either follow what @latyaodessa suggested or try a custom `TenantConfigResolver`

**Comment by DorianMaliszewski** [comment]
@sberyozkin @latyaodessa,

Okay, I understand, I tough that not only to override but to add more too.
So may be this can be an improvement :joy:

Have a good day,

**Comment by sberyozkin** [comment]
Hey @DorianMaliszewski thanks, a given `OidcTenantConfig` can be arbitrary complex, so creating a new tenant with N system properties would be quite brittle :-). `TenantConfigResolver` is the best way to control tenants dynamically IMHO, and you can have some custom properties there as well, etc
