### ISSUE TITLE
jaxp issue

### ISSUE THREAD

**Issue by dufoli** [quarkusio/quarkus#12799]
The code is inside cxf extension for quarkus. I try to fix the native support. But I am stuck on an issue with jaxp.
I have added a substitution to debug and my schema seems right but the namespace is not returned.

Utilisation of JAXP in native with Document()
Code executed
DOMSource domSource = new DOMSource(d);
        StringWriter writer = new StringWriter();
        StreamResult result = new StreamResult(writer);
        TransformerFactory tf = TransformerFactory.newInstance();
        Transformer transformer = null;
        try {
            transformer = tf.newTransformer();
            transformer.transform(domSource, result);
        } catch (Exception e) {
        }

        Logger LOG = LogUtils.getL7dLogger(org.apache.cxf.endpoint.dynamic.TypeClassInitializer.class);
        LOG.info("DOCUMENT :"+ writer.toString());
        LOG.info("DOCUMENT element :"+ d.getDocumentElement().toString());
        LOG.info("DOCUMENT namespace :"+ d.getDocumentElement().getNamespaceURI());

```
2020-10-19 14:19:53,770 INFO  [org.apa.cxf.end.dyn.TypeClassInitializer] (executor-thread-1) DOCUMENT :<?xml version="1.0" encoding="UTF-8" standalone="no"?><schema xmlns:tns="http://cxf.it.quarkus.io/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://cxf.it.quarkus.io/" version="1.0">
<element name="reply" type="tns:reply"/>
<element name="replyResponse" type="tns:replyResponse"/>
<complexType name="reply"><sequence><element minOccurs="0" name="text" type="xs:string"/></sequence></complexType>
<complexType name="replyResponse"><sequence><element minOccurs="0" name="return" type="xs:string"/></sequence></complexType>
</schema>
2020-10-19 14:19:53,770 INFO  [org.apa.cxf.end.dyn.TypeClassInitializer] (executor-thread-1) DOCUMENT element :[schema: null]
2020-10-19 14:19:53,771 INFO  [org.apa.cxf.end.dyn.TypeClassInitializer] (executor-thread-1) DOCUMENT namespace :null
```

**Comment by dufoli** [comment]
I have added many class which seems loaded by reflection in cxf or in jab jaxp but still failing.
 
reflectiveItems.produce(new ReflectiveClassBuildItem(true, true,
                "com.sun.org.apache.xpath.internal.domapi.XPathEvaluatorImpl",
                "com.sun.xml.internal.stream.events.XMLEventFactoryImpl",
"com.sun.xml.internal.bind.marshaller.NoEscapeHandler",
                "com.sun.xml.internal.bind.marshaller.MinimumEscapeHandler",
                "com.sun.xml.bind.marshaller.NoEscapeHandler",
                "com.sun.xml.bind.marshaller.MinimumEscapeHandler",
                "org.apache.cxf.common.jaxb.NamespaceMapper",
                "org.apache.cxf.jaxb.NamespaceMapper",
                "com.sun.tools.internal.xjc.api.XJC",
                "com.sun.tools.xjc.api.XJC",
                "com.sun.xml.internal.bind.api.JAXBRIContext",
                "com.sun.xml.bind.api.JAXBRIContext",
                "com.sun.xml.bind.v2.runtime.LeafBeanInfoImpl",
                "com.sun.xml.bind.v2.runtime.ArrayBeanInfoImpl",
                "com.sun.xml.bind.v2.runtime.ValueListBeanInfoImpl",
                "com.sun.xml.bind.v2.runtime.AnyTypeBeanInfo",
                "com.sun.xml.bind.v2.runtime.JaxBeanInfo",
                "com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl",
                "com.sun.xml.bind.v2.runtime.CompositeStructureBeanInfo",
                "com.sun.xml.bind.v2.runtime.ElementBeanInfoImpl",
                "com.sun.xml.bind.v2.runtime.MarshallerImpl",
                "com.sun.xml.messaging.saaj.soap.SOAPDocumentImpl",
                "com.sun.xml.internal.messaging.saaj.soap.SOAPDocumentImpl",
                "com.sun.org.apache.xerces.internal.dom.DOMXSImplementationSourceImpl",
                "com.sun.xml.internal.bind.v2.ContextFactory",
                "com.sun.xml.bind.v2.ContextFactory",
                "com.sun.xml.bind.v2.runtime.BridgeContextImpl",
                "com.sun.xml.bind.v2.runtime.JAXBContextImpl",
                "com.sun.xml.bind.subclassReplacements",
                "com.sun.xml.bind.defaultNamespaceRemap",
                "com.sun.xml.bind.c14n",
                "com.sun.xml.bind.v2.model.annotation.RuntimeAnnotationReader",
                "com.sun.xml.bind.XmlAccessorFactory",
                "com.sun.xml.bind.treatEverythingNillable",
                "com.sun.xml.bind.retainReferenceToInfo",
                "com.sun.xml.internal.bind.subclassReplacements",
                "com.sun.xml.internal.bind.defaultNamespaceRemap",
                "com.sun.xml.internal.bind.c14n",
                "com.sun.xml.internal.bind.v2.model.annotation.RuntimeAnnotationReader",
                "com.sun.xml.internal.bind.XmlAccessorFactory",
                "com.sun.xml.internal.bind.treatEverythingNillable",
                "com.sun.xml.bind.marshaller.CharacterEscapeHandler",
                "com.sun.xml.internal.bind.marshaller.CharacterEscapeHandler",
                "com.sun.org.apache.xerces.internal.dom.ElementNSImpl",
                "com.sun.xml.internal.bind.retainReferenceToInfo"

**Comment by dufoli** [comment]
yes I have added it ;-)

**Comment by dufoli** [comment]
the whole project is in https://github.com/dufoli/quarkus-cxf

**Comment by dufoli** [comment]
I have nother exception upper:
2020-10-19 14:19:53,767 FINE  [com.sun.xml.bin.v2.sch.XmlSchemaGenerator] (executor-thread-1) Writing XML Schema for com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator@7fcae7477c78[http://cxf.it.quarkus.io/=com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace@7fcae7477ef8]: com.sun.xml.bind.v2.util.StackRecorder
	at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator.write(XmlSchemaGenerator.java:425)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.generateSchema(JAXBContextImpl.java:790)
	at org.apache.cxf.common.jaxb.JAXBUtils.generateJaxbSchemas(JAXBUtils.java:813)
	at org.apache.cxf.jaxb.JAXBDataBinding.generateJaxbSchemas(JAXBDataBinding.java:467)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:384)
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)

**Comment by Postremus** [comment]
@dufoli If I understand correctly, the problem is that `d.getDocumentElement().getNamespaceURI()` returns null, even though the namespace is set using `xmlns:xs="http://www.w3.org/2001/XMLSchema"`.


I am myself not that familiar with jaxp / jaxb apis, but managed to find a place a bit earlier where the nsUri is returned as blank:
https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/txw/runtime/src/main/java/com/sun/xml/txw2/TXW.java#L59

(localname is schema, so that is the right tag).

I started a bit of cleanup in https://github.com/Postremus/quarkus-cxf/commits/try-fix-native-tests.

**Comment by dufoli** [comment]
hello @Postremus ,
thanks for help.
I have added proxy because of cxf:
https://github.com/apache/cxf/blob/dc2f6af9ad09888cafb350f95935e9ec6abf8aee/core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java#L1585

**Comment by gastaldi** [comment]
Are you depending on the `quarkus-jaxp` extension from Quarkus 1.9.0.Final?

**Comment by dufoli** [comment]
OK, I have gone further...
issue is located in
    com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator.write
        com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator.Namespace.writeTo
            com.sun.xml.bind.v2.schemagen.xmlschema.Schema._namespace
indeed  com.sun.xml.bind.v2.schemagen.xmlschema.Schema implement TypedXmlWriter which is a proxy interface

com.sun.xml.txw2.ContainerElement handle the invoke method
I have declared TypedXmlWriter as proxy interface and all inherited interface too but it is still not enough.

**Comment by dufoli** [comment]
ok got the point. Indeed, I end exactly to the same place. So XMLNamespace target (package) must be loaded.
        for (AnnotationInstance xmlNamespaceInstance : index.getAnnotations(DotName.createSimple("com.sun.xml.txw2.annotation.XmlNamespace"))) {
            reflectiveClass.produce(new ReflectiveClassBuildItem(false, false, xmlNamespaceInstance.target().asClass().name().toString()));
        }

**Comment by dufoli** [comment]
I have sent a pull request for that and few other things:
https://github.com/quarkusio/quarkus/pull/13408

**Comment by geoand** [comment]
Is this still an issue?
