### ISSUE TITLE
OIDC Introspection and Userinfo Cache

### ISSUE THREAD

**Issue by JohZed** [quarkusio/quarkus#12800]
**Description**
(see also discussions on #4481)

Currently, opaque OIDC access tokens need to invoke the token introspection and userinfo endpoint for each request. 

An improvement would be the addition of a token introspection/userinfo cache. The cache should be configurable with a cache expiration. Applications would first check the token by invoking cache if not found it would invoke the token introspection/userinfo endpoint.

**Comment by missourian55** [comment]
We have similar requirements, in our organizations its a mandatory requirement to cache the userinfo for certain duration. It would be nice if Quarkus supports token introspection (OAuth2/OIDC) with a caching feature.

**Comment by sberyozkin** [comment]
Looking into this issue now
