### ISSUE TITLE
Cannot use multiple persistence units in same transaction

### ISSUE THREAD

**Issue by jfrantzius** [quarkusio/quarkus#12804]
**Describe the bug**
Given two Java packages configured in two separate persistence units, it is not possible to query entities in both of them within the same transaction. The query for the second persistence unit will always fail, while the first one works (i.e. no matter which PU is queried first, the other will fail). Querying the PUs outside of a transaction succeeds, though.

**Expected behavior**
It should be possible to query two different persistence units within the same transaction. 

**Actual behavior**
The second query always fails with `java.lang.IllegalArgumentException: Could not locate ordinal parameter [1], expecting one of []`

**To Reproduce**
[panache-multipe-persistence-units.zip](https://github.com/quarkusio/quarkus/files/5403827/panache-multipe-persistence-units.zip)
1. unzip above archive (code is based on hibernate-orm-panache-quickstart)
2. invoke `mvn test`
3. see test class fail in `org.acme.hibernate.orm.panache.MultiPersistenceUnitTest.testBothQueriesInTx()`, while tests doing the same outside of a transaction succeed

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin C02Z74E4LVDQ 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.3-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by yuhaibohotmail** [comment]
I have the same problem in my project，@Sanne

**Comment by jfrantzius** [comment]
It seems that io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager (TSEM) uses the following as the key for registering a "real" `EntityManager` with the current thread's transaction:
```java
private static final Object transactionKey = new Object();
```
As the TSEM itself has the name of the persistence unit as a constructor argument, the TSEM seems to be meant only for a single persistence unit. But the key above is a static object (one per class), so all TSEMs in the transaction will overwrite each other's `EntityManager`s in the transaction.  That could explain why the wrong `EntityManager` is applied for a query in the transaction.

I guess the key must not be a static object, but should be something like `TransactionScopedEntityManager.class.getName() + unit`, so there will be one `EntityManager` per `unit` registered in the transaction.

**Comment by jfrantzius** [comment]
Can reproduce the bug with 1.9.0.Final as well, using above example project.

**Comment by gsmet** [comment]
Yeah, you're right, there's something fishy.

Let me clean this up.

**Comment by jfrantzius** [comment]
OK I was able to fix it using a key for the transaction as described above. Will try to provide a Merge-Request.

**Comment by jfrantzius** [comment]
Looks like accessing two PUs in one transaction wasn't covered by a test yet? `io.quarkus.hibernate.orm.multiplepersistenceunits.MultiplePersistenceResourceInjectionUnitsTest` looks like the right place for it, but didn't cover it so far?

**Comment by gsmet** [comment]
@jfrantzius if it wasn't clear, I'm working on it (mostly because I wanted to do other cleanup in the file)

**Comment by jfrantzius** [comment]
I was a bit in a hurry because our project development is stalled due to this bug ...

**Comment by jfrantzius** [comment]
Also, to be honest, I'd be happy to contribute a PR :)

**Comment by gsmet** [comment]
OK, I suppose I will reapply my cleanups on top of your fix.

**Comment by jfrantzius** [comment]
Thanks @gsmet for the quick responses and looking at the PR!
