### ISSUE TITLE
Quarkus Caching extention: Invalidation does not work

### ISSUE THREAD

**Issue by janknobloch** [quarkusio/quarkus#12818]
**Describe the bug**

Running quarkus 1.8.3.Final: 
`<quarkus.platform.version>1.8.3.Final</quarkus.platform.version>
`

```
@CacheResult(cacheName = "documents")
  @Counted(name = "numbergetByOnlineIdAndIndexName", description = "")
  @Timed(name = "durationgetByOnlineIdAndIndexName", description = "", unit = MetricUnits.MILLISECONDS)
  public OnlineStory getByOnlineIdAndIndexName(@CacheKey long onlineId, String indexName)
```

```
@CacheInvalidateAll(cacheName = "documents")
  private void invalidateCache(@CacheKey long onlineId) {
  }
```

**Expected behavior**
Cache invalidation should work, neither @CacheInvalidateAll nor @CacheInvalidate seem to do anything?
I also tried to pass a second parameter to the invalidation function (non cache key) 
`private void invalidateCache(@CacheKey long onlineId, String indexName)`
to have a similar method signature in sense of parameters for the invalidation function without success.
My invalidation function is called but nothing happens.

**Actual behavior**
Cache is not cleared neither on basis of the @CacheKey (long primitive) / or based on @CacheInvalidateAll flag.

However using:
`quarkus.cache.caffeine."documents".expire-after-access=10S`
clears the cache as expected. 

**Configuration**
```properties
quarkus.cache.caffeine."documents".maximum-size=5000
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
MACOS 10.15.06
AdoptOpenJDK 11
 - GraalVM version 20.2
 - Quarkus version or git rev: 1.8.3. Final

Let me know if I can be of further assistance. Im trying to rule out any other issues from my side, but ATM it looks invalidation is only taking place set via property file not via annotation.

Best
Jan

**Comment by gsmet** [comment]
My guess is that it's because you're annotating a private method for which we won't install the interceptors. Annotating a public method should work.

@gwenneg should we maybe throw an error in this case?
@mkouba I have a very vague recollection that you added support for interceptors in more cases, it's still something we don't support, right?

**Comment by mkouba** [comment]
@janknobloch How and upon which instance do you call the `invalidateCache()` method?

@gsmet Interceptors should work for private methods.

**Comment by gsmet** [comment]
FWIW, these annotations are working properly in the Backports app so there's something specific to this app.

**Comment by janknobloch** [comment]
Hey all sorry for the delayed response,
and thanks for your super quick replies.

@gsmet : You've been correct the private method basically broke the interceptor as you described. Making my method public did the trick, thanks for pointing that out. Setting it to private again shows the behaviour described above.

I think a side note at: https://quarkus.io/guides/cache 
would be helpful about the interceptors :-)

@mkouba:
Basically I run different database services (ApplicationScoped) pulling initial data into my application and than using a single Kafka Service (reactive-messaging) (ApplicationScoped) which receives messages and forwards these "invalidation messages" to my database service.

Call chain in short - hope this helps:

1. databaseService.getDocument() -> annotated with cache annotation see above. (upcoming calls will be properly handled with caching)
2. kafkaService.incomingMsgForInvalidation() -> has an injected instance  of my databaseservice on classlevel and calls
3. public databaseService.handleIncomingRecordFromKafka() -> calls private databaseService. invalidateCache().

So it seems that indeed private methods for invalidation are not working properly?  Or do I have to force singletons as services to make cache invalidation work properly. I would expect the cacheName identifier is working as a singleton per cacheName transparent over all different @ApplicationScoped services? Or am I mistaken here?

Feel free to keep suggestions incoming so I can validate / invalidate.
 
Thanks for your support again.

Feel free to close this ticket as my error could be reproduced and pointed to method modifiers.
Thanks again @gsmet for pointing this out.

**Comment by janknobloch** [comment]
> FWIW, these annotations are working properly in the Backports app so there's something specific to this app.

Just out of curiosity - also for private methods?

**Comment by gsmet** [comment]
> Just out of curiosity - also for private methods?

No the methods are public, thus why I asked about the visibility.

But if @mkouba says interceptors should work on private methods, we should probably check what's going on.

@mkouba I see the interceptor bindings being installed on all methods, there's no "is public" filter. Could you check what's going on?

**Comment by mkouba** [comment]
So I think that the problem is that private methods are invoked via `invokespecial` if called from within another method in a bean class and so even if the intercepted subclass "overrides" the private method it's not invoked. However, interceptors would work e.g. for an intercepted private observer method where it's the container that calls the method. FYI package-private and protected methods should work just fine.

**Comment by gwenneg** [comment]
@mkouba Is there a way to fix that `interceptors on private methods` issue or should the cache extension forbid caching annotations usage on private methods?

**Comment by mkouba** [comment]
@gwenneg I don't think we could easily fix this. We would have to transform the bytecode and modify _all_ call sites which is probably not worth it. So I'd forbid the caching annotations on private methods...

**Comment by gwenneg** [comment]
Thanks for your answer. I'll submit a PR to forbid it.
