### ISSUE TITLE
Use buildtool data to generate requested dockerfile buildtool command

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#12816]
**Description**
Use buildtool data to generate requested dockerfile buildtool doc command:

Need to add `package-fast-jar` here: https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/buildtool/maven/codestart.yml#L29

maybe rename `package-uberjar` to `package-uber-jar`

Then use these in the different dockerfiles templates

**Comment by ia3andy** [comment]
@glefloch do you receive a notification when assigned?

**Comment by glefloch** [comment]
Yes, I did. I started working on it. This is a good idea. We could also use the `buildtool.cli` for Gradle project.
