### ISSUE TITLE
Invalid dockerfile fast-jar doc

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#12815]
**Describe the bug**
@glefloch I missed that in the review, but I think it's `-Dquarkus.package.type=fast-jar`

https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.fast-jar#L2

Could you fix that asap?

**Comment by glefloch** [comment]
yes
