### ISSUE TITLE
Memory leak via MojoLogger.logSupplier

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#12837]
`MojoLogger.logSupplier` is a static field holding a reference to the following chain of refs: 

`BuildMojo` -> `BuildMojo.repoSession` -> `DefaultRepositorySystemSession.cache`

When building Camel Quarkus with [mvnd](https://github.com/mvndaemon/mvnd), this prevents the cache (900+ MB on the heap) from being garbage collected after the build.

A PR follows.

**Comment by aloubyansky** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/12838
