### ISSUE TITLE
Add Support for OAuth 2.0 Authorization Code with PKCE Flow 

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#12856]
**Description**
For SPA & Native apps (public clients) this is the recommended way to implement the Authorization code flow

**Implementation ideas**
Some of the reference materials I looked into are

https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce

https://dzone.com/articles/securing-web-apps-using-pkce-with-spring-boot

https://www.stefaanlippens.net/oauth-code-flow-pkce.html

**Comment by sberyozkin** [comment]
Sure, we've been planning to do it even for the confidential clients

**Comment by sberyozkin** [comment]
@missourian55 I'd like to clarify, we can't do anything around making sure the tokens acquired by the SPA scripts or public clients use PKCE as Quarkus OIDC adapter does not control the code flow for these types of clients. We can only get PKCE applied to the code flow run for Quarkus `web-app` applications.

**Comment by missourian55** [comment]
Makes sense to me. Thanks!

**Comment by sberyozkin** [comment]
Prioritizing on it asap
