### ISSUE TITLE
Recorder must fail fast when it can't find the getter/setter instead of siliently replacing a field with null

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#12864]
```
public class Foo {
     private final String bar;
     public Foo(String bar) {
         this.bar = bar;
    }
    // Just for the recorder
    public Foo() {bar = null;}
   public void sayBar() { sout(bar);}
} 
```
When recording this:
```
new Foo("hello")
```
It ends up with bar being null on the other side, for example:
```
foo.sayBar(); // prints null instead of "hello"
```

Instead of replacing bar silently with null, it should fail fast and mention that it can't serialize bar.

See discussion here:
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/synthetic.20beans.20and.20recorder

**Comment by gsmet** [comment]
@stuartwdouglas not sure if it's an oversight or a feature? Could you confirm?

**Comment by ge0ffrey** [comment]
If it's a feature, the ability to add a strict=true mode to have it fail fast would be very useful.

optaplanner-core's SolverConfig hierarchy is very rich and when parts of it _might disappear_ (replaced by null) when going through the Recorder will lead to difficult to diagnose bugs, much later down the line.

**Comment by stuartwdouglas** [comment]
Originally it was a feature, as we were passing in some objects that were not designed to be recorded, and they could have things like isFooSet() {return foo != null;}. fooSet appears to be a property, but is not something we can record.

I will look at making it strict by default, and adding a @RelaxedValidation annotation for the recorder parameters to deal with any problematic cases.
