### ISSUE TITLE
Doma extension

### ISSUE THREAD

**Issue by nakamura-to** [quarkusio/quarkus#12881]
**Describe the extension**

[Doma](https://github.com/domaframework/doma) is a database access framework for Java 8+.

Quarkus Doma extension provides the following features:

- Build time initialization, configuration, and injection
- Hot reloading of SQL files
- Automatic SQL execution on startup
- Multiple Datasources

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
# Add your application.properties here, if applicable.
quarkus.doma.sql-file-repository=greedy-cache
quarkus.doma.naming=none
quarkus.doma.exception-sql-log-type=none
quarkus.doma.dialect=h2
quarkus.doma.batch-size=10
quarkus.doma.fetch-size=50
quarkus.doma.max-rows=500
quarkus.doma.query-timeout=5000
quarkus.doma.sql-load-script=import.sql
```

**Additional context**

This extension exists here: https://github.com/domaframework/doma-quarkus
Sample application is available here: https://github.com/domaframework/quarkus-sample

I want to develop this extension under the [quarkiverse organization](https://github.com/quarkiverse).

**Comment by gastaldi** [comment]
@nakamura-to hey! It appears that you are already maintaining the extension with several releases going on. That's really great! 

Moving to the Quarkiverse organization would require your extension to be renamed to the `io.quarkiverse.doma` groupId. It would also affect the package name. Is that something you think it's worth doing? 

If your intention is to get your extension listed in our tooling, we're still working on that, but you can add your extension to https://github.com/quarkusio/quarkus-extension-catalog (under the `extensions/` directory) in the mean time.

**Comment by nakamura-to** [comment]
@gastaldi  Hi. Thanks for your reply.

>It would also affect the package name. Is that something you think it's worth doing?

Yes, it's worth doing.
I want to join the Quarkiverse community.

**Comment by gastaldi** [comment]
@nakamura-to I created the https://github.com/quarkiverse/quarkiverse-doma extension and sent you an invite to become the lead maintainer of the repository.

Please set your extension coordinates' to the groupId: `io.quarkiverse.doma`and use the `io.quarkiverse.doma` as the package root.

Instructions to perform a release are here: https://github.com/quarkiverse/quarkiverse/wiki/Release

Let me know if you need anything else. The best way to reach us is through quarkusio.zulipchat.com
