### ISSUE TITLE
Make https://quarkus.io/guides/all-builditems reuse the same style as https://quarkus.io/guides/all-config

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#12887]
It would have been nice to have the same style as the config page, and also the search box. Who worked on that?

_Originally posted by @FroMage in https://github.com/quarkusio/quarkus/issues/733#issuecomment-714505862_

**Comment by SumaiyaSafdar** [comment]
hi, I would like to work on this project. Can you suggest me ways to get started?

**Comment by megha070** [comment]
I would like to take this up.

**Comment by gastaldi** [comment]
@megha070 that would be great! I assigned the issue to you. Feel free to ask anything here or in quarkusio.zulipchat.com

**Comment by lower-case** [comment]
Hi @gastaldi I'd like to work on this issue. 

I'm new to Quarkus. I went through the code of how documentation is generated and noticed few basic things.
The doc for build items is generated via `jbang quarkusbuilditemdoc` and the doc for config is generated via AllConfigGenerator.java

So, for this enhancement, do we have to retain the jbang part or should we migrate to something like AllConfigGenerator.
Also I noticed that build-item part has all the formatting code present in it's own file whereas config code is using SummaryTableDocFormatter. So, Will the enhancement involve using this formatter in builditem doc?

Please correct me If I've missed something and help with any extra suggestions for this change.

Thanks :)

**Comment by gastaldi** [comment]
@lower-case thanks for having a look at it. 

TBH I don't have a strong opinion on how this would be best solved, so I'd let you decide on that ;)

When I created the JBang script, the AllConfigGenerator already existed but I struggled to find a way to reuse it outside the annotation processor code.

**Comment by lower-case** [comment]
Thanks for your reply! Let me dig little more and raise a PR.

**Comment by ritvij14** [comment]
Hi! I am a newcomer to this project. I am done setting up quarkus on my system. Could anyone guide me as to how can I start working on this issue? I would like to start contributing to understand how quarkus works.

**Comment by FroMage** [comment]
Sure, but we first have to check if @lower-case is still working on this?

**Comment by ritvij14** [comment]
@FroMage ok got it. In the meantime, could you tell me some issues/tasks I can work upon to get a better idea of the working of this project? Because I see most of the good-first-issues have been assigned to someone :sweat_smile:

**Comment by lower-case** [comment]
Hey @ritvij14 You can work on this one.

**Comment by ritvij14** [comment]
@lower-case ok thank you. @FroMage could you please guide me a little bit as to how can I work with this?

**Comment by FroMage** [comment]
Sure. The program which generates the build-item docs is at https://github.com/quarkusio/quarkus/blob/master/.github/quarkusbuilditemdoc.java and the one which generates the config is at https://github.com/quarkusio/quarkus/blob/master/docs/src/main/java/io/quarkus/docs/generation/AllConfigGenerator.java

IMO this is just a question of applying the same CSS classes and HTML layout to all-builditems.

**Comment by ritvij14** [comment]
@FroMage how can build these doc files individually? I did an `mvn clean install` in the `docs` folder but it didn't work. I am confused as to how should I locally generate the docs.

**Comment by FroMage** [comment]
The CSS file is in `docs/src/main/asciidoc/stylesheet/config.css`, and the docs are generated at `docs/target/generated-docs/`

**Comment by ritvij14** [comment]
@FroMage thanks for the help. I went through all these files, and I found that since the `quarkusbuilditemdoc.java` is jbang script, its a lot different from the `AllConfigGenerator.java` so would the issue be solved if we create a new file for building item docs, which follows along the lines of how config generator is written? Or do we have to solve it differently using JBang only?
As I saw in the HTML files as well, `all-config.html` gets all content from the Java file only, and the `all-build-items.html` has all its contents inside the HTML file.

**Comment by gastaldi** [comment]
It's fine to have something similar to AllConfigGenerator if you can do it. The reason I chose to write in JBang is because I found no way to do that with the ConfigGenerator because BuildItems do not have a marker annotation to trigger the annotation processor, and because it aggregates all build items from all modules

**Comment by FroMage** [comment]
You can keep the jbang script, that's not an issue. IMO most of the work is just going to be tweaking the HTML output  so that it uses the same classes as the config page.

**Comment by ritvij14** [comment]
Hmm alright understood, I will dif into the JBang script and see what can be done. Thanks for the help!
