### ISSUE TITLE
Additional Manifest entries via POM

### ISSUE THREAD

**Issue by rober710** [quarkusio/quarkus#12889]
**Description**
This is related to https://github.com/quarkusio/quarkus/issues/5023 .
I have configured my project to generate a fat jar via application.properties, but in my pom, I have configured the [build number maven plugin](https://www.mojohaus.org/buildnumber-maven-plugin/usage.html) to get the commit ID and the branch the jar is being built from. In the jar plugin's configuration, I have the following:
```
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${jar-plugin.version}</version>
        <configuration>
          <archive>
            <manifestEntries>
              <Git-Commit-Id>${buildNumber}</Git-Commit-Id>
              <Git-Branch>${scmBranch}</Git-Branch>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
```
which adds those two entries to the original jar's manifest, but since the quarkus plugin doesn't use the assembly plugin to create the fat jar, the one that's created doesn't have these entries in the manifest. Would it be possible to add something similar to Quarkus plugin?

I tried doing something similar to what I saw in the [PR](https://github.com/quarkusio/quarkus/pull/8199#pullrequestreview-382448510):
```
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <configuration>
          <archive>
            <manifest>
              <manifestSections>
                <manifestSection>
                  <name>Test Information</name>
                  <manifestEntries>
                    <manifestEntry>
                      <entryKey>Test-Key-1</entryKey>
                      <entryValue>Test Value 1</entryValue>
                    </manifestEntry>
                  </manifestEntries>
                </manifestSection>
              </manifestSections>
            </manifest>
          </archive>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
but that didn't work. Checking the source, the manifestSections field of the ManifestConfig class is not exported as a configuration parameter.

Would it be possible to implement this, and have the chance to do this in Gradle too?

**Comment by andrewazores** [comment]
https://quarkus.io/guides/maven-tooling#quarkus-package-pkg-package-config_quarkus.package.manifest.manifest-sections-manifest-sections

You can use `quarkus.package.manifest.manifest-sections` if your scenario allows for the manifest attributes to be added to a named section within the MANIFEST.MF. I haven't tried specifying this in the pom, but it works in application.properties.

I'm looking for a solution to add arbitrary attributes to the main/unnamed section of the manifest however, so +1 on this issue I think.

**Comment by h2cone** [comment]
+1

Extracting META-INF/MANIFEST.MF of Uber-Jar shows that the Class-Path is empty. I want to add additional JAR files and directories to the class path, so I can only use `jar` to modify the manifest file.

**Comment by gsmet** [comment]
@glefloch would you be interested in having a look at this? I think it probably warrants a discussion with @aloubyansky before implementing anything.

**Comment by glefloch** [comment]
Sure, I will check with @aloubyansky what is the best strategy here to implement that on both maven and gradle.

**Comment by glefloch** [comment]
@aloubyansky, I was thinking of collecting those attributes directly from the `jar` task or from the `maven-jar-plugin`. Then in the `quarkusBuild` task / `Build` mojo, leverage the `quarkus.package.manifest.manifest-sections` property and set that in the 

```
QuarkusBootstrap.builder()
                .setBuildSystemProperties(effectiveProperties)
```

WDYT of that?

**Comment by aloubyansky** [comment]
That could work. Be careful not to ignore `quarkus.package.manifest.manifest-sections` defined in the application.properties (if contains one).

**Comment by gsmet** [comment]
But aren't we bypassing the maven-jar-plugin entirely? If so I don't think it would make sense to configure the manifest entries there.

Note that I might have missed something obvious to both of you so be patient with me :).

**Comment by aloubyansky** [comment]
Yes, we are. Perhaps, it'd be a better option to copy the relevant config to the `quarkus-maven-plugin`.

**Comment by gsmet** [comment]
Yes, my thought exactly.

**Comment by glefloch** [comment]
Ok I was thinking of it this way as we do something similar for compiler args, but in this case this is not used, I will add those property directly to plugins :)

**Comment by glefloch** [comment]
Using the quarkus property, we can only configure specific manifest section and not the main section. Is there a reason why ? or should we be able to add attributes to the main section too?
