### ISSUE TITLE
Have the CLI tool download and start a quarkus:dev ready docker Container 

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1288]
Map the local dir to the container one
Ask for the Pom info 
Then start the container in :Dev mode
And people can start editing right away with no JVM not Maven install.

**Comment by vorburger** [comment]
@emmanuelbernard I'm implementing this sort of as a side effect of my investigation re #1390 ...

https://github.com/quarkusio/quarkus/compare/master...vorburger:issue-1390_dev-container

Not quite working just yet, again due to #1449.

**Comment by stuartwdouglas** [comment]
Is this still an approach we want to take? It seems like JBang would be a better fit for this use case.

**Comment by maxandersen** [comment]
yeah - this specific usecase jbang handles cleaner imo. and does not require docker.
