### ISSUE TITLE
Disabled proactive authentication and @TestSecurity does not work

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#12882]
**Describe the bug**
My quarkus app uses OIDC (type=web-app) with `quarkus.http.auth.proactive=false` to disable the proactive authentication witch causes unit-tests to fail because the annotation `@TestSecurity(user = "myuser")` does not work any more. `SecurityContext.getUserPrincipal()` returns `null`.

If setting `quarkus.http.auth.proactive=true` the unit-tests works fine.

**Expected behavior**
The annotation `@TestSecurity(user = "myuser")` works in combination with `quarkus.http.auth.proactive=false`

**Actual behavior**
`@TestSecurity(user = "myuser")` in combination with `quarkus.http.auth.proactive=false` causes `SecurityContext.getUserPrincipal()` returns `null`.

**To Reproduce**

1. Quarkus project with JAX-RS Rest-Endpoint and OIDC
2. Protected endpoint (with `@Authenticated`) uses `SecurityContext.getUserPrincipal()` 
3. Unit-Test tests the endpoint using the annotation `@TestSecurity(user = "myuser")`

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.9.0.Final

**Comment by sberyozkin** [comment]
CC @stuartwdouglas
