### ISSUE TITLE
ReactivePG and Jandex problem during mvn install

### ISSUE THREAD

**Issue by cssrumi** [quarkusio/quarkus#12918]
Hi,

I found that after migration from 1.8.x to 1.9.0.Final it's impossible to build (mvn install/package) library, that use quarkus-reactive-pg-client and bean indexing with jandex (jandex-maven-plugin). I tried it with jandex version 1.0.7 and 1.0.8.

Same thing happen during integration tests with @QuarkusTest. 

Error message:
`[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 5 deployment problems: 
[ERROR] [1] Unsatisfied dependency for type io.vertx.mutiny.pgclient.PgPool and qualifiers [@Default]`

Every of that 5 deployment problems is related to same PgPool.

Code to reproduce: https://github.com/cssrumi/pgjandexbug
Command to reproduce: mvn install

PS. I'm using Quarkus since 1.2.1 and that problem never happen before.
PS2. Sorry for my lack of focus on english lessons :)

**Comment by cssrumi** [comment]
I verified that same problem occur during quarkus:dev

**Comment by ghokun** [comment]
Problem goes away if you add an application.properties file containing:
```
quarkus.datasource.db-kind=postgresql
```

**Comment by cssrumi** [comment]
Thx a lot :)
It helped.

**Comment by gsmet** [comment]
I will have a look to be sure we understand the issue.

**Comment by gsmet** [comment]
Ok so this is due to the old datasource configuration being removed.

Before 1.9, you had a default reactive datasource created even if you hadn't specified any configuration properties. You now need to configure things to get a reactive datasource.
