### ISSUE TITLE
 Jsonb: @JsonbTransient does not work on abstract classes.

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#12926]
@JsonbTransient work when used on interface, but not on abstract class.
This prevent to hide fields on an abstract class views with blaze. 
It's working fine with Jackson.
```
@EntityView(TheEntity.class)
public abstract class TheView {
    public TheView(){

    }
    @IdMapping
    public abstract long getId();
    @JsonbTransient
    public abstract String getField1();

    public abstract String getField2();
}
```
when used in a Jax-RS Resource, this return:
```
{"field1":"aaa","field2":"bbb", "id":"1"}
```

**Comment by rmanibus** [comment]
reproducer: 

https://github.com/rmanibus/quarkus_12926

**Comment by geoand** [comment]
Thanks for reporting, but I am pretty sure this is a Yasson specific issue, so it would be best if you reported it to https://github.com/eclipse-ee4j/yasson
