### ISSUE TITLE
Unable to discover any JSON Deserializer implementations on the classpath

### ISSUE THREAD

**Issue by rafaelbarioni** [quarkusio/quarkus#12948]
Hello everyone.

I´m converting my lambdas here to use quarkus in native mode and I´m having issues to decode my JWT token.

I have this code in a separated maven dependency, which deals with JWT:
``` 
public static TokenInfo getPayload(String jwt) {
	try {

		TokenInfo payload = new TokenInfo();
		Claims claims = Jwts.parser().setSigningKey(Base64.getEncoder().encode(<MY_KEY>))
				.parseClaimsJws(jwt).getBody();
		final ObjectMapper mapper =
				new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		payload = mapper.convertValue(claims.get("info"), TokenInfo.class);
		return payload;
	} catch (MalformedJwtException | SignatureException e) {
		throw new UnauthorizedException(Mensagens.INVALID_AUTHORIZATION);
	}
}
```
and it has these dependencies:

```
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.10.7</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.10.7</version>
		</dependency>
```

When I try to call this method in my lambda, I get this exception:

> 2020-10-23 19:08:17,500 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread) Failed to run lambda: java.lang.IllegalStateException: Unable to discover any JSON Deserializer implementations on the classpath.
at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.locate(RuntimeClasspathDeserializerLocator.java:38)
at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.getInstance(RuntimeClasspathDeserializerLocator.java:21)
at io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator.getInstance(RuntimeClasspathDeserializerLocator.java:12)
at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:227)
at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:513)
at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:573)
at br.com.assertiva.commons.util.JwtUtils.getPayload(JwtUtils.java:60) 

I tried to add quarkus-rest-client-jackson, quarkus-rest-client-jsonb to my project, but no luck.

I´m building my image with:
mvn clean package -Pnative -Dquarkus.native.container-build=true

My application.properties:

quarkus.native.additional-build-args=--allow-incomplete-classpath\,--enable-all-security-services\,-H:DynamicProxyConfigurationFiles=proxy-config.json\,-H:ReflectionConfigurationFiles=reflection-config.json\,-H:ResourceConfigurationFiles=resource-config.json\,--report-unsupported-elements-at-runtime

quarkus.index-dependency.commons.group-id=br.com.assertiva
quarkus.index-dependency.commons.artifact-id=commons

quarkus.dynamodb.sync-client.type=apache

My reflection-config.json file:
```
[
	{
		"name": "io.jsonwebtoken.impl.DefaultJwtParser",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "io.jsonwebtoken.impl.io.RuntimeClasspathDeserializerLocator",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "java.lang.String",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "com.amazonaws.auth.AWS4Signer",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "com.amazonaws.services.s3.internal.AWSS3V4Signer",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "org.apache.commons.logging.impl.LogFactoryImpl",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "org.apache.commons.logging.LogFactory",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "org.apache.commons.logging.impl.SimpleLog",
		"allDeclaredConstructors": true,
		"allPublicConstructors": true,
		"allDeclaredMethods": true,
		"allPublicMethods": true,
		"allDeclaredClasses": true,
		"allPublicClasses": true
	},
	{
		"name": "com.amazonaws.partitions.model.Partitions",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	},
	{
		"name": "com.amazonaws.partitions.model.Partition",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	},
	{
		"name": "com.amazonaws.partitions.model.Endpoint",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	},
	{
		"name": "com.amazonaws.partitions.model.Region",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	},
	{
		"name": "com.amazonaws.partitions.model.Service",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	},
	{
		"name": "com.amazonaws.partitions.model.CredentialScope",
		"allPublicMethods": true,
		"allDeclaredConstructors": true
	}
]
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: jdk11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.9.0-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn

Any suggestions about this?

**Comment by andersonbfn** [comment]
I'm having the same throuble on quarkus native running on k8s pods using the same dependencies from `io.jsonwebtoken`. Thank's in advance for any feedback.

**Comment by geoand** [comment]
Have you tried registering `io.jsonwebtoken.io.JacksonDeserializer` for reflection?

**Comment by brahimk** [comment]
Hello,

Any feedback on thie issues please?

Thanks.

**Comment by geoand** [comment]
Does anyone have an example project they can share?

**Comment by metaprice** [comment]
Any news here?

**Comment by cgaugel** [comment]
Any news here? Having the same problem...

**Comment by geoand** [comment]
If someone attaches a sample project exhibiting the problem in question, I can take a look

**Comment by geoand** [comment]
Closing as we never got a reproducer
