### ISSUE TITLE
Vertx-Web: Route with Failure Handling not working

### ISSUE THREAD

**Issue by Serkan80** [quarkusio/quarkus#12959]
**Describe the bug**
I try to do failure handling with Reactive Routes, see code below:

`

    public class ExceptionHandler {

    static final Logger log = LoggerFactory.getLogger(ExceptionHandler.class);

    @Route(type = HandlerType.FAILURE, produces = "application/json")
    public void exceptions(ApplicationException e, HttpServerResponse res) {
        log.info("In exception handler...");
        res.setStatusCode(e.statusCode).end(e.getMessage());
    }

    @Route(type = HandlerType.FAILURE, produces = "application/json")
    public void exceptions(ConstraintViolationException e, HttpServerResponse res) {
        log.info("In exception handler...");
        res.setStatusCode(400).end(handler ->
                e.getConstraintViolations().stream()
                        .map(err -> String.format("%s: %s", err.getPropertyPath().toString(), err.getMessage()))
                        .collect(Collectors.joining("\n"))

        );
    }

`

See also on [Zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/vertx.20web.20failure.20handling.20throws.20error).

**Expected behavior**
It should work according to the [Reactive Routes guide](https://quarkus.io/guides/reactive-routes).

**Actual behavior**
I get this exception:

> Caused by: java.lang.IllegalStateException: No parameter injector found for parameter 0 of route method void exceptions(javax.validation.ConstraintViolationException e, io.vertx.ext.web.RoutingContext ctx) declared on CLASS bean [types=[java.lang.Object, com.acme.redis.service.exceptions.ExceptionHandler], qualifiers=[@Default, @Any], target=com.acme.redis.service.exceptions.ExceptionFilter]
    at io.quarkus.vertx.web.deployment.VertxWebProcessor.validateRouteMethod(VertxWebProcessor.java:419)
    at io.quarkus.vertx.web.deployment.VertxWebProcessor.validateBeanDeployment(VertxWebProcessor.java:154)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
    at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
    at java.base/java.lang.Thread.run(Thread.java:834)
    at org.jboss.threads.JBossThread.run(JBossThread.java:479)

**Environment: **
 - JDK 11
 - Quarkus 1.8.3.Final
 - Maven 3.6.3

**Comment by mkouba** [comment]
Closing - failure handlers can only inject exception parameters in 1.9.0+.

**Comment by Serkan80** [comment]
@mkouba @gsmet  I'm testing this in Quarkus 1.9.2.Final and it still doesn't work. The application starts now without any exceptions, but when I throw an error it doesn't get handled from the failure handling route.

I throw my error as follows:

`
   return this.client.hget(AGGREGATE_TABLE, id)
                .onItem().ifNotNull().transform(res -> res.toString())
                .onItem().ifNull().failWith(new NotFoundException("TemperatureAggregate(id=%s) not found", id));
`

`
  public class ApplicationException extends RuntimeException {
    public int status;

    public ApplicationException(int status, String message, Object... args) {
        super(format(message, args));
        this.status = status;
    }
}
`

`
  public class NotFoundException extends ApplicationException {

    public NotFoundException(String msg, Object... args) {
        super(404, msg, args);
    }
 }

`

`
   import io.vertx.core.http.HttpServerResponse;
   ...

    @Route(type = Route.HandlerType.FAILURE, produces = "application/json")
    public void handleApplicationExceptions(NotFoundException e, HttpServerResponse response) {
        log.debug("In exceptionmapper");
        response.setStatusCode(e.status).end(e.getMessage());
    }

`

**Comment by mkouba** [comment]
> I throw my error as follows:

@Serkan80 This merely shows the code that produces a failed `Multi`, right? Do you return this `Multi` from a route method? I need to check what the generated code looks like. @cescoffier may know off the top of his head ;-).

**Comment by Serkan80** [comment]
@mkouba No, I'm throwing this error just from a regular class:


 `
   public Uni<String> getTemperatureAggregateByStationId(String id) {
        return this.client.hget(AGGREGATE_TABLE, id)
                .onItem().ifNotNull().transform(res -> res.toString())
                .onItem().ifNull().failWith(new NotFoundException("TemperatureAggregate(id=%s) not found", id));
     }

`

And this method is called from the route as follows:

`
   
  @Route(path = "/:id", methods = HttpMethod.GET)
    public Uni<String> getTemperatureByStationId(@Param("id") String id) {
        return this.processor.getTemperatureAggregateByStationId(id);
    }

`

**Comment by mkouba** [comment]
Ah, I can see the problem now. Our example in the docs is wrong because if no `Route#path()` is specified for a route the method name is used instead (this behavior is mentioned in the docs and also in `@Route` javadoc). So the correct solution is to use `@Route(path = "/*", type = Route.HandlerType.FAILURE, produces = "application/json")`...

**Comment by mkouba** [comment]
Maybe we should change this behavior for failure handlers where the method name is not really relevant? It should be an easy fix. @cescoffier WDYT?

**Comment by Serkan80** [comment]
> Ah, I can see the problem now. Our example in the docs is wrong because if no `Route#path()` is specified for a route the method name is used instead (this behavior is mentioned in the docs and also in `@Route` javadoc). So the correct solution is to use `@Route(path = "/*", type = Route.HandlerType.FAILURE, produces = "application/json")`...

OK, now it works. 

Can't you just make the path default to "/*" ? Does it make sense to provide a name to the path when exception handling ?

**Comment by mkouba** [comment]
> Can't you just make the path default to "/*" ? Does it make sense to provide a name to the path when exception handling ?

Sometimes it does make sense to specify a path for a failure handler but if no path is specified it should match all requests (as I mentioned in https://github.com/quarkusio/quarkus/issues/12959#issuecomment-724653904).
