### ISSUE TITLE
Vertx-Web: RouteBase path + Route path combined not working well

### ISSUE THREAD

**Issue by Serkan80** [quarkusio/quarkus#12965]
**Describe the bug**
I have the following code:

```

    @RouteBase(path = "/books", produces = "application/json")
    public class BookService {

    @Inject
    BookRepository repository;

    @Route(path = "/", methods = HttpMethod.POST, produces = "application/json")
    public Uni<Book> findAll() {
        return this.repository.findAll();
    }
    }

```

**Expected behavior**
When I call this endpoint as follows:

Example 1:
`
http :8080/books
`

or as:

Example 2:

`
http :8080/books/
`

In both cases it should work.

**Actual behavior**

Example 1, returns an error saying that the endpoint doesn't exist, because of a missing '/' at the end of the url, see below.
Example 2, works.

>   404 - Resource Not Found
No resources discovered
Reactive Routes
>- GET: books/
>- BookService#findAll()

**Environment (please complete the following information):**
 - JDK 11
 - Quarkus 1.8.3.Final
 - Maven 3.6.3

**Comment by geoand** [comment]
cc @mkouba @cescoffier

**Comment by Solido** [comment]
Got myself bite too !
This block the use of RouteBase as for now.
Thx

**Comment by cescoffier** [comment]
There is a workaround. The `@Route` annotation is repeatable, so you can declare it twice on the same method.
