### ISSUE TITLE
Support @TestProfile in native mode

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#12974]
The [javadoc of `NativeTestExtension.ensureNoTestProfile()`](https://github.com/quarkusio/quarkus/blob/5f5fe32587ea15f04fd05891c9286d80f0753c19/test-framework/junit5/src/main/java/io/quarkus/test/junit/NativeTestExtension.java#L115-L122) says

> We don't support `@link TestProfile` in native tests because we don't want to incur the native binary rebuild cost which is very high.

However, we'd need this in Camel Quarkus and Camel K. 

Because most of our config properties are runtime (rather than build time), we are not afraid of the native binary rebuild costs. Even in cases where a native rebuild would be required, we'd prefer Quarkus tooling to do it out of the box, instead of us having to maintain workarounds (multiple tests projects, or per-test-profile Maven profiles).

I'd be ready to work on this unless the Quarkus team is strongly against this?

cc @lburgazzoli @jamesnetherton

**Comment by geoand** [comment]
Just to be clear, you need to rebuild in order to have the ability to redefine build time properties?

**Comment by lburgazzoli** [comment]
As far as I know, it is not possible to override a build time only property at runtime so if any of the  overridden config values provided by QuarkusTestProfile is a build time only property, I think yes a rebuild is required

**Comment by geoand** [comment]
Yes that is correct. I am just making sure that you guys need to override build time properties.

I am +0 for this, but as it will make Camel's life easier, I don't have any objections.

@stuartwdouglas @gsmet WDYT?

**Comment by lburgazzoli** [comment]
Most of the time I think we don't need to override build time properties however it may happen. 
I'm fine of making that explicit if needed (i.e. by adding an additional option that says that the native image need to be rebuilt)
