### ISSUE TITLE
remove redundant configuration loading for live dev mode

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1298]
Currently `mvn quarkus:dev` only reads properties from "META-INF/microprofile-config.properties".  The maven plugin does not look for properties in "application.properties", so any properties defined in "application.properties" will not be loaded in live dev mode

**Comment by geoand** [comment]
To tell you the truth I don't know that part of the code is supposed to do.

But the files to be config to be checked for change are consulted at:
https://github.com/quarkusio/quarkus/blob/master/core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java#L149
https://github.com/quarkusio/quarkus/blob/master/core/devmode/src/main/java/io/quarkus/dev/HotDeploymentConfigFileBuildStep.java#L35

Do you have an example that you ran and the config change did not get picked up? The simple examples I tried worked fine

**Comment by johnaohara** [comment]
I haven't run an example, I was trawling through the code and noticed that it was not searching for application.properties. I will double check if this causes an issue somewhere

**Comment by geoand** [comment]
Cool, thanks

**Comment by johnaohara** [comment]
@geoand I have just spoken to @stuartwdouglas . The code at https://github.com/quarkusio/quarkus/blob/master/core/devmode/src/main/java/io/quarkus/dev/DevModeMain.java#L62  might be redundant. I am testing a patch now

**Comment by geoand** [comment]
Sounds good :)
