### ISSUE TITLE
Blocking routes added by build steps may execute in a different worker thread even though the request is already running in a worker thread

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#12990]
**Describe the bug**
Using `quarkus-health` as an example, a route is added here https://github.com/quarkusio/quarkus/blob/7199fc41bf328086483f14c67c6c9243d3dd51e0/extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java#L183.

If some application defines a filter that dispatches the request to a worker thread the route created by `quarkus-health` will end up being executed in another thread, whereas I think it should check first if the request is already running in a worker thread to then dispatch accordingly.

**Expected behavior**
Execute blocking code in a worker thread only if the request is running in an IO thread.

**Actual behavior**
Routers created as blocking are always dispatching to a new worker thread even though the request is already being executed in a worker thread.

**Comment by pedroigor** [comment]
To give some more context here, in Keycloak we have a top-level filter that intercepts every single request.

One of the things that this filter does is to dispatch requests to worker threads using `RoutingContext.vertx().executeBlocking`.

When we add `quarkus-health` extension, the `SmallRyeHealthHandlerBase` is executed in a different worker thread initiating at `io.vertx.ext.web.impl.BlockingHandlerDecorator`. Whereas it should first check if the route is already running in a worker thread first.

I'm not sure if this is a bug in health but Vert.x, or maybe something we can do differently on our side. Or if this is a situation that Quarkus should handle.

I know we have some places using `BlockingOperationControl` to decide whether or not it is already running in a worker thread. But the problem is that `BlockingHandlerDecorator` is from Vert.x.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20453 should have fixed this. If not, please reopen
