### ISSUE TITLE
Wrong variable expansion for custom configuration sources with high ordinal

### ISSUE THREAD

**Issue by paschm** [quarkusio/quarkus#12998]
**Describe the bug**
Providing a `ConfigSourceProvider` you can use custom configuration sources, see i. e. [guide](https://quarkus.io/guides/config#custom-configuration-sources) and the MP Config Spec. Using variable expressions within these sources and a "high" ordinal >= 5100, the variables won't be correctly expanded. I. e. `${foo.bar}` will be expanded to the string `"${foo.bar}"`. Apparently this seems to be a regression issues, as the expansion works with 1.8.3.Final, but not with 1.9.0.Final. 

**Expected behavior**
Varibles in custom configuration sources and ordinal >= 5100 get correctly expanded.

**Actual behavior**
Variable `${foo.bar}` get expanded to the string `"${foo.bar}"`.

**To Reproduce**
See attached maven [project](https://github.com/quarkusio/quarkus/files/5450615/code-with-quarkus.zip)

A custom configuration source ist provided by org.acme.config.MyConfigSourceProvider with ordinal `ConfigSource.DEFAULT_ORDINAL + 5000`. Within this source a property `application.greeting` with value `${application.greetingBase} foobar!` is defined. `ExampleResource` returns the value  `application.greeting`.

1. mvn test

[ERROR] Failures:
[ERROR]   ExampleResourceTest.testHelloEndpoint:19 1 expectation failed.
Response body doesn't match expectation.
Expected: is "oi foobar!"
  Actual: ${application.greetingBase} foobar!

Setting the ordinal of the custom configuration source to 1000 or using Quarkus 1.8.3.Final everything works fine.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.9.0.Final

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
This is because expansion is implemented with an ordinal and sorted with all the available sources, giving you the ability to actually have sources without expansion. We did use a high value (3800), which you obviously beat :)

Do you really require to use a higher ordinal or could you set a lower one to make sure that expansions is applied? Another solution is to register the `ExpressionConfigSourceInterceptor` with a higher ordinal in your application.

**Comment by paschm** [comment]
@radcortez Thank you for the answer. No, actually I don't need a config source with ordinal > 3800 and I already changed it to lower values for my custom config sources. But maybe this can be documented in the [guide](https://quarkus.io/guides/config#custom-configuration-sources) and / or something can be logged, if the value is exceeded? I was confused, as higher values worked till 1.8.3 and the "critical" ordinal 3800 is not really transparent and the resulting behaviour isn't really comprehensible.

**Comment by radcortez** [comment]
Yes, you are right. I've added https://github.com/smallrye/smallrye-config/issues/437 to follow up on this. Thanks!
