### ISSUE TITLE
Produces method is not call for each create request scope bean

### ISSUE THREAD

**Issue by xumk** [quarkusio/quarkus#13000]
**Describe the bug**
I am want to tweak created bean with help Depended bean.

My class for its:
```java
@Dependent
public class MyServerConfiguration {

    @Produces
    public MyService tracer(@Any Instance<MyService> instance, InjectionPoint injectionPoint) {
        int min = 100;
        int max = 200;
        int diff = max - min;
        Random random = new Random();

        Annotated annotated = injectionPoint.getAnnotated();
        final Context annotationContext = annotated.getAnnotation(Context.class);
        if (annotationContext == null) {
            throw new RuntimeException("Instance must be mark Context annotation");
        }
        final MyService myService = instance.select(annotationContext::qualifier).get();

        myService.setNumber(random.nextInt() + diff);
        myService.setName(annotationContext.name());

        return myService;
    }
}
```

**Expected behavior**
Methode `tracer` called for all request to my service.
**Actual behavior**
Methode `tracer` called only one for first request.
But I added `@RequestScoped` to my resource class, its is good work.

**To Reproduce**
simple project
[my-artifactId.tar.gz](https://github.com/quarkusio/quarkus/files/5451430/my-artifactId.tar.gz)

1. create class `@Produces public MyService tracer(@Any Instance<MyService> instance, InjectionPoint injectionPoint)` for tweak beans 
2. create annitaion for setting and qualifier
3. select bean in method `tracer` with help `final MyService myService = instance.select(annotationContext::qualifier).get();`
4. call set method bean
5. return bean 
6. call resource method used bean

**Configuration**
```properties
quarkus.http.port=8081

```

**Screenshots**
first call result:
![Снимок экрана от 2020-10-28 14-24-31](https://user-images.githubusercontent.com/14112305/97430022-524c0780-1929-11eb-9589-9c4a3ce91951.png)
second call result:
![Снимок экрана от 2020-10-28 14-24-23](https://user-images.githubusercontent.com/14112305/97430018-50824400-1929-11eb-8125-0c634d22356d.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux megaPk 4.15.0-122-generic #124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - java version: 11.0.7
 - Quarkus version: 1.6.1.Final and above
 - Build tool: mvnw

**Comment by geoand** [comment]
In Quarkus, JAX-RS resources are **not** request scoped by default, so this works as expected
