### ISSUE TITLE
Add support for encoded @ApplicationPath value for OpenLiberty

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#13007]
OpenLiberty requires support of encoding @ApplicationPath value, such as 
"@ApplicationPath("apppathrest%21")".  

This request was originally filed in RESTEasy.  The investigation of this
enhancement request determined that the code handling "routes" was based
in Quarkus code and Vertx classes  io.vertx.ext.web.impl.RouterImpl and 
io.vertx.ext.web.impl.RouteState.

A Quarkus based testcase, and the investigative information can be found in
https://issues.redhat.com/browse/RESTEASY-2744 Add support for encoded 
@ApplicationPath value

**Comment by geoand** [comment]
FWIW, we do support this in [Quarkus REST](https://github.com/quarkusio/quarkus/pull/12971)

**Comment by gastaldi** [comment]
Maybe it would be nice to have a `area/quarkus-rest` label to track issues that can be possibly fixed when Quarkus REST is available.

**Comment by geoand** [comment]
Was thinking the same

**Comment by rsearls** [comment]
outdated
