### ISSUE TITLE
Memory leak QuarkusClassLoader

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#13006]
The RESTEasy team was requested to run their integrations tests regularly
using Quarkus to help identify issues.  This testing has uncovered
a memory leak in Quarkus versions 1.9.0.Final.  A heapDump and analysis reports the following.

  331 instances of "io.quarkus.bootstram.classloading.QuarkusClassLoader" loaded
  by "sun.misc.Launcher$AppClassLoader @ 0x5d321e1e8" occupy 5,254,700,944 (83.85%)
  bytes.  These instances are referenced from on instance of "java.lang.Thread",
  loaded by "<system class loader>"

There are 441 tests in RESTEasy's integration-tests suite. Only 183 tests
run before memory is full.

The headDump is 8GB, to big to provide as an attachment.  I used Eclipse Memory Analyzer
to evaluation the headDump.

**To Reproduce**

Use this project to run the test suite.
https://github.com/rsearls/resteasy-quarkus-testsuite.git

1.   mvn clean initialize
2.   mvn test      or
      mvn test >> test.log 2>&1

NOTE: This project has been configured to force a heapDump by test, ContextProvidersTest,
     because heapDump settings as a system property and in maven were ignored.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   Linux localhost.localdomain 5.0.16-100.fc28.x86_64 #1 SMP Tue May 14 18:22:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
  java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
  1.9.0.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)

**Comment by geoand** [comment]
Thanks for reporting this.

We have fixed a few memory leaks in the [Quarkus REST](https://github.com/quarkusio/quarkus/pull/12971) PR. See for example these commits:
* https://github.com/quarkusio/quarkus/commit/1c5e6a995ab1a957278d261e168e5eafee83afe2
* https://github.com/quarkusio/quarkus/commit/8075df1616640d34043b806f6f9c0c56e9137d22
* https://github.com/quarkusio/quarkus/commit/7dcb69c357af44f247c4bd57abc25eb1474a456a
* https://github.com/quarkusio/quarkus/commit/5cadc80581c583a7bf634d9b16fb41c4115f969f
* https://github.com/quarkusio/quarkus/commit/7eca231fa3db86df3a548dbe89093441b1b534a0

**Comment by geoand** [comment]
The aforementioned commits have been in `master` for a while, so this can be closed
