### ISSUE TITLE
PrinterJob.lookupPrintServices() can't find printers in native mode

### ISSUE THREAD

**Issue by indalaterre** [quarkusio/quarkus#13017]
**Describe the bug**
PrinterJob.lookupPrintServices() can't find printers when runs in native mode. The method is invoked using a Runtime Recorder after the bean has been marked as Unremovable. If the app is run in JVM mode everything goes well

**Expected behavior**
PrinterJob.lookupPrintServices() returns results in both JVM and native mode

**Actual behavior**
PrinterJob.lookupPrintServices() returns results only in JVM

**To Reproduce**

Or attach an archive containing the reproducer to the issue.
[local-devices-client.zip](https://github.com/quarkusio/quarkus/files/5460067/local-devices-client.zip)

1. Run the application

**Environment (please complete the following information):**
 - Output of `java -version`: 11
- Platform: macOS
 - GraalVM version (if different from Java): 20.2.0
 - Quarkus version or git rev: 1.9.1-Final

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Thanks for reporting.

There likely isn't much Quarkus can do here, this is more of a GraalVM issue.

**Comment by dloiacono** [comment]
Seems that AWT is currently not supported on Substrate VM.

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaAWTSubstitutions.java#L39

**Comment by gastaldi** [comment]
Looks like the related issue is: https://github.com/oracle/graal/issues/2949

**Comment by machi1990** [comment]
> Looks like the related issue is: [oracle/graal#2949](https://github.com/oracle/graal/issues/2949)

Yes, I think we can close this as this is more like an upstream issue than anything Quarkus related.
