### ISSUE TITLE
Introduce a CDI bean which encapsulates the command-line arguments

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1302]
As a `List<String>` would be ideal.  Then users can inject & process them.

**Comment by mkouba** [comment]
Makes sense. Weld SE provides `@Inject @Parameters List<String> params` if started using `org.jboss.weld.environment.se.StartMain`.

**Comment by machi1990** [comment]
@mkouba I'd like to give this a shot.

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/7681.

This can now be achieved with the following piece of code:
```
@Inject
@CommandLineArguments
String[] args;
```
