### ISSUE TITLE
How to close the Quarkus application when the verticle deployment fails.

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#13033]
**Describe the bug**
I call `Quarkus.asyncExit()` but the process cannot be closed. Enter the following log. I want the process to end as expected without manual intervention. What should I do?

```
2020-10-30 21:59:27,823 DEBUG [io.qua.arc.impl] (Quarkus Main Thread) ArC DI container shut down
2020-10-30 21:59:27,834 INFO  [io.quarkus] (Quarkus Main Thread) Quarkus stopped in 0.053s
Quarkus application exited with code 0
Press Enter to restart or Ctrl + C to quit
```

thanks.

**Comment by gastaldi** [comment]
What Quarkus version are you using?

**Comment by aomsweet** [comment]
hi. @gastaldi 

Quarkus version: 1.9.0.Final

Run profile: dev

**Comment by geoand** [comment]
quarkus:dev doesn't shutdown completely, so this is expected behavior
