### ISSUE TITLE
Wrong inferring of metric names and metadata from annotations

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#1303]
With MP Metrics declared by annotations, the `absolute` attribute is ignored.
For example:
```
@Counted(monotonic = true, name = "counter1", absolute = true)
```
This will cause a registration of a metric named `example.quarkusmetrics.MainResource.counter1`, but after it is accessed due to a HTTP request, SmallRye interceptor will search for just `counter1`, so it will not be able to find the correct metric to increase.

**Comment by kenfinnigan** [comment]
Is this a bug in SmallRye?

**Comment by jmartisk** [comment]
No, this is a bug in Quarkus which eagerly initializes metrics at deployment, but initializes them under the wrong name.

**Comment by jmartisk** [comment]
I will try to come up with a solution, at at the same time add support for some other metric types that are missing as per https://github.com/quarkusio/quarkus/issues/1009

**Comment by jmartisk** [comment]
I believe the right solution here is to stop duplicating logic from SmallRye Metrics and let `io.smallrye.metrics.interceptors.MetricInterceptor` perform the registration of metrics. Quarkus is basically trying to register the metrics by itself, and the logic for that is incomplete.
