### ISSUE TITLE
JsonNode property not serialized correctly with RESTEasy JAX-RS

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#13043]
**Describe the bug**

REST endpoint returning a JsonNode object is not serialized as expected

````
    @GET
    @Path("/test")
    public Response get() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode json = mapper.readTree("{\"id\": \"132\", \"name\": \"Alice\"}");
        return Response.accepted(json).build();
    }
````

Instead of the expected JSON string as a response I´m always getting the response below

```

{
array: false,
bigDecimal: false,
bigInteger: false,
binary: false,
boolean: false,
containerNode: true,
double: false,
float: false,
floatingPointNumber: false,
int: false,
integralNumber: false,
long: false,
missingNode: false,
null: false,
number: false,
pojo: false,
short: false,
textual: false,
valueNode: false,
empty: false,
nodeType: "OBJECT",
object: true,
}
```

Used Quarkus version: 1.9.1.Final

Reproducer https://github.com/mklueh/quarkus-rest-json-node-not-serialized

**Comment by geoand** [comment]
Can you explain what the reasoning is for using `JsonNode` as a value for the response?
What's the benefit of doing so?

**Comment by mklueh** [comment]
> Can you explain what the reasoning is for using `JsonNode` as a value for the response?
> What's the benefit of doing so?

Hi @geoand ,

thanks for your response.

I´m not exactly sure anymore what I was trying to achieve at that time and I think it can be closed. 

Returning just the String itself will produce a response with a valid JSON anyway.

**Comment by geoand** [comment]
Understood, thanks
