### ISSUE TITLE
Dead link "https://quarkus.io/guides/security.adoc#testing-security" in documentation

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#13047]
On page https://quarkus.io/guides/getting-started-testing in chapter 12. Testing security there is a dead link https://quarkus.io/guides/security.adoc#testing-security

**Comment by machi1990** [comment]
Good catch @mklueh I think it should point to this page https://quarkus.io/guides/security-testing. Do you want to provide a PR to fix it? Thanks.

**Comment by mklueh** [comment]
@machi1990 It seems to be already fixed for a while on master https://github.com/mklueh/quarkus/commit/f84f386b585b9663a3ab8340ac1ea6cef77aaad9#diff-736ad6c4de04577ecfa48a1d44d6acaebb7ceac683ab1f51bdf30c7add9fe31c

How often is the documentation website getting deployed?

**Comment by machi1990** [comment]
> @machi1990 It seems to be already fixed for a while on master [f84f386#diff-736ad6c4de04577ecfa48a1d44d6acaebb7ceac683ab1f51bdf30c7add9fe31c](https://github.com/quarkusio/quarkus/commit/f84f386b585b9663a3ab8340ac1ea6cef77aaad9#diff-736ad6c4de04577ecfa48a1d44d6acaebb7ceac683ab1f51bdf30c7add9fe31c)
>

Ah right. I wasn't near my machine to actually verify it before proposing that you provide a fix. 
 
> How often is the documentation website getting deployed?

/cc @gsmet

**Comment by gsmet** [comment]
Yeah I haven't backported this change because it also changed things related to new features introduced in 1.10.

I have fixed the dead link in 1.9 here: https://github.com/quarkusio/quarkus/pull/13074

1.9.2.Final should be released soon enough.

**Comment by gsmet** [comment]
Thanks for taking the time to report it!

**Comment by sberyozkin** [comment]
Not sure why closing #13074 did not close this issue, or, Guillaume, would you like to keep it open till the release is out ? (I closed one other issue today after the merged PR kept that issue open, but now I'm not sure :-) )

**Comment by machi1990** [comment]
> Not sure why closing #13074 did not close this issue, or, Guillaume, would you like to keep it open till the release is out ? 

I was asking myself a similar question. I'd assume so, 1.9.2.Final should be out by tomorrow (which will include website updates), I suppose from there this issue can be closed.

**Comment by gsmet** [comment]
Yeah, this can be closed.
