### ISSUE TITLE
keycloak-admin-client extension imposes quarkus-oidc extension properties

### ISSUE THREAD

**Issue by Erfankam** [quarkusio/quarkus#13056]
**Describe the bug**
Recently I used Quarkus version 1.4.2 in a multi module maven project. I had a module use quarkus-keycloak-admin-client that administrate Keycloak instance and work properly without any problem.
After upgrade to version Quarkus 1.6.1, I got some errors about needed properties like auth-server-url that needed for quarkus-oidc extension and I have no enabled quarkus-oidc extension.

**Expected behavior**
I expected after upgrade, I dont need any auth-server-url or other new properties for quarkus-oidc.

**Actual behavior**
In new versions after 1.4.2, if you have enable quarkus-keycloak-admin-client, you must fill quarkus-oidc properties too that is unwanted.

**To Reproduce**

In version 1.6.1 and later, enable just qurarkus-keycloak-admin-client extension.

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@Erfankam That module has long been gone,  `quarkus-oidc` has to be used, there was a message sent to the Quarkus forum and the migration notes updated

**Comment by sberyozkin** [comment]
@Erfankam Sorry, should've added some more context info. The decision to move to `quarkus-oidc` has been done in complete agreement with the Keycloak experts, with the 2 main reasons being: 1. Portability 2. Reactive security support on top of Vert.x
HTH

**Comment by sberyozkin** [comment]
@Erfankam I've got confused, reopening it, thanks to Guillaume as well

**Comment by sberyozkin** [comment]
@aloubyansky Hi Alexey, this is a [PR](https://github.com/quarkusio/quarkus/commit/ce8f172629636f7fb6b608f04fbb54a03f6afb88#diff-bb89edaddfe733219ecaec40168e84e8efc8da0c3122128c1541bc6bc534e2f1) which introduced the dependency on `quarkus-oidc`, Indeed, it is only `quarkus-keycloak-authorization` which may need it, `quarkus-keycloak-admin-client` is totally independent. Can you please revert only the change to `keycloak-admin-client/deployment/pom.xml` ?

**Comment by aloubyansky** [comment]
@sberyozkin just to clarify, if i add `quarkus-keycloak-admin-client` then `quarkus-oidc` will be expected among the runtime dependencies but `quarkus-oidc-deployment` should not be present at build time?

**Comment by gsmet** [comment]
Hmmm, as said on Zulip, I don't understand why we depend on the runtime `quarkus-oidc` artifact in `keycloak-admin-client`?

What's the reason for this?

**Comment by sberyozkin** [comment]
@aloubyansky We just don't need `quarkus-oidc` for `quarkus-keycloak-admin-client`, `quarkus-keycloak-admin-client` is unrelated to what `quarkus-oidc` does, only `quarkus-keycloak-authorization` is.

`quarkus-keycloak-admin-client` is only about administering Keycloak. `quarkus-oidc` and also `quarkus-keycloak-authorization` - are about protecting Quarkus endpoints without having any relationship to `quarkus-keycloak-admin-client`.

Does it clarify it ? Thanks

**Comment by sberyozkin** [comment]
It can be a bit confusing, I was actually planning to add some docs about this admin client to the keycloak authorization page, but I'm going to do a big enough docs updates soon, including the info about the admin client...

**Comment by sberyozkin** [comment]
For example, the application may be using some mutual TLS or Form authentication, nothing to do with `quarkus-oidc` but then the endpoint code may want to do something with Keycloak while processing the current request, which is where this admin client may be used, etc

**Comment by gsmet** [comment]
So we just need to remove the `quarkus-oidc` artifacts from both the runtime and the deployment artifacts of the Keycloak admin client?

Am I right?

**Comment by aloubyansky** [comment]
Sure, I didn't add a dependency on quarkus-oidc though. I added the dep on the quarkus-oidc-deployment given that the dep on quarkus-oidc was already there and it was incosistent.

**Comment by sberyozkin** [comment]
Hi @aloubyansky Thanks, it was there for some reasons in the original PR I guess but we've never noticed it (I'm only finding out it now :-) ) until your fix which was, as I see now, correct from your perspective, sorry about it all :-), and thanks for the PR

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/13065 will fix it.

I will backport it to 1.9.2.Final. Thanks for the report!

**Comment by sberyozkin** [comment]
This issue has now been fixed thanks to Alexey's PR and Guillaume spotting me closing this issue too early :-)

**Comment by Erfankam** [comment]
Thanks all for incorporating.
