### ISSUE TITLE
Support OpenJDK S2I

### ISSUE THREAD

**Issue by siamaksade** [quarkusio/quarkus#1305]
When Using OpenJDK S2I to build and deploy the examples on OpenShift, builds succeeds but the deployment fails.

```
oc new-app java~https://github.com/quarkusio/quarkus-quickstarts --context-dir=getting-started --name=quarkus
```
The deployment fails with the following error since it can't determine which JAR file to use:

```
ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 2 JARs found in /deployments (1 expected)
```

```
sh-4.2$ ls /deployments/ -l
total 40
drwxrwxr-x. 2 jboss root     6 Oct 17 22:12 data
-rw-r--r--. 1 jboss root 34673 Mar  7 13:49 quarkus-quickstart-1.0-SNAPSHOT-runner.jar
-rw-r--r--. 1 jboss root  3353 Mar  7 13:49 quarkus-quickstart-1.0-SNAPSHOT.jar
```

**Comment by stuartwdouglas** [comment]
Try `<uberJar>true</uberJar>` in the maven plugin config

**Comment by siamaksade** [comment]
Do any of the quickstarts have it enabled to test with OpenShift?

**Comment by cescoffier** [comment]
No, the quickstarts are not using uberjar. 

Note that with uberjar you will be in JVM mode and not in native mode.

**Comment by vorburger** [comment]
@siamaksade @cescoffier I may be able to help with this one - will try to do so tomorrow or Monday...

FYI, background: https://github.com/fabric8io-images/s2i/issues/123 is kind of related to this...

see also #304

**Comment by cescoffier** [comment]
@vorburger That would be awesome!

**Comment by geoand** [comment]
Weird.. I have actually tried binary builds for the ap4k extension and it works fine fabric8/s2i-java:2.3

**Comment by geoand** [comment]
Using the uberjar config should do the trick since in that case we add the `.original` sufficient to the original jar, thus leaving a single `.jar` file.

**Comment by siamaksade** [comment]
It would be valuable to add a quickstart for OpenShift similar to [getting-started-kubernetes](https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started-kubernetes) and with uberjar config enabled

**Comment by geoand** [comment]
@siamaksade Good idea. What would you like to see in that guide?

**Comment by cescoffier** [comment]
The last section of the kubernetes guide covers OpenShift.

**Comment by siamaksade** [comment]
@geoand a quickstart like getting-started-openshift that possibly has also fabric8 in it and one can just run `mvn fabric8:deploy`, and that would create a build on OpenShift using the OpenJDK builder image and deploys the Quarkus app. 

@cescoffier a guide is also would be great (https://github.com/quarkusio/quarkus/issues/1306). One wouldn't even find it currently on quarkus.io since item in the guides page is called "Deploying Applications on Kubernetes" rather than "Deploying Applications on Kubernetes/OpenShift". Furthremore, it needs instructions on how to use S2I for the build, in addition to the docker build strategy.

**Comment by geoand** [comment]
If we agree that it is needed, I can definitely add it

**Comment by vorburger** [comment]
> The last section of the kubernetes guide covers OpenShift.
> One wouldn't even find it currently on quarkus.io since item in the guides page is called "Deploying Applications on Kubernetes" rather than "Deploying Applications on Kubernetes/OpenShift". 

@siamaksade @cescoffier OK so let's fix (or further discuss) that point over in https://github.com/quarkusio/quarkusio.github.io/pull/124 ...

> It would be valuable to add a quickstart for OpenShift similar to getting-started-kubernetes and with uberjar config enabled

But if we can get `oc new-app` to work (original issue here; I'll look more into it next), then we may not actually need a separate getting-started-openshift anymore, no?

> @geoand a quickstart like getting-started-openshift that possibly has also fabric8 in it and one can just run mvn fabric8:deploy, and that would create a build on OpenShift using the OpenJDK builder image and deploys the Quarkus app.

@siamaksade @geoand I'm personally actually not sure if I am huge fan of `fabric8:deploy`, and whether we should be further promoting it here... IMHO "normal" S2I on-cluster build from Git repo is what one would want to do to biuld from source? And to push local not yet committed changes, there's no need for a Maven plugin, but simply `s2i build --copy .` should do? To be tested and documented, of course.

**Comment by siamaksade** [comment]
@vorburger sure. I understand your reluctance toward fabric8 :)

**Comment by vorburger** [comment]
> Try `<uberJar>true</uberJar>` in the maven plugin config

@stuartwdouglas @cescoffier see #1344 ...

I can see two solutions forward: a) I could do what's needed in the S2I Builder image to make it pick the (bigger) runner.jar over the (smaller) other normal JAR; or b) we could make the `quarkus-maven-plugin` produce only a single JAR? (Or do that `jar.original` rename thing but without bloating the runner JAR.)

Doing b) may be quicker, and would have the advantage that it would work for all S2I images (if I did the (a) solution it would be in https://github.com/fabric8io-images/s2i; the later the same would have to separately be redone over in https://github.com/jboss-container-images/openjdk because of https://github.com/fabric8io-images/s2i/issues/218).

> Note that with uberjar you will be in JVM mode and not in native mode.

Understood; this issue (for #1306) is about building a Quarkus app in OpenShift with S2i in JVM mode, not native. We'll tackle that later under #304.

**Comment by siamaksade** [comment]
(b) is preferable IMHO for reasons you mentioned. S2I builder image just sees 2 jars files and any heuristic for picking one would end up being the wrong choice for other use-cases.

**Comment by geoand** [comment]
I opened a PR for b) - let's see what people think

**Comment by cescoffier** [comment]
Didn’t read everything, but if we could about the fat jar in a container that would be great...

**Comment by cescoffier** [comment]
Can’t we have a builder that just take the regular runner and copy the libs?

**Comment by vorburger** [comment]
> Didn’t read everything, but if we could about the fat jar in a container that would be great...

can you elaborate a little bit on why?  I trust you have good reasons - I'd love to learn about them!

> Can’t we have a builder that just take the regular runner and copy the libs?

we could, but that requires work in the S2I base image(s; several!), they probably won't know that they have to copy lib/ ... it's doable, but what's the "justification" ? Using `uberJar` for producing a FAT JAR may be the best solution after all, for the short term. (And sorry for the back and forth!)

**Comment by cescoffier** [comment]
A docker container is already your packaging unit, creating another packaging unit in it is just looking for bad performances at startup time.

In addition, we are creating a huge top layer and every update is going to resync the whole "fat" layer, which we would avoid with using the runner (as it's only your application code and resources).

**Comment by vorburger** [comment]
https://github.com/quarkusio/quarkus-quickstarts/pull/81 now has a working (tested) proposed first version! That is still based on <uberJar>true. I'll document that now, and then separately and incrementally see if I can apply the idea from @gastaldi mentioned in #1345 to incrementally improve it.

**Comment by vorburger** [comment]
https://github.com/quarkusio/quarkus-quickstarts/pull/81 has gone through some iterations, and we now have something (hopefully) final (now without `<uberJar>true`). @siamaksade hope you're OK if we close this issue after https://github.com/quarkusio/quarkus-quickstarts/pull/81 and https://github.com/quarkusio/quarkus/pull/1353 have been merged?

**Comment by vorburger** [comment]
@siamaksade OK for you to close this issue, now that both https://github.com/quarkusio/quarkus-quickstarts/pull/81 as well as #1353 have been merged, and that https://github.com/quarkusio/quarkusio.github.io/pull/126 is hopefully about to be merged?

**Comment by cescoffier** [comment]
This can be closed. quarkusio/quarkusio.github.io#126 need a bit of rework (very very small ordering issue).
