### ISSUE TITLE
jna extension

### ISSUE THREAD

**Issue by dufoli** [quarkusio/quarkus#13054]
graalvm do not support jna in native mode.
But JNA seems to be mainly a classic jar wich use a jni small subset to load native lib.
So my point is that maybe it is doable to use substitution + reflection identification + proxy identification to have jna support.

reference:
https://github.com/java-native-access/jna

quick analyse:

proxy:
https://github.com/java-native-access/jna/search?q=newproxyinstance
- all interface inherited of com.sun.jna.Library  and Library  itself
- all interface inherited of com.sun.jna.Callback and Callback itself

Reflections:
- class.forName here:
https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/internal/ReflectionUtils.java
- all chain of embeded class with  a method with Modifier.NATIVE
- all class inherited of NativeMapped
- all class inherited of Number and Number
- class FFIType
- all class inherited of Structure and Structure

**Comment by gsmet** [comment]
I really don't think it's something we will want to do on our own.

@stuartwdouglas WDYT?

**Comment by dmlloyd** [comment]
It's doable. GraalVM have said "no" (https://github.com/oracle/graal/issues/673) but it should be possible as you say.

**Comment by gsmet** [comment]
@dufoli do you have a specific use case?

**Comment by dufoli** [comment]
Indeed it was because, I was thinking to the fact that java is not used compair to other language (python, ...) for machine learning. I discover deep java library and thinking that it can be awesome to have a neural network available on quarkus. I discover that there is someone who have work on it on https://github.com/apache/camel-quarkus/issues/1598
. But native support is not working before it depend of JNA.
And I think that native can boost performance which is very important for neural network. So that s why I create this issue for jna.

**Comment by stuartwdouglas** [comment]
Maybe we could have a Quarkiverse extension? I started one here just to play around with what would be involved: https://github.com/stuartwdouglas/quarkiverse-jna

Unfortunately it is not going to be as simple as just registering some stuff for reflection. The first error that pops up is https://github.com/java-native-access/jna/blob/54c84a34f82d1e8148b0ed3808b64db4d1f79df3/src/com/sun/jna/internal/ReflectionUtils.java#L76 where they are using reflection to hack into method handle internals.

It would be really cool to have neural networks on Quarkus, but at this stage it is hard to say how much work is involved.

**Comment by geoand** [comment]
Riding the AI / ML wave in Quarkus would be awesome, but at this point I really think that any work in that direction should probably be done outside of Quarkus core.

**Comment by JiriOndrusek** [comment]
I don't have enough experience with jna, but it seems, that some kind of usage with graalvm is possible and example is on the way - https://github.com/oracle/graal/issues/2261#issuecomment-703195020

**Comment by dufoli** [comment]
@gastaldi can you create jna on quarkiverse and clone repo from mine (dufoli/quarkiverse-jna) . it is now failing with 
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
...
quarkus-jna-integration-tests-0.1.0-SNAPSHOT-runner.o:(.data+0xaa0): undefined reference to `Java_java_util_prefs_FileSystemPreferences_chmod'
collect2: error: ld returned 1 exit status

but it seems to be related to graalvm bug:
https://github.com/oracle/graal/issues/2856 fixed in 20.3

**Comment by gastaldi** [comment]
@dufoli I created https://github.com/quarkiverse/quarkiverse-jna and gave you push access. Feel free to push your code there when it's usable. 

Thanks! Closing this issue now

**Comment by amahfouz1** [comment]
I have the full JNA configurations sample here if anyone is interested https://github.com/amahfouz1/jna-graalvm

**Comment by dufoli** [comment]
Me, I am working on extension but never finished it.

**Comment by amahfouz1** [comment]
@dufoli here you go the full configuration and it has been proven stable in production. Let me know if you need any help with the extension.

**Comment by GavinRay97** [comment]
@amahfouz1 Thank you for this!

If this works, maybe it's possible to merge it upstream into JNA itself?

All that JNA has to do is distribute these files in it's JAR, at the following location:
`META-INF/native-image/<group-id>/<artifact-id>`

And it should work for everyone. Would be awesome to have.
