### ISSUE TITLE
Add documentation for building with S2I on OpenShift

### ISSUE THREAD

**Issue by siamaksade** [quarkusio/quarkus#1306]
The current docs on the website use Dockerfile for building the app image:
https://quarkus.io/guides/kubernetes-guide

There should also be docs on how to use S2I and OpenJDK builder image for building non-native and possibly also native packaging on OpenShift.

**Comment by vorburger** [comment]
@siamaksade see also #304 for a prior discussion re. S2I building with `-Pnative` on OpenShift

**Comment by siamaksade** [comment]
We should probably separate the (1) S2I build on OpenJDK from (1) S2I build for a native binary. This issue is to track (1).  Will comment regarding (2) on #304

**Comment by vorburger** [comment]
> We should probably separate the (1) S2I build on OpenJDK from (1) S2I build for a native binary. This issue is to track (1). Will comment regarding (2) on #304

Sounds like a plan! I've updated the title of #304 accordingly (perhaps you'd like to do the same here and update the title of this issue with a "(non-native)" suffix).

**Comment by vorburger** [comment]
@siamaksade https://github.com/quarkusio/quarkus/pull/1353 and https://github.com/quarkusio/quarkusio.github.io/pull/126, based on the new https://github.com/quarkusio/quarkus-quickstarts/pull/81, will provide this documentation.
