### ISSUE TITLE
OIDC not appending X-Forwarded-Prefix to redirect_uri

### ISSUE THREAD

**Issue by canidae** [quarkusio/quarkus#13062]
**Describe the bug**
OIDC `redirect_uri` doesn't seem to honor `X-Forwarded-*` headers, when configuring the app as explained on these two sites:
- https://quarkus.io/guides/security-openid-connect-web-authentication#running-behind-a-reverse-proxy
- https://quarkus.io/guides/vertx#reverse-proxy

_Setup:_
Proxy (Traefik): docker.example.com
Quarkus-app: Internal (Docker) network, listening on `:8080/`. Traefik routes docker.example.com/app to this app.
OIDC (Keycloak): oidc.example.com

The `X-Forwarded-Prefix` will not be appended to the `redirect_uri` passed to the OIDC server:
`https://docker.example.com/app` -> `302 location: https://oidc.example.com/auth/realms/ExampleRealm/protocol/openid-connect/auth?redirect_uri=https%3A%2F%2Fdocker.example.com%2F&state=...`
This causes the user to be redirected to `https://docker.example.com/` after authenticating, instead of the expected `https://docker.example.com/app`.

Replacing Quarkus application with an echo service reveals that headers are correctly set:
```
x-forwarded-for: "10.0.0.2"
x-forwarded-host: "docker.example.com"
x-forwarded-port: "443"
x-forwarded-prefix: "/app"
x-forwarded-proto: "https"
```

**Workaround**
Setting `quarkus.http.root-path=/app` will make the `redirect_uri` sent to OIDC correct, but it's not an entirely satisfactory solution as you may want to host the app at multiple locations at the same time, like `https://app.example.com/` (without trailing `/app`) and `https://docker.example.com/app`. You'll also have to keep both app configuration and proxy configuration in sync.

There is a `quarkus.oidc.authentication.redirect-path`, but this will not solve the issue either. While the user initially will be redirected to `https://docker.example.com/app`, a later request directs the user to `https://docker.example.com/`.

**To Reproduce**
Unfortunately I don't have a setup I can share.

**Configuration**
```properties
quarkus.oidc.application-type=hybrid
quarkus.http.cors=true
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-prefix=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.allow-forwarded=true
quarkus.oidc.auth-server-url=https://oidc.example.com/auth/realms/ExampleRealm
quarkus.oidc.authentication.force-redirect-https-scheme=true
```

**Environment:**
 - Quarkus version or git rev: 1.9.0

**Comment by sberyozkin** [comment]
The fix is not complete
