### ISSUE TITLE
Testcontainers not working as expected with QuarkusTest

### ISSUE THREAD

**Issue by dinabogdan** [quarkusio/quarkus#13081]
I've created a `@Testcontainers` and `@QuarkusTest` according to the Testcontainers documentation for JUnit 5. 

You can find the documentation [here](https://www.testcontainers.org/quickstart/junit_5_quickstart/). 
The problem is that if I'm not manually starting and stopping the container by calling `container.start()` and `container.stop()`, then the container will not be automatically started by Testcontainers framework (as expected).

I've found that if I will remove the `@QuarkusTest` then Testcontainers works well.
(Describe the problem clearly and concisely.)

The container created by using Testcontainers framework should be started and stopped automatically by the framework.
(Describe the expected behavior clearly and concisely.)

The container created by using Testcontainers framework is not started and stopped automatically by the framework, but by me from the code.
(Describe the actual behavior clearly and concisely.)

**To Reproduce**

```
@QuarkusTest
@Testcontainers
public class S3AccountRepositoryIntegrationTest {
    private static final String MINIO_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE";
    private static final String MINIO_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";
    private static final int port = 9000;

    @Container
    public static GenericContainer<?> s3 = new GenericContainer<>(DockerImageName.parse("minio/minio"))
            .withExposedPorts(9000)
            .withEnv("MINIO_ACCESS_KEY", MINIO_ACCESS_KEY)
            .withEnv("MINIO_SECRET_KEY", MINIO_SECRET_KEY)
            .withCommand("server /data");

    @Test
    public void test_container() {
        assertTrue(s3.isRunning());
    }
}
```

1. Create a test case by using `@QuarkusTest` and `@Testcontainers`
2. Create whatever container by using Testcontainers engine.
3. Create a `@Test` in which to `assertTrue(container.isRunning())`.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.1082]
 - Output of `java -version`: java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Maven home: C:\Users\HR11MD\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Users\HR11MD\java\jdk1.8.0_201-ing\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
(Add any other context about the problem here.)

**Comment by famod** [comment]
There have been some discussions in #8097.

For now you could try:
- https://github.com/quarkusio/quarkus/issues/8097#issuecomment-620894139
- or https://github.com/quarkusio/quarkus/issues/8097#issuecomment-603234127 (maybe even via `@io.quarkus.test.junit.TestProfile`)

@geoand WDYT, should we close this one in favor of #8097 or do you want to track this one separately?

**Comment by geoand** [comment]
@famod I agree, let's close this as a duplicate.
