### ISSUE TITLE
Add Quarkus to the MicroProfile Starter

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#1310]
MicroProfile [has its own starter](https://start.microprofile.io/), so we should add Quarkus to the MP 2.1 version. Thorntail V2 is already listed as an MP 2.1 implementation.

**Comment by kenfinnigan** [comment]
The one issue that might be a bit touchy given current discussions, is that Quarkus doesn't run the TCKs at present

**Comment by Karm** [comment]
@kenfinnigan @jclingan Tracked here: https://github.com/eclipse/microprofile-starter/issues/195

**Comment by Karm** [comment]
Blocked by #3596

**Comment by gsmet** [comment]
@kenfinnigan what's the status of this? I don't see Quarkus in the runtime choices.

**Comment by kenfinnigan** [comment]
We can't add ourselves to that list until we're Final

**Comment by gsmet** [comment]
@kenfinnigan can you take care of that once we are Final?

That would be one less issue to manage.

**Comment by kenfinnigan** [comment]
It will be when we claim compatibility, which now looks like 1.1
