### ISSUE TITLE
Constructor injection does not work on RESTEasy component

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#1314]

**Comment by geoand** [comment]
cc @asoldano @mkouba

**Comment by mkouba** [comment]
For the record: _"Support for constructor injection of JAX-RS resources is OPTIONAL. Portable applications MUST instead use fields or bean properties in conjunction with a `@PostConstruct` annotated method. Implementations SHOULD warn users about use of non-portable constructor injection."_

**Comment by geoand** [comment]
In this case we have a failure instead of a warning :P

**Comment by mkouba** [comment]
Yes, I'd say that RESTEasy just doesn't support constructor injection ;-)

**Comment by asoldano** [comment]
See https://issues.jboss.org/browse/RESTEASY-1538
Feel free to open up a new jira if this is relevant here.

**Comment by davinkevin** [comment]
From the Kotlin point of view, this is very sad because we have to use `lateinit var` which is a bad practice

**Comment by geoand** [comment]
Indeed. Hopefully it will be fixed in RESTEasy soon enough and then we can reap the benefits 😁

**Comment by davinkevin** [comment]
I've fixed it by using the Kotlin `no-args` plugin: https://t.co/MFkh3BG8vr

But yeah, would be good to live without it 👍
