### ISSUE TITLE
Building native image - try podman by default

### ISSUE THREAD

**Issue by huw0** [quarkusio/quarkus#13150]
**Description**
Issues / PRs #12157, #12135, #10815 cover using podman to create a container image. However a stacktrace is still printed about docker missing unless `-Dquarkus.native.container-runtime=podman` is specified.

When building a native image, podman should be used by default where available, in line with the Red Hat strategy that has removed Docker from latest RHEL 8.x release.

_I am testing with the Gradle plugin, but presume this would be a generic fix to the native generation code._

**Comment by ebullient** [comment]
I think most quarkus options should be focused on developer first, and most developers will have docker on their laptops, and not buildah/podman. I'm not sure I would make this change, as it creates a tripping hazard/obstacle for devs getting started.

**Comment by geoand** [comment]
This is out of date as Quarkus does try both Docker and Podman by default
