### ISSUE TITLE
Minio Extension

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#13166]
**Describe the extension**
[Minio](https://min.io/) is a Kubernetes Native, high performance object storage.

It has a java client library that can easily be integrated to Quarkus.

I have an extension that works both in OpenJDK and Native mode. See https://github.com/jtama-op/quarkus/commit/ef5142948ee1c5fb170fdc45fe89669fec3cc723

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
# Add your application.properties here, if applicable.
quarkus.minio.url=http://localhost:9000/
quarkus.minio.access-key=YOURACCESSKEY
quarkus.minio.secret-key=YOURSECRETKEY
```

**Additional context**

Minio being K8s native it can only be installed locally through containers. I'm not sure what kind of automtic testing I can provide. The extension is used and working on a project though I know it's not testing ;). Help or ideas would be much appreciated on this point.

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkiverse-minio. You should have push permission @jtama-op
