### ISSUE TITLE
Programmatic rest client generation fails in native mode

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#1317]
To reproduce, you may use the `CountriesResourceTest` in https://github.com/michalszynkiewicz/quarkus-quickstarts/tree/builder-native-failure

Error log:
https://gist.github.com/michalszynkiewicz/174fbfabfb1bb14ccd36f3a8c2d533c5

The cause is that we only register interfaces annotated with `@RegisterRestClient` here:
https://github.com/quarkusio/quarkus/blob/13f7c14bc28714c866e204e7fc3e7acafdd13a56/extensions/smallrye-rest-client/deployment/src/main/java/io/quarkus/smallrye/restclient/deployment/SmallRyeRestClientProcessor.java#L171-L175

**Comment by kenfinnigan** [comment]
Does the spec allow that to work?

I always thought `@RegisterRESTClient` must be present on the interface?

**Comment by michalszynkiewicz** [comment]
I didn't read it very carefully now, but examples and the section about registering cdi beans with the said annotation suggest that it's only needed in the cdi injection case.

**Comment by kenfinnigan** [comment]
I took a look at the spec and I was wrong. But we have a way to fix it

**Comment by michalszynkiewicz** [comment]
Registering everything with `@Path` seems to make the most sense to me

**Comment by michalszynkiewicz** [comment]
@kenfinnigan do you want to tackle that? If not, I'd be happy to

**Comment by kenfinnigan** [comment]
By all means you can tackle it.

In chatting with @stuartwdouglas and @mkouba the logic we settled on is:
- Look for all `@Path` annotations
- Select those that are interfaces
- Search for a class that implements the interface. If there's no match, then add it to the list of interfaces to register for reflection

It's a little more complicated, but we need to ignore the case where a JAX-RS Resource implements an interface with the annotations present.

**Comment by michalszynkiewicz** [comment]
IMO in some cases people may use the same interface for exposing and consuming.
An obvious example would be when doing a demo. But I can imagine someone may want to have some generic API that could be used like that in a production system.

The piece of code in question only registers classes as being available for reflection/proxying, right?
Do we have some estimates on the cost of registering a single class?

I chatted with @mkouba  and he seemed okay with registering all interfaces with `@Path`

**Comment by kenfinnigan** [comment]
Though it can be common for a single interface, you wouldn’t have the client and server in the same app?

Ideally we want to make the native image as small as we can. It’s not just that class, as we then register all the return types of methods on the interface as well

**Comment by michalszynkiewicz** [comment]
I meant having the client and server in the same app

**Comment by kenfinnigan** [comment]
Not sure how realistic that would be.

Stephane also mentioned yesterday that we should discourage people from sharing interfaces between client and server because it ties the execution model of the server to the client. So if the resource used CompletionStage, then the client would have to as well

**Comment by michalszynkiewicz** [comment]
Not knowing the performance impact I remain not convinced, but I implemented it with skipping the interfaces that are implemented ;)

**Comment by mkouba** [comment]
The performance impact should be IMHO negligible but your PR need proper formatting - see https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md ;-)

**Comment by michalszynkiewicz** [comment]
seems I left some unused imports, let's see what happens now
