### ISSUE TITLE
No parameter injector found for parameter 1 of route method void listGroup

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#13176]
**Describe the bug**
String type can work, Integer type throws an exception

**To Reproduce**

```
    @Route(path = "/groups/list/:id", methods = HttpMethod.GET)
    public void listGroup(RoutingContext context, @Param("id") int id) {
        List<String> list = captchaService.getCaptchaByGroupId(id);
        context.response().end(Json.encode(list));
    }
```

**Comment by gsmet** [comment]
Which version of Quarkus is it?

/cc @mkouba @cescoffier

**Comment by mkouba** [comment]
An automatic conversion is not supported yet. See https://quarkus.io/guides/reactive-routes#reactive-route-methods for more info.

**Comment by mkouba** [comment]
Duplicates https://github.com/quarkusio/quarkus/issues/11481

**Comment by aomsweet** [comment]
thanks. @gsmet @mkouba
