### ISSUE TITLE
RESTEASY003880: Unable to find contextual data of type when quarkus-undertow-websockets dependency added

### ISSUE THREAD

**Issue by fafanoulele** [quarkusio/quarkus#13187]
**Describe the bug**
Once I had the dependency `quarkus-undertow-websockets`, the filter/interceptor fails with this error:
```
RESTEASY002005: Failed executing GET /fruits: org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:124)
	at com.sun.proxy.$Proxy42.remoteAddress(Unknown Source)
	at org.acme.rest.json.LoggingFilter.filter(LoggingFilter.java:29)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:312)
```

**Expected behavior**
It should not throw this exception.

**Actual behavior**
Error exception:
```
RESTEASY002005: Failed executing GET /fruits: org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:124)
	at com.sun.proxy.$Proxy42.remoteAddress(Unknown Source)
	at org.acme.rest.json.LoggingFilter.filter(LoggingFilter.java:29)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:312)
```

**To Reproduce**

The reproducer is there: https://github.com/fafanoulele/quarkus-issue-RESTEASY003880

1. Start the app i.e. `./mvnw quarkus:dev`
2. Call a REST API i.e. `curl http://localhost:8080/fruits`
3. This call returns this error `RESTEASY003880: Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest`

**Environment (please complete the following information):**
 - Output of `uname -a`: `18.7.0`
 - Output of `java -version`: `Java version "1.8.0_202"`
 - GraalVM version (if different from Java): 
 - Quarkus version: `1.9.2.Final` 
 - Build tool (ie. output of `mvnw --version`): `3.6.3_1`

**Comment by geoand** [comment]
This is expected behavior. 

When you add any Undertow related dependency, then the underlying IO is no longer handled by Vert.x (which is where `io.vertx.core.http.HttpServerRequest` is coming from), but by Undertow.

What you can do in order to use something that will work in both cases is use information from the `ContainerRequestContext context` parameter or try using any of the following objects with `@Context`: https://docs.jboss.org/resteasy/docs/4.5.8.Final/userguide/html_single/#_Context

**Comment by fafanoulele** [comment]
Thanks! It is fair enough. FYI, I had added `Undertow` because in my app I have WebSocket endpoints besides JAX-RS endpoints.
I confirm that using `ContainerRequestContext` or `@Context` fits with what I need to do. Thanks again!
