### ISSUE TITLE
Add referral mode config property to the quarkus.security.ldap.dir-context

### ISSUE THREAD

**Issue by andrzejszywala** [quarkusio/quarkus#13184]
**Description**
Add referral mode config property to the quarkus.security.ldap.dir-context. 
In io.quarkus.elytron.security.ldap.LdapRecorder.createDirContextSupplier there is hardcoded DirContextFactory.ReferralMode.IGNORE passed to dirContextFactory.obtainDirContext method. Please add to DirContextConfig new config property quarkus.security.ldap.dir-context.referral-mode because there is sometimes need to set other values then ignore.

**Implementation ideas**
1. Add to DirContextConfig new configuration property:
```
@ConfigItem
public Optional<DirContextFactory.ReferralMode> referralMode;
```
2. In LdapRecorder change
```
return () -> dirContextFactory.obtainDirContext(DirContextFactory.ReferralMode.IGNORE);
```
to
``` 
return () -> dirContextFactory.obtainDirContext(dirContext.referralMode.orElse(DirContextFactory.ReferralMode.IGNORE));
```

**Comment by sberyozkin** [comment]
@andrzejszywala Thanks for this proposal, can you please consider a PR and CC to @hartimcwildfly ? I maybe able to review as well, thanks

**Comment by gsmet** [comment]
Just do:
```java
@ConfigItem(defaultValue = "ignore")
public DirContextFactory.ReferralMode referralMode;
```
and it will get properly autodocumented and you will avoid some boilerplate :).

(`ignore` as lowercase, everything will be handled by Quarkus to get the enum value from this string)
