### ISSUE TITLE
Allow releasing runner class loader resources

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#13202]
**Description**
When doing CLI applications it might be necessary to make the re-augmentation process more transparent to users by issuing specific commands to the application, where these commands may have different options and logic that require configuring and parsing arguments using Picocli.

When doing re-augmentation on Windows, the JARs generated during the re-augmentation may be locked when the `RunnerClassLoader` is created thus failing to recreate these JARs.

**Implementation ideas**
Allow closing the `RunnerClassLoader` so that resources are released while still allowing these resources to be loaded again.

**Comment by pedroigor** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/13157

**Comment by Sanne** [comment]
hi @pedroigor - did you mean to close this?
