### ISSUE TITLE
Evaluate the use of parentFirst artifacts in io.quarkus.bootstrap.runner.RunnerClassLoader

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#13216]
**Description**
As mentioned in https://github.com/quarkusio/quarkus/pull/13157#issuecomment-724612324, the JDK ClassLoader seems to be loading more jars that necessary when using the `fast-jar`.
Ideally we want all jars (other than the Quarkus bootstrap jars) to be loaded by the `io.quarkus.bootstrap.runner.RunnerClassLoader`.
 
**Implementation ideas**
It's likely that extra jars are being loaded by the JDK ClassLoader because `RunnerClassLoader` takes into account the `parentFirst` configuration of artifacts. This configuration is meant for dev mode and probably doesn't make sense to be honored by `RunnerClassLoader`.

**Comment by geoand** [comment]
I'll take a quick look and see if there is an easy win in this case.

**Comment by Sanne** [comment]
thanks @geoand !

Also keep in mind @stuartwdouglas mentioned the loggers need to be loaded by the JDK classloader - I'm just not sure which one of the many logger-related jars, probably all but I hope we could limit that.

So I'd suspect the `parentFirst` configuration still need to exist, but the list needs to be different.

**Comment by geoand** [comment]
I just saw that myself when playing with the code :)

**Comment by geoand** [comment]
@Sanne see https://github.com/quarkusio/quarkus/pull/13219 for a quick and dirty display of the issue
