### ISSUE TITLE
Integrate OpenTelemetry and gRPC Quarkus extensions

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13224]
**Description**
At the moment, the OpenTracing data are not propagated from a REST service to a gRPC service and vice versa.

**Example**

Having the OpenTracing, gRPC and RestEasy (this is optional) extensions:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-opentracing</artifactId>
</dependency>

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-grpc</artifactId>
</dependency>

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy</artifactId>
</dependency>
```

My REST endpoint using RestEasy:

```java
@Path("/ping")
public class PingResource {

    @Inject
    @GrpcService("pong")
    PongServiceGrpc.PongServiceBlockingStub pongClient;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String getPing() {
        return "ping " + pongClient.sayPong(PongRequest.newBuilder().build()).getMessage();
    }
}
```

And my gRPC service implementation:

```
@Singleton
public class GrpcPongService extends PongServiceGrpc.PongServiceImplBase {

    @Override
    public void sayPong(PongRequest request, StreamObserver<PongReply> responseObserver) {
        String lastTraceId = MDC.get("traceId"); // This is null! traceId is not propagated!
        responseObserver.onNext(PongReply.newBuilder().setMessage("pong").build());
        responseObserver.onCompleted();
    }
}
```

The full example can be found [here](https://github.com/Sgitario/beefy-scenarios/tree/opentracing_master/010-quarkus-opentracing-reactive-grpc).

**Implementation ideas**

There is some implementations in GitHub about how to integrate two pieces, as an example: https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/java.

However, I'm aware of the OpenTracing Quarkus extension is deprecated and I'm not sure if the effort will be worthy for the future OpenTelemetry extension.

**Comment by cescoffier** [comment]
Shouldn't we use OpenTelemetry instead? @kenfinnigan 

Implementation could use an interceptor, however, we may hit async boundary issues. gRPC services are by default invoked on the event loop. But with the recent introduction of @Blocking, there is a context switch.

**Comment by kenfinnigan** [comment]
I'm still working on OpenTelemetry extension for Quarkus, but ideally yes we'd be integrating with OpenTelemetry and not OpenTracing
