### ISSUE TITLE
Hibernate validation for multi module case: javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint

### ISSUE THREAD

**Issue by asodja** [quarkusio/quarkus#13233]
When using hibernate validation and `@Valid` with request body parameter, I got an 500 when Pojo I am validating is not in a module that Quarkus scans. My Pojo class has annotation `@NotBlank` but I get:
```
javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotBlank' validating type 'java.lang.String'. Check configuration for 'hello.arg0.value'
```

If I add `@NotBlank` anywhere in module that Quarkus scans it works ok and pojo gets validated and I get 400 if it is invalid or 200 if it is valid.

I don't want that my lib module is scanned, since there are a lot of things in there.

**Expected behavior**
Pojo is validated normally, I get 400 if it is not valid or 200 if it is valid.

**Actual behavior**
javax.validation.UnexpectedTypeException is thrown.

**To Reproduce**
1. git clone https://github.com/asodja/quarkus-multimodule-hibernate
2. Run `MyResourceTest.java` -> both tests fail, response is 500
3. Uncomment dummy method with `@NotBlank` annotation in `MyResource.java`
4. Run `MyResourceTest.java` -> both tests pass, response is 400 and 200 as expected 

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "1.8.0_242"
 - Quarkus version: 1.9.2.Final
 - Build tool: Gradle 6.6.1

**Comment by gsmet** [comment]
HV will only register the constraint validators for the constraints it can find.

What you need to do is create a Jandex index for the additional module. This plugin might help: https://plugins.gradle.org/plugin/org.kordamp.gradle.jandex .

**Comment by asodja** [comment]
Hmm so if I understand correctly, it is not technically possible that hibernate-validator extension would also check annotations recursively on classes that are used with`@Valid` even if they are not in the module?

**Comment by gsmet** [comment]
Hibernate Validator in Quarkus needs to have a complete lists of all the constraints used and this is done by scanning the Jandex index.

**Comment by asodja** [comment]
Thanks for explanation. I will try workaround this. I will first try with some class that will have all constraints annotations in it so all validators will be initialized, it's dummy but it looks like it works ok and there it seems is not that big performance penalty for our use case.

If that does not work ok I will add Jandex index build step into our build.

You can close this issue.

**Comment by gsmet** [comment]
Frankly, just add the Jandex index creation to your build. Anything else will be brittle.

**Comment by moisaluc** [comment]
Hi,

I know this is closed but I'm having the same issue, even with what was specified in the previous comments. Multi-module project, I have a Jandex index, the POJOs are discovered fine but get javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotBlank' validating type 'java.lang.String'.

I have a few strings annotated with @NotBlank(message = ...). Using 2.7.3.Final. Anything else I might be missing that's not in the comments? I've turned the internet upside-down and couldn't really find an answer for this particular case.

Thanks!

**Comment by gsmet** [comment]
@moisaluc you're using Hibernate Validator 6.2.x and Bean Validation 2.0, right?

If not, you should (that's what the Quarkus BOM enforces so if you haven't overridden the versions, it should be OK). If so, please create a reproducer.

**Comment by moisaluc** [comment]
@gsmet I am, yes, I haven't changed anything. But while building a small, separate reproducer I noticed that it actually works as expected so it looks like there's something wrong with my actual project. Happily (or sadly...) I only have to figure out what.

Thanks for the fast reply!

**Comment by gsmet** [comment]
Make sure you really have a Jandex index for the modules in which the
constraints are.

Because we take the list of constraints we detect in the Jandex index and
we push it to HV. Any constraint that is not in the Jandex index won't have
its validators registered in HV. Which would lead to the errors you are
seeing.

**Comment by MakraGitHub** [comment]
What is the solution ?

**Comment by simkamboj** [comment]
Could you please share the solution?
