### ISSUE TITLE
Deferred release of JarFile buffers in RunnerClassLoader

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#13258]
**Description**
As a follow up to #13157 : releasing the caches isn't super effective as there's much code (and resources) possibly being loaded much later after the bootstrap has completed.

**Implementation ideas**
There's a number of things we could do.

## Switch to immediate-close, with threshold

@stuartwdouglas in https://github.com/quarkusio/quarkus/pull/13219#issuecomment-725682255 suggests we could, after bootstrap, switch to a strategy of opening/closing the jars immediately - and give up of closing it again if we observe there's many opening events happening - just counting it to go over some threshold.

Personally I like the principle, but I'm afraid of the impact of having many sequential open/close requests - I can think of some scenarios in which it's not going to be nice.

I think my main problem with this is that performance of the application could possibly get severely inconsistent while it stabilizes into the right threshold, and it's hard for us to guess a reasonable number for such threshold.

## Switch to SoftReferences

This could be improved with a SoftReference? We'd open on demand, and close the Jar on GC - this should give it the opportunity to reuse the same Jar buffers, should there be sequential need. Except I'm not a fan of XReference tricks, they usually end up costing some other unpredicted soul.

## Periodic unload

We could use a timer to cleanup the JarFile caches each N seconds. And [edited following @geoand 's suggestions below], only close a Jar after some access grace period.

This is interesting, provided we can reuse an existing thread - would prefer to not need to start a dedicated new thread. Perhaps the main thread, which is sitting waiting for the app to quit could occasionally wake up and verify things? There might be other things it could do.

## Other?

TBD

To be considered that solving #13256 should also mitigage the need for this, so SoftReferences could be good enough.

**Comment by geoand** [comment]
How about having a timer thread that closes the resources **iff** no request has been retrieved for loading something (assuming we keep track of the last load time)?

**Comment by Sanne** [comment]
> How about having a timer thread that closes the resources **iff** no request has been retrieved for loading something (assuming we keep track of the last load time)?

I like it, but assuming we have a "free timer" :)

**Comment by geoand** [comment]
Do you have reason to assume that the JDK's timer has non-free overhead?

**Comment by Sanne** [comment]
My memory is often faulty, but I think it requires threads to work and it will start one if you don't hand it one explicitly. And maybe that's ok, I probably shouldn't be so picky about not wanting to start one :)  But it starts to erode in the beauty of the design choice.

**Comment by geoand** [comment]
Yeah it does start a timer thread indeed. We can certainly measure and see if it brings any significant overhead

**Comment by stuartwdouglas** [comment]
Vert.x threads have built in timer capability, and most apps have vert.x installed.
