### ISSUE TITLE
Unit tests an mvn quarkus:dev runs should have the same current folder

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#13253]
**Description**

I have applications which consult data files.  Both my local runs and my unit tests have dummy variants of these files, say under ${projectfolder}/data.    My application.properties contains a setting like path=/some/or/other/folder 

Unfortunately, this code:
new File(".").getAbsolutePath()
will return ${projectfolder} when running a unit test, but ${projectfolder}/target  when running as mvn quarkus:dev

Hence the setting requires different values between unit tests and dev runs.

Workaround:

You can do this in application.properties:

%dev.path=../data
%test.path=./data

**Implementation ideas**

I assume changing the current folder will break backward compatibility.  Some alternatives in application.properties might be:
 * Provide an expandable value like ${quarkus.projectfolder}
 * Provide a setting like quarkus.currentfolder=

**Comment by famod** [comment]
What about adding those data files to `src/main/resources` and load them from the classpath?

**Comment by hyperman1** [comment]
There are things you can do with a file path but not classpath.  E.g. listing all files in a folder, listening to FS changes

In my specific situation, there is an NFS share.  An external system dumps files on them every X minutes.  My program picks them up and processes them.

**Comment by gsmet** [comment]
I think we adjusted that with continuous testing.
