### ISSUE TITLE
Quarkus configuration and kubernetes configmap/secrets

### ISSUE THREAD

**Issue by hyperman1** [quarkusio/quarkus#13254]
**Description**
Quarkus expects config in the file ./application.properties but kubernetes prefers configmaps and secret maps.  I would like a way to dump a full configmap/secret map in application.properties

**Implementation ideas**

It is possible in kubernetes to publish config and secrets as a mounted file system, eg a configmap with key1=value1,key2=value2 appears as a folder /some/path/configmap with files key1 containing value1, key2 containing value2

Hence a system property or soomething to read in such a folder and publish it as eclipse microprofile config seems one way forward.  

It would be good to make it possible to import multiple such folders, so e.g. different teams can each manage their config/secrets in their own maps.

For example java -Dquarkus.configmaps=/some/path/configmap,some/path/secrets   application.jar

Workaround:  I added this in a shellscript:

for x in /app/configmap/* /app/secret/*;do  echo `basename $x`=`cat $x`;done > /app/config/application.properties

I had to modify my dockerfile to make /app/config/application.properties writeable

**Comment by geoand** [comment]
@hyperman1 does https://quarkus.io/guides/kubernetes-config not cover you needs?

**Comment by hyperman1** [comment]
@geoand   I have no idea how I managed to overlook that.  Sorry to disturb you.

**Comment by geoand** [comment]
Not a problem at all!
