### ISSUE TITLE
RestClient not evaluating API annotations in class hierarchy

### ISSUE THREAD

**Issue by GeorgHenkel** [quarkusio/quarkus#13263]
**Describe the bug**
In a RestClient implementation the additional API annotations in the class hierarchy are not evaluated.  So that it is needed to duplicate the annotation on the RestClient interface. 

**Expected behavior**
I would expect that annotations are evaluated in the class hierarchy, like it is done in the JAX-RS resource implementation, where e.g. the `@Path` annotation can be used in an interface. 

**Actual behavior**
Annotations in the class hierarchy are ignored. The `@Path` annotation must be explicitly set on the interface which is annotated with `@RegisterRestClient`.

**To Reproduce**
https://github.com/GeorgHenkel/quarkus-restclient-error

1. Start modules impl and service with `./mvnw quarkus:dev`
2. Request URL http://0.0.0.0:8080/test/myName -> Returns 404
3. Request URL http://0.0.0.0:8080/test/with-path/myName -> Returns 200 with json body: `{ "name": "myName" }`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  
> Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu- 6153.141.2.2~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
 - Quarkus version or git rev: 
> 1.9.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
> Maven home: /Users/georgleber/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
> Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Users/georgleber/.sdkman/candidates/java/11.0.8.hs-adpt
> Default locale: de_DE, platform encoding: UTF-8
> OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by rquinio** [comment]
Linking to https://github.com/eclipse/microprofile-rest-client/issues/262, as it appears to be an issue in the spec.

**Comment by geoand** [comment]
Is this still an issue with `quarkus-rest-client-reactive`?

**Comment by geoand** [comment]
👌
