### ISSUE TITLE
OIDC Discovery fails for Azure Active Directory B2C

### ISSUE THREAD

**Issue by osst** [quarkusio/quarkus#13265]
**Description**
If you are using Azure Active Directory B2C as the Identity Provider, Discovery fails for the following reason:
'issuer validation failed'.

As a `quarkus.oidc.auth-server-url` I'm supplying a url that looks like this:
`https://{tenant-name}.b2clogin.com/{tenant-id}/{policy-name}`

Azure responds to `.well-known/openid-configuration` with the following json:
```
{
  "issuer": "https://{tenant-name}.b2clogin.com/{tenant-id}/",
  ...
}
```

The issue here is that in this response "issuer" does not have the last bit `{policy-name}`. As a result issuer validation fails in a Vert.x class here:
https://github.com/vert-x3/vertx-auth/blob/3.9/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/providers/OpenIDConnectAuth.java#L74

**Implementation ideas**
Would it be possible to add an option to skip validation of the issuer? Vert.x already has this option. They are using it here:
https://github.com/vert-x3/vertx-auth/blob/3.9/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/providers/AzureADAuth.java#L74

Or
Azure allows to specify policy name as an argument:
`https://{tenant-name}.b2clogin.com/{tenant-id}/.well-known/openid-configuration?p={policy-name}`
it would be nice to have `extra-params` option but for the discovery path. For example:
`quarkus.oidc.discovery.extra-param.p={policy-name}`

**Comment by sberyozkin** [comment]
@osst This is already covered with `quarkus.oidc.token.issuer`, can you try it please ?

**Comment by osst** [comment]
@sberyozkin Thank you! With this property, everything works well.

Couldn't figure it out from the documentation, as I thought this property applies only to token validation.

**Comment by sberyozkin** [comment]
@osst sure, I'll consider updating the docs during the next round
