### ISSUE TITLE
Spring Cloud config list properties are incompatible with smallrye

### ISSUE THREAD

**Issue by ntrp** [quarkusio/quarkus#13277]
**Describe the bug**
The properties coming from Spring Cloud Client are not compatible with SmallRye mappings because the format is different.
This is in yml fragment:
```
test:
 - qwe
 - asd
```
which, if set in Quarkus, produces a context map with:
```
"test" -> "qwe,asd"
"test.[0]" -> "qwe"
"test.[1]" -> "asd"
```
When I set the same in the config server this is the outcome:
```
"test[0]" -> "qwe"
"test[1]" -> "asd"
```
Notice the missing point

**Expected behavior**
The properties are normalized to be compatible with SmallRye or handled properly in some other way

**Actual behavior**
The list properties coming from the config server are unusable because they do not exist technically. Quarkus does not find anything for `test` because the properties are `test[0]` and `test[1]`.

**To Reproduce**
Did not create the reproducer because the explanation is straight forward and no debugging is needed

**Configuration**
Defined in previous section

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.9.2.final
Rest of the versions are not relevant

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
@ntrp thanks for reporting!

Do you perhaps have a small sample Spring Cloud Config Server setup with the problematic YAML properties so I can give it a try?

**Comment by ntrp** [comment]
Well the small sample is the one I added at the beginning, the same yaml produces different properties between could config client and local yaml. You mean a working project to try it out? I can set one up if I find some time..

**Comment by geoand** [comment]
A very simple working project along with the Spring Cloud Config Server you used to show the problem would be great.

**Comment by geoand** [comment]
@ntrp any change you could add an example as mentioned above?

**Comment by radcortez** [comment]
I believe that with the changes we added in SmallRye Config 1.11.0 and the Indexed Properties Support, this should work fine, but needs verification.

**Comment by ntrp** [comment]
Sorry, was busy this days. Will add one until the weekend and thank you for the great support you offer on all bugs we open! Not something that happens on every project :)

**Comment by radcortez** [comment]
BTW, the Indexed Properties Support was added here: https://github.com/quarkusio/quarkus/pull/14955

**Comment by ntrp** [comment]
Sorry for being again late.. I tested the latest version of Quarkus 1.12.0 and the error still appears, here you are a minimal demo repo https://github.com/ntrp/quarkus-issues-13277.

If you copy this:
```yaml
demo:
  - asd
  - qwe
```
to the client `application.yml` the client can start.

**Comment by geoand** [comment]
Thanks for the reproducer.

I will have a look.

**Comment by geoand** [comment]
@radcortez essentially this boild down to:

In a hello world Quarkus application, if I add

```properties
demo[0]=hello
demo[1]=friend
```

and have code that expects to read the configuration like so:

```java
@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "demo")
    List<String> demos;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return demos.get(0);
    }
}
```

then Quarkus fails with:

```
2021-03-01 10:03:29,453 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): javax.enterprise.inject.spi.DeploymentException: No config value of type [java.util.List] exists for: demo
        at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:39)

```

Does the indexed configuration support only work for `@ConfigMapping` perhaps?

**Comment by radcortez** [comment]
Ah, yes. Forgot that `@ConfgProperty` injection is implemented differently in Quarkus (we use a CDI Extension in SR Config), so we need to implement things twice.

I'll handle that. Sorry for wasting everyones time.

**Comment by geoand** [comment]
No worries, thanks for picking it up @radcortez!
