### ISSUE TITLE
Support reading grpc client trust store from classpath

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#13305]
**Description**
Currently we can read server certificate and key from classpath but client's trust store can only be read from a file. 
It causes problems with dev mode, see https://github.com/quarkusio/quarkus-quickstarts/issues/709
It would ease development if we supported reading the trust store from classpath too.

**Comment by michalszynkiewicz** [comment]
@cescoffier do you see any cons?

**Comment by cescoffier** [comment]
No, we should support both.
