### ISSUE TITLE
Default Schema Is Not Automatically Detected

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13303]
**Describe the bug**
When using Hibernate and flyway, the default schema is not properly resolved and the schema validation is failing with:

```
Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-orm-rest-data-panache, jdbc-postgresql, mutiny, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation]
WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 42P01
[org.hib.eng.jdb.spi.SqlExceptionHelper] (main) ERROR: relation "application" does not exist
```

In order to workaround this issue, we need to configure the default schema as:

```
quarkus.hibernate-orm.database.default-schema=my-schema
```

**Expected behavior**

The expected behaviour should be that the default schema is configured via the JDBC URL:

```
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/my-schema
```

**Actual behavior**

It fails with:
```
Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-orm-rest-data-panache, jdbc-postgresql, mutiny, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation]
WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 42P01
[org.hib.eng.jdb.spi.SqlExceptionHelper] (main) ERROR: relation "application" does not exist
```

**To Reproduce**
1. `pom.xml`:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm-rest-data-panache</artifactId>
</dependency>

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-flyway</artifactId>
</dependency>

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
```

2. Having this `application.properties`:

```
# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sarah
quarkus.datasource.password=connor
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test
quarkus.hibernate-orm.database.generation=validate

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=test
```

3. My migration file:

```
CREATE SEQUENCE hibernate_sequence START 1;

CREATE TABLE application
(
  id            BIGINT PRIMARY KEY,
  name          VARCHAR(100) NOT NULL UNIQUE
);
```

4. My Panache entity:

```
@Entity(name = "application")
public class ApplicationEntity extends PanacheEntity {
    @Column(unique = true, nullable = false)
    public String name;
}
```

This fails to start with the above failure. Note that to workaround this issue, we need to add this property to `application.properties`:

```
quarkus.hibernate-orm.database.default-schema=test
```

The full reproducer (with tests to reproduce the issue) can be found [here](https://github.com/Sgitario/beefy-scenarios/tree/add-panache-flyway-example/011-quarkus-panache-rest-flyway).

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

```
Linux localhost.localdomain 5.7.11-200.fc32.x86_64 #1 SMP Wed Jul 29 17:15:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

 - Output of `java -version`: 

```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
```

 - Quarkus version or git rev: **999-SNAPSHOT**
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): **Apache Maven 3.6.3**

**Comment by gavinking** [comment]
Wait, I don't understand: that JDBC URL is specifying the Postgres *database*, not the *schema*, or am I totally crazy?

**Comment by gavinking** [comment]
I think you use the `currentSchema` parameter to set the schema in a Postgres JDBC URL (though I have not tested this).

**Comment by Sgitario** [comment]
My bad @gavinking ! I just checked the currentSchema parameter and it works as expected. Closing this issue.

**Comment by gavinking** [comment]
Phew 😅 cheers!
