### ISSUE TITLE
Kotlin Plugin: plugin is probably applied by a mistake

### ISSUE THREAD

**Issue by guildenstern70** [quarkusio/quarkus#13318]
Quarkus-Gradle-Kotlin project gives this warning while building (quarkus-build & quarkus-dev):

`
> Task :quarkusGenerateCode
preparing quarkus application
kotlin scripting plugin: root project 'smartquark'.compileQuarkus-generated-sourcesKotlin - configuration not found: quarkus-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake

> Task :quarkusGenerateCodeTests
preparing quarkus application
kotlin scripting plugin: root project 'smartquark'.compileQuarkus-test-generated-sourcesKotlin - configuration not found: quarkus-test-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake
`

Using Graal JVM 11. Tried using Graal JVM 8 and downgrading to target bytecode JRE8, same result.

Link to source code: 
https://github.com/guildenstern70/SmartQuark

**Comment by glefloch** [comment]
I can't find the PR, but this has been fix by declaring those `sourceSet`
