### ISSUE TITLE
Health check configurable for each datasource

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#13326]
**Description**
I have multiple datasources, one of which is only used by a job at the beginning of the day. That datasource is failing sometimes and it causes the whole application to be seen as DOWN in the health check.

I'd need to configure for that specific datasource that I want the health check disabled, while still having the check enabled for my main datasource.

Any possibility to have the health check config datasource-specific?

**Comment by jmartisk** [comment]
I think this makes sense. We could add a `health-enabled` property per data source and treat it as `true` by default if health is enabled in general.
I will look into it soon if no one else wants to take it

**Comment by antoniomacri** [comment]
Hi @jmartisk, any plan when this will be released?

**Comment by jmartisk** [comment]
Hi @antoniomacri the PR is still in review, feel free to comment on it if you wish to help speed it up :)
