### ISSUE TITLE
Open localhost:8080 in default browser AFTER starting up if -Dquarkus.http.open-in-browser=true

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#13321]
For demo scripts, it's very useful to open the content that Quarkus is serving, by opening the browser after the server has started.  

The pitfall is that any demo shell scripts, can't open the browser themselves, because they have no clue how long it will take for the server to start up. Nor can they tell the user to open it, because the user might do it too soon, which ruins the demo experience. So it must be done in the Quarkus process itself.

This works, but I think it should be standarized (and use HTTPS if that's active):

```
    @ConfigProperty(name = "quarkus.http.open-in-browser", defaultValue = "false")
    boolean startupOpenBrowser;
    @ConfigProperty(name = "quarkus.http.port")
    int httpPort;

    public void setup(@Observes StartupEvent startupEvent) {
        if (startupOpenBrowser) {
            openInBrowser(httpPort);
        }
    }

    private void openInBrowser(int port) {
        String url = "http://localhost:" + port;
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop == null || !desktop.isSupported(Desktop.Action.BROWSE)) {
            // There is no default browser
            return;
        }
        try {
            desktop.browse(new URI(url));
        } catch (IOException | URISyntaxException e) {
            throw new IllegalStateException("Failed opening the default browser to show the URL (" + url + ").", e);
        }
    }
```

**Comment by geoand** [comment]
Closing as this option (by pressing `d`) has since been added to the console
