### ISSUE TITLE
/app folder not readable by others, when Jib extra directories feature is used

### ISSUE THREAD

**Issue by msogrin** [quarkusio/quarkus#13322]
**Describe the bug**
When Jib extra directory feature is used (introduced in https://github.com/quarkusio/quarkus/issues/8936) by putting files into `src/main/jib` folder, if the `app` folder is used here (e.g. with a file `src/main/jib/app/foo`), then the `/app` folder created in the container image *does not have "o+x" permission*.

**Expected behavior**
`/app` folder in the container image has "o+x" permission, like it does when Jib extra directories feature is not used.

**Actual behavior**
`/app` folder in the container image doesn't have "o+x" permission, thus not allowing non-root users to load the app.

**To Reproduce**

1. Use Jib for creating container image.
2. Add some files in `src/main/jib/app/` folder.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin *** 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: AdoptOpenJDK OpenJ9 11.0.9
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.0.Final  (the feature was introduced in 1.6)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.6.1

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/13336 should fix the issue
