### ISSUE TITLE
Bump Vault to 1.6 in extension IT and doc

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#13339]
**Description**
Test vault extension against Vault 1.6.
Blocked by https://github.com/hashicorp/vault/issues/10232

**Comment by sberyozkin** [comment]
@vsevel #13347 has been merged, should this issue be closed now (your PR had a workaround) ?

**Comment by vsevel** [comment]
yes @sberyozkin 
Fixed by https://github.com/quarkusio/quarkus/pull/13347
