### ISSUE TITLE
Activate Dependabot for this repo?

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1333]
How about activating https://dependabot.com for this repo? (Needs an org admin; I can't do.)

I've used it for a while in a number of projects - works great IMHO!

Can be configured to auto-merge PRs which passed, or manual.

Would help to avoid manual "toil" (churn) such as #1332.

**Comment by kenfinnigan** [comment]
The issue might be that there are a reasonable number of dependencies that we have hard dependencies on that need to be aligned across frameworks.

Misalignment will break the build

**Comment by vorburger** [comment]
> The issue might be that there are a reasonable number of dependencies that we have hard dependencies on that need to be aligned across frameworks.

Oh. But then sholdn't those be inherited transitively from somewhere anyway, instead of being fixed in the Quarkus BOM?

Perhaps if you (anyone) has a specific example of such a situation, we could have a closer look.

> Misalignment will break the build

FYI Dependabot would never force merge any PRs which doesn't pass the build.

**Comment by kenfinnigan** [comment]
Netty is one example.

We need the same version across Vert.x, Undertow, RESTEasy, and Infinispan

**Comment by vorburger** [comment]
OK then after we activate Dependabot (if there are no other major cons) it's easy to "teach" it, one time only, about these cases ... for example, the first time it proposes a bump of Netty, you would comment "@dependabot ignore this dependency" and it will shut up (forever, AFAIK) about it. See e.g. https://github.com/vorburger/odlparent/pull/583 for an example - expand that "Dependabot commands and options" section to see how you to "configure" it...

**Comment by kenfinnigan** [comment]
I've used Dependabot on projects before.

My concern is we need tighter control over all versions than just updating if CI passes

**Comment by vorburger** [comment]
> Can be configured to auto-merge PRs which passed, or manual.
> My concern is we need tighter control over all versions than just updating if CI passes

sure, so we would definitely never ever let it "auto-merge" - fine, granted. This "tighter control" you are referring to would simply happen in PR reviews (as for any change) - for some cases leading to "@dependabot ignore this dependency" (one time, only; initially), and in others to "thanks!" (and merge). Still seems very useful, no? :smile_cat: So such version bump PRs should be approved by whoever is best positioned to understand impacts. And, really, better tests should be written if something cannot be version bumped but CI still passes?

**Comment by dmlloyd** [comment]
It will definitely screw up our ecosystem plans.

**Comment by cescoffier** [comment]
I love dependabot, but for quarkus it can be pretty dangerous. We have lots of "tricky" dependency where updates need to be coordinated.

**Comment by kenfinnigan** [comment]
Closing as "won't do" for now.
