### ISSUE TITLE
Native Support for Micrometer + Stackdriver

### ISSUE THREAD

**Issue by murphye** [quarkusio/quarkus#13349]
**Describe the bug**

Micrometer Stackdriver isn't supported by Quarkus Native.
https://github.com/ebullient/quarkus-micrometer-extension/pull/3

This is would a **nice to have** for those who are using Google Cloud Platform which uses Stackdriver. There is increasing interest with using Quarkus Native with managed Google Cloud Run, which would require the Stackdriver support in order to collect metrics from the Quarkus application.

Note: If you're using Google Cloud Run on Anthos, you would use Micrometer Prometheus instead.

Related Issue:
https://github.com/quarkusio/quarkus/issues/11923

**Comment by loicmathieu** [comment]
@murphye as you already noticed, Google Cloud services are developed outside the core Quarkus extensions inside the Quarkiverse Google Cloud Services repository.

@ebullient maybe the Quarkiverse repo is a better host for this extension ?

**Comment by ebullient** [comment]
stackdriver is optional registry add-on for micrometer, which is a core extension

**Comment by ebullient** [comment]
1) Micrometer Stackdriver registry move to Quarkiverse: 
  * Remove from Quarkus (1.11) https://github.com/quarkusio/quarkus/pull/13764
  * Add to Quarkiverse: https://github.com/quarkiverse/quarkiverse-micrometer-registry/pull/3
 
2) Update quarkiverse-micrometer-registry-stackdriver extension to use/work with google cloud services extensions (also in quarkus) for native mode support
