### ISSUE TITLE
Maven property `quarkus.profile` should be picked up by quarkus-maven-plugin

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#13341]
Given this pom.xml:
```
      <properties>
        <quarkus.profile>foo</quarkus.profile>
      </properties>
```
and this application.properties
```
hello-message=Hello
%foo.hello-message=Hi
```
the hello message should resolve to "Hi".

Reproduced with a "native" profile property in the code mentioned in this discussion:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Native.20profile.3A.20how.20to.20create.20one.3F

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by ge0ffrey** [comment]
Any change on this?

**Comment by aloubyansky** [comment]
That's a bit tricky. At this point the project build properties aren't checked to contain `quarkus.profile` https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ProfileManager.java#L41
And the profile is configured early https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigUtils.java#L74
before the config source are added to the builder (the build properties are not at the top) https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java#L146

cc @stuartwdouglas @dmlloyd

**Comment by ge0ffrey** [comment]
As this can't be solved easily, I've created https://github.com/quarkusio/quarkus/issues/14757

**Comment by essobedo** [comment]
A potential fix for this ticket https://github.com/quarkusio/quarkus/pull/15356. I have not tested it in "native mode" but in "non native mode", it seems to work unless I missed something

**Comment by ge0ffrey** [comment]
Thanks @essobedo !
