### ISSUE TITLE
Render HTML in Qute from data properties

### ISSUE THREAD

**Issue by Phil404** [quarkusio/quarkus#13348]
Hello,

I have the following problem:
I store text with html tags in database and want to render it with qute.
The text appears in the rendered page but the html tags are not rendered.

landingpage.kt
```
@Path("/")
class Landingpage() {
  @Inject
  lateinit var landingpage: Template

  @Get
  @Produces(MediaType.TEXT_HTML)
  fun get(): TemplateInstance {
    return landingpage.data("data", "render this <br> tag")
  }
}
``` 

landingpage.html
```
<h1>My content</h1>
<div>
  {data}
</div>
```

Are there any option to turn html rendering for qute data on or did i miss something?

**Comment by mkouba** [comment]
For HTML templates some special characters are [escaped by default](https://quarkus.io/guides/qute-reference#character-escapes) to prevent unintended/dangerous output. You need to use the `raw` or `safe` properties to render the unescaped value: `{data.raw}` or `{data.safe}`.
