### ISSUE TITLE
Using Googe Error Prone for bug detection?

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1335]
How about using http://errorprone.info for this project?

I mean for quarkus' own dev, not to impose it upon its users.

EP can help find (and prevent regressions of) issues such as:
* #1331 String split
* #1327 getDeclaredConstructor().newInstance()
* #1329 resource stream leak
* #1328 use logger instead of printStackTrace()
* probably a bunch more, I just didn't get further, yet

Raising this issue to gauge reactions and see if there are strong objections for activating EP, before sinking more time into continuing to raise more individual PRs with small fixes like the above.

Goal would be gradually leading up to ultimately activating it via something like https://github.com/vorburger/quarkus/commit/ecedd594e341ecd8459156f66437fa79ae77e387 (last commit on [my error-prone-X branch](https://github.com/quarkusio/quarkus/compare/master...vorburger:error-prone-X)).

IMHO doing this only makes sense if there is agreement that we do want to activate enforcement. If there isn't, then this remains a one time exercise and over time new problems creep back in.

**Comment by vorburger** [comment]
> Goal would be gradually leading up to ultimately activating it

or we could do this the other way around? As in FIRST merge #1336, then gradually run builds (locally) with `-Perrorprone` and work (together?) through issues it finds, perhaps in some cases refining the proposed final EP configuration - and then when it fully passes switch to enforcement?

**Comment by dmlloyd** [comment]
Well we definitely don't want Guava.  Automated bug checkers are always a bit double-edged, and there's always another bug checker that finds more things or has different opinionation.  This includes IDE inspections BTW.

There's nothing stopping individuals from running checkers or inspections on their own and proposing the resultant fixes.

**Comment by emmanuelbernard** [comment]
Right, my experience is that frameworks have a weird code patterns that don't cope well with such tools _generally_. So let's have someone interested test it for a few weeks and report on the false positives. We usually know what we are doing, but then so is Doug Lea form the website quote ;)

**Comment by vorburger** [comment]
Just to make sure we don't run into a major misunderstanding because of one overall only very small point here: So using Googe Error Prone for bug detection DOES NOT REQUIRE to use Guava. ONLY [one (of many) particular check](https://errorprone.info/bugpattern/StringSplitter) suggested to use  (Guava's) `Splitter` instead of `String.split()` - that's all. If we agree _StringSplitter_ has value, but want to I guess we could just "steal" and copy paste it. If we disagree, we can easily configure EP in the POM to ignore that particular check - trivial.

**Comment by dmlloyd** [comment]
For now, if you want to run code checking tools locally and post fixes to identified problems, go ahead.  I don't think we want to pull in bug checkers though.  At least not at this time.

**Comment by vorburger** [comment]
IMHO doing this only makes sense if there is agreement that we do want to activate enforcement at least eventually. If there isn't, then this remains a one time exercise and over time new problems creep back in. 

To make it easier to run code checking tools locally and gradually post most fixes such as #1329 #1327 #1328 and test it for a few weeks and tune the configuration on possible false positives (e.g. the particular check suggested to use (Guava's) Splitter instead of String.split() could be disabled), would require acceptance of #1336 (`-Perrorprone`), otherwise it's a PITA to do this in practice.

**Comment by gsmet** [comment]
Let's close it for now.
