### ISSUE TITLE
Hibernate Reactive hot reload issue

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#13355]
**Describe the bug**

In dev mode, when I update an `entity`, I get:

```
Type specified for TypedQuery [me.escoffier.pirate.quotes.model.Quote] is incompatible with query return type [class me.escoffier.pirate.quotes.model.Quote]
```

I was updating a named query:

```
@NamedQuery(name = "Quotes.findAll", query = "SELECT f FROM Quote f")
```

**Expected behavior**
It should work :-D 

**Actual behavior**
It does not work

**To Reproduce**

A simple entity with a named query in dev mode should reproduce it.

**Comment by Sanne** [comment]
@aguibert could you have a look at this one?

**Comment by aguibert** [comment]
Sure, I'll take a look

**Comment by aguibert** [comment]
@cescoffier I attempted to reproduce this issue on Quarkus 1.10.2.Final and was not able to force any unexpected errors with the scenario you described. Are you still able to reproduce this issue? If so, you can please push up a reproducer so I can take a look?

FYI here is the repo I used for an attempted reproducer: https://github.com/aguibert/basic-quarkus-mvn/tree/quarkus-bug-13355
Different scenarios I tried were:
 - Adding a new property to the Fruit entity
 - Updating the named query from `SELECT f FROM Fruit f` to `SELECT f FROM Fruit f ORDER BY f.name`
 - Updating the rest endpiont

To use the sample reproducer, you can hit a combination of these endpoints:
 - create a new fruit: `GET http://localhost:8080/create`
 - list all fruits with named query: `GET http://localhost:8080/fruits`

**Comment by cescoffier** [comment]
I may likely have been fixed in the meantime. 
The application I was using mixed gRPC and Hibernate Reactive. 

Let's close this issue and if I see it again, I will provide a reproducer.
