### ISSUE TITLE
gRPC client reponse dispatched on the wrong thread

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#13357]
A gRPC client response got dispatched on a gRPC executor instead of the event loop.

**Comment by Andro999b** [comment]
@cescoffier Is it released? Cause i observe similar issue whit grpc streams.  
onMessage listener calles on event-loop thread and onClose called worker thread. 
Because of this stream can be closed when message recived.
I am using quarkus 1.11.3

**Comment by cescoffier** [comment]
Yes, it was released. Can you open another issue with a reproducer?

**Comment by Andro999b** [comment]
@cescoffier I have created issue with details https://github.com/quarkusio/quarkus/issues/15187
