### ISSUE TITLE
Gelf test timing out

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#13364]
@loicmathieu so we just add this failure for native tests in a Hibernate ORM PR:
```
2020-11-18 14:48:15,298 INFO  [io.qua.log.gel.it.GelfLogHandlerResource] (executor-thread-1) Some useful log message
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.362 s <<< FAILURE! - in io.quarkus.logging.gelf.it.GelfLogHandlerIT
Error:  io.quarkus.logging.gelf.it.GelfLogHandlerIT.test  Time elapsed: 12.094 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a io.quarkus.logging.gelf.it.GelfLogHandlerTest 1 expectation failed.
Expected status code <200> but was <400>.
 within 10 seconds.
Caused by: java.util.concurrent.TimeoutException
```

https://github.com/quarkusio/quarkus/pull/13352/checks?check_run_id=1418454217

I don't know if we just need to set a higher timeout or if that means we won't be able to test things for Gelf?

**Comment by loicmathieu** [comment]
This is what I was afraid of :(

This should be this timeout that needs to be increase: https://github.com/quarkusio/quarkus/blob/master/integration-tests/logging-gelf/src/test/java/io/quarkus/logging/gelf/it/GelfLogHandlerTest.java#L51

Ideally we should switch to a more "clever" think than awaiting, I need to check but there should be some API that we can request to know if the UDP input is ready.

As a temporal solution, the wait can be increase to 10s, on my local computer 2s was enought.
