### ISSUE TITLE
Add configuration property to disable http access log for certain routes

### ISSUE THREAD

**Issue by rohit-s8** [quarkusio/quarkus#13377]
**Description**
Quarkus provides a way to log the http calls being made to it via the config property `quarkus.http.access-log.enabled`and this is just fine. However, in a kubernetes environment, this usually means that all the liveness and readiness probes also get logged which makes the logs very messy (IMO). So it would be great if there was a property like `quarkus.http.access-log.disabled-routes` where we specify which routes will not be logged and for good measure, this can be defaulted to routes like /health, /health/live, /health/ready and /metrics.

**Implementation ideas**

**Comment by geoand** [comment]
I think this makes sense. 

WDYT @stuartwdouglas @cescoffier @kenfinnigan @ebullient ?

**Comment by ebullient** [comment]
y. A similar mechanism exists in micrometer to exclude urls.

I don't know that I would exclude them by default. It can be the easiest first check that things are working properly (even before your endpoint works).

**Comment by kenfinnigan** [comment]
Probably should be a follow on from #13144 to make it easier as it can be anything under the endpoint prefix is ignored

**Comment by rohit-s8** [comment]
I don't see anything in #13144 that talks about configuring logging for non application endpoints.

**Comment by akoufa** [comment]
Hello to all. Is there any update on this ? Is this possible now ?

**Comment by daurrutia** [comment]
Any chance there'd be an example for path such as `/auth/resources/nje61/...`?

**Comment by tweinreich** [comment]
> Any chance there'd be an example for path such as `/auth/resources/nje61/...`?

When you take a look at the code it is just a regex. For your example it would be `/auth/resources/nje61/.*`

I know this reply is late but I want to add it in case someone else is searching for an example (maybe it could be added to the documentation / tutorials).

**Comment by geoand** [comment]
> maybe it could be added to the documentation

Documentation enhancements are always welcome!
[This](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/http-reference.adoc#10-configuring-http-access-logs) is the where such an example could be added.
