### ISSUE TITLE
Add additional properties to the quarkus GELF extension

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#13370]
**Description**

Quarkus GELF extension is based of below library. However, it doesn't support all the properties of the original library. Two very important features for example. These additional knobs improves the user experience, performance, and cost savings for the Quarkus users.

- **includeLocation**  by default this option is set as true, in performance sensitive application we want to turn this off because collection of location information is expensive (snapshot of stacktrace and walk the stacktrace)

- **includeLogMessageParameters** log storage is expensive, this is one of the parameters where users should have the option set this as **false**. Currently we cannot do that with Quarkus extension

https://logging.paluch.biz/examples/jbossas7.html

**Implementation ideas**
Just add _all the available options_ from the original library to Quarkus GELF extension.

**Comment by missourian55** [comment]
@loicmathieu I closed the original issue https://github.com/quarkusio/quarkus/issues/13334

**Comment by loicmathieu** [comment]
@missourian55 #13384 will provides the needed configuration options.

**Comment by missourian55** [comment]
@loicmathieu Tested the new functionalities in `1.11.0.Beta1` and works great. Thank you very much.

Can we bump the version of logstash gelf to **1.14.1** from **1.14.0**? It contains important GelfTCPSender fix

**Comment by gsmet** [comment]
I added it to Dependabot here https://github.com/quarkusio/quarkus/pull/14050 to that it gets regularly updated.
