### ISSUE TITLE
Enhancements in @Startup annotation

### ISSUE THREAD

**Issue by ivannov** [quarkusio/quarkus#13395]
**Description**

Right now, when a bean is annotated with the `io.quarkus.runtime.Startup` annotation, it is eagerly instantiated by the Quarkus runtime when the applications starts.

Sometimes for such beans a Quarkus application developer may decide to create alternative that should be picked up in test or dev mode or when a certain Quarkus profile is active. However, due to the nature of the observers, in case of using `@Startup` alternatives are ignored.

**Request**

Make it possible (with an annotation attribute for example) to only enable the startup event observers in certain launch mode(s) or profile(s) (whichever is more suitable). The default should be _ALL_.

**Additional references**

More info in this thread: https://groups.google.com/d/msgid/quarkus-dev/CACYLA9HxTNyEEV8KxtP0JQJkDA-kOb3wg6zaJawSO4egOzWh%2Bg%40mail.gmail.com

**Comment by mkouba** [comment]
Hm, I liked the idea. But in fact, you can simply annotate your bean with `@UnlessBuildProfile("test")` and it will be completely ignored during tests automatically, i.e.:
```java
@UnlessBuildProfile("test")
@Startup
class MyBean {
 
   @PostConstruct
   void init() {
      // ...do some stufff - but this method will never be called during tests   
   }
}
```
So it's probably unnecessary since we have an annotation-based alternative even now. @geoand @manovotn WDYT?

**Comment by geoand** [comment]
Very good point @mkouba !

+1 on just reusing what we have

**Comment by manovotn** [comment]
+1 for `@UnlessBuildProfile("test")`, let's not re-introduce what we already have.

**Comment by ivannov** [comment]
I can confirm that the proposed solution works for me.

I am OK to close the issue
