### ISSUE TITLE
logging-sentry: Add config option for "server_name"

### ISSUE THREAD

**Issue by medvedev** [quarkusio/quarkus#13412]
**Description**
Target extension: logging-sentry
Currently all the events in sentry have "server_name:localhost". Probably, it's a default value.
Proposal is to add a config option for sentry's server_name and pass it with every event.

**Implementation ideas**
Add config option `log.sentry.server-name` and use it for `DefaultSentryClientFactory.SERVERNAME_OPTION` in [iSentryConfigProvider.getProperty(String key)](https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryConfigProvider.java#L23)

**Comment by gsmet** [comment]
@medvedev are you interested in contributing this feature? It should be easy enough.

**Comment by gsmet** [comment]
Ah ah, I see you're working on it :).

**Comment by medvedev** [comment]
@gsmet can you please check the PR?
https://github.com/quarkusio/quarkus/pull/13414

**Comment by Erfankam** [comment]
I m interested to work on this issue. How to assign issue to myself?

**Comment by medvedev** [comment]
@Erfankam the PR is already merged. But you can pick other Sentry's options from `DefaultSentryClientFactory` stack and make them configurable in Quarkus, in scope of a separate ticket.

**Comment by machi1990** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/13414
