### ISSUE TITLE
No primary artifact to install when using Quarkus 1.10.0.Final + uberJar

### ISSUE THREAD

**Issue by evacchi** [quarkusio/quarkus#13417]
see also https://github.com/kiegroup/kogito-apps/pull/548

**Describe the bug**
Installing a module configured as uberJar causes the main artifact to be no longer installed.
workaround: force install the '.jar.original' file through an extra Maven plugin. In this PR I am using the Groovy Maven plug-in.

**Expected behavior**
main artifact should be installed

**Actual behavior**
 This does not occur if the standard thin jar is used. I understand this is intended. But it causes a chain of other issues e.g. when deploying to a Nexus repo where it is not allowed for `packaging=jar` to only include attached artifacts (see the log below)

This is apparently due to a change introduced in Quarkus 1.10.0.Final -- it didn't occur with  Quarkus 1.10.0.CR1;
Final does not install the main artifact anymore when the project is configured as a uberJar. 

In fact, this info message is printed in all instances where an uberJar is used in kogito-apps:
```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jobs-service ---
[INFO] No primary artifact to install, installing attached artifacts instead. 
[INFO] Installing /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/jobs-service/pom.xml to /home/evacchi/.m2/repository/org/kie/kogito/jobs-service/1.0.0-SNAPSHOT/jobs-service-1.0.0-SNAPSHOT.pom
[INFO] Installing /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/jobs-service/target/jobs-service-1.0.0-SNAPSHOT-runner.jar to /home/evacchi/.m2/repository/org/kie/kogito/jobs-service/1.0.0-SNAPSHOT/jobs-service-1.0.0-SNAPSHOT-runner.jar
[INFO] Installing /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/jobs-service/target/jobs-service-1.0.0-SNAPSHOT-tests.jar to /home/evacchi/.m2/repository/org/kie/kogito/jobs-service/1.0.0-SNAPSHOT/jobs-service-1.0.0-SNAPSHOT-tests.jar
[INFO] Installing /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/jobs-service/target/jobs-service-1.0.0-SNAPSHOT-sources.jar to /home/evacchi/.m2/repository/org/kie/kogito/jobs-service/1.0.0-SNAPSHOT/jobs-service-1.0.0-SNAPSHOT-sources.jar
[INFO] Installing /home/evacchi/Devel/redhat/pr/submarine/kogito-apps/jobs-service/target/jobs-service-1.0.0-SNAPSHOT-test-sources.jar to /home/evacchi/.m2/repository/org/kie/kogito/jobs-service/1.0.0-SNAPSHOT/jobs-service-1.0.0-SNAPSHOT-test-sources.jar
```

**To Reproduce**
```
git clone https://github.com/kiegroup/kogito-apps/ 
git checkout 1.0.x
cd jobs-service
mvn install
```

**Environment (please complete the following information):**
Quarkus 1.10.0.Final

**Comment by gsmet** [comment]
For now you can workaround it with: https://github.com/quarkusio/quarkus/pull/13259/commits/b31b1954c401db637d767c62e4b4cce36de39071

**Comment by gsmet** [comment]
I think we fixed this issue recently.
