### ISSUE TITLE
default on config pojo should behave the same if set in src/main/resources/application.yaml

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#13423]
**Description**
Assuming the following config object:
```
@ConfigProperties(prefix = "greeting")
public class MyConfig {
    public String url;
    public String host;
}
```

and `src/main/resources/application.yaml`;
```
greeting:
  url: http://${greeting.host}
  host: myhost
```
Then the following test will pass:
```
@QuarkusTest
public class MyTestCase {

    @Inject
    MyConfig config;

    @Test
    public void test() {
        Assertions.assertEquals("http://myhost", config.url);
    }
}
```
However, if I move `host=myhost` as a default value, the test won't pass anymore:

```
greeting:
  url: http://${greeting.host}
  # host: myhost
```
and:
```
@ConfigProperties(prefix = "greeting")
public class MyConfig {
    public String url;
    @ConfigProperty(defaultValue = "myhost")
    public String host;
}
```
then I get the following error at startup:
```
Caused by: java.util.NoSuchElementException: SRCFG00011: Could not expand value greeting.host in property greeting.url
```
it is the same behavior if I put the default as the field init: `public String host="myhost";`

I believe that defaults should be picked up in the code, and applied as if the values were present in the `src/main/resources/application.yaml`.

**Comment by radcortez** [comment]
Related with https://github.com/eclipse/microprofile-config/issues/475

**Comment by radcortez** [comment]
This can be achieved with `@ConfigMapping`. Check here: https://github.com/smallrye/smallrye-config/commit/8f40839f4a6f627a32cfb8da83f0a4342590ca14.

Quarkus `@ConfigProperties` is now deprecated, so our recommendation is to use `@ConfigMapping`.
