### ISSUE TITLE
"Authorization" header is being overwritten.

### ISSUE THREAD

**Issue by xpete** [quarkusio/quarkus#13431]
**Describe the bug**
Since version 1.9.0, when a ClientBuilder.newClient() post request is sent, the "Authorization" header is overwritten with a JWT. If the post is sent with a null body, the correct header is sent but if the body has some content the header is overwritten.
Version 1.8.x had the same problem but only when using the microprofile rest client.

**Expected behavior**
The request should send the "Authorization" header that I defined.

**Actual behavior**
A JWT is send in the "Authorization" header.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux Z87-HD3 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 - GraalVM version (if different from Java): openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
 - Quarkus version or git rev: 1.9.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-54-generic", arch: "amd64", family: "unix"

**Comment by sberyozkin** [comment]
@xpete Can you clarify please which JWT do you mean ? None of Quarkus extensions dealing with JWT (quarkus-jwt, quarkus-oidc) would even know about the JAX-RS client

**Comment by gsmet** [comment]
@xpete the best would be to provide a small reproducer.

**Comment by sberyozkin** [comment]
I think I know what this may be about.
MP Rest Client can do the propagation of the original client request headers, so it looks like @xpete is initializing this client with its own `Authorization` header but it is overridden with the original Authorization header (likely `Authorization: Bearer JWT`).

CC @radcortez @FroMage Hi Roberto, Stephane, do you know if something has changed around the way the headers propagation is managed in RestEasy MP RestClient impl ?

**Comment by gsmet** [comment]
One thing that has changed is that we are now properly initializing the provider factory in all cases of usage of the REST Client, which would explain the `Version 1.8.x had the same problem but only when using the microprofile rest client.`.

What probably needs a fix is that the header shouldn't be overridden if existing.

**Comment by xpete** [comment]
I can't create a small reproducer now but the problem is what @sberyozkin described. Only diference is that the "original Authorization header" is  `Authorization: Bearer JWT` but what is being sent is `Authorization: JWT`. The client `Authorization` header I want to send is completely different. There's any way I can avoid the propagation so I don't have to wait for a fix?

**Comment by sberyozkin** [comment]
@xpete Try `ClientRequestFilter` to set your preferred `Authorization` header.

**Comment by xpete** [comment]
Just found that I had an WriterInterceptor that was writing the `Authorization: JWT`. Anyway the WriterInterceptor was configured to be used only on the server side and wasn't supposed to be called on the client side.

**Comment by sberyozkin** [comment]
@xpete OK, I think this issue is invalid then. 
Please create a different issue about `WriterIntertceptor` - note if it just available as a provider then it will likely be picked by both server and the client, perhaps you can experiment with the runtime scope.
But as far as this issue is concerned - lets close it, thanks

**Comment by gsmet** [comment]
@kenfinnigan do you know if there's a way to register a provider only for server or client? For some of them, it makes perfect sense.

**Comment by kenfinnigan** [comment]
If a provider has `@Provider` on it then I believe it's discovered for both situations.

If it doesn't have the annotation, it can be included for use with the client with the programmatic API or `@RegisterProvider` annotation on the REST Client interface

**Comment by gsmet** [comment]
@xpete I just stumbed upon this: `@ConstrainedTo(RuntimeType.SERVER)` that you can use on a provider.

Could you have a look if it fixes your issue? If so I will document it properly.

**Comment by xpete** [comment]
@gsmet It works. Thanks!
