### ISSUE TITLE
Unleash extension

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#13434]
**Describe the extension**
Hi,

we do continue rolling out the Quarkus as a new technology stack in the projects. The next missing piece for us is the Unleash feature toggle extension. I created a base structure for the extension which contains one producer for the Unleash object. 

The original PR https://github.com/quarkusio/quarkus/pull/13426 which should be move in to the `quarkiverse` organization.

To-do:
- [x] register classes for reflection
- [x] native image
- [ ] extend unleash configuration
- [ ] unit test
- [ ] integration test
- [ ] documentation

**Additional context**
The `Unleash` java SDK client is a rest client which call the `Unleash` service. For the unit and integration test we can use Testcontainers.

My test application: https://github.com/andrejpetras/quarkus-unleash-test

**Comment by gsmet** [comment]
I created the project here: https://github.com/quarkiverse/quarkiverse-unleash .

You will have to adjust your extension to follow the naming conventions: https://github.com/quarkiverse/quarkiverse/wiki#joining-quarkiverse .

Feel free to ask for help if you need it.

I'm not exactly aware of all the bells and whistles so I will let @gastaldi set them up once he's back from PTO :).

**Comment by gastaldi** [comment]
Thanks @gsmet, it looks good overall, just needs some minor tweaks. I described the steps in https://github.com/quarkiverse/quarkiverse/wiki/NewProject
