### ISSUE TITLE
Provide a Neo4j (embedded) test resource.

### ISSUE THREAD

**Issue by michael-simons** [quarkusio/quarkus#13438]
**Description**
I discovered test resource and their base interface `QuarkusTestResourceLifecycleManager`. I like the fact that one can take care of

* providing an ephemeral test resource running "somewhere" else
* plus a direct way to change the properties.

I would like to see this for Neo4j. 

**Implementation ideas**

I have two suggestions. One based on Neo4j Testcontainers which I do maintain (see https://www.testcontainers.org/modules/databases/neo4j/) or one based on our embedded version. This could work much like the H2 resource.

I have a working implementation here: https://github.com/michael-simons/neo4j-from-the-jvm-ecosystem/blob/master/quarkus-reactive/src/test/java/org/neo4j/examples/jvm/quarkus/reactive/movies/EmbeddedNeo4jTestResource.java

I am happy to contribute this in one way or the other to Quarkus.

**Comment by michael-simons** [comment]
How would you see this implemented, @machi1990 ? 

Pro using Neo4j Testharness:
* Speed
* No docker
* Dedicated methods to provide fixtures
Contra
- Tons of dependencies
- Using enterprise edition is not that straight forward

Pro using Testcontainers
* No dependencies
* Using a more realistic approach in regards of network
* Easy to switch image between community and enterprise edition
Contra
* Docker
* Speed

I would have some cycles in the upcoming weeks to take care of this.

**Comment by machi1990** [comment]
Good question @michael-simons , I do not have a recommendation or strong opinion on either really. I've seen both approaches used on the repo. 

Maybe @gsmet and @geoand would know better.

**Comment by geoand** [comment]
Great idea!

I generally prefer the embedded way when it's an option.

Testcontainers for me is great when the service is not a JVM service.

**Comment by michael-simons** [comment]
One good reason for test containers is that selecting the version would be ideally an init parameter of the test support, pointing to the image in use. Which might even be one held in a local repo with a fixture build in. Quarkus users than wouldn't need to deal with the dependencies of the embedded Neo4j product.

I personally do recommend embedded for stored procedure development and where I am sure I have the last word about the version and dependency management. It's hard on a framework side to keep up with the dependencies it bring.

**Comment by michael-simons** [comment]
I think this can be closed since we have the dev-services support based on containers for a while now.
