### ISSUE TITLE
google/protobuf/any.proto: File not found.

### ISSUE THREAD

**Issue by sshaaf** [quarkusio/quarkus#13430]
**Describe the bug**
helloworld.proto is unable to import the any.proto from the classpath. This should be there by default since the grpc extension is using the protobuf-java jar file e.g. protobuf-java-3.13.0.jar

**Expected behavior**
Should be able to use proto files included in the protobuf-java-XX-jar which is likely pulled from the grpc extensio.

**Actual behavior**
google/protobuf/any.proto: File not found.
helloworld.proto:9:1: Import "google/protobuf/any.proto" was not found or had errors.

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.
archive attached
[quarkus-pulumi-grpc.zip](https://github.com/quarkusio/quarkus/files/5582607/quarkus-pulumi-grpc.zip)

1. run `mvn compile`
 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin xx-mac 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.9.2.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
mvn

**Additional context**
(Add any other context about the problem here.)

**Comment by michalszynkiewicz** [comment]
@sshaaf thank you for your report.
The issue with import is fixed in 1.10.0.Final.

You can use io.quarkus:quarkus-bom:1.10.0.Final as the platform to have it working :)
