### ISSUE TITLE
quarkus-mongodb-client Unsatisfied dependency for type com.mongodb.client.MongoClient and qualifiers [@MongoClientName(value = "myName")]

### ISSUE THREAD

**Issue by waldimiro** [quarkusio/quarkus#13437]
**Describe the bug**
I have an businesslogic-app and a rest-app. The rest-app include the businesslogic-app as dependency (lib). I declare in a class of businesslogic-app a MongoClient attribute annotated as @MongoClientName("myName"). Mongo properties are declared in the rest-app application.properties. 

**Expected behavior**
MongoDB client for "myName" must be injected.

**Actual behavior**
javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.mongodb.client.MongoClient and qualifiers [@MongoClientName(value = "myName")]

Without @MongoClientName annotation it works.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windos 10
 - Output of `java -version`: openjdk-14
 - Quarkus version or git rev: 1.9.2.FInal
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Comment by loicmathieu** [comment]
Quarkus have an __unused bean removal__ functionality that will remove not used beans.

As you use a separate dependencies, do you take care of configuring bean discovery for your **businesslogic-app** or its beans will not be discovered, and if only the beans from your **businesslogic-app** module uses the MongoDB client, the client will be seen as not used and removed from the bean container.

The easier way is to define the Jandex plugin inside the pom.xml of your **businesslogic-app** module, more info here: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

**Comment by waldimiro** [comment]
Hi @loicmathieu thanks. I added the index without success. What I don't understand is why if I omit the @MongoClientName annotation it works?

**Comment by gsmet** [comment]
@waldimiro if you use a `@MongoClientName` qualifier, you config needs to register a named client such as:

```
quarkus.mongodb.myName.connection-string=...
```

with `myName` being what you have in your qualifier.

I suspect you're not doing that and that you are defining the default client.

**Comment by waldimiro** [comment]
Hi @gsmet how I wrote: Mongo properties are declared in the rest-app application.properties. I checked again, they are correct.

**Comment by loicmathieu** [comment]
@waldimiro can your create a small reproducer, or at least give us your `application.properties` content ?

**Comment by waldimiro** [comment]
@loicmathieu the application.properties follows the Quarkus MongoDB description, properties resides in the rest-app, the MongoClient is injected in a class in businesslogic-app. Hier the snippet:

...
#
# DATASOURCE (rest-app)
#
quarkus.mongodb.myName.connection-string=mongodb://localhost:27017
quarkus.mongodb.myName.database=myName
...

**Comment by loicmathieu** [comment]
@waldimiro can you enable debug logging from Arc processor to determine if it's a bean being removed ?

```
quarkus.log.category."io.quarkus.arc.processor".level=DEBUG
```

Then copy/paste here the Arc debug logs.

**Comment by gsmet** [comment]
I think it would be easier if we could get a simple project reproducing your issue. It shouldn't be too much work to prepare it AFAICS.

**Comment by loicmathieu** [comment]
@waldimiro did you had time to prepare a reproducer ? Or did you find a way to fix your issue ?

**Comment by loicmathieu** [comment]
Closing the issue as we asked for more info for the creator 6 months ago.

@waldimiro please feel free to re-open it if needed.
