### ISSUE TITLE
Link to Graal (substratevm) reflection documentation is broken

### ISSUE THREAD

**Issue by sleberrigaud** [quarkusio/quarkus#13447]
`https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md` is no longer valid, it should be replaced by `https://github.com/oracle/graal/blob/master/substratevm/Reflection.md`

**Comment by sleberrigaud** [comment]
I quickly created a small PR with fixes to more links, https://github.com/quarkusio/quarkus/pull/13448

**Comment by jaikiran** [comment]
The linked PR has been merged. Closing this issue.
