### ISSUE TITLE
Getting NullPointerException for open tracing with jaeger

### ISSUE THREAD

**Issue by krnkhanna1989** [quarkusio/quarkus#13440]
**Getting NullPointerException for open tracing with jaeger**

**There should not be any exception.**

**Actual behavior**
Exception in thread "pool-8-thread-1" java.lang.NullPointerException
	at io.quarkus.jaeger.runtime.MDCScope.<init>(MDCScope.java:31)
	at io.quarkus.jaeger.runtime.MDCScopeManager.activate(MDCScopeManager.java:17)
	at io.smallrye.opentracing.OpenTracingAsyncInterceptor.applyContext(OpenTracingAsyncInterceptor.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.jboss.resteasy.microprofile.client.impl.MpClientInvocation$Decorator.lambda$decorate$0(MpClientInvocation.java:90)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Configurations that I used**

quarkus.log.console.format=%p, %d{yyyy-MM-dd HH:mm:ss.SSSZ}, traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled}, [%c{3.}], %s%e%n
# configurations for jaeger
quarkus.jaeger.service-name=load-auth-service
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.endpoint=http://localhost:14268/api/traces

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
 - Quarkus version or git rev: 1.7.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
Dependency used for open tracing:
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-opentracing</artifactId>
</dependency>

**Comment by geoand** [comment]
@krnkhanna1989 would be able to provide a small sample project that exhibits the behavior you describe?

Thanks

**Comment by pat-karakun** [comment]
I have the same NPE using Quarkus 1.9.2.Final or 1.11.1.Final when trying to invoke an asynchronous method (for example returning Uni<byte[]>) on a REST client.
There is no NPE when invoking a corresponding synchronous method (returning byte[]).
There is also no NPE when disabling Quarkus Jaeger open tracing with 'quarkus.jaeger.enabled=false'.

As the reporter didn't provide a sample project and nothing seems to be done without it, I attach a small maven project to reproduce the issue, just set quarkus.jaeger.enabled to true in application.properties.

[quarkus-jaeger-npe.zip](https://github.com/quarkusio/quarkus/files/5944786/quarkus-jaeger-npe.zip)

**Comment by pat-karakun** [comment]
I slightly extended the sample project such that the project provides an own REST resource that can be accessed (so no need to set a valid URL providing a Pdf or similar). Only Quarkus has to be started (`mvn compile quarkus:dev`) before executing the test(s).

[quarkus-jaeger-npe.zip](https://github.com/quarkusio/quarkus/files/5945156/quarkus-jaeger-npe.zip) (new version)

**Comment by jnsfrg** [comment]
I am having the exact same issue with Quarkus 1.11.2 as well. @pat-karakun did you find any way around this?

**Comment by gsmet** [comment]
@pat-karakun @jnsfrg could you test my PR here: https://github.com/quarkusio/quarkus/pull/15007 ?

https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master should be helpful except you need to get my branch.

It sure fixes the NPE but I have no idea if the issue is more complex than that and if the `MDCScope` shouldn't have been created in the first place.

**Comment by gsmet** [comment]
@Ladicek created a PR for SmallRye OpenTracing here: https://github.com/smallrye/smallrye-opentracing/pull/173 .

Hopefully, we will be able to update to a new version in Quarkus soon. Stay tuned.

**Comment by radcortez** [comment]
@pat-karakun I gave it a try with your example and with the following update: https://github.com/quarkusio/quarkus/pull/15015. It seems to work.

Do you mind to confirm as well? Thanks!

**Comment by pat-karakun** [comment]
bad timing... I'm out of office for a week and won't be able to confirm personally. But I ask my teammembers whether someone can do it earlier.

**Comment by radcortez** [comment]
> bad timing... I'm out of office for a week and won't be able to confirm personally. But I ask my teammembers whether someone can do it earlier.

Thanks! Have fun :)

**Comment by jnsfrg** [comment]
I gave it a try using https://github.com/quarkusio/quarkus/pull/15015 with my app and it seems to resolve the issue. Thanks for the great support!
