### ISSUE TITLE
quarkus-maven-plugin uberJar configuration knob should be clearly documented

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1344]
In https://github.com/quarkusio/quarkus/issues/1305, @stuartwdouglas proposed using `quarkus-maven-plugin`'s configuration knob `uberJar`, in response to an OpenShift S2I related problem from @siamaksade  (which is not the point of this issue):

> Try `<uberJar>true</uberJar>` in the maven plugin config

I do not know what that option is for, can't find it mentioned on the site in the docs, and [its Mojo source code has no documentation](https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java) either. I feel it would be beneficial do clearly document what that does and its intended use.

The reason why it seems to be me that it would be good to write up doc about it is that appears to be  confusingly "dangerous", as it it actually creates huge instead of minimal JARs? Here is the result of a quick test I just did:

Running `mvn package; ll target/` in quarkus-quickstarts/getting-started as it currently is:

    -rw-r--r--. 1 vorburger vorburger 3.3K Mar  8 13:57 quarkus-quickstart-1.0-SNAPSHOT.jar
    -rw-r--r--. 1 vorburger vorburger  34K Mar  8 13:57 quarkus-quickstart-1.0-SNAPSHOT-runner.jar

after adding the following:

    <artifactId>quarkus-maven-plugin</artifactId>
    <version>${quarkus.version}</version>
    <configuration>
        <uberJar>true</uberJar>
    </configuration>
    <executions>

re-running `mvn package; ll target/` in quarkus-quickstarts/getting-started instead creates:

    -rw-r--r--. 1 vorburger vorburger 3.3K Mar  8 14:00 quarkus-quickstart-1.0-SNAPSHOT.jar.original
    -rw-r--r--. 1 vorburger vorburger 8.9M Mar  8 14:00 quarkus-quickstart-1.0-SNAPSHOT-runner.jar

NB how the runner.jar jumped from 34K to 8.9M .. not sure that is what we want to show off? :smile:

**Comment by geoand** [comment]
> NB how the runner.jar jumped from 34K to 8.9M .. not sure that is what we want to show off?

The non uberjar is small because it does not contain the dependencies. If you however look at the `lib` directory you will see them :)

**Comment by cescoffier** [comment]
As said in another issue, I would prefer avoiding using a fat jar in a container

**Comment by geoand** [comment]
#1345 proposes an update to only have a single file with the `.jar` suffix (same thing we do for uberJar basically)

**Comment by vorburger** [comment]
> The non uberjar is small because it does not contain the dependencies. If you however look at the lib directory you will see them :)

Duh! OK now (after having had a look at the `MANIFEST.MF` ..) I fully understand what we are doing here ... sorry I'm a little slow! :smile: I I'll raise a PR proposing adding some documentation about how this works - OK as JavaDoc, or better elsewhere? That will wrap up this issue.

**Comment by geoand** [comment]
> > The non uberjar is small because it does not contain the dependencies. If you however look at the lib directory you will see them :)
> 
> Duh! OK now (after having had a look at the `MANIFEST.MF` ..) I fully understand what we are doing here ... sorry I'm a little slow!  I I'll raise a PR proposing adding some documentation about how this works - OK as JavaDoc, or better elsewhere? That will wrap up this issue.

No worries it's new stuff :)

Not sure about the JavaDoc thing, better let others comment :)

**Comment by vorburger** [comment]
Closing this issue - too lazy to contribute doc; what `uberJar` does is actually pretty obvious.
