### ISSUE TITLE
Arguments passed with -Dquarkus.args are ignored in dev mode

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#13451]
**Describe the bug**
When passing args as below:
```
mvn clean compile quarkus:dev -Dquarkus.args='first second'
```
The @QuarkusMain application does not receive the said arguments, while I would expect it should.

**To Reproduce**
```
git clone https://github.com/aldettinger/quarkus-13451-reproducer.git
cd quarkus-13451-reproducer
mvn clean compile quarkus:dev -Dquarkus.args='first second'
```
The maven outcome contains:
```
From Main
args.length:0
```
While I would expect the length to be 2.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux ag.remote.csb 3.10.0-1160.2.2.el7.x86_64 #1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
 - Quarkus version or git rev: 
`1.10.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /home/..../dev/maven/apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /home/.../.sdkman/candidates/java/11.0.8.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.2.2.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by jtama-op** [comment]
Fails with io.quarkus:quarkus-maven-plugin:1.10.0.Final

Works with Fails with io.quarkus:quarkus-maven-plugin:1.9.2.Final

**Comment by gsmet** [comment]
@aloubyansky could you have a look at this one? If @jtama-op is right, it would be a regression introduced by one of your changes.

Thanks!

**Comment by jtama-op** [comment]
I will try to find the exact lines on monday.

**Comment by aloubyansky** [comment]
It is a regression. Here is a fix https://github.com/aloubyansky/quarkus/commit/e81638925977af9152d1a0faabfc0888addf0124
Apparently we have no tests for this. I'll add some and open a PR. Gradle is fine.
