### ISSUE TITLE
RestEasy Jaxb not registered properly anymore

### ISSUE THREAD

**Issue by Sabartius** [quarkusio/quarkus#13453]
**Describe the bug**
After Upgrading our Application from 1.9.2.Final to 1.10.0.Final which uses Jax-b, REST calls fail because there is no MessageBodyReader present anymore

```
RESTEASY003145: Unable to find a MessageBodyReader of content-type application/xml and type class xxx.xxx.xxx
```

The dependecies include

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jaxb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jaxb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jaxb</artifactId>
        </dependency>
```

Funny Note:
In Tests that are run without Quarkus, the Jaxb-Providers are still registered and working

**Expected behavior**
XML should be read with jaxb as before

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: openjdk 11.0.9 2020-10-20 LTS
 - Quarkus version or git rev: 1.10.0.Final

**Comment by gsmet** [comment]
Any chance you could provide a small Maven reproducer? That would be helpful. Thanks!

**Comment by Sabartius** [comment]
Hope it helps: https://github.com/Sabartius/quarkus-jaxb-issue

**Comment by geoand** [comment]
I'll take a look later on today or tomorrow

**Comment by geoand** [comment]
So IIUC you are not using the MicroProfile REST client, but instead relying on the JAX-RS Client?
That is something that's not officially supported, so your mileage may vary.

Furthermore, I tried your reproducer with Quarkus `1.9.2.Final` and it failed with that as well. If there perhaps something missing from the reproducer you uploaded?

**Comment by Sabartius** [comment]
> That is something that's not officially supported, so your mileage may vary.

Thats news to me, good to know.

I can't seem to find any more significant differences between my project and the repro-case, but yeah 1.9.2.Final doesn't seem to work either.

After a bit of fiddling around i found a workaround, so i can delay the inevitable rewrite of my http-clients.
Apparently when registering a dummy MP-RestClient which produces the necessary types, my jax-rs clients start to work again with quarkus 1.10.0.Final. I updated the repro-case accordingly.

```
@Path("testIt")
public interface FakeRestClient {

    @GET
    @Produces("application/xml")
    String get();

    @GET
    @Produces("application/x-www-form-urlencoded")
    String getForm();
}
```

**Comment by geoand** [comment]
Right.

That happens because Quarkus knows that now XML is in play and registers the proper providers.

**Comment by gsmet** [comment]
I wonder if we should force the providers to be added when we add an extension such as `resteasy-jaxb`.

Why would you add it if you didn't want the providers around?
