### ISSUE TITLE
Reactive HTTP and WebSocket connector enhancements

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#13466]
- [ ] add support for STOMP or some other protocol that allows acking/nacking by the remote websocket endpoint 
- [ ] support text messages for websockets
- [ ] add content type headers in http serializers
- [ ] websocket source exception mapper
- [ ] improve conversion error reporting (ATM we have 500 instead of 422 in such case)
- [ ] give a possibility to read response for sent out messages

**Comment by cescoffier** [comment]
@michalszynkiewicz is this issue still relevant?

**Comment by michalszynkiewicz** [comment]
I still think these enchancements make sense.
I don't know when we'd be able to implement them though.

**Comment by michalszynkiewicz** [comment]
moved to https://github.com/quarkiverse/quarkus-reactive-messaging-http/issues/58
