### ISSUE TITLE
Warn when an annotation that is added to a generated class is not a bean defining annotation

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#13465]
**Description**
I recently ran into an issue where for some reason an `Instance` could not find my generated bean with my custom annotation. Turn out the project that annotation is from did not contain a `bean.xml` file, which in turns mean its classes, annotations and interfaces were not registered. It would be helpful if the ClassCreator can check if an added annotation is not a bean defining annotation and warn the user it will be unable to be detected by the CDI.

Alternatives:
- Print this warning when an Instance that searches for an annotation fails to find any classes that match an annotation

**Comment by gsmet** [comment]
Can't say I'm excited about this given you can add annotations for a lot of reasons. So I think we will have to leave it as it is.
