### ISSUE TITLE
Support plural and singular form for add-extension(s) -Dextension(s)

### ISSUE THREAD

**Issue by dashorst** [quarkusio/quarkus#1347]
I tried to add the quarkus-resteasy-jsonb extension to process JSON, but the command fails to add the extension.

```
mvn quarkus:add-extension -Dextension="io.quarkus:quarkus-resteasy-jsonb"
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< nl.topicus.bots:banaan-slack-bot >------------------
[INFO] Building banaan-slack-bot 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:0.11.0:add-extension (default-cli) @ banaan-slack-bot ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.116 s
[INFO] Finished at: 2019-03-08T15:28:18+01:00
[INFO] ------------------------------------------------------------------------
```

It claims to be successful, but examining the POM shows that the dependency was not added. Adding the dependency manually makes my actual problem go away, but I figured the add-extension command should work normally without manually adding extensions.

**Comment by gsmet** [comment]
Hi @dashorst ,

Funny to see you here after all this time (I used Wicket a lot back in the time!).

So it's supposed to be `-Dextensions=` with an **s**. I checked the doc here https://quarkus.io/guides/maven-tooling and it seems to be OK. Did you see the singular form somewhere?

We probably should throw an error if `extensions` is not defined. Or maybe we could also support the singular form?

@cescoffier WDYT?

**Comment by cescoffier** [comment]
`-Dextensions` (plural as you can pass a comma-separated list of extension). 

However, keep this issue open as an error message should be printed, and the build failed.

**Comment by cescoffier** [comment]
Damn @gsmet you'are too fast :-D

**Comment by dashorst** [comment]
Well, probably what threw me off is that the command is called `add-extension`, the singular, not the plural. Instead of copy/pasting from the website I just typed it in, and then I assumed a symmetry between the command and the parameter. Quite illogically I guess?

**Comment by cescoffier** [comment]
From the usability perspective I guess we need to:

* support the singular form
* if neither the singular and plural forms are set; throw an error

**Comment by gsmet** [comment]
@cescoffier yeah and maybe we should also have `add-extensions` as an alias to `add-extension`. @dashorst definitely has a point on the consistency between the command and the option.

**Comment by cescoffier** [comment]
Agreed about the alias.

**Comment by cescoffier** [comment]
@gsmet if you wonder why I removed the "..." it's because of the release script.

**Comment by dashorst** [comment]
👍 🥇
