### ISSUE TITLE
Hibernate validator does not work with extending interfaces

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#13470]
**Describe the bug**
`quarkus-hibernate-validator` does not work if class implements a resource interface that extends another interface.

```java
public interface BookResource {

    String PATH = "/books";

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    String hello(@NotNull @QueryParam("name") String name);
}

@Path(ScienceBookResource.PATH)
public interface ScienceBookResource extends BookResource {

    String PATH = BookResource.PATH + "/science";
}

public class ScienceBookResourceImpl implements ScienceBookResource {

    @Override
    public String hello(String name) {
        return "Hello " + name;
    }
}
```

This used to work in Quarkus 1.6.2 but seems to be broken in some of the higher versions.

**Expected behavior**
`quarkus-hibernate-validator` should correctly validate even such resources.

**Actual behavior**
`quarkus-hibernate-validator` does not validate even such resources.

**To Reproduce**

```sh
git clone git@github.com:Meemaw/quarkus-validation-bug.git quarkus-reproducer-hibernate
cd quarkus-reproducer-hibernate
./mvnw quarkus:dev
```

Go to: http://localhost:8080/books/science

You will see: `Hello null`

What should happen: Validation error is thrown

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "15.0.1" 2020-10-20
 - Quarkus version or git rev: 1.9.2 Final

**Comment by gsmet** [comment]
Thanks for the detailed report and the reproducer.

I created https://github.com/quarkusio/quarkus/pull/13529 to fix it.

**Comment by Meemaw** [comment]
Great, thanks @gsmet. Does this by any change also fixes https://github.com/quarkusio/quarkus/issues/13029? It seems related.
