### ISSUE TITLE
Vault doesn't work with profiles

### ISSUE THREAD

**Issue by RustamSultansoy** [quarkusio/quarkus#13479]
**Describe the bug**
I want to use vault only for prod profile, so I added this in my properties:
`%prod.quarkus.vault.url=http://localhost:8200
...
%prod.quarkus.datasource.password=${pass-from-vault}

`
**Expected behavior**
I expect that for all profiles except prod it won't work because optional url is empty.
But when prod is active then it should work.
**Actual behavior**
It doesn't work with all profiles.

**Comment by vsevel** [comment]
should be fixed by https://github.com/quarkusio/quarkus/pull/13498

**Comment by geoand** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/13498
