### ISSUE TITLE
HTTP Server does not support `Expect: 100-continue`

### ISSUE THREAD

**Issue by defnull** [quarkusio/quarkus#13478]
**Describe the bug**
A `HTTP/1.1` request with `Expect: 100-continue` is not handled correctly by the HTTP server implementation (vert.x / undertow). This causes timeouts or delays for clients that follow the spec.

**Expected behavior**
The HTTP server implementation should send `100 Continue` or an error response immediately, or at least as soon as the application tries to read from the message body. RFC 7231 5.1.1 states that an HTTP/1.1 server receiving `Expect: 100-continue` "MUST NOT wait for the message body before sending the 100 (Continue) response."

**Actual behavior**
The HTTP server implementation does not send `100 Continue` and waits for message body data. Strict clients will not send any data before they receive `100 Continue`, which never happens, causing a timeout. Less strict clients will wait for a certain time (curl waits for one second by default) and then send data anyway, assuming the server does not implement this part of the spec.

**To Reproduce**
1) Build a minimal jax-rs application that accepts PUT requests and the request body as an `InputStream`. Read from that input stream.
2) Run `echo "foo" | curl -XPUT -T - --expect100-timeout 5 -v http://localhost:8080/path/to/endpoint`. The `-T -` trick forces curl into chunked `100-continue` mode.

You will notice a delay of 5 seconds while curl waits for `100 Continue`. More strict clients (e.g. ffmpeg http protocol handler) will just fail with a timeout, assuming the server is unresponsive.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.10.0.Final

**Comment by defnull** [comment]
Also confirmed for `1.10.0.Final`

**Comment by defnull** [comment]
I guess what's missing is `io.undertow.server.handlers.HttpContinueAcceptingHandler`. Is there a way to add this handler to the stack without waiting for a new quarkus release?

**Comment by stuartwdouglas** [comment]
Here is the Servlet fix: https://github.com/quarkusio/quarkus-http/pull/48

**Comment by defnull** [comment]
Thanks a lot. Since this got merged, I think this can be closed :)

**Comment by gsmet** [comment]
I'm not sure this is fully fixed as the quarkus-http PR has not been merged yet: https://github.com/quarkusio/quarkus-http/pull/48
