### ISSUE TITLE
`IfBuildProfile` is not respected for gRPC `ServerInterceptor`

### ISSUE THREAD

**Issue by cihati** [quarkusio/quarkus#13489]
**Describe the bug**
```java
@ApplicationScoped
@IfBuildProfile("prod")
public final class AuthInterceptor implements ServerInterceptor {
    private static final Logger LOG = LoggerFactory.getLogger(AuthInterceptor.class);

    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
        final ServerCall<ReqT, RespT> call,
        final Metadata headers,
        final ServerCallHandler<ReqT, RespT> next) {

        Status status;
        String profile = ProfileManager.getActiveProfile();
        status = Status.UNAUTHENTICATED.withDescription("We should not be here in this profile: " + profile);

        call.close(status, headers);
        return new ServerCall.Listener<>() {
            // noop
        };
    }
}
```

**Expected behavior**
`AuthInterceptor` should not be activated unless `prod` profile is used.

**Actual behavior**
I see the output `rpc error: code = Unauthenticated desc = We should not be here in this profile: test` when running in `test` profile

**To Reproduce**
Relevant code piece is given above

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin cihat-layer-mbp.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 

```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

 - GraalVM version (if different from Java): 

 - Quarkus version or git rev: 1.9.2.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Mac OS X 10.15.4 x86_64
```

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
@mkouba At runtime we do a simple lookup for all beans implementing `ServerInterceptor`. How can we handle the `IfBuildProfile` in this case? Should I filter out the bean directly, or there is some magic happening somewhere?

**Comment by mkouba** [comment]
I think that the bean should not be available at all, i.e. no need to filter anything. Is there a reproducer available? CC @geoand

**Comment by cihati** [comment]
I was just trying to create a reproducer for this, and I failed. Then I realized that this might be due to my multi-project setup with gradle (I have a `common` project where I implement this `ServerInterceptor`, and another project that uses this `common` project to do some business logic), and voila, it worked! (I basically applied the plugin as suggested here https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index to the `common` project's `build.gradle`)

However, my integration tests are still suffering from this issue! For some reason, the issue persists in my Docker image: `AuthInterceptor` is in fact being used even when not using `prod` profile!

any ideas @mkouba ?

**Comment by mkouba** [comment]
I have no idea. @aloubyansky or @glefloch might know more...

**Comment by glefloch** [comment]
that's really weird, gradle should not be part of something special here. Could you share your module with failing integration test?

**Comment by glefloch** [comment]
@cihati do you still have the issue? if yes, can you share a sample?

**Comment by cihati** [comment]
Hey @glefloch -- we ended up switching from Quarkus. When I raised the issue, I could not create a small repro.

**Comment by cescoffier** [comment]
Closing - please re-open if needed.
