### ISSUE TITLE
Extension to view the values configured by MicroProfile config in development mode

### ISSUE THREAD

**Issue by hpehl** [quarkusio/quarkus#1349]
Integrate the [config extension](https://github.com/hpehl/quarkus-config-extension) into Quarkus. Can come handy in both dev and production mode.

**Comment by emmanuelbernard** [comment]
I was thinking of dev mode only actually to avoid some security disaster.

**Comment by hpehl** [comment]
Yes, makes sense to me. We could make it part of the configuration: Default would be enabled in devmode, disabled in production mode.

**Comment by emmanuelbernard** [comment]
We hate configuration toggles. They complicate the user experience. You really need an important reason to bring one in. What usage flow would not work if we  were not allowing this to be seen in PROD mode?

**Comment by hpehl** [comment]
Agreed, no toggles. I've updated the config extension to only work in development mode:
https://github.com/hpehl/quarkus-config-extension/commit/3530c88c908288c530f82047b8150741f2c9e152

**Comment by gsmet** [comment]
@hpehl do you plan to do it or should I close it?

**Comment by hpehl** [comment]
I'll update the extension and open a PR.

**Comment by stuartwdouglas** [comment]
We can now do this in the config editor in Dev UI, so IMHO this can be closed.

**Comment by hpehl** [comment]
No objections from my side.
