### ISSUE TITLE
Qute extension method with parameters not working in loop

### ISSUE THREAD

**Issue by eamelink** [quarkusio/quarkus#13500]
**Describe the bug**
Given the following extension method: 

    static Set<String> tags(Item item, String category) { return item.tagsForCategory(category); }

The following works:

    {item.tags('foo')} // This prints ['foo', 'bar']

But the following doesn't:

    {#each item.tags('foo')}
      {it}
    {/each}

The Quarkus build fails with:

    io.quarkus.qute.TemplateException: Found template problems (1):
        [1] Incorrect expression: it
	- property/method [tags('foo')] not found on class [org.acme.qute.Item] nor handled by an extension method

The same problem occurs with the {#for} and {#let} tags.

**Expected behavior**

I would expect that I can use tags such {#each} and {#for} to loop over the results of a virtual method.

**To Reproduce**

See https://github.com/eamelink/quarkus-qute-issue-reproducer , and then the /qute/items path.
**Environment 
-  Darwin MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "15" 2020-09-15
 - Quarkus version or git rev: Quarkus 1.9.2

**Comment by mkouba** [comment]
@eamelink Thanks for reporting! Yes, it's a validation problem. I need to check the validation algorithm. You can remove/comment out the parameter declaration as a workaround.

**Comment by mkouba** [comment]
I can confirm that we have a bug in a loop section validation. We need to rework the validation algorithm. 

For now there are 2 workarounds:
1. Remove the `{@java.util.List<org.acme.qute.Item> items}` param declaration, i.e. skip the validation completely
2. Redeclare the param declaration inside the loop, i.e.:
```
{#each item.tags('foo')}
     {@java.lang.String it} <1>
     {it}
{/each}
```
<1> This tells qute to treat `it` as `String`.

And yes, neither of the two is _acceptable_ but that's all we have :-(.
