### ISSUE TITLE
SimpleScheduler: pause doesn't work

### ISSUE THREAD

**Issue by RustamSultansoy** [quarkusio/quarkus#13512]
**Describe the bug**
When you try to inject SimpleScheduler and then call SimpleScheduler::pause nothing happens.

**Expected behavior**
Scheduled jobs should be paused

**Actual behavior**
Nothing happens

**To Reproduce**
Add some method annotated by @Scheduled
Then try to pause scheduler using SimpleScheduler::pause method.

<img width="521" alt="Screenshot 2020-11-27 at 12 26 40" src="https://user-images.githubusercontent.com/73348899/100439210-ea194e80-30ab-11eb-8948-98f8ee8c3b2a.png">
looks like bug is here.

**Comment by mkouba** [comment]
Uf, that's a stupid bug :-(. @RustamSultansoy Would you care to send a PR? The fix is very straightforward. A test could be a little bit more challenging ;-)

**Comment by RustamSultansoy** [comment]
@mkouba yeap, will send a pull request from my personal account later
