### ISSUE TITLE
-Dquarkus.args is not working in dev mode

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#13519]
**Describe the bug**
Following https://quarkus.io/guides/command-mode-reference#dev-mode the command `mvn compile quarkus:dev -Dquarkus.args='--help'` should pass the argument in dev mode but nothing is passed in args.

**Expected behavior**
quarkus.args are passed in `@QuarkusMain` method

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**

Quarkus main;
```java
@QuarkusMain
public class HelloWorldMain implements QuarkusApplication {
    @Override
    public int run(String... args) throws Exception {
        System.out.println("Hello World " + Arrays.toString(args));
        return 10;
    }
}
```

Or attach an archive containing the reproducer to the issue.
Just generated the quarkus app and added the above class.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux Set-FI 5.8.9-200.fc32.x86_64 #1 SMP Mon Sep 14 18:28:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode
 - GraalVM version (if different from Java): 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
 - Quarkus version or git rev: 1.10.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/mstefank/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /opt/java/hotspot/jdk-11.0.8+10
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.9-200.fc32.x86_64", arch: "amd64", family: "unix"

**Additional context**
When compiled to native the arguments are passed normally as expected.

**Comment by jtama-op** [comment]
Duplicate of #13451

**Comment by xstefank** [comment]
thanks @jtama-op
