### ISSUE TITLE
Native image - sources folder is not generated at the location mentioned by documentation

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#13518]
Native image - sources folder is not generated at tle location mentioned by documentation

https://quarkus.io/guides/building-native-image#debugging-native-executable - `The location of source cache is target/{project.name}-{project.version}-native-image-source-jar/sources folder.`

Sources directory produced during the build is `target/sources`

While the docs are expecting `target/{project.name}-{project.version}-native-image-source-jar/sources` path

```
mvn io.quarkus:quarkus-maven-plugin:1.9.2.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello"
cd getting-started
mvn clean package -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11 -Dnative -Dquarkus.native.debug.enabled=true
ls target
```

**Comment by zakkak** [comment]
Good catch @rsvoboda. Thanks!
