### ISSUE TITLE
.debug file next to the native executable is not present when building on macOS using the docker image

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#13517]
https://quarkus.io/guides/building-native-image#debugging-native-executable says `To generate debug symbols, add -Dquarkus.native.debug.enabled=true flag when generating the native executable. You will find the debug symbols for the native executable in a .debug file next to the native executable.`

I'm on macOS and when using mandrel image to build native I don't see `.debug` file.
Using the same commands on RHEL machine I get both native binary and `.debug` file.

Reproducer:
```
mvn io.quarkus:quarkus-maven-plugin:1.9.2.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"
cd getting-started
mvn dependency:sources
mvn clean package -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11 -Dnative -Dquarkus.native.debug.enabled=true
ls target/getting-started-1.0-SNAPSHOT-runner.debug  ## not present when using macOS for the docker based build
```

**Comment by zakkak** [comment]
@rsvoboda is `objcopy` in your `PATH`?
Do you see any message like:
```
Cannot find executable (objcopy) to separate symbols from executable.
```
when using `quarkus.log.level=DEBUG`?

**Comment by rsvoboda** [comment]
Doing
```
brew install binutils 
export PATH=/usr/local/opt/binutils/bin:$PATH
```
before running maven helped, .debug file is present.

Thanks for pointer it wasn't obvious what's wrong and I didn't consider running with `quarkus.log.level=DEBUG`

What about changing `log.debug("Cannot find executable (objcopy) to separate symbols from executable.");` to `log.info...` in NativeImageBuildStep? And Native guide could have a note about `objcopy` in debug section. wdyt?

**Comment by zakkak** [comment]
@rsvoboda I am closing this since you got it working and #13582 hopefully improved the documentation

**Comment by jerboaa** [comment]
> quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11

@rsvoboda @zakkak This doesn't make sense to me. Why would one need to install `objcopy` on the host system for a container-based-native-image-build? For a native-image generation using the Linux container quoted above, Quarkus should be using `objcopy` from the container. The container has it installed. Why the failure then?

```
$ podman run --rm -ti --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11
[quarkus@d1c52e2b2ef0 project]$ objcopy --version
GNU objcopy version 2.30-73.el8
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by jerboaa** [comment]
If it's actually using the host system, this is a bug. It should be using the container instead. It might entail calling the container a second time after the native-image build for stripping debug symbols using `docker run -v <host-path>:/project:z ... --entrypoint /bin/objcopy <objcopy-args>`

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L710 ... system based `objcopy` is invoked

 => this is a bug

Thanks for second eyes on this

**Comment by jerboaa** [comment]
This is a bug. For `-Dquarkus.native.container-build=true` based builds it should use the container to do the stripping. No gymnastics needed on the host system in that case.

**Comment by jerboaa** [comment]
The idea for `-Dquarkus.native.container-build=true` is to not have any native-image tooling installed on the host system and rely on the container. This includes functionality so as to strip debuginfo.

**Comment by rsvoboda** [comment]
@jerboaa should I create new issue for it or it's fine to reopen this one?

**Comment by jerboaa** [comment]
@rsvoboda Feel free to reopen this one.

**Comment by zakkak** [comment]
@rsvoboda I am closing this in favour of https://github.com/quarkusio/quarkus/issues/13754 to keep it more focused
