### ISSUE TITLE
AWS Lambda - APIGatewayV2 adoption and warning

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#13531]
**Describe the bug**

We are migrating our Rest based AWS lambdas to HTTP Lambdas with Payload 2.0 format. During compilation I am getting below error.

I ignored the warning and tested the functionalities. Java mode working correctly, but in the native mode I am always getting null authorizer from *APIGatewayV2HTTPEvent*. I want to resolve below warning and give it a try, any recommendations on how to do that?

```java
Unable to properly register the hierarchy of the following classes 
for reflection as they are not in the Jandex index:
	- org.joda.time.DateTime 
(source: AmazonLambdaProcessor > com.test.demo.AuthorizerLambdaHandler
[com.amazonaws.services.lambda.runtime.events.SimpleIAMPolicyResponse handleRequest(com.amazonaws.services.lambda.runtime.events.APIGatewayV2CustomAuthorizerEvent input, com.amazonaws.services.lambda.runtime.Context context)])
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");
```

**Expected behavior**
APIGatewayV2 work as expected

**Actual behavior**
see above

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macos & linux
 - Output of `java -version`:  Java 11
 - GraalVM version (if different from Java): 20.3.0-java11
 - Quarkus version or git rev: 1.10.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw

**Additional context**
(Add any other context about the problem here.)

**Comment by patriot1burke** [comment]
Linking docs on json format here for future reference on fixing this:

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by patriot1burke** [comment]
@missourian55 A little late to getting to this, but are you deploying regular Lambdas that consume ApiGatewayV2HttpEvent?  Or are you using Resteasy (jax-rs) or some other Quarkus HTTP API?

**Comment by patriot1burke** [comment]
If you are deploying regular lambdas that consume ApiGatewayV2HTTPEvent, the problem in native mode is that we are using Jackson to deserialize this class.  Native doesn't use the core Java lambda runtime.  So, ApiGatewayV2HttpEvent does not have getters and setters so Jackson doesn't know how to convert from json to this class instance.

**Comment by patriot1burke** [comment]
Just need to exclude joda time

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>joda-time</groupId>
                    <artifactId>joda-time</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


Here's what my lambda was:


import java.util.HashMap;
import java.util.Map;

public class TestLambda implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    @Override
    public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent event, Context context) {
        APIGatewayV2HTTPResponse res = new APIGatewayV2HTTPResponse();
        res.setStatusCode(200);
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "text/plain");
        res.setHeaders(headers);
        res.setBody("Hello");
        return res;
    }
}
