### ISSUE TITLE
Throwing AuthenticationFailedException from IdentityProvider.authenticate stalls connection.

### ISSUE THREAD

**Issue by defnull** [quarkusio/quarkus#13559]
**Describe the bug**
The documentation of `IdentityProvider.authenticate` is a little bit unclear on how one should throw `AuthenticationFailedException` or return the same exception wrapped in an `Uni`. I got it wrong and noticed that throwing `AuthenticationFailedException` stalls the client connection without any warning in the logs. Other exceptions (e.g. `RuntimeException`) are properly logged as an error and immediately return a 500 error to the client. This took me a while to figure out...

**Expected behavior**
Throwing `AuthenticationFailedException` from `IdentityProvider.authenticate` should either do the same as returning it wrapped in an `Uni`, or be handled as an application error (just like any other exception) resulting in a 500 error response.

**Actual behavior**
Throwing `AuthenticationFailedException` from `IdentityProvider.authenticate` does not produce an error log entry, does not trigger a 500 error response, and instead stalls the client connection until it times out.

**To Reproduce**

Implement a custom `IdentityProvider` that throws `AuthenticationFailedException`, add one of the auth annotations to a jax-rs resource, then request that resource with credentials.

```java
@ApplicationScoped
public class BasicIdentityProvider implements IdentityProvider<UsernamePasswordAuthenticationRequest> {
	@Override
	public Class<UsernamePasswordAuthenticationRequest> getRequestType() {
		return UsernamePasswordAuthenticationRequest.class;
	}

	@Override
	public Uni<SecurityIdentity> authenticate(UsernamePasswordAuthenticationRequest request,
			AuthenticationRequestContext context) {
		throw new AuthenticationFailedException("Not in the mood");
	}
}

@Path("/test")
@ApplicationScoped
public class TestResource {
	@GET
	@RolesAllowed({ "not-one" })
	public void get200() {
	}
}

// curl http://wrong:pass@localhost:8080/test  # This will block until timeout
```

**Configuration**
```properties
quarkus.http.auth.basic=true
```
**Environment (please complete the following information):**
 - Output of `java -version`: 14.0.2+12-Ubuntu-120.04
 - Quarkus version or git rev: 1.10.1.Final

**Comment by sberyozkin** [comment]
@defnull Please do

`return Uni.createFrom().failure(...)`

It is a FAQ so I'll update the docs and resolve this issue once the doc update is merged

**Comment by defnull** [comment]
I did, and that works as expected. I know that the error was on my side, not following the documentation exactly, but leaking client connections until they timeout is still something that should not happen I think. Perhaps there is room to improve stability even in case of application errors.

**Comment by sberyozkin** [comment]
Hi @cescoffier @jponge 
I wonder, is is possible somehow to have a Quarkus code which catches the escaped exception outside of Uni, for example, here, https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java#L96, and awakens the Uni which would otherwise be activated with `Uni.createFrom().failure(...)` ?

I will certainly document that one should avoid throwing the exceptions directly, but it is not the first time an issue like this one has been opened :-)
What do you think ? Also CC @stuartwdouglas

**Comment by defnull** [comment]
IMHO it would be nice if any `Uni`-returning API that is supposed to be implemented by application developers is at some point wrapped with a stupidity-protection-wrapper that logs and wraps unchecked exceptions and tells the developer to get some more coffee and take a break. It took me a while to find my error, because I first thought it was related to  #13478 somehow or the HTTP client I'm using was misbehaving.

**Comment by cescoffier** [comment]
@sberyozkin I don't understand.

In a Uni, if any stage throws an exception, that exception is propagated. However, in the code you mention, there are no unis, it's just a plain routing context handler.

**Comment by sberyozkin** [comment]
@cescoffier Sorry, missed your comment, yes, Stuart added an extra catch block in #13573
