### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by luszczynski** [quarkusio/quarkus#1355]
Swagger annotations [1] and swagger-ui are supported for API doc? Is there any plan for this feature?

[1] https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X

**Comment by danielpetisme** [comment]
Have a look to
https://github.com/danielpetisme/jhipster-sample-app-quarkus

I've added the following dependencies to the `pom.xml` and it scans your resource to build the Open API specs.
```
 <!-- Swagger -->
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2</artifactId>
      <version>2.0.7</version>
    </dependency>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2-servlet-initializer</artifactId>
      <version>2.0.7</version>
    </dependency>
```

Once done got to http://localhost:8080/openapi.json and you'll find your API description.

If you want swagger-ui too, copy the content of https://github.com/swagger-api/swagger-ui/tree/master/dist into your `src/main/MET-INF/resources` folder.

Update swagger-ui's index.html
```
...
var baseUrl = function() {
        var urlMatches = /(.*)\/swagger-ui\/index.html.*/.exec(window.location.href);
        return urlMatches[1];
      };
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: baseUrl() + "/openapi.json",
...
````
Example:
https://github.com/danielpetisme/jhipster-sample-app-quarkus/tree/master/src/main/resources/META-INF/resources/swagger-ui/index.html

You can now go to http://localhost:8080/swagger-ui/index.html and test "graphically" your API.

Note: I didn't watched yet how to integrate the JWT with swagger-ui's request.

Hope it helps

**Comment by cescoffier** [comment]
Hello Daniel, Can you tell us more about the jhipster part (seem that you
use JHipser).

Also, note that Quarkus supports OpenAPI.

Le sam. 9 mars 2019 à 00:25, Daniel PETISME <notifications@github.com> a
écrit :

**Comment by danielpetisme** [comment]
I'm used to use the JHipster Sample App as a "petclinic/todo" app, a kind of comparison tool.
I know the basecode almost by heart, I can easily compare spring approaches/snippets (data, web, configuration, security, testing, DI, etc.) to any thing else (quarkus here).

@cescoffier I'm sure you have an secret idea 😃 

Do you have any pointer to quarkus OpenAPI support I'm looking for a more "out of the box" approach.

**Comment by cescoffier** [comment]
@kenfinnigan may be able to give more details on the openapi extension (https://github.com/quarkusio/quarkus/tree/master/extensions/smallrye-openapi). Unfortunately, not yet documented.

**Comment by kenfinnigan** [comment]
Quarkus currently includes SmallRye OpenAPI as an extension.

Just add `quarkus-smallrye-openapi` as a `pom.xml` dependency and you will get an endpoint on `/openapi` with all the information.

Not sure if OpenAPI has an equivalent to the Swagger UI or not. We could look at something like that for dev mode

**Comment by danielpetisme** [comment]
@kenfinnigan  you can use swagger-ui as-is
Look at
https://github.com/danielpetisme/jhipster-sample-app-quarkus/tree/openapi

I've added the `quarkus-smallrye-openapi` dependency as you mentioned.

Copy/paste swagger-ui into `src/main/resources/META-INF/resources`
Tweak the `swagger-ui/index.hml`

```
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: baseUrl() + "/openapi", //It request smallrye endpoint
```
https://github.com/danielpetisme/jhipster-sample-app-quarkus/blob/openapi/src/main/resources/META-INF/resources/swagger-ui/index.html#L48

And *voilà*
![Capture d’écran 2019-03-11 à 21 27 28 (2)](https://user-images.githubusercontent.com/593564/54155503-8d43b380-4444-11e9-9af6-a4c9691d1fe5.png)

A swagger-ui integration documentation would be valuable but IMHO you don't need to go further.

**Comment by gsmet** [comment]
@danielpetisme I wonder if we should integrate the Swagger UI in our OpenAPI extension so that you get it out of the box. It's licensed under the Apache License so that could work.

What I'm wondering is if we should find a way to enable it only in development mode (at least the one bundled by default).

Would you be interested in experimenting with that?

**Comment by kenfinnigan** [comment]
As this is easy enough to "drop in" to an application as a third party addition, maybe just a user guide on what to do is sufficient?

My concern is that adding Swagger UI directly will get out of date quickly and require updating the version frequently.

**Comment by gsmet** [comment]
@kenfinnigan I agree we will have to update it from time to time to bring the latest additions/fixes.

But I think having it by default in dev mode would be a nice feature. You could play with your APIs in a second.

Otherwise, you have to download it, push it to your app, update it to point to our OpenAPI URL (that maybe we should change to `/openapi.json` to avoid that).

@emmanuelbernard WDYT?

**Comment by gsmet** [comment]
Some notes of a discussion with Stuart in case we want to have it:

> Stuart Douglas: At the moment most of the integration revolves around adding Servlets
> Stuart Douglas: you would need to add a io.quarkus.undertow.deployment.ServletExtensionBuildItem
> and add a wrapper that can interceptor requests to whatever path and delegates to a ResourceHandler
> io.undertow.servlet.api.DeploymentInfo#addOuterHandlerChainWrapper is probably what you want

**Comment by danielpetisme** [comment]
@gsmet yes I can try to propose something more packaged.

**Comment by danielpetisme** [comment]
Based on the Zulip conversation
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Problems.20with.20Getting.20Started/near/160573859
There is an attempt to use https://github.com/microprofile-extensions/openapi-ext/tree/master/swagger-ui as front end provider for the open api definition (maintained by 1 person only...).

Despite the fact that right now it doesn't work (because of an internal quarkus issue it seems), the approach is smart and worth the try.

**Comment by kenfinnigan** [comment]
Any reason not to just include the Swagger UI directly as opposed to including an external library that does just that?

**Comment by danielpetisme** [comment]
IMHO; Maintenance.
If there is a shared lib with other project there is a greater probability that this lib stays up to date.
My only concerns is that the referenced [lib](https://github.com/microprofile-extensions/openapi-ext/tree/master/swagger-ui) is maintained by 1 person...

It's not complex at all to package a "quarkus-smallrye-swagger-ui" if you prefer to keep the ownership.

If you think it make more sense to have a quarkus package I can try to do an initial contribution (I can commit to a long term maintenance).

**Comment by emmanuelbernard** [comment]
@gsmet I like it (on for dev mode).

**Comment by kenfinnigan** [comment]
@danielpetisme my preference would be for us to include it directly as opposed to an additional dependency that does the wrapping, as then it's an extra step to update/fix Swagger UI

**Comment by danielpetisme** [comment]
@kenfinnigan directly into `quarkus-smallrye-openapi`?

**Comment by gsmet** [comment]
@danielpetisme yes, that would be my preference. And only enable it in dev-mode for now. See my comment here for some indications on how to do it: https://github.com/quarkusio/quarkus/issues/1355#issuecomment-471981874 .

**Comment by danielpetisme** [comment]
Ok I'll try it.

**Comment by gsmet** [comment]
Feel free to ask some guidance in a PR if you have some issues.

**Comment by kenfinnigan** [comment]
It may be simpler to have it as a separate extension that is always included into OpenAPI. Then there’s no confusion over which code does what

**Comment by danielpetisme** [comment]
@kenfinnigan not sure to understand your position (surely a translation misunderstanding).
>@danielpetisme my preference would be for us to include it directly as opposed to an additional dependency that does the wrapping, as then it's an extra step to update/fix Swagger UI

Do you want me to update `quarkus-smallrye-openapi` or create a `quarkus-swagger-ui` extension?
Sorry for the misunderstanding

**Comment by kenfinnigan** [comment]
No problem, can see how I made it confusing.

By not having an additional dependency, I meant purely an external one.

Yes, my preference would be a quarkus-swagger-ui extension that is then added as a dependency to quarkus-smallrye-openapi

**Comment by gsmet** [comment]
@danielpetisme is actively working on it.

**Comment by mboulatian** [comment]
so smallrye-openapi doesn't include swagger annoations like apimodel

**Comment by kenfinnigan** [comment]
@mboulatian it uses the MP Open API annotations, which were based off Swagger/OpenAPI
