### ISSUE TITLE
io.quarkus:quarkus-maven-plugin:0.11.0:create still generates a microprofile-config.properties

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1357]
```
mvn io.quarkus:quarkus-maven-plugin:0.11.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

ls getting-started/src/main/resources/META-INF/microprofile-config.properties

**Comment by emmanuelbernard** [comment]
Maybe gradle and CLI are affected.

**Comment by gsmet** [comment]
It has already been fixed here: https://github.com/quarkusio/quarkus/pull/1313 .

**Comment by emmanuelbernard** [comment]
ah damn, I *searched* for it but the search excluded PRs. I hate that we don't open issues every time.

**Comment by emmanuelbernard** [comment]
@gsmet so we can close it I guess right?

**Comment by gsmet** [comment]
Yes, I think so.
