### ISSUE TITLE
Add a verify method to BcryptUtils

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#13576]
**Description**
BcryptUtils allows a plain text password to get encrypted , but has no methods to verify a plain text password.  It would be  nice to have an utility method for verification as other open source libraries for bcrypt appear to have.

**Implementation ideas**
Below is my unit test method testPasswordHash() that uses BcryptUtils.bcryptHash(String password) method.

I based the verifyPassword(String originalPwd, String encryptedPwd) method on the instruction found on the following Wildfly documentation link:  https://docs.wildfly.org/20/WildFly_Elytron_Security.html

I'm using Java 11 and Quarkus 1.9.2 with the quarkus-security-jpa extension

       public void testPasswordHash() throws Exception {
                
                // get the password the user sent in the post
                String testPassword = "myPassword";

                // get the MCF formatted string to store in the database
                String encryptedPwd = BcryptUtil.bcryptHash(testPassword);

                // verify posted password against the encrypted password from the database
                boolean matches = verifyPassword(testPassword, encryptedPwd);

                Assertions.assertTrue(matches, "passwords match!");
        }

        private boolean verifyPassword(String originalPwd, String encryptedPwd) throws Exception {
                // convert encrypted password string to a password key
                Password rawPassword = ModularCrypt.decode(encryptedPwd);

                // create the password factory based on the bcrypt algorithm
                PasswordFactory factory = PasswordFactory.getInstance(BCryptPassword.ALGORITHM_BCRYPT);

                // create encrypted password based on stored string
                BCryptPassword restored = (BCryptPassword) factory.translate(rawPassword);

                // verify restored password against original
                return factory.verify(restored, originalPwd.toCharArray());
        }

**Comment by sberyozkin** [comment]
@jefrog1844 thanks, I'll close it as a duplicate of #10855, I'll copy your proposal there with CC to you, thanks

**Comment by msis94** [comment]
i try with quarkus eleytron for bycrptutil and it give error : 

Exception in thread "main" java.security.NoSuchAlgorithmException: ELY08028: Invalid algorithm "bcrypt"
