### ISSUE TITLE
AWS Funqy Lambda native image Timeout

### ISSUE THREAD

**Issue by EzxD** [quarkusio/quarkus#13595]
**Describe the bug**
Deploying my funqy lamda function in jvm works perfectly fine.
After cleaning and building new with ``mvn package -Pnative -Dquarkus.native.container-build=true`` and deploying with ``./manage.sh native create`` the functions times out https://i.imgur.com/JVfUfIy.png

**Expected behavior**
Maybe any response? :)

**Actual behavior**
Not getting any response :(

**To Reproduce**

https://github.com/EzxD/Quarkus-Funqy-Native-Example

1. mvn package -Pnative -Dquarkus.native.container-build=true
2. ./target/manage.sh native create
3. send test from AWS get a time out

**Configuration**
```properties
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.funqy.export=helloWorld.
```

**Screenshots**
https://i.imgur.com/JVfUfIy.png

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux Pauls-PC 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 - GraalVM version (if different from Java): openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
 - Quarkus version or git rev: https://github.com/EzxD/Quarkus-Funqy-Native-Example (quarkus verion 1.10.1.Final)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /mnt/c/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.128-microsoft-standard", arch: "amd64", family: "unix"

**Comment by matejvasek** [comment]
@EzxD Could you please try adding some input pram for the helloWorld function? I have suspicion there is an issue when function takes no input.

**Comment by matejvasek** [comment]
I think that this is caused by this code:
https://github.com/quarkusio/quarkus/commit/4e2502bee17e21b8870592abedd4bcad95301426#diff-b0bcdc4c5807481b0e5fc7652e0ea523623924d6e2acfc0f555deb1a001082d3R66-R70

**Comment by steve-hb** [comment]
>I think that this is caused by this code:
>[4e2502b#diff-b0bcdc4c5807481b0e5fc7652e0ea523623924d6e2acfc0f555deb1a001082d3R66-R70]
>(https://github.com/quarkusio/quarkus/commit/4e2502bee17e21b8870592abedd4bcad95301426#diff-b0bcdc4c5807481b0e5fc7652e0ea523623924d6e2acfc0f555deb1a001082d3R66-R70)

Doesn't this only apply for JVM based artifacts?

**Comment by EzxD** [comment]
Even using the native image with the createUser method the function is timing out

**Comment by EzxD** [comment]
I am even getting a timeout using following application.properties ```properties
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.funqy.export=createUser
```
https://i.imgur.com/3qORuUv.png

**Comment by steve-hb** [comment]
We'll try to replace the H2 and use an in-memory list

**Comment by steve-hb** [comment]
Ok, we tried the "UserCreate" function of our example and it worked. Conclusion would be, that it's really a problem with function not having parameters at all.

**Comment by matejvasek** [comment]
I'll submit PR then.
