### ISSUE TITLE
Use JSON as the default media type when returning objects in RESTEasy Reactive

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#13594]
**Description**
Currently we default to `text/plain` for String but we don't default to JSON for objects. 
We should make this simplification (it has already been done for the quarkus-resteasy) extension

**Comment by geoand** [comment]
cc @FroMage @stuartwdouglas

**Comment by FroMage** [comment]
One of the strategies that would be possible is to add a `@DefaultConsumes/Produces(MediaType)` that we can place on `MessageBodyReader/Writer`:

```java
@DefaultConsumes(MediaType.TEXT_PLAIN)
// explicit type required because we declare writing for Object
@DefaultProduces(value = MediaType.TEXT_PLAIN, forTypes = String.class)
public class StringMessageBodyHandler extends PrimitiveBodyHandler
        implements MessageBodyReader<String>, MessageBodyWriter<Object> {
```

And then we can do similar for all types, including JSON and (eventually) XML.

At build time we collect all those, and we can infer that if the return type is `String` and there's no `@Produces` we make it default to `text/plain`. For any other type, the `Object` mapping of JSON would match and we'd end up with `application/json` and we don't have to special-case anything like `File` which would have its own default mapping.

**Comment by stuartwdouglas** [comment]
This appears to be out of date
