### ISSUE TITLE
Implicit JSON Content-type impacts swagger-ui POST endpoints

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#13615]
**Describe the bug**
Since 1.10.2 the default content-type is JSON, so we can remove `@produces` and `@consumes` but I noticed that on `swagger-ui` for a POST method when doing `try it out` I can not fill in the body with JSON content (the input box is not visible) 

**Expected behavior**
I can put a JSON body with swagger-ui in POST endpoints with using `try it out` 

**To Reproduce**

1.  Create a new Quarkus 1.10.2 project (with Resteasy, Resteasy JSON-B, and OpenAPI extensions
2.  Add a POST endpoint without @produces and @consumes 
3.  Go to swagger-ui and try out the endpoint

**Screenshots**
<img width="1742" alt="Screenshot 2020-12-02 at 10 15 46" src="https://user-images.githubusercontent.com/335133/100852961-7ac6a480-3487-11eb-9bfe-fff8046cda7e.png">

**Environment (please complete the following information):**
 - Quarkus version : 1.10.2

**Additional context**
Maybe it's related to swagger-ui and there is nothing you can do about it

**Comment by phillip-kruger** [comment]
Hi @sebastienblanc - Thanks for the issue. I'll have a look at it a.s.a.p.

**Comment by phillip-kruger** [comment]
This is now fixed in #13715
