### ISSUE TITLE
OpenAPI branding does not seem to work

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#13627]
**Describe the bug**
Following recent blog post about branding support in swagger u I tried to use custom styles and log but neither of these seem to work. Tried both dev mode and runner jar

This looks that in production profile (when building runner jar) it cannot find the file (logo.png) as it tries to search it as regular path while the root points to jar file

`/Development/git-repos/quarkus-apps/custom-logo/target/custom-logo-0.0.1-SNAPSHOT.jar/META-INF/branding/logo.png`

so this cannot be found
it is from here https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java#L209

in dev mode it does not seem to go over the overrides at all due to this condition 
https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java#L66

**Expected behavior**
custom logo and styles are not applied

**Actual behavior**
custom logo and styles are applied

**To Reproduce**

just follow https://quarkus.io/blog/stylish-api/#logo

**Screenshots**
here you can see the built runner jar content (META-INF folder)
![image](https://user-images.githubusercontent.com/904474/100879595-e884c780-34ab-11eb-9ead-b6170cc9ea4f.png)

as you can see the index.html still points to log.png instead of branding/logo.png which I would expect with this setup

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 19.6.0
 - Output of `java -version`: Java version: 11.0.2
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by phillip-kruger** [comment]
Hi @mswiderski.

Do you have a reproducer ? This is working fine for me. Any small project will do.
Thanks.

Also have a look at https://github.com/phillip-kruger/openapi-example, see if that work for you and let me know.

**Comment by mswiderski** [comment]
@phillip-kruger many thanks for the example, that helped to solve the issue. It turned out it was my configuration of Quarkus-maven-plugin that was only executing build phase and apparently that cause the issue.

P.S.
Maybe worth adding this link (example) to the blog post, really very useful as reference.

Closing as it's not an issue (I assume the quarkus-maven-plugin config was already in migration guide so I just didn't apply in time :))

**Comment by phillip-kruger** [comment]
Great ! I'll update the blog post.

**Comment by neal-shah** [comment]
Hi @phillip-kruger ,

Should this work when running `./gradlew quarkusDev`?

I've placed the **logo.png** and **style.css** under **src/main/resources/META-INF/branding** - I then run `./gradlew quarkusDev` but it seems like the logo does not change.

Am I missing something here?

Thank you!

**Comment by phillip-kruger** [comment]
Hi @neal-shah . 
What version of Quarkus are you running ?
What OS are you using ?
Did you make sure it's not your browser cache ? (so ctrl-F5)
Can you share a small reproducer.

Thanks :)

**Comment by neal-shah** [comment]
Hey @phillip-kruger,

Thanks for the quick reply!

Here's my repro repo -> https://github.com/neal-shah/code-with-quarkus

Quarkus version is 1.11.3.Final.

I'm using macOS Catalina 10.15.7 - i've cleared all browser caches and using incognito on Chrome.

Many thanks! 🙂

**Comment by phillip-kruger** [comment]
Hi @neal-shah 
I cloned your repo and started it in dev mode and the branding seems to work fine:

![image](https://user-images.githubusercontent.com/6836179/108702908-8ff52180-7512-11eb-9250-85770dc389e9.png)

Can you check if there is a quarkus folder in your temp folder ? And try and delete it and try again.

**Comment by neal-shah** [comment]
Ok so as much as I thought I had cleared the browser cache - it turns out I cleared it again and rebooted my laptop... and it seemed to work 🤦🏽‍♂️

So sorry for the time wasted, please accept my apologies! 🙏🏽

**Comment by phillip-kruger** [comment]
Hi @neal-shah . No apologies needed :) I am glad it is working for you. Also note that the "hot-reload" should also work now.

Cheers.
