### ISSUE TITLE
Listening on: http://localhost:8080 by default when a mutable jar is deployed to OpenShift

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#13638]
**Describe the bug**
(Describe the problem clearly and concisely.)
When a mutable jar is deployed to OpenShift via a binary build, localhost:8080 is listening by default than 0.0.0.0:8080 so the endpoint(i.e. REST API) can't be accessed externally via a router.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Listening on: http://0.0.0.0:8080

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Listening on: http://localhost:8080

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Add the below package type(quarkus.package.type=mutable-jar)
2. oc new-build registry.access.redhat.com/ubi8/openjdk-11:1.3 --binary --name=quarkus-remote -l app=quarkus-remote
3. rm -rf target/binary && mkdir -p target/binary && cp -r target/remote-dev-demo-1.0.0-SNAPSHOT-runner.jar target/lib target/binary
4. oc start-build quarkus-remote --from-dir=target/binary
5. oc new-app quarkus-remote -e QUARKUS_LAUNCH_DEVMODE=true
6. oc expose service quarkus-remote
7. See the pod logs then access the route URL

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.package.type=mutable-jar
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/14066977/100907262-16f8a780-3498-11eb-8055-e2abe79d749f.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Daniels-MacBook-Pro 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): apache-maven-3.6.3

OpenShift 4.6.3

oc version
Client Version: openshift-clients-4.6.0-202006250705.p0-162-g074039a0a
Server Version: 4.6.3
Kubernetes Version: v1.19.0+9f84db3

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@stuartwdouglas I suppose it's due to the changes we made to the host.

It's not the first time that I think remote dev should be its own mode. Dunno how much work it would be though.

**Comment by geoand** [comment]
> @stuartwdouglas I suppose it's due to the changes we made to the host.
> 

Which change is that?

**Comment by gsmet** [comment]
@geoand https://github.com/quarkusio/quarkus/pull/13223
