### ISSUE TITLE
Add security support for gRPC

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13656]
**Description**
At the moment, securing gRPC servers must be implemented manually. It would be good to support the same security annotations as in HTTP services, for example:

```
@Singleton
public class HelloService extends GreeterGrpc.GreeterImplBase {

    @Override
    @Authenticated
    @RolesAllowed("my-role")
    public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
    }
}
```

It would not make sense to use the oidc Quarkus extension, but maybe the jwt extension does. 

**Implementation ideas**
See an example of implementing security using JWT in this post: https://sultanov.dev/blog/securing-java-grpc-services-with-jwt-based-authentication/

**Comment by sberyozkin** [comment]
@Sgitario Hi, I guess it falls into the same category as web sockets, the metatada keys if any containing the tokens are not standardized in either case.
This should be done in the grpc interceptor I guess which would populate a `SecuryIdentity` it it can be demoed in the quicktart...

**Comment by indalaterre** [comment]
I tried with this approach but let me know if could be ok
UsePrincipalService is a `@RequestScope` either the internal or the principal created by AuthenticationMechanism.

`return serverCallHandler
        .startCall(new ForwardingServerCall.SimpleForwardingServerCall<ReqT, RespT>(serverCall) {
          @Override
          public boolean isReady() {
            Status status;
            String token = metadata.get(GRPC_AUTHENTICATION_METADATA);
            if (StringUtils.isEmpty(token)) {
              status = Status.UNAUTHENTICATED.withDescription("Authorization token is missing");
            } else {
              try {
                Claims claims = jwtUtils.extractAllClaims(token);

                UserPrincipal principal =
                    JwtIdentityProvider.buildPrincipalFromClaims(claims, token, true);

                UserPrincipalService userPrincipalService =
                    CDI.current().select(UserPrincipalService.class).get();
                userPrincipalService.setInternalPrincipal(principal);

                return super.isReady();

              } catch (Exception ex) {
                log.error("Error while parsing the authentication token", ex);
                status = Status.UNAUTHENTICATED.withDescription(ex.getMessage()).withCause(ex);
              }
            }

            close(status, metadata);
            return false;
          }
        }, metadata);`

This code fails because of this exception `java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride`

**Comment by michalszynkiewicz** [comment]
@indalaterre could you create a small reproducer that throws this exception?

**Comment by cescoffier** [comment]
Closing this issue in favor of #24755.
