### ISSUE TITLE
RESTEasy Reactive: change default name mapping strategy for `@RestHeader`

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#13665]
ATM if you define your param as `@RestHeader String contentType` it will map to the `contentType` header, but it should map to `Content-Type`, so we have to adjust the name mapping rules to make it work for all HTTP headers by default.

**Comment by FroMage** [comment]
This turns out to generate the `content-Type` header for `@RestHeader String contentType` because it doesn't change the casing: it just hyphenates. Given that headers are case-insensitive, it's not critical, but we should still fix it. Also, this was added to the server, but not the client, making them incompatible when using `@RestHeader` with no argument.

**Comment by geoand** [comment]
Are you sure the client doesn't work properly?

Because I am seeing that it does send the proper header name.

**Comment by FroMage** [comment]
Without your fix, I saw the client generate `content-Type` and not `Content-Type`. But now I need to redo part of #28782 with your new method, so let's merge this.

**Comment by geoand** [comment]
👌🏼
