### ISSUE TITLE
OutgoingKafkaRecordMetadata not workink with SmallRye

### ISSUE THREAD

**Issue by krisraich** [quarkusio/quarkus#13679]
**Describe the bug**

OutgoingKafkaRecordMetadata as described here https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/kafka/kafka.html#_outbound_metadata does not work with an Emitter.

eg: 

```
    @Inject
    @Channel("kafka-producer")
    Emitter<Message<String>> emitter;

    public void send(String val){
        Message<String> message = Message.of(val);
        
        OutgoingKafkaRecordMetadata<String> metadata = OutgoingKafkaRecordMetadata.<String>builder()
                .withKey("my-key")
                .withTopic("my-custom-topic")
                .build();
        message.addMetadata(metadata);

        emitter.send(message);
    }
```
When executed, it throws an Error, because the Message<> cant be casted to a String. If fixed, with an Custom Serializer, the topic set in the metadata is ignored.

**Expected behavior**

Retrieve the value from the message and publish it to the topic stated in the metadata 

POM:
```
  <properties>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <maven.compiler.target>11</maven.compiler.target>
    <quarkus.platform.version>1.10.2.Final</quarkus.platform.version>
    <maven.compiler.source>11</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <quarkus-plugin.version>1.10.2.Final</quarkus-plugin.version>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
  </properties>
...
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging</artifactId>
    </dependency>
```

**Comment by kenfinnigan** [comment]
Whether using a payload or `Message`, the `Emitter` only refers to the payload type, so I think it's a problem of wrapping.

If you change your emitter to be `Emitter<String>` even when calling `emitter.send(message)` it should work

**Comment by krisraich** [comment]
Yes that would work, but than i can't pass the topic or message key to the kafka-producer.

**Comment by kenfinnigan** [comment]
@krisraich All you need to do in your above code sample is change it to use `Emitter<String>`.

The content of the `send()` method will still work. `Emitter` has overloaded send methods for the payload variant, in this case, a String, or for a `Message`.

**Comment by krisraich** [comment]
Your right, didn't see that. Sorry for the inconvenience.

**Comment by kenfinnigan** [comment]
No problem, glad it's working
