### ISSUE TITLE
Support OIDC `id_token` flow

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#13676]
**Description**
In some cases the users would like to get hold of the ID token in their SPA before making it available to Quarkus.
**Implementation ideas**
Introduce `IdTokenAuthenticationMechanism` which will handle the redirect from IDP as the form post response:
https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

The difference between the SPA using for example `keycloak.js` is that here the browser is still posting an ID token to the endpoint as opposed to using an access token returned from the code flow as a bearer token

This would imply an ID token only token state strategy as well.

CC @pedroigor @stianst

**Comment by AlbozDroid** [comment]
Nice one.

One thing though, the SPA (front-end) doesn't really get hold of the `id_token`, the IdP uses a `form_post` to auto-post the `id-token` to Quarkus. 
The only difference from Quarkus' perspective is that Quarkus is getting an `Id-token` directly from the IdP instead of getting a `code`. 
This means the last step which exchanges the `code` for the `id-token & access-token` can be skipped.

Here are some diagrams depicting it:
https://darutk.medium.com/diagrams-of-all-the-openid-connect-flows-6968e3990660

**Comment by sberyozkin** [comment]
@AlbozDroid I don't we'd do it just for the sake of the optimization, the code flow would be preferred. If you don't need this ID token in the SPA then I'm not sure there is much point in this extension

**Comment by sberyozkin** [comment]
@AlbozDroid 

> The only difference from Quarkus' perspective is that Quarkus is getting an id_token directly from the IdP instead of getting a code.

This is not correct - Quarkus would be getting it from the user browser.

**Comment by AlbozDroid** [comment]
I'm not saying to do it just to save the last step. 

It's to support the OpenId Connect Protocol, this is the only `flow/response_type` added specifically by the OIDC specs to the existing OAuth2 flows.

The back-end application then can return it to the SPA/Front-end/UI. This would be App-specific behaviour.

**Comment by AlbozDroid** [comment]
> @AlbozDroid
> 
> > The only difference from Quarkus' perspective is that Quarkus is getting an id_token directly from the IdP instead of getting a code.
> 
> This is not correct - Quarkus would be getting it from the user browser.

Yes, and the `code` comes from the user's browser too. Instead of the `code`, you get the `id_token`. 
What's not correct?

**Comment by sberyozkin** [comment]
@AlbozDroid 
Sure what you say is technically correct; but with the code flow we are having a confidential client, the Quarkus endpoint, authenticating with its secret, requesting the id token with the code. if the front channel is compromized then the attacker won't be able to use a a one time only code without a secret - with the ID token in the frontchannel a not carefully protected ID token (not encrypted, signed only which is a mainstream, cam leak a lot of info about the user).
Anyway, it is well accepted that the code flow security is better.
And with it we can manage the session at the quarkus level by auto-refreshing it. If we get the ID token only then the only option is for the user to always reauthenticate when the session expires

**Comment by AlbozDroid** [comment]
Yes, the `Authorization code flow` is more secure, that's why it's the recommended `OIDC flow` for apps that have a back-end. 
Thanks for taking this into consideration, the `id_token` with `form_post` is not that bad security-wise :)

**Comment by AlbozDroid** [comment]
@sberyozkin  One more thing: Can we have a property named `responseType` to set the flow, with possible values `code` or `id_token` instead of the `application-type` property?

This is sort of a standard way for many frameworks, and it's the same language used in the specs.

**Comment by sberyozkin** [comment]
@AlbozDroid I'm sorry but I'm not sure what you mean; right now I'm considering to close this issue as there is no practical justification to support a less secure `id_token` flow

**Comment by sberyozkin** [comment]
I've looked at this issue again and indeed if the `id_token` flow is required then it is an SPA-level decision - and if this SPA then posts this token as a bearer token to Quarkus then the existing `service` app will just verify it as always... Let me close it for now
