### ISSUE TITLE
Returning Optional for single result find Panache operations

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#1368]
Given a custom Entity extending PanacheEntity, for operations returning a single result, it would nice propose an additional method returning `java.util.Optional`.
The aim here is clearly to build null-safe method chains.
A naive approach would be to add a method like.
` public static Optional<T extends PanacheEntityBase>> findById(Object id)`.

The issue is that without an explicit affectation, the wrapped object is masked by the `PanacheEntityBase` object and we can't get access to the custom Entity field (and we loose all the magic).

```
//Given
public class Person extends PanacheEntity {
  public String name;
}
...

// I can do
Person person = Person.findById("");
person.name;
Optional<Person> opt = Optional.offNullable(Person.findById(""));
opt.map(it -> it.name);

// But I can't do
Person.findById("").name
Optional.offNullable(Person.findById("")).map(it -> it.name);
```

An option I can see would be to do something like
```
public class Person extends PanacheEntity<Person> { }
...
public class PanacheEntityBase<T> {
 public static <T> T findById(Object id) {}
}
```
I agree it's looks ugly but it capture the type at compilation.

Last but not least, the naming since I only want to change the return object the method (don't change the method  signature) it must have a specific name ( `findOptionalById`, `firstOptionalResult`)?

An acceptable answer would be also "It's not Panache issue, the dev is responsible of the null management".

**Comment by FroMage** [comment]
> An option I can see would be to do something like
> ```
> public class Person extends PanacheEntity<Person> { }
> ...
> public class PanacheEntityBase<T> {
>  public static <T> T findById(Object id) {}
> }
> ```

This is actually not possible (we tried) because static methods don't capture enclosing type parameters.

But we could propose a return type of `Optional`

**Comment by danielpetisme** [comment]
> But we could propose a return type of Optional
that means a double declaration?
```
public static <T extends PanacheEntityBase> T findById(Object id)
public static Optional<T extends PanacheEntityBase> T findOptionalById(Object id)
```
IMHO not very "sexy" but very simple to implement. So far I don't other alternatives.

**Comment by FroMage** [comment]
Yeah, me neither. WDYT @gsmet @Sanne ?

**Comment by emmanuelbernard** [comment]
Looking at @loicmathieu implementation proposal #4809,
I think I prefer an optional root vs maybe, it's more explicit. In decreasing priority:

1. `optionalFindById(Object id)` // short and pre filter auto completion with optional in case we want more methods like that
2. `optionallyFindById` //note the double `ll`
3. `findByIdOptional`

@FroMage @loicmathieu le'ts just discuss to converge on the name and move on.

**Comment by FroMage** [comment]
`optionalFindById` is good if you're looking for methods returning `optional`, but probably fails the auto-completion goal of making the method discoverable for people trying `Entity.find[COMPLETE]`, where `findByIdOptional` works. 

I guess it has my preference for that reason, despite it being longer.

Unless we have more methods that can return `Optional` which we could group by starting with `optional` but it doesn't look like it.

An alternative line of thought could be a new term to express optionality: `tryById()` or `findTryId()`, but the has the same drawbacks as `optionalFindById` I just mentioned, and the second is shorter but less clear than `findByIdOptional`.

**Comment by loicmathieu** [comment]
@FroMage `try` is connoted with the idea that it will return a value or an error, like in Vavr Try: https://www.baeldung.com/vavr-try

I think the `optionally` variants are semantically better (they sound better to me but I'm not an english expert) but I don't care :). And the Spring users can write queries like `findOptionalByName(name)` so it is already a popular choice.

One thing to note is that we can also provides optional method inside PanacheQuery for `findFirst` and `findOne`

**Comment by FroMage** [comment]
Yeah, `try` was not a very good proposal, as I explained why. I'm not pushing for it, just listing a shot-down solution.

**Comment by danielpetisme** [comment]
Silly but why Optional couldn't be the norm rather than having the 2 semantics? Would be consistent with the `Stream` finders would only return an optional

**Comment by loicmathieu** [comment]
> Silly question but why `Optional` couldn't be the norm rather than having the 2 semantics?
 
@danielpetisme  this is not a silly question :) this has been proposed (this is also my favourite choice) and dismiss as we don't want to break compatibility.

So, as both @emmanuelbernard and @FroMage like `findByIdOptional` I propose to go with this name. 

Should we also for for `PanacheQuery.findFirstOptional` and `PanacheQuery.findOneOptional` or should I open a new issue to discuss them ?

**Comment by emmanuelbernard** [comment]
yes let's be consitent
