### ISSUE TITLE
Invalid JSON returned from the default QuarkusErrorHandler (Vert.x)

### ISSUE THREAD

**Issue by pismy** [quarkusio/quarkus#13681]
**Describe the bug**
Using vertx-http and quarkus-resteasy, if an exception is thrown in a JAX-RS endpoint and no ExceptionMapper catches it gets forwarded to [QuarkusErrorHandler](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/QuarkusErrorHandler.java).

In case of `application/json` Accept header, the stack does not get properly escaped there.
More specifically, produces a JSON with a string including unencoded tab characters.

**Environment:**
 - Quarkus `1.9.2.Final`

**Additional info**
The same exact issue existed in Undertow QuarkusErrorServlet implementation
see: https://github.com/quarkusio/quarkus/issues/9463

The fix to apply here is very similar to [undertow fix](https://github.com/quarkusio/quarkus/pull/9484/files)

**Comment by gsmet** [comment]
@pismy would you like to prepare a PR?

**Comment by pismy** [comment]
Sure
