### ISSUE TITLE
Micrometer Stackdriver registry support including support for native mode

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#13684]
quarkiverse-micrometer-stackdriver-registry (?)

**Describe the extension**
This extension will pull together required/related extensions to make support for the micrometer stackdriver registry work in native mode.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
This extension will borrow/reuse `quarkus.micrometer.export.stackdriver.*` configuration (as it is a loose bag)

**Additional context**
There will have to be an additional test in the proper quarkus extension to see if this extension is around to squash warnings and/or allow registration in native mode (TBD)

**Comment by gsmet** [comment]
As discussed with @ebullient on Zulip, let's go with `quarkiverse-micrometer-registry-stackdriver` so that we can have others with the same naming convention.

/cc @gastaldi

**Comment by gastaldi** [comment]
Repository https://github.com/quarkiverse/quarkiverse-micrometer-registry-stackdriver created. I'm assuming @ebullient will lead this?

**Comment by gastaldi** [comment]
Invitation sent! @ebullient have fun and let me know if you need any help 😉
