### ISSUE TITLE
OASFilter is called twice

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#13683]
**Describe the bug**
I have a custom OASFilter. It gets executed twice, which can be easily seen in the ui.

**Expected behavior**
Each filter should only be executed once for a openapi document.

**Actual behavior**
Filter is executed twice.

**To Reproduce**

1. Download the reproducer: 
[duplicate-oas-filter.zip](https://github.com/quarkusio/quarkus/files/5638444/duplicate-oas-filter.zip)

2. mvn quarkus:dev
3. go to localhost:8080/swagger-ui
4. "First Filter!" is output twice on the "/hello-resteasy" operation.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux martin 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
 - Quarkus version or git rev: 1.10.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/martin/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /home/martin/.sdkman/candidates/java/11.0.7-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-54-generic", arch: "amd64", family: "unix"

**Comment by phillip-kruger** [comment]
Thanks @Postremus - I am looking at this now.

**Comment by phillip-kruger** [comment]
What happend here is that we moved the filter to runtime, to allow people to do dynamic filtering based on runtime config, but never removed the compile time filter, so the filter now gets called twice. #13715 fixes that.
