### ISSUE TITLE
Flyway + OpenTracing configuration

### ISSUE THREAD

**Issue by ekarlso** [quarkusio/quarkus#13690]
**Describe the bug**
Is there a smart way to combine in-app flyway migrations when using the OpenTracing instrumentation?

We have a issue with the jdbc:tracing:postgres://.... not being supported in the default datasource url by flyway when the application comes up to migrate the datasource. The examples for both just show them alone and not in combination with each other.

**Expected behavior**
You'd be able to combing both 

**Actual behavior**
Caused by: java.sql.SQLException: Driver does not support the provided URL: jdbc:tracing:postgresql://hostname:5432/mydb?ssl=true&sslmode=required

**To Reproduce**
Setup a project with opentracing jdbc, opentracing and flyway and use in-app migrations with the above address type and it will fail.

**Configuration**
```properties
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
Quarkus 1.6.x
Java 11
Built with Maven

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@ekarlso could you prepare a reproducer (i.e. a small Maven project reproducing the issue)? Thanks!

**Comment by loicmathieu** [comment]
@ekarlso I'm surprised by this issue as I do have an application using both Flyway and the Opentracing contrib JDBC driver and it works.
Can you test with a recent version of Quarkus ? If the issue still occurs can you provide a reproducer ?

**Comment by radcortez** [comment]
Closing due to the lack of activity.
