### ISSUE TITLE
Random Gradle build error when building Quarkus

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#13702]
I've seen this happen several times now and it's very odd. When I reboot my machine, the Quarkus Gradle plugin fails to build, complaining with the following:

```
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find jboss-annotations-api_1.2_spec-1.0.2.Final.jar (org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:1.0.2.Final).
Searched in the following locations:
    file:/home/g/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.2.Final/jboss-annotations-api_1.2_spec-1.0.2.Final.jar
```

See [longer](https://gist.github.com/galderz/47c1d087263ba45847cb1263228e70d7).

When I look at the `~/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.2.Final` directory, I see only this:

```
-rw-r--r--. 1 g g 4.9K Nov 26 08:38 jboss-annotations-api_1.2_spec-1.0.2.Final.pom
-rw-r--r--. 1 g g   40 Nov 26 08:38 jboss-annotations-api_1.2_spec-1.0.2.Final.pom.sha1
-rw-r--r--. 1 g g  196 Nov 26 08:38 _remote.repositories
``` 

I then nuke the `~/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.2.Final` directory and the build completes fine, but funnily enough that directory is not there any more. All I see is:

```
❯ l ~/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec
total 0
drwxr-xr-x. 3 g g  25 Dec  4 14:21 .
drwxr-xr-x. 4 g g  82 Nov 26 08:38 ..
drwxr-xr-x. 2 g g 260 Nov 26 08:38 1.0.0.Final
```

Has anyone seen anything similar? I've not yet figured out what produces that odd, partially constructed, `1.0.2.Final` folder, and why it bothers Gradle. And why is not present after a successful build?

**Comment by glefloch** [comment]
I used to see this error when working on the Release test build job. 
A sample gradle project used in `integration-test`. I fixed the issue by removing that dependency..

Also, I had nothing in the `_remote.repositories` file, I'm not a maven expert and I don't know if this is a problem..

**Comment by huw0** [comment]
Possibly this is occurring because something else in the Quarkus build needs this pom, but never downloads the jar which can then result in this race condition since mavenLocal occurs before mavenCentral.

See: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local

Potentially just swapping the ordering of mavenCentral and mavenLocal may be enough to resolve this issue assuming that local dev always take place using SNAPSHOTS that aren't present in mavenCentral or any other repositories.

**Comment by galderz** [comment]
This is still happening, any Gradle experts care look at this?

**Comment by glefloch** [comment]
I add this error again on CI, a workaround I used was to invert the repository declaration.

**Comment by glefloch** [comment]
@galderz it seems that maven only resolved the pom and not the artifact. As soon as gradle found a pom, it expects a complete entry which is not the case.

**Comment by galderz** [comment]
Bump. Still happening...

**Comment by galderz** [comment]
@glefloch Can you send a PR for your workaround? Or is it something that needs to be tweaked in the local env?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
