### ISSUE TITLE
Apply OASFilter at runtime to modify security schemes in openapi 

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#13714]
**Description**
Sometimes, some values in the openapi files must be adjusted at runtime to have a correctly working api description. For example, the security scheme changes for each deployment.

Therefore it would be great if the OASFilters can be applied at runtime (when first hitting the /openapi endpoint or at startup)

Example code for changing the security scheme: 
```
public class SecuritySchemeFilter implements OASFilter {
    @Override
    public SecurityScheme filterSecurityScheme(final SecurityScheme securityScheme) {
        String url = ConfigProvider.getConfig().getValue("quarkus.oidc.auth-server-url", String.class);
        var implicitFlow = securityScheme.getFlows().getImplicit();

        implicitFlow.setAuthorizationUrl(url + "/protocol/openid-connect/auth");
        implicitFlow.setRefreshUrl(url + "/protocol/openid-connect/token");
        implicitFlow.setTokenUrl(url + "/protocol/openid-connect/token");

        return securityScheme;
    }
}
```

And in the application.properties: 

```
mp.openapi.filter=com.qumea.qumeacare.config.SecuritySchemeFilter
```

**Comment by phillip-kruger** [comment]
Hi @joggeli34 - What version of Quarkus are you using ?

**Comment by joggeli34** [comment]
Hi @phillip-kruger  I'm currently using 1.10.2

**Comment by phillip-kruger** [comment]
Ok, I would have thought that it works then. We moved the filter to runtime a while back. (We left it in complile time too, and that caused https://github.com/quarkusio/quarkus/issues/13683 - but I am fixing that as we speak).

can you create a small project that recreate the issue ? that will help to get a fix in quicker. 

Thanks :)

**Comment by joggeli34** [comment]
I checked again, and I mixed something up with mp.openapi.model.reader and the filter as I was testing both. Then I was confused by the compile time call too. 

So it works as it should. I apologize for the circumstances.
