### ISSUE TITLE
Permit Launching Directly in IDE

### ISSUE THREAD

**Issue by dansiviter** [quarkusio/quarkus#1372]
As it stands, the maven plugin generates a `io.quarkus.runner.GeneratedMain` which `io.quarkus.runtime.Quarkus` calls.  Unfortunately, this means the `main(...)` class cannot be called directly within the IDE so does not get any of the benefit of debugging and profiling.

The only way to debug is to run via Maven and remote attach which is onerous.

Moved from quarkusio/quarkus-quickstarts#84.

**Comment by arnostv** [comment]
I guess this issue is duplicate of #2143

**Comment by dansiviter** [comment]
Or is #2143 is a duplicate of this as this appeared first?! 😄

Happy to close this as it's covered in the aforementioned.
