### ISSUE TITLE
Quarkus AWS Lambda - ConfigProperty annotation is not working

### ISSUE THREAD

**Issue by tpenakov** [quarkusio/quarkus#13723]
**Describe the bug**

* Create a Quarkus project from here: https://code.quarkus.io/
* Select only AWS Lambda and Jackson extension.
* Add to the `application.properties`
```
prop.name=john
```
* Add the following to the GreetingsLammbda.java
```
    @ConfigProperty(name = "prop.name")
    String name;
```
* Try to build the project with `mvn clean package`

**Expected behavior**
Project is compiled successfully and the tests are executed.

**Actual behavior**
Build failed:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.386 s <<< FAILURE! - in org.acme.lambda.LambdaHandlerTest
[ERROR] testSimpleLambdaSuccess  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: prop.name

```

**To Reproduce**
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5648622/code-with-quarkus.zip)

**Configuration**
```properties
# Add your application.properties here, if applicable.
prop.name=john
```

**Screenshots**

**Environment (please complete the following information):**
Java11
**Additional context**
Attached is the sample project in order to reproduce the problem: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5648622/code-with-quarkus.zip)

**Comment by patriot1burke** [comment]
You need to specify prop.name within src/test/resources/application.properties

FYI:  I spent 20 minutes making the same error trying to reproduce this!! :)

**Comment by tpenakov** [comment]
Hi @patriot1burke ,
You are right - it is about that the `application.properties` file is not 'mixed' when is present more than once. However I still think that duplication of the content is error prone and may lead to unexpected errors as in my case.

In order to prevent this - may I suggest to remove the `src/test/resources/application.properties` entirely and to move the line:
```
quarkus.lambda.enable-polling-jvm-mode=true
```
into the `src/main/resources/application.properties`, however it should be made to work for tests only and that's why it should become:
```
%test.quarkus.lambda.enable-polling-jvm-mode=true
```
