### ISSUE TITLE
Quarkus Micrometer not publishing Agroal metrics

### ISSUE THREAD

**Issue by bollerdominik** [quarkusio/quarkus#13730]
**Describe the bug**
Using Quarkus Micrometer all the Agroal metrics such as `agroal_acquire_count_total` are always 0. Using the same setup but with `quarkus-smallrye-metrics` instead of `quarkus-micrometer` the metrics are published correctly.

**To Reproduce**

pom.xml

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>

application.properties

```
# Database
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:TEST/TEST@//localhost:1521/saa
quarkus.hibernate-orm.dialect=org.hibernate.dialect.Oracle12cDialect

# Metrics
metrics.micrometer.enabled=true
quarkus.datasource.jdbc.enable-metrics=true
quarkus.datasource.metrics.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
```

Tested on Quarkus version 1.9.1.Final and 1.10.2.Final.

The resulting metrics look like this after performing some database transactions:

```
# HELP agroal_blocking_time_average_milliseconds Average time an application waited to acquire a connection.
# TYPE agroal_blocking_time_average_milliseconds gauge
agroal_blocking_time_average_milliseconds{datasource="default",} 0.0
# HELP system_cpu_usage The "recent cpu usage" for the whole system
# TYPE system_cpu_usage gauge
system_cpu_usage 0.08303987742937104
# HELP agroal_creation_time_max_milliseconds Maximum time for a connection to be created.
# TYPE agroal_creation_time_max_milliseconds gauge
agroal_creation_time_max_milliseconds{datasource="default",} 0.0
# HELP agroal_max_used_count Maximum number of connections active simultaneously.
# TYPE agroal_max_used_count gauge
agroal_max_used_count{datasource="default",} -9.223372036854776E18
# HELP agroal_creation_time_total_milliseconds Total time waiting for connections to be created.
# TYPE agroal_creation_time_total_milliseconds gauge
agroal_creation_time_total_milliseconds{datasource="default",} 0.0
# HELP agroal_available_count Number of idle connections in the pool, available to be acquired.
# TYPE agroal_available_count gauge
agroal_available_count{datasource="default",} 0.0
# HELP agroal_acquire_count_total Number of times an acquire operation succeeded.
# TYPE agroal_acquire_count_total counter
agroal_acquire_count_total{datasource="default",} 0.0
```

Note that all the Agroal values are 0

**Comment by jmartisk** [comment]
I tried reproducing this, but actually got reasonable numbers. There must be something specific that I'm not aware of..
(just purely theoretically the Oracle database, I tried with PostgreSQL)
Would you be able to provide a full reproducer, or something? Preferably with an in-memory H2 database or something this simple :)

**Comment by bollerdominik** [comment]
I tried to reproduce it but failed. Then went back to the current project where the issue was first noticed but then I didn't see the issue there any longer.

I am not sure how this happened but I will close this issue. Sorry about that.

**Comment by mjiderhamn** [comment]
For anyone else stumbling across this issue in the future, a possible explanation can be found in #22556
