### ISSUE TITLE
Customized ObjectMapper Ignored

### ISSUE THREAD

**Issue by aramponi** [quarkusio/quarkus#13742]
**Describe the bug**
Customized jackson's ObjectMapper are not taken into account when using reactive routes & Multi/Uni

```
git clone github.com:aramponi/reactive-jackson.git

run tests

```

**Additional context**
the Mutiny calls ends in `io.vertx.core.json.jackson.JacksonCodec.toBuffer`which make use of a static reference to `ObjectMapper` of `io.vertx.core.json.Json` which is not the one I instantiated

**Comment by gsmet** [comment]
@geoand @cescoffier wondering if we should overwrite the `Json` static field with the customized `ObjectMapper`?

It's not the first time people complain about it.

**Comment by cescoffier** [comment]
I guess we should.

**Comment by geoand** [comment]
Yes, we've had people expect the customization to work in Vert.x as well.

Is there any expectations that Vert.x has however from the ObjectMapper that could break by a user customization?

**Comment by cescoffier** [comment]
So... (fun ahead).
This part has been reworked in Vert.x 4 - so everything I will say below this line will be wrong when we switch to Vert.x 4.

The JSON mappers provided by Vert.x are accessible from `Json.mapper` and `Json. prettyMapper`. These are deprecated but the official access (`DatabindCodec`) still relies on these. 

The mappers are configured with a _module_ containing the mapping logic for Vert.x objects:
https://github.com/eclipse-vertx/vert.x/blob/3.9/src/main/java/io/vertx/core/json/Json.java#L48-L66

If the user configures a mapper, we would still need to register that module. Without it, things would get pretty bad...

**Comment by geoand** [comment]
Thanks @cescoffier!

**Comment by geoand** [comment]
Looks innocent enough for us to configure - Famous last words :)

**Comment by geoand** [comment]
This will be addressed when we move to Vert.x 4 and is being tracked by [here](https://github.com/quarkusio/quarkus/issues/15031), so let's close this as a duplicate
