### ISSUE TITLE
Is there any Enhancement Proposals like Python,JCP, and Groovy lang?

### ISSUE THREAD

**Issue by netroby** [quarkusio/quarkus#13767]
### Description
Any Enhancement Proposals progress like them ?

Python PEPs
https://www.python.org/dev/peps/

### Analysis

The famous open source project has there good Enhancement Proposals.

That limit the change happen and revert , and make project stable  and growing well.

I have watching quarkus for a while. it growing very fast, changes made very soon and seems a bit lost control.

Codes was changed , then revert, and can't quickly catch up with them.

If there be a Enhancement Proposals progress, it may be a good control.

**Comment by geoand** [comment]
We don't have such a formal process, but any issue you open of the like should be marked with `kind/enhancement`
