### ISSUE TITLE
Log messages are barely visible in on white background

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1378]
Log messages are barely visible in macOS native terminal 

<img width="1046" alt="Screenshot 2019-03-10 at 14 20 02" src="https://user-images.githubusercontent.com/925259/54085572-ef66c080-433f-11e9-9f4b-cad827563404.png">

Workaround is to use alternative terminal - e.g. https://www.iterm2.com/

**Comment by cescoffier** [comment]
Like the web site, dark mode only :-)

**Comment by rsvoboda** [comment]
Lol, like dark mode (side?) of the Force :)

WildFly works nicely in both terminals. So there will be some tricks to make the output nice for light mode.

<img width="1304" alt="Screenshot 2019-03-10 at 15 27 58" src="https://user-images.githubusercontent.com/925259/54086411-6fddef00-4349-11e9-8938-35705e46f516.png">

**Comment by dmlloyd** [comment]
There will be light and dark mode options in an upcoming release.

**Comment by rhuss** [comment]
> Workaround is to use alternative terminal - e.g. [iterm2.com](https://www.iterm2.com/)

Iterm2 is not of much help here, as the log output uses absolute RGB value and not plain ANSI colors, which could be adapted and configured by the terminal adapter.

So having the mode switchable, or even better, make it configurable for each color individually would be awesome.

**Comment by dmlloyd** [comment]
You can disable colors via `-Dquarkus.log.console.color=false` or setting this property in your `application.properties`.

**Comment by gsmet** [comment]
@rsvoboda has this been fixed? I remember some work on it.

**Comment by rsvoboda** [comment]
Out of the box experience is still the same

You can tweak it with `quarkus.log.console.darken` which is not documented.


![Screenshot 2019-11-08 at 09 46 35](https://user-images.githubusercontent.com/925259/68462375-b2273b00-020c-11ea-9965-52d149dca253.png)

**Comment by gastaldi** [comment]
Using `quarkus.log.console.darken` resolves the problem. Closing this issue for now
