### ISSUE TITLE
RESTEasy Reactive: Introduce Websocket support

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#13794]
**Description**
Currently in Quarkus the way for a user to get server side websocket support, is to introduce Undertow. 

It would be nice to provide a similar API in RESTEasy Reactive so users don't have to add Undertow just to get websockets support.

**Comment by geoand** [comment]
I remember @ebullient also mentioning wanting this :)

**Comment by ebullient** [comment]
YES. ;) I can help test.

**Comment by ebullient** [comment]
ok. I have to resolve some meter registry stuff first -- if no one has picked this up before I get to it, I'll have a go. I am also willing to help whoever does get there first. ;)

**Comment by stuartwdouglas** [comment]
I will look into this, it should not be too big a deal, just a lot of dependency untangling. The core transport is pure Netty so this should all work fine, but there are some Undertow Core dependencies that need to be duplicated, and Servlet dependencies that need to be hidden behind a SPI.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/compare/master...stuartwdouglas:vertx-websockets?expand=1
https://github.com/quarkusio/quarkus-http/compare/master...stuartwdouglas:websockets-split1?expand=1

This is my initial work at Servlet free websockets, I should be able to get it cleaned up into a mergable state tomorrow. 

In some respects it is a breaking change, as you can no longer user Servlet filters to intercept websocket requests, but I don't think that matters.

**Comment by FroMage** [comment]
That looks great, but they don't appear to be related to RESTEasy Reactive, or did I miss something?

**Comment by stuartwdouglas** [comment]
This is what we need to support Jakarta Websockets without the Servlet dependency. I will add the RR bit tomorrow but it should be pretty simple, basically you will just be able to do:

@GET 
void websocket(javax.websocket.Session session) {

}

and go from there.

**Comment by stuartwdouglas** [comment]
Websockets no longer need Undertow
