### ISSUE TITLE
Hibernate NPE with Quarkus 1.10.3.Final

### ISSUE THREAD

**Issue by jw941** [quarkusio/quarkus#13791]
When we upgraded Quarkus from 1.9.2.Final to 1.10.3.Final, we had some NPE issue with Hibernate. When Hibernate tries to load entities with OneToMany collections that are initialized to a default value, for example List subEntities = new ArrayList(), it throws NPE when it's loaded.

A reproducer is at this repo:
https://github.com/jw941/hib-npe

Thanks.

**Comment by Sanne** [comment]
thanks @jw941 !

Could test yet, but smells like related to https://github.com/hibernate/hibernate-orm/pull/3674 , @beikov ?

**Comment by beikov** [comment]
I'll take a look

**Comment by beikov** [comment]
Yeah, that issue is fixed by https://github.com/hibernate/hibernate-orm/pull/3674

**Comment by gsmet** [comment]
@Sanne it looks pretty serious or it's just me?

**Comment by Sanne** [comment]
yes, and it's confirmed by three users already - sorry we rushed the previous release to re-converge a regression issue with Reactive.
I'll get a new release out soon.
