### ISSUE TITLE
When import the BOM with Gradle, Quarkus dependencies are not properly resolved 

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#1381]
When importing the Quarkus BOM via gradle like is shown in https://github.com/quarkusio/quarkusio.github.io/pull/135 (implementation(platform("io.quarkus:quarkus-bom:0.11.0"))) then `ResolvedGradleArtifactDeps#extractDependencies` does properly extract the app dependencies unless they have their version set (which shouldn't be the case when using the BOM).

This is because in `ResolvedGradleArtifactDeps#traverseDependencies` the dependencies are not of type `ResolvedDependencyResult` - but something like UnresolvedDependencyResult.

**Comment by gsmet** [comment]
@stalep could you take a look at this one? Thanks.

**Comment by stalep** [comment]
@geoand what is the usecase of importing the bom?
I don't know why the dependencies are not of type `ResolvedDependencyResult` tbh.

**Comment by Sanne** [comment]
FYI as a Gradle user I'm not sure I'd use a BOM at all. There are better solutions.

**Comment by stalep** [comment]
I thought so as well, but then I found: https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import

**Comment by geoand** [comment]
I just opened the issue because someone mentioned it. I am not a gradle user myself so I don't how often people do this :)

**Comment by Sanne** [comment]
yes Gradle _can_ support it, and +1 to give this option to users.

I just meant we should look at some other options too, but clearly that's material for a different issue.
