### ISSUE TITLE
NativeImageTest with container-image extensions

### ISSUE THREAD

**Issue by rquinio** [quarkusio/quarkus#13818]
**Description**

When using:
* `quarkus.native.container-build=true` (GraalVM/Mandrel native-image used from a docker image during NativeImageBuildStep)
* and `quarkus.container-image.build=true` (the application native executable is dockerized by JibProcessor)

it would be great if `@NativeImageTest` would be able to actually use that docker image to start the application, rather than trying to start the native executable inside/target from NativeImageBuildStep, because it may fail to start if incompatible with the host OS (i.e. building a Linux executable on a Windows laptop).

```xml
<properties>
  <quarkus.package.type>native</quarkus.package.type>
  <quarkus.native.container-build>true</quarkus.native.container-build>
  <quarkus.native.container-runtime>docker</quarkus.native.container-runtime>
  <quarkus.container-image.build>true</quarkus.container-image.build>
  <quarkus.container-image.push>false</quarkus.container-image.push>
</properties>
<dependencies>
  <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-container-image-jib</artifactId>
  </dependency>
</dependencies>
```

This is also somehow related to #8654

**Implementation ideas**

I don't know if it is technically feasible for container-image-* extensions to change the behavior of NativeImageTest, which is core.
NativeImageLauncher might use TestContainers to start the containerized native image if `quarkus.container-image.build build=true`, rather than trying to launch the xxx-runner native executable ?
It would look for the image built during package phase, retrieving it from the docker daemon or the docker registry (depending on value of `quarkus.container-image.push`).

**Comment by geoand** [comment]
This is a very intersting idea. 

@stuartwdouglas IIRC you had a similar idea?

**Comment by ebullient** [comment]
I just ran into this (again), too. I remember talking to Stuart about it.. a long time ago. 

I work (sometimes) on a mac. My [monster-combat](https://github.com/ebullient/monster-combat) application can act as a reproducer if you like (two quarkus applications in there). 

When I'm working on linux, this sequence just works: 

```bash
# build images
./mvnw install

# build native quarkus images (with GraalVM or Mandrel)
./mvnw install -Dnative -pl quarkus-micrometer,quarkus-mpmetrics
```

If I try the latter command on a mac (I assume windows would be the same, but I don't have one of those), this happens: 

```bash
[INFO] Running dev.ebullient.dnd.NativeEncounterResourceIT
Executing [/Users/elh/git/ebullient/monster-combat/quarkus-micrometer/target/mc-quarkus-micrometer-0.4.0-runner, -Dquarkus.http.port=8183, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8183, -Dquarkus.log.file.path=target/target/quarkus.log]
/Users/elh/git/ebullient/monster-combat/quarkus-micrometer/target/mc-quarkus-micrometer-0.4.0-runner: /Users/elh/git/ebullient/monster-combat/quarkus-micrometer/target/mc-quarkus-micrometer-0.4.0-runner: cannot execute binary file
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.363 s <<< FAILURE! - in dev.ebullient.dnd.NativeEncounterResourceIT
[ERROR] testAnyEndpoint  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] testPrometheusScrapeEndpoint  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] testFaceoffEndpoint  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException

[ERROR] testMeleeEndpoint  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   NativeEncounterResourceIT.testAnyEndpoint ? NullPointer
[ERROR]   NativeEncounterResourceIT.testFaceoffEndpoint ? NullPointer
[ERROR]   NativeEncounterResourceIT.testMeleeEndpoint ? NullPointer
[ERROR]   NativeEncounterResourceIT.testPrometheusScrapeEndpoint ? NullPointer
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
```

I am deliberately creating a native image here, which means (on mac) that I have to use a container for that build step. The container then writes to the same place that the os-native build would, so I end up with a linux binary instead of a mac binary (granted, this behavior is needed for CI... )

In my opinion, the standard maven targets should just work. For now, I think I'm going to have to document a bit of song and dance to separate the steps. 

I don't particularly care about the how here: 
* the container build could always white the binary to a different place, using an additional property to control whether or not the binary should be copied back to the root of the target/output dir, 
* we could use the native image to run the tests somehow (that would be ideal, as I would be testing the binary I would eventually want to run)
* Some other thing I haven't thought of. ;)

**Comment by geoand** [comment]
I certainly think we can take `container-image` build into account here and make it transparent to users of `@NativeImageTest`

@WDYT @stuartwdouglas ?

**Comment by stuartwdouglas** [comment]
My idea was that our integration tests should run on whatever the final output was:
- For a normal jar build it just starts the resulting production jar
- For a native build it runs the native application directly
- For a container build it runs the container and tests the container
- If you want to get really fancy for an OpenShift/kube build it can test the app running in the cloud

**Comment by geoand** [comment]
@stuartwdouglas I assume that are thinking of a new annotation right? Something like `@QuarkusIntegrationTest`?

**Comment by stuartwdouglas** [comment]
Yes, exactly.

**Comment by geoand** [comment]
I'll probably start working on it towards the end of the week or the beginning of next week

**Comment by ebullient** [comment]
For an additional integration test, sure -- but for my existing test, I would like that just to work, whether I'm on Linux or on Windows/Mac, without having to do a dance around additional/separated steps.

**Comment by geoand** [comment]
What Stuart and I mention should just work if implemented properly.

Essentially `@QuarkusIntegrationTest` will deprecate `@NativeTest`

**Comment by geoand** [comment]
I will start working on this today and should have something by early next week

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15009 is a very rough first version of this that implements the 3 first parts of https://github.com/quarkusio/quarkus/issues/13818#issuecomment-758373951

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15009 should now be usable if you want to test it let me know what you think
