### ISSUE TITLE
RESTEasy: XmlMapperCustomizer

### ISSUE THREAD

**Issue by sirAlexanderT** [quarkusio/quarkus#13821]
**Description**
so with RestEasy you can customize your ObjectMapper like so
`
@Singleton
public class MyObjectMapperCustomizer implements ObjectMapperCustomizer {

    @Override
    public void customize(ObjectMapper objectMapper) {
        // To suppress serializing properties with null values
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    }
}
`
Would be great to have the same support for XML i.e.  a  io.quarkus<>XmlMapperCustomizer ?

**Comment by gsmet** [comment]
Are you referring to the Jackson XmlMapper? If so, what do you use it to have RESTEasy make use of it?

**Comment by sirAlexanderT** [comment]
> Are you referring to the Jackson XmlMapper? If so, what do you use it to have RESTEasy make use of it?

@gsmet Yes, I am referring to the Jackson XmlMapper. So just like the Json equivalent, I'm able to customise the output I require and also use 'mixins'. i.e.
`xmlMapper.registerModule(new JavaTimeModule());
  xmlMapper.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
  xmlMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
  xmlMapper.addMixIn(Some.class, SomeXmlMixin.class);
`

**Comment by gsmet** [comment]
OK. What I don't understand is that we have absolutely no support for it at the moment AFAIK.

So aren't you manually instantiating it anyway? Or am I missing something?

**Comment by sirAlexanderT** [comment]
> OK. What I don't understand is that we have absolutely no support for it at the moment AFAIK.
> 
> So aren't you manually instantiating it anyway? Or am I missing something?

- could possibly be me misunderstanding it all. But with RestEasy both json and xml serialization/deserialization is supported out of the box, depending on the "Media.Type Header you use i.e. "application/json" or "application/xml"

- so my assumption is, there is possibly an xmlMapper configured somewhere under the hood.

**Comment by gsmet** [comment]
Which RESTEasy dependencies did you add?

Because Jackson's `XmlMapper` comes with `jackson-dataformat-xml` and I don't see us depending on it.

**Comment by sirAlexanderT** [comment]
just these:
```
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
```

**Comment by sirAlexanderT** [comment]
@gsmet so if RestEasy isn't using xmlMapper internally, what is it using? and how can I customize or tweak the config

**Comment by geoand** [comment]
For XML support with RESTEasy, Quarkus uses JAX-B, see https://github.com/quarkusio/quarkus/blob/2.1.0.Final/extensions/resteasy-classic/resteasy-jaxb/runtime/pom.xml
