### ISSUE TITLE
Why quarkus does not generate basic k8s deployment file

### ISSUE THREAD

**Issue by smmansoor** [quarkusio/quarkus#1382]
Quarkus template project generate docker file, but does not generate kubernetes deployment file. Helidon does it for you.

**Comment by smmansoor** [comment]
Quarkus template project generate docker file, but does not generate kubernetes deployment file. Helidon does it for you.

**Comment by cescoffier** [comment]
We could provide a template but what would be the advantages over the instructions we are giving in https://quarkus.io/guides/kubernetes-guide.html?

Also, can you upload the template generated by Helidon?

**Comment by cescoffier** [comment]
I've found an example of generated template:
https://github.com/oracle/helidon/blob/master/examples/quickstarts/helidon-quickstart-se/src/main/k8s/app.yaml

**Comment by geoand** [comment]
@smmansoor We have an interesting as work in progress for this: https://github.com/quarkusio/quarkus/pull/1300

With the proposed [ap4k](https://github.com/ap4k/ap4k) extension you will able to do a lot than just generate a Kubernetes file from a template :wink:

**Comment by mansoors-rabo** [comment]
> I've found an example of generated template:
> https://github.com/oracle/helidon/blob/master/examples/quickstarts/helidon-quickstart-se/src/main/k8s/app.yaml



> We could provide a template but what would be the advantages over the instructions we are giving in https://quarkus.io/guides/kubernetes-guide.html?
> 
> Also, can you upload the template generated by Helidon?

Advanteges are same as for docker template and generating a minimal project.

**Comment by smmansoor** [comment]
>We could provide a template but what would be the advantages over the instructions we are giving in >https://quarkus.io/guides/kubernetes-guide.html?


Advantages are same as for docker template and generating a minimal project.

**Comment by smmansoor** [comment]
> @smmansoor We have an interesting solution as work in progress for this: #1300
> 
> With the proposed [ap4k](https://github.com/ap4k/ap4k) extension you will able to do a lot than just generate a Kubernetes file from a template 😉

Thanks @geoand. I will have a look at that. But adding a template will provide a launching pad to the developer.

**Comment by smmansoor** [comment]
> > @smmansoor We have an interesting solution as work in progress for this: #1300
> > With the proposed [ap4k](https://github.com/ap4k/ap4k) extension you will able to do a lot than just generate a Kubernetes file from a template 😉
> 
> Thanks @geoand. I will have a look at that. But adding a template will provide a launching pad to the developer.

I just have a look at ap4k and its really cool  👍 . This should be added on the quarkus documentation under extension section.

**Comment by smmansoor** [comment]
> I've found an example of generated template:
> https://github.com/oracle/helidon/blob/master/examples/quickstarts/helidon-quickstart-se/src/main/k8s/app.yaml

Great. Can we generate the same? I am happy to add this functionality. Can you please guide me?

**Comment by geoand** [comment]
@smmansoor once we merge the PR there will  be documentation for using ap4k as well

**Comment by smmansoor** [comment]
Thanks @geoand and @cescoffier 
Another issue I have noticed  is regarding docker file. The docker file create by maven template project in src directory, is for graal vm. It does not get regenerated in target folder based on VM used for building the project. 

We should place the template file in src directory and then generate one on build using maven-resources-plugin.

**Comment by cescoffier** [comment]
Why would you need a second one? 
We have added a .dockerignore to reduce the size of the context so the build is much faster.

**Comment by stuartwdouglas** [comment]
Pretty sure this is now out of date?

**Comment by geoand** [comment]
Yes, this has been implemented
