### ISSUE TITLE
quarkus.container-image.group default to project.groupId

### ISSUE THREAD

**Issue by rquinio** [quarkusio/quarkus#13823]
**Description**

Currently  `quarkus.container-image.group` defaults to `${user.name}`, while `quarkus.container-image.name` defaults to `${project.artifactId}`
But we already have some namespacing information in the Maven pom via `${project.groupId}`, which is not used today.
Since dots are not allowed in docker, they'd have to be replaced by `/`:

```xml
<groupId>com.company.domain</groupId>
<artifactId>microservice</artifactId>
<version>1.0-SNAPSHOT</version>
```
Docker:  `<registry>/com/company/domain/microservice:1.0-SNAPSHOT`

Docker coordinates don't usually follow the reverse DNS convention, but Maven doesn't need to either, as Maven artifacts of a cloud-native application are typically not deployed anywhere, only the Docker image is:

```xml
<groupId>domain</groupId>
<artifactId>microservice</artifactId>
<version>1.0-SNAPSHOT</version>
```
Docker: `<registry>/domain/microservice:1.0-SNAPSHOT`

**Workaround** 

Note that this can be done today via a bit of Maven hacking:

```xml
<properties>
  <quarkus.container-image.group>${groupId.with.slash}</quarkus.container-image.group>
</properties>  
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>build-helper-maven-plugin</artifactId>
  <version>3.0.0</version>
  <executions>
    <execution>
      <id>regex-property</id>
      <phase>initialize</phase>
      <goals>
        <goal>regex-property</goal>
      </goals>
      <configuration>
        <name>groupId.with.slash</name>
        <value>${project.groupId}</value>
        <regex>\.</regex>
        <replacement>/</replacement>
        <failIfNoMatch>true</failIfNoMatch>
      </configuration>
    </execution>
  </executions>
</plugin>
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>properties-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>fix-jib-build-with-system-properties</id>
      <phase>initialize</phase>
      <goals>
        <goal>set-system-properties</goal>
      </goals>
      <configuration>
        <properties>
          <property>
            <name>groupId.with.slash</name>
            <value>${groupId.with.slash}</value>
          </property>
        </properties>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by geoand** [comment]
Thanks for the issue.

This is something we don't want to change to be honest, as it has the potential to break to many applications

**Comment by rquinio** [comment]
@geoand Indeed it may be a bit too late for such change.
Maybe it could make sense as a built-in optional alternative ?  Though Quarkus is opinionated on simplicity and having a single way to do things !

I'd be curious to know how many people actually:
- rely on the default, and override user.name at build time (local or CI)
- vs hardcode the override of `quarkus.container-image.group` inside all their microservices pom.xml, for build reproducibility.

**Comment by geoand** [comment]
What we could do, is "inject" a new property into the build, something like `quarkus.application.group`, but that would still not contain the slashes.
Of course we could go even farther and add a property with slashes instead of dots, but it seems a little contrived to be honest.

**Comment by geoand** [comment]
I am going to close this as there has been little interest. If people really want this, let me know :)
