### ISSUE TITLE
PanacheEntityBase: support collections in Hibernate filters

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13832]
**Description**
In Hibernate, we can filter using a collection of items by:

```java
@FilterDef(name = "nameFilter", parameters = {@ParamDef(name = "names", type = "string")})
@Filter(name = "nameFilter", condition = "name in (:names)")
```

And then calling to the `setParameterList`:

```java
Collection names = // ...
filter.setParameterList("names", names);
```

The problem is that we can't make use of the setParameterList as the setParameter is hardcoded [here](https://github.com/quarkusio/quarkus/blob/ff0465fa4ae559bec41e7e114cc88650fe7a2277/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L350).

**Implementation ideas**

An idea to implement this feature is to have a custom Filter definition class instead of[ a plain Map<String, Object>](https://github.com/quarkusio/quarkus/blob/ff0465fa4ae559bec41e7e114cc88650fe7a2277/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L53). This way we can add extra information to instruct the later code what to do:

```java
query.filter("nameFilter", Parameters.withList("name", "a name"));
```

Whereas the new method `withList` will instruct the usage of the setParameterList. 

Another alternative is to infer the usage of the setParameterList if the value field in Parameters.with is a collection. But I don't think this is a good idea because some users might want to still use the setParameter with collections.

**Comment by FroMage** [comment]
Not sure I understand the difference in semantics between `setParameter` and `setParameterList` if both take a collection. Should we really treat them different @Sanne ?

**Comment by fiorenzino** [comment]
@FroMage Following your suggestion, you should change:

` filter.setParameter(paramEntry.getKey(), paramEntry.getValue());`
https://github.com/quarkusio/quarkus/blob/ff0465fa4ae559bec41e7e114cc88650fe7a2277/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L350

in something like this:

            ```
            // in Parameters.values map
            Map<String, Object> map = new HashMap();
            map.put("names", values);

            Filter filter = getEntityManager().unwrap(Session.class).enableFilter("nameFilter");
            for (Map.Entry<String, Object> paramEntry : map.entrySet()) {
                if (paramEntry.getValue() instanceof List<?>) {
                    filter.setParameterList(paramEntry.getKey(), (List<?>) paramEntry.getValue());
                } else if (paramEntry.getValue() instanceof Collection<?>) {
                    filter.setParameterList(paramEntry.getKey(), (Collection<?>) paramEntry.getValue());
                } else {
                    filter.setParameter(paramEntry.getKey(), paramEntry.getValue());
                }
            }
```
For List and Collection is ok, but if you have some Object[] values:
What's the best way to check and cast an array (ie String[], or int[])?

**Comment by FroMage** [comment]
You can check for `instanceof Object[]` but that won't work for primitives, you have to add an `instanceof char[]` etc…

But I'd like to have @Sanne's answer before we touch that.

**Comment by gavinking** [comment]
I mean this distinction is a pretty ancient feature of Hibernate. And it applies to `Query` also, not just to filters. And I forget what the JPA spec has to say about it. First thing to check is if and how you can do this in JPA.

**Comment by ahmadshabib** [comment]
the way it is implemented in hibernate-orm is this 
https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/internal/FilterImpl.java.
currently, I am trying to implement something for my project and I found out that it is not supported.
I would like to work on the issue if you like to, but the cases here are important but as @FroMage mentioned these checks can be done with `instanceof char[]`
