### ISSUE TITLE
PanacheEntityBase: support for Hibernate @FilterJoinTable

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13831]
**Description**
In https://github.com/quarkusio/quarkus/issues/9036, Quarkus added the support of hibernate `@Filter`. But there is another Hibernate annotation `@FilterJoinTable` that is a must to have filters in entity associations. 

**Implementation ideas**
Similarly to the `@Filter` annotation, this is how the `@FilterJoinTable` annotation is used:

```
@Entity(name = "parent")
@FilterDef(name = "byChildNames", parameters = { @ParamDef(name = "name", type = "string") })
@FilterJoinTable(name = "byChildNames", condition = "{c}.name = :name", aliases = @SqlFragmentAlias(alias = "c", table = "child"))
public class ParentEntity extends PanacheEntity {
    @OneToMany
    @JoinTable(joinColumns = { @JoinColumn(name = "id") }, inverseJoinColumns = { @JoinColumn(name = "child_id") })
    public Set<ChildEntity> extensions;
}
```

The usage should be the same as the annotation `@Filter`:

```java
query.filter("byChildNames", Parameters.with("name", "my child name"));
```

**Comment by FroMage** [comment]
Are you sure this isn't working already? IMO this should already work with the current API.

**Comment by Sgitario** [comment]
@FroMage thanks for looking into this! I would say that unless I'm doing something wrong, this is not working:

I have [a project](https://github.com/Sgitario/beefy-scenarios/tree/add_filters_using_panache/011-quarkus-panache-rest-flyway) with [a test](https://github.com/Sgitario/beefy-scenarios/blob/51c78c95ab9788b8b56f6cf551a3237a6e1c6ef5/011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java#L107) that reproduces this issue.

Basically, this is how we declare the filter:

```java
@Entity(name = "application")
@FilterDef(name = "useServiceByName", parameters = { @ParamDef(name = "name", type = "string") })
@FilterJoinTable(name = "useServiceByName", condition = "{s}.name = :name", aliases = @SqlFragmentAlias(alias = "s", table = "service"))
public class ApplicationEntity extends PanacheEntity {
// ...
   @JoinTable(name = "service", joinColumns = { @JoinColumn(name = "id") }, inverseJoinColumns = {
            @JoinColumn(name = "application_id") })
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    public List<ServiceEntity> services = new ArrayList<>();
}
```

But when using the filter, it seems to be ignored (no errors, no warnings, but the query is not filtering by the service name).

**Comment by FroMage** [comment]
I'm not sure why, we don't do anything special about `FilterDef`. This is ORM's job.

OK, I see `quarkus-hibernate-orm` has special handling of `FilterDef` but not `FilterJoinTable`, probably that's it, no @Sanne ?

**Comment by Sanne** [comment]
Well `@FilterDef` requires special handling as it's allowed on packages, but `@FilterJoinTable` shouldn't need ay special treatment.

I could be wrong though, this needs testing. @FroMage I see that when you fixed `FilterDef` in #9238 you only patched Panache code.

**Comment by FroMage** [comment]
I didn't _fix_ them: I added code to enable filters, no matter how they are defined. Or are you saying that to enable those filters there's another API than https://github.com/quarkusio/quarkus/pull/9238/files#diff-f1dd80cb4009ba16114063c3cd4e043c18fb68ef65815b34c14989ef4ff72b9fR386 ?

**Comment by Sgitario** [comment]
> I didn't _fix_ them: I added code to enable filters, no matter how they are defined. Or are you saying that to enable those filters there's another API than https://github.com/quarkusio/quarkus/pull/9238/files#diff-f1dd80cb4009ba16114063c3cd4e043c18fb68ef65815b34c14989ef4ff72b9fR386 ?

I spent some more time to analyze this issue: 
- The hibernate `@Filter` annotation when filtering a **column** works fine at class level (according to the Hibernate documentation, It's not supposed to work at field level for **columns**):

```java
@Entity(name = "application")
@FilterDef(name = "useLikeByName", parameters = { @ParamDef(name = "name", type = "string") })
@Filter(name = "useLikeByName", condition = "name like '%' || :name || '%'") // works!
public class ApplicationEntity extends PanacheEntity {
    @NotEmpty
    @Column(unique = true, nullable = false)
    @Filter(name = "useLikeByName", condition = "name like '%' || :name || '%'") // it does not work! but expected
    public String name;
```

- The hibernate `@Filter` annotation when filtering an **association** works fine at field level and according to the same Hibernate documentation, It's not supposed to work at class level for associations:

```java
@Entity(name = "application")
@FilterDef(name = "useServiceByName", parameters = { @ParamDef(name = "name", type = "string") })
@Filter(name = "useServiceByName", condition = "{s}.name = :name", aliases = {
            @SqlFragmentAlias(alias = "s", table = "service")
    }) // it does not work! but expected
public class ApplicationEntity extends PanacheEntity {
    @JsonManagedReference
    @OneToMany(mappedBy = "application", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @Filter(name = "useServiceByName", condition = "{s}.name = :name", aliases = {
            @SqlFragmentAlias(alias = "s", table = "service")
    }) // works!
    public List<ServiceEntity> services = new ArrayList<>();
```

- The hibernate `@FilterJoinTable` should work as the filter `@Filter` annotation for associations. The problem here was that it needs to work with the `@JoinTable` annotation which there is an issue with (reported by [this ticket](https://github.com/quarkusio/quarkus/issues/13842)).

Therefore, I'm closing this issue as the real issue was related to https://github.com/quarkusio/quarkus/issues/13842.

**Comment by Sanne** [comment]
many thanks @Sgitario
