### ISSUE TITLE
Rest-client extension does not record any metrics about client calls

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#13847]
I followed [the official documentation](https://quarkus.io/guides/rest-client) to create an app that uses the rest-client extension to make http calls.
I also added the micrometer lib to the project, so I get metrics.
My expectation is that I can get out-of-the-box metrics about rate, latency (percentiles), errors, etc on the clients calls.

But when I execute my example (and call localhost:8080/country/name/{name}), I do not see any client related metrics, even though I can see the result of the client call on my browser.

# Steps to reproduce:
1. Clone https://github.com/oscarfh/quarkus-rest-metrics
2. Run ./mvnw compile quarkus:dev
3. go to http://localhost:8080/country/name/germany
4. go to http://0.0.0.0:8080/metrics
5. Notice that there is no metric about the rest client call performed when you executed item 3

**Comment by oscarfh** [comment]
cc @radcortez because I think you are the one responsible about for this extension, right?

**Comment by jmartisk** [comment]
We don't currently support any metrics associated with rest clients.
There are metrics for the server side (statistics how often each REST method is called and how long it takes) if you use the SmallRye Metrics extension.
With the Micrometer extension, we support a lower-level approach of gathering metrics on the HTTP (Vert.x) layer. But it's, again, for the server side.

**Comment by oscarfh** [comment]
@jmartisk Do you think this should exist?
I was planning to create an interceptor (or something similar) that intercepts calls to any bean annotated with `@RegisterRestClient` and creates the metrics.
An Alternative would be to extend the rest-client extension to wrap the resteasy proxy with a custom object that would register the metrics. I analyzed the code and I don't know if that is feasible.

What do you think? Is any of these a viable solution?

**Comment by ebullient** [comment]
You can certainly create a client interceptor to emit metrics as a near term (use the appropriate API for the metrics extension you're using).

We can also add support for http client metrics to the micrometer extension (which will capture outbound vert.x requests). I'll get started on that after publishing a few things today. If you'd like to help, that's cool. ;)

**Comment by oscarfh** [comment]
@ebullient I will try to get something started.

**Comment by ebullient** [comment]
Ok. For the micrometer extension, I'll be emulating this for clients: https://github.com/quarkusio/quarkus/blob/master/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java (to emit metrics akin to what Spring actuator emits, as a reasonable baseline)

**Comment by oscarfh** [comment]
I am trying this right now, but I cannot get it called, because it seems that using the resteasy does not create an HttpClientImpl

**Comment by ebullient** [comment]
Y. I double checked -- resteasy client goes straight out using apache http client, that's why I hadn't added the vert.x based instrumentation. So we'll want client request/response filters.. And I think we may be able to keep those in the rest-client extension in this case .. I'll probably crib from what you get working..

**Comment by oscarfh** [comment]
I just got the client filters to work, see https://github.com/oscarfh/quarkus-rest-metrics/commit/4b500e573e20fe122ebee6ffbf8b8892359385b3

I will start working on a PR to get the rest-client extension to create these filters.

**Comment by ebullient** [comment]
ContainerRequestFilter / ContainerResponseFilter are server side?
