### ISSUE TITLE
Mutual TLS with client-auth=request breaks HTTP Basic authentication

### ISSUE THREAD

**Issue by renegrob** [quarkusio/quarkus#13844]
**Describe the bug**

I have a project with Mutual TLS and HTTP Basic authentication configured (see Configuration section).
If I activate mutual TLS with `client-auth: request` it breaks the HTTP Basic authentication (quarkus-elytron-security-properties-file).
While it makes sense that we can only have one user principal, it doesn't make sense to be anonymous just because the client could send a client certificate (which is optional in this case).  

**Expected behavior**

If Mutual TLS is activated and no client certificate is provided then other authentication mechanism should still trigger (https://quarkus.io/guides/security#combining-authentication-mechanisms), 
meaning that in my case the HTTP Basic authentication would work. 

**Actual behavior**

* If I set `client-auth: request` and provide a client certificate, the request arrives authenticated as
`{"principalName":"CN=test-client,OU=dev,O=acme.org,C=US", "anonymous":false, "credentialTypes":"io.quarkus.security.credential.CertificateCredential"}`
which is as expected. (The code producing the JSON is in the "To Reproduce" section.)
* But if I don't provide a client certificate but an HTTP Basic authentication header, the request arrive authenticated as anonymous
`{"principalName":"","anonymous":true,"credentialTypes":""}`
* If I remove `client-auth: request` from `application.yaml`, the user gets properly authenticated and arrives as
`{
"principalName":"user1",
"anonymous":false,
"credentialTypes":"io.quarkus.security.credential.PasswordCredential"
}`

**To Reproduce**

Take any project with mutual TLS and add the following REST endpoint and adjust the configuration (see Configuration section). 
Then execute the steps described in the Acutal Behavior section.

#### `Diagnostics.java`
```java
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import io.quarkus.security.identity.SecurityIdentity;

@Path("/diagnostics")
public class Diagnostics {

    @Inject
    SecurityIdentity securityIdentity;

    @GET
    @Path("currentPrincipal")
    @Produces(MediaType.APPLICATION_JSON)
    public SecurityPrincipalInfo currentPrincipal() {
        return new SecurityPrincipalInfo(securityIdentity);
    }

}
```

#### `SecurityPrincipalInfo.java`
```Java
import java.util.stream.Collectors;

import io.quarkus.security.identity.SecurityIdentity;

public class SecurityPrincipalInfo {
    private final String principalName;
    private final boolean anonymous;
    private final String credentialTypes;

    SecurityPrincipalInfo(SecurityIdentity securityIdentity) {
        this.anonymous = securityIdentity.isAnonymous();
        this.principalName = securityIdentity.getPrincipal().getName();
        credentialTypes = securityIdentity.getCredentials().stream().map(credential -> credential.getClass().getName())
                .collect(Collectors.joining(", "));
    }

    public String getPrincipalName() {
        return principalName;
    }

    public boolean isAnonymous() {
        return anonymous;
    }

    public String getCredentialTypes() {
        return credentialTypes;
    }
}
```

**Configuration**

#### `application.yaml`
```
quarkus:
  http:
    insecure-requests: redirect
    ssl-port: 8443
    ssl:
      client-auth: request
      certificate:
        key-store-file-type: JKS
        key-store-file: server-keystore.jks
        key-store-password: secret
        trust-store-file: server-truststore.jks
        trust-store-password: secret
    auth:
      proactive: true

  security:
    users:
      file:
        enabled: true
        plain-text: true
        users: users.properties
        roles: roles.properties 
```

#### `users.properties`
```
user1=pwd1
```

#### `roles.properties`
```
user1=Role1
```

**Screenshots**
n/a

**Environment (please complete the following information):**
- Output of `uname -a` or `ver`:
```
$ uname -a
Linux automatix 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Output of `java -version`:
```
$ java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
```
- GraalVM version (if different from Java):`n/a`
- Quarkus version or git rev:
  `1.10.2.Final`
- Build tool (ie. output of `mvnw --version` or `gradlew --version`):
```
./gradlew --version

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9.1 (Azul Systems, Inc. 11.0.9.1+1-LTS)
OS:           Linux 5.4.0-56-generic amd64
```

**Additional context**
n/a

**Comment by sberyozkin** [comment]
@renegrob Thanks, this should be `client-auth=required`, can you retry please with the correct value ?

**Comment by renegrob** [comment]
`client-auth=required` means that mutual TLS is mandatory. I can't do that because not all TLS connections will use a client certificate but some have to. That's exactly the point I need to support many authentications including mutual TLS but I can only force them on certain endpoints by verifying the roles (I can do that with a SecurityidentityAugmentor).

**Comment by sberyozkin** [comment]
@renegrob Oh I see, I thought it was a typo :-)
So it does not work only if it is `request` but does work if it is `required` ?
In this case I guess the server-side MTLS authentication mechanism needs to be configured to return no `SecurityIdentity` is no certificate is available for the next mechanism to give it a try.
This is interesting, for the MTLS OIDC token binding I'll need both the client certificate authentication and the bearer token authentication...

**Comment by renegrob** [comment]
Well, client-cert authentication works in both cases. However, I need HTTP authentication to be triggered, too.
> In this case I guess the server-side MTLS authentication mechanism needs to be configured to return no SecurityIdentity if no certificate is available for the next mechanism to give it a try.
Exactly.
> This is interesting, for the MTLS OIDC token binding I'll need both the client certificate authentication and the bearer token authentication...
Well, actually I even will need nested authentication (Mutual TLS + other) and also switch between HTTP BASIC, BEARER (JWT and OAuth2 with Opaque-Token) but that's another topic and not part of this bug. For that I'm aware that I'll have to build custom logic. My goal is that in the end the customer can configure which authentication is used on what endpoint and also enforce technical authentication with Mutual TLS on some endpoints. I'm porting an authentication server to make it cloud ready and it needs to support a lot of authentication schemes by design.

**Comment by sberyozkin** [comment]
@renegrob Sounds good; we'll invest more time into making it more flexible switching dynamically between different auth mechanisms next year

**Comment by stuartwdouglas** [comment]
I tried to reproduce this in a test and it appeared to work fine:  https://github.com/quarkusio/quarkus/pull/13865

Can you provide a reproducer project?

**Comment by renegrob** [comment]
You can find the reproducer here: https://github.com/renegrob/quarkus-issue-13844
I'm really wondering what's the reason that it doesn't work in my setup.

**Comment by renegrob** [comment]
I think the problem is that only one authentication mechanism is active in my configuration. What did I do wrong?

**Comment by renegrob** [comment]
I found the difference: `quarkus.http.auth.basic=true` -> as soon as I add this property it works!
It seems to works without that property as long as Basic Auth is the only configured authentication mechanism.

**Comment by stuartwdouglas** [comment]
Basic auth is the default option, as long as no other auth mechanisms are enabled it will work out of the box. If you want multiple mechanisms then you need to explicitly enable it.

**Comment by sberyozkin** [comment]
Thanks @stuartwdouglas I'll update the docs with this point

**Comment by renegrob** [comment]
Thanks @stuartwdouglas and @sberyozkin
