### ISSUE TITLE
Add oauth2 configuration to swagger-ui

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#13845]
**Description**
Already many configurations for the openapi / swagger-ui can be set in the application.properties. It would be nice to be able to set the oauth 2 configuration properties (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md) 

This would allow to set preconfigure the oauth login dialog with all the necessary options.

**Implementation ideas**
As example, with spring-doc the properties can be set as follow:
`springdoc.swagger-ui.oauth.client-id=theclient`
so for quarkus it could be 

```
quarkus.swagger-ui.oauth.client-id=theclient
```

**Comment by Legion2** [comment]
Is there a workaround for setting this config and other ui configuration options?

**Comment by Legion2** [comment]
I want to make a pull request for this, but I don't know how to support the nested configurations such as `additionalQueryStringParams` for OAuth 2.0 configuration `initOAuth` method.

**Comment by phillip-kruger** [comment]
You can do a PR and mark it as WIP (or draft) and I can try and help from there ?

**Comment by Legion2** [comment]
Ok, after looking into it more, I found that this has to be first implemented in `smallrye-open-api` see the [TODO](https://github.com/smallrye/smallrye-open-api/blob/master/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexCreator.java#L213-L216)

**Comment by Legion2** [comment]
I created an Issue there https://github.com/smallrye/smallrye-open-api/issues/663

**Comment by Legion2** [comment]
@phillip-kruger Thanks for you work, I tried 1.12.0.CR1 and it works great. Now I only need to wait for https://github.com/smallrye/smallrye-open-api/pull/679 to remove the workaround `oauth2-redirect.html` file.
