### ISSUE TITLE
REST Data Panache: Wrong behaviour when using @JoinTable and @OneToMany

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13842]
**Describe the bug**
When using parent/child entities like:

```java
@Entity(name = "application")
public class ParentEntity extends PanacheEntity {
    // ...

    @JoinTable(name = "child", joinColumns = { @JoinColumn(name = "id") }, inverseJoinColumns = {
           @JoinColumn(name = "child_id") })
    @JsonManagedReference
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    public List<ChildEntity> children = new ArrayList<>();
}
```

And:

```java
@Entity(name = "child")
public class ChildEntity extends PanacheEntity {
    // ...

    @ManyToOne
    @JoinColumn(name = "parent_id", nullable = false)
    @JsonBackReference
    public ParentEntity parent;
}
```

Then, the parent resource:

```java
public interface ParentResource extends PanacheEntityResource<ParentEntity, Long> {
}
```

When I add (or update) a parent entity with a child:

```java
ParentEntity request = new ParentEntity();
// ... 
ChildEntity child = new ChildEntity();
// ...
request.services.add(child);
given().accept(MediaType.APPLICATION_JSON).contentType(ContentType.JSON)
           .when().body(request).post("/parent")
           .then().statusCode(HttpStatus.SC_CREATED);
```

Note that I'm using the `@JsonManagedReference` and `@JsonBackReference` annotations to deal with [bidirectional relationships](https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion) which I think would be nice to add to the documentation. 

**Expected behavior**

The above REST call should work as expected and create both parent and child entities.

**Actual behavior**

The above REST call fails because:

```
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "name" of relation "service" violates not-null constraint
  Detail: Failing row contains (1, null, 2).
```

It seems that the framework is inserting the same child entity twice: one with the data populated and the second with null data and hence giving the not-null constraint. 

**To Reproduce**

This module can be used to reproduce this issue: https://github.com/Sgitario/beefy-scenarios/blob/9102ca699eedc6920b7356aac17efb2f57f4086f/011-quarkus-panache-rest-flyway/src/main/java/io/quarkus/qe/ApplicationEntity.java#L41

Just change the above line to:

```java
@JoinTable(name = "service", joinColumns = { @JoinColumn(name = "id") }, inverseJoinColumns = {
            @JoinColumn(name = "application_id") })
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JsonManagedReference
    public List<ServiceEntity> services = new ArrayList<>();
```

And uncomment the test from [this link](https://github.com/Sgitario/beefy-scenarios/blob/9102ca699eedc6920b7356aac17efb2f57f4086f/011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/PostgreSqlApplicationResourceTest.java#L94). When running this test, everything should work fine, but it's failing with the above exception.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.9" 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 999-SNAPSHOT
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback.
