### ISSUE TITLE
Reactive RESTEasy - Project demonstrating various issues

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#13852]
**Describe the bug**
I have tried RESTEasy reactive on a project and came across numerous issues. I have created a replicator project which simplifies down the various issues I have found thus far:
1) Sub resource path params are not bound correctly
2) A POST which accepts a List of non-trivial Objects fails deployment
3) Binding a BigDecimal as a path param causing booting to fail with a ClassNotFoundException
4) Returning a List<String> encodes the result incorrectly
5) Binding a resource method with multiple Method annotations results in only the first one being bound
6) Calls to sub resources pass through a ContainerRequestFilter for each sub resource level
7) Calling requestContext.getUriInfo().getMatchedResources() in a ContainerResponseFilter results in an NPE  java.lang.NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.mapping.RuntimeResource.getClassPath()" because "this.target" is null

**Expected behavior**
All of these should work. The sample project passes all tests using standard RESTEasy

**Actual behavior**
All 7 test cases fail

**To Reproduce**
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

**Configuration**
Nothing

**Screenshots**
Run the reproducer to see failures. Change the pom to non-reactive mode and all tests pass

**Environment (please complete the following information):**
This is not environment specific

**Additional context**
NA

**Comment by geoand** [comment]
Thanks a lot for reporting these issues!

I have opened https://github.com/quarkusio/quarkus/pull/13853 to start adding fixes.

For `5`, this is not mentioned anywhere in the spec nor is it tested by the TCK. 
I also found https://www.eclipse.org/lists/jaxrs-dev/msg00171.html where someone asks for the same feature.

We don't currently support it, but we certainly could (in order be in line with what RESTEasy proper does), although I am personally against it.
@FroMage @stuartwdouglas WDYT?

**Comment by bcluap** [comment]
Thanks Georgios,

The support from the Quarkus team never fails to amaze me!

To be honest 5 is easy to work around but I just feel that adoption and
migration from standard resteasy will be much higher if the new version
acts the same. People will be scared of the migration if it introduces
run-time changes which will only be discovered by end users facing issues.

Perhaps 5 could be solved with a deployment failure saying that multiple
method annotations are not supported? Then at least it can be addressed
without runtime bugs?

**Comment by geoand** [comment]
> Thanks Georgios, The support from the Quarkus team never fails to amaze me! To be honest 5 is easy to work around but I just feel that adoption and migration from standard resteasy will be much higher if the new version acts the same. People will be scared of the migration if it introduces run-time changes which will only be discovered by end users facing issues. Perhaps 5 could be solved with a deployment failure saying that multiple method annotations are not supported? Then at least it can be addressed without runtime bugs?

I'm glad you feel that way :)

I like your idea for `5` - it makes a lot of sense

**Comment by geoand** [comment]
@stuartwdouglas since you know the most about the sub-resource handling, mind taking up the related issues?

Thanks

**Comment by bcluap** [comment]
I've updated the reproducer with a new issue:
8) If a filter aborts with a payload > 30463 bytes and there is a WriterInterceptor then an exception occurs:
Caused by: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:226)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:90)

This has something to do with an overflow buffer trying to use the array method on Netty PooledUnsafeDirectByteBuf which is not supported.

**Comment by geoand** [comment]
Nice one, thanks!

**Comment by geoand** [comment]
`4` is just a result of `2` - when `2` gets fixed, `4` will be fixed automatically.

**Comment by FroMage** [comment]
Regarding multiple HTTP methods on a single endpoint method, I don't see why we couldn't implement that, is it really hard?

**Comment by geoand** [comment]
It isn't hard, but I am afraid we could run into weird circumstances with method parameters (like having a body when `GET` and `POST` are both used).
I think it's just more clear to not allow it

**Comment by FroMage** [comment]
GET and POST are indeed weird, but if we have validation, then the body param will fail for the GET validation.

POST/PUT may be more common.

Or a catchall GET PUT POST DELETE

**Comment by geoand** [comment]
I'll take another look when I've dealt with the other issues (which are more important)

**Comment by geoand** [comment]
I'll reopen this as there is one more issue thing (point `8`) that needs to be addressed.
I am working on a fix now and will open a PR soon
