### ISSUE TITLE
Quarkus Remote Development does not work with OpenShift Developer Sandbox

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#13850]
**Describe the bug**
Error trying to remote develop with the [OpenShift Developer Sandbox](https://developers.redhat.com/articles/2020/12/09/get-started-your-developer-sandbox-red-hat-openshift). The generated image cannot write to `/work/dev` directory. The
Exception is  ` java.nio.file.AccessDeniedException: /work/dev`.
In fact, the only writeable directory is `/tmp`.

This error is generated when the pod tries to boot the application in developer mode. As a result, the application never starts.

The application boots successfully by commenting out the QUARKUS_LAUNCH_DEVMODE property.

Note, I also had this problem with RHPDS.

** Reproduce **

- Use code.quarkus.io to create simple "Hello World" application; select the OpenShift and jib extensions
  - Set appropriate properties:
````
quarkus.package.type=mutable-jar
quarkus.live-reload.password=abc123
quarkus.openshift.env.vars.QUARKUS_LAUNCH_DEVMODE=true
quarkus.container-image.builder=jib
quarkus.openshift.expose=true
quarkus.container-image.registry=quay.io
````
- Deploy to OpenShift Developer Sandbox
  - `mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true`

**Comment by stuartwdouglas** [comment]
I don't really know what I can do about this, short of copying the full application into /tmp and launching from there, which really does not feel right.

**Comment by jclingan** [comment]
Yeah, I understand that this is a tough problem. Perhaps I'll track this down internally.

**Comment by stuartwdouglas** [comment]
If this does not work I can probably fix it, either by unpacking to /tmp or somehow doing an in-memory version, but I would rather not spend the time on it if I don't have to.

**Comment by jclingan** [comment]
This does work by mounting a writeable external volume (persistent volume claim) and running the code from that volume.

**Comment by edeandrea** [comment]
I just tried it using the developer sandbox and it worked fine

**Comment by jclingan** [comment]
I'll close this issue. It may be an issue with the base container image used. It does work with S2I though.

**Comment by jfrantzius** [comment]
We're seeing the same problem on Azure Kubernetes Service (AKS). 
@jclingan you mentioned a workaround by using a PVC, do you refer to mounting it as `/work/dev`? Or what do you mean by "running the code from that volume"?
