### ISSUE TITLE
Kafka configuration normalization

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#13889]
**Describe the bug**
Kafka configuration properties should be the same whatever the extension used.

**Expected behavior**
As of now, if you use the `smallrye-reactive-messaging-kafka`, the kafka host is configured through the `kafka.bootstrap.servers` property, but if you use the `quarkus-smallrye-reactive-messaging-kafka`, the you must use `quarkus.kafka-streams.bootstrap-servers` property.

If both extension are used, the configuration miust be duplicated which is error prone.

Actualy, none of the `quarkus-smallrye-reactive-messaging-kafka` properties starts with `quarkus`which seems odd to me.

**Actual behavior**
Configuration property keys should be normalized.

 - Quarkus version : 1.10.3

**Comment by cescoffier** [comment]
SmallRye Reactive Messaging properties do not start with the quarkus prefix because they are defined in the Reactive Messaging specification. 

Regarding this issue, we should make the Kafka streams extension read the `kafka.bootstrap.servers` property as a fallback (if  `quarkus.kafka-streams.bootstrap-servers` is not set)

**Comment by jtama-op** [comment]
Yes I get that property keys are defined by SmallRye Reactive Messaging, but couldn't we provide "translation" from `quarkus` to `SmallRye Reactive Messaging` like property names ? I mean many other extension do exactly that.

**Comment by cescoffier** [comment]
No, unfortunately, it's not that simple in this case. How reactive messaging (not smallrye, the spec) is a bit particular. 

We could prepend "quarkus." to all the properties, but that would only create longer keys.

**Comment by cescoffier** [comment]
BTW, I just opened #14095 which allows Kafka Streams to be configured using `kafka.bootstrap.servers`.

**Comment by cescoffier** [comment]
Fixed by #14095.
