### ISSUE TITLE
IntelliJ IDEA doesn't recognize classes generated from proto files in a Gradle project

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#13882]
**Describe the bug**
IntelliJ IDEA doesn't recognize classes generated from proto files in a Gradle project.

**Expected behavior**
Quarkus gRPC plugin should update IDEAs source sets so that it could see the generated classes automatically (for instance, like the protobuf-gradle-plugin [does it](https://github.com/google/protobuf-gradle-plugin/blob/bf6301ac28c22c78eb930c7f249ebbb7f691b5aa/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L540)).

**Actual behavior**
IntelliJ IDEA doesn't recognize classes generated from proto files in a Gradle project.

**To Reproduce**

1. Generate a Qurkus Gradle project with the `'io.quarkus:quarkus-grpc'` dependency.
2. Add a valid proto file definfing a gRPC service into `src/main/proto`.
3. Build the project and check that the code has been generated to `build/classes/java/quarkus-generated-sources/grpc`.
4. Add a Java class with an import of a class from the generated sources.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: `1.10.3.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Gradle 6.5.1

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Mac OS X 10.16 x86_64
```

**Additional context**
The work around is to manually specify an additional source set in Gradle:
```
sourceSets {
    main {
        java {
            srcDirs 'build/classes/java/quarkus-generated-sources/grpc'
        }
    }
}
```
But I tried many things and wasted a lot of time until I found how to fix it. It is important to have a ready-to-run project after project generation.

**Comment by glefloch** [comment]
Is it a kotlin project? I have a fix that register the generated output to the gradle compile task. 
I'm looking at removing the sub directory in the generated folder.

**Comment by Shpota** [comment]
@glefloch the issue exists in both Java and Kotlin projects.

**Comment by galiagacandia** [comment]
In intellij idea it is necessary to perform the following configuration

![image](https://user-images.githubusercontent.com/6887394/142708407-db2dcc65-39c0-4c9b-b695-e655b2a83878.png)

![image](https://user-images.githubusercontent.com/6887394/142708419-2f86530f-751e-4ecc-b3b4-f3700c72b86f.png)

![image](https://user-images.githubusercontent.com/6887394/142708425-f20bfe9c-d558-42e7-8c4c-b5f9701236d8.png)

I hope this helps.

**Comment by michalszynkiewicz** [comment]
Isn't it enough to reload the project? That's how it works with maven projects, IntelliJ doesn't pick up new folders of generated sources until the project is reloaded

**Comment by geoand** [comment]
Closing as we never got feedback

**Comment by alanLJ** [comment]
> In intellij idea it is necessary to perform the following configuration
> 
> ![image](https://user-images.githubusercontent.com/6887394/142708407-db2dcc65-39c0-4c9b-b695-e655b2a83878.png)
> 
> ![image](https://user-images.githubusercontent.com/6887394/142708419-2f86530f-751e-4ecc-b3b4-f3700c72b86f.png)
> 
> ![image](https://user-images.githubusercontent.com/6887394/142708425-f20bfe9c-d558-42e7-8c4c-b5f9701236d8.png)
> 
> I hope this helps.

That's so great.
