### ISSUE TITLE
Instantiate new Redis client

### ISSUE THREAD

**Issue by omarkad2** [quarkusio/quarkus#13887]
**Description**
When using the same redis client for subscription / publishing we get this error:
 `ERR Can't execute 'client': only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT are allowed in this context`.

This is the expected behavior, since as mentioned in Redis documentation, we must use different clients. However in `quarkus-redis-client` no API expose a factory method that allows us creating a new instance of the client nor we can inject the client instance bean with a prototype scope (like in Spring) that will return a different instance every time it is injected.

Do we have a known workaround for this ? or we should add a factory method to instantiate different Redis clients when needed ?

**Comment by zrlurb** [comment]
you could add in the application.properties file (e.g)
```
%prod.quarkus.redis.hosts=redis://dashboard-redis.projection.svc:6379
%dev.quarkus.redis.hosts=redis://localhost:6379

%prod.quarkus.redis.second.hosts=redis://localhost:6379
%dev.quarkus.redis.second.hosts=redis://localhost:6379

```

and used it like :
```
  @Inject
  RedisClient redisClient;

  @Inject
  ReactiveRedisClient reactiveRedisClient;

  @Inject
  @RedisClientName("second")
  RedisClient redisClient2;

  @Inject
  @RedisClientName("second")
  ReactiveRedisClient reactiveRedisClient2;
  ```

**Comment by zrlurb** [comment]
@omarkad2 Do you have a sample about subscription / publishing  in quarkus ?

**Comment by omarkad2** [comment]
thanks @zrlurb it works for me, I didn't pay attention but this was already mentioned in documentation.

I created a small project to showcase a redis pub/sub using quarkus https://github.com/omarkad2/quarkus-redis-example.

I noticed that there is no API in the quarkus's extension `quarkus-redis-client` allowing to define subscriber handlers, so I end up using vertx for this.
But I keep getting this warning in my logs each time I run the project:
`2020-12-16 21:02:19,990 WARNING [io.ver.red.cli.imp.RedisConnectionImpl] (vert.x-eventloop-thread-1) No handler waiting for message: [subscribe, timestamp, 1] I don't know if you have already encountered this ?
`

**Comment by zrlurb** [comment]
thanks @omarkad2 
I have the WARNING too. :-(

by the way, I have done following:
```
  @GET
  @Produces(MediaType.SERVER_SENT_EVENTS)
  @SseElementType(MediaType.TEXT_PLAIN)
  @Path("/redis/subscribe")
  public Publisher<String> firstredis(){
       return eventBus.<String>consumer("io.vertx.redis.message-channel").toPublisherBuilder()
        .map(Message::body)
 }
 ```
 this works well with Sse, but if I have open more than one browser, it receives the message in one browser only. So it does not Subscribe/Publish to all consumers. It serves the message round-robin to one of the open See connection.
 Do you have any suggestions ?

**Comment by cristian-com** [comment]
> thanks @zrlurb it works for me, I didn't pay attention but this was already mentioned in documentation.
> 
> I created a small project to showcase a redis pub/sub using quarkus https://github.com/omarkad2/quarkus-redis-example.
> 
> I noticed that there is no API in the quarkus's extension `quarkus-redis-client` allowing to define subscriber handlers, so I ended up using vertx to register my handlers.
> But I keep getting this warning in my logs each time I run the project:
> `2020-12-16 21:02:19,990 WARNING [io.ver.red.cli.imp.RedisConnectionImpl] (vert.x-eventloop-thread-1) No handler waiting for message: [subscribe, timestamp, 1] I don't know if you have already encountered this ? `

Hey, I've been playing with the library a bit. I will check better how to define such handler. Just wanted to let you know I opened this issue https://github.com/vert-x3/vertx-redis-client/issues/291 regarding the warning message you mentioned. 

Only messages are being sent directly to the event bus, other kinds are not handled by default from what I can see

**Comment by machi1990** [comment]
> we should add a factory method to instantiate different Redis clients when needed ?

+1 on this. I'll prepare a PR to enrich the interface with factory methods.

```java
public interface RedisClient {
    /**
     * Creates the {@link RedisClient} using the default redis client configuration
     * @return {@link RedisClient}
     */
    public static RedisClient createDefaultClient() {...}

    /**
     * Creates the {@link RedisClient} using the named redis client configuration
     * @return {@link RedisClient}
     */
    public static RedisClient createClient(String name){...};


   // .... other methods
}
```

```java
public interface ReactiveRedisClient {
    /**
     * Creates the {@link ReactiveRedisClient} using the default redis client configuration
     * @return {@link ReactiveRedisClient}
     */
    public static ReactiveRedisClient createDefaultClient() {...}

    /**
     * Creates the {@link ReactiveRedisClient} using the named redis client configuration
     * @return {@link ReactiveRedisClient}
     */
    public static ReactiveRedisClient createClient(String name){...};


   // .... other methods
}

```

> thanks, @omarkad2
> I have the WARNING too. :-(
> 
> by the way, I have done following:
> 
> ```
>   @GET
>   @Produces(MediaType.SERVER_SENT_EVENTS)
>   @SseElementType(MediaType.TEXT_PLAIN)
>   @Path("/redis/subscribe")
>   public Multi<String> firstredis() {
>     return Multi.createFrom()
>         .publisher(eventBus.<String>consumer("io.vertx.redis.message-channel").toMulti()
>             .map(msg -> String.format("%s", msg.body())));
> 
>   }
> ```
> 
> This works well with Sse, but if I have open more than one browser, it receives the message in one browser only. So it does not Subscribe/Publish to all consumers. It serves the message round-robin to one of the open Sse connection.

Correct. This is coming from the fact that the underlying handler will `send` the received response to the eventBus and not publish it.

> Do you have any suggestions?

My suggestion would be to implement a custom handler (on a `ReactiveRedisClient`) that will publish to the event bus on a different channel. This way several consumers will receive a copy of the response.  On your rest resource, you will consume from the that channel.
