### ISSUE TITLE
Expose kafka-client in extensions.json

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1388]
I refrained from doing so, thinking it was more like a low level library but it probably makes sense to expose it as we expose the JDBC drivers.

See the thread [quarkus-dev] Help me debugging a native image creation with Kafka Client on quarkus-dev.

**Comment by machi1990** [comment]
I am not able to see the thread in question on Zulipchat.  But this looks like a good-first issue: it involves adding kafka-client in `extensions.json`, while respecting the alphabetical order? If so I can submit a PR for this right away. 

Other than `kafka-client` what other labels do we assign to this extension?
