### ISSUE TITLE
Some URLs without HTTPS

### ISSUE THREAD

**Issue by LuccaPrado** [quarkusio/quarkus#13888]
**Description**
I've noticed that some urls on quarkus, like apache license 2.0, w3.org xml schema and liquibase schema definitions (and others may be too) are still using http instead of https. 

**Implementation ideas**
Change the http urls to https when exists and its possible.

**Comment by geoand** [comment]
Hi!

Would you like to provide a Pull Request addressing this issue?

**Comment by LuccaPrado** [comment]
I'll create a PR with that today!

**Comment by LuccaPrado** [comment]
@geoand  I just don't know if on xml xmls this could be a problem. (as I don't understand the use of this url on it).

For example on file:
https://github.com/quarkusio/quarkus/blob/b27b4cc998bff4709bc09fd3aa0e752e1a6002f2/build-parent/pom.xml
On line 2

**Comment by geoand** [comment]
I would leave those out TBH

**Comment by LuccaPrado** [comment]
I Guess that with my PR #13911 we can close this issue (as the other urls are in xmlNamespaces)

**Comment by geoand** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/13911
