### ISSUE TITLE
use package-private warning when using REST Data with Panache

### ISSUE THREAD

**Issue by eliaharm** [quarkusio/quarkus#13895]
**Describe the bug**
compiler warning:
```
INFO  [io.qua.arc.pro.BeanProcessor] (build-6) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field org.acme.autorest.CountriesResourceJaxRs_0fccf8a7cc91a16f62fff01e3dbc87f01f43565c#resource,
        - @Inject field org.acme.autorest.ServiceCategoriesResourceJaxRs_9f5b7a023b47285e2816e5f41f317dc105ea194a#resource,
```
**Expected behavior**
No warnings

**Actual behavior**
Could not fix the code to remove warning given that no `private` members were declared in class `CountriesResource`...

**To Reproduce**

pom.xml
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-rest-data-panache</artifactId>
    </dependency>
```
CountriesResource.java
```
package org.acme.autorest;

import java.util.List;
import org.acme.jpa.*;
import io.quarkus.hibernate.orm.rest.data.panache.PanacheEntityResource;
import io.quarkus.panache.common.Page;
import io.quarkus.panache.common.Sort;
import io.quarkus.rest.data.panache.MethodProperties;
import io.quarkus.rest.data.panache.ResourceProperties;

@ResourceProperties(hal = false, path = "api/v1/countries", paged = false)
public interface CountriesResource extends PanacheEntityResource<TCountries, Integer> {

  @MethodProperties(path = "all")
  List<TCountries> list(Page page, Sort sort);

  @MethodProperties(exposed = true)
  boolean delete(Integer id);
}
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  MSYS_NT-10.0-18363 DESKTOP-B13A99G 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys
 - Output of `java -version`: 
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.3
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\elia\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 11.0.8, vendor: ojdkbuild, runtime: C:\Users\elia\scoop\apps\ojdkbuild11-full\current
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
(Add any other context about the problem here.)

**Comment by gytis** [comment]
@loicmathieu assign this to me, I'll fix it.

**Comment by loicmathieu** [comment]
@gytis it's all yours ;)

**Comment by gytis** [comment]
@loicmathieu this seems to have been fixed here https://github.com/quarkusio/quarkus/commit/94803d76174ac181ce79a0390f9896cff1645dff by George

**Comment by loicmathieu** [comment]
Yes, this has been fied by #14149, I'm closing it.
