### ISSUE TITLE
Fix the guides which use `className` when generating the project

### ISSUE THREAD

**Issue by meistermeier** [quarkusio/quarkus#13917]
**Describe the bug**
When creating a new project with the `resteasy-jackson` extension, it will create its default classes no matter if I provide a `className` or not.
Also the tests are missing but I assume that this is a result of the extension doing something wrong.
Following documentation in the getting started guides right now is not possible if the `resteasy-jackson` extension is involved in the creation process.

**Expected behavior**
Respect the `className` definition.

**Actual behavior**
(Part of the reproduce section)

**To Reproduce**
Create a project
Note: I added also the Neo4j extension to have something to compare with.
```
mvn io.quarkus:quarkus-maven-plugin:1.10.3.Final:create \                    
    -DprojectGroupId=com.meistermeier.neo4j \
    -DprojectArtifactId=rest-neo4j-quarkus \
    -DclassName="com.meistermeier.neo4j.MovieResource" \
    -Dextensions="neo4j, resteasy-jackson"
```
creates
```
➜  rest-neo4j-quarkus tree
.
├── README.md
├── mvnw
├── mvnw.cmd
├── pom.xml
└── src
    └── main
        ├── docker
        │   ├── Dockerfile.fast-jar
        │   ├── Dockerfile.jvm
        │   └── Dockerfile.native
        ├── java
        │   └── com
        │       └── meistermeier
        │           └── neo4j
        │               └── resteasyjackson
        │                   ├── JacksonResource.java
        │                   └── MyObjectMapperCustomizer.java
        └── resources
            ├── META-INF
            │   └── resources
            │       └── index.html
            └── application.properties

11 directories, 11 files
```

whereas
```
mvn io.quarkus:quarkus-maven-plugin:1.10.3.Final:create \
    -DprojectGroupId=com.meistermeier.neo4j \
    -DprojectArtifactId=neo4j-quarkus \ 
    -DclassName="com.meistermeier.neo4j.MovieResource" \
    -Dextensions="neo4j"
```
creates
```
.
├── README.md
├── mvnw
├── mvnw.cmd
├── pom.xml
└── src
    ├── main
    │   ├── docker
    │   │   ├── Dockerfile.fast-jar
    │   │   ├── Dockerfile.jvm
    │   │   └── Dockerfile.native
    │   ├── java
    │   │   └── com
    │   │       └── meistermeier
    │   │           └── neo4j
    │   │               └── MovieResource.java
    │   └── resources
    │       ├── META-INF
    │       │   └── resources
    │       │       └── index.html
    │       └── application.properties
    └── test
        └── java
            └── com
                └── meistermeier
                    └── neo4j
                        ├── MovieResourceTest.java
                        └── NativeMovieResourceIT.java

15 directories, 12 files
```
Adding the extension later with `./mvnw quarkus:add-extension -Dextensions="resteasy-jackson"` works fine (maybe obvious but I wanted to mention this)

**Environment (please complete the following information):**
 - Output of `java -version`: 11 / 15

**Comment by ia3andy** [comment]
@gsmet This option is @deprecated in favor of packageName: 

```
     * This parameter is only working with the RESTEasy and Spring Web extensions and is going to be removed.
     * Use packageName instead.
```
https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java#L115

When using `className` you still get the `packageName` extracted from it, but the class name part is ignored.

The reason behing is that as soon as you pick more than one extension with example code, this `className` is not making sense anymore (and would break the generated app) while `packageName` can work anyway.

Note: It still works with `resteasy` OR `spring-web` to keep the same level of functionality as we had before.

**Comment by ia3andy** [comment]
Also, it's working without `resteasy-jackson` because then you get the `resteasy` example by default..

**Comment by meistermeier** [comment]
Thanks for the clarification. But the problem that `resteasy-jackson` is referred in some guides (e.g. neo4j, mongodb, restclient...) and they tell to open and edit the resource created with the `className` option, is still a problem, right?

**Comment by ia3andy** [comment]
@meistermeier right, then this is a bug indeed, sorry I missed that, we should update the guides for sure!

**Comment by ia3andy** [comment]
I am hesitating between a few solutions:
1. changing the logic so that when `className` is used (and spring-web is not selected), we automatically add the resteasy example. It would fix all the guides but would make the behavior inconsistent.
2. updating all the guides which already provide example code in the extension set to be consistent with the new example code
3. having a new `--examples=resteasy` option to specify the examples to use and udpate all the guides which need it..

**Comment by ia3andy** [comment]
We decided on a fix: https://github.com/quarkusio/quarkus/issues/14391
