### ISSUE TITLE
Managed JAX-RS @Provider beans are not being registered in Resteasy

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1392]
The getConverter method is never called when having a managed bean as defined below:

```java
@Provider
@ApplicationScoped
public class DependencyParamConverterProvider implements ParamConverterProvider {

    @Inject
    DependencyParamConverter dependencyParamConverter;

    @Override
    @SuppressWarnings("unchecked")
    public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {
        // THIS IS NEVER CALLED
        if (rawType == Dependency.class) {
            return (ParamConverter<T>) dependencyParamConverter;
        }
        return null;
    }
}
```

**Comment by gastaldi** [comment]
It looks like it only happens when you have an injected field:
```java 
    @Inject
    DependencyParamConverter dependencyParamConverter;
```

If I remove the `@Inject` annotation, the converter is called

**Comment by r-uu** [comment]
What might be reasons why the ```getConverter(...)``` method never gets called? I have the code below and I can see that the provider instance (and it's static members) is created. Do I have to use a special scope for ```ConverterProvider```? Or do I have to register it somewhere? BTW: I'm using Jsonb, not Jackson.
```
@Provider
public class ConverterProvider implements ParamConverterProvider
{
	private final static TagGroupConverter TAG_GROUP_CONVERTER = new TagGroupConverter();
	private final static TagConverter      TAG_CONVERTER       = new TagConverter();
	private final static DocumentConverter DOCUMENT_CONVERTER  = new DocumentConverter();

	@SuppressWarnings("unchecked")
	@Override
	public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations)
	{
		// THIS IS NEVER CALLED
		if (rawType.getName().equals(TagGroup.class.getName()))
		{
			return (ParamConverter<T>) TAG_GROUP_CONVERTER;
		}
		if (rawType.getName().equals(Tag.class.getName()))
		{
			return (ParamConverter<T>) TAG_CONVERTER;
		}
		if (rawType.getName().equals(Document.class.getName()))
		{
			return (ParamConverter<T>) DOCUMENT_CONVERTER;
		}

		throw new UnsupportedOperationException("unexpected raw type " + rawType.getName());
	}
}```

**Comment by gastaldi** [comment]
You need to add `@ApplicationScoped` to your provider

**Comment by r-uu** [comment]
I added ApplicationScoped but it does not change the behaviour - still no calls to getConverter(). So there must be something else. Do you have any idea? Any need to configure something? Maybe an annotation somewhere?

One thing: the Converters, the ConverterProvider and the types to be converted live in their own maven module which is imported via maven dependency into the "server" module. Could that cause any problems?

**Comment by gastaldi** [comment]
Have you tried to add an empty `META-INF/beans.xml` to your maven module?

**Comment by r-uu** [comment]
Yes, empty ```META-INF/beans.xml``` everywhere, in the importing and in the imported module.

I stumbled upon ```JsonbConfigCustomizer```. I made an implemention and annotated it as singleton. Quarkus at least calls it's ```customize(...)``` method. Is there a way to register Converters or ConverterProvider implementations there?

**Comment by r-uu** [comment]
I think I misunderstood something. I thought that ```ParamConverter```s were also used for request / response message bodies. I actually do not use parameters but message bodies. So it is no surprise that a ```ParamConverter``` is never requested from my provider. No need for further investigation / help regarding this. Sorry. Thank you.
