### ISSUE TITLE
dev mode logging is not configurable

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1393]
Logging for quarkus:dev mode is not configurable. Users should be able to define logging configuration via application.properties files

**Comment by dmlloyd** [comment]
Specifically `application.properties` I think.

**Comment by johnaohara** [comment]
I didn't know if we needed to support both application.properties and META-INF/microprofile-config.properties?

**Comment by dmlloyd** [comment]
It'll happen automatically because we use the default sources as well.  But when you say "via `.properties` files" I'm thinking `logging.properties`.

**Comment by johnaohara** [comment]
I have updated the description

**Comment by rsvoboda** [comment]
In dev mode I would like to configure DEBUG logging level for some categories.

Maybe some people would like to see DEBUG as default level for dev mode.
