### ISSUE TITLE
Openapi - HV Constraints on lists are generated as allof

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#13937]
**Describe the bug**
I have a list field in my rest models, that is annotated with hv constraints. In the generated openapi, I get an allof with 2 elements. First element is a ref to the object, in the other element the hv constraints are present.

This only affects list fields, not simple String fields for example.

**Expected behavior**
```
Person:
       required:
      - addresses
      type: object
      properties:
        addresses:
          $ref: '#/components/schemas/ListAddress'
          maxItems: 2
          minItems: 1
          nullable: false
```

**Actual behavior**
```
Person:
      required:
      - addresses
      type: object
      properties:
        addresses:
          allOf:
          - $ref: '#/components/schemas/ListAddress'
          - maxItems: 2
            minItems: 1
            nullable: false
```

**To Reproduce**

1. Download the reproducer: [openapi-hv-allof.zip](https://github.com/quarkusio/quarkus/files/5707985/openapi-hv-allof.zip)
2. mvn quarkus:dev
3. http://localhost:8080/openapi
4. Look at the Person object, it has allof

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Quarkus version or git rev: 
 - 1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\zulu11.39.15-ca-jdk11.0.7-win_x64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by MikeEdgar** [comment]
@Postremus - `$ref` is an exclusive property. If you want to have a schema include the attributes of `#/components/schemas/ListAddress` along with the other three you listed, the `allOf` is required. Please see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#referenceObject

**Comment by Postremus** [comment]
@MikeEdgar 

I looked a  bit further where my sudden problems in quarkus 1.10.3.Final with openapi came from.
During migration, I also removed following setting because I thought that it was not needed anymore:
```
mp.openapi.scan.exclude.packages=java.util
```

If I add it to the reproducer, I get way better output:
```
Person:
      required:
      - addresses
      type: object
      properties:
        addresses:
          maxItems: 2
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Address'
          nullable: false`
```
Notice that it is now just an `Address`, and not an `ListAddress`.

According to https://github.com/quarkusio/quarkus/issues/7238 this setting is not needed anymore.

**Comment by MikeEdgar** [comment]
@Postremus , it's still needed, but the new property here https://github.com/smallrye/smallrye-open-api/pull/524 is a better choice. The default value might change in a future release.

**Comment by Postremus** [comment]
I am using the new property now, works perfectly. Thank you!
