### ISSUE TITLE
 Authorization request header not generated in api documentation 

### ISSUE THREAD

**Issue by emiste** [quarkusio/quarkus#13940]
**Describe the bug**
 Authorization request header not generated in api documentation. If other word used, such as "Auth" for example the text input field is well generated.

**Expected behavior**
Get a text input field for header named "Authorization"

**Actual behavior**
The text input field is not generated in api documentation

**To Reproduce**

[openapiTest.zip](https://github.com/quarkusio/quarkus/files/5708293/openapiTest.zip)

1. ./mvnw compile quarkus:dev
2. http://localhost:8080/swagger-ui
3. check documentation for http://localhost:8080/swagger-ui/#/default/get_resteasy_jackson_quarks  ==> **input text not generated**
4. check documentation for http://localhost:8080/swagger-ui/#/default/post_resteasy_jackson_quarks ==> **input text is well generated**

**Comment by MikeEdgar** [comment]
Hi @emiste - this is expected if you are using `@HeaderParam` (JAX-RS) or `@Parameter` from Microprofile. 

The MP specification states that certain headers are to be ignored: https://download.eclipse.org/microprofile/microprofile-open-api-1.1.2/apidocs/org/eclipse/microprofile/openapi/annotations/parameters/Parameter.html#name--.

This is in alignment with the OpenAPI specification as well: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10

Developers should use the security-related annotations/properties to document the application's authorization/authentication requirements.

**Comment by emiste** [comment]
Thank you @MikeEdgar  for the clarifications
