### ISSUE TITLE
Panache: deleteAll not deleting child entities when using cascade ALL or REMOVE

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#13941]
**Describe the bug**
When calling the deleteAll function to delete all the entities. It's expected to delete also the child entities if it has been configured to use cascade ALL or REMOVE:

```java
@Entity(name = "application")
public class ApplicationEntity extends PanacheEntity {
    // ...

    @OneToMany(mappedBy = "application", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    public List<ServiceEntity> services = new ArrayList<>();
```

Delete all method usage:

```java
ApplicationEntity.deleteAll();
```

This works fine if we delete the entity individually:

```java
ApplicationEntity.findById(actualEntityId).delete();
```

**Expected behavior**
Delete one item and delete all should behave the same, so both methods should delete the child entities if cascade is properly configured.

**Actual behavior**
DeleteAll method is not deleting child entities even though the cascade is properly configured.

**To Reproduce**
You can run [this test](https://github.com/Sgitario/beefy-scenarios/blob/916b397def22313707a439d892ecbd3a2e7bd6d7/011-quarkus-panache-rest-flyway/src/test/java/io/quarkus/qe/ApplicationEntityTest.java#L29) as a reproducer. 
The test is failing and it should pass.

**Environment (please complete the following information):**
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by FroMage** [comment]
I'm not sure `deleteAll` makes such guarantees. I remember @gavinking and @Sanne talking about this recently, but I can't recall their opinion?

**Comment by gavinking** [comment]
I imagine that `deleteAll()` is using a bulk `delete` query, and it's quite normal for cascade delete to be ignored in that case. Indeed, it is would be terribly inefficient to delete parents and children using N+1 delete statements. (That's the really bad implementation we already noticed Spring using somewhere, and we definitely shouldn't do the same thing here.)

Now, in principle you could make it work by issuing two bulk delete queries but that's not functionality that JPA or Hibernate have ever provided, and if it's needed it would probably be better to implement it in Hibernate, not in Panache. OTOH, in 20 years I've never noticed that this was something users really ask for.

**Comment by Sanne** [comment]
Right; personally I'm not a big fan of the "cascade" semantics as defined on the JPA spec, but that's what we're stuck with.

Ideally I think such cascading rules from the model should be applied as DDL table options: far more efficient and less cumbersome to deal with.
But Hibernate ORM isn't really meant as a tool to define all advanced aspects of DDL generation, people should hopefully manage their schema with other means.

**Comment by FroMage** [comment]
Fair enough. So in that case I advise that you "override" the `ApplicationEntity.deleteAll()` static method for your special use-case.

**Comment by FroMage** [comment]
Now, as to whether Hibernate ORM provides an operation for that that doesn't require loading the entities, or if there's a plain SQL alternative that does it, I'm not really sure.

**Comment by Sanne** [comment]
> Fair enough. So in that case I advise that you "override" the `ApplicationEntity.deleteAll()` static method for your special use-case.

Or edit the schema so to have the DB deal with it.

**Comment by Sgitario** [comment]
Taking into account the developer experience, users would expect that deleteAll method behaves as the delete method. In fact, as you said above, in Spring Data, It's working like this. 
However, I agree with you about this is not something users usually do or ask for. More if this is something really complex to do. Therefore, maybe a simple note in the documentation to state that the cascade rules are not in consideration when calling to the deleteAll would suffice. What do you think?

**Comment by gavinking** [comment]
You should pretty much *never* use Spring's `deleteAll()`, since it is a performance bug.

**Comment by gavinking** [comment]
I mean, "avoid N+1 queries" is one of the most basic axioms of data access.

**Comment by FroMage** [comment]
If this table is the only table using `ServiceEntity` you can trivially do:

```java
public class ApplicationEntity extends PanacheEntity {
// ...
  public static void deleteAll(){
    // this is basically super.deleteAll()
    JpaOperations.INSTANCE.deleteAll(ApplicationEntity.class);
    ServiceEntity.deleteAll();
  }
}
```

**Comment by gavinking** [comment]
> Right; personally I'm not a big fan of the "cascade" semantics as defined on the JPA spec, but that's what we're stuck with.

Well, that would be my fault, since they're copied directly from Hibernate 2. ;-)

But yeah, Ive never been terribly sure that this stuff is totally the right thing either.

**Comment by gavinking** [comment]
> Ideally I think such cascading rules from the model should be applied as DDL table options: far more efficient and less cumbersome to deal with.

The issue with that approach is keeping the second-level cache in sync.

**Comment by gavinking** [comment]
>  maybe a simple note in the documentation to state that the cascade rules are not in consideration 

`deleteAll()` is a framework-defined method with Javadoc, no, @FroMage?

**Comment by Sanne** [comment]
> > Ideally I think such cascading rules from the model should be applied as DDL table options: far more efficient and less cumbersome to deal with.
> 
> The issue with that approach is keeping the second-level cache in sync.

Good point; I wonder if one could still fire the right eviction events, but omit the SQL statements. It would certainly require ORM to _know_ about the DDL structure (which we don't) and be able to rely on it.

**Comment by FroMage** [comment]
> deleteAll() is a framework-defined method with Javadoc, no, @FroMage?

Yes, we could improve the javadoc.

**Comment by gavinking** [comment]
@Sanne well for delete everything it could be made to work. But when the delete statement has a where clause I think we're screwed. Which is why we don't have this feature.

**Comment by hprange** [comment]
> Premature optimization is the root of all evil.

When I first reported this issue to the mailing list, I was trying to use the `deleteAll` method to clear the database after running each test. This is a very common use case for this method. And performance isn't relevant in this scenario.

IMHO, the way it is, the current implementation also violates the principle of least surprise. I expect the `deleteAll` method to behave indistinguishably from the `delete` method, but for all records.

So, if cascading is not expected to occur when calling the `deleteAll` method, can you consider changing the method name to something less ambiguous?

**Comment by gavinking** [comment]
Counterpoint: when I first learned the semantics of `deleteAll()` on Spring, I wasn't merely _suprised_, I was shocked that they would have implemented something so crap. So "least surprise" can be a pretty misleading principle. We're surprised by things we're not used to: you're used to Spring, and I'm used to data access code that isn't crap 🤷‍♂️😆

**Comment by gavinking** [comment]
Anyway, the conclusion is that there's actually a really good reason that Hibernate itself doesn't have cascading bulk deletes or a `deleteAll()` operation: the reason is that all the obvious ways to implement it are actually really bad, and to do it right would require a pretty weird and tricky implementation involving multiple `select` and `delete` queries. Perhaps someday we could do a really correct implementation of that, but it seems to have never come up as a priority in 20 years. Sometimes it's better to simply not have a feature than to have a bad implementation of the feature.

**Comment by gavinking** [comment]
@Sanne a crazy thought that just occurred to me is that the only actual usecase we have for this thing is cleaning up after tests. And I thought, well, I never have this need because I use schema export for that. But then I remembered that schema export is really slow on DB2. So what I would really like is for schema export to be able to delete instead of drop tables. FK constraints are a potential problem with that idea, however.

**Comment by FroMage** [comment]
Perhaps all we need is a `DB.deleteAll()` then?

**Comment by hprange** [comment]
> We're surprised by things we're not used to: you're used to Spring, and I'm used to data access code that isn't crap 🤷‍♂️😆

In the end, does it matter if the code is well-written and performant if it doesn't work? 😉 BTW, I have no experience with Spring whatsoever. So, I'm not biased because of it.

> Sometimes it's better to simply not have a feature than to have a bad implementation of the feature.

I agree. In the absence of a better solution,  maybe removing the `deleteAll` method is the way to go. It could have saved me a few hours of debugging.

As a matter of fact, a colleague reported the same issue yesterday. And when this kind of error happens, our first thought is: "what have I done wrong in my entity configuration"? So, you spend a few hours until you realize the `deleteAll` doesn't cascade. We had that lesson learned. How many developers will have to go through the same experience?

> a crazy thought that just occurred to me is that the only actual usecase we have for this thing is cleaning up after tests. 

Not crazy at all. I can't recall having to recur to the `deleleAll` method in production code from my experience. At least not on purpose. 😅 I've resorted to it in test cases multiples times, though, especially considering Quarkus applications testing nature.

> Perhaps all we need is a DB.deleteAll() then?

Sounds like a plan.

Thank you, @gavinking and @FroMage, for taking the time to look into this matter. I'd be glad to provide a pull request regardless of the chosen solution. I just need some guidance. 😀

**Comment by gavinking** [comment]
> Perhaps all we need is a `DB.deleteAll()` then?

Yeah that would be perfect it seems to me.

**Comment by FroMage** [comment]
Well we can start with improving the javadoc to inform that it doesn't do cascade, that's an easy enough PR :)

We can also add this to the documentation and suggest the alternative code I showed above. Again an easy PR :)

**Comment by FroMage** [comment]
> Yeah that would be perfect it seems to me.

Is there a way to do this with runtime ORM metadata or do I generate bytecode that knows about all the `PanacheEntity` to call `deleteAll()` on each?

**Comment by gavinking** [comment]
> BTW, I have no experience with Spring whatsoever. So, I'm not biased because of it.

No worries I was just trying to be funny.

> In the absence of a better solution, maybe removing the `deleteAll` method is the way to go. It could have saved me a few hours of debugging.

Yeah well that's what I was trying to hint at.
 
> As a matter of fact, a colleague reported the same issue yesterday. And when this kind of error happens, our first thought is: "what have I done wrong in my entity configuration"? So, you spend a few hours until you realize the `deleteAll` doesn't cascade. We had that lesson learned. How many developers will have to go through the same experience?

Right. This is exactly how I feel about this thing. It can be worse to have crappy implementation than to have no implementation. In the end you just waste the user's time and your own time.


> Not crazy at all. I can't recall having to recur to the `deleleAll` method in production code from my experience.

Nope. I don't think it's normal. At least not for OLTP-type applications.

**Comment by gavinking** [comment]
> > Yeah that would be perfect it seems to me.
> 
> Is there a way to do this with runtime ORM metadata or do I generate bytecode that knows about all the `PanacheEntity` to call `deleteAll()` on each?

There is but the big issue is getting the order right to not violate FK constraints.

**Comment by Sanne** [comment]
+1 to remove the method, I'm not convinced that such helpers belong in Panache.

**Comment by FroMage** [comment]
I think the method is fine, and its variant which takes a _where_ clause is useful for prod and has the same issue anyway. But it works when you don't have relations, or when you manage cascades yourself. There are in fact a lot of use-cases where it just works. I think documenting this properly in the javadoc would fix most misconceptions.

**Comment by FroMage** [comment]
> There is but the big issue is getting the order right to not violate FK constraints.

Why would these even kick in if it's called in a transaction?

**Comment by gavinking** [comment]
> > There is but the big issue is getting the order right to not violate FK constraints.
> 
> Why would these even kick in if it's called in a transaction?

This behavior is very platform-dependent. In Postgres, by default, FK constraints are checked on every statement, though it is possible to set things up so that constraint checking is deferred to the end of the tx. IIRC MySQL is different but similar.

**Comment by gavinking** [comment]
>  IIRC MySQL is different but similar.

I did recall correctly. By default they're checked immediately, but you can disable them completely using a variable.

**Comment by hprange** [comment]
@FroMage I've opened pull request #14205. It adds a warning message to the Javadoc of the `deleteAll` and `delete` with where clause methods, stating that cascade delete rules are ignored. Please, let me know if you need any changes or if I can contribute with anything else.

**Comment by Sgitario** [comment]
> @FroMage I've opened pull request #14205. It adds a warning message to the Javadoc of the `deleteAll` and `delete` with where clause methods, stating that cascade delete rules are ignored. Please, let me know if you need any changes or if I can contribute with anything else.

I've commented the PR with: https://github.com/quarkusio/quarkus/pull/14205#pullrequestreview-565116397

**Comment by tomperr** [comment]
Should we close this issue as the problem has been explained and documented, or do we still consider that `deleteAll` should delete child entities?

**Comment by Sgitario** [comment]
Moreover, taking into account that there hasn't had much activity here either, perhaps not many users are impacted, so I'm fine with closing this issue after having documented the `deleteAll` behavior.
