### ISSUE TITLE
All integration tests using Hibernate Reactive need to move to RESTEasy Reactive

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#13944]
**Description**
Several integration tests are using a combination RESTEasy (old-blocking) with Hibernate Reactive.

This results in racy callback executions and will soon be made illegal by new assertions I'm introducing in Hibernate Reactive, so we need to move to RESTEasy Reactive for all such integration tests.

**Comment by geoand** [comment]
I think this makes a lot of sense

**Comment by FroMage** [comment]
Well, does it? Isn't HR supposed to also work on blocking models? Is that a new limitation? I guess it's related to our discussion from the other day, but I didn't understand we'd disallow running HR on a non-vertx thread.

**Comment by Sanne** [comment]
> Well, does it? Isn't HR supposed to also work on blocking models? Is that a new limitation? I guess it's related to our discussion from the other day, but I didn't understand we'd disallow running HR on a non-vertx thread.

I don't think HR can work on a blocking thread. It needs to run on the vertx eventloop so that callbacks to its operation are applied within the same thread.

See my just-sent email as well...

Happy to be shown wrong, but even if we figure out a way to make it work safely, I don't think it's going to be simple.

**Comment by geoand** [comment]
Regardless if it is a technical necessity or not, to me it makes sense to push users of HR (which is itself something very new), to RR in order to get the complete Reactive stack.

**Comment by stuartwdouglas** [comment]
If HR needs to do work on an event loop thread then IMHO it should just dispatch to the correct thread internally.

**Comment by Sanne** [comment]
We do internally dispatch operations that need to happen on the DB during bootstrap, such as scheme generation / validation; so (since yesterday) we can bootstrap HR from whatever thread.

But beyond bootstrap, it gets really tricky to get right? The application code and the internal PU state do exchange data to/from database/application by passing state via the mapped entities. I can't require all entities be threadsafe?

Perhaps I'm confused?

**Comment by stuartwdouglas** [comment]
Whenever you are doing a reactive operation won't there be a
callback/CS/Uni involved? and if so then when the operation is submitted
from the wrong thread you just return the Uni, dispatch to the correct
thread, and have the correct thread do the work that causes the Uni to
complete?

Stuart

**Comment by Sanne** [comment]
Yes we might be able to dispatch the operation, when the whole transaction is expressed as a lambda - but still there are other patterns that will require restrictions.

For example, we can allow this use as we can dispatch the whole context on the right thread:

    factory.withTransaction(
        // persist the Authors with their Books in a transaction
        (session, tx) -> session.persistAll(author1, author2)
    )

This is equally ok:

    factory.withSession(
        // retrieve a Book
        session -> session.find(Book.class, book1.getId())
        // print its title
	.invoke( book -> out.println(book.getTitle() + " is a great book!") )
    )

But we can't allow people to return a xSession and then run operations on it, so `factory.openSession()` and `factory.openStatelessSession()` need either to throw an exception when detecting the wrong thread, or we remove the methods.

Summary:

- accessing SessionFactory is fine
- running some "within" a scoped Session or Transaction is fine as we can dispatch it
- returning a Session to the user's Thread is off-limits

@gavinking , @DavideD looking forwards to your opinion as well - I guess I should open a parallel issue on the HR project.

**Comment by stuartwdouglas** [comment]
Why is factory.openSession() a problem? It says that the connection is obtained lazily, so you would get a session, and then when you invoke on it the operation is dispatched to the IO thread.

**Comment by Sanne** [comment]
The problem is that any event which is waiting on a response (even just a confirmation) from the DB, will be executed on the event loop when the response is received - because the SQL Client isn't going to dispatch this back to your original thread.

Many of such continuations will need to make state change operations within the Persistence Unit, so I can't have it shared for concurrent access by the application thread in the meantime.

**Comment by Sanne** [comment]
Well I suppose we could wrap all operations on the SQL Client to "dispatch back" onto the original thread as first thing.. but isn't that quite horrible and defeating the whole point?

**Comment by gavinking** [comment]
@Sanne 

> I don't think HR can work on a blocking thread. It needs to run on the vertx eventloop so that callbacks to its operation are applied within the same thread.

Well, wait, are we sure that's right? I still think it *can* work on the blocking thread.

Note, I'm not against this change, but I do question whether we need to enforce it in all circumstances.

**Comment by gavinking** [comment]
> If HR needs to do work on an event loop thread then IMHO it should just dispatch to the correct thread internally.

Yes, and was working on that last night, and failed in my first attempt, but I *think* I know conceptually how to do it, but I'm going to need a little bit of extra help from @vietj.

**Comment by Sanne** [comment]
@gavinking yes I think you might be right, but it's damn hard to figure it all out. Could you please check out / join the discussion I just had with Stuart?
 - https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Hibernate.20Reactive

**Comment by Sanne** [comment]
The summary is I'm inclined to enable strong restrictions to begin with, and relax later if we figure a safe way - looking forward to your opinion.

**Comment by gavinking** [comment]
Well if we decide to merge https://github.com/hibernate/hibernate-reactive/pull/493, it might not matter?

**Comment by Sanne** [comment]
right it might not ne necessary, but I still prefer having the reactive tests using the fully reactive stack as that's how we intend this to be used.
Also, we need to explore some details still - I'm not 100% persuaded that we can delegate to the right thread in all circumstances.

**Comment by gavinking** [comment]
Yes I totally agree that our tests should run in the reactive stack. I was never trying to argue that point.

**Comment by gavinking** [comment]
And yeah. I'm still waiting for more feedback on that other PR. I'm not 100% sure about it either.
