### ISSUE TITLE
Some openshift container image combinations produce images that are not 3rd party tool friendly

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#13947]
**Describe the bug**
Some of our Openshift related container-image building options are not `oc new-app` friendly (or 3rd party tool friendly).

In some cases the jars end-up under `/deployments/target` instead of `/deployments` but the resulting image expect them in the latter directory. When the image paired with the manifests we create, this is no problem as our manifests contain the proper commands/arguments in order to properly start the application. That is not the case however when the image is used 

I think that this affects only s2i binary builds and all other combinations are working properly, but we do need to verify this.

**Expected behavior**
The resulting image should be runnable standalone without depending on the manifests to pass the correct artifact location.

**Actual behavior**
In some cases, the image entry point tries to start the app from `/deployments` but the artifacts are not there.

**Comment by geoand** [comment]
Is this still an issue or has it been addressed?
