### ISSUE TITLE
Upgrade to GraalVM CE 20.3

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#13954]
**Description**
GraalVM CE 20.3 was released in Nov 17 2020 and it would be nice to upgrade Quarkus to support this new release (which is also an LTS release).
However it looks like this is not possible and this issue aims to capture why.

**Current Status**
Despite efforts on resolving Quarkus issues with 20.3:
* https://github.com/quarkusio/quarkus/pull/13473
* https://github.com/quarkusio/quarkus/pull/13718
* https://github.com/quarkusio/quarkus/pull/12405
* https://github.com/quarkusio/quarkus/pull/12344

there is still an outstanding issues that we were not able to work around on the Quarkus side (see #13644). 

**Blocking issue**
In GraalVM 20.2 there was an issue with color profiles that was (partially) fixed in 20.3 through https://github.com/oracle/graal/commit/39d7ff72e9b02d24a333d176c9dc3166afabd6a3 by requiring `ColorSpace` and `ICC_Profile` classes to be reinitialized at runtime and by forbidding any instances of the said classes in the native image heap.

Unfortunately though to get an instance of `ICC_Profile` at runtime one typically invokes `getInstance` which ends up trying to load libawt at runtime 
(see https://github.com/quarkusio/quarkus/pull/13644#issuecomment-738892352) something that is not supported in 20.3.

The whole issue seems to be fixed in `master` through https://github.com/oracle/graal/commit/5d2997a9ac8cafdfc6b5c316532165839ad7d1af, which is expected to land in GraalVM 21.0 on January.

**Way forward**
At this point in time it looks like upgrading to 20.3 is not possible without reverting https://github.com/oracle/graal/commit/39d7ff72e9b02d24a333d176c9dc3166afabd6a3 or backporting of https://github.com/oracle/graal/commit/5d2997a9ac8cafdfc6b5c316532165839ad7d1af.

So unless one of the above gets done on the GraalVM side, moving to 20.3 will break tests and possibly use cases that used to embed `ColorSpace` and/or `ICC_Profile` instances in the native image heap.

**Comment by zakkak** [comment]
Upstream Graal issue: https://github.com/oracle/graal/issues/3077

**Comment by gastaldi** [comment]
Will GraalVM 20.3 fix any other outstanding issue in Quarkus? Otherwise I think it's safer to wait for 21.0 instead.

**Comment by zakkak** [comment]
> Will GraalVM 20.3 fix any other outstanding issue in Quarkus? Otherwise I think it's safer to wait for 21.0 instead.

No. However, GraalVM 20.3 is an LTS release, so it appears to be a better target than 21.0 (at least for now).
According to https://github.com/oracle/graal/issues/3077 the necessary changes to make Quarkus tests pass will be part of the 20.3.1 release.
