### ISSUE TITLE
gRPC Context propagation does not work

### ISSUE THREAD

**Issue by cihati** [quarkusio/quarkus#13959]
**Describe the bug**
If I have `ServerInterceptor` in which I set up some gRPC `Context` call a different service in a different thread, the `Context` isn't propagated.

**Expected behavior**
I expect to able to use `Context.current()` to have what I set in `ServerInterceptor`

**Actual behavior**
The `Context`s are different in different threads, and the `Context` I set in my grpc interceptor is no longer valid.

**To Reproduce**

1) Run the reproducer with `./mvnw quarkus:dev`
2) Run `grpcurl -v -proto=src/main/proto/helloworld.proto -plaintext -d '{"name": "abc"}'  localhost:9000 helloworld.Greeter.SayHello`, it works
3) Now, go to `src/main/java/org/acme/MyService.java` and uncomment `DOES NOT WORK` part, try again. It'll fail.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.grpc.clients.hello.host=localhost
quarkus.log.min-level=DEBUG
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin cihat-layer-mbp.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 

```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /Users/cihat/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.7, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home
Default locale: en_TR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Additional context**
Original discussion with @cescoffier and @FroMage at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Passing.20gRPC.20context.20around/near/220134523

This SO question/answer (non-Quarkus) describes my issue very well: https://stackoverflow.com/questions/47231289/how-to-pass-on-a-traceid-from-grpcs-context-to-another-thread-threadpool

I would like to see a workaround and/or a fix, and would love to see the docs updated as well. Many thanks!

**Comment by michalszynkiewicz** [comment]
@cihati is this still an issue?

**Comment by cihati** [comment]
To be honest, I don't know. We had quite a few problems with Quarkus at the time and moved away from it.

**Comment by cescoffier** [comment]
Just tried quickly and it seems to be fixed. So closing.
If it happens to not be fixed in your case, just re-open the issue and we will have another look.
