### ISSUE TITLE
Http Client should support Http/2

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#13969]
**Description**
Quarkus httpClient (quarkus-rest-client) should be able to works over `http/2` as the server-side does. Otherwise, if we use `quarkus-rest-client` for example to exchange data between microservices, then the server(even if is able to talk on `Http/2`) will talk on the same protocol as the client libraries (`Http1.1`).

**Implementation ideas**

Well, I will try to support several clients over the same interface (`StrategyPattern`). So `quarkus-rest-client` must be just the common interface of several HttpClient as ...`VertxHttpClient` (that supports `Http/2`), `OkHttp3`, `ApacheHttpClient`...etc And then depends on your configuration, you should have some specific `application.properties`. 

Example:
Lets add the proposal common HttpClient interface `quarkus-rest-client` and an implementation  `interface smallrye-mutiny-vertx-web-client`

Dependencies: 
```
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client</artifactId>
 </dependency>

 <dependency>
         <groupId>io.smallrye.reactive</groupId>
         <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
 </dependency>
```

application.properties

```
quarkus.client.http.http2=true
quarkus.client.http.ssl=true
quarkus.client.http.alpn=true
quarkus.client.http.truststore=META-INF/resources/client.keystore
quarkus.client.http.hostverified=false
```

Thank U!.

External references:

[Jira Issue](https://issues.redhat.com/browse/QUARKUS-658)

**Comment by gsmet** [comment]
@asoldano is HTTP 2 supported by the RESTEasy REST client? And if not, is there any plan to support it?

**Comment by asoldano** [comment]
@ronsigal ^

**Comment by ronsigal** [comment]
It looks like we would have to upgrade to HttpClient 5.0. I don't know yet what the implications would be, but I think it's a great idea.

**Comment by ronsigal** [comment]
JIRAs with tentative Fix Versions:

 * 4.6.0.Final: https://issues.redhat.com/browse/RESTEASY-2802
 * 3.15.0.Final: https://issues.redhat.com/browse/RESTEASY-2803

**Comment by geoand** [comment]
@michalszynkiewicz does the Reactive REST Client support HTTP 2 ?

**Comment by michalszynkiewicz** [comment]
Vert.x HTTP Client supports http/2. 
HTTPClientOptions don't have a setting for enabling http/2 so I guess rest client reactive should just use it if available but I never tested it.

**Comment by michalszynkiewicz** [comment]
I was wrong, there is an option to specify HTTP/2, you do it with `HTTPClientOptions#setProtocolVersion(HttpVersion.HTTP_2)`.

**Comment by geoand** [comment]
Interesting, I wonder if we should expose it

**Comment by michalszynkiewicz** [comment]
I think it would be good to do so

**Comment by kostacasa** [comment]
Is there a way to manually enable this on Quarkus 2.x services before it's exposed by Quarkus directly? Adding HTTP/2 support would be a great improvement to improve efficiency of high throughput API integrations. Calling other HTTP services is presumably something that most Quarkus services do.

**Comment by cescoffier** [comment]
I would rather not have complex things like multiple client implementations. We already have 2 (classic and reactive), and it's hard to keep an eye on everything.

The reactive rest client supports HTTP/2, so closing this issue is recommended.
