### ISSUE TITLE
Integration Test for Gradle?

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1396]
Given #1323, I was wondering if you would welcome an Integration Test for the Gradle Plugin stuff?

Basically there could be something like what I'll propose over in https://github.com/quarkusio/quarkus-quickstarts/issues/75 but in this main core repo, with "something" that launches it (either just a `exec-maven-plugin`, or Ant in POM, or a [via Java Code using the Gradle Wrapper](https://github.com/vorburger/ch.vorburger.osgi.gradle/blob/master/ch.vorburger.osgi.gradle/src/main/java/ch/vorburger/osgi/builder/gradle/internal/GradleBuildService.java); any preference?), so that any future breaking changes cause that IT to fail.

 @stalep @dmlloyd @Sanne @gsmet

**Comment by cescoffier** [comment]
Ideally, all the test from the maven plugin should be ported to gradle.

**Comment by vorburger** [comment]
> Ideally, all the test from the maven plugin should be ported to gradle.

[devtools/maven/src/it](https://github.com/quarkusio/quarkus/tree/master/devtools/maven/src/it ) can't be directly ported - the Maven Invoker is ... Maven specific. And you would want to run these Gradle tests from a regular `mvn install`, on any PR, to detect any future regressions.

Let me propose a minimalistic version of what I have in mind, and people can review it...

**Comment by cescoffier** [comment]
There is a lot more test for maven (src/test/java), and yes they are maven specific. I know they cannot be reused, but we need at least the same coverage.

**Comment by vorburger** [comment]
> There is a lot more test for maven (src/test/java), and yes they are maven specific. I know they cannot be reused, but we need at least the same coverage.

That would be ideal, but as s starting point, to go from 0% coverage to something, and be able to automatically find regressions like #1323 in the near term future, how about doing #1405 for now? @stalep

**Comment by stalep** [comment]
hi @vorburger, since we merged #1405 already, can we close this?

**Comment by vorburger** [comment]
> Hi @vorburger, since we merged #1405 already, can we close this?

yup, for me yes; so I'm closing it. (@cescoffier do feel free to re-open if you disagree.)
