### ISSUE TITLE
Reactive Pool HealthCheck should run on the event loop

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#13978]
**Description**
A possible improvement to follow up on #13977 would be to ensure that the "health check" operations, which need to run a SQL statement on the reactive Pool, were dispatched on the Vertx Context to be run.

This would be useful as otherwise a `Pool` instance gets associated on the worker thread, while we would typically expect these pools to only be used by operations running on the Vert.x event loop.

It's not a problem if the user ends up triggering initialization of such pools on other threads if they prefer so, but we should avoid this in our components; beyond memory costs, this would also possibly tie up connections.

**Comment by gsmet** [comment]
But isn't it a problem that the health check will probably have to be blocking?

**Comment by Sanne** [comment]
the health check is blocking already; it waits for the reactive code to have fininished successfully.

The point is that the block of reactive code which does open the connection needs to run on the vert.x event loop.

**Comment by Sanne** [comment]
Turns out we needed this as step to fix #13943 , so incorporating in the same PR.
