### ISSUE TITLE
Path configured with quarkus.http.root-path is lost when query param is included and request is redirected to IdP

### ISSUE THREAD

**Issue by canidae** [quarkusio/quarkus#13973]
**Describe the bug**
When user requests a resource with query parameters and Quarkus redirects user to IdP for authentication then the user is eventually redirected to the wrong path.

If I visit `localhost:8080/foo/` (without being authenticated) I get redirected to my Keycloak instance, which redirects me back with state params and then finally back to `localhost:8080/foo/` where everything is fine.
If I on the other hand visit `localhost:8080/foo/?bar`, I get redirected to the Keycloak instance, redirect back with state params and then finally back to `localhost:8080/?bar`. The `foo` path is lost when I add query parameters to the request.

**Expected behavior**
With configuration `quarkus.http.root-path=/foo/`.
1. Visit http://localhost:8080/foo/?bar (without having authentication tokens)
2. User will be redirected to IdP
3. User will be redirected back to http://localhost:8080/foo/?state=...
4. User will be redirected to http://localhost:8080/foo/?bar

**Actual behavior**
Same as expected, although user is finally redirected to http://localhost:8080/?bar, where "/foo" has been removed from the path.

**To Reproduce**
See _Expected behavior_.

**Configuration**
```properties
quarkus.http.root-path=/foo/
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# probably less relevant, but in case:
quarkus.oidc.application-type=hybrid
quarkus.oidc.token-state-manager.split-tokens=true
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.token.lifespan-grace=5
quarkus.oidc.token.auto-refresh-interval=3M
quarkus.oidc.authentication.session-age-extension=8H
quarkus.oidc.authentication.force-redirect-https-scheme=true

# this is tested with both true and false
quarkus.http.proxy.enable-forwarded-prefix=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 and CentOS Linux 7.9.2009
 - Output of `java -version`: Java 15.0.1-1
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.10.3
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
N/A

**Comment by gsmet** [comment]
Let's try to target a fix for this one for 1.11. It looks very annoying.
