### ISSUE TITLE
MutinyMailerImpl  - INFO: Sending email MySubject from null to [myemailadress@gmail.com] using Quarkus Mailer

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#13984]
The "from" property is always null when using the Quarkus Mailer with the log output:

> Dez. 19, 2020 8:21:42 AM io.quarkus.mailer.runtime.MutinyMailerImpl send
INFO: Sending email MySubject from null to [myemailadress@gmail.com], text body: 

and the configuration

```
quarkus.mailer.from=test@something.com
quarkus.mailer.host=smtp.sendgrid.net
quarkus.mailer.port=465
quarkus.mailer.ssl=true
quarkus.mailer.username=myuser
quarkus.mailer.password=mypassword
quarkus.mailer.mock=false
```

and the Mailer call

`
mailer.send(Mail.withText("myemailadress@gmail.com","MySubject","Some Text");
`

using Quarkus 1.10.5.

In my setup I´m using Sendgrid and it seems there is nothing really sent as I cannot complete the verification process of Sendgrid, which is likely related to the missing "from" address. 

Please let me know if I´m missing something.

**Comment by gsmet** [comment]
So the null from is just a mock artifact. It will use the right from when actually sent. We need to fix that though.

Now I have no idea why the mock is enabled as it shouldn't be. Could you prepare a small reproducer?

**Comment by gsmet** [comment]
Hmmm, no, it's not a mock artifact, it looks like your config is simply ignored.

**Comment by gsmet** [comment]
I will definitely need a reproducer for that one. Thanks.

**Comment by mklueh** [comment]
Hey @gsmet , I found the issue: I had my mail credentials in the main/application.properties but ran the code in an integration test and properties weren´t defined in the test/application.properties. Sorry :)

**Comment by gsmet** [comment]
No worries!
