### ISSUE TITLE
UnsatisfiedResolutionException in Gradle multi-module build, but working fine under test

### ISSUE THREAD

**Issue by melissasgarden** [quarkusio/quarkus#13982]
**Describe the bug**
When running `./gradlew clean build` ArC validate is throwing an `UnsatisfiedResolutionException` for a dependency injection site in a module that requires an instance of some interface, where the implementation of the interface is defined in another module. The implementing module has a `META-INF/beans.xml`.

When running the tests, the build succeeds with no validation issues and the dependency is successfuly resolved.  

**Expected behavior**
The build to succeed when running `./gradlew clean build`.

**Actual behavior**

`./gradlew clean build` - FAILS
Output:

`Execution failed for task ':order-service:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type example.OrderRepository and qualifiers [@Default]
        - java member: example.OrderService#<init>()
        - declared on CLASS bean [types=[java.lang.Object, example.OrderService], qualifiers=[@Default, @Any], target=example.OrderService]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1021)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:241)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:127)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:411)`

`./gradlew clean :order-service-test:test --tests "example.OrderServiceTest"` - SUCCEEDS
Output:

`Testing started at 10:51 AM ...

> Task :order-service:quarkusGenerateCode
preparing quarkus application
kotlin scripting plugin: project ':order-service'.compileQuarkus-generated-sourcesKotlin - configuration not found: quarkus-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake
> Task :order-service:quarkusGenerateCodeTests
preparing quarkus application
kotlin scripting plugin: project ':order-service'.compileQuarkus-test-generated-sourcesKotlin - configuration not found: quarkus-test-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake
> Task :order-service:compileKotlin UP-TO-DATE
> Task :order-service:compileJava NO-SOURCE
> Task :order-service:processResources UP-TO-DATE
> Task :order-service:classes UP-TO-DATE
> Task :order-service:inspectClassesForKotlinIC UP-TO-DATE
> Task :order-service:jar UP-TO-DATE
> Task :order-service-test:quarkusGenerateCode
preparing quarkus application
kotlin scripting plugin: project ':order-service-test'.compileQuarkus-generated-sourcesKotlin - configuration not found: quarkus-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake
> Task :order-service-test:quarkusGenerateCodeTests
preparing quarkus application
kotlin scripting plugin: project ':order-service-test'.compileQuarkus-test-generated-sourcesKotlin - configuration not found: quarkus-test-generated-sourcesKotlinScriptDef, the plugin is probably applied by a mistake
> Task :order-service-test:compileKotlin UP-TO-DATE
> Task :order-service-test:compileJava NO-SOURCE
> Task :order-service-test:processResources UP-TO-DATE
> Task :order-service-test:classes UP-TO-DATE
> Task :order-service-test:compileTestKotlin UP-TO-DATE
> Task :order-service-test:compileTestJava NO-SOURCE
> Task :order-service-test:processTestResources NO-SOURCE
> Task :order-service-test:testClasses UP-TO-DATE
> Task :order-service-test:test
Dec 19, 2020 10:51:59 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.1.Final
Dec 19, 2020 10:52:00 AM io.quarkus.arc.processor.BeanProcessor$PrivateMembersCollector log
INFO: Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field example.OrderServiceTest#service
Dec 19, 2020 10:52:01 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.1.Final
Dec 19, 2020 10:52:01 AM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Quarkus 1.9.1.Final on JVM started in 2.156s. Listening on: http://0.0.0.0:8081
Dec 19, 2020 10:52:01 AM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Profile test activated. 
Dec 19, 2020 10:52:01 AM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Installed features: [cdi, kotlin, rest-client]
Dec 19, 2020 10:52:01 AM example.OrderService process
INFO: Processing: Order(orderId=some_test_order)
Dec 19, 2020 10:52:01 AM example.InMemoryOrderRepository save
INFO: Saving: Order(orderId=some_test_order)
Dec 19, 2020 10:52:01 AM io.quarkus.bootstrap.runner.Timing printStopTime
INFO: Quarkus stopped in 0.067s
BUILD SUCCESSFUL in 6s
12 actionable tasks: 5 executed, 7 up-to-date
10:52:01 AM: Task execution finished ':order-service-test:test --tests "example.OrderServiceTest"'.`

**To Reproduce**

[https://github.com/melissasgarden/quarkus-dependency-resolution](url)

1. run `./gradlew clean build` - fails
2. run `./gradlew clean :order-service-test:test --tests "example.OrderServiceTest"` - succeeds

**Environment (please complete the following information):**

Linux t480s 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

java version "11.0.8.0.2" 2020-07-09 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03, mixed mode, sharing)

quarkusPluginId=io.quarkus
quarkusPluginVersion=1.9.1.Final
quarkusPlatformGroupId=io.quarkus
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPlatformVersion=1.9.1.Final

Gradle 6.3
Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8.0.2 (Oracle Corporation 11.0.8.0.2+1-LTS-jvmci-20.2-b03)
OS:           Linux 5.3.0-64-generic amd64

**Comment by glefloch** [comment]
Hi @melissasgarden, 

I think there is an issue in your project configuration. 
Running `./gradlew build` will try to build both `order-service` and `order-service-test` modules. 

As the `order-service` module applies the `quarkus` plugin, it will tries to build it and it fails as the `order-service` module  does not depends on `order-service-test` module which contains a `Repository` implementation bean.

In order to fix this, you can either:
* disable the `quarkus` plugin in the `order-service`
* specifically build the `order-service-test` using `./gradlew :order-service-test:build`

**Comment by glefloch** [comment]
@melissasgarden were you able to get it working ?

**Comment by glefloch** [comment]
@melissasgarden I'm closing the issue. Feel free to re-open it if you have some news.
