### ISSUE TITLE
Quartz standby mode

### ISSUE THREAD

**Issue by nragon** [quarkusio/quarkus#13993]
**Description**
Enable quartz to start in standby mode

**Implementation ideas**
It would be nice to provide an option, such as `quarkus.quartz.standby-mode (boolean)`, to enable scheduler to start in standby mode.
This would provide an easy way to enable rest apis over quartz. More like a dummy scheduler for rest operations.
In my use case I want several quarkus apps to start as scheduler workers (quartz cluster mode) and only one of them to receive/responde rest requests

**Comment by gsmet** [comment]
@nragon looks like a good opportunity to start contributing? Would you be interested?

**Comment by nragon** [comment]
@gsmet I'll try to make this one and another that is to start scheduler after registering listeners programmatically. Currently if I register listeners through `onStart`, scheduler would already have started.
I'll purpose the later in a different PR.

Thanks

**Comment by nragon** [comment]
Follow up https://github.com/quarkusio/quarkus/pull/14043

**Comment by aadityasinha-dotcom** [comment]
Hey @nragon !
I am looking forward to contributing but I am new to all this.
Can you please help me?

**Comment by nragon** [comment]
@aadityasinha-dotcom, I've just followed CONTRIBUTING.md
