### ISSUE TITLE
Async with Hibernate/Panache

### ISSUE THREAD

**Issue by crivera** [quarkusio/quarkus#1399]
I would like to use the async feature with Hibernate/Panache.

So my Controller/Resource would look something like this:

```
 @POST
  public CompletionStage<Fruit> create(Fruit fruit) {
    return CompletableFuture.supplyAsync(() -> {
      return fruitService.create(fruit);
    });
  }
```

The Service something like this:

```
public Fruit create(@Valid Fruit fruit) throws ConstraintViolationException {

    if (fruit.id != null) {
      throw new WebApplicationException("Id was invalidly set on request.", 422);
    }

    fruit.persist();
    return fruit;

  }
```

Currently though when I run this code I get the following error: `javax.enterprise.context.ContextNotActiveException`

The main question is too as to where to put/create the async block: In the Controller or in the Service?

Ifs its in the service we could do multiple service calls parallel which could speed up things tremendously. For example:

1. I would like to make a call to another API. (async)
2. I want to load something from my database. (async)
3. Once both are complete I want to combine the data and return my json object.

Thanks
Chris

**Comment by michalszynkiewicz** [comment]
seems somewhat connected to https://github.com/quarkusio/quarkus/issues/1537 where we have MP FT `@Timeout` spawning a new thread where the entity manager is not available.

**Comment by richsanram** [comment]
Any news about this? I have also this problem with Panache

**Comment by FroMage** [comment]
If you import the `quarkus-smallrye-context-propagation` module (in master, not released yet), you can now write your first endpoint as:

```java
@Inject ManagedExecutor executor;

 @POST
  public CompletionStage<Fruit> create(Fruit fruit) {
    return executor.supplyAsync(() -> {
      return fruitService.create(fruit);
    });
  }
```

And it will work. As such, I'll close this issue. Don't hesitate to reopen if it turns out I was wrong :)
