### ISSUE TITLE
multiple reactive datasource healthcheck 

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#13994]
**Description**
Since quarkus supports multiple reactive database, it would be great if the healthcheck returns the status of each datasource as a separated nodes .

Current behaviour : 

```json
{
            "name": "Reactive PostgreSQL connection health check",
            "status": "UP"
        },
```

Is it possible to add some datasource information in nodes ? With a dedicated datasource status. 
Something like this :

```json
 {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "channel1": "[OK]",
                "channel2": "[OK]"
            }
        },
```

Thank you

**Comment by gsmet** [comment]
I don't know what the best practices are for that, maybe @jmartisk and @xstefank can help.

The current behavior is the following: having UP means that all the datasources are OK. If some are failing, you will have more details with the failing ones.

I agree it would be better to be consistent for all the health checks and we need to decide in which direction we want to go.

**Comment by xstefank** [comment]
I would agree that this kind of information could be useful but this has nothing to do with the health practice only a personal preference. Users are free to define whatever they need in the "data" element. It can also be configurable if needed.

**Comment by gsmet** [comment]
Well, these are provided by Quarkus. So we need to define which best practices we want to have. And preferably be consistent across all the health checks provided by Quarkus.

**Comment by geniusit** [comment]
Actually, the reactive database healthcheck is implicit and there is no way to override it as I know
