### ISSUE TITLE
Collection of Object support in @ConfigProperties

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#14006]
**Describe the bug**
Quarkus YAML configuration should be able to parse something like this:

```
@ConfigProperties(prefix = "prefix")
public interface MyConfig {

   @ConfigProperty(name = "inputs")
   List<Input> inputs();

   @ConfigProperty(name = "outputs")
   Output[] outputs();
}
```

**Expected behavior**
Quarkus config should be able to parse YAML with variable length collection of sub-structures.

**Actual behavior**
It appears Quarkus config fails with collection fields liek above, complaining it needs converter!

**To Reproduce**
A realistic YAML config example with no known workaround,   is presented in [this thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Nested.20complex.20configurations.3F) where the issue is discussed with @geoand and @gastaldi

**Comment by geoand** [comment]
Thanks for reporting

**Comment by gastaldi** [comment]
I created a project with the data you provided and I couldn't reproduce the error: 

[hello-test.zip](https://github.com/quarkusio/quarkus/files/5724372/hello-test.zip)

**Comment by gastaldi** [comment]
Make sure you're using these imports in your `MyConfig` class: 

```java
import io.quarkus.arc.config.ConfigProperties;
import org.eclipse.microprofile.config.inject.ConfigProperty;
```

**Comment by gastaldi** [comment]
When I do: 

```java
    @Inject
    ProxyConfiguration configuration;
```

The config is injected, but the converter error is thrown when I call `configuration.inputs()` or `outputs()`

**Comment by hrstoyanov** [comment]
@gastaldi Exactly, so this is still a gap - Quarkus should be able to handle variable list of sub-structures in the YAML config .

**Comment by hrstoyanov** [comment]
so what are the plans here? If this is going to be a major effort and take some time, do you have alternatives to suggest?

**Comment by geoand** [comment]
I haven't had time to look into yet unfortunately...

It should be on the top of my list when I'm back from PTO

**Comment by geoand** [comment]
@radcortez does the new MP Config handle this case somehow?

I see that in the case of YAML like in the example @gastaldi uploaded, the value is some kind of json object that I assume can be converted into the list of objects we want, so I would like to know if there is anything that I could reuse

**Comment by radcortez** [comment]
We have similar issues reported in SR Config:
https://github.com/smallrye/smallrye-config/issues/447
https://github.com/smallrye/smallrye-config/issues/436

The main issue here is that MP Config is backed by `String` key value pairs. The Converter API does not have any context information of additional keys. The conversion happens in a key/value fashion, making it very unfriendly to retrieve related configuration in the case of multi nested lists, maps or composed objects.

What we do is to expose a parent key that contains the entire YAML context that you can use to convert to what you need. Please, check here: https://github.com/smallrye/smallrye-config/blob/master/sources/yaml/src/test/java/io/smallrye/config/source/yaml/YamlConfigSourceTest.java

**Comment by geoand** [comment]
I'll check it out, thanks!

**Comment by geoand** [comment]
I see that in that example, under the covers the new ConfigMapping API is being used. 
My plan is to rely on that for this use case - is that OK with you @radcortez ? 
I understand it's experimental, but I since this will be far away from users, we can easily adapt on the Quarkus side of that API breaks.
WDYT?

**Comment by geoand** [comment]
Hm... Actually I don't think I can use the ConfigMapping API because `SmallRyeConfig` will not have not have it configured

**Comment by radcortez** [comment]
In Quarkus any ConfigMappings are automatically added now, so it should be fine.

Anyway, the trick here is the Converter piece: https://github.com/smallrye/smallrye-config/blob/a8c0fab9b056b8205f3b4282b433f63c26f83048/sources/yaml/src/test/java/io/smallrye/config/source/yaml/YamlConfigSourceTest.java#L203-L208

A parent property `admin.users` contains the entire YAML section as a String, so you can deserialize it in the Converter. For Quarkus, to make this work transparently, we need to generate converters based on the type (if using ConfigProperties / ConfigMapping) that handle the YAML deserialization.

**Comment by geoand** [comment]
Understood, thanks.

I'll have a closer look sometime this week.

**Comment by geoand** [comment]
I think I have way to make something like this work.

It involves generating some intermediate classes and some configuration that will be fed to SnakeYaml in order to use it to generate a proper converter.
It will definitely have issues, but should work fine for basic cases.

**Comment by geoand** [comment]
@hrstoyanov with https://github.com/quarkusio/quarkus/pull/14123 (which will hopefullt be part of `1.11.CR1`) you will get almost exactly what you described.
See https://github.com/quarkusio/quarkus/blob/0bc9f8199729d5cd7201a755424c3ed5ffa37813/extensions/config-yaml/deployment/src/test/java/io/quarkus/config/yaml/deployment/InterfaceConfigPropertiesTest.java#L82 for an example of what the supported configuration will look like.

**Comment by hrstoyanov** [comment]
@geoand thanks a lot! ... waiting for 1.11.CR1 to test it out! 
Did you also expand on the [Quarkus Configuration](https://quarkus.io/guides/config) tutorial with the new capabilities, so other developers can benefit too?

**Comment by geoand** [comment]
You are welcome!

That is one thing I didn't do... I'll add some documentation today.
Good idea!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14158 adds some documentation
