### ISSUE TITLE
Undertow does not perform full classpath scanning

### ISSUE THREAD

**Issue by mvysny** [quarkusio/quarkus#14024]
**Describe the bug**
A set of classes, passed into the `ServletContainerInitializer.process()` method of a class present in a dependency jar file, doesn't receive classes from other dependency jar files.

In particular, I have a Vaadin-based project containing `DevModeInitializer`. The class is supposed to receive all `@NpmPackage`-annotated classes such as `GeneratedVaadinButton`, but it receives an empty set of classes instead.

**Expected behavior**
The `ServletContainerInitializer` class should receive a list all classes present in all jar files, not just in the .class files from the application itself. In particular, the `DevModeInitializer` should receive roughly ~70 classes but receives 0 classes.

**Actual behavior**

The `DevModeInitializer` class receives a list of 0 classes.

**To Reproduce**

Please find an example app attached in the bug report.

1. Place a breakpoint into `com.vaadin.flow.server.startup.DevModeInitializer.process()` method (line 184).
2. Run the attached app in debug mode. (I'm running the app in Intellij with the Quarkus plugin in debug mode).
3. Observe that `Set<Class<?>> classes` is empty.

**Configuration**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux mavi-vaadin 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04; OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10); OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10, mixed mode, sharing)
 - GraalVM version (if different from Java): GraalVM not used.
 - Quarkus version or git rev: 1.10.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/mavi/local/apache-maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-33-generic", arch: "amd64", family: "unix"

**Comment by mvysny** [comment]
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5728993/code-with-quarkus.zip)

**Comment by gsmet** [comment]
That's expected in the Quarkus world. You need your libraries to be part of the Jandex index.

See https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index for instance.

**Comment by mvysny** [comment]
Thank you so much for letting me know; the Jandex index looks great, let me try to index the Vaadin classes with Jandex.

Quick question: the documentation suggests that only CDI beans may be present in the Jandex index, or that Quarkus will only consider CDI beans from the Jandex index. If this is true, that is a bit of a problem since I need Quarkus+Undertow to for example find all classes annotated with `@NpmPackage` annotation.

**Comment by mvysny** [comment]
Ah, excellent - adding the following into `application.properties` helped:

```
quarkus.index-dependency.vaadin.group-id=com.vaadin
quarkus.index-dependency.vaadin.artifact-id=vaadin-button-flow
```

I can not unfortunately modify existing Vaadin artifacts to include the Jandex index, but I will try to explore an option to create a new jar with the index present for all Vaadin classes.

**Comment by gsmet** [comment]
This is exactly what you need to do to index external dependencies. If the dependencies are not too big, it should be good enough!
