### ISSUE TITLE
resteasy-reactive: When using own Content-Types for @Produces entity is always serialized with toString (resteasy-reactive 1.11.0.Beta1)

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#14023]
**Describe the bug**
Using `@Produces` with non-standard content type does not work with resteasy-reactive.  It will always serialize with toString.

**Expected behavior**
It should serialize with the correct serializer depending on the content type (e.g. jackson when Content-Type ends with `+json`)

**Actual behavior**
It serializes with toString()

**To Reproduce**

1. Checkout https://github.com/quarkusio/quarkus-quickstarts/tree/development/hibernate-reactive-quickstart
2. Change version to 1.11.0.Beta1
3. Add `@Produces("application/vnd.quarkus.fruit-v1+json")` to POST method
4. Call `curl -H "Content-Type: application/vnd.quarkus.fruit-v1+json"  http://localhost:8080/fruits -d'{"name": "apple"}' -v`

**Comment by geoand** [comment]
I have a fix for this but it breaks some of the TCK tests which means I'll need to dig into it more
