### ISSUE TITLE
Deploying a native service on knative with quarkus-openshift reports OpenShiftNotAvailableException

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#14034]
**Describe the bug**
quarkus-openshift seems unable to deploy a native service on knative into a crc cluster.
The exception log below is reported:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.3.Final:build (default) on project hello-cq-knative-native-mode: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromNative threw an exception: io.dekorate.deps.openshift.client.OpenShiftNotAvailableException: OpenShift is not available. Root paths at: https://api.crc.testing:6443/ do not include oapi.
[ERROR] 	at io.dekorate.deps.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:46)
[ERROR] 	at io.dekorate.deps.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:33)
[ERROR] 	at io.dekorate.deps.kubernetes.client.BaseClient.adapt(BaseClient.java:128)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:306)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromNative(OpenshiftProcessor.java:280)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**To Reproduce**
1. crc start -b crc_libvirt_4.6.6.crcbundle -c 8 -m 15000
2. oc login -u kubeadmin -p *********** https://api.crc.testing:6443
3. Install OpenShift ServerLess Operator (4.6/1.11.0)
4. Create a KNative Serving instance in the knative-serving namespace
5. Create a KNative Eventing instance in the knative-eventing namespace
6. git clone git@github.com:aldettinger/getting-further-with-camel-on-quarkus.git getting-further-with-camel-on-quarkus
7. git checkout QUARKUS-14034
8. cd getting-further-with-camel-on-quarkus/hello-cq-knative-native-mode
9. mvn clean package -Dquarkus.kubernetes.deploy=true

**Configuration**
```properties
quarkus.kubernetes.deployment-target=knative
quarkus.container-image.group=default
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
```

**Additional context**
It works well in JVM mode, so it looks only linked to native mode.

**Comment by geoand** [comment]
CC @iocanel

**Comment by iocanel** [comment]
The error says pretty much that `the kubernetes-client doesn't recognize the target cluster as openshift`. (so it doesn't really have to do with knative).

Why this may happen? 
Usually, due to misconfiguration of the client. Either the user is not logged in at all (though we do see that this is not the case in the provided tasks).
Other reason, may be related to client not accepting the certificates of the api server. @aldettinger: can you please add `quarkus.kubernetes-client.trust-certs` to see if this is the case?

**Comment by aldettinger** [comment]
@iocanel Many thanks for having a look.

Indeed, I don't know if there is a direct link with knative. But it's worst mentioning that I'm able to deploy the same native service when NOT using `deployment-target=knative`.

I've added `quarkus.kubernetes-client.trust-certs = true` to `application.properties`

I was thinking about a kind of transient failure to resolve the oapi url, so I've played with:
`watch 'curl -X GET -H "Authorization: Bearer ${TOKEN}" "https://api.crc.testing:6443/oapi" --insecure'`
And the apis could be listed before, during and after the failing deployment.

Any other idea ?

**Comment by aldettinger** [comment]
I had a try with remote debugging `mvnDebug clean package -Dquarkus.kubernetes.deploy=true` and learn few things:
- The maven build succeed most of the time in debug
- The issue is not sticky
- I can't hit a breakpoint in the OpenShiftExtensionAdapter class: does it run in a separate jvm ?

**Comment by aldettinger** [comment]
After more investigation, the issue could also happen repeatedly in debug too. So this is not linked.
I strongly suspect that the root cause is the crc cluster availability/stability as most of the time the web console fails at the same time of the deployment.
Moreover, I'm able to deploy the very same projects on a remote cluster with no issue.
I don't see more value to this ticket, so closing. Feel free to reopen and many thanks for assistance :+1:
