### ISSUE TITLE
resteasy-reactive: When using own Content-Type for @Produces then quarkus will set 'application/json' as Content-Type header

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#14045]
**Describe the bug**
When. using `@Produces` with non-standard content type with resteasy-reactive  will result in 'application/json' being set as Content-Type header instead of the requested type.

**Expected behavior**
It should set the requested content type that was requested in the Accept header.

**Actual behavior**
'application/json' is always set.

**To Reproduce**

1. Checkout https://github.com/quarkusio/quarkus-quickstarts/tree/development/hibernate-reactive-quickstart
3. Add `@Produces("application/vnd.quarkus.fruit-v1+json")` to POST method
4. Call `curl -H "Accept: application/vnd.quarkus.fruit-v1+json"  http://localhost:8080/fruits -d'{"name": "apple"}' -v`

**Comment by geoand** [comment]
I am pretty sure it has already been fixed in master.

Would you be willing to build master and give it a try?

Thanks

**Comment by holledauer** [comment]
Hi, I used the nightly build quarkus-resteasy-reactive-999-20201224.025011-26 for testing. https://github.com/quarkusio/quarkus/issues/14023 is already fixed there.

**Comment by holledauer** [comment]
I found another bug when trying to workaround this issue: When setting the Content-Type explicitly then the entity is serialized with toString again.

`Response.status(Response.Status.CREATED).entity(fruit).header("Content-Type", "application/vnd.quarkus.fruit-v1+json").build()`

**Comment by geoand** [comment]
Okay thanks.

I'll check it out soon

**Comment by geoand** [comment]
I opened #14046.

It does **not** fix the problem you mention in the comment - but that is more of a niche use case we can deal with later (it would be great if you opened a new issue for it).

**Comment by geoand** [comment]
Actually, I pushed a second commit to that PR that fixes the problem mentioned in the comments as well
