### ISSUE TITLE
Why does quarkus use hibernate reactive to operate the database and the query method does not use database connection pool

### ISSUE THREAD

**Issue by shilei9213** [quarkusio/quarkus#14052]
hi

I use the quarkus framework, integrate hibernate reactive, and use the panache list method to query. I find that it do not use the connection pool, but use the connection directly. As a result, the query cannot be executed after the connection is closed.

SqlClientConnection

```java
public CompletionStage<RowSet<Row>> preparedQuery(String sql, Tuple parameters) {
        feedback(sql);
        String processedSql = usePostgresStyleParameters ? Parameters.process( sql, parameters.size() ) : sql;
        return Handlers.toCompletionStage(
                        handler -> client().preparedQuery( processedSql ).execute( parameters, handler )
        );
}
```
PanacheQueryImpl

```java
  @Override
    public <T extends Entity> Uni<List<T>> list() {
        return delegate.list();
    }
```

I'd like to know how to use pool when querying?

**Comment by Sanne** [comment]
Hi, yes it uses connections. Is something not working, could you clarify what you intend to do and what is not working?

Please follow the template for reporting issues.

**Comment by gavinking** [comment]
Well, it obtains a connection from the pool and uses it. That's the correct usage pattern, as far as I understand.

Note that a query belongs to a certain session, and you shouldn't try to reuse it after the session it belongs to has been closed.
