### ISSUE TITLE
RESTEasy Reactive + OpenTracing - @Blocking results in heap memory leak

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#14058]
Describe the bug
Heap grows constantly when running load on a simple REST endpoint with @Blocking annotation
Expected behavior
Memory should not leak
Actual behavior
Memory leaks
To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn -Prelease-profile clean install
cd target
java -Xmx100m -jar ./service-runner.jar

Then :
ab -c40 -t10 -n10000000 -k http://127.0.0.1:8000/dummypath

Heap will grow and OOM will result

**Comment by geoand** [comment]
Thanks for reporting.

I'll take a look next week when I'm back from PTO

**Comment by geoand** [comment]
I did a super quick test with another hello world example and didn't see this problem...

Do you have any profiling information perhaps?
Also, I assume from the description that you didn't see the problem when `@Blocking` was not used?

**Comment by bcluap** [comment]
Correct. It only happens when using blocking annotation. I had the same
issue on a full project and then added it to the sample project and same
happened. Not sure why you cant recreate it

Not at my laptop currently so cant send more info but will try to in coming
days

**Comment by gwenneg** [comment]
@geoand I also did a super quick test 2 days ago using the reproducer, JMeter and VisualVM. There's something fishy happening in the heap related to the quarkus-smallrye-opentracing extension (lots of Jaeger-related objects that are never garbage-collected). Unfortunately I couldn't find more time to investigate this further but this information might help you identify the cause :)

**Comment by geoand** [comment]
That's interesting, thanks for the information!

**Comment by bcluap** [comment]
Yes i can confirm that this is related to opentracing. Something is not
freeing spans/traces from threadlocals

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14088 should take care of the problem
