### ISSUE TITLE
resteasy-reactive: When using @ServerExceptionMapper the entity is serialized with toString()

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#14065]
**Describe the bug**
When using a @ServerExceptionMapper and setting the content type (e.g. `application/problem+json`) then the entity will be serialized with toString().

**Expected behavior**
The entity should be serialized with the correct serializer (json in this case)

**Actual behavior**
The entity is serialized with toString()

**To Reproduce**

```
class ThrowableProblemExceptionMapper {
    @ServerExceptionMapper
    fun toResponse(e: ThrowableProblem): Response {
        return Response.status(e.status?.statusCode ?: 500).type("application/problem+json").entity(e).build();
    }
}
```

**Comment by geoand** [comment]
Thanks for reporting the problem.

I could not reproduce the issue in any of the tests I performed. 
Can you please add more details or a small reproducer?

Thanks

**Comment by holledauer** [comment]
Hi,
I finally found out where the problem is. The problem was with a external Jackson module (https://github.com/zalando/problem) that has issues when compiled natively with GraalVM. When running natively it produces only `{}` as a result.
Sorry that I was suspecting it to be the toString() issue that I had before.
I will dig deeper into the lib and try to solve it somehow.

**Comment by geoand** [comment]
Cool, thanks for the information!
