### ISSUE TITLE
AWS - Support StsWebIdentityCredentials

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#14061]
**Description**
When using AWS EKS the AWS credentials are [injected](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) into the container and are normally automatically picked up by the aws client library when adding the software.amazon.awssdk:sts dependency.
Unfortunately this doesnt work with quarkus native (I guess there is reflection involved). It would be great if quarkus could automatically work with this credential provider.

**Comment by oztimpower** [comment]
Any chance you could provide a minimalist project to test this?

**Comment by holledauer** [comment]
It is hard to provide a project because the magic is happening in the aws infrastructure. When including the software.amazon.awssdk:sts  dependency the credentials are automatically picked of from the aws infrastructure. There is normally nothing else to do in the project. 

It seems that others have the same issue: https://github.com/quarkusio/quarkus/issues/6488
I will close this as duplicate.

**Comment by gsmet** [comment]
@holledauer does the fix in the issue you pointed out work? e.g. https://github.com/moralesl/aws-quarkus-demo/commit/108f741c71fe84c96b8df30da8cb5bc3c5a041b1 ?

Looks like we would need an extension for STS.

/cc @marcinczeczko

**Comment by holledauer** [comment]
Yes that fixes the issue. But only if a synchronous aws client is available. For example it works when DynamoDbClient is injected, but not when DynamoDbAsyncClient is used. I guess that the sts library is using a sync client and that won't be compiled when DynamoDbAsyncClient is used.
