### ISSUE TITLE
Possibility to add cookie when using Qute

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#14069]
**Description**
We are at the moment developing a portal which uses our own internal system to generate JWT tokens for authentication, the token has to be returned in a Cookie that will then be used subsequently.
Unfortunately as of now there seems to be no mean to return a cookie when returning a TemplateInstance.

**Implementation ideas**
I don't really have a particular implementation idea but it would be interesting to have something like 
**_TemplateInstance.addCookie(cookie_name, cookie)_**
with _cookie_ an instance of _javax.ws.rs.core.Cookie_

**Comment by mahieddine** [comment]
Qute is a templating engine and that's it, if you want to create a cookie why not use vertx web ext ?

**Comment by dwamara** [comment]
@mahieddine Any pointer on how I can do that with Quarkus?

**Comment by mahieddine** [comment]
Yes it's super simple, you will use reactive routes https://quarkus.io/guides/reactive-routes (this nicely explains how it works)

After setting up your project, you need to add the CookieHandler to your router, you can do that somewhere in your project like this 

```java
public void init(@Observes final Router router) {
  router.route().handler(CookieHandler.create());
}
```

then in your actual route, you create your cookie and attach it to the request 

```java
@Route(path = "/accounts/:id", methods = HttpMethod.GET)
void getAccount(RoutingContext ctx) {
  Cookie cookie = Cookie.cookie(cookieName, cookieValue);
  context.addCookie(cookie);
  ...
}
```

**Comment by dwamara** [comment]
Thanks @mahieddine I have started reading about the reactive routes yesterday but something is bothering me, and it is exactly written again in your last post: "you create your cookie and attach it to the **_request_**" but it is not the request that is interesting for me because I have a login request and it is on successful login that the Cookie should be returned in the **_response_** because it contains the value of the JWT that was obtained, value that I do not have in the login request.

**Comment by mahieddine** [comment]
Sorry for the confusion i meant the context not the request ! by calling context.addCookie the cookie will be returned in the response to the client

**Comment by dwamara** [comment]
As I need to move faster than I thought with the prototype, I have decided to switch to Struts2 to solve this problem and make the frontend. I will definitely come back to this though but for the moment the issue doesn't need to stay open.
Thanks again @mahieddine for the pointer.

**Comment by pmentz** [comment]
I know this topic is old and closed, but web search did get me here and probably it helps someone, that I was able to solve this, by returning a Response with the TemplateInstance as entity (tested with Resteasy Reactive, but it should work with RestEasy Classic as well):

```
Response.ok(Templates.myTemplate())
                     .cookie(new NewCookie("foo", "bar"))
                     .build());
```

**Comment by jasonsychau** [comment]
I was able to add cookies from the client side. I'd be interested to know if there would be further security concerns for a solution like this.
