### ISSUE TITLE
Jakarta NoSql (JNoSql) Extension 

### ISSUE THREAD

**Issue by deratzmann** [quarkusio/quarkus#14060]
**Describe the extension**
Hey there.
First: thank you for your work. I like quarkus a lot.
What I am missing is an extension of "jnosql", which is a upcoming jakarta EE Standard spec for nosql databases like mongodb: https://projects.eclipse.org/projects/ee4j.nosql
I know there is an extension for some nosql clients, but especially the mongodb extension feels very rudimentary. 
Jnosql is more like jpa for nosql DBs with a CDI integration, annotations for entities and a query language.

IMHO a hibernate like integration in application.properties (especially the secretProvider) would be fine.

You can find the project here https://www.jnosql.org/ and here https://github.com/JNOSQL/jnosql.github.io.

Here is a great doc: https://jnosql.gitbook.io/jnosql-book/en/introduction
DISCLAIMER: I am not a developer on this project, I am just a guy who wants to use quarkus with it.

Thanks a lot and good night.

**Comment by maxandersen** [comment]
+1 on this being a quarkiverse extension.

**Comment by amoscatelli** [comment]
Hi guys !
I am actually want to work on this (reading quarkiverse guide just now).

I am doing this for/based on the Alpha3 version (since JNoSql v1 is going out soon and it'll be based on jakarta)
