### ISSUE TITLE
Openapi: Get rid of redirection

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#14066]
**Description**
When calling GET `/openapi` there is a redirection to `/q/openapi`. Is it possible to get rid of this redirection?

**Comment by phillip-kruger** [comment]
@kenfinnigan

**Comment by holledauer** [comment]
The same happens with the health endpoint. When calling `/health` I'm redirected to `/q/health`. I'm using the latest snapshot version (999-SNAPSHOT)

**Comment by famod** [comment]
AFAICT, this is by design and will be noted in the 1.11 release blogpost: #13601

In that PR @kenfinnigan also notes:
> Previous behavior can be attained by setting `quarkus.http.framework-root-path` to `/`

**Comment by holledauer** [comment]
The setting seems to be `quarkus.http.non-application-root-path`. I changed it to `/` and I'm still redirected to `/q/openapi` /  `/q/health`. But now I get a 404 because `/q/openapi` /  `/q/health` is not available anymore

**Comment by kenfinnigan** [comment]
It will need two configurations:

```
quarkus.http.redirect-to-non-application-root-path=false
quarkus.http.non-application-root-path=/
```

**Comment by holledauer** [comment]
I added both config options but unfortunately it didn't work. Still the same behaviour. btw I'm using `io.quarkus:quarkus-resteasy-reactive'.

**Comment by holledauer** [comment]
I just found out that the 301 redirection is cached in the browser forever. When clearing the browser cache it works.
