### ISSUE TITLE
Update partial model

### ISSUE THREAD

**Issue by tamht298** [quarkusio/quarkus#14081]
I try to update partial model and It same as db.collection.update( { _id:...} , { $set: someObjectWithNewData } in native query mongodb. This lib supports for this?

**Comment by loicmathieu** [comment]
I answer to this question on the following Zullip Thread: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/How.20to.20update.20partially.20model.20with.20mongo.20panache

Is it OK for you ?

**Comment by gastaldi** [comment]
Copying the chat transcription here: 

1. Load the entity, update the field and save if again via the `myEntity.update()` method
2. Use the `MyEntity.update(<updateDocument>).where(<filterDocument>)` method   
https://quarkus.io/guides/mongodb-panache#most-useful-operations

If you'll want to update a single field based on its ID, with the second solution this will be something like
`Person.update("name", "Loïc").where("_id", "123")`

Check the JavaDoc of the method for more information
