### ISSUE TITLE
ThreadLocalPool (reactive) leaks connections upon Thread Scale up and down

### ISSUE THREAD

**Issue by voigtste** [quarkusio/quarkus#14087]
**Describe the bug**
The ThreadlocalPool and derived variant ThreadLocalPgPool leak connections when quarkus is scaling down threads (after idling).
Root cause is, that the thread locals are additionally kept in the threadLocalPools list in io.quarkus.reactive.datasource.runtime.ThreadLocalPool. When quarkus is scaling up worker threads under load, additional ThreadLocal instances are spawned (understoodable). But as soon as the thread pool shrinks, the previous thread local instances are still in the threadLocalPools list. All connections in there are also kept open towards the DB.
When the the engine gets under load again and spawns new threads, new Threadlocal pool instances are created.
This breaks as soon as the underlying DB is running out of connections.

**Expected behavior**
ThreadLocal pools (not the pool itself, but the ThreadLocal "partitions" of the pool should be closes properly including their connections, when the Threads are scaled down.

**Actual behavior**
As mentioned above, the pool creates new ThreadPool "partitions" for each newly spawner worker thread plus corresponding DB Connections

**To Reproduce**

1. deploy some bean with DB interaction (simple query) with hibernate reactive
2. put the system under load; should be so much load, that the DB Pool is saturated
3. Cross check open connection on the DB (e.g. Postges via SELECT * FROM pg_stat_activity;); should show pool size * worker threads count of open connections
4. leave the system in idle and wait until the worker threads are reduced by quarkus
5. Repeat the load test
6. Cross check open connection on the DB (e.g. Postges via SELECT * FROM pg_stat_activity;); should show pool size * worker threads count of open connections -> the number of connections is doubled

**Configuration**
```properties
application.properties
quarkus.hibernate-orm.database.generation=create
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=***
quarkus.datasource.password=***
quarkus.datasource.reactive=true
quarkus.datasource.reactive.url=postgresql://localhost:5434/****
quarkus.hibernate-orm.log.sql=false
quarkus.datasource.reactive.max-size=10
quarkus.thread-pool.max-threads=32
quarkus.datasource.reactive.cache-prepared-statements=true
quarkus.datasource.reactive.postgresql.pipelining-limit=256

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin localhost 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "11.0.2" 2019-01-15 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.0.Beta2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9-LTS)
OS:           Mac OS X 10.16 x86_64

Workaroung for me at the moment is to set quarkus.thread-pool.core-threads and quarkus.thread-pool.max-threads to the same value in order to prevent any up and down scaling of the ThreadPool (e.e. quarkus.thread-pool.core-threads=32
quarkus.thread-pool.max-threads=32)

**Comment by geoand** [comment]
cc @Sanne @FroMage

**Comment by voigtste** [comment]
cross checked that again. If i set

quarkus.thread-pool.core-threads=32
quarkus.thread-pool.max-threads=32

which prevents thread scale up and down at all fixes the issue temporary.

But for sure, I assume this is not as it should be...

**Comment by Sanne** [comment]
Good point, thanks for reporting. Should be noted that we're actually working to ensure that all Hibernate Reactive use happens on the vertx async loop, so the scale down of the worked pool won't affect it anymore.

But I guess it's still a problem for people not using Hibernate Reactive and using the Vert.x pool directly. I wonder though if that's correct usage - we're making those changes in Hibernate Reactive as it seems the vert.x pool design requires this, something we had not fully understood initially.

**Comment by Sanne** [comment]
@voigtste a quick workaround would be to use the very latest Hibernate Reactive, you'll have to build it from master. I hope to release a beta2 soon, maybe this week already, but in the meantime it would be great if you could check if it solves your problem.

 - https://github.com/hibernate/hibernate-reactive

**Comment by Sanne** [comment]
@FroMage , do you have suggestions about the use of the vert.x pool from within the worker pool? As discussed on zulip, it's inherently unsafe in respect to the threading model, I wonder if I should wrap the pool with an assertion, having it throw exceptions in case of misuse.

**Comment by voigtste** [comment]
@Sanne: already tried that before (hibernate latest from repo). The pool impl is coming from the quarkus extension. So unfortunately, does not help.
Additionally, I cannot prevent, that the pool is used from the worker threads. In my sample (blueprint for larger app system) we want to use hibernate reactive together classic business logic inside CDI beans (also request scoped). On top we would like to use panache reactive and this is looking for the reactive hibernate session (mutiny) via CDI injection. In other words, we do not have real control, where the session is openened and subsequently connections are initiated.

I see too solution approaches: Either open the API of the Quarkus Pool implementation for more lifecycle control (e.g. method for explicity closing the local thread partition (not the whole pool). I would be ok to implement the cleanup on the application side as long as this is clearly documented. Or it would also be ok, that the quarkus extension allows a configuration of an "own" derived pool implementation. Right now, the impl class is hard coded on the extension bootstrap.

solution b) (preferred) The pool is "smart enough to handle thread spawn and decommission and subsequent disposal of the thread local partitions. I thought about handling this via a close hook on the vertx context of the worker thread. But I am not sure, of this lifecycle works reliable for worker threads.

**Comment by voigtste** [comment]
Side note just as a constructive critic: I do not like the thread local pool approach so much. I am pretty sure, that there was reason to do that but it makes it quite complex in deployment scenarios with multiple threads. E.g. when you configure the pool size to 5, the limit will not be five, it will be 5 times the number of spawned threads. So this is error prone from the config side and on a large scale app (multicore with a lot of workers) it will bring every DB under "pressure".

**Comment by FroMage** [comment]
I guess we can ask @dmlloyd if there's a hook for thread cleanup from the pool.

But that won't help us when pooling on non-quarkus-threads. We should probably only do TL-pooling on event loop threads (provided they don't scale up/down) and Quarkus worker threads (if we can shut down the pool on scale-down).

Note that this setting was added for a benchmark that was running on the event loop, and we didn't really mean to make this non-experimental for other types of threads.

You could just disable thread-local pooling.

**Comment by dmlloyd** [comment]
What you'd want to do is to wrap the `Thread`'s `Runnable` so that it does the requisite cleanup before exiting in a `finally` block.  The way to do this (in our thread pool or almost any other) would be to wrap the `ThreadFactory`.

**Comment by FroMage** [comment]
OK so there's nothing in place for that, but we can add it at the Quarkus level and provide a user API for declaring such cleanup actions, thanks.

**Comment by FroMage** [comment]
@Sanne if you forced the thread-local pool default to make sure we didn't use the global pool, then perhaps we should get rid of the global pool and refuse to pool on non-event-loop threads entirely?

**Comment by Sanne** [comment]
Right, within Hibernate Reactive there's assertions (since only a couple of weeks) to ensure we exclusively access the pool from the event loop. I believe that's the right call for Hibernate.

But there's potentially more users than Hibernate Reactive; for those we have three options (summarizing your and David's suggestions as well):

1. patch our worker pool executor to produce special threads on which we can register a cleanup hook
2. Explicitly check (and disallow) any usage of the Pool instance from the wrong context
3. Make my silly pool wrapper more paranoid, e.g. check for dead threads lingering in the map each time there's a new thread or periodically.

For the record, I don't like 3. Option 2. is what I proposed in the chat in Zulip before christmas, but it had objections.. are the objections withdrawn now that the problem is perhaps clearer?

Personally I'd go with option 2, *unless* you can see other similar needs for cleanup actions. If we need such a hook for multiple reasons, might as well use it here too.

**Comment by Sanne** [comment]
> @Sanne: already tried that before (hibernate latest from repo). The pool impl is coming from the quarkus extension. So unfortunately, does not help.

You're right; it's not going to be like that - I have some more patches locally. Sorry, I forgot about those during the break :)

**Comment by Sanne** [comment]
> Side note just as a constructive critic: I do not like the thread local pool approach so much. I am pretty sure, that there was reason to do that but it makes it quite complex in deployment scenarios with multiple threads. E.g. when you configure the pool size to 5, the limit will not be five, it will be 5 times the number of spawned threads. So this is error prone from the config side and on a large scale app (multicore with a lot of workers) it will bring every DB under "pressure".

I totally agree - and warned my team mates about the same concern. A better pool implementation will be needed and I am watching this closely. But also consider we'll soon (2 months?) switch to Vert.x 4, which won't need the threadlocal and changes the design a bit.

In case we still want to use a thread-local based approach, I'd want to at least improve it by implementing some scheme to honour the connection limits across threads. But let's see Vert.x v4 first..

**Comment by dmlloyd** [comment]
> 1. patch our worker pool executor to produce special threads on which we can register a cleanup hook

I want to clarify that what I was suggesting was *not* to create special threads but to delegate to the "upstream" `ThreadFactory` but pass it a wrapped `Runnable`, which is essentially exactly what was asked for (i.e. a uniform way to add behavior to a thread without really caring what the thread implementation is).  Adding an API to register cleanup hooks is not necessary as long as the thread factory can be configured.

**Comment by voigtste** [comment]
@Sanne
>I totally agree - and warned my team mates about the same concern. A better pool implementation will be needed and I am watching this closely. But also consider we'll soon (2 months?) switch to Vert.x 4, which won't need the threadlocal and changes the design a bit.
>In case we still want to use a thread-local based approach, I'd want to at least improve it by implementing some scheme to honour the connection limits across threads. But let's see Vert.x v4 first..

Sounds good to me. Will watch and follow this

> 1.  patch our worker pool executor to produce special threads on which we can register a cleanup hook
> 2. Explicitly check (and disallow) any usage of the Pool instance from the wrong context
> 3. Make my silly pool wrapper more paranoid, e.g. check for dead threads lingering in the map each time there's a new thread or periodically.
for 2. I think disallowing is not so nice. As in my case (hibernate reactive plus with panache reactive) it is more or less impossible to control the point where the framework will pickup / initialize the connection. Especially with CDI injected cases (lazy initialized by nature) it is hard to predict as soon as the application side will incorporate worker threads (which should be not unusual) for hybrid scenarios (reactive and "short term" blocking code. I would prefer 1. or 3.

**Comment by voigtste** [comment]
Another side question in this context: do worker threads also have per default a vertx context which will be disposed when the thread is removed and then would a "close hook" on the vertx context be called in this case? Just as an idea to place some cleanup logic for the pool...

**Comment by Sanne** [comment]
> for 2. I think disallowing is not so nice. As in my case (hibernate reactive plus with panache reactive) it is more or less impossible to control the point where the framework will pickup / initialize the connection. Especially with CDI injected cases (lazy initialized by nature) it is hard to predict as soon as the application side will incorporate worker threads (which should be not unusual) for hybrid scenarios (reactive and "short term" blocking code. I would prefer 1. or 3.

I understand, but if you do indeed use it from a context in which you don't know for sure if you're using the client from "the right thread", then you get in trouble with data races - and might not notice, especially if you are in a context in which you can't know for sure.
I can't prevent race conditions other than documenting "don't do this" but this gets tricky in such complex applications. Don't you think some form of `IllegalStateException` to catch problematic usage during integration testing would be preferreable?

FWIW, the "blocking" version of Hibernate ORM also performs very well in Quarkus, and doesn't have (nor need) such limitations; I would suggest using that when one can't guarantee a fully-reactive use.

On the other hand, if your function is entirely living within a reactive context (running on the Vert.x event loop), such as being initiated by RESTEasy Reactive, then it's more efficient to stay within the event loop by using Hibernate Reactive and/or the vertx SQL client.

I also wonder how to make the "hybrid reactive" situation better, but haven't figured it out yet :) My impression so far is that Reactive is better experienced when "pure"..

**Comment by Sanne** [comment]
@voigtste might want to play with https://github.com/quarkusio/quarkus/pull/14102

It does NOT address:

- the connection leak reported here
- nor fixes Hibernate Reactive Panache

but if you use Hibernate Reactive over its own API and without opening a Session directly, it will delegate work to the right context.
You can set `-Dorg.hibernate.reactive.common.InternalStateAssertions.ENFORCE=true` to have it throw exceptions when one of the other APIs is used from the wrong thread (and it would fail with Panache Reactive if you use it at all from the wrong thread).

Assuming you don't access the SQL Pool directly from a worker pool thread, and your code doesn't fail when run with that flag enabled, it should avoid the connection leak as well.

**Comment by gavinking** [comment]
@Sanne remember this is changing somewhat in vert.x 4 and i'm not sure how that impacts this discussion.

**Comment by Sanne** [comment]
@gavinking right, I mentioned that some ~100 comments above :)
 - https://github.com/quarkusio/quarkus/issues/14087#issuecomment-754112051

I guess I should check what the pool does in vert.x 4, I haven't had the chance yet - I just suspect it will still need _some_ restrictions, but let's see first..

**Comment by gavinking** [comment]
ah OK, sorry, carry on 😅

**Comment by Sanne** [comment]
np, I'm glad you're watching these issues :)

**Comment by voigtste** [comment]
> @voigtste might want to play with #14102
ok, will play with that and come back asap

**Comment by Sanne** [comment]
I didn't want to spend too much time on this (as I don't have much time and should really study vert.x 4 for a long term optimal solution), but since a leak isn't acceptable to me I'm sending a PR with an alternative solution.

Essentially, while it would be more complicated to immediately cleanup references on scale down, it's quite straight forward to check for zombies when we scale in the other direction. This implies that while resources won't be immediately released, the maximum cost will - in worst scenario - only match the cost you'd have at maximum scale up of the pool.

So it's not optimal yet but at least it's not a leak which risks taking down a system, as a periodic scale up/down won't result in additional memory costs.

**Comment by FroMage** [comment]
That's a nice fix for the moment, thanks.
