### ISSUE TITLE
RocksDB extension proposal

### ISSUE THREAD

**Issue by alukin** [quarkusio/quarkus#14097]
**RocksDB extension description**

It would be a very good thing for compact microservice to have the ability to save data in a simple but very fast embedded key-value store. RocksDB is a good candidate for such key-value store with on-disk persistence. RocksDB is used in many projects and well supported. It is implemented C/C++ but has supported Java API in its source repository.
Simply adding "rocksbjni" dependency to Quarkus project works well in Java mode, but needs ld-preload of rocksb shared library in native mode. To solve this problem, Quarkus extension should be developed.

I think there's no need for complicated things on top of RocksDB API, such as Panache. Maybe it is a good idea to add SpringData-like KeyValueRepository support as described in the [article](https://dev.to/thegroo/simple-rocksdb-with-java-crash-course-20o7)

Note, that quarkus-kafka-streams extension already uses RocksDB but does not expose the API. So the conflict of extensions is possible.  

I (alukin@gmail.com) would like to start and lead the development of this extension.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
```properties
# Add your application.properties here, if applicable.
quarkus.rocksdb.basedir=/mnt/ssd/myapp
quarkus.rocksdb.bufsize=16M
#other RocksDb options similar to [MyRocks module](https://mariadb.com/kb/en/myrocks-system-variables/)
```

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkiverse-rocksdb.

Let us know if you have any questions in the Quarkus mailing list or in https://quarkusio.zulipchat.com. 

Happy coding! ;)
