### ISSUE TITLE
Hooks on RuntimeUpdatesProcessor

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#1410]
The [`io.quarkus.dev.RuntimeUpdatesProcessor`](https://github.com/quarkusio/quarkus/blob/a91a034b855cae3f8d474951cb33e8d05707dc13/core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java) is responsible to scan both sources or resources to detect a change an apply a reload.

The idea is to expose the change detection events (either on RuntimeUpdatesProcessor or directly on HotReplacementContext), mainly for 3rd party integrations, here you have some ideas: 

- When doing web development it would be interesting to delegate to webpack to build the web app whenever a "web" file has been modified or having an integration with BrowserSync.
- Propose some "useless but mandatory stuff" like a growl notification when the app is reloaded.
- Collecting some "real-life" stats about how much stop/start a dev earned thanks to the hot reload, time to start, etc.

**Comment by danielpetisme** [comment]
@gsmet I propose to close the issue, it's a duplicate of #1418.

**Comment by gsmet** [comment]
@danielpetisme is it really? It seems it's a little bit different and you developed interesting ideas here?

**Comment by danielpetisme** [comment]
🤔 
From my understanding, the complex part of these ideas is the resources file detection and how to hook up 3rd-party tools.
LiveReload is of course a good use case. 
Is it enough to cover all the technical aspects ? Do you see, in the above proposals, technicals points not covered by the LiveReload support initiative?
