### ISSUE TITLE
smallrye-health extension doesn't work when a root path is set in 1.11.0.BetaX versions

### ISSUE THREAD

**Issue by jessydeclerck** [quarkusio/quarkus#14109]
**Describe the bug**
Using quarkus 1.11.0.Beta2 version, smallrye health endpoint is not found when a root path is set
(Behaviour is the same for 1.11.0.Beta1)

**Expected behavior**
When calling http://localhost:8080/myrootpath/health should return a 200 with some health informations

**Actual behavior**
When calling http://localhost:8080/myrootpath/health a 404 Resource Not Found is returned. Moreover, I'm redirected to http://localhost:8080/q/myrootpath/health which also returns a 404

**To Reproduce**
https://github.com/jessydeclerck/microprofile-health-issue

1. mvn compile quarkus:dev
2. Check http://localhost:8080/myrootpath/health => Resource Not Found
3. Shutdown app, set quarkus-plugin.version and quarkus.platform.version to 1.10.5.Final
4. mvn compile quarkus:dev
5. Check http://localhost:8080/myrootpath/health => Works perfectly

**Comment by kenfinnigan** [comment]
@gsmet I'm going to look into this as it should be fixed for CR1

**Comment by gsmet** [comment]
OK, thanks!
