### ISSUE TITLE
Incorrect status code with custom Vert.x route and Quarkus RESTEasy extension is enabled

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#14112]
**Describe the bug**

If you configure a custom Vert.x route like the following:

```java
public void init (@Observes Router router) {
    router.post("/test")
            .consumes("application/json")
            .produces("application/json")
            .handler(context -> context.response().end("{\"message\": \"Hello World\"}"));
}
```

Then `POST` to the `/test` endpoint and omit the required `Content-Type` header, then the expected status code should be `415 Unsupported Media Type`. This is the behavior, except when Quarkus RESTEasy is present. In this case the status code is incorrectly returned as `404`.

**Expected behavior**

The response code where the incorrect `Content-Type` is provided should be `415`.

**Actual behavior**

The response code where the incorrect `Content-Type` is provided is `404` when the Quarkus RESTEasy extension is active.

**To Reproduce**

I built a simple demo app to reproduce the problem here:

https://github.com/jamesnetherton/quarkus-http-demo

**Comment by geoand** [comment]
I am not really sure about this to be honest...

Basically what happens when you add Quarkus RESTEasy is that RESTEasy takes over the entire handling of the request and thus 404 is returned. My guess is that you can probably get the behavior you are looking for if you set `quarkus.resteasy.path` to something other than `/`. 
I would personally be in favor of keeping things the way they are, but I'd like to hear what @stuartwdouglas and @cescoffier think as well.

**Comment by cescoffier** [comment]
To implement the behavior you want you cannot use `consumes` as it will skip the route is the media type does not match (hoping to find another suitable route later). As @geoand explained, at some point, it just delegates to resteasy. 


There are two possibilities:

1. Did you try to remove quarkus-resteasy (if your application does not use it). 
2. Remove the `consumes` and handle that in the handler.

**Comment by jamesnetherton** [comment]
Yes, removing `quarkus-resteasy` works but it's not an ideal 'fix'.

FWIW I'm coming at this from a Camel perspective where the HTTP consumer component we use for Quarkus creates routes on the Vertx.x router. If RESTEasy is present, then it has the potential to screw things up in some scenarios.

I can experiment with handling `consumes` in the route handler and also setting an alternate `quarkus.resteasy.path`.

**Comment by jamesnetherton** [comment]
Setting a custom `quarkus.resteasy.path` seems to work ok.

In practice, it's maybe not so likely that folks will mix JAX-RS services with Camel HTTP consumers, so I'm happy to close this for now given that there's an acceptable workaround.

**Comment by geoand** [comment]
Great!
