### ISSUE TITLE
Nested YAML structures not handled properly by @ConfigurationProperties

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#14113]
**Describe the bug**
See [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Yet.20another.20configuration.20issue)

**Expected behavior**
As per the example given, I expected to see 3 different mssql structures 

**Actual behavior**
All 3 ended up the same - like the last one

**To Reproduce**
See the description above, it has all the sample code and YAML. The isseu is observed in Quarkus 1.10.5.FInal, Java 15.

@geoand @gastaldi

**Comment by gsmet** [comment]
hey @hrstoyanov , could you please describe the issue in your description? Will be handy if users search for it in the future.

**Comment by hrstoyanov** [comment]
Atatching a reproducible project - See the Main.java class
[issue14113.zip](https://github.com/quarkusio/quarkus/files/5770037/issue14113.zip)

**Comment by geoand** [comment]
This had the potential to be serious, but thankfully the fix is simple and effective (and included in https://github.com/quarkusio/quarkus/pull/14123). Under the hood, things make a lot more sense now.
The problem was that we hadn't considered the fact that the same interface could be used for different method of the top-level interface. 

Thanks for reporting!

**Comment by hrstoyanov** [comment]
Lovely!!! Will try 1.11.RC1  with #14123 as soon as it is out,  since I am stuck right now ...

**Comment by hrstoyanov** [comment]
@geoand unfortunately I still see issues here with 1.11.RC1(see gradle config). Take a look at the attached reproducible project
[issue14113-new.zip](https://github.com/quarkusio/quarkus/files/5818878/issue14113-new.zip)

I added Version nested configuration and data for it in the application.yml. I expected to read that data , but instead - got the defaults from the Version interface???

Run Main and you will see in the output console:

```major: 15, minor: 0```

instead of:

```major: 16, minor: 0```

**Comment by geoand** [comment]
I'll have a look later on

**Comment by geoand** [comment]
I took a look and if I am not mistaked, the problem lies in your configuration, not the way Quarkus handles it.
In your YAML you have:

```
sql_proxy:
  server:
      version:
        major:16
        minor:0
```

which is wrong because there is no whitespace between `major:` and `16`. If you add a whitespace, then everything works as expected.

**Comment by hrstoyanov** [comment]
ouch ... you are correct! The traps of YAML

**Comment by geoand** [comment]
I personally dislike YAML very much...

**Comment by hrstoyanov** [comment]
Please re-open:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Need.20some.20help.20with.20Smallrye.20ConfigMapping

**Comment by geoand** [comment]
Do you have an example I can use to test this?

**Comment by hrstoyanov** [comment]
See #14847. @radcortez is well aware of the issues, we discussed them on the zulip chat, I provided examples there
