### ISSUE TITLE
Private and static methods on interface don't work with @ConfigProperties

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#14110]
**Describe the bug**
Described in details [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Configuration.20interface.20-.20unnecessary.20restriction.3F/near/221631040)

**Expected behavior**
Config interface should not suffer from such restrictions on private static methods

**Actual behavior**
Quarkus 1.10.5.Final fails with :
```
 io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.IllegalArgumentException: Method convert of interface com.dynamind.sqlproxy.server.mp.SQLProxyConfig is not a getter method since it defined parameters

```

**To Reproduce**
See issue description for sample code.

**Comment by hrstoyanov** [comment]
@geoand as you requested ..i filed this bug

**Comment by geoand** [comment]
Thanks a lot!

**Comment by geoand** [comment]
This was just a garden variety bug and a fix is included in https://github.com/quarkusio/quarkus/pull/14123
