### ISSUE TITLE
MongoDB with Panache - Field accessor rewriting not working on native

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#14128]
**Describe the bug**
Field accessor rewritting lands in master a few days ago thanks to #13743

But failures on Quickstart seems to indicates that it didn't work on native images: https://github.com/quarkusio/quarkus/issues/6588#issuecomment-745129630

**Expected behavior**
Field accessor rewritting works in both JVM and native mode.

**To Reproduce**

A reproducer can easily be created by adding a `toUpperCase()` to the `io.quarkus.it.mongodb.panache.book.Book.getTitle()` and updating the test acordingly.

After making the test pass in JVM mode, it will fail in native.

**Comment by geoand** [comment]
What's the plan for this one?

**Comment by FroMage** [comment]
There's no reason why this would work for JVM and not native, especially if it works for ORM with Panache.

**Comment by gsmet** [comment]
@evanchooly could you have a look at this one? Thanks!

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
