### ISSUE TITLE
docker build native error

### ISSUE THREAD

**Issue by waerly** [quarkusio/quarkus#14138]
I reported an error during the build：

`registry.access.redhat.com 504 Gateway Time-out`

**Comment by waerly** [comment]
dockerfile

```sh
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
#FROM ubi8/ubi-minimal:8.3
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

**Comment by geoand** [comment]
Maybe it was a transient error?

It doesn't look like Quarkus has anything to do with it here

**Comment by waerly** [comment]
> Maybe it was a transient error?
> 
> It doesn't look like Quarkus has anything to do  with it here

@geoand 
ok,I have solved this problem。thank you！

But there was a new mistake in my docker run ..... 


```sh

standard_init_linux.go:219: exec user process caused: exec format error

```

**Comment by geoand** [comment]
Cool!

Hm... That seems like a docker (or podman) bug though... Again it shouldn't be related to Quarkus

**Comment by proteus1121** [comment]
@waerly I faced the same issue in the docker run, did you solve it?
