### ISSUE TITLE
Scala language support

### ISSUE THREAD

**Issue by vertexclique** [quarkusio/quarkus#1413]
In addition to Kotlin, maybe it's also good to have Scala supported. Adding Scala source discovery and having it to compile an Akka application would be a nice way to provide a starting ground for Scala.

**Comment by gsmet** [comment]
@vertexclique would you be interested in taking a stab at it?

The PR for the Kotlin addition is here: https://github.com/quarkusio/quarkus/pull/1059 .

**Comment by marcobattaglia** [comment]
@geoand @vertexclique
You can find an example of using quarkus, scala and kotlin together here:
[https://github.com/marcobattaglia/quarkus-scala](https://github.com/marcobattaglia/quarkus-scala)

We are working on testing other quarkus features: jpa, reactiveX and so on.

If you think that it needs some work in order to provide a better integration with quarkus we can work on it.

**Comment by geoand** [comment]
@marcobattaglia thanks for the pointer!

I think what @vertexclique was asking for was support for the dev mode with Scala resources

**Comment by vertexclique** [comment]
> I think what @vertexclique was asking for was support for the dev mode with Scala resources

Yes, also the support dependency like how kotlin has been done.

**Comment by gabfssilva** [comment]
Scala is a bit different from Kotlin since it uses its own Option<T>, List<T>, Future<T> and so on, so maybe it needs more efford than Kotlin to implement expressive Scala with Quarkus.

**Comment by wiradikusuma** [comment]
I use Grade 5.2.1 and followed https://quarkus.io/guides/gradle-tooling but I still can't make `gradlew quarkusDev` to run on my Java/Scala project.

First, it complains when the source dir is separate (`src/main/java` and `src/main/scala`). When I merged them together (`src/main/java`), it complains that it can't find some stuff that the Java classes rely on (basically, `gradlew quarkusDev` completely ignores Scala files).

Is https://github.com/quarkusio/quarkus/pull/3399 supposed to fix this? If yes, which release will have that?

**Comment by geoand** [comment]
The Scala PR has been merged but there is no release that contains it yet.
0.22.0 which is the next release will have this support

**Comment by forevergenin** [comment]
Looks like 0.22 release doesn't include scala support.

**Comment by geoand** [comment]
That is true.

0.22 turned out to be an intentionally small release because we only wanted to get some of the stuff out.
Stay tuned for newer Quarkus releases soon 😉

**Comment by aesteve** [comment]
Tried it with 0.23.1 seems to be working really fine in dev/jar mode!

I still have an issue building a native image (on Mac OS 10), but really not sure it's related to Scala, gradle, Graal, 0.23.1, or my laptop, or anything else actually :s

Here is the experiment: https://github.com/aesteve/quarkus-scala-gradle

**Comment by machi1990** [comment]
This issue has been fixed by https://github.com/quarkusio/quarkus/pull/3399 and deployed in 0.23.1 version. Closing.
