### ISSUE TITLE
Qute...Co-locate templates and static resources

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#14130]
**Description**
I'm working on using Qute along with Hotwired Turbo (https://turbo.hotwire.dev/) which is working very well since Qute returns HTML and that is what Turbo is designed for.  This methodology can be outstanding as long as Quarkus continues to support some type of template system if not Qute.

Turbo can submit ajax requests to resources/META-INF/resources directory without accessing a JAX-RS endpoint.  These are resources such a .css, .js, .jpg, and static .HTML files.

The issue becomes when access to a dynamic HTML page is needed (getting a list of items from a database).  The .html resources needed via Qute are located in the resources/templates directory.  So these files in order to access static resources use a src attribute like so (assume quarkus.http.root-path=/example/resources):  

<script src="/example/resources/assets/js/turbo.js">

**Implementation ideas**
Can the Qute templates also be located under a resources/META-INF/resources/qute directory so they are in the same directory structure but also separated from the other content? 
 resources/META-INF/resources/assets/css/some.css
resources/META-INF/resources/assets/js/some.js
resources/META-INF/resources/assets/images/some.jpg
resources/META-INF/resources/static.html
resources/META-INF/resources/qute/dynamic_template.html

I was not able to figure out how to change the path to the templates as described in section 2.6.1 by manual registration or by use of a locator.  If those are options, please update the docs to show how this is done.
 
Thanks

**Comment by mkouba** [comment]
Hi @jefrog1844, what exactly are you trying to achieve? Turbo is a SPA framework, right? Do you need to obtain a rendered template without a JAX-RS endpoint or a reactive route? I don't think it makes much sense to access a template source?

**Comment by jefrog1844** [comment]
Turbo is an SPA that uses web components to issue AJAX requests to updated specific areas on the page or the entire page.  It expects HTML instead of JSON.  It uses basic tags like <turbo-frame id="messages" src="/messages”></turbo-frame> to issue AJAX requests which will replace the contents between the tags with the returned html content.

So I can place an index.html file in the resources/META-INF/resources directory that can contain the turbo frames markup and retrieve html content from JAX-RS endpoints via Qute templates which is reasonable.  I do have some pages though that don’t require injection of data, they are static pages (i.e help pages, forms).  The options are to load them from the META-INF/resources directory or set up a JAX-RS endpoint to retrieve them from the templates directory.

I was hoping the front end files (html, css, javascript) could all reside in the same directory.

Thanks

Jeff

**Comment by mkouba** [comment]
I'm going to close this issue. There is no plan to co-locate qute templates and static resources in the near future. I think that static resources should always be placed in the `META-INF/resources` directory and accessed directly from the template, e.g. `<link href="/css/styles.css" rel="stylesheet">` for `META-INF/resources/css/styles.css`. If we permit templates in the `META-INF/resources` directory we would have to filter out template sources when serving static resources. Also note that not all templates need to be published via the HTTP server.
