### ISSUE TITLE
Failing Kafka message silently swallowed

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14145]
**Describe the bug**
I have a Kafka message handler which raises an exception. This exception is nowhere logged making it impossible to find out what's wrong.

**Expected behavior**
The exception should be shown on sysout.

**Actual behavior**
Not seeing the exception. Only after a while I see another exception about the fact that my message never was acked. But I have no way of knowing why that'd be.

**To Reproduce**

Have a handler like this:

    @Incoming("payment")
    public CompletionStage<Void> onMessage(KafkaRecord<String, String> message) throws IOException {
        return CompletableFuture.runAsync(() -> {
            throw new RuntimeException ("BOOM");
        }).thenRun(() -> message.ack());
    }

**Configuration**
n/a
**Screenshots**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: openjdk 16-ea 2021-03-16
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3_1
 
**Additional context**
n/a

**Comment by gunnarmorling** [comment]
CC @cescoffier

**Comment by cescoffier** [comment]
Hum,

You should see something like:

```
@LogMessage(level = Logger.Level.ERROR)
@Message(id = 201, value = "Error caught during the stream processing")
void streamProcessingException(@Cause Throwable cause);
```

Because you use `Message`, it cannot be _nacked_ automatically (as the _nack_ may have been done already). BTW, what's the reason to use `Message` and not _payload_? 


```
@Incoming("payment")
public CompletionStage<Void> onMessage(Record<String, String> message) throws IOException {
    return CompletableFuture.runAsync(() -> {
        throw new RuntimeException ("BOOM");
    });
}
```

**Comment by cescoffier** [comment]
My bad, found the issue...

**Comment by gunnarmorling** [comment]
> My bad, found the issue...

Ok, that's good. Silent swallows like this are kinda concerning :)

> BTW, what's the reason to use Message and not payload?

I need access to key and headers, too.

**Comment by cescoffier** [comment]
@gunnarmorling PR opened: https://github.com/smallrye/smallrye-reactive-messaging/pull/921
If everything goes through, release and bump tomorrow

**Comment by gunnarmorling** [comment]
Excellent, thx for the fast turnaround!

>
