### ISSUE TITLE
Investigate why LOG level may be different to the configured level in CI builds

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#14140]
**Description**
`integration-tests/bouncycastle-fips-jsse` test has this configuration:
```
quarkus.log.category."org.bouncycastle.jsse".level=TRACE
``` 
When I run this test locally both the console and file logs are reported at the trace level in JVM mode. In CI I saw a message like
`"org.bouncycastle.jsse".level is configured at the level below the required INFO, promoting it to INFO` - so I had to disable checking the log for that test.

**Comment by gsmet** [comment]
It might be due to the new `min-level` feature: https://github.com/quarkusio/quarkus/pull/13376 .

/cc @galderz

**Comment by sberyozkin** [comment]
@gsmet Interesting, thanks, I'll give it a try in another PR :-)

**Comment by sberyozkin** [comment]
Specifically I'll try to re-enable checking the log in `bouncycastle-fips-jsse` (this one runs in JVM mode for now) and update the way it is checked in `bouncycastle-jsse` (runs in JVM and native modes - in JVM both client and server TLS records are checked, in native - only server as client ones were not captured - I'll try to catch the client records in the native mode too)

**Comment by sberyozkin** [comment]
I've started with #14163.

@galderz Hi, quick question - why does `integration-tests/oidc-client` which also has a `TRACE` enabled successfully detects `TRACE`-level logging without `min-level`, while `integration-tests/bouncycastle-fips-jsse` fails without `min-level`, something I've now also verified locally ? Can it be related to the fact that `integration-tests/oidc-client` traces the `quarkus-oidc-client/runtime/.../OidcClientImpl.class` (so this class is native to the extension) while `integration-tests/bouncycastle-fips-jsse` traces a 3rd party library ?

**Comment by sberyozkin** [comment]
@galderz `integration-tests/bouncycastle-jsse` also works without `min-level`.

I'm not sure - the documentation is clear that `min-level` allows to optimize and remove some dead code related to the trace level, but it looks non-intuitive to me, having to set `TRACE` twice. I guess no one is using this level in production

**Comment by sberyozkin** [comment]
@galder - oh, sorry, you've already fixed `integration-tests/bouncycastle-jsse`, thanks :-)

**Comment by sberyozkin** [comment]
I'm going to close this one now, in the native mode, `bouncycastle-jsse` can still not capture the client records, but I'm not really worried about it as the MTLS test itself passes and it is not really related I think to the `min-level`. thanks
