### ISSUE TITLE
Kafka healthcheck with SASL SSL

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#14156]
Hello,

I have a problem with the kafka healthcheck management.

prerequisite: `quarkus.kafka.health.enabled=true`

To make it works you MUST define a `kafka.bootstrap.servers` value.

Rather than, I prefer to config my kafka boostrap server according with a specific channel : 

```
mp.messaging.incoming.mytraindata.connector=smallrye-kafka 
mp.messaging.incoming.mytraindata.bootstrap.servers=xxxxx
mp.messaging.incoming.mytraindata.security.protocol=SASL_SSL
mp.messaging.incoming.mytraindata.sasl.mechanism=PLAIN
mp.messaging.incoming.mytraindata.group.id=xxxxx
mp.messaging.incoming.mytraindata.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="xxxxxxxxxxxx";
mp.messaging.incoming.mytraindata.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.mytraindata.enable.auto.commit=false
```

So I think there is no way not to duplicate the line

But even if I do it I got the following timeout error on healthcheck call : 

```json
 {
            "name": "Kafka connection health check",
            "status": "DOWN",
            "data": {
                "reason": "org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1609967046632) timed out at 1609967046633 after 1 attempt(s)"
            }
        },
```

I notice that i don't encounter this prob with no secure connection.

Also, as a consequence, you can't differentiate the channels by servers.
As reading the GET response, you will trust that all the channels belong to the same kafka bootstrap servers (`kafka.bootstrap.servers`).
It would be a good idea the differentiate channels by bootstrap servers because actually the healthcheck always refers to the default one (`kafka.bootstrap.servers`)

Does the healthcheck use the secure configuration ? I think not ... 

In fact this issue relates to two differents problem. I should have been create two separates

Thank you

**Comment by xstefank** [comment]
This seems related to Kafka health checks. @cescoffier can you take a look?

**Comment by cescoffier** [comment]
I will have a look.
The JSON output does not seem totally consistent with what we have in reactive messaging. 

In reactive messaging, you can enable/disable the health check per channel using the `health-enabled` attribute.

**Comment by geniusit** [comment]
Thank you, it's what im looking for

**Comment by cescoffier** [comment]
The issue has been fixed upstream (in reactive messaging).
