### ISSUE TITLE
Remote-Dev triggers an entire redeployment(S2I Processor) with OpenShift Extension

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#14152]
**Describe the bug**
(Describe the problem clearly and concisely.)
Quarkus remote-dev always triggers an entire redeployment using the S2I processor rather than sending changed code when Quarkus application is deployed to OpenShift using OpenShift extension. This causes removing an existing environment variable(QUARKUS_LAUNCH_DEVMODE=true) in the DeploymentConfig so the remote-dev breaks. Furthermore, it takes quite a time to send changed code rather than using binary deployment.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Sending only changed code just like using binary build(i.e. oc new-build, oc start-build, oc new-app) when I do livecoding.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Rebuild an entire project via OpenShift extension then package it for redeployment. after that, the following error is happened when I try to live coding:

2021-01-04 15:46:29,661 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.io.IOException: Server did not start a remote dev session
at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.doConnect(HttpRemoteDevClient.java:128)
at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:169)
at java.base/java.lang.Thread.run(Thread.java:832)

2021-01-04 15:46:29,662 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connection failed after 10 retries, exiting

This seems to be caused by removing "QUARKUS_LAUNCH_DEVMODE=true".

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Use a getting-started project like helloword
2. Add an quarkus-openshift extension
3. Add the below configurations

**Configuration**
```properties
quarkus.package.type=mutable-jar
quarkus.live-reload.password=REPLACE_WITH_YOUR_PASSWORD
quarkus.live-reload.url=REPLACE_WITH_YOUR_ROUTE_URL
quarkus.container-image.build=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=openshift
quarkus.kubernetes.deploy=true
quarkus.openshift.expose=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: OpenJDK 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by danieloh30** [comment]
@iocanel @stuartwdouglas @geoand

**Comment by geoand** [comment]
@iocanel sounds like we should not be triggering deployment

**Comment by stuartwdouglas** [comment]
The workaround for this for now is to put the quarkus.openshift.deploy=true as a system property rather than in the config file, so it does not take effect when you run mvn quarkus:remote-dev.

I need to think about this a bit. The remote dev mode actually run in production mode locally, to generate new production application that mirrors the one on the server. The advantage of this is that server side is always fully up to date, so if the Quarkus process is stopped and restarted (or even restarted in production mode), then the code it still up to date.

**Comment by danieloh30** [comment]
@stuartwdouglas The workaround doesn't work for me. Here is what I added properties in application.properties:

quarkus.package.type=mutable-jar
quarkus.live-reload.password=fdnlafdslna
quarkus.container-image.build=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.expose=true

Then, I executed the following command to package and deploy the mutable app:
mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true

When the quarkus pod runs, I don't see that live coding is activated:
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-01-12 13:47:28,840 INFO  [io.quarkus] (main) quarkus-remote 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.10.5.Final) started in 0.577s. Listening on: http://0.0.0.0:8080
2021-01-12 13:47:28,859 INFO  [io.quarkus] (main) Profile prod activated.
2021-01-12 13:47:28,859 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy]

**Comment by stuartwdouglas** [comment]
Are you sure the URL you are pointing to is correct? You get that error if you attempt to open a session against a server that does not support remote dev.

**Comment by danieloh30** [comment]
Yeah, I'm pretty sure. Here is what I set the URL in the application.properties:
quarkus.live-reload.url=http://quarkus-remote-quarkus-remote.apps.cluster-boston-c079.boston-c079.sandbox1545.opentlc.com/hello-resteasy

You can access the URL now.

**Comment by stuartwdouglas** [comment]
It needs to be http://quarkus-remote-quarkus-remote.apps.cluster-boston-c079.boston-c079.sandbox1545.opentlc.com 

I should make this error handling better though

**Comment by stuartwdouglas** [comment]
That particular instance might be a bit broken, because I connected a random app to it and aborted half way through the update.

**Comment by danieloh30** [comment]
Ok. It works now. There are 2 concerns though.
1) If I keep the following configuration when I run remote-dev, it takes a long time to connect remote server since it seems to trigger S2I deployment once again like
```
2021-01-12 16:22:09,050 INFO  [io.qua.con.ima.ope.dep.OpenshiftProcessor] (build-19) Successfully pushed image-registry.openshift-image-registry.svc:5000/quarkus-remote/quarkus-remote@sha256:a4d2ef4fd0937747336bc02e056c82a97d2200062b4587f550805d6a0a8a79522021-01-12 16:22:09,050 INFO  [io.qua.con.ima.ope.dep.OpenshiftProcessor] (build-19) Successfully pushed image-registry.openshift-image-registry.svc:5000/quarkus-remote/quarkus-remote@sha256:a4d2ef4fd0937747336bc02e056c82a97d2200062b4587f550805d6a0a8a7952
```
2) I have set QUARKUS_LAUNCH_DEVMODE=true manually in DC once after I deployed the app via OpenShift extension. Is there a way to add this in application.properties with OpenShift extension?

**Comment by stuartwdouglas** [comment]
The linked PR should fix 1), the workaround is to make sure that the property that triggers the S2I build is not set in application.properties, only on the command line when you do the initial build.

For 2) I think you should be able to do: quarkus.kubernetes.env.vars.QUARKUS_LAUNCH_DEVMODE=true

If this works we should document it.

**Comment by danieloh30** [comment]
1) In the meantime, I will take the workaround as well as remove the following configuration to run the remote-dev:
```
quarkus.container-image.build=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.expose=true
```
2) It doesn't work for me:
```
mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true -Dquarkus.kubernetes.env.vars.QUARKUS_LAUNCH_DEVMODE=true
```

**Comment by geoand** [comment]
For 2, I think it needs to be:

```
quarkus.kubernetes.env-vars.quakus-launch-devmode.value=foobar
```

**Comment by danieloh30** [comment]
@geoand Should it be in application.properties or CLI?

**Comment by geoand** [comment]
It shouldn't matter

**Comment by danieloh30** [comment]
Just redeploy but both don't work for me.

```
quarkus.kubernetes.env-vars.quakus-launch-devmode.value=true
```

or

```
mvn clean package -DskipTests -Dquarkus.kubernetes.deploy=true -Dquarkus.kubernetes.env-vars.quakus-launch-devmode.value=true
```

**Comment by geoand** [comment]
Can you also try `quarkus.kubernetes.env.vars.quarkus-launch-devmode=value` please?

**Comment by geoand** [comment]
@metacosm https://quarkus.io/guides/kubernetes#environment-variables still show the old style of defining env vars, can you take a look please?

**Comment by metacosm** [comment]
Will do.

**Comment by danieloh30** [comment]
No luck with quarkus.kubernetes.env.vars.quarkus-launch-devmode=true

**Comment by danieloh30** [comment]
Ok. It works with ```quarkus.openshift.env-vars.quarkus-launch-devmode.value=true```

Thx for the help to fix it, @geoand
