### ISSUE TITLE
quarkus-smallrye-reactive-messaging-amqp: permit to use the schema 'amqps'

### ISSUE THREAD

**Issue by zhang-hongjie** [quarkusio/quarkus#14151]
**Description**
quarkus-smallrye-reactive-messaging-amqp: permit to use the schema `amqps`

**Implementation ideas**

**Comment by gsmet** [comment]
@cescoffier does it make sense to you or do we need more details?

**Comment by cescoffier** [comment]
I would need a bit more detail. Connection use host/port attributes. Is it about supporting an connection url?

**Comment by zhang-hongjie** [comment]
Hello, I have resolved this need by using the field "amqp-use-ssl: true". Thanks for your good job.
