### ISSUE TITLE
Type Map<String,String> in config root is not working

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#1415]
If I have a Map<String,String> in a config object such as:

```java
@ConfigRoot(name = "rt", phase = ConfigPhase.RUN_TIME)
public class TestRunTimeConfig {
    /** A map of properties */
    @ConfigItem
    public Map<String, String> stringMap;
...
```

With an application.properties configuration like:
```properties
# A root map of properties
quarkus.rt.string-map.key1=value1
quarkus.rt.string-map.key2=value2
quarkus.rt.string-map.key3=value3
```

The are no values populated into the stringMap.

**Comment by starksm64** [comment]
What currently happens is that processing goes into this ConfigDefintion#processMap(...) code block:

```java
        } else {
            // treat as a plain object, hope for the best
            // TODO, REVISIT THIS
            final ObjectConfigType leaf = new ObjectConfigType(NO_CONTAINING_NAME, mct, true, "", valueClass);
            //container.getConfigDefinition().getLeafPatterns().addPattern(subKey, leaf);
        }
```

and no leaf node ends up handling the configuration value.

**Comment by starksm64** [comment]
I think I have a straightforward fix for this

**Comment by starksm64** [comment]
It got a little more complicated when I got to the bytecode generation to load the config into runtime. Let me know if there are changes.

**Comment by dmlloyd** [comment]
I incorporated some of these changes and the tests into #1430.  If that one looks/works OK, merging it will auto-close this PR.
