### ISSUE TITLE
mvn add-extension in sub-module shouldn't add dependencyManagement

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14164]
I call mvn add-extension for a sub-module of a Maven multi-module project. This adds a dependencyManagement block to that module's POM with the Quarkus BOM, although that's already present in the parent. This also removes the reference to the parent POM (`<relativePath>../pom.xml</relativePath>` gets removed).

**Comment by famod** [comment]
Thanks for reporting!

I haven't reproduced it yet but looking at the code there does not seem to be a parent check.

Btw, `../pom.xml` is the default for `relativePath` and can thus be omitted. But I agree that the plugin should not mess with it.

I'll have a look in the next days.

/cc @aloubyansky

**Comment by aloubyansky** [comment]
@ia3andy fyi

**Comment by famod** [comment]
Should be fixed by the PR for #16264.

**Comment by aloubyansky** [comment]
This should be fixed by https://github.com/quarkusio/quarkus/pull/16290
