### ISSUE TITLE
quarkus-resteasy-mutiny Multi documentation

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#14178]
**Describe the bug**
I think the documentation is not very cleared on the fact that using Multi as a return type for jax-rs resources will be blocking if `@Produces` annotation does not use `text/event-stream`. Depending on the Multi producer, that can result in never ending requests (thus, I think, the issue #13988)

**Expected behavior**
Documentation should be clear on the fact that Multi ressource are blocking.

**Comment by jtama-op** [comment]
(Why can't I add documentation label)?

**Comment by cescoffier** [comment]
I always considered this as a bug in RestEasy (accumulating the publisher). @geoand / @FroMage how does that work in resteasy reactive?

**Comment by FroMage** [comment]
I don't know why it would be blocking. I don't think it blocks. It does accumulate, but it's still async.

**Comment by jtama-op** [comment]
It blocks the client...

**Comment by FroMage** [comment]
It depends if the client is async or not. It doesn't block async clients and they get data by chunks while streaming.

And no, `SseElementType` is only if you serialise over SSE. The streaming behaviour is raw HTTP streaming.

**Comment by geoand** [comment]
> I always considered this as a bug in RestEasy (accumulating the publisher). @geoand / @FroMage how does that work in resteasy reactive?

IIRC, the behavior in RESTEasy Reactive is to stream the result

**Comment by FroMage** [comment]
Indeed, since it's actually trivial to implement the "collect" use-case yourself, we didn't make the framework implement it. So you get either raw streaming (no annotation) or SSE streaming (with SSE `@Produces`).

**Comment by jtama-op** [comment]
Ok if this isn't considered worth documenting, this issue should be closed (though I still think a small word on that point would benefit developers)
