### ISSUE TITLE
Create a Hibernate Reactive Example

### ISSUE THREAD

**Issue by PedroEsnaola** [quarkusio/quarkus#14174]
**Description**

I spent the last day trying to find some documentation on the integration of hibernate reactive with Quarkus, but without success

**Implementation ideas**

Maybe add Reactive Example of config and use on the hibernate / panache Hibernate guide

**Comment by Sanne** [comment]
There are full examples among the Quickstarts:
 - https://github.com/quarkusio/quarkus-quickstarts/tree/master/hibernate-reactive-quickstart
 - https://github.com/quarkusio/quarkus-quickstarts/tree/master/hibernate-reactive-routes-quickstart

Good idea, someone should at very least link to these from the guide. Ideally include a walk-through.

**Comment by gavinking** [comment]
Indeed, we should even link to these from the HR docs.
