### ISSUE TITLE
Propose a `JaxRsResourceBuildItem` to deploy extension based JAX-RS resources

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#14182]
**Description**
I would like to develop en extension which gathers technical endpoint that should be re-usable on a set of projects (configuration exposition, metrics, thread dump, etc)

As for now, all the extension-based endpoints are supported by Vert.x Handlers (on the runtime part) and deployed via `RouteBuildItem`s (on the deployment part).

The Idea of the PR is to ease the extension development by providing the JAX-RS abstraction.

**Implementation ideas**
The Zulip discussion
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/exposing.20jaxrs.20resources.20via.20a.20quarkus.20extension

**Comment by danielpetisme** [comment]
After discussion with @geoand and @FroMage (feel free to complete if needed)

The objective can be achieved using `AdditionalBeanBuildItem` to register a custom JAX-RS resource.
```
@Path("/api")
public class HelloEndpoint {

    @GET
    @Path("/hello")
    public String getThreadDump() {
        return "Hello";
    }
}
```

```
@BuildStep
    public void createThreadDumpEndpoint(BuildProducer<AdditionalBeanBuildItem> beans) {
        beans.produce(new AdditionalBeanBuildItem(HelloEndpoint.class));
    }
```

However, the developer to keep in mind
1- Resteasy is a high-level abstraction and would work only in a Resteasy context. If the final application isn't using RESTEASY then Vert.X should be preferred because it's Quarkus core HTTP engine.
2- There is no easy way to configure "dynamically" the JAX-RS paths versus Vert.X which gives more control during the Route-Handler mapping configuration.

**Comment by mkouba** [comment]
I think that Vert.x route handlers are a more flexible and universal approach in Quarkus.

@danielpetisme Do you still want to keep this issue open?

**Comment by geoand** [comment]
> I think that Vert.x route handlers are a more flexible and universal approach in Quarkus

Definitely

**Comment by geoand** [comment]
Let's close this for now
