### ISSUE TITLE
Amazon Lambda - Extensions

### ISSUE THREAD

**Issue by oztimpower** [quarkusio/quarkus#14186]
Amazon Lambda added a new feature called "Extensions".
https://docs.aws.amazon.com/lambda/latest/dg/using-extensions.html

The Quarkus extension for Amazon Lambda will need to incorporate these URL calls into the native wrapper.

**Implementation ideas**

Sample go runtime, similar to the Quarkus native implementation:
https://github.com/glassechidna/serverlessish/blob/master/lambdaruntime/lambda_runtime.go

http://${AWS_LAMBDA_RUNTIME_API}/2020-01-01/extension/register"
req.Header.Set("Lambda-Extension-Name", name)
output.Identifier = resp.Header.Get("Lambda-Extension-Identifier")

http://${AWS_LAMBDA_RUNTIME_API}/2020-01-01/extension/event/next
req.Header.Set("Lambda-Extension-Identifier", identifier)

@patriot1burke

**Comment by patriot1burke** [comment]
Not grokking this at the moment.  From what I read external extensions are configured outside of code.  Internal extensions are just wrapper scripts, which we already do for native deployments.  Not sure how this overlaps with Quarkus.  Can you point to an example?  Are you saying you want to be able to write external extensions using quarkus and to hook into the event processing there?

**Comment by oztimpower** [comment]
It’s a new bootstrapping, that executes before the function is invoked, for shared code, such as monitoring or other common code. Like a layer in a container.

**Comment by patriot1burke** [comment]
> It’s a new bootstrapping, that executes before the function is invoked, for shared code, such as monitoring or other common code. Like a layer in a container.

I understand that, but how does it relate to Quarkus?  I didn't see any callback APIs.
