### ISSUE TITLE
Clarify use of Multi as return type in RESTEasy Reactive

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#14183]
**Description**
Currently RESTEasy Reactive always tries to "stream" a result when `Multi` is used a return type of Resource method.

This can be surprising in cases like the following:

```java
@Path("fruits")
@ApplicationScoped
@Produces("application/json")
@Consumes("application/json")
public class FruitMutinyResource {
    private static final Logger LOGGER = Logger.getLogger(FruitMutinyResource.class.getName());

    @Inject
    Mutiny.Session mutinySession;

    @GET
    public Multi<Fruit> get() {
        return mutinySession
                .createNamedQuery( "Fruits.findAll", Fruit.class ).getResults();
    }

}
```

where users expect to get a JSON array as a result, but instead end up with something like

```json
{"id":2,"name":"Apple"}{"id":3,"name":"Banana"}{"id":1,"name":"Pineapple"}
```

We have the following options:

* Keep things as they are (as in `Multi` always "streams") and expect users to collect the results to `Uni` (using `.collectItems().asList()` on the `Multi`)
* Have RESTEasy Reactive automatically collect the result to `Uni` when the media type of resource method does not support streaming (for example `application/json` does not stream). This may not be bullet-proof however as there is no spec mandate about which media types can and can't stream.

**Historical note**

The discussion that lead to this is [here](https://github.com/quarkusio/quarkus/issues/14183)

**Comment by FroMage** [comment]
Technically, we can stream json arrays too, as long as we start with `[` and separate them with `,` and end with `]`, with the `application/json` mime type: that's just raw HTTP streaming since the end result is a valid json value.

We could just do that and call it a day. Then it's up to the client to figure out if it wants to stream or not.

**Comment by cescoffier** [comment]
+1

If someone tells me how this should be done, I will be happy to implement it (well, reuse the code I wrote for reactive routes).

**Comment by FroMage** [comment]
https://github.com/quarkusio/quarkus/pull/14214 should fix this.

**Comment by cescoffier** [comment]
Shouldn't we close that issue? PR #14214 has been merged. 

@geoand @FroMage

**Comment by geoand** [comment]
Yes, let's close it
