### ISSUE TITLE
Issues trying to make my extension show in the Dev Console

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#14199]
First of all, thanks for the great work that is being invested into Quarkus.
I am very excited about Dev Console (https://github.com/quarkusio/quarkus/pull/13899) therefore I wanted to make [my extension](https://github.com/quarkiverse/quarkiverse-logging-manager) support it.
Unfortunately I am not able to do so, I will report some issues I found along the way that prevented me from achieving my goal. I understand this is a work in progress, but I am reporting my experience because I imagine this is the kind of feedback expected in CR versions.

1. [The documentation](https://quarkusio-quarkusio-github-io-preview-pr-815.surge.sh/guides/dev-console) says that 
```In order to make your extension listed in the DEV Console you don’t need to do anything!```
However, this was not my experience. Building my extension against Quarkus 999-SNAPSHOT (or 1.11.0.CR1) does not list my extension in the console

2. Adding an empty `embedded.html` makes my extension be shown as a "tile" in the console
3. The example provided in the documentation breaks the console layout:
This is what the docs say:
```
The contents of this file will be included in your extension card, so for example we can place two links with some styling and icons:

<a href="/q/openapi" class="badge badge-light">
  <svg … ></svg>
  OpenAPI</a>
<a href="/q/swagger-ui/" class="badge badge-light">
  <svg … ></svg>
  Swagger UI</a>
```
So I coped this content and pasted it in the html file. This completely broke the dev console layout: 
![image](https://user-images.githubusercontent.com/3311764/104051174-7a2bd700-51c6-11eb-9da7-257b95d88e14.png)

In order to have a "uniform" tile layout, I went picking in the [cache extension code](https://github.com/quarkusio/quarkus/blob/1.11.0.CR1/extensions/cache/deployment/src/main/resources/dev-templates/embedded.html).

~~5. Wrong title in the "tile":~~
~~With an empty html or with one based on the cache extension, I have the following effect: the title of my extension tile is `Quarkus - Logging UI - Runtime`, while I expect it to be `Logging UI`.~~

~~6. Wrong description in the tile:~~
~~In the same scenario, the description is: `Parent POM for Quarkiverse projects that includes the default release and artifact publishing related configuration`. I cannot find this string in my project, so I do not have any idea where this comes from.~~

~~Result: ![image](https://user-images.githubusercontent.com/3311764/104051014-3933c280-51c6-11eb-82ea-f293977c001c.png)~~

~~These last 2 issues made me stop the effort for the moment, because they will prevent me from having a meaningful tile for my extension.~~
(I just found out that this info comes from pom `name` and `description` entries for the runtime project. So I adjusted them and issues 5 and 6 are working now)

7. `DevConsoleRuntimeTemplateInfoBuildItem` not resolvable
The docs say 
```
In both cases we advise that you add support for the DEV Console in your {pkg}.deployment.devconsole package in a DevConsoleProcessor class (in your extension’s deployment module).
```
But I am trying to add it and my IDE cannot resolve `io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem;`.
I looked at the [cache extension PR](https://github.com/quarkusio/quarkus/commit/3e9763d748a1fc4a76da944906d2925c9e5495d0) and there were only two new dependencies added, which are already in my project. I also noticed that the references class is in the quarkus main project. But my quarkiverse project ist not able to resolve it.

To solve this, I hgave to add the following dependency:
```
 <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-vertx-http-dev-console-spi</artifactId>
    <version>1.11.0.CR1</version>
</dependency>
```
This could be mentioned in the doc

Extra information: Is it possible that this is because my extension is a quarkiverse extension?~~

Thanks

**Comment by geoand** [comment]
There have been a lot of changes in Quarkus DevUI so this might have already been fixed.

Can you give it a shot with the latest versions of Quarkus?

**Comment by oscarfh** [comment]
I am pretty busy, I cannot promise you that. I would propose that we close it and I open a new ticket if I have a similar issue.
WDYT?

**Comment by geoand** [comment]
Sure, makes sense
