### ISSUE TITLE
Invalid WARN Log level DEBUG for category 'X' set below minimum logging level INFO, promoting it to INFO

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#14196]
**Describe the bug**
If I set a category to level `DEBUG`, the level is not applied, and the following warning is printed:
```
Log level DEBUG for category 'io.quarkus.vault' set below minimum logging level INFO, promoting it to INFO
```
This is new behavior in Quarkus 11 CR1. 
10.0.5 did not do this.

**Expected behavior**
Same as 10.0.5: `DEBUG` level gets applied.

**Actual behavior**
Invalid warning is printed, and `DEBUG` level is not applied.

**To Reproduce**

1. Activate log with level `DEBUG` on a specific category

**Configuration**
```properties
quarkus:
  log:
    category:
      "io.quarkus.vault":
        level: DEBUG
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 11 CR1

**Additional context**
This has happened on my business application.
I did not try on a `getting-started` example.

**Comment by gsmet** [comment]
You also need to set the `min-level` now.

**Comment by vsevel** [comment]
yes I can see that in the documentation in master. this will be clearer when the doc is updated on the website. thanks.
