### ISSUE TITLE
DEV Console: Add a list of endpoint page to RESTEasy Reactive extension

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#14195]
We currently have a [DEV Console](https://quarkusio-quarkusio-github-io-preview-pr-815.surge.sh/guides/dev-console) for the [RESTEasy Reactive](https://quarkusio-quarkusio-github-io-preview-pr-813.surge.sh/guides/resteasy-reactive) extension with two entries:

- One that lists the REST endpoint scores
- One that points to our `/404` page to list endpoints and their parameters

But the 404 page is all red and ugly and super hard to maintain. I would like to have a nicer looking version easier to maintain, written in [Qute](https://quarkus.io/guides/qute) instead.

This is going to be a progressive job, because it's not trivial, so my advice is:

- Go to https://code.quarkus.io/ and generate a sample application with the `resteasy-reactive` and `qute` extensions
- Download the application and import it in your IDE
- Start the application in "DEV mode": `mvn clean quarkus:dev`
- Visit it at http://localhost:8080
- Add a few REST endpoints for fun
- Add at least one endpoint that [returns a Qute template](https://quarkus.io/guides/qute#type-safe-templates) and try to pass it some values and try the [Qute syntax](https://quarkus.io/guides/qute-reference)
- Visit the DEV Console at http://localhost:8080/q/dev and check out the RESTEasy Reactive enties, in particular the `/404` one
- When you feel up for it, import the `quarkus-resteasy-reactive-deployment` and `quarkus-resteasy-reactive` extensions in your IDE
- Check out the `extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/resources/dev-templates` templates and how they relate to what you observed at the DEV Console
- Modify `embedded.html` and add a link to a new file next to it called `endpoints.html`
- Recompile that module: `mvn -f extensions/resteasy-reactive/quarkus-resteasy-reactive clean install` (Note that this assumes you already built a full Quarkus before)
- Make your application use the `999-SNAPSHOT` version of Quarkus (modify the `pom.xml` `properties` to use that version), so that it will use the Quarkus version you've just built
- Restart your sample application and observe the results in the DEV Console `/q/dev` page

**Comment by FroMage** [comment]
Note that this is for @SaumyaSingh1 but I haven't figured out how to assign it to her yet. Just don't take it away from her ;)

**Comment by geoand** [comment]
@FroMage if she comments on the issue, then you can assign her :)

**Comment by FroMage** [comment]
Aha! Thanks!

**Comment by SaumyaSingh1** [comment]
Hey @FroMage , you can assign me : )

**Comment by FroMage** [comment]
So I should have been more clear that this is not over yet because we still need to implement the `endpoints.html` file, to make it show as much of the useful info of the 404 page as possible, for example:

![Screenshot from 2021-01-14 10-18-59](https://user-images.githubusercontent.com/179265/104570443-3582be80-5652-11eb-9b4b-51e643e72b8f.png)

Here we can see that the 404 page shows HTTP method, path, consumes/produces mime types and that's pretty much it. And below it shows additional endpoints declared by build items. We will do the latter last, so let's start with the former.

In theory all you have to do is remove some information from the current `endpoints.html` since it's based on `scores.html` so you can see which info to remove.

Note that we want to make it look better than the 404, so keep the current styling, don't try to emulate the 404 page one :)

**Comment by FroMage** [comment]
Ideally it would be nice if the endpoints were listed alphabetically by URL, and if they are equal, by HTTP method alphabetically.

**Comment by FroMage** [comment]
Notice that the 404 page lists endpoints in a hierarchical manner for some internal implementation reason that I don't agree with, and that the DEV console should not emulate, as shown by the equivalent `/scores` page:

![Screenshot from 2021-01-14 10-25-18](https://user-images.githubusercontent.com/179265/104571088-fe60dd00-5652-11eb-92e2-e9955c39cbb7.png)

**Comment by SaumyaSingh1** [comment]
@FroMage after adding `REST resources` , I need some hints for `Static Resources` and `Additional endpoints` categories.

**Comment by SaumyaSingh1** [comment]
> I've reviewed your PR. Do you want to merge it and do another PR for further improvements or keep working on it?

Umm yes whatever seems good to you :) 

For further improvements opening up new PR will be good I think ?

**Comment by FroMage** [comment]
So let's forget static resources for now and focus on "additional enpoints". The way the Quarkus build-time processors pass this on to the 404 page is in `ResteasyReactiveDevModeProcessor` in `extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment`:

```java

    @Record(STATIC_INIT)
    @BuildStep(onlyIf = IsDevelopment.class)
    void addAdditionalEndpointsExceptionMapper(List<NotFoundPageDisplayableEndpointBuildItem> displayableEndpoints,
            ExceptionMapperRecorder recorder, HttpRootPathBuildItem httpRoot) {
        List<AdditionalRouteDescription> endpoints = displayableEndpoints
                .stream()
                .map(v -> new AdditionalRouteDescription(v.getEndpoint(), v.getDescription()))
                .sorted()
                .collect(Collectors.toList());

        recorder.setAdditionalEndpoints(endpoints);
    }
```

This essentially says that at build time, this function will get invoked by Quarkus, with `List<NotFoundPageDisplayableEndpointBuildItem>` listing all the declared "additional endpoints" as a build item, and then the function stores it in a `static` variable for later use.

If we want to make this visible to our `endpoints.html` page, we need to collect the same build items in `io.quarkus.resteasy.reactive.server.deployment.devconsole.DevConsoleProcessor` (same extension) to create a new `DevConsoleRuntimeTemplateInfoBuildItem` based on the `List<NotFoundPageDisplayableEndpointBuildItem>` we will collect, and give it a name. From then on, you will be able to access that value in your `endpoints.html` template.

Let me know if you have any question or run into trouble. This is the build-time API of Quarkus, so it can be scary, but we mostly work on it by copying other `@BuildStep` similar methods and modify them to our needs, which is less daunting than going through the rather long documentation, but feel free to read it if you prefer:

https://quarkus.io/guides/building-my-first-extension
https://quarkus.io/guides/writing-extensions
https://quarkus.io/guides/all-builditems

**Comment by SaumyaSingh1** [comment]
ok sure Stef, I will start working on it now :) 
In case I will get stuck will ping on Zulip.

**Comment by FroMage** [comment]
Now _now_, surely, it's way past working hours in your time zone :)

**Comment by SaumyaSingh1** [comment]
oh you noticed this Stef :) 
alright then on next day

**Comment by FroMage** [comment]
OK, so the next step is now to add links to static resources. You can start by copying the 404 page's approach to those, by collecting them from the same source as the 404 page (see `ResteasyReactiveDevModeProcessor` in `quarkus-resteasy-reactive-deployment`):

```java
    @Record(STATIC_INIT)
    @BuildStep(onlyIf = IsDevelopment.class)
    void addStaticResourcesExceptionMapper(ApplicationArchivesBuildItem applicationArchivesBuildItem,
            ExceptionMapperRecorder recorder) {
        recorder.setStaticResourceRoots(applicationArchivesBuildItem.getAllApplicationArchives().stream()
                .map(i -> i.getChildPath(META_INF_RESOURCES))
                .filter(Objects::nonNull)
                .map(p -> p.toAbsolutePath().toString())
                .collect(Collectors.toSet()));
    }
```

But ultimately I think that approach only works for really small amount of static resources and doesn't let me explore folders.

So an iterative approach to fixing this would be to first start by listing all resources. Then only list toplevel resources and distinguish folders from files. Then adding a new DEV Console (it's now called "Dev UI", BTW)  page for listing resources in a folder, recursively and link from the current `endpoints.html` page to this page. But that can come last.

**Comment by SaumyaSingh1** [comment]
Alright, so as per my understanding in order to show `static resources` on the `endpoints.html` template , we have two ways.

1. **This one works for really small amount of static resources , does not allow to explore folders**  , **so we will avoid this/not use** ?
      _This is similar to what was done for `additional endpoint`, collecting  info from `ResteasyReactiveDevModeProcessor` into 
      `DevConsoleProcessor` & accessing into endpoints.html template._

2. This second iterative approach overcomes the limitation in point 1, we are going to use this ?
    
     @FroMage

**Comment by SaumyaSingh1** [comment]
Also , from the `@404` page , I noticed for my app in static resource category only 1 file was there `index.html`. I guess that needs to be clickable and on clicking we will be directed to `index.html` page ? 🤔 

Here is the saved ss- 

![image](https://user-images.githubusercontent.com/46818757/105328521-22459500-5bf6-11eb-8e9e-c88eacc544ee.png)

**Comment by FroMage** [comment]
Yes, let's make it iteratively and start with the same sort of display as the 404, not collapsing entries into folders, and extend it later.

But yeah, it needs to be clickable and send the user to the resource in question.

**Comment by SaumyaSingh1** [comment]
ok so in the iterative approach workflow will be :

- Start with listing all resources in `DevconsoleProcessor` (?)         
- List toplevel resources & distinguish folders from files again in (?)`DevconsoleProcessor` 
- Add a new DEV Console page (umm means a new template in `dev-templates` folder like endpoint.html ? )  
- Linking to endpoint template

**Comment by FroMage** [comment]
Yes

**Comment by SaumyaSingh1** [comment]
And for listing the resources in `DevconsoleProcessor` , as a reference  I will be looking at `ResteasyReactiveDevModeProcessor`. 
Also I will be using `DevConsoleTemplateInfoBuildItem`.
Right ?

**Comment by FroMage** [comment]
Yes.

**Comment by FroMage** [comment]
OK, so the next step is that I'd really like to have static resources shown in a hierarchical manner. For example, given the following structure of static resources:

![Screenshot from 2021-01-26 17-51-53](https://user-images.githubusercontent.com/179265/105876459-4bec2b00-5fff-11eb-9472-695bacf38428.png)

I'd like the endpoint page to only list the following static resources:

- `images` (with a folder icon)
- `javascript` (with a folder icon)
- `index.html` (with a file icon)

The `index.html` would link to the resource itself (as it does right now).
The folder items would link to a new page called perhaps `static-resource.html` and pass it a query parameter which would indicate which folder we're displaying, like `static-resource.html?folder=images`, and that page would then display only the following static resources:

- `icon.png` (with a file icon)

And similarly for every other folder.

I can provide more detailed steps and instructions, if you want, or if you prefer I can let you try it and only ask if you run into blockers? Let me know.

**Comment by SaumyaSingh1** [comment]
For this I will be probably modifying the `DevConsoleProcessor` inside `quarkus-resteay`  🤔 
well yes few hints will help better, else I will end up reading all the files inside `quarkus-resteasy-reactive` :P

**Comment by FroMage** [comment]
My apologies, I've made some progress in coming up with instructions, but it doesn't look like I'll be able to produce them today given the meetings I still have scheduled. I'll try my best to have them tomorrow, really sorry.

**Comment by SaumyaSingh1** [comment]
It's completely alright, no problem :)

**Comment by FroMage** [comment]
OK, sorry about that I wanted to make sure you'd have all the pieces.

You should start your branch on top of this branch: https://github.com/FroMage/quarkus/tree/dev-ui-static-resources because it has commits you will need.

My advice is that you start in `DevConsoleProcessor.collectStaticResourcesInfo()` and change the static resources from a `Set` to a new structure called `StaticResourceInfo`, in which you will store a map of resource paths (relative to the resource folders) to a new type `StaticResourceInfo.StaticFile`.

That `StaticFile` should have a name (last part only), a boolean to know if it's a folder, and a collection of `StaticFile` for its children. I'll let you pick the right data structure for the collection, but if you make `StaticFile` implement `Comparable` you can make them sorted like we want: folders first, alphabetically in both cases.

Then you'll need to change `collectKnownPaths` to build those items and fill the map. For that you will need to implement `preVisitDirectory` and `postVisitDirectory` as well. Basically in pre-visit you will check the relative path of the directory, see if you already have a mapping for it in your map of resource paths, and if not create a new `StaticFile` for the directory and save it in your map.

Then you'll need to remember you're visiting this folder, so that in `visitFile` you can create the `StaticFile` and add it to that folder's `children`.

And in post-visit you need to return back to the previous folder you were visiting. That's a hint as to what data structure you need to maintain that state in pre/post ;)

As for the viewing, you can then change `endpoints.html` to obtain the collection of static files for `/` (the root of all resources), and iterate them to display them. If they're files: link to the file itself. If they're directories, link to `view?path=...` with the relative path to the resource folder.

Then you can add a `view.html` flie which does the same as the `endpoints.html` when it comes to listing the static resources part, except that instead of using `/` for the children, you can access the `path` query parameter by obtaining it from the current request with `{currentRequest.params.get("path")}`.

I hope this is enough to occupy you, let me know if you have any questions :)

**Comment by FroMage** [comment]
Pretty sure this is done.
