### ISSUE TITLE
Resteasy-reactive fails to start with fast-jar and logging-json

### ISSUE THREAD

**Issue by kwakiutlCS** [quarkusio/quarkus#14202]
**Describe the bug**
The application fails to start, after building an image with type fast-jar, logging-json extension and the extension resteasy-reactive.

**To Reproduce**
Link to project which reproduces the issue https://github.com/kwakiutlCS/fictional-eureka
1. create a quickstart Installed features: [cdi, resteasy]
2. add extensions logging-json, container-image-docker
3. change quarkus version to 1.11.0.CR1, change resteasy to resteasy-reactive (artifact-id needs to change to quarkus-bom?)
4. change package type to fast-jar
5. build image and run container
6. error shows
ERROR: Failed to start application (with profile prod)
java.lang.ClassNotFoundException: javax.json.Json
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.jboss.logmanager.formatters.JsonFormatter.<init>(JsonFormatter.java:60)
	at io.quarkus.logging.json.runtime.LoggingJsonRecorder.initializeJsonLogging(LoggingJsonRecorder.java:17)

**Environment:**
 - Output of `uname -a` or `ver`:  Linux element 4.19.0-8-amd64 # 1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
 - Output of `java -version`: 
 openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
 - Quarkus version or git rev: 1.11.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): maven 3.6.3

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14203 fixes the issue.

For the record this isn't RESTEasy Reactive specific, it also happens when RESTEasy classic was used (basically anytime `logging-json` was used with `fast-jar`)

**Comment by geoand** [comment]
Fixes by  https://github.com/quarkusio/quarkus/pull/14203
