### ISSUE TITLE
Keycloak Admin Client in QuarkusTest*Callback

### ISSUE THREAD

**Issue by Vinche59** [quarkusio/quarkus#14204]
**Describe the bug**
First of all, I'm not really sure if it's a bug or me who does not understand how QuarkusTest Callbacks work.
I try to reset Keycloak Server environment between each of my test methods using **QuarkusTestAfterEachCallback** but as soon as I try to manipulate **org.keycloak.admin.client.Keycloak** instance inside **afterEach** Method I get an InvocationTargetException like the following :

`Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.<init>(java.lang.Class, javax.ws.rs.client.WebTarget)
Caused by: java.lang.NoSuchMethodException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.<init>(java.lang.Class, javax.ws.rs.client.WebTarget)`

It looks like a classloader issue but I'm out of idea how include this missing method.

**To Reproduce**

A small reproducer can be found there : https://github.com/Vinche59/test-callbacks

1. mvn test

**Comment by famod** [comment]
Have you tried `org.junit.jupiter.api.extension.AfterEachCallback` instead?

**Comment by Vinche59** [comment]
Hi,

Thank you for the quick fix. I confirm that resolves the problem for my use case.

Do you think it's possible to incorporate that commit into the upcoming 1.11 release ?
Or should I wait for the 1.12 one ?

Thanks again.

**Comment by famod** [comment]
@Vinche59 The backport label was added to the PR by @geoand so it will most likely be backported to 1.11.

**Comment by Vinche59** [comment]
> @Vinche59 The backport label was added to the PR by @geoand so it will most likely be backported to 1.11.

@famod Oups, yeah sorry I missed that... (I only saw 1.12 milestone set by quarkus-bot).

Thanks again to all of you for your great work and support.

**Comment by geoand** [comment]
Hey folks,

The fix will be backported to 1.11.0.Final
