### ISSUE TITLE
Docker run results in failure

### ISSUE THREAD

**Issue by sshaaf** [quarkusio/quarkus#14206]
**Describe the bug**
running the jar locally works, devmode works, however after building with the default docker.jvm the container throws a stack trace. I have used the default project from code.quarkus.io to test this out.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Should be able to run the docker container. 
docker run -i --rm -p 8080:8080 quarkus/quarkus-test-jvm

**Actual behavior**
build trace: 
[docker-build.log](https://github.com/quarkusio/quarkus/files/5791986/docker-build.log)

Run trace as follows:
~/d/quarkus-test » docker run -i --rm -p 8080:8080 quarkus/quarkus-test-jvm                                                                                                       00:35:12
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
Jan 09, 2021 11:35:14 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.lang.ClassNotFoundException: org.jboss.threads.JBossThreadFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.runtime.ExecutorRecorder.createExecutor(ExecutorRecorder.java:158)
        at io.quarkus.runtime.ExecutorRecorder.setupRunTime(ExecutorRecorder.java:43)
        at io.quarkus.deployment.steps.ThreadPoolSetup$createExecutor-168269452.deploy_0(ThreadPoolSetup$createExecutor-168269452.zig:92)
        at io.quarkus.deployment.steps.ThreadPoolSetup$createExecutor-168269452.deploy(ThreadPoolSetup$createExecutor-168269452.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:400)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

**To Reproduce**
Reporducer attached: 
[quarkus-test.tar.gz](https://github.com/quarkusio/quarkus/files/5791989/quarkus-test.tar.gz)

1. mvn clean compile package 
2. build docker image
3. run docker image

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux local 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

 - GraalVM version (if different from Java): graalvm-ce-java11-20.2.0
 - Quarkus version or git rev: 
 ```
   <properties>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <maven.compiler.target>11</maven.compiler.target>
    <quarkus.platform.version>1.10.5.Final</quarkus.platform.version>
    <maven.compiler.source>11</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <quarkus-plugin.version>1.10.5.Final</quarkus-plugin.version>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
  </properties>
  ```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
apache-maven-3.6.3
**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
I just tested this out locally and it works fine for me. Does it work if you run the app without docker?

**Comment by geoand** [comment]
Worked for me as well. Do you have a reproducer project to share?

**Comment by sshaaf** [comment]
Doesnt work on my linux box. but works fine on mac.

**Comment by geoand** [comment]
I tried your example @sshaaf and I couldn't reproduce the problem

**Comment by sshaaf** [comment]
i'll close this issue. and thanks for looking into it.. I'll look further into my own environment.

**Comment by geoand** [comment]
👍🏼

**Comment by sshaaf** [comment]
just to document this. the issue was with my local storage not able to write files or save them randomly.
