### ISSUE TITLE
Windows - ? instead of codestarts icons when generating project

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14219]
Running https://quarkus.io/guides/getting-started#bootstrapping-the-project on Windows 10

There are ? instead of codestarts icons when generating project, tried with cmd and poweshell

![Screenshot 2021-01-11 11 20 08](https://user-images.githubusercontent.com/925259/104171584-265a0180-5403-11eb-90c5-e09bcf763d30.png)

![Screenshot 2021-01-11 11 21 35](https://user-images.githubusercontent.com/925259/104171593-29ed8880-5403-11eb-9c9e-ef1be40e5b04.png)

Expected to see something like this:
![Screenshot 2021-01-11 at 11 50 53](https://user-images.githubusercontent.com/925259/104171712-5b665400-5403-11eb-99c5-c6df46978826.png)

**Comment by ia3andy** [comment]
@rsvoboda I believe that unicode is not by default on PowerShell, could you try what's suggested in that answer?
https://stackoverflow.com/a/49481797

If this solution works, I don't know if we should switch to bullets for Windows or keep it and let the user enable it or not?

**Comment by rsvoboda** [comment]
I tried https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096 but without luck

A) My old Windows 10 machine without service packs installed - I don't even have that `set the system locale (language for non-Unicode programs) to UTF-8` option available
b) My wife's Windows 10 machine - settings is available, selected it, restarted the system but still see `?`, tried with both `cmd` and `powershell`

**Comment by ia3andy** [comment]
Ok, so we need a patch to use bullets on Windows systems.

**Comment by imshuv** [comment]
I want to work on this ,I would be extremely thankful if someone could guide me on how to get started with this?

**Comment by ejba** [comment]
Someone corrects me if I am wrong.

* Jump to independent-projects/tools/codestarts/src/main/java/io/quarkus/devtools/codestarts/core/CodestartProjectGeneration.java 
* Refactor L51 with the following algorithm: 
  - Get OS name (e.g.`System.getProperty("os.name")`) 
  - if the name contains **"win"** then use bullets, otherwise use `CodestartType.getIcon()`

**Comment by ia3andy** [comment]
@ejba that's right! We should also find a fix where those icons are used too: https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/message-writer/src/main/java/io/quarkus/devtools/messagewriter/MessageIcons.java
