### ISSUE TITLE
Regression: Redirect for non-application root path does not consider root path correctly

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#14216]
**Describe the bug**
I have an application where I have configured a non-standard root path using `quarkus.http.root-path=/foo`. As of Quarkus 1.11 which introduces the non-application root path (defaulting to `/q`) I now need to go to http://localhost:8080/foo/q/swagger-ui/ to get to the Swagger UI. This makes sense. But there is also a redirect in place for http://localhost:8080/foo/q/swagger-ui/. Unfortunately this redirect is wrong as it redirects to http://localhost:8080/q/foo/swagger-ui/.

The same problem also applies to `quarkus.smallrye-openapi.path`.

**Expected behavior**
The redirect URL for the Swagger UI (and the OpenAPI definition) should correctly consider the HTTP root path.

**Actual behavior**
See bug description.

**To Reproduce**
Create a minimal application which includes the OpenAPI extension and configures a non-standard `quarkus.http.root-path`.

**Configuration**
```properties
quarkus.http.root-path=/foo
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
Looking at it ....

**Comment by phillip-kruger** [comment]
@knutwannheden - if you go to a url that does not exist, eg localhost:8080/asd you should see the Not Found page, what is the URL's for the above there ?

**Comment by knutwannheden** [comment]
@phillip-kruger I would have to go to localhost:8080/foo/bar to get the Not Found page, but since I also have an `@ApplicationPath` annotation I in fact have to go to localhost:8080/foo/rest/bar to get that.

On the Not Found page the link text shows up as /foo/swagger-ui/ and the link URL matches that. But it redirects to /q/foo/swagger-ui/.

**Comment by knutwannheden** [comment]
I am also unsure which URL is correct. Should it be `/<root-path>/<non-application-root-path/swagger-ui` or just `/<non-application-root-path/swagger-ui`?

**Comment by phillip-kruger** [comment]
I would think `/<root-path>/<non-application-root-path/swagger-ui` - @kenfinnigan ?

**Comment by knutwannheden** [comment]
That is also what I was expecting.

As a workaround I tried setting `quarkus.http.non-application.root-path` to `/`. I was then able to access the Swagger UI using `/foo/swagger-ui`. But the Swagger UI failed to load my `swagger.json` (I have also set `quarkus.smallrye-openapi.path` to `/swagger.json`) with an error "Fetch error Not Found /swagger.json".

When I instead set `quarkus.http.non-application.root-path` to `${quarkus.http.root-path}`, the Swagger UI is available under `/foo/foo/swagger-ui` and the OpenAPI definition `swagger.json` loads correctly. But this isn't quite what I want.

Let me know if you want me to report a separate issue for this problem.

**Comment by kenfinnigan** [comment]
I think this is the same issue that was fixed in https://github.com/quarkusio/quarkus/pull/14133

If you're using 1.11.CR1 the fix isn't present, but it will be for 1.11

@phillip-kruger is correct as to what the appropriate path structure should be

**Comment by phillip-kruger** [comment]
Thanks @kenfinnigan - I can not replicate the behaviour as described by @knutwannheden when using master, however, there is an issue with the opeapi path set by swagger-ui when the root path is set, that I will fix a.s.a.p.

**Comment by knutwannheden** [comment]
@kenfinnigan and @phillip-kruger Thanks for looking into this!

Do you expect the fix #14133 be backported for 1.11.0.Final?

**Comment by kenfinnigan** [comment]
It's marked for backport triage so should be
