### ISSUE TITLE
Cannot build and deploy AWS Lambda with SAM (missing ApplicationImpl)

### ISSUE THREAD

**Issue by 0x4a616e** [quarkusio/quarkus#14224]
**Describe the bug**
Disclaimer: I'm not sure if this is a bug or a feature request

I'm using `sam build` and `sam deploy` to build and deploy quarkus based AWS lambda functions.

Invoking `sam build` automatically triggers a maven build on all lambda functions and copies compiled sources to `.aws-sam/build/FunctionName`.

The problem here is that `quarkus-maven-plugin` is generating a `function.zip` containing all required classes, but this file is _not_ used by `sam build`. Instead, sam copies compiled sources from the `target` directory as it is unaware of `quarkus-maven-plugin`.

Unfortunately, `ApplicationImpl` is only added to `function.zip` and not to the compiled classes in the `target` directory. Thus, sam misses this file resulting in a `ClassNotFoundException` on deployment.

Sam templates generated by quarkus seem to work around this issue by setting `CodeUri: build/function.zip` but this is not supported for `sam build` as `CodeUri` has to be a directory.

Unfortunately, i could not find any way to make sam use the `function.zip` file compiled by `quarkus-maven-plugin`, so currently my only workaround is manually unzipping the `function.zip` into the respective folder below `.aws-sam/build/`.

Maybe it could be a solution to use a parameterized `CodeUri` and use the project directory for `sam build` and the compiled `function.zip` for `sam deploy`, but it would be really nice if there would be a simpler solution.

Hope this is clear, thanks for looking into this!

**Expected behavior**
ApplicationImpl added to compiled classes in `target` directory

**Actual behavior**
ApplicationImpl only added to `function.zip`

**Comment by patriot1burke** [comment]
We can't you "sam deploy" the function.zip generated by the build?  Why do you have to use "sam build"?

**Comment by 0x4a616e** [comment]
I have a couple of lambda functions using different runtimes. `sam build` builds all of them automatically and prepares the deployment data. Of course, a solution would be to create some script to manually compile all functions using their respective compilers, copy compiled sources if necessary and not use `sam build` at all. However sam build is already there and works quite well for everything except quarkus... Thus I was hoping to somehow make it work.
