### ISSUE TITLE
Log regression in 1.11.0.CR1 with native build and yaml configuration

### ISSUE THREAD

**Issue by matthyx** [quarkusio/quarkus#14229]
**Describe the bug**
Log level isn't set using the following snippet:
```
Logger log = Logger.getLogger(GreetingResource.class);

log.debug("hello debug");
log.info("hello info");
```
Please note this is a regression in 1.11.0.CR1 compared to 1.10.5.Final.

**Expected behavior**
Logging in DEBUG should be shown in the application output with both builds.

**Actual behavior**
Only INFO level is shown in native whereas both are with jvm build.

**To Reproduce**
I have setup a public repo (https://github.com/matthyx/quarkus-getting-started) with 2 branches containing the same example in both versions.

1. git clone https://github.com/matthyx/quarkus-getting-started.git
2. ./mvnw package
3. ./mvnw package -Pnative -Dquarkus.native.container-build=true
4. cd mytest
5. ../target/getting-started-1.0.0-SNAPSHOT-runner
6. (separate terminal) curl http://127.0.0.1:8080/hello
7. java -jar ../target/getting-started-1.0.0-SNAPSHOT-runner.jar
8. (separate terminal) curl http://127.0.0.1:8080/hello

**Configuration**
```properties
# src/main/resources/application.yml
quarkus:
  log:
    min-level: DEBUG
```
```properties
# config/application.yml
quarkus:
  http:
    port: 18080
  log:
    category:
      "org.acme.getting.started":
        level: TRACE
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux parrot 5.9.0-2parrot1-amd64 #1 SMP Debian 5.9.6-2parrot1 (2020-11-17) x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1) OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1, mixed mode, sharing)
 - GraalVM version (if different from Java): quay.io/quarkus/ubi-quarkus-native-image   20.3.0-java11
 - Quarkus version or git rev: 1.11.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by matthyx** [comment]
cc @vsevel

**Comment by gsmet** [comment]
Yeah, you also need to set the build time `min-level` configuration property now.

**Comment by vsevel** [comment]
hi @gsmet, well we did
it is happening on the native executable mode only. jvm mode works as expected.

**Comment by sberyozkin** [comment]
Not sure if it is related but `integration-tests/bouncycastle-jsse` can not capture all the expected TLS log records in the native mode only, jvm mode is fine

**Comment by gsmet** [comment]
/cc @galderz looks like we have issues with `min-level` in native?

Could you check the reproducer?

(I'm supposed to release 1.11 tomorrow morning so this is high priority)

**Comment by geoand** [comment]
Using the supplied reproducer, I can't see the debug messages in JVM mode either

**Comment by matthyx** [comment]
> Using the supplied reproducer, I can't see the debug messages in JVM mode either

Do you mean you don't see neither "hello debut" nor "hello info" when doing the curl?

**Comment by geoand** [comment]
I only see `hello info`

**Comment by matthyx** [comment]
This is what I have in jvm mode:
```
$java -jar ../target/getting-started-1.0.0-SNAPSHOT-runner.jar 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-01-12 11:15:11,779 WARN  [io.qua.run.log.LoggingSetupRecorder] (main) Log level TRACE for category 'org.acme.getting.started' set below minimum logging level DEBUG, promoting it to DEBUG
2021-01-12 11:15:12,048 INFO  [io.quarkus] (main) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.11.0.CR1) started in 0.859s. Listening on: http://0.0.0.0:18080
2021-01-12 11:15:12,049 INFO  [io.quarkus] (main) Profile prod activated. 
2021-01-12 11:15:12,049 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, resteasy]
2021-01-12 11:15:19,773 DEBUG [org.acm.get.sta.GreetingResource] (executor-thread-1) hello debug
2021-01-12 11:15:19,774 INFO  [org.acm.get.sta.GreetingResource] (executor-thread-1) hello info
```

**Comment by matthyx** [comment]
> I only see `hello info` in both JVM and native modes

Do you run your jar from the `mytest` dir that contains the config?

**Comment by geoand** [comment]
Ah, I didn't see that

**Comment by galderz** [comment]
I've replicated the issue, looking into it.

**Comment by matthyx** [comment]
Thanks folks!

**Comment by vsevel** [comment]
well done!
