### ISSUE TITLE
Spring DI guide - ideas for enhancements

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14221]
I was playing a bit with Spring DI and Quarkus before Christmas. I took repo referenced from baeldung.com site, trimmed the code and pom.xml to use just di.spring package. After the trimming I tried to migrate source code to use quarkus-spring and then I tried to migrate tests. I have ideas for enhancements in Spring DI guide

Code is here: https://github.com/rsvoboda/tutorials/commits/experiments

**`@ComponentScan` and `@Import`**
In https://github.com/rsvoboda/tutorials/commit/68c9f76fdcd181b4dc913977f564f09705784beb I had to comment out org.springframework.context.annotation.ComponentScan and org.springframework.context.annotation.Import stuff

Based on the discussion with @geoand, `@ComponentScan` is entirely unnecessary because of the build time processing. `@Import` is not supported as we don't support XML config.

Info about `@ComponentScan` and `@Import` should be added into https://quarkus.io/guides/spring-di#conversion-table or nearby. People without Quarkus context won't know the above details and it will make Quarkus onboarding easier.

**ApplicationContext**
There is nothing about `org.springframework.context.ApplicationContext` in our guides. We don't support that - it's too tied to Spring internals. Spring DI guide should provide some context and explain into what ApplicationContext translates in Arc / Quarkus DI world.

**Testing**
For tests, we don't support any of the Spring testing stuff. It's just so different than what we have in Quarkus.
https://quarkus.io/guides/getting-started-testing could be linked from the guide.

**Comment by geoand** [comment]
@aureamunoz would you like to take this one?

**Comment by aureamunoz** [comment]
Thank you for this! I would like but not sure to be able to take it this week because I'm working on the Dekorate talk and the deadline is next Friday so if it can wait, yes! I'll do it

**Comment by geoand** [comment]
There is no pressure on this, so feel free to do it whenever you like :)

**Comment by geoand** [comment]
Was fixed in https://github.com/quarkusio/quarkus/pull/14514
