### ISSUE TITLE
Kafka Deserialization errors are hidden in debug logs.

### ISSUE THREAD

**Issue by javadevmtl** [quarkusio/quarkus#14234]
Using Quarkus 1.9.1.Final

**Describe the bug**
It seems like deserialization are are logged as debug. Wasn't able to consume messages and couldn't figure out why until debug was enabled.

{"appTimestamp":"2021-01-11T12:35:53.924-05:00","sequence":72610,"loggerClassName":"io.smallrye.reactive.messaging.kafka.i18n.KafkaLogging_$logger","loggerName":"io.smallrye.reactive.messaging.kafka","level":"DEBUG","message":"SRMSG18228: A failure has been reported for Kafka topics '[smpp-clone-mo-dev]'","threadName":"vert.x-kafka-consumer-thread-0","threadId":111,"hostName":"anastasioss-macbook-pro.local","processName":"smpp-clone-0.1-RC152-dev.jar","processId":71532,"stackTrace":"org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition smpp-clone-mo-dev-8 at offset 4. If needed, please seek past the record to continue consumption.\nCaused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"metadata\" (class com.xxxxxx.model.http.request.MyRequest), not marked as ignorable (7 known properties: \"xxxxxx\", \"xxxxxx\", \"xxxxxx\", \"xxxxxx\", \"xxxxxx\", \"xxxxxx\", \"xxxxxx\"])\n at [Source: (ByteArrayInputStream); line: 1, column: 324] (through reference chain: com.xxxxxx.model.http.request.MyRequest[\"metadata\"])\n\tat io.quarkus.kafka.client.serialization.ObjectMapperDeserializer.deserialize(ObjectMapperDeserializer.java:39)\n\tat org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1310)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher.access$3500(Fetcher.java:128)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1541)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1377)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:677)\n\tat org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:632)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1290)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1248)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)\n\tat io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:147)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"metadata\" (class com.xxxxxx.model.http.request.MyRequest), not marked as ignorable (7 known properties: )\n at [Source: (ByteArrayInputStream); line: 1, column: 324] (through reference chain: com.xxxxxx.model.http.request.MyRequest[\"metadata\"])\n\tat com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)\n\tat com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)\n\tat com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1554)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:511)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)\n\tat com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)\n\tat com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3505)\n\tat io.quarkus.kafka.client.serialization.ObjectMapperDeserializer.deserialize(ObjectMapperDeserializer.java:37)\n\t... 16 more\n"}

**Expected behavior**
Should be logged as error otherwise we will never know.

**Comment by cescoffier** [comment]
The issue has been fixed by @loicmathieu upstream, and the version has been released and integrated.
