### ISSUE TITLE
Redis NOAUTH Authentication required.

### ISSUE THREAD

**Issue by 362228416** [quarkusio/quarkus#14271]
**Describe the bug**
(Describe the problem clearly and concisely.)

this code throw expcetion, NOAUTH Authentication required.
```java
import io.quarkus.redis.client.RedisClient;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.Arrays;

@Singleton
public class SessionService {

    @Inject
    RedisClient redisClient;

    private final String SESSION_KEY = "session";

    public void saveToken(Integer uid, String token) {
//        redisClient.auth("0669");   // require auth by self
        redisClient.hset(Arrays.asList(SESSION_KEY, uid.toString(), token));  //  errorr
    }

    public String getToken(Integer uid) {
        return redisClient.hget(SESSION_KEY, uid.toString()).toString();
    }

}
```

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

will be ok

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

error

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  use maven
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

quarkus.redis.hosts=redis://0669@localhost:6375

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
CC @pmlopes

**Comment by pmlopes** [comment]
Hi, I believe the url is incorrect:

```
quarkus.redis.hosts=redis://0669@localhost:6375
```

According to the spec the `userinfo` section which is the characters between: `redis://` and `@localhost` are composed of two parts:

```
username[:password]
```

What is being said here is that the username is: `0669` and no password. Redis before version 6 didn't take username in consideration (from 6 and up it does as it has `ACL` built ins). As redis URLs are registered at IANA they are fully compliant with the spec so the desired URL is:

```
quarkus.redis.hosts=redis://:0669@localhost:6375
```

Note the extra `:` at the start of the `userinfo` segment. Also, the IANA registry states that passwords can be specified as query arguments like:

```
quarkus.redis.hosts=redis://localhost:6375?password=0669
```

Finally, nothing is said about the password character encoding, so they are currently URL decoded assuming a charset of `UTF-8`.

**Comment by 362228416** [comment]
@pmlopes 
You're right. That's the reason. Thank you
