### ISSUE TITLE
qute: varargs extension function is not called when exactly one parameter is given

### ISSUE THREAD

**Issue by chschroe74** [quarkusio/quarkus#14270]
Let this be a qute extension function:
```
@TemplateExtension(namespace = "t")
public static String test(String... args) {
    return "TEST: " + String.join(", ", args);
}
```
We can call this extension function like this:
```
{t:test()}<br>
{t:test("a")}<br>
{t:test("a", "b")}<br>
```
The output should be:
```
TEST:
TEST: a
TEST: a, b
```
Instead, the output is:
```
TEST:
NOT_FOUND
TEST: a, b
```
Obviously, the extension function is not found when exactly one argument is passed.

The bug lies in the method "parameterTypesMatch" of the class "io.quarkus.qute.EvaluatedParams". It first checks if the actual number of parameters is different from the declared number of parameters. Only in this case, the "varargs" part is executed, which then correctly identifies the method as matching if the number of actual parameters is 0 or greater than 1. If exactly one parameter is passed, the varargs-specific code is skipped and the types are compared. The actual type is "String" whereas the declared type is "String[]". Because of this mismatch, the parameters are treated as not matching.

**Comment by mkouba** [comment]
I think that this should be fixed in master, specifically by this PR: https://github.com/quarkusio/quarkus/pull/14226

@chschroe74 could you pls test your app against the current master (or 1.11.0.Final which should be released within a few days).

**Comment by chschroe74** [comment]
Tested against the latest snapshot version. I can confirm that the issue is resolved.
