### ISSUE TITLE
Detect calls to getDeclaredFields() and getDeclaredMethods() in the reflection debug agent

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1428]
See the discussion we had here:
https://github.com/quarkusio/quarkus/pull/1420#discussion_r264616929

When, for instance, the JSON-B serializer serializes an entity, it gets the fields and methods via `getDeclaredFields()` and `getDeclaredMethods()`. If these elements have not been fully registered for reflection, GraalVM will return partial results.

Warning the user about it would be great and would fix https://github.com/quarkusio/quarkus/issues/739 .

**Comment by geoand** [comment]
Should we keep this around or close? Asking because we don't really promote the use of our agent nor really update it (not to mention that GraalVM has its own [agent](https://www.graalvm.org/reference-manual/native-image/Agent/))
