### ISSUE TITLE
security-jpa custom cypher for passwords

### ISSUE THREAD

**Issue by davide-malagoli** [quarkusio/quarkus#14284]
HI,
I'm having a problem with security-jpa.

We have an already existing database with users already created, and we need to integrate our application with that.

Password are stored usign SHA-256 cypher, but this seems not supported by the module (only MCF and CLEAR seem to allowed).

Is there any method we could override to make things work?

**Comment by sberyozkin** [comment]
@FroMage can you recommend something ?

**Comment by FroMage** [comment]
I can definitely comment that SHA-256 is not the best solution for hashing passwords, because it's too fast. BCrypt is much safer. So I've mixed feelings about supporting a non-optimal hashing solution out of the box.

Perhaps the right thing to do is to make it pluggable in a way that users will have to provide their own hashing solutions (even if it uses the hashing algos from our lib) if it's not the one we advise? Makes it possible, while a little more annoying, but just enough that users won't use this by mistake and understand the risk.

Some API like this perhaps:

```java
class Hash implements PasswordHasher {
 @Override
 public String hash(String password){
  return Something.sha256(password);
 }
}

@Entity
@Table(name = "test_user")
@UserDefinition 
public class User extends PanacheEntity {
    @Username 
    public String username;
    @Password(value = PasswordType.CUSTOM, hash = Hash.class)
    public String password;
    @Roles 
    public String role;
}
```

Also note that we actually probably already support SHA-256 passwords as long as they're in MCF format: https://en.wikipedia.org/wiki/Crypt_(C)#Key_derivation_functions_supported_by_crypt

**Comment by gsmet** [comment]
+1 for custom implementation. That's what I had in mind when I answered Davide on Zulip.

Should be pretty straightforward for a new contributor.

**Comment by davide-malagoli** [comment]
@FroMage I know this is a sub-optimal (read horrible) solution, but this database it's still used in production, so we cannot change something so critical like password encoding.
I like your approach that uses a custom class.

@gsmet I read your response on Zulip.
So, I need to write also an enanchment request or we can continue using this issue?

Thanks both for your cooperation.

So what's next? 
Is there a way where I can contribute to this enanchment?

**Comment by gsmet** [comment]
This issue is fine to track this.

Sure, if you can give a try at implementing what @FroMage suggested, that would be awesome.

Reading https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md might a good start.

**Comment by davide-malagoli** [comment]
I'm trying to code it myself, but I'm missing something.
How can I express the logic "this fields contains a class impleting this interface?

/**
 * <p>
 * Indicates that this field or property should be used as a source of password for security. Only
 * supports the {@link String} type.
 * </p>
 * <p>
 * Defaults to considering the password as hashed with bcrypt in the Modular Crypt Format.
 */
@Target({ ElementType.FIELD, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Password {
    /**
     * Sets the password storage type. defaults to {@link PasswordType#MCF}.
     */
    PasswordType value() default PasswordType.MCF;

    Class<? implements PasswordHasher> hash;
}

**Comment by imshuv** [comment]
I want to work on this ,I would be extremely thankful if someone could guide me on how to get started with this?

**Comment by davide-malagoli** [comment]
@imshuv maybe you can join us, I opened a zulip topic about that

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/security-jpa.20custom.20password.20cypher.20algorithm/near/222617005

**Comment by iamavx** [comment]
Hey, I am new beginner in this issue can you suggest me how to get started

**Comment by antoniodvr** [comment]
> I can definitely comment that SHA-256 is not the best solution for hashing passwords, because it's too fast. BCrypt is much safer. So I've mixed feelings about supporting a non-optimal hashing solution out of the box.
> 
> Perhaps the right thing to do is to make it pluggable in a way that users will have to provide their own hashing solutions (even if it uses the hashing algos from our lib) if it's not the one we advise? Makes it possible, while a little more annoying, but just enough that users won't use this by mistake and understand the risk.
> 
> Some API like this perhaps:
> 
> ```java
> class Hash implements PasswordHasher {
>  @Override
>  public String hash(String password){
>   return Something.sha256(password);
>  }
> }
> 
> @Entity
> @Table(name = "test_user")
> @UserDefinition 
> public class User extends PanacheEntity {
>     @Username 
>     public String username;
>     @Password(value = PasswordType.CUSTOM, hash = Hash.class)
>     public String password;
>     @Roles 
>     public String role;
> }
> ```
> 
> Also note that we actually probably already support SHA-256 passwords as long as they're in MCF format: https://en.wikipedia.org/wiki/Crypt_(C)#Key_derivation_functions_supported_by_crypt

@gsmet @FroMage 

What if rather than passing two values (`value` and `hash`) we only pass one value with the class reference of the PasswordHasher implementation?

```java
@Entity
 @Table(name = "test_user")
 @UserDefinition 
 public class User extends PanacheEntity {
     @Username 
     public String username;
     @Password(ClearTextPasswordHasher.class)
     //@Password(MCFPasswordHasher.class)
     //@Password(ExternalCustomHasher.class)
     public String password;
     @Roles 
     public String role;
 }
 ```

So that we can replace the `PasswordType` enum with the implementations:

 ```java
class ClearTextPasswordHasher implements PasswordHasher {
  @Override
  public String hash(String password){
    return ... ;
  }
}

class MCFPasswordHasher implements PasswordHasher {
  @Override
  public String hash(String password){
    return ... ;
  }
}
```

**Comment by FroMage** [comment]
That's possible, but it would not be binary-compatible.

I'd make constants for the built-in classes, to allow for completion:

```java
     @Password(PasswordHasher.ClearText)
     //@Password(PasswordHasher.MCF)
     //@Password(ExternalCustomHasher.class)
     public String password;
```
