### ISSUE TITLE
QueryParam values are not injected into the API under test when using RestAssured and the JBoss version of the @QueryParam annotation

### ISSUE THREAD

**Issue by picaron** [quarkusio/quarkus#14288]
**Describe the bug**

I am writing a simple test case using RestAssured which passes some query params to my REST API under test. 

Example test:

```
    @Test
    public void simpleTest() {
           given()
                .when()
                    .queryParam("from", "2021-01-01")
                    .queryParam("to", "2021-01-31")
                    .get("/testapi")
                .then()
                    .statusCode(200);
    }
```

Example REST API:

```
import ...
import org.jboss.resteasy.annotations.jaxrs.QueryParam

@Path("/testapi")
public class TestResource {
    @GET                                                            
    @Produces(APPLICATION_JSON)
    public Response availability(@QueryParam String from, @QueryParam String to) {
        //from and to are always null here if I use the JBoss version of the annotation
    }
}
```

**Expected behavior**

I should be able to use the JBoss annotation with my tests and not have to revert to the JAX-RS one to make my tests work.

**Actual behavior**

Only if I use the standard JAX-RS import it works as expected when testing with RestAssured.

However its more verbose, I have to repeat the name of the parameter while the JBoss one infers it from the name of the variable.

**To Reproduce**

See example code above

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin macbook.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
 ```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
 - GraalVM version (if different from Java): not using yet
 - Quarkus version or git rev: `1.10.5.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/pascal.chouinard/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_265, vendor: AdoptOpenJDK, runtime: /Users/pascal.chouinard/.sdkman/candidates/java/8.0.265.hs-adpt/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

**Comment by famod** [comment]
Interesting proposal (more of an enhancement than a bug).
/cc @gsmet @geoand

**Comment by geoand** [comment]
You are most likely seeing this because the java compiler has not been configured to include parameter names.

See https://github.com/quarkusio/quarkus-quickstarts/blob/master/hibernate-reactive-quickstart/pom.xml#L83 for an example configuation (which is automatically applied when creating a project from code.quarkus.io)

**Comment by famod** [comment]
It never occurred to me that we also do support the jboss annotations already. In this case, following up on @geoand's suggestion, make sure you don't run into this problem: https://github.com/quarkusio/quarkus/issues/14331#issuecomment-761168707

**Comment by geoand** [comment]
Closing this as the comments above explain the issue and we haven't heard anything new.
If this is still an issue, feel free to reopen or comment
