### ISSUE TITLE
Hibernate Validator - Support groups in method validation

### ISSUE THREAD

**Issue by ChMThiel** [quarkusio/quarkus#14293]
I asked for BeanValidation-Support in zulip (see https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/BeanValidation.20Groups).  Guillaume Smet found, that i should request an enhancement. Here it comes:

**Description**

Currently I have an issue with BeanValidation: I need to provide ValidationGroups in order to use Constraint-Annotations like this:
_@Null(groups = POST.class)
@NotNull(groups=PUT.class)
UUID id;_
-> Force user to NOT set the Id on create. Force user to provide id on update.

As far as i can see, there is no way to provide BeanValidation-Groups to Quarkus.

**Implementation ideas**

I found io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor in artifact quarkus-hibernate-validator which delegates the actual verification to hibernate-validator, without any ValidationGroups :
...
__Set<ConstraintViolation<Object>> violations = executableValidator.validateParameters(ctx.getTarget(), ctx.getMethod(), tx.getParameters()); 
//No Groups here :(
//....all validateXXX-Methods of validator provide a varArg-Parameter for validationGroups, but's not provided here_
...

Wouldn't it be nice to provide an annotation like @ValidationGroups(class[]) which could be used at class/method-level to provide the ValidationGroups to be used for the validation (default behavior just like it is now: No annotation present -> no validationGroups given to the validator)

**Comment by yrodiere** [comment]
@ChMThiel I had a closer look, and it turns out you can already do what you want, without any new annotation.

The trick is to use `@ConvertGroup`. Since you know the `Default` group is active, you can convert it in whatever group you want. So, to enable the `Put` and `Post` groups when validating a parameter, do something like this:

```
    public String put(@Valid @ConvertGroup(to = Put.class) MyBeanWithGroups bean) {
        return "ok";
    }

    public String post(@Valid @ConvertGroup(to = Post.class) MyBeanWithGroups bean) {
        return "ok";
    }
```

Then this bean will be required to have a null `id` in `put`, but a non-null one in `post`:

```
public class MyBeanWithGroups {

    @Null(groups = Put.class)
    @NotNull(groups = Post.class)
    private Long id;

    @NotNull
    private String name;

    // ...
}

You may want to keep the `Default` group active when `Put`/`Post` are active, so as to validate the `@NotNull` on `name`. If you want that, just make the `Put`/`Post` interfaces extend `Default`:

```
public interface Post extends Default {
}

public interface Put extends Default {
}
```

See #14509 for more details.

**Comment by ChMThiel** [comment]
@yrodiere Thank your for your suggestions. I will try it that way.

**Comment by ChMThiel** [comment]
Yep, works like a charm!
Thanks!
