### ISSUE TITLE
dev console -> dev mode

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#14296]
**Description**
Quarkus Developer Console has some unfortunate connotations of it might be for management features or cause confusion between OpenShift Developer Console. 

Suggestion that came up during conversations was to simply just call the page "Dev Mode" or "Quarkus Dev Mode" in full.

This would:

a) avoid using the already overloaded console term
b) makes it clear this feature set is for development mode; not a management tool of any sorts
c) does not introduce new vocabulary besides "dev mode"  page.

Too late for 1.11 but I suggest we do it in 1.11.1

**Comment by geoand** [comment]
cc @FroMage @stuartwdouglas @gsmet

**Comment by gsmet** [comment]
Can't say I agree with this. It's a Dev Console. Calling it Dev Mode will be confusing as we already have something called dev mode.

**Comment by maxandersen** [comment]
that is the whole point - to not make this something more than what is dev mode. This is part of devmode - why not call it the dev mode page ?

Dev console is a term heavily used in OpenShift thus it will cause unnecessary confusion/friction IMO.

**Comment by geoand** [comment]
I personally don't have much of a preference... I can see merit in both names

**Comment by gavinking** [comment]
I think there's three reasons to do this. It:

1. strengthens the "Dev Mode" brand, making it a stronger feature
2. makes it clear that this isn't a management console, making its purpose clearer
3. removed the useless word "console" which isn't doing any real work here, and actually has no clear semantics (people sometimes call a command line interface a "console")

Or course, we're also open to other suggestions. But I think value in this proposed name is in strengthening/unifying the whole idea of a "dev mode".

**Comment by mkouba** [comment]
Hm, what about "Dev Mode Console"?

**Comment by gavinking** [comment]
> Hm, what about "Dev Mode Console"?

Sure, that was one of my suggestions, but we then agreed that "console" doesn't mean anything, and just makes the name longer.

**Comment by stuartwdouglas** [comment]
My only objection to this is that it overloads 'dev mode', when someone says dev mode in chat or on an issue it may not be clear what they are talking about. That said I don't really have a better name, my only suggestion from a while back was 'Quarkus Accelerator', because it accelerates app development and plays into the particle accelerator/subatomic theme.

**Comment by geoand** [comment]
> > Hm, what about "Dev Mode Console"?
> 
> Sure, that was one of my suggestions, but we then agreed that "console" doesn't mean anything, and just makes the name longer.

But it does disambiguate when we need to have users explain issues. I'm +1 for Martin's suggestion

**Comment by gavinking** [comment]
> my only suggestion from a while back was 'Quarkus Accelerator'

This is a nice name, but I would keep it up our sleeves for something much cooler that we invent in the future.

**Comment by gavinking** [comment]
> But it does disambiguate when we need to have users explain issues.

That's true, and to clarify, I think it's fine as a name of the software component that sits behind this page. But I'm inclined to leave it off the title of the page itself.

**Comment by maxandersen** [comment]
Btw. Another issue is that there are rumblings of adding quarkus hooks into openshift dev console. Overloading even more. 

I like dev mode as this is dev mode :) I'm fine with other names too but since hard to name things I prefer dev mode as a neutral starting point :)

**Comment by geoand** [comment]
> > But it does disambiguate when we need to have users explain issues.
> 
> That's true, and to clarify, I think it's fine as a name of the software component that sits behind this page. But I'm inclined to leave it off the title of the page itself.

Sure, that makes to me too

**Comment by mkouba** [comment]
> > Hm, what about "Dev Mode Console"?
> 
> Sure, that was one of my suggestions, but we then agreed that "console" doesn't mean anything, and just makes the name longer.

Well, it does mean different things but maybe we can find a better name. "Dev Mode Dashboard", "Dev Mode Control Panel",  "Dev Mode Control",  "Dev Mode Controls"

**Comment by gavinking** [comment]
> > > Hm, what about "Dev Mode Console"?
> > 
> > 
> > Sure, that was one of my suggestions, but we then agreed that "console" doesn't mean anything, and just makes the name longer.
> 
> Well, it does mean different things but maybe we can find a better name. "Dev Mode Dashboard", "Dev Mode Control Panel", "Dev Mode Control", "Dev Mode Controls"

But what value do any of those words add. I'm sitting here looking at a web page titled "Quarkus Dev Mode". That tells me what I need to know. I simply don't need any additional noisewords to disambiguate the purpose of this thing.

When in doubt, prefer short, snappy names.

**Comment by dandreadis** [comment]
Dev Mode Page?

**Comment by gsmet** [comment]
I agree a short name is better. But as Stuart and I mentioned it, naming two different things with the same name is a recipe for confusion. We need a name that is not `dev mode`, whatever it is.

**Comment by maxandersen** [comment]
Dev mode home(page) :)

**Comment by gavinking** [comment]
> Dev mode home(page) :)

OMG Max, I can't believe you have not proposed "My Quarkus Dev Mode"!

**Comment by geoand** [comment]
Dev Mode UI?

**Comment by gavinking** [comment]
DevModeUI since we all know computery things don't have spaces in them.

**Comment by maxandersen** [comment]
Am I the only one that sees dev mode as the thing that skips augmentation, enables dev mode hot reload, enables the dev mode exception handling , enables this dev mode page ?

We don't have individual names for those sub parts afaik - it's all things that part of dev mode - dev mode haven't been only the hot reload feature since well...forever ?

**Comment by maxandersen** [comment]
How about on the page that only shows up when dev mode is available writes "Quarkus Dev mode overview" ?

**Comment by gavinking** [comment]
> naming two different things with the same name is a recipe for confusion

In seriousness, I'm pretty sure that whenever there is potential for confusion, it can easily be eliminated by saying "the Dev Mode page", "the Dev Mode home page" or the "Dev Mode web UI" or something like that.

It doesn't need to be a (capitalized) part of the name.

But ordinarily it's going to be very clear from context.

**Comment by gavinking** [comment]
> How about on the page that only shows up when dev mode is available writes "Quarkus Dev mode overview" ?

That's fine too.

**Comment by gavinking** [comment]
Um, I think we also need to regularize the naming of this "dev mode". Is it "development mode", "dev mode", or "Dev Mode"? Apparently this isn't uniform even in the existing Quarkus documentation.

**Comment by maxandersen** [comment]
> Um, I think we also need to regularize the naming of this "dev mode". Is it "development mode", "dev mode", or "Dev Mode"? Apparently this isn't uniform even in the existing Quarkus documentation.

agree, but lets boil one ocean at a time :)

**Comment by stuartwdouglas** [comment]
Think about it if you were doing a presentation: 'I am starting Quarkus in dev mode', and you show off the live reload etc, 'and now I am going to show you Quarkus Dev Mode' which has the same name but is a completely different thing. 

Thinking about names some more:

Dev UI
Quarkus Webtools
Qtools
QUI
Devpage

**Comment by stuartwdouglas** [comment]
> > my only suggestion from a while back was 'Quarkus Accelerator'
> 
> This is a nice name, but I would keep it up our sleeves for something much cooler that we invent in the future.

This is early days, $NAME will end up a lot cooler in a few releases time.

**Comment by maxandersen** [comment]
> 'I am starting Quarkus in dev mode', and you show off the live reload etc, 'and now I am going to show you Quarkus Dev Mode'

you would say "Quarkus Dev Mode page" or "the page giving an overview of extra things available when we run in dev mode".

I honestly don't see the issue here.

**Comment by maxandersen** [comment]
> This is early days, $NAME will end up a lot cooler in a few releases time.

yes - I really just want to remove the usage of "console" here as that overlaps with things we do not have a way to fix/disambiguate.

**Comment by gsmet** [comment]
`Dev UI` makes a lot of sense given this:

https://github.com/quarkusio/quarkus/pull/14300

We have all the other UIs with `Xxx UI`.

**Comment by maxandersen** [comment]
okey - but isn't "Dev mode UI" more telling ? But I'm fine having the page say "Dev UI" or I guess "Quarkus Dev UI" as it nukes console and ties it to "development"/devmode.

**Comment by dandreadis** [comment]
I kind of like the /devmode URL that leads you to the DevMode UI/Page/View/WebUI/add-other-name. As Stuart said, just think how you'd naturally describe it in a presentation.

**Comment by FroMage** [comment]
I agree we can't call it "dev mode" because it means something else ATM and will make it confusing. I don't care if it's renamed, I understand your motivation.
"Dev Mode UI" or "Dev Mode Interface" sound OK to me.

**Comment by gsmet** [comment]
For me, it's more a Development UI, rather than simply a Dev mode one. You can do a lot of things that are not related at all to Dev mode. Granted, it's available in dev mode but it's really about easing development.

I will create a PR to rename it `Dev UI` so that it's consistent with all the other UIs @phillip-kruger is working on.
