### ISSUE TITLE
Quarkus Form Authentication...404 Response

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#14313]
**Description**
I'm using form authentication (quarkus.http.auth.form.enabled = true) with security-jpa and it works fine except when there is a post authorization error.  Also, my spa is located in resources/META-INF/resources

During my development I had a null pointer in the endpoint I set up as a re-direct.  I corrected the logic, then re-submitted my login to j_security_check and got a 404.  This one took me awhile to figure out the issue.  Since the error occured after authentication, my browser had the quarkus-credential cookie and subsequent attempts to login with the cookie present triggers a 404 response.  

I built a unit test to reproduce the error:
public void testFormBasedAuthentication() {

               ValidatableResponse response = given()
                .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                .body("j_username=read.only&j_password=jackplane")
                .post("j_security_check")
                .then()
                .statusCode(Status.FOUND.getStatusCode())
                .cookie("quarkus-credential",notNullValue());
                String cookie = response.extract().cookie("quarkus-credential");

               // submit another login with the cookie received in the prior response
                given()
                .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                .body("j_username=read.only&j_password=jackplane")
                .cookie("quarkus-credential", cookie, "")
                .post("j_security_check")
                .then()
                .statusCode(Status.FOUND.getStatusCode())
                .cookie("xsrf-token",notNullValue());
        }
Is this operating as intended to prevent subsequent login when a cookie is currently valid?  If so, a 404 doesn't seem to be the correct status code.
**Implementation ideas**
Could the form based authentication logic return a different response ?

**Comment by sberyozkin** [comment]
CC @stuartwdouglas Hi Stuart - can you comment please when you get a sec, thanks
