### ISSUE TITLE
quarkus.datasource.db-kind is not set when using PostgreSql ServiceBinding

### ISSUE THREAD

**Issue by johnpoth** [quarkusio/quarkus#14327]
**Description**
quarkus.datasource.db-kind is not set when using PostgreSql ServiceBinding and so no default DataSource is created,

**Implementation ideas**
Set quarkus.datasource.db-kind

Thanks !

**Comment by geoand** [comment]
As mentioned in https://github.com/quarkusio/quarkus/pull/14328#issuecomment-761071198, this is intentional as `quarkus.datasource.db-kind` is a build time property
