### ISSUE TITLE
for JAX-RS resources generated by Panache, when using PUT to update, omitted fields are set to null 

### ISSUE THREAD

**Issue by eliaharm** [quarkusio/quarkus#14325]
**Describe the bug**
when calling a REST api generated with Panache ORM quarkus-hibernate-orm-rest-data-panache

suppose you have the below table:
```
CREATE TABLE T_Service_Categories (
Service_Category_ID    SERIAL NOT NULL,
Description      VARCHAR(40),
Created_by    VARCHAR(40),
Created_Date  DATE,
Updated_by    VARCHAR(40),
Updated_Date  DATE,
PRIMARY KEY (Service_Category_ID)
);
```
For an existing record, if you call the PUT api with the ID and JSON data
if for example the `Created_by` and `Created_Date` attributes are omitted in the JSON object, these fields will be set to `null`.

**Expected behavior**
the API should update the fields that have values in the JSON object and and leave the other fields untouched.
a workaround would be to read the original values for example for  `Created_by` and `Created_Date` fields and add them to the request. but this will not be practical for large tables for example if you only need to update `status` field for a row with 50 columns.

**Actual behavior**
table fields missing in the JSON object passed to the rest api are cleared

**To Reproduce**

using Quarkus 1.10.5

**Comment by loicmathieu** [comment]
@eliaharm I don't agree with you, PUT should replace the entity with the body of the request.

This is what a standard PUT method is for, you can check the HTTP RFC: https://tools.ietf.org/html/rfc7231#section-4.3.4

> The PUT method requests that the state of the target resource be
   created or replaced with the state defined by the representation
   enclosed in the request message payload.

Partial update it a debatable subject on REST endpoint, it is sometimes implemented using PATCH method (not standard) but not everybody agree on this.

**Comment by eliaharm** [comment]
Thanks @loicmathieu for the info, turned out to be a complicated subject.

I get there is no plan to support PATCH. If I want to have this option should I create a new api or can it be added in the same panache xxxxResource class?

Also for related tables for example master details, to update the MASTER should the JSON also include the DETAILS records or else the rows could be deleted?

**Comment by loicmathieu** [comment]
>I get there is no plan to support PATCH. If I want to have this option should I create a new api or can it be added in the same panache xxxxResource class?

You can open an ehancement request (a different type of issue) for this and starts a discussion

> Also for related tables for example master details, to update the MASTER should the JSON also include the DETAILS records or else the rows could be deleted?

You should include the full ressource including all details. I won't be 100% sure that it will delete the details (it depends of your mapping I think) but it's possible.

**Comment by eliaharm** [comment]
done, request https://github.com/quarkusio/quarkus/issues/14329 .
thanks
