### ISSUE TITLE
Add TOML and JSON support for quarkus configuration

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#14330]
**Description**
Quarkus supports  java properties, JSON and YAML formats for configuration. Each of these, unfortunately suffers from either verbosity, obscurity or weak syntax  validation for configuration purposes, as JSON and YAML are primarily data formats.

TOML emerges as the best format for configuration and it would be a wonderful addition to Quarkus. You can read about [TOML here](https://github.com/toml-lang/toml) and why it is superior as configuration format.

**I wish TOML can go all the way to MicroProfile Config as the preferred standard format.**

**Implementation ideas**
There are several candidate implementations if you gogole "Java toml", for example [toml](https://github.com/tomlj/tomlj).

@geoand

**Comment by geoand** [comment]
cc @radcortez

**Comment by glefloch** [comment]
I would definitely be interested into working on this. As for `yml` this could be part of an extension. Maybe in quarkiverse?

**Comment by geoand** [comment]
I am fairly certain that @radcortez will want the core support to be in Smallrye Config.

But let's see what he says

**Comment by radcortez** [comment]
I think it would be better if this works happens in SR Config.

On the support itself, there are some limitations due to the MP Config API, namely treating every configuration as a single property key and value as String. This works fine for things like properties files, env, system properties, etc, but it is hard for `json` or `yaml` structures.

I do have some ideas on how to improve this, but I think we should work on some prototype before proposing something to the spec.

**Comment by radcortez** [comment]
> I am fairly certain that @radcortez will want the core support to be in Smallrye Config.
> 
> But let's see what he says

:)

**Comment by geoand** [comment]
A first step however could be to provide s ConfigSource similar to what you have with YAML, right?

Then ConfigProperties could use the same trick it does with for YAML to parse the value of the property for complex structures

**Comment by radcortez** [comment]
Yes.

**Comment by hrstoyanov** [comment]
I would gladly test prototypes ! I have some real-world complex configurations as the one I sent to @geoand  before for yaml.

**Comment by radcortez** [comment]
Here is a prototype: https://github.com/smallrye/smallrye-config/pull/497

**Comment by hrstoyanov** [comment]
will test shortly!

**Comment by hrstoyanov** [comment]
See sample configs here:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Need.20some.20help.20with.20Smallrye.20ConfigMapping/near/233873807

**Comment by radcortez** [comment]
All additional configuration formats will be supported by https://github.com/quarkiverse/quarkus-config-extensions. I've created https://github.com/quarkiverse/quarkus-config-extensions/issues/6 to track this and we will follow from there.
