### ISSUE TITLE
Gradle Plugin Classpath Setting

### ISSUE THREAD

**Issue by jamesward** [quarkusio/quarkus#14334]
I'm using the Quarkus Gradle Plugin (1.11.0.Final) and need a way to set the Classpath that `quarkusDev` uses.  Reason is that for dev I like to create a configuration that has different stuff in it than the main configuration.  In Spring Boot I can use a `developmentOnly` configuration for this kind of thing.

**Comment by glefloch** [comment]
Internally we already create a `quarkusDevMode` configuration internally. We could make it public. WDYT @aloubyansky ?

**Comment by jamesward** [comment]
Thanks!
