### ISSUE TITLE
Tests are not compiled with `maven.compiler.parameters=true`

### ISSUE THREAD

**Issue by josejulio** [quarkusio/quarkus#14331]
**Describe the bug**
When running the tests I see some errors about `parameters` not being set. This does not happen on `quarkus:dev`.

On my pom file I'm setting `<maven.compiler.parameters>true</maven.compiler.parameters>`

**Expected behavior**
Property `maven.compiler.parameters` being used by the tests

**Actual behavior**
Fails unless `parameters` are set into `maven-compiler-plugin`

```
<compilerArgs>
    <arg>-parameters</arg>
</compilerArgs>
```

**To Reproduce**

I don't have a small reproducer yet, but is failing on this [commit](https://github.com/RedHatInsights/policies-ui-backend/pull/171/commits/1a6d5994195e16cb18adeef669506e433e5a0dff)
[see github actions output](https://github.com/RedHatInsights/policies-ui-backend/runs/1709921536#step:5:524)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux fedora 5.9.10-200.fc33.x86_64 #1 SMP Mon Nov 23 18:12:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
 ```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11, mixed mode, sharing)
 ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  `1.9.1`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/josejulio/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.9, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-0.fc33.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.10-200.fc33.x86_64", arch: "amd64", family: "unix"
```

**Comment by famod** [comment]
I think this is a known maven-compiler-plugin bug:
https://issues.apache.org/jira/browse/MCOMPILER-413
That ticket also includes a workaround.

**Comment by famod** [comment]
@josejulio please reopen in case you still think this is a Quarkus bug.

**Comment by josejulio** [comment]
Thanks, the workaround specified there did the trick.
