### ISSUE TITLE
Separate layer for snapshot dependencies in quarkus-container-image-jib

### ISSUE THREAD

**Issue by kekbur** [quarkusio/quarkus#14347]
**Description**
I have a multi-module Maven project where a Quarkus application declares snapshot dependencies to the other modules. Currently `quarkus-container-image-jib` lumps all jar files in `target/lib` together into a single Docker image layer, including the snapshot jars of my dependent modules. This makes the Docker images much less efficient than what they could be because there is 50 MB of never changing content and a few hundred kilobytes of always changing content in one layer.

As a workaround I attempted to make my snapshot builds reproducible using `reproducible-build-maven-plugin`, but this effort failed because `jandex-maven-plugin` does not generate reproducible results. [Somebody wanted to make jandex builds reproducible](https://github.com/wildfly/jandex/issues/71), but that effort seems to be on hold.

**Implementation ideas**
`quarkus-container-image-jib` should generate a separate layer for jars that have `SNAPSHOT` in their name. The layer would be directly on top of the dependent libraries layer.

**References**

Adjacent discussion at #9818.

**Comment by geoand** [comment]
This is a really good idea

**Comment by geoand** [comment]
@aloubyansky is there a way we can know from the `AppModel` whether or not a runtime dependency is part of the "project" or not?

**Comment by gsmet** [comment]
Shouldn't we put all snapshot dependencies in a separate layer, whether they're part of the project or not? They are moving targets anyway.

**Comment by geoand** [comment]
That's a good idea as well - and part of a second enhancement

**Comment by gsmet** [comment]
Oh, I thought it would be easier given you asked how to differentiate them :).

**Comment by geoand** [comment]
Now that I started to implement it, you are right :)

**Comment by geoand** [comment]
@gsmet I followed your advice and opened https://github.com/quarkusio/quarkus/pull/14362

**Comment by aloubyansky** [comment]
> @aloubyansky is there a way we can know from the `AppModel` whether or not a runtime dependency is part of the "project" or not? `getLocalProjectArtifacts` maybe?

yes

**Comment by kekbur** [comment]
Well, that was fast. Thanks guys.

**Comment by geoand** [comment]
Keep in mind that for the time being what you requested will only work when the version of your project (and therefore the dependencies) use the SNAPSHOT in their version.

This restriction might be lifted in later revisions of the code
