### ISSUE TITLE
Graphql uplaod file

### ISSUE THREAD

**Issue by mutasemhidmi** [quarkusio/quarkus#14350]
is it possible to upload file using multipart ?

**Comment by phillip-kruger** [comment]
@mutasemhidmi no that is not possible.

**Comment by mutasemhidmi** [comment]
@phillip-kruger so the solution will be to convert it to base64 and send it as string or there is work around solution ?

**Comment by phillip-kruger** [comment]
I would just not use GraphQL for that. Either use vertx, or server, or rest. If you have GraphQL you also have vertx. I am not sure how easy that is, but I would start there.

**Comment by mutasemhidmi** [comment]
will it support it in the future because if I'm not wrong Apollo the javascript library support something like this ?

**Comment by phillip-kruger** [comment]
@mutasemhidmi - this is not on our radar at the moment, but you can open a issue at https://github.com/smallrye/smallrye-graphql if you want this to be considered. Thanks :)

**Comment by mutasemhidmi** [comment]
thanks phillip for your help, i'm closing this question
