### ISSUE TITLE
quarkus-infinispan extension hard-coding location of hotrod-client.properties

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#14368]
I posted this on zulip chat last week but haven't been able to get a response (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20infinispan.20extension.20hotrod-client.2Eproperties/near/222425566)

Using the Infinispan component with camel-k. The issue is that the quarkus-infinispan extension hard-codes the location of `hotrod-client.properties` as `META-INF/hotrod-client.properties` (https://github.com/quarkusio/quarkus/blob/master/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java#L62).

In camel-k, the build is performed by the operator, so the user has no way to put `hotrod-client.properties` within a `META-INF` directory. The user just submits an `Integration` custom resource (https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e#file-camelk-client-yml-L56-L57) referencing a `ConfigMap`, and that `ConfigMap` is mounted in a directory in the running pod and is added to the root of the classpath. Because of this, as a camel-k user using the camel-infinispan component (which the underlying runtime is quarkus, handing off to the quarkus-infinispan extension), the integration just doesn't work.

This has been cross-posted on the camel-k issue tracker as well (apache/camel-k#1898)

**Comment by edeandrea** [comment]
@lburgazzoli I filed this here re the `hotrod-client.properties` issue we were discussing (apache/camel-k#1898).

**Comment by karesti** [comment]
@edeandrea let me know if the solution in the PR works for you, please

**Comment by edeandrea** [comment]
The PR moves it to the root of the classpath correct? Why can't it be configurable so the user can input (maybe via a property) where its location is?

**Comment by karesti** [comment]
@edeandrea it can be configurable via a property I guess, we wanted to avoid the need of adding a new property for this but just make it work without configuration. is this an issue ?

**Comment by karesti** [comment]
We can implement a new configuration property I guess @wburns wdyt

**Comment by edeandrea** [comment]
@lburgazzoli should weigh in as well since camel-k will need to make some changes once this change is made so that it becomes usable within camel-k.

**Comment by wburns** [comment]
I personally feel a configuration property to define the location of a properties file is overkill. The root classpath mirrors what Infinispan itself does anyways. The only reason it was in META-INF was due to to trying to hide other configuration files in Quarkus in general, which seems didn't quite happen.

**Comment by edeandrea** [comment]
That works for me then. We should still let @lburgazzoli  weigh in as well just to make sure he's good with it.

**Comment by wburns** [comment]
The `hotrod-client.properties` file is currently build time only. We can have a discussion about making it run time in another Issue if you would like.

**Comment by lburgazzoli** [comment]
So it does not help much moving to another location for the camel-k use case, let's have a separate discussion over zulip tomorrow

**Comment by wburns** [comment]
Yeah, it would be good to know what properties you plan on using as well. We specifically added a few to the runtime configuration used by the infinispan-client namespace which are detailed at https://quarkus.io/guides/infinispan-client. Maybe we can just add some more.

**Comment by gsmet** [comment]
@edeandrea @lburgazzoli is it something that you need in 1.11 or can it wait for the next version?

**Comment by lburgazzoli** [comment]
@gsmet for the camel POV, we can wait for the next version as we have some workarounds

**Comment by lburgazzoli** [comment]
@wburns the issue we have in camel-k is that the application build is performed by an operator and is not very simple to handle cases like when an additional property file is required so:

- @edeandrea mind providing more info about what hotrod properties you need so eventually they can be added to the quarkus-infinispan configuration options directly thus you won't need the hotrod-client.propertis fiel any more ?
- @wburns as the hot rod properties have their own properties namespace, would it be possible to retrieve them from MP config in addition to from the hotrod-client.propertis file ?

**Comment by edeandrea** [comment]
Everything I specifically am using is shown in https://github.com/edeandrea/debezium-demo-apb/blob/master/roles/Demo/objects/camelk-client.yml#L29L47

That, however, doesn't mean that there aren't others who are using other properties. Why would we develop a solution that only satisfies my specific use case? I would think any property available in `hotrod-client.properties` should be available for configuration. I don't know the internals of Quarkus, camel, or camel-k so there might be a good reason. From the outside looking in though, why wouldn't we want it to be as flexible as possible and guard against future change?

What if, down the road, some new property is introduced by Hotrod? Do we then need to wait for quarkus to "wrap" it, then wait for camel-k to make changes in the integration build that the operator performs?

Today on camel-k using the camel runtime I can do

`camel.component.infinispan.configuration.configurationUri=file:{{env:CAMEL_K_MOUNT_PATH_CONFIGMAPS}}/camelk-rhdg-client-config/hotrod-client.properties`

**Comment by wburns** [comment]
> That, however, doesn't mean that there aren't others who are using other properties. Why would we develop a solution that only satisfies my specific use case? I would think any property available in `hotrod-client.properties` should be available for configuration. I don't know the internals of Quarkus, camel, or camel-k so there might be a good reason. From the outside looking in though, why wouldn't we want it to be as flexible as possible and guard against future change?

The problem is this goes completely against the mantra of Quarkus of making as much build time as possible, which is the approach we took. We then would slowly add properties to runtime as required.

> Everything I specifically am using is shown in https://github.com/edeandrea/debezium-demo-apb/blob/master/roles/Demo/objects/camelk-client.yml#L29L47

Looking at your configured properties, I have categorized them.

These are all configurable at runtime.
```yaml
    infinispan.client.hotrod.use_auth=true
    infinispan.client.hotrod.auth_username=developer
    infinispan.client.hotrod.auth_password=developer
    infinispan.client.hotrod.auth_realm=default
    infinispan.client.hotrod.sasl_mechanism=SCRAM-SHA-512
    infinispan.client.hotrod.use_ssl=true
    infinispan.client.hotrod.trust_store_path=/etc/camel/conf.d/_secrets/albums-rhdg-cert-secret/tls.crt
```

I can see adding these as runtime.
```yaml
    infinispan.client.hotrod.tcp_no_delay=true
    infinispan.client.hotrod.tcp_keep_alive=false
    infinispan.client.hotrod.default_executor_factory.pool_size=1
```

I can maybe see making this runtime, but really it seems like a build time thing as your code would have to know if it has set or not. It also may provide build time optimizations.
```yaml
    infinispan.client.hotrod.force_return_values=false
```    

I don't foresee these becoming runtime, are you sure you need it at runtime? These all provide various optimizations.

```yaml
    infinispan.client.hotrod.marshaller=org.infinispan.commons.marshall.UTF8StringMarshaller
    infinispan.client.hotrod.java_serial_whitelist=java.util.ArrayList,java.util.LinkedHashMap,java.util.HashMap
    infinispan.client.hotrod.async_executor_factory=org.infinispan.client.hotrod.impl.async.DefaultAsyncExecutorFactory
    infinispan.client.hotrod.hash_function_impl.2=org.infinispan.client.hotrod.impl.consistenthash.ConsistentHashV2
    infinispan.client.hotrod.request_balancing_strategy=org.infinispan.client.hotrod.impl.transport.tcp.RoundRobinBalancingStrategy
    infinispan.client.hotrod.key_size_estimate=64
    infinispan.client.hotrod.value_size_estimate=512
```

**Comment by edeandrea** [comment]
The ones you point out I actually did notice you could set in quarkus. When I moved my camel-k migration onto the quarkus runtime I did make those changes (https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e).

The other ones (especially the marshaller) are a problem. By not being able to specify the marshaller, infinispan falls back to default serialization, which in my case is not what I want. It actually breaks my consumers of the infinispan cache, as they are expecting the keys to be String and the values to be Json. Instead the keys & values in the cache are objects.

Whether I need them at build time or compile time - I don't really know the answer to that question. All I know is that as a user using camel-k I need to be able to provide this configuration in some way and it needs to work, which it currently does not.

My current solution is that I use the `quarkus.enabled` trait to turn off quarkus as the underlying runtime and fall back to the default camel runtime, but that is going away in the next camel-k release. So right now I'm stuck with a solution where I have to muck with the camel autowiring support and fall back to the camel configuration to get it to work.

Whether its something that can be solved at build time by the camel-k operator or whether its needed at runtime - I don't know the answer to that question. @lburgazzoli ?

**Comment by lburgazzoli** [comment]
build vs runtime is not really an issue here, the main problem for camel-k is that the configuration options are spread among different files. 

@wburns I'm thinking about two possible options to make the current build time behavior a little bit mor flexible:
1. have `InfinispanPropertiesBuildItem::setup` to accept a list of `HotrodPropertiesBuildItem` (this is a new build item) so the infinispan-client extension could provide a default one from `hotrod-client.properties` but we can hook into the process and provide also our properties from an alternative source
2. derive hotrod properties from MP config directly and leverage a custom MP Config Source for backward compatibility

I can work on any of the two option if you think they are reasonable

**Comment by wburns** [comment]
I personally like option 1 so that any app can set default values for the client properties without having to use the `hotrod-client.properties` file.

**Comment by karesti** [comment]
@wburns IMO, on top of that, we should be able to override any property of the client Infinispan without using the hotrod-client.properties as we do in SB

**Comment by tqvarnst** [comment]
I'm in favour of doing 1 as well. It's only natural that you configure the client as part the application.properties since it's part of the users configuration. This also has the benefit that for example the VS code plugin will be able to auto complete the hotrod configuration for application.properties and that we already have the feature in place to mark what is build time and what is boot time properties.

**Comment by tqvarnst** [comment]
> One note though is the behavior of `quarkus.infinispan-client.trust-store` is different than `infinispan.client.hotrod.trust_store_path`. `infinispan.client.hotrod.trust_store_path` allows pointing directly to a certificate in pem format (per https://docs.jboss.org/infinispan/11.0/apidocs/org/infinispan/client/hotrod/configuration/package-summary.html), whereas `quarkus.infinispan-client.trust-store` requires importing the certificate into an actual Java trust store and specifying the path to that trust store.

@edeandrea Maybe better to create a new issue for this, since it's a new feature request.

**Comment by edeandrea** [comment]
@tqvarnst I can certainly do that. I put it here because if we are indeed going to map properties from `hotrod-client.properties` into the `infinispan-client` then shouldn't the behavior be the same? Or are you indicating that because it currently isn't the same then its a bug that needs to be addressed?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by edeandrea** [comment]
To be honest i'm not sure. @lburgazzoli ?

**Comment by edeandrea** [comment]
The PR @lburgazzoli raised (#14848) is still in draft.

**Comment by edeandrea** [comment]
> > One note though is the behavior of `quarkus.infinispan-client.trust-store` is different than `infinispan.client.hotrod.trust_store_path`. `infinispan.client.hotrod.trust_store_path` allows pointing directly to a certificate in pem format (per https://docs.jboss.org/infinispan/11.0/apidocs/org/infinispan/client/hotrod/configuration/package-summary.html), whereas `quarkus.infinispan-client.trust-store` requires importing the certificate into an actual Java trust store and specifying the path to that trust store.
> 
> @edeandrea Maybe better to create a new issue for this, since it's a new feature request.

I raised #18996 for that.

**Comment by edeandrea** [comment]
#14848 mentions that it was deferred to the infinispan team.
