### ISSUE TITLE
db-kind cannot be overridden from QuarkusTestResourceLifecycle manager

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#14367]
**Describe the bug**

I've got the following configuration at `application.properties` file:

```
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=update
```

Then I created the following QuarkusTestResourceLifecycle manager:

```
public class MariaDBResource implements QuarkusTestResourceLifecycleManager {

    static MariaDBContainer<?> db = new MariaDBContainer<>("mariadb:10.3.6")
                                            .withDatabaseName("mydb")
                                            .withUsername("developer")
                                            .withPassword("developer");

    @Override
    public Map<String, String> start() {
        db.start();
        
        final Map<String, String> conf = new HashMap<>();
        conf.put("%test.quarkus.datasource.jdbc.url", db.getJdbcUrl());
        conf.put("%test.quarkus.datasource.username", "developer");
        conf.put("%test.quarkus.datasource.password", "developer");
        conf.put("%test.quarkus.datasource.db-kind", "mariadb");
        
        return conf;

    }

    @Override
    public void stop() {
       db.stop();
    }
    
}
```

Notice that by default test profile is configured to use H2 but then I override the configuration.

**Expected behavior**

MariaDB configuration us used.

**Actual behavior**

Some of the properties are overridden but not `db-kind`.
I notice that because of the following log line:

```
WARN: Datasource '<default>': Driver does not support the provided URL: jdbc:mariadb://localhost:32785/mydb
Jan 18, 2021 3:21:28 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
```

Notice that the URL is correct but it says that the driver do not support the schema as it is taking the H2.

If then I go to `application.properties` and I change manually the `db-kind` to `mariadb` then everything works as expected.

**Environment (please complete the following information):**

Quarkus 1.10.5

**Comment by lordofthejars** [comment]
In fact what is happening is that the dialect is loaded before the QuarkusTestResource is executed:

```
INFO: HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
Jan 18, 2021 5:03:59 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusH2Dialect

2021-01-18 17:03:48,294 INFO  [org.tes.doc.DockerClientProviderStrategy] (main) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-01-18 17:03:49,126 INFO  [org.tes.doc.DockerClientProviderStrategy] (main) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2021-01-18 17:03:49,127 INFO  [org.tes.DockerClientFactory] (main) Docker host IP address is localhost
2021-01-18 17:03:49,171 INFO  [org.tes.DockerClientFactory] (main) Connected to docker: 

```

**Comment by geoand** [comment]
`quarkus.datasource.db-kind` is a build time property, it cannot be set at runtime

**Comment by lordofthejars** [comment]
Ok but then we have a problem here. Look I can have component tests and integration tests. Component tests are run in H2 and integration tests in real MariaDB. So I should be able to override this property too. I know that there is a workaround and it is creating a custom Quarkus profile where I set the db-kind. But then the test is not self contained.

**Comment by geoand** [comment]
You could also use different Maven profiles to do your testing.

Although I understand this is a limiation, it is something we've done from day 1 and something which enables various other optimizations.

cc @gsmet

**Comment by lordofthejars** [comment]
Yes, the workaround is Maven profiles and Quarkus profiles, I completely agree and I understand that if this has been there for several optimizations then it is not going to change :)
