### ISSUE TITLE
Sentry can not be configured with environment variables, VM arguments or sentry.properties file

### ISSUE THREAD

**Issue by yunusual** [quarkusio/quarkus#14373]
**Describe the bug**
Sentry Java SDK supports additional configuration sources like environment variables starting with `SENTRY_` prefix, sentry.properties files in classpath or VM arguments. This is no longer possible after the SDK version upgrade to 3.2.0 with #14153. Sentry configuration explains that these configuration options are taken into account only if `enableExternalConfiguration` is enabled, which seems to be disabled by default in `SentryOptions`. Probably this is a non-backwards compatible change.

https://docs.sentry.io/platforms/java/configuration/#configuration-methods
> To enable loading configuration from the properties file, system properties or environment variables, enableExternalConfiguration has to be set to true on SentryOptions:

**Expected behavior**
Environment properties like `SENTRY_TAGS_FIRST_TAG=first-tag-value` to appear in the Sentry event as an additional tag.

**Actual behavior**
Additional tag does not appear in the Sentry event.

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk 11.0.7
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by geoand** [comment]
cc @ia3andy

**Comment by ia3andy** [comment]
Hey @yunusual,

Thanks for taking part of making Quarkus better by posting this :)

Sentry extension is responsible of mapping the Quarkus Config to Sentry Options:
https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryHandlerValueFactory.java#L36

In Quarkus extension role of proper integrator, we never actually supported external Sentry configuration even if that was possible in previous versions because Sentry didn't allow to disable it.
The idea was to start with the most common options, then to add new Sentry configuration options as Quarkus config properties whenever they would be needed. 
Having them as Quarkus config makes them documented and easier to use for the whole community..

Here are the different possible courses of action:
1. We provide a PR to add the mapping for the options you are looking for (and continue on that path)
2. We change our plan and decide to allow external config and provide a PR in that direction

I guess you guessed that I would be in favor of 1..

Cheers,

**Comment by yunusual** [comment]
Hi @ia3andy. Thanks for the explanation. Makes sense and I'm perfectly fine with the approach of supporting configurations in Quarkus Sentry extension only. Let me explain in more detail the issue I have experienced. In its core, this is a Sentry SDK issue rather than Quarkus. 

I would like to enrich Sentry events with my transaction's MDC context, but I need them to appear as "tags" in Sentry. That's because Sentry only allows searching/filtering on tags; searching on MDC fields are not supported. This was automatically being done in Sentry in early versions of the SDK. The MDC fields would also appear as tags. But with 3.2.0, that's no longer the case and these attributes are only appearing in the MDC block (https://github.com/getsentry/sentry-java/issues/1148).

I was searching for workarounds to this and thought maybe I can do it with custom Sentry tags (e.g `SENTRY_TAGS_FIRST_TAG=...`, as I mentioned in the original post). However, I think that this is also not a good solution. For now, I have applied the following workaround to solve it. This startup block runs on application startup and introduces an `EventProcessor` hook which gets triggered before any event is broadcasted to Sentry. It enriches the event by setting all MDC fields as tags:
```
public void configureSentry(@Observes StartupEvent event) {
  HubAdapter.getInstance().configureScope(scope -> {
    scope.addEventProcessor(new EventProcessor() {
      
      @Override
      public SentryEvent process(SentryEvent event, Object hint) {
        final Map<String, String> mdcProperties = MDC.getMDCAdapter().getCopyOfContextMap();
        mdcProperties.entrySet().forEach(e -> event.setTag(e.getKey(), e.getValue()));
        return event;
      }
    });
  });
}
```

I was wondering if it would make sense to embed this logic in Quarkus' `SentryHandler.createEvent()` and enable it with a configuration key like `-Dquarkus.sentry.log.sendMdcAsTag=true`. The other option, of course, is to wait for Sentry to solve the issue on their side and they will probably introduce a similar configuration variable which we can implement in Quarkus Sentry extension. Curious what you think. Thanks!

Regards,

**Comment by ia3andy** [comment]
Hi @yunusual,

Well I think we have something like this, just slightly different, instead of tag, it's now in the context:
```
https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/src/main/java/io/quarkus/logging/sentry/SentryHandler.java#L115
```

Does that help?

Cheers,

**Comment by yunusual** [comment]
Unfortunately, it does not help. With that, Sentry only adds them to the list of MDC:
![image](https://user-images.githubusercontent.com/1414523/105062126-4f296900-5a8b-11eb-999b-6ffc5fea7c18.png)

But I need them as tags for Sentry to allow searching on them. Like this:
![image](https://user-images.githubusercontent.com/1414523/105062271-797b2680-5a8b-11eb-8d2b-6c2e71965014.png)

**Comment by ia3andy** [comment]
Ok @yunusual gotcha! 

If you have a safe and working workaround, I think it'd be better to wait. While I agree it would be nice to give the choice as you suggested, we won't have control over the SentryHandler for long as it will soon be part of the Sentry library (it was just a temporary workaround). Though we may extend it, so there may be a possibility if this is really needed.

Adding a config property means we need to support it for a while, so I would say we should wait if someone else needs it to implement something, wdyt?

**Comment by ia3andy** [comment]
If this seems reasonable, maybe we should close this bug issue and open a feature request with what you are looking for, maybe some other community members will vote for it :)

**Comment by yunusual** [comment]
Sounds good to me. The workaround is fine for now, so there is no urgency. I'll close this issue, monitor https://github.com/getsentry/sentry-java/issues/1148 for further progress by Sentry and create a new issue later if needed. Thanks for thinking along @ia3andy.
