### ISSUE TITLE
quarkus:dev maven target does not support spaces

### ISSUE THREAD

**Issue by eador** [quarkusio/quarkus#1438]
If the path where your project lives has a space in it quarkus:dev will fail to start up the application.

For example:
~/te st/quarkus-quickstarts/getting-started . <-- Will not work
~/test/quarkus-quickstarts/getting-started <-- Will work

**Comment by dmlloyd** [comment]
Fixed via #1436.

**Comment by dmlloyd** [comment]
See https://github.com/quarkusio/quarkus/issues/1673#issuecomment-477205320
