### ISSUE TITLE
Default database name, throw an exception: 'io.vertx.db2client.DB2Exception'

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#14389]
**Summary**
As is not possible to set a default DB for a given data source you must include the dbName in all your statements. If you use the default DB name given by the driver (db) you don't require to add the DB name to your statements, however, Vertx adds the default dbName to your statement in the wrong DB2 format:

**Expected behavior**
```
select * from DB.PRICINGRULES; -> will not work on DB2
 select * from "DB".PRICINGRULES; -> will work on DB2  
```

**Actual behavior**
`io.vertx.db2client.DB2Exception: The object 'DB.PRICINGRULES' provided is not defined`

**To Reproduce**

Launch DB2 with the following configuration:

```properties
## BD2
## Database
quarkus.datasource.db2.reactive=true
quarkus.datasource.db2.db-kind=db2
quarkus.datasource.db2.username=db
quarkus.datasource.db2.password=test
quarkus.datasource.db2.reactive.url=vertx-reactive:db2://localhost:50000/db

```

`docker run --name db2  -p 50000:50000 --privileged=true -e LICENSE=accept -e DB2INST1_PASSWORD=test -e DB2INSTANCE=db -e AUTOCONFIG=false -e ARCHIVE_LOGS=false -e DBNAME=db ibmcom/db2`

```
public static Multi<PricingRules> findAll(Pool client) {
    return client.query("SELECT * FROM pricingRules").execute().onItem().transformToMulti(PricingRules::fromSet);
}
```

Then -> `io.vertx.db2client.DB2Exception: The object 'DB.PRICINGRULES' provided is not defined`

External Ref:

[Jira issue](https://issues.redhat.com/browse/QUARKUS-694)

**Comment by geoand** [comment]
cc @Sanne

**Comment by tsegismont** [comment]
Cannot reproduce, please reopen if a complete reproducer can be provided
