### ISSUE TITLE
Mailer guide shows examles with CompletionStage, Quarkus way is using Uni now

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14399]
Mailer guide shows examles with CompletionStage, Quarkus way is using Uni now
Change to Uni was introduced in quarkusio/quarkus#14344

In mailer guide the signature of the methods should change and return a Uni. This is the model Quarkus recommends.
Few things about Uni vs. CS should be mentioned to explain why Uni is the way.

QS update in https://github.com/quarkusio/quarkus-quickstarts/pull/751

**Comment by glefloch** [comment]
I updated the `MailerTemplateInstance`. I can update the doc, I forget about it.

**Comment by glefloch** [comment]
Actually in `https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/mailer.adoc#message-body-based-on-qute-templates` the result of `MailerTemplateInstance#send` is already converted into a `CompletionStage` using `.subscribeAsCompletionStage`.

The docs looks up to date. However, should add a note specifying that `quarkus-resteasy-mutiny` can be used to directly return a `Uni` ? (as it done in the reactive mailer section)

@rsvoboda am I missing something?

**Comment by cescoffier** [comment]
Yes, the idea is to show the usage of Uni directly, without the need to use an intermediate CompletionStage.

**Comment by geoand** [comment]
> Actually in `https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/mailer.adoc#message-body-based-on-qute-templates` the result of `MailerTemplateInstance#send` is already converted into a `CompletionStage` using `.subscribeAsCompletionStage`.
> 
> The docs looks up to date. However, should add a note specifying that `quarkus-resteasy-mutiny` can be used to directly return a `Uni` ? (as it done in the reactive mailer section)
> 

Or just use `quarkus-resteasy-reactive` 😉

**Comment by cescoffier** [comment]
@geoand well, you are right! With 0.12.0, it's time for us to push it more.
