### ISSUE TITLE
Resteasy-Reactive: Wrong blocking configuration handling in ResteasyReactiveScanner 

### ISSUE THREAD

**Issue by heubeck** [quarkusio/quarkus#14397]
Blocking configuration issue in ResteasyReactiveScanner:

https://github.com/quarkusio/quarkus/blob/master/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ResteasyReactiveScanner.java#L87

the following for sure is not intended:
```java
// Line 87ff:
            if (applicationClassInfo.classAnnotation(ResteasyReactiveDotNames.NON_BLOCKING) != null) {
                blocking = false;
            } else if (applicationClassInfo.classAnnotation(ResteasyReactiveDotNames.NON_BLOCKING) != null) {
                blocking = true;
            }
```

**Comment by gsmet** [comment]
I discussed with @heubeck on Zulip. The issue is that both conditions are exactly the same which looks very suspicious.

**Comment by geoand** [comment]
Let me check

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14400 fixes the issue
