### ISSUE TITLE
quarkus:dev's debugHost not configurable

### ISSUE THREAD

**Issue by slinstaedt** [quarkusio/quarkus#14403]
We are running development environments and tools in containers and trying to separate responsibilities not only in separate containers (and also pods, so colocation is not really a solution). One of the ideas was separate IDE pods from the actual application (quarkus-based, in this occasion) being in development. The challenge for us is, to make relevant ports from the application in development available at least to the IDE container.

When running` mvn quarkus:dev`, application's port is only bound to loopback interface, which is luckily configurable e.g. via enviroment variable `QUARKUS_HTTP_HOST=0.0.0.0`. The same problem applies to other ports like the debug port, which is opened by the maven plugin. Unfortunately it looks like there is currently no way to change this configuration, even though most of the code to do so is already there (have a look at `io.quarkus.maven.DevMojo#debugHost`).

**Expected behavior**
When running `mvn quarkus:dev` debug port is bound to 127.0.0.1 by default, but is configurable somehow. 

**Actual behavior**
Running `mvn quarkus:dev` debug port is bound to 127.0.0.1 and not configurable.

**To Reproduce**
Without containering: Start any quarkus application using `mvn quarkus:dev` and from the same machine try to connect to it using `jdb -attach $(hostname):5005`. `jdb -attach localhost:5005` is working fine for reference.

**Comment by stuartwdouglas** [comment]
You should be able to do mvn quarkus:dev -DdebugHost=0.0.0.0

**Comment by geoand** [comment]
I added a documentation note about that at https://github.com/quarkusio/quarkus/pull/14421

**Comment by slinstaedt** [comment]
> You should be able to do mvn quarkus:dev -DdebugHost=0.0.0.0

Yep, that is what I already tried. I am not an expert for maven plugins, but the last time I wrote one, you needed to set a property (name) for your injected @Parameter.  Otherwise system properties are not considered.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/blob/1.11/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L190

**Comment by slinstaedt** [comment]
Thats the line, sorry for not linking it. You can configure this line using the plugin's <configuration/> block, but not using system properties, afaik. Would be nice, if someone can verify this.

**Comment by geoand** [comment]
That should also work

**Comment by slinstaedt** [comment]
Please run `mvn -X quarkus:dev -DdebugHost=0.0.0.0` on a vanilla quarkus app yourself and search the last parts of the logs for "debugHost":

```
DEBUG] Launching JVM with command line: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home/bin/java -DdebugHost=0.0.0.0 -XX:TieredStopAtLevel=1 -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager --enable-preview -jar /Users/sven/work/quarkus-example/target/quarkus-example-dev.jar
Listening for transport dt_socket at address: 5005
```

Using quarkus 1.10.5.Final

**Comment by gsmet** [comment]
Reopening as the OP says it doesn't help AFAICS.

**Comment by geoand** [comment]
I'll have another look later
