### ISSUE TITLE
dev mode: support suppressing warnign about non existing source directory

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#14402]
**Description**

Since version 1.3.0, [camel-k](https://github.com/apache/camel-k) has switched to Quarkus as default runtime. For troubleshooting purpose we have some pure java based examples which I'm now migrating to use `quarkus:dev` instead of the `exec-maven-plugin` and since in camel-k we basically do composition, we don't have any source in project and that leads to the following warning:

```
The project's sources directory does not exist /home/codespace/workspace/camel-k-runtime-example-kamelets/src/main/java
```

As it is perfectly fine for a camel-k project to be "source free", it would be nice to add an option to silence such warning

**Comment by geoand** [comment]
What sort of option are you thinking of @lburgazzoli ?

**Comment by aloubyansky** [comment]
Simply removing the warning, afaiu.

**Comment by geoand** [comment]
But isn't that warning useful for some users?

**Comment by aloubyansky** [comment]
@lburgazzoli you do provide the resources dir with the application.properties, don't you? So in that case this is the only file that will be hot-reloadable. We probably need to adjust the check to include the resources dir in it.

**Comment by lburgazzoli** [comment]
@geoand a property like the `<noDeps>true</noDeps>`, maybe `<noSources>true</noSources>` / `<noResources>true</noResources>`
@aloubyansky we can have an application.properties but it is not strictly mandatory as camel-k dev supports adds all the files that are relevant for camel-k among the hot-reloadables

**Comment by geoand** [comment]
Sounds good to me, but @aloubyansky is the SME here, so let's see what he says

**Comment by gsmet** [comment]
Does this warning really have value? I would be in favor of just dropping it if it's in the way of some use cases.

**Comment by aloubyansky** [comment]
I tend to agree with @gsmet. If somebody complains we can reconsider.

**Comment by geoand** [comment]
OK, fine with me

**Comment by lburgazzoli** [comment]
@gsapountzis @geoand @aloubyansky thx
