### ISSUE TITLE
Unrecognized configuration key "quarkus.kubernetes.deploy" was provided

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#14429]
**Describe the bug**
When deploying Quarkus application on OpenShift via `./mvnw clean package -Dquarkus.kubernetes.deploy=true` then
during the Maven test phase a warning shows up:

```WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.kubernetes.deploy" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo```

P.S the application is deployed successfully though

**Expected behavior**
The warning should be suppressed.

**To Reproduce**

1. Create a simple quarkus bootstrap project with openshift extension
2. Run `./mvnw clean package -Dquarkus.kubernetes.deploy=true`

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14433 should take care of this
