### ISSUE TITLE
Kubernetes: liveness and readiness probes ignore the `quarkus.http.root-path` setting

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#14438]
Seems that we have a [regression issue](https://github.com/quarkusio/quarkus/issues/6833): 
Works on 1.7
Fails on 1.11.0.Final

[Jira Ref](https://issues.redhat.com/browse/QUARKUS-705)

**Comment by geoand** [comment]
Thanks, I'll look into it
