### ISSUE TITLE
Open API logo customization not affecting

### ISSUE THREAD

**Issue by hhovhann** [quarkusio/quarkus#14431]
https://github.com/quarkusio/quarkus/blob/842b3f2b943d066512bc032d488f8b3188b2c53c/core/deployment/src/main/java/io/quarkus/deployment/util/WebJarUtil.java#L83

**Environment** 

Java 11
OS Windows 10
Quarkus 1.0.12:

Dear all, thanks a lot for your great job and nice framework. 
Followed the steps how can customize the openapi logo in topic [Stylish API](https://quarkus.io/blog/stylish-api/), but was not able to change and use custom logo based on steps.

If once I have already started app with openapi dependency it's creating and populating the directory, in my case on **Windows** was
C:\Users\<my_user>\AppData\Local\Temp\quarkus\drp\io.smallrye\smallrye-open-api-ui\2.0.15, so when I am trying to customize the logo following the documentation isn't working.
The reason is that directory not open and that piece of code which is creating all resources including new logo is not modifying at all. 
My Workaround was just cleaning both directories for `smallrye-open-api-ui` and `smallrye-open-api-ui` and rerun the application.

Make sense to track somehow or check if in directory we have new logo added or style.css etc.

Thanks in advance

**Comment by Postremus** [comment]
Can confirm, I also was unable tot customize the Logo in 1.10.3.Final.

Hayk Hovhannisyan <notifications@github.com> schrieb am Mi., 20. Jan. 2021,
14:21:

**Comment by phillip-kruger** [comment]
Hi @hhovhann and @Postremus 

Thanks for this . Can you please give me some more context:
1) Are you only talking about dev more ? (`mvn quarkus:dev`). So if you build a jar or native, does the branding work ?
2) If in dev mode, when you do `mvn clean install quarkus:dev` does it work then ?
3) Are you trying to update the branding while running the app in dev mode ? (As hot reload is not supported on these files)

Thanks !

**Comment by hhovhann** [comment]
Hi @phillip-kruger 
1. Yes I only tried with dev mode.
2. I am running with `./mvnw -Pdrp -Dquarkus.profile=drp clean compile quarkus:dev`
3. I updated and then rerun, clear from browser clear storage clear site data and then rerun with the command from step 2.

Thanks & Regards

**Comment by phillip-kruger** [comment]
Hi @hhovhann 
Thanks for the reply. So it might be a Windows issue then ? Can you share a small reproducer ?

**Comment by hhovhann** [comment]
Hi @phillip-kruger
My steps was something like this, I just moved from here the profile parts, I think that is not the case here.

1. Create Quarkus app with quarkus-smallrye-openapi
2. Run the app with ./mvnw clean compile quarkus:dev
3. Visit localhost:8080/swagger-ui and http://localhost:8080/health-ui to see the default logo
4. Add logo.png and style.css under src/main/resources/META-INF/branding folder
5. Rerun the application
6. Open browser clear old site data

**Expected Result:** Modified logo in both swagger-ui and health-ui
**Actual Result:** Quarkus logo still was there

[Here is ](https://github.com/hhovhann/code-with-quarkus-openapi) I have created the project without adding META-INF/branding and custom logo.png and style.css:  
Can use it in your local Windows Env if you have, run it then modify and checking the behavior.
First time it needs to be run with default without adding logo.png and style.css under src/main/resources/META-INF/branding folder.

Regards

**Comment by phillip-kruger** [comment]
Thanks @hhovhann I'll have a look. So are you restarting the app between the old and new branding? Again hot reloading is not supported

**Comment by hhovhann** [comment]
Yes I started without new logo then stoping it and starting again with
already modified logo.
And as I found only index.html file is revisiting because I saw datetime
was changed for that file with comparison of others like favicon etc.

Regards

**Comment by phillip-kruger** [comment]
Ok I'll try it out on my environment in a few minutes and get back to you

**Comment by hhovhann** [comment]
@phillip-kruger In my last example:reproducer the last version of quarkus is `1.11.0.Final`.
Thanks

**Comment by phillip-kruger** [comment]
@hhovhann - your app works perfect on my environment. 

https://user-images.githubusercontent.com/6836179/105221501-dfd27880-5b61-11eb-8bbf-16bab399d6e4.mp4

- Make sure to use `mvn clean install quarkus:dev` (note the **install**) - package should also work (so `mvn clean package quarkus:dev`
- Make sure it' not your browser cache (so do a shift-f5) 
- If it still does not work, then it might be a Windows specific issue. If that is the case I can look at it tomorrow (I need to setup windows on a VM first, so need some time)

Let me know.

**Comment by hhovhann** [comment]
@phillip-kruger it works with `mvn clean package quarkus:dev`.
Thanks and please let something added in documentation about package/install instead of compile in case if someone else will do that.
Thanks

**Comment by phillip-kruger** [comment]
Thanks @hhovhann.
Let's keep this open so that @Postremus can confirm his case and that I have a reminder to update the blog post with this information.

**Comment by gsmet** [comment]
Hmmm, I think it's going to be an issue if `package` is required. AFAIK, `quarkus:dev` only implies `compile`.

**Comment by phillip-kruger** [comment]
I will investigate if I can change that.

**Comment by phillip-kruger** [comment]
Hi @gsmet, @hhovhann and @Postremus 

I ended up just implementing hot reload support. That solves the issue of what mvn command works. 
And app without any custom branding can now be started in dev mode and branding can be added while running.

See #14499

**Comment by nragon** [comment]
I have third level child module with META-INF/branding which is not going to generated-bytecode on swagger-ui during package.
Is this related?

**Comment by phillip-kruger** [comment]
No I do not think this is related. We only scan first level.

**Comment by nragon** [comment]
> No I do not think this is related. We only scan first level.

Should this be open as enhancement?

**Comment by phillip-kruger** [comment]
You are welcome to open a new issue :)
