### ISSUE TITLE
Java Naming Convention for groupId

### ISSUE THREAD

**Issue by BeRoots** [quarkusio/quarkus#14435]
**Describe the bug**
When I build project from a command like `mvn io.quarkus:quarkus-maven-plugin:1.10.5.Final:create` and I fill my groudId then the underscore isn't interpreted as well and my package folder structure is broken. Two separated folder on the groudId domain part.

**Expected behavior**
The groupId like org.my-domain should be org.my_domain and generate namespace like org.my_domain... and package structure like src/main/java/org/my_domain/...

**Actual behavior**
The groupId like org.my-domain generate namespace like org.my.domain... and package structure like src/main/java/org/my/domain/...

**To Reproduce**
Shell example:
```user@host:/tmp$ mvn io.quarkus:quarkus-maven-plugin:1.10.5.Final:create
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.10.5.Final:create (default-cli) @ standalone-pom ---
Set the project groupId [org.acme]: org.my_company
Set the project artifactId [code-with-quarkus]: 
Set the project version [1.0.0-SNAPSHOT]: 
What extensions do you wish to add (comma separated list) [resteasy]: 
Do you want example code to get started (yes), or just an empty project (no) [yes]: yes
-----------
selected extensions: 
- io.quarkus:quarkus-resteasy


applying codestarts...
🔠 java
🧰 maven
🗃 quarkus
📜 config-properties
🛠 dockerfiles
🛠 maven-wrapper
🐒 resteasy-example

-----------
👍 quarkus project has been successfully generated in:
--> /tmp/code-with-quarkus
-----------
[INFO] 
[INFO] ========================================================================================
[INFO] Your new application has been created in /tmp/code-with-quarkus
[INFO] Navigate into this directory and launch your application with mvn quarkus:dev
[INFO] Your application will be accessible on http://localhost:8080
[INFO] ========================================================================================
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.570 s
[INFO] Finished at: 2021-01-20T15:28:52+01:00
[INFO] ------------------------------------------------------------------------
```
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux host.me.local 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 
 - Output of `java -version`:
 ```openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```
 - GraalVM version (if different from Java): `unused`
 - Quarkus version or git rev: `io.quarkus:quarkus-maven-plugin:1.10.5.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `mvn`

**Additional context**
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by ia3andy** [comment]
This has been here for a while (it was already in legacy).

This would be an easy fix, we just have to remove the `_` replace to `.` there:
https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/CreateProjectCommandHandler.java#L72

and there for the legacy:
https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/LegacyCreateProjectCommandHandler.java#L74

I am personally not a big fan of `_` in package names but after all it's up to the developer I guess since it's in the java naming convention..

**Comment by gsmet** [comment]
I think we should just drop the `-` in this case. I think it makes for a better default behavior. I'll have a look at it.

**Comment by geoand** [comment]
I just tried this and the problem no longer occurs in `3.14.4` so I will close this
