### ISSUE TITLE
Quickstart link broken in  spring-data-rest guide

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#14440]
**Describe the bug**
https://quarkus.io/guides/spring-data-rest#solution

the link to the quickstart is broken: https://github.com/quarkusio/quarkus-quickstarts/tree/master/spring-data-rest-quickstart

**Comment by geoand** [comment]
@aureamunoz can you please take a look?

**Comment by gsmet** [comment]
The PR is here https://github.com/quarkusio/quarkus-quickstarts/pull/714 but was never merged.

**Comment by geoand** [comment]
Also cc @gytis

**Comment by gsmet** [comment]
For now, the quickstarts are broken due to a change in the Mailer API. I will rebase the PR as soon as I merge the fix.

**Comment by aureamunoz** [comment]
Ok, Thanks @gsmet. Let us know if you need something from us.

**Comment by gsmet** [comment]
@gytis @aureamunoz the quickstart tests didn't pass on CI, please have a look: https://github.com/quarkusio/quarkus-quickstarts/pull/714

**Comment by gytis** [comment]
I can take a look. I have totally forgot about that PR to be honest.
