### ISSUE TITLE
Quarkus Funqy Knative Events guide

### ISSUE THREAD

**Issue by sshaaf** [quarkusio/quarkus#14454]
**Describe the bug**
The Quarkus funqy knative events guide has the following issues:
- yaml files are missing spec for broker
- Curler is mentioned but not present.

source: https://quarkus.io/guides/funqy-knative-events

**Comment by matejvasek** [comment]
@sshaaf has this been fixed by your PRs?

**Comment by sshaaf** [comment]
yes they should be

**Comment by sshaaf** [comment]
Closing issue, PRs have the fix
