### ISSUE TITLE
Broken quickstart link in reactive-messaging-http-quickstart guide 

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#14451]
**Describe the bug**
https://quarkus.io/guides/reactive-messaging-http

https://github.com/quarkusio/quarkus-quickstarts/tree/master/reactive-messaging-http-quickstart

This is the second one I find today #14440, it would be nice to have a review of all our guides quickstart links. @gsmet could you put someone on it?

**Comment by gsmet** [comment]
Well, it's the responsibility of the person merging the extension and the documentation to check this.

**Comment by gsmet** [comment]
Apparently, it has been created here https://github.com/quarkusio/quarkus-quickstarts/pull/721 but never merged.

**Comment by gsmet** [comment]
Fixed.
