### ISSUE TITLE
RESTEasy Reactive Jackson dependes on JSONP 

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#14469]
**Describe the bug**
The quarkus-resteasy-reactive-jackson extension dependens on quarkus-jackson and quarkus-jsonp.

**Expected behavior**
I would expect quarkus-resteasy-reactive-jackson extendsion to only depend on the quarkus-jackson extension.

**Actual behavior**
The quarkus-resteasy-reactive-jackson extension dependens on both the quarkus-jackson and quarkus-jsonp extension.

**To Reproduce**
1. add the following extension to a basic project using version 1.11.0.Final:
```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>
```

**Workaround**
Excluding quarkus-jsonp resolves the issue as a workaround.

**Environment:**
Not important for the issue.

**Comment by geoand** [comment]
Jsonp support is mandated by the JAX-RS spec IIRC, which is why RESTEasy Reactive has a hard dependency on it

I don't think that Jackson implements jsonp, but I can give it a quick check.

**Comment by geoand** [comment]
I just checked and Jackson itself doesn't implement the JSONP spec itself, so there is nothing we can do here.

**Comment by bpasson** [comment]
Thanks, sorry for the inconvenience in the extra work it gave you.

**Comment by geoand** [comment]
No inconvenience at all!

Thanks for the feedback!
