### ISSUE TITLE
smallrye-jwt extension stopped working on 1.11.0.Final (package io.smallrye.jwt.build not found)

### ISSUE THREAD

**Issue by casmeiron** [quarkusio/quarkus#14464]
### 1.10.5.Final ###

In version **1.10.5.Final** I just needed to add the extension '**smallrye-jwt**' to make JWT works. The class **io.smallrye.jwt.build.JWT** is used to generate a new token.

### 1.11.0.Final ###

Upgrading to **1.11.0.Final** the package '**io.smallrye.jwt.build**' doesn't exists anymore so I've found in the GUIDES section that I had to add another extension named '**smallrye-jwt-build**'. Even thought the mentioned extension was incorporated in my POM, the package still not valid. 

Im rolling back to the previous version. Any thoughts on that? I don't think its something with my build because when I inspected the jar for 'smallrye-jwt-build' its empty (no java classes).

Thanks.

**Comment by GAlexMES** [comment]
@casmeiron You need the package `io.quarkus:quarkus-smallrye-jwt-build` not `smallrye-jwt-build`
See: https://mvnrepository.com/artifact/io.quarkus/quarkus-smallrye-jwt-build

**Comment by sberyozkin** [comment]
@casmeiron, all, sorry - it is now documented. It was important to decouple the JWT generation API from the core smallrye-jwt code - sometimes one wants to generate the tokens against a non-MP-JWT server and likewise, which is probably more important, is that I'd say most MP-JWT server endpoints do not need this API to verify a token, may be 20% only...

@casmeiron Can you please close this issue once you confirm adding the quarkus extension as recommended by @GAlexMES works for you ?
Thanks

**Comment by casmeiron** [comment]
Ok, after following @GAlexMES suggestion now its working with the latest version.

Thanks very much!
