### ISSUE TITLE
REST: `Form` is empty if `@FormParam` is used at the same time.

### ISSUE THREAD

**Issue by defnull** [quarkusio/quarkus#14473]
**Describe the bug**
Using `@FormParam` causes the `MessageBodyReader` for `Form` or `MultivaluedMap<String, String>` to not work correctly. They do not fail or log a warning, but silently return an empty map. **Edit: Issue only happens when testing (with restassured), NOT in production or dev mode.**

**Expected behavior**
A `Form` or `MultivaluedMap<String, String>` should contain all form fields submitted by the client, even if some of them are extracted separately by `@FormParam`.

**Actual behavior**
A `Form` or `MultivaluedMap<String, String>` is empty if combined with `@FormParam` on the same method.

**To Reproduce**

    @POST
    @Path("/test")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public void test(@FormParam("foo") String foo, Form form) {
        assert ! form.asMap().isEmpty();
    }

1. Spin up a minimal REST app accepting `Form` and a `@FormParam` parameter at the same time.
2. `curl -d foo=bar localhost:8080/test`
3. `Form` should contain data, but does not.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.11.0.Final

**Comment by gsmet** [comment]
@defnull is it with RESTEasy or RESTEasy Reactive?

**Comment by defnull** [comment]
Just RESTEasy (+jackson)

**Comment by gsmet** [comment]
If you could come up with a small reproducer, that would be helpful.

**Comment by defnull** [comment]
While trying to create a reproducer, I could not reproduce the error. I'm not sure yet where the difference is. I'll investigate. You may close this issue and I'll open another once I can actually reproduce it.

**Comment by defnull** [comment]
The error happens during tests only, not when running the service and actually issuing requests. I'll try this in the reproducer.

**Comment by defnull** [comment]
Yes, that's it. The problem seems to be related with the quarkus test framework? Here is a reproducing example:

    https://github.com/defnull/quarkus-issue
    cd quarkus-issue
    mvn test

**Comment by geoand** [comment]
This is a known limitation in RESTEasy. From https://docs.jboss.org/resteasy/docs/4.5.9.Final/userguide/html/_FormParam.html:

```
You cannot combine @FormParam with the default "application/x-www-form-urlencoded" that unmarshalls to a MultivaluedMap<String, String>
```
