### ISSUE TITLE
Properties in bootstrap app for 1.11 are in random order, 1.7 had them alphabetically sorted

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14478]
Properties in bootstrap app for 1.11 are in random order, 1.7 had them sorted alphabetically

1.11.0.Final:
```xml
  <properties>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <quarkus.platform.version>1.11.0.Final</quarkus.platform.version>
    <maven.compiler.target>8</maven.compiler.target>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus-plugin.version>1.11.0.Final</quarkus-plugin.version>
    <maven.compiler.source>8</maven.compiler.source>
  </properties>
```

1.7.6.Final
```xml
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.7.6.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.7.6.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
```

Used commands:
```
mvn io.quarkus:quarkus-maven-plugin:1.11.0.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started \
  -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello"
mvn io.quarkus:quarkus-maven-plugin:1.7.6.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started-old \
  -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello" -DplatformVersion=1.7.6.Final
```

**Comment by gsmet** [comment]
@rsvoboda let's be a bit more cautious about what we consider a bug. This is not one.

**Comment by rsvoboda** [comment]
It's a regression from usability perspective, thus I went ahead with bug type.

**Comment by ia3andy** [comment]
cc @gastaldi it's the Smart Merger :-/

**Comment by gastaldi** [comment]
@ia3andy can you provide a reproducer? This hasn't changed since last September (https://github.com/fabric8-launcher/maven-model-helper/commits/v16)

**Comment by gsmet** [comment]
But we weren't using that one before, right? @rsvoboda is comparing this to 1.7 so a very old version.

**Comment by ia3andy** [comment]
The codestarts use the (fabric8-launcher/maven-model-helper) and `1.7` was using the legacy codegen.

@gastaldi remember you already tried to fix it but said it wasn't possible because properties were not ordered or something?

**Comment by gsmet** [comment]
There's something that says sorted here: https://github.com/fabric8-launcher/maven-model-helper/blob/v16/src/main/java/io/fabric8/maven/merge/SortedProperties.java

:)

**Comment by ia3andy** [comment]
@gastaldi maybe I should set something when calling?

https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/codestarts/src/main/java/io/quarkus/devtools/codestarts/core/strategy/SmartPomMergeCodestartFileStrategyHandler.java#L42

**Comment by gastaldi** [comment]
@ia3andy you shouldn't have to, because it's handled in https://github.com/fabric8-launcher/maven-model-helper/blob/master/src/main/java/io/fabric8/maven/merge/SmartModelMerger.java#L29-L41. 

Can you add a breakpoint in that line and check if the `Properties` in the Maven model is a `SortedProperties`?

**Comment by ia3andy** [comment]
I think I found the problem, the fabric8-launcher/maven-model-helper `Maven.readModel` and `Maven.writeModel` are not using the `SortedProperties` and when there is one pom only, it's not using the `SmartModelMerger`. @gastaldi is on it..

**Comment by gsmet** [comment]
Nice work, folks!
