### ISSUE TITLE
Dev UI card for Hibernate Search

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#14484]
I think it would be nice to have a Hibernate Search card and a few features exposed in the newly added Dev UI (https://quarkus.io/guides/dev-ui).

I was thinking we could have:
- full reindexing of all entities
- indexing of some of the entities (with a multi select box)

**Comment by glefloch** [comment]
I would definitely be interested into working on this if this is ok for everyone.

**Comment by gsmet** [comment]
@glefloch Sure!

**Comment by yrodiere** [comment]
@glefloch That would be great, thanks!

Some information that you may find useful:

* You can access the `SearchMapping` from Arc, it's a bean
* You can use `org.hibernate.search.mapper.orm.mapping.SearchMapping#allIndexedEntities` to list all indexed entities
* You can use `mapping.scope( MyClass.class ).massIndexer()` to create a mass indexer; no need to open a transaction.
* As a second step, we could provide a way to make it work when multi-tenancy is enabled: `mapping.scope( MyClass.class ).massIndexer( tenantId )`

**Comment by glefloch** [comment]
Thanks for all those infos!
