### ISSUE TITLE
OIDC Client > Cannot overwrite properties

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#14480]
**Describe the bug**
Question about override properties for Quarkus apps:

The thing is that when deploying these apps into OpenShift, the apps are failing because:

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ // / // / __ |/ , / ,< / // /\ \
--\___\\____// |//|//|_|\____/___/
2021-01-21 11:07:36,224 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.net.ConnectException: Connection refused
    at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

I've checked that the problem is that the OIDC client properties are not being replaced correctly. These are the environment properties that I'm passing:

`QUARKUS_OIDC_AUTH_SERVER_URL` (this property is for the existing OIDC extension and it's working fine: it's mapped to `quarkus.oidc.auth-server-url`)
`QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL` (this should be mapped to `quarkus.oidc-client.auth-server-url`)

Same with the OIDC Client tenants. 

**Expected behavior**
The new extensions should work as the existing OIDC extension being able to overwrite properties when deploying apps into the cloud via environment properties.

**Actual behavior**
Application is failing to start.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.11.0.Final and master

**Comment by sberyozkin** [comment]
Interesting, I thought I knew where the problem was but I'm not sure now.
So I've mirrored it the way it is done for `quarkus-oidc` where:
- [OidcTenantConfig](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java) is a `ConfigGroup`
- [OidcConfig](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcConfig.java) is a `ConfigRoot` with a runtime scope which holds the default and tenant-specific configurations

**Comment by sberyozkin** [comment]
I wonder if it is the name of the classes, the `ConfigRoot` class should be called `OidcClient` and the `ConfigGroup` one renamed from `OidcClientConfig` to OidcClientTenantConfig` ?

**Comment by radcortez** [comment]
I'll have a look.

**Comment by bwand** [comment]
Hi, I do get exactly the same error without any overriding of config. Just setup oidc-client, tested it in Dev Mode and everything worked fine.

Then build Docker Container and start it and I get this error and quarkus app refuses to start

```
docker@vsldocker14:~/flows$ docker logs admin --follow
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-01-21 14:03:26,107 INFO  [io.qua.oid.run.OidcRecorder] (main) Connecting to IDP for up to 45 times every 2 seconds
2021-01-21 14:03:26,920 INFO  [io.qua.oid.cli.run.OidcClientRecorder] (main) Connecting to IDP for up to 45 times every 2 seconds
2021-01-21 14:03:26,973 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by radcortez** [comment]
@Sgitario @bwand can you please try something for me?

Remove any configuration you may have in the application for `quarkus.oidc-client.auth-server-url` and `quarkus.oidc-client.client-id`. If you try to start, Quarkus should complain that these properties are required.

And then try to set it up as an env variable to see if the error is the same (meaning that the property is not being read) or if it shows the reported error, it means it was read but there is some other issue.

I've tried this is a local sample, and I didn't spot any issue with Docker and Env variables.

**Comment by Sgitario** [comment]
> @Sgitario @bwand can you please try something for me?
> 
> Remove any configuration you may have in the application for `quarkus.oidc-client.auth-server-url` and `quarkus.oidc-client.client-id`. If you try to start, Quarkus should complain that these properties are required.
> 
> And then try to set it up as an env variable to see if the error is the same (meaning that the property is not being read) or if it shows the reported error, it means it was read but there is some other issue.
> 
> I've tried this is a local sample, and I didn't spot any issue with Docker and Env variables.

Thanks for looking into this @radcortez . I tried what you suggested and it worked for me. However, when using a more complex scenario (tenant configuration), it's still not working, for example:
These are the environment properties that I'm passing:

- `QUARKUS_OIDC_AUTH_SERVER_URL` (this property is for the existing OIDC extension and it's working fine: it's mapped to `quarkus.oidc.auth-server-url`)
- `QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL` (this should be mapped to `quarkus.oidc-client.auth-server-url`)
- `QUARKUS_OIDC_CLIENT_NORMAL_USER_AUTH_SERVER_URL` (this is a tenant I'm using in my example and it should be mapped to `quarkus.oidc-client.normal-user.auth-server-url`)
- `QUARKUS_OIDC_CLIENT_ADMIN_USER_AUTH_SERVER_URL` (same, it should be mapped to `quarkus.oidc-client.admin-user.auth-server-url`)
- `QUARKUS_OIDC_CLIENT_JWT_SECRET_AUTH_SERVER_URL` (same, it should be mapped to `quarkus.oidc-client.jwt-secret.auth-server-url`)

**Comment by bwand** [comment]
> @Sgitario @bwand can you please try something for me?
> 
> Remove any configuration you may have in the application for `quarkus.oidc-client.auth-server-url` and `quarkus.oidc-client.client-id`. If you try to start, Quarkus should complain that these properties are required.
> 
> And then try to set it up as an env variable to see if the error is the same (meaning that the property is not being read) or if it shows the reported error, it means it was read but there is some other issue.
> 
> I've tried this is a local sample, and I didn't spot any issue with Docker and Env variables.

Hi @radcortez I tried what you suggested. Removed all oidc-client config from application.config results to
```
bwand@bwand-mac.local [~/Development/Flows2/flow-definition-module/admin]$ docker logs admin --follow
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-01-22 08:47:11,200 INFO  [io.qua.oid.run.OidcRecorder] (main) Connecting to IDP for up to 45 times every 2 seconds
Both 'auth-server-url' and 'client-id' properties must be configured
```
Then try to start the docker container via:
`docker run -d --name=admin --net=flows -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/flows -e QUARKUS_OIDC_CLIENT_CLIENT_ID=admin -e QUARKUS_OIDC_CLIENT_CREDENTIALS.SECRET=XXXXXXXXXXXXXX --rm -p 8095:8095 flows/admin-jvm`

Keeps getting the same error, so in my case this seems to be not a problem of overriding stuff:
```
bwand@bwand-mac.local [~/Development/Flows2/flow-definition-module/admin]$ docker logs admin --follow
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-01-22 08:56:32,896 INFO  [io.qua.oid.run.OidcRecorder] (main) Connecting to IDP for up to 45 times every 2 seconds
2021-01-22 08:56:34,216 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sberyozkin** [comment]
@Sgitario Hi - have you tried overriding `quarkus-oidc` tenant specific properties before ? thanks

**Comment by sberyozkin** [comment]
@bwand Hi, the Vert.x client is created [here](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L103). The tests depend on the Keycloak running in docker. In your case, it connects to Keycloak when you set the properties in `application.properties`, correct ? So it looks like the system properties have not been picked up... Perhaps you can try set a breakpoint and check what the client is actually initialized with ?
thanks

**Comment by sd-f** [comment]
It seems properties `ssl` and `host` of WebClientOptions are always set to false and localhost in OIdcClientRecorder:107.

**Comment by bwand** [comment]
Hi @sd-f, this would match to my scenario where it can reach the Keycloak over localhost when I start application from dev mode.
But it cannot reach Keycloak via internal docker URL http://keycloak:8080...

**Comment by sd-f** [comment]
I'll try fixing that locally and do some tests

**Comment by radcortez** [comment]
Yes, I was suspecting that the issue was related with the docker or any other environment not being able to reach the server than a configuration issue, that is why I've asked to do that test.

Now that we seem to have a cause, I'll try to setup an environment to test this properly.

**Comment by sd-f** [comment]
I am not sure about the vertx webclient, but as i understand it is setting host and ssl if options parameter is passed on create. Usally this is done by parsing absolute uris, but in this case options is passed and the parser ist skipped.

Everything works great when settings host and ssl in options as can be seen in:

https://github.com/quarkusio/quarkus/compare/master...sd-f:oidc-client-webclient-options

**Comment by sberyozkin** [comment]
@sd-f Great, thanks for finding this code - I see the similar updates are done inside Vertx Oauth2 when doing a request.

can you open a PR please - we can then ask Guillaume to backport ? I'd only consider renaming this method to `setWebClientOptions`, `OidcCommonUtils.setHttpOptions` is used both by `quarkus-oidc-client` and `quarkus-oidc` but for now lets keep this code inside `OidcClientRecorder`

thanks

**Comment by sberyozkin** [comment]
@cescoffier hey Clement - would it make sense to have this code @sd-f has posted be part of a helper method like `WebClientOptions.newOptions(authServerUrl)` or similar ? thanks

**Comment by sd-f** [comment]
@sberyozkin https://github.com/quarkusio/quarkus/pull/14521 the right place would be common util module i guess, I was note sure about side effects.

**Comment by sberyozkin** [comment]
@sd-f right, at the moment `quarkus-oidc` is using vertx web client indirectly so indeed it is better to keep it separate for now

**Comment by sberyozkin** [comment]
@radcortez 

> Yes, I was suspecting that the issue was related with the docker or any other environment not being able to reach the server than a configuration issue, that is why I've asked to do that test.

thanks for it :-)

**Comment by sberyozkin** [comment]
Hi @Sgitario, so @sd-f has provided a PR which will close this issue. The only remaining problem then is overriding the tenant specific properties does not work - please check next week if you can override them with `quarkus-oidc` - I wonder if it is a general problem with the `Map` properties - and then please open a new issue
thanks all

**Comment by sd-f** [comment]
@Sgitario If you want to test it I deployed a preview version to my nexus.

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc-client</artifactId>
            <version>1.11.1.Alpha0</version>
        </dependency>
 ```

 ```
  <repositories>
    <repository>
      <id>co-community-third-party</id>
      <name>CAMPUSonline Community Third Party</name>
      <url>https://nexus.campusonline.community/repository/third-party</url>
    </repository>
    ...
  </repositories>
 ```
 
 It also contains the final fix from PR https://github.com/quarkusio/quarkus/pull/14543
 
 Hint: absolutely not official ;)

**Comment by bwand** [comment]
Thanks for the quick fix of this problem. I can see that it is currently fixed for Version 1.12. 
As the feature is not usable when only relying on localhost I would like to ask if it qill be backported to next minor version 1.11.1? I see the triage/backport? label on the PR but what does that mean?

**Comment by sd-f** [comment]
@sberyozkin can you answer @bwand s question? I am not sure about the release backport processes ;)

**Comment by sberyozkin** [comment]
@bwand the PR and the follow up PR opened by @sd-f have a `triage/backport?` label - so @gsmet would consider them for backporting if he agrees
