### ISSUE TITLE
Running quarkus:dev in-container on OpenShift "fails" (ends build)

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1449]
I'm experimenting with something re. #1390 and for me running `mvn compile quarkus:dev` in-container on OpenShift strangely just ends the build instead of serving the applications... where as it normally is:

```
mvn clean compile quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building quarkus-quickstart 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ quarkus-quickstart ---
[INFO] Deleting /home/vorburger/dev/Quarkus/git/quarkus/docker/centos-dev-java11/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quarkus-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/vorburger/dev/Quarkus/git/quarkus/docker/centos-dev-java11/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:0.11.0:dev (default-cli) @ quarkus-quickstart ---
[INFO] Using servlet resources /home/vorburger/dev/Quarkus/git/quarkus/docker/centos-dev-java11/src/main/resources/META-INF/resources
Listening for transport dt_socket at address: 5005
2019-03-13 00:57:37,674 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-03-13 00:57:38,089 WARN  [io.qua.agr.dep.AgroalProcessor] (build-13) Agroal dependency is present but no driver has been defined for the default datasource
2019-03-13 00:57:38,529 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 855ms
2019-03-13 00:57:38,862 INFO  [io.quarkus] (main) Quarkus 0.11.0 started in 1.248s. Listening on: http://127.0.0.1:8080
2019-03-13 00:57:38,864 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, narayana-jta, resteasy]
```

I'm instead just seeing this weird behaviour:

```
mvn clean compile quarkus:dev
[INFO] Using servlet resources /home/quarkus-dev/src/main/resources/META-INF/resources
Listening for transport dt_socket at address: 5005
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.979 s
[INFO] Finished at: 2019-03-12T23:44:55Z
[INFO] ------------------------------------------------------------------------
```

Perhaps `quarkus-maven-plugin:0.11.0:dev` failed to start the Quarkus based app runtime for some reason... but if that were the case, it should not silently swallow whatever root caused that and let Maven print a `BUILD SUCCESS`, but re-throw some huge exception!

Should be reproducible using https://github.com/quarkusio/quarkus/compare/master...vorburger:issue-1390_dev-container. 

This may be some problem perhaps related to how [OpenShift runs containers under a different user](https://docs.okd.io/latest/creating_images/guidelines.html#openshift-specific-guidelines), or something like that, because a container built locally from the same Dockerfile works just fine! I'm going to try it out in pure K8s next.

**Comment by vorburger** [comment]
> because a container built locally from the same Dockerfile works just fine!

unless you run that with a different user (`docker run -u`), then it's reproducible even outside of OpenShift...

**Comment by emmanuelbernard** [comment]
Generally I think `quarkus:dev` is really not chatty enough and we should trya nd improve that (cc  @stuartwdouglas )
Would be good to get to to bottom of this specific problem though, I don't think we ever say quarkus:dev jsut silently crash. unless the app as only daemon on threads and the app starts and stops right away.

**Comment by gsmet** [comment]
I'm closing this one for now, feel free to reopen if it's still an issue with newer releases.
