### ISSUE TITLE
Metrics throw a 500 Internal Server Error when Application has configured a quarkus.http.root-path

### ISSUE THREAD

**Issue by bwand** [quarkusio/quarkus#14516]
**Describe the bug**
When the App has a quarkus.http.root-path configured I get a 500 and the Error:
`The expected context root of metrics is /q/metrics, but a request with a different path was routed to MetricsRequestHandler`
when trying to browse Metrics.

**Expected behavior**
Metrics should also work with a root path.

**Actual behavior**
Browsing to http://localhost:8095/admin/q/metrics throws a 500. The root path is named admin and before version 1.11.0 it has worked with a root path

**To Reproduce**

1. Create a project with quarkus.http.root-path=/admin
2. Add quarkus-smallrye-metrics
3. Try to browse metrics.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=8095
quarkus.http.root-path=/admin
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4275361/105490515-2d132f00-5cb5-11eb-9b76-76affed6aba3.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin bwand-mac.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec 2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): No Native Build
 - Quarkus version or git rev: powered by Quarkus 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Comment by jmartisk** [comment]
Looks like after adding support for `quarkus.http.non-application-root-path`, the property `quarkus.http.root-path` mistakenly isn't properly taken into account anymore, but we need to mind both now. Will be an easy fix.
