### ISSUE TITLE
IllegalAccessError with Reactive Hibernate Panache Entity from Unit Test

### ISSUE THREAD

**Issue by CurtisBaldwinson** [quarkusio/quarkus#14528]
**Describe the bug**
Using quarkus-hibernate-reactive-panache
Inside a unit test, instantiating an Entity that extends PanacheEntityBase yields an IllegalAccessError when attempting to set a public member.
Likely similar to https://github.com/quarkusio/quarkus/issues/12514 but I believe the fix may have only been for MongoDB, instead of MySQL.

**Expected behavior**
To be able to instantiate an Entity (and then perform operations on it) as works inside the regular src folder.

**Actual behavior**
`java.lang.IllegalAccessError: class ___.___.MessageInitiationT tried to access protected field ___.___.entity.mysql.RootAccount.username (___.___.MessageInitiationT and ___.___.entity.mysql.RootAccount are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader`

**To Reproduce**

1. Create an Entity extending PanacheEntityBase (again, reactive)
2. Instantiate it in a Unit Test and attempt to set the value of a public member
3. IllegalAccessError

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.746]
 - Output of `java -version`: java version "15.0.1" 2020-10-20
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
I encountered this when upgrading to 1.11.0.Final and switching from regular hibernate-panache to the reactive edition.

**Comment by geoand** [comment]
Is this still an issue with Quarkus `1.11.3.Final` or `1.12.0.CR1`?

If so, can you provide a reproducer please?

**Comment by famod** [comment]
@CurtisBaldwinson friendly reminder ^

**Comment by geoand** [comment]
Closing this as we didn't get the expected user input. 
If this is still an issue, please comment with the new information
