### ISSUE TITLE
configMap configured in quarkus.openshift properties does not get picked up by Quarkus application

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#14525]
**Describe the bug**
`configMap` configured in  `quarkus.openshift` according to [Quarkus - Deploying on OpenShift](https://quarkus.io/guides/deploying-to-openshift) does not get properly recognised by a Quarkus application. This approach worked in 1.7, therefore this is a breaking change.

With Quarkus 1.7, using the properties from docs was sufficient for a RESTful Quarkus application to pick up `configMap`s:

```
quarkus.openshift.config-map-volumes.app-config.config-map-name=app-config
quarkus.openshift.mounts.app-config.path=/deployments/config
```

It seems that with Quarkus 1.11, a new property is required:

```
quarkus.openshift.env.vars.smallrye-config-locations=/deployments/config
```

**Expected behavior**
`configMap` is picked up by application deployed to OpenShift.

**Actual behavior**
`configMap` is not picked up by application deployed to OpenShift.

**To Reproduce**
1. Clone https://github.com/quarkus-qe/quarkus-openshift-test-suite
2. Run `configMap` tests to reproduce the issue:
   ```
   mvn -B -V clean verify -pl app-metadata/deployment,app-metadata/runtime,common,configmap/file-system
   ```
3. Add `quarkus.openshift.env.vars.smallrye-config-locations=/deployments/config` to `config-secret/file-system/src/main/resources/application.properties`. Rerun test for workaround.

**Configuration**
```properties
quarkus.openshift.expose=true
quarkus.openshift.config-map-volumes.app-config.config-map-name=app-config
quarkus.openshift.mounts.app-config.path=/deployments/config
quarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-11:latest
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux tigris 5.10.8-200.fc33.x86_64 #1 SMP Sun Jan 17 19:53:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
    ```
   openjdk version "11.0.9.1" 2020-11-04
   OpenJDK Runtime Environment 18.9 (build 11.0.9.1+11)
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+11, mixed mode, sharing)
   ```
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: `1.11.0.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)`
 - OpenShift 4.6.9

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
cc @metacosm who worked on the env vars rework

**Comment by metacosm** [comment]
I did work on the env vars rework but this issue pertains to mounts and volumes and my changes didn't affect these parts. I haven't looked at the mount code so I don't know what it does, sorry! 😞

**Comment by geoand** [comment]
@iocanel any ideas?

**Comment by geoand** [comment]
> I did work on the env vars rework but this issue pertains to mounts and volumes and my changes didn't affect these parts. I haven't looked at the mount code so I don't know what it does, sorry!

Thanks

**Comment by geoand** [comment]
I took a quick look and this and it's a little weird.

The produced jar file is in `/deployments/configmap-file-system-1.0.0-SNAPSHOT-runner.jar` while the mounted configuration should be in `/deployments/config`, which should be enough for Quarkus. 

@mjurc can you show what the container's file system look like when you deploy the application?

Adding to the mystery, `SMALLRYE_CONFIG_LOCATIONS` doesn't seem to be specified in Quarkus or SR Config. Where did find that @mjurc ?

**Comment by geoand** [comment]
> Adding to the mystery, `SMALLRYE_CONFIG_LOCATIONS` doesn't seem to be specified in Quarkus or SR Config. Where did find that @mjurc ?

Nevermind this last comment, I see where SR Config uses this.

I think that the problem is how things are getting mounted into the containers File System. So @mjurc when you have a chance, please post what that file system looks like under `/deployment`.

Thanks

**Comment by iocanel** [comment]
@mjurc @geoand: I am a little bit confused with the expectation.

As far as it concerns the `quarkus-kubernetes` and `quarkus-openshift`, configuring & mounting a config map, does not imply that the config map will also be exposed as environment variables. AFAIK, this is something that was always needed to be explicitly specified.

So, the expectation does not seem valid.

Also, it seems to me that it might be dangerous, to automatically use config-maps without the user being explicit about it.

**Comment by mjurc** [comment]
@geoand The filesystem is as follows:
```
sh-4.4$ ls -l /deployments/
total 444
-rw-rw-r--. 1 jboss root           93 Jan 27 11:58 app-metadata.properties
drwxrwxr-x. 3 jboss root           46 Jan 27 11:58 classes
drwxrwsrwx. 3 root  1000650000     89 Jan 27 11:58 config
-rw-rw-r--. 1 jboss root       426322 Jan 27 11:58 configmap-file-system-1.0.0-SNAPSHOT-runner.jar
-rw-rw-r--. 1 jboss root         4837 Jan 27 11:58 configmap-file-system-1.0.0-SNAPSHOT.jar
drwxrwxr-x. 2 jboss root            6 Jan 21 15:18 data
drwxrwxr-x. 3 jboss root           25 Jan 27 11:58 generated-sources
drwxrwxr-x. 3 jboss root           30 Jan 27 11:58 generated-test-sources
drwxrwxr-x. 2 jboss root           94 Jan 27 11:58 kubernetes
drwxrwxr-x. 2 jboss root         8192 Jan 27 11:58 lib
drwxrwxr-x. 2 jboss root           28 Jan 27 11:58 maven-archiver
drwxrwxr-x. 3 jboss root           35 Jan 27 11:58 maven-status
drwxrwxr-x. 3 jboss root           23 Jan 27 11:58 quarkus
drwxrwxr-x. 2 jboss root          131 Jan 27 11:58 surefire
drwxrwxr-x. 2 jboss root          189 Jan 27 11:58 surefire-reports
drwxrwxr-x. 3 jboss root           96 Jan 27 11:58 test-classes
```

@iocanel We're deploying an application configured according to Quarkus docs. The `configMap` is mounted and mapped in application properties. If there's a change in behaviour that requires the users to add another mapping, it needs to be documented and explicitely mentioned in release notes as this is a breaking change (compared to 1.3 and 1.7).

**Comment by geoand** [comment]
I think I know what the issue is.

@mjurc what is the working directory of the application? For the `/deployments/config` to be taken into account, the working directory needs to be `/deployments` - if it's not then that is the bug in the Openshift manifests we need to fix.

**Comment by geoand** [comment]
@mjurc where you able to check the above?

**Comment by mjurc** [comment]
The current working directory of the running Java process is as follows:
```
sh-4.4$ ls -lad /proc/$(pgrep java)/cwd
lrwxrwxrwx. 1 1000650000 root 0 Jan 29 00:24 /proc/1/cwd -> /home/jboss
```

**Comment by geoand** [comment]
Then that the reason of the failure.

So @iocanel we either need to set the working directory to `/deployments` or to automatically set the env var that @mjurc .

Do you want to take care of it or should I?

**Comment by iocanel** [comment]
@geoand we can't force working directory to `/deployments` as there are cases that this might no be true.
I'll look into doing the later.

**Comment by iocanel** [comment]
To further elaborate on working dir:

We only have a slight idea of where the actual jar will land on `Openshift` based builds. Even then the result may vary depending 
on the builder image, `jvm vs native mode` and actual user configuration. For docker based builds this is controlled by the actual image and for jib based builds this is probably fixed. 

For all these reasons we stay away from messing with the workingDir in the generated manifests (which is also what broke @mjurc) Code.

Also, we can't really guess which mount will contain smallrye config. We can possibly try to guess but this might backfire.

IMHO, the best solution is to invert the situation into something like: `Tell us which is the resource that contains the config and we'll take care of mounts, volumes and env vars`.

So, the user would just need to specify something like:

`quarkus.opesnhift.app-secret` or `quarkus.openshift.app-config-map` and we would take care of mounts and env vars.

**Comment by geoand** [comment]
I like ☝️

**Comment by mjurc** [comment]
I like this solution. The new property hides the provider.

Considering this is a very common use case, would it be possible to include it in 1.11.2? cc @gsmet 

Also, the new property should be added to the docs. Again, it's a very common use case.

**Comment by geoand** [comment]
Once @iocanel has a PR with his proposed solution ready and we merge it, we will definitely include it in `1.11.x`
