### ISSUE TITLE
Check if OIDC Client can use Vertx Web Client more effectively

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#14541]
**Description**
@sd-f has helped with setting the web client options correctly.

What would be good to check next is look at `.getAbs()` (vs `.get()`). @vsevel uses `.getAbs()` in his PR.
The question I have, what is cheaper. If we set the default host and port options then may be it is more efficient to use only the path component of the auth server url and also the token url ? At the moment we set the default host/port - but also use absolute URIs with the `.get()` and `post()`. It feels like we can further optimize something :-).

Also minor optimization is possible by replace `transformToUni` with just `transform` in `OidcClientRecorder` where `JsonObject` response is picked up

**Comment by sd-f** [comment]
@sberyozkin i think using absolute URIs is the way to go in this case. This leaves all the parsing and setting options to the webclient and auth-server-url property will always be one string containing an aboslute uri. Setting host etc. in options is for special cases where the host or port does not match the Host-Header in the request. Maybe I have some time today to check. What do you say?

**Comment by sberyozkin** [comment]
@sd-f thanks for you analysis, it makes sense, I've seen your PR, cheers, I'll have a look
