### ISSUE TITLE
OpenAPI 301 has no CORS headers

### ISSUE THREAD

**Issue by huw0** [quarkusio/quarkus#14546]
**Describe the bug**
In Quarkus 1.11.0 /openapi now redirects to /q/openapi. However the redirect has no CORS headers, so using an external Swagger UI will be unable to load the API definition.

**Expected behavior**
/q redirects should have the Quarkus configured CORS headers, if CORS has been enabled.

**Actual behavior**
Redirect from /openapi to /q/openapi has no CORS headers

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.11.0
```
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-resteasy-mutiny'
    implementation 'io.quarkus:quarkus-smallrye-openapi' 
```

**Comment by phillip-kruger** [comment]
@kenfinnigan

**Comment by kenfinnigan** [comment]
I'm not entirely sure it should.

Redirection from /openapi to /q/openapi was put in place to prevent backward compatibility breakage in the short term.

Longer term we may revert the setting to `false` by default. For this reason, it may not be the right approach to add CORS headers to a redirect that isn't intended for extended real usage.

If a situation requires CORS today, then it should be modified to use the /q prefix on the path

**Comment by gsmet** [comment]
I don't know. I think the redirects should keep things functional. That's why we added them. If they are broken (and using Swagger UI is not a niche use case), why add them in the first place?

**Comment by phillip-kruger** [comment]
redirect is now removed. Can we close here ?
