### ISSUE TITLE
Impossible to override OIDC non-default tenant properties

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#14540]
**Describe the bug**
@Sgitario hi, FYI, please check `quarkus-oidc-client` and `quarkus-oidc` - may be it is related to Map properties in general, if  yes then we will rename this issue

**Comment by rsvoboda** [comment]
Is this something to be fixed in 1.11.x version stream?

**Comment by sberyozkin** [comment]
@rsvoboda Hi, unlikely, well, most likely not in 1.11.1.Final as it is due shortly.
@Sgitario Hi, did you have a chance to update your test to check the `quarkus-oidc` tenant ?
You can use `quarkus.oidc.tenant-enabled=false` to disable the default configuration

**Comment by Sgitario** [comment]
> @rsvoboda Hi, unlikely, well, most likely not in 1.11.1.Final as it is due shortly.
> @Sgitario Hi, did you have a chance to update your test to check the `quarkus-oidc` tenant ?
> You can use `quarkus.oidc.tenant-enabled=false` to disable the default configuration

I had this example covered here: https://github.com/Sgitario/quarkus-openshift-test-suite/tree/sso_multitenant_upstream/security/keycloak-multitenant and all the tests are passing. So, I think this issue is not affecting the Quarkus OIDC extension.

More info: This example is using three tenants using a different method:
```
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.client-id=test-unused-client

# Tenant For Webapp
quarkus.oidc.webapp-tenant.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.webapp-tenant.client-id=test-webapp-client
quarkus.oidc.webapp-tenant.credentials.secret=test-webapp-client-secret
quarkus.oidc.webapp-tenant.application-type=web-app
quarkus.oidc.webapp-tenant.roles.source=accesstoken

# Tenant for Service
quarkus.oidc.service-tenant.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.service-tenant.client-id=test-service-client
quarkus.oidc.service-tenant.credentials.secret=test-service-client-secret
quarkus.oidc.service-tenant.application-type=service

# Tenant for JWT
quarkus.oidc.jwt-tenant.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.jwt-tenant.client-id=test-jwt-client
quarkus.oidc.jwt-tenant.credentials.jwt.secret=AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow
quarkus.oidc.jwt-tenant.application-type=web-app
quarkus.oidc.jwt-tenant.token.issuer=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.jwt-tenant.roles.source=accesstoken
```

And we're providing the right properties here: https://github.com/Sgitario/quarkus-openshift-test-suite/blob/sso_multitenant_upstream/security/keycloak-multitenant/src/test/java/io/quarkus/ts/openshift/security/keycloak/AbstractSecurityKeycloakOpenShiftIT.java#L44

**Comment by sberyozkin** [comment]
@Sgitario OK, thanks; I really don't know right now where is the difference between the way the tenants map is declared in the `quarkus-oidc-client` `OidcClients` vs `quarkus-oidc` `OidcConfig`.
I'll create a branch where I'll experiment with the different class names

**Comment by sberyozkin** [comment]
@Sgitario Hi, can you clarify please how are you trying to use the client tenant configuration ?
It is only expected to support `OidcClients` container, see https://quarkus.io/guides/security-openid-connect-client#oidcclients

**Comment by Sgitario** [comment]
> @Sgitario Hi, can you clarify please how are you trying to use the client tenant configuration ?
> It is only expected to support `OidcClients` container, see https://quarkus.io/guides/security-openid-connect-client#oidcclients

Hello @sberyozkin . Good news, I've tried my example that is using OIDC Client tenants using the Quarkus version in master (999-SNAPSHOT) and now it's working fine.

See my example here: https://github.com/Sgitario/quarkus-openshift-test-suite/tree/sso_oidc_client/security/keycloak-oidc-client

**Comment by rsvoboda** [comment]
We need to have this fixed in 1.11 stream. What's the situation there?

**Comment by sberyozkin** [comment]
Hi @Sgitario cool, thanks, yeah - the tenancy concept does not really fit into the OIDC client space the way it fits into the server OIDC space - as we need in many cases to inject the client at the startup - and here it would be the job of the configuration profile if it were needed to select between the clients that early.
But at runtime, when we have some incoming context value, then indeed we can choose the client bound to the specific request.
Hi @rsvoboda We are good here, Jose has confirmed all works as per the current constraints

**Comment by sberyozkin** [comment]
@Sgitario Note @pedroigor had a good idea about having something like
```
@Id("tenant-a")
@OidcClient client;

but it was not possible to make it work across different scopes given the feedback from @mkouba, so for now it is only `OidcClients` which can be used to select the client dynamically
```
