### ISSUE TITLE
Application does not work with dev config after native compilation

### ISSUE THREAD

**Issue by suleymancan** [quarkusio/quarkus#14553]
**Describe the bug**
`mvn -Pnative package` 
`./target/app-runner -Dquarkus.profile=dev` 
After compiling and running using the command, I cannot run it with `dev` profile config. When I run it with the `stage` profile it works as expected.

`mvn package` 
`java -jar -Dquarkus.profile=dev ./target/app-runner.jar` 
When I create the jar, I can run it with dev config.

**Expected behavior**
After compiling native, I expect it to work with the `dev` profile when I configure the dev profile.

log messages:
Profile dev activated.
kafka: 
 bootstrap.servers = [dev-servers]

**Actual behavior**
After compiling native, The application continues to read the `prod` profile configs.

log messages:
Profile dev activated.
kafka: 
 bootstrap.servers = [prod-servers]

**To Reproduce**

1. create a new quarkus project 
(dependencies: quarkus-smallrye-reactive-messaging-kafka, quarkus-jdbc-mssql, quarkus-smallrye-openapi, quarkus-config-yaml, quarkus-hibernate-orm-panache, quarkus-smallrye-fault-tolerance, quarkus-arc, lombok, quarkus-logging-json, quarkus-logging-gelf, quarkus-smallrye-health)
2. compile the project native and run by override the profile

**Configuration**
```properties
quarkus:
  kafka:
    health:
      enabled: true
  log:
    console:
      enable: true
      json: false
      format: format
  hibernate-orm:
    jdbc:
      statement-batch-size: 1000
    database:
      generation: none
  datasource:
    db-kind: mssql
    username: db-username
    password: db-password
    jdbc:
      url: dev-url
  swagger-ui:
    always-include: true
  smallrye-health:
    root-path: /_monitoring/health
    
kafka:
  bootstrap:
    servers: dev-hosts

mp:
  messaging:
    connector:
      smallrye-kafka:
    incoming: 
       ...channel configs...
       
"%dev":

"%stage":
  quarkus:
    log:
      handler:
        gelf:
          enabled: true
          host: host
          port: port
          level: INFO
          facility: facility
          include-full-mdc: true
    datasource:
      jdbc:
        url: stage-url
  kafka:
    bootstrap:
      servers:  stage-hosts      
      
"%prod":
  quarkus:
    log:
      handler:
        gelf:
          enabled: true
          host: host
          port: port
          level: INFO
          facility: facility
          include-full-mdc: true
    datasource:
      jdbc:
        url: prod-url
  kafka:
    bootstrap:
      servers: prod-hosts
```
Quarkus version: 1.10.5.Final
Java version: 11
GraalVM version: OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
Maven version:  3.6.3 

Note: 
When I create a native image with the multi stage dockerfile and run it, I cannot run it in the dev profile.

**Comment by gsmet** [comment]
The dev profile is something specific used for dev mode (live reload).

It's not supposed to be used in native as it won't work at all.
