### ISSUE TITLE
Allow enums to be passed to included Qute templates

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14559]
When including a template, I'd like to pass an enum value:

```
{#include offering-form.html mode=dev.morling.demos.hotwire.Mode.CREATE}{/include}
```

But when referencing the `mode` variable from the included template, it's resolved to "NOT_FOUND". It works when passing e.g. a String.

**Comment by mkouba** [comment]
Yes, you can't access enum values and static members by FQCN. This is a limitation of Qute [expressions](https://quarkus.io/guides/qute-reference#expressions).

An easy workaround is to provide a namespace [extension method](https://quarkus.io/guides/qute-reference#template_extension_methods) to output enum values for a particular enum type, e.g.:
```java
import javax.enterprise.event.TransactionPhase;

@TemplateExtension(namespace = "transactionPhase", matchName = "*")
static TransactionPhase enumValue(String value) {
   return TransactionPhase.valueOf(value);
}
```
and in the template: `{transactionPhase:IN_PROGRESS}`.

A more generic solution would be something like: 
```java
@TemplateExtension(namespace = "enum")
static <T extends Enum<T>>  Object value(String value) throws ClassNotFoundException {
   ClassLoader cl = Thread.currentThread().getContextClassLoader();
   String className = value.substring(0, value.lastIndexOf('.'));
   Class<?> enumClass = cl.loadClass(className);
   if (enumClass.isEnum()) {
      return Enum.valueOf((Class<T>) enumClass, value.substring(className.length() + 1, value.length()));
   }
   return Results.Result.NOT_FOUND;
}
```

And in the template: `{enum:value('javax.enterprise.event.TransactionPhase.IN_PROGRESS')}`.

Finally, you could also pass an enum type as template data:
```
template.data("transactionPhase", TransactionPhase.class);
```
and access the field directly, e.g. in the template: `{transactionPhase.IN_PROGRESS}` (this would not work in native mode though).

I'd probably recommed a specialized extension method (solution no 1).

**Comment by mkouba** [comment]
I'm going to close this issue now. Feel free to reopen if you still think we should do something in this area.
