### ISSUE TITLE
Can't use Qute in reactive application

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14550]
When trying to build an application using RestEasy Reactive and Qute for rendering responses from templates, this exception is raised:

```
java.lang.IllegalStateException: The 'quarkus-resteasy-reactive' and 'quarkus-resteasy' extensions cannot be used at the same time.
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:235)
```

Given Qute supports async rendering, I'd expect it to be useable in a Reactive application. Specifically, I'd like to use Qute to render server-sent events.

**Comment by gunnarmorling** [comment]
As I learned from @cescoffier, there's a dedicated artifact, `quarkus-resteasy-reactive-qute`, which needs to be used when combining Reactive with Qute. This should be highlighted in the Qute guide.

**Comment by mkouba** [comment]
FYI @geoand we should add a chapter similar to https://quarkus.io/guides/qute-reference#resteasy_integration. Would you care to send a PR?

**Comment by geoand** [comment]
Good idea. I'll do that soon
