### ISSUE TITLE
How to properly register XMLGregorianCalendar?

### ISSUE THREAD

**Issue by wjglerum** [quarkusio/quarkus#14569]
Already for some time some warning is bugging me when our Quarkus app is starting up. This is regardless of the Quarkus version, seeing this warning on both 1.10 and 1.11

We generate some Java code from XSD files for a REST Client implementation using JAXB. The XSD contains a datetime field which translates to a `javax.xml.datatype.XMLGregorianCalendar`. And gives me the following warning on start up:

```
2021-01-23 11:13:19,751 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-6) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - javax.xml.datatype.XMLGregorianCalendar (source: RestClientProcessor > nl.wjglerum.xml.Prices)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

I tried the following options without any success:
- adding an empty `beans.xml` in `META-INF`
- adding the jandex maven plugin to build the Jandex index
- adding an annotation to register the class with `@RegisterForReflection(targets = XMLGregorianCalendar.class)`
- adding it using `application.properties`, unfortunately I couldn't figure out what to add here.

Sample repo to reproduce the warning: https://github.com/wjglerum/quarkus-xml

Also see zulip https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/How.20to.20properly.20register.20XMLGregorianCalendar.3F

**Comment by wjglerum** [comment]
Seems to be happening for other javax classes too, see https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reflection.20registration.20of.20JDK.20classes.3F

**Comment by gastaldi** [comment]
@wjglerum I've provided a fix in https://github.com/quarkusio/quarkus/pull/14576

**Comment by wjglerum** [comment]
Thanks @gastaldi! I had a look at that class the other day, but had no clue where to start to fix the issue ...

Out of interest, why can we simply ignore the warning for this class?

**Comment by gastaldi** [comment]
AFAIK it's because that's a class provided by the JDK and it's not part of the application or a 3rd party library, so it doesn't make sense to look for a Jandex index in this case.
