### ISSUE TITLE
MySql reactive driver slowness 

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#14564]
I had to switch from reactive postgres client to mysql and I saw a major drop in performance.
My program is in command mode that reads from kafka (self managed and partition assignment with reactive kafka client), do some transformation, and write to DB in batches. Basically a batch cmd tool (or poor man's Spark =) )

On a simple test (non benchmark) it managed to read and insert ~150K messages in no time to postgres, but when I switched to mysql, the performance dropped drastically to ~1K records to mysql.
All test run on my MacBook pro. With the same configuration.

Repro - https://github.com/FreifeldRoyi/Reactive-db-driver-slowness

java:
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

Quarkus - 1.10.5.Final

**Comment by gsmet** [comment]
Hmmm? Is it the driver being slow or MySQL just being slower? Hard to say from the provided information.

**Comment by BillyYccc** [comment]
Hi, I think there're several reasons for Vert.x MySQL client batching being slower compared to Vert.x Postgres client.

1. MySQL server does not provide a batching protocol natively and the MySQL client execute batches by composing unary executions, this would add many network round-trips leading to decreasing the throughput and adding latency. For example let us batch with 256 iterations, for Postgres it's a single request-reponse interaction, but for MySQL it's 256*(request-response)
2. The Postgres client supports command pipelining and configure it by default while MySQL client does not supports it, so increases of network round trips will amplify the impact to performance, but I think the MySQL client can support command pipelining later and have a boost on performance, see https://github.com/eclipse-vertx/vertx-sql-client/issues/861
3. you should enable the prepared statement cache option for both clients, that would help the performance as well

**Comment by cescoffier** [comment]
@tsegismont anything we can do about this?

**Comment by tsegismont** [comment]
I don't believe there's something we can do. @BillyYccc explained well what happens under the hood.

Now the JDBC driver probably rewrites batches in case they are simple insert/updates. For example, instead of adding N batches for this same query:

```sql
INSERT into movies (name, plot) VALUES (?,?)
```

You can create an ad-hoc query:

```sql
INSERT into movies (name, plot) VALUES (?,?), (?,?), (?,?) /* n-times*/
```

That is something the user can do (but upstream in MySql client we have no plans for implementing a SQL parser).

**Comment by cescoffier** [comment]
Ok, then, let's close this issue.
