### ISSUE TITLE
GraalVM substitutions randomly break org.hibernate.Version

### ISSUE THREAD

**Issue by Mobe91** [quarkusio/quarkus#14560]
**Describe the bug**
GraalVM substitutions in the Hibernate-ORM integration generate classes in the `org.hibernate` package that are not located inside the `hibernate-core` JAR. This causes the `META-INF/MANIFEST.MF` in `hibernate-core` not to take effect when the `java.lang.Package` instance for the `org.hibernate` package is created during class loading whenever the first class of the `org.hibernate` package being loaded is a substitution class. Since the class loading order is non-deterministic, this problem occurs randomly. This issue affects libraries like Blaze-Persistence that seek to integrate with Hibernate and rely on `org.hibernate.Version` for resolving the Hibernate version that is being used. `org.hibernate.Version` relies on the package implementation version defined in the `META-INF/MANIFEST.MF` of the `hibernate-core` JAR.

**Expected behavior**
The `java.lang.Package` instance for the `org.hibernate` package is consistently associated with the `META-INF/MANIFEST.MF` of the `hibernate-core` JAR.

**Actual behavior**
The `java.lang.Package` instance for the `org.hibernate` package is randomly associated with either the `META-INF/MANIFEST.MF` of the `hibernate-core` JAR or the `META-INF/MANIFEST.MF` of the main application JAR that uses the Hibernate-ORM integration.

**To Reproduce**
Due to its random nature, this issue cannot be reproduced consistently.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux YVR-5CG0324CBJ 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
   openjdk 11.0.9.1 2020-11-04
   OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
   OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
 - GraalVM version (if different from Java): 20.3.0-java11 
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by Sanne** [comment]
Very interesting, thanks for spotting that.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by gsmet** [comment]
I think we can close this one. I haven't heard any complaints about the Blaze Persistence integration for ages and @beikov released several versions since then.
