### ISSUE TITLE
Exclude graphql-ui from jwt verification

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#14561]
Use graphql-ui and smallrye-jwt, 
chrome plugin use ModHeader set Authorization= Bearer {token}
if the token is invalid, graphql-ui will get 401， page can not open.

Is there any configuration to exclude graphql-ui from jwt verification

----
![image](https://user-images.githubusercontent.com/6096680/105650822-fc6b0980-5eef-11eb-8608-3364bdfea604.png)
-----
![image](https://user-images.githubusercontent.com/6096680/105650897-376d3d00-5ef0-11eb-9823-d6e734849ecb.png)

-----

**Comment by gsmet** [comment]
When we come with a solution, could we document it somewhere if not already done? Thanks!

**Comment by phillip-kruger** [comment]
Hi @pipinet 

See https://stackoverflow.com/questions/63456589/how-do-i-exclude-quarkus-graphql-ui-from-jwt-authentication

Basically, you can exclude the graphql ui from JWT by adding this to your application.properties:

```
quarkus.http.auth.permission.permit.paths=/graphql-ui/*
quarkus.http.auth.permission.permit.policy=permit
```

Also note that from version 1.11.0.Final the path is `/q/graphql-ui`, so change above to include the `q`.

Hope that helps.

**Comment by pipinet** [comment]
Hi @phillip-kruger 
Got it !!! thanks!
