### ISSUE TITLE
@Scheduled memory leak

### ISSUE THREAD

**Issue by wwadge** [quarkusio/quarkus#14572]
**Describe the bug**

When I native compile the following code and run it under docker, I can observe a slow memory leak as observed by docker stats. The leak stops if the scheduler is turned off via "-e QUARKUS_SCHEDULER_ENABLED=false" 

  ```
@Component @ApplicationScoped @Startup 
  public class SomeClass  {

    @Scheduled(cron = "{something.from.config}")
    void doSomething() {
    }
  }

```

**Expected behavior**
No memory leak

**Actual behavior**
Leaks a few Kb of ram every second.

**To Reproduce**

https://github.com/wwadge/quarkus-scheduler-leak
**Configuration**
```properties
something.from.config = 0 0 9 ? * WED
```

**Screenshots**
N/A

**Environment (please complete the following information):**
- Quarkus 1.11.0.Final, Java 11

**Comment by wwadge** [comment]
Example project:
https://github.com/wwadge/quarkus-scheduler-leak

Note: leak is apparent even if cron expression is not due yet to fire

**Comment by mkouba** [comment]
@wwadge Thanks for reporting. I've got some questions ;-).

1. Is it reproducible locally, i.e. no docker and no native?
2. If so, do you have a memory dump?

Also a few KBs of RAM does not have to be a leak...

**Comment by wwadge** [comment]
Hi! I think the issue was unrelated here (I've attached a profiler, it seems fine) -- apologies for the noise, closing issue.

**Comment by mkouba** [comment]
> Hi! I think the issue was unrelated here (I've attached a profiler, it seems fine) -- apologies for the noise, closing issue.

No problem! Enjoy the development with Quarkus :-)
