### ISSUE TITLE
Documentation how to use gradle with quarkus is wrong

### ISSUE THREAD

**Issue by RupprechJo** [quarkusio/quarkus#1457]
There are two errors in the supposed build.gradle on quarkus homepage: 
- Gradle does not use Junit5 out of the box (and does this silently). You have to add this to the build.gradle to make gradle running the tests:
```
test {
    useJUnitPlatform()
}
```
- Gradle (I used 5.2) does not know the configuration testOnly. So you have to replace this
`testOnly group: 'io.quarkus', name: 'quarkus-junit5', version:'0.11.0'`
by this
`testCompile group: 'io.quarkus', name: 'quarkus-junit5', version:'0.11.0'`

**Comment by gsmet** [comment]
@RupprechJo could you be more clear about what you are referring to?

I looked for `testOnly` in our code and couldn't find any occurrence.

**Comment by RupprechJo** [comment]
I mean the documentation found here: https://quarkus.io/guides/gradle-tooling.html

**Comment by edeandrea** [comment]
I would also add that the documentation uses the `gradle` command, which assumes that you have a global installation of Gradle on your machine. The most common way to use gradle is via the Gradle wrapper, which uses the `gradlew` command that comes with each individual project.

**Comment by gsmet** [comment]
@edeandrea this part is already fixed in our master branch.

**Comment by stalep** [comment]
This is fixed in master where we also recommend using the `implementation` configuration.
