### ISSUE TITLE
Dynamically Enable / Disable QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by eye0fra** [quarkusio/quarkus#14575]
**Description**
The use case is the ability to run individually a test case, or in case some environment do not have the correct resources available (Docker for instance for Test Containers):

- Test 1 QuarkusTestResourceLifecycleManager is created to spin up several resources like (TestContainers)
- Test 2 with a different lifecycle manager or without one.

Currently, if I launch the Test 2 the QuarkusTestResourceLifecycleManager used by Test 1 starts always unless I comment out the lifecycle manager definition.
Same result with different test profiles in different packages.

**Implementation ideas**
I would leverage [the profile definition ](https://quarkus.io/guides/getting-started-testing#testing_different_profiles) at the start so I know that specific lifecycle is just for that profile, and plus the [@Disabled](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Disabled.html) in case the test is not yet ready.

**Comment by geoand** [comment]
Currently the `testResources` of `QuarkusTestProfile` allows to enable **additional** `QuarkusTestResourceLifecycleManager` to be used for that profile.

If I understand correctly the end result you are trying to achieve, I assume adding a new method named `excludedtestResources` where you could explicitly exclude some of the global `QuarkusTestResourceLifecycleManager` classes from taking effect would be enough, right?

**Comment by eye0fra** [comment]
Yes, it provides an additional Lifecycle, and it is the only way I found to avoid to run different lifecycle without clashing. Using the annotations `@QuarkusTestResource` for a specific test, it runs always. 
The `excludedTestResource` method can be useful too but if a developer annotates a class should this test resource used by the specific class only? Wrong assumptions?

What probably I am getting wrong is how to run exclusively (if possible) the test profile (-Dquarkus.test.profile).

**Comment by geoand** [comment]
> Yes, it provides an additional Lifecycle, and it is the only way I found to avoid to run different lifecycle without clashing. Using the annotations `@QuarkusTestResource` for a specific test, it runs always.

Thats is correct. Classes annotated with `@QuarkusTestResource` are essentially "global".

> The `excludedTestResource` method can be useful too but if a developer annotates a class should this test resource used by the specific class only? Wrong assumptions?

I am not sure I understand what you mean here. Can you explain?

> 
> What probably I am getting wrong is how to run exclusively (if possible) the test profile (-Dquarkus.test.profile).

You mean have a way to run only the tests that are associated with that profile? If so, then no, we don't support that. The only way for us to do that would be to tell JUnit 5 to skip the rest of the tests (which I am not even sure is possible).

**Comment by eye0fra** [comment]
> > Yes, it provides an additional Lifecycle, and it is the only way I found to avoid to run different lifecycle without clashing. Using the annotations `@QuarkusTestResource` for a specific test, it runs always.
> 
> Thats is correct. Classes annotated with `@QuarkusTestResource` are essentially "global".
> 
> > The `excludedTestResource` method can be useful too but if a developer annotates a class should this test resource used by the specific class only? Wrong assumptions?
> 
> I am not sure I understand what you mean here. Can you explain?
> 
Ok you answered me above `@QuarkusTestResource` is global and my assumption was wrong :)
> > What probably I am getting wrong is how to run exclusively (if possible) the test profile (-Dquarkus.test.profile).
> 
> You mean have a way to run only the tests that are associated with that profile? If so, then no, we don't support that. The only way for us to do that would be to tell JUnit 5 to skip the rest of the tests (which I am not even sure is possible).

I guess with [`@Tag`](https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions) and use the profile as the parameter.

**Comment by geoand** [comment]
Right, in JUnit land you could also use https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution-custom.

But I am still unclear if my proposal about `excludedTestResource` would suit you or not.
To clear the confusion, I propose you add some pseudo code of what your scenario looks like and what **exactly** you are trying to achieve.

**Comment by eye0fra** [comment]
Here some pseudocode:

_**.profile 1**_
```java
public class EmbeddedProfile implements QuarkusTestProfile {

    @Override
    public String getConfigProfile() { 
        return "emb";
    }

	@Override
	public List<TestResourceEntry> testResources() {
		
		return Collections.singletonList(new TestResourceEntry(KafkaResource.class));

	}    
}
```
```java
// Define  an embeddable cluster of Kafka
public class KafkaResource implements QuarkusTestResourceLifecycleManager  {
 ....
}
```

```java
@TestProfile(EmbeddedProfile.class)
@QuarkusTest
public class TopologyTest {

...

}
```

_**.profile 2**_

```java
public class IntegrationProfile implements QuarkusTestProfile {

    @Override
    public String getConfigProfile() { 
        return "int";
    }

	@Override
	public List<TestResourceEntry> testResources() {
		
		return Collections.singletonList(new TestResourceEntry(DebeziumResource.class));

	}

    
}

```
```java
// Defines TestContainers (like Kafka, PostgreSQL and Debezium)
public class DebeziumResource implements QuarkusTestResourceLifecycleManager  {
 ....
}
```

```java
@QuarkusTest
@TestProfile(IntegrationProfile.class)
public class TopologyAggregatorTest {

...

}
```

I think `excludedTestResource` does not help because the tests (profile1 and profile2) will both run with `mvn clean test`. The idea is to run profile mutually exclusive.

**Comment by geoand** [comment]
Thanks for the explanation. I now see what you want to do.

So like you mentioned before you would like the Quarkus extension to only execute tests that use a specific Quarkus profile, but then also a way to turn off the global `QuarkusTestResourceLifecycleManager`, right?

**Comment by eye0fra** [comment]
Correct!

**Comment by geoand** [comment]
I think for the second part, the most appropriate solution would be to have a new `disableGlobalTestResources` method on `QuarkusTestProfile` which is `false` by default.

For the first part, I am not sure what the proper approach should be (it's definitely not `quarkus.test.profile` which refers to something else entirely.
But maybe we could have some other property that would allow you to run only Quarkus tests annotated with some specific `QuarkusTestProfile` annotation (this could of course be turned into a more general conditional solution, but I am not sure it's worth it).

@stuartwdouglas what is your take on this?

**Comment by stuartwdouglas** [comment]
I agree with adding a disableGlobalTestResources() method: https://github.com/quarkusio/quarkus/pull/14637

We can definitely have some way to only run specific profiles, but I don't know what the best way to do it is. Ideally we could integrate with the existing tag mechanism, but I don't think that is possible at the moment, so we may just have to have a system property.

**Comment by geoand** [comment]
> I agree with adding a disableGlobalTestResources() method: #14637
> 
> We can definitely have some way to only run specific profiles, but I don't know what the best way to do it is. Ideally we could integrate with the existing tag mechanism, but I don't think that is possible at the moment, so we may just have to have a system property.

Yeah, it's worth looking into for sure.

**Comment by geoand** [comment]
Here is an idea:

We add 

```java
Optional<String> tag() {
   return Optional.empty();
}
``` 

to `QuarkusTestProfile`.

These tags can be used to allow us to skip test execution based on those values if JUnit's Tags have been configured (via Surefire or the IDE). 
Note that the configured tags **are** available to use via `ExtensionContext#getTags`. 

We could also add a dedicated system property that would also allow us to skip tests based on the provided tag.

WDYT @stuartwdouglas ?

**Comment by famod** [comment]
@geoand I think a profile should be able to specify multiple tags. Imagine different tests sharing the same profile but using (for whatever reason) different tags.

**Comment by geoand** [comment]
@famod how would multiple tags help with that case?

**Comment by stuartwdouglas** [comment]
I think ExtensionContext#getTags is the tags on the current test method/class, not the set of tags the user tried to run.

**Comment by famod** [comment]
@geoand
> how would multiple tags help with that case?

I might have misunderstood your idea. I thought the tags of the profile should be compared to the active tags and if there is no match the profile is not considered.

**Comment by geoand** [comment]
> I think ExtensionContext#getTags is the tags on the current test method/class, not the set of tags the user tried to run.

I'll double check and let you know

**Comment by geoand** [comment]
> @geoand
> 
> > how would multiple tags help with that case?
> 
> I might have misunderstood your idea. I thought the tags of the profile should be compared to the active tags and if there is no match the profile is not considered.

Yes, that is the idea

**Comment by geoand** [comment]
> > I think ExtensionContext#getTags is the tags on the current test method/class, not the set of tags the user tried to run.
> 
> I'll double check and let you know

You are right... So we indeed don't have a way to tie into JUnit's tags

**Comment by geoand** [comment]
I took at look at how Surefire launches JUnit 5 tests and found that tags play the role of a `org.junit.platform.launcher.PostDiscoveryFilter` which means that tests that don't match the configured tags are filtered out before tests are even launched.
Moreover, when it comes time to launch the final set of tests, the information about all the originally discovered tests (basically the original `org.junit.platform.engine.TestDescriptor`) has been pruned and there is no way information about tags at test execution time.

**Comment by knutwannheden** [comment]
This seems like it is related to #10297. I think it should be possible to add `@Tag` annotations to the class referenced by `@TestProfile` and these tags would then apply to the corresponding tests. This might also solve the use case described here.

**Comment by geoand** [comment]
We wanted to do that, but unfortunately it's not possible as per my explanation above

**Comment by knutwannheden** [comment]
I should have read that more carefully then. Unfortunate nevertheless ☹️
