### ISSUE TITLE
The exceptions thrown into an event flow (or a separate thread) are quietly captured and the developer won´t know it 

### ISSUE THREAD

**Issue by vteferrer** [quarkusio/quarkus#14591]
**Describe the bug**
In the code into an event handler method or another way to generate a separate thread (for example created using _Executors.newSingleThreadExecutor()_ or something like that) the exceptions are not reported, it seems they are quietly captured in an external layer. 

**Expected behavior**
In this code: 
```
@ApplicationScoped
public class EventsAndExceptions {

    private static final Logger LOGGER = Logger.getLogger(EventsAndExceptions.class.getCanonicalName());

    @Inject
    EventBus bus;

    @ConsumeEvent("greeting")
    public void consume(String name) {
        LOGGER.log(Level.INFO, "Hello {0}", name.toUpperCase());

        String nullReference = null;
        nullReference.toUpperCase();

        LOGGER.log(Level.INFO, "See you soon {0}", name.toUpperCase());
    }

    void startup(@Observes StartupEvent event) {
        bus.publish("greeting", "Vicent");
    }
}
```

```2021-01-25 20:30:09,627 INFO  [org.acm.EventsAndExceptions] (vert.x-eventloop-thread-1) Hello VICENT```

I expected the application to show the error, but it shows error nowhere. As expected, the last INFO log isn´t executed  because the flow has been interrupted at the forced NPE, but the developer won´t know it

If I capture explicitly the exception, evidently the catch block is invoked and the flow continues reaching the INFO log. 
```
String nullReference = null;
try {
     nullReference.toUpperCase();
} catch (Exception e) {
      LOGGER.log(Level.SEVERE, "Yes, this is a NPE", e);
}
```
```2021-01-25 20:30:09,627 INFO  [org.acm.EventsAndExceptions] (vert.x-eventloop-thread-1) Hello VICENT
2021-01-25 20:30:09,633 SEVERE [org.acm.EventsAndExceptions] (vert.x-eventloop-thread-1) Yes, this is a NPE: java.lang.NullPointerException
   at org.acme.EventsAndExceptions.consume(EventsAndExceptions.java:28)
   at org.acme.EventsAndExceptions_ClientProxy.consume(EventsAndExceptions_ClientProxy.zig:188)
...
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-25 20:30:09,635 INFO  [org.acm.EventsAndExceptions] (vert.x-eventloop-thread-1) See you soon VICENT
```

Am I doing something wrong?

**Actual behavior**
The application doest´t notify about the exception has been thown. 

**To Reproduce**
I attach this zip file [this zip file](https://github.com/quarkusio/quarkus/files/5869258/code-with-quarkus-exceptions.zip)  with a fresh project using only _vertx_ and _resteasy-mutiny_ extensions to have events support. 

1. Unzip the file
2. Change to its directory and execute it: _./mvnw compile quarkus:dev_ 

**Configuration**
Not applicable

**Screenshots**
Not necessary

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 ```
Darwin iMac-de-Vicente-4.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```
- Output of `java -version`: 
 ```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
 - GraalVM version (if different from Java): GraalVM CE 20.3.1
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /Users/vferrer/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

**Comment by gsmet** [comment]
@cescoffier looks like a Reactive Messaging issue? I remember seeing something similar elsewhere but I'm not sure it's exactly the same issue?

**Comment by cescoffier** [comment]
No, @ConsumeEvent does not come from Reactive Messaging. It's part of the Vert.x extension.

**Comment by cescoffier** [comment]
Hum,
We do have a global exception handler:
https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L202-L207

**Comment by cescoffier** [comment]
Oh, definitely a bug (thanks for the reproducer). The `@ConsumeEvent` swallows the exception even when there is no reply. A regular consumer reports the failure as expected.

**Comment by cescoffier** [comment]
\CC @mkouba
