### ISSUE TITLE
Native image - support for app icon

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1460]
Native image - support for app icon

This could be useful when people create custom utilities and want to use and distribute them in their favourite OS - especially macOS and Windows (Substrate VM hopefully available soon) when apps are executed from UI rather than from console.

Some OS related guidelines for app icons
 * https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon
 * https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos
 * https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

I originally created issue in graalvm upstream (https://github.com/oracle/graal/issues/1051), but we should track it here too.

**Comment by gsmet** [comment]
I'm inclined to close that one. We will need some GraalVM support for it and until then, I don't think it's worth managing the issue again and again. Feel free to reopen if you disagree.

**Comment by gsmet** [comment]
(I subscribed to the GraalVM issue to be notified if something new happens on that front)
