### ISSUE TITLE
Support @MultipartForm in RESTEasy Reactive

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14601]
When switching to these reactive components, a previously working multipart form REST method stops to work (unsupported content type for the client).

**Comment by geoand** [comment]
I've not really used multipart myself, so I am wondering what the proper API should be for this.

Also cc @gastaldi @gsmet who have done some Multipart stuff in Quarkus

**Comment by gunnarmorling** [comment]
No need for anything new in terms of API, really. It should just work as with non-Reactive:

```
    @GET
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Transactional
    @Path("new")
    @Blocking
    public Response addOffering(@MultipartForm OfferingForm offeringForm) {
        Offering offering = offeringForm.convertIntoOffering();
        offering.persist();

        return Response.status(Status.SEE_OTHER)
            .location(URI.create("/offering"))
            .build();
    }
```

This works with non-Reactive, but with Reactive RESTEasy, the method isn't considered and the client receives HTTP 415.

**Comment by geoand** [comment]
What does `OfferingForm` look like?

**Comment by gunnarmorling** [comment]
It's a basic POJO with `@FormParam`s for all the input fields:

```java
public class OfferingForm {

    public @FormParam("inputTitle") @PartType(MediaType.TEXT_PLAIN) String title;
    public @FormParam("inputSeller") @PartType(MediaType.TEXT_PLAIN) String seller;
    public @FormParam("inputDescription") @PartType(MediaType.TEXT_PLAIN) String description;
    public @FormParam("inputMinPrice") @PartType(MediaType.TEXT_PLAIN) String minPrice;

    public Offering convertIntoOffering() {
        Offering offering = new Offering();

        offering.postingDate = ZonedDateTime.now();
        offering.title = title;
        offering.seller = seller;
        offering.description = description;
        offering.minPrice = new BigDecimal(minPrice);

        return offering;
    }
}
```

Values are posted from a form rendered via Qute like this:

```
<form action="/offering/{#if update}{offering.id}/edit{#else}new{/if}" method="POST" name="offeringForm" enctype="multipart/form-data">
  <div class="form-row">
    <div class="form-group col-md-3">
      <label class="sr-only" for="inputTitle">Title</label>
      <input type="text" name="inputTitle" class="form-control" id="inputTitle" placeholder="Title" {#if mode == 'EDIT' ||  mode == 'VIEW'}value="{offering.title}"{/if} {#if mode == 'VIEW'}readonly{/if}>
    </div>
    <div class="form-group col-md-3">
      <label class="sr-only" for="inputSeller">Seller</label>
      <input type="text" name="inputSeller" class="form-control" id="inputSeller" placeholder="Seller" {#if mode == 'EDIT' ||  mode == 'VIEW'}value="{offering.seller}"{/if} {#if mode == 'VIEW'}readonly{/if}>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label class="sr-only" for="inputDescription">Description</label>
      <input type="text" name="inputDescription" class="form-control" id="inputDescription" placeholder="Description" {#if mode == 'EDIT' ||  mode == 'VIEW'}value="{offering.description}"{/if} {#if mode == 'VIEW'}readonly{/if}>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-2">
      <label class="sr-only" for="inputMinPrice">Min. Price</label>
      <input type="text" name="inputMinPrice" class="form-control" id="inputMinPrice" placeholder="Min. Price" {#if mode == 'EDIT' ||  mode == 'VIEW'}value="{offering.minPrice}"{/if} {#if mode == 'VIEW'}readonly{/if}>
    </div>
  </div>

  {#if mode != 'VIEW'}
  <button type="submit" class="btn btn-primary mb-2">{#if mode == 'CREATE'}Create{#else}Update{/if}</button>
  {/if}
</form>
```

**Comment by FroMage** [comment]
Looks _very_ similar to `@BeanParam`, so perhaps the same implementation?

**Comment by gastaldi** [comment]
It would be nice if we could use `@BeanParam` instead. Not sure why RESTEasy classic introduced `@MultipartForm`

**Comment by FroMage** [comment]
Probably, yeah.

**Comment by geoand** [comment]
> Looks _very_ similar to `@BeanParam`, so perhaps the same implementation?

That would be ideal

**Comment by geoand** [comment]
> It would be nice if we could use `@BeanParam` instead. Not sure why RESTEasy classic introduced `@MultipartForm`

@patriot1burke do you remember?

**Comment by itboy87** [comment]
for now is there any workaround for it?

**Comment by gunnarmorling** [comment]
I'm not aware of any viable approach using RESTEasy atm. You can use Reactive Routes as an alternative programming model:

    @Route(methods = HttpMethod.POST, path = "/offering/new", type = Route.HandlerType.BLOCKING, consumes = MediaType.MULTIPART_FORM_DATA)
    @Transactional
    @Blocking
    public void blocking(RoutingContext rc) {
        MultiMap formAttributes = rc.request().formAttributes();

        Offering offering = new Offering();

        offering.postingDate = ZonedDateTime.now();
        offering.title = formAttributes.get("inputTitle");
        offering.seller = formAttributes.get("inputSeller");
        offering.description = formAttributes.get("inputDescription");
        offering.minPrice = new BigDecimal(formAttributes.get("inputMinPrice"));

        offering.persist();

        rc.response().setStatusCode(Status.SEE_OTHER.getStatusCode())
            .putHeader("location", URI.create("/offering").toString())
            .end();
    }

Note you can combine this with RESTEasy, even in a single endpoint class. So it's not too bad.

**Comment by geoand** [comment]
I'll be looking at this soon, so we should have something in for `1.12`

**Comment by gsmet** [comment]
Btw, even if we're using the same code as for `BeanParam`, I think we should support `FormParam` anyway as it's in the spec. It's the same as for others, there is a spec version requiring the name and a RESTEasy-specific one not requiring it.

**Comment by geoand** [comment]
After taking a quick look at what `@BeanParam` does, Multipart is similar in philosophy, but it's not the same the thing. 
So the implementation _might_ share some stuff, but it can't be used as is.

**Comment by FroMage** [comment]
>  I think we should support FormParam anyway as it's in the spec

We already do. But that's not for multi-part, that's for urlencoded forms.

**Comment by FroMage** [comment]
> After taking a quick look at what @BeanParam does, Multipart is similar in philosophy, but it's not the same the thing.
So the implementation might share some stuff, but it can't be used as is.

So what's the difference?

**Comment by geoand** [comment]
That multipart can only read parts of the body and that each part can have
a different media type

**Comment by FroMage** [comment]
Sure, but IIRC each part of a `BeanParam` generates code that calls a method like `context.getXXXParam` to fill it once created, and perhaps this is just adding support for another type of field that calls `context.getMuiltipartForm(mime, name)`, no?

**Comment by geoand** [comment]
Maybe, I haven't looked into it that much but something tells me it will be slightly more complicated than that

**Comment by geoand** [comment]
@gunnarmorling #14852 adds the necessary support if you want to take it for a spin :)

**Comment by gunnarmorling** [comment]
Excellent, thanks! I didn't find the time to test it, sorry. Will pull it
when getting back to my Reactive Qute experimentation.

>

**Comment by geoand** [comment]
Cool, thanks 👍

**Comment by ntrp** [comment]
Hello, amazing feature but is there any way we can upload multiple attachment with the same name? I mean an attachment list.

**Comment by geoand** [comment]
Hi,

What would thag look like on the client side? I mean what would the browser or cURL send?

**Comment by ntrp** [comment]
Well simply the same field name multiple times, like I would send multiple times the form field `attachments`. In spring webflux for example this allows to bind a Flux<FilePart> in the controller, in this case it might be List<FileUpload>.

An example curl command would be:
```
curl --location --request POST 'http://localhost:8091/send/email' \
   --header 'Accept: application/stream+json' \
   --form 'payload="{
      \"test\": \"test\"
   }";type=application/json' \
   --form 'attachments=@"/tmp/pic1.jpg";type=image/jpeg' \
   --form 'attachments=@"/tmp/pic2.jpg";type=image/jpeg'
```
I can see if I can create a pull request, if anybody can point me to the right files without me having to search for them would be helpful.

Another thing I did not understand about RESTEasy multipart support is if I can bind @FormParam or @RestForm in the controller method and if not, unless there is a reason it cannot be done I would try that too.

In Spring webflux for example I have this signature:
```java
public voind sendEmail(Mono<SendEmail> email, Flux<FilePart> attachments, ..) {
...
}
```

**Comment by ntrp** [comment]
Just for extra clarity this would generate a body like this:
```
POST /send/email HTTP/1.1
Host: localhost:8091
Accept: application/stream+json
Content-Length: 462
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="payload"
Content-Type: application/json

{
  "test": "test"
}
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="attachments"; filename="pic1.jpg"
Content-Type: image/jpeg

(data)
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="attachments"; filename="pic2.jpg"
Content-Type: image/jpeg

(data)
----WebKitFormBoundary7MA4YWxkTrZu0gW
```

**Comment by ntrp** [comment]
Ok nevermind, I think I found already the answer to my question https://github.com/ntrp/quarkus/commit/18946b7cf40772a75b05a5b1a8c0f3a7f4156b0e, thanks again ^^'

**Comment by geoand** [comment]
Indeed https://github.com/quarkusio/quarkus/pull/17039 adds the ability to capture all uploaded files (docs for the `main` branch are [here](https://quarkus.io/version/main/guides/resteasy-reactive#handling-multipart-form-data)).

So essentially what you are asking for is to support:

```
class Pojo {

   ...


   @RestForm("attachments")
   List<FileUpload> attachments;
}
```

correct?

If so, can you please open an issue?

**Comment by ntrp** [comment]
I created this one https://github.com/quarkusio/quarkus/issues/17246

**Comment by abuelgasimsaadeldin** [comment]
@ntrp @geoand Hi guys, I was previously using the ```quarkus-resteasy-multipart``` and after migrating to resteasy reactive I was able to still use Multipart form by default but I am unable to add validation like done previously Example: @NotNull or @NotBlank in requests. That would be very helpful. Any ideas if this is still possible with the resteasy reactive? Thanks!

**Comment by geoand** [comment]
Ah, I had forgot about that!

Can you please open a new issue asking for that feature?

Thanks
