### ISSUE TITLE
Deal with null collections in Qute

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#14610]
**Description**

`{#for pet in owner.pets}`

If pets is null collection, then a NPE is thrown. It can be fixed with an `if` but your HTML file looks more complex then.

**Implementation ideas**

Maybe implement something like:

`{#for pet in ?owner.pets}` which means that `null` value is the same as an empty list.

**Comment by mkouba** [comment]
Hm, a more idiomatic way would be probably `{#for pet in owner.pets.orEmpty}`...  @lordofthejars WDYT?

Currently, it's possible to pass an empty list and use it as a default value, e.g. something like `{#for pet in owner.pets.or(emptyList)}` should work if `emptyList` resolves to `Collections.emptyList()`.

**Comment by lordofthejars** [comment]
Well with age I am getting lazy to have to write all the `or(emptyList)` so
I prefer the Elvis way but because I am lazy nothin else.

Missatge de Martin Kouba <notifications@github.com> del dia dt., 26 de gen.
2021 a les 11:05:

**Comment by mkouba** [comment]
> Well with age I am getting lazy to have to write all the `or(emptyList)` so I prefer the Elvis way but because I am lazy nothin else. 

Well, `?` is not a full elvis ;-).

I prefer `pets.orEmpty` that would return an empty list if pets is null.

**Comment by lordofthejars** [comment]
Then go for it :)

Missatge de Martin Kouba <notifications@github.com> del dia dt., 26 de gen.
2021 a les 11:16:
