### ISSUE TITLE
Error creating image on RHEL with podman

### ISSUE THREAD

**Issue by ewoks** [quarkusio/quarkus#14613]
I'm facing issue similar to #8386
Error message states `Image generation failed. Exit code: 125` and `Unable to get GraalVM version from the native-image binary. `
Increasing xmx (to 10g) as suggested in #8386 doesn't help.

There is one more error logged as INFO after GraalVM version issue stating:
 **`Error: requested user's UID 119066 is too large for the rootless user namespace`**, so I guess this is another flavor of the issue with same Exit error code.
```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] podman run -v /home/<user>/repos/quarkus-getting-started/target/quarkus-getting-started-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 119066:119066 --userns=keep-id --rm registry.access.redhat.com/quarkus/mandrel-20-rhel8 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar quarkus-getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-getting-started-1.0.0-SNAPSHOT-runner Error: requested user's UID 119066 is too large for the rootless user namespace
```

**To Reproduce**
`mvn -e package -Pnative`
with $GRAALVM_HOME is set to ~/.sdkman/candidates/java/20.2.0.r11-grl/

`$ java -version`
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)

`$ mvn -v`
Apache Maven 3.6.3

OS: RHEL 8.3
podman v2.0.5
Quarkus v1.11.0.Final

and following configuration in **application.properties**
```
quarkus.native.container-build=true
quarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-20-rhel8
quarkus.native.container-runtime=podman
```
which is the only modification I added to the project after creating it in VS Code via new Quarkus project wizard.

**Comment by jerboaa** [comment]
This seems to be a root-less podman/linux kernel namespace limitation (not mandrel related):

```
$ podman run --rm -ti --user 119066:119066 --userns=keep-id registry.access.redhat.com/ubi8
Error: requested user's UID 119066 is too large for the rootless user namespace
$ podman run --rm -ti --user 11906:11906 --userns=keep-id registry.access.redhat.com/ubi8
bash-4.4$ exit
$
```

Any chance to get a smaller UID? Failing that you'll need to change `/etc/subuid` to include the large user id. For me this didn't work either, but you may have more luck. See:
https://www.redhat.com/sysadmin/user-flag-rootless-containers

**Comment by ewoks** [comment]
Thanks for the article, I suspected it is that, but article confirms that UID can't be  > 65536..
Any recommendation on changing it for myuser? Currently I have:
```
rhel-liveuser:100000:65536
splunk:165536:65536
myuser:231072:65536
```
Should I actually touch this manually?

**Comment by jerboaa** [comment]
From the article:
```
One potential issue that we have seen users have is when they specify a large UID on rootless containers. Remember that the rootless Podman user is only allocated a limited number of UIDs, as defined in the /etc/subuid file. Usually, you can only use 65536 UIDs. This means that if you attempt to launch a rootless container with a UID of > 65536, the container will fail. If you have to launch with a larger UID, then you need to modify the /etc/subuid to include the UID you want to use.
```
This does't read to me like it's **not** supported. It just means `/etc/subuid` needs adjusting. So I've dug into this a bit more and this worked for me (on a F33 test system):

```
$ grep UID_MAX /etc/login.defs 
UID_MAX                 200000
[...]
SUB_UID_MAX		600100000
[foobar@f33 ~]$ grep foobar /etc/subuid
foobar:300000:200000
[foobar@f33 ~]$ id
uid=119066(foobar) gid=119066(foobar) groups=119066(foobar) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[foobar@f33 ~]$ podman run --rm -ti --user 119066:119066 --userns=keep-id registry.access.redhat.com/ubi8
bash-4.4$
```

Not sure if the `login.defs` MAX bumps are needed, but that's how I got it working.

**Comment by Karm** [comment]
Hello @ewoks, is this still an issue for you?

**Comment by Karm** [comment]
Out of date.

**Comment by ewoks** [comment]
missed the ping, sorry for that. This is not any issue any more for me, but tbh I don't remember the fix any more
