### ISSUE TITLE
quarkus.oidc.auth-server-url is missing in the all configuration guide

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#14626]
**Describe the bug**
`quarkus.oidc.auth-server-url` and other found in https://github.com/quarkusio/quarkus/blob/df5f7d27916db069d2bcc0744ced7e79d2b79584/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java are missing in the https://quarkus.io/guides/all-config#quarkus-oidc_quarkus-oidc-openid-connect section. 

**Expected behavior**

properties to be listed

**Actual behavior**
properties are not listed

**To Reproduce**

Visit https://quarkus.io/guides/all-config#quarkus-oidc_quarkus-oidc-openid-connect and observe missing properties. 

**Additional context**

I think the generator is not scanning config items from super classes, in this case https://github.com/quarkusio/quarkus/blob/df5f7d27916db069d2bcc0744ced7e79d2b79584/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java  hence that's why they are not showing. 

/cc @miguelsorianod thanks for spotting this.

**Comment by sberyozkin** [comment]
Hey @machi1990 Interesting, yes, some common properties made it into the `OidcCommonConfig` with the introduction of `quarkus-oidc-client`, with `quarkus-oidc-client` `OidcClientConfig` and `quarks-oidc` `OidcTenantConfig` extending it

**Comment by machi1990** [comment]
> Hey @machi1990 Interesting, yes, some common properties made it into `OidcCommonConfig` with the introduction of `quarkus-oidc-client`, with `quarkus-oidc-client` `OidcClientConfig` and `quarks-oidc` `OidcTenantConfig` extending it

Yes, the generator should be able to support this use case. I may look into this once I've some free cycle and noone beats me to it.
