### ISSUE TITLE
Hibernate missing reflection JoinedSubclassEntityPersister definition

### ISSUE THREAD

**Issue by mathianasj** [quarkusio/quarkus#1463]
The hibernate-orm extension does not define a constructor reflection for the JoinedSubclassEntityPersister class.  This is required when using generic tables and class extension of entities.

**Comment by mathianasj** [comment]
I do have a pull request ready to add this if you would like @gsmet

**Comment by gsmet** [comment]
@mathianasj ah sorry, already created https://github.com/quarkusio/quarkus/pull/1464 :/

**Comment by gsmet** [comment]
I added one more that was missing.

**Comment by gsmet** [comment]
@mathianasj could you check my PR and confirm it solves your issue?

**Comment by mathianasj** [comment]
Building and checking now

**Comment by mathianasj** [comment]
@gsmet that has resolved my issue

**Comment by gsmet** [comment]
Thanks for checking.
