### ISSUE TITLE
AWS X-Ray dependency version not being updated

### ISSUE THREAD

**Issue by martinoneutrino** [quarkusio/quarkus#14661]
**Description**
It seems that most other AWS dependencies are automatically updated by dependabot. However, the `aws-xray-recorder-sdk-aws-sdk-v2` version is still at 2.4.0 (Nov 2019), although the current version is 2.8.0 (Nov 2020).

**Implementation ideas**
Update dependabot so that the `aws-xray.version` is updated automatically.
```
<groupId>com.amazonaws</groupId>
<artifactId>aws-xray-recorder-sdk-aws-sdk-v2</artifactId>
<version>${aws-xray.version}</version>
```

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/15376 .
