### ISSUE TITLE
Bump swagger ui version

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#14677]
**Description**

The swagger-ui is outdated. New version already support the openidConnect security schema.

**Comment by phillip-kruger** [comment]
@AmsterdamFilho - We are currently using v3.40.0, that, as far as I know, is the latest. What version are you looking at ?

**Comment by phillip-kruger** [comment]
see https://github.com/smallrye/smallrye-open-api/blob/23c69bf32dfcdb25dade808729d0df3288b0dafe/ui/open-api-ui/pom.xml#L16

**Comment by AmsterdamFilho** [comment]
@phillip-kruger The problem is that I have this configuration:

`{
  "openapi": "3.0.3",
  "info": {
    "title": "test",
    "description": "test",
    "version": "1.0.0-SNAPSHOT"
  },
  "security": [
    {
      "openid": []
    }
  ],
  "paths": {
  },
  "components": {
    "securitySchemes": {
      "openid": {
        "type": "openIdConnect",
        "openIdConnectUrl": "https://some-url.com/auth/realms/some-realm/.well-known/openid-configuration"
      }
    }
  }
}
`

When accessing http://localhost:8080/q/swagger-ui/ I get this
<img width="672" alt="Screen Shot 2021-02-02 at 08 47 23" src="https://user-images.githubusercontent.com/12434206/106597186-d28b9580-6534-11eb-9bc9-d98d837455c6.png">
When downloading the swagger ui from here https://github.com/swagger-api/swagger-ui, running it locally and accessing http://localhost:7999/index.html?url=http://localhost:8080/openapi I get this
<img width="685" alt="Screen Shot 2021-02-02 at 08 48 55" src="https://user-images.githubusercontent.com/12434206/106597190-d4555900-6534-11eb-85ed-a151d01c73c6.png">
So I figured the swagger-ui version is outdated, but maybe there is another problem.

**Comment by phillip-kruger** [comment]
Can you look in your browser's web console if there is any errors when doing the available authorizations ?
Also have a look at the swagger-ui configuration options, maybe you need something there ?

**Comment by AmsterdamFilho** [comment]
Yes, I can see some errors...

<img width="1456" alt="Screen Shot 2021-02-02 at 21 37 26" src="https://user-images.githubusercontent.com/12434206/106681412-2cc14080-659f-11eb-9262-d2623e668d98.png">

**Comment by phillip-kruger** [comment]
@AmsterdamFilho - can you please create a small reproducer that I can look at ?

**Comment by AmsterdamFilho** [comment]
@phillip-kruger I updated Quarkus to 1.11.1.Final and the issue is fixed. 
I guess #14422 fixed it.

**Comment by phillip-kruger** [comment]
Great !
