### ISSUE TITLE
OpenAPI invalid document - missing schema element

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#14670]
**Describe the bug**
The generated openapi document is missing the schema element "MessageDataItemsAnimal".

Bug is in Quarkus version: **1.11.1.FINAL** and not in **1.11.0.FINAL**

**Expected behavior**
The generated openapi document is consistent.

**Actual behavior**
The generated openapi document refereces the schema "MessageDataItemsAnimal" but not creating it.

**To Reproduce**

1. Clone and start the reproducer: https://github.com/haraldatbmw/openapi-reproducer
2. Look at the openapi document at http://localhost:8080/q/openapi
3. Or open the swagger-ui at http://localhost:8080/q/swagger-ui and try to expand the schema AnimalListEnvelope --> error occurs

**Environment (please complete the following information):**
 - Quarkus version: 1.11.1.FINAL

**Comment by phillip-kruger** [comment]
@MikeEdgar - can this be something in here : https://github.com/smallrye/smallrye-open-api/pull/623 ??

**Comment by MikeEdgar** [comment]
@phillip-kruger - looks like it. The behaviour is the same in `master` as well. I am looking into it.

**Comment by MikeEdgar** [comment]
@haraldatbmw - can you try one of the following:

1. Remove `@Schema` from `MessageDataItems`
2. Add `type = SchemaType.OBJECT` to `@Schema` from `MessageDataItems`

This is a work-around until a code change is made and released.

**Comment by haraldatbmw** [comment]
@MikeEdgar 

Replacing this:

```java
@Schema
public class MessageDataItems<T> {
```

with this:

```java
@Schema(type = SchemaType.OBJECT)
public class MessageDataItems<T> {
```

seems to works :-)
