### ISSUE TITLE
quarkus-quartz clustered job via @Schedule problem

### ISSUE THREAD

**Issue by apat59** [quarkusio/quarkus#14671]
Environment 
quarkus version 1.11.1.Final
jvm mode

Description: @Scheduled annotated method doesn't act as clustered job.
Way to reproduce: 
quartz-quickstart is enough to reproduce the problem.

Few comments:
* docker-compose.yml should use QUARKUS_DATASOURCE_JDBC_URL and not QUARKUS_DATASOURCE_URL
* I've update the Bean using @Scheduled(every = "30s", identity = "taskbean_schedule")
* I'm building then running using docker-compose up --scale tasks=3 --scale nginx=1

3 tasks are created every 30 seconds, not one.

Is there a way to mimic clustering within a test? I may be running the app badly.

```
tasks_1     | 2021-01-28 09:46:22,756 INFO  [io.quarkus] (main) quartz-quickstart 1.0-SNAPSHOT on JVM (powered by Quarkus 1.11.1.Final) started in 1.686s. Listening on: http://0.0.0.0:8080
tasks_1     | 2021-01-28 09:46:22,756 INFO  [io.quarkus] (main) Profile prod activated. 
tasks_1     | 2021-01-28 09:46:22,756 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, mutiny, narayana-jta, quartz, resteasy, resteasy-jackson, scheduler, smallrye-context-propagation]
tasks_1     | Hibernate: 
tasks_1     |     select
tasks_1     |         nextval ('hibernate_sequence')
tasks_2     | 2021-01-28 09:46:22,782 INFO  [org.qua.plu.his.LoggingJobHistoryPlugin] (QuarkusQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.taskbean_schedule fired (by trigger io.quarkus.scheduler.Scheduler.taskbean_schedule_trigger) at:  09:46:22 01/28/2021
tasks_1     | Hibernate: 
tasks_1     |     insert 
tasks_1     |     into
tasks_1     |         TASKS
tasks_1     |         (createdAt, id) 
tasks_1     |     values
tasks_1     |         (?, ?)
tasks_1     | 2021-01-28 09:46:22,788 INFO  [org.qua.plu.his.LoggingJobHistoryPlugin] (QuarkusQuartzScheduler_Worker-1) Job [io.quarkus.scheduler.Scheduler.taskbean_schedule] execution complete and reports: null
tasks_2     | 2021-01-28 09:46:22,824 INFO  [io.quarkus] (main) quartz-quickstart 1.0-SNAPSHOT on JVM (powered by Quarkus 1.11.1.Final) started in 1.647s. Listening on: http://0.0.0.0:8080
tasks_2     | 2021-01-28 09:46:22,824 INFO  [io.quarkus] (main) Profile prod activated. 
tasks_2     | 2021-01-28 09:46:22,824 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, mutiny, narayana-jta, quartz, resteasy, resteasy-jackson, scheduler, smallrye-context-propagation]
tasks_2     | Hibernate: 
tasks_2     |     select
tasks_2     |         nextval ('hibernate_sequence')
tasks_2     | Hibernate: 
tasks_2     |     insert 
tasks_2     |     into
tasks_2     |         TASKS
tasks_2     |         (createdAt, id) 
tasks_2     |     values
tasks_2     |         (?, ?)
tasks_2     | 2021-01-28 09:46:22,845 INFO  [org.qua.plu.his.LoggingJobHistoryPlugin] (QuarkusQuartzScheduler_Worker-1) Job [io.quarkus.scheduler.Scheduler.taskbean_schedule] execution complete and reports: null
tasks_3     | 2021-01-28 09:46:23,278 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 2.0.0
tasks_3     | 2021-01-28 09:46:23,278 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
tasks_3     | 2021-01-28 09:46:23,615 INFO  [org.qua.plu.his.LoggingJobHistoryPlugin] (QuarkusQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.taskbean_schedule fired (by trigger io.quarkus.scheduler.Scheduler.taskbean_schedule_trigger) at:  09:46:23 01/28/2021
tasks_3     | 2021-01-28 09:46:23,656 INFO  [io.quarkus] (main) quartz-quickstart 1.0-SNAPSHOT on JVM (powered by Quarkus 1.11.1.Final) started in 2.534s. Listening on: http://0.0.0.0:8080
tasks_3     | 2021-01-28 09:46:23,657 INFO  [io.quarkus] (main) Profile prod activated. 
tasks_3     | 2021-01-28 09:46:23,657 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, mutiny, narayana-jta, quartz, resteasy, resteasy-jackson, scheduler, smallrye-context-propagation]
tasks_3     | Hibernate: 
tasks_3     |     select
tasks_3     |         nextval ('hibernate_sequence')
tasks_3     | Hibernate: 
tasks_3     |     insert 
tasks_3     |     into
tasks_3     |         TASKS
tasks_3     |         (createdAt, id) 
tasks_3     |     values
tasks_3     |         (?, ?)
tasks_3     | 2021-01-28 09:46:23,679 INFO  [org.qua.plu.his.LoggingJobHistoryPlugin] (QuarkusQuartzScheduler_Worker-1) Job [io.quarkus.scheduler.Scheduler.taskbean_schedule] execution complete and reports: null
```

**Comment by apat59** [comment]
I don't think the "steps to reproduce" above are accurate.
I'm not observing exactly the same behavior with my app which makes me think the above setup is broken (docker image, docker-compose ?).

What I'm getting in my app is:
* one task per pod is created at pod start, this is the actual issue 
* then everything is fine, only one pod will create the next task after the defined interval

**Comment by mkouba** [comment]
Hm, I was able to reproduce the problem locally.

@apat59 what version of quarkus do you use?

**Comment by apat59** [comment]
1.11.1.Final
I did (git)clone yesterday

**Comment by apat59** [comment]
I'm not going to comment on my local setup which I suspect is broken.

How is the @scheduled parsed and what is it doing exactly?
Could it be the trigger is simply re created by the second node, triggering n initial execution per node?

**Comment by mkouba** [comment]
It seems to be related to the `org.quartz.jobStore.clusterCheckinInterval` property (20s by default, Quartz docs: _"Set the frequency (in milliseconds) at which this instance checks-in with the other instances of the cluster. Affects the quickness of detecting failed instances."_). 

If I change the annotation to `@Scheduled(every = "21s", identity = "task-job")` the task is only executed on one node.

> Could it be the trigger is simply re created by the second node, triggering n initial execution per node?

Each node should remove all previous job definitions and triggers, see also https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187. @machi1990 am I right?

**Comment by mkouba** [comment]
> How is the @scheduled parsed and what is it doing exactly?

Annotation metadata are used to build a job and a trigger:
https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L121-L191

**Comment by machi1990** [comment]
> It seems to be related to the `org.quartz.jobStore.clusterCheckinInterval` property (20s by default, Quartz docs: _"Set the frequency (in milliseconds) at which this instance checks-in with the other instances of the cluster. Affects the quickness of detecting failed instances."_).

We already allow the user to configure this? 

> If I change the annotation to `@Scheduled(every = "21s", identity = "task-job")` the task is only executed on one node.
> 
> > Could it be the trigger is simply re created by the second node, triggering n initial execution per node?
> 
> Each node should remove all previous job definitions and triggers, see also https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187. @machi1990 am I right?

This is correct.

**Comment by mkouba** [comment]
> We already allow the user to configure this?

I don't think so.

**Comment by machi1990** [comment]
> > We already allow the user to configure this?
> 
> I don't think so.

That's correct - I do not see it in https://quarkus.io/guides/quartz#quartz-configuration-reference.

**Comment by mkouba** [comment]
It's staightforward to implement but harder to test ;-). I can send a PR later today...

**Comment by apat59** [comment]
> > Each node should remove all previous job definitions and triggers, see also https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187. @machi1990 am I right?
> 
> This is correct.

humm, so this is expected behavior and somehow makes sense from a technical point of view.
That might deserve a tiny note in the reference guide.

If I deploy one app with some @Scheduled(every) methods, it's not intuitive these methods will be executed one time by each pod at startup, then once.

**Comment by machi1990** [comment]
> It's staightforward to implement but harder to test ;-). 

Yes. 

> I can send a PR later today...

Thanks, I can jump in for review.

**Comment by mkouba** [comment]
> humm, so this is expected behavior and somehow makes sense from a technical point of view.
> That might deserve a tiny note in the reference guide.
> 
> If I deploy one app with some @scheduled(every) methods, it's not intuitive these methods will be executed one time by each pod at startup, then once.

Yes, to me it seems like a limitation of the clustered scheduler. Unfortunately, the Quartz docs don't describe this config property in more detail.

**Comment by apat59** [comment]
would it make sense to create a new config or option like
 @scheduled(ifExists= every = "30s", identity = "taskbean_schedule")

with
    enum IfExists {
DELETE_RECREATE,
KEEP_CURRENT,
    }

Sounds bad to me, this is a tricky one.

How about including the app version in the quartz groups related columns?
Currently you have io.quarkus.scheduler.Scheduler as group name.
Could be io.quarkus.scheduler.Scheduler_APP_VERSION
That way it is quite easy to know when we should delete/recreate.

Maybe that would start being very complex.

**Comment by mkouba** [comment]
Hm, there must be something else wrong. Setting the `org.quartz.jobStore.clusterCheckinInterval` does not always help. We need to find out more about the cluster locking mechanism...

**Comment by mkouba** [comment]
No matter how hard I try, I'm not able to make it work reliably :-(.

I've tried to make the `clusterCheckinInterval `configurable and set `quarkus.quartz.cluster-checkin-interval=5000` and set `org.quartz.jobStore.acquireTriggersWithinLock=ture` (WIP in this branch: https://github.com/mkouba/quarkus/tree/issue-14671).

And I've also tried to switch to `quarkus.quartz.store-type=jdbc-tx`.

My `TaskBean` from the quickstart looks now:
```java
@ApplicationScoped
public class TaskBean {

    private static final Logger LOG = Logger.getLogger(TaskBean.class);

    @Inject
    Scheduler scheduler;

    @Transactional
    @Scheduled(delayed = "3s", every = "10s", identity = "task-job")
    void schedule() throws SchedulerException {
        Task task = new Task();
        task.persist();
        LOG.infof("===> New task created: %s [instanceId: %s, instanceName: %s]", LocalDateTime.now(),
                scheduler.getSchedulerInstanceId(), scheduler.getSchedulerName());
    }
}
```

It's also possible to log all postgres statements (just add `command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]` in the `docker-compose.yml` under `postgres:`) but I wasn't able to read any useful info from the log.

@machi1990 It would be great if you can take a look too. The quickstart needs to be fixed too: https://github.com/mkouba/quarkus-quickstarts/tree/quartz-fix

**Comment by apat59** [comment]
I really have a doubt on the docker-compose env to check this. I also noticed some weirdness, there might be race condition.
Here is what I can confirm from our real app running with 2 pods in Openshift (however built with quarkus 1.10.1.Final). Hoping that can help.

Programmatic created JOBS: no problem at all, perfectly working as expected
@Scheduled annotated methods: both pods are running all annotated method at startup, then everything runs as expected. One or the other pod will execute the job, but only one execution will happen.
As you explained, that seems to be expected for the first execution.

**Comment by machi1990** [comment]
> No matter how hard I try, I'm not able to make it work reliably :-(.
> 
> I've tried to make the `clusterCheckinInterval `configurable and set `quarkus.quartz.cluster-checkin-interval=5000` and set `org.quartz.jobStore.acquireTriggersWithinLock=ture` (WIP in this branch: https://github.com/mkouba/quarkus/tree/issue-14671).
> 
> And I've also tried to switch to `quarkus.quartz.store-type=jdbc-tx`.
> 
> My `TaskBean` from the quickstart looks now:
> 
> ```java
> @ApplicationScoped
> public class TaskBean {
> 
>     private static final Logger LOG = Logger.getLogger(TaskBean.class);
> 
>     @Inject
>     Scheduler scheduler;
> 
>     @Transactional
>     @Scheduled(delayed = "3s", every = "10s", identity = "task-job")
>     void schedule() throws SchedulerException {
>         Task task = new Task();
>         task.persist();
>         LOG.infof("===> New task created: %s [instanceId: %s, instanceName: %s]", LocalDateTime.now(),
>                 scheduler.getSchedulerInstanceId(), scheduler.getSchedulerName());
>     }
> }
> ```
> 
> It's also possible to log all postgres statements (just add `command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]` in the `docker-compose.yml` under `postgres:`) but I wasn't able to read any useful info from the log.
> 
> @machi1990 It would be great if you can take a look too. The quickstart needs to be fixed too: https://github.com/mkouba/quarkus-quickstarts/tree/quartz-fix

Thank you @mkouba I think the issue here is the first run on startup and I suspect that at this point the cluster check algorithm has not kicked yet or finished yet. I'll have a look at this too once I've some free cycles.

**Comment by machi1990** [comment]
> > No matter how hard I try, I'm not able to make it work reliably :-(.
> > I've tried to make the `clusterCheckinInterval `configurable and set `quarkus.quartz.cluster-checkin-interval=5000` and set `org.quartz.jobStore.acquireTriggersWithinLock=ture` (WIP in this branch: https://github.com/mkouba/quarkus/tree/issue-14671).
> > And I've also tried to switch to `quarkus.quartz.store-type=jdbc-tx`.
> > My `TaskBean` from the quickstart looks now:
> > ```java
> > @ApplicationScoped
> > public class TaskBean {
> > 
> >     private static final Logger LOG = Logger.getLogger(TaskBean.class);
> > 
> >     @Inject
> >     Scheduler scheduler;
> > 
> >     @Transactional
> >     @Scheduled(delayed = "3s", every = "10s", identity = "task-job")
> >     void schedule() throws SchedulerException {
> >         Task task = new Task();
> >         task.persist();
> >         LOG.infof("===> New task created: %s [instanceId: %s, instanceName: %s]", LocalDateTime.now(),
> >                 scheduler.getSchedulerInstanceId(), scheduler.getSchedulerName());
> >     }
> > }
> > ```
> > 
> > 
> > It's also possible to log all postgres statements (just add `command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]` in the `docker-compose.yml` under `postgres:`) but I wasn't able to read any useful info from the log.
> > @machi1990 It would be great if you can take a look too. The quickstart needs to be fixed too: https://github.com/mkouba/quarkus-quickstarts/tree/quartz-fix
> 
> Thank you @mkouba I think the issue here is the first run on startup and I suspect that at this point the cluster check algorithm has not kicked yet or finished yet. I'll have a look at this too once I've some free cycles.

When I was trying the reproducer, the only issue I encountered is the one I stated above where during startup more than one app node "could" execute the job. This was happening randomly depending on the condition of the cluster checking. 

It was due to the scheduling logic https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187 which I've changed to only schedule the job only when it does not exists. With this change, I managed to get deterministic result where a job is scheduled on one node picked up and when this node is shutdown, the job will be picked up by any of the remaining node.

@mkouba I tried pushing something for you to try in your fork but had permission issues cause of this I've pushed in a [branch](https://github.com/machi1990/quarkus/tree/issue-14671.) on my fork. Can you give it a try and see if you get consistent results?

**Comment by apat59** [comment]
> It was due to the scheduling logic https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187 which I've changed to only schedule the job only when it does not exists. With this change, I managed to get deterministic result where a job is scheduled on one node picked up and when this node is shutdown, the job will be picked up by any of the remaining node.

@machi1990 
This is what I was thinking but immediately concluded that would start to be tricky

Imagine we deploy
@Scheduled(delayed = "3s", every = "10s", identity = "task-job")

Later deployment
@Scheduled(delayed = "3s", every = "20s", identity = "task-job")

Would the new interval apply or not?

We should check all the details to decide if it's a delete/replace or ignore.

**Comment by machi1990** [comment]
> > It was due to the scheduling logic https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L185-L187 which I've changed to only schedule the job only when it does not exists. With this change, I managed to get deterministic result where a job is scheduled on one node picked up and when this node is shutdown, the job will be picked up by any of the remaining node.
> 
> @machi1990
> This is what I was thinking but immediately concluded that would start to be tricky
> 
> Imagine we deploy
> @scheduled(delayed = "3s", every = "10s", identity = "task-job")
> 
> Later deployment
> @scheduled(delayed = "3s", every = "20s", identity = "task-job")

This was indeed the motivation to delete previous jobs. To make sure that no stale jobs are present but doing so it meant the schedulers acting as a migration extension, which it is not.  

> Would the new interval apply or not?

The new interval will apply "eventually" but the first two lines might still be on the previous data. To get past this, 
- I'll advise using a db migration to remove all stale/old jobs 
- change the identity so that a new job will be created 
- or accept that the new deployment will kick in after some initial reconciliation between the old and new state.

> We should check all the details to decide if it's a delete/replace or ignore.

I agree, but this will making the extension doing more than what's supposed to do IMO.

**Comment by apat59** [comment]
> I agree, but this will making the extension doing more than what's supposed to do IMO.

I tend to agree, the extension can't handle everything possible scenario.
The extension is very handy but as soon as you enable clustering, it might be misleading.

I think a big warning in the doc about "it's your responsibility to manage existing jobs, clean them up".
How about providing a rest endpoint which lists all existing jobs ? The idea is to allow the user to quickly check what is actually scheduled.
I personally will check directly to the db but not sure all users will.

**Comment by mkouba** [comment]
> > I agree, but this will making the extension doing more than what's supposed to do IMO.
> 
> I tend to agree, the extension can't handle everything possible scenario.
> The extension is very handy but as soon as you enable clustering, it might be misleading.
> 
> I think a big warning in the doc about "it's your responsibility to manage existing jobs, clean them up".

:+1:  

A new deployment should always clear the previous state. Moreover, we should be clear that the apps that form the "cluster" should be identical.

> How about providing a rest endpoint which lists all existing jobs ? The idea is to allow the user to quickly check what is actually scheduled.
> I personally will check directly to the db but not sure all users will.

I don't think we should expose this kind of info by default. We could do this for the dev mode though, e.g. something similar to `http://localhost:8080/q/dev/io.quarkus.quarkus-scheduler/schedules`.

**Comment by mkouba** [comment]
I can confirm that @machi1990 's fix results in consistent behavior (at least it's locally reproducible ;-). I've sent a PR and added a warning to the doc.
