### ISSUE TITLE
consider re-instating OpenShift/S2I quickstart documentation

### ISSUE THREAD

**Issue by jmtd** [quarkusio/quarkus#14701]
The deploying-to-openshift-s2i quickstart was deleted in commit 8930ea1919182fa38f55c9b84bb2b78b053049d3 ("Remove old (totally manual) knative and openshift guides"). Consequently https://quarkus.io/guides/deploying-to-openshift-s2i throws 404 (and incoming links from blogs and guides etc are broken)

The content of that page was useful (although might need updating for more recent quarkus changes) and is not covered by the remaining, similar guides:

 * https://quarkus.io/guides/deploying-to-openshift
 * https://quarkus.io/guides/container-image
 
These both cover deployments driven by Maven plugin in the application source tree rather than a deployment driven from outside the source tree, as in the older guide: I.e., the old guide had a deployment triggered like this:

    oc new-app registry.access.redhat.com/ubi8/openjdk-11~https://github.com/quarkusio/quarkus-quickstarts.git \
       --context-dir=getting-started --name=quarkus-quickstart

I'd accept it if the maven-driven deployment approach is preferred and likely more common but the oc-driven deployment case is still useful in some circumstances. Specifically, I'm writing some content for developer.redhat.com which is primarily OpenShift-oriented (rather than quarkus-oriented), planned to re-use this example and had linked through to the (now missing) page from my draft.

**Comment by geoand** [comment]
cc @maxandersen @cescoffier

**Comment by geoand** [comment]
Closing this as it did not get any traction
