### ISSUE TITLE
Load any yml from config external folder

### ISSUE THREAD

**Issue by lferna** [quarkusio/quarkus#14710]
**Description**
Currently, there is a possibility to load configuration yml from an external folder. According to the documentation, the external folder must be named "config". But the file name inside the folder must be "application.yml". If the file name is different, the properties can not be found.

**Implementation ideas**
It would be great if every yml within "config" folder should be able to be load as a configuration file regardless of its name (or inject the file like Spring)

**Comment by radcortez** [comment]
Hi @lferna this is already supported for some time as an experimental feature for `properties` files.

Please refer to: https://smallrye.io/docs/smallrye-config/config/config.html#locations and https://github.com/quarkusio/quarkus/tree/master/integration-tests/smallrye-config

Starting `1.13` it will be supported also as a `quarkus` property.

And I'll be adding the `YAML` support as well.

**Comment by radcortez** [comment]
Actually the support for additional `yaml` files is already available in the last version with the property `smallrye.config.locations`. Next version will add the config `quarkus.config.locations` to align with the quarkus namespace.

Please refer to this: https://smallrye.io/docs/smallrye-config/config/config.html#locations.

I'll be closing this one. If you feel that the current support is not enough, feel free to reopen and tell us what is missing :)
