### ISSUE TITLE
Test extension uses a run time config class during static init

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1472]
This breaks once we read run-time config from the main method.

**Comment by dmlloyd** [comment]
I'm unassigning this because the obvious solution (make the `configureBean` method be `RUNTIME_INIT`) does not work due to the production of a `BeanContainerListener`, which is not allowed at run time.

The extension is basically flawed in that it's consuming run time config (which won't be available until after the `main` method runs) but producing something for static init, which runs before run time.

**Comment by starksm64** [comment]
So the idea was to pass the configuration seen at runtime to a runtime component for validation. So if the bean was returned in a RuntimeValue from the configureBean call and then actually called with the configuration from a RUNTIME_INIT method would that solve this?

**Comment by dmlloyd** [comment]
Yes that seems reasonable.

**Comment by starksm64** [comment]
Ok, I'll take a look at fixing it.
