### ISSUE TITLE
resteasy-reactive header propagation

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#14736]
Description:
The http header from the client is not forwarded out from the resteasy client towards the external service.
This works great without the usage of resteasy-reactive

Expected behavior:
When a client is invoking a rest endpoint with an Authorization header, I expect that the Authorization header is propagated out from the resteasy client towards the external service.

Actual behavior:
From logs I see that my Authorization header is NOT forwarded towards my external service, which again replay with statuscode 401

To Reproduce:
My project is similar to: https://quarkus.io/guides/rest-client
But the external service invoked by my application is secured with basic auth.
My reactive changes:
pom.xml:
I replace: quarkus-resteasy-jackson with quarkus-resteasy-reactive-jackson
I removed: quarkus-resteasy-mutiny
I added: quarkus-rest-client-jackson
Add: @RegisterClientHeaders to the CountriesService
Add: org.eclipse.microprofile.rest.client.propagateHeaders=Authorization to application.properties

Verification:
Add:  .headers(new Headers(new Header("Authorization", "TstVal"))) to CountriesResourceTest
Run the test
Monitor the http outgoing logging, ie. No Authorization can be seen

uname -a
Linux rhclient444.xxx 3.10.0-1160.6.1.el7.x86_64 #1 SMP Wed Oct 21 13:44:38 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
Quarkus version: 1.11.1.Final
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /home/xxx/opt/jdk-8u192_b12/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.6.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@michalszynkiewicz sounds like one for you :)

**Comment by michalszynkiewicz** [comment]
it seems there's some clash between resteasy reactive and client from "normal" resteasy.

In the near future we will have a MP Rest Client implementation based on Reactive RestEasy with which you'll be able to pass through the headers and use Reactive RestEasy.

**Comment by lthasle** [comment]
Ok! I am looking forward for the solution, I can help out with the verification

**Comment by lthasle** [comment]
The fault still exists, with the 1.12 version also.
I guess you already know, as the issiue is not closed

**Comment by michalszynkiewicz** [comment]
This will be resolved by https://github.com/quarkusio/quarkus/pull/15141
The pull request introduces a new microprofile rest client implementation, based on RestEasy Reactive
 
I'll add this issue to resolved issues
