### ISSUE TITLE
Use proxy setting for keycloak policy enforcer

### ISSUE THREAD

**Issue by albert0815** [quarkusio/quarkus#14733]
**Description**
For OIDC a proxy setting was introduced with #8088. Currently this setting is not used in the policy enforcer. But actually the same resource URI (quarkus.oidc.auth-server-url) is used to connect to Keycloak. When using quarkus.oidc.proxy.host one most probably wants to use that proxy setting also for the policy enforcement. At least this is the case for us. So I would like to suggest to reuse the proxy settings assigned to the OIDC connection also for the policy enforcement. But if you assume it might be better to use a different setting this would be fine for us as well. Anyway we would need a way to use a proxy for the connection to the Keycloak used for policy enforcement.

**Implementation ideas**
I assume the implementation could be similar to what is in use for the oidc connection.

**Comment by sberyozkin** [comment]
@albert0815 
`org.keycloak.representations.adapters.config.AdapterConfig` only has a `setProxyUrl` method - can it be enough ? If yes then I can open a PR (which will pick up the proxy host and port properties from the OIDC config), otherwise a Keycloak issue will need to be opened asking for more proxy properties to be supported (username, password)

**Comment by albert0815** [comment]
For me proxy host and port would be sufficient.

**Comment by sberyozkin** [comment]
@albert0815 OK, let me handle it, @pedroigor Hi Pedro can you please also consider opening a Keycloak RFE to support the proxy authentication (username, password properties)

**Comment by pedroigor** [comment]
@sberyozkin Thanks for looking at this one. Regarding the RFE, I'm not sure if it makes sense to open one? We had a similar issue [1] like this one a long time ago, but never for authentication.

[1] https://issues.redhat.com/browse/KEYCLOAK-2054

**Comment by sberyozkin** [comment]
@pedroigor Sure, sounds good :-), it is just that Vertx ProxyOptions have these properties... Yeah, we can review in the future if needed
