### ISSUE TITLE
Gradle tasks should be renamed

### ISSUE THREAD

**Issue by jnizet** [quarkusio/quarkus#1473]
The convention is to name Gradle tasks like Java methods, in camelCase. Gradle uses that to provide shortcuts. For example, instead of `./gradlew javaCompile`, you can just use `./gradlew jC`.
Task names become Groovy/Kotlin variables, and you should be able to reference the tasks directly, without using a string:

    assemble.dependsOn(quarkusBuild)

Having a dash in the name makes all this more difficult than it should, and breaks one additional Gradle best practice.

**Comment by Sanne** [comment]
Many thanks, that's very good feedback! Let's fix this.

**Comment by edeandrea** [comment]
You should also look at the Gradle object model rather than having hard `dependsOn` between tasks. Declaring your own extensions/objects with inputs/outputs and having your tasks use the inputs/outputs of other tasks/extensions will remove the need to have your tasks depend on other tasks.

**Comment by stalep** [comment]
I agree, we should change this. The reason we went for the original task names was to have them as similar to maven as possible. - I guess that's not a valid reason :)
