### ISSUE TITLE
Reactive rest-easy, support sub resources

### ISSUE THREAD

**Issue by leutrimmusliuu** [quarkusio/quarkus#14747]
ResourceInfo doesn't contain information about subresource method annotations at @ServerRequestFilter.
In the following example resource info should contain annotatitons @Get, @Path, @EndpointAnnotation, but instead it has the informations about the setupSubResource() method. Below you have the code examples. Also I attached a producer app.

public class RequestFilter {
  @ServerRequestFilter
  public Uni<Void> filter(
      ContainerRequestContext requestContext,
      ResourceInfo resourceInfo,
      HttpServerRequest httpServerRequest) {
    if (!hasEndpointAnnotation(resourceInfo)) {
      System.out.println("Resource Annotation Missing");
      return Uni.createFrom().voidItem();
    }
    return Uni.createFrom().voidItem();
  }

  private boolean hasEndpointAnnotation(ResourceInfo resourceInfo) {
    return resourceInfo.getResourceClass().isAnnotationPresent(EndpointAnnotation.class)
        || resourceInfo.getResourceMethod().isAnnotationPresent(EndpointAnnotation.class);
  }
}

@ApplicationScoped
@Path("/resource")
public class Resource {
  @Inject SubResource subResource;

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @EndpointAnnotation("RESOURCE_ANNOTATION")
  public Uni<String> getResource() {
    return Uni.createFrom().item("resource");
  }

  @Path("/sub-resource")
  public SubResource setUpSubresource() {
    return subResource;
  }
}

@ApplicationScoped
public class SubResource {

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @EndpointAnnotation("SUB_RESOURCE")
  @Path("/first")
  public Uni<String> getFirstSubResource() {
    return Uni.createFrom().item("sub resource");
  }
}

@Documented
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface EndpointAnnotation {
  String value();
}

[quarkus.zip](https://github.com/quarkusio/quarkus/files/5905032/quarkus.zip)

**Comment by leutrimmusliuu** [comment]
@geoand

**Comment by geoand** [comment]
Thanks for reporting.

I'll hopefully have a look this week.

**Comment by geoand** [comment]
I took a look at this and actually there is no way of presenting the `ResourceInfo` of the sub-resource in this case, because the filter executes way before we know which sub-resource is returned

**Comment by leutrimmusliuu** [comment]
@geoand That really bad, this means we cannot use sub-resources anymore when we have filtering and annotations, which in most cases we do. Basically this reactive functionality is really limited and will be hard to use (migrate) rest-easy reactive without sub-resources in a bigger application. The point to migrating to a better version(in this case to rest-easy reactive) is to have more functionality, not less. Hope this will be fixed in the future. Thank you anyway.

**Comment by geoand** [comment]
Did this work with RESTEasy Classic?

If so, it didn't seem so from the issue you uploaded

**Comment by leutrimmusliuu** [comment]
@geoand It does work when using javax.ws.rs.container.DynamicFeature. The issue was to show that it doesn't work at @ServerRequestFilter on the reast-easy reactive. I thought it was given that it works on classic one. If you have any suggestion on how to organize sub-resource as a work around please let me know.

**Comment by geoand** [comment]
> @geoand It does work when using javax.ws.rs.container.DynamicFeature. The issue was to show that it doesn't work at @ServerRequestFilter on the reast-easy reactive. I thought it was given that it works on classic one. If you have any suggestion on how to organize sub-resource as a work around please let me know.

I was asking because I tried it with RESTEasy Classic and couldn't get it to work.
If you have such an example, I'd love to see it

**Comment by leutrimmusliuu** [comment]
@geoand  Here is a working example. Please let me know if you have any questions/sugestions.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5989808/code-with-quarkus.zip)

**Comment by geoand** [comment]
Thanks for the reproducer.

What you show in that code does work, but it's not the same thing as you describe in the case of the filter. In your latest example you are deciding whether or not to add a filter using a DynamicFeature, but the filter itself can't know the proper `ResourceInfo`.

That same code should work with RESTEasy Reactive as RESTEasy Reactive supports all the normal JAX-RS features.

**Comment by geoand** [comment]
In your example you could also use https://docs.oracle.com/javaee/7/api/javax/ws/rs/NameBinding.html instead of the dynamic feature.
Supporting `@NamedBinding` with `@ServerRequestFeature` in that case makes sense.

**Comment by leutrimmusliuu** [comment]
@geoand Thanks you for your time and suggestions. If we could have @NamedBinding at @ServerRequestFeature would really help us at many use cases. Looking forward to using it.

**Comment by geoand** [comment]
It will hopefully be in `1.12.1` :)
