### ISSUE TITLE
Implement quarkus:dev mode for camel apps

### ISSUE THREAD

**Issue by gnodet** [quarkusio/quarkus#1474]
The first problem is that a camel application does not necessarily spawn a non-daemon threads, which cause the `quarkus:dev` goal to start the application and close it immediately.
The second problem is that there's no live-reload of resources, because it's only done when an http request is send into undertow.  I suggest to implement a strategy to reload the context using `java.nio.file.WatchService`.
I'll work on a PR for both.

**Comment by emmanuelbernard** [comment]
Thanks Guillaume. Let's see your PR and then we can all discuss on concrete grounds :)

**Comment by gnodet** [comment]
PR available at https://github.com/quarkusio/quarkus/pull/1559
