### ISSUE TITLE
Add a crud capable Kubernetes server test resource

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#14744]
**Description**
Similar to KubernetesMockServerTestResource it would be great to have KubernetesServerTestResource supporting the crud feature of the fabric8 KubernetesServer.

**Implementation ideas**
A new test resource class.  Locally my implementation is just https://github.com/shawkins/mk-agent/blob/39d2606d59a228845d7fa643d277dfe495b64c04/agent-sync/src/test/java/org/bf2/sync/KubernetesServerTestResource.java - at least for my usage there's no need for something like MockServer annotation support.

**Comment by FroMage** [comment]
I'll take this.

**Comment by geoand** [comment]
Coolio
