### ISSUE TITLE
quarkus-integration-test-micrometer-prometheus failing when .minikube/ca.crt is missing

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#14749]
**Describe the bug**
When I attempt to build current master, module `quarkus-integration-test-micrometer-prometheus` fails with

```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ quarkus-integration-test-micrometer-prometheus ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.4.28-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.350 s
[INFO] Finished at: 2021-02-01T17:10:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-micrometer-prometheus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:236)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:64)
[ERROR] 	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:51)
[ERROR] 	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:126)
[ERROR] 	at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient(KubernetesClientUtils.java:49)
[ERROR] 	at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:16)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.nio.file.NoSuchFileException: /home/sanne/.minikube/ca.crt
[ERROR] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[ERROR] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[ERROR] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[ERROR] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[ERROR] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
[ERROR] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
[ERROR] 	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.getInputStreamFromDataOrFile(CertUtils.java:74)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:80)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:115)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:94)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:120)
[ERROR] 	... 15 more

```

**Expected behavior**
A clean checkout should always pass.

**Actual behavior**
Can't build.

**To Reproduce**

Run the build.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ambeast 5.10.9-201.snn4.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: Tried several versions, no difference.
 - Quarkus version or git rev: `515ca8a966` (and various previous commits as I tried to go back some days: no difference)

**Comment by geoand** [comment]
cc @iocanel

**Comment by ebullient** [comment]
weird. I'll double check.

**Comment by iocanel** [comment]
The error, seems like there are environment variables / system properties configuring client certificates, that are not present.
It might be a good idea to when setting up the tests, to cleanup the environment to avoid such issues.

In the client itself we do it on:
1. surefire level: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/pom.xml#L263 
2. junit level too: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/test/java/io/fabric8/kubernetes/client/ConfigTest.java#L70

**Comment by Sanne** [comment]
thanks for the pointer @iocanel !

But I don't have any such environment variable on the terminal I'm using to build this.

I see they are being set by `KubernetesMockServerTestResource` so this seems intentional by who designed this, but I'm not familiar with neither module.
 - https://github.com/quarkusio/quarkus/blob/f188601df7010f76d588dbf33547ccc5bb508c20/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java#L18-L29

Am I the only contributor with this problem?

**Comment by iocanel** [comment]
An other way this can be tirggered is when `.kube/confg` points to a minikube cluster that has been deleted.

In a scenario like this the current cluster will have an entry like:

```
- cluster:
    certificate-authority: /home/<username>/.minikube/ca.crt
    server: https://192.168.49.2:8443
  name: minikube`
```

But the actual `/home/<username>/.minikube/ca.crt` will not be present.

So, I think that we will have to find how the kubernetes-client is getting dragged in and cause such issues.

Quick workarounds till then:

- switch to a valid context
- remove `.kube/config`
- set `KUBERNETES_AUTH_TRYKUBECONFIG` to false.

**Comment by Sanne** [comment]
> An other way this can be tirggered is when .kube/confg points to a minikube cluster that has been deleted.

So that was exactly my problem. Sorry for the noise! I'll close this.

Many thanks @iocanel and @ebullient
