### ISSUE TITLE
Adding mutiny-test-utils in Quarkus bom

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#14755]
**Description**

When using Mutiny in Quarkus, you might want to write tests for the code you developed using it. Mutiny project has a really nice JAR file to simplify writing tests:

```
<groupId>io.smallrye.reactive</groupId>
      <artifactId>mutiny-test-utils</artifactId>
      <version>0.13.0</version>
```

The problem is that since this artifact is not in Quarkus bom, then you need to specify the mutiny version, and this can end up with inconsistencies between mutiny in testing and mutiny in code.

**Comment by jponge** [comment]
Sounds like we could provide a BOM on the Mutiny side (discussed offline with @cescoffier)

**Comment by cescoffier** [comment]
Yes, we started having a bunch of modules in Mutiny (mutiny itself, kotlin, reactive streams ops...). Having a bom start to make some sense.
