### ISSUE TITLE
Application.properties quarkus.resteasy.path not working

### ISSUE THREAD

**Issue by JanHuege** [quarkusio/quarkus#14769]
**Describe the bug**
quarkus.resteasy.path is not working but found in several docs. For example:
https://quarkus.io/guides/getting-started-testing#testing-a-specific-endpoint

**Expected behavior**
quarkus.resteasy.path prefixes all Paths for javax.ws.rs

**Actual behavior**
Is ignored.

**To Reproduce**

1. create simple quarkus app with resteasy-reactive
2. Create Resource with `@Path("/example")`
3. Configure `quarkus.resteasy.path` in `application.properties`

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MINGW64_NT-10.0-19042 Einstein 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys
 - Output of `java -version`: 
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
 - Quarkus version or git rev: 
 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3

**Comment by geoand** [comment]
I just tried it and it works as expected.

**Comment by JanHuege** [comment]
Using resteasy-reactive? Does not work for me. Also not listed on /q/dev application.properties view and IntelliJ IDEA also states `Unknown property 'quarkus.resteasy.path'`

**Comment by geoand** [comment]
No, with RESTEasy Classic. For RESTEasy Reactive you can use `quarkus.http.root-path`.

**Comment by GavinRay97** [comment]
Came here looking for how to set base URL path like `/api` for RESTEasy Reactive, surprisingly hard to find

**Comment by languitar** [comment]
On thing I see with `quarkus.http.root-path` is that this also moves the dev tools and everything else. With RESTEasy Classic and `quarkus.resteasy.path` one could only move the base path of the provided API while leaving the rest in it's original place.

**Comment by loban** [comment]
If anyone else arrives here, for RESTEasy Reactive, use `quarkus.resteasy-reactive.path`.
