### ISSUE TITLE
RuntimeClassLoader inconsistent resource lookups

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1477]
Given a generated resource, a call to `RuntimeClassLoader.getResouce(name)` may return `null` whereas a call to `RuntimeClassLoader.getResources(name)` returns an enumeration with one element.  This is because `getResource()` does not consult the `io.quarkus.runner.RuntimeClassLoader#resources` map.

**Comment by petebowden** [comment]
Is this a quarkus issue or a graal one? 

See: https://github.com/oracle/graal/issues/534

**Comment by dmlloyd** [comment]
Definitely Quarkus.  The `RuntimeClassLoader` is not used in native images; in fact it's only used in dev mode.

**Comment by sberyozkin** [comment]
@dmlloyd, I'm seeing a `null` resource being returned [in this call](https://gitbox.apache.org/repos/asf?p=tika.git;a=blob;f=tika-core/src/main/java/org/apache/tika/mime/MimeTypesFactory.java;h=c6ffd25fa8335531981e85f49b9dfe8a03b7cf77;hb=8e6cf38407e72c9f254aa923b47eff61f10a7c75#l170) inside the native image (while it returns a non-null URL in the regular mode). Is this issue related to what I'm seeing or it is another one ?
FYI, the resource path is `org/apache/tika/mime/tika-mimetypes.xml`, it is attached to the 'tika-core.jar' which is linked

**Comment by gsmet** [comment]
Did you include the resource in your native image (see
`SubstrateResourceBuildItem`)?

**Comment by sberyozkin** [comment]
Thanks for a hint, will try
