### ISSUE TITLE
Exposing the schema-generation.scripts properties in the application.properties

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#14771]
**Description**

This follows a discussion on Zulip[1].

To generate the DDL for JPA and/or Panache entities, I can use the `schema-generation.scripts` properties in the `persistence.xml` file as follow:

```
<property name="javax.persistence.schema-generation.scripts.action" value="drop-and-create"/>
<property name="javax.persistence.schema-generation.scripts.create-target" value="create.ddl"/
<property name="javax.persistence.schema-generation.scripts.drop-target" value="drop.ddl"/>
```

This works well, but I am trying to avoid using the `persistence.xml` and only use the `application.properties` instead. I couldn't find these properties in the Quarkus documentation, so I tried several formats but none work:

```
javax.persistence.schema-generation.scripts.action=drop-and-create
quarkus.javax.persistence.schema-generation.scripts.action=drop-and-create
quarkus.hibernate-orm.schema-generation.scripts.action=drop-and-create
```

It looks like these properties are not exposed. It would be very nice to have them so we can get the DDL files without having the `persistence.xml`.

[1] https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Any.20way.20to.20have.20a.20scripts.2Ecreate-target.20property.20.3F

**Comment by Sanne** [comment]
something different than the existing `quarkus.hibernate-orm.database.generation` ?

- https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.generation

**Comment by agoncal** [comment]
The `quarkus.hibernate-orm.database.generation` is _equivalent_ to the standard JPA `javax.persistence.schema-generation.database.action` property. It has an impact on the schema generated in the database (`none, create, drop-and-create, drop`). 

The `javax.persistence.schema-generation.scripts.action` property (came later, I think in JPA 2.1) is about the schema definition. This property generates the DDL scripts, but does not generate the schema itself.

In fact, in JPA, you can have both properties to generate the database schema as well as the DDL script.

**Comment by Sanne** [comment]
Right, so you want it to also expose configuration options to generate the
create.sql and drop.sql ?

Wondering, should we maybe generate these always by default when running in
dev mode?

**Comment by agoncal** [comment]
As you know, there are several strategies when mapping objects to a DB. Existing DB, starting from scratch, entities first, DB first.... So I'm not sure generating the DDL out of the entities should be the default in dev mode. Would that mean that these values would be the default ?

```
javax.persistence.schema-generation.scripts.action=drop-and-create
javax.persistence.schema-generation.scripts.create-target=create.sql
javax.persistence.schema-generation.scripts.drop-target="drop.sql
```

Because in JPA, the default is `none`:

```
javax.persistence.schema-generation.scripts.action=none
javax.persistence.schema-generation.database.action=none
```

So, TBH, I prefer the good old JPA way (no DB schema generation, no DDL generation, and you have to change the values if needed).

Today, to get my DDL I need a `persistence.xml` (which is sad ;o). And to ease the DDL generation without starting Quarkus, I use this trick, using the JPA API:

```
public class GenerateDDL {

  public static void main(String[] args) {
    Persistence.generateSchema("<name of the persistence unit>", null);
    System.exit(0);
  }
}
```

**Comment by TomasHofman** [comment]
I'm going to take a look at this.
