### ISSUE TITLE
quarkus-oidc-token-propagation should also work with quarkus-smallrye-jwt

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#14798]
**Description**

The idea behind `quarkus-oidc-token-propagation` is simply to propagate the current access token (though we'd want to support a token exchange protocol in the future to make the audience/issue.etc management under control) - but it only currently works with `quarkus-oidc` which `quarkus-oidc-token-propagation` currently depends upon. However the bearer tokens verified with `quarkus-smallrye-jwt` should also be propagated if needed (in fact it should work for the OAuth2 extension as well).

**Comment by cortex93** [comment]
Seems weird to me that in the example `Client -> Service A -> Service B` you are actually giving the advice that `Service A` is able to to produce a new signed JWT and that `Service B` should actually trust `Service A` signature. Configuring `B` to trust both `Service A` public keys and an AS public keys is not possible for me as `smallrye.jwt.verify.key.location` accept only one jwks uri.

JWT should be emitted by a trusted Authorization Server. Thus, `Service A` should actually do a token exchange (see https://tools.ietf.org/html/rfc8693) if the scope/aud of the current token is not appropriate to call `Service B`.

Renaming the extension (breaking changes) would make it clearer that it works with OAuth2 Access Token and not only with OIDC (which is built on top of OAuth2 to bring Id token).

Apart from that, thanks for this merge request, it will simplify our own custom extension to request a token exchange.
