### ISSUE TITLE
Qute type-safe message bundles - use locale from the selected variant if "locale" attribute not set

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#14794]
Also document the usage of the "locale" attribute.

**Comment by FroMage** [comment]
So, for server-rendered stuff, the API I've used over the years does this:

- `static Locale I18N.get()`
- `static void I18N.set(Locale)`
- `static void I18N.set(String)`

`set` will set a session cookie to remember it, and `get` uses that, or defaults to the HTTP request headers to find a matching locale based on those supported in the config (say `fr,de,en`)

This makes it trivial to support a multi-language website with server rendering.

**Comment by mkouba** [comment]
@FroMage Seems reasonable. But it's something that should be implemented in the resteasy extension, right? And then we could easily change the `TemplateResponseFilter` to set the correct Qute attribute. For now, I will modify the `TemplateResponseFilter` to use the `Accept-Language` header...

**Comment by FroMage** [comment]
Yeah, probably, but it's going to be required, because the `Accept-Language` header is mostly useless for end users…

Thing is, I don't think we have that session storage cookie yet, but perhaps this is the right time to add it, WDYT @geoand ?

**Comment by geoand** [comment]
Indeed, no storage cookies yet, but yeah we should add them sooner rather than later :).
