### ISSUE TITLE
Add quarkus-smallrye-jwt-build as quarkus-smallrye-jwt dependency

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14803]
Add `quarkus-smallrye-jwt-build` as dependency of `quarkus-smallrye-jwt`

This is followup for https://github.com/quarkusio/quarkus/pull/13626 change to avoid need to explicitly add `quarkus-smallrye-jwt-build` dependency into pom.xml of existing applications which are using this API.

This way it will be transparent for existing users and new users can still select just `quarkus-smallrye-jwt-build`.

Docs should be also updated to include info that `quarkus-smallrye-jwt-build` can be excluded when users do not need that API in their application.

**Comment by sberyozkin** [comment]
@rsvoboda thank you, I agree, I suppose dropping it was too forceful at this stage and indeed some users did get caught by it because I also missed updating the migration guide.
So I'll put it back and will also update the docs.
I will open a new issue to drop in in Quarkus 2.0 :-)

**Comment by LuccaPrado** [comment]
Hey, we need just to update quarkus guides, as the [security jwt](https://quarkus.io/guides/security-jwt#maven-dependency) still referring to quarkus-smallrye-jwt-build
