### ISSUE TITLE
Having custom configurations

### ISSUE THREAD

**Issue by m-yassine1** [quarkusio/quarkus#14800]
**Describe the bug**
I am trying to create my own custom configuration with a dynamic value inside the key configuration. I am following the example shown [here](https://quarkus.io/guides/writing-extensions#configuration-example). I noticed that it does not have any annotation for it to initialize it.

**Expected behavior**
Have the configuration loaded inside the configurations injected automatically as stated in the example.

**Actual behavior**
The configurations are not getting injected into the configuration and the variable remains null.

**To Reproduce**
A sample project can be seen here.

[rest-json-quickstart.zip](https://github.com/quarkusio/quarkus/files/5919283/rest-json-quickstart.zip)
1. Run the project
2. Add a breakpoint to line 11 in MailService.java
3. Check that the attribute is null

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.mail.outlet-smtp-configuration."1".host=test.com
quarkus.mail.outlet-smtp-configuration."1".port=465
quarkus.mail.outlet-smtp-configuration."1".is-ssl=true
quarkus.mail.outlet-smtp-configuration."1".username=username
quarkus.mail.outlet-smtp-configuration."1".password=password

quarkus.mail.outlet-smtp-configuration."2".host=test.com
quarkus.mail.outlet-smtp-configuration."2".port=465
quarkus.mail.outlet-smtp-configuration."2".is-ssl=true
quarkus.mail.outlet-smtp-configuration."2".username=username
quarkus.mail.outlet-smtp-configuration."2".password=password

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/3103534/106765636-af024100-6641-11eb-9af1-16a9ba3d5de6.png)
![image](https://user-images.githubusercontent.com/3103534/106765723-c80af200-6641-11eb-8991-e4201b0a95fa.png)
![image](https://user-images.githubusercontent.com/3103534/106765802-dc4eef00-6641-11eb-8dbe-ef95383c6bc6.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.1457]
 - Output of `java -version`: 11.0.9
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
If there is any other way to have a dynamic value inside the key property, I would be happy to be linked so I may follow it.

**Comment by famod** [comment]
Are you actually implementing a Quarkus extension?
If not, you might want to check `@ConfigProperties`: https://quarkus.io/guides/config-reference#using_configproperties
But IIRC, there is some limitation regarding maps.
I'll hand this over to @radcortez and @geoand at this point. 😉

**Comment by radcortez** [comment]
This should work: https://smallrye.io/docs/smallrye-config/mapping/mapping.html

But yes, I also want to know if you are doing an extension or just a regular app.

**Comment by m-yassine1** [comment]
> Are you actually implementing a Quarkus extension?
> If not, you might want to check `@ConfigProperties`: https://quarkus.io/guides/config-reference#using_configproperties
> But IIRC, there is some limitation regarding maps.
> I'll hand this over to @radcortez and @geoand at this point. 😉

Actually no I am not, I thought that I can use the same annotation for my applications, and yes it has limitations for maps.

> This should work: https://smallrye.io/docs/smallrye-config/mapping/mapping.html
> 
> But yes, I also want to know if you are doing an extension or just a regular app.

I will try it, and I am doing a regular app.

**Comment by geoand** [comment]
> > Are you actually implementing a Quarkus extension?
> > If not, you might want to check `@ConfigProperties`: https://quarkus.io/guides/config-reference#using_configproperties
> > But IIRC, there is some limitation regarding maps.
> > I'll hand this over to @radcortez and @geoand at this point. wink
> 
> Actually no I am not, I thought that I can use the same annotation for my applications, and yes it has limitations for maps.

Was there something in the documentation that led you to believe you can use those annotations for application configuration?
If so, we need to fix it

**Comment by m-yassine1** [comment]
> > > Are you actually implementing a Quarkus extension?
> > > If not, you might want to check `@ConfigProperties`: https://quarkus.io/guides/config-reference#using_configproperties
> > > But IIRC, there is some limitation regarding maps.
> > > I'll hand this over to @radcortez and @geoand at this point. wink
> > 
> > 
> > Actually no I am not, I thought that I can use the same annotation for my applications, and yes it has limitations for maps.
> 
> Was there something in the documentation that led you to believe you can use those annotations for application configuration?
> If so, we need to fix it

I saw it as similar behavior to @ConfigProperties, and thought it might actually work regardless if it was meant for extensions only or not because it had the same prefix @Config.

I also want to note that I tried using [smallrye config](https://smallrye.io/docs/smallrye-config/mapping/mapping.html). I keep on getting class cast exception,

I have updated the project to accommodate the smallrye config: 
[rest-json-quickstart.zip](https://github.com/quarkusio/quarkus/files/5924131/rest-json-quickstart.zip)

The example is not straight forward as shown in their example, but I think I did as it should.

**Comment by radcortez** [comment]
Ops, unfortunately you hit https://github.com/smallrye/smallrye-config/pull/494.

I've tried you sample with that fix and it does work. I can do a release of SR Config and you override the dependency directly in you project so you don't have to way for the next Quarkus release.

**Comment by gsmet** [comment]
@radcortez if you can prepare a micro, 1.11.2 is not far away (things have to be merged there by Monday evening).

**Comment by radcortez** [comment]
Sure, I'll push a new update now. We only have that fix, so it is a very minimal update. Thanks!

**Comment by famod** [comment]
(Red) hats off to you @radcortez - swift support and fixing, as always! 🙂

**Comment by radcortez** [comment]
> (Red) hats off to you @radcortez - swift support and fixing, as always! 🙂

Thanks!

**Comment by m-yassine1** [comment]
> Ops, unfortunately you hit [smallrye/smallrye-config#494](https://github.com/smallrye/smallrye-config/pull/494).
> 
> I've tried your sample with that fix and it does work. I can do a release of SR Config and you override the dependency directly in you project so you don't have to way for the next Quarkus release.

Yes I can confirm that I tried the project again by removing the optional and updating the properties to: 
```
mail."1".host=test.com
mail."1".from=test.com
mail."1".tls-security-enabled=false
mail."1".port=465
mail."1".is-ssl=true
mail."1".username=username
mail."1".password=password

mail."2".host=test.com
mail."2".from=test.com
mail."2".tls-security-enabled=false
mail."2".port=465
mail."2".is-ssl=true
mail."2".username=username
mail."2".password=password
```
Still it is annoying since I have to specify all the properties. Nonetheless, thank you so much for the support and valiant effort!

> @radcortez if you can prepare a micro, 1.11.2 is not far away (things have to be merged there by Monday evening).

In version 1.11.2, will the optional work so I may update my application accordingly?

I want to also stress that is nice to have this https://quarkus.io/guides/writing-extensions#configuration-example on an application level and not just extensions.

**Comment by radcortez** [comment]
> In version 1.11.2, will the optional work so I may update my application accordingly?
> 

Yes. And you can do it right now, by overriding the `smallrye-config` version in your dependencies. Just use version `1.10.2`. 

> I want to also stress that is nice to have this https://quarkus.io/guides/writing-extensions#configuration-example on an application level and not just extensions.

Moving forward the recommended API, is the `@ConfigMapping` from SR Config. What are you missing in SR Config?

**Comment by m-yassine1** [comment]
> > In version 1.11.2, will the optional work so I may update my application accordingly?
> 
> Yes. And you can do it right now, by overriding the `smallrye-config` version in your dependencies. Just use version `1.10.2`.
> 
> > I want to also stress that is nice to have this https://quarkus.io/guides/writing-extensions#configuration-example on an application level and not just extensions.
> 
> Moving forward the recommended API, is the `@ConfigMapping` from SR Config. What are you missing in SR Config?

I am not missing anything and everything is working fine. I am just saying it would be nicer to use the Quarkus config annotation instead of the SR. Given the fact that in Intilj, it will create a shortcut for them inside the application.recourse file which can be accessed via ctrl+space. This can be seen in the screenshots I shared, they aren't highlighted as warnings as shown in the image:
![image](https://user-images.githubusercontent.com/3103534/107124352-1c190f00-68ac-11eb-9c61-81b51873adb4.png)

**Comment by radcortez** [comment]
Is this from the Quarkus plugin in IntelliJ?

**Comment by m-yassine1** [comment]
> Is this from the Quarkus plugin in IntelliJ?

I think so, for the Quarkus @ConfigRoot, they get highlighted nicely and are accessible via shortcuts.

**Comment by rquinio** [comment]
IDE support for microprofile-config in .properties files would be nice. 
But it'd require jars to ship with some standardized JSON metadata (similar to spring-boot-config metadata), otherwise every IDE plugin has to re-invent the wheel and scan annotations from any jar in classpath (cf implementation of current Quarkus editors, cf #5229).

**Comment by m-yassine1** [comment]
> IDE support for microprofile-config in .properties files would be nice.
> But it'd require jars to ship with some standardized JSON metadata (similar to spring-boot-config metadata), otherwise every IDE plugin has to re-invent the wheel and scan annotations from any jar in classpath (cf implementation of current Quarkus editors, cf #5229).

Deal. Again it is because I saw it done with the "write your own extension" configuration properties. If it is a hassle, I would understand. Thank you for your efforts as always!
