### ISSUE TITLE
Allow to use JSON-P without RESTEasy

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#1480]
We had issues to use JSON-P due to missing reflection configs. As I learned from @gsmet, the required config is contributed through the RESTEasy module, while our service doesn't use that (using JSON-P directly to deserialize JSON payloads received from Kafka).

**Comment by gsmet** [comment]
@gunnarmorling could you add some details about the API calls you make so that we can add the appropriate test cases?

**Comment by gunnarmorling** [comment]
@gsmet, you can see the original service here: https://github.com/debezium/debezium-examples/blob/master/outbox/shipment-service/src/main/java/io/debezium/examples/outbox/shipment/facade/OrderEventHandler.java#L42-L59 It's this usage and within the called `ShipmentService`.

**Comment by gsmet** [comment]
@gunnarmorling you will have `quarkus-jsonp`/`quarkus-jsonb` extensions in tomorrow's release.
