### ISSUE TITLE
Dependencies with duplicate files detected. The dependencies [org.jboss.logging:jboss-logging::jar:3.4.1.Final(compile), org.jboss.logging:jboss-logging-spi::jar:2.1.2.GA(compile)] contain duplicate files, e.g. org/jboss/logging/MDC.class

### ISSUE THREAD

**Issue by angelo-chan** [quarkusio/quarkus#14819]
**Describe the bug**
Dependencies with duplicate files detected. The dependencies [org.jboss.logging:jboss-logging::jar:3.4.1.Final(compile), org.jboss.logging:jboss-logging-spi::jar:2.1.2.GA(compile)] contain duplicate files, e.g. org/jboss/logging/MDC.class while building the uber jar while include commons-logging and jdk log adaptors in the application:

**To Reproduce**

1. add below log adaptors to project

```
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>commons-logging-jboss-logging</artifactId>
</dependency>
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging-jdk</artifactId>
</dependency>
```

2. build the uber jar: 

`./mvnw clean package -Dquarkus.package.type=uber-jar`

**Additional context**
common-logging-jboss-logging depends on org.jboss.logging:jboss-logging::jar:3.4.1.Final but 
jboss-logging-jdk depends on org.jboss.logging:jboss-logging-spi::jar:2.1.2.GA those 2 have duplicate class  e.g. org/jboss/logging/MDC.class

**Comment by jamezp** [comment]
Where do the `jboss-logging-jdk` and `jboss-logging-spi` dependencies come from? I'm not seeing either under the jboss-logging organization https://github.com/jboss-logging.

**Comment by jamezp** [comment]
It looks like that came in via https://github.com/quarkusio/quarkus/commit/441742ebbf8d270c7464e134ee44c62c02c8b185. I'm not sure that is right. That is a very old dependency released over 10 years ago now. I only see a reference to that `org.jboss.logging:jboss-logging-jdk` in the `bom/application/pom.xml` and a reference in the documentation. I think it should be removed as a dependency.

**Comment by angelo-chan** [comment]
this also comes from the quarkus logging guide:

![image](https://user-images.githubusercontent.com/8653839/107134867-d3576980-6930-11eb-8079-b7d7d73888bc.png)

**Comment by jamezp** [comment]
Yes. I'm not really sure why that was added. I don't think that dependency should be used at all, but we may want to ask @dmlloyd if there was a reason this dependency was added. Maybe it was mistaken for another logging dependency because we have several :)

**Comment by dmlloyd** [comment]
Yeah that's definitely a documentation error.  That dependency should never be added to a Quarkus application!
