### ISSUE TITLE
Generated Openshift manifest contains malformed value of app.openshift.io/vcs-url and app.quarkus.io/vcs-url annotations

### ISSUE THREAD

**Issue by mkonzal** [quarkusio/quarkus#14827]
**Describe the bug**
Openshift manifest generated by the Quarkus 1.11.1 contains malformed url of the git repo when ssh is used.

**Expected behavior**
Openshift manifest generated by the Quarkus contains value provided by git like `ssh://git@fqhn:port/path/repo.git`

**Actual behavior**
Actual value in the generated manifest `https://fqhn/port/path/repo.git`

**To Reproduce**

`mvn clean package` on a Quarkus project where the remote repo is accessed over ssh then check the generated Openshift Manifests in `target/kubernetes/openshift.[yml|json]`

Result of git remote -v
```
git remote -v
origin  ssh://git@hostname.subdomain.domain.tld:7999/path/repo-name.git (fetch)
origin  ssh://git@hostname.subdomain.domain.tld:7999/path/repo-name.git (push)
upstream        ssh://git@hostname.subdomain.domain.tld:7999/path/repo-name.git (fetch)
upstream        ssh://git@hostname.subdomain.domain.tld:7999/path/repo-name.git (push)
```

**Configuration**
```properties
config_suffix=-t

quarkus.application.name=application-name${config_suffix}

quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.env.configmaps=config-map${config_suffix}
quarkus.openshift.env.secrets=truststore-password,keystore-passwords
quarkus.openshift.mounts.keystore.path=/mnt/keystore
quarkus.openshift.mounts.truststore.path=/mnt/truststore
quarkus.openshift.secret-volumes.truststore.secret-name=some-truststore
quarkus.openshift.secret-volumes.keystore.secret-name=keystore
quarkus.openshift.service-account=default

quarkus.openshift.resources.requests.memory=100Mi
quarkus.openshift.resources.requests.cpu=50m
quarkus.openshift.resources.limits.memory=250Mi
quarkus.openshift.resources.limits.cpu=100m
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: OS name: "linux", version: "3.10.0-1160.11.1.el7.x86_64", arch: "amd64", family: "unix"
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 LTS
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.11.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
 - git version: git version 1.8.3.1

**Comment by geoand** [comment]
cc @iocanel @FroMage

**Comment by FroMage** [comment]
Sorry @iocanel this one's for you ;)

**Comment by iocanel** [comment]
@mkonzal:  The git url that is used, is converted to https if posssible, for compatibility related reasons, anonymous access etc, which I think that it does make sense when it comes to using git via tooling. 

To provide the best possible solution, I'd like to understand a little bit better your use case and how using `https` is causing issues for you. 

Thanks in advance!

**Comment by iocanel** [comment]
@mkonzal: behavior changed so urls are no longer sanitized. If user needs sanitization, then that should happen locally as part of git configuration.
