### ISSUE TITLE
Postgres TestContainer fails with "No suitable driver found" when switching test profiles

### ISSUE THREAD

**Issue by patrick-vonsteht** [quarkusio/quarkus#14829]
**Describe the bug**
Setup:
* You have two QuarkusTests
* **The QuarkusTests use different TestProfiles.**
* Both QuarkusTests start a postgres container through a QuarkusTestResourceLifecycleManager.

**Expected behavior**
Expected Result:
* Both tests run successfully.

**Actual behavior**
Result:
* The first test runs successfully.
* The second test, after the profile switch, fails with "java.sql.SQLException: No suitable driver found for <SOME_JDBC_URL>"

**To Reproduce**

See minimal example at https://github.com/patrick-vonsteht/quarkus-test-containers-test-profiles-switch-bug

1. Run "mvn test" in the reproducer.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19042.746]
 - Output of `java -version`: openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)

**Additional context**
A similar issue has been fixed here: https://github.com/quarkusio/quarkus/issues/12116

**Comment by geoand** [comment]
I'll take a look next week

**Comment by geoand** [comment]
Seems similar to https://github.com/quarkusio/quarkus/issues/12116

**Comment by matjazs** [comment]
I have only recently updated our Quarkus dependencies and found out that loading postgresql driver parent-first, causes our previously working, Postgis related, @QuarkusTest-annotated tests to fail.

Our test methods are failing when comparing:
- instances of `org.postgis.PGgeometry` loaded from database within the same test method using the JDBC ResultSet and the injected Agroal data source, to
- equal instances of `org.postgis.PGgeometry` instantiated within the same test method using a constructor.

PGgeometry comes from the net.postgis:postgis-jdbc:2.5.0 which is a PostGIS JDBC Driver extension.

The assertion errors look like:

```
java.lang.AssertionError:
Expecting:
  <...some org.postgis.PGgeometry instance...>
to be of class
  <org.postgis.PGgeometry>
but was of class
  <org.postgis.PGgeometry>
```

The actual difference are the class loaders being used to load the org.postgis.PGgeometry class:
- the class loader referenced in `org.postgresql.jdbc.PgConnection` (JDBC connection obtained in test methods from the injected AgroalDataSource) is: `ClassLoaders$AppClassLoader`
- the class loader used in test method thread is: `QuarkusClassLoader:Quarkus Base Runtime ClassLoader`

PgConnection has a type cache, containing the `PG type name` to `Java class` mappings. This type cache is used in `PgConnection#getObject()` for constructing `org.postgis.PGgeometry` instances when reading the data from ResultSets in our test methods. In our case the `Java classes` for the mappings are loaded with the ClassLoaders$AppClassLoader, resulting in a class loader mismatch when comparing them to PGgeometry instances created in the same test methods using a constructor.

We also use the Quarkus Flyway extension which causes to create a database connection prior to running the tests.

Is such behaviour anticipated and should we refactor our tests, or might this actually be a an issue? The tests work if I remove the `parentFirstArtifacts` configuration from `extensions/jdbc/jdbc-postgresql/runtime/pom.xml`. I can provide a reproducer if needed.
