### ISSUE TITLE
Smallrye Health extension doesn't work in native

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#1482]
Generating project without REST endpoint:

```
mvn io.quarkus:quarkus-maven-plugin:0.11.0:create \
    -DprojectGroupId=io.xstefank \
    -DprojectArtifactId=health-test
```

and adding smallrye-health:

```
mvn quarkus:add-extension -Dextensions="smallrye-health"
```

Compiling to native and then accessing /health results in:

java.lang.InstantiationException: Type `org.glassfish.json.JsonProviderImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.

full stacktrace: https://pastebin.com/eupq0e5n

This class is added for reflective access only in [ResteasyJsonbProcessor](https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-jsonb/deployment/src/main/java/io/quarkus/resteasy/jsonb/deployment/ResteasyJsonbProcessor.java#L35) however smallrye-health uses JSON-P in [SmallRyeHealthReporter](https://github.com/smallrye/smallrye-health/blob/master/implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java#L118).

I believe that smallrye-health extension should also register "org.glassfish.json.JsonProviderImp" for reflective access.

**Comment by gsmet** [comment]
OK, this goes in parallel to https://github.com/quarkusio/quarkus/issues/1480 .

I think we will need some low level JSON-B/JSON-P library setting everything up and added as a dependency for everyone that needs it.

**Comment by xstefank** [comment]
@gsmet ok, thanks, I will leave it then to you

**Comment by gsmet** [comment]
It should be fixed in tomorrow's release.
