### ISSUE TITLE
ArC - make it possible to turn an annotation into a qualifier without adding @Qualifier to it

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#14822]
I.e. add an alternative to `BeforeBeanDiscovery.addQualifier()`

**Comment by manovotn** [comment]
CC @Ladicek since we talked about Quarkus not having this recently in context of Lite :-)

**Comment by Ladicek** [comment]
There's a couple more (`addStereotype`, `addInterceptorBinding`), do we already have [an equivalent of] those?

**Comment by manovotn** [comment]
We do have `InterceptorBindingRegistrarBuildItem` already.
But I don't think we have anything like this for stereotypes.

**Comment by Ladicek** [comment]
Thanks!

**Comment by Ladicek** [comment]
BTW is this urgent and needs to be done soon, or just an idea? If the latter, I'd volunteer to take a look.

**Comment by manovotn** [comment]
IIUIC, @mkouba needs this for some Qute work. But do check with him.

**Comment by Ladicek** [comment]
Gotcha, thanks. Leaving this to @mkouba then :-)
