### ISSUE TITLE
Error in DockerFile.multistage Gradle script on quarkus.io Documentation

### ISSUE THREAD

**Issue by bfontana** [quarkusio/quarkus#14835]
**Describe the bug**
**The Gradle script** showing how to build a native image with **DockerFile.multistage** has a typo and it **doesn'twork**. Please see below. The "Expected Behavior" is the one fixed. 

**Expected behavior**
.....

Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/**build/target/*-runner** /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

**Actual behavior**
...

Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/**build/*-runner** /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

**Comment by glefloch** [comment]
Thanks @bfontana. I will take care of this one.

**Comment by glefloch** [comment]
Actually the Dockerfile seems to be correct, the gradle task outputs the runner binary in the `build/` directory. Can you try running `./gradlew clean quarkusBuild -Dquarkus.package.type=native` to validate that the binary is generated in the `build/` directory?

**Comment by glefloch** [comment]
@bfontana were you able to test it again?

**Comment by bfontana** [comment]
@glefloch, sorry for the delay. I missed this notification. I'll test it tomorrow and we'll see.

**Comment by glefloch** [comment]
@bfontana were you able to test it?

**Comment by bfontana** [comment]
@glefloch, I tested again and it worked like a charm. Thanks for your help.

**Comment by glefloch** [comment]
Great, thanks for the feedback.  I close the issue then.
