### ISSUE TITLE
Generated Openshift manifest contains cp argument with all dependencies when uber-jar packaging is used

### ISSUE THREAD

**Issue by mkonzal** [quarkusio/quarkus#14844]
**Describe the bug**
When uber-jar packaging is selected then the generated openshift manifest contains in the cp argument list of nonexisting files `/deployments/lib/*` like in the legacy-jar packaging case.

**Expected behavior**
cp argument with list of dependencies is not part of the arguments when uber-jar packaging is active.

**To Reproduce**
'mvn clean package` on a Quarkus project where uber-jar packaking is selected then check the generated Openshift Manifests in target/kubernetes/openshift.(yml|json).

**Configuration**
```properties
config_suffix=-t

quarkus.package.type=uber-jar

quarkus.application.name=application-name${config_suffix}

quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.env.configmaps=config-map${config_suffix}
quarkus.openshift.env.secrets=truststore-password,keystore-passwords
quarkus.openshift.mounts.keystore.path=/mnt/keystore
quarkus.openshift.mounts.truststore.path=/mnt/truststore
quarkus.openshift.secret-volumes.truststore.secret-name=some-truststore
quarkus.openshift.secret-volumes.keystore.secret-name=keystore
quarkus.openshift.service-account=default

quarkus.openshift.resources.requests.memory=100Mi
quarkus.openshift.resources.requests.cpu=50m
quarkus.openshift.resources.limits.memory=250Mi
quarkus.openshift.resources.limits.cpu=100m
```

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 LTS
 - Quarkus version or git rev: 1.11.1, 1.10.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
@iocanel I don't even see where `-cp` comes from. Can you take a look at this?

**Comment by iocanel** [comment]
I think its added expliclitly. Let me see if we can make it work without it.
