### ISSUE TITLE
Support quarkus:dev in multimodule projects

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1484]
It would be nice if `quarkus:dev` supported multimodule projects (eg. a change in a class from a module triggers a redeployment)

**Comment by emmanuelbernard** [comment]
Stuart, I assigned it for evaluation, not to do it necessarily.

**Comment by aloubyansky** [comment]
I think it'll be easier once the bootstrap stuff is in. As it already has the notion and discovery of a workspace.

**Comment by gastaldi** [comment]
Not sure if it helps, but JRebel uses a [rebel.xml](https://manuals.zeroturnaround.com/jrebel/standalone/config.html#jar-configuration) on each JAR to find out where the compiled classes are - maybe a similar approach would be interesting

**Comment by stuartwdouglas** [comment]
I think this is relatively easy to do, although it would require running quarkus:dev from the top level project. It will likely conflict with the bootstrap work though so I will hold off on this until it is in.
