### ISSUE TITLE
Resteasy Reactive Security Context Exception

### ISSUE THREAD

**Issue by akoufa** [quarkusio/quarkus#14850]
Hello. I am trying to update the security context in a RequestFilter like this:
`context.securityContext = GatewaySecurityContext(context.securityContext, principalDetails) `. 

This is working with RestEasy Classic. Unfortunately using RestEasy Reactive I am getting the following error:
 ```
io.quarkus.resteasy.reactive.server.runtime.security.SecurityContextOverrideHandler.updateIdentity(SecurityContextOverrideHandler.java:48)
```

The issue is that in the following code

```
Uni<SecurityIdentity> oldIdentity = currentIdentityAssociation.getDeferredIdentity();
        currentIdentityAssociation.setIdentity(oldIdentity.map(new Function<SecurityIdentity, SecurityIdentity>() {
```
**oldIdentity** is **null** in the `SecurityContextOverrideHandler` class.

Is there anything I need to be aware of or am I doing something wrong here ?

**Comment by CurtisBaldwinson** [comment]
`.getDeferredIdentity()` is asynchronous so when you're calling `oldIdentity.map` it hasn't received a value yet. You'll want to react when the value is returned:

```
        currentIdentityAssociation.getDeferredIdentity()
                .call(currentIdentity -> currentIdentityAssociation.setIdentity(oldIdentity.map(new Function<SecurityIdentity, SecurityIdentity>() {
```

**Comment by stuartwdouglas** [comment]
Do you have a reproducer, or can you include the stack trace of the actual error?

I fixed something in the Servlet support around this, however it is likely slightly different.
