### ISSUE TITLE
[Quarkus Artemis] Support transaction manager integration

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#14871]
**Description**
Currently it does not work in the JTA XA transaction. So I'd like to integrate with the Transaction Manager, especially from the narayana-jta extension.

**Implementation ideas**
Some ideas are from Argroal extesion to set the transaction integration type with

- ENABLED (integration with JTA TransactionManager of Quarkus and enlist in the XA transaction automatically)
- DISABLED (ActiveMQ will control the transaction itself)

It could leverage the [Narayana JMS](https://github.com/jbosstm/narayana/tree/master/ArjunaJTA/jms) which wraps the XAConnectionFactory to provide the capabilities.

**Comment by zhfeng** [comment]
The Narayana JMS only supports JMS 1.1 right now. I'm investigating that if it is possible to support JMS 2.0.

**Comment by zhfeng** [comment]
[JBTM-3429](https://issues.redhat.com/browse/JBTM-3429) is raised to track the work for JMS 2.0 support in Narayana

**Comment by zhfeng** [comment]
[messaginghub](https://github.com/messaginghub/pooled-jms) could be an another option to support the transaction manager integration.

**Comment by fvaleri** [comment]
@zhfeng the messaginghub approach is what I used for this Camel-SB example, maybe it helps.

https://github.com/apache/camel-spring-boot-examples/tree/main/spring-boot-jta-jpa

**Comment by jochenr** [comment]
hello @fvaleri ,

I tried to use you messaginghub approach to implement a workaround for the camel-jms component on Quarkus:
https://github.com/jochenr/camel-quarkus-example/blob/messaginghub.org/src/main/java/de/jochenr/camelquarkusexample/jms/JmsComponentProducer.java

It seems to work.😃

**Comment by fvaleri** [comment]
@jochenr this is great. 

Thanks for sharing :)

**Comment by zhfeng** [comment]
Currently you can use `quarkus-artemis` and `quarkus-pooled-jms` together and enable `quarkus.pooled-jms.xa.enabled=true` to get the XA transaction support. A camel-quarkus jta-jpa could be found on https://github.com/apache/camel-quarkus-examples/tree/camel-quarkus-main/jta-jpa.

**Comment by mmusgrov** [comment]
@zhfeng I'm trying to track down which release this issue was fixed it, do you know?
