### ISSUE TITLE
Dev UI - display better error messages instead of `NOT_FOUND` in Qute templates

### ISSUE THREAD

**Issue by SaumyaSingh1** [quarkusio/quarkus#14872]
**Description**
I am working on endpoints page in RESTEasy Reactive extension. I am inserting expression values in my template, most of the times I get `RESOURCES_NOT_FOUND` or `NOT_FOUND`. That means I am looking at fields that don't exist.

I think that an error message that included which part was null would help me a lot, more than RESOURCES_NOT_FOUND :)

![image](https://user-images.githubusercontent.com/46818757/107110128-734abf80-686b-11eb-99d4-6b0c9690ae3d.png)

Thanks

**Comment by mkouba** [comment]
Hi @SaumyaSingh1, it's definitely possible. The "regular" qute users can control this behavior via the `quarkus.qute.property-not-found-strategy` config property but can add a custom result mapper in the Dev UI. What behavior would you prefer?

**Comment by SaumyaSingh1** [comment]
ok great, basically instead of that `NOT_FOUND` , I want proper error message like what excatly is empty , hints ..
For this pusrpose do I need to implement `TemplateException` ?

**Comment by mkouba** [comment]
> ok great, basically instead of that `NOT_FOUND` , I want proper error message like what excatly is empty , hints ..

Hm, I don't think we would be able to print what's exactly empty. We could print the original expression tag, e.g. `{resource.path}`, the template, line, line char start/end but we don't have any other context information available inside a result mapper. We could catch the exception thrown during rendering and output the data passed to the template.

**Comment by gsmet** [comment]
TBH, I think we should trigger an exception by default. I don't see any case where you would like to end up with a NOT_FOUND when pushing to production.

**Comment by SaumyaSingh1** [comment]
oh for me this problem was fixed weeks ago :)
Debugging helped!

**Comment by mkouba** [comment]
Ok, so I think that we could use a result mapper that throws an exception with some minimal info.
