### ISSUE TITLE
@Blocking annotation not working with @RestForm parameters

### ISSUE THREAD

**Issue by indalaterre** [quarkusio/quarkus#14875]
Hi,
I found this strange behavior. In my app I've annotated my Application class with @Blocking annotation since I'm not using yet Hibernate Reactive. 
The queries are performed so everything goes well.

I than added a new endpoint with some @RestForm attributes and I had this errror
`java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
`

which means that the @Blocking annotation is not working.
I tried also to add the annotation directly on the method but the result was the same.

Than I removed the form parameters and for testing purpose added them as path parameters and the query was performed.

This is my endpoint

**IO THREAD ERROR**
` @POST
  @PermitAll
  @Blocking
  @Consumes(MULTIPART_FORM_DATA)
  @Produces(APPLICATION_JSON)
  public Uni<Response> generateToken(@RestForm String username, @RestForm String password) {
    return this.userService.authenticate(username, password)
        .map(response -> Response.ok().entity(response).build());
  }`

**NO ERRORS**
`  @POST
  @Path("/{username}/{password}")
  @PermitAll
  @Blocking
  @Consumes(TEXT_PLAIN)
  @Produces(APPLICATION_JSON)
  public Uni<Response> generateToken(String username, String password) {
    return this.userService.authenticate(username, password)
        .map(response -> Response.ok().entity(response).build());
  }`

Currently I'm using v1.11.1

Am I doing something wrong? 
Thank you very much

**Comment by gsmet** [comment]
@indalaterre any chance you could provide a small reproducer?

/cc @geoand

**Comment by geoand** [comment]
I am pretty sure that the first commit from #14852 takes care of the issue

**Comment by indalaterre** [comment]
Hi, thanks for the response.
This is the demo project and a stack trace of the problem
[demo.zip](https://github.com/quarkusio/quarkus/files/5937650/demo.zip)
[stacktrace.txt](https://github.com/quarkusio/quarkus/files/5937651/stacktrace.txt)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14880 takes care of the issue
