### ISSUE TITLE
Quarkus native images will not run in AWS

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1487]
Substrate VM uses named semaphores as a concurrency control primitive in its C helper for signal handling.  This means that our native images will fail to start in that environment.

I suggested to use unnamed semaphores but these are not supported on Darwin.  Another idea is to use pthread mutexes or similar.

To workaround we'd have to rip out our signal handlers and also disable the couple of signal handlers that Substrate introduces.  We might want a build option to do this.

**Comment by dmlloyd** [comment]
See also: https://github.com/oracle/graal/issues/841 https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.native.libchelper/src/cSunMiscSignal.c#L113

**Comment by drissamri** [comment]
Since that issue is fixed, is there any chance AWS Lambda support will happen soon @dmlloyd?

**Comment by dmlloyd** [comment]
Once GraalVM RC15 is released, then that should solve this.  But I think @evanchooly has AWS Lambda more or less functional at this point either way.

**Comment by drissamri** [comment]
Any idea where I can find the working example? I'd like to demo this at our company asap to get people experimenting 👍

**Comment by evanchooly** [comment]
I have a working implementation.  I filed PR #1822 today.  There's an unexpected failing test in there I'll have to track down tomorrow morning.  I have a working example in a git repo on my drive.  I'll clean it up and push it to github tomorrow.

**Comment by gsmet** [comment]
I think this has been fixed already.
