### ISSUE TITLE
Native image build fail if quarkus-resteasy-reactive and quarkus-smallrye-opentracing are used.

### ISSUE THREAD

**Issue by taf-team-aki** [quarkusio/quarkus#14876]
**Describe the bug**
If quarkus-resteasy-reactive and quarkus-smallrye-opentracing are used in the same project the native image build fails.

**Expected behavior**
Native image will be created.

**Actual behavior**
Build process interrupts with 
```
Fatal error:java.lang.TypeNotPresentException: Type org.jboss.resteasy.microprofile.config.FilterConfigSource not present
        at java.base/sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:46)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
```

**To Reproduce**

1. Create a simple quarkus project
   mvn io.quarkus:quarkus-maven-plugin:1.11.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
2. Replace artifact quarkus-resteasy by quarkus-resteasy-reactive in pom.xml
3. Add artifact quarkus-smallrye-opentracing to pom.xml
4. Execute command mvn clean verify -Pnative

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   Linux jojo-020 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
   openjdk version "11.0.9" 2020-10-20
   OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
   OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.9, vendor: GraalVM Community, runtime: /usr/lib/jvm/graalvm-ce-java11-20.3.0
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-65-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/14882 fixes the issue
