### ISSUE TITLE
Error trying to fetch image in Openshift Serverless

### ISSUE THREAD

**Issue by lferna** [quarkusio/quarkus#14884]
**Describe the bug**
Deploying a Quarkus image on Openshift Serverless raises next error:
`Unable to fetch image "<session_user>/openshift-quickstart:1.0.0-SNAPSHOT" UNAUTHORIZED: authentication required;`

Added the following properties to my application.properties

```
quarkus.kubernetes.deployment-target=knative
quarkus.container-image.username=myuser
quarkus.container-image.password=mypass
```
And run: `/mvnw clean package -Dquarkus.kubernetes.deploy=true`

But the user that uses to fetch the image is different (session user)

**Expected behavior**
Image should be fetched with the username of the application.properties

**Actual behavior**
Fails with 401 error. UNAUTHORIZED: authentication required

**To Reproduce**

```
mvn io.quarkus:quarkus-maven-plugin:1.11.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=openshift-quickstart \
    -DclassName="org.acme.rest.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions="resteasy,openshift"

```
Set application.properties and then run:

`/mvnw clean package -Dquarkus.kubernetes.deploy=true`

**Configuration**
```
quarkus.kubernetes.deployment-target=knative
quarkus.container-image.username=myuser
quarkus.container-image.password=mypass
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4258187/107145668-8761f000-6943-11eb-908d-3d41165f21cc.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux crdhost 4.19.0-14-cloud-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
 - Output of `java -version`:  openjdk version "11.0.9.1" 2020-11-04
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.1.FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by geoand** [comment]
cc @iocanel

**Comment by lferna** [comment]
Adding this property:
`quarkus.container-image.group=lferna`

The error disappears but the image can't be found:

`Unable to fetch image "lferna/openshift-quickstart:1.0.0-SNAPSHOT": failed to resolve image to digest: failed to fetch image information: GET https://index.docker.io/v2/lferna/openshift-quickstart/manifests/1.0.0-SNAPSHOT: MANIFEST_UNKNOWN: manifest unknown; map[Tag:1.0.0-SNAPSHOT]
`

**Comment by iocanel** [comment]
I have some tests attend for that particular setup! I'll have a look and see if it's a regression or something

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
