### ISSUE TITLE
Export invocation order 

### ISSUE THREAD

**Issue by tobiasstadler** [quarkusio/quarkus#14885]
**Description**
I would like see which filters/interceptors in which order are run on a particular JAX-RS resource/CDI bean. Ideally the invocation order can be exported during the (maven) build.

**Implementation ideas**

**Comment by famod** [comment]
This sounds like a nice addition to Dev UI? 🤔 /cc @geoand @gsmet

**Comment by geoand** [comment]
That's a great idea indeed!

It should be easy to implement if someone wants to take it up - otherwise I'll get to it sometime (hopefully soon)

**Comment by geoand** [comment]
@FroMage is this something you think that @SaumyaSingh1 can lool into?

**Comment by FroMage** [comment]
Indeed, sounds like a good idea!

**Comment by SaumyaSingh1** [comment]
Sure, would love to work on it :)

**Comment by geoand** [comment]
This is especially useful for Filters that use `@NameBinding`

**Comment by FroMage** [comment]
@SaumyaSingh1 you can find the info about response/request filters in `ResourceInterceptorsBuildItem`, so that should be enough to create a new DEV UI page to display that info if you expose it from `DevConsoleProcessor`. Do you need more guidance or is it enough to get started?

**Comment by SaumyaSingh1** [comment]
> @SaumyaSingh1 you can find the info about response/request filters in `ResourceInterceptorsBuildItem`, so that should be enough to create a new DEV UI page to display that info if you expose it from `DevConsoleProcessor`. Do you need more guidance or is it enough to get started?

Sure

**Comment by FroMage** [comment]
Isn't this fixed @geoand ?

**Comment by geoand** [comment]
Ah darn... The PR didn't close the issue automatically :(

**Comment by geoand** [comment]
Fixed by #15237

**Comment by tobiasstadler** [comment]
Thank You!
