### ISSUE TITLE
@Transactional does not work with reactive rest/panache

### ISSUE THREAD

**Issue by zemiak** [quarkusio/quarkus#14883]
**Describe the bug**
When I annotate a `@POST` (or whatever) method/rest class as ```@Transactional```, I expect transactions to work.

**Expected behavior**
Method should start a transaction before entering and closing it (doing DB commit) afterwards.

**Actual behavior**
Unless I close the code in Panache.withTransaction, the persisting does not work.

**To Reproduce**
https://github.com/zemiak/reactive-fruits-panache

Or attach an archive containing the reproducer to the issue.

1. mark a REST class as `@Transactional`
2. persist an entity - `@POST public void create(Entity entity) { entity.persist(); }`
3. the entity will not persist and there is no exception/warning

**Configuration**
Standard local PGSQL. Extensions: reactive resteasy, pgsql, hibernate and panache.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin xxx 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `openjdk version "11.0.6" 2020-01-14`
 - Quarkus version or git rev: `1.11.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /Users/vasko/bin/maven
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_SK, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

**Additional context**
I know, that .withTransaction works, but this is contra-intuitive and not playing well with "we will deliver reactive experience with standard APIs".

**Comment by FroMage** [comment]
For the moment, we've decided to make transaction demarcation explicit and not support the annotation when using Hibernate Reactive. We may reevaluate this in the future.

CC @Sanne @gavinking

**Comment by zemiak** [comment]
@FroMage I kinda disagree. 

In non-reactive world, I use `@Transactional` for both Panache and Hibernate and it is both standardised and pretty explicit - class or method scoped - and working for both.

In reactive Hibernate, I have to inject a Mutiny.Session and I do not have to encapsulate the code in a transaction.
In reactive Panache, I have to use Panache.withTransaction around the code.

This is totally different to the "classic" code and and between reactive Panache and Hibernate as well.

**Comment by FroMage** [comment]
Well, sure, it would be nice, but this is a Hibernate Reactive feature that is not implemented ATM, so the Panache layer can't use it until it lands. If it lands, we're still experimenting.

**Comment by gavinking** [comment]
Well it's not that we decided not to support it; it's just that it would be a whole separate implementation of `@Transactional` (in Quarkus, not HR) because there's no integration between the reactive database client and the TM.

**Comment by jiayaoO3O** [comment]
I had the exact same problem, until I read this issue, I didn't know that I had to use **Panache.withTransaction()**, which I think is very important information and should be explained in the **guides**

**Comment by jiayaoO3O** [comment]
Hi @FroMage ,
I would like to ask a question, when I use **@Transactional**, I tend to add **@Transactional** annotation in the **service layer** of the application, where there are many methods in a service, and when these methods throw an exception, **the whole transaction is rolled back**. But when I use **quarkus-hibernate-reactive-panache**, I find that I have to use **Panache.withTransaction()**, _so should I wrap the entire service method with Panache.withTransaction() to achieve the original functionality_?

**Comment by FroMage** [comment]
Yes.

**Comment by romainshen** [comment]
you can use @ReactiveTransactional, which is the reactive variant of @Transactional
