### ISSUE TITLE
MicroMeter extension: JSONExporter issue with "NaN" values

### ISSUE THREAD

**Issue by flobjective** [quarkusio/quarkus#14887]
**Describe the bug**
The JSON-Exporter for the micrometer metrics throws a NumberFormatException when a Gauge that is based on weak reference returns "NaN".
According to https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing a Gauge's value can get garbage-collected if it's not using a strong-reference. This happened to me for the Gauge "system.cpu.usage" which leads the JSON-Exporter to serialize "NaN.
There is a check for NaN-values in `JsonExporter`: 
`https://github.com/quarkusio/quarkus/blob/95602076fa89d89e0db6c00709e07a0b9cc28530/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/registry/json/JsonExporter.java#L91`
Unfortunately that check does not work here as one line lower the Gauges' value is queried again resulting in a different value ('NaN').

**Expected behavior**
The JSON-Exporter should filter out `NaN`-double values.

**Actual behavior**
The JSON-Exporter tries to use a `NaN` value leading to a NumberFormatException.

**To Reproduce**
I did create a small repo with a test that fails: https://github.com/flobjective/Quarkus-Metrics-JSON-Nan

1) Run the test `GreetingResourceTest:prometheus_metrics_in_json_should_be_available` using `./mvnw test`

Alternative:

1) Run `./mvnw quarkus:dev`
2) Run curl from a shell `curl http://localhost:8080/q/metrics -H "Accept:application/json"`
3) Repeat the curl a few times (I only 1-2 runs locally)

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.micrometer.export.json.enabled=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 ```
 Darwin machinename 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
 ```
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
```
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: `1.11.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
Maven home:  /Users/florianfritzsche/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

**Comment by ebullient** [comment]
This should be fixed in #14750 (see 241c6367c2c5493c819e30f146fdb409be8407ee)
