### ISSUE TITLE
Unable to build docker image. Please check your docker installation

### ISSUE THREAD

**Issue by kiziltas** [quarkusio/quarkus#14892]
**Describe the bug**
mvn clean install fails with a docker related exception unexpectedly.

**Expected behavior**
Successful build when everything is set and up.

**Actual behavior**
An error occurs with the message `Unable to build docker image. Please check your docker installation`

```
[WARNING] [io.quarkus.container.image.docker.deployment.DockerWorking] No Docker binary found
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.5.Final:build (default) on project ***-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Unable to build docker image. Please check your docker installation
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:78)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**To Reproduce**
No reproducton

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin localhost 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw 0.5.6

I'm running on Docker for Mac 2.4.0

**Comment by famod** [comment]
I suppose when you type `docker -v` you get a proper output (no error)?

**Comment by kiziltas** [comment]
Indeed no error. 

`Docker version 19.03.13, build 4484c46d9d`

I can use docker with other applications with no visible issues.

**Comment by famod** [comment]
So I guess there is a special error case being swallowed here: https://github.com/quarkusio/quarkus/blob/1.10.5.Final/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerWorking.java#L41-L43
/cc @geoand 

@kiziltas If I would provide a branch with more diagnostic ouput, would you be able to build Quarkus locally?
E.g. https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#building-master but with a branch I would yet have to create.

**Comment by famod** [comment]
Or, you could try do debug yourself and check what `Exception e` is exactly in your case.

**Comment by geoand** [comment]
> So I guess there is a special error case being swallowed here: https://github.com/quarkusio/quarkus/blob/1.10.5.Final/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerWorking.java#L27-L29 (_edit: wrong link corrected_)
> /cc @geoand
> 

Yeah, we should probably at least print the exception message.

**Comment by famod** [comment]
@kiziltas So in case you want to try building Quarkus locally to get more output for your case:
- `git clone https://github.com/famod/quarkus.git`
  (my fork of Quarkus)
- `cd quarkus`
- `git switch docker-setup-check-logging`
  (see also: https://github.com/quarkusio/quarkus/compare/master...famod:docker-setup-check-logging)
- `export MAVEN_OPTS="-Xmx1563m"`
- `./mvnw -Dquickly`

And then in your project switch the Quarkus version from `1.10.5.Final` to `999-SNAPSHOT` and try to build the docker image via Quarkus.
In case you are using `quarkus-universe-bom` you need to change that to `quarkus-bom`.

**Comment by famod** [comment]
@kiziltas You could now also try 1.12.0.CR1.

**Comment by gsmet** [comment]
If you use 1.12.0.CR1, be sure to use the `quarkus-bom` and not the `quarkus-universe-bom`!

**Comment by gsmet** [comment]
@kiziltas any news?

**Comment by kiziltas** [comment]
Sorry for late response. I've managed to fix this by myself (can't remember right now, but was most likely workspace related), so this can be closed.

**Comment by geoand** [comment]
OK, let's close for now and if needed please re-open it with new information

**Comment by rupipal** [comment]
Hi,
I've started-off with Quarkus just recently. I'm facing exactly the same issue while building and deploying openshift-quickstart with command:  ./mvnw clean package -Dquarkus.container-image.build=true

[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerException(DockerProcessor.java:220)
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:145)
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:85)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

Other details are:
Apache Maven 3.8.2 
Java version: 11.0.12, vendor: Debian
OS name: "linux", version: "5.10.0-8-amd64", arch: "amd64", family: "unix"
minishift v1.34.3+4b58f89


Would request help. @kiziltas
