### ISSUE TITLE
InjectMock with package private method

### ISSUE THREAD

**Issue by AntonFagerberg** [quarkusio/quarkus#14898]
've noticed that when using `@InjectMock` on a class that declares package-private methods, you do get a mocked instance but the methods that are declared package private can't be stubbed.

Given a class like this:

```java
package example;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class MyService {

    public String getPublic() {
        throw new NullPointerException();
    }

    protected String getProtected() {
        throw new NullPointerException();
    }

    String getPackagePrivate() {
        throw new NullPointerException();
    }

}
```

And a test like this:

```java
package example;

import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.mockito.InjectMock;

@QuarkusTest
public class MyServiceTest {

    @InjectMock
    MyService myService;

    @Test
    void getPublic() {
        when(myService.getPublic()).thenReturn("hello");
    }

    @Test
    void getProtected() {
        when(myService.getProtected()).thenReturn("hello");
    }

    @Test
    void getPackagePrivate() {
        when(myService.getPackagePrivate()).thenReturn("hello");
    }

}
```

The `getPublic()` and `getProtected()` tests will work as expected but `getPackagePrivate()` will throw a null pointer since it's actually invoking `myService.getPackagePrivate()` inside then when clause.

Contrary to this, a "normal" Mockito test will work just fine:

```java
package example;

import static org.mockito.Mockito.when;
import static org.mockito.MockitoAnnotations.openMocks;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;

public class MyServiceTest {

    @Mock
    MyService myService;

    @BeforeEach
    void setup() {
        openMocks(this);
    }

    @Test
    void getPublic() {
        when(myService.getPublic()).thenReturn("hello");
    }

    @Test
    void getProtected() {
        when(myService.getProtected()).thenReturn("hello");
    }

    @Test
    void getPackagePrivate() {
        when(myService.getPackagePrivate()).thenReturn("hello");
    }

}
```

If it's for some reason not possible to stub package-private methods in Quarkus then at least a helpful error message would be appreciated - it took me a while to figure out why my mock wasn't working 😄

Java version:
```
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

Quarkus version: `1.11.0.Final`

**Comment by geoand** [comment]
It seems that ByteBuddy (which is used by Mockito behind the scenes) won't generate the mock in the same package as the application class because the application class is loaded from the Quarkus ClassLoader.

@stuartwdouglas do you remember why we made Mockito parent first? I am sure there is a really good reason, I just don't remember it :)

**Comment by geoand** [comment]
So indeed we can't support package-private methods in mocking.

What would a helpful message look like to you @AntonFagerberg ? I mean would you expect to see a warning from Quarkus every time you run the tests?

**Comment by stuartwdouglas** [comment]
AFAIK it was simply not working when not loaded parent first.

**Comment by geoand** [comment]
OK, thanks

**Comment by stuartwdouglas** [comment]
The root cause of this is that QuarkusClassLoader.getParent() does not return the actual parent, but the platform ClassLoader.

This is to work around some really nasty bugs in the MP API artifacts, where they don't leave delegation to the ClassLoader but instead do manual delegation which breaks when you have isolated ClassLoaders (e.g. https://github.com/eclipse/microprofile-reactive-streams-operators/pull/130).

**Comment by stuartwdouglas** [comment]
I am testing out https://github.com/quarkusio/quarkus/compare/master...stuartwdouglas:class-loader-fix?expand=1 to see if there are other problems caused by fixing getParent().

**Comment by geoand** [comment]
> The root cause of this is that QuarkusClassLoader.getParent() does not return the actual parent, but the platform ClassLoader.
> 
> This is to work around some really nasty bugs in the MP API artifacts, where they don't leave delegation to the ClassLoader but instead do manual delegation which breaks when you have isolated ClassLoaders (e.g. [eclipse/microprofile-reactive-streams-operators#130](https://github.com/eclipse/microprofile-reactive-streams-operators/pull/130)).

Wow! I didn't even consider this :)

**Comment by geoand** [comment]
> The root cause of this is that QuarkusClassLoader.getParent() does not return the actual parent, but the platform ClassLoader.
> 

Now that is one thing I won't be forgetting anytime soon 😆

**Comment by stuartwdouglas** [comment]
Once we have a new reactive streams operations API release we should be able to remove the hack

**Comment by geoand** [comment]
Excellent!
