### ISSUE TITLE
Vert.x 4 + Micrometer: Use request context attributes + requestRouted

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#14905]
**Description**
Vert.x 4 brings some Observability API changes that could/should allow some cleanup of the code trying to determine the active route for the request.

Reference: eclipse-vertx/vert.x#3579 -> eclipse-vertx/vert.x#3792

Part of #14779

**Comment by cescoffier** [comment]
@ebullient is this one done?
