### ISSUE TITLE
Resteasy duplicate path not detected

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#14909]
**Describe the bug**
If multiple targets are declared for the same path, one of them will be picked as the runtime target for the endpoint

**Expected behavior**
The duplication should be detected at build time, and an exception triggered to prevent application startup

 - Quarkus version : 1.11.1.FINAL

**Comment by jtama-op** [comment]
I would be happy to help, and though I can see that detecting the duplicate is rather easy only considering the class level `@Path` annotation (certainly in `ResteasyServerCommonProcessor`), it maybe a bit more tricky with combined class and method annotations.

**Comment by gsmet** [comment]
Let's focus our efforts on RESTEasy Reactive. I will close this one.
