### ISSUE TITLE
Improve code.quarkus.io (and devtools?) Dockerfile.native to allow running as root

### ISSUE THREAD

**Issue by huw0** [quarkusio/quarkus#14912]
**Describe the bug**
Various cloud platforms run containers as root during the build and/or execution (e.g. GCP Cloud Run). However the out of the box `Dockerfile.native` copies the native application such that running the container fails if it is not UID 1001.

To reduce effort needed to run on these platforms I think it would be helpful to default to allowing container to be run as either UID 1001 or root.

**Expected behavior**
A Quarkus native image can be run either as UID 1001 or as root UID 0.

**Actual behavior**
Container fails to start when run as root. This is expected given the permissions on the application

```
drwxrwxr-x.  2 1001 root 4096 Feb  8 17:11 .
drwxr-xr-x. 19 root root 4096 Feb  8 17:11 ..
-rw-rw-r--.  1 1001 root    0 Feb  8 17:10 application
```

**To Reproduce**

Generate a blank project through code.quarkus.io or through Quarkus devtools.

**Additional context**
I have solved this locally by swapping the COPY and RUN lines in the Dockerfile to ensure that the copy occurs before any permissions are modified.

```
COPY api/build/*-runner /work/application
RUN chown 1001 /work \
    && chmod -Rv "g+rwX" /work \
    && chown -Rv 1001:root /work
```

**Comment by gsmet** [comment]
@cescoffier does it make sense to you?

**Comment by cescoffier** [comment]
@gsmet Wonderful container world. If we use root, we won't be able to run on OpenShift anymore (where root is considered as a security issue). 

The good news is that you can use:

COPY --chown=<user>:<group> <hostPath> <containerPath>

So COPy --chown=1001 ... should work.

**Comment by huw0** [comment]
My chown commands leaves the user intact as 1001 but sets the group to root. This should enable non-root on OpenShift while allowing for root on GCP etc.

It's been awhile since I used OpenShift, but my understanding is that while it prevents running as root, it shouldn't be impacted if permissions just allow root permissions to run the app also?

**Comment by huw0** [comment]
Closing. Above fix is not present.
