### ISSUE TITLE
property `quarkus.swagger-ui.always-include` doesn't work on Native mode.

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#14911]
## Description

When I set up an application with `quarkus.swagger-ui.always-include` enabled, swagger-ui must be available. However on Native mode are not available. 

example:
```
quarkus.http.root-path=/api
quarkus.swagger-ui.always-include=true 
```
- Compile and run your app on native mode and then make the following query:

```
Request method:	GET
Request URI:	http://test-http-advanced-pablo-test.apps.ocp45.dynamic.quarkus/api/q/swagger-ui

HTTP/1.1 404 Not Found
```
**Notes:**
- Tested with Rest assurance. 

[Jira Ref](https://issues.redhat.com/browse/QUARKUS-752)

**Comment by phillip-kruger** [comment]
Managed to recreate. This is only when using `quarkus.http.root-path`. Investigating.

**Comment by phillip-kruger** [comment]
@kenfinnigan - I need some help please. 
jar version works fine (fast-jar) so only when using `-Pnative` and only when adding `quarkus.http.root-path`
There is nothing obvious in the extension wrong (that I can see)

Can you assist ?

**Comment by pjgg** [comment]
lets me give you a scenario!:
Use this application: https://github.com/pjgg/beefy-scenarios/tree/master/001-quarkus-getting-started
Add this dependency to his pom.xml

```
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
```

And this property to his application.property

```
quarkus.http.root-path=api
quarkus.swagger-ui.always-include=true 
```

And now compile this app: `mvn clean install -Dmaven.test.skip=true -Pnative` (in native mode)

Then run the app, located in target folder: `./001-quarkus-getting-started-1.0.0-SNAPSHOT-runner`
Validate that is running: `curl -v http://localhost:8080/hello`
And try to load swagger-ui site: `http://localhost:8080/api/q/swagger-ui/` and you will get a 404
