### ISSUE TITLE
How do you register JsonbAdapter?

### ISSUE THREAD

**Issue by rdifrango** [quarkusio/quarkus#1491]
I'd like to register custom [JsonbAdapter](http://json-b.net/docs/api/java.json.bind/javax/json/bind/adapter/JsonbAdapter.html) to handle my custom types.  

It's not clear from the documentation how I would go about doing so and/or if this is supported.

To be clear, with JAXB/Moxy I could add `@Named` to my adapters and thus they were eligible for DI and when JAXB/Moxy attempted to resolve them it used the one defined in the environment instead of creating a new instance each time.

**Comment by gsmet** [comment]
You mean when using RESTEasy + JSON-B?

**Comment by rdifrango** [comment]
@gsmet correct.

**Comment by rdifrango** [comment]
So upon a quick test I did something roughly like the following:

```
@JsonbTypeAdapter(value = MyAdapter::class)
class MyType {}

...

class MyOtherType {
    MyType myType;
}
```

and it resulted in:

```
2019-03-15 09:04:57,334 8c8590c96b47 chassis-quarkus-pocs-dev.jar[3058] ERROR [org.jbo.res.res.i18n] (XNIO-1 task-1) RESTEASY002025: Unknown exception while executing GET /hello: javax.ws.rs.ProcessingException: RESTEASY008205: JSON Binding serialization error java.lang.UnsupportedOperationException
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.writeTo(JsonBindingProvider.java:137)

...

Caused by: java.lang.UnsupportedOperationException
	at io.quarkus.arc.BeanManagerImpl.createAnnotatedType(BeanManagerImpl.java:205)
```

**Comment by gsmet** [comment]
Hmmm, do you mean `@JsonbTypeAdapter(value = MyAdapter.class)` with a `.` instead of `::`?

You will probably need to also add `@RegisterForReflection` on the adapter implementation.

I don't know if this will work but another (better IMHO) option would be to use a provider implementing `ContextResolver<Jsonb>`. Something like:
```
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class JsonbContextResolver implements ContextResolver<Jsonb> {
  // implement what you want here
}
```

**Comment by rdifrango** [comment]
@gsmet Yeah, the `::` was because I'm using Kotlin :) . 

I tried `@RegisterForReflection` and the same result.

I'll try the `ContextResolver` next.

**Comment by rdifrango** [comment]
As a point of reference here's what I'm after and no matter what I seem to do it doesn't work:

https://developer.ibm.com/articles/j-javaee8-json-binding-3/#json-b-adapters

**Comment by gsmet** [comment]
@rdifrango could you share a simple project that I can take a look at?

Thanks.

**Comment by masini** [comment]
I think the problem is in how Yasson lookup CDI Beans, like your Adapter, it uses BeanManager's method not implemented by Arc.

**Comment by gsmet** [comment]
@mkouba could you take a look at this one? Especially to this comment: https://github.com/quarkusio/quarkus/issues/1491#issuecomment-473280520 .

It looks like a method is missing in ArC if we want to support JSON-B properly.

**Comment by manovotn** [comment]
This looks very much the same as #1656.

I am not sure that Yasson tries to achieve with those beans - is it addition of new beans or modification of bean metadata? Or if it's just looking up contextual instances, then you can use either `CDI.current()` or, better still, `BeanManager.createInstance()` and go from there. Both are supported by Arc.
