### ISSUE TITLE
Resteasy-reactive duplicate path exception not detected

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#14910]
**Describe the bug**
If multiple targets are declared for the same path, one of them will be picked as the runtime target for the endpoint

**Expected behavior**
The duplication should be detected at build time, and an exception triggered to prevent application startup

 - Quarkus version : 1.11.1.FINAL

**Comment by jtama-op** [comment]
I would be happy to help, and though I can see that detecting the duplicate is rather easy only considering the class level @Path annotation (certainly around ResteasyReactiveScanner), it maybe a bit more tricky with combined class and method annotations.

**Comment by geoand** [comment]
Thanks for reporting!

Can you give an example where you encountered the problematic behavior?
I would like to see what the behavior of RESTEasy Classic is in the same case.

**Comment by stuartwdouglas** [comment]
Note that multiple routes matching the same path are allowed by the spec, as JAX-RS also matches on content type. If we were going to detect this it needs to detect that the [path, method, produces,consumes] combination is exactly the same. If any one of them is different then this is valid.

**Comment by geoand** [comment]
Yeah.

I really want to see how RESTEasy Classic behaves because I don't want to add this sort of detection (which whatever performance penalty it might entail) unless we really have to

**Comment by jtama-op** [comment]
Resteasy behave exactly the same #14909. In any case it causes the endpoint score page to trigger an exception :

`io.quarkus.qute.TemplateException: Loop section error in template io.quarkus.quarkus-resteasy-reactive/scores on line 4: [info:endpointScores.endpoints] resolved to [io.quarkus.qute.Results$Result] which is not iterable`

I will create a reproducer.

**Comment by geoand** [comment]
The specific case you have in your reproducer:

```java
@Path("/hello-resteasy")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String helloDuplicate() {
        return "Hello duplicate RESTEasy";
    }
}
```

is very easy to detect at build time and warn about. However there could be more tricky cases that would potentially much more to detect.

@stuartwdouglas @FroMage what is your take on this? So we add some simplistic detection?

**Comment by FroMage** [comment]
Let's do the easy common ones first, and leave the complex ones for another millenia/team.

**Comment by jtama-op** [comment]
I will be happy to help !

**Comment by geoand** [comment]
@jtama-op Cool!

I propose starting small by checking the use case where methods of the same class have serve the same HTTP method, have the same path and have the same Consumes value.
The most likely place to do that check is `org.jboss.resteasy.reactive.common.processor.EndpointsIndexer#createEndpoints`

**Comment by stuartwdouglas** [comment]
That is perfectly legal though, the method will be believed based on the accept header sent by the client

**Comment by geoand** [comment]
Ah damn... I forgot the fact that the Accepts header comes into play...

**Comment by jtama-op** [comment]
Ok, so I have something that works, and that is enable to detect duplicates from different classes. 
But I find the code really messy...
I made a WIP PR so we can discuss on this.

**Comment by mkouba** [comment]
FTR I've found this in the spec, JAX-RS 2.1, 3.7.2 Request Matching:
```
(c) Let D be the first resource method in the set M 8 and O an instance of the class that defines D. If
after sorting, there is more than one maximum element in M , implementations SHOULD report
a warning and select one of these methods in an implementation dependent manner.
```
In my particular case, I had the following resource classes:
```java
@Path("/hello")
public class HelloResource {

    @GET
    @Produces(MediaType.TEXT_HTML)
    public String get() {
        return "hello";
    }
}

@Path("/hello")
public class HeroResource {

    @GET
    @Produces(MediaType.TEXT_HTML)
    public String get() {
        return "hero";
    }
}
```
RESTEasy classic logs the following message:
```
2021-06-29 14:21:42,858 WARN  [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002142: Multiple resource methods match request "GET /hello". Selecting one. Matching methods: [public java.lang.String org.acme.qute.HelloResource.get(java.lang.String), public java.lang.String org.acme.qute.HeroResource.get()]
```

**Comment by FroMage** [comment]
I actually got bitten by this last week. We should really get this in.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15037 attempts to solve it

**Comment by jtama** [comment]
Yes although a simple warning seems weak to me.

**Comment by geoand** [comment]
We don't have much of a choice. We either only warn or introduce a config flag that will allow for failing (and this flag won't be used in the TCK)

**Comment by jtama** [comment]
Ok thanks I’ll check that.

From: Georgios Andrianakis ***@***.***>
Date: Wednesday, 30 June 2021 at 11:31
To: quarkusio/quarkus ***@***.***>
Cc: Jérôme TAMA ***@***.***>, Mention ***@***.***>
Subject: Re: [quarkusio/quarkus] Resteasy-reactive duplicate path exception not detected (#14910)

We don't have much of a choice. We either only warn or introduce a config flag that will allow for failing (and this flag won't be used in the TCK)

**Comment by FroMage** [comment]
Well, we could default to failing, and add a flag that we turn on for the TCK. I thought we already did that for some of our default return type matching?

Yeah we do: https://github.com/quarkusio/resteasy-reactive-testsuite/blob/master/tests/src/test/java/com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsink/JAXRSClient0176.java#L56

**Comment by geoand** [comment]
We could certainly do that, but I personally don't think it's right - although I can definitely understand the POV

**Comment by FroMage** [comment]
IMO endpoints that are matches for the exact same rules should be an error. I mean, I don't even see the point in allowing them, and picking one randomly.

Perhaps there are cases where we don't quite know if there are multiple matches until runtime, but I'm not sure I see any example.

**Comment by jtama** [comment]
I perfectly agree exact match should be an error. Warnings will be ignored 90% of the time.

**Comment by mkouba** [comment]
I also think that a warning is not enough but we should only do that if we're 100% sure it does not break any legal use case; and I can't help here because my knowledge of jax-rs request matching is very limited.

**Comment by stuartwdouglas** [comment]
It should definitely be an error IMHO, I don't think there is any use case for picking one at random.

**Comment by jtama** [comment]
Pushed some code on the PR implementing @FroMage suggestion
