### ISSUE TITLE
Quarkus-Quartz: Jobs running concurrently in clustered environment 

### ISSUE THREAD

**Issue by flansen** [quarkusio/quarkus#14924]
**Describe the bug**
Hi,

I was using Quarkus/Quartz in my project to manage jobs in a clustered environment. 
My requirement is that the my job is running exactly once.

Following this guide: https://quarkus.io/guides/scheduler-reference#concurrent_execution my Job method looked like this:

```java
@Scheduled(every = "15s", concurrentExecution = SKIP) 
void nonConcurrent() throws Exception {
  logger.info("start");
  Thread.sleep(30000);
  logger.info("end");
}
```

Running locally, the job was really just executed once.
In my cluster, the job was executed exactly once by each pod.

**Expected behavior**
I expected `concurrentExecution = SKIP` to make use of the Job configuration parameter `is_nonconcurrent` which is used by quartz to ensure a job is running nonconcurrently.

**Actual behavior**
`is_nonconcurrent` is not set by `concurrentExecution = SKIP`. 
Jobs are actually executed concurrently in a multi-pod environment

**To Reproduce**

1. Setup project with quarkus and quartz
2. Create the job mentioned above
3. Run multiple pods

**Configuration**
Quarkus version: 1.10.5.Final
```properties
quarkus:
    quartz:
      clustered: true
      store-type: jdbc_cmt
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 20.2.0
 - Output of `java -version`:  openjdk version "11.0.9" 2020-10-20
 - GraalVM version (if different from Java): %
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_DE, platform encoding: US-ASCII
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Additional context**
%

**Comment by mkouba** [comment]
Hello, yes the `Scheduled#concurrentExecution()` is not reflected in the Quartz cluster config in any way. And the docs intentionally do not mention that it does. Nevertheless, if the `is_nonconcurrent` column maps to `@DisallowConcurrentExecution` I don't think it would help to prevent multiple job executions in a cluster.

In any case, I think that this issue duplicates https://github.com/quarkusio/quarkus/issues/14671 that was fixed in https://github.com/quarkusio/quarkus/pull/14734. It would be great if you could test your app with quarkus master branch or 1.11.2 that should be released shortly.

**Comment by flansen** [comment]
Thanks for your quick reply :-)
Maybe I did understand the docs incorrectly.

_Nevertheless, if the is\_nonconcurrent column maps to @DisallowConcurrentExecution I don't think it would help to prevent multiple job executions in a cluster._
I'm using the `@DisallowConcurrentExecution` annotation successfully with programmatic scheduling - it works just fine to prevent multiple Jobs of the same identity to be running concurrently in the cluster.

When I'm using programmatic scheduling and annotate my Job with said annotation, I can observe it works fine in the multi-pod environment:

```java
@ApplicationScoped
@DisallowConcurrentExecution
public class MyJob implements Job {

    private static final Logger logger = LoggerFactory.getLogger(MyJob.class);

    @Override
    public void execute(final JobExecutionContext context) {
          logger.info("start");
          Thread.sleep(30000);
          logger.info("end");
    }
}
```

Can you maybe explain the intention concurrentExecution = SKIP won`t prevent concurrent job executions via said flag?

**Comment by mkouba** [comment]
> I'm using the @DisallowConcurrentExecution annotation successfully with programmatic scheduling - it works just fine to prevent multiple Jobs of the same identity to be running concurrently in the cluster.

I'm not a quartz expert but multiple jobs of the same identity should only be triggered by one node in the cluster by default, i.e. no need to add `@DisallowConcurrentExecution` which is IMO more about overlapping executions...

> When I'm using programmatic scheduling and annotate my Job with said annotation, I can observe it works fine in the multi-pod environment:

There was a problem in scheduling `@Scheduled` methods during app start: https://github.com/quarkusio/quarkus/pull/14734/files#diff-c639bfa620c120ae00ffdef3e0c3ef8dfc051f4f305c818a8691edb8e4c0bd31L184-L190

**Comment by flansen** [comment]
I just did test it again. Setup:

```java
@ApplicationScoped
public class MyJob {

    private static final Logger logger = LoggerFactory.getLogger(MyJob.class);

    @Scheduled(identity = "MyJob", every = "15s", concurrentExecution = SKIP)
    void doStuff() throws InterruptedException {
        logger.info("starting job");
        Thread.sleep(30_000);
        logger.info("finished job");
    }
}
```

My expectation would be that when multiple nodes are running, only one node will execute the job.

Having a look at the logs:

```
my-service-49-1 09:39:02 INFO  [MyJob] (QuarkusQuartzScheduler_Worker-1) starting job
my-service-49-2 09:38:54 INFO  [MyJob] (QuarkusQuartzScheduler_Worker-14) starting job
```

You can see that the Job is startet twice within 8s by different nodes.

When I change to using programmatic scheduling in combination with DisallowConcurrentExecution, my jobs will not be started concurrently in any way.

```java
@ApplicationScoped
@DisallowConcurrentExecution
public class MyJob implements Job {

    private static final Logger logger = LoggerFactory.getLogger(MyJob.class);


    @Override
    public void execute(final JobExecutionContext context) throws JobExecutionException {
        logger.info("starting job");
        try {
            Thread.sleep(30_000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        logger.info("finished job");
    }
}
```

Scheduling Code:

```java
    private <T extends Job> void scheduleJob(final Class<T> clazz, final int intervalInSeconds) {
        try {
            final JobDetail job = buildJobDetail(clazz);
            final Trigger trigger = buildTrigger(clazz, intervalInSeconds);

            scheduler.addJob(job, true, true);
            scheduler.scheduleJob(job, Set.of(trigger), true);
            logger.info("Scheduled {} every {} seconds", clazz.getSimpleName(), intervalInSeconds);
        } catch (final SchedulerException schedulerException) {
            logger.error("Couldn't schedule Job " + clazz.getSimpleName() + " due to an exception", schedulerException);
        }
    }


    private <T extends Job> Trigger buildTrigger(final Class<T> clazz, final int intervalInSeconds) {
        return TriggerBuilder.newTrigger()
                .withIdentity(clazz.getSimpleName() + "_Trigger", "group1")
                .startAt(Date.from(Instant.now().plus(5, ChronoUnit.MINUTES)))
                .withSchedule(SimpleScheduleBuilder.simpleSchedule()
                        .withIntervalInSeconds(intervalInSeconds)
                        .repeatForever())
                .build();
    }


    private <T extends Job> JobDetail buildJobDetail(Class<T> clazz) {
        return JobBuilder.newJob(clazz)
                .withIdentity(clazz.getSimpleName() + "_Job", "group1")
                .build();
    }
```

Conclusion: To me it looks like preventing concurrent execution does not work as expected.

**Comment by mkouba** [comment]
> When I change to using programmatic scheduling in combination with DisallowConcurrentExecution, my jobs will not be started concurrently in any way.

My point was that it should work even if you skip the `@DisallowConcurrentExecution` annotation.

> Conclusion: To me it looks like preventing concurrent execution does not work as expected.

Ok, I'll repeat it once again: 
1. `Scheduled#concurrentExecution()` was not intended as a cluster functionality.
2. There was a bug that should be fixed in the linked pull request.

**Comment by dcdh** [comment]
Sorry for replying to this old issue.

Is it possible to document it on the guide ?

Because we where facing the same issue that @flansen 

On our side we are programmatically creating a scheduler following this guide https://quarkus.io/guides/scheduler-reference#programmatic_scheduling with 
```java
                .setConcurrentExecution(Scheduled.ConcurrentExecution.SKIP)
```
and we except to have a quartz job (which is the case) having IS_NONCONCURRENT defined to true (which is not).

I've got same intention than @flansen

**Comment by mkouba** [comment]
> Is it possible to document it on the guide ?

It is documented in https://quarkus.io/guides/scheduler-reference#concurrent_execution and in the javadoc of `io.quarkus.scheduler.Scheduled.ConcurrentExecution`.

> We expected to have a quartz job detail in database (which is the case) having IS_NONCONCURRENT defined to true (which is not).

I cannot find any relevant, clear and unambiguous information about the relationship between `@DisallowConcurrentExecution`, the `is_nonconcurrent` column and the behavior in a cluster.
