### ISSUE TITLE
hibernate-jpamodelgen is causing problems

### ISSUE THREAD

**Issue by the-bug** [quarkusio/quarkus#14926]
**Describe the bug**
I started a the 'Quarkus - Get Started'-project (See https://quarkus.io/get-started/) in order to have an initial code base.
After that I added JPA and tried to integrate 'hibernate-jpamodelgen' in order to use the 'Metamodel Generator'. 
Adding the hibernate-jpamodelgen was done via:
```
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
<configuration>
	<annotationProcessorPaths>
		<annotationProcessorPath>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-jpamodelgen</artifactId>
			<version>5.4.27.Final</version>
		</annotationProcessorPath>
		<annotationProcessorPath>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-panache-common</artifactId>
			<version>${quarkus.platform.version}</version>
		</annotationProcessorPath>
	</annotationProcessorPaths>
</configuration>
</plugin>
```
As described in https://quarkus.io/guides/hibernate-orm-panache#defining-entities-in-external-projects-or-jars.

'mvn clean compile quarkus:dev' leads to the following error:
```
[ERROR] /home/jonas/private-workspace/getting-started/target/generated-sources/annotations/org/acme/getting/started/Person_.java:[10,71] cannot find symbol
  symbol:   class PanacheEntity_
  location: package io.quarkus.hibernate.orm.panache
```

**Expected behavior**
'mvn clean compile quarkus:dev' works and the 'Metamodel Generator' works as well

**Actual behavior**

'mvn clean compile quarkus:dev' leads to the following error:
```
[ERROR] /home/jonas/private-workspace/getting-started/target/generated-sources/annotations/org/acme/getting/started/Person_.java:[10,71] cannot find symbol
  symbol:   class PanacheEntity_
  location: package io.quarkus.hibernate.orm.panache
```

**To Reproduce**

1. `git checkout git@github.com:the-bug/hibernate-jpamodelgen-reproducer.git`
2. `cd hibernate-jpamodelgen-reproducer`
3. `mvn clean compile quarkus:dev`

**Configuration**
-

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux ... 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 ```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
 - GraalVM version (if different from Java): not used 
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
Maven home: /home/.../.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-65-generic", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by dstutz** [comment]
I just added
```
<dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-jpamodelgen</artifactId>
      <scope>provided</scope>
</dependency>
```
to my pom and I get the metamodel classes generated.  I don't know if this is "the right way" but it works.  provided scope keeps it out of the jar as it's only used during compilation.

**Comment by famod** [comment]
The downside of adding annotation processor dependencies as provided is that they can pollute you test classpath.

**Comment by famod** [comment]
@Postremus seeing that you added something for `PanacheEntity_` a year ago via #7218, do you know what's going wrong here? Thanks!

**Comment by the-bug** [comment]
@dstutz thanks for this hint. I used this approach as well and it used to worked.
Did you extend an entity with PanacheEntity e.g. `extends PanacheEntity`? Like in https://github.com/the-bug/hibernate-jpamodelgen-reproducer/blob/main/src/main/java/org/acme/getting/started/Person.java#L10 
I think this is the root cause...

**Comment by Postremus** [comment]
Annotation processors where deactivated in the panache modules, causing no PanacheEntity_ to be generated.
I proposed a fix in #15064, but I'm not sure myself why they where deactivated in the first place.

**Comment by the-bug** [comment]
@Postremus thanks!

**Comment by dstutz** [comment]
> Did you extend an entity with PanacheEntity e.g. `extends PanacheEntity`? Like in https://github.com/the-bug/hibernate-jpamodelgen-reproducer/blob/main/src/main/java/org/acme/getting/started/Person.java#L10

@the-bug , I did not...I'm working on converting a very small application from Jakarta EE to Quarkus and just copied the entities over.
