### ISSUE TITLE
Quarkus dev UI does not load when app does not start

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#14931]
In my usual flow, I create a todo app with an endpoint, create the entity but the database configuration is not set yet.
When I hit refresh, I get an error expectedly. But then I want to edit the config file with the Dev UI and hit `/q/dev/` and I get the DB error and the Dev UI does not show. Which means I cannot update my config file.

**Comment by emmanuelbernard** [comment]
CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/14692 is supposed to help with this, it embeds a config editor for the relevant properties onto the error page. It should also be possible to get the full config editor working, although probably not the full dev console as some bits of it assume there is a working application (e.g. can't list beans if there is no working CDI, can't list schedule methods for the same reason).

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
