### ISSUE TITLE
Dev UI config editor does not make it clear which property is set and which is not

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#14933]
There is the blue background but it's not made explicit what it is about

**Comment by gsmet** [comment]
@phillip-kruger did you address that in your Dev UI config work?

**Comment by phillip-kruger** [comment]
When you change bit, it goes green for a moment, but then goes back to normal. 

I think we can do something where we indicate what is set by you, i.e in application.properties.

I can look at that .

**Comment by phillip-kruger** [comment]
Hi @emmanuelbernard @gsmet @radcortez 

I have been looking at this, and I think we should remove  `environment variables` and `system properties` from the list here. Or at least make them not editable.

Here my reason:

Changing any value here really just add an entry into `application.properties` and restart the app (in dev mode). 

`application.properties` can not override any property in  `environment variables` or `system properties` as the ordinal is lower, so this has not effect when changing any value from those two config sources.

We should only allow editing config sources that can be overridden with `application.properties` (as this is what we edit) 

If we remove  `environment variables` and `system properties` completely (i.e. not just make then uneditable, but remove them) that might also solve some of the security concerns.

What I have done so far is to have multiple tables (rather that just one) that group the values according to the Config Source.
That way, all `application.properties` is at the top and easy to see what you have set yourself.

Let me know what you think.

**Comment by phillip-kruger** [comment]
Hi @emmanuelbernard @gsmet @radcortez

You can see what I have done so far here: https://github.com/quarkusio/quarkus/compare/master...phillip-kruger:dev-ui-indicate-app-properties

Looks something like this:
![dev-ui-conf-properties](https://user-images.githubusercontent.com/6836179/109828476-54123880-7c45-11eb-8777-f2222170e606.gif)

**Comment by radcortez** [comment]
I think the main motivation to include everything is for the user to have a clear view on what is being overridden or not. We had some cases in the past where users reported issues about configs not being read, but in fact it was an env variable of system property being set somewhere.

I'm ok if we change them to be read only, but also remember that the current user env, is not necessarily the env where the app is going to run (or even other developers), so the user may want to add a property to make sure is not going to be missed.

**Comment by phillip-kruger** [comment]
> so the user may want to add a property to make sure is not going to be missed.

You mean to application.properties ?

Even if the use does that, it will not take effect until the env var is removed, that we are not doing from this interface.
So at the moment, it would just appear like it's not working.

I make them read only but still visible. Let me know if this is ok ? Should I do a PR ?

**Comment by radcortez** [comment]
Sure go ahead.
