### ISSUE TITLE
Quartz: Allow to use a configuration property in identity

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#14967]
**Description**
Most of the fields in the `@Scheduled` annotation allow to use a config property:

```
@Scheduled(cron = "{myMethod.cron.expr}")
```

However, the identity field can't do:

```
@Scheduled(identity = "{job.id}")
```

**Comment by machi1990** [comment]
Very good idea, WDYT @mkouba?. 

Do you want to give it a stab? @Sgitario

**Comment by Sgitario** [comment]
> Very good idea, WDYT @mkouba?.
> 
> Do you want to give it a stab? @Sgitario

I'm very volunteer! :)
