### ISSUE TITLE
1.11.2.Final compilation error

### ISSUE THREAD

**Issue by ryckowski** [quarkusio/quarkus#14965]
**Describe the bug**
Upgrade from 1.10.5 to 1.1.2.Final compilation error

**Expected behavior**
Working as before

**Actual behavior**
`
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.2.Final:build (default) on project xxx: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.NoSuchMethodError: 'void io.quarkus.bootstrap.runner.SerializedApplication.write(java.io.OutputStream, java.lang.String, java.nio.file.Path, java.util.List, java.util.List)'
[ERROR] 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:556)
[ERROR] 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
`

**To Reproduce**
./mvnw clean package -Pnative

**Comment by gsmet** [comment]
Just to be sure, you have also upgraded the quarkus bom version? And all versions are consistent?

**Comment by ryckowski** [comment]
> Just to be sure, you have also upgraded the quarkus bom version? And all versions are consistent?
Right, didn't notice there're 2 places to be changed

**Comment by gsmet** [comment]
Thanks for confirming!
