### ISSUE TITLE
Add start/stop methods for QuarkusProdModeTest and do not setup RestAssured.port if it's configured randomly

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#14961]
**Description**
The JAVA process that is created as part of `QuarkusProdModeTest` follows the JUnit extension lifecycle. However, sometimes is desired to manually control the state to cope with more scenarios within the same test case.

**Implementation ideas**
I will provide implementation ideas. Also, I would like to provide a solution for this enhancement by myself.

**Comment by geoand** [comment]
I don't really understand this, can you explain more?

**Comment by Sgitario** [comment]
> I don't really understand this, can you explain more?

Mostly, in order to cope with test scenarios of failover cases. Example:

```
@RegisterExtension
static final QuarkusProdModeTest nodeApp = new QuartzNodeApplicationResource();

@RegisterExtension
static final QuarkusProdModeTest masterApp = new QuartzMasterApplicationResource();

@Test
public void testFailover() {
    assertMasterIsConnectedWithNode();

    // simulate node failover
    nodeApp.stop();
    assertMasterIsNotConnectedWithNode();

    nodeApp.start();
    assertMasterIsConnectedWithNode();
}
```

Also, about the rest assured, when we want to start our Quarkus application using a random port (`quarkus.http.port=0`), the QuarkusProdModeTest is setting `RestAssured.defaultPort = 0` which is invalid (if you try to do `given()` in your test case, you will get an exception.

**Comment by Sgitario** [comment]
@geoand I've proposed a PR to address this issue.

**Comment by geoand** [comment]
I see, thanks for the example.

To be honest, `QuarkusProdModeTest` was never meant to work when having multiple test extensions registered... I am surprised that is does work but I am not sure I want to explicitly support this...

@stuartwdouglas WDYT?

**Comment by stuartwdouglas** [comment]
I think this is a corner case, but it does seem relatively simple to support so maybe it is ok. I would like some tests for this in the PR thought.

**Comment by Sgitario** [comment]
> I think this is a corner case, but it does seem relatively simple to support so maybe it is ok. I would like some tests for this in the PR thought.

This module was lacking of test units. However, I've added one to support this simple use case. The PR is updated.
