### ISSUE TITLE
Native build fails for 1.11.2.Final with quarkus-smallrye-opentracing

### ISSUE THREAD

**Issue by kjeldpaw** [quarkusio/quarkus#14971]
**Describe the bug**
After I have upgraded to 1.11.2.Final from 1.11.1.final I'm not able to build native when my project uses quarkus-smallrye-opentracing. Removing the dependency it's working. 

**Actual behavior**
I'm getting following error:

`[INFO] --- quarkus-maven-plugin:1.11.2.Final:build (default) @ user-stash ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.flyway.FlywayProcessor] Adding application migrations in path '/Users/pfk/Projects/infrastructure/user-stash/target/classes/db/migration/' using protocol 'file'
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.4.27.SP1
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Using docker to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Checking image status quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
20.3.1-java11: Pulling from quarkus/ubi-quarkus-native-image
57de4da701b5: Already exists
cf0f3ebe9f53: Already exists
05bc129dcb13: Pull complete
Digest: sha256:b20c8294bf4278f79e7ac7ca0318f858bf46bd80f427de91776762632d25e87f
Status: Downloaded newer image for quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/pfk/Projects/infrastructure/user-stash/target/user-stash-snapshot-native-image-source-jar/user-stash-snapshot-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/pfk/Projects/infrastructure/user-stash/target/user-stash-snapshot-native-image-source-jar/user-stash-snapshot-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Using docker to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Checking image status quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
20.3.1-java11: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:b20c8294bf4278f79e7ac7ca0318f858bf46bd80f427de91776762632d25e87f
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/pfk/Projects/infrastructure/user-stash/target/user-stash-snapshot-native-image-source-jar:/project:z --env LANG=C --rm quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dcom.mysql.cj.disableAbandonedConnectionCleanup=true -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar user-stash-snapshot-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace user-stash-snapshot-runner
[user-stash-snapshot-runner:26] classlist: 18,691.05 ms, 1.19 GB
[user-stash-snapshot-runner:26] setup: 2,067.90 ms, 1.19 GB
Error: One of @Delete, @Alias, or @Inject must be used: static final java.lang.String io.quarkus.smallrye.opentracing.runtime.graal.Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.FILTER_CONFIG_SOURCE_NAME
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Alias, or @Inject must be used: static final java.lang.String io.quarkus.smallrye.opentracing.runtime.graal.Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.FILTER_CONFIG_SOURCE_NAME
at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:398)
at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:343)
at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:309)
at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:919)
at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:853)
at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:554)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)`

**To Reproduce**
Here is the Maven command:
`mvn clean package -Pnative -Dquarkus.native.container-build=true`

**Configuration**
Here is the pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dk.figge</groupId>
    <artifactId>user-stash</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>user-stash</name>
    <description>UserStash service</description>

    <properties>
        <surefire-plugin.version>2.22.1</surefire-plugin.version>
        <maven.compiler.target>11</maven.compiler.target>
        <quarkus.platform.version>1.11.2.Final</quarkus.platform.version>
        <maven.compiler.source>11</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <quarkus-plugin.version>1.11.2.Final</quarkus-plugin.version>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <service-base-entities-quarkus.version>3</service-base-entities-quarkus.version>
        <service-base-entities-quarkus-test.version>1</service-base-entities-quarkus-test.version>
        <stofa.repo.url>https://mvn-repo.stofa.net/repository</stofa.repo.url>
        <lombok.version>1.18.18</lombok.version>
        <revision>snapshot</revision>
        <quarkus-tracer.version>8</quarkus-tracer.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jsonb</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jsonb</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mysql</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-metrics</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-opentracing</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>
                                            ${project.build.directory}/${project.build.finalName}-runner
                                        </native.image.path>
                                        <java.util.logging.manager>org.jboss.logmanager.LogManager
                                        </java.util.logging.manager>
                                        <maven.home>${maven.home}</maven.home>
                                    </systemPropertyVariables>
                                    <environmentVariables>
                                        <dk.stofa.platform.test.database>${dk.stofa.platform.test.database}
                                        </dk.stofa.platform.test.database>
                                    </environmentVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>

</project>
`

**Comment by gsmet** [comment]
Thanks for the report.

It has already been fixed and we will release a 1.11.3.Final tomorrow with the fix.
