### ISSUE TITLE
Changing the log level for a category doesn't just work

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#14999]
In application.properties, this works:

```
quarkus.log.level=INFO
quarkus.log.min-level=DEBUG
quarkus.log.category."org.optaplanner".level=DEBUG
```

These should work too,
as shown in the docs here https://quarkus.io/guides/logging#runtime-configuration

```
quarkus.log.level=INFO
quarkus.log.category."org.optaplanner".level=DEBUG
```
This silently keeps org.optaplanner logging on INFO, but should put it on DEBUG.

or even simpler:

```
quarkus.log.category."org.optaplanner".level=DEBUG

```
This silently keeps org.optaplanner logging on INFO, but should put it on DEBUG.

**Comment by ge0ffrey** [comment]
I am pretty sure this is a regression.

**Comment by ge0ffrey** [comment]
Probably fixed in 1.11.2.Final already. Verifying...

**Comment by gsmet** [comment]
It's related to `min-level`. If you want to log more than `INFO`, you needed to set `min-level=DEBUG` too.

I changed it in 1.11.2.Final: default min-level is DEBUG in 1.11.2.Final (but you still need to change it if you want TRACE level debug info).

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.11#log-min-level (but I will update it now that 1.11.2.Final is released).

**Comment by geoand** [comment]
So do we close this or is there something more to do?

**Comment by gsmet** [comment]
We can close.

**Comment by Jaland** [comment]
I am running into the exact same issue as Geoffrey was with the latest version of quarkus. I tried setting my `min-level=DEBUG` which still did not help, and also does not make sense since the documentation says that is the default value anyways. As far as I can tell it is just ignoring the category loggers unless there is something I am missing
