### ISSUE TITLE
Improve index.html welcome page

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1499]
We include in Quarkus a welcome page when creating a new project.

The current file is here: https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/test/resources/projects/classic/src/main/resources/META-INF/resources/index.html .

It could use some love once we have a logo. @jkbrock could your team take care of it once everything is settled? It's the first thing people will see when creating a new app so I think it deserves to be nice.

**Comment by jkbrock** [comment]
@gsmet we'll definitely help. But I have a couple of questions:

- Is this a patternfly layout? 
- Here's a screenshot rendered from that code, is this what you're displaying now?

![Screen Shot 2019-03-15 at 3 41 40 PM](https://user-images.githubusercontent.com/10758508/54460904-ef4c3380-4738-11e9-8624-52f2cbad9b27.png)

**Comment by gsmet** [comment]
I don't think it's a patternfly layout, it's styled very basically (we need all the styles to be embedded so that the user only has to delete one file to get rid of it).

And yes, this is how it looks right now. Thus my request :).

**Comment by cescoffier** [comment]
I can't remember how I did it, but I don't believe it uses Patternfly, more some kind on "embedded" CSS. Note that quckstart pages (chat, validation...) uses Patternfly.  I'm not against using Patternfly (I love it), but it needs to be embedded in the page as the user may not have internet access (and adding a resource might be a bit too much).

**Comment by jkbrock** [comment]
Sounds good, I'll take a look and start on some mockups next week.

**Comment by gsmet** [comment]
@jkbrock any chance we could try to tackle this soon?

**Comment by emmanuelbernard** [comment]
now moved to @insectengine

**Comment by brunolmfg** [comment]
Maybe a configuration property could be provided to indicate the welcome or index page. This is only possible with `undertow` extension using the `welcome-files` entry on `web.xml`. The `vertx-http` extension could provide an option like this:

```properties
quarkus.http.index-page=/default.html
```

Open a specific issue for this configuration?

**Comment by insectengine** [comment]
@brunolmfg , @gsmet  - sorry, this request was before my time. Does this page still need it's visual design addressed?

**Comment by cescoffier** [comment]
@insectengine yes, definitely. I did the current one at the very beginning of Quarkus. It can be improved a lot.

**Comment by geoand** [comment]
Are we still planning on addressing this one?

**Comment by insectengine** [comment]
Didn't we already address this?

**Comment by geoand** [comment]
I'll have to check

**Comment by geoand** [comment]
Is this the updated page?

![Screenshot from 2023-08-31 09-30-17](https://github.com/quarkusio/quarkus/assets/4374975/b646c285-f8d7-4884-93ec-eea4bd25fc19)

Looks pretty similar to what was reported in this issue. Am I missing something?

**Comment by cescoffier** [comment]
No, it had not been addressed... 

We had a few ideas with @phillip-kruger, especially when running in dev mode (where we could imagine a dynamic page)

**Comment by phillip-kruger** [comment]
Yes, see "Replace the static page on root (/) with a dynamic page created by Dev UI" here: https://github.com/quarkusio/quarkus/discussions/35178

I do not think this page should be in non-dev mode (test and prod) by default anyway. We can do something that if the use wants it, we create a static file (from a button in dev ui or something)

**Comment by phillip-kruger** [comment]
see #37680
