### ISSUE TITLE
SecurityIdentityAssociation's identity not set by event fired from Undertow

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#15006]
Hello,

our application performs authentication with the servlet spec (HttpSerlvletRequest.login) and we faced the following issue when we tried to upgrade from **1.10.3.Final** to **1.11.2.Final**:

by fixing [issue/13835](https://github.com/quarkusio/quarkus/issues/13835) **SecurityIdentityAssociation** does not observe **SecurityIdentity events** anymore ([here](https://github.com/renegrob/quarkus/commit/be934ecb75799778d8ee2991b0de8b0423340fb7#diff-5f4aab87946367b5d4b85a8517f60c5404718591324f6bb91a838409b1c40b17L39)), so the event fired by the **UndertowDeploymentRecorder** [here](https://github.com/quarkusio/quarkus/blob/master/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L224) never ends up setting the security identity.

I believe that the UndertowDeploymentRecorder does not need to fire the event anymore and instead it just has to set the SecurityIdentityAssociation's identity via CDI.

The proposed fix can be found [here](https://github.com/quarkusio/quarkus/pull/15005).

**Comment by CurtisBaldwinson** [comment]
I'm not sure if it was a bug or not but I had a similar problem.

In my Filters class I injected the following SecurityIdentityAssociation:
```
    @Inject @RequestScoped
    SecurityIdentityAssociation delegateSecurityIdentityAssociation;
```

Then after grabbing the user information, I set the identity like so inside the @ServerRequestFilter:
```
                delegateSecurityIdentityAssociation.setIdentity(
                        new SecurityIdentity() {
                            @Override
                            public Principal getPrincipal() {
                                return response::toString;
                            }
... etc. etc. more methods to override
```

SecurityIdentity has a bunch of methods you'll need to override, which your IDE should help you generate.

**Comment by gsmet** [comment]
Has been fixed by https://github.com/quarkusio/quarkus/pull/15005 .
