### ISSUE TITLE
 resources not found when using PathParam

### ISSUE THREAD

**Issue by tursicSR** [quarkusio/quarkus#15008]
Hello.
I have a problem with loading resources when using PathParam. With usage of QueryParam everything works fine.
When I call it with PathParam, the code is called several times, and only at first time the original param is passed, and then it is called with all my ressources (like .css-file, pictures, etc.) as param.

The result is, that the resources are not found.

Here is the code:
```java
@Path("/e")
public class Example {
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance example(Example ex);
    }

     ExampleService service = new ExampleService();

//called like this:   .../e?nr=123
//works fine:
    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance getExample(@QueryParam("nr") String nr) {
        Example ex = service.getExample(nr);
        return Templates.Example(ex);
    }

//called like this:    .../e/123
//causes error, called several times and only first time the real param is passed
    @GET
    @Path("/{nr}")
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance get(@PathParam("nr") String nr) {
        Example ex = service.getExample(nr);
        return Templates.example(ex);
    }
}
```
What am I doing wrong?

**Comment by CurtisBaldwinson** [comment]
Are you using RestEasy Reactive? Try `@RestPath String nr` instead of `@PathParam("nr") String nr`

See: https://quarkus.io/guides/resteasy-reactive#accessing-request-parameters

**Comment by tursicSR** [comment]
I have tried it with RestEasy Reactive and "@RestPath String nr", but it didn't help. Instead I got problems with my database access (blocking operation on a IO thread).
Without reactive the database access works fine.

**Comment by CurtisBaldwinson** [comment]
> I have tried it with RestEasy Reactive and "@RestPath String nr", but it didn't help. Instead I got problems with my database access (blocking operation on a IO thread).
> Without reactive the database access works fine.

That means the RestPath worked, but now you have a different problem, which is you're using blocking operations with a reactive endpoint. You can annotate `@Blocking` to the methods if you want to proceed anyways, or yes you can use non-reactive and write procedural/imperative code as you may be used to.

It's unlikely it will actually become a problem but of course you gain additional performance and backpressure support when using reactive programming paradigms instead of a traditional blocking style.

**Comment by geoand** [comment]
I just tried taking out qute quickstart (see https://github.com/quarkusio/quarkus-quickstarts/blob/master/qute-quickstart/src/main/java/org/acme/qute/HelloResource.java)

and by changing

```java
    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance get(@QueryParam("name") String name) {
        return hello.data("name", name);
    }
```

to 

```
    @Path("/{name}")
    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance get(@PathParam("name") String name) {
        return hello.data("name", name);
    }
```

everything worked as expected

**Comment by tursicSR** [comment]
I think, it has something to do with the Browser not finding the resources(.css and pictures), the data itself is there.

But you can close the issue, I will use only QueryParam, which works fine.

**Comment by geoand** [comment]
Well if you have an example project to share that exhibits the problematic behavior, I'd love to see it :)

**Comment by tursicSR** [comment]
ok, example:  https://github.com/tursicSR/example.git

**Comment by geoand** [comment]
The problem is that the way you have constructed the matching paths, when `http://localhost:8080/e/1` does not return the image.
