### ISSUE TITLE
Application name and version are not available in test

### ISSUE THREAD

**Issue by glefloch** [quarkusio/quarkus#15013]
As discuss here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Application.20name.20and.20version, 
`quarkus.application.name` and `quarkus.application.version` are not available in test mode. 

To be consistent, those configuration should always be available and fallback to artifact id/version if not set.

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by glefloch** [comment]
@aloubyansky, I started working on it right here: #14834. As you suggested I migrated the `buildSystemProperties` in the `AppModel` but I'm kind of stuck there. I don't know how to properly propagate them in the application.

**Comment by aloubyansky** [comment]
I'll get back to you soon about this. Sorry for the delay.

**Comment by tioback** [comment]
Hey, guys. It's been a while, now, so I wonder if there's been an update, or if any help is needed.
Also, is there a workaround?

**Comment by tioback** [comment]
Posting the workaround (wrap it in an Optional) in case anyone else has the same doubt:

```java
@ConfigProperty(name = "quarkus.application.version")
java.util.Optional<String> version;
```

**Comment by GregJohnStewart** [comment]
Bump to this issue, really odd to me.

**Comment by ambition-consulting** [comment]
bump, still not working

**Comment by vsevel** [comment]
+1

**Comment by GregJohnStewart** [comment]
Another bump, as of `2.7.5`, still an issue

**Comment by aloubyansky** [comment]
@glefloch do you think you can add support for these two properties as you originally planned?
I was thinking it would make sense to make the complete set of the build system properties available but it appeared it wasn't clear it was useful or even a good idea.

**Comment by glefloch** [comment]
Yes sure, I will dig into it.
