### ISSUE TITLE
RESTEasy Reactive: Customised Jackson ObjectMapper not used

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#15018]
Expected behavior
If the ObjectMapper is customised then it should be used when serialising JSON as it does with normal RestEASY.

Actual behavior
Some other ObjectMapper is being used, causing customised mapping to be ignored.

To Reproduce

git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

Configuration
Nothing specific

Environment (please complete the following information):
Nothing specific

**Comment by bcluap** [comment]
Hi Georgios

Just an FYI on the strange way I'm adding the serializer config. For the life of me I cannot get this to work on reactive nor normal resteasy. The log line is seen but the mapper is not used in either mode. I've always just worked around this by injecting the mapper and adding the config:

@Singleton
public class RegisterCustomModuleCustomizer implements ObjectMapperCustomizer {
    private static final Logger log = LoggerFactory.getLogger(RegisterCustomModuleCustomizer.class);
    @Override
    public void customize(ObjectMapper jacksonMapper) {
        log.info("Configuring Jackson mapper [{}]", jacksonMapper);
        SimpleModule module = new SimpleModule();
        module.addSerializer(ZonedDateTime.class, new JsonSerializer<ZonedDateTime>() {
            @Override
            public void serialize(ZonedDateTime t, JsonGenerator jg, SerializerProvider sp) throws IOException {
                jg.writeString("aaa");
            }
        });
        jacksonMapper.registerModule(module);
    }
}

**Comment by geoand** [comment]
I completely understand why one would think this looks like a bug, but it's actually not.
It only worked in RESTEasy Classic, sort of by accident.

The proper way to customize an `ObjectMapper` in Quarkus is by using an [ObjectMapperCustomizer](https://quarkus.io/guides/rest-json#jackson).

In your case as you are trying to add a serializer that also added by the `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule`, there is the additional slight complication that you to need to change the priority of the customizer.

Wrapping up, the Quarkus code you need write to make your use case work is:

```java
@Singleton
public class MyCustomizer implements ObjectMapperCustomizer {

    private static final Logger log = LoggerFactory.getLogger(RestResource.class);

    @Override
    public int priority() {
        return MINIMUM_PRIORITY;
    }

    @Override
    public void customize(ObjectMapper objectMapper) {
        log.info("Configuring Jackson mapper [{}]", objectMapper);
        SimpleModule module = new SimpleModule();
        module.addSerializer(ZonedDateTime.class, new JsonSerializer<ZonedDateTime>() {
            @Override
            public void serialize(ZonedDateTime t, JsonGenerator jg, SerializerProvider sp) throws IOException {
                jg.writeString("aaa");
            }

        });
        objectMapper.registerModule(module);
    }
}
```

and then completely drop 

```
@PostConstruct
void init() {
...
}
```

from your Resource

**Comment by bcluap** [comment]
lol so in fact there is more to this than meets the eye. It seems that its not the priority method that makes a difference - instead its the name of the Customizer. It seems like they are prioritized based on alphabetic order of classname. If you do a pull you will see some changes I made to your customizer:
```

@Singleton
public class ZMyCustomizer implements ObjectMapperCustomizer { // THIS ONE DOES NOT WORK
// public class AMyCustomizer implements ObjectMapperCustomizer { // THIS ONE WORKS

```

The name "RegisterCustomModuleCustomizer" I was using starts with R while yours started with "M" and that's what makes yours work!!!

**Comment by geoand** [comment]
That is sort of the case.

When the customizers don't change the priority, the default priority is set and then yeah, I guess the name comes into play implicitly.
But if you use the priority (which was added to address this type of situation), then you don't have to worry about the name.

**Comment by geoand** [comment]
> The name "RegisterCustomModuleCustomizer" I was using starts with R while yours started with "M" and that's what makes yours work!!!

No, that's not the case. If I remove the priority mine doesn't work either

**Comment by bcluap** [comment]
Even with priority it fails if the class name is late in the alphabet:

![image](https://user-images.githubusercontent.com/26746221/107743040-d67b9c80-6d18-11eb-9c4f-5dea95039d38.png)
![image](https://user-images.githubusercontent.com/26746221/107743052-dd0a1400-6d18-11eb-8e23-356ebfb13ccb.png)
![image](https://user-images.githubusercontent.com/26746221/107743104-f612c500-6d18-11eb-9b63-a1d6fd175d09.png)
![image](https://user-images.githubusercontent.com/26746221/107743119-fd39d300-6d18-11eb-9216-9560dcf8d97f.png)

**Comment by bcluap** [comment]
Aha. I'm not going mad!!!

**Comment by geoand** [comment]
So the problem turns to be that the auto-generated customizer also uses the minimum priority and that causes the sort to fallback on the name.

Thanks for identifying the problem!

I'll add a fix ASAP

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15027 takes care of the problem.

Thanks again for the vigilance!
