### ISSUE TITLE
Even if feature about serialization (from  GraalVM 21.0 ) is proposed, small change could make it work even now

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus#15039]
**Description**
There is an issue about *Better DevExp for serialization feature support as of GraalVM 2* (https://github.com/quarkusio/quarkus/issues/14530)

But it is possible to make serialization work only by removing substitution, which cuts off serialization - see https://github.com/quarkusio/quarkus/commit/214e05cf396c8dca18bd6a7b99062fe42d9749bc

**Implementation ideas**
I've tested camel-quarkus nitrite extension, which uses java serialization. 

With provided serialization mapping (https://github.com/JiriOndrusek/camel-quarkus/commit/04134ef809dcbf796ba100aaf49d07d723c12e71#diff-e008186a29d7dc393c8bc2c05a5303d14d3f13050f7f48dc08b27d50edaf68f9R1) and removed substitution  https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/graal/JavaIOSubstitutions.java, serialization **works**. (my test could be used as reproducer, use this commit https://github.com/JiriOndrusek/camel-quarkus/commit/04134ef809dcbf796ba100aaf49d07d723c12e71 and execute by `mvn clean verify -Pnative -f integration-tests/nitrite`)

I'd like to suggest to remove substitution https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/graal/JavaIOSubstitutions.java. (if it makes sense)

**Comment by gsmet** [comment]
@JiriOndrusek if CI is OK with it, I'm OK too.

**Comment by JiriOndrusek** [comment]
CI is OK with the subset of tests at the moment, I'm working on the rest of them (but their issues are not serialization related)

**Comment by JiriOndrusek** [comment]
@gsmet Sorry, I didn't understand correctly.  I'll try to create PR and see whether CI is ok. I've tested only my usecase.
