### ISSUE TITLE
Mapper sharing between the Jackson extension and Vert.x

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15031]
**Description**

Vert.x 4 offers an SPI mechanism that would allow sharing the `ObjectMapper` between Quarkus and Vert.x. Thus, user customization would also be applied to object mapped to JSON from Vert.x. 

**Implementation ideas**

- The Jackson extension (runtime) could depend on Vert.x core (optional dependency) and implement the SPI
- The SPI implementation would retrieve the managed `ObjectMapper` using:
```java
mapper = Arc.container().instance(ObjectMapper.class).get();
```
- The Jackson would check the availability of the Vert.x capability and if so register the SPI to be available in native mode.
- Also, it should make sure that the `ObjectMapper` does not get removed by Arc, as Arc cannot detect such a usage.
- The SPI implementation should register the Vert.x module:
```java
SimpleModule module = new SimpleModule();
// custom types
module.addSerializer(JsonObject.class, new JsonObjectSerializer());
module.addSerializer(JsonArray.class, new JsonArraySerializer());
// he have 2 extensions: RFC-7493
module.addSerializer(Instant.class, new InstantSerializer());
module.addDeserializer(Instant.class, new InstantDeserializer());
module.addSerializer(byte[].class, new ByteArraySerializer());
module.addDeserializer(byte[].class, new ByteArrayDeserializer());
module.addSerializer(Buffer.class, new BufferSerializer());
module.addDeserializer(Buffer.class, new BufferDeserializer());
```
- We need to make sure that the Instant and byte[] serializer/deserializer does not conflict with the user's code.
- Testing can be done by registering a special module and use `Json.decode` and `Json.encode` methods.

Related to #14779

**Comment by geoand** [comment]
I'll start looking into this today

**Comment by geoand** [comment]
@cescoffier I can't seem to build the `vertx4-snapshot` branch.

Is there anything I need to do?

**Comment by cescoffier** [comment]
the "quickly" does not pass?

**Comment by geoand** [comment]
Nope, I get:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1:compile (default-compile) on project quarkus-vertx-web: Compilation failure: Compilation failure: 
[ERROR] /home/gandrian/projects/redhat/quarkus/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/Route.java:[9,34] cannot find symbol
[ERROR]   symbol:   class Routes
[ERROR]   location: @interface io.quarkus.vertx.web.Route
[ERROR] /home/gandrian/projects/redhat/quarkus/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/Route.java:[131,5] cannot find symbol
[ERROR]   symbol:   class HandlerType
[ERROR]   location: @interface io.quarkus.vertx.web.Route
[ERROR] /home/gandrian/projects/redhat/quarkus/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/Route.java:[97,5] enum io.quarkus.vertx.web.Route.HttpMethod is already defined in class io.quarkus.vertx.web.Route
[ERROR] /home/gandrian/projects/redhat/quarkus/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/Route.java:[79,13] cannot find symbol
[ERROR]   symbol: class Routes
[ERROR] -> [Help 1]

```

**Comment by geoand** [comment]
Nevermind, my local branch had some extra commits for some reason...

**Comment by geoand** [comment]
@cescoffier I have this ready, would you like me to push into the `vertx4-snapshot` branch?

**Comment by cescoffier** [comment]
Go ahead @geoand 

Sorry, I'm 8h behind schedule...

**Comment by geoand** [comment]
Don't even think about it!

Done :)
