### ISSUE TITLE
Quarkus AWS S3AsyncClient doesn't apply default connectionMaxIdleTime set by AWS

### ISSUE THREAD

**Issue by AndreiYu** [quarkusio/quarkus#15048]
**Describe the bug**
[There was a bug in AWS SDK2.0+ S3AsyncClient ](https://github.com/aws/aws-sdk-java-v2/issues/1122)that caused Netty 'stale' connections to be picked up and reaped by `IdleConnectionReaper` when multiple concurrent async calls were performed. SDK picked up 3 threads that were to be killed by the reaper one by one and it caused retry policy to fail (3 unsuccessful attempts) and fire with  

`software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Server failed to send complete response: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Server failed to send complete response`

The solution AWS team introduced was to decrease `connectionMaxIdleTime` to 5 sec, so AWS always peaked up fresh connections.

**Expected behavior**
Default AWS SDK parameters apply by default for AWS SDK clients

**Actual behavior**
Quarkus overrides default parameters for AWS SDK clients that causes AWS S3AsyncClient to fail again despite the fact that bug was fixed.

```
io.quarkus.amazon.common.runtime.NettyHttpClientConfig

    @ConfigItem(defaultValue = "60S")
    public Duration connectionMaxIdleTime;

```

**To Reproduce**

```
try (S3AsyncClient client = S3AsyncClient.create()) {
    client.putObject(r -> r.bucket("tmp.millems").key("test"), AsyncRequestBody.fromBytes("".getBytes())).join();

    for (int i = 0; i < 1000; ++i) {
        System.out.println("Iteration " + i);
        Path outputPath = Paths.get("/tmp/foo");
        Files.deleteIfExists(outputPath);
        client.getObject(r -> r.bucket("tmp.millems").key("test"), AsyncResponseTransformer.toFile(outputPath)).join();
    }
}
```

1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**

 - GraalVM version (if different from Java): 20.2.0.r11
 - Quarkus version or git rev: 1.10.5

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/15087 should fix it.
