### ISSUE TITLE
Maven phase process-classes is not executed as part of quarkus:dev goal

### ISSUE THREAD

**Issue by martinoneutrino** [quarkusio/quarkus#15049]
**Describe the bug**
Classes are left without byte-code enhancements after compilation, leading to errors at runtime, such as missing interfaces and `ExceptionInInitializerError`

**Expected behavior**
Using the `quarkus:dev` goal, including for hot-reload, will execute the `process-classes` phase so that classes are fully processed before being used at runtime.

**Actual behavior**
The `quarkus:dev` lifecycle appears to finish at the `compile` phase, and so byte-code enhancements that run during `process-classes` are never performed, and classes are incompletely formed.

**To Reproduce**
[Fork of quickstarts getting-started project](https://github.com/martinoneutrino/quarkus-quickstarts/tree/master/getting-started) showing issue.

- Compare class output of `.\mvnw quarkus:dev` to class output of `.\mvnw process-classes`

**Configuration**
As shown in linked project, added eBean to pom.xml. This a project that uses the `process-classes` phase.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: _Microsoft Windows [Version 10.0.18363.1377]_
 - Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: _1.11.3.Final_
 - Build tool
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T09:06:16-06:00)
Maven home: C:\Users\martin\.m2\wrapper\dists\apache-maven-3.6.2-bin\795eh28tki48bv3l67maojf0ra\apache-maven-3.6.2
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**
### .\mvnw quarkus:dev
```
[INFO] Scanning for projects...
[INFO] --- tiles-maven-plugin: Injecting 1 tiles as intermediary parent artifacts for org.acme:getting-started...
[INFO] Mixed 'org.acme:getting-started:1.0.0-SNAPSHOT' with tile 'io.ebean.tile:enhancement:12.6.2' as its new parent.
[INFO] Mixed 'io.ebean.tile:enhancement:12.6.2' with original parent '(no parent)' as its new top level parent.
[INFO]
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.11.3.Final:dev (default-cli) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\quarkus-quickstarts\getting-started\target\classes
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
```
This results in an incomplete _GreetingTest.class_ file that decompiles to:
```
// 
// Decompiled by Procyon v0.5.36
// 

package org.acme.getting.started;

import javax.persistence.Table;
import javax.persistence.Entity;

@Entity
@Table(name = "greeting")
public class GreetingTest
{
    public void setName(final String name) {
    }
}
```
### .\mvnw process-classes
```
[INFO] Scanning for projects...
[INFO] --- tiles-maven-plugin: Injecting 1 tiles as intermediary parent artifacts for org.acme:getting-started...
[INFO] Mixed 'org.acme:getting-started:1.0.0-SNAPSHOT' with tile 'io.ebean.tile:enhancement:12.6.2' as its new parent.
[INFO] Mixed 'io.ebean.tile:enhancement:12.6.2' with original parent '(no parent)' as its new top level parent.
[INFO]
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ getting-started ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\quarkus-quickstarts\getting-started\target\classes
[INFO]
[INFO] --- ebean-maven-plugin:12.6.2:enhance (main) @ getting-started ---
[INFO] classSource=C:\quarkus-quickstarts\getting-started\target\classes  transformArgs=debug=0
[INFO] packages entity:[org.acme.getting.started]  transactional:[]  querybean:[]  profileLocation:true
[INFO] loaded resources: [META-INF/ebean-generated-info.mf]
[INFO]      Entities (1)  pkgs[org/acme/getting/started] beans[GreetingTest]
[INFO]    QueryBeans (1)  pkgs[org/acme/getting/started/query] beans[QGreetingTest]
[INFO] Transactional (0)  pkgs[] beans[]
[INFO] Query Callers (0)  pkgs[] beans[]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.121 s
[INFO] Finished at: 2021-02-12T12:18:53-07:00
[INFO] ------------------------------------------------------------------------
```
This results in an expected _GreetingTest.class_ file that decompiles to:
```
// 
// Decompiled by Procyon v0.5.36
// 

package org.acme.getting.started;

import io.ebean.bean.EntityBeanIntercept;
import javax.persistence.Table;
import javax.persistence.Entity;
import io.ebean.bean.EntityBean;

@Entity
@Table(name = "greeting")
public class GreetingTest implements EntityBean
{
    public static /* synthetic */ String[] _ebean_props;
    protected /* synthetic */ EntityBeanIntercept _ebean_intercept;
    
    public GreetingTest() {
        this._ebean_intercept = new EntityBeanIntercept((Object)this);
    }
    
    public void setName(final String name) {
    }
    
    static {
        GreetingTest._ebean_props = new String[0];
    }
}
```

**Comment by yhgillet** [comment]
I have the same problem with some `validate` phase plugin (the copy resources from maven-resources-plugin ). The plugin is not called from the `quarkus:dev` goal

**Comment by martinoneutrino** [comment]
I would say that `validate` is not an appropriate phase to copy resources. It should be in `process-resources`. See the [Maven lifecycle reference](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference).

**Comment by yhgillet** [comment]
yes the maven documentation gave the `validate` phase as an example by default , but it doesnt matter, as the `process-resources` phase plugins doesnt trigger also

**Comment by yhgillet** [comment]
> I would say that `validate` is not an appropriate phase to copy resources. It should be in `process-resources`. See the [Maven lifecycle reference](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference).

yes the maven documentation gave the `validate` phase as an example by default , but it doesnt matter, as the `process-resources` phase plugins doesnt trigger also

**Comment by famod** [comment]
@martinoneutrino Do you also see this problem _without_ `tiles-maven-plugin`?

**Comment by famod** [comment]
@yhgillet The ["standard" goal `resources`](https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html) _is_ called by `quarkus:dev`, but custom `copy-resources` executions are not.
What happens in your `copy-resources` execution?

@aloubyansky Not sure about this. A user could have multiple such executions and in theory, DevMojo would need to call them all (with the respective config).

**Comment by martinoneutrino** [comment]
@famod Thanks for the startup work around (`mvn process-classes quarkus:dev`). That takes care of the initial launch, but of course not the hot-reload that `quarkus:dev` uses to make development so easy...

**Comment by stuartwdouglas** [comment]
You will need to either write an EBean extension and tie into our class transformation or use the ebean-agent Javaagent to do the transformation. Maven is not involved in the hot reload process, so there is nothing that we can do here.

**Comment by famod** [comment]
Closing, see Stuart's explanation.
