### ISSUE TITLE
gRPC server not starting if proto grammar in maven dependency

### ISSUE THREAD

**Issue by jspasquali** [quarkusio/quarkus#15057]
In my setup, there are 2 maven modules:
* a maven module with the grammar of the service inside src/main/proto/service.proto
* a maven module with the gRPC implementation + dependency on the grammar module (containing generated java code).  The gRPC implementation is a simple class like in the grpc quickstart
```
@Singleton
public class HandlerService extends MutinyServiceGrpc.ServiceImplBase {
...
}
```

When compiling and running `java -jar target/my-app-1.0.0-SNAPSHOT-runner.jar`  the grpc server does not start, and grpc-server does not appear in the installed features:
```
2021-02-13 15:03:08,064 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, smallrye-context-propagation, vertx]
```

But if I remove the maven dependency on generated grammar and add the service.proto into the project itself, then the grpc server starts as expected:
```
2021-02-13 15:04:47,141 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-1) gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
2021-02-13 15:04:47,207 INFO  [io.quarkus] (main) Installed features: [cdi, grpc-server, mutiny, smallrye-context-propagation, vertx]
``` 

I would have expected the gRPC feature to be enabled as soon as a gRPC service implementation bean is present, but it seems it works differently. Am I missing something?  Should I add something to the project to make the gRPC feature enabled by quarkus?

**Environment**
 - Output of `uname -a` or `ver`: 
MINGW64_NT-10.0 NCEL77941 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
 - Output of `java -version`: 
java version "11.0.6" 2020-01-14 LTS                                                                                                                                                 Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)                                                                                                                            Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
 - Quarkus version or git rev:  1.11.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
Apache Maven 3.6.3

**Comment by michalszynkiewicz** [comment]
@jspasquali thanks for your report!
Is the service implementation class in your Quarkus project?

**Comment by jspasquali** [comment]
> @jspasquali thanks for your report!
> Is the service implementation class in your Quarkus project?

Not sure if what you refer to service implementation class is the generated grpc services or the singleton implementation extending from it... I'll try to be more specific:
- In a first Maven "grammar" module : it contains only the .proto definitions;  the pom.xml has dependency on quarkus-grpc + the quarkus-maven-plugin with `generate-code` goal, so the deliverable contains the generated grammar and services.  This grpc API is actually more of a SPI, which can be implemented by multiple clients.
- In a second Maven "client impl" module : it is a quarkus project with dependency on previous grammar module + dependency on quarkus-grpc.  It contains the Singleton service implementation as shown in original post, that extends from the generated `MutinyServiceGrpc.ServiceImplBase` coming from the dependency.

If my goal is to share the .proto definition, maybe I should change the approach and not deliver the generated grpc services in the "grammar" module but only deliver .proto files;  and generate grpc services in each "client impl" module?

**Comment by michalszynkiewicz** [comment]
I meant the singleton.

I think what you describe should work fine. Do you happen to have, or can prepare, a minimal reproducer? It would help me a lot in fixing the issue quickly.

**Comment by jspasquali** [comment]
Sure, I'll try to put together a minimal reproducer when possible

**Comment by michalszynkiewicz** [comment]
Thanks in advance :)

**Comment by jspasquali** [comment]
Here is a reproducer repo : https://github.com/jspasquali/quarkus-grpc-dep-issue
Thanks to have a look!

**Comment by michalszynkiewicz** [comment]
The details on what happens are that the `grpc-grammar` module doesn't have a Jandex index and the `grpc-service` module doesn't know that the implementation class is an implementation of (I think) `BindableService`, so it's not discovered.

To fix this, you need to have the `grpc-grammar` indexed. I think in this case the base way to do it is to add jandex-maven-plugin to it. 
You can find details on how to do it, and alternative solutions, here: https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module

**Comment by jspasquali** [comment]
Thanks, I forgot about this jandex thing... I tried with empty beans.xml and with jandex plugin, both are indeed valid solutions.
It is a bit unfortunate this deeper level of knowledge is needed for simple things, this jandex indexing is not something you typically understand by browsing a few quarkus guides!

**Comment by michalszynkiewicz** [comment]
True, it would be good to have this info in the gRPC guide. I added this to my todo list.

**Comment by nastra** [comment]
+1 on adding this to the gRPC guide. I ran into this problem and found this issue here and it can be fixed by https://github.com/quarkusio/quarkus/issues/15057#issuecomment-780506852

**Comment by nastra** [comment]
@michalszynkiewicz I opened https://github.com/quarkusio/quarkus/pull/19441 that updates the gRPC guide. Do you have some free cycles to review it?

**Comment by michalszynkiewicz** [comment]
@nastra thanks a lot :)
