### ISSUE TITLE
With 1.12.0.CR1 the runner jar is not generated

### ISSUE THREAD

**Issue by Legion2** [quarkusio/quarkus#15059]
**Describe the bug**
After updating to 1.12.0.CR1 `mvn package` does not generate the `...-runner.jar` file any more.
When using the option `-Dquarkus.container-image.build=false` the docker image can not be build because of the missing file.

**Expected behavior**
The runner jar is generated into `target/` when running `mvn clean && mvn package`.

**Actual behavior**
No runner jar is present in `target/` after running `mvn clean && mvn package`.

**To Reproduce**

1. run `mvn clean && mvn package`
3. there is no file in the `target/` dir

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10
 - Output of `java -version`: 
 ```
 openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.12.0.CR1`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
 Java version: 14.0.2, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**
The project uses Kotlin
With `1.11.3.Final` the file was generated in the same project.

**Comment by famod** [comment]
Quarkus 1.12 has switched to `fast-jar` packaging that has a different layout and jar file.
The details are here, including how to enable the old `legacy-jar` packaging (although you should consider making the move to `fast-jar`):
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12#fast-jar-as-default
