### ISSUE TITLE
Typo on DeploymentInjectionException

### ISSUE THREAD

**Issue by JohnneSouza** [quarkusio/quarkus#15066]
**Description**
The text message on the Exception read as follow:
_Failed to inject extension deplpyment dependencies_

**Implementation ideas**
It should instead be like:
_Failed to inject extension deployment dependencies_

The typo is on the **deployment** word.

**Comment by JohnneSouza** [comment]
I can open a Pull Request if necessary!

**Comment by geoand** [comment]
PRs welcome :)
