### ISSUE TITLE
@PermitAll and expired JWT

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#15065]
**Describe the bug**
I have a method annotated with @PermitAll property setting of smallrye.jwt.always-check-authorization=false.  When I submit a call to this method, I get a error stating the JWT is expired.

**Expected behavior**
Method to execute even with expired JWT since it is annotated as PermitAll

**Actual behavior**
Caused by: org.jose4j.jwt.consumer.InvalidJwtException gets thrown and message is that JWT is expired.

**To Reproduce**
1. annotate method with @PermitAll
2. set application.properties: smallrye.jwt.always-check-authorization=false
3. set jwt expiration to 120 seconds
4. Configure jwt to be http only cookie
5. Let jwt expire and submit request with JWT to method with @PermitAll

**Configuration**
```properties
smallrye.jwt.always-check-authorization=false

```

**Environment (please complete the following information):**
Java 11.0.7 Oracle
Quarkus 1.11.3
Builld tool Maven 3.6.3
MAC OSX

**Additional context**

**Comment by stuartwdouglas** [comment]
Can you try setting `quarkus.http.auth.proactive=false`. By default if a credential is present we will attempt to validate it, if this is set then we won't attempt to authenticate until it is actually required.

**Comment by sberyozkin** [comment]
@jefrog1844 Yes, as Stuart @stuartwdouglas suggested, please disable the proactive authentication.

`smallrye.jwt.always-check-authorization` is about controlling, for the cases when JWT may also be expected as a cookie, that JWT should be checked not only as a cookie but also as Authorization header value. Some users were expecting for a single endpoint to have JWT to be submitter either as a bearer or cookie token. It is a bit confusing but sometimes it is hard to capture the intention in a property name :-)

**Comment by sberyozkin** [comment]
I've just checked the docs and I believe `smallrye.jwt.always-check-authorization` is documented clearly enough...

**Comment by jefrog1844** [comment]
Stuart's recommendation of using the setting quarkus.http.auth.proactive=false works as I expect the application to behave.  And thanks for clarification on always-check-authorization.  Nice job guys!
