### ISSUE TITLE
Error in injection of RestClient in Kotlin constructor

### ISSUE THREAD

**Issue by seijikohara** [quarkusio/quarkus#15069]
**Describe the bug**
When injecting RestClient in the Kotlin constructor, an exception is raised and Quarkus fails to start.

**Expected behavior**
No exception is thrown and Quarkus starts.

**Actual behavior**
UnsatisfiedResolutionException is raised.

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type example.services.GeoService and qualifiers [@Default]
	- java member: example.resources.GeoResource#<init>()
	- declared on CLASS bean [types=[java.lang.Object, example.resources.GeoResource], qualifiers=[@Default, @Any], target=example.resources.GeoResource]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=example.services.GeoService, qualifiers=[@org.eclipse.microprofile.rest.client.inject.RestClient, @Any]]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:237)
```

**To Reproduce**

- RestClient

```kotlin
package example.services

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.PathParam
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@RegisterRestClient
interface GeoService {

    @GET
    @Path("/{ipAddress}")
    @Produces(MediaType.APPLICATION_JSON)
    fun getGeo(@PathParam("ipAddress") ipAddress: String): Map<String, Any?>

}
```

- Resource that injects RestClient

```kotlin
package example.resources

import example.services.GeoService
import javax.inject.Inject
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.PathParam
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@Path("/api/geo/{ipAddress}")
@Produces(MediaType.APPLICATION_JSON)
class GeoResource @Inject constructor(val geoService: GeoService) {

    @GET
    fun getGeo(@PathParam("ipAddress") ipAddress: String): Response {
        return Response(geoService.getGeo(ipAddress))
    }

    data class Response(val geo: Map<String, Any?>?)

}
```

1. `./gradlew quarkusDev`
2. `UnsatisfiedResolutionException` is raised.

**Configuration**

```properties
example.services.GeoService/mp-rest/url=http://ip-api.com/json
example.services.GeoService/mp-rest/scope=javax.inject.Singleton
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin MacBook-Pro-Seiji.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `openjdk version "11.0.9.1" 2020-11-04 LTS`
 - GraalVM version (if different from Java): openjdk version "11.0.9.1" 2020-11-04 LTS
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.5.1

**Additional context**

None.

**Comment by glefloch** [comment]
@seijikohara could you try to add the `@RestClient` qualifier in the constructor where the rest client is injected, such as:
`class GeoResource constructor(@RestClient val geoService: GeoService)`

**Comment by seijikohara** [comment]
@glefloch No exceptions were thrown and it worked fine.
Thank you for your advice.

**Comment by glefloch** [comment]
If everything is fine. I close this issue.

**Comment by mkouba** [comment]
I think that it's a known limitation of RESTEasy "classic" and it should work just fine with RESTEasy Reactive. 

CC @geoand

**Comment by geoand** [comment]
Constructor injection also works in RESTEasy Classic, unless you try to do it in classes annotated with `@Provider`. In RESTEasy Reactive it works in all cases

**Comment by MartinX3** [comment]
Same issue here with Reactive, the `@RestClient` was needed while using constructor injection in kotlin.

**Comment by isadounikau** [comment]
@geoand the injection issue for kotlin is unfortunately presented in https://quarkus.io/guides/rest-client-reactive

**Comment by geoand** [comment]
Please attach a sample project that exhibits the problem and I'll have a look

**Comment by isadounikau** [comment]
Please find an example in the next archive [Archive.zip](https://github.com/quarkusio/quarkus/files/8502356/Archive.zip)

**Comment by geoand** [comment]
Everything works just fine if you use `quarkus-resteasy-reactive-jackson` instead of `quarkus-resteasy-jackson`
