### ISSUE TITLE
timezone setting for jackson in application.properties

### ISSUE THREAD

**Issue by junk123321** [quarkusio/quarkus#15077]
**Description**
I would like to set jackson timezone to make Json output displayed with users' timezone. Here request a configuration similar to "spring.jackson.time-zone" in application.properties. It is much convenient than annotation setting like "@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Tokyo")" . As the latter one needs to be set for each date field. Thanks much!

**Comment by geoand** [comment]
This seems like a reasonable request to me.

The only complication I see is that in order to preserve the `static-init` semantics of the `ObjectMapper` bean, we would need to make this property a build-time property (which is not ideal, but better than nothing...).

@gsmet is that OK with you?

**Comment by gsmet** [comment]
@geoand I think we can live with it. If you use annotations, it will be defined at build time anyway.

**Comment by geoand** [comment]
OK, I'll add this today
