### ISSUE TITLE
allow dynamically setting flyway location

### ISSUE THREAD

**Issue by HelvetiaAppDev** [quarkusio/quarkus#15072]
**Description**
Currently the only way to set the flyway locations is through the built-time property `quarkus.flyway.locations`.
However it would be helpful to be able to set it at run-time.
One possible use case is using the same jar for multiple stages and one of the stages needs testdata that should be inserted with flyway.
Would this be possible? It was possible with thorntail and as far as I know all resources stay in the jar anyway so accessing them at runtime should be possible.

**Implementation ideas**
Either make `quarkus.flyway.locations` a run-time configuration or allow dynamically configuring flyway in the code to start a manual migration.

**Comment by geoand** [comment]
We don't really want to do this, as we use the fact that `locations` is a build time property to optimize the startup time and memory usage of Quarkus when the Flyway extension is present.

**Comment by flo-ryan** [comment]
@geoand so there is no way to specify this property at runtime?
To me it definitely seems like a reasonable and sometimes "necessary" feature to be able to set different locations at runtime.

**Comment by geoand** [comment]
Yes that is correct, it's not possible to set at runtime

**Comment by flo-ryan** [comment]
@geoand hm, that's a pity. And also not entirely logical to me since the files are packaged in the jar anyways - but I also don't know the workings of Quarkus very well.
Is there maybe another option to cover that use case? 
Using Flyway "natively" without the Quarkus plugin probably...?

**Comment by geoand** [comment]
I'm no flyway expert, so I can't really say

**Comment by alessandroAmedei** [comment]
> @geoand hm, that's a pity. And also not entirely logical to me since the files are packaged in the jar anyways - but I also don't know the workings of Quarkus very well.
> Is there maybe another option to cover that use case?
> Using Flyway "natively" without the Quarkus plugin probably...?

I agree, this means that if I have multiple enviroments with different datasources, I have to build the project multiple times.

**Comment by montanajava** [comment]
If we build a project multiple times, we are really taking a step backwards. That is an inviolable principle at least where I work. The fact that Flyway supports different parameters based on the environment is critical. We are gutting a core feature of Flyway if this cannot work.

**Comment by lxngr** [comment]
Also would highly appreciate if `quarkus.flyway.locations` could be changed at runtime (e.g. using profiles). It would be the easiest way for applying different migrations in different environments or for test data seeding.

The other available options (`quarkus.hibernate-orm.sql-load-script` and `quarkus.datasource.devservices.init-script-path`) are tricky to use and, at least in my opinion, are not really an alternative.

Any change of mind here yet, @geoand?

**Comment by geoand** [comment]
Not really

**Comment by lazyBisa** [comment]
Stumbled over the same issue today. Have to build an extra container image with flyway cli and fiddle the migrations in there just because our database design has two small oddities that require us to sometimes seed it with different data on different environments. 

May I inquire how exactly quarkus optimizes startup time and memory? And why it was judged such a massive improvement that the flexibility was sacrificed? 

Really considering to skip the quarkus way and just use the native flyway api.

**Comment by geoand** [comment]
> Stumbled over the same issue today. Have to build an extra container image with flyway cli and fiddle the migrations in there just because our database design has two small oddities that require us to sometimes seed it with different data on different environments.
> 
> May I inquire how exactly quarkus optimizes startup time and memory? And why it was judged such a massive improvement that the flexibility was sacrificed?
> 

https://github.com/quarkusio/quarkus/blob/ef974032b8df45c29e9338ebf5ff7bcfdce68284/extensions/flyway/deployment/src/main/java/io/quarkus/flyway/deployment/FlywayProcessor.java#L128

> Really considering to skip the quarkus way and just use the native flyway api.

That is certainly a worthwhile option
