### ISSUE TITLE
Improve documentation of Kafka configuration

### ISSUE THREAD

**Issue by bnjns** [quarkusio/quarkus#15078]
**Description**

We have recently integrated one of our products with Kakfa, by following this guide: https://quarkus.io/guides/kafka.

We found that configuring the service to use a local Kafka set up was relatively straightforward, but in production the Kafka cluster is hosted by Aiven and uses SSL authentication for the broker and HTTP basic authentication for the schema registry. We found this really hard to configure, as there doesn't seem to be any documentation on where to place the configuration values (either in the [Quarkus guide](https://quarkus.io/guides/all-config) or in the SmallRye docs).

We ended up having to experiment with various keys based on some old bug reports or StackOverflow questions, but even though it now appears to be working we're not 100% sure we've used the "correct" keys.

The docs for Kafka streams looks to be very detailed and outlines all of the config properties needed, but this is missing for the "standard" Kafka extension (it only contains a couple of config properties in its configuration section).

**Implementation ideas**

The normal Kafka guide should include a list of all the available configuration properties (both the Kafka connector's general config and the channel config), similar to the Kafka streams guide. If this is already documented by SmallRye then I think it would be fine to simply link to those docs so that you don't have to maintain a duplicate, but we really struggled to find anything for the connector.

**Comment by cescoffier** [comment]
All the properties are documented on SmallRye, so I can add a link. However, keeping the link right is going to be harder, as the URL includes the version.

I believe we should go with a link and a table with the main attributes
