### ISSUE TITLE
Quarkus Quartz tables could be created by default.

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15082]
## Description

When you are using Quarkus quartz extension, sometimes you want to persist your job history into a database (so could be shared between pods). However, with the current implementation, you have to [set up your schema](https://github.com/quarkusio/quarkus-quickstarts/blob/master/quartz-quickstart/src/main/resources/db/migration/V2.0.0__QuarkusQuartzTasks.sql) manually.

My suggestion is, when the developer has set the following properties:
```
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true
```
 Could be possible to create this required schema without any extra configuration and scripts?

**Comment by gsmet** [comment]
Given it's not a Quartz feature, I think we will have to live with it.
