### ISSUE TITLE
ApplicationScoped bean observing start/stop still observing even when mocked

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15083]
**Describe the bug**
I have an application scoped bean observing start:

```
@ApplicationScoped
public class SomeBean {
  protected void onStart(@Observes StartupEvent ev) {
    System.out.println("I'm here");
  }
}
```
I can of course see this hit the start method when the application starts.

In my QuarkusTests, I don't actually need/want the start to be hit.

If I use `@InjectMock SomeBean`, or create a `@Mock` replacement that overrides the start, I still see the original `onStart` being called.

**Expected behavior**
If you use `@InjectMock` or an alternative bean with `@Mock`, the original observes should not be called.

**To Reproduce**
See attached [observes.zip](https://github.com/quarkusio/quarkus/files/5982250/observes.zip)

**Environment (please complete the following information):**
Quarkus version 1.11.3.Final
Maven info:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.7-100.fc32.x86_64", arch: "amd64", family: "unix"

**Comment by FroMage** [comment]
I can confirm this behaviour.

**Comment by FroMage** [comment]
Is this @mkouba or @geoand territory?

**Comment by FroMage** [comment]
In the case of `@InjectMock` I confirm we get to `ArcContainerImpl.mockObserversFor`:

```java
    private void mockObserversFor(String beanIdentifier, boolean mock) {
        for (InjectableObserverMethod<?> observer : observers) {
            if (observer instanceof Mockable && beanIdentifier.equals(observer.getDeclaringBeanIdentifier())) {
                Mockable mockable = (Mockable) observer;
                if (mock) {
                    mockable.arc$setMock(null);
                } else {
                    mockable.arc$clearMock();
                }
            }
        }
    }
```

And it finds the observer bean and calls `mockable.arc$setMock(null);` but I am not sure how this should disable the observer.

**Comment by FroMage** [comment]
Actually, what I see is that application startup events are invoked before any `MockSupport` methods are called, so probably this is fired before all our observer mocking setup.

**Comment by FroMage** [comment]
Yes, startup events are fired by `QuarkusTestExtension` in:

```java
            runningQuarkusApplication = startupAction.run();
```

Way before we do the mock setup in before/after methods.

**Comment by FroMage** [comment]
Considering this call runs the startup actions, and returns us what we need to install the mocks:

```java
            Method pushContext = runningQuarkusApplication.getClassLoader().loadClass(MockSupport.class.getName())
                    .getDeclaredMethod("pushContext");
            pushContext.setAccessible(true);
            pushContext
                    .invoke(null);
```

That's a pretty big chicken/egg problem.

**Comment by geoand** [comment]
> Actually, what I see is that application startup events are invoked before any `MockSupport` methods are called, so probably this is fired before all our observer mocking setup.

Right, mocking doesn't really come into play with the events, so I don't think we can do much here...

**Comment by FroMage** [comment]
> Right, mocking doesn't really come into play with the events, so I don't think we can do much here...

According to @mkouba mocking a bean is supposed to disable all its observer methods.

**Comment by geoand** [comment]
Hm... I don't think that is the case because IIRC, all mocking does under the hood is add a field to the normal scoped bean that can be used as the "target" instead of the actual instance of the bean.
But there might be something I am missing

**Comment by FroMage** [comment]
Well, I think the logical intuitive behaviour is:

- For `@Mock`, overriding the event method should hijack the event, just like overriding other methods override behaviour. In practice, if I do that, _both_ methods get called (supertype and mock type). Yeah, that's just super weird.
- For `@InjectMock`, the event method should be a noop just like very other bean method, at least until we can define what behaviour it should have with `Mockito`. In practice, it's not.

So this is not working according to intuition.

**Comment by mkouba** [comment]
> > Right, mocking doesn't really come into play with the events, so I don't think we can do much here...
> 
> According to @mkouba mocking a bean is supposed to disable all its observer methods.

It does but `StartupEvent` is a bit special because it's fired before the mock is created. It's fired when the app starts.

**Comment by geoand** [comment]
So is there a way forward @mkouba ?

**Comment by shawkins** [comment]
My workaround is to use PostConstruct/PreDestroy with trivial usage of the bean in question in the QuarkusApplication run.

**Comment by stuartwdouglas** [comment]
Maybe we just need some way to disable StartupEvent or @Startup beans being created when running tests?

**Comment by mkouba** [comment]
> Maybe we just need some way to disable StartupEvent or @startup beans being created when running tests?

We could add a config property to disable the `LifecycleEventRunner.fireStartupEvent()` completely but I'm not so sure we should do this by default. Some extensions perform some important initialization logic there and the same might apply to some application classes.

BTW it's possible to "disable" the observer logic for tests like this:
```java
void onStart(@Observes StartupEvent event, LaunchMode mode) {
 if (mode != TEST) {
   // do something...
 }
}
```
But it's not very nice of course...

**Comment by stuartwdouglas** [comment]
I was thinking of basically doing that but via annotation, although unless we get more requests for this we should probably hold off for now.

**Comment by FroMage** [comment]
@mkouba adding test logic in real beans makes it hard to write one test that relies on the startup event not being fired and another that does. That makes it hard to isolate test behaviour.

@stuartwdouglas something like this?

```
@QuarkusTest
@DisableStartupEvents
public class MyTest {
 @InjectMock
 MyBean bean b;

 ...
}
```

**Comment by mkouba** [comment]
> @mkouba adding test logic in real beans makes it hard to write one test that relies on the startup event not being fired and another that does. That makes it hard to isolate test behaviour.

Sure. That's why I wrote it's not very nice ;-)

> 
> @stuartwdouglas something like this?
> 
> ```java
> @QuarkusTest
> @DisableStartupEvents
> public class MyTest {
>  @InjectMock
>  MyBean bean b;
> 
>  ...
> }
> ```

Again, I don't think we could just skip the event completely. We could disable the app observers though and restart the app like we do for `@TestProfile`. Actually, could we make it part of the `QuarkusTestProfile`?

**Comment by geoand** [comment]
> Again, I don't think we could just skip the event completely. We could disable the app observers though and restart the app like we do for `@TestProfile`. Actually, could we make it part of the `QuarkusTestProfile`?

That sounds reasonable to me

**Comment by FroMage** [comment]
To me too.

**Comment by famod** [comment]
Could we also log a warning/info in case a user mocks a bean with such an observer method but does *not* use a profile? Or do you think it's too invasive?

**Comment by mkouba** [comment]
@FroMage @geoand @famod @shawkins @stuartwdouglas Here's a draft PR: https://github.com/quarkusio/quarkus/pull/15144

At the moment  the tests are missing.

**Comment by dvsingh9** [comment]
> > Maybe we just need some way to disable StartupEvent or @startup beans being created when running tests?
> 
> We could add a config property to disable the `LifecycleEventRunner.fireStartupEvent()` completely but I'm not so sure we should do this by default. Some extensions perform some important initialization logic there and the same might apply to some application classes.
> 
> BTW it's possible to "disable" the observer logic for tests like this:
> 
> ```java
> void onStart(@Observes StartupEvent event, LaunchMode mode) {
>  if (mode != TEST) {
>    // do something...
>  }
> }
> ```
> 
> But it's not very nice of course...

Works fine but that's not proper way to do it.

**Comment by mkouba** [comment]
> Works fine but that's not proper way to do it.

Have you tried `quarkus.arc.test.disable-application-lifecycle-observers=true`?

**Comment by franck102** [comment]
Not sure why the thread focusses on startupEvent, but the issue exists for any CDI event, I don't think fixes that focus on lifecycle events are appropriate.

```
public void cdiInvoiceFinalized(@Observes TenantMessage message)
    {
       handleMessage(message);
    }
```

I have a Mock test bean that subclasses the application bean to just overrides the handleMessage, and currently two events are dispatched - one to the mock bean but also one to the application bean.

I will have to disable the application bean I guess - and btw that's where an @UnlessBuildProfile("test") would be great.

**Comment by mkouba** [comment]
> Not sure why the thread focusses on startupEvent, but the issue exists for any CDI event, I don't think fixes that focus on lifecycle events are appropriate.

Well, because that was the ogirinal problem - see the description of this issue. Also startup event is a bit special because it's fired by the container, and not from user code.

> 
> ```
> public void cdiInvoiceFinalized(@Observes TenantMessage message)
>     {
>        handleMessage(message);
>     }
> ```
> 
> I have a Mock test bean that subclasses the application bean to just overrides the handleMessage, and currently two events are dispatched - one to the mock bean but also one to the application bean.

That's expected. Mock beans are usually `@Alternative`s and alternatives do not disable the original beans. It merely affects injection/lookup. In CDI full you can use specialization to completely override a second bean. But specialization is not supported in Quarkus.

> I will have to disable the application bean I guess - and btw that's where an @UnlessBuildProfile("test") would be great.

Yes, that should work.

**Comment by franck102** [comment]
> That's expected. Mock beans are usually `@Alternative`s and alternatives do not disable the original beans. It merely affects injection/lookup. In CDI full you can use specialization to completely override a second bean. But specialization is not supported in Quarkus.
> 

Ahh sorry then, maybe the doc could mention that for the readers less familiar with CDI. When I read "CDI alternatives to mock *out* a bean" or "override the bean you wish to mock" I assumed the original bean would be replaced.

Thanks!

**Comment by mkouba** [comment]
> > That's expected. Mock beans are usually `@Alternative`s and alternatives do not disable the original beans. It merely affects injection/lookup. In CDI full you can use specialization to completely override a second bean. But specialization is not supported in Quarkus.
> 
> Ahh sorry then, maybe the doc could mention that for the readers less familiar with CDI. When I read "CDI alternatives to mock _out_ a bean" or "override the bean you wish to mock" I assumed the original bean would be replaced.

Well, yes, it's a standard behavior. Would you care to update the docs and send a pull request?
