### ISSUE TITLE
Vert.x 4 - OICD

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15084]
**Description**

The OICD integration is taking more time than anticipated, as there is an ongoing rewrite of the extension using the WebClient directly, instead of Vert.x OAuth.

This task tracks some of the work that needs to be done:

- [x] Re-enable `io.quarkus.it.keycloak.BearerTokenAuthorizationTest`
- [x] Re-enable `io.quarkus.it.keycloak.OidcClientTest`
- [x] Re-enable `io.quarkus.it.keycloak.CodeFlowTest`
- [x] Re-enable `io.quarkus.it.keycloak.BearerTokenAuthorizationTest` (from Multi-Tenant OpenID Connect Adapter)
- [x] Re-enable `io.quarkus.it.keycloak.ServicePublicKeyTestCase`
- [x] Re-enable `BearerOpaqueTokenAuthorizationTest` (from oidc-wiremock)
- [x] Re-enable `BearerTokenAuthorizationTest` (from oidc-wiremock)

**Comment by sberyozkin** [comment]
@cescoffier I'm focusing on this migration now

**Comment by cescoffier** [comment]
Thanks @sberyozkin!

I disabled the test to gets the build a bit further and see if the next modules are going to be full of surprises...

**Comment by famod** [comment]
@cescoffier

> I disabled the test to gets the build a bit further

FWIW, you could also set `-Dmaven.test.failure.ignore=true` and then grep the console output for `<<<`. (or grep the test reports)

**Comment by cescoffier** [comment]
@famod it's what we used (-fae) but we want to be as close as possible to the original build.

**Comment by sberyozkin** [comment]
See https://github.com/quarkusio/quarkus/commit/f01686480dd97dd07e68e1ff9eb8c7b5d9d510f8 and https://github.com/quarkusio/quarkus/commit/46008fe6e961e8e17d944852f8e3aafeb6d680c3
