### ISSUE TITLE
Quarkus depending on maven-compiler-plugin version 3.8.0-jboss-2

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#1508]
Version `3.8.0-jboss-2` is not available in Maven Central, so this dependency is having us require usage of the JBoss Maven repository.

I'm confident there was a good reason to choose this version, hoping others will comment on our options.

Related: should we replace the parent org.jboss:jboss-parent:32 with a quarkus alternative so to make it easier to make such adjustments?

**Comment by cescoffier** [comment]
@Sanne I would really like removing our dependency on jboss-parent (we would gain in flexibility). 

@stuartwdouglas @dmlloyd do you remember why we are using this compiler version?

**Comment by Sanne** [comment]
@cescoffier +1 . David pointed me to https://issues.apache.org/jira/browse/MCOMPILER-320

**Comment by dmlloyd** [comment]
> @Sanne I would really like removing our dependency on jboss-parent (we would gain in flexibility). 

I disagree.  In what way would we gain flexibility?  It seems to me we'd just end up reimplementing the whole thing.
