### ISSUE TITLE
Flyway with Dockerizing Quarkus with Quartz and MySQL

### ISSUE THREAD

**Issue by myassine2** [quarkusio/quarkus#15099]
**Describe the bug**
I am trying to create a Quarkus container that has Quartz and I want to persist Quartz jobs. As such, I have to use the flyway to create the Quartz database. When running the project normally through IDE, it works great. When running through docker, the flyway fails to connect to the database.

**Expected behavior**
When running the docker containers, flyway should be able to connect to the database and create the needed tables.

**Actual behavior**
When running the docker containers, flyway is unable to connect to the database due to a certificate error.

**To Reproduce**
[dbtest.zip](https://github.com/quarkusio/quarkus/files/5987045/dbtest.zip)

1. Install docker and docker-compose
2. Follow the steps in DockerFile.fast-jar file to build the maven project.
3. In the root directory, run `docker-compose build`.
4. Finally run `docker-compose up`.
5. Any changes done in the properties file or .env, you have to `docker-compose down` and `docker-compose build` again.

**Configuration**
.env file:
```properties
DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/qrtz_notification
QUARTZ_STORE_TYPE=db
DATASOURCE_DB_KIND=mysql
FLYWAY_MIGRATE_AT_START=true
FLYWAY_DEFAULT_SCHEMA=qrtz_notification
FLYWAY_CLEAN_AT_START=true
_DEV_DATASOURCE_USERNAME=root
_DEV_DATASOURCE_PASSWORD=root
```
Properties file:
```
quarkus.datasource.db-kind=${DATASOURCE_DB_KIND}
quarkus.datasource.username=${DATASOURCE_USERNAME}
quarkus.datasource.password=${DATASOURCE_PASSWORD}
quarkus.datasource.jdbc.url=${DATASOURCE_JDBC_URL}

quarkus.flyway.migrate-at-start=${FLYWAY_MIGRATE_AT_START}
quarkus.flyway.schemas=${FLYWAY_DEFAULT_SCHEMA}

quarkus.flyway.clean-at-start=${FLYWAY_CLEAN_AT_START}
quarkus.quartz.store-type=${QUARTZ_STORE_TYPE}
```
**Screenshots**
quarkus    | 2021-02-16 07:24:22,429 ERROR [io.qua.run.Application] (main) Failed to start application (with profile dev): javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
quarkus    | 	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
quarkus    | 	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
quarkus    | 	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:221)
quarkus    | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433)
quarkus    | 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
quarkus    | 	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317)
quarkus    | 	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
quarkus    | 	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97)
quarkus    | 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:333)
quarkus    | 	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167)
quarkus    | 	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350)
quarkus    | 	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
quarkus    | 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
quarkus    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
quarkus    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
quarkus    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
quarkus    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
quarkus    | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
quarkus    | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
quarkus    | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:434)
quarkus    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
quarkus    | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
quarkus    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
quarkus    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
quarkus    | 	at java.base/java.lang.Thread.run(Thread.java:834)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux myassine-Lenovo-ideapad-110-15ISK 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 11.0.10
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.3
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by machi1990** [comment]
What happens when the datasource creds below
```
_DEV_DATASOURCE_USERNAME=root
_DEV_DATASOURCE_PASSWORD=root
```

are set without the profile prefix?

```
DATASOURCE_USERNAME=root
DATASOURCE_PASSWORD=root
``` 
?

**Comment by myassine2** [comment]
> What happens when the datasource creds below
> 
> ```
> _DEV_DATASOURCE_USERNAME=root
> _DEV_DATASOURCE_PASSWORD=root
> ```
> 
> are set without the profile prefix?
> 
> ```
> DATASOURCE_USERNAME=root
> DATASOURCE_PASSWORD=root
> ```
> 
> ?

Nothing, you may remove them. I copied these valued from another application.

**Comment by geoand** [comment]
In the interest of saving time, what

are the values 

```
quarkus.datasource.db-kind
quarkus.datasource.username
quarkus.datasource.password
quarkus.datasource.jdbc.url
```

when the container is built and when it is run?

**Comment by myassine2** [comment]
> In the interest of saving time, what are the values of
> 
> ```
> quarkus.datasource.db-kind
> quarkus.datasource.username
> quarkus.datasource.password
> quarkus.datasource.jdbc.url
> ```
> 
> when the container is built and when it is run?
Yes of course the values are as follows:

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/qrtz_notification
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=qrtz_notification
quarkus.flyway.clean-at-start=true
quarkus.quartz.store-type=db

**Comment by geoand** [comment]
I don't get how you are trying to run things. From the logs it looks like you are running Quarkus in dev mode, but your docker-compose file indicates that you have built a production jar and are running it

**Comment by myassine2** [comment]
Thank you so much for your support, it was an issue from my end.

**Comment by geoand** [comment]
Glad you figured it out :)
