### ISSUE TITLE
RESTEasy Reactive: Sub resource Path Params more than 2 levels back are not passed correctly

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#15114]
Describe the bug
Sub resource path params are not bound correctly in a scenario with more than two sub resource levels.
E.g. if path /trees/{treeId}/branches/{branchId}/leaves/{leafId} is handled by a sub resource "LeavesResource" which uses @PathParam("treeId") and @PathParam("branchId") and @PathParam("leafId") then treeId is not injected while the other two are. 

Expected behavior
Multiple levels should be supported. The correct behaviour is found in standard resteasy.

Actual behavior
The value is not injected causing difficult to track bugs.

To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

Configuration
Nothing abnormal

Screenshots
Run the reproducer to see failures. Change the pom to non-reactive mode and all tests pass

Environment (please complete the following information):
This is not environment-specific
999-SNAPSHOT and before

Additional context
NA

**Comment by geoand** [comment]
@stuartwdouglas mind taking a look at this one since you did most of the subresource stuff?

**Comment by stuartwdouglas** [comment]
I will have a look, however this particular bit was done by someone else :-)

https://github.com/quarkusio/quarkus/commit/c3ebc9adea635df73eb099c806b31812ac2e43e8

**Comment by geoand** [comment]
I must have erased it from my mind completely 🙈

**Comment by bcluap** [comment]
Thanks @stuartwdouglas @geoand . I've confirmed it's working even with 4 levels of resources.

**Comment by FroMage** [comment]
> I must have erased it from my mind completely see_no_evil

Hahaha, I'm pretty sure we talked about this commit at the time and I noted it was only for a single level ;) :ghost: :bug:

**Comment by FroMage** [comment]
https://github.com/quarkusio/quarkus/pull/13853#discussion_r543164320

**Comment by FroMage** [comment]
:rofl:

**Comment by FroMage** [comment]
But OK, I was wrong, I said we had to use a stack and @stuartwdouglas used a chained list ;)

**Comment by geoand** [comment]
Somehow I had completely forgotten about it...

It's all a blur!

**Comment by bcluap** [comment]
[image: image.png]

Looks like I'm a wildling :-)

**Comment by FroMage** [comment]
> Somehow I had completely forgotten about it...

TBH I don't have a clue how I could have remembered that and not what I did yesterday. I guess it's like those SMB secret blocks I still remember from childhood, there's special brain storage for random stuff.

**Comment by geoand** [comment]
I want a brain upgrade :P
