### ISSUE TITLE
Enhance builder image with extra tools

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus#1511]
As of today the current container image does not have maven and other tools to build the containers effectively i.e. there is a multi step process to build container images that has quarkus binary.

The https://github.com/redhat-developer-demos/quarkus-java-builder has been built to enhance the devx with the following features:

- maven, buildah and podman along with graal-rc12 are included by default 
- common maven options MAVEN_MIRROR_URL, proxy settings are cofigurable
- default build script that build the image using buildah ( no docker daemon), the default option is to use `-Pnative` profile
- the default script can be overridden 

The builder image also helps in deploying quarkus app to vanilla kuberntes  and knative service as well. The example https://github.com/redhat-developer-demos/quarkus-java-builder/tree/master/example shows how do zero touch quarkus deployment in to kubernetes 

CC: @cescoffier , @emmanuelbernard , @vorburger , @burrsutter

**Comment by cescoffier** [comment]
This is also related to the idea to push our docker image to Quay.io (need to investigate this).

**Comment by kameshsampath** [comment]
@cescoffier  - this can do all that is needed.  The `DESTINATION_NAME` parameter that you can set will determine where it needs to be pushed. e.g if I say `DESTINATION_NAME` as `quay.io/rhdevelopers/myapp` then its gets pushed there with only requirement that you need to have registry secrets configured. check the example out for more details. I am happy to fix anything that you find missing

**Comment by cescoffier** [comment]
When I said investigate it was more for me, as I never used Quay before.

**Comment by kameshsampath** [comment]
sorry @cescoffier - you comment seem to me like general more info kind of thing, thats why I popped with that answer.

**Comment by vorburger** [comment]
@kameshsampath FYI see also (my) related #1358 and #1390 (https://github.com/quarkusio/quarkus/compare/master...vorburger:issue-1390_dev-container) ...

**Comment by kameshsampath** [comment]
@vorburger  if you check my builder image i have made it to use buildah than using docker which speeds up the build, the only issue I see with s2i is that your entire builder image packs to be output which is not good , in this approach my end image is just 30mb with ubi base. 

Let me know your thoughts

**Comment by vorburger** [comment]
@kameshsampath I did have a closer look at it meanwhile, and [your quarkus-java-builder](https://github.com/kameshsampath/quarkus-java-builder) is cool! To me, given that it is Kubernetes Knative Build based, it is complementary to OpenShift S2I (Native #1358 & JVM https://github.com/quarkusio/quarkus-quickstarts/pull/81) and Dev #1390) - IMHO we should offer both, and let users and customers choose.

I'm not sure I would directly integrate it "as is" as a new builder image here in Quarkus Core, I think at least some of what you have done there (e.g. a buildah in container) would actually be great to instead contribute directly to upstream Knative Build / build-templates / Tekton? (Unless they already have that, I'm currently learning more about it myself.)

BTW: You do have a couple of nice tricks in _quarkus-java-builder_ (e.g. `HTTP_PROXY_*` and `MAVEN_MIRROR_URL`) which would be cool & very useful for customers to have in #1358 as well... if you have any interest, contributions from you in the form of new PRs improving #1358 with such features would certainly be very welcome! (Once #1358 is merged, I think @cescoffier will do that today or tomorrow.)

**Comment by kameshsampath** [comment]
@vorburger  thanks for the comments, I dont mind sending PR to the new Quarkus core image.  Let me know once you have it merged, I shall start sending PR's to it

**Comment by cescoffier** [comment]
That has been done.

**Comment by gsmet** [comment]
So let's close it :).
