### ISSUE TITLE
Hibernate Reactive component is missing the dependency to Quarkus-Mutiny

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#15111]
**Describe the bug**
Hibernate Reactive depends on Mutiny, but isn't using the `quarkus-mutiny` module; this implies it's missing the deployment module for Mutiny as well.

**Comment by cescoffier** [comment]
The quarkus-mutiny module also does the "infrastructure setup" (log, blocked thread checker, worker pool thingy). So you need to make sure you use quarkus-mutiny in your extension.

**Comment by DavideD** [comment]
Thanks, I will have a look in a bit

**Comment by Sanne** [comment]
@DavideD it's assigned to me.. sending a PR soon.

**Comment by DavideD** [comment]
Ah, sorry @Sanne, I didn't see it and thought you were on PTO.

Thanks

**Comment by Sanne** [comment]
thanks @DavideD :) I'll be away from tomorrow.
