### ISSUE TITLE
ServerExceptionMapper is not working expected in native image

### ISSUE THREAD

**Issue by queencge** [quarkusio/quarkus#15132]
ServerExceptionMapper is not working expected in native image
When I tested without native-image 
ServerExceptionMapper is called when it has exception and return proper value.

But after native-image, same call has just
{"error": null}

**Expected behavior**
Response with proper body

"error": {"method": "PUT","path": "/v1/users/send-reset-password-email","service": "core-identity-service","status": 400,"code": 2004,"description": "No user with email of ge.choi@vodafone.com.1","timestamp": "2021-02-17T13:30:23.715Z"}}

**Actual behavior**
{"error": null}

**To Reproduce**

```
    @ServerExceptionMapper({NotFoundException.class})
    public Response handleNotFoundException(NotFoundException notFoundException, HttpServerRequest httpServerRequest) {
        logger.error("notFoundException", notFoundException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(notFoundException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), 2004))
            .build();
    }
```

Call the service to have `NotFoundException` exception.

**Environment (please complete the following information):**
Java Version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

use below command to make native-image
mvn clean install -Pnative -Dquarkus.native.native-image-xmx=4g -DskipTests

**Comment by geoand** [comment]
Can you update the code to show what `buildErrorResponse` does?

**Comment by queencge** [comment]
public class ExceptionMappers {

    private final Logger logger = getLogger(getClass());

    @ServerExceptionMapper({IllegalStateException.class})
    public Response handleIllegalStateException(IllegalStateException illegalStateException, HttpServerRequest httpServerRequest) {
        logger.error("illegalStateException", illegalStateException);
        return Response
            .status(HttpResponseStatus.INTERNAL_SERVER_ERROR.code())
            .entity(buildErrorResponse(illegalStateException.getMessage(), httpServerRequest, HttpResponseStatus.INTERNAL_SERVER_ERROR.code(), ILLEGAL_SERVER_STATE.getCode()))
            .build();
    }

    @ServerExceptionMapper({IllegalArgumentException.class})
    public Response handleIllegalArgumentException(IllegalArgumentException illegalArgumentException, HttpServerRequest httpServerRequest) {
        logger.error("illegalArgumentException", illegalArgumentException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(illegalArgumentException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), ILLEGAL_INPUT_DATA.getCode()))
            .build();
    }

    @ServerExceptionMapper({ConnectException.class})
    public Response handleConnectException(ConnectException connectException, HttpServerRequest httpServerRequest) {
        logger.error("connectException", connectException);
        return Response
            .status(HttpResponseStatus.SERVICE_UNAVAILABLE.code())
            .entity(buildErrorResponse(connectException.getMessage(), httpServerRequest, HttpResponseStatus.SERVICE_UNAVAILABLE.code(), ILLEGAL_SERVER_STATE.getCode()))
            .build();
    }

    @ServerExceptionMapper({EmailException.class})
    public Response handleEmailException(EmailException emailException, HttpServerRequest httpServerRequest) {
        logger.error("emailException", emailException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(emailException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), 2002))
            .build();
    }

    @ServerExceptionMapper({TokenException.class})
    public Response handleTokenException(TokenException tokenException, HttpServerRequest httpServerRequest) {
        logger.error("runtimeException", tokenException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(tokenException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), 2003))
            .build();
    }

    @ServerExceptionMapper({NotFoundException.class})
    public Response handleNotFoundException(NotFoundException notFoundException, HttpServerRequest httpServerRequest) {
        logger.error("notFoundException", notFoundException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(notFoundException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), 2004))
            .build();
    }

    @ServerExceptionMapper({LimitExceededException.class})
    public Response handleLimitExceededException(LimitExceededException limitExceededException, HttpServerRequest httpServerRequest) {
        logger.error("limitExceededException", limitExceededException);
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(limitExceededException.getMessage(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), 2005))
            .build();
    }

    @ServerExceptionMapper({ConstraintViolationException.class})
    public Response handle(ConstraintViolationException constraintViolationException, HttpServerRequest httpServerRequest) {
        logger.error("ConstraintViolationException", constraintViolationException);
        StringBuilder message = new StringBuilder();
        Set<ConstraintViolation<?>> violations = constraintViolationException.getConstraintViolations();
        for (ConstraintViolation<?> violation : violations) {
            message.append(violation.getMessage().concat(";"));
        }
        return Response
            .status(HttpResponseStatus.BAD_REQUEST.code())
            .entity(buildErrorResponse(message.toString(), httpServerRequest, HttpResponseStatus.BAD_REQUEST.code(), DATA_CONSTRAINT_VIOLATION.getCode()))
            .build();
    }

    @ServerExceptionMapper({RuntimeException.class})
    public Response handleRuntimeException(RuntimeException runtimeException, HttpServerRequest httpServerRequest) {
        logger.error("runtimeException", runtimeException);
        return Response
            .status(HttpResponseStatus.INTERNAL_SERVER_ERROR.code())
            .entity(buildErrorResponse(runtimeException.getMessage(), httpServerRequest, HttpResponseStatus.INTERNAL_SERVER_ERROR.code(), UNKNOWN_SERVER_ERROR.getCode()))
            .build();
    }

    /**
     * @param exceptionMessage  exception Message
     * @param httpServerRequest get all request information
     * @param httpCode          HTTP Code which can be returned in HttpResponse
     * @param code              business defined error code, it is defined in this service
     * @return ErrorResponse for HTTP response
     */
    private ErrorResponse buildErrorResponse(String exceptionMessage, HttpServerRequest httpServerRequest, Integer httpCode, Integer code) {
        return new ErrorResponse.ErrorResponseBuilder()
            .withError(
                new ErrorBuilder()
                    .withDescription(exceptionMessage)
                    .withCode(code)
                    .withMethod(httpServerRequest.method().toString())
                    .withPath(httpServerRequest.path())
                    .withService("core-identity-service")
                    .withStatus(httpCode)
                    .withTimestamp(OffsetDateTime.now())
                    .build()
            )
            .build();
    }
}

**Comment by geoand** [comment]
And `ErrorResponse ` looks like?

**Comment by queencge** [comment]
```
public class ErrorResponse {
    private Error error;
// getter
// builder
}
public class Error {
    private String method;
    private String path;
    private String service;
    private Integer status;
    private Integer code;
    private String description;

 // getter
 // builder
```

**Comment by queencge** [comment]
when I tried to make Object to String

```

  ObjectMapper mapper = new ObjectMapper()
            .findAndRegisterModules()
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);


   String message = exceptionMessage;
        try {
            logger.error("before parse={}", message);
            message = mapper.writeValueAsString(errorResponse);
            logger.error("message={}", message);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

```

message is printed out like this.. {"error":null} . only that is happened in native-image

**Comment by geoand** [comment]
This is **not** a RESTEasy Reactive issue. 

The thing is that Quarkus has no way of knowing what type of entity you are returning and therefore cannot automatically make reflection work for that class in native mode.
To make the application work properly in native mode, you need to provide some hints manually by using `@RegisterForReflection` as is mentioned at https://quarkus.io/guides/rest-json#conclusion
