### ISSUE TITLE
Bean Validation on Vert.x Routes is not automatically mapped to JSON

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15159]
**Describe the bug**
When using constraints on param binding:

```
@Route(produces = "application/json")
Person createPerson(@NonNull @Param("id") String primaryKey) {
  // ...
}
```

And calling this route directly from a browser or curl with a wrong value, the output is not mapped to JSON. 

This is working fine when validating responses:

```
@Route
@Valid Uni<Person> createPerson(...) {
  // ...
}
```

If the returned person is not validated, now the output is properly mapped to JSON as expected. Moreover, I didn't need to set the `produces = "application/json"` in the `@Route` annotation. 

Note that as a workraround, the only way to make this work is to send the HTTP header "ACCEPT: application/json". 

When using resteasy jackson extension:

```
@Path("/rest-query")
public class QueryResource {
    @GET
    public Greeting getGreetingWithName(@Pattern(regexp = "ne.*") @NotNull @QueryParam("name") String name) {
        return new Greeting(name, "hi");
    }
}
```

This is also working as expected mapping the validation errors into JSON.

**Expected behavior**
It should map the constraint errors into JSON as done when validating responses and also using other Quarkus extensions like Resteasy.

**Actual behavior**
The constraint errors are always in HTML format unless you set the HTTP header "ACCEPT: application/json".

**Environment (please complete the following information):**
 - Output of `java -version`: 11
 - Quarkus version or git rev: 1.12.0.Final

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
Yes, it seems that the current behaior is not consistent. The `Accept: application/json` header is required when a constraint is violated; see for example: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/validation/SyncValidationTest.java#L48-L65. But it's not necessary when the returned object is not `String` or `Buffer`.
