### ISSUE TITLE
@QueryParam/@PathParam extraction as field on sub jaxrs resources do not work

### ISSUE THREAD

**Issue by franden** [quarkusio/quarkus#15167]
In case of usage of jaxrs [sub resources](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#sub_resources) the extraction of  @QueryParam/@PathParam on fields does not work. It works only as method parameter.
```
@RequestScoped
@Path("rest")
public class RootResource {

    @Inject
    ParameterResource parameterResource;

    @Path("parameter")
    public ParameterResource getParameterResource() {
        return parameterResource;
    }

}

@Dependent
public class ParameterResource {

    public static final String QUERY_PARAMETER = "queryParameter";
    public static final String PATH_PARAMETER = "pathParameter";

    //!!!!!  extraction does NOT work classQueryParameter is always null
    @QueryParam(QUERY_PARAMETER)
    String classQueryParameter;

    //!!!!!  extraction does NOT work classPathParameter is always null
    @PathParam(PATH_PARAMETER)
    String classPathParameter;

    @Path("{" + PATH_PARAMETER + "}")
    @Produces(MediaType.APPLICATION_JSON)
    @GET
    public String getParameter(
        //extraction WORKS
        @QueryParam(QUERY_PARAMETER) String methodQueryParameter,
        @PathParam(PATH_PARAMETER) String methodPathParameter) {
        System.out.println("getParameter called");
        return Json.createObjectBuilder()
            .add("classQueryParameter", firstNotNull(classQueryParameter, "")) 
            .add("classPathParameter", firstNotNull(classPathParameter, ""))
            .add("methodQueryParameter", firstNotNull(methodQueryParameter, ""))
            .add("methodPathParameter", firstNotNull(methodPathParameter, ""))
            .build().toString();
    }
}
```

Detailed example:
https://github.com/franden/quarkus_jwt_401_handling_issue_showcase/blob/2e50055fcc792b3c14886ce06611037f0da208a0/src/main/java/org/acme/rest/boundary/ParameterResource.java

Extraction of @QueryParam/@PathParam fields on normal jaxrs resource (WITHOUT sub resource) works as expected: [normal resource example](https://github.com/franden/quarkus_jwt_401_handling_issue_showcase/blob/2e50055fcc792b3c14886ce06611037f0da208a0/src/main/java/org/acme/rest/boundary/RootResource.java)

**To Reproduce**
1. checkout code
2. mvnw quarkus:dev
3. curl -X GET "http://localhost:8080/rest/parameter/parameter1?queryParameter=parameter2" -H  "accept: application/json"
4. check the response. classQueryParameter and classPathParameter are empty string, because the extraction resulted to null
``` 
{
  "classQueryParameter": "",
  "classPathParameter": "",
  "methodQueryParameter": "parameter2",
  "methodPathParameter": "parameter1"
}
```

**Comment by geoand** [comment]
cc @asoldano @rsearls

**Comment by geoand** [comment]
Does this work with RESTEasy Reactive?

**Comment by rsearls** [comment]
This is pre RESTEasy Reactive?

**Comment by geoand** [comment]
It is yeah, I'm just wondering whether RESTEasy Reactive already addresses it or not

**Comment by rsearls** [comment]
I have no idea.  resteasy has undergone major changes since this was filed.

**Comment by geoand** [comment]
Thanks for the update.

Let's close this if we don't get any feedback

**Comment by knuspertante** [comment]
@geoand 

Today I wanted to switch to resteasy-reactive but this error still exists (only in resteasy-reactive. resteasy-classic works just fine)

Object-Variables are always null

```java
@PathParam(PATH_PARAMETER)
String classPathParameter;
```

**Comment by knuspertante** [comment]
#27473

**Comment by sschellh** [comment]
Hi,

it seems like that problem still exists in Quarkus 2.16.6.

Using RESTeasy reactive, the @PathParam is not working on member variables in sub resources.

**Comment by geoand** [comment]
Can you open a new issue please and attach a sample project that exhibits the problematic behavior?

Thanks
