### ISSUE TITLE
application.yaml properties not injected with @ConfigProperty

### ISSUE THREAD

**Issue by Jeansen** [quarkusio/quarkus#15173]
**Describe the bug**
Confiugarion properties work fine with application.properties. But when using application.yaml in combination with the maven dependcy, then Annotations with @ConfigProperty no longer work. That is, configuration properties are no longer injected.

**Expected behavior**
Adding the maven dependency io.quarkus:quarkus-config-yaml and converting a simple application.properties to
application.yaml should inject configuration properties with @ConfigPropperty.

**Actual behavior**
Values no longer injected and - depending on the type - are null or 0 and tests now fail!

**To Reproduce**

1. Clone https://github.com/quarkusio/quarkus-quickstarts
2. Add Maven dependency 
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-config-yaml</artifactId>
</dependency>
```
to https://github.com/quarkusio/quarkus-quickstarts/blob/master/config-quickstart/pom.xml

4. Convert and rename https://github.com/quarkusio/quarkus-quickstarts/blob/master/config-quickstart/src/main/resources/application.properties to application.yaml

```
greeting:
    message: hello
    name: quarkus
```

5. Run `mvn clean package` for https://github.com/quarkusio/quarkus-quickstarts/tree/master/config-quickstart

**Comment by famod** [comment]
You need to use 2 spaces indentation, not 4.

**Comment by famod** [comment]
Just confirmed that it works with 2 spaces. Feel free to reopen in case you still think there is bug.

**Comment by Jeansen** [comment]
@famod Thanks for the quick reply. Is this by design? Shouldn't it be irrelevant what amount of spaces, as long as the indentation structure is fine? But even if it matters, then I would actually expect a parsing error telling me that the properties file is malformed. instead of silently ignoring values.

**Comment by famod** [comment]
Under the hood, Quarkus is using [`smallrye-config-source-yaml`](https://github.com/smallrye/smallrye-config/tree/master/sources/yaml) which is in turn using [`snakeyaml`](https://bitbucket.org/asomov/snakeyaml/src/master/).
So 2 spaces seems to be the default in snakeyaml and whether or not something is considered malformed is also up to snakeyaml.

There are, however, examples in the Quarkus docs, all with two spaces: https://quarkus.io/guides/config-reference#configuration-examples

/cc @radcortez

**Comment by famod** [comment]
@Jeansen https://github.com/quarkusio/quarkus-quickstarts/pull/784 will add a new `config-yaml-quickstart` to help others not falling into the same pit.

**Comment by gsmet** [comment]
> Thanks for the quick reply. Is this by design? Shouldn't it be irrelevant what amount of spaces is used, as long as the indentation structure is fine? But even if it matters, then I would actually expect a parsing error telling me that the properties file is malformed. instead of silently ignoring values.

@radcortez could you comment on this ^. I also think it's a pretty bad behavior. Either it works or it throws an error but it shouldn't be silently ignored given it's perfectly valid to indent with 4 spaces as long as you are consistent.

**Comment by radcortez** [comment]
Let me check what `snakeyaml` is doing.

**Comment by radcortez** [comment]
Hum, I was not able to reproduce this. I've added a test in SmallRye Config with multiple spaces. I've also tried with the described steps and it worked fine for me.

If I use a `tab` character you get the following error:

```
Caused by: org.yaml.snakeyaml.scanner.ScannerException:
while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 2, column 1:
    	message: hello
    ^
```

@famod did you also run into the error with 4 spaces?

**Comment by radcortez** [comment]
```console
🌀 git diff
diff --git a/config-quickstart/pom.xml b/config-quickstart/pom.xml
index f140cdf0..963683ef 100644
--- a/config-quickstart/pom.xml
+++ b/config-quickstart/pom.xml
@@ -29,6 +29,10 @@
   </dependencyManagement>

   <dependencies>
+    <dependency>
+      <groupId>io.quarkus</groupId>
+      <artifactId>quarkus-config-yaml</artifactId>
+    </dependency>
     <dependency>
       <groupId>io.quarkus</groupId>
       <artifactId>quarkus-resteasy</artifactId>
diff --git a/config-quickstart/src/main/resources/application.yaml b/config-quickstart/src/main/resources/application.yaml
index cba49f1b..f76b4cbd 100644
--- a/config-quickstart/src/main/resources/application.yaml
+++ b/config-quickstart/src/main/resources/application.yaml
@@ -1,3 +1,3 @@
-# Your configuration properties
-greeting.message = hello
-greeting.name = quarkus
+greeting:
+    message: hello
+    name: quarkus

🌀 mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:config-quickstart >---------------------
[INFO] Building config-quickstart 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ config-quickstart ---
[INFO] Deleting /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ config-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ config-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ config-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ config-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ config-quickstart ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.config.GreetingResourceTest
2021-02-19 19:44:03,396 INFO  [io.quarkus] (main) Quarkus 1.11.3.Final on JVM started in 1.270s. Listening on: http://localhost:8081
2021-02-19 19:44:03,398 INFO  [io.quarkus] (main) Profile test activated.
2021-02-19 19:44:03,398 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, resteasy]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.846 s - in org.acme.config.GreetingResourceTest
2021-02-19 19:44:04,496 INFO  [io.quarkus] (main) Quarkus stopped in 0.060s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ config-quickstart ---
[INFO] Building jar: /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target/config-quickstart-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:1.11.3.Final:build (default) @ config-quickstart ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target/config-quickstart-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 756ms
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ config-quickstart ---
[INFO] Installing /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/target/config-quickstart-1.0.0-SNAPSHOT.jar to /Users/radcortez/.m2/repository/org/acme/config-quickstart/1.0.0-SNAPSHOT/config-quickstart-1.0.0-SNAPSHOT.jar
[INFO] Installing /Users/radcortez/Code/open-source/quarkus-quickstarts/config-quickstart/pom.xml to /Users/radcortez/.m2/repository/org/acme/config-quickstart/1.0.0-SNAPSHOT/config-quickstart-1.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.310 s
[INFO] Finished at: 2021-02-19T19:44:06Z
[INFO] ------------------------------------------------------------------------

**Comment by famod** [comment]
> did you also run into the error with 4 spaces?

Hm, actually I might have missed that.

**Comment by famod** [comment]
@radcortez Thanks for checking! I must have missed reproducing properly the actual reported problem because I now have to confirm what you are seeing: 4 spaces work just fine! 🤦

**Comment by radcortez** [comment]
@Jeansen can you please check?

**Comment by Jeansen** [comment]
@radcortez OK, that's odd now. I've checked on my Linux system and it works fine with 4 spaces! But on my companies Laptop (MacBook Pro), it fails. I am not sure what's the issue, but so far I believe the error is on my side.

Thanks everyone for putting some time into this. Next time I will check better before opening an issue!

**Comment by radcortez** [comment]
As a note, my box is also a Mac and it worked fine. In the SR Config tests we run on both Linux and Windows, so it seems it is not something related with the OS.

**Comment by Jeansen** [comment]
@radcortez Thx for your feedback. I am quite sure I use the same general development setup on both systems, Linux and Mac, but like I said. It is probably more likely, that the error is on my side and currently sits in front of the scree ;-)
