### ISSUE TITLE
Vert.x Routes List/Set collections support

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15170]
**Description**
I would like to use some list or set collections as:

```
@Route(methods = HttpMethod.POST, path = "/validateFlightCodes")
void routeWithList(@Body List<String> list) {
    // ....
}
```

Or:

```
@Route(methods = HttpMethod.POST, path = "/validateFlightCodes")
void routeWithList(@Body Set<String> list) {
    // ....
}
```

At the moment, the only way to do this is using the `JsonArray` class:

```
@Route(methods = HttpMethod.POST, path = "/validateFlightCodes")
void routeWithList(@Body JsonArray list) {
    // .... the list is now here: flightCodes.getList()
}
```

But supporting List and Set collections provide a better developer experience.

**Implementation ideas**
It should be just a matter of detect the collection here: https://github.com/quarkusio/quarkus/blob/9ae27a3e9e6559c1a35ab7c47b3b142fa01e7cf7/extensions/vertx-web/deployment/src/main/java/io/quarkus/vertx/web/deployment/VertxWebProcessor.java#L1244 and use a proper method.

**Comment by geoand** [comment]
@Sgitario thanks for trying out Reactive Routes and adding ideas to improve it.

Have you tried RESTEasy Reactive? Asking because most (if not all ?) of the enhancement you have proposed around Reactive Routes are featured already present in RESTEasy Reactive :)

**Comment by cescoffier** [comment]
I agree with @geoand, for such kind of mapping feature, RESTEasy Reactive is better suited.

**Comment by gsmet** [comment]
OK, closing then.
