### ISSUE TITLE
Unable to add smallrye-reactive-messaging extension

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/quarkus#1518]
When trying to add the smallrye reactive messaging extension nothing happens.

**Comment by gsmet** [comment]
Could you maybe be a bit more explicit? What do you expect exactly?

**Comment by hguerrero** [comment]
`mvn quarkus:add-extension -Dextension="io.quarkus:quarkus-smallrye-reactive-messaging"` does nothing
expected to have the dependencies added to the pom.xml file

**Comment by gsmet** [comment]
It's `-Dextensions` plural form.

We had a discussion about that here https://github.com/quarkusio/quarkus/issues/1347 and, in master, we now support singular and plural form for both the command and the option.

We also improved error reporting.

**Comment by hguerrero** [comment]
working using the "extensions"
