### ISSUE TITLE
Tracing broken when mixing JAX-RS reactive with reactive routes

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkusio/quarkus#15182]
**Describe the bug**
When using both JAX-RS (reactive) resources and reactive routes (vertx @route), the generated trace_id seems to be broken on vertx threads after a JAX-RS reactive resources has been hit.
By broken i means that the trace_id on next requests hitting the reactive routes will be the same one as generated for the last JAX-RS resource request.

**Expected behavior**
Any request (no matter if it's a JAX-RS reactive / non reactive or reactive route setup with vertx should have a unique trace_id generated.

**Actual behavior**
As mentioned above, on certain circumstances with both JAX-RS reactive and reactive routes, the generated trace_id is broken for reactive routes, re-using the last one generated on same vertx-loop thread used by a JAX-RS reactive resource.
(please see my screenshot below for easier understanding)

**To Reproduce**

Here is a quick [reproducer maven project](https://github.com/nicolas-vivot/quarkus-tracing-reactive-routes-bug-reproducer).

The instructions to reproduce the bug can be found on the README.

**Configuration**

The configuration can be found on the linked reproducer.

**Screenshots**

![image](https://user-images.githubusercontent.com/79290619/108446291-3cc86800-72a1-11eb-80e5-21709985fed1.png)

**Environment:**
 - Java version: 11
 - Quarkus version: 1.11.3-Final
 - quarkus-smallrye-opentracing
 - quarkus-resteasy-reactive
 - quarkus-vertx-web

**Comment by nicolas-vivot** [comment]
Hi,

This bug make the next requests on reactive routes non-traceable. (well, traceable but all grouped together under the same trace_id)

Note: it's fine to change all JAX-RS reactive endpoint as reactive routes, but then what's the point of JAX-RS reactive ?
Note 2: i'm new to Quarkus, my apologies if this is an expected behavior. If so, do you mind explaining me the reason of this ?

**Comment by nicolas-vivot** [comment]
I added the branch 'datadog-tracer'. Same bug happens with Datadog as tracer implementation, so does not come from the tracer itself.

**Comment by nicolas-vivot** [comment]
Surprisingly, when switching to json logger (using logging-json extension) this bug does not happens.
It's coming from the log formatter.

**Comment by geoand** [comment]
I am a little confused by the description as you mention both RESTEasy Reactive and Reactive Routes.
Can you clarify what **exactly** the problem is?

**Comment by kenfinnigan** [comment]
Took a look at the reproducer, and it does include RESTEasy Reactive *and* Vert.x Web (for Reactive Routes).

Is this a bug with slf4j then if it's in the log formatter?

**Comment by nicolas-vivot** [comment]
@geoand 
Long story short: the problem is that the reported trace_id on the logs is wrong. This does not happen if i only hit the reactive routes. This happen as soon as i start to use the RESTEasy Reactive endpoints.

@kenfinnigan 
Might be, i'll have a closer look at it this weekend.

**Comment by Ladicek** [comment]
I didn't take a look yet, but I fear that we leak an active span somewhere. I hope I'm wrong :-) I also hope I'll find some time to take a look, but it will probably be on Mon. If someone beats me to it, that would be great :-)

**Comment by nicolas-vivot** [comment]
@kenfinnigan  I was wrong, my eyes was probably tired during my tests.. The generated trace_id is still wrong no matter the formatter.

And this is happening no matter the tracer implementation.
When i use Jaeger as backend, all traces start to stack on the same.
When i use Datadog, no trace is reported back (probably because it detects this as a duplicate and skip it)

So i am afraid this is on Quarkus/Smallrye part

**Comment by geoand** [comment]
Do things work properly if you use `@Blocking` on the JAX-RS method?

**Comment by nicolas-vivot** [comment]
Yes

**Comment by geoand** [comment]
The problem is that OpenTracing only works (AFAIK) with ThreadLocal in order to pass around the context. 
The solution to make it work properly with RESTEasy Reactive (or any web framework that doesn't use a thread per request) would be to have an SPI that pushes and pull information from the framework's context object.

@kenfinnigan this is something that OpenTelemetry will definitely need to take into account :).
I am not sure if OpenTracing can be retrofited to work as I explained (@Ladicek would probably know more)

**Comment by Ladicek** [comment]
Ah yeah, I guess the JAX-RS integration in SmallRye OpenTracing / OpenTracing Contrib (https://github.com/smallrye/smallrye-opentracing/blob/1.3.5/implementation/src/main/java/io/smallrye/opentracing/SmallRyeTracingDynamicFeature.java and https://github.com/opentracing-contrib/java-jaxrs) assumes thread-per-request implementation. Does maybe RESTEasy Reactive have a way to notify us when request processing starts / ends, so that we could activate / deactivate the span (which, I assume, would potentially be multiple times)?

**Comment by geoand** [comment]
There isn't something as explicit as you mention, but there is currently something limited that allows CDI Request scope to work in despite the presence of suspend / resume.

See: https://github.com/quarkusio/quarkus/blob/master/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/AbstractResteasyReactiveContext.java#L31-L32,

**Comment by Ladicek** [comment]
I see. One way or another, we'll need to have some sort of suspend / resume callbacks. CDI request scope is one user, OpenTracing active span is another. If this sounds dangerously close to MP Context Propagation with all its pitfalls and headaches, that's probably because it is.

**Comment by geoand** [comment]
Unfortunately yes...

**Comment by pat-karakun** [comment]
I stumbled over this issue while searching a solution for https://stackoverflow.com/questions/66478120/opentracing-context-not-propagated-on-quarkus-when-using-reactive-messaging. Might it be that these are related?

**Comment by Ladicek** [comment]
That doesn't seem related, at first glance.

**Comment by pat-karakun** [comment]
The reason I thought it might be related is @geoand's [comment](#issuecomment-783183023) above about OpenTracing using ThreadLocal. And ThreadLocal AFAIK doesn't work with reactive messaging, or does it?

But I don't want to hijack the conversation, if you disagree I'll open a separate issue.

**Comment by Ladicek** [comment]
Just found there's one other issue: even if we had suspend/resume callbacks that we would use to deactivate/reactivate the current span (I tried to prototype that using existing `ThreadSetupAction`s), there's one missing piece of the puzzle: when is the span (which is automatically started per MP OpenTracing rules with https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/ServerTracingFilter.java) finished? This https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/SpanFinishingFilter.java does that for servlet-based JAX-RS, but that's not the case with RESTEasy reactive -- and that's in fact the reason why the span leaks in the reproducer here. It's just never closed.

**Comment by geoand** [comment]
So do we need something specific to RESTEasy Reactive?

**Comment by Ladicek** [comment]
Aaaaaaaa ... I think so.

**Comment by geoand** [comment]
Are you on it or do you want me to look at it at some point?

**Comment by Ladicek** [comment]
I just wanted to take a quick look and see what I can do. Not much :-) I'm not planning to do any significant work on this. Also, I know @kenfinnigan has been deemphasizing OpenTracing in favor of OpenTelemetry, so not sure if this is even worth it.

**Comment by geoand** [comment]
But wouldn't a solution for OpenTracing be closely applicable to what might need to be done for OpenTelemetry?

**Comment by kenfinnigan** [comment]
Not necessarily, I'm hoping to work on OpenTelemetry and Resteasy Reactive next week

**Comment by geoand** [comment]
OK, cool. Let me know when you start looking at it

**Comment by nicolas-vivot** [comment]
FYI, I'm ok not fixing this. I agree that open telemetry support should be the priority.

But open telemetry is not yet mature on all the expected features (logging for example), especially when it comes to 3rd party vendors (like datadog) who do not yet provide full support on their collector's exporter.

Because of that, some people will continue to stay with open tracing for a while (that's my case obviously), so any bug / non support should be at least documented so that people are aware of the restriction. This is currently not documented. (a.K.a not mixing blocking & non blocking routes, but also the offer reported issue with vertx web related to incomplete tracing)

**Comment by kenfinnigan** [comment]
Though OpenTelemetry is still working on metrics and logs, tracing is GA and stable.

What else is needed to move away from OpenTracing?

**Comment by nicolas-vivot** [comment]
Technically nothing.

But - and i will talk only for myself and the company i work for - it has a cost depending on the monitoring vendor you're using.
In my case it's datadog.
We have a small kubernetes cloud infra with a few apps and monitor all of this with datadog. We have the datadog agent installed & running on each cluster to monitor. Logs, traces and metrics pass by that agent before being potentially filtered / augmented and finally sent to the datadog backend.

Moving the tracing part to open telemetry would need to install the open telemetry collector and run it along with the datadog agent. One for logs & metrics, the other for traces. Running two agents in the same cluster has a cost in term of resources used for the monitoring versus the resources used for the applications. And unfortunately this is for now not validated.

So unless all features (infra monitoring, logs, metrics and traces) can be dealt by open telemetry, we are not moving on it, even for the tracing part.
That's also why i recently created a quarkus extension to support tracing with datadog in Native. The extension is internal to my company but i'm thinking to push that to the quarkiverse repository soon. Even if it's a temporary solution (until open telemetry is fully supported by datadog on all features), it could be useful for other people facing similar "problems".

Well, anyway, that's out of this ticket's scope right :)

**Comment by kenfinnigan** [comment]
Makes sense, thanks for the details.

We'd be more than happy to have you submit the extension to the quarkiverse!

**Comment by ambition-consulting** [comment]
https://dzone.com/articles/thread-local-state-availability-in-reactive-servic

**Comment by ambition-consulting** [comment]
With https://github.com/quarkusio/quarkus/pull/19225, tracing with the QuarkusContextStorage should work again. Obviously MDC will continue to not work due to it's ThreadLocal nature, but maybe we could add something similar that also gets stored to the VertX localData, maybe even inside the QuarkusContextStorage, and use that similar to MDC for additional tracing/logging information.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by radcortez** [comment]
I believe this is not an issue with the OpenTelemetry extension. Probably, is still an issue with the OpenTracing extension, but we are not supporting OpenTracing anymore.
