### ISSUE TITLE
Vert.x Routes Wrong Behaviour when using hyphens (-) in params

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15185]
**Describe the bug**
When using a route with param names that includes hyphen characters:

```java
@Route(methods = HttpMethod.GET, path = "/path/:my-param")
boolean myRoute(@Param("my-param") String param) {
    return true;
}
```

If we call our route, we will get a HTTP 404 Not Found error. 

Now, if we change our route to get rid of hyphens:

```java
@Route(methods = HttpMethod.GET, path = "/path/:myParam")
boolean myRoute(@Param("myParam") String param) {
    return true;
}
```

Everything works fine now.

**Expected behavior**
If there is a strong technical reason to not support hyphens, this should be documented. However, I think it should be supported. And for sure, not return HTTP Not Found 404 status.

**Actual behavior**
It returns HTTP Not Found 404 status.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.0.Final

**Comment by geoand** [comment]
cc @mkouba

**Comment by geoand** [comment]
FWIW, this works as expected with RESTEasy Reactive (I just checked as I was curious)

**Comment by mkouba** [comment]
It seems that a dash (`-`) may not be used in a [path parameter name](https://vertx.io/docs/vertx-web/java/#_capturing_path_parameters): _"The placeholders consist of : followed by the parameter name. Parameter names consist of any alphabetic character, numeric character or underscore."_

Unfortunately, Vertx Web does not seem to validate the path at all. I think that we should add a least a quarkus-specific validation for `@Param`...

**Comment by cescoffier** [comment]
CC @pmlopes

**Comment by pmlopes** [comment]
Hi @Sgitario The issue here was that vert.x was not allowing the `-` symbol to be part of a variable name as it used a regular expression that mimicks the java variable naming rules. I've created a PR to address this and allow it:

```
:([A-Za-z][A-Za-z0-9_-]*)
```

A variable must start with a letter and have a sequence of letters, numbers or `_` and `-`. I guess the rule could be even more relaxed to support more characters but as it gets more complex it may also introduce a parsing tax on performance.

**Comment by pmlopes** [comment]
@cescoffier I think we can relax the rule on vert.x side and add also add `$`. This way we pretty much cover all the allowed characters for variable naming on most programming languages:

```regex
:([A-Za-z][A-Za-z0-9_-$]*)
```

**Comment by mkouba** [comment]
Hi @pmlopes, I wonder if it would be possible to verify the path parameter during registration? It seems that the route is currently just ignored.

**Comment by pmlopes** [comment]
@mkouba Validation is now present on the PR too. However, the PR is now different. By default, the naming rules are as described on the documentation of vert.x web (alphanumeric characters and underscore). If a system property is set:

```
-Dio.vertx.web.route.param.extended-pattern=true
```

Then the rule is extended to allow `-` and `$`. The reason for this choice is as follows, imagine that you had designed an API as:

```
Route path: /flights/:from-:to
Request URL: http://localhost:8080/flights/LAX-SFO
ctx.params: { "from": "LAX", "to": "SFO" }
```

If the pattern switch would happen now it would mean we just introduced a breaking change for all users of vert.x + downstream users.

Regarding validation, if the "normal" pattern is in place validation on the route path above *will* pass as the 2 variables will be found as `from` and `to`. However, with the extended mode, the validation will also pass as the there are 2 variables but this time with sligthly different names: `from-` and `to`. (note the dash).

It is common to use `/` to split variables, but that is just a common practice and never a requirement from vert.x as the goal was to be non-opinionated.

With this flag, we can switch between "normal" and "extended" modes, so I think this is a good middle ground that will not break backwards compatibility and ensure that the upcoming quarkus 2.0 uses the desired "extended" behavior.

/cc @cescoffier @vietj

**Comment by mkouba** [comment]
> /flights/:from-:to

@pmlopes Hm, so the dash `-` is here used as a separator of path segments. Are you sure this is legal for HTTP?

**Comment by pmlopes** [comment]
@mkouba of course, it is, HTTP does not mandate anything regarding variables. Protocol wise, HTTP refers to resources that are structured in a hierarchical form just like a file system. If you see the example:

```
/flights/LAX-SFO
```

There is nothing wrong with it from the HTTP perspective or even from a REST perspective. Another example could be:

```
path: /print/:name.:extension
```

Which would be used for example as:

```
/print/report.pdf
```

Again nothing wrong or against the HTTP spec.

**Comment by mkouba** [comment]
Ok, I misunderstood the concept of _path parameters_. My understanding was that a path param always represents a path segment. A subtle clarification in the docs would be helpful ;-).

**Comment by pmlopes** [comment]
The issue has been closed, does it mean it's fixed? If it is I can undo the extended pattern upstream to support extra characters.

**Comment by mkouba** [comment]
> The issue has been closed, does it mean it's fixed?

Not really. The build now fails if there isa  `@Param#value()` that does not follow the current rules (a-zA-Z_0-9) and maps to a path param, e.g.  `@Route(path = "/path/:my-param")` and `@Param("my-param")`. The error message looks like: _"A path param name must only contain word characters (a-zA-Z_0-9): my-param [route method foo() declared on org.acme.Bar]"_.
