### ISSUE TITLE
Dev UI config editor with filtering capabilities

### ISSUE THREAD

**Issue by belu** [quarkusio/quarkus#15196]
**Description**
The Config Editor in the Dev UI has no built-in possibility to filter for entries.

**Implementation ideas**
Could be similar to the one in the [All-Config Guide](https://quarkus.io/guides/all-config).

It would be helpful that after a value is updated and the page reloaded, the filter is still active.

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
Hi @geoand - I am happy to look at this. I have not done the original config screen though, I think that might have been @radcortez. 

@radcortez - any ideas ? Or can I just do what I think ?

**Comment by geoand** [comment]
Gotcha!

You guys can work it out between you then :)

**Comment by radcortez** [comment]
> @radcortez - any ideas ? Or can I just do what I think ?

Feel free to change what you want. The original screen is just a boring table with each config in a line. I'm terrible for UI :)
