### ISSUE TITLE
exclusion of slf4j-jboss-logmanager

### ISSUE THREAD

**Issue by dfa1** [quarkusio/quarkus#15193]
**Describe the bug**
In our quarkus applications we use a custom extension to be able to log JSON with a particular format (not supported by any quarkus extension I'm aware of).

Since slf4j-jboss-logmanager is extending `MarkerIgnoringBase` and we would like to use SLF4J as facade with *Markers*, right now we are excluding `slf4j-jboss-logmanager` manually from a lot of dependencies.

**Expected behavior**
Ideally slf4j-jboss-logmanager  should not use MarkerIgnoringBase, so it could be used also in our case (don't know if that is possible) but actually I would like to not forcing any SLF4J binding in quarkus. 

**Actual behavior**
A lot of effort to track down every single usage of slf4j-jboss-logmanager (I see it is a direct dependency for quarkus-core and quarkus-scheduler, at least).

**To Reproduce**
N/A

**Configuration**
N/A
 
**Screenshots**
N/A 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.1757]
 - Output of `java -version`: openjdk 11
 - GraalVM version (if different from Java):  N/A
 - Quarkus version or git rev: 1.11.3
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
I could provide a pull request or in general help with testing

**Comment by gsmet** [comment]
/cc @jamezp 

BTW, have you seen this extension: https://github.com/quarkiverse/quarkus-logging-json? You can tweak a lot of things!

**Comment by jamezp** [comment]
The reason the `slf4j-jboss-logmanager` uses the `MarkerIgnoringBase` is because the JBoss Log Manger itself does not support markers. There has been a request to add the support https://issues.redhat.com/browse/LOGMGR-124. However I'm a bit naive with what markers actually are.

**Comment by dfa1** [comment]
hi! thank you for quick reply :) 

yes, I actually tried quarkus-logging-json but we need to pass SLF4J `Marker`s down to perform some additional logic (e.g. marking the event as "security event" or "audit log") but `slf4j-jboss-logmanager` is dropping them.

**Comment by dfa1** [comment]
hi @jamezp, 
oh I see :)

By the way within the company, we are required to use a "catalog" of predefined events for security and auditing purposes:

``` 
public enum PredefinedEvents implements Marker {

    MISC_LOGIN_SUCCEEDED(EventCategory.SECURITY, 3004, "Misc Login Succeeded"),
    MISC_LOGIN_FAILED(EventCategory.SECURITY, 3005, "Misc Login Failed"),
    DATA_DUMP(EventCategory.AUDIT, 19004, "Data Dump"),
    DATA_IMPORT(EventCategory.AUDIT, 19005, "Data Import"),
...
```

example:

```
        logger.info(PredefinedEvents.DATA_DUMP, "FTP GET: {}", path);
```

**Comment by dfa1** [comment]
So the feature request is: it would be possible to not bind any SLF4J implementation by default?

**Comment by gsmet** [comment]
@dfa1 could you show us a small project showing what you usually do with SLF4J markers?

That might help @jamezp better understand what you are using them for.

**Comment by dfa1** [comment]
@gsmet I cannot really "open source" the code.

By the way I tried to explain that in my previous comment! I'm open to answer more question and provide more "snippets" if needed! :)

**Comment by jamezp** [comment]
Yes the snippet does help for sure. I'm not sure when I'll have the time to look at this for the log manager itself. The log manager is an extension of JUL so it would be something new we'd need to implement, keep backwards compatibility and have something that would work for both slf4j and log4j2.

**Comment by dfa1** [comment]
oh thank you, that would solve a big problem for us and maybe others as well :) 

Of course, I could provide help (testing and even code, given you provide some guidelines).

**Comment by clotton** [comment]
@dfa1 Hi there.  My team faces this same issue where we are using Quarkus, and wish to use markers in logs but haven't found any way to make it happen.   I was hoping you might have some advice on what we can do here to get it working.  Is it now a matter of bumping up a Quarkus version or a jboss logging dependency?  Or is it something more complex?

**Comment by dfa1** [comment]
hi @clotton,

 with pleasure :) 

You have to use a recent version of slf4j-jboss-logmanager (https://github.com/jboss-logging/slf4j-jboss-logmanager/releases/tag/1.2.0.Beta3) that is forwarding the SLF4J Marker as to the underlying logging library.

Then, with [quarkus-logging-json](https://github.com/quarkiverse/quarkus-logging-json), you can customize fully the JSON structure:

```java
@Singleton
public class MyJsonProvider implements JsonProvider {

    @Override
    public void writeTo(JsonGenerator generator, ExtLogRecord event) throws IOException {
        event.getMarker(); <-- coming from JBoss Logging
   }
}
```

Please let me know if this is enough for you :)

**Comment by gsmet** [comment]
@jamezp any chance you could release a final version of `slf4j-jboss-logmanager` 1.2.0 so that we can upgrade it in our BOM?

**Comment by clotton** [comment]
Thank you very much @dfa1 and @gsmet we'd love to see this rolled into a Quarkus release.  

In the meantime, we'll see how your suggestion goes and let you know!  Very much appreciated.

**Comment by clotton** [comment]
@dfa1 Do you by chance have a working example of using that custom JsonProvider?  Not quite seeing how MyJsonProvider works in the greater scheme of a Quarkus app.

**Comment by dfa1** [comment]
@clotton the only working example I have is the production code running happily @SIX since April 2021. I cannot share that... but I believe you should first of all have a look here:

https://github.com/quarkiverse/quarkus-logging-json/blob/master/README.md

**Comment by clotton** [comment]
That's great @jamezp!  @gsmet looking forward to a Quarkus version bump up to use 1.2.0

**Comment by gsmet** [comment]
Yeah, Dependabot should bring it once it hits Central.

**Comment by clotton** [comment]
@dfa1 Do I understand correctly, that once there's a new Quarkus version available using slf4j-jboss-logmanager 1.2.0.Final then the custom JSONProvider won't be necessary?  I believe in our case, we don't need to customize the output, we only want to ensure that our markers end up in the json output so they can be displayed as fields in splunk.   Currently, we are using MDC to make that happen.

**Comment by clotton** [comment]
@dfa1 btw if you have a means to communicate directly (email, slack?) and take the conversation out of the PR here, I'm all for it.

**Comment by dfa1** [comment]
> @dfa1 Do I understand correctly, that once there's a new Quarkus version available using slf4j-jboss-logmanager 1.2.0.Final then the custom JSONProvider won't be necessary?  I believe in our case, we don't need to customize the output, we only want to ensure that our markers end up in the json output so they can be displayed as fields in splunk.   Currently, we are using MDC to make that happen.

most likely you will still need the json provider to write the Markers (but maybe it is supported out of the box now).


And you could try it right now by overriding the managed version of slf4j-jboss-logmanager in your pom/gradle build!

**Comment by dfa1** [comment]
> @dfa1 btw if you have a means to communicate directly (email, slack?) and take the conversation out of the PR here, I'm all for it.

@clotton let's keep this conversation public, so maybe others will benefit too ;)

**Comment by clotton** [comment]
Sure @dfa1.  Is it possible to disable any, non-standard field?  For example, we have a field "resource.apiVersion" in our logs and I'd like to remove it from log output.  Does something like this exist?

`quarkus.log.console.json.fields.myfield.enabled=false
`

**Comment by dfa1** [comment]
@clotton did you already disabled all built-in loggers? (see https://github.com/quarkusio/quarkus/issues/15193#issuecomment-1189516423)

**Comment by clotton** [comment]
Yes we did @dfa1

**Comment by dfa1** [comment]
@clotton then I would open a bug in https://github.com/quarkiverse/quarkus-logging-json 

I don't remember this apiVersion being logged (but maybe I'm using an older version).

**Comment by clotton** [comment]
Thanks @dfa1.  To clarify, we have fields somehow coming from kubernetes by the looks of it.  The fields like "resource.apiVersion" for example are not part of quarkus logging.   So they arent in the same family of logging fields like "thread name" or "process id" or "sequence" etc.  

So I was just wondering if there is a way to turn off ANY field, not just the ones automatically generated by quarkus logging.

**Comment by dfa1** [comment]
@clotton in our infrastructure we have something similar built in openshift but we (devs) can't really control what is being added. So, I fear that there is nothing you can do in your quarkus application. Unless, of course, I'm missing something :-)
