### ISSUE TITLE
Panache empty collection as a middle parameter in a query causes QueryException

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#15200]
**Describe the bug**
If a query takes a collection as a parameter that is not the first or last parameter,
and the collection is empty, the following exception is thrown:
```
org.hibernate.QueryException: Unexpected gap in ordinal parameter labels [1 -> 3] : [1,3]
```

**Expected behavior**
The query executes normally

**Actual behavior**
A variant of `org.hibernate.QueryException: Unexpected gap in ordinal parameter labels` is thrown.

**To Reproduce**
https://github.com/Christopher-Chianelli/issue-reproducer/tree/panache-empty-collection-in-query

Steps to reproduce the behavior using above reproducer:
1. `mvn clean install`
2. `java -jar target/issue-reproducer-8.0.0-SNAPSHOT-runner.jar`

Steps to reproduce on any project:
1. Create an query that takes a colllection as a query parameter (but not as the first or last parameter), and pass in an empty collection for that parameter.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:issuereproducer
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ada 5.10.15-200.fc33.x86_64 #1 SMP Wed Feb 10 17:46:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`:
 ```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
 ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

**Additional context**
If the collection is not empty, the query is executed normally.

**Comment by gsmet** [comment]
@FroMage @loicmathieu could one of you have a look. We have a reproducer above.

**Comment by loicmathieu** [comment]
I'll have a look this week if I found some time but I quickly check the Panache code and we didn't handle specifically collection attributes so this may be tricky.

**Comment by geoand** [comment]
Is this still an issue in the latest versions of Quarkus?

**Comment by Christopher-Chianelli** [comment]
No, can confirm the latest version of Quarkus fixed the issue (although it was probably fixed in a prior version, given the issue was for `1.11.3.Final`.

**Comment by geoand** [comment]
Thanks for checking!
