### ISSUE TITLE
Build native image source jar

### ISSUE THREAD

**Issue by ebaron** [quarkusio/quarkus#15208]
**Description**
I would like the ability for Quarkus to produce a native image source jar without also running a `native-image` build. The scenario in mind is the following, with two machines:
1. Maven builder machine with all needed dependencies, but no GraalVM/Mandrel.
2. Container builder machine using a Mandrel builder image, but no Maven or dependencies. It has access to the output from the first machine.

I cannot find a way to perform a Maven build with Quarkus, such that the output jar can be passed to `native-image` and produce a working executable. When I give `native-image` the standard runner jar, or uber-jar, the executable exits immediately with exit code 1.

**Implementation ideas**
This functionality could perhaps be added as a package type selection for the `quarkus.package.type` property.

**Comment by geoand** [comment]
This would be very easy to add, the question is whether we want to support it or not :)

cc @gsmet @stuartwdouglas

**Comment by jerboaa** [comment]
@geoand I've had a discussion about a similar workflow with @tqvarnst. The basic idea would be to do everything needed up to - but not including - running `native-image`. In fact, we've coined an idea of writing the native image command to a file (or just the native-image args) so as to be able to run the native-image command at a later stage later. This would be helpful for a staged container build, and debugging native-image builds outside `quarkus-maven-plugin`. For the former, consider:

1. Compile the Java files and produce necessary artefacts in tooling container `A`
2. Run `native-image` on tooling container `B` using `A`'s output (jar artefacts and native-image args)
3. Take the result from `B` - the native image of the app - and put it into a runner image `C`

Each step along the way minimizes the needed dependencies in images `A`, `B` and `C`. A workflow like that could also be used in build pipelines. Please consider implementing this.

**Comment by geoand** [comment]
Understood. 

I'll create a draft PR later on with a new package type as requested and we can discuss further based on that

**Comment by jerboaa** [comment]
Thanks!
