### ISSUE TITLE
Kubernetes extension should not produce env vars with slashes when mapping mp-rest client config to env vars

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#15201]
Given an `application.properties` like the following:

```
foo/mp-rest/url=http://localhost:8080

quarkus.kubernetes.env.mapping.foo/mp-rest/url.from-secret=something-parameters
quarkus.kubernetes.env.mapping.foo/mp-rest/url.with-key=foo.url
```

The generated `kubernetes.yml` uses the `FOO/MP_REST/URL` env var, which is invalid, as noted by https://github.com/eclipse/microprofile-rest-client/issues/171 and https://github.com/eclipse/microprofile-config/issues/420 in the past.

We should replace `/` with `_` and figure out if MP-Config actually can do the reverse mapping.

**Comment by FroMage** [comment]
@kenfinnigan says the reverse mapping should work. :crossed_fingers:

**Comment by geoand** [comment]
OK, I'll fix it ASAP

**Comment by radcortez** [comment]
> @kenfinnigan says the reverse mapping should work. 🤞

The reverse mapping rules only apply to the `EnvConfigSource`.

**Comment by radcortez** [comment]
I think we should provide a dotted version of `/mp-rest/url` to improve the user experience and to not confuse people. I mean you can still use it but a dotter version will also be accepter and map to the right configuration.

**Comment by gsmet** [comment]
Well, if we didn’t want to confuse people, we would have proper Quarkus config :)
