### ISSUE TITLE
Fixed order execution of unit tests

### ISSUE THREAD

**Issue by vnittala** [quarkusio/quarkus#1520]
Hi

I'm trying to execute unit tests in a fixed order, similar to @FixMethodOrder(MethodSorters.NAME_ASCENDING). Is it possible to do the same when writing units tests in quarkus?

Thanks
Kiran.

**Comment by gsmet** [comment]
We use the Maven surefire plugin and JUnit 5 (by default) so you can use the methods that work for them.

For instance, see `<runOrder>` [here](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html) for surefire.

**Comment by vnittala** [comment]
Thank you @gsmet, I'll close the issue.
