### ISSUE TITLE
Panache Query/DTO projection with fields from referenced entity

### ISSUE THREAD

**Issue by mrizzi** [quarkusio/quarkus#15222]
**Description**

Currently, the Panache `project` method works great if the parameters in the DTO's constructor belongs to the same entity.

The case of having a DTO with also fields from referenced entities is not working because the required "dot" notation to build a working query is not compatible with Java naming that doesn't allow the usage of dots `.` in a parameter's name.

Example `DogDto` based on [`Person`](https://github.com/quarkusio/quarkus/blob/2b7f0c397d064f6dd1ebd466179aa61d6a33a121/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/Person.java) and [`Dog`](https://github.com/quarkusio/quarkus/blob/af8b5b23b75b41d47000a2e64f0cd66dbc18499d/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/Dog.java) entities from [`hibernate-orm-panache`](https://github.com/quarkusio/quarkus/tree/68759c9f6e4596c8a826bd3f1f28b2b806860473/integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache) integration tests
```java
@Entity
public class Person extends PanacheEntity {

    public String name;
    @Column(unique = true)
    public String uniqueName;

    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    public List<Dog> dogs = new ArrayList<>();
}

@Entity
public class Dog extends PanacheEntityBase {

    @Id
    @GeneratedValue
    public Integer id;

    public String name;

    public String race;

    @ManyToOne
    public Person owner;
}

@RegisterForReflection
public class DogDto {

    public String name;

    public String ownerName;

    public DogDto(String name, String ownerName) {
        this.name = name;
        this.ownerName = ownerName;
    }

}
```
The `DogDto`'s constructor parameters have no way to reference the field `name` from the entity `Person`

**Implementation ideas**

The idea is to add a `ProjectionForField` annotation for `ElementType.PARAMETER` to let the developers provide the "SQL path" to get the value for the field the annotation refers to in the DTO's constructor, considering the projection works starting from the DTO's constructor parameters.

Example based on the above use case
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
public @interface ProjectionForField {
    String value();
}

@RegisterForReflection
public class DogDto {

    public String name;

    public String ownerName;

    public DogDto(String name, @ProjectionForField("owner.name") String ownerName) {
        this.name = name;
        this.ownerName = ownerName;
    }

}
```
The annotation's name `ProjectionForField` wants to be consistent with the annotation [`ProjectionFor`](https://github.com/quarkusio/quarkus/blob/66ff4f130a858ae53d8746be8f266774b1b6e522/extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/ProjectionFor.java) (available for Panache Mongo extension) that refers to classes.

**Comment by mrizzi** [comment]
`quarkus-dev` Google group discussion https://groups.google.com/g/quarkus-dev/c/Es8MvR8o_2I

**Comment by anthony-quiros** [comment]
Hello 😄
I have a question,
Can we also find a way to managed a list of referenced entities ?
Example :

```java
@Entity
public class Person extends PanacheEntity {

    @Basic
    public String uniqueName;

    @Basic
    public long birthdate;

    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    public List<Dog> dogs = new ArrayList<>();
}

@Entity
public class Dog extends PanacheEntityBase {

    @Id
    @GeneratedValue
    public Integer id;

    public String name;

    public String race;

    @ManyToOne
    public Person owner;
}

@RegisterForReflection
public class PersonDto {

    public String uniqueName;

    public List<Dog> dogs = new ArrayList<>()

    public DogDto(final String uniqueName, final List<Dog> dogs) {
        this.uniqueName = uniqueName;
        this.dogs = dogs;
    }

}
```

**Comment by loicmathieu** [comment]
@anthony-quiros please open a different github issue for your example, did you try your example ? Which exception did it throws ?

**Comment by FroMage** [comment]
That feature sounds very reasonable.
