### ISSUE TITLE
Panache Query/DTO projection with fields from referenced a list of entities

### ISSUE THREAD

**Issue by anthony-quiros** [quarkusio/quarkus#15239]
**Description**
Currently, the Panache project method works great if the parameters in the DTO's constructor belongs to the same entity.

But when we have a DTO with field that reference a list of entities we got this error message: 

```log
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: Unable to locate appropriate constructor on class [com.example.model.controller.PersonDto]. Expected arguments are: java.lang.String, java.util.Collection [SELECT new com.example.model.controller.PersonDto (name, dogs) FROM com.example.model.controller.Person]
```

Here repository of an example : https://github.com/anthony-quiros/example-quarkus-entities-projection

**Comment by loicmathieu** [comment]
As the error exception said, you need to use a `Collection` and not a `List` for the dogs attribute.

```
Expected arguments are: java.lang.String, java.util.Collection
```

But after this, there is a new issue with an incorrect SQL query sent to Postgres:

```
2021-04-21 23:36:56.775 UTC [124] ERROR:  syntax error at or near "{" at character 35
2021-04-21 23:36:56.775 UTC [124] STATEMENT:  select person0_.name as col_0_0_, {non-qualified-property-ref} as col_1_0_ from example.person person0_ inner join example.dog dogs1_ on person0_.id=dogs1_.owner_id
```

This may be an issue with DTO projection on Hibernate Reactive.

**Comment by FroMage** [comment]
Yeah, that looks like an HR bug, no @DavideD @gavinking should I file an issue?

**Comment by DavideD** [comment]
Yes @FroMage, please

**Comment by FroMage** [comment]
Reported in https://github.com/hibernate/hibernate-reactive/issues/723 I'm going to close it here. Thanks everyone involved!

**Comment by FroMage** [comment]
@anthony-quiros Turns out this sort of projection is not supported by Hibernate, as noted in the hibernate/hibernate-reactive#723 issue.

**Comment by anthony-quiros** [comment]
@FroMage,
Thanks a lot for the work and the information 🙏
