### ISSUE TITLE
A way to determine exactly what secret/configmap was used by quarkus-kubernetes-config

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15247]
**Description**
We would like our application to restart it's own container when it detects that relevant configuration has changed.  Currently all we can determine from the config names created by quarkus-kubernetes-config is the secret/configmap name.

**Implementation ideas**
This could be as simple as just providing a full name: https://github.com/quarkusio/quarkus/compare/master...shawkins:master which adds the namespace, uid, and resourceVersion.  Or it could create a new interface for the returned configs that a similar set of information.

**Comment by geoand** [comment]
Interesting.

I understand that the config name will be different with your change when the config map has changed and I'm fine with that.
But could you explain a little how you plan to restart the container?

**Comment by shawkins** [comment]
> But could you explain a little how you plan to restart the container?

We'll setup a watch or periodic get on the secret containing properties that we want to trigger a restart.  On either a uid or resourceVersion change we'll call Quarkus.asyncExit - we don't have a requirement at this point to do any deep introspection of what values are actually changing.

**Comment by geoand** [comment]
Makes sense, but I still don't understand where the config source name will come into play.

**Comment by shawkins** [comment]
On start we'll need to use ConfigProvider.getConfig().getConfigSources() to look for ConfigSources that come from the secret in question - with the simple change it would need to parse the name to look for [secret=value].  For a given namespace/name that will give us the uid and resourceVersion that are the baseline for the configuration that is currently in use.  Of course if it's not safe to rely upon config names, or even the ConfigSources then this won't work.

**Comment by geoand** [comment]
The names themselves aren't part of the API but I don't see a reason for them to change, so I'm fine with the assumption that their names (I mean for ones coming from secrets or configmaps) can be predicted.
But best that is explained in a comment and be verified by tests.
So feel free to open a PR with the changes you indicated and the stuff I mentioned above

**Comment by shawkins** [comment]
Updated with a pr to make it clearer what the intention is.
