### ISSUE TITLE
Add support for Flyway "ignore future migrations"

### ISSUE THREAD

**Issue by lenalebt** [quarkusio/quarkus#15242]
**Description**
Flyway can be configured to ignore future migrations. Support for missing migrations already has been added in https://github.com/quarkusio/quarkus/issues/11421 . Ignoring future migrations is useful in rollback scenarios when you have backwards compatible database migrations (that you need anyways for zero-downtime deployments) and encounter an issue that is related to code changes. Rolling back would solve it, but flyway would fail starting because it sees migrations applied it does not know.

**Implementation ideas**
Add a new boolean-typed `quarkus.flyway.ignore-future-migrations` configuration property (defaulting to `false` as in Flyway).

**Comment by lenalebt** [comment]
I can implement it if you want to, following the implementation in https://github.com/quarkusio/quarkus/pull/11437/files as it's really no different. If you'd like to, I can try to make additional configuration properties available as I see need for them in case I see them missing?

**Comment by geoand** [comment]
Thanks!

I like the idea and it would be great if you could contribute this new property.
I would say best limit the PR to this feature only.
If you want to add other Flyway options, it can always be done in subsequent PRs :)

**Comment by lenalebt** [comment]
Okay, will do so :-).
