### ISSUE TITLE
Vert.x upgrade from 3.6.2 to 3.6.3 has conflict with io.smallrye.reactive:smallrye-axle-generator:0.0.1

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1524]
Vert.x upgrade from 3.6.2 to 3.6.3 has conflict with io.smallrye.reactive:smallrye-axle-generator:0.0.1

```
[WARNING]
Dependency convergence error for io.vertx:vertx-codegen:3.6.2 paths to dependency are:
+-io.quarkus:quarkus-vertx-runtime:999-SNAPSHOT
  +-io.smallrye.reactive:smallrye-axle-generator:0.0.1
    +-io.vertx:vertx-codegen:3.6.2
and
+-io.quarkus:quarkus-vertx-runtime:999-SNAPSHOT
  +-io.vertx:vertx-rx-java2:3.6.3
    +-io.vertx:vertx-rx-gen:3.6.3
      +-io.vertx:vertx-codegen:3.6.3
```

To upgrade Vert.x is it necessary to go via smallrye-axle bits ?

I think there could be some flexibility to bump Vert.x version without touching axle.
@cescoffier wdyt ?

**Comment by gsmet** [comment]
We need to define the `vertx-codegen` version in the BOM so that it doesn't conflict.

**Comment by cescoffier** [comment]
@gsmet @rsvoboda I will update the Vert.x Axle client today.
