### ISSUE TITLE
Support for Kryo serialization library

### ISSUE THREAD

**Issue by atorr0** [quarkusio/quarkus#15265]
**Kryo serialization option for https://code.quarkus.io/**
Hi,

I've read the serialization extension listed in https://code.quarkus.io/, but I haven't found any reference to Kryo.
I think it could be very nice to have Kryo serialization extension listed.

Thank you,

More info:
* https://github.com/EsotericSoftware/kryo
* https://flink.apache.org/news/2020/04/15/flink-serialization-tuning-vol-1.html

**Comment by ia3andy** [comment]
Ok so it hasn't changed thanks.. moved..

**Comment by geoand** [comment]
Where do you envision Kryo would be used?

**Comment by geoand** [comment]
Yes, there no denying that.
What I am wondering is what use cases do you have in mind for Quarkus?

**Comment by gastaldi** [comment]
I created https://github.com/FasterXML/jackson-dataformats-binary/issues/328 asking to be implemented as another Jackson Data Binary format

**Comment by geoand** [comment]
I don't really see how this would be used and we have not got any feedback on it either, so I'll close this as won't fix

**Comment by FrodoOf9Fingers** [comment]
I am aiming to write an adapter between a legacy system and a new system. I'm looking at using Kryo for dealing with serialization of (very) complex legacy object models that my adapter is constructing from data in the new system. 

I came across this today, and seeing that it was just closed, figured I'd throw my use case in. I'm still poking around to see if there is a way to bring it in without direct support in Quarkus.

**Comment by geoand** [comment]
In that case you would just handle the use of Kryo manually, right?

**Comment by FrodoOf9Fingers** [comment]
Yep! What I ended up doing is targeting a byte array with the output stream and returning that (though, I've ended up on FST for my needs instead of Kryo). For streaming, I think you could pass a ResteasyReactiveOutputStream into Kryo's Output, though I have not confirmed that.
