### ISSUE TITLE
Support for Narayana LRA (Saga)

### ISSUE THREAD

**Issue by eamazaj** [quarkusio/quarkus#15266]
**Add support for distributed transactions**
Narayana LRA implement the spec Microprofile LRA, Qurakus has taken a lot of force for the implementation of native applications in the cloud, it is important to add or implement the SAGA pattern to orchestrate microservices transactions on the Quarkus.

**Comment by nmcl** [comment]
How is this different than https://github.com/quarkusio/quarkus/issues/4399

**Comment by gastaldi** [comment]
Looks like it's a duplicate. I'll close this one
