### ISSUE TITLE
OpenAPI/Swagger properties not behaving as expected

### ISSUE THREAD

**Issue by pawoolley** [quarkusio/quarkus#15275]
**Describe the bug**

In this [sample-project.zip](https://github.com/quarkusio/quarkus/files/6029778/sample-project.zip), I am trying to set it up so that:

1. The `openapi` and `swagger` urls are not enabled by default.
2. The `openapi` and `swagger` urls are only enabled for the `foo` profile.
3. The `openapi` and `swagger` urls are located at `/openapi` and `/swagger` respectively (i.e. under the `/` root and not under the `/q` root).

However, I am getting inconsistent behaviour from this setup which, as far as I can tell, does not match what is described in the [documentation](https://quarkus.io/guides/openapi-swaggerui#configuration-reference).

**For the default/dev profile**

_To reproduce:_

1. Run up the sample project with `mvn clean compile quarkus:dev`
2. Go to http://localhost:8080/swagger
3. Go to http://localhost:8080/openapi

_Expected behaviour:_

1. http://localhost:8080/swagger is 404 Not Found.
2. http://localhost:8080/openapi is 404 Not Found.

_Actual behaviour:_

1. http://localhost:8080/swagger redirects to http://localhost:8080/q/swagger and is 404 Not Found.  I thought the redirect should have been disabled by the `quarkus.http.non-application-root-path=/` property.
2. http://localhost:8080/openapi redirects to http://localhost:8080/q/openapi and is 404 Not Found.  I thought the redirect should have been disabled by the `quarkus.http.non-application-root-path=/` property.
3. http://localhost:8080/swagger/ shows the swagger UI, which I thought had been disabled by the `quarkus.swagger-ui.enable=false` property.

**For the `foo` profile**

_To reproduce:_

1. Run up the sample project with `QUARKUS_PROFILE=foo mvn clean compile quarkus:dev`
2. Go to http://localhost:8080/swagger
3. Go to http://localhost:8080/openapi

_Expected behaviour:_

1. http://localhost:8080/swagger shows the Swagger UI.
2. http://localhost:8080/openapi downloads the API definition yaml file.

_Actual behaviour:_

1. http://localhost:8080/swagger redirects to http://localhost:8080/q/swagger and is 404 Not Found.  I thought the redirect should have been disabled by the `quarkus.http.non-application-root-path=/` property.
2. http://localhost:8080/openapi redirects to http://localhost:8080/q/openapi and is 404 Not Found.  I thought the redirect should have been disabled by the `quarkus.http.non-application-root-path=/` property.
3. http://localhost:8080/swagger/ shows the swagger UI, but it is at the wrong path (should be just `/swagger` with no trailing `/`) and the API definition at `/openapi` is 404 Not Found.

**Configuration**
```properties
# Always include the swagger-api in the application
quarkus.swagger-ui.always-include=true

# Set the paths
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger

# Disabled by default
quarkus.smallrye-openapi.enable=false
quarkus.swagger-ui.enable=false

# Don't do the "/q" thing
quarkus.http.non-application-root-path=/

# Enabled for the "foo" profile
%foo.quarkus.smallrye-openapi.enable=true
%foo.quarkus.swagger-ui.enable=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
```
Darwin ip-192-168-0-17.ec2.internal 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```
 - Quarkus version or git rev: `1.11.3.Final`

**Comment by phillip-kruger** [comment]
Hi @pawoolley 
Thanks for the sample app, that helps.I looked at it, and this is working for me as expected (i.e I got the expected behavior in both scenarios)

Maybe it's your browser cache ?

**Comment by pawoolley** [comment]
Hi @phillip-kruger
Thank you for the quick reply and for taking a look.  You're right.  It must have been my browser cache 🤦‍♂️ 
I retried this using an incognito tab and it behaved as expected.  Rookie error.

**Comment by phillip-kruger** [comment]
No problem :) Glad it's working now :)
