### ISSUE TITLE
Jacoco instrument with @QuarkusTest caused vm crash

### ISSUE THREAD

**Issue by ligangty** [quarkusio/quarkus#15289]
**Describe the bug**
Recently I'm using jacoco to do test coverage analysis together with Quarkus test framework, but I met problems when run them together in maven. It will crash the vm like below:

................................
................................
[INFO] Running org.commonjava.indy.service.repository.jaxrs.RepositoryQueryResourcesTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire-reports/2021-02-24T11-21-29_356-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.246 s
[INFO] Finished at: 2021-02-24T11:22:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (integration-tests) on project indy-repository-service: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service && /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.fc32.x86_64/bin/java -Djdk.attach.allowAttachSelf=true -jar /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire/surefirebooter4080097235006468675.jar /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire 2021-02-24T11-21-29_356-jvmRun1 surefire5732770477089355412tmp surefire_12616931527994133108tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] org.commonjava.indy.service.repository.jaxrs.RepositoryQueryResourcesTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service && /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.fc32.x86_64/bin/java -Djdk.attach.allowAttachSelf=true -jar /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire/surefirebooter4080097235006468675.jar /home/gli/workspaces/java/projects/nos/indy-services/indy-repository-service/target/surefire 2021-02-24T11-21-29_356-jvmRun1 surefire5732770477089355412tmp surefire_12616931527994133108tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] org.commonjava.indy.service.repository.jaxrs.RepositoryQueryResourcesTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
................................
................................

This only happened during the @QuarkusTest, but the other tests without this annotation will pass successfully.

**Expected behavior**
Running tests without vm crash error and jacoco report  generated successfully

**Actual behavior**
VM crashed like problem description

**To Reproduce**
Can use https://www.github.com/commonjava/indy-repository-service  to reproduce. Please use "jacoco" branch to reproduce. Please try more several times if the first time passed.

1.  Checkout to "jacoco" branch
2.  Run "mvn clean verify"
3.  If the tests passed, please try several times. (It will pass sometimes, but fails more often)

**Environment (please complete the following information):**
 - OS: Fedora 32 & 33(CPU 4core & 32G mem), CentOS Linux release 7.9.2009(VCPU 8core & 24 G mem)
 - Output of `java -version`:  
    openjdk version "11.0.10" 2021-01-19
    OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool: maven 3.6.0+

**Comment by ligangty** [comment]
I also suspect it is some type of heap mem issue, so I've also tried the jvm heap params in surefire plugin like below:

 <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${plugin.surefire.version}</version>
        <configuration>
          <excludedGroups>integration</excludedGroups>
          <skipTests>${skipTests}</skipTests>
          <argLine>-Xmx4096 -XX:MaxMetaspaceSize=3072</argLine>
          <systemPropertyVariables>
            <jacoco-agent.destfile>${project.build.directory}/jacoco-ut.exec</jacoco-agent.destfile>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
        <executions>
          <execution>
            <id>integration-tests</id>
            <phase>integration-test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <excludedGroups>!integration</excludedGroups>
              <skipTests>${skipTests}</skipTests>
              <groups>integration</groups>
              <argLine>-Xmx4096 -XX:MaxMetaspaceSize=3072</argLine>
              <systemPropertyVariables>
                <jacoco-agent.destfile>${project.build.directory}/jacoco-it.exec</jacoco-agent.destfile>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>

But with this it will fail as no this settings(or passed randomly)

**Comment by gsmet** [comment]
I'm not sure you'll be able to make it work with the current state of things. @stuartwdouglas worked on a `quarkus-jacoco` extension for Quarkus 1.13 (coming in ~ 1 month).

Maybe you could try our snapshots and report back? They are published here: https://oss.sonatype.org/content/repositories/snapshots/ and have the version `999-SNAPSHOT`.

**Comment by ligangty** [comment]
@gsmet I've switched to this 999-SNAPSHOT, but I got following error this time:

[INFO] --- jacoco-maven-plugin:0.8.4:restore-instrumented-classes (restore-ut) @ indy-repository-service ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ indy-repository-service ---
[INFO] Building jar: /home/gli/workspaces/indy-repository-service/target/indy-repository-service-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ indy-repository-service ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.257 s
[INFO] Finished at: 2021-02-24T09:39:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project indy-repository-service: Failed to build quarkus application: java.lang.RuntimeException: Failed to load steps from class io.quarkus.vertx.http.deployment.devmode.ArcEndpointProcessor: io/quarkus/vertx/http/runtime/devmode/ArcEndpointRecorder: io.quarkus.vertx.http.runtime.devmode.ArcEndpointRecorder -> [Help 1]

Seems it has some problems to build the package with this version.

**Comment by gsmet** [comment]
Did you update both the BOM and the Maven plugin and did a proper clean?

Also my understanding is that with master, you can drop the Jacoco Maven plugin and just add the `quarkus-jacoco` extension.

**Comment by ligangty** [comment]
@gsmet I can confirm the plugin and BOM is using same version: 999-SNAPSHOT

For your suggestion, I've removed all jacoco deps & plugin, and added quarkus-jacoco extension through 'mvn quarkus:add-extension -Dextensions="quarkus-jacoco" '. But it reported same error after updating. I've pushed update to the  here: https://github.com/Commonjava/indy-repository-service/blob/jacoco/pom.xml

**Comment by famod** [comment]
I gave this a shot and it _does_ generate a report for me, for both variants (Quarkus 999-SNAPSHOT + jacoco extension _and_ Quarkus 1.11.3 + jacoco plugin).

PS: I had to use Azul JDK 11 because Adopt JDK 11 failed with missing flight recorder imports.
```
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/moldowan/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: Azul Systems, Inc., runtime: /home/moldowan/.sdkman/candidates/java/11.0.10-zulu
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.128-microsoft-standard", arch: "amd64", family: "unix"
```

**Comment by stuartwdouglas** [comment]
@ligangty that error looks like what can happen if you don't  have a clean build of Quarkus (i.e. mvn install rather than mvn clean install).

**Comment by stuartwdouglas** [comment]
I could not reproduce the crash. I did see thought that it is attempting to load a native library `org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path`.

Do you have this library? If so a native lib would be the prime suspect when you have a JVM crash.

**Comment by ligangty** [comment]
@stuartwdouglas For that native lib, I've removed that deps and disabled related Unit tests this time, but the problem is still happening. I've updated this part of code in my personal repo here: https://github.com/ligangty/indy-repository-service/tree/jacoco  And I've created a travis ci build to make sure it is not my env related, this is the failed build here: https://travis-ci.org/github/ligangty/indy-repository-service/builds/760397411  (Note that I've changed back quarkus version to 1.11.3.Final in this branch to make it can build on travis, and it still happens randomly, which I've restarted the job 3 times to trigger this error)

And for the 999-SNAPSHOT with quarkus-jacoco extension, I've found it can pass on my Fedora 32 laptop, but will still meet that ArcEndpointRecorder error on my Centos 7.9 VM. Not sure if it is an env related issue. I've put this part of code to jacoco-ext branch here: https://github.com/ligangty/indy-repository-service/tree/jacoco-ext

**Comment by stuartwdouglas** [comment]
Can you attach a copy of the dump file created by the JVM?

That ArcEndointRecorder error is generally caused by not doing a clean build of Quarkus, are you sure you did a clean build on CentOS?

**Comment by ligangty** [comment]
@stuartwdouglas This is the vm crash log and dumpstream file (On my Fedora 32 laptop with openjdk11.0.10 + maven3.6.3)

[dump.zip](https://github.com/quarkusio/quarkus/files/6040526/dump.zip)

For that 999-SNAPSHOT on centos, I can 100% confirm it is cleaned just like below:

$ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] --------< org.commonjava.indy.service:indy-repository-service >---------
[INFO] Building Indy :: Service :: Repository 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ indy-repository-service ---
[INFO] Deleting /home/gli/workspaces/indy-repository-service/target
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) @ indy-repository-service ---
..............................................................................
..............................................................................
..............................................................................
..............................................................................
INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ indy-repository-service ---
[INFO] Building jar: /home/gli/workspaces/indy-repository-service/target/indy-repository-service-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ indy-repository-service ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.790 s
[INFO] Finished at: 2021-02-25T04:44:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project indy-repository-service: Failed to build quarkus application: java.lang.RuntimeException: Failed to load steps from class io.quarkus.vertx.http.deployment.devmode.ArcEndpointProcessor: io/quarkus/vertx/http/runtime/devmode/ArcEndpointRecorder: io.quarkus.vertx.http.runtime.devmode.ArcEndpointRecorder -> [Help 1]

**Comment by ligangty** [comment]
After checking, I hghly suspect this is caused by the jdk.jfr package. In my project the we involved the an JFR Event to tracking some data, and seems that the jacoco meets some problems to instrument these new Event class during tests. After removing these Events, the vm crashing problem never happens again. 
I think this is not a problem of Quarkus, so will close this one. Sorry for the wrong report.
