### ISSUE TITLE
Quarkus site code blocks text not readable

### ISSUE THREAD

**Issue by ealcantara22** [quarkusio/quarkus#15306]
**Describe the bug**
Hello, as described in the title quarkus sites code blocks text format has changed. Not sure if is intentional, but the current format makes reading the code a bit difficult.

**Expected behavior**
![image](https://user-images.githubusercontent.com/56136351/109028460-3454a080-7698-11eb-8ebd-180e4a217a07.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/56136351/109026576-459cad80-7696-11eb-86df-fcdb15825f5b.png)

**To Reproduce**
Visit: https://quarkus.io/guides/getting-started-reactive#mutiny

**Additional context**
Checked across multiple web browsers.
Mozilla Firefox, google chrome in Mac OS (light and dark mode). 
Mozilla Firefox, google chrome in Linux Mint (light and dark mode)

**Comment by gsmet** [comment]
That would be my fault. I'll go fix it.

**Comment by gsmet** [comment]
It's fixed (you need to force a refresh though). Thanks a lot for the report!
