### ISSUE TITLE
Static Resources in devmode doesn't provide filtered ones

### ISSUE THREAD

**Issue by brunolmfg** [quarkusio/quarkus#15303]
**Describe the bug**
Static resources are directly provided from source project directory in dev mode and the filtering process is ignored. 

**Expected behavior**
The filtered resources with interpolated Maven properties are provided by static handler for `src/main/resources/META-INF/resources` files when running in dev mode.

**Actual behavior**
The original resources without Maven properties resolution are provided by static handler for `src/main/resources/META-INF/resources` files when running in dev mode.

**To Reproduce**
The project bellow was generated at [Quarkus Code Start](https://code.quarkus.io/). The resources filtering was enabled and the `src/main/resources/META-INF/resources/index.html` was changed to use some Maven properties.

https://github.com/brunolmfg/static-handler-issue

1. Enable resources filtering
2. Use Maven property interpolation in some static provided resource
3. Run application in dev mode
4. The provided resource is the original non-filtered file without properties interpolation

**Configuration**
No special configuration needed.

**Screenshots**
On reproducer project the `src/main/resources/META-INF/resources/index.html` was changed to use Maven properties after enabling resources filtering:
![image](https://user-images.githubusercontent.com/60534/109009715-a1166d80-768d-11eb-8ab9-038efb1d430e.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
```
Linux captain 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
 - GraalVM version (if different from Java): Not applied
 - Quarkus version or git rev: `1.12.0.Final` but previous versions have the same issue
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/develop/apache-maven-3.6.3
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-43-generic", arch: "amd64", family: "unix"
```

**Additional context**
No additional context but I've found some reported issues like #554, #3886 and #10912 that seems correlated.

I've the following questions when investigating the approach to create a static handler for providing "static" resources:
* The strategy used for hot deployment doesn't consider the resources processing. So the interpolation of Maven properties is not processed.
* Maybe the handlers created for `hotDeploymentResourcePaths` are unnecessary on `StaticResourcesRecorder` or they could be postponed after the handler for the `knownPaths` collected by `StaticResourcesProcessor`.
* Another possibility is the `hotDeploymentResourcePaths` being used to recollect the `knownPaths` on `StaticResourcesRecorder` instead of adding new static handlers. It seems a better procedure for enable changed resources to be statically available.
* Finally I've found that `hotDeploymentResourcePaths` is collected by `StaticResourcesHotReplacementSetup` using the method `getResourcesDir` of `RuntimeUpdatesProcessor`. Maybe checking the output path first could be more appropriated.

```java
    public List<Path> getResourcesDir() {
        List<Path> ret = new ArrayList<>();
        for (DevModeContext.ModuleInfo i : context.getAllModules()) {
            if (i.getResourcePath() != null) {
                ret.add(Paths.get(i.getResourcePath()));
            } else if (i.getResourcesOutputPath() != null) {
                ret.add(Paths.get(i.getResourcesOutputPath()));
            }
        }
        Collections.reverse(ret); //make sure the actual project is before dependencies
        return ret;
    }
```

**Comment by maxandersen** [comment]
@stuartwdouglas @aloubyansky did we have a way of doing filtered resources part of devmode ? maybe not per default but somehow be able to enable it for projects dependent on it ?

**Comment by aloubyansky** [comment]
That would be a feature request. Property replacement could certainly be supported.

**Comment by maxandersen** [comment]
> Property replacement could certainly be supported.

as in calling the underlying build system filtering or by us reimplimenting/emulating it ?

**Comment by aloubyansky** [comment]
A quick(er) fix would be doing it ourselves. We are not calling the underlying build system for the compilation neither. The approach certainly neglects all the possibly configured extra Maven goals/Gradle tasks but helps make the restart faster.

**Comment by brunolmfg** [comment]
If I haven't missed something in that additional discussion, the filtering is currently already being performed on devmode. In this issue I've reported that the filtered resources aren't being served by the created `StaticHandler` at `StaticResourcesRecorder`. I've proposed the PR #15312 with changes to allow the classes directory being preferred when serving that static resources. 😅
