### ISSUE TITLE
SmallRye Metrics should respond with Accept All headers

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#15310]
**Describe the bug**
Metrics are not returned when accessing `/q/metrics`

**Expected behavior**
If no Accept header is passed, ie. it means Accept All, then the metrics should be returned

**Actual behavior**
Currently, SmallRye Metrics returns a HTTP 406 if `text/plain` is not passed as an Accept header type.

**Comment by jmartisk** [comment]
I'm not sure what you mean here - if I call simply `curl localhost:8080/q/metrics` without any headers, I get a Prometheus export by default. I get a 406 error only if I pass an `Accept` header with an unrecognised value.

**Comment by kenfinnigan** [comment]
@ebullient added a test yesterday where we had an issue where the behavior you describe didn't happen.

I don't believe the test was adding any accept headers to the request

**Comment by ebullient** [comment]
I'll double check. this also may not be something unique to smallrye metrics, as I have #15093 also. I'll poke so we can be more precise about where something might need to be adjusted.
