### ISSUE TITLE
Gradle integration test doesn't actually run the test

### ISSUE THREAD

**Issue by jnizet** [quarkusio/quarkus#1532]
The gradle-it module has a test, but this test is never executed because the gradle test task isn't properly configured to `useJUnitPlatform()`.

If the test tack is properly configured, then the test fails, due to #1458

Besides, the configuration `testCompile` used by the gradle build is deprecated. The correct configuration is `testImplementation`. See https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html and https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations

**Comment by stalep** [comment]
I tested locally with adding:
```groovy
test {
    useJUnitPlatform()
}

sourceSets {
  test {
    output.resourcesDir = file('target/test-classes')
    java.outputDir = file('target/test-classes')
  }
}
```
This gets past the PathTestHelper issue, but it still fails. Looking into it.

**Comment by jnizet** [comment]
The change still hardcodes a single default location for the classes. 
This location is incorrect if Kotlin is used. 
And if both Java and Kotlin are used, Gradle will store classes in two separate directories, not just one. 
I don't know why the locations need to be verified that way because I have no idea of what Quarkus needs to do with these classes, but am I right to say that:

- given that these locations are hardcoded that way, you can't run tests from the IDE (since it stores classes in a different directory than Gradle/Maven)
- you can't use any other language than Java (and Kotlin if fixed for Kotlin)
- you can't have classes and test classes in separate Gradle/Maven projects/modules?

**Comment by gsmet** [comment]
@jnizet could you open another issue with all your (very valid) concerns. We knew it was a hack, we need to find a better solution but not sure it will be easy.

**Comment by jnizet** [comment]
@gsmet I have created #1584
