### ISSUE TITLE
Disabling Kafka health check is not working.

### ISSUE THREAD

**Issue by anaray** [quarkusio/quarkus#15321]
**Describe the bug**
Disabling Kafka health check by configuring _quarkus.kafka.health.enabled=false_ is not working as expected. 
**Expected behavior**
On configuring quarkus.kafka.health.enabled=false Kafka health must not run

**Actual behavior**
It runs the health even after setting quarkus.kafka.health.enabled=false. It returns below response
```
HTTP/1.1 503 Service Unavailable
content-length: 245
content-type: application/json; charset=UTF-8

{
    "checks": [
        {
            "data": {
                "kafka-connector": "[KO]"
            },
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN"
        }
    ],
    "status": "DOWN"
}
```
**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Create Quarkus application
2. Add quarkus-smallrye-reactive-messaging-kafka , quarkus-smallrye-health dependencies
3. Add quarkus.kafka.health.enabled=false
4. Call health REST endpoint for example http localhost:8080/q/health/ready

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.vertx.prefer-native-transport=true
quarkus.http.so-reuse-port=true
quarkus.http.tcp-quick-ack=true
quarkus.http.tcp-cork=true
quarkus.http.tcp-fast-open=true

## disable kafka health check
quarkus.kafka.health.enabled=false

## Logs
quarkus.log.level=DEBUG

## openapi configuration
mp.openapi.extensions.smallrye.openapi=3.0.3

## Http client  configuration
mp.messaging.outgoing.metrics.connector=smallrye-http
mp.messaging.outgoing.metrics.method=POST
mp.messaging.outgoing.metrics.url=http://localhost:9090/test

## Kafka Ingestion configuration
# mp.messaging.outgoing.metrics.connector=smallrye-kafka
# kafka.bootstrap.servers=host.docker.internal:9092
# mp.messaging.outgoing.metrics.topic=metrics
# mp.messaging.outgoing.metrics.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin 19.6.0 Darwin Kernel Version
 - Output of `java -version`: openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
There are two levels of health checks: the one coming from the Quarkus Kafka extension and the one comings from Reactive Messaging.

To disable the checks on reactive messaging, use:

```
mp.messaging.outgoing.metrics.health-enabled=false
```

If you have multiple channels, and want to disable them globally, use:

```
mp.messaging.connector.smallrye-kafka.health-enabled=false
```

**Comment by anaray** [comment]
@cescoffier thank you
I tried both approaches, but I still see that it runs the health check and returns below response

```
▶ http localhost:8080/q/health/ready
HTTP/1.1 503 Service Unavailable
content-length: 245
content-type: application/json; charset=UTF-8

{
    "checks": [
        {
            "data": {
                "kafka-connector": "[KO]"
            },
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN"
        }
    ],
    "status": "DOWN"
}
```

**Comment by cescoffier** [comment]
Try configuring on the channel 'health-readiness-enabled' to false too.


If that does not work can you provide a small reproducer?

**Comment by anaray** [comment]
> Try configuring on the channel 'health-readiness-enabled' to false too.
> 
> If that does not work can you provide a small reproducer?

```
mp.messaging.outgoing.metrics.health-enabled=false
mp.messaging.connector.smallrye-kafka.health-enabled=false
```
My finding is that, setting either of the above configurations have no affect. The configuration which has a affect is  given, but it would disable everything which is not what I am looking for 
```
quarkus.health.extensions.enabled=false
```

I will try to create a reproducer and share it with you. 
Thanks

**Comment by cescoffier** [comment]
BTW, I extended the documentation to explain how health checks needs to be configured.

**Comment by cescoffier** [comment]
Closing - please reopen if it still happens. A reproducer would be really nice.
