### ISSUE TITLE
DEV UI: Enhancing the Scores Page in RESTEasy Reactive

### ISSUE THREAD

**Issue by SaumyaSingh1** [quarkusio/quarkus#15322]
As per @phillip-kruger's suggestions, I will be working on beautifying the `Scores` Screen in `RESTEasy Reactive` extension :)

Right now the screen looks like this:
![image](https://user-images.githubusercontent.com/46818757/109108912-6a5a5900-775a-11eb-9120-ee08420f95b2.png)

Enhanced Screen:
![image](https://user-images.githubusercontent.com/46818757/109109185-dd63cf80-775a-11eb-8bfb-0d498cf3e775.png)
(By Phillip)

**Comment by SaumyaSingh1** [comment]
@geoand 
Please assign this to me :)

**Comment by geoand** [comment]
Done :)

**Comment by phillip-kruger** [comment]
@gsmet @SaumyaSingh1 this can be close right ?

**Comment by SaumyaSingh1** [comment]
Most probably yes :) 
This was completed by us.
