### ISSUE TITLE
when a resource return 404, the metrics does not return the uri called

### ISSUE THREAD

**Issue by mmaggioni-wise** [quarkusio/quarkus#15327]
### Description

when a resource return 404, the metrics does not return the uri called

`http_server_requests_seconds_count{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",}`

instead of

`http_server_requests_seconds_count{method="GET",outcome="CLIENT_ERROR",status="404",uri="/hello-resteasy/{code}",}`

it's misleading, and for projects with more than one endpoint you cannot really tell what's going on, and where are those 404

### Analysis
i created a new quarkus project with:

features: `[cdi, micrometer, resteasy]`

the code is very simple.
the problem happens with Response 404 and with `throw new NotFoundException();`

```
@Path("/hello-resteasy/{code}")
public class GreetingResource {

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  public Response hello(@PathParam("code") Long l) {

      if (l == 5) {
          return Response.status(404).build();
      } else {
          return Response.ok("found").build();
      }
  }
}
```

**Comment by mmaggioni-wise** [comment]
ah, sorry.
for some reason i choose Epic instead of Bug....

**Comment by ebullient** [comment]
404 URIs will not be displayed in metrics. 

Log / trace analysis can reveal URIs that aren't found, but the list of possible values is effectively infinite, and thus not suitable for a metrics tag.

**Comment by ebullient** [comment]
Think about it this way, what are all of the things you'd get a 404 for?
* Missing /favicon
* /Totally/nonsense/URI
* /hello/resteasy/{infinitechoices}


I can see that in your case, you're using 404 to provide more reasonable information.. but the 404 (as measured at a lower level) encompasses a much larger (unbounded) set than you're thinking of.

So I think what you're hoping is to capture "how many times was this endpoint called with a bad parameter value. A counter may be more appropriate for that if that particular metric is important.

**Comment by mmaggioni-wise** [comment]
I understand your point, but i do not agree. I don't think 404 for non existing urls (eg /Totally/nonsense/URI ) are so common (maybe only the favicon, but we can live with that :) ) , and to me it makes more sense to track everything.

If we start to receive a lot of 404 for `/hello/resteasy/{non_existing_resource}` we won t see it, and we could miss an important information.

btw it's not a problem. We would create a filter, it should be easy!

**Comment by ebullient** [comment]
That is a much better solution, and yes, it should be.
