### ISSUE TITLE
Rest Client - Unable to read an Entity from a WebApplicationException

### ISSUE THREAD

**Issue by bradleywarrenslater** [quarkusio/quarkus#15325]
**Quarkus version: 1.12.0.Final**

When catching a WebApplicationException we are unable to read the Entity from the response, this works in version 1.11.3.Final

**Expected behavior**
`WebApplicationException.getResponse().readEntity(Class<T>) should unmarshal to to Class<T>`

**Actual behavior**
`
WebApplicationException.getResponse().readEntity(Class<T>) causes
javax.ws.rs.ProcessingException: java.lang.IllegalStateException: RESTEASY003291: Input stream was empty, there is no entity
`

**Comment by sberyozkin** [comment]
@bradleywarrenslater Hi, please see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12, `Rest Client Exceptions`
