### ISSUE TITLE
Using gradle compileOnly configuration is wrong

### ISSUE THREAD

**Issue by jnizet** [quarkusio/quarkus#1533]
I still don't know exactly why it was chosen to use the `compileOnly` configuration for dependencies, but it looks wrong to me. Let me elaborate:

1. The compileOnly configuration, as its name indicates, is for dependencies (and their transitive dependencies) that are only used at compilation time, and should thus not be added to the runtime classpath. This is not the case of quarkus dependencies: resteasy, for example, is very much necessary at runtime. 
2. Although close to the Maven `provided` scope of Maven, they're not equivalent. In particular, compileOnly dependencies are not added to the runtime classpath, and also not added to the test compile classpath. This means that, to be able to use a Jax-RS class such as NotFoundException for example, simply to write a unit test for a resource that throws this exception, I need to add the dependencies twice: once in the compileOnly configuration because that's what Quarkus forces us to use, and once in the testImplementation configuration to be able to compile tests. This shouldn't be necessary.

**Comment by stalep** [comment]
Hi, as you mention the reason why 'compileOnly' was used is because it's the recommended configuration with regards to 'provided'. As the quarkus build/native plugin takes care of this for you, the only issue here is tests if I'm not misunderstanding. I guess 'providedCompile' from the war task is something you have in mind?

**Comment by jnizet** [comment]
No, not really. As far as I know, the provided scope in Maven was designed for dependencies that you need at compile time and at runtime, but which don't need to be bundled with your artifact because the artifact (a war file, typically) is deployed in a container which provides the dependency.

That's not the case here: there is no container, and the dependencies need to be bundled with the produced jar file. 

So I would argue that even the provided dependency in Maven is incorrect (not to mention [this issue](https://github.com/quarkusio/quarkus/issues/1409), which explains that the scope of dependencies shouldn't be specified in the bom, but specified by the project using the dependencies)

With gradle, it's even weirder and annoying to use the compileOnly configuration, since that will additionally make the dependency not available in the tests (in addition to not normally being available at runtime).

**Comment by stalep** [comment]
I agree, for now I think we should change the it to `compile` instead of `compileOnly`.
With the latest changes in master i have tests working with `compile`. - except the native test, but looking into it.

**Comment by jnizet** [comment]
`compile` is deprecated. `implementation` is the configuration to use for stuff that are needed at compile time and at runtime. See https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management.

**Comment by stalep** [comment]
ah, i didnt know. thanks!
