### ISSUE TITLE
Native image build server does not start with `-Dquarkus.native.enable-server=true`

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#15331]
**Describe the bug**
As of GraalVM/Mandrel 20.2 `--no-server` is the default and `--experimental-build-server` is required to enable the build server.
(see https://github.com/oracle/graal/commit/ab8e3138b5899ba83e902607e1f88113749c8107)

Quarkus, however, still assumes that the build server is started by default, thus doing nothing (other than omitting `--no-server` when `-Dquarkus.native.enable-server=true`

I am personally in favor of dropping that option/feature for the following reasons:
1. The build server is considered experimental
2. Mandrel doesn't support the build server
3. Getting the build server to work with containers will complicate `NativeImageBuildStep` with no good reason (IMO)

**Expected behavior**
When `-Dquarkus.native.enable-server=true` is used Quarkus should start a native-image build server.

**Actual behavior**
Quarkus starts native-image in non server mode.

**To Reproduce**
```
./mvnw clean package -Dnative -Dnative.surefire.skip \
    -Dquarkus.native.enable-server=true \
    -Dquarkus.native.graalvm-home=/opt/jvms/graalvm-ce-java11-21.0.0 \
    -pl integration-tests/main
/opt/jvms/graalvm-ce-java11-21.0.0/bin/native-image --server-list
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.10.10-200.fc33.x86_64
 - Output of `java -version`: OpenJDK 11.0.10+9
 - GraalVM version (if different from Java): GraalVM CE 21.0.0
 - Quarkus version or git rev: `master`
 - Build tool: Apache Maven 3.6.3

**Comment by famod** [comment]
There is also a paragraph in https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#build that should be dropped or rewritten:
> By default the build will use the native image server. This speeds up the build, but can cause problems due to the cache
not being invalidated correctly in some cases. To run a build with a new instance of the server you can use
`./mvnw install -Dnative-image.new-server=true`.

(https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#build)

**Comment by zakkak** [comment]
@gsmet shall I prepare a PR for this?

**Comment by zakkak** [comment]
According to https://github.com/oracle/graal/pull/3382#issuecomment-832719462 the server mode is going to be completely removed in the future.
