### ISSUE TITLE
Allow to skip bytecode instrumentation and force a full reload for specific classes

### ISSUE THREAD

**Issue by mariofusco** [quarkusio/quarkus#15330]
**Description**

Quarkus 1.11 introduced bytecode instrumentation to avoid reloading of unchanged classes when not strictly necessary. This improvement doesn't work well with Kogito for the following 2 reasons:

**1. Missing reactivity to changes to an external non-java resource**

**When a resource A referenced within a class B is changed, the class B is not reloaded.**

Our DMN implementation has a Java class that, when loaded, parses as part of static initialization an external resource, with extension .dmn, and stores the result of this parsing into a static field. In Kogito extension we have a CompilationProvider implementation that is notified by Quarkus when a .dmn file is changed and when this happens it regenerates the java class with that static field. 

Although a .dmn change notifies the Kogito extension properly, the bytecode of the newly generated class is identical to the old one (e.g.: “load file model1.dmn” code remains the same). However, before the Quarkus change that I linked above, what Quarkus did during hot reload was reloading the new class which caused the external resource, the only file that actually changed, to be indeed parsed again. Since Quarkus 1.11 it realizes that the bytecode of the regenerated class isn’t changed and then it doesn’t perform the class reloading thus ignoring the changes in the dmn file.

We have been able to consistently reproduce the change of Quarkus devmode hot reload behaviour, and we have been able to find a workaround, by introducing a synthetic static field which will be different at each code generation. We wonder however if it’s possible to explicitly mark a specific class to be reloaded regardless.

**2. Class redefinition failed: attempted to change the class NestHost or NestMembers attribute**

For what regards rules, .drl files, the situation is totally different. When a drl file is changed we regenerate Java classes that are different from the previous version but when these classes are loaded into Quarkus something goes wrong. In particular during the first hot reload everything seems to work even though I see in the terminal an exception saying `java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost or NestMembers attribute`. 

A second change in the drl file triggers another hot reload that breaks everything triggering an exception saying org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: org/mfusco/P01/LambdaPredicate0183C8E09EBA30A9B359FFDB99FF4F85

**Implementation ideas**

For these reasons we need a way to tell Quarkus that for classes generated by the Kogito extension we need to skip bytecode instrumentation and force a full reload regardless of the content of the bytecode.

Introduce a new BuildItem allowing to provide the class names that should skip instrumentation and result in a full reload.

**Comment by geoand** [comment]
Let me try whip up a quick prototype that you can try so we can see if it covers your needs
