### ISSUE TITLE
Resiliency issue while using Emitter and a Channel - Not able to recover if downstream service is down

### ISSUE THREAD

**Issue by anaray** [quarkusio/quarkus#15344]
**Describe the bug**
I created a question in StackOverFlow (https://stackoverflow.com/q/66361285/3573604) but didn't get any response. 

I am proxying incoming http requests to a down stream REST service. Everything works fine if the downstream REST service is up and running, but if that service goes down, all further requests fails with below exception and it never regains even after the downstream service comes back. 

The first failed request never times out and later requests fails with
```
 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-3) Request failed: java.lang.IllegalStateException: SRMSG00028: The subscription to events has been cancelled
```
This is the code and application.properties is given below.
```
@ApplicationScoped
@Path("/")
@Retry(maxRetries = 2)
@Tag(name = "Ingest events", description = "The REST API endpoint for ingesting events")
public class EventGatewayResource {

    private static final Logger LOGGER = Logger.getLogger("EventGatewayResource");

    @Inject
    @Channel("events")
    Emitter<byte[]> eventEmitter;

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(responseCode = "200", description = "{response : success}")
    @APIResponse(responseCode = "500", description = "{response : failure}")
    @Timeout(250)
     public CompletionStage<Response> enqueuePayload(byte[] payload){
               return eventEmitter.send(payload).thenApply(response -> Response.ok(success).build()).exceptionally(throwable -> Response.serverError().build());
    }
                                           
```

**Expected behavior**
The requests after the downstream service comes back must succeed.
The failed request must timeout.

Document on resiliency section.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
The first failed request never timeout.
The quarkus application never regains even after the downstream REST service comes back. It keeps on throwing
java.lang.IllegalStateException: SRMSG00028: The subscription to events has been cancelled

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  Create a quarkus with jax-rs endpoint
2. Create a channel and use emitter to send the data to configured downstream REST service.
3. Do a curl request. Everything should work fine
4. Stop the downstream REST service
5. Do a curl request. At this point the curl will get stuck (does not time out)
6. Do curl requests again. All these will fail with above exceptions.

**Configuration**
```properties
mp.messaging.outgoing.events.connector=smallrye-http
mp.messaging.outgoing.events.method=POST
mp.messaging.outgoing.events.url=http://localhost:9090/event

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin 19.6.0 Darwin Kernel Version
 - Output of `java -version`: openjdk version "11.0.10" 2021-01-19
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
(Add any other context about the problem here.)

**Comment by anaray** [comment]
Quarkus team, 
Any updates here? I am not able recover from a downstream error. Please have a look !

**Comment by cescoffier** [comment]
Can you provide a reproducer (a simple all-in-one project reproducing the issue?)

**Comment by michalszynkiewicz** [comment]
@cescoffier is smallrye-http working properly with Quarkus? 

@anaray does quarkus-http connector work for you?

**Comment by anaray** [comment]
@michalszynkiewicz  I will test using quarkus-http connector . 

From the documentation I see following 

_In the case of consuming an arbitrary object, the reactive-messaging-http extension will attempt to deserialize the request body assuming it is JSON._

In my case I don't want to deserialize the request, I just want pass the incoming byte array as is to the downstream. I assume that there would be option to do that ?

**Comment by anaray** [comment]
@michalszynkiewicz . I used **quarkus-http connector** instead of **smallrye-http**. I also added a custom serializer for bytes[]. Now everything works as expected. Stopping the downstream service doesn't affect the quarkus application. It retries and once the downstream service comes, it connects back. Thank you @cescoffier @michalszynkiewicz 


```
public class ByteSerializer implements Serializer<byte[]> {
    private static final Logger LOGGER = Logger.getLogger("ByteSerializer");

    @Override
    public boolean handles(Object payload) {
        LOGGER.infof("Class %s",
                payload.getClass()
        );
        return payload instanceof byte[];
    }

    @Override
    public Buffer serialize(byte[] payload) {
        LOGGER.infof("Received http body payload %s",
                payload.length
        );
        return Buffer.buffer(payload);
    }

}
```
