### ISSUE TITLE
Cannot import io.quarkus.elasticsearch.restclient.lowlevel.ElasticsearchClientConfig

### ISSUE THREAD

**Issue by Void9711** [quarkusio/quarkus#15346]
**Description**

Cannot import `io.quarkus.elasticsearch.restclient.lowlevel.ElasticsearchClientConfig`

I cannot import `io.quarkus.elasticsearch.restclient.lowlevel.ElasticsearchClientConfig` in my Java code.

Cannot find it anywhere in local jar or online repo.

Code from: [Quarkus - Connecting to an Elasticsearch cluster](https://quarkus.io/guides/elasticsearch#programmatically-configuring-elasticsearch)

Which jar dependency does the annotation **@ElasticsearchClientConfig** locate in?

**Comment by geoand** [comment]
The annotation is available when you add the `quarkus-elasticsearch-rest-client` extension from Quarkus `1.12.0.CR1` onward
