### ISSUE TITLE
RESTEasy Reactive: Chained Sub resources Result in 405 Method not allowed

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#15357]
Describe the bug
Trying to access a chain of sub resources results in a 405 method not allowed. This works perfectly on normal resteasy.

Expected behavior
The sub resources should be located and called

Actual behavior
a 405 is returned

To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

Configuration
Nothing abnormal

Screenshots
Run the reproducer to see failures. Change the pom to non-reactive mode and all tests pass

Environment (please complete the following information):
This is not environment-specific
999-SNAPSHOT and before

Additional context
The project also includes another unrelated bug - uriinfo.getRequestUri.tostring has the query params duplicated

**Comment by geoand** [comment]
@stuartwdouglas is this still an issue even with you #15363 in?

**Comment by bcluap** [comment]
Thanks Stuart & Georgios. Working great
