### ISSUE TITLE
Hibernate orm search with elasticsearch, does not search and retrieve deep attributes from a @OneToOne relationship

### ISSUE THREAD

**Issue by rpinaa** [quarkusio/quarkus#15361]
**Describe the bug**
Using the dependency: quarkus-hibernate-search-orm-elasticsearch, I cannot retrieve deep attributes from a @OneToOne relationship, but I works for @OneToMany and @ManyToMany relationships.

**To Reproduce**

I'm using Quarkus 1.12.0.Final, my related entities are:

@Getter
@Setter
@Accessors(chain = true)
@Entity
@Indexed
@DynamicUpdate
@Table(name = "accesses")
public class SectionIIEntity {

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", updatable = false, unique = true)
  private Long a0;

  @OneToOne(fetch = EAGER, cascade = ALL)
  @JoinColumn(name = "fk_id_requests")
  private SectionIEntity a1;

  @IndexedEmbedded(name = "a2")
  @OneToOne(fetch = EAGER, cascade = ALL, orphanRemoval = true)
  @JoinColumn(name = "fk_id_general_access")
  private SectionIIAEntity a2;

  @KeywordField(
      normalizer = "sort",
      sortable = Sortable.YES,
      valueBridge = @ValueBridgeRef(type = DateTimeBridge.class)
  )
  @Column(name = "created_on")
  @CreationTimestamp
  private LocalDate a3;
}

@Getter
@Setter
@Accessors(chain = true)
@Entity
@Indexed
@DynamicUpdate
@Table(name = "general_accesses")
public class SectionIIAEntity {

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", updatable = false, unique = true)
  private Long a0;

  @JsonbTransient
  @OneToOne(mappedBy = "a2", fetch = LAZY)
  private SectionIIEntity a00;

  @Fetch(SELECT)
  @OneToMany(mappedBy = "a1", fetch = EAGER, cascade = ALL)
  private List<SectionIIAAEntity> a1;

  @Column(name = "general_status_type", length = 254)
  private String a2;

  @FullTextField(analyzer = "keyword")
  @Column(name = "other_general_status", length = 254)
  private String a3;

  @FullTextField(analyzer = "keyword")
  @Column(name = "description", length = 512)
  private String a4;

  @Column(name = "accesses_purpose_type", length = 64)
  private String a5;

  @Column(name = "investigation_type", length = 64)
  private String a6;

  @Column(name = "collection_license_type", length = 64)
  private String a7;

  @Column(name = "collection_mode_type", length = 64)
  private String a8;

  @FullTextField(analyzer = "keyword")
  @Column(name = "other_collection_mode", length = 254)
  private String a9;

  @FullTextField(analyzer = "keyword")
  @Column(name = "business_number", length = 128)
  private String a10;

  @FullTextField(analyzer = "keyword")
  @Column(name = "collection_owner", length = 128)
  private String a11;

  @FullTextField(analyzer = "keyword")
  @Column(name = "project_number", length = 254)
  private String a12;

  @Column(name = "starting_date")
  private LocalDate a13;

  @Column(name = "ending_date")
  private LocalDate a14;
}

**Configuration**
```properties
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.datasource.username=
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200
quarkus.hibernate-search-orm.elasticsearch.version=7
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=bean:elasticSearchConfig
quarkus.hibernate-search-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy=sync

```

**Environment (please complete the following information):**
It's executing in test environment using Junit and Rest assured-

**Additional context**

This is the retrieve business method, where I'm adding "a2.a3", "a2.a4", "a2.a9", "a2.a10", "a2.a11", "a2.a12" to be searched for the "matching".

  @Override
  @Transactional
  public Response retrieveAccesses(final Page page) {
    return Response
        .ok(ofNullable(page.getA3())
            .filter(s -> !s.trim().isEmpty())
            .map(s -> this.searchSession
                .search(SectionIIEntity.class)
                .where(f -> f.simpleQueryString()
                    .fields("a2.a3", "a2.a4", "a2.a9", "a2.a10", "a2.a11", "a2.a12")
                    .matching(s))
                .fetch(20))
            .map(a -> new Pageable()
                .setA0(a
                    .hits()
                    .stream()
                    .map(this.sectionIIAdapter::map)
                    .collect(toList()))
                .setA1(a.total().hitCount()))
            .orElse(new Pageable()
                .setA0(this.sectionIIRepository
                    .findAll()
                    .page(page.getA0(), page.getA1())
                    .stream()
                    .map(this.sectionIIAdapter::map)
                    .collect(toList()))
                .setA1(this.sectionIIRepository.count())))
        .build();
  }

In "test" mode I create the following JSON using the import.sql:

```
{
	"a0": [{
		"a0": 1,
		"a2": {
			"a1": [{
				"a0": 2,
				"a2": "PDF",
				"a3": "prueba",
				"a4": "512"
			}],
			"a10": "C02L13",
			"a11": "C02L13",
			"a12": "C02L13",
			"a13": "2019-05-25",
			"a14": "2019-05-25",
			"a2": {
				"d0": "C01L11",
				"d1": "Correo electrónico"
			},
			"a3": "C01L12",
			"a4": "C01L13",
			"a5": {
				"d0": "C01L14",
				"d1": "Escrito presentado ante Semarnat"
			},
			"a6": {
				"d0": "C01L15",
				"d1": "Otro"
			},
			"a7": {
				"d0": "C02L11",
				"d1": "Solicitud de acceso"
			},
			"a8": {
				"d0": "C02L12",
				"d1": "Solicitud de información para el acceso"
			},
			"a9": "C02L13"
		}
	}],
	"a1": 1
}
```

When I send the matching value "C02L13", I get the following response:
```
{
	"a0": [

	],
	"a1": 0
}
```
This is my starting up, where I can see two indexes that were added correctly on the Elasticsearch in single node configuration.

```
er.uuid": "YVOz0iRJSvKjuIcZBcdDyA", "node.id": "IjQuEeqvR9WlBwzF9rkgkg"  }
[INFO] DOCKER> [docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1] "elasticsearch": Waited on url http://localhost:9200 8384 ms
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ mx-puntofocal-pn-accesses ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running mx.semarnat.puntofocal.PuntofocalAccessesApplicationTest
20:02:38.849 Elasticsearch:{"type": "server", "timestamp": "2021-02-28T20:02:38,848Z", "level": "INFO", "component": "o.e.c.m.MetadataCreateIndexService", "cluster.name": "docker-cluster", "node.name": "4c8d3f4791bc", "message": "[sectioniientity-000001] creating index, cause [api], templates [], shards [1]/[1]", "cluster.uuid": "YVOz0iRJSvKjuIcZBcdDyA", "node.id": "IjQuEeqvR9WlBwzF9rkgkg"  }
20:02:38.952 Elasticsearch:{"type": "server", "timestamp": "2021-02-28T20:02:38,952Z", "level": "INFO", "component": "o.e.c.m.MetadataCreateIndexService", "cluster.name": "docker-cluster", "node.name": "4c8d3f4791bc", "message": "[sectioniiaentity-000001] creating index, cause [api], templates [], shards [1]/[1]", "cluster.uuid": "YVOz0iRJSvKjuIcZBcdDyA", "node.id": "IjQuEeqvR9WlBwzF9rkgkg"  }
2021-02-28 20:02:39,122 INFO  [io.quarkus] (main) Quarkus 1.12.0.Final on JVM started in 7.606s. Listening on: http://localhost:8081
2021-02-28 20:02:39,123 INFO  [io.quarkus] (main) Profile test activated. 
2021-02-28 20:02:39,123 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-search-elasticsearch, hibernate-validator, jdbc-h2, jdbc-postgresql, mutiny, narayana-jta, oidc, resteasy, resteasy-jsonb, security, smallrye-context-propagation]
```
If I try with a OneToMany or ManyToMany relationships the search works correctly.

**Comment by gsmet** [comment]
Please create a simple Maven project allowing to reproduce the issue. Thanks!

**Comment by rpinaa** [comment]
@gsmet Thanks, I could detect the problem, it was that I should set the bidirectional attribute and execute two persistence phases, before for SectionIIAEntity and then for SectionIIEntity, adding the right setter convention. It's working fine.

**Comment by yrodiere** [comment]
@rpinaa Thanks for confirming this was an error on your end.

Closing as invalid.
