### ISSUE TITLE
Panache Data REST: Update method requires at least two connections

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15369]
**Describe the bug**
I have a resource called:

```java
public interface ApplicationResource extends PanacheEntityResource<ApplicationEntity, Long> {
}
```

This endpoint exposes all the REST methods. The problem is that the PUT method (update) requires a minimal of two connections. So, if we limit the amount of connections using this property:

```
quarkus.datasource.jdbc.max-size=1
```

The update method will fail with:

```
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
```

This is a regression issue that was entered as part of this commit: https://github.com/quarkusio/quarkus/commit/8c76e39060f6b288eaaeeb28bc477b33a972a40f. In this commit, the `@Transactional` annotations were removed from the REST methods and added into the inner methods. The problem with the update implementation is that is calling two inner methods (get and update). 

**Expected behavior**
All REST methods should use only one connection.

**Actual behavior**
PUT REST method needs at least two connections.

**To Reproduce**
1- git clone `https://github.com/Sgitario/beefy-scenarios`
2- cd beefy-scenarios/014-quarkus-panache-with-transactions-xa
3- git checkout reproducer_15369
4-mvn clean install (it needs to have built quarkus master locally)

This example is basically doing this:

1. Create a resource
2. Update the existing resource -> here it fails

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT (1.12.1.Final)

**Comment by Sgitario** [comment]
cc @gytis

**Comment by gytis** [comment]
Seems that we might need to start and commit a transaction ourselves and not rely on CDI interceptors in this method.

**Comment by gsmet** [comment]
@gytis you can use interceptors but you need to call only one intercepted method that wraps the two calls.

**Comment by FroMage** [comment]
> Expected behavior
> All REST methods should use only one connection.

To be honest, this doesn't seem to me like an obvious requirement. WDYT @gavinking or @Sanne ?

**Comment by Sanne** [comment]
> All REST methods should use only one connection.

Well stating "All REST methods should use only one connection" literally is a too strong requirement, as there's of course many use cases that are totally fine to use two.

But the devil is in the detail, if we need to open a second connection while still holding the first one, then there's a risk of deadlocks to happen when the connection pool is close to exhaustion - so indeed that pattern needs to be strictly avoided, and if we need two connections to be held open in parallel this must have been requested explicitly by the user.

I haven't had the time to reproduce this issue, but is it still the case on master? We recently improved some things in a related area; e.g. see #14305

**Comment by Sanne** [comment]
BTW this seems like the real issue:

> This is a regression issue that was entered as part of this commit: 8c76e39. In this commit, the @Transactional annotations were removed from the REST methods and added into the inner methods. The problem with the update implementation is that is calling two inner methods (get and update).

Essentially this means it's implementing a "transactional update" by performing two independent transactions, a get followed by an update?
That's definitely wrong, you want both operations to be wrapped by the same, single transaction.

**Comment by FroMage** [comment]
OK, right, single transaction is definitely a requirement, we can agree on that :)

**Comment by gytis** [comment]
I'm fixing this already. Although, transactionally this might not be as dangerous at it sounds. The initial find is used by the JAX-RS resource to know what response to return at the end (201 or 204). Then the same update operation is performed regardless of what was the result of the find. Even if the state would change in-between find and update, the inconsistency would be in the HTTP status code, not in the data.
