### ISSUE TITLE
ENVs required in prod profile break dev profile but only when using the built artifact

### ISSUE THREAD

**Issue by atamanroman** [quarkusio/quarkus#15389]
**Describe the bug**

Quarkus tries to resolve ENVs for profiles which are not active. This breaks other profiles. This only happens with the built jar. It works fine with the `quarkus:dev` plugin.

Example:

Empty Quarkus project with `%prod.quarkus.http.port=${HTTP_PORT}` as the only configuration in `application.properties` breaks every other profile when running from jar if `HTTP_PORT` is not exported. 

**Expected behavior**

If `HTTP_PORT` is not set application should start fine with any profile but `prod`. `HTTP_PORT` is only required in `prod`.

**Actual behavior**

Quarkus tries to resolve `HTTP_PORT` regardless of the active profile and fails to start.

```
QUARKUS_PROFILE=foo java -jar target/quarkus-app/quarkus-run.jar
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00011: Could not expand value HTTP_PORT in property quarkus.http.port
```

**To Reproduce**

https://github.com/atamanroman/quarkus-profile-dev-prod-repro

Steps to reproduce here:

https://github.com/atamanroman/quarkus-profile-dev-prod-repro/blob/main/README.md

**Additional context**

This issue was opened after discussion in [this zulip thread](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/ENVs.20required.20in.20prod.20profile.20break.20dev).

**Comment by gsmet** [comment]
Reopening this as I had to revert the commit for the Final.
