### ISSUE TITLE
Federated GraphQL service

### ISSUE THREAD

**Issue by KSmigielski** [quarkusio/quarkus#15386]
**Describe the extension**
The main purpose of the extension is to create a tool that will allow you to easily create microservices compliant with the   [GraphQL Federation Specification created by Apollo Graph Inc.](https://www.apollographql.com/docs/federation/federation-spec/l)

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
At this point, the only configuration I can think of is the ability to specify a resource containing GraphQL schema.value
```properties
quakus.federated-graphql.schema-location=/schema.graphql #default value
```
**Additional context**
Federated GraphQL is a standard for creating GraphQL schemas in distributed systems. The gateway service is responsible for breaking the query into the appropriate parts and distributing them to the appropriate microservices. 
This extenstion is the first step for Quarkus. It allows you to create microservices that can connect to a gateway provided by Apollo Graph Inc. The next step will be to create an extension that will create a gateway to Federeted GraphQL according to the standard. Thanks to the native Quarkus compilation, it will allow you to create a very efficient distributed system supporting GraphQL.

**Comment by phillip-kruger** [comment]
This is already an issue on the SmallRye GraphQL issue board, and once added there should come in as part of the current GraphQL Extension

**Comment by KSmigielski** [comment]
Thanks for the answer. I didn't know there was such a topic already. I will look at it and maybe I can help there 😄 
[SmallRye GraphQL issue](https://github.com/smallrye/smallrye-graphql/issues/521)
