### ISSUE TITLE
When I run Jmeter for testing a native executable of getting-started project, the server seems to hang

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#1539]
I run a native executable of getting-started project,everything is normal。
![2](https://user-images.githubusercontent.com/48646226/54489791-1b0f1b00-48eb-11e9-9eba-7fbb4ebc0be6.PNG)
![01](https://user-images.githubusercontent.com/48646226/54489814-5dd0f300-48eb-11e9-86b6-e3e2db4ac2db.PNG)
![0](https://user-images.githubusercontent.com/48646226/54489820-6aede200-48eb-11e9-857a-c3d6b59bdff3.PNG)

but when I run JMeter for testing the native executable of getting-started project, the server seems to hang.
![1](https://user-images.githubusercontent.com/48646226/54489823-78a36780-48eb-11e9-97ad-750b2e87c4ea.PNG)
![3](https://user-images.githubusercontent.com/48646226/54489827-85c05680-48eb-11e9-85b1-33892247940b.PNG)

**Comment by yuhaibohotmail** [comment]
My environment is:
ubuntu-18.04.1.0
graalvm-ce-1.0.0-rc13
Quarkus 0.11.0

**Comment by geoand** [comment]
@yuhaibohotmail perhaps you would like to compare your test with https://github.com/johnaohara/pingperf#jmeter-load-tests-results?
