### ISSUE TITLE
Make quarkus.datasource.db-kind overridable at runtime

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#15403]
I have an application that uses a relational database and the database type is selected when the application is installed (mysql, mariadb, mssql and oracle). Right now, since the property `db-kind` is fixed at build time, I have to compile four different times the same application, one for each database type. 
With hibernate the application code is already independent from the implementation, so being able to define the whole data source at runtime would make things easier.
I know it won't work for the native image, but JIT is totally fine.

**Comment by geoand** [comment]
This has been discussed before and it's something we really don't want to do.

cc @Sanne @gsmet

**Comment by gsmet** [comment]
Yeah, I asked @iompo to open an issue so that we can gather feedback on this. I explained for now we weren't considering it.

**Comment by ge0ffrey** [comment]
This is an issue for optaweb-vehicle-routing and optaweb-employee-rostering: "While we don't aim to support multiple different DBs out of the box, this Quarkus limitation makes it difficult to run Cypress integration tests against the standalone artifact because we can't build it for PostgreSQL and use H2 for integration tests at the same time. We can't have both in the same module."

**Comment by myannou** [comment]
This limitation is an issue when you want to deliver a software with an agnostic DB (Postgresql, h2, Oracle, ...)
This is my situation for a customer.
I know it exists a way to do it with "[Re-augmenting a Quarkus Application](https://github.com/quarkusio/quarkus/pull/16606/files?short_path=807c7b8#diff-807c7b894545841a2c1b78235411bac63febcf5603e2c61004c21e5869521958)" 
but then it won't work with the native way

@geoand : what are the reasons you really don't want to do it ? (I guest it is a tricky issue...)

**Comment by maxandersen** [comment]
Reasons why we don't want to do it is that it then prevents us from doing a lot of the optimizations that makes Quarkus app start up fast in devmode, java vm and native mode. If this was not a build time flag we'll be back to old approach that makes java apps slow and heavy.

Thus for now if you want to support multiple databases then explicitly configure multiple datasources with appropriate drivers or use reaugmentation.

There is no easy solution here without paying too high a cost for general startup time and memory consumption.

I'm going to close this as wont-fix for now. If new ideas or approaches becomes available a new issue/pr can be made.
