### ISSUE TITLE
w3c tracing headers support

### ISSUE THREAD

**Issue by anmiralles** [quarkusio/quarkus#15408]
**Description**
Hi everyone,

we are trying to follow CloudEvent standard in order to trace request through different micros and systems (Kafka broker). The problem right now is quarkus-smallrye-opentracing dependency is internally using an old jaeger-core lib which still doesn't support w3c standards for tracing:

https://www.w3.org/TR/trace-context/

Trace context is split into two individual propagation fields supporting interoperability and vendor-specific extensibility:
- traceparent 
- tracestate

**Implementation ideas**
Upgrade quarkus-jaeger internal dependencies to:

<dependency>
    <groupId>io.jaegertracing</groupId>
    <artifactId>jaeger-core</artifactId>
    <version>1.5.0</version>
</dependency>

Thanks in advance.

**Comment by kenfinnigan** [comment]
OpenTracing is no longer maintained.

The best way to get W3C tracing header support is when the OpenTelemetry extension is included: https://github.com/quarkusio/quarkus/issues/10499
