### ISSUE TITLE
Send micrometer metrics for vertx pools

### ISSUE THREAD

**Issue by andrerigon** [quarkusio/quarkus#15410]
**Description**
We'd benefit from monitoring vertx worker and event loop pools so we can detect/alarm long waiting and tune pool sizes if needed. 

**Implementation ideas**
I'd suggest using micrometers executor service wrapper: https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java#L316

**Comment by ebullient** [comment]
This set: https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/VertxPoolMetrics.java ?

**Comment by himanshumps** [comment]
I think we need the vertx webclient metrics as well to be shown as most of the microservices use rest communication to get the data. The list is huge as there is no predefined set for communication between applications(kafka, amqp, ....)

**Comment by beatrizacbs** [comment]
Does this already contains the sugestion to also export eventbus metrics? If not, I would also add that. I believe that many people need this metric.

**Comment by ebullient** [comment]
Resolved by #30150

**Comment by cescoffier** [comment]
Yes, you will be able to monitor Vert.x pools (including worker pools, connection pools...)

**Comment by cescoffier** [comment]
To answer many of the comments here:

#30150 does:

- implement event bus metrics (@beatrizacbs)
- add metrics for the web clients (opt-in by setting the client name) (@himanshumps)
- implement the pool metrics and the client metrics

**Comment by ebullient** [comment]
Going to close this one as resolved by #30150 

If we have other gaps, I'd like another issue raised w/ what the remaining gaps are.

**Comment by cjbooms** [comment]
This issue seems to have been hijacked by a comment requesting eventbus metrics instead of event (loop) pool metrics, the former is added in #30150, but the latter (which this issue relates to) is not.
