### ISSUE TITLE
RBAC is generated incorrectly when namespace is set with kubernetes-config

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15422]
**Describe the bug**
When the namespace property is set the generated role/rolebinding is the same as if it the property were not set.  This leads to a start-up error.

**Expected behavior**
A clusterrole and a rolebinding that specifies the target namespace should be generated.

**To Reproduce**
set the quarkus.kubernetes-config.namespace and deploy with RBAC enabled.  

**Configuration**
```properties
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.secrets.enabled=true
quarkus.kubernetes-config.secrets=test-secret
quarkus.kubernetes-config.namespace=x
```

**Comment by geoand** [comment]
@iocanel what is the proper way to add a namespace to the RBAC resources only?

**Comment by shawkins** [comment]
There are two problems here.  The first is that namespace is not a build time property - so you don't know if it's being used when the role information is built.

The second is that the role construction logic doesn't handle this scenario regardless.  Preferably you would create a clusterrole and have the rolebinding specify the target namespace - https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

**Comment by iocanel** [comment]
I think that we need to introduce a decorator for this. Limiting the scope of a decorator to a subset of resources is fairly trivial.

**Comment by shawkins** [comment]
@iocanel the current logic KubernetesRoleBindingBuildItem does support a clusterWide flag, which will create a cluster role.  However there is nowhere to specify the namespace for the role binding.  Also since namespace is not a build time property it won't be available when needed.

**Comment by geoand** [comment]
Feel free to assign it yourself then :)
