### ISSUE TITLE
SmallRye OpenAPI generates incorrect content type when using Spring Web annotations

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#15443]
**Bug description**
`quarkus-smallrye-openapi` extension does not generate correct content type based on Spring Web annotation provided by `quarkus-spring-web` extension when generating OpenAPI schema (calling `/q/openapi` endpoint).

Instead of picking up the content type specified by Spring annotation
```
@...Mapping(produces = <desired-content-type>)
```
it generates response content type `application/json`.

The content type of the application endpoint response itself is correct and unaffected by this bug.

**Expected output**
```
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /greeting:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

**Actual output**
```
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /greeting:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
```

**To Reproduce**

[smallrye-openapi-spring-web-reproducer.zip](https://github.com/quarkusio/quarkus/files/6077185/smallrye-openapi-spring-web-reproducer.zip)

1. Use both extensions together:
    - quarkus-smallrye-openapi
    - quarkus-spring-web
2. Define endpoint using Spring annotations and specify response content type, e.g.
```
@RestController
@RequestMapping("/greeting")
public class GreetingController {

    @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
    public String hello() {
        return "Hello Spring";
    }
}
```
3. Call OpenAPI endpoint `/q/openapi`.

**Environment (please complete the following information):**
 - `java -version`:
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
 - GraalVM version: 20.3.1
 - Quarkus version: 1.12.0.Final
 - Build tool: Apache Maven 3.6.3

**Comment by geoand** [comment]
@phillip-kruger this is something that would need to fixed in SR, right?

**Comment by phillip-kruger** [comment]
Yip, I'll have a look a.s.a.p

**Comment by geoand** [comment]
Thanks!

**Comment by phillip-kruger** [comment]
This is now fix in SmallRye. Once we have done a release and pull the new version into Quarkus this should be resolved.

**Comment by jsmrcka** [comment]
https://github.com/jsmrcka/beefy-scenarios/tree/QUARKUS-849/603-spring-web-smallrye-openapi

Here is a more comprehensive test scenario, which covers other `@...Mapping` annotations as well as the use of both the `consumes` and `produces` attributes.
On current master, it fails in 14 out of 45 tests.
Problematic annotations include `@DeleteMapping`, `@GetMapping`, `@PatchMapping`, `@PutMapping`. All of them fail when `produces`/`consumes` defines anything but `application/json`.

**Comment by phillip-kruger** [comment]
Thanks. I am busy with a SR release that will then be pulled into Quarkus, please can you then (I'll let you know) rerun these

**Comment by jsmrcka** [comment]
@phillip-kruger Sure, just say the word.

**Comment by phillip-kruger** [comment]
As soon at https://github.com/quarkusio/quarkus/pull/15489 is merged you can check again.

**Comment by phillip-kruger** [comment]
@jsmrcka  Fix is merged and in master. Please can you confirm that it's fixed. Thanks :)

**Comment by jsmrcka** [comment]
The aforementioned test scenario is passing now on master. :)

**Comment by jsmrcka** [comment]
@phillip-kruger I have one more question regarding Spring Web + SmallRye OpenAPI.

It is not clear to me, what is the desired behavior when the content type is not specified in code. Current solution generates `application/json` as a default and is consistent with Quarkus JAX-RS approach. But that diverges from native Spring solution, which in such cases generates `*/*` in the OpenAPI schema.

**Comment by phillip-kruger** [comment]
Yea not sure, the default changes for Quarkus in general, that is why you see Json, but maybe @geoand knows what the rule should be for Spring

**Comment by geoand** [comment]
I am pretty sure we have Json as the default for Spring as well

**Comment by jsmrcka** [comment]
@geoand Well, if I do something like this in Spring:
```
...
    @GetMapping("/greeting")
    public String hello() {
        return "hello";
    }
...
```
it will produce this YAML:
```
...
  /greeting:
    get:
      tags:
      - demo-resource
      operationId: hello
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
...
```
(using org.springdoc:springdoc-openapi-ui).

And one of the Quarkus Spring guides (https://quarkus.io/guides/spring-web#adding-openapi-and-swagger-ui) also presents the `*/*` wildcard in its examples.

**Comment by geoand** [comment]
I'll need to look at it again as I don't really remember what we use as the default.

**Comment by jsmrcka** [comment]
Anyway, as far as Quarkus goes, the desired status is JSON as the default, as documented e.g. here: https://quarkus.io/guides/rest-client#create-the-interface.
So the Quarkus Spring Web guide is kind of misleading: https://quarkus.io/guides/spring-web#adding-openapi-and-swagger-ui. 

Right?

**Comment by geoand** [comment]
Yes, I opened https://github.com/quarkusio/quarkus/pull/15534 to fix the doc
