### ISSUE TITLE
Quarkus 1.12.1.Final doesnt honor the path declared in the javax.ws.rs.core.Application

### ISSUE THREAD

**Issue by dbl81** [quarkusio/quarkus#15458]
**Describe the bug**
I chose to implement a javax.ws.rs.core.Application because of some OpenAPI values I would like define there (info, security and so on). I defined the base path of my application inside the javax.ws.rs.core.Application class, with the Path() annotation.  
Quarkus ignores the declared path. The resources still work with their declared path without the prefix path declared inside the javax.ws.rs.core.Application class.

Following an example:
*  javax.ws.rs.core.Application class with Path("/application")
*  resource with Path("/resource")

I can successfully call the rest resource with the path */resource*, but it doesnt work with the path */application/resource*.

**Expected behavior**
I should be able to successfully call the */application/resource* endpoint.

**Actual behavior**
I can successfully call the rest resource with the path */resource*, but **it doesnt work** with the path */application/resource*.

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).  
https://github.com/dbl81/applicationpath.git

1.  clone the repo
2.  mvn compile quarkus:dev
3.  browse: http://localhost:8080/application/resource --> 404
4.  browse: http://localhost:8080/resource  --> 200 (plain text response "hello")

**Configuration**
```properties
```

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 Home Edition
 - Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: 1.12.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: C:\Program Files\jdk-11.0.7.10-hotspot
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Additional context**

**Comment by ebullient** [comment]
Yes -- my guess is that this will behave as expected with the leading '/' removed (so that the specified endpoint Path remains relative to the overall Application Path

**Comment by ebullient** [comment]
I've double checked our tests, and we managed not to have a test for the combination of non-root application path and nested resource paths beginning with '/'.

Guillaume, I'll work on a fix for this, but for now, the clear work around is to remove the leading slash in @Path annotations, as they are ignored anyway.

**Comment by ebullient** [comment]
hmm. That's discouraging. For curiuosity's sake, can you flip to resteasy (alone) and not resteasy-reactive?

**Comment by dbl81** [comment]
I was using resteasy (**not** the reactive implementation), I'm sorry I didnt mention it before!
I ran my previous test on resteasy (not reactive) and the example I published (branch called *main*) has resteasy as dependency.

Following your (inverse) input I switched to resteasy-reactive and I faced the same problems. I pushed the new code to the branch called reactive.

**Comment by ebullient** [comment]
I am an idiot.. and I didn't read closely enough (there is still something in resteasy reactive to look at, BUT).. 
What you have in the reproducer at the moment is two peer application scoped paths: 

```java
@ApplicationScoped
@Path("resource")
public class ExampleResource {
...
}
```
and
```java
@ApplicationScoped
@Path("/application")
public class ExampleApplication extends Application {
}
```

There isn't anything that implies these two are anything other than siblings. What you intended, I think, was to specify an application path, so you should change the latter to the following:
```java
@ApplicationScoped
@ApplicationPath("/application")
public class ExampleApplication extends Application {
}
```

I see the correct behavior with this change. Which I think begs a different question about how a plain `@Path` annotation should be handled, which was your original question. With all the URL craziness going on, my brain went somewhere else instead..

**Comment by ebullient** [comment]
According to the spec (as I quoted earlier), `@Path` annotations always specify relative. To define the base URI for your whole application, you need to use `@ApplicationPath`.

**Comment by dbl81** [comment]
OMG, shame on me! I'm really sorry for bothering!
I followed your hint and it worked like a charm.

Hoping next time I can help you in inproving the cool Quarkus.
I close this issue.
