### ISSUE TITLE
Kafka Health Check readiness is always down until It's consumed the first time

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15464]
**Describe the bug**
Given an application with the following extensions:

- `pom.xml`:

```xml
         <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kafka-streams</artifactId>
        </dependency>
```

That creates a custom topology:

```java
@Produces
    public Topology buildTopology() {
        StreamsBuilder builder = new StreamsBuilder();

        JsonbSerde<LoginAttempt> loginAttemptSerde = new JsonbSerde<>(LoginAttempt.class);
        JsonbSerde<LoginAggregation> loginAggregationSerde = new JsonbSerde<>(LoginAggregation.class);

        builder.stream("from", Consumed.with(Serdes.String(), loginAttemptSerde))
                .groupByKey()
                .windowedBy(TimeWindows.of(Duration.ofSeconds(windowsLoginSec)))
                .aggregate(LoginAggregation::new,
                        (id, value, aggregation) -> aggregation.updateFrom(value),
                        Materialized.<String, LoginAggregation, WindowStore<Bytes, byte[]>> as(LOGIN_AGGREGATION_STORE)
                                .withKeySerde(Serdes.String())
                                .withValueSerde(loginAggregationSerde))
                .toStream()
                .filter((k, v) -> (v.getCode() == UNAUTHORIZED.getStatusCode() || v.getCode() == FORBIDDEN.getStatusCode()))
                .filter((k,v) -> v.getCount() > threshold)
                .to("target");

        return builder.build();
    }
```

Spite of the application is correctly working, the health check readiness says that the "target" is down:

```json
{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "login-http-response-values": "[OK]",
                "login-denied": "[KO]"
            }
        },
        {
            "name": "Kafka Streams topics health check",
            "status": "UP",
            "data": {
                "available_topics": "login-http-response-values"
            }
        }
    ]
}
```

This was working fine prior to 1.12.0.Final.

**Expected behavior**
Health check should be UP.

**Actual behavior**
Health check is DOWN in 1.12.0.Final, 999-SNAPSHOT.

**To Reproduce**
1. git clone https://github.com/Sgitario/quarkus-examples
2. cd reproducers/kafka-streams-reactive-messaging
3. mvn clean install -Dquarkus.version=1.12.0.Final
It fails because the test checks whether the health check is UP.

If we build the reproducer with `mvn clean install -Dquarkus.version=1.11.5.Final`, it works:

```
{
    "status": "UP",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "login-http-response-values": "[OK]",
                "target": "[OK]"
            }
        },
        {
            "name": "Kafka Streams topics health check",
            "status": "UP",
            "data": {
                "available_topics": "login-http-response-values"
            }
        }
    ]
}
```

 - Quarkus version or git rev: 1.12.0.Final and 999-SNAPSHOT

**Comment by cescoffier** [comment]
Can you tell me who's is consuming the `login-denied` channel?

**Comment by Sgitario** [comment]
To sum up, the Health Check readiness will be DOWN until the channel starts being in use. In the reproducer example, the consumer is:

```
@Inject
    @Channel("login-alerts")
    Publisher<String> alerts;

    @GET
    @Path("/monitor/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType("application/json")
    public Publisher<String> stream() {
        return alerts;
    }
```

After the above path is called, the Health Check will became UP. 

Note that this current strategy will not work in K8s or OpenShift as the Health endpoints are used to start accepting connections, so it needs to be disabled. 

Pending actions:
- Update docs to disable the channel
- Update migration guide so users are aware of this change

**Comment by rsvoboda** [comment]
K8s or OpenShift ...  that's a good concern

**Comment by cescoffier** [comment]
I've opened #15533 updating the guide.

**Comment by rsvoboda** [comment]
So the conclusion for this issue is to keep the behavior as is and only document how to disable it?

**Comment by cescoffier** [comment]
Yes, until we find a better way to implement the check.

**Comment by Sgitario** [comment]
> Yes, until we find a better way to implement the check.

Thanks for the update on docs. As this is a breaking change for users using Kafka on OpenShift/K8S, how should we state this change in the migration guide?

**Comment by cescoffier** [comment]
@Sgitario I added a note to the migration guide.
