### ISSUE TITLE
Add a mechanism to include other fragments in the kubernetes deployment file(s)

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15469]
**Description**
There are currently limited facilities for generating RBAC resources like Roles, and RoleBindings.  It would be great if the kubernetes extension had a way to include other files in the main generated kubernetes deployment file.  Or should we be looking to use something like jkube instead?

**Comment by geoand** [comment]
What other files you have in mind?

**Comment by shawkins** [comment]
One or more yaml files containing kubernetes resources.  In our case a Role, RoleBinding, ClusterRole, and ClusterRoleBinding.  

When working in dev we have to create/apply those files separately, then do the maven deployment of the quarkus image - having all of that happen as part of the maven command would be great.

For the final consumption of the build artifacts it would also be nice to have all of that in a single file.

I recall other frameworks (thorntail?, spring boot?) having a facility for an openshift/kubernetes include folder, but it looks like jkube handles this nicely as well.

**Comment by geoand** [comment]
Currently do support adding snippets in `src/main/kubernetes` (see https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources) but I don't think it applies to any random resource.

@iocanel sounds doable, no?

**Comment by shawkins** [comment]
I'm guilty of not seeing that doc section.  We initially had files named things like role.yaml in the src/main/kubernetes directory, which are not picked up by this mechanism so assumed that this facility wasn't available.  Having a single file named kubernetes.yml works as expected.  This can be closed.

**Comment by geoand** [comment]
Cool!
