### ISSUE TITLE
Kafka Health Check guide is misleading about how to enable/disable it

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15460]
**Description**
The section https://quarkus.io/guides/kafka#kafka-health-check is misleading as:
- It's not disabled by default (unless when using reactive messaging which I think it's always)
- We cannot disable it using the property "quarkus.kafka.health.enabled". But works when using "quarkus.reactive-messaging.health.enabled".

Indeed, there are a few related issues because of the same confusing section:
- https://github.com/quarkusio/quarkus/issues/15321
- https://github.com/quarkusio/quarkus/issues/13920

I would have directly provided a pull request with the clarifications, but I'm unclear about the next points:
- Is the health check kafka disabled by default in all the Kafka extensions? When it's enabled and when it's not.
- When should we use this property "quarkus.kafka.health.enabled" and when "quarkus.reactive-messaging.health.enabled".

Thanks in advance for the clarifications

**Comment by cescoffier** [comment]
I already opened a PR extending that section. The PR has been merged already.

**Comment by Sgitario** [comment]
Thanks @cescoffier . I see the PR you mentioned https://github.com/quarkusio/quarkus/pull/15368.
