### ISSUE TITLE
Quarkus (Gradle) build should not run tests

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#15471]
## Description

While building the application I've noticed that `./gradlew build -Dquarkus.package.type=fast-jar` will also run all the tests:

```shell
[x80486@uplink:~/Workshop/Development/kotlin-quarkus]$ ./gradlew build -Dquarkus.package.type=fast-jar 
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Task :quarkusGenerateCode
preparing quarkus application

> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :processResources
> Task :classes
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip

> Task :quarkusGenerateCodeTests
preparing quarkus application

> Task :compileTestKotlin
> Task :compileTestJava NO-SOURCE
> Task :processTestResources
> Task :testClasses
> Task :test

> Task :quarkusBuild
building quarkus jar

> Task :assemble
> Task :check
> Task :build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
13 actionable tasks: 13 executed
```

I think this should be avoided because that's a different (usually time consuming) stage/task that's triggered on a different phase.

## Implementation Ideas

Make the Gradle (and/or Maven) plugin avoid `check` and/or `test`, somehow like this command: `./gradlew -Dquarkus.package.type=fast-jar build --exclude-task=check` — that simple I guess 😓

**Comment by x80486** [comment]
And just a side note, I think with `1.12.x` the Gradle `build` task is defaulting to a "fast-jar", so I guess the [Gradle Tooling](https://quarkus.io/guides/gradle-tooling#using-fast-jar) guide might need some changes 😎

**Comment by glefloch** [comment]
Actually `build` is a default gradle task. If you only need the quarkus build, you can call the `quarkusBuild` task which does not depend on test.

**Comment by gastaldi** [comment]
Sounds like this issue has been answered and can be closed.

**Comment by gsmet** [comment]
Hmmm, except the doc part that needs an update for fast-jar. @glefloch could you have a look at it?

**Comment by glefloch** [comment]
yes, I'm going to update the docs.
