### ISSUE TITLE
Quarkiverse extension for the Java Operator SDK

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#15478]
**Description**
The [Java Operator SDK project](https://github.com/java-operator-sdk/java-operator-sdk)  has a Quarkus extension that we would like to migrate to the Quarkiverse. I (@metacosm) will be leading the work. Requested repo name would be: `quarkus-operator-sdk`.

Thanks in advance.

**Comment by gastaldi** [comment]
Awesome, can you give a small description on what this extension does?

**Comment by metacosm** [comment]
It's an extension that makes it easy to create kubernetes operators in Java.

**Comment by gastaldi** [comment]
Created in https://github.com/quarkiverse/quarkus-operator-sdk

**Comment by metacosm** [comment]
Thank you!
