### ISSUE TITLE
OpenShift plugin not deploying the Quarkus App (Regression Issue)

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15487]
**Describe the bug**
This is a regression issue caused by this commit: https://github.com/quarkusio/quarkus/commit/588db63138715a4e1e2a112676ab9ece2fab36ca

When using the OpenShift Quarkus extension to deploy our Quarkus app:

```
mvn package -Dquarkus.kubernetes.deploy=true
```

Then, the BuildConfig and the Build are triggered in OpenShift and when the Build instance finished, It's deleted (see the commit changes). Then, the DeploymentConfig does not trigger the application startup spite of the image stream is there. For some reason, the DeploymentConfig depends on the build instance to not be deleted. 

After reverting the changes in https://github.com/quarkusio/quarkus/commit/588db63138715a4e1e2a112676ab9ece2fab36ca, the Build instance is not deleted and hence everything works fine.

**To Reproduce**
For your Quarkus application:

```
mvn package -Dquarkus.kubernetes.deploy=true
```

The application will not be deployed into OpenShift. The same works for 1.12.0.Final and also by reverting the commit: https://github.com/quarkusio/quarkus/commit/588db63138715a4e1e2a112676ab9ece2fab36ca

**Environment (please complete the following information):**
 - OpenShift: 4.6
 - Quarkus version or git rev: 1.12.1.Final, 999-SNAPSHOT

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@iocanel @geoand this one needs to be diagnosed quickly as this particular commit has been backported to 1.11.

**Comment by geoand** [comment]
I have assigned Ioannis to it
