### ISSUE TITLE
Automated warning about deprecated configuration properties

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#15486]
Introduce automated warning about deprecated configuration properties so Quarkus users are aware of it without the need to look at the source code of the config classes.

There are 2 aspects to be covered:
 - build time information 
 - information in guides
 
1) build time information 
An automated warning when using deprecated configuration properties should appear in the log.
Similar functionality is already present for unused properties.

2) information in guides
https://quarkus.io/guides/all-config and properties listed at the end of many guides should contain information which config properties are deprecated and what's their replacement.

Adding @gsmet and @geoand into the loop, the final trigger to file this request for enhancement was route/ingress configuration PR and discussion there.

**Comment by geoand** [comment]
This is a great idea

**Comment by radcortez** [comment]
This was implemented in https://github.com/quarkusio/quarkus/pull/30603.
