### ISSUE TITLE
Support CDI decorators

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#15490]
Support decorators

We tend to favor composition over inheritance, so when it's suitable we split features in a decorator/delegate pattern which also makes it easier to test different concerns in isolation. For example it could be something like this:

```
interface DataLoader {
  Data load();
}

class DefaultDataLoader implements DataLoader {
  public Data load() {
    return ...
  }
}

class ValidatingDataLoader implements DataLoader {

  DataLoader delegate;

  public Data load() {
    return validate(delegate.load())
  }
}

class CachingDataLoader implements DataLoader {

  DataLoader delegate;

  public Data load() {
    return cache(delegate.load())
  }
}
```

Also we have a multi module project and try to clearly split API from implementation so in some cases the decorators shouldn't know about other decorators or the base/default implementation (in the example the CachingDataLoader shouldn't know about DefaultDataLoader for example, just about the DataLoader interface which is the API). In addition, if the base implementation has some qualifiers the decorators shouldn't need to know or repeat those to work properly (unless required by their logic).

This clearly fits the CDI decorator pattern and without it the only workarounds I can think of to get everything wired/injected and working properly are the following (which due to the points mentioned above are becoming quite annoying):
  1. Only the "top" (we might not care about order) decorator is a managed bean and doesn't rely on CDI to create the delegate (which, although not shown in the example, means it needs to know not only about all implementations, but about all their the dependencies as well):

```
  class CachingDataLoader implements DataLoader {

    DataLoader delegate = new ValidatingDataLoader(new DefaultDataLoader());

    public Data load() {
      return cache(delegate.load())
    }
  }
```

  2. Define different qualifiers for each class so that the injection chain can be resolved properly. This gets complex quickly, still requires some coupling due to knowledge of the qualifiers and might require repeating qualifiers on decorators and interfere with the actual qualifiers the classes should have.

Could decorators be supported? Am I missing any workarounds? Thanks.

**Comment by maxandersen** [comment]
Awesome :)

**Comment by xtaixe** [comment]
Great! Thanks @mkouba ! Hopefully there's a 1.14 soon and we don't have to wait for 2.0...
