### ISSUE TITLE
Make it possible to filter which metrics are sent from kafka

### ISSUE THREAD

**Issue by ferencbeutel4711** [quarkusio/quarkus#15493]
**Description**
Hi, currently it seems to be impossible to define which of the hundreds of kafka consumer/producer-metrics are sent out if kafka metric support is enabled. Since these metrics can be quite costly if sent to the cloud, it would be great to have some form of filtering in place so that the service only publishes the metrics I am interested in.

**Implementation ideas**
Ideally, this would be configuration only, so some form of application.yml integration.

**Comment by ebullient** [comment]
This is already possible with Micrometer, though at the moment only programmatically.

You can define a MeterFilter that looks for kafka metrics based on the metric name and some combination of tags to allow/deny those metrics.

There are some examples shown in the [Quarkus Micrometer extension guide](https://quarkus.io/guides/micrometer#using-meterfilter-to-configure-metrics)), but allow/deny filters are better shown in the Micrometer docs: https://micrometer.io/docs/concepts#_meter_filters

**Comment by cescoffier** [comment]
@ebullient what should we do about this one? Your answer looks good to me.

**Comment by ebullient** [comment]
I think the question is whether or not this is common enough to warrant generation from some config attribute.. though that comes with some complexity.

**Comment by cescoffier** [comment]
Yes, let's see if there are other demands. The work around you have made it not a blocker at all.

Alternatively we can had an attribute on the kafka connector to disable the metrics per channel, but I'm not sure it addresses the problem, as it won't let you filter but will drop clients completely. I would even consider that as a bad pattern.

**Comment by ferencbeutel4711** [comment]
Hi guys, sorry for the late response. Just to let you know, the provided workaround is definitely good enough for us and the way to set it via configuration was only a suggestion, not requirement we have. So considering that, I think the issue could be closed for us and if a lot of demand comes up for this feature, it could be reopened.

**Comment by cescoffier** [comment]
Thanks @ferencbeutel4711 ! 

Closing for now.
