### ISSUE TITLE
Quarkus + Resteasy + Google Cloud Functions: no query parameters bypass

### ISSUE THREAD

**Issue by HardNorth** [quarkusio/quarkus#15501]
**Describe the bug**
I'm trying to implement a simple service using Google Cloud Functions and Quarkus. But if I'm trying to use `@QueryParam` annotation I'm getting nulls in any param. E.G.:
```java
	@GET
	@Path("echo1")
	@Produces(MediaType.TEXT_PLAIN)
	public Response echo1(@QueryParam("test") String test) {
		return Response.status(Response.Status.OK)
				.encoding("UTF-8")
				.entity("test: " + test).build();
	}
```

**Expected behavior**
```none
test: test string
```

**Actual behavior**
```none
test: null
```

**To Reproduce**
I've implemented a very small test service to reproduce the issue:
https://github.com/HardNorth/quarkus-google-functions-test/blob/main/src/main/java/net/hardnorth/test/quarkus/QuarkusTestService.java

You need to deploy it into Google Cloud. Because it works locally.

**Configuration**
Doesn't matter at all

**Additional context**
Based on what I see from code there is a missing part in `QuarkusHttpFunction.java`. E.G. for Amazon lambdas you have a whole loop which appends query parameters to `path` variable:
https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java#L154

But there is no such logic for Google Functions:
https://github.com/quarkusio/quarkus/blob/master/extensions/google-cloud-functions-http/runtime/src/main/java/io/quarkus/gcp/functions/http/QuarkusHttpFunction.java#L94

**Comment by loicmathieu** [comment]
@HardNorth I confirm query params didn't works.

Thanks for pointing me to the missing piece of code ;) I'll try to provide a fix soon.

**Comment by loicmathieu** [comment]
@HardNorth in fact, the piece of code you pointed to is not for amazon-lambda-http so not related to query string support on with resteasy. Anyway I'll have a look.

**Comment by HardNorth** [comment]
@loicmathieu Thanks for watching into this! Please excuse me but let me hightlight it again: the bug within Goggle Cloud Functions handling code, Amazon code I pointed serves for example and does very similar thing, of course it's not one-to-one. And I actually made a workaround in my project which fixes the issue:
https://github.com/HardNorth/service-merge-validate/blob/develop/src/main/java/net/hardnorth/quarkus/gcp/functions/http/QuarkusHttpFunction.java#L89

The class is actually copy-paste from your code with two differences: fixes for this and issue #15510

Sorry if I wasn't clear first.

**Comment by loicmathieu** [comment]
Yes, maybe the issue also exist for amazon-lanbda-http ...

If you already have a fix for it, you can open a pull request if you want to contribute it.
Or I can do it, just tell me ;)

**Comment by HardNorth** [comment]
@loicmathieu Sure I will open the request.

**Comment by HardNorth** [comment]
ETA: tomorrow, since I want to cover it with tests and it's late evening in my timezone.

**Comment by loicmathieu** [comment]
@HardNorth no worry, take your time, if you need help you can also reach to me on Zulip, you can ask question about how to build Quarkus on the dev channel: https://quarkusio.zulipchat.com/#reload:859994484326
Or send me a PM if you have a specific question.

**Comment by HardNorth** [comment]
@loicmathieu @gsmet Posted a pull-request: https://github.com/quarkusio/quarkus/pull/15620
