### ISSUE TITLE
Cannot import io.quarkus.mongodb.reactive.ReactiveMongoClient in 1.12.1.Final

### ISSUE THREAD

**Issue by royi-frontegg** [quarkusio/quarkus#15521]
Cannot resolve io.quarkus.mongodb.reactive.ReactiveMongoClient in 1.12.1.Final.
Everything is running ok in 1.12.0.Final

**Comment by gsmet** [comment]
Could you put together a reproducer (a simple Maven project reproducing the issue)? Thanks.

**Comment by cescoffier** [comment]
I just tried.

I have the following dependency:
```xml
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
</dependency>
```

And the following injection works:

```
@Inject
ReactiveMongoClient client;
```

The import statement is: `import io.quarkus.mongodb.reactive.ReactiveMongoClient;`

So, yes, I would need a reproducer.

**Comment by royi-frontegg** [comment]
Sorry. 
I had a small hiccup downloading the maven deps
