### ISSUE TITLE
quarkus.container-image.push=false doesn't work

### ISSUE THREAD

**Issue by tarric1** [quarkusio/quarkus#15523]
I'm trying to build an image by means of Jib, and I don't want it is pushed.
To do that, I'm using the following pom.xml:

`<?xml version="1.0"?>`
`<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`
`  <modelVersion>4.0.0</modelVersion>`
`  <groupId>io.tarric1.quarkus</groupId>`
`  <artifactId>confignlog</artifactId>`
`  <version>1.0.0</version>`
`  <properties>`
`    <java.version>11</java.version>`
`    <maven.compiler.source>${java.version}</maven.compiler.source>`
`    <maven.compiler.target>${java.version}</maven.compiler.target>`
`    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`
`    <quarkus.container-image.build>true</quarkus.container-image.build>`
`    <quarkus.container-image.builder>jib</quarkus.container-image.builder>`
`    <quarkus.container-image.group>${project.groupId}</quarkus.container-image.group>`
`    <quarkus.container-image.name>${project.artifactId}</quarkus.container-image.name>`
**`    <quarkus.container-image.push>false</quarkus.container-image.push>`**
`    <quarkus.version>1.12.1.Final</quarkus.version>`
`  </properties>`
`  <dependencyManagement>`
`    <dependencies>`
`      <dependency>`
`        <groupId>io.quarkus</groupId>`
`        <artifactId>quarkus-bom</artifactId>`
`        <version>${quarkus.version}</version>`
`        <type>pom</type>`
`        <scope>import</scope>`
`      </dependency>`
`    </dependencies>`
`  </dependencyManagement>`
`  <dependencies>`
`    <dependency>`
`      <groupId>io.quarkus</groupId>`
`      <artifactId>quarkus-resteasy-jsonb</artifactId>`
`    </dependency>`
`    <dependency>`
`      <groupId>io.quarkus</groupId>`
`      <artifactId>quarkus-container-image-jib</artifactId>`
`    </dependency>`
`  </dependencies>`
`  <build>`
`    <plugins>`
`      <plugin>`
`        <groupId>io.quarkus</groupId>`
`        <artifactId>quarkus-maven-plugin</artifactId>`
`        <version>${quarkus.version}</version>`
`        <extensions>true</extensions>`
`        <executions>`
`          <execution>`
`            <goals>`
`              <goal>build</goal>`
`            </goals>`
`          </execution>`
`        </executions>`
`      </plugin>`
`    </plugins>`
`  </build>`
`</project>`

As you can see, I have putted the property `quarkus.container-image.push=false`, but the maven plugin tries anyway to execute `docker load`.

Here:

- [https://github.com/tarric1/confignlog](https://github.com/tarric1/confignlog)

you can find the source code to reproduce.

**Comment by geoand** [comment]
This works as expected.

When `quarkus.container-image.push=false`, Quarkus builds the container image inside the local docker daemon.
When `quarkus.container-image.push=true`, the Quarkus (via Jib) pushes the built container image directly to the specified registry without interacting with the local docker daemon (which doesn't need to even exist)
