### ISSUE TITLE
Quarkus 1.12.1.Final uses smallrye.reactive.mutiny 0.13.0 not 0.14.0

### ISSUE THREAD

**Issue by mbennertz** [quarkusio/quarkus#15526]
**Describe the bug**
Quarkus 1.12.1.Final using smallrye.reactive.mutiny 0.13.0

**Expected behavior**
Quarkus 1.12.1.Final has dependency smallrye.reactive.mutiny 0.14.0

**Actual behavior**
Quarkus 1.12.1.Final  resolves to  mutiny 0.13.0 

**To Reproduce**

1. Clone quarkus-quickstarts/getting-started-reactive.
2. Look at the maven effective pom
3. Quarkus 1.12.1.Final has dependency smallrye.reactive.mutiny-0.13.0

**Comment by cescoffier** [comment]
1.12.x uses 0.13.0 as the bump to 0.14.0 happened after the "cut". 1.13 will use 0.14.0.
