### ISSUE TITLE
HttpRootPathBuildItem has changed his `path` format several times. 

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15535]
**Describe the bug**

On version 1.11.1.Final or  1.12.0.Final `HttpRootPathBuildItem` returns a path like  `http://test-http-advanced-pablo-http-advanced.apps.ocp46.dynamic.quarkus/api` but on version 1.11.5.Final or 1.12.1.Final  `HttpRootPathBuildItem` returns a path like  `http://test-http-advanced-pablo-http-advanced.apps.ocp46.dynamic.quarkus/api/` 

**note** that on version 1.11.5.Final the paths end with "/".

I am not sure if these inconsistencies are related to this commit: https://github.com/quarkusio/quarkus/commit/e0f8ec94ef9b6882a60a4f7299c9db9b17893fe2

I think that should not end with "/" at the end. 

Could you clarify the expected behavior?

**Comment by gsmet** [comment]
@ebullient @kenfinnigan

FWIW this led to PR like this: https://github.com/quarkusio/quarkus/pull/15529

**Comment by ebullient** [comment]
Yes. We know. That's one of the reasons we had to fix all the places we knew would need a fix. 
@stuartwdouglas mentioned the cosmetic fix needed for the dev ui.

Have you pushed publish on the blog post yet?
@pjgg were the Javadoc comments on the build item clear? (they were updated in 1.12.1.Final & 1.11.5.Final)

**Comment by ebullient** [comment]
Also, I think I need to go back though #15529 -- while it did resolve the cosmetic issue re: having two slashes visible, I'm not sure it did it in the correct way that would ensure paths are resolved correctly as config allows things to be moved around (w/o being misinterpreted).
