### ISSUE TITLE
Quarkus 1.12.1.Final swagger-ui endpoint under /q is broken: stale content in tmp

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#15537]
I have issue with swagger-ui endpoint

````
2021-03-08 07:46:18,870 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, hibernate-validator, kubernetes, kubernetes-client, logging-manager, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]

mvn clean quarkus:dev
````

with swagger-ui I obtain a white page with those errors
````
GET http://localhost:8383/q/swagger-ui/style.css net::ERR_ABORTED 404 (Not Found)
(index):16 GET http://localhost:8383/q/swagger-ui/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
(index):17 GET http://localhost:8383/q/swagger-ui/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
(index):6 GET http://localhost:8383/q/swagger-ui/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
(index):7 GET http://localhost:8383/q/swagger-ui/theme-feeling-blue.css net::ERR_ABORTED 404 (Not Found)
(index):17 GET http://localhost:8383/q/swagger-ui/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
(index):21 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload ((index):21)
window.onload @ (index):21
load (async)
(anonymous) @ (index):20
favicon.ico:1 GET http://localhost:8383/q/swagger-ui/favicon.ico 404 (Not Found)
````

![image](https://user-images.githubusercontent.com/191879/110325633-9214b100-7fe5-11eb-91d0-0dddee5216fb.png)

with http://localhost:8383/q/dev/

in the browser console we have this : 
````
http://localhost:8383/q//dev/resources/css/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)
````
![image](https://user-images.githubusercontent.com/191879/110325563-7c06f080-7fe5-11eb-9ef1-8062813684b0.png)

**Comment by phillip-kruger** [comment]
Did you make sure that this is not browser cache ? Also try and delete the /tmp/quarkus folder and rebuild

**Comment by phillip-kruger** [comment]
Can you share a reproducer ?

**Comment by survivant** [comment]
I can reproduce it anything my with application.  Let me check if I can clone a quickstart guide and reproduce it with them

**Comment by survivant** [comment]
I'll need you help for that one.  https://github.com/survivant/quarkus-swagger-demo

you launch it by  :  mvn clean quarkus:dev   and http://localhost:8383/q/swagger-ui/     I try with 2 differents browsers and got the same white page.

BUT  I found something that doesn't make sense (shouldn't)

if I change this in the pom.xml : artifact name to anything else.. it works

````
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.comact.iep.api</groupId>
    <artifactId>kubernetes-api</artifactId>
    <version>1.0.0-SNAPSHOT</version>
````

for 
````
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.comact.iep.api</groupId>
    <artifactId>kubernetes-api2</artifactId>
    <version>1.0.0-SNAPSHOT</version>
````

I don't see why it doesn't work.. unless there is something in the code that clashed with the artifact name ending by -api ?

**Comment by phillip-kruger** [comment]
Did you try and delete `/tmp/quarkus` (it use the artifact name, so that might make sense) In dev mode we store the static content in the temp folder. Also trying this on my pc....

**Comment by phillip-kruger** [comment]
Yes, working on my PC, so I am sure it's the tmp folder.
![image](https://user-images.githubusercontent.com/6836179/110330636-aaf18680-8026-11eb-937b-4e8941124c9e.png)

**Comment by survivant** [comment]
it works.   I though it was generated in ./target/tmp/quarkus

there is a way to clean the folder /tmp/quarkus/artifactname    when quarkus starts ?

**Comment by ebullient** [comment]
Is the updated topic correct to what we understand the problem to be now?

**Comment by survivant** [comment]
@ebullient yes, now that we identified the root cause of the problem.

**Comment by phillip-kruger** [comment]
It is supposed to clean on a new full build, i.e. not just quarkus:Dev, but clean install

**Comment by gsmet** [comment]
@stuartwdouglas is there a way to differentiate the first start in dev mode compared to the reloads after that? We should clean the temp directory when we first start dev mode.

**Comment by stuartwdouglas** [comment]
io.quarkus.deployment.builditem.LiveReloadBuildItem#isLiveReload will tell you if it is first start or a reload.

**Comment by phillip-kruger** [comment]
Ok I can make an enhancement to clear on first dev mode start as well.
