### ISSUE TITLE
quarkus-spring-data-rest Validation constraint message is empty. 

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15549]
**Describe the bug**
Extension: `quarkus-spring-data-rest`
Quarkus Version error: On the current master branch

On Quarkus 1.11.5.Final and 1.12.0.Final when you set up an entity with contains validation annotation as:

```
@Entity
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Length(min = 2, max = 50, message = "length must be between {min} and {max}")
    @NotBlank(message = "Name may not be blank")
    private String name;
```

For an invalid input, you got an error message like `length must be between 2 and 50` But now the message is empty.

[Reproducer](https://github.com/quarkus-qe/beefy-scenarios/blob/master/602-spring-data-rest/src/test/java/org/acme/spring/data/rest/BookRepositoryTest.java#L114)

**Comment by geoand** [comment]
cc @gytis

**Comment by famod** [comment]
Isn't this more or less the same as #15492?

**Comment by geoand** [comment]
I certainly looks like it, but I'll let @gytis decide

**Comment by gytis** [comment]
Yes, this is a duplicate issue. I've only added a basic mapping to start with. I've discussed this with @Sgitario offline last week and will look into it.
