### ISSUE TITLE
Basic Authentication is not working on GraphQL Resources

### ISSUE THREAD

**Issue by fabienmifsud** [quarkusio/quarkus#15544]
**Describe the bug**
When we activate Basic Auth based on file properties on a graphQL resources, nothing is taken into account and the resource still be accessible for anyone.

**Expected behavior**
The resource is only available for authenticated user with the correct role.

**Actual behavior**
The resource is available for any anonymous user.

**To Reproduce**

https://github.com/fabienmifsud/quarkus-crud

1. mvn quarkus:dev
2. Go to http://localhost:8080/q/graphql-ui/
3. Execute the query : 
```
query readClients {
  clients {
    id
    name
    email
    dateOfBirth
  }
}
```
4. The app sends back an answer whitout asking for user/password or throwing a forbidden resource error

**Comment by phillip-kruger** [comment]
Thanks @fabienmifsud - I'll have a look a.s.a.p

**Comment by fabienmifsud** [comment]
@phillip-kruger, I did test again this morning and this is working now. I guess this is more related to a build or hot reload issue. I close the issue.
