### ISSUE TITLE
Missing description for generated health OpenAPI responses

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#15551]
**Describe the bug**
According to the validator https://apitools.dev/swagger-parser/online/ (and also that in the Azure API Management) the OpenAPI definition generated by the Quarkus Health extension are invalid. The API responses don't have any description.

**Expected behavior**
The individual API responses should each have their description. Like in this extract:

```yaml
    get:
      tags:
      - MicroProfile Health
      summary: An aggregated view of the Liveness and Readiness of this application
      description: Check the health of the application
      operationId: microprofile_health_root
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        "500":
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
```

**Actual behavior**
Here is an extract of what gets generated:
```yaml
    get:
      tags:
      - MicroProfile Health
      summary: An aggregated view of the Liveness and Readiness of this application
      description: Check the health of the application
      operationId: microprofile_health_root
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
```

**To Reproduce**
Create a project including the OpenAPI and Health extensions.

**Configuration**
```properties
quarkus.health.openapi.included=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
To be honest I have not yet checked the specs myself, but since two tools reported errors I was assuming that they are correct.

**Comment by phillip-kruger** [comment]
Thanks. I'll fix this a.s.a.p

**Comment by knutwannheden** [comment]
The samples in *Expected behavior* and *Actual behavior* were reversed. I have fixed that now in the issue description.
