### ISSUE TITLE
Unable to limit Java usage for AWS Lambda using -Xmx32m

### ISSUE THREAD

**Issue by tpenakov** [quarkusio/quarkus#15562]
I was trying to limit a memory used by Quarkus AWS Lambda in the same way as used for Quarkus Web Applicaiton :
```
-Xmx32m
```
According to [this](https://quarkus.io/guides/amazon-lambda) guide, I've tried to create a `src/main/zip.native/bootstrap` file with the content below, but seems it is unaffected from the `Xmx` setting:
```
#!/usr/bin/env bash

./runner -Xmx32m
```
However there is no difference in Lambda memory usage reported by AWS with `-Xmx32m`, without it and with `-Xmx64m` .

Could someone help me how to limit the memory usage?

**Comment by patriot1burke** [comment]
Modify the manage.sh file generated.  You'll see that create-function invoke hardcodes the memory size to 256

**Comment by tpenakov** [comment]
It is the memory size of lambda? If I am right It does nothing to do with capping the memory of the application. If this option is not present there is a chance GC never to get called and the application to consume the entire host memory
