### ISSUE TITLE
Cleanup of vertx-cache temporary directories

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#15566]
Introduce enhancement to clean vertx-cache temporary directories

Highlighted during review of https://github.com/quarkusio/quarkus/pull/15541#pullrequestreview-606753837

The previous approach was not deleting the directory either, but it is better to do the cleanup if we have created the directory.

We won't clean if it's a directory set by the user (because it would reuse it during the next execution, and so would allow avoiding copying files over).

**Comment by cescoffier** [comment]
I did it as part of #15541.
