### ISSUE TITLE
S2I build on OpenShift with Quarkus 1.12.0.Final breaks build with multiple datasources

### ISSUE THREAD

**Issue by dominik42** [quarkusio/quarkus#15563]
**Describe the bug**
The Quarkus build process failed if multiple datasources are configured for a project and one of the datasource is for a database with no built-in extension.   
For such a datasource, you have to specify `jdbc.url`and `jdbc.driver`. But there was a [commit](https://github.com/quarkusio/quarkus/commit/690dd35895938ca11781461639e8d3eb71a51f1a) in [AgroalProcessor](https://github.com/quarkusio/quarkus/blob/master/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java) line 79 which throws a exception and fails the build if driver OR url are present ?????

**Expected behavior**
The build with `mvn clean package` is successful on the OpenShift S2I build.

**Actual behavior**
The builds failed with the following error:

```
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.12.0.Final:build (default) on project XYZ: 
Failed to build quarkus application: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception:   
io.quarkus.runtime.configuration.ConfigurationException:   
quarkus.datasource.url and quarkus.datasource.driver have been deprecated in Quarkus 1.3 and removed in 1.9.   
Please use the new datasource configuration as explained in https://quarkus.io/guides/datasource.
```

**To Reproduce**
Application with 2 different datasources, the default one with mssql, the other named datasource with oracle:

```
quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=msdb
quarkus.datasource.password=password
quarkus.datasource.username=user

quarkus.datasource.secondDatasource.db-kind=other
quarkus.datasource.secondDatasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.secondDatasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/xe
quarkus.datasource.secondDatasource.password=password
quarkus.datasource.secondDatasource.username=user
```
The Quarkus guide for datasources states, that for datasource with no built-in extension, you have to specify the driver. The second datasource "secondDatasource" is such a datasource, there is no extension for Oracle. Therefor this second datasource needs both parameter, `jdbc.url`and `jdbc.driver`. 

Start the build with 
```
mvn clean -s configuration/settings.xml package -DskipTests -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true -e -B --show-version
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: OpenShift Kubernetes Versiuon v1.16.2
 - Output of `java -version`: 11.0.8
 - Quarkus version or git rev: 1.12.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by geoand** [comment]
cc @gsmet

**Comment by dominik42** [comment]
[SOLVED] The error was an erroneous environment variable for the build config of the application in the cluster.
There was a ENV VARIABLE named QUARKUS_DATASOURCE_URL but have to be QUARKUS_DATASOURCE_JDBC_URL.
Sorry for the potential confusion and effort....
