### ISSUE TITLE
CI: Introduce nightly JDK EA/RC job (starting with JDK 16 RC)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#15575]
**Description**
There is no CI job/workflow that is testing the next upcoming JDK, e.g. JDK 16 as of 09.03.2021.

See discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.20tested.20on.20Java.2016

**Implementation ideas**
- at least analogous to job "JVM Tests - JDK 11"
- more jobs to be decided:
  - Windows?
  - Maven?
  - Devtools?
  - Gradle?
- trigger: nightly and on-demand
- include in status.quarkus.io

**Comment by gsmet** [comment]
Let's run a simple full build on Linux. We don't care if it takes time so I would keep it simple.

**Comment by famod** [comment]
Ok, KISS it is. Do we care about that job possibly creating the monthly Maven repo cache instead of the JDK 11 job from the regular CI workflow?

**Comment by gsmet** [comment]
I don't think it makes sense to rely on a non final JDK to do anything :)

**Comment by famod** [comment]
FWIW, I'm testing a new workflow file in my fork: https://github.com/famod/quarkus/actions/workflows/jdk-early-access-build.yml
4 hours timeout were not sufficient, testing with 6 hours now.

AFAICS, we'll have to use the default `setup-java` action to get a EA build easily, which is a Zulu one (not AdoptOpenJDK) but better than nothing. 😉

**Comment by famod** [comment]
#15711 adds the respective job. After this is merged, someone else will have to do `status.quarkus.io` part.
