### ISSUE TITLE
Support in DevServices for additional JDBC URL parameters

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#15579]
**Description**
The DevServices feature currently doesn't yet support setting additional URL parameters for the created database. Some database (like Oracle and MySQL for example) allow specifying various parameters (e.g. time zone) as JDBC URL parameters. Currently the JDBC URL will be constructed by Testcontainers, so to specify URL parameters the Dev Service would have to call `org.testcontainers.containers.JdbcDatabaseContainer#withUrlParam()`.

Currently `DevServicesDatasourceProvider#startDatabase()` declares a parameter `Map<String, String> additionalProperties`. I am however not quite sure about the intended purpose of this parameter. While Testcontainers currently doesn't support specifying parameters (which would be passed to `java.sql.Driver#connect(String, Properties)`), this isn't really necessary either, because Dev Services doesn't delegate the Connection creation to Testcontainers, only the JDBC URL creation.

**Implementation ideas**
Possibly the `Map<String, String> additionalProperties` parameter could be (renamed and) repurposed. Or if I have misunderstood its purpose, possibly a new parameter could be introduced which would allow specifying additional JDBC URL parameters.

**Comment by famod** [comment]
/cc @stuartwdouglas 

@gsmet maybe "DevServices" should trigger some labels, e.g. `area/devmode` and `area/testing`?

**Comment by stuartwdouglas** [comment]
There needs to be a dedicated property for this, if devservices is in use then there is no URL to parse (as the presence of a URL will stop devservices starting)

**Comment by knutwannheden** [comment]
> There needs to be a dedicated property for this, if devservices is in use then there is no URL to parse (as the presence of a URL will stop devservices starting)

I see. I hadn't quite understood yet that this is how devservices is activated. Thanks for the clarification.

**Comment by knutwannheden** [comment]
As commented on the PR, I believe the implementation for MSSQL needs some minor adjustment.
