### ISSUE TITLE
Named Redis client injection not working when used in separate JAR

### ISSUE THREAD

**Issue by abutic** [quarkusio/quarkus#15581]
**Describe the bug**
We have an application scoped bean, defined in our common project and being used by other services, that utilizes `RedisClient`:
```
@ApplicationScoped
public class Service {

    @Inject
    @RedisClientName("second")
    RedisClient redisClient;
    ...
}
```
This common project is packaged as JAR and then used as a Maven dependency from other services.

We keep getting this error when starting those other services:
```
javax.enterprise.inject.spi.DeploymentException:
  javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.redis.client.RedisClient and qualifiers [@RedisClientName(value = "second")]
```

We've defined an alternate Redis connection like this:
```
quarkus.redis.second.hosts=redis://localhost:6379
```
and made sure it's being used as expected by a Redis client defined in our service (not the common JAR!) like this:
```
    @Inject
    @RedisClientName("second")
    RedisClient redisClient;
```

Should it be possible to have a bean class contained in a dependency JAR and make it use Redis connection defined in the project that uses that JAR?

**Expected behavior**
Bean defined in a dependency JAR, which uses a Redis client annotated by `@RedisClientName`, properly using Redis connection defined in containing service.

**Comment by manovotn** [comment]
> This common project is packaged as JAR

Does the JAR contain `beans.xml`? Empty one should do the trick.

**Comment by abutic** [comment]
> 
> 
> > This common project is packaged as JAR
> 
> Does the JAR contain `beans.xml`? Empty one should do the trick.

Unfortunately, yes, the JAR contains an empty `META-INF\beans.xml` file.

**Comment by manovotn** [comment]
Hmm, not sure why you cannot see it then.
You could try to make the bean `@Unremovable` (or just check in dev mode that it wasn't removed) to make double sure something isn't going wrong there.
Besides that, a reproducer project would be nice so that we can check what's going on close up.

**Comment by mkouba** [comment]
It seems that the redis client extension only considers classes from the application root (i.e. `src/main/java`) when collecting the client names and registering the relevant synthetic beans: https://github.com/quarkusio/quarkus/blob/master/extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java#L89-L93

CC @machi1990

**Comment by machi1990** [comment]
> It seems that the redis client extension only considers classes from the application root (i.e. `src/main/java`) when collecting the client names and registering the relevant synthetic beans: https://github.com/quarkusio/quarkus/blob/master/extensions/redis-client/deployment/src/main/java/io/quarkus/redis/client/deployment/RedisClientProcessor.java#L89-L93
> 
> CC @machi1990

Thanks for spotting this @mkouba . What archive should have been used instead? I think the same problem can occur for the {mongo-extension](https://github.com/quarkusio/quarkus/blob/33364c8700988293515dfb34d53f238f196ead15/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java#L119)
/cc @glefloch

**Comment by manovotn** [comment]
I'd try with [BeanArchiveIndexBuildItem](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/BeanArchiveIndexBuildItem.java).
