### ISSUE TITLE
Kubernetes Resource Generation requires "RestEasy" dependency

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#15587]
**Describe the bug**
Standalone microservices like Kafka Consumer, ActiveMQ consumers don't need to expose an HTTP listener. However, without HTTP dependency, the Quarkus doesn't generate any Kubernetes configuration files in target/Kubernetes. There is no warning of any sought in the log files, and it just won't create those files

**Expected behavior**
Support Kubernetes resource generation without the RESTEasy dependency

**Actual behavior**
Kubernetes resources are not generated without Quarkus REST easy dependency

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux X64
 - Output of `java -version`:  Java 11
 - GraalVM version (if different from Java): 20.0.0.2
 - Quarkus version or git rev: 1.12.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw

**Additional context**
(Add any other context about the problem here.)

**Comment by rquinio** [comment]
Similar issue: #9660

**Comment by geoand** [comment]
Good point! Let's close this as a duplicate
