### ISSUE TITLE
DB/Panache API around getting sessions is badly designed

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#15595]
In ORM with Panache we have:

- `PanacheEntityBase.getEntityManager()` which is wrongly an instance method, it should be static since it applies to entity classes, never instances.
- `PanacheEntityBase.flush()` is similarly wrongly an instance method because it flushes the entire DB, not just one entity. It's convenient, sure, but deceptive.
- Probably we're missing `Panache.flush()` as a shortcut for `Panache.getEntityManager().flush()` too, in case we have a single PersistenceUnit.

In HR with Panache we're missing:

- `PanacheEntityBase.getSession()` for an equivalent to `getEntityManager()`
- Probably we're missing `Panache.flush()` as a shortcut for `Panache.getSession().flush()` too, in case we have a single PersistenceUnit.

Do we have similar issues in Mongo/Panache @loicmathieu?

I'm not sure how to deal with the change from instance to static though, given that it's not binary compatible at all. Adding them with worse names doesn't sound very appealing.

**Comment by loicmathieu** [comment]
@FroMage for MongoDB we have `mongoCollection` that is a static method: https://github.com/quarkusio/quarkus/blob/master/extensions/panache/mongodb-panache/runtime/src/main/java/io/quarkus/mongodb/panache/PanacheMongoEntityBase.java#L928

And yes, these methods should have been static. I'm almost sure it was my mistake (at least for flush) :(

I think we already discuss this, it's not binary compatible but I think it's still feasible, it will only need a re-compilation and people will have a warning on there IDE right ?

**Comment by loicmathieu** [comment]
@FroMage we can take the opportunity for Quarkus 2 to move these methods to static and introduce a binary incompatibility (but recompiling will fix the issue).
I can take care of it if you want.

**Comment by FroMage** [comment]
That's actually a really good idea, be my guest!
