### ISSUE TITLE
Splunk extension

### ISSUE THREAD

**Issue by vietk** [quarkusio/quarkus#15605]
**Describe the extension**
Quarkus extension to be able to send logs to a Splunk HTTP Event Collector

This extension is based on the [official Splunk's HEC client](https://github.com/splunk/splunk-library-javalogging).

It registers its own [Java Logging Handler](https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/Handler.html) rather than using the [official one](https://github.com/splunk/splunk-library-javalogging/blob/1.8.0/src/main/java/com/splunk/logging/HttpEventCollectorLoggingHandler.java).

The reason for that is, it was not compatible with JBoss logger implementation used in Quarkus and, as such,
prevents the ability to record steps at build time.

**Extension name proposal :** quarkus-logging-splunk

**Additional context**

We are two developers from [Amadeus](https://github.com/AmadeusITGroup) :
- @vietk  (Kevin Viet)
- @rquinio1A (Romain Quinio)

We have developed a fully functional Quarkus extension that we would like to add to the quarkiverse and maintain.
We have the green light from our legal department to opensource our code.

Regards

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-splunk and developers added to the `@quarkiverse/quarkiverse-splunk` team with write permission to the repository.

Enjoy!

**Comment by vietk** [comment]
Thanks !
