### ISSUE TITLE
Java resource classes in src/test/java are not properly loaded

### ISSUE THREAD

**Issue by StFS** [quarkusio/quarkus#15618]
**Describe the bug**
It seems that resource classes that are written in Java and placed in the `src/test/java` directory are not properly loaded into Quarkus when running tests.

This was discovered when I was trying to figure out a problem with null values appearing in my `@PathParam` method parameters. I created a comprehensive test project here:
https://github.com/StFS/quarkus-test-resources

Check this project out and run `./gradlew test` to see how unit tests that try to reach resources that are defined in Java classes within the `test/src/java` directory encounter a 404 response from Quarkus.

**Expected behavior**
Unit tests that access resources defined by Java resource classes in `src/test/java` should get a response from those resources.

**Actual behavior**
Unit tests trying to access resources from Java classes within the `src/test/java` directory get a 404 response and the resource classes are never invoked.

**To Reproduce**

(sorry, this is a gradle project, but I don't believe the issue has anything to do with gradle)
https://github.com/StFS/quarkus-test-resources

1. Check out the project
2. Run `./gradlew test`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Darwin Stefans-MBP.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

 - Output of `java -version`:
```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing) 
``` 
 - GraalVM version (if different from Java): `N/A`

 - Quarkus version or git rev: 
`1.12.1.Final`

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15 (AdoptOpenJDK 15+36)
OS:           Mac OS X 10.16 x86_64
```

**Comment by StFS** [comment]
Alright, so I may have been a little off when I created this ticket. This issue (resource classes of src/test/java not being loaded)  is probably better placed in the Quarkus project.

However, the other issue discovered regarding `@PathParam` values being null may be something that concerns the RestEASY project.

I'm going to create a new issue on the Quarkus project and see what they have to say about this.

**Comment by glefloch** [comment]
Hi @StFS, I can reproduce the issue. I should be able to push a fix later today. Thanks for reporting this.

**Comment by StFS** [comment]
Woohoo! Thanks @glefloch .

I assume that is the issue with Java resource classes not being loaded from the test source directory (as that is what this issue is about).

That leaves the other issue that I have in the test project that I created which is the problem with `@PathParam` method parameters being null. I'm not sure whether I should report that on the Quarkus project or the RestEASY project. Can you help me out with that at all?

**Comment by glefloch** [comment]
I will tries this out as well. Actually, when running test, we look for resources in all main directories (`src/main/java`, `src/main/kotlin`) and in the directory of the test (so either `src/test/java` or `src/test/kotlin`). I updating the code to make sure we are looking in all available directories. 
Regarding the `@PathParam`, I will have a closer look to it.
