### ISSUE TITLE
Errors reported to sentry.io result in an <unlabelled event>

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#15623]
In our setup, we use sentry.io to report errors. This setup seems to be currently broken for our quarkus services though. Errors reported to sentry.io do not show any actual content but are marked as unlabelled events: 

![image](https://user-images.githubusercontent.com/1176370/110758259-9bec1d80-824c-11eb-9c1d-866583eb2eea.png)

**Expected behavior**
Errors in sentry should contain stacktraces, error messages etc. 

**Actual behavior**
All errors reported result in unlabelled events with actual no content. 

**Configuration**
gradle.properties:
```properties
# Add your application.properties here, if applicable.
#Gradle properties
#Fri Dec 18 09:44:23 CET 2020
quarkusPluginVersion=1.12.1.Final
quarkusPlatformArtifactId=quarkus-bom
quarkusPluginId=io.quarkus
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.12.1.Final
org.gradle.logging.level=INFO
```
dependencies from build.gradle 
```groovy 
dependencies {

    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'io.quarkus:quarkus-amazon-dynamodb'
    implementation 'software.amazon.awssdk:dynamodb-enhanced'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-jackson'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
    implementation 'de.spinscale.quarkus:quarkus-logging-ecs:0.0.2'
    implementation 'io.quarkus:quarkus-logging-sentry'
    implementation 'io.quarkus:quarkus-micrometer'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-cache'
    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-smallrye-jwt-build'
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.github.microutils:kotlin-logging:1.12.0'
}
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.3

**Comment by u6f6o** [comment]
I initially forgot to mention, that this issue occurs only with the native image.

**Comment by u6f6o** [comment]
I took some time and played with the reflection recorder. After adding the following entries in reflection-config.json, the reporting finally worked. Looks like the sentry-java library is not ready for native execution yet: 

```json
[
  {
    "name":"io.sentry.Breadcrumb",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.SentryBaseEvent",
    "allDeclaredFields":true
  },
  {
    "name":"io.sentry.SentryEvent",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.SentryValues",
    "allDeclaredFields":true
  },
  {
    "name":"io.sentry.protocol.DebugImage",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.DebugMeta",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Mechanism",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Message",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.Request",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SdkInfo",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SdkVersion",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryException",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryPackage",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryStackFrame",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryStackTrace",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.SentryThread",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },
  {
    "name":"io.sentry.protocol.User",
    "allDeclaredFields":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  }
]


```

**Comment by maciejwalkowiak** [comment]
FYI we are working on it on the Sentry SDK side: https://github.com/getsentry/sentry-java/pull/1329

**Comment by maxandersen** [comment]
@ia3andy any idea why we dont have this issue - just a feature of sentry we didnt use and thus wasnt noticed ?

**Comment by gsmet** [comment]
In the meantime, I think we should fix it for 1.13. I implemented the rules here while we wait for the upgrade to a Sentry version including them: https://github.com/quarkusio/quarkus/pull/15847 .

**Comment by gsmet** [comment]
@u6f6o if you have the time to check the PR fixes your issue, that would be very nice.

https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#checking-an-issue-is-fixed-in-main might be of help (except you need to target my PR branch instead of main).

**Comment by ia3andy** [comment]
> @ia3andy any idea why we dont have this issue - just a feature of sentry we didnt use and thus wasnt noticed ?

In code.quarkus.io we are not using native, so I guess this was never actually tested in native.

@maciejwalkowiak it would be nice if we add some integration tests to make sure events are sent correctly (native & non native), any idea how we could do it, mocking some Sentry components maybe?

**Comment by maciejwalkowiak** [comment]
You can mock the `transport` - which is the last piece before payloads are sent to Sentry. Maybe you can take a look at how I did the tests for Logback appender to verify events at the very end: https://github.com/getsentry/sentry-java/blob/main/sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt#L82 and https://github.com/getsentry/sentry-java/blob/main/sentry-test-support/src/main/kotlin/io/sentry/test/assertions.kt

**Comment by u6f6o** [comment]
@gsmet : I tested it as well, it worked for me. Thx for the fix!
