### ISSUE TITLE
OpenAPI  schema generation issue

### ISSUE THREAD

**Issue by bobbyphilip** [quarkusio/quarkus#15624]
The core class is   

`public class Greet {

    private String greetingText;

    public Greet() {

    }

    // @JsonbProperty(value = "greetingText")
    public String getGreetingText() {
        return greetingText;
    }

    @JsonbProperty(value = "externalServiceText")
    public void setGreetingText(String greetingText) {
        this.greetingText = greetingText;
    }

}`

My idea behind this is that I am using a 3rd party API to generate this object via the RestClient in Quarkus.
`externalServiceText` is the name of the json entry in the 3rd party.
In my system, I want the greetingText variable name to be used.  
The API response is correct and I see a json with greetingText in it.

However my generated openapi schema is

`components:
  schemas:
    Greet:
      type: object
      properties:
        externalServiceText:
          type: string`

It still has externalServiceText in it.  My understanding, is that the annotation on the setter is used during deserialization( from the rest client in my scenario). If I dont have an annotation on the getter, it should use the original fieldname.  However it doesnt work that way.  
If I add annotation` @JsonbProperty(value = "greetingText")` on my getter, the openapi schema generation is correct.

Do I really have to add an annotation on the getter, or is this a bug?

**To Reproduce**

https://github.com/bobbyphilip/smallrye-openapi-q1

**Comment by MikeEdgar** [comment]
Hi @bobbyphilip - I think in this case you will not be able to avoid an additional annotation. You could add `@Schema(name = "greetingText")` to the field. You can also use the Jsonb annotations, as you mentioned, but `@Schema` might be a more clear way to document it.
