### ISSUE TITLE
RunnerClassLoader.findResources does return null

### ISSUE THREAD

**Issue by moritz-bruder** [quarkusio/quarkus#15625]
https://github.com/quarkusio/quarkus/blob/ba778a7e37d9eaa635b3ec6c301903488bafb660/independent-projects/bootstrap/runner/src/main/java/io/quarkus/bootstrap/runner/RunnerClassLoader.java#L196

In the javadoc of the official API of `java/lang/ClassLoader.findResources` it is mentioned that this method will always return an `Enumeration`.  While OpenJDK does protect against `null` this is by no means a requirement.  In order to increase robustness and compatibility with other VMs, it is best to not return `null` or at least not in this specific inherited method.

**Comment by jaikiran** [comment]
I've opened https://github.com/quarkusio/quarkus/pull/15634 to include this change.
