### ISSUE TITLE
RestEasy Reactive client - jackson and jsonb modules

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#15621]
we need client specific jackson and jsonb modules for resteasy reactive (the current ones work but are ment for server and bring server as a depenendency).

**Comment by geoand** [comment]
We should probably leverage the `@ConstrainedTo` annotation for these

**Comment by geoand** [comment]
Jackson support was added in https://github.com/quarkusio/quarkus/pull/15777. I don't think we'll need JSON-B support unless someone really wants it
