### ISSUE TITLE
Docs: "Writing JSON REST Services" lacks a url parameters example. (@QueryParam)

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#15627]
This doc:
  https://quarkus.io/guides/rest-json
doesn't explain how to use URL parameters (@QueryParam), which is a very common requirement for many use cases. For example, to do paging.

**Comment by geoand** [comment]
With RESTEasy Reactive going to become the default REST layer, do you feel that https://quarkus.io/guides/resteasy-reactive provides enough information WRT issue?
