### ISSUE TITLE
Cache lookup

### ISSUE THREAD

**Issue by pokusak** [quarkusio/quarkus#15630]
**Description**
Current implementation of quarkus-cache extension supports cache lookup only as one operation together with inserting new value. Please enable simple lookup of value by key in cache. This should enable to lookup value by key in cache without inserting new value. If there is no such key, null can be returned or exception raised. 

**Implementation ideas**
Simple expose of function cache.get(Key) would be sufficient.

**Comment by gwenneg** [comment]
Hi @pokusak.

I think your enhancement request could fit into the programmatic API proposal from this [draft PR](https://github.com/quarkusio/quarkus/pull/8631). WDYT?

**Comment by geoand** [comment]
Closing as https://github.com/quarkusio/quarkus/pull/8631 should cover it
