### ISSUE TITLE
Use application name (if set) as Kafka group.id

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15632]
**Description**

At the moment, the group.id is:

* not set in prod mode - meaning that the user must set it
* is generated to be a unique id in dev mode - to facilitate the hot reload

It would be great to set the group.id to the application name if that name is set. 

**Implementation ideas**

If the application name is set, add the "kafka.group.id" property.

**Comment by cescoffier** [comment]
@michalszynkiewicz / @Ladicek fancy a simple one?

**Comment by Ladicek** [comment]
Sure, that makes sense, and looks like I should be able to handle it with my limited skills :-)
