### ISSUE TITLE
Upgrade mariadb-jdbc from 2.3 to 2.4

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1563]
Upgrade mariadb-jdbc from 1.3 to 1.4

Classes imported in https://github.com/quarkusio/quarkus/blob/master/extensions/jdbc/jdbc-mariadb/jdbc-mariadb-runtime/src/main/java/io/quarkus/jdbc/mariadb/runtime/graal/DefaultAuthenticationProvider_Substitutions.java#L5-L10 are not available in 1.4 anymore

Not sure if it it's good or bad sign for substratevm support.

**Comment by Sanne** [comment]
I take it you meant versions _2.3_ -> _2.4_ instead of _1.3_ -> _1.4_ ? Updated the title.
