### ISSUE TITLE
Fat JARs don't work well with service loader mechanism

### ISSUE THREAD

**Issue by rob-spoor** [quarkusio/quarkus#15643]
The service loader mechanism allows multiple JAR files to provide implementations of interfaces or classes. These are put in `META-INF/services/<fully qualified interface or class name>`.

When a fat JAR is created and it encounters these files, it will only use one of them. All others are discarded, with a warning. As a result, fat JARs are often broken if this occurs - part of the functionality is simply missing.

The obvious solution would be to not use uber JARs, but in case of an Azure Function this is enforced: https://github.com/quarkusio/quarkus/pull/14526. It's impossible to turn this off by changing the package type.

One possible solution is to take any file that matches the service loader pattern, and squash them together. Inside the uber JAR there would be (for each service) an uber service loader file that contains the contents of each separate file concatenated (keep in mind - files may not end in line breaks).

**Comment by rob-spoor** [comment]
Note that there are other similar files for which there will be issues if they are overwritten and not combined. `META-INF/spring.schemas` and `META-INF/blueprint.handlers` are just two I found in the logs.

To easily see this, include a dependency to https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-frontend-jaxws/3.4.2.

**Comment by geoand** [comment]
I'm going to close this as https://github.com/quarkusio/quarkus/pull/17077 introduced a solution based on extensions

**Comment by madocter** [comment]
> I'm going to close this as [#17077](https://github.com/quarkusio/quarkus/pull/17077) introduced a solution based on extensions

I think close the issue do not solve the issue ... what if is a multi module project you handle it with extensions ... so this is not real Spring alternative and just for little services not enterprise solution at all. I'm having same issues in 2026, shall I open an Issue ?

**Comment by geoand** [comment]
Please do, but it would be best to attach a sample project that exhibits the problematic behavior with the latest versions of Quarkus
