### ISSUE TITLE
RestClientITCase failure on master

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1565]
It looks like recent PRs (incl. e.g. #1327, #1562, #1561, #1559) all fail with:

```
[ERROR] Failures: 
[ERROR]   RestClientITCase>RestClientTestCase.testMicroprofileCdiClientHeaderPassing:88 1 expectation failed.
JSON path header-name doesn't match.
Expected: some-not-at-all-random-header-value
  Actual: null

[ERROR]   RestClientITCase>RestClientTestCase.testMicroprofileClientHeaderPassing:98 1 expectation failed.
JSON path header-name doesn't match.
Expected: some-not-at-all-random-header-value
  Actual: null
```

I can locally reproduce this with `../../mvnw -Dnative=true clean install` (NB: IT) in `integration-tests/main` on the current (0813fed5f320d55ac3b0eb02f2cac6a3a985793e) `master` branch ...

... anyone looking at fixing this so that we can rebase those PRs?

**Comment by dmlloyd** [comment]
I'm working on reproducing now.

**Comment by rsvoboda** [comment]
This what I see in my PR #1561, I tried to revert my changes but without luck.

Then I tried to run locally on the master and I see the errors too - `mvn clean install -DskipTests -Denforcer.skip=true -Dcheckstyle.skip=true -Dno-native &&  mvn -pl integration-tests/main clean integration-test -Dnative  -Dit.test=RestClientITCase -Dtest=NONE -DfailIfNoTests=false`

When looking into PR #1562 (Remove warning messages from devmode) I see RestClientITCase failure too.

New tests for RestClientITCase / RestClientTestCase were introduced in PR #1550 by @michalszynkiewicz

**Comment by gsmet** [comment]
I narrowed down the issue to this: https://github.com/quarkusio/quarkus/pull/1567/files .

**Comment by kenfinnigan** [comment]
PR merged

**Comment by michalszynkiewicz** [comment]
@gsmet, do you know what caused the problem? The test worked fine in the build for the PR that added it https://github.com/quarkusio/quarkus/runs/79930279
