### ISSUE TITLE
Build native image stuck

### ISSUE THREAD

**Issue by mutasemhidmi** [quarkusio/quarkus#15653]
I have a MacBook pro M1 and I am trying to build a native docker image for lambda that gets stuck. I am using this version 20.3.1-java11, and this is the command I am running 
./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.native-image-xmx=16g -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 
My docker desktop memory is 16G also
sometimes I get this error 
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled

**Comment by mutasemhidmi** [comment]
Is there a known issue with MacBook M1?

**Comment by Karm** [comment]
Hello @mutasemhidmi See the duplicate https://github.com/quarkusio/quarkus/issues/16225#issuecomment-987912107

@famod This issue should be closed.

**Comment by gastaldi** [comment]
Duplicate of #16225
