### ISSUE TITLE
JWK cache refresh interval with HTTP should behave the same as with HTTPS

### ISSUE THREAD

**Issue by leche43** [quarkusio/quarkus#15656]
**Description**
In the description of the JWK cache interval it says:
_smallrye.jwt.jwks.refresh-interval - ... It will be ignored unless the mp.jwt.verify.publickey.location points to the HTTPS URL based JWK set ..._ 
It would be desirable to be able to use the refresh interval also with HTTP and not only HTTPS. Especially because mp.jwt.verify.publickey, mp.jwt.verify.publickey.location and mp.jwt.verify.issuer do work with HTTP. But they are not usable right now with a key-rotation in place, since the refresh-interval is not supporting HTTP.

**Implementation ideas**
This was already picked up upstream by smallrye-jwt. See: https://github.com/smallrye/smallrye-jwt/issues/397 and https://github.com/smallrye/smallrye-jwt/pull/406 and therefore merged into smallrye-jwt:2.4.3 I see here: https://github.com/quarkusio/quarkus/releases/tag/1.12.0.CR1 smallrye-jwt:2.4.3 is already used, but the feature did not get picked up in Quarkus. I propose to reuse the functionality from smallrye:2.4.3.

**Comment by sberyozkin** [comment]
@leche43 Hi, do you mean the documentation has not been updated in Quarkus ? `quarkus-smallrye-jwt` does not itself do any JWK refresh work - so refreshing over HTTP should work, have you tried ?

**Comment by leche43** [comment]
> 
> 
> @leche43 Hi, do you mean the documentation has not been updated in Quarkus ? `quarkus-smallrye-jwt` does not itself do any JWK refresh work - so refreshing over HTTP should work, have you tried ?

Hi, yes I have tried, using Quarkus 1.12.0.Final against an HTTP based jwks endpoint. I have set the refresh-interval to 2 mins. The application worked till the key-rotation took place and then old keys were rejected. Did not seem that any refresh took place. Does it work for you? Additionally the documentation should be updated, yes.

**Comment by sberyozkin** [comment]
@leche43 I only have a unit test, it is possible the fix is not complete - can you please put a breakpoint [here](https://github.com/smallrye/smallrye-jwt/blob/2.4.3/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java#L111) and also [here](https://github.com/smallrye/smallrye-jwt/blob/2.4.3/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java#L210) ?
Can you confirm the rotation happens ? Note there is a an interval gate there - you can minimize it, one can't force constant refreshes...

**Comment by sberyozkin** [comment]
@leche43 The unit test is [here](url). This works exactly the same way as for HTTPS endpoints.

`refresh-interval` regulates how often the JWKs can be refreshed. If it was refreshed now then whatever has been fetched will be used to verify the tokens until this interval passes, to minimize a risk of DOS where the token kids are randomized and will never match the local JWKs.

I believe your test may not be precise - please debug or provide a reproducer - perhaps in the form of the unit test (similat to the one I've liked to) directly in smallrye-jwt...

**Comment by leche43** [comment]
@sberyozkin I retested a couple of times today with both available configuration options:
`smallrye.jwt.jwks.refresh-interval= 2
mp.jwt.verify.publickey.location: "http://my-server/JWKS"
mp.jwt.verify.issuer: "http://my-server"` 
and
`smallrye.jwt.jwks.refresh-interval= 2
smallrye.jwt.verify.key.location: "http://my-server/JWKS"
mp.jwt.verify.issuer: "http://my-server"`
and both seems to work. I can't reproduce it. I even activated the org.jose4j.jwk logs and observer such logs:
> Updated JWKS content from http://my-server/JWKS will be cached for 120 seconds until about Mon Mar 15 18:02:08 UTC 2021

So everything good, sorry for the false alarm :) I believe still the documentation for smallrye.jwt.jwks.refresh-interval and smallrye.jwt.jwks.forced-refresh-interval should be adapted.

**Comment by sberyozkin** [comment]
@leche43 great, thanks for the update. Yes the doc fix is coming with this PR: #15687 - I updated it to close this issue once it has been merged
