### ISSUE TITLE
Command mode dependency on resteasy when using rest-client

### ISSUE THREAD

**Issue by oztimpower** [quarkusio/quarkus#15665]
**Describe the bug**
Using `quarkus-picocli` and `quarkus-rest-client`, without `quarkus-resteasy` generates the following issue under `native-image`

```
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.JaxrsFormProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.JaxrsFormProvider
```

Prior incarnation was #2040 (fixed)

**Expected behavior**
`rest-client` has no dependency on the server-side `quarkus-resteasy`, particularly when used at the command line for `quarkus-picocli`

**Actual behavior**
`native-image` fails at runtime with the above CNFE

**To Reproduce**
Use `quarkus-picocli` and `quarkus-rest-client`. 

None of the Quikstarts have this combination, hence perhaps hasn't been tested before. The documentation for `quarkus-rest-client` includes `quarkus-resteasy` and omits the command line use case.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin  18.7.0 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 21.0
 - Quarkus version or git rev: 1.12.1-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle-6.8.3

/cc @gsmet

**Comment by dforsl** [comment]
We're also seeing this in our apps that are exposed as AWS Lambdas, ie no dependency on eg `quarkus-resteasy`. It's making our logs pretty unreadable in the places where a rest client used, as more or less full stacktraces are logged and that it's not once per client call - but there seem to be multiple classes not found and thus causing a somewhat overwhelming amount of warning-level logging.

Haven't yet had the time to dig when the issue started, but I don't remember having had this issue "that long" ago.

**Comment by geoand** [comment]
Is this still an issue or has or has it since been fixed?

**Comment by oztimpower** [comment]
Yes, verified this is now fixed. Thanks!

**Comment by geoand** [comment]
Thanks for checking!
