### ISSUE TITLE
@JsonFormat does not work with Graalvm + quarkus-resteasy-reactive-jackson

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#15669]
**Describe the bug**

I have a data class with a OffsetDateTime.

`data class MyData(
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssZ", timezone = "UTC")
    val myTime: OffsetDateTime)
`
When running under Java the serialization works, in native mode it doesn't.

**Expected behavior**

`  {
    "myTime": "2021-03-10T19:15:00+0000"
  }
`

**Actual behavior**

`  {
    "myTime": 1615403700.000000000
  }
`
**Environment (please complete the following information):**
 - GraalVM version: 21.0.0
 - Quarkus version or git rev: 1.12.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Gradle 6.6.1

**Comment by geoand** [comment]
I can't reproduce this.

I used the following model:

```java
public class Fruit {

    public String name;
    public String description;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssZ", timezone = "UTC")
    public OffsetDateTime myTime;

    public Fruit() {
    }

    public Fruit(String name, String description, OffsetDateTime myTime) {
        this.name = name;
        this.description = description;
        this.myTime = myTime;
    }
}
```

and it worked just fine.

Can you attach a project that reproduces the behavior you are seeing?

**Comment by holledauer** [comment]
Maybe this is an issue with Kotlin?

I can reproduce it with the following code:

`
import io.smallrye.mutiny.Uni
import javax.ws.rs.GET
import javax.ws.rs.Path
import java.time.OffsetDateTime

import com.fasterxml.jackson.annotation.JsonFormat

data class Fruit(
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssZ", timezone = "UTC")
    var myTime: OffsetDateTime? = null
)

@Path("/fruit")
class FruitController {

    @GET
    fun getFruit() = Uni.createFrom().item(Fruit(OffsetDateTime.now()))
}

`

**Comment by geoand** [comment]
Can you attach a project so I can test?

**Comment by holledauer** [comment]
[fruit.zip](https://github.com/quarkusio/quarkus/files/6130430/fruit.zip)

**Comment by geoand** [comment]
If you change to `@field: JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ssZ", timezone = "UTC")` it works

**Comment by holledauer** [comment]
Thanks! Would be great if this would be added to the documentation

**Comment by geoand** [comment]
Which part of the documentation?

**Comment by holledauer** [comment]
Maybe here? https://quarkus.io/guides/rest-json#jackson .

But I still think this is a bug. Isn't it possible to get it to work?
We are using the annotation in multiple quarkus and spring projects and it works everywhere without the the field specifier.

**Comment by geoand** [comment]
> Maybe here? https://quarkus.io/guides/rest-json#jackson .
> 
> But I still think this is a bug. Isn't it possible to get it to work?

There is nothing Quarkus can do about this. It has to do with the bytecode Kotlin produces and how Jackson handles the annotation lookups
