### ISSUE TITLE
Generated configurations do not show up in sites

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#15663]
**Describe the bug**

Seems like the generated configurations knobs do not appear in site, see links below.

- https://quarkus.io/guides/datasource#reactive-configuration
- https://quarkus.io/guides/building-native-image#configuration-reference
- https://quarkus.io/guides/all-config

**Expected behavior**

The generated knobs should appear

**Comment by gastaldi** [comment]
It was a deployment error during the release. It's fixed now. Thanks for reporting it @machi1990 !

**Comment by machi1990** [comment]
Thanks @gastaldi
