### ISSUE TITLE
Simplify debugging of extensions that can cause a Timeout

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#15668]
**Description**
Because of Timeouts, debugging several types of application is complicated. An example of this is a reactive application using RestEasy Reactive and Vert.x.

In this type of situations there are several types of timeout that can happen: http request time out, worker thread timout and I'm assuming there are more that I'm not aware of.
As far as I know, now a user has to find all the timeout related properties and set them to a higher value before they can start to see the exception they are looking for.

It would be nice to have an easier approach to do it

**Implementation ideas**

I don't know, maybe a  debug mode when starting quarkus,  similar to dev but with the timeouts disabled or a property that sets the timeout for all extensions to the max value allowed (not sure if it's really feasable).

**Comment by cescoffier** [comment]
What kind of timeouts are you referring to?

**Comment by DavideD** [comment]
Any kind really.
In vert.x it could be the  blocked thread check period, in other case the http request timeout.
The problem for me is that every time there is a timeout while debugging I need to first figure out which extensions is causing it, then I have to find the property for that specific extension and repeat until I've found all the properties referring to timeout for all the extensions.

Maybe it's just me not being super familiar with all the extensions, but it would be nice if this process were a bit easier.

**Comment by cescoffier** [comment]
If we can detect that the debugger is attached (and @stuartwdouglas has an idea for this), we can extend the vert.x blocker thread timeout.

**Comment by stuartwdouglas** [comment]
This will stop the blocked thread messages when a debugger is attached:  https://github.com/quarkusio/quarkus/pull/18668
