### ISSUE TITLE
Qute fails to resolve a method invoked from an injected bean

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#15679]
## Describe the bug
Qute does not resolve a method properly to be invoked from an injected bean

## Expected behavior
The method in the injected bean is invoked

## Actual behavior
The following error is thrown during the build
```
io.quarkus.qute.TemplateException: Incorrect expression found: {inject:prettyTime.format(stats.updated)}
	- property/method [format(stats.updated)] not found on class [org.ocpsoft.prettytime.PrettyTime] nor handled by an extension method
	- at StatusResource/issues.html:17
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:173)
```

## To Reproduce

1. Clone https://github.com/gastaldi/quarkus-status
2. Change to branch `pretty_time`
3. Run `mvn clean compile quarkus:dev`

## Configuration
```properties
# Add your application.properties here, if applicable.

```

## Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):
 - Output of `uname -a` or `ver`: Fedora 33
 - Output of `java -version`: JDK 11
 - GraalVM version (if different from Java): Not needed to reproduce
 - Quarkus version or git rev: 1.12.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Comment by mkouba** [comment]
I can confirm that it's a bug. The fix is simple but I discovered another related bug in validation :-(. So I'll prepare a PR to fix both problems.
