### ISSUE TITLE
Lambda Quarkus Graalvm Native Test - Error: fork/exec /var/task/bootstrap: exec format error","errorType":"Runtime.InvalidEntrypoint"

### ISSUE THREAD

**Issue by tehioant** [quarkusio/quarkus#15674]
**Describe the bug**
I have build my function.zip and deploy it with
`# ./mvnw clean install -Pnative -Dnative-image.docker-build=true -Dquarkus.native.native-image-xmx=8g`
`# sh target/manage.sh native create`

Then  

**Expected behavior**
I want to test the project with 
`# sh target/manage.sh native invoke`

**Actual behavior**
Unfortunately I get the error : 
`Error: fork/exec /var/task/bootstrap: exec format error","errorType":"Runtime.InvalidEntrypoint`

On AWS the answer for Runtime.InvalidEntrypoint is 
Issue: You receive a Runtime.ExitError error message, or an error message with "errorType": "Runtime.InvalidEntrypoint".
Verify that the ENTRYPOINT to your container image includes the absolute path as the location. Also verify that the image does not contain a symlink as the ENTRYPOINT.

**Screenshots**
`Invoking function
++ aws --profile saml --region us-east-1 lambda invoke response.txt --cli-binary-format raw-in-base64-out --function-name ANTE-QuarkusAmazonLambdaArchetypeNative --payload file://payload.json --log-type Tail --query LogResult --output text
++ base64 --decode
START RequestId: ba3762b6-efb4-4f19-b616-2e7c3f1622aa Version: $LATEST
END RequestId: ba3762b6-efb4-4f19-b616-2e7c3f1622aa
REPORT RequestId: ba3762b6-efb4-4f19-b616-2e7c3f1622aa	Duration: 16.44 ms	Billed Duration: 17 ms	Memory Size: 256 MB	Max Memory Used: 4 MB	
RequestId: ba3762b6-efb4-4f19-b616-2e7c3f1622aa Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint
{"errorMessage":"RequestId: ba3762b6-efb4-4f19-b616-2e7c3f1622aa Error: fork/exec /var/task/bootstrap: exec format error","errorType":"Runtime.InvalidEntrypoint"}% `

**Environment (please complete the following information):**
 - Quarkus version 1.12.1.Final
 - GraalVM version 21.0.0.2

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
