### ISSUE TITLE
quarkus-smallrye-fault-tolerance depends on libraries which are licensed with "GPL with classpath exception"

### ISSUE THREAD

**Issue by albert0815** [quarkusio/quarkus#15682]
**Description**
We are currently preparing the release of our application using Quarkus. Part of this is a license check. We have few findings which are marked as high risk license components. There are few dependencies which use the "GPL with classpath exception" within quarkus-smallrye-fault-tolerance which seems to be risky. I would kindly like to ask you evaluating whether it is possible to get rid of those dependencies.

In detail:

* Dependency `jakarta.el:jakarta.el-api`
I am hoping this might be something which can be solved by excluding some libraries from pom.xml of quarkus-smallrye-fault-tolerance. That component contains a dependency to `jakarta.enterprise:jakarta.enterprise.cdi-api` (see https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/runtime/pom.xml#L42) - not sure why since this is already a dependency of smallrye-fault-tolerance. Nevertheless in smallrye-fault-tolerance there is an exclusion of the jakarta-el lib (see https://github.com/smallrye/smallrye-fault-tolerance/blob/master/pom.xml#L90). That library is licensed under the GPL with CPE which is an issue for us. And it seems that lib is actually not required by `smallrye-fault-tolerance` since they are excluding it. So I want to ask whether it is possible to get rid of that dependency in `quarkus-smallrye-fault-tolerance`. 
* Dependency `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api`
In smallrye-fault-tolerance there is a dependency to jakarta.enterprise.concurrent-api in the version 4.3.2 which seems to be in use in Quarkus. In smallrye-fault-tolerance 5.0.0 this dependency is not present any more.

**Implementation ideas**
* Dependency `jakarta.el:jakarta.el-api`
Maybe the dependency `jakarta.enterprise.cdi-api` could be removed altogether from `quarkus-smallrye-fault-tolerance`? Or at least an exclusion could be added?
* Dependency `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api`
Update to smallrye-fault-tolerance 5.0.0

**Comment by Ladicek** [comment]
I think both can be excluded. I'm looking at the history and SmallRye Fault Tolerance depending on `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api` seems to have been a mistake, it has never been used (maybe in the ancient 2.x version, not sure). I just got rid of that dependency when I noticed it's not used anywhere, in an unrelated commit.

**Comment by Ladicek** [comment]
Now looking at it again, I can indeed remove the dependencies on `jakarta.enterprise:jakarta.enterprise.cdi-api` and `jakarta.annotation:jakarta.annotation-api` from the `quarkus-smallrye-fault-tolerance` module, but `el-api` will sneak in anyway. I found that the Hibernate Validator and Scheduler extensions use Jakarta EL, so there's probably no escape here.

I'll exclude the `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api` dependency, that is OK.

**Comment by albert0815** [comment]
Thanks very much for looking into this so quickly and applying few of the suggested changes.

For the hibernate-validator output of maven dependency tree looks like this:

```
[INFO] +- io.quarkus:quarkus-hibernate-validator:jar:1.12.2.Final:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  \- org.glassfish:jakarta.el:jar:3.0.3:compile

```
I mean, that is actually a different artifact. It is not `jakarta.el:jakarta.el-api` which is refered in `quarkus-smallrye-fault-tolerance` but it is a glassfish version - it may contain the same stuff with the same license, still it is a little weird to have the same classes in two different jars as part of the application. It feels a little inconsistent (from my experience this can lead to the kind of errors which are hard to find, e.g. if actually different versions are refered to). But I don't know in detail how you handle this in Quarkus. And this is not the main problem I am suffering from right now :).

Nevertheless I have the feeling that also quarkus-hibernate-validator might not be using that el-api. If I search for javax.el in the Quarkus Github repo there is no match. So maybe it is still possible to exclude that lib (also for hibernate-validator)?

**Comment by Ladicek** [comment]
Yea some of the `org.glassfish` artifacts duplicate the Jakarta APIs. Don't search for `javax.el`, search for `jakarta.el` -- you will find the dependencies.

Also, I just looked into the `jakarta.el:jakarta.el-api` and `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api` artifacts and I think the license situation is a little more complex than just "GPL 2.0 with CPE". Specifically:

- all files in `jakarta.el:jakarta.el-api:3.0.3` are licensed either under 1. Apache License 2.0, or 2. Eclipse Public License 2.0. The files that are licensed under EPL 2.0 can also be optionally distributed under GPL 2.0 with Classpath Exception;
- all files in `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api:1.1.2` are licensed under Eclipse Public License 2.0 and can also be optionally distributed under GPL 2.0 with Classpath Exception.

BTW, the same also applies to e.g. `jakarta.interceptor:jakarta.interceptor-api` (looking at version `1.2.5`) or `jakarta.annotation:jakarta.annotation-api` (looking at version `1.3.5`) -- they are both EPL 2.0 and optionally also GPL 2.0 with CPE. I'm 100% sure we wouldn't be able to exclude those :-) Could you please verify your statement that `jakarta.el:jakarta.el-api` and `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api` are licensed under GPL 2.0 with CPE? Thanks!

**Comment by Ladicek** [comment]
Also, one thing just to be sure: I'm not a lawyer and you shouldn't take my word as legal advice for sure :-)

**Comment by albert0815** [comment]
I am a little confused: Searching for jakarta.el just finds the one match in the pom.xml from the hibernate-validator (no code - this is why I was assuming that hibernate-validator doesn't actually use that dependency). As per wikipedia code moved to jakarta.el package with version 4. So jakarta.el-api-3.0.3 also contains javax.el packages.

In terms of licenses: We are working together with a lawyer on this. I don't have the final results yet, this was just some sneak preview about the risky candidates in our dependencies (and they mentioned that GPL 2 with CPE for those). So I thought I do a little research about those. I am happy to share the final results as soon as I have them.

**Comment by Ladicek** [comment]
The Quarkus extension for Hibernate Validator doesn't itself necessarily use EL, but you can find the usages in the Hibernate Validator codebase itself: https://github.com/hibernate/hibernate-validator/search?q=jakarta.el

Why does the Scheduler extension depend on EL, I'm not sure.

**Comment by gsmet** [comment]
I confirm Jakarta EL API 3 is licensed under both the Eclipse License and
the (historic) GPL with CPE.

See the Licenses field here:
https://search.maven.org/artifact/jakarta.el/jakarta.el-api/3.0.3/jar -
which is coming directly from the pom.

So I suggest you have a closer look at the licenses.
