### ISSUE TITLE
Better support of OpenTracing in Reactives Routes

### ISSUE THREAD

**Issue by cortex93** [quarkusio/quarkus#15691]
**Describe the bug**
OpenTracing extension doesn't work properly with Reactives Routes.
It needs `@Traced` annotation to be set on the reactive routes to start a new span but parent span is not propagated from the request headers.

**Expected behavior**
OpenTracing extension should work with Reactive Routes the same way it works with Jax-RS. Meaning, without any annotation, a span is created as a childof a potential parent span found in the request headers.

**Actual behavior**
Requires to set `@Traced` to start a span, but it cannot be linked to the incoming parent span.

**To Reproduce**

You can use the sample project of this issue https://github.com/quarkusio/quarkus/issues/15182 and hit the reactive routes `/route1` with a valid Uber-Trace-Id header.

The log will print a different traceId from the one given in the request header.

**Environment (please complete the following information):**
Java version: 11
Quarkus version: 1.11.3-Final
quarkus-smallrye-opentracing
quarkus-vertx-web

**Additional context**
The extension use SmallRye OpenTracing which in turns use https://github.com/opentracing-contrib/java-jaxrs.
There is a vertx.web implentation that may be used. https://github.com/opentracing-contrib/java-vertx-web.

This may be related to https://github.com/quarkusio/quarkus/issues/15182. The vertx.web implementation of opentracing relies on RountingContext to propagate the active span. Thus, removing the need of Thread local storage. This may impact the way the @Traced annotation would work in this context.

**Comment by kenfinnigan** [comment]
We'd be happy to receive a PR for this, as we're currently focused on implementing OpenTelemetry in Quarkus because OpenTracing is no longer maintained

**Comment by luketn** [comment]
> We'd be happy to receive a PR for this, as we're currently focused on implementing OpenTelemetry in Quarkus because OpenTracing is no longer maintained

Quick question: will OpenTelemetry support Reactive everything well out of the box? (Without hacks like @ annotations?)

**Comment by kenfinnigan** [comment]
Are there particular annotations you don't like using? Developer Experience for OpenTelemetry is an area for improvement, please raise issues for any areas of concern

I believe OpenTelemetry integration with Reactive works well, but it depends on whether you're expecting automatic span creation?

**Comment by luketn** [comment]
> it depends on whether you're expecting automatic span creation?

I’m still learning Quarkus, but as I understand it, if use use straight up JAX-RS you will get great support just by adding the extension for OpenTracing / OpenTelemetry right? Is it possible to have the same experience with the Reactive flavour of JAX-RS also without changing or annotating your code? Apologies I may be missing some knowledge about how this works that would require the annotation of code to have the traces and spans be recorded across JAX-RS, database queries, remote http calls etc. It’d be cool if the Quarkus engine could just take care of that!

**Comment by kenfinnigan** [comment]
Ah ok.

If you're just talking about RESTEasy Reactive, then yes OpenTelemetry integrates with that without annotations required on the code.

Database queries is something that is not there today for OpenTelemetry, it's on the roadmap, but the other pieces should be present already

**Comment by luketn** [comment]
Cool, thanks!

**Comment by geoand** [comment]
Should we close this given that both OpenTracing and Reactive Routes have been superceded in Quarkus with alternatives we now put most of our energy into?

**Comment by radcortez** [comment]
> Should we close this given that both OpenTracing and Reactive Routes have been superceded in Quarkus with alternatives we now put most of our energy into?

Yes.
