### ISSUE TITLE
Empty Beans With Arc during BuildStep

### ISSUE THREAD

**Issue by rac021** [quarkusio/quarkus#15696]
## Describe the bug
(Describe the problem clearly and concisely.)
Can't get my Beans using Arc in Method annotaded with @BuidStep 
### Expected behavior
(Describe the expected behavior clearly and concisely.)

   I should have Set<Bean<?>> not Empty 
   I want to instanciate my CDI bean ( myClass ) eagerly. Is this possible ?

### Actual behavior
(Describe the actual behavior clearly and concisely.)

   beans     = []
   
## To Reproduce

```
 @ApplicationScoped
 public class myClass {
   @Inject Logger LOG ;
 }

 public class myProcessor  {

 ...

  @BuildStep
  @Produce( EmptyBuildItem.class )
  public void genLetsEncryptCertificate( BuildProducer<AdditionalBeanBuildItem> addProd ) throws Exception  {

      AdditionalBeanBuildItem beanBuilItem = AdditionalBeanBuildItem.unremovableOf( myClass.class ) ;
      additionalBeanProducer.produce( beanBuilItem ) ;

      Arc.initialize() ;
      ArcContainer container = Arc.container();
       
     InstanceHandle<myClass> instance = container.instance(  myClass.class, Any.Literal.INSTANCE );
     System.out.println( "instance = " + instance ) ;
     // The same with 
     BeanManager beanManager = container.beanManager() ;
     Set<Bean<?>> beans = beanManager.getBeans( myClass.class ) ;
     System.out.println( "beans = " + beans );        
  }
}
// Outupt : 

instance = InstanceHandleImpl [bean=null, instance=null, creationalContext=null, ...
beans     = []

```
Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Linux pc 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux
### GraalVM version (if different from Java)
openjdk version "11.0.10" 2021-01-19

### Quarkus version or git rev
1.12
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven
## Additional context
(Add any other context about the problem here.)

**Comment by manovotn** [comment]
You cannot instantiate your beans at build time - at that moment the CDI container is not yet running and you should let Quarkus take care of that and not start it manually.
If you want eager bean initialization (e.g. as soon as the app starts in runtime), then place `@Startup` annotation on your bean. See also https://quarkus.io/guides/cdi-reference#startup_event

**Comment by mkouba** [comment]
Matej is right, you can't access the CDI container in a build step, neither should you initialize the container manually. You can however access the CDI container in a [recorder method](https://quarkus.io/guides/writing-extensions#bytecode-recording) executed from a `@Record(RUNTIME_INIT)` or  `@Record(STATIC_INIT)`) build step.

And Matej is also right with the `StartupEvent` and `@Startup` ;-).
