### ISSUE TITLE
Hibernate Search dependencies only partially available

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#15703]
## Description

I´m trying out spatial searches with the Hibernate Search Elastic plugin. However, I´m often running into missing dependencies when trying out tutorials or examples, which really confuses me. (likely v5 examples vs v6 dependency)

For example:

### The annotation ```@Spatial``` does not exist as described in the official docs

https://docs.jboss.org/hibernate/search/5.0/reference/en-US/html/spatial.html#spatial

https://github.com/hibernate/hibernate-search/blob/7d51b2e284e989821bb5055ee2e3f2fe263a4aa2/v5migrationhelper/engine/src/main/java/org/hibernate/search/annotations/Spatial.java

### Querying not possible via QueryBuilder

From 11.4:  https://docs.jboss.org/hibernate/search/5.6/reference/en-US/html/ch11.html#__anchor_xml_id_elasticsearch_scrolling_xreflabel_elasticsearch_scrolling_paging_and_scrolling

```
QueryBuilder qb = fullTextSession.getSearchFactory()
    .buildQueryBuilder().forEntity(Book.class).get();
Query luceneQuery = /* ... */;
FullTextQuery query = s.createFullTextQuery( luceneQuery, Book.class );
Sort sort = qb.sort()
        .byNative( "authors.name", "{'order':'asc', 'mode': 'min'}" )
        .andByField("title")
        .createSort();
query.setSort(sort);
List results = query.list();
```

**1. fullTextSession: assuming with the variable here SearchSession is meant, then the getSearchFactory() method does not exist**
**2. FullTextQuery does not exist**
**3. QueryBuilder: I have two QueryBuilders in my application, but not the one that is used here. Mine are:**
**- org.elasticsearch.index.query.QueryBuilder**
**- org.apache.lucene.util.QueryBuilder**

### FullTextEntityManager not available

From https://www.baeldung.com/hibernate-search

```
FullTextEntityManager fullTextEntityManager 
  = Search.getFullTextEntityManager(entityManager);

QueryBuilder queryBuilder = fullTextEntityManager.getSearchFactory() 
  .buildQueryBuilder()
  .forEntity(Product.class)
  .get();
```

**Search.getFullTextEntityManager() does not exist**

### The only way I´m able to do queries is this one:

```
// Not shown: get the entity manager and open a transaction
SearchSession searchSession = Search.session( entityManager ); 

SearchResult<Book> result = searchSession.search( Book.class ) 
        .where( f -> f.match() 
                .field( "title" )
                .matching( "robot" ) )
        .fetch( 20 ); 

long totalHitCount = result.total().hitCount(); 
List<Book> hits = result.hits(); 
// Not shown: commit the transaction and close the entity manager
```

So is it something Quarkus related, am I missing dependencies or is something even deprecated / removed from Hibernate Search I´m not aware of? Thanks for any advice

**Comment by gsmet** [comment]
You are referring to the documentation of Hibernate Search 5.

Quarkus includes Hibernate Search 6 so try this documentation instead: https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/ .

For instance: https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-geopoint and https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-predicate-spatial-within .

**Comment by yrodiere** [comment]
> You are referring to the documentation of Hibernate Search 5.
> 
> Quarkus includes Hibernate Search 6 so try this documentation instead: https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/ .
> 
> For instance: https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#mapper-orm-geopoint and https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-predicate-spatial-within .

This.

What's more, the sources you linked are indeed in the Search 6 codebase, but are part of a "migration helper" to use *some* of the Hibernate Search 5 APIs on top of Hibernate Search 6, and only in *some* setups. This migration helper does not make sense in Quarkus for various reasons, so you should ignore it.

**Comment by mklueh** [comment]
Thanks guys
