### ISSUE TITLE
quarkus-oidc : quarkus.oidc.client-id property should not be mandatory 

### ISSUE THREAD

**Issue by ah1508** [quarkusio/quarkus#15707]
## Description

`quarkus.oidc.client-id` should not be mandatory with `quarkus-oidc`. 

`quarkus.oidc.auth-server-url` property should be enough if the REST API only need to discover configuration in order to verify JWT present in incoming HTTP requests.

Without `quarkus.oidc.client-id` property : ` io.quarkus.runtime.configuration.ConfigurationException` (_Both 'auth-server-url' and 'client-id' properties must be configured_) thrown by `OidcCommonUtils.verifyCommonConfiguration`

Workaround : setting this property to a dummy value.

**Comment by sberyozkin** [comment]
@ah1508 IMHO there is a need for this optimization. I suppose if the JWKS endpoint is always public then it will work for the bearer tokens/`service` applications only. But there are several ifs:
- if the bearer token is opaque then we need to introspect where the client authentication is required 
- the same may have to be done even for the JWT endpoints if no matching JWK is available and the introspection is enabled
- it is required for the `web-app`/`hybrid` application types
- even if client-id is not required for the local JWK based authentication, I think it is reasonable for the application to assert what client these tokens are associated with - we don't log a client-id yet - but may be we should to make it easier to trace which tokens issued to which clients have failed the verification etc

Given the above and also the fact that a `client-id` is always known (I'm not sure what you meant by `Workaround : setting this property to a dummy value.`), I'm going to close this issue though will wait for your comments first.

**Comment by sberyozkin** [comment]
@ah1508 If you have a case where a single Keycloak realm has more than one `client` definition then it is where `OIDC multi-tenancy` will help - it is more involved than just omitting a client id but IMHO it is really worth to be aware of the client id for the reasons suggested above

**Comment by ah1508** [comment]
Hi,

Indeed, my suggestion concerns cases where the token is a JWT (i.e. not opaque) and OIDC server expose a `jws_uri`. This scenario is quite common.

I don't understand when you write "_Given the above and also the fact that a `client-id` is always known_"; the REST API does not need to be a client of the OIDC server. The REST API only needs to validate tokens issued by the OIDC server to clients (a SPA for instance). I guess that's why spring-security and aspnet security only ask for a issuer uri. They add `/.well-known/openid-configuration` to it, read the `jwks_uri`, etc...

About the dummy value :

`quarkus.oidc.client-id=blablabla`

works. This proves that this property is ignored when not needed and thus could be made optional.

**Comment by sberyozkin** [comment]
@ah1508 have you seen my other suggested 3 reasons ? `quarkus-oidc` is bigger than just the local bearer token verification.

And I know in case of the SPA the Quarkus endpoint is not a client itself but it may need to know it to introspect the token or some SPAs may be doing a pure code flow against Quarkus.

And the client id is known - so you can type a dummy value - but if we start logging something like `Tokens issued to 'blablabla'` then you will only confuse your users - so why would you not enter the real value :-) ? So relaxing a requirement to require setting `client-id` at the initialization time, before we even know what kind of tokens will be there, will save a minute to the users who work with JWT but will produce the runtime errors during the token introspection when the users work with the opaque tokens and forgot to set a client id.

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, what is your opinion ?

**Comment by sberyozkin** [comment]
It won't work if the rest endpoint will want to propagate the bearer token and the exchange protocol is used (to be introduced soon) - the client id will be required I believe to use an exchange token grant

**Comment by ah1508** [comment]
@sberyozkin : I agree with you for opaque token and for all use cases you mention; but I still believe that the amount of configuration should depend on project requirements. 

JWT validation : you need to set the issuer uri
Opaque token: you need to set the issuer uri and the client id of your application
etc...

**Comment by sberyozkin** [comment]
@ah1508 but that was my point. 
We have 2 approaches:
- make it optional and hope everyone is using only JWT tokens and that the providers guarantee that the rotated keys will also match the token kid if it was not matching the local cache and hence no introspection is needed; if users post the opaque tokens then we expose them to the runtime errors/unexpected 401/before they discover they need to set it
- or continue as is and ask the users set the client id they already know

I'll waif for @pedroigor's feedback, thanks

**Comment by pedroigor** [comment]
@sberyozkin @ah1508 AFAIK, a service type application is basically a resource server in the OAuth 2 world. As such, it always has a client id associated with it.

If other frameworks are not forcing a `client_id`, this probably means they are not checking the audience of tokens. And that is a critical validation when verifying/accepting tokens from clients.

The audience should avoid replay attacks and make sure the token is targeted for a particular resource server.

That said, I don't think it makes sense to make client_id optional.

**Comment by sberyozkin** [comment]
@pedroigor right - we can enforce the token audience. And indeed, we can start logging, when the token verification fails the associated client_id so that afterwards the tokens associated with a given client can be traced by sys admins etc :-)

**Comment by sberyozkin** [comment]
@ah1508 OK, let me close this issue - please consider using `quarkus-smallrye-jwt` as well - it actually has no a `client-id` requirement :-) but it does not support the introspection and other options which may require a client id. But I'd encourage you to set the client-id known from the Keycloak realm. etc
thanks
