### ISSUE TITLE
Dev UI log console hides text from main page

### ISSUE THREAD

**Issue by belu** [quarkusio/quarkus#15709]
## Describe the bug
The Dev UI log console hides text from the main page.

### Expected behavior
The text from the main page should be completely visible. At least in minimized form of the Dev Console. Ideally, also if the Dev UI console is expanded.

### Actual behavior
The bottom text is not visible. The Dev UI log console hides text from the main page.

Workaround: Expand log console. Then you can shrink it with the button in the middle until you don't see it anymore :-)

## To Reproduce

1. Use a project with enough RESTEasy-Reactive endpoints included.
2. mvn clean quarkus:dev
3. Open http://localhost:8080/q/dev/io.quarkus.quarkus-resteasy-reactive/scores
4. Scroll down

### Screenshots
![dev-ui-console](https://user-images.githubusercontent.com/1174164/111074677-6b261580-84e4-11eb-80b1-4fd1018577d2.png)

### Quarkus version or git rev
1.12.2.Final

**Comment by gsmet** [comment]
It's already fixed here https://github.com/quarkusio/quarkus/pull/15437 but I forgot to backport it :/

**Comment by belu** [comment]
@gsmet 
You guys are too fast in fixing stuff :-) Will verify next finding with main branch before opening an issue.
