### ISSUE TITLE
Better error handling for quarkus.smallrye-openapi.path

### ISSUE THREAD

**Issue by KarstenWintermann** [quarkusio/quarkus#15714]
## Description

If you set the 2 properties 

```
quarkus.smallrye-openapi.path 
quarkus.swagger-ui.path
```

to the same value, then Swagger UI displays a cryptic error message ("Parser error on line 22: end of the stream or a document separator is expected"). This also happens when `quarkus.smallrye-openapi.path` is set to the default value of `quarkus.swagger-ui.path` (`quarkus.smallrye-openapi.path=/swagger-ui`).

## Implementation ideas

It would be helpful if either a better error message was displayed in Swagger UI or Quarkus refused to start (with a corresponding error message).

**Comment by phillip-kruger** [comment]
Hi @KarstenWintermann .

Good point. Setting those to the same value is invalid. We can check that when building and throw a better exception with a message that should tell the use what is wrong. I will look at this a.s.a.p.

Thanks :)

**Comment by phillip-kruger** [comment]
Fixed in this PR #15769
