### ISSUE TITLE
Regression with Quarkus Guide HTML pages format

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#15722]
Some issues have been reported in this [Zulip thread](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Doc.20pages.20are.20not.20formatted.20correctly), for example, https://quarkus.io/guides/security-jwt is not well formatted when I open it with Firefox - the table of content is misplaced, etc

**Comment by maxandersen** [comment]
i see quirkiness when browsing on mobile -   i think maybe the combo box for past versions are messing with some reactive alignments.

**Comment by gsmet** [comment]
@sberyozkin can you include a screenshot? I have absolutely no problem with either Vivaldi (Chromium-based) or Firefox.

**Comment by gsmet** [comment]
I pushed a change to hide the version selector on mobile.

**Comment by geoand** [comment]
Looks fine now, so I'll close this
