### ISSUE TITLE
Dev UI: open code in IDE should use IDE path from scanning processes

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#15721]
ATM we scan the processes to find which IDE to use, but then we discard the running process command, and invoke `idea` or `eclipse` hoping it's in the user's `$PATH`, which turns out is not necessarily true, for people with multiple versions of each IDEs.

It would be nice if the scanning of processes returned the exact IDE command path and we used that instead of relying on `$PATH`.

CC @geoand

**Comment by geoand** [comment]
This is a really good idea.

**Comment by SaumyaSingh1** [comment]
Nice

**Comment by maxandersen** [comment]
on first hand this does looks interesting but please be aware that wont work if using osx Applications. i.e. if you call the eclipse executable directly on osx it will launch a new instance, not reuse the existing already running eclipse.

I dont know if same goes for other IDE's, but I can very well imagine that there is a shell  / batch wrapper to handle reusing logic thus using the command listed in process table is not a sure thing.

I would say it could be used if and only if no matching binary/script is found in the PATH.

**Comment by FroMage** [comment]
> I would say it could be used if and only if no matching binary/script is found in the PATH.

That's a great idea.

**Comment by geoand** [comment]
Is someone working on this or should I take it?

**Comment by SaumyaSingh1** [comment]
> Is someone working on this or should I take it?
Sure, 
These days, I am exploring Prod Stuff so not working on this :)
