### ISSUE TITLE
VSCode test runner doesn't resolve sub project path for Quarkus based test

### ISSUE THREAD

**Issue by shuawest** [quarkusio/quarkus#15737]
## Describe the bug
(Describe the problem clearly and concisely.)

In VSCode if you have a workspace where the Quarkus project is not at the root of the workspace, quarkus tests don't properly resolve the project to build / run tests on. The root cause exception states the maven artifact pointing at the root directory, not the project subdirectory.  The workaround is to open the quarkus based project in its own workspace where the quarkus project is the root of the workspace - this is not practical given a typical workspace will have many and a hierarchy of projects. 
```
...
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application /Users/jowest/dev/repos/sample-app
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:260)
	... 43 more
```
Note the quarkus project is located at `/Users/jowest/dev/repos/sample-app/quarkus-example`

### Expected behavior
(Describe the expected behavior clearly and concisely.)

In a workspace with more than module / project, I should be able to create a new quarkus project, add a test, and use "Run Test" on any of my @QuarkusTest based tests. No other VSCode configuration should be necessary.  

The same should apply to Intellij, Eclipse, Che, etc.

**Comment by geoand** [comment]
Closing as we never got a reproducer
