### ISSUE TITLE
Vertx with SockJSHandler error

### ISSUE THREAD

**Issue by subhankar-banerjee** [quarkusio/quarkus#15746]
I was trying to compile the below code in vertex 4.0.2 , but I am getting an error :  incompatible types: io.vertx.ext.bridge.BridgeOptions cannot be converted to io.vertx.ext.web.handler.sockjs.SockJSBridgeOptions

  private SockJSHandler eventBusHandler() {
    BridgeOptions options = new BridgeOptions()
      .addOutboundPermitted(new PermittedOptions().setAddressRegex("auction\\.[0-9]+"));
    return SockJSHandler.create(vertx).bridge(options, event -> {
      if (event.type() == BridgeEventType.SOCKET_CREATED) {
        logger.info("A socket was created");
      }
      event.complete(true);
    });
  }

need help

**Comment by cescoffier** [comment]
No, we don't support Vert.x 4 for now. 

However, the sockjs bridge works already. See https://github.com/quarkusio/quarkus-quickstarts/blob/main/vertx-quickstart/src/main/java/org/acme/vertx/SockJsExample.java

**Comment by subhankar-banerjee** [comment]
do we have any Real-time bidding with Websockets and Vert.x using Maven ?
I was following this example: https://vertx.io/blog/real-time-bidding-with-websockets-and-vert-x/ to implement that using Maven but got the above error .....

**Comment by famod** [comment]
@cescoffier I leave it up to you to close this issue whenever you see fit.
