### ISSUE TITLE
Picocli example app readme is incorrect

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#15758]
## Describe the bug
Create app from code.quarkus.io with picocli selected and with Gradle: the readme instructions are incorrect and with bad error report.

### Expected behavior

Readme should show proper Gradle syntax

### Actual behavior

Gradle syntax is incorrect, it should be

```shell script
## incorrect one  (both use of -D and use of help)
./gradlew quarkusDev -Dquarkus.args=='help'

## correct one
./gradlew quarkusDev --quarkus-args='-h'
```

## To Reproduce

Create app from code.quarkus.io with picocli selected and with Gradle.

### Quarkus version or git rev

1.12.2.Final 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew

**Comment by emmanuelbernard** [comment]
@ia3andy is that for you?

**Comment by maxandersen** [comment]
a bit surprised - @aloubyansky shouldn't -D work for gradle plugin too here?

**Comment by ia3andy** [comment]
Good catch! I'll fix it..

**Comment by maxandersen** [comment]
> Good catch! I'll fix it..

but shouldn't -D not work too?

**Comment by ia3andy** [comment]
@maxandersen I have no idea :)

**Comment by ia3andy** [comment]
@maxandersen ok you are right it should work with (
```bash
./gradlew quarkusDev -Dquarkus.args='hello --first-name=andy'
```
I think it's a quarkus core bug with gradle and command mode.

Here is a sample reproducer https://github.com/ia3andy/try-picocli-gradle

cc @stuartwdouglas @glefloch

**Comment by ia3andy** [comment]
ahh it works with:
```bash
./gradlew quarkusDev --quarkus-args='hello --first-name=andy'
```

I found this in the template: https://github.com/quarkusio/quarkus/blob/main/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/examples/picocli-example/base/README.tpl.qute.md

Which I should fix :)
