### ISSUE TITLE
Quartz: Clustered mode is not working fine when using `quarkus.quartz.start-mode=forced`

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15754]
## Describe the bug
When using the property `quarkus.quartz.start-mode=forced` in a clustered setup (2 instances running the same job). When we shutdown one instance, the second instance is not triggered. 

I'm not sure if this is expected or not, but if this is not expected, we should prevent users to use `quarkus.quartz.start-mode=forced` and `quarkus.quartz.clustered=true` at the same time.

Note that using `quarkus.quartz.start-mode=normal` (the default value) works fine.

## To Reproduce

1- git clone https://github.com/Sgitario/beefy-scenarios
2- git checkout reproducer_15754
3- cd beefy-scenarios/017-quartz-cluster
4- mvn clean verify -Dnative -Dquarkus.native.container-build=true (it needs to have built quarkus master locally)

Note that this does not need to be necessarily a native compilation, but it used to happen more often in native.

### Configuration
```properties
# datasource configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2

# custom configuration
owner.name=default

# Quartz configuration
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true
quarkus.quartz.start-mode=forced

# flyway to create Quartz tables
quarkus.flyway.connect-retries=10
quarkus.flyway.table=flyway_quarkus_history
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0
quarkus.flyway.baseline-description=Quartz
```

### Quarkus version or git rev
999-SNAPSHOT

**Comment by mkouba** [comment]
Hm, I don't see how the `quarkus.quartz.start-mode=forced` property can change the behavior if a `@Scheduled` method is present. In fact, the only purpose of this property is to start the Quartz scheduler even if no `@Scheduled` method is present - a job can be registered programatically.

I've tried to reproduce the issue locally with no success. @Sgitario Does the test fail intermittently?

**Comment by Sgitario** [comment]
> Hm, I don't see how the `quarkus.quartz.start-mode=forced` property can change the behavior if a `@Scheduled` method is present. In fact, the only purpose of this property is to start the Quartz scheduler even if no `@Scheduled` method is present - a job can be registered programatically.
> 
> I've tried to reproduce the issue locally with no success. @Sgitario Does the test fail intermittently?

Using `quarkus.quartz.start-mode=forced` is intermittently working, without it. It seems to be working always. 

What is happening is that the QUARTZ triggers table gets locked by the node and when this node is killed, the table remains locked. The second node should unlock the QUARTZ tables and indeed this is behaving this way when not using `quarkus.quartz.start-mode=forced`. My guess is that having the `start-mode` to `forced` is making the second node scheduler not being started or being dismissed for some reason. But honestly, as this seems to be a random behaviour, it's a bit complicated :/

**Comment by mkouba** [comment]
I've just run the test more than 10x in a row (with and without `quarkus.quartz.start-mode=forced`) and no failure :-(. The test for native image seems to always got stuck though. It could be a timing issue or a similar kind of problem. But to be honest I'm not quite sure where to look now. Maybe @machi1990 has some idea?

**Comment by machi1990** [comment]
> I've just run the test more than 10x in a row (with and without `quarkus.quartz.start-mode=forced`) and no failure :-(. The test for native image seems to always got stuck though. It could be a timing issue or a similar kind of problem. But to be honest I'm not quite sure where to look now. Maybe @machi1990 has some idea?

@mkouba @Sgitario I've not checked out the reproducer locally yet. I'll sit on this, next thing in the morning and try to reproduce it.

**Comment by machi1990** [comment]
> I've just run the test more than 10x in a row (with and without `quarkus.quartz.start-mode=forced`) and no failure :-(. The test for native image seems to always got stuck though. It could be a timing issue or a similar kind of problem. But to be honest I'm not quite sure where to look now. Maybe @machi1990 has some idea?

I've tried to reproduce the error with the [quartz quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/quartz-quickstart) by adding the `quarkus.quartz.start-mode=forced` and no issue. Both in native mode and in jvm mode.

**Comment by Sgitario** [comment]
> > I've just run the test more than 10x in a row (with and without `quarkus.quartz.start-mode=forced`) and no failure :-(. The test for native image seems to always got stuck though. It could be a timing issue or a similar kind of problem. But to be honest I'm not quite sure where to look now. Maybe @machi1990 has some idea?
> 
> I've tried to reproduce the error with the [quartz quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/quartz-quickstart) by adding the `quarkus.quartz.start-mode=forced` and no issue. Both in native mode and in jvm mode.

The issue happens in a real environment when you disconnect one node. The another instance is not taking over the scheduled job. As far I can see, the quickstart is only starting up one instance.

**Comment by machi1990** [comment]
> > > I've just run the test more than 10x in a row (with and without `quarkus.quartz.start-mode=forced`) and no failure :-(. The test for native image seems to always got stuck though. It could be a timing issue or a similar kind of problem. But to be honest I'm not quite sure where to look now. Maybe @machi1990 has some idea?
> > 
> > 
> > I've tried to reproduce the error with the [quartz quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/quartz-quickstart) by adding the `quarkus.quartz.start-mode=forced` and no issue. Both in native mode and in jvm mode.
> 
> The issue happens in a real environment when you disconnect one node. The another instance is not taking over the scheduled job. As far I can see, the quickstart is only starting up one instance.

Yes, that's what I tried to reproduce. 
In several trials, I started the more than one instance with `docker-compose up --scale tasks=10 --scale nginx=1` and then continuously scaling up and down the `tasks` service with `docker-compose scale tasks=3` etc while observing the output to see if the job was picked up by another node.

**Comment by Sgitario** [comment]
Ok, thanks for trying! Then I'm running clueless about why the beefy module is behaving this way. I'm experiencing the same than @mkouba. Also, for JVM, if I debug the module and stop the code test flow before killing the node, I also can reproduce it almost 100% of the times.

**Comment by mkouba** [comment]
@machi1990 @Sgitario I have no idea what to do next... do you have any suggestion?

**Comment by Sgitario** [comment]
This test has gone a while ago, and since nobody else has complained about this in almost 2 years, I'm going to close this issue.
