### ISSUE TITLE
`quarkus.http.redirect-to-non-application-root-path` is not working on master branch

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15760]
Given an application with the following configuration:

```
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=/q
quarkus.http.redirect-to-non-application-root-path=true
```

An `http://localhost:8080/openapi` should return an HTTP 301 with a location header `/q/openapi` but is returning a 404. 

Looks like on master we are pre-pending `quarkus.http.root-path`. 
master -> http://localhost:8080/api/health -> redirected to  http://localhost:8080/q/health
previous -> http://localhost:8080/health -> redirected to  http://localhost:8080/q/health>

**Comment by rsvoboda** [comment]
CC @kenfinnigan / @ebullient

**Comment by kenfinnigan** [comment]
That's correct behavior.

All endpoints came off the `http.root-path`, so the redirects do the same. If `http.root-path` is something other than `/` the redirects will come off the path it defines

**Comment by pjgg** [comment]
Is not an issue, is the intended behavior. 
You could set up an app with version 1.7.6 with the following properties

```
quarkus.http.root-path=/api
```

And `/health` endpoint is under `/api/`. So on the current version if you force a redirection `quarkus.http.redirect-to-non-application-root-path=true`, then your health endpoint is under `/api` and redirected to `/q/health`

**Comment by ebullient** [comment]
https://quarkus.io/blog/path-resolution-in-quarkus/ explains how everything should work, with examples. That is how we go forward. ;)

**Comment by rsvoboda** [comment]
Maybe this blog post could be transformed into regular Quarkus guide to summarize available non application endpoints, their paths and configuration options.

New blog posts are coming and path-resolution-in-quarkus one will be moved to "Older posts" sooner or later. Once that happens Quarkus users will have harder time to find the info.
Another benefit of regular guide is that the text is present in the main Quarkus codebase and it is easier to find the content with offline google search, I mean `git grep`.
