### ISSUE TITLE
RESTEasy Reactive exception mapper issues

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#15763]
This one happens only in DEV mode. Start with this endpoint:

```java
@Path("/")
public class GreetingResource {

    @Path("fruit/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Object> fruit(@PathParam("id") Long id){
        throw new NotFoundException();
    }
    
//    @ServerExceptionMapper(NotFoundException.class)
//    public Response handleNotFound() {
//        System.err.println("We're in there");
//        return Response.status(Response.Status.NOT_FOUND)
//                .entity(new JsonObject()
//                        .put("type", "https://example.com/probs/cant-touch-this")
//                        .put("title", "we could not find it :("))
//                .type(MediaType.APPLICATION_JSON)
//                .build();
//    }
}
```

Now trigger the 404 with `GET /fruit/123`, you get the DEV Mode 404 red page.

Now uncomment the exception mapper and reload the page, you get:

```
Error handling 56fcd1fd-68f3-4922-926f-a263fa4ab22c-2, java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.acme1.GreetingResource$GeneratedExceptionHandlerFor$NotFoundException$OfMethod$handleNotFound
```

This looks very similar to #15748, but only for DEV mode. Perhaps it's different?

Now, a more annoying thing is that if I change the endpoint method to:

```java
    @Path("fruit/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Object> fruit(@PathParam("id") Long id){
        return Uni.createFrom().failure(() -> new NotFoundException());
    }
```

It behaves differently and doesn't even try to run my exception mapper, when it should be identical to the previous endpoint.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15767 takes care of the second problem. The first one I can't reproduce

**Comment by geoand** [comment]
The first problem is due to Vertx event-loop threads hanging on to the original Quarkus ClassLoader.
@stuartwdouglas haven't we fixed this before somewhere?

**Comment by geoand** [comment]
Actually I am pretty sure I know what the problem is but I need to investigate more

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15779 should fix the first case

**Comment by FroMage** [comment]
Thanks!

**Comment by geoand** [comment]
YW!
