### ISSUE TITLE
Version overrides - we should warn users to primarily use versions defined in Quarkus BOM

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1577]
Version overrides - we should warn users to primarily use versions defined in Quarkus BOM
The initial motivation for this version override topic is https://github.com/quarkusio/quarkus/issues/1522

Good fit for end-user warning could be https://quarkus.io/guides/getting-started-guide => 4. Bootstrapping the project => Note box after "Once generated, look at the pom.xml. You will find the import of the Quarkus BOM, allowing to omit the version on the different Quarkus dependencies. In addition, you can see the quarkus-maven-plugin responsible of the packaging of the application and also providing the development mode." text.

Maybe https://quarkus.io/guides/application-configuration-guide could be worth the note too.

Tips for other places to mention this are welcome.

**Comment by rsvoboda** [comment]
Issues like https://stackoverflow.com/questions/55233662/how-add-flyway-dependency-and-build-native-image-quarkus-java-lang-classnotfound shows that we should warn also about risk for 3rd party libraries in native mode.
Native mode works with components defined in BOM, for 3rd party libraries there is a risk users would hit an issue.

**Comment by gsmet** [comment]
I'm closing this. If we think it's necessary, open a PR directly, not an issue stalling for months.
