### ISSUE TITLE
Path with path parameters conflicting

### ISSUE THREAD

**Issue by spligo** [quarkusio/quarkus#15771]
## Describe the bug
There are two @Paths A ("/cars/{brand}/{model}") and B ("/cars/notification/all"). When I try to call path B it always takes me to path A. Then I add another @Path C ("/cars/messages/all"), and path C works as expected. When I swap B and C around (i.e. B => "/cars/messages/all" and C => "/cars/notification/all"), B now works with the new endpoint but C does not work but goes to A.

```
@Get
@Path("/cars/{brand}/{model}")
@Produces(MediaType.APPLICATION_JSON)
public Response getModel(@PathParam("brand") String brand, @PathParam("model") String model) {
  ...
}

@Get
@Path("/cars/notification/all")
@Produces(MediaType.APPLICATION_JSON)
public Response getAllNotifications() {
  ...
}

@Get
@Path("/cars/messages/all")
@Produces(MediaType.APPLICATION_JSON)
public Response getAllMessages() {
  ...
}
```

### Expected behavior
If request path matches B exactly then endpoint B should be called => `getAllNotifications()`.
If request path does not match B or C then A should be called => `getModel()`
Endpoint C works as expected.

### Actual behavior
If request path matches B exactly, B is not called but rather A is called => `getModel()`.

## To Reproduce
I have tried to create a small enough project to reproduce it but without any luck. It only occurs on the main project.

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Microsoft Windows [Version 10.0.18363.1379]

### Output of `java -version`
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

### Quarkus version or git rev
1.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Apache-Maven\apache-maven-3.6.3\bin\..
Java version: 11.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.10
Default locale: en_ZA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Additional context
(Add any other context about the problem here.)

**Comment by spligo** [comment]
Quarkus version is 1.12.1.Final

**Comment by geoand** [comment]
Can you please add a reproducer project?

**Comment by geoand** [comment]
Closing as we did not receive feedback
