### ISSUE TITLE
Quarkus reports occupied http port on occupied https port

### ISSUE THREAD

**Issue by szgergo** [quarkusio/quarkus#15776]
## Describe the bug
I have tried to enable https in Quarkus by adding keystore to src/main/resources and defining the following properties:
`quarkus.http.port=10000
quarkus.http.ssl-port=443
quarkus.http.ssl.certificate.key-store-file=keystore.jks`
When I started the application it failed with an error message stating that port 10000 is occupied. This was not the case (checked with netstat). The problem was that the 443 port was in fact occupied.

### Expected behavior
Throw exception on actually occupied port. (In this case the 443 port)

### Actual behavior
Throws exception on not occupied http port instead of the occupied https port.

## To Reproduce

1. Download the zip: [black-dwarf-main.zip](https://github.com/quarkusio/quarkus/files/6151337/black-dwarf-main.zip)
2. Start a process on port 443 (For example netcat -l 443)
3. Start the application (run mvn clean install -U then java -jar deployment/target/quarkus-app/quarkus-run.jar)

## Environment (please complete the following information):

**Uname -a output:**
Darwin Gergos-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

**Java version:**
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

**GraalVM version:**
No GraalVM

**Quarkus version:**
 1.12.2.Final

**Maven version:**
Maven home: /opt/homebrew/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.10, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_HU, platform encoding: UTF-8
OS name: "mac os x", version: "11.2.3", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
Closing in favor of https://github.com/quarkusio/quarkus/issues/22967 which is essentially the same issue but has more details

**Comment by yrodiere** [comment]
Closing now, I think @geoand forgot to actually do it :)

**Comment by geoand** [comment]
Oops! Thanks for catching the mistake @yrodiere
