### ISSUE TITLE
RestAssured Json Schema Validator

### ISSUE THREAD

**Issue by alphawolf1988** [quarkusio/quarkus#1578]
Currently RestAssured is available in the Quarkus BOM. It would be nice if also the Json Schema Validator is included:

`<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <scope>test</scope>
 </dependency>`

**Comment by gsmet** [comment]
PR welcome :).

**Comment by gsmet** [comment]
PR merged.
