### ISSUE TITLE
Quarkus/Jaeger OpenTracing SenderFactory not customisable

### ISSUE THREAD

**Issue by ambition-consulting** [quarkusio/quarkus#15799]
Following the default does not work: When I add
`META-INF/services/io.jaegertracing.spi.SenderFactory`
with the SenderFactory canonical name include to my quarkus application, this will not be picked up by the SenderResolver from jaeger-core:
`ServiceLoader<SenderFactory> senderFactoryServiceLoader = ServiceLoader.load(SenderFactory.class,
        SenderFactory.class.getClassLoader());`
Instead, something like this would work:
`ServiceLoader<SenderFactory> senderFactoryServiceLoader = ServiceLoader.load(SenderFactory.class,
        SecuritySupport.getContextClassLoader());`

This effectively stops us from adding custom senders, and makes the quarkus.jaeger.sender-factory pretty pointless.

Does anybody know a workarround? I do not fully understand, where SenderFactory.class.getClassLoader() takes it's classes from, and how I could squeeze in my customised sender+factory.

**Comment by kenfinnigan** [comment]
@ambition-consulting, as we're working on integrating OpenTelemetry for tracing and OpenTracing is no longer maintained, it's unlikely the core team would investigate this issue.

However, we'd gladly accept a PR from the community to resolve it

**Comment by ambition-consulting** [comment]
That would include updating an already now really outdated, semantically
breaking Jaeger Core versions across  multiple independent open source
repositories.

I guess I will have to for the next giant should to hop on instead.

Ken Finnigan ***@***.***> schrieb am Mi., 17. März 2021,
13:00:

**Comment by radcortez** [comment]
Closing this, because we are no longer supporting OpenTracing.
