### ISSUE TITLE
Move codestarts to their own artifact

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#15813]
## Description

When https://github.com/quarkusio/quarkus/issues/15812 is ready, we should move the existing codestarts (they are cuttently located in platform-descriptor-json):

- The core quarkus codestarts to the `devtool-commons` module or to a new module (`quarkus-project-codestarts`
- The examples to a new module `quarkus-project-core-extension-codestarts`
- The jbang codestarts to a new module `quarkus-jbang-project-codestarts`

**Comment by aloubyansky** [comment]
Do you still also want them to be merged into a single platform-wide codestarts artifact? Or is this different?

**Comment by ia3andy** [comment]
> Do you still also want them to be merged into a single platform-wide codestarts artifact? Or is this different?

@aloubyansky all the quarkus-core extension codestarts be in `quarkus-project-core-extension-codestarts`
