### ISSUE TITLE
Quarkus maven plugin does not take pluginRepositories into consideration

### ISSUE THREAD

**Issue by rsynek** [quarkusio/quarkus#15817]
## Describe the bug
The Quarkus maven plugin downloads dependencies of the project. Unfortunately, it does not take into consideration the project's `pluginRepositories`. As a result, if there is a plugin that is not available in maven central, the Quarkus maven plugin fails, despite there is a `pluginRepository` defined that contains this plugin.

To illustrate the situation, the reproducer (see below) uses the `jboss-parent` as its parent pom.xml. The `jboss-parent` overrides the `maven-compiler-plugin` version to `3.8.1-jboss-1`, which is available only in the JBoss Nexus. The `jboss-parent` defines a `pluginRepository` that points to the JBoss Nexus. 

Thus, while the `mvn clean install` completes successfully, `mvn quarkus:dev` does not.

If the project defines the JBoss Nexus as a `repository` (and not a `pluginRepository`!), the `mvn quarkus:dev` downloads the dependency and runs successfully.

### Expected behavior
Successfully run the application.

### Actual behavior
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.12.2.Final:dev (default-cli) on project quarkus-maven-plugin-reproducer: Failed to obtain descriptor for Maven plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1 goal compile: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.1-jboss-1 in central (https://repo.maven.apache.org/maven2) 

## To Reproduce

1. erase the `maven-compiler-plugin:3.8.1-jboss-1` from your local maven repository
2. git clone https://github.com/rsynek/quarkus-maven-plugin-reproducer && cd quarkus-maven-plugin-reproducer
3. mvn quarkus:dev

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven

**Comment by aloubyansky** [comment]
Just for your info, a workaround would be to add `compile` explicitly to the command line.

**Comment by rsynek** [comment]
@aloubyansky interesting, thanks for sharing.
