### ISSUE TITLE
Quarkus doesn't refresh when resource files are updated

### ISSUE THREAD

**Issue by maryellenw77** [quarkusio/quarkus#15820]
## Describe the bug
My project has a set of json configuration files in the resources directory. We'd like Quarkus to restart and load these files when they are updated. Currently, Quarkus sees the file updates but determines that a restart isn't necessary. We know this because we see the message 'Files changed but restart not needed' when we make modifications.

### Expected behavior
Quarkus is restarted when any resource file is modified.

### Actual behavior
Quarkus is only restarted when certain resources files are modified.     Not certain what these files are, but they include banner.txt.    

## To Reproduce
1.  Add file fields.json to resources directory 
2.  Start quarkus
3.  Edit fields.json
4.  See message "Files changed but restart not needed'

### Output of `java -version`
openjdk 11.0.10

### Quarkus version or git rev
1.10.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

## Additional context
None.

**Comment by mkouba** [comment]
@maryellenw77 FYI you should be able to specify additional watched resources via the [quarkus.live-reload.watched-resources](https://quarkus.io/guides/all-config#quarkus-core_quarkus.live-reload.watched-resources) config property. Unfortunately, directories and wildcards are not supported. @geoand Maybe we could try to implement wildcards so that e.g. `*.json` would match all json resources?

**Comment by geoand** [comment]
@mkouba yeah, that sounds very reasonable

**Comment by geoand** [comment]
@gastaldi @radcortez is there anything in SR Commons that could be used for ^

**Comment by radcortez** [comment]
I don't think we have. Feel free to add something :)

**Comment by gastaldi** [comment]
@geoand support for wildcards? You mean like in https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/util/GlobUtil.java?

**Comment by geoand** [comment]
Right! That exactly like what we want here. Mind integrating it in the handling of `quarkus.live-reload.watched-resources`?

**Comment by gastaldi** [comment]
I think this issue may be closed (or renamed) and can be marked as a `good-first-issue` for our rockstar community contributors 😉

**Comment by gsmet** [comment]
Stupid question maybe but why don't we reload by default when resources are changed?

**Comment by mkouba** [comment]
> Stupid question maybe but why don't we reload by default when resources are changed?

I think that historically we've chosen this path to minimize the number of resources that can trigger the reload, i.e. not every resource modification requires a reload. Anyway, if we change it now it would be a non-compatible change. So we should be careful here.
