### ISSUE TITLE
ElasticRestClient fails to load the provided custom configuration via @ElasticsearchClientConfig

### ISSUE THREAD

**Issue by aashreya** [quarkusio/quarkus#15825]
## Describe the bug
The ElasticRestClient fails to load the provided custom configuration via @ElasticsearchClientConfig.
I followed the documentation here https://quarkus.io/guides/elasticsearch#programmatically-configuring-elasticsearch to provide a custom configuration for elastic search. 

In my case I am adding  AWS signing interceptor to the httpClientBuilder.

Version 1.12.2.Final

### Expected behavior
The custom configuration (signing interceptor) should get loaded up

### Actual behavior
Fails to load the custom configuration.

## To Reproduce

Add a new custom configuration based on the docs.
```
@ApplicationScoped
@ElasticsearchClientConfig
public class MyCustomConfig implements RestClientBuilder.HttpClientConfigCallback {

   @Override
    public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
             // log something here
   }

}

```
Then inject the REST client.

```
 @Inject
 RestClient lowLevelClient;
```

No logged message above

From the MR here: https://github.com/quarkusio/quarkus/commit/08df613dd1f989a96b2414755ddd1dbc1c8ec02b#diff-3530ce31269994606ad048f4d42f2fa57425d1fa08c6cf4ffb37980ee8dcbd5dR86

```
Iterable<InstanceHandle<RestClientBuilder.HttpClientConfigCallback>> handles = Arc.container()
                        .select(RestClientBuilder.HttpClientConfigCallback.class, new ElasticsearchClientConfig.Literal())
                        .handles();
```

I copied the above code to my unit tests and the size of the `handles` variable always seem to be 0.

Arc.container() does not seem to find the custom config. 

Or is there another class registration step missed in the documentation ?

Any feedback is really appreciated. 
Thank you

Tagging original authors for help.
@eAybars @gsmet

**Comment by yrodiere** [comment]
I believe your bean was detected as unused by Arc and was subsequently removed. See [here](https://quarkus.io/guides/cdi-reference#remove_unused_beans).

As a workaround, annotate your type with `@Unremovable`.

We should add something in the extension to tell Quarkus that anything annotated with `@ElasticsearchClientConfiguration` should not be considered as unused.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/15833 should fix it.

**Comment by eAybars** [comment]
Hi, I was also able to reproduce the problem with a bean which is annotated with  `@Unremovable` , `@Dependent` and `@ElasticsearchClientConfig`. 

When I select the bean through Arc using its implementation class (or `RestClientBuilder.HttpClientConfigCallback` with `@Any` qualifier) and inspect the returned beans qualifiers, `@ElasticsearchClientConfig` is not listed among them. It seams to have only  `@Default` and `@Any`. I suspect `@ElasticsearchClientConfig` is not registering as a qualifier somehow. Could it be because the qualifier definition has `@Target({ FIELD, TYPE, PARAMETER })` instead of ` @Target({METHOD, FIELD, PARAMETER, TYPE})`?

**Comment by yrodiere** [comment]
> Could it be because the qualifier definition has `@Target({ FIELD, TYPE, PARAMETER })` instead of ` @Target({METHOD, FIELD, PARAMETER, TYPE})`?

That sounds... strange?

@eAybars I'm interested in that reproducer. In particular, can you turn it into a test inside the extension, next to `ElasticsearchClientConfigTest`? It's really surprising that `ElasticsearchClientConfigTest` passes if user beans are ignored.

**Comment by gsmet** [comment]
We need to make `ElasticsearchClientConfig` a bean.

**Comment by gsmet** [comment]
I think we also need something like: https://github.com/quarkusio/quarkus/pull/15838

But a test/reproducer would help, either in the code tree or as a standalone Maven project.

**Comment by gsmet** [comment]
No need for a reproducer. AFAICS the test is only working because we inject the class itself to test it. If I remove
```
    @Inject
    @ElasticsearchClientConfig
    TestConfigurator testConfigurator;
```
the configurator is not executed.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/15838 fixes the test and makes things work.

**Comment by gsmet** [comment]
@eAybars as a workaround for now, you can try this: inject your configurator in one of the beans of your application:
```java
@Inject
@ElasticsearchClientConfig
MyCustomConfig myCustomConfig;
```
This should trigger adding `@ElasticsearchClientConfig` as a qualifier and make things work (hopefully).

**Comment by gsmet** [comment]
Well, this ^ was for @aashreya :)

**Comment by aashreya** [comment]
Thanks @gsmet for the fixes. 
I actually gave that a try and Arc still couldn't find the class annotated with `@ElasticsearchClientConfig `
I can give it a try again with the above fixes.

**Comment by aashreya** [comment]
Can this fix be backported to 1.12.* or the next version of 1.13* ?

**Comment by gsmet** [comment]
Yes, it's going to be backported to 1.13.

**Comment by deepankarmalhan** [comment]
Has this fixed been released? I'm running into the same issue.

**Comment by loicmathieu** [comment]
@deepankarmalhan this has been fixed on Quarkus 1.13, wich version are you running on?

**Comment by deepankarmalhan** [comment]
Running on 1.12, upgrading to 1.13 right now since I saw the milestone tags on this issue. I can report back if the issue still exists.

**Comment by deepankarmalhan** [comment]
Updating to `1.13.2.Final` worked. Thanks!
