### ISSUE TITLE
Fetch a lazy association after using getReference doesn't work with Hibernate Reactive

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#15839]
It's possible to reproduce it adding the following method to `HibernateReactiveTestEndpointFetchLazy`:
```
    @GET
    @Path("/getReferenceBooksWithMutiny/{authorId}")
    public Uni<Collection<Book>> getReferenceBooksWithMutiny(@PathParam("authorId") Integer authorId) {
        return Mutiny.fetch(mutinySession.getReference(Author.class, authorId).getBooks());
    }
```
and the test in `HibernateReactiveFetchLazyTest`
```
    @Test
    public void fetchAfterGetReferenceWithMutiny() {
        RestAssured.when()
                .post("/prepareDb")
                .then()
                .body(is("Neal Stephenson"));

        Response response = RestAssured.when()
                .get("/getReferenceBooksWithMutiny/567")
                .then()
                .extract().response();
        assertTitles(response, "Cryptonomicon", "Snow Crash");
    }
```

See my branch: https://github.com/DavideD/quarkus/tree/getreference

This will cause a Session is closed exception. Adding transaction won't cause any exception but it will return 0 results.

**Comment by DavideD** [comment]
@gavinking Am I missing something or this should work?

**Comment by gavinking** [comment]
I think you need to fetch the entity first. `getReference()` usually returns a proxy.

**Comment by DavideD** [comment]
Do you mean like this?
```
    @GET
    @Path("/getReferenceBooksWithMutiny/{authorId}")
    public Uni<Collection<Book>> getReferenceBooksWithMutiny(@PathParam("authorId") Integer authorId) {
        return Mutiny.fetch(mutinySession.getReference(Author.class, authorId))
                .chain(author -> Mutiny.fetch(author.getBooks()));
    }
```

**Comment by gavinking** [comment]
yeah, like that, not like what I wrote :-)

**Comment by DavideD** [comment]
:-)

Sadly, it still doesn't work and gives Session already closed.

**Comment by gavinking** [comment]
Does it work in a plain HR test?

**Comment by DavideD** [comment]
I will try to test this exact case, but we have several tests in `ReferenceTest` similar to this one.

**Comment by gavinking** [comment]
well we probably do need to add a test with a detached object like the example I added to the docs.

**Comment by DavideD** [comment]
I think we already cover these cases in Hibernate reactive.
See [ReferenceTest](https://github.com/hibernate/hibernate-reactive/blob/183fa297317416646d6d9448cbad760a1cb07e30/hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java#L101):

* [testDetachedEntityReference](https://github.com/hibernate/hibernate-reactive/blob/183fa297317416646d6d9448cbad760a1cb07e30/hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java#L57)
* [testDetachedProxyReference](https://github.com/hibernate/hibernate-reactive/blob/183fa297317416646d6d9448cbad760a1cb07e30/hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReferenceTest.java#L101)

**Comment by DavideD** [comment]
I haven't verified it, but I suspect this issue is related to this one on Hibernate Reactive: https://github.com/hibernate/hibernate-reactive/issues/975
