### ISSUE TITLE
ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature #783 

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#15840]
## Describe the bug
I'm using jbang to create a simple rest service, and it fails because of the mentioned exception because of of mismatched dependencies as the Jackson Core version resolved is jackson-core-2.11.1 but it looks like jackson-core-2.12.1 is required

The original report for the issue is: https://github.com/jbangdev/jbang/issues/783

## To Reproduce
1. run the example linked in the jbang [issue](https://github.com/jbangdev/jbang/issues/783)

**Comment by maxandersen** [comment]
this is afaics not an issue specific for jbang the same happens when using that single maven dependency in either maven or gradle project. 

Hints at some inconcistency in the Jackson extension itself.

**Comment by geoand** [comment]
Quarkus imports the Jackson BOM, so `1.12.1` should be enforced throughout. 
Any idea where `2.11.1` is coming from?

**Comment by lburgazzoli** [comment]
I don't, the only think I've added in my example was the resteasy-jackson extension

**Comment by maxandersen** [comment]
if you just add same single dep to a project then the jackson deps are not locked in  and thus 2.12 comes in via resteasy and vertx afaics.

basically - you must use a bom for this all to work.

**Comment by gastaldi** [comment]
As explained by @maxandersen in https://github.com/quarkusio/quarkus/issues/15840#issuecomment-802389676, you need to add a BOM for this to work. Closing.
