### ISSUE TITLE
Quarkus extension conditional dependencies

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#15844]
## Description

It becomes more and more evident that the dependency resolution mechanism is lacking a feature of including certain extra dependencies only in cases when all their required dependencies are satisfied and not including them if at least one of their dependencies isn't found among the project's dependencies.

Given that Quarkus Maven and Gradle plugins use different (build system-specific) dependency resolver implementations, this issue will be split into the following subtasks:

- [x] support for extension conditional dependencies for Maven projects (https://github.com/quarkusio/quarkus/pull/15736)
- [x] support for extension conditional dependencies for Gradle projects (https://github.com/quarkusio/quarkus/pull/16147)
- [x] documentation on how to use, configure and analyze conditional dependencies

**Comment by maxandersen** [comment]
@aloubyansky this issue was done except for the documentation was not marked as done.

I see https://quarkus.io/guides/conditional-extension-dependencies is there.

Thus closing this. If things missing in docs please open separate more dedicated issue.
