### ISSUE TITLE
RESTEasy Reactive: UniInvoker signatures are wrong

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#15852]
Due to how we implement it, all its return types are `Uni<?>` instead of the more useful `Uni<R>` for methods like `<R> get(Class<R>)`, forcing users to cast the return types to the right type:

```java
UniInvoker invocation = target.request().rx(UniInvoker.class);
Uni<String> ret = (Uni<String>) invocation.get(String.class);
```

This is because we implemented it with:

```java
public class UniInvoker extends AbstractRxInvoker<Uni<?>> {}
...
public abstract class AbstractRxInvoker<T> implements RxInvoker<T> {

    @Override
    public <R> T get(Class<R> responseType) {
        return method("GET", responseType);
    }
}
```

Now, for some reason the JAXRS interface is:

```java
public interface RxInvoker<T> {

    public <R> T get(Class<R> responseType);
}
```

Which is pretty useless. We could mitigate this by making `UniInvoker` generic.

Or we could do like for `MultiInvoker` (for some reason this does pass the Java type system):

```java
public class MultiInvoker extends AbstractRxInvoker<Multi<?>> {

    @SuppressWarnings("unchecked")
    @Override
    public <R> Multi<R> get(Class<R> responseType) {
        return (Multi<R>) super.get(responseType);
    }
}
```

Perhaps we should do both (generify and fix the signature via that weirdly allowed covariant override)?

**Comment by FroMage** [comment]
Huh, `CompletionStageRxInvoker` does the same trick to fix the signature of `<R> get(Class<R>)`:

```java
public interface CompletionStageRxInvoker extends RxInvoker<CompletionStage> {

    @Override
    public CompletionStage<Response> get();

    @Override
    public <T> CompletionStage<T> get(Class<T> responseType);
```

But interestingly it also overrides `get()` to return a `CompletionStage<Response>` which is probably what we should do too?

**Comment by geoand** [comment]
> But interestingly it also overrides `get()` to return a `CompletionStage<Response>` which is probably what we should do too?

That does sounds reasonable
