### ISSUE TITLE
Improvements for in tree extension creation

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#15851]
I tried to create a new extension in our tree using the command line.

First, I tried to create the extension in `extensions/` but this doesn't work as it tries to find `extensions/extensions/pom.xml`. I wonder if we could support that?

Next I tried to execute `mvn quarkus:create-extension` in the root of Quarkus and it didn't work. I had to use `mvn io.quarkus:quarkus-maven-plugin:create-extension`.

Third issue, it's not exactly clear that you shouldn't have the `quarkus-` prefix in the id. I think we shouldn't add the `quarkus-` prefix if it's already there in the provided id (and should probably be removed to generate the name).

Then the parent pom of the extension (the one of the module containing runtime and deployment) contains:
```
    <properties>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>
```
It shouldn't be the case as it's coming from the parent.

In quarkus-extension.yaml, the name is `Quarkus - My Extension`. It shouldn't have the `Quarkus - ` prefix.

(Will add more findings if I find more)

**Comment by ia3andy** [comment]
Ah cool, thanks for the feedbacks!!!

> I tried to create a new extension in our tree using the command line.
> 
> First, I tried to create the extension in `extensions/` but this doesn't work as it tries to find `extensions/extensions/pom.xml`. I wonder if we could support that?
> 

This should work, there is a hook to look in the parent dir, did you try with `mvn io.quarkus:quarkus-maven-plugin:create-extension`? Maybe there is a bug.

> Next I tried to execute `mvn quarkus:create-extension` in the root of Quarkus and it didn't work. I had to use `mvn io.quarkus:quarkus-maven-plugin:create-extension`.
> 

I don't think we have the quarkus plugin in the plugin dependencies in quarkus-core. I am not sure how we could solve this?

> Third issue, it's not exactly clear that you shouldn't have the `quarkus-` prefix in the id. I think we shouldn't add the `quarkus-` prefix if it's already there in the provided id (and should probably be removed to generate the name).
> 

Good idea!

> Then the parent pom of the extension (the one of the module containing runtime and deployment) contains:
> 
> ```
>     <properties>
>         <maven.compiler.parameters>true</maven.compiler.parameters>
>         <maven.compiler.source>1.8</maven.compiler.source>
>         <maven.compiler.target>1.8</maven.compiler.target>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
>     </properties>
> ```
> 
> It shouldn't be the case as it's coming from the parent.

ok!

> 
> In quarkus-extension.yaml, the name is `Quarkus - My Extension`. It shouldn't have the `Quarkus - ` prefix.
> 

👍

> (Will add more findings if I find more)

thanks!!

**Comment by ia3andy** [comment]
Ok it was a bug, it should have worked from the `extensions` dir.. I will provide a PR for all those..
