### ISSUE TITLE
KubernetesTestServer does not return set mocked pods

### ISSUE THREAD

**Issue by el10686** [quarkusio/quarkus#15853]
## Describe the bug
We (me and @chris-asl) are using Quarkus and quarkus-kubernetes-client following the documentation [Quarkus Kubernetes Client](https://quarkus.io/guides/kubernetes-client).

The test outlined in the documentation is not passing and fails with
```
[ERROR] Failures:
[ERROR]   KubernetesClientTest.testInteractionWithAPIServer:38 1 expectation failed.
JSON path size() doesn't match.
Expected: is <2>
  Actual: <0>
```
We have created a test repository demonstrating exactly the problem (using `code.quarkus.io`) so that we have a minimal, complete and verifiable example, which you can find [here](https://github.com/el10686/quarkus-kubernetes-client).

The project contains three branches:
- master: code as described from the docs
- use-quarkus-snapshot: uses latest Quarkus SNAPSHOT (as outlined in CONTRIBUTING doc), still failling
- fix-with-deprecated-resource: uses a deprecated resource `KubernetesMockServerTestResource` with which the **tests are passing**

Is there something we're missing or are the docs outdated?

### Expected behavior
Expected Kubernetes Mock Server to return 2 pods.

### Actual behavior
Returned 0 pods.

## To Reproduce
Here is a project that reproduces the issue (as described above)
https://github.com/el10686/quarkus-kubernetes-client

1. git clone
2. `./mvnw test`

### Configuration
Empty file

### Output of `uname -a` or `ver`
`Linux vanias-G5-5500 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

### GraalVM version (if different from Java)
Not using GraalVM

### Quarkus version or git rev
1.12.2.Final and tested against latest snapshot

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/vanias/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-45-generic", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
> https://github.com/el10686/quarkus-kubernetes-client

Something tells me I know where the username comes from :)

More seriously, I'll look into the issue son

**Comment by geoand** [comment]
@FroMage would you like to take a look at `getting-started-testing.adoc` and `kubernetes-client.adoc` to see if there is anything we need to update based on your work with `WithKubernetesTestServer`?

**Comment by FroMage** [comment]
Damn, I forgot to update that one, didn't I?

**Comment by geoand** [comment]
Well, I also forgot about it and I'm the one that reviewed it, so 🤷🏼

**Comment by FroMage** [comment]
Actually, `WithKubernetesTestServer` is documented there.

**Comment by chris-asl** [comment]
@FroMage 
The problem is that although it's documented, we're using it like this https://github.com/el10686/quarkus-kubernetes-client/blob/master/src/test/java/org/acme/KubernetesClientTest.java, but the test is failing
```
[ERROR] Failures:
[ERROR]   KubernetesClientTest.testInteractionWithAPIServer:38 1 expectation failed.
JSON path size() doesn't match.
Expected: is <2>
  Actual: <0>
```

Are we missing something fundamental?

**Comment by FroMage** [comment]
Oh OK, lemme check

**Comment by FroMage** [comment]
#15853 should fix that. Basically CRUD mode is now the default, so if you want to fix your test in the simplest way, just add `crud = false` on the annotation.
Or set up your test resources like this:

```java
@WithKubernetesTestServer
@QuarkusTest
public class KubernetesClientTest {

    @KubernetesTestServer
    KubernetesServer mockServer;

    @BeforeEach
    public void before() {
        final Pod pod1 = new PodBuilder().withNewMetadata().withName("pod1").withNamespace("test").and().build();
        final Pod pod2 = new PodBuilder().withNewMetadata().withName("pod2").withNamespace("test").and().build();

        // Set up Kubernetes so that our "pretend" pods are created
        mockServer.getClient().pods().create(pod1);
        mockServer.getClient().pods().create(pod2);
    }

    @Test
    public void testInteractionWithAPIServer() {
        RestAssured.when().get("/pod/test").then()
                .body("size()", is(2));
    }

}
```

IMO this is cleaner as it doesn't require mocking HTTP which can be error-prone.

**Comment by FroMage** [comment]
Let me know if this helps?

**Comment by chris-asl** [comment]
@FroMage @geoand I can confirm this works just fine! Thank you very much for the prompt reply! :smile:

**Comment by el10686** [comment]
closing as it's resolved in referenced PR
