### ISSUE TITLE
Quarkus Tools IntelliJ plugin changes the maven dependencies

### ISSUE THREAD

**Issue by bkzoller** [quarkusio/quarkus#15868]
## Describe the bug
When building a Quarkus project on the command line, maven uses commons-io version 2.8.0 from the pom.xml. However, when I run the unit tests in IntelliJ 2020.3.3, there is an external library named "Quarkus (deployment)" shown in the IDE, which uses commons-io version 2.5.

This difference in commons-io dependencies can result in unit tests which pass on the command line maven, but which fail to compile in IntelliJ. For example, in one Quarkus project I'm using IOUtils.resourceToString, which was introduced in commons-io 2.6 and cannot be resolved in commons-io 2.5.

This happens when importing a Quarkus project with the enabled plugin Quarkus Tools from RedHat (version 1.4.0.121 in this case). It does not happen with the Quarkus plugin from JetBrains enabled, and the Quarkus Tools from RedHat disabled.

### Expected behavior
IntelliJ should use the classpath defined in the pom.xml, instead of overriding with a different set of dependencies provided from a plugin.

### Actual behavior
IntelliJ imports Quarkus project with older versions of commons-io 2.5 and jackson 2.11.

## To Reproduce

1. Install IntelliJ 2020.3.3 (Ultimate Edition)
2. Install Quarkus Tools from RedHat (versions 1.4.0.121 up to 1.9.0.185)
3. Import [hibernate-orm-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-quickstart)
4. Find External Libraries -> Quarkus (deployment) containing the older dependencies for commons-io 2.5 and jackson-* 2.11

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
[External Libraries screenshot](https://quarkusio.zulipchat.com/user_uploads/11321/qZK5qyHnORr6rwyhXcNb1uEZ/Screen-Shot-2021-03-18-at-3.39.21-PM.png)

### Output of `uname -a` or `ver`
Darwin Brians-MBP.fios-router.home 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 20.3.1 (build 11.0.10+8-jvmci-20.3-b09)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.1 (build 11.0.10+8-jvmci-20.3-b09, mixed mode, sharing)

### Quarkus version or git rev
1.12.2.Final
2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/bzoller/tools/apache-maven-3.6.3
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

## Additional context
(Add any other context about the problem here.)

**Comment by maxandersen** [comment]
@jeffmaury something you can explain why intellij plugin messes with users dependencies ?

**Comment by jeffmaury** [comment]
This quarkus deployment library is added for Quarkus project in order to add Quarkus deployment JARs to the project classpath so that quarkus properties are discovered. It should have a specific scope that should not impact executions but that needs to be rechecked

**Comment by bkzoller** [comment]
@jeffmaury When the module "Quarkus (deployment) - scope: Provided" appears at the end of the list of modules in Project Settings -> Modules, then it does not interfere with the dependencies. However, when it appears at the top of that list of modules, then it does interfere and cause compilation errors.

It may be related to timing of loading the dependencies during project import, because I have encountered both orderings.

**Comment by bkzoller** [comment]
@jeffmaury @maxandersen This bug is still happening almost one year later after many new versions of Quarkus and Quarkus Tools. It's still failing on Quarkus 2.7.1.Final, Quarkus Tools 1.9.0.185 and IntelliJ IDEA Ultimate 2021.3.2. The plugin is still adding same old dependency versions of commons-io-2.5 and jackson 2.11 to the project dependencies, which are older versions than Quarkus itself uses. This prevents running the Quarkus Tools plugin in projects where these old dependencies cause conflicts with the project code.

**Comment by jeffmaury** [comment]
Moved to https://github.com/redhat-developer/intellij-quarkus/issues/505

**Comment by geoand** [comment]
Closing as this has likely been fixed
