### ISSUE TITLE
getDeferredIdentity

### ISSUE THREAD

**Issue by ghost** [quarkusio/quarkus#15863]
In resteasy reactive when quarkus.http.auth.proactive set to false methods annotated with security annotations throw exception if the "@Blocking" annotation is not used. If it is ok please add something to your documentation because interrelation between this features is not evident to newbies. Thank you.

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by sberyozkin** [comment]
@hogmuzzle80 Hi,
It has been documented here for a while: https://quarkus.io/guides/security-built-in-authentication#proactive-authentication

It says it is a blocking operation - I'll add a note about `@Blocking`

**Comment by sberyozkin** [comment]
Hmm, no, that doc is different

**Comment by geoand** [comment]
@sberyozkin should this be closed?

**Comment by michalvavrik** [comment]
It's documented very well now here https://quarkus.io/guides/security-built-in-authentication-support-concept#proactive-authentication, also it is not true for resource methods anymore (endpoints). You can only experience it over CDI beans as mentioned in linked docs.
