### ISSUE TITLE
Bump smallrye-graphql to 1.0.25

### ISSUE THREAD

**Issue by fabasoad** [quarkusio/quarkus#15873]
## Description

There is a https://github.com/smallrye/smallrye-graphql/pull/689 fix in smallrye-graphql 1.0.25 that allows users to use `Instant` type in GraphQL. This bug blocks us for bumping Quarkus to the 12.0.x version.

Current smallrye-graphql version:
https://github.com/quarkusio/quarkus/blob/6ca52ee869d70b45ceefa1784268736336aecfee/bom/application/pom.xml#L47

**Comment by shinji62** [comment]
Will be nice, we hit the same issue in our team as well !

**Comment by phillip-kruger** [comment]
We are fixing one more thing in SmallRye, then we will do a release and pull it into Quarkus

**Comment by phillip-kruger** [comment]
cc @jmartisk

**Comment by phillip-kruger** [comment]
thanks @gsmet !
