### ISSUE TITLE
Dev mode inside a container

### ISSUE THREAD

**Issue by Teg79** [quarkusio/quarkus#15877]
## Describe the bug
When running the `./mvnw compile quarkus:dev` command inside a container the server starts without error but every http request is dropped without any response or error in the logs.

### Expected behavior
The server must respond to http connections.

### Actual behavior
Start the server inside a container produces this log:
```
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /deployments/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.2.Final:dev (default-cli) @ code-with-quarkus ---
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-03-18 15:14:16,856 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.12.2.Final) started in 2.043s. Listening on: http://localhost:8080
2021-03-18 15:14:16,879 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-03-18 15:14:16,879 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy]
```
From inside the container the `curl http://localhost:8080/` retrieves the default index.html correctly

From outside the container the same command (on the mapped port) gets:
`curl: (56) Recv failure: Connection reset by peer`

The same message is for any url you can try, existing or not.

## To Reproduce
1. Generate a blank project from `code.quakus.io` with only the `RESTEasy JAX-RS` extension
2. Execute `docker run --rm -v $PWD:/workspace -w /workspace -p 8080:8080 maven:3.6-openjdk-11 ./mvnw compile quarkus:dev`
3. Test `curl http://localhost:8080/`
 

### Output of `uname -a` or `ver`
Linux qm-dev-rd 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Oracle Corporation, runtime: /usr/local/openjdk-11
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1127.8.2.el7.x86_64", arch: "amd64", family: "unix"

## Additional context
It worked until version 1.7.2.Final, we bumped to 1.11.2.Final and got the error, bumped to 1.12.2.Final and the error persists
This is blocking for us to adopt the last version of Quarkus

**Comment by Teg79** [comment]
The last version working is the 1.9.2.Final

**Comment by geoand** [comment]
This happens because Quarkus in dev mode only listens on `localhost` (this is done in order to prevent unauthorized access to the developers machine).

To change this, all you need to do is add `-Dquarkus.http.host=0.0.0.0` to your dev-mode invocation.
