### ISSUE TITLE
.env file for quarkus properties setup is not recognized

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#15885]
## Describe the bug
According to the https://quarkus.io/guides/config quarkus should support reading properties values from .env file located in the root directory of the quarkus project.

However it doesn't and throws `javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting.name`

Reproducer attached.

### Expected behavior
Quarkus recognize .env file + prioritize it if multiple property sources are present

### Actual behavior
Error is thrown when trying to read property from .env file
javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting.name

## To Reproduce
Archive attached 
[getting-sstarted.zip](https://github.com/quarkusio/quarkus/files/6170983/getting-sstarted.zip)

1. cd getting-sstarted
2. mvn clean quarkus:dev
3. ---> See the error message

**Comment by famod** [comment]
FTR: Quarkus version is 1.11.6.Final

@kshpak 
Can you try
```
GREETING_NAME=kirill
```
instead of
```
greeting.name=kirill
```
?

See also https://quarkus.io/guides/config-reference#env_file (which is (indirectly) linked from the article you mentioned)

**Comment by famod** [comment]
Nevermind, tried it myself. `GREETING_NAME=kirill` works, as documented.
