### ISSUE TITLE
CDI events qualifiers not working when abstract superclass is in a library

### ISSUE THREAD

**Issue by MarcoMartins86** [quarkusio/quarkus#15886]
## Describe the bug
CDI events qualifiers are not working well when abstract superclass is in a library since when implementing the class it will be registered as a general observer instead of one with a qualifier.
Check https://github.com/MarcoMartins86/event_qualifier_issue for more details.

### Expected behavior
If I trigger an important event `http://localhost:8080/Events/Important` should appear:
```text
Library AbstractObserverImportantEvent: Important event message 0 Event qualifiers[[@org.acme.ImportantEvent(), @javax.enterprise.inject.Any()]]
Runner ImportantEventImpl: Important event message 0
```

### Actual behavior
If I trigger an important event `http://localhost:8080/Events/Important` appears:
```text
Library AbstractObserverNormalEvent: Important event message 0 Event qualifiers[[@org.acme.ImportantEvent(), @javax.enterprise.inject.Any()]]
Runner NormalEventImpl: Important event message 0
Library AbstractObserverImportantEvent: Important event message 0 Event qualifiers[[@org.acme.ImportantEvent(), @javax.enterprise.inject.Any()]]
Runner ImportantEventImpl: Important event message 0
```

## To Reproduce
A project that reproduces this https://github.com/MarcoMartins86/event_qualifier_issue

1. make
2. Do GET to http://localhost:8080/Events/Important
3. Check the command line for the prints

### Output of `uname -a` or `ver`
Darwin PT-320323-MBP16 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

### Output of `java -version`
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home
Default locale: en_PT, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by mkouba** [comment]
@MarcoMartins86 the `qualifier_issue_lib` is probably not indexed and the `NormalEvent` qualifier is not discovered. Could you try to add an empty `src/main/resources/META-INF/beans.xml` file in the lib project?

See also https://quarkus.io/guides/cdi-reference#bean_discovery for more info about Quarkus bean discovery.

**Comment by MarcoMartins86** [comment]
Thank you for the suggestion but it did not work. Also, reading the page you mentioned, in the underlined text, if I understand correctly observers should be discovered automatically. 

> Bean classes that don’t have a bean defining annotation are not discovered. This behavior is defined by CDI. But producer methods and fields <ins>and observer methods are discovered even if the declaring class is not annotated with a bean defining annotation (this behavior is different to what is defined in CDI)</ins>. In fact, the declaring bean classes are considered annotated with @Dependent.

**Comment by mkouba** [comment]
> Thank you for the suggestion but it did not work. Also, reading the page you mentioned, in the underlined text, if I understand correctly observers should be discovered automatically.
> 

Yes, but the bean classes, qualifiers, etc. must be indexed by Quarkus first. I'll take a look at the reproducer.

**Comment by MarcoMartins86** [comment]
I think I was doing that already by having this on the pom.xml. Thank you again for your time.

```xml
      <plugin>
        <groupId>org.jboss.jandex</groupId>
        <artifactId>jandex-maven-plugin</artifactId>
        <version>${jandex-plugin.version}</version>
        <executions>
          <execution>
            <id>make-index</id>
            <goals>
              <goal>jandex</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**Comment by mkouba** [comment]
I can confirm that it's a bug. 

The Jandex `MethodParameterInfo` does not implement `equals()/hashCode()` and for some reason we receive two distinct target instances for the `@Observes` and `@NormalEvent` annotations declared on the event param of `AbstractObserverNormalEvent.observer()`.

I'll prepare a fix next Monday.

**Comment by mkouba** [comment]
@MarcoMartins86 FYI the problem only occurs if an observer method is declared on a class located in an archive with a pregenerated Jandex index (e.g. via the jandex-maven-plugin).
