### ISSUE TITLE
Grpc Web support

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#15883]
First make it work with Envoy proxy, then implement proxy in Quarkus

**Comment by michalszynkiewicz** [comment]
I create an example project that demonstrates using gRPC Web with Quarkus (with Envoy): https://github.com/michalszynkiewicz/quarkus-grpc-web

**Comment by cescoffier** [comment]
Awesome! Deserve a blog post :-D

**Comment by cescoffier** [comment]
@michalszynkiewicz should we close this one as it's likely never going to be done?

**Comment by cescoffier** [comment]
Marking it as won't fix (at least for now).
