### ISSUE TITLE
hibernate.temp.use_jdbc_metadata_defaults=false setting is ignored in persistence.xml

### ISSUE THREAD

**Issue by tttomat19** [quarkusio/quarkus#15888]
## Describe the bug
1. Use quarkus-hibernate-orm extension
2. Use dedicated META-INF/persistence.xml for configuration
3. set hibernate.temp.use_jdbc_metadata_defaults=false in persistence.xml
4. the setting is ignored during startup

### Expected behavior
hibernate.temp.use_jdbc_metadata_defaults setting should actually take effect.

### Actual behavior
hibernate.temp.use_jdbc_metadata_defaults=false is ignored during application deployment

## To Reproduce

link to reproducer: https://github.com/tttomat19/quarkus-quickstarts

1. get https://github.com/tttomat19/quarkus-quickstarts
2. use modified hibernate-orm-quickstart (the only difference is persistence.xml)
3. run with ./mvnw quarkus:dev -Dsuspend=y 
4. see in debugger that quarkus goes through JdbcEnvirtonmentInitiator twice. The second time it ignores the setting.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
 ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context

The problem is with this line in quarkus-hibernate-orm extension:
file: FastBootHibernatePersistenceProvider.java
runtimeSettingsBuilder.put("hibernate.temp.use_jdbc_metadata_defaults", "true");
it just overrides whatever is set in persistence.xml

And my actual problem is that I hit the edge case: my database has literally 10000 tables, the metadata scan is slow, and overall startup is slow. I try to disable the metadata scan. But.

**Comment by Sanne** [comment]
Interesting, thanks for the reproducer.

Please note we need this disabled to be able to compile to native - also it's an undocumented property, I was not expecting end users to set it.

But I agree it should either be possible to disable it explicitly, or we need to ensure it's consistently disabled.

**Comment by tttomat19** [comment]
Thanks for feedback.

So I made a fix. It really works for me. Overall startup time improved by 18 seconds (from 25 down to 7 seconds).

tbh I do not fully understand the native part. Does it require a lot of testing?

Hibernate code itself obviously should not break while using this property. But can it break some quarkus internals?

**Comment by Sanne** [comment]
Nice, thanks.

For the native aspects, yes it typically requires a lot of testing but I don't think it's the case here: if you had it wrong it would fail on any of the existing tests.

If you could send a pull request with your patch and ideally include an integration test we'll be happy to review; sending a PR will also trigger CI to run all native tests: so don't worry about it, if it breaks we'll know and we can iterate.

**Comment by juliaaano** [comment]
This also may be fixed by #17509

**Comment by Sanne** [comment]
Closing this as we provided a better fix as discussed in https://github.com/quarkusio/quarkus/issues/16927#issuecomment-858958729
