### ISSUE TITLE
Quartz extension - graceful shutdown for @Scheduled does not work

### ISSUE THREAD

**Issue by arvidvillen** [quarkusio/quarkus#15908]
Allow users to set the `quarkus.shutdown.timeout` (or a separate property) to configure graceful shutdown for `@Scheduled`.
A typical use case is that the application interacts with a message queue in a scheduled method. When upgrading/releasing a new version of the app the user wants the service to ignore incoming messages (i.e., not run any new scheduled jobs) but finish the currently running job(s).

**Comment by mkouba** [comment]
I've just verified that the graceful shutdown works for simple scheduler (except the shutdown timeout is not interpreted correctly, but that's a different bug in the`io.quarkus.runtime.ExecutorRecorder`). However, we need to implement this for quartz extension because it does not reuse the default quarkus blocking executor.

**Comment by mkouba** [comment]
Unfortunately, it seems that we will be able to enable the graceful shutdown for quartz but we will not be able to honor the timeout property (there is no quartz config option to specify the timeout and `org.quartz.Scheduler.shutdown(boolean)` just blocks until all running tasks are completed). In fact, this should have worked already but there's a missing `@Observes` on this line: https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L284

**Comment by machi1990** [comment]
> Unfortunately, it seems that we will be able to enable the graceful shutdown for quartz but we will not be able to honor the timeout property (there is no quartz config option to specify the timeout and `org.quartz.Scheduler.shutdown(boolean)` just blocks until all running tasks are completed). In fact, this should have worked already but there's a missing `@Observes` on this line: https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L284

Good catch.

**Comment by gsmet** [comment]
Should we throw a build error in this case? Or automatically consider the annotation is here (but I'm not sure of the consequences)?

**Comment by mkouba** [comment]
> Should we throw a build error in this case? 

I don't think we should do this. We could detect a param with a qualifier that is not declared on a producer method or an initializer method but since it's legal to use a qualifier annotation for other non-CDI stuff. 

> Or automatically consider the annotation is here (but I'm not sure of the consequences)?

-1
