### ISSUE TITLE
AWS Lambda HTTP Content-Type is lost

### ISSUE THREAD

**Issue by richiethom** [quarkusio/quarkus#15909]
## Describe the bug
Quarkus RestEasy AWS Lambda's Content-Types don't get returned by AWS API Gateway.

### Expected behavior
The content type returned by the API Gateway is the one set by RESTEasy (ie 'application/json' unless set otherwise via @Produces)

### Actual behavior
The content type is `text/plain`.

## To Reproduce

1. Generate the Amazon Lambda HTTP example at https://quarkus.io/guides/amazon-lambda-http
2. Delete the `GreetingVertx`, `GreetingFunction` and `GreetingServlet` classes, and modify the pom accordingly to remove the corrresponding dependencies
3. Modify `GreetingResource`. Change the `@Produces` annotation to `APPLICATION_JSON` (RestEasy defaults to `application/json` but at least like that it is explicit) and modify the returned String to be a valid piece of JSON
4. Build the native Lambda: `mvn clean install -DskipTests=true -Pnative -Dnative-image.docker-build=true`
5. Upload it to AWS: `aws lambda create-function --function-name mynativefunction --zip-file fileb://target/function.zip --handler not.used.in.provided.runtimei --runtime provided --role arn:aws:iam::1234567890123:role/MyAppropriateRole`
6. Create an API on the API Gateway:
  6.1. Create a new HTTP API
  6.2. Choose the lambda integration uploaded in 5
  6.3. Configure a `GET /hello` route
  6.4. Configure the `$default` stage and create the API
7. Copy the Invoke URL and invoke it: `wget -S https://abcdef.execute-api.zone.amazonaws.com/hello`

Inspect the content-type returned by the invocation - it is `text/plain` despite the content type being `application/json` in the `GreetingResource` class.

### Configuration
NA

### Screenshots
NA

### Output of `uname -a` or `ver`
`Linux DESKTOP-GJJ95MV 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)
NA

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/rich/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /home/rich/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.104-microsoft-standard", arch: "amd64", family: "unix"
```

## Additional context
I have managed to fix this locally by adding the following hacky code to the `msg instanceof HttpResponse` clause of the `LambdaHttpHandler` class. I will try to get a pull request done soon.

```java
final List<Entry<String, String>> entries = res.headers().entries();
final Map<String, String> responseHeaders = new HashMap<>();
for (final Iterator<Entry<String, String>> i = entries.iterator(); i.hasNext();) {
	final Entry<String, String> e = i.next();
	log.info(e.getKey() + " : " + e.getValue());
	responseHeaders.put(e.getKey(), e.getValue());
}
responseBuilder.setHeaders(responseHeaders);
```

**Comment by richiethom** [comment]
@patriot1burke @gsmet any chance this can be put into a hypothetical 1.13.2.Final release? From what I've been reading a 1.14 release is unlikely, and it'd be a shame to have to wait for v2 for such a small code change. Without it it's not really possible to use Quarkus on AWS's newer (cheaper) gateway, at least not for an API where the content-type is important!

Thanks again!

**Comment by geoand** [comment]
It does look innocent enough to backport but I would like @patriot1burke to weigh in
