### ISSUE TITLE
Reactive panache nested transaction error

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#15918]
## Describe the bug
As of today, reactive panache nested transactions always trigger exception.

### Expected behavior
When in a nested transaction panache should  : 
* Minimal : Give an understandable error
* Better : Have a default behaviour like "start or join existing"
* Best : Offer control to the developper to choose between "required-existing" and "sub-transaction"
### Actual behavior
Triggers a `java.lang.IllegalStateException` because `io.vertx.sqlclient.impl.SqlConnectionImpl` (line 109)

## To Reproduce

Reproducer can be found on https://github.com/jtama/quarkus-rent/tree/nested-transaction.

1. Run postgresql containeur (docker compose file available
2. Run application
3. `curl -v -X POST "http://localhost:8080/api/hostels" -H "X-user-name: Joe" -H "X-user-roles: USER,ADMIN" -H "Content-Type: application/json" -d "{ \"id\": 0, \"name\": \"Ritz\"}"`

### Apache Maven 3.6.3

**Comment by jtama** [comment]
Happy to help on this.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by jtama** [comment]
I have to say I have absolutly no idea.

**Comment by geoand** [comment]
Let's close for now and if we find it's still an issue, we can reopen

**Comment by jtama** [comment]
Absolutely, If I was the only one to report in 4 years...
