### ISSUE TITLE
Grpc is giving a connection refuse on upstream

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15934]
## Describe the bug

On main branch we are getting the following error (GRPC):

```
Resulted in: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9000
Resulted in: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
```

Reproducer: [Quarkus-quickstarts/grpc-plain-text-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/grpc-plain-text-quickstart) or [beefy-scenarios](https://github.com/quarkus-qe/beefy-scenarios/tree/main/009-quarkus-infinispan-grpc-kafka) pointing to main branch `999-SNAPSHOT`

Works on 1.12.2

**Comment by stuartwdouglas** [comment]
Quickstarts fix is here:  https://github.com/quarkusio/quarkus-quickstarts/pull/820

Basically we changed the test port from 9000 to 9001 so it does not conflict with a running app.

**Comment by pjgg** [comment]
Do you think that make sense create a new property called: `quarkus.grpc.clients.<service_name>.test-port` as `quarkus.http.test-port`

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/blob/0a42b6c35c1e37a34e97f8b4f94407a5bef7e193/extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/config/GrpcServerConfiguration.java#L24

The issue is the client, generally apps won't be connecting back to themselves, so I don't think it makes sense to change the client to default to 9001 in test mode.

**Comment by pjgg** [comment]
Thank you!, 

So on test mode, the Grpc server port has been changed to `9001` so If we are running some test against our local environment we should add `%test.quarkus.grpc.clients.hello.port=9001` to our `application.properties`
