### ISSUE TITLE
Configuration error after running application on Proguard: Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus

### ISSUE THREAD

**Issue by atrosin** [quarkusio/quarkus#15937]
After running proguard on my application
(Proguard config file attached below)
and running output.jar with java -jar output.jar command I getting an error you see below

I have tried to insert some values(initial-size=0,isolation-level=none) for these properties in application.properties file, but the error appears with another configuration options and the error value is always "5M".

### Expected behavior
Working obfuscated project

### Actual behavior
I get an error:

Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:301)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting. The errors are:
An invalid value was given for configuration key "quarkus.datasource.initial-size": For input string: "5M"
An invalid value was given for configuration key "quarkus.datasource.transaction-isolation-level": Cannot convert 5M to enum class io.agroal.api.configuration.AgroalConnectionFactoryConfiguration$TransactionIsolation

### Configuration
```properties
sounds.directory=/app/asterisk16/var/lib/asterisk/sounds/
thread.pool.size=100
quarkus.http.port=8080
quarkus.banner.path=art

quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
quarkus.datasource.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.url=jdbc:mysql://127.0.0.1:3306/andrei
quarkus.datasource.username=xxx
quarkus.datasource.password=xxx
#quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.generation=create
quarkus.datasource.max-size=50

quarkus.log.category."com.unifun.voice".level=DEBUG
quarkus.log.console.enable=true
quarkus.log.file.enable=false
quarkus.log.file.level=INFO
quarkus.log.file.path=/var/log/wrongivr/wrongivr.log
quarkus.log.file.format=%d{MMM d HH:mm:ss} %-5p [%F:%L] %s%e%n
quarkus.log.file.rotation.max-file-size=100m
quarkus.log.file.rotation.max-backup-index=3
```

### Output of `java -version`
AdoptOpenJDK (build 11.0.10+9)

### Quarkus version 
1.8.3.Final

### Build tool 
Apache Maven 3.6.3

## Additional context
-injars wrongivr-1.0.0-SNAPSHOT-runner.jar
-outjars wrongivr-1.0.0-SNAPSHOT-runner-out.jar

-libraryjars 'C:\Users\a.trosinenco\.jdks\adopt-openjdk-11.0.10'
-libraryjars 'C:\Users\a.trosinenco\IdeaProjects\wrongivr\mvn_repo\ch\loway\oss\ari4java\ari4java'
-libraryjars 'C:\Users\a.trosinenco\IdeaProjects\wrongivr\target\lib'

-dontskipnonpubliclibraryclassmembers
-dontshrink
-dontoptimize
-dontusemixedcaseclassnames
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,Synthetic,EnclosingMethod,MethodParameters,LocalVariable*Table
-dontwarn com.unifun.voice.endpoints.CampaignEndpoint_Subclass,com.unifun.voice.services.SubscribersListUploader_Subclass,com.unifun.voice.endpoints.StatisticEndpoint_Subclass

-keepclassmembers class **.EntitySuperclass {
    <fields>;
	<methods>;
}
-keepclassmembers class **.EntitySuperclassIdOnly {
    <fields>;
	<methods>;
}
-keepclassmembers class **.TemplateAudio,**.TemplateSmsText{
   *** group;
}

-keepclassmembers class **.IvrMenuItem{
   *** ivrMenu;
}

-keepclassmembers @javax.persistence.Table class * {
	@javax.persistence.Column java.lang.String msisdn;
}
-keepclassmembers class * {
    !private org.slf4j.Logger *;
}
-keepclassmembers class * {
    @org.eclipse.microprofile.config.inject.ConfigProperty
    <fields>;
}
-keepclassmembers class * {
    @javax.transaction.Transactional
    private <methods>;
}
-keepclasseswithmembers public class * {
    public static void main(java.lang.String[]);
}
-keep public class * {
    public protected <fields>;
    public protected <methods>;
}
-keepclasseswithmembers,includedescriptorclasses,allowshrinking class * {
    native <methods>;
}

**Comment by aadityasinha-dotcom** [comment]
Hey, can I work on this issue?

**Comment by mkouba** [comment]
A simple reproducer project (ideally Maven) that demonstrates the problem would be helpful.

**Comment by geoand** [comment]
Closing as we never got a reproducer
