### ISSUE TITLE
MongoDB Health Check may be waiting forever

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15945]
## Describe the bug

The MongoDB Health checks are waiting forever (30s as that's the default Mongo timeout) if the MongoDB server does not reply.

### Expected behavior

The health check endpoint should reply in a timely fashion.

### Actual behavior

Wait 30s, actually wait 30s per client when the brokers are not available.

## To Reproduce

Here is a google drive link with a reproducer:
https://drive.google.com/file/d/1Gd2MPBqqjj2L0yywzGsqECKs5kNiXVpb/view?usp=sharing

- Run the application in dev mode
- Visit locahost:8080/q/health

The endpoint will hang, it will never respond. This is especially concerning in cases where the health endpoints are used to determine the health of the pod.

**Comment by cescoffier** [comment]
@loicmathieu I wonder about the current check strategy. It does a query against the "admin" database, which may not be accessible to the user. 

After a bit of research (basically stackoverflow :-)), I've found another strategy that would just list the databases. Should be switched? 

an alternative would be to allow the user to configure the database to query (and fallback to admin). 

WDYT?

**Comment by loicmathieu** [comment]
I remember that the first implementation was to list databases and we switch to do a query to the admin database, I'll need to check why.

There is also the issue that when using MongoDB with Panache we setup both the sync and reactive client even if the user only use one of the two. So the health check would be done on both client.

**Comment by loicmathieu** [comment]
Now I remember why we do this, the ping command is lightweigth and made for this purpose, a health check of the connection.
Some MongoDB user may not be able to list the databases that's wy it's better than list database.

Now, if the admin database is not accessible to the user, maybe we need to use a different one, there is an authSource from the credential config, or the `database` property (used for auth or by Panache). Anyway, the user can still configure a database or an authSource from the MongoDB connection URI so it may be hard to select which database to use.

Maybe we can add an optional health-database property for this, with fallback to admin.

**Comment by loicmathieu** [comment]
By the way, there is also the issue that both sync and reactive client are available anytime with Panache even if we only use one of the two. This is a known issue that can significantly add some latency to the health check.

**Comment by cescoffier** [comment]
@loicmathieu the latency comes from how the check is implemented today. I will try to find a moment today or tomorrow (likely tomorrow) to use concurrent calls. 

+1 about the ability to set the database.
