### ISSUE TITLE
OpenShift: We can't provide Java arguments

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15943]
## Describe the bug
Before [this PR](https://github.com/quarkusio/quarkus/pull/15670) was merged, we could add Java arguments via the jvmArgs properties (which was wrong and fixed as part of this PR). However, now we don't have any properties or way to add real Java arguments.

As an example, the args section in the YAML look like:

```
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
```

And what we can't achieve is to add Java arguments:

```
args:
    - '-Dquarkus.http.host=0.0.0.0'
    - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
    - '-jar'
    - /deployments/quarkus-run.jar
    - ARG1
    - ARG2
```

I tried to use the property `quarkus.openshift.arguments` but it's replacing all the args section as:

```
args:
    - ARG1
    - ARG2
```

I think this issue is also relevant for Kubernetes and S2I.

**Comment by iocanel** [comment]
@Sgitario: I feel that the expectation is a little bit off.
The property `quarkus.openshift.arguments` was never meant to append, but replace the arguments.

From my POV this is the only way we can provide full customizability and I wouldn't want to change it, as it would be really limiting for other use cases.

Something that would possibly address your needs is introducing an additional property that would be used for appending, but I am a little bit sceptic about introducing multiple properties for similar things.

@geoand: Thoughts?

**Comment by Sgitario** [comment]
Sure, I never meant to change the behaviour of the `quarkus.openshift.arguments`. However, having a new property would potentially help users that require to provide additional arguments. 
Being said that, I don't have a strong need of having this feature.

**Comment by geoand** [comment]
👍

Let's keep this open as an enhancement request

**Comment by iocanel** [comment]
A use case that was brought to my attention and slightly changed my perspective on this, is when an application is in need of arguments (e.g. a picoli app). Again, not the most common use case, but there is a clear distinction between kubernetes cmd/args and application args and that makes me less reluctant.

**Comment by geoand** [comment]
For a picocli style application to be useful, we would likely want to support Kubernetes Job or CronJob in addition to this

**Comment by maxandersen** [comment]
I think a "appargs" or similar property makes sense to add; but yes - don't see this as being openshift specific. Should be generally possible for wherever we configure the java/app launch for native and jvmmode.
