### ISSUE TITLE
Propose a parent pom for external extensions

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#1594]
Currently, the extensions are embedded into the main Quarkus repository thus use the internal `build-parent` pom.xml.
To permits 3rd parties to develop their own extensions, it would be great to propose a public `quarkus-extension-parent` pom.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Extensions/near/161188290

**Comment by ppalaga** [comment]
I proposed a basic parent for third party extensions in https://github.com/quarkusio/quarkus/pull/3427 the commit: https://github.com/ppalaga/quarkus/commit/512022706309a0de6925c9a9ef5fd10a067e8ae9

However, when we start refactoring the hierarchy, @aloubyansky would like to solve more than this single problem https://github.com/quarkusio/quarkus/pull/3427#issuecomment-518580389

> This is basically the same approach I was investigating. I was just thinking it could be organized slightly differently, e.g.
> 
> ```
> build-parent/
> |- application/
> |  `- pom.xml (parent for apps built on Quarkus core, flattened)
> |- extension/
> |  `- pom.xml (parent for extensions built on Quarkus core, probably has application/pom.xml as its parent, flattened)
> `- internal/
>    `- pom.xml (Quarkus core build parent pom, has extension/pom.xml as its parent).
> ```
> 
> However, before actually applying this kind of change, it'd be a good idea to announce/discuss it on the dev list.

**Comment by danielpetisme** [comment]
Fixed by https://github.com/quarkusio/quarkus-platform fix
