### ISSUE TITLE
Regression issue: Exception when using OpenShift/Kubernetes extensions and having an external Ansi dependency

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15953]
## Describe the bug
We are getting an exception when using the OpenShift/Kubernetes extensions and having a third party dependency like:

```xml
<dependency>
          <groupId>org.fusesource.jansi</groupId>
          <artifactId>jansi</artifactId>
          <version>2.3.2</version>
</dependency>
```

When we build our application, it fails with:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project openshift-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.IllegalStateException: AnsiLogger requires a PrintStream instance.
[ERROR] 	at io.dekorate.logger.AnsiLogger.check(AnsiLogger.java:82)
[ERROR] 	at io.dekorate.logger.AnsiLogger.info(AnsiLogger.java:59)
[ERROR] 	at io.dekorate.processor.SimpleFileReader.read(SimpleFileReader.java:51)
[ERROR] 	at io.dekorate.Session.lambda$readExistingResources$6(Session.java:291)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.dekorate.Session.readExistingResources(Session.java:291)
[ERROR] 	at io.dekorate.Session.generate(Session.java:281)
[ERROR] 	at io.dekorate.Session.close(Session.java:248)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$4(KubernetesProcessor.java:168)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:122)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

This is a regression issue caused by [this change](https://github.com/quarkusio/quarkus/commit/e7acfd4a687e75aaab37f6c0778b678a0ae2a629).

### Expected behavior
The application should work as before [this change](https://github.com/quarkusio/quarkus/commit/e7acfd4a687e75aaab37f6c0778b678a0ae2a629).

## To Reproduce

1. Create a Quarkus application using:

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create     -DprojectGroupId=org.acme     -DprojectArtifactId=openshift-quickstart     -DclassName="org.acme.rest.GreetingResource"     -Dpath="/greeting" 
```

2. Add an ansi dependency like:

```
<dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
             <version>2.3.2</version>
        </dependency>
```

## Additional context
The issue is that the AnsiLogger gets used instead of NoopLogger. But AnsiLogger is not initialized.

**Comment by iocanel** [comment]
I agree! The `NullLogger` should be used instead. This will probably need to be addressed on the dekorate side.

**Comment by Sgitario** [comment]
> /cc @iocanel

If you know any workaround, please let me know. This is a blocker for building our test suite against main atm :(

**Comment by Sgitario** [comment]
Any updates about this issue? I could not find any workaround in our side yet as it seems that it's also picking AnsiLogger when: https://github.com/dekorateio/dekorate/blob/7d9a96f0ba3c07983ed89db81b3c84dddfa63433/core/src/main/java/io/dekorate/LoggerFactory.java#L49

I could make it worked when setting `LoggerFactory.setLogger(new NoopLogger());` at the beginning of the KubernetesProcessor.build method. Not saying this is the proper solution, but it needs to be addressed though. 

Moreover, we raised another issue related to the same changes: https://github.com/quarkusio/quarkus/issues/16089

cc @geoand @gsmet

**Comment by geoand** [comment]
@iocanel are you looking at this?
Is there some quick fix we can do in Quarkys?

**Comment by iocanel** [comment]
@geoand @Sgitario: I haven't had the time to look at it and I won't manage to look at it before Thursday.

But, here are some thoughts for everyone that wants to go for a fix.
The extension is meant to be using the `NoopLogger` this was either broken in one of the recent refactorings, or the changes in dekorate 2.x no longer respect the set logger (the former seems more likely).

AFAIR, we were setting the `NoopLogger` just when we created the `Session` through the `Session`. If the code is removed, we should bring it back, if it no longer works, then `LoggerFactory.setLogger(new NoopLogger())` is not a bad idea.

**Comment by geoand** [comment]
We already seem to have https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java#L135.

Furthermore it doesn't seem like we can access Dekorate's logger any other way.

**Comment by Sgitario** [comment]
> We already seem to have https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java#L135.
> 
> Furthermore it doesn't seem like we can access Dekorate's logger any other way.

Any updates about this issue? 

Otherwise, are you ok if we fix it by: 
"I could make it worked when setting LoggerFactory.setLogger(new NoopLogger()); at the beginning of the KubernetesProcessor.build method." ? 

cc  @iocanel @geoand

**Comment by geoand** [comment]
This one is really for @iocanel to decide

**Comment by rsvoboda** [comment]
This is blocking us with https://github.com/quarkus-qe/quarkus-openshift-test-suite move to Quarkus 2.0.0 Alpha releases.

**Comment by geoand** [comment]
@iocanel what do you want to do about this one?

**Comment by pjgg** [comment]
@geoand there is a new Dekorate minor release that include a patch for this issue:

https://github.com/dekorateio/dekorate/releases/tag/2.1.4

Could we upgrade Quarkus Upstream in order to include this lib version?

**Comment by geoand** [comment]
@pjgg can you first respond to https://github.com/dekorateio/dekorate/pull/753#issuecomment-838036419 so we can be sure things are fixed?

**Comment by iocanel** [comment]
> @pjgg can you first respond to [dekorateio/dekorate#753 (comment)](https://github.com/dekorateio/dekorate/pull/753#issuecomment-838036419) so we can be sure things are fixed?

He responded via google chat. We are good to go!

**Comment by geoand** [comment]
Cool!

In the future, it would be great to record such outcomes on the issue for posterity :)

**Comment by geoand** [comment]
@iocanel are you planning on opening the PR to bump dekorate?
