### ISSUE TITLE
Misleading Embeddable Configuration Documentation

### ISSUE THREAD

**Issue by Alwaysgone** [quarkusio/quarkus#15981]
When trying to embed a configuration from another module in a Quarkus service I came across [this](https://quarkus.io/guides/config-reference#embedding-a-configuration-file-inside-a-dependency) documentation. In there it says that the properties file for the microprofile config's path should be `META-INF/microprofile.properties`. That does not work and after some digging I found one of your integration tests where those properties are located under `META-INF/microprofile-config.properties` which does work like a charm.
This is just a very minor thing if you can google about microprofile config and check for the correct file name but it would be nice if the documentation could be updated for future Quarkus users.

Thanks in advance and keep up the great work!

**Comment by geoand** [comment]
cc @radcortez
