### ISSUE TITLE
Resteasy Reactive: Enhance support for media types with suffix

### ISSUE THREAD

**Issue by markusdlugi** [quarkusio/quarkus#15982]
## Description

Follow-up to #15042. Media types with suffixes such as `application/hal+json` behave counterintuitively in Resteasy Reactive. For example, a `MessageBodyWriter` for `application/hal+json` is never used, but instead the normal provider for `json` is used since the suffix (`json`) is prioritized over the actual subtype (`hal`).

## Implementation ideas

See discussion in #15042, or more specifically, research regarding spec done by @FroMage: https://github.com/quarkusio/quarkus/issues/15042#issuecomment-780468801

## Reproducer

I have created a small reproducer to demonstrate the current state:

https://github.com/markusdlugi/mediatype-reproducer

The behavior is as follows:

- GET Request to http://localhost:8080/ with `Accept: json` returns `application/json`
  - --> as expected
- GET Request  to http://localhost:8080/ with `Accept: hal` returns `application/hal` and uses `HalProvider`
  - --> as expected
- GET Request  to http://localhost:8080/ with `Accept: hal+json` returns `application/json` and does **not** use `HalJsonProvider`
  - --> **not as expected**

Expected behavior would most likely be that a provider for `hal+json` is used, and if none exists, then it should fallback to using  a provider for `hal`. It should not fallback to `json`, at least not before trying the better fitting alternatives.

**Comment by jhoeflaken** [comment]
Hi,

What is the status of this issue? I am working on a HAPI FHIR extension and running into this problem. My application/fhir+xml and application/fhir+json supporting reader and writer are not called because the media type is converted to application/xml and application/json.

Kind regards,

Jacob

**Comment by jhoeflaken** [comment]
Hi,

Additionally: if I have a produces with "application/fhir+xml" and "application/fhir+json" it will be translated to "application/xml" in the `isWriteable` of the MessageBodyWriter, even if I set "application/fhir+json" in the Accept header (I would have expect "application/json"). This means that I can not have a workaround of registering my customer readers and writers as "application/xml" and "application/json" internally and requiring "application/fhir+xml" or "application/fhir+json" as Content-Type and Accept headers. It will always return the first media type specified in the isWriteable method regardless of what is specified in the Accept header.

`    @GET
    @Path("/metadata")
    @Consumes({"application/fhir+xml", "application/fhir+json"})
    @Produces({"application/fhir+json", "application/fhir+xml"})
    public Uni<CapabilityStatement> capabilities(
            @RestQuery final Optional<String> mode,
            @BeanParam final GeneralQueryParams generalQueryParams) {
        return Uni.createFrom().item(new CapabilityStatement());
    }`

**Comment by geoand** [comment]
Hi,

This slipped between the cracks...
@Sgitario do you want to take a look?
