### ISSUE TITLE
Console leaks startup WARN output even when quarkus.log.console.level=INFO

### ISSUE THREAD

**Issue by phiwu-gpdec** [quarkusio/quarkus#15993]
Quarkus 1.11.6.FINAL

## Describe the bug
```
quarkus:
  log:
    level: DEBUG
    console:
      level: INFO
      format: "[LEVEL: %p] [%c] %s%e%n"
```

### Expected behavior
[LEVEL: INFO] [io.quarkus] MY-APP 1.0.0 on JVM (powered by Quarkus 1.11.6.Final) started in 1.154s. Listening on: http://localhost:8080
[LEVEL: INFO] [io.quarkus] Profile testconfig activated. Live Coding activated.
[LEVEL: INFO] [io.quarkus] Installed features: [cdi, config-yaml, rest-client, resteasy, resteasy-jackson, resteasy-jaxb, smallrye-health, smallrye-openapi, swagger-ui]

### Actual behavior
[LEVEL: WARN] [io.quarkus.restclient.deployment.RestClientProcessor] Unsupported default scope javax.inject.RequestScoped provided for rest client ...
[LEVEL: WARN] [io.quarkus.config] Unrecognized configuration key ...
[LEVEL: WARN] [io.quarkus.config] Unrecognized configuration key ...
[LEVEL: WARN] [io.quarkus.config] Unrecognized configuration key ...
[LEVEL: WARN] [io.quarkus.config] Unrecognized configuration key ...
[LEVEL: INFO] [io.quarkus] MY-APP 1.0.0 on JVM (powered by Quarkus 1.11.6.Final) started in 1.154s. Listening on: http://localhost:8080
[LEVEL: INFO] [io.quarkus] Profile testconfig activated. Live Coding activated.
[LEVEL: INFO] [io.quarkus] Installed features: [cdi, config-yaml, rest-client, resteasy, resteasy-jackson, resteasy-jaxb, smallrye-health, smallrye-openapi, swagger-ui]

### Question
I don't know why this happens, or perhaps I'm doing something wrong? I assume that setting root logger to DEBUG and console logger to INFO that in the console I only see INFO output, or I am wrong with that?

As an expected behavior, I want to see in the console log only INFO output and in the file log the whole DEBUG output.

**Comment by gsmet** [comment]
`WARN` is superior to `INFO` so you will always have the warnings when logging at `INFO` level. Same as you will have the errors.

Question is: why do you have these unrecognized properties? What are they?

**Comment by phiwu-gpdec** [comment]
Ok sorry, this was my fault, I think I misunderstood something.

These unrecognized properties are OpenTracing properties and OpenTracing isn't part of the project. It was only to see some other log messages.
