### ISSUE TITLE
Readiness shows database connection although no database configured

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#15991]
## Describe the bug
There is an entry in my healthcheck that leads to think that there is a database attached to the application when there is none

### Expected behavior
No entry for a database check should appear 

### Actual behavior
Although there is no database configured in my application the Readiness check still returns an UP for a database connection, which leads to confusion. There should be no such entry when there is no database configured.
```
{
    "status": "UP",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "UP"
        },
        {
            "name": "covid-pass-check (20210324_131720) : Readiness check",
            "status": "UP"
        }
    ]
}
```

## To Reproduce
1. Create a sample projet 
2. Add classes for liveness and readiness check
3. add the Panache and MySQL dependencies in the pom.xml
4. call the readiness URL

### Configuration
```properties
quarkus.application.name=covid-epass-check
quarkus.application.version=version_tag

quarkus.banner.enabled=false

%dev.application.host=localhost
application.host=dwitech-vps.de

#### Development Port
%dev.quarkus.http.port=40803

#### CORS
quarkus.http.cors=true

#### Graylog logging
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=${application.host}
quarkus.log.handler.gelf.filter-stack-trace=true
quarkus.log.handler.gelf.level=ALL
quarkus.log.handler.gelf.include-full-mdc=true

#### Logging
%dev.quarkus.log.console.json=false
quarkus.log.console.color=true
quarkus.log.syslog.format=%d{dd-MM-yyyy HH:mm:ss,SSS} | [%-5p] %C{1}.%M(%L) | %m%n
quarkus.log.file.format=%d{dd-MM-yyyy HH:mm:ss,SSS} | [%-5p] %C{1}.%M(%L) | %m%n
quarkus.log.console.format=%d{dd-MM-yyyy HH:mm:ss,SSS} | [%-5p] %C{1}.%M(%L) | %m%n
quarkus.log.console.json.pretty-print=true

### Remote Clients
url.gateway.service=http://${application.host}:40801/

com.dwitech.saas.covidepass.check.boundary.CertificatesService/mp-rest/url=${url.gateway.service}
```

### Output of `uname -a` or `ver`
Darwin DWI-MBP15-1 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
### Output of `java -version`
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

### Quarkus version or git rev
1.12.2.Final

### Build tool
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Volumes/Work/tools/apache-maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home
Default locale: en_DE, platform encoding: US-ASCII
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Is this still a problem in the latest Quarkus versions?

**Comment by geoand** [comment]
Closing for lack of feedback.
