### ISSUE TITLE
Gradle multi-module project causes quarkusDev to fail

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#16023]
## Describe the bug

The issue manifests itself differently between Java and Kotlin projects but the setup is the same, a multi-module Gradle project where one module depends on one or more other modules and any of the depended on modules have empty sources.

Running `quarkusDev` in a Kotlin project causes it to fail with gradle outputting `Failed to run`. If you run with `--stacktrace` you can see a further error `Failed to locate classes directory in the project`.

 For Java, `quarkusDev` executes without error but Quarkus startup fails with a rather long chain of exceptions like `Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.UncheckedIOException: Error while reading file as JAR: /Users/kdubb/Downloads/code-with-quarkus/modA/build/classes/java/main`

This setup may seem unnecessary but we have some modules that are effectively dependency containers. One of the modules previously had some shared code and when that shared code was removed we encountered this issue; determining the cause of the issue was pretty time consuming.

### Expected behavior

`quarkusDev` completes correctly in both Java & Kotlin projects with this configuration and that Quarkus starts up correctly in the same configuration. 

### Actual behavior

For Kotlin projects, `quarkusDev` fails with nondescript `Failed to run` error.

For Java projects, `quarkusDev` completes but Quarkus fails to start with `Error while reading file as JAR`.

## To Reproduce

Attached are reproducer projects for both Java & Kotlin. The projects were derived from a simple code start project and adapted to use a shared gradle config in a way that many multi-module projects are setup

[code-with-quarkus-kotlin.zip](https://github.com/quarkusio/quarkus/files/6207863/code-with-quarkus-kotlin.zip)
[code-with-quarkus-java.zip](https://github.com/quarkusio/quarkus/files/6207864/code-with-quarkus-java.zip)

To solve the issues in either project you just need to place a `dummy.kt` or `dummy.java` in the appropriate source directory for `modA` module.

1.  Run `quarkusDev` in `modB` directory.

### Configuration
```properties
# Empty file as provided by the codestart
```

### Output of `uname -a` or `ver`

`Darwin host.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

### Output of `java -version`

```
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
```

### Quarkus version or git rev

`1.12.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.6 (Oracle Corporation 11.0.6+8-LTS)
OS:           Mac OS X 10.16 x86_64
```

## Additional context
(Add any other context about the problem here.)

**Comment by kdubb** [comment]
This may be related to #10894 as it seems to have an auspicious conclusion.

**Comment by glefloch** [comment]
@kdubb thanks for reporting this I will have a look on both issue.

**Comment by gilbertopsantosjr** [comment]
is this issue has been fixed ?
