### ISSUE TITLE
quarkus cli uber jars pom list external dependencies

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16026]
## Describe the bug
the published pom for  io.quarkus:quarkus-cli:1.13.0.Final:runner has a pom.xml that list dependencies but they are not needed.

that causes duplicate classes on classpath, affecting logging resolution see https://github.com/jbangdev/jbang/issues/813

### Expected behavior
im not really sure to be honest - but my first reaction is that the pom shouldnt say it needs deps.

we can also find workaround in jbang and just have it skip resolving but feels cleaner if maven pom.xm were correct.

**Comment by maxandersen** [comment]
so, isssue is that the -runner.jar has all its dependencies listed in the pom.xml despite its a shaded jar which should have zero dependencies.

https://stackoverflow.com/questions/39286613/maven-shaded-jar-used-as-external-project-dependency/51443562 describe the various situations and I would say there are few to choose from in no particular order:

a) deploy another "real" artifact with zero dependencies as described in https://stackoverflow.com/a/51443562/71208

b) add a marker attribute in the manifest.mf that jbang would grok as "don't need to add dependencies on the class path"

c) publish it as a standalone artifact on github release then point jbang on that jar directly.
i.e. jbang https://github.com/quarkusio/quarkus/releases/download/v2.0.0/quarkus-cli.jar


downside of B is that the dependencies will still be resolved....A would be the "real" deal.
upside of C is that we could have native binaries served the same way.

Thus maybe C is the better option actually.

**Comment by ebullient** [comment]
(c) is then followed by #10354?
Do we need a published GH release, or is pointing to the maven repository artifact jar sufficient (as you've done already in quarkusio/jbang-catalog#13)?

**Comment by maxandersen** [comment]
If we want to publish binaries I think it makes sense to use GitHub release locations in the long run.

**Comment by ebullient** [comment]
Resolved by #10354 (publish jar as GH release)
