### ISSUE TITLE
review quarkus cli command / flag structure

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16033]
current cli outline looks like this:

```
Usage: quarkus [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  build             Build your quarkus project
  clean             Clean current project
  create            Create a new quarkus project.
  create-jbang      Create a new quarkus jbang project.
  list              List installed (default) or installable extensions.
  platforms         List imported (default) or all available Quarkus platforms.
  add               Add extension(s) to current project.
  remove, rm        Remove an extension from this project.
  dev               Execute project in live coding dev mode
  create-extension  Creates the base of a Quarkus extension in different layout depending of the options and environment.
```

they currently can be grouped in following categories:

## project creation 

create, create-jbang, create-extension

imo. `create-jbang` should be a `--jbang` flag instead of its own command.

## platform/extension query/manipulation

list,add,remove/rm
platforms

kinda core to what we would like the cli to do but feels a bit weird we have list/add/remove/rm for extensions but then a separate platform command.

## dev time commands

build, clean, dev

force: they abstract away wether you are doing maven or gradle (in future jbang could be included here)

weakness: you cant express clean build - they always end up as two commands ..
missing remote dev

missing commands/ideas:

update - would check if quarkus has a newer release and update the corresponding build artifact. 

validate/lint - be able to see if using out-of-platform-bounds artifacts.

**Comment by ebullient** [comment]
> create-jbang should be a --jbang flag instead of its own command.

By this light, we should also simplify create-extension to use an --extension flag

```
Usage: quarkus [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  build             Build your quarkus project
  clean             Clean current project
  create            Create a new quarkus project.
  list              List installed (default) or installable extensions.
  platforms         List imported (default) or all available Quarkus platforms.
  add               Add extension(s) to current project.
  remove, rm        Remove an extension from this project.
  dev               Execute project in live coding dev mode
```  

Create options: 
```
Usage: quarkus create [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Create options:
     --jbang          Create a new quarkus jbang project. 
     --extension   Creates a Quarkus extension project.
```  

.. more tomorrow (Will edit) ...

**Comment by maxandersen** [comment]
Note, --jbang is an alternate build/layout like --gradle and --maven. 

But extension is arguably different "thing".

**Comment by ebullient** [comment]
It is.. but you could also think of it as a variant of what is being created.. you still end up with a project in the end.

**Comment by maxandersen** [comment]
lets say we unified on `create`, how would you indicate wether you want a quarkus project created or quarkus extension created ?

**Comment by aloubyansky** [comment]
What we should think of is a set options that `create-extension` (and another create flavors) need. If they have different options, I think they are good candidates to become subcommands instead of options of `create`.

**Comment by ebullient** [comment]
Coming back to this after letting it percolate for a bit.... (also some simplifications after talking w/ Max)

```
Usage: qs [-hV] [--verbose] [COMMAND]
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  create            Create a new quarkus project
  create-cli        Create a new quarkus command line project
  create-extension  Create a new quarkus extension project

  build             Build the current project
  clean             Clean the current  project
  dev               Run the current project dev mode (live coding)

  list              List extensions and platforms
  add               Add extension(s) to current project
  remove, rm        Remove extension(s) from this project
```

Lots of room for improvement w/ list. Wondering about pinning/filtering based on platform version (even if platform version then still appears in the resulting list.. ). Starts to make the existence/selection of a platform meaningful w.r.t. where extensions come from... 
```
Usage: qs list [-Bhi] [-s=PATTERN] [--include=all] [--name | --concise | --full | --origins]
List platforms and/or extensions.

Options
  -B, --batch-mode       run command in non-interactive batch mode
  -h, --help             display this help message

Filters
      --include=[all | extensions | platforms]
                         List platforms and extensions (default), only extensions, or only platforms
  -i, --installable      Display installable platforms and/or extensions
  -s, --search=PATTERN   Search for platforms or extensions that match the specified Java Pattern.

Output
      --name             Display name only. (default)
      --concise          Display name and description.
      --full             Display concise format and version related columns.
      --origins          Display extensions including their platform origins.
```

I don't have an impulse to change add/remove, though part of me is thinking about tucking under a dependency command (dep add, dep remove, dep tree, .. ?!)

```
Usage: qs add [-Bh] EXTENSION...
Add extension(s) to current project.

      EXTENSION...   extensions to add to project
  -B, --batch-mode   run command in batch mode
  -h, --help         display this help message
```

```
Usage: qs remove [-Bh] EXTENSION...
Remove an extension from this project.
      EXTENSION...   extensions to remove
  -B, --batch-mode   run command in batch mode
  -h, --help         display this help message
```

**Comment by aloubyansky** [comment]
Nice. A thing to keep in mind is commands like `add` and `list` depend on the context. E.g. if it's an application, it's what's described. What if I `create-extension` and do `add`? It could certainly still add a dependency on an extension, it's not unreasonable. But in that case it would have to update the deployment module as well.

**Comment by ebullient** [comment]
it could certainly help make sure you add the right dependency in the right place (as you don't always need them in both places, ... ). But there are a few cases where I need the extension dependency in one or the other (but not both), so yes, extensions are trickier. 

We could either say add/remove isn't supported for extension projects, or figure out a middle ground (e.g. advice on what needs to be added where to add the dependency on the other extension)

**Comment by aloubyansky** [comment]
Just in case, if a runtime extension artifact depends on a runtime artifact of another extension, it should be mirrored in the deployment deps. And the other way around.

**Comment by ebullient** [comment]
Micrometer uses some extensions in the test scope (so only in deployment, not at runtime at all).

Micrometer also uses other extensions optionally: so the optional dependency is in the runtime module, and maybe only the spi is in deployment (there are other checks in place to ensure paths aren't exercised if the other extension isn't there).

**Comment by maxandersen** [comment]
What does create-cli actually do ? Just create quarkus project without default resteasy ?

**Comment by maxandersen** [comment]
I kinda have mixed feelings that list works for both platform and extensions. 

not sure what implications are of the multiple platform notion. 

Wondering if list should be for extensions and a more generic query command to get info from the registry data ?

**Comment by ebullient** [comment]
create-cli creates a client project.. --without-jbang would apply there to remove the jbang wrapper.

elevates the nature of using quarkus to create cli projects (where jbang wrapper would be included by default)

**Comment by ebullient** [comment]
I can see the mixed feelings re: platforms and extensions.

In my head: platforms are a limiter on the extensions that are available (they are essentially an extension constraint).

I see the following output for list (MAKING THIS UP):
```
> qs list
Active/Enabled/Installed/? Platforms
 io.quarkus:quarkus-bom::pom:999-SNAPSHOT

Extensions
 quarkus-tika                                       
 quarkus-neo4j                                     
 quarkus-scala                                     
 quarkus-jgit 
```

Or: 
```
> qss list -i --origins
Active/Enabled/Installed/? Platforms
 io.quarkus:quarkus-bom::pom:999-SNAPSHOT

Available Extensions
 Logging JSON                                       999-SNAPSHOT                      io.quarkus:quarkus-bom::pom:999-SNAPSHOT
 Logging Sentry                                     999-SNAPSHOT                      io.quarkus:quarkus-bom::pom:999-SNAPSHOT
 Logging GELF                                       999-SNAPSHOT                      io.quarkus:quarkus-bom::pom:999-SNAPSHOT
```

There is a linkage between platform(s) and extensions. Reminding people which platform their project is using isn't a bad thing.

**Comment by maxandersen** [comment]
> create-cli creates a client project.. `--without-jbang` would be the option to remove the jbang wrapper.

so `create-cli` replaces `create-jbang` ?

Not a big fan as jbang projects using quarkus is just as able to be non-cli as a standard quarkus app. 

like `qs create --jbang resteasy,openshift` should be as doable as `qs create resteasy,openshift` just like `qs create-cli --jbang picocli,jackson` and `qs create-cli --gradle picocli,jackson` would both create a cli - just that with jbang lots of the ceromony is removed and deps are in the source files.

**Comment by ebullient** [comment]
ok. If --jbang is shorthand for "create a jbang wrapper" .. then that should be the option and create-jbang should go away, and we don't need one to create a client. :-P

**Comment by ebullient** [comment]
Above draft PR will let you play with options as I've messed with them so far.. and we can keep going more interactively.
```
Usage: q [-ehV] [--verbose] [COMMAND]
  -e, --errors    Produce execution error messages.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
      --verbose   Verbose mode.
Commands:
  create            Create a Quarkus project
  create-cli        Create a Quarkus command-line project
  create-extension  Create a Quarkus extension project
  build             Build the current project
  clean             Clean the current project
  dev               Run the current project in dev mode (live coding)
  list              List platform(s) and extensions
  add               Add extension(s) to current project.
  remove, rm        Remove an extension from this project.
```

create: 
```
Create a Quarkus project
Usage: q create [-B | -h] [[-g=GROUP-ID] [-a=ARTIFACT-ID] [-v=VERSION]]
                [--jbang | --maven | --gradle | --grade-kotlin-dsl] [--java |
                --kotlin | --scala] [-0 | -x=<list> [-x=<list>]...]
                [EXTENSION...]
By default, this command will create a new 'code-with-quarkus' directory
containing a Java project that will use maven to build a quarkus application
with groupId='org.acme', artifactId='code-with-quarkus', and version='1.0.0
-SNAPSHOT'.

      [EXTENSION...]        extension to add to project

Common options
  -B, --batch-mode          run command in batch mode
  -h, --help                display this help message

Project group, artifact, and version (org.acme:code-with-quarkus:1.0.0-SNAPSHOT)
  -g, --group-id=GROUP-ID   The groupId for maven and gradle artifacts
  -a, --artifact-id=ARTIFACT-ID
                            The artifactId for maven and gradle artifacts
  -v, --version=VERSION     The initial project version

Build tool
      --jbang               Use jbang
      --maven               Use Maven
      --gradle              Use Gradle
      --grade-kotlin-dsl    Use Gradle with Kotlin DSL

Target language
      --java                Use Java (default)
      --kotlin              Use Kotlin
      --scala               Use Scala

Example code
  -0, --no-examples         Do not include examples
  -x, --examples=<list>     List of example(s) to include in the project
```

create-cli:
```
Create a Quarkus command-line project
Usage: q create-cli [-B | -h] [[-g=GROUP-ID] [-a=ARTIFACT-ID] [-v=VERSION]]
                    [--jbang | --maven | --gradle | --grade-kotlin-dsl] [--java
                    | --kotlin | --scala] [EXTENSION...]
By default, this command will create a new 'cli-with-quarkus' directory
containing Java project that will use jbang to build a quarkus application.

      [EXTENSION...]        Extensions to add to project

Common options
  -B, --batch-mode          run command in batch mode
  -h, --help                display this help message

Project group, artifact, and version (org.acme:cli-with-quarkus:1.0.0-SNAPSHOT)
  -g, --group-id=GROUP-ID   The groupId for maven and gradle artifacts
  -a, --artifact-id=ARTIFACT-ID
                            The artifactId for maven and gradle artifacts
  -v, --version=VERSION     The initial project version

Build tool
      --jbang               Use jbang
      --maven               Use Maven
      --gradle              Use Gradle
      --grade-kotlin-dsl    Use Gradle with Kotlin DSL

Target language
      --java                Use Java (default)
      --kotlin              Use Kotlin
      --scala               Use Scala
```

**Comment by ebullient** [comment]
Trying to use shared option groups (e.g. the GAV groups for create and create-cli) is a little awkward when it comes to specify defaults because we use a different default "code-with-quarkus" vs. "cli-with-quarkus" .. I'm tempted to simplify and either use "code-with-quarkus" always.

**Comment by ebullient** [comment]
@ia3andy @mkouba .. see above

**Comment by aloubyansky** [comment]
> Trying to use shared option groups (e.g. the GAV groups for create and create-cli) is a little awkward when it comes to specify defaults because we use a different default "code-with-quarkus" vs. "cli-with-quarkus" .. I'm tempted to simplify and either use "code-with-quarkus" always.
> 

That makes sense, IMO, especially if it allows reusing some options and code.

**Comment by mkouba** [comment]
So I wonder whether it would make sense to turn such complicated commands (`create-extension`...) into a wizard-like multi-step process? IIRC jboss forge supported something similar, or? @gastaldi

**Comment by mkouba** [comment]
picocli [interactive options](https://picocli.info/#_interactive_password_options) might also help...

**Comment by ebullient** [comment]
create-extension does have interactive prompting for options you don't specify..
Also, just by the bye -- I was messing with the existing create extension behavior, and the way it determines the layout and makes assumptions as a result is.. REALLY confusing. So that's something I also want to sort out.

See more conversation in the PR? @gsmet made some comments..

**Comment by mkouba** [comment]
> create-extension does have interactive prompting for options you don't specify..

Does it? I can't see it anywhere but it could be that I just need more caffeine ;-)

**Comment by ia3andy** [comment]
@ebullient there are 3 differents cases handled:
- in quarkus or quarkus/extensions: (quarkus layout)
- in an empty dir: standalone layout
- in an empty dir with io.quarkiverse.xxx as groupId: quarkiverse layout

Is it that confusing?

**Comment by ebullient** [comment]
It is how it is determined and what attributes are (or are not) required that is magical/confusing.

**Comment by ia3andy** [comment]
If too confusing, we could make the layout part of the options or different subcommands `create-extension quarkus-core/standalone/quarkiverse` or something, I am not against it.
