### ISSUE TITLE
RESTEasy Reactive: @Blocking endpoint uses eventloop for streaming a Multi back to the caller

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#16050]
Describe the bug
When streaming a Multi back to a caller, the eventloop thread ends up being used even on @Blocking calls. This creates issues where the stream relies on thread context such as for transaction management and accessing the entitymanager.

Expected behavior
The worker thread should be used for the full request/response

Actual behavior
Eventloop is used after 2 iterations on the stream by a worker thread

To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

Configuration
Nothing abnormal

Screenshots
Run the reproducer to see failures. 

Environment (please complete the following information):
1.12.2.Final

**Comment by geoand** [comment]
Here is an explanation of why this happens:

Each item in the stream is written out here: https://github.com/quarkusio/quarkus/blob/7064dc76e59f50d3b4d5391eafdb26fa04797026/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java#L61. 
This happens on the executor thread correctly for the first item.
However, once Vert.x completes the write of the first item (on an event-loop thread as all IO is going through Vert.x), the handler is called on that event-loop thread.
That means that https://github.com/quarkusio/quarkus/blob/7064dc76e59f50d3b4d5391eafdb26fa04797026/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java#L77 is called on the event loop thread which means that subsequent items will be requested from that thread.

Now this is odd surely weird behavior, but I am not sure what the best approach to tackle it should be (cc @FroMage @stuartwdouglas).

Moreover @bcluap for the issue you described in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Returning.20JPA.20ResultStream.20over.20JAX-RS where your code was:

```java

    @Blocking
    @GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Multi<DbTemplate> csvFromStream() {
        Stream<DbTemplate> templates = em.createNativeQuery("SELECT * from template", DbTemplate.class)
                .setHint(QueryHints.HINT_FETCH_SIZE, Integer.MIN_VALUE)
                .getResultStream()
                .peek((o) -> {
                    em.clear();
                });
        return Multi.createFrom().items(templates);
    }

``` 

To get over the problem in a hacky way, you can likely switch to:

```java

    Executor executor; // for this to work, you need the context-propagation extension - if you don't use it, there is a hacky way to get a hold of this executor

    @Blocking
    @GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Multi<DbTemplate> csvFromStream() {
        Stream<DbTemplate> templates = em.createNativeQuery("SELECT * from template", DbTemplate.class)
                .setHint(QueryHints.HINT_FETCH_SIZE, Integer.MIN_VALUE)
                .getResultStream();
        return Multi.createFrom().items(templates)
          .emitOn(executor)
          .onItem((o) -> {
                    em.clear();
                })
    }

```

**Comment by bcluap** [comment]
Thanks @geoand for the analysis.

Playing around with your suggestion a bit I found I could get it to work by using an executor and passing the thread context explicitly. This was however about 50% slower than just setting the thread context on the eventloop itself as and when required (e.g. every 1000 items when we want to clear the EM). This means we only set the context when actually needed.

```
    @Inject
    ThreadContext threadContext;
    @Inject
    EntityManager em;

    @GET
    @Blocking
    @Produces(MediaType.APPLICATION_JSON)
    public Multi<DbTemplate> csvFromStream2() {
        Runnable clearEm = threadContext.contextualRunnable(() -> {
            em.clear();
        });
        AtomicInteger i = new AtomicInteger();
        Stream<DbTemplate> templates = em.createNativeQuery("SELECT * from template", DbTemplate.class)
                .setHint(QueryHints.HINT_FETCH_SIZE, Integer.MIN_VALUE)
                .getResultStream()
                .peek((o) -> {
                    if (i.incrementAndGet() % 1000 == 0) {
                        clearEm.run();
                    }
                });
        return Multi.createFrom().items(templates);
    }
```

The above example works a charm. I can stream about 55k records/s on my laptop. Here I stream 461MB of data with a 50MB heap:
![image](https://user-images.githubusercontent.com/26746221/112716607-fb565880-8eef-11eb-84d9-f2647048afee.png)

![image](https://user-images.githubusercontent.com/26746221/112716696-a0713100-8ef0-11eb-8ae8-8053b410e8d5.png)

**Comment by geoand** [comment]
Looks pretty nice!

On another note, this is another case where the stateless session from Hibernate would be great.
The reason is that the results of the query would be not be tracked and therefore there would be no need to clear the session.
We really need to get that documented and we will soon

**Comment by bcluap** [comment]
Thanks. Thats a nice tip:

```
    @GET
    @Blocking
    @Produces(MediaType.APPLICATION_JSON)
    public Multi<DbTemplate> csvFromStream2() {
        StatelessSession s = em.getEntityManagerFactory().unwrap(SessionFactory.class).openStatelessSession();
        Stream<DbTemplate> templates = s.createNativeQuery("SELECT * from template", DbTemplate.class)
                .setHint(QueryHints.HINT_FETCH_SIZE, Integer.MIN_VALUE)
                .getResultStream();
        return Multi.createFrom().items(templates);
    }
```

Works as well. Same performance.

**Comment by geoand** [comment]
Excellent 👌

**Comment by cescoffier** [comment]
@geoand should it be closed?

**Comment by geoand** [comment]
Yeah, I think we can close it. @bcluap please reopen if you feel it has not been addressed properly
