### ISSUE TITLE
Add multi-build support in a single module

### ISSUE THREAD

**Issue by bcournaud** [quarkusio/quarkus#16053]
## Description

Give the possibility to build the same module multiple times with different profiles, generating different artifacts.

## Implementation ideas

Add multiple executions to the Quarkus maven plugin, specifying a different Quarkus profile for each execution.
The plugin could then generate one artifact for each execution and store it into a specific output directory.

Here is an example of the `executions` we could find in the `pom.xml`, resulting in 2 subfolders:
- `target/foo-quarkus-app`
- `target/bar-quarkus-app`

```
<executions>
  <execution>
    <id>build-foo</id>
    <goals>
      <goal>generate-code</goal>
      <goal>generate-code-tests</goal>
      <goal>build</goal>
    </goals>
    <configuration>
      <systemProperties>
        <quarkus.profile>foo</quarkus.profile>
        <quarkus.package.output-directory>foo-quarkus-app</quarkus.package.output-directory>
      </systemProperties>
    </configuration>
  </execution>
  <execution>
    <id>build-bar</id>
    <goals>
      <goal>generate-code</goal>
      <goal>generate-code-tests</goal>
      <goal>build</goal>
    </goals>
    <configuration>
      <systemProperties>
        <quarkus.profile>bar</quarkus.profile>
        <quarkus.package.output-directory>bar-quarkus-app</quarkus.package.output-directory>
      </systemProperties>
    </configuration>
  </execution>
</executions>
```

**Comment by bcournaud** [comment]
Potential PR for this: https://github.com/quarkusio/quarkus/pull/16054

**Comment by essobedo** [comment]
@aloubyansky Hi, WDYT of this enhancement and the related PR proposal? It is somehow the next step of https://github.com/quarkusio/quarkus/pull/15356.

**Comment by aloubyansky** [comment]
I commented on the PR. Thanks!
