### ISSUE TITLE
Qute template failed to compile javascript syntax

### ISSUE THREAD

**Issue by krisachai** [quarkusio/quarkus#16067]
## Describe the bug
I followed this quickstart [guide ](https://quarkus.io/guides/security-openid-connect#single-page-applications) to the part that I need to create an static html page (coped from the link above).

```
@Path("/login")
public class LoginResource {
    @Inject
    @ResourcePath("login")
    Template login; 

    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance get() {
        return login.data("Hello", "world");
    }
}
```
However, the page that I created throws error 
```
org.jboss.resteasy.spi.UnhandledException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: No resolver for namespace: onLoad
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:610)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:520)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)

```

due to this particular javascript syntax **{onLoad**
```
  keycloak.init({onLoad: 'login-required'}).success(function () {
            console.log('User is now authenticated.');
        }).error(function () {
            window.location.reload();
        });
```
I'm able to access the login page after I put a whitespace between `{` and `onload`
something like this
``` 
 keycloak.init({ onLoad:
```
### Expected behavior
It should compile successfully 

### Actual behavior
It failed to compile

### Quarkus version
1.12.2.Final

**Comment by glefloch** [comment]
@krisachai have you tried escaping `{ˋ with `\{ˋ ?

**Comment by mkouba** [comment]
This is a known limitation. You have several possibilities:
1. Add a whitespace or any other invalida identifier after the `{; see also https://quarkus.io/guides/qute-reference#identifiers
2. Use the escape sequence `\{` (as mentioned by @glefloch)
3. Use [unparsed character data](https://quarkus.io/guides/qute-reference#unparsed-character-data) surrounded by `{|` and `|}` 
4. Use [content filters](https://quarkus.io/guides/qute-reference#content-filters) to treat the `<script>` tags as unparsed character data automatically

**Comment by krisachai** [comment]
Thank you all, I will close this issue as it is a known limitation.
