### ISSUE TITLE
@Scheduled add Support for Default Value and for Switching Timer Off

### ISSUE THREAD

**Issue by renegrob** [quarkusio/quarkus#16063]
## Description

The `@Scheduled` annotation currently allows the attributes `cron`, `every` and `delayed` to contain a fix value or reference a property value by an expression `{propertyname}`.
I suggest to offer a default value for the property expression: e.g. `@Scheduled(every = "{mytask.interval:5m}")` -> If the property `mytask.inteval`is `null` then the default value `5m` is used.
Also it is sometimes helpful to be able to switch a specific job off (e.g. on specific nodes). I suggest that if the property expression results in `off`or `disabled`, the timer for that scheduled task is switched off: `@Scheduled(every = "{mytask.interval:5m}")` if `mytask.inteval` is `off` the task will not be scheduled.

More examples:
`mytask.interval=null`: `@Scheduled(every = "{mytask.interval:off}")`  -> disabled
`mytask.interval=off`: `@Scheduled(every = "{mytask.interval:5m")}`  -> disabled
`mytask.interval=null`: `@Scheduled(every = "{mytask.interval:5m}")`  -> scheduled every 5m
`mytask.schedule=off`: `@Scheduled(cron = "{mytask.schedule:0/2 0/2 0 ? * * *")}`  -> disabled

`mytask.delayed=null`: `@Scheduled(every= "5m", delayed = "{mytask.delayed:1m}")`  -> scheduled every 5m with an initial delay of 1m.

* all `String` attributes of the `@Scheduled` annotation should support null defaults (similar to Wildfly property-replacement)
* `cron`and `every` should support the reserved values `off` and `disabled` to disable scheduling. (Better solution than: https://stackoverflow.com/questions/13835221/quartz-cron-expression-that-will-never-execute for `cron` and `every` cannot be switched off yet)
* Besides of the current property expression the JBoss/Wildfly style `${property}` expression could be supported, too
* Optionally nested expressions could be supported: `@Scheduled(every = "{mytask.interval:{global.defaultInterval:off}}`)
* Optionally property substitution could be used for substrings: `mytask.minutes='15,30,45'`: `@Scheduled(cron = "0 {mytask.minutes} * ? * *")` -> cron = `0 15,30,45 * ? * *`

## Implementation ideas

As property expressions are a general feature. This should probably be implemented consistently by different extensions. The current implementation is located in `io.quarkus.scheduler.runtime.util.SchedulerUtils` and only supports a single property value lookup.

**Comment by renegrob** [comment]
@radcortez I found your comment in smallrye-confi: https://github.com/smallrye/smallrye-config/issues/198#issuecomment-601777924. And I noticed that https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html#expression-interceptor is already in the Quarkus core. So I suggest to use that instead of having a proprietary implementation here. It already covers all the substitution features. For backwards compatibility we could add a leading $-sign to the expression if it starts with a "}". Like that only the values "off" and "disabled" need to be treated specially. But that can be done after the value resolution.

**Comment by mkouba** [comment]
I think that the possibility to specify the defaults and the "disabled" state might be very useful.

+1 to add support for the `${property}` syntax.

I'm not so sure about the "nested expressions" and "property substitution" though. I find the syntax quite complex and hard to read. Plus the additional value is questionable.

**Comment by renegrob** [comment]
Well, if we use `io.smallrye.common.expression.Expression` which is already in Quarkus core then it comes out-of-the-box although it might not add that much value. I think it makes sense to support everywhere the same expressions consistently. Else you end up with it looks the same but behaves slightly different than when used in this other extension.
Else I'd rather stick with the "{property}" syntax which then doesn't support what the "${property}" syntax does. But in the end you guys have to decide on this. For me the features are more relevant than the syntax or if the same Expression is used or not.

**Comment by mkouba** [comment]
> Well, if we use `io.smallrye.common.expression.Expression` which is already in Quarkus core then it comes out-of-the-box although it might not add that much value.

Ok, it makes sense to reuse the existing SM stuff. I'd still prefer not to propagate these features though.

> I think it makes sense to support everywhere the same expressions consistently. 

+1

> Else you end up with it looks the same but behaves slightly different than when used in this other extension.
> Else I'd rather stick with the "{property}" syntax which then doesn't support what the "${property}" syntax does. But in the end you guys have to decide on this. For me the features are more relevant than the syntax or if the same Expression is used or not.

Well, we could just prepend the `$` to the top level expression if needed, e.g. `{foo.bar}` would become `${foo.bar}` before the SM expression is parsed.

**Comment by renegrob** [comment]
> Well, we could just prepend the $ to the top level expression if needed, e.g. {foo.bar} would become ${foo.bar} before the SM expression is parsed.

+1
I can easily change that in the PR.
> I'd still prefer not to propagate these features though.

So should we prevent: `delay="${myconf.delay}s"`or `every="${myconf.task1.interval:${myconf.default.interval:off}}"` ?

**Comment by mkouba** [comment]
> So should we prevent: `delay="${myconf.delay}s"`or `every="${myconf.task1.interval:${myconf.default.interval:off}}"` ?

Well, I don't think we need to prevent this. We could just mention that the syntax follows the SM expression rules, add a link, and only show the simple examples, i.e. `${my.conf.delays:10s}` or `{my.conf.delays:off}`.

**Comment by radcortez** [comment]
Let me know if you need help.
