### ISSUE TITLE
RestEasy returns status code 200 instead of 307 when using Response.temporaryRedirect during test

### ISSUE THREAD

**Issue by s0l0c0ding** [quarkusio/quarkus#16070]
## Describe the bug
RestEasy returns status code 200 instead of 307 when verifying the  Response.temporaryRedirect with RestAssured

### Expected behavior
status code 307 should be returned 

### Actual behavior
a 200 status  code is returned 

## To Reproduce

run the test GreetingResourceTest

in this repo https://github.com/s0l0c0ding/bug-resteasy-restassured

1. controller with endpoint using Response.temporaryRedirect
2. write a test with restAssured
3. test will not pass when the expected code is 307 

### Configuration
no special configuration 

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Linux pc 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
### Quarkus version or git rev
1.12.2.Final

### Build tool
mvn

## Additional context
a correct response is given when trying with browser

**Comment by geoand** [comment]
There is no bug in either RESTEasy or RestAssured, it's just how RestAssured behaves - it follows redirects by default.

You can update your test method to

```java
    @Test
    public void testHelloEndpoint() {
        given()
          .config(config().redirect(redirectConfig().followRedirects(false)))
          .when().get("/hello-resteasy")
          .then()
             .statusCode(307);
    }
```

if you don't want to follow redirects

**Comment by s0l0c0ding** [comment]
thanks for the hint
