### ISSUE TITLE
Qute should handle non-public field only classes better

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16077]
## Description

would it not be feasible to have qute handle accessing fields like this:

```
 static public class Alias {
        String name;
        String description;
    }
```

right now i see to have to add getters or make the fields public.

which I could kinda live with but since jackson access them just fine and my class does not need the fields to be public to use it would be nice qute wasn't picky :)

in case there are some technical reasons for not doing it then could qute at least say
field found but missing accessors or similar ?

**Comment by mkouba** [comment]
> in case there are some technical reasons for not doing it then could qute at least say
field found but missing accessors or similar ?

FTR you should get an error at build time when using type-safe expressions and type-safe templates.

**Comment by mkouba** [comment]
I'm going to close this one. We didn't have any similar complaint and AFAIK neither EL nor SpringEL support this out of the box.
