### ISSUE TITLE
Difference in object serialization between REST and REST reactive

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#16081]
We are trying to serialize a MonetaryAmount object. However, the CurrencyUnit member of this object is serialized differently in REST and REST Reactive. 

In REST, the attached serializer (see class `io.i15s.quarkus.objectmapper.ObjectMapperConfiguration`) is used and therefore the object is formatted correctly: 

```json
{
   "amount":0,
   "currency":"EUR"
}
```

But when we use REST Reactive, the serializer is not used and the object is formatted using POJO serializer:

```json
{
   "amount":0,
   "currency":{
      "context":{
         "empty":false,
         "providerName":"java.util.Currency"
      },
      "defaultFractionDigits":2,
      "currencyCode":"EUR",
      "numericCode":978
   }
}
```

The bug happens in Quarkus 1.12.0.Final - 1.12.2.Final and also in Quarkus 1.13.0.CR1

We created a small project to reproduce: https://github.com/andlinger/quarkus-object-mapper

**Comment by geoand** [comment]
I'll check it out

**Comment by geoand** [comment]
I am not sure if this is a Jackson Databind or Jackson Datatype Money problem, but in any case https://github.com/zalando/jackson-datatype-money/pull/283 should take care of the issue.

**Comment by geoand** [comment]
https://github.com/zalando/jackson-datatype-money/pull/283 was merged so I'll go ahead and close this

**Comment by andlinger** [comment]
awesome! thank you
