### ISSUE TITLE
JWT Config key behevior different in native and jvm mode

### ISSUE THREAD

**Issue by Andro999b** [quarkusio/quarkus#16099]
## Describe the bug
`mp.jwt.verify.publickey.location` is build time config key in native mode
and runtime in jvm mode

### Expected behavior
`mp.jwt.verify.publickey.location` to  be runtime evaluated in both jvm and native

### Actual behavior
`mp.jwt.verify.publickey.location`  evaluate during build in native mode

1. Use env varaible in `mp.jwt.verify.publickey.location` like: `http://${NAMESPACE}-accounts.${NAMESPACE}.svc.cluster.local/jwks`
2. Observe: ` Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#registerNativeImageResources threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value NAMESPACE in property mp.jwt.verify.publickey.location
`

### Output of `uname -a` or `ver`
Linux andrii-PC 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

### GraalVM version (if different from Java)
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

### Quarkus version or git rev
1.13.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.5.1

**Comment by sberyozkin** [comment]
@radcortez hey Roberto, how would we tackle this one :-) ? (I believe it is not a smallrye-jwt specific issue and relates to the ongoing conversation about syncing `mp-*/smallrye-*` properties with the quarkus-namespaced properties)

**Comment by radcortez** [comment]
No, the issue here is that the MP property is being queried during build time to register the resource with the native image. But we don't want to force configuration properties outside the `quarkus` namespace to be build time. I've made a fix that registers the resource if we can find one, and if not it is on the user to provide the correct configuration during runtime.
