### ISSUE TITLE
Register subclasses MessageCodec for EventBus usage

### ISSUE THREAD

**Issue by flupec** [quarkusio/quarkus#16103]
## Describe the bug
The problem is that quarkus does not handle the case when a subtype of the type declared in the method is passed to the method. Quarkus registers Message Codec's only specifically for classes declared with `@ConsumeEvent` annotation.

### Expected behavior
`LocalEventBusCodec` must be registered for all subtypes of parameter type from method that is annotated with`@ConsumeEvent`

### Actual behavior
Currently, `LocalEventBusCodec` registered only for concrete classes from method parameter.

## To Reproduce

1. Create two classes, for example:
```
public class Event {
    String a;
}

public class SubClassEvent extends Event {}
```
2. Declare event consumer method, for example:
```
@ConsumeEvent("address")
void handle(Event event) {}
```

3. Send or publish object of `SubClassEvent` type via EventBus and see following message: `java.lang.IllegalArgumentException: No message codec for type: SubClassEvent`

### Quarkus version or git rev
1.11.1.Final

## Additional context
I think the problem is in following implementation: [EventBusCodecProcessor](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusCodecProcessor.java)

**Comment by flupec** [comment]
Here is simple [reproducer](https://github.com/flupec/quarkus-issue-rreproducer)

**Comment by cthiebault** [comment]
Hello
I have the same problem with version 2.14.1
How did you manage it?

**Comment by cthiebault** [comment]
Have a look to 
https://github.com/quarkusio/quarkus/blob/2.14/extensions/vertx/deployment/src/test/java/io/quarkus/vertx/MyPetCodec.java

**Comment by gsmet** [comment]
Looks like this one fell through the cracks. I created https://github.com/quarkusio/quarkus/pull/29560 to fix it.

**Comment by gsmet** [comment]
@flupec thanks for the reproducer, btw!
