### ISSUE TITLE
quarkus.tls.trust-all=true not working

### ISSUE THREAD

**Issue by afnaanbaig** [quarkusio/quarkus#16119]
BUG: tls trust all not working

### Expected behavior
Expected result is to ignore the certificate validation and allow all sorts of certificates whether secure or not 

### Actual behavior
Unable to access the actual website through our application.
Link for testing purpose.
https://untrusted-root.badssl.com/

## To Reproduce

[https://github.com/afnaanbaig/Bad-ssl-quarkus] 

### Configuration
```properties

quarkus.tls.trust-all=true
Bad-ssl/mp-rest/uri=https://untrusted-root.badssl.com

```

### Output of `ver`
Microsoft Windows [Version 10.0.19041.867]

### Output of `java -version`
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

### GraalVM version 
not running on graal vm 

### Quarkus version 
<quarkus.platform.version>1.12.2.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3\bin\..
Java version: 11.0.9, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.9
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
## Additional context
I need to disable SSL verification

**Comment by glefloch** [comment]
Thanks for reporting this @afnaanbaig. Under the hood, `quarkus.tls.trust-all` add `io.quarkus.restclient.NoopHostnameVerifier` as hostname verifier of all rest client (https://quarkus.io/guides/rest-client#disabling-hostname-verification). 
I will check if we need to do more.

**Comment by afnaanbaig** [comment]
o.quarkus.restclient.NoopHostnameVerifier this does not work as well. I have tried this method not once but multiple times and I am unable to resolve the issue.  Your help would be appreciated.
