### ISSUE TITLE
Allow us to enable browser-like http client caching in quarkus rest clients

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#16118]
## Description

It would be nice if we could configure the quarkus rest clients to respect http cache headers returned by a remote server. In case these headers are present, the rest client could decide on its own, wether it should send a request to the server again or if a local copy of a previous response from a local cache could be sufficient. The etag header could furthermore reduce the amount of bytes transferred over the wire in case the etag matches the latest server version. 

These mechanics are quite common in our case, especially in our client applications (android, ios etc.). Frameworks like okhttp support these out-of-the-box and it works best for resources that do not change very often (static files etc.). It would be nice if we could use the same techniques on the server-side as well. Aside from the reduced traffic, we could have more control on the server-side as we could easily change the expiry dates for certain resources. 

I am aware that there is a suggestion to configure a browser like cache for [resteasy clients](https://docs.jboss.org/resteasy/docs/4.0.0.Final/userguide/html/Cache_NoCache_CacheControl.html#client_cache); yet the proposed solution feels a bit "experimental" (delete whole cache if size too big, write to mailing list if other cache solutions should be supported) imo. In order to have some caching in place, I decided to manually cache the responses with [quarkus application caching](https://quarkus.io/guides/cache) instead for now. It would be nice though, if this could be a core feature of quarkus.

**Comment by geoand** [comment]
@michalszynkiewicz is this something we have considered?

**Comment by michalszynkiewicz** [comment]
Caching for the rest client is planned, here's another issue that talks about it: https://github.com/quarkusio/quarkus/issues/22797

**Comment by geoand** [comment]
Let's keep one issue then. I'll let you decide which :)

**Comment by michalszynkiewicz** [comment]
I'll leave the one Max created because it's more generic but will add the description of this one there as a comment.

**Comment by michalszynkiewicz** [comment]
Closed in favor of https://github.com/quarkusio/quarkus/issues/22797
