### ISSUE TITLE
JDBC ConfigSource Extension

### ISSUE THREAD

**Issue by wansors** [quarkusio/quarkus#16124]
## Describe the extension

The idea is to have a extension that implements a ConfigSource to read properties from a JDBC Database table.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
```properties
# Add your application.properties here, if applicable.
quarkus.jdbc-config.enabled If set to true, the application will attempt to look up the configuration from DB
quarkus.jdbc-config.table table name for configuration records, default value is "configuration"
quarkus.jdbc-config.key-column name of the column containing the key, default value is "key"
quarkus.jdbc-config.value-column name of the column containing the value, default value is "value"

```

## Additional context
The extension can depend on agroal.
It can be similar to https://github.com/microprofile-extensions/config-ext/tree/main/configsource-db, but with quarkus constrains (No JNI).

Initial discussion about implementation:
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/ConfigSourceProvider.20from.20Database.20Table.20Extension

**Comment by geoand** [comment]
I think this would be interesting to have the in Quarkiverse.

WDYT @phillip-kruger @radcortez ?

**Comment by phillip-kruger** [comment]
Yea, I was thinking that many of the config extensions can move there.

**Comment by radcortez** [comment]
+1 for a Quarkiverse Extension. 

I'm wondering if we should group all sources in a single extension with multi modules or just keep them separate.

**Comment by wansors** [comment]
Can I create a PR to add the jdbc config module on
https://github.com/quarkiverse/quarkus-config-extensions ?

I have a code that implements a ConfigSourceFactory, Do I need to develop it as the others config extensions (I think they use the ConfigSourceProvider)?

Thanks

**Comment by radcortez** [comment]
Feel free to open a PR. We may need to work the project structure a bit, but I'm thinking a multimodule project with each source in a submodule.

I guess that you use `ConfigSourceFactory` to read some additional configuration and configure the source? In the case, it is fine, because you cannot do it with ´ConfigSourceProvider`.

**Comment by wansors** [comment]
Hi @radcortez ,

I created a PR, there will be some things to analyze.

The problem of using ConfigSourceContext to obtain the config items, makes quarkus complain when configuring the module:
`Unrecognized configuration key "quarkus.jdbc-config.key-column" was provided`

Where should I put a guide or readme explaining how to configure it?

Thanks
