### ISSUE TITLE
DevServices: Passing parameters to TestContainers

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#16125]
## Description

The new DevServices stuff in 1.13 is awesome! It would be really nice to be able to pass additional parameters directly to testcontainers.

For example:

```properties
quarkus.datasource.devservices.image-name=postgres:13
quarkus.datasource.devservices.properties.TC_INITSCRIPT=db/schema.sql
```

where in `src/main/resources/db` there is a `schema.sql` file that creates the schema.

See the Using a classpath init script section from https://www.testcontainers.org/modules/databases/jdbc/

Right now I'm doing this:

```properties
%test.quarkus.datasource.jdbc.url=jdbc:tc:postgresql:13:///mydb?TC_INITSCRIPT=db/schema.sql
%test.quarkus.datasource.jdbc.driver=org.testcontainers.jdbc.ContainerDatabaseDriver
```

Would be nice to be able to get this through the DevServices config.

**Comment by geoand** [comment]
I am a little confused, doesn't `quarkus.datasource.devservices.properties.TC_INITSCRIPT=db/schema.sql` already do what you want?

**Comment by edeandrea** [comment]
No it doesn't. When you look at the resolved properties the JDBC url is not a testcontainers url (i.e. jdbc:tc:.......). Its a standard postgres url.
