### ISSUE TITLE
CLI: reported name is incorrect

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#16152]
```
$ qs
Usage: quarkus [-ehV] [--verbose] [COMMAND]
...
$ quarkus
quarkus: command not found
```

That's wrong: it's called `qs` so use `$0` (name of the current executable) to report the usage line

**Comment by gsmet** [comment]
Are you testing main or 1.13? Something related got fixed here: https://github.com/quarkusio/quarkus/pull/15747 . Not sure if it's the same issue or not.

**Comment by FroMage** [comment]
How can I know? I installed with `curl -Ls https://sh.jbang.dev | bash -s - app install --force qs@quarkusio`

**Comment by gsmet** [comment]
I have no idea what this does :). But with `main`, I have `qs` in the usage. So I think it has been fixed properly! Closing.

**Comment by FroMage** [comment]
```
$ qs --version
1.13.0.Final
```

So I guess you're right.

> I have no idea what this does :).

This is how the official documentation tells us to install it, get with the program ;)
