### ISSUE TITLE
Adding a Microprofile Custom ConfigSource not possible?

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#1616]
I'm trying to add a customer config source as per https://www.tomitribe.com/blog/custom-configsource-with-microprofile-configuration/

The following code snippet works in both Thorntail and Oracle Helidon, but I can't get it to work in Quarkus. Is this a bug or not yet supported by the MP Config implementation in Quarkus?

```java
public class MyConfigSource implements ConfigSource {

  private static final Map<String, String> PROPERTIES = new HashMap<>();

  public MyConfigSource() {
    System.out.println("*** Initializing MyConfigSource ***");
  }

  @Override
  public int getOrdinal() {
    return 800;
  }

  @Override
  public String getValue(String key) {
    if (PROPERTIES.containsKey(key)) {
      return PROPERTIES.get(key);
    }
    return null;
  }

  @Override
  public String getName() {
    return "MyCustomConfigSource";
  }

  @Override
  public Map<String, String> getProperties() {
    return PROPERTIES;
  }
}
```
and in  
```
/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource contents:
se.acme.quarkus.MyConfigSource
```

**Comment by kenfinnigan** [comment]
Are there any errors? Or it just does nothing?

**Comment by enbohm** [comment]
@kenfinnigan no errors, Quarkus starts but doesn't seem to do anything with the ConfigSource (the class doesn't seem to be instantiated at startup)

**Comment by gsmet** [comment]
@enbohm can you prepare a simple reproducer so that we can take a look?

**Comment by enbohm** [comment]
sure, will do that later this evening or early tomorrow morning!

**Comment by enbohm** [comment]
My bad here....sorry

While trying to write a reproducer with a test case it did work. I was expecting the class "MyConfigSource" to be initialized while Quarkus was starting (since that has been the case with Helidon and other MP Config implementation). BUT it turns out to be that Quarus is only instantiating the class when a ConfigProperty is used, i.e. it delays the initialization of the custom class ("lazy") until needed. 

I'm using a custom ConfigSource to read from path /run/secrets/ when the app is running in a Docker container (Docker secrets). If the secret doesn't exist, the container fails to start. With Quarkus this seems to be delayed and the container might start and fail a bit later but I guess that the spec doesn't say anything when the custom config source should be initiated. Anyhow, this is working and I'm closing this issus. Keep up the good work :)
