### ISSUE TITLE
The Dev UI link in the application root path points to the error 

### ISSUE THREAD

**Issue by ThreeDollarsABottleOfGreenTea** [quarkusio/quarkus#16166]
## Describe the bug
The Dev UI link in the application root path points to the error 

### Expected behavior
Forward the '192.168.0.111:8080/**monitor**/q/dev' link to open this page. 

### Actual behavior
This link leads me to 'http://192.168.0.111:8080/q/dev/', this page can't open, where root-path is missing.

## To Reproduce

Build a quarkus application use get started in the idea.

1. Build a quarkus application use get started in the idea.
2. Change application.properties to application.yml
3. Add config quarkus:http:root-path: /monitor to application.yml
4. Add quarkus-config-yaml dependencies to pom 
5. Use command with mvn compile quarkus:dev to run the program
6. Visit the link 'http://192.168.0.111:8080/monitor/'
7. Click the Quarkus now ships with a **Dev UI** (available in dev mode only) button
8. bug has happened

### Configuration
```properties
# Add your application.yml here, if applicable.
quarkus:
  http:
    port: 8080
    root-path: /monitor
```

### Screenshots
![image](https://user-images.githubusercontent.com/23132086/113241241-bc5f3480-925a-11eb-9980-ef52f44c13ff.png)

![image](https://user-images.githubusercontent.com/23132086/113241324-ef092d00-925a-11eb-997c-f4b424c6cdc3.png)
![image](https://user-images.githubusercontent.com/23132086/113241356-00ead000-925b-11eb-9404-d8bb50d7a993.png)

### Output of `uname -a` or `ver`
```
Microsoft Windows [Version 10.0.18363.1440]
```

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Maven home: D:\Application\apache-maven-3.6.3\bin\..
Java version: 11.0.10, vendor: GraalVM Community, runtime: D:\Application\graalvm\graalvm-ce-java11-21.0.0.2
Default locale: en_US, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

## Additional context
Forward link is error.

**Comment by gsmet** [comment]
Yeah, the index page is static so it doesn't react to your configuration. I don't think we want to change that because we don't want to have a template engine as a required dependency.

**Comment by ThreeDollarsABottleOfGreenTea** [comment]
> Yeah, the index page is static so it doesn't react to your configuration. I don't think we want to change that because we don't want to have a template engine as a required dependency.

Maybe you can get this parameter from address bar to fix this bug.
