### ISSUE TITLE
Oracle - Agroal can't connect with service name

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#16162]
Hi!

I'd like to connect to an Oracle database with service name instead of SID, I receive the following message:

Invalid connection string format, a valid format is: "host:port:sid" : java.sql.SQLException: Io exception: Invalid connection string format, a valid format is: "host:port:sid"

The format I'd like to use: host:port/service_name

Could you provide any solution to this?

**Comment by senzu** [comment]
With another Oracle JDBC driver worked, sorry

<dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11</artifactId>
      <version>21.1.0.0</version>
</dependency>

**Comment by gsmet** [comment]
No worries, thanks for the follow-up!
