### ISSUE TITLE
Support more than one kafka `kafka.bootstrap.servers` per application

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16179]
## Description

Even if Kafka scale very well and the security is done by topics (so make sense that multi-tenancy it's also covered by topics), sometimes could make sense to have two or more Kafkas in your infrastructure/env. 

Nowadays I didn't find a way to configure two or more kafkas on your `application.properties`

```
kafka.bootstrap.servers
```

I suggest something like...

`kafka.`service_name`.bootstrap.servers`

Like in databases:  `quarkus.datasource."datasource-name".reactive.mysql.charset`

What do you think?

**Comment by cescoffier** [comment]
In Reactive Messaging each channel can have its own bootstrap.servers. In addition, with the service binding work, we generate multiple kafka configurations (using the service binding id as name).

**Comment by cescoffier** [comment]
basically, it's already in the works.

**Comment by pjgg** [comment]
Ok so If for example, I have an outgoing topic called `source-stock-price`  that receive events from a producer, and an incoming topic called `sink-stock-price`, we could have a configuration like the following one:
```
mp.messaging.outgoing.source-stock-price.connector=smallrye-kafka
mp.messaging.outgoing.source-stock-price.bootstrap.servers=localhost:9092
mp.messaging.outgoing.source-stock-price.topic=stock-price
mp.messaging.outgoing.source-stock-price.value.serializer=io.apicurio.registry.utils.serde.AvroKafkaSerializer
mp.messaging.outgoing.source-stock-price.apicurio.registry.artifact-id=io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
mp.messaging.outgoing.source-stock-price.apicurio.registry.global-id=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
mp.messaging.outgoing.source-stock-price.apicurio.registry.avro-datum-provider=io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider

mp.messaging.incoming.sink-stock-price.connector=smallrye-kafka
mp.messaging.incoming.sink-stock-price.bootstrap.servers=168.127.0.65:9093
mp.messaging.incoming.sink-stock-price.topic=end-stock-price
mp.messaging.incoming.sink-stock-price.value.serializer=io.apicurio.registry.utils.serde.AvroKafkaSerializer
mp.messaging.incoming.sink-stock-price.apicurio.registry.artifact-id=io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
mp.messaging.incoming.sink-stock-price.apicurio.registry.global-id=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
mp.messaging.incoming.sink-stock-price.apicurio.registry.avro-datum-provider=io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider

```

Assuming that channel `source-stock-price` is listening on `localhost:9092` and `sink-stock-price` is listening on `168.127.0.65:9093` 

Thank you @cescoffier I think that we could close this issue. 
As a suggestion, I think that [this documentation](https://quarkus.io/guides/kafka) could reflect this configuration in some manner at least on `Table 1. Incoming Attributes of the 'smallrye-kafka' connector` leave a comment as `kafka.bootstrap.servers can be configured globally or per channel `
