### ISSUE TITLE
Http2 does not work with reactive routes in quarkus dev mode

### ISSUE THREAD

**Issue by lrotim** [quarkusio/quarkus#16170]
## Describe the bug
When using enabling http2 & SSL receiving a request from browser that is processed via HTTP2 on quarkus backend yields `java.lang.IllegalStateException: Request has already been read` Error if using reactive route in dev mode

As far as I can see in VertxHttpRecorder there is an attempt to resume a request which raises an error - This  "Recorder" is added in front of any Route added with @Route annotation 

If Http1.1 is used the same code works ok

### Expected behavior
That a route would serve the request without raising an error 

### Actual behavior
Registering any Reactive route results in raising an IllegalStateException 

## To Reproduce

I've setup a small example repo on git https://github.com/lrotim/quarkus-bug.git

1. `git clone https://github.com/lrotim/quarkus-bug.git`
2. `cd quarkus-bug`
3. Run quarkus in dev mode with provided certificate for SSL (dev certificates are in the given repo), command: `mvn -Dquarkus.http.ssl.certificate.file="$(pwd)/dev.com+3.pem" -Dquarkus.http.ssl.certificate.key-file="$(pwd)/dev.com+3-key.pem" quarkus:dev`
4. Goto http://localhost:8080/hello -> works without error, using HTTP1.1
5. Goto https://localhost:8443/hello -> raises an error, using HTTP2

### Configuration
```properties

quarkus.http.http2=true
quarkus.http.ssl-port=8443

```

### Output of `uname -a` or `ver`
Darwin nb-lrotim.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)

### Quarkus version or git rev
1.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven home: /Users/leonrotim/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by gsmet** [comment]
@stuartwdouglas could you have a look?

**Comment by cescoffier** [comment]
That's probably is a "if (! response.isEnded())" missing.

**Comment by lrotim** [comment]
> That's probably is a "if (! response.isEnded())" missing.

What do you mean by that? Missing as-if in quarkus source code?
