### ISSUE TITLE
Include Quarkiverse Google Cloud Services in the platform

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#16175]
As noted earlier, our `camel-quarkus-google-bigquery` and `camel-quarkus-google-pubsub` extensions depend on `io.quarkiverse.googlecloudservices:quarkus-google-cloud-bigquery` and `io.quarkiverse.googlecloudservices:quarkus-google-cloud-pubsub` extensions respectively. For this to be legal, those `io.quarkiverse.googlecloudservices:*` should be tested in the platform.

**Comment by ppalaga** [comment]
cc @jamesnetherton

**Comment by aloubyansky** [comment]
fyi @loicmathieu

**Comment by loicmathieu** [comment]
@aloubyansky can you point me to where I can find the information of what it means to be in the platform (cost, integration way, release process).

Another question, Camel currently only use two services, should I only include those ones or should I include all the extensions ?

**Comment by ppalaga** [comment]
We plan to add storage and functions. So, we'd prefer to have those at least.

**Comment by loicmathieu** [comment]
Function is already a core extension.

Quarkiverse Google Cloud services provides the following extensions:

   - BigQuery
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/bigquery>
   - Bigtable
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/bigtable>
   - Firestore
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/firestore>
   - PubSub
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/pubsub>
   - Secret Manager
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/secret-manager>
   - Spanner
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/spanner>
   - Storage
   <https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/storage>


Le jeu. 1 avr. 2021 à 15:09, Peter Palaga ***@***.***> a
écrit :

**Comment by ppalaga** [comment]
OK, out of those, we (Camel Quarkus) are only interested in bigquery, pubsub and storage, which is not to say that we are against publishing everything :)

**Comment by aloubyansky** [comment]
@loicmathieu i'll write a doc about that and let you know.
Ideally, what you need to provide is
* a BOM that includes your extensions and their required dependencies (you may import other BOMs they require)
* tests packaged as test-jar

You don't need to package the whole testsuite, more like smoke tests. They will be integrated into the platform TS.

**Comment by aloubyansky** [comment]
Your BOM will be imported here https://github.com/aloubyansky/quarkus-platform/blob/main/bom/pom.xml
And your tests will be integrated in https://github.com/aloubyansky/quarkus-platform/tree/main/integration-tests

**Comment by aloubyansky** [comment]
I would consider adding all your extensions to the platform. It probably makes more sense that way.

**Comment by aloubyansky** [comment]
BTW, i'm working on a new platform project setup. Which hopefully make it all easier. It's not yet ready though, just keep in mind we are looking into improving it.

**Comment by loicmathieu** [comment]
Hi,

Thanks for the information.

I don't have a bom at the moment but was thinking of creating one for some
time, now seems to be a good moment ;)

For smoke tests, this is not easy and we will not be able to test all the
services as not all provide emulators (some needs a real instance on the
cloud to be run). So I could only include tests for which an emulator
exists.

Regards,

Loïc

Le jeu. 1 avr. 2021 à 20:58, Alexey Loubyansky ***@***.***> a
écrit :

**Comment by ppalaga** [comment]
> I don't have a bom at the moment but was thinking of creating one for some time, now seems to be a good moment ;)

@jamesnetherton recently did some alignment of google dependency versions in Camel Quarkus so he may perhaps help.

**Comment by loicmathieu** [comment]
Just created a BOM this morning so it would be easier to manage the version.
I still need to investiguate on the usage of the library BOM from Quarkus, last time I check we use too many Google library so I was reluctant to use it to avoid possible issue with grcp or other areas.
