### ISSUE TITLE
Cannot use Hibernate on Java 11

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#1618]
I'm using Hibernate to persist on PostgreSQL and on H2, on tests.
When executing tests or running on dev mode (mvn quarkus:dev) I get failures on Java 11. Exception bellow.
Setting the compatibility mode to Java 9, make things work. I'm using the latest Quarkus 0.12.0 but this already happened in the previous version. 
Relevant dependencies:
```
 <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
            <version>${quarkus.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-postgresql</artifactId>
            <version>${quarkus.version}</version>
            <scope>provided</scope>
        </dependency>
...
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
            <version>${quarkus.version}</version>
            <scope>test</scope>
        </dependency>
```
Some of the annotations I'm using:
```
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
```
---
Config:
quarkus.datasource.url:jdbc:postgresql://localhost:5432/something
quarkus.datasource.username:something
quarkus.datasource.password:something
quarkus.hibernate-orm.database.generation=drop-and-create

Test Config:
quarkus.datasource.url=jdbc:h2:tcp://localhost/mem:something;MODE=PostgreSQL
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username:sa
quarkus.datasource.password:
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm.database.generation=drop-and-create

---

> 11:32:53,369 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>         at java.base/java.lang.Class.newInstance(Class.java:584)
>         at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:118)
>         at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
>         at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
> Caused by: java.lang.RuntimeException: Failed to start quarkus
>         at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
>         ... 8 more
> Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [com.<removed>]
>         at io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:55)
>         at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:109)
>         at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:155)
>         at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:149)
>         at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:298)
>         at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:119)
>         at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:93)
>         at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:59)
>         at io.quarkus.hibernate.orm.runtime.HibernateOrmTemplate$4.created(HibernateOrmTemplate.java:82)
>         at io.quarkus.arc.runtime.ArcDeploymentTemplate.initBeanContainer(ArcDeploymentTemplate.java:99)
>         at io.quarkus.deployment.steps.ArcAnnotationProcessor$build9.deploy(Unknown Source)
>         ... 9 more
> Caused by: java.lang.UnsupportedOperationException
>         at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
>         at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
>         at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
>         at io.quarkus.runner.RuntimeClassLoader.handleTransform(RuntimeClassLoader.java:237)
>         at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:191)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Class.java:398)
>         at io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:53)
>         ... 19 more
>

**Comment by gsmet** [comment]
Looks like we are not using the correct ASM version. Will fix.

**Comment by doublefx** [comment]
Hi Guys,

Is it fully fixed?

All good with java compatibility 9 but with java 11, I still get:

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.demo.entity.AccountDetailsTest]: Failed to enhance class com.demo.entity.AccountDetails
Caused by: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class com.demo.entity.AccountDetails
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
```

**Comment by stuartwdouglas** [comment]
Can you open a new issue with the details, and include either a reproducer or at the very least the full stack trace so we can get some idea what is happening?

**Comment by gwenneg** [comment]
@doublefx The stack trace from your comment looks pretty much like the one from #6800 which was fixed today in Hibernate ORM. Since this is an upstream issue, we don't know yet which Quarkus release will include this fix.
