### ISSUE TITLE
Debugger doesn't stop on a breakpoint when debugging a Quarkus app

### ISSUE THREAD

**Issue by svor** [quarkusio/quarkus#16191]
## Describe the bug
Active breakpoints don't work if you make changes before debugging a Quarkus application, but after disabling/enabling the breakpoint, it starts working. It is reproducible in VS Code and Eclipse IDE.

As @maxandersen suggested I tried to disable instrumentation `-Dquarkus.live-reload.instrumentation=false` and the problem has gone.

### Expected behavior
The debugger should stop on the line with a breakpoint

### Actual behavior
The debugger doesn't stop on the line with a breakpoint if add another breakpoint or even remove/add current one and refresh the application, it'll work as expected

## To Reproduce
Here is a screencast with the problem: https://www.youtube.com/watch?v=CAso9LDtX98

1. Clone and open getting-started app https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started
2. Package it (`mvn package`) and run in dev mode (`mvn compile quarkus:dev -Dquarkus.http.host=0.0.0.0`)
3. Open file (`GreetingResource`) and set breakpoint on line 21
4. Make small changes in the file (add spaces)
5. Run the debugger to attach to the app (it is important to attach after making changes)
debug configuration is:
```json
{
 "type": "java",
 "request": "attach",
 "name": "Attach to Remote Quarkus App",
 "hostName": "localhost",
 "port": 5005
}
```
6. Open the application http://localhost:8080/hello/greeting/lola

### Screenshots
https://www.youtube.com/watch?v=CAso9LDtX98

### Output of `uname -a` or `ver`
18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.8" 2020-07-14

## Additional context
(Add any other context about the problem here.)

**Comment by maxandersen** [comment]
@stuartwdouglas rings a bell ? Feels like our check for instrumention clears/disables the active breakpoints somehow.

**Comment by stuartwdouglas** [comment]
We have disabled instrumentation by default, as it seems to cause lots of problems like this one (which I think is a JDK/IDE problem rather than a Quarkus one).
