### ISSUE TITLE
Introduce Tuning guide

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1621]
Introduce Tuning guide (for stuff -Xmx100m -Xmn70m) as these options have slightly different meaning in jvm vs. native mode of GraalVM.

Users should be guided through this area to avoid mistakes.

@n1hility fyi

**Comment by kenfinnigan** [comment]
Is this a duplicate of #1620?

**Comment by rsvoboda** [comment]
Yeah, I created it basically at the same time as David :)
