### ISSUE TITLE
Excluded JAX-RS classes are visible in openapi

### ISSUE THREAD

**Issue by Legion2** [quarkusio/quarkus#16218]
## Describe the bug
When JAX-RS classes are excluded via `@IfBuildProfile` (#15215), it is still visible in the generated openapi document.

### Expected behavior
When a JAX-RS class is excluded from the current build via an `IfBuildProperty` annotation (or similar), it should also be excluded from openapi document generation.

### Actual behavior
The endpoints of the JAX-RS class are visible in openapi and swagger, but can not be called.

## To Reproduce

1. Create a JAX-RS class
2. include `quarkus-smallrye-openapi` extension
3. add `@IfBuildProfile("foo")` to the class
4. run in dev mode
5. open swagger ui
6. see that the JAX-RS class is visible

### Quarkus version or git rev
`1.13.0.Final`

**Comment by MikeEdgar** [comment]
Should a class disabled in the build with this annotation be also excluded from the Jandex index or is it needed there for other purposes?

**Comment by phillip-kruger** [comment]
@geoandri maybe you can help ? When a `@IfBuildProfile` is present, will the class be removed from the Jandex index ?

**Comment by geoandri** [comment]
Hi @phillip-kruger , I think that you meant to mention @geoand .

**Comment by phillip-kruger** [comment]
Yes I did, sorry :)

**Comment by geoand** [comment]
> @geoandri maybe you can help ? When a `@IfBuildProfile` is present, will the class be removed from the Jandex index ?

They will not be removed from the Jandex index. They are only removed from Arc

**Comment by phillip-kruger** [comment]
Thanks, that is the problem then. We look at jandex when we build the schema. So we will have to build in something specific for this case...

**Comment by geoand** [comment]
Let me know if you need anything from me

**Comment by phillip-kruger** [comment]
Thanks, will do
