### ISSUE TITLE
Flyway initSql support

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#16226]
## Description
Flyway has an initSql property to specify sql to run. This is useful e.g. for selecting a role in PostgreSQL to use for the migration. This is beneficial if you use vault generated users who also need to update schemas. Currently it cannot be specified in the extension configuration. I think it would be a good addition.

**Comment by srisatya1197** [comment]
Is the issue was assigned or can I work on this Sir?

**Comment by geoand** [comment]
You can work on it if you like

**Comment by srisatya1197** [comment]
Sure Sir

**Comment by gastaldi** [comment]
@srisatya1197 hey, I just saw the conversation now. I needed this feature so I provided a PR, hope you don´t mind? 😃

**Comment by srisatya1197** [comment]
@gastaldi No worries Sir.
