### ISSUE TITLE
Quarkus-mongodb-panache -- embedded object

### ISSUE THREAD

**Issue by yoobi** [quarkusio/quarkus#16222]
## Describe the bug
Hello! I'm new to quarkus and trying to build a REST API with it for the fun, I'm trying out "io.quarkus:quarkus-mongodb-panache" but I'm unable to find a solution for this simple use-case
I've been reading this nice [article](https://quarkus.io/guides/mongodb-panache) but didn't find anything related to my issue

```kotlin
interface ZooModel {
    val id: ObjectId
        get() = ObjectId.get()
    val address: Address
    val name: String
}


@MongoEntity(collection = "zoo")
class Zoo @BsonCreator constructor(
    @BsonId
    override val id: ObjectId = ObjectId.get(),

    @BsonProperty("name")
    override val name: String,

    @BsonProperty("address")
    override val owner: Address,
): ZooModel, PanacheMongoEntityBase()
```
My issue here is that the `Address` is a `data class` that is provided by a third-party library  so I can't add `PanacheMongoEntity` to it so I'm getting the following error:
```
org.bson.codecs.configuration.CodecConfigurationException: Cannot find a public constructor for 'Address'.
```

### Configuration
```properties
    implementation(kotlin("stdlib-jdk8"))
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-resteasy-jackson")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-resteasy")
    implementation("io.quarkus:quarkus-mongodb-panache")

    testImplementation("io.quarkus:quarkus-junit5")
```

**Comment by loicmathieu** [comment]
Hi,

```
org.bson.codecs.configuration.CodecConfigurationException: Cannot find a public constructor for 'Address'.
```

So this is a typical issue with Kotlin Data classes and the MongoDB POJO codec that MongoDB with Panache uses. There is some explaination on the MongoDB with Panache guide: https://quarkus.io/guides/mongodb-panache#working-with-kotlin-data-classes

As the `Address` class is provided in a third party library, you cannot annotate the construcotor nor configure the no-arg kotlinc plugin to generate an empty default constructor. In this cas you need to create a Mongo Codec for the `Address` class, it will be automatically detected by Quarkus, see https://quarkus.io/guides/mongodb#simplifying-mongodb-client-usage-using-bson-codec
