### ISSUE TITLE
Datadog tracer

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkusio/quarkus#16234]
## Describe the extension

The purpose of this extension is to provide native support to the Datadog tracer implementation for open tracing (using Datadog official dd-java-ot and dd-java-api jars)

### What / who this extension is for

- people who are interested in migrating their java stack to Quarkus native, but cannot due to their dependence on Datadog for the tracing and the [reasons mentioned here](https://github.com/quarkusio/quarkus/issues/15182).
- people who do not want to move on open telemetry (yet)
- hopefully a temporary solution until Datadog provide full support for open telemetry's features in their exporter (especially the metrics and logs)
- will support report of trace & span id in logs for correlation purpose
- will support all [official configuration properties documented by datadog here](https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers), either from quarkus configuration and/or environment variables (environment variables override properties)

### What / who this extension is not for

- a replacement to open telemetry as for the tracing part
- a long term solution

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
```properties
# default true, to activate/deactivate the extension at build time
quarkus.datadog.enabled=true/false
# default true, to activate/deactivate correlation through logs at runtime
quarkus.datadog.logs.injection=true/false
# all official datadog configuration properties, as string values
quarkus.datadog.xx.yy=zzz 
```

## Additional context

The extension is already developed, hosted on a private repository and used internally on different projects in production.
I just want to share it to the community until Datadog offer a more complete support on open telemetry.

This extension should belongs to the Quarkiverse Hub if accepted

I'm of course interested in leading the development of this extension as it's already done.

**Comment by kenfinnigan** [comment]
Agree it makes sense for this to be added to Quarkiverse

**Comment by ebullient** [comment]
Would be nice if I could get a review for the datadog micrometer registry support as a bonus. ;)

**Comment by nicolas-vivot** [comment]
Do you have an idea when this extension would be approved ?

Just to know if it's still doable before end of April as i'm going to be quite busy from May.

@ebullient 
When using the statsD registry, i found the name of the JVM metrics does match what datadog is expecting and therefore count these metrics as custom metrics. (potential increase of the billing depending on your subscription plan and your infrastructure) 
Due to this naming issue, metrics sent are not used by the pre-made JVM dashboard / views in datadog products (monitoring, APM, RUM)
I exchanged with them about that and they are not planning to do anything about it.

I will give a try to the datadog registry this afternoon but i'm afraid i would face a similar issue.

**Comment by kenfinnigan** [comment]
@ebullient I think it would be confusing to have a Datadog OpenTracing extension in amongst OpenTelemetry extensions. It's probably best in a separate repo.

**Comment by fiorenzino** [comment]
@nicolas-vivot waiting a Quarkiverse repository,  can you share your actual repository, to see your code?

**Comment by nicolas-vivot** [comment]
@fiorenzino Unfortunately for now, as explained in the first post, my extension is hosted on a private repository owned by my actual company. The code also refers to the company names (artifacts, group id, package names) so i'm not going to share it.

I was thinking to wait for the repository to be available as it would automatically includes the correct names from the prepared structure, and then just rename my packages to fit quarkiverse instead of my company naming conventions.

I'll try to find the time this week to migrate it in a personal repository so that you can access it without waiting for the official quarkiverse repo.

**Comment by fiorenzino** [comment]
@nicolas-vivot no news about your datadog example in quarkus? i'm trying, also watching your examples project on github, but without success. Using the java agent, in the docker image, i'm not capable to add on the logs the traceId..

**Comment by nicolas-vivot** [comment]
@fiorenzino Sorry i'm super buzzy these days in my job. Let me quickly upload that on my projects by tomorrow.

**Comment by fiorenzino** [comment]
@nicolas-vivot if you want share privately part of code (fiorenzino AT Gmail)

**Comment by nicolas-vivot** [comment]
@fiorenzino I invited you to a private repository so that you have access to the extension code.

Feel free to report an problem you have directly there.

Note: i've seen you're interested in the log correlation. The extension is using the json logging extension and this one output the MDC context as a sub objected called 'mdc' in logs. So you'll have to create a TraceId re-mapper rules in your datadog account where logs are shipped to so that datadog will use the trace_id / span_id from the mdc structure.
![image](https://user-images.githubusercontent.com/79290619/115633288-ab7a7e00-a343-11eb-9cfd-85bb5d430335.png)

**Comment by nicolas-vivot** [comment]
@Ladicek @kenfinnigan Any ideas when the extension repository will be available ?

Is there anything special i need to know to make my extension compliant with version 2.0 of Quarkus ?

**Comment by Ladicek** [comment]
I don't know anything about the process around Quarkiverse extensions, or if there's any. I know @gastaldi is involved, so pinging him :-)

(Also CC @gsmet -- wouldn't it make sense, for the Quarkus bot, to ping Quarkiverse people on issues labeled `kind/extension-proposal`?)

**Comment by nicolas-vivot** [comment]
Oh ok sorry about that.

@gastaldi Could you please have a look at this proposal ? :)

**Comment by gastaldi** [comment]
Thanks for the ping, @Ladicek :)

@nicolas-vivot no worries, I'll create a repository to get you started. Are you comfortable in being the lead maintainer of this extension?

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-datadog-opentracing with a sample code and invitation to join the team sent. Let me know if you need any assistance.

**Comment by nicolas-vivot** [comment]
@gastaldi Thank you very much ! No problem being the lead maintainer.
