### ISSUE TITLE
Missing Hazelcast logs after change #15636

### ISSUE THREAD

**Issue by mincel** [quarkusio/quarkus#16239]
## Describe the bug
We use Hazelcast embedded in one of our projects. After upgrading to 1.13.0.Final version we get `"LogManager error of type WRITE_FAILURE: The delayed handler's queue was overrun and log record(s) were lost. Did you forget to configure logging?"` during server startup. All Hazelcast startup logs are lost. I suspect it is related to change https://github.com/quarkusio/quarkus/pull/15636.

Hazelcast is initialized in a producer method. I added some logging into this producer method to see if they are printed however those logs get lost as well.

PS: When I start the project in `dev` mode the logs are printed correctly.

**Comment by gsmet** [comment]
FWIW, I also had the warning when I upgraded Quarkus in an app. Just downloading the new artifacts triggered it.

I think we need to rethink this or at least have a discussion about it.

/cc @geoand @stuartwdouglas

**Comment by geoand** [comment]
This one seems to the gift that keeps on giving

**Comment by jaikiran** [comment]
The GitHub Action CI logs for Quarkus have a lot of this specific WARN message for a while now. I haven't had the time or chance to check if this was just because of the way the tests are written/run or some genuine issue.

**Comment by gsmet** [comment]
@mincel any chance you could prepare a small reproducer? I'd like to have a look with an example.

In the meantime, I think we need to revert this patch for 1.13.1.

**Comment by gsmet** [comment]
I wonder if it's recording all log levels thus leading to us collecting a ton of records.
