### ISSUE TITLE
@UnlessBuildProfile not working as expected

### ISSUE THREAD

**Issue by rareddy** [quarkusio/quarkus#16243]
## Describe the bug
When @UnlessBuildProfile used on @ApplicationScoped bean, there are a couple of issues I am seeing. 

1. When you build a profile that does not match to the annotation, even in that profile the bean is available.
2. When the bean is available it does not do the @inject operations correctly.

for example, I have @UnlessBuildProfile("prod"), and when building the prod I still see the bean available. I could verify that because in my case it is rest controller.

### Expected behavior
The bean be not available

## To Reproduce
```
@ApplicationScoped
@UnlessBuildProfile("prod")
@Path("/")
public class MockControlPlane {

  public String hello(){
     return "hello";
  } 
}
```

build with `-Dquarkus.profile=prod`

**Comment by FroMage** [comment]
CC @mkouba

**Comment by FroMage** [comment]
Actually, I wonder if this is not a combination of RESTEasy scanning and taking over discovery because CDI would not claim that bean?

**Comment by mkouba** [comment]
> Actually, I wonder if this is not a combination of RESTEasy scanning and taking over discovery because CDI would not claim that bean?

Yes, I think so. The bean is not registered but there's a fallback used in the [QuarkusInjectorFactory](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-common/runtime/src/main/java/io/quarkus/resteasy/common/runtime/QuarkusInjectorFactory.java) that just creates the resource instance via `new MockControlPlane()` and that's why CDI injection does not work there.

**Comment by mkouba** [comment]
TBH I'm not sure what the correct behavior would be but I think that the fallback is there since the beginning (and an "invisible" DEBUG message is logged).

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
Yeah, I think what you guys mention is what is going on

**Comment by FroMage** [comment]
So perhaps RESTEasy Classic and Reactive should both special-case `@UnlessBuildProfile`?

**Comment by geoand** [comment]
That will likely be needed

**Comment by geoand** [comment]
This actually should be working as we have merged: https://github.com/quarkusio/quarkus/pull/15215

**Comment by rareddy** [comment]
I am using `1.11.1.Final` version of Quarkus if the above is after that I would need validate with a newer release

**Comment by geoand** [comment]
OK, that explains it then, as I just tried with the latest and it works
