### ISSUE TITLE
The usage of 8081 by tests must be documented

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus#1627]
The default tests are not working with v0.12.0

Steps to reproduce:

1. Create a default Quarkus project

```shell
     mvn io.quarkus:quarkus-maven-plugin:0.12.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=application-configuration \
    -DclassName="org.acme.config.GreetingResource" \
    -Dpath="/greeting"
```

2. do `./mvnw clean test` or `mvn clean test`

## Expected Behaviour 

Tests should pass 

## Actual Behaviour

Tests failed with error 

```
java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.
```

## More details:

If you notice startup logs of the test run, the quarkus server is started with IPv6 address like **Listening on: http://[::]:8081**

```
Mar 22, 2019 12:15:00 AM io.quarkus.deployment.QuarkusAugmentor run
INFO: Beginning quarkus augmentation
Mar 22, 2019 12:15:00 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Alpha4
Mar 22, 2019 12:15:01 AM io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 1065ms
Mar 22, 2019 12:15:01 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.0.Final
Mar 22, 2019 12:15:01 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.0.Final
Mar 22, 2019 12:15:01 AM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 0.12.0 started in 0.462s. Listening on: http://[::]:8081
Mar 22, 2019 12:15:01 AM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [cdi, resteasy]
```

This requires the RestAssured to be configured with proper baseURI, like 

```java
 @BeforeEach
  public void setURL() {
    RestAssured.baseURI = "http://[::1]:8081";
  }
```

not sure if the app should default to IPv6 or IPv4, if IPv6 is correct then we need to update the test cases and quickstarts to this behaviour

@cescoffier , @stuartwdouglas

**Comment by geoand** [comment]
I could not reproduce this... I tried both with JDK 8 and JDK 11 and got

```
[INFO] Running org.acme.config.GreetingResourceTest
2019-03-21 22:58:19,004 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-03-21 22:58:19,597 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 593ms
2019-03-21 22:58:19,832 INFO  [io.quarkus] (main) Quarkus 0.12.0 started in 0.221s. Listening on: http://[::]:8081
2019-03-21 22:58:19,832 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.974 s - in org.acme.config.GreetingResourceTest
2019-03-21 22:58:20,955 INFO  [io.quarkus] (main) Quarkus stopped in 0.005s
```

Could you please give us the output of `mvn -version`?

**Comment by n1hility** [comment]
Is there another process on your box that is listening to localhost 8080?, that would cause the later any bind to succeed yet not answer that port. The 404 instead of a connection refused would support that.

**Comment by kameshsampath** [comment]
@n1hility  @geoand  - i have a local nexus running in 8081. 

thats why I see QuarkusTest is starting the app with IPv6 on 8081 ?

**Comment by kameshsampath** [comment]
after discussing with @stuartwdouglas , I tried adding `quarkus.http.test-port` to the surefire test to change the port where  test will start and that seem to work. Wondering if I need to close this issue or its good to keep to add this trick in doc. Worth adding a test guide to the main repo ?

**Comment by cescoffier** [comment]
The testing doc should be updated. I will open a PR.
