### ISSUE TITLE
JGraphT extension proposal for quarkiverse

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#16270]
I played with JGraphT(https://jgrapht.org/) during the Easter holiday and it works well in JVM mode and reasonably well in native mode.

GraphML Import/Export is where I hit issues in native mode. I have `quarkus-jgrapht` WIP extension code that 
addresses import/export issues.

I would like to share that extension as part of https://github.com/quarkiverse/quarkus-jgrapht.

Is quarkus-jgrapht extension acceptable for quarkiverse ecosystem? If yes, could you please initiate https://github.com/quarkiverse/quarkus-jgrapht repository?

**Comment by gastaldi** [comment]
@rsvoboda yes, that library is awesome, we use it in JBoss Forge. I'll set up a repository for you

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-jgrapht with a sample code. Enjoy!
