### ISSUE TITLE
Support for opentracing-jdbc without the need to provide jdbc url

### ISSUE THREAD

**Issue by typekpb** [quarkusio/quarkus#16299]
## Describe the bug
Currently, to integrate quarkus with opentracing-jdbc, there is a need to (based on https://quarkus.io/guides/opentracing) provide config props like:
```
quarkus.datasource.db-kind=postgresql
# add ':tracing' to your database URL
quarkus.datasource.jdbc.url=jdbc:tracing:postgresql://localhost:5432/mydatabase
# use the 'TracingDriver' instead of the one for your database
quarkus.datasource.jdbc.driver=io.opentracing.contrib.jdbc.TracingDriver
# configure Hibernate dialect
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
```

However in the quarkusDev it's not optimal, as I'm not able to use auto-created postgres container (just by including the `quarkus-jdbc-postgresql` dependency, as I'm forced to  override the jdbc url. Would it rather be possible to use the opentracing-jdbc in the inerceptor mode (https://github.com/opentracing-contrib/java-jdbc#interceptor) in case jdbc-url is not provided?

**Comment by loicmathieu** [comment]
We will need an extension for this, and I'm not sure it will be compatible in native as it must use some kind of dynamic instrumentation.

**Comment by radcortez** [comment]
We added support for this in the OTel JDBC Driver: https://github.com/quarkusio/quarkus/pull/24321

Since the idea is to move forward with OTel and drop OpenTracing, I'll close this issue.
