### ISSUE TITLE
Liquibase includeAll does not work in native mode

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#16292]
This is a follow-up to #14751 which contains all the necessary info, especially https://github.com/quarkusio/quarkus/issues/14751#issuecomment-808919081

Short story: includeAll was fixed for JVM mode by upgrading to Liquibase to 4.3.2 but the classpath resource scanning in Liquibase needs some adjustments (in Quarkus) to make it work in native.

**Comment by geoand** [comment]
Do we have an example application where this isn't working?

Or some easy way to reproduce it?

**Comment by famod** [comment]
Two options to reproduce:
- run the IT from #16293 (and flip that flag)
- use the sampleproject from #14751 (which is about JVM mode, so native bits have to be added)

**Comment by geoand** [comment]
So I had a quick look at this one, and it seems that the way `includeAll` works (which is by reading the contents of the actual directory file), does not work well in GraalVM.
I even tried registering the directory as a resource (which worked with a small fix in Quarkus), but that still didn't do the trick.

So if we want to make this work, we'll need to change the Liquibase implementation to **not** open the directory as a stream, but instead I guess filter the files the file systen

**Comment by famod** [comment]
Thanks for looking into this @geoand! I had a feeling that it would turn out this way.

@nvoxland would you be open to making Liquibase more GraalVM friendly?
If yes we would create an upstream issue to track this.

**Comment by famod** [comment]
FTR, liquibase 4.6.0 tightened the validation in that `errorIfMissingOrEmpty` is now set to `true` by default, causing a hard failure (directory not found).
See also: https://github.com/quarkusio/quarkus/pull/24487#discussion_r832709276

**Comment by JeremyLeriche** [comment]
Still not working with 2.16.5.Final
Dev and JVM mode ok but not with native apps.
Is there any bypass ?

**Comment by geoand** [comment]
Is this still an issue in the latest versions of Quarkus?

**Comment by famod** [comment]
Just checked the IT on main - still an issue, unfortunately.

**Comment by geoand** [comment]
😢

Thanks for checking
