### ISSUE TITLE
CLI: consider autocomplete support via TAB

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#16318]
I believe that most of the CLI users are used to use this feature.

See https://picocli.info/autocomplete.html.

**Comment by TomasHofman** [comment]
@mkouba can I take a look at this?

I think we could add a `qs completion [bash|zsh]` command, that would generate the bash completion script, similarly like `oc completion` does.

**Comment by mkouba** [comment]
@TomasHofman Yep, it seems that we can try to reuse the built-in [subcommand](https://picocli.info/autocomplete.html#_distribution).

**Comment by ebullient** [comment]
I have this in my draft PR already (that we can test). 
Note: the draft PR has isolated/stopped calling the pieces that do any actual work (so we can focus on command structure and make sure dumb things like --help are performant, which they should be, as they don't need to touch anything requiring any loading of resources). 

Will add function back once we settle #16033 

https://github.com/quarkusio/quarkus/pull/16407
