### ISSUE TITLE
Quarkus 1.13.0 with Jacoco include test classes in report

### ISSUE THREAD

**Issue by hyper-ricardo** [quarkusio/quarkus#16323]
## Describe the bug
With a Quarkus 1.13.0 Gradlew project and the quarkus-jacoco extension, classes from src/test/resources are included in the Jacoco report.
Event with this property in the application.yml

```yml
quarkus:
  jacoco:
    excludes:
      - "*Test"
```

### Expected behavior
No test classes from src/test/java should be included in the Jacoco raport

### Actual behavior
Test classes from src/test/java are included in the Jacoco report

## To Reproduce

https://github.com/hyper-ricardo/quarkus-jacoco-test

1. ./gradlew clean build
2. open build/jacoco-report/index.html
3. see that GreetingResourceTest is present

![image](https://user-images.githubusercontent.com/23709368/113876836-69383500-97b8-11eb-9146-f714d7642d51.png)

### Output of `uname -a` or `ver`
Darwin hyper 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev
1.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Mac OS X 10.16 x86_64

**Comment by geoand** [comment]
cc @stuartwdouglas
