### ISSUE TITLE
Incorrect micrometer metrics for http method OPTIONS

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#16329]
## Describe the bug
The method="OPTIONS" request creates a separate counter for each path parameter instead of combining them.

### Expected behavior
Metrics should look like follow:

`
http_server_requests_seconds_max{,method="POST",outcome="SUCCESS",status="204",uri="/api/alerts/{alertId}",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/{alertId}",} 0.0
`

### Actual behavior
For get/post-request it's ok, but not for options (cors preflight)
`
http_server_requests_seconds_max{method="POST",outcome="SUCCESS",status="204",uri="/api/alerts/{alertId}",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8676",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8586",} 0.0
http_server_requests_seconds_max{method="OPTIONS",outcome="SUCCESS",status="200",uri="/api/alerts/8631",} 0.0
`

## To Reproduce

Send an OPTIONS request to any http endpoint with path variables

### Quarkus version
1.12.2.Final

**Comment by ebullient** [comment]
Thanks for opening this. You can use a configuration match pattern to correct this condition while you wait for an official fix.
https://quarkus.io/guides/micrometer#quarkus-micrometer_quarkus.micrometer.binder.http-server.match-patterns

**Comment by ebullient** [comment]
Can you send me a sample/reproducer application? I'd like to see how you're declaring the OPTIONS handler..

**Comment by joggeli34** [comment]
By trying to reproduce it, it only happend when I added the `quarkus-undertow-websockets` extention. Otherwise I couldn't reproduce it and always got `uri="root"` as metric which is also ok.
It's even fixed with `quarkus-websockets`

**Comment by ebullient** [comment]
if you have cors enabled (and are looking for preflight checks) you'll see this. If you want to try the PR, that should make the preflight checks all come under /cors-preflight (which is a more accurate representation of what they are.. )
