### ISSUE TITLE
Ability to detect podman when creating container output

### ISSUE THREAD

**Issue by ajhajj** [quarkusio/quarkus#16326]
I have noticed that:

`./mvnw package -Pnative -Dquarkus.native.container-build=true`

will detect either docker or podman and use accordingly.  However:

`./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true`

requires the presence of docker unless I explicitly specify '`-Dquarkus.native.container-runtime=podman`'.  This feels like inconsistent behavior.  Can we see about detecting podman for the container image build as we do for the native build?

**Comment by geoand** [comment]
Can you explain which part of the build requires docker?

Some logs for the second case would be helpful

**Comment by ajhajj** [comment]
It seems that if I want to create a container output as documented in https://quarkus.io/guides/building-native-image#creating-a-container.  There it mentions a dependency on container-image extensions (https://quarkus.io/guides/container-image).  There are three as I understand it.  But for usecases outside of OpenShift just jib and docker.  Unfortunately jib also requires docker in some cases as indicated by: 
"In situations where all that is needed to build a container image and no push to a registry is necessary (essentially by having set quarkus.container-image.build=true and left quarkus.container-image.push unset - it defaults to false), then this extension creates a container image and registers it with the Docker daemon. This means that although Docker isn’t used to build the image, it is nevertheless necessary. Also note that using this mode, the built container image will show up when executing docker images."

The build output shows no errors in this case but no image is produced .  The output of the run is below:

 ☕ [ajhajj@laptop insult]$ ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< com.redhat:jsp >---------------------------
[INFO] Building jsp 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.2.Final:generate-code (default) @ jsp ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jsp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jsp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.2.Final:generate-code-tests (default) @ jsp ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jsp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ajhajj/dev/quarkus_servlet/workspace/insult/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ jsp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ jsp ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jsp ---
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.2.Final:build (default) @ jsp ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/ajhajj/dev/quarkus_servlet/workspace/insult/target/jsp-1.0.0-SNAPSHOT-native-image-source-jar/jsp-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/ajhajj/dev/quarkus_servlet/workspace/insult/target/jsp-1.0.0-SNAPSHOT-native-image-source-jar/jsp-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using podman to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11
Trying to pull quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11...
Getting image source signatures
Copying blob 0f7eddd60d0a skipped: already exists  
Copying blob 57de4da701b5 skipped: already exists  
Copying blob cf0f3ebe9f53 [--------------------------------------] 0.0b / 0.0b
Copying config 31ccea2b17 done  
Writing manifest to image destination
Storing signatures
31ccea2b17aeb3f2f1d2ab187da9c78b7e7f1ab135a44bff982f0baef86026ab
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar jsp-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace jsp-1.0.0-SNAPSHOT-runner
[jsp-1.0.0-SNAPSHOT-runner:20]    classlist:   2,070.22 ms,  0.93 GB
[jsp-1.0.0-SNAPSHOT-runner:20]        (cap):     600.59 ms,  0.93 GB
[jsp-1.0.0-SNAPSHOT-runner:20]        setup:   2,022.48 ms,  0.93 GB
18:09:39,691 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[jsp-1.0.0-SNAPSHOT-runner:20]     (clinit):     441.29 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]   (typeflow):  11,632.88 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]    (objects):  10,180.57 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]   (features):     494.57 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]     analysis:  23,800.20 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]     universe:   1,098.65 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]      (parse):   2,565.99 ms,  2.67 GB
[jsp-1.0.0-SNAPSHOT-runner:20]     (inline):   4,631.73 ms,  4.31 GB
[jsp-1.0.0-SNAPSHOT-runner:20]    (compile):  18,882.17 ms,  5.54 GB
[jsp-1.0.0-SNAPSHOT-runner:20]      compile:  27,471.61 ms,  5.54 GB
[jsp-1.0.0-SNAPSHOT-runner:20]        image:   2,665.42 ms,  5.54 GB
[jsp-1.0.0-SNAPSHOT-runner:20]        write:     543.36 ms,  5.54 GB
[jsp-1.0.0-SNAPSHOT-runner:20]      [total]:  60,129.22 ms,  5.54 GB
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 64882ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2021-04-08T14:10:25-04:00
[INFO] ------------------------------------------------------------------------

**Comment by ajhajj** [comment]
I updated my previous comment as I had forgotten to enable the jib extension on my first run output.

**Comment by ajhajj** [comment]
The fact that it will automatically register with the local docker registry if a remote registry is not provided but not do the same for podman is the issue I am trying to describe really.

**Comment by geoand** [comment]
OK, thanks for the information.

As implied by the names of the different properties, (`quarkus.native.container-runtime` and `quarkus.native.container-build`) these are two different things.
So although I understand you would like to use `podman` throughout, these are two different things, so you would need to configure the registry (`-Dquarkus.container-image.registry=....`) to do what you want.

**Comment by ajhajj** [comment]
I agree that they are different.  My concern was the overall consistency of user experience.  Maybe that is something we can consider down the road some time.

**Comment by geoand** [comment]
Yes, that is a good point.

Maybe we could introduce some global setting.

WDYT @zakkak, @gsmet ?

**Comment by zakkak** [comment]
+1 being able to define the container engine globally (or even better detect it automatically) would be nice. 

I have only tried podman with `container-image-docker` though, so I am not sure how it would work with JIB and S2I.

**Comment by andrewazores** [comment]
There is also the [`dockerClient.executable`](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#dockerclient-closure) config property that Jib supports which I think might be relevant here. If it is not then I think that a separate issue could be opened to add support for this to the `quarkus-container-image-jib` build plugin as `quarkus.jib.dockerClient.executable=/usr/bin/podman`. I use this in [Cryostat](https://github.com/cryostatio/cryostat/blob/5394bd47bf9aa911f157e5c60467e32b537a47b0/pom.xml#L577) to default the image builder to `podman`, but allow it to be overridden if some developer needs that to be `docker` (or probably `buildah` too - haven't tried that yet).

**Comment by geoand** [comment]
Best open a new issue for this.

**Comment by geoand** [comment]
I am going to close this because https://github.com/quarkusio/quarkus/pull/24238 will introduce the same detection method we have for the native binary using container build into our Jib support
