### ISSUE TITLE
Qute example not working in firefox

### ISSUE THREAD

**Issue by XakepSDK** [quarkusio/quarkus#16336]
## Describe the bug
When clicking `Generate new quark`, Firefox fails to execute POST request with error `NS_BINDING_ABORTED`
Works in Chromium

### Expected behavior
New item added

### Actual behavior
POST request fails, no new item added

## To Reproduce
1. Create quarkus project with Qute
2. Open example page
3. Click on `Generate new quark`

### Configuration
Nothing changed; default config from project generator

## Environment (please complete the following information):
Firefox 88.0.b8

### Quarkus version or git rev
1.13.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven

**Comment by mkouba** [comment]
Works fine with Firefox 87.0 (64-bit). 88.0.b8 is a developer edition, right? 

@XakepSDK Could you try to dump the response headers received from the server?

**Comment by XakepSDK** [comment]
Works with FF 87; It's firefox beta bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1673534
