### ISSUE TITLE
Unit Testing Quarkus with quarkus-smallrye-openapi causing InvalidDefinitionException Java 8 date/time type `java.time.LocalDate` not supported

### ISSUE THREAD

**Issue by mukhtarhussainbaloch** [quarkusio/quarkus#16343]
## Describe the bug
When `quarkus-smallraye-openapi` dependency is included in pom.xml, Unit Test having POJO's with LocalDate type variable fail with "com.fasterxml.jackson.databind.exc.InvalidDefinitionException:"
### Expected behavior
Unit Test should run without exception and objects having LocalDate type should marshal and unmarshal without any problem.
### Actual behavior
Unit Test fail with exception 
> 
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Java 8 date/time type `java.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
 at [Source: (String)"{"dob":"2019-04-04","id":10,"name":"abc"}"; line: 1, column: 8] (through reference chain: org.acme.Person["dob"])
        at org.acme.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.java:18)

## To Reproduce

1. Generate a basic Quarkus application from quarkus website. Inlude `quarkus-resteasy-jsonb`, `quarkus-smallrye-openapi`, `quarkus-resteasy`
2. Create a POJO that has a LocalDate type variable and return that POJO as Response with rest endpoint producing MediaType JSON
3. Write a unit test to hit the rest endpoint and extract the POJO.

### Configuration
```properties
# Add your `application.properties` here, if applicable.

```

### Output of `java -version`
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)

### GraalVM version (if different from Java)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
### Quarkus version or git rev
1.13.0.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T20:06:16+05:00)
Maven home: C:\Users\CS Dept\scoop\apps\maven\3.6.2\bin\..
Java version: 11.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
## Additional context
The program executes correctly when executed with **mvnw compile quarkus:dev**

**Comment by geoand** [comment]
Thanks for reporting.

Can you please attach a reproducer project to the issue?

**Comment by mukhtarhussainbaloch** [comment]
https://github.com/mukhtarhussainbaloch/quarkus-smallrye-openapi-bug

**Comment by geoand** [comment]
Things work properly if you switch from `quarkus-resteasy-jsonb` to `quarkus-resteasy-jackson`

**Comment by Manfred73** [comment]
I'm also experiencing the above error and I'm using both `quarkus-resteasy-reactive` and `quarkus-smallrye-openapi` dependencies in my pom. I only get this error when running integration tests against native build:

Resource:
```
@GET
@Produces(MediaType.APPLICATION_JSON)
public ResponseResult<MyModel> determineFine(@BeanParam @Valid final FineParams params) {
    final var fine = myService.determineFine(params);
    return ResponseResult.<MyModel>builder().result(fine).build();
}
```

FineParams:
```
@Getter
@Setter
public class FineParams {

    @RestQuery("startDate")
    @NotNull
    private LocalDate startDate;
}
```

When a request is sent, I see an error in the log:
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
```

I have tried adding @RegisterForReflection to the `FineParams` class. Also tried adding dependency `jackson-datatype-jsr310` and adding annotations `@JsonSerialize(using = LocalDateSerializer.class)` and `@JsonDeserialize(using = LocalDateDeserializer.class)` to the `startDate`. But that didn't help.

According to https://quarkus.io/guides/rest-json the above should work out-of-the-box without having to add any additional dependencies or configuring ObjectMapper?

**Comment by Manfred73** [comment]
To answer my own question:

There is nothing wrong with the above and it's working fine.
The error seems to come from somewhere else from our own StructuredLogging library which doesn't handle the LocalDate well.
