### ISSUE TITLE
Kmongo for Quarkus

### ISSUE THREAD

**Issue by yoobi** [quarkusio/quarkus#16354]
## Describe the extension
[Kmongo](https://litote.org/kmongo/) is a really good toolkit for mongo on Kotlin

it supports aggregation and lookup which panache don't.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
```properties
# Add your application.properties here, if applicable.
quarkus.mongodb.connection-string=URL
quarkus.mongodb.database=database
```

## Additional context
(Add any other context about the proposal here.)

**Comment by geoand** [comment]
Sounds like a candidate for the Quarkiverse

**Comment by loicmathieu** [comment]
We aready have a MongoDB with Panache extension for Kotlin (not yet documented) so our prefered way to simplify MongoDB with Kotlin is to use this one.

Note that as Kmongo uses extension method it should not need a tight integration with Quarkus so it should works easily on JVM mode with ou Quarkus MongoDB Client extension. Not sure for native mode.

**Comment by yoobi** [comment]
I have tried using Panache and it's nice for simple query, right now I'm trying to do aggregation, lookup and such but Panache doesn't support this, then it's mandatory going back and forth between mongodb-client and panache while Kmongo can do everything Panache does and more.

**Comment by evanchooly** [comment]
I'm going to make the executive decision to close this as won't fix. We have not only panache support but also [quarkiverse-morphia](https://github.com/quarkiverse/quarkus-morphia/) for a more robust ODM solution. While community contributions are always welcome, this isn't one the quarkus team will pursue at this point.
