### ISSUE TITLE
LegacyNamedMongoClientConfigTest is flaky

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#16369]
Seen this fail multiple times in the last days, e.g. https://github.com/quarkusio/quarkus/pull/16367/checks?check_run_id=2299302627
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.092 s <<< FAILURE! - in io.quarkus.mongodb.LegacyNamedMongoClientConfigTest
Error:  io.quarkus.mongodb.LegacyNamedMongoClientConfigTest  Time elapsed: 4.092 s  <<< ERROR!
java.util.concurrent.RejectedExecutionException
	at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
	at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2045)
	at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:767)
	at io.smallrye.mutiny.infrastructure.MutinyScheduler$DecoratedRunnableTask.run(MutinyScheduler.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.util.concurrent.RejectedExecutionException: Executor is being shut down
		at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2047)
		... 5 more
```
Further up in the log there are a couple of `ConnectException: Connection refused`, not sure this is expected.

**Comment by loicmathieu** [comment]
@cescoffier you wrote the original tests of the mongodb-client extension, I see that on the integration test we have the following piece of code that are not present in the mongodb-client extension (they didin't use a test resource as they are using QuarkusUnitTest).

```
        try {
            //JDK bug workaround
            //https://github.com/quarkusio/quarkus/issues/14424
            //force class init to prevent possible deadlock when done by mongo threads
            Class.forName("sun.net.ext.ExtendedSocketOptions", true, ClassLoader.getSystemClassLoader());
        } catch (ClassNotFoundException e) {
```

Maybe adding it will avoid such issue ?

Note that for the LegacyNamedMongoClientConfigTest we can also delete the old annotation and this test as they are deprecated for a long time ;)

**Comment by cescoffier** [comment]
Looking at the log it seems that the Mongo process didn't start correctly. I'm actually surprised that only one test failed as there are multiple stack traces.

About the `RejectedExecutionException`, this has been fixed in #16434 .

**Comment by cescoffier** [comment]
@famod @gsmet Did you see that one during the last _few_ days?

**Comment by famod** [comment]
@cescoffier You mean in the last 4 days or so? No, I don't think so.

**Comment by famod** [comment]
@loicmathieu thanks for that info! Closing...
