### ISSUE TITLE
Native image build in docker writes files as root to target dir

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1636]
If you build a native image inside a docker container with `mvn clean package -Pnative -Dnative-image.docker-build=true`  the artefacts are written by root. 

As a result, subsequent commands like `mvn clean` fail, and artifacts can only be removed with `sudo rm`. 

It is possible to run processes in Docker with a different user with the `--user` command line argument, but we will need to find a portable way of running the docker build with the current user id

**Comment by cescoffier** [comment]
I'm surprised by this (don't have this behavior on mac). Are your docker running as root? (can a regular use do something like `docker run ....`)

**Comment by johnaohara** [comment]
afaik docker runs as root by default on linux

**Comment by johnaohara** [comment]
I think docker runs in a virtual machine on mas os, so might not have the same issue

**Comment by johnaohara** [comment]
if i run ` mvn clean package -Pnative -Dnative-image.docker-build=true`

This is the target dir;

```
$ls -la target/
total 26708
drwxrwxr-x 10 user user      4096 Mar 22 05:48 .
drwxrwxr-x  4 user user      4096 Mar 22 05:47 ..
drwxrwxr-x  3 user user        50 Mar 22 05:47 classes
drwxrwxr-x  3 user user        24 Mar 22 05:47 generated-sources
drwxrwxr-x  2 user user      8192 Mar 22 05:47 lib
drwxrwxr-x  2 user user        27 Mar 22 05:47 maven-archiver
drwxrwxr-x  3 user user        34 Mar 22 05:47 maven-status
-rw-rw-r--  1 user user      3693 Mar 22 05:47 quarkus.jar
-rwxr-xr-x  1 root root  27261864 Mar 22 05:48 quarkus-runner
-rw-r--r--  1 user user     55059 Mar 22 05:47 quarkus-runner.jar
drwxr-xr-x  2 root root      4096 Mar 22 05:48 reports
drwxrwxr-x  2 user user         6 Mar 22 05:47 transformed-classes
drwxrwxr-x  6 user user        56 Mar 22 05:47 wiring-classes


```

**Comment by cescoffier** [comment]
So, on linux we would need to pass `--user` to the docker command line

**Comment by cescoffier** [comment]
But if you are on linux, why are you using docker?

**Comment by johnaohara** [comment]
Yes, so we would need to detect we were running on linux and pass in something like `--user $(id -u):$(id -g)`, however I am not sure how portable that would be across distributions and shells.

**Comment by johnaohara** [comment]
good question, but if people run on docker in linux, the build will currently break their maven functionality

**Comment by Sanne** [comment]
@cescoffier I had to use docker to test your images ;)

**Comment by cescoffier** [comment]
@Sanne you got a point :-D

**Comment by johnaohara** [comment]
@cescoffier @Sanne I have created a PR #1810 Not sure about windows build, but will wait on CI to see if it builds on windows

**Comment by johnaohara** [comment]
#1810 fixes this issue
