### ISSUE TITLE
OIDC Issuer Verification

### ISSUE THREAD

**Issue by eddiecarpenter** [quarkusio/quarkus#16384]
The returned issuer value of the authentication provider is compared the configured issuer value and if there is a mismatch the authentication fails. 

The problem I am experiencing is that we are using Microsoft's authentication (Azure) allowing multiple Microsoft tenants to access our system. The Issuer string on their side is defined as https://login.microsoftonline.com/{tenantid}/v2.0 where the {tenantid} is the tenant the user belongs too.  In other word the Issuer is dynamic and cannot be defined at configuration time!

My suggested solutions are:
1. Allow for a best match where only the first bit of the issuer is defined, for example: https://login.microsoftonline.com/
2. Add a configuration flag that mark the verification as optional or alternatively if no issuer is defined ignore the verification process.
3. Added a mechanism similar to the TenantResolver that allows the developer to override the issuer verification process.

Eddie

**Comment by famod** [comment]
/cc @sberyozkin 

PS: not sure I chose the right label

**Comment by sberyozkin** [comment]
@famod it is fine, thanks, I also added `oidc`

**Comment by sberyozkin** [comment]
@eddiecarpenter Hi, what happens if you do not configure `quarkus.oidc.token.issuer` ? i.e, what `issuer` is returned as part of the discovered well-known configuration ?

**Comment by sberyozkin** [comment]
What Quarkus version is it ?

**Comment by eddiecarpenter** [comment]
> @eddiecarpenter Hi, what happens if you do not configure `quarkus.oidc.token.issuer` ? i.e, what `issuer` is returned as part of the discovered well-known configuration ?

**Comment by sberyozkin** [comment]
@eddiecarpenter does it work now :-) ?

**Comment by eddiecarpenter** [comment]
I am using the latest version 1.13.1 :-)

**Comment by sberyozkin** [comment]
@eddiecarpenter 

> If I do not configure the issuer it defaults to https://login.microsoftonline.com/{tenantid}/v2.0

OK, so believe it works now, thanks

**Comment by eddiecarpenter** [comment]
> @eddiecarpenter
> 
> > If I do not configure the issuer it defaults to [https://login.microsoftonline.com/{tenantid}/v2.0](https://login.microsoftonline.com/%7Btenantid%7D/v2.0)
> 
> OK, so believe it works now, thanks
No, it does not work as expected. If I define an issuer with a known tenant-id the mechanism works. As explain above, the problem is that the issuer value return is dynamic and unknown at configuration/startup time.

**Comment by eddiecarpenter** [comment]
My apologies, I somehow click on the wrong link and closed the issue.

**Comment by sberyozkin** [comment]
@eddiecarpenter I'm getting confused - sorry, so why did you close the issue ?

and,

>  https://login.microsoftonline.com/{tenantid}/v2.0

Do you mean the literal `{tenant-id}`, i.e, not `/my-tenant/v2.0`, etc but `{tenant-id}` ? While, when the user is authenticating, you have `/my-tenanr/v2.0`, etc ?

**Comment by sberyozkin** [comment]
@eddiecarpenter OK, np :-)

**Comment by eddiecarpenter** [comment]
> @eddiecarpenter I'm getting confused - sorry, so why did you close the issue ?
> 
> and,
> 
> > If I do not configure the issuer it defaults to [https://login.microsoftonline.com/{tenantid}/v2.0](https://login.microsoftonline.com/%7Btenantid%7D/v2.0)
> 
> Do you mean the literal `{tenant-id}`, i.e, not `/my-tenant/v2.0`, etc but `{tenant-id}` ? While, when the user is authenticating, you have `/my-tenanr/v2.0`, etc ?

Microsoft literally returns  `https://login.microsoftonline.com/{tenantid}/v2.0` in their well known service response, but in the openid OAUTH2 response replaces the {tenantid} tag with actual tenant-id the user/email address belongs too.

**Comment by sberyozkin** [comment]
@eddiecarpenter Got it - thanks. Well, yeah, in this case we can't match it - unless we start going the JAX-RS path and take `tenant-id` as a template var :-), but it would be too messy.... CC @pedroigor

**Comment by sberyozkin** [comment]
@eddiecarpenter Ok, we'll sort it out - in meantime, here is a workaround:

 Set `auth-server-url`, `discovery-enabled=false`, and `jwks-path=/certs` (point to the correct Azure path relative to `auth-server-url`) - and no issuer will be discovered - and the check will be skipped

**Comment by eddiecarpenter** [comment]
> @eddiecarpenter Ok, we'll sort it out - in meantime, here is a workaround:
> 
> Set `auth-server-url`, `discovery-enabled=false`, and `jwks-path=/certs` (point to the correct Azure path relative to `auth-server-url`) - and no issuer will be discovered - and the check will be skipped

Thanks
