### ISSUE TITLE
Possible Leak in quarkus-micrometer on 1.13.0.Final not anymore on 1.13.1.Final

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#16382]
## Describe the bug
If you start 1.13.0.Final with quarkus-micrometer in dev mode, and stop it, some process are not stopped forcing to kill them manually.

It seems to be fixed on 1.13.1.Final, but I thought it wise to be sure the team was aware of this. You can close this if this is under control.

I made a reproducer: https://github.com/ia3andy/reproducer-micrometer-leak

To reproduce:
- Start in dev mode
- Stop
- Start again 
```
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< org.acme:reproducer-micrometer-leak >-----------------
[INFO] Building reproducer-micrometer-leak 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.13.0.Final:dev (default-cli) @ reproducer-micrometer-leak ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Nothing to compile - all classes are up to date
[ERROR] Port 5005 in use, not starting in debug mode
Debugger failed to attach: handshake failed - connection prematurally closed
^C%
```

CC @cescoffier

**Comment by ebullient** [comment]
Yes, we know about this issue.

It was reported in #16130, and fixed by both #16140 (in 1.13.1, this fixes the issue), and #16164 (removes the condition that surfaced the issue, which is in main).
