### ISSUE TITLE
Inconsistent path for @HealthGroup annotations

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16389]
## Describe the bug

For example, having this health check:

```java
@HealthGroup("greeting")
@ApplicationScoped
public class GreetingHealthCheck implements HealthCheck {

    // ...
}
```

According to the javadocs in the `@HealthGroup` annotation (see [here](https://github.com/smallrye/smallrye-health/blob/f33a89959d4e6b21b300f7c536942fd2f0be3da4/api/src/main/java/io/smallrye/health/api/HealthGroup.java#L52)), the path for this Health group should be `/health/greeting`. The problem is that the Smallrye Health Quarkus extension is adding a `group` base path (see [here](https://github.com/quarkusio/quarkus/blob/d513e9b81c244c19bd131ddcbc45b269b87a6da5/extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthConfig.java#L35)). So, the correct path to read our Health group is `/heatlh/group/greeting`.

We should fix the inconsistency and remove the extra `/group` path.

### Quarkus version or git rev
999-SNAPSHOT

**Comment by Sgitario** [comment]
According to the Smallrye Health documentation: https://smallrye.io/docs/smallrye-health/3.0.0/health-groups.html, the right path is `/health/group/{groupName}`, so the property at Quarkus side is correct and we should only amend the comment in the annotations:
https://github.com/smallrye/smallrye-health/pull/286

**Comment by xstefank** [comment]
Sorry, this slipped my radar. I'll look into this.

**Comment by xstefank** [comment]
Yes, wrong Javadoc. This can be closed.

**Comment by Sgitario** [comment]
The PR https://github.com/smallrye/smallrye-health/pull/286 has been merged. Closing.
