### ISSUE TITLE
Micrometer support for undertow-based websockets

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#16396]
The Quarkus websockets extension uses undertow rather than Vert.x. Some glue is required to record metrics for registered websockets.

Either: a hidden conditional feature, or a websocket spi module to allow the micrometer extension (or smallrye-metrics) and eventual opentelemetry extension to probe upgrade/connect/disconnect of websocket connections (with properly templated URIs)

**Comment by gsmet** [comment]
Hmmm. The new websocket extension should use Vert.x, Stuart worked on that specifically.

**Comment by ebullient** [comment]
it does use vertx.. but also still undertow for Java EE prog model semantics.

**Comment by gsmet** [comment]
Maybe I'm missing something but this one shouldn't use Undertow at all: https://github.com/quarkusio/quarkus/tree/main/extensions/websockets/runtime .

But again, maybe I don't understand what you're saying.

**Comment by ebullient** [comment]
It uses the undertow websockets support. It does not use undertow servlets.

**Comment by brunobat** [comment]
Won't do because we have the new websocket.next micrometer instrumentation: https://github.com/quarkusio/quarkus/pull/44379
