### ISSUE TITLE
Regression issue: SmallRye OpenAPI generates incorrect content type when using Spring Web annotations

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#16395]
## Describe the bug
Regression of https://github.com/quarkusio/quarkus/issues/15443.

## To Reproduce
See https://github.com/quarkusio/quarkus/issues/15443

OR

1. `git clone git@github.com:jsmrcka/beefy-scenarios.git && cd beefy-scenarios`
2. `git checkout gh#15443-reproducer`
3. `mvn clean verify -pl 603-spring-web-smallrye-openapi -am`

### Quarkus version or git rev
999-SNAPSHOT

**Comment by phillip-kruger** [comment]
Thanks @jsmrcka - Yes I need to release the 2.1 branch in SmallRye and pull the latest version in Quarkus.

**Comment by gsmet** [comment]
@phillip-kruger I will probably release a 1.13.2 next Wednesday FYI.

**Comment by phillip-kruger** [comment]
Thanks @gsmet.

**Comment by phillip-kruger** [comment]
For Quarkus 2, this will be in SmallRye 2.1.3 (see https://github.com/smallrye/smallrye-open-api/milestone/37?closed=1)
