### ISSUE TITLE
Create an Orika Mapper Extension

### ISSUE THREAD

**Issue by mathianasj** [quarkusio/quarkus#1640]
I would like to create an Orika extension.  Would this be something that should be part of the framework, or would this be better suited to be a standalone item?

**Comment by dmlloyd** [comment]
You can always implement it as a standalone extension as a first step.  I don't know of any drive to have something like this in Quarkus framework itself, but that could always be revisited later if it turns out it's something we really want to have in there.

**Comment by gunnarmorling** [comment]
I'd argue that MapStruct is a much better fit for Quarkus than Orika, as it avoids any sort of reflection to begin with. In fact, it "just works" with Quarkus and native images, without more code changes needed. But I might be biased :)

**Comment by mathianasj** [comment]
I took a quick look and it looks like that would be better, especially since it does not require reflections.
