### ISSUE TITLE
Quarkus Dev Mode: xml resources seems ignored

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#16402]
## Describe the bug
I face a situation where changing an xml resources should trigger a quarkus dev restart while it's not the case.

### Expected behavior
I would expected the dev mode to restart the service.

### Actual behavior
The service is not restarted.

## To Reproduce
git clone git@github.com:aldettinger/quarkus-devmode-restdsl-not-reloaded-reproducer.git
mvn quarkus:dev
http :8080/steps (output STEP 1 => ok)
In rests.xml, change "STEP 1" to "STEP 2" and save
http :8080/steps (output STEP 1 => ko)

Sometimes, no change is detected.
Sometimes, it displays "Files changed but restart not needed - notified extensions".
While any change in application.properties make the application reloaded which is great.

Is is possible that an xml resource always trigger reload like an application.properties file ? Via configuration ? Via an extension that would mark this file as restartNeeded ?

The closest issue I found is https://github.com/quarkusio/quarkus/issues/16350, but not sure there is a link.

**Comment by famod** [comment]
Have you tried https://quarkus.io/guides/maven-tooling#quarkus-live-reload-live-reload-config_quarkus.live-reload.watched-resources ?

**Comment by aldettinger** [comment]
Many thanks @famod , it works like a charm to set it via configuration :+1: 
Now, I wonder what would be the correct way to handle this from an extension, maybe having an extension adding configuration is ok.

**Comment by famod** [comment]
Glad it worked for you.

For extensions you should have a look at `LiveReloadBuildItem`. There should be plenty examples in the Quarkus code base.
