### ISSUE TITLE
Paths trailing slash treatment RESTeasy Reactive vs. RESTeasy classic

### ISSUE THREAD

**Issue by heubeck** [quarkusio/quarkus#16406]
## Description

Please find the original discussion [in Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Resteasy.20Reactive.3A.20trailing.20slash.20paths).

Essence: RESTeasy classic ignored trailing slashes, e.g. `@Path("/call/")` catches `/call` as well as `/call/`.
RR is more... precise, and matches only exact path (with or without trailing slash).

## To be discussed:

Whether RR should behave the same as RESTeasy classic to become more compatible.

**Comment by geoand** [comment]
Actually I wasn't able reproduce this in a couple in a couple simple endpoints.

Can you attach an example to the issue description please?

**Comment by heubeck** [comment]
Interesting.
I had to remove the trainling slash here: https://github.com/heubeck/api.adoptium.net/pull/1/files#diff-c3a4165254c943488e6ce1d4165aec65b6d386d257c836141e076bf39bd2bfd4R22
to make this test happy: https://github.com/heubeck/api.adoptium.net/blob/feature/ResteasyReactive/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/PlatformsPathTest.kt#L15
after changing to RR (also in the PR above)

**Comment by geoand** [comment]
The following worked just fine for me:

```java
@Path("/test/")
public class TestResource {

    @Path("/test2/")
    @GET
    public String test() {
        return "test2";
    }
}
```

That resource responded just fine to `http://localhost:8080/test/test2`

**Comment by heubeck** [comment]
That's unlikely to my test... any ideas what I should try?

`@Path("platforms/")`:
`GET platforms`: 404
`GET platforms/`: 200

`@Path("platforms")`:
`GET platforms`: 200
`GET platforms/`: 200

---

![image](https://user-images.githubusercontent.com/40993644/114391085-59916580-9b97-11eb-9d98-738b4173ef60.png)
![image](https://user-images.githubusercontent.com/40993644/114391041-4b434980-9b97-11eb-9cf2-ea605b209107.png)

---

![image](https://user-images.githubusercontent.com/40993644/114395266-6e242c80-9b9c-11eb-988d-cd9f8b0f89ce.png)
![image](https://user-images.githubusercontent.com/40993644/114395307-7c724880-9b9c-11eb-986d-b16b14595255.png)

**Comment by kenfinnigan** [comment]
Are you using Kotlin? That appears to be the main difference between your example and @geoand

**Comment by heubeck** [comment]
You're right, it's Kotlin - do you think that makes a difference?

**Comment by kenfinnigan** [comment]
I believe it could be. It's worth trying without Kotlin to verify it does work

**Comment by heubeck** [comment]
Hi @kenfinnigan,

I did tests with clean code-with-quarkus projects, the behavior of Java and Kotlin is exactly the same as described below.

Just for clarification: I don't have an opinion whether that behavior should be changed, there was a short discussion in Zulip with the result to create an issue for discussing about and an open outcome.

The root course, why this came up, is, that RESTEasy classic responds with a 200 in each of the following cases.

***resteasy-reactive, Java:***

without slash:
```java
@Path("/hello-resteasy-reactive")
public class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("slashes")
    public String hello() {
        return "Hello RESTEasy Reactive";
    }
}
```
Test result:
`GET` `/hello-resteasy-reactive/slashes`: 200
`GET` `/hello-resteasy-reactive/slashes/`: 200

---

with slash:
```java
@Path("/hello-resteasy-reactive")
public class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("slashes/")
    public String hello() {
        return "Hello RESTEasy Reactive";
    }
}
```
Test result:
`GET` `/hello-resteasy-reactive/slashes`: 404
`GET` `/hello-resteasy-reactive/slashes/`: 200

---

***resteasy-reactive, Kotlin:***

without slash:
```kotlin
@Path("/hello-resteasy-reactive")
class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("slashes")
    fun hello() = "Hello RESTEasy Reactive"
}
```

Test result:
`GET` `/hello-resteasy-reactive/slashes`: 200
`GET` `/hello-resteasy-reactive/slashes/`: 200

---

with slash:
```kotlin
@Path("/hello-resteasy-reactive")
class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("slashes/")
    fun hello() = "Hello RESTEasy Reactive"
}
```

Test result:
`GET` `/hello-resteasy-reactive/slashes`: 404
`GET` `/hello-resteasy-reactive/slashes/`: 200

**Comment by kenfinnigan** [comment]
Thanks for the details.

The big issue is that RESTEasy Classic, via the JAX-RS spec, is *too* lenient in terms of the translation of `@Path` content.

**Comment by geoand** [comment]
This was actually re-reported in #26016 and was fixed in https://github.com/quarkusio/quarkus/pull/26101
