### ISSUE TITLE
Problem with rest-client 

### ISSUE THREAD

**Issue by PotemkinAlexey** [quarkusio/quarkus#16408]
## Describe the bug
I have 2 different applications 
in the first application I registered a rest-client

```
@Path("/tracks")
@ApplicationScoped
@RegisterRestClient(configKey = "tracks-api")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@RegisterProvider(AdapterResponseExceptionMapper.class)
public interface TracksStorage {
    @POST
    CompletionStage<Long> saveMessage(SBSMessage message);

    @POST
    @Path("batch")
    CompletionStage<List<Long>> saveMessage(List<SBSMessage> messages);
}
```
in the second 

```
@Slf4j
@Path("/tracks")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class SbsTracksController {

    @Inject
    SaveSbsTracksService saveSbsTracksService;

    @POST
    public Response addTrack(@Valid SBSMessage message) {
        log.debug("Add a new SBS track with HEX: {}", message.getHexIdent());
        saveSbsTracksService.saveSbsTrack(new SaveSbsTracksService.SaveSbsTrackCommand(message));
        return Response.ok().build();
    }

    @POST
    @Path("batch")
    public Response addTracks(@Valid List<SBSMessage> messages) {
        log.info("Add a list of SBS tracks: {}", messages.size());
        saveSbsTracksService.saveSbsTracks(new SaveSbsTracksService.SaveSbsTracksCommand(messages));
        return Response.ok().build();
    }

}

```

### Expected behavior
Get messages in the 2 app from the 1

### Actual behavior
The 1 send message but the 2 doesn't get

On version 1.9 worked without problem

### Screenshots
in the first 
![image](https://user-images.githubusercontent.com/9607254/114238682-b4577100-998d-11eb-86fe-2a026108ee48.png)

in the second
![image](https://user-images.githubusercontent.com/9607254/114238755-d05b1280-998d-11eb-8ba4-7841a474d1af.png)

### Output of `java -version` 
java 11

### Quarkus version or git rev 
Quarkus version 1.13.1

**Comment by gsmet** [comment]
@PotemkinAlexey I think it would help if you could prepare a self contained reproducer. Thanks!

**Comment by geoand** [comment]
Closing as we never got a reproducer
