### ISSUE TITLE
RESTEasy Reactive - GZIP support

### ISSUE THREAD

**Issue by heubeck** [quarkusio/quarkus#16425]
## Description

RESTEasy classic has gzip support via `@org.jboss.resteasy.annotations.GZIP` or `quarkus.resteasy.gzip.enabled=true`.
It would be great if RR could get gzip support, too.

## Implementation thoughts

Reference to RESTEasy classics gzip implementation: [DecodingInterceptor](https://github.com/resteasy/Resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/GZIPDecodingInterceptor.java),  [EncodingInterceptor](https://github.com/resteasy/Resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/GZIPEncodingInterceptor.java)

I guess, the decoding filter needs to be present  always, the encoding filter could propably get bound to a `@NameBinding` `@GZIP` - if you like to solve only with jax-rs techniques.

A global setting similar for that you have for RESTEasy classic could enable or completely disable gzip support by deactivation of that filters.

**Comment by geoand** [comment]
@FroMage Vert.x has built-in gzip support doesn't it?
If so, it would be great if we could tie into it somehow

**Comment by FroMage** [comment]
Yes. Let's absolutely not do this ourselves if we can avoid it. Especially not with jaxrs interceptors.

**Comment by FroMage** [comment]
@SaumyaSingh1 is going to look into that

**Comment by stuartwdouglas** [comment]
It's fairly coarse grained, and can already be enabled: https://github.com/stuartwdouglas/quarkus/blob/ac8b99c0d022e7e26eb18834e39282821933c31f/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java#L223

**Comment by heubeck** [comment]
Did I get this right?:
gzip for RESTEasy Reactive as well as for reactive routes can globally get enabled via `quarkus.http.enable-compression = true`?

That would be sufficient for my case, so the question in here would change to: Should there be a route specific configuration?

**Comment by FroMage** [comment]
Yeah, that's part of what we need to do here:

- Test this, verify that it can be enabled
- Document it
- Figure out if we need a way to make it endpoint-specific, and if that's even doable at all at the vert.x level
- Implement that, or not

**Comment by stuartwdouglas** [comment]
It is tested: https://github.com/quarkusio/quarkus/blob/b1dbf7c9a416dd20e401bb73a5c251fe624e3ca6/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/CompressionTest.java#L17

At the moment the only way to make it endpoint specific is pretty yuck, you need to add a `Transfer-Encoding: identity` header to stop the compression happening.

**Comment by FroMage** [comment]
Well, perhaps we can improve that with an annotation to automate it? Also I'm curious as to how that translates to binary data we send: are we compressing images, for example? I'd like for @SaumyaSingh1 to run more tests from the POV of RESTEasy Reactive and get this sort of information.

**Comment by Hubbitus** [comment]
@mkouba, Am I right that such changes only handle quarkus responses compression in RR? Compression in requests still is not implemented? Should I open new issue?

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba), Am I right that such changes only handle quarkus responses compression in RR? Compression in requests still is not implemented? Should I open new issue?

Which changes do you have in mind? If you refere to https://github.com/quarkusio/quarkus/pull/24558 then yes, it's all about compressing HTTP responses.

For HTTP requests you'll need to use [`quarkus.http.enable-decompression=true`](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-enable-decompression) to enable the decompression.

**Comment by Hubbitus** [comment]
> For HTTP requests you'll need to use [quarkus.http.enable-decompression=true](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-enable-decompression) to enable the decompression.

But that also does not work in `RESTEasy Reactive` unfortunately.

**Comment by geoand** [comment]
It should work. Can you add a sample application that shows it does not?
