### ISSUE TITLE
CI: Reduce time spent in native tests by grouping more tests in the same native image

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#16439]
## Description
Native Tests in CI are taking too long, mainly due to the long compilation time of native images.

### Main ~8m
<details> 
<pre>
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:50 min
</details> 
</pre>

### Data1 ~27m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - JPA - Derby .......... SUCCESS [04:36 min]
[INFO] Quarkus - Integration Tests - JPA - MariaDB ........ SUCCESS [04:38 min]
[INFO] Quarkus - Integration Tests - JPA - H2 ............. SUCCESS [04:05 min]
[INFO] Quarkus - Integration Tests - JPA - MSSQL .......... SUCCESS [05:29 min]
[INFO] Quarkus - Integration Tests - Hibernate - Multitenancy SUCCESS [04:54 min]
[INFO] Quarkus - Integration Tests - JPA without entities . SUCCESS [02:54 min]
</details> 
</pre>

### Data2 ~39m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - JPA .................. SUCCESS [04:49 min]
[INFO] Quarkus - Integration Tests - JPA - DB2 ............ SUCCESS [07:28 min]
[INFO] Quarkus - Integration Tests - JPA - MySQL .......... SUCCESS [05:03 min]
[INFO] Quarkus - Integration Tests - Hibernate Reactive - DB2 SUCCESS [06:21 min]
[INFO] Quarkus - Integration Tests - Hibernate Reactive - MySQL SUCCESS [04:58 min]
[INFO] Quarkus - Integration Tests - Reactive DB2 Client .. SUCCESS [05:39 min]
[INFO] Quarkus - Integration Tests - Reactive MySQL Client  SUCCESS [04:31 min]
</details> 
</pre>

### Data3 ~22m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Hibernate ORM with Panache SUCCESS [06:43 min]
[INFO] Quarkus - Integration Tests - Hibernate ORM with Panache and Kotlin SUCCESS [ 44.136 s]
[INFO] Quarkus - Integration Tests - Hibernate ORM with Envers SUCCESS [04:10 min]
[INFO] Quarkus - Integration Tests - Flyway ............... SUCCESS [04:25 min]
[INFO] Quarkus - Integration Tests - Liquibase ............ SUCCESS [05:26 min]
</details> 
</pre>

### Data4 ~25m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Hibernate ORM REST Data with Panache SUCCESS [05:15 min]
[INFO] Quarkus - Integration Tests - Neo4j ................ SUCCESS [03:39 min]
[INFO] Quarkus - Integration Tests - MongoDB Client ....... SUCCESS [03:12 min]
[INFO] Quarkus - Integration Tests - MongoDB Panache ...... SUCCESS [04:10 min]
[INFO] Quarkus - Integration Tests - MongoDB Panache Kotlin SUCCESS [ 50.326 s]
[INFO] Quarkus - Integration Tests - MongoDB REST Data with Panache SUCCESS [03:51 min]
[INFO] Quarkus - Integration Tests - Redis Client ......... SUCCESS [03:55 min]
</details> 
</pre>

### Data5 ~16m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - JPA - PostgreSQL ..... SUCCESS [05:13 min]
[INFO] Quarkus - Integration Tests - Hibernate Reactive - PostgreSQL SUCCESS [04:25 min]
[INFO] Quarkus - Integration Tests - Reactive Pg Client ... SUCCESS [03:48 min]
[INFO] Quarkus - Integration Tests - Narayana STM ......... SUCCESS [  9.585 s]
[INFO] Quarkus - Integration Tests - Narayana JTA CDI ..... SUCCESS [02:31 min]
</details> 
</pre>

### Data6 ~20m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Hibernate Reactive with Panache SUCCESS [06:09 min]
[INFO] Quarkus - Integration Tests - Hibernate Search ORM + Elasticsearch SUCCESS [05:42 min]
[INFO] Quarkus - Integration Tests - Elasticsearch REST client SUCCESS [03:58 min]
[INFO] Quarkus - Integration Tests - Elasticsearch REST high level client SUCCESS [04:29 min]
</details> 
</pre>

### Security1 ~29m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Bouncy Castle ........ SUCCESS [03:41 min]
[INFO] Quarkus - Integration Tests - Bouncy Castle FIPS ... SUCCESS [03:32 min]
[INFO] Quarkus - Integration Tests - Bouncy Castle JSSE ... SUCCESS [04:17 min]
[INFO] Quarkus - Integration Tests - Elytron Security ..... SUCCESS [02:50 min]
[INFO] Quarkus - Integration Tests - Elytron Security OAuth2 SUCCESS [03:13 min]
[INFO] Quarkus - Integration Tests - Elytron Undertow ..... SUCCESS [04:03 min]
[INFO] Quarkus - Integration Tests - Elytron Security JDBC  SUCCESS [03:45 min]
[INFO] Quarkus - Integration Tests - Elytron Security LDAP  SUCCESS [03:23 min]
</details> 
</pre>

### Security2 ~42m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - OpenID Connect Adapter SUCCESS [05:04 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Client  SUCCESS [04:43 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Client Wiremock SUCCESS [03:57 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Token Propagation SUCCESS [04:34 min]
[INFO] Quarkus - Integration Tests - Smallrye JWT Token Propagation SUCCESS [04:27 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Adapter Code Flow SUCCESS [05:13 min]
[INFO] Quarkus - Integration Tests - Multi-Tenant OpenID Connect Adapter SUCCESS [04:25 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Adapter WireMock SUCCESS [03:21 min]
[INFO] Quarkus - Integration Tests - Keycloak Policy Enforcer SUCCESS [05:47 min]
</details> 
</pre>

### Security3 ~8m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Vault ................ SUCCESS [01:12 min]
[INFO] Quarkus - Integration Tests - Vault Agroal ......... SUCCESS [ 29.574 s]
[INFO] Quarkus - Integration Tests - Vault App ............ SUCCESS [06:12 min]
</details> 
</pre>

### Amazon ~13m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Amazon Services ...... SUCCESS [06:36 min]
[INFO] Quarkus - Integration Tests - Amazon Lambda ........ SUCCESS [02:51 min]
[INFO] Quarkus - Integration Tests - Amazon Lambda HTTP ... SUCCESS [03:46 min]
</details> 
</pre>

### Messaging ~35m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Kafka ................ SUCCESS [05:05 min]
[INFO] Quarkus - Integration Tests - Kafka with Snappy .... SUCCESS [04:12 min]
[INFO] Quarkus - Integration Tests - Kafka Avro ........... SUCCESS [05:11 min]
[INFO] Quarkus - Integration Tests - Kafka Streams ........ SUCCESS [04:33 min]
[INFO] Quarkus - Integration Tests - Artemis - Core ....... SUCCESS [03:01 min]
[INFO] Quarkus - Integration Tests - Artemis - JMS ........ SUCCESS [03:02 min]
[INFO] Quarkus - Integration Tests - Reactive Messaging - AMQP SUCCESS [02:55 min]
[INFO] Quarkus - Integration Tests - Reactive Messaging - Kafka SUCCESS [03:45 min]
[INFO] Quarkus - Integration Tests - Reactive Messaging HTTP SUCCESS [03:14 min]
</details> 
</pre>

### Cache ~13m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Infinispan Client .... SUCCESS [04:20 min]
[INFO] Quarkus - Integration Tests - JPA - Infinispan Cache SUCCESS [04:02 min]
[INFO] Quarkus - Integration Tests - Cache ................ SUCCESS [04:27 min]
</details> 
</pre>

### HTTP ~25m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Vert.x HTTP .......... SUCCESS [03:53 min]
[INFO] Quarkus - Integration Tests - Vert.x Web ........... SUCCESS [02:32 min]
[INFO] Quarkus - Integration Tests - Vert.x Web - Jackson . SUCCESS [02:28 min]
[INFO] Quarkus - Integration Tests - Vert.x ............... SUCCESS [03:04 min]
[INFO] Quarkus - Integration Tests - Elytron RESTEasy ..... SUCCESS [02:54 min]
[INFO] Quarkus - Integration Tests - RESTEasy Jackson ..... SUCCESS [02:54 min]
[INFO] Quarkus - Integration Tests - RESTEasy Mutiny ...... SUCCESS [ 12.268 s]
[INFO] Quarkus - Integration Tests - Virtual Http ......... SUCCESS [ 14.020 s]
[INFO] Quarkus - Integration Tests - Vert.x GraphQL ....... SUCCESS [03:12 min]
[INFO] Quarkus - Integration Tests - REST client .......... SUCCESS [03:59 min]
</details> 
</pre>

### Misc1 ~34m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Jackson .............. SUCCESS [03:05 min]
[INFO] Quarkus - Integration Tests - JSON-B ............... SUCCESS [02:18 min]
[INFO] Quarkus - Integration Tests - JGit ................. SUCCESS [03:58 min]
[INFO] Quarkus - Integration Tests - JSch ................. SUCCESS [03:15 min]
[INFO] Quarkus - Integration Tests - Maven tooling ........ SUCCESS [02:55 min]
[INFO] Quarkus - Integration Tests - Quartz ............... SUCCESS [03:24 min]
[INFO] Quarkus - Integration Tests - Qute ................. SUCCESS [04:14 min]
[INFO] Quarkus - Integration Tests - Consul - Config ...... SUCCESS [03:31 min]
[INFO] Quarkus - Integration Tests - Logging when minimum level is unset SUCCESS [02:19 min]
[INFO] Quarkus - Integration Tests - Logging when minimum level is set SUCCESS [02:11 min]
...
[INFO] Failsafe report directory: /home/runner/work/quarkus/quarkus/integration-tests/simple with space/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:35 min
</details> 
</pre>

### Misc2 ~23m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Hibernate Validator .. SUCCESS [04:48 min]
[INFO] Quarkus - Integration Tests - Test Extension Native Tests SUCCESS [02:30 min]
[INFO] Quarkus - Integration Tests - Apache Tika .......... SUCCESS [04:43 min]
[INFO] Quarkus - Integration Tests - Logging - GELF ....... SUCCESS [04:42 min]
[INFO] Quarkus - Integration Tests - Bootstrap Config ..... SUCCESS [  0.137 s]
[INFO] Quarkus - Integration Tests - Mailer ............... SUCCESS [03:41 min]
[INFO] Quarkus - Integration Tests - Native Configuration Profile SUCCESS [02:25 min]
</details> 
</pre>

### Misc3 ~14m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Kubernetes Client .... SUCCESS [06:18 min]
[INFO] Quarkus - Integration Tests - OpenShift Client ..... SUCCESS [07:16 min]
</pre>
</details> 

### Misc4 ~36m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Gradle tooling ....... SUCCESS [07:28 min]
[INFO] Quarkus - Integration Tests - SmallRye Config ...... SUCCESS [03:52 min]
[INFO] Quarkus - Integration Tests - SmallRye Metrics ..... SUCCESS [02:56 min]
[INFO] Quarkus - Integration Tests - SmallRye GraphQL ..... SUCCESS [02:50 min]
[INFO] Quarkus - Integration Tests - Picocli Native ....... SUCCESS [02:37 min]
[INFO] Quarkus - Integration Tests - Micrometer MP Metrics  SUCCESS [02:56 min]
[INFO] Quarkus - Integration Tests - Micrometer Prometheus  SUCCESS [04:26 min]
[INFO] Quarkus - Integration Tests - OpenTelemetry ........ SUCCESS [02:56 min]
[INFO] Quarkus - Integration Tests - Logging - JSON ....... SUCCESS [02:28 min]
[INFO] Quarkus - Integration Tests - JAXP ................. SUCCESS [02:57 min]
</details> 
</pre>

### Spring ~20m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - Spring DI ............ SUCCESS [03:10 min]
[INFO] Quarkus - Integration Tests - Spring Web ........... SUCCESS [03:28 min]
[INFO] Quarkus - Integration Tests - Spring Data JPA ...... SUCCESS [04:08 min]
[INFO] Quarkus - Integration Tests - Spring Boot properties SUCCESS [02:19 min]
[INFO] Quarkus - Integration Tests - Spring Cloud Config Client SUCCESS [03:07 min]
[INFO] Quarkus - Integration Tests - Spring Data REST ..... SUCCESS [03:41 min]
</details> 
</pre>

### gRPC ~23m
<details> 
<pre>
[INFO] Quarkus - Integration Tests - gRPC - TLS ........... SUCCESS [04:15 min]
[INFO] Quarkus - Integration Tests - gRPC - Plain Text with gzip compression SUCCESS [03:48 min]
[INFO] Quarkus - Integration Tests - gRPC - Plain Text with Mutiny SUCCESS [03:31 min]
[INFO] Quarkus - Integration Tests - gRPC - TLS with mutual auth SUCCESS [03:29 min]
[INFO] Quarkus - Integration Tests - gRPC - Streaming ..... SUCCESS [ 12.851 s]
[INFO] Quarkus - Integration Tests - gRPC - Interceptors .. SUCCESS [03:31 min]
[INFO] Quarkus - Integration Tests - gRPC - Proto v2 ...... SUCCESS [03:29 min]
[INFO] Quarkus - Integration Tests - gRPC - Health ........ SUCCESS [ 15.971 s]
</details> 
</pre>

The numbers are grabbed from https://github.com/quarkusio/quarkus/actions/runs/739239839

## Implementation ideas

As a first step we could redistribute the tests in the different groups to achieve a better balance and bring all groups closer to 20-25 minutes.

To further reduce test times we should group more tests in a single native-image. For instance instead of having to compile 8 native images for gRPC we could reduce this to 1 or 2 native-images.

**Comment by geoand** [comment]
+1 on what @gsmet says

**Comment by zakkak** [comment]
Do I understand correctly that the main concern is not about dependencies but about the different native-specific setup that happens in the different extensions (e.g. different substitutions, native features, etc.)?

Would it be possible to have the same tests run "combined" in PRs and "isolated" in some Nightly workflow? Would something like this be possible without a lot of code duplication?

**Comment by famod** [comment]
While I'm all for making CI more efficient in general: Is this mainly about PR build time (which are incremental these days) or about `main` (always a full build)?

**Comment by zakkak** [comment]
@famod I am personally more interested in `main` since we often have to test all the native tests to ensure that `native-image` updates don't break anything. 

I have to admit that I have not tested how well the incremantal builds work with native tests and changes affecting the native build process, but it looks like it's doing a pretty good job (judging by https://github.com/quarkusio/quarkus/actions/runs/741066882), thanks for making this happen!

**Comment by famod** [comment]
To be fair, incremental builds are no silver bullet, e.g. a change early on the critical path (i.e. core) will give you an (almost) full build, and so they don't rule out other efficiency improvements.

**Comment by ppalaga** [comment]
> Would it be possible to have the same tests run "combined" in PRs and "isolated" in some Nightly workflow? Would something like this be possible without a lot of code duplication?

We recently started doing something like that in Camel Quarkus - see e.g. https://github.com/apache/camel-quarkus/pull/2477 There are some time measurements before and after the change in the final PR comment.

We run the grouped tests by the community CI and the isolated tests are run by Camel QE on internal RH infra. I admit that we may revisit this strategy once we start using GIB.

**Comment by zakkak** [comment]
Thanks for the info @ppalaga .

With GIB in place the "grouping" of multiple tests in a single native image indeed doesn't seem to be worth the effort.

So if there are no tests that could be combined without possible negative effects to the quality of testing, I suggest we close this issue and leave things at their current state.
