### ISSUE TITLE
Reactive DB pool - keep IDLE connection on database

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16444]
## Describe the bug

Extension: Reactive SQL 
Even If I set an `idle-timeout` the connection remained on DB, for example, on `pg_stat_activity` with state `IDLE`

**Note:** there is also, at least one active connection

**Comment by tsegismont** [comment]
@pjgg can you please share a reproducer?

**Comment by pjgg** [comment]
You could reproduce it by running this test:

`mvn clean install test -pl 303-quarkus-vertx-sql -Dtest=PostgresPoolTest#checkIdleExpirationTime`

over this branch:
`https://github.com/pjgg/beefy-scenarios/tree/reproducer/reactive-sql-pool`

This is the test:
`https://github.com/pjgg/beefy-scenarios/blob/reproducer/reactive-sql-pool/303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java#L112`

**Comment by tsegismont** [comment]
@pjgg I filed https://github.com/eclipse-vertx/vertx-sql-client/issues/935

**Comment by pjgg** [comment]
This issue is fixed and could be closed!. 
Thank you!.
