### ISSUE TITLE
Support for Proto3 Optional Fields

### ISSUE THREAD

**Issue by bbemis017** [quarkusio/quarkus#16451]
## Description

We should be able to use the quarkus grpc extension with optional fields defined in our proto files like this:
```proto
message Foo {
     optional string bar = 1;
}
```

I believe the newest version of [jprotoq](https://github.com/salesforce/grpc-java-contrib/releases) now supports optional proto fields. There is some documentation on their [github page](https://github.com/salesforce/grpc-java-contrib/tree/master/jprotoc/jprotoc#implementing-a-plugin) on how to set the feature flag as well. It would be super helpful if quarkus would support this too.

**Comment by geoand** [comment]
cc @michalszynkiewicz

**Comment by cescoffier** [comment]
@michalszynkiewicz I know that @pmlopes added support for optional fields in Vert.x gRPC relatively recently.

**Comment by mkouba** [comment]
Correct me if I am wrong, but `optional` is just redundant in proto3, i.e. all fields are optional by default.

**Comment by michalszynkiewicz** [comment]
True, unlike in `proto2`, each field is `optional` by default in `proto3`. 
However, if the field value is missing, the field is set to the default value.

This SO answer says that `optional` now allows to differentiate between default value provided and no value provided: https://stackoverflow.com/a/62566052/4662593

**Comment by mkouba** [comment]
I see. That's quite confusing TBH...
