### ISSUE TITLE
Add support for Java 16 record class in Qute templates

### ISSUE THREAD

**Issue by smsajid** [quarkusio/quarkus#16469]
## Description

Java 16 finalized record classes. Add support for reading record classes and their fields in Qute template

**Comment by mkouba** [comment]
I did a quick and dirty test and it seems that the reflection-based `ValueResolver` fallback does work in the JVM mode (the generated getter is used). @smsajid it would be helpful if you could setup a simple reproducer app.

**Comment by smsajid** [comment]
Yes, you are right. It works for me too. The issue was that I was using json-b and it does not support record serialization yet. I switched to jackson and it works fine.
