### ISSUE TITLE
How do I include my classpath dependencies in the native-image?

### ISSUE THREAD

**Issue by rgcostea** [quarkusio/quarkus#1647]
Currently, "package -Pnative -Dnative-image.docker-build=true" only packages my java service into the native image.  However, it references many other jar files internally.  How do I mimic passing the argument "-cp target/*:target/lib/*" through quarkus so those libraries are also included in the image?

I tried adding it as an additionalBuildArg but that gave an error "-cp" is an unrecognized option.

Thanks.

**Comment by gsmet** [comment]
What's your issue exactly?

Because your dependencies should be included in the native image already.

**Comment by rgcostea** [comment]
The runner jar created after compilation contains the class file of my project, some io.quarkus arc/deployment/runner/runtime classes including a GeneratedMain, and a MANIFEST file that contains the Class-Path with all of my dependencies.  One of those dependencies is jersey-client-2.23.1.

Now when I run the container image I get a ClassNotFoundException for org.glassfish.jersey.client.JerseyClientBuilder.  I figured this was because the class path wasn't configured correctly.  But if the dependencies are being included in the native image already, I wouldn't expect to see this exception.

**Comment by rgcostea** [comment]
My rest service is actually a wrapper around an existing rest service.  The existing rest service is accessed using jersey-client.  When we attempt to build that client using ClientBuilder.newBuilder, we get the ClassNotFoundException mentioned above.  I am assuming that is because quarkus has configured the resteasy client to be used rather than the jersey-client I am attempting to use.  This configuration means that jersey-client is not included on the classpath for my internal service.

Am I correct in that assumption?

**Comment by gsmet** [comment]
No. My bet would be that `JerseyClientBuilder` is instantiated via reflection and thus is not included in your native image as GraalVM can't determine that it is used so it's automatically removed from the image. You would have to register it for reflection for it to work.

The good thing if you use our `smallrye-rest-client` extension is that we take care of everything for you. You can find a guide here: https://quarkus.io/guides/rest-client-guide .

If you still want to use Jersey, you will have to register the class for reflection yourself either directly via GraalVM (https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#manual-configuration) or by developing a Quarkus extension (you can then use all our nice framework with ``BuildStep``s and `ReflectiveClassBuildItem`).

**Comment by rgcostea** [comment]
Yes.  You are right.  I figured that out last night.  I'm now struggling to load the META-INF/services needed by some of those dependencies.  Thanks for the pointers.

**Comment by ldebello** [comment]
@rgcostea hi , were you able to run the service using jersey client? I am facing the same issue I included JerseyClientBuilder in the reflection file but I am still getting the same error

**Comment by rgcostea** [comment]
Yes.  I got this working with jersey 2.28.  My reflection.json file looks like this:
` {
    "name" : "org.glassfish.jersey.client.JerseyClientBuilder",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.internal.inject.InjectionManagerFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.DynamicConfigurationService",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.DynamicConfigurationServiceImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.ServiceLocator",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.ServiceLocatorImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.ServiceLocatorRuntimeImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.annotations.Service",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.internal.PerThreadContext",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.JerseyErrorService",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.Hk2RequestScope",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.ByteArrayProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.DataSourceProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.FileProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.FormMultivaluedMapProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.FormProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.InputStreamProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.BasicTypesMessageProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.ReaderProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.RenderedImageProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.StringMessageProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.SourceProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.SourceProvider$StreamSourceReader",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.xml.transform.sax.SAXSource",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.SourceProvider$SaxSourceReader",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.SourceProvider$DomSourceReader",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.client.ChunkedInputReader",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.IterableProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.IterableProviderImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.utilities.InjecteeImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.SystemInjecteeImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl$Binder",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl$CacheKey",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.Factory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.DescriptorType",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.DescriptorVisibility",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.PerLookup",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.PerLookupContext",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.PerLocatorUtilities",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.ConstantActiveDescriptor",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.xml.parsers.SAXParserFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.jaxb.internal.SaxParserFactoryInjectionProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "com.sun.org.apache.xerces.internal.parsers.SAXParser",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.jaxb.internal.XmlInputFactoryInjectionProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.internal.JaxrsProviders",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.client.ClientConfig$State",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.xml.parsers.DocumentBuilderFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.inject.Provider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.inject.Singleton",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.inject.Named",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.ws.rs.core.Context",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "javax.ws.rs.ext.MessageBodyReader",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.MessagingBinders",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.MessagingBinders$MessageBodyProviders",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.utilities.cache.Cache",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.utilities.binding.AbstractBinder",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.ThreeThirtyResolver",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.InjectionResolver",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.hk2.api.ClassAnalyzer",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.jvnet.hk2.internal.DefaultClassAnalyzer",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.internal.util.ReflectionHelper",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "java.lang.reflect.ParameterizedType",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.StreamingOutputProvider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.message.internal.SourceProvider$SourceWriter",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.inject.hk2.RequestContext",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
 {
    "name" : "org.glassfish.jersey.process.internal.RequestScoped",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredFields": true,
    "allPublicFields": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
 },
`

**Comment by gsmet** [comment]
@rgcostea any reason why you do not want to use the SmallRye REST client? Is there anything missing in it that we should add?

**Comment by rgcostea** [comment]
I'm coding to a java REST SDK.  The SDK internally uses jersey-client to communicate with the service I want to manipulate.  I don't have any control over that.
