### ISSUE TITLE
RESTEasy Singleton resource with constructor injection failing with RESTEASY003190

### ISSUE THREAD

**Issue by chris-asl** [quarkusio/quarkus#16475]
## Describe the bug
When using constructor injection in a non annotated resource ([reproducer link](https://github.com/chris-asl/quarkus-mcve/commit/2234069170ec55e341388ad5e12445269eb320a3#diff-c1e351af7879a35f1479bc0907392e13720790b0c7ccabcd4acbf4da3ef175bcR11-R19)), e.g.

```java
@Path("/hello")
public class GreetingResource {

    GreetingService greetingService;

    @Inject
    public GreetingResource(GreetingService greetingService) {
        this.greetingService = greetingService;
    }
```

the program spins up successfully.

Given the default resource scope, as defined by [`quarkus.resteasy.singleton-resources`](https://quarkus.io/guides/all-config#quarkus-resteasy-server-common_quarkus.resteasy.singleton-resources) is `Singleton`, why do I get an error if I annotate the class with `@Singleton`, as [I did here](https://github.com/chris-asl/quarkus-mcve/commit/72a40a7f2f7f25bba2e50a634af1a333145806d8)?

The program fails upon startup with:
```
...
Caused by: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: org.acme.getting.started.GreetingResource
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.getConstructor(ResourceBuilder.java:852)
...
```

It seems there's a difference with explicitly setting the scope to `Singleton` with it being set-up "automatically".  
If I am missing something, a pointer towards the docs would be more than welcome.

I don't know if this is related to https://github.com/quarkusio/quarkus/issues/6722 or https://github.com/quarkusio/quarkus/issues/7495.

### Expected behavior
As in both cases the scope effectively is `Singleton`, shouldn't the behaviour be the same?

### Actual behavior
Annotating a RESTEasy Resource with `@Singleton`, I get the aforementioned error.

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. `git clone git@github.com:chris-asl/quarkus-mcve.git`
2. `./mvnw quarkus:dev`

### Configuration
Defaults

### Output of `uname -a` or `ver`

`Linux homer 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

### Quarkus version or git rev
`1.13.1.Final` (also tested with `1.12.2.Final`)

### Build tool

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/chris/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-48-generic", arch: "amd64", family: "unix"
```

FYI @el10686

**Comment by mkouba** [comment]
I can confirm that the behavior varies. If there is no scope annotation present then the no-args constructor is generated automatically. However, if the `javax.inject.Singleton` is added you need to add the no-args constructor manually. It's interesting that if you add `@RequestScoped` the no-args constructor is also generated although I don't see the `javax.enterprise.context` package in the list of compatible annotations here: https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L452-L463

CC @geoand

**Comment by mkouba** [comment]
> It's interesting that if you add `@RequestScoped` the no-args constructor is also generated although I don't see the `javax.enterprise.context` package in the list of compatible annotations here...

In this case, the no-args constructor is generated by ArC because `@RequestScoped` is a normal scope.

**Comment by mkouba** [comment]
@geoand I think that we could just add the `javax.inject` to the list of compatible packages. I can send a PR tomorrow.

**Comment by geoand** [comment]
@mkouba yeah, that makes perfect sense!
