### ISSUE TITLE
Test non-platform extensions' compatibility when a new Quarkus release becomes available

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#16480]
When a new Quarkus release becomes available, we run a CI for each of those extensions compatible with the previous version of Quarkus against the newly released one.

Those that pass the CI are assumed to be compatible with the new Quarkus release and the registry gets updated with that info. Those that fail aren't marked as compatible then when the next Quarkus release becomes available, we repeat.

Extension authors may also submit updates manually (subject to approval).

We assume in the registry that extensions are compatible with a given Quarkus version if the requested Quarkus version is the same or higher compared to the one compiled against the extension. 

The idea here is to automate the steps to certify that any Quarkiverse extension is compatible with a specific Quarkus version and store that information in the Registry. For now, you can specify this manually: https://github.com/quarkusio/quarkus-extension-catalog#compatibility-with-older-quarkus-core-versions

**Comment by gastaldi** [comment]
After talking to @aloubyansky, we decided on some action items:

- [ ] Non-platform extensions will publish test-jars (under a release profile defined on `quarkiverse-parent`)
- [ ] Listen when quarkusio/quarkus is tagged (released) and run the tests on the existing test-jars and record the compatibility test outcome in registry.quarkus.io

**Comment by geoand** [comment]
Is this still relevant?

**Comment by gastaldi** [comment]
Maybe not, let's close and revisit later if needed
