### ISSUE TITLE
`quarkus:create` adds `quarkus-resteasy` to a project even when `quarkus-resteasy-reactive-jackson` is specified

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#16497]
## Describe the bug
When generating a project with `quarkus-resteasy-reactive-jackson`, `quarkus-resteasy` extension is added to the project's pom.

Related to https://github.com/quarkusio/quarkus/issues/15997

### Expected behavior
`quarkus-resteasy-reactive` and `quarkus-resteasy` are mutually exclusive, the latter should not be added when the former is used, and `quarkus-resteasy-reactive-jackson`  brings in the former.

### Actual behavior
The dependency on `quarkus-resteasy` is added. 
It all works okay if a user explicitly adds `quarkus-resteasy-reactive`

## To Reproduce
```
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create -Dextensions=resteasy-reactive-jackson
```

**Comment by geoand** [comment]
CC @ia3andy

**Comment by ia3andy** [comment]
This due to `resteasy` being the default example, I need to make that dynamic...
