### ISSUE TITLE
Opentelemetry - reactiveRoutes / vertx

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16499]
## Describe the bug
I am working with opentelemetry extensions over a [Quarkus application](https://github.com/quarkus-qe/beefy-scenarios/pull/166) with Reactive routes:

```
       <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-jaeger</artifactId>
        </dependency>
```
When I am running my application in JVM mode my jaeger `ServiceName` is set to `<<unset>>` but on native mode is set to `300-quarkus-vertx-webclient` (my app-module name), as you can see on [my test](https://github.com/quarkus-qe/beefy-scenarios/pull/166/files#diff-4cb7c5d2d3bfca7d26ad99a9b3df8d9160f7b8a25d5de1e4cb3a18356f81f8a3R176)

This is quite an inconvenience  :) 
 But In my opinion, the root of the issue is that we are not allowed to set a jaeger service name by configuration, as we do in other extensions as opentracing (quarkus-smallrye-opentracing). 

Opentraicing config

```
# Jaeger
quarkus.jaeger.service-name=my-custom-service-name
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
```

**Comment by kenfinnigan** [comment]
There's a couple of factors at play here. One is that OpenTelemetry has not been tested with Reactive Routes yet, and likely won't because my understanding is in Quarkus 2.x it won't be a recommended approach anymore. And two, I haven't reached a point of adding much customization to the extensions yet

**Comment by kenfinnigan** [comment]
It's a problem with how Quarkus tests work that `quarkus.application.name` and `quarkus.application.version` are not set when running tests, but **are** set with Dev mode or a built Jar.

The solution is to add `quarkus.application.name=300-quarkus-vertx-webclient` to your `application.properties` in `src/test/resources` so it's only applied for testing.

**Comment by rsvoboda** [comment]
`quarkus.application.name` and `quarkus.application.version` are now propagated in tests too thanks to https://github.com/quarkusio/quarkus/pull/24666
