### ISSUE TITLE
Opentelemetry - VertxHttpClient doesn't have his own span

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16507]
## Describe the bug

I am working with opentelemetry extensions over a [Quarkus application](https://github.com/quarkus-qe/beefy-scenarios/pull/166), Reactive routes, and vert.x HttpClient:

```
       <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-jaeger</artifactId>
        </dependency>

        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
        </dependency>
```

Based on [this doc ](https://quarkus.io/blog/quarkus-1-13-0-final-released/#opentelemetry-extension) I expected that If I have an HttpClient behind an endpoint, I will have two spans with the same traceId. The first span represents the endpoint and the second the HttpClient request. But I am getting just one Span per traceId (we are not recording HTTP requests)

You have a reproducer [here](https://github.com/quarkus-qe/beefy-scenarios/pull/166/files#diff-4cb7c5d2d3bfca7d26ad99a9b3df8d9160f7b8a25d5de1e4cb3a18356f81f8a3R104).

**Comment by kenfinnigan** [comment]
Not all usages of OpenTelemetry have been tested/verified at present.

Right now I expect RESTEasy Classic, REST Client, and Reactive Messaging with Kafka to work. Other extensions may "work", but there are no guarantees at present.

In addition, the existing extensions in 1.x will likely change significantly for the 2.x/main stream

**Comment by kenfinnigan** [comment]
I verified this works with the `2.0` branch.
