### ISSUE TITLE
KafkaStream extension should report better that no topology is found

### ISSUE THREAD

**Issue by vietk** [quarkusio/quarkus#16514]
Not really a bug ... but :
Inside KafkaStreams the topology that will build the logic of the application is supposedly be exposed a CDI bean.

We had a case with native compilation where, by mistake, no topology was provided by our maven dependencies.
It was a little hard to understand why our native application was not processing anything ... we found by switching to log level to DEBUG.

So I gonna open a small PR to raise the level of the concerned log so that it's more explicit for the developer to understand its mistake 🙄

**Comment by vietk** [comment]
Last thing, can we ask a backport to 1.11 when issue is closed?

**Comment by gastaldi** [comment]
@vietk not sure about 1.11, but it should be possible for 1.13.2.Final
