### ISSUE TITLE
Drop jprocesses in favor of java.lang.ProcessHandle

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#16521]
## Description
As per https://github.com/quarkusio/quarkus/pull/16249#issuecomment-815263204

[`jprocesses`](https://github.com/profesorfalken/jProcesses) has not seen any activity for 3 years and with JDK 8 support now dropped (in main), the OOTB `ProcessHandle` should be used instead.

## Implementation ideas
Remove code, write a tiny bit of new code, remove dependency - be happy! 😉

**Comment by geoand** [comment]
Interesting, I didn't even know about jprocesses.

I actually had custom code for the IDE link handling that I just removed, so I'm obviously +1 for this

**Comment by gastaldi** [comment]
@famod fancy providing a PR?

**Comment by gastaldi** [comment]
I'm guessing the code in `DevModeTestUtils` would be something like: 

```java
    public static void killProcesses(String... cmdParts) {
        ProcessHandle.allProcesses()
                .filter(processHandle -> {
                    String cmdLine = processHandle.info().commandLine().orElse(null);
                    if (cmdLine == null) {
                        return false;
                    }
                    for (String part : cmdParts) {
                        if (cmdLine.contains(part)) {
                            return true;
                        }
                    }
                    return false;
                })
                .forEach(ProcessHandle::destroyForcibly);
    }
```

**Comment by famod** [comment]
Looks like you implemented it already. 😄

**Comment by famod** [comment]
But yeah, I can provide a PR later this week.

**Comment by gastaldi** [comment]
@famod I put my code in a PR for your appreciation: https://github.com/quarkusio/quarkus/pull/16529
