### ISSUE TITLE
Opentelemetry: Distributed tracing with Reactive Routes

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16520]
## Description

As far as I see with reactive Routes (Vert.x) and openTelemetry we are not propagating trace headers between different microservices. 

As a cloud-native developer, most of the applications are a composition of several microservices, distributed in several places, some of them are under our platform as ocp/k8s and some others are in third-party services (even in serverless platforms like Knative). So, for us is important to propagate the trace headers as `traceId`, `ParentSpanId` or `spanId`, in order to be able to understand why a given request takes "so much time" (because we would have one `traceID` and `N` spans as a tree, so we have all the dependencies, all the transaction history recorded). 

Also would be great, be able to use a common protocol for all the layers (services), so if for example `X-B3` is widely adopted because of Istio, then would be great to be able to enable/disbaled b3 headers with a property like: `opentracing.jaeger.enable-b3-propagation=true`

**Comment by kenfinnigan** [comment]
As mentioned on #16499, Reactive Routes has not been tested with OpenTelemetry at present

**Comment by kenfinnigan** [comment]
@pjgg you could try this again with 2.0.0.CR3, as I think it should work now

**Comment by kenfinnigan** [comment]
Also, specifying different context propagation is available in 2.0.0.Final.

I'm going to close as I've verified Reactive Routes is being traced, and we do inject headers into outgoing requests.

Please re-open with a reproducer if it's not the case
