### ISSUE TITLE
Enhance RestClient Reactive to support registering providers via custom annotations

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#16522]
## Description

The following is possible with `quarkus-rest-client`, for example, with `OidcClientRequestFilter`

```
@Inject
@OidcClientFilter
MyMpRestClient client;
```
where the `quarkus-oidc-client-filter` extension registers `OidcClientFilter annotation and OidcClientRequestFilter.class` pair, and where `quarkus-rest-client`'s RestClientProcessor [discovers such registrations](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/deployment/src/main/java/io/quarkus/restclient/deployment/RestClientProcessor.java#L241) and [passes them to RestClientBase](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java#L60).

Note as far as `OidcClientRequestFilter` is concerned, the alternative solution (explicitly register it with MP RestClient `RegisterProvider`) is available. This issue is not about `OidcClientRequestFilter` but about a generic support for registering providers via custom annotations.
## Implementation ideas

Do something similar in the reactive rest client to what is done in `quarkus-rest-client`'s [RestClientProcessor](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/deployment/src/main/java/io/quarkus/restclient/deployment/RestClientProcessor.java#L241) and [RestClientBase](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java#L60).

**Comment by geoand** [comment]
cc @michalszynkiewicz

**Comment by geoand** [comment]
@sberyozkin what's your take on https://github.com/quarkusio/quarkus/issues/16522#issuecomment-1246773262? Is there something we need to do to make the experience better? Or maybe just add some more documentation?

**Comment by sberyozkin** [comment]
Hey @geoand, apologies, I've just discovered your comment after following on the related comments from Rostislav in QUARKUS-2389.

I think that if RestEasy Reactive could allow supporting the same style of registering OIDC Reactive client filter as the one allowed in RestEasy Classic for OIDC client reactive,

```
@Inject
@OidcClientFilter
MyMpRestClient client;
```
in addition to the standard

```
@Inject
@RegisterProvider(OidcClientRequestReactiveFilter.class)
MyMpRestClient client;
```

then it would indeed be a bit nicer and as @rsvoboda has indicated, would not even require the code changes during the migration to Resteasy Reactive which Rostislav is quite concerned about.

Have a look at the description please - I've provided links to the RestEasy Classic code showing how `@OidcClientFilter` is recognized and processed to get (classic) `OidcClientFilter` registered, I can try to do pretty much the same but in RestEasy Reactive, but I'd appreciate some help. May be Jose can be interested as well ?

thanks

**Comment by geoand** [comment]
Thanks @sberyozkin, I'll have a look next week.

**Comment by sberyozkin** [comment]
For example, `oidc-client-filter` registers a pair of `@OidcClientFilter` and the associated provider class name [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client-filter/deployment/src/main/java/io/quarkus/oidc/client/filter/deployment/OidcClientFilterBuildStep.java#L34), and then RestEasy Classic checks the list of these build items and if a given REST Client has a matching annotation then the associated provider is added, so it should be simple enough I guess to do the same with RestEasy Reactive :-), and then once this is in place, the users can have their custom extensions provide such annotation shortcuts

**Comment by sberyozkin** [comment]
@geoand Np at all, yeah, lets see if it can be done without too many problems, ping me please if you'd like me to help somehow, cheers

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
@sberyozkin can you take a look at https://github.com/quarkusio/quarkus/pull/28451?

It should cover this

**Comment by sberyozkin** [comment]
Hey @geoand what a good Friday, sorry, had to step outside for a very late lunch :-)

**Comment by geoand** [comment]
No problem at all :)
