### ISSUE TITLE
Make quarkus-oidc-client-filter work with reactive RestClient

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#16523]
## Description

- `quarkus-oidc-client-filter` depends on `quarkus-rest-client` (to register itself as `OidcClientFilter`) and it is also blocking when it is auto-refreshing or if the initial token acquisition has been postponed until the first request.

## Implementation ideas

For it to work with the reactive client, the code which registers `OidcClientFilter` annotation should be made optional if the rest client classic feature is present.
But also, I think it can make sense to create a dedicated light-weight `quarkus-oidc-reactive-client` extension which would ship a totally non-blocking client filter

## Workaround:

https://quarkus.io/guides/security-openid-connect-client#use-injected-tokens

CC @geoand @michalszynkiewicz

**Comment by sberyozkin** [comment]
> the code which registers OidcClientFilter annotation should be made optional if the rest client classic feature is present

It is not gong to work, unless the same `RestClientAnnotationProviderBuildItem` currently shipped with `quarkus-rest-client` is also known to `rest-client-reactive`.

But given it would still remain blocking in some situations as described above, it does feel the dedicated extension is the way to go. The question is, @geoand, @michalszynkiewicz, is there a rest client reactive specific non-blocking client filter available ? I mean, such that I can avoid doing `Uni.await().indefinitely()` when auto-refreshing the tokens and set them on the current HTTP request only when they are available without blocking the original thread ?

**Comment by geoand** [comment]
We will have to add that functionality, we have something similar in the server, but I don't think we have it in the client

**Comment by sberyozkin** [comment]
@geoand That would be very cool once it becomes available

**Comment by geoand** [comment]
I'll add it to my TODO list

**Comment by geoand** [comment]
I opened https://github.com/quarkusio/quarkus/issues/16615 to track the need

**Comment by sberyozkin** [comment]
Great stuff :-)

**Comment by geoand** [comment]
@sberyozkin I opened #16624 to cover the suspend / resume case for filters. Here is an example of how it can be used: https://github.com/quarkusio/quarkus/pull/16624/files#diff-f38b9446e212797812d04f5e5da9a9cc749e486c1d89dd5e27cedbae200e2962

**Comment by sberyozkin** [comment]
Thanks, PR is on the way :-)
