### ISSUE TITLE
DevMojoIT.testThatNewResourcesAreServed is flaky

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#16524]
Seen e.g. [here](https://github.com/quarkusio/quarkus/pull/16519/checks?check_run_id=2344427204) and [here](https://github.com/quarkusio/quarkus/pull/16249/checks?check_run_id=2342175326):
```
2021-04-14 15:57:25,403 INFO  [io.quarkus] (Quarkus Main Thread) acme 1.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.304s. Listening on: http://localhost:8080
2021-04-14 15:57:25,404 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-14 15:57:25,404 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation, websockets]
2021-04-14 15:57:25,404 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-3) Live reload total time: 0.388s 
Error:  Tests run: 40, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 553.529 s <<< FAILURE! - in io.quarkus.maven.it.DevMojoIT
Error:  io.quarkus.maven.it.DevMojoIT.testThatNewResourcesAreServed  Time elapsed: 72.101 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.DevMojoIT that uses java.lang.String was not fulfilled within 1 minutes.
```

**Comment by geoand** [comment]
I have an idea what might be the cause of this issue

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/16527 should take care of the issue.

I used `@RepeatedTest` to run the test with the fix and it passed (as oppoed to prior to the fix where I could easily reproduce the problem)

**Comment by famod** [comment]
Good catch! But why did it not fail every time?

**Comment by geoand** [comment]
My assumption is that something changed with Vert.x - maybe it caches for longer.
I didn't look to closely at the implementation

**Comment by famod** [comment]
Well, a fix is a fix.

**Comment by famod** [comment]
Unfortunately, this still happens: https://github.com/quarkusio/quarkus/pull/16250/checks?check_run_id=2361425088

**Comment by famod** [comment]
Haven't seen this for a while, closing.

**Comment by geoand** [comment]
Actually, I've see this happen, for example https://github.com/quarkusio/quarkus/pull/18363

**Comment by geoand** [comment]
The problem is that I cannot reproduce the problem locally...

**Comment by geoand** [comment]
Closing this as the test is no longer flaky.
