### ISSUE TITLE
Improve serializer / deserializer detection the Kafka connector

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#16544]
## Description

At the moment, the user must specify the key and value serializer/deserializer when using reactive messaging with Kafka:

```
mp.messaging.foo.incoming.value.deserializer=....

mp.messaging.bar.outgoing.value.serializer=....
```

(for key, if not set "String" is used).

In Quarkus we can detect the right value by inspecting the code:

* methods having an `@Incoming("foo")
* methods having an `@Outgoing("bar")
* injection of the `@Channel("foo") (Multi/Publisher<X>, Multi/Publisher<Message<X>>)
* injection of the `@Channel("bar") Emitter<X> or Emitter<Message<X>> or MutinyEmitter

There is a few cases to consider:

* method can have many potential signatures - See https://docs.google.com/spreadsheets/d/11cNwX8eXKTKjoF_amXTPLU1-DfrYxwu4VLnEideBy7Q/edit?usp=sharing for details
* `Record<K, V>` can be used, and in this case, it's the K/V that are interesting
* It needs to handle X but also `Message<X>`

Of course, if the configuration contains an explicit deserializer or serializer, this one should be used.

## The Avro case

Avro is a bit different.
If the detected type is X and X is an Avro-generated class, Avro _serde_ should be used. Depending on if Confluent or Apicurio is in the classpath the right class names should be used.

**Comment by Ladicek** [comment]
I put something together, but need to write a bunch of tests, so not publishing it anywhere yet.

**Comment by Ladicek** [comment]
PR sent: #16544

**Comment by geoand** [comment]
This doesn't seem to work for `@Emitter` (or I am doing something wrong)

**Comment by Ladicek** [comment]
@geoand What Quarkus version did you use? This was fixed in https://github.com/quarkusio/quarkus/pull/17725/files#diff-46509415268dd405a7fd2532913b85a80102b0a06e6c2bf311741256c0ca9c5d, so 2.0.0.Final should be fine.

**Comment by Ladicek** [comment]
That would be great, thanks!

**Comment by geoand** [comment]
Here you go: [upload.zip](https://github.com/quarkusio/quarkus/files/6724358/upload.zip)

Just build with `mvn package -DskipTests` and try to run it with `java -jar target/quarkus-app/quarkus-run.jar read`

**Comment by Ladicek** [comment]
Alright, so the autodetection works, there's just nothing to autodetect. No serializer exists.

If you want to serialize with Jackson, you can add this class:

```java
public class CsvRecordSerializer extends ObjectMapperSerializer<CsvRecord> {
}
```

and it will be autodetected.

**Comment by geoand** [comment]
Aha, gotcha!

Would it not make sense however for us to auto-configure that as we have:

```java
@Channel("csv-record") Emitter<CsvRecord> emitter
```

in the code and the Jackson extension in the application capabilities?

**Comment by Ladicek** [comment]
Jackson is actually _always_ present with Kafka, so not totally sure it's a conscious choice.

**Comment by Ladicek** [comment]
I mean ... if the `CsvRecord` class contained at least one Jackson annotation, that would probably be good enough for me...

Also, there's this unfortunate asymmetry where you can define `ObjectMapperSerializer` as a value serializer, but you can't define `ObjectMapperDeserializer` as a value deserializer -- you have to create a subclass of that. So for autodetection, I thought it's best to start with something that _is_ symmetric.

**Comment by geoand** [comment]
Good point.

However, for microservices that are going to be implementing sending data to Kafka, the asymmetry shouldn't really matter, right?

**Comment by Ladicek** [comment]
I'm using [a]symmetry as a proxy for confusing, hard[er] to understand [than necessary] and generally weird :-)

That said, I've got nothing against automatically configuring Jackson (and/or JSON-B) serializer and deserializer (we could easily generate the deserializer class), if there's _some_ sign that this is what the user wants. Jackson presence unfortunately doesn't cut it, as it's always present (https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/runtime/pom.xml#L26-L29).

**Comment by geoand** [comment]
I personally see it the other way around:

I would generate the serializer unless there is an indication that the users wants their own :)

**Comment by Ladicek** [comment]
I filed #18195 for this (and one other improvement I have in mind). I don't agree with you, but feel free to beat me with your arguments on the issue :-)
