### ISSUE TITLE
Default favicon.ico for quarkus-resteasy

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#16548]
When adding an `index.html` file in `src/main/resources/META-INF/resources/` and opening it in a browser, the development console shows this error in the console:

![image](https://user-images.githubusercontent.com/176880/114868208-f5201180-9df5-11eb-8f41-32a46bad83fc.png)

_If and only if_ the user did not create a `src/main/resources/META-INF/resources/favicon.ico` file, Quarkus should automatically return a default one. If that's the Quarkus icon, it's very good for Quarkus marketing. But it might have a security impact.

**Comment by geoand** [comment]
Closing as `won't fix`
