### ISSUE TITLE
kubernetes client extension fails when using in @Scheduled method

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#16552]
## Describe the bug
When using the Kubernetes client extension inside an @Scheduled annotated method only the first few calls to the scheduled method give the expected results. Invocations after about 1 or 2 minutes give: Request Forbidden by administrative rules.

### Expected behavior
Every invocation of the @Schedules method should list services, see the reproducer project.

### Actual behavior
Only the first few invocation lists the services.  Invocations after about 1 or 2 minutes give: Request Forbidden by administrative rules.

## To Reproduce
See the reproducer project here [https://github.com/bpasson/quarkus-scheduled-kubernetes-client-failure](https://github.com/bpasson/quarkus-scheduled-kubernetes-client-failure)

1. Checkout the project
2. Build with ./mvnw quarkus:dev
3. Wait a bit for the exceptions, method is called every 10s after an initial delay of 5s, after about 1 to 2 minutes the exceptions start coming in. 

### Configuration
Make sure you have a valid ~/.kube/config. 

### Output of `uname -a` or `ver`
Darwin maq.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Volumes/Data/Users/basp/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Volumes/Data/Users/basp/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
@iocanel @gastaldi @Ladicek do you have any ideas on why this could be happening?

**Comment by gastaldi** [comment]
Maybe there is a API Throttle threshold configured in the server to prevent DDoS attacks?

@bpasson which K8s server are you using? OpenShift?

**Comment by Ladicek** [comment]
I'd guess that if first few requests work and subsequent ones start failing with `Request Forbidden by administrative rules.`, without any obvious reason, it truly is "forbidden by administrative rules".

**Comment by geoand** [comment]
Is there maybe some Istio magic going on?

**Comment by bpasson** [comment]
@gastaldi This is plain Kubernetes 1.20 running. API server is placed behind HAProxy which validates the client certificate before submitting the request to the backend. I am under the impression after some time the client certificate is missing for some reason. It might be something with the proxy, but is there a way I can get some more information on the actual requests?

**Comment by bpasson** [comment]
@gastaldi @Ladicek I will test it against the API server without the proxy in front of it to see what happens.

**Comment by bpasson** [comment]
@gastaldi @Ladicek testing confirmed it is an issue with HAProxy and the fabric8 kubernetes client. Not an issue for Quarkus. I'm closing this for now and will open one with fabric8 if I have more details around the cause. If you have any ideas on what could be happening I'd love to hear them.

**Comment by bpasson** [comment]
I have the issue solved, leaving a comment here if someone else hits a similar issue.

In HAProxy there are two ACL checks for verifying a client certificate was used in the request:
* ssl_fc_has_crt
* ssl_c_used

I was using the wrong one (ssl_fc_has_crt) for the purpose of checking for the presence of a client certificate.

Both accomplish verify if a client certificate was used, but with a subtle difference. The first, ssl_fc_has_crt only succeeds if a client certificate was offered on the actual request. The latter succeeds if the ssl session uses a client certficate. If using the first this can lead to failures in case of ssl resumption. See https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.4-ssl_fc_has_crt for more details.
