### ISSUE TITLE
Mock of CrudRepository in QuarkusTest leads to ClassCastException

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#16556]
## Describe the bug
When some `public EntityInterface extends CrudRepository<...>` is mocked in a `@QuarkusTest` and then installed through `installMockForType(...)`, a `ClassCastException` occurs.

### Expected behavior
The mock should be injected.

### Actual behavior
A `ClassCastException` occurs.

## To Reproduce

- Checkout https://github.com/turing85/quarkus-test-mock-bug
- Execute `./mvn test`

**Comment by geoand** [comment]
For cases like this, you should use Quarkus' `@InjectMock` as mentioned in https://quarkus.io/guides/getting-started-testing#further-simplification-with-injectmock.

To do that you should remove `quarkus-junit5` and `mockito-core` dependencies and instead add `quarkus-junit5-mockito`.

Your code would like something like:

```java
@QuarkusTest
@TestHTTPEndpoint(FooResource.class)
class FailingTest {

  @InjectMock
  FooRepository originalFooRepository;

  @Test
  void test() {
    final Foo foo = new Foo();

    given()
            .header("Content-Type", MediaType.APPLICATION_JSON)
            .body(foo)
        .when()
            .post();

    verify(originalFooRepository).save(any(Foo.class));
  }
}
```
