### ISSUE TITLE
Problem with loading resources with fast-jar

### ISSUE THREAD

**Issue by phelioz** [quarkusio/quarkus#16550]
## Describe the bug
In our project we load "directories" with resources under the class path.
So we get the class loader with ```Thread.currentThread().get_contextClassLoader()```
and the root of the class path would be  ```Thread.currentThread().get_contextClassLoader().getResource("")```

With legacy-jar packing this work great with both the file protocol (dev, test) and jar protocol (running jar).
When using dev, test (file protocol) the class path root points to ```target/classes``` and when running the runner jar it points
to `target/<jar name>-runner.jar`

But with fast-jar only dev, test (file protocol) works the same.
When you run the jar ```target/quarkus-app/quarkus-run.jar``` with fast-jar it doesn't work anymore because of the different structure.
When running the jar it seems like the root of the class path is in one of the jars in ```target/quarkus-app/lib/<some jar here>.

### Expected behavior
Would expect the root of the class path ```Thread.currentThread().get_contextClassLoader().getResource("")``` to point
to the ```target/quarkus-app/app/<app name>.jar``` so we easily can get our resources.

### If this is on purpose
If this is on purpose is there any other way for us to easly get the resources under a "directory" in our app jar.
Thanks in advance for any help!

**Comment by geoand** [comment]
This is an extreme corner case... 
I don't see the legacy jar working with this either to be honest

**Comment by stuartwdouglas** [comment]
Does it work if you use getResources() and iterate on the result?

**Comment by geoand** [comment]
Closing as we never got feedback
