### ISSUE TITLE
Explore DDL scripts from Hibernate ORM in the DevUI

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#16553]
## Description

Hibernate ORM can automatically generate create/update/drip scripts for the database schema.

This is normally done when it's started (see #16483 ), as we expose some configuration properties which allow it to generate the `.sql` files when it starts.

However this feature is very useful during development, as one makes changes to the domain model and its mapping we want to immediately verify if it's having the intended effect on the schema.

Would be great to allow inspecting of these scripts from the DevUI

**Comment by TomasHofman** [comment]
I'm going to investigate next week.

**Comment by keshavcodex** [comment]
Hello sir, i want to work on this, what are things i need to know to resolve this issue?
