### ISSUE TITLE
1.13.x WebSocket client Dev mode threading inconsistency

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#16569]
1.13.x WebSocket client callbacks occur on the IO thread in Prod (e.g. in Docker image) but not in Dev mode (as if quarkus.websocket.dispatch-to-worker was set to true).  Hence in Dev mode we don't get the "blocking on I/O" warning if using an EntityManager or similar.

**Comment by geoand** [comment]
Is this still an issue with the Quarkus 3.2.z?

**Comment by geoand** [comment]
Closing for lack of feedback
