### ISSUE TITLE
Maven wrapper added to the parent directory of generated projects

### ISSUE THREAD

**Issue by fbricon** [quarkusio/quarkus#1657]
Following up on https://github.com/quarkusio/quarkus/issues/1498#issuecomment-475888872:

```
➜  souk mvn io.quarkus:quarkus-maven-plugin:0.12.0:create \
    -DprojectGroupId=foo.bar \
    -DprojectArtifactId=todo-quarked \
    -DclassName="foo.bar.GreetingResource" \
    -Dpath="/hello"
...
[INFO]
[INFO] Maven Wrapper version 0.5.3 has been successfully set up for your project.
[INFO] Using Apache Maven: 3.6.0
[INFO] Repo URL in properties file: https://repo.maven.apache.org/maven2
[INFO]
[INFO]
[INFO] ========================================================================================
[INFO] Your new application has been created in /Users/fbricon/Dev/souk/todo-quarked
[INFO] Navigate into this directory and launch your application with mvn compile quarkus:dev
[INFO] Your application will be accessible on http://localhost:8080
[INFO] ========================================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.927 s
[INFO] Finished at: 2019-03-23T13:18:01-04:00
[INFO] ------------------------------------------------------------------------
➜  souk cd /Users/fbricon/Dev/souk/todo-quarked
➜  todo-quarked ./mvnw quarkus:list-extensions
zsh: no such file or directory: ./mvnw
➜  todo-quarked la
total 16
-rw-r--r--  1 fbricon  staff    53B 23 Mar 13:17 .dockerignore
-rw-r--r--  1 fbricon  staff   3.5K 23 Mar 13:17 pom.xml
drwxr-xr-x  4 fbricon  staff   128B 23 Mar 13:17 src
drwxr-xr-x  6 fbricon  staff   192B 23 Mar 13:19 target
```

Turns out the maven wrapper has been added to the parent directory instead

**Comment by gsmet** [comment]
@geoand so FYI, the Maven project creation behaves differently if the directory is empty or not:
- if the directory is empty, it creates a new project in place and that's probably what we all tested;
- if the directory is not empty, it will create a new project in a new directory and that's where the Maven wrapper should be installed.

@cescoffier I still think we should always create a new directory and have a consistent behavior if it was unclear :)

**Comment by geoand** [comment]
I'm cool with whatever behavior we think is appropriate and will gladly submit a PR to implement it.

**Comment by cescoffier** [comment]
> @cescoffier I still think we should always create a new directory and have a consistent behavior if it was unclear :)

Well, it's more complicated. We need to check if there is a `pom.xml`, if there, check the type, add the sub-module and so on. So yes, we need to do it, but it's not a 15 minutes fix.

**Comment by geoand** [comment]
Why don't we just fail the create process if there is already a `pom.xml` in the directory? 
It seems to me that trying to accommodate cases where the project already exists would be tricky and not obvious to users. From my perspective, when I create a project I start with the idea that it is always a blank slate.

**Comment by gsmet** [comment]
Yes, personally, I would prefer the following behavior:
- create project: create a new project from scratch in a directory named after the artifact name;
- if we want to implement creating a submodule, I would make it a separate command. It's definitely not the same thing you are after and the behavior might be totally different (maybe the property `quarkus.version` should be added to the parent pom for instance). One thing that comes to mind is that I'm really not sure I would like the command to entirely rewrite and reformat my existing pom file (which is what it would do right now).

@geoand for now, I would fix the mvn wrapper addition to take into account where the project is created if it's not too much work. This discussion is a bit orthogonal IMHO.

**Comment by geoand** [comment]
@gsmet makes sense, I'll look into the wrapper part and see how it can be fixed

**Comment by cescoffier** [comment]
Don’t forget that also forcing to ‘cd’ is not very user friendly. (I personally hate having a dir within a dir)

But, I’m not opposed to change this, it’s just requires rechecking all quickstarts as some are based on the current behavior.

**Comment by FroMage** [comment]
Haha, just got bitten by this.

**Comment by geoand** [comment]
It should be fixed in `master` :)
