### ISSUE TITLE
Rest Client Reactive - passing headers with async return type doesn't work

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#16577]
with 
```java
    @GET
    EmployeeDto getByToken(@HeaderParam("MyHeader") String header);
```

passing `MyHeader` works but with the following, it doesn't:
```java
    @GET
    Uni<EmployeeDto> getByToken(@HeaderParam("MyHeader") String header);
```

**Comment by spbolton** [comment]
I think this is related to a bug and pull request I have pushed to resteasy .  The Parameter annotations are being ignored when using Uni https://issues.redhat.com/browse/RESTEASY-2872

**Comment by spbolton** [comment]
My issue was with the regular original REST client when using Uni not the new reactive client,  not sure if this is still using the same code I fixed in the base Resteasy code.

**Comment by michalszynkiewicz** [comment]
@spbolton thanks for adding a comment that might be useful :) 
In this case, the underlying code is completely separate. The fix is awaiting review and should be in Quarkus 2.0 (who knows, maybe even next 1.3.x)
