### ISSUE TITLE
1.13.x WebSocket server root problems

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#16570]
The old Undertow WebSocket root path could be configured via `quarkus.servlet.context-path`.

This does not exist in the new implementation so I tried `quarkus.http.root-path`.  This appears to move the root but now at least in the context of WebSockets (I didn't experiment with REST) both `\` and the new root location both 404. 

This can be reproduced by tweaking the ChatTest example config.

With 1.12.x and `quarkus.servlet.context-path` things work as expected except that the @TestHTTPResource does not adjust to be relative to the new root.  I'm not sure if the intention is that it should.

**Comment by placidetmuzo** [comment]
same here whatever quarkus.http.root-path quarkus.servlet.context-path valuation combinaisons are.

**Comment by geoand** [comment]
Closing for lack of feedback
