### ISSUE TITLE
Quarkus Hibernate-orm-panache-common count throws NoResultException

### ISSUE THREAD

**Issue by mhautman** [quarkusio/quarkus#16573]
**Issue**: When executing a count() on a table which is empty a javax.persistence.NoResultException: No entity found for query is thrown.
**Expected behavior**: Returns 0 if the table is empty.

**The Problem**:

The class located here: https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java

Has this method (and overloaded methods):
```
   public long count(Class<?> entityClass) {
        return (long) getEntityManager(entityClass)
                .createQuery("SELECT COUNT(*) FROM " + PanacheJpaUtil.getEntityName(entityClass))
                .getSingleResult();
    }
```

The call to `getSingleResult()` throws a NoResultException. 

**Proposition**:

Something like : `getResultList().stream().findFirst().orElse(0)`

**Comment by FroMage** [comment]
That sounds like a weird result from your DB. `count(*)` should never return an empty result set, no? What DB is this?

**Comment by mhautman** [comment]
@FroMage It's a Postgres. Now that the table has been filled in it seems to work fine. I deIeted all the rows and it still works fine. I think this happens when the table has never been filled in before and the count is queried programmatically or it's a problem between the desk and the chair.. Sorry for bothering you.

**Comment by FroMage** [comment]
Maybe the table didn't exist? If that was the case, then indeed, it's not the job of this method to pretend that it exists and all went well. It's better to keep throwing, even if the exception could be better.

I'll close this, then, OK?
