### ISSUE TITLE
Simultaneous use of persistence.xml and quarkus.hibernate-orm.* properties is not actually forbidden

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#16589]
## Describe the bug

The [Hibernate ORM guide](https://quarkus.io/guides/hibernate-orm#setting-up-and-configuring-hibernate-orm-with-a-persistence-xml) states:

> If you have a persistence.xml, then you cannot use the quarkus.hibernate-orm.* properties and only persistence units defined in persistence.xml will be taken into account.

But it's not true.

### Expected behavior

We should either remove this statement from the documentation, or actually enforce it and test it correctly.

I'd say unless we have good reasons, we should just allow mixing `persistence.xml` with `application.properties`? I would simply forbid mixing the two for the same persistence unit.

### Actual behavior

We have a test for that: `io.quarkus.hibernate.orm.PersistenceAndQuarkusConfigTest`. This test expects an exception when using a `persistence.xml` and `quarkus.hibernate-orm.*` properties simultaneously. It does yield an exception, but not for the right reason: the persistence.xml is simply invalid (it references a class that doesn't exist). If you fix the `persistence.xml`, all of a sudden no exception is thrown, and the test fails...

## To Reproduce

See how `io.quarkus.hibernate.orm.PersistenceAndQuarkusConfigTest` no longer fails after we fix the `persistence.xml`:

https://github.com/yrodiere/quarkus/tree/pointless-PersistenceAndQuarkusConfigTest

### Configuration
N/A

### Screenshots
N/A

## Environment (please complete the following information):
N/A

## Additional context
N/A

**Comment by yrodiere** [comment]
@Sanne, @gsmet , any opinion on this one?

**Comment by Sanne** [comment]
+1 to forbid using a mix for the same PU.

We should keep allowing the use of a different configuration method for a different PU though.

To be clear our initial plan was that the use of `persistence.xml` would be phased out, but I don't think we ever considered all aspect of such a move.
IMO it's nice to optionally allow a full JPA-spec compliant use, so maybe we should just work on making the use of persistence.xml more robust, but such work would then need to also verify and veto some configuration properties which we don't want to be applicable.

**Comment by yrodiere** [comment]
> +1 to forbid using a mix for the same PU.
> We should keep allowing the use of a different configuration method for a different PU though.

Ok I'll look into that... at some point.

For future reference: the (faulty) test that supposedly checked that one couldn't use `persistence.xml` and `application.properties` in the same app was removed in the first commit of #16630 (because it wasn't testing the right thing).
