### ISSUE TITLE
Quarkus Gradle plugin breaks Gradle incremental compilation

### ISSUE THREAD

**Issue by asodja** [quarkusio/quarkus#16596]
## Describe the bug
After upgrading to Quarkus 1.13.x I've noticed that all modules that use Quarkus plugin are fully rebuilt everytime. That increases our build times. The issue seems to be related to these fixes: https://github.com/quarkusio/quarkus/pull/16214 and https://github.com/quarkusio/quarkus/pull/15365. 

From Gradle logs I get:
```
Task ':server:compileJava' is not up-to-date because:
  Input property 'options.annotationProcessorPath' file /Users/anzes/Downloads/code-with-quarkus/library/build/libs/library-1.0.0-SNAPSHOT.jar has changed.
The input changes require a full rebuild for incremental task ':server:compileJava'.
```

I think that putting whole compile classpath to annotation classpath is in general not a good idea with Gradle, but I might be wrong.

### Expected behavior
Projects are built incrementally.

### Actual behavior
Projects are not built incrementally.

## To Reproduce
Check attached reproducer.
[code-with-quarkus-example.zip](https://github.com/quarkusio/quarkus/files/6327901/code-with-quarkus-example.zip)

1. run ./gradlew compileJava --info -> everything is rebuilt, since it's first compilation
2. run ./gradlew compileJava --info -> nothing is compiled since nothing changed
3. Change String "hello" to "hello1" in LibraryClass.java
4. run ./gradlew compileJava --info -> :library:compileJava is run, :server:compileJava is up-to-date
5. uncomment `id 'io.quarkus'` in server/build.gradle and run ./gradlew compileJava --info two time so compile task are up-to-date
6. Change String "hello1" in LibraryClass.java to  "hello2"
7. run ./gradlew compileJava --info -> :library:compileJava is run and also :server:compileJava with message `The input changes require a full rebuild `
8. Repeat

### Output of `uname -a` or `ver`
MacOS

### Output of `java -version`
Openjdk 11.0.7 2020-04-14

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

Also I noticed that `quarkusGenerateCode` task is not incremental and it's run every time since it does not declare inputs and outputs. But that is unrelated issue :).

**Comment by asodja** [comment]
I was thinking about it a bit more. It's just my opinion: modifying users classpaths/annotation paths by plugin is from my "user" view not a good thing. Since I don't have control over my app. I see some issues here when user defines his own annotation paths, but then plugin overrides it. Also there might be issues with order of annotation processors, for example if user uses lombok.

Maybe it might be the most transparent and bullet proof, to just add warning to plugin's documentation that needs annotation processor and for Gradle it needs also annotation processor set as `annotationProcessor <plugin>`.

**Comment by glefloch** [comment]
Thanks for reporting this @asodja. 
User annotation processor are not lost. We append user annotation processors alongside quarkus annotation processors.
Regarding the order, I think user comes first but I will double check. We can make it configurable if this becomes an issue. 

I don't understand why this triggered a full build. I will check. But if this become an issue we will definitely have to find something else.

**Comment by asodja** [comment]
Thank you for fast response. I believe that full recompilation happens, because Gradle has incremental annotation compilation and that is why a separate annotation classpath. And any change on annotation processor classpath is basically a signal to Gradle: some annotation processor changed, you will have to do a full recompilation otherwise incremental compilation will produce incorrect result.

In this case my understanding is, that since Quarkus adds compile classpath to annotation classpath, any change on compile classpath also triggers annotation classpath change. And so Gradle thinks that some annotation processor was changed and it needs a full recompilation.

**Comment by asodja** [comment]
Just want to check, is there is any news for this being considered?

It's possible to workaround this though, but I would like to avoid this workaround. 
Workaround:
```
tasks.withType(JavaCompile) {
    options.setAnnotationProcessorPath(configurations.getByName(ANNOTATION_PROCESSOR_CONFIGURATION_NAME))
}
```

If it helps I also saw some code how to add dependency to configuration differently, something like:
```
public void apply(Project project) {
    project.afterEvaluate(p -> {
        DependencyHandler dependencyHandler = p.getDependencies();
        dependencyHandler.add("annotationProcessor", "group:module:version")
    })
} 
```
But then again, I did not test this so don't trust me with this :)

**Comment by glefloch** [comment]
@asodja, yes I'm still looking for a way to solve this issue. Actually the incremental compilation is broken on mutli module project. 
As we are setting the `CompileClasspath` dependencies, as the annotation processor configuration each time, you update a module, this configuration is updated and then a full recompilation is needed. 

I'm trying to find a way to filter project dependencies from the annotation processor classpath. This way, incremental compilation should be back, and it will still be possible to get quarkus annotation processors running.

**Comment by asodja** [comment]
Any update on this one?

**Comment by glefloch** [comment]
Not yet but refactoring on the dependency management has been done it should help for this one.
