### ISSUE TITLE
OIDC authentication for websockets doesn't work in 1.13.*

### ISSUE THREAD

**Issue by oberstrike** [quarkusio/quarkus#16602]
As @devauxbr mentioned, the bug is not related to Kotlin and may be fixed in the future.

**Comment by sberyozkin** [comment]
Hi @oberstrike It is hard to do anything about this issue without a reproducer - please create the one for us to have a look

**Comment by oberstrike** [comment]
@sberyozkin its really hard to make a reproducer because it has so many dependencies like keycloak configuration etc. But I'll try my best to do one.

**Comment by devauxbr** [comment]
Hello

I have encountered the exact same issue while upgrading my WebSocket Quarkus app to 1.13+
I don't use Kotlin, but my app relies on a custom `HttpAuthenticationMechanism`. I managed to create a [minimalistic bug reproducer here](https://github.com/devauxbr/quarkus-websocket-auth)

I've been quickly digging through the new quarkus-websocket extension source code. From what I understand, the old extension relied on the legacy Undertow Servlet WebSocket implementation that got the WebSocket Session `Principal` correctly populated from the Servlet layer. The new Vertx implementation does not retrieve the Principal yet (as [this todo](https://github.com/quarkusio/quarkus-http/blob/5eb8e760c9db4434e953a5b6284d4aba6e3572d8/websocket/vertx/src/main/java/io/undertow/websockets/vertx/VertxWebSocketHttpExchange.java#L172) suggests)

Hope this helps ! 🤞

**Comment by devauxbr** [comment]
FWIW I think (guess would be a better phrasing) the work involved in resolving this issue might also be an opportunity to resolve this issue as well ?
https://github.com/quarkusio/quarkus/issues/13565

**Comment by oberstrike** [comment]
Now they have passed 2 month since we found out what the problem is. When will the problem be fixed? Or is there a workaround exist?

**Comment by aldoborrero** [comment]
Care to comment @stuartwdouglas ?

**Comment by aldoborrero** [comment]
Playing around with the code, inside `VertxWebSocketHttpExchange` we do have access to the original `RoutingContext` in the class attribute `exchange`.

![image](https://user-images.githubusercontent.com/82811/133102173-3b635134-78ca-432e-bf24-6bef95c14f1c.png)

Upon closer inspection, I can see the `principal` is correctly populated inside the map the `exchange.data()` map like we can see below:

![image](https://user-images.githubusercontent.com/82811/133102574-7364aced-a981-4c36-bc2a-b6ce3f9c5c97.png)

It is safe to assume that we can return directly that object in method `getUserPrincipal`? Or is there any other implication I'm not taking into account (which will be probably)?
