### ISSUE TITLE
Health check for quarkus-smallrye-reactive-messaging-amqp reports UP when message broker is down

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#16603]
## Describe the bug
My application uses quarkus-smallrye-reactive-messaging-amqp to connect to Apache Artemis.
When application is starting up and can't connect to Artemis, `/q/health` endpoint correctly reports `[DOWN]`.
When Artemis becomes available, application's health endpoint correctly reports `[UP]`.
But when Artemis goes down again and application loses connection with it, the health endpoint keeps reporting `[UP]`.

### Expected behavior
As documented in https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.9/amqp/amqp.html#amqp-health
> On the inbound side (receiving messages from AMQP), the check verifies that the receiver is attached to the broker.
> On the outbound side (sending records to AMQP), the check verifies that the sender is attached to the broker.

I expect health endpoint to report `[DOWN]` when connection to Artemis is lost.

### Actual behavior
Health endpoint keeps reporting `[UP]` when connection to Artemis is lost.

## To Reproduce

Application class using reactive messaging annotations:
```java
package com.example;

import org.eclipse.microprofile.reactive.messaging.Incoming;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class MessageProcessor {

  @Incoming("my-queue")
  public void onIncoming(String payload) {
    System.out.println(payload);
  }
}
```

Test class:
```java
package com.example;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import org.apache.activemq.artemis.core.config.impl.ConfigurationImpl;
import org.apache.activemq.artemis.core.server.embedded.EmbeddedActiveMQ;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.awaitility.Awaitility.await;

@QuarkusTest
public class ReactiveMessagingHealthCheckTest {

  @Test
  void health_test() throws Exception {
    assertHealthStatusCode(503);

    EmbeddedActiveMQ broker = startMessageBroker();

    await().atMost(Duration.ofSeconds(10)).untilAsserted(() -> assertHealthStatusCode(200));

    broker.stop();

    await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> assertHealthStatusCode(503));
  }

  private static void assertHealthStatusCode(int status) {
    RestAssured.when().get("/q/health")
        .then().statusCode(status);
  }

  private static EmbeddedActiveMQ startMessageBroker() throws Exception {
    EmbeddedActiveMQ broker = new EmbeddedActiveMQ();
    ConfigurationImpl config = new ConfigurationImpl();
    config.setSecurityEnabled(false);
    config.setPersistenceEnabled(false);
    config.addAcceptorConfiguration("tcp", "tcp://localhost:5672?protocols=AMQP");
    broker.setConfiguration(config);
    broker.start();
    return broker;
  }
}
```

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>quarkus-grpc-retry</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <quarkus.version>1.13.1.Final</quarkus.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>quarkus-build</id>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-universe-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-reactive-messaging-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-server</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-amqp-protocol</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

### Configuration
```properties
mp.messaging.incoming.my-queue.connector=smallrye-amqp

amqp-host=localhost
amqp-port=5672

quarkus.http.port=8080
quarkus.http.test-port=8080
```

## Environment

* Output of `uname -a`: `Linux 5.4.80-gentoo-r1 #2 SMP Sun Feb 7 16:10:48 MSK 2021 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux`
* Output of `java -version`: `openjdk version "11.0.9.1" 2020-11-04 LTS`
* GraalVM version (if different from Java): none
* Quarkus version or git rev: `1.13.1.Final`
* Build tool: `Apache Maven 3.6.3`

**Comment by cescoffier** [comment]
The behavior is "expected". Let me explain (and we should improve that).

The AMQP connector has a retry policy. By default, it retries 100 times, with exponential back-off. It does not report "down" until all these retries have been attempted.
The retry is configured as follows:

```
  .onFailure().retry().withBackOff(ofSeconds(1), ofSeconds(retryInterval)).atMost(retryAttempts)
```

`retryInterval` is 10 by default, and `retryAttempts` 100 by default.

In your test, you wait for 30 seconds. However, that does not give enough time for the connector to "fail" (the connector is still retrying). 

On my machine, I was able to get your test passing with:

```
mp.messaging.incoming.my-queue.reconnect-attempts=5
mp.messaging.incoming.my-queue.reconnect-interval=1
```

**Comment by vladykin** [comment]
Thanks for explanation. That should definitely be added to the documentation.

With the reconnect properties you suggested, the test passed for me too. However I have additional questions on this.

Am I correct that after exhausting retries the application enters a non-recoverable state, where it no longer attempts any reconnects and will never succeed in sending/receiving any messages to/from message broker?

I added a second start of Artemis to the test and never see health endpoint returning `[UP]` again:
```
  @Test
  void health_test() throws Exception {
    assertHealthStatusCode(503);

    EmbeddedActiveMQ broker = startMessageBroker();

    await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> assertHealthStatusCode(200));

    broker.stop();

    await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> assertHealthStatusCode(503));

    broker = startMessageBroker();

    await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> assertHealthStatusCode(200));
  }
```

**Comment by vladykin** [comment]
And a second question. Suppose an application with REST API, which sends messages to @Outgoing channel as part of incoming REST request processing.

With the current algorithm of health reporting, the application loses connection with broker but continues reporting itself as ready. It means k8s keeps sending REST requests to the application, but they can't be successfully processed, because message broker is down.

What is the recommended approach if I want to detect problems with message broker and report `[DOWN]` from health endpoint to prevent k8s from routing REST requests to the application during message broker outage? But as soon as message broker comes back, I want the health endpoint to return `[UP]` again and start accepting REST requests.

**Comment by cescoffier** [comment]
Tes, once the retires have been exhausted, the connector considered this failure as fatal. As a consequence, it switches the liveness check to false and applies a "let it crash" pattern (a supervisor would kill it and restart it).

For your second question, you would have to implement your own check. At the moment both readiness and liveness (in the AMQP connector) have the same logic. It would make sense to distinguish both. However, as said in another issue, the  AMQP connector is behind in terms of features.

**Comment by vladykin** [comment]
Ok, got it, thanks again.

So, this discussion results in two follow-up enhancement requests:
* document what health endpoint actually returns taking into account reconnect attempts --- it was not obvious at all
* extend AMQP connector to separately report readiness and liveness (readiness indicates if connection to broker is available right now, liveness indicates if we still have hope to reconnect)

Meanwhile I've implemented a custom readiness check testing broker availability with `AmqpClient.connect()`.
BTW, is there any API in reactive-messaging-amqp allowing me to get current connection status without creating and configuring my own AmqpClient?

**Comment by cescoffier** [comment]
Forgot to close this issue, but this has been integrated.
