### ISSUE TITLE
migrate from master to main in quarkiverse

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16601]
## Description
ecosystem-ci repo default branch are being renamed from master to main. need to update all the quarkiverse repos.

We want to rename the https://github.com/quarkusio/quarkus-ecosystem-ci default branch from `master` to `main`, however by doing so, this might break the builds for a CI participant unless a small update to their `.github/workflows/quarkus-snapshot.yaml` files is performed. The change is simple and should work with your current build as of today:

We kindly ask the extension maintainers to remove the `ref` attribute in their `quarkus-snapshot.yaml` files. See https://github.com/quarkiverse/quarkus-prettytime/commit/298127569dd5f3e89bf3c6d07ee8e4b3fcf9cd2e if you need help.
New extensions generated through the plugin already have this change. If your action YAML does not have the `ref` you're all set :)

We're planning to change the branch name on May 3rd, so make sure to perform that change in your repositories by then.

## Implementation ideas
search replace and submit pr

**Comment by maxandersen** [comment]
step 1: git clone all quarkiverse quarkus extensions:
```
GHORG=quarkiverse; curl "https://api.github.com/orgs/$GHORG/repos?per_page=1000" | grep 'clone_url' | grep -o 'https[^"]*' | grep /quarkus | xargs -L1 git clone
```

step 2: remove all ref: master lines
```
find . -name quarkus-snapshot.yaml | xargs -L1 sed -i '' '/ref: master/d'
```

if on non-osx use `sed -i` without ''

step 3: add the expected file:
```
ls -1 | xargs -L1 -I xx git -C xx add .github/workflows/quarkus-snapshot.yaml
```

step 4: fork all repos using hub
```
ls -1 | xargs -L1 -I xx hub -C xx fork
```

step 5: switch branch
```
ls -1 | xargs -L1 -I xx hub -C xx co -b ecosystemdefaultbranch
```

step 6: commit locally 
```
ls -1 | xargs -L1 -I xx hub -C xx commit -m "migrate from master to main in quarkiverse. Fixes https://github.com/quarkusio/quarkus/issues/16601"
```

step 7: push to own branch
```
ls -1 | xargs -L1 -I xx hub -C xx push maxandersen ecosystemdefaultbranch
```

step 8 create shared pr msg:
```
 echo update to use default branch from ecosystem > prmsg.txt
echo > prmsg.txt
 echo >> prmsg.txt
echo ecosystem are renaming its branch on May 3rd. Please merge this before this date. >> prmsg.txt
echo Details at https://github.com/quarkusio/quarkus/issues/16601 >> prmsg.txt
 echo cc @gastaldi >> prmsg.txt
```

step 9: submit prs
```
ls -1 | xargs -L1 -I xx hub -C xx pull-request -F prmsg.txt
```

**Comment by gastaldi** [comment]
Fantastic! Thank you so much!

**Comment by maxandersen** [comment]
keeping it open until all prs closed.
