### ISSUE TITLE
System.out.println breaks quarkus

### ISSUE THREAD

**Issue by domdorn** [quarkusio/quarkus#1661]
When changing a few lines in 
quarkus-quickstarts/hibernate-orm-panache-resteasy/src/main/java/com/acme/hibernate/orm/panache/FruitResource.java
![image](https://user-images.githubusercontent.com/100349/54885513-3ba41b80-4e7d-11e9-9f50-535bf5d82f8c.png)

I'll get this exception
![image](https://user-images.githubusercontent.com/100349/54885515-42329300-4e7d-11e9-9135-bcb2f76cc88d.png)

`
OpenJDK GraalVM CE 1.0.0-rc13 (build 25.202-b08-jvmci-0.55, mixed mode)
`

quarkus then cannot start anymore. If I remove the System.out.println's, it works again..

**Comment by gsmet** [comment]
Which version of Quarkus do you use? It seems you have the old error page. It's not related to your issue but it seems weird.

Could you try forcing the usage of the latest ASM version in your dependencies:
```
<dependency>
        <groupId>org.ow2.asm</groupId>
        <artifactId>asm</artifactId>
        <version>7.1</version>
</dependency>
```
?

We worked on an upgrade for the next release but it's not yet included.

**Comment by domdorn** [comment]
@gsmet I've used master of `https://github.com/quarkusio/quarkus-quickstarts` with this revision:
```
commit 84ac2852bb9354908cff6f5d0e2c349f0336ac14
Merge: b6bf55a d689ea6
Author: Clement Escoffier <clement.escoffier@gmail.com>
Date:   Tue Mar 12 07:55:40 2019 +0100
```

**Comment by gsmet** [comment]
OK, that explains why you have the old error page.

Could you test with the ASM upgrade and report back? Thanks!

**Comment by cescoffier** [comment]
Can you also mention your _regular_ JVM version? (are you using the GraalVM version to run the dev mode)

**Comment by FroMage** [comment]
Given that this is a few versions behind, I'll close it assuming it has been fixed now. Don't hesitate to reopen if you can reproduce with the latest version.
