### ISSUE TITLE
Introduce versions of ClientRequestFilter and ClientResponseFilter that can suspend and resume

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#16615]
## Description

In RESTEasy Reactive we have the `ResteasyReactiveContainerRequestFilter` and `ResteasyReactiveContainerResponseFilter` which can suspend and resume thus allowing for non-blocking filters.

We should have something similar for the client

Originally came up in https://github.com/quarkusio/quarkus/issues/16523

**Comment by FroMage** [comment]
Well OK, but then also exception mappers, no? ;)

**Comment by geoand** [comment]
Yup

**Comment by geoand** [comment]
But probably later, cause I don't know if/how are handling the exception mapper for the client

**Comment by FroMage** [comment]
Sure, those are not linked.

**Comment by geoand** [comment]
I opened a new issue: https://github.com/quarkusio/quarkus/issues/16626

**Comment by FroMage** [comment]
Damnit, man, I'm sorry I misread this issue. I thought you were talking about annotation-declared client requests and filters, and I suggested adding annotation-declared exception mappers. I didn't realise I had mis-read the subject. I don't think exception mappers can suspend on the server-side, can they?

**Comment by geoand** [comment]
No need to apologize, you likely read the correct thing :)
What happened is that when I opened the issue initially, I did mention the annotations. Howeve then I realised that the client doesn't automatically register filters, so I then changed the title and description to only mention suspend and resume.

As for exception mappers, they can resume on server

**Comment by FroMage** [comment]
Hahahaha, excellent :)

**Comment by FroMage** [comment]
> However then I realised that the client doesn't automatically register filters

Huh, is that by design or because we forgot?

**Comment by geoand** [comment]
I think it's just how the JAX-RS client works by spec - if it worked otherwise, the TCK would have a ton of failing tests :)

**Comment by geoand** [comment]
Yeah, I like the idea.
Up until today I actually thought that the filters where automatically registered
