### ISSUE TITLE
Cannot access Quarkus microservices running in wsl 2 from windows when using development mode.

### ISSUE THREAD

**Issue by harrison-nc** [quarkusio/quarkus#16610]
## Describe the bug
I have a quarkus application in WSL 2 using Maven. While building the application in development mode with `mvn compile quarkus:dev` I can access it with cURL or Httpie in WSL.  But, connecting to the application from windows using a browser fails.

However, when the application is packaged and the jar is run with `java -jar path/to/jar` it can be access from both WSL and Windows. 
I tried running the application in development mode using different versions of quarkus (see below). The application works well on version `1.9.x.Final` but fails on all the versions after it. 
It seems, that starting with version `1.10.x` the quarkus development loop server does not expose applications running in WSL 2 to Windows.

### Expected behavior
The application should be accessible from windows when the URL is entered in the browser (e.g. Edge, Firefox, etc.). 

### Actual behavior
Opening the URL in any browser fails to connect. However, the URL can be accessed using cURL or Httpie inside WSL 2.

## To Reproduce

1. Goto [Quarkus starter](https://code.quarkus.io/?e=resteasy) and download a project that uses only `resteasy` extension.
2. Open the project in WSL 2 and run `mvn compile quarkus:dev`
3. Open a browser in windows (I used Edge and Firefox) and enter the URL of the application (e.g. `http://localhost:8080`)

### Output of `uname -a`
Linux aspire 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### Output of `java -version`
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Quarkus version or git rev

Tried the following version but didn't get the expected behavior.
1. `1.13.2.Final`
2. `1.13.1.Final`
3. `1.13.0.Final`
4. `1.12.0.Final`
5. `1.11.3.Final`
6. `1.11.0.Final`
7. `1.10.5.Final`
8. `1.10.3.Final`

I got the expected behavior while running on Quarkus version `1.9.x`.

### Build tool
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/harrison/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /home/harrison/tools/jdk-11.0.2
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"

## Additional context
The project files and development tools are stored in WSL 2. 

Best regards.
Harrison.

**Comment by geoand** [comment]
The change is behavior you are seeing is due to https://github.com/quarkusio/quarkus/pull/13223.

The fact that it doesn't work well in WSL2 seems to be a bug of WSL2 itself, see https://github.com/microsoft/WSL/issues/5298.

Apart from the workarounds mentioned in that issue, you can also specify `quarkus.http.host=0.0.0.0`.
