### ISSUE TITLE
Local information disclosure vulnerability in the Netty version from 1.13.2.Final

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#16625]
Quarkus `1.13.2.Final` depends on netty `4.1.49.Final` which suffers from [this vulnerability](https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2) which was fixed in netty `4.1.59.Final`

I saw that netty was updated to `4.1.60.Final` on `main` because of Vert.x 4.

Would it be possible to update netty to either `4.1.59.Final` or `4.1.60.Final` in the next `1.13` release (assuming there's one)?

**Comment by cescoffier** [comment]
Not really, Quarkus and Vert.x are not impacted by the CVE as we don't use the `AbstractDiskHttpData` class.

**Comment by gwenneg** [comment]
That's good to know, thanks for the info @cescoffier.
