### ISSUE TITLE
io.quarkus.mailer.MailTemplate - mailer doesn't send email messages on Quarkus 1.12.2.Final and higher

### ISSUE THREAD

**Issue by tom3cz** [quarkusio/quarkus#16635]
![image](https://user-images.githubusercontent.com/82838494/115286811-cd131400-a14f-11eb-8682-aacf857b19e4.png)

I am sending emails as in the above screenshot, using this https://quarkus.io/guides/mailer. I have made upgrade from Quarkus 1.11.1Final to the newest 1.13.2 and this approach stoped sending emails. There is no error, even in debug mode. Email is not sending (with quarkus.mailer.mock is not printed to system out as well).

I have checked and it works fine on version up to 1.11.6.Final and not works on 1.12.2.Final.

**Comment by gsmet** [comment]
My guess is that it's because it now returns a `Uni` and you need to subscribe to it or it doesn't execute anything.

/cc @cescoffier

**Comment by cescoffier** [comment]
As @gsmet said, it now returns a Uni and you need to subscribe to trigger the operation (sending the email). You can use: subscribeAsCompletionStage() to send the email and ignore the outcome. You can also use subscribe().with(x -> success, t -> failed) method.

**Comment by cescoffier** [comment]
Closing. The solution is in the previous comment.
