### ISSUE TITLE
SSL: Missing HTTPS protocol when building in Native

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16651]
## Describe the bug

According to the guide `https://quarkus.io/guides/native-and-ssl`, for native, the next SSL configuration needs to be set:

```
-H:EnableURLProtocols=http,https --enable-all-security-services -H:+JNI
```

The problem is that these properties are not being set by default:
- Creating a new app using Maven command line:

```
mvn io.quarkus:quarkus-maven-plugin:1.13.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=rest-json-quickstart \
    -DclassName="org.acme.rest.json.FruitResource" \
    -Dpath="/fruits" \
    -Dextensions="resteasy,resteasy-jackson"
cd rest-json-quickstart
```

Adding the `server.keystore` into `src/main/resources/META-INF/resources`.
Having the properties:

```
quarkus.http.ssl.certificate.key-store-file=META-INF/resources/server.keystore
quarkus.http.ssl.certificate.key-store-password=password
```

It seems that I need to provide also the following property:

```
quarkus.ssl.native=true
```

And also I think the guide should say that the ssl certificates should be under the `src/main/resources/META-INF/resources` folder.

### Quarkus version or git rev
1.13.2.Final

**Comment by Sgitario** [comment]
It seems that I need to provide the following property when creating a new application:

```
quarkus.ssl.native=true
```

This should be noted in the guide though. But I'm not sure why it works fine from the quickstarted. Any ideas?

**Comment by gsmet** [comment]
> And also I think the guide should say that the ssl certificates should be under the src/main/resources/META-INF/resources folder.

but doesn't it make your keystore publically accessible?

**Comment by gsmet** [comment]
I added some details here: https://github.com/quarkusio/quarkus/pull/16687

**Comment by Sgitario** [comment]
> I added some details here: #16687

The new details in the PR are sufficient for my point of view to resolve this issue. Thanks for looking into this!
