### ISSUE TITLE
gradle quarkusDev task not reading .env

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#16659]
## Describe the bug
I have a `.env` file in my project directory, but when I run `quarkusDev`, the environment variables don't exist.

### Expected behavior
```java
System.getenv("TEST"); // is "foo"
```

### Actual behavior
```java
System.getenv("TEST"); // is null
```

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. `gradlew myproject1:quarkusDev`
2. attach debugger to running service

### Configuration
file structure
```
- repo
  - myproject1
      - .env
      - build.gradle
      - src/ 
```

build.gradle
```gradle
...
quarkusDev {
    workingDir = projectDir
}
...
```

.env
```properties
TEST=foo
```

### Output of `uname -a`
git bash
MINGW64_NT-10.0

### Output of `java -version`
openjdk 11.0.4 2019-07-16

### Quarkus version
1.11.0

### Build tool
Gradle 6.3

**Comment by mweber03** [comment]
Another example.

I pulled this repository: https://github.com/mkyong/quarkus

Added: `quarkus-hello-world-gradle/.env` with contents
```
TEST_ENV=foo
```

Updated: `quarkus-hello-world-gradle/src/main/java/com/mkyong/quarkus/HelloResource.java` with
```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return System.getenv("TEST_ENV"); // added this
    }
```

Still no luck. This project uses Quarkus 1.11.0

**Comment by glefloch** [comment]
Thanks for reporting this. 
Actually I don't think this is a bug. Variables in `.env` file are used by `smallrye-config` to populate your config properties alongside your `application.properties` file.

If you declare the following property, it should be correctly populated: 

    @ConfigProperty(name = "test.env")
    String env; 

Am I right @radcortez ?

**Comment by radcortez** [comment]
Yes, but the `.env` file needs to reside in the working directory. I'll give it a try , maybe there is some issue with Gradle.

**Comment by radcortez** [comment]
Just tried it with the sample project and it does work.

I've just noticed that @mweber03 is using `System.getenv`. While it seems to make sense the JDK API does not read from `.env` files. This is done by SmallRye Config, our config implementation and you need to use the Config API to retrieve the values. Either by using injection like @glefloch suggested or you can also do it programmatically like:

```java
ConfigProvider.getConfig().getValue("test.env",String.class);
```

**Comment by mweber03** [comment]
So I guess there's no way to get traditional environment variables into the `quarkusDev` task?

Basically I'm migrating some of our services to Quarkus and we previously had `JavaExec` tasks to run the dev mode (which has `environment` properties to set environment variables). But it sounds like we would have to migrate all of our internal `System.getenv` references to the microprofile config before we can use `quarkusDev`? Which makes this migration a bit more tricky since my group doesn't own some of the code..

**Comment by radcortez** [comment]
I guess it could work if we made some changes to read the `.env` file in the quarkus dev mode runner and pass them to the running process.

But there are things that are not going to work, like configuration override, profiles, property expansion etc. 

TBH, I don't we should support this, because we would have to support loading of all properties as well to make `System.getProperty` consistent and I think it is going to be confusing to have two inconsistent ways to access Quarkus configuration.

**Comment by mweber03** [comment]
I appreciate the clarification, we're going to look into migrating our baseline fully to the microprofile config. But I will say, the documentation for dev mode is kind of misleading then because the `.env` file is just another config properties file, not environment variables as they are traditionally understood.

**Comment by radcortez** [comment]
I'll add some clarifications in the documentation.
