### ISSUE TITLE
@Cacheable with hibernate quarkus not working

### ISSUE THREAD

**Issue by ivanjunckes** [quarkusio/quarkus#16660]
## Describe the bug
The hibernate cache is not working with @Cacheable in Quarkus

### Expected behavior
Be able to cache a query

### Actual behavior
Cache is not working

## To Reproduce

https://github.com/ivanjunckes/quarkus-hibernate-cache-example

1. Execute mvn clean install
2. UserResourceTest

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### Quarkus version or git rev
1.13.2
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn 3.6.3
## Additional context
(Add any other context about the problem here.)

**Comment by Sanne** [comment]
hi @ivanjunckes ! I've had a look at your reproducer.

There's a couple mistakes:

1. You need to enable statistics `quarkus.hibernate-orm.statistics=true`
2. On the `Statistics` object, use `getQueryExecutionCount()` and `getQueryCacheHitCount`. Query Cache is not the same as entity cache.
3. It can't use the actual query cache as you have uncommitted changes pending in the current transaction; this would potentially lead to inconsistencies. If you persist the test entities first in a different transaction, and then try to query them multiple times you'll see that it works.

But I'll take the opportunity to add a test to Quarkus as it seems to be missing, so you had me worried there for a minute :)

Thanks!
