### ISSUE TITLE
encoding problems in log file

### ISSUE THREAD

**Issue by steelcg** [quarkusio/quarkus#16668]
## Describe the bug
when using Chinese text in logging file, the encoding of the log file will chang from UTF-8 to ansii

### Expected behavior
the encoding of the log file should aways be UTF-8

### Actual behavior
the encoding of the log file changes from UTF-8 to ansii

## To Reproduce

i uploaded the project.

1. package the project with "mvnw package"
2. run the application with "java -jar target/quarkus-app/quarkus-run.jar
3. check the log file "qurkus.log" in log folder and you will see the encoding is "UTF-8"
4. access the url "http://localhost:8080/resteasy-jackson/quarks/" then check the log file again, you will see the encoding is "ANSII" now.

### Configuration
```properties
refer to the project file

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)
![2021-04-21 10_48_28-log](https://user-images.githubusercontent.com/38218864/115490759-51b97b80-a291-11eb-84ff-73f8bfc48bbf.png)
![encoding changed](https://user-images.githubusercontent.com/38218864/115490709-3189bc80-a291-11eb-9a2c-8bba64ed26e5.png)

## Environment (please complete the following information):
windows 10
### Output of `java -version`
1.8

### Quarkus version or git rev

1.13.2.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\lich72\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Additional context
![encoding changed](https://user-images.githubusercontent.com/38218864/115490709-3189bc80-a291-11eb-9a2c-8bba64ed26e5.png)

(Add any other context about the problem here.)

**Comment by steelcg** [comment]
[quarkus-logging-encoding-problems.zip](https://github.com/quarkusio/quarkus/files/6347747/quarkus-logging-encoding-problems.zip)
project

**Comment by manuelbl** [comment]
Text files do not save the encoding. So Notepad++ guesses what the encoding is. In this case, Notepad++ has certainly made in incorrect guess.

Open the log file explicitly with UTF-8 and see if that fixes the problem.

**Comment by steelcg** [comment]
> Text files do not save the encoding. So Notepad++ guesses what the encoding is. In this case, Notepad++ has certainly made in incorrect guess.
> 
> Open the log file explicitly with UTF-8 and see if that fixes the problem.


![encoding](https://user-images.githubusercontent.com/38218864/115508654-25f9be00-a2b0-11eb-9758-ace7c9781d7f.png)
that donesn't fix the problem
This point of the problem is why these text wasnot written to file with out UTF-8 encoded.
```java
import org.jboss.logging.Logger;
    @Inject
    Logger logger;
    @GET
    public Set<Quark> list() {
        logger.info("English: " + "abcd");
        logger.info("German: " + "ä, ö ,ü");
        logger.info("Chinese: " + "中文");
        return quarks;
    }
```

**Comment by manuelbl** [comment]
Independent of the log message, the log file is written in the platform's default encoding. This applies whether Chinese text is used or not. Unfortunately, the default encoding on most Windows machine is usually country-specific instead of a universal encoding like UTF-8. The problem hardly exists on Linux and macOS as they have switched to UTF-8 some time ago.

As far as I can tell the fact that the file encoding defaults to the platform default instead using UTF-8 across all platforms is a behavior inherited from the underlying JBoss log manager.

As a quick solution, you can change the default encoding when starting the application:

```
java -jar target/quarkus-app/quarkus-run.jar
```

Additionally, it would probably make sense to create a feature request in order to make the log file encoding configurable and possibly default to UTF-8.

**Comment by steelcg** [comment]
@manuelbl Thanks for your support.

**Comment by geoand** [comment]
Closing as per [this](https://github.com/quarkusio/quarkus/issues/16668#issuecomment-823870855) analysis
