### ISSUE TITLE
Cannot enable Swagger UI via Quarkus profile

### ISSUE THREAD

**Issue by jfrantzius** [quarkusio/quarkus#16698]
## Describe the bug
The property `quarkus.swagger-ui.always-include` is a build time property, and so it should be possible to set `quarkus.swagger-ui.always-include=true` via Quarkus profiles, i.e. define it per profile in `application.properties`. When I try this and then successfully activate the profile at runtime, Quarkus still says "RESTEASY003210: Could not find resource for full path: http://localhost:8080/q/swagger-ui/".

(I got encouraged by https://github.com/quarkusio/quarkus/issues/7594#issuecomment-595212632 , )

### Expected behavior
Swagger UI should be accessible when switched on via profile.

### Actual behavior
"RESTEASY003210: Could not find resource for full path: http://localhost:8080/q/swagger-ui/"

## To Reproduce
1. Download and unpack [swagger-ui.zip](https://github.com/quarkusio/quarkus/files/6352749/swagger-ui.zip)
2. verify that reproducer contains swagger-ui by running `mvn compile quarkus:dev` and opening http://localhost:8080/q/swagger-ui/ 
2. `./mvnw package`
3. `export QUARKUS_PROFILE=dev-environment`
4. `java -jar target/quarkus-app/quarkus-run.jar`
5. open http://localhost:8080/q/swagger-ui/ 

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
[swagger-ui.zip](https://github.com/quarkusio/quarkus/files/6352749/swagger-ui.zip)

### Configuration
```properties
quarkus.swagger-ui.always-include=true
%dev-environment.quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.always-include=false
```

### Output of `uname -a` or `ver`
Both on Mac and also reproducible in Docker image via quarkus-container-image-jib

### Output of `java -version`
openjdk 14.0.2 2020-07-14

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by phillip-kruger** [comment]
Hi @jfrantzius

As you notes, that property is a build time property, so when you "change" it, to take effect you will to rebuild. So step 3 and 4 needs to switch around.

1.     Download and unpack swagger-ui.zip
2.     verify that reproducer contains swagger-ui by running mvn compile quarkus:dev and opening http://localhost:8080/q/swagger-ui/
4.     export QUARKUS_PROFILE=dev-environment
3.     ./mvnw package
5.     java -jar target/quarkus-app/quarkus-run.jar
6.     open http://localhost:8080/q/swagger-ui/

You can also look at [quarkus.swagger-ui.enable](https://quarkus.io/guides/openapi-swaggerui#quarkus-swaggerui_quarkus.swagger-ui.enable)  that is a runtime property that allows you to enable/disable the UI

**Comment by jfrantzius** [comment]
Thanks a lot @phillip-kruger , `quarkus.swagger-ui.enable` does the trick for me, I wasn't aware of that flag. It seems that the documentation for it may be wrong, or behaviour may not be as expected, though: 
> "If Swagger UI is included, it should be enabled/disabled. By default, Swagger UI is enabled if it is included (see always-include)."

I did set `quarkus.swagger-ui.always-include=true`, but have to additionally set `quarkus.swagger-ui.enable=true`  in order for it to work (when not running in dev mode).
