### ISSUE TITLE
Quarkus MTLS auth SecurityIdentity empty if `quarkus.http.ssl.client-auth` is loaded from a profile

### ISSUE THREAD

**Issue by mcsweeneyjm** [quarkusio/quarkus#16694]
## Describe the bug
When attempting to do MTLS auth in Quarkus, the `SecurityIdentity` does not have the certificate information if I have the `quarkus.http.ssl.client-auth:request` property in a profile in `application.properties`. If I move this property out to the top-level outside of a profile, the certificate will load. I'm also testing this in Docker, so that might be relevant as well.

### Expected behavior
I would expect that, if provided a certificate, the SecurityIdentity would be loaded with the certificate information so that I can use it for further role management. 

### Actual behavior
The SecurityIdentity contains no certificate information.

## To Reproduce
link to a reproducer here: https://github.com/mcsweeneyjm/quarkus-mtls-issue (it is gradle, I can use maven instead if needed but the issue is possibly due to how gradle handles profiles as well?) 

1. Move `quarkus.http.ssl.client-auth:request|required` to be loaded from a profile instead of the top-level of the properties.
2. Send an HTTPS request to the project with a client certificate provided
3. Attempt to access the certificate information

### Configuration
```properties
quarkus.http.ssl-port=8443
quarkus.http.insecure-requests=disabled

quarkus.http.ssl.certificate.key-store-file=META-INF/resources/keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
quarkus.http.ssl.certificate.trust-store-file=META-INF/resources/truststore.jks
quarkus.http.ssl.certificate.trust-store-password=password
quarkus.http.auth.proactive=false

%issue.quarkus.http.ssl.client-auth=request

```

### Output of `uname -a` or `ver`
`Darwin macbook-m1 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64`

(does happen on an intel mac as well ;) )

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

### GraalVM version (if different from Java)
N/A

### Quarkus version or git rev
no version set, so presumably just `latest`? 
`quarkus-security 1.1.4.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
`Gradle 6.8.3`

**Comment by sberyozkin** [comment]
@mcsweeneyjm Thanks, based at what you said in the Zulip thread I'm assuming for now it is a configuration issue (i.e it works if it is a top level property). CC @radcortez

**Comment by sberyozkin** [comment]
Hi @mcsweeneyjm closing this issue given the explanation from Rene Grob in the linked Zulip thread - please re-open if you feel something needs to be done about this issue, thanks
