### ISSUE TITLE
Dev UI does not use embedded.html when extension module is in same project as application

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#16699]
## Describe the bug
When a Quarkus app is in the same project as a local extension, the extension's embedded.html will be ignored in Dev UI

### Expected behavior
The extension's embedded.html will be shown in Dev UI

### Actual behavior
The extension's embedded.html is not shown in Dev UI

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
https://github.com/Christopher-Chianelli/issue-reproducer/tree/quarkus-dev-ui-ignore-local-extension-embedded-html

1. `cd my-ext/integration-tests/`
2. `mvn quarkus:dev`
3. Navigate to the Quarkus Dev UI at localhost:8080/q/dev
4. Note that the embedded.html of the extension was ignored (the extension's tile should have the String "Custom embedded.html is being used!" in it.)

Note this is only for local extensions; performing the above steps in the `/external-app` directory results in the `embedded.html` being used.

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
Running from  `my-ext/integration-tests/` (Actual Behaviour)
![actual-behaviour](https://user-images.githubusercontent.com/15825810/115601861-47f14180-a2ac-11eb-8fc5-a7fbb81f48d9.png)

Running from `external-app` (Expected Behaviour):
![expected-behaviour](https://user-images.githubusercontent.com/15825810/115602058-8424a200-a2ac-11eb-9902-13ae5c1991c2.png)

### Output of `uname -a` or `ver`
Fedora 33

### Output of `java -version`
openjdk 11.0.10 2021-01-19

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context
(Add any other context about the problem here.)

**Comment by mkouba** [comment]
It seems that Dev UI only considers templates located in jar files: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/DevConsoleProcessor.java#L585

In this particular case, the URL points to a directory, .e.g. the `file://` protocol is used.

**Comment by mkouba** [comment]
The problem is that we can't easily read the `groupId` and `artifactId` from the file path of a `-deployment` module, e.g. `/my/source/my-ext/deployment/target/classes/dev-templates`.

@FroMage WDYT?

**Comment by FroMage** [comment]
This seems like a pretty edge case, running dev mode inside an extension. If there's a quick hack we can do to make it work, then why not, but it doesn't seem to be a very useful requirement, no?

**Comment by Christopher-Chianelli** [comment]
It also occurs when the extension in in the same project (note the root of my reproducer doesn't have a pom for this reason). I sometime create one-off extensions for projects (ex: an irc-bot extension that read annotations and automatically sets up the bot). I came into this issue when trying to test the Dev UI for my extension; at the very least, a warning should be shown that Dev UI won't be available for local extensions (if it can't be easily fixed).
