### ISSUE TITLE
Document various ways how to integrate extension with CDI/ArC

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#1669]

**Comment by gsmet** [comment]
@mkouba do you still plan to do it? If so, maybe add the `pinned` label.

**Comment by gastaldi** [comment]
Isn't this done yet @mkouba ?

**Comment by mkouba** [comment]
Yes, [more or less](https://quarkus.io/guides/cdi-reference#build_time_apis) ;-). I think tha we can close this issue now.
