### ISSUE TITLE
Rest Client Reactive - Filters not executed for non-successful return codes

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#16702]
CC @geoand I will try to attach a minimal reproducer tomorrow

**Comment by geoand** [comment]
That would be great, thanks

**Comment by michalszynkiewicz** [comment]
AFAIR the MicroProfile TCK tests this by returning an erroneous response from a filter, maybe JAX-RS one does it this way too?

**Comment by geoand** [comment]
Not sure TBH.

BTW, reading https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/reactive.20server.20.26.20client it seems like that issue was about `ExceptionMapper` classes, but this issue is about ClientResponseFilters. Is that intentional?

**Comment by geoand** [comment]
Ah, now I see how it works.

So basically the rest-client engages `ResponseExceptionMapper` by implementing a `ClientResponseFilter`, so the problem is actually that `ClientResponseFilter` is not executed when an exception is thrown.

**Comment by michalszynkiewicz** [comment]
Running the test from the [example project](https://github.com/quarkusio/quarkus/files/6356676/wrong-status-code-causes-filter-skip-example.zip) you can see that the `ClientResponseCompleteRestHandler` is throwing an exception.

I think the exception could be thrown later, in `ClientResponseCompleteRestHandler` and not in `ClientSetResponseEntityRestHandler` if the status code is wrong.
Or maybe we could set the `checkSuccessfulFamily` to `false` for rest client? I'm not sure what's the best approach.

**Comment by michalszynkiewicz** [comment]
changing how rest client reactive handles `ResponseExceptionMapper` is also an option :)

**Comment by geoand** [comment]
I'll look at it more closely either later on today or tomorrow

**Comment by geoand** [comment]
In https://github.com/geoand/quarkus/tree/%2316702 I made the `ClientResponseFilter` part of the abort handling chain, however the JAX-RS TCK did not pass (there was a test that failed with a NPE because it expected the HTTP status to be set).

Moreover, even with this change in place, the reproducer does not engage the `MyResponseExceptionMapper`.
So it looks like some other strategy will be needed to handle `ResponseExceptionMapper`.

Finally, in this specific, it doesn't really make sense IMHO to have `ResponseExceptionMapper` as the there was no response from the server - processing fails with `java.net.UnknownHostException: restcountries.eu3: Name or service not known`

**Comment by michalszynkiewicz** [comment]
For unknown host, I agree, we should fail as we do now, I think.

I don't fully follow what happened in the jax-rs test, tried looking at it in the browser and it is **not** easy to follow :D

**Comment by geoand** [comment]
The spec isn't clear on whether or not `ClientResponseFilter` should be executed when there is an exception or not and the NPE in failing test isn't exactly indicative.

Does the old rest-client depend on this behavior?

**Comment by michalszynkiewicz** [comment]
Classic RestEasy used a `ClientResponseFilter` for exception mapping:
https://github.com/resteasy/Resteasy/blob/main/resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/ExceptionMapping.java

Does this answer your question?

**Comment by geoand** [comment]
OK, I guess then that I'll just disable the failing TCK test and open a PR. 
But like I said, it won't be enough to fix the original problem, as it seems like the new rest-client does not register `MyResponseExceptionMapper`

**Comment by michalszynkiewicz** [comment]
have you checked with the project I attached or the one the reporter provided? The latter was missing `@RegisterProvider(...)` on the client side IIRC

**Comment by geoand** [comment]
Yes, I enabled that and still the mapper never seems to be engaged

**Comment by geoand** [comment]
Here it is: https://github.com/quarkusio/quarkus/pull/16731

**Comment by michalszynkiewicz** [comment]
I'll see why the exception mapper is not triggered tomorrow.

**Comment by michalszynkiewicz** [comment]
Programmatically registered exception mapper works with your changes :)

I'll try to create a fix for mappers registered with `@RegisterProvider` today

**Comment by geoand** [comment]
Cool :)
