### ISSUE TITLE
Being able to pause/resume a specific scheduled method 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#16701]
## Description
The scheduler can be paused and resumed globally, it will be nice to programatically allow pausing/resuming a specific scheduled method. 
 
A workaround for now is for someone to not execute the main logic of the scheduled method based on the said condition.

**Comment by mkouba** [comment]
Hm, we should be able to reuse the `@Scheduled.identity()` to identify a specific method...

**Comment by mkouba** [comment]
BTW it would be also nice to implement pause/resume per job in the Dev UI ;-)

**Comment by machi1990** [comment]
> Hm, we should be able to reuse the `@Scheduled.identity()` to identify a specific method...

Yes, I was thinking the same. What about jobs that do not have `identity`? I was thinking of not giving making it possible to pause/resume them if no identity is given by the user. Or otherwise, use the combination of `ClassName#methodName` and retrieve the generated combination. 

Would also be good to make this work for the Quartz extension too.

**Comment by mkouba** [comment]
> Or otherwise, use the combination of `ClassName#methodName` and retrieve the generated combination.

`ClassName#methodName` is not necessarily unique. We should also keep in mind that `@Scheduled` is repeatable. In theory, we could expose the list of scheduled methods, i.e. something like `io.quarkus.scheduler.runtime.SchedulerContext.getScheduledMethods()` through the public API. But in general, an explicit identity should be used to pause/resume the job.

> Would also be good to make this work for the Quartz extension too.

+1 The impl should be straightforward - we use the identity for the `JobKey`, so we'll just delegate to `org.quartz.Scheduler.pauseJob(JobKey)`.

**Comment by machi1990** [comment]
> > Or otherwise, use the combination of `ClassName#methodName` and retrieve the generated combination.
> 
> `ClassName#methodName` is not necessarily unique. We should also keep in mind that `@Scheduled` is repeatable. In theory, we could expose the list of scheduled methods, i.e. something like `io.quarkus.scheduler.runtime.SchedulerContext.getScheduledMethods()` through the public API. But in general, an explicit identity should be used to pause/resume the job.
> 

Good point. I typed too fast, I mean to use the combination of classname and method to retrieve the generated unique ids. But I agree with you on using the explicit id for pausing and resuming. 

> > Would also be good to make this work for the Quartz extension too.
> 
> +1 The impl should be straightforward - we use the identity for the `JobKey`, so we'll just delegate to `org.quartz.Scheduler.pauseJob(JobKey)`.

+1. 

This is a very good first issue for contribution. I'll label it as such so that any community contributor can pick it up.

**Comment by aadityasinha-dotcom** [comment]
Hey! I want to work on this issue. 
Can you explain me about this.

**Comment by mkouba** [comment]
@aadityasinha-dotcom Sure thing ;-). Here's what needs to be done (in a nutshell):

1. Extend the `io.quarkus.scheduler.Scheduler` API, i.e. add `pause(String indentity)` and `resume(String identity)` methods
2. Implement these methods in the [SimpleScheduler](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java) and [QuartzScheduler](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java)
   * we will need to track the status in the [trigger](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java#L230), e.g. add a field
   * for quartz we should just delegate to `org.quartz.Scheduler`
3. Write tests
4. Add this functionality to the Dev UI (optional)

**Comment by aadityasinha-dotcom** [comment]
Thanks for your reply.
I will work on this :+1: .

**Comment by machi1990** [comment]
> @aadityasinha-dotcom Sure thing ;-). Here's what needs to be done (in a nutshell):
> 
> 1. Extend the `io.quarkus.scheduler.Scheduler` API, i.e. add `pause(String indentity)` and `resume(String identity)` methods
> 2. Implement these methods in the [SimpleScheduler](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java) and [QuartzScheduler](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java)
>    
>    * we will need to track the status in the [trigger](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java#L230), e.g. add a field
>    * for quartz we should just delegate to `org.quartz.Scheduler`
> 3. Write tests
> 4. Add this functionality to the Dev UI (optional)

Well summed up @mkouba 

> Thanks for your reply.
> I will work on this  .

Thank you so much @aadityasinha-dotcom feel free to ping us in case of any questions or opening a draft PR and we can iterate from there.

**Comment by mkouba** [comment]
> Thank you so much @aadityasinha-dotcom feel free to ping us in case of any questions or opening a draft PR and we can iterate from there.

Also feel free to join the community on the [zulip](https://quarkusio.zulipchat.com/) chat...

**Comment by adrianfiedler** [comment]
Hi @mkouba, @machi1990,
not sure if this is still in progress, but I played a little around with the schedulers. Do you mean something like here?
https://github.com/quarkusio/quarkus/pull/16855

**Comment by machi1990** [comment]
> Hi @mkouba, @machi1990,
> not sure if this is still in progress, but I played a little around with the schedulers. Do you mean something like here?
> #16855

Thanks for opening a draft PR but let's hear from @mkouba @aadityasinha-dotcom who will be able to give a better statutory update on the progress of this as @aadityasinha-dotcom has been looking at it.

**Comment by mkouba** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/16855. There is a follow-up issue to document this feature: https://github.com/quarkusio/quarkus/issues/16942/
