### ISSUE TITLE
Generated NamedOidcClient producers have different clients sharing the same Tokens State 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#16719]
## Describe the bug
I've come across it while looking at the reactive OidcClient filter tests where an extension provider and custom filter both extend `AbstractTokensProducer` - this is not a problem for filters because they all use the same underlying OidcClient instance, but for the named clients case where we can have
```
@Inject
@NamedOidcClient("client1")
OidcClient client1;
@NamedOidcClient("client2")
OidcClient client2;
```

with `client1` and `client2` pointing to for example different Keycloak realms it would cause 401s and some other confusion.
Named client is still the `main` branch feature only so we have time to fix it.

The problem is, `AbstractTokensProducer` depends on `TokensHelper.tokenRequestStateUpdater` which is static.

CC @fwippe

**Comment by sberyozkin** [comment]
I think we should just remove `AtomicReferenceFieldUpdater` and use the local `AtomicReference<TokenRequestsState>`

**Comment by sberyozkin** [comment]
I'll need to update the named client tests to reproduce the problem and will open it as a draft PR

**Comment by fwippe** [comment]
@sberyozkin I don't see any obvious problem regarding the static `TokensHelper.tokenRequestStateUpdater`: You are explicitly allowed to use the same `AtomicReferenceFieldUpdater` for several update targets. Thus, as far as I know, a new `TokensHelper` (or `AbstractTokensProducer`) should provide an independent `Tokens` via the individual `TokenRequestState`.

**Comment by sberyozkin** [comment]
@fwippe Sure, I got some unexpected log output when 2 different filters were running - only a single LOG notification that the tokens have been acquired - so seeing the `static` qualifiers got me wondering, but I'll investigate it further

**Comment by sberyozkin** [comment]
@fwippe it was a false alarm - it was just the way the test was set up - in fact 2 different filters extending `AbstractTokensProducer` do log independently (and their state is not shared) - I assumed the `static` updater might have its own state, etc. So for now I'll drop the idea of using `AtomicReference` instead, though may revisit it later again
thanks
