### ISSUE TITLE
resteasy-reactive doesn't trigger filters

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#16723]
## Describe the bug
The RestEasy Reactive client core handler fails when a request is not successful and doesn't trigger filters

### Expected behavior
 filters triggered

### Actual behavior
filters not triggered

## To Reproduce
see: 
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/reactive.20server.20.26.20client/near/235506862

## Environment (please complete the following information):
uname -a
Linux rhclient444.xxx 3.10.0-1160.6.1.el7.x86_64 #1 SMP Wed Oct 21 13:44:38 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
Quarkus version: 1.11.1.Final
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /home/xxx/opt/jdk-8u192_b12/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.6.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Thanks for reporting!

We opened an issue in the meantime (https://github.com/quarkusio/quarkus/issues/16702) so let's close this one as a duplicate
