### ISSUE TITLE
Agrogal triggers testcontainer to start without JDBC datasource settled up

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#16720]
## Describe the bug
Quarkus 1.13.2 Agrogal dependency runs testcontainer automatically without JDBC datasource settled up in application.properties file and without testcontainer resource defined.

### Expected behavior
A warning message is shown as in 1.11.6.Final version
WARN  [io.qua.agr.dep.AgroalProcessor] (build-42) The Agroal dependency is present but no JDBC datasources have been defined.

### Actual behavior
Docker postgres cointainer is started.
Happens when quarkus-jdbc-postgresql dependency is defined. May be the same with other jdbc drivers defined in pom.xml

## To Reproduce

1. Download sample project https://code.quarkus.io/?e=hibernate-orm-panache&e=resteasy-jackson&e=jdbc-postgresql&extension-search=pos
2. Run: mvn quarkus:dev

### Output of `java -version`
java 11.0.8

### Quarkus version or git rev
Quarkus 1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven 3.8.1

**Comment by kshpak** [comment]
Affected by https://github.com/quarkusio/quarkus/pull/14960
Feature, but looks like a bug
Unnecessary overhead of docker container is added

**Comment by geoand** [comment]
This is what [Dev Services](https://quarkus.io/guides/dev-services) is all about
