### ISSUE TITLE
Should the CamelRuntimeProducer be marked as unremovable?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1672]
A user reported having this in his logs:
```
2019-03-25 12:20:39,124 WARN  [io.qua.arc.run.ArcDeploymentTemplate] (main) Bean matching class io.quarkus.camel.core.runtime.CamelRuntimeProducer was marked as unused and removed during build.
Extensions can eliminate false positives using:
    - a custom UnremovableBeanBuildItem
    - AdditionalBeanBuildItem(false, beanClazz)
```

I think the `CamelRuntimeProducer` bean should probably be marked as unremovable.

**Comment by mkouba** [comment]
I believe it should. I'll try to adapt the camel code to use the new `RuntimeBeanBuildItem` API proposed by Stuart.

**Comment by mkouba** [comment]
Actually, once we switch to `RuntimeBeanBuildItem` the bean can be removable because the template does not attempt to lookup and initialize the `CamelRuntimeProducer` programatically. If we run into similar issues in the future we could simply add `RuntimeBeanBuildItem.setRemovable(false)`.
