### ISSUE TITLE
Quarkus Service binding - specific service documentation it is not easy to find

### ISSUE THREAD

**Issue by wtrocki** [quarkusio/quarkus#16737]
## Example service bindings for quarkus are not well documented (or I simply cannot find it).

I would expect to have single page that list all services that quarkus supports and what are the key for them.
Something like

```
/bindings/kafka
├── bootstrapServers
├── password
├── provider
├── saslMechanism
├── securityProtocol
├── type
└── user
```

or 

```
/bindings/postgre
├── host
├── password
├── provider
├── type
└── user
```

**Comment by wtrocki** [comment]
Once we have more services it wil be great to actually have registry even outside quarkus for other teams like Node.js to pickup etc.

**Comment by machi1990** [comment]
+1, I think this is a documentation and each extension that support service binding can enlist the expected binding keys.

**Comment by wtrocki** [comment]
I'm happy to contribute this upon agreement

**Comment by geoand** [comment]
We currently have https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/deploying-to-kubernetes.adoc#service-binding.

I'd be happy to have that enhanced further :)

**Comment by machi1990** [comment]
> We currently have https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/deploying-to-kubernetes.adoc#service-binding.
> 
> I'd be happy to have that enhanced further :)

@geoand Suppose we add the bindings details in there for each extension, won't that be too big of information to maintain and for users to find their way on the docs over time?

**Comment by wtrocki** [comment]
There are different use cases.
Binding is being used internally in quarkus - values provided are consumed in plugins.

But even for simple summit demos we had situations where apart from quarkus plugin we needed to get raw config for other non quarkus lib. Additionally this is working with one specific Kafka. I'm trying to facilitate other Kafkas - like strimzi to conform to this standard - having clear documentation on standard supported by quarkus is essential ( and that is not only for kafka)

**Comment by geoand** [comment]
> > We currently have https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/deploying-to-kubernetes.adoc#service-binding.
> > I'd be happy to have that enhanced further :)
> 
> @geoand Suppose we add the bindings details in there for each extension, won't that be too big of information to maintain and for users to find their way on the docs over time?

I'd love us to come to a point where having too much documentation is a problem 😎

**Comment by machi1990** [comment]
> > > We currently have https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/deploying-to-kubernetes.adoc#service-binding.
> > > I'd be happy to have that enhanced further :)
> > 
> > 
> > @geoand Suppose we add the bindings details in there for each extension, won't that be too big of information to maintain and for users to find their way on the docs over time?
> 
> I'd love us to come to a point where having too much documentation is a problem

Me too. I was only thinking of a dividing and spreading the same contents in a different way. But let's get the content first and see how it goes.

**Comment by wtrocki** [comment]
I had different idea. Since those configs need to be across different frameworks we might actually setup separate page for it - config registry and quarkus can reference it in the documentation.

This way we going to kill two birds with one stone - provide clear info for Quarkus (but also other languages and frameworks also populating quarkus as reference implementation for java that does follow those configs)

**Comment by geoand** [comment]
That sounds very reasonable

**Comment by bmozaffa** [comment]
+1, I searched and could not find anything, and part of the reason I couldn't find the page referenced here is because I was trying to find the docs based an example with properties such as db.host, etc

**Comment by wtrocki** [comment]
CC @slemeur

**Comment by mhdawson** [comment]
@wtrocki, It would be great to have a place that documents what each of the service bindings is, independent of runtime.  We could then reference that from the documentation for each of the different tools/utilities that leverage it. For example on the readme of https://github.com/nodeshift/kube-service-bindings

**Comment by geoand** [comment]
Thanks @wtrocki

**Comment by geoand** [comment]
Is there anything we need to do about his one now?

**Comment by wtrocki** [comment]
@geoand we decided to put all info on sbo website.
We have content but still some work is happening on sbo site to publish website. CC @pedjak

My take is that we can duplicate this info and add to quarkus doc for the moment or wait till sbo website is live

**Comment by geoand** [comment]
Thanks for the update!

**Comment by geoand** [comment]
Closing this as there hasn't been any relevant activity or request
