### ISSUE TITLE
Add quarkus-logging-kafka extension

### ISSUE THREAD

**Issue by bennetelli** [quarkusio/quarkus#16733]
## Describe the extension

At Red Hat Insights we have got the situation that we want to log our application log to a Apache Kafka topic instead of the standard application log.
In our opinion the extension could also be useful for others who need more flexibility than with the existing extensions like quarkus-logging-gelf which directly sends logs to a centralized log management system like logstash and graylog for example.

By using this this extension users would get the flexibility to log to every system they want to.

**Note:**
Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
```properties
# Add your application.properties here, if applicable.
quarkus.log.kafka=true
quarkus.log.kafka.level=INFO
quarkus.log.kafka.broker-url=localhost:9092
quarkus.log.kafka.topic-name=kafka-logging-topic
```

When the amount of users and use cases increases there will be more than just these four properties probably.
But for now it works with just these four entries. (It would also work with less because of default values of course.)

## Additional context
(Add any other context about the proposal here.)

Let me know what you think about it :-)

**Comment by bennetelli** [comment]
here is a working example: https://github.com/bennetelli/quarkus-logging-kafka

**Comment by cescoffier** [comment]
I need to think a bit more about that one.
Typically what's your record key, how to enforce ordering (well, yes with a key), how to be sure we don't mess up the ordering (Retry + number of inflight...).

In your code, you use `write` which is async, you have no guarantee it will be processed before others, that depends on retry and the inflight. Also, if it fails, you probably won't catch the error too.

That being said, if we want to move forward, it should be in the quarkiverse.

**Comment by cescoffier** [comment]
@bennetelli should we move forward and create an extension in the quarkiverse? (please also note my comment about `write`).

**Comment by bennetelli** [comment]
@cescoffier at Insights we decided to log our application logs to CloudWatch, so we don't need this extension anymore. 
I can polish this extension and add it to quarkiverse if you still think this extension could be useful for others.

**Comment by gastaldi** [comment]
Let's close it for now and reopen once there is a demand for it 👍🏻
