### ISSUE TITLE
Avro code generation issue in Quarkus 2.0.0-Alpha1 

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#16747]
## Describe the bug
Just tried 2.0.0.Alpha1 in a sample Kafka project facing compilation error 

### Expected behavior
Avro code generation should work

### Actual behavior
Duplicate class error

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

Run 1.13.2 Kafka Avro example and migrate to 2.0.0.Alpha1 to reproduce the error

### Configuration
```xml
    <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <version>1.10.2</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>src/main/avro</sourceDirectory>
                            <outputDirectory>${project.build.directory}/generated-sources</outputDirectory>
                            <stringType>String</stringType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Linux x64
### Output of `java -version`
Java 11
### Quarkus version or git rev
2.0.0.Alpha1
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvnw
## Additional context
(Add any other context about the problem here.)

**Comment by glefloch** [comment]
@missourian55 thanks for reporting this. @michalszynkiewicz shouldn't we remove the avro plugin in the quickstart ?

**Comment by michalszynkiewicz** [comment]
@glefloch where do we have the avro plugin in quickstarts?

**Comment by glefloch** [comment]
oh I taught @missourian55 was using a quickstart but it's not the case. @missourian55 could you attach a reproducer?

**Comment by michalszynkiewicz** [comment]
@missourian55 with 2.0 it's no longer necessary to use the plugin. Can you retry with it removed from your pom.xml?

**Comment by missourian55** [comment]
@michalszynkiewicz 

Thanks, once I removed the Avro codegen plugin, the compilation was successful. So fa,r two things worthy enough to a callout in 2.0.0 migration guide

1. No need to configure `Avro code-gen` plugin if you declare `quarkus-avro` dependency
2.  Kubernetes plugin now start mapping port *80* to *8080*, previously it was 8080 to 8080

We use Quarkus with istio sidecars so we have to modify the istio configurations. 

Once again thanks to the Quarkus team for 2.0.0 Alpha Release.

**Comment by cescoffier** [comment]
@michalszynkiewicz can you add these into the migration guide? 

I'm surprised by the second item (not related to Avro), @geoand was this done on purpose?

**Comment by geoand** [comment]
@cescoffier yes, it was done on purpose (cc @iocanel who made this change when we bumped to Dekorate 2.x)

**Comment by geoand** [comment]
Just edit https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0 :)

**Comment by michalszynkiewicz** [comment]
done

**Comment by cescoffier** [comment]
Closing - changes have been documented.
