### ISSUE TITLE
404 error from resources declared in javax.ws.rs.core.Application#getClasses

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#16754]
I'm trying to upgrade to **1.13.2.Final** and use the ability to limit the JAX-RS resources introduced by [this](https://github.com/quarkusio/quarkus/pull/14207) feature, but the declared resources in the overriden ``javax.ws.rs.core.Application#getClasses`` method return 404 error. If i do not override ``getClasses`` (or return an empty set, which as far as i understand is equivalent), the endpoints work as expected.

#### To Reproduce
You can use [this](https://github.com/blxbrgld/jaxrs-application) sample. ``/api/test`` is the endpoint that returns the 404 error.

**Comment by essobedo** [comment]
Hi, inheritance is not yet supported by this feature, it was a very basic first step but it should not be hard to add it. I will check it asap, meanwhile you could get rid of the interface to make it work.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/quarkusio/quarkus/pull/16793

**Comment by essobedo** [comment]
The corresponding PR for 1.13 https://github.com/quarkusio/quarkus/pull/16823
