### ISSUE TITLE
Openshift/K8s resources files not created without quarkus-resteasy dependency

### ISSUE THREAD

**Issue by avano** [quarkusio/quarkus#16760]
## Describe the bug
I have `quarkus-openshift` extension in my pom file, but the resources in `target/kubernetes` are not generated without `quarkus-resteasy` dependency

### Expected behavior
Resources generated even without `quarkus-resteasy` dependency

### Actual behavior
No resources are generated after removing `quarkus-resteasy` dependency

## To Reproduce

https://github.com/avano/quarkus-openshift-reproducer

1. `mvn clean package`
2. check `target` folder:
```
ls target/kubernetes 
Permissions  Size User  Group Date Modified    Name
.rw-r--r--@ 2.8Ki avano avano 2021-04-23 15:05 kubernetes.json
.rw-r--r--@ 2.1Ki avano avano 2021-04-23 15:05 kubernetes.yml
.rw-r--r--@ 5.3Ki avano avano 2021-04-23 15:05 openshift.json
.rw-r--r--@ 4.2Ki avano avano 2021-04-23 15:05 openshift.yml
```

1. comment out `quarkus-resteasy` dependency
2. `mvn clean package`
3. check `target` folder:
```
ls target/kubernetes
"target/kubernetes": No such file or directory
```

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Logs
with `quarkus-resteasy` dependency, the log ends with:

```
[INFO] --- quarkus-maven-plugin:1.13.2.Final:build (default) @ getting-started ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Selecting target 'openshift' since it has the highest priority among the implicitly enabled deployment targets
[INFO] Checking for existing resources in: /tmp/getting-started/src/main/kubernetes.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1388ms
```

without the `quarkus-resteasy` dependency:

```
[INFO] --- quarkus-maven-plugin:1.13.2.Final:build (default) @ getting-started ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Selecting target 'openshift' since it has the highest priority among the implicitly enabled deployment targets
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 900ms
```

### Output of `uname -a` or `ver`
```
Linux 5.11.9-200.fc33.x86_64 #1 SMP Wed Mar 24 12:09:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```
### Quarkus version or git rev
`1.13.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
`Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
This is expected behavior.

For Quarkus to generate the manifests, the application needs to be an HTTP application.

That might change in the future, but for now it's expected
