### ISSUE TITLE
kafka-client : Detected a MBean server in the image heap

### ISSUE THREAD

**Issue by glandais-sparklane** [quarkusio/quarkus#16765]
## Describe the bug
In some cases, org.apache.kafka.common.metrics.JmxReporter.reconfigure is called, implying the usage of MBean server.
Native executable can not be build.

### Expected behavior
All methods accessing to MBeanServer shall be substituted.

### Actual behavior
reconfigure method is causing this kind of error during native build :

`Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@fde425e reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@1a67ab17 reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:227)
	at org.apache.kafka.common.metrics.JmxReporter.lambda$reconfigure$1(JmxReporter.java:113)
	at org.apache.kafka.common.metrics.JmxReporter$$Lambda$1649/0x00000007c2ad1840.accept(Unknown Source)
`

## To Reproduce

Stacktrace is incomplete and not easily reproductible.

### Output of `uname -a` or `ver`

Linux XXX 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)

Using quarkus.native.container-build

### Quarkus version or git rev

1.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/gla/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /home/gla/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-50-generic", arch: "amd64", family: "unix"

**Comment by cescoffier** [comment]
Which version of kafka client were you using?

**Comment by glandais-sparklane** [comment]
@cescoffier I guessed you've seen it but the kafka client version is coming from the bom (kafka2.version=2.7.0) with 1.13.2.Final
