### ISSUE TITLE
RestEasy custom error response bodies missing

### ISSUE THREAD

**Issue by YunaBraska** [quarkusio/quarkus#16779]
## Describe the bug
After build the native build, the custom error handler (`implements ExceptionMapper`) does not return response bodies.
I get a bit frustrated with quarkus these days. There are many features not working and I feel like i am building workarounds only these days... 
I can't provide a project link here its a private one.

### Expected behaviour
Rest exception handling should return the full declared response with body not just only the error code

### Actual behavior
Rest exception handling returns only the error code

## To Reproduce
*  https://github.com/YunaBraska/quarkus_16779

**Comment by geoand** [comment]
Can you please attach a sample project that reproduces this problem?

Otherwise it's very hard for us to be able to identify the exact issue and provide you the necessary help

**Comment by YunaBraska** [comment]
@geoand I created a small project now https://github.com/YunaBraska/quarkus_16779 and I was lucky to also point more error details as this clean project returns an error like `No serializer found for class ApiError and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)`
So somehow the serialisation does not work on native. I could imagine that the ObjectMapper uses reflection while running on JVM but missing some description how to serialise on native mode. I would expect these serialisation descriptions to have automatically while the native build or else to not have even the object mapper available if this is an issue.

**Comment by geoand** [comment]
In your project all you need to do is add `@RegisterForReflection` on the `ApiError` class and the problem goes away.

More details can be found at https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

**Comment by YunaBraska** [comment]
@geoand is there any other cleaner way to do this? This annotation sounds for me like an `@Dirty`-Solution...

**Comment by geoand** [comment]
There is no way for Quarkus to know that you are using the `ApiError` as a DTO

**Comment by YunaBraska** [comment]
What does `@RegisterForReflection`? It sounds like it does more than needed.
I have found a different solution by creating a dummy endpoint which returns my error DTO as a response.
As far as I understand, the usual endpoint DTOs are creating meta files for the serialisation which is probably better than the usage of `@RegisterForReflection`. So what I am missing is basically something like `DtoRegistry.register(MyErrorResponse.class)`

**Comment by geoand** [comment]
The doc I linked to above should explain, no?

**Comment by YunaBraska** [comment]
Oh sorry I missed that link, thx

**Comment by geoand** [comment]
👍🏼
