### ISSUE TITLE
QuarkusTest  multiPart fileupload works fine with eclipse but not working mvnw test JVM crashed

### ISSUE THREAD

**Issue by selvarajchennappan** [quarkusio/quarkus#16778]
Quarkus test  multiPart fileupload runs fine with eclipse IDE but not working mvnw test JVM crashed

### Expected behavior
mvnw test should work fine 

### Actual behavior
floods of log "org.apa.htt.wire  and VM crashed.
[quarkustest-fileuplod-mvnw.txt](https://github.com/quarkusio/quarkus/files/6368890/quarkustest-fileuplod-mvnw.txt)

1.Create Rest endpoint with Multipart file
2.Implement quarkus test and pass any file .
3. Run it on eclipse it works fine
4. same test run it using mvnw test .

### Configuration
```properties
# Add your application.properties here, if applicable.

Java 8 
Quarkus 1.38.0
Maven 3.6.3

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):

### Output of `uname -a` or `ver`

### Output of `java -version`

### GraalVM version (if different from Java)

### Quarkus version or git rev

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
What version of Quarkus are you using? `1.38.0` is not a valid version.

Furthermore, can you add a reproducer project that we can test?

**Comment by selvarajchennappan** [comment]
sorry my mistake 
<quarkus.platform.version>1.13.0.Final</quarkus.platform.version>
Test steps are quite simple . dont have reproducer project.

**Comment by selvarajchennappan** [comment]
Test code snippet . It works fine with Eclipse IDE run it as junit. However when we build using mvn it fails and log is attached in the first message .

@QuarkusTest
public class DocumentRepositoryResourceTest {

	public String inputFile = "src/test/resources/test/test.pdf";

	 @Test
	public void testCheckin() {

		String absPath = "/advitium/pdf/" + System.currentTimeMillis() + ".pdf";
		Document details = new Document();
		details.setAbsolutePath(absPath);
		details.setComments("First Commit");
		details.setDescription("Test file");
		details.setMimeType("application/pdf");

		JsonObject userJson = new JsonObject();
		userJson.put("userId", "613498638");

		String json = Json.encode(details);
		Response response = given().multiPart("fileDetails", json).multiPart("fileUpload", new File(inputFile))
				.header("principal", userJson.toString()).post("/doc-mgmt/api/v1/checkin").andReturn();

		System.out.println("checkin status code : " + response.getStatusCode());

		assertEquals(200, response.getStatusCode());
	}
	}

**Comment by geoand** [comment]
Closing this as we have various of [tests](https://github.com/quarkusio/quarkus/blob/2.3.0.Final/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/deployment/src/test/java/io/quarkus/resteasy/reactive/jackson/deployment/test/MultipartTest.java) that do something similar and work just fine in our CI
