### ISSUE TITLE
Changed runtime value of quarkus.datasource.db-kind is silently ignored

### ISSUE THREAD

**Issue by renegrob** [quarkusio/quarkus#16786]
## Describe the bug
Usually when you change a build-time property at runtime, you get a warning like this:
```shell
2021-04-10 21:35:45,946 WARN  [io.qua.run.con.ConfigChangeRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.health.enabled was 'true' at build time and is now 'false'
```

However if I change db-kind:
```shell
java -jar -Dquarkus.datasource.db-kind=other target/quarkus-app/quarkus-run.jar
```
Its value is silently ignored.
From my point of view, it should behave like other build-time properties and produce a warning.

_Originally posted by @aloubyansky in https://github.com/quarkusio/quarkus/pull/16606#r615658657_

### Expected behavior
If the build time property `quarkus.datasource.db-kind` has a different value at runtime then either a warning should be logged or if the property `quarkus.configuration.build-time-mismatch-at-runtime=fail` is set, Quarkus should fail during startup.

### Actual behavior
The value is silently ignored which can be confusing.

## To Reproduce

This can be reproduced with any Quarkus 1.13.x project that has db-kind configured. Just set a different runtime configuration value for `db-kind` than the one used during augmentation.

See above.

**Comment by yrodiere** [comment]
> If the build time property `quarkus.datasource.db-kind` has a different value at runtime then either a warning should be logged or if the property `quarkus.configuration.build-time-mismatch-at-runtime=fail` is set, Quarkus should fail during startup.

@radcortez I believe we do have a warning log for this nowadays, right? If so we can close this issue.

**Comment by renegrob** [comment]
@yrodiere By then it was a special case that did neither trigger the warning nor fail. I doubt that this has magically changed. It should be possible to create a unit-test for this.

**Comment by radcortez** [comment]
Yes, this works as expected (tested with the latest version):

```console
🌀 java -Dquarkus.datasource.db-kind=x -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-08-20 17:55:58 WARN  [io.qua.run.con.ConfigRecorder]] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.db-kind is set to 'x' but it is build time fixed to 'postgresql'. Did you change the property quarkus.datasource.db-kind after building the application?
```

This was reported in Quarkus 1.13.x... the configuration changed drastically since that version :) Configuration handling is way more consistent now.
