### ISSUE TITLE
Context is not propagated within IdentityProvider (AuthenticationRequestContext's runBlocking method)

### ISSUE THREAD

**Issue by bboyz269** [quarkusio/quarkus#16789]
## Describe the bug
I'm implementing a custom IdentityProvider, require access to the request.  I tried to inject `io.vertx.ext.web.RoutingContext` but got the `javax.enterprise.context.ContextNotActiveException`.

What I tried:
* Adding `@ActivateRequestContext`, the exception turns to `javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()`

### Expected behavior
When smallrye-context-propagation activated, all contexts, include request context should be accessible in AuthenticationRequestContext's runBlocking thread.

### Actual behavior
Got `javax.enterprise.context.ContextNotActiveException` for using `io.vertx.ext.web.RoutingContext#request()`

## To Reproduce
Custom IdentityProvider with RoutingContext injected
```kotlin
@ApplicationScoped
class CustomIdentityProvider(
    private val routingContext: RoutingContext
) :
    IdentityProvider<TokenAuthenticationRequest> {
    override fun getRequestType() = TokenAuthenticationRequest::class.java

    override fun authenticate(
        request: TokenAuthenticationRequest,
        context: AuthenticationRequestContext
    ): Uni<SecurityIdentity> = context.runBlocking {
        routingContext.request().remoteAddress() // >> ContextNotActiveException
        null
    }
}
```

**Comment by sberyozkin** [comment]
@renegrob Hi Rene - is it what your quarkus-security enhancement was about (passing the relevant info via the custom attributes etc) ?

**Comment by sberyozkin** [comment]
@bboyz269 `IdentityProvider`s are run as part of the process for creating an injectable `SecurityIdentity` hence you see this error - so the context propagation is not quite relevant.

**Comment by renegrob** [comment]
> @renegrob Hi Rene - is it what your quarkus-security enhancement was about (passing the relevant info via the custom attributes etc) ?

@sberyozkin Yes. Currently it is possible but you have to replace/extend the `HttpAuthenticationMechanism`in order to put additional context in the `AuthenticationRequestContext`.
I don't know if it is possible to let `QuarkusIdentityProviderManagerImpl` augement the `AuthenticationRequestContext` similar to the augmenters already present for `SecurityIdentity`. Are we still on the Vertx thread when `QuarkusIdentityProviderManagerImpl.authenticate()`is called. Else we have to do a breaking change to make it work.

**Comment by sberyozkin** [comment]
I think so, which is why a `runBlocking` alternative is provided. But augmenting `AuthenticationRequestContext` on the Vert.x thread should work as it would me simply about associating some request properties with it.

**Comment by bboyz269** [comment]
Is my understanding correct that it's currently impossible to have quarkus security with multi tenant hibernate JPA?
Since RoutingContext is not available  within `runBlocking` thread, `TenantResolver` just fails.
Or is there other bean that contains request information I can use here?

My current setup
```kotlin
@ApplicationScoped
class MyTenantResolver(
    private val rc: RoutingContext // < inaccessible during `runBlocking`
) : TenantResolver {
    /* omit things */
    override fun resolveTenantId() = routingContext.request().getHeader("X-Forwarded-Host") ?: routingContext.request().host()
}

@ApplicationScoped
class MyIdentityProvider(
    private userService: UserService // uses tenant-wise panache hibernate repository

) : IdentityProvider<TokenAuthenticationRequest> {
    /* omit things */
    override fun authenticate(
        request: TokenAuthenticationRequest,
        context: AuthenticationRequestContext
    ): Uni<SecurityIdentity> = context.runBlocking(
        userService.getIdentity(request.token) // resolve identity by calling tenant-wised UserRepository
    )
}
```

**Comment by renegrob** [comment]
@bboyz269 Well, you can access the `RoutingContext` in the corresponding token `HttpAuthenticationMechanism` and then set the header's value as attribute on the `TokenAuthenticationRequest`. 
And if Sergey is right, then you could also use `RoutingContext` before you call `context.runBlocking` in your `IdentityProvider`'s `authenticate`method. That way you don't need to have to extend the correspondig token `HttpAuthenticationMechanism`.
@stuartwdouglas Are we still on the Vertx thread when `QuarkusIdentityProviderManagerImpl.authenticate()`is called? Or more specific: Is it safe to call `Vertx.currentContext` on the `IdentityProvider` as long as we didn't call `context.runBlocking(..)`yet?

**Comment by stuartwdouglas** [comment]
Maybe we should always provide the RoutingContext as an attribute via `io.quarkus.security.identity.request.AuthenticationRequest#setAttribute`

**Comment by bboyz269** [comment]
Sorry I didn't phrase my issue properly.

I could collect request information (RoutingContext) by implement a new `AuthenticationRequest` or just collect them before passing to `runBlocking` as final variables.  
What I couldn't do is access to RoutingContext in `TenantResolver` (hibernate orm multitenant). Please check my previous post for the code.

This should be a problem with quarkus-hibernate-orm multitenancy instead of quarkus-security?

**Comment by renegrob** [comment]
Your `TenantResolver` should be `@RequestScoped`. See: https://quarkus.io/guides/hibernate-orm

**Comment by mkouba** [comment]
> Maybe you can help with this?

@renegrob I'm afraid not. This is more a question for security and context propagation experts... CC @manovotn @FroMage

> Maybe we should always provide the RoutingContext as an attribute via `io.quarkus.security.identity.request.AuthenticationRequest#setAttribute`

@stuartwdouglas I think that this is a good idea.

**Comment by bboyz269** [comment]
> I think your `TenantResolver` should be `@RequestScoped` (see: https://quarkus.io/guides/hibernate-orm).
> However I'm not sure if that's gonna fix the issue. 

@renegrob It's `@RequestedScoped` in my actual code and you're right that I got the same issue.


Also, I tried to implement custom `IdentityProviderManager` to set the `blockingExecutor` but couldn't figure which executor to use.
(already tried "@Inject ManagedExecutor" from context propagation guide).

*io.quarkus.security.runtime.IdentityProviderManager*
```java
    @Produces
    @ApplicationScoped
    public IdentityProviderManager ipm() {
        boolean customAnon = false;
        QuarkusIdentityProviderManagerImpl.Builder builder = QuarkusIdentityProviderManagerImpl.builder();
        for (IdentityProvider i : identityProviders) {
            builder.addProvider(i);
            if (i.getRequestType() == AnonymousAuthenticationRequest.class) {
                customAnon = true;
            }
        }
        if (!customAnon) {
            builder.addProvider(new AnonymousIdentityProvider());
        }
        for (SecurityIdentityAugmentor i : augmentors) {
            builder.addSecurityIdentityAugmentor(i);
        }
        builder.setBlockingExecutor(new Executor() {
            @Override
            public void execute(Runnable command) {
                //TODO: should we be using vert.x blocking tasks here? We really should only have a single thread pool
                ExecutorRecorder.getCurrent().execute(command);
            }
        });
        return builder.build();
    }
```

**Comment by FroMage** [comment]
Yeah, I'm not actually an expert in this part of the security, or even in multi-tenant stuff, so I can't really say, but what @stuartwdouglas suggested:

> Maybe we should always provide the RoutingContext as an attribute via io.quarkus.security.identity.request.AuthenticationRequest#setAttribute

makes a lot of sense IMO.

**Comment by sberyozkin** [comment]
@bboyz269 Are you saying that `RoutingContext` injections works if `TenantResolver` is called an the IO/Vert.x thread ?

**Comment by renegrob** [comment]
@bboyz269 Replacing `IdentityProviderManager` should not be necessary. Your first approach looks good, except that the injection does not work.
The problem you described in the "Reproduce" section of the issue can easily be solved if you read the request attribute before you call `context.runBlocking {...`. However the `@RequestScoped TenantResolver` sounds more like a CDI context propagation problem to me, since you can't access a `@RequestScoped` bean from the worker thread.  What does `Arc.container().requestContext().isActive()` return in the blocking method? - Probably `false`... 
I suggest that you create a reproducer project so that it can be debugged.

**Comment by renegrob** [comment]
@sberyozkin Cloud `AuthenticationRequestContext.runBlocking` propate / restore the request context? I think ResteasyReactive also needs to do it for `@Blocking` but I've no idea about the details. I did something with Weld years ago to start the Context within a different thread.

**Comment by sberyozkin** [comment]
I wonder if it is the same problem though, i.e does it really matter if it is a blocking call or not, the problem is - it is the process for creating an injectable `Securityidentity` so the context injection into the code involved into this process can not be achieved. So in this specific case we'll get `RoutingContext` available to `IdentityProvider`s which then should propagate is somehow to the downstream components

**Comment by renegrob** [comment]
I played a bit around: https://github.com/renegrob/reproducer-base/tree/inject-request-blocking
It works but it's not the way it should be. @sberyozkin  Can you have a look?

**Comment by renegrob** [comment]
Since Arc does not have an active request context, the injection of @RequestScoped does not work. My workaround was to start it manually in the runBlocking method. But I don't think it should be that way. @mkouba?

**Comment by sberyozkin** [comment]
@renegrob thanks; yeah - CC to Martin :-).

**Comment by renegrob** [comment]
I saw that other extensions e.g. GraphQL have some setup to support the injection (see `io.quarkus.smallrye.graphql.deployment.InjectRoutingContextTest` and `ElytronSecurityJdbcProcessor` on line 41).

**Comment by renegrob** [comment]
@sberyozkin @mkouba  I think I figured out what the missing piece was: 

In order to be able to inject the `RoutingContext` besides of having an active request context the current `RoutingContext` must be set on `CurrentVertxRequest`:
```java
        Arc.container().requestContext().activate(null);
        try {
            currentVertxRequest.setCurrent(authenticationRequest.getAttribute(RoutingContext.class.getName()));
            return identityProviderManager.authenticate(authenticationRequest);
        }finally {
            Arc.container().requestContext().deactivate();
        }
```
If this would be either in `HttpAuthenticator`or in `io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder.authenticationMechanismHandler()` injection of the `RoutingContext` and of any `@RequestContext` beans would work. IMO it would make sense to start the context very early, else it might get started multiple times within a request lifecycle.

The 2nd fix then would be to propagate the request context in the `runBlocking()` method:
```java
public class QuarkusIdentityProviderManagerImpl implements IdentityProviderManager {
    private static final Logger log = Logger.getLogger(QuarkusIdentityProviderManagerImpl.class);

    private final Map<Class<? extends AuthenticationRequest>, List<IdentityProvider>> providers;
    private final List<SecurityIdentityAugmentor> identityAugmenters;
    private final List<AuthenticationRequestAugmentor> requestAugmenters;
    private final Executor blockingExecutor;

    private final AuthenticationRequestContext blockingRequestContext = new AuthenticationRequestContext() {
        @Override
        public Uni<SecurityIdentity> runBlocking(Supplier<SecurityIdentity> function) {
            return Uni.createFrom().deferred(new Supplier<Uni<? extends SecurityIdentity>>() {
                @Override
                public Uni<SecurityIdentity> get() {
                    if (BlockingOperationControl.isBlockingAllowed()) {
                        try {
                            SecurityIdentity result = function.get();
                            return Uni.createFrom().item(result);
                        } catch (Throwable t) {
                            return Uni.createFrom().failure(t);
                        }
                    } else {
                        final InjectableContext.ContextState state = Arc.container().requestContext().getState();

                        return Uni.createFrom().emitter(new Consumer<UniEmitter<? super SecurityIdentity>>() {
                            @Override
                            public void accept(UniEmitter<? super SecurityIdentity> uniEmitter) {

                                blockingExecutor.execute(new Runnable() {
                                    @Override
                                    public void run() {
                                        Arc.container().requestContext().activate(state);
                                        try {
                                            uniEmitter.complete(function.get());
                                        } catch (Throwable t) {
                                            uniEmitter.fail(t);
                                        } finally {
                                            Arc.container().requestContext().deactivate();
                                        }
                                    }
                                });
                            }
                        });
                    }
                }
            });

        }
    };
```
I'm not sure if it is necessary to check whether there is already an active request context.

However, I'm wondering if there was a particular reason why it hasn't been done before and where's the best place to start the request context (first code snippet).

**Comment by stuartwdouglas** [comment]
It's not done this way because setting up the request context is relatively expensive, and 99.99% of the time it is not required.

We should fix this by providing the RoutingContext as an attribute via io.quarkus.security.identity.request.AuthenticationRequest#setAttribute

**Comment by bboyz269** [comment]
> We should fix this by providing the RoutingContext as an attribute via io.quarkus.security.identity.request.AuthenticationRequest#setAttribute

@stuartwdouglas
Then would injecting RoutingContext into `TenantResolver` works automatically or I still have to manually activate the request context manually before `runBlocking` as @renegrob suggested?

Mockup:
```kotlin
@ApplicationScoped
class MyIdentityProvider(
    private userService: UserService // service uses tenant-wise panache hibernate repository
) : IdentityProvider<TokenAuthenticationRequest> {
    override fun getRequestType() = TokenAuthenticationRequest::class.java
    override fun authenticate(
        request: TokenAuthenticationRequest,
        context: AuthenticationRequestContext
    ): Uni<SecurityIdentity> = context.runBlocking {
        // resolve identity by calling tenant-wised UserService
        userService.getIdentity(request.token)
    }.onSubscribe {
        Arc.container().requestContext().activate(request.requestContextState)
    }.eventually {
        Arc.container().requestContext().deactivate()
    }
}

/*@RequestScoped
class MyTenantResolver(
    private val rc: RoutingContext // inaccessible during `runBlocking`
) : TenantResolver {
    /* omit things */
    override fun resolveTenantId() = routingContext.request().getHeader("X-Forwarded-Host") ?: routingContext.request().host()
}*/
```

**Comment by stuartwdouglas** [comment]
No, then you would be able to call request.getAttribute() to get the routing context directly.

**Comment by renegrob** [comment]
> It's not done this way because setting up the request context is relatively expensive, and 99.99% of the time it is not required.
Ok, I get it.
@bboyz269 AFAIK the same `TenantResolver` needs to work within the `IdentityProvider` and within the REST endpoints. In the `IdentityProvider` you can't inject `@RequestScoped` beans without the workaround and in the REST endpoint you can't access the `AuthenticationRequest` attributes.
That said I see two possibilities:
 * Make the `TenantResolver` `@ApplicationScoped`, check if Arc's request context is started, if yes use `CDI.current().select(...)` to access the `RoutingContext` else use a `ThreadLocal` that you set from the `IdentityProvider`.
 * Start the Arc's request context within the `runBlocking` and you will be able to use the `@RequestScoped TenantResolver` with the injected `RoutingContext`.
Neither solution is perfect.

**Comment by bboyz269** [comment]
Thank you @stuartwdouglas  @renegrob , I managed to put up some hacky code that satisfy with my situation now.  
I went with propagating the request context within `runBlocking` for a seamless injection of `@RequestScoped` beans.
(still waiting for the official patch of providing `AuthenticationRequest` for cleaner code).

One more point about pvoriding `RoutingContext`, instead of `AuthenticationRequest`, what do you think of put it inside `AuthenticationRequestContext`?  
The former is passed in `IdentityProvidier` while the latter is passed in both `IdentityProvider` and `SecurityIdentityAugmentor`. Both of them have somewhat similar use cases.  
Ex: I want to use `quarkus-smallrye-jwt`'s provider and further augment the identity with user's information via multitenant-jpa repositories.

**Comment by renegrob** [comment]
`AuthenticationRequestContext` is `@ApplicationScoped` and therefore not suited to transport request specific context attributes. (I'm not absolutely sure, if I got your question right)

**Comment by bboyz269** [comment]
> (I'm not absolutely sure, if I got your question right)

@renegrob That indeed was my question as I was not awared of the scope of `AuthenticationRequestContext`.  
So we have to deal with everything that requires `RoutingContext` in `IdentityProvider` for now, I guess.

**Comment by sberyozkin** [comment]
I've opened PR to have it passed as an attribute - not a perfect solution for all the cases :-) but hopefully will make it easier to access it when needed
