### ISSUE TITLE
Non-essential bean

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#16784]
## Description

Bean injection is not necessary, if the bean is empty, Inject will report an error.

## Implementation ideas

Spring can use @Resource annotation, but Quarkus does not seem to recognize @Resource

**Comment by geoand** [comment]
Can you add an example of what you are looking for?

**Comment by stuartwdouglas** [comment]
You need to use @Inject Instance<Bean> rather than @Inject Bean for this case, then use `javax.enterprise.inject.Instance#isResolvable` to check if the bean is there.
