### ISSUE TITLE
Restructure Vert.x extensions

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#16797]
## Description

At the moment, we have 4 Vert.x related extensions. This is mostly because of decisions taken at the very beginning of the project, before Vert.x becomes the underlying engine (even the name of the extension is somewhat broken now).
So currently we have:

* vertx-core -> configure vert.x, produce the "bare" Vert.x instance
* vertx-http -> initialize Vert.x Web router(s) and the Vert.x HTTP server
* vertx -> produce the Mutiny Vert.x instance, add support for the `@ConsumeEvent` annotation (event bus, built-in in vert.x)
* vertx-web -> handle reactive routes (`@Route`) and provide the `@RouteFilter` annotation

With the introduction of RESTEasy Reactive, Reactive Routes use case become less relevant. 
Also, Mutiny, becoming the omniscient reactive programming library, should be supported by default (Stuart already started doing some work around that)

To ease the maintenance, and also reduce a bit the confusion, here is a structuration proposal:

* vertx-core -> configure vert.x, producer "bare" and "mutiny" instances, add support for `@ConsumeEvent`
* vertx-http ->  initialize Vert.x Web router(s) and the Vert.x HTTP server, handle reactive routes (`@Route`) and provide the `@RouteFilter` annotation

The vertx and vertx-web extensions would be _dropped_.

**Comment by mkouba** [comment]
@cescoffier Hm, I suppose that we want to keep the FQCN of API classes, e.g. `io.quarkus.vertx.web.RouteFilter`, right?

**Comment by cescoffier** [comment]
As it's not the most used feature, if that's an issue, I would not mind a new package with a note in the migration guide.

**Comment by mkouba** [comment]
> As it's not the most used feature, if that's an issue, I would not mind a new package with a note in the migration guide.

I mean in general, i.e. the same applies to `io.quarkus.vertx.ConsumeEvent`, `io.quarkus.vertx.web.Route`, etc.

**Comment by cescoffier** [comment]
I would do the same, move them to "api" packages and add a note in the migration guide. 
We already broke `@Route` anyway (the class containing the Method enum has changed).

**Comment by mkouba** [comment]
Ok. Why not.. ;-)

**Comment by gsmet** [comment]
How is it a problem to keep the current packages? Having subpackages is not a problem. And as long as things are not in `runtime`, these are supposed to be API packages.

I really don't see a good reason to break things in this case. Or did I miss something?

**Comment by mkouba** [comment]
> And as long as things are not in `runtime`, these are supposed to be API packages.

Hm, I thought that the convention is a bit different, e.g. for `quarkus-vertx-http` the api are all classes in all subpackages of `io.quarkus.vertx.http` except for `io.quarkus.vertx.http.runtime` and subpackages which is an "internal implementation". This way we would add `io.quarkus.vertx.web` next to the `io.quarkus.vertx.http`. It's possible but not ideal...

**Comment by gsmet** [comment]
Well, frankly better than breaking applications for no benefits.

TBH, I see the value of merging vertx and vertx-core but I don't see the value of merging vertx-web and vertx-http, except for creating problems, but I might be missing something.

BTW, another point about vertx-core/vertx, IIRC, one of the difference is that vertx-core didn't come with `jackson-databind`. By merging the two, you will make `jackson-databind` a core dependency of mostly everything. I don't know if it's still a problem but it used to be. So while the separation might need some adjustments, I'm not sure merging them is such a good idea (except if we decide `jackson-databind` is now a mandatory dependency).

**Comment by mkouba** [comment]
> BTW, another point about vertx-core/vertx, IIRC, one of the difference is that vertx-core didn't come with `jackson-databind`.

This is a good point. I personally find it very confusing that you can work with Vertx core API classes BUT `io.vertx.core.json.JsonObject` and friends don't work unless you add `quarkus-vertx` or `quarkus-vertx-web`. IIRC the `quarkus-vertx` and `quarkus-vertx-web` extensions were supposed to provide user API whereas `quarkus-http` and `quarkus-core` were more like an internal extensions. Good intentions but very confusing...

**Comment by cescoffier** [comment]
The dependency on databind has been removed in Vert.x 4, so that issue is not a problem anymore. Vert.x detects if databind is available and if so, use a mapper. If not available, it uses some built-in rules (not allowing every feature, but allows basic usage of JSON Object and JSON Array).

Merging vertx-web and vertx-http is mostly about @RouteFilter. Today, defining a filter, without being an extension or using the router directly is not possible. Note that these filters are called before RestEasy / RestEasy Reactive. Now, we can delay that merge as there is a workaround.

**Comment by mkouba** [comment]
We discussed this with @cescoffier and maybe we should only merge the `quarkus-vertx` with `quarkus-vertx-core` and rename `quarkus-vertx-web` to something like `quarkus-vertx-routes` or `quarkus-vertx-reactive-routes` (we could probably keep the package names, i.e. `io.quarkus.vertx.web`). @gsmet WDYT?

**Comment by stuartwdouglas** [comment]
+1 to keeping reactive routes separate.

**Comment by mkouba** [comment]
Ok, so I think that we should:

1. Merge the `quarkus-vertx` and `quarkus-vertx-core` extentions, keep the API packages, i.e. `io.quarkus.vertx.ConsumeEvent` and `io.quarkus.vertx.LocalEventBusCodec`; the final extension name is `quarkus-vertx-core`
2. Rename the `quarkus-vertx-web` extension to `quarkus-reactive-routes`; keep the package name `io.quarkus.vertx.web`.

This change should probably target 2.3 because 2.2 is a "hardening release".

**Comment by stuartwdouglas** [comment]
IMHO the final extension name should be `quarkus-vertx`, this way users that already were using it will not notice a difference, while `quarkus-vertx-core` was basically an implementation detail and not user visible.
