### ISSUE TITLE
DB Connection Leak with TxType.SUPPORTS in WebSocket handler

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#16790]
## Describe the bug
Database Connections Leak with TxType.SUPPORTS.  May be specific to WebSocket handler.

### Expected behavior
No Leak.

### Actual behavior
Leak.

## To Reproduce

See attached mod of ChatTest example.  See table.sql.

[websockets-quickstart2.zip](https://github.com/quarkusio/quarkus/files/6373897/websockets-quickstart2.zip)

Note that ChatRepo.read() leaks (TxType.SUPPORTS), however ChatRepo.save() does not leak (TxType.REQUIRED).

Example uses OrderedExecutor as previously advised by Stuart in order to resolve several other WebSocket issues.

Note also that `quarkus.websocket.dispatch-to-worker` (with removal of OrderedExecutor) does not seem to have any effect in 1.13.2.Final.

### Quarkus version or git rev

1.13.2.Final.  2.0.0.Alpha1 also looks problematic.
Was OK in 1.12.2.Final.

**Comment by jimbogithub** [comment]
Have just observed more leaks which suggest the problem is not WebSocket specific.

**Comment by jimbogithub** [comment]
![image](https://user-images.githubusercontent.com/5095954/116153168-01cc3000-a73b-11eb-971a-cc58d39d2d3d.png)

**Comment by gsmet** [comment]
@barreiro could you have a look please? It looks quite serious and might be related to the Agroal upgrade.

**Comment by jimbogithub** [comment]
@gsmet This appears to be fixed in 2.0.0.CR1.  The above reproducer certainly works OK now.  I'll need the CR2 before I can test in the full system.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by apat59** [comment]
Hi,
no for us.

**Comment by jimbogithub** [comment]
All OK for us.

**Comment by geoand** [comment]
🙏
