### ISSUE TITLE
Kafka AVRO (Strimzi / apicurio) - new required property

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16809]
## Describe the bug
Seems that a new property is required.

Quarkus version: Upstream

[The following](https://github.com/quarkus-qe/beefy-scenarios/tree/main/301-quarkus-vertx-kafka) scenario is failing after pointing to the latest Quarkus upstream changes.

New required property: `apicurio.registry.use-specific-avro-reader=true` 

Unset the following property: 

`apicurio.registry.avrodatumprovider=io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider`

**Comment by Ladicek** [comment]
Note that `use-specific-avro-reader` is only read by `DefaultAvroDatumProvider`. If you use `ReflectAvroDatumProvider`, which is still possible, then `use-specific-avro-reader` is ignored.

The problem you're facing is a different problem -- one that has to do with Avro class loading.
