### ISSUE TITLE
Kotlin 1.5.10

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#16806]
## Description

Dear developers,

regarding https://github.com/quarkusio/quarkus/issues/11428 would it be possible to switch to kotlin 1.5 now? Maybe for 2.0 if some stuff in quarkus needs to get adapted to use its new features.
Kotlin 1.5 is now available via the dependency manager.

## Implementation ideas
N/A

**Comment by famod** [comment]
This would also be required to get the Kotlin bits building in Quarkus CI.

FTR, @evanchooly commented on 1.5.0-*rc* [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.20tested.20on.20Java.2016/near/235726958):
> but even if the rc builds properly, we won't bump to 1.5 until it's final. and probably not right away at that.

**Comment by MartinX3** [comment]
Yes, Kotlin 1.5 seems to be final now according to its new version number.

And good to know what is needed there.
So it depends on https://github.com/quarkusio/quarkus/issues/16195

Kotlin 1.5 won't work with Java LTS 11 ?

**Comment by famod** [comment]
@MartinX3 
> Kotlin 1.5 won't work with Java LTS 11 ?

I haven't checked but I'd be very surprised if it doesn't work with 11.

**Comment by MartinX3** [comment]
Argh, I'm sorry, I misunderstood your message :)

**Comment by famod** [comment]
@evanchooly I added another item to the things to revert. Please let me know if you need support with any of that, it has become rather complex to grok.

**Comment by evanchooly** [comment]
I have all the bits mentioned in that last comment reverted.  waiting to see how CI fares, now.
