### ISSUE TITLE
Make quarkus.lambda.handler property a compile time property

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#16807]
## Description

At the moment the property `quarkus.lambda.handler` is a runtime property. However, compiling a project with multiple lambda handlers, requires you to specify this property during compile and during runtime. 

I think it would make more sense to change this property to a compile time property. This way, Quarkus could use the information to remove all the other handlers and optimize the build to only contain the required classes.

**Comment by andreas-eberle** [comment]
This is also a bit related to #16188.

**Comment by missourian55** [comment]
> I guess the original idea was that you could have one project with a bunch of lambdas then pick the one you wanted without recompilation. I honestly wonder if anybody uses quarkus.lambda.handler in practice though. Do you use it?

Yes, we use it for the reasons you mentioned "One project with a bunch of lambdas". During the CDK-Cloudformation deployment we inject environment variables. This is super flexible for us.

`quarkus.lambda.handler=${LAMBDA_HANDLER:default}`

**Comment by andreas-eberle** [comment]
Yes, we use it also since we have two lambdas that share a lot of code. And to be clear, this works at the moment. However, you have to specify the property `quarkus.lambda.handler` during compile time and during runtime. I think it would make sense to make it a compile time property and use it to remove all the other lambda handlers from the compilation. This can help reduce the binary size and runtime.
