### ISSUE TITLE
Security context not available in health check

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#16813]
## Describe the bug
The health checks don't appear to have access to the security context (`SecurityIdentity` object) which was created for the corresponding `q/health` call.

### Expected behavior
When a health check is called the authenticated user should be available via the `SecurityIdentity` object.

### Actual behavior
The `SecurityIdentity` object in the health check always appears to represent the anonymous user.

## To Reproduce

https://github.com/knutwannheden/health-check-security

1. Clone repo
2. Start with `mvn quarkus:dev` and connect with debugger.
3. Add breakpoints in `QuarkusSecurityIdentity` constructor and in `MyHealthCheck` method.
4. Call endpoint using `curl -H 'Authorization: Basic c2NvdHQ6amIwc3M=' http://localhost:8080/q/health/live`.

### Configuration
```properties
quarkus.http.auth.basic=true
quarkus.http.auth.proactive=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true

quarkus.security.users.embedded.users.scott=jb0ss
quarkus.security.users.embedded.users.stuart=test
quarkus.security.users.embedded.users.jdoe=p4ssw0rd
quarkus.security.users.embedded.users.noadmin=n0Adm1n

quarkus.security.users.embedded.roles.scott=Admin,admin,Tester,user
quarkus.security.users.embedded.roles.stuart=admin,user
quarkus.security.users.embedded.roles.jdoe=NoRolesUser
quarkus.security.users.embedded.roles.noadmin=user
```

### Output of `java -version`
```
$ java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+22-SA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+22-SA (build 11.0.9+11-LTS, mixed mode)
```

## Additional context
(Add any other context about the problem here.)

**Comment by knutwannheden** [comment]
As [suggested on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Security.20context.20propagation.20in.20health.20checks.3F) I tried protecting the health endpoints using the following additional configuration:
```properties
quarkus.http.auth.policy.role-policy1.roles-allowed=admin
quarkus.http.auth.permission.roles1.paths=/q/health/*
quarkus.http.auth.permission.roles1.policy=role-policy1
```
It doesn't appear to make any difference. In the health check the security identity is still not available.

Please also note that the reproducer contains an adapted `GreetingResource` (path `/hello-resteasy`) which also uses `CurrentIdentityAssociation.current()` to access the security identity. There it works as expected (i.e. the authenticated user is available).

**Comment by knutwannheden** [comment]
FWIW, I also tested with `quarkus-resteasy-reactive` instead of `quarkus-resteasy` and the result is the same there.

**Comment by xstefank** [comment]
I believe this should be able to be fixed as health is using different dispatch/handling of the routing context. I will try to fix this.

**Comment by xstefank** [comment]
So this works for the first invocation, however, the issue is that we cache the health check invocations in Mutiny Unis on the SmallRye side. I will need to find some way around this in SR.

**Comment by xstefank** [comment]
@knutwannheden I know how to fix this but it will require a refactoring in the SR health because Uni is not able to propagate context in the way we would require for this issue. The Uni/Mutiny propagates CDI context only for the first invocation of the health check, so this would work right now with an easy fix in Quarkus. However, for later invocations, the context isn't longer propagated which requires the mentioned refactoring. 

Would you prefer to have access at least for the first invocation of the health check or can you wait until I'll rework the Uni handling in SR?

**Comment by knutwannheden** [comment]
@xstefank Thank you for looking into this! Only having access for the first invocation is not that useful in my case, so I will just wait for the proper fix. Thanks again.
