### ISSUE TITLE
Disabling container image push is impossible

### ISSUE THREAD

**Issue by nielspardon** [quarkusio/quarkus#16831]
## Describe the bug

The Quarkus guide for building container images lists the `quarkus.container-image.push` property as a means of enabling / disabling the push of a container image. In practice this property will never disable the image push due to a bug in the current code base.

### Expected behavior
Set `quarkus.container-image.push` to `false` and observe that the container image is not pushed to the remote registry.

### Actual behavior
Set `quarkus.container-image.push` to `true` or `false` and observe that the container image is **always** pushed to the remote registry.

### Quarkus version or git rev

1.13.2 Final

## Additional context

Example [DockerProcessor.java](https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java):

The private method `createContainerImage()` ultimately makes the decision of whether to push the container image or not:

https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java#L149

`pushRequested` is a method parameter being set to `pushRequest.isPresent()` in both public methods `dockerBuildFromJar()` and `dockerBuildFromNativeImage()`:
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java#L85-L87

https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java#L122-L123

Both `dockerBuildFromJar()` and `dockerBuildFromNativeImage()` are containing a guard clause that returns early if `!pushRequest.isPresent()` or `!containerImageConfig.push` which means that `createContainerImage()` is never called if `pushRequest` would be absent meaning that the `pushRequest` parameter of `createContainerImage()` is always `true` and never `false`, also `createContainerImage()` is never called if `containerImageConfig.push` is `false`:
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java#L73-L76
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java#L105-L108

Similar pattern in [JibProcessor.java](https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java):

Same guard clause in `buildFromJar()` and `buildFromNative()`:
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L111-L114

https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L148-L151

Same invokation of `containerize()` with `pushRequest.isPresent()`:
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L131-L132

https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L163-L164

Same `if` statement in `createContainerizer()` that makes the decision whether to push or not:
https://github.com/quarkusio/quarkus/blob/6c2608571941914d51450b048bdff12a826d6952/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L197

**Comment by geoand** [comment]
I'll take a look soon

**Comment by geoand** [comment]
I can't reproduce this.

Setting `quarkus.container-image.push` works as expected for both boolean values and both container-image extension.

What **exactly** are you doing to make to problem appear?

**Comment by nielspardon** [comment]
I have to apologize. I was trying to change an existing internal multi module project and after a lot of debugging thought I fully understood what's going on. I was trying to conditionally configure the image push behavior using different Quarkus profiles.

Using Gradle I was using a snippet like the following and running `./gradlew image`:

```
task image {
    doFirst {
        System.setProperty("quarkus.container-image.build", "true")
        System.setProperty("quarkus.container-image.push", "false")
        System.setProperty("%prod.quarkus.container-image.push", "true")
        System.setProperty("quarkus.container-image.registry", imageRegistry as String)
        System.setProperty("quarkus.container-image.group", imageGroup as String)
        System.setProperty("quarkus.container-image.name", project.name)
        if (project.version.toString().matches("(.*)SNAPSHOT")) {
            // snapshot versions will be tagged as "latest".
            System.setProperty("quarkus.container-image.tag", "latest")
        } else {
            System.setProperty("quarkus.container-image.tag", project.version.toString())
            System.setProperty("quarkus.container-image.additional-tags", "release")
        }

        println "Pushing container image to: " +
                System.properties.get("quarkus.container-image.registry") + "/" +
                System.properties.get("quarkus.container-image.group") + "/" +
                System.properties.get("quarkus.container-image.name") + ":" +
                System.properties.get("quarkus.container-image.tag")
    }
    finalizedBy quarkusBuild
}
```

What I only realized after preparing a reproducible example for you is, that `prod` is the default Quarkus profile and I was simply having a false expectation of how Quarkus profiles work.

Sorry for the confusion. I hope that at least someone else can learn from my mistake.

**Comment by geoand** [comment]
No problem :)
