### ISSUE TITLE
Quarkus extension classpath issues with 2.0.0.Alpha1

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#16849]
## Describe the bug
I'm working on upgrading the RabbitMQ Client extension to support Quarkus 2.0.0.Alpha1 and am running into classpath issues it seems. Resources from the test-classpath added to the @RegisterExtension deployment are not being found. Furthermore when running ./mvnw clean verify `java.lang.IllegalAccessError: failed to access class ...` errors show up.

### Expected behavior
Running ./mvnw clean verify to finish successfully.

### Actual behavior
The build fails with multiple issues. Using the quarkus.test.flat-class-path=true setting has no effect what so ever.

## To Reproduce
Checkout https://github.com/quarkiverse/quarkus-rabbitmq-client branch 2.x and run ./mvnw clean verify. This works for the 1.x branch.

### Output of `uname -a` or `ver`
Darwin mac.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### GraalVM version (if different from Java)
-

### Quarkus version or git rev
2.0.0.Alpha1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Volumes/Data/Users/basp/.m2/wrapper/dists/apache-maven-3.8.1-bin/5jr7905sp869ck60ofuug4vpod/apache-maven-3.8.1
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Volumes/Data/Users/basp/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by stuartwdouglas** [comment]
You need to use .setFlatClassPath() on the QuarkusUnitTest. quarkus.test.flat-class-path=true only works for @QuarkusTest.

I am begining to wonder if I should just make this the default, QuarkusUnitTest does not support continuous testing anyway. I though that it would help show up actual issues that are a problem with dev mode, but it mostly seems to just cause problems like this, where you have the test attempting to access package private stuff from the platform.

**Comment by bpasson** [comment]
@stuartwdouglas that indeed works.

**Comment by bpasson** [comment]
Closing this issue.
