### ISSUE TITLE
It would be great to have native Let's Encrypt Support in a Quarkus Module

### ISSUE THREAD

**Issue by JimTyrrell** [quarkusio/quarkus#16850]
## Description

Let's Encrypt has become the standard for implemented HTTPS communications on the internet.  It would be lovely to use 1 or more of the libraries that deliver this capability in Java and make Let's Encrypt a module within Quarkus.  With some pointers or a bit of a mentor I would be willing to take this on.

## Implementation ideas
It seems like the library https://github.com/shred/acme4j is one of the leading Java libraries in this space.  I would be open to explore other libraries if required.  This library is Apache licensed so I would think it can be easily incorporated into this idea.

**Comment by sberyozkin** [comment]
Hi @JimTyrrell 
Thanks for this enhancement request - can you please look at #15559 - we've already had such requests earlier with some concrete work already being done at #15559 - have a look there and contribute please
I'll close this issue as a duplicate
Cheers
