### ISSUE TITLE
Outdated repository settings in io.quarkus.bootstrap:bootstrap-parent

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#1685]
This pom file still refers to the out of date `quarkus-nexus-release` repository id and imports the JBoss Nexus repository.

Also wondering: why is this structured as indipendent project? Please check with @cescoffier for special needs re relase process.

**Comment by cescoffier** [comment]
@Sanne what's bootstrap? Is it a specific branch?

**Comment by cescoffier** [comment]
Ah got it, it's in Alexey's branch. 
why is it an independent project? Shouldn't it be in _core_? 

If it's an independent project I need to update the release scripts (not a big deal, just must keep that in mind), and copy the release settings (take them from Arc).

**Comment by cescoffier** [comment]
wow... `NotEnoughCoffeeException`

Having a look....
