### ISSUE TITLE
It would be great for Quarkus to Support SNI for multiple HTTPS Certs available against a single IP address and port

### ISSUE THREAD

**Issue by JimTyrrell** [quarkusio/quarkus#16851]
## Description
Looking at the capabilities of Quarkus the requirement to bring in OpenShift, NGinx, and other software load balancers to front Quarkus, to only get the benefits of SNI(multiple ssl certs against multiple domains at one IP address and Port) seems like operational and network overhead that is unnecessary.

## Implementation ideas
Looking into the Undertow libraries and the Vert.x code base it seems that some of the building blocks to support SNI are available, but have not been exposed to Quarkus.  Again with a bit of a mentor I am willing to take this on and submit this as a Quarkus Module.

**Comment by geoand** [comment]
cc @stuartwdouglas @cescoffier

**Comment by cescoffier** [comment]
We should be able to expose the SNI capabilities from Vert.x.
