### ISSUE TITLE
Continuous Testing on Windows 10 cmd hang

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#16865]
## Describe the bug
When using the new continuous testing features on Windows 10 default terminal (cmd) the terminal hang and you cannot quit it via CTRL-C.

### Expected behavior
CTRL-C exit the application.

### Actual behavior
CTRL-C has no effect

## To Reproduce

Simple project to reproduce the issue
[try-continous-testing.zip](https://github.com/quarkusio/quarkus/files/6390500/try-continous-testing.zip)

1. Start  a terminal on Windows 10 via `cmd`
2. Start the application on dev mode : `mvn quarkus:dev`
3. Enable continuous testing : `e`
4. Disable continuous testing: `d`
5. Try to quit the application via CTRL-C

**Comment by axblu** [comment]
@loicmathieu
Have you (re)tested this with 2.0.0.CR3?
For me CTRL+c is still not working when Continous Testing is enabled. If disabled the application exits fine on CTRL+c.

**Comment by loicmathieu** [comment]
@axblu I do testing it OK. However I saw a small delay between hitting CTRL-C and the actual stop of the application.

**Comment by axblu** [comment]
@loicmathieu 
Ah! I have this issue with WSL in Windows, not cmd. Sorry for the wrong alert.
