### ISSUE TITLE
Add quarkus-logging-cloudwatch extension

### ISSUE THREAD

**Issue by bennetelli** [quarkusio/quarkus#16864]
## Describe the extension
We need to log our application log to Cloudwatch directly instead of the standard application log. That's why we would like to add it to quarkiverse.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
```properties
# Add your application.properties here, if applicable.
quarkus.log.cloudwatch.enabled=true
quarkus.log.cloudwatch.access-key-id=<your key>        
quarkus.log.cloudwatch.access-key-secret=<your secret>
quarkus.log.cloudwatch.region=us-east-1                
quarkus.log.cloudwatch.log-group=<my-log-goup>  
quarkus.log.cloudwatch.log-stream-name=<my-log-stream>
quarkus.log.cloudwatch.level=INFO                     
```

## Additional context

https://github.com/pilhuhn/quarkiverse-logging-cloudwatch

**Comment by gastaldi** [comment]
@bennetelli are you interested in leading the development of this extension?

**Comment by pilhuhn** [comment]
@gastaldi I volunteer @bennetelli as well :->

**Comment by gastaldi** [comment]
@pilhuhn @bennetelli I believe the extension already exists under https://github.com/pilhuhn/quarkiverse-logging-cloudwatch? Want to move it to the Quarkiverse org?

**Comment by pilhuhn** [comment]
Yes

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-logging-cloudwatch.
Added @bennetelli and @pilhuhn as maintainers. 

Enjoy! 😉

**Comment by gastaldi** [comment]
Go home @quarkus-bot, you're drunk

**Comment by bennetelli** [comment]
thank you very much @gastaldi :-)
