### ISSUE TITLE
Automatic compression of rolling log files

### ISSUE THREAD

**Issue by tarvfx** [quarkusio/quarkus#16877]
## Description

The current log file is not compressed, at least I did not find the configuration at [https://quarkus.io/guides/logging](https://quarkus.io/guides/logging). Uncompressed logs take up disk space, so can they support automatic compression?

**Comment by dmlloyd** [comment]
This should be possible by adding `.gz` to the rotation suffix.

**Comment by geoand** [comment]
It does work, see https://github.com/quarkusio/quarkus/issues/12260
