### ISSUE TITLE
Moving extensions outside of core repository

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#16870]
Proposal (with question marks for the ones I'm really not sure about):
- amazon-alexa
- amazon-services
- artemis-core
- artemis-jms
- consul-config?
- jgit
- jsch
- logging-gelf
- logging-json -> this one, I think we should just decommission it: we have another logging-json extension in the Quarkiverse with more features
- logging-sentry
- narayana-stm?
- tika
- vault? (@vsevel do you see a good reason to keep it in Core?)

Questions:
- should we change the groupId to `io.quarkiverse`?
- should we change the root package to `io.quarkiverse`?
- should we change the version? Using the Quarkus version scheme might be confusing with compatibility (e.g. we have a 1.13.3.Final extension but it's indeed also compatible with Quarkus 2).
- what do we do if some of these extensions are used by the Platform? Typically I wonder if jgit isn't used by Camel Quarkus.

**Comment by geoand** [comment]
+1 for `consul-config`

**Comment by aloubyansky** [comment]
Let's clarify what extensions we _want_ to be excluded from the platform. This is probably the key question.

**Comment by maxandersen** [comment]
> Let's clarify what extensions we _want_ to be excluded from the platform. This is probably the key question.

you mean something like:

* extensions that are not key to quarkus core team release schedule and resources (i.e. apache-tika is for sure interesting but not something we at least for now would be spending energy on)
* extensions which are simpler to maintain upstream from quarkus core 
* extensions that are not highly used and could just be deprecated
* extensions we don't expect having to update on regular basis 
* extensions whos testsuite takes up alot of resources and not critical we know it failed on a PR update (this might not be that relevant with gib in place to reduce builds)

Other criteria ?

**Comment by aloubyansky** [comment]
It's important to keep that in mind that each integrated extension will influence the overall dependency constraint set (possibly resulting in adjustments in the dependencies of other highly critical members) of the platform.

**Comment by maxandersen** [comment]
@aloubyansky you mean if one of these were the source of a specific transitive dependency now the members in platform need to adjust their dependencies to explicitly list it ? i.e. remove jsch and camel use it then we need two things: camel to explicility use it in their build; add it expliclity to platform so its consistently considered in tools/dep chain ?

**Comment by aloubyansky** [comment]
That too actually. In general, if Camel depends on a non-Camel extension, either that non-Camel extension should be added to the platform or that Camel extension should be removed from the platform. Or we have to exclude that non-Camel extension from the platform BOM to unlock the Quarkiverse version of that extension in the catalog.

What I meant in my previous comment was simply any platform member may create a conflict with any other platform member. By removing members that aren't critical as platform members we are reducing the chances of creating/resolving conflicts among the members on every member version update.

**Comment by loicmathieu** [comment]
I copy here my remarks from Zulip regarding the logging-gelf extension: I would not move logging-gelf out of core as it's the only extension that provides centralized logging which is a very common needs when dealing with complex applications.
I was surprised to see it used by a lot of people when I saw on zulip or on mail the list of features used.
It's still very very common to have centralized logs with Graylog or ELK these days, not everybody just logs inside docker console and use some cloud facility to centralize logs. logging-gelf is used for this purpose.

So I'm -1 for `logging-glef` this is a core features for a cloud ready framework.

As for how to move, we must change the groupId and the version scheme as it will not evolve in the same rate as Quarkus so it should not use the same version. As for changing the root package name, I'm more balanced as it will create a big breaking change but not very hard to solve and it's a best practive to align root package with groupId.

**Comment by maxandersen** [comment]
> As for how to move, we must change the groupId and the version scheme as it will not evolve in the same rate as Quarkus so it should not use the same version

I think this is very much dependent on the way the extension is maintained. i.e. if you want maintain branches to i.e. support 1.11.x at the same time as 2.x quarkus then using 1.x and 2.x as version numbers makes sense. I think in practice many (but not all) quarkiverse extensions would if not completely at least somewhat have some connection to the base quarkus version.

**Comment by aloubyansky** [comment]
TBH, I don't think changing the version is critical at all. I think we could even honor some (or all) of those with the `io.quarkus` groupId. They've been "pioneers" of the platform 1.x after all :)

**Comment by vsevel** [comment]
> vault? (@vsevel do you see a good reason to keep it in Core?)

+1
no, I do not see a good reason. it would make sense to limit core to what is really necessary, or something that is used by most applications.
vault is a specific product, and not everybody is using vault, or even _a_ vault.
in fact I have started toying around with Azure Key Vault, and I was going to create a quarkiverse extension. that would make sense to move vault there too.

the only drawback is that extensions in quarkiverse do not get the same level of scrutiny and review that was done in core. 
this could lower the level of quality for extensions, or at least the perception of quality from consumers. for instance extensions in core were guaranteed to support native. but not in quarkiverse I believe. enterprises are looking for quality then quantity, in that order. do we have a way to rate the quality, completeness and maturity of an extension? there is the _preview/stable_ tag we had on extensions in core. is that the right approach? should there be some quality related elements as well (e.g. test coverage; or a _contains integration tests_ label)? or capabilities (e.g. supports _native_)?

**Comment by aloubyansky** [comment]
We'll definitely want to indicate which extensions work in native in the tools. `preview/stable` though is in the hands of the extension maintainers. The Quarkus core team can't possibly check and make sense of every extension's metadata out there.

**Comment by loicmathieu** [comment]
@vsevel the bigger issue I see working in the quarkiverse instead of the core is to find reviewer. This is related to your concern about quality and testing/scrutiny such extensions has.

You tend to work alone on your extension and merge your own PR without any reviewer.

Maybe creating a quarkiverse channel in Zulip where quarkiverse extension maintainers can ask for PR review could be an improvements in the area.

**Comment by vsevel** [comment]
> You tend to work alone on your extension and merge your own PR without any reviewer.

on freemarker yes, but by the lack of candidates or gouvernance structure, not by choice. now that camel is using it, may be there is a natural fit going forward. but the fact that I was able to do so proves my point in terms of quality expectations for consumers.

should there be an official list of high quality extensions that are required to pass quality checks? e.g. at least 1 reviewer in the core committers, test coverage > x, up-to-date with quarkus core, ... and may be those can find their ways in the quarkus universe bom? just some ideas.

> Maybe creating a quarkiverse channel in Zulip where quarkiverse extension maintainers can ask for PR review could be an improvements in the area.

yes.

**Comment by loicmathieu** [comment]
>  and may be those can find their ways in the quarkus universe bom? just some ideas.

+1 for that, one more BOM to manage, I'm not sure @aloubyansky will love that ;)

**Comment by aloubyansky** [comment]
That depends. Platform is not limited to a certain quality standard. It's also a collaborative effort which implies commitment to resolve possible incompatibilities/conflicts in a timely manner and coordination between the members.

**Comment by vsevel** [comment]
> one more BOM to manage

why? I meant the existing [quarkus-universe-bom](https://github.com/quarkusio/quarkus-platform/blob/main/bom/pom.xml)
the project says: _Quarkus Platform aggregates extensions from Quarkus Core and those developed by the community_
who says why camel, debezium and a few others go in this bom, and not others? what are the criterias?

**Comment by gsmet** [comment]
> So I'm -1 for logging-gelf this is a core features for a cloud ready framework.

The point of moving this sort of extensions outside of the core is not a way to say they are not useful. The main purpose is to make contributions easier if it doesn't have to be in core.

For me, that's typically the sort of extensions that will have more contributors outside of the core. And having it in the core brings nothing.

Just have a look at the JSON extension in the Quarkiverse. It got a lot more attention than the one in core.

Also, the plan is to make all these extensions visible everywhere so that won't change anything from a user point of view.

And just to be clear, while the maintainer POV is important to us, we also have to ponder it with the cost of having all these extensions in the Core for EVERYONE contributing to the Core repo.

**Comment by aloubyansky** [comment]
> who says why camel, debezium and a few others go in this bom, and not others? what are the criterias?

I guess, that'll be "the platform club".
In short:
1) quality criteria (e.g. native support, dev experience, performance characteristics, etc);
2) commitment to collaboration with the rest of the members to not break/block releases;
3) fitting the primary purpose of the stack the platform represents.

Each extension contributes something, hopefully, great and valuable. But platforms have members that should coordinate their dev and release processes. The more extensions the platform includes the more potential dependency conflicts there will be and some of them may be not trivial to resolve to guarantee the compatibility.
The third point above should also not be overlooked. The platform has a purpose - it defines a development stack for some primary use-cases.

At this point, it's called `universe`, which kind of implies no limits. Although, at the same time, Quarkus from the beginning has been manifesting its opinionated spirit. There is a bit of a contradiction and a compromise. We didn't have a notion of the quarkiverse and couldn't properly represent the wide ecosystem in our tools. The `universe` BOM was the only way to grow it.
However, with the evolution of our dev tools, what is currently known as the `universe` platform may stop being the one and only Quarkus platform. We will definitely support multiple platforms and may consider creating specialized platform stacks.

BTW, I will send a proposal about an alternative platform model to the dev list this or next week.

**Comment by loicmathieu** [comment]
> Also, the plan is to make all these extensions visible everywhere so that won't change anything from a user point of view.

@gsmet don't take it wrong as I don't want to critizise anything/anybody but we already discussed the issue with documentation in the guide page (where people find extensions) and the inclusion on code.quarkus.io and the quarkus plugin months ago for Quarkiverse extensions, and it's still not there. 
So moving an extension out of core will make it disapear (at least for now).

You have my vote, but I'm OK with what you decided guys, I'll volonteer to maintain `logging-gelf` out of core if you wanted but I still think having centralized logging is a core features of a microservice framework. As Jboss logging has no tcp handler and no flexible JSON formatter, this is the only way to do it.

**Comment by gastaldi** [comment]
Just a clarification that "moving an extension out of core" does not mean "removing the extension from the platform", it's just moving to a separate repository for easier maintenance, which could lead to more frequent releases. 

The extension will still be listed in our tooling and in the documentation guide pages.

**Comment by loicmathieu** [comment]
> The extension will still be listed in our tooling and in the documentation guide pages.

This means the guide will still be inside the Quarkus repository as it's the only way to currently have this

**Comment by gastaldi** [comment]
I´d also add to the possible candidates: 

- neo4j
- elasticsearch-rest-client
- scala (which seems to be already superseded by https://github.com/quarkiverse/quarkus-scala3)
- azure-functions-http
- funqy
- swagger-ui

**Comment by gsmet** [comment]
@marcinczeczko @middagj @michael-simons just to make sure you are aware of this effort and that we are planning to move the Amazon Services, Artemis and Neo4j extensions to the Quarkiverse for 2.6 together with a bunch of other extensions. The core repo is becoming too big and we are doing a first batch of moving things to the Quarkiverse. The idea is also to make it easier to contribute to these extensions.

The full rationale is explained here: https://groups.google.com/g/quarkus-dev/c/hUAxFf04lDw .

I will do the migration work and make sure everything is done in the best way possible. I'll also put in place relocations and everything that's needed for an easy migration.

FYI, the migration process keeps the history and the authorship. You will be made maintainer of your respective extensions.

After this migration, the release will have to be done separately using the Quarkiverse process (which is very simple, you can do everything from the GitHub UI).

They will be included in the Ecosystem CI and visible here https://status.quarkus.io/ so that we can track their compatibility with new Quarkus versions.

**Comment by michael-simons** [comment]
Hi,
i can’t reply to the group, so I do it here:

I don’t mind moving the Neo4j extension out of the core, actually quite the contrary, 
if

- it is still easy to find, both from the Core repo and what is more important
- from the docs and what’s more important 
- from https://code.quarkus.io <https://code.quarkus.io/>

The last point has been bugging us with Spring Boot for quite a while:
The Neo4j extension there is also part of the core, so that it is available on start.spring.io <http://start.spring.io/>.

Those generators are paramount for (smaller) extensions and integrations to be seen.

I am completely fine of not burdening the maintainers of Quarkus or Spring Boot with our extensions.
I. think most often it’s much easier for us than for the framework maintainers to asses if things are correctly integrated or not.
Kinda „owning“ the repo of such an extension makes this easier.

If there’s kinda agreement in place that the extensions maintainer use / obey the rules of the core (i.e. checkstyle, build plugins, whatever you have), I think everybody wins.

Cheers,
Michael.

**Comment by gsmet** [comment]
@michael-simons yes, I plan to make the guides visible on the Guides page and the extensions will be visible on code.quarkus.io. We still have to improve on this though and I plan to work on making things better in the next few weeks.

And don't hesitate to provide feedback if you see things that could be improved on this front.

**Comment by maxandersen** [comment]
@michael-simons much appreciated with the response. 

What we've done recently which hasn't been advertised much yet is that extensions that are not part of the Quarkus platform still show up in code.quarkus. As an example search for CXF on https://code.quarkus.io now and see how that works. You should see 0 platform 1 other on screen and from there it show up and is accessible.

same is availalbe in cli and IDE's.

feedback very much welcome.

**Comment by michael-simons** [comment]
Yeah, something like that makes a lot of sense.
I understand the burden of having the extensions in the core and I have discussed this in the past with Stéphane from Spring Boot already. 

The dimensions I see are

- Quality of extensions: Who makes sure that „other“ has the same quality as „platform“? 
- Who maintains it: here I am in favor of having the authors of the „integrated thing“ being responsible. In the end, it’s their interest to be on the platform / framework
- Release cycle: What has kept me and the team I am working busy a lot the last years is the different cadence one sits in as a driver author: On the one hand there’s the product (here Neo4j the database), then there’s frameworks like Quarkus plus in our case Spring Data Neo4j. Moving the above responsibility in our direction frees us a bit from one site.
- Visibility: Decoupling the presence on one of the code generators from the fact whether a project is maintained as direct part of the platform or as an external extension is a great step forward. Most of the time the discussion to integrate things on those starters have a political dimension to them as well… So it’s also great removing one thing to optimize for from the equation

Having said all that:
My goal is to keep Neo4j an integral part of Quarkus. 
Unrelated the whole discussion, developing for (and actually with) Quarkus brought personal joy to me and we do actually have customers using Quarkus, the driver extension and Neo4j-OGM together and I think this is great!

**Comment by aloubyansky** [comment]
It depends on how quality is defined. As to the implementation details, performance, features, etc it's responsibility of the maintainers of the extension. Generally, Quarkus core developers aren't going to be monitoring the quality of the implementation but still consulting https://status.quarkus.io/#quarkiverse for the CI status and general compatibility with the Quarkus core.

Another potentially related aspect is compatibility with the Quarkus platform (that integrates extensions developed outside of the core repo by aligning their transitive dependencies). The Quarkus platform is basically making sure a set of extensions developed outside of the Quarkus core repo do not have conflicts in their transitive dependencies and can be used in any combination in the same application. The Quarkus platform does imply certain quality standards and commitment from the platform members to possibly resolve conflicts in time to respect the release schedule.

**Comment by middagj** [comment]
I agree with @michael-simons, completely fine of not burdening the maintainers of Quarkus with the Artemis extension. However, Artemis is not mine, I added the extension because we wanted to use it with Quarkus in a project. One of the reasons is it still a basic extension, there is a possibility to do a lot more. So let's see how it goes, happy to be a maintainer, but probably with same effort as the past two years.

**Comment by vsevel** [comment]
@gsmet and @sberyozkin I recommend adding @kdubb as an admin to the quarkiverse vault repo if he agrees. Kevin has done significant contributions to the vault extension lately. I think this is well deserved.

**Comment by gastaldi** [comment]
@vsevel that sounds like a great idea! I created https://github.com/quarkiverse/quarkiverse-devops/pull/15 which adds him to the list of maintainers to the https//github.com/quarkiverse/quarkus-vault repo

**Comment by kdubb** [comment]
@vsevel Thanks for the confidence. I'm willing to continue contributions and help maintain the Vault extension.

That being said, I'm just getting introduced to this issue and getting caught up on the previous discussion here. Many of the points brought up by @michael-simons seem pertinent to me. Specifically, I agree that the extension guides should be available amongst the normal "guides" and available on "code.quarkus.io". An extension you can find, is an unused extension and unused extension will fall into disrepair rapidly.

Finally, and I apologize if this is common knowledge to others, I have a question about about quality/compatibility is to be maintained in these previously core and now "quarkiverse" extensions.

**With each release of Quarkus are all these extensions verified automatically during release? If not, are we saying it's up to each extension's maintainer(s) to keep up with Quarkus's releases and do testing/verification/releasing?**

I ask this specifically because I've been working on the Vault extension and it is integrated with _a lot_ of other extensions. It seems like this will be a daunting task for the Vault extension to manually verify itself with every release of Quarkus.

**Comment by aloubyansky** [comment]
> With each release of Quarkus are all these extensions verified automatically during release? If not, are we saying it's up to each extension's maintainer(s) to keep up with Quarkus's releases and do testing/verification/releasing?

It is automatically verified nightly against the current `main` branch of the Quarkus repo. The status is reflected at https://status.quarkus.io/#quarkiverse
If an extension fails a CI with the current `main` branch of Quarkus, it is **not** treated as a blocker for the Quarkus release. It could either be a bug in Quarkus, in which case it would have to be reported and fixed in the Quarkus repo. Or it could be a deliberate breaking change, in which case, the maintainers of the extension will have to adjust to it once the Quarkus release becomes available.

The compatibility with a specific Quarkus version is supposed to be recorded in registry.quarkus.io, so the dev tools (including code.quarkus.io) do not suggest incompatible versions of the Quarkiverse extensions for the selected Quarkus platform release. All the dev tools and the registry data model are designed with this in mind. However, we are in fact lacking the automatic compatibility data collection. This is what will have to improve, ASAP.

Practically speaking, hopefully, for the suggested extensions it won't become a pain, given that the integration is not highly complex. We've seen numerous examples of the extensions staying on Quarkus versions that are 6 months older than the current one and they still worked. However, that depends on the number of features and API the impl depends on.

**Comment by maxandersen** [comment]
> 've been working on the Vault extension and it is integrated with _a lot_ of other extensions

That is interesting - what other extensions do you see use it ? 

about auto verification that is something we want to get in for sure and automate as much as we possibly can.

**Comment by kdubb** [comment]
Well it's a Config source and it's currently the only core implementation of `CredentialsProvider`. Just between those two things there are a lot touch points for the Vault extension, including Agroal, and most of the reactive database driver extensions.

**Comment by maxandersen** [comment]
@kdubb but that is a fairly stable interface is it not ? Since agroal and reactive db drivers are still in core we will see if it breaks "clients" and the automated testing will also capture it. If the API is stable that should give us all enough heads up ?

**Comment by michael-simons** [comment]
Hey. Just to let you know: after the first releases has been cut from the Neo4j quarkiverse extension, they way it still is on code.quarkus.io I have to say I’m sold on the solution. Great way forward for both 3rd party vendors and Quarkus. Well done.

**Comment by gsmet** [comment]
I did the first batch. I think we can close this one and open a new one should we move others.
