### ISSUE TITLE
JPA Converter with auto-apply not working

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#16874]
## Describe the bug
When defining a AttributeConverter that converts a special type with auto-apply=true it is not applied at all.

### Expected behavior
The AttributeConverter shown under "To Reproduce" should store the Java-Money type as a custom String format and load it appropriately

### Actual behavior
The AttributeConverter is ignored, writing the Objects String representation which is total bogus. It is necessary to add the Converter annotation as a workaround.

```
@NotNull
@Convert(converter = JpaMoneyConverter.class)
Money retailPrice;
```

## To Reproduce

Define a JPA entitiy using a Java Money typed field, without adding Converter annotation.
Write a JPA Attribute-Converter like this.

```
@Converter(autoApply = true)
public class JpaMoneyConverter implements AttributeConverter<Money, String> {

    @Override
    public String convertToDatabaseColumn(Money money) {
        return String.format("%s|%s", money.getNumber().toString(), money.getCurrency().getCurrencyCode());
    }

    @Override
    public Money convertToEntityAttribute(String dbData) {
        String[] split = dbData.split("\\|");
        return Money.of(new BigDecimal(split[0]), Monetary.getCurrency(split[1]));
    }
}
```

Save the entity to a database.
Consult DB: a cryptic byte-string was saved which cannot be loaded any more.

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

## Additional context
I know that the auto-apply work in Eclipselink, so I am not yet sure if this is a bug in Quarkus and how it configures Hibernate or Hibernate itself.

**Comment by markusdlugi** [comment]
@Sanne @DavideD @geoand, we are experiencing the same thing with Hibernate Reactive. Not sure if this is related rather to Hibernate or rather to Quarkus?

**Comment by geoand** [comment]
> @Sanne @DavideD @geoand, we are experiencing the same thing with Hibernate Reactive. Not sure if this is related rather to Hibernate or rather to Quarkus?

I have no idea TBH. Hibernate is not my wheelhouse

**Comment by yrodiere** [comment]
It's most likely a Quarkus issue. I'll have a look next week if nobody gets to it.
