### ISSUE TITLE
UTF-8 not working for Multipart RestEasy Inputstream

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#16878]
Using Multipart, we are uploading a csv file that may contain any kind of characters, so UTF-8 encoding is necessary. 

Somehow however the encoding never works. Here I have a reproducer - try to upload a file with Postman with special characters like German Umlauts (ü, ö, ä) or ß..

https://github.com/MarcusBiel/quarkus-multipart-reproducer

The issue is maybe related to this:
https://github.com/quarkusio/quarkus/issues/10323

Using Quarkus 1.13.2.Final with Java 16 but still having the issue.

**Comment by gsmet** [comment]
Use the `quarkus-resteasy-multipart` extension. That will fix your problem.

See https://quarkus.io/guides/rest-json#multipart-support .

**Comment by hantsy** [comment]
My working example. https://github.com/hantsy/quarkus-sandbox/blob/master/multipart/

**Comment by hantsy** [comment]
But in another real project, I tried to add Chinese chars in the doc, and upload, then print the file content, some issues, only the Chinese displayed as *??*.
Tried to add the `quarkus.resteasy.multipart.input-part.default-charset=UTF-8` explicitly, still not worked.

**Comment by gsmet** [comment]
Are you sure they are valid UTF-8 characters? With the extension, UTF-8 is the default so you don't have to set anything.

**Comment by MarcusBiel** [comment]
Found the issue. There must be two UTF-8 conversions - once from InputStream to String, second from String to byte[] to store it as a blob in the DB. The latter was missing:
 from.getData().getBytes(StandardCharsets.UTF_8);
