### ISSUE TITLE
Rest Data with Panache check if "?sort" parameter is specified

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#16871]
## Description

To override the default behaviour of the HTTP GET method for rest-data-with-panache resource, we should create a facade class. It could be combination of Entity + PanacheRepository(facade) + PanacheRepositoryResource. 
Either we use HTTP GET method with or without "?sort" parameter we need to override repository method `public PanacheQuery<UserEntity> findAll(Sort sort)`

However, it could be useful to leave the default implementation of this method if we only want to override the default behaviour of HTTP GET without specifying "?sort" parameter. Thus the method `public PanacheQuery<UserEntity> findAll()` should affect this. Currently by overriding the `findAll()` method do not affect anything.

Code example: https://github.com/kshpak/panache-qa/blob/feature_get/src/main/java/org/acme/resteasyjackson/PersonRepository.java

**Comment by FroMage** [comment]
Thanks @gytis :)
