### ISSUE TITLE
Boolean type get number as true value at runtime 

### ISSUE THREAD

**Issue by puertigris** [quarkusio/quarkus#16873]
In my REST project

I have a controller with a function

```java
@PUT
@Path("/passive/{requestId}")
public BaseResponse updatePassiveLiveness(@PathParam("requestId") @Valid @Pattern(regexp = UUID, message = INVALID_UUID) String requestId,
                                              @Valid OperationParameter<LivenessResultRequest> parameter,
                                              @HeaderParam(USER_NAME) String userName,
                                              @HeaderParam(MERCHANT_MODULE_CLIENT) String clientPermissionCode) {
      /// my code here ...
}
``` 
and my `LivenessResultRequest` class contain an element.
```java
@NotNull
private Boolean alive;
```
When I call my API using Postman with a number.
```json
{
    "data": {
        "alive": 5
    }
}
```
I always get `true` value not an exception. Why?

**Comment by gsmet** [comment]
@geoand maybe you know the answer to this one?

**Comment by geoand** [comment]
Doesn't ring a bell, but I'd like to see a project that reproduces this behavior

**Comment by puertigris** [comment]
Hi, I created a project that reproduces this behavior: [https://github.com/puertigris/quarkus-issue](https://github.com/puertigris/quarkus-issue).
When I ran it, I ran into exactly the problem I was having.
Hope to hear the explantation from you guys.

**Comment by geoand** [comment]
Thanks for the reproducer.

This seems to be a Jackson feature which however you can turn of in your Quarkus application by introducing an [ObjectMapperCustomizer](https://quarkus.io/guides/rest-json#configuring-json-support) like so:

```java
@Singleton
public class Customizer implements ObjectMapperCustomizer {
    @Override
    public void customize(ObjectMapper objectMapper) {
        objectMapper.configure(MapperFeature.ALLOW_COERCION_OF_SCALARS, false);
    }
}
```
