### ISSUE TITLE
Reconsider the name/usage of io.quarkus.grpc.runtime.annotations.GrpcService

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#16872]
This annotation is currently a CDI qualifier and is used to inject a gRPC stub. On the server side a gRPC service should be annotated with `@javax.inject.Singleton` and extend the appropriate service definition (aka the abstract `ImplBase` class).

I think that it would make sense to rename the qualifier to something like `@GrpcClient` (aligned with MP rest client) or `@GrpcStub`. And use the `@GrpcService` to mark a gRPC service (i.e. impl of `io.grpc.BindableService`). Note that a user does not care about the fact that his gRPC service is a bean, similarly if you create a JAX-RS endpoint you don't need to define the CDI scope either.

Moreover, the annotation should not live in `io.quarkus.grpc.runtime.annotations` which is by convention not part of the public API.

So my proposal is to:
1. Move `io.quarkus.grpc.runtime.annotations.GrpcService` to `io.quarkus.grpc.GrpcClient` or `io.quarkus.grpc.GrpcStub`
2. Introduce `io.quarkus.grpc.GrpcService` that would be used to mark a gRPC service class (instead of  `@Singleton`)

**Comment by michalszynkiewicz** [comment]
@cescoffier wdyt? If we're going to do it better do it sooner than later and changing the major number in the version is a good occasion

**Comment by mkouba** [comment]
Of course, this would be a breaking change...

**Comment by mkouba** [comment]
We could also make `io.quarkus.grpc.runtime.annotations.GrpcService.value()` optional and derive the value from the injection point by default (i.e. a field or param name).

**Comment by cescoffier** [comment]
> Move io.quarkus.grpc.runtime.annotations.GrpcService to io.quarkus.grpc.GrpcClient or io.quarkus.grpc.GrpcStub

I would go for client. Stub is reminding me RMI and Corba. 

> Introduce io.quarkus.grpc.GrpcService that would be used to mark a gRPC service class (instead of @Singleton)

+1 - It would be better too as we can force it to be singleton (it has to be, because it cannot be proxied)

I believe we can handle the change without too much breakage. But if we have to, it's the right time.

**Comment by mkouba** [comment]
> I would go for client. Stub is reminding me RMI and Corba.

No problem. I thought it would make sense because the generated class that is injected has the `Stub` suffix ;-).

> I believe we can handle the change without too much breakage.

Any ideas how? We could mark the annotation as deprecated and pollute the code with special branches for deprecated parts but I don't think it's worth the effort.

**Comment by cescoffier** [comment]
Yes, that's what I was thinking, but if it gets too ugly, we should just break.

**Comment by mkouba** [comment]
Not only it's ugly but we'll end up with two `@GrpcService` annotations on the class path... which is not good.
