### ISSUE TITLE
Unable to configure kafka reactive messaging with AWS Glue Schema Registry

### ISSUE THREAD

**Issue by jjdestef3** [quarkusio/quarkus#16889]
Having an issue integrating the AWS Glue schema registry with quarkus reactive messaging for kafka. I have a property defined as:

mp.messaging.outgoing.eligibility.schemaName=<some schema name>

Notice the camelcase in schemaName. The Glue schema registry is looking for a value for schemaName but from the log output quarkus seems to be putting that property out in all lower case as schemaname so the default approach for adding additional kafka properties doesn't work. I also tried to put quotes around schemaName and that put out a property in the log as "schemaname". So quotes around the property and lowercase schemaname.

Is there a way to maintain the camel casing in the properties file or another approach to adding kafka properties to an application.

Quarkus version: 1.11.6

**Comment by cescoffier** [comment]
Hum, I believe it's a bug in SmallRye REactive Messaging where we do weird things to compute the Kafka configuration. Does it happen with 2.0.0.alpha1 ?

**Comment by jjdestef3** [comment]
Hi,

Haven't been able to compile what I have with Alpha yet. Missing the universe bom in maven. I guess the short answer might be that this won't work with 1.11.6? 

Thanks

**Comment by jjdestef3** [comment]
Hi,

One more quick question. Would there be another way to introduce/inject kafka configuration into apps using reactive messaging or the kstreams extension besides the configuration file?

Thanks

**Comment by cescoffier** [comment]
So, unfortunately, what we had to do to support the "unknown" properties of Kafka is not possible until MicroProfile 4 (thanks to the Config update). So we fixed in in Quarkus 2.0.

About your question on the configuration, you can implement a CDI producer exposing a `Map<String, String>` and `@Named("default-kafka-broker")`.

**Comment by jjdestef3** [comment]
Thanks,

That will probably work for now.

**Comment by cescoffier** [comment]
Closing - please re-open if you still have the issue.
