### ISSUE TITLE
com.fasterxml.jackson.module:jackson-module-blackbird 2.12.3

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#16886]
## Description

Please upgrade the package `com.fasterxml.jackson.module:jackson-module-blackbird` in the universe bom from 2.12.1 to 2.12.3

## Implementation ideas

N/A

**Comment by gsmet** [comment]
I marked https://github.com/quarkusio/quarkus/pull/16490 for backport, it will be pushed to the next 1.13.
