### ISSUE TITLE
Unexpected transitive import of resteasy when using resteasy-reactive

### ISSUE THREAD

**Issue by thuringia** [quarkusio/quarkus#16884]
## Describe the bug
When importing the `resteasy-reactive`, or `resteasy-reactive-jackson` extensions, there appears to be a dependency issue causing Quarkus to output a warning that Mutiny support, via the `resteasy-mutiny` extension is needed.
This is the same warning as shown in #15400

Based on the discussion in #15400 this appears to be a transitive import issue causing the non-reactive versions of RESTeasy being imported. It is unclear if this is caused by the `resteasy-reactive-*` extension itself, or a side-effect of including other extensions.  

From the dependency graphs attached below, it appears to be caused by `io.quarkus:quarkus-oidc-client-filter`.

### Expected behavior
Using the `resteasy-reactive-jackson` extension provides infrastructure for endpoints to respond to requests in a non-clocking way even when using other Vertx- or Mutiny-based code downstream.

### Actual behavior
The bug manifests in the aforementioned Gradle warning, as well as inconsistent behavior when running Quarkus.
<details>
<summary> ./gradlew build -Dquarkus.package.type=uber-jar</summary>
<code>
> Task :quarkusGenerateCode
preparing quarkus application

> Task :quarkusGenerateCodeTests
preparing quarkus application

> Task :quarkusBuild
building quarkus jar

Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. Reactive REST endpoints in your application that return Uni or Multi will not function as you expect until you add this extension. Endpoints that need Mutiny are: de.company.#{io.smallrye.mutiny.Uni<de.company.#Response> startImport(de.company.#Request body)}
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.google.common.collect.Multimap (sources: JacksonProcessor > de.company.#, JacksonProcessor > de.company.#$Builder)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
Duplicate entry codegen-resources/examples-1.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/service-2.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/paginators-1.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/customization.config entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry META-INF/maven/io.netty/netty-transport-native-epoll/pom.properties entry from io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime) will be ignored. Existing file was provided by io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)
Duplicate entry META-INF/maven/io.netty/netty-transport-native-epoll/pom.xml entry from io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime) will be ignored. Existing file was provided by io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)
Duplicate entry javax/xml/bind/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/xml/bind/helpers/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/xml/bind/util/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/el/PrivateMessages.properties entry from jakarta.el:jakarta.el-api::jar:3.0.3(runtime) will be ignored. Existing file was provided by org.glassfish:jakarta.el::jar:3.0.3(runtime)
Dependencies with duplicate files detected. The dependencies [com.sun.activation:jakarta.activation::jar:1.2.1(runtime), jakarta.activation:jakarta.activation-api::jar:1.2.1(runtime)] contain duplicate files, e.g. javax/activation/ActivationDataFlavor.class
Dependencies with duplicate files detected. The dependencies [jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime), org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime)] contain duplicate files, e.g. javax/xml/bind/Validator.class
Dependencies with duplicate files detected. The dependencies [io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime), io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)] contain duplicate files, e.g. io/netty/channel/epoll/EpollChannelConfig$1.class
Dependencies with duplicate files detected. The dependencies [jakarta.el:jakarta.el-api::jar:3.0.3(runtime), org.glassfish:jakarta.el::jar:3.0.3(runtime)] contain duplicate files, e.g. javax/el/BeanELResolver$BPSoftReference.class
Dependencies with duplicate files detected. The dependencies [org.jboss.logging:commons-logging-jboss-logging::jar:1.0.0.Final(runtime), commons-logging:commons-logging::jar:1.2(runtime)] contain duplicate files, e.g. org/apache/commons/logging/impl/SimpleLog$1.class
Dependencies with duplicate files detected. The dependencies [software.amazon.awssdk:sns::jar:2.16.19(runtime), software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)] contain duplicate files, e.g. codegen-resources/paginators-1.json
Dependencies with duplicate files detected. The dependencies [org.jetbrains.kotlin:kotlin-reflect::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib-jdk7::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib-jdk8::jar:1.4.31(runtime)] contain duplicate files, e.g. META-INF/versions/9/module-info.class

BUILD SUCCESSFUL in 4m 1s
18 actionable tasks: 14 executed, 4 up-to-date
Time: 0h:04m:04s
</code>
</details>

In this case it was detected in unit tests hitting an endpoint returning `Uni<T>` (`T` being a simple data-class) that request an OIDC access token and then data from an API, all provided as Wiremock test resources. With calls to the Wiremocks sometimes not happing or returning `null`. A deployment on a test system behaves similarly, even with "real" data.

## To Reproduce

1. Run build
2. Run tests or start server to hit endpoint

### Configuration
<details>
<summary>gradle.properties</summary>
<code>
quarkusPluginVersion=1.13.2.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPluginId=io.quarkus
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.13.2.Final
kotlinPluginVersion=1.4.31
</code>
</details>

<details>
<summary>settings.gradle.kts</summary>
<code>
pluginManagement {
    val quarkusPluginVersion: String by settings
    val quarkusPluginId: String by settings
    val kotlinPluginVersion: String by settings

    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        kotlin("jvm") version kotlinPluginVersion
        kotlin("plugin.allopen") version kotlinPluginVersion
        id(quarkusPluginId) version quarkusPluginVersion
    }
}
rootProject.name = "libra"
</code>
</details>

<details>
<summary>build.gradle.kts</summary>
<code>
plugins {
    kotlin("jvm")
    kotlin("plugin.allopen")
    id("io.quarkus")
    id("com.diffplug.spotless") version "5.11.1"
}

repositories {
    mavenLocal()
    mavenCentral()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(kotlin("stdlib-jdk8"))

    implementation(enforcedPlatform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))

    // implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-amazon-sns")
    implementation("software.amazon.awssdk:netty-nio-client")
    implementation("io.quarkus:quarkus-container-image-jib")
    implementation("com.fasterxml.woodstox:woodstox-core")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-logging-json")
    implementation("io.quarkus:quarkus-micrometer")
    implementation("io.micrometer:micrometer-registry-cloudwatch2")
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.quarkus:quarkus-mongodb-client")
    implementation("io.quarkus:quarkus-oidc-client")
    implementation("io.quarkus:quarkus-oidc-client-filter")
    // this set of extensions compiles without Gradle warnings:
    // implementation("io.quarkus:quarkus-resteasy")
    // implementation("io.quarkus:quarkus-resteasy-jackson")
    // implementation("io.quarkus:quarkus-resteasy-mutiny")
    // end
    // this is what we want/should use but causes a Gradle warning:
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    // end
    implementation("io.quarkus:quarkus-scheduler")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-vertx")
    implementation("io.netty:netty-transport-native-epoll:linux-x86_64")
    implementation("io.netty:netty-transport-native-kqueue:osx-x86_64")
    implementation("io.vertx:vertx-lang-kotlin")
    implementation("io.smallrye.reactive:smallrye-mutiny-vertx-web-client")

    implementation("io.cloudevents:cloudevents-json-jackson:2.0.0")

    // de.otto.prada.product
    implementation("org.apache.commons:commons-compress:1.20")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("net.jcip:jcip-annotations:1.0")

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.quarkus:quarkus-junit5-mockito")
    testImplementation("io.rest-assured:rest-assured")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.27.2")
    testImplementation("org.awaitility:awaitility")
}

group = "de.company"
version = "1.0.0-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    kotlinOptions.javaParameters = true
}

tasks.withType(JavaCompile::class) {
    options.compilerArgs.add("-Xlint:unchecked")
    options.compilerArgs.add("-Xlint:deprecation")
}

spotless {
    java {
        toggleOffOn()
        importOrder()
        removeUnusedImports()
        googleJavaFormat("1.10.0")
    }

    kotlin {
        toggleOffOn()
        ktlint("0.41.0")
    }

    kotlinGradle {
        target("*.gradle.kts")
        toggleOffOn()
        ktlint("0.41.0")
    }
}
</code>
</details>

Dependency tree:
file version due to character limit: [dependencies.txt](https://github.com/quarkusio/quarkus/files/6393748/dependencies.txt)

As @FroMage mentioned that `org.jboss.resteasy:resteasy-core` and `io.quarkus:quarkus-resteasy-common` are unexpectly imported, I queried the dependency graph for them as well:
<details>
<summary>./gradlew -q dependencyInsight --dependency resteasy-core</summary>
<pre>
org.jboss.resteasy:resteasy-core:4.5.9.Final
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - Forced

org.jboss.resteasy:resteasy-core:4.5.9.Final
+--- io.quarkus:quarkus-resteasy-common:1.13.2.Final
|    +--- io.quarkus:quarkus-universe-bom:1.13.2.Final
|    |    \--- compileClasspath
|    \--- io.quarkus:quarkus-rest-client:1.13.2.Final
|         +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
|         \--- io.quarkus:quarkus-oidc-client-filter:1.13.2.Final
|              +--- compileClasspath (requested io.quarkus:quarkus-oidc-client-filter)
|              \--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
+--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
\--- org.jboss.resteasy:resteasy-client:4.5.9.Final
     +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
     \--- org.jboss.resteasy:resteasy-client-microprofile:4.5.9.Final
          +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
          \--- io.quarkus:quarkus-rest-client:1.13.2.Final (*)

org.jboss.resteasy:resteasy-core-spi:4.5.9.Final
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - Forced

org.jboss.resteasy:resteasy-core-spi:4.5.9.Final
+--- io.quarkus:quarkus-universe-bom:1.13.2.Final
|    \--- compileClasspath
+--- org.jboss.resteasy:resteasy-client:4.5.9.Final
|    +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
|    \--- org.jboss.resteasy:resteasy-client-microprofile:4.5.9.Final
|         +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
|         \--- io.quarkus:quarkus-rest-client:1.13.2.Final
|              +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
|              \--- io.quarkus:quarkus-oidc-client-filter:1.13.2.Final
|                   +--- compileClasspath (requested io.quarkus:quarkus-oidc-client-filter)
|                   \--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
+--- org.jboss.resteasy:resteasy-client-api:4.5.9.Final
|    +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
|    \--- org.jboss.resteasy:resteasy-client:4.5.9.Final (*)
\--- org.jboss.resteasy:resteasy-core:4.5.9.Final
     +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
     +--- io.quarkus:quarkus-resteasy-common:1.13.2.Final
     |    +--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
     |    \--- io.quarkus:quarkus-rest-client:1.13.2.Final (*)
     \--- org.jboss.resteasy:resteasy-client:4.5.9.Final (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.
</pre>
</details>

<details>
<summary>./gradlew -q dependencyInsight --dependency quarkus-resteasy-common</summary>
<pre>
io.quarkus:quarkus-resteasy-common:1.13.2.Final
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - Forced

io.quarkus:quarkus-resteasy-common:1.13.2.Final
+--- io.quarkus:quarkus-rest-client:1.13.2.Final
|    +--- io.quarkus:quarkus-universe-bom:1.13.2.Final
|    |    \--- compileClasspath
|    \--- io.quarkus:quarkus-oidc-client-filter:1.13.2.Final
|         +--- compileClasspath (requested io.quarkus:quarkus-oidc-client-filter)
|         \--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)
\--- io.quarkus:quarkus-universe-bom:1.13.2.Final (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

</pre>
</details>

### Screenshots
n/a

### Output of `uname -a` or `ver`
local environment: `Linux SurfacePro 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux`

The deployment target is an AWS Fargate container, i.e. a Linux environment

### Output of `java -version`
local:
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)

deployment target:
openjdk:15.0.2:
quarkus.jib.base-jvm-image=openjdk@sha256:d3906cc726058e9b7fcd0a90b775bc83490d9f4efc82394fb31f65123cb7efef

### GraalVM version (if different from Java)
default version when running `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true`

### Quarkus version or git rev
1.13.2.Final

this also appear in any 1.13 release

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7)
OS:           Linux 5.10.16.3-microsoft-standard-WSL2 amd64

## Additional context
originally discussed in #15400

**Comment by stuartwdouglas** [comment]
You need to use quarkus-rest-client-reactive instead of quarkus-rest-client. That said we should detect this and display a nice warning.

**Comment by geoand** [comment]
@michalszynkiewicz don't we already have such a warning in place?

**Comment by thuringia** [comment]
@stuartwdouglas That's good to know, but we're not directly including the REST client at the moment. Is this a problem of nested dependencies then, i.e. we add the OIDC client, which uses the REST client, which loads the non-reactive RESTeasy libraries?
Or could this be fixed by adding the reactive REST client, event though we don't use it ourselves, to supply the correct infrastructure for the OIDC client?

**Comment by geoand** [comment]
The oidc client will have a resteasy-reactive variant from Quarkus `2.0.0.Alpha2` on

**Comment by thuringia** [comment]
I'd guess this issues fixes itself then once alpha 2 is available. That's great news

**Comment by michalszynkiewicz** [comment]
@geoand I don't think we have it (yet)

**Comment by geoand** [comment]
Closing this as `quarkus-oidc-client-reactive-filter` is available.
