### ISSUE TITLE
Redesign the multi-stage docker build

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#16881]
## Description
Our documentation contains an example of a multi-stages docker file to build a container running a native executable. That example is on https://quarkus.io/guides/building-native-image#using-a-multi-stage-docker-build. 

That example is using a Quarkus image as based that we would like to retire (quay.io/quarkus/centos-quarkus-maven:21.0.0-java11). 

## Implementation ideas

Here is another working variant that uses an image that we will continue to produce regularly:

```dockerfile
## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 AS build
COPY pom.xml /project/
COPY mvnw /project/mvnw
COPY .mvn /project/.mvn
USER quarkus
WORKDIR /project
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /project/src
RUN ./mvnw package -Pnative

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
WORKDIR /work/
COPY --from=build /project/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

The idea is to rely on the maven wrapper instead of expecting Maven to be provided by the base image. First, it allows the user to decide which version of Maven should be used (3.6.3 vs. 3.8.1).  It also makes the usage of Gradle straightforward. 
That new requirement demand the user to run ` mvn -N io.takari:maven:0.7.7:wrapper` first to install the maven wrapper if not already there.

@maxandersen @n1hility @geoand @mkouba WDYT? (I didn't create a PR yet, because I want to discuss it first). 

NOTE: The go-offline is used to provision in its own layer the required dependencies, meaning that if you change your code and re-build it will recover from the layer `COPY src ...`

**Comment by geoand** [comment]
I personally like it a lot!

**Comment by cescoffier** [comment]
Should we move forward?

**Comment by mkouba** [comment]
I'm not a big fan of maven wrapper but it sounds reasonable if we document this requirement properly.

**Comment by maxandersen** [comment]
I'm +1

I do think we will evolve this in future anyway if buildpack becomes viable. 

But removing need for this monster of image is worth more than having mvn wrapper use imo. 

Users who need/want that can customize as need.

**Comment by cescoffier** [comment]
Ok, I will open a PR tomorrow.

**Comment by ThoSap** [comment]
RHEL 8.4 was [released on 2021-05-21](https://distrowatch.com/?newsid=11249) 😉
Can we update the base image to [registry.access.redhat.com/ubi8/ubi-minimal:**8.4**](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.4)?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/17764 should take care of it
