### ISSUE TITLE
Some "SLF4J:" traces are being randomly printed in Windows

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16896]
## Describe the bug
When running a Quarkus application in Windows, at startup time the app sometimes print these SLF4J traces:

```
SLF4J: io.netty.util.internal.InternalThreadLocalMap
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: io.netty.channel.MultithreadEventLoopGroup
SLF4J: io.netty.util.internal.PlatformDependent
SLF4J: io.netty.util.internal.PlatformDependent0
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: io.netty.util.internal.logging.InternalLoggerFactory
SLF4J: loggers will work as normally expected.
SLF4J: io.netty.util.ResourceLeakDetector
SLF4J: io.netty.util.internal.CleanerJava9
SLF4J: io.netty.channel.nio.NioEventLoop
```

This is unexpected and it's not happening in other platforms. 

Probably, this is related to https://github.com/quarkusio/quarkus/issues/15884, but not quite sure.

## To Reproduce
A windows based machine is needed.

1. git clone `https://github.com/Sgitario/quarkus-startstop`
2. cd `quarkus-startstop`
3. git checkout `reproducer_16896`
4. `mvn clean verify -Ptestsuite -Dtest=ArtifactGeneratorBOMTest#quarkusUniverseBomExtensionsA`

### Quarkus version or git rev
1.13.2.Final

**Comment by geoand** [comment]
Is this still an issue?
