### ISSUE TITLE
Unable to make the Vert.x cache directory in Windows

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16895]
## Describe the bug
When running a Quarkus application in Windows, this warning is sometimes printed:

```
{"timestamp":"2021-04-28 13:02:58","sequence":346,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.vertx.core.runtime.VertxCoreRecorder","level":"WARN","message":"Unable to make the Vert.x cache directory (C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\vertx-cache) world readable and writable","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"fv-az158-860","processName":"target/quarkus-app/quarkus-run.jar","processId":3172}
```

Which is unexpected as it should create a temporary folder. 
I think this is related to the changes made in https://github.com/quarkusio/quarkus/issues/7678. Concretely: https://github.com/quarkusio/quarkus/pull/15541/files#diff-a38e0d86cf6a637c19b6e0a0e23959f644886bdcc0f0e5615ce7cfa0e6bc9909R244

### Expected behavior
The Vert.x cache directory should work in Windows

## To Reproduce

A windows based machine is needed.

1. git clone `https://github.com/Sgitario/quarkus-startstop`
2. cd `quarkus-startstop`
3. git checkout `reproducer_16895`
4. `mvn clean verify -Ptestsuite -Dtest=ArtifactGeneratorBOMTest#quarkusUniverseBomExtensionsA`

The test should pass, but it's failing.

### Quarkus version or git rev
1.13.2

**Comment by cescoffier** [comment]
Are you sure it's not created? I'm pretty sure it's the permissions that are failing not the creation.
I don't have a windows machine to test that, unfortunately.

**Comment by cescoffier** [comment]
@Sgitario ping?

**Comment by rsvoboda** [comment]
@cescoffier yes, it's about permissions

I see `"message":"Unable to make the Vert.x cache directory (C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\vertx-cache) world readable and writable"` with Quarkus 2.0.2.Final

**Comment by cescoffier** [comment]
Ok, so we may want to reduce the log level to debug, or not trying the call on windows. Wdyt?
