### ISSUE TITLE
Kotlin, resteasy, reactive-postgres throwing an exception

### ISSUE THREAD

**Issue by oberstrike** [quarkusio/quarkus#16914]
## Describe the bug
The following project doesn't work. I'm getting an UnsatisfiedResoulutionException when I try to start the base test. I hope someone can find my mistake.

### Expected behavior
Programm runs without exceptions.

### Actual behavior
![grafik](https://user-images.githubusercontent.com/11050732/116604944-18d37380-a92f-11eb-934c-1b46aa903e4b.png)

##Enviroment:
- Windows 10
- Kotlin
- Java 15
- Quarkus
- Postgres 

## To Reproduce
Project: https://github.com/oberstrike/QuarkusIssueNr16914

**Comment by Davide-Di-Do** [comment]
Hi @oberstrike I've checked your code and I've noticed a couple of things, and maybe are not strictly related to your problem, but you can review them. First thing is that you are using blocking panache Postgresql into a context of reactive controller; the second point is that you are using the Active Record pattern and Repository pattern, but I think that are exclusively usable. Fill free to comment my thoughts. 
Later I'll create for you an PR with a possible fix

**Comment by oberstrike** [comment]
That would be awesome!

**Comment by Davide-Di-Do** [comment]
As promosed here your controller class updated
```
@Entity
class GreetingEntity(
        @Id
        var id: UUID? = null,
        var message: String? = null
)

@ApplicationScoped
class GreetingRepository : PanacheRepository<GreetingEntity>

@Path("/hello-resteasy-reactive")
class ReactiveGreetingResource(
        private val greetingRepository: GreetingRepository
) {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun hello(): Uni<List<GreetingEntity>> {
        return greetingRepository
                .listAll()
    }
}
```
but as mentioned before the little updates do not solve the problem that seems to be deep in the context manager and how it manages the transaction manager. I've tried also with other tries:

1. tried to add this configuration quarkus.arc.unremovable-types=io.smallrye.context.jta.context.propagation.* to prevent to remove some useful bean;
2. change quarkus-resteasy-reactive-jackson with quarkus-resteasy-mutiny

**Comment by geoand** [comment]
Is this still a problem?

If it is, is it also a problem if you use RESTEasy Reactive?

**Comment by oberstrike** [comment]
Yes, the same problem with 2.2.3.Final. Davide-Di-Do's workaround is the only solution to this problem. @geoand

**Comment by geoand** [comment]
I tried this with Quarkus from `main` (what will be `2.5.0.CR1` in a few days) and the problem no longer exists
