### ISSUE TITLE
Quarkus Panache reactive should return a uni for the saved entity when flushing

### ISSUE THREAD

**Issue by deathwaiting** [quarkusio/quarkus#16921]
## Description

In spring jpa data repositories, using `save()` method will persist the entity and return an object of the updated entity, along with the generated ID and anything else.

in Panache however, when using the active record pattern, we should use `persistAndFlush()` as I understand.

If I am working on blocking-panache, then my entity will be updated, and I can use the generated value in the next line.
However when using reactive-panache with reactive hibernate, `persistAndFlush()` will return a `Uni<Void>` , and I have to subscribe for it with a callback.
The problem is that , I will normally want `persistAndFlush()` to actually return `Uni<? extends PanacheEntity>` , so that I can chain the returned entity directly to the next step in the pipeline and make the code more in the functional style, but with the current implementation, I have to put the entity into a  separate variable and I end with an uglier code like this:

````
var entity = createMyEntity(); 
  entity.persistAndFlush().onItem().ifNotNull().transform(v -> entity).invoke(this::processMyEntity);
  ````

While I was hoping to make it like this:

````
createMyEntity().persistAndFlush().onItem().ifNotNull().invoke(this::processMyEntity);
````

**Comment by loicmathieu** [comment]
Duplicated with #14475

I'm closing this one, you can watch / provides feedback on #14475 instead.
