### ISSUE TITLE
smallrye-jwt prevents the use of customized tokens, ignores @PermitAll

### ISSUE THREAD

**Issue by NinjaTycoon** [quarkusio/quarkus#16935]
## Describe the bug
I'd like to use customized JWT handling for certain methods, and use smallrye-jwt for others. However, I cannot find a way to prevent smallrye-jwt from trying to verify a token being passed via the Authorization header.  Having @PermitAll has no effect.  It still returns HTTP 401.  

### Expected behavior
I expect it to not process REST calls that are marked with @PermitAll or via some other means of exclusion to enable custom JWT handling. 

### Actual behavior
If you pass any token that smallrye-jwt cannot verify, it returns 401.  It always tries to verify.  

## To Reproduce
Enable smallrye-jwt and try to pass a token it does not have the public key to verify with @PermitAll enabled.  

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Enable smallrye-jwt
2. Create a REST method with @PermitAll
3. Pass a token.  

### Configuration
```properties
# Add your application.properties here, if applicable.
I've tried a lot of things to get around this with configuration, from no configuration to configuration that in theory would allow the token to get by.  In this case, the token is EC256, so the correct configuration that should at least verify it would be:

mp:
  jwt:
    verify:
      relax-key-validation: true
      algorithm: ES256
      publickey:
        location: META-INF/resources/key-public-ec-p256.pem
      issuer: SC-CORSAIR-TS

Yet, it does not work even with that.  Though, I don't want it to even try to verify.  

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Linux hostname 4.18.19-100.fc27.x86_64 #1 SMP Wed Nov 14 22:04:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

### Quarkus version or git rev
    <quarkus.platform.version>1.13.3.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc28.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.19-100.fc27.x86_64", arch: "amd64", family: "unix"

## Additional context
The ultimate goal is for this to use smallrye-jwt for common REST API while having the ability to handle a lot of different public keys of various algorithms for other use cases, such as integration with other systems that provide their own public key.  Thus, I need either for smallrye-jwt to be able to multiple public keys, issuers and algorithms, or, as is documented above, the ability to permit tokens it can't be handled to be passed so custom code can handle the other cases.

**Comment by sberyozkin** [comment]
@NinjaTycoon I believe you need to disable the [proactive authentication](https://quarkus.io/guides/security-built-in-authentication#proactive-authentication), it is not really related to `smallrye-jwt`, can you try it please

**Comment by sberyozkin** [comment]
@NinjaTycoon I believe you need to disable the [proactive authentication](https://quarkus.io/guides/security-built-in-authentication#proactive-authentication), it is not really related to `smallrye-jwt`, can you try it please

**Comment by sberyozkin** [comment]
Also, if all the tokens are issued by OIDC providers then you might want to experiment with `quarkus-oidc` and its multi-tenancy support to avoid writing a code to verify the tokens - if it is the only option then please also consider using `smallrye-jwt`'s `JWTParser`

**Comment by NinjaTycoon** [comment]
> @NinjaTycoon I believe you need to disable the [proactive authentication](https://quarkus.io/guides/security-built-in-authentication#proactive-authentication), it is not really related to `smallrye-jwt`, can you try it please

Thank you very much!  This did solve my problem.  I'm able to pull out the custom token while still using the RS256 with smallrye-jwt in another REST endpoint.  Can you add a link to 'security-built-in-authentication#proactive-authentication' from the 'security-jwt' documentation so help people in the future?  I read that page up and down for a solution lol.  

I will explore quarkus-oidc, too.  Though, my uses cases are a bit custom today.  Perhaps I can conform to OpenID standards at some point.  So, viability today will come down to how much I can customize with quarkus-oidc.  

One question for understanding my options.  I noticed that if I access an injected JsonWebToken it then tries to validate it.  This is not an issue; but, is this a reliable way to enforce validation by smallrye-jwt?  
---
I just want to give my hats off to the Quarkus team!  I've been doing this for 4 decades, programming in 30 languages by age 30, using countless platforms (including JBoss 2.3.2 with Marc in 2002), and I have the highest praise possible for Quarkus.  You guys have really made Java a best-of-breed microservices platform!  While no documentation is perfect, your documentation is very high quality and overall very complete.  And now, you proved, your support is top notch!  Thank you!  Thank you!  Thank you!

**Comment by sberyozkin** [comment]
Hi @NinjaTycoon 
Glad it worked for you, and thanks for appreciating what the large Quakus team does :-). Sometimes we can get the right solution fast, sometimes it takes longer, but yes, we are here to help.

Good point about linking to the proactive authentication - as it happens a PR has already been open to update the smallrye-jwt version with a few minor doc updates - so I've just added a small section there.

Yes, `JsonWebToken` can only be accessed if it has been verified (unless a custom factory is used to skip the verification)

Please see #16937
