### ISSUE TITLE
Scheduler - document how to pause/resume a @Scheduled method with identity

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#16942]
This follows up on https://github.com/quarkusio/quarkus/pull/16855.

We should document this functionality in the [Scheduler Reference Guide](https://quarkus.io/guides/scheduler-reference#scheduler).

**Comment by mkouba** [comment]
@adrianfiedler would you care to take this one?

**Comment by adrianfiedler** [comment]
> @adrianfiedler would you care to take this one?

Of course, I assume it is this here? https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/scheduler-reference.adoc

**Comment by mkouba** [comment]
> > @adrianfiedler would you care to take this one?
> 
> Of course, I assume it is this here? https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/scheduler-reference.adoc

Great! The source of the guides is in the main repo: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/qute-reference.adoc

**Comment by adrianfiedler** [comment]
Hi @mkouba ,
please check if this is enough documentation https://github.com/quarkusio/quarkus/pull/17096
Should there also be an example for identity with expression?
