### ISSUE TITLE
Improved Security Logging

### ISSUE THREAD

**Issue by mrickly** [quarkusio/quarkus#16947]
## Description

It seems that the security exceptions mappers do not log anything, see for instance https://github.com/quarkusio/quarkus/blob/e355848fa3eba6131db7687778e31859f28f8e52/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/ForbiddenExceptionMapper.java

Using our own ForbiddenExceptionMapper would probably not help much, since the Security Exception do not seem to include much usable information at all, see for instance https://github.com/quarkusio/quarkus/blob/15f8ebb5ce9fed6560a61a44990378de4cb8eb23/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/check/RolesAllowedCheck.java#L61

## Implementation ideas

- The security exceptions could contain relevant informations about the cause of the exceptions. For instance: ForbiddenException could contain:  
  - The location/resource that triggered the exception
  - A list of roles allowed at that location 
  - A list of the roles bound to the identity.  
- There should be a documented mechanism to either override the existing ExceptionMappers or customize them. In particular, this would allow Quarkus applications to log security exception informations if they wish to do so.

**Comment by sberyozkin** [comment]
@mrickly 

> Using our own ForbiddenExceptionMapper would probably not help much

You can get most of the information you are after with JAX-RS contexts injected into a custom mapper, `UriInfo` can be used to get the request path, `ResourceInfo` - the resource class/method, etc.
Logging the security relevant request info is not really recommended so for some users Quarlkus logging it would not be good.

**Comment by mrickly** [comment]
Hi @sberyozkin , thank you for you response and input. We will give it a try with our own exception mapper.

**Comment by michalvavrik** [comment]
> There should be a documented mechanism to either override the existing ExceptionMappers or customize them. In particular, this would allow Quarkus applications to log security exception informations if they wish to do so.

Now it's documented here https://quarkus.io/guides/security-built-in-authentication-support-concept#how-to-customize-authentication-exception-responses so I'll go ahead and close the issue, please feel free to re-open it if you don't agree.
