### ISSUE TITLE
Jackson with kotlin default constructor arguments fails in Native images

### ISSUE THREAD

**Issue by cjbooms** [quarkusio/quarkus#16979]
## Describe the bug
In native mode, default arguments do not work in Kotlin Jackson data classes.
Given the below data class:
```
@RegisterForReflection
data class Table(
  @param:JsonProperty("name")
  @get:JsonProperty("name")
  @get:NotNull
  val name: String,
  @param:JsonProperty("idColumn")
  @get:JsonProperty("idColumn")
  @get:NotNull
  val idColumn: String = "id"
)
```
and this Json:
```
{
  "name": "my-table-name"
}
```

### Expected behavior
 The Json should be deserialised to this object:
 ```
 Table(name = "my-table-name",  idColumn = "id")
```

### Actual behavior
In native mode, the following error is thrown.
```
"message": "Cannot construct instance of `ie.zalando.fabric.fes.operator.models.Table`, problem: Parameter specified as non-null is null: method ie.zalando.fabric.fes.operator.models.Table.<init>, parameter idColumn\n
```

## Additional context
I found a similar bug raised and [fixed in MicroNaut](https://github.com/micronaut-projects/micronaut-kotlin/pull/222/files) for this issue and have verified that adding the following fixes the issue
 - [reflection-config.json.txt](https://github.com/quarkusio/quarkus/files/6423750/reflection-config.json.txt)
 - [resources-config.json.txt](https://github.com/quarkusio/quarkus/files/6423708/resources-config.json.txt)

It would be great if these files could be bundled in Quarkus, similar to what was done in Micronaut. I'd be happy to issue the PR, if someone could let me know where they belong. In Micronaut, the live here:
[src/main/resources/META-INF/native-image/io.micronaut.kotlin/kotlin-runtime](https://github.com/micronaut-projects/micronaut-kotlin/tree/master/kotlin-runtime/src/main/resources/META-INF/native-image/io.micronaut.kotlin/kotlin-runtime)

**Comment by geoand** [comment]
@cjbooms thanks for reporting.

Would you be able to test https://github.com/quarkusio/quarkus/pull/16990?

**Comment by geoand** [comment]
Closing this as we didn't get any feedback.
