### ISSUE TITLE
add multi-tenancy support to keycloak-authorization

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#16973]
## Description

Add multi-tenancy support to keycloak-authorization so that it can be used together with the oidc-multi-tenancy.

## Implementation ideas

Configuration could be similar to the oidc-configuration:

```properties
# for default tenant
quarkus.keycloak.policy-enforcer.enable=true

# for specific tenant
quarkus.keycloak."tenant".policy-enforcer.enable=true
```

**Comment by pedroigor** [comment]
If we could leverage the existing support from OIDC that would be awesome. But I guess that would require some refactoring on `keycloak-authorization` config. Do you agree @sberyozkin ?

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, yeah, definitely, we can do it for the static tenants easily - by the time Keycloak Policy enforcer is called `RoutingContext` will already have a resolved `tenant-id` attribute. I reckon it would be reasonable to restrict it to the static tenants for now....
