### ISSUE TITLE
Make shutdown cause/trigger available

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#16976]
## Description

CLI apps might need to know if shutdown is due to normal exit or due to Ctrl+C/SIGINT, so there should be a way to distinguish those (and maybe other signals too).

## Implementation ideas

Enhance the `ShutdownEvent` with some kind of "cause" or "trigger" property or maybe have different events to observe for different shutdown triggers.

**Comment by geoand** [comment]
It's actually pretty easy in Quarkus code to determine whether or not the shutdown came from a `SIGINT` as `io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread` is the Shutdown Hook involved.

Ultimately `io.quarkus.runtime.StartupContext#close` gets called (no matter what the source of the shutdown is) so if we have some state in there we could propagate it

**Comment by xtaixe** [comment]
@manovotn

> What exactly do you consider a "normal" exit for CLI app?

Maybe I didn't express that properly. I meant the program just finishes cause there's nothing more to do (e.g. `ls`) as opposed to keep running doing or waiting for something (e.g. tail/follow logs), which in our case is when you need to stop it using CTRL+C.

> Also what other signals do you think are worth distinguishing? I don't see much value in telling user if it was SIGINT or SIGTERM but i might be missing something.

Maybe it's not worth distinguishing. In our case it's not needed, as long we can distinguish finishing from interrupted is enough. But if the information is already there maybe just provide it and let the user decide.

**Comment by manovotn** [comment]
Right, we can only probably differentiate between normal program finish and "all else".
That is, a situation when `ShutdownHookThread` is not invoked (normal) and when it is invoked (`SIGINT`, `SIGTERM`, ... but also `System.exit()`).

I'll try to get to it later this week and put together a PR.
