### ISSUE TITLE
Unused resourceEntry.getKey() string replacement in KubernetesProcessor

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#16993]
Unused `resourceEntry.getKey()` string replacement in KubernetesProcessor.
Replaced string is not assigned. Not Sure if it can be removed or the replaced value should be persisted somewhere.

```java
resourceEntry.getKey().replace(root.toAbsolutePath().toString(), KUBERNETES);
```
https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java#L174

**Comment by geoand** [comment]
@iocanel should we just remove this piece of code or does it aim to actually do something?

**Comment by iocanel** [comment]
Created a PR.
