### ISSUE TITLE
provide JSON Schema support for web-frontend and quarkus (backend)

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#16992]
## Description

I am missing a JSON Schema serde (= serializing and deserializing) support especially for web-frontend and quarkus (backend).

It would be nice to provide simple integration for validating Rest-Endpoints through https://vertx.io/docs/vertx-json-schema/java/ (Json-Schema has the benefit that it can be used on both client and server). For example:

```
@GET
@Path("/user")
@Consumes(MediaType.APPLICATION_JSON)
@JsonSchema(myschema.json)
public User createOrUpdateUser(User user){
...
} 
```

or

```
@GET
@Path("/user")
@Consumes(MediaType.APPLICATION_JSON)
public User createOrUpdateUser(User user){
JsonSchemaValidator validator = JsonSchemaValidator.loadResource("..");
List<ValidationException> validations = validator.validate(user);
..
} 
```
Quarkus can provide the glue code to make it simple to produce and consume (e.g. for validation) json-schema at various places.

## Implementation ideas

Quarkus can provide 
- an annotation `@JsonSchema `with a property path to include the json-schema from the quarkus resources-folder.
- a simple api to include json-schema within the code

**Comment by nimo23** [comment]
I am missing a JSON Schema serde support especially for web-frontend and quarkus (backend).

**Comment by geoand** [comment]
Closing as `won't fix`
