### ISSUE TITLE
Possibility to inject HttpClient in RestClient

### ISSUE THREAD

**Issue by sciack** [quarkusio/quarkus#16991]
## Description

Have the possibility to provide a configured HttpClient (could be Apache or others) to RestClient, so could support strange authentication or strange redirect scenarios. This could also be related to https://github.com/quarkusio/quarkus/issues/12517

## Implementation ideas

On user perspective the HttpClient should/could be declared as Provide or give a FQN of the factory in the properties.

**Comment by geoand** [comment]
What kind of configuration do you apply to the Apache Client?

**Comment by sciack** [comment]
Currently in our implementation we configure:
1. Redirect & circular redirect
2. Socket timeout
3. Connection pooling
4. Keystores for TLS authentication

Maybe some of them are redundant, but some can be specific of the context/environment/client we have to call.

**Comment by michalszynkiewicz** [comment]
1. What do you mean by circular redirect? Redirects are supported in Quarkus 2.0. Moreover, if you use rest-client-reactive, you also get `quarkus.rest.client.max-redirects` property which lets you configure maximum number of redirects.
2. Rest Client supports `connectTimeout` and `readTimeout` - would that do for you?
3. I don't know about connection pooling...
4.  There are quite a few options to conflgiure SSL for the rest client, [MicroProfile Rest Client Guide](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#ssl) has the details. Please note, that rest-client-reactive doesn't support custom `HostnameVerifier` or `SSLContext`, as described in [Quarkus Rest Client Reactive Guide](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/rest-client-reactive.adoc#known-limitations)

**Comment by sciack** [comment]
Thanks for the answer, can you please point out to all the possible configuration in quarkus for the RestClient, I'm ok to try some more things, but I was stuck not able to find how to configure it.

**Comment by michalszynkiewicz** [comment]
> Is fair to assume that all the configuration in https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html are available in Quarkus?
Yes

**Comment by sciack** [comment]
I tried and can be configured, but I found something strange (sorry I cannot share the logs due to security restriction), looks like the SSL configuration is unable to find the right algorithm for the client certificate but when I create the http client works correctly. I've 2 UT that tests the connection in the two configuration, running in the same JVM.

Do you know if Quarkus ro Microprofile use a specific configuration of SSL or is the standard of the JVM.

**Comment by artkonr** [comment]
Hey team, 

Just wanted to add my voice to this. I really miss the ability to tailor the connection pooling.

For my use case I need both small connection pools (1-5 connections) and pools which can create more connections but evict them automatically after an hour or two.

Based on what I see in the logs, default size of the connection pool in REST client is 50, which is way too much. I have ~10 separate services, all different, so I cannot use the same client for all of them. Thus, I end up with some 500 active connections and my environment is very tight in terms of memory.

**Comment by michalszynkiewicz** [comment]
> I tried and can be configured, but I found something strange (sorry I cannot share the logs due to security restriction), looks like the SSL configuration is unable to find the right algorithm for the client certificate but when I create the http client works correctly. I've 2 UT that tests the connection in the two configuration, running in the same JVM.
> 
> Do you know if Quarkus ro Microprofile use a specific configuration of SSL or is the standard of the JVM.

Standard JVM settings should be picked up (if you run Quarkus on JVM). There are also SSL settings as described in https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#ssl

**Comment by michalszynkiewicz** [comment]
@artkonr do you use `quarkus-rest-client` or `quarkus-rest-client-reactive`?

**Comment by artkonr** [comment]
@michalszynkiewicz I'm using non-reactive at the moment and I did not really plan to switch for now. Do I benefit somehow from using the reactive client?

**Comment by geoand** [comment]
> @michalszynkiewicz I'm using non-reactive at the moment and I did not really plan to switch for now. Do I benefit somehow from using the reactive client, I mean memory-wise?

Yes you would. 1) it does not drag in additional dependencies (as the Vert.x dependencies are already present), 2) it uses non-blocking IO so there is no new thread pool that would cause additional memory usage and 3) the implementation benefits from Quarkus' build time optimizations

**Comment by artkonr** [comment]
Sounds good, thanks. 

However, I'm still curious if there is some way to add connection pooling settings to the REST client. I won't, of course, claim I have the full picture, but it seems to me that it's just a bunch of new properties to add. Is there something more about it that I don't see? Off the top of my head, there probably could be implementations of REST client not necessarily based on apache client and thus offering limited conn management functionality. Is this the case?

I think the defaults are fairly reasonable for *most* of the apps out there, it's just that the client code should be able to go about settings in its own way, and I think it quite neatly fits into the overall approach to configs in Quarkus, the way I've come to understand it.

**Comment by geoand** [comment]
The reactive rest client does do connection pooling because it relies on the Vertx Http Client which handles all those details.
Note that you are **not** forced to use reactive programming when using the new reactive rest client - it works perfectly well with blocking code as well.

**Comment by artkonr** [comment]
Awesome, thank you. I don't really follow, though: if I plug in `quarkus-rest-client-reactive`, can I tailor connection pooling for the Vert.x client? It seems like there are some configs out there, such as `maxPoolSize` or suchlike, but I don't see how I can bridge the gap between the declarative annotation+`application.properties` config and the underlying Vert.x backend. From the looks of it, these configs are just not there in the MP REST client spec.

**Comment by geoand** [comment]
Currently you can't tinker with those, but we can certainly expose something like that. Mind opening a new issue asking for that feature?

**Comment by artkonr** [comment]
Not at all, I'll do that today, thank you!

**Comment by geoand** [comment]
Thanks 👍

**Comment by geoand** [comment]
Closing this as our focus in on the `quarkus-rest-client-reactive` (which uses Vert.x under the hood)
