### ISSUE TITLE
Exceptions thrown from ClientRequestFilter are mapped differently in native image

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#17002]
## Describe the bug
If MP RestClient `ClientRequestFilter` throws `RuntimeException` then it will be mapped differently in JVM and native modes.
In JVM `500` and `that RuntimeException's error message` is reported, in native image `500` + something like `Error id - <generated unique number>` 

Note it is different from the case where a downstream service reports an exception whose Response is blocked by default.

### Expected behavior
The error message is also included in native image

## To Reproduce

register custom `ClientRequestFilter` and have it throwing some RuntimeException in its `filter` method

**Comment by geoand** [comment]
Are you sure about this?

I tried it and the handling of the exceptions is the same. What was different was the handling in dev-mode, but that's to be expected

**Comment by sberyozkin** [comment]
@geoand Thanks for checking it so fast :-)

Have a look at this [test endpoint](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-token-propagation/src/main/java/io/quarkus/it/keycloak/FrontendResource.java#L35) please. I just merged that PR if you update that method just to `return accessTokenPropagationService.getUserName();` and do
```
mvn clean install -Dstart-containers -Dtest-containers
``` 
then it will pass but fail if you do
```
mvn clean install -Dstart-containers -Dtest-containers -Dnative
```

then you'll see this failure. The exception is propagating from [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-token-propagation/runtime/src/main/java/io/quarkus/oidc/token/propagation/AccessTokenRequestFilter.java#L53)

**Comment by geoand** [comment]
Got it thanks, let me give it a try

**Comment by geoand** [comment]
So basically the message is different?

**Comment by sberyozkin** [comment]
Yeah :-)

**Comment by sberyozkin** [comment]
Not a major issue - as throwing the exceptions from `ClientRequestFilter` is rare

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
I think something similar was fixed recently, so I'll close this. 
If it's not fixed, feel free to reopen.
