### ISSUE TITLE
Support SASL/Bearer for the Kafka Bindings

### ISSUE THREAD

**Issue by wtrocki** [quarkusio/quarkus#17005]
## Describe the bug

When service binding provides type as SASL/OAUTH Bearer Kafka connection doesn't work. 
This is due to the missing authorization server URL provided by binding. 

This is up to discussion if that type should be supported. 
I'm logging issue in quarkus and RHOAS operator

**Comment by cescoffier** [comment]
@geoand  - Was that property defined? I don't believe it was providing it. Without a clear specification (name, format) of the property coming from the operator, there is not much we can do.

**Comment by geoand** [comment]
Here is what we currently do: https://github.com/quarkusio/quarkus/blob/fadc4779e8d88b6430316c52c1bd0db9d42d2dbb/extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaBindingConverter.java#L15-L50

If someone tells me what the mapping is supposed to look like, then I can easily add support for this case.

**Comment by wtrocki** [comment]
I will work on having those cases documented and link it here or even make changes directly in PR

**Comment by cescoffier** [comment]
@wtrocki any update on this?

**Comment by wtrocki** [comment]
We haven't done any work on this yet. The reason for it is that we needed to choose one protocol and SASL/Plain was obvious choice :)

**Comment by cescoffier** [comment]
Any update @wtrocki ?

@ozangunalp do you know if it uses plain or oauth when we use the SBO?

**Comment by ozangunalp** [comment]
`saslMechanism` property we are getting is `PLAIN`. In Quarkus the service binding config converter also handles the Scram but not the oauth. The binding secret contains the client id and client secret (same as the username and password) coming from the service account but not the authorization server for oauth.

**Comment by cescoffier** [comment]
Closing.
Please re-open when the service binding operator produces the OAUTH configuration
