### ISSUE TITLE
Vertx-web return Vertx Future support.

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#17037]
## Description

Compared to mutiny, I prefer Vertx's Promise and Future. Mutiny takes more time to learn and also affects code readability.

```java
    @Route(path = "/", methods = HttpMethod.POST,
        produces = "application/json",
        consumes = "application/json")
    public Future<String> promise(@Body JsonObject body) {
        Promise<String> promise = Promise.promise();
        //do somethings.
        return promise.future();
    }
```

The above code does not produce the expected result, it will respond:

```json
{
    "complete": true
}
```

*aomsweet*
*Best Regards*

**Comment by cescoffier** [comment]
Instead of Future, we should add support for CompletionStage. Then, you can create the CompletionStage from the Future object (.toCompletionStage()).

**Comment by aomsweet** [comment]
Hi. @cescoffier  @mkouba 

Thanks.  ☕

But i have a question. Why not directly support Vertx's `Future`? `Future` is more commonly used than `CompletionStage` in `Vertx`.

**Comment by cescoffier** [comment]
In Vert.x, yes, but it's an unknown type for the rest of the Java world and may collide with the Java Future type (which is blocking). CompletionStage is much more common in the Java world. Also, Quarkus chose Mutiny as main model.

Note that if you want direct Vert.x code, just inject the Router and register your routes. See https://quarkus.io/blog/magic-control/ fro details.

**Comment by aomsweet** [comment]
@cescoffier  Got it. Thank you. 😊

**Comment by mkouba** [comment]
> Note that if you want direct Vert.x code, just inject the Router and register your routes. See https://quarkus.io/blog/magic-control/ fro details.

Oh, I completely missed this blogpost. I like the _"But magic is not inherently bad..."_ paragraph... ;-)
