### ISSUE TITLE
Property not expanding when using 2 BUILD_TIME Configs

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#1703]
While working on this #1300 I added a configuration named `KubernetesConfig` and in it I wanted to add `ConfigItem` like so:

```
@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
public class KubernetesConfig {

    @ConfigItem
    public boolean deploy = false;

    @ConfigItem(defaultValue = "${quarkus.application.group}")
    public String group;

   .....
}

```

with the expectation that `group` would be expanded to value of `quarkus.application.name` if not value for `quarkus.kubernetes.group` was supplied.
Unfortunately I am just seeing `${quarkus.application.group}` when using the config item

**Comment by dmlloyd** [comment]
Note to self:

- [ ] Check to make sure expansion is enabled (duh)
- [ ] Possibly change default expansion such that the defaults are part of a separate config source instead of expanded in line, so that recursive default expansion works
