### ISSUE TITLE
Documentation for @ConsumeEvent could mention that exceptions are not logged

### ISSUE THREAD

**Issue by samodadela** [quarkusio/quarkus#17040]
## Description
Throwing any exception within a @ConsumeEvent results in the exception not being logged at all. 

Example:
```
...
    bus.send(EVENT_ADDR, "hey");
    // bye-bye
...

@ConsumeEvent(EVENT_ADDR) 
public void eventConsumer(String event) {
    throw new AnyException("no one hears me"); 
}
```
According to @mkouba this is intentional as explained here: https://github.com/quarkusio/quarkus/issues/11525

Since my case is a fire-and-forget I found no other way to log the exception except catching it myself in eventConsumer().

## Implementation ideas
Could you please mention this peculiarity in the javadoc for @ConsumeEvent?
Not event https://quarkus.io/guides/reactive-messaging mentions such behaviour.

**Comment by mkouba** [comment]
Well, `@ConsumeEvent` is not related to CDI async events in any way, and thus https://github.com/quarkusio/quarkus/issues/11525 is completely unrelated. It's merely a wrapper around the `io.vertx.core.eventbus.EventBus.consumer()`. That said, if a method annotated with `@ConsumeEvent` throws an exception then:
* if a reply handler is set the failure is propagated back to the sender via an `ReplyException` with code `ConsumeEvent.FAILURE_CODE` and message `Exception.toString()`.
* if no reply handler is set then the exception is rethrown (and wrapped in a `RuntimeException` if necessary) and can be handled by the `io.vertx.core.Vertx.exceptionHandler(Handler<Throwable>)`

> Could you please mention this peculiarity in the javadoc for @ConsumeEvent?
> Not event https://quarkus.io/guides/reactive-messaging mentions such behaviour.

I'm +1 for both, i.e. adding a section about failure handling into the guide and javadoc.

**Comment by samodadela** [comment]
@mkouba Thanks for the explanation. If you don't mind... could you please provide minimal examples for both of the cases above?

**Comment by mkouba** [comment]
@samodadela You can try to take a look at our test: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/deployment/src/test/java/io/quarkus/vertx/deployment/MessageConsumerFailureTest.java
