### ISSUE TITLE
Move "bootstrap-maven-plugin" to separate repository

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#1706]
Having had experience with this from Thorntail, there's not really a good reason to have this inside the main repo, and if anything causes issues.

I'd recommend we move it out to it's own repository in the GH org and have it's own release cycle. Possibly just with a single incrementing number 1, 2, 3, etc.

It would also be good if this happened before 0.13.0 is released

**Comment by gsmet** [comment]
It's an independent project now but still released as part of the main repo.

I'm closing this one. Changing this will be a coordinated effort we will decide later (and create appropriate issues).
