### ISSUE TITLE
gRPC Dev UI support

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#17064]
It can be helpful to provide some basic Dev UI functionality for the gRPC extension, e.g.
* List all ``@GrpcService``s
* Provide some basic way to test the services

We could either make use of an existing tool (such as [grpcurl](https://github.com/fullstorydev/grpcurl)), probably started via DevServices, or try to implement some basic UI, e.g. reuse the generated stubs and [`com.google.protobuf.util.JsonFormat`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.html).

**Comment by mkouba** [comment]
The initial support was added in https://github.com/quarkusio/quarkus/pull/17381.

**Comment by mkouba** [comment]
@michalszynkiewicz I think that we can close this one. WDYT?

**Comment by cescoffier** [comment]
I would say so, improvements can be added later.

**Comment by mkouba** [comment]
Addressed in https://github.com/quarkusio/quarkus/pull/17381, https://github.com/quarkusio/quarkus/pull/17442 and follow-up bugfix PRs.
