### ISSUE TITLE
javax validation with entities in external library

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#17072]
## Describe the bug

Validating objects included via a dependency does not work in two cases:

1. If the project does not have any `javax.validation.constraints` annotation, no validation is performed even on external entities. Need to mark/force something on the library?
2. After solving 1, validation constraints on nested external entities is not performed.

### Expected behavior

Entities are validated even if imported from an external dependency.

### Actual behavior

Entities imported from an external dependency are not validated.

## To Reproduce

Clone `git@github.com:antoniomacri/quarkus-validation-reproducer.git`

1. `cd quarkus-validation-lib`
2. `../mvnw clean install`
3. `cd ../quarkus-validation-app`
4. `../mvnw quarkus:dev`
5. `curl -X POST --location "http://localhost:8080/validating" -H "Content-Type: application/json" -H "Accept: application/json" -d "{}"` -> "No validator could be found"
6. Uncomment `@NotNull` in class `InternalDto` and rerun the previous curl, it now works: the constraint is validated and the appropriate error is returned
7. Now run `curl -X POST --location "http://localhost:8080/validating" -H "Content-Type: application/json" -H "Accept: application/json" -d '{"innerDto":{}}'` -> 204, but should raise a validation exception since innerDto.id is null.
8. If both the DTOs are copied in the project validation works.

**Comment by stuartwdouglas** [comment]
Add this to your library (or include a META-INF/beans.xml):

```
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>1.0.8</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

See:

**Comment by antoniomacri** [comment]
Sorry, my mistake, I did try it on the real project/library but there was a classifier filtering the beans.xml.

I'll close, thanks.
