### ISSUE TITLE
io.quarkus.bootstrap.BootstrapException if pom exists in parent directory

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#1708]
The method:

io.quarkus.bootstrap.resolver.maven.workspace.LocalProject#locateRootProjectDir

try to locate the parent pom without looking at the content.

If you have a "dirty" pom in a directory which is parent of your pom.xml but with any relationship (no parent in Quarkus project, no module in parent pom) that pom.xml is used for the build and the build of course will be broken.

**Comment by gsmet** [comment]
@aloubyansky I just noticed this one. I saw several fixes that could be related, do you think it's fixed?

**Comment by aloubyansky** [comment]
Yes, this should be fixed now. Please, re-open in case there is still any issue with the workspace discovery. Thanks again @masini !
