### ISSUE TITLE
Enable fault-tolerance tests on JDK 16+

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#17080]
Update to a smallrye-fault-tolerance release that incorporates https://github.com/smallrye/smallrye-fault-tolerance/pull/409 (probably 5.0.1?) and revert this commit: https://github.com/quarkusio/quarkus/pull/17053/commits/d9290492cd2a30f04e8216725d03930fa7fb9468

Relates to https://github.com/quarkusio/quarkus/issues/16195#issuecomment-832585114

- set JDK 16 (e.g. via `sdk`)
- if Kotlin 1.5 is not yet integrated: add `--add-opens java.base/java.util=ALL-UNNAMED` to `MAVEN_OPTS`
- `mvn -Dquickly -T1C`
- `mvn clean verify -f tcks/microprofile-fault-tolerance` (should not fail)
- `mvn clean verify -f tcks/microprofile-fault-tolerance -P'!jdk16-workarounds'` (should fail)
- same with `integration-tests/main` (`RestClientTestCase#testFaultTolerance`)

**Comment by Ladicek** [comment]
Thanks for filing this, I'll take care of it. Hopefully this week.
