### ISSUE TITLE
quarkus-resteasy-reactive slower than quarkus-resteasy when returning Multi

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#17094]
## Describe the bug
When a JAX-RS endpoint returns `Multi` with the `quarkus-resteasy-reactive` extension, the response time is unstable and sometimes much higher than with `quarkus-resteasy`.

### Expected behavior
Stable and reasonable response time with `quarkus-resteasy-reactive`.

## To Reproduce

https://github.com/gwenneg/quarkus-resteasy-reactive-response-time

This repo contains two subfolders which contain the exact same code. The only different file is `pom.xml`:
- the `resteasy` subfolder depends on `quarkus-resteasy` and `quarkus-resteasy-mutiny`
- the `resteasy-reactive` subfolder depends on `quarkus-resteasy-reactive`

1. `cd resteasy-reactive`
2. `./mvnw clean quarkus:dev`
3. Go to http://localhost:8080/test/uni and look at the response time, it should be good
4. Repeat a few times, the response time should be stable
5. Go to http://localhost:8080/test/multi and look at the response time, it may or may not be good
6. Repeat a few times, the response time should be unstable and sometimes really bad

If you follow the same steps with the `resteasy` subfolder, the response time should always be good and stable with both `Uni` and `Multi`.

### Output of `java -version`

```
$ java -version
openjdk version "11.0.9.1" 2020-11-04
```

### Quarkus version or git rev

`1.13.3.Final`

**Comment by geoand** [comment]
Thanks for reporting!

@FroMage as you know more than anyone about returning Multi in both cases, mind taking a look?

**Comment by gwenneg** [comment]
This is probably related to the problem we discussed a few days ago.

**Comment by famod** [comment]
FWIW, some quick'n'dirty `hey` results from my machine (Ubuntu 20 WSL2):

**reactive:**
```
Summary:
  Total:        4.3978 secs
  Slowest:      0.0534 secs
  Fastest:      0.0012 secs
  Average:      0.0201 secs
  Requests/sec: 2273.8477


Response time histogram:
  0.001 [1]     |
  0.006 [745]   |■■■■■
  0.012 [319]   |■■
  0.017 [1152]  |■■■■■■■■
  0.022 [5735]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.027 [892]   |■■■■■■
  0.033 [598]   |■■■■
  0.038 [110]   |■
  0.043 [367]   |■■■
  0.048 [78]    |■
  0.053 [3]     |


Latency distribution:
  10% in 0.0095 secs
  25% in 0.0177 secs
  50% in 0.0205 secs
  75% in 0.0216 secs
  90% in 0.0277 secs
  95% in 0.0345 secs
  99% in 0.0427 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0000 secs, 0.0012 secs, 0.0534 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0026 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0008 secs
  resp wait:    0.0200 secs, 0.0012 secs, 0.0507 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0003 secs

Status code distribution:
  [415] 10000 responses
```
**non-reactive:**
```
Summary:
  Total:        4.9421 secs
  Slowest:      0.0491 secs
  Fastest:      0.0020 secs
  Average:      0.0227 secs
  Requests/sec: 2023.4156


Response time histogram:
  0.002 [1]     |
  0.007 [788]   |■■■■
  0.011 [212]   |■
  0.016 [45]    |
  0.021 [120]   |■
  0.026 [7049]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.030 [1021]  |■■■■■■
  0.035 [170]   |■
  0.040 [1]     |
  0.044 [288]   |■■
  0.049 [305]   |■■


Latency distribution:
  10% in 0.0107 secs
  25% in 0.0219 secs
  50% in 0.0222 secs
  75% in 0.0230 secs
  90% in 0.0298 secs
  95% in 0.0439 secs
  99% in 0.0453 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0000 secs, 0.0020 secs, 0.0491 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0015 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0013 secs
  resp wait:    0.0227 secs, 0.0020 secs, 0.0491 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0004 secs

Status code distribution:
  [415] 10000 responses
```

Results can vary _a lot_ in different runs (is't only a basic load test after all).

PS: `hey -n 10000 http://localhost:8080/test/uni`

**Comment by geoand** [comment]
Thanks @famod!

**Comment by famod** [comment]
Wait a scond...that response code doesn't look right and those are just the uni-results.

**Comment by geoand** [comment]
Also, I would like to know what your use case is for returning `Multi` @gwenneg

**Comment by famod** [comment]
Ok, I was missing `-T application/json`. I updated the uni results above.

Multi:

**reactive:**
```
Summary:
  Total:        5.1124 secs
  Slowest:      0.2764 secs
  Fastest:      0.0009 secs
  Average:      0.0241 secs
  Requests/sec: 1956.0146


Response time histogram:
  0.001 [1]     |
  0.028 [8015]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.056 [744]   |■■■■
  0.084 [413]   |■■
  0.111 [295]   |■
  0.139 [196]   |■
  0.166 [123]   |■
  0.194 [86]    |
  0.221 [62]    |
  0.249 [37]    |
  0.276 [28]    |


Latency distribution:
  10% in 0.0055 secs
  25% in 0.0066 secs
  50% in 0.0077 secs
  75% in 0.0173 secs
  90% in 0.0723 secs
  95% in 0.1155 secs
  99% in 0.2075 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0001 secs, 0.0009 secs, 0.2764 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0020 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0018 secs
  resp wait:    0.0237 secs, 0.0007 secs, 0.2761 secs
  resp read:    0.0002 secs, 0.0000 secs, 0.0027 secs

Status code distribution:
  [200] 10000 responses
```

**non-reactive:**
```
Summary:
  Total:        5.0915 secs
  Slowest:      0.0674 secs
  Fastest:      0.0015 secs
  Average:      0.0233 secs
  Requests/sec: 1964.0689

  Total data:   70000 bytes
  Size/request: 7 bytes

Response time histogram:
  0.002 [1]     |
  0.008 [951]   |■■■■■
  0.015 [79]    |
  0.021 [559]   |■■■
  0.028 [7266]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.034 [542]   |■■■
  0.041 [23]    |
  0.048 [240]   |■
  0.054 [59]    |
  0.061 [38]    |
  0.067 [242]   |■


Latency distribution:
  10% in 0.0088 secs
  25% in 0.0227 secs
  50% in 0.0231 secs
  75% in 0.0238 secs
  90% in 0.0305 secs
  95% in 0.0460 secs
  99% in 0.0623 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0000 secs, 0.0015 secs, 0.0674 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0031 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0010 secs
  resp wait:    0.0232 secs, 0.0015 secs, 0.0674 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0007 secs

Status code distribution:
  [200] 10000 responses
```

**Comment by gwenneg** [comment]
> Also, I would like to know what your use case is for returning `Multi` @gwenneg

`Multi` was returned for a wrong reason. I'm writing "was" because I noticed the response time difference after cleaning some old code (I replaced `Multi` with `Uni<List>` in a few API endpoints).

**Comment by geoand** [comment]
The difference in response time is probably explained by the different way that `Multi` is handled in RESTEasy Reactive vs RESTEasy Classic.

**Comment by FroMage** [comment]
Should I really take a look? The response times mentioned here look very similar, and the RPS too…

**Comment by geoand** [comment]
I talked to Gwenneg and I think we are fine for now. I'll let you know if we really need your expert eyes on it after all :)

**Comment by geoand** [comment]
I'm going to close this as it does not seem to be an issue. If it is an issue, please reopen and/or comment with updated information
