### ISSUE TITLE
Enable xstream based tests on JDK 16+

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#17091]
Update to a [xstream](https://github.com/x-stream/xstream) version that fixes the illegal access problems and revert https://github.com/quarkusio/quarkus/pull/17053/commits/7d4bec1d92c5e99f77ef6ddb1a584f8277ca02c0 (⚠️ `surefire.argLine.additional` should stay!).

Relates to #16195.

- set JDK 16 (e.g. via `sdk`)
- if Kotlin 1.5 is not yet integrated: add `--add-opens java.base/java.util=ALL-UNNAMED` to `MAVEN_OPTS`
- `mvn -Dquickly -T1C`
- `mvn clean verify -f integration-tests/main` (should not fail)
- `mvn clean verify -f integration-tests/main -P'!jdk16-workarounds'` (should fail)

**Comment by famod** [comment]
I'll have a look at whether this still happens with xstream `master` (which means 1.5 will fix it).

**Comment by famod** [comment]
This unfortunately still fails with xstream 1.5.0-SNAPSHOT: https://github.com/x-stream/xstream/issues/253

/cc @geoand

**Comment by geoand** [comment]
😢

**Comment by famod** [comment]
Ok, I found some workarounds: https://github.com/x-stream/xstream/issues/253#issuecomment-835877790

Will send a PR to re-enable the tests on Java 16. But this won't help users of Quarkus, I'm afraid.

**Comment by famod** [comment]
Ok, that's what I was suspecting. Thanks for confiming!
