### ISSUE TITLE
Enable TCKS rest-client tests on JDK 16+

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#17093]
Analyze problem (illegal access w.r.t. "opens java.lang.invoke" and also plain assertion errors), probably update some component and revert https://github.com/quarkusio/quarkus/pull/17053/commits/6f627403d1a950a91407d9eaf9b56a802974d122.

Relates to #16195.

- set JDK 16 (e.g. via `sdk`)
- `mvn -Dquickly -T1C`
- `mvn clean verify -f tcks/microprofile-rest-client` (should not fail)
- `mvn clean verify -f tcks/microprofile-rest-client -P'!jdk16-workarounds'` (should fail)

**Comment by famod** [comment]
Will most likely require an upgrade to RESTEasy 4.7.0: https://issues.redhat.com/browse/RESTEASY-2905

**Comment by famod** [comment]
Quarkus issue for the update: #18622

**Comment by famod** [comment]
`Timeout*Test`s still fail, see https://github.com/quarkusio/quarkus/pull/18710#issuecomment-880793441

**Comment by gsmet** [comment]
@michalszynkiewicz any chance you could have a look at this one when you have some time? It would be nice to have everything working with JDK 16+

**Comment by michalszynkiewicz** [comment]
If nothing more urgent pops up, I'll take a look at it on Monday

**Comment by jaikiran** [comment]
Hello @michalszynkiewicz, @gsmet, this PR https://github.com/quarkusio/quarkus/pull/19559 should fix the Timeout* test case failures in Java 16+.

**Comment by michalszynkiewicz** [comment]
thanks for handling this @jaikiran
