### ISSUE TITLE
quarkus.test.profile not considered since quarkus 2.0.0.Alpha2

### ISSUE THREAD

**Issue by zbendhiba** [quarkusio/quarkus#17103]
## Describe the bug
When running a test a quarkus.test.profile, it gets the default properties on version quarkus 2.0.0.Alpha2, instead of the properties for the profile that I've set.

### Expected behavior
It should gets the properties for the profile.

## To Reproduce
I created a project to reproduce the problem. The [URL of the project](https://github.com/zbendhiba/test).
The profile is set in  [MyTestResource.java](https://github.com/zbendhiba/test/blob/main/src/test/java/org/acme/MyTestResource.java) 
The test failing in  [GreetingResourceTest.java)](https://github.com/zbendhiba/test/blob/main/src/test/java/org/acme/GreetingResourceTest.java)

**Comment by geoand** [comment]
To be honest, I am surprised this ever worked. 

Setting the test profile needs to happen very very early, so it's best done using a system property when launching the maven build or as part of the surefire configuration.
