### ISSUE TITLE
Closing the application is that the vert.x redis client will not close

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#17104]
## Describe the bug

I debugged my application and found that close() would not be executed.

io.quarkus.redis.client.runtime.RedisAPIProducer.java

```java
    @PreDestroy
    public void close() {
        for (RedisAPIContainer container : REDIS_APIS.values()) {
            container.close();
        }

        REDIS_APIS.clear();
    }
```

## To Reproduce

I can provide if needed.

### Configuration
```properties
# Add your application.properties here, if applicable.

quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.client-type=standalone
quarkus.redis.max-pool-size=12
quarkus.redis.max-pool-waiting=64

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`

Windows 10 64bit

### Output of `java -version`

JDK: 1.8

### GraalVM version (if different from Java)

GraalVM: 21.1.0

### Quarkus version or git rev

Quarkus: 1.13.3.Final

## Additional context
(Add any other context about the problem here.)

**Comment by machi1990** [comment]
> ## Describe the bug
> I debugged my application and found that close() would not be executed.

@aomsweet thanks for opening the issue. Why do you think that close will never be executed? 
 
> io.quarkus.redis.client.runtime.RedisAPIProducer.java
> 
> ```java
>     @PreDestroy
>     public void close() {
>         for (RedisAPIContainer container : REDIS_APIS.values()) {
>             container.close();
>         }
> 
>         REDIS_APIS.clear();
>     }
> ```

**Comment by aomsweet** [comment]
hi @machi1990 

thanks for your reply.

It was found through the Debugger that close was not called.

**Comment by aomsweet** [comment]
@machi1990 
It seems that @PreDestroy does not work in synthetic beans.

**Comment by aomsweet** [comment]
@machi1990 

It seems that `@PreDestroy` does not work for beans created with `AdditionalBeanBuildItem`.

**Comment by machi1990** [comment]
> @machi1990
> It seems that @PreDestroy does not work in synthetic beans.

But `io.quarkus.redis.client.runtime.RedisAPIProducer.java` is not a synthetic bean. 

Can you provide a reproducer?

**Comment by aomsweet** [comment]
@machi1990 

This is reproducer. Please check it. [https://github.com/aomsweet/quarkus-redis-example](https://github.com/aomsweet/quarkus-redis-example)

The way I tested is to set breakpoints in the following two methods, and then start the application in debug mode. Wait for the program to start and then kill the application process.

Although this method is clumsy, I think it is effective.

io.spinach.DestroyAbleBean.java

```java
    @PreDestroy
    public void destroy() {
        System.out.println("DestroyAbleBean destroying...");
    }
```

io.quarkus.redis.client.runtime.RedisAPIProducer.java

```java
    @PreDestroy
    public void close() {
        for (RedisAPIContainer container : REDIS_APIS.values()) {
            container.close();
        }

        REDIS_APIS.clear();
    }
```

**Comment by mkouba** [comment]
> How can synthetic beans be destroyed when executing `kill pid`?

I think that shutdown hooks are only executed in case of normal termination, i.e. quarkus itself will not be shut down correctly when you do `kill pid`, and thus neither class-based nor synthetic beans are destroyed correctly.

**Comment by aomsweet** [comment]
@mkouba @machi1990 

You are right, I have always relied on intellij idea's debug mode test. This may be a bug in the IDE or it may be that the dynamic bytecode generated by quarkus causes the breakpoint to be invalid. When I package the application and run it through `jar -jar` everything works fine. 

I am very sorry.

thanks.
