### ISSUE TITLE
Keycloak absolute URL for quarkus.oidc.authorization-path property

### ISSUE THREAD

**Issue by Jojal** [quarkusio/quarkus#17130]
## Description

As a developer running keycloak in a kubernetes pod and my Quarkus application in a second pod, it would be great to have the possibility to specify the quarkus.oidc.authorization-path in an absolute way in order to override the quarkus.oidc.auth-server-url which is an internal kubernetes URL.
This case should happen only for the redirection to display the login page to the user.

## Justification

Working with kubernetes with this configuration :
```
quarkus.oidc.auth-server-url=http://keycloak-http.authentication.svc.cluster.local/auth/realms/quarkus
````
We can see the url is pointing to **authentication.svc.cluster.local** which is the URL of the Keycloak POD only accessible from the Quarkus Application POD. (i mean not accessible from outside)
Unfortunatly, when if we set the quarkus.oidc.application-type to **web-app**, we need a redirection to display the login page to the user. With this basic configuration, the redirection will happen to a kubernetes url **authentication.svc.cluster.local** which is not accessible from the user browser. 

That way, if we could just put an absolute URL in the quarkus.oidc.authorization-path property, the redirection would happened correctly.

**Comment by sberyozkin** [comment]
As confirmed by @Jojal `KEYCLOAK_FRONTEND_URL` works do I'll close this issue with a small PR adding a note about `KEYCLOAK_FRONTEND_URL`
