### ISSUE TITLE
do after transaction commit

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#17146]
## Description

Thread 1 running inside a transaction creates object A and needs to launch asynchronous action (through messaging service for example) which uses object A. Doing this directly creates a race between a transaction commit in thread 1 when object A will be visible to other transactions and asynchronous action which reads object A by id in another transaction
In Spring there is
```
TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){
           void afterCommit(){
                //do what you want to do after commit
           }
})
```
In quarkus AFAIK there is no such functionality, so you have no option to delay asynchronous code until transaction is commited. It forces develper write some hacks like splitting code in multiple methods, resulting in messy code.

**Comment by stuartwdouglas** [comment]
You can just:

@Inject
TransactionSynchronizationManager tsr;

or

@Inject
TransactionManager tm;

And use this to register a sync. 

Can can also use CDI transactional observers. We really should document this better though.

**Comment by Shohou** [comment]
IDE doesn't find TransactionSynchronizationManager for me and googling `TransactionSynchronizationManager quarkus` shows no relevant info

```
@Inject
TransactionManager tm;
tm.getTransaction().registerSynchronization(Synchronization)
```
seems to be what I need
Thank you!

**Comment by stuartwdouglas** [comment]
Sorry, I meant javax.transaction.TransactionSynchronizationRegistry
