### ISSUE TITLE
Arc silently fails if there is an exception in a @Produces method

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1714]
If a `@Produces` method call fails with an exception, that exception is swallowed and the application silently fails.

If there is an exception thrown by `createInstanceHandle()`  in this lambda :

https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/AbstractSharedContext.java#L33

The exception is swallowed and not reported.

In my case, a call to `bean.create()` on this line;

https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/AbstractSharedContext.java#L86

was failing with an 'java.lang.IllegalStateException' but the exception, nor the exception message is logged

**Comment by manovotn** [comment]
@johnaohara not sure what situation you mean?
I have put together a [simple test](https://github.com/manovotn/quarkus/tree/issue1714) that has producers which throw ISE. The exception proliferates to the surface as expected in my case.

**Comment by johnaohara** [comment]
This exception is occurring for the quarkus-vertx rest-http-crud-demo. I will create a reproducer for the issue

**Comment by mkouba** [comment]
Thanks John, a reproducer would be really helpful.

**Comment by johnaohara** [comment]
@manovotn Have spent some time digging into this, the exception is propagating back from arc correctly, looks like an issue in vertx-web. Still investigating

**Comment by johnaohara** [comment]
@mkouba see above, I think the issue is in vertx-web

**Comment by johnaohara** [comment]
@mkouba  @manovotn  This isn't a bug, I had a vertx router that was handling the error response, but was not reporting the exception message. My mistake
