### ISSUE TITLE
Synthetic Bean will not be destroyed

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#17156]
## Describe the bug
```java
private SyntheticBeanBuildItem createWebClientSyntheticBean(WebClientRecorder recorder, String clientName) {
        SyntheticBeanBuildItem.ExtendedBeanConfigurator configurator = SyntheticBeanBuildItem
            .configure(WebClient.class)
            .destroyer(WebClientDestroyer.class)
            .scope(ApplicationScoped.class)
            .supplier(recorder.webClientSupplier(clientName))
            .setRuntimeInit();

        return applyCommonBeanConfig(clientName, configurator);
    }

    private SyntheticBeanBuildItem applyCommonBeanConfig(String clientName,
                                                         SyntheticBeanBuildItem.ExtendedBeanConfigurator configurator) {
        configurator.unremovable();
        if (RootWebClientConfiguration.isDefault(clientName)) {
            configurator.addQualifier(Default.class);
        } else {
            configurator.addQualifier().annotation(WEB_CLIENT_ANNOTATION).addValue("value", clientName).done();
        }
        return configurator.done();
    }
```

io.spinach.quarkus.vertx.web.client.deployment.WebClientDestroyer.java

```
public class WebClientDestroyer implements BeanDestroyer<WebClient> {

    @Override
    public void destroy(WebClient instance, CreationalContext<WebClient> creationalContext, Map<String, Object> params) {
        System.out.println("Closing web client......");
        instance.close();
    }
}
```

### Expected behavior
Console output `Closing web client......`

### Actual behavior
Console does not output `Closing web client......`

## To Reproduce
Can provide if needed.

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
os: Ubuntu 20.04

### Output of `java -version`
Java: 11

### GraalVM version (if different from Java)
GraalVM: 21.1.0

### Quarkus version or git rev
Quarkus: 1.13.3.Final

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by mkouba** [comment]
Isn't this related to https://github.com/quarkusio/quarkus/issues/17104? As I wrote [in this comment](https://github.com/quarkusio/quarkus/issues/17104#issuecomment-839493615), when you do `kill pid` no beans are destroyed correctly.

@aomsweet How do you close your app?

**Comment by aomsweet** [comment]
hi. @mkouba  @geoand 

Sorry, I did not introduce it clearly. The test environment is Windows wsl 2 Ubuntu 20.4. The method annotated by @PreDestroy is executed at the end of the process.

**Comment by manovotn** [comment]
We even have a very similar test that asserts this behavior, see https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/buildextension/beans/BeanRegistrarTest.java#L96-L103
The test uses singleton but that doesn't matter, application scoped works as well.

Since your bean is application scoped, are you using that bean at least once in your app (e.g. invoke any method on it) before you verify that it gets destroyed? If you don't, the bean never gets created in the first place.
But I am just guessing - we'd need a reproducer to see what's going on.

**Comment by aomsweet** [comment]
@mkouba @manovotn 

I have always relied on intellij idea's debug mode test. This may be a bug in the IDE or it may be that the dynamic bytecode generated by quarkus causes the breakpoint to be invalid. When I package the application and run it through `jar -jar` everything works fine. 

I am very sorry.

thanks.
