### ISSUE TITLE
Delay when hitting "r" to enable continuous testing

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17159]
## Describe the bug
There is significant delay when hitting "r" on this project
https://github.com/ia3andy/rock-rock-rock

### Expected behavior
The output should be modified instantly to yell that the action have been received and things are getting ready to run the tests (even if in the background processing is still happening)

### Actual behavior
It's frozen

## To Reproduce

Use https://github.com/ia3andy/rock-rock-rock and start in dev mode then hit "r".

### Quarkus version or git rev

2.0.0.Alpha2

**Comment by stuartwdouglas** [comment]
Fixed upstream
