### ISSUE TITLE
Console "failed" counter is wrong using continuous testing

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17160]
## Describe the bug
"Test run failed, 5 tests were run, 1 failed, 0 were skipped. Tests took 7544ms"

While 5 did fail.

### Expected behavior
Should show 5 failed

### Actual behavior
(Describe the actual behavior clearly and concisely.)

## To Reproduce

Use https://github.com/ia3andy/rock-rock-rock and start in dev mode then hit "r".

### Quarkus version or git rev

2.0.0.Alpha2

**Comment by stuartwdouglas** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/17155
