### ISSUE TITLE
Unable to compile due to the aws sdk classes

### ISSUE THREAD

**Issue by marcinczeczko** [quarkusio/quarkus#1716]
Hi,
I was trying to create a lambda function with `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent` & `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent` types for RequestHandler

However, during quarkusBuild task I'm getting the error
```
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
Consider adding them to the index either by creating a Jandex index for your dependency or via quarkus.index-dependency properties.

> Task :aws-lambda:quarkusBuild
building quarkus runner
io.quarkus.creator.AppCreatorException: Failed to build a runner jar
```

Do you know how to overcome that issue ?

**Comment by evanchooly** [comment]
It's curious you're seeing that error.  I'm actually wrapping up the next round of Amazon Lambda integration which uses that class and I'm not seeing it.  I should have the extension merged today or tomorrow if all goes well.  When that goes, can you try using a `master` build and seeing if you get the same error?

**Comment by marcinczeczko** [comment]
So coincidence :) Sure, I'll definitely check it. Thanks.

**Comment by marcinczeczko** [comment]
By the way, do you have plans to add more AWS SDK dependencies in the future ? Would be useful to get support for Dynamodb for instance.

**Comment by evanchooly** [comment]
Nothing is *planned* for Dynamodb, necessarily, but it's hard to say how that might change in the future.  As we build out the extensions that *we* support, we're mostly looking at what makes most of our users more productive.  The hope is that for the wide variety of things we simply can't do, that there'd be community support for such extensions.

**Comment by marcinczeczko** [comment]
@evanchooly thanks. I tried changes you mentioned and looks fine now. 
Regarding Dynamodb, I implemented extension for aws dynamodb sdk2, that includes async client that uses netty (and both async and blocking clients works fine on native image too). I did that on my fork, would you be interested in such contribution, so I could raise PR ?

**Comment by evanchooly** [comment]
I can't make any promises but a PR is probably a good idea.

**Comment by marcinczeczko** [comment]
@evanchooly See my PR #2050
