### ISSUE TITLE
PanacheBaseEntity fails with "This method is normally automatically overridden"

### ISSUE THREAD

**Issue by atomicmass** [quarkusio/quarkus#1717]
I have a class that extends `PanacheBaseEntity` and is annotated with `@Entity`. When I load the service with `mvn compile quarkus:dev` it works perfectly. 

However if I execute the jar file directly `java -jar target/myproject-runner.jar` I get 
```
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotated your entity with @Entity?
at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.implementationInjectionMissing(JpaOperations.java:329)
at io.quarkus.hibernate.orm.panache.PanacheEntityBase.find(PanacheEntityBase.java:155)
```
This happens as soon as I hit one of the `list()` methods.
I'm using version 0.12.0

**Comment by FroMage** [comment]
This appears to work for me. Can you give me some code to look at?

**Comment by FroMage** [comment]
I'm going to close this due to inactivity. Don't hesitate to reopen if you can reproduce.
