### ISSUE TITLE
NPE during live reload on 2.0.0.Alpha2

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17177]
## Describe the bug

It happened during a demo, I am not sure of how to reproduce:
![image](https://user-images.githubusercontent.com/2223984/118002199-b1aeb980-b347-11eb-8e5b-cb65b5e01266.png)

**Comment by ia3andy** [comment]
cc @stuartwdouglas

**Comment by gsmet** [comment]
AFAICS, it would be this line: https://github.com/quarkusio/quarkus/blob/2.0.0.Alpha2/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L703
