### ISSUE TITLE
Problems loading classpath resources within QuarkusTestResource classes

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#17175]
## Describe the bug
Testing camel-quarkus with Quarkus 2.0.0.Alpha2, I noticed a number of test failures that seem to be related to the loading of classpath resources.

The problems occur where we do some pre-test setup work within a `QuarkusTestResourceLifecycleManager` impl. If some third party lib attempts to load a resource from the classpath, it appears to be failing. 

For example, we use `org.apache.ftpserver` to set up a local FTP server and pass it a keystore to configure security. The loading of the keystore from the classpath fails. E.g the FTP library does:

```
getClass().getClassLoader().getResourceAsStream(storeFile.getPath())
```

Similarly, some tests that use testcontainers also fail where testcontainers tries to load a resource from the classpath.   

This was previously working fine in 2.0.0.Alpha1.

### Expected behavior
Classpath resource loading works successfully.

### Actual behavior
`null` is returned from `getResource` / `getResourceAsStream` etc. E.g in the case of the aforementioned FTP server example

## To Reproduce

1. Clone reproducer project https://github.com/jamesnetherton/quarkus-test-resource-demo.
2. Run tests to observe the failure. `mvn clean test`. Note the console message: 

```
Caused by: org.apache.ftpserver.FtpServerConfigurationException: Key store could not be loaded from server.jks
```

3. Rerun tests, forcing `2.0.0.Alpha1` and observe success. `mvn clean test -Dquarkus.platform.version=2.0.0.Alpha1`.

**Comment by stuartwdouglas** [comment]
This will work with `quarkus.test.flat-class-path=true`

The root cause here is a bug in https://github.com/gkopff/mina-ftpserver/blob/master/core/src/main/java/org/apache/ftpserver/ssl/SslConfigurationFactory.java#L297

It uses getClass().getClassLoader() rather than Thread.currentThread().getContextClassLoader().
