### ISSUE TITLE
Support gRPC micrometer metrics

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#17183]
## Description

Micrometer v1.7.0 can generate metrics for gRPC. See [Link](https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc)

It would be great if the gRPC extension could register the metrics automatically

**Comment by cescoffier** [comment]
Definitely something we can add. We just need to check where things need to be wired.

**Comment by mkouba** [comment]
It seems that there are client and server interceptors that accept an instance of `MeterRegistry`. So in theory, all we need to do is to instantiate the interceptors with the correct `MeterRegistry` and register them for each client/service. I can take a look later this week.

**Comment by cescoffier** [comment]
Sync with @ebullient. The interceptor may need to be added to the micrometer extension (maybe, maybe not, only Erin knows :-))

**Comment by ebullient** [comment]
I am not the only one, and I am happy for the help.

A few extensions use the core MetricsFactory build item to detect metrics (and micrometer) support: Mongo and Jaeger are probably better examples, Hibernate and agroal do something a little different. The kicker is to avoid anything that references (or imports) the micrometer api unless the extension is present (to ensure it remains an optional dependency). All of the examples above show that.
