### ISSUE TITLE
Quarkus [1.13.3.Final] Classloader issue - works in QuarkusTest and not in quarkusDev. (Can't find class)

### ISSUE THREAD

**Issue by rroopreddy** [quarkusio/quarkus#17197]
## Describe the bug

Quarkus [1.13.3.Final] Classloader issue - works in QuarkusTest and not in quarkusDev. 

It works in test mode and not in quarkusDev mode.  Seems like the System.getClassLoader() is different **@QuarkusTest** vs **gradle quarkusDev**. Class.forName(className) is returning null for a class (JksSslEngineFactory ) specified for SSL configuration.  Tried to attach `@ApplicationScoped` to `JksSslEngineFactory` and various other approaches without much luck. 

### Expected behavior
Class loader to work similarly in test and dev mode

### Actual behavior
Works in test mode and not in quarkusDev mode

## To Reproduce

1. Created a custom class for SSL cert loader defined in same module

    ```java
    public class JksSslEngineFactory extends     DefaultSslEngineFactory {
    
        public AwsSslEngineFactory(DriverContext     context) {
            super(context);
        }
        ....
    }
    ```

2. Configured Cassandra Java Driver to support SSL through `application.conf`

    ```
    datastax-java-driver {
        .....
      advanced.ssl-engine-factory {
        class = com.xx.JksSslEngineFactory
        hostname-validation = false
        truststore-path = "RootCA.jks"
        truststore-password = ${?    CASSANDRA_TRUSTSTORE_PASSWORD}
      }
    }
    ```
3. `QuarkusCqlSession` reference below triggers the configuration from above

   ```java
   public class CassandraDBService {
   	@Inject
   	public QuarkusCqlSession session;
       .....
   }
   ```

4. When I use the service in a **@QuarkusTest** where the class (com.xx.JksSslEngineFactory) is resolved everything works. Class name is resolved to `Class` in below file

   ```
   File where it fails: com.datastax.oss.driver.internal.core.util.Reflection.java
   clazz = Class.forName(className);
   ```

5. When I run **gradle quarkusDev** things where the class (com.xx.JksSslEngineFactory) returns null with errors

   ```
   Caused by: java.lang.IllegalArgumentException:    Can't find class com.xx.JksSslEngineFactory    (specified by advanced.ssl-engine-factory.class)
   at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:219)
   ```

### Output of `uname -a` or `ver`

Darwin rxd.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

1.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle --version
Gradle 7.0

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Can you attach a project that reproduces the issue please?

**Comment by rroopreddy** [comment]
Uploaded "test-project" with instruction in "README.md"
[test-project.zip](https://github.com/quarkusio/quarkus/files/6474141/test-project.zip)

**Comment by stuartwdouglas** [comment]
I think this is an issue with https://github.com/datastax/cassandra-quarkus

Basically it is not using the correct ClassLoader, instead of using the TCCL it appears to be using its own ClassLoader. I think the fix may be to add a getClassLoader method to `com.datastax.oss.quarkus.runtime.internal.context.QuarkusDriverContext` that always returns the TCCL, but I don't know enough about the extension to say for sure. Can you open an issue in their issue tracker?

**Comment by rroopreddy** [comment]
@stuartwdouglas I debugged a bit where the `com.datastax.oss.quarkus.runtime.internal.context.QuarkusDriverContext` is setting the class loader to `null`.  This forces `Class.forName(className)` to be called which implicitly uses `ClassLoader.getSystemClassLoader()`

Isn't the default Quarkus class loader supposed to include the dependent Jars for `Class.forName` to work properly

**Comment by stuartwdouglas** [comment]
It will work in production mode, not in dev mode. Classs.forName(String) is almost always the wrong one to use, you should use the TCCL instead.

This should be easy to fix in casandra-quarkus, it just needs to be changed to use the  TCCL.
