### ISSUE TITLE
Improve doc of quarkus:remote-dev

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1720]
https://github.com/quarkusio/quarkus/pull/1666/files#diff-08ed80fdba6156d04b65ff7da6eac102

This does not explain why it's useful: run your app in Kubernetes and having the backend services deployed and consumable. Can someone take a stab at it.

**Comment by gsmet** [comment]
@stuartwdouglas looks like an issue we could close easily?

**Comment by stuartwdouglas** [comment]
IMHO this is already done "
This allows you to develop in the same environment you will actually run your app in, and with access to the same services.
"
