### ISSUE TITLE
Dev UI triggers continuous testing on "R" button pressed 

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#17205]
## Describe the bug
Dev UI triggers continuous testing on "R" button pressed. This happens in http://localhost:8080/q/dev/
Even though this can be a feature, but while user editing field in the config
http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/config this shouldn't trigger continuous testing

### Expected behavior
Define scope when "R" button should run tests. 

### Actual behavior
(Describe the actual behavior clearly and concisely.)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Create bootstrap project which contains tests
2. mvn quarkus:dev
3. Go to http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/config 
4. Press "R" on any filed while typing

## Environment (please complete the following information):
Linux Fedora

### Quarkus version or git rev
Latest Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn 3.8.1

**Comment by phillip-kruger** [comment]
Fixed in #17203
