### ISSUE TITLE
getting-started-reactive deprecated code

### ISSUE THREAD

**Issue by hull90** [quarkusio/quarkus#17209]
Beginner comment here..

the second 'transform' in the demo code of the guide is deprecated

```
Multi.createFrom().ticks().every(Duration.ofSeconds(1))
        .onItem().transform(n -> String.format("hello %s - %d", name, n))
        .transform().byTakingFirstItems(count);
```
I tried 
```
Multi.createFrom().ticks().every(Duration.ofSeconds(1)).onItem()
    	.transform(n -> String.format("Hello N:" + n + " to " + name))
    	.select().first(count);
```
and it seems to work as expected

**Comment by geoand** [comment]
Thanks for reporting. 

This has already been fixed in the `main` branch and you can see the result at: https://quarkus.io/version/main/guides/getting-started-reactive
