### ISSUE TITLE
quarkus-keycloak-authorization extension allow access to a protected resource

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#17222]
## Describe the bug

Quarkus Version: `2.0.0.Alpha1, 2.0.0.Alpha2`
Extension: `quarkus-keycloak-authorization`
Reproducer: over [this project](https://github.com/pjgg/quarkus-openshift-test-suite/tree/feat/upgrade_2x) you can run the following command: `mvn -B -V clean verify -fae -Dversion.quarkus=2.0.0.Alpha2 -pl app-metadata/deployment,app-metadata/runtime,common,security/keycloak-authz -Dts.authenticated-registry`

Test: [SecurityKeycloakAuthzOpenShiftTest:noUser_userResource](https://github.com/pjgg/quarkus-openshift-test-suite/blob/feat/upgrade_2x/security/keycloak-authz/src/test/java/io/quarkus/ts/openshift/security/keycloak/authz/AbstractSecurityKeycloakAuthzOpenShiftTest.java#L97)

Keycloak properties: https://github.com/pjgg/quarkus-openshift-test-suite/blob/feat/upgrade_2x/security/keycloak-authz/src/test/resources/keycloak-realm.json

Test output: 
```
[ERROR]   SecurityKeycloakAuthzOpenShiftTest>AbstractSecurityKeycloakAuthzOpenShiftTest.noUser_adminResource:112 1 expectation failed.
Expected status code <401> but was <200>.

[ERROR]   SecurityKeycloakAuthzOpenShiftTest>AbstractSecurityKeycloakAuthzOpenShiftTest.noUser_userResource:103 1 expectation failed.
Expected status code <401> but was <200>.
```
Explanation:

Resource `/users` is protected by [Keycloak auth configuration](https://github.com/pjgg/quarkus-openshift-test-suite/blob/feat/upgrade_2x/security/keycloak-authz/src/test/resources/keycloak-realm.json) and a query without credentials should return a `401` as Quarkus 1.13.2.Final

Note: work as expected over Quarkus 1.13.2.Final and lower versions.

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by Sgitario** [comment]
This issue is duplicated by https://github.com/quarkusio/quarkus/issues/17164
cc @sberyozkin
