### ISSUE TITLE
Different Logging levels / filter possibilities for RestEasy

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#17224]
Our backend running on prod often gets some weird requests (Wrong http method, or http instead of https and trying to find wordpress or robots.txt and so on) from bots or wannabe-hackers.
Each time an error is logged and this polutes our logging.

I don't think it would be wise to entirely turn of logging for the relevant classes. 
Best might be to log this in DEV, but not log this on PROD.

https://pastebin.com/mwjpE9EC

**Comment by geoand** [comment]
@asoldano, @ronsigal is this something that is possible in RESTEasy?

**Comment by jamezp** [comment]
I don't really see a way do this in RESTEasy itself. If a resource match is not found a `NotFoundException` must be thrown. An `ExceptionMapper` could probably be used to filter these out and not print the stack trace.

**Comment by stuartwdouglas** [comment]
I just checked and this appears to no longer be an issue.
