### ISSUE TITLE
Hibernate Reactive / Reactive Messaging Transaction issue on constraint violation

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#17256]
## Describe the bug

I have a very simple application using RestEasy Reactiv, Reactive Messaging (no connector, just plain in-memory), and Hibernate Reactive with PostgreSQL.

My application has an endpoint doing this:

```java
@Channel("database")
MutinyEmitter<Person> emitter;

@POST
public Uni<Response> upload(Person person) {
    return emitter.send(person)
            .replaceWith(Response.accepted().build())
            .onFailure().recoverWithItem(t -> 
                  Response.status(Response.Status.BAD_REQUEST).entity(t.getMessage()).build()
     );
}
```

Basically, it gets a `Person` and sends it to the `database` channel.

The `database` channel is read as follows:

```java
@Incoming("database")
public Uni<Void> write(Person person) {
      return Panache.withTransaction(person::persist);
}
```    

Everything works fine until I add a constraint in my entity and that constraint gets violated:

```java
@Entity
public class Person extends PanacheEntity {

    @Column(unique = true)
    public String name;

}
```

It works until I deliberately send a payload violating the constraint. I got the 400 error, but any subsequent request gets the same issue, with the same error message:

```shell
> http POST :8080 name=a
HTTP/1.1 202 Accepted
content-length: 0

> http POST :8080 name=a # Exception expected
HTTP/1.1 400 Bad Request
Content-Type: application/octet-stream
content-length: 555

Multiple exceptions caught:
	[Exception 0] javax.persistence.PersistenceException: org.hibernate.HibernateException: io.vertx.pgclient.PgException: { "message": "duplicate key value violates unique constraint \"uk_is4vd0f6kw9sw4dxyie5cy9fa\"", "severity": "ERROR", "code": "23505", "detail": "Key (name)=(a) already exists.", "file": "nbtinsert.c", "line": "656", "routine": "_bt_check_unique", "schema": "public", "table": "person", "constraint": "uk_is4vd0f6kw9sw4dxyie5cy9fa" }
	[Exception 1] io.vertx.core.VertxException: Transaction already completed

> http POST :8080 name=b
HTTP/1.1 400 Bad Request
Content-Type: application/octet-stream
content-length: 555

Multiple exceptions caught:
	[Exception 0] javax.persistence.PersistenceException: org.hibernate.HibernateException: io.vertx.pgclient.PgException: { "message": "duplicate key value violates unique constraint \"uk_is4vd0f6kw9sw4dxyie5cy9fa\"", "severity": "ERROR", "code": "23505", "detail": "Key (name)=(a) already exists.", "file": "nbtinsert.c", "line": "656", "routine": "_bt_check_unique", "schema": "public", "table": "person", "constraint": "uk_is4vd0f6kw9sw4dxyie5cy9fa" }
	[Exception 1] io.vertx.core.VertxException: Transaction already completed
```

So even when sending `b`, it still complains about `a`. It seems like it didn't clean up after the transaction rollback.
I have checked that all the calls used the same MutinySession, but the transaction objects are different. 

## To Reproduce

[reproducer-rm-hr.zip](https://github.com/quarkusio/quarkus/files/6489668/reproducer-rm-hr.zip)

To reproduce, just run the test included in the project above ^
Or in a terminal

```shell
mvn clean quarkus:dev
```

and, in another terminal:

```shell
http POST :8080 name=bob # expected 202
http POST :8080 name=bob # expected 400 - name is not unique
http POST :8080 name=tom # expected 202, but got 400, with the same error message than the previous request
```

**Comment by cescoffier** [comment]
CC @tsegismont as it may be something in the PG client. 

BTW, it uses Panache.

**Comment by Sanne** [comment]
the 'MutinySession' should not be reused after an exception happened: it
should be closed.

**Comment by cescoffier** [comment]
Oh thanks! 
So, basically `Panache.withTransaction()` is not really usable.

**Comment by cescoffier** [comment]
I get the same behavior with:
```java
 @Incoming("database")
    public Uni<Void> write(Person person) {
        Mutiny.Session session = Panache.getSession();
        return session.withTransaction(t -> person.persistAndFlush())
                .onFailure().call(session::close);
    }
```

I always get the same session object.

Also, `close` does not seem to _close_:

```java
@Incoming("database")
    public Uni<Void> write(Person person) {
        Mutiny.Session session = Panache.getSession();
        System.out.println("Session is " + session);
        return session.withTransaction(t -> person.persistAndFlush())
                .onFailure().call(session::close)
                .onFailure().invoke(() -> System.out.println("session is open? " + session.isOpen()));
    }
```

`isOpen` is always true. I would have expected it to be `false`.

**Comment by DavideD** [comment]
I'm having a look

**Comment by Sanne** [comment]
@FroMage ( assuming Davide or someone figures out why the Session isn't being closed) - should we maybe have

```
.onFailure().call(session::close)
```
implicit as part of the `withTransaction` ? and do we need it in other places?

**Comment by DavideD** [comment]
`SessionFactory#withTransaction`  should already do that

**Comment by DavideD** [comment]
I don't think `Session#withTransaction` should also close the session. It doesn't seem the right place

**Comment by Sanne** [comment]
right, good point @DavideD - that was a bad idea.

I guess it just confuses me a lot that Session(s) are opened automatically - in which case I would expect such things to be taken care of as well.

I still think it's a bad idea - at least for reactive - to have the Session scope and lifecycle managed as managed beans as the boundaries of the context are not the same.

**Comment by DavideD** [comment]
Ah, I thought `getSession` was the same as `openSession`

**Comment by Sanne** [comment]
right that's the confusing part. The users "gets the Session" - but has no say about which one, and has no option to get a new one. It all depends on CDI's notion of "current Session" - but I keep having issues with this notion.

**Comment by DavideD** [comment]
It seems it's a bug in Hibernate Reactive, when we close the session we don't set the boolean that decides if it's open or close. I'm going to fix it

**Comment by DavideD** [comment]
I've created a PR for Hibernate Reactive: https://github.com/hibernate/hibernate-reactive/pull/759

**Comment by DavideD** [comment]
This should've been already fixed

**Comment by cescoffier** [comment]
Closing - fixed.
