### ISSUE TITLE
FSWatchUtil should assign a good name to the threads it starts

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#17254]
## Description

Apparently `FSWatchUtil` starts an `Executor`, but the threads this is spawning have name patterns like `pool-406-thread-1`.

It would be highly preferreable for all of our components to specify a good name for threads which are being started, to help with diagnostics.

**Comment by SivaTharun** [comment]
@Sanne can i work on this issue, i see that the method `observe` with in the `FSWatchUtil` class, is instantiating a single thread executor, so one worker thread of thread pool size -1 , will be started.

what is the expectation regarding the naming conventions of the pool thread

**Comment by Sanne** [comment]
thanks for offering help @SivaTharun !

Yes that's `observe` method is likely what needs to be patched. In terms of naming I would suggest a pattern like `FSWatchUtil-thread-1`

**Comment by Roshanchandipur** [comment]
I'm a beginner so can you suggest me how to get started.

**Comment by SivaTharun** [comment]
@Roshanchandipur i have already started to work on this issue and will raise a PR in a day or two.

**Comment by chetankokil** [comment]
@Sanne if this issue is still open, can i give it a shot ???
