### ISSUE TITLE
Support injection of Maps using @ConfigProperty

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#17269]
## Description
In order to provide a better developer experience, it would be good to support injection of maps directly using the `@ConfigProperty` annotation. Example:

```java
@ConfigProperty("map")
Map<String, String> myMap;
```

With properties:

```
map.A=Value 1
map."Key B"=Value 2
```

Note that Spring currently supports this approach: https://www.baeldung.com/spring-yaml-inject-map

At the moment, there is a workaround using the `@ConfigMapping` annotation, but we need to first add an interface and then inject it:

```
@ConfigMapping(prefix = "properties")
public interface PropertiesMap {
   Map<String, String> map;
}
```

Change the properties to add an additional prefix:

```
properties.map.A=Value 1
properties.map."Key B"=Value 2
```

And then injecting the interface:

```
@Inject
PropertiesMap properties;
```

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
This needs to be implemented first in SR Config.

BTW, @Sgitario, I don't consider the `@ConfigMapping` a workaround. It is the natural extension on how to represent a configuration source or namespace from the API perspective.
