### ISSUE TITLE
Support injection of `@ConfigMapping` in fields

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#17266]
## Description
Using Smallrye Config, we can inject properties using the `@ConfigMapping` annotation into fields. Example:

```
@Inject
@ConfigMapping(prefix = "cloud")
Server cloud;
```

Where the Server class is:

```
public class Server {
    String host;
    int port;

    // getters
}
```

Full example in Smallrye Config in here: https://github.com/smallrye/smallrye-config/blob/main/cdi/src/test/java/io/smallrye/config/inject/ConfigMappingInjectionTest.java

When trying to do the same in Quarkus, it fails to load using:

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.qe.configmapping.Server and qualifiers [@Default]
	- java member: io.quarkus.qe.configmapping.ConfigMappingResource#server
	- declared on CLASS bean [types=[io.quarkus.qe.configmapping.ConfigMappingResource, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.qe.configmapping.ConfigMappingResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:488)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:460)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:252)
	... 12 more
```

Note that I tried to annotate the field with `@Any`, but didn't help.

## Implementation ideas

Moreover, using it in Quarkus, it would not be necessary to use it with `@Inject`, so doing:

```
@ConfigMapping(prefix = "server")
Server server;
```

It should work.

**Comment by mkouba** [comment]
CC @radcortez

**Comment by loicmathieu** [comment]
You don't need to use `@ConfigMapping` at the injection point but only `@Inject`.
Without it, it should works

**Comment by Sgitario** [comment]
> You don't need to use `@ConfigMapping` at the injection point but only `@Inject`.
> Without it, it should works

I've updated the description to state that the `Server` class is not annotated with `@ConfigMapping`. 
The idea is to use directly the `@ConfigMapping` directly on the fields, not in the types. The same as it's done in https://github.com/smallrye/smallrye-config/blob/main/cdi/src/test/java/io/smallrye/config/inject/ConfigMappingInjectionTest.java.

**Comment by radcortez** [comment]
Hi @Sgitario,

The linked test has `Server` annotated with `@ConfigMapping`. As far as I remember, the annotation is mandatory for the mapping classe to be discovered.

For the injection point you can either use `@Inject` or `@ConfigProperties` to override the prefix from the mapping class in the injection point.

**Comment by Sgitario** [comment]
> Hi @Sgitario,
> 
> The linked test has `Server` annotated with `@ConfigMapping`. As far as I remember, the annotation is mandatory for the mapping classe to be discovered.
> 
> For the injection point you can either use `@Inject` or `@ConfigProperties` to override the prefix from the mapping class in the injection point.

Ok, I think I misinterpreted this annotation when being annotating a field. I thought we can get rid of the annotation in the interface, but instead is a way to override the mapping configuration in the interface. 
Closing then... 
Thanks @radcortez for the clarifications.

**Comment by sophokles73** [comment]
> For the injection point you can either use @Inject or @ConfigProperties to override the prefix from the mapping class in the injection point.

How can I use `@Inject` to override the prefix? AFAIK the `Inject` annotation has no properties that would allow me to do so ....

**Comment by radcortez** [comment]
Sorry, I think I miss-typed :) I meant to say use `@ConfigMapping`.

Use both `@Inject` and `@ConfigMapping(prefix=[OVERRIDE])` to override the prefix.
