### ISSUE TITLE
More config issues in Quarkus 1.13.4.Final

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#17278]
## Describe the bug

Consider this config setup:

```Java
@ConfigMapping(prefix = "dbproxy")
public interface DBProxyConfig {
    @WithName("thread_pool")
    Optional<ThreadPoolConfig> threadPool();
}

public interface ThreadPoolConfig {

    @WithName("prefix")
    @WithDefault("dbproxy-")
    String prefix();

    @WithName("min")
    @WithDefault("0")
    int minThreads();

    @WithName("max")
    @WithDefault("2147483647")//Integer.MAX_VALUE
    int maxThreads();

    @WithName("keep_alive_in_seconds")
    @WithDefault("60")
    int keepAliveInSeconds();
}
```
and this YAML config file:

```Yaml
dbproxy:
  thread_pool:
    prefix: mypool
    keep_alive_in_seconds: 10
```

### Expected behavior
The thread pool configuration is extracted properly.

### Actual behavior
Smallrye Config will fail to pick up the thread pool attributes, will default to an empty optional.

Bizarrely, we can make this work, if we do these changes:

```
public interface DBProxyConfig {
    @WithName("threadpool")
    Optional<ThreadPoolConfig> threadpool();
}

dbproxy:
  threadpool:
    prefix: mypool
    keep_alive_in_seconds: 10
```
but this is hardly acceptable!  Note that changing the method name above to ```threadPool()``` will break it again!

### Output of `uname -a` or `ver`
20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)

### Quarkus version or git rev
Quarkus 1.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0.1

Build time:   2021-05-10 16:08:58 UTC
Revision:     67e618faef187783dadd03a34fdab9dc71b85b19

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (BellSoft 16.0.1+9)
OS:           Mac OS X 11.3.1 aarch64

**Comment by hrstoyanov** [comment]
@radcortez

**Comment by radcortez** [comment]
Fixed in https://github.com/smallrye/smallrye-config/pull/570.
