### ISSUE TITLE
Auto-indexing in Jandex of classes referenced from Hibernate ORM entities/embedables/XML mappings/etc.

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#17285]
## Description

See https://github.com/quarkusio/quarkus/issues/14762#issuecomment-842310703

When the Hibernate ORM extension encounters a class that is not in the Jandex index, we get this:

```
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
        - org.agoncal.quarkus.jdbc.Customer
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

This can happen for example if a class is referenced from an XML mapping file (#16630), or if a class is indirectly referenced from an entity getter (even if the entity class itself is in the Jandex index).

Can we improve the situation and index the corresponding artifact automatically, whenever we detect such a class is missing from the Jandex index?

## Implementation ideas

None at the moment.

**Comment by stuartwdouglas** [comment]
@yrodiere do you have a test case for this? It may be as simple as: https://github.com/quarkusio/quarkus/compare/main...stuartwdouglas:jpa-computing-index?expand=1

**Comment by yrodiere** [comment]
@stuartwdouglas Indeed it does the trick. I created #17339. Thanks!
