### ISSUE TITLE
Message field as a JSON object in logging

### ISSUE THREAD

**Issue by Pedro-Henriques** [quarkusio/quarkus#17288]
Working on Quarkus 1.11.2.Final, I am trying to send logs from our application to Kibana. They go through filebeat to logstash, and then kibana.

I'm having a problem on logstash, where the "message" field in the log(JSON format) is being sent as a String instead of a JSON object. Example:
{
	"timestamp":"2021-05-17T10:31:08.826Z",
	"sequence":380,
	"loggerClassName":"org.apache.logging.log4j.spi.AbstractLogger",
	"loggerName":"com.bmw.connectedmusic.connectedradio.api.filter.ResponseFilter",
	"level":"INFO",
	"message":"
		{	
			"path":"/hello/Pedro",
			"headers":
				{
					"Content-Type":
						[{
							"parameters":{},
							"subtype":"json",
							"type":"application",
							"wildcardSubtype":false,
							"wildcardType":false
						}]},
					"code":200,
					"tier":"API",
					"method":"GET",
					"X-Correlation-ID":"174312e1-6e51-4897-bbb3-9a671ab6347b",
					"action":"FINISH",
					"params":{},
					"body":
						{
							"timestamp":"2021-05-17T10:31:08.819775Z",
							"userName":"Pedro"
						},
					"Timestamp":"2021-05-17T10:31:08.822Z"
		}",
	"threadName":"executor-thread-1",
	"threadId":18,
	"mdc":{},
	"ndc":"",
	"hostName":"avs-connected-radio-6cf566d4f-x4t2r",
	"processName":"quarkus-run.jar",
	"processId":1
}

Is there a way to configure the logger to send a JSON object in the message field instead of a String?

**Comment by gsmet** [comment]
@loicmathieu you might be able to help here.

**Comment by loicmathieu** [comment]
@Pedro-Henriques I guess you are using the `logging-gelf` extension ?
What you want is what is called **structured logging** where instead of logging a message as a simple String you want to send a structured (with a format) message in JSON.

`logging-gelf` didin't support this kind of logging, the use case is to send String based logs that will then be analysed by loggstach/elasticsearch for example (a logstash pipeline can extract a structured document from a raw String).

There is an extension inside the Quarkiverse that support structured logging: https://github.com/quarkiverse/quarkus-logging-json

**Comment by Pedro-Henriques** [comment]
Hello @loicmathieu 
Thank you for the answer, I'll take a look into that extension and solve my issue either with that extension or in logstash.

Best regards,
Pedro Henriques

**Comment by loicmathieu** [comment]
OK, can we close this issue or do you want to keep it open and provide feedback later on your findings ?

**Comment by Pedro-Henriques** [comment]
I believe we can close this issue, as the solution seems to be changing something on logstash side and not specifically change something on quarkus to work for my problem. 
It would be great if there as an option like "appender.console.layout.objectMessageAsJsonObject" that we have on our project for Log4j2, but we will make it work :)

Thank you again for the quick assistance on my doubts!

**Comment by loicmathieu** [comment]
Closing it as the question has been answered
