### ISSUE TITLE
Hibernate isInitialized not working properly

### ISSUE THREAD

**Issue by fabrii** [quarkusio/quarkus#17291]
## Describe the bug
Hibernate.isInitialized(proxy) function is not working properly.

### Expected behavior
Return true when the object is initialized.
Return false when the object is not initialized.

### Actual behavior
Returns true always.

## To Reproduce

1. Create an entitiy "a", with a OneToMany Lazy Collection.
2. logger.log(Level.INFO, "Is initialized?: " + Hibernate.isInitialized(a.getCollection()));

### Output of `uname -a` or `ver`

Linux fabricio-desktop 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

1.11.3 and 1.13.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-73-generic", arch: "amd64", family: "unix"

**Comment by yrodiere** [comment]
Thank you for your report.

Unfortunately, I was not able to reproduce your problem with the provided information. In my tests, `Hibernate.isInitialized()` returns `false` as expected.

Please provide a minimal project reproducing the problem.

You can for example use this one as the base of your reproducer, changing whatever is necessary to reproduce your problem: https://github.com/yrodiere/quarkus-playground/tree/hibernate-isinitialized

**Comment by fabrii** [comment]
Hi! You just need to change this line:

Containing containing = entityManager.getReference(Containing.class, id);

by

Containing containing = entityManager.find(Containing.class, id);

**Comment by Sanne** [comment]
@fabrii that would invalidate the test: `find` is not allowed to return a lazily initialized object - it needs to load the real object.

**Comment by yrodiere** [comment]
@Sanne I must admit I'm a bit surprised; is `find` supposed to load lazy collections? It should not return a proxy, that's for sure, but loading lazy collections as well seems a bit... too much?

**Comment by Sanne** [comment]
ah sorry sure - I was only referring to the object itself, my bad I misunderstood.

**Comment by fabrii** [comment]
From my experience using Quarkus, when using find the collections are lazy (no querys are fired to the database to load them), but the Hibernate.isInitialized returns true anyway.

**Comment by yrodiere** [comment]
From what I can see, `Hibernate.isInitialized` is right: the collection *was* initialized. It shouldn't have been, though, and *that* is a bug.

I opened https://hibernate.atlassian.net/browse/HHH-14620 upstream.

**Comment by plevart** [comment]
Hi, what's the state of this? I'm using Quarkus 2.11.2 which uses Hibernate 5.6.10 and I still trigger some Hibernate Session interaction by calling myEntity.getMyFetchTypeLazyCollection() while Hibernate.isInitialized(myEntity) == true. Since this happens in a custom serializer when the Session is not active any more, it triggers Hibernate exception. Here's the relevant part of stack trace:

```
Caused by: org.hibernate.LazyInitializationException: Unable to perform requested lazy initialization [eu.otlm.ferengi.hibernate.model.Tower$E.spanB] - no session and settings disallow loading outside the Session
        at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.throwLazyInitializationException(EnhancementHelper.java:275)
        at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.performWork(EnhancementHelper.java:165)
        at org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.loadAttribute(LazyAttributeLoadingInterceptor.java:80)
        at org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.fetchAttribute(LazyAttributeLoadingInterceptor.java:76)
        at org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.handleRead(LazyAttributeLoadingInterceptor.java:57)
        at org.hibernate.bytecode.enhance.spi.interceptor.AbstractInterceptor.readObject(AbstractInterceptor.java:153)
        at eu.otlm.ferengi.hibernate.model.Tower$E.$$_hibernate_read_spanB(Tower.java)
        at eu.otlm.ferengi.hibernate.model.Tower$E.getSpanB(Tower.java:64)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

...and here's the part of the entity with mapping annotations:

```java
        @Override
        @OneToMany(targetEntity = Span.E.class, mappedBy = "towerB", fetch = FetchType.LAZY)
        public Set<Span> getSpanB() {
            return spanB;
        }
```

It looks like although the `Tower$E` proxy should be initialized as `Hibernate.isInitialized(tower) == true`, calling `.getSpanB()` on it still triggers Hibernate Session interaction. Shouldn't this already be fixed?

**Comment by yrodiere** [comment]
@plevart No, the fact that your entity is initialized does not mean its associations are. You `spanB` association is lazy, so unless you access it before closing your session, that lazy init exception is expected.

If you want to discuss this further, please open a GitHub discussion or a bug report. Reviving old topics is not a great way to get visibility to your comments ;)

**Comment by plevart** [comment]
Sorry, I incorrectly assumed this issue was still open.

**Comment by plevart** [comment]
I posted this here: https://github.com/quarkusio/quarkus/discussions/27657
