### ISSUE TITLE
Register Exception handler for vertx-web

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1729]
After speaking to @mkouba regarding #1714 there is an issue where if a bean instance fails to instantiate as part of a vertx-web application, the root cause exception is swallowed, and a http 500 error is returned to the client

We need to register an exception handler for vertx-web to log any bean instantiation exceptions.

**Comment by mkouba** [comment]
Note that `vertx-web` does not register any sophisticated error handler by default. However, we should be probably more user-friendly. @cescoffier @vietj WDYT?

BTW we already register a `BodyHandler` automatically.

**Comment by gsmet** [comment]
@cescoffier what's the status of this? Was this addressed somehow?

**Comment by stuartwdouglas** [comment]
This was fixed by https://github.com/quarkusio/quarkus/commit/83c432703cb923b1707165780b9e06e4ca1c5aa7
