### ISSUE TITLE
Agroal has a thread local leak

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#17304]
`io.agroal.pool.ConnectionPool#localCache` is never cleared, so when running QuarkusUnitTest and QuarkusDevModeTest this leaks the ClassLoaders, which will eventually result in an OutOfMemoryError if there are too many tests in the module.

**Comment by stuartwdouglas** [comment]
Note that just clearing the list is not enough, the we need some way to clear the TL so there threads ThreadLocalMap does not hold a reference to the ClassLoader.

**Comment by yrodiere** [comment]
Note we raised the memory and metaspace allocated in JVMs spawned by surefire in #16630, so that we could get the build to pass despite leaks. Once the leaks are addressed, we should set those values back to `1500m`.
See the last commit in #16630.

**Comment by barreiro** [comment]
The TL cache in Agroal should be cleared periodically, on the idle timeout check. Quarkus sets a default value of 5M for that.

**Comment by Sanne** [comment]
@barreiro the leak is happening when the application is restarted, for example during continuous testing. Could you make sure it's also cleared on shutdown?
