### ISSUE TITLE
CLI `qs` to support native executable building using containers.

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#17320]
## Description
I'm currently using `qs` version 1.13.3.Final and it works great, but I'm missing a feature to build native executables in a container (to create Linux binaries).

(Describe the feature here.)
I can build a native using `qs build -n`,  but that requires a locally installed GraalVM. I actually think that it would be better to default `qs build -n` to use containers to build. This way the GraalVM or Mandrel version will automatically be aligned to use the correct version for the Quarkus project I'm building.  (e.g. same as `mvn package -Pnative -Dquarkus.native.container-build=true` does). We could instead offer an additional flag called ` -gh --graalvm-home` and let the user set the GraalVM home path. Alternative if nothing is specified it will use the value of `GRAALVM_HOME`. 

The benefit is that this would lower the number of mistakes because of misalignment with GraalVM version and not require you to download GraalVM. The drawback is that building in a container is a bit slower, but that is not a big issue in my opinion. 

## Implementation ideas
The CLI could check if the user has docker or podman installed locally, if not fall back to try to use GRAALVM_HOME.

**Comment by ebullient** [comment]
yep. this is on my list to fix for all of those reasons.

**Comment by Sgitario** [comment]
@ebullient I'm looking into this issue and I think it's already working fine:
- Using`quarkus build --native` will build native using containers by default
- Using`quarkus build --native -Dquarkus.native.container-build=false ` will build native using graalvm tooling (if found)

Therefore, what's missing here? (just asking)

**Comment by ebullient** [comment]
What I have been thinking about is how to map/consolidate some of the image properties into easier to use flags. Something like: 
```
quarkus build --native
quarkus build --native --with-container
```
or something that would work with tab-completion. WDYT?

**Comment by Sgitario** [comment]
> What I have been thinking about is how to map/consolidate some of the properties into easier to use flags. Something like:
> 
> ```
> quarkus build --native
> quarkus build --native --with-container
> ```
> 
> or something that would work with tab-completion. WDYT?
> 
> I'm also thinking about how to set this up for testing..

Fine with me! But my concern now is how you are planning to append some contextual help to all these options. For example, the `--with-container` only makes sense when using this another option `--native`.

**Comment by ebullient** [comment]
Exactly. That's why I'm still mulling things over. 
It could be an optional attribute of the native parameter `--native=container`, 
Or it could be an alternate parameter (where you use one or the other) `--native-container`.

**Comment by maxandersen** [comment]
closing this as basic functionallity is there. using --native or passing through the explicit flags.
