### ISSUE TITLE
No http_server_requests data  in /q/metrics with micrometer enabled

### ISSUE THREAD

**Issue by kusumachalasani** [quarkusio/quarkus#17337]
## Describe the bug
Even after the micrometer is enabled, http_server_requests data is not seen in /q/metrics.
The same behaviour is observed on openshift cluster , minikube and with docker commands.

### Expected behavior
We should be able to get  http_server_requests data

### Actual behavior
No http_server_requests data

## To Reproduce

For the TechEmpower Frameworks bechmark, I enabled micrometer and created the required images to run the benchmark.
Benchmark  - `https://github.com/kusumachalasani/FrameworkBenchmarks/tree/tfb_mm/frameworks/Java/quarkus/resteasy-hibernate`
                       Git : `https://github.com/kusumachalasani/FrameworkBenchmarks -b tfb_mm`
Manifests location - `https://github.com/kusumachalasani/benchmarks/tree/tfb/techempower/manifests` 
                                Git : `https://github.com/kusumachalasani/benchmarks -b tfb`
Images : `kusumach/postgres`  `kusumach/tfb-qrh-mm:1.13.2.F_v1.1`

**Steps to reproduce the behavior:**
**On openshift** 
1. Apply the DB manifests file - postgres.yaml   and then the application - quarkus-resteasy-hibernate.yaml
        oc apply -f postgres.yaml
        oc apply -f quarkus-resteasy-hibernate.yaml
        Expose the service of application : oc expose svc/tfb-qrh-service
2. Once the pods are up and running, hit the endpoint /db multiple times.
3. Check for /q/metrics and look for data related to http_server_requests.

**On minikube**
1. Apply the DB manifests file - postgres.yaml   and then the application - quarkus-resteasy-hibernate.yaml
        kubectl apply -f postgres.yaml
        kubectl apply -f quarkus-resteasy-hibernate.yaml
2. Application URL will be <minikube ip>:32334
2. Once the pods are up and running, hit the endpoint /db multiple times.
3. Check for /q/metrics and look for data related to http_server_requests.

**Using docker commands:**
Start postgres
`docker run --ulimit memlock=-1:-1 -d --rm=true --network host --memory-swappiness=0 -e POSTGRES_USER=benchmarkdbuser -e POSTGRES_PASSWORD=benchmarkdbpass -e POSTGRES_DB=hello_world -p 5432:5432 --name tfb-database kusumach/postgres`
Start Quarkus Application
`docker run --rm -d --name tfb-server --network host -e QUARKUS_DATASOURCE_JDBC_URL="jdbc:postgresql://localhost:5432/hello_world?loggerLevel=OFF&disableColumnSanitiser=true&assumeMinServerVersion=12&sslmode=disable" kusumach/tfb-qrh-mm:1.13.2.F_v1.1`

### Quarkus version  1.13.2.Final

**Comment by ebullient** [comment]
There needs to be a better reproducer for this, as I can't reproduce it using the benchmark app. When I run the application, the metrics are present as expected.
One thing I did notice in your repo is that you specify the version for the micrometer-prometheus registry extension. That line should be removed: 
```
diff --git a/frameworks/Java/quarkus/resteasy-hibernate/pom.xml b/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
index 282e3f8d4..bfa50d2a8 100644
--- a/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
+++ b/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
@@ -41,7 +41,6 @@
        <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
-            <version>1.11.3.Final</version>
         </dependency>
```

**Comment by ebullient** [comment]
We could try turning on debugging which would not work for a benchmark run, but should show what is going on (whether or not timers are completing): `quarkus.log.category."io.quarkus.micrometer".level=DEBUG`

**Comment by kusumachalasani** [comment]
> There needs to be a better reproducer for this, as I can't reproduce it using the benchmark app. When I run the application, the metrics are present as expected.
> One thing I did notice in your repo is that you specify the version for the micrometer-prometheus registry extension. That line should be removed:
> 
> ```
> diff --git a/frameworks/Java/quarkus/resteasy-hibernate/pom.xml b/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
> index 282e3f8d4..bfa50d2a8 100644
> --- a/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
> +++ b/frameworks/Java/quarkus/resteasy-hibernate/pom.xml
> @@ -41,7 +41,6 @@
>         <dependency>
>              <groupId>io.quarkus</groupId>
>              <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
> -            <version>1.11.3.Final</version>
>          </dependency>
> ```

I did remove the version line and tried. I still see the same behaviour.
Will turn on the debug and try.

**Comment by ebullient** [comment]
`"-Dvertx.disableMetrics=true` was present in the docker file, which disabled vertx-based metrics.
