### ISSUE TITLE
Add vertx-web-client to the BOM

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#1733]
RIght now, the only way to add the `vertx-web-client` dependency is:
```xml
<dependency>
   <groupId>io.vertx</groupId>
   <artifactId>vertx-web-client</artifactId>
   <version>3.6.3</version> <!-- versions are not imported from a pom dependency -->
</dependency>
```

**Comment by kenfinnigan** [comment]
Do we want vertx dependencies exposed through Quarkus BOM?

Check with @cescoffier

**Comment by mkouba** [comment]
It's already assigned to Clement ;-). Anyway, we already have non-quarkus dependencies in BOM so I see no reason why not `vertx-web-client`.

**Comment by kenfinnigan** [comment]
It's not so much about a non Quarkus dependency, but exposing Vert.x programming model and whether doing so makes things more complicated. Will leave it up to @cescoffier

**Comment by cescoffier** [comment]
I would rather add the Axle versions which are more inlined with the API model.

**Comment by mkouba** [comment]
Ok. Well, feel free to add the Axle version only but honestly I don't understand the reason. If you look at our BOM we do include things like guava, org.apache.httpcomponents, jetty-client... and it's probably not that we're "exposing" their APIs.
