### ISSUE TITLE
Pressing "r" when all tests are passing in broken only mode won't re-run any tests (continuous testing)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17330]
## Description

```
All 3 tests are passing (0 skipped), 0 tests were run in 395ms.
```

I think pressing "r" should temporarily override the broken mode.

In broken only mode, I think we should also re-run tests (already passed) when their direct content is changed, or when adding new tests (if that's possible).

**Comment by stuartwdouglas** [comment]
Adding new tests already works, but changing the test class itself is a deliberate decision. The logic is:

- In normal mode if you change a test class all its tests are run, and no other tests, so if you want this behavior just use normal mode
- If you have 10 tests in a class and you just want to debug the failing one it is super annoying to have the other 10 tests tripping your breakpoints

**Comment by ia3andy** [comment]
> Adding new tests already works, but changing the test class itself is a deliberate decision. The logic is:
> 
> * In normal mode if you change a test class all its tests are run, and no other tests, so if you want this behavior just use normal mode
> * If you have 10 tests in a class and you just want to debug the failing one it is super annoying to have the other 10 tests tripping your breakpoints

Ok, yeah if all the tests are run, then I get it, I was thinking it was possible to only run the modified one (with a direct modification if its definition, not a dependency).


Still the main issue is still a problem right? "Pressing "r" when all tests are passing in broken only mode won't re-run any tests"

**Comment by stuartwdouglas** [comment]
yea, the linked PR fixes it
