### ISSUE TITLE
Exposing the request object in Qute

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#17353]
## Description

Qute already exposes a few built-ing objects such as the [configuration](https://quarkus.io/guides/qute-reference#config): `{config:foo}`. Sometimes, when you are in a Qute template, you need to access the root-path of the resource. With `config` you could do `{config:property('quarkus.http.host')}:{config:property('quarkus.http.port')}`.

It would be nice for Qute to expose a `request` object. This way, we could use `{request:headers}` and `{request:host}`

## Implementation ideas

As discussed in [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Accessing.20the.20root-path.20in.20Qute), @mkouba came up with this implementation:

```
@Singleton
class CurrentRequest {
    @Named("request")
    @Produces
    @RequestScoped
    public io.vertx.core.http.HttpServerRequest getCurrent(RoutingContext rc) {
       return rc.request();
    }
}
```

The advantage with this is that it would give infinie possibilities in terms of producing as many objects as needed. The inconventient, is that the syntax would be something like `{inject:request.headers}`  `{inject:request.host}` instead of just `{request:headers}`. Which would collide with `{config:foo}` instead of `{inject:config.foo}`.

## References

* https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Accessing.20the.20root-path.20in.20Qute
* https://quarkus.io/guides/qute-reference
* https://www.programmersought.com/article/61734778618/
* https://quarkus.io/guides/qute-reference#config

**Comment by mkouba** [comment]
So another advantage of the `@Named` approach, i.e. `{inject:request.foo}`, is that you can pass the current request as a param of a virtual method, e.g. `{service.doSomethingWithRequest(inject:request)}`. This would not be possible with the `request:` namespace. Also the impl would be much less complicated. I think that we can start with the `@Named` approach and add the specialized namespace if needed. @agoncal WDYT?
