### ISSUE TITLE
Unable to serialize simple Kotlin data class

### ISSUE THREAD

**Issue by MarkusKramer** [quarkusio/quarkus#17358]
I'm trying to serialize a data class. I've already simplified it to:

```
import com.fasterxml.jackson.annotation.JsonProperty

data class BadRequestResponse constructor(
    @field:JsonProperty("date")
    val date: String? = null
)
```

using
```
val body = objectMapper.writeValueAsString(BadRequestResponse(
            date = Instant.now().toString()
        ))
```
it gives me an empty JSON "{}" string.

This works in JVM mode but not in native image mode. I'm successfully serializing / deserializing objects in other places of my app.

Using Quarkus version: 1.13.4.Final, with quarkus-resteasy-jackson.

**Comment by geoand** [comment]
Have you tried adding `@RegisterForReflection` to `BadRequestResponse`?

**Comment by MarkusKramer** [comment]
Thanks, that solved my problem. However, I'm not directly returning BadRequestResponse in the Response but serialize it manually first.

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello(): String {
        val body = objectMapper.writeValueAsString(
            BadRequestResponse(
                date = Instant.now().toString()
            )
        )
        return body
    }
```


 Maybe this could be added in the documentation under https://quarkus.io/guides/kotlin#kotlin-and-jackson or is this still a bug?

**Comment by geoand** [comment]
It's not a bug.

Unless you return the class itself from the method, there is no way for Quarkus to know what class you are using.

The documentation does mention this annotation in the jsom guide.
