### ISSUE TITLE
Dev mode fails to reload classes when using reactive rest client

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#17359]
## Describe the bug
We are using resteasy reactive and the reactive rest client in Quarkus 1.13.4.Final, gradle and Kotlin. Everytime the quarkus dev mode reloads the code, Quarkus is broken and we have to restart it.

We were able to break it down to a small reproducer. The problem seems to appear, when we have a POST resource that receives a DTO in the body and passes this dto to a rest client call that receives a generified response (best take a look at the `ReactiveResource:getClient()` method in the reproducer). When the service is freshly started `gradlew quarkusDev`, it all works fine. However, as soon as you change something and quarkus recompiles the code on the next call, it is broken.

We added a logging of the received object and there we get the following error:

```
2021-05-19 15:52:52,547 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-10) Request failed: java.lang.ClassCastException: class org.acme.dto.ApiResponse cannot be cast to class org.acme.dto.ApiResponse (org.acme.dto.ApiResponse is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @df5f5c0; org.acme.dto.ApiResponse is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1091b449)
	at org.acme.ReactiveResource$getClient$1.apply(ReactiveResource.kt:18)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
...
```

When we do not add the logging, the response from the resource is just empty. 

Please note: In the reproducer, we use the rest client to call the same quarkus service again. This is just to make the reproducer self contained. We also experienced this when calling another service.

### Expected behavior
Quarkus Dev Mo

### Actual behavior
The classes do not seem to be reloaded correctly.

## To Reproduce

1. Download reproducer and unzip [2021-05-19-restclient-dev-mode.zip](https://github.com/quarkusio/quarkus/files/6509313/2021-05-19-restclient-dev-mode.zip)
2. In the project run `./gradlew quarkusDev`
3. Call the endpoint with 
```
curl --location --request POST 'localhost:8080/client' \
--header 'Content-Type: application/json' \
--data-raw '{
	"name" : "Bernd"
}'
```
4. Change anything in the code to cause a recompile on the next call
5. Call the service again and observe the error in the log.

**Comment by geoand** [comment]
What versions have you tried? `1.13.4.Final`, `2.0.0.Alpha2`, `main`?

**Comment by andreas-eberle** [comment]
Only 1.13.4.Final so far.

**Comment by geoand** [comment]
I just tried Quarkus from `main` and the problem still exists.

I'll take a look soon

**Comment by andreas-eberle** [comment]
Thanks @geoand!

**Comment by andreas-eberle** [comment]
Hi @geoand ,

it looks like the same issue happens with Quarkus 2.0.0.CR2 when you use coroutines. Can you have a look? I updated my reproducer project: [2021-05-19-restclient-dev-mode (2).zip](https://github.com/quarkusio/quarkus/files/6576292/2021-05-19-restclient-dev-mode.2.zip)

Many thanks!

**Comment by geoand** [comment]
Can you open a new issue please?

**Comment by andreas-eberle** [comment]
Sure
