### ISSUE TITLE
SDL Directives in smallrye graphql

### ISSUE THREAD

**Issue by hogmuzzle** [quarkusio/quarkus#17376]
Smallrye Graphql has support for SDL Directives but implementation in quarkus is not compatible with the new smallrye version. 

Can you please add support for the last version of smallrye qraphql to quarkus.

**Comment by phillip-kruger** [comment]
This will be in Quarkus 2.

**Comment by phillip-kruger** [comment]
Closing here as the latest (already in main branch) will be in the next version of Quarkus.
