### ISSUE TITLE
MP RestClient calls fail if OpenTelemetry is in list of dependencies

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#17385]
Auth tests fail, I see at https://github.com/RedHatInsights/notifications-backend/blob/8cbd03f2f648d68e681a0[…]/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java a failure of `java.lang.NoClassDefFoundError: org/jboss/resteasy/client/jaxrs/internal/ClientRequestContextImpl` is thrown as result of trying to do a call via MP-RestClient.

We see this issue since switching to Quarkus-resteasy-reactive from Resteasy-classic.

It turns out that the OpenTelemetry dependencies in the POM cause the failure

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-jaeger</artifactId>
        </dependency>

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

1. build / verify https://github.com/pilhuhn/notifications-backend/tree/089bcbd464d2d713e2abad715fe91b93c687965f
2. see tests fail with code 401
3. remove opentelemetries dependencies from pom
4. rebuild / verify
5. See tests pass

### Quarkus version or git rev

1.13.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.1

cc @kenfinnigan

**Comment by kenfinnigan** [comment]
Thanks @pilhuhn
