### ISSUE TITLE
quarkus-jaeger: JAEGER_SERVICE_NAME env variable can't be used anymore

### ISSUE THREAD

**Issue by calohmn** [quarkusio/quarkus#17400]
## Describe the bug

When using Jaeger tracing with the `io.quarkus:quarkus-jaeger` dependency, a documented way of setting the jaeger service name is using the `JAEGER_SERVICE_NAME`  env var.

This is for example described here:
https://quarkus.io/guides/opentracing#run-the-application
````
./mvnw compile quarkus:dev -Djvm.args="-DJAEGER_SERVICE_NAME=myservice -DJAEGER_SAMPLER_TYPE=const -DJAEGER_SAMPLER_PARAM=1"
````

But, this doesn't work anymore (it seems since https://github.com/quarkusio/quarkus/commit/434f195df32f207faee92a13f0a98e2ce69bd0cb#diff-b51318f59f7f35e1bf92b6454af4a7a047c2401c4f258f93632a84fc1027e92f).

See the relevant code here:
https://github.com/quarkusio/quarkus/blob/9245ad39e42234e929bf24034821c619d76ee23a/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/JaegerDeploymentRecorder.java#L42-L50

The service name is now either taken from the `quarkus.jaeger.service-name` property or the application config name. If both are not set, `quarkus/unknown` is used.

### Expected behavior

Expected behaviour would be that `JAEGER_SERVICE_NAME` can be used to set the service name.
I would expect this order of precedence:

`quarkus.jaeger.service-name` > `JAEGER_SERVICE_NAME` > application config name > `quarkus/unknown` 

### Actual behavior

`JAEGER_SERVICE_NAME` is currently being ignored.

## To Reproduce

Run an application using `io.quarkus:quarkus-jaeger` and try to set the service name using `JAEGER_SERVICE_NAME`.

### Quarkus version or git rev

Tested with Quarkus 1.11.6.

**Comment by geoand** [comment]
I am going to close this as it's very old and we have moved to using OpenTelemetry for all tracing needs
