### ISSUE TITLE
Built-in NotFoundException triggered before Request-Filter

### ISSUE THREAD

**Issue by mikoma** [quarkusio/quarkus#17413]
## Describe the bug
I want to use a  "Request-ID" for logging and as a custom HTTP-header to trace requests through our microservice network. The idea is to use a `ContainerRequestFilter` to read the request-id from an incoming request or create a new id, if it's not available, then use a `ContainerResponseFilter` to add the request-id to the response-header. The design also includes a custom `ExceptionMapper<Throwable>` that takes care of logging and formatting the response.

Now I'm facing multiple issues:

- Requesting an undefined route will trigger a `NotFoundException` that is captured by the built-in ExceptionMapper as described in [#7883](https://github.com/quarkusio/quarkus/issues/7883), instead of my custom `ExceptionMapper<Throwable>`
- The `NotFoundException` is thrown before the `ContainerRequestFilter`, which is never being triggered. Thus no request-ID will be created (neither from the header, nor a new one) - in my current implementation the value will be null and cause the next issue:
- The `ContainerResponseFilter` on the other hand is being triggered and tries to add a header value of null. The result of this is that the server will give no response at all. The request will eventually timeout.

### Expected behavior
- No `WebApplicationException` is thrown before `ContainerRequestFilter` are triggered
- My own `ExceptionMapper<Throwable>` is used instead of a built-in one
- Setting a header value of null should not result in a timeout

### Actual behavior
- The `ContainerRequestFilter` is never triggered
- The built-in NotFoundException-handler is used
- The request results in a timeout

## To Reproduce

1. Implement request and response filters and a simple class to transfer the request-id
2. Make HTTP-request to an undefined route
3. Observe that the server won't respond

```
@Provider
public class RequestIdFilter implements ContainerRequestFilter {
    @Inject
    RequestDetails requestDetails;

    @Override
    public void filter(ContainerRequestContext context) {
        requestDetails.setRequestId(context.getHeaderString("X-Request-ID"));
    }
}

@Provider
public class ResponseFilter implements ContainerResponseFilter {
    @Inject
    RequestDetails requestDetails;

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) {
        responseContext.getHeaders().add("X-Request-ID", requestDetails.getRequestId());
    }
}

@RequestScoped
public class RequestDetails {

    String requestId;

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        if(requestId == null) {
            this.requestId = "new random id";
        } else {
            this.requestId = requestId;
        }

    }
}
```

**Comment by geoand** [comment]
Have you tried this with RESTEasy Reactive to see what the behavior is?

**Comment by geoand** [comment]
I am pretty sure what you are seeing with regards to the request filter is actually spec defined behavior.
To overcome it, simply annotate the filter with [@PreMatching](https://docs.oracle.com/javaee/7/api/javax/ws/rs/container/PreMatching.html)
