### ISSUE TITLE
Quarkus Keycloak is not considering the http method when evaluating the matching Authorization Services resource

### ISSUE THREAD

**Issue by codependent** [quarkusio/quarkus#17416]
## Describe the bug
Suppose you have two Keycloak resources 

One for GET /messages

<img width="836" alt="image" src="https://user-images.githubusercontent.com/6399869/119155746-c7149980-ba53-11eb-80fe-20e9efc73100.png">

And another one for POST /messages

<img width="854" alt="image" src="https://user-images.githubusercontent.com/6399869/119155702-bd8b3180-ba53-11eb-9b56-0f73b06ff9ef.png">

I assign a policy for user1 with permission to access the get-resource and another policy for user2 with permission for post-resource.

I'm using the quarkus-keycloak library with the policy enforcer configuration enabled the http method as scope:

```
quarkus:
  keycloak:
    policy-enforcer:
      enable: true
      http-method-as-scope: true
```

The problem is, calls from user2 (which can access POST /message) are evaluated considering the path (but not the method).

In `org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize()` --> `PathConfig pathConfig = this.getPathConfig(request); `

The corresponding resource is obtained using the request path, not the combination of method + request path, so user2 gets a match with get-resource (instead of post-resource) and consequently doesn't get access to the resource.

### Expected behavior
Path evaluations against resources should consider the HTTP method when http-method-as-scope is true

### Actual behavior
Evaluations of matching resource consider only the path, so in cases where there are multiple resources with different scopes, any of them would be returned

### Configuration
```properties
quarkus:
  keycloak:
    policy-enforcer:
      enable: true
      http-method-as-scope: true
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin MacBook-Pro-de-Adminprfl-2.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
### Quarkus version or git rev
1.13.4.Final

**Comment by sberyozkin** [comment]
@pedroigor Hi Pedro, can you comment ?

**Comment by codependent** [comment]
Here's a more detailed explanation of this issue:

Resource configuration:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/6399869/119173171-2fb94180-ba67-11eb-9b12-4f02fe49f8b3.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/6399869/119173196-3b0c6d00-ba67-11eb-839d-8a63a8a31215.png">

Policies:

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/6399869/119173276-57100e80-ba67-11eb-9846-49328b3d6084.png">

Permissions:

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/6399869/119173308-62fbd080-ba67-11eb-9631-19ca47341035.png">

Summing up :

user1 shoud be able to invoke GET /message
user1 can't invoke POST /message

user2 can't invoke GET /message
user2 shoud be able to invoke POST /message

**user1**

I get an access token through http://localhost:8180/auth/realms/myrealm/protocol/openid-connect/token using a password flow for user1

GET /message  -> 200
POST /message -> 403 

This behaviour is correct

**user2**
I get an access token through http://localhost:8180/auth/realms/myrealm/protocol/openid-connect/token using a password flow for user2

GET /message  -> 403 
POST /message -> 403

user2 should be able to invoke POST /message. Having a look at the logs we can see that the `AbstractPolicyEnforcer` is checking against the _get-resource_ resource, instead of the _post-resource_ resource, as it isn't considering the HTTP method as indicated previously.

```
2021-05-21 19:08:35,794 DEBUG [org.key.ada.aut.AbstractPolicyEnforcer] (executor-thread-1) Checking permissions for path [http://localhost:8081/message] with config [PathConfig{name='get-resource', type='null', path='/message', scopes=[GET], id='fe192d20-3256-41f8-9172-1a25ab2d28c4', enforcerMode='ENFORCING'}].
```

**Comment by codependent** [comment]
More info:

In `PolicyEnforcer` there's a resource search by targetUrI: `List<ResourceRepresentation> matchingResources = authzClient.protection().resource().findByMatchingUri(targetUri);`

Since ProtectedResource supports searching also by scope...

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/6399869/119181661-339e9100-ba72-11eb-86a2-416ee66d2fe5.png">

I guess this could be fixed passing the HTTP verb when `http-method-as-scope: true`.

**Comment by pedroigor** [comment]
@codependent Thanks for the report and the contribution. Really appreciated it.

It is expected a single resource (e.g.: messages resource) associated with the two scopes (e.g: get and post). Then for each scope you can define individual permissions (scope-based permissions) so that they are evaluated accordingly depending on the  scope being requested.

I'm not sure if we want to have distinct resources mapping to a same URI. Could you check if the approach above works for you?

**Comment by codependent** [comment]
@pedroigor thanks for your feedback, I didn't know that restriction was in place, I must've missed it in the docs. Offhand I'd say that it could work for that case. However we are trying to model a fine grained scenario that needs mapping the _kind of same URI_ to different resources, e.g.:

**admin-resource**
/articles/{id} GET, POST
-> User admin will have GET and POST permission to all {id}s.

**editor-resource**
/articles/1 GET, POST
-> User editor will have GET and POST permission to only a subset of the ids, in this case id 1.

Should this be supported? By the way I [opened an issue](https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-18265?filter=reportedbyme) for this particular case in Jira.

**Comment by pedroigor** [comment]
@codependent In this case, I think you should be able to use a single resource (e.g.: Article) and a single permission with two policies using the `AFFIRMATIVE` decision strategy:

* One that grants access to admins
* One that grants access to an editor

By using the `AFFIRMATIVE`, a permit from any policy should be enough to grant access to the resource.

Another way to solve this is leveraging the concept of resource types. When a resource defines a type other resources with the same type should inherit the permissions and scopes associated with the "parent" resource. However, this parent/child relationship is only possible if the child resources have a user as the owner. We have an example here https://github.com/keycloak/keycloak-quickstarts/blob/latest/app-authz-photoz/photoz-restful-api/src/main/resources/photoz-restful-api-authz-service.json#L26.

I think this example is similar to what you are trying to do.

**Comment by codependent** [comment]
@pedroigor In case I had only one resource with a single URI /articles/{id} GET, POST.

The admin policy is straightforward, however I still don’t grasp how to restrict access by id for an editor. Using a js policy? User == someuser && id == 1? If this is the case how can we access the resource uri id from JavaScript?

**Comment by pedroigor** [comment]
@codependent Sorry for the delay.

There are two options here. The example I pointed out created resources dynamically and these resources are set with the user as the `owner`. In this case, the JS policy would just check if the identity from the context is the same user set as the owner.

Another option is to push claims. You could pass over the `owner` identifier as a claim to your policies and then perform the same comparison. The difference here is that your application should be aware of the user that should have access to the article and send that as a claim to policies.

**Comment by codependent** [comment]
@pedroigor Thanks again for your time. I'll follow your suggestions from the last comment.

I'm closing this issue as it doesn't apply.
