### ISSUE TITLE
SmallRye GraphQL Subscription Concurrent Connections

### ISSUE THREAD

**Issue by ethan-gallant** [quarkusio/quarkus#17422]
## Describe the bug
Concurrent connections in the Quarkus-Smallrye-GraphQL library do not work. Once a single client is connected and subscribed, no other clients are able to receive data from the socket. The socket allows the connection but no data is sent. Also, should one client send a malformed payload that causes an exception, all clients fail and disconnect.

### Expected behavior
Multiple clients should be able to connect at the same time

### Actual behavior
Once a client connects, any other clients are blocked and do not receive any data. Though the WebSocket does open and function, just no data.

## To Reproduce

https://github.com/Volxz/quarkus-smallrye-graphql-test

1. Run the  quarkus app
2. Open two browser tabs and navigate to the graphql-ui
3. Start two subscribers that are running concurrently

```graphql
subscription {
    pong(p: {startingNumber: 5}) {
    pongNumber
  }
}
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
```Linux NotAComputer 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
### Output of `java -version`
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
### Quarkus version or git rev
``` 
2.0.0.Alpha3 
```
## Additional context
I believe this may be a problem with the AtomicReference specified in [SmallRyeGraphQLSubscriptionHandler](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLSubscriptionHandler.java) as there is only one instance allowed of a subscription. I could be completely wrong and am currently hacking on master. I am also looking into the Smallrye library.

**Comment by ethan-gallant** [comment]
I believe I have pinned down the problem with the subscription handler. I have a working solution in the MR although I am unsure if this is the correct way to do it. 

The main problem I found was in the SmallRyeGraphQLSubscriptionHandler there was an AtomicReference<Subscription> which would be updated as soon as new subscriptions came in. The problem I found was that there is only one instance of the SmallRyeGraphQLSubscriptionHandler meaning that any new subscriptions would attempt to overwrite it, causing it to fail until the previous subscription was cancelled or completed.

The two options I can think of would be to RequestScope the entire SmallRyeGraphQLSubscriptionHandler or to implement a socket management solution such as a ConcurrentHashmap in the PR.

Again, unsure if this is the correct way to do it, but any criticism is greatly appreciated and I will be sure to implement any needed changes or different methods of solving this issue.

Thank you @phillip-kruger for the speedy responses inside of Zulip and the quick tips on where to look. 😄 

Here are some commented screenshots of where I believe the problem is coming from
![image](https://user-images.githubusercontent.com/19141569/119249052-beab8400-bb63-11eb-8cd9-fae138e94d4b.png)
![image](https://user-images.githubusercontent.com/19141569/119249069-d1be5400-bb63-11eb-8235-d93d85128009.png)

**Comment by phillip-kruger** [comment]
Hi @ethan-gallant - I can confirm that this is a bug. You can try with Alpha2, as this worked initially (see https://user-images.githubusercontent.com/6836179/118034779-aa4cd780-b36a-11eb-8469-ee3be51852f0.gif) I'll looked into the diffs to see where I broke this.

**Comment by gsmet** [comment]
@phillip-kruger have you seen https://github.com/quarkusio/quarkus/pull/17423 ?

**Comment by phillip-kruger** [comment]
@gsmet - No I have not :) Thanks. Looking now.
