### ISSUE TITLE
Hibernate reactive with panache project throws ClassCastException in dev mode

### ISSUE THREAD

**Issue by ScientistPun** [quarkusio/quarkus#17421]
## Describe the bug
I use hibernate reactive with panache to do my database work. When use two seccessive invocation of project on the same projection class in dev mode, it throws ClassCastException.

### Expected behavior
Don't throw

### Actual behavior
It throws ClassCastException

## To Reproduce

1. Write an Entity (e.g. E)
2. Write a projection class (e.g. P)
3. Project the class for the entity in Panache transaction twice by flatMap
4. Start quarkus dev
5. Modify something to let quarkus dev relaod
6. It throws ClassCastException saying that P cannot be cast to P. It indicates that the same class P are from two different instances of io.quarkus.bootstrap.classloading.QuarkusClassLoader

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
![image](https://user-images.githubusercontent.com/22999568/119222209-c51b0b00-bb25-11eb-86aa-32c84051d36d.png)

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
What version of Quarkus are you seeing this issue in?

Can you attach a sample project that demonstrates this error please?

**Comment by qiuhw** [comment]
Hi, the bug reporter is my workmate.
> What version of Quarkus are you seeing this issue in (asking because various similar issues have already been fixed)?
We use 1.13.4.Final the latest stable version.
> 
> Can you attach a sample project that demonstrates this error please (mentioning this because it's important we have an exact reproducer as this could be caused by various things)?
The sample project is attached

[bug-demo.gz](https://github.com/quarkusio/quarkus/files/6536267/bug-demo.gz)

**Comment by qiuhw** [comment]
The problem also exists in 1.13.5.Final, 1.13.6.Final and 2.0.0.CR2.

**Comment by Sanne** [comment]
I think this might be fixed in Quarkus `main` now as consequence of fixing #18875

But I can't try it again currently :)  @DavideD could you test it?

**Comment by DavideD** [comment]
Yes, I will have a look

**Comment by DavideD** [comment]
I can confirm the live reload works now with the latest quarkus snapshot.
No exception is thrown.

**Comment by Sanne** [comment]
excellent, thanks @DavideD !
