### ISSUE TITLE
RESTEasy Reactive: read ContainerRequestContext getEntityStream in filter resource method payload becomes null

### ISSUE THREAD

**Issue by selvarajchennappan** [quarkusio/quarkus#17430]
## Describe the bug
Resource method payload becomes null if we do 
ContainerRequestContext#getEntityStream in ContainerRequestFilter

Payload : pojo [FileUpload ]

### Expected behavior
(Describe the expected behavior clearly and concisely.)
payload shoudn't be null
### Actual behavior
(Describe the actual behavior clearly and concisely.)
payload is null

if we remove filter then it works as expected . 

[quarkus-issue.zip](https://github.com/quarkusio/quarkus/files/6531164/quarkus-issue.zip)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. add filter implementation and read getEntityStream
2. upload file and file is null in resource class
3. remove filter works 
please note that added @Blocking 
### Configuration
```properties
# Add your application.properties here, if applicable.

```
Java version : 1.8 
Quarkus version : 1.13.4.Final
We have implemented our application using reactive, had forced to mark it as blocking we have use case to process the request entity at filter .However its not working 
### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Additional context
(Add any other context about the problem here.)

**Comment by selvarajchennappan** [comment]
could you please update on this issue . it is blocker now

**Comment by geoand** [comment]
You essentially need to do what is described in https://github.com/quarkusio/quarkus/issues/17280

**Comment by selvarajchennappan** [comment]
thanks 
I hope you had seen the attached code .
changed from implements ContainerRequestFilter to 	@ServerRequestFilter(priority = 0)

**However it is not working .**
@Blocking is also there  
@ApplicationPath("/")
@Blocking
public class RestBlockingApplication extends Application {
}
Could you please check .

**Comment by geoand** [comment]
Please provide a complete working example and steps on how to reproduce the problem

**Comment by selvarajchennappan** [comment]
It is not working when content type "multipart/form-data" fileUpload becomes null 
we have to  log every request inpustream to kafka.

[quarkus-fileupload-log-issue.zip](https://github.com/quarkusio/quarkus/files/6537159/quarkus-fileupload-log-issue.zip)

Reproduce:-
upload file with name ["fileUpload"]from postman or any http client .
 logs getting printed in filter but resource class its empty 
application.properties
quarkus.http.port=8080
quarkus.http.body.delete-uploaded-files-on-end= false --tried with false as well actual is true .
quarkus.http.body.uploads-directory=/temp
quarkus.http.body.preallocate-body-buffer =true
quarkus.http.limits.max-body-size=200M

**Comment by selvarajchennappan** [comment]
@geoand could you please update on this issue.

**Comment by geoand** [comment]
Please add a fully working example I can check without having to fill anything in myself and I'll give it another look

**Comment by geoand** [comment]
Thanks.

Basically you need to do as https://github.com/quarkusio/quarkus/issues/17280 describe, i.e. to buffer the stream. 
This is because in Java IO, when a stream is read, you can't re-read it. 
So you buffer the data you read and then set the entity stream to the buffered stream thus allowing the framework to read the body as well

**Comment by selvarajchennappan** [comment]
Thanks for immediate response .
@geoand set the entity stream to the buffered stream however its not working
InputStream is = ctx.getEntityStream();
String body = new BufferedReader(new InputStreamReader(is)).lines().collect(Collectors.joining("\n"));
**ctx.setEntityStream(new ByteArrayInputStream(body.getBytes()));**

As had mentioned before it works with content type json. I think issue is with Multipart fileupload .
Could you please check

**Comment by geoand** [comment]
I will check next week as I am on PTO

**Comment by geoand** [comment]
Unfortunately the way we handle things won't work for this use case.

The issue is that we reading the entire body in a filter is rathe dodgy and can mess up the subsequent processing by Vert.x (and therefore the Multipart handling)... 
I think we should have a way to provide some kind of filter that logs the request body (or allows the user to handle it) that will play nice with the rest of the infrastructure, but I don't know what that would look like.

@FroMage @stuartwdouglas any ideas?

**Comment by FroMage** [comment]
Is it because Vert.x handles multi-part by bypassing our entity stream?

**Comment by geoand** [comment]
Yes, exactly

**Comment by FroMage** [comment]
Can we detect that someone changed it, and then load it differently frmo vert.x?

That won't work for any other custom vert.x-specific handler that bypasses the jax-rs API, but :shrug:

**Comment by geoand** [comment]
I would much like to avoid having to do something like that. I would prefer if we could have some kind of special filter that could let the user handle the entire body without messing up the following handlers for Vert.x.
That said, I don't know what that would look like

**Comment by FroMage** [comment]
Not sure we can do that if one of the handlers needs to stream the body into something: there's never any "fullly loaded" representation of the bytes.

The best we might be able to do is an API that lets users "see" the byte buffers as we pass them to whatever's consuming them. Not sure it'd help in this case.

Sort of like a streaming filter…

**Comment by stuartwdouglas** [comment]
I think we need to write our own Multipart handler, and not rely on Vert.x.

**Comment by stuartwdouglas** [comment]
With the linked PR the example works, if you correct the code to:

```
		InputStream is = ctx.getEntityStream();
		byte[] data = is.readAllBytes();
		String body = new String(data, StandardCharsets.UTF_8);
		System.out.println(" successfully read entity stream in filter" + body);
		// push to kafka
		ctx.setEntityStream(new ByteArrayInputStream(data));
```

**Comment by selvarajchennappan** [comment]
Thanks a lot.
Does it work for content type "multipart/form-data" ?

**Comment by stuartwdouglas** [comment]
Should work for both.
