### ISSUE TITLE
Random not allowed in Kafka SASL

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#17444]
https://gist.github.com/alesj/65fb0483632e5e247e3c4fb1e8ee086a

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace:
at parsing org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.access$100(SaslClientAuthenticator.java:77)
```

https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa#diff-8ea159555f76609d835155ca3b7f534b8a5adbb932fa6366c4db09a5b2ec2275

**Comment by gsmet** [comment]
Can you make sure you are using 2.0.0.Alpha3 of the `quarkus-kafka-client` extension too?

Because this should have been fixed for a while: https://github.com/quarkusio/quarkus/commit/5cb8c3c35407c82b14895b486ec1fba33f2c785c#diff-b2a1070ffbd0dee93197f4ae77ed98dab5e006359468ce012f8c85f005e9510d .

**Comment by alesj** [comment]
> Can you make sure you are using 2.0.0.Alpha3 of the quarkus-kafka-client extension too?

This is the only place where I set the version ...
* https://github.com/alesj/quarkus-kafka-exporter/blob/main/pom.xml#L27

And switching from 2.0.0.Alpha2 to 2.0.0.Alpha3 results in that error ...

**Comment by alesj** [comment]
OK, missing dependency on the extension ...
