### ISSUE TITLE
Quarkus/Gradle/Application class CDI issue - Injected variable is null during test step

### ISSUE THREAD

**Issue by bogedal** [quarkusio/quarkus#17441]
## Describe the bug
During the test step of gradle the test fails with a nullpointer exception on the injected variable in the Application class.

## To Reproduce
[reproducer.zip](https://github.com/quarkusio/quarkus/files/6536746/reproducer.zip)

1. execute gradle build

### Output of `java -version`
Java version "11.0.10" 2021-01-19 LTS

### Quarkus version or git rev
Quarkus version 1.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by geoand** [comment]
This is a limitation of JAX-RS, you can't inject stuff via CDI into a JAX-RS Application class

**Comment by geoand** [comment]
Sure, I'm not saying it can't be done technically.

What I am saying is that because reads this class at build time, injection does not work

**Comment by bogedal** [comment]
@geoand Do you mean that Quarkus reads this class at build time?

**Comment by geoand** [comment]
> @geoand Do you mean that Quarkus reads this class at build time?

Yes

**Comment by bogedal** [comment]
Ok - Thanks a lot for the very quick responses :)

**Comment by geoand** [comment]
I have a opened a PR to make this a build time error in RESTEasy Reactive.
