### ISSUE TITLE
OIDC introspection (opaque access token, not jwt)

### ISSUE THREAD

**Issue by tiagodev** [quarkusio/quarkus#17457]
I'm using quarkus 1.11.1. and oidc _service_  application type.

Is there any option to disable introspection for opaque access tokens?

Thank you.

**Comment by sberyozkin** [comment]
@tiagodev In 1.13.x or 2.0.0.M2 one can use `quarkus.oidc.token.allow-jwt-introspection=false` - but it only blocks the JWT token introspection.
What is your requirement ? Are you working with JWT but would like to block the opaque tokens ?
One option to try is to disable the auto discovery and only set the `jwks-path` - in this case no introspection will be possible for any token - not sure how it will work in `1.11.x` - but should fail with `401` in `1.13.x`/`2.0.0.M2`

**Comment by tiagodev** [comment]
@sberyozkin Perfect that will do. Thank you ;)

**Comment by sberyozkin** [comment]
@tiagodev Please re-open if it is not 401 for the opaque tokens when introspection path is not available in 1.13.x/2.0.0.x, thanks

**Comment by sberyozkin** [comment]
It will fail, but we don't have a test yet where an opaque token is rejected because no introspection path is available

**Comment by sberyozkin** [comment]
Perfect, thanks :-)

**Comment by tiagodev** [comment]
sorry i meant 500

**Comment by sberyozkin** [comment]
@tiagodev OK :-), which version is it ?

**Comment by tiagodev** [comment]
1.13.x

**Comment by sberyozkin** [comment]
I think I may need to introduce `quarkus.oidc.token.allow-opaque-token-introspection` - since if it is a valid opaque token and the server has not been configured with the introspection path it may well be `500`, especially if it is expected the opaque tokens are used. It would also work with or without auto discovery (as opposed to the suggested indirect solution) and will be easy to understand what it is for.

**Comment by tiagodev** [comment]
quick question @sberyozkin is it possible to have multiple clients calling a quarkus api with an opaque access token? probably I'm missing something but if the lib calls the introspection, which requires a client id and secret, how do I handle multiple client ids?
