### ISSUE TITLE
quarkus.log.console.enable disable file log handlers

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#17480]
## Describe the bug
with the following application.properties
```
quarkus.package.type=uber-jar
quarkus.log.level=INFO
quarkus.log.console.enable=false
quarkus.log.console.level=INFO

quarkus.log.handler.file."CONSOLE_MIRROR".enable=true
quarkus.log.handler.file."CONSOLE_MIRROR".path=quarkus.log

quarkus.log.category."".handlers=CONSOLE_MIRROR
```
when running the uber jar (it's working file with quarkus:dev) 
 the file quarkus.log is created but is empty.

This was working prior quarkus 1.13

## To Reproduce

https://github.com/rmanibus/quarkus_17480

1.  mvn install
2. java -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
 -> application does not log to quarkus.log
3. java -Dquarkus.log.console.enable=true -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
 -> application log to quarkus.log

**Comment by famod** [comment]
This works:
```
#...
quarkus.log.file.enable=true
quarkus.log.file.path=quarkus.log
```
If you really want a named handler you need to use a proper category, like `org.acme` in your case:
```
#...
quarkus.log.handler.file."CONSOLE_MIRROR".enable=true
quarkus.log.handler.file."CONSOLE_MIRROR".path=quarkus.log

quarkus.log.category."org.acme".handlers=CONSOLE_MIRROR
```

https://quarkus.io/guides/logging does not mention `""` to be a valid category.
So I'm inclined to close this. WDYT @dmlloyd?

**Comment by rmanibus** [comment]
In my understanding it was the way to declare the root category. Also It was working beforr quarkus 1.13.4 so I assume something has changed recently.

**Comment by dmlloyd** [comment]
This seems like a legitimate request to me.  We should have a way to attach named handlers to the root logging config, like this:

```properties
quarkus.log.handler.file.CONSOLE_MIRROR.enable=true
quarkus.log.handler.file.CONSOLE_MIRROR.path=quarkus.log

quarkus.log.handlers=CONSOLE_MIRROR
```

This would be consistent with how we configure the root category log level.

**Comment by famod** [comment]
Makes sense!

FWIW, something in [1.3.0.CR1](https://github.com/quarkusio/quarkus/releases/tag/1.13.0.CR1) causes `quarkus.log.category."".handlers=CONSOLE_MIRROR` to not work as in 1.12.2.Final (just verified with this reproducer).
Maybe https://github.com/quarkusio/quarkus/commit/88172b7f54030f536361c9f1e113c4539e1d10e6 or https://github.com/quarkusio/quarkus/commit/5b69ffa9ded999138edfaaa6d9692bbf9697ee4a.

**Comment by rmanibus** [comment]
After some more investigation, even with a category set, the file handler does not work if the console is disabled.
```
quarkus.log.category."org.acme".handlers=CONSOLE_MIRROR
```
If a file logger is configured, then everything work fine.

```
quarkus.log.file.enable=true
quarkus.log.file.path=quarkus2.log
```

**Comment by geoand** [comment]
Does https://github.com/quarkusio/quarkus/pull/26657 make sense?

**Comment by rmanibus** [comment]
@geoand Thank you very much for taking care of this I will have a look !

**Comment by geoand** [comment]
👍🏼
