### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by andresetevejob** [quarkusio/quarkus#1750]
Hi,
I am a java developer, I heard about quarkus during a talk by Emmanuel Bernard.I would like to contribute to the development of the project.I read the guide line of contribution.IL asks to install the tools and to clone the project.After that how should I go about being in the list of contributors and follow the issues they need to be addressed

**Comment by cescoffier** [comment]
@andresetevejob you can pick any of the opened issue. Once you decide on one, just add a comment to the issue saying that you are working on this. I recommend to pick one of these:
https://github.com/quarkusio/quarkus/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
