### ISSUE TITLE
Quarkus : 1.13.6.Final : Out of date version of GraalVM detected: GraalVM Version 20.0.0 CE

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#17508]
I want to build a native image but I got this compilation error even if I specify Mandrel 21.0 version

PS.  I'm on windows 10.

mvn clean package -Pnative -DskipTests "-Dnative-container-build=true" "-Dquarkus.container-image.build=true" "-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11"

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.6.Final:build (default) on project kubernetes-api: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.IllegalStateException: Out of date version of GraalVM detected: GraalVM Version 20.0.0 CE. Quarkus currently supports 21.0. Please upgrade GraalVM to this version.
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.checkGraalVMVersion(NativeImageBuildStep.java:359)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:155)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by geoand** [comment]
I am pretty sure those quotes you are using are incorrect and causing the system properties to not be set

**Comment by survivant** [comment]
there are mandatory now with powershell.  see : https://github.com/quarkusio/quarkus/issues/16291

**Comment by geoand** [comment]
In any case, I don't have a Windows machine, so someone else will have to take this

**Comment by survivant** [comment]
I ran the command with -X  and I found this

[DEBUG] properties used {env.NUMBER_OF_PROCESSORS=8, env.USERPROFILE=C:\Users\sd003526, java.specification.version=11, sun.cpu.isalist=amd64, quarkus.container-image.build=true, sun.arch.data.model=64, env.PROGRAMW6432=C:\Program Files, surefire-plugin.version=3.0.0-M5, java.vendor.url=http://java.oracle.com/, env.OS=Windows_NT, maven.compiler.parameters=true, sun.boot.library.path=C:\dev\jdk11\bin, sun.java.command=




````
org.codehaus.plexus.classworlds.launcher.Launcher clean package -Pnative -DskipTests -Dnative-container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11 -X

... env.MAVEN_CMD_LINE_ARGS=clean package -Pnative -DskipTests -Dnative-container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11 -X
````

and this at the end

````
[DEBUG] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\native-image.cmd --version
[DEBUG] [org.jboss.threads] Thread "Thread[build-11,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-15,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-9,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-17,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-19,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-22,5,build group]" exiting
[DEBUG] [org.jboss.threads] Thread "Thread[build-20,5,build group]" exiting
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.0.0 CE
[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build" in 10714 ms
[DEBUG] [io.quarkus.builder] Dependency of "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result" finished; 0 remaining
[DEBUG] [io.quarkus.builder] Dependency of "io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromNativeImage" finished; 0 remaining
[DEBUG] [io.quarkus.builder] Starting step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result"
[DEBUG] [io.quarkus.builder] Starting step "io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromNativeImage"
[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result" in 1 ms
[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromNativeImage" in 2 ms
[DEBUG] [io.quarkus.builder] Dependency of "io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy" finished; 1 remaining
[DEBUG] [io.quarkus.builder] Dependency of "io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy" finished; 0 remaining
[DEBUG] [io.quarkus.builder] Starting step "io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy"
[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy" in 0 ms
````

**Comment by survivant** [comment]
@aloubyansky do you have a idea what could be the issue ?

**Comment by aloubyansky** [comment]
Looks like the arguments are messed up. Try
````
mvn clean package -Pnative -DskipTests "-Dquarkus.native.container-build=true" "-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11"
````
instead.

**Comment by survivant** [comment]
can we provide JAVA heapsize and other params in the dockerfile.native ?

like
````
CMD ["./application", "-XshowSettings:vm -XX:+HeapDumpOnOutOfMemoryError -Xms200m -Xmx500m -Dquarkus.http.host=0.0.0.0"]
````

in JVM mode, I have this when I launch the application
````
root@test-pcl4004:~# kubectl logs kubernetes-api-76bd8f7cc6-68gr5 |less
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XshowSettings:vm -XX:+HeapDumpOnOutOfMemoryError -Xms1g -Xmx1500m -XX:+ExitOnOutOfMemoryError -cp . -jar /app/quarkus-run.jar
VM settings:
    Min. Heap Size: 1.00G
    Max. Heap Size: 1.46G
    Using VM: OpenJDK 64-Bit Server VM
````
How can I validate if the memory params were passed correctly ? I didn't find example in Quarkus native guide about that.
