### ISSUE TITLE
Use ';' as default delimited in Hibernate ORM's generated DDL scripts

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#17514]
## Description

The new `HibernateOrmConfigPersistenceUnitScriptGeneration` allowing to generate DDL scripts is a very nice addition. What appears to be missing is a `delimiter` option to map to Hibernate's `hibernate.hbm2ddl.delimiter` option, so that the generated statements in the script are delimited. Otherwise the delimiter is always just a new line, which isn't all that useful, since some statements in the output could span multiple lines.

## Implementation ideas
Add a new `delimiter` option to `HibernateOrmConfigPersistenceUnitScriptGeneration`. The default value should maybe be `;` but another option would be to have a default value for each supported DB kind, although that may just complicate things without much value.

**Comment by Sanne** [comment]
I really like the idea of having a default value for each database kind.

**Comment by knutwannheden** [comment]
> I really like the idea of having a default value for each database kind.

I assume `;` will be OK for most dialects. For Oracle (when using SQL*Plus) `\n/` (i.e. a slash on a line of its own) may be a better alternative, although it probably shouldn't matter for the DDL produced by Hibernate, where `;` would likely work nicely as well.

If someone knows which separator is required for the currently supported database kinds, it would be great if you could document them here.

**Comment by knutwannheden** [comment]
P.S. I can look into providing a PR for this issue.

**Comment by Sanne** [comment]
Amending the title to reflect how this is being fixed (via https://hibernate.atlassian.net/browse/HHH-14665 )
