### ISSUE TITLE
Reactive messaging LocalDateTime issues

### ISSUE THREAD

**Issue by Sleepy-GH** [quarkusio/quarkus#17511]
## Describe the bug
I was trying to set something up with reactive amqp messaging and I noticed that whenever I send an object to the message broker (ActiveMQ Artemis) that contains a LocalDateTime (presumably also LocalDate, didn't check that), the request seems to "hang" in Postman (stuck on sending request) whereas when I remove the LocalDateTime from my model and resend the request it gets processed without issues.

### Expected behavior
That reactive messaging can send models with LocalDateTime to message brokers.

### Actual behavior
The request is "stuck" processing and the message never gets delivered to the queue.

## To Reproduce
See the attached archive for a small project that can reproduce the problem
[quarkus-msg.zip](https://github.com/quarkusio/quarkus/files/6557243/quarkus-msg.zip)

1. docker-compose up
2. http://localhost:8161/console/  log in and create the `model` address and queue.
3. Run the application and POST the sample request located in src/main/resources/test.json to http://localhost:8080/test
4. Note that the request is "stuck"
5. Comment out the LocalDateTime field from Model.java and retry.
6. Note that the request is processed and there is now a message on the queue.

### Configuration
```properties
# AMQP settings
amqp-username=test
amqp-password=test

mp.messaging.outgoing.test.connector=smallrye-amqp
mp.messaging.outgoing.test.address=model
```

### Output of `uname -a` or `ver`
Running on Windows 10

### Output of `java -version`
$ java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)

### GraalVM version (if different from Java)
Not running natively

### Quarkus version or git rev
1.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven home: ${HOME}\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 15.0.2, vendor: AdoptOpenJDK, runtime: D:\Dev\Java\AdoptOpenJDK\jdk-15.0.2.7-hotspot
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Additional context
-

**Comment by kenfinnigan** [comment]
I think a JSON serializer for `LocalDateTime` would need to be registered, just as if you were returning a model object with `LocalDateTime` in it as a REST response

**Comment by cescoffier** [comment]
You need to register the module handling the date on the Vertx JSON Object Mapper. 

This is slightly different in 2.0, where the mapper is shared between vertx and Quarkus, which means that a regular customization of the Quarkus mapper works.

**Comment by Sleepy-GH** [comment]
Okay, I can try that. Would the workaround in this issue be the way to do that? https://github.com/quarkusio/quarkus/issues/9741

Shouldn't it also just throw an exception in stead of the request getting stuck?

**Comment by cescoffier** [comment]
It should not be stuck, that's definitely a bug. And yes, #9741 provides a workaround.

**Comment by cescoffier** [comment]
The issue has already been fixed in 2.x. However, I've opened a PR on the AMQP connector to improve the reporting and avoid being stuck.

**Comment by cescoffier** [comment]
Closed - fixed in reactive messaging and integrated into the CR3.
