### ISSUE TITLE
supporting of hibernate.integration.envers.enabled property

### ISSUE THREAD

**Issue by maciekg89** [quarkusio/quarkus#17516]
I want to be able to disable/enable of ENVERS  using application.properties.

I suggest:
quarkus.hibernate-envers.enabled   //default true

This property could be equivalent to hibernate.integration.envers.enabled
It should be runtime property.

I tried using hibernate.properties to disable Envers but there is the problem - https://github.com/quarkusio/quarkus/issues/17515
So, actually, in my opinion, the only way to disable ENVERS  is persistance.xml (I didn't check it)

**Comment by Sanne** [comment]
this is a reasonable request, but please share why.

Couldn't you exclude the extension from the dependency of your project?
We're really preferring encouraging keeping the classpaths as small as
possible.

**Comment by maciekg89** [comment]
I am aware that it is better not to have a dependency that is not used, but our applications are used in a few projects.
Sometimes, the Envers is needed, sometimes not. We don't want to  create two versions of jars with and without Envers.

**Comment by Sanne** [comment]
>It should be runtime property.

Sorry that's not possible. It needs to be a build time property as the Envers metadata affects the model, and the model needs to be fixated at build time.

Would you still see a use case for this or should I close it?

**Comment by maciekg89** [comment]
Yes, I see a use case, e.g. the jar with envers can be used as dependency in quarkus application. And sometimes envers is not needed.

**Comment by maciekg89** [comment]
So, build time property  will also be useful.

**Comment by Sanne** [comment]
> Yes, I see a use case, e.g. the jar with envers can be used as dependency in quarkus application. And sometimes envers is not needed.

Good point. Especially if you have multiple persistence units, and only want Envers used on some of them.
