### ISSUE TITLE
Wrong/insufficient instructions on https://quarkus.io/guides/amazon-lambda-http

### ISSUE THREAD

**Issue by rohit-gandhe** [quarkusio/quarkus#17513]
## Describe the bug
(Describe the problem clearly and concisely.)
Running the following command should create a project with mvn wrapper, which can be used to package/deploy projects
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-rest-archetype \
       -DarchetypeVersion=1.13.6.Final

### Expected behavior
(Describe the expected behavior clearly and concisely.)
Create a maven wrapper mvnw
Building the project should create sam.jvm.yaml and sam.native.yaml

### Actual behavior
(Describe the actual behavior clearly and concisely.)
Doesn't create mvn wrapper, which is needed by later instructions to build other files
Building the project doesn't generate sam.xxx.yaml files

## To Reproduce
Run 
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-rest-archetype \
       -DarchetypeVersion=1.13.6.Final

**Comment by geoand** [comment]
Closing this as I just tried it and `sam.native.yaml` / `sam.jvm.yaml` were properly generated using Quarkus `2.10.2.Final`
