### ISSUE TITLE
io.quarkus.hibernate.orm.runtime.boot.QuarkusEnvironment - hibernate.properties has leading "/". It causes the file can not be read.

### ISSUE THREAD

**Issue by maciekg89** [quarkusio/quarkus#17515]
## Describe the bug

There is following line:
          InputStream stream = classLoader.getResourceAsStream("/hibernate.properties");<br class="Apple-interchange-newline">

the leading "/" causes the method to always return null.

https://stackoverflow.com/questions/47900677/where-does-leading-slash-in-java-class-loader-getresource-leads-to

I am aware that this is legacy fragment, but to fix it, only deleting "/" is required.

**Comment by Sanne** [comment]
to be fair the use of 'hibernate.properties' is deprecated in Quarkus as it
bypasses our ability to warn & amend for critical configuration mistakes -
which is important to us as it's otherwise fairly complex to integrate
Hibernate ORM in Quarkus correctly and without causing lots of difficult to
diagnose issues.

Could you elaborate on why you're needing to use it?

**Comment by maciekg89** [comment]
I tried use it only for set hibernate.integration.envers.enabled (https://github.com/quarkusio/quarkus/issues/17516)

If hibernate.properties' is deprecated and this fragment is never executed ( classLoader.getResourceAsStream("/hibernate.properties") ALWAYS return null) I suggest remove this code. It can be confusing for users. I tried using this hibernate.properties after reading this class (with  full awareness that is depracated) but  It took me a while to realize that this piece of code would never execute.

**Comment by Sanne** [comment]
Good point, I'll get rid of it. To be clear while we had deprecated it, I didn't know that it wasn't working at all - but it's a great indicator about how widely used this was!

**Comment by yrodiere** [comment]
The offending class was removed as part of #17538 : https://github.com/quarkusio/quarkus/pull/17538/files#diff-890a90ad2811570bef83600bec368cb7ff101c1cca5a4a975e6ea881b40f0167

Closing this issue as it is no longer relevant. Thanks for starting the discussion @maciekg89!
