### ISSUE TITLE
Overriding SecurityContext doesn't work with quarkus-resteasy-reactive, but works with quarkus-resteasy

### ISSUE THREAD

**Issue by rohit-gandhe** [quarkusio/quarkus#17527]
## Describe the bug
I use AWS cognito to get a JWT token. I have the following code to override quarkus ContainerRequestContext's security context with my own with additional attributes from Cognito

`@PreMatching
public class SecurityFilter implements ContainerRequestFilter {

@Inject
    AuthenticationContextImpl authCtx;

    @Override
    public void filter(ContainerRequestContext requestContext) {
        String authHeader = requestContext.getHeaderString(HttpHeaders.AUTHORIZATION);

        AUser user = new AUser(xxxxx);
        requestContext.setSecurityContext(new SecurityContext() {
            @Override
            public Principal getUserPrincipal() {
                return new Principal() {
                    @Override
                    public String getName() {
                        return user.getName();
                    }
                };
            }

            @Override
            public boolean isUserInRole(String r) {
                return user.getGroups().contains(r);
            }

            @Override
            public boolean isSecure() {
                return true;
            }

            @Override
            public String getAuthenticationScheme() {
                return "basic";
            }

            public XXXUser getUser(){
                return user;
            }

        });

    }`

This works fine when I use quarkus-resteasy dependency

`
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
`

but throws the following exception when I use quarkus-rest-easy-reactive dependency

`2021-05-21 23:27:43,564 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /interests failed, error id: f5b561bd-c844-45cc-80b0-dbc4077409b9-1: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface io.quarkus.security.identity.CurrentIdentityAssociation] and qualifiers [[]]
    at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
    at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
    at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
    at io.quarkus.resteasy.reactive.server.runtime.security.SecurityContextOverrideHandler.updateIdentity(SecurityContextOverrideHandler.java:46)
    at io.quarkus.resteasy.reactive.server.runtime.security.SecurityContextOverrideHandler.handle(SecurityContextOverrideHandler.java:41)
    at io.quarkus.resteasy.reactive.server.runtime.security.SecurityContextOverrideHandler.handle(SecurityContextOverrideHandler.java:25)`

### Expected behavior
Overriding SecurityContext through a filter shouldn't break quarkus-reactive 

### Actual behavior
Breaks quarkus-reactive

## Additional context
@geoand asked to open this issue https://stackoverflow.com/questions/67644917/quarkus-overriding-securitycontext-doesnt-work-with-quarkus-resteasy-reactive

**Comment by FroMage** [comment]
Sorry I'm not familiar with what this override does.
