### ISSUE TITLE
smallrye.config.locations property didn't work on 2.0.0.CR2

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#17525]
## Describe the bug
Using the `smallrye.config.locations` property didn't works on 2.0.0.CR2 but the new `quarkus.config.locations` do works.

### Expected behavior
Both property works

### Output of `uname -a` or `ver`
Microsoft Windows [version 10.0.19042.964]

### Output of `java -version`
openjdk version "16" 2021-03-16

### Quarkus version or git rev
2.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

**Comment by radcortez** [comment]
Strange. I was not able to reproduce. Do you mind proving me a reproducer? Maybe something else is messing up.

**Comment by radcortez** [comment]
BTW, the relocation was added here: https://github.com/quarkusio/quarkus/commit/ff0dfd44479e484bbea9091e79a96f14b318a8ed, so since 1.13.x without any apparent issue.

**Comment by loicmathieu** [comment]
I was running 1.13 previously so it's definitly something going on with Quarkus 2.0.
More info on this, I use a property inside of one of those external config file and inject it inside a Java class via `@ConfigProperty`, I don't know if it is the scenario you tested.
I'll try to make a reproducer later this week if I found the time.

**Comment by radcortez** [comment]
Check this one:
https://github.com/radcortez/microprofile-samples/commit/907e27e3350ece8138ebe842b6b813052bc12304

Test runs fine. Also in dev mode with `mvn quarkus:dev -Dsmallrye.config.locations=config.properties`. I'm probably missing something :)

**Comment by loicmathieu** [comment]
Here is a reproducer, using 2.0.0.CR3.
[smallrye-config-external-issue.zip](https://github.com/quarkusio/quarkus/files/6622513/smallrye-config-external-issue.zip)

Running the reproducer with `smallrye.config.locations` show an error in the logs that no upstream subscriber is defined. Using `quarkus.config.locations` all works fine.

I use smallrye reactive messaging Kafka in my reproducer as it's the framework that I use in my component, so maybe the issue is in the way the Kafka connector is configured

**Comment by radcortez** [comment]
Added a fix. The issue only occurred in some specific cases, where a `quarkus.config.locations` was recorded in build time from `smallrye.config.locations`.
