### ISSUE TITLE
Remove (deprecated) support for hibernate.properties

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#17537]
## Description
A long deprecated and undocumented "backdoor" which allows to specify any Hibernate ORM configuration property is to have an `hibernate.properties` resource in the root of the classpath.

Not only this has been long deprecated, but it appears from report #17515 that this was no longer working at all.

The lack of general feedback about this also seems like a good indicator it's safe enough to now fully remove this, as a preference over fixing the partial support.

Also to note: this was hard to support as such options had the ability to override the preference defined by our extension, and never supported live-reloading.

**Comment by Sanne** [comment]
@gsmet sorry I didn't think of doing this before CR - still since it seems this was already broken I think you should consider it for backport to 2.0

**Comment by yrodiere** [comment]
> but it appears from report #17515 that this was no longer working at all.

The question is how long has this not been working. At least on April 13th, it was still working, since there's a reproducer here that uses `hibernate.properties` as a workaround: https://github.com/quarkusio/quarkus/issues/16463

And I still think that, especially for workarounds, such support for arbitrary properties *is* valuable. I understand it goes against the Quarkus policy of only exposing what was proven to be necessary, though.

**Comment by Sanne** [comment]
> And I still think that, especially for workarounds, such support for arbitrary properties is valuable. I understand it goes against the Quarkus policy of only exposing what was proven to be necessary, though.

yea and I'm well aware that some people will hate me for this. But I still think it's necessary - we've kept this around (undocumented) because often we couldn't address specific needs with alternative fixes fast enough, but it has to stop at some point as this backdoor is unsupportable and leads to more trouble.

> The question is how long has this not been working. 

Fair question, but my comment was meant in context of "should we backport or not to 2.0" - clearly this would have been ideally addressed before some CR, but considering it's broken we either go with it or fix it. I say it's a good time to remove.

Remember people can also still use `persistence.xml` ... and now even XML mapping ;-) Both are better tested.
