### ISSUE TITLE
Panache MongoDB regex does not work

### ISSUE THREAD

**Issue by YunaBraska** [quarkusio/quarkus#17534]
## Describe the bug
While using Quarkus with Mongodb, Since PanacheQL does not cover everything, I need to use objects like  `BasicDBObject`, and `Document` (https://mongodb.github.io/mongo-java-driver/4.2/driver/tutorials/perform-read-operations/). But some filters are not working like regex: `new Document("$regex", "/.*" + name + ".*/I")` or ` new BasicDBObject("$regex", "/.*" + name + ".*/I")`. The issue might be, that the regex is double quoted as a string while performing the query. next issue is that the Mongodb original operators like `gte`, `eq`,... does not work but writing that as a string like `$gte` works. And I still don't know how to create a `sort` with the `Document` Object.

### Expected behavior
* The `$regex` should just work
* Functions should be tested on Quarkus Panache!
* Add more explanation like this: https://mongodb.github.io/mongo-java-driver/4.2/driver/tutorials/perform-read-operations/
* Add more explanation about sorting with `Document`

### Actual behavior
* The `$regex` is not working at all.
* The documentation does not tell you enough about Mongodb filters

## To Reproduce
* Create a Quarks project
* Add Panache MongoDb
* Filter your entries with a regex.

## Additional info
* I really have no time for a demo Project as all my invested time is currently spent on creating many workarounds and debugging Quarkus. I am really frustrated about the developed and documented Quarkus functions which most of my time doesn't work. Currently Quarks feels like a bundle of libraries not like a framework. Please provide more tested functionalities.

**Comment by YunaBraska** [comment]
Yesterday I have tried different solutions to create `Document` queries:
* [FAILED] `new Document("$regex", Patternt.compile(myRegex))`
  * Result: "name": {"$regex": {"$regularExpression": {"pattern": "/.*R.*/i", "options": ""}}}
* [FAILED] `new Document(Patternt.compile(myRegex))`
  * Result: "name": {"$regularExpression": {"pattern": "/.*R.*/i", "options": ""}}
* [FAILED] `new Document("$regex", myRegex)`
  * Result: "name": {"$regex": "/.*R.*/i"}}
* [SUCCESS] With workaround
  ```
  final String result = new String[]{new Document("$regex", myRegex).toJson()};
  regexFields.forEach(field -> {
            var matcher = Pattern.compile("(\"" + field + "\":.*\\/i\"\\})").matcher(result[0]);
            while (matcher.find()) {
                result[0] = result[0].replace(matcher.group(0), matcher.group(0).replace("\"", ""));
            }
        });
  ```
  * Result: name: {$regex: /.*R.*/I}}

**Comment by loicmathieu** [comment]
@YunaBraska sort is support on MongoDB with Panache, see https://quarkus.io/guides/mongodb-panache#sorting

You can create a sort with a Document based query also:

``̀`
MyEntity.find(new Document("name", "toto"), Sort.by("name"));
```

Be carefult this is the panache `Sort` class not a MongoDB one.

**Comment by loicmathieu** [comment]
@YunaBraska for the regex, we do have regex tests inside MongoDB with Panache, no using Document but string based query:

```
TestImperativeEntity entityWithUpperCase = new TestImperativeEntity("title11", "upperCaseCategory", "desc");
entityWithUpperCase.persist();
TestImperativeEntity.list("category like ?1", "upperCase.*"); // simple regex
TestImperativeEntity.list("category like ?1", "/uppercase.*/i"); // js regex
```

These will generates the following BSON queries:

```
{'category':{'$regex':'upperCase.*'}}
{'category':{'$regex':/uppercase.*/i}}
```

As you can see, the first is a String based regex, the second one what I called a JS regex which is not a String.

To use JS regex with a Document based query, you must use a Java Regex, you can find some information is this SO question: https://stackoverflow.com/questions/32714333/java-mongodb-regex-query/44730220

Note that Document based queries are provided as a convenience for user, the prefered way to run MongoDB queries is with string based queries so we will not extensively covers them as they work the same way than using the MongoDB driver directly.

**Comment by YunaBraska** [comment]
Hi @loicmathieu i can have a look again but as you see in my description, the Java Regex pattern was not working in the document based query

**Comment by YunaBraska** [comment]
@loicmathieu you can close this ticket as well. Its very hard to find how to do the regex queries at the best without much pain but in dynamic ways. My issue was that I was trying out so much things to get regex to work that i used in some queries BsonObjects and some Documents and some Strings. Documents are from my side the best way to do simple queries.

these things worked for me the best, maybe its worth to have such example in the documentation as well:
(i have spring boot background, never worked so close with the database)

### Solutions
Small with java support
```java
var query = new Document();
query.put(field, Pattern.compile(value, Pattern.CASE_INSENSITIVE));
//[...]
```


Long, ugly and hardcoded strings but works
```java
var query = new Document();
var regQuery = new Document();
regQuery.append("$regex", value);
regQuery.append("$options", "i");
query.put(field, value);
//[...]
```

### Sorting
my next thing is to find out how to do the sorting cause there is no method like `MyEntity.find(document, sort);`, its `MyEntity.find(document, document);`
what I do is `MyEntity.find(document.tojson(), sort);`

### Sorting small feature request
My query is pretty dynamic, same with the sorting order and fields. It would be cool If I can initiate an empty `Sort` to add my dynamic fields later on. Currently I wrote a wrapper for this...

```java
public static class Sortable {
        private Sort sort = null;

        public Sortable field(final String field) {
            return field(field, null);
        }

        public Sortable field(final String field, Direction direction) {
            if (direction != null) {
                if (sort == null) {
                    sort = Sort.by(field, direction);
                } else {
                    sort.and(field, direction);
                }
            }
            return this;
        }
//[...]
    }
```

**Comment by loicmathieu** [comment]
Glad you successfully make the regex work.

> there is no method like MyEntity.find(document, sort);

Yes there is one, it's here: https://github.com/quarkusio/quarkus/blob/85c2e7fb3377b1fa99f744dbe2243edd3b9fbc91/extensions/panache/mongodb-panache/runtime/src/main/java/io/quarkus/mongodb/panache/PanacheMongoEntityBase.java#L231

>  It would be cool If I can initiate an empty Sort to add my dynamic fields later on. 

I don't really understand how it will work, the Sort is dynamic as you can define it at query time. I'll close this issue, if you want to improve the Panache sorting capability please open a new issue (enhancement request) with some code exemple (API changes and usage exemples).

**Comment by YunaBraska** [comment]
@loicmathieu 

` public static <T extends PanacheMongoEntityBase> PanacheQuery<T> find(Document query, Document sort) { `
This is a document Sort not the sort you were telling me above with panache `Sort`

**Comment by loicmathieu** [comment]
Ah yes, I read it too quickly.
At the time we introduce Document variant for find, we found it more natural to offers Document type parameter to both the query and the sort as these methods are for complex use cases.
If you're using the Document based methods, you're back on the MongoDB API, no more the Panache API. This is the choice we made at this time.
