### ISSUE TITLE
Vertx-web App with code blocking event loop does not respond to SIGTERM

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1754]
An application using vertx-web, that blocks the event loop does not respond to a SIGTERM signal.  The application can only be stopped with a SIGKILL.

Is there anything we could do to intercept the signals and handle them correctly?

**Comment by vietj** [comment]
can you elaborate ?

an application usually blocks the event loop because of user code and not because of Vert.x code.

**Comment by mkouba** [comment]
@johnaohara BTW if a route handler blocks it should have `@Route.type()=BLOCKING`

**Comment by dmlloyd** [comment]
Normally `SIGTERM` (and all other signals) are handled via calling `System.exit(128 + sigNum)`.  This in turn triggers the app shutdown process.  I think the only piece that is missing is probably interrupting threads that are performing blocking operations (which can be a bit delicate but it's the only safe and universal way to indicate that a blocking operation should be cancelled).

**Comment by gsmet** [comment]
Closing, reopen if still an issue.
