### ISSUE TITLE
Continuous testing is inconsistent with resteasy-reactive

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#17540]
## Describe the bug
When using `resteasy-reactive`, I have 2 methods exposing rest and 2 unit tests (passing). Adding a space or a comment or even working code just to make the tests run again have no consistent results, totally randomly I get one of those  : 

- They are all green (expected behavior)
-  They all fail (restassured getting a 404 instead of a 200)
-  Only one test fails
- It detects only one test (and fails)   

### Expected behavior
The tests should behave the same if I don't change the code. 

## To Reproduce

https://github.com/sebastienblanc/testing-cr2/

1. `mvn quarkus:dev`
2.  change resteasy resource to trigger the tests
3. watch results (and repeat step 2) 

### Screenshots
![cr2bug1](https://user-images.githubusercontent.com/335133/120113047-feccc100-c178-11eb-937d-80f97ac8768a.png)
![bug2](https://user-images.githubusercontent.com/335133/120113059-0a1fec80-c179-11eb-9ced-1383e0c8e4b9.png)

### Output of `uname -a` or `ver`
Linux localhost.localdomain 5.10.15-200.fc33.x86_64
### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)

### Quarkus version or git rev
2.0.0.CR2 (but issue was also present on CR1)
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn

**Comment by geoand** [comment]
Does this happen by any chance in vcscode only?

**Comment by sebastienblanc** [comment]
That was the first thing I thought but also happens outside (meaning having the app running outside ina terminal and changing my code from vscode)

**Comment by geoand** [comment]
Does it happen if you change the code in any other IDE or editor?

Asking because we found an issue with annotation processing that was
specific to Vscode.

**Comment by sebastienblanc** [comment]
You're right ! It works with any other editor (I tested with vi ;) ). But I even need to close vscode complexly otherwise I still have the issue.

**Comment by geoand** [comment]
Thanks for the confirmation!

@n1hility spotted this a couple days ago and @FroMage is already aware of it, so we will have a fix for `2.0.0.Final`

**Comment by geoand** [comment]
This should be fixed by https://github.com/quarkusio/quarkus/pull/17503
