### ISSUE TITLE
Continuous testing: Support specifying unit, ITs, and QuarkusTests

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#17558]
## Description
The continuous testing feature suggests to activate the `dev`-mode testing based on different test scopes, currently *all*, *QuarkusTest*, or *unit*.

It would be helpful to make the distinction between *unit* test (how the Maven surefire plugin defines them, i.e. classes that end with `*Test`), *integration tests* (Maven failsafe integration tests, i.e. ending with `*IT`), and `QuarkusTest`.

Many projects make this distinction since Maven per default doesn't execute `IT`s, and thus projects include tests that, for example, require a running application. This would be very helpful to control in the `dev` mode -- at least by a configuration flag which tests should be auto-executed, or also by a control key.

This is somewhat connected to the bug in #17557.

**Comment by stuartwdouglas** [comment]
You can kinda do this at the moment by specifying quarkus.test.(include|exclude)-pattern to specify the file patterns to include or exclude.

The issue with just hard coding the maven rules is that they don't apply to gradle, and they are user customizable, so I am going to need to figure out some way to push this information down into the continuous testing code.

**Comment by sdaschner** [comment]
@stuartwdouglas Got it. Is that documented somewhere already?

**Comment by sdaschner** [comment]
+1 for excluding them by default, makes sense to me. But then that flag how to include them should be mentioned that at least in the next CR announcement :)

Is there a version I can test already?

**Comment by stuartwdouglas** [comment]
I have just changed the quarkus.test.exclude-pattern to default to the failsafe IT naming patterns. With the current master your example will run 2 tests, and re-run them as related classes are modified.

CR3 should be out soon with this fix.
