### ISSUE TITLE
Continuous testing: not all tests are re-run automatically

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#17557]
## Describe the bug
In `quarkus:dev` in `2.0.0.CR2`, not all tests are re-executed automatically on save, only `@QuarkusTest` annotated ones.

## To Reproduce

The Quarkus playground project contains a Maven plain unit test (`*Test`), an integration tests (`*IT`), and a `@QuarkusTest`.

- Project: https://github.com/sdaschner/quarkus-playground
- Run `quarkus:dev` and execute tests
- Change something in `src/main/java`
- Only 1 tests (`QuarkusTest`) is re-executed automatically

### Expected behavior

I expected all tests to be continuously re-executed -- or none at all.

Specifying `-Dquarkus.test.type=all` had no effect.

**Comment by stuartwdouglas** [comment]
It only re-runs changed and failing tests. It is mentioned here: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/continuous-testing.adoc#2-introduction

We use instrumentation to detect which tests cover which code so we don't waste time running irrelevant tests.

**Comment by stuartwdouglas** [comment]
Actually looks like something else is going on here

**Comment by sdaschner** [comment]
@stuartwdouglas Yes, in my case all the three tests failed equally... Looking forward to the PR :)
