### ISSUE TITLE
Different JSON-response when compiling to native image

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#1755]
**quarkus Version:**
0.11.0

**Java versions:**
* Oracle 1.8.0_191
* Oracle 11.0.2 2019-01-15

**GraalVM versions:**
* CE-1.0.0-RC12
* CE-1.0.0-RC13
* CE-1.0.0-RC14
* EE-1.0.0-RC12
* EE-1.0.0-RC14

**Expected behavior:**
Normal build and native image should create same JSON-response when REST-endpoint is called.

**Actual behavior:**
The JSON-responses differ.

**Description:**
The sample code can be found at https://github.com/turing85/quarkus-playground.

When built as `jar` and executed (`mvn clean package && java -jar target/dus.quarkus-1.0-SNAPSHOT-runner.jar`), the endpoint `http://localhost:8080/users` will produce

    [
        {
            "eMail": "alice@wonder.land",
            "name": "Alice",
            "uuid": 0
        },
        {
            "eMail": "bob@builder.com",
            "name": "Bob",
            "uuid": 13
        }
    ]

When built as native image and executed (`mvn clean package -Pnative && target/dus.quarkus-1.0-SNAPSHOT-runner`), the same endpoint will produce

    [
        {},
        {}
    ]

**Comment by marcinczeczko** [comment]
I think you're missing `@RegisterForReflection` annotation on `User` pojo.

**Comment by turing85** [comment]
Jup that fixes the issue. Thank you!

**Comment by gsmet** [comment]
@turing85 we add classes automatically for reflection if they are the return type of the REST endpoint but as long as you are using `Response`, we can't do that.

It's explained in more details here: https://quarkus.io/guides/rest-json-guide#about-serialization .
