### ISSUE TITLE
Can not override vertx-web configuration at runtime 

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1756]
configuration parameters for vertx-web can not be overridden at runtime, passing `-Dquarkus.vertx.http.host=0.0.0.0` to a vertx-web application does not change the host that the application binds to

**Comment by mkouba** [comment]
@johnaohara So it looks like it works as expected but the config key is `quarkus.vertx-http.host` (note the hyphen between `vetx` and `http`). I apologize for mystifying you ;-)

**Comment by johnaohara** [comment]
Thanks for clarifying
