### ISSUE TITLE
Option quarkus.websocket.dispatch-to-worker=true doesn't work anymore in Quarkus 1.13

### ISSUE THREAD

**Issue by Feavy** [quarkusio/quarkus#17571]
## Describe the bug
Setting the value of `quarkus.websocket.dispatch-to-worker` to `true` doesn't change anything. WebSockets remain on vert.x-eventloop threads.

### Expected behavior
WebSockets should be executed on executor threads (like in Quarkus 1.11).

### Actual behavior
WebSockets are executed on vert.x-eventloop threads instead of executor ones.

## To Reproduce

1. Start with Quarkus 1.13 WebSockets example code.
2. Add a log line in `SupersonicChatSocket#onOpen` like `LOG.info("I am a WebSocket!");`
3. Launch the program, go to http://localhost:8080, and connect with a username.
4. See in the console `2021-06-01 01:32:50,570 INFO  [org.acm.und.SupersonicChatSocket] (vert.x-eventloop-thread-11) I'm a WebSocket!` notice `vert.x-eventloop-thread-11`
5. Now, set the property `quarkus.websocket.dispatch-to-worker=true` in application.properties
6. Redo step 3 and 4 and observe that it still logs a `vert.x-eventloop-thread-X` thread.

You can do the same thing with Quarkus 1.11.3.Final, after setting the option to true you will see WebSocket is executed on an executor thread like it should be:

`2021-06-01 01:30:27,083 INFO  [org.acm.und.SupersonicChatSocket] (executor-thread-198) I am a WebSocket!`

**Comment by Feavy** [comment]
I think the problem came with this PR https://github.com/quarkusio/quarkus/pull/15068

**Comment by gsmet** [comment]
Yeah, I think https://github.com/quarkusio/quarkus/pull/17632 should fix it.

**Comment by Feavy** [comment]
Thank you! I use this option to be able to do blocking operations (like saving users' data in a database) as they are not allowed on IO threads.
I don't know if there is a better way to do it. I think it would be much better to only use a worker thread while doing blocking tasks, and remain on vertx threads for the rest. But I don't know how to do it.
