### ISSUE TITLE
ArC - rework the way the build profile/property producer beans are disabled

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#17583]
Currently, we add `@Alternative` and [remove `@AlternativePriority` if present](https://github.com/quarkusio/quarkus/pull/17570). However, if a user declares an `@Alternative` producer and enables it via `quarkus.arc.selected-alternatives` then `@UnlessBuildProperty` and friends would have no effect.

We could:
1. Remove `@Produces` and all scopes and known qualifiers/stereotypes (due to [Simplified Producer Method Declaration](https://quarkus.io/guides/cdi-reference#simplified-producer-method-declaration)), 
2. Remove all annotations (just in the context of `AnnotationStore`),
3. Introduce a new annotation, e.g. `@VetoedProducer` (note that `@javax.enterprise.inject.Vetoed` has `@Target({ ElementType.TYPE, ElementType.PACKAGE })`).

**Comment by manovotn** [comment]
> Introduce a new annotation, e.g. @VetoedProducer (note that @javax.enterprise.inject.Vetoed has @Target({ ElementType.TYPE, ElementType.PACKAGE })).

A bit outside of this question but do you think it would be worth it to expand CDI spec to allow usage of `@Vetoed` on methods/fields? I think it might be worth it.

Otherwise, option 3 sounds like a way to go.

**Comment by mkouba** [comment]
> A bit outside of this question but do you think it would be worth it to expand CDI spec to allow usage of `@Vetoed` on methods/fields? I think it might be worth it.

I'm not sure TBH. The original intent of `@Vetoed` was probably to exclude classes from an explicit bean archive (bean discovery `all`), i.e. those that would otherwise end up as `@Dependent` beans. For sure you can use it for tests etc. but the majority of use cases was probably different. See also https://issues.redhat.com/browse/CDI-50.
