### ISSUE TITLE
ConfigMapping maps some properties in a different way than ConfigProperties

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#17588]
UsefulLinks: 
- https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#smallrye-config
- https://quarkus.io/version/main/guides/config-mappings

Quarkus Version: Upstream (2.x)
Imagine that you have the following application.properies

```
vertx.kafka.producer.delay-ms=100
vertx.kafka.producer.batch-size=1
```

Using old `ConfigProperties` annotation, these properties must be mapped with the following class:

```
@ConfigProperties("vertx.kafka.producer")
public class VertxKProducerConfig {

    @ConfigProperty(name = "delayMs")
    public long delay;

    @ConfigProperty(name = "batchSize")
    public int batchSize;

}
```

Note: `delay-ms` property is mapped with a camelCase syntax 

Using `ConfigMapping` annotation, the mapped property must be exactly the same as it is in the application.properties

```
@ConfigProperty(name = "delay-ms")
    public long delay;
```

**Comment by pjgg** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Interesting.

Both `@ConfigProperties` and `@ConfigMapping` support a naming strategy and the default is `kebab-case` (property is derived by replacing case changes with a dash). 

Did you set `quarkus.arc.config-properties-default-naming-strategy` to something else?

Also, `@ConfigProperty` to change the name shouldn't work. You need to use `@WithName`.

**Comment by pjgg** [comment]
No, I didn't set any "naming strategy". So If the default is `kebab-case`  ConfigMapping should work with the above configuration isn't it? 

I mean if I have this property `vertx.kafka.producer.delay-ms=100` and this class:

```
@ConfigMapping("vertx.kafka.producer")
public class VertxKProducerConfig {

    @ConfigProperty(name = "delayMs")
    public long delay;
```

is expected to work?

**Comment by radcortez** [comment]
Not sure it this was a type (since the @ConfigMapping is being used in a class and it only support interface). This would be a possible way to map it:

```java
@ConfigMapping(prefix = "vertx.kafka.producer")
interface VertxKProducerConfig {
  long delayMs();
}
```

or 

```java
@ConfigMapping(prefix = "vertx.kafka.producer")
interface VertxKProducerConfig {
  @WithName("delayMs)
  long delay();
}
```

**Comment by pjgg** [comment]
thank you @radcortez 

This is not an issue is worked as expected.
