### ISSUE TITLE
Configure java agent for cloud remote debugging and set env var JAVA_OPTIONS_TOOL

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#17581]
## Description

I propose that we provide a new parameter/property able to configure the following ENV var for Cloud deployment of an application (and maybe for local remote debugging as syntax changes with JDK).
```
quarkus.kubernetes.env-vars.JAVA_TOOL_OPTIONS.value=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
```

We should offer the possibility for the user too to:  
- Enable or disable the `suspend=y|n` argument,
- Specify the external port to be used to access remotely the application (`e.g. nodePort: 31000`)
- Specify the url when they will use an ingress or openshift route if that works using such resource !!! (to be investigated)

Why ? 
- Without such an ENV var included within the Kubernetes Deployment generated by the Quarkus Kubernetes/Openshift extensions, it is needed that the user configure (= edit the file) manually before to deploy the kubernetes YAML/JSON resources
- The syntax of the javaagent to be configured is different between the JDK as described here https://dzone.com/articles/remote-debugging-java-applications-with-jdwp
- User does not know what should tbe the ENV VAR to be passed to the JDK container image as image used could be different between JIB, Buildpacks, S2I builds

**Comment by iocanel** [comment]
+1
