### ISSUE TITLE
Disable tests when running on SVM

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#1758]
For tests that are shared between JVM and Substrate (like our guide advises), some tests do not go through HTTP endpoints and do not therefore make sense in native mode, we should support a `@DisabledOnSubstrate` annotation to disable those tests only on SVM.

**Comment by cescoffier** [comment]
Great idea! I'm just facing this issue :-)

**Comment by FroMage** [comment]
Fixed!
