### ISSUE TITLE
quarkus:dev test run has assertions disabled

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#17586]
## Describe the bug
When running `mvn quarkus:dev` a test that fails with unmet assertion succeeds.

**Comment by geoand** [comment]
Do you have an example? Or a reproducer project?

**Comment by michalszynkiewicz** [comment]
Actually, while simplifying the reproducer I notices that `mvn clean package` also runs tests without assertions. 

This is my reproducer:
https://github.com/michalszynkiewicz/dev-mode-tests-error

**Comment by michalszynkiewicz** [comment]
It even has enabling assertions specified explicitly in the surefire plugin configuration...

**Comment by michalszynkiewicz** [comment]
This is what caused the problem during quarkus insights, I used `assert` in the newly added test, that's why it was reported successful.

**Comment by michalszynkiewicz** [comment]
one last thing :) it works as it should in IntelliJ

**Comment by geoand** [comment]
Oh, so you mean Java language assertions :).

You would need to run dev-mode like so: `mvn quarkus:dev -Djvm.args=-ea`

**Comment by geoand** [comment]
@stuartwdouglas should we enable `-ea` by default when running dev-mode?
That would certainly be a breaking change

**Comment by michalszynkiewicz** [comment]
there is one other issue closeby, assertions are ignored with `QuarkusTest`. I created https://github.com/quarkusio/quarkus/pull/17595 to fix this. 

For me, it would be much more intuitive to have assertions enabled in the dev mode tests.

**Comment by michalszynkiewicz** [comment]
Fixed with https://github.com/quarkusio/quarkus/pull/17595
