### ISSUE TITLE
Gson sub class deserialization is not working properly

### ISSUE THREAD

**Issue by nunomarks** [quarkusio/quarkus#17587]
## Describe the bug
From Quarkus 1.13.x on, we've been unable to deserialize a Json object to a subclass based on an attribute, using Gson. This behaviour was not verified previously (we've tested in Quarkus 1.10.x, 1.11.x and 1.12.x). We suspect that something related to reflection that has changed in this minor Quarkus version might be the cause of this issue.

### Expected behavior
Everything should go smoothly when deserializing.

### Actual behavior
An error occurs, such as:
```
Can not set org.acme.gson.reflection.model.Annotation field org.acme.gson.reflection.model.Document.annotation to org.acme.gson.reflection.model.ConcreteAnnotation
```

## To Reproduce

This project replicates the problem: https://github.com/nunomarks/quarkus-gson-test-project

For comparison, there are two tests, one as a regular Junit test (`ObjectConverterTest.fromJson()`), and an IT with `@QuarkusTest` annotation (`ObjectConverterQuarkusTest.fromJson()`). The former passes and the latter fails.

1. Checkout the repository
2. `mvn test`

Also, if you try the same procedure, but with, for instance, Quarkus 1.12.2, it works.

### Output of `uname -a` or `ver`
`Darwin CBR-MBP16-0037.Home 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

### Quarkus version or git rev
`1.13.x`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

### Additional Context
Any question me and @pedrolopix are here to answer

**Comment by nunomarks** [comment]
Any news on this ?

**Comment by nunomarks** [comment]
Tested with `2.0.0.Final`. It still happens.

**Comment by brunobat** [comment]
This is impacting production code. Prevents Quarkus upgrade.

**Comment by radcortez** [comment]
Let me have a look.

**Comment by radcortez** [comment]
This is a classloading issue, because subclasses of the model load in a different classloader, (while the main parent class of the model loads in the Quarkus classloader because it is referenced directly in the code). Because the main parent class and subclasses are in different classloaders you get the error.

To fix it just set `.overrideClassLoaders(Thread.currentThread().getContextClassLoader())` in the `ClassGraph()` builder.

**Comment by nunomarks** [comment]
> This is a classloading issue, because subclasses of the model load in a different classloader, (while the main parent class of the model loads in the Quarkus classloader because it is referenced directly in the code). Because the main parent class and subclasses are in different classloaders you get the error.
> 
> To fix it just set `.overrideClassLoaders(Thread.currentThread().getContextClassLoader())` in the `ClassGraph()` builder.

Everything worked as you mentioned. Thank you for your help.
