### ISSUE TITLE
Quarkus should simplify retrieving the client ip address

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#17594]
Currently, to retrieve the real client's ip address, I need to parse the info from the header like this:       

String forwardedForHeader = Objects.toString(routingContext.request().getHeader("X-Forwarded-For"), "");
String iAddress = forwardedForHeader.split(",")[0];

-
In Quarkus, Marcus would expect there'd be a better way than that! ;)

**Comment by maxandersen** [comment]
https://github.com/quarkusio/quarkus/issues/4922 Is related

**Comment by kenfinnigan** [comment]
Can't you do `((HttpServerRequest)routingContext.request()).remoteAddress().host()`?

**Comment by MarcusBiel** [comment]
No :)

**Comment by kenfinnigan** [comment]
Do you have a reason why? That's exactly how I'm setting the client IP on spans

**Comment by MarcusBiel** [comment]
I tested it, and I got the internal docker address, also, there can be a list of proxies in between:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by kenfinnigan** [comment]
Thanks, I will verify whether I have the same problem with spans

**Comment by stuartwdouglas** [comment]
So we have had support for this for a while, but it was just mentioned in the config properties, and only just was added to the guide: https://github.com/quarkusio/quarkus/blob/04f2041a004256dd0ed0799655d3ed378a61c48a/docs/src/main/asciidoc/http-reference.adoc#9-running-behind-a-reverse-proxy

If you set these properties then the above solution should work for you, as Quarkus will parse these headers and update the request.
