### ISSUE TITLE
ClassNotFoundException in a synthetic CDI event listener bean during tests

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#17626]
## Describe the bug

I have the following generated synthetic bean:
```java
import io.javaoperatorsdk.operator.Operator;
import io.javaoperatorsdk.operator.api.ResourceController;
import io.quarkus.arc.InjectableObserverMethod;
import io.quarkus.arc.impl.Mockable;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.util.function.Supplier;
import javax.enterprise.inject.spi.CDI;
import javax.enterprise.inject.spi.EventContext;

// $FF: synthetic class
public class DelayedController_registration_observer_Observer_Synthetic_72068acb5d6c55856271762a728e4a61279251eb implements InjectableObserverMethod, Mockable {
    private final Type observedType;
    private volatile boolean mock;
    private final Supplier declaringProviderSupplier;

    public DelayedController_registration_observer_Observer_Synthetic_72068acb5d6c55856271762a728e4a61279251eb() {
        ClassLoader var1 = Thread.currentThread().getContextClassLoader();
        Class var2 = Class.forName("io.quarkiverse.operatorsdk.it.DelayedController$RegisterEvent", (boolean)1, var1);
        this.observedType = (Type)var2;
        this.mock = (boolean)0;
    }

    public Type getObservedType() {
        return this.observedType;
    }

    public Class getBeanClass() {
        return DelayedController_registration_observer.class;
    }

    public void notify(EventContext var1) {
        if (!this.mock) {
            CDI var2 = CDI.current();
            Annotation[] var3 = new Annotation[0];
            Operator var5 = (Operator)var2.select(Operator.class, var3).get();
            Annotation[] var4 = new Annotation[0];
            ResourceController var6 = (ResourceController)var2.select(DelayedController.class, var4).get();
            var5.register(var6);
        }
    }

    public String getDeclaringBeanIdentifier() {
        return null;
    }

    public void arc$clearMock() {
        this.mock = (boolean)0;
    }

    public void arc$setMock(Object var1) {
        this.mock = (boolean)1;
    }
```

This bean is used during an integration test that emits a CDI event to trigger the bean's `notify` method, which fails with the following exception:

```java
Caused by: java.lang.NoClassDefFoundError: io/quarkiverse/operatorsdk/it/DelayedController
        at io.quarkiverse.operatorsdk.it.DelayedController_registration_observer_Observer_Synthetic_72068acb5d6c55856271762a728e4a61279251eb.notify(DelayedController_registration_observer_Observer_Synthetic_72068acb5d6c55856271762a728e4a61279251eb.zig:115)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:264)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
```

The same code works without issue on 1.13.6.

### Expected behavior
No exception while running the tests.

### Actual behavior
Exception while running the tests. :(

## To Reproduce

Build https://github.com/quarkiverse/quarkus-operator-sdk/pull/56 using `mvn clean package`, the build will fail in the `integration-tests` module.

**Comment by mkouba** [comment]
Hm, the generated class from the snippet above does not represent a synthetic bean but a _synthetic observer method_. And the `getBeanClass()` method seems to return a non-existent class - `DelayedController_registration_observer.class`. Note that the bean class is used to determine whether the generated observer method is "bound" to an application class, i.e. it determines which [classloader should be used in the dev mode](https://quarkus.io/guides/class-loading-reference#classloader-implementations).

When I change [this line](https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java#L199) to `.beanClass(info.name())` the test seems to pass.

I have no idea how this could work in previous versions...

**Comment by metacosm** [comment]
I didn't write the original code and I'm not super familiar with CDI so I can't tell you why it worked before… 😓 
But it does seem to work now, which is great! 
Thank you.

**Comment by mkouba** [comment]
> I didn't write the original code and I'm not super familiar with CDI so I can't tell you why it worked before… sweat
> But it does seem to work now, which is great!
> Thank you.

Not at all. Thanks for verifying the fix ;-).
