### ISSUE TITLE
Switching from Quarkus 1.x to 2.0.0.CR2 breaks for JWTs without issuedAt (iat) claim

### ISSUE THREAD

**Issue by xwoker** [quarkusio/quarkus#17622]
## Describe the bug

After switching from Quarkus 1.13.6.Final to 2.0.0.RC2 my jwt validation failed with a "iat" missing message. It seems that previously this optional field in an JWT as considered optional, with the change to 2.0.0 it became mandatory.

### Expected behavior

I expect that quarkus processes jwts without issuedAt as valid.

### Actual behavior

JWTs without issuedAt are considered invalid:

```
2021-06-02 10:25:22,740 DEBUG [io.sma.jwt.aut.principal] (vert.x-eventloop-thread-0) SRJWT08004: Token is invalid
2021-06-02 10:25:22,741 DEBUG [io.qua.sma.jwt.run.aut.MpJwtValidator] (vert.x-eventloop-thread-0) Authentication failed: io.smallrye.jwt.auth.principal.ParseException: SRJWT07000: Failed to verify a token
	at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parseClaims(DefaultJWTTokenParser.java:160)
	at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parse(DefaultJWTTokenParser.java:56)
...
Caused by: org.jose4j.jwt.consumer.InvalidJwtException: JWT (claims-> ...) rejected due to invalid claims or other invalid content. Additional details: [[3] No Issued At (iat) claim present.]
```

## To Reproduce

1. Use Quarkus 2.0.0.CR2 and process an JWT without issuedAt claim.
2. You should get an error that the JWT is invalid.

### Configuration

# Add your application.properties here, if applicable.

### Screenshots

(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`

Darwin e210-4.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev

2.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@xwoker Hi, `iat` is a required claim in MP JWT `1.2` since without it it is impossible to restrict it is time to live limit. 

Which party is issuing the token ? Is it done in your own client code ? Or by 3rd party tool you can't control ?

**Comment by sberyozkin** [comment]
It was also required in MP JWT 1.1.1 as far as I recall but it was not enforced

**Comment by xwoker** [comment]
Unfortunately, It's a 3rd party tool I can't control. 

Thanks for pointing out the changes in the MP JWT 1.2 (https://download.eclipse.org/microprofile/microprofile-jwt-auth-1.2/microprofile-jwt-auth-spec-1.2.html#_requirements_for_rejecting_mp_jwt_tokens and https://download.eclipse.org/microprofile/microprofile-jwt-auth-1.2/microprofile-jwt-auth-spec-1.2.html#_required_mp_jwt_claims). I wasn't aware of it.

I guess I will be staying with Quarkus 1.x for some the foreseeable future until the 3rd party will provide an iat as part of the token.

BTW, great response time! Appreciate that! And quarkus is a great platform.

**Comment by sberyozkin** [comment]
@xwoker if it is a case of a 3rd party issuer which does not set an issued at claim and there is no way it can be changed to set this claim then I can consider adding a smallrye-jwt property to control it, I'll open an issue

**Comment by sberyozkin** [comment]
@xwoker Indeed it was required even in `MP JWT 1.1.1` but there was an agreement to start actually enforcing some of the very essential claims were set in `1.2`

**Comment by sberyozkin** [comment]
Please watch https://github.com/smallrye/smallrye-jwt/issues/469

**Comment by brunobat** [comment]
The smallrye issue was solved and it would be nice to include the fix in the next quarkus...

**Comment by sraturi** [comment]
Did adding `smallrye.jwt.time-to-live=-1` to application properties work for folks? I added this in my application.properties and can initially see [maxTimeToLiveSecs](https://github.com/smallrye/smallrye-jwt/blob/cc849ac94ccf8f9913e79738d003da503fe80db3/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java#L188) being set to -1  in the debugger. However, when `jtwparser` tries to [verify](https://github.com/smallrye/smallrye-jwt/blob/main/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java#L70) , it copies over the `JWTAuthContextInfo` which has [maxTimeToLiveSec](https://github.com/smallrye/smallrye-jwt/blob/cc849ac94ccf8f9913e79738d003da503fe80db3/implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java#L98) set to null. 

I am using quarkus `2.6.1.Final`

**Comment by gsmet** [comment]
@sraturi please ask your question here: https://github.com/quarkusio/quarkus/discussions/categories/q-a . Commenting on old issues is easy to miss for us. Thanks!

**Comment by sraturi** [comment]
Posted it in the QA, putting here for reference

https://github.com/rapidrobotics/platform/pull/1195#discussion_r780574606

**Comment by sraturi** [comment]
Posted it in the QA, putting here for reference

https://github.com/quarkusio/quarkus/discussions/22736
