### ISSUE TITLE
RESTEASY002160 warning when starting an application with @RegisterRestClient

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#17627]
## Describe the bug

Developing an application with a `@RegisterRestClient` prints out the following warning:

```
2021-06-02 13:52:24,412 WARN  [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002160: Provider instance org.jboss.resteasy.microprofile.client.publisher.MpPublisherMessageBodyReader is already registered.  2nd registration is being ignored.
```

### Expected behavior

No warning.

### Actual behavior

Warning printed out.

## To Reproduce

* Run the [QUARKUS - USING THE REST CLIENT](https://quarkus.io/guides/rest-client) guide
* Start the application
* execute `curl http://localhost:8080/country/name/greece`

You will see the warning.

### Configuration

as documented in the guide.

### Quarkus version or git rev

`2.0.0.CR2`

**Comment by geoand** [comment]
I will take a look

**Comment by geoand** [comment]
@radcortez it seems like `QuarkusRestClientBuilder` which you added for supporting MP 4 is registering `MpPublisherMessageBodyReader`, but that provider is also being picked up (due to the `@Provider` annotation) in `ResteasyCommonProcessor#setupProviders`.

I wonder if we should just skip the registration in the latter case when the MP Client capability is present...

**Comment by radcortez** [comment]
Is registration automatic? Don't you need a `@RegisterProvider` in the REST Client case?

**Comment by geoand** [comment]
It gets registered with RESTEasy because it handles both the server and client providers in the same way.

**Comment by radcortez** [comment]
Feel free to remove one of the registrations. The code I added is mostly a copy from RESTEasy and it was the only way to pass in our own custom CDI injector. I guess that I should have also submitted a PR to make that more extendable on the RESTEasy to remove the unnecessary Quarkus code. In that case, I believe we probably need to filter out on the Processor side.
