### ISSUE TITLE
Vertx web client uses single thread causing performance issues

### ISSUE THREAD

**Issue by AntonFagerberg** [quarkusio/quarkus#17631]
I've been investigating performance issues in our application and I've found something I think looks really strange. I've created a small example which I believe reproduces this problem.

My test resource looks like this:

```java
import static org.jboss.logging.Logger.getLogger;

import java.time.Duration;
import java.util.UUID;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

import org.jboss.logging.Logger;

import io.smallrye.mutiny.Uni;
import io.vertx.core.json.JsonArray;
import io.vertx.ext.web.client.WebClientOptions;
import io.vertx.mutiny.core.Vertx;
import io.vertx.mutiny.ext.web.client.HttpResponse;
import io.vertx.mutiny.ext.web.client.WebClient;

@Path("test")
public class TestResource {

    @Inject
    Vertx vertx;

    WebClient client;

    private static final Logger LOG = getLogger(TestResource.class);

    @PostConstruct
    void init() {
        client = WebClient.create(vertx, new WebClientOptions()
                .setDefaultHost("localhost")
                .setDefaultPort(8080));
    }

    @GET
    @Path("/1")
    public Uni<JsonArray> test1() {
        var id = UUID.randomUUID();
        LOG.infof("start: " + id);
        var startTime = System.currentTimeMillis();

        return client
                .get("/test/2")
                .send()
                .map(HttpResponse::bodyAsJsonArray)
                .map(result -> {
                    LOG.info("done: " + id + " " + (System.currentTimeMillis() - startTime));
                    return result;
                });
    }

    @GET
    @Path("/2")
    public Uni<JsonArray> test2() {
        return Uni.createFrom()
                .item(JsonArray::new)
                .onItem()
                .delayIt()
                .by(Duration.ofSeconds(1));
    }

}
```

(I've been following this guide for creating the Vertx client: https://quarkus.io/guides/vertx#using-vert-x-clients)

The resource has two end-points.

`/test/2` will respond with an empty Json array after 1 second delay.
`/test/1` will call `/test/2` over HTTP using the Vertx client.

(I believe this issue can be reproduced using external URLs but this will make it more consistent.)

If I call the `/test/1` end-point using cURL locally a few times manually:

```
curl --location --request GET 'http://localhost:8080/test/1'
```

The log looks like this:
```
(vert.x-eventloop-thread-4) done: feb5f22f-1b28-412c-bb58-3415838904a9 1178
(executor-thread-1) start: 0d9e0553-5750-4799-bca0-0370de9fe73e
(vert.x-eventloop-thread-4) done: 0d9e0553-5750-4799-bca0-0370de9fe73e 1010
(executor-thread-1) start: abc546bc-2e74-45e2-b6d6-a31cf4920fff
(vert.x-eventloop-thread-4) done: abc546bc-2e74-45e2-b6d6-a31cf4920fff 1007
```

Each request will respond in roughly 1 second (the last number, 1178, 1010, 1007, is the millisecond response time).

Now I'm using a script to do the same thing 20 times concurrently:

```sh
for ((i = 0 ; i < 20 ; i++)); do
	curl --location --request GET 'http://localhost:8080/test/1' &
done
```

Here's the output, broken down into a few pieces with comments:

All requests start at the same time and they use different executor-threads:
```
(executor-thread-5) start: aac8493e-1b5f-4ab0-ace4-e79fb1300dd8
(executor-thread-4) start: b5e0c184-1e10-4f3b-97d7-405f9ef194e3
(executor-thread-1) start: a2c7295e-9125-496a-ad2a-483b1497eedf
(executor-thread-2) start: f87996df-9aa4-440d-8020-1ac4c7bade87
(executor-thread-5) start: fe3a5cff-2a58-4a0b-a792-4946c1483f02
(executor-thread-7) start: 467c0d55-8915-4497-a693-b3a731a268e8
(executor-thread-6) start: a3ae46ce-bb63-48af-8eb3-ae597d87d928
(executor-thread-3) start: 9f937923-ba29-49cb-952e-662680bdb330
(executor-thread-2) start: 067f594a-4dd7-4321-9647-177ca6ed6521
(executor-thread-8) start: 1f2e2aa0-7387-4ce0-8512-3ee21e697fe2
(executor-thread-7) start: 66bb3e81-5c54-40ad-a1ce-d1473eb7c615
(executor-thread-6) start: 6d418df3-6176-46d9-97b0-7742f7cbb7cc
(executor-thread-8) start: 72f095cf-1a30-4fba-82de-3c1dae0b23ac
(executor-thread-8) start: 65b15b17-bdf4-4c30-9ca9-399796120848
(executor-thread-2) start: d736ef00-8a7b-419c-af6f-1fff644ca5af
(executor-thread-4) start: 9175737d-9e06-42dd-b7d6-c59e5158f47c
(executor-thread-5) start: e77820dd-688e-4914-9c98-9e30b30cdd70
(executor-thread-2) start: 8d833b12-4a72-4290-86d3-961babc7cbff
(executor-thread-2) start: b00a042e-6103-4bd3-8c44-c558d8557275
(executor-thread-5) start: cf543e9b-0de7-4e35-95e5-b92e29abbaec
```

But there is some kind of blocking causing the response times to increase from 1  to 4 seconds: 
(Not the parallelism that I would expect.)

```
(vert.x-eventloop-thread-4) done: a2c7295e-9125-496a-ad2a-483b1497eedf 1013
(vert.x-eventloop-thread-4) done: aac8493e-1b5f-4ab0-ace4-e79fb1300dd8 1016
(vert.x-eventloop-thread-4) done: f87996df-9aa4-440d-8020-1ac4c7bade87 1017
(vert.x-eventloop-thread-4) done: b5e0c184-1e10-4f3b-97d7-405f9ef194e3 1022
(vert.x-eventloop-thread-4) done: fe3a5cff-2a58-4a0b-a792-4946c1483f02 1021
(vert.x-eventloop-thread-4) done: a3ae46ce-bb63-48af-8eb3-ae597d87d928 2021
(vert.x-eventloop-thread-4) done: 467c0d55-8915-4497-a693-b3a731a268e8 2024
(vert.x-eventloop-thread-4) done: 9f937923-ba29-49cb-952e-662680bdb330 2026
(vert.x-eventloop-thread-4) done: 067f594a-4dd7-4321-9647-177ca6ed6521 2028
(vert.x-eventloop-thread-4) done: 1f2e2aa0-7387-4ce0-8512-3ee21e697fe2 2027
(vert.x-eventloop-thread-4) done: 72f095cf-1a30-4fba-82de-3c1dae0b23ac 3025
(vert.x-eventloop-thread-4) done: 6d418df3-6176-46d9-97b0-7742f7cbb7cc 3031
(vert.x-eventloop-thread-4) done: 66bb3e81-5c54-40ad-a1ce-d1473eb7c615 3034
(vert.x-eventloop-thread-4) done: d736ef00-8a7b-419c-af6f-1fff644ca5af 3031
(vert.x-eventloop-thread-4) done: 65b15b17-bdf4-4c30-9ca9-399796120848 3032
(vert.x-eventloop-thread-4) done: 8d833b12-4a72-4290-86d3-961babc7cbff 4031
(vert.x-eventloop-thread-4) done: 9175737d-9e06-42dd-b7d6-c59e5158f47c 4033
(vert.x-eventloop-thread-4) done: e77820dd-688e-4914-9c98-9e30b30cdd70 4034
(vert.x-eventloop-thread-4) done: cf543e9b-0de7-4e35-95e5-b92e29abbaec 4034
(vert.x-eventloop-thread-4) done: b00a042e-6103-4bd3-8c44-c558d8557275 4035
```

Also, every subsequent request I make will use the same thread, vert.x-eventloop-thread-4.

Now I change my code so that the request method will create a new client every time:

```java
return WebClient.create(vertx, new WebClientOptions()
        .setDefaultHost("localhost")
        .setDefaultPort(8080))
        .get("/test/2")
        .send()
        .map(HttpResponse::bodyAsJsonArray)
        .map(result -> {
            LOG.info("done: " + id + " " + (System.currentTimeMillis() - startTime));
            return result;
        });
}
```

And now I get this output:
```
(vert.x-eventloop-thread-18) done: e37a2c67-0695-4d29-ab29-920d44ae24f9 1020
(vert.x-eventloop-thread-0) done: b025a7d8-e6ac-442a-94b3-98506f45da1b 1016
(vert.x-eventloop-thread-4) done: cd8f22ea-27c5-4565-9cb5-67d09fa40b0f 1015
(vert.x-eventloop-thread-9) done: bccd7d6a-2c92-4d9e-842e-c8287539994f 1017
(vert.x-eventloop-thread-15) done: 7caac495-7c45-4c15-939f-757cbd451727 1011
(vert.x-eventloop-thread-23) done: 0bd40f95-4991-4ac0-b830-8ac968d9a9f6 1012
(vert.x-eventloop-thread-3) done: 0da22fa9-e068-4ff2-aa9c-b6a519c77ad0 1018
(vert.x-eventloop-thread-15) done: 92fa0570-eb81-49cf-ba6e-86f01f90319e 1010
(vert.x-eventloop-thread-13) done: 8d78c7f8-e4d8-4740-ad0f-2bdede024e23 1010
(vert.x-eventloop-thread-21) done: e9113068-6634-455e-aace-5d1051309f8e 1010
(vert.x-eventloop-thread-6) done: ba532fbb-fc1f-4ee3-b8e4-fcac08ab974f 1009
(vert.x-eventloop-thread-10) done: dbc2781e-1734-450d-9da5-d09250d87d3d 1011
(vert.x-eventloop-thread-18) done: 08fab211-b537-460d-81e4-a209203109aa 1009
(vert.x-eventloop-thread-22) done: 17620266-d3f5-4b4d-ae4c-92eace2614af 1008
(vert.x-eventloop-thread-5) done: 1ca017d4-2ad1-429e-b7ba-45d0b76b3429 1007
(vert.x-eventloop-thread-15) done: cb2d4f85-1aaa-40a1-951b-32533f28d81d 1006
(vert.x-eventloop-thread-10) done: dbbc833a-4387-4c1a-b9b0-3a8f757cc497 1007
(vert.x-eventloop-thread-4) done: 27d206d7-865c-45ad-b0c0-bea977f6d3be 1006
(vert.x-eventloop-thread-3) done: c38b5c75-321b-42f6-9af3-74ce472fbfce 1006
(vert.x-eventloop-thread-8) done: ace60e8d-9754-44ec-8db0-832bbf82347d 1005
```

All requests done in 1 second (and they all use different threads).

When the application starts up, I can see that it will create 24 vert.x-eventloop-thread-X threads, but it seems as each client instance is bound to just a single thread.

This is tested using Quarkus 1.13.6 (running with profile "prod") on MacOS Big Sur (11.4).
The example is tested on Java 11 and Java 16 with the same result. (Built with Java 11 SDK.)
I'm using Gradle 6.7.

**Comment by geoand** [comment]
Have you tried increasing the `maxPoolSize` option (see https://vertx.io/docs/apidocs/io/vertx/ext/web/client/WebClientOptions.html)?

The default is set to 5, which means that the WebClient will not allow more than 5 in flight requests per host

**Comment by sberyozkin** [comment]
`quarkus-oidc-client` (and other extensions depending on it) should probably have the configuration options to increase it

**Comment by geoand** [comment]
@sberyozkin that sounds like a very good idea. 
IMHO, any extension that uses the Vert.x Web Client and expects to hit a single host a lot, should probably have this value configured higher by default

**Comment by sberyozkin** [comment]
> should probably have this value configured higher by default

Good point, yes, will take of the OIDC extensions

**Comment by AntonFagerberg** [comment]
@geoand thanks for the reply, that makes sense and I can confirm that I get the same response time when increasing it.

I'm still a bit confused though why the thread vert.x-eventloop-thread-X is always the same? It's probably not a big problem since the requests are non-blocking / async but all computations on the result following it seems to be using the same thread as well(?). I'm thinking that if we do some heavy json conversions / computations or similar, then it will essentially "block" all other requests until that computation is done. If we have a lot of requests at the same time, I guess this would have at least some performance impact?

**Comment by geoand** [comment]
@AntonFagerberg that is how Vert.x (and other non-blocking libraries / toolkits) work. The use a very small number of threads (could even be just one) and perform all IO operations on that thread. 
That obviously means that the all operations must be very quick - meaning that you can't perform blocking IO and you can't run heavy CPU bound processing, otherwise the system will be unable to process other requests.

Having an entire request processing be performed in this way, means that the least possible system resources are used and there are no extensive hand-offs to other threads.

**Comment by AntonFagerberg** [comment]
@geoand Yes, I understand the how non-blocking works :), and I'm not talking about real blocking IO. But I mean, there's a reason why all incoming requests use different threads (in a very small and limited thread pool) and Quarkus isn't configured to run on a single thread - because there is a performance benefit in having at least the same number of threads as cores (roughly speaking). The computations are fast and non-blocking, but they still take some time to do small computations.

So why is the Vertx client different in this regard? Wouldn't there be a performance benefit in Vertx using more threads than one? It is creating a thread pool with 24 threads, so why is it still only using one in my example?

**Comment by geoand** [comment]
Quarkus and Vert.x will use all the available event loop threads.

In your case you are likely observing thread affinity behavior of Vert.x and thus seeing the same thread being used.

**Comment by AntonFagerberg** [comment]
@geoand thanks for the help, I will read more about it to see what's up :)

**Comment by geoand** [comment]
You are welcome!

**Comment by AntonFagerberg** [comment]
@geoand I'll continue here even though this issue is closed, I hope you don't mind!

The issue with the slow response times has been solved but I want to continue understanding why the same thread is used.

I've been reading more about how Vert.x works and I don't think my issue is caused by thread affinity as you mentioned. 

In the Vertx mailing group I found this quote:

> When the WebClient is created, Vert.x will check if the calling thread is a Vert.x event loop. As in your case it's not, it will assign one to the WebClient client instance. Then the WebClient results will be emitted on this event loop.

[source](https://groups.google.com/g/vertx/c/LXVr8Zqu_XE/m/ZpJdQIHmAQAJ)

There's also this note on the Vertx website:

> Even though a Vertx instance maintains multiple event loops, any particular handler will never be executed concurrently, and in most cases (with the exception of&nbsp;worker verticles) will always be called using the exact same event loop.

[source](https://vertx.io/docs/vertx-core/java/#_reactor_and_multi_reactor)

So the model is built on many event loops, but the web client will only use one of them (i.e. one thread).

How does it scale then?

> Verticles are chunks of code that get deployed and run by Vert.x. A Vert.x instance maintains N event loop threads (where N by default is core*2) by default. [...] An application would typically be composed of many verticle instances running in the same Vert.x instance at the same time.

[source](https://vertx.io/docs/vertx-core/java/#_verticles)

As I understand it, the way you scale Vertx is by deploying multiple "verticles" in your application. The general recommendation seems to be that you should also create (at least) one new web client for each verticle. 

This seems (to me) not to really fit into the Quarkus model of working. In Quarkus, you create one application into which all incoming requests will go into different threads (in a limited pool based on the cores) for maximum performance. But if I only create one Vertx web client, which is reasonable, then all requests made by that client is going to use the same single thread every time. Essentially, if every end-point in my Quarkus application makes a request to an external service using the web client, then it's effectively limited by a single core on my server.

The only way I can think of to get around this would either be to get rid of Vertx web client and use something else which seems unfortunate, or maintain a pool of Vertx web clients matching the cores on my server.

**Comment by geoand** [comment]
I'll defer this one to @cescoffier

**Comment by cescoffier** [comment]
The web client will use the event loop it got created on. This avoids many concurrency issue. So, callbacks will always happen on that thread. Multi threading will not help, it may actually get worse. Note that I mention the callback. So if your callback is expensive, maybe you need to offload that part. 

Also, if the problem is a concurrency limit, the web client is limiting the number of connection per server to 5 by default. Did you try to increase this settings?

**Comment by AntonFagerberg** [comment]
@cescoffier Yes, we tried to increase the number of connections and it solved my initial performance issue. What I'm talking about here is mainly a theoretical problem as of now. We don't have that much traffic.

What I'm doing is essentially building an API-gateway. All end-points will work like this:

incoming request -> make N http requests to other servers -> transform json -> reply

My issue is with the comment: "The web client will use the event loop it got created on."
It makes total sense in Vert.x but to me it seems flawed in Quarkus since there won't be any different event loops handling the incoming requests.

If I break down my scenario above, this is how it would work:

- incoming request: will be executed on a thread in the pool (executor-thread-X), but not any of the Vert.x event loop threads (vert.x-eventloop-thread-X).
- make N http requests to other servers: all requests will use the same Vert.x web client. When the client is created, an event loop thread will be assigned to it and all subsequent calls will use that same single thread. It would be fine for one incoming request to use that thread for all outgoing requests, my problem is that all other incoming requests will also use that single thread.

This means that if I deploy my Quarkus application on a 128 core machine (to exaggerate my point), it will essentially only make use of one thread for almost all work. If I get 1000 requests per second to my service, the 1000 requests will end up in different threads from the incoming request thread pool (executor-thread-[1 to X]), but will then all end up in the single Vert.x web client thread for all work done (vert.x-eventloop-thread-1) and all other (vert.x-eventloop-thread-[2 to 256] spawned at startup) will do nothing ever and just "waste" resources. It's not a problem unless we have a lot of traffic, especially since it's non-blocking, but for a high performance system it must be a bit of a bottle neck at least? It's the difference why you deploy multiple Node.js servers on one machine, multiple verticles in a Vertx server on a machine, but just a single Quarkus server on a machine.

(And I assume the same problem would be if you at the start of each incoming request make a call to some auth service for example.)

To contrast this with, for example, DynamoDB. If I use that async / non-blocking client, it will (I believe) maintain a thread pool and every incoming request will be divided between those threads in that pool - making full use of the CPU cores.

I guess there's not much to do about it since that's the way Vert.x work. Or am I wrong in my thinking? Is it something you have considered in Quarkus?
