### ISSUE TITLE
GraphQL handler blows up if request contains newline breaks

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#17667]
## Describe the bug
When an incoming GraphQL query contains newline characters, the JSON parser that parses it blows up.

### Expected behavior
Request with newlines is parsed, the newlines ignored

### Actual behavior
The request processing blows up on something like
```
javax.json.stream.JsonParsingException: Unexpected char 10 at (line no=1, column no=19, offset=18)
```
where the "char 10" is a newline character

**Comment by hantsy** [comment]
Reproducer https://github.com/hantsy/quarkus-sandbox/blob/master/graphql-client/src/main/java/com/example/demo/JvmClient.java#L32 and related backend project https://github.com/hantsy/quarkus-sandbox/blob/master/graphql

**Comment by jmartisk** [comment]
Ok, so the problem here is that the observed behavior is correct from the PoV of the JSON specification, which does not allow line breaks inside strings.
It works correctly even if you send a query containing line breaks, but they must not be inside a JSON string. Instead of a line break, there must be `\n`.

Works:
```
{ "query": 
        "{people {name gender}}"                                                                             
}
```

Does not work:
```
{ "query": 
        "{people { 
		name 
		gender
	  	}
	}"                                                                             
}
```

Unfortunately when using a Java text block, the line breaks are included in the resulting string.
So if we want to seamlessly support text blocks, even though it it is against the JSON specification, we could potentially run the incoming JSON through something that strips away the line breaks, and probably also tab characters. Stripping them from just JSON strings would be a bit more difficult, I think we could remove them from the whole JSON document, because IIUC line breaks in JSON don't play any role.
If the user needs to use a real line break or tab inside a GraphQL variable or something, they will simply use properly escaped `\n` or `\t`, that will not be stripped away.
I'll come up with a PR for this and let's see
