### ISSUE TITLE
Quarkus bundles generated projects with maven wrapper 3.6.3

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#17668]
## Describe the bug
Project from code.quarkus.io and projects generated via mvn io.quarkus:quarkus-maven-plugin:1.13.6.Final:create still bundles with maven wrapper in version 3.6.3

According to https://github.com/quarkusio/quarkus/pull/16249 the shift to maven 3.8.1 was done

### Expected behavior
Maven wrapper 3.8.1 is bundled

### Quarkus version or git rev
1.13.x

**Comment by famod** [comment]
I suppose something has to be changed in https://github.com/quarkusio/code.quarkus.io @ia3andy @gsmet?
I'm not failiar with that repo.

**Comment by geoand** [comment]
Would https://github.com/quarkusio/quarkus/pull/17688 not do the trick?
