### ISSUE TITLE
Native image build fails on windows 10

### ISSUE THREAD

**Issue by efrancis59** [quarkusio/quarkus#17665]
## Describe the bug
I get error messages when I try to build a native executable on windows 10 

### Expected behavior
Build must complete without any problem

### Actual behavior
The build process stops and displays error messages.  
Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: Fold invokes should no longer exist....

## To Reproduce
1. Generate a minimal project on https://code.quarkus.io/
2. Download it and unzip it
3. In the project directory, use the command explained in this page to start the build process : https://quarkus.io/guides/building-native-image The command is below :

`cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && mvn package -Pnative'`

### Configuration
The application.properties file is empty

### Screenshots
![Screenshot 2021-06-03 131120](https://user-images.githubusercontent.com/14142333/120635943-5155f800-c46d-11eb-9697-a4e437d5acee.png)

## Environment (please complete the following information):
Microsoft Windows 10 Professional
Version : 10.0.19043 Build 19043

### Output of `java -version`
`openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)`

### Quarkus version or git rev
1.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context
The complete build output is in the attached log.txt file
[log.txt](https://github.com/quarkusio/quarkus/files/6591274/log.txt)

**Comment by gsmet** [comment]
With 1.13, you should use GraalVM 21.0.

GraalVM 21.1 will be supported by Quarkus 2.0.
