### ISSUE TITLE
Vertx Redis client configuration via Quarkus properties

### ISSUE THREAD

**Issue by pokusak** [quarkusio/quarkus#17673]
## Description

Quarkus 2.x uses Vertx 4.x which provides Redis client which provides more features than exposed via Quarkus configuration options. It would be great to configure features like TLS or AUTH (possibly others) directly via Quarkus configuraiton properties to avoid manual configuration of Redis client used by Vertx used by Quarkus. 

Functionality is already provided by existing code as discussed in #13161. This enhancement is only about configuration propagation from Quarkus to Vertx Redis client.

**Comment by machi1990** [comment]
Thanks @pokusak for opening the issue. It should be relative straight forward, do you want to take a look at it?

**Comment by antoniodvr** [comment]
@machi1990 I can take it!

**Comment by machi1990** [comment]
@antoniodvr thanks. Consider the issue yours, ping me in case of anything or you want an early review /feedback on the PR.

**Comment by cescoffier** [comment]
Fixed by #17714
