### ISSUE TITLE
Can not mock non-static persist method on PanacheEntityBase

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#17697]
## Describe the bug
In Quarkus `2.0.0.CR3` (an most likely in `1.13.x`) using Panache reactive I am not able to mock the non-static methods on `PanacheEntityBase` (`persist()` for example - I haven't tried the others). Mockito does not allow you to mock them because Mockito requires an instance in `Mockito.when`/`Mockito.doReturn(..).when`.. `PanacheMock` does not seem to work either.

## To Reproduce
I've attached a reproducer project: 
[panache-reactive-activerecord-persist-mock.zip](https://github.com/quarkusio/quarkus/files/6599269/panache-reactive-activerecord-persist-mock.zip)

### `src/main/java/org/acme/rest/FruitResource.java`
```java
@Path("/fruits")
public class FruitResource {
	@POST
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	public Uni<Fruit> addFruit(@Valid Fruit fruit) {
		return Panache.withTransaction(() -> fruit.persist());
	}
}
```

### `src/test/java/org/acme/rest/FruitResourceTests.java`
```java
@QuarkusTest
class FruitResourceTests {
	@Test
	public void addFruit() {
		PanacheMock.mock(Fruit.class);
		PanacheMock.doReturn(Uni.createFrom().item(new Fruit(100L, "Grapefruit", "Summer fruit")))
			.when(Fruit.class).persist();

		given()
			.when()
				.contentType(ContentType.JSON)
				.body("{\"name\":\"Grapefruit\",\"description\":\"Summer fruit\"}")
				.post("/fruits")
			.then()
				.statusCode(200)
				.contentType(ContentType.JSON)
				.body(
					"id", is(100),
					"name", is("Grapefruit"),
					"description", is("Summer fruit")
				);

		PanacheMock.verify(Fruit.class).persist();
		PanacheMock.verifyNoMoreInteractions(Fruit.class);
	}
}
```

Running `./mvnw clean verify` produces the following test failure, indicating the `PanacheMock.doReturn(Uni.createFrom().item(new Fruit(100L, "Grapefruit", "Summer fruit"))).when(Fruit.class).persist();` is not actually being "picked up". The asserted `id` should be `100`, but it isn't.

```shell
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.231 s <<< FAILURE! - in org.acme.rest.FruitResourceTests
[ERROR] org.acme.rest.FruitResourceTests.addFruit  Time elapsed: 2.645 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
JSON path id doesn't match.
Expected: is <100>
  Actual: <1>

        at org.acme.rest.FruitResourceTests.addFruit(FruitResourceTests.java:30)

2021-06-04 10:29:08,142 INFO  [io.quarkus] (main) Quarkus stopped in 0.041s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FruitResourceTests.addFruit:30 1 expectation failed.
JSON path id doesn't match.
Expected: is <100>
  Actual: <1>

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

### Output of `uname -a` or `ver`
`Darwin edeandre-mac 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64`

### Output of `java -version`
```shell
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### GraalVM version (if different from Java)
N/A

### Quarkus version or git rev
`2.0.0.CR3`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```shell
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/edeandre/.sdkman/candidates/java/11.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by FroMage** [comment]
To mock instance methods of an entity you need to actually mock the session:

```java
@QuarkusTest
public class PanacheMockingTest {

    @InjectMock
    Mutiny.Session session;

    @Test
    public void testPanacheSessionMocking() {
        Person p = new Person();
        // mocked via Mutiny.Session mocking
        p.persist().await().indefinitely();
        Assertions.assertNull(p.id);

        Mockito.verify(session, Mockito.times(1)).persist(Mockito.any());
    }
}
```

**Comment by edeandrea** [comment]
Where in the example though do I set up an interaction? In Panache reactive, the `persist()` method on the entity returns `Uni<T>` but `Mutiny.Session.persist(Object)` returns `Uni<Void>`?

I want to set up an interaction that is something like "When the `persist()` method is called, return some other `Uni` which the test will provide.

**Comment by loicmathieu** [comment]
Here, the issue is that you normally should create a mocked Fruit with Mockito but you cannot as the Fruit object is created by the resteasy serialization layer.

I'm afrad there is no solution to what you want to achieve, if you test your application at the HTTP layer using restassured, you must use the restassured assertion (at the http layer). Here I would remove all the code related to mockito/panachemock.

**Comment by edeandrea** [comment]
Also adding

```java
@InjectMock
Mutiny.Session session;
```

doesn't work. This is what I get in the output:

```shell
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.667 s <<< FAILURE! - in org.acme.rest.FruitResourceTests
[ERROR] org.acme.rest.FruitResourceTests.addFruit  Time elapsed: 0.004 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.
Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.2+9
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.2+9
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.16
Underlying exception : java.lang.IllegalArgumentException: Unknown type: null
Caused by: java.lang.IllegalArgumentException: Unknown type: null
2021-06-07 10:04:49,594 INFO  [io.quarkus] (main) Quarkus stopped in 0.033s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FruitResourceTests.addFruit » TestInstantiation Failed to create test instance
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
```

**Comment by edeandrea** [comment]
> I'm afrad there is no solution to what you want to achieve, if you test your application at the HTTP layer using restassured, you must use the restassured assertion (at the http layer). Here I would remove all the code related to mockito/panachemock.

I can use the rest-assured at the HTTP layer to validate the returned json is correct, but I don't need/want an entire persistence back-end just to verify my HTTP layer. I can accomplish this just fine using the repository pattern.

For the active record pattern, I'll continue with what I was doing before:

```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Uni<Fruit> addFruit(@Valid Fruit fruit) {
	return Panache.withTransaction(() ->
		Fruit.persist(fruit)
			.replaceWith(fruit)
	);
}
```

and the tests

```java
@Test
public void addFruit() {
	PanacheMock.mock(Fruit.class);
	Mockito.when(Fruit.persist(Mockito.any(Fruit.class), Mockito.any()))
		.thenReturn(Uni.createFrom().voidItem());

	given()
		.when()
			.contentType(ContentType.JSON)
			.body("{\"id\":1,\"name\":\"Grapefruit\",\"description\":\"Summer fruit\"}")
			.post("/fruits")
		.then()
			.statusCode(200)
			.contentType(ContentType.JSON)
			.body(
				"id", is(1),
				"name", is("Grapefruit"),
				"description", is("Summer fruit")
			);

	PanacheMock.verify(Fruit.class).persist(Mockito.any(Fruit.class), Mockito.any());
	PanacheMock.verifyNoMoreInteractions(Fruit.class);
}
```

**Comment by loicmathieu** [comment]
@edeandrea yes, this is the difference between repository where you can easily mock it, and entity. Again, here, the Fruit is created by the serialization layer and there is no way you mock the instanciation of an object JVM wide! The new is made by the serialization layer, so with entity I recommend using embedded database (h2 or testcontainer based database).

**Comment by edeandrea** [comment]
Thank you @loicmathieu for the conversation!

**Comment by FroMage** [comment]
> doesn't work. This is what I get in the output:

I have a fix for that in https://github.com/quarkusio/quarkus/pull/17728 it's a bug.

**Comment by edeandrea** [comment]
Awesome! Scanning that ticket I see

   > Added `@ReactiveTransaction` to forward to `Mutiny.Session.withTransaction`: method must return a `Uni` or be invoked from a non-VertxThread (in which case it blocks)"

Would that be an annotation I could put on a method instead of having to do something like

```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Uni<Fruit> addFruit(@Valid Fruit fruit) {
  return Panache.withTransaction(() -> this.fruitRepository.persist(fruit));
}
```

?

**Comment by FroMage** [comment]
Yes.

**Comment by FroMage** [comment]
Because `@Transactional` integrates with JTA and we don't support that, ATM, so it would give you a false sense of it being the same.

**Comment by edeandrea** [comment]
Got it - thanks @FroMage !

Is this going to be part of Quarkus 2.0? Or a later 2.x version? Will `@TestTransaction` also be made to work in tests?

**Comment by FroMage** [comment]
Hopefully 2.0 yes. I don't know what `@TestTransaction` is.

**Comment by edeandrea** [comment]
> I don't know what `@TestTransaction` is.

https://quarkus.io/guides/getting-started-testing#tests-and-transactions
