### ISSUE TITLE
Add m2e lifecycle mapping to bootstrap maven plugin

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#1769]
This issue is about integrating the plugin into the build process triggered by Eclipse. Currently it's ignored by Eclipse build which results in extension descriptor missing from the classes dir after the build.

**Comment by FroMage** [comment]
Just tried again, and really my Eclipse goes into an infinite "building workspace" loop with this patch. What version of Eclipse are you using? I've Version: 2018-12 (4.10.0).

**Comment by FroMage** [comment]
ATM it never settles down. I always see a rebuild in the status bar bottom right. Every few seconds it starts a new build.

**Comment by cescoffier** [comment]
@aloubyansky  Should we close this one? The PR is merged?

**Comment by cescoffier** [comment]
Closing, if there is still an issue, let's create another issue.
