### ISSUE TITLE
2.0.0.CR3 caused system properties from QuarkusTestResourceLifecycleManager to not be available in tests

### ISSUE THREAD

**Issue by juangon** [quarkusio/quarkus#17698]
## Describe the bug
When using a class implementing `QuarkusTestResourceLifecycleManager`, method `start` and returning some value on it, it isn't available from test using System.getProperty. I am using `QuarkusTestProfile` for adding those resources. Was working in 1.x.

### Expected behavior
All properties set in any QuarkusTestResourceLifecycleManager should be available in test class.

### Actual behavior
Value is null.

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Output of `java -version`
JDK 11
### Quarkus version or git rev
2.0.0.CR3
## Additional context
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
This is expected. You now need to access them via config. Using system properties could lead to weird behaviors as they are global.

See https://github.com/quarkiverse/quarkus-github-app/commit/7032a2c50ad073045f4ec0d5a03f8d4fa7254d3e#diff-1b552a48f1a3bbdce78e0accde822d203c0ff06fa351a065eaa8664f0aaa6560R22-R23 for an example of how to do it.

I was wondering if we should add something to the migration guide about it. Looks like I have my answer :).

**Comment by juangon** [comment]
Thanks very much!

**Comment by juangon** [comment]
Fixed using ConfigProvider.getConfig().getValue(...). Thanks again!
