### ISSUE TITLE
quarkus-rest-client does not propagate headers if you use RegisterProvider

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#17702]
## Describe the bug
When we have a Microprofile REST Client declared and use `@RegisterProvider` to apply a filter, it seems that the `org.eclipse.microprofile.rest.client.propagateHeaders` stops being taken into account.

The solution to this would be to explicitly add the `@RegisterClientHeaders` annotation to the top of the interface to restore this behavior to what it should be.

### Expected behavior
Headers declared via `org.eclipse.microprofile.rest.client.propagateHeaders` should be propagated when ClientRequestFilters are applied on the REST Client

### Actual behavior
Headers declared via `org.eclipse.microprofile.rest.client.propagateHeaders` are not propagated when `ClientRequestFilter`s are applied on the REST Client, unless the `@RegisterClientHeaders` are explicitly used

## To Reproduce

- Download the following project [demo.zip](https://github.com/quarkusio/quarkus/files/6600034/demo.zip)
- Go into the `MyRestClientWithAuthFilter` and comment the `@RegisterClientHeaders`
- Run the application and visit `http://localhost/hello/withfilter`, with `to-propagate=testheadervalue` as header
- Check that the header `to-propagate` is not propagated from the rest client

## Environment (please complete the following information):
Java 11, MacOS 11.2.3

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
### Quarkus version or git rev
1.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven

## Additional context
The sample project works with other methods (there are three other methods to achieve the same thing).

**Comment by geoand** [comment]
I can't say I am understand from the spec what the proper behavior should be.

@michalszynkiewicz any idea? Is there a TCK test that tests for this?

**Comment by michalszynkiewicz** [comment]
The spec says that the headers should not be propagated if the interface doesn't have the `@RegisterClientHeaders` annotation:
```
By default, no ClientHeadersFactory implementation is used. To enable a ClientHeadersFactory, the client interface must be annotated with the @RegisterClientHeaders annotation
```

And, checking the reproducer locally, this is how it behaves for me. Even without `@RegisterProvider`, the headers are propagated iff I add `@RegisterClientHeaders`

**Comment by geoand** [comment]
So should this be closed?

**Comment by michalszynkiewicz** [comment]
@csotiriou could you recheck the behavior without `@RegisterProvider` for you? 
Also, if it doesn't work for you, could you alter the reproducer to also consume the client call, so that anyone working on this issue doesn't have to implement the consuming part?

Thank you for your report :)

**Comment by michalszynkiewicz** [comment]
@csotiriou I'll close the issue but please reopen if it you find out that it doesn't behave as specified without `@registerProvider`.
