### ISSUE TITLE
2.0.0.CR3 gradle `quarkus-generated-sources` in wrong place

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#17706]
## Describe the bug
Building project with gradle with version 2.0.0.CR3 creates `quarkus-generated-sources` and `quarkus-test-generated-sources` empty directories at the module level. I believe they must be created under `build` directory

### Expected behavior
All build directories appear under `build` directory

### Actual behavior
Empty directories appear after `./gradlew clean build`

## To Reproduce
1. Checkout this repo - https://github.com/Shohou/quarkus-liquibase-bug (nevermind the name, created for #17523)
2. in master branch run `./gradlew clean build`
3. Check under `db` directory. Two new empty directories appear there
4. Same under `quark` module

**Comment by glefloch** [comment]
Thanks for reporting this @Shohou. I can reproduce it locally. I will have a look on it.
