### ISSUE TITLE
2.0.0.CR3 org.hibernate.LazyInitializationException for fetched relation ouside the transaction

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#17710]
## Describe the bug
With quarkus version `2.0.0.CR3` I'm seeing this exception
```
2021-06-05 00:32:13,387 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): org.hibernate.LazyInitializationException: Unable to perform requested lazy initialization [org.acme.resteasyjackson.Quark.bark] - no session and settings disallow loading outside the Session
        at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.throwLazyInitializationException(EnhancementHelper.java:275)
        at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.performWork(EnhancementHelper.java:165)
        at org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.loadAttribute(LazyAttributeLoadingInterceptor.java:77)
```
While with `1.13.6.Final` it works fine.
It happens when an Entity has a relation with default `fetch = FetchType.LAZY`. I load it inside the transaction with `left join fetch` part in select statement. Then I try to use it outisde the transaction and read the relation. With `2.0.0.CR3` it fails with attempt to load relation, while with `1.13.6.Final` it correctly passes because relation was already loaded.

### Expected behavior
Already loaded relation should still be usable outside the transaction

### Actual behavior
Quarkus tries to load the relation from database and fails because it is outside the transaction context

## To Reproduce
1. Checkout this repo - https://github.com/Shohou/quarkus-lazy-fetch-bug
2. Run `./gradlew clean quarkusDev` and see the exception
3. switch to `1.13.6` branch and run `./gradlew clean quarkusDev` again. There will be no exception and `quark - bark` message can be found in console
4. Inspect the code - https://github.com/Shohou/quarkus-lazy-fetch-bug/blob/master/src/main/java/org/acme/resteasyjackson/Init.java

**Comment by yrodiere** [comment]
Thanks for reporting this, and for the reproducer.

From what I can see, the `left join fetch` in your query is not being honored by Hibernate ORM. I suspect this is a regression in ORM 5.5. I'm investigating.

**Comment by yrodiere** [comment]
Created https://hibernate.atlassian.net/browse/HHH-14659. Working on it.

**Comment by Sanne** [comment]
thanks @yrodiere ! I couldn't check, but wondering if it could relate to some side effect from the fix for HHH-14620

**Comment by yrodiere** [comment]
> thanks @yrodiere ! I couldn't check, but wondering if it could relate to some side effect from the fix for HHH-14620

That's what I thought at first, but that seems unlikely considering that fix was specific to "to-many" associations, and this bug is specific to "to-one" associations.

I have some tests in ORM now, I'm trying to find the culprit.

**Comment by yrodiere** [comment]
Possible fix: https://github.com/hibernate/hibernate-orm/pull/4033
