### ISSUE TITLE
Support multiple AWS Lambda functions deployable simultaneously

### ISSUE THREAD

**Issue by aagnone3** [quarkusio/quarkus#17718]
## Description

I’ve found several nice examples of Quarkus projects which enable easy declaration of a Lambda in a project, usually also using AWS SAM, which is great. However, none of them (or any docs, that I could find) show support for multiple Lambda handlers in one project without having to choose a single one to deploy.

The use case I’m looking for is a basic REST API offering CRUD methods (one handler per HTTP verb) where the SAM template declares a new Lambda for each handler.

## Implementation ideas

I'm still familiarizing myself with the details of Quarkus behind the scenes, but from the docs I've picked up that the library scans for implementations of `com.amazonaws.handlers.RequestHandler`. I'm not sure what prevents deploying multiple implementations (with a name annotation making them unique) simultaneously. Looking for feedback on this, if someone has starting pointers for implementation I could help.

**Comment by patriot1burke** [comment]
use @javax.inject.Name on each of your handlers.  Then you should be able to choose by @Name which handler you use by setting a QUARKUS_LAMBDA_HANDLER environment variable

**Comment by aagnone3** [comment]
Hey @patriot1burke, thanks for responding. I think you missed my detail about simultaneously deployable. I don't want to use an environment variable to pick a handler; I want to use all of them.

In [this section](https://quarkus.io/guides/amazon-lambda#choose), it says the following:

```
If it finds more than one handler class, a build time exception will also be thrown.
```

This precludes from having a project with one handler for each of a GET, PUT, POST, etc. request from API Gateway that are all deployed at the same time. 

Is my understanding correct?

**Comment by guru500** [comment]
Facing same issue ! Have you found the solution?
