### ISSUE TITLE
2.0.0.CR3 gRPC code generator doesn't work anymore (Gradle project)

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#17726]
## Describe the bug
I upgraded my project from 2.0.0.Alpha3 to 2.0.0.CR2. 
After that the grpc files are not created anymore. 
The proto files are in folder src/main/proto/

### Expected behavior
The generated grpc sources are generated under build/classes/java/quarkus-generated-sources/grpc/ (this works with 2.0.0.Alpha3)

### Actual behavior
The grpc files are not generated at all.

### Quarkus version or git rev
2.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.6.1

**Comment by glefloch** [comment]
I think this has been fix in #17716

**Comment by cescoffier** [comment]
Thanks @glefloch !

**Comment by holledauer** [comment]
it would be great if you could release a 2.0.0.CR4 with that fix
