### ISSUE TITLE
QuarkusIntegrationTest docker run, does not clean container after timeout

### ISSUE THREAD

**Issue by bdevreugd-vialis** [quarkusio/quarkus#17737]
If the docker run process takes more then 10 seconds to fully startup Quarkus, the extension will forcibly destroy the process. If the container, however, was started, it won't be cleaned up, leaving it running on the docker daemon.

https://github.com/quarkusio/quarkus/blob/11607b626f070f5ed92617e3273322b30de6822d/test-framework/common/src/main/java/io/quarkus/test/common/LauncherUtil.java#L73

If you use the `--cidfile` parameter on docker run, then at the end of the process you can check if that file exists and if so remove the container with `docker rm -f {cidfile_contents}`

_These dangling containers also arrived with issue #17565, so I would prefer the cidfile cleanup over changing `destroyForcibly` to `destroy`, that way all issues that could arrive will never result in dangling containers._

**Comment by geoand** [comment]
I'll check it out
