### ISSUE TITLE
integrate mapstruct with dev mode

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#17745]
ATM, `quarkus:dev` restart is needed when mapstruct interface gets changed.
It would be great if we could have it working without needing the restart.

It could probably be made by creating a mapstruct extension and using the code gen provider but would require some changes.

**Comment by famod** [comment]
Related: #1502 & #5956 (maybe more)

**Comment by michalszynkiewicz** [comment]
Thanks @famod !

Maybe we could have a single CodeGenProvider invoking all the annotation processors...

**Comment by geoand** [comment]
Closing this as it's a duplicate of the aforementioned issues
