### ISSUE TITLE
Improve interaction with DB Migrations frameworks like flyway and liquibase etc

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#1775]

**Comment by machi1990** [comment]
Support for Flyway may land soon: There is a [PR](https://github.com/quarkusio/quarkus/pull/1649) to add it.

**Comment by pipinet** [comment]
@machi1990 ok, thanks。

**Comment by geoand** [comment]
The flyway PR has been merged, OK to close the issue @pipinet ?
