### ISSUE TITLE
`@TestSecurity(authorizationEnabled = false)` does not work with `quarkus.security.jaxrs.deny-unannotated-endpoints`

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#17759]
## Describe the bug
When an application sets `quarkus.security.jaxrs.deny-unannotated-endpoints` to `true` then a test annotated with `@TestSecurity(authorizationEnabled = false)` will get a `401` rather than a `200` status when calling an endpoint annotated with `@RolesAllowed`. This in contrast to when `quarkus.security.jaxrs.deny-unannotated-endpoints` is not set (to `true`).

### Expected behavior
Even when `quarkus.security.jaxrs.deny-unannotated-endpoints` is set to `true` I would expect `@TestSecurity(authorizationEnabled = false)` annotated tests to pass.

### Actual behavior
A test like the following will fail, because the returned status is 401 rather than 200:
```java
    @Test
    @TestSecurity(authorizationEnabled = false)
    void authorizationDisabled() {
        Assertions.assertEquals(200, RestAssured.get().thenReturn().statusCode());
    }
```

By also declaring the `user` and `roles` the test can be made to pass:
```java
    @Test
    @TestSecurity(authorizationEnabled = false, user = "foo", roles = "user")
    void authorizationDisabled() {
        Assertions.assertEquals(200, RestAssured.get().thenReturn().statusCode());
    }
```

## To Reproduce
1. Clone https://github.com/knutwannheden/test-disable-authorization
2. Run `mvn verify`
3. The test `DenyUnannotatedTest#authorizationDisabled()` fails while `StandardTest#authorizationDisabled()` passes. The former has `quarkus.security.jaxrs.deny-unannotated-endpoints` set to `true`.

### Configuration
```properties
quarkus.security.jaxrs.deny-unannotated-endpoints=true
```

### Output of `uname -a` or `ver`
```shell
$ uname -a
MSYS_NT-10.0-19043 WIN10-KNUT 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys
```

### Output of `java -version`
```shell
$ java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+22-SA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+22-SA (build 11.0.9+11-LTS, mixed mode)
```

### Quarkus version or git rev
1.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```shell
$ ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\knutw\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 11.0.9, vendor: Azul Systems, Inc., runtime: C:\dev\tools\azul-zulu-enterprise-openjdk-jdk11.0.9-win_x64-mobi1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
This is actually a duplicate of https://github.com/quarkusio/quarkus/issues/19896 which was fixed in `2.3.0.CR1`
