### ISSUE TITLE
Update Migration Guide to use `@Identifier` instead of `@Named` to inject the default Kafka broker

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#17754]
## Description
This change is related to https://github.com/quarkusio/quarkus/commit/11bc00f324b6ed4166ab4250e6661060b7d1a4d4.
The problem is that keeping injecting the default Kafka broker using `@Named` is now failing:

```java
@ApplicationScoped
public class KafkaProviders {

    @Inject
    @Named("default-kafka-broker")
    Map<String, Object> config;
}
```

Using:

```java
@ApplicationScoped
public class KafkaProviders {

    @Inject
    @Identifier("default-kafka-broker")
    Map<String, Object> config;
}
```

It works. 

Therefore, this is a breaking change that should be noted in the Migration guide for 2.x.

**Comment by cescoffier** [comment]
Jum, why do you need to inject the Kafka configuration? This is internal.

**Comment by cescoffier** [comment]
Migration guide updated.
