### ISSUE TITLE
NativeImageTest fails because the LauncherUtil is unable to determine the status of the running process

### ISSUE THREAD

**Issue by abrenn** [quarkusio/quarkus#17767]
## Describe the bug
After upgrading from Quarkus 1.12 to 1.13 not even a native image smoke test works anymore.
When Using the `@NativeImageTest` the test failes before the first test step is executed. 
The exceptions says:
```
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
        at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:73)

```

This is happening (according to LauncherUtil) when the Quarkus Application is not reporting its address within 10 seconds.
According to the logs the application started and I can see the address and port like that:

```
0.0.1 native (powered by Quarkus 1.13.6.Final) started in 0.029s. Listening on: http://0.0.0.0:43529"
```

### Expected behavior
The tests is starting.

### Actual behavior
The test is not starting but failing with the described exception.

### Output of `uname -a` or `ver`
```
Linux  5.12.2-1-MANJARO #1 SMP PREEMPT Fri May 7 17:53:15 UTC 2021 x86_64 GNU/Linux
```
### Output of `java -version`
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

### Quarkus version or git rev
1.13.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
gradle 7.0.2

**Comment by gsmet** [comment]
Could you share a small reproducer? That would allow us to check if it's environment related.

**Comment by geoand** [comment]
Can you also try with `2.0.0.CR3`? 
We have fixed a few issues around this

**Comment by abrenn** [comment]
@geoand I will try that with our current project but I think that an update to 2.0.0 will break a couple of other things.
If that is the case I will try to create a small reproducer.

**Comment by abrenn** [comment]
@gsmet Sorry, that it took a while, but here we go:

https://github.com/GAlexMES/quarkus-native-testing

I figured out, that the problem has something to do with `org.slf4j:slf4j-api:2.0.0-alpha1` which we forcefully use.
When you remove this resolution strategie or switch to a different provider in the application.yml it works.

However: It worked in this configuration before I updated to 1.13.7. I will try to investigate if we can work around that specific slf4j version in the next days. Nevertheless I think Quarkus should be compatible to newer slf4j versions.

@geoand I was not able to update Quarkus to 2.0.0. in this service because there are too many broken dependencies. That seems like a topic for another day ;)

**Comment by abrenn** [comment]
@gsmet 
To give you guys more context:
We need native building and we need to configure the application log style using logback XMLs due to company restrictions.

Therefor we added the set the logging provider to slf4j `-Dorg.jboss.logging.provider=slf4j`.
Sadly that was not working out of the box because quarkus was not picking up the logback.xml files for application logging.

Thats why we switched to the new slf4j version which also requires the new logback version. That construct then worked for quite some time until the `1.13` quarkus update. 

I hope that helps to figure it out. If you need anything else let me now :)

**Comment by geoand** [comment]
Unfortunately unless have an actual test application, it will be very hard to figure out the problem

**Comment by abrenn** [comment]
@geoand I added a link to the github where I added the application where the native test is failing yesterday.

What exactly do you need that is not in that repository?

**Comment by geoand** [comment]
Ah, I hadn't seen that.
I'll need to check it out

**Comment by geoand** [comment]
So it seems like your application doesn't write to the logs until it's closed.
You can see that when running the native image standalone.

Now given that what you are doing with logging is non standard, I don't really know how you could get around the problem

**Comment by abrenn** [comment]
I don't see why using a different logging provided is "non standard".
JBoss Logging offers this option and it should therefore be supported by a fromework using JBoss, shouldn't it?
However: you are right, there is no logging, because there is no logging provider.

I added one to the Repo and added a `LOG.info()` to the Main. This is printed into the console. The quarkus application log is still missing and the native test is still failling.

**Comment by geoand** [comment]
It seems that the native application does not dump the logs to the file, whether you log manually or not (I tried this by removing the logging code in your `main` method).

Other than that, `@NativeImageTest` does not work with applications that don't listen on an http port.

What are you trying to test exactly?

**Comment by abrenn** [comment]
In this example I am not testing anything, just reproducing the issue.

In the real application I am doing integration testing.
Read Dara from Kafka, store to database, get it from an http endpoint.

**Comment by abrenn** [comment]
@geoand any news on this topic?

**Comment by geoand** [comment]
Not really no. I don't know what's going an the application doesn't dump the logs to the file

**Comment by abrenn** [comment]
Do you need any more support or are you just dropping it?

**Comment by geoand** [comment]
I personally I am not looking into it (as the application does not use standard logging - other applications I tried worked just fine), others are obiously free to check

**Comment by simon-hlx** [comment]
Any update about it, i have the same issue :/

**Comment by geoand** [comment]
I would encourage folks to test `2.1.0.CR1` which has some related fixes

**Comment by simon-hlx** [comment]
I take simpe starter on quarkus site
i put the version to 2.1.0.CR1
`<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>code-with-quarkus</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>2.1.0.CR1</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <parameters>${maven.compiler.parameters}</parameters>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
`
my graalvm_home and java_home is set to this version
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/
gu --version
GraalVM Updater 21.0.0.2
java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

MacOs BigSur version 11.4

Logs 
`[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] objcopy --strip-debug code-with-quarkus-1.0.0-SNAPSHOT-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 55269ms
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ code-with-quarkus ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.NativeGreetingResourceIT
Executing [/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log, -Dquarkus.log.file.enable=true]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 63.415 s <<< FAILURE! - in org.acme.NativeGreetingResourceIT
[ERROR] org.acme.NativeGreetingResourceIT.testHelloEndpoint  Time elapsed: 0.009 s  <<< ERROR!
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   NativeGreetingResourceIT.testHelloEndpoint » IllegalState Unable to determine ...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ code-with-quarkus ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:07 min
[INFO] Finished at: 2021-07-16T08:58:43-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (default) on project code-with-quarkus: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/simon.huleux/Documents/projects/code-with-quarkus/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by geoand** [comment]
What does `/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log` look like when the test fails?

**Comment by simon-hlx** [comment]
There no here , what i see in
NativeImageLauncher.java line 110
it delete this file and create the parent directory if needed
        Files.deleteIfExists(logFile);
        Files.createDirectories(logFile.getParent());
But at the end (after the test fail) there no log file exist.

**Comment by geoand** [comment]
Are you using any peculiar logging settings?

**Comment by simon-hlx** [comment]
Not i do not change anything about it, i just take what the quarkus start coding give it to me.
You can see in the pom.xml

**Comment by geoand** [comment]
If you have a reproducer, please attach it to the issue and I will take a look

**Comment by simon-hlx** [comment]
https://code.quarkus.io/?e=resteasy&extension-search=resteasy
i took just this extension
![Capture d’écran, le 2021-07-16 à 10 27 43](https://user-images.githubusercontent.com/70451777/125963482-4e2f9b61-526e-4c4d-8ef8-d56ecf538699.png)
i after you comment i just update the quarkus version from 2.0.2.Final to 2.1.0.CR1

**Comment by geoand** [comment]
I tried that and it worked just fine.

After the test fails, can you try running:

```
/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log, -Dquarkus.log.file.enable=true
```

**Comment by simon-hlx** [comment]
What is your config (version etc )

**Comment by geoand** [comment]
I tried multiple versions, and they all work

**Comment by simon-hlx** [comment]
i had this 
/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner , -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log, -Dquarkus.log.file.enable=true
[1]    39248 killed      , -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444,

**Comment by geoand** [comment]
Sorry, my bad:

```
/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log -Dquarkus.log.file.enable=true
```

**Comment by simon-hlx** [comment]
Same :/
 /Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner  -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/Users/simon.huleux/Documents/projects/code-with-quarkus/target/quarkus.log -Dquarkus.log.file.enable=true
[1]    39490 killed      -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444

**Comment by geoand** [comment]
No logs, no exceptions, nothing?

**Comment by simon-hlx** [comment]
No nothing, i can not search :/
it is for that perhaps it come from about how i install Graalvm or something specific of mac os bigsur i do not know
What is your environment base to have unit test native pass well ?

**Comment by geoand** [comment]
Does `/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner` do anything?

**Comment by simon-hlx** [comment]
it does the same 
 /Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner 
[1]    39746 killed  


Btw i deploy it (with package with docker ) on AWS lambda and the native image wotk well

It is just on my mac that not work for native part

**Comment by geoand** [comment]
I don't assume you have `quarkus.native.container-build=true` set, do you?

**Comment by simon-hlx** [comment]
to build and test on my laptop (MacOs) i do just
 to build
./mvnw clean package -Pnative 
 to Test 
 ./mvnw verify -Pnative 
 
 But yes when i deploy to Aws i used quarkus.native.container-build=true

**Comment by geoand** [comment]
Then yeah, `quarkus.native.container-build=true` won't work with `@NativeImageTest`

**Comment by simon-hlx** [comment]
yeah i know it is for that i do not used this property to launch the unit test native

**Comment by geoand** [comment]
If you cant determine why 

```
/Users/simon.huleux/Documents/projects/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner
```

Then there is not much else we can do

**Comment by abrenn** [comment]
I figured out my problem:

As we use logback and the ELK Stack to write to logs directly to kibana we do not write any log files.
Apparently the `@QuarkusIntegrationTest` triggers a lookup of the host and ports in a log file.

Therefore we now write that logfile during service startup. I attached the code below.
I don't know if the filepath works for you. You may have to alter it to your needings.
However we also had to fix the `quarkus.http.test-port`to a fix value instead of the dynamic `0` value.
Because we found no solution how to get the randomly chosen port during runtime and the code would otherwise just write `0` in the file.


Here is the code:

```
import io.quarkus.runtime.StartupEvent;
import org.eclipse.microprofile.config.ConfigProvider;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import java.io.FileWriter;
import java.io.IOException;
import java.util.NoSuchElementException;


@ApplicationScoped
public class StartupListener {

    void onStart(@Observes StartupEvent ev) {
        try {
            String port = ConfigProvider.getConfig().getValue("quarkus.http.test-port", String.class);
            FileWriter myWriter = new FileWriter("./build/quarkus.log");
            myWriter.write("Listening on: http://localhost:" + port);
            myWriter.close();
        } catch(NoSuchElementException | IOException nse){
            nse.printStackTrace();
        }
    }
}
```

Please do not blame me on the hackyness of this solution, its not my fault....

**Comment by geoand** [comment]
That's interesting... So even though the test starts Quarkus with settings that supposedly force it to write to a log file, your setup was preventing that from happening?

**Comment by abrenn** [comment]
I don't really know what is preventing it from writing into that log file. The logfile was created but was empty.

**Comment by geoand** [comment]
That's very interesting in it's own right. If you could create a small project that replicates this behavior, it would be a tremendous help for us

**Comment by geoand** [comment]
> As for the test port, I'll need to check.

This worked for me. Here is part of the output:

```
Executing [java, -Dquarkus.http.port=0, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:0, -Dquarkus.log.file.path=/home/gandrian/projects/redhat/quarkus-quickstarts/getting-started/target/quarkus.log, -Dquarkus.log.file.enable=true, -jar, /home/gandrian/projects/redhat/quarkus-quickstarts/getting-started/target/quarkus-app/quarkus-run.jar]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-07-21 11:15:18,426 INFO  [io.quarkus] (main) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.466s. Listening on: http://0.0.0.0:37883

```

**Comment by abrenn** [comment]
@geoand it is still reproduceable by the same code i posted 29 days ago further up in this issue:
https://github.com/quarkusio/quarkus/issues/17767#issuecomment-866011229

**Comment by geoand** [comment]
That reproducer isn't listening on an http port as far as I can tell. 
In cases like that, you'll need to implement your own `io.quarkus.test.common.IntegrationTestStartedNotifier` (or the now deprecated `io.quarkus.test.common.NativeImageStartedNotifier`) in order to let the testing infrastructure know when the application starts

**Comment by abrenn** [comment]
You are correct. But you can just add one HTTP Endpoint to it. Or I will do that later today.

**Comment by geoand** [comment]
I tested the application with a REST endpoint and indeed the log file was empty. When I removed the custom gradle configuration you have for logging, everything worked as expected

**Comment by simon-hlx** [comment]
Which custom gradle configuration you removed ?
Cause me i add nothing come from the "starter code" from quarkus

**Comment by geoand** [comment]
I removed any logging related stuff from the reproducer mentioned in https://github.com/quarkusio/quarkus/issues/17767#issuecomment-866011229

**Comment by bvarner** [comment]
I'm seeing the same behavior as described by this ticket -- but only intermittently -- in a containerized CI environment.

It _seems_ like if the startup takes too long, or the CPU is slow, I get these errors. I've managed to run _a handful of times_ out of hundreds and get the Integration Tests to function properly.

My project is using maven & the failsafe plugin, but I'm still seeing the same issues with the quarkus logs being empty.



@geoand - I'm not clearly understanding your post about the `IntegrationTestStartedNotifier`.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/blob/2.2.2.Final/test-framework/common/src/main/java/io/quarkus/test/common/IntegrationTestStartedNotifier.java is what I was referring to

**Comment by bvarner** [comment]
So, I'm testing an app with HTTP rest endpoints.
Why would I need to implement a Notifier? And can you think of a good reason why there's some sort of race condition resulting in my log files being non-existent when I'm using a single forked failsafe test?

**Comment by geoand** [comment]
You should not need it.

I can't think of a reason why you don't have the logs of the running application

**Comment by bvarner** [comment]
I don't get any output through failsafe either, that implies that quarkus is actually starting up.
it looks like it's hanging.

But when I run the commands and forks being dumped into logging by `./mvnw -X` -- the quarkus app starts up just fine.

**Comment by geoand** [comment]
If you have an example application that exhibits this behavior, please attach it

**Comment by bvarner** [comment]
Unfortunately this is a real life customer app, not a reproducer.

**Comment by bvarner** [comment]
I am able to reproduce this behavior by resource-constraining my system while building.

The threshold for triggering the condition appears to be highly variable and system-dependent.

For example, on my laptop, by disabling all but 2 cpu cores and forcing them to throttle to 800Mhz, I can reproduce this with a high degree of reliability.

None of the time-out settings for the maven-failsafe-plugin appear to have any effect.

**Comment by geoand** [comment]
Which property are you using to set the wait timeout?

**Comment by bvarner** [comment]
This is my failsafe configuration. The tests fail around 20seconds into the plugin executing. Regardless of my settings.

```
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <forkedProcessTimeoutInSeconds>180</forkedProcessTimeoutInSeconds>
                            <forkedProcessExitTimeoutInSeconds>60</forkedProcessExitTimeoutInSeconds>
                            <skip>${skipTests}</skip>
                            <systemPropertyVariables>
                                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                <maven.home>${maven.home}</maven.home>
                                <quarkus.test.wait-time>120</quarkus.test.wait-time>
                                <quarkus.test.native-image-profile>it</quarkus.test.native-image-profile>
                                <quarkus.test.arg-line>${argLine}</quarkus.test.arg-line>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by geoand** [comment]
> This is my failsafe configuration. The tests fail around 20seconds into the plugin executing. Regardless of my settings.

With the latest quarkus version?
Can you please also post any logs you have?

**Comment by bvarner** [comment]
Quarkus 2.2.1.Final

The only logs I get are what's listed in: https://github.com/quarkusio/quarkus/issues/17767#issuecomment-916356709
Which I am reposting here:
```
Executing [java, -javaagent:/app/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/app/target/quarkus.log, -Dquarkus.log.file.enable=true, -Dquarkus.profile=it, -jar, /app/target/quarkus-app/quarkus-run.jar]
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xmx671m -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 
Log file '/app/target/quarkus.log' was not created.
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 7, Time elapsed: 14.484 s <<< FAILURE! - in com.foo.bar.ThingResourceIT
[ERROR] com.foo.bar.ThingResourceIT.getEndpointNotFound  Time elapsed: 0.025 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
```

**Comment by geoand** [comment]
Thanks. 

And you said it always fails after 20 seconds?

**Comment by bvarner** [comment]
It seems to be consistently around that timeframe. The log reports elapsed times that vary from what I see on a stop-watch when I try to time it.

In real life it seems like it's closer to 25-30s after failsafe first starts logging that it's running, but I've not been super scientific about it. Really it's pretty bothersome to reproduce since I have to throttle the tar out of my system, or use an oversubscribed cloud-based build.

**Comment by bvarner** [comment]
Also confirmed on 2.2.2.Final.

**Comment by geoand** [comment]
Understood, thanks

**Comment by geoand** [comment]
One last think (hopefully): When you run:

```
java -javaagent:/app/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/app/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.profile=it -jar, /app/target/quarkus-app/quarkus-run.jar
```

manually, how does the application behave?

**Comment by bvarner** [comment]
When my system is throttled, it takes a while to start, but it starts and runs just fine.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20129 should likely take care of it

**Comment by bvarner** [comment]
I'm building / testing now from main.

Any chance this can end up in a maintenance release on 2.2 soon?

**Comment by geoand** [comment]
This fix will likely be part of `2.2.4`, hopefully to come out next week.

**Comment by bvarner** [comment]
I've locally branched off the upstream 2.2, cherrypicked in e1bb4f2, and I'm still seeing the same behavior.
Is there some debug log setting I can use to make things a bit more verbose without having to pour through `./mvnw -X` output?

**Comment by bvarner** [comment]
> One last think (hopefully), when you run:
> 
> ```shell
> java -javaagent:/app/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/app/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.profile=it -jar, /app/target/quarkus-app/quarkus-run.jar
> ```
> 
> manually, how does the application behave?

I get exceptions that the JVM failed to be created -- because the paths (absolute with `/app` as the prefix) don't match my local system. If I adjust those to be absolute and actual resolve to my system, things work fine.

**Comment by geoand** [comment]
> I've locally branched off the upstream 2.2, cherrypicked in [e1bb4f2](https://github.com/quarkusio/quarkus/commit/e1bb4f23d14c084421d6928898a507a84ca69108), and I'm still seeing the same behavior.
> Is there some debug log setting I can use to make things a bit more verbose without having to pour through `./mvnw -X` output?

You can set the Quarkus logging to DEBUG in your application.properties and run the test with that

**Comment by bvarner** [comment]
Setting Quarkus logging to DEBUG didn't change the outcome.
I'm still getting...
```
Executing [java, -javaagent:/.../.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/.../target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/.../target/quarkus.log, -Dquarkus.log.file.enable=true, -Dquarkus.profile=it, -jar, /.../target/quarkus-app/quarkus-run.jar]
Log file '/home/bvarner/Documents/work/AVT/spcd-rest-api/target/quarkus.log' was not created.
```

Shouldn't `-Dquarkus.test.wait-time=120` be included if my pom.xml is specifying:
```
 <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <forkedProcessTimeoutInSeconds>180</forkedProcessTimeoutInSeconds>
                            <forkedProcessExitTimeoutInSeconds>60</forkedProcessExitTimeoutInSeconds>
                            <skip>${skipTests}</skip>
                            <systemPropertyVariables>
                                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                <maven.home>${maven.home}</maven.home>
                                <quarkus.test.wait-time>120</quarkus.test.wait-time>
                                <quarkus.test.native-image-profile>it</quarkus.test.native-image-profile>
                                <quarkus.test.arg-line>${argLine}</quarkus.test.arg-line>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20101 fixed the issue of `quarkus.test.wait-time` not being taken into account.
Can you try using the legacy `quarkus.test.jar-wait-time` in the meantime?

**Comment by bvarner** [comment]
I do not see wait-time arguments when running the integration tests using either or both of those properties.
I'm using a local build of quarkus 999-SNAPSHOT off the `main` branches of quarkus-platform and quarkus.

**Comment by geoand** [comment]
I don't think you are running from main, because the `Executing...` format is a little different in main

**Comment by bvarner** [comment]
My local quarkus platform build was using 2.2.1.Final...

**Comment by bvarner** [comment]
Ok, finally getting everything to use 999-SNAPSHOT, and I can confirm this solves the issue.

**Comment by geoand** [comment]
Awesome 👍.

Thanks for checking!
