### ISSUE TITLE
QuarkusIntegrationTest on java jar, should support Jacoco

### ISSUE THREAD

**Issue by bdevreugd-vialis** [quarkusio/quarkus#17760]
In our CI we first do a simple `mvn verify` run with jacoco enabled, so we can get proper test coverage results.

With QuarkusIntegrationTest, the jar is obviously run on a separate JVM, which doesn't have the jacoco java-agent.
https://github.com/quarkusio/quarkus/blob/1871e8e00562614004562e6d386be5967539522e/test-framework/common/src/main/java/io/quarkus/test/common/JarLauncher.java#L78-L79

Would it be possible to pass the `argLine` value set by the jacoco-maven-plugin to the created jvm? That way Jacoco would work fine for integration tests that simply use the jar.

_Obviously it won't work on docker/native, just on the java one._

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/17677 will fix this
