### ISSUE TITLE
dev services vs. QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#17797]
## Describe the bug

In the main Quarkus codebase, when I do `cd integration-tests/kafka` and run `mvn clean test -Dtest-containers`, I see 2 Kafka containers started: first one is a Redpanda container started by Dev Services for Kafka, and second is a Strimzi Kafka container started by `KafkaTestResource` (which is a `QuarkusTestResourceLifecycleManager`).

This is unexpected, because `KafkaTestResource` sets the `kafka.bootstrap.servers` config property, while `DevServicesKafkaProcessor` checks for presence of this property and skips itself when the property is present.

@stuartwdouglas says:

```
I am pretty sure I know what the bug is
its to do with how I changed the TestResourceLufecycleManager config to be set
so continous testing does not set system properties that could interfere with dev mode
but they are only set for runtime
while DevServices reads them at build time
which sounds wrong, but normally in dev and test the runtime and build time config is the same
and this broke that assumption
```

### Expected behavior

Only 1 container started. Dev services skips itself correctly.

### Actual behavior

2 containers started.

## To Reproduce

```bash
cd integration-tests/kafka
mvn clean test -Dtest-containers
```

### Output of `uname -a` or `ver`

```
$ uname -a
Linux argondie 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`

```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

72493690f446fed5dc90e745bf2ac45bef5898eb

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
$ mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/lthon/software/apache-maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-144-generic", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
I am going to close this as a duplicate in favor of https://github.com/quarkusio/quarkus/issues/19296
