### ISSUE TITLE
Resteasy-Reactive: Read an manipulate body with ContainerRequestContext in a non-blocking wise

### ISSUE THREAD

**Issue by wernert75** [quarkusio/quarkus#17791]
## Description

I try to read the body of a REST-Request within a ContainerRequestFilter. 

                InputStream is = context.getEntityStream();
                byte[] data = is.readAllBytes();
                String body = new String(data, StandardCharsets.UTF_8);

Unfortunately this blocks the io-thread. 

I think it's really useful in an complete reactive approach to access and modify the body in a filter, that is not blocking the io-thread.

**Comment by stuartwdouglas** [comment]
You need to mark the filter as @Blocking. @FroMage @geoand it looks like `ResteasyReactiveContainerRequestFilter` does not help here, as it does not appear to have support for async reads in the API that we expose?

**Comment by geoand** [comment]
Yeah exactly. That's something we should provide as this is not the first time this has come up

**Comment by FroMage** [comment]
Yeah, we don't have a way to do an async read unless you use the vert.x APIs directly, and also, we don't have a way for filters to set the body to a stream either for further consumption.

**Comment by geoand** [comment]
I'll close this in favor of https://github.com/quarkusio/quarkus/issues/17280 which has more of a discussion
