### ISSUE TITLE
Distributed tracing for RestEasy Reactive

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#17800]
With RestEasy Classic we can trace the calls with Jaeger, we need the same functionality for RestEasy Reactive, both for server and client (client needs to propagate appropriate headers)

**Comment by kenfinnigan** [comment]
I kind of have this covered as part of https://github.com/quarkusio/quarkus/issues/17118 as well.

I know today the Reactive REST Client bit isn't there, but there should be tracing with OpenTelemetry for RESTEasy Reactive server components.

**Comment by michalszynkiewicz** [comment]
Should we close this then and add a bullet about the client to #17118 ?

**Comment by kenfinnigan** [comment]
Thinking on it more, I think it's ok for this to be open, as I know there is work needed for the client which can be added under this issue instead of the validation one.

I think I'd planned on creating issues when I find things during validation, but I know the client is missing for reactive, so this can stay

**Comment by kenfinnigan** [comment]
Today I've verified the server tracing is working for RESTEasy Reactive.

It's only the client missing

**Comment by michalszynkiewicz** [comment]
@kenfinnigan do you intend to work on it? Or should I?

**Comment by kenfinnigan** [comment]
I wouldn't be getting to it until some time next week at the earliest. If you have the time it would be appreciated

**Comment by michalszynkiewicz** [comment]
I doubt I will have time for this that soon too :) If I do, I will let you know
