### ISSUE TITLE
Class.getDeclaredMethods() return superclass methods too if superclass is package friendly

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#17809]
## Describe the bug
From the Class Javadocs:
Returns an array containing Method objects reflecting all the declared methods of the class or interface represented by this Class object, including public, protected, default (package) access, and private methods, but *excluding inherited methods*.

If you have a class B extends a package friendly class A, then
B.class.getDeclaredMethods() also includes A methods, which is incorrect.

### Expected behavior
B.class.getDeclaredMethods() contains only methods declared in B

### Actual behavior
B.class.getDeclaredMethods() contains methods declared in B and A

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

https://github.com/Christopher-Chianelli/issue-reproducer/tree/declared-classes-invalid

Or attach an archive containing the reproducer to the issue.

1. Declare class A to be package friendly (ex: class A {}, not public class A {})
2. Have class B extend class A
3. Note that `B.class.getDeclaredMethods()` contains A methods.

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Additional context
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@Christopher-Chianelli given the reproducer, I fail to see how it could be a Quarkus-specific issue?

/cc @stuartwdouglas

**Comment by Christopher-Chianelli** [comment]
@gsmet quarkus is the only dependency in the reproducer I posted. Outside of Quarkus, `getValue, setValue` are the only thing that `getDeclaredMethods()` returns. This presents an issue for OptaPlanner, since it navigates all the class (and super classes) members when looking for a PlanningId, and the same member is return by two seperate calls from `getDeclaredMethods()`, which means OptaPlanner cannot determine which member is actually a PlanningId

**Comment by Christopher-Chianelli** [comment]
(the issue I linked was how I discover this issue)

**Comment by stuartwdouglas** [comment]
getId() is a bridge method, getId() is added by the compiler, this has nothing to do with Quarkus.

Because the superclass is package private, and getd() is public, the compiler needs to create a copy of the method to allow code outside the package to invoke it.

If you want to check for this look for java.lang.reflect.Modifier#BRIDGE (although this is not the only reason a bridge method may be added).
