### ISSUE TITLE
add <groupid> in plugins to avoid IntelliJ errors

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#17804]
Intellij give errors when there is no <groupid> in the <plugin> section

````
<plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
````

I used https://code.quarkus.io/  to generated the example

to avoid Intellij to complain, I had to add this 
````
<groupId>org.apache.maven.plugins</groupId>
````

**Comment by geoand** [comment]
This is more of an IntelliJ issue, but I don't see why we can't add this.

cc @ia3andy

**Comment by ia3andy** [comment]
It seems to be fixed: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml#L152

**Comment by ia3andy** [comment]
Or maybe it's the compiler plugin which needs the groupId?

**Comment by ia3andy** [comment]
@survivant would you provide a PR? I added the file which needs to be edited.

**Comment by survivant** [comment]
@ia3andy I did a PR : https://github.com/quarkusio/quarkus/pull/18198
hope I apply it in the right place
