### ISSUE TITLE
[1.13.7] Using dotenv file and get unrecognized configuration key warn.

### ISSUE THREAD

**Issue by edufolly** [quarkusio/quarkus#17818]
## Describe the bug
Get this warn message:

```
2021-06-09 20:33:16,068 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.hibernate.orm.database.generation" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-06-09 20:33:16,068 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.db.kind" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### Expected behavior
No warn message for `QUARKUS_DATASOURCE_DB_KIND` and  `QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION`.

### Actual behavior
Quarkus works fine, but the warning message is shown.

If I set `QUARKUS_DATASOURCE_DB-KIND=postgresql` the warning message is not displayed, but Quarkus doesn't work correctly. Same behavior for `QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create`.

## To Reproduce
Create any project with dotenv file and add some property with `-`.

### Configuration
```properties
QUARKUS_DATASOURCE_DB_KIND=postgresql
QUARKUS_DATASOURCE_USERNAME=postgres
QUARKUS_DATASOURCE_PASSWORD=postgres
QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5432/hibernate_dev
QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
```

### Output of `uname -a` or `ver`
Darwin MacBook.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev
1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64

**Comment by kontoeniki** [comment]
Same with 1.13.6.Final. Until 1.13.4 the underscore configuration worked fine.

**Comment by radcortez** [comment]
This was fixed with https://github.com/quarkusio/quarkus/pull/17798. It seems we didn't backport it. Anyway, I'll add these as an additional test case to make sure it is correct.
