### ISSUE TITLE
QuarkusIntegrationTest docker env does not work with property names containing '/'

### ISSUE THREAD

**Issue by bdevreugd-vialis** [quarkusio/quarkus#17810]
We use the GraphQLClient in Quarkus 2.0.0, it requires a property called `test-service/mp-graphql/url`.
When the docker image is started, it is started with param: `--env TEST_SERVICE/MP_GRAPHQL/URL=http://localhost:50683`
This is an invalid environment variable, so it fails.

This is caused by:
https://github.com/quarkusio/quarkus/blob/f762885947f6af116eda4bbb8793be6688533f8d/test-framework/common/src/main/java/io/quarkus/test/common/DockerContainerLauncher.java#L151-L153

Please make sure it also converts '/' to '_'

**Comment by geoand** [comment]
Interesting.

I'll have a look soon
