### ISSUE TITLE
jsons extension not serializing object in native mode

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#1781]
If i manually serialize objects to json using jsonb, e.g;
```
    @Route(path = "/fruits", methods = GET, produces = "application/json")
    public void get(RoutingContext context) {
        StringBuilder response = new StringBuilder();
        response.append("[");
        Fruit.findAll(pool).subscribe(
                fruit -> response.append(jsonb.toJson(fruit).concat(",")),
                e -> context.response().setStatusCode(500).end(e.getLocalizedMessage()),
                () -> {
                    response.append("]");
                    context.response().end(response.toString());
                }
        );
    }
```

In JVM mode, the output is expected;

```
$ curl -D - http://localhost:8080/fruits
HTTP/1.1 200 OK
content-length: 99

[{"id":2,"name":"Apple"},{"id":3,"name":"Banana"},{"id":1,"name":"Cherry"},{"id":4,"name":"Pear"},]
```

but in native mode the output is an empty array;

```
$ curl -D - http://localhost:8080/fruits
HTTP/1.1 200 OK
content-length: 14

[{},{},{},{},]
```
There are no exceptions logged in the application log

**Comment by gsmet** [comment]
You have to add the `@RegisterForReflection` annotation to your objects.

And, yes, GraalVM doesn't throw any error, unfortunately.

See https://github.com/quarkusio/quarkus/issues/739 for more details.

**Comment by geoand** [comment]
We also have a relevant section in the docs [here](https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/writing-native-applications-tips.adoc#register-reflection)

**Comment by johnaohara** [comment]
Thanks @gsmet and @geoand for pointing out the documentation `@RegisterForReflection` did the trick.
