### ISSUE TITLE
GraphQL guide simplifications

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#17827]
Following the GraphQL guide I noticed that we're:

- Showing some large `Film` and `Hero` DTOs using lots of “dumb” accessors, when replacing them with public fields would work just as well and make the docs shorter and easier to read.
- Showing `@Name("filmId")` when it's actually optional and we could use the parameter name, inducing me to falsly believe this was required.
- I'm told I need to use `@Inject Context` by https://quarkus.io/guides/smallrye-graphql#context when trying to add it as a query method parameter appeared to Just Work.

Perhaps we can simplify the guide around these topics?

**Comment by phillip-kruger** [comment]
Sounds good. I'll fix a.s.a.p

**Comment by FroMage** [comment]
Thanks a lot! And also congrats on getting all those things right: they just worked when I tried them out, even though they were not documented in the guide :)
