### ISSUE TITLE
Classes directories are not added to the classpath in dev mode

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#1782]
ClassLoaderCompiler adds only JARs to the its classpath ignoring directories and everything else. In dev mode we perform workspace discovery and where possible using classes directories instead of the installed JAR artifacts. In case of a multi-module project when one of the module appears as a dependency, its classes will appear in the directory. When the main project is recompiled, the dependency on the module will be missing from the compiler's classpath.

**Comment by cescoffier** [comment]
At the same time, the target/generated-sources directory should also be managed. No?

**Comment by aloubyansky** [comment]
> At the same time, the target/generated-sources directory should also be managed. No?

yes, it should be. I plan to review this whole thing to add proper support for multi-module dev mode. I wanted to fix the immediate issue the user faced.
