### ISSUE TITLE
GraphQL DEV UI History doesn't appear to work

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#17828]
I've run many queries and the History tab is always empty. I get no JS Console errors. Is this normal?

**Comment by phillip-kruger** [comment]
This is not normal no, could be something I broke as I tinkered with the js to get subscriptions to work. I'll have a look a.s.a.p (This is actually in SmallRye, I'll open a issue there)

**Comment by phillip-kruger** [comment]
@FroMage , only looking at this now. I could not recreate it, using the latest Quarkus (2.1.0)

![history](https://user-images.githubusercontent.com/6836179/127645483-2da70f1d-9407-4ba7-9c8c-fad5df1b44ab.gif)

Can you check again ?

**Comment by geoand** [comment]
I am seeing the same thing as @FroMage, no history at all.

![Screenshot from 2021-08-03 19-15-58](https://user-images.githubusercontent.com/4374975/128050282-dcb0fe16-acd9-4431-b734-643b767d0618.png)

**Comment by phillip-kruger** [comment]
Weird. Let me try Chrome as well.

**Comment by phillip-kruger** [comment]
Works for me on chrome and firefox on Fedora. @FroMage - any more details you can share about your environment ?

**Comment by phillip-kruger** [comment]
Thanks for checking @geoand !

**Comment by FroMage** [comment]
Just tried it too, and I get history now. I wonder if that's reload-related?

**Comment by FroMage** [comment]
Nope, can't reproduce, oh well :)
