### ISSUE TITLE
For 2.x devtools, provide better messages when 1.x metadata is encountered

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#17831]
## Describe the bug

trying to explicitly specfify rhbq platform during creation gives this error:

```
qssnap create app -p com.quarkus.redhat:quarkus-universe-platform:1.11.6.Final-redhat-00001

Downloading from central: https://repo.maven.apache.org/maven2/com/quarkus/redhat/quarkus-universe-platform-quarkus-platform-descriptor/1.11.6.Final-redhat-00001/quarkus-universe-platform-quarkus-platform-descriptor-1.11.6.Final-redhat-00001-1.11.6.Final-redhat-00001.json
[ERROR] ❗ Unable to create project: Failed to resolve the Quarkus extension catalog
```

and I have settings.xml configured.

traditonal mvn create works:

```
mvn io.quarkus:quarkus-maven-plugin:1.11.6.Final-redhat-00001:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started -DplatformGroupId=com.redhat.quarkus -DplatformVersion=1.11.6.Final-redhat-00001 -DclassName="org.acme.quickstart.GreetingResource" -Dpath="/hello"
```

### Expected behavior
cli should know about repository locations defined by maven - not sure how that would work for gradle ? 

### Actual behavior

it seem to not consider maven settings at all.

**Comment by maxandersen** [comment]
snippet to put in ~/.m2/settings.xml to use for using rhbq:

```
 <profiles>
    <!-- Configure the JBoss Enterprise Maven repository -->
    <profile>
      <id>jboss-enterprise-maven-repository</id>
      <repositories>
        <repository>
          <id>jboss-enterprise-maven-repository</id>
          <url>https://maven.repository.redhat.com/ga/</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>jboss-enterprise-maven-repository</id>
          <url>https://maven.repository.redhat.com/ga/</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <activeProfiles>
    <!-- Optionally, make the repository active by default -->
    <activeProfile>jboss-enterprise-maven-repository</activeProfile>
  </activeProfiles>
```

**Comment by aloubyansky** [comment]
The correct argument is `-p com.redhat.quarkus:quarkus-universe-bom:1.11.6.Final-redhat-00001`, i.e. the group and artifact IDs are wrong in the description.
This will still not work because the 1.11 descriptor is in the old format.

**Comment by maxandersen** [comment]
doh - missed the flipped name ....but running with quarkus build from yesterday I get this:

```
 quarkus create app -p com.redhat.quarkus:quarkus-universe-bom:1.11.6.Final-redhat-00001 -a test234
[ERROR] ❗ Unable to create project: Failed to deserialize extension catalog /Users/max/.m2/repository/com/redhat/quarkus/quarkus-universe-bom-quarkus-platform-descriptor/1.11.6.Final-redhat-00001/quarkus-universe-bom-quarkus-platform-descriptor-1.11.6.Final-redhat-00001-1.11.6.Final-redhat-00001.json
```

are you able to run it to completion?

**Comment by ebullient** [comment]
I think we need to be able to parse the (older) extension catalog contents

**Comment by ebullient** [comment]
@tqvarnst and @maxandersen .. if I understand correctly from @aloubyansky, there was no expectation that the 2.x client would be able to work with 1.x RHBQ (as so many of the tools have changed.. )

**Comment by ebullient** [comment]
Something like this?
```
 % java -jar devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar create cli -o target/boo -P 1.13.7.Final
[ERROR] ❗  Unable to create project: The version 2 CLI can not be used with Quarkus 1.x projects.
The 1.x Quarkus CLI runner jar can be downloaded from Maven Central, e.g.
$ mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:get \
       -Dtransitive=false -Dartifact=io.quarkus:quarkus-cli:1.13.7.Final:jar:runner
```

**Comment by tqvarnst** [comment]
I would prefer if the error message said  something like `The version 2 CLI cannot be used with Quarkus 1.x projects, it's recommended to use the maven/gradle tooling for Quarkus 1.x projects`

**Comment by aloubyansky** [comment]
I think we could still support at least 1.13.x unless it is actually broken. I personally haven't seen a failure yet using the 2.x CLI with a 1.13 project. @ia3andy are there any incompatibilities in codestarts between 1.13 and 2.0?

**Comment by ebullient** [comment]
I think the issue is there are places we expect things to fail (old metadata, can't resolve published files, ... based on the conversation last week, I believe we opted to be safe).

I'm happy to instead redirect to maven and gradle tooling, that's fine

**Comment by maxandersen** [comment]
The issue we had was 1.11 usage. 

@aloubyansky what's the driver for wanting 1.13 to work and not 1.11 ? Wouldn't they have similar metadata ?

**Comment by ebullient** [comment]
I'm glad it worked ok most of the time for 1.13, but we know that 1.11 metadata was incompatible.

I'd prefer to make the clean separation and suggest people use 1.x maven/gradle/other tools with 1.x Quarkus than chase edge cases.
