### ISSUE TITLE
MP REST/GraphQL client config and slashes

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#17832]
I still don't understand why MP-REST went with slashes in their config keys, which is just horrible and inconsistent and contrary to everything we do in Quarkus and perhaps there were good reasons, but we should offer an alternative, on top of keeping supporting it, in the form of:

```
# old:
star-wars-typesafe/mp-graphql/url=...
org.acme.rest.client.CountriesService/mp-rest/url=https://restcountries.eu/rest
org.acme.rest.client.CountriesService/mp-rest/scope=javax.inject.Singleton
# new:
quarkus.graphql-client.star-wars-typesafe.url=...
quarkus.rest-client.countries-service.url=https://restcountries.eu/rest
quarkus.rest-client.countries-service.scope=Singleton
```

We can argue about `rest` vs `rest-client` (similarly for `graphql`), we can argue for `quarkus.rest-client.countries-service` over `quarkus.rest-client.CountriesService`, and even quarkus.rest-client.org.acme.rest.client.CountriesService` or quarkus.rest-client."org.acme.rest.client.CountriesService"` or whatever, but I think we should:

- get rid of slashes, be consistent with the rest of our config
- offer shortcuts for MP REST when the class name is enough, after all we scan all these, so we know their packages and they're already annotated with the `@RegisterRestClient` marker annotation
- offer shortcuts for scopes such as `Singleton`, though I do wonder if we couldn't place the annotation on the damn interface in the first place

WDYT?

CC @cescoffier

**Comment by phillip-kruger** [comment]
+1 on being consistent with Quarkus config and still be compatible with the spec ugly backslash one.

**Comment by jmartisk** [comment]
+1, I don't really like the current scheme either, but I went with it in GraphQL mainly to be consistent with MP REST Client. We can add an alternative.

**Comment by cescoffier** [comment]
Definitely +1, 

We discussed a bit with @michalszynkiewicz and @phillip-kruger last week (while working on a demo where the problem very visible) (see https://github.com/cescoffier/microservice-demo/blob/master/api-gateway/src/main/resources/application.properties).

**Comment by jeffmaury** [comment]
Adding @angelozerr because I'm not sure it impacts the LS

**Comment by angelozerr** [comment]
Thanks @jeffmaury for pinged me. Indeed we need to generate the new syntax properties on the JDT LS side. When this feature will be merged we could work on this new syntax.

Do you new if we need to generate old/new syntax, or perhaps generate the new syntax accoring the Quarkus version from the classpath. To promote the new syntax we could highlight aswarning the property and provide a code action (quickix) to convert to new syntax.

**Comment by geoand** [comment]
Big +1!

I've never heard of anyone using Quarkus that actually liked the use of `/` in the config property...

**Comment by Ladicek** [comment]
I'm trying to get a life, but before I succeed with that, just wanted to quickly add yet another +1 :grin:

**Comment by FroMage** [comment]
I guess I wasn't clear: if you think slashes should move out of config keys, you already made great life choices ;)

**Comment by radcortez** [comment]
Some additional information. A parallel discussion has been happening here: https://github.com/quarkusio/quarkus/pull/17220 (not about the slashes, but relevant because it is about how to extend MP Client configuration)

And here is some discussion on the MP REST Client side: https://github.com/eclipse/microprofile-rest-client/issues/171

I'm +1 to provide a way to configure without the slashes.

**Comment by michalszynkiewicz** [comment]
I think this means that reference guides for our clients will need to copy all the properties from the spec, but that's probably a good thing anyway.

Won't we have a bit of a problem with global vs client specific properties, e.g. `quarkus.rest-client.scope` vs `quarkus.rest-client.my-client.url`? I think @mkouba was/is trying to do a similar thing for grpc clients and it's not that easy. Maybe this clash was the reason for using slashes in the first place.

Anyway, if the majority thinks it's better, and the above isn't a problem, let's do it.

**Comment by michalszynkiewicz** [comment]
One more thing, I don't really like magically changing `org.acme.rest.client.CountriesService` to `countries-service`, it would be confusing for me as a user. I like `quarkus.rest-client.CountriesService` more.

Big +1 to shortcuts for scopes. Everywhere we have scopes :)

**Comment by jmartisk** [comment]
> Won't we have a bit of a problem with global vs client specific properties, e.g. quarkus.rest-client.scope vs quarkus.rest-client.my-client.url?

Yeah we kinda have a similar problem with data sources and it's quite confusing at times (there it's even worse because of the default [unnamed] data source). I guess it needs a good documentation for each property to make it clear what it means. Or we might just not use global properties, and require each client specify it separately.

> One more thing, I don't really like magically changing `org.acme.rest.client.CountriesService` to `countries-service`, it would be confusing for me as a user. I like `quarkus.rest-client.CountriesService` more.

I don't quite like `quarkus.rest-client.CountriesService` either, it's still magic, if the user didn't specify a `configKey`, then I'd require the fully qualified name, but I might be a minority in this.

**Comment by Ladicek** [comment]
> > One more thing, I don't really like magically changing `org.acme.rest.client.CountriesService` to `countries-service`, it would be confusing for me as a user. I like `quarkus.rest-client.CountriesService` more.
> 
> I don't quite like `quarkus.rest-client.CountriesService` either, it's still magic, if the user didn't specify a `configKey`, then I'd require the fully qualified name, but I might be a minority in this.

Agree here. This kind of shortcuts has an intrinsic danger: it works when there's exactly 1 class of given short name, but when a 2nd class of the same short name in a different package is added later, what used to work stops working. (Sure, it's usually unlikely. But not impossible, especially with names that are generic enough.)

I kinda like how we do it with logging (`quarkus.logging."com.example.MyClass".level` or something like that).

**Comment by Ladicek** [comment]
Sure, I wouldn't expect anything less. My point was this part: _what used to work stops working_.

**Comment by FroMage** [comment]
I dunno, seems to me that if you have two classes named `CountriesService` in your app, it's probably an error anyway ;)

**Comment by Ladicek** [comment]
I agree in principle, but I can also see a generic name such as `CountriesService` being used in multiple 3rd-party libraries rather easily.

**Comment by FroMage** [comment]
So just make it an error if there are more than one with that name, the same would happen with explicit bean names. It's fine ;)

**Comment by FroMage** [comment]
As for CamelCase and brochette-case being usable interchangeably in the config file, I thought it was already the case, I'm not sure anyone would bat an eyelid if we could write `CountriesService` both as-is and as `countries-service` which feels more config-compatible.

**Comment by FroMage** [comment]
>  I don't really like magically changing

Uh… first, it's not magically changing, but allowing shortcuts. Second, this is not magic, this is a clear case of Oh You Damn Well Know What I Mean You Stupid Framework So Let's Cut The Red Tape™. Third: we do magic all the time in Quarkus, either you didn't get the memo, or you've been calling it some other name ;)

**Comment by FroMage** [comment]
And now that I think about it, I don't even know why I _have_ to set the damn URL in the config in the first place: 

```java
@Path("/v2")
@RegisterRestClient(baseUri = "https://restcountries.eu/rest")
public interface CountriesService {

    @GET
    @Path("/name/{region}")
    Set<Country> getByRegion(@PathParam String region, @QueryParam("city") String city);
}
```

So why are we not documenting this first and foremost? It's not like most people want to be able to change the URI of a remote service without having to rewrite their client. It's pretty rare when a remote service moves without changing API.

**Comment by knutwannheden** [comment]
> It's pretty rare when a remote service moves without changing API.

I doubt we are the only ones doing this, but when we deploy our services to various stages (development, testing, etc.) in the cloud, we will have different URLs for them as well. This is where we then use the config key approach to configure the URL.

**Comment by michalszynkiewicz** [comment]
If we support both `countries-service` and `CountriesService` - fine by me. I meant to say that guessing that one has to use `countries-service` for `CountriesService` is not easy. That requires reading documentation :D

**Comment by FroMage** [comment]
Oh yeah, agreed.

**Comment by jmartisk** [comment]
Looks like we've kinda reached some consensus, so I'll get coding and come up with a PR for the GraphQL client
I'll include the short-cutting, even though I don't quite like it, but... it will be optional, right.

**Comment by TomasHofman** [comment]
> One more thing, I don't really like magically changing org.acme.rest.client.CountriesService to countries-service, it would be confusing for me as a user. I like quarkus.rest-client.CountriesService more.

I'm bit late here, but I would side with @jmartisk and @michalszynkiewicz - in the context of the MP rest client, assuming equivalency between `org.acme.rest.client.CountriesService` and `country-service` seems a bit confusing to me, because I would rather expect that the "country-service" refers to configKey attribute of the `@RegisterRestClient` annotation, as in:

```
@RegisterRestClient(configKey="country-service")
```
rather than to a class name.

Looking at it from the other end, if I saw a config file that contained:
```
quarkus.rest-client.countries-service.url=https://restcountries.eu/rest
```

and I wanted to grep for the interface(s) that use this config property, it would be much easier if I knew that "countries-service" can only refer to configKey, and not maybe also to a class name `CountriesService`. Too much ambiguity for me... If I want to use some sort of a short name, defining configKey is simple enough.

I rather like these two options:

```
# config key:
quarkus.rest-client.countries-service.url=https://restcountries.eu/rest
# class name:
quarkus.rest-client."org.acme.rest.client.CountriesService".url=https://restcountries.eu/rest
```

And since multiple clients can share the same configKey, I would say that a global setting is not strictly needed.

>> It's pretty rare when a remote service moves without changing API.

> I doubt we are the only ones doing this, but when we deploy our services to various stages (development, testing, etc.) in the cloud, we will have different URLs for them as well. This is where we then use the config key approach to configure the URL.

These properties definitely need to be overrideable externally, without modifying the application sources, so that environment specific configuration can be provided.

**Comment by TomasHofman** [comment]
This PR implements the new schema for REST client (classic and reactive): https://github.com/quarkusio/quarkus/pull/17220

**Comment by tttomat19** [comment]
Yet another reason to ban forward slashes is poor yaml support for these. Because `/` is not a valid hierarchy separator in yaml.

I had both of these issues: kubernetes poor support for `/` and yaml too.

**Comment by michalszynkiewicz** [comment]
Is there anything more to do for this issue? The REST Client config has been modified by @TomasHofman

**Comment by geoand** [comment]
Good point, let's close
