### ISSUE TITLE
Support for Local Keycloak Authorization

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#17843]
## Description
I've read by including all the permissions into a token the authorization service action can be performed locally by introspecting the token

## Implementation ideas

Enhance `KeycloakPolicyEnforcerAuthorizer` to avoid the remote call if the token includes the permissions.
By the time `KeycloakPolicyEnforcerAuthorizer` is invoked the token has already been verified - and the parsed `JsonWebToken` is already available (we might add it as an attribute to `Securityidentity`)  - so the code should check the token claim containing the permissions first and do the remote call only if it does not exist. A property should be added to allow for it (or request that the remote check always has to be done)

**Comment by sberyozkin** [comment]
CC @pedroigor

**Comment by famod** [comment]
This sound interesting for my current app. I suppose you first want to see how many people would like to have it before starting to implement it?

**Comment by sberyozkin** [comment]
@famod `quarkus-keycloak-authorization` supports caching the policy enforcer responses but avoiding the remote requests altogether can be of interest since there is no need to cache the data.
@pedroigor Hi Pedro can you please expand a bit more on how a claim representing the authorization permissions may look like ? I guess Keycloak can be configured to include not all but some of them ? And which Keycloak library/code should be used to check the permissions extracted from the token locally ?

**Comment by pedroigor** [comment]
Permission requests should only be sent in case the token does not contain permissions, previously granted by the server.

For that, the client (calling the backend) needs to exchange their access token with a new token by using a specific grant type. As per https://www.keycloak.org/docs/latest/authorization_services/#_service_obtaining_permissions.

Is this enough? Or the requirement here is to perform local policy enforcement based on the policies defined in Keycloak?

**Comment by sberyozkin** [comment]
Hi Pedro, thanks, if the access token which is sent to Quarkus already contains the Keycloak authorization permissions inlined, do you recall if quarkus-keycloak-authorization will skip sending a request to Keycloak in this case ? This is the idea behind this issue (I recall I was reading about the inlined permissions in your and Stians book, though I might've misread :-) )

**Comment by pedroigor** [comment]
Yeah, it will skip the call to the server if permissions are within the token and the token is valid.

**Comment by sberyozkin** [comment]
@pedroigor Excellent, thanks, so I'll close this issue then
