### ISSUE TITLE
Type-safe messages - consider declaring io.quarkus.qute.i18n.Message.value() as optional

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#17857]
If the relevant properties file is provided, e.g. `msg.properties`.

We would have to validate the presence of the file and key.

**Comment by michalvavrik** [comment]
@mkouba I'm happy to implement this. Can you please tell me how do you prefer to handle situation when there is both `msg.properties` file with key `xyz` and io.quarkus.qute.i18n.Message.value() in same namespace with same key is present?
e.g.
1. user can set his strategy in config file: file-first, annotation-first, fail-on-conflict,...
2. we do not allow this situation to happen and throw an exception
...?

**Comment by mkouba** [comment]
> Can you please tell me how do you prefer to handle situation when there is both `msg.properties` file with key `xyz` and `io.quarkus.qute.i18n.Message.value()` in same namespace with same key is present?

That's a good question. I think that we could start with the annotation-first approach. WDYT?
