### ISSUE TITLE
exclude-types not working in dev mode

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#17866]
## Describe the bug
I have a service that with `quarkusDev` dependencies on other service projects for the purpose of dev mode only. I knew there would be collisions on the `Application` classes, so I added the `Application` class fro mthe dependency to `quarkus.arc.exclude-types`. But it does not seem to be excluded because I get an error saying there is more than one `Application` class.

### Expected behavior
Quarkus dev mode to work.

### Actual behavior
`RuntimeException: More than one Application class: [my.project.OtherApplication,my.project.ThisApplication]`

## To Reproduce

`service3` in https://github.com/mweber03/quarkus-test

1.  `./gradlew build service3:quarkusDev`

### Configuration
build.gradle
```groovy
dependencies {
    quarkusDev project('service1')
}
```

application.properties
```properties
quarkus.arc.exclude-types=my.project.service1.Service1Application
```

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
Quarkus 1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by glefloch** [comment]
Thanks for reporting this issue @mweber03. I can reproduce it locally. It turns out that using the `implementation` scope seems to fix the issue. This could be used as a workaround.

**Comment by glefloch** [comment]
Actually, I can make it work as expected, I can exclude a bean from a `quarkusDev` dependency. Could you share a reproducer?

**Comment by mweber03** [comment]
@glefloch Here is a reproducer:

https://github.com/mweber03/quarkus-test

Run: `./gradlew build service3:quarkusDev`

**Comment by glefloch** [comment]
@mweber03, were you able to make it work?
