### ISSUE TITLE
Cache, Multitenancy and CacheKeyGenerator

### ISSUE THREAD

**Issue by goafabric** [quarkusio/quarkus#17879]
## Description

For Multi Tenancy, the Cache (Extension) needs to be aware of the TenantId.
From the Documentation I don't see if there is an easy to fulfill this.

For Spring and also the Native Java Cache API, we can achieve this by setting a Custom KeyGenerator, e.g:
https://schneide.blog/2020/03/24/the-java-cache-api-and-custom-key-generators/

But Quarkus Annotations, yet even if they look similar, don't support this.

So my Questions is:
How can Multi Tenancy be achieved for the Cache ?
Is there a standard way ? Or a possibility for a Cache Key Generator ?

**Comment by gwenneg** [comment]
Hi @goafabric. There is currently no built-in support for multitenancy or custom key generators in `quarkus-cache` indeed.

However, wouldn't the following logic be enough to support multitenant cached values in your application?

```
public String getTenantCachedValue(int key) {
    String tenantId = // Retrieve the tenant ID from the Vert.x RoutingContext or any other appropriate source.
    return getCachedValue(tenantId, key);
}

@CacheResult(cacheName = "multitenant-cache")
private String getCachedValue(String tenantId, int key) { // The cache key will be composed of both tenantId and key.
    // Method body omitted.
}
```

**Comment by gwenneg** [comment]
I wouldn't recommend to build a cache key from a `String` tenant ID though but rather from a custom class (the `TenantId` you mentioned?) with proper `equals` and `hashCode` implementations. Otherwise, the cached value could be accessed inadvertently from another method that would have the same kind of arguments: `(String, int)` in my example above.

**Comment by goafabric** [comment]
Hi,
and thank you for your fast reply.
Of course your solution would work.
However i do not want to polute the signatures with the tenantid.

In spring boot i currently save it within a threadlocal.
And append it inside the CacheKeygenerator

This way its transparent to the rest of the application

**Comment by goafabric** [comment]
closing this issue because of no reaction after 6 months
