### ISSUE TITLE
Quarkus CLI does not display icons correctly

### ISSUE THREAD

**Issue by belu** [quarkusio/quarkus#17876]
## Describe the bug
When creating an app via Quarkus CLI the icons are not displayed as shown in the documentation.
In my terminal a white rectangle is shown instead.

### Expected behavior
Icons are displayed correctly or if the terminal does not support this something else is used instead.

### Actual behavior
Icons are not displayed correctly.

## To Reproduce

1. quarkus create app

### Screenshots
![quarkus-cli-missing-logos](https://user-images.githubusercontent.com/1174164/121770814-e9d63180-cb6b-11eb-9a73-dd4e711eeb0f.png)

## Environment
OS: Linux
Shell: Bash
Terminal: Konsole (KDE, https://konsole.kde.org/)

**Comment by maxandersen** [comment]
What os, shell and terminal are you using ?

**Comment by belu** [comment]
OS: Linux
Shell: Bash
Terminal: Konsole (KDE, https://konsole.kde.org/)

**Comment by belu** [comment]
And in xterm it looks like this :-)
![quarkus-cli-xterm](https://user-images.githubusercontent.com/1174164/121771299-d24c7800-cb6e-11eb-93cf-614ec68d019e.png)

**Comment by maxandersen** [comment]
Does your font have icons normally ?

**Comment by belu** [comment]
Simple icons yes, but not Emojis. Tried to use different fonts with emojis:
- EmojiOne Color Font -> the icon for Maven is missing, only black & white
- Noto Emoji Font -> only black & white
- Twemoji Color Font -> only black & white

The problem is all of them are not suited to be used in a terminal (no fixed character width). And all of them are not colored but black & white.

**Comment by maxandersen** [comment]
Just to check - I assume you have Same issue with using mvn create plugin which is the same code ?

**Comment by belu** [comment]
Not sure what you mean. This does not display any icons/emojis, just an error message:
![maven-create-plugin](https://user-images.githubusercontent.com/1174164/121797018-bce25700-cc1d-11eb-8058-1c174e86f516.png)

**Comment by maxandersen** [comment]
I mean the way we thus far use maven to create projects:

'''

mvn io.quarkus:quarkus-maven-plugin:1.13.7.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
cd getting-started
'''

How does that render its output on your setup?

**Comment by belu** [comment]
Then I see the following output:
![quarkus-maven-tooling](https://user-images.githubusercontent.com/1174164/121797922-8ad3f380-cc23-11eb-96d2-dcaf49a76621.png)

Note that after installing the Emoji fonts I see at least some of the emojis (in black & white). Not sure if there exists another font pack that is missing to get the other emojis, too.

**Comment by belu** [comment]
Finally made some progress!

![gnome-terminal-quarks](https://user-images.githubusercontent.com/1174164/121799437-67617680-cc2c-11eb-989a-ba6ad7957eb6.png)

This is with the **Gnome Terminal**. Furthermore I installed ONLY the **Noto Color Emoji** font.

The icon for Maven 🧰 is still not working here.

There is also a missing space for some icons. This seem to be exactly the ones that have the _FE0F_ appended (to indicate colored icon). See here for an explanation: https://en.opensuse.org/Emoji.
And for a list of emojis with code points to be able to avoid the _FE0F_: https://unicode.org/Public/emoji/12.0/emoji-test.txt

Maybe we could replace the icons that are making problems with similar ones?
- Maven: 🧰 could be replaced by 💼 or 📦
- Quarkus: 🗃️ could be replaced by 💎, 👑, 🚀 etc. :-)
- Dockerfiles: 🛠️ could be replaced by 🐋 or 🐳
- Maven-Wrapper: 🛠️ could be replaced by 🔨 or 🔧

The suggested icons all work fine here.

**Comment by maxandersen** [comment]
make sense to choose better icons when available.

we do though expect users using "modern" terminals - sounds like your kconsole/xterm setup uses the absolute minimal terminal setup :)

**Comment by axblu** [comment]
In WSL it looks the following:
![quarkus-cli-wsl](https://user-images.githubusercontent.com/72867162/122163083-e1843c00-ce74-11eb-8466-0b61004c83eb.jpg)

The mentioned alternative Emojis from the comment above would all work in WSL out-of-the-box (only B&W here).

**Comment by ebullient** [comment]
The emojis are rendered w/in common code in devtools/codestarts...

**Comment by ebullient** [comment]
To clarify, you're asking to work backwards and use older emojis that have a monichrome/unqualified equivalent?
Most of what you link recommended adding that suffix to ensure the color version was used (which would require it to be present)

**Comment by ebullient** [comment]
Can you try w/ the PR?

**Comment by belu** [comment]
@ebullient Never mind. Just built everything and then I was able to execute the CLI JAR.

The emojis look good now in the Gnome Terminal!

![quarkus-cli-snapshot](https://user-images.githubusercontent.com/1174164/122250204-c1cb3300-cec9-11eb-9711-5333555a7253.png)

**Comment by maxandersen** [comment]
![2021-06-17_00-50-38](https://user-images.githubusercontent.com/54129/122304774-0e346400-cf06-11eb-9023-93ada2e13594.png)

here is it on osx in iterm2.

they are much less distinguishable but wsl usecase is quite a big crowd thus I reluctantly agree.
