### ISSUE TITLE
Logging Configuration and Kubernetes Configmap

### ISSUE THREAD

**Issue by goafabric** [quarkusio/quarkus#17885]
## Description

Hello everybody,
i have a very basic problem with the logging configuration and Kubernetes Configmap.
Already searched for existing issues and answers, but found none.

Logging categories in Quarkus are defined with double quotes, which is a little strange to me, e.g. :

quarkus.log.category."org.hibernate".level=INFO

Not a big deal as long as they stay inside application.properties.
The problem is now porting those over to kubernetes configmaps.

As long as the configmaps also have a an embedded file "application" properties,
we can just escape the property like this:

quarkus.log.category.\"org.hibernate\".level=INFO

However what I really want, the same way as for spring boot,
is to have to config directly inside the data sections of kubernetes:

data
  quarkus.log.category.\"org.goafabric\".level: "INFO"

This is of course not working because kubectl or the yml parser complains
"a valid config key must consist of alphanumeric characters"

Ommitting the escaped \" just yields to the logging config to have no effect.

So is there a solution to this, other than having an embedded application.properties ?

**Comment by geoand** [comment]
A YAML value of:

```yaml
quarkus:
  log:
    category:
      "org.hibernate":
        level: "INFO"
``` 

would yield the expected result.

Indeed, `quarkus.log.category."org.goafabric".level: "INFO"` does not

**Comment by goafabric** [comment]
Unfortunately kubectl does not allow for style like this:

"invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string";"

All examples for configmap always use the "dot-style"

e.g
quarkus.log.level: "INFO"

**Comment by soframel** [comment]
Hello,
I agree with goafabric, the solution using yaml on different lines in a configMap data does not work, Kubernetes expects configMap entries to be given as one line key-value pairs. 
Is there a workaround for this? Because for now, we can either change the log levels for all categories at once in Kubernetes (using quarkus.log.level), or rebuild the application completely, to change the level in application.properties…
Thanks.
