### ISSUE TITLE
Support aarch64 CPU architecture in gRPC extension code generation

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#17886]
## Description

It'd be useful if the gRPC extension protobuf code generation steps could work with aarch64.

See this reported issue in the camel-quarkus project https://github.com/apache/camel-quarkus/issues/2762.

## Implementation ideas

Upgrade `protoc` to 3.17.3 as aarch64 seems to be supported:

https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.17.3/

**Comment by michalszynkiewicz** [comment]
we need to see if vertx-grpc is compatible with this

**Comment by cescoffier** [comment]
@pmlopes do you know with Vert.x gRPC works with aarch64?

**Comment by pmlopes** [comment]
@cescoffier while this is totally possible:

https://github.com/vert-x3/vertx-grpc/pull/103

Netty versions are still preserved and tests pass, I can only assume that you will be able to compile proto files as `protoc` now offers a native aarch64 binary and the jprotoc/canteen plugins we use to run our templates from java also seem to offer thse binaries:

https://repo1.maven.org/maven2/com/salesforce/servicelibs/canteen-bootstrap/1.1.0/canteen-bootstrap-1.1.0-osx-aarch_64.exe

I don't have access to this hardware setup so I cannot be 100% sure that after merging the PR you can bump the vert.x dependency and close this issue.

**Comment by michalszynkiewicz** [comment]
So, `protoc` is indeed there but `protoc-gen-grpc-java` is not... 
I don't have the hardware to check if it's possible to use some other binary for `protoc-gen-grpc-java` with e.g. `osx-x86_64`...

**Comment by michalszynkiewicz** [comment]
People write this is possible with Rosetta. 
This PR upgrades grpc to the version used by vertx-grpc and allows to override the os classifier, so in case of M1+rosetta, should allow mac users to use osx-x86_64 binaries, if I understand it correctly.

**Comment by michalszynkiewicz** [comment]
I don't want to close this issue yet, let's close it when we have get a proper fix (when protoc-gen-grpc-java is released for osx-aarch64)

**Comment by Karm** [comment]
Hello @michalszynkiewicz,  Mandrel has aarch64 builds available on https://github.com/graalvm/mandrel/releases/tag/mandrel-21.3.0.0-Final

Is this issue actually resolved or does it make sense to include these tests in aarch64 Quarkus TS runs?

**Comment by cescoffier** [comment]
Fixed.
