### ISSUE TITLE
Native image/runner/executeable generation influenced by CI ENV variables

### ISSUE THREAD

**Issue by ineednousername** [quarkusio/quarkus#17892]
Not sure if this is a bug or intended feature.
**Quarkus version 1.11.7.Final**

## Describe the bug
We create native quarkus like e.g.: `mvn install -Dnative`
Several run- and buildtime properties are specified in a application.properties/yaml
One of those properties is named for example `my.app.enabled=true`.
Our CI environment, where the native image is build/created, has several ENV variables.
When running `mvn install -Dnative` the env variables may override the default properties defined in application.properties
e.g. when a `export MY_APP_ENABLED=false` exists the my.app.enabled will be overridden and the new default in the native runner will be false.
That `my.app.enabled=false` is slightly irritating when running the application on the target system without any override, through a ENV variable MY_APP_ENABLED=false, of my.app.enabled. 
   
is this a bug or the intended behavior?

### Actual behavior
**Open a shell**

`export MY_APP_ENABLED=false`
while having a application properties stating `my.app.enabled=true` and an app which is logging the value on startup
run `mvn install -Dnative` produce a native runner
 
**Open a new shell**  (without export MY_APP_ENABLED)
start the produced runner
`./target/my-app-0.0.1-SNAPSHOT-runner ` 
will log "is app enabled = false"

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
We do exclude the properties coming from the `EnvSource` in build time so they are not recorded, but if a property requires recording the value may still be looked up on the `EnvSource` and in this case, the environment value is recorded in the native image as the value to use (and not the one in `application.properties` for instance).

I'll need to think a little bit on how to workaround this.

**Comment by ineednousername** [comment]
@radcortez so to wrap up my question, it is an unintended behavior ?

**Comment by radcortez** [comment]
Yes, I've pushed a fix for it in #18104.
