### ISSUE TITLE
Quarkus build docker images should emit warning when pom.xml have no "Container Image extensions"

### ISSUE THREAD

**Issue by kafeltz** [quarkusio/quarkus#17901]
## Description

When doing `./mvnw clean package` it does not emit any warning/error trying to create a docker image and/or pushing it.

It took me some hours to find out that I must put an **Container Image extensions** like this one:
```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-container-image-docker</artifactId>
</dependency>
```

I know that info is writting in the guide: https://quarkus.pro/guides/container-image.html but would be nice an warning instead of "nothing" because I forgot that part and this would save people wasting time figuring this out.

Thx

**Comment by geoand** [comment]
@radcortez I wonder if we should also be emitting a warning at build time if a config property does not map to Quarkus Config object

**Comment by radcortez** [comment]
We should be able to do it for build time as well.
