### ISSUE TITLE
add extensions in gradle

### ISSUE THREAD

**Issue by cniweb** [quarkusio/quarkus#1790]
Implement functionality to automatically add extensions to your Gradle project

**Comment by cniweb** [comment]
An initial implementation already exists, but unfortunately without function:
https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusAddExtension.java

**Comment by stalep** [comment]
Hi, yes it's on our todo :)

**Comment by dhoffi** [comment]
well, not being able to addExtension makes the gradle support pretty limited useful ... doesn't it?

**Comment by cniweb** [comment]
@dhoffi Yes, you are right, that makes the support of Gradle quite limited useful

**Comment by Dufgui** [comment]
duplicate of #3102

**Comment by Dufgui** [comment]
@aloubyansky could you assign to me or close it. Please. I have done the based of it in #3415   We just need to call it from the task
