### ISSUE TITLE
@AroundConstruct method returning Object works only if it's private

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#1791]
`InterceptorGenerator` incorrectly assumes that return type from an `@AroundConstruct` method is void, but the specification allows `Object` too (https://docs.oracle.com/javaee/7/api/javax/interceptor/AroundConstruct.html). 

When the method is private, it will work because `InterceptorGenerator` will use a reflection fallback and find the method to invoke by name and param types only (so the return type doesn't matter): https://github.com/quarkusio/quarkus/blob/0.12.0/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/InterceptorGenerator.java#L245

**Comment by mkouba** [comment]
Well, it is allowed and it's IMHO quite useless and misleading. But the truth is that in theory it should be possible to intercept both `AroundConstruct` and `AroundInvoke` with one method and so we should fix it.
