### ISSUE TITLE
Missing section in Migration Guide about NamedClient => GraphQLClient

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#17912]
Add section about NamedClient => GraphQLClient shift into https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0

Motivation: It's a breaking change for end user applications, application doesn't compile anymore
Example of QS update: https://github.com/quarkusio/quarkus-quickstarts/pull/886/files

**Comment by jmartisk** [comment]
This applies to the `smallrye-graphql-client` extension, but that is new in Quarkus 2.0, so I'd say it can't affect 1.x users' migration.

**Comment by phillip-kruger** [comment]
Agree, this is new in 2.0
