### ISSUE TITLE
Maven Plugin always adds a quarkus-resteasy dependency even without RestEasy extension

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#17920]
## Describe the bug

When creating a new project with the Maven Quarkus plugin, the `quarkus-resteasy` dependency is always added to the `pom.xml` even when we don't add a RestEasy extension.

### Expected behavior

The `quarkus-resteasy` dependency should not be added to the `pom.xml` when none of the following extension is selected: resteasy, resteasy-reactive or spring-web.

## To Reproduce

I'm generating several applications related with database access without RestEasy. So here are the 3 scripts I am using:

```
$ mvn -U io.quarkus:quarkus-maven-plugin:create \
                    -DprojectGroupId=org.agoncal.course.quarkus.orm \
                    -DprojectArtifactId=artist \
                    -DpackageName="org.agoncal.quarkus.jdbc" \
                    -Dextensions="jdbc-mysql, quarkus-agroal"

$ mvn -U io.quarkus:quarkus-maven-plugin:create \
                    -DprojectGroupId=org.agoncal.course.quarkus.orm \
                    -DprojectArtifactId=customer \
                    -DpackageName="org.agoncal.quarkus.jpa" \
                    -Dextensions="jdbc-mariadb, hibernate-orm"

$ mvn -U io.quarkus:quarkus-maven-plugin:create \
                    -DprojectGroupId=org.agoncal.course.quarkus.orm \
                    -DprojectArtifactId=vintage-store \
                    -DpackageName="org.agoncal.quarkus.panache" \
                    -Dextensions="jdbc-postgresql, hibernate-orm-panache"
```

All these 3 projects have the `quarkus-resteasy` dependency but shouldn't.

BTW, the `-U` pulls the latest version of the plugin, which is 2.0.0.CR3 in my examples.

### Output of `uname -a` or `ver`

Darwin iMac-Pro-de-Antonio.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

### Quarkus version or git rev

2.0.0.CR3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec

**Comment by geoand** [comment]
This has long been fixed
