### ISSUE TITLE
Quarkus CLI create app to move to created directory

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#17927]
## Description

Currently, when you create an application in either batch mode or normal mode the current directory remains the same. From a user perspective, it can be assumed that after you have created your app you want to do additional quarkus CLI tasks like add an extension or build the project so it would feel more natural if the Quarkus CLI in interactive mode changed the current directory to the newly created application.

## Implementation ideas

I think it makes sense to move to the directory of the newly created application in interactive mode, while it remains in the current directory in batch mode.

**Comment by ebullient** [comment]
@tqvarnst

1) batch mode vs. not for automatic directory change
2) message at the end of command output reminding you to change directories.

We spoke a bit about unexpected behavior if you blindly create more than one (where the automatic cd would then end up with you creating nested projects unintentionally) .. 

Would a message (or even a prompt?!) when not in batch mode make the difference?

**Comment by axblu** [comment]
Changing the directory automatically after executing something in the shell is not what I would expect.

**Comment by tqvarnst** [comment]
Different tools seem to have different ways to do this. Some will stay in the current directory and some will move you to the application directory.  While I agree that for complex use-cases where you create multiple projects it's not optimal to have to run `cd ..`. For simpler use-cases and demos it's however nice to not have `cd <artifact-id>` into the directory before running for example `quarkus dev`.

If we had a possibility to provide a local configuration (see RFE #17949) we could have a setting that allows moving to the application directory after the creation that could default to not do that, but for users that prefer that behaviour they could set their local config to make the CLI behave like this.

**Comment by ebullient** [comment]
I will chew on it, but, sans a local config option to bypass it, a simple yes/no prompt (when running in interactive mode) could do the job (and make it obvious it happened).

**Comment by tqvarnst** [comment]
My view of interactive mode is that it's a great tool to make people understand what features are available like it could be used to prompt the user for code examples etc, but it should be possible to skip it by passing a parameter. E.g. the yes/no prompt to change to the current directory could be good if you can also pass `--cd` or `--nocd` to avoid that prompt being displayed.

**Comment by maxandersen** [comment]
Can anyone point to a tool that CDs into a just created project ?

I've not been able to find one but please educate :)

Also afaik youll need to do a native call to be able to change the directory of the shell that invoked java ... 

In short: I'm not fan of trying to make the cli attempt to change process.

**Comment by ebullient** [comment]
well. quarkus create would have to return no other output (no pretty emoji) .. only the name of the directory created to allow you to do that
which is not what is required

**Comment by maxandersen** [comment]
Not just java. Neither python nor go or anything can change the directory of the calling shell in any reliable way as default on Linux is to have a copy of the environment including current directory. 

Thus unless someone can show existing clis has this behaviour without Shell specific tricks i suggest we reject this.

**Comment by ebullient** [comment]
#18319 updates create output with the following: 
```
Creating an app (default project type, see --help).
-----------

applying codestarts...
📚  java
🔨  maven
📦  quarkus
📝  config-properties
🔧  dockerfiles
🔧  maven-wrapper
🚀  resteasy-codestart

-----------
[SUCCESS] ✅  quarkus project has been successfully generated in:
--> /Users/elh/git/quarkusio/quarkus/devtools/cli/target/code-with-quarkus
-----------
Navigate into this directory and get started: quarkus dev
```
