### ISSUE TITLE
publish gradle plugin to the gradle plugin portal

### ISSUE THREAD

**Issue by cniweb** [quarkusio/quarkus#1793]
Publish gradle plugin to the gradle plugin portal.

How it works, see:
https://plugins.gradle.org/docs/submit

**Comment by stalep** [comment]
It is also in the todo :)

**Comment by Sanne** [comment]
Added it to the list of issues we should have for 1.0

**Comment by Dufgui** [comment]
I create a merge request to have better information display in gradle portal.
So now you must create a quarkus release account in gradle portal : 
https://plugins.gradle.org/user/register

Get the API Keys :
```gradle.publish.key=<key>
gradle.publish.secret=<secret>
```

So to do it, during the release process, you must call in `devtools/gradle` (with key and secret replace by the previous API Keys values) :
```
gradle publishPlugins -Pgradle.publish.key=<key> -Pgradle.publish.secret=<secret>
```
No more

**Comment by Sanne** [comment]
Reopening as it's not published yet.

**Comment by gsmet** [comment]
Raaah, it was closed automatically by the PR. Thanks @Sanne

**Comment by patoessy** [comment]
Why is this always been moved to another milestone? Is it always hard to publish?

**Comment by patoessy** [comment]
How can I assist?

**Comment by maxandersen** [comment]
duplicate of https://github.com/quarkusio/quarkus/issues/4311 which has a bit more context of why its relevant to push.
