### ISSUE TITLE
@QuarkusTestResource stopped being started from custom annotation

### ISSUE THREAD

**Issue by MarcoMartins86** [quarkusio/quarkus#17930]
## Describe the bug
When I create an annotation (`@MyTestAnnotation` in repo code that reproduces this) for defining common `@QuarkusTest` and `QuarkusTestResource` annotations and use it to create tests, it will not launch the Quarkus Test Resources since version 1.13.1.Final, and so the test will fail.

### Expected behavior
Quarkus Test Resources should be launched like in 1.11.7.Final, 1.12.2.Final and 1.13.0.Final and tests should pass.

### Actual behavior
Quarkus Test Resources are not launched since 1.13.1.Final and tests fail.

## To Reproduce

Clone code from https://github.com/MarcoMartins86/test_annotation_issue
Docker is needed.

1. In a terminal `cd old_version` and run `./mvnw clean install` -> Tests will pass.
2. In a terminal `cd new_version` and run `./mvnw clean install` -> Tests will fail.

### Output of `uname -a` or `ver`
Darwin PT-320323-MBP16 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

### Output of `java -version`
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

### Quarkus version or git rev
1.13.1.Final and onwards

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/marco.martins/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home
Default locale: en_PT, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by famod** [comment]
@geoand I suppose this has something to do with #16112

**Comment by geoand** [comment]
Dunno would have to check.

@MarcoMartins86 does this same issue occur with `1.13.7.Final` as well?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/17941 takes care of the issue.

For the time being, @MarcoMartins86 you can get around the issue by using 

```
@QuarkusTestResource(RedisTestResource.class)
```

instead of 

```
@QuarkusTestResource.List({
        @QuarkusTestResource(RedisTestResource.class)
})
```

**Comment by MarcoMartins86** [comment]
Thank you for the insights @geoand. In the meanwhile, I tried your workaround and found out what I think is another issue.
Using the custom annotation with the `@QuarkusTestResource(RedisTestResource.class)` the resource will behave like it has the `restrictToAnnotatedClass = true` flag when annotated on the test class directly. Basically, it is being started per test instead of the expected just once per run. Can you confirm that this is also an issue?

**Comment by geoand** [comment]
That is the expected behavior

**Comment by MarcoMartins86** [comment]
Ok, I didn't know about that because in 1.11.7.Final it was behaving as I described.

**Comment by geoand** [comment]
Right, that was by accident :)

**Comment by famod** [comment]
Does this mean that if you run 3 subsequent tests that all have the same meta annotation, the resource started and stopped three times?

**Comment by geoand** [comment]
Yes

**Comment by famod** [comment]
Hm, I must say I find this rather counter-intuitive. I was about to ask if `@TestProfile` behaves the same but AFAICS you cannot use it in a meta annotation.
