### ISSUE TITLE
hibernate-orm mixed usage for `persistence.xml` and quarkus default settings

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#17937]
## Description

Currently, I need to set `hibernate.metadata_builder_contributor` parameter in `persistence.xml` to customize some trigger/custom indexes, since quarkus hibernate-orm extension doesn't support this property yet.

However, I really love the idea that quarkus automatically choose proper and modern default setting for us, since I'm not hibernate expert so I'm happy to keep those nice default setting, but with a little bit customization from `persistence.xml`

For now, is there any way to mix use regarding `persistence.xml` and quarkus own default settings? (say, properties in `persistence.xml` will overwrite quarkus own settings.)

I'm not sure if we already have this feature or not....from the document I can not find the behavior when users explicit give a `persistence.xml`

**Comment by yrodiere** [comment]
Using `persistence.xml` for some persistence units and `application.properties` for others should work, but using both for the same persistence unit does not, and we don't plan to support that. See #16589.

At the end of the day, what you really need is for #13807 to get fixed, and that has already happened in Quarkus 2.0 (currently in the candidate release phase). See [here](https://quarkus.io/version/main/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.metadata-builder-contributor).

As to other configuration properties... I've been saying we need some way to set arbitrary Hibernate ORM properties in `application.properties`, with clear indications that those are not, and never will be supported (i.e. if they don't work, tough luck, open a ticket to get a dedicated, supported configuration property but the unsupported one will never get better).

But that's a minority point of view and I think it's unlikely to happen. There are various reasons this is not allowed, mostly to avoid combinatorial explosions in the amount of configurations we need to support, especially for old, deprecated configuration knobs (of which Hibernate ORM has many).

**Comment by liuzqt** [comment]
@yrodiere  thanks for the detailed explanation! I agree with you that there is no point to support legacy configuration things from hibernate.  
And #13807 is exactly what I want, and I think this is a reasonable and mostly helpful feature to have, glad we already have it in 2.0.   For now, I would probably use the workaround mentioned in #13807 to make my program work, but it doesn't matter since 2.0 is coming out very soon. 
Thanks again for your help!

**Comment by liuzqt** [comment]
@yrodiere  and BTW I've read through your opinion in #16951 when fixing #13807. I understand `xxx_contributor` things might already be some adhoc things...... I'm totally new to hibernate (I'm from python....) and just try to get some equivalent things in Java and hibernate.  So I would like to know if I was doing the right thing:
I mainly used `metadata_builder_contributor` to add `AuxiliaryDatabaseObject`, where I can add customized index in hbm2ddl like GIN/GIST/SP-GIST which is a specific index type only supported in `postgres`, hibernate doesn't support this in his APIs as well so `AuxiliaryDatabaseObject` is the way I try to bypass this constraint.

**Comment by yrodiere** [comment]
>  So I would like to know if I was doing the right thing:

Yes, this is definitely a legitimate use case. I haven't tested this specifically, but I expect it should work.

**Comment by liuzqt** [comment]
thanks for the help! I will close this issue.
