### ISSUE TITLE
Support Azure AD OIDC with certificate secrets

### ISSUE THREAD

**Issue by roysjosh** [quarkusio/quarkus#17952]
## Describe the bug
Attempting to exchange the OIDC authorization code for tokens using a certificate fails with the following:
`
2021-06-15 11:14:07,469 DEBUG [io.qua.oid.run.OidcProviderClient] (vert.x-eventloop-thread-1) Request has failed: status: 400, error message:`
```json
{
  "error": "invalid_request",
  "error_description": "AADSTS5002723: Invalid JWT token. No certificate thumbprint nor keyId specified in token header.\r\nTrace ID: babe3807-af83-4be8-9595-9157adca0700\r\nCorrelation ID: 7d627715-bfd6-42e5-b6fa-f7b3b3a1460b\r\nTimestamp: 2021-06-15 15:14:07Z",
  "error_codes": [
    5002723
  ],
  "timestamp": "2021-06-15 15:14:07Z",
  "trace_id": "babe3807-af83-4be8-9595-9157adca0700",
  "correlation_id": "7d627715-bfd6-42e5-b6fa-f7b3b3a1460b"
}
```

### Expected behavior
Certificate secrets should function.

### Actual behavior
Error from AAD.

### Configuration
```java

        // get tenantId from request

        config.setTenantId(tenantId);

        config.setApplicationType(ApplicationType.WEB_APP);

        List<String> scopes = Arrays.asList(
            "profile", "email",
            // request refresh_token
            "offline_access",
            // request app's static permissions
            "https://graph.microsoft.com/.default");
        config.getAuthentication().setScopes(Optional.of(scopes));

        String authServerUrl = "https://login.microsoftonline.com/" + tenantId + "/v2.0";
        config.setAuthServerUrl(authServerUrl);

        String clientId = "REDACTED";
        config.setClientId(clientId);

        config.getCredentials().jwt.keyStoreFile = Optional.of("/path/to/test.jks");
        config.getCredentials().jwt.keyStorePassword = "REDACTED";
        config.getCredentials().jwt.keyId = Optional.of("1");
        config.getCredentials().jwt.keyPassword = "REDACTED";
        config.getCredentials().jwt.jwsKeyId = Optional.of("REDACTED");

        config.getAuthentication().setRedirectPath("/aad");
        config.getAuthentication().setRestorePathAfterRedirect(true);

        // cookie is WAAAAY too big for Firefox without this
        config.tokenStateManager.setSplitTokens(true);

        config.setTenantEnabled(true);

```

### Output of `uname -a` or `ver`
Darwin mac62151.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Corretto-16.0.1.9.1 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Corretto-16.0.1.9.1 (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev
1.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Amazon.com Inc. 16.0.1+9)
OS:           Mac OS X 10.15.7 x86_64

## Additional context
If this simplistic approach works, I'd be happy to put it in a PR:

```diff
diff --git a/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java b/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java
index 60d53bb4af..0398c0c390 100644
--- a/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java
+++ b/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonConfig.java
@@ -209,6 +209,12 @@ public class OidcCommonConfig {
             @ConfigItem(defaultValue = "password")
             public String keyPassword;

+            /**
+             * The JWS keyId, the base64-encoded SHA-1 digest of the DER-encoded certificate
+             */
+            @ConfigItem
+            public Optional<String> jwsKeyId = Optional.empty();
+
             /**
              * JWT life-span in seconds. It will be added to the time it was issued at to calculate the expiration time.
              */
diff --git a/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java b/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java
index e9cb3de936..7a057b3296 100644
--- a/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java
+++ b/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java
@@ -207,6 +207,9 @@ public class OidcCommonUtils {
         if (key instanceof SecretKey) {
             return builder.sign((SecretKey) key);
         } else {
+            if (oidcConfig.credentials.jwt.jwsKeyId.isPresent()) {
+                return builder.jws().keyId(oidcConfig.credentials.jwt.jwsKeyId.get()).sign((PrivateKey) key);
+            }
             return builder.sign((PrivateKey) key);
         }
     }
```

**Comment by sberyozkin** [comment]
Hi @roysjosh thanks for identifying this problem, please open a PR, here is some initial comments:

> The JWS keyId, the base64-encoded SHA-1 digest of the DER-encoded certificate

key id `kid` is only a key id, ` the base64-encoded SHA-1 digest of the DER-encoded certificate` is a certificate thumbprint of the certificate Azure will use to verify this token and I don't really expect the Quarkus users know these values, it should be calculated during the token creation process and since we only support the token encryption with the public certificates I believe the certificate thumbprint property is not needed yet.
I propose to call this new property `tokenKeyId` - and doc it as a `Token key identifier` - however - can you confirm please the key store key alias is not same as the token key identifier ?

Also, note in `2.0.0.CR3`, you can use `smallrye.jwt.new-token.key.id` property can be used to set key id to the newly created tokens. Or you can load a key from a `keyFile` in a JWK format and the key id will be set as well. 

```
+            if (oidcConfig.credentials.jwt.jwsKeyId.isPresent()) {
+                return builder.jws().keyId(oidcConfig.credentials.jwt.jwsKeyId.get()).sign((PrivateKey) key);
+            }
```

I think this key id, if set, should be set on the builder earlier, so it works for secret or pem keys as well, so please do:
```
JwtSignatureBuilder builder = Jwt
                .issuer(oidcConfig.clientId.get())
                .subject(oidcConfig.clientId.get())
                .audience(getAuthServerUrl(oidcConfig))
                .expiresIn(oidcConfig.credentials.jwt.lifespan).
                .jws();
if (key id set) {
   builder.keyId(...);
}

```

thanks

**Comment by sberyozkin** [comment]
@roysjosh I've removed a `kind/bug` label since this requirement is specific to Azure - we have the tests where the client JWT authentication works with Keycloak without this property, thanks

**Comment by sberyozkin** [comment]
@roysjosh 

> I just tried to use my private key as a JWK with the proper kid both in the JWK and set as the config.getCredentials().jwt.keyId. 
> This did not seem to add a kid to the JWT header as I again received the same error from AAD.
> I have also set smallrye.jwt.new-token.key.id on Quarkus 999-SNAPSHOT which similarly doesn't seem to work.

My fault, it only works if the no arg `sign()` is used, here the key is loaded directly.
However the new property should also work for this case, let me comment on your PR
