### ISSUE TITLE
quarkus-bom v1.13.x brings incompatible opentracing-api via opentracing-tracerresolver

### ISSUE THREAD

**Issue by grossws** [quarkusio/quarkus#17960]
## Describe the bug
`quarkus-bom` use `opentracing-tracerresolver:0.1.8` which depends on `opentracing-api:0.33.0`. It's API-incompatible with `opentracing-api:0.31.0` used in MicroProfile/SmallRye.

It shouldn't affect Maven users because of different dependency resolution process but in case of Gradle it bumps `opentracing-api` to v0.33.0.

Workarounds:
* use `enforcedPlatform` for `quarkus-bom`/`quarkus-universe-bom`;
* use gradle version constraint for `io.opentracing:opentracing-api`.

### Expected behavior
`opentracing-tracerresolver` pinned at `v0.1.5` until `smallrye-opentracing` is updated to 2.0.0.

### Actual behavior
See above. Trace:

```
java.lang.NoSuchMethodError: 'io.opentracing.Scope io.opentracing.ScopeManager.active()'
        at io.jaegertracing.internal.JaegerTracer.activeSpan(JaegerTracer.java:195)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.activeSpan(QuarkusJaegerTracer.java:115)
        at io.opentracing.util.GlobalTracer.activeSpan(GlobalTracer.java:148)
        at io.quarkus.smallrye.opentracing.runtime.TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.activeSpan(TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.zig:199)
        at io.opentracing.contrib.jaxrs2.server.ServerTracingFilter.parentSpanContext(ServerTracingFilter.java:107)
        at io.opentracing.contrib.jaxrs2.server.ServerTracingFilter.filter(ServerTracingFilter.java:73)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:312)
```

## To Reproduce

https://gist.github.com/grossws/4e44830c80de63f28c109b4275d606a7 (put `TestResource.java` into `src/main/java/t/`

1. `./gradlew quarkusDev`
2. `curl http://localhost:8080/test`

### Output of `uname -a` or `ver`
`Linux unterwelt 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```

### Quarkus version or git rev
`1.13.7.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7)
OS:           Linux 5.12.9-arch1-1 amd64
```

**Comment by kenfinnigan** [comment]
I don't think we want to update the version of a dependency because Gradle handles the dependency resolution differently.

`0.1.8` has been used in Quarkus since at least 1.7.0.Final. Changing the dependency now would potentially introduce a large number of unintended breakages.

**Comment by grossws** [comment]
I looked through https://github.com/opentracing-contrib/java-tracerresolver/commits/release-0.1.8 and two major changes besides opentracing version bump are:
* automatic module name for java9+;
* new method `TracerResolver.resolveTracer(ClassLoader)`.

So I agree, it's potentially breaking change if someone depends on it.

OTOH Maven unstable resolution management could be breaking all the same. If someone added `io.smallrye:smallrye-opentracing` alongside `io.quarkus:quarkus-smallrye-opentracing` in Maven project `opentracing-api` version would depend on order of that dependencies.

**Comment by kenfinnigan** [comment]
While I agree it relies on Maven behaving, but at the same time, we've had this in since 1.7.0.Final, possibly earlier as the file location moved at one point. For that reason, I don't think it's worth the risk.

**Comment by aloubyansky** [comment]
Is using `enforcedPlatform` not an acceptable option in this case?

**Comment by aloubyansky** [comment]
Here is a bit more on the nature of Quarkus BOMs.

`quarkus-universe-bom` is a result of integrating various extensions developed by separate teams, making sure all those extensions do not conflict with each other in any combination. That is achieved by aligning their **transitive** dependencies that work for everybody. Importing the universe BOM using `platform` in Gradle will ignore the alignment between the extensions and will result in their original transitive dependencies pulled into the app, which isn't safe (i.e. no guarantee the app will build and/or run).

`quarkus-bom` is composed differently but it's not a coincidence that `enforcedPlatform` appears to fix your issue.

I would still be interested to know whether `enforcedPlatform` causes any issue in your case. I don't recall anybody raising it yet. Thanks.

**Comment by aloubyansky** [comment]
> OTOH Maven unstable resolution management could be breaking all the same. If someone added `io.smallrye:smallrye-opentracing` alongside `io.quarkus:quarkus-smallrye-opentracing` in Maven project `opentracing-api` version would depend on order of that dependencies.

I see that `quarkus-bom` contains `opentracing-api`, which means the order of imports of the mentioned dependencies is irrelevant. The version of `opentracing-api` is managed by the BOM unless explicitly overridden in the app config. It would depend on the order of dependency declarations if you **did not** import the `quarkus-bom`. BTW, in both cases the resulting dependency tree is 100% predictable.

**Comment by grossws** [comment]
I usually use simple `platform` instead of `enforcedPlatform` to avoid overriding dependency constraints defined in my own platforms, especially if framework-provided BOM/platform has large scope like `quarkus-universe-bom` or `spring-boot-dependencies`.

[As I learned](https://gradle-community.slack.com/archives/CAH4ZP3GX/p1623938634097500) this is expected behavior for Gradle when using `platform` instead of `enforcedPlatform`, so I'm closing this issue. I hope it'll save someone time in case of similar issues.

> I would still be interested to know whether enforcedPlatform causes any issue in your case. I don't recall anybody raising it yet. Thanks.

Off the top of my head I recall I had such issue when using newer version of Apache James Mime4j alongside with RESTEasy's mime-multipart-provider. So I now usually avoid using `enforcedPlatform` and try to be very careful with BOM imports order in Maven's `dependencyManagement`.
