### ISSUE TITLE
Add info about Logger into Quarkus Opentracing guide

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#17974]
## Description
By following guide: https://quarkus.io/guides/opentracing  
It is not fully obvious that OpenTracing requires Logger to be defined inside each @Traced class to present logs properly.  
*By bootstrapping project there is no Logger predefined in the example class (no codestart).  

## Implementation ideas
Add a note that each @Traced class requires Logger to be defined in order to show `traceId=xxx parentId=xxx spanId=xxx` in the logs.

**Comment by kenfinnigan** [comment]
We're open to community contribution for this, as we aren't working on OpenTracing anymore but OpenTelemetry instead
