### ISSUE TITLE
ID-based invalidation of the bootstrap CP cache

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#1797]
Current bootstrap classpath cache invlidation is based on a latest timestamp of a pom.xml in the workspace. That potentially could not be enough in case some of the pom.xml files get updated (from a remote repository) with a timestamp that appears to be earlier than the recorded latest one, resulting in the CP cache not being invalidated.
Instead of relying on the latest timestamp, some kind of hash value should be calculated using the timestamps of all the pom.xml files in the workspace and used as the CP cache validity ID.

**Comment by kenfinnigan** [comment]
Is it not possible to use the Maven metadata in the local repository for an artifact to know if it was updated?

**Comment by aloubyansky** [comment]
@kenfinnigan possibly. Another requirement though is that it has to be fast, which is why I'm looking for a solution which is kind of on the surface. I am going to get a hold of the pom.xml files no matter what, so they will be right there for me. Reading artifact descriptions will mean creating requests and interpreting the results which will cost more and then I'll still have to be tracking updates per artifact. So I'll pursue what seems to be simpler first. Unless you see a problem with that. Thanks.
