### ISSUE TITLE
Elasticsearch reactive client

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#17996]
## Describe the extension
Provides a reactive Elasticsearch client based on the Mutiny variant of the reactiverse Elasticsearch client: https://github.com/reactiverse/elasticsearch-client

I made some early testing of th library and it's easy to integrate inside Quarkus so it's not a lot of work to provides an extension for it, I can do it quickly as soon as we have an agreement that such extension provides value.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

## Configuration suggestion
Re-use the same configuration properties as the current Elasticsearch client extension.

**Comment by yrodiere** [comment]
FWIW the official Elasticsearch client (for which we already have an extension) is asynchronous and non-blocking, so it's easy to make it reactive with a simple wrapper. We do that in Hibernate Search: https://github.com/hibernate/hibernate-search/blob/9372a6788f033f6ec68182df28ecb0543a861afd/backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/client/impl/ElasticsearchClientImpl.java#L112-L134

**Comment by yrodiere** [comment]
Though I suppose the reason you want to use the client from reactiverse is to avoid Apache HTTP Client, which uses its own, dedicated thread pool.

**Comment by loicmathieu** [comment]
@yrodiere the reason is also to have Mutiny return types and avoid re-creating my own wrapper, so it's easier to integrate it this way.
For the thread pool, yes, I assume it will use the Vert.x eventloop as it's tightly integrated with Vert.x so it will smoothly integrate with Quarkus reactive core. @jponge may know more about this.

**Comment by loicmathieu** [comment]
@yrodiere at first I also propose to create a wrapper around the Elasticsearch client, this is what we did for Mongodb, see the discussion on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Reactive.20Elasticsearch

**Comment by yrodiere** [comment]
Ah, I see this is about the high-level client. I was talking about the low-level one, which is little more than a simple HTTP client, which is why I was a bit surprised.

Nevermind what I was saying, creating a wrapper for the high-level client manually would indeed be too much work.

**Comment by loicmathieu** [comment]
Implemented inside the Quarkiverse => https://github.com/quarkiverse/quarkus-elasticsearch-reactive
