### ISSUE TITLE
Application title in Swagger UI may overlap with the path input box

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#18019]
## Description
 The application title may overlap with the path input box

![Screenshot_20210619-122957_Chrome](https://user-images.githubusercontent.com/54133/122647277-d1c95980-d0f9-11eb-9fa1-3a901b14a4a9.jpg)

## Implementation ideas

One idea is to move the application title to appear in the bottom-left footer

**Comment by phillip-kruger** [comment]
Thanks, I know about this:) plan is to make is more responsive. So on small screens hide the application name
