### ISSUE TITLE
shared application properties among several subproject

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#18015]
## Description

I have several sub projects under a mono repo, those projects are similar microservices and sharing some common library(also under the same mono repo). So it would be nice if we can share application properties among several sub projects.

I'm not sure if we already have this feature, I go over all the guides but haven't found one.

## Implementation ideas

Maybe some properties under the root dir, and sub project will automatically pickup these common things. I'm using gradle to organize my multi-project repo, and gradle is comfortable to work with multi-project layout, so I guess there should be some ways to do this.

**Comment by gsmet** [comment]
I think we have such a feature but I don't know if it's already available or only in the upcoming 2.0. @radcortez would know for sure.

**Comment by radcortez** [comment]
This was implemented in https://github.com/quarkusio/quarkus/pull/15282 and available since `1.13.0.Final`.
