### ISSUE TITLE
gRPC port issue

### ISSUE THREAD

**Issue by venkatt007** [quarkusio/quarkus#18025]
## Describe the bug
When I start grpc service in dev mode it takes both 8080 and 9000 ports

### Expected behavior
When I run a grpc application with quarkus it should use only 9000 port or the grpc server port alone so that I can run multiple grpc applications in dev mode

### Actual behavior

I ran a grpc application with quarkus grpc dependency alone. It takes both 8080 and 9000 ports. Due to this not able to run two grpc applications in same time and throws 8080 port is already used when starting second application

## To Reproduce
Create a grpc application with quarkus grpc extension alone. Run the service. Both 8080 and 9000 will be blocked and it will show the running pids

I am trying this with quarkus 2.0.0.CR3 version in my windows 10 laptop

Using graalvm 11 as my java version

**Comment by michalszynkiewicz** [comment]
It's probably to expose the dev mode UI, you can access it on `http://localhost:8080/q/dev`.
Why is this a problem for you?

**Comment by venkatt007** [comment]
Can I change the port for that ? It causing troubles when I run multiple services. The second service also trying to use the same dev ui port. That the issue.

**Comment by venkatt007** [comment]
Is there a way to disable this when running in production?

**Comment by cescoffier** [comment]
You can change the http port with: quarkus.http.port

The dev console is disabled in prod mode (even in test mode).

**Comment by venkatt007** [comment]
My issue is cleared used 8081 port instead of 8082. Thanks for the help
