### ISSUE TITLE
SqsListener Annotation

### ISSUE THREAD

**Issue by ericsouza** [quarkusio/quarkus#18020]
## Description

Is there any plan to add or a documented way to have a  `SqsListener` annotation for consuming messages like in Spring Cloud?

**Comment by gsmet** [comment]
Maybe you could point to more details about what you expect?

**Comment by ericsouza** [comment]
Something similar to what Spring Cloud does [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.0.0.RELEASE/multi/multi__messaging.html#_annotation_driven_listener_endpoints)

 where we can consume a Sqs Queue just by adding the `SqsListener` annotation to a method that receive the content of the message as an object

**Comment by ericsouza** [comment]
Closing this as smallrye-reactive-messaging now supports SQS 🚀 🎉
