### ISSUE TITLE
Artemis JMS guide, small correction

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#18032]
## Description
For the JMS guide: https://quarkus.io/guides/jms 
in order to get the artemis part to work I had to do one additional change

https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/jms.adoc

https://quarkus.io/guides/jms#configure-the-artemis-properties

## Implementation ideas
I also had to change the broker.xml file according to this:
https://github.com/quarkusio/quarkus-quickstarts/blob/main/jms-quickstart/src/test/resources/broker.xml

**Comment by gsmet** [comment]
@lthasle any chance you could prepare a pull request?

**Comment by gsmet** [comment]
No news for a while, closing as I have no idea what actually requires a change.
