### ISSUE TITLE
Resteasy-reactive produces invalid json for Multi

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#18043]
## Describe the bug
While using Multi<String> as a return value for a method annotated with `@Produces(MediaType.APPLICATION_JSON)`, the returned json looks like an array(it uses square brackets around the results), but lacks quotation marks around the strings inside e.g. `[Hello,Hola]` instead of `["Hello","Hola"]`. Adding quarkus-resteasy-reactive-jackson to a classpath does not solve the problem.

### Expected behaviour
Any of the following:
Returning of valid json array (`["Hello","Hola"]`)
Returning values one-by-one
Compilation error

### Actual behavior
Invalid json array(`[Hello,Hola]`)

## To Reproduce

Link to a reproducer:
```
git clone git@github.com:fedinskiy/reproducer.git -b multi-jackson
```
1. `mvn clean quarkus:dev`
2. `curl -w'\n' localhost:8080/hello/multi`
Or:
1. `mvn clean test`

### Output of `uname -a` or `ver`
`Linux localhost.localdomain 5.12.10-300.fc34.x86_64 #1 SMP Thu Jun 10 14:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
### Output of `java -version`
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment GraalVM CE 20.3.2 (build 11.0.11+8-jvmci-20.3-b15)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.2 (build 11.0.11+8-jvmci-20.3-b15, mixed mode, sharing)
```
### Quarkus version or git rev
2.0.0.CR3
OR
1.13.7.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 

May be somehow connected to https://github.com/quarkusio/quarkus/issues/14183

**Comment by oliver-brm** [comment]
The items in the `Multi<String>` hit a condition in [`JacksonMessageBodyWriterUtil`](https://github.com/quarkusio/quarkus/blob/4a057ec392f4e7e4f0733a61d52a5151bbd1896a/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson-common/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/JacksonMessageBodyWriterUtil.java#L47):

```java
if (o instanceof String) { // YUK: done in order to avoid adding extra quotes...
    entityStream.write(((String) o).getBytes());
} else {
    ...
```

Removing this condition would fix this issue but I'm not sure if it would raise other issues.

**Comment by geoand** [comment]
> Removing the condition would fix this issue but I'm not sure if it would raise other issues.

Unfortunately it would

**Comment by StephenOTT** [comment]
Is there a workaround for this?
