### ISSUE TITLE
Reactive SQL Client Documentation Missing Information

### ISSUE THREAD

**Issue by ethan-gallant** [quarkusio/quarkus#18056]
## Describe the bug
In the docs here https://quarkus.io/version/main/guides/reactive-sql-clients it says to create prepared statements with `$1 $2 $3` etc. However, this appears to be Postgres specific as the Vert.x MySQL reactive library expects arguments to be passed as Question marks `?`.

### Expected behaviour
The docs should have a bubble stating that `?` should be used for MySQL and `$1,$2,$3` etc is only applicable for Postgres SQL.

## Additional context
Not sure if I am missing anything here or if it's already been documented. I am not sure what the best way to iterate this information in the docs, but I would be glad to open a PR.

**Comment by tsegismont** [comment]
Thanks for pointing this out @ethan-gallant . I will update the doc
