### ISSUE TITLE
 maven-shared-utils@3.2.1 Security Vulnerability: Command Injection 

### ISSUE THREAD

**Issue by xmlking** [quarkusio/quarkus#18050]
## Describe the bug
My company nexus blocked quarkus-ide-launcher due to the following Vulnerability.
https://snyk.io/vuln/maven:org.apache.maven.shared:maven-shared-utils@3.2.1

### Expected behavior
Should not have dependencies issues with quarkus latest version. 

### Actual behavior
(Describe the actual behavior clearly and concisely.)
please lock `org.apache.maven.shared:maven-shared-utils`  version to 3.3.3 or above.

Fixed in maven-shared-utils@3.3.3 
https://github.com/apache/maven-shared-utils/pull/40
https://issues.apache.org/jira/browse/MSHARED-297

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/schintha/.sdkman/candidates/maven/current
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/<userid>/.sdkman/candidates/java/11.0.11.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

```
gradle --version
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64
```
## Additional context
 Repo: https://github.com/xmlking/micro-apps

![image](https://user-images.githubusercontent.com/627951/122808948-56df7a80-d282-11eb-8c60-b22bb8fa51e3.png)

**Comment by xmlking** [comment]
![image](https://user-images.githubusercontent.com/627951/122809543-16ccc780-d283-11eb-906f-287753a1c4f8.png)

**Comment by xmlking** [comment]
![image](https://user-images.githubusercontent.com/627951/122809589-264c1080-d283-11eb-89ce-d33c5a040ce3.png)

**Comment by gsmet** [comment]
@aloubyansky WDYT? I'm a bit nervous at the idea of using a version different from the one coming with Maven.

**Comment by aloubyansky** [comment]
If you are using gradle in Quarkus 1.x you should be able to completely exclude all the `org.apache.maven` dependencies from your project and the `io.quarkus` plugin.
I am not sure why maven 3.8.1 distribution includes maven-shared-utils 3.2.1 which was released half a year later than e.g. 3.3.0.

**Comment by xmlking** [comment]
this is really blocking us to use any recent 1.x or  2.x Quarkus releases. 
@aloubyansky  Could you please guild me, how to completely exclude all the `org.apache.maven`  in Gradle Quarkus 1.x  repo ?

I tried this with no lick:
```
configurations.all {
    resolutionStrategy {
        force("org.apache.maven.shared:maven-shared-utils:3.3.4")
    }
}
```
I also surprised why maven is not using their own latest deps.
https://mvnrepository.com/artifact/org.apache.maven/maven-core/3.8.1

![image](https://user-images.githubusercontent.com/627951/122835757-d29eee80-d2a5-11eb-9c88-a580874dd5a6.png)

**Comment by aloubyansky** [comment]
Which Quarkus version are you using? It should work in, e.g. 1.13.7.Final. E.g.
````
configurations.all {
     resolutionStrategy {
          exclude group:'org.apache.maven'
      }
}
````

**Comment by xmlking** [comment]
@aloubyansky since  `maven-shared-utils` is also used in Gradle plugin, the above solution is not working for me. 
looks like the only way is to  force `org.apache.maven.shared:maven-shared-utils:3.3.4` Quarkus BOM

**Comment by aloubyansky** [comment]
You mean the Quarkus gradle plugin? You should be able to exclude dependencies from the plugin as well. Which Quarkus version are you using?

**Comment by xmlking** [comment]
I tried `1.13.7.Final` and `1.13.5.Final` 
https://github.com/xmlking/micro-apps/blob/develop/gradle/libs.versions.toml#L51-L55
our Nexus proxy blocking to pull  `quarkus-ide-launcher-1.13.7.Final.jar` as it is marked as vulnerable (due to its dependency on maven-shared-utils)
My understanding is `resolutionStrategy/exclude` solution only filter our after it pulls the dependency graph.

**Comment by aloubyansky** [comment]
What if you exclude `org.apache.maven.shared`, do you still see it among the dependencies locally with 1.13.7.Final?

**Comment by hamburml** [comment]
We have the same issue and we use maven 3.8.1.

**Comment by aloubyansky** [comment]
Are you also using gradle?

**Comment by aloubyansky** [comment]
@gsmet i think we could try upgrading it. I actually did it last week locally and the CI has passed at least.

**Comment by famod** [comment]
If in doubt, you ask on maven-dev oder maven-user mailing list.

**Comment by famod** [comment]
@gnodet Since you were the one who bumped maven-shared-utils from 3.2.1 to 3.3.4 in Maven `master` (https://github.com/apache/maven/pull/433): Do you think it should be safe for Quarkus to bump shared-utils?
Those dependency unpack adjustments in the PR don't look relevant AFAICS.
Thanks!

**Comment by famod** [comment]
FWIW, I raised awareness in an ongoing Maven 3.8.x discussion on maven-dev mailing list: https://lists.apache.org/thread.html/r960d0cc002dfdaa7140694122ae829e6de21ad82daa17427facd267a%40%3Cdev.maven.apache.org%3E

**Comment by hamburml** [comment]
@aloubyansky No, we use maven 3.8.1. Nexus blocks quarkus-ide-launcher. We simply exclude it on all dependencies which use it - but it's not a great solution.

**Comment by aloubyansky** [comment]
Thanks for the info @hamburml

**Comment by aloubyansky** [comment]
I'll add a safe version of maven-shared-utils to the quarkus-bootstrap-bom once https://github.com/quarkusio/quarkus/pull/18167 has been merged.
