### ISSUE TITLE
Relax restriction regarding platform properties

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#18063]
## Description

As documented in the [platform guide](https://quarkus.io/guides/platform#platform-properties), all platform properties must have the `platform.` prefix and in order for them to provide default values for some extension config property, the extension must then also explicitly dereference the platform property in the default value.

I think it would be very useful if a platform could provide values for arbitrary config properties. The values would also have a higher priority than defaults provided by matching `@ConfigItem` declarations so that the platform defaults would take precedence.

So for example the platform should be allowed to define a default value for the MicroProfile JSON Web Token config property `mp.jwt.token.header` and this value would then be returned by the `ConfigProvider.getConfig()` object in downstream applications, unless the application itself overrides it:

```properties
mp.jwt.token.header=X-Identity
```

### Use Cases

This would then allow a platform to provide:
1. Platform-specific config properties which for example may get referenced by application code or extensions part of the platform
2. Defaults for MicroProfile config properties (typically prefixed with `mp.`)
3. Defaults for config properties defined by extensions part of the platform itself, Quarkus core or possibly some other derived from platform

**Comment by knutwannheden** [comment]
I think it would be useful if the platform can both specify values for existing build-time and runtime properties. But how will Quarkus know if a given property (specified by the platform) is a build-time or runtime property?

**Comment by knutwannheden** [comment]
Currently the platform properties are only available as build-time properties and are implemented using a `KeyMapBackedConfigSource`: https://github.com/quarkusio/quarkus/blob/6bead1f0bfeeae74b261ba81dd0143b5011eb331/core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java#L152-L165

Using a regular `MapBackedConfigSource` would have the advantage that the platform properties could be iterated using `getProperties()` and `getPropertyNames()`.

**Comment by radcortez** [comment]
@knutwannheden if I understood correctly, you want to be able to set a bunch of properties in one place and redistribute them across your projects or organization?

**Comment by knutwannheden** [comment]
@radcortez Yes, that is part of it.

- I want to be able to set both build-time and runtime properties
- the provided values should be defaults (overriding the config item defaults)
- these defaults shouldn't require the extension author to add any dependency, as the extension may be part of multiple platforms with different defaults
- nor the downstream application developer (using the platform) should be required to add any additional dependencies, since that can easily get forgotten
- further, the defaults should not cause any warning to get logged if the "corresponding" extension isn't being used or it should be possible to dynamically decide which defaults to supply

Ultimately I also want to run validations against the actual properties (in case the application overrides the defaults) to make sure they conform to the "platform requirements". But this part is outside the scope of this issue.

**Comment by radcortez** [comment]
> @radcortez Yes, that is part of it.
> 

Just to brainstorm a little bit here, on how this can possibly work or what we should do to support all use cases.

> * I want to be able to set both build-time and runtime properties

Any `application.properties` files (and even YAML) sitting in the classpath are loaded and merged in the Config instance. Adding a dependency to some sort of project that just includes the configuration files should do the trick.

> * the provided values should be defaults (overriding the config item defaults)

We can control the loading order with `config_ordinal` in such configuration file. You can even make it in such a way to not allow any overrides (by setting a high ordinal value). 

> * these defaults shouldn't require the extension author to add any dependency, as the extension may be part of multiple platforms with different defaults

Even the current platform properties require adding a dependency. If you as a user have to control this, where do you envision adding such configuration? It needs to live and added somewhere.

> * nor the downstream application developer (using the platform) should be required to add any additional dependencies, since that can easily get forgotten

Getting the answer to the last question, should also fix this one by transitively including additional resources. 

> * further, the defaults should not cause any warning to get logged if the "corresponding" extension isn't being used or it should be possible to dynamically decide which defaults to supply

If I remember correctly, warnings only show up for configuration names registered under the `quarkus` namespace. I suppose that you want to add property names from other namespaces. With some logic, it should be possible to not add the warning, even for the `quarkus` namespace, and only for such properties.

> 
> Ultimately I also want to run validations against the actual properties (in case the application overrides the defaults) to make sure they conform to the "platform requirements". But this part is outside the scope of this issue.

How do you envision such validations? Using Bean Validator for instance?

**Comment by knutwannheden** [comment]
> > @radcortez Yes, that is part of it.
> > 
> 
> Just to brainstorm a little bit here, on how this can possibly work or what we should do to support all use cases.
> 
> > * I want to be able to set both build-time and runtime properties
> 
> Any `application.properties` files (and even YAML) sitting in the classpath are loaded and merged in the Config instance. Adding a dependency to some sort of project that just includes the configuration files should do the trick.
> 

Yes. Or also one of the resource names specified by MP Config should work, AFAICT.

> > * the provided values should be defaults (overriding the config item defaults)
> 
> We can control the loading order with `config_ordinal` in such configuration file. You can even make it in such a way to not allow any overrides (by setting a high ordinal value). 
> 

Providing "fixed" (i.e. non-overridable) values is indeed what we want to achieve in some cases. But unless Quarkus itself can issue a warning when the developer attempts to override any such property (which would be the best solution from my perspective), this is one use case I have in mind for the validations I mentioned: I would validate that the actual config property corresponds to the platform default.

> > * these defaults shouldn't require the extension author to add any dependency, as the extension may be part of multiple platforms with different defaults
> 
> Even the current platform properties require adding a dependency. If you as a user have to control this, where do you envision adding such configuration? It needs to live and added somewhere.
> 

I would now have to look at how exactly the platform gets loaded again, but according to the documentation this doesn't require an actual dependency, AFAICT. The user just needs the platform BOM in the dependency management section, which then includes the platform descriptor and platform properties artifacts (which need to follow strict naming conventions) and Quarkus will then find this during the build. IMHO this is the beauty of platform properties.

> > * nor the downstream application developer (using the platform) should be required to add any additional dependencies, since that can easily get forgotten
> 
> Getting the answer to the last question, should also fix this one by transitively including additional resources. 
> 
> > * further, the defaults should not cause any warning to get logged if the "corresponding" extension isn't being used or it should be possible to dynamically decide which defaults to supply
> 
> If I remember correctly, warnings only show up for configuration names registered under the `quarkus` namespace. I suppose that you want to add property names from other namespaces. With some logic, it should be possible to not add the warning, even for the `quarkus` namespace, and only for such properties.
> 

Until a ConfigRoot can specify a custom namespace, we will here also have `quarkus` and without additional logic I expect there would be warnings for these defaults.

> > 
> > Ultimately I also want to run validations against the actual properties (in case the application overrides the defaults) to make sure they conform to the "platform requirements". But this part is outside the scope of this issue.
> 
> How do you envision such validations? Using Bean Validator for instance?
> 

No, I think I will want to implement the validations procedurally, so that for instance various config properties can be cross-checked against each other. At the moment we have an extension which has a runtime recorder build step which implements the validations. This works nicely, but since we have two platforms, with overlapping sets of extensions, it is a bit tricky to keep the validations platform-specific.

**Comment by radcortez** [comment]
Ok, let's try to summarize and see what is missing:

- [ ] Set Build and Runtime properties 
Yes. Multiple `application.properties` may be loaded from the classpath

- [ ] Set Defaults and Issue Warnings
Not directly, but can be implemented easily with an [SR Config Interceptor](https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html). The interceptor can just check a custom or fixed set of properties or check if the property was loaded from a particular source.

- [ ] Without adding Dependencies
May require one for the custom interceptor. I'm guessing that if the properties jar is placed in the classpath, the Config Builder should be able to locate any interceptors and add them to Config instance.

- [ ] Defaults and warnings if not being used 
Not supported. 

- [ ] Validations
The validations can also be done with the interceptor API.

Do you agree?

**Comment by knutwannheden** [comment]
> Ok, let's try to summarize and see what is missing:
> 
> - [x] Set Build and Runtime properties 
> Yes. Multiple `application.properties` may be loaded from the classpath
> 

Yes and no. I like the platform properties mechanism, since it is basically extension independent (which is good for us, since we have two separate platforms with different sets of defaults) and doesn't require the developer to do anything besides using the platform BOM. But the current platform properties are currently only available at build-time and also are restricted to have the `platform.` prefix. Relaxing this is the main theme of this request.

> - [x] Set Defaults and Issue Warnings
> Not directly, but can be implemented easily with an [SR Config Interceptor](https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html). The interceptor can just check a custom or fixed set of properties or check if the property was loaded from a particular source.
> 

Interesting. Thanks for the pointer. I will investigate this.

> - [x] Without adding Dependencies
> May require one for the custom interceptor. I'm guessing that if the properties jar is placed in the classpath, the Config Builder should be able to locate any interceptors and add them to Config instance.
> 
> - [ ] Defaults and warnings if not being used 
> Not supported. 
> 
> - [x] Validations
> The validations can also be done with the interceptor API.
> 
> Do you agree?

Tying the validations to the platform only (i.e. independent of any extension or additional dependency) is not supported yet, but IMHO that is out of scope here and is just something to think about. Also, I am suspecting this may be too esoteric to get accepted as a standard Quarkus feature.
