### ISSUE TITLE
CLI: Missing documentation for the new command line tool

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18064]
## Description
- For `extensions list` options: Note the different among `--concise`, `--origins`, `--full`. Or when to use `--installable`: for example, I tried to run it from an existing Quarkus application path and outside, and the output was the same. 
- What `--registry-client` stands for?
- What is `quarkus extensions list --stream` for? What is the difference between `--stream` and `--platform-bom`? Why `--stream` requires `--registry-client`?

Moreover, I think the existing functionality for getting the list of extensions is not very user friendly as it behaves differently depending to where is invoked, but I've also reported this https://github.com/quarkusio/quarkus/issues/18062 issue for tracking this.

**Comment by Sgitario** [comment]
cc @maxandersen @ebullient

**Comment by ebullient** [comment]
I have a partial update in #18086

It adds a section to the cli docs about specifying the version using a platform or a stream, and a note that `--stream` needs the `--registry-client` option for now.

It also adds some additional help text to extension list to clarify a project vs. release mode, in terms of which extensions are listed and why.

**Comment by Sgitario** [comment]
> I have a partial update in #18086
> 
> It adds a section to the cli docs about specifying the version using a platform or a stream, and a note that `--stream` needs the `--registry-client` option for now.
> 
> It also adds some additional help text to extension list to clarify a project vs. release mode, in terms of which extensions are listed and why.

Hello @ebullient , still I can't find how to use the `--stream` option and unless I'm missing something, the new changes in the documentation does not clarify it. The documentation only mentions `platformKey:streamId` and I'm unfamiliar with what it states.

Note that I tried `quarkus  extension list -S io.quarkus.platform:quarkus-bom:2.1.0.Final` and it returns: `[ERROR] ❗  Unable to list extensions: Failed to locate stream quarkus-bom:2.1.0.Final in platform io.quarkus.platform`

**Comment by ebullient** [comment]
> Hello @ebullient , still I can't find how to use the `--stream` option and unless I'm missing something, the new changes in the documentation does not clarify it. The documentation only mentions `platformKey:streamId` and I'm unfamiliar with what it states.

Noted. Does this help: https://quarkus.io/blog/quarkus-2x-platform-quarkiverse-registry/

**Comment by Sgitario** [comment]
> > Hello @ebullient , still I can't find how to use the `--stream` option and unless I'm missing something, the new changes in the documentation does not clarify it. The documentation only mentions `platformKey:streamId` and I'm unfamiliar with what it states.
> 
> Noted. Does this help: https://quarkus.io/blog/quarkus-2x-platform-quarkiverse-registry/
> Also.. please be clear now about which CLI version you're using.. default behaviors have changed with 2.1 final..

It did help! Thanks a lot @ebullient 
I also had questions about how to use extensions from multiple boms and the post also explains that. I guess this is only supported for extensions from the Quarkus ecosystem, right? (We can't add Bom dependencies from others).

**Comment by ebullient** [comment]
Great! I'll work on figuring out how to pull that blog post into docs. 

We should eventually be able to support the addition of additional registries, which would help resolve extensions from other places, but there are other issues for that.

**Comment by maxandersen** [comment]
cli is documented now afaik. open new if specifics missing.
