### ISSUE TITLE
Camel Extension - Native binary does not output Camel version

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/quarkus#1807]
The native compiled binary does not output the Camel version when you run it

Native
```
2019-04-01 20:55:50,251 INFO  [io.qua.cam.cor.run.sup.FastCamelRuntime] (main) Apache Camel  (CamelContext: camel-1) is starting
```

vs JVM
```
21:08:59,645 INFO  [io.qua.cam.cor.run.sup.FastCamelRuntime] Apache Camel 3.0.0-M2 (CamelContext: camel-1) is starting
```

Notice how the JVM mode outputs version 3.0.0-M2 and its blank in the native mode.

@gnodet @lburgazzoli its likely due that Apache Camel loads its version from the classpath by looking inside the maven meta-data to grab the version (AFAIK). So for quarkus we need to do something that does this on build time.

**Comment by davsclaus** [comment]
Here is how the version is loaded
https://github.com/apache/camel/blob/926cb1b2a41730db4334c5e917a72487ceb6e32f/core/camel-core/src/main/java/org/apache/camel/impl/AbstractCamelContext.java#L2193

**Comment by gnodet** [comment]
Yes, we need to specify to the substrate VM that the file needs to be preserved.  Another (better) way would be to load the version at build time and add a substitution to avoid having to load the file at runtime and hardcode the version loaded at build time somehow.

**Comment by davsclaus** [comment]
Okay @gnodet - I noticed that get version was not eager loaded in camel-core so I added this
https://github.com/apache/camel/commit/35375403ab20f4aceb88ab26e54ca694803236d0

We could also optimise camel upstream and have the version source code generated and avoid loading that maven pom.xml file

**Comment by ppalaga** [comment]
Is this still an issue? I am looking for a Camel related issue to start with.

**Comment by gnodet** [comment]
Yes, that's still the case.  Now that native works again, this can be investigated.
