### ISSUE TITLE
Migration guide entry for the change, where we stopped passing config from TestResources via System props

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#18087]
Peter Palaga: I have not found any [Migration guide entry](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0) for the change, where we stopped passing config from TestResources via System props https://github.com/quarkusio/quarkus/commit/c988b9aef5c7a8d89d84136e68f0864caf710e90
It will hit any end users who have their custom QuarkusTestResourceLifecycleManager. I guess this is worth an entry in the migration guide.

**Comment by maxandersen** [comment]
looks like this fell through the cracks. @ppalaga I don't follow your comment on it affecting users, particularly with QuarkusTestResourceLifecycleManager can you remember it? if you or @stuartwdouglas do, just go and add entry to the migration guide for completeness or add the info here and I can put it.

If no update we should just close it as its been 2 years and afaik still makes sense to have continuous test run more isolated.

**Comment by ppalaga** [comment]
IIRC, the only issue was that accessing the values via System.getProperty() stopped working because of that change. I agree it is a good change and I guess now everybody must have noticed and fixed their test code.
