### ISSUE TITLE
OIDC: Wait for actual realm

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#18089]
## Description

`quarkus.oidc.connection-delay` can be used to wait (a longer time) for IDP availability (Keycloak in my case).
This delay does unfortunately _not_ wait for the actual realm endpoint to become available.
If Keycloak (KC) starts at about the same time as Quarkus and imports the respective real via the entrypoint script, then Quarkus will finish waiting too early, will end up with missing tenant config and will throw an exception saying `Tenant configuration has not been resolved` for each request that is issued.

## Implementation ideas

https://github.com/quarkusio/quarkus/blob/901c30cc171c98954a8305cc0dcab1aa52433d3b/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L315
Instead of returning `null` on 404, either wait for 200 by default or introduce a property to fine-tune the expected behavior.

**Comment by sberyozkin** [comment]
@famod I'll look at introducing a property - it would need to be used with care to avoid the OIDC spinning in case of a realm typo for ex, but I can see why it makes sense to have this property
