### ISSUE TITLE
Hibernate validator: use custom PropertyNodeNameProvider

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#18101]
## Description

Load custom `org.hibernate.validator.spi.nodenameprovider.PropertyNodeNameProvider` if in classpath or provide a way to configure it.

Our specific use case is to provide the JSON property names (in `@JsonProperty`) if present for validation errors instead of the Java getter name. 

## Implementation ideas

The docs mention that some of the validator SPIs are already overridable/customizable so hopefully the same mechanism can be used.

**Comment by gsmet** [comment]
@xtaixe this is easily achievable by adding something similar to what I did there: https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/HibernateValidatorRecorder.java#L120 

You also need to tweak the test here: `CustomConfigurationViaBeansTest`

Would you be interested in contributing it?

In any case, that's something we could easily get in 2.0.1. Let me know if you want to do it or if I should.

**Comment by gsmet** [comment]
Done here: https://github.com/quarkusio/quarkus/pull/18112
