### ISSUE TITLE
Guide for Hibernate-reactive

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#18103]
## Description
The hibernate-reactive extension is now in a preview status, but lacks any guides, despite having serious differences from ordinary hibernate. Some kind of "getting started" guide for this would be beneficial, especially since asynchronous I/O is a "killer feature" of Quarkus.

## Implementation ideas
This guide can be based on this one[1] but with addition of quarkus-specific things, eg getting EntityManagerFactory through dependency injection and not through Persistence.createEntityManagerFactory.

[1] http://hibernate.org/reactive/documentation/1.0/reference/html_single/

**Comment by DavideD** [comment]
Where do we need to add the documentation for the extension?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/17728 adds a guide for Hibernate Reactive Panache

**Comment by fedinskiy** [comment]
@DavideD I was looking for guide here: https://quarkus.io/guides/, and I assume most people will do the same.

**Comment by AlexandreGuidin** [comment]
> @DavideD I was looking for guide here: https://quarkus.io/guides/, and I assume most people will do the same.

I think that the file `docs/src/main/asciidoc/hibernate-reactive-panache.adoc` will create a guide in that page

Compare it:
https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/hibernate-orm-panache.adoc
https://quarkus.io/guides/hibernate-orm-panache

You can appreciate the preview:
https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/hibernate-reactive-panache.adoc

**Comment by fedinskiy** [comment]
@Sanne is there any plans for a guide for Hibernate Reactive without Panache?

**Comment by Sanne** [comment]
yes sure, but it's still experimental.

**Comment by Sanne** [comment]
up - it's time to resolve this :)
