### ISSUE TITLE
Injecting from another module causes ClassNotFoundException in dev mode

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18117]
## Describe the bug
The class to be injected is located in another module in the project dependency. During the `quarkusDev`, injection fails with `java.lang.ClassNotFoundException`. Both main project and dependency have beans.xml. If the injected class is moved to the main project, injection works. It also works when running the jar directly (`java -jar service1/build/quarkus-app/quarkus-run.jar`).c So this seems to only be a dev mode issue.

### Expected behavior
Class should be injected without error.

### Actual behavior
`ClassNotFoundException: my.project.plugin.Plugin`

## To Reproduce

`service1` in https://github.com/mweber03/quarkus-test

1. `./gradlew build service1:quarkusDev`

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
Quarkus 1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by geoand** [comment]
Does the same problem happen with `2.0.0.CR3`?

**Comment by mweber03** [comment]
@geoand I get an error switching to that version:
`Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-universe-bom/2.0.0.CR3/quarkus-universe-bom-2.0.0.CR3.pom]`

**Comment by geoand** [comment]
Use `quarkus-bom` instead of `quarkus-universe-bom` to test `2.0.0.CR3`

**Comment by mweber03** [comment]
Yeah it still happens with `2.0.0.CR3`

**Comment by geoand** [comment]
cc @aloubyansky @stuartwdouglas

**Comment by aloubyansky** [comment]
It's related to `runtimeOnly` config. @glefloch could you please have a look? This change allows to launch the dev mode
````
diff --git a/modules/service1/build.gradle b/modules/service1/build.gradle
index 68cc19c..ad5f46a 100644
--- a/modules/service1/build.gradle
+++ b/modules/service1/build.gradle
@@ -7,7 +7,7 @@ version = '1.0.0'
 
 dependencies {
     implementation project(':plugin-api')
-    runtimeOnly project(':plugin1')
+    implementation project(':plugin1')
````

**Comment by glefloch** [comment]
@aloubyansky yes, checking it :)
