### ISSUE TITLE
NoSuchElementException when building a project with no source files

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18118]
## Describe the bug
I am trying to plugin libraries via CDI into a service to create a new service. So in my example my original service is `service1`, which I'd like to add `plugin2` to create `service2`. So I made a new project with no source code and only dependencies in `service1` and `plugin2`. I was hoping the REST resources from `service1` would be picked up off the classpath along with `plugin2` through CDI. But when I `quarkusBuild`, I get a `NoSuchElementException`.

### Expected behavior
A successful build.

### Actual behavior
```
Caused by: java.util.NoSuchElementException
        at io.quarkus.deployment.builditem.ArchiveRootBuildItem.<init>(ArchiveRootBuildItem.java:97)
        at io.quarkus.deployment.builditem.ArchiveRootBuildItem.<init>(ArchiveRootBuildItem.java:17)
        at io.quarkus.deployment.builditem.ArchiveRootBuildItem$Builder.build(ArchiveRootBuildItem.java:50)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:141)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:394)
        ... 125 more
```

## To Reproduce

`service2` in https://github.com/mweber03/quarkus-test

1. Uncomment `service2` from `settings.gradle`
2. `./gradlew service2:build`

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
Quarkus 1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by geoand** [comment]
Thanks for reporting!

It seems you forgot to attach the project :")

**Comment by mweber03** [comment]
@geoand added a reproducer (`service2` in https://github.com/mweber03/quarkus-test)

**Comment by geoand** [comment]
@aloubyansky I am not sure what the proper behavior should be here...

**Comment by aloubyansky** [comment]
If I add an empty application.properties to the service2 module it builds. Which shouldn't be required.

**Comment by geoand** [comment]
Do you want to take a look?

**Comment by aloubyansky** [comment]
Sure

**Comment by geoand** [comment]
Thanks 👍
