### ISSUE TITLE
Make the use of Mandrel images easier

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#18129]
## Description

Currently Quarkus defaults to using `native-image` from `$GRAALVM_HOME/bin`, `$JAVA_HOME/bin`, or the system's `$PATH`. If `native-image` is not available then it falls back to using a container runtime with the [ubi-quarkus-native-image](https://quay.io/repository/quarkus/ubi-quarkus-native-image) container image.

The main benefit of this is that users can simply run:
```
./mvnw -Pnative package
```
and create a native executable of their Quarkus application without any local setup. This also makes it easy to ensure that the users are using the correct container image (and the correct version) since it's defined in [`build-parent/pom.xml`](https://github.com/quarkusio/quarkus/blob/057969838faffa65955bf83d551b81a9c53dee40/build-parent/pom.xml#L134)

In order for users to use Mandrel they need to do one of the following:
* Download Mandrel, set it up, and make sure `native-image` can be found either in `$GRAALVM_HOME/bin`, `$JAVA_HOME/bin`, or the system's `$PATH`.
* Use `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11`

Now the issue I see with both options is that the user is responsible for figuring out the correct Mandrel version to use.
I believe that Quarkus should offer an option to allow users to state that they would like to build their native executable using Mandrel without the need to worry about the correct version.

e.g.
```
./mvnw -Pnative `-Dquarkus.native.mandrel=true` package
```

## Implementation ideas

We could possibly introduce yet another property like `quarkus.native.mandrel` or we could handle something like `-Dquarkus.native.builder-image=mandrel` and replace `mandrel` with the `ubi-quarkus-mandrel` image that is compatible with the Quarkus version being used.

WDYT?

**Comment by galderz** [comment]
Hmmm, I think I'd leave `quarkus.native.builder-image` as is, a property that points to a builder image, but I'd give it a default based on the Quarkus version. Instead, I would add something like `quarkus.native.provider` that takes an enum of `graalvm`, `mandrel` or whichever option we might have in the future (e.g. leyden?). Then, to build with mandrel, you'd do:

```
./mvnw -Pnative package -Dquarkus.native.provider=mandrel
```

`quarkus.native.builder-image` would still allow you to tweak the builder image in use, say if you're testing a locally built one, or a newer or older version.

**Comment by zakkak** [comment]
Although I like how this separates the actual image from the distribution/provider I am afraid it might make things unnecessarily complicated. E.g. , users might think they need to pass `-Dquarkus.native.provider=mandrel` with `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.0-java11` while they shouldn't have to.

I think I like more the option of making `quarkus.native.builder-image` accept either a value from an `enum` of `graalvm`, `mandrel` or a container image. In that case the default value of `quarkus.native.builder-image` should become `graalvm` or `mandrel`. The only downside I see with this option is that we "reserve" `graalvm` and `mandrel` (and whatever might come in the future) making the use of images named like this a bit harder, but I don't expect this to be an issue.

@gsmet @geoand WDYT?

**Comment by geoand** [comment]
That sounds like an interesting idea, I like it!

**Comment by galderz** [comment]
I think that's a fair suggestion. I would suggest validating the contents of the property early on so that any mistakes are clearly reported. So, it's either one of the 2 (currently) reserved words, or a URL.
