### ISSUE TITLE
panache-archive.marker files litter the root directory

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#18134]
There files should end up in the target directory instead of the root directory:
  ![image](https://user-images.githubusercontent.com/176880/123272646-3a517580-d502-11eb-8214-2fde52ae5648.png)

Discussion: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/panache-archive.2Emarker

To reproduce with quarkus 1.13.3.Final (I haven't tried 2.0 yet):

1. git clone https://github.com/kiegroup/optaplanner-quickstarts
2. cd optaplanner-quickstarts
3. mvn clean install

**Comment by stuartwdouglas** [comment]
This is an optaplanner issue, KieMemoryCompiler has the project root setup as the CLASS_OUTPUT, so the annotation processor creates the files there when the tests are run.

**Comment by ge0ffrey** [comment]
Related: https://issues.redhat.com/browse/DROOLS-6501
