### ISSUE TITLE
kafka configuration from env variables crashes the application

### ISSUE THREAD

**Issue by r00ta** [quarkusio/quarkus#18135]
## Describe the bug
using the library `quarkus-smallrye-reactive-messaging-kafka`, it is not possible to define a kafka configuration using env variables. 
For example, if the `application.properties` contain 
```properties
mp.messaging.incoming.kogito-tracing-decision.group.id=trusty-service
mp.messaging.incoming.kogito-tracing-decision.connector=smallrye-kafka
mp.messaging.incoming.kogito-tracing-decision.topic=kogito-tracing-decision
mp.messaging.incoming.kogito-tracing-decision.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kogito-tracing-decision.auto.offset.reset=earliest
```

and the env variable 
```bash
 export MP_MESSAGING_INCOMING_KOGITO_TRACING_DECISION_FAILURE_STRATEGY="ignore"
```
is exported, then the application crashes with 
```bash
2021-06-24 15:38:10,144 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-06-24 15:38:10,141 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `kogito`
	at io.smallrye.reactive.messaging.impl.ConnectorConfig.lambda$null$0(ConnectorConfig.java:47)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
```

I tried with the quarkus version 1.13.4 and this works properly, so the problem started with 1.13.5. 

### Expected behavior
It should be possible to configure the application using env variables

### Actual behavior
The application crashes

## To Reproduce
See the reproducer https://github.com/r00ta/issues-reproducers/tree/main/kafka-quickstart

Or attach an archive containing the reproducer to the issue.

1. run 
```bash
mvn io.quarkus:quarkus-maven-plugin:1.13.5.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=kafka-quickstart \
    -DclassName="org.acme.kafka.PriceResource" \
    -Dpath="/prices" \
    -Dextensions="resteasy,smallrye-reactive-messaging-kafka"
cd kafka-quickstart
```
2. add the following application properties to `application.properties`
```properties
mp.messaging.incoming.kogito-tracing-decision.group.id=trusty-service
mp.messaging.incoming.kogito-tracing-decision.connector=smallrye-kafka
mp.messaging.incoming.kogito-tracing-decision.topic=kogito-tracing-decision
mp.messaging.incoming.kogito-tracing-decision.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kogito-tracing-decision.auto.offset.reset=earliest
```
3. export the env variable
```bash
export MP_MESSAGING_INCOMING_KOGITO_TRACING_DECISION_FAILURE_STRATEGY="ignore"
```
4. run `mvn clean compile quarkus:dev`
5. see the error
```bash
2021-06-24 15:38:10,144 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-06-24 15:38:10,141 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `kogito`
	at io.smallrye.reactive.messaging.impl.ConnectorConfig.lambda$null$0(ConnectorConfig.java:47)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
```

### Configuration
```properties
mp.messaging.incoming.kogito-tracing-decision.group.id=trusty-service
mp.messaging.incoming.kogito-tracing-decision.connector=smallrye-kafka
mp.messaging.incoming.kogito-tracing-decision.topic=kogito-tracing-decision
mp.messaging.incoming.kogito-tracing-decision.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kogito-tracing-decision.auto.offset.reset=earliest
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):
export MP_MESSAGING_INCOMING_KOGITO_TRACING_DECISION_FAILURE_STRATEGY="ignore"

### Output of `uname -a` or `ver`
Linux jrota.remote.csb 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Wed Feb 3 03:12:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

### Quarkus version or git rev
\>= 1.13.5
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/jrota/opt/build/apache-maven-3.6.3
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /home/jrota/.jabba/jdk/adopt@1.11.0-6
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-240.15.1.el8_3.x86_64", arch: "amd64", family: "unix"

## Additional context
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
I believe it is already fix in 2.0. The MicroProfile 3 config were unable to handle that case. This was fixed in MicroProfile 4.

**Comment by cescoffier** [comment]
No, it does not work in 2.0 either, because env variable introduces non-deterministic attribute parsing. 

It works if your channel name does not use any special character (no -).
It's a limitation of Microprofile Config, not from the connector which only gets what config is providing. 

If you switch your channel name to use `.` instead of `-`, you can make it work with (using 2.0):
```
mp.messaging.incoming."kogito.tracing.decision".connector=smallrye-kafka
mp.messaging.incoming."kogito.tracing.decision".group.id=trusty-service
mp.messaging.incoming."kogito.tracing.decision".topic=kogito-tracing-decision
mp.messaging.incoming."kogito.tracing.decision".value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming."kogito.tracing.decision".auto.offset.reset=earliest
```

and:

```
export MP_MESSAGING_INCOMING__KOGITO_TRACING_DECISION__FAILURE_STRATEGY="ignore"
```

Not great, I agree, but the mapping between properties and env variable is quite limited (as env variable are not allowed to contain any special character except _).

**Comment by rquinio1A** [comment]
We faced the same issue with hyphens in channel names.

Discovering channel names at runtime (https://github.com/smallrye/smallrye-reactive-messaging/blob/dcbf3fc61ee05cec4ee39799e404ebf243d454fa/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConfiguredChannelFactory.java#L91-L109) seems wrong in a Quarkus context:

- Channel names should be determined at build time based on the names referenced in byecode (could be a build item cf #20158)
- The configuration of the channel can then discovered at runtime in a deterministic way.

**Comment by cescoffier** [comment]
Smallrye reactive messaging is used on several contexts. Quarkus is just one of them.

However I agree with what you said and the ability to detect channels at build time. It will require a bit of change to allows executing the first pass of the wiring at build time, but it's possible.

**Comment by baiglin** [comment]
Hello. 

Actually after more investigation with @rquinio1A we found that there is logic done in smallrye to validate if there is not a non-env property defined that could match the any env property by applying reverse logic on it (replace any non alpha-num characters by an underscore) then remove the property from the list that is used to determine the channel names. 

So to sum-up, you define the property you want to use inside your application.properties file with a dummy value, then override it with your env property and it should work.
