### ISSUE TITLE
java.lang.IllegalStateException: The current thread cannot be blocked

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#18147]
## Describe the bug
This might not be a bug, maybe just expected behavior and I use it in the wrong way.

I'm following the reactive example https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started-reactive

I try to make a request blocking
- by adding `@Blocking` on the API method(i.e, https://github.com/quarkusio/quarkus-quickstarts/blob/main/getting-started-reactive/src/main/java/org/acme/getting/started/ReactiveGreetingResource.java), which means blocking the whole request, it's working fine
-  but when I tried to add `@Blocking` at the service(i.e, https://github.com/quarkusio/quarkus-quickstarts/blob/main/getting-started-reactive/src/main/java/org/acme/getting/started/ReactiveGreetingService.java), which means blocking part of the request,  it report the `The current thread cannot be blocked` error

Is that the expected behavior? I'm wondering if I can only make part my a request blocking

**Comment by geoand** [comment]
This is indeed the expected behavior. 
`@Blocking` is meant to be added to a JAX-RS Resource, not a CDI bean

**Comment by liuzqt** [comment]
@geoand in my scenario, there're still some parts that can not be run asynchronously, but just a small of the whole request. Marking the JaxRS request as `@Blocking` will move the request to run on the worker thread, do we still benefit from the reactive pattern (since most parts of this request are still reactive)

**Comment by geoand** [comment]
With blocking, the request will be served by a worker thread no matter what the implementation does.

If you want to take advantage of Reactive processing, you will have to refactor your service be reactive (i.e. to not block the thread it's working on)
