### ISSUE TITLE
Wrong content-type when using Kotlin coroutines in RESTEasy Reactive

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#18145]
## Describe the bug
I have changed a web endpoint from returning a Mutiny Uni to using a suspend function.

### Expected behavior
I would expect that the content type stays the same (application/json)

### Actual behavior
The content-type is application/octet-stream

## To Reproduce

Returns application/json:

```
@Path("/test")
class TestController{

    @GET
    fun test() = Uni.createFrom().item(MyObject("hello"))
}

data class MyObject(val test:String)
```

Returns application/octet-stream:

```
@Path("/test")
class TestController{

    @GET
    suspend fun test() = MyObject("hello")
}

data class MyObject(val test:String)
```

**Comment by geoand** [comment]
I'll take a look

**Comment by geoand** [comment]
I was not able to reproduce this with an example application. 
Can you please attach a reproducer?

**Comment by holledauer** [comment]
[quarkus-coroutines.zip](https://github.com/quarkusio/quarkus/files/6715895/quarkus-coroutines.zip)

See attachment.

**Comment by geoand** [comment]
Thanks!

https://github.com/quarkusio/quarkus/pull/18171 fixes the issue
