### ISSUE TITLE
RestEasy Reactive: Incorrect ResourceRequestFilterHandler used in handler chain

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#18141]
## Describe the bug
This relates to #16106
After much investigation and logging, I've come to the conclusion that when RuntimeResourceDeployment populates the handler list around line 188, its using the method handlers of the parent resource and when a sub resource is used, its method handlers are not invoked.

One symptom of this is that things like QuarkusSmallRyeTracingDynamicFeature that register a filter for a method, end up with the incorrect filter being used on sub resources.

I can demonstrate this with System.out.println() in the Resteasy reactive code but cant really create a reproducer other than a simple example like mentioned below where one can debug this and see that the Tracing filter being used is the one created for the root resource as opposed to the sub resource.

At first I thought this was an issue with the operation name provider or something in opentracing but it turns out this is a more core issue in resteasy reactive deciding which non-global filter to use in a sub resource.

### Expected behavior
If a filter is registered in a sub resources FeatureContext at runtime then that filter should be the one invoked when the resource is used and not the one of the parent (root) resource.

### Actual behavior
The root resource's features are invoked.

## To Reproduce

git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
git checkout d84d29b
mvn clean test

### Configuration
Nothing specific

### Screenshots
Some logging when the feature is registered per root and sub resource:

![image](https://user-images.githubusercontent.com/26746221/123341155-c76dec00-d54d-11eb-9046-7a4bcd635211.png)

Some logging where handlers are set up per resource (not called for sub resources)

![image](https://user-images.githubusercontent.com/26746221/123341173-d05ebd80-d54d-11eb-8fb6-5a24372917e5.png)

Some logging of when a filter is initialised and what its hashcode is so we can see when its used:

![image](https://user-images.githubusercontent.com/26746221/123341243-ef5d4f80-d54d-11eb-94cc-8c200ff7c4e8.png)

Some logging of when a filter is called and its hashcode

![image](https://user-images.githubusercontent.com/26746221/123341265-f97f4e00-d54d-11eb-84d1-dcfc7005c8fa.png)

The resulting logs show how the only ServerTracingFilter actually assigned to a handler is the one of the root resource, and it is used when a sub resource is called:

![image](https://user-images.githubusercontent.com/26746221/123341090-a73e2d00-d54d-11eb-8b2e-7c78c8787c3d.png)

## Environment (please complete the following information):
NA
### Output of `uname -a` or `ver`
NA
### Output of `java -version`
NA
### GraalVM version (if different from Java)
NA
### Quarkus version or git rev
999-SNAPSHOT
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
NA
## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Thanks a lot for investigating!

I'll look into it next week

**Comment by bcluap** [comment]
Thanks @geoand . Sorry I can't suggest a fix right now. It's really difficult to fully grasp what is going on without being able to eat and breathe the code. I'm sure you or Stuart would be able to suggest a change pretty quickly. My sense is that by avoiding registering filters twice, the code errs on the side of only registering root resources as opposed to registering root and sub resource methods but skipping those that don't have an Http method annotation on them.

**Comment by geoand** [comment]
No need to apologize 😃

You've way more than what a lot of users are willing to do 😜

**Comment by bcluap** [comment]
Lol so in describing why I can't suggest a solution, I tried the solution I was suggesting and it seems to fix this...

![image](https://user-images.githubusercontent.com/26746221/123414691-80ffa800-d5b4-11eb-88d9-0672a1c186cf.png)

**Comment by geoand** [comment]
Cool!

Mind opening a PR? 
Having a test that verifies your problem is fixed would be ideal

**Comment by bcluap** [comment]
PR added. Writing a test for this is beyond my resteasy kungfu for now. I'm pressured on some other delivery but will do the next one if you show the way on this one.

**Comment by geoand** [comment]
OK, no problem at all!

Do you have some example however I could use to write a test for this case?

Thanks

**Comment by bcluap** [comment]
The example in this ticket is pretty heuristic so wont really work. Can you potentially have a test that has a sub resource and then add a dynamic request filter for that specific resource which adds a header like "foo: true" in the request context and then the sub resource reads the header and responds with its value as the body. Then the test case verifies that when it calls the sub resource it replies with body "true".
