### ISSUE TITLE
Upgrade micrometer-bom from 1.7.0 to 1.7.1 (or further)

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#18151]
## Description

Follow up from #18120 

Apparently the micrometer jar now include native-image metadata, and the included directives aren't correct.

## Implementation ideas

We will either need to contribute fixes to Micrometer or find a way to exclude them.

**Comment by zakkak** [comment]
I have opened https://github.com/micrometer-metrics/micrometer/issues/2670 to let the micrometer team know about this issue.
