### ISSUE TITLE
When using PicoCLI, `@TopCommand` should be optional

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#18153]
## Description

When creating a new PicoCLI application, the codestarts generate some very useful things, like this:

```java
@TopCommand
@CommandLine.Command(mixinStandardHelpOptions = true, subcommands = { HelloCommand.class, GoobyeCommand })
public class EntryCommand {
}
```

Would it not make sense to have this auto-generated when there is no `@TopCommand` present in the application?

**Comment by geoand** [comment]
cc @maxandersen @ia3andy

**Comment by maxandersen** [comment]
I don't follow. You say it generates it but you want to generate it?

**Comment by geoand** [comment]
What I mean is that it should not be necessary to be part of user code.
Furthermore this needs to be updated when a new command is added.

MY point is that is should be generated in bytecode

**Comment by maxandersen** [comment]
Hmm - how would you figure out which is the root command and what order of du commands you would want ?

**Comment by geoand** [comment]
Well that was why I pinged you folks.

The simplest case is where you want all commands to be subcommands of the top command.

What other situations are there? And how are they defined with annotations?

**Comment by ia3andy** [comment]
That's already the case for 2.0:
https://github.com/quarkusio/quarkus/tree/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/picocli-codestart/java/src/main/java/org/acme

The idea is now to only provide starters (instead of examples) which contain the base code that you would use 90% of the time when using an extension.

**Comment by geoand** [comment]
Which commit enables the feature I am requesting? I don't see anything relevant...

**Comment by ia3andy** [comment]
It's done a while ago

**Comment by ia3andy** [comment]
https://github.com/quarkusio/quarkus/commit/271160508391b686f3c112ca39ff177df3c6e237#diff-41bc9636c0f1be3a2631e845cd9ffdd92738ddc3b9dc0f9915f4740c3724c29c

**Comment by geoand** [comment]
Yeah, but I don't see anything relevant in the code.

Let me verify at least that it works as I expect it would

**Comment by ia3andy** [comment]
Ah ok, sorry @geoand I misread you 😅, there is no more top command in the codestart is what I meant.

Yeah I think it would be a good idea to auto generate it when there is more than one command without any top command.

**Comment by geoand** [comment]
OK, what you pointed to, is not what I am requesting.

What I am requesting is that my code doesn't have to contain:

```java
@TopCommand
@CommandLine.Command(mixinStandardHelpOptions = true, subcommands = { HelloCommand.class, ByeCommand.class })
public class EntryCommand {
}

```

when I have `HelloCommand` and `ByeCommand` annotated with `@Command`.
What I want is for Quarkus to generate that in bytecode and my question is whether or not that makes sense

**Comment by gsmet** [comment]
TBH, I don't like this proposal.

I don't think it's a good idea to have a behavior that is different from traditional Picocli.

**Comment by geoand** [comment]
The point of my proposal is this:

Why make the user add `@CommandLine.Command(...)` which a bunch of subcommands if we can safely deduce that it's not necessary?
It's just too easy to create a new subcommand and forget to add it to that annotation...

**Comment by maxandersen** [comment]
The thing is the sequence of the commands matters when it comes to help / docs generation.

**Comment by geoand** [comment]
Good point (I didn't know that).

My point is that if a user doesn't add one, we can make things easier. If a user wants full control (in the manner you mention), we would back out obviously

**Comment by gsmet** [comment]
Adding more and more magic already bit us several times. I would be in favor of keeping the default Picocli behavior as that's what users will expect and there's not that much value in simplifying this. Especially since there's a good chance you will want to order subcommands anyway.

**Comment by geoand** [comment]
I agree about the reservations - I don't agree about this not adding value (obviously).
