### ISSUE TITLE
standalone Qute has no meaning full resultmapper to force errors

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18177]
## Describe the bug
im using qute standalone in jbang and I been battling that qute just ignores missing names/propertyes by default.

I see there is https://github.com/quarkusio/quarkus/pull/13471 but all those resultmappers only exist in Quarkus - should there not be similar ones available for plain qute rather than users have to implement them manually ?

**Comment by mkouba** [comment]
So we could just move the [PropertyNotFoundThrowException](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/PropertyNotFoundThrowException.java) and friends to the `qute-core` and make it public/part of the API...

**Comment by gsmet** [comment]
If we move it, I would make it the default behavior. I can't see when you would want to have these errors simply ignored.

**Comment by mkouba** [comment]
> I can't see when you would want to have these errors simply ignored.

Many templating engines out there do treat missing values as empty strings/0/false etc. But I understand that this kind of behavior might be problematic. My point is that  it should be a matter of configuration, i.e. the code that manages the `Engine` instance is in charge.

Note that we've changed the default behavior for the quarkus development mode already and throw an exception if a result is not found.
