### ISSUE TITLE
'quarkus create cli' and 'quarkus create app' generate the same code 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#18172]
## Describe the bug
Running `quarkus create cli` and `quarkus create app`, with or without `--jbang` produces the same generated code.

Only a `JAX-RS resource` is produced when running either `app` or `cli` without `--jbang`.
Additionally, `main` is also produced when running either `app` or `cli` with `--jbang`.

So it is not clear what is the difference between `app` and `cli` options.

### Expected behavior

Perhaps `main` should be produced with or without `--jbang` when only a `cli` option is used.

**Comment by ebullient** [comment]
As I said then, this issue: https://github.com/quarkusio/quarkus/issues/18114
