### ISSUE TITLE
Quarkus 2.0 : Logging on windows cmd or power shell with encoding problems

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#18178]
## Describe the bug

Logging work fine in dev mode  On windows cmd or power shell。
![image](https://user-images.githubusercontent.com/48646226/123497595-fa54d480-d660-11eb-9ee2-014ebbedd8ed.png)

But  there are some encoding problems in standlone jvm mode  or  native mode.
![image](https://user-images.githubusercontent.com/48646226/123497410-eb215700-d65f-11eb-8c44-e7d9041b2cef.png)

## Environment (please complete the following information):

Windows 10

### Quarkus version or git rev

Form Quarkus 2.0.0.Alpha1 to Quarkus 2.0.0.Final

## Additional context
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment]
I just tested this locally and I don't see any issues, although I don't see any colored output in dev mode. Are you running with any flags to force the color? 

This is the code that decides on color or not, so in most cases it should decide not to use it: https://github.com/quarkusio/quarkus/blob/2c2784aa34449442a50d837decce9828d4c73b9f/core/devmode-spi/src/main/java/io/quarkus/dev/console/QuarkusConsole.java#L42

Jansi in dev mode will set ENABLE_VIRTUAL_TERMINAL_PROCESSING which is why color works in dev, just not sure why you are seeing ANSI output in prod

**Comment by yuhaibohotmail** [comment]
> I just tested this locally and I don't see any issues, although I don't see any colored output in dev mode. Are you running with any flags to force the color?

yes，I  force  the  color with console log.
`quarkus.log.console.color=true`

> 
> This is the code that decides on color or not, so in most cases it should decide not to use it:
> 
> https://github.com/quarkusio/quarkus/blob/2c2784aa34449442a50d837decce9828d4c73b9f/core/devmode-spi/src/main/java/io/quarkus/dev/console/QuarkusConsole.java#L42
> 
> Jansi in dev mode will set ENABLE_VIRTUAL_TERMINAL_PROCESSING which is why color works in dev, just not sure why you are seeing ANSI output in prod

**Comment by knutwannheden** [comment]
On a related note I am having issues in Windows Terminal after returning from Dev Mode: Ctrl+C won't work anymore. I could file a separate issue for this.

**Comment by stuartwdouglas** [comment]
@yuhaibohotmail did `quarkus.log.console.color=true` used to work on older versions? I would not expect it to work. In dev mode we use the jansi library to print the console at the bottom, and one of the side effects is turning on color support. We don't have this in prod mode.

**Comment by stuartwdouglas** [comment]
@knutwannheden can you file a separate issue?

**Comment by famod** [comment]
@yuhaibohotmail you might want to check the value of the Windows registry key `VirtualTerminalLevel`. See also: https://superuser.com/a/1300251

**Comment by yuhaibohotmail** [comment]
> @yuhaibohotmail did `quarkus.log.console.color=true` used to work on older versions? I would not expect it to work. In dev mode we use the jansi library to print the console at the bottom, and one of the side effects is turning on color support. We don't have this in prod mode.
yes, it  work on older versions.@famod ‘s method works well. Thanks a lot!
I will close this issue.

**Comment by yuhaibohotmail** [comment]
> @yuhaibohotmail you might want to check the value of the Windows registry key `VirtualTerminalLevel`. See also: https://superuser.com/a/1300251

Thanks a lot!

**Comment by stuartwdouglas** [comment]
@knutwannheden can you test out  this PR? https://github.com/quarkusio/quarkus/pull/18258

**Comment by knutwannheden** [comment]
@stuartwdouglas Yes, I will test it and report back. Thanks for looking into this!

**Comment by knutwannheden** [comment]
> @stuartwdouglas Yes, I will test it and report back. Thanks for looking into this!

@stuartwdouglas I can confirm that your PR fixes the problem. 🚀

**Comment by stuartwdouglas** [comment]
Nice, it should also give you coloured logging in Dev mode

**Comment by knutwannheden** [comment]
> Nice, it should also give you coloured logging in Dev mode

Yes, indeed. Very nice!

With all that work you have put into making a Java CLI app work properly even under Windows I am hoping it will be possible to reuse some of that effort when building Quarkus-based CLI applications.
