### ISSUE TITLE
Customize response from resteasy jackson parse error

### ISSUE THREAD

**Issue by AlexandreGuidin** [quarkusio/quarkus#18184]
## Description

Quarkus have a great exception mapper that is very useful to customize response, example:
```
  // Mapping a Hibernate Validator exception to my own response
    @ServerExceptionMapper
    public Response constraintViolationException(ConstraintViolationException exception) {
        List<ValidationError> errors = exception.getConstraintViolations()
                .stream()
                .map(ValidationError::new)
                .sorted(Comparator.comparing(ValidationError::getField))
                .collect(Collectors.toList());

        return Response.status(422).entity(errors).build();
    }
```
It just return a 422 status with a list of my class `ValidationError`

--

But, for some serialize problems, it get stuck at [this code](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/ServerJacksonMessageBodyReader.java#L55)
```
    @Override
    public Object readFrom(Class<Object> type, Type genericType, MediaType mediaType, ServerRequestContext context)
            throws WebApplicationException, IOException {
        try {
            return doReadFrom(type, genericType, context.getInputStream());
        } catch (MismatchedInputException e) {
            context.abortWith(Response.status(Response.Status.BAD_REQUEST).build());
            return null;
        }
    }
```

In some cases, the server just return a 400 status code, with no message and we could not create a `ServerExceptionMapper`
Some examples:
- Enum field with a invalid string value
- LocalDateTime field with a invalid string value

## Implementation ideas

If it's possible, `ServerJacksonMessageBodyReader` [at line 55](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/ServerJacksonMessageBodyReader.java#L55) could just throws a exception, and not abort request with a 400 status code

**Comment by geoand** [comment]
This is a very interesting use case.

Can you share an example of the input that is being treated like you mention in `ServerJacksonMessageBodyReader`? 
I want to get a sense of the types of problematic inputs here

**Comment by AlexandreGuidin** [comment]
> This is a very interesting use case.
> 
> Can you share an example of the input that is being treated like you mention in `ServerJacksonMessageBodyReader`?
> I want to get a sense of the types of problematic inputs here

Sure!

**ENUM EXAMPLE**
I have a endpoint for registration
```
    @Path("/registration")
    @POST
    public Response registration(@Valid RegistrationRequest registrationRequest) {
        profileService.register(registrationRequest);
        return Response.ok().type(MediaType.APPLICATION_JSON).build();
    }
```
RegistrationRequest have a enum field
```
public class RegistrationRequest {

    @NotEmpty
    private String name;

    @NotNull
    private ProfileType profileType;
```
The ProfileType enum
```
public enum ProfileType {
    ADMIN,
    GUEST;
}
```
It a sent a wrong value in the `profile_type` field, it have a `MismatchedInputException` at `ServerJacksonMessageBodyReader:55`
```
{
    "name": "Alexandre",
    "profile_type": "XXX"
}

Exception:
Cannot deserialize value of type `model.dto.ProfileType` from String "XXX": not one of the values accepted for Enum class: [USER, ADMIN]
```


The thrown exception have a `getter` to the field name and value, i could use this to build some appropriate return message



**TIME AND DATE FIELDS**
I have other requests that use `LocalDateTime` and `LocalDate`
It throws a similar exception
```
Localdate:
Cannot deserialize value of type `java.time.LocalDate` from String "2021-66-10": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2021-66-10' could not be parsed: Invalid value for MonthOfYear (valid values 1 - 12): 66

LocalDateTime
Cannot deserialize value of type `java.time.LocalTime` from String "07:": Failed to deserialize java.time.LocalTime: (java.time.format.DateTimeParseException) Text '07:' could not be parsed at index 3
```

But imagine that it could goes wrong with any other classes

> Sorry for some typos in my English, it's not my primary language :)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18207 should allow you to handle `MismatchedInputException` in the normal ways

**Comment by AlexandreGuidin** [comment]
> #18207 should allow you to handle `MismatchedInputException` in the normal ways

wow! That was fast 😄

**Comment by AlexandreGuidin** [comment]
I've updated to `2.0.1.Final` and it works very well

**Comment by geoand** [comment]
👌

**Comment by andreiyusupau** [comment]
@geoand I'm having similar problem, but instead of @ServerExceptionMapper I'm using ExceptionMapper interface.
For some reason this exception mapper doesn't catch any exceptions:
```java
@Provider
public class GlobalExceptionMapper implements ExceptionMapper<Exception> {

    @Override
    public Response toResponse(Exception ex) {
        return Response.....
    }
}
```
But this one works fine:
```java
@Provider
public class MismatchedInputExceptionMapper implements ExceptionMapper<MismatchedInputException> {

    @Override
    public Response toResponse(MismatchedInputException ex) {
         return Response.....
    }
}
```
What may be the reason for this?
Quarkus 3.13.0
