### ISSUE TITLE
Investigate changing the test-extension jaxb dependency to io.quarkus.jaxb.

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#1819]
A current update to the test-extension introduce a jaxb dependency on the standalone libraries rather than our jaxb extension due to concerns about dependencies from the core module on other extensions. We need to verify that this can be swapped out and remove the library dependency for the next release.

**Comment by gsmet** [comment]
I will have a look and see if it's an easy fix.

**Comment by gsmet** [comment]
I'm closing this one for now. This `test-extension` is in the core module and it's probably better to avoid having dependencies to other extensions.

My intuition is that this extension should be moved to the ITs instead but it can probably wait.
