### ISSUE TITLE
Decorating QuarkusApplication won't build

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#18200]
## Describe the bug
Creating a decorator for the `QuarkusApplication` interface gives a build error about only decorators can declare a delegate (even if the decorator is properly marked as `@Decorator`)

### Expected behavior
According to conversation on Zulip, this should work, so the app should build and the whole Quarkus execution decorated

### Actual behavior
Build error:
```java
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.CR3:build (default) on project app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Only decorators can declare a delegate injection point: CLASS bean [types=[io.quarkus.runtime.QuarkusApplication, java.lang.Object, AppDecorator], qualifiers=[@Default, @Any], target=AppDecorator]
[ERROR] 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:457)
```

## To Reproduce

Reproducer: [main-decorator.zip](https://github.com/quarkusio/quarkus/files/6726011/main-decorator.zip)

1. Just build with Maven

### Output of `uname -a` or `ver`
`Darwin xtaixe 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```

### Quarkus version or git rev
`2.0.0.CR3`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/xtaixe/.mvnvm/apache-maven-3.8.1
Java version: 11.0.11, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

**Comment by mkouba** [comment]
I can confirm that it's a bug. First of all, we should skip decorators [here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L776). Furthermore, a `QuarkusApplication` impl annotated with `@Decorator` should not be registered as an additional bean [here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L776). Finally, the container should throw a definition error if a decorator declares any scope other than `@Dependent`.
