### ISSUE TITLE
ReflectiveHierarchyStep - io.vertx.core.json JsonArray/JsonObject, PanacheEntity

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1820]
When running QS I see warnings for [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index

Reported classes
	- io.quarkus.hibernate.orm.panache.PanacheEntity
	- io.vertx.core.json.JsonArray
	- io.vertx.core.json.JsonObject

Similar changes were done for https://github.com/quarkusio/quarkus/issues/385 via https://github.com/quarkusio/quarkus/pull/517 by @gsmet

**Comment by FroMage** [comment]
I'm not sure I understand this TBH. @gsmet you do?

**Comment by gsmet** [comment]
Ah ah, funny. Just saw this issue and I already added an ignore rule for the Vert-x ones here: https://github.com/quarkusio/quarkus/pull/1833 .

As for `PanacheEntity`, I plan to fix it as part of my review of https://github.com/quarkusio/quarkus/pull/1654 .

**Comment by gsmet** [comment]
This is now fixed by the PRs mentioned above.
