### ISSUE TITLE
Hibernate Reactive to use the same import.sql format as Hibernate ORM

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#18216]
## Describe the bug
The Hibernate ORM extension is defaulting the ORM to use the "multi-line" format for `import.sql` scripts, which allows people to format SQL statements nicely on multiple lines but requires statement delimitators.

upstream "vanilla" Hibernate ORM's default is to interpret the `import.sql` scripts as one statement per line, and not expecting other delimitators (other than newline).

Hibernate Reactive is currently matching the same defaults of vanilla Hibernate ORM, but it should match the same defaults as the Quarkus extension for consistency, and to allow easy migration from one to the other.

cc/ @cescoffier

**Comment by cescoffier** [comment]
Awesome! Thanks!
