### ISSUE TITLE
Add support for deep stubbing in @InjectMock

### ISSUE THREAD

**Issue by goldmann** [quarkusio/quarkus#18236]
## Description

It would be very nice to have support for https://www.javadoc.io/doc/org.mockito/mockito-core/2.13.0/org/mockito/Mockito.html#RETURNS_DEEP_STUBS for bean injected with the `@InjectMock`.

## Implementation ideas

This could be implemented as a new parameter in the `@InjectMock` annotation, like `deepStubs`. Default value would be `false`.

**Comment by geoand** [comment]
Thanks! 

I'll have a look

**Comment by geoand** [comment]
Here you go: https://github.com/quarkusio/quarkus/pull/18243
