### ISSUE TITLE
Make `quarkus.artemis.url` optional

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#18231]
In Camel Quarkus we encourage our users to use quarkus-artemis-jms together with our camel-quarkus-jms extension. Camel has some alternative ways to configure Artemis, e.g. end users can produce their own ConnectionFactory. In such a case, quarkus-artemis-jms complains about missing quarkus.artemis.url, although in fact it is not needed. Thus we'd appreciate if quarkus.artemis.url could please be made optional.

This is very similar to https://github.com/amqphub/quarkus-qpid-jms/issues/11

**Comment by ppalaga** [comment]
cc @jamesnetherton

**Comment by gsmet** [comment]
@ppalaga so you mean you have an error if you just add the extension and don't configure it?

If so, yes, it needs a fix.

**Comment by ppalaga** [comment]
> @ppalaga so you mean you have an error if you just add the extension and don't configure it?

Yes

**Comment by zhfeng** [comment]
@gsmet @ppalaga ```quarkus.artemis.url``` is inherited from artemis-core ArtemisRuntimeConfig. If we make it optional, it would produce the ```ServerLocator``` and ```ConnectionFactory``` as null value. But these classes are used in health check which is default enabled in buildtime. I'd like to suggest to introduce such a configItem like ```quarkus.artemis.enabled``` in ArtemisBuildTimeConfig to disable produce ```ServerLocator``` in artemis-core and ```ConnectionFactory``` in artemis-jms. WDYT ?

**Comment by ppalaga** [comment]
Can't we disable the health check based on the availability of quarkus.artemis.url and thus also ServerLocator and ConnectionFactory?

**Comment by zhfeng** [comment]
I think we can not do this because ```quarkus.artemis.url``` is a runtime config and we decide the health check during building time and can not retrie the runtime config value.

**Comment by ppalaga** [comment]
> I think we can not do this because `quarkus.artemis.url` is a runtime config and we decide the health check during building time and can not retrie the runtime config value.

Oh, I see, thanks for the explanation. But if so, I am not 100% sure the proposed `quarkus.artemis.enabled` property would be an acceptable solution for Camel K folks. WDYT @lburgazzoli?

**Comment by lburgazzoli** [comment]
I don't think this is just for camel-k as any camel user that want to configure the jms component programmatically would hit the same issue.

@n1hility @maxandersen this falls in the same category as of the `quarkus.google.*` property we have been discussing some time ago so we probably need to have a generic solution.

A side note: if the health checks are a build time things, IMHO, they should be smart enough to handle the case where the runtime bits they depends on are not available and as a consequence auto disable themself or work in a degraded mode.

**Comment by stuartwdouglas** [comment]
Why not just have the health check manually read the config, and if this is not present it can just return UP.

**Comment by zhfeng** [comment]
@stuartwdouglas it makes sense and I will work on this proposal if we all agree.

**Comment by gsmet** [comment]
I forgot to post it here but I started working on that last week:
- I indeed did what @stuartwdouglas suggested
- but... I ended up with the issue that I was unable to not produce the beans as beans are defined before the runtime phase - and producing a null bean didn't sound very appealing...

**Comment by zhfeng** [comment]
Thanks @gsment and the beans you mentioned to produce are ```ConnectionFactory``` in artemis-jms and ```ServerLocator``` in artemis-core ?

**Comment by gsmet** [comment]
Yeah exactly.

**Comment by stuartwdouglas** [comment]
Can we add a 'DynamicHealthCheck' interface (name may need some work) that has an isEnabled() method, and if a health check implements this have Smallrye Health Check call this method do decide if the beans are enabled at runtime?

**Comment by zhfeng** [comment]
@gsmet are you stll working on this issue and how do you think to introdue ```quarkus.artemis.enabled``` at build time to avoid producing the null bean when ```quarkus.artemis.url``` is not configure.
