### ISSUE TITLE
Extend MicroProfile Rest Client documentation

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#18234]
1. Search:

- `http` doesn't show rest clients. 
- `rest client` doesn't show `rest-client-reactive`

2. Things missing from the guide that need to be described in the reference guide for the Rest Client (Reactive?):

- ClientBuilder API
- `@HeaderParam`

**Comment by michalszynkiewicz** [comment]
I think the docs have improved since the issue was created, up to you @Sgitario if you want to keep it

**Comment by Sgitario** [comment]
I see there is documentation about the items you mentioned in the description. So, let's close this issue and create others if users need it for more specific things.
