### ISSUE TITLE
QUARKUS_OIDC_CONNECTION_DELAY not working in 2.0.0.Final

### ISSUE THREAD

**Issue by segersb** [quarkusio/quarkus#18249]
## Describe the bug
The environment property QUARKUS_OIDC_CONNECTION_DELAY is not working anymore when using quarkus 2.0.0.Final.

### Expected behavior
Quarkus should wait for Keycloak to be up.

### Actual behavior
Quarkus quits immediately after a ConnectionRefused error.

## To Reproduce

Set up Quarkus with Keycloak, in my setup I use the Keycloak policy provider.
Start Quarkus without starting Keycloak.

**Comment by gsmet** [comment]
@sberyozkin could you check this? And potentially redirect to @radcortez if it's a general config issue.

**Comment by radcortez** [comment]
It seems that the policy enforcer tries to establish an HTTP connection before the OIDC connector. If we turn the policy enforcer off, then the delay works as expected, so it doesn't seem like a configuration issue (values not being applied or read).

**Comment by sberyozkin** [comment]
@radcortez Interesting, it is now initialized in the recorder, so it looks like `quarkus-keycloak-authentication` needs to wait till `quarkus-oidc` finishes its initialization in `OidcRecorder` - I wonder what is the right mechanism, it is done at runtime...

**Comment by radcortez** [comment]
Maybe  a dependency issue between BuildItems?

**Comment by geoand** [comment]
> Maybe a dependency issue between BuildItems?

This would be enough

**Comment by radcortez** [comment]
I don't believe so.

**Comment by geoand** [comment]
@segersb any chance you can let us know if this is still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
