### ISSUE TITLE
Generated resources are not recognized. Getting 404

### ISSUE THREAD

**Issue by GopisettyVasavi** [quarkusio/quarkus#18257]
I am using openAPI 3.0.0 to generate the source for my swagger.
I use -tags to group the resources.
some scenarios, though I could see quarkus listing the endpoints at http://localhost:8080/src/main/resources/META-INF/resources, I get 404, saying full path is not found.
If I separate the endpoints into multiple tags(generates multiple API interfaces), then it's finding the endpoint/resource.

I have tried changing parameters etc., but not any use.
All i change is the tags in swagger spec, so endpoints are split in multiple APIs then quarkus resource is identifying it at runtime or else its 404.
Is there any rule for this in quarkus? Like what kind of endpoints should be grouped?

**Comment by gsmet** [comment]
@GopisettyVasavi I think we would need a reproducer (a simple Maven project reproducing the issue) to understand what's going on.

**Comment by phillip-kruger** [comment]
There is no rules in Quarkus that should do what you describe. I would need a reproducer to look at this.

**Comment by gsmet** [comment]
No reproducer, closing.
