### ISSUE TITLE
Opentelemetry server templating does not work with template in class Path annotation

### ISSUE THREAD

**Issue by hacst** [quarkusio/quarkus#18251]
## Describe the bug
I'm not sure whether this should even be allowed, but when adding a Path annotation with a template parameter to a class the server span contains the actual path of the request instead of the templated version.

According to @kenfinnigan it is worth figuring out what is supposed to happen here.

### Expected behavior
Either Quarkus should complain about the template parameter in that place or the template should be correctly replaced.

### Actual behavior
The actual url without replacement is used as the name of the server span.

## To Reproduce
The problem is reproducible with a resource similar to:
```java
@Path("/tracing/filter/{dummy}")
public static class TestResource {
  @GET
  public String get(@PathParam("dummy") String dummy) {
    // ...
  }
}
```

The resulting name of the span has the full path of e.g. `/tracing/filter/1234` instead of the template `/tracing/filter/{dummy}`.

in contrast templating is working fine with
```java
@Path("/tracing")
public static class TestResource {
  @GET
  @Path("/filter/{dummy}")
  public String get(@PathParam("dummy") String dummy) {
    // ...
  }
}
```
### Quarkus version or git rev
2.0.0.Final

**Comment by kenfinnigan** [comment]
From a brief look it's valid for `@Path` on a class to have templated values, so looks like a bug in determining templated paths.

**Comment by geoand** [comment]
> From a brief look it's valid for `@Path` on a class to have templated values, so looks like a bug in determining templated paths.

Yes, it is valid - albeit not widely used :)
