### ISSUE TITLE
gradle plugin does not consider application.properties file

### ISSUE THREAD

**Issue by anadollu** [quarkusio/quarkus#1825]
Steps to reproduce 
1. convert Application Config project from quarkus-quickstarts projects to gradle project
https://github.com/quarkusio/quarkus-quickstarts/tree/master/application-configuration
2. build and run  directly (java -jar)  or gradle quarkusDev 
3. then you will get an exception " javax.enterprise.inject.spi.DeploymentException: No config value of type class java.lang.String exists for: greeting.message"

After investigating the problem,  i found that there is no application.properties file in the jar generated in the build folder ( xxxxxx-runner.jar or xxxxx-dev.jar)

**Comment by geoand** [comment]
Hi @anadollu 

There have been a lot of changes on the gradle front since `0.12.0`. I would suggest that you either try using `master` or wait (a few hours most likely) for `0.13.0` to see if the problem has been fixed.

**Comment by stalep** [comment]
Yes, this have been fixed in master and will be visible in the upcoming `0.13.0` version.
