### ISSUE TITLE
OpenTelemetry ClientTracingFilter adds credentials to http.url field

### ISSUE THREAD

**Issue by hacst** [quarkusio/quarkus#18250]
## Describe the bug
The `http.url` attribute `ClientTracingFilter` sets contains the userinfo portion of the URL to which https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes states "http.url MUST NOT contain credentials passed via URL in form of https://username:password@www.example.com/."

### Quarkus version or git rev
2.0.0.Final

**Comment by kenfinnigan** [comment]
Is it "safe" to look for `@` and exclude everything before it?

**Comment by hacst** [comment]
If an `@` is present dropping everything between the first `//` up to and including the `@` should be correct. At least that's my reading of https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax to get rid of the userinfo portion.
