### ISSUE TITLE
HibernateValidatorProcessor fails with Jandex ClassCastException on openshift deployment target

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18265]
## Describe the bug
While deploying an application on openshift, that has a dependency on hibernate validator -- the `ClassCastException` is thrown 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.ClassCastException: class org.jboss.jandex.ClassInfo cannot be cast to class org.jboss.jandex.MethodInfo (org.jboss.jandex.ClassInfo and org.jboss.jandex.MethodInfo are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @45655e8d)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Similar issue**: https://github.com/quarkusio/quarkus/issues/17491

## To Reproduce

Repository: https://github.com/kshpak/quarkus-openshift-test-suite/tree/feat/upgrade_2x
Branch: feat/upgrade_2x

1. Login to OpenShift cluster

2. mvn clean install -Dquarkus-core-only -Dversion.quarkus=2.0.0.Final -Dts.use-ephemeral-namespaces=true -pl .,app-metadata/deployment,app-metadata/runtime,common,sql-db/app -DskipTests=True -DskipITs=true

3. mvn clean verify -Dquarkus-core-only -Dts.use-ephemeral-namespaces=true -fae -Dversion.quarkus=2.0.0.Final -Dts.authenticated-registry -Dinclude.datagrid -Dinclude.serverless -pl sql-db/postgresql

_This will install the required dependency for `sql-db/postgresql` project and will run this project with `quarkus-bom` and `2.0.0.Final`_ 

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev
2.0.0.Final (Core)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment]
Can we have the full stacktrace please?

**Comment by gsmet** [comment]
There's a good chance it's just: https://quarkus.io/guides/getting-started-testing#quarkus-test-resource .

**Comment by gsmet** [comment]
Wrong copy paste, I meant: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#jandex-upgrade .

**Comment by kshpak** [comment]
Full stacktrace: 
[fullstacktrace.txt](https://github.com/quarkusio/quarkus/files/6740686/fullstacktrace.txt)

cc @geoand

**Comment by kshpak** [comment]
Updating jandex maven plugin solves this, thanks @gsmet 
cc @geoand
