### ISSUE TITLE
Allow integration with zipkin

### ISSUE THREAD

**Issue by raul-valdoleiros-gowithflow-io** [quarkusio/quarkus#18278]
## Description

Allow integration with zipkin like discussed in zulip

**Comment by mkouba** [comment]
I wonder if this is still relevant in the context of [Quarkus Observability Roadmap 2023](https://quarkus.io/blog/quarkus-observability-roadmap-2023/).

CC @brunobat @radcortez

**Comment by brunobat** [comment]
We should allow integration with Zipkin through a OTLP Exporter. See: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#zipkin-exporter
This issue still make sense.

**Comment by raulvaldoleiros** [comment]
Hi @brunobat, somehow the mails were in the junk folder :)

The development was done in this mr https://github.com/quarkusio/quarkus/pull/18313, so I believe this issue is finished :)

**Comment by brunobat** [comment]
Grand! Thanks @raulvaldoleiros
