### ISSUE TITLE
Development mode quarkus:dev not working with kotlin sources

### ISSUE THREAD

**Issue by Teg79** [quarkusio/quarkus#1827]
In my project there is the kotlin extension.
When I run the `quarkus:dev` mode the server starts correctly but if I modify the sources the live recompile and reload doesn't trigger.
With java sources it works.

Attached you can find the example project
[getting-started.tar.gz](https://github.com/quarkusio/quarkus/files/3036062/getting-started.tar.gz)

**Comment by geoand** [comment]
Hi @Teg79 ,

The Kotlin reload use case works fine when Maven is properly configured. I would suggest that you create a project using:

```
mvn io.quarkus:quarkus-maven-plugin:0.12.0 -DprojectGroupId=org.acme -DprojectArtifactId=kt     -DclassName="org.acme.rest.GreetingResource" -Dpath="/greeting" -Dextensions="kotlin"
```
and building up your project from there.

I am going to close this for the time being. If you create a project like I mention above and then still run into problems, feel free to reopen.

**Comment by Teg79** [comment]
Thanks @geoand , 
The archetype from scratch it's working.
If you create the project without the `kotlin` extension and add it later, it adds only the dependency, the kotlin maven plugin is missing.

PS
there is a typo in your command, the working version is:
```
mvn io.quarkus:quarkus-maven-plugin:0.12.0:create -DprojectGroupId=org.acme -DprojectArtifactId=kt     -DclassName="org.acme.rest.GreetingResource" -Dpath="/greeting" -Dextensions="kotlin"

```

**Comment by geoand** [comment]
Good to know @Teg79 :)

**Comment by Teg79** [comment]
My fault, the problem wasn't the kotlin extension but the Vert.x extension.
If I understand correctly the reload is triggered by a http request on undertow, if I don't use undertow (I removed the resteasy extension) but the vert.x web server, the reload automation is not working also with java
