### ISSUE TITLE
ServerResponseFilter isn't called when using a Multi as return type in Quarkus reactive

### ISSUE THREAD

**Issue by holledauer** [quarkusio/quarkus#18272]
## Describe the bug
@ServerResponseFilter function isn't called when using a Multi as return type in Quarkus Reactive. When using a Uni as return type it works.

### Expected behavior
The @ServerResponseFilter function ist called when returning a Multi.

### Actual behavior
The @ServerResponseFilter isn't called

### Quarkus version or git rev

2.0.0

**Comment by holledauer** [comment]
also the @Cache annotation does not work with Multi (it works with Uni)

**Comment by geoand** [comment]
This is by design, @FroMage can tell you more

**Comment by holledauer** [comment]
Maybe this should be added to the documentation. I couldn't find anything about it

**Comment by geoand** [comment]
Good idea. @FroMage would you like to add that?

**Comment by FroMage** [comment]
Sure: #18442
