### ISSUE TITLE
quarkus build -Dkey=value pairs should be passed through blindly

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18285]
## Describe the bug
at the moment we have special "propagatePropertyIfset" for quarkus build specific properties:

maven.repo.local, io.quarkus.maven.secondary-local-repo  and CONFIG_FILE_PATH_PROPERTY

this should not be in the cli as will have weird sidefects onusers.

### Expected behavior 
just pass any -Dkey=value through. 
I can;t think of a case where the cli treats key=value as somethng special that the build system shouldn't know about.

**Comment by ebullient** [comment]
This isn't quite what it appears.
create, dev, build all pass -D options through "blindly". 

The properties raised in this issue are tied to how we launch things (especially in test): 
"maven.repo.local" is set via the build... 
then the test calls new QuarkusCli().run(args) .. such that system properties used by the test are picked up, and then need to be propagated to the forked Maven/Gradle/JBang process..

**Comment by ebullient** [comment]
#18319 makes support for -D common across CLI subcommands and removes the special property-propagation paths.
