### ISSUE TITLE
Cannot use @Inject and @TestInstance(TestInstance.Lifecycle.PER_CLASS)

### ISSUE THREAD

**Issue by cristhiank** [quarkusio/quarkus#1828]
Quarkus testing brokes when you mark a `@QuarkusTest` with `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` and the test has an `@Inject` field

https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle

This happens because Quarkus is bootstrapped in a `@BeforeAll` hook https://github.com/quarkusio/quarkus/blob/ee8e68db3dfc991dad87983a1cda8d2d2faa18d5/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L80-L105
And JUnit's behavior is to instantiate the Test class before calling the `@BeforeAll` hook.
The class instantiation is done in: 
https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L297-L309 
and it tries to inject the dependencies but the ArC Container has not been initialized yet (chicken or egg problem)

I have a reproducer in https://github.com/cristhiank/quarkus-bugs

**Comment by cristhiank** [comment]
I wonder if it would be better to do the dependency injection implementing the JUnit `TestInstancePostProcessor` extension point ?. But I don't know all the implementation details

https://junit.org/junit5/docs/current/user-guide/#extensions-test-instance-post-processing

**Comment by manovotn** [comment]
Hmm, `TestInstancePostProcessor` probably won't help here. Quarkus is booted in `beforeAll()` and this  invocation will still come first if the lifecycle is set to `PER_CLASS`.

Maybe it would make sense to instead move the Quarkus boot to `createInstance()` and store some information about it into context store so we do it only once per test class. Then you could be always sure that you have quarkus and arc booted by the time you attempt injection?

I'll dig into this and see if I am right or wrong :)

**Comment by geoand** [comment]
Having Quarkus booted only once is a design decision as far as I understand (we only want to do it once since it contains the entire augmentation phase which is something we don't want running multiple times).
So perhaps we should also perform the same check that is done in `beforeAll` (meaning that we could maybe check the state and call `doJavaStart` iff the state does not contain the Quarkus info).

**Comment by manovotn** [comment]
@geoand yeah I understood as much.
There is already most of the logic needed to check if we are booted (`ExtensionState` is being stored into root context), so I am now testing that moving it into `createInstance()` won't break anything.

**Comment by geoand** [comment]
@manovotn awesome!
