### ISSUE TITLE
Console log has no color after switching to Quarkus 2.0.0.Final

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#18288]
## Describe the bug
Console log has no color after switching to Quarkus 2.0.0.Final

### Expected behavior
![image](https://user-images.githubusercontent.com/70388114/124052663-767c5d00-da51-11eb-92ca-9c854456f141.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/70388114/124052725-927ffe80-da51-11eb-8adc-d7936812d8f8.png)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.log.console.color=true
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `java -version`
java version: 11
### Quarkus version or git rev
quarkus version: 2.0.0.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven version: 3.8.1
## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
I don't see this behavior in various sample projects.

What OS are you running on? What terminal are you using?

**Comment by aomsweet** [comment]
@geoand 

OS: Windows 10 20H2 64bit
Terminal: Intellij IDEA Application run

![image](https://user-images.githubusercontent.com/70388114/124207120-6038d480-db17-11eb-950d-b90bf45f8f86.png)

**Comment by geoand** [comment]
I am personally seeing the same behavior in both `2.x` and `1.13`

**Comment by aomsweet** [comment]
Do you also use Intellij IDEA? I switched to 1.13.7.Final and it worked fine, but 2.0.0.Final could not display colors.

**Comment by geoand** [comment]
Yes, I use IntelliJ `2021.1.3`

**Comment by knutwannheden** [comment]
FYI: Possibly you would like to test #18258. I tested it and on-my-machine™️ it fixed the coloring problem as well as another issue. It should be included in the upcoming 2.0.1 release.

**Comment by gsmet** [comment]
Might have something to do with Windows. @stuartwdouglas does it ring a bell? I know you did a couple adjustments there.

**Comment by aomsweet** [comment]
Hi. @knutwannheden  I tested 2.0.1.Final and no coloring.  

reproducer: 
[https://github.com/aomsweet/quarkus2-issue18287](https://github.com/aomsweet/quarkus2-issue18287)

**Comment by aomsweet** [comment]
Use `main(String[] args)` to start it to display the color. Use `Intellij IDEA Quarkus plugin` to start, the color cannot be display.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/18506 should fix it, I will boot into windows later today to test it.

**Comment by stuartwdouglas** [comment]
So the linked PR fixes the color, but it won't add the proper console, as the plugin does not run inside a real terminal.

If you do mvn quarkus:dev in the intellij terminal you will get the full terminal experience.
