### ISSUE TITLE
what the behavior of multi-profile properties config?

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#18292]
## Description
I saw this PR https://github.com/quarkusio/quarkus/pull/11145 but it didn't specify the behavior under multi-profile settings, for example, if I run in dev mode, it will try to pick up config from `application-dev.properties` first, and then fallback to `application.preperties`?

I assume the behavior is the same as `%prof.aa.bb.cc` and `aa.bb.cc` under single-config setting. I've done some small experient and seems that's true. Can we have a confirmation on that? 

And a more complex usecase: say I have `application-dev.properties` containing property `aa.bb.cc`, and a conflict property is also given in `application.preperties` like `%dev.aa.bb.cc`, what is behavior in this case? (I know this might be not a valid usecase and might be developer's mistake, but still want to know the mechanism behind this)

BTW maybe add this to the official guide? (I was not even aware of the multi-profile features, I found that PR by chance...from this issue https://github.com/quarkusio/quarkus/issues/18015)

## Implementation ideas
(If you have any implementation ideas, they can go here.)

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
> ## Description
> I saw this PR #11145 but it didn't specify the behavior under multi-profile settings, for example, if I run in dev mode, it will try to pick up config from `application-dev.properties` first, and then fallback to `application.preperties`?
> 

Yes.

> I assume the behavior is the same as `%prof.aa.bb.cc` and `aa.bb.cc` under single-config setting. I've done some small experient and seems that's true. Can we have a confirmation on that?
> 

Yes.

> And a more complex usecase: say I have `application-dev.properties` containing property `aa.bb.cc`, and a conflict property is also given in `application.preperties` like `%dev.aa.bb.cc`, what is behavior in this case? (I know this might be not a valid usecase and might be developer's mistake, but still want to know the mechanism behind this)
> 

It also works. The rule here is that the profiled file `application-dev.properties` will always have priority. So the order is:
- Profile aware files
- Profile named properties
- Regular names properties

> BTW maybe add this to the official guide? (I was not even aware of the multi-profile features, I found that PR by chance...from this issue #18015)

You can find most of the information here https://quarkus.io/guides/config-reference#profiles, except the case where you mix both. I can add a clarification there. Please let me know if the guide is missing anything else. Thank you.

**Comment by liuzqt** [comment]
Thanks for the explanation!
