### ISSUE TITLE
Support customization of the project name and version in logs

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1829]
The log says: 

```
INFO  [io.quarkus] (main) Quarkus 0.12.0 started in 0.007s. Listening on: http://localhost:8080
```

It would be nice if the project name and version could be customized in the logs, like in the example below:

```
INFO  [io.quarkus] (main) Fabric8 Launcher Backend 1.2.2 (Running on Quarkus 0.12.0) started in 0.007s. Listening on: http://localhost:8080
```

**Comment by gastaldi** [comment]
Bonus points if this customization can be specified through Microprofile Config (`application.properties`)

**Comment by klearchos** [comment]
Hi @gastaldi 
I found that I will have to update the io.quarkus.runtime.Timing
Do you have any other pointers that I should take care of?

It would be nice to have ascii art during startup as it happens with Spring Boot ?
What do you think?

**Comment by gastaldi** [comment]
@klearchos yeah, I think this is where the Config needs to be read to gather the product name. I am not opposed to an ASCII art, but I'm fine with whatever the Quarkus team decides :)
