### ISSUE TITLE
QUARKUS - CONTINUOUS TESTING Guide  Configuration property table layout broken

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus#18296]
## Description
See https://quarkus.io/guides/continuous-testing#configuring-continuous-testing starting with `quarkus.test.exclude-pattern`

## Implementation ideas
Looks to be a minor table formatting issue, if you could point out where the docu is generated from i could check it.

**Comment by geoand** [comment]
cc @gsmet

**Comment by gsmet** [comment]
Ah, yes, we need to escape `|`. I'll have a look, thanks for the report.

**Comment by gsmet** [comment]
Fixed on the website and https://github.com/quarkusio/quarkus/pull/18304 will fix it for good.
