### ISSUE TITLE
Build fails when defining property quarkus.kubernetes.pvc-volumes

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#18294]
## Describe the bug
Build fails when application.properties contains the property _quarkus.kubernetes.pvc-volumes_ 

### Expected behavior
build task should add the persistent volume claim info inside the kubernetes deploy script.

### Actual behavior
build fails with error
`java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.PersistentVolumeClaimVolumeSourceFluent io.fabric8.kubernetes.api.model.VolumeFluent$PersistentVolumeClaimNested.withNewReadOnly(boolean)'`

## To Reproduce

https://github.com/iompo/quarkus-error-kubernetes-pvc

1. run command: ./gradlew build 

## Environment:

Quarkus 2.0.0
Gradle 6.8.3
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)

**Comment by geoand** [comment]
Looks like a Dekorate issue, right @iocanel !

**Comment by geoand** [comment]
@iocanel this came up again. Can you take a look?

**Comment by iocanel** [comment]
It seems like kubernetes-model mismatch. Not sure if its part of dekorate or kubernetes-extension, without a stacktrace. But, I'll try it locally and see.
