### ISSUE TITLE
Quarkus OpenShift extension pulls every tagged version of image into ImageStream

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18306]
## Describe the bug
While deploying Quarkus application to OpenShift via Source To Image (S2I) base image, the Image Stream for that image in the project namespace contains every tagged version of this image (including source files).

Is there a reason for that? It introduces a lot of memory being consumed to store them.

### Expected behavior
Only the `latest` image is pulled (if a specific tag version is not specified)

### Actual behavior
Pulls every tagged version of an image. But uses only `latest`.

## To Reproduce
https://github.com/kshpak/quarkus-openshift-test-suite/tree/feat/upgrade_2x

**Login to openshift cluster ( version 4.6.35)**

1. mvn clean install -Dts.use-ephemeral-namespaces=true -pl .,app-metadata/deployment,app-metadata/runtime,common,sql-db/app -DskipTests=True -DskipITs=true
2. mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.kubernetes-client.trust-certs=true -pl microprofile/
3. See Image Stream for openjdk-11 contains 31 pulled images

### Configuration
```properties
quarkus.openshift.route.expose=true
quarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-11

```

### Screenshots

![image](https://user-images.githubusercontent.com/71509020/124131364-046f3c80-da80-11eb-95cf-a7234ebb1407.png)

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Maven version
Apache Maven 3.8.1

### Quarkus version or git rev
2.0.0.Final
1.11.7.Final

### OpenShift version
4.6.35

**Comment by geoand** [comment]
cc @iocanel

**Comment by kshpak** [comment]
Closing this. Not an issue. ImageStreams works that way
