### ISSUE TITLE
Lambda extension: Class not found: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler

### ISSUE THREAD

**Issue by smoell** [quarkusio/quarkus#18315]
## Describe the bug
After migrating to Quarkus 2.0, I ran into an issue with SAM local:

`Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorMessage': 'Class not found: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler', 'errorType': 'java.lang.ClassNotFoundException'}`

### Expected behavior
Class `QuarkusStreamHandler `is found, Lambda function can be tested properly using SAM local

### Actual behavior
Class `QuarkusStreamHandler` is not found, exception is thrown

## To Reproduce

Project: https://github.com/aws-samples/aws-quarkus-demo

1. git clone https://github.com/aws-samples/aws-quarkus-demo
2. cd aws-quarkus-demo/lambda
3. ./mvnw clean package
4. sam local start-api --template sam.jvm.yaml
5. curl -v -d '{"userName":"jdoe", "firstName":"John", "lastName":"Doe", "age":"35"}' -H "Content-Type: application/json" -X POST  http://127.0.0.1:3000/users

### Configuration
All configs are in the repository

### Screenshots
(If applicable, add screenshots to help explain your problem.)

**Comment by patriot1burke** [comment]
Not sure who created these examples but they are out of date.  The included sam template is out of date.  We now generate this file and also generate a function.zip.

Try 

`sam local start-api --template target/sam.jvm.yaml`

https://quarkus.io/guides/amazon-lambda#testing-with-the-sam-cli

**Comment by patriot1burke** [comment]
Don't close this bug, the demo needs to be removed or updated.

**Comment by smoell** [comment]
This is my demo, I just updated this from Quarkus 1.x to 2.0 and I ran into this issue. The generated SAM template doesn't contain the DynamoDB local config, so I can't use it (not sure if there's mechanism to add this dynamically)

**Comment by smoell** [comment]
OK, found it, thank you, now it works again.
