### ISSUE TITLE
Don't automatically start Kafka container with DevServices if broker already present

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#18318]
## Description

Currently, when running `mvn quarkus:dev` with the `quarkus-smallrye-reactive-messaging-kafka` extension present it starts a RedPanda container even if I have a Kaka Broker running in Docker at localhost:9092.

## Implementation ideas

If it could recognize a Kafka Broker already exists on the default path and not start RedPanda

**Comment by stuartwdouglas** [comment]
This sounds a bit dangerous to just connect to any running Kafka?

**Comment by kenfinnigan** [comment]
Well, not any running, only a localhost broker.

It was just annoying because I couldn't run it in DEV mode as it keeps starting RedPanda.

Is there a way to disable it from starting that container?

**Comment by stuartwdouglas** [comment]
It won't start it if you have configured a server to connect to with a URL.

**Comment by kenfinnigan** [comment]
Hmm. Bit annoying to have to specify the same as the default broker URL to prevent it.

If we don't think it's worth worrying about I'm fine with closing

**Comment by stuartwdouglas** [comment]
So did this used to work? For databases this was not an issue, as we never had a 'default URL', did Kafka previously have this?

**Comment by kenfinnigan** [comment]
I don't know, only happened to hit it today when I tried.

I think Kafka has had a default Broker URL for a while, at least Reactive Messaging has

**Comment by cescoffier** [comment]
Yes, there is a default location. 
Do you have 'kafka.bootstrap.servers' set in your application.properties?

If you don't, it will start the broker. Before it was connecting to localhost:9092.

**Comment by kenfinnigan** [comment]
I didn't, as it was the same location, so I was trying to just "piggyback"

**Comment by patrox** [comment]
Hey @kenfinnigan, maybe this shared broker setup, will help you, as this seems to be somehow related: https://github.com/quarkusio/quarkus/pull/17837

**Comment by cescoffier** [comment]
Added a section in the migration guide.
