### ISSUE TITLE
Continuous Testing not using updated log level

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#18330]
## Describe the bug
Quarkus 2.0.0.Final Continous Testing not applying an updated log level changed in application.properties

### Expected behavior
Log level does not change. When app started with default (INFO), and then quarkus.log.level is updated to a higher log level (like TRACE or DEBUG), the logs should include the appropriate logging statements.

### Actual behavior
Logging continues to log at INFO log level.

## To Reproduce

1. Clone the [reproducer git repo](https://github.com/jclingan/continuous_testing_logging).
2. `mvn quarkus:dev`
3. Press 'r' to run tests
4. Press 'o' to enable output
5. Press 'r' to run tests again. Should see:
```
FATAL [org.acm.LoggingResource] ***** JBossLogManagerLogger: FATAL *****
ERROR [org.acm.LoggingResource] ***** JBossLogManagerLogger: ERROR *****
WARN  [org.acm.LoggingResource] ***** JBossLogManagerLogger: WARN *****
INFO  [org.acm.LoggingResource] ***** JBossLogManagerLogger: INFO *****
INFO  [io.quarkus] greeting stopped in 0.009s
```
6. In application.properties, update quarkus.log.level to TRACE.
7. Test will automatically run, and display above text reflecting the log level is still INFO.

**Comment by stuartwdouglas** [comment]
This is kind of by design, you have two applications present (the dev mode one and the test one) and only one can configure logging. Any %test logging config is ignored, and dev mode logging settings are used instead. 

In Quarkus upstream pressing 's' would restart the app and apply the logging changes. But I can't really see a good solution for this.

On an unrelated note this has given me an idea around logging and the console...

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/18331

**Comment by stuartwdouglas** [comment]
Hmm, looks like this is also a problem for mvn quarkus:test. I will fix that.

**Comment by jclingan** [comment]
Thanks. I didn't even think of the app being in test mode, although it is "continuous *TESTING*", LOL.

**Comment by jclingan** [comment]
Closing this issue, understanding that this will be fixed with #18331

**Comment by stuartwdouglas** [comment]
That PR does not really fix it, it allows you to easily toggle the log level from the console (the idea I mentioned above).

I am working on a PR now that will fix it for mvn quarkus:test, but the mvn quarkus:dev mode behaviour won't change.

**Comment by jclingan** [comment]
Thx.

**Comment by stuartwdouglas** [comment]
The linked PR should fix it
