### ISSUE TITLE
Adding Support io.smallrye.config.ConfigMapping to support Java  Records

### ISSUE THREAD

**Issue by fordsworth** [quarkusio/quarkus#18338]
## Description
It would be nice if one could use Java 14 records to map application properties with ConfigMapping
(Describe the feature here.)
One will be able to configure properties and then bind them directly to the Java Record Class properties

**Comment by geoand** [comment]
`ConfigMapping` can only supports interfaces in the latest SmallRye Config releases, so I will close this.
