### ISSUE TITLE
Fix inconsistent behavior for quarkus.jaeger.reporter-log-spans between native/non-native

### ISSUE THREAD

**Issue by christian-morin** [quarkusio/quarkus#18346]
## Description

When enabling the log-span reporter for jaeger, the sent spans are reported, but the behaviour differs between native/non-native builds.

When running in java-mode, the LoggingReporter from Jaeger-client is used: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/reporters/LoggingReporter.java. It produces the following log-output:
```
2021-07-01 11:36:17.890  INFO 57947 --- [vert.x-worker-t] io.ja.in.re.LoggingReporter : Span reported: 79849c0ae5afa2ef:dbf5e2379cd593e:79849c0ae5afa2ef:1 - GET
```
But when running in native-mode:
```
--- not logging: f2c37d78d475ccf4:acd21ae452e05d6d:e751e2cdb1c44646:1 - GET
```
This is because the https://github.com/quarkusio/quarkus/blob/main/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/graal/Target_LoggingReporter.java is used, which simply writes to stderr instead of a proper log.
```java
@Substitute
    @Override
    public void report(JaegerSpan span) {
        System.err.println("--- not logging: " + span);
    }
```
Is there a reason for it not simply using a org.jboss.logging.Logger for this, in order to get a proper log instead?

Sorry if this might be an obvious limitation and there's nothing that can be done in regards to this, but it creates a bit of inconsistency amongst our different Quarkus services when they're not reporting spans created the same way (and also making us have to parse non-log-lines).

## Implementation ideas

Simply change the io.quarkus.jaeger.runtime.graal.Target_LoggingReporter
```java
@Substitute
    @Override
    public void report(JaegerSpan span) {
        System.err.println("--- not logging: " + span);
    }
```
into:
```java
@Substitute
    @Override
    public void report(JaegerSpan span) {
        logger.info("Span reported: {}", span);
    }
```
using org.jboss.logging.Logger

**Comment by kenfinnigan** [comment]
We'd love for you to submit a PR with the proposed fix
