### ISSUE TITLE
Qute - @CheckedTemplate Parameter names not recorded error

### ISSUE THREAD

**Issue by sam959** [quarkusio/quarkus#18357]
## Describe the bug
I have defined a class
```
@io.quarkus.qute.CheckedTemplate
public class CheckedTemplate {
  public static native TemplateInstance mailTemplate(List<String> templateValues);
}
```
I have the template under `resources/templates/mailTemplate`

In another class, I inject the a `List<String> templateValues` with:

`CheckedTemplate.mailTemplate(templateValues).renderAsync();`

### Expected behavior
The value is injected

### Actual behavior
Starting Quarkus in dev mode fails with message:
```
Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#collectCheckedTemplates threw an exception: io.quarkus.qute.TemplateException: Parameter names not recorded for com.org.outbound.template.CheckedTemplate: compile the class with -parameters
	at io.quarkus.qute.deployment.QuteProcessor.collectCheckedTemplates(QuteProcessor.java:336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
```

## Environment (please complete the following information):
Quarkus dev

### Output of `java -version`
Java 16

### Quarkus version or git rev
1.13.4.Final

**Comment by mkouba** [comment]
Hi @sam959, this behavior is expected. You need to instruct the compiler to store the parameter names in the class files, e.g. for the `maven-compiler-plugin`: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters.
