### ISSUE TITLE
quarkus-amazon-lambda-rest:  wrong base64 encoding and unable to add binary type by configuration

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#18356]
## Describe the bug

Quarkus version: 2.0.0
Environment:  AWS ALB -> Quarkus

When downloading binary content from ALB you will receive a HTTP 502. 
See also: https://github.com/awslabs/aws-serverless-java-container/issues/339

In the following class:

_https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/LambdaHttpHandler.java_

the body is encoded using the MimeEncoder:
`responseBuilder.setBody(Base64.getMimeEncoder().encodeToString(baos.toByteArray()));`

This should be changed to
`
responseBuilder.setBody(Base64.getEncoder().encodeToString(baos.toByteArray()));`

Don't forget the other way around!

Also it would be very nice to be able to add binary content by a config property.

 Now i have to do it myself by using the following code:

```
    //also base64 encode http application/pdf content
    LambdaContainerHandler.getContainerConfig().addBinaryContentTypes(.........);    
    //default charset should be UTF-8
    LambdaContainerHandler.getContainerConfig().setDefaultContentCharset(StandardCharsets.UTF_8.name());
```

**Comment by patriot1burke** [comment]
Ok, i'll include this in my PR i'm working on.

**Comment by argenstijn** [comment]
Thanks.
 Any idea when this fix will be implemented?

**Comment by patriot1burke** [comment]
Working on it now.

**Comment by patriot1burke** [comment]
FYI, I don't think I want a config switch for binary types.  I'm just going to *not* base 64 encode media types of "text", "xml", or "json".  Everything else will be encoded.

**Comment by argenstijn** [comment]
Fair enough. But then again, the user should eventually decide what he/she want to do with it. Maybe it has it's own custom media types....etc.
