### ISSUE TITLE
quarkus-redis-client needs ZUNION method

### ISSUE THREAD

**Issue by kafeltz** [quarkusio/quarkus#18351]
The **ZUNION** method is missing in the [quarkus-redis-client](https://mvnrepository.com/artifact/io.quarkus/quarkus-redis-client). Currently there is only the **ZUNIONSTORE** method.

This one: https://redis.io/commands/zunion

**Comment by patrox** [comment]
@kafeltz @machi1990 I can address this missing functionality if you aren't already working on this one.

**Comment by patrox** [comment]
It seems like Vert.x Redis client will have to be updated as well, as currently it doesn't support ZUNION neither: https://www.github.com/vert-x3/vertx-redis-client/tree/master/src%2Fmain%2Fjava%2Fio%2Fvertx%2Fredis%2Fclient%2FRedisAPI.java

**Comment by machi1990** [comment]
> It seems like Vert.x Redis client (which is used by `quarkus-redis-client`) will have to be updated as well, as it doesn't support ZUNION: https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/RedisAPI.java#L3500-L3516

@patrox thanks for the interest in fixing the issue. Yes, the command might need to be added in upstream first in Vertx 4. @pmlopes WDYT?

As an alternative for now: 

You can try injecting the plain vertx `io.vertx.redis.client.Redis` client. And use it to send the command.
```
redis.send(Request.cmd(Command.ZUNION).arg("arg1").arg("arg2").arg("arg3"), res -> {
  if (res.succeeded()) {
    
  }
});
```

using the mutiny based client: `io.quarkus.redis.client.runtime.MutinyRedis` will be the most appropriate
```
mutinyRedis.send(Request.cmd(Command.ZUNION).arg("arg1").arg("arg2").arg("arg3"))....
```

**Comment by patrox** [comment]
Thank you @machi1990 for the alternative suggestion, I can try that as I won't have to wait for the upstream change.

I created a feature request in Vert.x Redis Client  to address that in longer term as well:

https://github.com/vert-x3/vertx-redis-client/issues/299

**Comment by machi1990** [comment]
> Thank you @machi1990 for the alternative suggestion, I can try that as I won't have to wait for the upstream change.

Thanks, let me know how it goes. 

> I created a feature request in Vert.x Redis Client to address this in a longer term as well:
> 
> [vert-x3/vertx-redis-client#299](https://github.com/vert-x3/vertx-redis-client/issues/299)

Awesome. Thank you.

**Comment by patrox** [comment]
```
redis.send(Request.cmd(Command.ZUNION).arg("arg1").arg("arg2").arg("arg3"), res -> {
  if (res.succeeded()) {
    
  }
});
```

@machi1990 I'm afraid we won't be able to proceed this way, as the [`Command`](https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/Command.java#L233) enum doesn't include the `ZUNION` value :(

I updated it already on my PR which I'm going to open in vert.x redis client: https://github.com/patrox/vertx-redis-client/pull/1/files.

Maybe there should be a possibility to pass there plain `String`s (i.e. "ZUNION") instead of `Command` values (Command.ZUNION) ?

**Comment by machi1990** [comment]
> ```
> redis.send(Request.cmd(Command.ZUNION).arg("arg1").arg("arg2").arg("arg3"), res -> {
>   if (res.succeeded()) {
>     
>   }
> });
> ```
> 
> @machi1990 I'm afraid we won't be able to proceed this way, as the [`Command`](https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/Command.java#L233) enum doesn't include the `ZUNION` value :(
> 

@patrox thanks for finding sometime to look at this. 

Yes, we'll have to create a new command `Command.create("zunion".....)`. 

> I updated it already on my PR which I'm going to open in vert.x redis client: https://github.com/patrox/vertx-redis-client/pull/1/files.

It seems that this has been fixed in https://github.com/vert-x3/vertx-redis-client/commit/8d783078dbcf369d2a58197925bbf31c4a2594e3, we can wait for the new release and add all the new commands. It seems like there are couple others commands which might be useful. What do you think? 
And as for now, we can document how the user can handcraft missing commands (see #18378 )
 
> Maybe there should be a possibility to pass there plain `String`s (i.e. "ZUNION") instead of `Command` values (Command.ZUNION) ?

Yes, we'll have to create a new command `Command.create("zunion".....)`.

**Comment by patrox** [comment]
In the meantime @pmlopes has added the commands from a recent Redis server version (including ZUNION) to vert.x Redis client, so probably we will be able to use the new version soon .

**Comment by patrox** [comment]
@machi1990 Yes, I saw the other new commands which were added, so I can add these as well.

I can also document the workaround method as well - is it OK to do it in a single PR ? I can create separate commits for these changes.

**Comment by machi1990** [comment]
> @machi1990 Yes, I saw the other new commands which were added, so I can add these as well.
> 
> I'll monitor vert.x redis client to see if there is a new version.
> 
> I can also document the workaround method as well - is it OK to do it in a single PR ? I can create separate commits for these changes.

I think what we can do is document the workaround for now in a separate PR and we'll fix the issue once a new release of the redis client is there.

**Comment by pmlopes** [comment]
@machi1990 @patrox the fix will arrive with vert.x 4.2.0.

The workaround required defining the zunion command, you can do it as:

```java
public static final Command ZUNION = Command.create("zunion", -3, 0, 0, 0, false, true, true, false);
```

See the latest generation for 6.2.4 sources:

https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/Command.java

**Comment by patrox** [comment]
> @machi1990 @patrox the fix will arrive with vert.x 4.2.0.
> 
> The workaround required defining the zunion command, you can do it as:
> 
> ```java
> public static final Command ZUNION = Command.create("zunion", -3, 0, 0, 0, false, true, true, false);
> ```
> 
> See the latest generation for 6.2.4 sources:
> 
> https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/Command.java

Thanks @pmlopes, this is exactly what I was looking for!

**Comment by kafeltz** [comment]
@patrox I think the reactive library needs the **zunion** function too. Have you seen it?

**Comment by gastaldi** [comment]
Quarkus is using Vert.x 4.2.2. Is this still an issue?

**Comment by gsmet** [comment]
I think we probably still need to bind the new commands in the Quarkus impl if not already done.
