### ISSUE TITLE
Quarkus OIDC Client unable to retrieve access-token

### ISSUE THREAD

**Issue by chiragrp** [quarkusio/quarkus#18374]
## Describe the bug
I am using quarkus-oidc-client extension to obtain token. The idea is to send client-id, client-secret and grant-type to OpenID connect provider to obtain access token. I am referring to this doc @ https://quarkus.io/guides/security-openid-connect-client
I am using annotation "@OidcClientFilter" on a resource annotated using "@RegisterRestClient". 
The OidcClient is not able to retrieve access-token as it sends only grant_type=client_credentials to the OAuth server.

I have configured the extension with following configuration
```
quarkus.oidc-client.auth-server-url=https://openid-provider.org 
quarkus.oidc-client.discovery-enabled=false
quarkus.oidc-client.token-path=/token
quarkus.oidc-client.client-id=rf3ScIceRGbm8IShjMUDUY67INhJEGRb
quarkus.oidc-client.credentials.secret=************
#quarkus.oidc.authentication.scopes=EMAIL
```

### Expected behavior
OidcClient should sent HTTP post request with form having parameters "client_id", "client_secret", "grant_type" and "scopes".
The response should be a HTTP 200 from OAuth server as following:
{
"access_token": "",
"token_type": "",
"expires_in": "",
"issued_at": ""
}

Please refer to OAuth2 token response @ https://developer.okta.com/docs/reference/api/oidc/#request-example

### Actual behavior
As OidcClient is NOT sending client_id and client_secret, OAuth server is returning following error:

Caused by: io.quarkus.oidc.client.OidcClientException: 
                {  
                        "error":"invalid_client",
                        "error_description":"missing or invalid client_id or client_secret"
                }

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.oidc-client.auth-server-url=https://openid-provider.org
quarkus.oidc-client.discovery-enabled=false
quarkus.oidc-client.token-path=/token
quarkus.oidc-client.client-id=rf3ScIceRGbm8IShjMUDUY67INhJEGRb
quarkus.oidc-client.credentials.secret=************
quarkus.oidc.authentication.scopes=EMAIL
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):
Ubuntu 18 LTS

### Output of `uname -a` or `ver`
Linux inggou18 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)

### Quarkus version or git rev
1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven 3.6.6

## Additional context
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@chiragrp, sorry for a delay, typically the client id and secret are supplied as Basic Authentication credentials - but it looks like the OIDC provider you are dealing with does not support it - so a `client_secret_post` authentication method needs to be activated, have a look [here](https://quarkus.io/guides/security-openid-connect-client#oidc-client-authentication) how to do it and let me know if it fixes the problem, thanks

**Comment by chiragrp** [comment]
Thank you @sberyozkin for you response. I have tried with "client_secret_post" and ran into another issue of scope. I managed to send scope/permissions using `quarkus.oidc-client.grant-options.client.scope=EMAIL`
Now, I am able to receive response from OAuth server. However, OidcClientImpl.emitGrantTokens() method returns an error while getting "expires_in" property from JSON response. Code is expecting it to be Long but it is String.

Please see attached image.
![image](https://user-images.githubusercontent.com/1540450/124463957-3995ca80-ddb1-11eb-9c83-4ac82c08f6a3.png)

Could you please suggest how to handle this issue?

**Comment by sberyozkin** [comment]
@chiragrp Thanks for making it (nearly) work... So the provider is also returning a non-compliant `expires in` representation. I suppose we can fallback to trying to convert it from String, will do it shortly

**Comment by chiragrp** [comment]
Thank you @sberyozkin for you quick response and action!
