### ISSUE TITLE
All Configuration Options web page layout is broken

### ISSUE THREAD

**Issue by kekbur** [quarkusio/quarkus#18376]
## Describe the bug
The guide web page for all Quarkus configuration options has broken table layout. Tested on Firefox and Chrome:

![image](https://user-images.githubusercontent.com/10086020/124349695-4374cd80-dbf9-11eb-9406-75f0d676cdae.png)

## To Reproduce

Open https://quarkus.io/guides/all-config#quarkus-core_quarkus.test.exclude-pattern and scroll to `quarkus.test.exclude-pattern`.

**Comment by machi1990** [comment]
This is in relation to https://github.com/quarkusio/quarkus/issues/18335. Closing due to duplicate.

/cc @gsmet
