### ISSUE TITLE
Extend Redis extension documentation to show how custom commands can be crafted

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#18378]
## Description

At the moment, the Redis clients does not support all the commands supported by recent versions of Redis: see https://github.com/quarkusio/quarkus/issues/18351 for example. 
However the backing vertx-redis-client provides a way to craft commands using `.send(Request.Command)` method. 
See https://github.com/quarkusio/quarkus/issues/18351#issuecomment-873370806 for example. We can document how users can use the raw redis client to craft additional commands depending on their use cases.

## Implementation ideas

Add a section on the `redis-reference.adoc` how crafting a new command can be done using the `MutinyRedis` API.

**Comment by cescoffier** [comment]
This is more advanced material, so it should be in redis-reference.adoc (which would be the reference guide for redis).

**Comment by machi1990** [comment]
> This is more advanced material, so it should be in redis-reference.adoc (which would be the reference guide for redis).

Thanks @cescoffier I've modified the implementation detail about the file to edit.

@patrox this kind of touches what you are looking at in #18351 let me know if you'll be interested in looking at this one too. Thanks

**Comment by patrox** [comment]
@machi1990 Yes, I noticed this issue and I can handle it as well, as indeed, it's closely related to what I'm doing at the moment.
