### ISSUE TITLE
variable quarkus.oidc.auth-server-url is not overided

### ISSUE THREAD

**Issue by Emmanuel35** [quarkusio/quarkus#18382]
## Describe the bug
Variable OIDC can't be overided by a Kubernetes environment variable.

### Expected behavior
My application is built with this configuration.

OIDC configuration in properties file:
```
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/efr
quarkus.oidc.client-id=frontend
quarkus.oidc.application-type=web-app
```

During Kubernetes deployment, environments variables are used with a
```
  envFrom:
        - configMapRef:
            name: envs-administration-final-t2kkk6m7fd
```

ConfigMap contains other value:
```
QUARKUS_OIDC_AUTH-SERVER-URL=http://keycloak/auth/realms/efr
```

### Actual behavior

But, in runtime, a DEBUG message is shown:
```
2021-07-04 14:27:56.770 | DEBUG [io.qu.oi.ru.OidcRecorder] (vert.x-eventloop-thread-1) 'Default' tenant initialization has failed: 'OIDC server is not available at the 'http://localhost:8180/auth/realms/efr' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus''. Access to resources protected by this tenant will fail with HTTP 401.
```
Please:

* make an ERROR message if OIDC server is not available
* make this variable accessible with a environment variable. 

## To Reproduce

In dev profile: %dev.quarkus.oidc.enabled is used
In prod profile: quarkus.oidc.enabled is used.
It was produced with *prod* profile. 

## Environment (please complete the following information):

* Quarkus: 13.3.7.Final
* Kubernetes: GKE latest stable version
* Keycloak 14.0.0

### Output of `java -version`

Build done with jib

**Comment by geoand** [comment]
You need to use `QUARKUS_OIDC_AUTH_SERVER_URL` as the environment variable name

**Comment by geoand** [comment]
@sberyozkin maybe in prod-mode we should make the configuration mandatory instead of falling back to the `localhost...` value?

**Comment by sberyozkin** [comment]
@geoand Hi Georgios, thanks for checking this issue, it does not fallback to it, it is only used in the example URL.
Also, in 2.0.x it will try to recover at runtime if it can't connect though in this case it won't make a difference as the required value is not provided...

**Comment by geoand** [comment]
Gotcha, thanks!
