### ISSUE TITLE
[2.0.0.Final] Bean validation issue - fail to process @NonBlank constraint

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#18396]
## Describe the bug
Upgrading my project from 1.13.7.Final to 2.0.0.Final starts to fail applying  @NonBlank bean constraint, which used to work with Quarlus 1.13.x and older, despite hibernate validation being included in the gradle build and no other changes. 

See also:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.202.2E0.2E0.2EFinal.20-.20Bean.20validation.20issue

**Comment by gsmet** [comment]
@hrstoyanov please describe the issue in the description as it's the only way for people to search for similar issues.

As for your issue, I think the problem might be that your constraint was ignored until now (we fixed a few things regarding that). `@NotBlank` won't work for a `DatabaseType`.

If you have an example of what's not working and how you expect it to work, that would help.

**Comment by hrstoyanov** [comment]
@gsmet @radcortez 
This 2.0.0.Final issue could be with the hibernate bena validator, or teh way smallryee config is using it.
Here is a small reproducer: [issue_18396.zip](https://github.com/quarkusio/quarkus/files/6766813/issue_18396.zip)
You need to run it against a YAML config file, like the **hristo-test.yaml**, enclosed:
>./gradlew -p dbproxy -Dsmallrye.config.locations=/Users/hristo/Downloads/hristo-test.yaml  quarkusDev

**Comment by gsmet** [comment]
I don't know exactly what I'm supposed to do with the reproducer as it starts OK for me.

But as I mentioned earlier, looking at your code, this can't work:
```
    @NotBlank
    @WithName("level")
    @WithDefault("is_not_supported")
    EncryptionLevel level();
```

`@NotBlank` only supports `CharSequence` by default and you don't add any custom validator AFAICS. That's why you end up with this error message saying it doesn't find any validator for this constraint and type. You need to use `@NotNull`, not `@NotBlank`.

**Comment by hrstoyanov** [comment]
Are you using java 16?

**Comment by radcortez** [comment]
I also tried the reproducer and if we replace `@NonBlank` with `@NotNull` the app starts as expected.

Also, I think that `@NotNull` is not really required. Config never injects or retrieves a `null` value. A config `null` value look up always returns an exception and fails the application. The only exception is if the expected type is an Optional, but even in that case you get an empty Optional and never a `null`.

**Comment by hrstoyanov** [comment]
@radcortez any way to make the error show the bad annotated field?
