### ISSUE TITLE
https://quarkus.io/guides/all-config table is broken

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#18411]
## Describe the bug
All Config Table is broken (probably because a property value has un-escaped characters)

### Expected behavior

All Config page formatted correctly

### Actual behavior
All Config is formatted incorrectly 

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Go to https://quarkus.io/guides/all-config
2. Scroll until you find `quarkus.test.exclude-pattern` (use the browser's find feature to find it)

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
![image](https://user-images.githubusercontent.com/54133/124473578-e3effc80-dd75-11eb-9243-fe95b0af7ed9.png)

**Comment by gsmet** [comment]
This should already be fixed by https://github.com/quarkusio/quarkus/pull/18304 .

**Comment by gastaldi** [comment]
@gsmet you're right. I tried locally and the document is now generated correctly. Closing this

**Comment by machi1990** [comment]
> This should already be fixed by #18304 .

This is same issue as https://github.com/quarkusio/quarkus/issues/18335. It is indeed fixed in main as explained in https://github.com/quarkusio/quarkus/issues/18335#issuecomment-872806622, so could be an issue with rolling out the latest websites changes.
