### ISSUE TITLE
Wrong mail content when using quarkus-mail extension

### ISSUE THREAD

**Issue by daniel-alonso-sanchez** [quarkusio/quarkus#18418]
## Describe the bug
When I send a text mail using quarkus 1.13.7.Final, the body shows boundaries and some mail headers inside

```
From: callisto@mine.app
To: user@mine.app
Cc:
Content-Type: multipart/mixed; boundary="=--vertx_mail_1888117144_1625490420441_4"

--=--vertx_mail_1888117144_1625490420441_4
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Sample Mail

--=--vertx_mail_1888117144_1625490420441_4--
```

### Expected behavior
A simple text mail without content type header inside the body

### Actual behavior

Looks like the raw message inside the body content

## To Reproduce

Configuration:

JavaCode

```
Mail mail=new Mail();
mail.addTo("mailaddress@mail.com");
mail.setSubject("a subject");
mail.setText("a body");
mailer.send(mail);
```

1. Just using the code described before

### Configuration

```
quarkus.mailer.from=callisto@mine.app
quarkus.mailer.host=ahost
quarkus.mailer.login=REQUIRED
quarkus.mailer.mock=false
quarkus.mailer.password=apass
quarkus.mailer.port=aport
quarkus.mailer.ssl=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=ausername
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Debian 4.19.160-2
### Output of `java -version`
"11.0.2" 2019-01-15
### Quarkus version or git rev
1.13.7
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven 3.6.3

## Additional context
(Add any other context about the problem here.)

Thanks a lot in advance!

**Comment by cescoffier** [comment]
Do you know if it also happens in 2.0?

**Comment by daniel-alonso-sanchez** [comment]
I don't know. I' will try it tomorrow tomorrow and the and report any advance.
  

  
Thanks a lot!
  

  

  

  
  
  
  
  
>

**Comment by daniel-alonso-sanchez** [comment]
@cescoffier >You were right: it works on quarkus 2.0. It shows the mail content right after migration.

Thanks a lot!

**Comment by victoralc** [comment]
@cescoffier I have the similar issue running quarkus 3.28.3.

I've got the headers data in the email body however I expect only the body subject

```
From: <senderEmail>
To: <recipientEmail>
Cc: 
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Email body here 
```

Details

```
Platform: Microsoft Outlook
Extension: Mailer

#email config
quarkus.mailer.from=emailSender
quarkus.mailer.host=host
quarkus.mailer.port=port
quarkus.mailer.username=username
quarkus.mailer.password=password
quarkus.mailer.mock=false
quarkus.mailer.tls=false
quarkus.mailer.start-tLS=REQUIRED
quarkus.mailer.auth-methods=LOGIN
```
