### ISSUE TITLE
Provide Dev UI for OIDC when `quarkus.oidc.auth-server-url` is enabled which will work for all OIDC providers

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#18427]
## Description

We have discussed this option with Jim Tyrrell. We already have a draft PR where Keycloak specific Dev Services support may be offered with the dedicated extension extending `quarkus-oidc` - however, if only `quarkus-oidc` is loaded then we should offer something similar to https://oidcdebugger.com/ (thanks to @mraible for linking to it)

**Comment by sberyozkin** [comment]
@stuartwdouglas @phillip-kruger Hi, I've already referred to this project a few times but just would like to update on it, I've done some work on my branch and it is looking not bad, tested with `Keycloak` and `Auth0`.

So, when `mvn: quarkus-dev` is running and `quarkus.oidc.auth-server-url` is set, `Dev Services for Keycloak` is disabled.  At this point `quarkus.oidc.auth-server-url` can point to any OIDC provider. In this case `OpenId Connect` card will link to `OIDC Developer Console` - it will act nearly the same as the one we use for the container started with `Dev Services for KC` - it will be still the same standard authorization code flow by default - the only difference is the developer will be working against a provider started out of band, available as SaaS for ex, etc. 
This will be useful for Keycloak but also for projects like the one Jim was experimenting with where he could not easily obtain a test token from `Auth0` - it will work for Google/Azure/Okta etc...

**Comment by stuartwdouglas** [comment]
What is KC specific in the current implementation?

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, 
Yes, there is nothing Keycloak specific in the current Dev UI `provider.html` and related handlers - only a few assumptions are made that `auth-server-url` is calculated by adding a realm value, so the PR I will be trying to finalize soon enough would be mainly about cleaning it a bit and renaming a few vars and handlers. 
With Keycloak Dev Services we already have a container, without them the OIDC dev console code needs to discover a few details like the token and logout URLs.
Some parts of the current Dev UI might not work for all the providers, ex, `Logout` is not supported by Auth0 in a standard way, so it will be disabled, etc... One challenge there is that with `Auth0` you can't test with different user authentications as a result - so supporting alternative grants such as client credentials or password would be useful, but the grant configuration is in the `quarkus.keycloak.devservices` namespace - it might make sense to move the grant config to `quarkus.oidc.devui` namespace to keep the configuration which is not really affecting the containers but Dev UI only.
