### ISSUE TITLE
mutable-jar build breaks docker cache

### ISSUE THREAD

**Issue by cherrydev** [quarkusio/quarkus#18439]
## Describe the bug
When the package type is set to `mutable-jar`, the resulting build-system.properties file changes trivially every build. This causes the "COPY lib" Dockerfile command to generate a duplicate layer. This causes very large layers (>150Mi) to be unnecessarily pushed to a docker repository.

### Expected behavior
The Dockerfile contains the comment:
> \# We make four distinct layers so if there are application changes the library layers can be re-used

This indicates that the docker library layer is intended to be reused if the libraries don't change.

### Actual behavior
In the Quarkus gradle build system, while assembling the app for the `mutable-jar` package type, it collects all passed system properties that start with `quarkus.` and write them out to the file `build-system.properties` in the path `build/quarkus-app/lib/deployment/` using the built-in `java.util.Properties#store()` method. This causes a comment line to be added to the file with the current timestamp. There is no way to turn off this behaviour using this mechanism. This causes the `build-system.properties` file to be different each time and therefore defeating the docker layer cache.

## To Reproduce

https://github.com/cherrydev/quarkus-docker-layer-demo

* `$ ./mvnw package -Dquarkus.package.type=mutable-jar`
* Examine `target/quarkus-app/lib/deployment/built-system.properties` file.
* Note the timestamp on the second line of file
* re-run `$ ./mvnw package -Dquarkus.package.type=mutable-jar`
* Note a different timestamp on the file

### Output of `uname -a` or `ver`
Darwin [redacted] 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.11" 2021-04-20 LTS

### Quarkus version or git rev
2.0.0.FInal
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
## Additional context

This is trivial to fix, though not very clean without re-implementing `java.util.Properties#store()`. In `JarResultBuildStep` in the `quarkus-core-deployment` project, just pass `Properties#store()` an intermediary `StringWriter`, split up the resulting string by lines and output all the lines other than the second one into the file.

In my current project, this is saving 150Mi of duplicated docker layers each time I push them to my repository.

**Comment by geoand** [comment]
Mutable jar is kind of special to be honest. The Dockerfile.jvm` is geared towards the regular `fast-jar`, not the `fast-jar`.
Maybe we should also add an example for this case. 

WDYT @cescoffier @stuartwdouglas ?

**Comment by cherrydev** [comment]
Isn't mutable jar required for live-reload? My particular use-case (using live-reload on a development kubernetes cluster) requires both it and Dockerfile.jvm.

**Comment by geoand** [comment]
Yes, it is required for remote-dev

**Comment by cherrydev** [comment]
Here's an implementation of a utility function that will fix this:
``` java
    private static void storePropertiesWithoutTimestamp(Properties props, OutputStream out, String comment) throws IOException {
        Writer originalOut = new StringWriter();
        props.store(originalOut, comment);
        String originalOutString = originalOut.toString();
        String sep = System.lineSeparator();
        String[] lines = originalOutString.split(sep);
        for (int lineNum = 0; lineNum < lines.length; lineNum++) {
            if (lineNum == 1) continue;
            String nextLine = (lineNum == lines.length - 1) ? lines[lineNum] : lines[lineNum] + sep;
            out.write(nextLine.getBytes(StandardCharsets.ISO_8859_1));
        }
    }
```
8859-1 is the character set used in the Java 1.5-v9 implementation of `Properties#store()` and is also compatible with >v9 versions of `#load()`

**Comment by cescoffier** [comment]
Yes, the issue is that the properties file is updated with a timestamp and so requires rebuilding that layer and all the layers above. The proposed solution would work. Too bad that we can't disable that comment in https://docs.oracle.com/javase/10/docs/api/java/util/Properties.html#store(java.io.Writer,java.lang.String).
