### ISSUE TITLE
StreamingOutput does not work with quarkus-resteasy-reactive-jackson

### ISSUE THREAD

**Issue by pestapever** [quarkusio/quarkus#18444]
The same code working with the extension quarkus-resteasy-jackson doesn't work with the quarkus-resteasy-reactive-jackson. It seems that StreamingOutput is not supported.

Here the code, suitably modified to report only what is of interest.

	@Path("test")
	@GET
	@Produces(MediaType.TEXT_PLAIN)
	public CompletionStage<Response> test() {
		return CompletableFuture.supplyAsync(() -> {
			try {
				final java.nio.file.Path tempDir = Files.createTempDirectory("parentdir");
				File txtFile = Files.createTempFile(tempDir, "test", ".txt").toFile();
				FileUtils.writeStringToFile(txtFile, "my text content", "UTF-8");
				return txtFile;
			} catch (IOException e) {
				throw new CompletionException(e);
			}
		}).thenApplyAsync(txtFile -> Response.ok(new StreamingOutput() {
			@Override
			public void write(OutputStream output) throws IOException, WebApplicationException {
				try (final InputStream is = FileUtils.openInputStream(txtFile)) {
					IOUtils.copy(is, output);
				} finally {
					FileUtils.deleteQuietly(txtFile);
					FileUtils.deleteQuietly(txtFile.getParentFile());
				}
			}
		}).header("Content-Disposition", "attachment;filename=test.txt").build()).handleAsync((r, e) -> {
			if (e != null) {
				throw new CompletionException(e);
			}
			return r;
		});
	}

### Expected behavior
Receive a file with the content: "my text content".

### Actual behavior
I receive a file with content: "org.acme.ReactiveResource$3@68ab0594" (the toString of the object).

### Java
openjdk 11.0.11 2021-04-20 LTS

### Quarkus
2.0.0.Final

### Build tool
Apache Maven 3.8.1

**Comment by geoand** [comment]
`StreamingOutput` is indeed not supported in RESTEasy Reactive and we don't plan to support it as we have a much better way of streaming results, i.e by return a `Multi`
