### ISSUE TITLE
Resteasy Reactive ExceptionMapper for, e.g., ClientErrorException has no active request scope 

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#18451]
When using a ExceptionMapper<ClientErrorException> which is RequestScoped or uses other RequestScoped beans,
following error occurs:

ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] <> (vert.x-eventloop-thread-2) Request failed: javax.enterprise.context.ContextNotActiveException

This is easily reproduced with provoking a 405 on a jaxrs endpoint.

This happens with quarkus-resteasy-reactive and quarkus 2.0.0.Final.

This seems to also happen for WebApplicationException.

This used to work with Quarkus 1.12.0 and normal resteasy.

**Comment by geoand** [comment]
Can you please attach an example application?

**Comment by antonwiens** [comment]
I created a simple project for that:
[reproducer.zip](https://github.com/quarkusio/quarkus/files/6770590/reproducer.zip)
Simply call it with "curl localhost:8080/hello -X POST" and you will see the error.
It also happens if the exception mapper itself is not requestscoped but requestscoped beans are injected and used.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18454 fixes the issue.

Thanks for reporting
