### ISSUE TITLE
Indexed configuration properties not injected by @ConfigProperty

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#18473]
## Describe the bug
When using indexed properties, like described in the [docs](https://quarkus.io/guides/config-reference#indexed-properties), I can only access a collection programatically, but not via injection with `@ConfigProperty`.

## To Reproduce

```java
@ApplicationScoped
public class MyBean {

    @ConfigProperty(name = "complex.list")
    List<String> complexList;

    public void method() {
        List<String> values = ConfigProvider.getConfig().getValues("complex.list", String.class);
        System.out.println(values);
    }
}
```

and properties:

```
complex.list[0]=123
complex.list[1]=234
complex.list[2]=456
```

Fails with:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
  [...]
Caused by: javax.enterprise.inject.spi.DeploymentException: Failed to load config value of type class java.lang.String for: complex.list
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:42)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy_0(ConfigBuildStep$validateConfigProperties1249763973.zig:332)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy(ConfigBuildStep$validateConfigProperties1249763973.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:713)
	... 12 more
Caused by: java.util.NoSuchElementException: SRCFG00014: The config property complex.list is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:257)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:84)
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:39)
	... 15 more
```

However, if I uncomment the `complexList`, the programmatic lookup, like described in the docs works. But, I'd expect the same to work via injection.

I'm using Quarkus `2.0.0.Final` with JDK 16

**Comment by geoand** [comment]
Interesting use case, thanks for reporting!

It seems that here we would need to preserve the type signature when building `ConfigValidationMetadata` and use it to recreate the parameterized type for the List at runtime.
@mkouba I know Arc has a whole bunch of utilities to do similar things, which ones would be useful in this case?

**Comment by mkouba** [comment]
Hm, I don't think we have a util to convert a `org.jboss.jandex.Type` to something that could be passed as a recorder param. But maybe we will not need this. @radcortez how are the indexed properties handled in SR config? Are clients supposed to call  `org.eclipse.microprofile.config.Config.getValues(String, Class<T>)` or?

**Comment by radcortez** [comment]
It should work. The injection of indexed properties is handled by SR `ConfigProducerUtil`. This was added in https://github.com/quarkusio/quarkus/commit/820baaa346c9021987f74af26428de500ccc7019 and we added a bunch of tests for injection points. 

Let me try the reported use case.

**Comment by geoand** [comment]
The problem in this case is not in SR Config. It's in Quarkus only when we perform the validation logic

**Comment by radcortez** [comment]
Ok, it seems I added a https://github.com/quarkusio/quarkus/blob/820baaa346c9021987f74af26428de500ccc7019/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/config/IndexedPropertiesInjectionTest.java#L52 to the test :D

**Comment by radcortez** [comment]
Yes, if we remove the validation logic it works as expected. 

@mkouba what was your idea?

**Comment by mkouba** [comment]
> @mkouba what was your idea?

@radcortez  My idea was that we might store some info about the component type for collection types and handle them specifically in the recorder, which is basically a poor man's variant of passing the full type info as a recorder param.

> My question to @mkouba was which existing pieces should we just to do that?

@geoand And my answer was that I'm not aware of any existing "piece" ;-)

**Comment by geoand** [comment]
Understood, thanks!

Indeed just passing the component type of the collection type would be enough in this case

**Comment by radcortez** [comment]
Ok, who fixes this then? :)

**Comment by geoand** [comment]
I can fix it this week. `2.0.1.Final` is already out, so it doesn't make sense to try and get it in as fast as possible. But I do want it in for when `2.0.2.Final` so I'll take a look soon

**Comment by radcortez** [comment]
Ok. Thanks!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18491 should take care of the issue

**Comment by radcortez** [comment]
@sdaschner BTW, as a workaround, please use `@ConfigMapping` to map any configuration like detailed here: https://quarkus.io/guides/config-mappings.

**Comment by sdaschner** [comment]
Folks, you're awesome :sunglasses: Thanks for the quick updates!

@radcortez Yes, that's what I also tried out, this works
