### ISSUE TITLE
@Timeout seems not to work with @Fallback/@Retry

### ISSUE THREAD

**Issue by magicwerk** [quarkusio/quarkus#18479]
## Describe the bug

A service method is is annotated with 

	@Retry(maxRetries = 1)
	@Fallback(fallbackMethod = "fallbackRandomHero")
	@Timeout(value = 1, unit = ChronoUnit.SECONDS) // Timeout seems to be ignored, delay is 4 seconds

It tries to call another service which is not available.

### Expected behavior

As @Timeout is configured to be 1 second, processing should continue after 1 second, i.e.
- first attemp to call service -> fails after 1 sec
- retry attempt to call service -> fails after 1 sec
- call fallback method
 

### Actual behavior

The value configured in the @Timeout annotation is ignored, it takes 4 seconds until processing continues:

2021-07-07 12:57:12,680 INFO  [io.qua.wor.sup.fig.FightService] (executor-thread-1) findRandomHero start
2021-07-07 12:57:16,791 INFO  [io.qua.wor.sup.fig.FightService] (executor-thread-1) findRandomHero start
2021-07-07 12:57:20,902 INFO  [io.qua.wor.sup.fig.FightService] (executor-thread-1) fallbackRandomHero

The @Timeout is also not handled correctly if @Retry is commented out.

## To Reproduce

[ShowBugQuarkusTimeout.zip](https://github.com/quarkusio/quarkus/files/6776634/ShowBugQuarkusTimeout.zip)

1. unzip
2. mvn test

### Output of `uname -a` or `ver`
Microsoft Windows [Version 10.0.19042.1052]

### Output of `java -version`
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

### Quarkus version or git rev
1.13.7.FINAL

**Comment by magicwerk** [comment]
Can you confirm this to be a bug or point out what I am doing wrong?
Also your bot assigned the env/windows label to this issue, but I assume it occurs irrespective of the operating system.

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback.
