### ISSUE TITLE
Dev Services with a remote Docker environment

### ISSUE THREAD

**Issue by philschaller** [quarkusio/quarkus#18494]
## Description

Since Quarkus 2.0.0.Alpha2 (#16904) Dev Services are restricted to local Docker environments. Any existing remote environments are ignored. Our build system relies on such a remote Docker environment (GitLab Runner with k8s and DinD).

## Workaround

Use an explicit test container with `QuarkusTestResourceLifecycleManager` and disable Dev Services with `quarkus.datasource.devservices=true`.

## Implementation ideas

In addition to the local check also evaluate DOCKER_HOST and probably also DOCKER_TLS_VERIFY, DOCKER_CERT_PATH.

**Comment by stuartwdouglas** [comment]
Did this used to work? I don't think we changed anything in particular here.

**Comment by stuartwdouglas** [comment]
Ah, never mind, just saw the linked issue.

**Comment by stuartwdouglas** [comment]
@philschaller any chance you could build the linked PR and see if it fixes your issue? I don't have a remote docker env to test.

**Comment by philschaller** [comment]
@stuartwdouglas Thanks for the quick fix! It works as expected.
To test it locally you can use the following DinD setup. Insecure, but it works for a quick test:

```
docker container run -i -t --rm --net test-net --privileged --name dind --env DOCKER_TLS_CERTDIR="" docker:20.10.7-dind
```
```
docker container run -i -t --rm --net test-net --mount type=bind,source=$HOME/.m2,destination=/root/.m2 --mount type=bind,source=$(pwd),destination=/opt/project --mount type=bind,source=$HOME/.docker,destination=/root/.docker --workdir=/opt/project --env DOCKER_TLS_VERIFY=0 --env DOCKER_HOST="tcp://dind:2375" maven:3.8.1-openjdk-11 bash
```
