### ISSUE TITLE
No composite lambda handler (http + stream)

### ISSUE THREAD

**Issue by deodorel** [quarkusio/quarkus#18490]
## Describe the bug
Right now there is no way for an application to properly respond to both lambda stream calls (let's say an aws sqs trigger) AND standard http calls. 
If the rest/http module is active you can't have your own lambda handler, and you can only serve http like calls. 
If you write your own lambda handler you need a way to proxy the awsrequest to resteasy/jax-rs format and call the controllers with the proper context, and such a proxy doesn't exists like it exists for spring applications. 

### Expected behavior
Being able to serve both http and stream lambda requests.

### Actual behavior
You can serve either one or the other.

## To Reproduce
1.  build a rest lambda handler
2. try to trigger it with a stream source

**Comment by patriot1burke** [comment]
Not understanding this post.  We do not support both regular lambdas and our Spring MVC/JAX-RS/Servlet + lambda integration in one project.  Create separate projects.  If you want to use quarkus Spring MVC support (or JAX-RS or vertx web or servlet), etc, then use the quarkus-amazon-lambda-http/rest extension:

https://quarkus.io/guides/amazon-lambda-http
