### ISSUE TITLE
2.0 dev mode not reading application properties

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18500]
## Describe the bug
After switching to `2.0`, it looks like dev mode is not reading my `application.yaml` in `config/`.

### Expected behavior
Successful run

### Actual behavior
`NoSuchElementException: SRCFG00014: The config property name is required but it could not be found in any config source`

## To Reproduce

Reproducer: `service1` after swapping the Quarkus version in https://github.com/mweber03/quarkus-test

1. Switch to `2.0.1.Final` in `gradle.properties`
2. `./gradlew service1:quarkusDev`

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
2.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.9

**Comment by laemm-line** [comment]
Same problem here.

application.yaml in src/main/resources
Quarkus version 2.0.2.Final
Gradle version 7.1.1

**Comment by geoand** [comment]
Is this still a problem with Quarkus `2.2.3.Final` or `2.3.0.Final`?

**Comment by mweber03** [comment]
@geoand Yes it still seems to be happening with `2.3.0.Final`. See `service1` in https://github.com/mweber03/quarkus-test

**Comment by mweber03** [comment]
@geoand any updates on this?

**Comment by geoand** [comment]
@radcortez mind taking a look?

Thanks

**Comment by radcortez** [comment]
Sure.
