### ISSUE TITLE
Quarkus 2.0.1.Final Maven Build failing on step HibernateValidatorProcessor#build

### ISSUE THREAD

**Issue by casmeiron** [quarkusio/quarkus#18501]
## Describe the bug

Upgraded to Quarkus 2.0.1 (followed the instructions to migrate) but my project stop working, can't build anymore.

Heres the problem:

ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.1.Final:build (default) on project <>: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.ClassCastException: class org.jboss.jandex.ClassInfo cannot be cast to class org.jboss.jandex.MethodInfo (org.jboss.jandex.ClassInfo and org.jboss.jandex.MethodInfo are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4029265e)
[ERROR] 	at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:56)

I didnt have jandex plugin but added on my maven plugin's list with version 1.1.0 but that didnt make the trick.

I'm using a multi-layout project (with several modules) and in one of them I'm using hibernate-validator dependency with provided scope. This module will be used in others projects that doesn't use quarkus. Would that be the problem?

        <version.hibernate>6.0.0.Alpha8</version.hibernate>
        <version.hibernate.validator>7.0.1.Final</version.hibernate.validator>

        
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${version.hibernate}</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${version.hibernate.validator}</version>
            <scope>provided</scope>
        </dependency>

### Expected behavior
Build like it was with the previous version.

### Actual behavior
Building is failing.

### Output of `java -version`
adopt-openjdk-11 (11.0.11) - INTELLIJ ULTIMATE

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\Users\paulo\.jdks\adopt-openjdk-11.0.11
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Sanne** [comment]
hi @casmeiron , you should really not override the versions of components as provided by Quarkus, we pick the versions carefully for compatibility across them and our extensions. Please try using the versions from the BOM provided by Quarkus?

**Comment by gsmet** [comment]
Please see this entry of the migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#jandex-upgrade . It should solve the issue.

**Comment by geoand** [comment]
Closing as we have not heard back.

If this is still an issue, feel free to comment or reopen
