### ISSUE TITLE
Allow passing more parameters to NativeImageLauncher

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#1850]
The `io.quarkus.test.common.NativeImageLauncher` should allow to pass some more parameters and system properties to the native image.

**Comment by rsvoboda** [comment]
Just for the record: Related to neo4j investigation work - https://github.com/michael-simons/quarkus/commit/efe9b27abd2e3a49ebf29c5eabbb0ee60b962426#commitcomment-33025378

**Comment by klearchos** [comment]
Hi @Sanne ,
is this issue still valid? 
Could you elaborate a bit more towards what parameters and system properties we should be able to pass to the native image.
From the `NativeImageLauncher` I saw that we already have a system properties map that we pass to the `Runtime` as an array.

**Comment by schulzp** [comment]
Hi @Sanne & @klearchos,

I'd like to make `NativeImageLauncher` more configurable, too. Using `mvn -Pnative quarkus:native-image io.fabric8.docker:build` allows to create a native docker image (that is not host OS specific). However, `NativeImageLauncher` tries to launch the `target/*-runner` binary, which is **not working on the host OS** (macos, in my case).

I worked around this using a script, `src/main/docker/run-native`, that launches the docker container instead:
```
#!/bin/sh

docker run --rm -p 8080:8080 <docker-image-name> ./application -Dquarkus.http.host=0.0.0.0 $@
```

That in turn can be passed to `<native.image.path>${project.basedir}/src/main/docker/run-native</native.image.path>`.

So far so good. Now I'd like to link that to my dynamically launched [db container](https://www.testcontainers.org/) that is provided via `@QuarkusTestResource` but there's no way to way to pass a `--link` parameter to the `docker` command based on JVM properties already available in the test-executing JVM.

What would you think about an **SPI approach** just like the one for `io.quarkus.deployment.test.TestScopeSetup` so the `NativeImageLauncher` can easily be replaced?

**Comment by AndreiYu** [comment]
Hi, 
are there any enhancements of how to add additional parameters (except -D parameter options) to NativeImageLauncher executable?

**Comment by stuartwdouglas** [comment]
quarkus.native.additional-build-args should handle this.
