### ISSUE TITLE
FaultToleranceDefinitionException after migrating to Quarkus 2.0

### ISSUE THREAD

**Issue by jjolsvai** [quarkusio/quarkus#18511]
## Describe the bug
After migrating to Quarkus 2.0, @Retry throws the following exception:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: org.eclipse.microprofile.faulttolerance.exceptions.
FaultToleranceDefinitionException: Invalid @Blocking/@NonBlocking on public java.lang.String org.acme.getting.
started.ReactiveGreetingResource.greeting(java.lang.String): must return java.util.concurrent.CompletionStage or io.smallrye.mutiny.Uni
```
Using resteasy-reactive extension, the problem takes place on blocking endpoints with non Uni or CompletionStage return values.
The problem can be mitigated by:
 1. removing @Retry annotation
 2. rolling back to pre Quarkus 2.0 versions
 3. moving from resteasy-reactive to non-reactive resteasy.

### Expected behavior
Not getting FaultToleranceDefinitionException.

### Actual behavior
FaultToleranceDefinitionException thrown.

## To Reproduce
https://github.com/jjolsvai/quarkus-ft-reproducer

1. run the unit test in re-producer

## Additional context
We have a common library with resteasy reactive, but not all the microservices moved to full reactive yet. Hence, there are blocking endpoints.

**Comment by Ladicek** [comment]
I've created https://github.com/smallrye/smallrye-fault-tolerance/issues/463 to track this in SmallRye Fault Tolerance. I've also submitted a fix, which will be present in SmallRye Fault Tolerance 5.2.1 (to be released in a matter of minutes).
