### ISSUE TITLE
quarkus-smallrye-graphql and quarkus-neo4j don't work together in Quarkus 2.0.

### ISSUE THREAD

**Issue by michael-simons** [quarkusio/quarkus#18516]
Given a GraphQL API like this:

```
import javax.inject.Inject;

import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Name;
import org.eclipse.microprofile.graphql.Query;
import org.neo4j.driver.Driver;

@GraphQLApi
public class People {

	@Inject Driver driver;

	@Query("people")
	public CompletableFuture<List<Person>> getPeople(@Name("nameFilter") String nameFilter) {
		System.out.println(driver == null);
		return CompletableFuture.completedFuture(List.of());
	}
}
```

the injected driver will always be literal `null`. Used to work in 1.13.x, but not in 2.0.
I wonder if this is due to the `Neo4jDriverProducer` producing the driver as `Singleton` and the GraphQL things bootstrapping rather early.

**Comment by michael-simons** [comment]
Full project: https://github.com/michael-simons/neo4j-aura-quarkus-graphql which I cannot upgrade to 2.0 at the moment.

**Comment by phillip-kruger** [comment]
Out of interest, what happens if you add `@ApplicationScope` to the class (with the `@GraphQLApi`) ?

**Comment by phillip-kruger** [comment]
Yea, that actually fix it . This is a bug. As a workaround you can use this (https://github.com/michael-simons/neo4j-aura-quarkus-graphql/pull/1). I will look at this to fix the `GraphQLApi`. Thanks !

**Comment by michael-simons** [comment]
Oh wow, thanks for your PR! I can confirm that the workaround works.

**Comment by phillip-kruger** [comment]
Keeping this open until the bug is fixed. Thanks :)

**Comment by mkouba** [comment]
> I wonder if this is due to the `Neo4jDriverProducer` producing the driver as `Singleton` and the GraphQL things bootstrapping rather early.

So this is a good point!

@michael-simons It's actually not the scope that is important here but the fact that the `Neo4jDriverProducer#initialize()` is probably called after the `@GraphQLApi` bean is created. `@ApplicationScope` implies lazy initialization, i.e. the bean instance is created the first time the bean is called. 

@phillip-kruger Has the init logic changed in 2.0?

**Comment by mkouba** [comment]
BTW We should try to replace the `Neo4jDriverProducer` with a synthetic bean and get rid of the _initialize a volatile field at runtime_ pattern. I'll try to prepare a PR.

**Comment by phillip-kruger** [comment]
No the init logic has been the same a.f.a.i.k

**Comment by phillip-kruger** [comment]
Maybe we can create an example that use `Singleton` without Neo4J ? To confirm ?

**Comment by mkouba** [comment]
> Maybe we can create an example that use `Singleton` without Neo4J ? To confirm ?

Maybe. I'll take a look tomorrow.

FYI https://github.com/quarkusio/quarkus/pull/18530
