### ISSUE TITLE
quarkus-config-yaml extension erase content of src/main/resources folder

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18527]
## Describe the bug
When generating project with `quarkus-config-yaml` extension -
the `src/main/resources` directory is missing `/META-INF` folder which contains `index.html` file.

### Expected behavior
`/META-INF` folder and it's files are not missing

### Actual behavior
`/META-INF` folder is missing

Probably related to this effort https://github.com/quarkusio/quarkus/issues/13511

## To Reproduce

```
mvn io.quarkus:quarkus-maven-plugin:2.0.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello" -Dextensions=quarkus-config-yaml
```
And see /resources directory contains only **.yml** file

**Comment by geoand** [comment]
cc @ia3andy

**Comment by ia3andy** [comment]
Hello @kshpak this is expected. 

You only selected `quarkus-config-yaml` which gives you a config object plus it's config in yaml. If you want the html and the REST endpoint, you need to add the `resteasy` extension.

Currently if you don't pick any extension, you have `resteasy` by default but this is a special case to make sure you get some content to start with.

**Comment by ia3andy** [comment]
```bash
mvn io.quarkus:quarkus-maven-plugin:2.0.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello" -Dextensions=quarkus-config-yaml,resteasy
```
