### ISSUE TITLE
Utf-8 graphql issue with non ascii chars

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#18521]
## Describe the bug
Utf-8 chars like german umlauts are not usable.

### Expected behavior
Special chars should work like normal chars.

### Actual behavior
Special chars like german ä, ö, ü are replaced by things like Ã¼

## To Reproduce

Or attach an archive containing the reproducer to the issue.
[code-with-quarkus_graphql_utf8.zip](https://github.com/quarkusio/quarkus/files/6783786/code-with-quarkus_graphql_utf8.zip)

1. Send the example query via dev ui or intellij http request.
2. The response does contain destroyed umlauts.

```
Example Query:

query test{
  hello(string: "München")
}

Example response:

{
  "data": {
    "hello": "MÃ¼nchen"
  }
}

Example Intellij http request:

POST http://localhost:8080/graphql
Content-Type: application/json

{"query":"query test{\n  hello(string: \"München\")\n}\n","variables":null,"operationName":"test"}


### Output of `uname -a` or `ver`

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
### Quarkus version or git rev
2.0.1.Final

Problem could be here:

io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler#readBody

return new String(bytes);

**Comment by phillip-kruger** [comment]
Thanks ! I'll have a look !

**Comment by phillip-kruger** [comment]
@robp94 - I can not recreate this.

On Graphql-ui:

![image](https://user-images.githubusercontent.com/6836179/124910139-895fd600-dfeb-11eb-9259-e0e01e6ff4c7.png)

In browser extension:

![image](https://user-images.githubusercontent.com/6836179/124910229-a7c5d180-dfeb-11eb-97fe-83db27042d88.png)

In curl:

![image](https://user-images.githubusercontent.com/6836179/124910317-c0ce8280-dfeb-11eb-8f23-6498108821e7.png)

This does not mean this is not a bug, I am just trying to recreate it so that I can fix it. It might be that my OS is set up with UTF-8

output of `echo $LANG` is `en_ZA.UTF-8`

Anything more you can share on your environment ?

**Comment by robp94** [comment]
Sure, German Windows 10. Maybe the problem is the platform encoding?

uname -a
MSYS_NT-10.0 2.8.0(0.310/5/3) 2017-04-02 13:38 x86_64 Msys

mvnw --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Users\\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by robp94** [comment]
Starting like mvnw quarkus:dev -Dfile.encoding=UTF-8 solves the problem.

**Comment by phillip-kruger** [comment]
Let me see if I can recreate the problem by doing 

```
mvnw quarkus:dev -Dfile.encoding=Cp1252
```

**Comment by phillip-kruger** [comment]
Although I think we should keep the encoding to be a OS platform problem ?

**Comment by robp94** [comment]
Hm not sure, until this gets resolved https://openjdk.java.net/jeps/400 I usually call things like this:
`new String(bytes, DefaultCharset.UTF_8)`

**Comment by phillip-kruger** [comment]
But what if the user wants to use another Charset ? How would they do that ?

**Comment by phillip-kruger** [comment]
Doing `mvnw quarkus:dev -Dfile.encoding=Cp1252` recreate the problem.

**Comment by phillip-kruger** [comment]
I wonder if we can see what happens in REST ?

**Comment by robp94** [comment]
> 
> 
> But what if the user wants to use another Charset ? How would they do that ?

Or maybe via a property.

**Comment by phillip-kruger** [comment]
`file.encoding` is already a property, no ?

**Comment by robp94** [comment]
Yeah, but like in the application.properties or maybe in maven itself. Not sure if there is something like that.

**Comment by phillip-kruger** [comment]
Have you tried `file.encoding` in application.properties ?

**Comment by sgift** [comment]
Quick note regarding file.encoding from here https://openjdk.java.net/jeps/400: "Sometimes developers attempt to set the default charset via the system property file.encoding, but this has never been supported and may not actually work, especially if modified after the Java virtual machine is initialized."

So, this is unfortunately, not really a solution even if it works right now.

**Comment by robp94** [comment]
In the quarkus properties i only find an option for native
`
quarkus.native.file-encoding

Defines the file encoding as in -Dfile.encoding=…​ Native image runtime uses the host’s (i.e. build time) value of file.encoding system property. We intentionally default this to UTF-8 to avoid platform specific defaults to be picked up which can then result in inconsistent behavior in the generated native executable.
`

**Comment by robp94** [comment]
> 
> 
> Have you tried `file.encoding` in application.properties ?

Does not work for me.
`file.encoding=UTF-8`

**Comment by phillip-kruger** [comment]
OK, I think the way to solve this then is to add a property for encoding, with a default of UTF-8. I'll prepare a PR

**Comment by robp94** [comment]
Ok thx.

**Comment by phillip-kruger** [comment]
@robp94 - Can you please test something on your environment (with your reproducer)

Add this to application.properties:

```
quarkus.smallrye-graphql.http.get.enabled=true
```

Then do this in the Browser (GET):

```
http://localhost:8080/graphql?query=query%20test%7B%0A%20%20%20%20hello(string%3A%20%22M%C3%BCnchen%22)%0A%7D
```

Let me know what you get

**Comment by robp94** [comment]
<html><body>
<div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="JSON durchsuchen"></div><div class="panelContent">

  |  
-- | --
data |  
hello | "München"

</div>
</body>
</html>

**Comment by phillip-kruger** [comment]
Awesome, thanks ! Found the issue, fixing it now.

**Comment by phillip-kruger** [comment]
@robp94 @sgift - Thanks for this bug report. There is now an open PR that should fix this. The default encoding is UTF-8 all over, and can be changed with an `Accept` header. In you case, no header will be needed, this should fix your example. Cheers
