### ISSUE TITLE
Qute Templates not working when resources are in a submodule

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#18525]
If you have a qute template file in a submodule resource folder, the project wont build.
It seems to expect the qute template files in the main project for the quarkus build.
Is this intended? 

I added this sample project:

[sample.zip](https://github.com/quarkusio/quarkus/files/6784289/sample.zip)

**Comment by mkouba** [comment]
> Is this intended?

Yes, this is not supported ATM. Currently, there can be only one templates root dir in the app module.
