### ISSUE TITLE
Support one time OIDC access tokens 

### ISSUE THREAD

**Issue by nhat-vo** [quarkusio/quarkus#18536]
## Description

I would like to implement a Forgot password API as below:

Users send a request with their emails to `/forgot-password`. They will then receive an email with a token (embedded within a link to provide the new password). The token and the new password will then be sent to another endpoint `/reset-password`, where the user can reset their password. I want the token to only authenticate the user for `/reset-password`, like an [action token](blog.please-open.it/action-token/). 

Here, I tried to implement the flow with this `ActionToken`, but when I `serialize` (as in the [link](blog.please-open.it/action-token/) ), I could not find any way to initiate or inject the `session`.

**So my question is what is the best way to initialize the Keycloak session?**

Thanks :)

------

Below is a few information about my application:

- The application is protected by `quarkus-oidc`, where Keycloak (10.0) is the provider.
- The Keycloak server is hosted on `localhost:8081/auth`, and the API interacts with the server by either `KeycloakBuilder.builder()` (which returns a `Keycloak` object) or by HTTP requests to the server URL. 
- The public endpoints are `login`, `register`, `logout`, `forgot-password`, and `reset-password`.
- Some additional settings to `quarkus.oidc`:
```
quarkus.oidc.discovery-enabled       = false
quarkus.oidc.introspection-path      = /protocol/openid-connect/token/introspect
quarkus.oidc.authentication.verify-access-token=true
quarkus.oidc.roles.source=accesstoken
```

```kotlin
fun forgotPassword(email: String, uriInfo: UriInfo) {
        val user = authService.keycloakClient.getUserByEmail(email)
        val session = DefaultKeycloakSessionFactory().create()
        LOG.info("Session created" + session, LogTypeEnum.PROCESS)
        LOG.info("Realm: " + session.context.realm, LogTypeEnum.PROCESS)
        val token = ResetPasswordActionToken(user.id)
            .serialize(
                session,
                RealmModel(),
                uriInfo
            )
        LOG.info("Token created", LogTypeEnum.PROCESS)
        val body = "TO_BE_DEFINED \n$token"
        val to = SendSmtpEmailTo()
            .name(user.firstName ?: "" + user.lastName ?: "")
            .email(email)
        val content = SendSmtpEmail()
            .sender(mailer.sender)
            .to(listOf(to))
            .subject("Forgot password request")
            .textContent(body)
        mailer.send(content)
```

```kotlin
import org.keycloak.authentication.actiontoken.DefaultActionToken

class ResetPasswordActionToken(userId: String) :
    DefaultActionToken(userId, TOKEN_TYPE, EXPIRATION, null) {
    companion object {
        const val TOKEN_TYPE = "RESET_PASSWORD"
        const val EXPIRATION = 900
    }
```

**Comment by sberyozkin** [comment]
@OnePlusOneIsTen Hi, I've looked at your code example, and it appears that while this code can work as is in Quarkus, one can 1) acquite a one time token from Keycloak and then use JAX-RS API directly to save what is needed as a cookie bound to a specific path/domain, in case of JAX-RS you'd use `NewCookie` and set it on Response, or if it is stateful, then you can inject `RoutingContext` which has a `Session` property. I'm not sure what kind of extra support Quarkus can offer in this case
What do you think ?

**Comment by OnePlusOneIsTen** [comment]
@sberyozkin Hi, thank you for your answer. I don't think the `RoutingContext` exists, as when I tried to inject with the code:

```kotlin
    @POST
    @Path("forgot-password")
    fun forgotPassword(
        @QueryParam("email") email: String,
        @Context uriInfo: UriInfo,
        @Context ctx: RoutingContext
    )
```

 it gives the message:

 ```Unable to find contextual data of type: io.vertx.ext.web.RoutingContext```

Also, I'm not sure if the `Session` property of `RoutingContext` is of type `KeycloakSession` or not, as I will also be using the `KeycloakSession` to obtain the `RealmModel` (for the third argument of `serialize()`.

**Comment by sberyozkin** [comment]
@OnePlusOneIsTen - it has to be injected as a field, using `@Inject`:
```
@Inject
RoutingContext ctx;
``` 
> Also, I'm not sure if the Session property of RoutingContext is of type KeycloakSession or not, as I will also be using the KeycloakSession to obtain the RealmModel (for the third argument of serialize().

My understanding these are just the way to set the underlying HTTP session properties via this API - try to figure out what actually happens with `serialize` is done - then translate that into `RoutingContext.Sesssion` calls

**Comment by OnePlusOneIsTen** [comment]
I managed to add the `RoutingContext` and implement the `serialize` method to sign the token myself. Thank you very much for your help :)
