### ISSUE TITLE
@RegisterProvider required for resteasy interfaces

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#18560]
## Description
When a filter is defined with @Provider is should be applied to the resteasy interface.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/quarkus-rest-client-reactive.20need.20to.20use.20.40RegisterProvider/near/245419083

### Expected behavior
The following code should be enough to apply a filter
@Provider  
public class LogClientResponseFilter implements ClientResponseFilter 
Currently the following must also be done:
It also has to be registered to the interface:
@RegisterProvider(LogClientResponseFilter.class)

### Actual behavior
The filter is not applied to the resteasy interface

## To Reproduce

[rest-client-reactive-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/6790488/rest-client-reactive-quickstart.tar.gz)

1. run test, check output
2. remove @RegisterProvider and verify that the output is missing

## Environment (please complete the following information):

uname -a
Linux rhclient444.xxx 3.10.0-1160.6.1.el7.x86_64 #1 SMP Wed Oct 21 13:44:38 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
Quarkus version: 1.11.1.Final
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 1.8.0_192, vendor: Oracle Corporation, runtime: /home/xxx/opt/jdk-8u192_b12/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.6.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by michalszynkiewicz** [comment]
So, JAX-RS says this:
```
A client filter is a class that implements ClientRequestFilter or ClientResponseFilter or both. A
container filter is a class that implements ContainerRequestFilter or ContainerResponseFilter,
or both. An entity interceptor is a class that implements ReaderInterceptor or WriterInterceptor,
or both. Filters and entity interceptors are providers and, as such, may be annotated with @Provider for
automatic discovery.
```

So I think it should be applied to clients. @ronsigal @jamezp what do you guys think? How does it work in pure RESTEasy?

**Comment by lthasle** [comment]
It applies only to the Container(reactive) now. It would be nice if also would be applied to the client, to be consistent

**Comment by jamezp** [comment]
@maciejwalkowiak They are discovered if the client runs in the container. Outside the container I don't think things are auto-discovered.

**Comment by lthasle** [comment]
The ClientRequestFilter or ClientResponseFilter are also discovered in the resteasy classic(non reactive) case
