### ISSUE TITLE
Custom OpenTelemetry SpanExporter breaks Jaeger exporter

### ISSUE THREAD

**Issue by hacst** [quarkusio/quarkus#18575]
## Describe the bug
When using the quarkus-opentelemetry extension as well as the quarkus-opentelemetry-exporter-jaeger extension adding a custom `SpanExporter` makes the jaeger exporter stop working.

### Expected behavior
Both exporters are able to export spans and no warning occurs.

### Actual behavior
The jaeger exporter stops working and the following warning is output to console on startup:
```
2021-07-09 17:49:12,944 WARN  [io.qua.ope.exp.jae.run.LateBoundBatchSpanProcessor] (Quarkus Main Thread) No BatchSpanProcessor delegate specified, no action taken.
```
The custom exporter seems to be working though.

## To Reproduce
Adding to following class to a code-with-quarkus with both extensions and previously working tracing to a local jaeger reproduces the behavior:
```java
package org.acme;

import io.opentelemetry.sdk.common.CompletableResultCode;
import io.opentelemetry.sdk.trace.data.SpanData;
import io.opentelemetry.sdk.trace.export.SpanExporter;
import io.quarkus.arc.Unremovable;

import javax.enterprise.context.ApplicationScoped;
import java.util.Collection;

@Unremovable
@ApplicationScoped
public class CustomExporter implements SpanExporter {
    @Override
    public CompletableResultCode export(Collection<SpanData> spans) {
        System.out.println("CustomExporter.export");
        return CompletableResultCode.ofSuccess();
    }

    @Override
    public CompletableResultCode flush() {
        return CompletableResultCode.ofSuccess();
    }

    @Override
    public CompletableResultCode shutdown() {
        return CompletableResultCode.ofSuccess();
    }
}
```

### Quarkus version or git rev
2.0.1.Final

**Comment by hacst** [comment]
Some further analysis: Adding the custom exporter adds an additional `SimpleSpanProcessor` for each exporter:
https://github.com/quarkusio/quarkus/blob/ec2c72d7f1c5990be14ebbea140afb0ddc90d196/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java#L79

Due to that OTEL creates a `MultiSpanProcessor`
https://github.com/open-telemetry/opentelemetry-java/blob/ae4bb364cdf6cdae583f07209ce514674c98fdbd/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java#L45-L48
during construction that type calls `isStartRequired` on the processors requiring the delegate. This violates the assumption that creation of the delegate can be omitted during static initialization.

`isStartRequired` returns false after emitting the warning. I assume this prevents the `MultiSpanProcessor` from starting the jaeger exporter later on which would explain it not working.

**Comment by kenfinnigan** [comment]
Thanks @hacst, I'm taking a look today
