### ISSUE TITLE
Allow Jackson configuration through properties

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#18572]
## Description

It would be nice to be able to configure the Jackson `ObjectMapper` through properties rather than having to create a class extending `ObjectMapperCustomizer`.

Rather than having to constantly map Quarkus-specific properties to Jackson properties, just allow free-form mapping within the properties that would "flow-through" to the underlying Jackson enum properties. Something like this:

| **Enum** | **Property** | **Values** |
| :----- | :-------- | :------ |
| `com.fasterxml.jackson.databind.DeserializationFeature` | `quarkus.jackson.deserialization.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.databind.SerializationFeature` | `quarkus.jackson.serialization.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.databind.MapperFeature` | `quarkus.jackson.mapper.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.core.JsonGenerator.Feature` | `quarkus.jackson.generator.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.core.JsonParser.Feature` | `quarkus.jackson.parser.<feature_name>` | `true`, `false` |
| `com.fasterxml.jackson.annotation.JsonInclude.Include` | `quarkus.jackson.default-property-inclusion` | `always`, `non_null`, `non_absent`, `non_default`, `non_empty` |

This way, if/as new "things" are added to the enums, there isn't any work that needs to be done in the extension. As long as `<feature_name>` aligns with the enum constant, it would just map. 

I would envision these properties would be fixed at build time and not overridable at runtime. We'd have to decide what to do in the case that an application provides an `ObjectMapperCustomizer` and there are properties set. I would think that we would union the properties and what is defined in the `ObjectMapperCustomizer`. We'd have to figure out "who wins" in the situation where a property is set to one value and the customizer sets a different value for the same enum property. Don't property values specified in `application.properties`/`application.yml` always "win" over whats in the code?

   > Just a side note, I did get this idea from Spring and the [Spring documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.spring-mvc.customize-jackson-objectmapper) which allows for this. Its a very convenient feature to have that eliminates the need to write code.

**Comment by geoand** [comment]
I think this is a nice enhancement.

**Comment by geoand** [comment]
I'll do this after https://github.com/quarkusio/quarkus/pull/20468 is in

**Comment by geoand** [comment]
There is one thing I don't like however about the proposal: It is not conductive to auto-completion by IDEs because the feature names are simply strings.

**Comment by edeandrea** [comment]
I think the downside though is anytime there is a new config property in Jackson then Quarkus needs to make a change and "catch up", whereas them just being Strings allows users to use new features as they become available without Quarkus needing to make any changes.

That being said I don't know the internal implementation, so it may not be a big deal.

**Comment by edeandrea** [comment]
Do you _really_ want to have to remember to update Quarkus config/tests/etc _every time_ Jackson makes an update? Thats the real question.

Me personally I would prefer convention where I don't have to touch framework code if a library that the framework uses makes a change. But that's me and I'm not implementing this :)

Just my $0.02.

**Comment by geoand** [comment]
We always have to think about developer joy though as well 😉

**Comment by edeandrea** [comment]
As a developer I would have much joy if new things in Jackson just worked without me having to file a ticket to have some property implemented/recognized by Quarkus :D

**Comment by edeandrea** [comment]
Hey @geoand gentle ping on this...thoughts?

I'm up for trying out a PR for this if you can point me to where I might get started?

**Comment by geoand** [comment]
[This](https://github.com/quarkusio/quarkus/blob/main/extensions/jackson/runtime/src/main/java/io/quarkus/jackson/runtime/JacksonBuildTimeConfig.java) and [this](https://github.com/quarkusio/quarkus/blob/main/extensions/jackson/runtime/src/main/java/io/quarkus/jackson/runtime/ObjectMapperProducer.java) should be a good start.

**Comment by edeandrea** [comment]
I'll throw a draft PR together shortly for your to take a look at

**Comment by geoand** [comment]
Cool :)

**Comment by edeandrea** [comment]
Ahh seems I can't do this in `JacksonBuildTimeConfig`?

```java
   /**
     * Enable/disable Jackson serialization ({@code com.fasterxml.jackson.databind.SerializationFeature}) features.
     */
    @ConfigItem
    public Map<SerializationFeature, Boolean> serialization = new EnumMap<>(SerializationFeature.class);

    /**
     * Enable/disable Jackson deserialization ({@code com.fasterxml.jackson.databind.DeserializationFeature}) features.
     */
    @ConfigItem
    public Map<DeserializationFeature, Boolean> deserialization = new EnumMap<>(DeserializationFeature.class);

    /**
     * Enable/disable Jackson general purpose mapping ({@code com.fasterxml.jackson.databind.MapperFeature}) features.
     */
    @ConfigItem
    public Map<MapperFeature, Boolean> mapper = new EnumMap<>(MapperFeature.class);

    /**
     * Enable/disable Jackson parser ({@code com.fasterxml.jackson.core.JsonParser.Feature}) features.
     */
    @ConfigItem
    public Map<JsonParser.Feature, Boolean> parser = new EnumMap<>(JsonParser.Feature.class);

    /**
     * Enable/disable Jackson generator ({@code com.fasterxml.jackson.core.JsonGenerator.Feature}) features.
     */
    @ConfigItem
    public Map<JsonGenerator.Feature, Boolean> generator = new EnumMap<>(JsonGenerator.Feature.class);
```

**Comment by geoand** [comment]
You mean have an enum as the key of the map? If so, then correct, you can't

**Comment by edeandrea** [comment]
Yes thats what I mean. I would think this would be a common thing no? Couldn't we modify `BuildTimeConfigurationReader.processValue` where it does

```java
if (keyClass != String.class) {
  throw reportError(field, "Map key types other than String are not yet supported");
}
```

?

**Comment by geoand** [comment]
Yes, it can be done

**Comment by edeandrea** [comment]
take you what? an hour or so? :D

**Comment by geoand** [comment]
My guess is that it's a one liner 😜.

I'll have a look tomorrow

**Comment by edeandrea** [comment]
I changed that `if` statement to

```java
 if ((keyClass != String.class) && !keyClass.isEnum()) {
  throw reportError(field, "Map key types other than String and Enum are not yet supported");
  }
```

but no idea if that fixes it :) I'll play with it and see if my tests work :)

**Comment by geoand** [comment]
😎

**Comment by edeandrea** [comment]
Unfortunately that in itself doesn't seem to do it. Seems that the config class (`JacksonBuildTimeConfig` in this case) is instantiated programmatically via reflection, so even if I set a default value on the `Map` field (like `public Map<SerializationFeature, Boolean> serialization = new EnumMap<>(SerializationFeature.class);`) it doesn't take

The `BuildTimeConfigurationReader.readConfigGroup`  method blindly creates a `TreeMap` as a placeholder for values (see https://github.com/quarkusio/quarkus/blob/60426def0c6bccd76907aab4cd4893f1bf37f9ae/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L691-L698).

I'm not sure I understand enough of how the config parsing works to be able to take this on. Do you want me to create a separate ticket for this?

**Comment by geoand** [comment]
Sure yeah

**Comment by edeandrea** [comment]
I created ##24214

**Comment by edeandrea** [comment]
> It might just be me but I don't see how it is more practical than a customizer given you don't have any completion so you will somehow have to go in the doc to find the right name, whereas you can just use completion with a customizer.

I'm not sure what you mean by `customizer`. Can you provide an example? I'm not at all familiar with this part of the codebase.

**Comment by geoand** [comment]
@gsmet means an ObjectMapperCustomizer.

**Comment by edeandrea** [comment]
Yeah I was just in the middle of writing that `ObjectMapperCustomizer` is what I thought it was. Me personally I'd prefer to have less code and more config - being able to supply configuration once in my config and then leave it be. Just my opinion.
