### ISSUE TITLE
CompletionException: Session is currently connecting to database with injected Mutiny.Session (HibernateReactive)

### ISSUE THREAD

**Issue by Cavvar** [quarkusio/quarkus#18585]
## Describe the bug
When using Quarkus with Hibernate Reactive a CompletionException and IllegalStateException is thrown when combining two entities retrieved through an injected `Mutiny.Session`.

### Expected behavior
Should not throw an exception

### Actual behavior
Throws an CompletionException:
```
2021-07-09 21:19:18,583 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-8) failed to execute statement [select fruit0_.fruit_id as fruit_id1_1_0_, fruit0_.name as name2_1_0_ from fruits fruit0_ where fruit0_.fruit_id=$1]
2021-07-09 21:19:18,586 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-8) could not load an entity: [org.acme.Fruit#1]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: session is currently connecting to database
```

## To Reproduce

Bug can be reproduced in the following project: https://github.com/Cavvar/Quarkus-HibernateReactive-Bug

The essential code is:
```java
package org.acme;

import io.smallrye.mutiny.Uni;
import org.hibernate.reactive.mutiny.Mutiny;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

@ApplicationScoped
public class FoodsService {
    @Inject
    Mutiny.Session mutinySession;

    public Uni<Food> getFoods(){
        return Uni
                .combine()
                .all()
                .unis(mutinySession.find(Vegetable.class, 1), mutinySession.find(Fruit.class, 1))
                .asTuple()
                .map(fruitVegetable -> new Food(fruitVegetable.getItem1(), fruitVegetable.getItem2()));
    }
}
```

### Quarkus version or git rev
2.0.1.Final

**Comment by gwenneg** [comment]
Hi @Cavvar.

`Uni.combine().all().unis(...)` _may_ execute the Unis concurrently while the Hibernate Reactive session [must not be shared](https://hibernate.org/reactive/documentation/1.0/reference/html_single/#_obtaining_a_reactive_session) between different concurrent reactive streams. You need to adapt your code to prevent concurrent executions.

**Comment by Cavvar** [comment]
Hi @gwenneg,

thanks for the info. I wasn't sure at first. I'll close the issue.
