### ISSUE TITLE
Emitted OpenAPI Spec files can become corrupt when the API surface shrinks

### ISSUE THREAD

**Issue by misterjoshua** [quarkusio/quarkus#18586]
## Describe the bug
When I use `quarkus.smallrye-openapi.store-schema-directory` to emit my API's OpenAPI specs as files, the emitted `openapi.json` and `openapi.yaml` files can become corrupt if the API surface shrinks.

I believe the problem is [this `Files.write`](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L428). When extant OpenAPI specs are overwritten with smaller files, the bytes at the end of the file are not removed. To prevent this problem, I think that when we're writing the files, we should add `StandardOpenOption.TRUNCATE_EXISTING` to the `Files.write`.

### Expected behavior
The `openapi.json` and `openapi.yaml` files should be truncated when written so that the contents of the files are exactly the new OpenAPI specs without leftovers from the file's previous contents.

### Actual behavior
The new spec is written to `openapi.json` and `openapi.yaml` files, but the bytes at the end of the file stay, adding some corruption to the spec files.

## To Reproduce
Here's a reproducer: https://github.com/misterjoshua/quarkus-openapi-bug

1. Build the project with `mvn clean package` to make sure the files in `src/main/openapi` are available.
2. Comment out `com.example.AResource` so that the API surface shrinks.
3. Re-build the project with `mvn clean package`
4. The files in `src/main/openapi` are corrupt now.

When you look in the generated openapi files, you'll see that they're corrupt.

### Configuration
```properties
quarkus.smallrye-openapi.store-schema-directory=src/main/openapi
```

### Screenshots
**openapi.json**
![image](https://user-images.githubusercontent.com/644092/125146287-446a9b00-e0e2-11eb-88b8-75b6b502cf65.png)

**openapi.yaml**
![image](https://user-images.githubusercontent.com/644092/125146291-51878a00-e0e2-11eb-9750-9fe71785a1f4.png)

### Output of `uname -a` or `ver`
Windows 10 21H1

### Output of `java -version`
```
PS E:\p\openapi-bug-reproducer> java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

### GraalVM version (if different from Java)
I think it's 21.0.0

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Users\joshk\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1
Java version: 11.0.10, vendor: GraalVM Community, runtime: C:\Program Files\GraalVM\graalvm-ce-java11-21.0.0
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

## Additional context
Let me know if you need any more information. Thanks for looking at this! 🚀

**Comment by phillip-kruger** [comment]
Thanks @misterjoshua - fix applied and working as you suggested (https://github.com/quarkusio/quarkus/pull/18591)

As a workaround you can configure your build to clear that folder (on mvn clean).
See https://maven.apache.org/plugins/maven-clean-plugin/examples/delete_additional_files.html

**Comment by misterjoshua** [comment]
Thank you! :)
