### ISSUE TITLE
Dev mode console handler does not get installed if there are no tests (picocli app)

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#18594]
## Describe the bug
When running my (Pico)CLI app (https://github.com/gunnarmorling/kc-cli) in Dev mode, it doesn't show me the options for restarting that CLI app, editing the passed parameters, etc. It just hangs there:

```
mvn compile quarkus:dev  -Dquarkus.args='info'

...

Quarkus application exited with code 0
```

### Expected behavior
There should be the line telling me about the dev mode options like restarting, etc.

### Actual behavior
That line isn't displayed.

## To Reproduce

Clone the project and run it in dev mode.

### Configuration
n.a.

### Screenshots
n.a.

### Output of `uname -a` or `ver`
Darwin Kernel Version 19.6.0

### Output of `java -version`
build 17-ea+23-2064

### GraalVM version (if different from Java)
21.1.0

### Quarkus version or git rev
2.0.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven 3.8.1

## Additional context
n.a.

**Comment by stuartwdouglas** [comment]
This is a known problem, where the console handler does not get installed if there are no tests. 

For now you can work around it by adding a test.

**Comment by famod** [comment]
Looks very similar to #18352

**Comment by gunnarmorling** [comment]
Thx, can confirm adding a test brings back the dev mode input interface.
