### ISSUE TITLE
Extension quarkus-vertx-graphql interferes with extension quarkus-resteasy-multipart

### ISSUE THREAD

**Issue by aaronanderson** [quarkusio/quarkus#18598]
## Describe the bug
After upgrading to Quarks 2.0 I discovered an issue with my application that uses the extensions quarkus-vertx-graphql and quarkus-resteasy-multipart. While running my application in devmode if I perform a multipart form data post to a JAX-RS endpoint none of the parts are received by the JAX-RS endpoint. If i remove the quarkus-vertx-graphql dependency from my application it works fine. The application also works fine in production mode when I directly run the quarkus-run.jar.

### Expected behavior
The multipart form parameter parts are available regardless of what mode the Quarkus application is run in or if the quarkus-vertx-graphql extensions is included in the application. 

### Actual behavior
The request reaches the endpoint but no parts are available.

## To Reproduce

Reproducer: https://github.com/aaronanderson/quarkus-multipart

I experimented with the 2.0.1.Final version of the VertxGraphqlProcessor class and if I comment out this line and build the extension it fixes the issue:

https://github.com/quarkusio/quarkus/blob/9e0736c5091bc34791ceffe6b760f111af0b63bf/extensions/vertx-graphql/deployment/src/main/java/io/quarkus/vertx/graphql/deployment/VertxGraphqlProcessor.java#L84

I am not sure what the RequireBodyHandlerBuildItem does or why it would affect the multipart extension. I did confirm it is required for the vertx-graphql extension to work.

1. Check out the reproducer build and run it. 
2. Remove the quarkus-vertx-graphql or modify the VertxGraphqlProcessor class as mentioned above to successfully run the test.

### Output of `java -version`
```
java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Corretto-16.0.1.9.1 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Corretto-16.0.1.9.1 (build 16.0.1+9, mixed mode, sharing)
```

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn -version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/xxxx/apache-maven-3.8.1
Java version: 16.0.1, vendor: Amazon.com Inc., runtime: /home/xxxx/jdk-16
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-051300-generic", arch: "amd64", family: "unix"

## Additional context
(Add any other context about the problem here.)

**Comment by jmartisk** [comment]
The problem here is that resteasy-multipart is incompatible with globally active body handler, which unfortunately, the vertx-graphql extension uses. I submitted https://github.com/quarkusio/quarkus/pull/18600 which fixes this the same way as we fixed it for smallrye-graphql

**Comment by aaronanderson** [comment]
I updated to 2.0.2.Final and everything is working now. Thanks!

```
 public void setupRouter(@Observes Router router) {
...
        GraphQL graphQL = GraphQL.newGraphQL(graphQLSchema).build();
        Route route = router.post("/graphql");
        route.handler(BodyHandler.create());
        route.handler(ApolloWSHandler.create(graphQL));
        route.handler(GraphQLHandler.create(graphQL).queryContext(routingContext -> newContext(routingContext)));
}

 private DataFetcherContext newContext(RoutingContext routingContext) {
        QuarkusHttpUser user = (QuarkusHttpUser) routingContext.user();
        return new DataFetcherContext(user.getSecurityIdentity());
    }

    public class DataFetcherContext {
        final SecurityIdentity identity;

        public DataFetcherContext(SecurityIdentity identity) {
            this.identity = identity;
        }

       //other useful data fetcher contextual references from CDI
    }
```
