### ISSUE TITLE
Support the propagation of tokens from OIDC/JWT to Kafka

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#18604]
### Description

[Token Propagation Filter](https://quarkus.io/guides/security-openid-connect-client#token-propagation) supports the propagation (with the possible re-signing or token exchange) from the current Quarkus endpoint (secured with either `quarkus-oidc` or `quarkus-smallrye-jwt`, the OAuth2 extension may also work) to the downstream HTTP endpoints.

This enhancement request is about supporting the token propagation from Quarkus endpoint to the downstream Kafka destinations.

CC @ozangunalp, @cescoffier

### Implementation ideas

Kafka client should be configured with the token which is already available to the Quarkus endpoint. Some simple code from `quarkus-oidc-token-propagation` can be reused (which simply accepts an injected `TokenCredential` and uses its `getToken` value - initially that should be enough - and later `OidcClient` can be wired in to exchange the tokens).

The question is, is it possible to configure Kafka Client with the existing token ?

**Comment by cescoffier** [comment]
From what I understand, you want to inject the token for a specific authentication mechanism of Kafka. This would require having access to this authenticator and configuring it (if that's possible). The configuration is done once (and so unsuitable for this case). 

We may be able to use record interceptors to configure the token per message, but I'm not totally sure how this would work.

**Comment by sberyozkin** [comment]
> From what I understand, you want to inject the token for a specific authentication mechanism of Kafka.

Yes, into the one which can currently create the tokens itself (and uses Nimbus as per the Zulip discussion).

> We may be able to use record interceptors to configure the token per message, but I'm not totally sure how this would work.

Hopefully this or something similar could eventually work :-)

**Comment by cescoffier** [comment]
The question is: what do you expect to do with the token?

1) connect to the kafka broker - that won't work, the Kafka authentication happens at startup, not per request
2) pass some token with the kafka record (in a header or something) to be used later - I doubt it's going to be very useful as the token may expire before the consumption of the records (that can happen months later and multiple times)

**Comment by sberyozkin** [comment]
Hi Clement, @cescoffier, sure, I've opened this issue after following a Zero Trust discussion where the token propagation from the application endpoints to Kafka destinations has been discussed. I'll forward it to you offline. 

Point 2 would apply to any token propagation case - I'm using there is a specific scenario where the expectation is that the records will be consumed soon, or at least within the token expiry limit. 
I guess Point 1 is more about a technical authentication (if token is used there then the expiry issue would also apply).
So yeah, I believe it is point 2 which this issue is about

**Comment by cescoffier** [comment]
Ok, so about Point 2, this is "relatively" easy. I guess a ProducerInterceptor (https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/producer/ProducerInterceptor.html) can be set by the user which would extract the token from somewhere and add it to the header of the record.

**Comment by sberyozkin** [comment]
@cescoffier Great if this may already be done :-), I may try to experiment later on, should indeed be straightforward enough :-), thanks

**Comment by albert0815** [comment]
@sberyozkin , @cescoffier Is this something which you still consider useful and easy to implement? We would need this, any hint on how to get this up and running would be appriciated. 

Basically I assume this issue is same as #17501 (or at least this is the other side, the one on the consumer) which I once raised. Just to be clear, for us point 2 is the thing which we are into. 

Implementing a producer interceptor to pass the token to a Kafka message might be easy and I guess I would know how to do. But still it is not clear to me how we could implement the consumer side. Because there we need to create the QuarkusIdentity in a consumer interceptor. And this is what still is unclear for me how to implement something like that as only a HttpAuthenticationMechanism is available.

**Comment by sberyozkin** [comment]
@albert0815 Hi, we haven't looked into it recently, but it is useful to know there is some concrete user interest.

I think this issue is different to #17501, there it is about verifying this token, while here it is about producing it.

Can you please type here how such a producer interceptor can be implemented ? We can then doc it and resolve this issue, I know it won't solve #17501 but at least we'll still have some progress.

**Comment by cescoffier** [comment]
@ozangunalp  / @sberyozkin What's the status on this one? 

I'm still not feeling very comfortable with the idea to leak the token into persistent storage (kafka).

**Comment by sberyozkin** [comment]
@cescoffier Sure, lets close this one until we have some more specific requirements, thanks
