### ISSUE TITLE
Quarkus can not read the file : FileNotFoundException

### ISSUE THREAD

**Issue by erayerdem** [quarkusio/quarkus#18606]
### Describe the bug

I have a file at src/main/resources/pinglist/pinglist.xlsx  and I m trying to read this file in this code  . I m tried spring and standalone java application and I dont get any error . 
` URL url = getClass().getClassLoader().getResource("pinglist/pinglist.xlsx");
  FileInputStream file = new FileInputStream(url.getPath());
`
       `mvn compile quarkus:dev` works successfully  in my local machine 
       
      `mvn clean install  && java -jar target\quarkus-app\quarkus-run.jar ` gets FileNotFoudnException
     
     when I create image this dockerfile at openshift 
     
   

> FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3 

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
    && microdnf update \
    && microdnf clean all \
    && mkdir /deployments \
    && chown 1001 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh \
    && echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/lib/security/java.security

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY --chown=1001 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=1001 target/quarkus-app/*.jar /deployments/
COPY --chown=1001 target/quarkus-app/app/ /deployments/app/
COPY --chown=1001 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
     
     
this exception throwed 

`2021-07-12 07:59:28,685 ERROR [io.qua.run.Application] (main) Failed to start application (with profile dev): java.io.FileNotFoundException: file:/deployments/app/heart-beat-1.0.0-SNAPSHOT.jar!/pinglist/pinglist.xlsx (No such file or directory)`

Thanks

**Comment by geoand** [comment]
You should not be using `FileInputStream` to read a resource from the classpath.

I would use `getClass().getClassLoader().getResourceAsStream("pinglist/pinglist.xlsx");`

**Comment by erayerdem** [comment]
Thanks , its works .
