### ISSUE TITLE
scheduler: option to disable individual schedulers

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#18607]
### Description

As today it is possible to disable all the schedulers by setting `quarkus.scheduler.enabled` to false hoverit would be nice to be able to enable/disable individuals schedulers.

### Implementation ideas

Similar to the data-source configuration, we could introduce a property like:

    quarkus.scheduler.${identity}.enabled = true | false
    
to enable/disable named scheduler (matching the identity set with the `io.quarkus.scheduler.Scheduled` annotation)

**Comment by mkouba** [comment]
In fact, this is already possible via a config property, i.e. `@Scheduled(cron = "${myMethod.cron.expr}")` and `myMethod.cron.expr=disabled`. See https://quarkus.io/guides/scheduler-reference#cron and https://quarkus.io/guides/scheduler-reference#intervals for more information.

Moreover, it will be possible to skip a specific execution dynamically via [Conditional Execution](https://quarkus.io/version/main/guides/scheduler-reference#conditional_execution) in quarkus 2.1+.

**Comment by lburgazzoli** [comment]
Ah cool, for some reason I didn't notice them

**Comment by lburgazzoli** [comment]
@mkouba is this available in quarkus 1.x too ?

**Comment by mkouba** [comment]
> @mkouba is this available in quarkus 1.x too ?

Nope.

**Comment by lburgazzoli** [comment]
ok, that at least explain why I missed it :)
