### ISSUE TITLE
Expose LOG_QUERIES_SLOWER_THAN_MS for Hibernate

### ISSUE THREAD

**Issue by piotr-szybicki** [quarkusio/quarkus#18634]
### Description

Hibernate has this great option (https://vladmihalcea.com/hibernate-slow-query-log/) to set threshold above which the query us marked as slow and logged. I don't thing there is a way to set it under the current implementation in Quarkus.

**Comment by Sanne** [comment]
Right we should expose this property.

@piotr-szybicki would you be interested in trying to create a pull request?
