### ISSUE TITLE
panache-archive.marker file created at the root when building the optaplanner-quickstart

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#18654]
When I build the `optaplanner-quickstart` from our quarkus-quickstarts, I end up with a `panache-archive.marker` created at the root of the app.

Just run `mvn clean install` and the file appears. I wouldn't expect it to end up at the root of the project for the application itself?

@FroMage does it ring a bell?

**Comment by stuartwdouglas** [comment]
This is a duplicate of https://github.com/quarkusio/quarkus/issues/18134

Basically Optaplanner is creating a compiler instance that is not configured properly so the output ends up in the current working directory.

**Comment by ge0ffrey** [comment]
Thank you Stuart for identifying that. I need to verify if the issue is in Drools, Kogito or OptaPlanner-quarkus. Either way, it's indeed probably not a Quarkus issue. Let's close this ticket.

**Comment by stuartwdouglas** [comment]
It's in KieMemoryCompiler, it needs to set the CLASS_OUTPUT otherwise it just gets set to the current working directory.

**Comment by gsmet** [comment]
OK, closing this one then.
