### ISSUE TITLE
is quarkus-hibernate-orm contains a class like SpringPhysicalNamingStrategy ?

### ISSUE THREAD

**Issue by FromMeToMyself** [quarkusio/quarkus#18678]
### Description

If not, will this feature appear in the next of quarkus?

**Comment by geoand** [comment]
You can use `quarkus.hibernate-orm.physical-naming-strategy` to define your own strategy. 

Our `quarkus-spring-data-jpa` extension does contain this class, but of course the regular `quarkus-hibernate-orm` extension does not.

**Comment by Sanne** [comment]
No it doesn't. What are you needing to do?

**Comment by FromMeToMyself** [comment]
> No it doesn't. What are you needing to do?

Map database under_score field to java model camelCase field.
Although I can define it by myself, but I think if it provided by quarkus maybe better.
It just my opinion😄.

**Comment by Sanne** [comment]
I'm ok to add some generallyu useful naming strategies directly in the project if you'd like to contribute them.
