### ISSUE TITLE
Clicking on application class in stacktrace causes 500 in dev ui

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#18676]
### Describe the bug

I use idea for development.

Stack traces of the application are visible in the dev ui. Application classes are clickable, and should open the file in the ide. (see #15761)

This does not work however in my testing. The http access log simply shows a 500 status code.

### Expected behavior

File is opened in idea. If no ide is found, an actionable error message should be shown.

### Actual behavior

The http access logs show a status code 500. I was not able to get an stacktrace for this.
```
2021-07-14 09:54:36,646 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-11) 127.0.0.1 - - 14/Jul/2021:09:54:36 +0200 "POST /q/dev/io.quarkus.quarkus-vertx-http/openInIDE HTTP/1.1" 500 - 
Host: localhost:8080
Connection: keep-alive
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
Accept: */*
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryq6xHXmAFsFB0AMhL
Origin: http://localhost:8080
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/q/dev/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
content-length: 495
x-quarkus-hot-deployment-done: true
```

### How to Reproduce?

Reproducer:

1. mvn quarkus:dev
2. open dev ui, and open the log
3. in a seperate tab, go to localhost:8080/hello
4. switch to the dev ui log
5. click on the SomeResource application class

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14 LTS OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin.. Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Let me check

**Comment by geoand** [comment]
I couldn't reproduce this. Do you have a stacktrace perhaps?

**Comment by Postremus** [comment]
Hi @geoand,
No, was not able to get an stacktrace.
I believe the 500 status code is caused by this line: https://github.com/quarkusio/quarkus/blob/043f8070abb5c5ada02632b1d7829abec60e067a/extensions/vertx-http/deployment/src/main/java/io/quarkus/vertx/http/deployment/devmode/console/OpenIdeHandler.java#L46-L51
Activating debug logging for that logger prints following:

```
Unable to determine proper launch command for IDE: Ide{defaultCommand='eclipse'}
```

I have in my %PATH% variable an idea.cmd, generated using the jetbrains toolbox.

**Comment by geoand** [comment]
Would you be willing to debug through `io.quarkus.deployment.ide.IdeProcessor` and see what Quarkus is figuring out for your environment?

**Comment by Postremus** [comment]
I'll take a look later today.

**Comment by geoand** [comment]
Thanks a lot!

**Comment by Postremus** [comment]
@geoand 
I read through the source of the IdeProcessor a bit, and found some possible culprits.

1. Detecting the .idea directory is not working for multi module projects. 
https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java#L130-L142

The .idea directory is part of the root project (multi-module-jandex/.idea). The projectRoot variable points to multi-module-jandex/web, where no .idea exists.
In a simple project without any submodules idea is correctly detected.
```
Unable to determine proper launch command for IDE: Ide{defaultCommand='idea'}
```

2. Detecting the running idea process is not working, most likely since it does not use jbr in the command path, only in the working directory.
https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/ide/IdeProcessor.java#L62-L72
The code is searching for "jbr" inside the process command. Which is not the case for my system:
![image](https://user-images.githubusercontent.com/1223135/125605254-256ac022-8b2b-4051-b5f9-3e066ee1ddaf.png)

**Comment by geoand** [comment]
That's very useful information, thanks!

**Comment by geoand** [comment]
Would you be able to try https://github.com/quarkusio/quarkus/pull/18682 and see if it works on your environment?
