### ISSUE TITLE
@Context UriInfo/HttpRequest not injected into custom ClientHeadersFactory

### ISSUE THREAD

**Issue by sebthom** [quarkusio/quarkus#18684]
### Describe the bug

In our app we need to add HTTP headers to rest client calls based on the incoming HttpRequests URI.

We are using `RestClientBuilder.newBuilder()` to instantiate rest clients as we need to be able to dynamically change the baseURL during runtime.

Fields added with "@Context" to our ClientHeadersFactory are not injected.

### Expected behavior

Injecting HttpRequest, UriInfo objects into @Context annotated fields of ClientHeadersFactory should work.

### Actual behavior

Injecting HttpRequest, UriInfo objects into @Context annotated fields of ClientHeadersFactory does not seem to happen. the fields stay null.

### How to Reproduce?

We are instantiating the ClientHeadersFactory and RestClient like this:

```java
public static class MyClientHeadersFactory implements ClientHeadersFactory {
  @Context UriInfo uriInfo;
  @Context HttpRequest httpRequest;

  public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders,
    MultivaluedMap<String, String> clientOutgoingHeaders) {
    System.out.println(uriInfo); // prints null
    System.out.println(httpRequest); // prints null
    return clientOutgoingHeaders;
  }
}

@RegisterClientHeaders(MyClientHeadersFactory.class)
public interface HelloRemoteAPI extends Closeable {

  @GET
  @Path("/hello")
  @Produces("application/json")
  String hello();
}

@Path("/")
@SuppressWarnings("resource")
public class MyResource {

  private HelloRemoteAPI getHelloRemoteClient(String baseURL) {
    return RestClientBuilder.newBuilder()
      .baseUrl(new URL(baseURL))
      .build(HelloRemoteAPI.class);
  }

   @GET
   @Path("/hello")
   @Produces("application/json")
   public String hello() {
     return getHelloRemoteClient("http://somewhere").hello();
   }
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1621]

### Output of `java -version`

openjdk 11.0.10 2021-01-19 LTS

### Quarkus version or git rev

2.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment]
This is incorrect usage... You should not be trying to inject server side objects into client related classes
