### ISSUE TITLE
cli does not pass arguments to the app when using "--" shortcut

### ISSUE THREAD

**Issue by zemiak** [quarkusio/quarkus#18694]
### Describe the bug

When using a tip from quarkus tips 57 using maven, the quarkus cli does not pass arguments down to the app

### Expected behavior

`quarkus dev -- World` should pass the arguments down to the command line app

### Actual behavior

Getting from maven: `Unknown lifecycle phase "World"`

### How to Reproduce?

1. create a stock cli app: **quarkus create cli**
2. go there: `cd code-with-quarkus`
3. try to run with a parameter: `quarkus dev -- World`
4. getting: `Unknown lifecycle phase "World"`

### Output of `uname -a` or `ver`

Darwin zemiak-retina-macbook.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14

### Quarkus version or git rev

2.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/vasko/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1

### Additional information

**quarkus dev --dry-run -- 'World'** -> `/Users/vasko/Documents/projects/junk/code-with-quarkus/mvnw -Dstyle.color=always quarkus:dev World`

when running `quarkus dev -Dquarkus.args=World`, it passes the parameter down. The fact, that the app is unable to pick it up, is another thing, the dev mode reports: `[e] to edit command line args (currently 'World')`

**Comment by ebullient** [comment]
Fixed in #18666

**Comment by zemiak** [comment]
Thanks
