### ISSUE TITLE
dev mode does not pass the command-line arguments correctly to the app

### ISSUE THREAD

**Issue by zemiak** [quarkusio/quarkus#18695]
### Describe the bug

I am not sure, if this is caused by some dev mode glitch, or by the app generated using cli "create" template. However, if I am running:
`mvn compile quarkus:dev -Dquarkus.args='World'`
I am getting:
```
Hello
          , go go commando!
```

When I'm running:
`java -jar ./target/quarkus-app/quarkus-run.jar World`
I am getting:
```
Hello World, go go commando!
```

### Expected behavior

When running dev mode: the same output `Hello World, go go commando!`

### Actual behavior

Getting some empty newline as a parameter

### How to Reproduce?

1. quarkus create cli
2. cd code-with-quarkus
3. mvn compile quarkus:dev -Dquarkus.args='World'
4. 

### Output of `uname -a` or `ver`

Darwin zemiak-retina-macbook.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14

### Quarkus version or git rev

2.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/vasko/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1

### Additional information

After running `mvn compile quarkus:dev -Dquarkus.args='World'` and getting an unexpected input, however, the dev mode is reporting a correct parameter:
```
Press [q] or Ctrl + C to quit, [e] to edit command line args (currently 'World'), or any other key to restart
```

**Comment by stuartwdouglas** [comment]
I just tested it out and I can't reproduce it.

Did you add some tests to get the '[e] to edit command line args (currently 'World')' prompt? Quarkus 2.0.1 has a bug where that will only show up if you tests.

**Comment by geoand** [comment]
I could not reproduce this either.

**Comment by zemiak** [comment]
The problem is, me neither. I have cleaned up my junk folder, recreated the project and it works now :-(
Yesterday was a strange evening, sorry.

**Comment by zemiak** [comment]
Just for the record, that I am not wasting your time on purpose:
```
~/Documents/projects/junk/code-with-quarkus » mvn compile quarkus:dev  -Dquarkus.args="World"
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.0.1.Final:generate-code (default) @ code-with-quarkus ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- quarkus-maven-plugin:2.0.1.Final:dev (default-cli) @ code-with-quarkus ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ code-with-quarkus
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/vasko/Documents/projects/junk/code-with-quarkus/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ code-with-quarkus
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-07-14 22:49:36,498 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.1.Final) started in 0.842s.
2021-07-14 22:49:36,522 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-07-14 22:49:36,523 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, picocli]
Hello
          , go go commando!
2021-07-14 22:49:36,600 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus stopped in 0.002s
```

**Comment by geoand** [comment]
Thanks for taking the time to post your findings
