### ISSUE TITLE
Unable to install quarkus cli via jbang

### ISSUE THREAD

**Issue by zemiak** [quarkusio/quarkus#18692]
### Describe the bug

After installing the Quarkus cli and trying running it, I am getting compilation errors, apparently jbang is trying to compile a jar file.

### Expected behavior

I should be happily using the CLI by now

### Actual behavior

Getting cryptic binary characters in my terminal

### How to Reproduce?

1. cli installation (--fresh does not work for me):
`jbang app install --force quarkus@quarkusio`

2. quarkus help
```
/Users/vasko/.jbang/cache/urls/6c3236b01501d7b61370f6e8e1614185f3f670f68e3e623735bdfebed72c6b4a/QuarkusCli2.0.1.finalRunner.jar.java:2: error: unmappable character (0xFD) for encoding UTF-8
�l�R	META-INF/UT
     ^
```

Lots of these error messages appear

### Output of `uname -a` or `ver`

Darwin zemiak-retina-macbook.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14

### Quarkus version or git rev

2.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

jbang version `0.56.0`

### Additional information

JBang was installed/upgraded using brew.

**Comment by ebullient** [comment]
Wow! That's .. interesting. I did that this morning and it installed fine.

That is a pretty old version of jbang (I have 0.71.1 isntalled). 
Update jbang, and try again?

**Comment by zemiak** [comment]
Wav, that was a quick reaction :-) Of course, it's an old jbang - the `jbangdev/tap/jbang` is prety much outdated. After installing 0.72.0 everything works. Thanks!
