### ISSUE TITLE
Add basic injection capabilities to QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#18698]
### Description

As [discussed on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Get.20instance.20of.20QuarkusTestResourceLifecycleManager.20in.20test.3F/near/245973578), it would come in handy if there was some convenient injection support in `QuarkusTestResourceLifecycleManager`.
Today you are on own since you only get the `testInstance` in `inject()` and you have to do all the hard reflection work yourself.

### Implementation ideas

In a backward-compatible way, a new `inject(BasicInjector injector)` method could be introduced.
That `BasicInbjector` (or whatever its name is) wraps the test instance and could provide some basic convenience methods like:
- `injectIntoFields(Class<?> type, Object value)` (or with `<T>`)
- `injectIntoFields(Class<? extends Annotation> type, Object value)`
- etc.

**Comment by geoand** [comment]
Thanks for reporting!

This seems pretty useful to me. Hopefully I can pick it up soon

**Comment by geoand** [comment]
@FroMage always has exquisite API improvement ideas, so let's tap into his knowledge to get another take on this one :)

**Comment by geoand** [comment]
My idea building on what @famod posted here is something like:

```java

    default void inject(TestInjector testInjector) { // this is the new method

    }

    static abstract class TestInjector { // the implementation will be supplied by the test extension and one new instance will be created per test

        protected final Object testInstance;

        protected TestInjector(Object testInstance) {
            this.testInstance = testInstance;
        }


        public abstract void injectIntoFields(Class<?> type);

        public abstract void injectIntoFieldsWithAnnotation(Class<? extends Annotation> type);
    }
```

Then a supplied user implementations of `QuarkusTestResourceLifecycleManager` could do something like:

```java
    @Override
    public void inject(TestInjector testInjector) {
        testInjector.injectIntoFieldsWithAnnotation(KubernetesTestServer.class);
    }
```

WDYT?

**Comment by famod** [comment]
I like the varargs idea. CDI `BeanManager` and `Instance` use similar approaches.

PS: Another strategy, which can be used today, is to define an interface with one or more setters etc. and then use the existing inject method that can then simply do an `instanceof` + cast + call the setter. The rest is up to the implementing test class.
But Quarkus is about developer joy and the injector would make things easier regardless.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18714 is what I have in mind

**Comment by mkouba** [comment]
I like the idea but should be really clear that it has nothing to do with CDI injection ;-).

**Comment by geoand** [comment]
@mkouba definitely. How do you propose we make it clearer?

**Comment by mkouba** [comment]
> @mkouba definitely. How do you propose we make it clearer?

I'm not sure. Maybe just emphasize that the manager is fully in control of the lifecycle of the injected instance and that this "injection" happens after the CDI injection is perfomed??

**Comment by geoand** [comment]
PR updated to include that note in the Javadoc and the documentation

**Comment by FroMage** [comment]
> @FroMage always has exquisite API improvement ideas, so let's tap into his knowledge to get another take on this one :)

This is perfect!
