### ISSUE TITLE
OIDC Authorization Code Flow: add property to define response_mode to support Azure Active Directory B2C

### ISSUE THREAD

**Issue by franden** [quarkusio/quarkus#18711]
### Description

# Current behavior
We are using [Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow) in our company as identity provider. Unfortunately the quarkus OIDC with Authorization Code Flow do not work with this identity provider. The reason is, that if `response_mode` is not specified, the Identity Provider sends the code as `fragment` parameter, not as `query` parameter. Since fragment parameter are never sent to the server by the browser, quarkus app will never get the code.

![image](https://user-images.githubusercontent.com/20822716/125750969-cb270dde-712e-4865-83d0-4cc77d6a5704.png)

# Possible solutions / Expected behavior
1. If it would be possible to specify the `response_mode` , we would be able to set it to `query`.  According to the [oauth specification](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes) the `response_mode=query` is only a default value, not a MUST.
2. Another, solution would be if quarkus OIDC would set `response_mode=query` for all requests, rather then rely on the default `response_mode`.  Since only query parameters are used as source for "code". https://github.com/quarkusio/quarkus/blob/d9c30ee06fd9e2cac645209f2ed6cef131e3a25c/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L99

**Comment by sberyozkin** [comment]
@franden Thanks, well, yes, the core OIDC specification and the response mode one you linked to all say it is not recommended to send `response_mode=query` for `response_type=code`. It does look like a problem with this provider - but the good news is that you can use `quarkus.oidc.authentication.extra-params.response_mode=query` - can you try it please ?

**Comment by franden** [comment]
@sberyozkin `quarkus.oidc.authentication.extra-params.response_mode=query` works for me. thank you very much

**Comment by sberyozkin** [comment]
@franden Great, it would make sense to update the docs, I'll do it during the next doc PR
