### ISSUE TITLE
Exception reading yaml config list

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18727]
### Describe the bug

I'm not sure if this is currently unsupported behavior. But I'm trying to read a config list from my `application.yaml` into a list of POJOs, but it causes an exception. Please let me know if it's just user error and I'm doing something incorrectly.

### Expected behavior

```
Failed to start application (with profile prod): java.lang.NullPointerException
	at io.smallrye.config.ConfigMappingProvider.<init>(ConfigMappingProvider.java:73)
	at io.smallrye.config.ConfigMappingProvider$Builder.build(ConfigMappingProvider.java:904)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
	at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:50)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:513)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)

```

### Actual behavior

Successfully reads the config to the POJOs.

### How to Reproduce?

Reproducer: `service3` in https://github.com/mweber03/quarkus-test

1. `./gradlew service3:quarkusBuild`
2. `docker build -t service3 -f modules/service3/Dockerfile .`
3. `docker run -it -p 8080:8080 service3`

application.yaml
```
app:
  other: thing
  items:
    - name: name1
      num: 1
    - name: name2
      num: 2
```

java
```
    @ConfigMapping(prefix = "app.items")
    List<Service3Config> config;

    @GET
    @Path("names")
    @Produces(MediaType.TEXT_PLAIN)
    public List<String> names() {
        return this.config.stream().map(Service3Config::name).collect(Collectors.toList());
    }
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

**Comment by radcortez** [comment]
Lists are not supported as the root level, so you should create a mapping that represents the root, something like:

```java
interface App {
  String other();

  List<Item> items();

  interface Item {
    String name();
    Integer num();
  }
}
```

**Comment by mweber03** [comment]
Can this be added as an enhancement? It seems like a useful feature.

**Comment by radcortez** [comment]
If you prefer, you can map only the List, but for now, it always requires a wrapping object. Right now, supporting such a case is not in our priorities, since in my opinion, you are not saving much (just a couple of lines of code) so I don't see it as a feature that requires priority.

Of course, if you are willing to invest the time and provide the implementation for it, we are happy to review your PR :)

**Comment by mweber03** [comment]
I would be interested in making this update. I haven't dove deep into the Quarkus/Smallrye code yet, do you have a suggestion of what classes I should start looking with?

**Comment by radcortez** [comment]
Great. The main functionality is implemented in SR Config. 

Start by looking at:
https://github.com/smallrye/smallrye-config/blob/b10181c9572a66b78bb4de39bb4cd49cfaf85af3/implementation/src/main/java/io/smallrye/config/ConfigMappings.java
https://github.com/smallrye/smallrye-config/blob/b10181c9572a66b78bb4de39bb4cd49cfaf85af3/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java

And then just unwrap from there. The way you get a mapping programmaticaly is to call `io.smallrye.config.ConfigMappings#getConfigMapping(java.lang.Class<T>)`.

**Comment by delongmeng** [comment]
> @radcortez I haven't had any luck figuring this out.

Hi @radcortez I'm working on this issue. Can you reminder me in your original post where can I find the java code:    
```
@ConfigMapping(prefix = "app.items")
    List<Service3Config> config;
```
? Thanks!

**Comment by delongmeng** [comment]
> Ok, no worries. I'll see if I can look into it.

Hi @radcortez I'd like to work on this enhancement but am not familiar enough with the smallrye-config. Could you please elaborate a little bit more on the potential steps of implement the enhancement? Thanks!

**Comment by radcortez** [comment]
Hi @delongmeng 

Thanks for the help. Please have a look at the following sources:

https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappings.java
In here, you can find how mappings are registered and retrieved

https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java
Most of the mapping logic is contained here

Now, mappings are stored by their base class and instance and prefix. This means that somehow, you need to be able to tell that you want to retrieve a list of something. The tricky part here is that all the implementation was done around the existence of a single root, so most likely all the APIs and internals would need to change to accommodate a List. Probably the easiest way to implement something like this is to add some sort of a class aggregator that can represent a mapping of the list, that wraps the list itself to return it when requested. 

Hope it helps.

**Comment by delongmeng** [comment]
> Hi @delongmeng
> 
> Thanks for the help. Please have a look at the following sources:
> 
> https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappings.java In here, you can find how mappings are registered and retrieved
> 
> https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java Most of the mapping logic is contained here
> 
> Now, mappings are stored by their base class and instance and prefix. This means that somehow, you need to be able to tell that you want to retrieve a list of something. The tricky part here is that all the implementation was done around the existence of a single root, so most likely all the APIs and internals would need to change to accommodate a List. Probably the easiest way to implement something like this is to add some sort of a class aggregator that can represent a mapping of the list, that wraps the list itself to return it when requested.
> 
> Hope it helps.

Thank you very much @radcortez for the explanation! That sounds a little challenging to me but I'll take a closer look later.

**Comment by radcortez** [comment]
@delongmeng thanks for taking a look into it. There is indeed some effort involved in this.

Maybe I can suggest something smaller?

**Comment by radcortez** [comment]
Closing in favor of https://github.com/smallrye/smallrye-config/issues/698.
