### ISSUE TITLE
@TestSecurity annotation isn't working after upgrading from Quarkus 1.13.7 to 2.0.x

### ISSUE THREAD

**Issue by BenteleFlorian** [quarkusio/quarkus#18721]
### Describe the bug

While upgrading to Quarkus 2.0.0, the @QuarkusTest for a microservice fails due to 403 forbidden access errors on secured API Endpoints, which could usually be handled by `@TestSecurity` - as described within the [official quarkus documentation](https://quarkus.io/guides/security-testing) - and the user/role we provide.

The annotation is working as expected in Quarkus version 1.13.7 and the same is true for the base annotation `@TestSecurity(authorizationEnabled = false)`.
As we didn't change anything else besides upgrading to the new quarkus version our assumption is that the `@TestSecurity `annotation does not properly take in the provided role in Quarkus 2.0.x any more.

### Expected behavior

`@TestSecurity(user = "testUser", roles = {"admin", "user"})` should authorize and run our integration tests using identity with the given username and roles.

### Actual behavior

Test Cases for APIs that are limited to a specific OpenID Role are failing in Quarkus 2.0.x with an Authorization Error even though @TestSecurity is set.

```
[ERROR]   ControllerTest.test_initiation:212 1 expectation failed.
Expected status code <201> but was <403>.
```

We verified this error both on local machine as well as within our build pipeline (Azure DevOps).

### How to Reproduce?

1. Quarkus microservice with a secured API in version 1.13.7 with `@TestSecurity` Annotation to Authenticate against the endpoint
2. Run tests e.g. `mvn clean verify`
3. Check that access to the secured API is granted for the test cases
4. Upgrade to quarkus 2.0.x (we tested with all currently available patch versions)
5. Run tests again by executing e.g. `mvn clean verify` without changing anything else
6. Access to the secured API is denied (40X Errors)

### Output of `java -version`

11

### Quarkus version or git rev

2.0.0, 2.0.1, 2.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by sberyozkin** [comment]
@BenteleFlorian Can you please provider a reproducer project ? Quarkus tests relying on this annotation are running

**Comment by gsmet** [comment]
I'm closing this one for now. Please reopen with a reproducer once you have it. Thanks!
