### ISSUE TITLE
Support jacocoTestCoverageVerification task for quarkus jacoco plugin

### ISSUE THREAD

**Issue by lucafuji** [quarkusio/quarkus#18726]
### Description

When directly using the gradle jacoco plugin, it supports specifying a minimum coverage of a certain project so that if the test coverage is lower than this number, the corresponding build task will fail.

e.g.
`jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.7
            }
        }
    }
}`
will fail the build if the coverage is lower than 0.7.

So far this feature is not supported by https://quarkus.io/guides/tests-with-coverage

**Comment by famod** [comment]
In Maven you can simply run the respective goal and it picks up the results recorded by quarkus-jacoco just fine. Have you tried something similar with Gradle?

**Comment by lucafuji** [comment]
@famod 
I tried run with "./gradle check", it did generate reports, but it did not fail the build because of low coverage

**Comment by stuartwdouglas** [comment]
Did you configure the correct results file?

**Comment by lucafuji** [comment]
Just double confirm that I put the following blocks in my build.gradle
`jacocoTestCoverageVerification { 
 violationRules { 
  rule { 
    limit { 
     minimum = 0.7 
   } 
  } 
 } 
}`

Is this the correct way to specify minimal coverage?

I did not find a way to specify it in application.properties.
https://quarkus.io/guides/all-config

**Comment by geoand** [comment]
@lucafuji can you attach an example project?

**Comment by brianwyka** [comment]
I was able to get this to work, but only with a "hack":

Plugin Declaration:
```gradle
plugins {
   id: 'jacoco'
}
```

Test Dependency:
```gradle
dependencies {
   testImplementation 'io.quarkus:quarkus-jacoco'
}
```

Jacoco Configuration
```gradle
test {
    jacoco.enabled = false
}
jacocoTestCoverageVerification {
    executionData.setFrom("$project.buildDir/jacoco-quarkus.exec")
    violationRules {
        rule {
            limit {
                counter = 'INSTRUCTION'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
}
check.dependsOn jacocoTestCoverageVerification
```

The key parts were disabling `jacoco` within `test.jacoco.enabled` and setting the `executionData` to the quarkus generated exec file.

**Comment by brianwyka** [comment]
Unfortunately the above hack does not allow jacoco to check coverage for plain unit tests (not annotated with `@QuarkusTest`.

**Comment by brianwyka** [comment]
This may also be related to this:
https://github.com/gradle/gradle/issues/14760

**Comment by brianwyka** [comment]
@geoand , I think you can close this out now.  Docs have been updated in `Main-SNAPSHOT` here with gradle instructions:
https://quarkus.io/version/main/guides/tests-with-coverage

**Comment by geoand** [comment]
Thanks
