### ISSUE TITLE
Specify an Application class at build time

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18725]
### Description

Currently if your classpath contains more than one `javax.ws.rs.core.Application` an error occurs: `RuntimeException: More than one Application class: [my.project.service1.Service1Application,my.project.service1.Service1Application,my.project.service3.Service3Application]`

The existing logic can remain to automagically pickup the `Application`, but additional logic allowing one to specify a specific `Application` could be very useful in the above case.

**Comment by geoand** [comment]
@stuartwdouglas the ability to remove classes from a dependency you introduced in https://github.com/quarkusio/quarkus/pull/18121 would work here too right? 
A user would still need to specify the groupId and artifactId of the application, but the handling would work for application cases too wouldn't it?

**Comment by mweber03** [comment]
What is the groupId/artifactId if it's coming from a local project? For example: `implementation project(':myproject')`

**Comment by geoand** [comment]
> What is the groupId/artifactId if it's coming from a local project? For example: `implementation project(':myproject')`

https://github.com/quarkusio/quarkus/pull/23168 will make that possible

**Comment by aloubyansky** [comment]
> What is the groupId/artifactId if it's coming from a local project? For example: `implementation project(':myproject')`

That would be group and name in Gradle.
