### ISSUE TITLE
Opentracing NPE with v2

### ISSUE THREAD

**Issue by Rupert-RR** [quarkusio/quarkus#18739]
### Describe the bug

Incoming requests in a Quarkus 2 application cause NPEs in OpenTracing classes (as per https://github.com/quarkusio/quarkus/issues/13440).

This issue was fixed in https://github.com/smallrye/smallrye-opentracing/pull/173 and backported to the `1.3.5` release but no new release was made for `2.0.0` (which was released prior to the bug fix). Quarkus `2.0.0` has bumped the version of OpenTracing to `2.0.0` and so inherits this bug again.
I have created the issue https://github.com/smallrye/smallrye-opentracing/issues/193 to ask for a new release incorporating this bug fix then presumably we will need a new Quarkus release to bump the OpenTracing version again.

### Expected behavior

Incoming requests should not generate NPEs for OpenTracing classes.

**Comment by kenfinnigan** [comment]
@radcortez FYI

**Comment by radcortez** [comment]
Related with https://github.com/smallrye/smallrye-opentracing/issues/193
