### ISSUE TITLE
Opentelemetry does not seem to reliably preserve trace context to JAX-RS

### ISSUE THREAD

**Issue by hacst** [quarkusio/quarkus#18750]
### Describe the bug

With the quarkus-opentelemetry extension requests coming into Quarkus produce a server span for tracing. All subsequent spans on this call-path should then have the same traceId as this span and should be descendents with regards to spanId parent relationships. However this does not seem to be the case with resteasy JAX-RS handlers.

### Expected behavior

All subsequent spans in this request should have the same trace id as the server span and should be descendants with regards to span id parent relationships.

### Actual behavior

Spans created in the JAX-RS handler seem to start with a new trace context. They have an invalid parent (0000000000000000) and a new trace id instead of sharing the server span trace id and having it as the parent. It seems the JAX-RS handler did not receive the context that was previously know in the vert.x level.

### How to Reproduce?

Using the normal code-with-quarkus with resteasy and quarkus-opentelemetry extension add creation of a span to the GreetingResource:

```java
package org.acme;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {
    @Inject
    io.opentelemetry.api.trace.Tracer tracer;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        var span = tracer.spanBuilder("inside").startSpan();
        try (var scope = span.makeCurrent()) {
            return "Hello RESTEasy";
        } finally {
            span.end();
        }
    }
}
```

Doing a curl on the endpoint on a development server reproduces the issue.

```
Span: inside (INTERNAL, span id a44cb46c93c5a32b) parent 0000000000000000 trace aa187c927d67a6292d4e76cd09d11e5c
Span: hello (SERVER, span id a385283b4671c3a2) parent 0000000000000000 trace 16eef290f7c223d2f70350f69209c58b
```

Curling with a provided traceparent (e.g. `curl -v -H "traceparent: 00-dead50a4b9a9660eea4cad2a2a5e10dd-deadedeb2bf43038-01" http://localhost:8080/hello`) show the same behavior:

```
Span: inside (INTERNAL, span id ffdfaff9cdf88e43) parent 0000000000000000 trace 8e683504f17026c39ce77e83bfa20a79
Span: hello (SERVER, span id fb5f3934ff83c7de) parent deadedeb2bf43038 trace dead50a4b9a9660eea4cad2a2a5e10dd
```

Here is the custom exporter producing the output:
```java
package org.acme;

import io.opentelemetry.sdk.common.CompletableResultCode;
import io.opentelemetry.sdk.trace.data.SpanData;
import io.opentelemetry.sdk.trace.export.SpanExporter;
import io.quarkus.arc.Unremovable;

import javax.enterprise.context.ApplicationScoped;
import java.util.Collection;

@Unremovable
@ApplicationScoped
public class CustomExporter implements SpanExporter {
    @Override
    public CompletableResultCode export(Collection<SpanData> spans) {
        for (var span: spans) {
           System.out.println(String.format("Span: %s (%s, span id %s) parent %s trace %s", span.getName(), span.getKind(), span.getSpanId(), span.getParentSpanId(), span.getTraceId()));
        }
        return CompletableResultCode.ofSuccess();
    }

    @Override
    public CompletableResultCode flush() {
        return CompletableResultCode.ofSuccess();
    }

    @Override
    public CompletableResultCode shutdown() {
        return CompletableResultCode.ofSuccess();
    }
}

```

### Output of `java -version`

11.0.7

### Quarkus version or git rev

2.1.0.RC1

### Additional information

Another thing I wanted to try is whether context is properly propagated when using a RestClient. In the experiment the service called itself. For some reason there the context seems to be preserved after it gets lost on the initial request.

Here is the output for that:
```
Span: inside top (INTERNAL, span id 9844764273f64f7f) parent 0000000000000000 trace 
Span: inside sub (INTERNAL, span id e3cce5b999a4c469) parent a18aa50f01db1ba0 trace 254fb3ffd1ea04075e1176a9de41ffb6
Span: hello/sub (SERVER, span id a18aa50f01db1ba0) parent d7f8e3286d9fe48c trace 254fb3ffd1ea04075e1176a9de41ffb6
Span: hello/sub (CLIENT, span id d7f8e3286d9fe48c) parent 0000000000000000 trace 254fb3ffd1ea04075e1176a9de41ffb6
Span: hello/top (SERVER, span id 2e0c66cb709e47f8) parent deadedeb2bf43038 trace dead50a4b9a9660eea4cad2a2a5e10dd
```
After being called via curl top calls sub via rest client through localhost. Both have an internal span like in the example above. As can be seen top looses the context after the hello/top SERVER span while in sub the following "inside sub" span has the correct parent and trace data from the hello/sub. I'm not really sure what to make of this.

**Comment by hacst** [comment]
I had a bit of time to look into this. Unfortunately this is at the interface of various frameworks I know little about. But it looks like context transfer relies on [putLocal](https://vertx.io/docs/apidocs/io/vertx/core/Context.html#putLocal-java.lang.String-java.lang.Object-) which stores data on a [DuplicatedContext](https://groups.google.com/g/vertx-dev/c/hKJsj4v8KaA) that has the actual EventLoopContext as its delegate. Unfortunately the DuplicatedContext is not what is transferred into the system so this part of the context information is lost. I tried to check how other extensions transfer context data from vertx but they seem to rely on a [RoutingContext](https://vertx.io/docs/apidocs/io/vertx/ext/web/RoutingContext.html) which data can be added to. However that is created later. The tracing code runs very early as it taps into the Vertx tracing system. I find the vertx documentation to be quite sparse around the topic of different kinds of contexts and with the other layers added by Quarkus I have not yet found a obvious way to get the the information transported correctly.

**Comment by hacst** [comment]
@kenfinnigan Is there some estimate as to when this can be tackled? It is currently a blocker for adoption of the extension for us as we cannot get uninterrupted traces out of any JAX-RS api and cannot disable the code producing the broken spans. I understand that there are higher priorities than an experimental extension. Really only looking for some insight on what to expect. Thanks.

**Comment by radcortez** [comment]
I can confirm that I was able to reproduce the issue with `2.1.0.Final`.

With the latest version (`2.5.0.Final`), this is not happening anymore. Not sure when it was fixed, but it is :)
