### ISSUE TITLE
Combination Hibernate Validation advice to use @ApplicationScoped does not work.

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#18763]
### Describe the bug

If there are multiple occurrences of a custom annotation, it seems that there's only one initialized.  This is not the case in for instance JBOSS and leads to unexpected behavior.

I also tried @Singleton, same result.

### Expected behavior

The annotation is initialized with the correct annotation proxy instance before the `isValid` is executed.

### Actual behavior

It is not. First come, first serve.

### How to Reproduce?

https://github.com/sjaakd/reproducer_hv

Steps to reproduce: 
http://localhost:8080/reproducer/q/swagger-ui/#/default/example

Note the validated `Request`:

```java
    @AlwaysInvalid
    private String field1;

    @AlwaysInvalid( defaultState = "test ")
    private String field2;
```

The validator implementation is supposed to select the injected dao if  `defaulState` is not set.

### Output of `java -version`

java 11

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

1.12.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven, intellij

### Additional information

none

**Comment by geoand** [comment]
Quarkus `1.12.1.Final` is pretty old by now, can you try `1.13.7.Final` and / or `2.0.2.Final`?

**Comment by gsmet** [comment]
This is expected. You made your `AlwaysInvalidValidator` bean `@ApplicationScoped` so only one will be created for the whole application.

If you make it `@Dependent`, the problem goes away.

**Comment by sjaakd** [comment]
> This is expected. You made your `AlwaysInvalidValidator` bean `@ApplicationScoped` so only one will be created for the whole application.
> 
> If you make it `@Dependent`, the problem goes away.

I understand.. but I think the behavior on JBOSS looks different that in Quarkus (our validators are shared). That is portability issue. I'll check if I can adapt in JBOSS as well. I can't find where, but I read somewhere that the advice was to use `@ApplictionScoped` on custom validators.

Besides this example, I could not get non `@ApplicationScoped` validators to function earlier.

**Comment by sjaakd** [comment]
> Quarkus `1.12.1.Final` is pretty old by now, can you try `1.13.7.Final` and / or `2.0.2.Final`?

I would really like to, but https://github.com/quarkusio/quarkus/issues/18587 is blocking me.

**Comment by Sanne** [comment]
>  I can't find where, but I read somewhere that the advice was to use @ApplictionScoped on custom validators.

I really don't know about that, but I'd suggest to trust @gsmet over other random suggestions as he's the project lead for Hibernate Validator and also responsible for its maintenance in JBoss server ;-)

**Comment by gsmet** [comment]
Well, `@ApplicationScoped` is recommended **IF** your bean can be shared as you then have only one instance.

It's definitely not recommended if you need different `ConstraintValidator` beans.

**Comment by gsmet** [comment]
@sjaakd I created https://github.com/quarkusio/quarkus/pull/18935 to clarify this. Thanks for the report!
