### ISSUE TITLE
Use of RestClientBuilder leads to RESTEASY004655

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#18777]
### Describe the bug

In my application, I use a REST client using Injection:

```java
@Inject
@RestClient
MyApi myApi;
```

Which I configure using properties like:

```
my-api/mp-rest/url             = ${base-url}
my-api/mp-rest/connectTimeout  = 5000
my-api/mp-rest/readTimeout     = 10000

quarkus.ssl.native    = true
quarkus.tls.trust-all = true

quarkus.oidc-client.client-enabled             = true
quarkus.oidc-client-filter.register-filter     = false
quarkus.oidc-client.auth-server-url            = ${oidc-auth-server}
quarkus.oidc-client.client-id                  = ${client-id}
quarkus.oidc-client.credentials.secret         = ${client-secret}
```

The client is generates using the openapi generator so I don't have much option to customize (i.e. to add additional providers) thus I want to programmatic create the client but at this point, if I do something like:

```java
 myApi = RestClientBuilder.newBuilder()
    .baseUri(controlPlaneUri)
    .register(OidcClientRequestFilter.class)
    .register(SomethingElse.class)
    .build(MyApi.class);
```

then each call fails with:

```
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

### Expected behavior

I should be able to create a rest client using `RestClientBuilder`

### Quarkus version or git rev

2.0.2

**Comment by lburgazzoli** [comment]
I got it working copying some bits from the resteasy extension:

```java
        SSLContext sslContext = SSLContext.getInstance("SSL");
        sslContext.init(
            null, 
            new TrustManager[] { new PassthroughTrustManager() },
            new SecureRandom());
                
        MyApi api = RestClientBuilder.newBuilder()
            .baseUri(baseUrl)
            .sslContext(sslContext)
            .register(OidcClientRequestFilter.class)
            .register(NoopHostnameVerifier.class)
            .connectTimeout(5, TimeUnit.SECONDS)
            .readTimeout(10, TimeUnit.SECONDS)
            .build(MyApi.class);
```

but I think this should work out of the box as `quarkus.tls.trust-all` is set in the application properties file

**Comment by sberyozkin** [comment]
Hi @lburgazzoli, indeed, the OIDC client filter itself depends on Vert.x Web Client Mutiny.

**Comment by lburgazzoli** [comment]
@sberyozkin I tested that `OidcClientRequestFilter` is really not the culprit here but it looks like the implementation of `RestClientBuilder` do not honor `quarkus.tls.trust-all`

**Comment by lburgazzoli** [comment]
@gsmet mind having a look ?

**Comment by geoand** [comment]
cc @michalszynkiewicz

**Comment by michalszynkiewicz** [comment]
I will fix it, hopefully today. I have something that should work but one of the tests is failing ATM ;)

**Comment by geoand** [comment]
Is there a PR that closed this?

**Comment by michalszynkiewicz** [comment]
https://github.com/quarkusio/quarkus/pull/18892
