### ISSUE TITLE
jbang q:config properties not being picked up in 2.1

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18784]
### Describe the bug

jbang q:config properties seem to no longer be picked up

```
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-universe-bom:2.1.0.CR1@pom
//DEPS io.quarkus:quarkus-hibernate-orm-panache
//DEPS io.quarkus:quarkus-resteasy
//Q:CONFIG quarkus.datasource.db-kind=postgresql
//DEPS io.quarkus:quarkus-swagger-ui
//Q:CONFIG quarkus.swagger-ui.always-include=true
//JAVAC_OPTIONS -parameters

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.transaction.Transactional;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello-resteasy")
@ApplicationScoped
public class main {

    
    @GET
    @Transactional
    public String sayHello() {
        Test t = new Test();
        t.name = "max";
        t.persist();
        return "Hello RESTEasy";
    }


    public static void main(String[] args) {
        Quarkus.run(args);
    }


    static public class Test extends PanacheEntity {
        String name;
    }
}
```

### Expected behavior

that Q:CONFIG is picked up and honored when running with jbang.

opened here as its the quarkus side that is extracting the Q:* values.

### How to Reproduce?

Take the example above and run with `jbang --fresh -Dquarkus.dev main.java` and see it is not picking db-kind nor swagger include config option.

**Comment by gsmet** [comment]
@maxandersen is this still an issue? I think I define some in my JBang scripts and they work fine.

**Comment by maxandersen** [comment]
Yeah. This was fixed.

**Comment by jbride** [comment]
I'm noticing that //Q:Config doesn't seem to work with Quarkus 2.16.3 .
I am able to append the same properties to //JAVA_OPTIONS and that works fine.

**Comment by maxandersen** [comment]
Yes there is a regression here. It's not trivial to fix unfortunately. Using //Files application.properties or //Javaoptions are the best workarounds.

**Comment by jbride** [comment]
got it.  thank you.
