### ISSUE TITLE
Dependencies not included in uber jar

### ISSUE THREAD

**Issue by digven** [quarkusio/quarkus#18782]
### Describe the bug

I have the attached quarkus project (code-with-quarkus.zip) created with "amazon-lambda, resteasy, jackson. and gson" libraries. I have a StreamLambdaHandler implementing the RequestStreamHandler. 

I have the below property added in application.properties:
quarkus.package.uber-jar=true

I am using the thin jar named "code-with-quarkus-1-runner.jar".

Sending a JSON POST request from API gateway is giving below exception. Please let me know what could be the issue.

Error loading class org.test.StreamLambdaHandler: com/google/gson/JsonElement: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement. Current classpath: file:/var/task/

### Expected behavior

the gson libraries should have been copied in the uber jar and should not have thrown any exceptions

### Actual behavior

Sending a JSON POST request from API gateway is giving below exception. Please let me know what could be the issue.

Error loading class org.test.StreamLambdaHandler: com/google/gson/JsonElement: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement. Current classpath: file:/var/task/

### How to Reproduce?

Please try to generate a uber jar from the attached project, create lambda function and test it through API Gateway

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/6835684/code-with-quarkus.zip)

**Comment by digven** [comment]
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/6835683/code-with-quarkus.zip)

**Comment by gsmet** [comment]
I don't see any uberjar config in the attached project?

**Comment by digven** [comment]
@gsmet can you please let me know the config to provide for uber jar. 

I have the below property added in application.properties:
quarkus.package.uber-jar=true

**Comment by digven** [comment]
@gsmet  can you please respond. I tried few options and couldn't get this working. Appreciate your response

**Comment by jaikiran** [comment]
Hello @digven,

> I have the below property added in application.properties right now
> quarkus.package.uber-jar=true

Please use `quarkus.package.type=uber-jar` as noted in the documentation here https://quarkus.io/guides/maven-tooling#uber-jar-maven
