### ISSUE TITLE
hibernate-reactive-panache gives error "org.hibernate.LazyInitializationException: HR000056: Collection cannot be initialized"

### ISSUE THREAD

**Issue by re-thc** [quarkusio/quarkus#18786]
### Describe the bug

Tried using the latest Quarkus 2.1.0.RC and `hibernate reactive panache`. On `@OneToMany` and `@ManyToMany`. Looks like an issue with `FetchType.LAZY` as if I manually specify `FetchType.EAGER` it works. Tried wrapping it in `Panache.withTransaction` and any other combinations but doesn't work.

### Actual behavior

org.hibernate.LazyInitializationException: HR000056: Collection cannot be initialized: org.test.Test

### How to Reproduce?

1. Use `hibernate-reactive-panache`
2. Have mappings for any relationship that includes `OneToMany` or `ManyToMany`
3. Try to query it, e.g. listAll()

### Quarkus version or git rev

2.1.0.CR1

**Comment by gavinking** [comment]
Are you sure you've understood the need to call `fetch()` explicitly to perform lazy fetching in reactive?

**Comment by re-thc** [comment]
How would that work with e.g. entity.list()? I can see how it works with HR but there's no documentation of it on the Panache side. All variants of `list` return a `List<Entity>`. At this point it's already resolved? Where would `fetch` go?

**Comment by gavinking** [comment]
I don't think we can help any further unless you show us some code.

**Comment by DavideD** [comment]
@re-thc Without a reproducer it's hard to help you.

But I'm assuming that the problem is that you are trying to include the lazy collection in the response and because you have fetched it you have the exception.

I think in this scenario the best option is to eagerly fetch the lazy collections using the find method:
```
Fruit.find("select f from Fruit f left join fetch f.lazyCollection").list();
```

Where `lazyCollection` is the name of the field mapping the lazy association.

**Comment by MartinX3** [comment]
Same issue here.
I get a `Uni<List<User>>` response from the `find` function, but if I access it's `@ManyToMany List<Role>` I get this exception, so using `FetchType.EAGER` for now.

**Comment by Sanne** [comment]
@MartinX3 are you aware that lazy initialization requires an explicit invocation?
 - http://hibernate.org/reactive/documentation/1.0/reference/html_single/#_fetching_lazy_associations

My guess is that you didn't notice that; if that's not the case please share a test or some code we could look at.

**Comment by MartinX3** [comment]
Thank you for the link.
I should stop looking only at the quarkus guides and instead look into the root docs of the used technologies directly.
I just need to find a source how to use it with panache queries to run it on a single result.

**Comment by Sanne** [comment]
Thanks for confirming!
