### ISSUE TITLE
Quarkus 2.1.0.CR1: Hibernate Validator produces a warning when combined with Resteasy Reactive and Kotlin Coroutines

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#18783]
### Describe the bug

The combination of `Resteasy Reactive + Kotlin Coroutines + Hibernate Validator` leads to the following warning at compile time:
```kotlin
[WARNING] [io.quarkus.hibernate.validator.deployment] Hibernate Validator does not support constraints on static methods yet. Constraints on org.acme.ReactiveGreetingResource#java.lang.Object hello$suspendImpl(org.acme.ReactiveGreetingResource name, java.lang.String $completion, kotlin.coroutines.Continuation) are ignored.
```

### Expected behavior

No warning.

### How to Reproduce?

1. [Create a new quarkus project](https://code.quarkus.io/?e=kotlin&e=resteasy-reactive&e=hibernate-validator) with the dependencies: `Resteasy Reactive + Kotlin Coroutines + Hibernate Validator`
2. Update Quarkus to 2.1.0.CR1
3. Update Kotlin to 1.5.10
4. Create a suspend function

```kotlin
import org.hibernate.validator.constraints.Length
import org.jboss.resteasy.reactive.RestPath
import javax.validation.constraints.NotNull
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@Path("/")
class ReactiveGreetingResource {

    @Path("{name}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun hello(
        @RestPath("name") @NotNull @Length(max = 5) name: String,
    ) = "Hello RESTEasy Reactive"
}
```

### Quarkus version or git rev

2.1.0.CR1

**Comment by geoand** [comment]
Thanks for reporting!

https://github.com/quarkusio/quarkus/pull/18798 fixes the issue
