### ISSUE TITLE
Regression: Continuous testing does not detect new test classes

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18795]
### Describe the bug

Given having a Quarkus application running in DEV mode and with the continuous testing enabled, 
When we copy a test java class into the sources
Then the test should be detected and executed

Note that the above use case was working fine in 2.0.0.Final.

### How to Reproduce?

1. git clone `https://github.com/Sgitario/quarkus-test-suite`
2. cd quarkus-test-suite
3. git checkout reproducer_18795
4. cd http/http-minimum
5. run it using `mvn quarkus:dev`
6. Enable continuous testing (press r)
7. in another terminal, use: `cp src/test/resources/HelloResourceTest.java.template src/test/resources/HelloResourceTest.java`

The new HelloResourceTest should be detected but is not. This was working in previous versions.

**Comment by stuartwdouglas** [comment]
The 'cp' command in the reproducer is wrong (test/resources instead of test/java), but there is an issue here if the src/test/java dir does not exist when the app is launched. I have added this into https://github.com/quarkusio/quarkus/pull/18840 as they are related.

**Comment by Sgitario** [comment]
> The 'cp' command in the reproducer is wrong (test/resources instead of test/java), but there is an issue here if the src/test/java dir does not exist when the app is launched. I have added this into #18840 as they are related.

I wrote the cp command wrongly, my bad. Glad to know that this will be addressed though!
