### ISSUE TITLE
CLI ext add, list, remove are not registry aware

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#18799]
### Describe the bug

Currently the registry client needs to be explicitly enabled to resolve extension catalogs from registries. This option is available for `create` but not the rest of the commands such as `add`, `list` and `remove`.
Either we should switch to the registry client as the default source of extension catalog or we need to add the option to all the commands to enable it.

**Comment by ebullient** [comment]
One of the times I asked, I was told the registry client wasn't needed because the platform is already determined by the project. (That doesn't necessarily apply to listing extensions outside of a project context, but in that case you're also specifying a platform or stream explicitly)
