### ISSUE TITLE
Extensions should be sorted case insensitive

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/quarkus#18808]
**Describe the bug**
(Describe the problem clearly and concisely.)

Extensions are sorted with case sensitive, eg A..Za..z

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

They should be sorted regardless of case

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. https://code.quarkus.io/?extension-search=camel

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

See the screenshot

**Environment (please complete the following information):**
 - Browser: 
 - OS: 

**Additional context**
(Add any other context about the problem here.)

**Comment by ia3andy** [comment]
@davsclaus  would you provide a PR?
