### ISSUE TITLE
IntelliJ IDEA cannot compile language features of Java version greater than 8

### ISSUE THREAD

**Issue by rsynek** [quarkusio/quarkus#18812]
### Describe the bug

IntelliJ IDEA is unable to recognize newer Java language features in the Quarkus project. An example is using local variable type inference (`var anything = "anyValue";`) anywhere in the project.

Manually overriding the language level in Project Settings -> Modules does help only temporarily; IDEA updates these settings from the maven pom.xml.

This behavior is triggered by the `include-jdk-misc` profile coming from the `jboss-parent` pom.xml. For some reason, IDEA considers this profile active (although `mvn help:active-profiles` does not) and probably reads the compiler settings from the `release` config option of the `maven-compiler-plugin`:
`<release>8</release>`

### Expected behavior

Successful compilation in the IntelliJ IDEA.

### Actual behavior

Despite the fact that the project builds with Maven using language features from Java 10+, compilation in IntelliJ IDEA fails.

### How to Reproduce?

https://github.com/quarkusio/quarkus/pull/18809

Steps to reproduce:
1. See the draft PR above that illustrates Java 10 language feature.
2. Open Quarkus project in IntelliJ IDEA.
3. Open the changed file; IDEA informs that: Cannot resolve symbol 'var'.
4. Build the project in the IDE (Build -> Build Project); the build fails.
5. Navigate to Project Settings -> Modules and set the language level of the respective module to Java 11.
6. In the Maven tool window, click the "Reload all maven projects" button. The language feature is still unrecognized and the language level of the maven module returns to Java 8.

### Output of `java -version`

Java version: 11.0.10, vendor: AdoptOpenJDK

### Additional information

IntelliJ IDEA 2021.1.3 (Community Edition)
Build #IC-211.7628.21, built on June 29, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-59-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: Key Promoter X (2021.1.1), net.seesharpsoft.intellij.plugins.csv (2.17.1), EclipseCodeFormatter (20.8.203.000.0-Eclipse_2020-06-JavaOnly), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), org.asciidoctor.intellij.asciidoc (0.33.1)
Kotlin: 211-1.5.10-release-891-IJ7142.45
Current Desktop: ubuntu:GNOME

**Comment by geoand** [comment]
Indeed, OOTB IntelliJ fails, but https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#frequently-asked-questions mentions how to deal with the problem

**Comment by rsynek** [comment]
Thanks @geoand , it helps. Although I would argue it's not the best getting started experience for anyone who is not aware of this trick. I will file an issue with IntelliJ to hopefully get the root cause fixed.

**Comment by geoand** [comment]
👌

There has also been discussion of making some changes to our parent pom in order to get around the issue.
We'll see what happens
