### ISSUE TITLE
Avoid configuring `kafka.group.id` if no other Kafka configuration is present

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#18811]
### Description

Something that was observed in a Camel Quarkus [issue](https://github.com/apache/camel-quarkus/issues/2901) is that `KafkaRuntimeConfigProducer` will potentially always [add](https://github.com/quarkusio/quarkus/blob/4f8cf8b92db294cf8f4d625d95e0127f52d31437/extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRuntimeConfigProducer.java#L41-L43) config for `kafka.group.id`, regardless of whether any other Kafka configuration has been specified. It seems redundant in this case, so it'd be nice if it could be avoided.

### Implementation ideas

If the `result` map is empty - don't add `kafka.group.id`.

**Comment by cescoffier** [comment]
Make sense. The fix is trivial.
