### ISSUE TITLE
Reading config settings as Map doesn't work with Inheritance

### ISSUE THREAD

**Issue by nastra** [quarkusio/quarkus#18823]
### Describe the bug

```
    public interface ServerBase {
        Map<String, String> server();
    }

    @ConfigMapping(prefix = "maps.base")
    public interface MapsWithBase extends ServerBase {
        @Override
        Map<String, String> server();

        Map<String, Server> group();

        interface Server {
            String host();

            int port();
        }
    }

    @Inject
    MapsWithBase mapsWithBase;
```

Note that something like this works when reading config properties that aren't maps. I would expect this to work with Maps as well. I also created a test in https://github.com/quarkusio/quarkus/pull/18822 that reproduces this issue.

### Actual behavior

Config properties aren't being read when the same method name is in the parent class/interface

### How to Reproduce?

See test in https://github.com/quarkusio/quarkus/pull/18822

### Quarkus version or git rev

2.0.2.Final

**Comment by radcortez** [comment]
The issue is related with the method override you have from the base class to the inherited class. If you remove the override it works.

 I'll fix this, but I don't see a reason for an existing override. Can you please let me know your use case? Thanks!

**Comment by radcortez** [comment]
Requires https://github.com/smallrye/smallrye-config/pull/621.

**Comment by nastra** [comment]
> I'll fix this, but I don't see a reason for an existing override. Can you please let me know your use case? Thanks!

@radcortez thanks for fixing this. Our use case is: We define Base Config interfaces at a central place, which don't have any dependencies to Quarkus. Then we have a Quarkus-specific Config interface that extends this Base Config interface and just overrides the methods.
