### ISSUE TITLE
Guide/code.quarkus.io native image testing re-work

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#18820]
### Description

The Quarkus native image testing guide (https://quarkus.io/guides/getting-started-testing#native-executable-testing) says that `@NativeImageTest` is not yet deprecated but will be in the future and to use `@QuarkusIntegrationTest`.

If so, why does code.quarkus.io still generate projects using `@NativeImageTest` (& also the native image test extending the non-native base class).

**Comment by geoand** [comment]
cc @ia3andy

**Comment by ia3andy** [comment]
Good point, it's just a matter of updating the templates, we really need that done for the next release and backported to previous versions:

This is one of the templates to update (it needs to be done in java/kotlin/scala and also in resteasy-reactive):

https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java

**Comment by ia3andy** [comment]
@edeandrea are u up for a PR?

**Comment by edeandrea** [comment]
@ia3andy possibly. I'm just returning from a week's worth of PTO and have a ton of stuff to get through this week, so chances are it wouldn't be anything I could get to in the next week or 2.

**Comment by ia3andy** [comment]
@edeandrea thanks! no worries I'll have a look tomorrow..

**Comment by ia3andy** [comment]
the code generation tests (snapshots) will also need to be updated accordingly

**Comment by edeandrea** [comment]
Just wanted to give a gentle ping on this. Any updates? In addition to the test classes needing updating, the `pom.xml` would also need to be updated. Currently the failsafe plugin is only installed in the `native` profile. It would need to be moved into all profiles. like [here](https://github.com/edeandrea/quarkus-super-heroes/blob/main/rest-villains/pom.xml#L152-L170) (this project also has an [example integration test](https://github.com/edeandrea/quarkus-super-heroes/blob/main/rest-villains/src/test/java/io/quarkus/sample/superheroes/villain/rest/VillainResourceIT.java)).

**Comment by ia3andy** [comment]
@edeandrea I thought I did that one.. it must have slipped of my TODO list somehow.. do you want to provide a PR?

**Comment by edeandrea** [comment]
I don't know anything about how the templating or code.quarkus.io works nor how I would test any changes before I've committed anything. If its not too much work I could probably do a PR so long as you give me some starting points...

**Comment by edeandrea** [comment]
Looking at https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java - does it really belong in a directory called `native-test` if its now an integration test?

Would this be a much broader change? [This guide](https://quarkus.io/guides/building-native-image#testing-the-native-executable) would most likely need to be updated as well.

**Comment by ia3andy** [comment]
@edeandrea 
the pom is here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml#L164-L202

The tests are here:
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-reactive-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/scala/src/native-test/scala/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.scala
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-reactive-codestart/scala/src/native-test/scala/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.scala
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/kotlin/src/native-test/kotlin/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.kt
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-reactive-codestart/kotlin/src/native-test/kotlin/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.kt

**Comment by ia3andy** [comment]
First make the changes and then see what fails

**Comment by ia3andy** [comment]
> Looking at [`main`/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java](https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/resteasy-codestart/java/src/native-test/java/org/acme/Native%7Bresource.class-name%7DIT.tpl.qute.java?rgh-link-date=2021-12-07T13%3A09%3A03Z) - does it really belong in a directory called `native-test` if its now an integration test?
> 
> Would this be a much broader change? [This guide](https://quarkus.io/guides/building-native-image#testing-the-native-executable) would most likely need to be updated as well.

That's a good question, I think you can move them to the `test` directory we just need to make sure it's ok with gradle (cc @glefloch)

**Comment by ia3andy** [comment]
Yes I guess the guide also need to be udpated, but that could be a different PR..

**Comment by edeandrea** [comment]
@ia3andy I created a draft PR for this at #21997 

We can pick up the conversation over there.

**Comment by glefloch** [comment]
Moving those test in the test directory would result in IT test execution every time we run ˋgradle test` we should keep a separate source set (maybe ˋsrc/integration-test/java ˋ) at least for gradle ..
