### ISSUE TITLE
application.xml instead of application.properties

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#18831]
### Description

It would be great to be able to use XML (plus XSD validation :) instead of the properties file or yaml.
@radcortez 
----
//CC @brunoborges  :)

**Comment by radcortez** [comment]
I'll have a look.

**Comment by gsmet** [comment]
Is it really something we want? We already support two formats, I'm not sure a third one will serve us.

@geoand @stuartwdouglas WDYT?

**Comment by geoand** [comment]
I'm definitely not in favor of it, but I don't think I'll loose any sleep over it, as long as there is no runtime performance implications if I don't use it

**Comment by radcortez** [comment]
This can go to the quarkiverse config extensions: https://github.com/quarkiverse/quarkus-config-extensions.

**Comment by brunoborges** [comment]
I'd settle with TOML support instead of XML/XSD, simply because maintaining the XSD for this use case could be cumbersome.

**Comment by gsmet** [comment]
Well, question is what does it bring vs how much effort will it be to maintain one more format. I personally have no strong opinion about this but we need to be careful as long term maintenance has a cost for anything we do.

**Comment by brunoborges** [comment]
If you support YAML already, then supporting TOML is a matter of adding an if statement somewhere where "if it is TOML, use this Jackson library to convert it to JSON Object".

**Comment by gsmet** [comment]
No it's not. We would need a specific extension for it as we don't want to bring the TOML data format dependency if we don't need it.

**Comment by geoand** [comment]
Furthermore, I don't think we even rely on Jackson for YAML support (although I didn't check this)

**Comment by gsmet** [comment]
BTW, I'm -1 for XML, +0 for TOML as several users asked for it IIRC.

**Comment by stuartwdouglas** [comment]
I am -1 for XML. If a user wants it as a quarkiverse extension and is prepared to maintain it then that is fine, but I don't think we should be spending any time on it.

I also don't know how you would go about mapping all our config to an XSD.

**Comment by radcortez** [comment]
We did the work to support TOML in SR Config, but we never merged it because recently we didn't have people asking for it, so we didn't worry about it: https://github.com/smallrye/smallrye-config/pull/497

**Comment by mschorsch** [comment]
TOML support woule be great 😃

**Comment by gastaldi** [comment]
Looks like the XML idea was shot down with the (strong) arguments above. I'm closing this issue. Please follow smallrye/smallrye-config#497 or open an issue in https://github.com/quarkiverse/quarkus-config-extensions requesting (or providing a PR).

Thanks!
