### ISSUE TITLE
Quarkus 2.0 mongodb with devServices option

### ISSUE THREAD

**Issue by Srinivasa-Cana** [quarkusio/quarkus#18830]
### Description

I have quarkus2.0 application running with mongodb database.

To run my tests, I am depending on devServices option if I am not configuring quarkus.mongodb.connection-string for test profile Quarkus will start mongod docker container for tests.

Issue I have how to pass mongodb connection string options (ex: uuidRepresentation=standard). I am using uuidRepresentation=standard option for application.

Connection-String format as per below:

mongodb://username:password@localhost:27017/dbname?authSource=admin&uuidRepresentation=standard

**Note** : Without above functionality using mongodb 4.0 driver with  quarkus 2.0  un-useful.  Because  default driver comes with UuidRepresentation.UNSPECIFIED value.  Pls  consider as high priority for this request.

Open this request based on comment on stackover flow comment.
 
[Issue Comment on StackOver Flow](https://stackoverflow.com/questions/68416449/quarkus-2-0-mongodb-with-devservices-option)

### Implementation ideas

you can provide Connection-String options as separate configuration parameter. 

Provide Connection-String-Options or  Connection-String-Override-Options  as another configuration parameter.

Or 

should able to configure  Connection-String as per below

Connection-String=mongodb://?authSource=admin&uuidRepresentation=standard

**Note:** with out host, port and user name and password. so that devServices it will start new mongodb container and create actual url before setting MongoClientSettings.

As per mongodb documentation  Host name is mandatory. So I will prefer my first option.

**Comment by evanchooly** [comment]
honestly, the connection string used by dev services should include that by default.  I've yet to run across anyone *not* using the standard UUID representation.  Fixing that is a simpler fix as dev services assumes no user defined connection string, iirc.

**Comment by Srinivasa-Cana** [comment]
Configure default works for me (Since it is new DB). 

if any user using it old mongodb server which is having  JAVA_LEGACY implementation in their DB? How we are going to support that.  May be very less people right now for this option :)

**Comment by gsmet** [comment]
I think we should add `properties`similar to what we have in the datasource support here: https://github.com/quarkusio/quarkus/blob/main/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DevServicesBuildTimeConfig.java#L35

**Comment by geoand** [comment]
I agree with @gsmet, we should be consistent with this. I'll open a PR soon
