### ISSUE TITLE
Re-enable TokenUtilsEncryptTest#testFailAlgorithm on Java 17+

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#18833]
### Description

Because of some algorithm problem, that test (in `tcks/microprofile-jwt`) fails on Java 17 and was thus disabled: #18790

The goal is to re-enable that test (probably after some upstream update).

See also:
- https://bugs.openjdk.java.net/browse/JDK-8248268
- https://bitbucket.org/b_c/jose4j/issues/189
- #18372

/cc @sberyozkin

**Comment by b---c** [comment]
FWIW https://bitbucket.org/b_c/jose4j/issues/189 has been fixed with v0.7.9 https://bitbucket.org/b_c/jose4j/wiki/Release%20Notes#!jose4j-079-august-18-2021

**Comment by famod** [comment]
Thanks for the pointer @b---c!

/cc @sberyozkin but I suppose you're already aware.

**Comment by sberyozkin** [comment]
Thanks @b---c :-)

@famod, indeed I saw a fix from Brian.

Here is a smallrye-jwt update:
https://github.com/smallrye/smallrye-jwt/pull/491

I'll update Quarkus once it is released

**Comment by famod** [comment]
@sberyozkin I see smallrye-jwt was released recently and Java 17 will be released tomorrow, so time to bump smallrye-jwt? 🙂
