### ISSUE TITLE
@QuarkusCucumberTest

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#18846]
### Description

Description Cucumber is the most used tool for BDD testing and it supports Junit5, the problem is that the support for Junit 5 is using the Test engine instead the junit extensions. It would be great to have @QuarkusCucumberTest that take care of this problem

Implementation ideas I think that something like https://github.com/cucumber/cucumber-jvm/tree/main/spring could be implemented

https://gitmemory.com/issue/quarkusio/quarkus/11045/747799983

@Stua

**Comment by geoand** [comment]
I'll close this as a duplicate of https://github.com/quarkusio/quarkus/issues/11045 since that issue has a lot of discussion
