### ISSUE TITLE
Breaking change when upgrading Quarkus to 2.1

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18842]
### Describe the bug

Given:

```java
@ConfigMapping(prefix = "authN")
public interface AuthNConfig {
    @WithName("tokenLiveSpanMin")
    int liveSpan();
}
```

The property was being mapped from:

```
authN.token-live-span-min=10
```

This was working fine prior to 2.1 (unreleased yet). However, in 2.1, we upgraded Smallrye Config to 2.4.2 in https://github.com/quarkusio/quarkus/pull/18629 which contains this change https://github.com/smallrye/smallrye-config/pull/613.

From my understanding, the Smallrye Config change is to correctly apply the `@WithName` annotation which means that the way that was previously mapping the property was wrong (authN.token-live-span-min should not be mapped to tokenLiveSpanMin).

If this is done on purpose, this is a breaking change that should be noted in the migration guide in Quarkus 2.1.

**Comment by Sgitario** [comment]
Adding @radcortez for clarification

**Comment by geoand** [comment]
If this is indeed the case, we will need an entry in the migration guide

**Comment by radcortez** [comment]
Before the SmallRye Config fix, the `@WithName` was wrongly applying the naming strategy when it was intended to be an exact match of the annotation, so the current behavior is the expected one.

I don't consider this a breaking change, because it was a bug.

**Comment by geoand** [comment]
OK, but we at least need to give users a notice in the migration guide, that what they might have had working before will stop working now

**Comment by radcortez** [comment]
Ok, added: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1#config

So, nothing do to here I believe. I'll close the issue.
