### ISSUE TITLE
DevServices datasource property name is quite generic

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#18844]
### Describe the bug

`quarkus.datasource.devservices` should be renamed to `quarkus.datasource.devservices.enabled` as other devServices as `quarkus.kafka.devservices.enabled`

### Expected behavior

Disable datasource DevServices by this property -> `quarkus.datasource.devservices.enabled` 

### Actual behavior

Disable datasource DevServices by this property -> `quarkus.datasource.devservices` 

### Output of `uname -a` or `ver`

dev or test mode

### Quarkus version or git rev

upstream

**Comment by geoand** [comment]
I think we do the same thing in Mongo. 
I am +1 for this (we should be consistent in any case, whichever way we go down), but it would be a breaking change.

cc @gsmet

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/18847 .

I think we should include it in 2.1 to remove the deprecated one before we release 2.2.
