### ISSUE TITLE
Access to DevService properties in QuarkusIntegrationTest

### ISSUE THREAD

**Issue by bdevreugd-vialis** [quarkusio/quarkus#18854]
I have a quarkus integration test, which uses the devservices of Mongodb and Kafka. I can see the properties being passed to my docker image, so that gets started with the correct details.

However, I would also like to access those services from my test (to add 'input' messages  to kafka and to verify data written to the DB), but it is currently impossible to determine the correct connection details.

Could the properties from the following line, somehow, also made available in the context of the integration test. For example using `ConfigProvider.getConfig().getValue` or simply using `@ConfigProperty`, or anything else.

https://github.com/quarkusio/quarkus/blob/c10b430e039d0c2dcbe5607320a06d5aecfe49be/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java#L105

**Comment by geoand** [comment]
This is very interesting.

We can certainly inject some kind of dev-services configuration lookup service into the test that users could query.

@gsmet @stuartwdouglas WDYT?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18862 is what I have in mind

**Comment by languitar** [comment]
Is there a quick workaround to access these properties in the current release version?

**Comment by geoand** [comment]
Unfortunately, no

**Comment by stuartwdouglas** [comment]
Maybe we should provide a way to inject these clients into QuarkusIntegrationTest.

**Comment by geoand** [comment]
So injecting a data source for example?
That sounds neat, but I am wondering what we would inject in the case of Keycloak or Apicurio

**Comment by languitar** [comment]
Having easy access to the database and messaging systems etc. would be really good. Providing fixtures in terms of data inside integration tests is currently not exactly easy, especially with DevServices. Giving clients back to the test would really help. Being able to programmatically use entities to prefill the database would also be very nice.
