### ISSUE TITLE
Disabling Dev Services For Keycloak causes a template exception due to a strict rendering

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#18853]
### Describe the bug

Adding `quarkus.keycloak.devservices.enabled=false` to `application.proiperties` and starting with `quarkus:dev` and with `quarkus-oidc` included causes a template exception since the Dev UI templates shipped with `quarkus-oidc` check various properties created by the KC dev services processor which starts a container. I've spotted this problem after trying to accelerate the smote test (and not to start a container).

This is a problem since the plan is to also  have the custom non KC Dev UI supported OOB, #18427, which would require setting `quarkus.keycloak.devservices.enabled=false`. Also we will encourage to provide a custom Dev UI support for other providers.

I'll try to produce empty/null properties from the KC dev services processor if it is disabled. If that does not work then I believe the strict rendering for Dev UI should be switched off

CC @stuartwdouglas @mkouba @phillip-kruger

**Comment by mkouba** [comment]
@sberyozkin What does the template exception look like? What's the problematic expression? We should be able to fix it...

**Comment by sberyozkin** [comment]
Hey Martin, yeah, hope so, going to try now that I've got my coffee :-), it is:
```
io.quarkus.qute.TemplateException: Property not found in expression {info:keycloakUrl} in template io.quarkus.quarkus-oidc/provider on line 185
```
(and I expect a few more would happen for the other properties) - so I'll register these properties as null values and it should do it

**Comment by mkouba** [comment]
You don't need to pass `null` but use a safe expression instead: `{info:keycloakUrl??}` (as described in the [docs](https://quarkus.io/version/main/guides/qute-reference#strict-rendering)) However, I'm not quite sure it would be a good UX in this particular case because you would render a link with empty `href`.

**Comment by sberyozkin** [comment]
@mkouba 
> You don't need to pass null but use a safe expression instead: {info:keycloakUrl??} (as described in the docs) 
Cool, I should've read your comment before modifying the code :-)
> However, I'm not quite sure it would be a good UX in this particular case because you would render a link with empty href.
Dev UI OIDC Card will not link to this template if `keycloakUrl` is not available:
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/resources/dev-templates/embedded.html

There, if no external devservices provided, and no `keycloakUrl` is set then the default OIDC template will be included (in the currently empty branch). 
So the Keycloak template will not be visible

**Comment by sberyozkin** [comment]
Hi Martin, @mkouba 

I've only added
```
{#if info:keycloakUrl}
<div class="float-right">
    <a href="{info:keycloakUrl}" target="_blank" class="btn btn-link" title="Log into Keycloak to Configure Realms">
       <i class="fas fa-key"></i> Keycloak Admin
    </a>
</div>
{/if}
```

and it worked - nothing else had to be changed - I could've guessed it, sorry, but I've also learned about a `??` expression :-)

**Comment by mkouba** [comment]
Hmm, the `{#if info:keycloakUrl}` should fail in the same way; `{#if info:keycloakUrl??}` is the "safe" version. But if it works then OK ;-).

**Comment by sberyozkin** [comment]
@mkouba Sure, I'll add a few top level safe expressions as well just in case
