### ISSUE TITLE
Cli jbang install options won’t always work

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18879]
I noticed we have this in cli docs:

`curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio`

This will complete but if you don't have jbang setup already on path the `quarkus` command won't be on path. 

We could consider that a bug in jbang but for now reliable steps is to install jbang first then quarkus. 

`curl -Ls https://sh.jbang.dev | bash -s - app setup && jbang app install --fresh --force quarkus@quarkusio`

Similar in the power shell section. Setup jbang first then install quarkus.

**Comment by maxandersen** [comment]
@ebullient @aloubyansky

**Comment by n1hility** [comment]
@maxandersen that doesn't seem to fix it for me. It seems the issue is that jbang only edits .bashrc and not .bash_profile on my system.

**Comment by maxandersen** [comment]
Doh. You are probably right. 

https://github.com/jbangdev/jbang/issues/930 

Issue is OS X built in terminal behaves differently than anything else. 

@quintesse you got a chance to make a pr for that ?

**Comment by quintesse** [comment]
@maxandersen sure, but you'll have to test it, no Mac here :-)

See jbangdev/jbang#966

**Comment by maxandersen** [comment]
issue is not correct. no matter what option you take you need to restart/refresh your shell to have quarkus in the path after this (unless you already have jbang installed).
