### ISSUE TITLE
Quarkus as Gradle Kotlin sub-project fail

### ISSUE THREAD

**Issue by Solido** [quarkusio/quarkus#18874]
### Describe the bug

Created a parent project and adding sub-projects.
As long as Quarkus as Kotlin is not added everything compile.

Independently Quarkus gradle task is working too but failed when added as sub-project.

### Expected behavior

Can add Quarkus Kotlin Gradle as a sub-project.

### Actual behavior

Any gradle command fail with

```
Plugin [id: 'io.quarkus'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
...
```

### How to Reproduce?

1. Create an empty kotlin gradle project
2. Add a quarkus kotlin as sub-project
3. Configure settings.gradle.kts add` include ("quarkus-prj")`

### Output of `uname -a` or `ver`

Win 10 up to date

### Output of `java -version`

adopt-openjdk-15.0.2

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1 

### Additional information

Kotlin build.gradle.kts

**Comment by glefloch** [comment]
Thanks for reporting this @Solido. Are you using the Gradle kotlin DSL or not? I'm trying to reproduce the issue.

**Comment by Solido** [comment]
Bonjour Guillaume !
Yes this is a full kotlin solution

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
