### ISSUE TITLE
Regression: Continuous testing does not detect new test classes after changing sources

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18883]
### Describe the bug

This issue is similar to https://github.com/quarkusio/quarkus/issues/18795 (that has been already fixed), but happens after updating some existing sources.

Given having a Quarkus application running in DEV mode and with the continuous testing enabled, 
When we update an existing source
And we copy a test java class into the sources
Then the test should be detected and executed

After updating the existing code and copy the test java class, we got the next traces:

```
10:38:48.999 INFO  [app] __  ____  __  _____   ___  __ ____  ______ 
10:38:49.000 INFO  [app]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
10:38:49.000 INFO  [app]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
10:38:49.000 INFO  [app] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
10:38:49.001 INFO  [app] 10:38:45,530 test-http 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.271s. Listening on: http://localhost:27001
10:38:49.001 INFO  [app] 10:38:45,530 Profile DevModeHttpMinimumIT activated. Live Coding activated.
10:38:49.001 INFO  [app] 10:38:45,531 Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation]
10:38:49.002 INFO  [app] 10:38:45,531 Live reload total time: 0.607s 
10:38:53.003 INFO  [app] Running tests for the first time
10:38:53.004 INFO  [app] Press [h] for more options>
10:38:53.005 INFO  [app] Press [r] to re-run, [h] for more options>
10:38:53.005 INFO  [app] No tests found
10:38:53.006 INFO  [app] 10:38:49,798 Not re-running failed tests, as all tests passed
```

I think the problem could be around the `Not re-running failed tests, as all tests passed` log message.

### How to Reproduce?

1. git clone `https://github.com/Sgitario/quarkus-test-suite`
2. cd quarkus-test-suite
3. git checkout reproducer_18883
4. cd http/http-minimum
5. run the test `mvn clean verify -Dit.test=DevModeHttpMinimumIT#shouldDetectNewTestsAfterMakingChanges`

The test is failing and it should pass.

**Comment by stuartwdouglas** [comment]
I just see it hanging:

```
"main" #1 prio=5 os_prio=0 cpu=2165.21ms elapsed=45.04s tid=0x00007fb5d0028800 nid=0x5a1ab waiting for monitor entry  [0x00007fb5d7373000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:957)
	- waiting to lock <0x000000044f3d5ef8> (a com.gargoylesoftware.htmlunit.html.HtmlPage)
	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:898)
	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:879)
	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:860)
	at io.quarkus.test.bootstrap.DevModeQuarkusService.clickOnElement(DevModeQuarkusService.java:89)
	at io.quarkus.test.bootstrap.DevModeQuarkusService$$Lambda$706/0x0000000800869440.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11.0.11/ArrayList.java:1541)
	at io.quarkus.test.bootstrap.DevModeQuarkusService.enableContinuousTesting(DevModeQuarkusService.java:41)
```

**Comment by Sgitario** [comment]
> I just see it hanging:
> 
> ```
> "main" #1 prio=5 os_prio=0 cpu=2165.21ms elapsed=45.04s tid=0x00007fb5d0028800 nid=0x5a1ab waiting for monitor entry  [0x00007fb5d7373000]
>    java.lang.Thread.State: BLOCKED (on object monitor)
> 	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:957)
> 	- waiting to lock <0x000000044f3d5ef8> (a com.gargoylesoftware.htmlunit.html.HtmlPage)
> 	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:898)
> 	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:879)
> 	at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:860)
> 	at io.quarkus.test.bootstrap.DevModeQuarkusService.clickOnElement(DevModeQuarkusService.java:89)
> 	at io.quarkus.test.bootstrap.DevModeQuarkusService$$Lambda$706/0x0000000800869440.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(java.base@11.0.11/ArrayList.java:1541)
> 	at io.quarkus.test.bootstrap.DevModeQuarkusService.enableContinuousTesting(DevModeQuarkusService.java:41)
> ```

Thanks for your reply @stuartwdouglas . I've found the issue (not in Quarkus). Closing.
