### ISSUE TITLE
Regression: CLI newly created app does not start on DEV mode

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18884]
### Describe the bug

Having installed the latest Quarkus CLI using 999-SNAPSHOT
When create a new application: `quarkus create app my-app`
And run on dev mode: `quarkus dev` or `mvn quarkus:dev`

Neither way works to run on DEV mode because of:
```
[INFO] Nothing to compile - all classes are up to date
[WARNING] The quarkus-maven-plugin build goal was not configured for this project, skipping quarkus:dev as this is assumed to be a support library. If you want to run quarkus dev on this project make sure the quarkus-maven-plugin is configured with a build goal.
```

The `pom.xml` does contain the `quarkus-maven-plugin`:

```xml
<build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
...
```

The problem is that the property `quarkus.platform.group-id` has `io.quarkus.platform`. Using `io.quarkus` makes it work.

### Quarkus version or git rev

999-SNAPSHOT (fa6cd08debd7bbac3fb41a94d95b12cda032996a)

**Comment by aloubyansky** [comment]
This should be fixed with https://github.com/quarkusio/quarkus/pull/18813

**Comment by Sgitario** [comment]
> This should be fixed with #18813

I built Quarkus upstream by myself locally today (including the commit you mention) and didn't work for me...

**Comment by aloubyansky** [comment]
Yes, this means the CLI version is 999-SNAPSHOT. But now that the registry client is enabled, the project it generates is the one recommended by the registry.quarkus.io. Which is currently 2.0.2.Final. And this what you were trying to launch with quarkus:dev. Changing the plugin's groupId to `io.quarkus` in the generated project will fix it.

**Comment by Sgitario** [comment]
> Yes, this means the CLI version is 999-SNAPSHOT. But now that the registry client is enabled, the project it generates is the one recommended by the registry.quarkus.io. Which is currently 2.0.2.Final. And this what you were trying to launch with quarkus:dev. Changing the plugin's groupId to `io.quarkus` in the generated project will fix it.

Thanks for the clarifications!
