### ISSUE TITLE
Integrate Hibernate Validator with Hibernate ORM

### ISSUE THREAD

**Issue by anadollu** [quarkusio/quarkus#1889]
Normally we expect that a field defined in the Entity class like below

`
@Size(max=100)
@NotEmpty
@Column
private String name;
`

to be generated like that  

`name varchar(100) not null`

but currently hibernate ignores these validation annotations and generates 

`name varchar(255)`

unless we define all constraints with the @Column annotation.

**Comment by gsmet** [comment]
This is more or less expected, we still haven't linked ORM and Validator. Will prioritize it a bit more then!

**Comment by machi1990** [comment]
I'll take a look at this. 

Thanks @gsmet for the inputs.
