### ISSUE TITLE
DefaultBean with generics cannot be overridden for specific type

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#18903]
### Describe the bug

Given the following example kotlin code:

```kotlin
@Dependent
class DefaultOutboxConfiguration {
    @Produces
    @DefaultBean
    fun <EventType> catchAllSerializer(): EventSerializer<EventType> = throw RuntimeException("must not be called")

    @Produces
    fun <EventType> outbox(
        repo: PersistedEventRepository,
        serializer: EventSerializer<EventType>,
    ): TransactionalOutbox<EventType> = PanacheTransactionalOutbox(repo)
}

@Dependent
class CustomOutbox {
    @Produces
    fun stringSerializer(): EventSerializer<String> = StubEventSerializer()
}

@Dependent
class TestOutboxInjection {
    fun second(@Observes event: StartupEvent, outbox: TransactionalOutbox<String>) {}
}
```

### Expected behavior

`stringSerialize` should be used and the application does not end in a RuntimeException

### Actual behavior

`catchAllSerializer` is used.

I would also be happy to drop `catchAllSerializer` completely but in that case resolution fails.

### How to Reproduce?

This only seems to happen in case the produced beans stem from an external library with a Jandex index. An inline test case did not show this error.

### Output of `uname -a` or `ver`

Linux pres 5.10.50-1-lts #1 SMP Wed, 14 Jul 2021 15:15:15 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9) OpenJDK 64-Bit Server VM (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by mkouba** [comment]
@languitar would you care to prepare a minimal reproducer app? It would be really helpful to simplify the snippet...
