### ISSUE TITLE
quarkus-smallrye-openapi property quarkus.smallrye-openapi.operation-id-strategy doesn't work

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#18900]
### Describe the bug

The `quarkus.smallrye-openapi.operation-id-strategy` property provided by the `quarkus-smallrye-openapi` extension doesn't seem to work.

### Expected behavior

In my `application.properties` file if I set  `mp.openapi.extensions.smallrye.operationIdStrategy=METHOD`, when I download the openapi document I do see the `operationId` element in each section

### Actual behavior

In my `application.properties` file if I set `quarkus.smallrye-openapi.operation-id-strategy=method` (or `quarkus.smallrye-openapi.operation-id-strategy=METHOD`), when I download the openapi document I do not see the `operationId` element in each section.

### How to Reproduce?

Follow the guide at https://quarkus.io/guides/openapi-swaggerui and set `quarkus.smallrye-openapi.operation-id-strategy=method` in `application.properties`, then navigate to http://localhost:8080/q/openapi to download the openapi document. The `operationId` element for each operation is missing, whereas if you set `mp.openapi.extensions.smallrye.operationIdStrategy=METHOD` it is present.

**Comment by geoand** [comment]
I wonder if the problem is that we use `operationIdStrategy` as the suffix when setting the system property instead of `operation-id-strategy`

**Comment by phillip-kruger** [comment]
@edeandrea - The Guide (https://quarkus.io/guides/openapi-swaggerui#auto-generation-of-operation-id) does say that it should be set as `mp.openapi.extensions.smallrye.operationIdStrategy=METHOD`

This is a MicroProfile Property (that we have not mapped to quarkus)

**Comment by phillip-kruger** [comment]
Wait, we did. And that is the problem right ?
https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.operation-id-strategy

Ok I will have a look

**Comment by phillip-kruger** [comment]
What version of Quarkus  are you using ?

**Comment by geoand** [comment]
> Wait, we did. And that is the problem right ?
> https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.operation-id-strategy
> 
> Ok I will have a look

Exactly: https://github.com/quarkusio/quarkus/blob/2.1.0.CR1/extensions/smallrye-openapi-common/deployment/src/main/java/io/quarkus/smallrye/openapi/common/deployment/SmallRyeOpenApiConfig.java#L159

**Comment by edeandrea** [comment]
2.0.2.Final

**Comment by phillip-kruger** [comment]
Thanks. I'll have a look a.s.a.p

**Comment by edeandrea** [comment]
> I wonder if the problem is that we use `operationIdStrategy` as the suffix when setting the system property instead of `operation-id-strategy`.
> 
> If so, the same would go for other properties, like `termsOfService`. @edeandrea can you try setting `quarkus.smallrye-openapi.terms-of-service`?

@geoand I'll try this in a bit and report back

**Comment by geoand** [comment]
@phillip-kruger I found another issue with how the mapping is done. I will send a PR that will likely conflict with whatever fix you come up with, so I'll just rebase it when you are done.

**Comment by phillip-kruger** [comment]
@geoand :
I am planning to move to `RelocateConfigSourceInterceptor` now that it's available. Like we have done for GraphQL: https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLConfigMapping.java

**Comment by geoand** [comment]
Excellent. Then that will fix the issue I found as well :)

**Comment by edeandrea** [comment]
I wish the browser didn't prompt me to download the openapi...i guess that's because its in yaml format and not json?

@geoand setting `quarkus.smallrye-openapi.terms-of-service=blah` does not seem to work.

**Comment by geoand** [comment]
> @geoand setting `quarkus.smallrye-openapi.terms-of-service=blah` does not seem to work.

OK, thanks

**Comment by phillip-kruger** [comment]
@edeandrea - Above PR will fix the issue, I also added a test case for all mappings to make sure this says in tack. Thanks :)

**Comment by edeandrea** [comment]
@phillip-kruger Thanks for taking care of this so quickly! Any idea what Quarkus version we might see this? 2.0.x? 2.1.x?

**Comment by phillip-kruger** [comment]
We should be able to backport this, so I'll add the `backport` label. I think that means we should see it in 2.1.1 (as we already missed 2.1.0)

**Comment by edeandrea** [comment]
No chance of a 2.0.x?

**Comment by geoand** [comment]
I would say 0️⃣ . We don't maintain multiple streams. Once `2.1.x` is out, it's the end of `2.0.x`

**Comment by phillip-kruger** [comment]
I am also not sure if there will be another 2.0.x release....

**Comment by edeandrea** [comment]
But 2.1 isn't out :)

**Comment by geoand** [comment]
You think 😉
