### ISSUE TITLE
WWW-Authenticate Header missing

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#1893]
Given a protected method in a JAX-RS resource:

    @GET
    @Produces(MediaType.TEXT_HTML)
    @RolesAllowed("user-monitor")
    public String returnBootstrapHTML() {
...

and Elytron configured to use the embedded Auth:

    quarkus.security.embedded.enabled=true
    ...
    ...
    ...
    quarkus.security.embedded.auth-mechanism=BASIC

the curl request doesn't receive the correct header "WWW-Authenticate" that start the http challenge:

curl -v http://localhost:8080/gestione-ordini-bar
	*   Trying ::1...
	* TCP_NODELAY set
	* Connected to localhost (::1) port 8080 (#0)
	> GET /gestione-ordini-bar HTTP/1.1
	> Host: localhost:8080
	> User-Agent: curl/7.54.0
	> Accept: */*
	> 
	< HTTP/1.1 401 Unauthorized
	< Connection: keep-alive
	< Content-Type: text/html;charset=UTF-8
	< Content-Length: 14
	< Date: Fri, 05 Apr 2019 14:59:18 GMT
	< 
	* Connection #0 to host localhost left intact

**Comment by masini** [comment]
The problem is that Undertow doesn't challenge until setAuthenticationRequired is triggered.

But this is not triggered untile there a SecurityConstraint.

So I added this single line:

```java
        d.addSecurityConstraint(
                new SecurityConstraint().setEmptyRoleSemantic(SecurityInfo.EmptyRoleSemantic.AUTHENTICATE)
                        .addWebResourceCollection(new WebResourceCollection().addUrlPattern("/*")));

```
to "UndertowDeploymentTemplate" and now it works.

From my understanding of how it works, this mean that everyone must be authenticated so doesn't work for anonymous.

May be during template building can check given a property that tells what to do for empty roles, so that we can choose between PERMIT, DENY, AUTHENTICATE.

**Comment by stuartwdouglas** [comment]
@starksm64 it does not look like we have any tests for basic auth? 

The issue here is that because the check is happening at the JAX-RS level it is already past the Undertow security layer. By default Undertow will attempt to authenticate via basic auth if the headers are present, however it will not issue a challenge unless it knows (generally via a security constraint) that auth is required.

I am not sure about the cleanest way to fix this, one way is to simply get hold of the current ServletRequestContext and call HttpServletRequest.authenticate().

Another more generic possibility might be to install an Undertow commit listener that checks for a 401 response and instead attempts to authenticate.

**Comment by masini** [comment]
Other servers that use Undertow like Wildfly or Thorntail use the web.xml approach also for JAX-RS.

You put a constraint inside web.xml and the challenge start.

Do you think in Quarkus this approach cannot be used ?

**Comment by ggam** [comment]
Do you have a roadmap for this issue? The security guide (https://quarkus.io/guides/security-guide) examples don't work because of this issue, which is very annoying. I'm using @masini's code snippet as a workaround.

**Comment by flo-ryan** [comment]
+1 for this issue

@masini how did you add that line? thanks

**Comment by mazegreg** [comment]
+1
Any release planned?

**Comment by mazegreg** [comment]
@ggam In which file / line from which undertow version did you add this workaround? And then , how did you manage to use the recompiled lib?

**Comment by ggam** [comment]
If I remember correctly I just put a security constraint on the web.xml

Let me know if it doesn't work and I'll search the test project I did it to
verify.

**Comment by gsmet** [comment]
@sberyozkin could you please have a look to this one? It looks like a bug and maybe not one hard to fix and we have quite a few people asking for it.

Thanks!

**Comment by mazegreg** [comment]
@ggam 
> If I remember correctly I just put a security constraint on the web.xml Let me know if it doesn't work and I'll search the test project I did it to verify. 

Yes please, if you could post your project so that I can see how you arranged the files & contents, it would be grateful! I've tried many combinations and can't find a simple a-z tutorial for getting it work.

Thanks,
Grégoire

**Comment by ggam** [comment]
@mazegreg I don't find the project but you should just need to add the following to the web.xml file:

```
<security-constraint>
    <web-resource-collection>
        <web-resource-name>Quarkus</web-resource-name>
        <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <auth-constraint>
        <role-name>**</role-name>
    </auth-constraint>
</security-constraint>
```

Where /* is the pattern you want to protect and ** role means "authentication required, with no specific role".

**Comment by mazegreg** [comment]
Thank you @stuartwdouglas for your commit.
I've copied your code and compiled the extension resteasy on my side. Now, if I want to try it on one of my projects, would copy/pasting the ouput quarkus-resteasy-999-SNAPSHOT.jar file to my target directory be sufficient to see the pop up appear?

**Comment by stuartwdouglas** [comment]
It should, as this change does not affect any deployment time code.

**Comment by stuartwdouglas** [comment]
Actually there are likely many incompatibilities between 999-SNAPSHOT and whatever version you are using, so it likely won't work.

**Comment by t-shaguy** [comment]
> The problem is that Undertow doesn't challenge until setAuthenticationRequired is triggered.
> 
> But this is not triggered until there is a SecurityConstraint.
> 
> So I added this single line:
> 
> ```java
>         d.addSecurityConstraint(
>                 new SecurityConstraint().setEmptyRoleSemantic(SecurityInfo.EmptyRoleSemantic.AUTHENTICATE)
>                         .addWebResourceCollection(new WebResourceCollection().addUrlPattern("/*")));
> ```
> 
> to "UndertowDeploymentTemplate" and now it works.
> 
> From my understanding of how it works, this mean that everyone must be authenticated so doesn't work for anonymous.
> 
> May be during template building can check given a property that tells what to do for empty roles, so that we can choose between PERMIT, DENY, AUTHENTICATE.

@masini, pls can you through more light on how to add this on what object is this done? I have this error pop on on 1.12 and 2.92 amazingly it has always worked before now, adding this quarkus.HTTP.auth.proactive=false doesn't help matters. Thank you and looking forward.
