### ISSUE TITLE
Should start a single Vertx instance, or guarantee unique thread names

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#18942]
### Describe the bug

When starting Quarkus in dev mode, there are two independent Vert.x engined started:
 
1. One by `VertxCoreRecorder#initialize` triggered by `ResteasyStandaloneRecorder`
2. One by `DevConsoleProcessor#initializeVirtual`.

This doesn't seem efficient (is it necessary?) and is extremely confusing, as both instances are starting threads which have overlapping names; so for example I now have two different copies of `vert.x-eventloop-thread-0`, making it puzzling to resolve some of the memory leaks.

### Expected behavior

Ideally, start a single vert.x. (Is the second start by design @stuartwdouglas , @FroMage  ?)

If that's not possible, let's try at least to have them produce unambiguous thread names.

### Quarkus version or git rev

`cf73c98c5b`

**Comment by stuartwdouglas** [comment]
The additional Vert.x runs on the -deployment side, and is loaded by a different ClassLoader.

Basically this is how you can invoke functions in the -deployment part of Quarkus from a HTTP request handled by the runtime part, a virtual channel proxies the request to the vert.x instance in -deployment.

**Comment by stuartwdouglas** [comment]
It does not look like there is any way to change the thread names.

**Comment by Sanne** [comment]
Thanks for the explanation! I have a fix which seems to work fine.
