### ISSUE TITLE
Vulnerability in netty-codec 4.1.65

### ISSUE THREAD

**Issue by hamburml** [quarkusio/quarkus#18962]
Our nexusIQ shows a violation in netty-codec.
The version 4.1.66.Final has none.

Issue: SONATYPE-2021-0789

**Comment by sberyozkin** [comment]
@hamburml Can you please send an email with more details to security@quarkus.io ? I'm not allowed to view that issue, thanks

**Comment by geoand** [comment]
cc @jviet as we bring in Netty as a transitive dependency of Vert.x

**Comment by re-thc** [comment]
https://github.com/netty/netty/pull/11429 is the related issue. Might not be relevant if not using LZ4 but nevertheless.

**Comment by vietj** [comment]
@re-thc thanks, indeed it is not relevant, only users that are using LZ4, we'll upgrade anyway :-)

**Comment by hamburml** [comment]
Any news?
