### ISSUE TITLE
Alternate pom.xml ignored in Quarkus Dev mode and Tests if not specified with an absolute path

### ISSUE THREAD

**Issue by garyhodgson** [quarkusio/quarkus#18981]
### Describe the bug

Whilst investigating #18980 I encountered the problem that tests and dev mode do not seem to use the alternate pom when using the maven `-f` flag.

I attempted to use the flattened pom file generated by the [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin), but this resulted in the same exceptions.

After further investigation I found out that the alternate pom seems to be ignored if the original pom.xml remains in the base directory.  Temporarily deleting the pom.xml results in the tests passing and the app successfully starting in dev mode.

As I was writing up this issue I noticed in [BootstrapMavenContext.getPomForDirOrNull](https://github.com/quarkusio/quarkus/pull/9919/files#diff-052522c68b7ad31589938c6c5cfa315bc9298942cdaf495eae516a51178189dfR676) it expects the alternate pom.xml to have an absolute path.  I then tested and can confirm that an absolute path works even with the original pom.xml still in the directory.

### Expected behavior

quarkus dev mode and tests to work when specifying an alternate pom using a relative path, e.g. `mvn -f .flattened-pom.xml test` rather than having to give an absolute path.

### Actual behavior

The same exceptions occur as when running the commands against the regular pom.xml.

(Please note that the actual exceptions here are not the focus of this ticket, rather they indicate that the wrong pom.xml is being used.)

### How to Reproduce?

Reproducer: https://github.com/garyhodgson/quarkusdev_profiledep_reproducer

Steps:

Test: 

* `git clone https://github.com/garyhodgson/quarkusdev_profiledep_reproducer.git`
* `cd quarkusdev_profiledep_reproducer`
* `mvn clean process-resources`
* `cd getting-started`
* `mvn -f .flattened-pom.xml test` 
  * Exception occurs
* `mvn -f $(PWD)/.flattened-pom.xml test`
  * Tests succeed
* `rm pom.xml`
* `mvn -f .flattened-pom.xml test`
  * Tests succeed

Dev mode:

* `git clone https://github.com/garyhodgson/quarkusdev_profiledep_reproducer.git`
* `cd quarkusdev_profiledep_reproducer`
* `mvn clean process-resources`
* `cd getting-started`
* `mvn -f .flattened-pom.xml quarkus:dev`
  * Exception occurs
* `mvn -f $(PWD)/.flattened-pom.xml quarkus:dev`
  * App starts in dev mode.
* `rm pom.xml`
* `mvn -f .flattened-pom.xml quarkus:dev`
  * App starts in dev mode.

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0 garyhodgson-PC 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin

### Output of `java -version`

openjdk version "11" 2018-09-25 OpenJDK Runtime Environment 18.9 (build 11+28) OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

* The IT `io.quarkus.maven.it.DevMojoIT#testAlternatePom` from #9919 only covers the case when there is an alternative pom and no original pom.xml.  When I added a pom.xml alongside the alternative-pom.xml, and manually ran `mvn -f alternative-pom.xml quarkus:dev` in the test project folder it appears to instead try and use the pom.xml

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
Thanks for the report, https://github.com/quarkusio/quarkus/pull/18985 will fix it.

**Comment by garyhodgson** [comment]
@aloubyansky Many thanks for the very quick response!  I'll test as soon as it becomes available.
