### ISSUE TITLE
Inconsistency in Infinispan extension trust store

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#18996]
### Describe the bug

This is an offshoot from #14368 .

The behavior of `quarkus.infinispan-client.trust-store` is different than `infinispan.client.hotrod.trust_store_path` (defined in `hotrod-client.properties`). `infinispan.client.hotrod.trust_store_path` allows pointing directly to a certificate in pem format (per https://docs.jboss.org/infinispan/11.0/apidocs/org/infinispan/client/hotrod/configuration/package-summary.html), whereas `quarkus.infinispan-client.trust-store` requires importing the certificate into an actual Java trust store and specifying the path to that trust store.

I'm not sure if there is a new config property to be added or if this is just a documentation issue. In any case it should be clarified

**Comment by wburns** [comment]
@edeandrea did you set the trust store type to pem ? If this is not set it defaults to JKS

**Comment by wburns** [comment]
Talking with Tristan he mentioned this (which I was looking at 12 code)

> no, up to 11, PEM certs needed the alternate property (trust_store_path). Starting with 12.0, there is only trust_store_file and trust_store_type can be set to PEM

@edeandrea so what version of Quarkus are you using?

**Comment by edeandrea** [comment]
Not sure if this is still an issue or not.
