### ISSUE TITLE
Upgrade of hibernate-validator

### ISSUE THREAD

**Issue by HelvetiaAppDev** [quarkusio/quarkus#18991]
### Description

The current version of org.hibernate.validator:hibernate-validator in quarkus-hibernate-validator is 6.2.0.Final
There is a new version of org.hibernate.validator:hibernate-validator 7.0.x
Would it be possible to upgrade it for possible security concerns?

**Comment by Sanne** [comment]
> Would it be possible to upgrade it for possible security concerns?

Why would you be concerned? The same people maintaining Hibernate Validator are maintaining Quarkus, if there ever is a security issue we would backport it to any branch that Quarkus is using.

We can't upgrade to Validator 7 now as it changes APIs.
