### ISSUE TITLE
Resteasy Reactive not working with unspecified accept header and multiple produces

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#18997]
### Describe the bug

I have discovered a problem with resteasy-reactive and produces media type matching.

If i have more than one media type (e.g. text/plain and application/json) and no specific mediatype is selected in the accept header, then the response contains content-type: application/octet-stream.

Also i noticed that the qs parameter is ignored in resteasy-reactive, which is unfortunatly very important in our projekt.

This is in quarkus 2.0.3.Final.

I added an repoducer:

[reproducer.zip](https://github.com/quarkusio/quarkus/files/6878253/reproducer.zip)

Just execute the test.

**Comment by geoand** [comment]
I see the same issue with RESTEasy Classic, so I am inclined to think it's just how the JAX-RS spec handles these cases.

WDYT @FroMage ?

**Comment by antonwiens** [comment]
But this used to work for me in resteasy classic in quarkus  1.10, so i dont think its normal behavior.
Also the qs parameter used to work.

**Comment by geoand** [comment]
I just switched your reproducer to resteasy classic and the tests still failed

**Comment by antonwiens** [comment]
Sorry, i had an error in the test assertion, which also failed by mistake in resteasy-classic but not due to the same problem:

```
        assert(body.equals("{\"string\": \"string\"}"))
```

should be:
```
        assert(body.equals("{\"string\":  \"string\"}"))
```

**Comment by antonwiens** [comment]
Here is the the test with resteasy-classic with fixed assertion that is not failing:
[resteasy-classic-not-failing.zip](https://github.com/quarkusio/quarkus/files/6878433/resteasy-classic-not-failing.zip)

Here with resteasy-reactive failing with fixed assertion:
[reproducer-fixed-assertion.zip](https://github.com/quarkusio/quarkus/files/6878450/reproducer-fixed-assertion.zip)

**Comment by geoand** [comment]
The workaround is to use `RestAssured.given().accept("application/json").get(...)` instead of `RestAssured.given().get(...)`

**Comment by geoand** [comment]
It does seem like RESTEasy Reactive is not using the same default as RESTEasy Classic though... I'll have a look

**Comment by antonwiens** [comment]
> It does seem like RESTEasy Reactive is not using the same default as RESTEasy Classic though... I'll have a look

Thanks for looking into it.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19000 should fix the issue

**Comment by antonwiens** [comment]
As i can see the quality factor (qs parameter) is not yet considered in this fix?

**Comment by geoand** [comment]
It is because the supported media types are sorted by qs

**Comment by antonwiens** [comment]
> It is because the supported media types are sorted by qs

Thanks for clarifing this!
