### ISSUE TITLE
Suspendable ServerRequestFilter in Resteasy Reactive

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#19013]
### Description

The following return types are currently possible in Resteasy Reactive Filters (`@ServerRequestFilter`): `void`, `Response`, `RestResponse`, `Optional<Response>`, `Optional<RestResponse>`, `Uni <Void>`, `Uni<RestResponse>` or `Uni <Response>`.

Please add support for suspendable filters (Kotlin Coroutines).

Example
```kotlin
class Filters {

    @ServerRequestFilter(preMatching = true)
    suspend fun preMatchingFilter(requestContext: ContainerRequestContext): RestResponse<String>? {
        return if (requestContext.method == HttpMethod.GET) {
            RestResponse.ok("GET", MediaType.TEXT_PLAIN_TYPE)
        } else {
            null
        }
    }
}
```

**Comment by geoand** [comment]
This is certainly interesting, but may I ask what you plan to do in the filter that requires it to be a suspending function?

**Comment by mschorsch** [comment]
I am planning to call a suspend function in a service. The suspend function in the service makes an asynchronous request (a database call or a rest request).

In addition, it is already possible to return a `Uni`, so it would make sense to support `Deferred` as well.

Maybe it would be a good idea to support suspendable functions where `Uni` is already supported?

**Comment by geoand** [comment]
Yeah, we can certainly do that. But it will likely be a `2.3` enhancement, not a `2.2` one

**Comment by mschorsch** [comment]
@geoand Ist there any chance that this will be in 2.4?

**Comment by geoand** [comment]
I'd say chances are slim, but it could happen.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20529 introduces this feature
