### ISSUE TITLE
jax-rs - exception mapper - `Unable to extract parameter` message doesn't appear in dev mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19016]
### Describe the bug

When double-checking https://github.com/quarkusio/quarkus/issues/11252 I noticed that the expected `RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("paging") value is 'asd'` message for `curl -v 'localhost:8080/users?paging=asd'` request appears only when running the app in production mode using `java -jar ...`. 

The code of the endpoint is simple, expecting the value to be convertible to Integer:
```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Integer page(@QueryParam("paging") Integer page) {
        return page;
    }
```

I think this issue can be present for quite some time, maybe since the `Resources overview` page for 404 - Resource Not Found was introduced for web browser.

### Expected behavior

In production mode I receive 
```
< HTTP/1.1 404 Not Found
< Content-Length: 110
< Content-Type: text/html;charset=UTF-8
<
* Connection #0 to host localhost left intact
RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.QueryParam("paging") value is 'asd'
```

The same should appear in dev mode

### Actual behavior

When running in dev mode I do not see that message because I get `Resources overview` page for 404 - Resource Not Found in web browser or using curl I receive
```
< HTTP/1.1 404 Not Found
< Content-Length: 0
```

### How to Reproduce?

git clone git@github.com:gastaldi/resteasy-xss.git
cd resteasy-xss
mvn quarkus:dev -Dquarkus.platform.version=2.1.0.Final -Dquarkus-plugin.version=2.1.0.Final
curl -v 'localhost:8080/users?paging=asd'
Ctrl+C

mvn clean package -Dquarkus.platform.version=2.1.0.Final -Dquarkus-plugin.version=2.1.0.Final
java -jar target/quarkus-app/quarkus-run.jar
curl -v 'localhost:8080/users?paging=asd'
Ctrl+C

### Output of `uname -a` or `ver`

Darwin rsvoboda-mac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.0.0.2.r11-grl

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.6.3

**Comment by geoand** [comment]
Is this still an issue?

**Comment by rsvoboda** [comment]
Closing as this is fixed.

Checked with Quarkus 2.13.3.Final (quarkus-resteasy) and Quarkus 3.14.3 (both quarkus-resteasy and quarkus-rest)
