### ISSUE TITLE
java.lang.IllegalAccessError: class com.example.Startup tried to access protected field in Panache after 1.13

### ISSUE THREAD

**Issue by ivannov** [quarkusio/quarkus#19012]
### Describe the bug

I have an abstract Panache entity (`User extends PanacheEntityBase`) that declares a few public fields:

```java
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id;

    public String firstName;

    public String lastName;

    public boolean isActive;
```

Then I have another entity that extends the first one (`InheritedUser extends User`) without adding any new fields.

Then in a class (located in another package) I instantiate the `InheritedUser` class, try to set a value to one of the fields inherited from the parent and persist it.

However, I get here:

```
ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalAccessError: class com.example.Startup tried to access protected field com.example.model.User.isActive (com.example.Startup and com.example.model.User are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @75a5cafe)
	at com.example.Startup.onServerStartup(Startup.java:16)
	at com.example.Startup_Subclass.onServerStartup$$superaccessor1(Startup_Subclass.zig:265)
	at com.example.Startup_Subclass$$function$$1.apply(Startup_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:57)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:43)	
```

This works with 1.12, but stopped working with 1.13 and 2.0.

### How to Reproduce?

A reproducer project is pushed here:

https://github.com/ivannov/inheritance-panache

**Comment by FroMage** [comment]
So, I was able to reproduce it, in dev mode, for quite a while, but then it went away and I can't reproduce it anymore. This seems to be related to hot reload. Can you reproduce it always, from a fresh start?

**Comment by ivannov** [comment]
I started the reproducer project in dev mode and then killed it for 7-8 times. Every time it failed with the above exception. 

The last time I didn't kill it and left it hanging for 4-5 minutes. Quarkus was indeed trying to hot replace something, but every time it failed with the same error
