### ISSUE TITLE
Morphia extension in quarkiverse

### ISSUE THREAD

**Issue by evanchooly** [quarkusio/quarkus#19023]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

We've had a number of requests to add more ODM-like features to MongoDB Panache.  Rather than building yet another ODM, let's integrate an existing one.  As the maintainer of Morphia, integrating in to quarkus shouldn't be terribly difficult.

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-morphia.
Also registered in the Quarkus extension catalog in https://github.com/quarkusio/quarkus-extension-catalog/commit/d9f4722280203451182096e8e641ec9f19d1ede3
