### ISSUE TITLE
no logging output in tests not annotated with @QuarkusTest 

### ISSUE THREAD

**Issue by dfa1** [quarkusio/quarkus#19024]
### Describe the bug

In my quarkus applications I would like to see log output in all tests, not only those annotated with `@QuarkusTest` annotation.

 

### Expected behavior

To be able to configure and see logging output for all unit tests, even those not annotated with @QuarkusTest.

### Actual behavior

Logging output only for tests annotated with `@QuarkusTest`.

### How to Reproduce?

Try this small test:
```
package app;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LoggingTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(LoggingTest.class);

    @Test
    void logging() {
        LOGGER.error("hello world");
    }
}
```

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

openjdk 11

### Quarkus version or git rev

1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.1

**Comment by famod** [comment]
Related: #7696 & #11114

AFAIK, this still a blind spot that requires workarounds that may or may not work for you (see above issues),

**Comment by geoand** [comment]
Yeah, this is pretty much a duplicate of those issues, so I'll go ahead and close it

**Comment by dfa1** [comment]
thank you @famod  and @geoand  for the bugs
