### ISSUE TITLE
Quarkus Gradle plugin 2.1.0.Final configuration time is slow

### ISSUE THREAD

**Issue by asodja** [quarkusio/quarkus#19022]
### Describe the bug

I am upgrading our project from Quarkus 1.3.x to 2.x.x. I saw that 2.1.0.Final is on Gradle plugin portal so I tried it out, even though I know 2.1.0.Final is not released yet. I found out that 2.1.0.Final increases gradle configuration time substantially. Even gradle help now takes cca. 8s. Quarkus Gradle plugin 2.0.3.Final works ok.

It seems that problem is, that dependencies are resolved in configuration time (so in plugin.apply()) and not at execution time of the plugin as before. Since Gradle does not parallelise configuration time that well that can result in longer task startup times on multi-module projects. So every start of Gradle task is slow and can take multiple seconds even if it's not related to Quarkus plugin: imagine debugging unit tests where every test task start takes additional 8+ seconds.

We have project with 23 modules which is not that much and from gradle scan it can be seen that configuration phase for Quarkus takes 8 seconds.

Screenshot from `gradle help --scan`:
<img width="999" alt="Screenshot 2021-07-25 at 11 40 53" src="https://user-images.githubusercontent.com/3939893/126894796-528c4b42-d58f-4b65-94cc-67fb59b0245c.png">

### Expected behavior

Quarkus Gradle plugin configures in sub second

### Actual behavior

Quarkus Gradle plugin takes long time to configure

### How to Reproduce?

[quarkus-configuration.zip](https://github.com/quarkusio/quarkus/files/6885886/quarkus-configuration.zip)

Steps:
1. Run gradle help multiple times -> it takes cca. 5s everytime
2. Change version of Quarkus plugin to 2.0.3.Final in settings.gradle
3. Run gradle help multiple times -> it takes 1s (it takes more on first run)

### Output of `uname -a` or `ver`

MacBook-Pro 19.6.0

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

/

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

### Additional information

I know 2.1.0.Final is not released yet, but it might be good to know. Feel free to close it, if it is a known issue.

**Comment by glefloch** [comment]
In ˋ2.1.0.Final` we introduce conditional dependency resolution. 
This needs dependency to be resolved before compilation as it can adds dependencies to the classpath. 
Right now this is done in the ˋafterEvaluateˋ method but maybe we can do better.

**Comment by asodja** [comment]
Oh I see. Do you think creating a separate task for that and make compile task depend on it would solve it?

Current solution also brings up some issues with dependency plugins, for example Spring dependency plugin (https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/)

**Comment by ncorai** [comment]
This 8-10 second delay is very frustrating, since it happens for every Gradle task, even if there is no new compilation required.

**Comment by joggeli34** [comment]
We suffer from the same problem. As we have a mono-repo with multiple quarkus applications inside, it currently takes 30s-40s of configuration time before each run / build.

**Comment by glefloch** [comment]
yes, I working on it, I should be able to move deployment classpath resolution in a task. But I'm not sure this is a part of the code that takes time.

**Comment by joggeli34** [comment]
Using Quarkus 2.2.3.CR1 solves the problem for me. The time spend in configuration is now only 1sec.
The task `quarkusGenerateCode` takes some time, but it is only run for dependent task and works with the up-to-date check.
Thanks for the fix 👍

**Comment by glefloch** [comment]
@asodja, @ncorai could you give it a try?

**Comment by ncorai** [comment]
Yes!
`.\gradlew tasks` went from about 40 secs to 3 secs
`.\gradlew :singleproject:checkstyleMain` (after `clean`) from 1:35 to 24 secs
`.\gradlew :project1of4:checkstyleMain` (1st run after `clean`) from around 3:30 to 3:00
`.\gradlew :project1of4:checkstyleMain` (later run, no code changes) from around 2:15 to 30secs

Much much better, thank you

**Comment by asodja** [comment]
I did not have a chance to test this with production project. But I checked with reproducer and it looks good.

**Comment by glefloch** [comment]
@aloubyansky, can we consider to close this one as feedback looks good?

**Comment by aloubyansky** [comment]
Great! Thanks for the feedback everyone! And @glefloch for fixing it!
We'll keep looking into improving build performance in the upcoming releases.

**Comment by apssouza22** [comment]
Hi everyone, how to enable gradle configuration cache in a Quarkus multi-project repo? We are using jandex for indexing. However it seems that jandex doesn't support this feature since I am getting this error

```
- Task `:platform:runtime:quarkus:base:jandex` of type `org.kordamp.gradle.plugin.jandex.tasks.JandexTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

```

I am wondering how are you guys handle this on your multi-module Quarkus project
