### ISSUE TITLE
Multipart Class Defined Outside Resource Implementation Fails with CNFE "Populator"

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19037]
### Describe the bug

When I define a class meant to be used as a payload in both my REST client and resource I get a CNFE stating that the "populator" could not be located.  If I put the class with the resource it works fine.

Referencing a conversation with Michal on [Google Groups](https://groups.google.com/g/quarkus-dev/c/oq73n_QJzxI/m/zJw0CtJsAAAJ).

**Issue 1 demonstrates the error / Working 2 demonstrates what worked:**

[reproduce-issue1.zip](https://github.com/quarkusio/quarkus/files/6888330/reproduce-issue1.zip)
[reproduce-working2.zip](https://github.com/quarkusio/quarkus/files/6888336/reproduce-working2.zip)

NOTE: Hopefully I did not mix up my reproducers.

### Expected behavior

Class defined in a separate module can be used as the payload from the client and in the resource.

### Actual behavior

Class not found exception - "Populator" when the payload is defined in another module.

ClassNotFoundException: io.platform.api.publish.FilePackage_generated_populator

### How to Reproduce?

Run `mvn clean install` on the issue attached above

### Output of `uname -a` or `ver`

Ubuntu / WSL

### Output of `java -version`

JDK 11 in the POM / 15 as the default.

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

### Additional information

I forgot to include the Jandex plugin in my reproducer but my modules all are invoking it (and I see the IDX file).  I have also tried adding a `beans.xml` but that did not help.  Anything but the multipart payload seems to work though when separated between an API jar and the service jar.

**Comment by geoand** [comment]
@michalszynkiewicz let me know if you need anything from me on this one

**Comment by michalszynkiewicz** [comment]
The weird thing is, the class is there, generated.

**Comment by stuartwdouglas** [comment]
It is likely ending up in the wrong ClassLoader, which is determined by `io.quarkus.deployment.builditem.GeneratedClassBuildItem#applicationClass`

**Comment by michalszynkiewicz** [comment]
So, it is set to be an application class.
But it is the same in the case of having the payload class in the same module, and it works...
When I change `applicationClass` to `false` for it, it fails to load the interface class (in this case `api.FilePayload`) - and it fails like that also in Quarkus tests

**Comment by michalszynkiewicz** [comment]
@geoand if you could take a look at it, I'd be grateful :)

**Comment by geoand** [comment]
I'll have a look tomorrow

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19068 is the fix in any case
