### ISSUE TITLE
`gradlew build` seems to be trying to execute `@NativeImageTest`s

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19033]
### Describe the bug

When creating a new project from code.quarkus.io using Gradle as the build tool, running `./gradlew build` seems to be executing the `@NativeImageTest` tests.

```
$ ./gradlew --console=plain clean build
> Task :clean

> Task :quarkusGenerateCode
preparing quarkus application

> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar

> Task :quarkusGenerateCodeTests
preparing quarkus application

> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test

NativeReactiveGreetingResourceIT > testHelloEndpoint() FAILED
    java.io.IOException at ProcessBuilder.java:1128
        Caused by: java.io.IOException at ProcessImpl.java:-2

2 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/edeandre/workspaces/workshops/azure-quarkus/azure-quarkus/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
8 actionable tasks: 8 executed

```

### Expected behavior

The `@NativeImageTest`s shouldn't be run. At least that's my understanding according to https://quarkus.io/guides/gradle-tooling#building-with-gradlew-build

### Actual behavior

The `@NativeImageTest`s are executed

### How to Reproduce?

Generate a new project from code.quarkus.io (can be very basic) using Gradle and run `./gradlew build`.

### Output of `uname -a` or `ver`

Darwin edeandre-mac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### GraalVM version (if different from Java)

openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 6.9 ------------------------------------------------------------  Build time:   2021-05-07 07:28:53 UTC Revision:     afe2e24ababc7b0213ccffff44970aa18035fc0e  Kotlin:       1.4.20 Groovy:       2.5.12 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.2 (Oracle Corporation 11.0.2+9) OS:           Mac OS X 10.16 x86_64

**Comment by edeandrea** [comment]
Reading the guide further, should the generated `@NativeImageTest` be generated into a different source set other than `src/test/java`?

**Comment by glefloch** [comment]
Yes by default they are located under `src/native-test/java`. Could you try putting them there?

**Comment by edeandrea** [comment]
I must have done something dumb. Sorry about that.
