### ISSUE TITLE
Allow flyway to use different credentials

### ISSUE THREAD

**Issue by tioback** [quarkusio/quarkus#19039]
### Description

I would like to use different credentials for my flyway migrations, while still using the same datasource.

For that, I believe we should make `flyway.user` and `flyway.password` visible.

In case they are specified, the application should use those credentials to connect to the default (or named) datasource. 

The default behaviour in case the properties are missing, is to use the credentials provided at the datasource configuration.

These are the properties I'm talking about ([source](https://flywaydb.org/documentation/configuration/configfile)):

```properties
# User to use to connect to the database. Flyway will prompt you to enter it if not specified, and if the JDBC
# connection is not using a password-less method of authentication.
# flyway.user=

# Password to use to connect to the database. Flyway will prompt you to enter it if not specified, and if the JDBC
# connection is not using a password-less method of authentication.
# flyway.password=
```

The new properties names could be `quarkus.flyway.user` and `quarkus.flyway.password` with possible named values being `quarkus.flyway."named-data-source".user` and `quarkys.flyway."named-data-source".password`.

I'll see if I can work on a PR later on.

**Comment by gastaldi** [comment]
This is already implemented. See https://quarkus.io/guides/flyway#quarkus-flyway_quarkus-flyway-username
