### ISSUE TITLE
Support multipart payload with different parts in REST client

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19042]
### Description

When defining a multipart payload, for use in the RESTClient, it appears you cannot define multiple different parts.  Using the same payload directly in the resource appears to work.  It would be nice to support multiple parts within the payload (text, json, files, etc.)

This references this conversation on [Google Groups](https://groups.google.com/g/quarkus-dev/c/oq73n_QJzxI/m/BE9kNlFuAAAJ?utm_medium=email&utm_source=footer) and per Michal should be filed as an enhancment.

Attached is an example of a payload that does not seem to work from the client

[reproduce-issue3.zip](https://github.com/quarkusio/quarkus/files/6888899/reproduce-issue3.zip)

**Comment by geoand** [comment]
@michalszynkiewicz this has since been fixed, right?

**Comment by michalszynkiewicz** [comment]
yes
