### ISSUE TITLE
Support uploading multiple files with Multipart Payload in REST client

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19041]
### Description

Uploading multiple files through the RESTClient and a multipart payload does not work.  Handling multiple files as Multipart directly in the resource appears to work.  It would be convenient to handle multiple uploads in the multipart request instead of having to iterate/send each one or zip/unzip them.

This references this conversation on [Google Groups](https://groups.google.com/g/quarkus-dev/c/oq73n_QJzxI/m/BE9kNlFuAAAJ?utm_medium=email&utm_source=footer) and per Michal should be filed as an enhancment.

Attached are the non-working (multipart/multi-file/RESTclient) and working resource (multipart/multi-file)

[reproduce-issue2.zip](https://github.com/quarkusio/quarkus/files/6888872/reproduce-issue2.zip)
[reproduce-working1.zip](https://github.com/quarkusio/quarkus/files/6888874/reproduce-working1.zip)

NOTE: The working example seems to show that the resource can consume a multipart payload correctly but does not go through the steps of uploading it.

**Comment by Dosexe** [comment]
Hi, any updates on this topic? Seems quite strange that if I want to send multiple files with form names `attachment[0]`, `attachment[n]`, I have to predict the attachments limit in MultipartForm class

**Comment by geoand** [comment]
@Sgitario would you be interested in this?

**Comment by Sgitario** [comment]
> @Sgitario would you be interested in this?

Sure, I will start having a look into this next Monday/Tuesday.

**Comment by geoand** [comment]
Thanks

**Comment by Sgitario** [comment]
The reproducer seems to be working using the latest version of Quarkus 2.16.0.Final. 
@kjq @Dosexe , would you mind taking another look and see if you can reproduce this issue?

**Comment by kjq** [comment]
Ill take a look this week.  Thanks!

**Comment by Dosexe** [comment]
I will try as well, hopefully this week.

**Comment by kjq** [comment]
This looks to be working for us.

**Comment by geoand** [comment]
💪🏼
