### ISSUE TITLE
CLI "quarkus dev" command is not working with gradle kotlin

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#19049]
### Describe the bug

quarkus dev command is not working with gradle kotlin

### Expected behavior

should work

### Actual behavior

```
[ERROR] ❗  Unable to launch project in dev mode: Was not able to find a build file in: /Users/ia3andy/Downloads/code-with-quarkus
````

### How to Reproduce?

1. Generate some project with code.quarkus using Gradle Kotlin: https://stage.code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=resteasy&e=resteasy-jackson&e=hibernate-validator
2. Copy `quarkus dev` command in the popup
3. Unzip and cd
4.
```shell
$ quarkus dev
[ERROR] ❗  Unable to launch project in dev mode: Was not able to find a build file in: /Users/ia3andy/Downloads/code-with-quarkus
```

**Comment by glefloch** [comment]
I can reproduce the issue. This comes from here: https://github.com/quarkusio/quarkus/blob/8033e5e2a9ded66fd59eec281233777aff54a2a4/devtools/cli/src/main/java/io/quarkus/cli/build/GradleRunner.java#L238

I have fixed it. I'm adding a test.

**Comment by ia3andy** [comment]
Thanks @glefloch, we need to backport it to 2.0 and 2.1 if possible
