### ISSUE TITLE
Unable to set custom data source properties in Quarkus Flyway migration

### ISSUE THREAD

**Issue by ishwar25667** [quarkusio/quarkus#19050]
### Describe the bug

I Just wanted to migrated data source using Flyway extension using custom data source properties such as-

module.datasource.jdbc.url=xxx 
module.datasource.username=xxx
module.datasource.password=xxx

But unable to find any properties where I could set this custom data source.

gone through below article link but properties are started with quarkus.datasource.<custom_data_source_name>.jdbc.url.
https://quarkus.io/guides/flyway#multiple-datasources
quarkus.datasource.inventory.db-kind=h2
quarkus.datasource.inventory.username=username2
quarkus.datasource.inventory.jdbc.url=jdbc:h2:tcp://localhost/mem:inventory
quarkus.datasource.inventory.jdbc.max-size=12

Is there any way to set our custom data source name in Flyway just like below-

module.datasource.jdbc.url=xxx 
module.datasource.username=xxx
module.datasource.password=xxx

**Comment by geoand** [comment]
As mentioned in the guide you linked, for a datasource named `inventory` (configured with properties like `quarkus.datasource.inventory.db-kind=h2`), then you would configure flyway using something like:

```properties
quarkus.flyway.inventory.schemas=INVENTORY_TEST_SCHEMA
quarkus.flyway.inventory.locations=db/inventory/location1,db/inventory/location2
quarkus.flyway.inventory.migrate-at-start=true
```
