### ISSUE TITLE
Accept a list of quarkus extensions in the quarkus-platform-bom-maven-plugin

### ISSUE THREAD

**Issue by rsynek** [quarkusio/quarkus#19061]
### Description

The `quarkus-platform-bom-maven-plugin` currently requires a BOM (e.g. org.optaplanner:optaplanner-bom) as an input to generate a platform member BOM (e.g. io.quarkus.platform:quarkus-optaplanner-bom).

The input BOM is supposed to define also versions of dependencies of all related Quarkus extensions, which forces the `dependencyManagement` of the project the extensions belong (e.g. https://github.com/kiegroup/optaplanner) to be split into two parts:
1/ dependencies of Quarkus extensions
2/ everything else
This approach creates a maintenance burden on the platform participant project and does not guarantee the `dependencyManagement` is correct; think of overriding the BOM in some other place in the participant project's structure.

The proposal is to pass the list of GAV of related Quarkus extensions and a single pom.xml file declaring `dependencyManagement` for the entire project. The `quarkus-platform-bom-maven-plugin` would then pick only those `dependencyManagement` entries from the pom.xml file that the extensions truly depend upon.

@aloubyansky I took the liberty of filing this issue so that we can track and further discuss what we talked about today.

**Comment by aloubyansky** [comment]
@rsynek sounds good, although this issue should move to https://github.com/quarkusio/quarkus-platform-bom-generator, since this is where it will be implemented.

**Comment by rsynek** [comment]
@aloubyansky right, that's a better place; let me move it over there.

**Comment by rsynek** [comment]
Moving the issue to https://github.com/quarkusio/quarkus-platform-bom-generator/issues/64.
