### ISSUE TITLE
QuarkusIntegrationTest: Access to DevServices after #18933

### ISSUE THREAD

**Issue by bdevreugd-vialis** [quarkusio/quarkus#19080]
### Description

Issue #18854 allowed access to the dev service urls inside integration tests.
However, issue #18933 causes dev services to be started inside a shared network which will return urls inside that network. The integration test however is run from the host, which has no access to that shared network.

Could you add a method for integration tests, to acces the dev services?

### Implementation ideas

Expose a property with postfix .from-host that will contain the original URL (with the mapped port)?

**Comment by geoand** [comment]
Thanks for reporting!

**Comment by geoand** [comment]
I'll try and take a look next week

**Comment by Koekebakkert** [comment]
Any progress on this? It worked in 2.1.0.CR1 and Final only. It still broken in 2.4.1.Final. Desperately needed.

**Comment by Koekebakkert** [comment]
Thanks for your quick response.

I am using a WireMockServer inside an implementation of QuarkusTestResourceLifecycleManager to stub a graphql service.

During integration test phase on Linux using the application image, the application gets lauched as:

`docker run --rm -p 9990:9990 -p 8444:8444 --env QUARKUS_HTTP_PORT=9990 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://0.0.0.0:9990 --env GRAPHQL_SERVICE_MP_GRAPHQL_URL=http://localhost:8080/graphql application:1.0.1-SNAPSHOT`

and the application cannot reach localhost:8080

Everything will run fine with the '--network host' option, but that won't work on windows apparently.

With Quarkus 2.1.0.Final the application integration-test was working, it launched as:

`docker, run, --rm, --net=host, --env, QUARKUS_HTTP_PORT=9990, --env, QUARKUS_HTTP_SSL_PORT=8444, --env, TEST_URL=http://0.0.0.0:9990, --env, GRAPHQL_SERVICE_MP_GRAPHQL_URL=http://localhost:8080/graphql, application:1.0.1-SNAPSHOT`

How to proceed?

**Comment by geoand** [comment]
This should be taken care of in `2.5.0.CR1` (likely to be released in a few days) via https://github.com/quarkusio/quarkus/pull/21316

**Comment by Koekebakkert** [comment]
Looking forward to 2.5.0 ;)

**Comment by geoand** [comment]
If all goes well, `2.5.0.CR1` will be out today :)

**Comment by Koekebakkert** [comment]
Unfortunately, it still does not work with 2.5.0.Final.

I have tried it on both openSUSE Tumbleweed and LEAP where 2.1.0.Final works great.

What can I do to help troubleshoot the issue?

**Comment by geoand** [comment]
What does your code look like? What containers are launched when you start the test?

**Comment by Koekebakkert** [comment]
I have created a small project that can be used to hammer out the integration test issue. It will succeed with 2.1.0.Final but will fail with a higher version, including 2.5.0.Final. Where do I put it?

**Comment by geoand** [comment]
Just upload it to Github

**Comment by Koekebakkert** [comment]
Well here it is:  https://github.com/Koekebakkert/quarkus-wiremockserver-integration-test-service

Feel free to ask any question ;)

**Comment by geoand** [comment]
Thanks, I'll try and have a look tomorrow

**Comment by geoand** [comment]
It seems from the project you uploaded that you have not updated the code according to https://github.com/quarkusio/quarkus/issues/19080#issuecomment-964269107

**Comment by geoand** [comment]
Actually there is no good way to support that use case if we want to support the more common case where a supporting container is launched. You'll probably have to switch from Wiremock to https://www.testcontainers.org/modules/mockserver/
