### ISSUE TITLE
Custom Extension with reactive messaging blocking or runSubscprition not working

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#19094]
### Describe the bug

I have a custom extension which uses reactive messaging. It has some blocking work to do and then sends an event via a rest client. Without using `blocking` or `runSubscriptionOn` it is working, but sometimes gets the warning that it blocked the thread to long. So I tried adding the blocking annotation, which does not work. Injecting fails, like for the logger.
My second idea was using `runSubscriptionOn` like shown here https://smallrye.io/smallrye-mutiny/guides/imperative-to-reactive. But this although fails in my scenario with an IllegalStateException: RESTEASY004510: Client is closed. The exception is not logged.

Maybe there needs to be something special in the ExtensionProcessor?

### Expected behavior

To be able to run the blocking work whit out blocking the thread.

### Actual behavior

Not possible to use `blocking` or `runSubscriptionOn`.

### How to Reproduce?

[test-extension.zip](https://github.com/quarkusio/quarkus/files/6900624/test-extension.zip)

In the extension there is a class called EventSubscriber in which there are the 2 options with `blocking` and `runSubscriptionOn`. Run the test via `mvn test` and activate the different version in the class.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1110]

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by ozangunalp** [comment]
@robp94 your test exits before a thread in the worker pool can run on the `eventClient`.
You see the "Client is closed" error because the app is being shut down.
You can use `awaitility` library to wait in your test for the stub to receive the request.

Something like this at the end of your test should work:
```java
        await().untilAsserted(() -> {
            verify(postRequestedFor(urlEqualTo("/publish"))
                    .withHeader("Content-Type", equalTo(MediaType.APPLICATION_JSON)));
        });
```

**Comment by robp94** [comment]
Thx.
