### ISSUE TITLE
Split package usage for `io.fabric8:openshift-model`, `io.fabric8:openshift-model-operator`

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19092]
### Describe the bug

Quarkus reports split package `io.fabric8.openshift.api.model` usage in `io.fabric8:openshift-model`, `io.fabric8:openshift-model-operator` artifacts.

```
2021-07-29 13:47:28,761 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-8) Detected a split package usage 
which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.fabric8.openshift.api.model" found in [io.fabric8:openshift-model, io.fabric8:openshift-model-operator]
```

### How to Reproduce?

Build project with `quarkus-openshift-client` extension and check the console logs.

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 2.1.0.Final

**Comment by geoand** [comment]
cc @manovotn

**Comment by manovotn** [comment]
This should be addressed by whoever is the maintainer of the aforementioned packages (any idea who that would be @gsmet  or @geoand?).
If not solvable right away, they can whitelist the package as was done in https://github.com/quarkusio/quarkus/pull/18743
Alternatively, users will be able to ignore certain packages once https://github.com/quarkusio/quarkus/pull/19089 gets incorporated.

**Comment by geoand** [comment]
We can't really address it now (since it's a k8s client issue).

@manovotn does https://github.com/quarkusio/quarkus/pull/19089 allow an extension to provide configuration?

**Comment by manovotn** [comment]
It doesn't now, we can expand it.  Didn't think we would need that as well :-D
