### ISSUE TITLE
Migrate the maven invoker ITs tests to the internal test harness

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#1909]
The maven plugin has 2 types of tests:

* some using the maven invoker plugin
* some using an internal test harness mechanism

The second approach gives more flexibility and should be used for all the tests. This issue is about migrating the tests using the maven invoker plugin to the internal mechanism.

**Comment by koziolk** [comment]
@cescoffier I can work on it.

**Comment by cescoffier** [comment]
Great @koziolk, let me know how it goes!

**Comment by koziolk** [comment]
@cescoffier Could you point me to an example of IT test that uses "an internal test harness mechanism".  Thanks.

**Comment by cescoffier** [comment]
Here is some resources about the "internal test harness":
* Implemented in this [package](https://github.com/quarkusio/quarkus/tree/master/devtools/maven/src/test/java/io/quarkus/maven/it/verifier)
* You can see how it's used in [CreateProjectMojoIT](https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/test/java/io/quarkus/maven/it/CreateProjectMojoIT.java) and in [PackageIT](https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/test/java/io/quarkus/maven/it/PackageIT.java)

There is also a `RunningInvoker` but you won't need it to this task.

**Comment by machi1990** [comment]
@koziolk hi, any updates on this?

**Comment by koziolk** [comment]
@machi1990 Still in progress.

**Comment by machi1990** [comment]
> @machi1990 Still in progress.

Let me know if you'll need more help (pointers) on this.

**Comment by Ishaan1342** [comment]
How do I get started on this issue? I'm familiar with maven, java and docker. 
Thanks.

**Comment by adrianfiedler** [comment]
Hi @cescoffier, @machi1990 
I migrated the maven invoker plugin tests to the internal test harness. Please take a look on my PR and assign me to this issue:
https://github.com/quarkusio/quarkus/pull/8632
