### ISSUE TITLE
Unable to forward from a JAX-RS service to JSP

### ISSUE THREAD

**Issue by soul2zimate** [quarkusio/quarkus#1911]
After I add a JSP page into src/main/resources/META-INF/resources and forward a JAX-RS service to it, it will download directly the file instead of showing JSP content. This is not same behavior as WFLY.

QS reproducer https://github.com/soul2zimate/quarkus-quickstarts/tree/jsp/getting-started

Run: mvn clean install
Execute: java -jar target/quarkus-quickstart-1.0-SNAPSHOT-runner.jar
Open http://localhost:8080/hello/jsp
The file is downloaded.

**Comment by gsmet** [comment]
I don't think we support JSP at all. And I'm not sure we will.

**Comment by soul2zimate** [comment]
Thanks @gsmet If this is not supported, please feel free to close this one.
