### ISSUE TITLE
@QuarkusIntegrationTest not working with Docker Image when doing security testing

### ISSUE THREAD

**Issue by Lahres-Dev** [quarkusio/quarkus#19116]
### Describe the bug

`mvnw clean verify -Pdocker-deploy` aborts build process with `connection refused`

I am using `quarkus-test-keycloak-server` plugin to simulate a Keycloak instance for security testing. Running `mvnw clean verify` works fine, also `mvnw quarkus:dev` continuous tests are running successfully.

Reproducer: https://github.com/Lahres-Dev/quarkus-issue-1
`quarkus.container-image.group` and `quarkus.container-image.registry` need to be filled, as I'm using a private registry for my docker images.

### Expected behavior

`mvnw clean verify -Pdocker-deploy`  runs successfully

### Actual behavior

`mvnw clean verify -Pdocker-deploy`  no successful run

### How to Reproduce?

1. clone reproducer https://github.com/Lahres-Dev/quarkus-issue-1
2. run `mvnw clean verify -Pdocker-deploy`

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 LTS OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS) OpenJDK Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode, emulated-client)

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\XXX\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.11, vendor: Amazon.com Inc., runtime: C:\copybase\jdk11.0.11_9 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"

**Comment by geoand** [comment]
Thanks for reporting.

This is essentially a duplicate of https://github.com/quarkusio/quarkus/issues/18914

**Comment by Lahres-Dev** [comment]
ok, thanks for the info :)
