### ISSUE TITLE
quarkus.swagger-ui.oauth2-redirect-url documentation and default value

### ISSUE THREAD

**Issue by tttomat19** [quarkusio/quarkus#19113]
### Description

So I battled swagger-ui + oidc with auth code or implicit flow with redirects and such.
The problem was after successful login in oauth provider the redirect led to localhost:8080/oauth2-redirect.html
And there was 404.

The solution was found here in the last comment: https://github.com/quarkusio/quarkus/issues/4766 Many thanks to Phillip.

I set this property and it worked fine.
`quarkus.swagger-ui.oauth2-redirect-url=/q/swagger-ui/oauth2-redirect.html`

### Implementation ideas

I believe the setting `quarkus.swagger-ui.oauth2-redirect-url` should be set to `/q/swagger-ui/oauth2-redirect.html` by default. Or maybe if I'm wrong it might be good to add some more explanation to the property meaning in docs.

**Comment by phillip-kruger** [comment]
Hi @tttomat19 - Thanks for logging this. I'll play around with making that the default. As a last resort, I'll update the documentation
