### ISSUE TITLE
Broken favicon for Dev UI

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19117]
### Describe the bug

Broken favicon for Dev UI, nice one is when using Quarkus 1.13.7.Final.

Quarkus 2.0.0.Final and 2.1.0.Final bring weird gray something instead of favicon similar to the usual one like in case of https://quarkus.io/

http://localhost:8080/q/dev/resources/images/favicon.ico (you may need to hit Ctrl+R to force reload or open the link in private mode)
![Screenshot 2021-07-30 at 8 48 23](https://user-images.githubusercontent.com/925259/127612585-cc6b4bc6-8b9d-4356-a328-d80dde44b0bc.png)

### Expected behavior

favicon  similar to the one used on https://quarkus.io/ page

### Actual behavior

Current favicon - weird gray something

### How to Reproduce?

 - Run app in dev mode
 - Open http://localhost:8080/q/dev/
 - Check favicon 

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 2.1.0.Final

**Comment by famod** [comment]
I've also seen exceptions being logged about this.
