### ISSUE TITLE
hibernate-orm is missing some important Hibernate batch configuration options

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus#19129]
### Description

See https://quarkus.io/guides/hibernate-orm for current list and https://vladmihalcea.com/how-to-batch-insert-and-update-statements-with-hibernate/ for additional needed options, e.g.
* `hibernate.order_inserts`
* `hibernate.order_updates`
* `hibernate.jdbc.batch_versioned_data`

Is it planned to add them?

### Workaround
Using `persistence.xml`

**Comment by gavinking** [comment]
I feel like `hibernate.jdbc.batch_versioned_data` is something that's should be automatic the user should not really be required to worry about setting explicitly.

**Comment by Sanne** [comment]
Right, and same for the others.

FWIW:

 - AvailableSettings.ORDER_UPDATES is always enabled in Quarkus, as we believe it's the better option and has no known drawbacks.
 - `ORDER_INSERTS` is meant to be enabled in a similar way in the future, it's not today as there are some open issues related to it.

Regarding `BATCH_VERSIONED_DATA`, we're not setting it today but I guess we could take this in consideration; I'd need to better understand what implications this would have on designing applications making use of optimistic lockinng.

In general, I prefer to not expose many of these but rather make sure we automatically set the best strategies; this might also lead to removing of some such properties from ORM down the road, and allow us to better test all permutations of these options.

**Comment by funcbro** [comment]
Same issue here. 
We have to use persistence.xml to set the mentioned properties, but would favour of course the quarkus properties.
Additionally we use "reWriteBatchedInserts" of the Postgres driver in persistence.xml.

Generally I'm with you, only exposing settings commonly used. The settings for Batch-processing are from my point of view best-practices and though should be made available in an easy way I think, esspecially as you need a combination of multiple settings to make it work as most would expect.

Another problem I came over when looking into this topic was, that it's currently really hard to find out, which hibernate settings are set in Quarkus as defaults. Actually you have to read the extensions source to find out. Would be really helpful, when those were included in the documentation, even if there is currently no way overwriting them. But at least one knows immediately, that one has to switch to persistence.xml if settings are missing and there is no way to set them via quarkus properties.
(e.g. the mentioned ORDER_UPDATES or there are e.g. QuarkusH2Dialect and QuarkusPostgreSQL10/95Dialects which are not mentioned in the documentation at all, but only a reference to the hibernate dialects - are they used?)

**Comment by Sanne** [comment]
Regarding our defaults, that's a very good point. I remember wishing a feature that would dump the effective configuration on boot, not least to more easily get help from other Hibernate team members when we have complex bugs to investigage.

Unfortunately many components are bypassing the configuration parsing so it's not really possible to "listen" for configuration overrides and capture them.

But point taken, we should at least make an effort to precisely document it all.

> Generally I'm with you, only exposing settings commonly used. 

To be clear there's an additional reason: in several cases in the long history of Hibernate, it happened that we had some good idea to significantly improve something, but changing it would have broken existing applications. So over time the situation arose that most defaults are settings that people aren't recommended to use at all, other than keeping things smooth for legacy apps. Often properties exist just to enable the better strategy.

When we launched Quarkus we had the one in a lifetime luxury of not needing to be backwards compatible, for that reason we set the better defaults, and try to not expose the ones which should be eventually removed. We really need to trim down on the exposed properties, or maintenance is too complex.

Regarding batching specifically, what do you suggest?  Which one is urgently missing for you? As mentioned I believe `ORDER_UPDATES` and `ORDER_INSERTS` should be taken care of automatically (One is done, one will come when it's reliable: a drawback of not exposing such options is that people can't turn them off when they hit a bug so they need to be really solid).
Please suggest which flags are urgently missing for you - and if you can provide a convincing use case / test we'll add it to our integration tests.

**Comment by Sanne** [comment]
Followed up with #19197

**Comment by kay-horst** [comment]
As to `hibernate.order_inserts`: I have optimized bulk inserts by a factor of about 50 by using Hibernate batching in the case of entities without relations. This optimization is very important for the application.

However, for an entity type using `@OneToMany`, batching is not applied due to the entity types' not being sorted, so that single `INSERT`s are being generated.

It would be good to be able to stick with `application.yaml` properties instead of having to revert to a `persistence.xml`.

My suggestion for a "salomonic" solution: Instead of adding this property, which seems to have problems in some cases, to the `quarkus.hibernate-orm.*` - path, introduce `quarkus.jpa.properties.*` (analogous to SpringData), where one can set native JPA provider properties, which in the case of Hibernate will translate:

`quarkus.jpa.properties.foo.baz -> hibernate.foo.baz`

Thus, `hibernate-orm` can stick to a limited set of "opinionated" properties based on the module developers' reasoning, but the application developer has the liberty to apply arbitrary properties at their own risk. If it is made clear in the documentation, that using this puts the application developers at their own risk, it should not be too much of a hassle.

**Comment by funcbro** [comment]
Stumbled over another property I'm in need of: `hibernate.cache.auto_evict_collection_cache`
Like @kay-horst I would also like to see a more generic solution to this topic. Fallback to persistence.xml should not be the way to go.

**Comment by Sanne** [comment]
> My suggestion for a "salomonic" solution: Instead of adding this property, which seems to have problems in some cases, to the `quarkus.hibernate-orm.*` - path, introduce `quarkus.jpa.properties.*` (analogous to SpringData), where one can set native JPA provider properties, which in the case of Hibernate will translate:
> 
> `quarkus.jpa.properties.foo.baz -> hibernate.foo.baz`
> 
> Thus, `hibernate-orm` can stick to a limited set of "opinionated" properties based on the module developers' reasoning, but the application developer has the liberty to apply arbitrary properties at their own risk. If it is made clear in the documentation, that using this puts the application developers at their own risk, it should not be too much of a hassle.

Ok that's a reasonable proposal. As long as the aspect of "your own risk" is made clear I can relax my objections, but it's still not straight forward.

Just for sake of avoiding misuinderstandings:
It should also be clear that as we upgrade versions of Hibernate, some properties that had meaning today will cease to work at any time as we won't be testing for any of these being effective.

It's also the case that some properties are directly controlled by the Hibernate ORM Processor - and we might be enforcing some properties - in this case though if there's a mismatch with an externally provided property we'll log a warning to state it. For example, `order_updates` is enforced by Quarkus; other properties are mapped from general Quarkus properties - e.g. if `jdbc.timezone` is set, it will be copied into `hibernate.jdbc.time_zone`; there's a number of cases like this: not particularly tricky as long as we log a warning about inconsistencies & overrides, but it implies you'll not be able to control them all.

And finally, some integration code goes beyond what's configurable with properties. So for example don't expect to be able to configure a different connection pool or 2nd level cache implementation by using the standard Hibernate properties; this case is more tricky as the properties are simply not even looked at, so I don't see an opportunity to log appropriate warnings.

But yes this would work nicely with properties like `hibernate.cache.auto_evict_collection_cache` and `hibernate.order_inserts`. 

Someone wants to try preparing a patch?

**Comment by yrodiere** [comment]
> As long as the aspect of "your own risk" is made clear

IMO the only way to make that clear is to display a warning on startup listing all property keys (not values) set through `quarkus.hibernate-orm.properties`, and stating something like "those may be ignored or may not behave as desired, and even if they work now, they may stop working at any time when upgrading to a newer version of Quarkus". It would also help people doing commercial support.

Otherwise, +1000 to add something like this.

**Comment by yrodiere** [comment]
I would also suggest calling the property something that makes it extra clear it's not supported. Maybe `quarkus.hibernate-orm.unsupported-properties`.

**Comment by MikhailKlimenko** [comment]
Hello, does this option(quarkus.hibernate-orm.unsupported-properties) work in hibernate reactive?
