### ISSUE TITLE
Global config property to disable all DevServices

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19133]
### Description

It would be nice to have a global config property to be able to enable/disable all DevServices, something like `quarkus.devservices.enabled`.

A global switch to shut things off (like if I need/want to run `quarkus:dev` in a remote IDE like Eclipse Che which doesn't allow you to start containers because you're already in a container). In such a case if my app uses, say, a postgres db, kafka, & apicurio, it would be really nice to just be able to shut devservices off completely.

**Comment by OleKsimov** [comment]
It would be great to see this feature in the nearest future. It's so annoying to disable devservices for each module in multimodule project for each group of props (vault, datasource, kafka etc)

**Comment by stuartwdouglas** [comment]
I will add this, but TBH I don't really understand why it is an issue as if you have configured the relevant items Dev Services is automatically disabled. Are you adding extensions and then not using them?

**Comment by OleKsimov** [comment]
@stuartwdouglas I've just updated Quarkus version from 1.12 and noticed that tests started to work unstably. We are using testcontainers for vault, postgres and kafka (checking kafka topics in test for example), and in a lot of modules fix was just to add devservices.enabled=false to kafka configuration to fix all the problems. Currently, I have no time to investigate this issue in deep, but if you need some more information, I would explain it this way: tests preparation (after "Run Tests" button pressed on submodule) takes a bit more time and after that, I see next logs: 
[devservices.log](https://github.com/quarkusio/quarkus/files/6966528/devservices.log)
