### ISSUE TITLE
Allow multiple static openapi.yaml/json files

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#19131]
### Description

A service might implement multiple predefined APIs when using an API-first approach. I can also generate the appropriate model and API classes with the openapi generator by configuring multiple executions of the maven plugin with different input definition files. However, the ability of the openapi plugin for serving a static definition is currently limited to a single `openapi.yaml` or `openapi.json` file. Having the possibility to specify multiple files would aid when implementing several predefined API specifications and would avoid the need to manually merge them.

### Implementation ideas

Maybe extending the list of searched paths to something like

```
META-INF/openapi/*.json
META-INF/openapi/*.yaml
```

would already be sufficient.

The configuration property should probably also accept a list of file names.

**Comment by phillip-kruger** [comment]
Hi @languitar - thanks for this. We have thought about this before, and it should be possible to enhance the extension to do this. I'll have a look a.s.a.p.

Basically, we will keep the default to look for `META-INF/openapi.json` or `META-INF/openapi.yaml` except if some config is set that define the path(s) for the static file(s). 

When more than one file, we merge them into one.

Something like that ?

**Comment by languitar** [comment]
Sounds ok to me.
