### ISSUE TITLE
Quarkus rest client fails if the application is started via an costum start class 

### ISSUE THREAD

**Issue by hifleu** [quarkusio/quarkus#19149]
### Describe the bug

Quarkus rest client fails with 

_RoutingContext failure (500): java.lang.NoSuchMethodError: io.smallrye.context.SmallRyeManagedExecutor: method 'void <init>()' not found_ 

if started via an class annotated with @QuarkusMain calling Quarkus.run

### Expected behavior

Quarkus rest cleint should work even if the Quarkus application is started with an costum application start class.

### Actual behavior

unable to use Quarkus rest client with custom application start class

### How to Reproduce?

1. I copied the quarkus rest client example https://quarkus.io/guides/rest-client 
2. added the following class (copied code from: https://quarkus.io/guides/lifecycle)

```
package org.acme;

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.annotations.QuarkusMain;

@QuarkusMain
public class Main {

    public static void main(String ... args) {
         Quarkus.run(args);
    }

}
```

3. build the package with:

mvn package

4. run the application with 

java.exe -cp ".\target\quarkus-app\quarkus-run.jar;.\target\quarkus-app\app\*;.\target\quarkus-app\lib\boot\*;.\target\quarkus-app\lib\main\*;.\target\quarkus-app\quarkus\*" org.acme.Main

5. access the service with the following url 
http://localhost:8080/country/name/greece

the application throws:
2021-08-01 12:40:50,618 INFO  [io.ver.ext.web.RoutingContext] (executor-thread-0) RoutingContext failure (500): java.lang.NoSuchMethodError: io.smallrye.context.SmallRyeManagedExecutor: method 'void <init>()' not found

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1110]

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20; openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev

2.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment]
```
java.exe -cp ".\target\quarkus-app\quarkus-run.jar;.\target\quarkus-app\app*;.\target\quarkus-app\lib\boot*;.\target\quarkus-app\lib\main*;.\target\quarkus-app\quarkus*" org.acme.Main
```

Is not how you run a Quarkus application.

You run it with:

```
java.exe -jar ".\target\quarkus-app\quarkus-run.jar"
```

**Comment by hifleu** [comment]
Thank you for your clarification!

**Comment by geoand** [comment]
YW
