### ISSUE TITLE
Keycloak Dev Service doesn't use the Quarkus distribution of Keycloak

### ISSUE THREAD

**Issue by solsson** [quarkusio/quarkus#19141]
### Describe the bug

The Keycloak dev service is great, and the Dev UI for auth is very helpful. #17364 is impressive work, but if the Quarkus project doesn't use the Quarkus distribution of Keycloak, then who will?

### Expected behavior

IMO (without much insight into any of the two projects) Keycloak dev mode should default to using Keycloak.X, possibly allowing a toggle to the regular distribution for anyone who gets blocked by the "preview" status.

### Actual behavior

Starts regular Keycloak, which uses ~200MB more memory and double the startup time of Keycloak.X, compared to my [hack](https://github.com/Yolean/kubernetes-keycloakx/pull/1) to use Keycloak.X as dev service: https://github.com/Yolean/kubernetes-keycloakx/tree/master/quarkus-dev#keycloakx-for-quarkus-dev-mode

### How to Reproduce?

- `mvn quarkus:dev` from for example https://quarkus.io/guides/security-openid-connect
- Observe the `INFO  [🐳 ...]] (build-45) Container keycloak started in PT9.315248S`
- `docker stat` to see memory usage

### Output of `java -version`

OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)

### Quarkus version or git rev

2.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by sberyozkin** [comment]
Hi @solsson thanks for the feedback,  
I think at the very least we can document how to use the `keycloak-x` images. Red Hat builds of Keycloak are still WildFly based as far as I know and this is what QE is testing against so I guess it is better to keep it in sync at the dev services level by default as well for now at least. I'll experiment with the `-x` images in the next few days, thanks
CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
Dev Services is about developer experience, and is not really a 'supported' feature (in that you don't use it in production). IMHO it is fine to use Keycloak-x, we already do something similar with Kafka (use a smaller non-supported image for a better dev experience).

**Comment by sberyozkin** [comment]
Grand, I'll need to check all the provided options (grant types, custom ream imports) work with it and then can switch

**Comment by sberyozkin** [comment]
@solsson Hi, unfortunately importing the custom realms does not seem to work, have you tried it with your image ? Thanks

**Comment by solsson** [comment]
@sberyozkin Yes, the `quarkus` realm is there and Alice can log in. The initial requests to keycloak look like this:

```
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 503 /admin
GET 301 /auth
GET 302 /admin
GET 200 /admin/master/console/
POST 200 /auth/realms/master/protocol/openid-connect/token
POST 201 /auth/admin/realms
GET 200 /auth/realms/quarkus/.well-known/openid-configuration
GET 200 /realms/quarkus/protocol/openid-connect/certs
GET 200 /auth/realms/quarkus/protocol/openid-connect/auth?client_id=quarkus-app&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fq%2Fdev%2Fio.quarkus.quarkus-oidc%2Fprovider&scope=openid&response_type=code&response_mode=fragment&prompt=login&nonce=fS4rpjd
```

Where 301 is redirects https://github.com/Yolean/kubernetes-keycloakx/blob/master/quarkus-dev/docker-entrypoint-with-proxy.sh#L59, but there's also rewrites that aren't explicit in access logs. I don't know that the Keycloak project's strategy for these URL differences is, I only found them by trial and error.

**Comment by sberyozkin** [comment]
@solsson Thanks, what I meant was to check if a realm can be imported from a realm file, like [this one](https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-openid-connect-quickstart/config/quarkus-realm.json). Indeed I have also verified that the default realm is created and the default users (`alice`, `bob`) can sign in. But we expect the users work with the more complex set ups captured in the custom realm files. 
One can set `KEYCLOAK_IMPORT=realm.json` with the WildFly distro, with the `-X` image I've tried `import --file=realm.json` and `import realm.json` and cobing 2 commands as `start-dev import realm.json` - I'll quickly retry again a few variations - but looks like it does not work

**Comment by sberyozkin** [comment]
More than one command is not supported at the same time:
https://github.com/keycloak/keycloak/blob/master/quarkus/runtime/src/main/java/org/keycloak/cli/MainCommand.java

Looks like a dockerfile needs to be created for the self-signed certificates to be created as it does not start without `start-dev` or `--http-enabled=true` or may be it should be pushed into `keycloak.properties`

**Comment by sberyozkin** [comment]
I've had some progress with generating the self-signed certificates in a custom image and I could see the file being imported - it still fails to start - but I don't really want to continue exploring this path - it complicates things significantly and slows down a start up.
The approach where one can read the custom realm file into `RealmRepresentation` and post it with the admin API is not promising either - I'm already aware of a case where `RealmRepresentation` can not capture all the realm representation from the file.

**Comment by solsson** [comment]
I suppose that assistance from the Keycloak project could be necessary here. I've failed to assess the status of the "preview" such as if it's feature complete or not. However the principle of configuration at build time is a great improvement over the regular keycloak image. Some of the documented env:s there cause an additional appserver start and teardown from the entrypoint, which can delay readiness with minutes. Configuration at build time does make some "quick start" cases impractical though, and i'm not surprised if you've concluded that Quarkus would have to push its own downstream keycloak-x image.

**Comment by sberyozkin** [comment]
@solsson There is a good chance Keycloak experts will help with improving it - as soon as I can get a custom realm import working with `http` only I'll go ahead and finalize the PR such that it works for both WildFly and Keycloak-X containers; in meantime please keep stressing the initial DevServices/UI for Keycloak and let us know what you think (with issues, etc) - thanks
