### ISSUE TITLE
HibernateValidatorProcessor jandex ClassCastException

### ISSUE THREAD

**Issue by MarcoBaesso** [quarkusio/quarkus#19167]
### Describe the bug

Upgrade from version 1.13.7 to 2.x.x with quarkus-hibernate-validator break build with following exception:

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.1.0.Final:build (default) on project natocopsportal-runner: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.ClassCastException: class org.jboss.jandex.ClassInfo cannot be cast to class org.jboss.jandex.MethodInfo (org.jboss.jandex.ClassInfo and org.jboss.jandex.MethodInfo are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @60350b15)
[ERROR] 	at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:56)
[ERROR] 	at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:39)
[ERROR] 	at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:281)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

There is a workaround try catch
https://github.com/quarkusio/quarkus/blob/61ff524e5e3272f857b08a414dccfa3e959e978a/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L281

but this is not present on release 2.x.x, it was cherrypicked on 1.13.7

**Comment by gsmet** [comment]
I suppose you are using the Jandex plugin?

You need to upgrade it: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#jandex-upgrade .

**Comment by MarcoBaesso** [comment]
thanks, it was used by a custom extension

**Comment by gsmet** [comment]
And just to be thorough: we had a temporary workaround with a try until we could fix the real issue in Jandex. Thus why the try is gone and you need to upgrade Jandex.
