### ISSUE TITLE
dev mode - 404 Resource Not Found page available only on /XYZ when `quarkus.http.root-path=/XYZ` specified

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19194]
### Describe the bug

dev mode - 404 Resource Not Found page available only on /XYZ when `quarkus.http.root-path=/XYZ` specified

### Expected behavior

404 Resource Not Found page available only on any invalid URL in dev mode

### Actual behavior

404 Resource Not Found page available only on /XYZ prefixed URLs in dev mode

### How to Reproduce?

rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group

mvn -f app-generated-skeleton/pom.xml clean quarkus:dev -Dquarkus.http.root-path=/api

http://localhost:8080/foo
  vs.
http://localhost:8080/api/foo

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus main a01f9ef1d7

**Comment by geoand** [comment]
Is this still an issue?

**Comment by rsvoboda** [comment]
This is no longer an issue, checked with Quarkus 3.14.4.

**Comment by geoand** [comment]
Awesome, thanks for checking!
