### ISSUE TITLE
Document how exactly an Hibernate ORM instance is configured in Quarkus

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#19197]
### Description

Since we do override various defaults, and do also configure additional components automatically based on application introspection, advanced users are getting easily lost as they need to know the details of what we did.

### Implementation ideas

It seems that tracing our configuration properties would not provide a comprehensive solution, as often we plug in custom service implementations bypassing the traditional configuration mechanism.

A starting point would be to write it all down; would be great to figure out a way to ensure the documentation stays up to date. Maybe it can be made testable?

**Comment by yrodiere** [comment]
Hey @Sanne , documenting internals like this strikes me as something nobody will ever have time for, and which would lead to obsolete documentation pretty quickly anyway.

Is it ok if I close it as not planned?
