### ISSUE TITLE
Grpc DevUI output form resizing and missing test icons

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#19218]
### Describe the bug

[User Interface related] 
1. Output form height increasing at every method call
Causes: https://github.com/quarkusio/quarkus/blob/main/extensions/grpc/deployment/src/main/resources/dev-templates/service.html#L102

2. Tool(test) icon for redirecting to service methods is missing for Health endpoint and Steaming services (can be accessed only by directly accessing service URL e.x. http://localhost:8080/q/dev/io.quarkus.quarkus-grpc/service?name=helloworld.Streaming)

![image](https://user-images.githubusercontent.com/71509020/128172790-fb1c1d5d-03dd-4190-b499-80b79404b022.png)

### Expected behavior

1. Output form height is properly adjusted by the output size
2. Test redirect icons are present for Health and Streaming services 

### How to Reproduce?

Reproducer: https://github.com/kshpak/quarkus-reproducers/tree/main/grpc-devui

1. mvn clean quarkus:dev
2. Access http://localhost:8080/q/dev/io.quarkus.quarkus-grpc/services

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.1

**Comment by michalszynkiewicz** [comment]
There's one more thing that's wrong, the name of the streaming bean is the name of the generated class instead of the user's class. I will try to fix it too.

**Comment by michalszynkiewicz** [comment]
all the things but the service name are fixed, I'll leave the issue open to handle the service name as a part of it, if you don't mind
