### ISSUE TITLE
RestEasy Client default methods

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#19226]
### Describe the bug

When calling a default method on interface using `@RegisterRestClient` the default method is not invoked; instead I get an error saying
```
Could not find a method for: public default java.util.concurrent.CompletionStage io.foo.Bar.getFoo(java.lang.String)
```
Refactoring the code to use static methods on the interface works but is not that convenient.

### Expected behavior

The default method (actually decorating the call to another interface's method) is invoked and it will call the actual method, executing the REST request.

### Actual behavior

An error is thrown.

### How to Reproduce?

```java
@GET
@Path("foo")
CompletionStage<String> getFoo(@HeaderParam("Authorization") String authorization, @QueryParam("bar") String bar);

default CompletionStage<String> getFoo(String bar) {
  return getFoo("Bearer xyz", bar);
}
```

### Output of `java -version`

openjdk version "11.0.9" 2020-10-20

### Quarkus version or git rev

2.1.0

**Comment by geoand** [comment]
FWIW, this works fine with the reactive rest client

**Comment by geoand** [comment]
I am going to close this as `won't fix` since we already have a working alternative with the reactive rest client
