### ISSUE TITLE
Can not inject RedisClient to gRPC Service

### ISSUE THREAD

**Issue by hieunc278** [quarkusio/quarkus#19248]
### Describe the bug

Dear All,

We tried to inject RedisClient bean object to simple gRPC service but not successful yet. That object always has null value 

@GrpcService
public class GenOTPServiceImpl extends MutinyGenOTPServiceGrpc.GenOTPServiceImplBase {

    @Inject
    RedisClient redisClient;
}

However, when we injected to QuarkusApplication class, we saw that it is injected successful.

So how can we inject to gRPC service as well.

**Comment by cescoffier** [comment]
It would be great if you could provide a simple reproducer.

**Comment by hieunc278** [comment]
Dear Mr. @cescoffier,

Thanks for your supports. And now I could inject and use RedisClient properly. So I would like to close this issue as well.

**Comment by hieunc278** [comment]
Thanks @gsmet for your supports always.
