### ISSUE TITLE
Upgrade Gradle wrapper to 7.0 or greater

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#19256]
### Description

Currently, Gradle 6.9 has some limitations as not being able to define [exclusiveContent](https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository)

```
Gradle also lets you declare exclusive content that can only be found in one repository and it shouldn’t be searched for in any other.
```

This is especially useful to avoid "[A confusing dependency](https://autsoft.net/hu/a-confusing-dependency/)" than then later could finish in some security vulnerabilities. 

### Implementation ideas

Upgrade gradle distribution to something greater or equal to 7

https://github.com/quarkusio/quarkus/blob/main/devtools/gradle/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by pjgg** [comment]
@geoand WDYT ?

**Comment by glefloch** [comment]
@gsmet were you able to check if this can be done ? (IIRC there could have been issues with the support)

**Comment by gsmet** [comment]
I'd say we could prepare a PR and we will merge it either for 2.2 or for 2.3.

**Comment by gsmet** [comment]
Cool, thanks!

**Comment by gsmet** [comment]
@glefloch we have the green light to move to Gradle 7 in 2.2 if it helps making progress on the JDK 17 support.

**Comment by glefloch** [comment]
Great I will add this in the branch that enable gradle tests on jdk17 once I’m back from PTO.
