### ISSUE TITLE
quarkus-maven-plugin:2.1.0.Final creates project with different platform version

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#19250]
### Describe the bug

quarkus-maven-plugin:2.1.0.Final creates project with `<quarkus.platform.version>2.1.1.Final</quarkus.platform.version>`, which is not expected.
The issue exists even if `-Dquarkus.platform.version=2.1.0.Final` is specified.

Affects only 2.1.0.Final but may transit into 2.1.1.Final when a new release will be out.

### Expected behavior

`quarkus.platform.version` of the generated project is the same as `quarkus-maven-plugin` version

### Actual behavior

The `quarkus.platform.version` is resolved to 2.1.1.Final (the latest Quarkus version at the time)

### How to Reproduce?

```
mvn io.quarkus:quarkus-maven-plugin:2.1.0.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.1.0.Final
```
and see in the `/pom.xml` file, the `<quarkus.platform.version>`

### Quarkus version or git rev

2.1.0.Final

**Comment by kshpak** [comment]
`quarkus-maven-plugin` ignores the version and resolve the platform to the latest available
cc @geoand @stuartwdouglas @gsmet

**Comment by aloubyansky** [comment]
That is actually expected. I am still not sure whether it's a good thing though given that the plugin is released along with the Quarkus core.
Now all the devtools pull in the recommended Quarkus (platform) version from the registry.quarkus.io.

**Comment by kshpak** [comment]
It presents ambiguity for the users, why then they should specify the version!?

**Comment by aloubyansky** [comment]
The fact that the `platformVersion` seems to be ignore is definitely a bug.
