### ISSUE TITLE
quarkus-smallrye-health depends on microprofile-health-api 2.2 instead of 3.0

### ISSUE THREAD

**Issue by rolandhaas** [quarkusio/quarkus#19254]
### Describe the bug

According to the documentation and [blog announcement](https://quarkus.io/blog/quarkus-2-0-0-final-released/#eclipse-microprofile-4), quarkus >= 2.0.0 is implementing MicroProfile 4.0.

The MP spec uses microprofile-health-api version 3.0, see https://projects.eclipse.org/projects/technology.microprofile/releases/4.0

There seems to be an inconsistency between the MP APIs used.

### Expected behavior

Using 
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-health</artifactId>
</dependency>
```
from the quarkus guide should bring the transitive dependency org.eclipse.microprofile.health:microprofile-health-api:jar:**3.0**

Tested with version: 2.1.1.Final

### Actual behavior

The transitive dependency for version 2.2 of org.eclipse.microprofile.health:microprofile-health-api is used
```
[INFO] +- io.quarkus:quarkus-smallrye-health:jar:2.1.1.Final:compile
[INFO] |  +- io.smallrye:smallrye-health:jar:3.1.1:compile
[INFO] |  |  +- org.eclipse.microprofile.health:microprofile-health-api:jar:2.2:compile
[INFO] |  |  \- io.smallrye:smallrye-health-api:jar:3.1.1:compile
[INFO] |  \- io.smallrye:smallrye-health-provided-checks:jar:3.1.1:compile
```

This causes some weird exceptions while starting up my application
```
[io.quarkus.arc.processor.BeanArchives] Failed to index org.eclipse.microprofile.health.HealthCheckResponse$Status: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@121bf6ba
[io.quarkus.arc.processor.BeanArchives] Failed to index org.eclipse.microprofile.health.Startup: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@121bf6ba
```

Overwriting the dependency with 
```
        <dependency>
            <groupId>org.eclipse.microprofile.health</groupId>
            <artifactId>microprofile-health-api</artifactId>
            <version>3.0</version>
        </dependency>
```
directly within the applications pom.xml only reduces the exceptions by one. The following still remains
`[io.quarkus.arc.processor.BeanArchives] Failed to index org.eclipse.microprofile.health.Startup: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@519211f9`

I searched my projects and within the used dependencies and cannot find any usage of this class.

### Output of `java -version`

openjdk version "11.0.9" 2020-10-20 LTS

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by gsmet** [comment]
This is what I have with 2.1.1.Final in our quickstart:
```
[INFO] --------------< org.acme:microprofile-health-quickstart >---------------
[INFO] Building microprofile-health-quickstart 1.0.0-SNAPSHOT
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ microprofile-health-quickstart ---
[INFO] org.acme:microprofile-health-quickstart:jar:1.0.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-smallrye-health:jar:2.1.1.Final:compile
[INFO] |  +- io.smallrye:smallrye-health:jar:3.1.1:compile
[INFO] |  |  +- org.eclipse.microprofile.health:microprofile-health-api:jar:3.1:compile
[INFO] |  |  +- io.smallrye:smallrye-health-api:jar:3.1.1:compile
[INFO] |  +- io.smallrye:smallrye-health-provided-checks:jar:3.1.1:compile
```
So we are pointing to 3.1.

Are you sure you don't have a dependency specific to your project enforcing an older version somehow?

**Comment by xstefank** [comment]
Startup was added in 3.1 so that should fix the remaining error. However this is really strange, we indeed have MP Health API 3.1 in SR Health 3.1.1.

**Comment by rolandhaas** [comment]
Thanks for your quick replies.
I had to manually clear out my local repository and the artifactory store of our company. Now I can see the org.eclipse.microprofile.health:microprofile-health-api:jar:3.0 dependency which is comming from one of our internal frameworks. 
I'll try to exclude this dependencies manually... I guess this issue can be closed now.
