### ISSUE TITLE
Improve Logging traces regarding 403 errors

### ISSUE THREAD

**Issue by javiertoja** [quarkusio/quarkus#19263]
### Description

At this moment while developing a new application with the oidc-extension and keycloak or other provider it is possible to have human errors in the keycloak side while configuring the tokens or the quarkus side configuring audiences or roles. Human errors will happen always, but I would like to request and enhancement regarding the logging that the oidc extension does about token validation and configuration errors.

For example while using the oidc extension it is difficult to detect why 403 error is returned if the endpoint requires a roles that is not present within the tokens groups.

https://stackoverflow.com/questions/68648068/how-does-one-diagnose-quarkus-rest-service-oidc-errors-specifically-403-forbidd

**Comment by sberyozkin** [comment]
@javiertoja Hi, the values set in `RolesAllowed` are not logged, i.e, for ex, there would be no message like "Token contains a,b,c roles while RolesAllowed only contains d and e". When 403 occurs it is always the case that the token has no roles at all or has no matching roles so given that roles are set in KC and also in `RolesAllowed` it is easy enough to check why 403 occurs. Logging the specific values can expose too much information about the way Quarkus endpoints are configured so I'm not sure what else can be done beyond returning 403, thanks

**Comment by javiertoja** [comment]
@sberyozkin Hello, thanks for your time and look into this. 

I didn't know that the 403 could happen only in this case, I thought that maybe there where more scenarios where this error could happen. I see your point.

When I submitted the issue I wasn't looking for such a detailed message, with information about specific roles, rather than something more generic like "Token roles do not satisfy the ones required by the service" or something like that. The main point of requesting this kind of log entry is because, if I'm not mistaken at the moment there is none, and when a 401 error happens there is information about the actual error. Some users, including me, fall on the error of not realizing that the roles in the token were not the same as the ones requested on the service or that the roles path where not correct. Because there was no trace on the log in my case I considered the option that I had some missing configuration within the jwt or oidc extension configuration, rather than second checking the token content.

I see know that if there is only one possibility for an error 403 to happen, then there is no need for a special treatment of the error, but still I think that including some kind of debug message in the log that suggests the user to check the roles could be helpful specially to new users.

Thanks.

**Comment by sberyozkin** [comment]
HI @javiertoja the code which makes the authorization decision does not know if `SecurityIdentity` with the roles has been created from JWT or for ex Basic Auth, so it can't be very specific, and indeed the option you considered can also cause `403`

**Comment by sberyozkin** [comment]
I'd like to close it since 403 can only happen if the security identity has no required roles
