### ISSUE TITLE
Spurious warning when handling string list properties from YAML

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#19262]
### Describe the bug

I have an app which uses various quarkus extensions (e.g. opentelemetry, kubernetes-config) whose configuration includes comma-separated string-valued properties. I use the yaml extension so I can use application.yaml rather than application.properties.

When running on **2.0.1.Final** I found that I could lay out the yaml value of such a property in list form (for readability) e.g.

```yaml
quarkus:
  kubernetes-config:
    config-maps:
      - config1
      - config2
```

After upgrading to **2.1.1.Final** quarkus doesn't seem to like this anymore:

```
WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.kubernetes-config.config-maps[1]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.kubernetes-config.config-maps[0]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

It appears to be just a spurious warning as, regardless of whether the property value is specified as a comma-separated string or YAML list, the values read in by the config are the same at runtime.

### Expected behavior

That string-valued properties which are documented as comma-separated should be expressible as YAML list values.

### Actual behavior

If YAML list values are used, a warning is shown on app startup that the config keys [0], [1], etc are unrecognised. This does not appear to affect the runtime behaviour as the values are correctly parsed by the relevant `@ConfigRoot`-annotated class.

### How to Reproduce?

_Reproducer:_

**A**. Create a quarkus app using the yaml extension, and include any extension which has some comma-separated string property e.g. in your pom:

```xml
<!-- Support for YAML configuration -->
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-config-yaml</artifactId>
</dependency>

<!-- Example of an extension supporting comma-separated string property -->
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
</dependency>
```

**B**. In the application.yml, define the relevant property using a yaml list e.g.

```yaml
quarkus:
  opentelemetry:
    enabled: true
    propagators:
      - b3
      - b3multi
      - baggage
```

**C**. Put a breakpoint on the `OpenTelemetryRecorder::createOpenTelemetry` method and run the app in dev mode with debug.

Observe both that quarkus console emits a warning about the unrecognised propagators[0]...[2] properties, and that inspection of the `openTelemetryConfig` parameter value passed to the breakpointed method indicates that there are indeed 3 propagators in a `List<String>` with the correct values.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1500]

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Works fine in 2.0.1.Final

**Comment by geoand** [comment]
Does this happen with `2.1.1.Final` as well?

cc @radcortez

**Comment by radcortez** [comment]
This is because for item lists we also add their indexed property name to the list of configuration property names (the main property keeps the list as separated comma values lists). This allows you to keep retro compatibility and use either style.

Unfortunately, the Quarkus `@ConfigRoot` does not support indexed properties and reports these as unrecognized. I'll have a look.
