### ISSUE TITLE
Quarkus 0.13.0 removes important classes from my application by considering them unused

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1927]
When building [my app](https://github.com/fabric8-launcher/launcher-backend/) in Quarkus 0.13.0, it removes classes considered [unused](https://paste.fedoraproject.org/paste/IZ4qczWdZyxi8EEmKpaxaQ), but they are necessary. 

To reproduce this error, run the https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/test/java/io/fabric8/launcher/web/filters/SecuredIT.java test (Quarkus is removing the SecuredFilter)

The test passes in 0.12.0

**Comment by gastaldi** [comment]
This is the class that Quarkus removes: https://github.com/fabric8-launcher/launcher-backend/blob/master/core/core-impl/src/main/java/io/fabric8/launcher/core/impl/filters/SecuredFilter.java

**Comment by mkouba** [comment]
This should be fixed in https://github.com/quarkusio/quarkus/pull/1924.

**Comment by gastaldi** [comment]
I can confirm that https://github.com/quarkusio/quarkus/pull/1924 fixes this issue

**Comment by mkouba** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/1924.
