### ISSUE TITLE
Gradle test: Attempted to mix @SubstrateTest and JVM mode tests in the same test run. This is not allowed.

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1930]
Simply adding below e.g. to https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/build.gradle as suggested in https://github.com/quarkusio/quarkus-quickstarts/pull/139 :

```
test {
    useJUnitPlatform()
}
```

makes `../gradlew clean test` in `quarkus-quickstarts/getting-started` run and pass both tests in class [GreetingResourceTest](https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/src/test/java/org/acme/quickstart/GreetingResourceTest.java) (which is a `@QuarkusTest`), but fails the [NativeGreetingResourceIT](https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/src/test/java/org/acme/quickstart/NativeGreetingResourceIT.java) (which is a `@SubstrateTest` which extends GreetingResourceTest) with:

```
java.lang.RuntimeException: Attempted to mix @SubstrateTest and JVM mode tests in the same test run. This is not allowed.
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:85)
```

I (roughly) understand this may not be "bug" but something we should document (?) or perhaps solve by moving things around appropriately in the quickstart example, but it seems worth having an issue to track and discuss the best solution.

Perhaps to start with, how does this actually work in Maven? Surefire only runs *Test but not *IT? And ... failsafe (?) runs *IT, in a separate JVM? Do we "just" need to make Gradle do that? (Not that I would know how to.)

@jnizet @stalep @geoand @Sanne @aloubyansky input more than welcome.

**Comment by stuartwdouglas** [comment]
So the issue is that they would both want to use the same port. Also it is expected that you should run the JVM tests before building the native image, so if there are issues you pick them up earlier.

**Comment by gsmet** [comment]
> Perhaps to start with, how does this actually work in Maven? Surefire only runs *Test but not *IT? And ... failsafe (?) runs *IT, in a separate JVM? Do we "just" need to make Gradle do that? (Not that I would know how to.)

So, that's exactly the problem: with Maven, unit tests are run by Surefire and integration tests by Failsafe so they don't conflict.

I don't know if it's feasible to do the same in Gradle but that would be the idea.

**Comment by stalep** [comment]
Hi @vorburger, unfortunately I guess I've probably only talked about this on either zulip or the internal meetings, we should really add this to one of our guides. Yes, Gradle does it differently compared to Maven. Gradle have integration tests in different folders than unit tests (ref; https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests). While Maven differentiates between *Test.java and *IT.java Gradle do not.
I'm thinking that in the future we would have to split up the getting started guides for Maven and Gradle (or have some way of distinguishing the tests themselves with annotations or something that we can parse internally).

**Comment by vorburger** [comment]
#2993 by @garyttierney may propose a solution for this problem?

**Comment by gsmet** [comment]
We changed how the Gradle project tests are organized.
