### ISSUE TITLE
Bugsnag logging

### ISSUE THREAD

**Issue by krisgerhard** [quarkusio/quarkus#19308]
### Description

A Quarkus Extension to send (error) logs to a Bugsnag Error Monitoring. 
[Bugsnag homepage](https://www.bugsnag.com/)

There is an official extension for sentry (https://quarkus.io/guides/logging-sentry) but it is not the only popular error monitoring tool out there. I (and hopefully many others) would benefit from supporting Bugsnag as well.

In fact I have already implemented and used this extension in production for about two weeks now, and figured I might as well help make it available for others. It's separated in a repository -> https://github.com/krisgerhard/logging-bugsnag.
Couple of remarks about the implementation.
- I acknowledge it is not usable for quarkiverse as is. It is meant to show the simplicity of the extension.
- Most of the work is done by bugsnag-java library BUT there is some additional code to support tracking RESTEasy HTTP requests. For this I've also created a [PR](https://github.com/bugsnag/bugsnag-java/pull/167) in bugsnag-java repository but I would not count on them mergeing it any time soon so this code could as well be part of this extension until the time comes.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion
https://docs.bugsnag.com/platforms/java/other/configuration-options/
quarkus.log.bugsnag.enable=true
quarkus.log.bugsnag.api-key=YOUR_API_KEY
quarkus.log.bugsnag.minimum-event-level=WARN
quarkus.log.bugsnag.filters=password, credit_card_number
quarkus.log.bugsnag.ignored-classes=java.io.IOException, com.example.Custom
quarkus.log.bugsnag.notify-release-stage=production, development
quarkus.log.bugsnag.project-packages=com.company.package1, com.company.package2
quarkus.log.bugsnag.release-stage=development
quarkus.log.bugsnag.send-threads=false
quarkus.log.bugsnag.timeout=5000

**Comment by stuartwdouglas** [comment]
Note that you can also use the Quarkiverse logback support to use the logback appender: https://docs.bugsnag.com/platforms/java/other/configuring-logback/

**Comment by krisgerhard** [comment]
> Note that you can also use the Quarkiverse logback support to use the logback appender: https://docs.bugsnag.com/platforms/java/other/configuring-logback/

That's correct. Although at the moment Bugsnag does not know how to attach JAX-RS request data to the report.
It's arguable whether this should be the idea of the extension but it sure helps quarkus users towards using Bugsnag.

**Comment by krisgerhard** [comment]
@stuartwdouglas I started looking into the Logback extension. How would you inject bugsnag api key without committing it into repository?

logback.xml
```
<appender name="BUGSNAG" class="com.bugsnag.BugsnagAppender">
  <apiKey>your-api-key-here</apiKey>
</appender>
````

**Comment by stuartwdouglas** [comment]
You should be able to use `${my-key}`, which would get picked up from standard Quarkus config (e.g. a `MY_KEY` env var, or `-Dmy-key=` system prop).

**Comment by krisgerhard** [comment]
@stuartwdouglas Sorry for late reply. Logback extension + BugsnagAppender works as expected. Closing the issue.
