### ISSUE TITLE
Button to reset the database state from the Quarkus Dev UI for Hibernate ORM

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#19303]
### Description

See https://github.com/quarkusio/quarkus/pull/16764#pullrequestreview-648431733

> a button to reset the DB state (actually runs the drop script, followed by the create and optionally the import.sql if there's any)

CC @Sanne  @TomasHofman

### Implementation ideas

I think we would definitely need a pop-up with a warning, even if it's just development mode. Some people work with pre-initialized databases which take a long time to initialize, and they would be very annoyed if they dropped it by mistake.

**Comment by stuartwdouglas** [comment]
This exists here: https://github.com/quarkusio/quarkus/pull/15827

The reason why I did not go further with it was because I was not sure about how to add test support for native (for the test part). 

I might look at stripping out the test part for now.
