### ISSUE TITLE
Large Regression in Started RSS of native image

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#19334]
### Describe the bug

The started RSS of simple quickstarts has increased from ~18MB to ~66MB  for a 16 core machine.

This regression has been introduced between commits : 
13f0b2a6577e8f3a5a5236545cfa09ddbf7845a3 and 0d33b51c95474c512db8eb4fcaa98a8d0c889df8 

The size regression appears to be proportional to the number of cores available to the native application 

![Screenshot from 2021-08-11 07-04-01](https://user-images.githubusercontent.com/959822/128978328-2d8d238d-b5ba-48dc-a6cb-16190e16b680.png)

### How to Reproduce?

git clone https://github.com/quarkusio/quarkus-quickstarts.git

cd quarkus-quickstarts/getting-started/

./mvnw clean package -DskipTests=true -Pnative -Dquarkus.native-image.container-runtime=docker -Dquarkus.native.container-build=true

docker build -f src/main/docker/Dockerfile.native -t quarkus/getting-started-native .

docker run  --cpus="16" -i --rm --network=host -e QUARKUS_HTTP_PORT=9091 -e QUARKUS_HTTP_HOST=0.0.0.0 -e JAVA_OPTIONS=' -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus.vertx.event-loops-pool-size=4 -Dquarkus.vertx.worker-pool-size=32 -Xmx128m ' --name getting-started-native quarkus/getting-started-native

QUARKUS_PID=$(docker ps --filter="name=getting-started-native" --format="{{.ID}}" | xargs docker inspect | jq '.[].State.Pid')

pmap -x $QUARKUS_PID | grep total | awk '{print $4}' | sed 's/[^0-9]*//g'

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)

GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)

**Comment by holledauer** [comment]
Also the CPU load has increased dramatically:
![image](https://user-images.githubusercontent.com/804646/128993762-4cab9e8c-e46b-4b2f-b2fa-59479923b376.png)

This happened when I upgraded from 2.0.2.Final to 2.1.1.Final (there are no requests. this is just the base load). GraalVM 21.2.0 Java 11 CE

**Comment by mkouba** [comment]
Just trying `git bisect` to identify the problematic commit.

@johnaohara in the "How to Reproduce?" section: `docker build -f src/main/docker/Dockerfile.jvm -t quarkus/getting-started-jvm .` -> `docker build -f src/main/docker/Dockerfile.native -t quarkus/getting-started-native .` and `config-quickstart-native` -> `getting-started-native` ;-)

**Comment by johnaohara** [comment]
@mkouba ah yes, copied the wrong command from the logs, will update

**Comment by johnaohara** [comment]
I am having trouble reproducing this locally, but what I have noticed locally is the start time reported in the console has dramatically increased;


Commit ID | RSS (kB) | Start time
-- | -- | --
0d33b51c95474c512db8eb4fcaa98a8d0c889df8 | 37992 | 0.104s
589cebd0c3b84c25d8f4b565dc2e767f31f58ee8 | 38172 | 0.045s
5bec5375f4225f6e2c8091c1b0d71865042a95e9 | 38172 | 0.026s
28330b13b457ada58fa78e00edeb2e61034febc2 | 38136 | 0.027s
90ca472e742e0741ab910eef9e78db49ed1b906a | 38096 | 0.036s.

**Comment by johnaohara** [comment]
Another data point was in the lab, the start RSS had a large variation in RSS values;

run | startedVmRss
-- | --
1 | 17984
2 | 66756
3 | 48204
4 | 60436
5 | 50248

**Comment by mkouba** [comment]
Hm, I've just tried to checkout the `13f0b2a` commit and I get 34236 KB with `--cpus="4"`. And I get 34208 KB for the `main` branch. Where did you see the "~18MB" result? Last released version of quarkus?

**Comment by johnaohara** [comment]
The data is from runs in the performance lab, the RSS size is susceptible to the number of threads and cores on the machine.  The data is taken from nightly builds of the main branch. For example, the above data in the above commit is from commit id : 0d33b51c95474c512db8eb4fcaa98a8d0c889df8

**Comment by mkouba** [comment]
Just tried the `2.1.2.Final` and the RSS varies from 34080 to 34116 kB on my test machine (Linux 5.4.0-80-generic, i5-6260U with 4 CPUs) for `--cpus="1"`, `--cpus="2"` and `--cpus="4"`. In other words, the RSS number seems to be stable; ~ 34 MB. 

So I can't reproduce the regression locally :-(.

**Comment by johnaohara** [comment]
Having Investigated this further, I am seeing large variances in start time and RSS only on one particular machine (the machine we have been using for regression tests)  After swapping to a different machine in the lab, the start times and start RSS are stable and exhibit very low variations between invocations. I have cross-checked compiled binaries to ensure that there is not an issue with the build, and I see large variances in this particular machine independent of where the binary was built.  As this issue started between builds and has not been an issue for over 1 year, the problem must be related to a machine specific issue.  I have changed the startup regression tests to run on a stable machine in the lab

**Comment by johnaohara** [comment]
For information I found the root cause of the regression. Transparent huge pages had been enabled on that machine, and the kernel was allocating (and committing) multiple 2MB chunks of memory. disabling thp's has brought the RSS size back down and standard deviation is now very small. e.g. with THP enabled μ=45460kB; σ=20584. with THP disabled μ=1928kB; σ= 6.69
