### ISSUE TITLE
UberJar SecurityException when containing signed files

### ISSUE THREAD

**Issue by esteban-aliverti** [quarkusio/quarkus#1934]
I'm building a UberJar through the _quarkus-maven-plugin_ plugin but the generated jar can't be executed due to the following exception: **_Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes_**

This issue can be avoided by removing certain files from within the META-INF dir that is generated inside the Uber Jar. The files I'm talking about are _META-INF/*.SF_, _META-INF/*.DSA_ and _META-INF/*.RSA_ . I got this idea from here: https://stackoverflow.com/questions/999489/invalid-signature-file-when-attempting-to-run-a-jar

I've investigated the source code of the _quarkus-maven-plugin_ and realized that there is already [a filter for the entries we want to exclude](https://github.com/quarkusio/quarkus/blob/master/core/creator/src/main/java/io/quarkus/creator/phase/runnerjar/RunnerJarPhase.java#L75) from the generated jar. Unfortunately, the list of filters is fixed and can't be configured. 

I would gladly modify the code to allow the definition of extra entries in that list. So, in my case, I can exclude the conflicting files from my Uber Jar directly from within my pom.xml file.

Thoughts?

**Comment by Sanne** [comment]
Allowing users to customize the list of exclusions by configuring the `quarkus-maven-plugin` is a good idea.

**Comment by esteban-aliverti** [comment]
@Sanne I've created a new PR which includes the latest modifications from master and that adds support for this feature in both, the maven and the gradle plugin.

**Comment by esteban-aliverti** [comment]
The PR was approved and merged? Should I close this issue? Or is this something you guys will do?
Thanks for all the support!

**Comment by Sanne** [comment]
right, this should have been closed. Thanks again!
