### ISSUE TITLE
Issue building an uber-jar with getting-started application

### ISSUE THREAD

**Issue by ahamed-k** [quarkusio/quarkus#19342]
### Describe the bug

Faced an issue while building an uber-jar using the getting-started application with minimal changes.
Downloaded getting started application from the link - https://github.com/quarkusio/quarkus-quickstarts.git. Made few changes in application pom.xml and properties files to build an uber jar. An exception was thrown while building an application.

We tried the same in both Windows and Linux environment. 

The build failed with an exception as described in the reproducer in Windows.

Though the build was successful in Linux, it throws ClassNotFoundException: GreetingService when we ran the application.

### Expected behavior

The application should build, generate uber jar and run successfully in both Windows and Linux environments.

### Actual behavior

Build failed with an exception and could nit be resolved.

### How to Reproduce?

Reproducer:

Steps to reproduce the issue:
1. Download the application from - https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started
2. Added configuration > properties to quarkus-maven-plugin in pom to create a uber jar.
         <quarkus.package.output-name>getting-started</quarkus.package.output-name>
	 <quarkus.package.runner-suffix>-1.0.0-SNAPSHOT</quarkus.package.runner-suffix>
	
3. Added the following property in application.properties file.
    _quarkus.package.type=uber-jar_
4. Build the project.
    _mvn clean package_
5. The build failed with exception as below.
    [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.1.1.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: X:\quarkus\quarkus-quickstarts\getting-started\target\getting-started-1.0.0-SNAPSHOT.jar: **The process cannot access the file because it is being used by another process.**
[ERROR]
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:829)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.nio.file.FileSystemException: X:\quarkus\quarkus-quickstarts\getting-started\target\getting-started-1.0.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.
[ERROR]
[ERROR]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
[ERROR]         at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[ERROR]         at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildUberJar(JarResultBuildStep.java:289)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:231)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR]         ... 6 more

[getting-started.zip](https://github.com/quarkusio/quarkus/files/6967909/getting-started.zip)

### Output of `uname -a` or `ver`

MS Windows Version: 10.0.18363.1679

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20    OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)    OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### Quarkus version or git rev

Quarkus 2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Can you help resolve this. Thanks.

**Comment by jaikiran** [comment]
Hello @ahamed-k,

> [ERROR] [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: X:\quarkus\quarkus-quickstarts\getting-started\target\getting-started-1.0.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.

Does this happen every time on your Windows setup? 


> Though the build was successful in Linux, it throws ClassNotFoundException: GreetingService when we ran the application.

It should work fine without issues on Linux. I gave it a try with the getting started. What command do you use to launch the app (uber jar) on Linux? If you are still running into issues related to usage of uber jar on Linux, please create a separate issue for that so that it's easier to discuss and fix any potential problems there.

**Comment by geoand** [comment]
Closing as we did not get feeback
