### ISSUE TITLE
Improve guide for Kafka + Avro projects

### ISSUE THREAD

**Issue by mbrembilla** [quarkusio/quarkus#19350]
Hi all,
following this guide https://quarkus.io/guides/kafka-schema-registry-avro I noticed that it's necessary to add something in the "Creating the Maven Project" section.

If you use Confluent Schema Registry, you don’t need the `quarkus-apicurio-registry-avro`, but if you use Confluent's `kafka-avro-serializer`, the mechanins to auto-generate classes from avro schemas won't work since the `quarkus-avro` dependency will be missing.

In the snippet in the tip maybe you should add the `quarkus-avro` dependency, or at least add a phrases to warn the reader.

Thank you,
Mauro

**Comment by OneCricketeer** [comment]
The guide is specifically using Apicurio, which should probably be clarified better. 

That being said, `kafka-avro-serializer` isn't what is responsible for generating classes, and that **is** meant to be used with the `avro-maven-plugin`

**Comment by Ladicek** [comment]
The guide indeed uses Apicurio Registry, but there's nothing actually preventing anyone from using Confluent Schema Registry. The only required changes are in dependencies, which are mentioned in the guide (#19320 adds the mention of `quarkus-avro`), and in configuration (which is described in https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.8/kafka/kafka.html#kafka-avro-configuration).

**Comment by Ladicek** [comment]
I've added more details about Confluent Schema Registry to my PR, thanks for pushing for it! :-)

**Comment by mbrembilla** [comment]
Yeah I saw! Thank you for improving the guide, very appreciated!

Since we are talking about that guide I have another a little question regarding the [configuration section](https://quarkus.io/guides/kafka-schema-registry-avro#avro-code-generation-details).
I'm trying to compile a schema in order to reference it in the others.

Where should the `avro.codegen` configurations ( especially `avro.codegen.[avsc|avdl|avpr].imports` ) be put?
I tried to write it in my application.yaml file like this:
```
avro:
  codegen:
    avsc:
      imports: eventInfo.avsc
```
and like this:
```
quarkus:
  avro:
    codegen:
      avsc:
        imports: eventInfo.avsc
```
but none of them works because it always says that it doesn't recognise the type EventInfo.

My schemas are:
```
{
    "type": "record",
    "namespace": "xx.yy.ww",
    "name": "EventInfo",
    "fields": [
...
```
```
{
    "type": "record",
    "namespace": "xx.yy.ww",
    "name": "Event",
    "fields": [
        {
            "name": "eventInfo",
            "type": "EventInfo"
        },
...
```
If you think that it's not related to the original question or that this is not the right place to ask it, please tell me and I open it somewhere else like StackOverflow.
Thank you,
Mauro

**Comment by mbrembilla** [comment]
Ok thanks, I'll wait your colleague to come back from the vacation :-)

But I noticed that the issue [#19276](https://github.com/quarkusio/quarkus/issues/19276) is closed, so which is the right place to track that bug and wait for a resolution?

**Comment by Ladicek** [comment]
There's probably no issue open for that specific problem. If you could file one, that would be great!

**Comment by mbrembilla** [comment]
Ok, I'll do it after lunch.
Thank you very much again.
Will this issue be closed automatically when your PR is merged?

**Comment by Ladicek** [comment]
It is linked with the PR, so yes, it should get closed automatically.

**Comment by mbrembilla** [comment]
Sorry, for the dalay. Issue #19389 opened.

Can I ask you another thing?
Prior Quarkus 2 in my Kafka Stream application I used to import Confluent's `kafka-streams-avro-serde` dependency to serialize and deserialize Avro messages created with custom schemas with the SpecificAvroSerde.
WIth the new changes in Quarkus do I still need that dependency or can I obtain the same result in other ways? I don't understand if the automatic schema registration you mention in the guide for both apicuro and confluent schema registry allows me to avoid configuring specific serde for every type of message also in Kafka stream application.

Thank you,
Mauro

**Comment by Ladicek** [comment]
Thanks @mbrembilla! Autodetection of serializer/deserializer class only applies to SmallRye Reactive Messaging, so that doesn't help in Kafka Streams applications.

**Comment by lostiniceland** [comment]
Before opening another issue I would like to check weather this is just a documentation issue or not.

I need to send out some Avro Events to Kafka and I had the avro-maven-plugin setup nicely until I saw that there is a Quarkus extension. In order to stay closer to the Quarkus ecosystem I enabled the extension and removed the avro-maven-plugin (since it is also mentioned as unnecessary with the extension in the docs)

Unfortunately the extension does not seem to work with Avro IDL files (*.avdl) within `src/main/avro` and I'd rather stick to the IDL instead of writing JSON. So what I did now, is to enable the avro-maven-plugin again with goal=idl-protocol.
So now, I do not know if and why I should use the quarkus-avro extension.

Furthermore I am wondering why I still have to provide the kafka-avro-serializer dependency? My expectation was that the extension will pull in all necessary dependencies with the version matching the quarkus-bom. With the additional dependency I am not sure which version plays nicely with Quarkus, which brings me to the conclusion why I should use the quarkus-extension at all.

**Comment by Ladicek** [comment]
> Unfortunately the extension does not seem to work with Avro IDL files (*.avdl) within `src/main/avro` and I'd rather stick to the IDL instead of writing JSON. So what I did now, is to enable the avro-maven-plugin again with goal=idl-protocol. So now, I do not know if and why I should use the quarkus-avro extension.

I'm not entirely sure, but I don't think we've considered supporting the Avro IDL. Please file a feature request.

> Furthermore I am wondering why I still have to provide the kafka-avro-serializer dependency? My expectation was that the extension will pull in all necessary dependencies with the version matching the quarkus-bom. With the additional dependency I am not sure which version plays nicely with Quarkus, which brings me to the conclusion why I should use the quarkus-extension at all.

What Quarkus extension are you talking about? If you mean `quarkus-confluent-registry-avro`, the reason why you still have to add dependencies on the Confluent Schema Registry libraries is that they are not available in Maven Central. I realize this is less pleasant for users, but we will not rebuild those libraries to be able to publish them to Central (too big of a maintenance burden), and will not put the Confluent repository declaration to any of Quarkus POMs (discouraged by the Central guidelines, brings risks to build stability, not acceptable for downstream rebuilds). Confluent really should publish their libraries to Central, and it's their decision not to.

**Comment by lostiniceland** [comment]
Thanks for the quick reply. I didnt realize that the Confluent deps are not coming from Central since it is proxied in our corporate environment and its understandable that you are not shipping those then.
I will file a request regarding the IDL support.

**Comment by ozangunalp** [comment]
As far as I can tell the Avro IDL (*.avdl) files are already supported.
