### ISSUE TITLE
Spring Properties: Can't inject values using complex SpEL

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19368]
### Describe the bug

Having this class:

```
@RestController
@RequestMapping("/values")
public class ValueController {

    @Value("${values.text}")
    String fieldUsingValue; // works

    @Value("${values.list}")
    String[] fieldUsingArray; // works

    @Value("#{'${values.list}'.split(',')}")
    List<String> fieldUsingList; // does not work

    @Value("#{${values.map}}")
    Map<String, String> fieldUsingMap; // does not work

   // ...
}
```

Note the SpEL expressions I checked and that according to the Spring documentation should work.
This is the application properties I'm using:

```
values.text=hello
values.list=A,B
values.map={key1: '1', key2: '2', key3: '3'}
```

### Expected behavior

To be honest, I'm not sure how complex is to make the SpEL engine to work using the Quarkus configuration engine.
If this is too complex, I guess we should note this limitation in the Spring Properties guide.

**Comment by geoand** [comment]
Thanks for reporting, but this is not something we plan to support given the complexity involved in implementing it and the niche use case it addresses.

At best, we can print an error message mentioning this.
