### ISSUE TITLE
Spring Config: Using `@ConfigurationProperties` to inject maps does not work

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19366]
### Describe the bug

Spring users can bind maps like this:

```
@ConfigurationProperties("maps")
public class MapWiringProperties {

    // Cover injection of maps of integers and strings;
    public Map<Integer, String> integers;

    // Cover injection of maps of string and classes
    public Map<String, Person> persons;

    public static class Person {
        public String name;
        public int age;

        @Override
        public String toString() {
            return String.format("person[%s:%s]", name, age);
        }
    }
}
```

With application.properties:

```
maps.integers.1=Value 1
maps.integers.2=Value 2

maps.persons.character1.name=Sarah
maps.persons.character1.age=19
maps.persons.character2.name=Terminator
maps.persons.character2.age=999
```

If we try to use the same using the spring properties Quarkus extension, it throws the following exception:

```
Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for interface java.util.Map
```

### Expected behavior

Not sure if this is very complex to mimic in the Quarkus extension (we should generate the equivalent object using the `@ConfigMapping` annotation.
However, if this is too complex to support, we should document the current limitations in the Spring properties guide.

**Comment by geoand** [comment]
This is a known limitation of `@ConfigProperties`. We should just print a more relevant error message.

I'll do that when I get back from PTO
