### ISSUE TITLE
Possibility for Continuous Testing Mode to also execute tests in other modules in multi module project 

### ISSUE THREAD

**Issue by tbvl** [quarkusio/quarkus#19362]
### Description

The Continuous Testing Mode works well also when working in multi module project. Changes to sources files are detected in dependent modules and tests in the Quarkus module are re-run. 

But currently its not possible to also include (unit) tests in dependent modules to also be run in Continuous Testing Mode, which would be a nice feature in a multi-module project.

### Implementation ideas

Given the basic scenario:

- Root project (pom)
  - app1 (jar) Common code and unit tests - general java project no Quarkus runtime setup
  - app2 (jar) Quarkus project including Service definition and QuarkusTests on services - depends on app1.

Currently changes to unit tests are discovered on top of changes to "normal" source files when inserting a test dependency in app2 pom, like:

```
<!-- app2/pom.xml -->
<dependency>
	<groupId>com.myapp</groupId>
	<artifactId>app1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
</dependency>			

<!-- Dependency on test classes. Note: App2 needs the same test scoped dependencies defined in the POM as App1 to allow hot code reload to work in App2 -->

<dependency>
	<groupId>com.myapp</groupId>
	<artifactId>app1</artifactId>
	<classifier>tests</classifier>
	<type>test-jar</type>
	<scope>test</scope>
	<version>0.0.1-SNAPSHOT</version>
</dependency>
```
Would it be possible in the setup to also include app unit test in execution in Continuous Testing Mode?

**Comment by stuartwdouglas** [comment]
This is doable, but is moderately complex. I had been thinking about this but because of the amount of work involved I was going to wait and see if there was demand for it.

**Comment by tbvl** [comment]
@stuartwdouglas It would definitely be of high value for my team and I since we are "forced" to work in multimodule setup, but I can also see why it is a more complex undertaking. I cannot contribute much on the implementation side currently, but I can offer to test and mature any experimental / beta-releases of the feature on our setup.

**Comment by stuartwdouglas** [comment]
I will have a look into it. It will use more memory because every module has its own test classpath, but it should not really be an issue.

**Comment by famod** [comment]
If this is implemented, there should be an opt in or out.
Why? My current project consists of 7 modules and we can dev mode in most of them, but we only build the actual final app in a single module.
With this setup, it would not make much sense to run all tests, also because we have QuarkusTests (partially with TestProfiles) all over the place.

**Comment by stuartwdouglas** [comment]
Each module will have its own class path setup and run in an isolated manner. It might surprise you how well it actually works. 

That said, there will definitely be the option to limit the tested modules.

**Comment by stuartwdouglas** [comment]
PR is ready, it would be great if you could try it out and give some feedback.

**Comment by tbvl** [comment]
> PR is ready, it would be great if you could try it out and give some feedback.

Cheers, will take it for a spin today and let you know.
