### ISSUE TITLE
Dev UI - Test report output not visible

### ISSUE THREAD

**Issue by vgallet** [quarkusio/quarkus#19374]
### Describe the bug

On Dev UI, test result output is on black background with black font color and so is not visible, as shown in the picture below.

<img width="809" alt="Capture" src="https://user-images.githubusercontent.com/8947458/129197768-abfa8584-1962-4850-a7a2-08bc3b38f5bd.PNG">

### Expected behavior

Test output should be visible.

### How to Reproduce?

Run `mvn quarkus:dev` with continuous testing enabled.
Press `d` to open Dev UI
Go to Tests Results and double click on test names to see the output 

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19042.1110]

### Output of `java -version`

OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### Additional information

Google Chrome Version 92.0.4515.131

**Comment by phillip-kruger** [comment]
@vgallet - I can not seem to recreate this, it looks ok on my env. Can you share more details ? Is there anything in the browsers console ?

![image](https://user-images.githubusercontent.com/6836179/129354177-a4efb098-fcde-4645-8ded-d1b6806808e1.png)

**Comment by phillip-kruger** [comment]
@vgallet also maybe open the log in and see if that is styled correctly: 

![image](https://user-images.githubusercontent.com/6836179/129354369-bbe9dc9c-743b-41b0-b6cd-ef79a4964128.png)

**Comment by vgallet** [comment]
sorry for the delay, I take a look today. which part of the style are we looking for ?

**Comment by phillip-kruger** [comment]
All of them :) So check the test result page (as in your original bug report) and also open the log (as the screenshot above)

Let me know. Thanks
