### ISSUE TITLE
Trivial project setup fails to build with Dockerfile.multistage example

### ISSUE THREAD

**Issue by artempl** [quarkusio/quarkus#19375]
### Describe the bug

Generate sample project. Take Dockerfile.multistage from documentation.

Try to build with command:

`
docker build -f src/main/docker/Dockerfile.multistage -t quarkus-quickstart/getting-started .
`

### Expected behavior

Success build

### Actual behavior

Build fails with message:
`
Step 12/16 : COPY --from=build /project/target/*-runner /work/application

COPY failed: no source files were specified
`

### Output of `uname -a` or `ver`

Linux 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

2.1.2.Final

### Additional information

docker --version
Docker version 20.10.8, build 3967b7d

**Comment by geoand** [comment]
Is this still an issue?

**Comment by artempl** [comment]
Dockerfile on site has been updated but it also fails. Here is workaround that works for 
![Screenshot from 2021-09-30 10-11-36](https://user-images.githubusercontent.com/4968093/135404922-01cf5aed-ce6c-4135-b009-cd8dae8c6e89.png)
me

**Comment by manovotn** [comment]
I tried this and I am no longer seeing the error.
@artempl feel free to reopen if you disagree.
