### ISSUE TITLE
Cannot turn off http server

### ISSUE THREAD

**Issue by raducrisan1** [quarkusio/quarkus#19370]
### Describe the bug

I've created an app on top on v2.1.2 final and my container would not start if I try to disable http via env variable. The variable is: QUARKUS_HTTP_HOST_ENABLED with the value 0. 

### Expected behavior

The app or the container would start.

### Actual behavior

I've encountered an error while the container was starting. The error was: 

```
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 2021-08-12 10:52:51,505 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Must configure at least one of http, https or unix domain socket
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:899)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
hpc_producer-1.1.zehhlbpzwpf0@hzamd-node01    | 	at java.base/java.lang.Thread.run(Thread.java:834)

```

### How to Reproduce?

1. Create a quarkus app from maven
2. Add a resource adnotated with @Path
3. Either set in application.properties '''quarkus.http.host-enabled=false''' or set the env variable QUARKUS_HTTP_HOST_ENABLED=0
4. Try to start the app mvn quarkus:dev or attempt start the container, if a docker image has been created.

### Output of `uname -a` or `ver`

Linux hzamd-node01 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06) OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 21.0.0.2

### Quarkus version or git rev

2.1.2 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by famod** [comment]
@stuartwdouglas A had a brief look at the code involved in this and I find it irritating that this flag is only evaluated pretty far down in the recorder:
- https://github.com/quarkusio/quarkus/blob/2.2.1.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L584 (https)
- https://github.com/quarkusio/quarkus/blob/2.2.1.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L761 (http)

Shouldn't there be something like `startSocket && (httpConfiguration.hostEnabled || httpConfiguration.domainSocketEnabled)` at least as high up as here: https://github.com/quarkusio/quarkus/blob/2.2.1.Final/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L247
?
