### ISSUE TITLE
Error reading ConfigMapping in constructor injection

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#19387]
### Describe the bug

I want to specify a `@ConfigMapping` on a parameter in the injection constructor, such that it is used then thrown away. This causes an unsatisfied dependency error on build. This may be unsupported behavior, in which case feel free to retag this as an enhancement.

### Expected behavior

The ability to read config mappings in an injection constructor.

### Actual behavior

```
        Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type my.project.service3.config.Service3Config and qualifiers [@Default]
        - java member: my.project.service3.Service3Handler#<init>()
        - declared on CLASS bean [types=[my.project.service3.Service3Handler, java.lang.Object], qualifiers=[@Default, @Any], target=my.project.service3.Service3Handler]
```

### How to Reproduce?

Reproducer: `service3` in https://github.com/mweber03/quarkus-test

1. `./gradlew service3:quarkusBuild`

application.yaml
```
app:
  data1:
    name: Bob
    num: 100
  data2:
    name: Tim
    num: 30
```

java
```
@Dependent
public class Service3Handler {

    private final String value1;
    private final String value2;

    @Inject
    public Service3Handler(@ConfigMapping(prefix = "app.data1") final Service3Config config1,
            @ConfigMapping(prefix = "app.data12") final Service3Config config2) {
        this.value1 = String.format("%s-%s", config1.name(), config1.num());
        this.value2 = String.format("%s-%s", config2.name(), config2.num());
    }

    public String getValue1() {
        return this.value1;
    }

    public String getValue2() {
        return this.value2;
    }
}
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

**Comment by radcortez** [comment]
Hum... it should work. Let me have a look.

**Comment by radcortez** [comment]
@mweber03 you are missing the `@ConfigMapping` annotation in your config interface.

I also added a test to Quarkus and it does work as expected.

**Comment by mweber03** [comment]
@radcortez I disagree that your test actually tests anything.

Your test works because `@ConfigMapping(prefix = "config")` is on the `MyConfigMapping` interface, not because its on the injection constructor. If you removed the annotation from the injection constructor, it would still work. So basically putting the annotation in a constructor is pointless because it needs to be on the interface class regardless.

What I was hoping to do is share the interface class between two configs, but I can't do this if the config prefix needs to be on the interface class. This actually used to work with the quarkus arc `@ConfigPrefix` (if you replace the annotation below).

Example of what I was trying to do:
```java
public interface Service3Config {
    String name();
    int num();
}

public class Service3Handler {

    @Inject
    public Service3Handler(@ConfigMapping(prefix = "app.data1") final Service3Config config1,
            @ConfigMapping(prefix = "app.data2") final Service3Config config2) {
        ...
    }
}
```

**Comment by radcortez** [comment]
The annotation in the constructor is to override the prefix used in the injection point.

@mweber03 yes, the config mapping interface requires the annotation and the injection in the constructor works without it, but you can definitely reuse the same interface with different prefixes by overriding the injection point with the `@ConfigMapping` annotation and setting the new prefix. I'll add a test for that use case.
