### ISSUE TITLE
Service attempts to find a config value for an unused bean

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#19388]
### Describe the bug

I have a library with multiple beans in it, each containing config values. I also have a service that only injects one of those beans. But at runtime there is an error attempting to find the config value for the bean that is not used in the service.

Note: I'd like to not use default config values so that anyone actually injecting the bean is required to add it to the config.

### Expected behavior

Successful run.

### Actual behavior

Error find config value for unused bean.

### How to Reproduce?

Reproducer: `service4` in https://github.com/mweber03/quarkus-test

1. `./gradlew service4:quarkusBuild`
2. `docker build -t service4 -f modules/service4/Dockerfile .`
3. `docker run -it -p 8080:8080 service4`

Library with beans: `lib2`

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

**Comment by radcortez** [comment]
@mweber03  There is no `service4` branch or `service4` folder in the project structure.

**Comment by mweber03** [comment]
@radcortez Forgot to push, my bad. It's there now.
