### ISSUE TITLE
The application stuck when see this -- Tests paused Press [r] to resume testing, [o] Toggle test output, [h] for more options>

### ISSUE THREAD

**Issue by jdang67** [quarkusio/quarkus#19395]
### Describe the bug

1. Start the  app in debug mode:   ./mvnw compile quarkus:dev
2. Stop the application: Ctrl+C
Sometimes, the app does not stop but show
"Press [r] to resume testing, [o] Toggle test output, [h] for more options>"
try r, o, h or Ctrl+C nothing works. The only option is to restart the IDE

### Expected behavior

The app should stop and return the control to the developer

### Actual behavior

"Press [r] to resume testing, [o] Toggle test output, [h] for more options>"

### How to Reproduce?

1. Start the  app in debug mode:   ./mvnw compile quarkus:dev
2. Stop the application: Ctrl+C
Sometimes, the app does not stop but show
"Press [r] to resume testing, [o] Toggle test output, [h] for more options>"
try r, o, h or Ctrl+C nothing works. The only option is to restart the IDE

### Output of `java -version`

16.0.2

### Quarkus version or git rev

2.1.2.Final

**Comment by gsmet** [comment]
Could you run a `kill -3 <pid>` when it's stuck so that we get a stack dump?

**Comment by jdang67** [comment]
Thanks for your help. However, the dump file is too big to send by email.

**Comment by jaikiran** [comment]
Which operating system are you on? Is it possible you are hitting the same issue as https://github.com/quarkusio/quarkus/issues/19392? Does the thread dump that you captured look similar to what is pasted in the comments in that issue?

**Comment by stuartwdouglas** [comment]
I think this is likely fixed, there have been various deadlocks fixed in this area.
