### ISSUE TITLE
Dev Services for Redis should print out the connect string

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19397]
### Description

When Dev Services for Redis starts a redis container it should print out the connection string (i.e. `redis://localhost:55043`). This would be very helpful if I want to manually connect the redis cli to the cluster. Right now to get this I have to go into the config editor through the Dev UI to find it.

The dev services for Kafka does this, which is really nice:
```shell
INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-53) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://localhost:55046
```

**Comment by hieunc278** [comment]
Dear @machi1990,
Could I update for this ?

**Comment by machi1990** [comment]
Yes, it is free for grabs. Thanks for taking up on this @hieunc278
