### ISSUE TITLE
Remove dependency to weld

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#19393]
### Description

quarkus-rest-client transitivly pulls in weld.

This causes some annotations to be present multiple times, from different packages (e.g. javax.enterprise.context.control.ActivateRequestContext and org.jboss.weld.context.activator.ActivateRequestContext)

Can the dependency to weld please be removed?
```
[INFO] │  │     └─ io.quarkus:quarkus-rest-client:jar:2.1.2.Final (compile)
[INFO] │  │        ├─ org.jboss.resteasy:resteasy-client-microprofile:jar:4.7.0.Final (compile)
[INFO] │  │        │  └─ org.jboss.resteasy:resteasy-client-microprofile-base:jar:4.7.0.Final (compile)
[INFO] │  │        │     ├─ org.jboss.resteasy:resteasy-client:jar:4.7.0.Final (compile)
[INFO] │  │        │     │  └─ org.jboss.resteasy:resteasy-client-api:jar:4.7.0.Final (compile)
[INFO] │  │        │     ├─ org.jboss.resteasy:resteasy-cdi:jar:4.7.0.Final (compile)
[INFO] │  │        │     │  └─ org.jboss.weld:weld-api:jar:3.1.SP4 (compile)
[INFO] │  │        │     └─ org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0 (compile)
[INFO] │  │        └─ org.apache.httpcomponents:httpasyncclient:jar:4.1.4 (compile)
[INFO] │  │           └─ org.apache.httpcomponents:httpcore-nio:jar:4.4.14 (compile)
```

**Comment by famod** [comment]
/cc @mkouba @manovotn (because of the CDI relevance, just in case)

PS: I wonder whether we should ban weld dependencies globally.

**Comment by gsmet** [comment]
Yeah, this is tricky. `resteasy-cdi` depends on Weld-specific API AFAICS so I have no idea how it could work with ArC. @michalszynkiewicz could you have a closer look to this? My guess is that we should probably drop the dependency to `resteasy-cdi` and have our own ArC based implementation.

**Comment by jamezp** [comment]
It looks like there's only one place where Weld is explicitly used in resteasy-cdi. I've filed https://issues.redhat.com/browse/RESTEASY-2986 to have a look at that. I would hope it could be removed.

**Comment by gsmet** [comment]
Tbh, I have no idea if we need `resteasy-cdi` around, I hope @mkouba or @michalszynkiewicz will shed some light on this.

**Comment by jamezp** [comment]
I would kind of expect you don't. Not to distract too much, but maybe @mkouba could let me know if there is a way around [this](https://github.com/resteasy/Resteasy/blob/7f718a8955eba609f9a0bbef3bc460d5c39fc673/resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/CdiPropertyInjector.java#L61-L65) with just the API :)

**Comment by manovotn** [comment]
@jamezp looks like you are using Weld API to check if the `delegate` is an object you want to inject into, or just a proxy that you first need to "unwrap". In that case, there is no CDI API solution to unwrapping so you cannot easily remove the dep :-/

**Comment by jamezp** [comment]
Excellent, thanks @manovotn. I suspected we could not remove the dependency, but thought there was maybe some API I wasn't aware of :)

**Comment by gsmet** [comment]
@manovotn but are we using `resteasy-cdi` in Quarkus? It looks like a CDI extension and we don't support them AFAIK so I suspect the CDI integration in the REST Client relies on something else.

Maybe @michalszynkiewicz would know?

**Comment by michalszynkiewicz** [comment]
I don't know. I can try to investigate it

**Comment by manovotn** [comment]
@gsmet good point, I don't know from the top of my head and you're right that the module contains a classic CDI portable extension which just doesn't work with Quarkus.
It looks like we don't need that module at all for Quarkus...

**Comment by michalszynkiewicz** [comment]
I tried and handling `@ClientHeaderParam` fails without it, I'll see if I can work around it.

**Comment by michalszynkiewicz** [comment]
Dropping resteasy-cdi altogether is doable but requires copying some classes to Quarkus. Simple exclusion on weld-api is what I think is the best in this scenario. https://github.com/quarkusio/quarkus/pull/19611 does that
