### ISSUE TITLE
Warning SRCFG01005 when using quarkus.config.locations

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#19390]
### Describe the bug

I use quarkus.config.locations in all my projects to specifiy a custom configuration file in dev mode.

Since the update to quarkus 2.1, i get the following warning on dev mode start. The abc in the second line is the configuration value inside the custom-configuration-file.properties.

This is only a warning, and all configuration values are still read from the file.

```
2021-08-13 10:34:16,363 WARN  [io.sma.config] (main) SRCFG01005: Could not find sources with smallrye.config.locations in custom-configuration-file.properties
abc
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
```

application.properties:
```
quarkus.config.locations=custom-configuration-file.properties
```

custom-configuration-file.properties
```
some.value=abc
```

Code:
```
@ConfigProperty(name = "some.value")
    String configValue;

    @PostConstruct
    void init() {
        System.out.println(configValue);
    }
```

### Expected behavior

No warning about missing config locations.

### Actual behavior

The warning from above is logged. The configuration is still read.

### How to Reproduce?

Download the reproducer: [cnfe-jaxb.zip](https://github.com/quarkusio/quarkus/files/6981165/cnfe-jaxb.zip)
mvn quarkus:dev
the warning is logged. The configuration value is output as the next line (abc)

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk 11.0.7 2020-04-14 LTS OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin\.. Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
Will be fixed with https://github.com/smallrye/smallrye-config/pull/632.
