### ISSUE TITLE
No (mock) injection when using @Nested JUnit tests

### ISSUE THREAD

**Issue by timovandeput** [quarkusio/quarkus#19391]
### Describe the bug

Mock injection is not performed before execution of unit tests inside nested test classes.

### Expected behavior

Attributes of the top level class annotated with `@InjectMock` are injected before the tests of `@Nested` test classes are executed.

### Actual behavior

Attributes annotated with `@InjectMock` are `null`.

### How to Reproduce?

A test like this fails because the `service` is not injected:

```java
@QuarkusTest
class TestClass {
    @InjectMock
    private MyService service;

    @Nested
    class NestedTest {
        @Test
        void myTest() {
            assertNotNull(service);
        }
    }
}
```

And it passes if the nested class wrapper is removed.

### Output of `uname -a` or `ver`

2.1.0.Final

### Output of `java -version`

11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by geoand** [comment]
Pinging @geoand to put this on my radar
