### ISSUE TITLE
Can Scala 2 and Scala 2 Jackson be moved out of the BOM and into a Scala 2 Quarkiverse? (Scala is not ABI compatible)

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#19405]
### Description

The short way of explaining this is that, unlike Java and Kotlin which are generally ABI compatible between versions, Scala's ABI compatibility story is a bit of a mess.

The short of it is that:
- Scala 3 is backwards compatible with Scala `2.13.x` ONLY

But to complicate matters further, here's an example:
- Scala 3 Compiler `3.0.1` pulls in
- Scala 3 Library 3 `3.0.1` which then pulls in
- Scala 2 Library `2.13.6`

Now, if you have other Scala 2 dependencies in your build, here's what happens:
- Scala `2.12`
	- Bad News Bearz
- Scala `2.13` **lower** than the `2.13` the Scala 3 Compiler/Library uses
	- They will be reconciled to this lower version, which _shouldn't_ have any problems but may not be what you want

---

Because **Quarkus has Scala 2.12 in it's BOM**, it causes a lot of problems.

- The first is that, if you try to add Scala 3 Compiler for the `quarkus-scala3` extension, it flat out breaks. 
	- Why? Because Maven sees `scala-library:2.12.13` in `quarkus-bom` and decides this is the version that ought to be used for the transitive dependency from the Scala 3 compiler.
	- This is an unusable combination of versions for Scala 3, no code will compile. It took me a few hours to figure out what was going on here (why the `scala-library` was getting force-set to `2.12` when Scala 2 needs `2.13.5/6`)
- So you need to manually set a Scala 2 library version that matches the one your Scala 3 version uses, and you need to be aware that you need to do this

Alternatively, if you're using Gradle, you can do this:

```gradle
dependencies {
    // scala3-compiler_3 resolve it's own scala3-library_3, and transitively scala-library (Scala 2)
    implementation "org.scala-lang:scala3-compiler_3:$Versions.SCALA3"

    // Quarkus comes with Scala 2 distributed in it's Bill-of-Materials unfortunately =/
    // It's Scala 2.12.13, which is not ABI compatible. If using Scala 3, we need to exclude this entirely
   implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))  {
         exclude group: 'org.scala-lang', module: 'scala-library'
    }
```

It's the same sort of story with `jackson-module-scala_2.12`.
Scala 3 is only compatible with `jackson-module-scala_2.13` and `jackson-module-scala_3` unfortunately 🙁 

I know this may be somewhat complicated by this unfortunate sentence in the BOM:
```xml
        <!-- Scala is used by Kafka so we need to choose a compatible version -->
        <scala.version>2.12.13</scala.version>
```

Though I will note:
- https://kafka.apache.org/downloads

Changing the version to 2.13 would fix a LOT of these headaches due to `2.13 <-> 3.x` binary compatibility

![image](https://user-images.githubusercontent.com/26604994/129486744-4bad68bf-ac8e-4404-ae69-3ab00dbeaf21.png)

**Comment by GavinRay97** [comment]
Wow bot, you tagged a LOT of the wrong people.

Sorry Justin, who I _definitely_ know this has nothing to do with 😅

**Comment by maxandersen** [comment]
Scala isn't something I've seen used much so I'm not that concerned about "breaking" current user base. 

Moving scala to quarkiverse wether it's version 2 or 3 makes sense to me.

**Comment by aloubyansky** [comment]
+1

**Comment by gastaldi** [comment]
+1, we should rename the quarkiverse/quarkus-scala3 repo to quarkus-scala too

**Comment by GavinRay97** [comment]
So then in that case, I think the remaining questions are roughly something like:

```xml
<!-- Quarkus BOM -->
<!-- Scala is used by Kafka so we need to choose a compatible version -->
<scala.version>2.12.13</scala.version>
```

1. Is removing this from BOM going to break all of Quarkus' Kafka stuff? 😬 
	- If so, a quick + easy fix would be to just change Scala version to `2.13.5`, which is what Kafka 2.8 uses:
		- https://mvnrepository.com/artifact/org.apache.kafka/kafka_2.13/2.8.0
	- Then Scala `3.x` _should_ work with all Quarkus Scala stuff in classpath (due to `2.13.x` ABI compatibility)
		- Users COULD override the Scala 2 library version manually if they REALLY want to use a more recent one
			- (The latest is `2.13.6`, and change infrequently compared to Scala 3's versions)

2. Touching on this comment:
> We should rename the `quarkiverse/quarkus-scala3` repo to `quarkus-scala` too as part of this migration

I'm not opposed to this, BUT:
- Both `Scala 2` and `Scala 3` use the same `.scala` extension
- But require different compiler API's and have different syntax

If there is a way to make `quarkiverse/quarkus-scala` work for both "languages" that's probably cleaner than having `quarkiverse/quarkus-scala` or `quarkiverse/quarkus-scala2` and `quarkiverse/quarkus-scala3` -- but it might need to be something like a versioning trick.

IE, could publish the Scala 2 compiler code on the `quarkiverse:quarkus-scala:2.X.X` artifact coordinates and the Scala 3 compiler code at `quarkiverse:quarkus-scala:3.X.X`

Reason being they use different compiler libraries, dependencies, compiler options, etc.

**Comment by gastaldi** [comment]
@GavinRay97 you  can have a multimodule project containing quarkus-scala2 and scala3 extensions. Sure, you can also version in different branches if you want

**Comment by GavinRay97** [comment]
> @GavinRay97 you can have a multimodule project containing quarkus-scala2 and scala3 extensions. Sure, you can also version in different branches if you want

Ahh a "multi-module" -- sounds solid to me 👍

**Comment by famod** [comment]
Coming from https://github.com/quarkusio/quarkus/pull/24546#issuecomment-1083171087, what's the state of this?

Is there any use of further maintaining scala 2 in the main repo?

**Comment by gsmet** [comment]
Oh one more thing: I'm perfectly fine with us taking drastic decisions and getting rid of the Scala support in codestarts. I just didn't want in the way of all the other moves I had to do so I didn't want to start a discussion about it then.

**Comment by famod** [comment]
@gsmet what about doing one more update for scala 2 (to 2.13.8) in Quarkus 2.9 and document in the migration guide that it will be the last one and user's will have to migrate to the quarkiverse extension?
I could do that update (CI looks ok in my fork), but I'd need to know how you tested debezium back then: https://github.com/quarkusio/quarkus/pull/10053#issuecomment-645444103

Someone would need to add Scala 2 support to that quarkiverse extension before we can remove it from the main repo, though...

**Comment by famod** [comment]
FTR: In quarkus 2.9, Scala was updated to 2.13.8 via #25106

**Comment by grossws** [comment]
And it was sudden breaking change for those who had dependency on scala 2.12. Had to forcefully downgrade it to 2.12.x

**Comment by GavinRay97** [comment]
Scala 2.13 is ABI compatible with Scala 3.x, unlike Scala 2.12
This is great news, it means +v2.9 BOM won't cause compat issues with Scala 3 and users shouldn't have to modify their dep rules
