### ISSUE TITLE
Maven plugin `quarkus:add-extension` should add more than just import

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#1940]
When I add extensions like `resteasy` or `hibernate-orm` or `hibernate-orm-panache` I want to add a REST endpoint in the first case, and default config and an entity in the second case.

Is this something we can do or does it belong in another tool?

**Comment by cescoffier** [comment]
That's something I would love to have! 

It would require that the extension list give the set of properties that need to be copied to the application configuration.

**Comment by Dufgui** [comment]
In my opinion, it's quite simple to add some extra data in devtools-common, but I think we want something not centralized. Each plugin must provide it's own templated files. 
So 2 ways:

1. We ask to gradle or maven to download it, and the we explore them to get the templated file and produce them
2. We let them with a properties in maven or gradle and on the next build we generate the file by the extension and remove the properties to not do it again at next build

Any other idea ?
@cescoffier @FroMage

**Comment by ia3andy** [comment]
This is a must have and going to be part of #8134

**Comment by Dufgui** [comment]
Could I help on this. ? Nobody reply to me but I am really interested on this

**Comment by Dufgui** [comment]
Hello, i see the introduction of codestart in devtools platform. So i think you can close it.

**Comment by ia3andy** [comment]
Yes we can close it
