### ISSUE TITLE
Leave a note about setting Gradle's console mode to `plain` when using `quarkusDev` or `quarkusTest`

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#19406]
### Description

The `progress` bar at the bottom of gradle can mess up the formatting of output when in continual dev/test mode.

A simple fix is just to set the console mode to be `plain`, which doesn't have the "progress" bar but maintains all other formatting and color from Quarkus:

In `gradle.properties` it can be set:
```properties
org.gradle.console=plain
```
On a per-command basis, by:
```
./gradlew run --console=plain
```

Example of "plain" output:

![image](https://user-images.githubusercontent.com/26604994/129490509-9cc692f6-d60e-4b2e-81a3-9ebcb6eebec9.png)

**Comment by stuartwdouglas** [comment]
This is already here: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/gradle-tooling.adoc#development-mode

Also the 'quarkus dev' CLI command works even better.
