### ISSUE TITLE
Guides about JSON support misleading

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#1942]
I went to https://quarkus.io/guides/ trying to find how to write a JSON web client, so searched for `json` and only found https://quarkus.io/guides/rest-json-guide which does not even mention a client.

My first impression was that we just did not support JSON web clients. We should make sure this never happens.

We need to make sure people find the rest client guide from the rest server guide, and vice-versa. Especially since the REST client guide at https://quarkus.io/guides/rest-client-guide does mention the JSON dependency as a first thing. Both of these guides should point to each other, and the index page should make them both discoverable with the `json` term.

**Comment by gsmet** [comment]
Is it really an issue?

In the TOC on the right of the guides page, you have:
 * Writing REST JSON Services
 * Validation with Hibernate Validator
 * Using the REST Client

That seems good enough to me.

**Comment by FroMage** [comment]
It's really not good enough. This works only for people who think "I want a client" but not for people who think "I need to call a JSON service". We have to make sure every kind of user finds our way in our documentation.

**Comment by gsmet** [comment]
@FroMage could you either create a PR or close this one? I don't think it's worth keeping it open for months.

Thanks.

**Comment by FroMage** [comment]
OK: #5465

**Comment by FroMage** [comment]
And https://github.com/quarkusio/quarkusio.github.io/pull/371
