### ISSUE TITLE
Jackson extension should provide configuration for serializing null or empty values 

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#19428]
### Description

I wrote a ObjectMapperCustomizer to configure jackson, since it is not possible to do that through the config, as stated here:

https://quarkus.io/guides/all-config#quarkus-jackson_quarkus-jackson-jackson
At this point it offers:
qarkus.jackson.fail-on-unknown-properties
quarkus.jackson.fail-on-empty-beans
quarkus.jackson.write-dates-as-timestamps
quarkus.jackson.accept-case-insensitive-enums
quarkus.jackson.timezone

but not to change the default for null or empty values as I did here:
https://pastebin.com/ayxrMBWn

        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);

**Comment by famod** [comment]
Good suggestion! 👍 But it only makes sense to set _one_ inclusion, not multiple ones, right? That's how I understood the api docs.

**Comment by gastaldi** [comment]
Something like `quarkus.jackson.serialization-inclusion=always` accepting the `com.fasterxml.jackson.annotation.JsonInclude.Include` enum would be nice

**Comment by lferna** [comment]
> Something like `quarkus.jackson.serialization-inclusion=always` accepting the `com.fasterxml.jackson.annotation.JsonInclude.Include` enum would be nice

Is there any possibility to use this config in one field something like @JsonInclude(Include.ALWAYS) ?

**Comment by geoand** [comment]
Nope, it's a general setting
