### ISSUE TITLE
BUILD_AND_RUN_TIME_FIXED configuration is not actually fixed

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#19438]
### Describe the bug

At runtime these classes are not initialized with the build time value. You get a warning but they are initialized from the runtime config.

'Specified build/runtime' values also currently have lower priority than the packaged application.properties, so building with system properties to override config only works if the confg is not present in application.properties.

**Comment by radcortez** [comment]
Fixed in #20932
