### ISSUE TITLE
Setting quarkus.resteasy.path not reflected in OpenAPI or Swagger

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19434]
### Describe the bug

When I set the "quarkus.resteast.path" it works making API calls directly but does not get reflected in the OpenAPI or Swagger.

Using @ApplicationPath and setting eash @Path looks to work.

### Expected behavior

OpenAPI and Swagger reflect the path set in the application properties.

### Actual behavior

RESTful calls works but OpenAPI and Swagger do not reflect the path.  From Swagger invoking an endpoint gives a 404.

**Comment by phillip-kruger** [comment]
Do you perhaps have a small reproducer ?

**Comment by phillip-kruger** [comment]
We have these 2 test cases testing this scenario:

https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OpenApiWithResteasyPathHttpRootDefaultPathTestCase.java

https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/jaxrs/OpenApiWithResteasyPathTestCase.java

**Comment by kjq** [comment]
I tried to build a small reproducer but I am not sure if it is valid or not.

For whatever reason, it seems when I use "quarkus.resteasy.path" it does not get recognized but using "rest.path" does.  I've now managed to confused myself.  Either way, if this is valid, the SwaggerUI does not reflect the path set in the application.yaml.

I will look into it a little more later today but maybe for starters this helps.

[openapi.zip](https://github.com/quarkusio/quarkus/files/7000317/openapi.zip)

![Screenshot 2021-08-17 092207](https://user-images.githubusercontent.com/533810/129734923-f14873b3-0ecc-4aa2-a652-5212d07127d9.png)

**Comment by phillip-kruger** [comment]
Maybe a yaml issue ? Have you tried with application.properties ? (that is how the test cases work)

**Comment by kjq** [comment]
Hmm, just tried with application.properties (just replaced the yaml with an application.properties) and it did the same thing.

As a side note, using the @ApplicationPath "seemed" to work as expected - both OAS and Swagger reflected the path.

**Comment by phillip-kruger** [comment]
Maybe look at the tests I have referenced, and see if you can configure a test so that it replicate your setup ?

**Comment by kjq** [comment]
The "should_have_v1" test give me the error using either the yaml/properties file.  The "should_not_have_v1" passes.

[ERROR] Failures:
[ERROR]   OpenApiTest.should_have_v1_in_path:19 1 expectation failed.
JSON path paths doesn't match.
Expected: map containing ["/v1/ping/me"->ANYTHING]
  Actual: <{/ping/me={get={responses={200={description=OK, content={application/json={schema={type=boolean}}}}}}}}>

[ERROR]   ResourceTest.should_ping_api_using_path:32 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ResourceTest.should_ping_api_without_path:24 1 expectation failed.
Expected status code <404> but was <405>.

```java
@QuarkusTest
public class OpenApiTest {
        private static final String OPEN_API_PATH = "/q/openapi";

        @Test
        public void should_have_v1_in_path() {
                RestAssured.given().queryParam("format", "JSON").when().get(OPEN_API_PATH).then()
                                .header("Content-Type", "application/json;charset=UTF-8")
                                .body("openapi", Matchers.startsWith("3.0"))
                                .body("info.title", Matchers.equalTo("Generated API"))
                                .body("paths", Matchers.hasKey("/v1/ping/me"));
        }

        @Test
        public void should_not_have_v1_in_path() {
                RestAssured.given().queryParam("format", "JSON").when().get(OPEN_API_PATH).then()
                                .header("Content-Type", "application/json;charset=UTF-8")
                                .body("openapi", Matchers.startsWith("3.0"))
                                .body("info.title", Matchers.equalTo("Generated API"))
                                .body("paths", Matchers.hasKey("/ping/me"));
        }
}
```

**Comment by ebullient** [comment]
Yes, should be `quarkus.rest.path`

This may also help:

https://quarkus.io/blog/path-resolution-in-quarkus/

Note that as of 2.x, the redirect behavior has been removed, but the rest is accurate.

**Comment by kjq** [comment]
quarkus.*rest*.path or quarkus.*resteasy*.path?  I am totally confused
now.  The test case I mirrored used *resteasy*.

From the test case...
@RegisterExtension
static QuarkusUnitTest runner = new QuarkusUnitTest()
        .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                .addClasses(OpenApiResource.class, ResourceBean.class)
                .addAsResource(new StringAsset(
"quarkus.resteasy.path=/foo/bar"),
                        "application.properties"));
Either way, both seemed, but i can retest, to give me the same results.  In
fact, my reproducer has the "rest" property just commented out as well.

**Comment by kjq** [comment]
Just confirmed, using my reproducer with a mirrored test case (details on
https://github.com/quarkusio/quarkus/issues/19434) using either "rest" or
"resteasy" gives me the same results.  Using the @ApplicationPath seems to
work.

**Comment by phillip-kruger** [comment]
@kjq thanks for the test cases, looking at this now.

**Comment by phillip-kruger** [comment]
> Yes, should be `quarkus.rest.path`

@ebullient - Are you sure about this ? The test case use `quarkus.resteasy.path`
And the guide also still shows `quarkus.resteasy.path` (see https://quarkus.io/guides/all-config#quarkus-resteasy-server-common_quarkus.resteasy.path) default to `/`

**Comment by phillip-kruger** [comment]
@kjq ok @ebullient confirmed that the `quarkus.resteasy.path` is relative to `rootpath` so the tests are correct. I'll dive a bit deeper today to see if I can recreate your issue.

**Comment by phillip-kruger** [comment]
@kjq @ebullient I can confirm this is a bug. See attached your original reproducer, that is not working for normal requests (as you described) but the value in the openapi document is wrong. I'll prepare a PR to fix a.s.a.p.

If you use resteasy reactive, you need to use `quarkus.resteasy-reactive.path` and not `quarkus.resteasy.path`
[openapi.zip](https://github.com/quarkusio/quarkus/files/7005915/openapi.zip)

**Comment by ebullient** [comment]
> > Yes, should be `quarkus.rest.path`
> 
> @ebullient - Are you sure about this ? The test case use `quarkus.resteasy.path`
> And the guide also still shows `quarkus.resteasy.path` (see https://quarkus.io/guides/all-config#quarkus-resteasy-server-common_quarkus.resteasy.path) default to `/`
>

When we worked on the path support, `quarkus.rest.path` was used. That has since been deprecated (I didn't notice), and replaced with `quarkus.resteasy.path` and `quarkus.resteasy-reactive.path`.. so you're correct. I was remembering old things.

**Comment by phillip-kruger** [comment]
Ok cool ! Thanks for confirming :)

**Comment by magori** [comment]
The documentation https://quarkus.io/guides/resteasy-reactive only talks about this property "quarkus.rest.path" and does not define that it is deprecated.

**Comment by ebullient** [comment]
Can you open a new issue?
