### ISSUE TITLE
In DEV mode, the default landing page should list endpoints

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#1943]
I don't care if it depends on Swagger UI or not, but it should list all registered REST endpoints and some info like the data source used.

The default 404 page should also list those in DEV mode.

**Comment by FroMage** [comment]
![Screenshot from 2019-05-29 16-27-21](https://user-images.githubusercontent.com/179265/58565376-e2ff4f00-822e-11e9-9dfc-1d91d02e038b.png)

For example, for a 404.

Note that OOTB there's also a `/@documentation` url that lands me on the current version of the docs, which is pretty sweet.

**Comment by FroMage** [comment]
Of course, writing such a page would be a lot easier with templates…

**Comment by Dufgui** [comment]
Have you already implemented it? If not I am interesting to make a pr on this. 
For the design. I create a endpoint for this and a custom exception handler to catch the 404 which redirect to it. And ok for the template just like create project ? A ftl file ?
And we can overload the path of endpoint and template with application config ?

**Comment by FroMage** [comment]
This is not implemented yet, but it could be implemented the same way as #2698 (with hardcoded html) until we have support for templating. The trick is going to be how to implement this without depending on RESTEasy which is the one having all the registered URIs that are not servlets.

**Comment by Dufgui** [comment]
we can parse with jandex `@Path`, `@Get`, ... and generate template in io.quarkus.undertow.deployment.devmode package ?

**Comment by Dufgui** [comment]
the custom error handler from resteasy can forward to the generated template file?

**Comment by FroMage** [comment]
No, I think that for RESTEasy we should query the RESTEasy API of registered endpoints. You should be able to get them via `ResteasyDeployment` and `ResourceMethodRegistry`.

**Comment by Dufgui** [comment]
ok, it's work on 404 now, and the template is centralized. I don't create the /@documentation
but I don't know how doing it on compile/deploy phase, so you think i can do it on runtime ?
And i must add return type and real method  and class wich handle the end point.

for the landing page, i don't find it yet, because it seems to be taken by undertow and not by reasteasy. So i must check how to handle them.

Have a nice day

**Comment by FroMage** [comment]
I think we can do the `@documentation` another time. This is already great. So we only need to make sure this runs only in DEV/TEST mode. You can do that in `ResteasyProcessor` by conditionally registering your feature based on a new injected `LaunchModeBuildItem` parameter.

**Comment by Dufgui** [comment]
done, ready for review

**Comment by FroMage** [comment]
Could you open a PR so we can review it properly please?

**Comment by Dufgui** [comment]
it 's already done but the link seems not working , i don't know why

https://github.com/quarkusio/quarkus/pull/2992

**Comment by FroMage** [comment]
Sorry you're right, I missed it.

**Comment by Dufgui** [comment]
seems ok :op
 now i am looking for my next ticket, any proposal ?

**Comment by FroMage** [comment]
Thanks a lot!

I don't have any specific proposal but you can ask on Zulip :)
