### ISSUE TITLE
Cannot deploy "pure" messaging application to Kubernetes

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#19442]
### Describe the bug

If you have an application that does not run an HTTP server, the OpenShift/Kubernetes metadata generation fails with:
```
No Openshift manifests were generated (most likely due to the fact that the service is not an HTTP service) so no openshift process will be taking place
```

It does not fail the build, just do not generate the descriptors and skip the deployment. 

Not having an HTTP server is very likely for pure messaging applications that do not expose an HTTP endpoint.

### Expected behavior

It should still generate the descriptor and proceed with the deployment.

### Actual behavior

It skips the descriptor and deployment.

### How to Reproduce?

Use the kafka-quickstart, go to the `processor` sub-module.
Then run:

```
> mvn quarkus:add-extension -Dextensions="openshift"
> mvn clean package -Dquarkus.container-image.build=true -DskipTests -Dquarkus.container-image.push=true
```

### Output of `uname -a` or `ver`

Darwin bespin.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

no native involved in this issue

### Quarkus version or git rev

main branch (999-SNAPSHOT)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.2

**Comment by cescoffier** [comment]
**Workaround:**

Add the resteasy reactive extension and a dummy resource:


```java
package org.acme.kafka;

import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/dummy")
public class Dummy {

    @GET
    public String hello() {
        return "hello";
    }
    
}
```

**Comment by geoand** [comment]
This is a known limitation that we should lift at some point

**Comment by geoand** [comment]
So if we want to generate the Kubernetes manifests for application that don't listen to HTTP, we just need to generate a `Deployment` without ports and no `Service`. 
Right?

**Comment by cescoffier** [comment]
> Furthermore, I assume there will no readiness and liveness probes

Not HTTP (on the main HTTP interface) ones.
