### ISSUE TITLE
JDBI Extension

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#19447]
### Description

Quoted from [documentation](https://jdbi.org/):

> Jdbi provides convenient, idiomatic access to relational data in Java. Jdbi is built on top of JDBC. If your database has a JDBC driver, you can use Jdbi with it. Jdbi improves JDBC’s rough interface, providing a more natural Java database interface that is easy to bind to your domain data types. Unlike an ORM, we do not aim to provide a complete object relational mapping framework - instead of that hidden complexity, we provide building blocks that allow you to construct the mapping between relations and objects as appropriate for your application.

Some usage examples:

```
// Define your own declarative interface
public interface UserDao {
    @SqlUpdate("CREATE TABLE user (id INTEGER PRIMARY KEY, name VARCHAR)")
    void createTable();

    @SqlUpdate("INSERT INTO user(id, name) VALUES (?, ?)")
    void insertPositional(int id, String name);

    @SqlUpdate("INSERT INTO user(id, name) VALUES (:id, :name)")
    void insertNamed(@Bind("id") int id, @Bind("name") String name);

    @SqlUpdate("INSERT INTO user(id, name) VALUES (:id, :name)")
    void insertBean(@BindBean User user);

    @SqlQuery("SELECT * FROM user ORDER BY name")
    @RegisterBeanMapper(User.class)
    List<User> listUsers();
}
```

```
Jdbi jdbi = Jdbi.create("jdbc:h2:mem:test");
jdbi.installPlugin(new SqlObjectPlugin());

// Jdbi implements your interface based on annotations
List<User> userNames = jdbi.withExtension(UserDao.class, dao -> {
    dao.createTable();

    dao.insertPositional(0, "Alice");
    dao.insertPositional(1, "Bob");
    dao.insertNamed(2, "Clarice");
    dao.insertBean(new User(3, "David"));

    return dao.listUsers();
});
```

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Additional context

[jdbi/jdbi#1890: Support for Quarkus and native image](https://github.com/jdbi/jdbi/issues/1890)

**Comment by gastaldi** [comment]
@Eng-Fouad are you interested in leading the development of this extension? I can setup a Quarkiverse repository for you 😉

**Comment by smil2k** [comment]
@gastaldi We will try to make it work, if it requires extra efforts I'm intending to do that and then I'll ask the author to move it to Quarkiverse

**Comment by Eng-Fouad** [comment]
I was able to run JDBI on Quarkus native image successfully: https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

**Comment by smil2k** [comment]
Create the repo, I'll try my best to find time to work on it.

**Comment by gastaldi** [comment]
Repository https://github.com/quarkiverse/quarkus-jdbi created. Please follow the checklist here for the next steps: https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created

**Comment by smil2k** [comment]
> I was able to run JDBI on Quarkus native image successfully: https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

Hi,

I tried to add your listed classes for constructor reflection along with proxy class discovery:
https://github.com/quarkiverse/quarkus-jdbi

I did not tried it out it only compiles :)

Can you share your entire test jdbi project, I would like to try to test it with the extension?

**Comment by Eng-Fouad** [comment]
@smil2k https://github.com/Eng-Fouad/jdbi-quarkus-native

**Comment by Eng-Fouad** [comment]
@smil2k I added bunch of newly discovered classes that are reflectively accessed: https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

Instead of including all these classes (which in turn increase the native image size), I think the best approach is to inspect the user source code, and include only the necessary classes that will be reflectively accessed.

For example, include

    {"name":"org.jdbi.v3.sqlobject.config.internal.RegisterBeanMapperImpl","methods":[{"name":"<init>"}]}

only if `@RegisterBeanMapper` is used.

**Comment by gastaldi** [comment]
Agreed, that's why using BuildItems is better than having a huge JSON 😉

**Comment by smil2k** [comment]
@gastaldi 
Now I'm officially amazed! Writing this was so much less pain that I expected! Quarkus rocks!

@Eng-Fouad 
I was able to compile your test app using the extension. 

Looking at the classes there is a room for improvement eg probably SqlUpdateHandler is only used if @SqlUpdate is used etc...

But it works now, so It might make sense to try to publish the first beta ;)

**Comment by Eng-Fouad** [comment]
@smil2k I added more details on each class and when to include it: https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

@gastaldi Could you please add me to the project [quarkiverse/quarkus-jdbi](https://github.com/quarkiverse/quarkus-jdbi)?

**Comment by gastaldi** [comment]
@Eng-Fouad I created https://github.com/quarkiverse/quarkiverse-devops/pull/66. Because that's up to the extension lead (@smil2k) to decide, I'll wait until he approves the PR to merge it.

**Comment by smil2k** [comment]
> @smil2k I added more details on each class and when to include it: https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

I've added the processing logic for most of the listed handlers, they are dynamically discovered now. There are many things left out of course.

I think the most urgent matter for now:
1) create a jdbi kitchensink application which is using everything somehow
2) make a beta release

I'll try to find time for at least a basic test and figure out how to release. Feel free to fix anything or create a test on your own in the meantime. 

Cheers

**Comment by gastaldi** [comment]
@smil2k create issues for the missing stuff, this will help you keep track and distribute tasks easily
