### ISSUE TITLE
adding optional environment variable example 

### ISSUE THREAD

**Issue by evanshortiss** [quarkusio/quarkus#19450]
### Description

I ran into this issue today. My application has a properties like so:

```properties
security.header.name=${SECRET_HEADER_NAME:X-3scale-proxy-secret-token}
security.header.value=${SECRET_HEADER_VALUE}
```

I wanted to make the `security.header.value` optional, i.e default to `null` if not found. The issue was that I received `Could not expand value SECRET_HEADER_VALUE in property security.header.value`. If no default value is given.

Eventually I found that adding a colon achieved my desired behaviour `security.header.value=${SECRET_HEADER_VALUE:}`. It seems as though this is interpreted as "use null as the default".

I did not find this in docs/examples though.

### Implementation ideas

Perhaps adding this information to the [Configuration Reference page](https://quarkus.io/guides/config-reference) is a good idea? I can PR it if it helps.

**Comment by geoand** [comment]
I think the docs already have this at https://quarkus.io/guides/config-reference#property-expressions, but feel free to improve them
