### ISSUE TITLE
Kubernetes Config fails on EKS/K8S 1.21 with Service Account Error

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19452]
### Describe the bug

We see these errors when deploying our native service using the latest Quarkus and the "kubernetes-config" extension:
WARN: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring

ERROR: Failed to start application (with profile my-release) io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.100.0.1/api/v1/namespaces/platform-445-staging/configmaps/my-config. Message: configmaps "my-config" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "platform-445-staging".

We are starting to think this is an issue between our K8S upgrade to 1.21 from 1.19.
1.19 - it was working here (no code/config changes)
1.20 - dont know if it works or not we only upgraded here to get to latest
1.21 - does not work

We know it worked before and as a quick test we deployed it into an older cluster (1.17) and it looks to work as-is.

Maybe it is related to this according to the upgrade log for K8S?
**Service account tokens bound to a pod is now a stable feature. The feature gates will be removed in 1.21 release. For more information, refer to notes below on the changelogs.**

We double-checked and redeployed the same service as-is to 1.19 and 1.20 - both of those work as they did before.

### Expected behavior

Deploys into EKS 1.21 as it did before and the configuration can read the config map.

### Actual behavior

Fails to startup in EKS 1.21 with this error:

>kubectl logs my-platform-client-c85ff7478-m7876 -n platform-445-staging 

Aug 06, 2021 4:08:37 PM io.fabric8.kubernetes.client.Config 
WARN: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring. 
Aug 06, 2021 4:08:37 PM io.fabric8.kubernetes.client.Config 
WARN: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Aug 06, 2021 4:08:37 PM io.fabric8.kubernetes.client.Config 
WARN: Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring. 
Aug 06, 2021 4:08:37 PM io.quarkus.runtime.ApplicationLifecycleManager run 
ERROR: Failed to start application (with profile my-release) io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.100.0.1/api/v1/namespaces/platform-445-staging/configmaps/my-config.
Message: configmaps "my-config" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "platform-445-staging". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=configmaps, name=my-config, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "my-config" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "platform-445-staging", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).

### Output of `java -version`

11

### Quarkus version or git rev

2.1.2 Final

**Comment by geoand** [comment]
@manusa do you know if in Kubernetes `1.21` a user needs additional permissions to read a config map from the API server?

**Comment by manusa** [comment]
> @manusa do you know if in Kubernetes `1.21` a user needs additional permissions to read a config map from the API server?

I guess that with [RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) you can control access to **any** resource (REST API endpoint), but I don't recall that there's any difference in default permissions based on the K8s version (at least for config maps).


From the log, I see that the application is having trouble locating the service account token that Kubernetes [mounts by default](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/) for each Pod. I don't know if there are any differences with this in [EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) flavored K8s, but we haven't seen any issues reported so far.

Follow this guide (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) to make sure that service accounts aren't disabled. As a workaround, you can try to mount a different token in the default directory `/var/run/secrets/kubernetes.io/serviceaccount`.

**Comment by geoand** [comment]
Is this still a problem?

**Comment by kjq** [comment]
Georgios.

We have not had a chance to try it again yet but I will try this weekend
and see.

Thanks.

KJQ

**Comment by geoand** [comment]
Great, thanks

**Comment by iocanel** [comment]
> Maybe it is related to this according to the upgrade log for K8S? **Service account tokens bound to a pod is now a stable feature. The feature gates will be removed in 1.21 release. For more information, refer to notes below on the changelogs.**

This justifies the warnings and the behavior. We need to check how the service account token is meant to be read from 1.21 onward and update the client.

**Comment by mweber03** [comment]
I am also seeing this issue, but we're running our own Kubernetes cluster (not Amazon's). We're using Kuberneetes 1.21.5.

**Comment by manusa** [comment]
> @manusa I am also seeing this issue, but we're running our own Kubernetes cluster (not Amazon's). We're using Kubernetes 1.21.5.

Could you please specify the Quarkus version you are using and if the error message is the same as the one reported in the issue?

**Comment by kjq** [comment]
For us, running the latest Quarkus and Kubernetes (almost) on EKS we have not seen this issue again.

**Comment by kjq** [comment]
We are well into 1.24 and have not had any issues with this.

**Comment by Anon1235** [comment]
This appears to still be an issue with current version of Quarkus' Kubernetes Config extension and Kubernetes 1.21.  Upgrading an entire cluster might not be an option for those.  [Post](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens) for changes seems relevant.  

Have attempted to use the projected service account token volume but without any luck.
