### ISSUE TITLE
ContainerResponseFilter setEntity() did not work properly in native

### ISSUE THREAD

**Issue by tamht298** [quarkusio/quarkus#19468]
I use setEntity() for set custom object when the response status is 404. In dev mode, it works ok, the response has custom data that I set before, but with native mode, nothing data response

**Comment by stuartwdouglas** [comment]
We need more details, can you provide a reproducer.

**Comment by tamht298** [comment]
I try to declare a class for body response:
``
@RegisterForReflection
@Data 
@Builder
public class CustomError {
 private String message;
 private String state;
}
``
and the class for handle response:
``
@Provider
public class CustomFilter implements ContainerResponseFilter {
   @Override
  public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) throws IOException {
    CustomError response = new CustomError("Resource not found", "notFound");
    responseContext.setEntity(response);

  }
}
``

**Comment by stuartwdouglas** [comment]
Is this with resteasy reactive or resteasy classic? 

It's also a lot easier for us to work on this if you provide a complete reproducer, so we don't have to attempt to reproduce it ourselves.

**Comment by tamht298** [comment]
I'm using rest easy classic

**Comment by geoand** [comment]
If this is still a  problem, please attach a small project that exhibits the problematic behavior.
A quick and dirty check I did worked just fine

**Comment by tamht298** [comment]
Please check here: [https://github.com/tamht298/quarkus-example](https://github.com/tamht298/quarkus-example)

**Comment by stuartwdouglas** [comment]
You need to use 
      `responseContext.setEntity(ErrorResponse.builder().error("NotFound").build(), null, MediaType.APPLICATION_JSON_TYPE);` as RESTEasy classic seems to be defaulting to HTML for some reason.

**Comment by tamht298** [comment]
Thanks so much. Your solution helps me resolve the problem.
