### ISSUE TITLE
Either RESTEasy Reactive/REST Client Reactive swallow errors in some scenarios, very difficult to debug

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#19488]
### Describe the bug

The actual error being throw under the hood was:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.HashSet<org.acme.CurrentWeather>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (ByteArrayInputStream); line: 1, column: 1]
```

But between the fact that Quarkus generates a lot of code, and the reactive/multithreaded bit, debugging this and trying to navigate the source + callstack was somewhat of a nightmare because:
- For a lot of the source, there's no file it would show in the IDE for the relevant code bits 
- The chain of calls/indirection can be particularly deep

![quarkus-reactive-not-surfacing-errors](https://user-images.githubusercontent.com/26604994/129968962-05498c8a-896b-4e96-bbab-26e1fbfabfb5.png)

But with this code/endpoint:
```java
@JsonIgnoreProperties(ignoreUnknown = true)
class CurrentWeather {
    public String description;
    public int temp;
    public int feels_like;
    public int wind_speed;
}

@RegisterRestClient(baseUri = "http://api.openweathermap.org/data/2.5")
interface WeatherService {

    enum MeasurementKind { standard, metric, imperial }

    // We can fake/pretend these are path params and it winds up a bit clearer
    @GET
    @Path("/weather?q={city},{country}&appid={apiKey}&units={units}")
    Set<CurrentWeather> getWeatherByCityAndCountry(String city,
                                                   String country,
                                                   String apiKey,
                                                   String units);
}

public class Thing {
    private static final Logger log = Logger.getLogger(SomePage.class);
    
    @RestClient WeatherService weatherApi;
    @Inject Configuration config;

    @GET
    @Path("/route")
    @Blocking
    public Set<CurrentWeather> getWeatherExample1() {
        log.info("called!!!");
        var results = weatherApi.getWeatherByCityAndCountry(
                "Miami", "US",
                config.openWeatherMapApiKey,
                WeatherService.MeasurementKind.imperial.name());
        log.info("results = ");
        log.info(results);
        return results;
    }
}
```

Nothing is ever logged past the initial `called!!!` 🙁 
Very confusing

![image](https://user-images.githubusercontent.com/26604994/129969471-4ff809f0-61dc-4967-bc08-5ed3d7bba30a.png)

![image](https://user-images.githubusercontent.com/26604994/129969491-5b8c8cb1-1df9-429c-9ff2-54dd3e704d0d.png)

### How to Reproduce?

Quarkus `v2.1.2-final`
```kts
plugins {
    java
    id("io.quarkus")
}

repositories {
    mavenCentral()
    mavenLocal()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-resteasy-reactive-qute")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-rest-client-reactive")
    implementation("io.quarkus:quarkus-rest-client-reactive-jackson")

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.rest-assured:rest-assured")
}

group = "org.acme"
version = "1.0.0-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}
```

**Comment by GavinRay97** [comment]
The solution to making the actual ENDPOINT work?
- https://stackoverflow.com/a/58544375

```java
@Singleton
class MyObjectMapperCustomizer implements ObjectMapperCustomizer {
    public void customize(ObjectMapper mapper) {
        mapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
    }
}
```


I blame Jackson for the terrible error message, for starters... 😅

**Comment by geoand** [comment]
Yeah, it's sometimes hard to understand where the Jackson errors actually mean in practice.
That said, we could likely add some intelligence in Quarkus (perhaps only in dev-mode) to help users, but it would probably be very fragile...

**Comment by GavinRay97** [comment]
@geoand The main issue here was that the error mistakenly (I think) seemed to be "swallowed" -- no RESTeasy exception is ever thrown and it fails to "bubble up":

![image](https://user-images.githubusercontent.com/26604994/130501888-035f47e6-09ce-4367-8cec-402df34647b6.png)

No exception/error message -- the rest of the function just fails to execute

And the page response, empty:

![image](https://user-images.githubusercontent.com/26604994/130501946-b6f5153f-269d-4bc5-8ff9-5b3e2fa1a0af.png)

**Comment by stuartwdouglas** [comment]
Do you have a simple GH repo that reproduces the logging issue?

I could setup a new project and copy paste the classes above but a reproduce repo would make things a lot easier (It's not uncommon with these copy/paste reproducers for something to be missing so you spend the time setting it up and then it does not work anyway).

**Comment by geoand** [comment]
As Stuart mentions, if you have a small project we can use to reproduce what you are seeing, that would be great

**Comment by GavinRay97** [comment]
Here you go @geoand @stuartwdouglas:

[quarkus-reactive-jackson-repro.zip](https://github.com/quarkusio/quarkus/files/7039528/quarkus-reactive-jackson-repro.zip)

It runs on port `8081`, only thing to note.
Run a `gradle quarkusDev` and then visit

- http://localhost:8081/weather/broken?city=Miami

For example, and watch the log output

Important pieces of the code (only 2 areas) have been tagged with `FOR QUARKUS DEVS` comments so you can `Ctrl + F` 👍 

```java
// FOR QUARKUS DEVS
@GET
@Path("/broken")
@Produces(MediaType.APPLICATION_JSON)
@Blocking
public Set<WeatherResponse> thisBreaksStuffs(@QueryParam("city") String city) {
    log.info("HERE, START OF thisBreaksStuffs()");
    Set<WeatherResponse> res = weatherApi.INCORRECT_BROKEN_GetWeatherByCityAndCountry(
            city, "USA",
            config.openWeatherMapApiKey, WeatherService.MeasurementKind.imperial
    );
    log.info("AFTER weatherApi.INCORRECT_BROKEN_GetWeatherByCityAndCountry, RETURNING RESPONSE");
    return res;
}
```

**Comment by stuartwdouglas** [comment]
This is because the 400 WebApplicationException from the client ends up being interpreted by the server. It's a known issue with both the client and the server using the same exception types, I have added a fix.

**Comment by GavinRay97** [comment]
Thank you, I really appreciate you all 🙏

**Comment by lorenzobenvenuti** [comment]
Hi,

I just came across the same issue in 2.16.3: if the REST client gets a 400 while serving a request, the application returns a 400 (while I think it should return a 500). I created a reproducer here: https://github.com/lorenzobenvenuti/rest-client-exception-bug

Thanks,

lorenzo

**Comment by geoand** [comment]
@lorenzobenvenuti the behavior you mention is expected.

If you really want to return 400 when the client gets that result, you can use `Response` or `RestResponse` as the return type of your client method and then check the response code.

**Comment by lorenzobenvenuti** [comment]
> If you really want to return 400

Hi @geoand , actually the problem is that I _don't_ want to return a 400: returning the same status code of a REST call performed by the request handler seems misleading to me. Since the underlying issue is that there was an unhandled exception on the server side. I think the default behavior should be returning a 500 (BTW this seems the same issue addressed by [this MR](https://github.com/quarkusio/quarkus/pull/19630), but either it doesn't work or there was a regression)

**Comment by geoand** [comment]
Oh sorry, I misread what you wrote. Please open a new issue and add the details you mentioned in the comment above.

Thanks

**Comment by lorenzobenvenuti** [comment]
Created https://github.com/quarkusio/quarkus/issues/31326. Thanks!
