### ISSUE TITLE
Classloader issue with JUnit TestInfo

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#19482]
### Describe the bug

In order to make some configurations, I'm reading annotations on tests using JUnit `TestInfo`. 

However I'm facing a problem on Quarkus 2 since `TestInfo` is loaded with a different classloader than my test, so looking for annotations using `testInfo.getTestMethod()...getAnnotationsByType` does not return anything.

Consider:

    @QuarkusTest
    public class AnnotatedTest {
    
        @Test
        void test(TestInfo testInfo) {
            Class<?> declaringClass = testInfo.getTestMethod().orElseThrow().getDeclaringClass();

            System.out.println("declaringClass classloader: " + declaringClass.getClassLoader());
            System.out.println("this classloader: " + this.getClass().getClassLoader());
        }
    }

### Expected behavior

I'd expect something like this (obtained with Quarkus 1.13.7):

    declaringClass classloader: QuarkusClassLoader:Quarkus Base Runtime ClassLoader
    this classloader: QuarkusClassLoader:Quarkus Base Runtime ClassLoader

Both classes are with the same classloader.

### Actual behavior

On Quarkus 2.1.2.Final I get:

    declaringClass classloader: jdk.internal.loader.ClassLoaders$AppClassLoader@3b192d32
    this classloader: QuarkusClassLoader:Quarkus Runtime ClassLoader: TEST restart no:0@6a9ad3d6

Different classloaders.

### How to Reproduce?

See example above.

I'd also expect the following to work:

    @QuarkusTest
    @MyTestConfig("class")
    public class AnnotatedTest {
    
        @Test
        @MyTestConfig("method")
        void testProcessAnnotation(TestInfo testInfo) {
            assertThat(processAnnotation(testInfo, MyTestConfig.class))
                    .extracting(MyTestConfig::value).containsExactly("class", "method");
        }
    
        <T extends Annotation> List<T> processAnnotation(TestInfo testInfo, Class<T> annotationClass) {
            Method m = testInfo.getTestMethod().orElseThrow();
            T[] classAnnotations = m.getDeclaringClass().getAnnotationsByType(annotationClass);
            T[] methodAnnotations = m.getAnnotationsByType(annotationClass);
            return Stream.of(classAnnotations, methodAnnotations)
                    .flatMap(Arrays::stream)
                    .collect(Collectors.toList());
        }
    }

Having for example:

    @Target({ TYPE, METHOD })
    @Retention(RUNTIME)
    public @interface MyTestConfig {
        String value();
    }

### Output of `java -version`

11

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

(Originally opened on SO: https://stackoverflow.com/questions/68815352/quarkus-2-vs-junit-testinfo-classloader-issue-on-annotated-test)

**Comment by famod** [comment]
You need those annotation values inside your test methods, right?
Otherwise you might want to have a look at `QuarkusTestBeforeEachCallback` as a workaround.

**Comment by antoniomacri** [comment]
Yes, I need to read annotations from test methods or before each callback, but different test classes may perform different actions on a given annotation.

**Comment by antoniomacri** [comment]
Sorry about reopening this, please tell me if it's better to submit another issue.

There is a similar case which still does not work:

```
@QuarkusTest
public class AnnotatedTest {

    @BeforeEach
    public void beforeEach(TestInfo testInfo) throws NoSuchMethodException {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertEquals(AnnotatedTest.class.getDeclaredMethod("testInfoTestCase", TestInfo.class),
                testInfo.getTestMethod().get());
    }

    @Test
    public void testInfoTestCase(TestInfo testInfo) throws NoSuchMethodException {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertEquals(AnnotatedTest.class.getDeclaredMethod("testInfoTestCase", TestInfo.class),
                testInfo.getTestMethod().get());
    }

    @AfterEach
    public void afterEach(TestInfo testInfo) throws NoSuchMethodException {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertEquals(AnnotatedTest.class.getDeclaredMethod("testInfoTestCase", TestInfo.class),
                testInfo.getTestMethod().get());
    }
}

```

In Before/AfterEach the testInfo should return the "Method associated with the current test".

(Also I noticed expected/actual in your PR were inverted.)

**Comment by famod** [comment]
@antoniomacri can you check `2.2.1.Final`? It includes another fix: #19751

**Comment by antoniomacri** [comment]
Ops, of course! I'll wait to see it on Maven Central

Thanks!

**Comment by antoniomacri** [comment]
Fixed Before/AfterEach!

However Before/AfterAll give an exception on this line since getTestMethod is empty:

    Method newTestMethod = determineTCCLExtensionMethod(info.getTestMethod().get(), testClassFromTCCL);

You can use the example above as a reproducer.

Would you like me to open another issue?

**Comment by famod** [comment]
Argh...at a certain point of that PR I had a proper handling of this case, but it got lost in subsequent iterations.

Please create another issue, I'll have a look ASAP!

**Comment by antoniomacri** [comment]
Done #19800, thanks!

**Comment by vamsisayimpu** [comment]
#TODO: Quakrus Testing framework uses QuarkusClassLoader
quarkus.test.flat-class-path=true
