### ISSUE TITLE
Extend `CurateOutcomeBuildItem`'s `AppModel` to list all present extensions

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#19497]
### Description

I would like to implement an extension which verifies the setup of an application. One part of this verification is to make sure that certain extensions are present or not present. Currently there is no such mechanism offered by Quarkus. There are build items to access the list of capabilities and features, but not for extensions.

### Implementation ideas

I propose to add a multi build item for the list of extensions present in the build. This build item would somehow be provided by Quarkus and extensions would not be expected to explicitly produce corresponding build items, only consume it.

**Comment by aloubyansky** [comment]
I would suggest adding this information to the AppModel instead provided by the CurateOutcomeBuildItem.

**Comment by knutwannheden** [comment]
> I would suggest adding this information to the AppModel instead provided by the CurateOutcomeBuildItem.

That sounds like a good idea. That way there is no confusion regarding a "read-only" build item.

**Comment by gsmet** [comment]
In any way, it shouldn't be a MultiBuildItem but a simple one providing the list of GA of the extensions.

@aloubyansky AFAICS the AppModel is not exposed in a consumable build item, do we really want to expose it completely?

**Comment by knutwannheden** [comment]
@aloubyansky Can you provide me with some hints on how to implement this? I've tried to understand the code and my guess would have been that I need to extend `BootstrapAppModelResolver#doResolveModel()` to collect all the extensions using the `DeploymentInjectingDependencyVisitor` and then pass them to the `AppModel.Builder`. To achieve this I would probably have extended `DeploymentInjectingDependencyVisitor#visitExtensionDependency()` to also collect all `extDep.info.runtimeArtifact` elements.

**Comment by aloubyansky** [comment]
Pretty much. The `DeploymentInjectingDependencyVisitor` can add the extension dependencies to the `AppModel.Builder` directly.

**Comment by knutwannheden** [comment]
Thanks. I will set up my local Quarkus workspace and try to work on this.

**Comment by aloubyansky** [comment]
There is also the Gradle side of it, which should be added to the `QuarkusModelBuilder`. FYI @glefloch
