### ISSUE TITLE
Qute description doesn't mention HTML templating

### ISSUE THREAD

**Issue by lucas-deangelis** [quarkusio/quarkus#19499]
### Description

The current description of Qute is "Offer templating support for web, email, etc in a build time, type-safe way". These descriptions are pulled to be used on code.quarkus.io. This means that Qute doesn't appear when you search "HTML templating" or just "HTML".

From what I understand, Qute is the recommended way to do HTML templating with Quarkus, so I think it should appear in the results when you search for "HTML templating" on code.quarkus.io.

### Implementation ideas

I would suggest adding "HTML" to the descriptions of Qute: "Offer templating support for web, email, HTML, etc in a build time, type-safe way".

I can make a pull request for it, but I'm not sure if I should do it before or after the suggestion has been approved.

**Comment by gsmet** [comment]
I think HTML was implied in `web`. @mkouba maybe it's worth adding a couple more keywords to the extension metadata? I suppose they are taken into account in the search? @ia3andy can you confirm?

**Comment by ia3andy** [comment]
> I think HTML was implied in `web`. @mkouba maybe it's worth adding a couple more keywords to the extension metadata? I suppose they are taken into account in the search? @ia3andy can you confirm?

yes they are

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/19576
