### ISSUE TITLE
Quarkus Native Image Isn't Working on Lambda

### ISSUE THREAD

**Issue by krezchikov42** [quarkusio/quarkus#19516]
### Describe the bug

When I try to deploy a native image lambda while following this tutorial I keep getting this error.  https://quarkus.io/guides/amazon-lambda-http 

```
RequestId: 205eadec-1ee1-499d-869e-0d048cd3ce15 Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint
```
Here are my java version 
![quarkus-lambda-rest-orig — konstantin@TEAL-C02F44B2MD6P — -zsh — 156×33 2021-08-19 at 3 20 56 PM](https://user-images.githubusercontent.com/31769496/130131178-e667369d-c939-471f-8e22-3523b2c44b53.jpg)

I've run commands 

``` 
mvn clean install -D native
mvn clean install -Dnative -Dnative-image.docker-build=true
```

and then try 

```
sam local start-api --template target/sam.native.yaml 
sam deploy -t target/sam.native.yaml -g 
```
I've tried every mvn command with both sam commands and I am always getting this error. I've also tried to change the 
` <quarkus.package.type>native</quarkus.package.type>`  to uber-jar. Nothing works. I've successfully tested this tutorial with the jvm, but the native binary always has this issue. I would love some help. Thank you!

### Expected behavior

This is what I expect the server to return 
hello jaxrs

### Actual behavior

I get this on the screen 
```
{"message": "Internal server error"}
```
and this error logged in aws
```
RequestId: 205eadec-1ee1-499d-869e-0d048cd3ce15 Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint
```

### How to Reproduce?

Follow this tutorial https://quarkus.io/guides/amazon-lambda-http 
1. mvn clean install -Dnative 
2. sam local start-api --template target/sam.native.yaml
3 sam deploy -t target/sam.native.yaml -g

### Output of `uname -a` or `ver`

Darwin TEAL-C02F44B2MD6P 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 20.3.2 (build 11.0.11+8-jvmci-20.3-b15)

### Quarkus version or git rev

        <quarkus.platform.version>2.1.2.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by gsmet** [comment]
The doc was incorrect. You need to use `-Dquarkus.native.container-build=true`.

I created a PR to fix it here: https://github.com/quarkusio/quarkus/pull/19577 .
