### ISSUE TITLE
Unable to get Otel Current Context in debug Mode with opentelemetry

### ISSUE THREAD

**Issue by stevefavez** [quarkusio/quarkus#19512]
### Describe the bug

Hi, 
My issue is the following : when running a simple restfull helloworld jax-rs "helloworld" service using opentelemetry, if I'm trying to access the currentspan / current otel context in Debug mode, I can't access the one created by VertxTracingAdapter. It sounds like LazyStorage is using QuarkusContextStorage Instance, so, VertxTracingAdapter is storing the Span and Context properly, but the underlying restfull service can't access the span.

When running in "normal" mode, no problem, I can access the span properly.

Here's my code : 

```
@Path("")
public class HelloQuarkus {
    private static final Logger LOGGER = LoggerFactory.getLogger(HelloQuarkus.class);


    @GET
    @Path("/hello")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        MDC.getCopyOfContextMap() ;
        final Context currentContext = Context.current();
        final Context rootContext = Context.root();
        Span.fromContext(currentContext) ;
        final Span currentSpan = Span.current();
        final SpanContext spanContext = currentSpan.getSpanContext();
        MDC.put("traceId", spanContext.getTraceId());
        MDC.put("spanId", spanContext.getSpanId());
        MDC.put("parentId", "0");
        LOGGER.info("hello");
        return "Hello Quarkus";
    }
}
```

By the way, this was a test to get a better understanding on how to solve this issue : #18228 ( Support for MDC log metadata when using Opentelemetry  )

Thanks for your help

### Expected behavior

When invoking Span.current() in my code (restfull service) I get the one created by Vertx even in Debug mode

### Actual behavior

When running in Debug mode, Span.current() returns a new root span

### How to Reproduce?

Step to reproduce : 

1. Create a Helloworld project
2.  add opentelemetry support
3. Add Span.current() in the  helloworld method
4. Run in debug mode - a Root Span is returned

**Comment by kenfinnigan** [comment]
@stuartwdouglas does `quarkus:dev` result in different threads being used, or some change in behavior that could cause this?
