### ISSUE TITLE
Documentation is unclear about how to mount a PVC on Openshift

### ISSUE THREAD

**Issue by mmuzikar** [quarkusio/quarkus#19528]
### Description

If a user wants to attach a volume to their app they might be confused by the docs mentioning specifically secret and configmap volumes as if they were the only ones supported.

### Implementation ideas

Just as 
ConfigMap volumes

quarkus.openshift.config-map-volumes.my-volume.config-map-name=my-secret

is in the docs the same can be for 
Persistent Volume Claims

quarkus.openshift.pvc-volumes.my-pvc.claim-name=my-pvc

**Comment by geoand** [comment]
cc @metacosm
