### ISSUE TITLE
New Blog post using Quarkus

### ISSUE THREAD

**Issue by oztimpower** [quarkusio/quarkus#19524]
### Description

Hi, how do I get a blog post added to the Quarkus blog page.

My AWS official blog in the Security channel used Quarkus for the solution with various Quarkus extensions: OIDC, Kotlin, Kubernetes, Jib. 

https://aws.amazon.com/blogs/security/access-token-security-for-microservice-apis-on-amazon-eks/

**Comment by geoand** [comment]
Nice!

@gsmet should have all the details

**Comment by gsmet** [comment]
Blog posts are there: https://github.com/quarkusio/quarkusio.github.io/tree/develop/_posts

You also need to add yourself as an author here: https://github.com/quarkusio/quarkusio.github.io/blob/develop/_data/authors.yaml
