### ISSUE TITLE
Missing Kubernetes Client change in Migration Guide for 2.1 and 2.2

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19533]
### Description

As users might use this library independently, we should add the upgrades in the migration guide. 
This is done in Quarkus 2.0 when we upgraded to Kubernetes Client:5.4: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#kubernetes-client

But not in:
- Quarkus 2.1 when we upgraded from 5.4 to 5.6.
- Quarkus 2.2 when we upgraded from 5.6 to 5.7 (see related commit https://github.com/quarkusio/quarkus/commit/97c1f89205ee40387e5f65c48687bfa07c4057a4)

In both migration guides, we should add a similar comment that was done for Quarkus 2.0: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#kubernetes-client

**Comment by geoand** [comment]
Added https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1#kubernetes-client and https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.2#kubernetes-client to address this. 

Thanks

**Comment by gsmet** [comment]
Frankly, we shouldn't do it except if there are known migration issues, which was the case for the one we put in the migration guide.

We upgrade a ton of components in each release and we don't add them to the migration guide. For me it's the responsibility of the Kubernetes Client team to ask us to add something to the migration guide if necessary.

**Comment by geoand** [comment]
There are minor breaking changes in each of these releases and it appears that they broke some actual applications QE used. I would say that warrants an entry
