### ISSUE TITLE
Crash during mvn io.quarkus-maven-plugin:2.1.3.Final:create

### ISSUE THREAD

**Issue by luminecs** [quarkusio/quarkus#19558]
### Describe the bug

Crash during mvn io.quarkus-maven-plugin:2.1.3.Final:create

OS version: WSL Ubuntu 20.04

Maven version: 3.8.2

Java version: jdk-16

Quarkus version: 2.1.3

The follow command (from https://quarkus.io/guides/getting-started) does not work
```
mvn io.quarkus:quarkus-maven-plugin:2.1.3.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
```

### Actual behavior

root@DESKTOP-JJTFEFQ:/mnt/c/data/repo/learn/quarkus-guides# mvn io.quarkus:quarkus-maven-plugin:2.1.3.Final:create     -DprojectGroupId=my-groupId     -DprojectArtifactId=my-artifactId     -DprojectVersion=my-version     -DclassName="org.my.group.MyResource"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.1.3.Final:create (default-cli) @ standalone-pom ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.864 s
[INFO] Finished at: 2021-08-21T14:24:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.1.3.Final:create (default-cli) on project standalone-pom: Failed to initialize Quarkus extension catalog resolver: Failed to resolve Quarkus extension registry descriptor io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT from aliyunmaven (https://maven.aliyun.com/repository/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

### Output of `uname -a` or `ver`

Linux DESKTOP-JJTFEFQ 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment (build 16.0.2+7-67) OpenJDK 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

### Quarkus version or git rev

2.1.3

### Additional information

I am from China, and I use the Aliyun maven repository service (from Alibaba, https://maven.aliyun.com/repository/public) .

I also find the **io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT** from the maven central repository (https://repo.maven.apache.org/maven2/io/quarkus/quarkus-registry-descriptor/), but there is nothing about this. 

**Is there something wrong with my operation?**

![屏幕截图 2021-08-21 144108](https://user-images.githubusercontent.com/24493654/130313154-d60610a3-513c-4f0a-a932-bcdae9df8f23.png)

**Comment by gsmet** [comment]
@aloubyansky could you have a look at this one?

**Comment by aloubyansky** [comment]
Is there a Maven mirror in the settings or the pom.xml?

**Comment by aloubyansky** [comment]
This may help https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/extension-registry-user.adoc#maven-repository-mirrors-and-proxies

**Comment by gsmet** [comment]
@aloubyansky but why does it try to resolve a snapshot version of something `io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT`?

**Comment by aloubyansky** [comment]
All the `io.quarkus.registry` artifacts are snapshots. It allows to have static coordinates for the dynamic content. The `quarkus-registry-descriptor` isn't actually expected to be changing often but that catalogs are.

**Comment by aloubyansky** [comment]
The fact that the plugin fails w/o suggesting a workaround is an issue though.

**Comment by luminecs** [comment]
> Is there a Maven mirror in the settings or the pom.xml?

Hi aloubyansky, the following is maven's `conf/settings.xml` (the comments have been deleted). 

The aliyunmaven mirror is an alternative version of the maven central repository and is widely used in China. There is also the same error while I used the maven central repository.

Are there any other configurations that need to be add to the `conf/settings.xml`? What I mean is that I can create a new Quarkus project directly by using the `io.quarkus:quarkus-maven-plugin:2.1.3.Final:create -DprojectGroupId=org.acme ...` command. 

I am very interested in Quarkus, it’s just that I’m not familiar with this project, so I always encounter various problems... :)

```
<?xml version="1.0" encoding="UTF-8"?>

<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
          
  <pluginGroups> </pluginGroups>

  <proxies> </proxies>

  <servers> </servers>

  <mirrors>
	<mirror>
            <id>aliyunmaven</id>
	    <mirrorOf>*</mirrorOf>
	    <name>阿里云公共仓库</name>
	    <url>https://maven.aliyun.com/repository/public</url>
	</mirror>
  </mirrors>

  <profiles> </profiles>

</settings>
```

**Comment by aloubyansky** [comment]
@luminecs `aliyunmaven` is a mirror of which repositories? The config implies it is a mirror of all the Maven repositories. It's very unlikely that it is.

**Comment by luminecs** [comment]
> @luminecs `aliyunmaven` is a mirror of which repositories? The config implies it is a mirror of all the Maven repositories. It's very unlikely that it is.

The `https://maven.aliyun.com/repository/public` is the union of `https://repo1.maven.org/maven2/` and `	
http://jcenter.bintray.com/`. Does the Quarkus have it own repository, and how to configure is? Or can I refer to your configuration？

If the expression is wrong,  please criticize and give advice. I have been learning to improve my English. Thanks.

**Comment by aloubyansky** [comment]
Yes, that's what I meant, using `*` means the mirror should be capable of providing artifacts from all the possible repositories., see https://maven.apache.org/guides/mini/guide-mirror-settings.html#using-a-single-repository.
If you know that `aliyunmaven` is a mirror of only those two repos, you should have the following config instead:

````
	<mirror>
            <id>aliyunmaven</id>
	    <mirrorOf>central,jcenter</mirrorOf>
	    <name>阿里云公共仓库</name>
	    <url>https://maven.aliyun.com/repository/public</url>
	</mirror>
````

There is a Quarkus extension registry Maven repository, which is required only for the dev tools to, for example, create a new project but not required to build applications. See https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/extension-registry-user.adoc#maven-repository-configuration

**Comment by foal** [comment]
See https://github.com/quarkusio/quarkus/issues/19612#issuecomment-904671430

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/pull/19455 will help in this case by logging a warning about the registry not being available in the current environment and falling back to the extension catalog narrowed to the platform release (kind of a legacy approach).

**Comment by luminecs** [comment]
@aloubyansky @foal The problem has been solved. Thanks you very much.
