### ISSUE TITLE
Qute standalone - format functions for java.time.ZonedDateTime

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19555]
### Description

docs at https://quarkus.io/guides/qute-reference#built-in-template-extension says `format` exits for ZonedDateTime but when calling it i get:

```
Exception in thread "main" io.quarkus.qute.TemplateException: Method "format('d MMM uuuu')" not found on the base object "java.time.ZonedDateTime" in expression {post.pubDateZonedDateTime.get().format('d MMM uuuu')} in template 1 on line 23
```

note: i'm using qute standalone if that matters

**Comment by maxandersen** [comment]
reproducer:

update.java:
```java

///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus.qute:qute-core:2.2.0.CR1
//DEPS https://github.com/w3stling/rssreader/tree/v2.5.0
//JAVA 16+

import com.apptastic.rssreader.Item;
import com.apptastic.rssreader.RssReader;
import io.quarkus.qute.Engine;
import io.quarkus.qute.EvalContext;
import io.quarkus.qute.ReflectionValueResolver;
import io.quarkus.qute.ValueResolver;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class update {

    public static void main(String... args) throws IOException {

        String bio = """
                blah
		""";


        RssReader reader = new RssReader();
        Stream<Item> rssFeed = reader.read("https://xam.dk/blog/feed.atom");
        List<Item> posts = rssFeed.collect(Collectors.toList());
        var x = posts.get(0).getPubDateZonedDateTime();
        Engine engine = Engine.builder()
                .removeStandaloneLines(true)
                .addValueResolver(new ReflectionValueResolver())
                .addDefaults()
                .build();
        Files.writeString(Path.of("readme.adoc"), engine.parse(Files.readString(Path.of("template.adoc.qute")))
                .data("bio", bio)
                .data("posts", posts)
                .render());


    }
}

```

and `template.adoc.qute`:

```
{bio}

## ✍️ Most recent blog posts

{#for post in posts}
{post.title.get()} ({post.pubDateZonedDateTime.get().format("d MMM uuuu")})::
{post.description.get()}
{/for}
```

`jbang update.java`

**Comment by maxandersen** [comment]
hmm - even time: namespace are not available.

Is this a case of quarkus configures qute to have these but they are not available in the standalone setup ?

**Comment by gastaldi** [comment]
AFAIK you need to  add a ValueResolver to your `Engine`. I faced something similar while trying to use the `inject` namespace in the dev UI qute template 😝

**Comment by maxandersen** [comment]
yes thats fine but then imo the docs should not say its there by default and preferably say what resolver to add to get it....in this case though its hidden inside the quarkus extension not  in qute itself.

**Comment by maxandersen** [comment]
What are the reasons why all the basic defaults are only in quarkus ? Would at least be helpful docs would point out what is in qute and what is uniquely quarkus.

**Comment by mkouba** [comment]
> What are the reasons why all the basic defaults are only in quarkus ? 

Well, Qute is _primarily intended_ to be used as a Quarkus extension. It is possible to use it standalone but then many features (such as type-safe templates) are not available because we're not able to perform the pre-processing during the build phase. Some of those features could be ported to a runtime-only environment but this approach has its drawbacks. First of all, we would have to maintain two implementations of the same feature. And that's something we'd like to avoid. 

> Would at least be helpful docs would point out what is in qute and what is uniquely quarkus.

Quarkus-specific features are described under the _3. Quarkus Integration_ section.

**Comment by mkouba** [comment]
FTR the limitations of Qute standalone are described here: https://quarkus.io/guides/qute-reference#standalone
