### ISSUE TITLE
DataSources DevService doesnt follow the same logs patterns as other devServices 

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#19573]
### Describe the bug

I am missing the following Log in postgresql | mysql | mariadb | Mssql devService:

```
Dev Services for <DATABASE_KIND> started.
```

As other devServices do, for example: 

Amqp (follow this pattern): 
```
1.      Pulling docker image: quay.io/artemiscloud/activemq-artemis-broker
2.      Please be patient; this may take some time but only needs to be done once
3.      Starting to pull image
4.      Dev Services for AMQP started
```

RedPanda:

```
1. Pulling docker image: vectorized/redpanda
2. Please be patient; this may take some time but only needs to be done once
3. Starting to pull image
4.  Dev Services for Kafka started
```

But Postgres follow this pattern:

```
1. Pulling docker image: postgresql
2. Please be patient; this may take some time but only needs to be done once
3. Starting to pull image
```

I think that is important to have a unified log and also explicitly says that DevService <DATABASE_KIND> was started

### Expected behavior

Dev Services for <DATABASE_KIND> started

**Comment by gsmet** [comment]
I will have a look at this one and the other one https://github.com/quarkusio/quarkus/issues/19485

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/19575
