### ISSUE TITLE
MyBatis extension

### ISSUE THREAD

**Issue by halhelal** [quarkusio/quarkus#1958]
Are there any plans to provide extensions for mybatis framework?

**Comment by emmanuelbernard** [comment]
There is no immediate plan but that looks like a typical extension that someone could write based on the one we did for Hibernate for example. Interested?

**Comment by halhelal** [comment]
Yes, I am interested. I will look at the hibernate extension. I am also looking at Oracle jdbc driver.

**Comment by gastaldi** [comment]
This extension will be developed under the quarkiverse organization. See https://github.com/quarkusio/quarkus/pull/10671#issuecomment-706231300

**Comment by knbsyoo** [comment]
That's so disappointing

**Comment by gastaldi** [comment]
@knbsyoo what is disappointing? The extension is in https://github.com/quarkiverse/quarkus-mybatis and docs in https://docs.quarkiverse.io/quarkus-mybatis/dev/index.html
