### ISSUE TITLE
maven-plugin create downloads a io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#19612]
### Describe the bug

I was trying to follow along the json rest guide: https://quarkus.io/guides/rest-json

During project creation, I was asked to execute this command:
```
mvn io.quarkus:quarkus-maven-plugin:2.2.0.CR1:create -DprojectGroupId=org.acme -DprojectArtifactId=rest-json-quickstart -DclassName="org.acme.rest.json.FruitResource" -Dpath="/fruits" -Dextensions="resteasy,resteasy-jackson"
```

This tries to download `io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT` from our corporate nexus proxy, which fails.
AFAIK, we only proxy releases from maven central, and not snapshot from ossrh.

This behavior is strange however - I believe it should download the beta8 instead of an snapshot version: https://search.maven.org/artifact/io.quarkus/quarkus-registry-descriptor/1.0.0.Beta8/jar

This happens for quarkus 2.1.X.Final, and 2.2.0.CR1. The project was not created.

As a workaround, I used 2.0.2.Final for now.

### Expected behavior

During project creation, no snapshot registry-descriptor should be downloaded.

### Actual behavior

```
C:\Users\mnp>mvn io.quarkus:quarkus-maven-plugin:2.2.0.CR1:create -DprojectGroupId=org.acme -DprojectArtifactId=rest-json-quickstart -DclassName="org.acme.rest.json.FruitResource" -Dpath="/fruits" -Dextensions="resteasy,resteasy-jackson"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.2.0.CR1:create (default-cli) @ standalone-pom ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.456 s
[INFO] Finished at: 2021-08-24T13:38:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.2.0.CR1:create (default-cli) on project standalone-pom: Failed to initialize Quarkus extension catalog resolver: Failed to resolve Quarkus extension registry descriptor io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT from nexus_public (https://nexus03.company.tld/repository/public) nexus_internal (https://nexus03.company.tld/repository/internal) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

Execute the command from above.

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk 16.0.1 2021-04-20 OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9) OpenJDK 64-Bit Server VM Zulu16.30+15-CA (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev

2.2.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin\.. Java version: 16.0.1, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\16 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by foal** [comment]
I have a very similar issue - try to add `container-image-jib` by the following command `mvnw quarkus:add-extension -Dextensions="container-image-jib"` and see the
```
[DEBUG] Using mirror lnexus (http://localhost:8081/repository/public) for registry.quarkus.io (https://registry.quarkus.io/maven).
[DEBUG] Could not find metadata io.quarkus.registry:quarkus-registry-descriptor:1.0-SNAPSHOT/maven-metadata.xml in local (D:\Development\repository)
[DEBUG] io.quarkus.registry:quarkus-registry-descriptor:1.0-SNAPSHOT/maven-metadata.xml was not found in http://localhost:8081/repository/public
```
If I check this artifact in my Nexus (http://localhost:8081/repository/registry.quarkus.io/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml) I see
```
Invalid maven-metadata.xml GAV io.quarkus.registry, quarkus-registry-descriptor, null does not match request path io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml
```
If I check this artifact on your side (https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml) I see a missing version 
```
<metadata>
<groupId>io.quarkus.registry</groupId>
<artifactId>quarkus-registry-descriptor</artifactId>
--> missing <version>1.0-SNAPSHOT<version>
<versioning>
...
</versioning>
</metadata>
```

**Comment by aloubyansky** [comment]
Starting from 2.1.0.Final, the Quarkus dev tools now use their own Maven snapshot repository to pull in extension catalogs https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/extension-registry-user.adoc

**Comment by aloubyansky** [comment]
@gastaldi could you please check the missing version issue mentioned above? Thanks.

**Comment by gastaldi** [comment]
@aloubyansky @foal it's fixed now, can you confirm?

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/pull/19455 will help in this case by logging a warning about the registry not being available in the current environment and falling back to the extension catalog narrowed to the platform release (kind of a legacy approach).

**Comment by aloubyansky** [comment]
@Postremus I've changed the way the registry client is initialized in 2.2.1.Final. It will try and apply the user settings first and if the descriptor couldn't be resolved it will try the original registry repo directly. If that also didn't work it will use the maven plugin's coords as the base platform. So in your case it will be `io.quarkus:quarkus-bom:2.2.0.CR1`.
I would suggest you to switch to `io.quarkus.platform:quarkus-maven-plugin` instead, that will be defaulting to the actual Quarkus platform. instead of `io.quarkus:quarkus-bom`.

Also you may read how to configure your Nexus to proxy/mirror the registry.quarkus.io repo now in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/extension-registry-user.adoc

If you think we can do better, please, let us know. I am closing the issue for now.
