### ISSUE TITLE
DevServices and QuarkusTestResourceLifecycleManager see different LaunchMode value in Continuous Testing mode

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#19622]
### Describe the bug

`LaunchMode.TEST` is reported as `LaunchMode.current()` in the `DevServices` processor code (ex, `KeycloakDevServicesProcessor`) while  `LaunchMode.NORMAL` is seen in `QuarkusTestResourceLifecycleManager` after starting Quarkus with `quarkus:dev` and pressing `r` to run the tests.

I've noticed it when trying to fix #19608 - I'd like to make sure that when a test container is started by `DevServices for Keycloak` after `r` is pressed (in addition to the one it starts for the dev services work) then the tests typed to use `KeycloakTestResourceLifecycleManager` reuse that test container 

CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
QuarkusTestResourceLifecycleManager is run before Quarkus starts, so Quarkus has not had a chance to set the launch mode.

That said given that this is only used in testing I don't think this is a bug, as you already know the launch mode is test.
