### ISSUE TITLE
Dev UI: Config Editor should render different web components depending on the config property type

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#19636]
### Description

It would be nice if number-based properties were displayed as a spinner, enum items as a combo box, boolean as checkboxes, etc.

### Implementation ideas

Store the config type in the `ConfigDescription` value object and check in the template

**Comment by phillip-kruger** [comment]
Hi @gastaldi - I had the same idea, and actually started to implement it, but I am not sure where to get the type of the config from. Maybe @radcortez can help ?

**Comment by phillip-kruger** [comment]
@gastaldi - I have done this ... PR to follow soon
