### ISSUE TITLE
Panache count() not updating during in test method

### ISSUE THREAD

**Issue by egore** [quarkusio/quarkus#19657]
### Describe the bug

When using PanacheEntityBase.count() to check if an element was created from a unit test of a service, it will not return the correct value.

Imagine the following Service:

    @Path("/hello")
    public class GreetingResource {

        @GET
        @Produces(MediaType.TEXT_PLAIN)
        @Transactional
        public String hello() {
            Person person = new Person();
            person.name = "Stef";
            person.birth = LocalDate.of(1910, Month.FEBRUARY, 1);
            person.persist();
            return Long.toString(Person.count());
        }
    }

And the following unit test:

    @QuarkusTest
    public class GreetingResourceTest {

        @Test
        public void testHelloEndpoint() {

            long expectedLong = Person.count() + 1L;
            String expected = Long.toString(expectedLong);

            given()
            .when().get("/hello")
            .then()
                .statusCode(200)
                .body(is(expected));

            Assertions.assertEquals(Person.count() + 1L, expectedLong);
        }

    }

The code above will fail the Assertion, presumably either as the result of Person.count() is cached or running within a transaction.

### Output of `java -version`

OpenJDK 64-Bit Server VM (build 11.0.12+7, mixed mode)

### Quarkus version or git rev

2.1.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by loicmathieu** [comment]
The second assertion seems wrong to me:

```
Assertions.assertEquals(Person.count() + 1L, expectedLong);
```

Should be:

```
Assertions.assertEquals(Person.count(), expectedLong);
```
