### ISSUE TITLE
improve kubernetes/openshift guide

### ISSUE THREAD

**Issue by rafaeltuelho** [quarkusio/quarkus#1967]
The actual [openshift guide](https://quarkus.io/guides/kubernetes-guide.html) use a multiple step approach to get the native package into a container on top of Openshift. This step can be simplified a little bit using the [Red Hat Universal Base Image](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_base_container_images_standard_and_minimal). Like this:

> given you have already built the package using `-pnative` profile...
```
oc new-build quay.io/redhat/ubi-quarkus-native-runner --binary --name=quarkus-quickstart
oc start-build quarkus-native-demo --from-file=./target/getting-started-1.0-SNAPSHOT-runner --follow
oc new-app quarkus-native-demo
```

**Comment by gsmet** [comment]
The link to the UBI is dead. Please open a new issue with updated information if it's still an issue.
