### ISSUE TITLE
Keycloak DevServices should produce DevServicesLauncherConfigResultBuildItem

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#19685]
### Describe the bug

As discused, we need to produce `DevServicesLauncherConfigResultBuildItem` for all config we auto set.

**Comment by sberyozkin** [comment]
My understanding Phillip would like to show the auto-added properties, but if `DevServicesLauncherConfigResultBuildItem` is already produced at a different level then I guess it all already works. I'd like though to clean up that code a bit, where KC produces `DevServicesConfigResultBuildItem` - as some of those items are representing the properties which may have already been configured, specifically, `quarkus.oidc.client-id` (and secret) - so they may not have been necessarily `auto-added` :-)

**Comment by phillip-kruger** [comment]
Ok apologies, I thought it did not work, let me double check today, and if it's working I'll close this.

**Comment by phillip-kruger** [comment]
Closing, it's working :)
