### ISSUE TITLE
Using JpaRepository causes error in native code

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#19683]
### Describe the bug

Using the spring-data-jpa extension, it is possible to use `JpaRepository` in JVM builds. But in native builds there is a runtime error caused by missing methods from the interface.

For example with the repository definition

```java
public interface ErewhonRepository implements JpaRepository<Erewhon, Long> { }
```

and injection of this interface into an application-scoped bean, then when running native the following error is reported:

```
java.lang.IllegalArgumentException: Cannot find method save[class Erewhon] on class ErewhonRepository_8003579965ca368f2bc90fccf68a67bef90d72b8Impl
    at io.quarkus.arc.impl.Reflections.findMethodInternal(Reflections.java:110)
    at io.quarkus.arc.impl.Reflections$2.apply(Reflections.java:40)
    at io.quarkus.arc.impl.Reflections$2.apply(Reflections.java:37)
    at io.quarkus.arc.impl.ComputingCache$1.get(ComputingCache.java:52)
    at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
    at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
    at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:49)
    at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:40)
    at io.quarkus.arc.impl.Reflections.findMethod(Reflections.java:81)
        at ErewhonRepository_8003579965ca368f2bc90fccf68a67bef90d72b8Impl_Subclass.<init>(ErehwonRepository_8003579965ca368f2bc90fccf68a67bef90d72b8Impl_Subclass.zig:79)
```

Attaching `@RegisterForReflection` to the interface itself, or any of those in the inheritance hierarchy, does not appear to cure the issue.

### Expected behavior

It should be possible to use `JpaRepository` in native as well as JVM quarkus applications.

### Actual behavior

A `java.lang.IllegalArgumentException: Cannot find method` error is raised (see details above).

### How to Reproduce?

Steps to reproduce the behaviour:

1. A minimal quarkus app with e.g. one REST entry point _P_.
2. An interface _I_ derived from `JpaRepository<E, Long>` based on a simple entity _E_ (could use h2 or other in-memory DB for convenience)
3. Make _P_ call a method of an injected _I_ (the actual method probably doesn't matter, it's just a trigger for Arc to go do work)

If built for JVM the call will succeed, but when run native there will be a `java.lang.IllegalArgumentException: Cannot find method` error when the endpoint _P_ is hit.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-18363 LAP1453 3.0.7-338.x86_64 2019-04-30 21:52 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Switching from `JpaRepository` to `PanacheRepository` makes the issue go away.

**Comment by wabrit** [comment]
Sorry for the delay - the simple reproducer I had hoped to put together does not reproduce the issue, so there's obviously something a little more subtle going on which will take some time to replicate.

**Comment by geoand** [comment]
Not a problem at all.

**Comment by geoand** [comment]
Closing as we did not get a reproducer
