### ISSUE TITLE
Unable to connect local Quarkus app with Infinispan cluster on OpenShift

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#19697]
### Describe the bug

Trying to connect the local Quarkus app with Infinispan (Red Hat Data Grid) cluster runs on OpenShift.
Quarkus process hangs without a try to authenticate the user or create/retrieve the cache.

Two scenarios were tried: with and without TLS (the result was the same)
External access was configured by Route resource.
DataGrid Operator 8.2.3
OpenShift versions: 4.6, 4.8

More details in reproducer.

### Actual behavior

Process hangs with the following logs printed in few minutes:
```
2021-08-26 17:18:26,225 INFO  [org.inf.HOTROD] (Quarkus Main Thread) ISPN004021: Infinispan version: Infinispan 'Taedonggang' 12.1.7.Final
2021-08-26 17:19:26,391 INFO  [org.inf.HOTROD] (HotRod-client-async-pool-1-2) ISPN004016: Server not in cluster anymore(kshpak-dg-infinispan-external-kshpak-dg..<OPENSHIFT_API>), removing from the pool.
2021-08-26 17:20:26,528 INFO  [org.inf.HOTROD] (HotRod-client-async-pool-1-3) ISPN004016: Server not in cluster anymore(kshpak-dg-infinispan-external-kshpak-dg.<OPENSHIFT_API>), removing from the pool.
```
The process keeps spinning new threads.

### How to Reproduce?

Prerequisites: 
- OpenShift cluster
- DataGrid Operator installed
- User logged in the cluster and has project/namespace

1. Create Infinispan CR and `oc apply -f cr_infinispan.yaml` (http://pastebin.test.redhat.com/989831)
This will create a service, pod and route. The Infinispan server should be accessible from the browser by Route URL.

2. Retrieve Infinispan server username and password: 
```
oc get secret <SERVICE_NAME>-generated-secret -o jsonpath="{.data.identities\.yaml}" | base64 --decode
```
or by accessing pod from OpenShift terminal: `cat server/conf/users.properties`

3. Use quickstart project https://github.com/quarkusio/quarkus-quickstarts/tree/main/infinispan-client-quickstart
4. Setup `application.properties`
```
quarkus.infinispan-client.server-list=kshpak-dg-infinispan-external-kshpak-dg.<OPENSHIFT_API> (TRIED WITH PORTS AS WELL: 11222, 80, 443)

# Auth
quarkus.infinispan-client.auth-username=developer (FROM STEP 2)
quarkus.infinispan-client.auth-password=SytgcFAKEKLius (FROM STEP 2)

# Defautls (optional)
# quarkus.infinispan-client.auth-server-name=kshpak-dg-infinispan
# quarkus.infinispan-client.sasl-mechanism=DIGEST-MD5

# Optional Encryption (not needed if using datagrid cluster without encryption) 
quarkus.infinispan-client.trust-store=/tmp/server.jks
quarkus.infinispan-client.trust-store-password=password
quarkus.infinispan-client.trust-store-type=JKS

## Docker 4 Mac workaround
quarkus.infinispan-client.client-intelligence=BASIC
```

5. Run quarkus project: `mvn clean quarkus:dev`

-=-=-=-=-=-=-=-=-=-=-=-=-
-=-=-=-=-=-=-=-=-=-=-=-=-
Key for encryption (STEP 4) generated by:
```
oc get secrets/signing-key -n openshift-service-ca -o template='{{index .data "tls.crt"}}' | openssl base64 -d -A > /tmp/server.crt
keytool -importcert -keystore /tmp/server.jks -storepass password -file /tmp/server.crt -trustcacerts -noprompt
```
Tried also with https://stackoverflow.com/a/11954816/14265173
-=-=-=-=-=-=-=-=-=-=-=-=-
-=-=-=-=-=-=-=-=-=-=-=-=-

### Output of `java -version`

openjdk 11.0.9 2020-10-20 OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06) OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

### Quarkus version or git rev

2.1.3.Final

### Additional information

Ping me on Quarkus Zulip or Google chat if more info needed

**Comment by kshpak** [comment]
Please take a look at it

**Comment by karesti** [comment]
@kshpak I will raise the issue to the team

**Comment by kshpak** [comment]
@karesti any luck with this one? I was also trying to access the Infinispan console/server via port-forwarding but no luck.
`oc port-forward --namespace <namespace> service/<service-name> 11222:11222 11223:11223`

**Comment by karesti** [comment]
@kshpak is this still not working with the latests versions client ?

**Comment by geoand** [comment]
Closing as we never got a reply. 

Feel free to comment and/or reopen if this is still an issue
