### ISSUE TITLE
Improve SIGQUIT handler

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#197]
* Include 'nid' field:
   * On Mac it should be the value of pthread_t (currently what's stuffed in the 'tid' field)
   * On Linux it's the result of `gettid` so it can be correlated to PS/top (but print it in decimal for sanity's sake)
* Fix 'tid' field:
   * On OpenJDK it's meant to be the pointer to the thread internal structure; should be able to derive that from the IsolateThread
* Add in monitors and stuff
   * Figure out which frames grab monitors or locks from the class/method name
   * Snoop the object right off of the call stack using JavaStackWalker and print some interesting info about it

**Comment by stuartwdouglas** [comment]
@dmlloyd is this still an issue?

**Comment by dmlloyd** [comment]
Probably not, I guess.  It's pretty old! 🙂
