### ISSUE TITLE
Expose HttpClient builder or provide mechanism to set RetryHandler 

### ISSUE THREAD

**Issue by yntelectual** [quarkusio/quarkus#19727]
### Description

Resteasy MP rest client uses Apache Http client internally as http engine. Apache HC provides a very useful feature - possibility to [register retryHandler ](https://www.javadoc.io/doc/org.apache.httpcomponents/httpclient/4.4/org/apache/http/impl/client/HttpClientBuilder.html#setRetryHandler(org.apache.http.client.HttpRequestRetryHandler)) which would automatically perform retry if the http called failed on low level intermittent error - such as Socket closed, NoHttpResponseException etc.

Inside Resteasy, the httpEngine can be set in the ResteasyClientBuilder.

MP Rest client provides SPI to modify the RestClientBuilder: https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_provider_declaration
Which allows us to access the `org.jboss.resteasy.microprofile.client.RestClientBuilderImpl` after casting the `clientBuilder` param of `onNewBuilder` method, however, the actual builderDelegate - that allows us to set the httpEngine- only has [package-private accessor ](https://github.com/resteasy/resteasy-microprofile/blob/692168bc2d90b0cbd7ffa4d33c887da1c8aa9723/rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java#L736) and thus we are unable to influence it (without resorting to ugly reflection hacks)

Proposed improvement:

a) expose the `ResteasyClientBuilder`/`builderDelegate` so that applications can modify the low level aspects of http client
b) allow registration of Apache retry handler via config property or other provider mechanism (e.g. `quarkus.http.retryhandler=com.acme.MyCleverRetryHandler` or via the SPI `onNewBuilder`, similarly how internal resteasy props could be set in #17220  
c) define the retry handler directly in Resteasy or some quarkus SPI but allow developers to define the list of exceptions(or other config) when it should be triggered, e.g. based on Apache's [DefaultRequestRetryHandler](https://www.javadoc.io/doc/org.apache.httpcomponents/httpclient/4.3.5/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.html)

**Comment by yntelectual** [comment]
@michalszynkiewicz yes we have done that on several places, but it comes with many drawbacks-  it is very repetitive, if you have any service that uses several rest clients, then you end up with this relatively ugly block on each method. Plus, if you use generated clients(openapi codegen for example) them you cant add the MP FT annotations on the REST endpoint generated interface and you have to do it on the layer where you actually use the client. There is no way how to make that behaviour global in single microservice, let alone across dozens of them (whereas if we can influence the MP Rest client builder, we can easily put it into shared lib)

@geoand I understand that in this case the Quarkus team would not be interested much in investing in config improvement related to Apache HC. However, with option a) it is really a [single accessor change in Resteasy MP client](https://github.com/resteasy/resteasy-microprofile/blob/692168bc2d90b0cbd7ffa4d33c887da1c8aa9723/rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java#L736) - provided that they would be OK accepting that change and making a new release, would that be in turn accepted into Quarkus as a minor change? If yes, could it also be accepted to 1.x branch(we have dozens of services in production running 1.11.x)? Or what is the general process/rules for when a bugfix or update of library gets into 1.x? 

Thanks

**Comment by geoand** [comment]
The general rule is that we won't be doing any new 1.x releases.

If a fix is tiny, then we could make it for the 2.x line. But the old rest client won't be given anything more than trivial maintenance going forward.
That said, the new REST Client is pretty much a drop in replacement for the old one.

**Comment by michalszynkiewicz** [comment]
👍🏻 
If you create a PR, with tests, I think it could go into `main` (2.3+).

With interfaces generated from OpenApi, you could try to create a subinterface of the generated one with `@Retry` on it. I'm 80% sure it would work for the classic rest client and 95% sure it would work for the reactive one ;)

**Comment by geoand** [comment]
Closing this as we have `@Retry` support in the reactive rest client
