### ISSUE TITLE
Add a configuration value/switch to disable the GRPC server in dev mode

### ISSUE THREAD

**Issue by fabland** [quarkusio/quarkus#19721]
### Description

Add a configuration value/switch to disable the GRPC server in dev mode

At the moment there is no way to disable starting of the GRPC server in dev mode. For instance if only the client is used it is weird to have to assign a random port to the GRPC server to solve port collision for instance from a real GRPC server. So I don't really know if this is an actual feature request or a small bug.

### Implementation ideas

Have a configuration value which disables the starting of the server, e.g.:
quarkus.grpc.server.enable

**Comment by michalszynkiewicz** [comment]
@fabland would you be interested in contributing this? :)
