### ISSUE TITLE
Reading REST response headers

### ISSUE THREAD

**Issue by ambition-consulting** [quarkusio/quarkus#19738]
### Description

To my understanding, sending request headers is easy, reading them (for response processing, not in some filter processing) not so much. The only way I found in RestEasy, was using the ResponseObject, which not only takes away automatic serialization, but also  Uni and reactive processing.

**Comment by ambition-consulting** [comment]
This works for sending headers, but not for receiving them. In our use
case, the response header is used for resource metadata, which is critical
for understanding it.

Guillaume Smet ***@***.***> schrieb am Fr., 27. Aug. 2021,
19:35:

**Comment by geoand** [comment]
Does this concern the REST Client?

**Comment by ambition-consulting** [comment]
Yes, both versions - but I would be happy if even one would allow for this.

Georgios Andrianakis ***@***.***> schrieb am Mi., 1. Sept.
2021, 13:50:

**Comment by geoand** [comment]
You can use `Response` as return type for the method.

**Comment by ambition-consulting** [comment]
@geoand Thank you. I used the [ResponseObject](https://docs.jboss.org/resteasy/docs/3.6.0.Final/userguide/html/RESTEasy_Client_Framework.html) from RestEasy, which also worked - but not together with Unis. 

Maybe it's just me, but is the header reading for REST clients via Response class documented anywhere? If not, please add that the ResponseObject should not be used instead. Probably the same holds true for the more recent [ClientResponse](https://docs.jboss.org/resteasy/docs/2.2.1.GA/userguide/html_single/index.html#Custom_client-side_responses)

**Comment by geoand** [comment]
@michalszynkiewicz WDYT about adding `Response` to the rest client docs?

**Comment by michalszynkiewicz** [comment]
Why not ;)

We finally need to create a reference guide for rest client (and then it will be moved there).

**Comment by tbkahuna48** [comment]
Client Interceptor: Request 
@Override
	public void filter(ClientRequestContext clientRequestContext) throws IOException {
String clientRequestHeader -> (String) clientRequestContext.getHeaders().getFirst(MvpConstant.CORRELATION_ID);
or you can get the header map -> clientRequestContext.getHeaders()

Client Interceptor: Response
@Override
	public void filter(ClientRequestContext clientRequestContext, ClientResponseContext clientResponseContext)
			throws IOException {
String clientResponseHeader = clientResponseContext.getHeaderString(instruction.name());
etc.
