### ISSUE TITLE
IsDockerWorking excludes the ability to simply use the unix socket directly. (docker-in-docker in tekton pipelines)

### ISSUE THREAD

**Issue by stephennimmo** [quarkusio/quarkus#19741]
https://github.com/quarkusio/quarkus/blob/966b67369dda58fd2a88e4719155a4c0d1cd1533/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L39

The devservices work great until we get to using them in tekton pipelines. Testcontainers requires docker (unfortunately) and in the past, this was solved by running a docker-in-docker sidecar in a task, mounting the unix socket folder from the sidecar where docker is running into the maven container at the location expected by testcontainers (/var/run/docker.sock). 

When using testcontainers directly, this solution works. However, devservices has the IsDockerWorking class (link above) that essentially forces the use of a tcp socket to connect to the docker daemon or to have the docker binaries installed. 

This implementation also doesn't respect the testcontainer configuration capabilities as documented here: https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection

**Comment by geoand** [comment]
Thanks for reporting.

This is an interesting use case, but I am not sure I understand what the exact request is here. Do you want to be able to turn off or docker detection or enhance it somehow?

**Comment by stuartwdouglas** [comment]
I think we should be able to enhance it to use the test containers docker client to check if docker is availible when TC is present.

**Comment by geoand** [comment]
Lemme give that a shot

**Comment by stuartwdouglas** [comment]
It maybe should be a seperate IsTestContainersWorking thinking about it, as IsDockerWorking is used in places that don't use test containers.

**Comment by geoand** [comment]
I'll open a draft in a few minutes and we can comment on that

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19764 is what I have in mind
