### ISSUE TITLE
Feature to get the current SessionFactory

### ISSUE THREAD

**Issue by bortolonrodrigo** [quarkusio/quarkus#19740]
### Description

Is it possible to add a new feature in order to get the sessionFactory created by Quarkus / Hibernate? 
I would like to apply an hibernate interceptor but I am not able to do it since I am not able to get the sessionFactory created by Quarkus at runtime.

Regards,
Rodrigo Bortolon

### Implementation ideas

Yes, I am able to set a new session factory to use like this:

HibernateUtil.getSessionFactory()
                    ?.withOptions()
                    ?.interceptor(<interceptor here>) // add interceptor to Session
                    ?.openSession()

where HibernateUtil contains all the config for the datasource but I would like to set the interceptor without creating new session. Instead of, using the session created by Quarkus.

**Comment by bortolonrodrigo** [comment]
Hello,

  I found this command based on HibernateProxy

 ` hibernateProxy.hibernateLazyInitializer.session.factory.withOptions().interceptor(<interceptor here>) `

  but when I use the HibernateProxy like this
  
 ```
 @Inject
  lateinit var hibernateProxy: HibernateProxy
```
  
  I am receiving the following error:
  
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.boot.Metadata and qualifiers [@Default]
[ERROR] 	- java member: br.com.contabilizei.movimentacao.infra.panache.PanacheCfg#metadata
[ERROR] 	- declared on CLASS bean [types=[br.com.contabilizei.movimentacao.infra.panache.PanacheCfg, java.lang.Object], qualifiers=[@Default, @Any], target=br.com.contabilizei.movimentacao.infra.panache.PanacheCfg]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1094)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:259)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.boot.Metadata and qualifiers [@Default]
[ERROR] 	- java member: br.com.contabilizei.movimentacao.infra.panache.PanacheCfg#metadata
[ERROR] 	- declared on CLASS bean [types=[br.com.contabilizei.movimentacao.infra.panache.PanacheCfg, java.lang.Object], qualifiers=[@Default, @Any], target=br.com.contabilizei.movimentacao.infra.panache.PanacheCfg]


Note: I am using Quarkus + Kotlin + Hibernate ORM + Panache (latest version).

Thank you,
Rodrigo Bortolon

**Comment by gsmet** [comment]
You can inject the `SessionFactory` in any CDI bean, it's a bean itself:

```
@Inject
SessionFactory, sessionFactory;
```

**Comment by bortolonrodrigo** [comment]
Hello @gsmet , 

Thank you! I will try this approach. But to apply this config to the global session, can I create a config class like this?

```
@ApplicationScoped
class PanacheConfig {

    @Inject
    lateinit var sessionFacatory: SessionFactory

    constructor() {
        sessionFactory.... <apply interceptor here>
    }

}
```

**Comment by gsmet** [comment]
No you cannot tweak the global SF after its creation.

**Comment by gsmet** [comment]
@Sanne do you remember if we support defining interceptors for the SF managed by Quarkus?

**Comment by bortolonrodrigo** [comment]
Hello guys, any news about this thread?

@gsmet 
@Sanne

**Comment by Sanne** [comment]
hi @bortolonrodrigo , sorry for the delay - I've been away.

So like @gsmet mentioned, we shouldn't allow changes to the SessionFactory after the application was started - that opens up to various problems.

But +1 to allow registering interceptors in some way, that's certainly useful. We need to think how to make that happen in the most convenient way.

**Comment by yrodiere** [comment]
> But +1 to allow registering interceptors in some way, that's certainly useful. We need to think how to make that happen in the most convenient way.

I'm on it.

**Comment by Sanne** [comment]
thanks @yrodiere !

**Comment by bortolonrodrigo** [comment]
Hello guys!

@Sanne , thank you very much for the answer and thank you all about the effort regarding this question. 

I really appreciate that!

Regards,
Rodrigo Bortolon

**Comment by yrodiere** [comment]
Interceptors support: https://github.com/quarkusio/quarkus/pull/20131

**Comment by Sanne** [comment]
Let's close this as

1. injecting a SessionFactory was already supported
2. the real ask here was about suprporting interceptors, which was implemented in #20131 

Thanks for the feedback @bortolonrodrigo !

**Comment by bortolonrodrigo** [comment]
Hello all, 

Thank you very much guys! 

@Sanne , do you have a forecast when a 2.3 release will be released with this new feature? 

Best regards,
Rodrigo Bortolon

**Comment by Sanne** [comment]
We should have one in 2 days.
 - https://github.com/quarkusio/quarkus/wiki/Release-Planning

**Comment by bortolonrodrigo** [comment]
@Sanne, thank you very much!

Regards,
RB
