### ISSUE TITLE
OpenTelemetry missing useful span name & tags for OAuth2/OIDC HTTP operations

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#19745]
### Describe the bug

The quarkus VertxTracingAdapter sets useful span names and attributes for outgoing HTTP requests, but does this only if the request is an instance of `io.vertx.core.http.HttpServerRequest`.

When using OIDC requests to an external oauth2 server are manifested as instances of `io.vertx.core.http.impl.HttpRequestHead`, which is not an instance of HttpServerRequest. 

This means the spans recorded from OIDC communications tend to pretty barbones (e.g. they have a name "post" and no additional http info attribution). 

### Expected behavior

The same span name mapping and tags based on e.g. HTTP headers that apply to HttpServerRequest instances should apply to `io.vertx.core.spi.observability.HttpRequest` instances.

### Actual behavior

Spans recorded from OIDC communications have a name derived from the http method only, and no additional http info attribution)

### How to Reproduce?

Enabling opentelemetry on any OAuth2-secured resource endpoint, and capturing the spans produced for OAuth2 server directed HTTP requests in e.g. jaeger/zipkin should reproduce the problem. Alternatively a simple unit test based on an instance of `io.vertx.core.spi.observability.HttpRequest`.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-18363 LAP1453 3.0.7-338.x86_64 2019-04-30 21:52 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by sberyozkin** [comment]
CC @ebullient

**Comment by radcortez** [comment]
I believe that https://github.com/quarkusio/quarkus/pull/21583 should have fixed this.
