### ISSUE TITLE
config "filter" shows up empty

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19752]
### Describe the bug

Things works nicely at first - can see the improvements from #19541 and if I click on icons in config ui I get to filtered list where I can see things correctly but when I then edit the filter using the filter eventually the show up empty.

### Expected behavior

This is what I see when clicking from the /q/dev page - all properties listed. all good.

<img width="1669" alt="2021-08-28_23-20-46" src="https://user-images.githubusercontent.com/54129/131231298-d5f81a6c-3164-427b-8cb1-20de71e9810d.png">

### Actual behavior

here is what I see if i choose same filter using the filter menu:

<img width="1677" alt="2021-08-28_23-21-12" src="https://user-images.githubusercontent.com/54129/131231318-760685ca-a728-425f-a8d8-0d9cf53889b1.png">

### How to Reproduce?

Using this app:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
/**
 * Run this with `jbang -Dquarkus.container-image.build=true build quarkus.java`
 * and it builds a docker image.
 */
//REPOS https://s01.oss.sonatype.org/content/repositories/snapshots/
//DEPS io.quarkus:quarkus-core:999-SNAPSHOT@pom
//DEPS io.quarkus:quarkus-resteasy
//DEPS io.quarkus:quarkus-smallrye-openapi
//DEPS io.quarkus:quarkus-swagger-ui
//DEPS io.quarkus:quarkus-container-image-jib
//Q:CONFIG quarkus.swagger-ui.always-include=true
//Q:CONFIG quarkus.container-image.name=quarkusjbangdemo
//FILES META-INF/resources/index.html=index.html

import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello")
@ApplicationScoped
public class quarkus {

    @GET
    public String sayHello() {
        return "hello from Quarkus with jbang.dev";
    }

}
```

running it with `jbang --fresh -Dquarkus.dev quarkus.java`

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
Weird! I'll have a look

**Comment by phillip-kruger** [comment]
@maxandersen did you see anything in the logs ? I found an issue with the logstream that registers a listener on **all** select elements, rather than just the one in the log dropdown. I am submitting a PR for that now. But for that one there is a clear stacktrace in the log file.
