### ISSUE TITLE
Replace "Could not find MessageBodyWriter for response object of type: java.util.ArrayList of media type: application/json" with helpful tip

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19756]
### Description

if you forget to add quarkus-resteasy-jackson or quarkus-resteasy-jsonb and try open rest endpoint returning json you just get a single line:

`Could not find MessageBodyWriter for response object of type: java.util.ArrayList of media type: application/json`

Could we be helpful and give a hint to user that what is missing is a json handler, probably missing quarkus-resteasy-jackon or quarkus-resteasy-jsonb ....

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19767 takes care of the issue
