### ISSUE TITLE
cannot create 999-snapshot project

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19754]
### Describe the bug

using:

```
 quarkus --version
Client Version 2.1.3.Final
```

running:
```
 quarkus create -P 999-SNAPSHOT ss2
Creating an app (default project type, see --help).
[ERROR] ❗  Unable to create project: Failed to resolve the default platform JSON descriptor
```

should I not get a 999-SNAPSHOT based project or is sometihng else needed ?

**Comment by maxandersen** [comment]
`quarkus create -P io.quarkus:quarkus-core:999-SNAPSHOT` seem to whats needed which makes sense.

But would be good we could list the "known" platforms quarkus cli has. just to give people a chance to locate the right one for them.

**Comment by ebullient** [comment]
specifying the partial (999-SNAPSHOT) should have worked, and certainly did at one point. You shouldn't have to specify that much to get a local build to work.

**Comment by ebullient** [comment]
We broke this when we changed the default group id to `io.quarkus.platform`

This also works: 
`quarkus create -P io.quarkus::999-SNAPSHOT`
