### ISSUE TITLE
Support logback and log4j2.

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#19761]
### Description

logback and log4j2 support more log adapters than jboss-logmanager, I think Quarkus should support them.

**Comment by gsmet** [comment]
Can you have a look at: https://github.com/quarkiverse/quarkus-logging-logback ?

**Comment by aomsweet** [comment]
Ok, Thank you @gsmet

**Comment by geoand** [comment]
Given how much bad publicity log4j has got over the past few weeks, I'd say that our insistence on only supporting JBoss LogManager has paid off even more.

**Comment by gsmet** [comment]
And for Logback adapters, there is now https://github.com/quarkiverse/quarkus-logging-logback .
