### ISSUE TITLE
Port rest-data-panache to RESTEasy Reactive

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#19771]
### Description

`quarkus-rest-data-panache` currently depends on RESTEasy Classic. 
We should port this to RESTEasy Reactive. 
This won't be trivial as RESTEasy Reactive builds all the necessary information by looking at the Jandex index of existing code, while rest-data-panache generates code which isn't available at this point.

**Comment by loicmathieu** [comment]
I'm not convinced by this one.
Maybe we need to create a rest-data-panache-rx based on RestEasy reactive and provides both flavor.
Rest-data-panache is opinionated, and provides easy to use REST endpoints based on conventions for quick usage, advanced use case will not use it so accoring to me having it using the simpliest extensions is OK.

As I understand it, soon, resteasy classic will be based on resteasy reactive so this may not be very important.

**Comment by geoand** [comment]
> I'm not convinced by this one.
> Maybe we need to create a rest-data-panache-rx based on RestEasy reactive and provides both flavor.
> Rest-data-panache is opinionated, and provides easy to use REST endpoints based on conventions for quick usage, advanced use case will not use it so accoring to me having it using the simpliest extensions is OK.
> 

Agreed. But the base itself provides no additional features. The under the covers transition to RESTEasy Reactive should be absolutely transparent (apart from the different transitive dependencies).

> As I understand it, soon, resteasy classic will be based on resteasy reactive so this may not be very important.

Not true. What will happen likely is that we will be proposing `resteasy-reactive` as the default API layer.

**Comment by geoand** [comment]
Closed by accident, so I am reopening
