### ISSUE TITLE
Quarkus testing using @QuarkusTest, mocks and javax.enterprise.inject.Instance

### ISSUE THREAD

**Issue by gkfirst8** [quarkusio/quarkus#19773]
### Describe the bug

We have an application that uses javax.enterprise.inject.Instance to find all validators for a service. This seems to work nicely but during testing we would like to swap out a few of those validators with a mock to skip their behaviour so it's easier to reach other validators.

When we try to do this using the 'Old approach' (See [Blog-post on this](https://quarkus.io/blog/mocking/)) we notice only the classes with @Mock are injected, not any of the normal ones.

When trying it the 'New approach' we get a javax.enterprise.inject.AmbiguousResolutionException that tells us TypeBValidator is found twice.

This is the setup of a trimmed-down version of our app showing the behaviour:

- Validator-interface
- TypeAValidator (@ApplicationScoped)
- TypeBValidator (@ApplicationScoped)
- REST-Service-class that has a @Inject like this: Instance<Validator> validators via the constructor.

In test-scope we have:

- TypeBMockValidator (which does have @Mock in old and no @Mock in the new approach)
- Test class for REST-Service that is annotated with @QuarkusTest. This test-class calls the REST-service using restassured, right as it's provided when one generates [an example project](https://code.quarkus.io/).

See [the example project](https://github.com/gkfirst8/quarkus-test-instance-example) for all details.

I'm looking for a stable and predictable way to replace only the TypeBValidator during my tests. Any help would be highly appreciated.

### Expected behavior

I'm looking for a stable and predictable way to replace only the TypeBValidator during my tests.

### Actual behavior

When we try to do this using the 'Old approach' (See [Blog-post on this](https://quarkus.io/blog/mocking/)) we notice only the classes with @Mock are injected, not any of the normal ones.

When trying it the 'New approach' we get a javax.enterprise.inject.AmbiguousResolutionException that tells us TypeBValidator is found twice.

### How to Reproduce?

See [the example project](https://github.com/gkfirst8/quarkus-test-instance-example) provided.

### Output of `uname -a` or `ver`

5.4.0-81-generic

### Output of `java -version`

openjdk version "14.0.2" 2020-07-14 OpenJDK Runtime Environment (build 14.0.2+13) OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

### Quarkus version or git rev

<quarkus.platform.version>2.1.4.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

I've developed the example within Eclipse 2021-06

**Comment by gkfirst8** [comment]
I've also posted this issue on Stackoverflow: https://stackoverflow.com/q/68954759/1023341 but was directed here by [geoand](https://stackoverflow.com/users/2504224/geoand).

**Comment by geoand** [comment]
The difference you see in your case for the two approaches is due to the subtleties of how each approach is implemented.
Because of the way you have structured your bean (with the test validator extending an existing validator), you can't really reconcile  the two mock approaches.

The easiest way to overcome the issue in your case would be to annotate `TypeBValidator` with `@DefaultBean`.
In that case, when tests are run `TypeBMockValidator` would become the only implementation of `TypeBValidator` that is a bean and `QuarkusMock.installMockForType` would work just fine.

**Comment by gkfirst8** [comment]
Sorry to bother again but this still does not help enough. Let me explain:

* I did update the example project as to your suggestion (hope I understood correctly: add @DefaultBean to main-scope-class-validators)
* Add logging to tests to show the different steps each test will take
* Notice that the one test that does not use QuarkusMock.installMockForType cannot find any Validator implementations while the other nicely finds one main-scope-validator AND the other replaced version (TypeBMockValidator)
* Notice that when QuarkusMock.installMockForType is not used at all (Put @Disabled at the other test) this test (testHelloEndpoint_NoMocks) nicely finds all main-scope-validators.

I might understand QuarkusMock a tiny bit but it feels like it hides things that are not directly intuitive. Can you please elaborate on this so we can enhance the documentation or write some blog about it, please?

**Comment by geoand** [comment]
Essentially `@Mock` makes Arc (our DI container) prefer that bean over any other.
What `QuarkusMock.installMockForType` does is stuff a delegate into the existing CDI bean.
