### ISSUE TITLE
Quarkus:dev not working

### ISSUE THREAD

**Issue by DDT88** [quarkusio/quarkus#19782]
### Describe the bug

Hi all ,

i have the problem when run mvnw compile quarkus:dev.  ( Java 11 , windows 10 , maven 3.8.2 )
can you help me please? 

below the problem : 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.558 s
[INFO] Finished at: 2021-08-30T16:36:59+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.1.4.Final:dev (default-cli) on project xxx-prova: Execution default-cli of goal io.quarkus.platform:quarkus-maven-plugin:2.1.4.Final:dev failed: A required class was missing while executing io.quarkus.platform:quarkus-maven-plugin:2.1.4.Final:dev: org/fusesource/jansi/internal/Kernel32
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.quarkus.platform:quarkus-maven-plugin:2.1.4.Final
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/xxxx/.m2/repository/io/quarkus/platform/quarkus-maven-plugin/2.1.4.Final/quarkus-maven-plugin-2.1.4.Final.jar
[ERROR] urls[1] = file:/C:/Users/xxxx/.m2/repository/io/quarkus/quarkus-bootstrap-core/2.1.4.Final/quarkus-bootstrap-core-2.1.4.Final.jar
[ERROR] urls[2] = file:/C:/Users/xxxx/.m2/repository/io/quarkus/quarkus-bootstrap-app-model/2.1.4.Final/quarkus-bootstrap-app-model-2.1.4.Final.jar

**Comment by famod** [comment]
Thanks for reporting. This is actually a duplicate and will be fixed in 2.2.1: https://github.com/quarkusio/quarkus/issues/19673#issuecomment-907431746
