### ISSUE TITLE
Quarkus should warn the user that the import-dev.sql is being ignored when setting database generation to 'update'

### ISSUE THREAD

**Issue by kafeltz** [quarkusio/quarkus#19811]
### Description

When setting **%dev.quarkus.hibernate-orm.database.generation=update** and the **%dev.quarkus.hibernate-orm.sql-load-script = import-dev.sql** the script is not loaded in the database, as expected.

But Quarkus should warn the user that the **import-dev.sql** is being ignored. Simply because it took me a while to figure this out.

It would be nice and helpful.

What do you think?

**Comment by gavinking** [comment]
Not sure how this is a Quarkus issue. If such a warning is useful (I'm not at all convinced), then it should be added to Hibernate.

**Comment by kafeltz** [comment]
> Not sure how this is a Quarkus issue. If such a warning is useful (I'm not at all convinced), then it should be added to Hibernate.

Good point.

**Comment by yrodiere** [comment]
Hey,

Related (kind of): #21866

I'm going to close this; please report Hibernate ORM enhancement requests directly to Hibernate ORM: https://hibernate.atlassian.net/browse/HHH

Thanks.
