### ISSUE TITLE
Flyway locations not working on native image

### ISSUE THREAD

**Issue by querdenker2k** [quarkusio/quarkus#19817]
### Describe the bug

When i use flyway to perform database migration on application start (_migrate-on-start_), with configured path like this:
_quarkus.flyway.locations=filesystem:db/migration/${quarkus.datasource.db-kind}_ this works fine in jvm build, but in native image.

### Expected behavior

Quarkus/Flyway should take the configured path and do the database migration.

### Actual behavior

In native build i can't get it to work. The output is everytime (whatever i have configured):
```
[2021.08.31 20:14:14.349 DEBUG [      i.q.f.r.QuarkusPathLocationScanner] - Locations: [classpath:db/migration/h2]
[2021.08.31 20:14:14.350 DEBUG [      i.q.f.r.QuarkusPathLocationScanner] - Migration file 'db/migration/postgresql/V5.0.0__initial.sql' will be ignored because it does not start with 'db/migration/h2/'
```
Therefor no database migration is performed.
I tried as well with `FLYWAY_LOCATIONS` environment variable but this changes nothing.

### How to Reproduce?

Configure flyway with migrate-on-start and a location (other than the default).
Build for jvm should work.
Build for native image don't work.

### Output of `uname -a` or `ver`

linux (running inside docker)

### Output of `java -version`

graal 11.0.12

### Quarkus version or git rev

2.1.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.2

**Comment by geoand** [comment]
Can you attach a sample project that exhibits this behavior please?

**Comment by querdenker2k** [comment]
Ok, i created a reproducer. but unfortunately its working. Well i have to find out why my setup does not work...

**Comment by querdenker2k** [comment]
Ok, i got it.
Now its not working: https://github.com/querdenker2k/quarkus-flyway-failure
The problem is that i cannot override _quarkus.flyway.locations_ at runtime, its always taken the value at buildtime.

**Comment by geoand** [comment]
This is done by design. The reason is that it enables a lot of optimizations, some of which are needed for native-image to work correctly
