### ISSUE TITLE
ServerResponseFilter not executed with SSE endpoint using Kotlin Flow

### ISSUE THREAD

**Issue by a-frank** [quarkusio/quarkus#19825]
### Describe the bug

When having an endpoint responding with server sent events using Kotlin Flow, any following ServerResponseFilter is not executed anymore. 

Example:

**Endpoint**
```
@GET
@Path("sse")
@Produces(MediaType.SERVER_SENT_EVENTS)
@RestSseElementType(MediaType.APPLICATION_JSON)
fun getSse(): Flow<String> = flow {
    emit("One")
    delay(100)
    emit("Two")
    emit("Three")
}
```

**ServerResponseFilter** 
```
class SseResponseFilter(private val logger: Logger) {
	@ServerResponseFilter
	fun additionalWork(responseContext: ContainerResponseContext) {
               logger.info {"Never logged"}
	}
}
```

**Comment by geoand** [comment]
This is actually the expected behavior. 

From https://quarkus.io/guides/resteasy-reactive#streaming-support:

```
Response filters are not invoked on streamed responses, because they would give a false impression that you can set headers or HTTP status codes, which is not true after the initial response. 
```

**Comment by a-frank** [comment]
How would you add additional headers to all your SSE endpoints, that a returned on the first response if that is not supported @geoand?
I also tried to return a Flow in a Response object with header MediaType.SERVER_SENT_EVENTS (+additional headers), but here the reponse to the client is just a simple 200 with no further events. Using Response return would be more of a workaround since it can't be implemented crosscutting to all SSE endpoints

**Comment by geoand** [comment]
You can't really.

@FroMage maybe we should introduce some kind of explicitly limited form of response filter in order to cater for these use cases?

**Comment by a-frank** [comment]
Would be cool of there is a mechanism to provide additional data, like headers, to the initial response of a SSE endpoint. 
Preferably with the possibility to do it cross-cutting for all SSE responses
