### ISSUE TITLE
'copy to profile' not limited by config editor scope

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#19821]
### Describe the bug

If I click on the 'Config Editor' button for Open ID Connect, it shows all the OIDC properties, however if I then hit 'copy to profile' it copies all dev service properties (e.g. if I have a database these get copied as well).

### Expected behavior

I would expect only properties from the current scope to be copied. 

### Actual behavior

All properties are copied

**Comment by phillip-kruger** [comment]
OK, So when filtered, we should take the filer into account when DevServices is copied. I'll look at that.
