### ISSUE TITLE
Rest Client: Support config properties in @ClientHeaderParam

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#19828]
### Description

Support passing header values from properties directly with sth like 

```java
@ClientHeaderParam(name="my-header", value="${my-property}")
```

**Comment by michalszynkiewicz** [comment]
Note: This change will be implemented only in Rest Client Reactive

**Comment by cescoffier** [comment]
Maybe a bit of rationale.
When integrating remote HTTP services, you often need to pass headers, typically to handle authentication (you pass a token or an API key). The rest client provides header support, but the value of the headers cannot come from the configuration. You need to target a static method. As these static methods cannot use @ConfigProperty, you end up using a static accessor for the configuration. Far from 1. being easy, 2. being discoverable.

The extension to customize the header can work but introduce another bean implementing a convoluted interface (receive 2 multimaps and returns one).

The idea here is to provide an easy way to access configured properties, without having to use any of these approaches. Something plain simple. 

One question is where the property must be resolved from the config-key of the client or from the root of the configuration.

**Comment by michalszynkiewicz** [comment]
fixed in the linked PR. 
ATM we use root-based config keys.
