### ISSUE TITLE
Upgrade from 2.1.4 to 2.2.1 - Resource and Validator Tests Failing

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#19834]
### Describe the bug

Quickly testing upgrading from 2.1.4 to 2.2.1 my resource and validator tests have started to fail.  I double-checked by going back to 2.1.4 and they pass.  No changes have been made except the Quarkus version.

Attached is a reproducer demonstrating the same results - 2.1.4 works / 2.2.1 fails.
[upgrade.zip](https://github.com/quarkusio/quarkus/files/7091572/upgrade.zip)

**Validation Test using Hibernate Validator:**
should_validate_optional  Time elapsed: 0.003 s  <<< ERROR!
javax.validation.ValidationException: HV000149: An exception occurred during message interpolation
        at ervices.client.ClientValidationTest.should_validate_optional(ClientValidationTest.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getHttpHeaders()" because the return value of "org.jboss.resteasy.reactive.server.injection.ContextProducers.getContext()" is null

**REST Resource Test:**
should_create_feature  Time elapsed: 0.034 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <401>.

### Expected behavior

Test cases that passed using 2.1.4 pass using 2.2.1 since there was no significant changes that would affect them running.

### Actual behavior

Validator and Resource tests fail

### How to Reproduce?

Using the reproducer:

1. Run as is `mvn install` - tests will fail
2. Change version to 2.1.4 and run `mvn install` - tests will pass

### Quarkus version or git rev

2.2.1.Final

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19842 and https://github.com/quarkusio/quarkus/pull/19844 take care of the 2 problems

**Comment by geoand** [comment]
Both PRs have been merged, so I am going to close this
