### ISSUE TITLE
Reactive datasource / DevServices doesn't support sql qualified table name

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#19841]
### Describe the bug

Extensions: 
- `quarkus-reactive-pg-client`
- `quarkus-reactive-mysql-client`

Quarkus Version: Upstream

Previous to DevServices was possible to make queries providing a qualified table name, for example:

```
 SELECT * FROM store.book
```

Because we provide to the datasource all the information that was required in order to set a default or active DB
However, with devServices was not possible to provide a Schema name so all the Queries that use qualified table names don't work, throwing the following error:

```
relation \"store.book\" does not exist
```

**Comment by stuartwdouglas** [comment]
Can you provide a reproducer? It seems like this is more likely to be an issue with the schema the tables are created in, rather than the actual query using a fully qualified name.

**Comment by pjgg** [comment]
Imagine that you have a project with an application property defined like this one:

 ```
## Postgresql
## Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.reactive.url=postgresql://localhost:5432/amadeus
quarkus.datasource.reactive.max-size=5
quarkus.datasource.reactive.idle-timeout=10
quarkus.datasource.reactive.reconnect-attempts=3
quarkus.datasource.reactive.reconnect-interval=3
```

With a PostgresqlResource used by Quarkus test like this one: 
https://github.com/quarkus-qe/beefy-scenarios/blob/main/303-quarkus-vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/test/resources/PostgresqlResource.java#L21

As you can see in the last link the DB schema is set as `Amadeus`
```
 postgresContainer = new GenericContainer<>(DockerImageName.parse("quay.io/debezium/postgres:latest"))
                .withEnv("POSTGRES_USER", "test")
                .withEnv("POSTGRES_PASSWORD", "test")
                .withEnv("POSTGRES_DB", "amadeus")
                .withExposedPorts(5432);
```

And the queries could be done, following a qualified table name nomenclature, for example:
https://github.com/quarkus-qe/beefy-scenarios/blob/main/303-quarkus-vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Airport.java#L59

```
"SELECT * FROM amadeus.airports"
```

Now Imagine that you try to move on this scenario to DevServices, you will end up with a configuration like the following one:
```
quarkus.datasource.db-kind=postgresql
```

Where the database schema is not defined anywhere.
Example project:
https://github.com/quarkus-qe/quarkus-test-suite/tree/main/sql-db/reactive-postgresql

As tools like Flyway doesn't work yet on DevServices, we could do some patch like this one (in order to create the tables, but not the schema, flyway doesn't create Schemas):

https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/resources/BookResource.java#L34

Then your queries don't know which schema was created by devservices, so can't be used as part of the query. 
Maybe would be great to have some optional property like `quarkus.datasource.devservices.db-name` in order to be able to set the schema name, same as DB port...

**Comment by geoand** [comment]
Is this still an issue?

**Comment by gsmet** [comment]
I think it has been implemented as I see:

```
quarkus.datasource.devservices.db-name
quarkus.datasource."datasource-name".devservices.db-name
```

in the reference documentation.
