### ISSUE TITLE
Mock RestClient with producer

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#19865]
### Describe the bug

I'm producing a RestClient, since I need to configure some things that cannot be specified by properties.

    @Produces
    @ApplicationScoped
    public InternalService createMyService() {
        RestClientBuilder restClientBuilder = RestClientBuilder.newBuilder()
                .baseUri(URI.create(serviceUrl));

        // some other logic
        System.out.println("Produced InternalService");

        return restClientBuilder.build(InternalService.class);
    } 

Therefore I used to inject it with:

    @Inject
    InternalService myService;

and mock with

    @InjectMock
    InternalService internalService;

Until Quarkus 2.0.3 it worked. Since 2.1.0 and also on 2.2.1 it gives:

    Caused by: javax.enterprise.inject.AmbiguousResolutionException: [io.quarkus.test.InternalService_7ad2fc3b76b323cb7d3a422dd9e99e1f7496ba8c_Synthetic_Bean@13fdbcd, io.quarkus.test.InternalServiceProducer_ProducerMethod_createMyService_4e02b8280ff73df84a4efd5e7c3987a1c788ca9c_Bean@ac4b7b20]

### Expected behavior

The test produces the injectable mock.

### Actual behavior

An AmbiguousResolutionException is thrown.

### How to Reproduce?

https://github.com/antoniomacri/quarkus-rest-client-producer

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by geoand** [comment]
You can get around this by adding `@AlternativePriority` to your producer method.

```java
    @Produces
    @ApplicationScoped
    public InternalService createMyService() {
        RestClientBuilder restClientBuilder = RestClientBuilder.newBuilder()
                .baseUri(URI.create(serviceUrl));

        // some other logic
        System.out.println("Produced InternalService");

        return restClientBuilder.build(InternalService.class);
    }
```
