### ISSUE TITLE
Enable JVM polling mode for QuarkusIntegrationTest and amazon-lambda

### ISSUE THREAD

**Issue by 0x4a616e** [quarkusio/quarkus#19862]
### Description

When running a `QuarkusIntegrationTest`, the `QuarkusIntegrationTestExtension` launches the currently built executable wich may either be a JVM build or a native build.

For native builds, the lambda poll loop is started automatically, so within a test case, you can use `LambdaClient.invoke` to send events to the started lambda instance.

This however only works for native builds as (AFAIK), there is no way to enable the lambda poll loop for the lambda instance that is started by `QuarkusIntegrationTestExtension ` because it can only be enabled for dev or test launch modes. As `QuarkusIntegrationTestExtension` "normally" starts the built jar, the launch mode is also set to `NORMAL`. As a result, the integration tests can only work for native builds.

It would be great if it would be possible to run `QuarkusIntegrationTestExtension` for lambdas for both JVM and native builds. Thus, it would really help if there would be a way to enable the JVM poll mode during integration tests.

### Implementation ideas

I guess in https://github.com/quarkusio/quarkus/blob/2.2.1.Final/extensions/amazon-lambda/deployment/src/main/java/io/quarkus/amazon/lambda/deployment/AmazonLambdaProcessor.java in

```
LaunchMode mode = launchModeBuildItem.getLaunchMode();
        if (config.enablePollingJvmMode && mode.isDevOrTest()) {
            recorder.startPollLoop(shutdownContextBuildItem);
        }
```

there should be a way to force enabling the poll loop for integration tests.

On the current `main` branch however, it looks like the flag has been removed.

**Comment by geoand** [comment]
@patriot1burke does it make sense to control whether the poll loop starts with some kind of system property?
That way the `@QuarkusIntegrationTest` could pass this flag when it launches the application

**Comment by patriot1burke** [comment]
This point is moot now:  Please see this:

https://bill.burkecentral.com/2021/09/08/quarkus-live-coding-and-continous-testing-with-lambda/

**Comment by geoand** [comment]
But this issue is for the `@QuarkusIntegrationTest`, no? 
In that case, the application is just run via `java -jar ...` and there is no polling enabled.

**Comment by 0x4a616e** [comment]
I also read the link you shared and it looks like a cool way for manual testing. Yet, I also wondered how this will affect `@QuarkusIntegrationTest`s or native image tests.

**Comment by patriot1burke** [comment]
Again, check out my PR (in main now).  The poll loop is now ALWAYS started in test and dev mode now for JVM mode.  Quarkus automatically starts a mock event server which you can post requests to via HTTP and the poll loop queries the mock event server for new events.  In native mode, this mock event server is also always started.  (The mock server is a quarkus "Dev Service").

For previous versions of quarkus you can force the poll loop to start.  Check out the lambda integration tests for older non-main versions of quarkus.

**Comment by patriot1burke** [comment]
We could make a switch to turn on the poll loop, but IMO, this defeats the purpose of  @QuarkusIntegraionTest as the quarkus poll loop will not run when deployed in a real Lambda environment

**Comment by geoand** [comment]
> We could make a switch to turn on the poll loop, but IMO, this defeats the purpose of @QuarkusIntegraionTest as the quarkus poll loop will not run when deployed in a real Lambda environment

👍🏼

**Comment by 0x4a616e** [comment]
Sorry for asking this again, but is the poll loop really not enabled when the quarkus lambda is deployed in a real Lambda environment? At least native builds AFAIK do enable the poll loop as they run in a custom environment and otherwise there would not be a way for them to retrieve new events.
