### ISSUE TITLE
Multiple rest reactive client extensions

### ISSUE THREAD

**Issue by harshmadhani** [quarkusio/quarkus#19860]
### Describe the bug

I am seeing multiple rest client reactive extensions. These are the ones which have confused me at the moment:

jaxrs-client-reactive
rest-client-reactive
rest-client-reactive-jackson

Can you help figure out which ones to use and when?

**Comment by harshmadhani** [comment]
cc @ebullient @geoand

**Comment by geoand** [comment]
@michalszynkiewicz I think we need some kind of rest-client reference doc, much like we have for RESTEasy Reactive.
In there we could explicitly mention where we envision these being used.

@harshmadhani the easy answer for now is that  `rest-client-reactive-jackson` depends on `rest-client-reactive` and simply brings in Jackson serialization / deserialization.
`jaxrs-client-reactive` is an implementation of the JAX-RS Client (which we need for the TCK to pass) that allows users to perform programmatic HTTP calls.

**Comment by ebullient** [comment]
Right. I asked for this issue to be opened so we minimally can update the descriptions in quarkus-extension.yaml (or decide to hide jaxrs-client-reactive) to make choices clearer. Right now, the text overlaps and doesn't give enough information to disambiguate which you should use.

**Comment by michalszynkiewicz** [comment]
@stuartwdouglas @FroMage what do you guys think of merging jaxrs-client and rest-client reactive (or hiding the former one)?

**Comment by geoand** [comment]
I think we can hide the former. We still need it however to pass the testsuite.
