### ISSUE TITLE
MINOR Getting Started Guide example fix

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkus#1987]
In https://quarkus.io/guides/getting-started-guide the example shows the output of curl on example application which returns the string 'hello'. However, on some environments that string ends up being placed on the same line as the command line prompt which can make it harder to see, so suggest changing ...

 @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";

... to

 @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello\n";

**Comment by Sanne** [comment]
ouch, the boss is back writing in all-capitals :)

**Comment by nmcl** [comment]
;)

Suggest the same for the example modification later in the section:

@ApplicationScoped
public class GreetingService {

    public String greeting(String name) {
        return "hello " + name + "\n";
    }

**Comment by Sanne** [comment]
@nmcl thanks, sent a PR.

A suggestion: for any such small detail it might be easier to just edit the file on the web UI.
For example in this case, navigate to  https://github.com/quarkusio/quarkus/edit/master/docs/src/main/asciidoc/getting-started-guide.adoc you can then create a git commit and send a PR directly.

**Comment by nmcl** [comment]
Though the tests also need to be changed:

@QuarkusTest
public class GreetingResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("hello\n"));
    }

    @Test
    public void testGreetingEndpoint() {
        String uuid = UUID.randomUUID().toString();
        given()
          .pathParam("name", uuid)
          .when().get("/hello/greeting/{name}")
          .then()
            .statusCode(200)
            .body(is("hello " + uuid + "\n"));
    }

}
