### ISSUE TITLE
quarkus CLI extension list failing

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/quarkus#19894]
### Describe the bug

Has a Quarkus maven project with 2.1.3.Final
```

quarkus extension list --verbose

[DEBUG] List extensions with initial parameters: ProjectExtensionList [format=io.quarkus.cli.common.ListFormatOptions@74eb909f, installable=false, searchPattern=*, output=OutputOptions [testM
ode=false, showErrors=false, verbose=true], runMode=RunModeOption [batchMode=false, dryRun=false]]                                                                                             
Refreshing the local extension catalog cache of registry.quarkus.io                                                                                                                            
Refreshing the local extension catalog cache of registry.quarkus.io                                                                                                                            
[DEBUG] Resolved registry descriptor io.quarkus.registry:quarkus-registry-descriptor:json:1.0-SNAPSHOT from registry.quarkus.io                                                                
[DEBUG] Resolving platform extension catalog io.quarkus.platform:quarkus-bom-quarkus-platform-descriptor:json:2.1.3.Final:2.1.3.Final                                                          
[DEBUG] Resolving platform catalog io.quarkus.registry:quarkus-platforms:json:2.1.3.Final:1.0-SNAPSHOT                                                                                         
[ERROR] Unable to list extensions: No catalogs provided                                                                                                                                        
```

### Expected behavior

Should not error

### Actual behavior

Error is generated

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1165]

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### Quarkus version or git rev

2.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Users\JeffMAURY\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: C:\apps\AdoptaJDK\openjdk\jdk-11.0.8+10 Default locale: fr_FR, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by ebullient** [comment]
You're invoking this from within a project directory or outside of a project directory?

**Comment by jeffmaury** [comment]
This was with cli 2.1.0.Final and from a 2.1.3.Final project

**Comment by jeffmaury** [comment]
Seems to be fixed with latest client
