### ISSUE TITLE
quarkus.security.jaxrs.deny-unannotated-endpoints=true does overrule @TestSecurity(authorizationEnabled = false)

### ISSUE THREAD

**Issue by TheParad0X** [quarkusio/quarkus#19896]
### Describe the bug

As mentioned [here](https://stackoverflow.com/questions/69028193/does-quarkus-security-jaxrs-deny-unannotated-endpoints-true-overrule-testsecuri?noredirect=1#comment122001326_69028193), I was asked to open this issue:

My (REST) Tests are all annotated with io.quarkus.test.security.TestSecurity's
`@TestSecurity(authorizationEnabled = false)`

When adding
`quarkus.security.jaxrs.deny-unannotated-endpoints=true`
they all fail with a 401 (thus ignoring the authorizationEnabled flag)

Is this the intended behavior?

### Expected behavior

To me, @TestSecurity(authorizationEnabled = false) should disable security for any endpoint, annotated or not.

### Actual behavior

quarkus.security.jaxrs.deny-unannotated-endpoints=true does overrule @TestSecurity(authorizationEnabled = false)

As a Workaround, I had to use
`@TestSecurity(user = "testUser", roles = {"admin"})`

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7) OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by geoand** [comment]
@sberyozkin @FroMage @stuartwdouglas what do you believe the expected behavior to be?

**Comment by sberyozkin** [comment]
Makes sense

**Comment by stuartwdouglas** [comment]
This does not sound right, `deny-unannotated-endpoints` should be basically doing a `@DenyAll`, so adding a username and roles should have no effect.

**Comment by geoand** [comment]
I'll have a look
