### ISSUE TITLE
Two conflicting default values for quarkus.log.console.darken

### ISSUE THREAD

**Issue by hwellmann** [quarkusio/quarkus#1989]
I've just upgraded to 0.13.1 and tried the new config property `quarkus.log.console.darken`.

I set it to 1 in my `application.properties`, and the log output is now indeed more readable on a white background.

On the other hand, I'm now getting a new warning which doesn't really make sense:

````
2019-04-10 18:20:44,214 WARN  [io.qua.configuration] (build-1) Two conflicting default values were specified for configuration key "quarkus.log.console.darken": "0" and "1" (using "0")
````
Is there a confusion about a configurable property vs. its configurable default value?

**Comment by dmlloyd** [comment]
This is happening due to a workaround I've put in to allow this value to be overridden directly by an environment variable.  I have a better fix coming up pretty soon though.  I'll keep this open until that fix gets in.
