### ISSUE TITLE
AWS / Amazon extensions in preview

### ISSUE THREAD

**Issue by tlloyd-synalogik** [quarkusio/quarkus#19898]
### Description

Hello!

Not sure if this has been asked before but it looks like almost all of the AWS extensions are marked as "preview" status.
I raised this on the mailing list recently and Bill from Redhat acknowledged that the extensions have been around for a couple of years.

I would like to use the "quarkus-amazon-lambda-http" extension in production as it makes it straightforward to migrate a JAX-RS REST API over to Lambda. However I am hesitant to do so since the technology is not yet considered stable.

Any news on when this extension and the other AWS extensions will move to stable status?
I am probably not the only one wishing to migrate a project over to Quarkus with use of the AWS extensions!

Kind regards,

Tom

**Comment by geoand** [comment]
Hi,

This has since been fixed in https://github.com/quarkusio/quarkus/pull/19837

**Comment by tlloyd-synalogik** [comment]
Great thanks!
