### ISSUE TITLE
Static resources as operations in Jaeger

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#19907]
### Describe the bug

After enabling tracing with OLTP for a frontend application, I realised that even static resources are being shown as operations in the Jaeger UI (see attached picture). 
<img width="565" alt="Screenshot 2021-09-03 at 16 15 42" src="https://user-images.githubusercontent.com/7215870/132021182-692ff5c8-1161-4679-ae72-ab3448a3f76f.png">

### Expected behavior

Only REST operations are listed 

### Actual behavior

Static resources are shown as operations

### Output of `uname -a` or `ver`

Darwin DWI-MBP15-1.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.6" 2020-01-14 LTS

### Quarkus version or git rev

2.2.1.Final

**Comment by kenfinnigan** [comment]
Can you confirm this is with the OpenTelemetry exporter extension?

While it might be beneficial to trace static resource retrieval, it should be off by default. This ties into #18708 for being able to exclude URL paths from tracing

**Comment by dwamara** [comment]
You mean with this because that's how I added it to my pom except for the application.properties where it is configured:

>         <dependency>
>            <groupId>io.quarkus</groupId>
>            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
>        </dependency>

**Comment by kenfinnigan** [comment]
Yes, and thanks for confirming
