### ISSUE TITLE
ConsumeEvent with Blocking Threading on wrong ExecutorService

### ISSUE THREAD

**Issue by owlkaboom** [quarkusio/quarkus#19911]
### Describe the bug

I have been running into a weird threading issue while using the ConsumeEvent while blocking is set to true.

I have noticed that when running locally via quarkusDev the function that is marked ConsumeEvent(blocking = true) is showing (vert.x-worker-thread-X) as the thread-name; this is working as I would expect and it only uses workers up to the configured quarkus.vertx.worker-pool-size.

After building the project and running it via java -jar. The same function now shows (executor-thread-X) when consuming the events and it seems unbounded. It does not obey the quarkus.vertx.worker-pool-size property.

### Expected behavior

The thread name for the function with ConsumeEvent(blocking = true) is (vert.x-worker-thread-X) when running a build with java -jar

### Actual behavior

The thread name for the function with ConsumeEvent(blocking = true) is (executor-thread-X) when running a build with java -jar.

### How to Reproduce?

I have made a simple project to reproduce the bug. https://github.com/owlkaboom/quarkus-threading-question.

1. Run the project with quarkusDev and you should see the expected behavior
2. Now build and run the build/quarkus-app/quarkus-run.jar with java -jar and you should see the Actual Behavior.

### Output of `java -version`

openjdk version "14" 2020-03-17 OpenJDK Runtime Environment (build 14+36-1461) OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.2.1-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

6.9

**Comment by mkouba** [comment]
Hm, the generated `EventConsumerInvoker` seems to be ok, i.e. the `EventConsumerInvoker.isBlocking()` method returns `true` and it should be executed with `Context.executeBlocking()`.

**Comment by mkouba** [comment]
@kenfinnigan @stuartwdouglas the implementation of [QuarkusExecutorFactory#createExecutor()](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/QuarkusExecutorFactory.java#L30-L43) looks strange. It seems that for the dev mode a new executor service is built but for any other launch mode the `QuarkusExecutorFactory.sharedExecutor` is used. And the `QuarkusExecutorFactory.sharedExecutor` is initialized with the `ExecutorBuildItem.getExecutorProxy()` in the `VertxCoreRecorder.configureVertx()`.

**Comment by kenfinnigan** [comment]
I can't remember the exact error, but when the same ExecutorFactory was used in DevMode there were errors.

**Comment by mkouba** [comment]
> I can't remember the exact error, but when the same ExecutorFactory was used in DevMode there were errors.

Ok, but what's the original intent? To use the `ExecutorBuildItem.getExecutorProxy()` as the executor service when the `Context.executeBlocking()` is used?

**Comment by cescoffier** [comment]
@kenfinnigan That is a bit annoying to have such a different behavior.

**Comment by kenfinnigan** [comment]
The original intent was for the Quarkus Executor Factory to utilize the Vert.x Worker pool instead of creating its own.

I think the issue was in DevMode was it prevented shutdown as an executor would be constantly waiting.

**Comment by mkouba** [comment]
> The original intent was for the Quarkus Executor Factory to utilize the Vert.x Worker pool instead of creating its own.

That probably makes sense but is it documented somewhere? I think that it should be at least mentioned in the Vert.x Reference Guide...

**Comment by kenfinnigan** [comment]
Likely not documented

**Comment by geoand** [comment]
This limitation exists in order to be able to properly support dev-mode. It should probably be documented somewhere, the problem is I don't know where :)

**Comment by cescoffier** [comment]
@geoand if we get the duplicated context doc, we could have a section about threads and add a note there. Note sure it's the right place, but at least, it would be somewhere.

**Comment by geoand** [comment]
Yeah, better to start somewhere :)
