### ISSUE TITLE
OAuth and Swagger UI fails on 2.2.1.Final

### ISSUE THREAD

**Issue by flynnk** [quarkusio/quarkus#19923]
### Describe the bug

Get 
`Uncaught TypeError: ui.initOAuth is not a function
    at window.onload ((index):40)`
on the Javascript console when I navigate to the localhost in dev mode (to /q/swagger-ui).

This is an excerpt from the generated Swagger console index.html:

`   
        <div id="swagger-ui"></div>
        <script src="swagger-ui-bundle.js" charset="UTF-8"></script>
        <script src="swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
        <script>

            window.onload = function() {
                
                const ui = {
                    url: '/q/openapi',
                    dom_id: '#swagger-ui',
                    deepLinking: true,
                    presets: [SwaggerUIBundle.presets.apis,SwaggerUIStandalonePreset],
                    plugins: [SwaggerUIBundle.plugins.DownloadUrl],
                    layout: 'StandaloneLayout',
                };
                
                // If Url is relative, append the host and port
                var oar = "/q/swagger-ui/oauth2-redirect.html";
                if(oar.startsWith("/")){
                    oar = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + oar;
                    ui.oauth2RedirectUrl = oar;
                }else if(oar !== "-"){
                    ui.oauth2RedirectUrl = oar;
                }
                
                ui.initOAuth({
		clientId: 'ui',
		appName: 'User Management Swagger UI',
	})
                
                window.ui = SwaggerUIBundle(ui)

                document.getElementsByClassName("link")[0].innerHTML = "<a href='/q/swagger-ui'><img src='logo.png' alt='OpenAPI UI (Powered by Quarkus 2.2.1.Final)' height='44' align='middle'></a>";
            }
        </script>
    </body>
`

### Expected behavior

Swagger UI console is rendered, with an option for OAuth authorization.

### Actual behavior

Swagger UI console fails to render and gives JavaScript error

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1165]

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by phillip-kruger** [comment]
Thanks ! This is already fixed in https://github.com/smallrye/smallrye-open-api/pull/887 and will be pulled into Quarkus soon.
