### ISSUE TITLE
RuntimeUpdatesProcessor always tries to compile package-info.java

### ISSUE THREAD

**Issue by RapidTransit** [quarkusio/quarkus#1992]
RuntimeUpdatesProcessor always tries to compile package-info.java because it matches the `.java` file extension but does not get a `.class` file in the compiled directory. 

I didn't make a test case, I could if it is necessary.

A possible solution:
https://github.com/quarkusio/quarkus/commit/8402942ef406c933bacf0686491d197d1cec7d9b

I wanted to minimize any changes while including a test to verify everything works OK, which required a couple of added dependencies, so I didn't open a pull request.

**Comment by gsmet** [comment]
@RapidTransit could you create a PR so that we can discuss it? That would be easier.

**Comment by gsmet** [comment]
The PR was closed so closing this issue too. Please reopen a new one with a reproducer if you encounter this issue.
