### ISSUE TITLE
JAX-RS ExceptionMappers are never invoked

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1994]
The following `ExceptionMapper` from my application used to be called in Quarkus 0.12.0 when an `IllegalArgumentException` is thrown in JAX-RS endpoints. It is no longer called in 0.13.1:

```java
@Provider
public class IllegalArgumentExceptionMapper implements ExceptionMapper<IllegalArgumentException> {

    @Override
    public Response toResponse(IllegalArgumentException exception) {
        return Response.status(Response.Status.BAD_REQUEST)
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                .entity(createArrayBuilder()
                                .add(createObjectBuilder()
                                             .add("message", exception.getMessage()))
                                .build())
                .build();
    }
}
```

**Comment by gastaldi** [comment]
In the logs, I see some mappers being removed: 

```
17:38:33.369 [main] DEBUG io.quarkus.resteasy.runtime - Create constructor: public io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyViolationExceptionMapper()
17:38:33.370 [main] DEBUG io.quarkus.arc.runtime.ArcDeploymentTemplate - No matching bean found for type class io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyViolationExceptionMapper and qualifiers []. The bean might have been marked as unused and removed during build.
17:38:33.503 [main] DEBUG io.quarkus.resteasy.runtime - Create constructor: public io.fabric8.launcher.web.providers.IllegalArgumentExceptionMapper()
17:38:33.504 [main] DEBUG io.quarkus.arc.runtime.ArcDeploymentTemplate - No matching bean found for type class io.fabric8.launcher.web.providers.IllegalArgumentExceptionMapper and qualifiers []. The bean might have been marked as unused and removed during build.

**Comment by gastaldi** [comment]
@mkouba any thoughts?

**Comment by gastaldi** [comment]
Test that reproduces the problem: https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/test/java/io/fabric8/launcher/web/endpoints/LauncherParamConverterProviderIT.java

**Comment by gastaldi** [comment]
Weird that in 0.12.0 I see the same log output in https://github.com/quarkusio/quarkus/issues/1994#issuecomment-481792708 and the mapper is called.

**Comment by gastaldi** [comment]
This seems to be a bug in Resteasy.

**Comment by mkouba** [comment]
It's definitely not related to the ArC bean removal feature - your `IllegalArgumentExceptionMapper` does not need CDI at all, and so it should be fine to use the default RESTEasy injector.

**Comment by mkouba** [comment]
Not a regression but a bugfix in RESTEasy - see https://issues.jboss.org/browse/RESTEASY-1364 and the relevant commit: https://github.com/resteasy/Resteasy/commit/28d62dae1e8b52554d3c79750cd4249254bdca33#diff-f16a5e4b96ee62250cd95607dbd3d6acR695.
