### ISSUE TITLE
Mutiny Vertx NetClient Tcp Socket Reading Bug

### ISSUE THREAD

**Issue by JayGhiya** [quarkusio/quarkus#19941]
### Describe the bug

While using Mutiny With Vertx Netclient (Tcp Client) to write and read tcp messages, read gets stuck after receiving the first message.

### Expected behavior

Reading of tcp messages should not block the mutiny based netclient pipeline. (This uses netclient tcp client)

### Actual behavior

Reading of tcp messages should not block the mutiny based netclient pipeline. This makes mutiny unsable for tcp communication which is a bummer. Vertx Core Apis (using get delegate) work fine.

### How to Reproduce?

[QuarkusMutinyTcpNetClientSendAndReceiveBug.zip](https://github.com/quarkusio/quarkus/files/7117330/QuarkusMutinyTcpNetClientSendAndReceiveBug.zip)
There would be two projects in attached zip. One for Mutiny based Tcp Client and another for mock server which is used to echo messages. 

> Both are maven projects. Import them and run the server project first and then the tcp client. 

### Output of `java -version`

11

### Quarkus version or git rev

2.2.1.FINAL

### Additional information

This is one of the most basic features that is going to be used by users (Tcp based comm) . It would be great if we can fix this asap. I have limited knowledge on vertx but would love to contribute. But let me know if i can learn and contribute in any way.

**Comment by jponge** [comment]
`collect().asList()` is blocking, there is no bug.

**Comment by JayGhiya** [comment]
@jponge - I do understand it is blocking as it is done on worker pool thread. (@Blocking annotation is there on the method)The concern is this - How does one first write and read response from server using mutiny pipeline of netclient?

**Comment by jponge** [comment]
See https://vertx.io/docs/apidocs/io/vertx/core/net/NetClient.html for the base Vert.x API.

**Comment by JayGhiya** [comment]
> See https://vertx.io/docs/apidocs/io/vertx/core/net/NetClient.html for the base Vert.x API.

I already have seen this :) thanks anyway :) - i have no issues with core vertex api but mutiny one just does not work. the usecase is this: a) i have to send an message b) receive an ack from server c) based on ack take some action! Now c requires i need to block it. I am not able to do it and i highly suspect something is wrong on mutiny wrapper on netclient.

**Comment by JayGhiya** [comment]
`
    @Blocking
    public Uni<Boolean> sendMessage(String msg)
    {

        return this.netSocket
             .invoke(NetSocket::toMulti)
             .call(netSocket1 -> netSocket1.write(msg))
                //this gets triggered once and it gets stuck
                .invoke(() -> LOG.info("Write successful"))
                .onItem()
                //this call is used for reading buffer but this seems to cause issue
                .transformToMulti(NetSocket::toMulti)
                .onItem()
                .transform(buffer ->
                {
                    LOG.infof("Buffer received is %s", buffer);
                    return Boolean.TRUE;
                })
                .toUni();
    }`

` while(count>0)
        {
            quarkusTcpVertxClient.sendMessage(sampleHl7Message).await().atMost(Duration.ofMillis(2000));
            count--;

        }`

Now this also fails, this shud have worked. i know my receiver buffer size i know it is going to be one buffer always. and i would want to take an action on response so i am waiting . this also fails

**Comment by jponge** [comment]
`.invoke(NetSocket::toMulti)` will do nothing in your pipeline.

**Comment by JayGhiya** [comment]
> `.invoke(NetSocket::toMulti)` will do nothing in your pipeline.

Should not it open the handler for receiving before i start writing? then you can read as it is open after writing?

**Comment by jponge** [comment]
My bad, it does transform the value. Still I don't get why you move from a Uni to a Multi, then to a Multi then to a Uni, only to block.

**Comment by jponge** [comment]
Err no, it does not transform. `invoke` is just to perform an action when you receive an item.

**Comment by jponge** [comment]
So here your action is "transform to a Multi", and that Multi is not passed down the pipeline.

**Comment by JayGhiya** [comment]
yea invoke does not transform, but what i thought is i have to open handler for reading right? and then also read. i did not want to use multi but the reason why i thought api returns multi is the server may return data more than received buffer size. i may be wrong but help me understand to achieve this simple usecase using mutiny netsocket :

- Open for reading
- Write
- Delay by sometime for read
- Get Response from server
- Take action based on response
- Convert to await call as i need naked response (wo uni/multi)

**Comment by JayGhiya** [comment]
my bad. This is off topic but i did not realize you are the author of the vertx in action. Planning to read that thanks for the book :) cheers

**Comment by jponge** [comment]
Remember that `Multi`/`Uni` require subscriptions.

So `invoke(foo::toMulti)` doesn't do anything.

I'd rather have a transformation to a `Multi` (if that's required by your logic), then take the resulting `Multi` as a result for the next transformation, etc.

**Comment by JayGhiya** [comment]
ok let me give it a try and get your feedback on modified pipeline thanks @jponge

**Comment by JayGhiya** [comment]
`
    public Uni<Multi<Buffer>> openForReading()
    {
        return this.netSocket
                .map(NetSocket::toMulti);
    }

    public Uni<NetSocket> writeMessage(String msg)
    {

        return this.netSocket
                .onItem()
                .call(netSocket1 -> netSocket1.write(msg))
                .invoke(() -> LOG.info("write successful"));

    }

    @Blocking
    public Uni<Boolean> sendMessage(String msg)
    {
        return Uni.combine().all().unis(openForReading()
        ,writeMessage(msg))
                .asTuple()
                .emitOn(Infrastructure.getDefaultWorkerPool())
                .onItem()
                .transformToMulti(objects -> objects.getItem1())
                .collect()
                .asList()
                .onItem()
                .transform(
                        buffers ->
                        {
                            if(buffers.stream().count()>0)
                            {
                                return Boolean.TRUE;
                            }
                            return Boolean.FALSE;
                        }
                );
    }`

And calling it like this:
`@Blocking
    public void produceMessages() throws ExecutionException, InterruptedException {

        int count = 10;

        while(count>0)
        {
            quarkusTcpVertxClient.sendMessage(sampleHl7Message).await().atMost(Duration.ofMillis(2000));
            count--;

        }
    }
`

This still does not work and gives a mutiny timeout . if i understand correctly now it has map operation instead of invoke and to make sure we open the read handler during write we call them together. Why still it does not work ?

**Comment by jponge** [comment]
Perhaps you're trying to collect all buffers as a list instead of processing them on-the-fly, and the stream hasn't finished yet, hence you don't see anything because it hasn't been closed.

BTW you may just `return buffers.stream().count()>0;` instead of doing a `if`/`else`.

**Comment by JayGhiya** [comment]
Collecting all buffers as a list should work right as I know I get one response for every request. Here the mock server that is part of reproducer instantly replies within 10ms. Why it is not able to collect? This is something I would want to understand. See the actual usecase will have validation on the received response from the server. Over there I won't be doing simple count .I will be required to parse the message.

**Comment by jponge** [comment]
Because your mock server is a mock, not a real socket.

**Comment by jponge** [comment]
Oh and your methods never subscribe to anything.

**Comment by JayGhiya** [comment]
yes they do require subscribing thats why 
`quarkusTcpVertxClient.sendMessage(sampleHl7Message).await().atMost(Duration.ofMillis(2000)); ` we do await ! so pipeline starts. i can also see it writing messages but it gets blocked after first response. Also mock server opens up  a real socket . please refer reproducer code.

**Comment by JayGhiya** [comment]
But as you told, the pipeline is overwriting vertx handlers which is causing the issue. Sticking to core vertx apis for now

**Comment by JayGhiya** [comment]
For anybody who is looking to implement tcp based send/receive code just like http request/response it might require some work. Here is the core vertx code for the same. Get the vertx in your quarkus through constructor injection and then use like this:

`protected void makeConnectionToTcpServer() throws ExecutionException, InterruptedException {
         //Making a connection
        this.netSocket
                = this.vertxNetClient
                .getDelegate()
                .connect(quarkusVertxServerPort,quarkusVertxServerHost)
                .onFailure(throwable -> LOG.errorf("Could not connect due to %s",throwable.getMessage()))
                .onSuccess(netSocket1 -> LOG.info("Connection Successful"))
                .toCompletionStage()
                .toCompletableFuture()
                .get();

    }

    //Get Ready for receiving messages
    protected void receiveMessages()
    {

        this.netSocket.handler(buffer ->
        {
            LOG.infof("BUFFER RECEIVED at time %s", Date.from(Instant.now()).toString());
            this.linkedBlockingDeque.add(buffer.getString(0,buffer.length()));
        });
    }


    @ConsumeEvent(value = "mockmessages",ordered = true,blocking = true)
    public boolean sendMessage(String message) throws InterruptedException {

        //sending
        this.netSocket.write(message)
                        .onSuccess(aVoid -> LOG.info("Message sent Successfully"))
                        .onFailure(throwable -> LOG.errorf("Could not send message retried"))
                        .result();

        //checking ack
        String ack = this.linkedBlockingDeque.poll(500, TimeUnit.MILLISECONDS);
        if(ack.length()>0)
        {
            LOG.info("ACK received");
            return Boolean.TRUE;
        }
    
        return Boolean.FALSE;

    }`

**Comment by jponge** [comment]
Here's a sketch of something similar although "not exactly what you are doing" but that shows `NetClient` handling in plain Vert.x + Mutiny:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.smallrye.reactive:smallrye-mutiny-vertx-core:2.13.0

import java.util.Random;

import io.smallrye.mutiny.Uni;
import io.smallrye.mutiny.vertx.core.AbstractVerticle;
import io.vertx.mutiny.core.Vertx;

public class sample {

    public static void main(String... args) {
        var vertx = Vertx.vertx();
        vertx.deployVerticleAndAwait(new AckServer());
        vertx.deployVerticleAndAwait(new EdgeServer());
    }

    static class EdgeServer extends AbstractVerticle {

        private long counter = 0L;

        @Override
        public Uni<Void> asyncStart() {
            return vertx.createHttpServer()
                .requestHandler(request -> {
                    System.out.println("HTTP request");
                    request.response()
                        .putHeader("Content-Type", "text/plain")
                        .setChunked(true);
                    vertx.createNetClient()
                        .connect(3000, "localhost")
                        .subscribe().with(socket -> {
                            System.out.println("Contacting the ACK server");
                            socket.writeAndForget(counter++ + "\n");
                            socket.toMulti().subscribe().with(
                                buffer -> {
                                    System.out.println("Received " + buffer);
                                    request.response().writeAndForget(buffer);
                                    if (buffer.toString().endsWith("\n")) {
                                        request.response().endAndForget();
                                        socket.closeAndForget();
                                    }
                                },
                                err -> {
                                    request.response().endAndForget(err.getMessage());
                                    socket.closeAndForget();
                                }
                            );
                        });
                })
                .listen(4000).replaceWithVoid();
        }
    }

    static class AckServer extends AbstractVerticle {

        @Override
        public Uni<Void> asyncStart() {
            var random = new Random();
            return vertx.createNetServer().connectHandler(socket -> socket.toMulti().subscribe().with(buffer -> {
                var response = random.nextBoolean() ? "ack\n" : "nack\n";
                System.out.println("[ack server] {" + buffer.toString().replace("\n", "") + "} -> " + response);
                socket.writeAndForget(response);
            })).listen(3000).replaceWithVoid();
        }
    }
}

```

Sticking to the Vert.x core APIs might be simpler here without the need to subscribe to trigger operations.

Note that this is doing 1 TCP connection per HTTP request, if you want to maintain 1 connection for all requests then you'll need some kind of state machine to assemble and forward results.

Hope it helps.

**Comment by JayGhiya** [comment]
Thanks for the sample. Appreciate it. Yes in my usecase only one connection has to be maintained and we do that with core vertx APIs. I agree with such lower stuff core vertx APIs are a better choice. It was just that I wanted to avoid writing code for delaying the item and handling failures etc as that is handled v well by mutiny. But this is good learning. Thankyou
