### ISSUE TITLE
OpenShift labels are not applied to all resources (missing ImageStream and Build resources

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19954]
### Describe the bug

According to the documentation: https://quarkus.io/guides/deploying-to-openshift#quarkus-openshift-openshift-config_quarkus.openshift.labels-labels, the labels should be applied to all the resources, however when deploying the Quarkus application using the OpenShift extension, the labels are missing for the ImageStream, Build and BuildConfig.

### Expected behavior

As far I see it, the labels should be added also to ImageStream, Build and BuildConfig.
If this is done on purpose, the documentation should note it.

**Comment by geoand** [comment]
@iocanel what is your take on this?
I am personally not sure what the proper behavior should be.

**Comment by Sgitario** [comment]
My bad, this is already working as expected. Closing.
