### ISSUE TITLE
@QuarkusMain not called from @QuarkusTest

### ISSUE THREAD

**Issue by JanM-cz** [quarkusio/quarkus#19957]
### Describe the bug

When @QuarkusTest is executed in combination with @QuarkusMain definition, the main class is not being called, but neither is the default configuration context which is normally executed when no @QuarkusMain is defined. This results in "underconfigured" system.

This prevents proper usage of @QuarkusMain for any customizations because they are then not available during @QuarkusTest context. One example would be apache-camel integration when routes are not being registered in such setup, but it seems to be a generic problem.

### Expected behavior

@QuarkusMain annotated class is executed on application startup when @QuarkusTest is being executed.

### Actual behavior

@QuarkusMain class is not being executed at all.

### How to Reproduce?

I've setup a simple apache camel-timer based reproducer to see that neither the default context nor @QuarkusMain context is being properly configured in @QuarkusTest tests. 

To reproduce simply uncomment the @QuarkusMain annotation on MainQuark class and execute the test in TimerRouteTest.

You can observe that:

1. when the application is started normally -> route is being processed and everything works.
2. when @QuarkusMain is commented out and test is executed -> route is being processed and everything works.
3. when @QuarkusMain comment is removed (annotation is activated) and test is executed -> **route is not being configured and is not being executed**

[mainquark.zip](https://github.com/quarkusio/quarkus/files/7120398/mainquark.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1165]

### Output of `java -version`

openjdk version "11" 2018-09-25

### Quarkus version or git rev

2.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
@stuartwdouglas I assume that https://github.com/quarkusio/quarkus/pull/19891 should cover this, right?

**Comment by ebullient** [comment]
Yes. #19891 is specifically to address this case. ;)

**Comment by geoand** [comment]
Excellent 👌🏼 .

So I'll close this as out of date.
