### ISSUE TITLE
Allow using RestResponse<T> as return type for rest client

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#19966]
### Description

The rest client (reactive) allows to use `Response` as a return type for rest methods. Unfortunately, `Response` is not typed at all and thus when you want to access the status code of the response, you cannot specify the type of the response in the rest client interface. This is not so nice, because ideally, you'd like to specify the whole api in that interface. 

In contrast, the `RestResponse<T>` class can already be used in resteasy-reactive for returning a type response. Please also add support for `RestResponse<T>` return types in the rest client (reactive).

**Comment by geoand** [comment]
This is a very good idea!

I'll take a look
