### ISSUE TITLE
CLI help message contains text for registry add command instead of extension add command

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19979]
### Describe the bug

CLI help message contains text for registry add command instead of extension add command.

There is no `add` command listed under `registry`.

```
jbang app install --force --name qss ~/.m2/repository/io/quarkus/quarkus-cli/999-SNAPSHOT/quarkus-cli-999-SNAPSHOT-runner.jar

qss --help
...
  extension, ext      List, add, and remove extensions of an existing project.
    list, ls          List platforms and extensions.
    categories, cat   List extension categories.
    add               Add a Quarkus extension registry to the registry client
                        configuration
    remove, rm        Remove extension(s) from this project.
  registry            Manage extension registries.
    list              List enabled Quarkus registries
    remove            Remove a Quarkus extension registry from the registry
                        client configuration
  version             Display version information.
  completion          bash/zsh completion:  source <(quarkus completion)
```

### Expected behavior

`add` sub-command is listed for both `extension` and `registry` commands

### Actual behavior

`add` sub-command is listed just for `registry` command but with text for `add` sub-command for `extension` command.

### How to Reproduce?

`qss --help` or `quarkus --help`

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

main

### Additional information

Running `qss ext --help` and `qss registry --help` gives correct info.

As if cli had hard time to handle two different sub-commands with the same `name = "add"`.
When I changed value of `name` attribute to `rs` in `RegistryAddCommand`, `qss --help` message got rendered properly.

**Comment by ebullient** [comment]
good catch. Not sure how that happened.
