### ISSUE TITLE
Datasources documentation does not contain JDBC URL reference for Oracle

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#19986]
### Describe the bug

In https://quarkus.io/guides/datasource#jdbc-url (https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/datasource.adoc#jdbc-url-reference), an Oracle subsection is missing. It should provide a description, an example and a link to detailed documentation.

Relevant sources:
https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html
https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/data-sources-and-URLs.html#GUID-C4F2CA86-0F68-400C-95DA-30171C9FB8F0

Example:
```
=== Oracle

`jdbc:oracle:thin:@host:port/service_name`

Example:: `jdbc:oracle:thin:@localhost:1521/test`

For further details, see the https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/data-sources-and-URLs.html#GUID-C4F2CA86-0F68-400C-95DA-30171C9FB8F0[official documentation].
```

**Comment by geoand** [comment]
This seems like it's already been done
