### ISSUE TITLE
quarkus:dev fails on empty project

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#1998]
Creates an empty project, without any sources or resources and run:

```
mvn compile quarkus:dev
...
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.1:dev (default-cli) on project async-demo: The project has no output yet, run `mvn compile quarkus:dev`. -> [Help 1]
```

Either the error messages must be updated to mention that the project must at least contain 1 file, or it should run and waits until we have content.

**Comment by machi1990** [comment]
I can update the error message to something like: `The project ${projectName} has no output yet. Make sure it contains at least one source file.`
