### ISSUE TITLE
Uber-JARs don't support multi-release libraries

### ISSUE THREAD

**Issue by rob-spoor** [quarkusio/quarkus#19991]
### Describe the bug

`quarkus-arc` depends, through `quarkus-core` and `smallrye-config`, on `smallrye-common-classloader`. This is a multi-release JAR file. For Java 8 it uses `sun.misc.Unsafe` to generate implementations of interfaces annotated with `@ConfigMapping`, for Java 9 and up it uses method handles. This library has a manifest entry `Multi-Release: true`, which is needed to make the multi-release mechanism work.

When an uber-JAR is created, the resulting manifest does not have the `Multi-Release: true` entry. As a result, on Java 11, an error is thrown because the method from `sun.misc.Unsafe` that is used in the Java 8 implementation has been removed.

For other forms this all works because the JAR files are kept intact, and the manifest entry is therefore not dropped.

### Expected behavior

When an uber-JAR is created and an interface annotated with `ConfigMapping` is used, this should just work.

If any manifest includes the `Multi-Release: true` entry, this should be included in the resulting manifest.

### Actual behavior

When an uber-JAR is created and an interface annotated with `ConfigMapping` is used, an error is thrown as soon as the interface is used.

The resulting manifest never includes the `Multi-Release: true` entry.

### How to Reproduce?

1. Create a new project.
2. Add a config interface and annotate it with `@ConfigMapping`.
3. Create a bean where this config interface is injected. Annotate it with `@Singleton` and `@Startup` so the problem will be encountered as soon as the application starts.
4. Set the packaging to uber-jar.
5. Start the application and observe the error.cmd

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1165]

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7) OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by rob-spoor** [comment]
If I manually add the `Multi-Release: true` entry to the manifest (the JAR is little more than a simple ZIP file), this error goes away.

We are currently forced to use an uber-JAR because we are using the `quarkus-azure-functions-http` extension that enforces uber-JAR packaging.

**Comment by jaikiran** [comment]
Hello Rob, I've opened https://github.com/quarkusio/quarkus/pull/19999 with a potential fix.

**Comment by rob-spoor** [comment]
Excellent, thanks!
