### ISSUE TITLE
Graceful shutdown doen't work in dev profile and uber-jar

### ISSUE THREAD

**Issue by jrybak23** [quarkusio/quarkus#19994]
### Describe the bug

Docs says that graceful shutdown for HTTP requests supported but. 
https://quarkus.io/guides/lifecycle#graceful-shutdown
Time out is set
`quarkus.shutdown.timeout=PT1H`
It immediately shutdowns regardless of HTTP request that being executed if run:
`kill -s SIGTERM $(lsof -t -i tcp:8080)`

### Expected behavior

It should wait when all responses are sent.

### Actual behavior

It immediately shutdown regardless of HTTP request that being executed if run:
`kill -s SIGTERM $(lsof -t -i tcp:8080)`

### How to Reproduce?

1. Open project [quarkus-shutdown.zip](https://github.com/quarkusio/quarkus/files/7127490/quarkus-shutdown.zip)
2. `mvn clean quarkus:dev` or run uber jar 
```
mvn clean package
java -jar target/quarkus-shutdown-1.0-SNAPSHOT-runner.jar
```
3. send request that runs 10 seconds `curl http://localhost:8080/hello`
4. than `kill -s SIGTERM $(lsof -t -i tcp:8080)`

### Output of `uname -a` or `ver`

Linux jrybak-VirtualBox 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

I also try to test with docker stop and it works as expected
```
docker build -f src/main/docker/Dockerfile.jvm -t quarkus/quarkus-shutdown-jvm .
docker run -i --rm -p 8080:8080 quarkus/quarkus-shutdown-jvm
curl http://localhost:8080/hello
docker stop <container id>
```

**Comment by jaikiran** [comment]
> than kill -s SIGTERM $(lsof -t -i tcp:8080)

I think the command you are running to send the signal will kill both the client (curl) as well as the server. So it's not an accurate test.

Instead, find the Java process representing Quarkus (using `jps -l`) and then send SIGTERM to it:

`kill -s SIGTERM <pid>`

That should work. I just gave this a try locally and it shutdown gracefully after the request completed.

**Comment by stuartwdouglas** [comment]
Closing as per Jaikiran's comment
