### ISSUE TITLE
Resources without a @Path on the class fails

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#1999]
the Following resource:

```
@Produces(MediaType.TEXT_HTML)
public class MyResource {

    @GET
    @Path("/sync")
    public String synchronousHello() {
        return "Hello";
    }
```

gives: `=> RESTEASY003210: Could not find resource for full path: http://localhost:8080/sync`

**Comment by younss** [comment]
do you have more log?

**Comment by mkouba** [comment]
Looks like a bug in `ResteasyScanningProcessor` - only classes annotated with `@Path` are registered as JAX-RS resources: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java#L296

**Comment by mkouba** [comment]
Actually, it seems that the **root resource classes** must be annotated with `@Path`. When I change the behavior I get: `RESTEASY003130: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path`.

**Comment by mkouba** [comment]
JAX-RS spec - Terminology:
> **Root resource class:** A resource class annotated with `@Path` . Root resource classes provide the roots of the resource class tree and provide access to sub-resources, see Chapter 3.

**Comment by mkouba** [comment]
@asoldano @ronsigal Could you pls confirm my finding?

**Comment by ronsigal** [comment]
Hi @mkouba,

One more point. The algorithm in Section 3.7.2 "Request Matching" of the JAX-RS spec starts with 
```
1. Identify a set of candidate root resource classes matching the request:
```
Only root resources are eligible to be matched against a request. So there's no bug here.

-Ron

**Comment by mkouba** [comment]
Thanks Ron. Marking the issue as invalid.

**Comment by cescoffier** [comment]
Ok, I still found it a bit weird to force the user to add `@Path("/")`. We need to check how other frameworks are doing this.

**Comment by mkouba** [comment]
Yep, it is weird.
