### ISSUE TITLE
Missing session id in Resteasy Reactive

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#20003]
### Describe the bug

We're basically missing two bits when using Resteasy Reactive:
1. Session ID in the requests
2. How to programmatically invalidate sessions

With Resteasy + Undertow, in order to invalidate sessions, we could do something like:

```
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.core.Context;

@Path("/session")
public class SessionResource {
    @PUT
    @Path("/invalidate")
    public void invalidate(final @Context HttpServletRequest req) {
        req.getSession().invalidate();
    }
}
```

And then, we could get the session ID in the HTTP response. Example using Restassured:

```
Response first = app.given().get("/cat/customFindDistinctivePrimitive/2");
String sessionId = first.sessionId();
```

However, with Resteasy Reactive, this is no longer possible:
- The session ID is not generated. (In undertow, it was done [here](https://github.com/quarkusio/quarkus/blob/57177330363224f0c58b1420084139538e6f85aa/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L166))
- To invalidate the session, "javax.servlet" dependency is not part of the Resteasy Reactive dependency, so the class HttpServletRequest is missing. Is there some way to achieve the same?

**Comment by geoand** [comment]
Is this something we want to support?

**Comment by geoand** [comment]
Actually, I am surprised that `javax.servlet.http.HttpServletRequest` is even allowed at the moment.
There is a prototype for supporting Servlets with RESTEasy Reactive, but it's not something we envision will be used widely.

**Comment by stuartwdouglas** [comment]
I don't think we want to support this. In general HTTP sessions are not 'cloud native', as by default they are tied to the node, and distributed sessions are complex.

**Comment by geoand** [comment]
Closing as `won't fix`
