### ISSUE TITLE
Add a reactive ClientHeadersFactory flavor

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#20001]
### Description

Currently, org.eclipse.microprofile.rest.client.ext.ClientHeadersFactory is used to intercept calls and add entries in the client request header.

A very common scenario is to integrate with an api that is secured by a token, that is generated by calling a specific endpoint. The current approach does not support this scenario, because it expects a sync response.

We need to support this use case.

### Implementation ideas

A good way to implement this would be to create something similar to org.jboss.resteasy.reactive.server.ServerRequestFilter.

That is an annotation that supports many kinds of responses. We could create a ClientRequestFilter annotation that would support the client request context in the method parameters and allow returning a Uni, so the request could be updated in an async way.

**Comment by geoand** [comment]
@michalszynkiewicz is this something you are working on (or planning to work on soon) or is it something @Sgitario could look into?

**Comment by michalszynkiewicz** [comment]
I'd be really happy if @Sgitario could take this one :)
