### ISSUE TITLE
CLI commands and sub-commands are listed sort of randomly in help message

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#20017]
### Describe the bug

CLI commands and sub-commands are listed sort of randomly in help message.

For example `extension` and `registry` have add / list / remove sub-commands but they are listed in different order.

Maybe everything should be alphabetically ordered for simplicity or at least the same sub-commands should have the same order in help

```
qss --help
...
Commands:
  create                  Create a new project.
    app                   Create a Quarkus application project.
    cli                   Create a Quarkus command-line project.
    extension             Create a Quarkus extension project
  build                   Build the current project.
  dev                     Run the current project in dev (live coding) mode.
  extension, ext          Configure extensions of an existing project.
    list, ls              List platforms and extensions.
    categories, cat       List extension categories.
    add                   Add extension(s) to this project.
    remove, rm            Remove extension(s) from this project.
  registry                Configure Quarkus registry client
    add                   Add a Quarkus extension registry
    list                  List enabled Quarkus registries
    remove                Remove a Quarkus extension registry
  version                 Display version information.
  completion              bash/zsh completion:  source <(quarkus completion)
```

### Expected behavior

Commands and sub-commands should be alphabetically ordered or at least to have some consistency in ordering for sub-commands with the same name

### Actual behavior

CLI commands and sub-commands are listed sort of randomly in help message

### How to Reproduce?

`qss --help`

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

main

**Comment by ebullient** [comment]
They aren't "random". This is a deliberate order (at the gross level). 

I can see how the difference between list/add/remove for extensions vs. registries would be annoying, but for the rest, there is a deliberate order. I'll make a few adjustments nonetheless.
