### ISSUE TITLE
Support `Multi<Byte>` and `Multi<byte[]>` for octet stream in Rest Client Reactive

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#20024]
### Description

REST Client Reactive should be able to parse binary data to `Multi<Byte>` and/or `Multi<byte[]>` (where one batches of bytes roughly correspond to chunks of HTTP data)

CC @cescoffier

**Comment by geoand** [comment]
@cescoffier @jponge I am pretty sure we could support this by turning `Multi<Byte>` and `Multi<byte[]>` into a Vertx `ReadStream`.

Is there any such converter anywhere?

**Comment by jponge** [comment]
https://github.com/smallrye/smallrye-mutiny-vertx-bindings/blob/main/vertx-mutiny-clients/vertx-mutiny-runtime/src/main/java/io/smallrye/mutiny/vertx/ReadStreamSubscriber.java#L20

**Comment by geoand** [comment]
Oh, that's nice!

**Comment by geoand** [comment]
I'll have a look at this after #39265 is in

**Comment by geoand** [comment]
It makes much sense to support `Multi<io.vertx.mutiny.core.buffer.Buffer>` due to the fact that this is what we can get from the various Vert.x  Mutiny APIs so that is what https://github.com/quarkusio/quarkus/pull/39285 does.
