### ISSUE TITLE
@PathParam does not work with REST Reactive Client when mixed with BeanParam

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#20027]
### Describe the bug

Using the @BeanParam in a Reactive REST client does not appear to work.  @BeanParams work fine in regular REST methods.

```
ERROR: HTTP Request to /ping/my-client failed, error id: 3aac885c-4d1c-4426-b61f-85fe9805c5bf-1
java.lang.IllegalArgumentException: Path parameter not provided client
	at org.jboss.resteasy.reactive.common.jaxrs.UriBuilderImpl.replaceParameter(UriBuilderImpl.java:621)
UriBuilderImpl.java:621
	at org.jboss.resteasy.reactive.common.jaxrs.UriBuilderImpl.buildCharSequence(UriBuilderImpl.java:553)
```

Because I've hit a couple odd ones before due to naming I changed my reproducer to use a generic name just to make sure and I get the same error.

Reproducer attached:
[beanparam.zip](https://github.com/quarkusio/quarkus/files/7136490/beanparam.zip)

### Expected behavior

Using the reactive rest client I can reuse @BeanParams to stay consistent with "outer" resource calls or just as a way to consolidate the arguments consistently.

### Actual behavior

An error is thrown saying the Path parameter was not provided.  Tracing through it "looks" to be there up until the invocation of the method.

Line 29 - InvocationHandler
`Object result = invoker.invoke(requestContext.getEndpointInstance(), requestContext.getParameters());`

Then it throws the exception...

### How to Reproduce?

Running the test will throw exception

### Quarkus version or git rev

2.1.4.Final

**Comment by michalszynkiewicz** [comment]
@kjq passing path params through bean param seemed really weird to me, that's why I didn't implement it.
What's your use case for doing so?

**Comment by kjq** [comment]
Hello Michal.

1. I actually didnt think the MicroProfile REST spec supported it but since
it does I assumed it followed the same conventions as JAX-RS.
2. I use them in my REST resources and wanted to follow the same
conventions with my REST client services for consistency.
3. I have pretty standard base set of header, path and query parameters -
it is a lot nicer to use than having to explode them out and "if" i make a
change or add additional minimizes me hunting and pecking where I need to
refactor as a follow-up.

Thanks for looking into this!

**Comment by michalszynkiewicz** [comment]
Your welcome :)
And thanks for the explanation
