### ISSUE TITLE
RestResponse usability

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#20031]
### Description

I expected to be able to write something like:

```java
    @Path("{id}")
    @GET
    public RestResponse<String> something(int id) {
        if (id % 2 == 0) {
            return RestResponse.ok("good");
        } else {
            return RestResponse.notFound();
        }
    }
```

However I can't because `notFound()` returns `RestResponse<Void>`.

This really limits the usability of `RestResponse`

**Comment by geoand** [comment]
cc @FroMage

**Comment by FroMage** [comment]
Yeah, I noticed this too. I'm not sure how to solve it, but we should.

**Comment by geoand** [comment]
I am not sure either, but this is severely limiting the usability of `RestResponse`

**Comment by stuartwdouglas** [comment]
I have proposed a solution at https://github.com/quarkusio/quarkus/pull/21293
