### ISSUE TITLE
@IfBuildProperty is NOT working as expected in false scenarios

### ISSUE THREAD

**Issue by JithendraKatkam** [quarkusio/quarkus#20030]
### Describe the bug

IfBuildProperty's stringValue is false, getting the exception - unsatisfied dependency exception - 
[1] Unsatisfied dependency for type com.abc.def.MyProperties and qualifiers [@Default]

### Expected behavior

It must ignore the exception (as user is intended to not to load the bean...)in such cases if stringValue is not matching the value in the properties

### Actual behavior

IfBuildProperty's stringValue is false, getting the exception - unsatisfied dependency exception - 
```
[1] Unsatisfied dependency for type com.abc.def.MyProperties and qualifiers [@Default]
        - java member: com.abc.def.Application#MyProperties
        - declared on CLASS bean [types=[io.quarkus.runtime.QuarkusApplication, java.lang.Object, com.abc.def.Application], qualifiers=[@Default, @Any], target=com.abc.def.Application]
```

### How to Reproduce?

Define or create simple application by using Quarkus and spring dependencies 
Application.java
```
@QuarkusMain
public class Application implements QuarkusApplication {
    private static final Logger LOGGER = LoggerFactory.getLogger(Application.class);
    public static void main(String[] args) {
        Quarkus.run(Application.class, args);
    }
    @Inject
    MyProperties myProperties;

    @Override
    public int run(String... args) {
        try {
            if(myProperties != null){
                LOGGER.info("....Test Name : "+myProperties.getTestValue());
            }

```
MyProperties.java 
```
@IfBuildProperty(name = "enable.flag", stringValue = "true")
public class MyProperties {
.
.
```
application.properties
```
enable.flag = false
test.value = TesingSpringAndQuarkus
```

### Output of `uname -a` or `ver`

Darwin C02C98D4LVDLMBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

11.0.12 (Amazon.com Inc. 11.0.12+7-LTS)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

### Additional information

Used the following Quarkus spring dependencies also :
    implementation 'io.quarkus:quarkus-spring-boot-properties'
    implementation 'io.quarkus:quarkus-spring-di'

**Comment by geoand** [comment]
This works exactly as intended.

You either need to have some other (likely `@DefaultBean` annotated) `MyProperties` bean implementation, or use `@Inject Instance<MyProperties>` instead of `@Inject MyProperties` in `Application`
