### ISSUE TITLE
@TestTransaction in combination with Junit5 @Nested does not roll back

### ISSUE THREAD

**Issue by snscaimito** [quarkusio/quarkus#20034]
### Describe the bug

In a `@QuarkusTest` placing `@TestTransaction` on methods inside a Junit5 `@Nested` class does not roll back the transaction - the test data stays in the database. Moving the test method out of the `@Nested class` makes it work.

### Quarkus version or git rev

2.0.2.Final and latest

**Comment by famod** [comment]
@stuartwdouglas @geoand I might be lacking a bit of creativity, but ain't that pretty much a "no-fix"? IIRC, there is no proper way to get a nested instance to be managed by ArC, which is also why `QuarkusTestExtension` is creating nested instances on its own.

**Comment by geoand** [comment]
I haven't looked into it, but that is likely the case.

**Comment by famod** [comment]
@mkouba @manovotn I suppose this
> unless there is some way to make nested classes managed by arc but that does not really seem possible.

is still the case?

**Comment by manovotn** [comment]
Yeah that's still the case. Nested classes are not managed beans as per spec
https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#what_classes_are_beans

**Comment by mkouba** [comment]
Well, _non-static nested classes_ (i.e. inner classes) just to be precise... _static nested classes_ are just fine ;-)

**Comment by knutwannheden** [comment]
As mentioned in the duplicate #29978 it would maybe be possible for the Quarkus runner to raise an error if it detects a CDI interceptor bound annotation on a `@Nested` test class. I think that would be very helpful.

**Comment by manovotn** [comment]
>  if it detects a CDI interceptor bound annotation on a @Nested test class. I think that would be very helpful.

We'd have to scan the detected nested class for annotations on class and all methods and then determine if any of them is an interceptor bindings. On top of that those bindings can be inherited or hidden within hierarchy of stereotypes. And even after all that, the bindings can be in place but there might be no interceptor (bound by same bindings) present in the test deployment hence it isn't really an error.

I don't think we are currently covering this in [testing guides](https://quarkus.io/guides/getting-started-testing) - maybe that would be better first step. We should explicitly state that when using non-static nested classes, CDI functionalities such as interception are not working (with a link to CDI specification for more info OFC). WDYT @mkouba

**Comment by mkouba** [comment]
Hm, I think that we should extend the set of invalid annotation usages detected when `quarkus.arc.detect-wrong-annotations=true` (by default). I.e. detect interceptor bindings declared on inner classes. It would not cover 100% cases but it could be a significant improvement (note that we already detect sopes, producer and observer methods).

**Comment by manovotn** [comment]
> Hm, I think that we should extend the set of invalid annotation usages detected when quarkus.arc.detect-wrong-annotations=true (by default). I.e. detect interceptor bindings declared on inner classes. It would not cover 100% cases but it could be a significant improvement (note that we already detect sopes, producer and observer methods).

Oh, I wasn't aware we do that already. In that case, you're right and we can expand on it.
