### ISSUE TITLE
`@WithKubernetesMockServer` not cleaning up pods on delete

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#20039]
### Describe the bug

When creating pods in the mock server with `mockServer.getClient().pods().create(pod1)`, deleting them at the end of a test with `mockServer.getClient().pods().delete()` does not result in the pods being removed in subsequent tests

### Expected behavior

Calling `mockServer.getClient().pods().delete()` removes all pods from the mocked server

### Actual behavior

`mockServer.getClient().pods()` still returns the pods that were created in a previous test

### Quarkus version or git rev

2.1.3.Final

**Comment by geoand** [comment]
Seems like an upstream issue as we pass do pass the `crud=true` flag to the `io.fabric8.kubernetes.client.server.mock.KubernetesServer`

**Comment by kenfinnigan** [comment]
Ok @geoand, I'll open an upstream issue

**Comment by kenfinnigan** [comment]
See https://github.com/fabric8io/kubernetes-client/issues/3461

**Comment by geoand** [comment]
Great, thanks

**Comment by geoand** [comment]
Closing as the fix was delivered in Kubernetes Client `5.8.0` which is now included in Quarkus
