### ISSUE TITLE
quarkus-oidc doesn't work if jwks endpoint has a different domain (like it's done in AWS Cognito) 

### ISSUE THREAD

**Issue by oleksandr-manko** [quarkusio/quarkus#20045]
### Describe the bug

I tried to use quarkus-oidc with AWS Cognito and It doesn't work 'cause quarkus-oidc assumes that JWKS endpoint ALWAYS should have  the same domain as the authorization server has. It's not always true. For instance, AWS Cognito has different domains for authorization servers and JWKS. In our case We have the following OIDC Configuration in Cognito:
```JSON
{
  "authorization_endpoint": "https://my-test.auth.eu-central-1.amazoncognito.com/oauth2/authorize",
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "issuer": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t12NbxXXX",
  "jwks_uri": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t12NbxXXX/.well-known/jwks.json",
  "response_types_supported": [
    "code",
    "token"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "phone",
    "profile"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint": "https://my-test.auth.eu-central-1.amazoncognito.com/oauth2/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "userinfo_endpoint": "https://my-test.auth.eu-central-1.amazoncognito.com/oauth2/userInfo" 
}
```   
We have `https://cognito-idp.eu-central-1.amazonaws.com` domain for JWKS and `https://my-test.auth.eu-central-1.amazoncognito.com` as auth-server.

We can only specify `quarkus.oidc.auth-server-url` and `quarkus.oidc.jwks-path`. JWKS uri is a result of concatenation of `auth-server-url` and `jwks-path`.

It happens in `io.quarkus.oidc.runtime.OidcRecorder#createOidcClientUni(OidcTenantConfig, TlsConfig, Vertx)` line 271.
```java
  if (!oidcConfig.discoveryEnabled) {
            String tokenUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString, oidcConfig.tokenPath);
            String introspectionUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString,
                    oidcConfig.introspectionPath);
            String authorizationUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString,
                    oidcConfig.authorizationPath);
            String jwksUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString, oidcConfig.jwksPath);
            String userInfoUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString, oidcConfig.userInfoPath);
            String endSessionUri = OidcCommonUtils.getOidcEndpointUrl(authServerUriString, oidcConfig.endSessionPath);
            metadataUni = Uni.createFrom().item(new OidcConfigurationMetadata(tokenUri,
                    introspectionUri, authorizationUri, jwksUri, userInfoUri, endSessionUri,
                    oidcConfig.token.issuer.orElse(null)));
  }
  
  public static String getOidcEndpointUrl(String authServerUrl, Optional<String> endpointPath) {
        return endpointPath.isPresent() ? authServerUrl + prependSlash((String)endpointPath.get()) : null;
  } 
        
```

### Expected behavior

Should be an ability to specify a full URI to JWKS including domain name in properties. 

### Actual behavior

No way to use any domains other then domain of `auth-server-url`

**Comment by GeraldScott** [comment]
Note the three URLs involved in the AWS Cognito implementation of OIDC:
- the OIDC endpoint is `https://cognito-idp.REGION.amazonaws.com/POOL_ID`. This will be the value of `quarkus.oidc.auth-server-url`. Quarkus will append `.well-known/openid-configuration` to the URL to discover the other endpoints
- the authorization_endpoint is `https://POOL_NAME.auth.eu-west-1.amazoncognito.com/oauth2/authorize` 
- JWKS endpoint is `https://cognito-idp.REGION.amazonaws.com/POOL_ID/.well-known/jwks.json`

Verify the OIDC configuration as follows:
```
curl -k https://cognito-idp.REGION.amazonaws.com/POOL_ID/.well-known/openid-configuration
```
