### ISSUE TITLE
Documentation page for micrometer metrics shows wrong quarkiverse extension depedency

### ISSUE THREAD

**Issue by FGRCL** [quarkusio/quarkus#20040]
### Describe the bug

In the quarkus guide titled "MICROMETER METRICS" located here: https://quarkus.io/guides/micrometer, it is shown that to add a quarkiverse extension the following maven dependency must be added:
```xml
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkus-micrometer-registry-stackdriver</artifactId>
</dependency>
```

However, the maven is unable to retrieve this dependency. The maven repository instead shows that the following dependecy should be added:
```xml
<dependency>
    <groupId>io.quarkiverse.micrometer.registry</groupId>
    <artifactId>quarkus-micrometer-registry-stackdriver</artifactId>
</dependency>
```

### Expected behavior

The documentation shows that the dependency to be used is:
```xml
<dependency>
    <groupId>io.quarkiverse.micrometer.registry</groupId>
    <artifactId>quarkus-micrometer-registry-stackdriver</artifactId>
</dependency>
```

### Actual behavior

The documentation shows:
```xml
<dependency>
    <groupId>io.quarkiverse</groupId>
    <artifactId>quarkus-micrometer-registry-stackdriver</artifactId>
</dependency>
```

### How to Reproduce?

1. Open https://quarkus.io/guides/micrometer#using-other-registry-implementations
2. View the displayed dependencies
3. Open https://mvnrepository.com/artifact/io.quarkiverse.micrometer.registry/quarkus-micrometer-registry-stackdriver/2.1.0
4. View the displayed dependency
5. Assert the dependencies differ

### Output of `uname -a` or `ver`

N/A

### Output of `java -version`

16.0.2

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

N/A

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by ebullient** [comment]
oops! You're right. How did I manage that? yikes. Easy to fix.
