### ISSUE TITLE
Enhance healthcheck exclude parameter for reactive datasource

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#20059]
### Describe the bug

Hi,

I have a microservice with a JDBC datasource (elytron-security-jdbc) and several reactive datasources.
First of all, the healthcheck returns DOWN as a global status for reactive datasource even if everything is UP. 
The JDBC shouldn't be part of the Reactive datasource healthcheck one ...
 
Currently the exclude-healthcheck only works for JDBC datasource BUT it has no effect in my case since I also have some reactive datasources.

Im looking for a way to have a coherent healthcheck status. 
Ideally with a clean separation between jdbc and reactive datasources.

### Expected behavior

The healthcheck must provide a clean separation between jdbc and reactive datasource

### Actual behavior

The healthcheck is wrong as you can see: 

```json
{
    "status": "DOWN",
    "checks": [
        {
            "name": "Microservice : mail",
            "status": "UP",
            "data": {
                "Application version": "1.1.3-SNAPSHOT",
                "Quarkus version": "2.1.1.Final"
            }
        },
        {
            "name": "Reactive PostgreSQL connections health check",
            "status": "DOWN",
            "data": {
                "<default>": "up",
                "react": "up"
            }
        },
        {
            "name": "io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy",
            "status": "DOWN",
            "data": {
                "rootCause": "quarkus.datasource.react.jdbc.url has not been defined"
            }
        }
    ]
}
```

"default" is a JDBC and not a Reactive datasource! 

as you can see : 

```properties
# DB connection, needed for authentication
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pwd
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dbuser
quarkus.datasource.jdbc.idle-removal-interval=PT20s
# Security parameters
quarkus.http.auth.basic=true
quarkus.security.jdbc.realm-name=quarkus
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.hash, u.salt, u.iter, u.roles FROM users u WHERE u.login=?
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.salt-index=2
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.iteration-count-index=3
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.hash-encoding=BASE64
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=4
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups

# DB for data
quarkus.datasource.react.db-kind=postgresql
quarkus.datasource.react.username=user2
quarkus.datasource.react.password=pwd
quarkus.datasource.react.reactive.url=postgresql://localhost:5432/dbother
quarkus.datasource.react.reactive.max-size=20
quarkus.datasource.react.reactive.reconnect-attempts=5
quarkus.datasource.react.reactive.reconnect-interval=PT1M
quarkus.datasource.react.reactive.idle-timeout=PT20s
```

### How to Reproduce?

Create a microservice with the smallrye-healthcheck, elytron-security-jdbc and reactive-postgres extension.
Defines some jdbc and some reactive datasources.

try to make a helathcheck

### Output of `uname -a` or `ver`

windows system

### Output of `java -version`

11

### GraalVM version (if different from Java)

NA

### Quarkus version or git rev

2.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.1

**Comment by xstefank** [comment]
@cescoffier ^^

**Comment by cescoffier** [comment]
CC @tsegismont

**Comment by tsegismont** [comment]
@geniusit I can't see an `exclude` parameter in the Quarkus config snippet. Would you mind updating it with what you tried to fix the issue?

**Comment by geniusit** [comment]
@tsegismont 

In order to fix my problem I got this properties file : 

```properties
# DB connection, needed for authentication
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pwd
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dbuser
quarkus.datasource.reactive.url=postgresql://localhost:5432/dbuser
quarkus.datasource.jdbc.idle-removal-interval=PT20s
# Security parameters
quarkus.http.auth.basic=true
quarkus.security.jdbc.realm-name=quarkus
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.hash, u.salt, u.iter, u.roles FROM users u WHERE u.login=?
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.salt-index=2
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.iteration-count-index=3
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.hash-encoding=BASE64
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=4
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups

# DB for data
quarkus.datasource.react.db-kind=postgresql
quarkus.datasource.react.username=user2
quarkus.datasource.react.password=pwd
quarkus.datasource.react.reactive.url=postgresql://localhost:5432/dbother
quarkus.datasource.react.reactive.max-size=20
quarkus.datasource.react.reactive.reconnect-attempts=5
quarkus.datasource.react.reactive.reconnect-interval=PT1M
quarkus.datasource.react.reactive.idle-timeout=PT20s
quarkus.datasource.react.health-exclude=true
```

But as you can see, it's incoherent for reason : 

1 : quarkus.datasource.reactive.url=postgresql://localhost:5432/dbuser

=> this line shouldn't be part of the file since the reactive datasource is specialized (.react.)

2 : quarkus.datasource.react.health-exclude=true

=> if I don't set the reactive datasource as exluded I got this error : 

SRHCK01000: Error processing Health Checks: io.quarkus.runtime.configuration.ConfigurationException: quarkus.datasource.react.jdbc.url has not been defined


The healthcheck should work without excluding anything, just separate jdbc from reactive.

**Comment by tsegismont** [comment]
@geniusit  Can you try adding this to your original config?

```properties
# Disable the default reactive datasource
quarkus.datasource.reactive.enabled=false
# Disable the react JDBC datasource
quarkus.datasource.react.jdbc.enabled=false
```

When you define a datasource, both the JDBC and Reactive parts are prepared unless you explicitly disable them.
That's why, I think, you get a failing `default` reactive datasource and a failing `react` JDBC datasource in your health check.

@jmartisk @cescoffier while looking into this, I noticed that, in #13375, we got a way to exclude a datasource from health-checks. Yet the implementation for reactive databases is missing. I'll work on it.

**Comment by tsegismont** [comment]
@geniusit sorry I made a mistake, actually you need this:

```properties
# Disable the default reactive datasource
quarkus.datasource.reactive.enabled=false
# Disable the react JDBC datasource
quarkus.datasource.react.jdbc.enabled=false
```properties

**Comment by geniusit** [comment]
@tsegismont This is what i was looking for! Thank you very much
