### ISSUE TITLE
@QuarkusIntegrationTest not working with Docker Image when doing security testing on Quarkus 2.2.2

### ISSUE THREAD

**Issue by Lahres-Dev** [quarkusio/quarkus#20053]
### Describe the bug

mvnw clean verify -Pdocker-deploy aborts build process with "[ERROR] WARNING: An illegal reflective access operation has occurred"

I am using quarkus-test-keycloak-server plugin to simulate a Keycloak instance for security testing. Running mvnw clean verify works fine, also mvnw quarkus:dev continuous tests are running successfully.

Reproducer: https://github.com/Lahres-Dev/quarkus-issue-1
quarkus.container-image.group and quarkus.container-image.registry need to be filled, as I'm using a private registry for my docker images. Also change quarkus.platform.version to 2.2.2.Final

### Expected behavior

mvnw clean verify -Pdocker-deploy runs successfully

### Actual behavior

mvnw clean verify -Pdocker-deploy no successful run

### How to Reproduce?

1. clone reproducer https://github.com/Lahres-Dev/quarkus-issue-1
2. hange quarkus.platform.version to 2.2.2.Final
3. run mvnw clean verify -Pdocker-deploy

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19043 XXX 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 LTS OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS) OpenJDK Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode, emulated-client)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\XXX.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.11, vendor: Amazon.com Inc., runtime: C:\copybase\jdk11.0.11_9 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"

### Additional information

Follow up from #19116

Console output on 2.2.2
[INFO] Running com.github.lahresdev.HelloServiceTestIT
Pulling container image XXX:1.0.0-SNAPSHOT'
Executing [docker, run, --rm, -p, 8081:8081, -p, 8444:8444, --env, QUARKUS_HTTP_PORT=8081, --env, QUARKUS_HTTP_SSL_PORT=8444, --env, TEST_URL=http://localhost:8081, --env, KEYCLOAK_URL=http://localhost:55047/auth, XXX:1.0.0-SNAPSHOT]
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/C:/Users/XXX/.m2/repository/org/codehaus/groovy/groovy/3.0.8/groovy-3.0.8.jar) to constructor java.lang.AssertionError(java.lang.St
ring)
[ERROR] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release

**Comment by geoand** [comment]
I just tried this and it worked properly.

**Comment by Lahres-Dev** [comment]
Oh, no. Then there's a problem on my side.

**Comment by sberyozkin** [comment]
@Lahres-Dev Hi, not sure what can be the cause of this reflection access op issue, hard to see how it being a Quarkus problem, may Georgios, @geoand, have you seen such errors before ?

@Lahres-Dev By the way, we now recommends running the integration tests against Keycloak using Dev Services for Keycloak, please see https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/security-openid-connect.adoc#dev-services-for-keycloak

**Comment by geoand** [comment]
I would assume that `--illegal-access=deny` is being set somewhere

**Comment by sberyozkin** [comment]
@geoand thanks for testing it :-)

**Comment by Lahres-Dev** [comment]
@sberyozkin I tried to follow the documentation, but there doesn't seem to be a utility class
`io.quarkus.test.keycloak.client.KeycloakTestClient` in that dependency

````
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-test-keycloak-server</artifactId>
    <scope>test</scope>
</dependency>
````
![image](https://user-images.githubusercontent.com/58905132/132835191-0440801e-e767-487e-82f7-0a16d2701df1.png)

Is this maybe in Version 2.3?

@geoand @sberyozkin Thanks for your help. I look further into it.
