### ISSUE TITLE
failed compiling getting-started

### ISSUE THREAD

**Issue by andreaneri** [quarkusio/quarkus#2006]
Hello,
i'm just clonin:
git clone https://github.com/quarkusio/quarkus-quickstarts.git

and run:
./mvnw compile quarkus:dev:
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.acme:quarkus-quickstart >---------------------
[INFO] Building quarkus-quickstart 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quarkus-quickstart ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:0.13.0:dev (default-cli) @ quarkus-quickstart ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.111 s
[INFO] Finished at: 2019-04-11T14:53:23+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.0:dev (default-cli) on project quarkus-quickstart: Failed to run: Failed to resolve Quarkus application model: Failed to locate current project among the loaded local projects -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

i'm on mac:
Darwin Macintosh.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

could you help me ?
thanks,

Andrea

**Comment by cescoffier** [comment]
Can you try with 0.13.1?

**Comment by andreaneri** [comment]
@cescoffier i just updated this line in pom.xml:
<quarkus.version>0.13.1</quarkus.version>

but i get:
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.1:dev (default-cli) on project quarkus-quickstart: Failed to run: Failed to resolve Quarkus application model: Failed to locate current project among the loaded local projects -> [Help 1]

**Comment by gsmet** [comment]
ˋquarkus:dev` won’t work in the parent directory of all the quick starts. You need to be in a specific QuickStart.

**Comment by andreaneri** [comment]
@gsmet i'm here:
pwd
/Users/Andrea/Projects/quarkus-quickstarts/getting-started

 ls -ltr
total 72
-rw-r--r--  1 tinan291  staff   453  8 Apr 21:26 build.gradle
-rwxr-xr-x  1 tinan291  staff  9892  8 Apr 21:26 mvnw
-rwxr-xr-x  1 tinan291  staff  6301  8 Apr 21:26 mvnw.cmd
-rw-r--r--  1 tinan291  staff   321  8 Apr 21:26 settings.gradle
drwxr-xr-x  4 tinan291  staff   128  8 Apr 21:26 src
-rw-r--r--  1 tinan291  staff  4358 11 Apr 17:36 pom.xml
drwxr-xr-x  5 tinan291  staff   160 11 Apr 17:38 target

**Comment by andreaneri** [comment]
@cescoffier @gsmet any idea ? what have i wrong ?

**Comment by gsmet** [comment]
@andreaneri sorry for the delay. I tried to do what you did with the current master of the quickstarts and it seems to work.

We had several bootstrap issues in 0.13.0 so maybe it could be one of them. Can you try with the current master of quickstarts? It should use 0.13.3 now, which received several bugfixes that could be related to your issue.

**Comment by andreaneri** [comment]
@gsmet thank sir, i updated ../quarkus-quickstarts/getting-started/pom.xml:
<quarkus.version>0.13.3</quarkus.version>

i got the same error:
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.3:dev (default-cli) on project quarkus-quickstart: Failed to run: Failed to resolve Quarkus application model: Failed to locate current project among the loaded local projects -> [Help 1]

thanks

**Comment by aloubyansky** [comment]
@andreaneri if 0.14.0 still doesn't work for you for some reason, 0.15.0 is definitely going to work :) If you have a chance to try the current master branch, please do. That error does not exist any more.

**Comment by andreaneri** [comment]
@aloubyansky 0.14.0 it work, thanks

**Comment by andreaneri** [comment]
@aloubyansky 0.14.0 it work, thanks

**Comment by gsmet** [comment]
Ah cool, thanks for confirming. Closing, then.
