### ISSUE TITLE
Kubernetes extension doesn't generate labels for `RoleBinding` resources

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#20065]
### Describe the bug

See title

### Expected behavior

Labels should be generated.

### Actual behavior

No labels are generated.

### Quarkus version or git rev

2.2.2.Final

**Comment by iocanel** [comment]
It seems that we are adding labels to all resources that have a specific name.
Since rolebindings are using a suffix, the are excluded. 

I'll fix  that shortly.
