### ISSUE TITLE
`quarkus.log.min-level` doesn't overwrite `quarkus.log.level`

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#20066]
### Describe the bug

According to the Doc:

There are two logging level settings: logging level and minimum logging level. The default logging level is INFO, the default minimum logging level is DEBUG. You can adjust both either globally, using the quarkus.log.level and quarkus.log.min-level property, or by category.

When you set the logging level below the minimum logging level, you must adjust the minimum logging level as well. Otherwise, **the value of minimum logging level overrides the logging level.**

However, If I set `quarkus.log.min-level` to `FATAL`, I am still logging `INFO` traces. 

Expected behavior: 
For a given application with the following traces:
```
        LOG.fatal("Fatal log example");
        LOG.error("Error log example");
        LOG.warn("Warn log example");
        LOG.info("Info log example");
        LOG.debug("Debug log example");
        LOG.trace("Trace log example");
```
And the configuration:
```
quarkus.log.min-level=DEBUG
quarkus.log.level=TRACE
```
I will expect to see the following traces: 
```
Fatal log example
Error log example
Warn log example
Info log example
Debug log example
```
Because of this Doc ref: `When you set the logging level below the minimum logging level, you must adjust the minimum logging level as well. Otherwise, **the value of minimum logging level overrides the logging level.**`

But I got these traces:

```
Fatal log example
Error log example
Warn log example
Info log example
Debug log example
Trace log example
```
Quarkus Version: upstream

Reproducer: https://github.com/pjgg/quarkus-test-suite/blob/feat/logMinLevel/logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/LogResourceIT.java#L78

Test cmd: `mvn clean verify -pl logging/jboss`

**Comment by galderz** [comment]
This could be a bug in the original feature when handling `quarkus.log.level` specifically. If you use a category, then this works. E.g.

```
quarkus.log.category."io.quarkus.ts.logging.jboss".level=TRACE
```

**Comment by galderz** [comment]
PR sent: https://github.com/quarkusio/quarkus/pull/20373
