### ISSUE TITLE
@IfBuildProperty needs to allow multiple property names 

### ISSUE THREAD

**Issue by JithendraKatkam** [quarkusio/quarkus#20099]
### Description

@IfBuildProperty does not allow multiple property names to be checked on the optional beans- similar to spring - @ConditionalOnProperty

- 

### Implementation ideas

Should able to declare like the below - 

`@IfBuildProperty( { name = "kafka.test.flag1", stringValue = "true"},
{ name = "kafka.test.flag2", stringValue = "false"},
{ name = "kafka.test.flag3", stringValue = "true"})` 
All value checks are OR based - (can be considered AND based - depending on the implementation - and easiness of usage.)  

In the AND case (Can be considered OR - depending on the implementation - and easiness of usage)-> defining multiple times the same annotation -
```
@IfBuildProperty( name = "kafka.test.flag1", stringValue = "true")
@IfBuildProperty( name = "kafka.test.flag2", stringValue = "false")
@IfBuildProperty( name = "kafka.test.flag3", stringValue = "false")
```
please check if this is feasible.

**Comment by mkouba** [comment]
It probably make sense to support repeatable `@IfBuildProperty` and `@UnlessBuildProperty` annotations. And the logic should be AND-like, i.e. all declared "conditions" must be satisifed. @geoand WDYT?

**Comment by geoand** [comment]
Yeah, that sounds most reasonable to me.

**Comment by JithendraKatkam** [comment]
Yes, that works.

**Comment by geoand** [comment]
@mkouba are you going to take this, or should I?

**Comment by mkouba** [comment]
> @mkouba are you going to take this, or should I?

I can take a look tomorrow. So if you have some spare cycles now, go and grab it! ;-)

**Comment by geoand** [comment]
If you don't take it tomorrow, then I will. I'm looking at something else for now :)
