### ISSUE TITLE
Maven Build fails if DB Configuration is missing in default file or test

### ISSUE THREAD

**Issue by psaraf** [quarkusio/quarkus#20109]
### Describe the bug

if DB Configuration is  missing from  default properties or test.properties. Most of application run build with mocking db connection and missing DB details should not cause build fail. 

### Expected behavior

build should be successful

### Actual behavior

Build is Failed 

### How to Reproduce?

Create project from start coding at quarkus.com
add hibernate, rest and postgress dependency. 
Remove docker and native test
run mvn clean package

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
Can you provide more info about what the exact failure is? Also, which extensions are you using and what does `application.properties` look like?

**Comment by geoand** [comment]
Closing as we never got feedback
