### ISSUE TITLE
Add the ability to set HTTP headers and Response status when returning Reactive Types from RESTEasy Reactive

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#20100]
### Description

Currently when returning a `Uni` or `Multi`, there is no easy way to set a response header or a  the HTTP status.
We should provide and document a way to do this.

### Implementation ideas

There are two ways I can think of:

1) We introduce `@Header` and `@Status` annotations that can be placed on a resource method and if the method was executed properly, these annotations set the corresponding response properties.
2) We allow the use of `RestResponse<Uni<T>>` and `RestResponse<Multi<T>>`. This would allow more control, but might be more cumbersome to use.

WDYT @FroMage @stuartwdouglas ?

**Comment by ambition-consulting** [comment]
Hate to be pushing again - but yes, we definitely need this. Not sure if we are the first enterprise application using reactive server+client with quarkus, but this stuff is fundamental!

**Comment by geoand** [comment]
We'll likely add this soon.

**Comment by FroMage** [comment]
Can't we return a `Uni<RestResponse<>>` ATM? The docs say we can from filters and exception mappers, so I assume we can from endpoints too.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20311 is what I had in mind

**Comment by geoand** [comment]
Yes it is. Feel free to comment about that on the Pull Request
