### ISSUE TITLE
@Nested JUnit test doesn't inherit lifecycle of @QuarkusTest

### ISSUE THREAD

**Issue by Foobartender** [quarkusio/quarkus#20114]
### Describe the bug

`@Nested` test of a test annotated with `@QuarkusTest` and `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` is run with a new instance of its outer test.

### How to Reproduce?

1. Run the test below. It passes.
2. Annotate it with @QuarkusTest and run it again. The outer test passes, but the nested test fails.

```kotlin
// @QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation::class)
class TestLifecycle {
 var s: String? = null

 @Test
 @Order(1)
 fun setString() {
  s = "foo"
 }

 @Test
 @Order(2)
 fun testString() {
  assertEquals("foo", s)
 }


 @Nested
 inner class NestedTest {
  @Test
  fun testString() {
   assertEquals("foo", s)
  }
 }
}
```

Edit: same test in Java, makes no difference.

```java
// @QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class TestLifecycleJ {
 private String s;


 @Test
 @Order(1)
 public void setString() {
  s="foo";
 }


 @Test
 @Order(2)
 public void testString() {
  assertEquals("foo", s);
 }


 @Nested
 public class NestedTest {
  @Test
  public void testString() {
   assertEquals("foo", s);
  }
 }
}
```

### Output of `uname -a` or `ver`

Linux ***** 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

21.2.0

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by Sgitario** [comment]
@geoand I've just realized this issue is also fixed as part of https://github.com/quarkusio/quarkus/pull/24172

**Comment by geoand** [comment]
Cool
