### ISSUE TITLE
CurrentVertxRequest is not set for coroutine routes

### ISSUE THREAD

**Issue by clay07g** [quarkusio/quarkus#20121]
### Describe the bug

Using RestEasy Reactive, you can easily get the current request by injecting an instance of "RoutingContext" and then calling ".request()" on it in your routing methods.

However, this doesn't work for suspending functions with Kotlin. It seems like the CurrentVertxRequest isn't set when Quarkus uses the coroutine dispatcher, perhaps similar to this: https://github.com/quarkusio/quarkus/pull/13371

The error I get is:
```
javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
```

Here is some actual code:
```
@Path("/test")
class TestApi {
    @Inject
    lateinit var ctx: RoutingContext

    @GET
    @Path("/coroutine")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun test(): String {
        println(ctx.request().headers()) // Error
        return "hello"
    }

    @GET
    @Path("/normal")
    @Produces(MediaType.TEXT_PLAIN)
    fun test2(): String {
        println(ctx.request().headers()) // Works!
        return "hello"
    }
}
```

### Expected behavior

No error is thrown when accessing the current request from a coroutine route.

### Actual behavior

An error is thrown when accessing the current request from a coroutine route.

### How to Reproduce?

See description

### Output of `java -version`

AdoptOpenJdk 11

### Quarkus version or git rev

2.2.0 final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 6.8.3 ------------------------------------------------------------  Build time:   2021-02-22 16:13:28 UTC Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78  Kotlin:       1.4.20 Groovy:       2.5.12 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          16.0.1 (Oracle Corporation 16.0.1+9-24) OS:           Windows 10 10.0 amd64

**Comment by geoand** [comment]
FWIW, you can do something like:

```java
@Path("/test")
class TestApi {
    @Inject
    lateinit var ctx: RoutingContext

    @GET
    @Path("/coroutine")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun test(headers: HttpHeaders): String {
        println(headers)
        return "hello"
    }
}
```

to get around the problem.

**Comment by geoand** [comment]
This was actually fixed by https://github.com/quarkusio/quarkus/pull/21328
