### ISSUE TITLE
Inconsistency in mongodb-client integration tests

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#20139]
### Description

While checking for Mongo test coverage, we noticed an inconsistency introduced by https://github.com/quarkusio/quarkus/pull/12902.

Originally, there were two tests in `integration-tests/mongodb-client/src/test/java/io/quarkus/it/mongodb/BookResourceTest.java` which were removed:
- `testVehicleEndpoint` (https://github.com/quarkusio/quarkus/pull/12902/files#diff-adad68742f7dc851850e5b594177697da7a5313144b74da9ca4dccfe19e5aeeaL135)
- `testPojoEndpoint` (https://github.com/quarkusio/quarkus/pull/12902/files#diff-adad68742f7dc851850e5b594177697da7a5313144b74da9ca4dccfe19e5aeeaL155)

Their respective endpoints, however, were kept intact:
- `integration-tests/mongodb-client/src/main/java/io/quarkus/it/mongodb/discriminator/VehicleResource.java`
- `integration-tests/mongodb-client/src/main/java/io/quarkus/it/mongodb/pojo/PojoResource.java`

What was the reason for the removal?
Would it be possible to either add the tests back, or remove the related enpoints?

**Comment by loicmathieu** [comment]
@jsmrcka nice catch! This should have been a merge issue, those two tests can be re-integrated.
Would you mind sending a PR ?

**Comment by jsmrcka** [comment]
@loicmathieu Sure thing, I'll make it ready.

**Comment by loicmathieu** [comment]
Thanks
