### ISSUE TITLE
Kotlin suspend endpoint throws NotSupportedException

### ISSUE THREAD

**Issue by hex1r0** [quarkusio/quarkus#20132]
### Describe the bug

It seems that kotlin.coroutines.Continuation is considered as one of the endpoint's parameters. it should not be assumed as a endpoint parameter and should be handled under the hood.

### Expected behavior

Tests should pass
HTTP STATUS 200 OK

### Actual behavior

HTTP ERROR 415

APPLICATION LOG: 

2021-09-14 11:21:59,590 ERROR [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002010: Failed to execute: javax.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: interface kotlin.coroutines.Continuation<? super java.lang.String> of content type: */*

### How to Reproduce?

1. Generate an empty kotlin quarkus project
2. In GreetingResource change `fun hello() = "Hello RESTEasy"` to `suspend fun hello() = "Hello RESTEasy"`
3. Run ./mvnw clean test
4. Observe test failure
5. You can also observe same behaviour by launching project and testing using browser.

### Output of `uname -a` or `ver`

Darwin hex1r0 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment (build 11.0.10+9) OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

### GraalVM version (if different from Java)

No Graal

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/hex1r0/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.10, vendor: Oracle Corporation, runtime: /usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "11.5.2", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Kotlin corroutines only work with RESTEasy Reactive - they are not supported by RESTEasy Classic.
