### ISSUE TITLE
hibernate not loading default schema

### ISSUE THREAD

**Issue by psaraf** [quarkusio/quarkus#20145]
### Describe the bug

we have different postgresql schema for each of environment, and each of those are defined into respective properties file under 
dev properties file

```
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = dev_rw
quarkus.datasource.password = xxxxx
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/test
quarkus.hibernate-orm.database.default-schema=test_dev
quarkus.hibernate-orm.log.sql=true
```
```
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = qa_rw
quarkus.datasource.password = xxxxx
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/test
quarkus.hibernate-orm.database.default-schema=test_qa
quarkus.hibernate-orm.log.sql=true
qa properties
```
we are setting using OS environment variable QUARKUS_PROFILE
All the properties of application are loading correct for each of environment except default schema

the default is getting populated whatever is set for compile time profile, if no profile is set then value from application.properties is taken, in this case value is not define and no schema is take. with exception `relation "testtable" does not exist`.
if profile is set at built time application then respective only that schema is taken 
e.g if build set to dev then all environment try to execute query as 

```
    select
        testtable0_.id as id1_0_,
        testtable0_.create_time as create_t2_0_,
        testtable0_.testtable_cd as testtable3_0_,
        testtable0_.testtable_desc as legalent4_0_,
        testtable0_.testtable_type as legalent5_0_,
        testtable0_.update_time as update_t6_0_
    from
        test_dev.testtable testtable0_
```

### Expected behavior

hibernate should connect with  quarkus.hibernate-orm.database.default-schema defined in each of profile properties

### Actual behavior

either default property value get embedded into code. rest profile ignored.

### How to Reproduce?

Create JPA project
create local postgres db with two schema dev and qa
use each schema on one profile. No schema in default application.properties. so dev application-dev.properties profile has dev schema, qa application-qa.properties has qa schema
build application using mvn clean package
set the  QUARKUS_PROFILE=dev then qa
run the jar file generated.

### Output of `java -version`

java 11

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by yrodiere** [comment]
Thanks for the report.
This duplicates #19660. Closing.
