### ISSUE TITLE
Reactive Messaging should generate ConfigDescriptionBuildItem

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#20158]
### Description

Currently the config editor does not display `mp.messaging` properties. By looking at the annotations in the application we could generate `ConfigDescriptionBuildItem` instances for each incoming/outgoing channel, to allow the user to easily wire them up in the config editor of the Dev UI.

e.g. if you have an `@Incoming("prices")` we should generate a build item for `mp.messaging.incoming.prices.connector`, as well as any other properties that reactive messaging know about.

**Comment by stuartwdouglas** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
The list cannot be exhaustive as part of the configuration depends on how the channel and underlying client is configured. However we can at least create a description based on our @ConnectorAttribute which would cover 80-90% of the cases.

**Comment by cescoffier** [comment]
Actually, to detect the configurable channel, we will have to run the graph traversal (wiring) during Quarkus build. It will require qui some change in reactive messaging to allows this, as the traversal could happen with some work but need to be decoupled from the materialization.

**Comment by stuartwdouglas** [comment]
I don't know if this needs to be exhaustive. Even if we just listed the simple properties it would be better than nothing.

**Comment by cescoffier** [comment]
Yes, we just need a good way to run the wiring algorithm at build time, as this is the only thing that can tell you which channel could be managed by connectors. I need to think about that. That should not be hard, the only runtime part is the connector registry but that can be changed.
