### ISSUE TITLE
SROAP04005: Could not find schema class in index: java.lang.Void when using rest-client-reactive with Uni<Void>

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#20152]
### Describe the bug

When using rest-client-reactive that uses following method on the interface

````
    @POST
    @Path("/name/{countryName}")
    Uni<Void> createCountry(String countryName);
````

with OpenAPI extension in the project, following warning is logged

````
SROAP04005: Could not find schema class in index: java.lang.Void
````

### Expected behavior

No warning is logged

### Actual behavior

Logged warning `SROAP04005: Could not find schema class in index: java.lang.Void`

### How to Reproduce?

It can be reproduced with `rest-client-reactive-quickstart`

1. add following method to `org.acme.rest.client.CountriesService`
2. add open api extension to pom.xml
3. run the project in dev mode

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven-3.6.3

**Comment by michalszynkiewicz** [comment]
@mswiderski thanks for the report :) 
Do I understand correctly that it works okay without openapi and causes an error if openapi is added?

**Comment by mswiderski** [comment]
in general it all works but it logs the warning, only when the open api is added

**Comment by michalszynkiewicz** [comment]
CC @phillip-kruger

**Comment by phillip-kruger** [comment]
This seems like a but, we probably do not treat `Void` in Uni as `void` . This will need to be fixed in SmallRye. @mswiderski would you open an issue there ?

**Comment by mswiderski** [comment]
@phillip-kruger issue created https://github.com/smallrye/smallrye-open-api/issues/914

**Comment by geoand** [comment]
@phillip-kruger any chance we will get a new version of the Openapi dependency before next week so we can include it in `2.3.0.Final`?

**Comment by phillip-kruger** [comment]
For sure ! I'll release later today

**Comment by geoand** [comment]
Great, thanks!
