### ISSUE TITLE
Gradle - quarkusDependency runs for all submodules when attempting to build one

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#20153]
### Describe the bug

In a monorepo with multiple subprojects, any build will cause `quarkusDependency` and `quarkusDependencyCopy` tasks to always run for all subprojects. This is particularly concerning in a 30 project monorepo when trying to build a single project (i.e. `./gradlew project:build`), which takes 3-4 minutes on every build.

### Expected behavior

The `quarkusDependency` and `quarkusDependencyCopy`  taks should only run for the individual project and any project dependencies.

### Actual behavior

All subprojects run `quarkusDependency` and `quarkusDependencyCopy`  always.

### How to Reproduce?

1. Create a multiproject repository
2. Run a single project: `./gradlew project:build`

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.2.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

**Comment by glefloch** [comment]
Hi @mweber03 this will be fix in #20112
