### ISSUE TITLE
Error in "Building native image guide"

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkus#2015]
With reference to https://quarkus.io/guides/building-native-image-guide.html it states "In addition to the regular files, the build also produces target/quarkus-quickstart-runner. You can run it using: ./target/quarkus-quickstart-runner."

Yet after using ./mvnw package -Pnative on the original example, there was no quarkus-quickstart-runner in the target directory.

**Comment by gsmet** [comment]
It should be fixed by:
 * https://github.com/quarkusio/quarkus/pull/2076
 * https://github.com/quarkusio/quarkus-quickstarts/pull/155

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/2076. Closing.
