### ISSUE TITLE
ConstrainValidator is wrongly cached 

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#20169]
### Describe the bug

When using a ConstraintValidator in Quarkus, its "initialize" method is called as often as the Validator is applied in the project, but on the same cached instance.

In our case we want to use a Validator for a date-interval and the rules applied by the validator need to be different for certain cases (e.g. in one case the interval is allowed to be open, so a null value in the second field, but in another case/field it is not)

The problem is, that Quarkus only ever creates one instance of the validator, but initiliazes it twice (or more, depending on how many usages of the annotation occurs). The following is a example to ilustrate.

```
@Entity
public class MyEntityA {
  
  @Embedded
  @MyConstraint(allowed = true) 
  @AttributeOverride....
  private EmbeddableType fu
}

@Entity
public class MyEntityB {
  
  @Embedded
  @MyConstraint(allowed = false) 
  @AttributeOverride....
  private EmbeddableType  bar
}

@Target({FIELD})
@Retention(RUNTIME)
@Constraint(validatedBy = {MyValidator.class})
public @interface MyConstraint {
  boolean allowed() default false;

  String message() default "DISBALED BY VALIDATOR";
  Class<?>[] groups() default {};
  Class<? extends Payload>[] payload() default {};
}

public class MyValidator implements ConstraintValidator<MyConstraint, EmbeddableType> {

  private boolean isAllowed;

  @Override
  public void initialize(MyConstraint constraintAnnotation) {
    // this is called on the same instance as often as the annotation is applied in the project
	// but with a different constraintAnnotation-instance
	this.isAllowed = constraintAnnotation.allowed();
  }

  @Override
  public boolean isValid(EmbeddableType value, ConstraintValidatorContext constraintValidatorContext) {
    if (value == null) {
      return true;
    }

    constraintValidatorContext.disableDefaultConstraintViolation();

    boolean result = true;
    if (!isAllowed && value.getSome() == null) {
      constraintValidatorContext
          .buildConstraintViolationWithTemplate("Try again")
          .addConstraintViolation();
      result = false;
    }

    return result;
  }
}
```

Depending on `@MyConstraint(allowed = true/false)` the validation behaviour changes. Since Quarkus is using the same instance and initializes it twice before calling `isValid` the validators state is overwritten and only once validation is correct. This depends on the bytecode, which field is processed first. Sometime fu, sometimes bar.

### Expected behavior

A validator instance is cached per field and reused among concurrent requests but not one instance for all.
Teh behaviour should be identical to `@Size(min=2)` where each occurence might be configured different

### Actual behavior

When debugging the initialize method, it is clear that the MyValidator instance is always the same, but for each usage of MyConstraint the configured instanced is passed, thus overwriting the configured state in the validator.

Removing MyConstraint  from MyEntityB hides this problem, but ist is still there. 
The same multiple initialization happens on other validators as well, but it did not produce flaky behaviour because no state was involved which could be overriden.

According to BeanVal 2.0 Spec

> The lifecycle of a constraint validation implementation instance is undefined. Jakarta Bean Validation providers are allowed to cache ConstraintValidator instances retrieved from the ConstraintValidatorFactory.

But the documentation states that only `isValid `must be thread-safe and `initialize` is called before. It doesnt make any sense to call initialize multiple times on the same instance, hence I assume that the spec refers to caching per field-application so that not each request creates a new instance.

### Output of `java -version`

11

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.1

### Additional information

It could still be a progamming mistake, but as far as I understood the BeanVal spec our use-case should be ok. Feeld free to correct.

**Comment by famod** [comment]
Have you tried adding `@Dependent` to `MyValidator`?

**Comment by lostiniceland** [comment]
> 
> 
> Have you tried adding `@Dependent` to `MyValidator`?

Indeed, adding `@Dependent` did solve the issue. I wonder why? Isn't this the default-scope? If so, should this be fixed in Quarkus.

**Comment by famod** [comment]
It's `@Singleton` by default since #11598, which is not the best choice IMO.

We might want to try being clever by checking whether the `ConstraintValidator` implements `initialize()`.
If not, `@Singleton` might be a nice optimization. If yes, then obviously `@Depenent` is required.
If we cannot safely determine that we have to resort to `@Dependent`.

And the docs should mention this as well (whatever we choose to implement).

/cc @gsmet (who might be still on PTO)

PS: Might actually take a stab at this myself later this week, but no promise.

**Comment by famod** [comment]
It might actually be a bit different than I first thought: Your validator is not using any injections, so it's probably not getting the singleton scope at all. See `requiresContainerServices()` here: https://github.com/quarkusio/quarkus/blob/2.2.3.Final/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L162

So for your specific case it's probably some Hibernate Validator thing.

Still, `@Singleton` is not the best choice von validators that use injections.

**Comment by famod** [comment]
@loicmathieu can you share a small reproducer project? That would speed things up!

**Comment by lostiniceland** [comment]
@famod Sorry for the late reply. Yes, I will create a sample app.

**Comment by lostiniceland** [comment]
For whatever reason, I am currently not able to reproduce the issue with the hibernate-orm-quickstart sample. Though I can on my project. I will see if I can push the sample to failure, but I cannot spent to much time on this.

**Comment by famod** [comment]
@lostiniceland friendly reminder! 🙂

**Comment by gsmet** [comment]
Yes, maybe we should change the default scope to `@Dependent`.

**Comment by lostiniceland** [comment]
Cant reproduce anymore

**Comment by famod** [comment]
@lostiniceland thanks for replying!

@gsmet 
> Yes, maybe we should change the default scope to `@Dependent`.

Would be safer. Or implement the smarter approach (`@Dependent` XOR `@Singleton`).
Are you going to take a stab at that? If not I can put it on my (long) list.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/22739
