### ISSUE TITLE
java.lang.UnsatisfiedLinkError: ..ECKeyPairGenerator.generateECKeyPair

### ISSUE THREAD

**Issue by Dudelilama** [quarkusio/quarkus#2016]
When running a generated bin containing a jdbc connection to postgres (azure) in a docker container, we get a missing lib warning:

WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.

And it crashes on DB Access with:
 Caused by: java.lang.UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.generateECKeyPair(I[B[B)[Ljava/lang/Object; [symbol: Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair or Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair__I_3B_3B]

Everything is working on local machine.

**Comment by gsmet** [comment]
@Dudelilama 

Two options here:
- If you don't connect to PostgreSQL using SSL, you can simply add `quarkus.ssl.native=false` to your `application.properties`.
- if you do, see the SSL guide here: https://quarkus.io/guides/native-and-ssl-guide - especially the `The SunEC library and friends` paragraph. You will need to include the SunEC library and the cacerts file into the Docker container and pass system properties to your application.

Feel free to ask for more information if you can't get it working. We will improve the guide if needed.

**Comment by Dudelilama** [comment]
Hi @gsmet 

Thanks a lot for pointing me out the guide! I'll try the bundling part and let you know, whether it worked propperly :).

Kind Regards

**Comment by ruromero** [comment]
@gsmet I face this issue when building a native docker image. I need SSL to work to connect to the k8s client using the sslCaCert.
Shall I include the whole library and the cacerts?

**Comment by gsmet** [comment]
@ruromero yes, you will need both.
