### ISSUE TITLE
RestEasy SPI HttpRequest injection in ContainerRequestFilter fails silently in native image

### ISSUE THREAD

**Issue by jayv** [quarkusio/quarkus#20161]
### Describe the bug

We followed the documentation here ( https://quarkus.io/guides/rest-json#servlet-compatibility ) to obstain the remote address in a JAX-RS app from a `ContainerRequestFilter`. It certainly works in dev mode, but it doesn't inject in the same project compiled to native image. The `request` property is never injected (remains `null`). There isn't any failure logged about it either, it just doesn't get set for some reason.

### How to Reproduce?

```kt
@Provider
@PreMatching
class AuthenticationInterceptor : ContainerRequestFilter {

    // Need to inject the RestEasy SPI HttpRequest to get remote address
    // https://quarkus.io/guides/rest-json#servlet-compatibility
    @Context
    var request: org.jboss.resteasy.spi.HttpRequest? = null

}
```

### Output of `uname -a` or `ver`

quay.io/quarkus/centos-quarkus-maven:21.0-java11

### Output of `java -version`

quay.io/quarkus/centos-quarkus-maven:21.0-java11

### GraalVM version (if different from Java)

quay.io/quarkus/centos-quarkus-maven:21.0-java11

### Quarkus version or git rev

1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.2

**Comment by geoand** [comment]
I tried this (in Java) with Quarkus `1.13.7.Final` and the latest version and they both worked.

Perhaps you need to make the field `lateinit var`?

**Comment by jayv** [comment]
I actually tried a bunch of variations of that field, including lateinit, added setters with the annotation, made the field and class open, …. I guess I can try making it a java class instead, not the end of the world. Just a bit curious that injection anywhere else works fine in both dev/native.

Just to be sure, you did try this natively compiled? Cause it does work for me in dev mode.

**Comment by geoand** [comment]
Oh sorry, my bad.

I didn't try in native mode, so let me reopen

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20206 fixes the issue

**Comment by jayv** [comment]
Thanks for the quick turnaround!

**Comment by geoand** [comment]
YW
