### ISSUE TITLE
Only the first @Gauge annotation is scanned on a class when using MPMetrics and Micrometer

### ISSUE THREAD

**Issue by smolloy** [quarkusio/quarkus#20184]
https://github.com/quarkusio/quarkus/blob/09b25988d58ef3927c9a3d652a47f32e16265457/extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/mpmetrics/GaugeAnnotationHandler.java#L50

Because of (I think) the line referenced above, only the FIRST @Gauge annotation is actually captured.  This is due to the "name" not including the method info, as several methods can have a Gauge annotation.  I can confirm this happens as this bug is what led me to read this section of source code and occurs on our code when switching from smallrye metrics to micrometer.

**Comment by ebullient** [comment]
This sounds about right. I don't recommend using annotations for things like Gauges (though I understand the practice was common because of how the MP spec was written). Oversight on my part. Will rectify.
