### ISSUE TITLE
Support  io.vertx.mutiny.ext.web.Router through @Observes CDI event

### ISSUE THREAD

**Issue by murphye** [quarkusio/quarkus#20185]
### Description

I cannot implement `void init(@Observes io.vertx.mutiny.ext.web.Router router)` as only `io.vertx.ext.web.Router` seems to be supported. When I need the Mutiny Router, it forces me to do `Router.newInstance(router)` to convert the regular `Router` to a Mutiny `Router`.

When using libraries such as `smallrye-mutiny-vertx-web-openapi` this becomes an annoyance, as the Mutiny variant of the `Router` may be needed. 

@cescoffier

**Comment by murphye** [comment]
Example located here 
https://github.com/murphye/vertx-web-openapi-quarkus-petstore/blob/main/src/main/java/org/acme/Main.java#L57

```
Router.newInstance(router).mountSubRouter("/", apiRouter); // Convert to Mutiny Router and mount apiRouter at '/'
```

**Comment by cescoffier** [comment]
Thanks @murphye, that is something we can add easily.
