### ISSUE TITLE
QuarkusDevModeTest add dynamic port like test-port=0

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#20196]
### Description

If you have a multimodule maven build with multiple extensions, and you run them in parallel, it often fails because the port 8080 is already in use. I could not find an option like quarkus.http.test-port=0 for the QuarkusDevModeTest in https://quarkus.io/guides/all-config. Could an option like this be added? Or maybe directly use quarkus.http.test-port?

**Comment by geoand** [comment]
`QuarkusDevModeTest` tests don't start Quarkus in test mode, so `quarkus.http.test-port` is not taken into account. 
You could use `quarkus.http.port=0` to get the random port assigned, but unfortunately for the time being that means that RestAssured won't be properly configured.

**Comment by robp94** [comment]
Ok thanks.
