### ISSUE TITLE
The proper way to scale vertx verticles

### ISSUE THREAD

**Issue by mxmind** [quarkusio/quarkus#2019]
Hi, 

My team and I'm planning to switch our platform on quarkus, but I stuck on the very simple operation for pure vertx. This is scaling verticle instances using deployment options.

Does it possible to scale vertx verticles? If true, please provide an example.

Thanks in advance

**Comment by cescoffier** [comment]
Did you try to use the regular `DeploymentOption` and set the number of instances?

**Comment by mxmind** [comment]
Hi, @cescoffier I tried to do a simple app, the code looks very close to this snippet:
```java
@Inject
private ICatalogServiceVerticle catalogServiceVerticle;

private String deploymentId;

private final DeploymentOptions options = new DeploymentOptions()
    .setInstances(4)
    .setIsolationGroup(this.getClass().getSimpleName().replaceAll("(.)(\\p{Upper})", "$1-$2").toLowerCase());

public void onStart(@Observes StartupEvent ev) {
    if (ev != null) {
        VxRifaUtil.registerRIFACodec(vertx);

        vertx.deployVerticle(catalogServiceVerticle, options, deployer -> {
            if (deployer.succeeded()) {
                VxRifaUtil.registerReceiver(vertx, ICatalogService.class, catalogServiceVerticle).setHandler(registrar -> {
                    if (registrar.failed()) {
                        LOGGER.error("Registration was failed", registrar.cause());
                        throw new IllegalStateException(registrar.cause());
                    } else {
                        LOGGER.debugv("{} deployment: {}", catalogServiceVerticle.getClass(), deployer.result());
                        this.deploymentId = deployer.result();
                    }
                });
            } else {
                LOGGER.error("Deployment failed", deployer.cause());
            }
        });
    }
}
```
as a result, the ILE raised as expected 
```bash
java.lang.IllegalArgumentException: Can't specify > 1 instances for already created verticle
```
I pretty know that is not a valid deployment, because I tried to deploy already instantiated verticle.
In my case, I want to have an option to get of CDI support, plus have an ability to register service verticles as VxRifa receiver.

**Comment by mxmind** [comment]
Just a bit more information, my current application has several factories to instantiate and deploy verticles, the deployment options are defined in application.conf. One of these factories is based on `weld-vertx` project. It works excellent. Now, my team doing the investigation, how we can move on `quarkus`.  In the case of Weld, we have everything to deploy and scale verticles by their class name.
The `quarkus` is great and shine, but it a beast animal (in the good sense) and I'm wondering how to implement or move everything we have with keeping the behavior of my application precisely same.

**Comment by gsmet** [comment]
@cescoffier what should we do about this one?

**Comment by BornToRain** [comment]
Is it settled now? I had the same problem.

**Comment by cescoffier** [comment]
The number of instances can only be set if you pass the class name (and not the instance of the verticle).

**Comment by kanibs** [comment]
hey @cescoffier , thanks for this information. But are there any plans to implement the feature(in future) of deploying an already instantiated verticle with instances getting set to more than 1. 
Reason being, when deploying using the class-name, there are many instance variable that does not get initialized and we have to make them all static.

**Comment by cescoffier** [comment]
That should be a feature request on Vert.x itself. In the meantime, you can use a Supplier<Verticle> instead of classnames to initialize the verticle properly.

**Comment by kanibs** [comment]
Thanks @cescoffier  for the response. My Bad I did not notice that this is Quarkus repo.

**Comment by stuartwdouglas** [comment]
Closing, as this is really a Vert.x issue.
