### ISSUE TITLE
quarkus-openapi: `@Schema(hidden=true)` on class level has no effect

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#20191]
### Describe the bug

`@Schema(hidden=true)` on class level has no effect.

See reproducer `HiddenFruit`

### Expected behavior

Classes annotated with `@Schema(hidden=true)` should not be visible in the openapi document.

### Actual behavior

`@Schema(hidden=true)` is ignored.

### How to Reproduce?

1. https://code.quarkus.io/?e=resteasy-reactive-jackson&e=smallrye-openapi
2. Add the following lines to the `application.properties`
```
quarkus.smallrye-openapi.store-schema-directory=target/generated-openapi
mp.openapi.scan.classes=org.acme.Fruit,org.acme.HiddenFruit,org.acme.VisibleFruit
```
3. Create the following classes
```java
package org.acme;

public class Fruit {

    public String name;
    public String description;

    public Fruit() {
    }

    public Fruit(String name, String description) {
        this.name = name;
        this.description = description;
    }
}
```

```java
package org.acme;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(hidden = true)
public class HiddenFruit {

    public String name;
    public String description;

    public HiddenFruit() {
    }

    public HiddenFruit(String name, String description) {
        this.name = name;
        this.description = description;
    }
}
```

```java
package org.acme;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(hidden = false)
public class VisibleFruit {

    public String name;
    public String description;

    public VisibleFruit() {
    }

    public VisibleFruit(String name, String description) {
        this.name = name;
        this.description = description;
    }
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1202]

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by phillip-kruger** [comment]
This is fixed in SmallRye. I'll close this when we up the SmallRye OpenAPI version

**Comment by phillip-kruger** [comment]
Sorry, the merge in SmallRye closed this. I'll close once it's updated
