### ISSUE TITLE
@ServerExceptionMapper seems to not support handle multi exception type

### ISSUE THREAD

**Issue by test210820** [quarkusio/quarkus#20202]
### Describe the bug

![image](https://user-images.githubusercontent.com/65008815/133625613-fa3cafdd-5d85-4e9e-8d06-79fe9835e39d.png)

then build time error

io.quarkus.resteasy.reactive.server.deployment.ServerExceptionMapperGenerator#getTargetMethodParamsInfo:533

![image](https://user-images.githubusercontent.com/65008815/133626562-293eda8b-cc3f-4ead-8585-e1509160f8c7.png)

### Expected behavior

support multi exception type

### Actual behavior

build time error

### Output of `uname -a` or `ver`

windows 10

### Output of `java -version`

openjdk 11

### Quarkus version or git rev

2.2.2.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by famod** [comment]
Fixed via #20216.
