### ISSUE TITLE
QuarkusEntryPoint assumes URL contains a file path

### ISSUE THREAD

**Issue by moritz-bruder** [quarkusio/quarkus#20201]
In https://github.com/quarkusio/quarkus/blob/cac51a60158212f662adb6ed086ce9c675215c65/independent-projects/bootstrap/runner/src/main/java/io/quarkus/bootstrap/runner/QuarkusEntryPoint.java#L30-L32 it is assumed that the returned `URL` contains a file path.  However, the class may have been loaded from another source.  Unfortunately, there is no `getParent` in `URL` but perhaps you could use `toURI().resolve("../../..")` instead.

**Comment by jaikiran** [comment]
Hello @moritz-bruder, could you add some background context on what issue this piece of code is causing. Perhaps with a reproducible example? This code may or may not have issues and I haven't paid detailed attention to it, but knowing the context will help us understand if there are better ways to deal with it.

**Comment by moritz-bruder** [comment]
Hello @jaikiran,

We are trying to make Quarkus work on JamaicaVM.  However, the code source for builtin classes is not a `URL` with the `file` protocol in our case.  The code in `QuarkusEntryPoint` seems to get the working directory through the code source (the path of the jar in this case).  Am I right in that assumption?  I am afraid it may not be easy to provide an example to you.

Would it be possible to check if the protocol is `file` and if not use a fallback path?  For example, the current working directory or a property.

**Comment by geoand** [comment]
@moritz-bruder if you have something in mind, feel free to open a PR

**Comment by geoand** [comment]
Closing as we did not get feedback
