### ISSUE TITLE
Hardcoded password for keystore in undertow plugin

### ISSUE THREAD

**Issue by sgerr** [quarkusio/quarkus#2021]
When initializing KeyManagerFactory at io.quarkus.runtime.configuration.ssl.ServerSslConfig:158 hardcoded password of "password" is used. Should be configurable property, let's say "quarkus.http.ssl.certificate.key-store-password". Like this:

@ConfigItem
public Optional<String> keyStorePassword;

at io.quarkus.runtime.configuration.ssl.CertificateConfig

**Comment by fndejong** [comment]
I would like to take a stab at this one, I should have enough time in the coming weekend.

**Comment by gsmet** [comment]
@fndejong cool, thanks!

**Comment by geoand** [comment]
Was this addressed by #2066? That PRs title seems to indicate it

**Comment by acheaito** [comment]
I can confirm that quarkus.http.ssl.certificate.key-store-password=mypass works with 0.16.1

**Comment by geoand** [comment]
Thanks @acheaito . I'll close this one then.

**Comment by fndejong** [comment]
@geoand I still have to document the feature. I must admit that I forgot to do it, since it took longer then expected to get merged. I should have some time to write document the options and their meaning in the coming weekend.

**Comment by geoand** [comment]
@fndejong OK, sounds good

**Comment by sgerr** [comment]
@fndejong I juist wrote a short howto at Stack Owerflow.

https://stackoverflow.com/questions/55588382/quarkus-https-restful-service/55647430#55647430

May be it would be helpful.

**Comment by gsmet** [comment]
@sgerr could you contribute something to this file: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/undertow-reference.adoc ?

It would be nice to have some proper documentation in our reference doc.

Thanks!

**Comment by gsmet** [comment]
Ah just saw @fndejong wanted to do it, sorry.

Let's get something ready for the next release!
