### ISSUE TITLE
mongodb-rest-data-panache integration tests use custom MongoTestResource

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#20211]
### Description

Integration tests in `mongodb-rest-data-panache` use a custom test resource:
https://github.com/quarkusio/quarkus/blob/main/integration-tests/mongodb-rest-data-panache/src/test/java/io/quarkus/it/mongodb/rest/data/panache/MongoTestResource.java

An equivalent one is available in `test-framework`:
`https://github.com/quarkusio/quarkus/blob/main/test-framework/mongodb/src/main/java/io/quarkus/test/mongodb/MongoTestResource.java`
This one is used across other modules in integration tests.

Only `mongodb-rest-data-panache` stands out and should be unified with the others.

### Implementation ideas

Pull request will follow.

**Comment by geoand** [comment]
I closed https://github.com/quarkusio/quarkus/pull/20212, see my comment about why.
The proper solution here would be to make `MongoTestResource` configurable.

**Comment by jsmrcka** [comment]
@geoand Second try in https://github.com/quarkusio/quarkus/pull/20227.
