### ISSUE TITLE
The locale-related configuration (e.g. quarkus.default-locale, quarkus.locales) currently only works on hibernate-validator. Will resteasy implement LocaleResovler and LocaleContext in the future? 

### ISSUE THREAD

**Issue by test210820** [quarkusio/quarkus#20210]
### Description

The locale-related configuration (e.g. quarkus.default-locale, quarkus.locales) currently only works on hibernate-validator. Will resteasy implement LocaleResovler and LocaleContext in the future?

**Comment by geoand** [comment]
In which JAX-RS objects would you expect to see support for this?
