### ISSUE TITLE
RestAssured not configured to use the correct port when `quarkus.http.test-ssl-port` is set

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#20228]
### Describe the bug

When a custom value for `quarkus.http.test-ssl-port` is set, RestAssured seems to not be configured to use it. Digging into the code, it appears that it's actually attempting to be set by resolving config property `quarkus.https.test-port`.

https://github.com/quarkusio/quarkus/blob/main/test-framework/common/src/main/java/io/quarkus/test/common/RestAssuredURLManager.java#L118-L120

There's also a couple of other references to it in the codebase:

https://github.com/quarkusio/quarkus/search?q=%22quarkus.https.test-port%22

### Expected behavior

The RestAssured port is configured to use the value of  `quarkus.http.test-ssl-port`.

### Actual behavior

`RestAssured.port` evaluates to `8444` and not the value of `quarkus.http.test-ssl-port`.

### How to Reproduce?

Create a unit test where `quarkus.http.test-ssl-port` is configured. Then use RestAssured to try and hit a server endpoint.

**Comment by geoand** [comment]
Is this still an issue? I vaguely remember us addressing something similar

**Comment by jamesnetherton** [comment]
Issue still seems to be present in Quarkus 2.16.0.Final.

**Comment by geoand** [comment]
Interesting, thanks for the update
