### ISSUE TITLE
Cannot use TestContainers, QuarkusTest and JPA together

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2022]
This should work and it does not:

```
@Testcontainers
@QuarkusTest
public class TodoResourceTest {

    @Container
    PostgreSQLContainer DATABASE = new PostgreSQLContainer<>()
            .withDatabaseName("rest-crud")
            .withUsername("restcrud")
            .withPassword("restcrud")
            .withExposedPorts(5432)
            .withCreateContainerCmdModifier(cmd -> {
                cmd
                        .withHostName("localhost")
                        .withPortBindings(new PortBinding(Ports.Binding.bindPort(5432), new ExposedPort(5432)));
            });

    @Test
    public void testInitialItems() {
        System.out.println(DATABASE.getJdbcUrl());
        String todos = get("/api").asString();
        System.out.println(todos);
    }

}
```

This is because the server is started before the database and connect to it immediately:
```
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution
Caused by: java.sql.SQLException: Exception while creating new connection
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while creating new connection
Caused by: java.lang.RuntimeException: Exception while creating new connection
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

The (ugly) workaround is:

```
@QuarkusTest
public class TodoResourceTest {

    @BeforeAll
    public static void init() {
        PostgreSQLContainer DATABASE = new PostgreSQLContainer<>()
                .withDatabaseName("rest-crud")
                .withUsername("restcrud")
                .withPassword("restcrud")
                .withExposedPorts(5432)
                .withCreateContainerCmdModifier(cmd -> {
                    cmd
                            .withHostName("localhost")
                            .withPortBindings(new PortBinding(Ports.Binding.bindPort(5432), new ExposedPort(5432)));
                });

        DATABASE
                .start();

        System.out.println(DATABASE.getJdbcUrl());
    }

    @Test
    public void testInitialItems() {
        String todos = get("/api").asString();
        System.out.println(todos);
    }

}
```

**Comment by bsideup** [comment]
Hi @cescoffier,
Although this does not seem to be Testcontainers' issue, If I may, I would like to suggest a few things here:
1) static port binding here is dangerous and most probably will break on CI env. I would suggest using random ports and either framework's test config mechanism or system properties like [here](https://github.com/testcontainers/workshop/blob/master/step-6-adding-redis.md). If you need PostgreSQL on port 5432 for **debugging with your favourite tools**, you can use the approach I described in [my recent article](https://bsideup.github.io/posts/debugging_containers/)

2) another option would be to use [the JDBC URL support](https://www.testcontainers.org/modules/databases/#database-containers-launched-via-jdbc-url-scheme), it makes starting with Testcontainers [super easy](https://github.com/testcontainers/workshop/blob/master/step-4-your-first-testcontainers-integration.md)

I hope that helps :)

**Comment by bsideup** [comment]
Well, if you use the JDBC URL-like containers, you can easily put it to `application.properties` like [here](https://github.com/testcontainers/testcontainers-java/blob/3b9e61e2b69db264db4e3f18dce8194d4debd2cf/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java#L12). The JDBC driver SPI will do the magic.

For other types of containers: yes, that's the algorithm :)

**Comment by geoand** [comment]
@cescoffier  I think you could get around the problem is a slightly less ugly way like so:

```
@Container
 static PostgreSQLContainer DATABASE = new PostgreSQLContainer<>()
            .withDatabaseName("rest-crud")
            .withUsername("restcrud")
            .withPassword("restcrud")
            .withExposedPorts(5432)
            .withCreateContainerCmdModifier(cmd -> {
                cmd
                        .withHostName("localhost")
                        .withPortBindings(new PortBinding(Ports.Binding.bindPort(5432), new ExposedPort(5432)));
            });

```

with the use of `static` you wouldn't have to add the boiler plate of `beforeAll`.

**Comment by cescoffier** [comment]
@geoand I've tried that, the application starts before the container so the connection failed.

**Comment by geoand** [comment]
@cescoffier weird... 

I changed our `quarkus-integration-test-jpa-postgresql` integration, by removing the docker maven plugin and altered the test code to be:

```
@Testcontainers
@QuarkusTest
public class JPAFunctionalityTest {

    @Container
    public static PostgreSQLContainer DATABASE = new PostgreSQLContainer<>("postgres:10.5")
            .withDatabaseName("hibernate_orm_test")
            .withUsername("hibernate_orm_test")
            .withPassword("hibernate_orm_test")
            .withExposedPorts(5432)
            .withCreateContainerCmdModifier(cmd -> {
                cmd
                        .withHostName("localhost")
                        .withPortBindings(new PortBinding(Ports.Binding.bindPort(5432), new ExposedPort(5432)));
            });

    @Test
    public void testJPAFunctionalityFromServlet() throws Exception {
        RestAssured.when().get("/jpa/testfunctionality").then().body(is("OK"));
    }

}
```

and everything worked as expected. I see from the logs that testcontainers is running before the Quarkus augmentation and application startup.

**Comment by cescoffier** [comment]
Ok, let me retry... I may have missed something (annotation order maybe?)

**Comment by cescoffier** [comment]
Ok, that was the issue, good to know! 
I'm going to change the title of the issue to work on a better integration as the one mention by @bsideup

**Comment by geoand** [comment]
If it doesn't work I can try again, perhaps I have done something wrong on my side :)

**Comment by geoand** [comment]
@cescoffier Great!
