### ISSUE TITLE
io.quarkus.jackson.ObjectMapperCustomizer DEFAULT_PRIORITY value should less than QUARKUS_CUSTOMIZER_PRIORITY?

### ISSUE THREAD

**Issue by test210820** [quarkusio/quarkus#20255]
### Description

![image](https://user-images.githubusercontent.com/65008815/133887579-58691983-6d23-4659-841f-a0b617e0836d.png)

In order to ensure that the user-defined can overwrite the built-in, DEFAULT_PRIORITY value should less than QUARKUS_CUSTOMIZER_PRIORITY ?

**Comment by geoand** [comment]
`DEFAULT_PRIORITY` being `0` means that the user customizer will be executer **after** the Quarkus customizer (which a priority of less than `0`).
That way Jackson will keep the the changes applied by the user customizer if there are conflicting settings

**Comment by test210820** [comment]
From the code point of view, it seems that the user-defined will be executed earlier than the built-in quarkus, if the user-defined priority is greater than the built-in quarkus ...

![image](https://user-images.githubusercontent.com/65008815/133892753-6ee551b1-40be-44a9-8acd-72eb7190b52d.png)


![image](https://user-images.githubusercontent.com/65008815/133892728-8f0932e0-0a45-46e6-8f4c-f221f9e5ab4d.png)

**Comment by test210820** [comment]
@geoand

**Comment by geoand** [comment]
Feel free to open a PR that improves the javadoc or the Jackson related docs
