### ISSUE TITLE
Allow to disable MP ConfigProperties and ConfigMapping

### ISSUE THREAD

**Issue by essobedo** [quarkusio/quarkus#20275]
### Description

Up to now, if we want to ease the mapping of the configuration, we can rely on the annotations `@ConfigProperties` from MicroProfile Config and/or `@ConfigMapping` from SmallRye Config. If used, Quarkus will check at runtime that the corresponding properties are available in the configuration which can be a problem if this part of the configuration only makes sense for production but not for the tests. 

### Implementation ideas

The idea could be to rely on build time conditions to enable or not the annotations `@ConfigProperties` and/or `@ConfigMapping`.

**Comment by radcortez** [comment]
I'm not totally sure if we should add this. Can you please elaborate more on a concrete use case? Thanks!

**Comment by essobedo** [comment]
In my use case I have several profiles that we will call `a` and `b`,  the code of both profiles is shared as they have a lot in common, so they also share some configuration classes. We rely on build time conditions to indicate Quarkus which Beans/JAX-RS Components/Configuration classes/properties... to enable or not according to the profile used at build time. Consequently, we have some specific configuration classes that map properties only available when the profile `a` is used so when we start the application with the profile `b`, it complains because the properties cannot be found. So the idea of this task is to be able to use build time conditions to disable or not  a Configuration class or interface, like it is already possible with the  deprecated annotation `io.quarkus.arc.config.ConfigProperties`.

```
@IfBuildProfile("a")
@ConfigProperties(prefix = "a")
public class SpecificToA {
    String somePropertySpecificToA;
 }
```

Is-it clear now?

**Comment by radcortez** [comment]
If I remember correctly, `@IfBuildProfile` does not include the bean during runtime, so it is effectively removed. If that is the case, then we can pick my other PR here https://github.com/quarkusio/quarkus/pull/19965/ and apply the same logic. If a bean that you use is unused and injects a mapping / properties, that one is also removed. In this way, you don't need additional annotations and it is done automatically.

**Comment by essobedo** [comment]
@radcortez If it allows to do the same thing that the test I have in my PR, it would be great

**Comment by radcortez** [comment]
Reopening, to close only when linked PR is merged.
