### ISSUE TITLE
Add support for CredentialsProvider in the MongoDB client

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#20277]
### Description

We use a custom credential provider to manage login credentials for all Argoal data sources, we need the same for MongoDB.  Currently MongoDB only supports plain text passwords in the application.properties/yml file which is not an acceptable solution.

Please add support for same credential provider in MongoDB.

Custom Credential Provider: https://quarkus.io/guides/credentials-provider#custom-credentials-provider

**Comment by dhoffer** [comment]
Discussed this here: https://groups.google.com/g/quarkus-dev/c/a5p4CHvA5to/m/Mee3r77TCgAJ?utm_medium=email&utm_source=footer

**Comment by SebaLG** [comment]
Any news about this?

**Comment by gsmet** [comment]
Not really. A contribution would be welcome. I don't think it would be that hard given there are already several examples in the tree.
