### ISSUE TITLE
Interceptors (and decorators?) should "inherit" annotations from stereotypes

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#20296]
### Description

As far as I understand, interceptor classes (and decorator classes too?) may declare stereotypes (because they are beans), in which case, they should inherit the relevant annotations. That is:

- in case of interceptors:
  - default scope, if it's `@Dependent` (otherwise an error? unless the class explicitly declares `@Dependent`?)
  - the set of interceptor bindings
  - the `@Priority` (CDI 4.0 will explicitly allow declaring `@Priority` on stereotypes)
- in case of decorators:
  - default scope, if it's `@Dependent` (otherwise an error? unless the class explicitly declares `@Dependent`?)
  - the `@Priority` (CDI 4.0 will explicitly allow declaring `@Priority` on stereotypes)

**Comment by mkouba** [comment]
-1 from me. I don't think this feature would bring any benefit to users. It would just complicate the logic and implementation code. You would have to handle situations (which are not clearly defined in the spec) like what if my interceptor declares multiple stereotypes where each declares an interceptor binding with a different value of a binding member (!)...

Interceptors/decorators are beans, but a _special kind_ of bean and a lot exceptions is applied. For example, they must be `@Dependent` and any other scope results in a definition error. Interceptors and decorators may not declare observer methods, their methods are not intercepted, if an interceptor/decorator is an alternative, non-portable behavior results, etc.
