### ISSUE TITLE
Question: How to terminate running app? Ctrl+C does not work

### ISSUE THREAD

**Issue by paulvi** [quarkusio/quarkus#2029]
How to terminate running app? Ctrl+C does not work ?

![image](https://user-images.githubusercontent.com/1614482/56025825-7f37ca00-5d45-11e9-9118-9a3a95ca16eb.png)

**Comment by rsvoboda** [comment]
Ctrl+C is the way. I tried it with quarkus-quickstarts - application-lifecycle-events and it works.
Checked on macOS and Windows Server in VirtualBox.

If you are somehow stuck you can try Task Manager to kill the process.

**Comment by starksm64** [comment]
I see this issue from within the git bash shell on windows under vmware as well, so it is probably the shell not handling signals correctly. I was going to look into what the cause might be and if there was a configuration/setting to fix this.

**Comment by starksm64** [comment]
More info, this issue on the underlying console used by git indicates there are different shells used:
https://github.com/cbucher/console/issues/262#issuecomment-159164159

The default exe used by the Git-Bash desktop link is C:\Program Files\Git\git-bash.exe, and this does not handle the Ctrl-c correctly. If instead you launch the C:\Program Files\Git\bin\bash.exe the Ctrl-c does work, however, the color output from the logging produces a bunch of garbage codes.

<img width="940" alt="console" src="https://user-images.githubusercontent.com/332210/56051706-6ce96c00-5d04-11e9-8400-bd9d5d33dd84.png">

**Comment by paulvi** [comment]
OK, I am pay attention to what executable of Git Bash is ... TODO update here

**Comment by rsvoboda** [comment]
I use https://cmder.net/ on Windows and it works well both for git and color output.
