### ISSUE TITLE
quarkus-resteasy-reactive and undertow can't coexist in one application

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#20302]
### Describe the bug

quarkus-resteasy-reactive and undertow can't coexist in one application

JAX-RS endpoint (`/hello`) is not available, 404 got returned, when checked Dev UI the enpoind was listed.

```
[ERROR] org.my.group.ReactiveGreetingResourceTest.testHelloEndpoint  Time elapsed: 1.471 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <404>.

	at org.my.group.ReactiveGreetingResourceTest.testHelloEndpoint(ReactiveGreetingResourceTest.java:17)

2021-09-21 14:08:23,977 INFO  [io.quarkus] (main) Quarkus stopped in 0.041s
```

### Expected behavior

http://localhost:8080/hello serves content and returns 200.

### Actual behavior

404 error

### How to Reproduce?

rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:2.2.3.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.2.3.Final -Dextensions=quarkus-resteasy-reactive,undertow

mvn clean verify -f app-generated-skeleton/pom.xml

### Quarkus version or git rev

2.2.3.Final

**Comment by rsvoboda** [comment]
close of the issue was miss-click

**Comment by lthasle** [comment]
What is the current status with this issiue?

It is blocking our attempt to migrate our applications from classic to reactive.

The problem may be reproduced by adding the undertow dependency to the reactive-guide:
https://quarkus.io/guides/rest-client-reactive
https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart
pom.xml:
<dependency>
		  <groupId>io.quarkus</groupId>
		  <artifactId>quarkus-undertow</artifactId> 
		</dependency>
    <dependency>

And run the command: mvn clean install
All the test then fails with 404

**Comment by geoand** [comment]
This was fixed in https://github.com/quarkusio/quarkus/pull/20886
