### ISSUE TITLE
Custom system properties are ignored by @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by afalhambra** [quarkusio/quarkus#20318]
### Describe the bug

When running integration tests by using annotated classes with @QuarkusIntegrationTest, custom system properties defined in the maven-failsafe-plugin maven plugin are completely ignored and not passed as system properties to the quarkus app when starting up the app when running the integration test.
The same approach works fine for the @QuarkusTest annotated classes in the maven-surefire-plugin maven plugin.

### Expected behavior

Custom system properties defined in the maven-failsafe-plugin maven plugin should be passed as system properties to the quarkus app when starting up the same.

### Actual behavior

Only predefined quarkus properties are passed to the quarkus app startup and not the custom system properties defined in the maven plugin for the integration tests.

### How to Reproduce?

Reproducer:

1. Download attached reproducer.
2. Execute maven command, mvn clean install
3. Both unit and integration tests should work (only @QuarkusTest unit test passed due to this bug)

[reproducer.zip](https://github.com/quarkusio/quarkus/files/7208137/reproducer.zip)

### Output of `uname -a` or `ver`

Linux antferna.remote.csb 4.18.0-305.17.1.el8_4.x86_64 #1 SMP Mon Aug 30 07:26:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 LTS

### GraalVM version (if different from Java)

none

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.6.3

**Comment by geoand** [comment]
This is a tough one to be honest...

the problem is that in the JUnit extension we don't know which system properties have been set by the Maven Failsafe plugin...
