### ISSUE TITLE
Allow Sort to be empty

### ISSUE THREAD

**Issue by acaciobrito** [quarkusio/quarkus#20329]
### Description

I am writing amazon lambdas using quarkus-amazon-lambda-rest, quarkus-resteasy-jackson and quarkus-hibernate-orm-panache
I have one rest endpoint that will return me a list of the entities. But I need to be able to sort that list based on a query param.

Right now my query param is a list of string where I receive 'columnName,(ASC or DSC)'

The Sort class from io.quarkus.panache.common has it constructor as private.
It requires the Sort object to always have some column. We should have way to be able to create a Sort object without defining a column. Pretty much to what spring does with Pageable.Sort.

For example, this isn't allowed

```java
 Sort sort = new Sort();

    for (String s : sortQuery) {
      String sortColumn = s.split(",")[0];
      String sortOrder = s.split(",")[1];

      sort.and(sortColumn,
          sortOrder.equalsIgnoreCase("ASC") ? Direction.Ascending : Direction.Descending);
    }
return personRepository.findByName(name, sort) 
```

### Implementation ideas

Either allow the constructor on Sort to be public or create an static method .empty().

**Comment by loicmathieu** [comment]
@FroMage empty sort is already possible via `Sort.by()` as we use a varargs but it's not very discoverable so adding `Sort.emtpy()` seems to be a good addition with a discoverable name and a straighforward implementation (delegate to `Sort.by()`).
WDYT ?

**Comment by geoand** [comment]
Sounds reasonable to me
