### ISSUE TITLE
Introduce cross version testing of platforms with tooling

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#20325]
We should test backward and forward compatibility.

IMO testing the CLI is not enough, we should:
Test each supported versions (+ the current main version of the dev tool lib) of the devtool java library with all the registry data (+ the current main version of the data), parse every extension and load every codestarts.

**Comment by ia3andy** [comment]
@maxandersen if I remember well there is a way with JBang to pass a dep version in command line args?

@aloubyansky I would need two scenarios:
1. The JUnit test runs the JBang script (using different version of the devtools) which use registry.quarkus.io (to test released data)
2. The JUnit test runs the JBang script (using different version of the devtools) which use some registry that contains current main

I am not sure if this fit best as a quarkus core integration test or an ecosystem test. I would think the latest.

**Comment by maxandersen** [comment]
for //DEPS dependencies you can use system property replacement (see https://www.jbang.dev/documentation/guide/latest/dependencies.html#system-properties-and-environment-variables)

But I assume what you are after is running specific versions of Quarkus cli ?

Then instead of using `quarkus@quarkusio` alias use what it directly points to:

`jbang https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/2.2.3.Final/quarkus-cli-2.2.3.Final-runner.jar`

You could use maven coordinates too but since the cli pom says it has dependencies when it really does not you end up with double classpath entries -  thus for now I would use the absolute urls instead.

**Comment by ia3andy** [comment]
@maxandersen using a different version of the Quarkus CLI is not enough, look at the issue description.

**Comment by maxandersen** [comment]
@ia3andy yes? so use the system property replacement approach I linked to if you want to run same piece of code against multiple versions.

**Comment by aloubyansky** [comment]
What would the JBang script do? Just trying to clarify whether it has to be a script and what fits better from the JUnit perspective.

**Comment by ia3andy** [comment]
A simpler way might be to have a maven project with junit tests which uses the `devtools-common` dep, then from the ecosystem CI we run it, using different versions. This way we could also use the test registry that we use for other tests in quarkus core.

**Comment by ia3andy** [comment]
@aloubyansky maybe we are saying the same thing?

The reason we thought about JBang is that if we run the test in quarkus core, it will be called from any JUnit test and we we would need to call something which use different versions of the devtools-commin dep (thus JBang). But from the eco-system ci, we can build & test the same maven project using different version of the dep.

**Comment by ia3andy** [comment]
I would go like this:
- Add a new integration-test in Quarkus Core, it will test (data processing and codestarts) using the snapshot version of devtools-common agains the snapshot registry and also the official registry.quarkus.io
- Add an ecosystem-ci which run this new integration-test with mvn changing the `devtools-common-version` property

**Comment by ia3andy** [comment]
STEP 1 "SNAPSHOT VERSION OF DEVTOOLS <-> All registry data (SNAPSHOT + RELEASED)":
@aloubyansky I would need your help to set that up, could you help me make
- an integration test that uses the current snapshot version of the registry
- another test that uses the official registry

Then I will take care of implementing the tests.

STEP 2 "PREVIOUS VERSIONS OF DEVTOOLS <-> All registry data (SNAPSHOT + RELEASED)":
We will also need to get the list of released versions of the devtools-common from maven central and iterate on the latest N.

**Comment by aloubyansky** [comment]
Sure, I can help but not today.

**Comment by maxandersen** [comment]
Can of course use junit to orchestrate it just Remember these need to run in external processes. Not in a junit under influence of any of our own classpath or env settings.

**Comment by maxandersen** [comment]
I made https://github.com/maxandersen/quarkus-hassle with a basic start of cross testing
