### ISSUE TITLE
Register kubernetes extension

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#2033]
When running `./mvnw quarkus:list-extensions` you see a lot of extensions but one that is set in guides but not registered is the one about Kubernetes.

`io.quarkus:quarkus-kubernetes`

I am using Quarkus 0.13.1

**Comment by lordofthejars** [comment]
I can help with a PR.

**Comment by gsmet** [comment]
Look for `extensions.json` in the tree, you need to add an entry here (if not already done in master). They are ordered alphabetically.

Thanks!

**Comment by geoand** [comment]
Funny, I remember adding this.... I guess it must have got lost in the many rebases/squashes that were done during the development of the extension.

Thanks for spotting!
