### ISSUE TITLE
Swagger-ui doesn't work when using openid-connect on quarkus 2.2.3.Final

### ISSUE THREAD

**Issue by deathwaiting** [quarkusio/quarkus#20337]
### Describe the bug

I am using keycloak for securing the application, 
when running the app in dev mode and opening `localhost:8180/q/swagger-ui` in the browser gives a white page.

The browser console gives the following error 
`Uncaught TypeError: ui.initOAuth is not a function
    onload http://localhost:8180/q/swagger-ui/:41
    EventHandlerNonNull* http://localhost:8180/q/swagger-ui/:20
swagger-ui:41:20`

checking the page code shows a strange redefinition of the `ui` variable.

```
window.onload = function() {
                const ui = {
                    url: '/q/openapi',
                    dom_id: '#swagger-ui',
                    deepLinking: true,
                    withCredentials: true,
                    presets: [SwaggerUIBundle.presets.apis,SwaggerUIStandalonePreset],
                    plugins: [SwaggerUIBundle.plugins.DownloadUrl],
                    layout: 'StandaloneLayout',
                };                
                // If Url is relative, append the host and port
                var oar = "/q/swagger-ui/oauth2-redirect.html";
                if(oar.startsWith("/")){
                    oar = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + oar;
                    ui.oauth2RedirectUrl = oar;
                }else if(oar !== "-"){
                    ui.oauth2RedirectUrl = oar;
                }
                
                ui.initOAuth({
		clientId: '#####',
		clientSecret: '####',
		realm: '#####',
		appName: '#########',
	})
                
                window.ui = SwaggerUIBundle(ui)

                document.getElementsByClassName("link")[0].innerHTML = "<a href='/q/swagger-ui'><img src='logo.png' alt='OpenAPI UI (Powered by Quarkus 2.2.3.Final)' height='44' align='middle'></a>";
            }
```

### Expected behavior

The page should work

### Actual behavior

get an error during the page load

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled) OpenJ9   - 345e1b09e OMR      - 741e94ea8 JCL      - 0a86953833 based on jdk-11.0.10+9)

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 6.5.1 ------------------------------------------------------------  Build time:   2020-06-30 06:32:47 UTC Revision:     66bc713f7169626a7f0134bf452abde51550ea0a  Kotlin:       1.3.72 Groovy:       2.5.11 Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019 JVM:          11.0.10 (Eclipse OpenJ9 openj9-0.24.0) OS:           Linux 5.13.13-1-MANJARO amd64

**Comment by phillip-kruger** [comment]
This is fixed in https://github.com/quarkusio/quarkus/releases/tag/2.3.0.CR1

**Comment by sberyozkin** [comment]
Let me close it then :-)
