### ISSUE TITLE
Quarkus gives 404 for static content with spaces in names

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#20344]
### Describe the bug

We are using 2.1.4.Final and have found that static content with spaces in the file names gives 404 errors.  Specifically we configure our static handler like this.

StaticHandler staticHandler = StaticHandler.create()
.setFilesReadOnly(true)
.setDirectoryListing(false)
.setAllowRootFileSystemAccess(true)
.setWebRoot(webRoot);

We have tracked this down from our upgrade to 2.1.4.Final from 1.13.7.Final.

These get added like:

public void init(@Observes Router router) {
  router.route(handlerPath).handler(staticHandler);

As a test I updated the following to the latest service pack update and it did not resolve the issue.

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web</artifactId>
  <version>4.1.4</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web-common</artifactId>
  <version>4.1.4</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-core</artifactId>
  <version>4.1.4</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-auth-common</artifactId>
  <version>4.1.4</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-bridge-common</artifactId>
  <version>4.1.4</version>
</dependency>

-Dave

### Output of `java -version`

openjdk version 11.0.11 2021-04-20

### Quarkus version or git rev

2.1.4.Final

**Comment by dhoffer** [comment]
I tried upgrading to Quarkus 2.2.3.Final and it has the same issue.

**Comment by stuartwdouglas** [comment]
The linked vert.x issue has been resolved.

**Comment by cescoffier** [comment]
Closing - we updated to Vert.x 4.2.

**Comment by dhoffer** [comment]
@cescoffier @pmlopes  I'm not clear what version of Quarkus has this fix.  I just updated an app to 2.4.2.Final, and Maven reports its using vertx 4.1.5.  Do we have to wait for Quarkus 2.5.x to get this fix?

**Comment by cescoffier** [comment]
Yes.
