### ISSUE TITLE
Resteasy Reactive: Kotlin `Flow` and `Multi` are not supported in suspend functions

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#20345]
### Describe the bug

`Flow` and `Multi` cannot be returned from a suspendable function (resteasy reactive).

### How to Reproduce?

1. https://code.quarkus.io/?e=resteasy-reactive-jackson&e=kotlin
2. Add the following code:

```kotlin
import io.smallrye.mutiny.Multi
import io.smallrye.mutiny.coroutines.asMulti
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.enterprise.context.ApplicationScoped
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@ApplicationScoped
@Path("/flow")
class FlowResource {

    @GET
    @Path("/1")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun flow1Method(): Flow<String> { // kotlinx.coroutines.flow.SafeFlow@6b336f3a
        compute()

        return flow {
            emit("1")
            emit("2")
            emit("3")
        }
    }

    @GET
    @Path("/2")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun multiMethod(): Multi<String> { // io.smallrye.mutiny.operators.multi.builders.EmitterBasedMulti@5eec36c2
        compute()

        return flow {
            emit("1")
            emit("2")
            emit("3")
        }.asMulti()
    }

    private suspend fun compute() {
        delay(1000)
    }
}
```

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by geoand** [comment]
This is indeed true, but I would like to know what a real world example of this would be.

**Comment by mschorsch** [comment]
> 
> 
> This is indeed true, but I would like to know what a real world example of this would be.

A real world example would be to stream data from a database. The database is accessed via a suspend function.

**Comment by geoand** [comment]
Returning data from database is hardly a streaming use case to be honest, databases don't stream results (in the `Multi` fashion). In almost all cases, returning `Uni<List<Whateve>>` is the proper way to handle the database results.

In any case, can you show some pseudocode of what you have in mind?

**Comment by mschorsch** [comment]
> 
> 
> Returning data from database is hardly a streaming use case to be honest, databases don't stream results (in the `Multi` fashion). In almost all cases, returning `Uni<List<Whateve>>` is the proper way to handle the database results.
> 
> In any case, can you show some pseudocode of what you have in mind?

Not a database streaming example, but hopefully it shows my point.

```kotlin
    @GET
    @Path("/1")
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun parse(
        file: FileUpload
    ): Flow<String> {
        readOrWriteSomethingFromOrToTheDatabase()
        return parseCsvFile(file.uploadedFile())
    }

    private suspend fun readOrWriteSomethingFromOrToTheDatabase() {
        // database access (or any other dependent function) needs a suspendable function
        // In our applications we us suspendable function heavilly.
    }

    private fun parseCsvFile(path: java.nio.file.Path): Flow<String> {
        return path.bufferedReader()
            .lines()
            .consumeAsFlow()
            .map { it.uppercase() }
            .flowOn(Dispatchers.IO) // Dispatchers.IO used here only as an example
    }
```

**Comment by geoand** [comment]
Thanks

**Comment by kdubb** [comment]
We _would_ use flow to send SSE events. It would fill that bill nicely. For example, connect to a message queue and push events to clients via SSE.

**Comment by kdubb** [comment]
I realize there are other solutions for this but this would allow us to stay inside a coroutine context.

**Comment by mofr** [comment]
Here is a real-life example from my side:
Build a service that streams a zip file built on the fly. The zip file contains files downloaded via HTTP. Files are big enough to don't fit into RAM. Using filesystem should be avoided since it's unnecessary.

I have a directly related question in the stackoverflow which basically duplicates the issue: https://stackoverflow.com/questions/69161606/how-to-stream-response-body-in-quarkus-with-kotlin
@geoand Please let me know if it's a separate issue.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20371 should take care of the `Flow` case. I don't think I'll add support for `Multi` for the time being as using `Multi` and `suspend` together sounds like a weird use case.
