### ISSUE TITLE
NullPointerException in MicrometerRecorder.registerMetrics

### ISSUE THREAD

**Issue by rolfborst** [quarkusio/quarkus#20350]
### Describe the bug

Hello Quarkus-Team,

great work. I'm currently moving a project from tomee to quarkus. This is a example project for my students in "database technology". So I have used a lot of your extensions for jpa, mongodb, neo4j, cassandra, ... All worked absolutly fine. In a last step I want to introduce the extension "quarkus-micrometer-registry-prometheus" to demonstrate the use of prometheus as a time series database. When I add this extension, the project doesn't start any more. The exception is:

```
2021-09-23 08:55:32,209 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.NullPointerException
	at io.quarkus.micrometer.runtime.MicrometerRecorder.registerMetrics(MicrometerRecorder.java:169)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry-2125003310.deploy_0(MicrometerProcessor$configureRegistry-2125003310.zig:123)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry-2125003310.deploy(MicrometerProcessor$configureRegistry-2125003310.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1189)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
```

It seems to me, that one of my lot of extension does not work correctly and so corrupt the complete system.

Is it possible, that you do a null check in the registerMetrics method (the parameter consumer is called with null)?

```java
    public void registerMetrics(Consumer<MetricsFactory> consumer) {
        consumer.accept(factory);
    }
```

I do a greater google search but it seems that no other people has my problem ;-)

I have tried to deactivate all of the metrics in the application.properties to find the "corrupt" extension but no of these deactivations have an effect to my NullPointerProblem. 

```
quarkus.micrometer.binder.jvm=false
quarkus.micrometer.binder.system=false
quarkus.micrometer.binder-enabled-default=false
quarkus.micrometer.registry-enabled-default=false
quarkus.scheduler.metrics.enabled=false
quarkus.datasource.jdbc.enable-metrics=false
quarkus.datasource.metrics.enabled=false
quarkus.hibernate-orm.statistics=false
quarkus.hibernate-orm.metrics.enabled=false
quarkus.neo4j.pool.metrics.enabled=false
quarkus.log.metrics.enabled=false
quarkus.smallrye-graphql.metrics.enabled=false
quarkus.grpc.metrics.enabled=false
```

Only when I deactivate all with "quarkus.micrometer.enabled=true" there is no NullPointerException any more. But then I also have no metrics ;-)

For me, this is not a serious problem, because that is a project for students, but I want to report the problem so that you can think about a null check at this point.

Bye 
Rolf

### Quarkus version or git rev

2.1.0.Final

**Comment by geoand** [comment]
It looks like neo4j is the one responsible for the `null` consumer: https://github.com/quarkusio/quarkus/blob/2.3.0.CR1/extensions/neo4j/runtime/src/main/java/io/quarkus/neo4j/runtime/Neo4jDriverRecorder.java#L79

I'll leave it up to @ebullient to decide whether `null` should be allowed (and therefore guarded against) or not

**Comment by rolfborst** [comment]
Wow, absolutly great work how fast you find the problem :-)

When I activate the neo4j-metrics all works fine:

quarkus.neo4j.pool.metrics.enabled=true

When I set it to false or leave it unset, I get the NullPointerException

**Comment by ebullient** [comment]
I should absolutely be checking for null because it can apparently happen, though it would be kinder for neo4j not to register the supplier at all unless metrics are turned on. I'll try to fix both. Thanks for looking Georgios.. you beat me to it.

**Comment by geoand** [comment]
👍🏼
