### ISSUE TITLE
Returning Uni<AsyncFile> doesn't work as described

### ISSUE THREAD

**Issue by madprogrammer** [quarkusio/quarkus#20352]
### Describe the bug

Hello,

In [documentation](https://quarkus.io/guides/resteasy-reactive#returning-a-response-body), it is stated that returning an `AsyncFile` or `Uni<AsyncFile>` should lead to contents of the file being returned, however, when I try to return `Uni<AsyncFile>`, or particularly `Uni<io.vertx.mutiny.core.file.AsyncFile>` which is by default returned from `vertx.fileSystem().open()`, what I get is just a string representation of the `AsyncFile` class.

### Expected behavior

The contents of the file should be returned by the server

### Actual behavior

A reply with following content is returned `io.vertx.core.file.impl.AsyncFileImpl@54d3c384`

### How to Reproduce?

The following code reproduces the problem for me:
```java
@Path("/photo")
@ApplicationScoped
public class PhotoResource {
    private final Vertx vertx;

    @Inject
    public PhotoResource(Vertx vertx) {
        this.vertx = vertx;
    }

    @GET
    @Blocking
    @Produces("image/jpeg")
    public Uni<AsyncFile> getPhoto(@QueryParam("id") String id) {
        return vertx.eventBus().<JsonObject>request("photo", new JsonObject().put("id", id))
          .onItem().transformToUni(message -> vertx.fileSystem()
            .open(message.body().getString("path"), new OpenOptions().setRead(true)));  
    }
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1237]

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by madprogrammer** [comment]
I also have an additional related question: is returning a `Uni<RestResponse<AsyncFile>>` or `Uni<Response>` with an `AsyncFile` supposed to work or not? Because I want to return a file body with an additional ETag header set in the response in case if the requested file was found, or return a 404 response otherwise. Currently, trying to return `Uni<RestResponse<Path>>` or `Uni<RestResponse<AsyncFile>>` produces the same behaviour (`toString` representation is returned in the response)

**Comment by michalszynkiewicz** [comment]
@madprogrammer which REST extension do you use?

**Comment by madprogrammer** [comment]
@michalszynkiewicz in "Installed features" the following relevant extensions are listed: `quarkus-resteasy-reactive`, `quarkus-resteasy-reactive-jackson`

**Comment by madprogrammer** [comment]
@michalszynkiewicz it seems to be related specifically to **Mutiny** API. I've rewrited the code without **Mutiny** to test, and it works:
```java
@javax.ws.rs.Path("/photo")
@ApplicationScoped
public class PhotoResource {
    private final Vertx vertx;

    @Inject
    public PhotoResource(Vertx vertx) {
        this.vertx = vertx;
    }

    @GET
    @Blocking
    @Produces("image/jpeg")
    public Uni<AsyncFile> getPhoto(@QueryParam("id") String id) {
        return Uni.createFrom().emitter(emitter -> {
            vertx.eventBus().<JsonObject>request("ru.weightsys.photo", new JsonObject().put("id", id), ar -> {
                if (ar.failed()) {
                    emitter.fail(ar.cause());
                } else {
                    String path = ar.result().body().getString("path");
                    vertx.fileSystem().open(path, new OpenOptions().setRead(true), result -> {
                       if (result.failed())  {
                           emitter.fail(result.cause());
                       } else {
                           emitter.complete(result.result());
                       }
                    });
                }
            });
        });
    }
}
```

**Comment by geoand** [comment]
Can  you try returning `io.vertx.core.file.AsyncFile`?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20374 fixes the issue
