### ISSUE TITLE
Support for Multi-instance Verticles and Dependency Injection

### ISSUE THREAD

**Issue by cdennison** [quarkusio/quarkus#20359]
### Description

As a Quarkus developer I use Quarkus to deploy high throughput services using protocols like HTTP/WS/Kafka/AMQP/MQTT/etc. Currently Quarkus has great support for HTTP/WS/Kafka but not AMQP/MQTT/etc. The reason why, is that to support high throughput I need multi-reactor support (i.e. multiple event-loops/threads per deployment). HTTP/WS already allows me to specify the exact number of event-loops/threads and Kafka also indirectly supports this through specifying the number of partitions.

Unfortunately, there's no good way to do this for several of the other protocols currently supported through  "[SmallRye Reactive Messaging](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/connectors/connectors.html)" or even using Vert.x clients directly again for protocols like AMQP/MQTT/etc.

The reason why is Quarkus either allows me to: 
1. Deploy non-bean Verticles and specify however many instances I want but have limited dependency injection support (and possible other limitations I haven't discovered)
2. [Deploy Verticles as @ApplicationScoped beans](https://quarkus.io/guides/vertx-reference#deploying-verticles) and get everything I'm expecting but then I cannot deploy more than 1 instance of the Verticle without getting the error "Can't specify > 1 instances for already created verticle". 

I've been exploring this issue with Clement Escoffier on StackOverflow which is why I'm confident that I'm not doing something wrong: https://stackoverflow.com/questions/69079674/how-to-start-multiple-message-consumers-in-quarkus/69199020

My feature request:

> I request that Quarkus support deploying Verticles as beans with more than one instance per deployment.

Alternatives I considered:

- Deploying non-beans with limited injection support - that's what I'm using for now
- Horizontal scaling vs. Verticle scaling - this is not an option for me. I'm using Quarkus because I require a lot of CPU for high throughput and I cannot waste the CPUs given to me. Based on performance testing if only use only 1 connection to a message broker per deployment the performance is much worse than if I have 2 or 4 connections.

**Comment by mkouba** [comment]
CC @cescoffier

**Comment by cescoffier** [comment]
@mkouba is it possible to ask Arc to produce multiple instance? Do we have to define a scope for this?

**Comment by cescoffier** [comment]
Another solution is to use access the CDI continuer object and do the lookup manually but that's not very nice.

**Comment by manovotn** [comment]
> @mkouba is it possible to ask Arc to produce multiple instance? Do we have to define a scope for this?

The only scope which allows you do have multiple instances is `@Dependent` which is really just a pseudo-scope.

**Comment by cescoffier** [comment]
Let's imagine, in an `@ApplicationScoped` bean,  I inject something like this : (with `MyVerticle` being in the `@Dependent` scope.):

```
@Inject Instance<MyVerticle> verticles;
```

If I call `verticles.get()` 3 times, how many different instances would I get?

**Comment by manovotn** [comment]
So, in order not to keep things simple, there are two options in Quarkus :-D
* You will get three different instances of `MyVerticle` under normal circumstances (under standard CDI behavior)
* If you also annotate the `Instance` injection point with `@WithCaching`, you will get only one, see [this part of docs](https://quarkus.io/guides/cdi-reference#caching-the-result-of-programmatic-lookup)

**Comment by mkouba** [comment]
We could also introduce a new scope? Bound to a `io.vertx.core.Context`? I'm not sure if it makes sense though...
