### ISSUE TITLE
Nonexisting truststore doesn't lead to error in native image

### ISSUE THREAD

**Issue by matthiasgubler** [quarkusio/quarkus#20360]
### Describe the bug

I tried to bake a truststore into my application using the following property:
`quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=/tmp/mongo/truststore.jks,-J-Djavax.net.ssl.trustStorePassword=changeit
`

The issue is that if the file /tmp/mongo/truststore.jks does not exist, I don't get an error because it seems that the build-process makes a fallback on some default truststore. This leads to a successful build and later on to an error message when calling a service/app/db that requires SSL:
`sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If I change the password to an arbitrary value, I get an error in the build process:
`javax.net.ssl.trustStorePassword=FooBar` 
`java.security.UnrecoverableKeyException: Password verification failed` 

This behaviour happens, even though the file does not exist.

If I use an existing truststore with the correct password, everything works fine.

### Expected behavior

By setting an non existing truststore I would expect the build process to fail with a corresponding error message.

### Actual behavior

The buildprocess takes some unknown default truststore, that then fails in the runtime of the application because of the wrong CA in it.

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-3.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64 (but also on ubuntu)

### Output of `java -version`

openjdk version "11.0.10"

### GraalVM version (if different from Java)

21.0.0

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3

### Additional information

Buildlog with nonexisting truststore:

`/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55197,suspend=y,server=n -Dmaven.multiModuleProjectDirectory=/Users/mathew/gitrepos/trap/trap -Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Users/mathew/Library/Caches/JetBrains/IntelliJIdea2020.3/captureAgent/debugger-agent.jar -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar org.codehaus.classworlds.Launcher -Didea.version=2020.3.4 package -Pnative -DskipTests
Connected to the target VM, address: '127.0.0.1:55197', transport: 'socket'
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< com.axa.ch.trap:trap >------------------------
[INFO] Building trap 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.2.3.Final:generate-code (default) @ trap ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ trap ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ trap ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:instrument (instrument) @ trap ---
[INFO] 
[INFO] --- quarkus-maven-plugin:2.2.3.Final:generate-code-tests (default) @ trap ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ trap ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ trap ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /Users/mathew/gitrepos/trap/trap/target/test-classes
[INFO] /Users/mathew/gitrepos/trap/trap/src/test/java/ch/zhaw/ba/mongo/codec/OrderEventProviderTest.java: /Users/mathew/gitrepos/trap/trap/src/test/java/ch/zhaw/ba/mongo/codec/OrderEventProviderTest.java uses unchecked or unsafe operations.
[INFO] /Users/mathew/gitrepos/trap/trap/src/test/java/ch/zhaw/ba/mongo/codec/OrderEventProviderTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ trap ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:restore-instrumented-classes (restore) @ trap ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ trap ---
[INFO] Building jar: /Users/mathew/gitrepos/trap/trap/target/trap-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:2.2.3.Final:build (default) @ trap ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- com.axa.ch.trap.model.OrderEvent (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/mathew/gitrepos/trap/trap/target/trap-1.0.0-SNAPSHOT-native-image-source-jar/trap-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/mathew/gitrepos/trap/trap/target/trap-1.0.0-SNAPSHOT-native-image-source-jar/trap-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0/Contents/Home/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=de -J-Duser.country=CH -J-Dfile.encoding=UTF-8 -J-Djavax.net.ssl.trustStore=/tmp/mongo/nonexisting.jks -J-Djavax.net.ssl.trustStorePassword=changeit -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-UseServiceLoaderFeature -H:+StackTrace trap-1.0.0-SNAPSHOT-runner -jar trap-1.0.0-SNAPSHOT-runner.jar
[trap-1.0.0-SNAPSHOT-runner:70790]    classlist:   2’404.77 ms,  1.19 GB
[trap-1.0.0-SNAPSHOT-runner:70790]        (cap):  10’402.39 ms,  1.68 GB
[trap-1.0.0-SNAPSHOT-runner:70790]        setup:  12’353.30 ms,  1.68 GB
15:31:09,174 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.2.0.Final
15:31:25,903 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[trap-1.0.0-SNAPSHOT-runner:70790]     (clinit):   1’193.02 ms,  5.59 GB
[trap-1.0.0-SNAPSHOT-runner:70790]   (typeflow):  19’297.94 ms,  5.59 GB
[trap-1.0.0-SNAPSHOT-runner:70790]    (objects):  22’367.74 ms,  5.59 GB
[trap-1.0.0-SNAPSHOT-runner:70790]   (features):   1’187.49 ms,  5.59 GB
[trap-1.0.0-SNAPSHOT-runner:70790]     analysis:  46’494.62 ms,  5.59 GB
[trap-1.0.0-SNAPSHOT-runner:70790]     universe:   2’547.29 ms,  5.47 GB
[trap-1.0.0-SNAPSHOT-runner:70790]      (parse):   3’572.96 ms,  5.47 GB
[trap-1.0.0-SNAPSHOT-runner:70790]     (inline):  10’216.13 ms,  6.78 GB
[trap-1.0.0-SNAPSHOT-runner:70790]    (compile):  32’642.28 ms,  6.45 GB
[trap-1.0.0-SNAPSHOT-runner:70790]      compile:  50’077.60 ms,  6.45 GB
[trap-1.0.0-SNAPSHOT-runner:70790]        image:   6’756.92 ms,  6.56 GB
[trap-1.0.0-SNAPSHOT-runner:70790]        write:   2’117.38 ms,  6.56 GB
[trap-1.0.0-SNAPSHOT-runner:70790]      [total]: 123’184.54 ms,  6.56 GB
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] objcopy executable not found in PATH. Debug symbols will therefore not be separated from the executable.
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] That also means that resulting native executable is larger as it embeds the debug symbols.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 145343ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:42 min
[INFO] Finished at: 2021-09-23T15:32:57+02:00
[INFO] ------------------------------------------------------------------------
Disconnected from the target VM, address: '127.0.0.1:55197', transport: 'socket'

Process finished with exit code 0
`

**Comment by famod** [comment]
`-Djavax.net.ssl.trustStore` is a standard JDK property and I don't think it's evaluated specifically by Quarkus.

@zakkak what's your take on this?

**Comment by zakkak** [comment]
Hello @matthiasgubler,

> By setting an non existing truststore I would expect the build process to fail with a corresponding error message.

Does your application fail in JVM mode when specifying a non-existing truststore?

**Comment by matthiasgubler** [comment]
@zakkak setting rubbish to a JVM quarkus application also does not lead to an error right away. So it seem to have a similar behaviour like the native version. So it's probably a standard JVM feature ;)

**Comment by famod** [comment]
Thanks for checking.
