### ISSUE TITLE
Set strict version for json-smart

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2037]
The JWT extension as a transitive dependency on JSON Smart. This dependency use a range:

```
 net.minidev:json-smart:jar:2.3:test (version selected from constraint [1.3.1,2.3])
```

Would it be possible to use a strict version? Range leads to update checks that take times.

**Comment by gsmet** [comment]
This is becoming more and more an issue. I had my builds stalled for several minutes today due to Maven Central throttling us.

**Comment by gsmet** [comment]
This has been fixed or is no longer an issue.
