### ISSUE TITLE
quarkus.jib.jvm-entrypoint property doesn't reflect JFR configuration

### ISSUE THREAD

**Issue by oscerd** [quarkusio/quarkus#20384]
### Describe the bug

Suppose you have something like this

`<quarkus.jib.jvm-entrypoint>java,-XX:+UseShenandoahGC,-Xlog:gc,-Xmx64m,-XX:StartFlightRecording=name=Test,settings=/work/jfr/heap.jfc,duration=5m,filename=/work/jfr/output.jfr-jar,/work/quarkus-run.jar</quarkus.jib.jvm-entrypoint>`

The JIBProcessor will translate this to

`[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -XX:+UseShenandoahGC, -Xlog:gc, -Xmx64m, -XX:StartFlightRecording=name=Test, settings=/work/jfr/heap.jfc, duration=5m, filename=/work/jfr/output.jfr-jar, /work/quarkus-run.jar]`

which it's wrong because it is separating the parameters related to JFR

### Expected behavior

Being able to add JFR instructions directly into the quarkus.jib.jvm-endpoint and start JFR correctly.

### Actual behavior

The java process will fail to start because the command is not correctly started

### Additional information

The problem is here: https://github.com/quarkusio/quarkus/blob/main/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L447

**Comment by geoand** [comment]
This isn't really a Quarkus bug - we need a way to separate the string into parts and `,` is the delimiter.

In your case simply changing to:

```
<quarkus.jib.jvm-entrypoint>java,-XX:+UseShenandoahGC,-Xlog:gc,-Xmx64m,-XX:StartFlightRecording=name=Test\,settings=/work/jfr/heap.jfc\,duration=5m\,filename=/work/jfr/output.jfr-jar,/work/quarkus-run.jar</quarkus.jib.jvm-entrypoint>
```

will work

**Comment by oscerd** [comment]
Thanks for the fast response. I think this is something that needs to be supported in a different way. If the Java command become too long it will be more or less impossible to read. Maybe add a property specific for JFR? To inject while forming the java command? Just an idea.

**Comment by geoand** [comment]
I understand the desire, however if we do that, there will be no end the flags we would be requested to support, so I'm not really a fan of this approach

**Comment by lburgazzoli** [comment]
maybe it would be worth thinking about an extension to set-up jfr and related stuffs ?

**Comment by geoand** [comment]
What else would that extension do other than update the property mentioned in this issue?

**Comment by lburgazzoli** [comment]
it could make it easy to integrate with i.e https://cryostat.io

**Comment by geoand** [comment]
I suppose that would be useful. I suggest sending an email to the dev list asking for feedback
