### ISSUE TITLE
Quarkus-Jacoco randomly fails to generate report

### ISSUE THREAD

**Issue by ed-devops-d2** [quarkusio/quarkus#20380]
### Describe the bug

I'm using quarkus-jacoco plugin with Maven. Although most of times it generates the reports under target/jacoco-report/jacoco.xml, sometimes it doesn't, even without modifying the build, just by chance.
I did search and found out other guys talking about EOFException, which indicates that exec file is truncated, but I'm not sure if that's my case here. Any suggestions?

Thanks in advance!

### Expected behavior

It should always generate the reports.

### Actual behavior

A few times randomly it fails and results in target/jacoco-report/error.txt

The error.txt results:

`Failed to generate Jacoco reports java.io.EOFException at java.base/java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345) at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594) at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569) at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:149) at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116) at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93) at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60) at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74) at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72) at java.base/java.lang.Thread.run(Thread.java:829)`

### How to Reproduce?

mvn clean install

### Output of `uname -a` or `ver`

Custom Docker Image: Linux 3.10.0-1127.18.2.el7.x86_64 GNU/Linux

### Output of `java -version`

version "11.0.11" 2021-04-20

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by famod** [comment]
I suppose you are referring to #18571? Are you seeing this in your IDE? If yes, which one?

**Comment by ed-devops-d2** [comment]
#18571 seems a close one. No I'm not, this file is being generated in Jenkins, in this project's workspace. Any ideas?

**Comment by famod** [comment]
@ed-devops-d2 what does your jacoco config look like (both quarkus and maven)?
