### ISSUE TITLE
Enable Junit5 Test-Suites

### ISSUE THREAD

**Issue by ChMThiel** [quarkusio/quarkus#20408]
### Description

Currently it seem not possible to implement Junit5 Test-Suites like shown here:
https://junit.org/junit5/docs/current/user-guide/#junit-platform-suite-engine-example
I would like to use @Suite-Annotation and Filters...
```
import org.junit.platform.suite.api.IncludeClassNamePatterns;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.Suite;

@Suite
@SelectPackages("a.b.c")
@IncludeClassNamePatterns(".*Test")
public class MyTestSuite {

}
```
Quarkus 2.2.1.Final comes with junit-platform-libs (common, engine, launcher) in version 1.7.2.
But it seems that not until version 1.8.1 junit-platform brings @SelectPackages etc.

See zulip-chat https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Junit5.20Test.20Suites/near/255000165

### Implementation ideas

Update JUnit-Platform libraries to version 1.8.1 (or newer)

**Comment by famod** [comment]
`@Suite` was added in JUnit 5.8.0 and Quarkus update to that version in 2.3.0.CR1, so please try it with that version (or wait for 2.3.0.Final).

**Comment by rsvoboda** [comment]
@ChMThiel can check the latest Quarkus?

**Comment by ChMThiel** [comment]
I tried it with Quarkus 2.4.1 ....still @Suite annotatione TestSuites not working (see above)
Any Ideas?

**Comment by famod** [comment]
So far, it seems nobody had the capacity to take a closer look.

/cc @geoand @stuartwdouglas

**Comment by ChMThiel** [comment]
If i don't use @Suite-Classes but use groups-property in the surefire-plugin, Tag-filtering works fine. (see https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html -> "Filtering by Tags")

**Comment by stuartwdouglas** [comment]
If you run with `-e` you get the following: ` [[engine:junit-platform-suite]/[suite:org.acme.TestSuite]/[engine:junit-platform-suite]/[suite:org.acme.TestSuite]]`.

The issue is that `@SelectPackages` is recursive because the suite is in the selected packages. Move the suite class outside this package structure and it appears to work fine.

Not sure if this is intentional or not, but this is nothing to do with Quarkus.
