### ISSUE TITLE
quarkus.hibernate-orm.log.bind-parameters does not work

### ISSUE THREAD

**Issue by arunkjn** [quarkusio/quarkus#20413]
I am following the documentation at https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.log.bind-parameters which specifies the property `bind-parameters`. But this property does not work with quarkus `2.2.3.Final`.

I get the log saying 

>  Unrecognized configuration key "quarkus.hibernate-orm.log.bind-parameters" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

**Comment by geoand** [comment]
I could not reproduce this, for me the parameter worked as expected.
Can you add your example application to github and link it to the issue?

**Comment by yrodiere** [comment]
Maybe that's what you get when setting the property at runtime?

Strangely, this is a build-time-only property and it cannot be changed at runtime. I wonder why, though?

**Comment by gsmet** [comment]
Looks like it's working and we didn't have any more info so closing.
