### ISSUE TITLE
Kubernetes example needs clarification

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkus#2041]
In https://quarkus.io/guides/kubernetes-guide.html at the start it says "First, you need to push the Docker image (created in the previous guide) to the image registry of your Kubernetes cluster. Depending on your cluster, there are several ways. "

Now at first glance this suggests building off the previous example and picking up from where we left off. If that is the case then the code example "docker build -f src/main/docker/Dockerfile -t quarkus-quickstart/quickstart ." is invalid as there's no Dockerfile at that stage, but Dockerfile.native or Dockerfile.jvm 

If the original statement wants the reader to start again from a clean slate then let's make that clearer along with the steps they need to take.

**Comment by gsmet** [comment]
@geoand looks similar to what we just discussed. Could you scan the guides to be sure everything is consistent with your quickstart PR introducing the proper Dockerfiles?

Thanks!

**Comment by geoand** [comment]
@gsmet PR: https://github.com/quarkusio/quarkus-quickstarts/pull/152 should fix the Dockerfiles for all the quickstarts.

**Comment by geoand** [comment]
@gsmet I also opened: https://github.com/quarkusio/quarkus/pull/2042, which I believe should address this issue when taken together with the PR in the quickstarts.

**Comment by gsmet** [comment]
Fixed via the 2 PRs mentioned above. Will be part of the next release.
