### ISSUE TITLE
Default Produces or Consumes annotations crash quarkus

### ISSUE THREAD

**Issue by XakepSDK** [quarkusio/quarkus#20432]
### Describe the bug

If i annotate class with empty `Produces` or `Consumes`, quarkus fails to start

### Expected behavior

Quarkus starts

### Actual behavior

Quarkus fails

### How to Reproduce?

1. Create Resource
2. Annotate class with `@Produces` and/or `@Consumes` without changing it's value
3. Create one or more endpoints without `Produces` or `Consumes` annotations, with `Path` annotation
4. Start quarkus
5. It crashes

### Output of `java -version`

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment (build 16.0.2+7) OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.2

**Comment by geoand** [comment]
Thanks for reporting, but we'll need more information.

What extensions are you using? Does this problem still occur with `2.2.3.Final` or `2.3.0.CR1`?

**Comment by gsmet** [comment]
No information given, let's close.
