### ISSUE TITLE
Exceptions ignored when writing repsonse with VertxBlockingOutput.java

### ISSUE THREAD

**Issue by gmagnu** [quarkusio/quarkus#20458]
### Describe the bug

I am using StreamingOutput to send large response body to the client.  If the client closes the connection while the server is writing the server will not get any exception and the  data written by the server will vanish into the aether.

- This happens in all versions after Quarkus 2.0.0.
- This does not happen for HTTP/2.
- This hapens when using the blocking call.

I believe that I have tracked this down to the io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.java:82 (`request.response().write(createBuffer(data));`)

The whole method is:

```
@Override
    public void write(ByteBuf data, boolean last) throws IOException {
        if (last && data == null) {
            request.response().end();
            return;
        }
        try {
            //do all this in the same lock
            synchronized (request.connection()) {
                try {
                    awaitWriteable();
                    if (last) {
                        request.response().end(createBuffer(data));
                    } else {
                        request.response().write(createBuffer(data));
                    }
                } catch (Exception e) {
                    if (data != null && data.refCnt() > 0) {
                        data.release();
                    }
                    throw new IOException("Failed to write", e);
                }
            }
        } finally {
            if (last) {
                terminateResponse();
            }
        }
    }
```

To me it looks like after the Vert.x 4 update the exception handling is missing.  After the update to 4 the `request.response().write` does not throw an exception but returns a Vertx future that needs to be checked for success/failure/throwable.

### Expected behavior

When the client closes the connection while the server is writing the response we should get:

`new IOException("Failed to write", e)`

### Actual behavior

When the client closes the connection while the server is writing the response  we get no exception and the server just continues to write its output to the aether.

### How to Reproduce?

I don't have a code example but:
1. Setup up server that returns large output as StreamingOutput (maybe infinite output).
2. Connect with the client using HTTP/1.1 and call the method.
3. Kill the client.
4. Notice the server method will just continue to write to the StreamingOutput without getting the expected error.

### Output of `uname -a` or `ver`

Darwin RKV-MBP-Gisli.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19

### Quarkus version or git rev

2.2.3.Final

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
The ‘write’ method is async. So you need to attach callbacks to returned Future to know when the write completed successfully or failed. 

You may want to use .toCompletionStage().toCompletableFuture().join(), it will throws the exception BUT it will block.
