### ISSUE TITLE
Kubernetes example doesn't work as outlined in Quickstart

### ISSUE THREAD

**Issue by nmcl** [quarkusio/quarkus#2045]
Again referring to https://quarkus.io/guides/kubernetes-guide.html

Tried "docker build -f src/main/docker/Dockerfile -t quarkus-quickstart/quickstart ." with Dockerfile replaced with Dockerfile.jvm and Dockerfile.native

Then following the commands in the rest of the guide:

kubectl run quarkus-quickstart --image=quarkus-quickstart/quickstart:latest --port=8080 --image-pull-policy=IfNotPresent
deployment.apps "quarkus-quickstart" created

kubectl expose deployment quarkus-quickstart --type=NodePort
service "quarkus-quickstart" exposed

Then ...

curl $(minikube service quarkus-quickstart --url)/hello/quarkus
RESTEASY003210: Could not find resource for full path: http://192.168.99.100:30286/hello/quarkus

And hitting that URL in a browser produces the same result.

For the record, am running on Mac OS 10.13.6 with latest minikube 1.0.0 (installed via homebrew)

**Comment by gsmet** [comment]
Could you try with `curl $(minikube service quarkus-quickstart --url)/hello/greeting/quarkus`?

I think it's just the URL that is invalid in the guide.

If you confirm it works, I'll go fix the guide.

**Comment by nmcl** [comment]
Nope. Tried it and get:

RESTEASY003210: Could not find resource for full path: http://192.168.99.100:31505/hello/greeting/quarkus

**Comment by geoand** [comment]
Let me give it a tr

**Comment by nmcl** [comment]
/hello works, i.e., curl $(minikube service quarkus-quickstart --url)/hello returns hello. But is that correct?

**Comment by geoand** [comment]
Both `/hello` and `/hello/greeting/whatever` should work according to the code: https://github.com/quarkusio/quarkus-quickstarts/blob/master/getting-started/src/main/java/org/acme/quickstart/GreetingResource.java#L12

**Comment by nmcl** [comment]
The GreetingResource generated by the quickstart doesn't have /whatever in it but does have /hello which is how I determined /hello should work. Here's the code I see for completeness:

package org.acme.quickstart;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}

**Comment by geoand** [comment]
So that solves the mystery then! We have extra code in the quickstart that is not mentioned anywhere is the guide. I guess we should just use `/hello` to make things easier and keep focus on the Kubernetes stuff instead of requiring users to add more code. WDYT @nmcl @gsmet ?

**Comment by nmcl** [comment]
Fine with me. Thanks.

**Comment by geoand** [comment]
Great! @gsmet feel free to review the relevant PR I opened, thanks!
