### ISSUE TITLE
tcnative.version undefined in quarkus-bom

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#20461]
### Describe the bug

The root cause is that `tcnative.version` is undefined in `netty-bom` (see https://github.com/netty/netty/issues/11691 ).
The flattened `quarkus-bom` just blindly takes  the issue over from there.

As a result of this, we are getting build errors like the following in Camel Quarkus:

```
[ERROR] Failed to execute goal on project camel-quarkus-integration-test-azure-grouped: Could not resolve dependencies for project org.apache.camel.quarkus:camel-quarkus-integration-test-azure-grouped:jar:2.3.0-SNAPSHOT: Failure to find io.netty:netty-tcnative-boringssl-static:jar:${tcnative.version} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

I wonder whether it would help to temporarily add `<tcnative.version>2.0.43.Final</tcnative.version>` to quarkus-bom till the issue gets resolved in `netty-bom`?

**Comment by ppalaga** [comment]
> I wonder whether it would help to temporarily add `<tcnative.version>2.0.43.Final</tcnative.version>` to quarkus-bom till the issue gets resolved in `netty-bom`?

I tried that and no it does not help. `flatten-platform-bom` mojo ignores it. 

@aloubyansky I wonder whether there is a better option than an ad hoc fix in `FlattenPlatformBomMojo`?

**Comment by ppalaga** [comment]
`FlattenPlatformBomMojo` should perhaps check that there are no unresolved props leaking into the flattened BOM.

**Comment by aloubyansky** [comment]
@ppalaga could you override it in Camel? The platform build will pick it up from your BOM.

**Comment by ppalaga** [comment]
> could you override it in Camel? 

Yes, we do that. But it is still causing problems when quarkus-bom is imported before camel-quarkus-bom in our tests. 
We want to have both, so that our QE can test against the platform BOM by overriding the BOM GAVs on the CLI see here: https://github.com/apache/camel-quarkus/pull/3134/files#diff-0e4c80d88a91a573b5842760520c42f78432a36c36c2afe88e15fc9dfe0eb531R33-R48
Putting camel-quarkus-bom before quarkus-bom helps, but could potentially introduce other issues https://github.com/apache/camel-quarkus/pull/3134/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R61-R67

**Comment by aloubyansky** [comment]
Would temporarily putting the tcnative constraints before both BOM imports be ok until we and/or netty fix it properly though?

**Comment by ppalaga** [comment]
Let's see whether whether all our tests are going to pass with camel-quarkus-bom before quarkus-bom. If so, the reordering of the BOMs would be an acceptable workaround.

**Comment by gsmet** [comment]
This has been fixed.
