### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by weolopez** [quarkusio/quarkus#2048]
Simple feature request to support mongodb.  

I may end up creating our own extension following: https://quarkus.io/guides/writing-native-applications-tips

If I do, I'll update this issue with progress.

**Comment by geoand** [comment]
cc @evanchooly

**Comment by cescoffier** [comment]
There is work in progress in this area.

**Comment by tpenakov** [comment]
Is it possible to port and reactive mongo client too?

**Comment by emmanuelbernard** [comment]
@cescoffier is that the issue you use for the MongoDB work? That's the one I added to the 1.0 project
