### ISSUE TITLE
Class PostgreSQL10Dialect not found on Quarkus in Google App Engine java11?

### ISSUE THREAD

**Issue by tares42** [quarkusio/quarkus#20492]
### Describe the bug

I wanted to deploy my quarkus application including hibernate panache to GCP app engine standard and got the error: Class PostgreSQL10Dialect not found on Quarkus

### Expected behavior

Successful startup of quarkus on GCP app engine standard

### Actual behavior

I've set up my quarkus application regarding to https://quarkus.io/guides/deploying-to-google-cloud 
Created a Cloud SQL instance.
And happily deployed the java11 app the first time to GAE. :-)

But - on startup quarkus fails with this reason:
```
	Caused by: java.lang.ClassNotFoundException: org.hibernate.dialect.PostgreSQL10Dialect 
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
```

Looking at the jar:
```
$ jar tvf foodie-1.0-SNAPSHOT-runner.jar | fgrep PostgreSQL10Dialect
  1184 Tue Sep 28 20:12:07 CEST 2021 io/quarkus/hibernate/orm/runtime/dialect/QuarkusPostgreSQL10Dialect.class
   990 Tue Sep 28 20:12:08 CEST 2021 org/hibernate/dialect/PostgreSQL10Dialect.class
```

Any hints how to proceed?

application.properties:
```
quarkus.package.type=uber-jar
quarkus.datasource.db-kind=other 
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql:///quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql:///quarkus
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.additional-jdbc-properties.cloudSqlInstance=addlogic-foodiefnf-1:europe-west3:quarkus 
quarkus.datasource.jdbc.additional-jdbc-properties.socketFactory=com.google.cloud.sql.postgres.SocketFactory
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect 
```

Extract from pom.xml:
```
		<maven.compiler.target>11</maven.compiler.target>
		<quarkus-plugin.version>2.2.3.Final</quarkus-plugin.version>
		<quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
		<quarkus.platform.version>2.2.3.Final</quarkus.platform.version>
		<postgres-socket-factory.version>1.3.3</postgres-socket-factory.version>
[...]
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-postgresql</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-orm-panache</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.cloud.sql</groupId>
			<artifactId>postgres-socket-factory</artifactId>
			<version>${postgres-socket-factory.version}</version>
		</dependency>
```

Sidenote on deployment?
----------------------------
How to investigate this warning on ´mvn clean package appengine:deploy´?

```
[INFO] Staging the application to: D:\eclipse\eclipse-workspace\code-with-quarkus\target\appengine-staging
[INFO] Detected App Engine app.yaml based application.
Okt. 01, 2021 8:08:38 AM com.google.cloud.tools.appengine.operations.AppYamlProjectStaging copyArtifactJarClasspath
WARNING: Could not copy 'Class-Path' jar: D:\eclipse\eclipse-workspace\code-with-quarkus\target referenced in MANIFEST.MF
```

Just a sidenote as deployment with `gcloud app deploy target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar` gives no WARNINFS and has same effects.

Alternative with mysql is functioning
=====================================
I've tried an alternative with mysql, which is functioning in the same MCVE and another testing project which I have set up.

pom.xml
```
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-mysql</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.cloud.sql</groupId>
			<artifactId>mysql-socket-factory-connector-j-8</artifactId>
			<version>1.3.3</version>
		</dependency>
```

application.properties
```
# https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-mysql.md
quarkus.datasource.db-kind=other 
quarkus.datasource.jdbc.url=jdbc:mysql:///quarkus 
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.username=root
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.additional-jdbc-properties.cloudSqlInstance=addlogic-foodiefnf-1:europe-west3:quarkusmysql
quarkus.datasource.jdbc.additional-jdbc-properties.socketFactory=com.google.cloud.sql.mysql.SocketFactory
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL8Dialect
```

***So this makes me more curious why it is not working with PostgreSQL.***

### How to Reproduce?

An MCVE reproducer project can be found at 
`git@gitlab.com:addlogic/code-with-quarkus.git#`

See README for reproduction steps.

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0 levante2b 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin

### Output of `java -version`

$ java -version java version "11.0.11" 2021-04-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.1

**Comment by tares42** [comment]
How to investigate this warning on ´mvn clean package appengine:deploy´?

```
[INFO] Staging the application to: D:\eclipse\eclipse-workspace\code-with-quarkus\target\appengine-staging
[INFO] Detected App Engine app.yaml based application.
Okt. 01, 2021 8:08:38 AM com.google.cloud.tools.appengine.operations.AppYamlProjectStaging copyArtifactJarClasspath
WARNING: Could not copy 'Class-Path' jar: D:\eclipse\eclipse-workspace\code-with-quarkus\target referenced in MANIFEST.MF
```

**Comment by gsmet** [comment]
@loicmathieu could you have a look at this one and check if it's still an issue?

**Comment by loicmathieu** [comment]
I'll try to reproduce it (tomorrow or next week).

**Comment by loicmathieu** [comment]
Hi,
I tested you reproducer and it works for me on appengine after a small correction.
In your application.properties, the dialect has a trailing space, that why the class is not found because it tries to load the `org.hibernate.dialect.PostgreSQL10Dialect ` class and not the `org.hibernate.dialect.PostgreSQL10Dialect` one.

**Comment by loicmathieu** [comment]
@tares42 please can you try to remove the trailing space and confirm it work on your side ?
I also answer on StackOverFlow.

**Comment by gsmet** [comment]
I'm working on improving the Hibernate ORM config to trim the values automatically where it makes sense.

**Comment by loicmathieu** [comment]
This would be great.
I remember being bit by this mistake once myself

**Comment by tares42** [comment]
> @tares42 <https://github.com/tares42> please can you try to remove the
trailing space and confirm it work on your side ?
> I also answer on StackOverFlow.

Thank you very much for the investigation and your work.

I will test it on next weekend.



Am Di., 11. Jan. 2022 um 21:46 Uhr schrieb Loïc Mathieu <
***@***.***>:

**Comment by tares42** [comment]
With removing the trailing space it works now!
That you very much for your investigation and help!
