### ISSUE TITLE
Jackson JQ support

### ISSUE THREAD

**Issue by ricardozanini** [quarkusio/quarkus#20504]
### Description

This extension aims to add [jq](https://stedolan.github.io/jq/manual/) expressions to a Quarkus application. It's backed by [jackson-jq](https://github.com/eiiches/jackson-jq) library. The extension is already done. I need to migrate it to the Quarkiverse format. You can see the code here: https://github.com/ricardozanini/jackson-jq/pull/1/files

### Configuration suggestion

The usage is pretty straightforward, won't require any additional properties for now.

### Additional context

Users will have the `Scope` bean available for injection. `Scope` is the entry point of Jackson JQ library, as demonstrated in their examples of usage:

Here's a simple use case. A REST endpoint that's capable of executing a `jq` expression and return its output:

```java
 @Path("/parser")
 @Produces(MediaType.APPLICATION_JSON)
 @Consumes(MediaType.APPLICATION_JSON)
 public class ParserResource {

     @Inject
     Scope scope;

     @POST
     public List<JsonNode> parse(Document document) throws JsonQueryException {
         final JsonQuery query = JsonQuery.compile(document.expression, Versions.JQ_1_6);
         List<JsonNode> out = new ArrayList<>();
         query.apply(this.scope, document.document, out::add);
         return out;
     }

     public static class Document {

         private String expression;
         private JsonNode document;

         public JsonNode getDocument() {
             return document;
         }

         public void setDocument(JsonNode document) {
             this.document = document;
         }

         public String getExpression() {
             return expression;
         }

         public void setExpression(String expression) {
             this.expression = expression;
         }
     }
 }
```

**Comment by geoand** [comment]
cc @gastaldi

**Comment by maxandersen** [comment]
so `io.quarkiverse.quarkus-jackson-jq`?

**Comment by maxandersen** [comment]
eh ...how :) I already pushed and the team is missing?

**Comment by maxandersen** [comment]
anyhow https://github.com/quarkiverse/quarkus-jackson-jq is now there with code - creating team now

**Comment by maxandersen** [comment]
@ricardozanini repo is setup; just awaiting you to ack the invite.

Please see https://github.com/quarkiverse/quarkiverse/wiki#getting-an-extension-onboarded for next step(adding code and setting on the ci)

**Comment by ricardozanini** [comment]
Thanks, guys! I'll start tweaking the code and will open the PR ASAP.

**Comment by ricardozanini** [comment]
PR: https://github.com/quarkiverse/quarkus-jackson-jq/pull/1/

**Comment by ricardozanini** [comment]
CI PR: https://github.com/quarkusio/quarkus-ecosystem-ci/pull/66
