### ISSUE TITLE
Missing JAX-B guide

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#20519]
### Describe the bug

XML serialization is supported via JAX-B but no guide exist.
We could create a "WRITING XML REST SERVICES" close to the JSON one: https://quarkus.io/guides/rest-json

**Comment by gsmet** [comment]
Frankly, I don't see us spending time writing a JAXB guide given there's nothing really specific except for the extension. So I will close this issue. If someday, someone wants to create one, just create a pull request with it and we will pursue from there.
