### ISSUE TITLE
Add Flyway quickstart and docs section

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#2051]
Currently, Flyway is supported but no quickstart (https://github.com/quarkusio/quarkus-quickstarts) example nor a section in the documentation. I think it will be great to have.

If you agree, please assign me the issue and I'll work on this providing a PR in both projects.

**Comment by gsmet** [comment]
We have a start of something here: https://quarkus.io/guides/flyway-guide .

Feel free to add more information if you think they are needed.

**Comment by lordofthejars** [comment]
Isn't supported in Quarkus that you add the dependency and then the migration happens automatically?

**Comment by cristhiank** [comment]
Hi @lordofthejars actually I'm working on getting this done. Will be pushing the code soon. 
See https://github.com/quarkusio/quarkus/issues/1925

**Comment by lordofthejars** [comment]
Great, then I close this issue.
