### ISSUE TITLE
Update documentation regarding mutable-jar

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus#20528]
### Description

https://quarkus.io/guides/maven-tooling#remote-development-mode mentions a possibility of building a `mutable-jar`  - the option value is missing under https://quarkus.io/guides/maven-tooling#quarkus-package-pkg-package-config_quarkus.package.type

Also it could be worth mentioning (based on my experience with this feature), that the configuration must be made in `application.property` and no other way will work (e.g. `mvn clean package -Dquarkus.package.type=mutable-jar`) - unless there is a way to build `fast-jar` by default and `mutable-jar` via additional command line parameters / without modifying `application.properties`?

**Comment by geoand** [comment]
`mutable-jar` is a rather advanced feature that is useful for a very specific use case, so I am not sure it's worth mentioning in the config page you mention, as it would give users the sense that it's generally useful.
