### ISSUE TITLE
Eureka discovery service with Quarkus

### ISSUE THREAD

**Issue by BechirLandolsi** [quarkusio/quarkus#2052]
Hello, I'm a big fan of RedHat products and recently I discovered the new native java framework "Quarkus". I want to use it in a microservice architecture, is it possible to use a quarkus microservice with Netflix Eureka for the discovery client? Thank u :)

**Comment by geoand** [comment]
Hi, there is no built in Eureka support in Quarkus. Quarkus mainly targets Kubernetes environments where no discovery service is needed because plain old DNS works out of the box when using the service name.

**Comment by tpenakov** [comment]
I've created a bare minimum Eureka Client which works on Quarkus: 
https://github.com/tpenakov/org-otaibe-eureka-client
It is not build as Quarkus extension, but you can embed the code in your project.

**Comment by tpenakov** [comment]
The Quarkus Based Eureka Client is rewritten as a library now: [otaibe-commons-quarkus project](https://github.com/tpenakov/otaibe-commons-quarkus)
I will continue to support and the [Standalone Quarkus Based Eureka Client](https://github.com/tpenakov/org-otaibe-eureka-client)

**Comment by fmcejudo** [comment]
Hi, recently we have released a Quarkus extension to integrate with Eureka, which covers a good bunch of features. You might want to take a look and see if this helps you in your projects.

The coordinates of the github project are:
https://github.com/fmcejudo/quarkus-eureka
where you can find how to use it.

and the dependency can be found at:
https://search.maven.org/artifact/com.github.fmcejudo/quarkus-eureka-parent/0.0.4/jar

**Comment by geoand** [comment]
Thanks for the input and your works @tpenakov @fmcejudo !

**Comment by fmcejudo** [comment]
sure @rsvoboda , I will take a look and happy to share it in quarkus ecosystem. I will contact you if I have any problem, can I? 
Thanks.

**Comment by geoand** [comment]
@fmcejudo feel free to ping me if you have any problems with ecosystem-ci

**Comment by florent-lb** [comment]
I'm really fan to have this feature to quarkus, will you propose a synergy with microprofile rest client in future ? (like openFeign )?

**Comment by kenfinnigan** [comment]
@florent-lb I don't think MP REST Client would integrate with Eureka because MP REST Client expects to be in a container type environment

**Comment by SelimHorri** [comment]
Hi @fmcejudo,
Is there any demo so to check your library consistency plz !?
Kindest,

**Comment by fmcejudo** [comment]
Hi @SelimHorri , sure I did this as example:

https://github.com/currofy/coffee-shop-parent

Check it out and if you have any issue, don't hesitate to contact me

**Comment by SelimHorri** [comment]
@fmcejudo, sure, i'll try it later and get back to you soon
Thank you

**Comment by srigano** [comment]
hi,
@fmcejudo : nice extensions!
could you please build it for Quarkus 2.6.1.Final?

**Comment by geoand** [comment]
Closing this as we won't be adding Eureka support to Quarkus Core
