### ISSUE TITLE
Update docs how to read a config value outside resource class

### ISSUE THREAD

**Issue by tehnodev** [quarkusio/quarkus#20520]
### Description

I do not understand how to read a config value in a class without [Path annotation](https://quarkus.io/guides/spring-cloud-config-client#greetingcontroller)
I have a class
```
public class Hello {
    @ConfigProperty(name = "greeting.name")
    String name;

    public String greeting() {
        return "Hello " + name;
    }
}
```

In application.properties
`greeting.name=John`

When i use it, i get "Hello null" instead of "Hello John"
```
@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return new Hello().greeting();
    }
}
```

### Implementation ideas

Please update documentation with additional example

**Comment by geoand** [comment]
I would suggest reading: https://quarkus.io/guides/config

For your use case, you essentially need to do something like:

```java
@Singleton
public class Hello {
    @ConfigProperty(name = "greeting.name")
    String name;

    public String greeting() {
        return "Hello " + name;
    }
}

@Path("/hello")
public class GreetingResource {

    @Inject
    Hello hello;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return hello.greeting();
    }
}
```
