### ISSUE TITLE
Quakrus CLI: --help command for 'create' is not working

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#20522]
### Describe the bug

Quakrus CLI for 999-SNAPSHOT fails with:

_Creating an app (default project type, see --help).
[ERROR] ❗  Unable to create project: Unknown option: '--help'_

when running:
java -jar $home/quarkus-main/devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar registry --help

### Expected behavior

Help for "create" command should appear

### Quarkus version or git rev

999-SNAPSHOT

**Comment by ebullient** [comment]
you're right. I know how I broke it. Two seconds. Thanks for catching that!
