### ISSUE TITLE
Hibernate Reactive Panache guide missing documentation on `@TestReactiveTransaction`

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#20521]
### Describe the bug

The [Quarkus Hibernate Reactive Panache guide](https://quarkus.io/guides/hibernate-reactive-panache) does not have any information on the existence of the `@TestReactiveTransaction` annotation nor how to use it.

Maybe it doesn't belong in that guide because it isn't specific to Panache Reactive and its more generic to reactive transaction management. That being said, it still isn't discussed anywhere in the guides. I think, too, more is needed than a sentence or two just saying that its there. I think there need to be some examples that show how to use it.

Furthermore, the [Tests and transactions](https://quarkus.io/guides/getting-started-testing#tests-and-transactions) section of the getting started testing guide is pretty weak. I think both need to be expanded on somewhere.

Maybe there needs to be a guide or something that talks about transaction management in general?

**Comment by gsmet** [comment]
@DavideD could you have a look at this one? It looks like something we could quickly fix and be done with.

**Comment by DavideD** [comment]
Yes, I will have a look at it

**Comment by DavideD** [comment]
Can somebody assign this issue to me, please?

**Comment by loicmathieu** [comment]
Done ;)

**Comment by DavideD** [comment]
Thanks

**Comment by mkouba** [comment]
Hm, it seems that when I use `@TestReactiveTransaction` in my test I can't use `Uni.await()` inside the test method anymore; it results in `java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-15`... So what's the idiomatic way of asserting some reactive code?

**Comment by edeandrea** [comment]
There are also some examples in the superheros sample app - https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-heroes/src/test/java/io/quarkus/sample/superheroes/hero/repository/HeroRepositoryTests.java

**Comment by DavideD** [comment]
>  So what's the idiomatic way of asserting some reactive code?

You can use Vert.x unit: https://vertx.io/docs/vertx-unit/java/#_introduction

**Comment by DavideD** [comment]
It integrates with JUnit: https://vertx.io/docs/vertx-unit/java/#_junit_integration

**Comment by edeandrea** [comment]
Isnt `@Rule` from JUnit 4?

**Comment by edeandrea** [comment]
@mkouba to use @TestReactiveTransaction` your test has to be non-blocking, which `Uni.await()` is inherently blocking.

If you want to go that route (or use the `UniAssertSubscriber` - some examples of that are in https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-heroes/src/test/java/io/quarkus/sample/superheroes/hero/service/HeroServiceTests.java) then you can't use the annotation and instead will have to implement your own cleanup within each test.

**Comment by DavideD** [comment]
For JUnit 5: https://vertx.io/docs/vertx-junit5/java/#_integration_with_junit_5

**Comment by edeandrea** [comment]
Quarkus also has `@RunOnVertxContext` (for which I can't seem to find much documentation either).

**Comment by mkouba** [comment]
> to use `@TestReactiveTransaction` your test has to be non-blocking, which `Uni.await()` is inherently blocking.

I know but it's a bit confusing as you can do `Uni.await()` if no `@TestReactiveTransaction` is present, because the test method body is executed on the `main` thread and only the panache entity/repository operations is executed on the event loop (see also `io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession()`).

**Comment by FroMage** [comment]
This looks like something we should document. I did run into the issue too myself.
