### ISSUE TITLE
[quarkus-quartz] `cron` expression of `@Scheduled` is not updated via ENV (overwriting application.properties)

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus#20538]
### Describe the bug

Given
* `@Scheduled(identity = "aJob", cron = "{a.job.schedule.cron}")` in code
* `a.job.schedule.cron=0 0 1 * * ? *` in application.properties and
* `A_JOB_SCHEDULE_CRON=0 0 1 * * ? 2100` in ENV

if the application has been started prior without the ENV part, restarting the application with ENV doesn't update the field `cron_expression` in the table `qrtz_cron_triggers`.

if the application has not been started prior without the ENV part, starting it the first time with ENV leads to `cron_expression` being filled with the cron expression from ENV, not from application.properties (as expected).

### Expected behavior

Field `cron_expression` in the table `qrtz_cron_triggers` is updated.

Alternatively, this behaviour is documented on the https://quarkus.io/guides/quartz and there is a way to overwrite existing cron expressions using ENV.

### Actual behavior

Field `cron_expression` in the table `qrtz_cron_triggers` is not updated.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1766]

### Output of `java -version`

11.0.10

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by mkouba** [comment]
Just to be clear - you're using `quarkus.quartz.store-type=jdbc-tx` or `jdbc-cmt`, i.e. qartz jobs and triggers are persisted in the DB. Is `quarkus.quartz.clustered` set to `true`? TBH I'm not sure it's possible to update a job trigger in similar use cases. 

@machi1990 Could it be a `JDBCJobStore` limitation?

**Comment by coiouhkc** [comment]
Hi @mkouba , right
`
quarkus.quartz.clustered=true
quarkus.quartz.store-type=jdbc-cmt
`

**Comment by machi1990** [comment]
> Just to be clear - you're using `quarkus.quartz.store-type=jdbc-tx` or `jdbc-cmt`, i.e. qartz jobs and triggers are persisted in the DB. Is `quarkus.quartz.clustered` set to `true`? TBH I'm not sure it's possible to update a job trigger in similar use cases.
> 
> @machi1990 Could it be a `JDBCJobStore` limitation?

I think it could be related to the way we schedule jobs for quartz and it is to be expected. If the trigger expression changes, the new trigger is not rescheduled: current we only schedule new jobs: https://github.com/quarkusio/quarkus/blob/bdce87ffc26bf6d82055d813e76775c067c54646/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L198-L202

So the bug is expected, by the way any change in the cron expression / trigger expression could result in the bug not only ENV changes. I've a quick fix which will add the rescheduling part but I'd like @coiouhkc to have a test.

**Comment by coiouhkc** [comment]
I've built the partial `999-SNAPSHOT` with `mvn install -DskipTests -am -pl :quarkus-quartz`, replaced `quarkus-quartz` version in the guided application and it worked like a charm:
* restarting with updated `application.properties` worked and updated the cron definition in the DB
* restarting with updated `application.properties` and additional ENV took proper precedence and updated the cron definition in the DB according to ENV

**Comment by apat59** [comment]
I may be wrong but I think this is introducing a new bug.
While running in a cluster, jobs will be rescheduled anytime you scale up (new pod) your app right?

So imagine your start your app with few jobs running on start and supposed to run every 24h.
If you scale up, all jobs are going to be rescheduled, and ran immediately, which is not what you want.
