### ISSUE TITLE
Issue with Quarkus to connect with Redis Client

### ISSUE THREAD

**Issue by mohansidda** [quarkusio/quarkus#20532]
### Describe the bug

My customer is trying the Quarkus framework to connect with Redis Client for enabling the ACL features. They have encountered the following errors:**ERR Client sent AUTH, but no password is set**

### How to Reproduce?

Create Quarkus to connect with Redis with ACL following the steps described here [1],[2]

[1] https://quarkus.io/guides/redis
[2] https://docs.redis.com/latest/rc/security/database-security/passwords-users-roles/

### Quarkus version or git rev

2.0.0

**Error:**
![Error](https://user-images.githubusercontent.com/23397435/136127944-2c9045a4-2829-4d73-8bb5-4e39830324da.png)

**Config:**
![config](https://user-images.githubusercontent.com/23397435/136127992-868f65c2-60f6-40ba-8821-e789c86ee56e.png)

**Code Snippet:**

![image001 (1)](https://user-images.githubusercontent.com/23397435/136331136-db6e3d10-1224-4fee-b585-d9fd95a7e517.png)

**Comment by cescoffier** [comment]
@pmlopes do you know if we have a vert.x example somewhere?

**Comment by pmlopes** [comment]
@mohansidda can you share the redacted connection string you're using?

I'd expect to see something like:

```
redis://:password@server[:port/db]
```

What is important to see is that your connection string is like:

```
|---- This is important as redis before 6 had no user, just password
v
:password
```

Also can you share the redis version you're trying to connect, because only in 6 true `ACL` was introduced: https://redis.io/topics/acl

**Comment by mohansidda** [comment]
HI, this is the update I received from the customer: 

Tried out the configuration below wherein “no user” (sc1). The app is able to connect using the user “default” (sc2).

For Redis there are is an ACL authentication introduced with 6.x. This is based on having multiple roles (sc3).

 

With Redis Quarkus Library, would like to understand what are the application properties or configurations to use Redis with ACL. (https://redis.io/topics/acl)

 

Hope this clears things out. Let me know if you require further details.

Sc1:
![sc1](https://user-images.githubusercontent.com/23397435/136127789-fe843d4b-23cb-4e04-94c0-8a872224b1ec.png)

Sc2:
![sc2](https://user-images.githubusercontent.com/23397435/136127804-07ecfb83-fd86-4e81-bb8a-fdff8003b9f8.png)

Sc3:
![sc3](https://user-images.githubusercontent.com/23397435/136127821-43d568bd-369e-4e0d-b2a1-d78501a6dafa.png)

**Comment by machi1990** [comment]
> As per the code snippet provided by @pmlopes, it is connected using vert.x client.

@mohansidda 
The reason I said it should work is that, the quarkus redis client is built on top of the vert.x redis client. In addition to the clients that were used in the redis guide, the redis extension exposes the following clients:
- `MutinyRedis` - io.quarkus.redis.client.runtime.MutinyRedis
- `MutinyRedisAPI` - io.quarkus.redis.client.runtime.MutinyRedisAPI
- `Redis` -  io.vertx.redis.client.Redis, like the one used by @pmlopes in the snipped
- `RedisAPI` - io.vertx.redis.client.RedisAPI;

All these clients can be used in your Quarkus application. 

> For the issue application is encountering, it is using Quarkus Redis client. Could you please try the quarkus redis client if it is supporting ACL features for Redis?

Yes. Below is the snipped code of using acl with the `MutinyRedis` API. 

I've the following configuration properties
```
quarkus.redis.hosts=redis://localhost:6379 # this will be used to create a normal client to set the ACL
quarkus.redis.user1.hosts=redis://user1:password@localhost:6379 # this will be used to create a client limited to perform operations on specific keys
```
The API is injected like
```java
@Inject
MutinyRedis redis;
```

and it is then used like:

```java
// create a user using the "io.quarkus.redis.client.runtime.MutinyRedis" redis client
// the user can access only the bar key
// the client is injected via 
// @Inject MutinyRedis redis
// it is using the connection properties set on application.properties

redis.send(Request.cmd(Command.ACL).arg("SETUSER").arg("user1").arg(">password").arg("on").arg("allcommands").arg("~bar*")).await().indefinitely();
        
// create a RedisClient with that user
// the connection string is on the application.properties file 
// i.e quarkus.redis.user1.hosts=redis://user1:password@localhost:6379 # I am on localhost
var alice = RedisClient.createClient("user1");
// verify that the user can ping
alice.ping(List.of());

// get will pass since the user can access the "bar" key
alice.get("bar");

// get will fail since the user has no permission to access the "foo" key
alice.get("foo");
```

Hope that helps.

Going back to my earlier ask

> Just to make sure I understand the issue, are you seeing any issue with connecting to the Redis server using a connection string that has both the username and password hence the ERR Client sent AUTH, but no password is set error in the issue description ? Or you are asking how to use the ACL Redis command with the RedisClient?

I am still unsure of the ask. If it is the `ERR Client sent AUTH, but no password is set error` or if  The `RedisClient` and `ReactiveRedisClient` exposes the ACL command. If it is the former, then I'd be very surprised and in that case I can use a small reproducer to see why that error is occurring. But I think the ask is more on the ACL command being exposed by the two clients, to which the short answer is "no" they are not exposed at the moment but you can use the other clients as shown in the snippets. 
We are currently working on document how to craft custom commands: https://github.com/quarkusio/quarkus/pull/18463 which may help. We could also expose the command ACL command in the meantime if that's the ask.

**Comment by machi1990** [comment]
> Hi @machi1990 the main question from customer is "how to use the ACL Redis (V6.x) connect with the quarkus-redis Client" ? the **quarkus.redis.hosts** configuration they are using as explained in here: https://quarkus.io/guides/redis (attached screen for reference).
> 
> ![Screenshot 2021-10-20 at 11 25 07 AM](https://user-images.githubusercontent.com/23397435/138023543-8a9d9386-8b87-4e26-af92-e837d0d41d7b.png)

Thanks for the clarification. The `quarkus.redis.hosts` connection string will look like `redis://redis-user:redis-password@host:port `

here:
- `redis-user` is the user, if you leave it to empty it will use the default user.
- `redis-password` is the user password
- `host` is your redis server host
- and `port` is your redis server port.
