### ISSUE TITLE
Beans are not loading from the custom dependent jars

### ISSUE THREAD

**Issue by JithendraKatkam** [quarkusio/quarkus#20540]
### Describe the bug

If the beans are in the same project - they are loading properly into the context, but when the same component or bean moved to other jar, they are not loading - the error is -  Unsatisfied dependency for type.......

### Expected behavior

The beans declared in other jars must be fetched and loaded to reuse the custom utilities and third party jars.

### Actual behavior

If the beans are in the same project - they are loading properly into the context, but when the same component or bean moved to other dependent jar, they are not loading - the error is - Unsatisfied dependency for type....
let say..Util.java bean with @Component with @Named is defined in the dependency jar - the application gives an error. 

### How to Reproduce?

1. Create 2 gradle projects with "main-mod" and "dep-mod"
2. Add Util.java class to "dep-mod" project as below
```
@Component
@Named("kafka.util")
public class Util {
// util methods or specific service methods..
}
```
3. publish the jar "dep-mod" with 1.0.0 version to local maven repo
4. add that dependency to the main-mod project
5. Add a main class where the Util bean/component is added
```
@Startup
@ApplicationScoped
@Slf4j
public class MainClass {
    @Inject
    @Named("kafka.util")
    Util util;
   //etc
   //..
   //..

}
```

### Output of `uname -a` or `ver`

Darwin C02C98D4LVDLMBP 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-11.0.12.7.2 (build 11.0.12+7-LTS, mixed mode)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.7

**Comment by glefloch** [comment]
@JithendraKatkam by default quarkus doesn't look in all dependency artifacts. 
There are multiple ways to tell quarkus to looks into specific jar, here is the list: https://quarkus.io/guides/cdi-reference#bean_discovery . 
You can for example add an empty `META-INF/beans.xml` file in your dependency projet, or reference the dependency in your `application.properties` by setting `quarkus.index-dependency`

**Comment by JithendraKatkam** [comment]
ok thanks - but preferable is to search all those dependency jars if any component is referenced and load that bean/or all beans in that jar as it is only during the build time. this is from flexibility point of view from the usage, but its fine to reduce the  build time and specify explicitly for the jar or beans required.

**Comment by glefloch** [comment]
Thanks for your answer @JithendraKatkam I'm closing.
