### ISSUE TITLE
RESTEasy Reactive extension does not link to its guide

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#20541]
On code.quarkus.io, the RESTEasy Reactive extension in the extension list does not have a link to [its guide](https://quarkus.io/guides/resteasy-reactive). See screenshot:

![Screen Shot 2021-10-05 at 8 02 49 AM](https://user-images.githubusercontent.com/363447/136018906-3f6f4c75-6033-49dc-83fc-30ffa678caf3.png)

**Comment by edeandrea** [comment]
@ia3andy I started to create the issue there but wasn't sure how everything worked under the covers so figured this was the best place to at least start.

**Comment by edeandrea** [comment]
If you'd prefer I create an issue over on quarkusio/quarkus just let me know & I'll do that.

**Comment by ia3andy** [comment]
@edeandrea I've moved the issue, no worries ;)
