### ISSUE TITLE
Akka / Actor Model Support -- Maybe an Akka Extension

### ISSUE THREAD

**Issue by steele232** [quarkusio/quarkus#20544]
**Akka / Actor Model Support -- Maybe an Akka Extension**

Hi, I would like a way to use Akka Actors with Quarkus because the Reactive features currently present are nice but I really need an actor model solution and it is missing from Quarkus.

I saw from other Github issues that Quarkus has an extension / support for Scala but it seems like you have to have a special setup for that. I tried doing that special setup with the help of the quickstart generator and it seems that writing Scala works to some extent but when I start using Akka, I was still having great difficulties. 

I also tried the base gradle/java quarkus starter (which I would like to use because I am using Java the whole way through except Akka uses Scala inside its core) -- I tried to importing Akka just like I do with a normal Java/Gradle project but I get the following error when I try to do that:

```
Caused by: java.lang.NoClassDefFoundError: scala/$less$colon$less
```

I feel like it shouldn't be too hard to use Akka with Quarkus and it very much fits in the Reactive paradigm which Quarkus aims to support, but so far my experience trying to get this to work has been fairly painful for compilation reasons.

**Comment by aloubyansky** [comment]
@steele232 have you been looking into this lately? Do you have a repo we could check out to see where it breaks? Thanks.

**Comment by ares-b** [comment]
@steele232 Akka moved frop Apache Licensing few months ago, I don't think any OSS solution will ever use their libraries again

**Comment by geoand** [comment]
As mentioned above, with Akka's new license model, it's a complete non starter for us to use it.

**Comment by millerjp** [comment]
You have Apache Pekko now (https://pekko.apache.org/) which is a fork of Akka

**Comment by geoand** [comment]
Thanks 👍
