### ISSUE TITLE
SmallRye Health codestart (in java and kotlin)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#20553]
### Description

As SmallRye Health is one of the most used extension, we should find a good codestart for it (in java and kotlin).

### Implementation ideas

We should first discuss the content of this codestart. The goal is to have code:
- that is re-used 99% of the time to get started with the extension (nearly no deletion)
- that is compatible with all other compatible extensions codestarts

What is the piece of code that you nearly always start with when using the extension.. Make it compile, and it's the perfect codestart!

The guide to create an extension codestart (only available in the snapshot documentation for now: https://quarkus.io/version/main/guides/extension-codestart)

**Comment by ia3andy** [comment]
@jmartisk do you mind proposing the content of a starter HealthCheck class here so we can discuss it already?

Readiness, Liveness? both? check name, maybe `MyHealthCheck`?

**Comment by jmartisk** [comment]
If we want to keep it ultra simple, then how about...

```
@Liveness
public class MyLivenessCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse.builder().up().name("alive").build();
    }

}
```
