### ISSUE TITLE
Rest Client codestart (in java and kotlin)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#20555]
### Description

As Rest Client is one of the most used extension, we should find a good codestart for it (in java and kotlin).

### Implementation ideas

We should first discuss the content of this codestart. The goal is to have code:
- that is re-used 99% of the time to get started with the extension (nearly no deletion)
- that is compatible with all other compatible extensions codestarts

What is the piece of code that you nearly always start with when using the extension.. Make it compile, and it's the perfect codestart!

The guide to create an extension codestart https://quarkus.io/guides/extension-codestart

**Comment by ia3andy** [comment]
@evanchooly do you want to have a look into this (It shouldn't take more than 1h), I can assist you by all means :-)

**Comment by michalszynkiewicz** [comment]
I think it should focus on REST Client Reactive, we can do REST Client too later, but we want to attract people to the reactive space more now.

For me the problematic part is having some API to call from the client, IMO we have the following options:

- use wiremock in a test and leave the client unconfigured for other profiles, it won't let users play with the app in dev mode but it will be the cleanest
- call some open API, but it will probably eventually break, like our quickstarts with restcountries.eu
- add RESTEasy Reactive to the project and consume some service exposed by it. This would also allow us to create a native test for the project but we end up with a dependency that in some cases won't be needed

**Comment by ia3andy** [comment]
> Hmm... maybe we could use some of our own endpoints, e.g. something from code.quarkus.io?

@michalszynkiewicz yes we could use this endpoint: https://code.quarkus.io/api/extensions

For the data, I would either suggest using a flexible structure, or use an internal data class so we stay with one file per codestart.

Regarding usage, a test is fine, a simple comment in the interface saying how to inject it or configure would be fine too IMO.

To decide, we should find what is the closest to where the users will start from. The goal is not to teach them, but give some hints to people who already used it so they don't have to go back to the guide to remember the starting point.

**Comment by michalszynkiewicz** [comment]
I'm not sure I'll have time soon. I just wanted to drop some thoughts
