### ISSUE TITLE
Hibernate & Hibernate with Panache codestart (and their reactive siblings)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#20551]
### Description

As hibernate is one of the most used extension, we should find a good codestart for it (in java and kotlin)

### Implementation ideas

We should first discuss the content of this codestart. The goal is to have code:
- that is re-used 99% of the time to get started with the extension (nearly no deletion)
- that is compatible with all other compatible extensions codestarts

What is the piece of code that you nearly always start with when using the extension.. Make it compile, and it's the perfect codestart!

The guide to create an extension codestart https://quarkus.io/guides/extension-codestart

**Comment by ia3andy** [comment]
IMO, we should make a choice between the active record pattern or the repository pattern for the codestart. 

I would just generate something like this:
```java
@Entity
public class Something extends PanacheEntity {
    public String name;

    public static Something findByName(String name){
        return find("name", name).firstResult();
    }
}
```

Also regarding specific examples (transactions, ...), IMO this is the role of the guide and the quickstarts.

**Comment by Sanne** [comment]
+100 would be awesome to have this.

I'm not sure however about being able to suggest some code which is 99% if cases not deleted: let's discuss some suggestions

**An example entity**
We could have an example entity but this would most likely get deleted / replaced. Could still be useful as one might rename the entity and start from there?
At least it would highlight that having an entity in such and such location is all what's needed to get going.

**An example import.sql**
Have an `import.sql` script in `/resources`. Could be empty, or it could store a couple of instances of the above type - this could be useful to also autogenerate some meaningful integration tests.
Any content we might want to suggest would eventually most likely get deleted though so it again violates the suggestion of 99% reuse.

**Inject an EntityManager**
This is most likely the only piece of code which is not going to be deleted. It's just a two-liner but could indeed be helpful, it suggests how to get started.

**An example use of the injected EntityManager**
Again most likely going to get deleted, but could be useful to highlight the need for having a `@Transactional` annotation on the method and provide similar guidance.

But since you're asking specifically for Panache, maybe injecting the EntityManager is not something we want to show. I would have it in an Hibernate ORM codestart which is not using Panache though.

**Comment by ia3andy** [comment]
> +100 would be awesome to have this.
> 
> I'm not sure however about being able to suggest some code which is 99% if cases not deleted: let's discuss some suggestions
> 
> **An example entity** We could have an example entity but this would most likely get deleted / replaced. Could still be useful as one might rename the entity and start from there? At least it would highlight that having an entity in such and such location is all what's needed to get going.
> 

I think renaming is different than deleting, and it's easier to rename and start from it than creating a new one. We can't have code that is not changed at all, but we should just be as close as possible. 

> **An example import.sql** Have an `import.sql` script in `/resources`. Could be empty, or it could store a couple of instances of the above type - this could be useful to also autogenerate some meaningful integration tests. Any content we might want to suggest would eventually most likely get deleted though so it again violates the suggestion of 99% reuse.
> 

I think we could also have this with just one `Something`? We need to think how to deal with different extensions providing imports.. can they have different name maybe?

> **Inject an EntityManager** This is most likely the only piece of code which is not going to be deleted. It's just a two-liner but could indeed be helpful, it suggests how to get started.
> 
> **An example use of the injected EntityManager** Again most likely going to get deleted, but could be useful to highlight the need for having a `@Transactional` annotation on the method and provide similar guidance.
> 

I am not familiar with those, so I let you see which is the best for the user...

> But since you're asking specifically for Panache, maybe injecting the EntityManager is not something we want to show. I would have it in an Hibernate ORM codestart which is not using Panache though.

We could have another codestart for Hibernate ORM

**Comment by Sanne** [comment]
> We could have another codestart for Hibernate ORM

Ok yes but I see some overlap. So if my application is using *only* `quarkus-hibernate-orm` then you should have those injection points, but if it's using both `quarkus-hibernate-orm` and `quarkus-hibernate-orm-panache` (excplicitly or implicitly: N.B. that `quarkus-hibernate-orm-panache` depends on `quarkus-hibernate-orm`) then you probably want to show the "Panache Way" of doing things.

You remember I mentioned the need for simple boolean operators to handle such things? Was that done making such a switch possible?

**Comment by ia3andy** [comment]
We can't decide wether we create a file or not depending on the selected extensions, but we can decide the content of a the same file (using qute):
`input.selected-extensions` is already available as data in the codestart qute templates as a set of `groupId:artifactId`

**Comment by Sanne** [comment]
> @Sanne
> 
> Yes we could use the same codestart for both, but using some switch depending on which extensions are selected to promote different things. How does that sound?

@ia3andy sounds great :)

**Comment by loicmathieu** [comment]
Very important, for Panache Quarkus **must** include both active record and repository pattern, we already had a long discussion about it and the status quo is that both pattern are as important inside Quarkus so both must be treated equally.

People may personnaly favor one for another on blog post and talks, but inside Quarkus code/guide/quickstart/etc... they must be treated equally.

**Comment by Sanne** [comment]
hi @loicmathieu ! Yes I agree we need to showcase both options, but also it doesn't make much sense to mix both approaches in the same app?

That would send the wrong message; it's confusing. Personally I don't care which one we show, but we need to pick one.

**Comment by loicmathieu** [comment]
But really, this point have been extensively discussed and I keep hearing "the Quarkus teams promote the entity pattern" or remarks like. So I must incist, both needs to be provided and the user choose wich one best fit its needs.

@FroMage WDYT ?

**Comment by ia3andy** [comment]
I am not a fan of having both together in the same app & we don't have a way to let the user decide beforehand.. 

We could have a comment saying that another option is equaly available and to refer to the guide for more info

**Comment by Sanne** [comment]
> But really, this point have been extensively discussed and I keep hearing "the Quarkus teams promote the entity pattern" or remarks like. 

That's not accurate. It's the personal preference of @FroMage , and possibly a few others. But there's many other team members who prefer the repository pattern.

My own personal preference is for the repository pattern, but I have to admit that in such case the benefit of using `Panache` vs using just `EntityManager` is less clear, so I don't feel like it's a big deal to show the entity pattern more prominently. It clarifies the potential better in documentation - but when it comes to this specific case I guess using repository is more suited, or at least equally so.

> The question is, will the repository be also for hibernate without panache? because we need them to have the same files.

@ia3andy sure no worries, I think we can work with the "same files" restriction.

**Comment by ia3andy** [comment]
@loicmathieu it would be nice if you could paste the target files here for both 
Hibernate & Hibernate with Panache, at least we can keep discussing..

**Comment by loicmathieu** [comment]
So, I will have time next week to work on it but we need to decide what to do first.

Scenario 1: The easiest way:
- Create a Fruit (or Person entity) as the Hibernate codestart
- Create a FruitRepository as the Hibernate with Panache codestart that will reuse the Fruit entity from the Hibernate with Panache codestart
- Create a FruitRessource or a FruitRepositoryTest that will show some usage of the repository.
- Add comment somewhere that the entity pattern exist and can replace the repository

Scenario 2: showing both way
- Create a Fruit entity as the Hibernate codestart
- Create a FruitRepository as the Hibernate with Panache codestart that will reuse the Fruit entity from the Hibernate with Panache codestart
- Create a Person entity that extends PanacheEntity to shows the two pattern
- Create a FruitResource that will show the usage of the repository
- Create a PersonTest that will show the usage of the entity and the specificity for mocking them using PanacheMock

We should try to provide the same code that the one existing inside the guides.

Maybe we also need to provide a REST resource or a test for the Hibernate codestart to see how to inject the entitymanager and use it directly. But we need to find a way to override it or at least to amend it with the Panache codestart.

The main issue is that both extensions are related, and if we don't have a way with codestart to take advantage of it we will need to duplicate things.

@Sanne @FroMage WDYT ?

**Comment by ia3andy** [comment]
I do prefer the `imports.sql` which is made for this.

**Comment by ia3andy** [comment]
@loicmathieu yes it's possible, let's continue that discussion on zulip

**Comment by yrodiere** [comment]
Hey @loicmathieu , do I understand correctly that you already merged a Hibernate ORM/Panache codestart for Java/Kotlin, and what remains to be done is "just" the reactive equivalent?

**Comment by loicmathieu** [comment]
@yrodiere I only merge an Hibernate ORM codestart, the Panache one was on-ice see #21651, we never comes to an agreement on whether or not it's worth doing it, please give your feedback on the PR ;)

**Comment by yrodiere** [comment]
@loicmathieu Done.

**Comment by yrodiere** [comment]
As far as I can see, we now have codestarts for Hibernate ORM with and without Panache, in Java and Kotlin. Thanks to everyone involved!

Closing.
