### ISSUE TITLE
Bootstrap workspace discovery should rely on the presence of parent in pom.xml

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#2056]
The workspace discovery may start from any project in the workspace (in case of launching tests, very unlikely from the top one unless it's a simple project with no modules).
Currently, the top project is looked by checking whether the parent directory contains pom.xml, which is a very primitive approach. One of the reasons for that was to be able to discover the whole workspace starting from, e.g. an independent project which still appears as a module in a workspace like in quarkus. However that is still not a proper way to do that.
The parent discovery has to rely on the presence of `parent` element in the `pom.xml` and its `relativePath` which by default is `../pom.xml`.

**Comment by gsmet** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/2057 .
