### ISSUE TITLE
Enable watermarking images, fonts rendering and all JDK supported image formats in AWT Extension

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#20565]
### Description

Use case:
 - watermarking images
 - drawing, server side generated graphics

Status:
 - polishing an update into a PR
 - wrapping up a new quickstart to open a PR in https://github.com/quarkusio/quarkus-quickstarts too

WIP:
Done means there is a suite of rigorous tests exercising the relevant code paths, e.g. for encoders only it's 964 test cases of image type:image format:colour space:compression.

- [x] Showcase in a Quick start: [awt-graphics-rest-quickstart](https://github.com/Karm/quarkus-quickstarts/tree/quarkus-awt/awt-graphics-rest-quickstart/#readme) (needs not yet published AWT extension update)
- [x] TIFF Decoder; all compressors; metadata
- [x] TIFF Encoder; all compressors; metadata; multiple images in a container
- [x] PNG Decoder; all compressors; layers; metadata
- [x] PNG Encoder; all compressors; metadata
- [x] GIF Decoder; all compressors; animations; metadata
- [x] GIF Encoder; all compressors; metadata
- [x] JPEG Decoder; metadata
- [x] JPEG Encoder; metadata
- [x] BMP Decoder; all compressors; metadata
- [x] BMP Encoder; all compressors; (metadata immutable, so just the default)
- [x] WBMP Decoder; metadata
- [x] WBMP Encoder; (metadata immutable, so just the default)
- [x] Fonts, both embedded and loading one's own: It's done in the aforementioned Quick start, I just need to do some streamlined copy-pasting :) to the extension's integration tests.
- [x] Geometry, full Java2D suite, building on the foundation I have in [/mandrel-integration-tests](https://github.com/Karm/mandrel-integration-tests/tree/master/apps/imageio)
- [x] Rinse and repeat on JDK 17 as all the above work is being done with JDK 11.0.13 ea.
- [x] Rinse and repeat on Windows, which will bring some additional changes. All the aforementioned work in being done on Linux.
- [x] README me for the test suite
- [x] Docs for the extension 

Implementation affects:
 - recent awt extension
 - core, switching Quarkus to be headless by default , i.e.
```diff
@@ -52,6 +52,13 @@ public class NativeConfig {
     @ConfigItem(defaultValue = "true")
     public boolean enableJni;
 
+    /**
+     * The default value for java.awt.headless JVM option.
+     * Switching this option affects linking of awt libraries.
+     */
+    @ConfigItem(defaultValue = "true")
+    public boolean headless;
+
...
@@ -597,6 +597,10 @@ public class NativeImageBuildStep {
                 nativeImageArgs.add("-H:+JNI");
                 nativeImageArgs.add("-H:+AllowFoldMethods");
 
+                if (nativeConfig.headless) {
+                    nativeImageArgs.add("-J-Djava.awt.headless=true");
+                }
+
```

### Implementation ideas

@gastaldi Assign the issue to me, please.

**Comment by Karm** [comment]
@galderz @jerboaa The issue to bind the upcoming PRs to....

**Comment by galderz** [comment]
I'm happy with the proposal. I think having the native image configuration options would be useful too, to avoid relying on implicit local environment, or docker image specific, setups.
