### ISSUE TITLE
Allow trusted certificates to be specified at runtime by keystore and multiple PEM files

### ISSUE THREAD

**Issue by ChetRHosey** [quarkusio/quarkus#20594]
### Description

According to https://quarkus.io/guides/native-and-ssl#the-truststore-path,

> the root certificates are fixed at image build time [...] when the defaults need to be changed, these system properties must be provided at image build time

But trust settings can be environmental. Examples:

- A corporate proxy may do MITM inspection of HTTPS traffic and re-sign with an organizational CA
- An organizational CA may be used on-premise
- An OpenShift cluster can provide service certificate with its own internal CA

Making this a build-time-only option limits the ability of Quarkus apps to connect to services whose certificates are signed by an environment-specific CA.

It would be helpful if operators could provide an environmental trust store at runtime.

Ideally PEM files could be trusted directly to avoid the need to use keytool at runtime. PEM files can come from a number of sources, especially within OpenShift:

- OpenShift can [inject its cluster-specific service CA certificate](https://docs.openshift.com/container-platform/4.8/security/certificates/service-serving-certificate.html#add-service-certificate-configmap_service-serving-certificate) into an annotated ConfigMap.
- Operators may add add organizational CAs to a ConfigMap.
- Cluster admins can configure the [proxy settings](https://docs.openshift.com/container-platform/4.8/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki) to include environmental CAs. This can be injected to a [specially labelled ConfigMap](https://docs.openshift.com/container-platform/4.8/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki).

A runtime option to load trusted CAs from multiple PEM files would greatly ease Quarkus' use in environments where custom CA settings are a requirement.

**Comment by cescoffier** [comment]
I'm +100 to have external certs.

We would need to check again, but initially it was the graalvm way. 

With most of the I/O using Vert.x we should be able to configure each client/server with the external certs. However we would need to check with extensions using a different model.

**Comment by stgrace** [comment]
Hi @cescoffier,

Do you have an update on this? We would like to be able to add ca-bundles at runtime, since we deploy our applications at multiple cusotmers and they all require communication over HTTPS, so adding ca bundles at build time is not really viable.

**Comment by cescoffier** [comment]
No, unfortunately, my work around the new TLS config is on hold (until I have the time to come back to it)
