### ISSUE TITLE
jcabi-aspects not working

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#20601]
### Describe the bug

I tried to add `jcabi-aspects`(https://aspects.jcabi.com/index.html) to my project (a simple one based on https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started),  adding `Loggable` annotation to my class and expect it to log every invocation.

### Actual behavior

didn't log anything

### How to Reproduce?

based on https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started
 add jcabi-aspects dependency
```
        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-aspects</artifactId>
            <version>0.23.2</version>
        </dependency>

```

add `Loggable` annotation to method:
```
package org.acme.getting.started;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import com.jcabi.aspects.Loggable;

import org.jboss.logging.Logger;

@ApplicationScoped
public class GreetingService {

    @Inject
    Logger LOGGER;

    @Loggable
    public String greeting(String name) {
        return "hello " + name;
    }

}

```

### Output of `uname -a` or `ver`

Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev

1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by geoand** [comment]
This is not something that is supported. For simplified logging, check out https://quarkus.io/guides/logging#logging-with-panache
