### ISSUE TITLE
@ConfigProperty without @Inject does not work in test

### ISSUE THREAD

**Issue by nilshartmann** [quarkusio/quarkus#2061]
In the "Application Configuration Guide" it says:

_The @Inject annotation is not necessary for members annotated with @ConfigProperty, a behavior which differs from MicroProfile Config_

While this works in Beans, it does not work in `@QuarkusTest`s. In my test case I have to add `@Inject` to `@ConfigProperty` to get access to a configuration property. Is this different behaviour intended? Then it could be helpful to add a note in the documentation.

**Comment by geoand** [comment]
@nilshartmann I opened a PR that fixes the issue, thanks for bringing this to our attention!
