### ISSUE TITLE
Smallrye Reactive Messaging MetricDecorator disabled when micrometer extension is used

### ISSUE THREAD

**Issue by baiglin** [quarkusio/quarkus#20612]
### Describe the bug

I noticed that the MetricDecorator is vetoed in case Micrometer is enabled https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java#L346

Which is strange since there is an adapter layer for Eclipse Profile Metrics available.

### Expected behavior

The expected behavior would be to keep the decorator even if Micrometer is used (Or even better use a decorator with Micrometer :) )

### Actual behavior

MetricDecorator is disabled 

https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java#L330

### How to Reproduce?

Use a project with Kafka Reactive Messaging and enable the property 

quarkus.reactive-messaging.metrics.enabled=true

Add Micrometer extension https://quarkus.io/guides/micrometer. 

Check metrics is available in a QuarkusTest

    given().when()
        .get("/q/metrics")
        .then()
        .statusCode(200)
        .body(containsString("base_mp_messaging_message_count_total{channel=\"receiver-channel\"}"));

Will fail

**Comment by ebullient** [comment]
https://github.com/smallrye/smallrye-reactive-messaging/pull/1448 -- is a beginning. I think there is a config question and a test question

**Comment by cescoffier** [comment]
Fixed with SmallRye Reactive Messaging 3.11 (which is not included in Quarkus).
