### ISSUE TITLE
Need to publish Neo4J console for Dev Service

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#20624]
### Describe the bug

When a Neo4J database stands up by Quarkus dev service, the Neo4J console(http://localhost:7474/browser) can't be accessible since the 7474 port wasn't published. If I run the Noe4J container manually with "--publish=7474:7474", I can access the console.

### Expected behavior

The web console can be accessible via http://localhost:7474/browser/

### Actual behavior

The web console can't be accessible via http://localhost:7474/browser/

### How to Reproduce?

1. Clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/neo4j-quickstart
2. Comment or remove all keys and values in the application.properties
3. Run Quarku Dev Mode
4. Access the Noe4J console via http://localhost:7474/browser/

### Quarkus version or git rev

2.3.0.Final

**Comment by michael-simons** [comment]
(just to be clear, our driver is completely independent from the browser console and browser console uses the JavaScript version of the driver to speak with the db, so it's a bit more than just exposing the browser port and hope things work…)

**Comment by sandronm** [comment]
Hello @michael-simons , any news about this feature to be able to set a port for this Dev Service? It will be very convenient! :)

**Comment by michael-simons** [comment]
Glad you asked, @sandronm  :) See attached PR and check whether it makes sense for you.

You can build Quarkus from my fork like this

```
./mvnw -Dquickly   
./mvnw -DskipTests install -pl io.quarkus:quarkus-neo4j -pl io.quarkus:quarkus-neo4j-deployment -pl io.quarkus:quarkus-neo4j-parent
```
[qdevservices.zip](https://github.com/quarkusio/quarkus/files/7514840/qdevservices.zip)


and test it with the attached project for example.
