### ISSUE TITLE
gzip compression only works if response_size < quarkus.resteasy.vertx.response-buffer-size

### ISSUE THREAD

**Issue by dinesh-chander** [quarkusio/quarkus#20637]
### Describe the bug

I'm using quarkus with hibernate and resteasy extensions. I'm facing one issue where gzip only works if 
response_size < quarkus.resteasy.vertx.response-buffer-size. I don't know if it's intentional or not. 

But even if the response_size > quarkus.resteasy.vertx.response-buffer-size and gzip is enabled globally, the response headers include 

content-encoding: gzip
transfer-encoding: chunked

which is incorrect since the response is not actually compressed.

### Expected behavior

quarkus.resteasy.vertx.response-buffer-size should not affect compression.

### How to Reproduce?

Reproducer:

1. Clone https://github.com/dinesh-chander/quarkus-resteasy-gzip-issue
2. Run server
3. Use postman to make call to localhost:8080/fruits. Check the response size (should be more than 20KB)
4. Now, uncomment quarkus.resteasy.vertx.response-buffer-size property in application.properties and make the call again to localhost:8080/fruits. Check the response size (should be less than 600B)

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0 dinesh-PC 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin

### Output of `java -version`

temurin-11 version 11.0.12

### Quarkus version or git rev

2.3.0.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3

**Comment by gsmet** [comment]
@geoand any chance you could have a look at this one and qualify it?

**Comment by geoand** [comment]
Sure yeah

**Comment by geoand** [comment]
I am **not** witnessing the behavior you mention.

When using `cURL` like so:

`curl -v -H "Accept-Encoding: deflate, gzip;q=1.0, *;q=0.5" -X GET http://localhost:8080/fruits -o /dev/null`

I am seeing the proper response:

```
< HTTP/1.1 200 OK
< Content-Encoding: gzip
< Content-Length: 375
< Content-Type: application/json
```

in both cases.
