### ISSUE TITLE
QuarkusNative now depends on Docker while building from Gradle?

### ISSUE THREAD

**Issue by renannprado** [quarkusio/quarkus#2063]
This is kinda of a question more than a bug report or something.
I was able to successfully try to use quarkus `0.13.1` to build a sample application, but what I found strange is that even though I have set (as I did in `0.12.0`) the `GRAALVM_HOME` variable, now it is using docker to build the application.

Is there an option to disable the need of using docker to build the native binary?

**Comment by cescoffier** [comment]
@renannprado to build a native executable using your OS architecture just use:

`mvn package -Pnative`

It won't use docker to run the build (but will need `GRAALVM_HOME`. The usage of docker is only required if you want a Linux64 executable and you are not using a Linux64 machine (on a Mac for instance).

For further reference: https://quarkus.io/guides/building-native-image-guide

**Comment by renannprado** [comment]
@cescoffier Sorry for not being clear, but I'm using Gradle. How would I do it with Gradle?

**Comment by renannprado** [comment]
@cescoffier unfortunately I'm unable to reopen the issue, but it still don't know how to do it with gradle.

**Comment by cescoffier** [comment]
oh sorry, let me update thte title.

**Comment by drissamri** [comment]
I'm not sure if this is the same issue, but when building in native mode, you still need to set the GRAALVM_HOME property. This shouldn't be required since it's not being used.

Should I open a new bug or is this the same?

**Comment by gwenneg** [comment]
@drissamri It looks like the same issue as #2786 which should have been fixed in Quarkus `0.21.1`. Could you try with `0.21.1` and confirm it's all good now please?

**Comment by gwenneg** [comment]
@renannprado Thanks for asking us to reopen this issue! There was a bug in our Gradle plugin which I just fixed.
