### ISSUE TITLE
Support DB Optional Properties in Service Binding pkg

### ISSUE THREAD

**Issue by myeung18** [quarkusio/quarkus#20634]
### Description

When connecting DB with JDBC, the user is allowed to append optional properties to customize the connection, 
`e.g.:jdbc:postgresql://localhost:5432/postgres?sslfactory=abc.def&prepareThreshold=1000`, but this is currently not supported by Quarkus Service Binding Extension.

This is to propose that Service Binding Extension reads an `options` file, if it is present, under the directories in SERVICE_BINDING_ROOT. The file content is "key=val" pair and concatenate with '&'. e.g. `sslfactory=class.path&prepareThreshold=1000`. 

### Implementation ideas

Each database converter can format the optional properies accordingly. Postgresql as an example: 
https://gist.github.com/myeung18/9a9a7dca09fca9050afd99a8cbfe81bf

**Comment by geoand** [comment]
@maxandersen do you know if there is any sort of support for this?

**Comment by maxandersen** [comment]
as things are quite new its kinda upto us and everyone using this to define the "defacto" standards.
I would assume these would make sense to make very specific and put them under `jdbc_options` key. 

we can add it to enable it at least; but really should end up being part of defacto standard/convention for SBI for database services.

**Comment by maxandersen** [comment]
that said - jdbc options can/is very dependent on the client app so just wondering if a user can set datasource options and they will "merge" with service binding auto detected settings?

**Comment by geoand** [comment]
Sure, we can definitely do that as well

**Comment by geoand** [comment]
Actually, we already have `quarkus.datasource.jdbc.additional-properties` and in concert with the fact that options are totally client specific, I am going to close this as `won't fix`.

**Comment by myeung18** [comment]
@geoand @Predrag Knezevic

Sorry, I didn't follow up this until now. 

Here are the service binding flow per my understanding:  
- The binding service, e.g. Service Binding Operator, reads the connection info. from k8s object such as ConfigMap or Sercret, and then it creates/binds the connection info to `SERVICE_BINDING_ROOT`. 

- Next, Quarkus service binding client reads connection info from `SERVICE_BINDING_ROOT`, and make a DB connection or a customized DB connection if `options` params exist (the purpose of this issue).

I don't understand what difference does it make to Service Binding client if those `options` are client specific or not.
Data that are available in ConfigmMap or Secret for binding purpose have to be processed and read by binding service as well as the Quarkus binding client.

Do you mean there is other way to make `options` available to Quarkus binding client so that a customzied DB connection can be created?

**Comment by geoand** [comment]
> I don't understand what difference does it make to Service Binding client if those options are client specific or not.

It means that it doesn't make sense for the operator to provide values for these, because each consumer (that is each client that consumes that service - a DB for example) has different needs and therefore needs to set different settings to match it's own unique access characteristics.

**Comment by myeung18** [comment]
Does that imply if we need a customized DB connection, we can't use Binding service/SBO?

**Comment by pedjak** [comment]
> Does that imply if we need a customized DB connection, we can't use Binding service/SBO?

What kind of customization needs to be pushed from a service to the client? Any example?

**Comment by myeung18** [comment]
I think all those options available for client to use are examples: https://jdbc.postgresql.org/documentation/head/connect.html.
like `ssl`, most of the databases have this option for client to enable or disable ssl connection: 
`jdbc:postgresql://localhost/test?user=fred&password=secret&ssl=true`

**Comment by myeung18** [comment]
The same thing has been implemented for Mongodb: https://github.com/quarkusio/quarkus/pull/19517
This is to suggest to apply to other databases.

**Comment by pedjak** [comment]
IMHO, a service needs to expose bindings that are agnostic to driver/client/runtime and are really required for establishing the connection, but not for connection management. Your example is very JDBC centric, but a Postgres service should expose binding items like:
* host
* database
* username
* password
* ssl
* rootcertificate, certficate, certificatepassword (in case when user/password is not used for authentication)

Based on what is projected into an app, the app should construct right JDBC url for example and add some options if needed. IMHO, pushing options from service into the application might have some security risks.

**Comment by myeung18** [comment]
> 
@pedjak  Thank you for your comments.

I didn't verify all those options, but, as far as I know, those keys and values are agnostic to driver/client/runtime. Depending on the clients,however, the construction of connection urls could be different.  E.g.: The formatted options part appended to the url will be different: jdbc : `ssl=true;param1=value1`, golang: `ssl=true param1=value1`.  
I am not sure about that connection management part, but the thing is if we provide a service that helps a client to create DB connections, shouldn't we let them to use the options features provided by the database as well?

Yes, you're right, and It is, in fact, the Quarkus Service Binding Client that does the JDBC url construction.  This issue is to suggest to change it to read `options` file for that purpose.
What is security risks you see on this?

**Comment by myeung18** [comment]
> > I don't understand what difference does it make to Service Binding client if those options are client specific or not.
> 
> It means that it doesn't make sense for the operator to provide values for these, because each consumer (that is each client that consumes that service - a DB for example) has different needs and therefore needs to set different settings to match it's own unique access characteristics.

@geoand  I'm still trying to understand this part. Apologize if I misunderstood/repeating something. 
Each consumer does have different DB connection needs.  They are using different databases with different usernames, passwords, etc. Perhaps they have different Db connection requirements which can be achieved with `options`. So, they have their own Quarkus applications which configure, use SBO and Quarkus SB client differently.  Does this not necessitate the need to let clients to use `options` for their own connections?

**Comment by geoand** [comment]
I am talking about the properties that affect the various details of the connection or the driver.

You can certainly have applications that use the same URL and credentials but otherwise don't share any other common JDBC properties.

**Comment by sgahlot** [comment]
@geoand / @pedjak  there are a couple of options that are used frequently, i.e. `connectTimeout`, `readTimeout`, `socketTimeout`, `ssl` (or `sslenabled`) etc. Are we saying that all of those should be outside the realm of SBO and shouldn't be coming from bindings, but should be put in the connection string (that is indeed coming from a Service BInding library) afterwards by an application depending on their customized needs?

**Comment by geoand** [comment]
I am no expert, but I would say that connect timeout is a client specific setting. 
Not really sure about SSL though...

@cescoffier @maxandersen WDYT?

**Comment by pedjak** [comment]
> What security risks you see on this?

Well, if service can dictate to user what readTimeout the client should use.

**Comment by cescoffier** [comment]
ssl could be set by the SBO, but not timeout. Timeout depends on latency, resource and load. These are specific to the client application.

**Comment by myeung18** [comment]
What I get so far is service binding can still selective support some of the option settings for customizing a DB connection. 

The names could be DB specific, for Postgresql as an example:
`ssl, rootcertificate, certficate, certificatepassword` or some other non-client specific or non-risky options.

They can be an individual entries in a Configmap for SBO, then for Quarkus SB client to process.

@geoand  does this sound right?

**Comment by geoand** [comment]
Yeah, that seems right to me

**Comment by cescoffier** [comment]
I'm wondering about the security implication of passing the trust store in the SBO. Basically, it's almost a "trust-all". I understand why we could desire to do that, but provisioning certs is a very sensible operation. 

Then, what about mTLS (I'm not sure PG supports it), how would you pass the client certs in this case?

**Comment by myeung18** [comment]
> I'm wondering about the security implication of passing the trust store in the SBO. Basically, it's almost a "trust-all". I understand why we could desire to do that, but provisioning certs is a very sensible operation.
> 
> Then, what about mTLS (I'm not sure PG supports it), how would you pass the client certs in this case?

In case we have this question is because I included those certificate related options in the example, we don't actually have plan nor any use case to do any key management over SBO.
Maybe someone else can answer the question.
