### ISSUE TITLE
Type mismatch: cannot convert from Multi<Object> to Publisher<String>

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#20650]
### Describe the bug

When I tried to run the Neo4J quickstart[1], I got this a warning:

Type mismatch: cannot convert from Multi<Object> to Publisher<String>

![image](https://user-images.githubusercontent.com/14066977/136683294-2a3e976f-59e9-4882-a914-d1661ba163bf.png)

[1]https://github.com/quarkusio/quarkus-quickstarts/tree/main/neo4j-quickstart

The reactive endpoint is actually working and there's no build failure in Dev mode though

### Expected behavior

No warning for this. It seems an error in IDE(VS Code) tool for developers.

### Actual behavior

Type mismatch: cannot convert from Multi<Object> to Publisher<String>

https://github.com/quarkusio/quarkus-quickstarts/blob/main/neo4j-quickstart/src/main/java/org/acme/neo4j/ReactiveFruitResource.java#L28

### How to Reproduce?

1. Clone the neo4j-quickstart(https://github.com/quarkusio/quarkus-quickstarts/tree/main/neo4j-quickstart)
2. Open the project via IDE(e.g. VS Code)
3. Go to `ReactiveFruitResource.java` 
4. Red underscore or highlight will show up on line 28(https://github.com/quarkusio/quarkus-quickstarts/blob/main/neo4j-quickstart/src/main/java/org/acme/neo4j/ReactiveFruitResource.java#L28)

### Quarkus version or git rev

2.3.0.Final

**Comment by cescoffier** [comment]
The QuickStart got updated in a way all ideas are happy.
