### ISSUE TITLE
Qute: prefix loop metadata

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#20671]
### Description

https://quarkus.io/guides/qute-reference#loop_section says that we get iterator metadata `index`, `hasNext`, `odd` and `even`, but it does not show any example of how to access it, leading me to believe it would be a property of the iterated variable such as `it.index`. I now realise it showed this example:

```java
{#each items}
  {count}. {it.name} 
{/each}
```

Which introduces the `count` metadata, I guess, but because it's not properly introduced I assumed it was a random toplevel.

The docs should be more clear as to which metadata properties are available, and also this is terrible wrt scoping, because it will automatically override any explicitely declared binding named `count` or `index` by surprise.

I do agree it'd be weird to tack these metadata properties to the iterated variable.

In other templates, I've seen the iterated variable name being used as a prefix, though, such as `it_count` or `myVar_hasNext` which greatly limits binding clashes.

Could we get such prefixed properties instead?

**Comment by mkouba** [comment]
Hm, the more I think about this, the more I think it's not worth the effort. I mean we should definitely introduce the metadata properly in the docs (right now there's only one example and a TIP that lists all properties). But I'm not so sure about the change. We could make it configurable, globally or per loop, but I doubt that someone will ever use it. We could introduce a prefixed version but then we would have to keep the old version for backward compatibility and so we would still override the variables from the outer scope.

**Comment by gsmet** [comment]
Please make sure we have a very actionable error message so that people know how to fix it. I'm pretty sure it's often used, given how often you have to special case the first or last iteration.
