### ISSUE TITLE
RHEL 8 - documentation might need to be updated to mention zlib-devel as a requirement to build native executable; when using docker-ce, I had to use "nobest" e.g. dnf install docker-ce --nobest

### ISSUE THREAD

**Issue by marcredhat** [quarkusio/quarkus#2067]
Hi,

I'm using GraalVM on RHEL 8 to build a native image as shown at https://quarkus.io/guides/building-native-image-guide.html

[marc@marc quarkus]$ echo $GRAALVM_HOME
/home/marc/graalvm-ce-1.0.0-rc14

./mvnw verify -Pnative
......
[INFO] --- quarkus-maven-plugin:0.13.1:native-image (default) @ getting-started ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /home/marc/graalvm-ce-1.0.0-rc14/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace

1) In order to create a native executable using ./mvnw package -Pnative, 
zlib-devel is required:
sudo dnf install zlib-devel

2) When using docker-ce, I had to use "nobest"
dnf install docker-ce --nobest
systemctl start docker
systemctl enable docker
docker run hello-world

**Comment by marcredhat** [comment]
Also, might be worthwhile adding some instructions on using buildah:
[marc@marc quarkus]$ pwd
/home/marc/quarkus
[marc@marc quarkus]$ sudo mkdir /home/marc/quarkus/src/main/docker/target/
[marc@marc quarkus]$ sudo cp -R ./target/*-runner /home/marc/quarkus/src/main/docker/target/

[marc@marc quarkus]$ sudo buildah bud src/main/docker
STEP 1: FROM registry.fedoraproject.org/fedora-minimal
STEP 2: WORKDIR /work/
STEP 3: COPY target/*-runner /work/application
STEP 4: RUN chmod 775 /work
STEP 5: EXPOSE 8080
STEP 6: CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
STEP 7: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@0d2156dec86067444fbaf4b48a8e5be129608e5d87e3cbe069ec0a245daf6ce2
Getting image source signatures
Skipping fetch of repeat blob sha256:d9195980ace865ace5d3c8f9a0d0e241f282a0fcb632174b74829c9349d7cef0
Copying blob sha256:c0279fc66f4e7729bcdbac262b2950a653e8da780434c3cc35d4d5630b24e9e4
 6.66 MiB / 6.66 MiB [======================================================] 0s
Copying config sha256:b83d0d63f85e7ed8ce1ddd385e1997b070f7626e736994ed6a78fcaa1768551b
 708 B / 708 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
--> 0d2156dec86067444fbaf4b48a8e5be129608e5d87e3cbe069ec0a245daf6ce2


[marc@marc quarkus]$ sudo podman images
REPOSITORY                                    TAG                  IMAGE ID       CREATED         SIZE
<none>                                        <none>               958243a5d5ce   4 seconds ago   127MB

[marc@marc quarkus]$ sudo podman run 958243a5d5ce
2019-04-14 22:02:37,120 INFO  [io.quarkus] (main) Quarkus 0.13.1 started in 0.005s. Listening on: http://[::]:8080
2019-04-14 22:02:37,120 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]

[marc@marc quarkus]$ sudo podman run -dit -p 3333:8080 958243a5d5ce
7dc290caff4eb4f643f025ec74043aef621d8d2511c820c68b054a792cb722e7


[marc@marc quarkus]$ sudo podman container ls
CONTAINER ID   IMAGE                                                              COMMAND                  CREATED              STATUS                  PORTS                    NAMES
1af46bb822c5   958243a5d5ce8fd74b98dd20f573930783d16c7d30eb588acd5de3b47d76a8a2   ./application -Dqua...   54 seconds ago       Up 53 seconds ago       0.0.0.0:3333->8080/tcp   reverent_kirch

curl localhost:3333

**Comment by cescoffier** [comment]
@marcredhat I just opened a PR to fix the doc.

Can you try with: `mvn clean package -Pnative -Dnative-image.docker-build=true`

**Comment by cescoffier** [comment]
@marcredhat about the zlib requirement, it is in the docker image or on the host? (sorry I don't have a RHEL8 machine)

**Comment by cescoffier** [comment]
@gsmet would you be able to test from your linux

**Comment by marcredhat** [comment]
thank you! 
zlib is a requirement on the host. 
please also find a 1-minute video (build and run using buildah and podman) at http://bit.ly/2IkIKEr

**Comment by gsmet** [comment]
So the zlib-devel requirement was in our CONTRIBUTING.md but not in our guides. I added it here.

About including `podman` in the guides, why not. @cescoffier WDYT? I wouldn't want to make the guides less clear because of that. Or maybe we need a specific one?

**Comment by gsmet** [comment]
Closing as out of date.
