### ISSUE TITLE
Duplicated persistence units and entities in dev ui

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#20683]
### Describe the bug

Dev ui duplicates entities and persistence units in the "persistence unit" view on hot reload:

### Expected behavior

No duplication.

### Actual behavior

![image](https://user-images.githubusercontent.com/1223135/136911163-264111fe-f052-4684-8544-2c1bf96fe814.png)

### How to Reproduce?

Download the hibernate-orm-quickstart
mvn quarkus:dev
open dev ui
Go to the persistence unit view
Press s in the console to force restart
refresh the page
The entities are duplicated

If your app has multiple persistence units, they get duplicated as well

### Output of `uname -a` or `ver`

MSYS_NT-10.0-19043 NANB7NLNVP2 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys

### Output of `java -version`

openjdk 17 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739) Maven home: C:\eclipse\tools\apache-maven Java version: 17, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Can you check 2.4.0.CR1?

I remember fixing something similar

**Comment by Postremus** [comment]
@geoand Still happens with 2.4.0.CR1.

![image](https://user-images.githubusercontent.com/1223135/136925294-42aeeeef-c058-4241-baa8-ce59b6e63379.png)
