### ISSUE TITLE
Opentelemetry NonApplicationEndpointSampler should consider http.root-path

### ISSUE THREAD

**Issue by stefanorg** [quarkusio/quarkus#20698]
### Describe the bug

With open-telemetry extension installed and enabled, the default behaviour is to ignore non application uri `suppress-non-application-uris: true`

With the default sampler implementation at runtime we got a`NonApplicationEndpointSampler` instantiated.
The default implementation doesn't take in consideration the application context root 

```
 @Override
    public SamplingResult shouldSample(Context parentContext, String traceId, String name, SpanKind spanKind,
            Attributes attributes, List<LinkData> parentLinks) {


// if context-root is myapplication, name will be myapplication/q/health/ready
// so this check will fail
        if (name.startsWith("q/") && spanKind == SpanKind.SERVER) {
            return NEGATIVE_SAMPLING_RESULT;
        }
        return root.shouldSample(parentContext, traceId, name, spanKind, attributes, parentLinks);
    }
```

### Expected behavior

If my application context-root is `myapplication` every request under `myapplication/q/*` should be ignored by the sampler if `suppress-non-application-uris` is `true`

### Actual behavior

Actually every check under `myapplication/q/*` get sampled.

**Comment by gsmet** [comment]
@radcortez looks like one we could tackle easily and be done with?

**Comment by radcortez** [comment]
Yes, the plan is to implement that. OTel is going to offer an API to disable selected endpoints, but we need to move to their config API, which is missing a few things for us to use properly. I'm discussing this with the OTel community, so we can add what is missing.

**Comment by radcortez** [comment]
Thinking about this a little better, it may take a while for us to have OTel fully integrated to use their config for this. I'll probably just add it directly into Quarkus for now.
