### ISSUE TITLE
Improve configuration when using TestContainer

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2069]
When using TestContainers, the container runtime may assign a random port to your container (let's say your database). We would need in this case to update the properties to use these values.

It may be possible with a specific config source and a few variables.

As an example: https://github.com/testcontainers/testcontainers-java/blob/3b9e61e2b69db264db4e3f18dce8194d4debd2cf/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java#L12

**Comment by cescoffier** [comment]
@lordofthejars You mention something like this on Twitter if I'm not mistaken.

**Comment by lordofthejars** [comment]
Exactly, happy to help on this. If you have something in mind we can discuss here.

**Comment by emmanuelbernard** [comment]
Some more comment

OK, can you open an issue with add support for property driven by testcontainer.
I think it should be generalized with a way in the test framework to set properties that will be used by @QuarkusTest to boot. Should be a quarter of a night of Stuart ;P

But Alex if you are up for it, It hink that's a controllable contribution. From a MP Config PoV, we need a new Config source or whatever they call it with a higher priority than the file one. And that config source is fed by the test framework infrastructure before we start Quarkus proper.

It gets tricky when you mix @SubstrateTest into the mix as the config is really to be passed to the native image. For this, we could make sure to call the executable with the right -D for each property overridden

**Comment by emmanuelbernard** [comment]
@lordofthejars is assigned to it as per quarkus-dev@ discussion

**Comment by lordofthejars** [comment]
PR: https://github.com/quarkusio/quarkus/pull/2311

**Comment by gsmet** [comment]
Closing
