### ISSUE TITLE
Health check throw an NPE if the name if not set

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2072]
If you declare a health without a name, you get:

```
 java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
```

I don't disagree about the error, just that it should mention that the `name` must be set (and not this message).

**Comment by kenfinnigan** [comment]
Raised issue in SmallRye Health: https://github.com/smallrye/smallrye-health/issues/28
