### ISSUE TITLE
Duplicate error log in tests/no logs in tests on exception in QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by Legion2** [quarkusio/quarkus#20749]
### Describe the bug

Error and warnings are logged twice during tests, probably because multiple logging handlers are registered.
On the other hand info logs and below are not logged if there is an exception in `QuarkusTestResourceLifecycleManager`, this was already discussed in #10885. However it is not solved according to the principle of least surprise.

### Expected behavior

During tests everything that is logged is handled according to the logging config, even if there is an exception in a `QuarkusTestResourceLifecycleManager`. There should only be the log handlers configured in quarkus and no other default handlers that create duplicate logs on the console.

### Actual behavior

If there is an exception in a `QuarkusTestResourceLifecycleManager`, nothing is logged to the console from the `InitialConfigurator.DELAYED_HANDLER`.
There is a default handler registered that logs errors and warnings to the console without any formatting, which can not be configured with quarkus.

### How to Reproduce?

> Examples are in kotlin

```kotlin
class DemoLifecycleManager : QuarkusTestResourceLifecycleManager {

    private val logger = LoggerFactory.getLogger(this::class.java)

    override fun start(): Map<String, String> {
        logger.info("log info")
        logger.warn("log warn")
        logger.error("log error")

        //throw RuntimeException("error")
        return emptyMap()
    }

    override fun stop() {

    }
}
```
1. Create a new demo quarkus project
2. enable standard stream logging for tests in maven or gradle
```kotlin
tasks.withType<Test> {
    testLogging {
        events("STARTED", "PASSED", "FAILED", "SKIPPED")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
        showStackTraces = true
    }
    systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
}
```
3. add the DemoLifecycleManager and add it to a `@QuarkusTest`
```kotlin
@QuarkusTestResource.List(
    QuarkusTestResource(DemoLifecycleManager::class),
)
```
4. run the test
5. observe that the following is printed before the test is started
```
log warn
log error
```
and
```
    2021-10-13 22:01:14,160 INFO  [org.acm.DemoLifecycleManager] (pool-3-thread-1) log info
    2021-10-13 22:01:14,165 WARN  [org.acm.DemoLifecycleManager] (pool-3-thread-1) log warn
    2021-10-13 22:01:14,165 ERROR [org.acm.DemoLifecycleManager] (pool-3-thread-1) log error
```
is printed during the test (`log warn` and `log error` are duplicate)
6. now change `DemoLifecycleManager` to throw an exception
7. run the test again
8. observe that
```
log warn
log error
```
and the exception stacktrace is printed, but the `log info` is missing.
I did not find any configuration options that change the logging behavior of the first 
```
log warn
log error
```

### Output of `uname -a` or `ver`

Linux leon-pc 5.11.0-37-generic #41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2) OS:           Linux 5.11.0-37-generic amd64

### Additional information

The project is created with `code.quarkus.io` and the kotlin extension and Gradle with Kotlin DSL.

**Comment by gsmet** [comment]
@famod probably related to your current work?

**Comment by famod** [comment]
It might be related, need to check.

@Legion2 can you provide a reproducer, please? This would speed things up. Thanks!

**Comment by famod** [comment]
Closing due to lack of feedback/lack of a reproducer. I do think this is not an issue anymore.

Please open a new issue in case you thinks something is not right or missing.
