### ISSUE TITLE
Java 17 is not reflected as source/target of generated project

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#20752]
### Describe the bug

Java 17 is not reflected as source/target of generated project.

In dev mode one sees warning like this `2021-10-13 22:56:53,445 WARN  [io.qua.dep.dev.JavaCompilationProvider] (vert.x-worker-thread-0) system modules path not set in conjunction with -source 11, line -1 in [unknown source]`

### Expected behavior

Project should use 17 as the value for maven.compiler. source / target / (release?).

### Actual behavior

Generated pom.xml when using Java 17 looks like this:

```xml
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
```

### How to Reproduce?

setJdk17

mvn io.quarkus.platform:quarkus-maven-plugin:2.4.0.CR1:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformArtifactId=quarkus-bom -DplatformVersion=2.4.0.CR1
mvn -f app-generated-skeleton quarkus:dev

sed -i "" "s/RESTEasy/RESTEasy v2/" app-generated-skeleton/src/main/java/org/my/group/GreetingResource.java
curl localhost:8080/hello

check the log, you will see "WARN  [io.qua.dep.dev.JavaCompilationProvider] (vert.x-worker-thread-0) system modules path not set in conjunction with -source 11, line -1 in [unknown source]"

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.4.0.CR1

**Comment by rsvoboda** [comment]
Docker templates need to be customizable too.

**Comment by netodevel** [comment]
Hi Folks, i need a tip to update the dockers templates to java 17;

@ia3andy, you gave the hint to transform codestarts `/src/main/resources/codestarts/quarkus/tooling/dockerfiles/codestart.yml` into a qute template;

but I didn't find it in the code where I register this template and pass values;




The progress of this issue can be seen here: https://github.com/quarkusio/quarkus/pull/20849

**Comment by ia3andy** [comment]
@netodevel I meant you can directly use `{#if java.version == "..."}` there:
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.jvm#L5
- https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/src/main/docker/Dockerfile.tpl.qute.legacy-jar#L5

**Comment by gsmet** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/20849
