### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by badping** [quarkusio/quarkus#2079]
Hello,
i wrote three very simple performance tests to compare Quarkus with SpringBootDocker images.
I created a native image from Quarkus compared with a SpringBootDocker image.
My test can be found here:
https://github.com/badping/quarkus-quickstarts/commit/c649b0c63e8fdd3615ed34b7763fdf8e9cdaf767

On spring boot it can be found here:
https://github.com/badping/gs-spring-boot-docker/commit/9f2a68f07f6e90f42d15558553dd0320a024a4ea

For example the /cpu request run on spring boot around with 1,7s and on Quarkus native image with 2,7s.
To be honest i expected that quarkus is at least as fast as the spring boot image.
I tested it on my local docker with 2 threads 5GB. And on AWS EKS with 1 thread and 5GB.
Both systems had similar results, so that Quarkus image was much slower in both cases.

Here you can see my results in ms:

Running /cpu on Springboot:
cpu,2042,1859,1709,1724,1707,1715,1725,1709,1728,1731

Running /cpu on Quarkus native:
cpu,2737,2769,2730,2738,2759,2756,2732,2749,2762,2742

Running /tmp on Springboot: tmp,8422
Running /tmp on Quarkus native: tmp,11816

Running /memory on Springboot: memory,6157,3462,3106,6410,3399,3110,2773,3910,3254,2892

Running /memory on Quarkus native:
memory,7057,5409,6503,7698,4662,7690,6778,5657,7355,8223

**Comment by johnaohara** [comment]
@badping thanks for sharing your benchmark.  I am assuming that you spun up the applications and timed hitting the rest endpoint? 

So, in reality, I think this benchmark is actually testing the difference between the Virtual Machines (i.e. JVM vs GraalVM), rather than testing differences between frameworks (Quarkus vs SpringBoot). 

GraalVM and JVM are designed for different use cases, so I would expect them to be different, but Quarkus can run in native mode or JVM mode, so if you want high performance in super tight loops over Random data, then choose the JVM.

I suspect if you run Quarkus on a JVM mode (i.e. not a native image) you will probably see similar results, the frameworks are doing very little in this benchmark.

**Comment by badping** [comment]
@johnaohara Thank you for your quick response.

I performed the test now with jvm Dockerfile (like you suggested):
./mvnw clean package
docker build -f src/main/docker/Dockerfile.jvm -t quarkus-quickstart/quickstart .
docker run -i --rm -p 8080:8080 quarkus-quickstart/quickstart

But the results are even more worse:
curl localhost:8080/cpu :
cpu,6485,6400,6428,6407,6406,6411,6420,6435,6412,6407

Any idea whats broken with this setup, compared to spring boot ?
Maybe you can spent 3 minutes and run my example yourself to verify it (2 Threads + 5GB Docker).

Thank you !

**Comment by johnaohara** [comment]
@badping I ran both examples you provided, on the same JVM, with the same configuration;

Quarkus: cpu,2086,2151,2187,2223,2231,2252,2273,2269,2268,2321
SpringBoot: cpu,2132,2264,2258,2301,2259,2265,2265,2226,2234,2223

There are no significant differences, between invoking these functions via Quarkus or SpringBoot. 

We do want to think about what defaults we use in the docker file though, as they are clearly not optimal 

Thanks

**Comment by badping** [comment]
Yes i agree its not a problem of quarkus itself (like you said).
The docker file configuration is causing the performance diffrence.
Thanks !

**Comment by johnaohara** [comment]
@badping please can you retest with the changes in #2105?

Thanks

**Comment by badping** [comment]
@johnaohara 
Now cpu performance is the same like on springboot image.
But the /tmp is around 1s = 20% slower.
Any idea why IO is a bit slower than the springboot image ?

Here are the results:
Quarkus:
cpu,1593,1530,1436,1439,1437,1444,1435,1437,1436,1436
cpu,1453,1409,1405,1404,1405,1406,1405,1404,1406,1404
tmp,6177
tmp,6032
tmp,5983
tmp,6168
memory,7003,8434,7190,7273,5928,5526,7486,6773,6691,8065

Springboot:
cpu,1604,1514,1407,1409,1410,1403,1405,1408,1409,1408
cpu,1445,1403,1402,1402,1403,1403,1402,1402,1406,1395
tmp,5057
tmp,5090
tmp,4923
tmp,4975
memory,7529,6740,7175,5638,6977,7855,7516,5705,6907,7423

Thanks!

**Comment by badping** [comment]
On more question about the native image. Is there also a diffrent image possible to speed up cpu performance ? For me the native is running with 2,4s instead of 1,4s on jvm image. Or do we need to live with it ?
Thanks.

**Comment by gsmet** [comment]
Closing this as it's an old discussions and things have changed dramatically since then.
