### ISSUE TITLE
Azure Functions - Create project with Archetype broken

### ISSUE THREAD

**Issue by LoRez** [quarkusio/quarkus#20814]
Creatiing a project as described in the Azure Functions Guide with 

mvn archetype:generate \
    -DarchetypeGroupId=io.quarkus \
    -DarchetypeArtifactId=quarkus-azure-functions-http-archetype \
    -DarchetypeVersion=2.3.0.Final

generates broken project.

Group Ids and Archetype Ids are the ones from the archetype

<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-azure-functions-http-archetype</artifactId>
  <version>2.3.0.Final</version>

and the pom contains hardcoded paths

```
/path/to/quarkus-release/work/quarkus/extensions/azure-functions-http/maven-archetype/target/azure-functions/${functionAppName}
```

and it seems the  version for 

<azure.functions.maven.plugin.version>1.9.1</azure.functions.maven.plugin.version>

and caused problems for me with the latest vesion of az cli.

When I did uses 1.12.0.Final as archetype version the pom looked ok.

**Comment by geoand** [comment]
It seems like in https://github.com/quarkusio/quarkus/blob/2.3.0.Final/extensions/azure-functions-http/maven-archetype/src/main/resources/archetype-resources/pom.xml, `project.build.directory` is getting set at release time.
