### ISSUE TITLE
REST client guide needs to be updated because restcountries.eu is no longer supported 

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#20810]
### Describe the bug

The test API restcountries.eu in [REST client guide](https://quarkus.io/guides/rest-client) is being discontinued - https://github.com/apilayer/restcountries/pull/280. It already doesn't work and thus REST client guide needs to be updated.

### Expected behavior

Guides should work?! :)

### Actual behavior

https://restcountries.eu is not responding.

### How to Reproduce?

Follow the instructions in the guide.

### Additional information

There are two possible ways I've found so far:

1/ the replacement https://countrylayer.com/ but it requires registration for API key
2/ backup https://restcountries.com/ which is open-sourced and seems to be maintained https://gitlab.com/amatos/rest-countries

**Comment by xstefank** [comment]
I will gladly fix this but I need to know which road to take.

**Comment by michalszynkiewicz** [comment]
I think we should rather switch to a different endpoint in both quickstarts and the guide.
Wiremocking countries makes the tests pass but the app will still fail.

On an issue about Rest Client codestart @ia3andy wrote that for codestart we could use https://code.quarkus.io/api/extensions
Maybe we could use it for the quickstart too?

**Comment by xstefank** [comment]
@geoand so just to confirm, switching to restcountries.com ?

**Comment by xstefank** [comment]
I don't think we need to expect many people will be doing the guide at the same time so the load should be minimal. OK, let's use `stage.code.quarkus.io`. Thanks, @ia3andy.

**Comment by xstefank** [comment]
@ia3andy I can take a look after this one, sure.
