### ISSUE TITLE
Support javax.imageio

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2081]
Trying to access code in `javax.imageio`, I could this exception at *runtime*:

    Caused by: java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images
	at javax.imageio.ImageIO.read(ImageIO.java:138)

Support for this would be helpful to implement use cases like creating thumbnail images in a native application (serverless style).

**Comment by fiorenzino** [comment]
some workaround for this?

**Comment by gsmet** [comment]
@dmlloyd do you know if they added support for `javax.imageio` in GraalVM?

**Comment by dmlloyd** [comment]
No they did not, but it might be a non-issue with GraalVM soon.  I think we still should think about implementing this ourselves though in a more lightweight way.

**Comment by murphye** [comment]
I ran into this issue, and am instead using: http://commons.apache.org/proper/commons-imaging/ to read image data.

However, it has significant limitations as it cannot read many JPEGs that have been compressed. Also PNGs cannot even be ready in native image mode with Commons.

Tried to find other solutions and nothing is available.

**Comment by dmlloyd** [comment]
Have we tried again recently?

**Comment by gsmet** [comment]
@dmlloyd I don't think so.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/commit/12f63afa48705fbd855f8a5ca4101d8cf13f5de7 this is now supported
