### ISSUE TITLE
Improve how need for JNI is reported

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2082]
When building a native image containing code that calls native methods via JNI, I get a build error like this:

    Error: Unsupported method sun.java2d.DefaultDisposerRecord.invokeNativeDispose(long, long) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)

It would be nice if Quarkus could amend this with the right way of doing this, e.g. the Maven plug-in could say: "Add the <enableJni>true</enableJni>" configuration option".

Bonus: perhaps the plug-in could even generate/show a template for the required configuration to enable calling the method in question?

**Comment by Dufgui** [comment]
I take a look at it.

**Comment by Dufgui** [comment]
https://github.com/quarkusio/quarkus-quickstarts/pull/235

**Comment by emmanuelbernard** [comment]
I think ti's superseded by https://github.com/quarkusio/quarkus/issues/2999 if I understand correctly.

**Comment by Dufgui** [comment]
I can continue on it ? Are you ok with my quickstart/test case ?

**Comment by emmanuelbernard** [comment]
So JNI integration is more a extension writer effort than an end user. On top of that we want to introduce this notion of JNI build item. So the quickstart is likely to evolve. It might be a better use of your time to work on the JNIBuildItem first.

**Comment by gunnarmorling** [comment]
As a test for JNIBuildItem you might use the Kafka Streams extension. This
currently requires "jni" to be set to "true" manually in the plug-in config
for native image mode, which shouldn't be needed any longer if it were to
use JNIBuildItem.

>

**Comment by cescoffier** [comment]
I believe this can be closed. JNI support has been improved a lot.

**Comment by Karm** [comment]
@cescoffier Close this one, please. JNI access works, and the particular error @gunnarmorling experienced is addressed with AWT extension via #20850 anyway...
