### ISSUE TITLE
Logger producer should use @DefaultBean

### ISSUE THREAD

**Issue by dirkweil** [quarkusio/quarkus#20821]
### Description

Quarkus' producer for org.jboss.logging.Logger causes an AmbiguousResolutionException if the application contains an own logger producer (for whatever reason; for me it was porting a JEE application to Quarkus while keeping as much of the code as possible).

### Implementation ideas

To enable people using their own producers, `io.quarkus.arc.runtime.LoggerProducer` should declare `@DefaultBean` for both producer methods.

**Comment by geoand** [comment]
@mkouba WDYT about this one?
It seems reasonable to me
