### ISSUE TITLE
Default Hibernate Envers properties override those defined in persistence.xml

### ISSUE THREAD

**Issue by blxbrgld** [quarkusio/quarkus#20831]
### Describe the bug

I'm trying to upgrade from **Quarkus 2.2.1.Final** to **2.3.0.Final** and it seems like the Hibernate Envers properties defined in `persistence.xml` are overriden by the Quarkus Envers [properties](https://quarkus.io/guides/all-config#quarkus-hibernate-envers_quarkus-hibernate-envers-hibernate-envers), even though i have not defined any in the `application.properties`.

More specifically, my `persistence.xml` file looks like this:

```
<properties>
    <property name="org.hibernate.envers.audit_table_prefix" value="PREFIX_" />
    <property name="org.hibernate.envers.audit_table_suffix" value="_SUFFIX" />
    <property name="org.hibernate.envers.store_data_at_delete" value="true" />
</properties>
```

and even though I do not define the `audit_table_suffix` in `application.properties`, the default `_AUD` takes precedence and Envers fails because (for example) `PREFIX_USER_AUD` does not exist (`java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist`). 

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19042 NRB092515 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys

### Output of `java -version`

java version "11.0.5" 2019-10-15 LTS

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by Sanne** [comment]
In PR ##21289 I've added some configuration properties - in particular, the ones mentioned here.

I don't want to expose all configuration properties, but rather be selective to the ones actually useful (many configurations in Hibernate exist only because of backwards compability) - so please do let me know which other properties you'd really like to see by opening more issues. thanks :)

**Comment by gsmet** [comment]
I think we should close this issue as we clearly want people to use the Quarkus config. We can add more settings if need there if need be but I think @Naros added a lot of them here: https://github.com/quarkusio/quarkus/pull/21872 .

If, for some reason, you cannot define your config with Quarkus config, please open a new issue with an example of what you are trying to accomplish and can't.

Thanks.
