### ISSUE TITLE
Classes used in REST client are not properly serialized when used on Native images

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#20878]
We have a REST client that performs a POST call passing a body. The problem is that this class, when used on a Native image, is always serialized  as `{}` ignoring its properties.

Example:
```
@Path("/")
@RegisterRestClient(configKey = "my-service.api-url")
interface MyApi {
    @POST
    @Consumes(APPLICATION_JSON)
    @Produces(APPLICATION_JSON)
    fun sendMessage(message: MessageBody): String
}

data class MessageBody(val message: String)
```
If I annotate the `MessageBody` class with `@RegisterForReflection` it works. But I would expect it worked without the annotation considering the class is used as a parameter. 

### Quarkus version or git rev

2.0.3.Final

**Comment by michalszynkiewicz** [comment]
Does it also happen for Java?
Can you test the newest released Quarkus version and provide a reproducer if it still fails?

**Comment by geoand** [comment]
Also, does this happen with newer versions of Quarkus?

**Comment by geoand** [comment]
Closing as we never got a response about whether this is still an issue. Feel free to reopen or comment if this is still an issue
