### ISSUE TITLE
Hibernate Validator: Wrong MediaType resolution in Resteasy Reactive

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#20888]
### Describe the bug

The hibernate validator extension only takes into account the `@Produces` annotation set at Method/Class level. The `accept` header set by users is ignored. For example, having:

```
@GET
@Path("/rest-end-point-validation/{id}/")
@Produces({ MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN })
public String testRestEndPointValidation(@Digits(integer = 5, fraction = 0) @RestPath("id") String id) {
    return id;
}
```

When there is validation errors, the result will always be JSON, regardless if the user calls it with the HTTP header `ACCEPT=text/plain`. 

### Expected behavior

The hibernate validator should take into account the header ACCEPT to serialise the validator errors.
This affects to the RESTEASY classic and reactive extensions.

### How to Reproduce?

1.- `git clone https://github.com/Sgitario/quarkus-test-suite`
2.- `cd quarkus-test-suite`
3.- `git checkout reproducer_20859`
4.- `cd http-minimum`
5.- `mvn clean verify` to use 999-SNAPSHOT
or `mvn clean verify -Dquarkus.platform.version=2.4.0.CR1` to use 2.4.0.CR1

See commit https://github.com/Sgitario/quarkus-test-suite/commit/fbad513377bac62c3e81a1e45ee5e99b5e378b6e

**Comment by geoand** [comment]
@Sgitario is this still an issue? If so, do you plan to address it?

**Comment by Sgitario** [comment]
> @Sgitario is this still an issue? If so, do you plan to address it?

This is still an issue and I can address it. Will provide a PR soon.

**Comment by geoand** [comment]
Thanks
