### ISSUE TITLE
Finalize multiple datasources support for Agroal

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2088]
@LightGuard offered to take a look at this one so dumping what I have in mind.

In the end, this issue is mostly about documenting properly what we already had.

### ~~Move named datasources to `.named` config namespace~~

**Apparently, it won't be an issue.**

Right now, named datasources are implemented like this:
```
quarkus.datasource.datasource2.driver=org.h2.Driver
quarkus.datasource.datasource2.url=jdbc:h2:tcp://localhost/mem:datasource2
quarkus.datasource.datasource2.username=username2
quarkus.datasource.datasource2.min-size=2
quarkus.datasource.datasource2.max-size=12
```
The issue is that the datasource name could conflict with current or future Agroal properties (current is not really an issue as you will have an error but future is really a problem).

Moving to something like that would help:
```
quarkus.datasource.named.datasource2.driver=org.h2.Driver
quarkus.datasource.named.datasource2.url=jdbc:h2:tcp://localhost/mem:datasource2
quarkus.datasource.named.datasource2.username=username2
quarkus.datasource.named.datasource2.min-size=2
quarkus.datasource.named.datasource2.max-size=12
```

### Check if `MultipleDataSourcesConfigTest` can be enabled again

We had to disable this test because it was not possible to have several tests with different configurations: the configuration was cached somehow.

It's possible that David fixed it already, let's see if it's fixed.

### ~~Get rid of the `@DataSource` qualifier~~

Right now, it's used a a poor man's `@Named` as I wasn't able to make `@Named` work properly with a default datasource being unnamed (and for which I don't want a `@Named` to be necessary).

Let's see if we can fix that.

**Comment by dmlloyd** [comment]
It would not conflict with a future Agroal property unless the property name would have the same sub-keys as a named data source.

For example, if I have a data source called `foo`, and Agroal added a property called `foo`, I'd have this:

```properties
quarkus.datasource.foo=something something
# here are the named data sources
quarkus.datasource.foo.driver=org.h2.driver
# ... and so forth
```

If Agroal added a property called `foo.bar`, it'd still be OK:
```properties
quarkus.datasource.foo=something something
quarkus.datasource.foo.bar=something else
# here are the named data sources
quarkus.datasource.foo.driver=org.h2.driver
# ... and so forth
```

So I wouldn't worry overmuch about this problem, especially if other high priority are in process already.

> ### Check if `MultipleDataSourcesConfigTest` can be enabled again
> We had to disable this test because it was not possible to have several tests with different configurations: the configuration was cached somehow.
> 
> It's possible that David fixed it already, let's see if it's fixed.

I'll have to look into why this was happening.  I recall a class loading related issue with config caches but I thought I addressed the problem at least once.  Given the big changes over the last couple of weeks, it might not be fully solved.

**Comment by gsmet** [comment]
> It would not conflict with a future Agroal property unless the property name would have the same sub-keys as a named data source.

Ok, that's good to know.

So maybe we can drop this part for now and work on the rest, @LightGuard .

**Comment by LightGuard** [comment]
Okay, sounds to me like what we want to do here now is figure out the bean resolution with datasources, correct?

**Comment by gsmet** [comment]
Yeah, mostly see if we can do better than having a specific qualifier.
