### ISSUE TITLE
CDI Bean injection inside Mocked Beans does not seem to work using QuarkusTest

### ISSUE THREAD

**Issue by janknobloch** [quarkusio/quarkus#20906]
### Describe the bug

Hey all,  @geoand  in particular.

Im facing some issues with Service Bean Injection Inside Mocked Beans:

Stating:

https://quarkus.io/blog/mocking/

```
Finally, note in the example above we didn’t mock InvoiceService, which meant that the real InvoiceService was being used in OrderServiceTest.
```

I would assume that using `@Inject` combined with `QuarkusMock.installMockForType()` the injected beans used inside my mock are automatically injected and ready to use. I actually thought in my old project this was working fine - however all injected beans in my mocked service are just null.

Debugging the mocked Bean I can see that in the original Bean inside the mock the injection points for the inject references are set but in the mock itself they are all null.

Also it does not matter if I use `@Inject `or `@InjectMock` the behaviour exposed seems to be identical. - which would make sense you're stating they have the same internals.

Can someone please point out to me how (if using `@QuarkusTest`) CDI properly injects non-mocked / spy-ed beans into my services, or if this is indeed a bug?

I build a minimal reproducer so i'm hopefully not wasting anyones time, feel free to send my a PR if i did something wrong or missed something crucial.

https://github.com/janknobloch/quarkus-mock-injection-issues

Cheers

Jan

### Expected behavior

CDI beans inside an injected Mock/Spy Bean should be available

### Actual behavior

CDI beans inside an injected Mock/Spy Bean are all null.

### How to Reproduce?

See my reproducer project run the tests inside.
https://github.com/janknobloch/quarkus-mock-injection-issues

### Quarkus version or git rev

2.2.3 final

**Comment by geoand** [comment]
This is expected behavior. When using `@InjectMock`, you need to properly setup all the aspects of the mock - i.e. all the methods you plan to exercise, otherwise the Mockito default will be used.
When using `@InjectSpy` all calls are forwarded to the original bean by default.

**Comment by janknobloch** [comment]
thanks for the clarification @geoand. 

But shouldn't this scenario then work as its "similar" if not equal to @InjectSpy:

```
	@Inject
	MainResource mainResource;

	@BeforeAll
	public static void beforeAll() {
		MainResource spy = Mockito.spy(MainResource.class);
		when(spy.callToInjectedBean()).thenCallRealMethod();
		QuarkusMock.installMockForType(spy, MainResource.class);
	}

	@Test
	public void testInjectedService() {

		assertEquals("injected", mainResource.callToInjectedBean());
	}
```

I strongly feel that if this is not the case should kind of packed into the guide here (https://quarkus.io/blog/mocking/)?

As the outcome is also a spy - even forcing the real method use, but it will fail as the dependencies are not in place?
How would this code fragment look to inject the needed services to the spy created?

The quide kind of implicitly only talks about making your code more clean using @InjectMock over @Inject using BeforeEach / BeforeAll respectively. Not about having a severe impact if you try the same behaviour with @InjectSpy vs @Inject using BeforeEach / BeforeAll creating a spy as stated above.
