### ISSUE TITLE
RESTEasy adapter for Amazon Lambda support

### ISSUE THREAD

**Issue by evanchooly** [quarkusio/quarkus#2091]
We need a [RESTEasy adapter](https://github.com/resteasy/Resteasy/tree/master/server-adapters) that registers a simple Java lambda which transforms the passed in [AwsProxyRequest](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java) to the HTTP payload internally used to dispatch RESTEasy requests. This will allow us to plug RESTEasy directly into AWS's built-in openjdk (which is modified for performance) and the custom provider we will use for native images.Along with other RESTEasy server adapters, the [Jersey implementation](https://github.com/awslabs/aws-serverless-java-container/tree/master/aws-serverless-java-container-jersey) in their Serverless Java Container can be used as a reference. Although we do not need (and probably do not want) to pull in this project as a dependency.

**Comment by gsmet** [comment]
This was done a while ago.

**Comment by grottah** [comment]
Hi, i know this is close, but i need a little help to find this implementation. I need a solution to code my own set of lambdas. i Know Quarkus has a magic support (https://quarkus.io/guides/amazon-lambda-http), but as I said before i need to tuning my own  lambdas (log, memory, etc...). The jersey is quite easy, https://aws.amazon.com/blogs/opensource/java-apis-aws-lambda/. I need the same in RESTEasy.
