### ISSUE TITLE
decouple Undertow from RESTEasy

### ISSUE THREAD

**Issue by evanchooly** [quarkusio/quarkus#2092]
We need to decouple Undertow from RESTEasy, which is something we have been needing to do anyway. This will allow us to avoid pulling in a whole server side stack on simple client usage, and it will also allow us to minimize the thread usage and so on.

**Comment by kenfinnigan** [comment]
Are you referring to use of SmallRye REST Client? Or a different client usage?

**Comment by evanchooly** [comment]
@n1hility ?

**Comment by gsmet** [comment]
This has been done.
