### ISSUE TITLE
Cannot Stop Application Once It Is Started

### ISSUE THREAD

**Issue by felix-seifert** [quarkusio/quarkus#20952]
### Describe the bug

I created a simple application which starts to consume a stream of Tweets directly after the application startup with the annotation`@Startup`. It the publishes a selection of these Tweets to a Kafka topic. After I start the application in either dev mode or production mode (JAR or native), I cannot stop the application. Even though I close the terminal I started the application in, the application continues to consume tweets from the stream. When I run the application in dev mode through IntelliJ, I have to press the stop button twice to stop the application.

### Expected behavior

I want the application to stop when I press `Ctrl + C`.

### Actual behavior

The application does not stop when I press `Ctrl + C` and have to restart my computer to stop the app.

### How to Reproduce?

The relevant class which should be initiated automatically after application start:

```java
@Startup
@ApplicationScoped
public class TwitterListener {

  private static final Logger LOGGER = Logger.getLogger(TwitterListener.class);

  @Inject
  TwitterClient twitterClient;

  @Inject
  @Channel("tweets")
  Emitter<Tweet> tweetEmitter;

  @PostConstruct
  public void startListenerAfterConstruction() throws IOException, URISyntaxException {
    final Map<String, String> rules = getRules();
    final List<String> existingRules = twitterClient.getExistingRules();
    if (!existingRules.isEmpty()) twitterClient.deleteRules(existingRules);
    twitterClient.createRules(rules);

    final Stream<Tweet> tweetStream = twitterClient.connectStream(1024); // Number defines size of BufferedStream
    consumeStream(tweetStream);
  }

  private void consumeStream(final Stream<Tweet> tweetStream) {
    tweetStream
        .parallel()
        .filter(tweet -> tweet.information().isPresent())
        .peek(LOGGER::info)
        .forEach(tweet -> tweetEmitter.send(tweet));
  }
}
```

A list of the dependencies:
```xml
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20210307</version>
    </dependency>
    <dependency>
      <groupId>org.immutables</groupId>
      <artifactId>value</artifactId>
      <version>2.8.8</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

The rest of the `pom.xml` is standard and I did not any other plugins than the standard plugins.

### Output of `uname -a` or `ver`

Linux seifert-ubuntu 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

IDE in which I can stop application after pressing stop twice: IntelliJ IDEA 2021.2.3 (Ultimate Edition)

**Comment by geoand** [comment]
You should not be performing operations like this in a `@PostConstruct` method.

For

> The application does not stop when I press Ctrl + C and have to restart my computer to stop the app.

you don't need to restart your machine. You can identity the process using `jps` and then kill it forcibly using `kill -9 pid`
