### ISSUE TITLE
Add toString() on ConfigMapping generated classes

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#20985]
### Description

`ConfigMapping` classes do not implement a custom `toString()`, which would print the field values of the config object.
It would be ideal to generate a default `toString()` methods that prints all fields, so this could be used in a logging statement.

There are questions around config objects that contain sensitive information, such as passwords in clear text, even if this is an anti-pattern.
One option would be to either allow, or unallow a field to participate in the `toString()`, using for instance an annotation such as:
```
String username();

@ObfuscateInToString
String password();
```
In the `toString()`, this would be rendered as: `username="bob", password="***"`

Other ideas:
- obfuscation could be bypassed in some profile modes: `@ObfuscateInToString(exceptIn={"dev"})`
- auto-obfuscation based on well known field names: secret, password, ...
- no `toString()` method, except if `@ToString` is defined on the interface

The idea is to be secured by default.

/cc @radcortez

**Comment by radcortez** [comment]
Moved to https://github.com/smallrye/smallrye-config/issues/666.
