### ISSUE TITLE
OpenTracing Jaeger: Probabilistic sampler didn't work

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#21002]
### Describe the bug

When using a probabilistic sample (with 0.5 as sampling rate) no traces are generated.
When using a constant sampler (with 1 as sampling rate) traces are correctly generated.

### Expected behavior

We can use a probabilistic sampler in Quarkus.

### How to Reproduce?

Steps to reproduce:

1. Download the sample project (configured with a probabilistic sampler, see 
https://www.jaegertracing.io/docs/1.22/sampling/#client-sampling-configuration): [jaeger-probabilistic-sampler.zip](https://github.com/quarkusio/quarkus/files/7416198/jaeger-probabilistic-sampler.zip)
2. Start Jaeger: `docker run -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 jaegertracing/all-in-one:latest`
3. Start the applicaiton via `mvn quarkus:dev`
4. Call the endpoint a few times: `curl localhost:8080/hello`
5. Go to the Jager UI (should be on port 16686): nothing shows up!

If you switch to a constant sampler, traces will shows up, you can verify this by updating the configuration with
```
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
```

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19042.1237]

### Output of `java -version`

openjdk version "17" 2021-09-14

### Quarkus version or git rev

2.3.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by radcortez** [comment]
Hum, I've followed the repro steps and it seems to work fine for me:

![Screenshot 2021-11-05 at 17 37 16](https://user-images.githubusercontent.com/5796305/140554603-98e299c7-f6fb-4e29-acdb-4a13e1708b8b.png)

Can you confirm?

**Comment by radcortez** [comment]
The only difference that I have is the OS. Let me see if I can dig up a Windows VM to try that out.

**Comment by loicmathieu** [comment]
I'll ask on Monday one of my colleagues that have a Mac to test and see if it works.

**Comment by radcortez** [comment]
I was able to try this on my Windows VM and it also works... wondering if it may be a difference in the jaeger docker image we are getting? I would expect it would be the same for both of us.

**Comment by radcortez** [comment]
Any update on this?

**Comment by loicmathieu** [comment]
Just tried it on my Windows laptop using Quarkus 2.6.1 and I can reproduce the issue.

**Comment by loicmathieu** [comment]
Just tried also on my Linux laptop and I can also reproduce the issue.

**Comment by loicmathieu** [comment]
Using tcpdump I can clearly see that when using probabilistic sampler no UDB packet are sent to the port 6831 but when using constant sampler I can see the packets.

**Comment by radcortez** [comment]
Ok, I'll have another look.

**Comment by loicmathieu** [comment]
Thanks

**Comment by radcortez** [comment]
We were able to determine that this is caused by writing the probabilistic value in format, that the Jaeger configuration would not read property due to the default Locale.
