### ISSUE TITLE
Warning in `quarkus:dev` when using `quarkus-smallrye-graphql`

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#21030]
### Describe the bug

When running in dev mode (`quarkus:dev`) with the `quarkus-smallrye-graphql` extension, an unexpected warning is printed out:
```
2021-10-27 09:40:54,889 WARN  [io.qua.run.con.ConfigRecorder] (Quarkus Main Thread) Build time property cannot be changed at runtime:
 - quarkus.smallrye-graphql.print-data-fetcher-exception was 'null' at build time and is now 'true'
```

### Expected behavior

Aforementioned warning is not present in the log output.

### Actual behavior

Aforementioned warning is present in the log output.

### How to Reproduce?

Steps to reproduce:
1. 
```
wget -O ./smallrye-qraphql-warn-reproducer.zip "https://code.quarkus.io/api/download?S=io.quarkus.platform:2.3&a=smallrye-qraphql-warn-reproducer&nc=true&e=quarkus-smallrye-graphql"
```
Alternatively for `2.4`:
```
wget -O ./smallrye-qraphql-warn-reproducer.zip "https://code.quarkus.io/api/download?S=io.quarkus.platform:2.4&a=smallrye-qraphql-warn-reproducer&nc=true&e=quarkus-smallrye-graphql"
```

2.
```
unzip ./smallrye-qraphql-warn-reproducer.zip
cd ./smallrye-qraphql-warn-reproducer/
./mvnw clean quarkus:dev
```

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.3.1.Final, 2.4.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by jmartisk** [comment]
This must have something to do with https://github.com/quarkusio/quarkus/pull/20602
Perhaps @radcortez  has an idea

**Comment by radcortez** [comment]
I'll have a look.
