### ISSUE TITLE
Combination of quarkus-infinispan-client and quarkus-micrometer ends up with build error, missing microprofile-metrics-api

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#21033]
### Describe the bug

Combination of quarkus-infinispan-client and quarkus-micrometer ends up with build error `Could not resolve artifact org.eclipse.microprofile.metrics:microprofile-metrics-api::jar among the runtime dependencies of the application`

If quarkus-infinispan-client or quarkus-micrometer extensions are used individually the application can be used in dev mode and compiled.

But if they are combined the app ends up with Build step error.
```
io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception:
  java.lang.RuntimeException: Could not resolve artifact org.eclipse.microprofile.metrics:
    microprofile-metrics-api::jar among the runtime dependencies of the application
```

### Expected behavior

Build / dev mode works

### Actual behavior

Build / dev mode fails
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: 
  java.lang.RuntimeException: Could not resolve artifact org.eclipse.microprofile.metrics:microprofile-metrics-api::jar 
  among the runtime dependencies of the application
```

### How to Reproduce?

mvn io.quarkus.platform:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=my-groupId -DprojectArtifactId=my-app -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformGroupId=io.quarkus -DplatformArtifactId=quarkus-bom -DplatformVersion=999-SNAPSHOT -DquarkusRegistryClient=false -Dextensions=quarkus-infinispan-client,quarkus-micrometer

mvn -f my-app quarkus:dev 

mvn -f my-app clean package

### Output of `java -version`

Java 17

### Quarkus version or git rev

fa595c7359

**Comment by rsvoboda** [comment]
@karesti, @wburns can you comment about the need for MP metrics api dependency?

**Comment by gsmet** [comment]
For now, I think we should add `org.eclipse.microprofile.metrics:microprofile-metrics-api` to the Infinispan Client extension always. It's just an API, nothing big.

Until we consider moving to Micrometer but I'm not sure how easy it will be to coordinate this for all the consumers of Infinispan.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/21267 (fun fact: there is another issue hidden by this one).

**Comment by ebullient** [comment]
Suspense.... which other bug?

**Comment by gsmet** [comment]
I explained things in detail here: https://github.com/quarkusio/quarkus/pull/21267/commits/a3ea8822aa04742b41c5acf8eb0233ff912a05f5
