### ISSUE TITLE
Kafka SASL connection stopped working in 2.3.0, but works fine in 2.2.2 version

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#21045]
### Describe the bug

We use next configuration for connection to Kafka cluster: 

> kafka:

    health:
      enabled: true
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL}  #SASL_SSL here
    sasl:
      mechanism: SCRAM-SHA-512
      jaas:
        config: >
          org.apache.kafka.common.security.scram.ScramLoginModule
          required username=${KAFKA_JAAS_USERNAME}
          password=${KAFKA_JAAS_PASSWORD} ;
    ssl:
      truststore:
        location: ${SSL_TRUSTSTORE_LOCATION}
        password: ${SSL_TRUSTSTORE_PASSWORD}
        type: JKS
      endpoint:
        identification:
          algorithm: https

Sorry for the broken formatting, I was trying to insert it in different ways and this is the best I found.

So, using this configuration consumer can connect to Kafka cluster and it works perfectly fine in 2.2.0 version. We added this functionality a few versions ago and it was working great until Quarkus version was bumped to 2.3.0
In quarkus 2.3.0 next exception happens:

> {"timestamp":"2021-10-27T18:17:15.038Z","sequence":2123,"loggerClassName":"org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger","loggerName":"org.apache.kafka.clients.NetworkClient","level":"ERROR","message":"[Consumer clientId=kafka-consumer-_consumer-name-hidden_, groupId=_group-id-hidden_] Connection to node -1 (_cluster-ip-hidden_:9093) failed authentication due to: SSL handshake failed","threadName":"smallrye-kafka-consumer-thread-0","threadId":21,"mdc":{},"ndc":"","hostName":"service-586cf4c9db-6zv98","processName":"quarkus-run.jar","processId":1}

### Expected behavior

Kafka client successfully connects to cluster

### Actual behavior

failed authentication due to: SSL handshake failed

### How to Reproduce?

Sorry for not attaching the reproducer. I'm on my vacation right now (have no access to the environment), but I can help you with this issue next week. 

### Output of `java -version`

Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)

### Quarkus version or git rev

2.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0

### Additional information

I'm just a bit unsure about [this commit](https://github.com/quarkusio/quarkus/pull/20416/commits/c17f875d0c0668c84768e51150ad60a5d73f4e27) for 2.3.0 version:

![image](https://user-images.githubusercontent.com/71016973/139125460-6f1a22aa-6ce9-49ce-8051-11ad2a583702.png)

Are you sure **replaceAll** shouldn't be used instead? I don't know what was the reason to replace previous behaviour, it's just the only suspicious lines of code for me.

**Comment by OleKsimov** [comment]
I've made a small investigation and found some interesting things.
Let's start from the point that two pods with the same configuration but different Quarkus versions (2.2.2 vs 2.4.0) behave differently in the case of sasl_ssl Kafka connection.
When I set kafka.bootstrap.servers=10.0.x.x:9093 (IP) it works fine in Quarkus 2.2.2 but it fails in 2.4.0 with next messages in logs:

![image](https://user-images.githubusercontent.com/71016973/139943947-3cf36d82-60ad-4fda-9b1d-462cb03a699e.png)

There are no such messages in 2.2.2 versions.
BUT if I set kafka.bootstrap.servers=test-kafka-brokers.test-deps.svc:9093 (domain name), it works fine in both versions.

So I believe that something is wrong with resolving a domain name before the connection to Kafka is established.
It is definitely not about producer or consumer config: there are no ProducerConfig or ConsumerConfig logs shown in 2.4.0 version.
Here is some information that I see in Quarkus 2.4.0 logs using options "-Djavax.net.debug=ssl,handshake" that can be interesting for you:

![image](https://user-images.githubusercontent.com/71016973/139944229-50e91ec1-373b-4414-922e-ddef7926a71d.png)

![image](https://user-images.githubusercontent.com/71016973/139944260-f29e864d-1289-4013-a32f-163f2bb31b36.png)

![image](https://user-images.githubusercontent.com/71016973/139944288-5fb3c36d-6759-47eb-a80e-e01eec771f71.png)

**Comment by OleKsimov** [comment]
In the 2.2.2 version it works like a charm, resolving domain name from IP without any problems and showing Consumer and ProducerConfigs in logs. As I already said, I created two pods with the same configuration which differs only in Quarkus version. The problem is stable to reproduce. I believe it is a bug, but I understand how difficult it would be to fix on the other hand.

**Comment by cescoffier** [comment]
Let me guess: https://issues.apache.org/jira/plugins/servlet/mobile#issue/KAFKA-8562

Can you try setting the kafka client version to 2.8.0? However, do that in a staging environment, 2.8.1 contains important CVE fixes.

**Comment by OleKsimov** [comment]
@cescoffier 
Considering there won't be any Kafka downgrade in Quarkus because of CVE fixes in the 2.8.1 version, I believe it would be fine to have SASL connection configured with domain name instead of IP address and have a more secure version. 
Thanks for your help and for what you're doing.

**Comment by cescoffier** [comment]
Yes, we cannot downgrade.

Closing this issue.
