### ISSUE TITLE
Layout broken in Kafka Streams dev console topology view

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#21059]
### Describe the bug

If you have larger topologies, the rendered graph is shifted to the bottom, with lots of empty space at the top of the graph.

![Screenshot_2021-10-27 Apache Kafka Streams › Topology kstreams-fk-join-aggregator 1 0 0-SNAPSHOT](https://user-images.githubusercontent.com/28612/139215720-d07f643e-8583-4bd0-8bda-d076735f1ec1.png)

Note how this shows only the lower half of the text box on the left-hand side but the upper half of the rendered graph. 
Another image of the full page (ignore the black bar in the middle, that's an artifact from screenshotting in Firefox):

![Screenshot_2021-10-28 Apache Kafka Streams › Topology kstreams-fk-join-aggregator 1 0 0-SNAPSHOT](https://user-images.githubusercontent.com/28612/139216665-e259a8a0-67e4-4189-91d2-4897aced1c98.png)

This can be observed by running this example: https://github.com/debezium/debezium-examples/tree/main/kstreams-fk-join.

### Expected behavior

Align text box and graph at the top.

**Comment by danielpetisme** [comment]
Hi, I started to have a look at the UI issue.
I found a way to trim the top white space but I have to lose the width's diagram constraints (cf. the screenshot attached). You have to scroll to the right to see it all.

I'm considering going in another direction, I'm not sure it brings a lot of value to see both the Topology text description and Graph at the same time. Usually, you need either one (mainly the graph one) or the other (text is mostly used for copy/pasting).
I'm considering having a toggle: Only one of the 2 representations visible at a given time and button permitting to switch from one to the other

What do you think?

**Comment by gunnarmorling** [comment]
+1 for the option to switch between the two representations.

**Comment by danielpetisme** [comment]
Hi team, quick teaser
What do you think?
![image](https://user-images.githubusercontent.com/593564/143773842-1fe98566-5f44-41a1-ac93-2427f5147ad2.png)

**Comment by gunnarmorling** [comment]
> What do you think?

Pretty cool, I'd say!

Am So., 28. Nov. 2021 um 16:11 Uhr schrieb Daniel PETISME <
***@***.***>:

**Comment by gsmet** [comment]
The improvements from Daniel have been merged, closing.
