### ISSUE TITLE
Debian based Distroless, UBI 8 based build, native-image troubles might ensue

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#21051]
### Describe the bug

As I added a distroless setup to AWT graphics Quickstart: https://github.com/quarkusio/quarkus-quickstarts/pull/961  (depends on #20850), it struck me as odd that all quickstarts, including those potentially sensitive to native libs such as Tika, use `quay.io/quarkus/quarkus-distroless-image:1.0` ([yaml](https://github.com/quarkusio/quarkus-images/blob/main/quarkus-distroless-image.yaml)) as their base, which is in fact Debian based.

Quarkus native executable is thus built using UBI 8 based builder image and then copied into Debian userland, with Debian libz copied over, hoping for the best, see ([yaml](https://github.com/quarkusio/quarkus-images/blob/main/quarkus-distroless-image.yaml#L16)).

I used [ubi-micro](https://www.redhat.com/en/blog/introduction-ubi-micro) for the AWT quickstart distroless, manually copying necessary libraries from `ubi-minimal`, which is somewhat frail, although better off than if I attempted to use Debian libs to satisfy UBI dependencies....

I find such setup fragile. It seems to me that if we aim for truly minimalistic setup, we should be working with [ubi-micro](https://www.redhat.com/en/blog/introduction-ubi-micro).

**Comment by gsmet** [comment]
@cescoffier what should we do with this one? Should we replace the distroless thing with ubi-micro? Or call it a day and close this issue?

**Comment by cescoffier** [comment]
That has already be done. So we can just close it.

**Comment by matthyx** [comment]
@cescoffier by the way, do you have some tracking issues on what you're planning regarding native images (upx, ...) to see if I can help somehow?

**Comment by cescoffier** [comment]
Most of the stuff will be tracked on https://github.com/orgs/quarkusio/projects/13. (let me know if you cannot access it, it should be public, but I may have to ping @maxandersen  again to remind him :-D )

BTW, UPX has already been implemented (https://quarkus.io/blog/upx/)

**Comment by matthyx** [comment]
> but I may have to ping @maxandersen again to remind him :-D
indeed, I am getting 404
