### ISSUE TITLE
Hibernate Panache sorting not working with Named Query

### ISSUE THREAD

**Issue by jkalex-git** [quarkusio/quarkus#21067]
### Describe the bug

Sorting not working with Named Query

```
@Entity
@NamedQueries({
        @NamedQuery(name = "countFruit",
                query = "FROM Fruit")
})
public class Fruit extends PanacheEntity {

    @Column(length = 40, unique = true)
    public String name;

    public static List<Fruit> listSortedFruitsByNamedQuery() {
        return list("#countFruit", Sort.by("name").ascending(), new HashMap<>()); // Not sorting
    }

    public static List<Fruit> listSortedFruits() {
        return list("FROM Fruit", Sort.by("name").ascending(), new HashMap<>()); //Sorting is done
    }

}
```

### Expected behavior

find, list and stream functions should support sorting for named queries also. 

### Actual behavior

No errors, but the result list is not sorted if named query is used 

### Output of `java -version`

openjdk version "11.0.11"

### Quarkus version or git rev

2.3.0.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Possible related issue: https://github.com/quarkusio/quarkus/issues/20758

**Comment by loicmathieu** [comment]
When using a named query, we have no idea what is the query so we cannot just "blindly" add an ORDER BY clause.
That's why you cannot use sorting, you should add your own order by clause in your named query.
Maybe we should add in the documentation that sorting should be made manyally with a named query

**Comment by yrodiere** [comment]
> Maybe we should add in the documentation that sorting should be made manyally with a named query

Or even better, we should throw an exception instead of silently ignoring when someone tries to sort and we cannot apply the sort.

**Comment by jkalex-git** [comment]
The documentation could have a 'known limitation' section, so the users are informed of cases like this.

**Comment by Sanne** [comment]
> > Maybe we should add in the documentation that sorting should be made manyally with a named query
> 
> Or even better, we should throw an exception instead of silently ignoring when someone tries to sort and we cannot apply the sort.

+1 that's the better approach

**Comment by loicmathieu** [comment]
@Sanne if we throw an exception, we may break existing code ... maybe a lot.
I think it's bettre to log a WARN and add a sentence in the documentation

**Comment by Sanne** [comment]
Well but did it ever work? I suppose it could have in particularly lucky cases, when nailing the syntax by pure luck.. but doesn't make it a good idea to keep such things working without attention.

**Comment by loicmathieu** [comment]
It didn't work but the parameter is silently ignored.
So it didn't crash either.

**Comment by yrodiere** [comment]
It was invalid usage, and it didn't behave as expected. That's reason enough to break backwards compatibility IMO.
If we can only change behavior when there's an actual exception, there's a whole lot of bugs we'll never be able to fix.

**Comment by loicmathieu** [comment]
OK then, I'll implement an IllegalArgumentException when using named query and sort
