### ISSUE TITLE
SmallryeJwtProcessor will throw NPE if the configuration property is mistyped

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#2107]
Having a typo in the `quarkus.smallrye-jwt.auth-mechanism=MP-JWT` property configuration will cause NPE:

```
Caused by: java.lang.NullPointerException
at io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor.configureIdentityManager(SmallRyeJwtProcessor.java:167)
```

**Comment by gsmet** [comment]
@sberyozkin has this one been fixed? If not, can we fix it and be done with it?

**Comment by rsvoboda** [comment]
@sberyozkin NPE is not ideal message to end user, is there any progress on this ?

**Comment by stuartwdouglas** [comment]
This was fixed by the big security changes.
