### ISSUE TITLE
@ConfigMapping validation fails and ignores @WithDefault if no/default prefix is defined

### ISSUE THREAD

**Issue by pawelbalczynski-tomtom** [quarkusio/quarkus#21088]
### Describe the bug

For @ConfigMapping (with default prefix) and fields with @WithDefault annotation validation fails on startup if no properties found were found in any of ConfigSources.

### Expected behavior

Successful startup and validation for properties with @WithDefault if they are not existing in any ConfigSource

### Actual behavior

For example @ConfigMapping with @WithDefault taken from documentation -> https://quarkus.io/guides/config-mappings#defaults and no properties defined anywhere

```
@ConfigMapping
public interface Defaults {
    @WithDefault("foo")
    String foo();

    @WithDefault("bar")
    String bar();
}
```
application fails to start with following stacktrace

```
2021-10-29 11:55:20,042 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
	PATH does not map to any root
	java.specification.version does not map to any root
	sun.cpu.isalist does not map to any root
	managerpid does not map to any root
        --- cut ------
	SSH_AUTH_SOCK does not map to any root
	java.util.logging.manager does not map to any root
	java.vm.version does not map to any root
	lessopen does not map to any root
	quarkus-internal.serialized-app-model.path does not map to any root
	user does not map to any root
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:855)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:403)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1373)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:446)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:105)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Everything is fine for following code:

```
@ConfigMapping(prefix = "dummy")
public interface Defaults {
    @WithDefault("foo")
    String foo();

    @WithDefault("bar")
    String bar();
}
```

### How to Reproduce?

1. generate sample project
```
$ mvn io.quarkus.platform:quarkus-maven-plugin:2.3.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
cd getting-started
```

2. create @ConfigMapping `src/main/java/org/acme/getting/started/Defaults.java`
```
package org.acme.getting.started;

import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithDefault;

@ConfigMapping
public interface Defaults {
    @WithDefault("foo")
    String foo();

    @WithDefault("bar")
    String bar();
}
```

3. Inject config object into GreetingResource
```
package org.acme.getting.started;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @Inject
    Defaults defaults;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }
}
```
4. run `$ ./mvnw quarkus:dev`

### Output of `uname -a` or `ver`

Linux localhost.localdomain 5.14.13-200.fc34.x86_64 #1 SMP Mon Oct 18 12:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.3.1, 2.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

If validation is disabled with `smallrye.config.mapping.validate-unknown=false` application starts and all @WithDefault properties are correctly initialized with values from annotation.

**Comment by radcortez** [comment]
Hi @pawelbalczynski-tomtom,

This is working as intended. The reason why you are getting the error is that a mapping without a prefix, matches all configuration property names and we have validation in place that fails if a configuration property does not have a corresponding mapping in the mapping interface.

As you stated, `smallrye.config.mapping.validate-unknown=false` makes the application start successfully. This disables the validation (when a configuration property does not have a corresponding mapping).

My recommendation is to either disable the validation or just set your prefix with the desired configuration.

**Comment by pawelbalczynski-tomtom** [comment]
Thanks for reply @radcortez, I wasn't sure if it's really a bug or intended behavior, but don't you think it's inconsistent? For ConfigMappings with prefix, validation passes as expected with just @WithDefault defined (without the need to have them anywhere in properties or so), while it does not work the same for the "global" ones.

**Comment by radcortez** [comment]
Because this has nothing to do with defaults. When you don't have a prefix, we match every configuration available and try to map it to the mapping class. If there is no mapping we validate and output the error. For instance, in your case you have the `PATH` environment variable being read as a configuration. The mapping expects to find the corresponding `String path()` in the interface.

This intended use case for this validation is to make sure that all configuration names are mapped in the interface class. If you add mappings to every configuration that matches the empty prefix, it would work. These are the properties names reported as `[NAME] does not map to any root`.
