### ISSUE TITLE
Help description are not the same in quarkus-maven-plugin depending on the groupId

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#21094]
### Describe the bug

The `quarkus-maven-plugin` has several group ids which are aliases (`io.quarkus.platform`, `io.quarkus`, etc.). So each goal should give the same output no matter which group id we use. This is not exactly the case when we use the `help:describe` goal as the descriptions are not taken into consideration. 

See https://twitter.com/agoncal/status/1454106070582972416

### Expected behavior

The following commands should return the exact same descriptions:

```
$ mvn -Dplugin=io.quarkus.platform:quarkus-maven-plugin:2.4.0.Final help:describe

$ mvn -Dplugin=io.quarkus:quarkus-maven-plugin:2.4.0.Final help:describe
```

### Actual behavior

With the group id `io.quarkus` we have all the descriptions: 

```
$ mvn -Dplugin=io.quarkus:quarkus-maven-plugin:2.4.0.Final help:describe

This plugin has 24 goals:

quarkus:add-extension
  Description: Allow adding an extension to an existing pom.xml file. Because
    you can add one or several extension in one go, there are 2 mojos:
    add-extensions and add-extension. Both supports the extension and
    extensions parameters.
```

But with the group id `io.quarkus.platform` we don't:

```
$ mvn -Dplugin=io.quarkus.platform:quarkus-maven-plugin:2.4.0.Final help:describe

This plugin has 24 goals:

quarkus:add-extension
  Description: (no description available)

quarkus:add-extensions
  Description: (no description available)
```

### How to Reproduce?

```
$ mvn -Dplugin=io.quarkus.platform:quarkus-maven-plugin:2.4.0.Final help:describe

$ mvn -Dplugin=io.quarkus:quarkus-maven-plugin:2.4.0.Final help:describe
```

### Output of `uname -a` or `ver`

Darwin iMac-Pro-de-Antonio.local 20.6.0 Darwin Kernel Version 20.6.0

### Output of `java -version`

java version "11.0.13" 2021-10-19 LTS

### Quarkus version or git rev

2.4.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by gsmet** [comment]
AFAICS, things are OK with 2.6.1.Final.
