### ISSUE TITLE
Docker container is not stopped (on Windows) after integration test

### ISSUE THREAD

**Issue by eijckron** [quarkusio/quarkus#21101]
### Describe the bug

Basic generated and downloaded quarkus project with jax-rs and quarkus-container-image-docker with some small alterations to the native tests to run on the build docker image works fine but fails to stop the docker image.

### Expected behavior

mvn clean verify 
Builds / tests 
Starts docker image 
Runs QuarkusIntegrationTest successful
Stops docker image

Steps are repeatable

### Actual behavior

mvn clean verify 
Builds / tests 
Starts docker image 
Runs QuarkusIntegrationTest successful
Docker image remains running

Steps are not repeatable because the docker image is still running.

### How to Reproduce?

1. Download standard build project with jax-rs and  quarkus-container-image-docker
2.  Add the following to the regular maven build:
```
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
3. In class NativeGreetingResourceIT change @NativeImageTest to @QuarkusIntegrationTest
4. Add the following to application.properties
```
quarkus.container-image.build=true
quarkus.container-image.group=org.acme
quarkus.container-image.name=code-with-quarkus
``` 
5. run mvn clean verify
6. Observe that docker image is still running

### Output of `uname -a` or `ver`

Windows 10 + Docker desktop 3.6.0

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### Quarkus version or git rev

2.4.0 (but same under 2.3.1, 2.3.0 and earlier

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Portable-dev\apache-maven-3.6.3\bin\..
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: C:\Portable-dev\jdk-11.0.9.1+1
Default locale: nl_NL, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
I could not reproduce this on a Linux machine

**Comment by eijckron** [comment]
I can confirm the problem does not happen on Linux.

I installed a WSL2 Ubuntu with Java11, maven and docker on my Windows machine and executed mvn clean verify on the same code and the docker container is stopped as expected.

**Comment by eijckron** [comment]
@geoand Thanks for picking this up so fast, looking forward to the 2.5 release.
