### ISSUE TITLE
Quarkus not always initialising web servlets on startup

### ISSUE THREAD

**Issue by eddiecarpenter** [quarkusio/quarkus#21118]
### Describe the bug

I have a problem with my Quarkus application, where my web servlets are not always initialising at startup.

When one does a maven clean and package, the application is either built with the code to start the servlets or not.  If the application at startup initialises the servlets, it will do so every time it starts and vice versa. 
The only way to resolve the issue is to rebuild the application until it works witch leads me to believe that the problem lies in the quarkus-maven-plugin.

The problem started after upgrading to Qaurkus 2.0.0.

### Output of `java -version`

openjdk 17 2021-09-14 LTS OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS) OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.4.0-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by geoand** [comment]
Do you have an example application you can attach that exhibits this behavior?

**Comment by eddiecarpenter** [comment]
Hi,

 

I will try and create one for you.

 

Regards

Eddie

 

From: Georgios Andrianakis ***@***.***>
Reply to: quarkusio/quarkus ***@***.***>
Date: Monday, 01 November 2021 at 08:00
To: quarkusio/quarkus ***@***.***>
Cc: Eddie Carpenter ***@***.***>, Author ***@***.***>
Subject: Re: [quarkusio/quarkus] Quarkus not always initialising web servlets on startup (Issue #21118)

 

Do you have an example application you can attach that exhibits this behavior?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eddiecarpenter** [comment]
[test.zip](https://github.com/quarkusio/quarkus/files/7452229/test.zip)

Steps:
1. run ./mvnw clean package
2. java -jar /target/quarkus-app/quarkus-run.jar
3. Check the output log. The first line after the log must be something like this
`2021-11-01 11:53:35.627 [] [] INFO  main null:-1 | Starting ZK 9.6.0.1 CE (build: 2021083012)` 
4. If the above line is not present then repeat steps 1 to 3 until the above line is in the log file.

Please contact me if you need more information

**Comment by geoand** [comment]
It doesn't look like there is any Java code in the example.
Furthemore, there are dependencies in `pom.xml` that are unresolvable.

**Comment by eddiecarpenter** [comment]
> It doesn't look like there is any Java code in the example.
> Furthemore, there are dependencies in `pom.xml` that are unresolvable.

Hi Georgios,

Thanks for the time you have spend on my problem so far :-)

Sorry, my mistake, the org.zkoss.zk:zuti is public domain module and I should have removed it. Please removed it from the pom.xml file, it is not needed to recreate the problem.

I am using a third party library (www.zkoss.org) to develop my web UI in. 
You are correct in that there are no java code needed to recreate the problem. There is a file called index.zul in resource/META-INF/resource that is loaded and rendered by zkoss library.

Please have a check again and let me know if you need more information.

**Comment by geoand** [comment]
What is happening is that your `web.xml` file is not being picked up because it's in the wrong directory (it should be `META-INF/web.xml`) and instead the web fragments (`META-INF/web-fragment.xml`) from the dependencies are being used.
Now, due to a bug, the way to those fragments are used is not predicable so sometimes the fragment from `org.zkoss.zk:zkwebfragment` is used and sometimes not.
