### ISSUE TITLE
`-DquarkusRegistryClient=true|false` is not documented for quarkus-maven-plugin:create

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#21128]
### Describe the bug

`-DquarkusRegistryClient=true|false` is not documented for quarkus-maven-plugin:create

### Expected behavior

https://quarkus.io/guides/maven-tooling#project-creation should mention `quarkusRegistryClient` property, it can be handy when working with 999-SNAPSHOT or product bits

### Actual behavior

`quarkusRegistryClient` property is not mentioned in https://quarkus.io/guides/maven-tooling#project-creation

**Comment by gsmet** [comment]
@rsvoboda maybe you could create a PR given it looks like you know what you want? It would be as quick as to open the issue :).

**Comment by rsvoboda** [comment]
OK, I can look into it tmr or on Friday.
