### ISSUE TITLE
@QuarkusProdModeTest, @QuarkusDevModeTest and @QuarkusUnitTest not found

### ISSUE THREAD

**Issue by fastluca** [quarkusio/quarkus#21123]
### Describe the bug

The annotations `@QuarkusProdModeTest, @QuarkusDevModeTest` and `@QuarkusUnitTest` are not available in Quarkus 2.3, but they're are specified in the documentation at [https://quarkus.io/guides/getting-started-testing#mixing-quarkustest-with-other-type-of-tests](https://quarkus.io/guides/getting-started-testing#mixing-quarkustest-with-other-type-of-tests).

### Expected behavior

The annotations `@QuarkusProdModeTest, @QuarkusDevModeTest` and `@QuarkusUnitTest` are available or the information about these is removed from documentation at [https://quarkus.io/guides/getting-started-testing#mixing-quarkustest-with-other-type-of-tests](https://quarkus.io/guides/getting-started-testing#mixing-quarkustest-with-other-type-of-tests).

### Quarkus version or git rev

2.3.1.Final

**Comment by geoand** [comment]
Those classes are sort of internal. They are part of the `quarkus-junit5-internal` module and are useful mainly for extension authors.

**Comment by fastluca** [comment]
So do you think that the documentation doesn't need to be updated? In this case we can close this issue

**Comment by JayGlass** [comment]
I'd say update the documentation - I just read it: https://quarkus.io/guides/getting-started-testing

And started to use @QuarkusProdModeTest only to find there was no import.  Wondering what was going on brought me to here - it'd be preferred to save some developers time by just completely removing them from the examples listed in https://quarkus.io/guides/getting-started-testing

My .02c
