### ISSUE TITLE
JAX-RS minimal application (just quarkus-resteasy) is getting heavy, 120 jars vs 105 jars in 2.2.3.Final

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#21139]
### Describe the bug

JAX-RS minimal application (just `quarkus-resteasy`) is getting heavy, 120 jars in 2.4.0.Final vs 105 jars in 2.2.3.Final, 11% increase in disk usage of quarkus-app

As quarkus-resteasy is matured extension and one of the most used one the impact of this regression can be quite wide.

This increase in disk footprint has implications for runtime
 - more classes need to be loaded
 - => it takes longer to boot the application
 - => more Metaspace gets used to keep class metadata => RSS gets bigger

```
2.3.1.Final / 2.4.0.Final / 999-SNAPSHOT
 30M	app-jax-rs-minimal/target/quarkus-app
 120 JAR files

2.2.3.Final
 27M	app-jax-rs-minimal/target/quarkus-app
 105  JAR files
```

Attaching list of jar files from the app
 - [app-jax-rs-minimal-2.4.0.txt](https://github.com/quarkusio/quarkus/files/7458553/app-jax-rs-minimal-2.4.0.txt)
 - [app-jax-rs-minimal-2.2.3.txt](https://github.com/quarkusio/quarkus/files/7458555/app-jax-rs-minimal-2.2.3.txt)

Can be compared for example with `code --diff ~/Downloads/app-jax-rs-minimal-2.2.3.txt ~/Downloads/app-jax-rs-minimal-2.4.0.txt`
Generated using `find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | xargs basename | sort`

In the diff I see more `com.fasterxml.jackson.*` and `io.smallrye.reactive.*` artifacts in 2.4.0.Final.

### Expected behavior

Same / similar number of jar files and similar disk usage between Quarkus versions.

### Actual behavior

Increase in number of jar files and disk usage between Quarkus versions.
 - 120 jars in 2.4.0.Final vs. 105 jars in 2.2.3.Final
 - 11% increase in disk usage of quarkus-app

### How to Reproduce?

Get https://github.com/quarkus-qe/quarkus-startstop
```
mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.4.0.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l
```
```
mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.2.3.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l
```

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.4.0.Final and Quarkus main

**Comment by rsvoboda** [comment]
CC @stuartwdouglas / @geoand / @gsmet

**Comment by geoand** [comment]
@rsvoboda can you try doing the same thing with a sample `vertx-web` application?

**Comment by rsvoboda** [comment]
```
mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.4.0.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l

mvn clean package -f app-jax-rs-minimal -Dquarkus.version=2.2.3.Final
du -cskh app-jax-rs-minimal/target/quarkus-app
find app-jax-rs-minimal/target/quarkus-app | grep "jar$" | wc -l
```
with `quarkus-vertx-web` gives
```
 28M	app-jax-rs-minimal/target/quarkus-app
 28M	total
     111

 28M	app-jax-rs-minimal/target/quarkus-app
 28M	total
     108
```

So only small diff in number of jars with `quarkus-vertx-web` 

As stated in description, I see more com.fasterxml.jackson.* and io.smallrye.reactive.* artifacts in 2.4.0.Final.
I have attached the list of artifacts too.

Direct comparison - https://www.diffchecker.com/fBNicRlQ (will be available for 1 month)

**Comment by geoand** [comment]
Great, thanks

**Comment by geoand** [comment]
Jackson Databind is now brought in because of https://github.com/quarkusio/quarkus/commit/262f5955cd35c1f36572124968723e613bacadcd - cc @mkouba @cescoffier

**Comment by mkouba** [comment]
Maybe we should remove the `quarkus-jackson` dependency from the `quarkus-vertx` extension. Because if I understand https://github.com/quarkusio/quarkus/issues/16797#issuecomment-828966581 correctly, it should not be needed anymore...

**Comment by geoand** [comment]
Yes, Vert.x should not be depending hardly on Jackson databind. Can you remove `quarkus-jackson` so we can see what CI says?

**Comment by mkouba** [comment]
Hm, we would have to get rid of https://github.com/quarkusio/quarkus/tree/main/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/jackson. Do you have an idea what are these classes for?

**Comment by geoand** [comment]
Those classes are used conditionally IIRC.

**Comment by rsvoboda** [comment]
What about `io.smallrye.reactive.*` additions ?

**Comment by geoand** [comment]
I don't think we can do anything about those, but let's ask @cescoffier and @jponge to be sure.

**Comment by cescoffier** [comment]
No we need the mutiny jars.
