### ISSUE TITLE
quarkus-grpc no longer exposing port 8080 for static content like index.html

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#21132]
### Describe the bug

`quarkus-grpc` no longer exposing port 8080 for static content - e.g. index.html

This is regression in 2.4.0.Final and Quarkus main comparing to Quarkus 2.3.0.Final / 2.3.1.Final

I have checked https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.4 and there is no note about such change is present.

### Expected behavior

Expose both gRPC Server port 9000 and HTTP port 8080

### Actual behavior

Only gRPC Server port 9000 gets exposed

### How to Reproduce?

Get the sample  app from https://code.quarkus.io/?extension-search=quarkus-grpc

run `mvn quarkus:dev -Dquarkus.platform.version=2.3.0.Final` to see ` code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.3.0.Final) started in 1.492s. Listening on: http://localhost:8080`

run `mvn quarkus:dev -Dquarkus.platform.version=2.4.0.Final` or `mvn quarkus:dev -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.group-id=io.quarkus` to see that only port 9000 is exposed and 8080 doesn't get provided

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.4.0.Final and Quarkus main

**Comment by famod** [comment]
This ia most likely due to #20465, /cc @stuartwdouglas

**Comment by gsmet** [comment]
I think we should just document it in the migration guide.

**Comment by stuartwdouglas** [comment]
Added:  https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.4#grpc-decoupled-from-http
