### ISSUE TITLE
Offer a quarkus create-extension maven and gradle plugin command

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2113]
The idea is to simplify the extension creation path

**Comment by danielpetisme** [comment]
As @cescoffier said in the duplicate, I'm interested to work on this.

**Comment by danielpetisme** [comment]
One question, so far the extensions are part of the Quarkus source repo.  The `create-extension` command should be preconfigured with the quarkus repo structure (+ register the extension in the parent pom etc.) or it should permit to create an extension out side ?

I had the discussion with @gsmet when doing the swagger extension, AFAIK there is no plan to have extensions hosted outisde the Quarkus repo.

WFDYT?

**Comment by gsmet** [comment]
Hi @danielpetisme ,

> AFAIK there is no plan to have extensions hosted outisde the Quarkus repo

That's not what I said. Right now, we don't have the infrastructure for that but having extensions outside our repo is something we want to encourage in the longer term.

What would be nice is if the `create-extension` mojo could analyze if it's in the `extensions` directory (we can analyze the pom file) and adapt the created extension to the Quarkus environment. The issue with adding the extension to the pom is that it will reformat the file, which we don't really want. And extensions are categorized. So for now, I wouldn't do it. We could have a WARN message saying you need to add the extension in the pom.

If not in the extensions directory, I would create an external extension in a new directory, without playing with the parent pom either.

What will be interesting to see is how it interacts with a bom for extensions (we might want one for runtime - which could be the current bom - and one for deployment or one global if it makes more sense) and/or the need of a parent. See https://github.com/quarkusio/quarkus/issues/2154.

**Comment by emmanuelbernard** [comment]
If we have to decide, I’d prefer we have the generator ready for extensions outside the core repo. 

Emmanuel

**Comment by ppalaga** [comment]
I started hacking on a maven plugin that would primarily suit the use case of adding extensions in camel-quarkus.

**Comment by emmanuelbernard** [comment]
Hey @ppalaga is that really specific to Camel? My concern would be fragmenting the community by offering tools useful in different islands. Also ideally we don't want people to have to install / setup / know more than the Quarkus maven plugin.

I understand we can't adhere to that stic tline 100%. I am just mentioning the general intent.

**Comment by ppalaga** [comment]
No, what I have is not Camel only. I am aiming at adding extension modules to source trees similar to quarkus or camel-quarkus.  Creating standalone extension projects is out of my scope now. I am adding the new mojo to `devtools/maven` module of the Quarkus repo. I hope I'll be able to send a PR soon.

**Comment by ppalaga** [comment]
The PR https://github.com/quarkusio/quarkus/pull/3191 is ready for review.
