### ISSUE TITLE
Dev mode first hot reload request is 'ignored' if there is no active REST endpoint on the service under Ubuntu

### ISSUE THREAD

**Issue by tlvlp** [quarkusio/quarkus#21145]
### Describe the bug

In the `intellij` terminal the first `s` triggers a manual restart when the Quarkus service has an active REST endpoint.
But if it doesn't have one, then the first `s` is ignored and restart only occurs on sending the second one as well.

### Expected behavior

Restart on the first request.

### Actual behavior

Restarts only on the second request even if minutes pass between the two.

### How to Reproduce?

A reproducer can be found at: 
https://github.com/tlvlp/quarkus-hot-reload-test (Note: it's only an empty, freshly generated project.)

1. Launch the service
2. Wait for the build and dev mode to load and for the service to start.
3. Make any changes to the code.
4. Select intellij's terminal
5. Press 's' and 'enter
6. Nothing happens
7. Repeat step 5.
8. The service hot-reload is triggered.

### Output of `uname -a` or `ver`

Linux tux 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.3.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

Related to #20809 where the affected code segment is also mentioned.

```
Linux 5.11.0-34-generic
Current Desktop: ubuntu:GNOME
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

com.redhat.devtools.intellij.quarkus (1.8.0.176)
```

**Comment by gsmet** [comment]
@stuartwdouglas this looks like an issue for you.

**Comment by stuartwdouglas** [comment]
I think https://github.com/quarkusio/quarkus/pull/21294 should fix it, although I could not reproduce it locally.
