### ISSUE TITLE
Conflicting dependency packages with org.jboss:jandex

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#2115]
org.jboss:jandex:2.1.1.Final  and org.jboss:jandex:2.0.5.Final

**Comment by gsmet** [comment]
Any chance we could get some more details?

**Comment by geoand** [comment]
Do you see this when using the maven jandex plugin perhaps?

**Comment by pipinet** [comment]
@gsmet demo is https://github.com/qwlabs/quarkus-issue

**Comment by pipinet** [comment]
@gsmet https://github.com/qwlabs/quarkus-issue
run command 
```bash
./gradlew quarkusBuild --info
```
```bash
Task ':quarkusBuild' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
building quarkus runner
User dependency org.jboss:jandex:2.0.5.Final overrides Quarkus platform dependency org.jboss:jandex:2.1.1.Final
Beginning quarkus augmentation
:quarkusBuild (Thread[Execution worker for ':',5,main]) completed. Took 0.569 secs.
```

**Comment by geoand** [comment]
I can confirm I get the warning as well.

Running `./gradlew dependencies` on the project and searching for the `jandex` I see:

```
|    +--- org.hibernate:hibernate-core:5.4.2.Final
|    |    +--- org.jboss.logging:jboss-logging:3.3.2.Final
|    |    +--- javax.persistence:javax.persistence-api:2.2
|    |    +--- net.bytebuddy:byte-buddy:1.9.10
|    |    +--- antlr:antlr:2.7.7
|    |    +--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.1.1.Final
|    |    +--- org.jboss:jandex:2.0.5.Final

```

My guess is that the issue is caused because the Quarkus BOM is not being used.

**Comment by gsmet** [comment]
@geoand by not being used, you mean in the OP's Gradle project or it's a problem with our Gradle plugin?

**Comment by geoand** [comment]
@gsmet I don't think our Gradle plugin can be blamed since it doesn't apply the BOM (although I think it be made to do so).

I did however try applying the BOM to the OP's project and although the Jandex issue did go away, new dependency issues arouse: 

```
User dependency org.apache.httpcomponents:httpclient:4.5.7 overrides Quarkus platform dependency org.apache.httpcomponents:httpclient:4.5.4
User dependency org.apache.httpcomponents:httpcore:4.4.11 overrides Quarkus platform dependency org.apache.httpcomponents:httpcore:4.4.7
User dependency commons-codec:commons-codec:1.11 overrides Quarkus platform dependency commons-codec:commons-codec:1.10
```

So I am not really sure at this point what the proper Gradle setup should be (I haven't played with Gradle that much unfortunately...)
