### ISSUE TITLE
Support reading version metadata/codestart when adding extension with specific version

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#21165]
### Description

We should support reading metadata for the specified version when adding extension with specific version. 

It would also open the way to generate codestarts for local extension in devolopment.

ex (should use the extension metadata from  io.foo:quarkus-foo-bar:999-SNAPHOT) :
```
q ext add io.foo:quarkus-foo-bar:999-SNAPHOT
```

**Comment by maxandersen** [comment]
worth mention this enables users to have coestarts for their extensions without being in the registry.
