### ISSUE TITLE
Tika 2.x support

### ISSUE THREAD

**Issue by denis111** [quarkusio/quarkus#21171]
### Description

Currently supported Tika version is 1.27. Is there any plan to support Tika 2.x?

### Implementation ideas

I see that current implementation references AbstractRecursiveParserWrapperHandler.TIKA_CONTENT which I can't see in Tika 2.1...

**Comment by sberyozkin** [comment]
@denis111 AFAIK Tika `2.x` introduces parser specific modules though it should provide an all inclusive jar similar to the `1.2x` line. I don't see any problems with a direct migration to a `Tika 2.x` all inclusive jar, though it does look like a few details needs to be changes like referring to this property you mention, etc.
If you can look at it then it would be good, it can be hard for me to prioritize on Tika related enhancements at the moment

**Comment by denis111** [comment]
@sberyozkin I could try but I don't have any experience with graalvm native image, and I'm sure it will give me compile or runtime problems :) For example, when I try to add JPEG2000 libs (jai-imageio-jpeg2000 and jj2000) it fails to compile even  with current tika v1.27.

**Comment by gsmet** [comment]
The extension has been moved to https://github.com/quarkiverse/quarkus-tika . Closing the issue here.
