### ISSUE TITLE
Quarkus reactive core with Panache reactive and Panache JPA

### ISSUE THREAD

**Issue by cristianorvf** [quarkusio/quarkus#21199]
Based on reading the blog post [RESTEasy Reactive - To block or not to block](https://quarkus.io/blog/resteasy-reactive-smart-dispatch/)

How to setup hibernate reactive + JPA for accessing EntityManager +  PanacheRepository (classic) or PanacheRepository (reactive) based on signatures ?

One understands that defaults for reactive and blocking has changed, ok.. nice. But also for the same post we can infer that things like `@Transacional` are infered to be blocking, and that the transactional manager should work over JPA (since its blocking.) 

Meaning, in the end that we can conbine both worlds in the same application. I've tried to setup such project without success where hibernate conflicts between hibernate reactive and JPA.

In my understanding things should work like (using panache for example..)
- Add panache hibernate reactive
- Add panache hibernate JPA
- Setup two datasources (r2dbc and jdbc)
- When use `@Transacional` the classic path happens (use `EntityManager` , ThreadLocals, transaction support) and is possible to use normal `PanacheEntity` with `PanacheRepository` classic
- When returning Unis and Multis things hapen with reactive in I/O Threads.. using `PanacheRepository` from reactive package

So, is this possible or did i get it wrong? 

Whats is the POM for non-conflict  ?

**Comment by MartinX3** [comment]
What's a `PanacheReactiveRepository`? I don't find it in google.

**Comment by cristianorvf** [comment]
> What's a `PanacheReactiveRepository`? I don't find it in google or in your link.

Sorry! I was writing the question with lots of code of the current project open in my IDE which uses spring data and spring data reactive in two separete projects.. there it uses a separation via class names for repos so my mind messed up when i was writing! What i meant was to use the two separate Repositories (which are separated via packages in quarkus..)

```
io.quarkus.hibernate.orm.panache.PanacheRepository;
io.quarkus.hibernate.reactive.panache.PanacheRepository;
```

The question stil remains, there is one repo with reactive signatures  and other with classic, i would like to use both in the same project, possibily with two connection pools (one via r2dbc Mutity and one JDBC agroal.)

**Comment by MartinX3** [comment]
Like this? https://quarkus.io/guides/datasource (found via google)

**Comment by cristianorvf** [comment]
> Like this? https://quarkus.io/guides/datasource (found via google)

No, not exactly.. but based on my exception i found this: [https://github.com/quarkusio/quarkus/issues/13425](https://github.com/quarkusio/quarkus/issues/13425)

Im closing since the other one is older, thanks.
