### ISSUE TITLE
Quarkus 2.4.1.Final : Dev-UI : Provider: Keycloak link in an OpenId Connect Dev UI card not showing

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#21202]
### Describe the bug

I'm following this guide : https://quarkus.io/version/main/guides/security-openid-connect

````
cd quarkus-quickstarts\security-openid-connect-quickstart

mvn quarkus:dev
````

at this step to : Open a Dev UI available at /q/dev and click on a Provider: Keycloak link in an OpenId Connect Dev UI card.

when I access the web page, when I click on the green button, the card is not shown.  
I'm on Windows, Google Chrome : Version 95.0.4638.54 (Build officiel) (64 bits)

I have a demo here of what I did
![openid-dev-ui](https://user-images.githubusercontent.com/191879/140401547-ed57409b-797a-41be-bc7d-2d4864243307.gif)

````
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-11-04 14:02:13,189 INFO  [io.quarkus] (Quarkus Main Thread) security-openid-connect-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.4.1.Final) started in 61.787s. Listening on: http://localhost:8080
2021-11-04 14:02:13,195 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-11-04 14:02:13,197 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, keycloak-authorization, oidc, resteasy, resteasy-jackson, security, smallrye-context-propagation, vertx]

--
Tests paused
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
````

**Comment by sberyozkin** [comment]
@survivant Interesting I've never seen this phenomenon :-), @phillip-kruger Hey Phillip, any idea how it can happen ?

@survivant Can you provide more info please, browser type/version, OS ?

**Comment by survivant** [comment]
Google Chrome Version 95.0.4638.54 (Build officiel) (64 bits)

I'm on Windows (don't think it's related this time) : 
````
Microsoft Windows [version 10.0.19043.1288]
(c) Microsoft Corporation. Tous droits réservés.
````

I have a proof this time :)  

I have to leave soon, but tomorrow I'll try with other browsers.

**Comment by sberyozkin** [comment]
Hi @survivant I've retried it and it works as expected for me.

I think there could be some sync issues here - the doc link you use points to `main`, if you select `2.4-LATEST` then you'd see no these doc updates. Also the `security-oidc*` quickstarts in `2.4.1.Final` do not match what is done in the development` branch.

Can you please try the snapshots to verify the quickstart docs you see in the `main` docs ?

**Comment by survivant** [comment]
Yes,i’ll do that tomorrow.maybe It's just that The issue

Le jeu. 4 nov. 2021, 18 h 19, sberyozkin ***@***.***> a
écrit :

**Comment by phillip-kruger** [comment]
It could also maybe be something with browser cache, so try clearing cache. Also open the web developer console in the browser to see if there are any errors and please report here.

**Comment by survivant** [comment]
ok, I see the screen now 

what I did was to close my browser and start again mvn quarkus:dev

but..before, I logged into Keycloak admin page before accessing Quarkus Dev-UI.  Maybe there was a "glitch" with the fact that I was previously logged into Keycloak.  

![image](https://user-images.githubusercontent.com/191879/140510177-9ad7ebf7-4251-4840-8c2b-420315a93013.png)

**Comment by sberyozkin** [comment]
@survivant So you had Keycloak started independently - logged in there, then, with `quarkus.oidc.auth-server-url` configured without a `%prod.` profile qualifier you started `quarkus:dev` and trying to Log in, using the same browser instance ?

It would explain the problem - Keycloak detects you are logged in or fails for some reasons and immediately redirects you back to the Dev UI page and this template branch runs: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/resources/dev-templates/provider.html#L44

which hides the tokens page as there is nothing to show.

I can see in your captured image that the `error_description` is included in the response URL - this is probably sufficient - as we can't really do a pop up as it may be blocked and printing it as we can't even logout afterwards to return to the initial screen.

I think we can add an option to log in the dev console - by posting the error description to the registered handler - it will help in the future to find the errors faster

**Comment by survivant** [comment]
Keycloak was started by  mvv quarkus:dev  

but, I logged into Keycloak dirrectly without using DEV-UI at first.  I wanted to look at the realms configuration.  After that I entered into DEV- UI page.  

that was the flow that I used yesterday.

**Comment by sberyozkin** [comment]
@survivant FYI, you can always use a `Keycloak Admin` option directly from Dev UI - as capturing the address with the logs now being compressed can be tricky :-).
I'll have a look at displaying the error message directly in the page

**Comment by survivant** [comment]
I never really used dev-ui before.  I saw this morning we could log in quarkus from there.. it's nice.

**Comment by sberyozkin** [comment]
@survivant @phillip-kruger I've reproduced exactly the same problem in the current OIDC quickstart - I just go to Keycloak admin and modify the Quarkus realm to disable the standard flows and after pressing a `Login to SPA` I returned immediately to it - the error is in the browser URL but this error message needs to be made more visible, will try to tweak the template a bit
