### ISSUE TITLE
Enhance warning about programmatic lookup problem detected with source of the problem

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#21218]
### Description

I am currently getting an Error about `programmatic lookup problem detected`.
However, since this project uses modules from other contributors, I have no idea where the programmatic lookup might be happening.

Can this warning please be enhanced with the source of the lookup?

```
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build
Removed beans:
- CLASS bean  [types=[class com.acme.SomeBean], qualifiers=null]
Required type: class com.acme.SomeBean
Required qualifiers: [@javax.enterprise.inject.Default()]
Solutions:
- Application developers can eliminate false positives via the @Unremovable annotation
- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
- See also  -' class='text-primary' target='_blank'>https://quarkus.io/guides/cdi-reference#remove_unused_beans
- Enable the DEBUG log level to see the full stack trace to identify the method that performed the lookup
================================================================================
```

**Comment by Postremus** [comment]
Okay, I am just now reading the full text of the error.
`Enable the DEBUG log level to see the full stack trace to identify the method that performed the lookup`

I still believe that the source of the problem should be immediatly shown without having to active DEBUG log first.

**Comment by geoand** [comment]
I'm personally -1 on this, but it's up to @mkouba

**Comment by mkouba** [comment]
Hm, I think that we can try to log the last stack trace element...

**Comment by geoand** [comment]
I think that's acceptable

**Comment by manovotn** [comment]
> Hm, I think that we can try to log the last stack trace element...

That sounds reasonable; it will at least provide a first step and if that's not enough, there is always `DEBUG` logging.

**Comment by mkouba** [comment]
Unfortunately, it's not so easy to find the correct element because the stack trace might be really deep. We could filter the stack and show for example the first element with declaring class that does not come from `io.quarkus.arc.impl` but I'm not sure how reliable it is...
