### ISSUE TITLE
compatibility: quarkus-undertow-websockets and quarkus-resteasy-reactive-jackson

### ISSUE THREAD

**Issue by artorius82** [quarkusio/quarkus#21222]
I have created a simple test case to show the problem.

```
import javax.ws.rs.POST;
import javax.ws.rs.Path;

@Path("rest")
public class RestResource {

  @POST
  public void post() {
  }

}
```

```
@QuarkusTest
class RestResourceTest {

  @Test
  void post() {
    given()
        .when()
        .accept("application/json, */*")
        .contentType("application/json")
        .body("{}")
        .post("/rest")
        .then()
        .statusCode(204);
  }
}
```

When I add both libraries to the project's pom.xml a simple post rest resource test case start to fail:

java.lang.AssertionError: 1 expectation failed.
Expected status code <204> but was <405>.

The test works fine however, if I use quarkus-resteasy-jackson instead of quarkus-resteasy-reactive-jackson.

### Expected behavior

Test case doesn't fail.

### Actual behavior

Test case fails.

### How to Reproduce?

Copy the rest resource and the test case into the "websockets-quickstart" quarkus project and run the test.

### Output of `uname -a` or `ver`

Linux thinkpad-t480s 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
Does it work if you use `quarkus-websockets`?

**Comment by artorius82** [comment]
**Yes, it works! Thank you very much!**
Btw. I copied the quarkus-undertow-websockets dependency from here: https://github.com/quarkusio/quarkus-quickstarts/blob/main/websockets-quickstart/pom.xml

**Comment by geoand** [comment]
Indeed, but for RESTEasy Reactive you need to use `quarkus-websockets`. Maybe we should provide an actionable warning message, WDYT @stuartwdouglas @gsmet?
