### ISSUE TITLE
QuarkusUnitTest.getLogRecords() cannot be used from within a test method

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#21225]
### Describe the bug

The returned list is always empty, i.e. you can't do something like this:
```java
public class MyTest {

    @RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .withEmptyApplication()
            .setLogRecordPredicate(log -> true);
   
   @Test
   public void test() {
      List<LogRecord> records = config.getLogRecords();
      // -> records is always empty
   }
}
```

It can be a problem related to the fact that the test class is initialized twice, i.e. there are two instances of `QuarkusUnitTest` created for each test class.

Note that `QuarkusUnitTest.assertLogRecords(Consumer<List<LogRecord>>)` works just fine and since the consumer is called during `AfterAllCallback` it can be used to assert log messages published during execution of test methods.

**Comment by mkouba** [comment]
See also zulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/QuarkusUnitTest.20initialized.20twice.3F

**Comment by geoand** [comment]
I see. I agree with your statement in chat that `getLogRecords` should be completely removed, it can't work properly.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21228 removed the logging related methods
