### ISSUE TITLE
Query param name containing the '=' character is not correctly encoded by the http client on quarkus reactive

### ISSUE THREAD

**Issue by agelbess** [quarkusio/quarkus#21234]
### Describe the bug

Here is a RestClient (take note that we are talking about the encoding of the param name...NOT the param value)

@GET
    @Path("ps")
    public Uni<Map<String, String>> ps(@QueryParam("p1") String p1,
                                       @QueryParam("p2(") String p2,
                                       @QueryParam("p3[") String p3,
                                       @QueryParam("p4?") String p4,
                                       @QueryParam("p5=") String p5,
                                       @QueryParam("p6-") String p6);

the 5th param (p5=) is not sent correctly to the server, as a result the server receives null.
(the other params even if they contain special characters are sent correctly)
NB: this happens ONLY with the reactive libraries.

Check out this repo, it has 2 branches, the master fails and the non_reactive succeeds.
https://github.com/agelbess/quarkus-reactive-query-param-name-with-equals-sign

### Expected behavior

@QueryParam(s) with names that contain the '=' character should be sent with the correct encoding to the server.

### How to Reproduce?

Clone the repo
https://github.com/agelbess/quarkus-reactive-query-param-name-with-equals-sign
and execute the commands (check the README.md for the same info)

mvn compile quarkus:dev
curl localhost:8080/start

The response will be
responds with {"p1":"1","p2":"2","p3":"3","p4":"4","p5":null,"p6":"6"}

...meaning that the 5th param was not sent correctly to the server.

### Quarkus version or git rev

2.4.0.Final

**Comment by geoand** [comment]
@Sgitario would you like to start exploring the reactive rest client code by tackling this issue?

**Comment by Sgitario** [comment]
> @Sgitario would you like to start exploring the reactive rest client code by tackling this issue?

Looking
