### ISSUE TITLE
Class metadata is not being fully loaded in debug mode

### ISSUE THREAD

**Issue by vhmolinar** [quarkusio/quarkus#21231]
### Describe the bug

While running a java quarkus app in i am not being able to gather all class metadata during debug mode.
Specifically saying, those metadata regarding annotation qualifiers are not being loaded by the proxy classes.
Consider the following example:

A implementation of a super type with qualifier
```java
@Dependent
@AnyQualifier("AnyImpl")
class AnyImpl implements Type {}
```

A injection of all subtypes
```java
@Inject
@Any
Instance<Type> types;
```

A read of metadata of any of subtype object
```java
Class<Type> clazz = subtypeObj.getClass();
AnyQualifier annotation = clazz.getAnnotation(AnyQualifier.class);
// annotation is always null in debug mode
```
As shown, quarkus wont load metadata of my custom qualifier annotation.
On the other hand should i call `clazz.getAnnotations()` I would get an array containing `@Dependent` annotation.

### Expected behavior

The problem occurs only in debug mode. Thus should work in debug mode as well.

### Actual behavior

Quarkus is not providing the full metadata information regarding a class during debug mode.

### How to Reproduce?

Full example here: https://github.com/vhmolinar/quarkus-issue-metadata

Steps to reproduce the error

- `./gradlew quarkusDev`
- Go to http://localhost:8080/demo

Also

- `./gradlew quarkusBuild`
- ` java -jar build/quarkus-app/quarkus-run.jar `
- http://localhost:8080/demo

### Output of `uname -a` or `ver`

Linux localhost.localdomain 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

21.2.0

### Quarkus version or git rev

2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

### Additional information

The issue was previously detected on 1.13.2.Final version. But wasnt ocurring in 1.11.0.Final.

**Comment by geoand** [comment]
Does the same thing happen if you have set `quarkus.arc.dev-mode.monitoring-enabled=false`?

**Comment by vhmolinar** [comment]
@geoand 🎯 . The problem doesn't occur disabling this feature.
Is this the expected behaviour?

**Comment by geoand** [comment]
Yes it is expected (@mkouba has more details).

You can likely get around the problem by calling `ClientProxyUnwrapper.#apply` on the instance and then calling `getClass` on the result

**Comment by mkouba** [comment]
In general, any injected instance is considered an internal container construct in CDI, i.e. it can be a [client proxy](https://quarkus.io/guides/cdi#client_proxies) or an intercepted subclass. In both cases, the injected instance is not an instance of `AnyImpl()` but an instance of a class that _extends_ `AnyImpl`. And annotations are not copied to the these subclasses.

And yes, you can test the instance whether it's assignable to `io.quarkus.arc.ClientProxy` or `io.quarkus.arc.Subclass` and if it is then simply call `type.getClass().getSuperclass()`.

**Comment by vhmolinar** [comment]
> In general, any injected instance is considered an internal container construct in CDI, i.e. it can be a [client proxy](https://quarkus.io/guides/cdi#client_proxies) or an intercepted subclass. In both cases, the injected instance is not an instance of `AnyImpl()` but an instance of a class that _extends_ `AnyImpl`. And annotations are not copied to the these subclasses.
> 
> And yes, you can test the instance whether it's assignable to `io.quarkus.arc.ClientProxy` or `io.quarkus.arc.Subclass` and if it is then simply call `type.getClass().getSuperclass()`.

Got it. Thanks for the explanation. @mkouba 

Anyway, this annotation copy process was happening prior to 1.13.x versions? Because back then it was actually possible to check the metadata of injected instances.

**Comment by geoand** [comment]
> Anyway, this annotation copy process was happening prior to 1.13.x versions? Because back then it was actually possible to check the metadata of injected instances.

Back then the feature enabled by `quarkus.arc.dev-mode.monitoring-enabled` didn't exist.

**Comment by mkouba** [comment]
> > Anyway, this annotation copy process was happening prior to 1.13.x versions? Because back then it was actually possible to check the metadata of injected instances.
> 
> Back then the feature enabled by `quarkus.arc.dev-mode.monitoring-enabled` didn't exist.

Yes, exactly. But it was only possible because the bean is '@Dependent' (i.e. no client proxy is required) and has no interceptor associated.
