### ISSUE TITLE
Clean up JDK 18 workarounds

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#21248]
### Description

Some workarounds were/are needed to get the EA job passing, which should be removed again if/when possible:
- https://github.com/quarkusio/quarkus/pull/21244
- ~~more to come~~ _edit: the above is the only real workaround_

Related: #20392

**Comment by geoand** [comment]
Is this still an issue?

**Comment by famod** [comment]
@geoand I suppose it is: https://github.com/quarkusio/quarkus/pull/19559#issuecomment-937816176
>  this essentially will mean RESTEasy will have to upgrade its internal dependency on Apache HTTPClient from 4.5.x to 5.x.

but I haven't really followed RESTEasy development.

**Comment by alexey-anufriev** [comment]
Contributed small cleanup here.

**Comment by famod** [comment]
FTR, RESTEasy still hasn't migrated to httpclient 5, see also:
- https://github.com/resteasy/resteasy/blob/main/resteasy-dependencies-bom/pom.xml#L65
- [RESTEASY-3291](https://issues.redhat.com/browse/RESTEASY-2802)

**Comment by geoand** [comment]
Can we close this now?
