### ISSUE TITLE
AWS Lambda - Quarkus - ClassNotFound

### ISSUE THREAD

**Issue by jamesneb** [quarkusio/quarkus#21240]
### Describe the bug

Hello all,

I am trying to run my quarkus project from aws lambda. I run into this issue when I test:

````
{
  "errorMessage": "Quarkus bootstrap failed.\njava.lang.ClassNotFoundException: io.quarkus.runner.ApplicationImpl. Current classpath: file:/var/task/\n\tat lambdainternal.CustomerClassLoader.findClass(CustomerClassLoader.java:63)\n\tat java.base/java.lang.ClassLoader.loadClass(Unknown Source)\n\tat java.base/java.lang.ClassLoader.loadClass(Unknown Source)\n\tat java.base/java.lang.Class.forName0(Native Method)\n\tat java.base/java.lang.Class.forName(Unknown Source)\n\tat io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.<clinit>(QuarkusStreamHandler.java:30)\n\tat java.base/java.lang.Class.forName0(Native Method)\n\tat java.base/java.lang.Class.forName(Unknown Source)\n\tat lambdainternal.HandlerInfo.fromString(HandlerInfo.java:33)\n\tat lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:108)\n\tat lambdainternal.AWSLambda.startRuntime(AWSLambda.java:226)\n\tat lambdainternal.AWSLambda.startRuntime(AWSLambda.java:195)\n\tat lambdainternal.AWSLambda.main(AWSLambda.java:189)\n",
  "errorType": "java.io.IOException",
  "stackTrace": [
    "io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:56)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)",
    "java.base/java.lang.reflect.Method.invoke(Unknown Source)"
  ]
}
````

I am using this function handler:
**io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest**

Here is an excerpt of my function handler class:

````
@Named("stream")
public class LambdaSolver implements RequestStreamHandler{

    private static final long PROBLEM_ID = 0L;

    private final AtomicReference<Throwable> solverError = new AtomicReference<>();
    private static final AtomicLong sequence = new AtomicLong();
   
    @Inject
    ScoreManager<VehicleRoutingSolution, HardSoftLongScore> scoreManager;
    @Inject 
    VehicleRoutingSolutionRepository repository;
    @Inject
    SolverManager<VehicleRoutingSolution, Long> solverManager;
    
    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
     
    	int letter;
        while ((letter = inputStream.read()) != -1) {
            int character = Character.toUpperCase(letter);
            outputStream.write(character);
        }
    	
    	
    	
    	
        
    }
````

I do not know how to proceed.

### Expected behavior

The lambda should execute handleRequest() from my LambdaSolver class.

### Actual behavior

I receive a ClassNotFound exception

### Output of `uname -a` or `ver`

arwin Macs-MBP.attlocal.net 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "13" 2019-09-17 Java(TM) SE Runtime Environment (build 13+33) Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)

### Quarkus version or git rev

2.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f) Maven home: /usr/local/Cellar/maven/3.8.2/libexec Java version: 13, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by gsmet** [comment]
@jamesneb could you try with the latest Quarkus 2.4.1.Final? If it doesn't solve your issue, a small project reproducing the issue would help.

**Comment by gsmet** [comment]
No comments, closing.
