### ISSUE TITLE
document how to log/trace http/rest client reactive

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#21249]
### Description

lets say you have:

```
@RegisterRestClient
interface DayCaptain {

    @POST
    @Path("/backlog-items")
    void addToBacklog(@HeaderParam("Authorization") String auth,String string);
}
```

and calling "captain.addToBacklog(token,task);" and you get a 302 or 500 status response how are users able to check what actually gets sent ?

One would expect enabling all logs would print something but it gives you nothing.
You could explore requestfilters - but what would they look like?
Other alternative is to us `mitmproxy` to trace everything but quarkus http client does not seem to react to -Dhttp.proxy* flags.

We should get these things documented. I'm happy to do it but couldn't find working answers - hence this issue :)

**Comment by maxandersen** [comment]
there are proably also some tracing one can do but that seems overkill to just have to debug client requests...

**Comment by michalszynkiewicz** [comment]
Vertx HTTP Client has a `setLogActivity` method but that only takes a `boolean` as parameter and supposedly logs tons of netty stuff. I think it's worth adding an option to enable it but it would be an overkill for most of users.

JAX-RS filters can be used to log the request and the _final_ response. I.e. if a request is redirected, it won't be reflected in the logs. That would probably be enough for most. But I'll try to find something that could get us more info.

**Comment by michalszynkiewicz** [comment]
I'm thinking of adding a config property:
```properties
quarkus.rest-client.logging=none | request-response | all
```

Where request-response would log request, response, and info about redirects, and `all` would also enable the lower level logging. WDYT @maxandersen @geoand ?

We could also have a possibility to overwrite it for a specific client, e.g.

```properties
quarkus.rest-client.logging=request-response
quarkus.rest-client."com.example.MyClient".logging=all
```

**Comment by geoand** [comment]
I like it!

**Comment by radcortez** [comment]
How about RESTEasy Tracing Feature: https://docs.jboss.org/resteasy/docs/4.7.3.Final/userguide/html_single/index.html#d4e4403?

**Comment by michalszynkiewicz** [comment]
https://github.com/quarkusio/quarkus/pull/21286 proposes a solution

**Comment by michalszynkiewicz** [comment]
The config properties added in #21286 should be automatically added to all properties list, is this enough for documentation?

**Comment by gsmet** [comment]
#21286 has been merged so we can close this one.

Also the work of @geoand to support HTTPToolkit properly is also an alternative.
