### ISSUE TITLE
"Unsatisfied dependency for type" with Quarkus 2.4.1 in Gradle multi-module project

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#21255]
### Describe the bug

In my multi-module project, I'm running into the issue that Quarkus cannot load beans from sub-modules, which works in 2.3.1.

I guess it should be easily reproducible, so I won't provide a reproducer for it, but for clarification, I'll add my project's structure:

-root
-- application
-- module_a 
-- module_b
-- module_c
module_a uses b and c, the application uses all of them.

Errors only occur with beans injected in the application module, but once I comment those out, it spreads into module_a with dependencies of module_b and module_c.

### Actual behavior

Produces "Unsatisfied dependency for type" for several/all of the sub-modules dependencies

**Comment by glefloch** [comment]
Thanks for reporting this @mklueh.
A reproducer will help a lot. There are sample projects in our integration test suite that match your project description and tests are passing. 
However we may be missing some project setup there and this could help improve our test coverage.

**Comment by mklueh** [comment]
@glefloch while building a reproducer based on my multi-module-template I found out that I was missing META-INF/beans.xml in my actual application

```
<?xml version="1.0" encoding="UTF-8"?>
<beans
        xmlns="http://xmlns.jcp.org/xml/ns/javaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee 
                      http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
        bean-discovery-mode="all">

</beans>
```


For whatever reason it worked without those files under Quarkus 2.3.1 and stopped working without them under 2.4.1.

**Comment by glefloch** [comment]
Right, without this file (or a jandex index), quarkus won't scan module for CDI beans. That's really weird that it used to work before. 

Here the documentation on how bean can be discovered: https://quarkus.io/guides/cdi-reference#bean_discovery

**Comment by glefloch** [comment]
I'm closing the issue as there won't be any fix.
