### ISSUE TITLE
Guide security-jwt mentions smallrye.jwt.key.verify.location instead of smallrye.jwt.verify.key.location

### ISSUE THREAD

**Issue by RolandGanaus** [quarkusio/quarkus#21257]
The verification key paragraph in the JWT guide (https://quarkus.io/guides/security-jwt#dealing-with-the-verification-keys) wrongly mentions "smallrye.jwt.key.verify.location" instead of the correct "smallrye.jwt.verify.key.location".

**Comment by gsmet** [comment]
Transferred to the main repo as the doc is managed there.
