### ISSUE TITLE
Webjars: support DEV UI

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#21273]
### Description

Webjars are nice, but DEV UI support that would list the files would be nice, because it's not obvious what the URIs are, and they're not listed as static resources.

https://quarkus.io/guides/http-reference#webjar-locator-support

**Comment by harshlancer** [comment]
Is there anything to be done by a newbie like me?

**Comment by FroMage** [comment]
Sure, this can be done by new contributors.

**Comment by afonsojramos** [comment]
@FroMage can you better detail what is it that you need? What are the URIs that need to be added?

**Comment by Parthib314** [comment]
Hey @FroMage , Can I contribute in this issue???

**Comment by majlantalik** [comment]
@FroMage I'd like to be assigned this issue please. I have prepared the Dev UI screen and would love to start a pull request soon.
