### ISSUE TITLE
Logging on windows cmd or power shell with encoding problems?

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#2128]
Running the examples on Windows 10, from cmd prompt or power shell, the output looks wrongly encoded:

java -jar .\target\rest-json-1.0-SNAPSHOT-runner.jar
[38;5;145m2019-04-17 11:35:35,155[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.quarkus[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mQuarkus [38;5;188m0.13.3[39m started in [38;5;188m2.009[39ms. [38;5;188mListening on: http://[::]:8080[39m[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-04-17 11:35:35,175[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.quarkus[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mInstalled features: [[38;5;188mcdi, resteasy, resteasy-jsonb[39m][39m[38;5;203m[39m[38;5;227m
[39m

Is there any configuration that can be done to correct this problem?

**Comment by gsmet** [comment]
`quarkus.log.console.color=false` in your `application.properties` should solve the issue.

Unfortunately, it's hard to know if the console supports colors. You don't have the issue with the Maven output? Is it colorized at all?

**Comment by seseso** [comment]
No, maven works just fine (you can have a look at the attached printscreen).

![image](https://user-images.githubusercontent.com/6703910/56282961-567a5080-6108-11e9-9bd4-9cc795d32550.png)

BTW, is there any place where I can get a list of configurable properties of core and/or extensions (not only for logging)?

Thanks!

**Comment by gsmet** [comment]
> No, maven works just fine (you can have a look at the attached printscreen).

Hmmm, OK, so we will need to understand how to do it properly on Windows.

> BTW, is there any place where I can get a list of configurable properties of core and/or extensions (not only for logging)?

Unfortunately, for now, the answer is: the source code (`@ConfigRoot`/`@ConfigGroup` annotations). We have to work on this.

**Comment by gpthome** [comment]
I was seeing a similar issue...

Listening for transport dt_socket at address: 5005
←[38;5;145m2019-06-26 06:47:54,334←[39m←[38;5;188m ←[39m←[38;5;107mINFO ←[39m←[38;5;188m [←[39m←[38;5;69mio.qua.dep.QuarkusAugmentor←[39m←[38;5;188m] (←[39m←[38;5;71mmain←[39m←[38;5;188m) ←[39m←[38;5;151mBeginning quarkus

Setting `quarkus.log.console.color=false` did actually make the gibberish go away when running `mvn compile quarkus:dev`.  I was seeing the gibberish from both a Windows CMD window and an Eclipse Terminal.  I'm running Windows 7.  When I ran Quarkus using the Eclipse Run Configuration... the output was normal.

Thank you!

**Comment by gsmet** [comment]
@jaikiran do you know if this is still an issue?

**Comment by rsvoboda** [comment]
Windows logging is OK for some time, closing this issue.
