### ISSUE TITLE
Connect the MockServer testcontainer to the DevService testcontainer Docker network in the integration test

### ISSUE THREAD

**Issue by haschi** [quarkusio/quarkus#21284]
### Description

As already asked in the [question on Stackoverflow](https://stackoverflow.com/questions/69855376), I would like to connect a [testcontainer (MockServer)](https://www.testcontainers.org/modules/mockserver/) to the Docker network that was started by Quarkus DevService in the integration test. I would like to explain my problem using this [graphic](https://drive.google.com/file/d/1q_wmU8jtiNPDaSxL_wV0BTJIpu9n-h4P/view?usp=sharing):

My application ([wolkenschloss / nubes / cookbook](https://github.com/wolkenschloss/nubes)) imports data from an external source. In the test, the deployment artifact is to be tested in the Docker container (`-Dquarkus.container-image.build = true`). The data (the imported recipe) is persisted in a MongoDB. The MongoDB is managed by the Quarkus DevService in the integration test. This starts the Docker container of MongoDB with the option `--net [random-network-name]`. Quarkus generates a connection string for MongoDB with a host alias for access to the database. So far everything is very comfortable.

Now the external data source is to be simulated by a MockServer. Since the application runs in a Docker container, *localhost* cannot be used because *locahost* is now the Docker container. A connection from the Docker container to the MockServer must be established. To do this, the MockServer must release its port to the host (development computer or CI server) and the ImportService must be given an IP address of the host (not 127.0.0.1) as the import source. Determining the host IP address can sometimes lead to unexpected results if several adapters are installed (or none at all). Alternatively I tried to connect the MockServer testcontainer to the `Network.SHARED` network. However, this is not the network that Quarkus DevServices is using. In summary, the procedure is anything but comfortable.

In my example, I am currently using Wiremock without a container, but I would prefer to run MockServer in a test container in the same Docker network as the MongoDB and the Quarkus application to be tested. For the test, it should be transparent whether the application is running in a Docker container or not.

I consider this scenario to be quite common. External systems that cannot be controlled should also be mocked in an integration test: [Integrated Tests Are A Scam}) https://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam)

(And if I had one more wish: A little more control over the life cycle of the container would be nice. For example, restarting the database container before each test, even if it takes a little more time).

**Comment by geoand** [comment]
Thanks for reporting.

I looked into it and I think I have a solution which I'll try out soon.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21287 is what I propose

**Comment by eijckron** [comment]
@geoand I'm trying to integrate mock-server (no other dev services) this way using [paragraph 16.1 of the Quarkus test documentation](https://quarkus.io/guides/getting-started-testing)

When using quarkus.container-image.build=false no network id is provided so no call to withNetworkMode is needed and the mapped port is used for the downstream service url. The service under test nicely calls mock-server when a downstream service call is performed.

When using quarkus.container-image.build=true a nework id (f.i, quarkus-integration-test-DlbKd) is supplied. Calling withNetworkMode(containerId) however produces this error:  
```
java.lang.RuntimeException: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.MockServer@15b3a09c
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.MockServer@15b3a09c
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: com.github.dockerjava.api.exception.NotFoundException:
Status 404: {"message":"network quarkus-integration-test-DlbKd not found"}
```
So somehow the network is not yet available when QuarkusTestResourceLifecycleManager.start is called.
This is on Windows in case that makes a difference.

Is there any example code using this feature that I can look into to see if I missed something?

**Comment by geoand** [comment]
Do you have an example application that I can look at?

**Comment by eijckron** [comment]
I've put a [minimal example on github](https://github.com/eijckron/quarkus-integration-test-example)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21932 takes care of the docker network timing creation issue. 
Thanks for bringing it to my attention!

**Comment by haschi** [comment]
It works for me if I provide my own implementation of the network interface:

```java
import org.jetbrains.annotations.NotNull;
import org.junit.runner.Description;
import org.junit.runners.model.Statement;
import org.testcontainers.containers.Network;
import org.testcontainers.shaded.org.apache.commons.lang.NotImplementedException;

record ContainerNetwork(String id) implements Network {

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void close() {
    }

    @NotNull
    @Override
    public Statement apply(@NotNull Statement base, @NotNull Description description) {
        throw new NotImplementedException();
    }
}
```
Then, depending on whether the `containerNetworkId` is present or not, I call the `MockServerContainer.withNetwork ()`  method:

```java
    @Override
    public void setIntegrationTestContext(DevServicesContext context) {
        this.mockServerContainer = context.containerNetworkId()
                .map(ContainerNetwork::new)
                .map(this::container)
                .orElseGet(this::container);

        context.containerNetworkId().ifPresent(id -> logger.infov("container network id: {0}", id));
    }

    private MockServerContainer container(ContainerNetwork network) {
        logger.infov("container network id: {0}", network.id());
        return container()
                .withNetwork(network)
                .withNetworkAliases(ALIAS);
    }

    @NotNull
    private MockServerContainer container() {
        return new MockServerContainer(IMAGE_NAME.withTag(IMAGE_TAG));
    }
```

[Example](https://github.com/wolkenschloss/nubes/blob/v0.0.9/services/cookbook/service/src/integrationTest/java/family/haschka/wolkenschloss/cookbook/testing/MockServerResource.java)

Maybe a bit awkward, but it works.

**Comment by einarjohnson** [comment]
I think I am facing the same issue here. @geoand , is there a version where the above fix is available?

**Comment by geoand** [comment]
2.5 should contain the fixes

**Comment by eijckron** [comment]
@einarjohnson It works with 2.5.0
See my working example: https://github.com/eijckron/quarkus-integration-test-example/tree/working-example
It connects to the provided network, configures properties, provides a client and logs to a file.

**Comment by einarjohnson** [comment]
@eijckron and @geoand. The problem I am facing is that networking from my application container does not work when it tries to communicate with MySQL and Kafka containers. (the application is a Kafka consumer that processes messages from a topic into MySQL).

I am testing it using `./mvnw clean verify -Dquarkus.container-image.build=true` 

Are there any good examples/guides than could help me achieve this when using the `quarkus-container-image-jib extension` to
build and publish my solution?

**Comment by geoand** [comment]
So your application is launching both a MySQL and a Kafka dev service?

**Comment by einarjohnson** [comment]
@geoand, I am using a test resource where I implement `QuarkusTestResourceLifecycleManager `and `DevServicesContext.ContextAware`. Inside that class I start the Kafka and MySQL containers and I use the `containerNetworkId `I receive from the `setIntegrationTestContext `override, much like @eijckron  does in his example.

**Comment by eijckron** [comment]
@einarjohnson Just to be sure, when running the application as a docker image the application container should use the hostname of mock-server (ALIAS = "mockserver" in my example code), mysql and kafka containers.
I assume dev services fix this for you for mysql and kafka.
In this case the application code runs within the docker network while your test code does not.

From your test code however you have to connect to a mapped port on localhost.

This differs from the run application from jar scenario since then the mock-server, mysql and kafka containers are accessed through their mapped port on localhost both from the application code and the test code.

**Comment by einarjohnson** [comment]
hi again. I think I have figured out what the problem was. Like you say @eijckron, I needed to use the hostname aliases. I was also incorrectly using `@TestProfile` instead of `@QuarkusTestResource.` 
Thanks for all the help here guys, really appreciate the input.

**Comment by einarjohnson** [comment]
hi again. wanted to ask one more question. I have structured my tests pretty much you do @eijckron where I have a `@QuarkusTest` using a `@QuarkusTestResource` that spins up my Testcontainers. Then I have a `@QuarkusIntegrationTest` that simply extends my existing `@QuarkusTest` without any code in it.
Everything works perfectly when I run this locally on my machine and both Surefire and Failsafe execute the tests successfully. However, when I try to get this running inside Gitlab the @QuarkusTest is executed successfully but when the `@QuarkusIntegration` test executes then then `@QuarkusTestResource` class is not created and the start method in it is never  executed.  This fails the test because I am @BeforeAll clause access the containers to set up helpers to communicate with the MySQL/Kafka containers. Any ideas what I might be doing wrong @geoand and @eijckron ?

I am starting the process in a Gitlab build step like this:
  script:
```
    - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - export QUARKUS_CONTAINER_IMAGE_IMAGE=${CI_REGISTRY_IMAGE}:${VERSION}
    - >
      $CI_PROJECT_DIR/mvnw -s $CI_PROJECT_DIR/.m2/settings.xml -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
      -Dquarkus.container-image.registry=${CI_REGISTRY}
      -Dquarkus.container-image.username=${CI_REGISTRY_USER}
      -Dquarkus.container-image.password=${CI_REGISTRY_PASSWORD} clean verify
```

**Comment by eijckron** [comment]
@einarjohnson My knowledge on gitlab is limited. As far as I know the build runs in a container. Does it allow to fire containers within this build container?

**Comment by einarjohnson** [comment]
@eijckron , i think it does. i have a services segment in my gitlab-ci.yml
```
  services:
    - name: my-repo.company.com/third-party/docker:19-dind
      alias: docker
      command: ["--registry-mirror", "https://my-mirror.registry.com"]
```
Also, the @QuarkusTest step seems to work fine which is firing up MySQL/Kafka test containers. :\

**Comment by edeandrea** [comment]
@geoand take a look at #23916. It's the Apicurio service that is started by Dev Services
