### ISSUE TITLE
Expand Kotlin "coroutines and Mutiny" documentation 

### ISSUE THREAD

**Issue by rgmz** [quarkusio/quarkus#21297]
### Description

Presently, the [Kotlin guide](http://quarkus.io/guides/kotlin) includes a small section about using coroutines: ["Kotlin coroutines and Mutiny"](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/kotlin.adoc#kotlin-coroutines-and-mutiny). However, the linked `mutiny-kotlin` documentation only describes the extension functions, not how to use coroutines with Kotlin. 

> Kotlin coroutines provide a imperative programming model that actually gets executed in an asynchronous, reactive manner. To simplify the interoperation between Mutiny and Kotlin there is the module io.smallrye.reactive:mutiny-kotlin, described here.

After fiddling around with the `getting-started` project, I was able to use coroutines (`suspend fun`) by switching to "reactive" libraries:
- `quarkus-resteasy-reactive` instead of `quarkus-resteasy`
- `quarkus-resteasy-reactive-jackson` instead of `quarkus-resteasy-jackson`
- `io.smallrye.reactive:mutiny-kotlin` instead of `io.quarkus:quarkus-resteasy-mutiny`
- potentially others?

### Implementation ideas

Provide a minimal Kotlin coroutines example; or, make clear what dependencies, configuration, and code (if applicable) is required to use coroutines in your application.

**Comment by heubeck** [comment]
WDYT @rgmz
https://github.com/quarkusio/quarkus/pull/21416

Something more, you would like to add?

**Comment by rgmz** [comment]
Thanks for opening a PR, @heubeck. 

Is there a compelling reason why a user would want to use `resteasy` instead of `resteasy-reactive`? In other words, is there a downside to recommending `resteasy-reactive` by default? I'm not familiar with the pros and cons of each.

**Comment by heubeck** [comment]
I would for sure stay with RESTeasy, if it's about best possible stability.
But when using the Kotlin extension, which is considered experimental by itself, there's no reason against RESTEasy Reactive in my opinion - especially as you tent to use coroutines in a Kotlin app.

Happy to ready your obstacles in first adopting the Quarkus/Mutiny/Kotlin stack.

**Comment by hmchangm** [comment]
Hi @rgmz 
I have a sample project with quarkus & kotlin coroutines and also arrow kt. 
https://github.com/hmchangm/quarkus-reactive-kotlin

**Comment by cescoffier** [comment]
We are recommending RestEasy reactive. See https://quarkus.io/blog/resteasy-reactive-smart-dispatch/. 

RestEasy is still supported, but the reactive variant provides more features.

**Comment by geoand** [comment]
Closing this as it seems to be covered by https://github.com/quarkusio/quarkus/pull/21416
