### ISSUE TITLE
OIDC client needs extra flexibility

### ISSUE THREAD

**Issue by liamor** [quarkusio/quarkus#21310]
### Description

I am attempting to authenticate with an NHS service that uses an idiosyncratic Microsoft OAuth implementation and I have hit an edge case that suggests some extra flexibility may be needed. 
Their service only has one endpoint which is the token endpoint. There is no auto-discovery. Due to this lack of auto-discovery, I have to set the token-path so I took the last part of the server URL and added that to token-path. However, the service insists that the JWT audience is the entire path to the token endpoint. When the JWT is signed however only the auth server URL is used for the audience.
My configuration is 
```
quarkus.oidc-client.client-enabled=true
quarkus.oidc-client.grant.type=client
quarkus.oidc-client.auth-server-url=https://dev.api.service.nhs.uk/oauth2
quarkus.oidc-client.client-id=<my_cid>
quarkus.oidc-client.discovery-enabled=false # token path MUST be set
quarkus.oidc-client.token-path=/token
quarkus.oidc-client.credentials.jwt.key-file=pk.pem
quarkus.oidc-client.credentials.jwt.token-key-id=<my-kid>
quarkus.oidc-client.credentials.jwt.signature-algorithm=RS512 # works as I am using the snapshot build
```
This means that in the OidcCommonUtils class in the signJwtWithKey method the JWT audience is set to `https://dev.api.service.nhs.uk/oauth2` where the service insists on `https://dev.api.service.nhs.uk/oauth2/token`. 

### Implementation ideas

Maybe some configuration options could be added to override the default JWT values for these restricted OIDC implementations.

**Comment by liamor** [comment]
Possibly another way would be to have some flag that allows the token-path to be omitted when discovery-enabled is set to false.

**Comment by sberyozkin** [comment]
@liamor Hi, you can configure it as

```
quarkus.oidc-client.grant-options.client.audience=https://dev.api.service.nhs.uk/oauth2/token
```

Can you try it please ? I've opened an issue to improve the OidcClient docds

**Comment by sberyozkin** [comment]
@liamor That is not correct - I'll have to investigate

**Comment by sberyozkin** [comment]
@liamor by the way, one should be able to drop a key id configuration if the key represented in a JWK format with a `kid` property

**Comment by liamor** [comment]
> @liamor Hi, you can configure it as
> 
> ```
> quarkus.oidc-client.grant-options.client.audience=https://dev.api.service.nhs.uk/oauth2/token
> ```
> 
> Can you try it please ? I've opened an issue to improve the OidcClient docs

Yes, that was the first thing I tried but as you've no doubt seen it just adds to the form fields.

**Comment by sberyozkin** [comment]
@liamor IMHO it would make sense to add a dedicated `audience` parameter - it is possible to configure a grant request with as many parameters as needed (such as `audience`) - but that affects what is included in the actual token form request (as I've just seen you confirming as well :-)).
Can you please try `smallrye.jwt.sign.new-token.audience` for now ? I'll finish some other task and then add this property.
Going forward, if some more properties, beyond those which are spec-ed for the JWT based authentication will be needed then I'll add an `extra-params` Map property as well

**Comment by liamor** [comment]
Hmm, doesn't seem to work. Does this get overridden by the explicit audience being set in the `signJwtWithKey` method?

**Comment by sberyozkin** [comment]
@liamor My fault, forgot it has to be accompanied with `overrid-matching-claims`, see https://quarkus.io/guides/security-jwt-build#smallrye-jwt-builder-configuration

**Comment by liamor** [comment]
Interesting... that worked but only when I also set the 'smallrye.jwt.new-token.issuer' as well. But the important thing is that it worked. Thanks, and I'll test with the new settings when you are able to get those out there.

**Comment by sberyozkin** [comment]
@liamor thanks, good it works now,

> that worked but only when I also set the 'smallrye.jwt.new-token.issuer' as well

Can you clarify please ? Did you have to set a different issuer value as well (different the client id) ?

**Comment by liamor** [comment]
Sorry, I just re-checked and I didn't need to set the issuer. I must have got something wrong previously.

**Comment by sberyozkin** [comment]
@liamor Please see #21319 - so once it is merged it will work for you without having to customize the audience - the provider you are dealing with has implemented the JWT authentication processing very precisely and correctly  :-)

**Comment by liamor** [comment]
Thank you very much.
