### ISSUE TITLE
Provide a useful error message when a user is not logged into an OpenShift cluster

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#21311]
### Description

And attempts to build/deploy a container image.

**Comment by geoand** [comment]
I think this makes a lot of sense.

@iocanel is there any utility in the client we can use here?

**Comment by geoand** [comment]
I think this makes a lot of sense.

@iocanel is there any utility in the client we can use here?

**Comment by brunobaiano** [comment]
Hi there,
I don't know if this is the best way... but... why should I be logged and already choosed my project?

Wouldn't it be nice to have properties for that?

Is there some guide of best practices for this deploy? I'm thinking in build a script to encapsulate my logic here.

**Comment by mkouba** [comment]
> Wouldn't it be nice to have properties for that?

There are properties to log in automatically. We've update the guide: https://quarkus.io/version/main/guides/deploying-to-openshift#log-into-the-openshift-cluster

**Comment by brunobaiano** [comment]
This is great news mkouba! thanks for the update!

But now... imagine I have 2 projects... I still need to be on the right project right?

Is there some magic to set my project too? =D

**Comment by geoand** [comment]
> I think this makes a lot of sense.
> 
> @iocanel is there any utility in the client we can use here?

Same question for @manusa

**Comment by mkouba** [comment]
> This is great news mkouba! thanks for the update!
> 
> But now... imagine I have 2 projects... I still need to be on the right project right?
> 
> Is there some magic to set my project too? =D

That's a good question for someone who knows more about the openshift extension ;-)

**Comment by geoand** [comment]
> > This is great news mkouba! thanks for the update!
> > But now... imagine I have 2 projects... I still need to be on the right project right?
> > Is there some magic to set my project too? =D
> 
> That's a good question for someone who knows more about the openshift extension ;-)

`quarkus.openshift.namespace=myproject`

**Comment by mkouba** [comment]
> > > This is great news mkouba! thanks for the update!
> > > But now... imagine I have 2 projects... I still need to be on the right project right?
> > > Is there some magic to set my project too? =D
> > 
> > 
> > That's a good question for someone who knows more about the openshift extension ;-)
> 
> `quarkus.openshift.namespace=myproject`

Hm, a nitpicking detail - we don't mention this in the Configuration Reference. Let me send a PR.

**Comment by manusa** [comment]
> is there any utility in the client we can use here?

We actually do something similar in JKube when performing an [S2I build](https://github.com/eclipse/jkube/blob/a4f9cf43b5eb9267bc3f225fed6543d074ce4821/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java#L238)

```java
client.isAdaptable(OpenShiftClient.class);
```

**Comment by mkouba** [comment]
@geoand Hm, `quarkus.openshift.namespace=myproject` does not seem to work. I have `quarkus.openshift.namespace=mkouba-stage` in my config but I can see the following log in the console:
```
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] An openshift deployment was requested, but the container image group:mkouba-stage is not aligned with the currently selected project:mkouba-dev.it is strongly advised to align them, or else the image might not be reachable.
```

**Comment by geoand** [comment]
> @geoand Hm, `quarkus.openshift.namespace=myproject` does not seem to work. I have `quarkus.openshift.namespace=mkouba-stage` in my config but I can see the following log in the console:
> 
> ```
> [WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] An openshift deployment was requested, but the container image group:mkouba-stage is not aligned with the currently selected project:mkouba-dev.it is strongly advised to align them, or else the image might not be reachable.
> ```

It looks like the check we perform before printing that message is far to simplistic... WDYT @iocanel since you are the one that added this check?

**Comment by mkouba** [comment]
It's not only the log message - the app is not deployed under the specified project...

**Comment by brunobaiano** [comment]
yes.... I think it's some protection from openshift.
On console... if you try to import a yaml with a diferent project... it´s rejected.

I think 
quarkus.openshift.namespace=myproject
should do an "oc project myproject" too.

**Comment by iocanel** [comment]
FWIW, the `quarkus.openshift.namespace` is used to set namespace to the target resources. I am not sure if the deployer takes it into consideration and I am not even sure if it needs to (e.g. I am not sure if we need to do something about it, or if setting the namespace in the resources is enough). Still, the end result should be the same: `the app deployed to the specified namesapce`.

So, from what I read the action items should be:
- Display a valid error message if connection to a cluster cannot be established.
- Display a valid error message if target cluster does not match our needs (e.g. we need openshift but cluster is vanilla).
- Ensure resources are deployed to the right namespace.

Let me pick this up

**Comment by mkouba** [comment]
> Let me pick this up

+1 

Let me know if you need to test something :-)
