### ISSUE TITLE
[2.4.1] Kubernetes extension does not expose the correct port?

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#21314]
### Describe the bug

Hi!

I have just started to get to know the Kubernetes extension, and I found something strange.

I have created the project from: [](https://quarkus.io/guides/deploying-to-kubernetes)

**mvn io.quarkus.platform:quarkus-maven-plugin:2.4.1.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=kubernetes-quickstart -DclassName="org.acme.rest.GreetingResource" -Dpath="/greeting" -Dextensions="resteasy,kubernetes,jib"**

After that I modified the application.properties with one single line:

**quarkus.http.port = 8888**

Then I ran the **mvnw package** command and saw the output in the **target/kubernetes** folder:

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-11-09 - 13:24:11 +0000
  labels:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kubernetes-quickstart
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-11-09 - 13:24:11 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: kubernetes-quickstart
  name: kubernetes-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: kubernetes-quickstart
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-11-09 - 13:24:11 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: kubernetes-quickstart
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: user/kubernetes-quickstart:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: kubernetes-quickstart
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP 

At the Service section, it shouldn't be

spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888

instead of

spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888

?

I looked at the configuration options but couldn't find a value where the default would be 80, so I have no idea what would need to be changed to include the 8888 IP.

Best regards,
Viktor

**Comment by geoand** [comment]
Thanks for reporting.

This works as expected, see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#service-port-mapping
