### ISSUE TITLE
Hibernate Reactive with Panache can't insert into a jsonb column

### ISSUE THREAD

**Issue by brunobastosg** [quarkusio/quarkus#21313]
### Describe the bug

I'm using [Quarkus Hibernate Types](https://github.com/quarkiverse/quarkus-hibernate-types) to map some attributes of my entity to PostgresSQL's `jsonb` column type.

If I use the regular JDBC driver, it works normally.

However, when using Hibernate Reactive, querying works, but inserting new entities fail with the error:

```
{"details":"Error id 3c00e4fb-6fc9-4953-9594-0410fa4c9093-1, io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[0] with class = [com.fasterxml.jackson.databind.node.ObjectNode] and value = [{\"field\":\"value\"}] can not be coerced to the expected class = [java.lang.Object] for encoding.","stack":"io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[0] with class = [com.fasterxml.jackson.databind.node.ObjectNode] and value = [{\"field\":\"value\"}] can not be coerced to the expected class = [java.lang.Object] for encoding."}
```

### Expected behavior

It should insert the entity with no error.

### Actual behavior

The entity is not inserted and an error occurs.

### How to Reproduce?

1. Clone [this](https://github.com/brunobastosg/hibernate-reactive-jsonb-column) repo
2. Run `docker-compose up` to start the db
3. Run `./mvnw quarkus:dev` to start the app
4. Run the following curl to try to insert data:

```
curl -X POST -H 'Content-Type: application/json' -i http://localhost:8080/example --data '{
  "id": 3,
  "content": { "yetAnotherField": "yetAnotherValue" }
}'
```

If you run `curl -X GET -i http://localhost:8080/example`, it works perfectly.

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1288]

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by DavideD** [comment]
`hibernate-types` sometimes requires a JDBC connection so not everything in it is compatible.
That said, I've tried to run the project associated to the issue and it seems to work as expected (I don't see any error).
Is this still an issue?

**Comment by DavideD** [comment]
I'm going to close this issue. The project works because they've already switch to the right approach that it's to map the Json field using a JsonObject

**Comment by brunobastosg** [comment]
@DavideD it is working because of [PR #1](https://github.com/brunobastosg/hibernate-reactive-jsonb-column/pull/1), which implements an `AttributeConverter` to map the column. But without it, it doesn't work. You can checkout the [first commit](https://github.com/brunobastosg/hibernate-reactive-jsonb-column/commit/d5405b6c8bb3ad4c1f562d0b3dccf884d894d291) to see the original error.

**Comment by DavideD** [comment]
Let me check

**Comment by DavideD** [comment]
It doesn't work because Hibernate Types convert the map to a `JsonNode` and the Vert.x SQL Client is not happy with it. It seems I was too optimistic about the compatibility between Hibernate Reactive and Hibernate Types. In the end I don't think this is bug nor something that we should solve.

It seems that Hibernate Reactive and Vert.x already offer a nice solution for this.

**Comment by DavideD** [comment]
Note that if you don't care about the field being a map, you can declare the entity field as `JsonObject` and everything will work without a converter

**Comment by brunobastosg** [comment]
Actually, if I declare it as `JsonObject`, then it serializes/deserializes incorrectly, as seen below. That was what the converter solved.

```
[{
  "id": 1,
  "content": {
    "map": {
      "field": "value"
    },
    "empty": false
  }
}, {
  "id": 2,
  "content": {
    "map": {
      "anotherField": "anotherValue"
    },
    "empty": false
  }
}, {
  "id": 3,
  "content": {
    "map": {},
    "empty": true
  }
}]
```

It should be:

[{
  "id": 1,
  "content": {
    "field": "value"
  }
}, {
  "id": 2,
  "content": {
    "anotherField": "anotherValue"
  }
}, {
  "id": 3,
  "content": {}
}]

**Comment by DavideD** [comment]
Probably the current the solution with the converter is the easiest one.
But converting the type into a response is not Hibernate Reactive responsibility.

It seems that RestEasy reactive doesn't recognize `JsonObject` as  a type and so it converts the values using all internal properties.

It would make sense to include it in the built-in types but I'm not sure whom should I ask about it.
@gsmet Any idea?

**Comment by brunobastosg** [comment]
> Probably the current solution with the converter is the easiest one. But converting the type into a response is not Hibernate Reactive responsibility.

Yeah, I'll keep using that for now.

Thank you for your time!

**Comment by DavideD** [comment]
Thanks for your feedack! It was really helpful

**Comment by DavideD** [comment]
I've created this issue on Hibernate Reactive: https://github.com/hibernate/hibernate-reactive/issues/1180
Maybe we can do something for making this easier to handle

**Comment by brunobastosg** [comment]
Thanks, will be following that!

**Comment by FroMage** [comment]
> It seems that RestEasy reactive doesn't recognize JsonObject as a type and so it converts the values using all internal properties.

Pretty sure RESTEasy Reactive handles `JsonObject`, right @geoand ?

**Comment by geoand** [comment]
Correct, see https://github.com/quarkusio/quarkus/blob/2.7.0.Final/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/providers/serialisers/jsonp/JsonObjectHandler.java#L16

**Comment by DavideD** [comment]
I've changed the entity from the example in this issue the following way:
```
@Entity
public class Example {

    @Id
    private int id;

    @Convert(converter = MapJsonConverter.class)
    private Map<String, Object> content;

   ...
    public Map<String, Object> getContent() {
        return content;
    }

	public JsonObject getContentAsJsonObject() {
		return new JsonObject(content);
	}

       ...
}
```

when do GET, It returns:
```
    {               
        "content": {                            
            "field": "value"
        },                      
        "contentAsJsonObject": {
            "empty": false,
            "map": {                                
                "field": "value"
            }
        },      
        "id": 1
    }
```

So there is definitely a difference between using a map or a `JsonObject`. Maybe this is correct but I don't think it's what a user would expect.
