### ISSUE TITLE
Unable to retrieve status for gRPC service

### ISSUE THREAD

**Issue by ruromero** [quarkusio/quarkus#21317]
### Describe the bug

When running IntegrationTests with `@grpcService` and not an HTTP server, Quarkus is not able to retrieve the status of the running process and it fails with the following error:

```
2021-11-08 14:26:58,647 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-1) gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
2021-11-08 14:26:58,647 INFO  [io.quarkus] (main) grpc-impl 1.0.0-SNAPSHOT native (powered by Quarkus 2.4.0.Final) started in 0.012s.
2021-11-08 14:26:58,647 INFO  [io.quarkus] (main) Profile prod activated.
2021-11-08 14:26:58,647 INFO  [io.quarkus] (main) Installed features: [cdi, grpc-server, smallrye-context-propagation, vertx]
Waited 60seconds for target/quarkus.log to contain info about the listening port and protocol but no such info was found
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 61.958 s <<< FAILURE! - in com.redhat.quarkus.reproducer.service.impl.PlayerServiceImplIT
[ERROR] com.redhat.quarkus.reproducer.service.impl.PlayerServiceImplIT.testGet  Time elapsed: 0.042 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
```

### Expected behavior

The IntegrationTests fail to start because the process status cannot be retrieved

### Actual behavior

The IntegrationTests start normally

### How to Reproduce?

The following repository contains a reproducer where the last commit contains the addition of the quarkus-vertx-http:

https://github.com/ruromero/grpc-deps-reproducer/tree/main/grpc-impl

### Output of `uname -a` or `ver`

Linux 5.14.14-200.fc34.x86_64 #1 SMP Wed Oct 20 16:15:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.13 2021-10-19 OpenJDK Runtime Environment 18.9 (build 11.0.13+8) OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by michalszynkiewicz** [comment]
@geoand do you remember what's the reason for checking if host:port that Quarkus listens to is printed in the log and not for the info that Quarkus has started?

**Comment by geoand** [comment]
This is needed to support HTTP services that have a random port set.

If this should not be done for gRPC services, then we might need something custom

**Comment by michalszynkiewicz** [comment]
With grpc, and without http, we don't have this line in the log at all. I'll try to figure something out for this case.
