### ISSUE TITLE
hibernate-orm - config values don't make sense for YAML

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#21324]
### Describe the bug

The documentation for `hibernate-orm` (https://quarkus.io/guides/hibernate-orm) lists 3 configuration properties that cannot be set together when using `application.yaml`.

```
quarkus.hibernate-orm.database.generation (string)
quarkus.hibernate-orm.database.generation.create-schemas (boolean)
quarkus.hibernate-orm.database.generation.halt-on-error (boolean)
```

When writing the YAML, in order to set all 3 properties, this would require `quarkus.hibernate-orm.database.generation` to be both a string and object.

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

Quarkus 2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by mweber03** [comment]
Looks like the same issue exists with:

```
quarkus.hibernate-orm.scripts.generation
quarkus.hibernate-orm."persistence-unit-name".database.generation
quarkus.hibernate-orm."persistence-unit-name".scripts.generation
```

**Comment by famod** [comment]
Have you tried this? https://quarkus.io/guides/config-yaml#configuration-key-conflicts

**Comment by mweber03** [comment]
That worked, thank you.
