### ISSUE TITLE
Upgrade Kafka client version to 2.2.0

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2133]
Currently 1.1.0 is used, which is a rather dated version; is there any specific reason for that, or could we update it to the current one (2.2.0 atm.)? @cescoffier?

**Comment by cescoffier** [comment]
@gunnarmorling the change must be made in:
1.  Vert.x Kafka Client (@ppatierno)
2. SmallRye Reactive Messaging (that would be me)
3. In Quarkus 

Note that Kafka requires some bloody substitutions, so the upgrade must be carefully tested.

**Comment by waldimiro** [comment]
I'm evaluating Quarkus (awesome!) as substitute of Thorntail. In the company, Kafka platform supports org.apache.kafka:kafka-clients:2.0.1 (at most). I tried to solve the problem in POM dependencies:

    ...
	<dependency>
	  <groupId>io.quarkus</groupId>
	  <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.apache.kafka</groupId>
				<artifactId>kafka_2.12</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.kafka</groupId>
				<artifactId>kafka-clients</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
    <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka_2.12</artifactId>
        <version>2.0.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka-clients</artifactId>
        <version>2.0.1</version>
    </dependency>
    ...

Is it correct this solution? what will happen in the future if I will continue to use version 2.0.1 instead of 2.2.0?

**Comment by gunnarmorling** [comment]
@cescoffier, just seeing you recently upgraded Vert.x to 3.7.0 and Kafka client to 2.1.0. That's great, so I'm going to close this issue here.

> In the company, Kafka platform supports org.apache.kafka:kafka-clients:2.0.1 (at most)

 @waldimiro, unless I'm mistaken, a newer client should work with older brokers. So I'd recommend you wait for the next Quarkus version bringing in this upgrade and use that one.
