### ISSUE TITLE
Hashicorp Vault integration stopped working in 2.4.0

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#21336]
### Describe the bug

Our application has a Rest-Client defined with `@RegisterRestClient(configKey = "aclient")`, and config 
```
aclient/mp-rest/url=https://somethi.ng
```
Most of the config lives is Hashicorp Vault when not running locally.
When upgrading to 2.4.0/.1 startup fails with
```
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'quarkus.rest-con
fig."aclient".url' or 'quarkus.rest-config."aclient".uri' to your Quarkus configuration
```

Changing the config key to `quarkus.rest-config."aclient".url`, `quarkus.rest-config.aclient.url`, `quarkus.rest-client.aclient.url` has no effect.

Looking at RestClientBase between [2.3.1](https://github.com/quarkusio/quarkus/blob/2.3.1.Final/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.javaa) and [2.4.1](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientBase.java) we see that handling of config is changed from ` ConfigProvider.getConfig().getOptionalValue(property, class)` to [RestClientsConfig](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/extensions/resteasy-classic/rest-client/config/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java).

My hypothesis is that the code that set `RestClientsConfig.configs` (code generated by [RunTimeConfigurationGenerator](https://github.com/quarkusio/quarkus/blob/2.4.1.Final/core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java)?) uses `ConfigSource.getPropertyNames()`, and [VaultConfigSource](https://github.com/quarkusio/quarkus/blob/main/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java#L51) return empty set for both `getProperties` and `getPropertyNames()`.
When setting breakpoint (java field breakpoint in Intellij) we see that the config from Vault loaded.

The same behaviour is seen with [quarkus-micrometer-registry-influx](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20quarkus-micrometer-registry-influx.20.2B.20Hashicorp.20Vault).

### Expected behavior

All config from Vault is used as if defined in application.properties.

### Actual behavior

Config values stored in Vault is not used, application crash with message that they are mssing.

### How to Reproduce?

* Combine guides for [rest-client](https://quarkus.io/guides/rest-client) and [vault](https://quarkus.io/guides/vault): [quarkus-vault-rest-client reproducer](https://github.com/computerlove/quarkus-vault-rest-client).
* Follow the steps for initializing the local Vault container. 
  * `docker run --rm --cap-add=IPC_LOCK -e VAULT_ADDR=http://localhost:8200 -p 8200:8200 --name=dev-vault vault:1.6.0` (Terminal A)
  * `docker exec -it dev-vault sh` (in new terminal B)
  * `export VAULT_TOKEN=$Root Token FROM terminal A ` (in terminal B)
  * `vault kv put secret/myapps/vault-quickstart/config a-private-key=123456`  (in terminal B)
  * ```
     cat <<EOF | vault policy write vault-quickstart-policy -
     path "secret/data/myapps/vault-quickstart/*" {
        capabilities = ["read"]
    }
    EOF

  * ```
     vault auth enable userpass
     vault write auth/userpass/users/bob password=sinclair policies=vault-quickstart-policy
  * Login to http://localhost:8200 with $Root Token FROM terminal A and add secrets in myapps/vault-quickstart/ (use do it in terminal B)

Downgrading to Quarkus 2.3.1 will make the application work as expected.

### Output of `uname -a` or `ver`

N/A

### Output of `java -version`

11, 17

### Quarkus version or git rev

2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.3

### Additional information

![vault](https://user-images.githubusercontent.com/769579/141089365-17ba2dcb-96fc-41c8-b695-e81d9fe38d4f.png)

**Comment by radcortez** [comment]
As a workaround, adding the properties in another source (application.properties) with empty values should work. This will list the properties in `getPropertyNames()` and on value lookup, it will retrieve the one from Vault because it has an higher ordinal.

In the meanwhile, we will fix this. Sorry for the inconvenience.

**Comment by computerlove** [comment]
Empty values in application.properties does work :)

**Comment by radcortez** [comment]
Great!
