### ISSUE TITLE
Create extension for Apache PDFBox and/or Tika

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2134]
I'll try and send a PR for PDFBox.

**Comment by sberyozkin** [comment]
@gunnarmorling 
I'm working on a Tika extension. Are you doing it too ?

**Comment by sberyozkin** [comment]
@gsmet @gunnarmorling can this issue be closed now ?

**Comment by gsmet** [comment]
Yes, and let's create other more specific issues if needed.
