### ISSUE TITLE
quarkus-amazon-lambda doesn't work after 2.3.0+

### ISSUE THREAD

**Issue by klutzer** [quarkusio/quarkus#21346]
### Describe the bug

This is easy to simulate with a fresh quarkus project (I'm using Kotlin but the problem happens on a Java project as well).

To simulate the bug, just create a project with the lambda-rest/lambda-http extension and then try to execute the tests twice (or open the swagger-ui to invoke the greeting endpoint more than once):
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.4.1.Final:create \
    -DprojectGroupId=com.test \
    -DprojectArtifactId=test-service \
    -DclassName="com.test.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions="resteasy,kotlin,resteasy-jackson,quarkus-amazon-lambda-rest,quarkus-smallrye-openapi"
```
When creating the same project, with the same dependenqqcies, but for version 2.2.3 (or less), the problem doesn't happen.

The following print can describe the problem with more details:

![image](https://user-images.githubusercontent.com/10657645/141162892-41a059ee-f8a5-4b7a-b458-7908a8e25bb1.png)

An important thing to notice is that if you remove the lambda extension, the application works normally (the same for running with lambda extension but on versions 2.2.3-)

### Expected behavior

Creation of quarkus projects for versions 2.3.0+ should work with lambda-rest/lambda-http extensions

### Actual behavior

The test runs successfully just for the first time, and also the dev-ui doesn't work if you try to test the service through swagger or even accessing greeting endpoint directly

### How to Reproduce?

Explained above

### Output of `uname -a` or `ver`

Linux erico-dell 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/erico/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-90-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Can you please enhance the description with information about what exactly is not working?

Thanks

**Comment by patriot1burke** [comment]
I'll check it out.

**Comment by klutzer** [comment]
> Can you please enhance the description with information about what exactly is not working?
> 
> Thanks

Done.

**Comment by patriot1burke** [comment]
Ok, I am able to run in dev mode and invoke on the service multiple times and also access swagger ui and execute swagger ui multiple times. 

I can only reproduce the bug when I re-run tests in test mode.

**Comment by klutzer** [comment]
> Ok, I am able to run in dev mode and invoke on the service multiple times and also access swagger ui and execute swagger ui multiple times.
> 
> I can only reproduce the bug when I re-run tests in test mode.

Yes, but if you just open de DevUI (even with tests not running), the application breaks too:

![image](https://user-images.githubusercontent.com/10657645/141193604-0658eae8-d557-48cd-a469-ca19232d28bd.png)

**Comment by patriot1burke** [comment]
PR should fix things

**Comment by klutzer** [comment]
I think the problem isn't solved yet @patriot1burke @gsmet @geoand . Tested now with 2.5.0 and stil happens.

To simulate, run the tests and then open dev-ui -> swagger (or anything else, inside dev-ui)

**Comment by klutzer** [comment]
Should I open a new issue to this? @patriot1burke

**Comment by patriot1burke** [comment]
Open up a new issue.  I did have problems running test-mode from WITHIN the dev-ui, but everything else worked fine for me.  Please open a new issue with exact steps to reproduce.

**Comment by klutzer** [comment]
Already opened by @AndLvovSky: https://github.com/quarkusio/quarkus/issues/23014
