### ISSUE TITLE
REST Client Config - Limitations of ConfigRoot `RestClientsConfig`

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#21348]
### Describe the bug

We are seeing several issues with the REST Client Config move to the `RestClientsConfig` ConfigRoot added in https://github.com/quarkusio/quarkus/pull/17220.

Related issues:
- https://github.com/quarkusio/quarkus/issues/21341
- https://github.com/quarkusio/quarkus/issues/21336
- https://github.com/quarkusio/quarkus/issues/21332
- https://github.com/quarkusio/quarkus/issues/21345

One of the main issues seems to be the expectation that the REST Client Config (or at least the URL) can be dynamically changed during runtime by just changing the configuration.

Another issue is the way that `RestClientConfig` is mapped. The use of `public Map<String, RestClientConfig> configs;` implies that named configuration (in this case the resource) is added by iterating the `Config#getPropertyNames`. This is usually ok because for most cases we are not aware of the named configuration and this is the only way to retrieve them. In the particular case of REST Clients, the named configuration is known at build time, but we ignore it and fill in the Map with `getPropertyNames` ignoring that some Config Sources like Vault do not provide their property names.

**Comment by radcortez** [comment]
I've been thinking about this for a while and I can't come to a good way to fix this. For most cases, we assume that our configuration is immutable and cannot be changed, but in this case, this is not true.

One issue is the actual expansion of `quarkus.http.test-port=0` (for a random port). The real actual port is only set in the `VertxRecorder` way after we initialized the configuration. What it does, is just to set the System property with the assigned port. The problem here is only the configuration retrieved after the port is set is going to see the new value (excluding all of the ConfigRoots because they were already initialized). Because we have no way to know the random port before config starts, the only option is to update it later (which is a little bit of a problem at the moment, because we don't have a mechanism to do it, again because we assume our configuration is immutable).

On the other hand, it seems that some users were relying on the way we had the REST Client Config before (allowing mutability) to change the configuration during runtime. We were always very strict about this behaviour, so this is something we need to discuss if we want to support it officially.

**Comment by geoand** [comment]
> On the other hand, it seems that some users were relying on the way we had the REST Client Config before (allowing mutability) to change the configuration during runtime. We were always very strict about this behaviour, so this is something we need to discuss if we want to support it officially.

Can you provide an example of what users do that just happened to work in the past and that does not now?
I'm in favor of sticking our ground and not supporting it officially, but would like to see what exactly users were doing and what there options are now.

**Comment by geoand** [comment]
The way I see it, #21341 worked by accident - it was never something we advertised, so I would not put any effort into making it work again

**Comment by franden** [comment]
The problem is not with the implementation of the test. The problem is that there is a reasonable requirement to change the target system of the REST client at runtime, e.g. to address a backup server when the productive server is not available.

There is also a possibility to specify the scope at the REST client. If the scope "@RequestScoped" is specified, then it is only logical that the configuration is read at every request and not once at start. Everything else makes no sense. Why else should you define the scope?

```
@RequestScoped
@RegisterRestClient(configKey = "greetings.client")
public interface GreetingsClient { 
```
If you don't fix this, the behavior of the configuratin framework would not be consistent. Because the other configurations are injected correctly on every request, see test:

```
@ConfigProperty(name = CONFIG_NAME_SALUTATION, defaultValue = "Hoi!!")
String salutation;
```

Please fix the problem.

**Comment by geoand** [comment]
What is mention is not something we ever said would work.

Could you not make your use case work with the REST Client builder API?

**Comment by franden** [comment]
That only the behavior I assumed makes sense, because the configuration framework behaves exactly the same in other cases as in my example. Otherwise the scope specification at `@RegisterRestClient` is meaningless.

REST client builder API would be a possibility but then we would have to inject all configuration parameters with @ConfigProperty and pass them to the builder. These are parameters we always use:
```
- com.mycompany.remoteServices.MyServiceClient/mp-rest/url
- com.mycompany.remoteServices.MyServiceClient/mp-rest/connectTimeout
- com.mycompany.remoteServices.MyServiceClient/mp-rest/readTimeout:
- com.mycompany.remoteServices.MyServiceClient/mp-rest/trustStore
- com.mycompany.remoteServices.MyServiceClient/mp-rest/trustStorePassword
```
This would result in a large amount of boilerplate code for each client.

**Comment by geoand** [comment]
I have stated my opinion, but it's ultimately up to @radcortez and @mschnitzler

**Comment by TomasHofman** [comment]
Hello @franden, when you talk about the requirement to change the target system of the REST client at runtime, I'm not sure we understand it in the same way.

Changing the rest client configuration at runtime is a reasonable and supported feature, but it requires a restart of the application process. How would you change a system property of a running process anyway? If I understand things correctly, the problem in your test is that it tries to change the client configuration without restarting the application process, and that is what is not supported.

So in your scenario, you have an app running with default configuration (started via `java -jar target/quarkus-app/quarkus-run.jar`) and you decide to redirect it to different URL. That means killing the application process (perhaps a Kubernetes pod) and starting the app again with a system property or an env variable that overrides the default config (`java -Dgreetings.client/mp-rest/url=https://www.google.de -jar target/quarkus-app/quarkus-run.jar`). That's how I understand changing the configuration at runtime (i.e. no rebuild needed).

Regarding the `@RequestScoped` annotation, that annotation controls lifecycle of CDI beans. It doesn't have any effect on config loading.

**Comment by franden** [comment]
You are right. Runtime configuration means that you can do a configuration without rebuilding the application. In our case it is necessary to change the configuration at runtime and without restarting the application. The reason is quite simple. The configuration can be changed for example in Azure Key Vault or Azure App Configuration by a key user (Role A). However, restarting the application can only be done by operations team (Role B). In our case, the colleagues do not always have both roles. 


> Regarding the @RequestScoped annotation, that annotation controls lifecycle of CDI beans. It doesn't have any effect on config loading.

I understand that, but if I have a REST client and the class where it is injected are annotated with @RequestScoped, then I expect a new instance of the REST client to be created and injected with each request along with the current configuration. 
But now I understand, that is not guaranteed. For normal [@ConfigProperty](https://github.com/franden/issue-rest-client-configuration/blob/16eb2f28b7a994fbfb6e7d762cfae677d1732e2e/src/main/java/org/zeiss/quarkus/GreetingResource.java#L17) this may be true but can also be changed in the future. Correct?

```
@ConfigProperty(name = CONFIG_NAME_SALUTATION, defaultValue = "Hoi!!")
String salutation;
```

**Comment by geoand** [comment]
> Runtime configuration means that you can do a configuration without rebuilding the application. In our case it is necessary to change the configuration at runtime and without restarting the application

At the risk of sounding like a broken record, this is **not** what Quarkus means by runtime configuration and supporting on the fly changing of configuration is something we have **explicitily**  said we don't support.

For your use case, I don't see what the problem is with the Client Builder API. If your concern is that you would need to reconfigure some of the values you have in `application.properties`, then I am sure we can come up with a programmatic way of including that configuration by default.

**Comment by radcortez** [comment]
I understand the use case and there are many other use cases where reloading the configuration might make sense.

The issue is that officially supporting dynamically reloading the configuration (and affected services) is super tricky, and in some cases, it doesn't even work (don't ask hibernate to reconfigure itself mid-flight). So for consistency, our position was always: we don't support it officially. I think it would be more confusing for the users to understand which configuration can be changed to dynamically reload something on the server.

There are also good reasons for us to validate and load the configuration on the app start (and cache it). This makes sure that all required configuration to run the app is available and that is not going to go away and crash the application later due to a missing configuration.

I think we can try to compromise here a bit. It should be possible to override the default `QuarkusRestClientBuilder` to dynamically read the configuration, so it is not required to change all the code to use the REST Client builder directly.

**Comment by damian-burda** [comment]
> The way I see it, #21341 worked by accident - it was never something we advertised, so I would not put any effort into making it work again.
> 
> That test can definitely be rewritten to use test profiles

I see this more as a hidden feature for tests :) Off course we can rewrite our tests, but I see this in as a valuable feature even if not advertised. 

This way one can easily use parallel build with maven or CI and not have to worry about multiple instances of Quarkus being started at the same time. 

Would it be still acceptable to change the behavior in tests only? I did not test it yet but maybe modifying the RestClientConfig in QuarkusTest*Callback?

**Comment by radcortez** [comment]
> Would it be still acceptable to change the behavior in tests only? I did not test it yet but maybe modifying the RestClientConfig in QuarkusTest*Callback?

Yes, you get a hold of an instance of RestClientConfig and modify it before the REST Client is created you should be able to get the same behaviour (but don't tell anyone :) )

**Comment by franden** [comment]
> For your use case, I don't see what the problem is with the Client Builder API. If your concern is that you would need to reconfigure some of the values you have in application.properties, then I am sure we can come up with a programmatic way of including that configuration by default.

If Client Builder API is used all properties must be looked up manually and the passed to the builder API.  Something like this:

```java
public static <T> T buildClient(String configKey, Class<T> restClientClass) {
    var applicationUri = ConfigProvider.getConfig().getValue(configKey + "/mp-rest/url", URI.class);
    var connectTimeout = ConfigProvider.getConfig().getOptionalValue(configKey + "/mp-rest/connectTimeout", Long.class);
    var readTimeout = ConfigProvider.getConfig().getOptionalValue(configKey + "/mp-rest/readTimeout", Long.class);
    var trustStore = ConfigProvider.getConfig().getOptionalValue(configKey + "/mp-rest/trustStore", String.class);
    var trustStorePassword = ConfigProvider.getConfig().getOptionalValue(configKey + "/mp-rest/trustStorePassword", String.class);
   //all possible other MP REST Client properties

    RestClientBuilder restClientBuilder = RestClientBuilder.newBuilder().baseUri(applicationUri);

    Optional<KeyStore> loadedTrustStore = loadTrustStore(trustStore, trustStorePassword);

    connectTimeout.ifPresent(value -> restClientBuilder.connectTimeout(value, TimeUnit.MILLISECONDS));
    readTimeout.ifPresent(value -> restClientBuilder.readTimeout(value, TimeUnit.MILLISECONDS));
    loadedTrustStore.ifPresent(value -> restClientBuilder.trustStore(value));

    //all possible other MP REST Client properties
    return restClientBuilder.build(restClientClass);
}
```

This is exactly the same logic which MP REST Client implementation would do during the start up. It is not a problem but additional effort to implement something what is already implemented.

**Comment by franden** [comment]
> I think we can try to compromise here a bit. It should be possible to override the default QuarkusRestClientBuilder to dynamically read the configuration, so it is not required to change all the code to use the REST Client builder directly.

Can you please give me an example of what the code would look like?

**Comment by geoand** [comment]
> This is exactly the same logic which MP REST Client implementation would do during the start up. It is not a problem but additional effort to implement something what is already implemented.

Which is why I metioned above that we should provide some way for the values in `application.properties` to be easily usable.

**Comment by franden** [comment]
>Which is why I metioned above that we should provide some way for the values in application.properties to be made available to the Builder API without requiring users to write this boilterplate.
Ahhh. Got it. Thanks

**Comment by radcortez** [comment]
> > I think we can try to compromise here a bit. It should be possible to override the default QuarkusRestClientBuilder to dynamically read the configuration, so it is not required to change all the code to use the REST Client builder directly.
> 
> Can you please give me an example of what the code would look like?

It depends on how you want to code it but, dynamic config retrieval could be done here by entending this class and overriding the `build` method.

https://github.com/quarkusio/quarkus/blob/1e517c8cc58a743e879f437821d1cfd9c0c79e0a/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusRestClientBuilder.java#L234

Registration is just a static call to `org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver#setInstance` to add a new Resolver for the new Builder. In this way, you are not required to have producer methods to change any of the code where REST Clients are used.

Alternatively, you can modify at your own risk the values of `RestClientsConfig` :)

**Comment by michalszynkiewicz** [comment]
@radcortez WDYT about resigning from FallbackConfigSourceInterceptor for REST clients?

**Comment by radcortez** [comment]
> @radcortez WDYT about resigning from FallbackConfigSourceInterceptor for REST clients?

Fine by me.
