### ISSUE TITLE
Support "Uncategorized" extensions

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#21350]
### Description

Currently extensions without category are not processed and not visible in code.quarkus.io

### Implementation ideas

Use "uncategorized" as category here (if empty): https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/platform/catalog/processor/CatalogProcessor.java#L25

Add "Uncategorized" as category last in `orderedCategories` here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/platform/catalog/processor/CatalogProcessor.java#L33

**Comment by geekiyer** [comment]
I will try to take a stab at this!
