### ISSUE TITLE
/metrics/application is not working

### ISSUE THREAD

**Issue by rafabene** [quarkusio/quarkus#2135]
I just followed https://quarkus.io/guides/metrics-guide

Executed the application https://github.com/quarkusio/quarkus-quickstarts/tree/master/microprofile-metrics 

The path `/metrics/application` has an empty response.

```
curl -v http://localhost:8080/metrics/application
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics/application HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< Date: Wed, 17 Apr 2019 16:19:28 GMT
<
* Connection #0 to host localhost left intact
```

**Comment by geoand** [comment]
@rafabene did you first execute `curl localhost:8080/350` and `curl localhost:8080/629521085409773`?

I tried it `/metrics/application` worked as expected after executing the curl commands above.

**Comment by kenfinnigan** [comment]
That's probably something we should fix in SmallRye Metrics.

Currently if no Application metrics have been captured, the endpoint returns an empty response

**Comment by rafabene** [comment]
Thanks @geoand . Now it worked for the quickstarts and for my application.

**Comment by cescoffier** [comment]
@kenfinnigan well, I would say that if we don't have application metrics yet, the `204` response looks right. 

However, the documentation should mention it.

**Comment by jmartisk** [comment]
This is because currently the metrics are registered lazily, when the bean that declares a metric is first constructed, only then the metric will be initialized. This will be fixed though https://github.com/quarkusio/quarkus/issues/1435 soon, I have the solution almost ready, just needs some more testing.

**Comment by jmartisk** [comment]
204 response is correct if there are no metrics. This is according to MP Metrics specification https://github.com/eclipse/microprofile-metrics/blob/1.1.1/spec/src/main/asciidoc/metrics_spec.adoc#23-exposing-metrics-via-rest-api

**Comment by jmartisk** [comment]
This should be resolved now with latest versions. The metrics from `PrimeNumberChecker` (except the Gauge) will be visible at `/metrics/application` right after the start even before sending any other HTTP requests. Can we close this?
