### ISSUE TITLE
Can't use GlobalInterceptor gRPC annotation with interceptor produced by a method

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#21358]
### Describe the bug

I have a server interceptor produced by a method:
```java
  @Produces
  public ServerInterceptor serverInterceptor() {
    return new LoggingServerInterceptor();
  }
```

I want to make it global by putting io.quarkus.grpc.GlobalInterceptor annotation.

I can't put this annotation on the producer method, because the annotation has `@Target({ FIELD, PARAMETER, TYPE })` (not applicable to methods).

And I can't put this annotation on LoggingServerInterceptor class, because the class does not have any CDI bean annotations on it. Quarkus complains:
```
2021-11-11 04:23:49,640 ERROR [io.qua.grp.run.GrpcServerRecorder] (main) Unable to start the gRPC server: java.lang.IllegalArgumentException: Server interceptor class class com.azul.cc.infrastructure.grpc.LoggingServerInterceptor is not a CDI bean. Only CDI beans can be used as gRPC server interceptors. Add one of the scope-defining annotations (@Singleton, @ApplicationScoped, @RequestScoped) on the interceptor class.
```

### Expected behavior

The GlobalInterceptor annotation should support this case as well.

### Quarkus version or git rev

2.4.1.Final

**Comment by michalszynkiewicz** [comment]
@vladykin Thank you for your report!

A workaround, if you cannot add a scope-defining annotation on the interceptor class, would be to subclass it and add the annotations on the subclass:

```
@ApplicationScoped
@GlobalInterceptor
public class MyLoggingServerInterceptor extends LoggingServerInterceptor {
}
```

**Comment by michalszynkiewicz** [comment]
I took a deeper look into it and it's not trivial to implement. 
Moreover, I believe the workaround above should let users handle all their use cases.
Please let me know if it doesn't work for you.

**Comment by vladykin** [comment]
Thank you, I can use the suggested workaround or put the CDI annotation directly on the LoggingServerInterceptor.
My personal preference is to use producer methods for constructing and configuring beans, but if that's not possible in this case, I can live with that.

**Comment by michalszynkiewicz** [comment]
I understand it's more convenient in some cases, I'm not closing this issue.
What I wanted to say is that, having a work around, and being non-trivial, I don't consider this a high priority feature request.

**Comment by slinkydeveloper** [comment]
I stumbled on this issue and I was wondering, would it be possible to use the `Produces` annotation at least for service scoped interceptors? It would be nice to reuse existing interceptors without wrapping them in new implementations.

**Comment by nahguam** [comment]
I'd just like to add that in some cases it's not as simple as extending the class to allow you to annotate it. Some interceptors may only be accessible via static factory methods, so you'd have to go down the decorator route which can be a lot of needless boilerplate.
