### ISSUE TITLE
RestEasy Reactive Client + byte[] generates invalid classes

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#21375]
### Describe the bug

The following simple interface generates an invalid class file.
```kotlin
@RegisterRestClient(baseUri = "http://example.com")
interface TestAPI {

  @GET
  suspend fun getHTML(): ByteArray

}
```

Any attempt to load the class results in the following error:
```
Request failed: java.lang.ClassFormatError: Illegal class name "byte[]" in class file org/acme/TestAPI$$QuarkusRestClientInterface
```

### Expected behavior

Using Kotlin interfaces with `ByteArray`s results in valid classes.

### Actual behavior

Invalid classes are generated for the Kotlin interface with `ByteArray`s.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7521168/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

Darwin ... 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### Quarkus version or git rev

`2.4.1` and `HEAD` of `main`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by kdubb** [comment]
Discovered the issue happens with Java interfaces that return `Uni<byte[]>` as well.

[code-with-quarkus 2.zip](https://github.com/quarkusio/quarkus/files/7521736/code-with-quarkus.2.zip)

**Comment by geoand** [comment]
cc @michalszynkiewicz
