### ISSUE TITLE
Hibernate Mapping for class in library

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#21379]
### Description

Hi!

I have a library which will be handed over an unwrapped Session from EntityManager, it would be nice if it were possible to expand the mapped Hibernate classes with the the ones in the library, so I could use saveOrUpdate() for the classes in the library.

Best regards,
Viktor

**Comment by Sanne** [comment]
This should be possible already, there are a couple of approaches. Do you just want the entities in this additional jar to be included, or is this other library having a dedicated Quarkus extension?

In the first case it should work by ensuring the 3rd party jar is indexed. See https://quarkus.io/guides/all-config#quarkus-core_quarkus.index-dependency.index-dependency-artifacts-on-the-classpath-that-should-also-be-indexed

In the second case, the other extension can use various extension APIs to automatically enlist additional model items, such as by using `AdditionalJpaModelBuildItem`

**Comment by senzu** [comment]
Thank you very much, I'll look at the indexing solution.
