### ISSUE TITLE
Partial PathParam doesn't work in RESTEasy Reactive 

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#21371]
### Describe the bug

Having an endpoint defined as: 

```java
@Path("/hello")
public class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/a-{extension}")
    public String hello(@PathParam("extension") String extension) {
        return "->" + extension + "<-";
    }
}
```

And if a request is done to http://localhost:8080/hello/a-hoy, a 404 is returned

### Expected behavior

The following should be returned: 

```http
HTTP/1.1 200 OK
Content-Type: text/plain;charset=UTF-8
content-length: 7

->hoy<-
```

### Actual behavior

It returns: 

```http
HTTP/1.1 404 Not Found
Content-Type: application/json
content-length: 0
```

### How to Reproduce?

1. Generate a project with RestEasy Reactive: https://code.quarkus.io/?e=resteasy-reactive&extension-search=reac
2. Add `@Path("/a-{extension}")` and add a `@PathParam`  to the `ReactiveGreetingResource` there
3. Run `mvn clean compile quarkus:dev`
4. Go to http://localhost:8080/hello/a-hoy

### Output of `uname -a` or `ver`

Fedora 35

### Output of `java -version`

JDK 17

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.2

**Comment by maxandersen** [comment]
afaik jaxrs path template syntax states {} placeholders only works between slashes.

**Comment by gastaldi** [comment]
@maxandersen it works with RESTEasy classic: https://github.com/quarkusio/registry.quarkus.io/blob/main/src/main/java/io/quarkus/registry/app/maven/RepositoryMetadataResource.java#L39-L43

**Comment by maxandersen** [comment]
Interesting well then sure :)

**Comment by geoand** [comment]
Let me check

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21380 should take care of it
