### ISSUE TITLE
Use one vertx context for all @ConsumeEvent handlers from one bean

### ISSUE THREAD

**Issue by crionuke** [quarkusio/quarkus#21385]
### Description

Hi, quarkusers!

Docs from vertx.io promises that all code from one verticles executed on the same event-loop, so no more worrying about synchronized and volatile fields.

And same i expected from quarkus, but.

If i will create bean with more that one @ConsumeEvent handlers i get **not** thread-safe construction if handlers will change any common data as ones will be executed within different contexts.

It's little bit missleading. So i guess it can be more handy if all handlers from one bean will be created from one vertx context to change "local" fields with no synchronized. Isn't it?

Piece of not thread-safe code for instance.

```java
@Startup
@ApplicationScoped
public class ServerService extends AbstractVerticle {
    static final Logger LOG = Logger.getLogger(ServerService.class);

    final WebSocketClientTable clientTable;

    ServerService() {
        clientTable = new WebSocketClientTable();
    }

    @ConsumeEvent(value = WebSocketSessionOpenedEvent.TOPIC)
    void handleWebSocketSessionOpenedEvent(final WebSocketSessionOpenedEvent event) {
        Session session = event.getSession();
        Address address = event.getAddress();
        WebSocketClient webSocketClient = new WebSocketClient(session, address);
        // PUT TO MAP
        clientTable.put(webSocketClient);
        vertx.eventBus().publish(ClientConnectedEvent.TOPIC,
                new ClientConnectedEvent(address, webSocketClient.getId()));
        LOG.infof("Client connected, clientId=%s, sessionId=%s",
                webSocketClient.getId(), session.getId());
    }

    @ConsumeEvent(value = WebSocketMessageReceivedEvent.TOPIC)
    void handleWebSocketMessageReceivedEvent(final WebSocketMessageReceivedEvent event) {
        Session session = event.getSession();
        // READ MAP
        if (clientTable.contain(session)) {
            WebSocketClient client = clientTable.get(session);
            Address address = event.getAddress();
            String message = event.getMessage();
            vertx.eventBus().publish(ServerReceivedMessageEvent.TOPIC,
```

**Comment by cescoffier** [comment]
it's a bit more complicated, especially with duplicated contexts, where each message comes with its own context. 

To have such a thread affinity, you need to implement and deploy your own verticle and not use `@ConsumeEvent`.
See https://quarkus.io/guides/vertx-reference#using-verticles learn how to use verticles in Quarkus. 

So, for now, it's better to not implement this behavior.
