### ISSUE TITLE
Build time config options are not reloaded in dev mode

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#2138]
If you have a build time config option (e.g. quarkus.datasource.driver) and you update it in dev mode you will see the updated value in the processor but the value in the template is the old value.

**Comment by gsmet** [comment]
I wonder if it's the same issue as https://github.com/quarkusio/quarkus/issues/2117 .

**Comment by dmlloyd** [comment]
It might be related but it's probably not the same bug. Build time config has a slightly different flow.
