### ISSUE TITLE
Unrecognized configuration key "quarkus.jacoco" warning when starting app

### ISSUE THREAD

**Issue by jdussouillez** [quarkusio/quarkus#21396]
### Describe the bug

I have a warning when running an app with Jacoco enabled.

```
2021-11-12 08:29:21,707 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.jacoco.title" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

Quarkus configuration :

```properties
quarkus.jacoco.title=Test
```

The options exist in the doc and works fine when building the app but a warning is logged when the app starts.

### Expected behavior

No warning

### Actual behavior

A warning is logged when the app starts

### How to Reproduce?

1. Clone the [getting-started project in quickstarts](https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started)
2. Add the Jacoco dependency in the root pom dependencies

```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jacoco</artifactId>
    <scope>test</scope>
</dependency>
```

3. Change the Quarkus version to the latest

```xml
<quarkus.platform.version>2.5.0.CR1</quarkus.platform.version>
```

4. Add the Jacoco configuration in the `application.properties` file

```properties
quarkus.jacoco.title=Test
```

4. Run the app with `mvn quarkus:dev`

**All these steps are done in this project : [getting-started-v2.zip](https://github.com/quarkusio/quarkus/files/7526207/getting-started-v2.zip)**

### Output of `uname -a` or `ver`

```
Linux frpo245 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`

```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)
```

### Quarkus version or git rev

```
2.5.0-CR1
```

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/junior/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 17, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-90-generic", arch: "amd64", family: "unix"
```

### Additional information

This is not blocking, the Jacoco report works fine, the app runs fine, but the warning seems to be a false positive.

**Comment by geoand** [comment]
Where did you find `quarkus.jacoco=true`? I don't see it anywhere

**Comment by jdussouillez** [comment]
I messed up with the project to reproduce it, sorry!

Actually, the `quarkus.jacoco` must be removed. And when I run `mvn quarkus:dev` I get the warning on the `quarkus.jacoco.title` property when running `mvn quarkus:dev` :

```
2021-11-12 10:02:52,777 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.jacoco.title" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by geoand** [comment]
Understood, thanks.

This behavior is actually expected. You can avoid it by prefixing the jacoco configuration values with `%test.`, so something like `%test.quarkus.jacoco.title`
