### ISSUE TITLE
Configurable base path for Qute templates

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#21393]
### Description

"templates" (resolving to `src/(main|test)/resources/templates`) seems to be hard-coded here: https://github.com/quarkusio/quarkus/blob/2.4.1.Final/extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java#L1186

This is a bit inflexible if you have a project/module that has different kinds of templates that you want to separate from each other, e.g:
```
src/main/resources/
  html-templates
  pdf-templates
```

It would be nice to configure the base path (or even configure multiple ones?).

**Comment by famod** [comment]
I just realized that there is `@CheckedTemplate.basePath`, but this is actually the part _after_ the "root" base path so to say (and this not available for "unchecked" templates, AFAICS).

**Comment by mkouba** [comment]
> This is a bit inflexible if you have a project/module that has different kinds of templates that you want to separate from each other, e.g:

Well, you can use `src/main/resources/templates/html` and `src/main/resources/templates/pdf`. It not flexible but it was good enough so far ;-)

> It would be nice to configure the base path (or even configure multiple ones?).

We can do this but I'm not really sure it's worth the effort...

> I just realized that there is @CheckedTemplate.basePath, but this is actually the part...

Yes, the `CheckedTemplate#basePath()` is relative to the templates root, i.e. relative to `src/main/resources/templates`.

**Comment by mkouba** [comment]
A problem I see with this enhancement is that other dependencies/extensions would not be able to contribute a template to your application. Or we would have to use a different base for dependencies/extensions and for your app. Which is not very nice.

Feel free to reopen this issue if you really think it's a fundamental feature we should add or if you have more questions/comments.
