### ISSUE TITLE
Qualifier on alternative bean - duplicate element error

### ISSUE THREAD

**Issue by joachimglink** [quarkusio/quarkus#21401]
### Describe the bug

I have a bean with annotations:

`@ApplicationScoped
@MyQualifier("some-value")
public class MyBean { .. }`

In the tests I have an alternative bean for it with following annotations:

`@ApplicationScoped
@MyQualifier("some-value")
@Alternative
@Priority(5)
public class TestMyBean extends MyBean { .. }`

When running the tests, an IllegalArgumentException happens with:
_duplicate element @MyQualifier("some-value")_

When I remove the qualifier from the alternative it works as expected.

### Expected behavior

I would expect that the Qualifier annotation can be defined on the alternative bean as it was prior to Quarkus 2.3
(Likely, the change was introduced with https://github.com/quarkusio/quarkus/pull/19759)

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS

### Quarkus version or git rev

2.4.1.Final

**Comment by mkouba** [comment]
> When running the tests, an IllegalArgumentException happens with:
> _duplicate element @MyQualifier("some-value")_

@joachimglink What's the actual stack trace? Did you try quarkus 2.6.1? I've tried to modify one of our tests and although the impl is suboptimal (the `Bean` metadata returns two qualifier instances) no exception is thrown...

**Comment by joachimglink** [comment]
The exception is this:
`java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to initialize Arc
Caused by: java.lang.IllegalArgumentException: duplicate element: @MyQualifier(value="some-value")
`

But it seems that the issue is already resolved with Quarkus 2.5.x
(I can reproduce it with 2.4.1.Final but no longer with 2.5.1.Final)

**Comment by mkouba** [comment]
> But it seems that the issue is already resolved with Quarkus 2.5.x

Yes, the IAE comes from the `java.util.Set#of()` method and it was fixed in https://github.com/quarkusio/quarkus/pull/21232 in 2.4.2.Final.

**Comment by mkouba** [comment]
However, we still need to fix the `BeanInfo` so that the qualifier annotation from the supertype is completely ignored.

**Comment by joachimglink** [comment]
Why should the qualifier from the supertype be ignored? 
I´d expect that the qualifier on the supertype is still recognized if the qualifier is marked with @Inherited.

**Comment by mkouba** [comment]
> Why should the qualifier from the supertype be ignored? I´d expect that the qualifier on the supertype is still recognized if the qualifier is marked with @inherited.

I mean it should be ignored if the subtype declares an annotation of the same type... as defined by the CDI spec.
