### ISSUE TITLE
Support setting locale and charset for "default" Qute `Variant`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#21405]
### Description

If I do _not_ want to set the `Variant` [for each `TemplateInstance`](https://quarkus.io/guides/qute-reference#template-variants) then the only way I could find to set it seems to be via `TemplateLocator`.
But usually I'm fine with how and from where templates are loaded, so implementing a `TemplateLocator` for this seems like overkill.

So it would be nice to have some way to configure which locale (and charset) is used.

### Implementation ideas

Maybe extend (and rename?) `quarkus.qute.content-types` so that you can also specify locale and encoding?

Or just introduce `quarkus.qute.locale` and `.encoding`?

**Comment by mkouba** [comment]
Yes, there's even a TODO in the code :D
https://github.com/quarkusio/quarkus/blob/main/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/EngineProducer.java#L233-L236 

> Maybe extend (and rename?) quarkus.qute.content-types so that you can also specify locale and encoding?

We could start with `quarkus.qute.default-locale` and `quarkus.qute.default-encoding`. Although for encoding I'd encourage users to stay with the default - UTF-8.

**Comment by gsmet** [comment]
@mkouba probably useful to have a look at `LocalesBuildTimeConfig`.
