### ISSUE TITLE
Add support for JMS

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2140]
The use case as discussed with a user is:

- help app migration
- strong Tx guarantees needed (the most important) 
- MDB style consumption

So the API can be a bit different but the transaction guarantees are important.

**Comment by emmanuelbernard** [comment]
CC @cescoffier for input

**Comment by kenfinnigan** [comment]
Just a cautionary tale, as we had similar requirements with Thorntail as well.

If an extension is added purely for assisting migration from other frameworks, developers are never going to migrate off that extension.

**Comment by gnieser** [comment]
Hello,

Not only for migration, I can think of several use cases where microservices do need JMS connectivity, 

For example many systems in financial sector rely on JMS brokers. I would really love to use quarkus for microservices interacting with those systems. Improving performance and scalability of said microservices would be hugely beneficial.

Kind regards!

**Comment by cescoffier** [comment]
MDB style consumption can be handled by Reactive Messaging:

```
@Incoming("my-jms-topic")
public void consume(String m) {
   // ...
}
```

The main issue is Tx, as reactive messaging does not handle transactions. 

It might be possible to bind "transaction" to the Reactive Messaging acknowledgment, and so commit//rollback the TX when the message processing succeeds or fails

**Comment by cescoffier** [comment]
Also note that unlike "default" JMS, the level of concurrency would be 1.

**Comment by gsmet** [comment]
We have some JMS support with the `artemis-jms` extension.
