### ISSUE TITLE
oidc-client: grant.type=password additional grant options are not supported

### ISSUE THREAD

**Issue by ThomasKriechbaum** [quarkusio/quarkus#21415]
### Description

I have just started playing around with quarkus-oidc-client to obtain tokens form our Ping-Identity server.

In case of quarkus.oidc-client.grant.type=password additional grant options are not supported as only password.username and password.password are considered while initializing the tokenGrantParams (see https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L154)

Our Ping Identity server requires an additional grant option (password.validator_id).

### Implementation ideas

in application.properties
```
quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=xxx
quarkus.oidc-client.grant-options.password.password=yyy
quarkus.oidc-client.grant-options.password.validator_id=validator_required_by_ping_identity
```

in [OidcClientRecorder](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L161)

```
Map<String, String> filtered = grantOptions.entrySet()
                .stream().filter(e -> !(OidcConstants.PASSWORD_GRANT_PASSWORD.equals(e.getKey()) || OidcConstants.PASSWORD_GRANT_PASSWORD.equals(e.getKey())))
                        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

tokenGrantParams.addAll(filtered);

```
I dont know, if this has any impact on the required entry ordering
see [OidcClientRecorder Comments]( https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L155)

**Comment by sberyozkin** [comment]
@ThomasKriechbaum Thanks for marking it as enhancement - but it is a bug - I updated the docs yesterday claiming the password grant can also be customized :-)

**Comment by ThomasKriechbaum** [comment]
@sberyozkin if it's ok for you I'll do further testing with Ping Identity - as for password grant it has some specific behaviour - but I'll check it with some colleagues before
