### ISSUE TITLE
Support kotlin coroutines in quarkus-scheduler

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#21428]
### Description
`quarkus-scheduler` does not support suspend functions. 

In the past i bridged the gap with custom code, but i think it should be supported by quarkus.

I had this requirement multiple times. 

```kotlin
@ApplicationScoped
class SomeBean {

    @Scheduled(every="10s")     
    suspend fun doSomething() {
        // ...
    }
}
```

**Comment by mschorsch** [comment]
@geoand 😃

**Comment by geoand** [comment]
Interesting idea!

**Comment by mkouba** [comment]
Hm, what's the point of turning a scheduled method into a coroutine? I mean it's not called directly from a user code and it's always executed on the main executor for blocking tasks. But I'm probably missing something here...

**Comment by geoand** [comment]
I assume so users can use coroutine enabled APIs

**Comment by mschorsch** [comment]
> I assume so users can use coroutine enabled APIs

That's the point. 

With this change other suspend functions can be called directly.

**Comment by mkouba** [comment]
Ok, contributions are welcome. I have no idea what needs to be implemented ;-).

**Comment by evanchooly** [comment]
I'm not convinced the complexity is worth it.  It's trivially simple to launch subsequent suspend functions via `runBlocking` or `launch`.  Given the asynchronous out-of band execution of the functions it feels like time could be better spent on more user facing concerns.

**Comment by evanchooly** [comment]
Has anything come of this?  what's the problem with using `runBlocking {}` inside your scheduled task?

**Comment by mschorsch** [comment]
runBlocking blocks the underlying thread. 

If i make for example an API call inside a scheduled method, the underlying thread is blocked as long as the API call takes.

**Comment by evanchooly** [comment]
`launch {}` doesn't however

**Comment by mschorsch** [comment]
Do you mean GlobalScope.launch? This isn't a good option because of:
> It is easy to accidentally create resource or memory leaks when GlobalScope is used. A coroutine launched in GlobalScope is not subject to the principle of structured concurrency, so if it hangs or gets delayed due to a problem (e.g. due to a slow network), it will stay working and consuming resources. 

 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/

I've written some glue code using a custom coroutine scope but i think it would be best if Quarkus would manage the ApplicationCoroutineScope in the same manner as in resteasy reactive.

**Comment by geoand** [comment]
This can definitely be done the proper way (like we have done in RESTEasy Reactive, but it's pretty low on our priority list...

**Comment by mschorsch** [comment]
@geoand @mkouba Thanks

**Comment by geoand** [comment]
🎉

**Comment by andreas-eberle** [comment]
@geoand : When will this be released? Could it make it to 2.8.1?

**Comment by geoand** [comment]
It will be part of Quarkus 2.9

**Comment by andreas-eberle** [comment]
Is there a planned release date for 2.9 already? 2.8 just came out and we cannot upgrade since 2.7.3 since we get into trouble with Hibernate Reactive...

**Comment by geoand** [comment]
CR1 should be end of April if all goes well

**Comment by JamshedAlamQaderi** [comment]
Can anyone tell me how to use `@Scheduled` with kotlin coroutine?

**Comment by geoand** [comment]
Just annotate a public suspend function with `@Suspend`

**Comment by JamshedAlamQaderi** [comment]
@geoand thanks for your help. Can you provide me the actual package for `@Suspend`

**Comment by geoand** [comment]
Sorry, I meant `@Scheduled`

**Comment by JamshedAlamQaderi** [comment]
I am using `io.quarkus:quarkus-scheduler`. Is that okay for coroutine?

**Comment by geoand** [comment]
Yes
