### ISSUE TITLE
support Event Bus Custom Exception Handler

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#21424]
### Description

it didn't support custom exception handler now  in `io.quarkus.vertx.core.runtime.VertxCoreRecorder` of depency `quarkus-vertx`,as below.
can it support custom exception handler?
![image](https://user-images.githubusercontent.com/25682169/141645903-2e3e982c-b281-458e-ac47-a8d47662fbd3.png)

### Implementation ideas

For example, use a default bean that can be covered in code or extension instead of the exception handler.

**Comment by cescoffier** [comment]
The exception handler you register on vertx is more than just for the event bus. It's catching every exception thrown the event loop. While it can be a good idea to allows the customization, for the event bus, I would recommend to use request/reply and handle failure.

**Comment by krakzk** [comment]
Is there any example or blogs related to using the request reply for handling VertX custom exception ? @cescoffier
