### ISSUE TITLE
Update to Vert.x 4.2.x or Vert.x 4.3.0

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21429]
### Description

Before Quarkus 2.6, we should update to the latest Vert.x version available at that time. 
At the moment, Quarkus uses Vert.x 4.2.1. We can continue using Vert.x 4.2.x or switch to Vert.x 4.3 is needed.

This epic references the issue that is related to Vert.x and that should be fixed with an update to the chosen version.

### Issues

_No issues at the moment_

CC @tsegismont @vietj @pmlopes

**Comment by gsmet** [comment]
Talking about 2.6 so closing.
