### ISSUE TITLE
Docs - mvn commands examples on Windows

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2142]
In Quarkus docs (e.g. https://quarkus.io/guides/getting-started-guide) there are multi-line example mvn commands.

These commands work fine on macOS and Linux. But on Windows there is trouble that `\` is not valid way. For cmd the magic character is "^" and for PowerShell it's "`" - info taken from https://stackoverflow.com/questions/605686/windows-how-to-specify-multiline-command-on-command-prompt

Should the docs have: 

a) Windows variants
b) Note about the limitation
c) Nothing extra for Windows 

?

Example of the command:
```
mvn io.quarkus:quarkus-maven-plugin:0.13.3:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

**Comment by gsmet** [comment]
Nobody reported it as an issue so I suppose they were able to translate the examples.
