### ISSUE TITLE
Qute should not try to parse files not having the configured suffixes

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#21420]
### Description

I'm currently migrating a Qute setup that is based on manual template loading to the `@CheckedTemplate` approach.
During that migration, I got this build error because there was an image in `templates/images/my-image.jpg`:
```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: io.quarkus.qute.TemplateException: Parser error in template [images/my-image.png] on line 15: unexpected non-text buffer at the end of the template - unexpected state [CDATA]: ���^�U�
```

I don't think Qute should parse anything _not_ matching the configured suffixes because it may make sense to place images under `templates` (which is a very common name and there might be other template files that are not for Qute in this directory).

### Implementation ideas

Apply `quarkus.qute.suffixes` as an include filter.

**Comment by mkouba** [comment]
I don't think that the `templates` dir is a good place for static files. See also [Serving Static Resources](https://quarkus.io/guides/http-reference#serving-static-resources). In any case, you can exclude any file in quarkus 2.5+ via [`quarkus.qute.template-path-exclude`](https://quarkus.io/version/main/guides/qute-reference#quarkus-qute_quarkus.qute.template-path-exclude).

**Comment by famod** [comment]
In my case it's not about serving static resources, it's about generating emails from xhtml templates. In those emails we have to embed images. So there is a strong correlation, hence placing the respective files in close proximity does make sense for us. YMMV!

But very nice that there's an exclude in 2.5!
It might just feel a little verbose when you just want xhtml and nothing else, because you'd set that via `suffixes` _and_ probably set something like `^(?!.*\.xhtml)$` for `exclude`.

Having said that, given that this exclusion property was added already, I'm ok with that solution.

**Comment by mkouba** [comment]
> In my case it's not about serving static resources, it's about generating emails from xhtml templates.

Ok, in that case it might make sense. The thing is that `quarkus.qute.suffixes` does not prevent you from using any suffix/pattern in your app; it's merely a hint that is used by the locator so that you don't need to use the suffix for injection points.

> It might just feel a little verbose...

Yes, it's a bit verbose, on the other hand it's not a common use case...

> Having said that, given that this exclusion property was added already, I'm ok with that solution.

+1
