### ISSUE TITLE
Micrometer extension allow to change root-path

### ISSUE THREAD

**Issue by Raffaello** [quarkusio/quarkus#21425]
### Description

like for example `quarkus.smallrye-health.root-path`
having a similar option for eg: `quarkus.micrometer.root-path`
or similar

to allow to define a different url from `/q/metrics` (in this case for the `/q` part)

### Implementation ideas

it should be enough to add that config property to the "root-path" to have the overriden option for the `/q`

**Comment by Raffaello** [comment]
actually the `quarkus.micrometer.export.prometheus.path` can do that already. 
the documentation led me think differently as it reports the default is `/metrics`

> 
> 
> quarkus.micrometer.export.prometheus.pathThe path for the prometheus metrics endpoint (produces text/plain). The default value is metrics. | string | metrics
> -- | -- | --
> 
> 

when instead the deafult path is `/q/metrics`

**Comment by ebullient** [comment]
The documentation is correct. The default value is the relative "metrics" value, which is resolved relative to the "non-application" endpoint root ("q"), which in turn is resolved relative to the http root path.

Using absolute paths (leading slash) for any of these values will remove them from relative path resolution.

This change was originally noted here:
https://quarkus.io/blog/path-resolution-in-quarkus/

I thought I'd included a cross-link in the docs to the configuration root behavior, but here it is: 

https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.non-application-root-path

Note that the automatic redirect behavior introduced in 1.11 has been removed in 2.x.

**Comment by ebullient** [comment]
Would this be clearer? 

```
The path for the prometheus metrics endpoint (produces text/plain).
The default value is {@code metrics} and is resolved relative to the non-application endpoint ({@code q}), e.g. `${quarkus.http.root-path}/${quarkus.http.non-application-root-path}/metrics`. If an absolute path is specified (`/metrics`), the prometheus endpoint will be served from the configured path.
```

**Comment by Raffaello** [comment]
yes. 
Thanks.
