### ISSUE TITLE
Improve @Blocking support when multiple extension handles this annotation

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21431]
### Description

At the moment, when a method or a class uses several extensions handling @Blocking, it may result in two consecutive dispatchings on worker threads. It introduces a performance penalty that should be avoided. 

This issue is particularly visible when using Fault Tolerance annotations.

**Comment by Ladicek** [comment]
Note to self: this probably could be handled by manipulating the Fault Tolerance annotation model (which is constructed at build time in Quarkus). If the Quarkus SmallRye Fault Tolerance extension can determine that a method has `@Blocking` && is subject to Fault Tolerance && something else will offload to another thread, then the extension can replace the `@Blocking` annotation with `@Nonblocking` _for the purpose of Fault Tolerance_ (that is, in the Fault Tolerance annotation model).

The question is, how to determine if something else will do the thread offload.

**Comment by Ladicek** [comment]
Over time, I grew convinced that the `@Blocking` / `@NonBlocking` annotations should be reserved for methods invoked by some kind of a container, and they should never be used on methods that are supposed to be called by user code. That naturally avoids the problem described in this issue.

From SmallRye Fault Tolerance perspective, that would however be a pretty big breaking change. I'll keep pondering this mess I built :-)

**Comment by Ladicek** [comment]
I believe SmallRye Fault Tolerance 5.6.0 (and 6.1.0) address this in the best way possible:

- usage of `@Blocking` and `@NonBlocking` is deprecated _for fault tolerance purposes_ (and support for them will be removed in SmallRye Fault Tolerance 7.0.0)
- it is recommended to use `@Asynchronous` to mark blocking methods for thread offload
- it is recommended to use non-compatible mode (default in Quarkus), where non-blocking methods don't need any extra annotation
- in the fully compatible mode (default elsewhere), non-blocking asynchronous methods should be annotated `@AsynchronousNonBlocking`
