### ISSUE TITLE
Handling @Blocking / @NonBlocking  in GraphQL APIs

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21433]
### Description

When implementing GraphQL APIs, the `@Blocking` and `@NonBlocking` annotation should be supported as well as the default dispatching rules. 

As a verification, it should be possible to implement a GraphQL Query method using:

* Panache  (Blocking)
* PAnache Reactive (Non-Blocking)

**Comment by gsmet** [comment]
Just posting here to make sure this one is not forgotten: https://github.com/quarkusio/quarkus/issues/21111 .

**Comment by phillip-kruger** [comment]
Thanks. I am busy looking at both

**Comment by phillip-kruger** [comment]
This is now added and will be available in 2.10.

Closing here
