### ISSUE TITLE
Add Cloud Event support to the AMQP connector

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21435]
### Description

This epic is about adding support for Cloud Events to the AMQP connector. At the moment only the Kafka connector supports Cloud Events.

**Comment by cescoffier** [comment]
Fixed as Reactive Messaging 1.12.1 has been integrated.

**Comment by paulrobinson** [comment]
@cescoffier do you have a link to the PR where "Reactive Messaging 1.12.1 has been integrated"?

I'm confused as I see smallrye-reactive-messaging is all the way up to 3.15.0: https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L54

**Comment by cescoffier** [comment]
It was in 3.12, not 1.something.
