### ISSUE TITLE
Improving GraphQL subscriptions support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21434]
### Description

The current GraphQL subscription supports should be improved to allow producing a `Multi` in which the notifications can transit.
This epic is about adding this feature and making sure it works correctly. 

As a validation, having a quickstart broadcasting the notifications to a web socket would be great. 
Another possibility would be to emit the notifications as Kafka records.

**Comment by phillip-kruger** [comment]
Done
