### ISSUE TITLE
Integrate the Reactive Oracle SQL Client

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21432]
### Description
Vert.x 4.2 ships the first version of the Vert.x Oracle client. 
This client should be included in Quarkus. This includes:

* Having a Quarkus extension
* Verifying the native build (and adding the required substitutions)
* Ensure basic support in Hibernate Reactive

**Comment by indiealexh** [comment]
This is the last big feature I am missing to do everything I need to do. So if I can help in anyway, I'm down to help.

**Comment by cescoffier** [comment]
@indiealexh the reactive client is almost ready. Then it's just the quarkus extension.

**Comment by cescoffier** [comment]
Closing as @tsegismont has done all the work (and a BIG thank you for that @tsegismont !)
