### ISSUE TITLE
Integrate Mutiny 1.3

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21430]
### Description

This epic is about the integration of Mutiny 1.2.x which should provide:

* Multi _onNoItem_ support
* New Context support
* Replay last n items in Multi (see open RFE at https://github.com/smallrye/smallrye-mutiny/issues/536)
* Review current deprecated and experimental APIs

The performance level is good, but there are areas for throughput/allocation wins, especially in transformTo{Uni,Multi} (aka flatMap and concatMap)

**Comment by geoand** [comment]
Should this be closed now that https://github.com/quarkusio/quarkus/pull/21799 is in or is this ticket meant to address code changes in the codebase as well?

**Comment by jponge** [comment]
Many items have been postponed to 1.3 https://github.com/smallrye/smallrye-mutiny/milestone/46

**Comment by geoand** [comment]
Thanks for the update

**Comment by jponge** [comment]
Mutiny 1.3.0 got merged into Quarkus (see #22825)
