### ISSUE TITLE
Allows consuming SSE endpoint as Multi using the Reactive REST Client

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21441]
### Description

Allows consuming SSE endpoint as Multi using the Reactive REST Client.
If the server produces an SSE response, it should be able to stream the items in a Multi. The item type can be recreated from JSON (from the data part). Additionally, a type including the other metadata could be defined.

**Comment by michalszynkiewicz** [comment]
I think it's already handled, I didn't remember about it when I first saw this issue :)

See:
https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive-jackson/deployment/src/test/java/io/quarkus/rest/client/reactive/jackson/test/MultiSseTest.java
