### ISSUE TITLE
Extend the Dev UI to list and use the REST Clients

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21444]
### Description

Extend the Dev UI to:

* list the REST Client that are defined in the application
* allows invoking the method to verify the result (a la Swagger)

**Comment by michalszynkiewicz** [comment]
I assume invoking is for CDI-registered clients only, programmatic ones have no configuration in the MP Config.

I'll see if I can include the ones that have no CDI beans in the list too

**Comment by michalszynkiewicz** [comment]
Initial take on it. Clicking on the client class opens it in the IDE:
![image](https://user-images.githubusercontent.com/3901322/142594831-8182ce69-016e-4d0d-a7bb-1ea9a1e5eb53.png)

**Comment by michalszynkiewicz** [comment]
we can further add:
- listing classes that might be interfaces but contain some problems, with the problems we found
- invoking the client (as the issue description mentions) - @cescoffier could you explain a bit what use case did you mean for this?

**Comment by cescoffier** [comment]
Invoking the client is like "swagger" for clients. For each method from the client, it should provide a way to invoke it (with params, headers...) and get the response. That would ease the debugging a lot. Bonus point: provide the curl equivalent command.

**Comment by michalszynkiewicz** [comment]
Response in a format a user would get? 
Or the original response of the server?

**Comment by cescoffier** [comment]
I would do the Http response. It generally what interests us (especially, when it's not what we are expecting, like we were expecting a 200 with some JSON and we get a 500 with a stack trace)

**Comment by geoand** [comment]
I don't think that the `invoking` the clients will work correctly. There are too many things that could go wrong during deserialization of the method arguments and serialization of the result to make it useful.

**Comment by cescoffier** [comment]
We do something similar for gRPC, I was thinking we could "copy" the idea.

**Comment by geoand** [comment]
I'll have a look

**Comment by geoand** [comment]
The way it's implemented for gRPC seems very gRPC specific and I mean that in a good way as it seems to avoid the marshalling / unmarshalling problems we would have if we try to replicate this for the REST Client.
I am afraid that if we do something similar for the REST Client, Jackson (or Jsonb) configuration could lead to hard to diagnose issues

**Comment by cescoffier** [comment]
Too bad 😟

Thanks for looking into this. Should we close the issue?

**Comment by geoand** [comment]
You are welcome 

Yeah, I'd prefer we close.
