### ISSUE TITLE
JAX-RS like gRPC experience

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21445]
### Description

Java-first gRPC - provide JAX-RS-like experience for implementing gRPC endpoints:

* Support various marshallers (including Protobuf and in that case, it can generate the protobuf file )
* Allows implementing partial services

**Comment by geoand** [comment]
If this is something we want to do, I can definitely help out (due to my JAX-RS experience, my gRPC experience is 0️⃣ )

**Comment by michalszynkiewicz** [comment]
It is, I'll ping you when I start looking into this.

**Comment by michalszynkiewicz** [comment]
Some thoughts on how I imagine it, to kickstart the discussion.

In the first iteration, I think e should focus on protocol buffers, and v3 version of proto.

A service definition could look as follows:
```java
    // grpc package = java package by default
    // different @GrpcService annotation? Or reuse the current one - but some attributes make no sense for the old way
    //
    @GrpcService(grpcName = "MyServiceName", grpcPackage = "com.mypackage", options = {@GrpcOption(name = "idempotency_level", value = "IDEMPOTENT")})
    public static class MyService {
        // streaming method:
        @GrpcMethod
        Multi<Out> foo(Multi<In> input) {

        }

        @GrpcMethod(name = "Foo_2") // override for the grpc method name
        Out foo2(Multi<In> input) { // blocking client-side streaming

        }

        Uni<Out> foo3(Multi<In> input) {

        }
        // and so on
    }
```

message/pojo definition - here a tricky thing is the package, if we want to have a single proto file, we probably need a single package for service and messages:
```java
    @GrpcMessage(grpcPackage = "com.mypackage", grpcName = "InMessage")
    public static class In {
        // grpc field annotation optional but a warning about backward and forward compatibility printed if it's not there
        @GrpcField(id = 1)
        String name;
    }


      public static class Out {
        // maybe value instead of id?
        @GrpcField(id = 1, type = "int32")
        Integer id;
        @GrpcField(id = 2)
        String name;
    }
```

CC @geoand @cescoffier @mkouba

**Comment by mkouba** [comment]
Hm, isn't this a bit against the core idea of gRPC which is contract-first? I do remember a similar approach in Java EE web services and IIRC the result was a bit unconvincing...

**Comment by michalszynkiewicz** [comment]
> Hm, isn't this a bit against the core idea of gRPC which is contract-first? I do remember a similar approach in Java EE web services and IIRC the result was a bit unconvincing...

It is a bit, yes. 
OTOH, gives a chance to get the benefits of gRPC for people who would rather start from Java.

**Comment by mkouba** [comment]
I think that one of the big pain points is that you can't easily switch between these two approaches when needed. And it's a lot of new annotations ;-).

**Comment by michalszynkiewicz** [comment]
CC @phillip-kruger AFAIR, you were interested in this too

**Comment by phillip-kruger** [comment]
Yes!

**Comment by hutchig** [comment]
@starksm64 the repo is now there but empty:
https://github.com/eclipse-ee4j/rpc
Also:
https://www.youtube.com/watch?v=erpFfXIb99Q
https://www.eclipsecon.org/sites/default/files/slides/Jakarta%20RPC.pdf
https://github.com/aseovic/jakarta-grpc-example
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24188#attach_30538
https://projects.eclipse.org/comment/1406
https://projects.eclipse.org/comment/1406#comment-1406
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/111
https://www.eclipse.org/lists/jakarta.ee-spec/msg02129.html
https://github.com/jakartaee/specifications/pull/446
https://projects.eclipse.org/proposals/jakarta-rpc
https://deploy-preview-446--jakartaee-specifications.netlify.app/specifications/rpc/
https://github.com/jakartaee/specifications/commit/d6b79db053e076d58839b9c8610c51053eeb7e9c (edited)

**Comment by cescoffier** [comment]
Closing in favor of #34183.
