### ISSUE TITLE
Allows consuming a JSON Array as Multi using the Reactive REST Client

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21442]
### Description

Allows consuming a JSON Array as Multi. If the service returns a large JSON Array, the consumer could process the item one by one. Each item would be re-created from the JSON objects. This approach would avoid having to accumulate the JSON Array in memory before starting the processing.

**Comment by michalszynkiewicz** [comment]
@cescoffier since we have json streaming, and with the linked PR it can be read as Multi, do we still want this?

**Comment by cescoffier** [comment]
No, that should be enough.

**Comment by mueihn** [comment]
I'd still be highly interested in what the original poster requested.

Also, it sounds a bit inconsistent to me as it is:

Suppose that REST server and REST client are both implemented in quarkus.

On the server side, we have a method for a given endpoint (producing application/json) that returns Multi<MyClass>. This means, the actual REST endpoint returns a JSON array of JSON objects.

On the client side, which consumes the endpoint, however, we are not allowed to have Multi<MyClass> as that seemingly results in quarkus trying to parse the whole array of JSON objects into a single instance of MyClass. So far, the only solution to me seems to be using List<MyClass> on the client side instead.
