### ISSUE TITLE
Configuring query parameter from configuration using the Reactive REST Client

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21443]
### Description
This epic is about configuring per-class and per-method query parameters, with an annotation.
Values may come from the configuration.

**Comment by michalszynkiewicz** [comment]
We could introduce a `@ClientQueryParam` annotation for it.
Something like:
```java
public @interface ClientQueryParam {
    String name();
    String value();
    boolean required() default false;
}
```

There's a chance we could reuse HeaderFiller for it.

**Comment by michalszynkiewicz** [comment]
CC @Sgitario

**Comment by geoand** [comment]
Not sure I get this. Can someone give an example of what we are looking for?

**Comment by cescoffier** [comment]
Yhe idea as far as I understand is to annotate a REST client method with the `ClientQueryParam` to add the specified params as query parameters to the call.  We have the same kind of feature for headers, but not for query parameters.

**Comment by geoand** [comment]
Okay cool, I'll add it.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/29277 brings in this future
