### ISSUE TITLE
Quarkus quartz should not reschedule jobs on start

### ISSUE THREAD

**Issue by apat59** [quarkusio/quarkus#21455]
### Describe the bug

Bug introduced by https://github.com/quarkusio/quarkus/issues/20538

Anytime quarkus starts it will reschedule jobs, not matter if the job config changed or not.
It's a tough decision, at best it should only detect changes and WARN, nothing else.
This can have serious collateral damages depending on what your jobs are doing.

If you are cleaning up your data once a year, you don't want that to be re initialized and triggered every time you restart the app or scale up your cluster.

### Expected behavior

Do not reschedule jobs, WARN or maybe improve the dev tools but this is too dangerous.

### Actual behavior

All jobs are rescheduled on start.

### How to Reproduce?

Pick any quartz based clustered app.
Create a job running every 5 sec for example.

Request the db for
select * from qrtz_simple_triggers and select * from qrtz_triggers

Restart the app and check the table again.
All triggers, executions are reset, ignoring past execution and, most important, the expected and persistent next_fire_time on qrtz_triggers.

### Output of `uname -a` or `ver`

no impact

### Output of `java -version`

no impact

### Quarkus version or git rev

since 2.3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

no impact

**Comment by apat59** [comment]
basically https://github.com/quarkusio/quarkus/pull/20546 should be reverted.
Damages are done by
`                        } else {
                            scheduler.rescheduleJob(trigger.getKey(), trigger);
                            LOGGER.debugf("Rescheduled business method %s with config %s", method.getMethodDescription(),
                                    scheduled);
                        }`

As I said, it's tricky. The root question being "how can we handle job config updates?" 
And even more complex "what if a developer changes the job id or simply removes the annotation?" 

There is no solution, at some point the developer will have to update the quartz tables or implement his own job and trigger management service and perfectly know what he is doing and document his job inventory. 
I don't see any safe way for quarkus to handle this auto-magically.

**Comment by coiouhkc** [comment]
Hi @apat59, from my point of view current default behaviour is fine, but i could see why you want it to be configurable.
Still my understanding of quarkus philosophy is, that it tries to provide the most meaningful defaults, and updating the schedules by default seems reasonable.

**Comment by apat59** [comment]
This might be a "very handy" behavior in dev profile and that is still debatable but that is not the most meaningful defaults.
That is comparable to the create-drop schema in hibernate, very handy but very dangerous in production.

Again, you use persistent job config, required when running in a cluster. 

If your app requires to scale up, meaning more pods, meaning every single pod will trigger scheduler.reschedule, I think it is dangerous to delete the jobs and recreates them (which is what scheduler.reschedule does) and fully ignore past trigger and scheduled "next execution".
Same happens if your apps crashes and you must restart it.

At the end, this behavior is pretty close to the non-cluster setup.

**Comment by coiouhkc** [comment]
On the other hand, whenever making changes to `@Scheduled` parameters (either directly or via application.properties or ENV) and publishing a new image version to the stream, i expect the changes to take effect - similar as in case with other annotations.
I might understand your point regarding `scheduler#reschedule` but then it's not a bug in quarkus but rather some implementation specific of quartz itself.

**Comment by apat59** [comment]
AFAIU this is the expected behavior, the javadoc states "Remove (delete) the Trigger with the given key, and store the new given one". It is not taking the responsibility to compare the old and new trigger.

I'd rather go deeper in the job config parsing 
- if job config is the same: do nothing
- if job config is different AND a global quarkus properties is set, then reschedule
- log WARN otherwise

But still, what happens if you simply remove the annotation? meaning you don't want that job anymore? Quarkus won't delete the db records for you, one will have to handle this manually.
Same if you change the job id.

**Comment by coiouhkc** [comment]
> But still, what happens if you simply remove the annotation? meaning you don't want that job anymore? Quarkus won't delete the db records for you, one will have to handle this manually.
> Same if you change the job id.
Makes sense, but i don't think it would have worked prior to #20546. From what i can take from your examples and your suggestion the refactoring done in #20546 should be continued but not reverted...

**Comment by apat59** [comment]
Meanwhile we have 3 critical apps stuck in prod with quarkus 2.3.0 because it would be a killer to reschedule all our jobs.
And I feel very lucky we detected this early in dev before deploying our last release.

I think this deserves a deeper analysis / design since it can quickly become even more complex than it seems.
The 'new' behavior is not even documented in the guide and I fear many apps will discover this in prod :(

**Comment by coiouhkc** [comment]
We have 20+ critical apps in prod where we need the new beahviour ;) But it's not about us, rather about Quarkus.

> I think this deserves a deeper analysis / design since it can quickly become even more complex than it seems.

Aggreed, let's wait for @machi1990 and @mkouba and try to bring both interests together.

**Comment by apat59** [comment]
@coiouhkc btw https://github.com/quarkusio/quarkus/issues/14671#issuecomment-770180851
We hit the same concern as you really quickly, on version 1.11.

I don't think it's impossible to handle it but it really is a complex topic.

**Comment by machi1990** [comment]
Thank you for the discussion @apat59 @coiouhkc and for raising the issue @apat59 

Personally I do not think that rescheduling the job is an issue. The issue here is that once the job was rescheduled, all the previous state especially the next fire time is not preserved since the new trigger is set to fire immediately or after a certain delay if this was configured with the `@Scheduled` annotation. I think of the following possible solutions to cater for both cases:
1. When rescheduling the job, the new trigger start time will be set to the next fire time of the old trigger. The snippet for that may look like
```java
org.quartz.Trigger oldTrigger = scheduler.getTrigger(trigger.getKey());
scheduler.rescheduleJob(trigger.getKey(),triggerBuilder.startAt(oldTrigger.getNextFireTime()).build());
```
The advantage of this approach is that no API change is required. The disadvantage of this is that, there could be a situation where the new trigger might have to wait for the next fire time of the old trigger before the changes takes in place: which I think might be acceptable.

2. We could make the `restartDelay` configurable in the `@Scheduled` annotation.
This might solve the disadvantage of the first option but it makes the API convoluted. Restart does not make sense for in memory scheduler, only make sense for quartz persisted jobs. 

I am leaning more towards the first option. I'd like to know what others think about it. 
/cc @mkouba

**Comment by apat59** [comment]
Indeed the issue is only the lost of the persistent state, mainly the next fire time.
Your solution looks perfect to me.

Not directly related but I'd also add this sort of warning in the guide:
Whenever you change the @Scheduled.identity, remove the @Scheduled annotation, quarkus is not in charge of cleaning up the qrtz_ tables, this must be handled by the migration scripts (flyway), or manually.

**Comment by mkouba** [comment]
@machi1990 I think that solution 1 makes sense. What other state is lost BTW?

> Whenever you change the @Scheduled.identity, remove the @scheduled annotation, quarkus is not in charge of cleaning up the qrtz_ tables related rows, this must be handled by the migration scripts (flyway), or manually.

@apat59 +1

**Comment by machi1990** [comment]
> @machi1990 I think that solution 1 makes sense. 
> Indeed the issue is only the lost of the persistent state, mainly the next fire time.
Your solution looks perfect to me.

@apat59 do you want to take a stab at this issue by opening a PR with the suggested solution? 

> What other state is lost BTW?

None other that come to mind other than the next fire time.

**Comment by Ashwin-exe** [comment]
Hi, @machi1990 Can I work on this I am new to open source, I understood that we have to preserve the next fire time of the old job before rescheduling the trigger by setting the old trigger "next fire time" as the "new trigger start time", am I right?
It would be helpful if you can share some follow-ups for me, Thanks.

**Comment by machi1990** [comment]
> Hi, @machi1990 Can I work on this I am new to open source, I understood that we have to preserve the next fire time of the old job before rescheduling the trigger by setting the old trigger "next fire time" as the "new trigger start time", am I right? 

Hi @ashwinair thanks for proposing to fix this. You are correct, and this has to be done only for existing jobs. 
This snippet 
```java
org.quartz.Trigger oldTrigger = scheduler.getTrigger(trigger.getKey());
scheduler.rescheduleJob(trigger.getKey(),triggerBuilder.startAt(oldTrigger.getNextFireTime()).build());
```
That need to be done in this block 
https://github.com/quarkusio/quarkus/blob/0794e80a907b2146cae334ef5c6e2c37ec675001/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L203-L207

> It would be helpful if you can share some follow-ups for me, Thanks.

You mean followup issues? If yes, let's get this one in and we can look for others together I've couple of ideas.

**Comment by ashwinair** [comment]
> > It would be helpful if you can share some follow-ups for me, Thanks.
> 
> You mean followup issues? If yes, let's get this one in and we can look for others together I've couple of ideas.
Ya, sure it would be good for me too as I get to learn about quarkus more.

sorry for replying late, actually I was trying to fix my quarkus setup issues first before submitting my first pull request that's why.
can you check it out? #22717 
Thanks :)
