### ISSUE TITLE
@Valid annotation treated as a bean

### ISSUE THREAD

**Issue by artkonr** [quarkusio/quarkus#21469]
### Describe the bug

If I create a config mapping interface and try to inject it anywhere (e.g. in a `@Producer` method) and place `@Valid` annotation on it, Quarkus seems to think that `@Valid` is actually the type of injected bean. Is this intended? Maybe config validation is supposed to be done only via `Validator`? With other beans it works.

I've also stumbled upon a ticket that describes a similar case, but I can't find it now :)

See repro.

### Expected behavior

When I inject a `@ConfigMapping`-annotated bean with `@Valid` on top of it, I expect the validation to kick in.

### Actual behavior

Quarkus fails to bootstrap

### How to Reproduce?

here's a link to a repro: https://github.com/artkonr/demo5

### Output of `uname -a` or `ver`

Darwin C8049 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by artkonr** [comment]
Thanks, @radcortez , got it.

I was just trying to apply the general approach to validation, figured it should work this way. The part of the documentation which describes config value validation seemed a bit vague to me on this account, it doesn't mention that the validation is done automatically. I'd probably add a note that client code does not need to validate the config-mapped interfaces manually.

As for the injection practice, I just have a real piece of code I'm working on, which is supposed to take the config-mapped bean and use it to produce a bean from a regular class. I guess field-based injection is a perfectly valid alternative, but in my case adding `@Valid` to it actually failed as well (see the snippet):

```java

@Inject
@Valid
GreetingsConfig cfg;

```

It struck me as something unusual, all the more confusing since the bootstrap failure didn't indicate the real problem and kept reporting that it cannot make a bean out of an annotation. Besides, I've been using `@Qualifier`s all along and they work OK.

So in this light, I'd consider adding some more meaningful error description for such a case, if it makes sense.

**Comment by gsmet** [comment]
I agree this is a bit weird, `@Valid` shouldn't have any implications on CDI beans. @radcortez could you have a quick look at the reproducer?

**Comment by radcortez** [comment]
> I was just trying to apply the general approach to validation, figured it should work this way. The part of the documentation which describes config value validation seemed a bit vague to me on this account, it doesn't mention that the validation is done automatically. I'd probably add a note that client code does not need to validate the config-mapped interfaces manually.

Sure. Let's clarify the documentation.

> It struck me as something unusual, all the more confusing since the bootstrap failure didn't indicate the real problem and kept reporting that it cannot make a bean out of an annotation. Besides, I've been using `@Qualifier`s all along and they work OK.

The `@Valid` is not required, but it shouldn't fail either. I'll have a look. For now, just remove the annotation, it will work without it anyway.

**Comment by radcortez** [comment]
> I agree this is a bit weird, `@Valid` shouldn't have any implications on CDI beans. @radcortez could you have a quick look at the reproducer?

Sure, I'll have a look.
