### ISSUE TITLE
quarkus.arc.test.disable-application-lifecycle-observers doesn't work for the dependency .jar

### ISSUE THREAD

**Issue by zenonwch** [quarkusio/quarkus#21487]
### Describe the bug

I have a dependency jar in which there is an ApplicatonScoped class with method onStart(@Observes StartupEvent ev)

When I run my tests with the quarkus.arc.test.disable-application-lifecycle-observers=true all events in methods with StartupEvent in my application are disabled, but method from the dependency lib a still works :(.

### Expected behavior

quarkus.arc.test.disable-application-lifecycle-observers=true should be applied for all beans in container

### Actual behavior

quarkus.arc.test.disable-application-lifecycle-observers=true applies for beans from my application only (excluding beans from dependency modules)

### How to Reproduce?

1. Create a jar with a class that contains a method with StartupEvent
2. Add the jar as a dependency to the any simple application
3. Run any @QuarkusTest in the application

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15

### Quarkus version or git rev

2.3.1 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by mkouba** [comment]
So we intentionally only disable the `StartupEvent` and `ShutdownEvent` observers declared on _application bean classes_ during the tests (i.e. classes from the application root and possibly other modules in a multi-module app). See also the config property description: https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.test.disable-application-lifecycle-observers and the discussion in https://github.com/quarkusio/quarkus/issues/15083. The main reason is that some extensions may perform some init logic in these observers.

As a workaround you can add the dependency in the list of hot-reloadable artifacts via the [`quarkus.class-loading.reloadable-artifacts`](https://quarkus.io/guides/all-config#quarkus-core_quarkus.class-loading.reloadable-artifacts) configuration property; e.g. place the `%test.quarkus.class-loading.reloadable-artifacts=org.acme:my-lib-artifactId` in the `application.properties` file. The `%test.` prefix means that it's only used during tests.

**Comment by zenonwch** [comment]
Thanks,  quarkus.class-loading.reloadable-artifacts works for my case.
