### ISSUE TITLE
Maven archetype generates code with file path in @Path

### ISSUE THREAD

**Issue by chrisjleu** [quarkusio/quarkus#2149]
On Windows (GitBash) the archetype places the file path of the GitBash installation in the Java source file, something like `@Path("/C:/Program Files/Git/hello")`.

```
mvn io.quarkus:quarkus-maven-plugin:0.13.3:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello
```

```java
package org.acme.quickstart;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;


@Path("/C:/Program Files/Git/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```
The same happens in the unit test.

**Comment by cescoffier** [comment]
oh, this is wonderful! I will have a look. BTW, in your first snippet, a double quote is missing. Is it on purpose?

**Comment by chrisjleu** [comment]
> oh, this is wonderful! I will have a look. BTW, in your first snippet, a double quote is missing. Is it on purpose?

No that's my bad.

**Comment by famod** [comment]
I have to confirm this bug with Quarkus 0.14.0.

**Comment by gsmet** [comment]
I don't think it's a bug in Quarkus but rather a bug in the shell, mistakenly appending the current directory to the path.

**Comment by famod** [comment]
I have just re-checked with 1.0.0.CR1. The problem is the leadng slash!
Works: `-Dpath="hello"`
Doesn't work: `-Dpath='/hello'`

**Comment by famod** [comment]
This is actually a _feature_ of MinGW: [Posix path conversion](http://www.mingw.org/wiki/Posix_path_conversion)
See the
```
foo=/bar
```
example which becomes:
```
foo=C:/MinGW/msys/1.0/bar
```

@gsmet how about adding a note to https://quarkus.io/guides/getting-started?
