### ISSUE TITLE
tekton  task mvn report error 401 Unauthorized

### ISSUE THREAD

**Issue by weir2010** [quarkusio/quarkus#21507]
### Describe the bug

Reference articles：https://www.infoq.com/articles/microservicilities-tekton/

error info:

> [INFO] Building jar: /workspace/source/target/quarkus-member-system-1.0.0.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:2.4.2.Final:build (default) @ quarkus-member-system ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.6.1.Final
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[INFO] Checking for existing resources in: /workspace/source/src/main/kubernetes.
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for fabric8/java-alpine-openjdk11-jre...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=Docker config auths section defines credentials for docker.io]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=LIFECYCLE, message=Using credentials from Docker config (/root/.docker/config.json) for fabric8/java-alpine-openjdk11-jre]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2021-11-16T14:36:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.4.2.Final:build (default) on project quarkus-member-system: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:194)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:134)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:821)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryAuthenticationFailedException: Failed to authenticate with registry registry-1.docker.io/fabric8/java-alpine-openjdk11-jre because: 401 Unauthorized
[ERROR] GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:fabric8/java-alpine-openjdk11-jre:pull
[ERROR] {"details":"incorrect username or password"}
[ERROR] 
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:305)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:257)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticatePull(RegistryAuthenticator.java:176)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:336)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.authPullByWwwAuthenticate(RegistryClient.java:395)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:177)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] Caused by: com.google.cloud.tools.jib.http.ResponseException: 401 Unauthorized
[ERROR] GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:fabric8/java-alpine-openjdk11-jre:pull
[ERROR] {"details":"incorrect username or password"}
[ERROR] 
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:355)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:283)
[ERROR] 	... 12 more
[ERROR] Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
[ERROR] GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:fabric8/java-alpine-openjdk11-jre:pull
[ERROR] {"details":"incorrect username or password"}
[ERROR] 
[ERROR] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:349)
[ERROR] 	... 14 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### Expected behavior

build-push-task-member.yml

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: build-member-app
spec:
 params:
 - name: docker-credentials-secret
   type: string
   description: name of the secret holding the docker credentials
   default: docker-credentials
 resources:
   inputs:
     - name: source
       type: git
   outputs:
     - name: builtImage
       type: image
 steps:
   - name: maven-build
     image: docker.io/maven:3.6-jdk-11-slim
     workingDir: "/workspace/source/"
     command:
       - mvn
     args:
       - -s
       - "/.m2/settings.xml"
       - clean
       - package
       - -DskipTests
       - -Dquarkus.container-image.push=true
     env:
     - name: QUARKUS_CONTAINER_IMAGE_IMAGE
       value: $(outputs.resources.builtImage.url)
     - name: QUARKUS_CONTAINER_IMAGE_USERNAME
       valueFrom:
         secretKeyRef:
           name: $(params.docker-credentials-secret)
           key: docker-username
     - name: QUARKUS_CONTAINER_IMAGE_PASSWORD
       valueFrom:
         secretKeyRef:
           name: $(params.docker-credentials-secret)
           key: docker-password
     volumeMounts:
     - mountPath: /.m2
       name: mvn-settings
 volumes:
   - name: mvn-settings
     configMap:
       name: member-maven-settings
       items:
       - key: weir.xml
         path: settings.xml

### Output of `uname -a` or `ver`

Darwin weirdeMacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java-alpine-openjdk11-jre

### Quarkus version or git rev

2.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by geoand** [comment]
Is there a code repository you can link to?

**Comment by weir2010** [comment]
solved！

for：

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: build-member-app
spec:
 params:
 - name: docker-credentials-secret
   type: string
   description: name of the secret holding the docker credentials
   default: docker-credentials
 resources:
   inputs:
     - name: source
       type: git
   outputs:
     - name: builtImage
       type: image
 steps:
   - name: maven-build
     image: docker.io/maven:3.6-jdk-11-slim
     workingDir: "/workspace/source/"
    #  script: |
    #   #!/usr/bin/env bash
    #   cd /workspace/source/target
    #   ls
    #   cat quarkus-artifact.properties
     command:
       - mvn
     args:
       - -s
       - "/.m2/settings.xml"
       - clean
       - compile
       - jib:build
      #  - package
       - -DskipTests
      #  - -Djib.to.image=hub.weir.com/weir/quarkus-member-system:latest
      #  - -Djavax.net.ssl.trustStore=/data/hub.weir.com.jks
      #  - -Djavax.net.ssl.trustStorePassword=336393
     env:
     - name: QUARKUS_CONTAINER_IMAGE_IMAGE
       value: $(outputs.resources.builtImage.url)
     - name: QUARKUS_CONTAINER_IMAGE_USERNAME
       valueFrom:
         secretKeyRef:
           name: $(params.docker-credentials-secret)
           key: docker-username
     - name: QUARKUS_CONTAINER_IMAGE_PASSWORD
       valueFrom:
         secretKeyRef:
           name: $(params.docker-credentials-secret)
           key: docker-password
     volumeMounts:
     - mountPath: /.m2
       name: mvn-settings
     - mountPath: /data
       name: weir-com
 volumes:
   - name: mvn-settings
     configMap:
       name: member-maven-settings
       items:
       - key: weir.xml
         path: settings.xml
   - name: weir-com
     configMap:
       name: hub-weir-com-jks
       items:
       - key: hub.weir.com.jks
         path: hub.weir.com.jks
