### ISSUE TITLE
How to stop a Quarkus application

### ISSUE THREAD

**Issue by simongun** [quarkusio/quarkus#2150]
The documentation https://quarkus.io/guides/application-lifecycle-events-guide does not mention how a Quarkus application can be stopped from within; this is necessary for e.g. command line or job type applications.
The io.quarkus.runtime.Application class provides the necessary APIs, but cannot be injected.

Thanks for any clarification.

**Comment by cescoffier** [comment]
Did you try `System.exit` ?

**Comment by simongun** [comment]
Yes, sorry, should have written that. That triggers Application's ShutdownHookThread and never returns from stateCond.awaitUninterruptibly(). That's why I thought the Application's state machine needs to be terminated via the Application's lifecylce methods ...

**Comment by simongun** [comment]
Just verified that with the most simple Quarkus application, System.exit does not happen:

```
@ApplicationScoped
public class AppLifecycleBean {
    private static final Logger LOGGER = LoggerFactory.getLogger("ListenerBean");
    void onStart(@Observes StartupEvent ev) {
        LOGGER.info("The application is starting...{}");
        new Thread(new Runnable() {
            @Override
            public void run() {
                LOGGER.info("About to system exit.");
                System.exit(0); // does not return
            }
        }).run();
    }
}
```

**Comment by dmlloyd** [comment]
You must call `Thread.start()`, not `Thread.run()`.

**Comment by simongun** [comment]
OK, so the findings are: If we System.exit() from the Thread from where we @Observed the Startup Event, System.exit() does not return:
```
public class AppLifecycleBean {
    private static final Logger LOGGER = LoggerFactory.getLogger("ListenerBean");
    void onStart(@Observes StartupEvent ev) {
        LOGGER.info("The application is starting...{}");
        LOGGER.info("About to system exit.");
        System.exit(0);
    }
}
```
But if we do it from a dedicated Thread, it works:

```
@ApplicationScoped
public class AppLifecycleBean {
    private static final Logger LOGGER = LoggerFactory.getLogger("ListenerBean");
    void onStart(@Observes StartupEvent ev) {
        LOGGER.info("The application is starting...{}");
        new Thread(new Runnable() {
            @Override
            public void run() {
                LOGGER.info("About to system exit.");
                System.exit(0);
            }
        }).start();
    }
}
```
Is this the expected behavior?`
Is it worth a note in the documentation?

**Comment by dmlloyd** [comment]
It is expected behavior. `exit` never returns, thus it blocks the thread forever.  The process doesn't exit until the thread pool shuts down, which cannot happen while threads are active. Thus, deadlock.

**Comment by simongun** [comment]
Thanks for your clarification & support. Since CLIs and Jobs will start their programs on @Observes StartupEvent, would it make sense to already dispatch these events from separate threads, so users don't have to figure out that they have to start their own threads to run their program? Or mention this fact in the documentation? Otherwise, feel free to close.

**Comment by dmlloyd** [comment]
That's an X/Y.  We need a proper shutdown API.  Also I don't think that observing `StartupEvent` is a proper long term solution for CLIs and jobs (I think there's an issue for this but I can't find it at the moment).  I do have an upcoming design proposal for these use cases.

**Comment by gastaldi** [comment]
Issue #2851 requests a proper shutdown API. Closing this issue now. Thanks!
