### ISSUE TITLE
No 2.5.0.CR1 artifacts exist for Quarkus Gradle Plugin and Gradle Application Plugin

### ISSUE THREAD

**Issue by ThoSap** [quarkusio/quarkus#21515]
### Describe the bug

In the MVN repository, no artifacts exist for Quarkus version `2.5.0.CR1`
- Quarkus Gradle Plugin -> https://mvnrepository.com/artifact/io.quarkus/io.quarkus.gradle.plugin?repo=gradle-plugins
- Gradle Application Plugin -> https://mvnrepository.com/artifact/io.quarkus/gradle-application-plugin

### Expected behavior

Artifacts should exist for Quarkus version `2.5.0.CR1` in the MVN repository
- Quarkus Gradle Plugin -> https://mvnrepository.com/artifact/io.quarkus/io.quarkus.gradle.plugin/2.5.0.CR1
- Gradle Application Plugin -> https://mvnrepository.com/artifact/io.quarkus/gradle-application-plugin/2.5.0.CR1

### Actual behavior

Gradle configure fails with
```gradle
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'my_project'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find quarkus-gradle-plugins:gradle-model:2.5.0.CR1.
     Searched in the following locations:
       - file:/C:/Users/ThoSap/.m2/repository/quarkus-gradle-plugins/gradle-model/2.5.0.CR1/gradle-model-2.5.0.CR1.pom
       - https://repo.maven.apache.org/maven2/quarkus-gradle-plugins/gradle-model/2.5.0.CR1/gradle-model-2.5.0.CR1.pom
       - https://plugins.gradle.org/m2/quarkus-gradle-plugins/gradle-model/2.5.0.CR1/gradle-model-2.5.0.CR1.pom
     Required by:
         project : > io.quarkus:io.quarkus.gradle.plugin:2.5.0.CR1 > io.quarkus:gradle-application-plugin:2.5.0.CR1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s

```

### How to Reproduce?

Download a Quarkus Gradle project https://code.quarkus.io/?b=GRADLE&e=rest-client-reactive&e=rest-client-reactive-jackson&extension-search=rest and change to the following in file `gradle.properties`
```properties
# Gradle properties
org.gradle.caching=true
org.gradle.logging.level=INFO

# Quarkus
quarkusPluginId=io.quarkus
quarkusPluginVersion=2.5.0.CR1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=2.5.0.CR1
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1916]

### Output of `java -version`

```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

### Quarkus version or git rev

2.5.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (Eclipse Adoptium 17.0.1+12)
OS:           Windows 10 10.0 amd64
```

**Comment by gsmet** [comment]
Thanks for the report. We stumbled upon it a few days ago.

It should be fixed for 2.5.0.Final: https://github.com/quarkusio/quarkus/pull/21485 .
