### ISSUE TITLE
Mutiny Uni.join().first(list) dosn't compile

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#21528]
### Describe the bug

        Uni<String> c = Uni.createFrom().item("C");
        Uni<String> d = Uni.createFrom().item("D");
        List<Uni<String>> asList = new ArrayList<>();
        asList.add(c);
        asList.add(d);

        Uni.join().first(asList).withItem();

'Cannot resolve method 'first(java.util.List<io.smallrye.mutiny.Uni<java.lang.String>>)'

### Actual behavior

doesn't compile
'Cannot resolve method 'first(java.util.List<io.smallrye.mutiny.Uni<java.lang.String>>)'

**Comment by jponge** [comment]
This is due to generics, the following works:

```java
        Uni<String> c = Uni.createFrom().item("C");
        Uni<String> d = Uni.createFrom().item("D");
        List<Uni<? extends String>> asList = new ArrayList<>();
        asList.add(c);
        asList.add(d);

        Uni.join().first(asList).withItem();
```

**Comment by ennishol** [comment]
@jponge Yes, but not practical, if we get unis list (`List<Uni<String>>`) from elsewhere then additional code is required:
```java 
List<Uni<? extends String>> asList = new ArrayList<>(unis());
Uni.join().first(asList).withItem();
```

**Comment by jponge** [comment]
Yes I'm thinking of revisiting generics here.

**Comment by jponge** [comment]
@ennishol There's a Mutiny 1.2.0 release in the coming days, so it will quickly be available.
