### ISSUE TITLE
Anything which starts logging too early will disable Quarkus logging

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2152]
The upstream LogManager has some stuff in it to prevent this from happening.  We should use that stuff.

**Comment by gsmet** [comment]
@dmlloyd do we still consider this an issue?

**Comment by dmlloyd** [comment]
Yes it's still not solved for Java agents.  I think we need a more resilient solution.

**Comment by stuartwdouglas** [comment]
Is there anything more we can realistically do here? We document/set the relevant system property every where we can, if a user uses a Java agent and does not set the property then IMHO this is user error, as AFAIK there is nothing we can do in that situation.
