### ISSUE TITLE
quarkus-avro: support UUID logical type

### ISSUE THREAD

**Issue by VoidAspect** [quarkusio/quarkus#21529]
### Description

Currently, the "uuid" logical type in the .avsc schema is interpreted as a String, and there's no validation to check if this string is a valid UUID.

### Implementation ideas

We can use an existing `org.apache.avro.Conversions.UUIDConversion` class and register it on the compiler.

**Comment by glefloch** [comment]
instead on registering the convertor, I think we could add an option that allow to list convertor to register? WDYT @michalszynkiewicz ?

**Comment by michalszynkiewicz** [comment]
sounds good to me

**Comment by gsmet** [comment]
I'm not that familiar with Avro but I think I would do both. UUID seems very widely used so I think it would make sense to have it enabled by default. But I'm not sure if it can break something to have it.

/cc @cescoffier

**Comment by glefloch** [comment]
sure we can do both.
