### ISSUE TITLE
quarkus-rest-client-reactive related configuration properties problem

### ISSUE THREAD

**Issue by nikosk686** [quarkusio/quarkus#21533]
### Describe the bug

Seems to be related to this [one](https://github.com/quarkusio/quarkus/issues/15032)

Tests ignore the `%test` properties for rest clients and try to use the `%prod` ones instead.
So having properties like these causes a failure in test that try to expand the prod value
```
%prod.external-service/mp-rest/url=${EXTERNAL_SERVICE_URL}
%test.external-service/mp-rest/url=http://localhost:8000
```

### Expected behavior

Tests should use the correct profile's properties of rest clients

### Actual behavior

Tests  use the prod profile's properties of rest clients

### How to Reproduce?

Reproducer: https://github.com/nikosk686/quarkus-config-properties-error-showcase

Try to run the test on the example linked above.
The error is:
> Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors have prevented the application from starting. The errors are: - SRCFG00011: Could not expand value EXTERNAL_SERVICE_URL in property %prod.external-service/mp-rest/url

Workaround, add a default value `%prod.external-service/mp-rest/url=${EXTERNAL_SERVICE_URL:}`
and the test passes

### Output of `uname -a` or `ver`

Linux dell-desktop 5.10.0-1051-oem #53-Ubuntu SMP Thu Oct 28 08:11:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

correto-11 version 11.0.13

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by geoand** [comment]
cc @TomasHofman @radcortez

**Comment by TomasHofman** [comment]
I will have a look.

**Comment by TomasHofman** [comment]
Thanks for well written bug report!

I think the problem is in incorrect implementation of the `RestClientFallbackConfigSourceInterceptor#iterateNames()` method. When the interceptor sees property like `%prod.config-key/mp-rest/url`, it tries to convert it to the new notation and the result is something like `quarkus.rest-client.%prod.config-key.url`. Later on, because this prop name is included in the iteration result, the property value is attempted to be expanded. The expansion fails because the value contains undefined variable (`${EXTERNAL_SERVICE_URL}`), which otherwise would not be needed in this scope.

I'm going to open a PR.

**Comment by BonomoAlessandro** [comment]
The on this page described bug is not fully resolved I guess.
I'm using Quarkus 2.5.1.Final.

If I run my tests with the properties defined like this, it will take the correct `%test` property.
`%prod.external-service/mp-rest/url=${EXTERNAL_SERVICE_URL}`
`%test.external-service/mp-rest/url=http://localhost:8000`

If I run my tests with just the test profile property it will also take the correct `%test` property.
`%test.external-service/mp-rest/url=http://localhost:8000`

But if I define the properties like the following, it will take the default property instead.
`external-service/mp-rest/url=${EXTERNAL_SERVICE_URL}`
`%test.external-service/mp-rest/url=http://localhost:8000`

Like on page [Quarkus - CONFIGURATION REFERENCE GUIDE](https://quarkus.io/guides/config-reference#profile-in-the-property-name) documented it should take the `%test` property if I run my tests.

**Comment by BonomoAlessandro** [comment]
The on this page described bug is not fully resolved I guess.
I'm using Quarkus 2.5.1.Final.

If I run my tests with the properties defined like this, it will take the correct `%test` property.
`%prod.external-service/mp-rest/url=${EXTERNAL_SERVICE_URL}`
`%test.external-service/mp-rest/url=http://localhost:8000`

If I run my tests with just the test profile property it will also take the correct `%test` property.
`%test.external-service/mp-rest/url=http://localhost:8000`

But if I define the properties like the following, it will take the default property instead.
`external-service/mp-rest/url=${EXTERNAL_SERVICE_URL}`
`%test.external-service/mp-rest/url=http://localhost:8000`

Like on page [Quarkus - CONFIGURATION REFERENCE GUIDE](https://quarkus.io/guides/config-reference#profile-in-the-property-name) documented it should take the `%test` property if I run my tests.

**Comment by TomasHofman** [comment]
I will have a look at that.

**Comment by TomasHofman** [comment]
@BonomoAlessandro I can't reproduce your problem with 2.5.1.Final neither with current main. Can you open a new issue with a small reproducer if you still experience it?
