### ISSUE TITLE
Noargs constructor is executed on non-bean-object proxies when returned from scoped producer method

### ISSUE THREAD

**Issue by E14** [quarkusio/quarkus#21568]
### Describe the bug

Consider a class:

```java
import java.util.concurrent.atomic.AtomicInteger;
import javax.enterprise.inject.Vetoed;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Vetoed
class A {
    private static final Logger LOG = LoggerFactory.getLogger(A.class);
    public static AtomicInteger count = new AtomicInteger(0);

    A() {
        LOG.info("{} constructed", this.getClass().getSimpleName());
        count.incrementAndGet();
    }

    public int getCount() {
        return A.count.get();
    }
}
```

Some bean with a scoped producer:
```java
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;

@ApplicationScoped
class Producer {
    @Produces
    @ApplicationScoped
    A produce() {
        return new A();
    }
}
```

And a unit test:
```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import javax.inject.Inject;
import org.junit.jupiter.api.Test;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
class ATest {
    @Inject
    A a;

    @Test
    void test() {
        assertEquals(1, a.getCount());
    }
}
```

The constructor will be invoked twice - once on creation of the client proxy for the application scope and once when creating the actual object.

### Expected behavior

Non-bean noargs constructor is not called or only pseudo scopes (`@Dependent`) are allowed for producers returning non-bean objects.

### Actual behavior

The test fails with:
> org.opentest4j.AssertionFailedError: expected: <1> but was: <2>

And it logs:

> 2021-11-19 11:59:46,732 INFO  [org.acm.cdi.pro.A] (main) Producer_ProducerMethod_produce_e48d74bd24e672937bf49c60afc6db55ea4584ea_ClientProxy constructed
> 2021-11-19 11:59:46,755 INFO  [org.acm.cdi.pro.A] (main) A constructed

Because the non-bean noargs constructor is called when the client proxy is constructed.

### How to Reproduce?

Run the unit test from the description above.

### Output of `uname -a` or `ver`

MSYS_NT-10.0-WOW STECH015 2.10.0(0.325/5/3) 2018-04-05 00:47 i686 Msys

### Output of `java -version`

Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Java\jdk-11.0.2

### Quarkus version or git rev

2.4.2.Final or 1.13.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: $USERPROFILE\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3 Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Java\jdk-11.0.2 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

As per the [CDI2 spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#producer_method)

> A producer method acts as a source of objects to be injected, where:
> * the objects to be injected are not required to be instances of beans [...]

producer methods are meant (among other use-cases) to bring non-beans into the CDI context, so it cannot be expected that those classes follow or even care about the rules of CDI (like having a noargs constructor without side-effects to allow proxy creation)

Currently, Quarkus will add a no-args constructor even to non-CDI classes in order to be able to generate a client proxy. So in addition to inserting and calling a noargs constructor into the bytecode when it does not exist, Quarkus could add and call a similar constructor _with_ argument(s) when a no-args constructor already exists.

If that is not possible, another option would be to fail at packaging when a (non-empty) non-bean constructor is invoked for creation of a client proxy.

Now a good consideration would be -- what does Weld do, as the reference implementation of CDI2? This test succeeds with Weld:

```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.jboss.weld.junit5.auto.AddBeanClasses;
import org.jboss.weld.junit5.auto.EnableAutoWeld;
import org.junit.jupiter.api.Test;

@EnableAutoWeld
@AddBeanClasses({ Producer.class })
class AWeldTest {
    @Test
    void test(A a) {
        assertNotEquals(a.getClass(), A.class); // Make sure we get a client proxy
        assertEquals(1, a.getCount());
    }
}
```

**Comment by famod** [comment]
I think this came up before:
- https://github.com/quarkusio/quarkus/issues/8062#issuecomment-602189071
- https://github.com/quarkusio/quarkus/issues/8960#issuecomment-621465379

**Comment by mkouba** [comment]
Hm, this works as mandated by the spec. And I believe that Weld does the same as ArC does. Are you really sure the test passed? Anyway, the test is not entirely correct because `A.count` is not synchronized/`volatile` and it could be in theory accessed from multiple threads.

**Comment by E14** [comment]
> I think this came up before:
> 
>     * [Constructor of bean with @Startup annotation is called twice #8062 (comment)](https://github.com/quarkusio/quarkus/issues/8062#issuecomment-602189071)
> 
>     * [An application scoped bean instantiated twice #8960 (comment)](https://github.com/quarkusio/quarkus/issues/8960#issuecomment-621465379)

These are about beans, I believe. `A` is not a bean.

**Comment by E14** [comment]
> Hm, this works as mandated by the spec. And I believe that Weld does the same as ArC does.
The spec only mentions that beans require a noargs constructor. I can't see where it says that calling the noargs constructor to instantiate a client proxy for a bean would be allowed, but I guess it can be implied. `A` is not a bean however.

I've noticed that `A` might be detected as a bean as per the spec in the unit test by arc, so I added `@Vetoed`,  still with the same results.

> Are you really sure the test passed?
...

> Anyway, the test is not entirely correct because `A.count` is not synchronized/`volatile` and it could be in theory accessed from multiple threads.

You are right, I've updated the test in the initial comment to use AtomicInteger, that should avoid the threading issues, but I got the same results; Quarkus test fails, Weld test succeeds.

**Comment by E14** [comment]
I think I found the relevant spec [Unproxyable bean types](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#unproxyable), so it's option two, according to spec (even though this talks about beans, not unmanaged classes) - throw a deployment error.

**Comment by E14** [comment]
So, I found out that weld-junit runs weld in relaxed mode by default, this actually fails now as well:

```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.jboss.weld.junit5.auto.AddBeanClasses;
import org.jboss.weld.junit5.auto.EnableAutoWeld;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

@EnableAutoWeld
@AddBeanClasses({ Producer.class })
class AWeldTest {
    @BeforeAll
    static void configure() {
        System.setProperty("org.jboss.weld.construction.relaxed", "false");
    }
    @Test
    void test(A a) {
        assertNotEquals(a.getClass(), A.class); // Make sure we get a client proxy
        assertEquals(1, a.getCount()); // => expected: <1> but was: <2>
    }
}
```

I still think this is wrong and the most appropriate way to throw a deployment exception, but I guess it is what Weld does as well.

**Comment by geoand** [comment]
@mkouba @manovotn should this be closed?

**Comment by mkouba** [comment]
Yes, I think that this one should be closed. `org.jboss.weld.construction.relaxed` is a non-portable feature where the constructor is not used at all to instantiate proxy instances and AFAIK it's only enabled by default for Weld SE.

> ### Expected behavior
> Non-bean noargs constructor is not called or only pseudo scopes (`@Dependent`) are allowed for producers returning non-bean objects.

Producer methods/fields are allowed to declare normal scopes. However, there are additional restrictions upon bean types for such bean types as mentioned in the [Bean types of a producer method](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#producer_method_types) and defined in [Unproxyable bean types](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#unproxyable).

**Comment by manovotn** [comment]
Late to the party but yes, this is intended behavior as per specification.

**Comment by E14** [comment]
Sorry for the trouble here, I'm OK with closing too (if that makes any difference)

I still think this is more in the area of unspecified behaviour. but I really like and appreciate what you're doing with the whole Quarkus ecosystem in general

**Comment by mkouba** [comment]
> Sorry for the trouble here, I'm OK with closing too (if that makes any difference)

+1 ;-)

> I still think this is more in the area of unspecified behaviour. 

I believe that the behavior is well-defined by the spec. That's my interpretation and I've spent many years working on the CDI spec, TCK and implementations (which of course does not mean I cannot be wrong ;-).

> but I really like and appreciate what you're doing with the whole Quarkus ecosystem in general

Thanks!
