### ISSUE TITLE
Kafka channel for profile "my-profile" is being picked up in the "prod" profile.

### ISSUE THREAD

**Issue by wmedvede** [quarkusio/quarkus#21572]
### Describe the bug

I have a kafka channel configuration like this:

%events-support.kafka.bootstrap.servers=localhost:9092
%events-support.mp.messaging.incoming.acme-events.enabled=true
%events-support.mp.messaging.incoming.acme-events.connector=smallrye-kafka
%events-support.mp.messaging.incoming.acme-events.topic=acme-events
%events-support.mp.messaging.incoming.acme-events.client.id=acme-events-service
%events-support.mp.messaging.incoming.acme-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

In Quarkus 2.3 and 2.4 this worked fine, i.e., the channel is picked up only when the app is started with the events-support profile.

When I moved the same example to Quarkus 2.5.0.Final, the channel is always picked up. e.g, if the "prod" profile active, the channel is picked up.

### Expected behavior

The channel above should be picked up only when the events-support profile is activated.

### How to Reproduce?

1) configure a channel for a given profile like the one in the description
2) stat the app in the "prod" profile
3) the channel is picked up.

**Comment by cescoffier** [comment]
That's probably due to the new build time wiring. 

@radcortez the extension must read the configuration using the Config Provider does that support profiles?

**Comment by radcortez** [comment]
`ConfigProvider` will load values from the currently active profile. During build time, the active profile is `prod`, so it should work as usual. Unless there is something different on how the config is being loaded.

**Comment by wmedvede** [comment]
HI @cescoffier , @radcortez In case it can help to identify where the potential change was introduced I've confirm that Quarkus 2.4.2.Final works well too, so 2.3, 2.4, and 2.4.2 works well. The issue must have been introduced in 2.5.

**Comment by wmedvede** [comment]
Some more information @cescoffier @radcortez 

Even by using an empty application.properties, i.e., no connectors configuration at all, I have the following situation.

1) When the application starts, it looks like an on-the-fly connector is being generated.
see: https://gist.github.com/wmedvede/de8bb42cc64a5fd7f353f24074fdcaa1

2) If I send kafka messages to that topic with another application, the effect is that current application receives the messages.
see: https://gist.github.com/wmedvede/82865e37315ec571a7413e1ba838cb16

(so the on-the-fly connector created in 1, effectively is working. In my local machine I have of course kafka working, etc)

3) Finally here's the code of the receiver in my application:
see: https://gist.github.com/wmedvede/08b9e7e60f43cf38d11b96b695c11177

So, it looks like an on-the-fly connector with a set of by default parameters is being created.

**Comment by wmedvede** [comment]
It looks like on the fly outgoing connectors are being generated too:

If I add the following code to my bean:

    @Inject
    @Channel("NOT_CONFIGURED_EMITTER")
    Emitter<String> notConfiguredEmitter;

when the application starts I can see this message:

2021-11-22 16:40:45,595 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18258: Kafka producer kafka-producer-NOT_CONFIGURED_EMITTER, connected to Kafka brokers 'localhost:9092', is configured to write records to 'NOT_CONFIGURED_EMITTER'

**Comment by wmedvede** [comment]
finally in 2.4.2.Final I see the messages below. Which looks better, a WARNING is produced, but the application starts since the   CDI dependency graph is there.

__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-11-22 16:47:17,662 WARN  [io.sma.rea.mes.provider] (main) SRMSG00207: Some components are not connected to either downstream consumers or upstream producers:
        - Emitter{channel:'NOT_CONFIGURED_EMITTER'} has no downstream
        - SubscriberMethod{method:'org.acme.messaging.ReactiveMessagingEventConsumer#onEventEvent', incoming:'acme-events'} has no upstream

**Comment by cescoffier** [comment]
I just try your initial example and everything works as expected.
Note that if you build the application with the events-support profile enabled, it will find it at runtime (without or without the profile). 
But if you do not enable the profile at build time:

```shell
>  java -jar target/quarkus-app/quarkus-run.jar # channel not seen
>  java -Dquarkus.profile=events-support -jar target/quarkus-app/quarkus-run.jar # channel seen
```

About the other comments. If you have a single connector on the classpath, we use that one. This attachment can be disabled using the following property:

```
quarkus.reactive-messaging.auto-connector-attachment=true
```

This property is a **build** time property.

**Comment by wmedvede** [comment]
> 

Thanks for the info @cescoffier , but let me ask you another question.

This kind of auto-picking of the connector (and the subsequent automatic generation) is something new in Quarkus 2.5? 

Because, if I run the same app with quarkus 2.4.2.Final this "auto-picking" effect is not happening. (in fact it looks like the quarkus.reactive-messaging.auto-connector-attachment does nothing.)

(reproducer here!: https://github.com/wmedvede/channel-issue-reproducer/tree/master/acme-kafka-receiver)

**In quarkus 2.4.2 I always see this in the log:**

2021-11-22 18:03:20,739 WARN  [io.sma.rea.mes.provider] (main) SRMSG00207: Some components are not connected to either downstream consumers or upstream producers:
        - Emitter{channel:'NOT_CONFIGURED_EMITTER'} has no downstream
        - SubscriberMethod{method:'org.acme.messaging.ReactiveMessagingEventConsumer#onEventEvent', incoming:'acme-events'} has no upstream


**However in quarkus 2.5.0 I see this:** (by setting NO extra property quarkus.reactive-messaging.auto-connector-attachment)

2021-11-22 18:09:35,343 WARN  [io.sma.rea.mes.kafka] (main) SRMSG18216: No `group.id` set in the configuration, generate a random id: 1f42313f-c488-48c6-8a5e-eea3d1eaf1f5
2021-11-22 18:09:35,365 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18229: Configured topics for channel 'acme-events': [acme-events]
2021-11-22 18:09:35,372 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18213: Setting bootstrap.servers to localhost:9092
2021-11-22 18:09:35,372 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18214: Key deserializer omitted, using String as default
2021-11-22 18:09:35,556 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18213: Setting bootstrap.servers to localhost:9092
2021-11-22 18:09:35,591 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18258: Kafka producer kafka-producer-NOT_CONFIGURED_EMITTER, connected to Kafka brokers 'localhost:9092', is configured to write records to 'NOT_CONFIGURED_EMITTER'
2021-11-22 18:09:35,664 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18257: Kafka consumer kafka-consumer-acme-events, connected to Kafka brokers 'localhost:9092', belongs to the '1f42313f-c488-48c6-8a5e-eea3d1eaf1f5' consumer group and is configured to poll records from [acme-events]
2


And finally by setting  quarkus.reactive-messaging.auto-connector-attachment=false I can get the same semantic as in 2.4.2

Thanks!

**Comment by cescoffier** [comment]
Yes, auto attachment is a new feature in 2.5. It avoids having to configure connectors when you have a single one on the classpath. 

It is actually done using build time wiring which prepares the graph at build time, and can detect issues at build time.

We are planning more feature which are possible using this new build time wiring.

**Comment by wmedvede** [comment]
@cescoffier THANK you!! this drove me nuts. Now I understand :).
