### ISSUE TITLE
Add the possibillity to return custom http response headers based on `application.properties`

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#21570]
### Description

The use case for me is to extend the response headers with a semver version notation of the public REST API in a header: `API-Version`.  See a screenshot of FireFox F12-network here:

![image](https://user-images.githubusercontent.com/6173283/142628212-f60a1c8a-e628-4e6b-b528-321edd53c445.png)

This is driven by the following piece of configuration in `application.properties`: 

```
application.version=1.0.0
```

Which could build-time be populated with the maven coordinates. 

To make this generic, one could think of the following addition:

```
quarkus.http.responseheader.<id>.name=API-Version
quarkus.http.responseheader.<id>.value=1.0.0
```

in a practical case such as this:
```
quarkus.http.responseheader.apiversion.name=API-Version
quarkus.http.responseheader.apiversion.value=1.0.0
```

See also: #21457

### Implementation ideas

I've used a `vertex.RouteFilter` to implement this:

```java
public class ApiVersionResponseFilter {

    private static final String API_VERSION_HEADER = "API-Version";

    //CHECKSTYLE:OFF
    @Inject
    ConfigProvider provider;
    //CHECKSTYLE:ON

    @RouteFilter
    public void addResponse(RoutingContext rc) {
            rc.response().headers().set( API_VERSION_HEADER,  provider.version  );
        rc.next();
    }

    @Dependent
    public static class ConfigProvider {

        //CHECKSTYLE:OFF
        @ConfigProperty( name = "application.version" )
        String version;
        //CHECKSTYLE:ON

    }
}
```

**Comment by sberyozkin** [comment]
@gastaldi You have already done it, right ?

**Comment by gastaldi** [comment]
> @gastaldi You have already done it, right ?

Yes, it's documented in https://quarkus.io/version/main/guides/http-reference#additional-http-headers
It is only available in `2.5.0.CR1` onwards (see https://github.com/quarkusio/quarkus/pull/21102).

Closing this issue as a duplicate

**Comment by gastaldi** [comment]
FTR this is what you would add in your `application.properties` :

```properties
quarkus.http.header."API-Version".value=${application.version}
```

**Comment by gastaldi** [comment]
Or you could avoid the `application.version`  property entirely and use:

``` properties
quarkus.http.header."API-Version".value=${quarkus.application.version:1.0.0}
```

`quarkus.application.version`: The version of the application. If not set, defaults to the version of the project (except for tests where it is not set at all).

**Comment by sjaakd** [comment]
@gastaldi , @sberyozkin Thanks! This is good news.
