### ISSUE TITLE
Annotations @Authenticated and @RolesAllowed are ignored if resource returns a Multi

### ISSUE THREAD

**Issue by BaptisteCyrill** [quarkusio/quarkus#21585]
### Describe the bug

If the resource returns a Multi the annotations @Authenticated and @RolesAllowed are completely ignored.
The response returns http code 200.

### Expected behavior

The response should return http code 401.

### Actual behavior

The response returns http code 200.

### How to Reproduce?

Reproducer:
https://bitbucket.org/AlexanderJoeris/quarkus-keyloak-issue/src/master/

Steps to reproduce the behaviour:
1. mvn test => test cases fail
2. replace quarkus version no in pom.xml (line 21) from 2.4.2.Final to 2.4.1.Final
3. mvn test => test cases succeed

### Output of `uname -a` or `ver`

Linux jojo-020 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by sberyozkin** [comment]
@BaptisteCyrill it has been fixed, please see #21518, thanks
