### ISSUE TITLE
Qute: insert in for/each doesn't have the desired effect

### ISSUE THREAD

**Issue by Mai-Lapyst** [quarkusio/quarkus#21584]
### Describe the bug

When putting a `{#insert}` section inside a for loop (or an each loop) in qute, nothing gets inserted and the default body is used instead.

### Expected behavior

That one is able to write an include-able template in which a `{#insert}` section is inside a `{#for}` / `{#each}` section.

### Actual behavior

The `{#insert}` section doesn't insert the template from the including template but instead uses the default body.

### How to Reproduce?

Reproducer: [qute_insert_for_bug.zip](https://github.com/quarkusio/quarkus/files/7573051/qute_insert_for_bug.zip)

1. Add an new template; name it "list_layout.html" with a following content:
```
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        {#for e : list}
            {#insert row name=e}No section body<br>{/}
        {/for}
    </body>
</html>
```
2. Add an second template; name it "helloworld_list.html" with following content
```
{#include list_layout}
    {#row}
        Hello world, {name}!<br>
    {/row}
{/include}
```
3. Write a resource/controller wich uses following code:
```
@Path("/list_helloworld")
public class HelloWorldRessource {
    @Inject
    Template helloworld_list;

    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance helloworld() {
        return helloworld_list.instance().data("list", new String[] { "Tony", "Ben", "Bruce" });
    }
}
```
4. Run the quarkus application and visit `http://localhost:8080/list_helloworld` in your browser.

### Output of `uname -a` or `ver`

Linux 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### GraalVM version (if different from Java)

GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)

### Quarkus version or git rev

2.5.0.Final (using io.quarkus instead of io.quarkus.platform)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by mkouba** [comment]
@Mai-Lapyst Thanks for reporting this! It should be easy to fix.
