### ISSUE TITLE
Swagger interface refuses to 'try' text value 1.0 as examplevalue in TextPlain

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#21597]
### Describe the bug

```java

@Path( "" )
public interface RestResource {

    @POST
    @Path( "/reproduce" )
    @Consumes( MediaType.TEXT_PLAIN  )
    @Produces( MediaType.TEXT_PLAIN )
    @Operation(
        operationId = "test",
        summary = "this is a tester",
        description = "a long story for something short: test"
    )
    @RequestBody(
        content = @Content(
            mediaType = MediaType.TEXT_PLAIN,
            examples = {
                @ExampleObject(
                    name = "version",
                    description = "1.0",
                    value = "1.0"
                )
            }
        )
    )
    @APIResponse(
        responseCode = "200",
        content = @Content( mediaType = MediaType.TEXT_PLAIN),
        description = "The result."
    )
    Response test(String xml);
}

```
Gives result

![image](https://user-images.githubusercontent.com/6173283/142777448-7b7651e9-c5e2-4006-8584-f9a4bb4b36b5.png)

### Expected behavior

an example value `1.0` 

### Actual behavior

`1`. Apparently some string manipulation takes place in the translation to javascript.

### How to Reproduce?

See reproducer: https://github.com/sjaakd/reproducer_quarkus_swagger_1_0

Try:
http://localhost:8080/reproducer/q/swagger-ui/#/Rest%20Resource/test

### Output of `java -version`

11

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by sjaakd** [comment]
I guess this needs to go to the swagger-ui git project?

**Comment by phillip-kruger** [comment]
Yes could be. I have not had a chance to look at this

**Comment by MikeEdgar** [comment]
@sjaakd - what is the output in the OpenAPI JSON/YAML? Unquoted `1.0` ?

**Comment by sjaakd** [comment]
> @sjaakd - what is the output in the OpenAPI JSON/YAML? Unquoted `1.0` ?

```yaml
---
openapi: 3.0.0
info:
  title: '@project.artifactId@ API'
  version: '@project.version@'
paths:
  /reproducer/reproduce:
    post:
      tags:
      - Rest Resource
      summary: this is a tester
      description: "a long story for something short: test"
      operationId: test
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            examples:
              version:
                description: "1.0"
                value: 1.0
      responses:
        "200":
          description: The result.
          content:
            text/plain: {}
```

**Comment by phillip-kruger** [comment]
@MikeEdgar - are you looking at this ?

**Comment by phillip-kruger** [comment]
Ok thanks

**Comment by phillip-kruger** [comment]
@sjaakd - can we  close here, and you can follow up on swagger-ui ?

**Comment by sjaakd** [comment]
I posted the issue here: https://github.com/swagger-api/swagger-ui/issues/7721

Thanks for looking into this!
