### ISSUE TITLE
Objcopy warning when building native executable on Windows 

### ISSUE THREAD

**Issue by geertschuring** [quarkusio/quarkus#21600]
### Describe the bug

When building a native-image on Windows 10 I get the following warning towards the end of the successful build:

```
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] objcopy executable not found in PATH. Debug symbols will therefore not be separated from the executable.
[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] That also means that resulting native executable is larger as it embeds the debug symbols.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 97534ms
```

I cannot find any documentation on how to install the missing executable.

### Expected behavior

I would expect the Quarkus documentation to tell me how to install the objcopy executable on Windows.

### Actual behavior

Quarkus gives me a warning message, but no help on how to solve it.

### How to Reproduce?

Run `mvnw clean package -Pnative` in a project generated by https://code.quarkus.redhat.com/

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

### GraalVM version (if different from Java)

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

RedHat Quarkus 2.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
This was fixed in https://github.com/quarkusio/quarkus/pull/20297
