### ISSUE TITLE
Quarkus CLI is outdated / Quarkus 2.3.0.Final based

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#21609]
### Describe the bug

When following https://quarkus.io/guides/cli-tooling#installing-the-cli instructions, I get Quarkus CLI based on version 2.3.0..Final instead of the latest, 2.4.2.Final atm.

```
quarkus --version
Client Version 2.3.0.Final
```

Apparently the https://github.com/quarkusio/jbang-catalog/blob/main/jbang-catalog.json is not updated with every Quarkus release. The last change was done one and half month ago. 

@gsmet, @maxandersen 

### Expected behavior

The latest version of cli is available, 2.4.2.Final atm.

### Actual behavior

2.3.0.Final version of cli is available.

**Comment by ebullient** [comment]
This is resolved. 2.5.1 pulled yesterday

**Comment by gsmet** [comment]
@ebullient FYI, updating https://github.com/quarkusio/jbang-catalog/blob/main/jbang-catalog.json is now part of my release process.

**Comment by ebullient** [comment]
I was pretty sure you and Max had sorted that. Thanks for updating the issue.
