### ISSUE TITLE
'No message codec' error when following "Using the [vertx] event bus" guide

### ISSUE THREAD

**Issue by rgmz** [quarkusio/quarkus#21619]
### Describe the bug

In the ["Using the event bus" guide](https://quarkus.io/guides/reactive-event-bus#using-codecs) it mentions that Quarkus provides a default `MessageCodec` for locally delivery. However, the example in the documentation results in a 'No message codec' error (at least with Kotlin).

> Quarkus provides a default codec for local delivery. So you can exchange objects as follows:
> ...
> ```java
>     return bus.<String>request("greeting", new MyName(name))
>        .onItem().transform(Message::body);
> ```

### Expected behavior

If `LocalEventBusCodec` is meant to work implicitly, I'd expect this to to 'just work'.

However, my assumption is that you'd actually need to register an instance of [`LocalEventBusCodec`](https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/LocalEventBusCodec.java) first, so the documentation should be updated to reflect this. I'm happy to open a PR if this is the case.

### Actual behavior

Sending an object locally throws an exception:

```
java.lang.IllegalArgumentException: No message codec for type: class org.acme.example.MyName
        at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101)
        at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:232)
        at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:102)
        at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:97)
        at io.vertx.mutiny.core.eventbus.EventBus.send(EventBus.java:94)
...
```

### Quarkus version or git rev

2.5.0.CR1

**Comment by cescoffier** [comment]
Do you have the same behavior using Java?

**Comment by rgmz** [comment]
Apologies @cescoffier, this seems to be an error on my part.

I actually had `MyName` implement an abstract class (e.g. `Name`) and was specifying `Name` as the type for `@ConsumeEvent`. This seems to be expected behaviour:
```java
EventBus eb = vertx.eventBus();
eb.registerDefaultCodec(Name.class, new LocalEventBusCodec<Name>());

eb.<Name>consumer("greeting").handler(m -> {
    System.out.println("Body is: " + m.body());
});

MyName myName = new MyName(name);
eb.send("greeting", myName);

// 2021-11-22 13:43:35,206 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.IllegalArgumentException: No message codec for type: class org.acme.MyName
```

Manually creating an instance of `LocalEventBusCodec` and specifying that as the codecName in DeliveryOptions works.

(My work laptop is locked down, so I tend to take notes and submit issues from my personal laptop when I have time.)
