### ISSUE TITLE
Intellij plugin does not show links for kotlin endpoints

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#21612]
With the quarkus plugin in intellij installed endpoints are shown in dev mode and clickable. However this not available in kotlin.

**Comment by geoand** [comment]
cc @jeffmaury

**Comment by jeffmaury** [comment]
Tested on VSCode and having the same issue so cc @angelozerr

**Comment by gsmet** [comment]
@jeffmaury should this be moved to a more appropriate tracker?

**Comment by jeffmaury** [comment]
See also https://issues.redhat.com/browse/JBIDE-28193

**Comment by gsmet** [comment]
Closing this one as issues have been created in the appropriate projects.

Thanks @jeffmaury !
