### ISSUE TITLE
Spring data Page does not work with interface projection

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#21616]
### Describe the bug

When using `org.springframework.data.domain.Page` with an interface projection, we get an error.

The same query works fine when used with a `java.util.List` instead of a Page 

### Expected behavior

A Page of projected entities

### Actual behavior

We get an exception :

```
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class <redacted1>.$SmallItem ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; <redacted1>.$SmallItem  is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1c91a09d)
```

### How to Reproduce?

Create a repository with returning a `org.springframework.data.domain.Page` while using a projection to an interface.

```java
@Repository
public interface ItemRepository extends CrudRepository<Item, Long> {
    @Query(
        value = "select distinct(c.name) as name, c.id as id, c.version as version from Item c where lower(c.name) like :name" 
        ,countQuery = "select count(distinct(c.name)) from Item c where lower(c.name) like :name"
    )
    Page<SmallItem> findAllByName(@Param("name") String name, Pageable page);

    interface SmallItem {
        String getName();
        String getVersion();
        Long getId();
    }

}
```

### Output of `uname -a` or `ver`

Linux 5.4.0-47-generic #51-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 Maven home: /usr/share/maven Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-47-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@Sgitario would you be interested in looking into a fix for this one?

**Comment by Sgitario** [comment]
> @Sgitario would you be interested in looking into a fix for this one?

Yes!
