### ISSUE TITLE
Unleash 0.2.0 : isEnable for userId strategy does not work anymore

### ISSUE THREAD

**Issue by seb-noirot** [quarkusio/quarkus#21614]
### Describe the bug

I am trying to call method :
`isEnabled(String toggleName, UnleashContext context, boolean defaultSetting)`

New UnleashService does not override all the default method of Unleash class and thus the context is not propagated to the client.

Unleash interface:
`
default boolean isEnabled(String toggleName, UnleashContext context, boolean defaultSetting) {
    return this.isEnabled(toggleName, defaultSetting);
  }
`
This should be added to UnleashService:
`    
@Override
    public boolean isEnabled(String toggleName, UnleashContext context, boolean defaultSetting) {
        return client.isEnabled(toggleName, context, defaultSetting);
    }
`

### Expected behavior

Call unleash with userId strategy working.

### How to Reproduce?

Reproducer:

1. Create a feature flag with userIds strategy in unleash and add some user
2. Call isEnable for this feature flag with user
`  unleash.isEnabled("quarkus.unleash.test.with.userid", UnleashContext.builder().userId("test").build(), false);`
3. Will return false

**Comment by gsmet** [comment]
Thanks but you should create your issue there: https://github.com/quarkiverse/quarkus-unleash .

**Comment by seb-noirot** [comment]
Will do
