### ISSUE TITLE
OidcClient and OidcClientFilter crash when auth-server is unavailable

### ISSUE THREAD

**Issue by R4V3NN0** [quarkusio/quarkus#21638]
### Describe the bug

Im using `quarkus-oidc-client-filter` and `quarkus-oidc-client` to use an external REST-API which is secured with OAuth2. We are caching the data in our application, so we only need to call the API once a day, so that our application can still work, when the external API is down.

When the external Auth Server is down, our application crashes, because of an OidcClientException (see Actual Behavior). When our application starts and the auth server is down our application crashes at start.

It would be great if we could catch the exception, so that our application does not crash when the Auth-Server is down because we are not fully dependend on the external API.

### Expected behavior

The application should not crash at start, when the Auth Server is unavailable. When the method which calls the API is used, it should throw an Exception which can be catched to handle the error.

### Actual behavior

The application crashes at start, when the Auth-Server is unavailable. When I used `connection-delay`, the application hangs while starting until the delay time is over.

It throws the error message:
`Suppressed: io.quarkus.oidc.client.OidcClientException: OIDC server is not available at the 'http://localhost:9090' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'`

### How to Reproduce?

1. Create an Interface with the RestClient Annotation from Microprofile 
2. Add the `@OidcClientFilter` Annotation to use OAuth2 to authenticate
3. Set the property `quarkus.oidc-client.auth-server-url` to an invalid url for example `localhost:9090`
4. Start the application

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1237]

### Output of `java -version`

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### GraalVM version (if different from Java)

We are not using GraalVM at the moment

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by sberyozkin** [comment]
@R4V3NN0 I don't think `crash` is a correct qualification - it is not some NPE, OidcClient, by design attempts to acquire a token early, so if the configured URL is not pointing to the running provider it is not a bug either if the exception is reported.
That said, I thought it should work as you described, let me have a look

**Comment by sberyozkin** [comment]
@R4V3NN0 Can you please try `quarkus.oidc-client.early-token-acquisition=false` ?

**Comment by sberyozkin** [comment]
Never mind, you'd get an exception in this case as well.
Well, with `quarkus-oidc`, if `auth-server-url` is not reachable then an attempt is used to recover during the first request, may be something like that can be done with the OIDC client, will try to look a bit later

**Comment by R4V3NN0** [comment]
@sberyozkin thanks for your quick reply.
I added `quarkus.oidc-client.early-token-acquisition=false` to the properties and now the Exception has changed to
`io.quarkus.oidc.client.runtime.DisabledOidcClientException: 'Default' client configuration is not initialized`

**Comment by R4V3NN0** [comment]
@sberyozkin I think I found a solution.
I had to set `quarkus.oidc-client.early-tokens-acquisition=false` instead of `quarkus.oidc-client.early-token-acquisition=false` they seem identically, but there is a difference because in the first one it is `tokens` and in the second one `token`

**Comment by sberyozkin** [comment]
@R4V3NN0 oh sorry, I mistyped, so does it work as expected now for you ?

**Comment by R4V3NN0** [comment]
Yes, now its working as expected. Thanks for your help. I will close this issue.

**Comment by sberyozkin** [comment]
@R4V3NN0 Thanks, FYI, this property is doc-ed at https://quarkus.io/guides/security-openid-connect-client#use-oidcclient-in-microprofile-restclient-client-filter as well, may be it could've been more visible
