### ISSUE TITLE
Support for GZIP in GraphQL Services

### ISSUE THREAD

**Issue by funcbro** [quarkusio/quarkus#21642]
### Description

The GraphQL extension `io.quarkus:quarkus-smallrye-graphql` currently does not support GZIP compression of responses.

GZIP compression of GraphQL-responses should be configurable.

When looking at the smallrye implementation itself, it should be possible to implement a GZIP compression via a Servlet Response-Filter.
By using the quarkus extension though this possibility does not seem to exist.

**Comment by phillip-kruger** [comment]
Thanks for this issue. The Quarkus extension does not use servlet for the HTTP transport. But we should be able to add this to the vertx route. I'll have a look a.s.a.p.

**Comment by funcbro** [comment]
any news on this issue?

**Comment by phillip-kruger** [comment]
Also add support for https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/Compressed.java

**Comment by www-wanglong** [comment]
I just need it.

**Comment by gsmet** [comment]
If we are using a Vert.x route, shouldn’t this be already supported with @mkouba ’s work?

**Comment by mkouba** [comment]
> If we are using a Vert.x route, shouldn’t this be already supported with @mkouba ’s work?

I don't think so. IIRC the compression support was not added to Vert.x routes in general but into Reactive Routes, RESTEasy Reactive,  Undertow Servlet, RESTEasy Classsic and static resources. More specifically, if `quarkus.http.enable-compression=true` then we add the `Content-Encoding: identity` header that disables the compression to every response and the task of the support is to remove this header if appropriate.
