### ISSUE TITLE
gRPC: per-client interceptors

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#21648]
### Description

For gRPC services we now have `@GlobalInterceptor`s and interceptors registered for specific servies.
We likely need something similar for clients, so that a user can attach an interceptor to a specific client

CC @cescoffier @mkouba

**Comment by cescoffier** [comment]
Exactly, I found out that when implementing the metrics support.

**Comment by sukolenvo** [comment]
Hi, I am trying to register client interceptor for a specific service. My bean graph is something like:
```java
FooAuthClientInterceptor {
}

BeanA {
  @GrpcClient("foo")
  FooBlockingStub fooGrpcClient;
  
  @GrpcClient("bar")
  BarBlockingSub barGrpcClient;
}

BeanB {
  @GrpcClient("foo")
  FooBlockingStub grpcClient;
}

BeanC {
  @GrpcClient("foo")
  FooBlockingStub grpcClient;
}
```
Adding `@RegisterClientInterceptor(FooAuthInterceptor.class)` for every injection point seems a bit redundant (and could be easily forgotten for new services). Have you considered support for annotation for a type? Something like:
```java
@RegisterFor("foo")
FooAuthClientInterceptor {
}
```
Alternatively if interceptor list could be set in `GrpcClientConfiguration` that would also be nit.

**Comment by cescoffier** [comment]
You can register a global interceptor. See https://quarkus.io/guides/grpc-service-consumption#client-interceptors

**Comment by sukolenvo** [comment]
Yes, but isn't global interceptor will attach to `@GrpcClient("bar")` as well?

**Comment by michalszynkiewicz** [comment]
Yes it will.
You can work around it by delegating all interactions with a specific client to a single bean
