### ISSUE TITLE
Make name of OIDC session cookie configurable

### ISSUE THREAD

**Issue by funcbro** [quarkusio/quarkus#21641]
### Description

The OIDC session-cookie from the extension `io.quarkus:quarkus-oidc` has the fixed name `q_session`.

### Requirement:
The name of the cookie should be made configurable.

### Problem
* In our environment we have several applications running in a common domain across different stage-environments (development, testing, etc).
* The applications need to share the cookie between separatly deployed UI and quarkus-services via domain-configuration by `quarkus.oidc.authentication.cookie-domain` settings.
* Depending on the stage-environment different oidc providers might be used, so sharing of the cookie is not possible.
* Separation by domain configuration is not possible in this case as all applications share the same domain in the different environments.

In combination this results in authentication errors when switching from an application in one stage-environment to another.

**Comment by sberyozkin** [comment]
@funcbro It makes sense, but I'd like to retain `q_session` and `q_auth` qualifiers to ensure it can be traced that Quarkus has created these cookies.
At the moment I'm thinking of using the value of `quarkus.profile`, `%prod` is default, in this case nothing gets changed, if it is for example `staging` then the cookies will be named as `q_session_staging`, etc

Would that work for you ? Not sure right now an extra property is required.

**Comment by funcbro** [comment]
This seems appropriate and should work for our case 👍

**Comment by sberyozkin** [comment]
@funcbro After thinking more about it I thought adding a property to support qualifying the names would be a better solution, my orginal proposal to use the profile by default can have side-effects especially given that it is not guaranteed the prod profile will be named `prod` etc
