### ISSUE TITLE
Add support for more java.time as queryparams in resteasy-reactive 

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#21663]
### Description

#15451 added support for java.time.LocalDate as a query param.

I need support for other java.time.* types, e.g.:
* LocalTime
* LocalDateTime

Ideally, Resteasy Reactive would support every java.time type out of the box.

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/21675 should take of it.
