### ISSUE TITLE
Support Disabling Custom ConfigSource / Factory During Build Time

### ISSUE THREAD

**Issue by brianwyka** [quarkusio/quarkus#21678]
### Description

Support the ability to disable MicroProfile `ConfigSource` or SmallRye `ConfigSourceFactory` loading during build time.

The [docs](https://quarkus.io/guides/config-extending-support) say that the `ConfigSource` is not added in this phase unless annotated with `@StaticInitSafe`.  This is a good start, but only works for static init.  Would like a similar feature for build time.

#### Problem Trying To Solve
Currently, there is no way (that I know of), that I can prevent logic from within a config source from being executed during build time.

I have a custom `ConfigSourceFactory` which needs to make remote HTTP calls, which needs to wait until runtime to actually be executed.  It does still get executed at runtime, but it is redundantly executed at build time as well (with no added value).  The configuration values that are retrieved are stored in an in-memory cache local to the `ConfigSourceFactory` which does not survive from build time to run time.  This factory also sets up a scheduled job which periodically refreshes the configuration values from the remote server behind the scenes.

### Implementation ideas

ONLY consider `ConfigSource` or `ConfigSourceFactory`, etc... annotated with `@StaticInitSafe` or perhaps a new `@BuildTimeSafe` to be loaded and used for configuration resolution.  All other config sources are ignored (like they don't exist) during static init phase.  It seems like this would need some integration support from MicroProfile Config / SmallRye Config to work in totality.

**Comment by brianwyka** [comment]
I attempted a workaround suggested by @radcortez to have the custom config source as a `runtimeOnly` dependency, but this did not work either.

**Comment by radcortez** [comment]
There is another way to do this, with a Quarkus Extension via:
- https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/builditem/StaticInitConfigBuilderBuildItem.java
- https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/builditem/RunTimeConfigBuilderBuildItem.java

The way to implement it is to not use any of the auto registration features (with the ServiceLoader) and then use the build items to access the Config builder to manually register what you want. Here is an example: https://github.com/quarkiverse/quarkus-config-extensions/pull/48

I know it requires some additional setup, I may add support to register these builders from the app directly to not require the Extension in the future.

**Comment by brianwyka** [comment]
@radcortez, in my case, I don't have a setup with a "Quarkus Extension".  I simply have a library JAR with the service loader.  Will it still work?

**Comment by brianwyka** [comment]
AN initial test of this in a gradle setup without the `deployment` and `runtime` separation did not yield success.

**Comment by radcortez** [comment]
Yes, those items are only read and used in the context of a Quarkus extension. This is how you can write one: https://quarkus.io/guides/writing-extensions.

I know that this is a little inconvenient for now, but it is a way to achieve it. 

The problem is that we have so many different requests in how to customize the configuration that I feel that is not scalable anymore. Most likely, I'm just going to provide a way to expose the static and runtime config builders so it would be possible to customize each Config instance without relying on just a few selected pieces.
