### ISSUE TITLE
quarkus-container-image-jib should support jib.dockerClient.executable config

### ISSUE THREAD

**Issue by andrewazores** [quarkusio/quarkus#21677]
Jib allows configuration of the `dockerClient` that is invoked for loading the built image to local registry. This allows developers to explicitly build to `docker`, `podman`, `buildah`, etc. depending on what is available on their system as well as explicitly selecting one of them if multiple are present. This is analogous to the `quarkus.docker.executable-name` config property that is already supported, so I think it would make sense that the `jib` builder supports it as well.

> There is also the [`dockerClient.executable`](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#dockerclient-closure) config property that Jib supports which I think might be relevant here. If it is not then I think that a separate issue could be opened to add support for this to the `quarkus-container-image-jib` build plugin as `quarkus.jib.dockerClient.executable=/usr/bin/podman`. I use this in [Cryostat](https://github.com/cryostatio/cryostat/blob/5394bd47bf9aa911f157e5c60467e32b537a47b0/pom.xml#L577) to default the image builder to `podman`, but allow it to be overridden if some developer needs that to be `docker` (or probably `buildah` too - haven't tried that yet).

_Originally posted by @andrewazores in https://github.com/quarkusio/quarkus/issues/16326#issuecomment-978025344_

**Comment by geoand** [comment]
Thanks. I'll add this tomorrow

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21690 takes care of it
