### ISSUE TITLE
docker build fails for src/main/docker/Dockerfile.native

### ISSUE THREAD

**Issue by rafabene** [quarkusio/quarkus#2168]
I've used the command `docker build -t rafabene/myapp -f src/main/docker/Dockerfile.native .` and the docker build failed with

> Step 3/6 : COPY target/*-runner /work/application
When using COPY with more than one source file, the destination must be a directory and end with a /

**Comment by rafabene** [comment]
This happened when I changed the name of the artifactId and it generated two "runner" files. I'm not sure if this should be fixed or documented.

**Comment by geoand** [comment]
Indeed, in this case you would have to do `mvn clean package ....` before creating the Docker image.
I think that changing the `COPY` command would probably create more problems than it would solve. Perphaps in the comments added to the docker file we should include the `mvn clean...` command?
