### ISSUE TITLE
Find a generic uniform way to filter extensions across platforms based on metadata

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#21697]
### Description

Currently, in the extensions metadata, we have random data used by different tools for different purposes, it would not be relevant/performant to make it all available for searching.

We should only limit this to the metadata fields which are relevant to be searched from in a `key:value` way:
`status:stable,experimental`, `xxx-support:supported`, `origin:platform`, `origin:other`, `category:web`, `category:web,data`, `xxx-support:any`, `extra:codestart`

Possible filter values would be `any` (exists),  or some specific value (i.e `xxx-support:any` would check that the field is defined to any value)

We should keep a way to search in all the values (like we currently do with `tags:...` in code.quarkus.io): `tags:platform,supported` 

Maybe we should just be stupid and "hardcode" the list of available fields in the devtools (and make it evolve): 
```
origin, *-support, category, status, extra, keywords
```

We would also need a way to list the available fields and values to be used for searching.

`origin` and `extra` don't exist yet and would need to be added.

**Comment by maxandersen** [comment]
> Maybe we should just be stupid and "hardcode" the list of available fields in the devtools (and make it evolve):

when you say "devtools" what do you mean here ? cli and plugins already get the full platform data so they at least not for performance reasons needs to hardcode list of fields ?

**Comment by ia3andy** [comment]
@maxandersen 

> > Maybe we should just be stupid and "hardcode" the list of available fields in the devtools (and make it evolve):
> 
> when you say "devtools" what do you mean here ? cli and plugins already get the full platform data so they at least not for performance reasons needs to hardcode list of fields ?

I mean the devtools-common java module, when I talk about perf, I am not talking about network here, but search performance. It's true that in the CLI it's less relevant as you don't get instant results while typing, but still searching across a large set of data can be resource demanding...
