### ISSUE TITLE
Quarkus throws warnings about quarkus.rest-client configuration after #21530 

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#21698]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/21530 introduced warnings when using quarkus-rest-client (both in JVM and native mode).

### Expected behavior

Quarkus shouldn't through warnings (like it did before https://github.com/quarkusio/quarkus/pull/21530)

### Actual behavior

Quarkus throws warnings like the following both in JVM and native mode:

```
04:09:13,334 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.restClientBaseUriConfigKey.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,357 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,358 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.GouvFrGeoApiClient".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,360 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.loopback.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,361 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestClientInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,367 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestClientWithFaultToleranceInterface".url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,368 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client."io.quarkus.it.rest.RestInterface".scope" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
04:09:13,370 WARN  [io.qua.config] Unrecognized configuration key "quarkus.rest-client.restClientConfigKey.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### How to Reproduce?

```
./mvnw verify -f integration-tests/pom.xml -pl main
```

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

3f0ffd4c98b672f7fbc5ab63c10d0456a213f040

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by TomasHofman** [comment]
OK, that would be likely caused by me removing the client configuration map from the `RestClientsConfig` ConfigRoot class, so part of the schema is now loaded via ConfigRoot and part is loaded directly from `Config`.

I could remove the ConfigRoot altogether and read everything from `Config`. That would probably make it stop complaining, but there will be no automatic docs generation then.

Or I could make the clients configuration map part of the ConfigRoot again, even though we would actually ignore it and still read the clients configs directly.

**Comment by radcortez** [comment]
Yes, just add the map to the ConfigRoot and we ignore it :)
