### ISSUE TITLE
google-cloud-graalvm-support dependency is not reolved from BOM after updating from 2.4.1 to 2.5.0

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#21699]
While updating Quarkus from 2.4.1 to 2.5.0, the `com.google.cloud:google-cloud-graalvm-support` dependency is not resolved from BOM anymore.

```
* What went wrong:
Execution failed for task ':my-project:compileKotlin'.
> Could not resolve all dependencies for configuration ':my-project:quarkusDependency'.
   > Could not find com.google.cloud:google-cloud-graalvm-support:.
     Required by:
         project :my-project
```

Build tool: Gradle 6.8.1

**Comment by loicmathieu** [comment]
Can you check that it's not a transient issue ?
It seems Gradle is not able to download this library: https://search.maven.org/artifact/com.google.cloud/google-cloud-graalvm-support

If it's not a transient issue, can you provide a reproducer ?

**Comment by Shpota** [comment]
@loicmathieu it is not a transitive issue.

Reproducer:
1. Generate a Gradle project using [code.quarkus.io](https://code.quarkus.io)
2. Add `implementation 'com.google.cloud:google-cloud-graalvm-support'` into the `buuld.gradle` file.
3. Build the project using `./gradlew build`

AR: 
```
> Task :quarkusGenerateCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusGenerateCode'.
> Could not resolve all dependencies for configuration ':quarkusDependency'.
   > Could not find com.google.cloud:google-cloud-graalvm-support:.
     Required by:
         project :
```

**Comment by loicmathieu** [comment]
OK, so you manually add this dependency without the version and previously the Quarkus BOM contains the version and now it didn't anymore.

I'm not sure which BOM is included by default but I think at some moment code.quarkus.io switch from the Platform BOM to the Quarkus core BOM.
For the com.google.cloud:google-cloud-graalvm-support to use a managed version from the Quarkus BOM you should switch to the Platform BOM (change the BOM groupId from io.quarkus to io.quarkus.platform I think) or add the Google Cloud Service BOM.
If you use some Google Cloud specific library, I strongly suggest to use the extensions from https://github.com/quarkiverse/quarkus-google-cloud-services

If you're only interested by the usage of the com.google.cloud:google-cloud-graalvm-support you can also manage the version by yourself.

**Comment by Shpota** [comment]
Thanks @loicmathieu. For me it doesn't really mater where the dependency comes from. I only want GraalVM APIs to work. What would be best way to achieve this?

I thought, if Quarkus manages the version of `google-cloud-graalvm-support` in its BOM, it means it is fully compatible with the Quarkus version I use. Is it a wrong assumption?

**Comment by loicmathieu** [comment]
Of you don't use any extensions that needs it, there is no point of having the version managed by Quarkus. 

So if you don't use any of the extensions from the Quarkivese Google Cloud Services project you better manage the version of the library by yourself.

**Comment by gsmet** [comment]
Two things:
- with the new Quarkus Platform model, the Google Cloud Services BOM is not included by default anymore: you need to add an additional BOM: https://search.maven.org/artifact/io.quarkus.platform/quarkus-google-cloud-services-bom/2.6.1.Final/pom 
- AFAICS, the artifact is now named `com.google.cloud:native-image-support`
