### ISSUE TITLE
Add support for @EndpointInject in Camel Core extension

### ISSUE THREAD

**Issue by ricardozanini** [quarkusio/quarkus#2170]
Hi!

It seems that the extension `camel-core` is not registering the `org.apache.camel.ProducerTemplate` into the context. The annotation `@EndpointInject` nor `@Produce` is working. To have the `ProducerTemplate` injected into the context, one have to create manually using `CamelContext`:

```java
@ApplicationScoped
public class CamelLifecycle {

    @Inject
    CamelContext context;
    
    private ProducerTemplate producerTemplate;

    @Produces
    public ProducerTemplate producerTemplate() {
        producerTemplate = context.createProducerTemplate();
        return producerTemplate;
    }   
    
    @PreDestroy
    public void cleanUp() throws Exception {
        if(producerTemplate != null) {
            this.producerTemplate.stop();
        }
    }
}
```

This way, the producer can now be used anywhere the application:

```java
@Path("/fruits")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class FruitsResource {

    @Inject
    ProducerTemplate producer;
    
    @GET
    public Response getFruits() {
        final List<Fruit> fruits = producer.requestBody("direct:getFruits", null, Fruit.class);
        return Response.ok(fruits).build();
    }
}
```

Proposal: add support for `EndpointInjection` in a similar way that  the [Spring Framework](http://camel.apache.org/spring-boot.html) does.

Ideally the context could provide:

- `TypeConverter`
- `ConsumerTemplate`
- `ProducerTemplate`

If the maintainers agree, I  can send a PR for this one.

Cheers!

**Comment by davsclaus** [comment]
I assume you have tried with the standard `@Inject` annotation? And it didnt work and so you had to add your own producers for it?

But yeah it would be good to have the other Camel annotations supported OOTB as `@EndpointInject` can configure a few more options than @Inject can do. But it would also be nice to have @Inject work with the these types you mention above.

You are surely welcome to submit a PR

**Comment by ricardozanini** [comment]
Hi @davsclaus! Good to see you here :p

>> I assume you have tried with the standard @Inject annotation? And it didnt work and so you had to add your own producers for it?

yes, the `@Inject` is also not working. I'm thinking about to submit a PR to first add the support for these through injection:

- TypeConverter
- ConsumerTemplate
- ProducerTemplate

Doing something similar to this in the camel extension:

```
 @Inject
    CamelContext context;
    
    private ProducerTemplate producerTemplate;

    @Produces
    public ProducerTemplate producerTemplate() {
        producerTemplate = context.createProducerTemplate();
        return producerTemplate;
    }   
    
    @PreDestroy
    public void cleanUp() throws Exception {
        if(producerTemplate != null) {
            this.producerTemplate.stop();
        }
    }
```
So users could have these classes available right away in the Registry.

Afterwards I can prepare another PR to support `@EndpointInject`.

wdyt?

**Comment by davsclaus** [comment]
Yeah good idea

**Comment by gsmet** [comment]
@lburgazzoli I let you move that one to the Camel issue tracker if you wish.

Closing.
