### ISSUE TITLE
Maven Quarkus plugin create an apps pointing to the wrong version

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#21712]
### Describe the bug

If I create an app pointing to Quarkus 2.2.3.Final as the [documentation](https://quarkus.io/version/2.2/guides/deploying-to-openshift) says

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.2.3.Final:create \                              
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=openshift-quickstart \
    -DclassName="org.acme.rest.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions="resteasy,openshift"
```

I expected to have a `pom.xml`  pointing to `2.2.3.Final` however is pointing to `2.5.0.Final`

**Comment by mkouba** [comment]
It seems that the platform version used is always the most recent version of Quarkus. However, you can just change the `quarkus.platform.version` property after the project skeleton is created.

I didn't find a way to explicitly set the platform version though.

CC @aloubyansky

**Comment by aloubyansky** [comment]
Right, the decision was made to recommend the version currently promoted by the registry.quarkus.io and if the registry is not available it would fallback to the version of the plugin.

Using the Maven plugin you have a couple of options:
* disable the registry client with `-DquarkusRegistryClient=false` on the command line
* specify the version explicitly by adding `-DplatformVersion=XXX` argument to the command line

FYI @maxandersen

**Comment by mkouba** [comment]
> * specify the version explicitly by adding `-DplatformVersion=XXX` argument to the command line

Shouldn't we document this one?
