### ISSUE TITLE
PanacheEntityBase.persist() silently fails outside a transaction

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#2172]
If you call this method outside a transaction the entity is not added, and no error is thrown. I would expect one or the other, but not silent failure.

**Comment by FroMage** [comment]
Really? How can that be? @Sanne is that normal behaviour of `EntityManager.persist`?

**Comment by Sanne** [comment]
No it's not "normal" but it can be setup to do such weird stuff. It's all under control of the integrator layer, so I guess there's something odd in how it's being bound to the context.

I would suspect it relates with some workarounds that people have introduced to automatically start a TX when it's missing? If it's automagically started but never committed then this would be the expected outcome.. 

I'll have a look to try tracing what's going on...

**Comment by FroMage** [comment]
Thanks.

**Comment by FroMage** [comment]
@Sanne up?
