### ISSUE TITLE
native image fails to start due to missing libfreetype.so.6 library

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#21729]
### Describe the bug

Running a quarkus native application (2.5.0.Final) fails with following error at startup:

```log
./application: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
```

With 2.4.2.Final it was working correctly

### Expected behavior

The application should just start.

### Actual behavior

The application can not start.

In the application.properties we have following settings for the native build:

```properties
quarkus.jib.base-native-image=quay.io/quarkus/quarkus-micro-image:1.0
quarkus.native.additional-build-args=\
  -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED
```

as build image we use `quay.io/quarkus/ubi-quarkus-native-image:21.3-java17`

and the build.gradle has following dependendies:

```gradle
plugins {
    id 'java'
    id 'io.quarkus'
    id 'com.github.ben-manes.versions'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
    implementation 'io.quarkus:quarkus-liquibase'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-scheduler'

    implementation 'org.apache.commons:commons-lang3'
    implementation 'io.quarkiverse.hibernatetypes:quarkus-hibernate-types:0.2.0'

    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testCompileOnly "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

    compileOnly 'org.osgi:osgi.annotation:8.0.1'
    testCompileOnly 'org.osgi:osgi.annotation:8.0.1'

    testImplementation 'at.favre.lib:bcrypt:0.9.0'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}

group 'com.qumea'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

quarkusDev {
    workingDir = rootProject.projectDir
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
    options.compilerArgs << '-Xlint:all'
    options.compilerArgs << '-Xlint:-exports'
    options.compilerArgs << '-Xlint:-requires-automatic'
    options.compilerArgs << '-Xlint:-processing'
    options.deprecation = true
}

compileTestJava {
    options.encoding = 'UTF-8'
}

quarkusBuild {
    nativeArgs {
        containerBuild = System.env.BITBUCKET_BRANCH == null
        builderImage = "quay.io/quarkus/ubi-quarkus-native-image:21.3-java17"
    }
}
```

### Output of `java -version`

Java 17.0.1

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3-java17

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
The runtime image does not provide libfreetype.so.6 by default (to save space). Do you know which part of your app needs it?

**Comment by joggeli34** [comment]
No, I have no idea where it is used. The app is more or less a simple CRUD-Application. It must be somewhere in the dependencies changed from quarkus 2.4.2.Final to 2.5.0.Final.

**Comment by joggeli34** [comment]
Comparing the dependencies, I see that the quarkus-liquibase has now a dependency to quarkus-awt, which was not before.
I assume that awt could use the libfreetype, but it is just a guess.

```
+--- io.quarkus:quarkus-liquibase -> 2.5.0.Final
|    +--- io.quarkus:quarkus-core:2.5.0.Final (*)
|    +--- org.liquibase:liquibase-core:4.6.1
|    +--- org.yaml:snakeyaml:1.29
|    +--- io.quarkus:quarkus-jaxb:2.5.0.Final
|    |    +--- io.quarkus:quarkus-core:2.5.0.Final (*)
|    |    +--- io.quarkus:quarkus-jaxp:2.5.0.Final
|    |    |    \--- io.quarkus:quarkus-core:2.5.0.Final (*)
|    |    +--- io.quarkus:quarkus-awt:2.5.0.Final
|    |    |    \--- io.quarkus:quarkus-arc:2.5.0.Final (*)
|    |    +--- org.glassfish.jaxb:jaxb-runtime:2.3.3-b02 (*)
|    |    \--- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final
|    +--- io.quarkus:quarkus-agroal:2.5.0.Final (*)
|    +--- io.quarkus:quarkus-datasource-common:2.5.0.Final
|    \--- io.quarkus:quarkus-narayana-jta:2.5.0.Final (*)
```

**Comment by cescoffier** [comment]
Yes, that's probably it. 
So, the approach would be to extend the runtime image to add the lib. Something like https://github.com/quarkusio/quarkus-quickstarts/blob/development/awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-distroless. 

We should document that.

**Comment by maxandersen** [comment]
its unfortunate if we now require bundling of those files if not actually needed :/ 
@galderz you looked at this earlier. ideas?

**Comment by galderz** [comment]
> its unfortunate if we now require bundling of those files if not actually needed :/ @galderz you looked at this earlier. ideas?

@Karm is working on [improving it](https://github.com/quarkusio/quarkus/pull/20850#issuecomment-981527941).

**Comment by wabrit** [comment]
I presume any quarkus native app which relies on the liquibase extension is not going to run under Quarkus 2.5.x until this issue is fixed? Is there a workaround in the meantime?

**Comment by vladimirfx** [comment]
Workaround is build your own base image with needed libs. Actually is what we do in our company. 
And yes, for applications that not using fonts or other graphics elements it is just annoying.

**Comment by Karm** [comment]
@wabrit @vladimirfx The fix in #20850 is pretty close to getting merged now :+1:

**Comment by Karm** [comment]
@wabrit @vladimirfx Fixed version is up and about: https://mvnrepository.com/artifact/io.quarkus/quarkus-core/2.6.0.CR1

**Comment by vladimirfx** [comment]
Thanks, I will check today

**Comment by vladimirfx** [comment]
Checked on 2.6.0.CR1 - works fine.
Thank you!

**Comment by joggeli34** [comment]
I checked it out on 2.6.0.CR1 too. Works greate.
Thanks a lot!
