### ISSUE TITLE
Avoid to mention where the application is listening at the end of Maven creation

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#2173]
When a new quarkus project is created using the Maven plugin it always prints:

`[INFO] Your application will be accessible on http://localhost:8080`

which comes from here: https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java#L312

It's not always true because the user could haven't created the project for a REST-based application or exposing service on that endpoint (i.e. I was creating an application based on Kafka).
Should we avoid to mention that?

**Comment by Dufgui** [comment]
I check the template code, we have just one template:
https://github.com/quarkusio/quarkus/blob/b11c1261626376c59744389551061174abae5d3d/devtools/common/src/main/java/io/quarkus/cli/commands/CreateProject.java#L127

This one is based on rest, so it seems, if I don't miss anything, it's always create by default a listen on port 8080.

So we can close it @cescoffier

**Comment by geoand** [comment]
Closing this as with the Quarkus CLI this is out of date
