### ISSUE TITLE
Adding an extension should add the dependencies

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#2174]
From the Kafka related guide I read:

> Eclipse Vert.x is also required as the Kafka connector relies on Vert.x

If I try to add the `quarkus-smallrye-reactive-messaging-kafka`, the related Vert.x isn't added as well.
Shoud the add extension command adds the dependencies for an extension as well?

**Comment by stuartwdouglas** [comment]
This should be handled as a transitive maven dependency.

**Comment by gsmet** [comment]
I see `vertx-core` as a transitive dependency of `smallrye-reactive-messaging-kafka`.

@ppatierno what's the issue exactly?

**Comment by ppatierno** [comment]
@gsmet @stuartwdouglas no issues around dependencies you are right, just the pom.xml is not updated with the other extensions, just to clarify the user what have you added. Btw it doesn't happen with "normal" maven dependencies as well when there are some transitive ones so maybe it doesn't make sense to have "transitive extensions" added to the pom.xml. I would close this issue then.
