### ISSUE TITLE
EntityManager doesn't work for Kotlin scheduler

### ISSUE THREAD

**Issue by renandeandradevaz** [quarkusio/quarkus#2175]
In this issue:
https://github.com/quarkusio/quarkus/issues/2102
The user fandiluo reported a problem with scheduler on quarkus.

The user @mkouba sugested to use @ActivateRequestContext annotation.

I used it and the problems kept happening.

The codes and erros below:

When I do with @singleton:

```
@Singleton
@ActivateRequestContext
open class Scheduler {

	@Inject
	lateinit var em: EntityManager

	@Transactional
	@Scheduled(every = "10s")
	@ActivateRequestContext
	fun createGift() {
		val gift = Gift()
		gift.name = "test"
		em.persist(gift)
	}
}
```
I get this error:

`Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped`

When I use @ApplicationScoped:

```
@ApplicationScoped
@ActivateRequestContext
open class Scheduler {

	@Inject
	lateinit var em: EntityManager

	@Transactional
	@Scheduled(every = "10s")
	@ActivateRequestContext
	fun createGift() {
		val gift = Gift()
		gift.name = "test"
		em.persist(gift)
	}
}
```
I get this error:

`Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped beans must declare a non-private constructor with no parameters: CLASS bean [types=[org.acme.scheduling.Scheduler, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.scheduling.Scheduler]`

When I use with internal modifier, I got this:

```
@ApplicationScoped
open class Scheduler  {

	@Inject
	lateinit internal var em: EntityManager

	@Transactional
	@Scheduled(every = "10s")
	fun createGift() {
		val gift = Gift()
		gift.name = "test"
		em.persist(gift)
		println("test")
	}
}

 kotlin.UninitializedPropertyAccessException: lateinit property em has not been initialized]
```

If I try with a constructor, this way:

```
@ApplicationScoped
open class Scheduler @Inject constructor(@Inject internal var em: EntityManager) {....}
```

I got:

`Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped beans must declare a non-private constructor with no parameters: CLASS bean [types=[org.acme.scheduling.Scheduler, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.scheduling.Scheduler]`

Another try, optional field:

```
@ApplicationScoped
open class Scheduler @Inject constructor(@Inject internal var em: EntityManager? = null) {....}
```

Error:

```
Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type int and qualifiers [@Default]
```

I'm using quarkus 0.13.3 version with Kotlin.

Can someone help me?

Thanks!

**Comment by mkouba** [comment]
So the reason why the `@ActivateRequestContext` interceptor binding does not work is that kotlin function is translated to a `final` method by default. CDI would fail during bootstrap but we've decided to more lenient and simply ignore the final methods. I do agree that we should at least log a warning.

Anyway, if you replace `fun createGift()` with `open fun createGift()` everything should work as expected.

**Comment by renandeandradevaz** [comment]
Hi @mkouba 
The solution with **open fun** together with **@ActivateRequestContext** works perfectly.

Thanks!
