### ISSUE TITLE
Is it possible to connect in multiple Artemis MQ broker instances?

### ISSUE THREAD

**Issue by saulocn** [quarkusio/quarkus#21752]
### Description

I'm sorry if this isn't the best channel to ask but, in case of primary and secondary Artemis broker instance. Is there any way to connect in both instances to keep connection if primary be down?

### Implementation ideas

Maybe the `quarkus.artemis.url` property be setted as an list comma separated.
Something like:
```
quarkus.artemis.url=tcp://localhost:61616,tcp://localhost:61617
```
Something like `kafka.bootstrap.servers`

**Comment by geoand** [comment]
cc @middagj

**Comment by middagj** [comment]
You can leverage the full potential of the Artemis url schema, e.g.
```
(tcp://myhost:61616,tcp://myhost2:61616)?reconnectAttempts=5
```
from [Artemis docs - clusters - configurating a cluster connection](https://activemq.apache.org/components/artemis/documentation/latest/clusters.html#configuring-a-cluster-connection)

Note that Artemis clustering by default connects to one and then uses load balances via Artemis

>With Apache ActiveMQ Artemis client-side load balancing, subsequent sessions created using a single session factory can be connected to different nodes of the cluster. This allows sessions to spread smoothly across the nodes of a cluster and not be "clumped" on any particular node.

[Artemis docs - clusters - client side load balancing](https://activemq.apache.org/components/artemis/documentation/latest/clusters.html#client-side-load-balancing)

You can disable that by setting `useTopologyForLoadBalancing=false` on the url param.

If you configure it via High Availbility options of Artemis then it could be that you need to enable `ha` as well via the url params. I couldn't find it that easily in the docs or code. Hope this helps you in the right direction.
