### ISSUE TITLE
Kotlin Debug Coroutine Monitor Problem

### ISSUE THREAD

**Issue by mhmtszr** [quarkusio/quarkus#21757]
### Describe the bug

I want to see current coroutine statuses on the Intellij Idea Coroutine monitor screen, but I can't. I added all the dependencies for coroutines like kotlinx-coroutines-core still I can't see any information about current coroutines. Could you please help me? Example Code:

```
@GET
@Produces(MediaType.TEXT_PLAIN)
suspend fun hello(): String =
   withContext(MDCContext()) {
       async {
           delay(500)
            hello world"
       }.await()
   }
```

And this is what I see in the Intellij Idea Coroutine monitoring screen:
![image](https://user-images.githubusercontent.com/35079195/143732164-5f9ff5c0-f1b9-4d43-9210-ac8514e9c735.png)

### Expected behavior

I want to see current using coroutines status(such as suspended or running)

### Actual behavior

Idea say that "No coroutine information found"

### How to Reproduce?

Debug any suspend method.

### Output of `java -version`

15.0.2

### Quarkus version or git rev

2.5.0(latest)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.3

**Comment by geoand** [comment]
This isn't a Quarkus issue
