### ISSUE TITLE
The interceptor has added parameters and cannot be intercepted

### ISSUE THREAD

**Issue by janyyy** [quarkusio/quarkus#21765]
### Describe the bug

```java
@InterceptorBinding
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface Log {


    String value() default "";
}
```

```java
@Slf4j
@Log
@Interceptor
@Priority(Interceptor.Priority.PLATFORM_BEFORE + 200)
public class LogInterceptor {

    @AroundInvoke
    Object invocation(InvocationContext context) throws Exception {
        // 获取注解参数
        Method method = context.getMethod();
        String value = method.getAnnotation(Log.class).value();
        log.info("===============" + value + "=============================");
        return context.proceed();
    }
}
```

```java
 @Log(value = "1111111")
    @GET
    @Operation(summary = "查询包裹签收信息列表")
    public Response queryList(@BeanParam ParcelReceiveInfoQuery parcelReceiveInfoQuery) {
        return Response.ok(parcelReceiveInfoService.queryList(parcelReceiveInfoQuery)).build();
    }
```

I customized an annotation, and a value string is generated inside the annotation. When the value is not assigned, the interceptor defined by the program can enter the corresponding method of @AroundInvoke. When I use annotations to assign values to the Resource, the interceptor fails.

### Expected behavior

After the annotation declares the parameters and executes, the interceptor runs normally

### Actual behavior

Interceptor does not execute

### Output of `java -version`

11.0.13

### GraalVM version (if different from Java)

21.3.0

### Quarkus version or git rev

2.4.2.Final/2.5.0Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by mkouba** [comment]
@janyyy Well, the `Log#value` is a _binding member_ which means that it's used during interceptor resolution. In other words, the `LogInterceptor` will only be bound to a bean/method which declares `@Log("")`. If you need to ignore the value during resolution then annotate the member with `@javax.enterprise.util.Nonbinding`.

A tip for the next time ;-): we usually need more information, at least the description of _"the interceptor fails"_, ideally a simple reproducer.

**Comment by janyyy** [comment]
Thank you very much

**Comment by mkouba** [comment]
> Thank you very much

yw
