### ISSUE TITLE
json format issue with quarkus 2.5.0.Final at patch request

### ISSUE THREAD

**Issue by RehamAboelyazied7** [quarkusio/quarkus#21768]
### Describe the bug

I was using quarkus 2.4.1.Final and implemented a patch request with quarkus-resteasy-jackson 
now, I need to update to 2.5.0.Final but when I try updating it, the format of response is not right and I get an error parsing JSON data.

### Expected behavior

the expected was to have the same json response as before

### Actual behavior

 the response code is 200 as before but with miss match json format - error to parse json  

### How to Reproduce?

find sample project for the problem: https://github.com/RehamAboelyazied7/mongo-with-quarkus

**Comment by geoand** [comment]
Can you please attach a sample project the exhibits the problem you mention?

**Comment by RehamAboelyazied7** [comment]
@geoand I updated it with github repository link  for sample

**Comment by geoand** [comment]
I see that your reproducer depends on another service that is not included. 

So I used what you specified in the issue:

```java
@Path("/testPath")
public class MyResource {
    @PATCH
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public Response myPatch(@PathParam("id") String id){
      return Response.ok(id).build();
   }
}
```

and it worked as expected

**Comment by RehamAboelyazied7** [comment]
I checked that https://github.com/quarkusio/quarkus/issues/21818 and I think it's the same issue

**Comment by geoand** [comment]
Very interesting.

Let's close this then since the underlying issue has already been fixed.

Once 2.5.1 is out, please give it a try and comment if the issue has not been fixed
