### ISSUE TITLE
Panache reactive shouldn't use Uni.combineAll in a persist

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#21772]
### Describe the bug

See [AbstractJpaOperations#persist(Stream)](https://github.com/quarkusio/quarkus/blob/ebd6d377ea432bdc13bed47b72cb46387a7f9bbe/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/runtime/AbstractJpaOperations.java#L96)

The Hibernate Reactive session cannot be used this way or it might lead to errors that are hard to debug.
Instead, the persist operations should be chained  so that the execution is sequential.
See the [documentation on GitHub](https://github.com/hibernate/hibernate-reactive/blob/main/documentation/src/main/asciidoc/reference/introduction.adoc#sessions-and-vertx-contexts):
> The session is not thread-safe (or "stream-safe"), so using it across different threads (or reactive streams) may cause bugs that are extremely hard to detect

**Comment by gavinking** [comment]
And also: Hibernate Reactive already has a `persist()` that accepts multiple arguments so Panache should use it.
