### ISSUE TITLE
Don't autodetect Avro serde in case multiple Avro serdes are present on classpath

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#21782]
### Describe the bug

The SmallRye Reactive Messaging Kafka support for autodetection behaves weirdly in case multiple Avro serdes are present on classpath. The autodetection algorithm will just pick one of those serdes in an opaque way. It really should either avoid autodetection entirely, so that the application fails with missing configuration during startup, or even fail the build entirely.

### Expected behavior

Predictable serde autodetection outcome in case multiple serdes are present.

### Actual behavior

Seemingly random serde autodetection outcome in case multiple serdes are present.

**Comment by knutwannheden** [comment]
For the Avro use case, where most channels will be using the generic Avro serializer (specific to the schema registry implementation), I think that it would be useful with an explicit config property like `quarkus.reactive-messaging.kafka.schema-registry.compatibility-mode` (which can be set to `auto`, `confluent`, `apicurio1`, or `apicurio2`). This would allow the extension to correctly set the Avro-specific config for the channels.

With this approach the extension could fail the build when it detects multiple Avro serdes and instruct the user to set this config property.

@Ladicek What do you think about this proposal?

**Comment by Ladicek** [comment]
I still don't want configuration for autodetection. It's a slippery slope and we'll eventually end up creating an alternative configuration system for SmallRye Reactive Messaging. Autodetectoin should work well for the most common 80% of cases, and if you need something advanced, you should just configure SmallRye Reactive Messaging directly.
