### ISSUE TITLE
Using @Transactional on a method annotated with @Incoming should add @Blocking if not present

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#21795]
### Description

When a method annotated with `@Incoming` is also annotated with `@Transactional`, it should automatically add `@Blocking` is no _blocking_ annotations (from SmallRye common and Reactive Messaging) are used. 

### Implementation ideas

1. Detect that configuration
2. Add the annotation
3. Implement tests
4. Document

**Comment by geoand** [comment]
Didn't @stuartwdouglas have something like this as well?

**Comment by stuartwdouglas** [comment]
It was specific to RESTEasy Reactive

**Comment by geoand** [comment]
Ah, OK

**Comment by mkouba** [comment]
> It was specific to RESTEasy Reactive

Maybe this should be implemented in the `quarkus-narayana-jta` instead? It would not hurt to add `@Blocking` on every method annotated with `@Transactional`, or?

**Comment by cescoffier** [comment]
+1 to @mkouba proposal. It would cover most cases.

**Comment by stuartwdouglas** [comment]
How would we actually implement that though, as @Blocking is processed by lots of different extensions.

**Comment by cescoffier** [comment]
That is a good point. Even if it adds the `@Blocking` annotation it would need to update the index before the other extensions look for the beans. I think, for now, we would need to do it in each individual extension.

**Comment by mkouba** [comment]
> How would we actually implement that though, as @Blocking is processed by lots of different extensions.

All those extensions can leverage the ArC transformers API, i.e. instead of looking at the index consumer the `io.quarkus.arc.deployment.TransformedAnnotationsBuildItem` and then analyze the result of `TransformedAnnotationsBuildItem.getAnnotations(AnnotationTarget)`.
