### ISSUE TITLE
Kubernetes resources(yml/json) not generated

### ISSUE THREAD

**Issue by nragon** [quarkusio/quarkus#21791]
### Describe the bug

Our application is using Kubernetes extension to generate all required resources however, when packaging it, no resources are generated.

### Expected behavior

When executing:

`mvnw clean package -Dresource.provider=kubernetes`

resources should be generated (kubernetes.yml and kubernetes.json).

### Actual behavior

When executing:

`mvnw clean package -Dresource.provider=kubernetes`

resources are not generated.

### How to Reproduce?

1. Create a project with 2 level modules
 >root
 >>runtime
>>>rest (kubernetes extension is here, activated by a profile)

2. Run mvnw clean package with the profile name to be activated

### Output of `uname -a` or `ver`

Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

[DEBUG] [io.quarkus.kubernetes.deployment.KubernetesProcessor] Generated the Kubernetes manifests: 'kubernetes.yml,kubernetes.json' in '/mnt/d/test/runtime/rest/target/rest/kubernetes'

This is an output, however, nothing is written.

**Comment by geoand** [comment]
Thanks for reporting.

First of all, where does `-Dresource.provider=kubernetes` come from? Why are you using it?

Second what does the file system look when you performed the package stage? I'm basically interested in the target directory.

Finally, any chance you could attach a project that exhibits this behavior?

**Comment by nragon** [comment]
@geoand, can't share the entire codebase, trying to replicate in a different project with same structure(not lucky so far).

**Comment by nragon** [comment]
Closing since we cannot reproduce it on a smaller project. Will reopen if the detect it on other projects with identical structure. Thanks

**Comment by geoand** [comment]
Thanks for checking!
