### ISSUE TITLE
OpenAPI JSON property naming support

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#21808]
### Describe the bug

Currently Quarkus OpenAPI extension didn't automatically use the JSON property naming strategy used by the Quarkus Object Mapper.

If you use an `ObjectMapperCustomizer` to set the property naming strategy to `SNAKE_CASE` for example, this is not honored by OpenAPI.

Discussions can be found here on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/OpenAPI.20don't.20honor.20ObjectMapper.20.20naming.20strategy

~To workaround this limitation we can use the `mp.openapi.extensions.smallrye.property-naming-strategy` setting but using it leads to the following build exception:~

**UPDATE** : as @tsuginodan pointed out I mis-configured  `mp.openapi.extensions.smallrye.property-naming-strategy`, setting `mp.openapi.extensions.smallrye.property-naming-strategy=com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy` worked around the issue

~The only~ An other usable workaround is to annotate each JSON object with a `@JsonNaming` annotation.

### Expected behavior

Quarkus OpenAPI extension reuse the Quarkus default ObjectMapper or at least it's configured property naming strategy.

An other solution would be for the `mp.openapi.extensions.smallrye.property-naming-strategy` setting to work in Quarkus.

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1348]

### Output of `java -version`

openjdk version "17" 2021-09-14

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by akaisuicchi** [comment]
Hello @loicmathieu ,
following your workaround, could you try this?
```properties
mp.openapi.extensions.smallrye.property-naming-strategy=com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy
```
Yes, I changed the last dot (.) with a dollar sign ($). Worked for me.

I found the same [issue](https://github.com/smallrye/smallrye-open-api/issues/712) and an example [here](https://github.com/smallrye/smallrye-open-api/pull/788/files#diff-26103c352cb3fa2119513cb6446930a3fb4d8c035bc95500b800bc2e628fe165)

---

That work for now, but as you said, having Quarkus reuse an existing ``ObjectMapperCustomizer`` would be better.

**Comment by loicmathieu** [comment]
@tsuginodan well, this is embarassing ;) I should have remember that nested class as accesible via `$` not `.` :(

**Comment by phillip-kruger** [comment]
Please reopen if this is still an issue.
