### ISSUE TITLE
Create Quarkus organization on Docker Hub

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2180]
The builder image used for native mode is pulled from @stuartwdouglas' Docker Hub account:

    Unable to find image 'swd847/centos-graal-native-image-rc12:latest' locally
latest: Pulling from swd847/centos-graal-native-image-rc12

I think it'd be better to pull it from a "quarkus" organization there or on Quay, so to give a more stream-lined project appearance.

**Comment by Sanne** [comment]
hi @gunnarmorling , what version is that? AFAIK we moved to Quay a while back.

**Comment by gunnarmorling** [comment]
Ah yes, you are right. It's coming from quay as of 0.13.3 (I was still using 0.11). Closing. Sorry for the noise.

**Comment by gunnarmorling** [comment]
Ah yes, you are right. It's coming from quay as of 0.13.3 (I was still using 0.11). Closing. Sorry for the noise.
