### ISSUE TITLE
Ability to inject Dev Services Kafka Config into @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#21819]
### Description

Currently its possible during an `@QuarkusTest` class to inject the kafka broker configuration provided by dev services (see https://github.com/quarkusio/quarkus-quickstarts/blob/development/kafka-quickstart/processor/src/test/java/org/acme/kafka/processor/QuoteProcessorTest.java#L32-L34).

It would be nice to be able to do the same in a `@QuarkusIntegrationTest`. Currently I'm forced to not use dev services and stand up my own Kafka instance using testcontainers as a test resource.

**Comment by geoand** [comment]
(Almost ) no kind of injection is supported into `@QuarkusIntegration`. 
What exactly is your use case? Asking because maybe we can cover it some other way...

**Comment by geoand** [comment]
> It would be nice to be able to do the same in a @QuarkusIntegrationTest. Currently I'm forced to not use dev services and stand up my own Kafka instance using testcontainers as a test resource.

How come?

**Comment by edeandrea** [comment]
If I have an application that publishes to kafka, then my integration test should trigger the app and then set up a `KafkaListener` and verify that expected items are sent to Kafka (see https://github.com/edeandrea/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/rest/FightResourceIT.java).

Similar on the inverse - I have an app that listens to Kafka and then does something (maybe processes & sends out via WebSocket?). In my integration test I need to setup a `KafkaProducer` to publish the message to Kafka.

Currently in either scenario there is no way to get access to the bootstrap server URL that Dev Services creates, so instead I have to manually create my own Kafka test resource and inject the config.

**Comment by geoand** [comment]
If I understand your use case correctly, then you should be able to use what is described [here](https://quarkus.io/guides/getting-started-testing#testing-dev-services).

Essentially, you just have a field in your test of type `DevServicesContext` and use that to obtain the properties you need. An example can be see [here](https://github.com/quarkusio/quarkus/blob/2.5.0.Final/integration-tests/mongodb-rest-data-panache/src/test/java/io/quarkus/it/mongodb/rest/data/panache/MongoDbRestDataPanacheIT.java).

Does that cover your use case?

**Comment by edeandrea** [comment]
Oooh I didn't know about that! Let me try it out and get back to you!

**Comment by geoand** [comment]
👍🏼

**Comment by edeandrea** [comment]
So in my case I have a KafkaConsumer which is constructed and subscribes to the topic in the test resource, then it is stopped at the end.

If I move that to the test class itself, I wouldn't be able to do that in a beforeAll/afterAll since the DevServicesContext is not static.

How would I get around that? Still use the test resource but implement ContextAware?

**Comment by geoand** [comment]
> How would I get around that? Still use the test resource but implement ContextAware?

Yup, that should do the trick - something like: https://github.com/quarkusio/quarkus/blob/2.5.0.Final/integration-tests/container-image/maven-invoker-way/src/it/container-build-jib-with-mongo/src/test/java/org/acme/DummyResource.java

**Comment by edeandrea** [comment]
That seems to work. How does https://github.com/edeandrea/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/KafkaBrokerResource.java and https://github.com/edeandrea/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/rest/FightResourceIT.java look?

**Comment by geoand** [comment]
LGTM!

So I assume you are fine closing the issue?

**Comment by edeandrea** [comment]
Yup I am! I'll even do it for you! Thanks for the help!

**Comment by geoand** [comment]
Please describe what you are trying to do. I am completely lacking context

**Comment by edeandrea** [comment]
I have this project: https://github.com/edeandrea/quarkus-super-heroes/tree/main/event-statistics

It uses the dev services context aware to create a `KafkaProducer` (https://github.com/edeandrea/quarkus-super-heroes/blob/main/event-statistics/src/test/java/io/quarkus/sample/superheroes/statistics/KafkaProducerResource.java)

When I run (this is java 17 - but java 11 gives the same result)

```shell
./mvnw clean verify -Pnative \
-Dmaven.compiler.release=17 \
-Dquarkus.http.host=0.0.0.0 \
-Dquarkus.native.container-build=true \
-Dquarkus.container-image.build=true \
-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.3-java17
```

The `integration-test` (https://github.com/edeandrea/quarkus-super-heroes/blob/main/event-statistics/src/test/java/io/quarkus/sample/superheroes/statistics/endpoint/WebSocketsIT.java) fails with

```shell
2021-12-06 11:13:05,395 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-4) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://kafka-XKptM:9092
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.728 s <<< FAILURE! - in io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT
[ERROR] io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT.testScenarios  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.sample.superheroes.statistics.KafkaProducerResource@168954cf
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.sample.superheroes.statistics.KafkaProducerResource@168954cf
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
```

It seems as if the dev services can't talk to kafka.

**Comment by edeandrea** [comment]
It also doesn't seem to be specific to building a native image either. The issue is connecting Dev Services when the integration test is running in a container.

From that same project running

```shell
./mvnw clean verify \
-Dmaven.compiler.release=17 \
-Dquarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm17 \
-Dquarkus.container-image.build=true
```

I get

```shell
2021-12-06 12:55:09,489 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-3) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://kafka-6aDz9:9092
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.252 s <<< FAILURE! - in io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT
[ERROR] io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT.testScenarios  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.sample.superheroes.statistics.KafkaProducerResource@6288a47d
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.sample.superheroes.statistics.KafkaProducerResource@6288a47d
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers

```

**Comment by geoand** [comment]
Can you try Quarkus from `main`? @manstis introduced a fix around this area recently

**Comment by edeandrea** [comment]
sure. Remind me again how to do that?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#checking-an-issue-is-fixed-in-main

**Comment by edeandrea** [comment]
I tried the snapshot - same failure

**Comment by edeandrea** [comment]
i can make a simple reproducer if that would be helpful

**Comment by manstis** [comment]
That would be very useful. I am successfully using DevService's Kafka container from both within the Docker network and Docker host network (admittedly not from an integration test). I'd be interested in seeing your setup (and looking at the issue) as I'll be writing integration tests for my use-case too at some point. BTW I'm not a Quarkus developer, just a contributor.

**Comment by edeandrea** [comment]
@manstis / @geoand here is a reproducer. I'm using a `Dockerfile.jvm` for java 11. The Java version doesn't seem to matter though.

[kafka-dev-service-container-int-test.zip](https://github.com/quarkusio/quarkus/files/7663481/kafka-dev-service-container-int-test.zip)

Unzip it & un `./mvnw clean verify -Dquarkus.container-image.build=true` and watch the integration test fail because it can't connect to the Kafka broker.

```shell
2021-12-06 15:48:38,316 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-8) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://kafka-P8z8t:9092
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.859 s <<< FAILURE! - in org.acme.NumbersWebSocketIT
[ERROR] org.acme.NumbersWebSocketIT.testScenario  Time elapsed: 0.012 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.KafkaProducerResource@463a6f06
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.KafkaProducerResource@463a6f06
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
```

**Comment by edeandrea** [comment]
Actually I think my problem has something to do with https://quarkus.io/guides/getting-started-testing#launching-containers

I'll play with it some more.

**Comment by edeandrea** [comment]
I've essentially ran into [this](https://stackoverflow.com/questions/69855376/how-can-i-connect-a-test-container-in-quarkus-to-the-docker-network-of-devservic), except in my case I want to construct a producer from the current jvm into the broker running in the container.

I don't know how to connect the test to the container network running the application & the Kafka broker.

**Comment by edeandrea** [comment]
I removed the `QuarkusTestResource` and instead directly injected the `DevServicesContext` into my test class

```java
@QuarkusIntegrationTest
class NumbersWebSocketIT {
	private static final Logger LOGGER = Logger.getLogger(NumbersWebSocketIT.class);

	@TestHTTPResource("/numbers")
	URI numbersUri;

	DevServicesContext devServicesContext;

	private Map<String, Object> producerConfig() {
		LOGGER.infof("Dev Services Properties: %s", this.devServicesContext.devServicesProperties());
		LOGGER.infof("Def Services container id: %s", this.devServicesContext.containerNetworkId());

		return Map.of(
			ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, this.devServicesContext.devServicesProperties().get("kafka.bootstrap.servers")
		);
	}

	private KafkaProducer<String, Integer> getProducer() {
		return new KafkaProducer<>(producerConfig(), new StringSerializer(), new IntegerSerializer());
	}

	@Test
	public void testScenario() throws DeploymentException, IOException {
		LOGGER.infof("Numbers URI: %s", this.numbersUri);

		// Set up queue to handle the messages
		var messages = new LinkedBlockingQueue<String>();

		// Set up the client to connect to the WebSocket
		try (var session = ContainerProvider.getWebSocketContainer().connectToServer(new EndpointTestClient(messages), this.numbersUri)) {
			// Make sure client has connected by waiting to receive a CONNECT message
			await()
				.atMost(Duration.ofMinutes(5))
				.pollInterval(Duration.ofSeconds(10))
				.until(() -> "CONNECT".equals(messages.poll()));

			var producer = getProducer();

			// Send 10 messages onto the Kafka topic
			IntStream.range(0, 10).boxed()
				.map(i -> new ProducerRecord<String, Integer>("numbers", i))
				.forEach(producer::send);

			// Wait for our messages to appear in the queue
			await()
				.atMost(Duration.ofMinutes(5))
				.pollInterval(Duration.ofSeconds(10))
				.until(() -> messages.size() == 10);

			var expected = IntStream.range(0, 10)
				.map(i -> i * 2)
				.boxed()
				.map(String::valueOf)
				.collect(Collectors.toList());

			assertThat(messages)
				.containsExactlyElementsOf(expected);
		}
	}

	@ClientEndpoint
	private class EndpointTestClient {
		private final Logger logger = Logger.getLogger(EndpointTestClient.class);
		private final BlockingQueue<String> messages;

		private EndpointTestClient(BlockingQueue<String> messages) {
			this.messages = messages;
		}

		@OnOpen
		public void open() {
			this.logger.info("Opening socket");
			this.messages.offer("CONNECT");
		}

		@OnMessage
		public void message(String msg) {
			this.logger.infof("Got message: %s", msg);
			this.messages.offer(msg);
		}

		@OnClose
		public void close(CloseReason closeReason) {
			this.logger.infof("Closing socket: %s", closeReason);
		}

		@OnError
		public void error(Throwable error) {
			this.logger.errorf(error, "Socket encountered error");
		}
	}
}
```

When the test starts up I see

```shell
2021-12-06 16:41:49,382 INFO  [io.qua.kaf.cli.dep.DevServicesKafkaProcessor] (build-6) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://kafka-A7gL9:9092
Executing "docker run --name quarkus-integration-test-uCZTy --rm -p 51610:51610 -p 8444:8444 --net=8a82f3a9f4a80e9382f69dd8e91a110fe21f775e95e52aa9a87b2154e457ce7b --env QUARKUS_HTTP_PORT=51610 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:0 --env KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-A7gL9:9092 edeandre/kafka-dev-service-container-int-test:1.0.0-SNAPSHOT"
```

To me that means that the kafka broker that Dev Services starts is not exposed outside of the container network and therefore is not accessible by the test. Is that true? There doesn't seem to be a `-p` mapping for `9092` to map back to the local machine network.

**Comment by geoand** [comment]
This can actually be fixed by what @manstis contributed.

@manstis I am wondering if we should have `exposeOnDockerHost` enabled by default...

**Comment by manstis** [comment]
@geoand I was thinking much the same last night... I'll look into later today. There are different things at play: service discovery (bootstrap servers) and the service itself. Did we want both always visible to docker host and docker internal networks regardless of whether the useSharedService is enabled? Is this now a question of the (re-)design of all services launched by DevServices? If we want Kafka available to both networks, why not for other services? Why not always allow binding to a fixed port (at the moment only possible if useSharedNetwork is  false). And, if we always want services available to both networks what purpose does the BuildItem then play?

**Comment by geoand** [comment]
> Did we want both always visible to docker host and docker internal networks regardless of whether the useSharedService is enabled

I would say that as a first step we probably want to expose the service to both the host and internal networks when `useSharedService` is enabled

> If we want Kafka available to both networks, why not for other services?

We probably want to use it for all DevServices

> And, if we always want services available to both networks what purpose does the BuildItem then play?

If we follow the approach I outlined above, then the build item still has a role to play.

WDYT?

**Comment by manstis** [comment]
@geoand FYI, https://github.com/quarkusio/quarkus/pull/21981

I removed the additional flag I'd introduced since it was only used to expose Kafka to Docker's host network in addition to the shared network when the `useSharedNetwork` flag was `true`... it serves no purpose now.

**Comment by edeandrea** [comment]
Should I reopen this ticket since we had closed it last week?

**Comment by geoand** [comment]
No need
