### ISSUE TITLE
Adding a quarkusDev dependency on quarkus-flyway does not run migrations on start

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#21822]
### Describe the bug

Add a dependency `quarkusDev 'io.quarkus:quarkus-flyway'` to build.gradle and set `quarkus.flyway.migrate-on-start` to true in application properties.

Start the application with `./gradlew quarkusDev`.

### Expected behavior

Migrations are performed when the application starts in dev mode.

### Actual behavior

The migrations are not performed.

Replacing the `quarkusDev` dependency with an `implementation` dependency works and the migrations are performed.

### Output of `uname -a` or `ver`

Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.8" 2020-07-14 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by josephearl** [comment]
Sorry thought I'd made a mistake so closed the issue, but after re-testing this does seem to be an issue.

**Comment by geoand** [comment]
cc @glefloch

**Comment by glefloch** [comment]
Thanks for reporting this, I will have a look ASAP
