### ISSUE TITLE
Quarkus Flyway is not supporting Microsoft SQL server 14/15

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#21826]
### Describe the bug

Quarkus version: `999-SNAPSHOT` (Upstream)

When I try to load a DB init script through Quarkus Flyway I am getting the following error: 

```
 org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 15.0
```

I have tried to downgrade Mssql version to 14.0 but is still not working. 

**Note:** Is working with previous Quarkus version as `2.3.0.Final` or `2.5.0.Final`

Involved extensions: 

```
io.quarkus:quarkus-jdbc-mssql
io.quarkus:quarkus-flyway
```
 Configuration example:
```
# Flyway
quarkus.flyway.mssql.schemas=msdb
quarkus.datasource.mssql.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=msdb
quarkus.flyway.mssql.locations=db/migration/mssql,db/migration/common
```

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6#flyway .
