### ISSUE TITLE
Warning on startup in dev mode: Unrecognized configuration key "quarkus.jacoco.report"

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#21828]
### Describe the bug

I am using Gradle together with the Jacoco Gradle plugin and the `io.quarkus:quarkus-jacoco` extension as a `testImplementation` dependency.

I have configured `quarkus.jacoco.report` to be false in my `application.yaml` - this works as expected and prevents the duplicate and empty HTML report being generated by the extension so I can just use the HTML report generated by the Jacoco Gradle plugin.

However when running the application with `./gradlew quarkusDev` I receive a warning just after the banner:

```
WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.jacoco.report" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### Expected behavior

No warning about an unrecognized configuration key "quarkus.jacoco.report"

### Actual behavior

Warning just after the banner on startup:

```
WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.jacoco.report" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### How to Reproduce?

1. Add `id 'jacoco'` to the plugins block in `build.gradle`
2. Add `testImplementation 'io.quarkus:quarkus-jacoco'` to the dependencies block in `build.gradle`
3. Set `jacoco.report.enabled` to be false in your configuration (not in an any specific profile)
4. Start the application with `./gradlew quarkusDev`

### Output of `uname -a` or `ver`

Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.8" 2020-07-14 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by geoand** [comment]
This is indeed an issue, but you can easily overcome it by using `test` profile specific configuration, as mentioned [here](https://quarkus.io/guides/config-yaml#profiles).

**Comment by josephearl** [comment]
Thanks! I was hoping to avoid that because I have multiple test profiles and wanted to share that configuration between them, but the duplication will do for now.

**Comment by geoand** [comment]
Right, I understand where you are coming from, but unfortunately there is no other way of going about this that would make Quarkus not warn about the unused property (since Jacoco is not available on the dev-mode classpath).
