### ISSUE TITLE
Cron expression defined as a config property in application.properties is not resolved while starting the application in native mode

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#21833]
### Describe the bug

I'm using the `quarkus-scheduler` extension and I have the following method: 
```java
@ApplicationScoped
public class MyScheduledBean {
    @Scheduled(cron = "{quarkus.registry.cache.cron}")
    void jobTriggered() {
        // Do stuff
    }
}
```

In my `application.properties`, I have the following entry defined: 
```properties
quarkus.registry.cache.cron=*/2 * * ? * *
```

The application starts up fine in JVM mode (including `quarkus:dev`) but fails with the following error when running in native

```
app_1       | 2021-12-01 03:55:49,772 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.util.NoSuchElementException: Could not expand value quarkus.registry.cache.cron in property ${quarkus.registry.cache.cron}
app_1       | 	at io.quarkus.scheduler.runtime.util.SchedulerUtils$1.accept(SchedulerUtils.java:113)
app_1       | 	at io.quarkus.scheduler.runtime.util.SchedulerUtils$1.accept(SchedulerUtils.java:104)
app_1       | 	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
app_1       | 	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
app_1       | 	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
app_1       | 	at io.quarkus.scheduler.runtime.util.SchedulerUtils.resolvePropertyExpression(SchedulerUtils.java:104)
app_1       | 	at io.quarkus.scheduler.runtime.util.SchedulerUtils.lookUpPropertyValue(SchedulerUtils.java:72)
app_1       | 	at io.quarkus.scheduler.runtime.SimpleScheduler.createTrigger(SimpleScheduler.java:230)
app_1       | 	at io.quarkus.scheduler.runtime.SimpleScheduler.<init>(SimpleScheduler.java:89)
app_1       | 	at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(SimpleScheduler_Bean.zig:400)
app_1       | 	at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(SimpleScheduler_Bean.zig:415)
app_1       | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
app_1       | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
app_1       | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
app_1       | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
app_1       | 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
app_1       | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
app_1       | 	at io.quarkus.scheduler.runtime.SimpleScheduler_Observer_start_09e6c17011ef77dec3e1dd9987380b3d946e3db6.notify(SimpleScheduler_Observer_start_09e6c17011ef77dec3e1dd9987380b3d946e3db6.zig:135)
app_1       | 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
app_1       | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
app_1       | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
app_1       | 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
app_1       | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
app_1       | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:80)
app_1       | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
app_1       | 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:984)
app_1       | 	at io.quarkus.runtime.Application.start(Application.java:101)
app_1       | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
app_1       | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
app_1       | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
app_1       | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
app_1       | 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

### Expected behavior

The data in `application.properties` should be used as the cron expression and the application should start without any errors with the predefined cron expression.

### Actual behavior

The application fails to start *ONLY IN NATIVE*

### How to Reproduce?

To reproduce, you need the Quarkus CLI installed.

1. Run `quarkus create app -x scheduler` to create the project
2. Add the following class:
```java
package org.acme;

import javax.enterprise.context.ApplicationScoped;

import io.quarkus.logging.Log;
import io.quarkus.scheduler.Scheduled;


@ApplicationScoped
public class MyScheduledBean {
    @Scheduled(cron = "{quarkus.registry.cache.cron}")
    void jobTriggered() {
        Log.info("SCHEDULER CALLED");
    }  
}
```
3. Add the following entry to your `application.properties`:
```properties
quarkus.registry.cache.cron=*/2 * * ? * *
``` 
4. Build the native image and run it afterwards: `mvn clean package -Dnative -DskipTests`

### Output of `uname -a` or `ver`

Fedora 35

### Output of `java -version`

JDK 17

### GraalVM version (if different from Java)

GraalVM 21.3.0 Java 11 CE

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

A workaround is to define the default value inside the `@Scheduled` annotation instead of putting it in `application.properties`:
```java
    @Scheduled(cron = "{quarkus.registry.cache.cron:*/2 * * ? * *}")
```

**Comment by mkouba** [comment]
Hm, I've just tried to build a native image for the [scheduler-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/scheduler-quickstart) with [`@Scheduled(cron = "{cron.expr}")`](https://github.com/quarkusio/quarkus-quickstarts/blob/main/scheduler-quickstart/src/main/java/org/acme/scheduler/CounterBean.java#L30) and it works jut fine. 

> To reproduce, you need the Quarkus CLI installed.

Is it something Quarkus CLI-specific?

**Comment by mkouba** [comment]
I think that it's a config problem - your config property has the `quarkus.` prefix and I can see the following warning in the console:
```
07:41:04,253 WARN  [io.qua.config] Unrecognized configuration key "quarkus.registry.cache.cron" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
It works if you remove the prefix and use `registry.cache.cron` instead.

So maybe an unrecognized config property with  the `quarkus.` prefix is not stored in the native image? CC @radcortez

**Comment by radcortez** [comment]
I don't believe we have a  `quarkus.registry.cache.cron` configuration.

Any configuration in the `quarkus` namespace requires a `ConfigRoot` for documentation, validation and recording. Because this is an unrecognized configuration, we don't record it in the native image so it is not available there.

My recommendation is to just use a configuration name without the `quarkus` prefix (it is reserved for Quarkus only).

**Comment by gastaldi** [comment]
I think this is a special case where it doesn't make sense to have a `ConfigRoot` because the config will only be read by the scheduler extension, but I understand the reason behind it. I'll use a different prefix in this case. Thanks!

**Comment by evision-alok** [comment]
@Scheduled(cron = "${quarkus.registry.cache.cron}") try this
