### ISSUE TITLE
Add migration note / documentation about Flyway 8.1.0 breaking change

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#21834]
### Description

Quarkus 2.6 upgraded Flyway 8.0.5 -> 8.1.0, which introduced breaking change described here:
- https://github.com/quarkusio/quarkus/pull/21715#issuecomment-979587768

I assume it will be mentioned in a migration guide.
But IMO, this is worth adding into regular documentation (Flyway guide?).

**Comment by jsmrcka** [comment]
Related to https://github.com/quarkusio/quarkus/issues/21826.

**Comment by zedbeit** [comment]
Working on this.
