### ISSUE TITLE
Make sure kubernetes-client can work with Elliptic Curve keys

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#21848]
### Description

Right now, if the EC keys are required, the client will fail due to the EC key utility code being excluded in the native image.

Reported by Alexander Hachmann.

### Implementation ideas

Consider adding
```
<dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
</dependency>
<dependency>
     <groupId>org.bouncycastle</groupId>
     <artifactId>bcpkix-jdk15on</artifactId>
</dependency>
```

as `quarkus-kubernetes-client` dependencies

**Comment by geoand** [comment]
cc @manusa
