### ISSUE TITLE
Use Strimzi Kafka images

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2184]
As we in Strimzi have a project that produces container images for Kafka we should use those images instead of the Wurstmeister ones in the Kafka guide: https://quarkus.io/guides/kafka-guide

**Comment by cescoffier** [comment]
@gunnarmorling Work done in https://github.com/quarkusio/quarkus-quickstarts/pull/185.

A big thank you to @scholzj that provided the docker-compose file

**Comment by gunnarmorling** [comment]
Excellent, thanks a lot! Jakub, I'd suggest you tweet about it, everything
on Quarkus + Kafka is super-hot.

**Comment by gunnarmorling** [comment]
Just noticing that the Kafka guide on the web site still uses the
Wurstmeister image:

    https://quarkus.io/guides/kafka-guide#starting-kafka

Is anyone working already on updating this to Strimzi, too?

**Comment by gunnarmorling** [comment]
Filed https://github.com/quarkusio/quarkusio.github.io/pull/212 for
applying the change from the quick start repo to the docs, too.
