### ISSUE TITLE
End Vert.x response before propagating mapped exception in VertxBlockingoutput 

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#21841]
### Describe the bug

When an exception is thrown when processing the write stream, Resteasy does not close the Vert.X response prior to propagating the exception.

This behavior might cause applications to not receive events from Vert.X (e.g.: when using a filter that adds a headers handler) because the response is not ended properly.

Similarly to when there is no data to write, the `VertxBlockingoutput` should make sure the response is ended.

Related to this issue https://github.com/quarkusio/quarkus/issues/21762.

### Expected behavior

Properly end the Vert.x response.

### Actual behavior

Vert.x response not properly ended when an exception occurs on the write stream.

### How to Reproduce?

See https://github.com/quarkusio/quarkus/issues/21762.

### Output of `uname -a` or `ver`

Linux fedora 5.14.18-200.fc34.x86_64 #1 SMP Fri Nov 12 16:48:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

2.4+

### Additional information

Resteasy classic issue.

**Comment by geoand** [comment]
Should this be closed now that https://github.com/quarkusio/quarkus/pull/21842 is in?

**Comment by mschorsch** [comment]
Possible reproducer: https://github.com/quarkusio/quarkus/issues/21762#issuecomment-985995830

**Comment by pedroigor** [comment]
@geoand Closing, thanks.
