### ISSUE TITLE
Qute: shorter enum constant access

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#21854]
### Description

At the moment we make enum values accessible in views using this declaration:

```java
@TemplateData
public enum ContentStatus {
    NEW,
    ACCEPTED,
    REJECTED,
    DELETED;
}
```

Which then exposes values such as `fr_epardaud_model_ContentStatus:NEW` which is handy in case of name conflict, but not so much if you don't have any conflict.

The shorter behaviour can already be obtained with `@TemplateData(namespace = TemplateData.SIMPLENAME)` but I'd like to have another annotation that would be an alias for this. Perhaps `@TemplateEnum`?

```java
@TemplateEnum
public enum ContentStatus {
    NEW,
    ACCEPTED,
    REJECTED,
    DELETED;
}
```

This would be usable in the views as `ContentStatus:NEW`.

Note that ATM I have a special case for accessing the `values()` enum static member:

```java
    @TemplateExtension(namespace = "ReputationGainReason", matchName = "*")
    static ReputationGainReason reputaionGainReason(String value) {
       return ReputationGainReason.valueOf(value);
    }

    @TemplateExtension(namespace = "ReputationGainReason", matchName = "values", priority = 6)
    static ReputationGainReason[] reputaionGainReasonValues() {
       return ReputationGainReason.values();
    }
```

And I wonder if we should not automatically add it as for for all enums declared with `@TemplateData` and `@TemplateEnum`? So `ContentStatus:values` would call the `.values()` static method. WDYT?

**Comment by mkouba** [comment]
I like the idea of `@TemplateEnum` with behavior equivalent to `@TemplateData(namespace = TemplateData.SIMPLENAME)`.

> And I wonder if we should not automatically add it as for for all enums declared with @TemplateData and @TemplateEnum? So ContentStatus:values would call the .values() static method. WDYT?

This already works with `@TemplateData(namespace = TemplateData.SIMPLENAME)`, just try `{#each ContentStatus:values}{it}{/}` or `ContentStatus:values[0]`.

**Comment by mkouba** [comment]
In general, `@TemplateData(namespace = TemplateData.SIMPLENAME)` makes all public static members accessible...

**Comment by FroMage** [comment]
Thanks!
