### ISSUE TITLE
Unable to build Quarkus CLI from 999-SNAPSHOT

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#21851]
### Describe the bug

Quarkus CLI build fails because of the next PR https://github.com/quarkusio/quarkus/pull/21820

Error stacktrace:
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-devtools-common:jar is missing. @ line 25, column 21
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-devtools-testing:jar is missing. @ line 61, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.quarkus:quarkus-cli:999-SNAPSHOT (/home/kshpak/myTests/Quarkus/github/quarkus-main/devtools/cli/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-devtools-common:jar is missing. @ line 25, column 21
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-devtools-testing:jar is missing. @ line 61, column 21
```

### Expected behavior

Be able to build CLI module
*Worked before mentioned PR

### How to Reproduce?

cd devtools/cli && mvn -B -s ../../.github/mvn-settings.xml clean install -Dquickly

**Comment by ebullient** [comment]
CLI has dependencies on the other projects, so you can't just build it alone.

From the root: mvn install -Dquickly -DskipTests -DskipITs -Dno-test-modules
The CLI will be built as part of that. 

If you're determined to build the minimal subset, you should build the modules under independent-projects/tools (registry-client, and devtools-*)

**Comment by kshpak** [comment]
Interestingly, it failed after rebuilding of main branch in my CI. Now it works.
CI that failed: https://github.com/kshpak/quarkus-test-suite/actions/runs/1526082771/attempts/1
cc @aloubyansky
