### ISSUE TITLE
Qute: bug in `if` test

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#21857]
### Describe the bug

I have the following tag:

```html
{#if user && target.status == ContentStatus:NEW && !target.voted(user)}
    User: {user}<br/>
    Target.status: {target.status}<br/>
    Target.voted(user): {target.voted(user)}<br/>
{/if}
```

When I call it with some values, I'm getting this output:

```
User: User<2>
Target.status: ACCEPTED
Target.voted(user): false
```

This can't be right. As you see `target.status` is `ACCEPTED` (that's the correct value) but the `if` condition specifies `target.status == ContentStatus:NEW` so in theory we should never be able to get into the `if` block and display this.

I can give you instructions for reproducing but it requires you build the vixen branch and checkout the aviouf demo app. Otherwise you can perhaps point me where to look in a debugger to help you narrow it down?

**Comment by mkouba** [comment]
Couldn't it be a race condition? I mean isn't it possible that the `target.status` can be changed before the body of the `{#if}` is rendered?

**Comment by mkouba** [comment]
> I can give you instructions for reproducing but it requires you build the vixen branch and checkout the aviouf demo app.

@FroMage That would be really helpful.

**Comment by FroMage** [comment]
OK:

- You need to build and install this branch of Quarkus: https://github.com/FroMage/quarkus/tree/renarde
- Build and install the Renarde extension: https://github.com/quarkiverse/quarkus-renarde
- Clone https://github.com/FroMage/aviouf
- Run `mvn clean quarkus:dev` in it
- Open http://localhost:8080/Login/loginForm
- Enter fromage / 1q2w3e4r
- Open http://localhost:8080/PersonOrGroups/view/Ron_Thal
- Click the green √ mark to accept it
- That page now is bogus, because the target status is `ACCEPTED` and yet `contentInfo.html` has the right test.

**Comment by mkouba** [comment]
Will try it, thanks!

**Comment by mkouba** [comment]
So I was able to reproduce the problem. And now the difficult part - to find the cause ;-).

**Comment by mkouba** [comment]
I found it! There's a bug in evaluation of composite params with a logical complement operator, i.e. the `!target.voted(user)` part caused the problem.

**Comment by FroMage** [comment]
Great!
