### ISSUE TITLE
Qute: extension tags not registered

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#21864]
### Describe the bug

I just tried the latest Quarkus/Qute to see if it would pick up my Vixen extension tags, declared in `extensions/vixen/runtime/src/main/resources/templates/tags` (in the runtime module) and they're not visible to the user application, I'm getting errors.

Perhaps I'm doing it wrong and they need to be in the deployment module?

**Comment by mkouba** [comment]
> Perhaps I'm doing it wrong and they need to be in the deployment module?

No, it should be the runtime module. Let me check..

**Comment by FroMage** [comment]
OK, this fixes my bug. Do you have any need for a tag build item then? https://github.com/FroMage/quarkus/commit/59440daf2c1c275d32dd7d194609a5f683d3f64a

Or should I drop this commit from my branch?

**Comment by FroMage** [comment]
OK, this fixes my bug. Do you have any need for a tag build item then? https://github.com/FroMage/quarkus/commit/59440daf2c1c275d32dd7d194609a5f683d3f64a

Or should I drop this commit from my branch?

**Comment by mkouba** [comment]
> Or should I drop this commit from my branch?

I don't think that we need the `TemplateTagBuildItem` so +1..

**Comment by FroMage** [comment]
OK thanks.
