### ISSUE TITLE
GRPC: Does not generate proto-based files

### ISSUE THREAD

**Issue by siudeks** [quarkusio/quarkus#21878]
### Describe the bug

version 2.5 gradle+scala+grpc do not generate code from my proto files
version 2.4.1.Final gradle+scala+grpc generates code from my proto files

### Expected behavior

java code based on my proto files is generate

### Actual behavior

java files are not generated

### How to Reproduce?

1. generate project using scala, grpc, gradle, v. 2.4.1
1. create source file src/main/proto/helloworld.proto
  ```
    syntax = "proto3";
    package helloworld;
    message Hello {
      string message = 1;
    }
  ```
1. gradle clean build
1. find . -name *.java
   - actual: The list contains just generated Helloworld.java file
1. Repeat the same steps using Quarkus v. 2.5
1. find . -name *.java
   - expected: The list contains Helloworld.java file
   - actual: the list is empty

### Output of `uname -a` or `ver`

Linux Home1 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Microsoft-28056 (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by glefloch** [comment]
Thanks for reporting this @siudeks. I tried to reproduce the error but files are correctly generated in `build/classes/java/quarkus-generated-sources/grpc/helloworld/Helloworld.java`
Do you have a reproducer ? I tested it with both `2.5.0.Final` and `2.5.1.Final`.

**Comment by siudeks** [comment]
@glefloch by bad in repro - instead of **gradle clean build** please use **gradle clean test** what is default to run tests 
![MAw8ppC7ft](https://user-images.githubusercontent.com/3256574/144487665-5c9769fd-ff6c-4a72-83d4-4de38d1441b6.gif)
*

**Comment by glefloch** [comment]
Right, I can reproduce the issue, there is a problem in how we linked tasks in the plugin. Working on a fix ;)
