### ISSUE TITLE
CI failure in TracingTest#testContextPropagationInFaultTolerance

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2187]
@pavolloffay @kenfinnigan we have CI failing from time to time due to the test added [here](https://github.com/quarkusio/quarkus/pull/2038).

The failure is the following:
```
2019-04-23 11:38:25,393 INFO  [io.quarkus] (main) Quarkus stopped in 0.033s
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.981 s <<< FAILURE! - in io.quarkus.smallrye.opentracing.deployment.TracingTest
[ERROR] testContextPropagationInFaultTolerance  Time elapsed: 0.971 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <5> but was: <4>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
	at io.quarkus.smallrye.opentracing.deployment.TracingTest.testContextPropagationInFaultTolerance(TracingTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

It happens once in a while. I saw it twice, once on a Linux build and once on a Windows build.

Could you take a look at that issue and, hopefully, fix it before tomorrow's release?

**Comment by pavolloffay** [comment]
I think we will have to wait until all spans are reported. I will submit a fix for it.

**Comment by gsmet** [comment]
@pavolloffay the issue doesn't seem to be fixed. I just had a test failure with:
```
ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.77 s <<< FAILURE! - in io.quarkus.smallrye.opentracing.deployment.TracingTest
[ERROR] testContextPropagationInFaultTolerance  Time elapsed: 5.899 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with io.quarkus.smallrye.opentracing.deployment.TracingTest was not fulfilled within 5 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
	at io.quarkus.smallrye.opentracing.deployment.TracingTest.testContextPropagationInFaultTolerance(TracingTest.java:106)
```

Do you think it would be possible that it takes more than 5 seconds?

**Comment by pavolloffay** [comment]
> Do you think it would be possible that it takes more than 5 seconds?

I don't think so given we wait after the request is done https://github.com/quarkusio/quarkus/blob/0277f3cff9cbdab7de55b950bc3b34a2247a8cb9/extensions/smallrye-opentracing/deployment/src/test/java/io/quarkus/smallrye/opentracing/deployment/TracingTest.java#L10

I was able to reproduce it. There were these spans present 
```
[
{traceId:10, spanId:12, parentId:11, operationName:"ft"}, 
{traceId:10, spanId:13, parentId:11, operationName:"ft"},
 {traceId:10, spanId:14, parentId:11, perationName:"io.quarkus.smallrye.opentracing.deployment.Service.fallback"}, 
{traceId:10, spanId:11, parentId:0, operationName:"io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance"}
]
```

There should be 3 `ft` spans and not 2. We use `maxRetries = 2` https://github.com/quarkusio/quarkus/blob/3680544654c3c00f5e062ba8b3338e8019f0936b/extensions/smallrye-opentracing/deployment/src/test/java/io/quarkus/smallrye/opentracing/deployment/Service.java#L28. I am not sure if this is a bug in FT or FT can decide to execute the method up to `maxRetries` count.

**Comment by gsmet** [comment]
@pavolloffay I'm not sure what I can do to help. Do you need help from someone else? @kenfinnigan maybe?

**Comment by pavolloffay** [comment]
Someone from FT community should have a look why the invocation number varies.

**Comment by gsmet** [comment]
@kenfinnigan could you ping the right people in the SmallRye world so that we get someone taking a look at it?

**Comment by kenfinnigan** [comment]
@michalszynkiewicz, @mkouba, @antoinesd, @Ladicek can one of you take a look?

**Comment by mkouba** [comment]
What's the current stack trace? I can see that the test waits at most 5 seconds. Could it be that CI is very slow and hystrix does not manage to run all the requested commands in time? Although I know that 5 seconds is sooo much time...

**Comment by FroMage** [comment]
I see FT and context propagation and I'm wondering if this is really the same problem we're solving with MP-CP… If yes we should totally talk about it.

**Comment by FroMage** [comment]
Yeah, I did not mean to derail the issue, we'll talk about this via email/chat.

**Comment by rsvoboda** [comment]
Quarkus has new FT implementation, is this issue still valid ? 
@Ladicek / @michalszynkiewicz / @pavolloffay

**Comment by Ladicek** [comment]
One interesting thing that I noticed in the comments here: if `maxRetries = 2`, and all invocation fails, then the method will be executed 3 times: initial attempt and up to 2 retries. But the number of invocations should definitely be constant.

**Comment by mkouba** [comment]
I've just run the test 20x in a row with no failure. @pavolloffay is there anything special I should do to reproduce the issue?

**Comment by pavolloffay** [comment]
@mkouba It's a very old issue I might not remember all. As I said in https://github.com/quarkusio/quarkus/issues/2187#issuecomment-486600799 it seems the failing test is related to a bug in FT so maybe the new impl solved it.

**Comment by mkouba** [comment]
@pavolloffay np, thanks! So I think that we should probably enable the test again and we'll see how it goes ;-). @rsvoboda @Ladicek Your opinion?

**Comment by Ladicek** [comment]
Ayea. The core implementation is new, the OpenTracing integration is new, the Quarkus extension is much smaller (if I remember the PR correctly). Agree that the test should probably be reenabled.

**Comment by pavolloffay** [comment]
Talk also to @michalszynkiewicz (author of the new impl?) I think he had some issues related to tracing.

**Comment by rsvoboda** [comment]
> Agree that the test should probably be reenabled.

+1

**Comment by mkouba** [comment]
Ok, I'll send a PR shortly.
