### ISSUE TITLE
No way to use anonymous identity with @TestSecurity

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#21888]
### Describe the bug

I would like to implement a test where an anonymous user tries to access authenticated path but that is not possible to define with `@TestSecurity` right now. Logged user works as documented.

```java
// works as expected
@Test
@TestSecurity(user = "test", roles = "test")
public void loggedUserWorking() {
    given()
      .when().get("/ping")
      .then()
         .statusCode(200)
         .body(is("Hello RESTEasy"));
}

// doesn't work, tries to authenticate with keycloak
@Test
@TestSecurity
public void anonymousNotWorking() {
    given()
        .when().get("/ping")
        .then()
        .statusCode(403);
}
```

### Expected behavior

There should be a way to specify an anonymous user for testing.

### Actual behavior

Not possible right now.

### How to Reproduce?

Reproducer: https://github.com/xstefank/quarkus-test-security-reproducer

### Additional information

Config is available in the reproducer:

```
%prod.quarkus.oidc.auth-server-url=${auth.server.url}
quarkus.oidc.client-id=test-client
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# test
%test.quarkus.keycloak.devservices.enabled=false
%test.quarkus.oidc.auth-server-url=http://not-required.com

```

**Comment by sberyozkin** [comment]
Thanks @xstefank.

@stuartwdouglas Hi Stuart, as Martin said the idea was to register an anonymous identity if the `user` attribute is not set as in the 2nd example above.

**Comment by stuartwdouglas** [comment]
This is just how Quarkus works, anonymous users are considered to be not logged in, so if there is a failure an attempt is made to log them in.

**Comment by xstefank** [comment]
@stuartwdouglas so it shouldn't be possible to test anonymous user is not allowed to access resources without any form of external authentication? Can we switch this off with config in tests?

**Comment by sberyozkin** [comment]
@stuartwdouglas But recall we had a discussion about the identity having a `Principal` but also having an anonymous flag, #15730. I have to admit I'm still not sure how this case should be handled.

That said, @xstefank, may be this should do if one sets `@TestSecurity` without any attributes:
``` 
CDI.current().select(TestIdentityAssociation.class).get()
                            .setTestIdentity(QuarkusSecurityIdentity.builder()
                                    .setPrincipal(new QuarkusPrincipal(null))
                                    .build());
```

**Comment by sberyozkin** [comment]
Stuart, I'm not sure the authentication should be attempted if the identity is anonymous - if the resource is public then all is good, but if the authentication is required (as configured in the properties) then it has to be 403 (not 401) since the identity has already been created (ex, non null `Principal` and `anonymous`) and therefore the authentication challenge is no longer required.

If we do not use `TestSecurity` then indeed the authentication layer will challenge if no required credential is provided -  but here we do provide the identity. 

If the custom authentication mechanism has created an identity with the anonymous flag then it should be called again to try to authenticate, the RBAC/authorization layer will block it if it is active.

**Comment by xstefank** [comment]
@sberyozkin that didn't trigger external auth but it takes user as authenticated (200).

**Comment by stuartwdouglas** [comment]
There is always a SecurityIdentity, its just that sometimes it is the anonymous one. If authorization fails then if this flag is set we will attempt to authenticate the user to get a non-anonymous one.

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas I think it is just simpler to return 403 at this point - if the anonymous identity has reached the RBAC layer then it means the authentication layer has allowed it for whatever reasons - trying to re-authenticate the anonymous identity is going to create a loop (the same authentication mechanisms will be retried, etc), right ?

**Comment by stuartwdouglas** [comment]
no, there is always an anonymous identity if auth has failed (it gets lazily created). If you changed this to return 403 then you would never send a challenge.

**Comment by sberyozkin** [comment]
@stuartwdouglas OK, I see; so as far as `TestSecurity` is concerned, looks like all that has to be done is to return 401 here, https://github.com/quarkusio/quarkus/blob/main/test-framework/security/src/main/java/io/quarkus/test/security/TestHttpAuthenticationMechanism.java#L41 ? As well as 
```
DI.current().select(TestIdentityAssociation.class).get()
                            .setTestIdentity(QuarkusSecurityIdentity.builder()
                                    .setAnonymous(true)
                                    .build());
```

when only `@TestSecurity` is set ? I can do  a PR if you agree

**Comment by stuartwdouglas** [comment]
That should work, but only if the test identity is not null. You may also need to increase the priority so it is first.

**Comment by xstefank** [comment]
@sberyozkin did you get a chance to work on this, please? I can also create a PR with the above changes if you'd like.

**Comment by sberyozkin** [comment]
Hey @xstefank @stuartwdouglas Sorry, I did not look at it yet, Martin, if you can help with the PR then it would nice, thanks

**Comment by sberyozkin** [comment]
@xstefank Would you have a bit of time to get this issue resolved given that we agreed here to how it can be fixed with thanks to you :-) ?

**Comment by xstefank** [comment]
@sberyozkin so it seems that if I now disable oidc in test with `%test.quarkus.oidc.enabled=-false` it works with 3.0.0.Alpha5 - %test.quarkus.oidc.enabled=-false. If you agree, we can close this.

**Comment by michalvavrik** [comment]
> If you agree, we can close this. Updated reproducer - https://github.com/xstefank/quarkus-test-security-reproducer

I agree; also Stuart's explanation makes sense to me.

I have my own opinion as well, though I hope I won't make this more complicated: having `@TestSecurity` logged with anonymous identity is something artificial. You are either recognized user, or you are have anonymous identity. Personally I'd test my application in a same way it is going to be used: with credentials (either correct ones or incorrect; they can be provided with via `@TestSecurity`) or without credentials at all. But that should be already possible.

**Comment by michalvavrik** [comment]
@xstefank in case you change your mind, please feel free to reopen this. thx
