### ISSUE TITLE
Adding first registry in CLI erases the default one

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#21905]
### Describe the bug

By default, registry list in CLI contains a default registry `registry.quarkus.io` and there is an option to add new registries. Although, if user adds a new registry, e.g. `registry.quarkus.redhat.com`, then the default registry will be silently removed from the list and became inaccessible.

### Expected behavior

Default registry stays in the list, registries are never removed without explicit user request.

### Actual behavior

Default registry is removed from the list.

### How to Reproduce?

1. Install quarkus afresh or remove/rename file ~/.quarkus/config.yaml
2. Check default registry.
```
$ quarkus registry list
Configured Quarkus extension registries:
registry.quarkus.io
```
3. Check existing extensions. 
```
$ quarkus ext list | wc -l
920
```
4. Add non-default registry: ` quarkus registry add registry.quarkus.redhat.com`
5. Check registry list:
```
$ quarkus registry list
Configured Quarkus extension registries:
registry.quarkus.redhat.com #registry.quarkus.io is not in the list
(Read from ~/.quarkus/config.yaml)
```
6. Check existing extensions. 
```
$ quarkus ext list | wc -l
170 # at least some extensions are not accessible any more
```

### Output of `uname -a` or `ver`

5.14.17-201.fc34.x86_64

### Output of `java -version`

Java version: 11.0.13, vendor: Eclipse Adoptium

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by maxandersen** [comment]
hmm - I can see how this is misleading . The one shown on first registry list is just the default when no registry found.

The expected lines to do if you want red hat build of quarkus to have priority is:

```
quarkus registry add registry.quarkus.redhat.com
quarkus registry add registry.quarkus.io
```

if you want it to be secondary you do:

```
quarkus registry add registry.quarkus.io
quarkus registry add registry.quarkus.redhat.com
```

But yeah, we could handle it better and at least inform the user.

**Comment by gsmet** [comment]
I think we could just add a warning when executing `quarkus registry add registry.quarkus.redhat.com` if there is no registry set.

**Comment by ashwinair** [comment]
Hi @gsmet, if no one is working on this issue, can you please assign me.

p.s  I was trying to reproduce this issue on my side and looks like the issue mentioned in the title is already fixed.

> I think we could just add a warning when executing `quarkus registry add registry.quarkus.redhat.com` if there is no registry set.

can you explain this a bit? please :)
I'm new to the codebase that's why.....

**Comment by ashwinair** [comment]
I understood that - " _we should warn the user when he executes the `quarkus registry add registry.quarkus.redhat.com` if there is no config file defined by the user._"
am I right?

**Comment by maxandersen** [comment]
The config file can be present without a registry in it.

The suggestion is to print a warning if no registry is already set. i.e. the list of registries are empty in the config file.

**Comment by ashwinair** [comment]
> The config file can be present without a registry in it.
> 
> The suggestion is to print a warning if no registry is already set. i.e. the list of registries are empty in the config file.

Thank you @maxandersen :)
