### ISSUE TITLE
Quarkus 0.13.0 - 0.13.3 application.properties enviroment variables doesnt work

### ISSUE THREAD

**Issue by HoodElliot** [quarkusio/quarkus#2192]
in the latest version of quarkus, I faced a hard time running the -runner.jar with environment variables in application.proparties lets say I have this as my property 

> quarkus.env.variable=${HOST:localhost}

when I do an `mvn clean package` and run the jar files with `java -jar target/app-runner.jar`
I expect to get localhost but I get as an answer this 

> ${HOST:localhost}

in quarkus 12.0 it works perfectly fine with environment variables 
and it shows localhost as it should be

**Comment by geoand** [comment]
Hi,

Is the property actually named `quarkus.env.variable`?

Also, would it be possible to share a reproducer project?

Thanks

**Comment by HoodElliot** [comment]
hello i have this piece of code like the tutorial in quarkus.io with the implementation of configProperties
**VERSION 0.12.0**

```
@Path("/login")
@ApplicationScoped
public class login {
    @ConfigProperty(name = "quarkus.env.variable")
    private String message;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return message;
    }
}
```
and i have this application.proparties
`quarkus.env.variable=${HOST:localhost}`
i run 
`mvn clean package -DskipTests=true
 java -jar target/app-runner.jar
`
i hit the page with localhost:8080/login
and the message goes as follows 
![Screenshot from 2019-04-23 21-00-26](https://user-images.githubusercontent.com/38839592/56604559-dfaeed00-660a-11e9-9596-a4446b32fe7f.png)

now switching the version back to 0.13.3 and doing exactly the same steps without changing any code expect the version and the output is this 
![Screenshot from 2019-04-23 21-02-33](https://user-images.githubusercontent.com/38839592/56604645-269ce280-660b-11e9-9f90-28dd69fbfc07.png)

i hope it helps :100: !

**Comment by geoand** [comment]
Thanks for the details.

Can you do me a favor and change the name of the property to something like `myapp.env.var` and try again?

**Comment by HoodElliot** [comment]
yes just did same in the version **0.12.0** got `localhost` and in **0.13.3** got `${HOST:localhost}`

**Comment by geoand** [comment]
I'll try and reproduce it and let you know

**Comment by geoand** [comment]
So I have good news all around :tada: 

I was able to reproduce this in `0.13.3`. The even better news is that with the current `master` is the issue does not exist. I am not sure which commit actually fixed it, but if we need to figure out later on, I'm should we can.
