### ISSUE TITLE
Introduce `OidcSession` interface

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#21928]
### Description

`OidcSession` will have a request scope injection support and it will provide some useful information and actions to OIDC `web-app` endpoints such as:
- how long the session will stay valid for
- tenant_id of this session
- invalidate - this will remove the session cookie to support the local-site only logout
- etc

This enhancement follows a conversation with @FroMage

**Comment by sberyozkin** [comment]
See also #22197. Specifically, the goal of this issue is for the users be able to avoid writing the resolver this way:
```
@ApplicationScoped
public class OidcTenantResolver implements TenantResolver {
    
    @Inject
    OidcConfig oidcConfig;

    @Override
    public String resolve(RoutingContext context) {
        // Named tenants
        for (Entry<String, OidcTenantConfig> tenantEntry : oidcConfig.namedTenants.entrySet()) {
            if(!tenantEntry.getValue().tenantEnabled)
                continue;
            String tenant = tenantEntry.getKey();
            // First case: login
            // Note that Router.getURI only works in JAX-RS endpoints
            if(context.request().path().equals("/login-"+tenant)) {
                return tenant;
            }

            // Second case: auth callback from the auth server
            Cookie cookie = context.request().getCookie("q_auth_"+tenant);
            if(cookie != null) {
                return tenant;
            }

            // Third case: already logged in
            cookie = context.request().getCookie("q_session_"+tenant);
            if(cookie != null) {
                return tenant;
            }
        }
        
        // manual JWT session
        Cookie cookie = context.request().getCookie("QuarkusUser");
        if(cookie != null) {
            return "manual";
        }

        // Not logged in or default tenant
        return null;
    }
}
```

`RoutinContext` `tenant-id` attribute will be available - for the already authenticated requests, so the code could be simplified as follows:
```
String tenantId = routingContext.get("tenant-id");
if (tenantId == null) {
    // non-authenticated request, path specific check is required
} else {
    return tenantId;
}
```

**Comment by FroMage** [comment]
If you already know the tenand-id I don't see why you need my resolver. Also, due to the fact that we _require_ a default tenant, whose ID is `null`, this is confusing, because if you have a `q_auth` cookie you also know the tenant is the default one, but you'll probably store it as `null` which would make my resolver think that it's unknown. We need a special value for the default tenant when it's known that we're using it.

**Comment by sberyozkin** [comment]
@FroMage the value for the default tenant is `Default`, but returning `null` is fine as well. Please recall we also have the dynamic config resolvers (`TenantConfigResolver` vs `TenantResolver` in your case) which are called first they need the id to get the cached dynamically created `OidcTenantConfig`

**Comment by sberyozkin** [comment]
>  Also, due to the fact that we require a default tenant, whose ID is null, this is confusing, because if you have a q_auth cookie you also know the tenant is the default one, but you'll probably store it as null which would make my resolver think that it's unknown

I'm not sure I follow. Default tenant is not required, it can be disabled

**Comment by sberyozkin** [comment]
And the tenant id is not known during the initial unauthenticated call

**Comment by sberyozkin** [comment]
@FroMage just to clarify,
```
String tenantId = routingContext.get("tenant-id");
if (tenantId == null) {
    // non-authenticated request, path specific check is required
   // we can not avoid it - it is called before the config has been resolved or cookies created
} else {
    // This will work for all the tenants incl the default one, with `q_auth` or `q_session`
    return tenantId;
}
```
But I think I need to PR to test returning `Default` (instead of `null`) works.

I see your earlier point, where returning `null` means a default tenant should be selected - but with the new PR `routingContext.get("tenant-id")` will not return `null` for the default tenant but `Default`.

Also note some tenants may be `service` apps - so there will be no OIDC cookies there at all...
