### ISSUE TITLE
Blazebit EntityView not serialized in Native image

### ISSUE THREAD

**Issue by chrigiansen** [quarkusio/quarkus#21930]
### Describe the bug

Hello

When running Quarkus as Native image, calling a rest endpoint results in a json array of the right size but with empty elements. running the same code in quarkus:dev works fine. The single element is a blaze EntityView, which when logged, shows the correct state of the objects. 

I have marked the views with `@RegisterForReflection`, but i don't think it's necessary.
The project also uses Lombok. After removing it from the entity doesn't make a difference

### Expected behavior

An array with the correct data:
`
[ 
    {
        "id": 1,
        "tournamentEnd": "2022-01-31T23:00:00Z",
        "tournamentName": "EM 2020",
        "tournamentStart": "2021-11-30T23:00:00Z",
        "winnerTeamSelectionEnd": "2021-12-07T23:00:00Z"
    },
    {
        "id": 2,
        "tournamentEnd": "2022-01-31T23:00:00Z",
        "tournamentName": "EM 2016",
        "tournamentStart": "2021-11-30T23:00:00Z",
        "winnerTeamSelectionEnd": "2021-12-07T23:00:00Z"
    }
]
`

### Actual behavior

An array with empty elements:
`[
    {},
    {}
]
`

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/7652979/reproducer.zip)

when running, change this params:
`MP_JWT_VERIFY_PUBLICKEY_LOCATION=https://demo.identityserver.io/.well-known/openid-configuration/jwks`
`QUARKUS_HTTP_CORS=true`
`QUARKUS_DATASOURCE_JDBC_URL=<your_db>`
`QUARKUS_DATASOURCE_PASSWORD=<your_pw>`
`QUARKUS_DATASOURCE_USERNAME=<your_user>`

on your postgresql db run:
`
INSERT INTO TOURNAMENT (ID, TOURNAMENTNAME, TOURNAMENTSTART, TOURNAMENTEND, WINNERTEAMSELECTIONEND) VALUES 
(nextval('hibernate_sequence'), 'EM 2016', CURRENT_DATE - interval '2 day', CURRENT_DATE + interval '60 day', CURRENT_DATE + interval '5 day');
`

get a token from demo.identityserver.io and call GET api/tournament

### GraalVM version (if different from Java)

GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.1

**Comment by beikov** [comment]
Thanks for the ping @famod, I'll take a look ASAP.

**Comment by beikov** [comment]
Hey @chrigiansen,
I created https://github.com/Blazebit/blaze-persistence/issues/1406 for this and have a fix in the pipeline. I'll ping you again when I release the next version with the fix.

**Comment by beikov** [comment]
I'm planning to do a release this week and will then update the version in Quarkus, so I guess that 2.6.0 or 2.6.1 will update to the new version. Note though that the Quarkus integration of Blaze-Persistence works with all Quarkus versions, so you can simply update the version of Blaze-Persistence in your library to without having to wait for a new Quarkus release.

**Comment by gsmet** [comment]
@beikov FYI, cut off dates for the Platform:
- this evening for 2.6.0.Final
- Thursday evening for 2.6.1.Final
(Paris time)

**Comment by beikov** [comment]
Will be fixed by updating to 1.6.4 which was just released. Also, here is the BOM update: https://github.com/quarkusio/quarkus-platform/pull/417

**Comment by chrigiansen** [comment]
I have tested my case and it now works as I expect it. thanks @beikov

**Comment by beikov** [comment]
Awesome, thanks for verifying!

**Comment by gsmet** [comment]
This has been fixed upstream.
