### ISSUE TITLE
MongoDB BsonDateTime is not in the Jandex index

### ISSUE THREAD

**Issue by edress185** [quarkusio/quarkus#21949]
### Describe the bug

When building a Quarkus application that is using mongodb-client and mongodb-panache extentions, ReflectiveHierarchyStep outputs:

```
WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-7) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.BsonDateTime (source: <unknown>)
```

### Expected behavior

Expected behavior after looking at "MongoDB BSON types are not in the Jandex index #17893 " is that there should be NO warning! 

### Actual behavior

A warning is logged stating the following:

```
WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-7) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.BsonDateTime (source: <unknown>)
```

### How to Reproduce?

To reproduce:

Create a sample application with the  "mongodb-panache" extension

```
mvn io.quarkus:quarkus-maven-plugin:2.5.0.Final:create \
    -DprojectGroupId=com.example\
    -DprojectArtifactId=demo \
    -Dextensions=resteasy,mongodb-client,mongodb-panache
```

Add a sample entity:

```
package com.example;

import io.quarkus.mongodb.panache.common.MongoEntity;
import org.bson.BsonDateTime;
import org.bson.codecs.pojo.annotations.BsonProperty;

@MongoEntity
public class Entity {
    @BsonProperty("time")
    public BsonDateTime time;
}
```

Add sample repository:

```
package com.example;

import io.quarkus.mongodb.panache.PanacheMongoRepositoryBase;

public class Repo implements PanacheMongoRepositoryBase<Entity, String> {
}
```

Build project and observe mentioned message:

`mvn clean package -DskipTests
`

### Output of `uname -a` or `ver`

-

### Output of `java -version`

11

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.5.0.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Java version: 11, vendor: Oracle Corporation, runtime: /opt/jdk-11 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "3.10.0-693.17.1.el7.x86_64", arch: "amd64", family: "unix"`

**Comment by loicmathieu** [comment]
Hi, this also occurs for the `BsonId` type and this WARNING can be safely ignored.

@aloubyansky their is multiple types on the org.bson package that generates this warning, I don't remember if we should index them or if we can provides a build item to ignore the warning ?

**Comment by edress185** [comment]
Yes, you are right it is the same for BsonId! I thought it was solved as part of  #17893, but I think it was not !

![image](https://user-images.githubusercontent.com/18722010/144857063-3ca77174-0fa0-4803-9a41-56c97c6c5d0c.png)

Below is a log indicating the warning for both BsonId and BsonDateTime 

```
WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-23) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- org.bson.BsonDateTime (source: <unknown>)
	- org.bson.codecs.pojo.annotations.BsonId (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

I will just go ahead and ignore these warning, and hopefully they will disappear as part of future Quarkus releases!

**Comment by aloubyansky** [comment]
> @aloubyansky their is multiple types on the org.bson package that generates this warning, I don't remember if we should index them or if we can provides a build item to ignore the warning ?

TBH, I am not sure. But if you used to recommend to ignore these and it worked then maybe we should not be indexing them by default?

**Comment by loicmathieu** [comment]
Yes, it's not needed to index them.

Some times ago, I force index the BsonId to avoid the warning, but the code seems to disapear, and now I wonder if I need again to force index them in the build or if there is a way to ignore the warning

**Comment by aloubyansky** [comment]
There is `ReflectiveHierarchyIgnoreWarningBuildItem` although it might be too fine grained in this case?

**Comment by loicmathieu** [comment]
Thanks @aloubyansky this is what I need, I'll have a look to fix the issue later on this week.

**Comment by loicmathieu** [comment]
What I did back then is to register for reflection the `ObjectId` which is used to denote the default MongoDB ID field.

But there is tons of types inside the bson library (BSON is the marshalling standard of MongoDB), I wonder if we should ignore all of them or build a Jandex index (I don't know if it impact build time and application size a lot). WDYT @aloubyansky ?

**Comment by gsmet** [comment]
You can use `ReflectiveHierarchyIgnoreWarningBuildItem(Predicate<DotName> predicate)` and ignore the whole package.

**Comment by loicmathieu** [comment]
Good idea, I open the class but for some reason didn't see the predicate based method ;)
Will try this.
