### ISSUE TITLE
Quarkus Custom authorization interceptors or filter

### ISSUE THREAD

**Issue by alinayebi9080** [quarkusio/quarkus#21952]
### Describe the bug

I have a Quarkus microservice doing authentication and authorization with Keycloak using quarkus-oidc and quarkus-keycloak-authorization extensions.

when i enable quarkus.keycloak.policy-enforcer, reader & writer interceptors and container request & container response filters not working on 401 error. do you have any idea??

### Output of `java -version`

11

### Quarkus version or git rev

2.5.1

**Comment by sberyozkin** [comment]
@alinayebi9080 

> when i enable quarkus.keycloak.policy-enforcer, reader & writer interceptors and container request & container response filters not working on 401 error. do you have any idea

I believe you need to add custom exception mappers to intercept the security exception but also disable the proactive authentication

**Comment by alinayebi9080** [comment]
i disable proactive, but exception mapper not working.

**Comment by alinayebi9080** [comment]
> @alinayebi9080
> 
> > when i enable quarkus.keycloak.policy-enforcer, reader & writer interceptors and container request & container response filters not working on 401 error. do you have any idea
> 
> I believe you need to add custom exception mappers to intercept the security exception but also disable the proactive authentication

i disable proactive, but exception mapper not working.

**Comment by gsmet** [comment]
There's really not much information here for us to help you. If you want help, you will need to provide a complete reproducer of your problem and explain how to reproduce it and what you're trying to do.

**Comment by geoand** [comment]
Closing as we did not receive feedback
