### ISSUE TITLE
config implement QuarkusTestProfile can't convert to @ConfigMapping config

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#21987]
### Describe the bug

there is a class implement QuarkusTestProfile#getConfigOverrides.

but the config can't convert to @ConfigMapping class when i run test

**Comment by geoand** [comment]
Can you add more details? Preferably add a reproducer

**Comment by naah69** [comment]
i had reslove the problem.the reson is that object properties in  config class of  @ConfigMapping is decorating by Optional
