### ISSUE TITLE
Support for proxy with NTLM-authentication for REST clients.

### ISSUE THREAD

**Issue by vtdmitriy** [quarkusio/quarkus#21983]
### Description

Currently, only Basic Authentication proxies are supported for REST clients.

**Comment by sberyozkin** [comment]
The challenge is how to ensure the negotiation works if more than one round is required.

**Comment by vtdmitriy** [comment]
> The challenge is how to ensure the negotiation works if more than one round is required.

This mechanism works successfully through Apache HttpClient, for example: 
```
NTCredentials ntCreds = new NTCredentials("user", "pass", null, "domain");
CredentialsProvider credsProvider = new BasicCredentialsProvider();
credsProvider.setCredentials(AuthScope.ANY, ntCreds);
HttpHost myProxy = new HttpHost(proxyUrl, proxyPort);
RequestConfig requestConfig = RequestConfig.custom()
		.setTargetPreferredAuthSchemes(Arrays.asList(AuthSchemes.NTLM))
		.build();
HttpClientBuilder clientBuilder = HttpClientBuilder.create()
		.useSystemProperties()
		.setProxy(myProxy)
		.setDefaultCredentialsProvider(credsProvider)
		.setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE)
		.setDefaultRequestConfig(requestConfig);
CloseableHttpClient httpClient = clientBuilder.build();
HttpGet httpGet = new HttpGet("https://www.google.com/");
```

But at the same time, all the convenience and advantages of using quarkus are lost...

**Comment by sberyozkin** [comment]
I'm sorry, I believe GSS API can be used to support it - however as opposed to Kerberos I have not found the examples where more than one negotiation round is required...

**Comment by AnastasiiaL** [comment]
is there still no plan to support NTLM-authentication? Maybe you can give some hints on how to make it work with microprofile rest client?
