### ISSUE TITLE
IllegalAccessError while accessing protected field with maven multi-module

### ISSUE THREAD

**Issue by Sirz3chs** [quarkusio/quarkus#21996]
### Describe the bug

I have a project with maven multi-module and i have a class that extends another class located in another module. The're both in the same package and i'm trying to access a protected field that is injected in the parent class then i have an `IllegalAccessError`.

### Expected behavior

Being able to access my protected field.

### Actual behavior

```
[ERROR] foo.bar.quarkusissue.service.FooExtensionServiceTest.testGet  Time elapsed: 0.015 s  <<< ERROR!
java.lang.IllegalAccessError: class foo.bar.quarkusissue.service.FooExtensionService_Bean tried to access protected field foo.bar.quarkusissue.service.FooService.barService (foo.bar.quarkusissue.service.FooExtensionService_Bean is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @c689973; foo.bar.quarkusissue.service.FooService is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3effd4f3)
        at foo.bar.quarkusissue.service.FooExtensionServiceTest.testGet(FooExtensionServiceTest.java:19)
```

If the field is public of course i can access it but that's not what i want.

### How to Reproduce?

I've made a little project to reproduce the issue https://github.com/Sirz3chs/quarkus-issue.

### Output of `uname -a` or `ver`

Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: /home/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3 Java version: 17, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/adoptopenjdk-17-hotspot-amd64 Default locale: en_GB, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-91-generic", arch: "amd64", family: "unix"

### Additional information

I saw a similar closed issue #14528

**Comment by famod** [comment]
Sorry to say that, but split packages are pretty much a bad practice since Java 9.
You should even see a warning logged by `SplitPackageProcessor` (IIRC).

/cc @manovotn @mkouba

**Comment by manovotn** [comment]
Yes, `SplitPackageProcessor` was added to help with precisely these issues. It is not only a bad practice but also brings some limitations into bean creation and access such as the one you just described.

You need to avoid using split packages in you application - with what you described it means either making it public or encapsulating the whole logic inside of one archive.

The original PR introducing this processor can be seen under https://github.com/quarkusio/quarkus/pull/18617.
It can provide some insights into why was this done and what are the limitations (if you have time and interest to read the PR and linked issues).
