### ISSUE TITLE
Agroal config needs examples/doc for `url`

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2200]
It does not define the format used, and because JDBC urls differ from Postgres urls, this can be very treacherous.

**Comment by FroMage** [comment]
https://vladmihalcea.com/jdbc-driver-connection-url-strings/ has some examples. Not sure if it's authoritative. I guess it depends on the driver.

**Comment by LightGuard** [comment]
I can take this on.

**Comment by LightGuard** [comment]
@FroMage is this something in the main repo? Are there examples I should be emulating?

**Comment by LightGuard** [comment]
Did I fix this with the documentation added for Agoral? @FroMage @gsmet

**Comment by gsmet** [comment]
I think @FroMage wanted a reference of the JDBC URLs that should be used for each RDBMS we support. I don't think we have that yet?

**Comment by LightGuard** [comment]
We do not have that yet. Where would this live?

**Comment by gsmet** [comment]
I think an additional paragraph explaining how to setup each RDBMS we support in the doc about datasource configuration you added would make sense.
