### ISSUE TITLE
Conflicting versions of vertx-mutiny-clients and kafka-clients lead to NoSuchMethodError

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#22000]
### Describe the bug

When we use io.vertx.mutiny.kafka.client.producer.KafkaProducer to send messages, we get this error:
```
java.lang.NoSuchMethodError: org.apache.kafka.clients.producer.RecordMetadata.checksum()J
09:51:05 	at io.vertx.kafka.client.common.impl.Helper.from(Helper.java:111)
```

### Expected behavior

Messages should be sent without errors.

### Actual behavior

Exception, full stack trace is below:

```
09:51:05 2021-12-07 08:51:05,814 ERROR [org.jbo.res.res.i18n] (vert.x-eventloop-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.NoSuchMethodError: org.apache.kafka.clients.producer.RecordMetadata.checksum()J
 	at io.vertx.kafka.client.common.impl.Helper.from(Helper.java:111)
 	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:35)
 	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### How to Reproduce?

1. Clone the repo: git@github.com:quarkusio/quarkus-quickstarts.git
2. Switch to `development` branch
3. Run `mvn clean verify -pl org.acme:kafka-bare-quickstart`

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.15.6-100.fc34.x86_64", arch: "amd64", family: "unix"

### Output of `java -version`

11.0.13, vendor: Eclipse Adoptium

### Quarkus version or git rev

79e84c8693421244a63fd18d478b6ee8b44561f6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

Brief search shows, that quarkus-bom exports io.smallrye.reactive:vertx-mutiny-clients-bom:2.16.0, which exports io.vertx:vertx-kafka-client:4.2.1, which have that code at the line 111 of io.vertx.kafka.client.common.impl.Helper:
```
  public static RecordMetadata from(org.apache.kafka.clients.producer.RecordMetadata metadata) {
    return new RecordMetadata(metadata.checksum(), metadata.offset(),
      metadata.partition(), metadata.timestamp(), metadata.topic());
  };
```
At the same time, quarkus-bom exports org.apache.kafka:kafka-clients:3.0.0, which doesn't have method checksum() in org.apache.kafka.clients.producer.RecordMetadata, and it seems that this method was removed in this commit: https://github.com/apache/kafka/commit/89933f21f204abf75336464d3ac24a4fdd254628

**Comment by ozangunalp** [comment]
Unfortunately `vertx-kafka-client` is still on `kafka-clients:2.6.0`. 
I'd advise forcing the `kafka-clients` version to `2.8.1` manually when using the `vertx-kafka-client` in Quarkus.

**Comment by fedinskiy** [comment]
@ozangunalp thank you, I can confirm, that the workaround works.

**Comment by cescoffier** [comment]
As a follow-up, we should bump the version in the mutiny binding. 2.6.0 is not right.

**Comment by gsmet** [comment]
Closing this one in favor of https://github.com/quarkusio/quarkus/issues/22295 . The user has a workaround.
