### ISSUE TITLE
2.3+ causes ConcurrentModificationException with CycloneDX Gradle plugin

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#22008]
### Describe the bug

When I upgraded to 2.3+, the [CycloneDX plugin](https://github.com/CycloneDX/cyclonedx-gradle-plugin) started throwing a `ConcurrentModificationException`

I'm not sure who this issue should be levied on, since the CycloneDX version didn't change and it worked fine before Quarkus 2.3. So I wrote one on the CycloneDX page too (https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/106).

### Expected behavior

Successful build

### Actual behavior

```
Caused by: java.util.ConcurrentModificationException
        at org.gradle.api.internal.DefaultDomainObjectCollection$IteratorImpl.next(DefaultDomainObjectCollection.java:475)
        at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:174)
```

### How to Reproduce?

1. Clone https://github.com/mweber03/quarkus-test
2. Run `./gradlew service1:cyclonedxBom`

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

Quarkus 2.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by glefloch** [comment]
Thanks for reporting this @mweber03. The error is quite weird, in 2.3 we updated the way the deployment classpath is built. We now create configuration for that. This may come from an unresolvable configuration, I will try to see if we can do something about it.

**Comment by gsmet** [comment]
@glefloch I checked and this is still a problem with 2.6.1.Final.

**Comment by BartoszCoyote** [comment]
Any info?

**Comment by glefloch** [comment]
Yes, I think I understand the issue. The plugin iterate over configurations. But in the quarkus plugin, in order to be lazy, we create deployment configuration while resolving the `implementaiton` configuration which leads to the `ConcurrentModificationException`. I tried to create all configuration in plugin initialization but without success.

**Comment by isacandrei** [comment]
We are also running on Quarkus 2.0+ currently and would like to benefit from some fixes implemented in Quarkus 2.3 and 2.6. However running the `cyclonedxBom` task from the CycloneDX plugin is mandatory for us.

Do you have any update on this?

**Comment by glefloch** [comment]
I pushed a fix in the cyclone-dx gradle plugin project.

**Comment by glefloch** [comment]
The release 1.5.0 fixes the issue. I'm closing the issue.
