### ISSUE TITLE
Command mode 'e' - edit parameter - not working on Windows

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#22013]
### Describe the bug

When developing a command mode application using the dev mode on Windows, hitting e should enable to edit the application parameter.

On Windows, it didn't work and "fail" the command mode, only CTL-C to quit the application is then feasible.

### Expected behavior

Hitting e should allow to edit the application parameter

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1348]

### Output of `java -version`

openjdk version "17" 2021-09-14

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by maxandersen** [comment]
@stuartwdouglas any idea?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by loicmathieu** [comment]
No idea, I no longuer work on Windows !
As there was a partial fix and nobody else complain about it, let's close it.
