### ISSUE TITLE
Support OIDC form_post response mode

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#22029]
### Description

Some OIDC providers such as `Apple OIDC` (as discovered by @FroMage) use a [form_post](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html) response mode when returning the authorization code to `quarkus-oidc` - so instead of including it as a query parameter in a `GET` redirect it will be form-posted, alongside `state`,  to Quarkus with `POST`.

So this response mode should also be supported

### Implementation ideas

Fallback to checking the form payload if the state verification has been done but no `code` has been found in a query string

**Comment by FroMage** [comment]
I already have a proto of this working. Needs config and tests though.

**Comment by sberyozkin** [comment]
We can tweak OIDC wiremock a bit to support the form_post as well, but,
Hmm... I've just realized the `state` is also posted and is state is not a query param we can't decide the post body can be read...i.e, how can quarkus-oidc figure out this POST is for `quarkus-oidc` only ? Perhaps, by analyzing the state cookie value and comparing the path stored there with the current request path.

**Comment by FroMage** [comment]
I've added preliminary support for this in https://github.com/FroMage/quarkus/commit/dcc701127bc7adcf1dcf9dc28114335151caa015

I'm not sure this should require a configuration to turn it on or off, because this only happens when calling the OIDC callback endpoint, and we can just look at the method being used if it's GET or POST.

**Comment by FroMage** [comment]
@sberyozkin fixing this would be really nice.
