### ISSUE TITLE
issue with the Method too large problem

### ISSUE THREAD

**Issue by ggaikwad321** [quarkusio/quarkus#22027]
### Describe the bug

build is failing with below error
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.4.0.Final:build (default) on project code-with-quarkus-demo: Failed to build q
uarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] [error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateConfigClass threw an exception: org.objectweb.asm.Meth
odTooLargeException: Method too large: io/quarkus/runtime/generated/Config.<clinit> ()V

when running in mvn clean install getting above error 

### Expected behavior

build should got passed 

### How to Reproduce?

[code-with-quarkus-demo.zip](https://github.com/quarkusio/quarkus/files/7676233/code-with-quarkus-demo.zip)

run the clean install it will fail

**Comment by ggaikwad321** [comment]
@radcortez let me know if anything needed from my side

**Comment by mkouba** [comment]
For the record - the reproducer contains an additional YAML config file which has almost 30 thousand lines and Quarkus attempts to parse this YAML file into config properties. I don't think it's a good idea to use the Quarkus config facility for similar use cases, i.e. I would recommend to load the YAML file manually and access the data via the `org.yaml.snakeyaml.Yaml` API directly.
