### ISSUE TITLE
How to resolve the conflict of the properties which have the same name when using quarkus native package?

### ISSUE THREAD

**Issue by Mkabaka** [quarkusio/quarkus#22054]
### Description

When I use `quarkus` to build a native-image with the `<quarkus.package.type>native</quarkus.package.type>` and then execute `mvn clean package -Pnative`. The final bytecode will generate successfully but unfortunately the source files in `/META-INF/resources` which have the same name will conflict. eg, I defined two files, the one named `/META-INF/resouces/A`:
```
aaaaaa
```
and the another one have same name `/META-INF/resouces/A`:
```
bbbbbb
```
I except the result should be: `/META-INF/resouces/A`:
```
aaaaaa
bbbbbb
```
but in fact, it always only contains the partly. Can anyone help me resolve it?

thanks a lot.

One last thing, the `/META-INF/resouces/A` files are defined in different jars, and I can't merge
it manually.

**Comment by geoand** [comment]
@gastaldi didn't you add something to address this at some point?

**Comment by gastaldi** [comment]
@geoand I remember a similar case and end up creating `UberJarMergedResourceBuildItem`, but that was for UberJars

**Comment by Mkabaka** [comment]
@geoand @gastaldi thanks a lot. I found the same issue #5677 and the fix of it #17077. But as @geoand said

> @geoand I remember a similar case and end up creating `UberJarMergedResourceBuildItem`, but that was for UberJars

It looks that the `UberJarMergedResourceBuildItem` only applies to UberJars. I wonder whether it will take effect when I use
`<quarkus.package.type>native</quarkus.package.type>`?  According to my understanding, the native-image-source-jar is
an UberJar, maybe the `UberJarMergedResourceBuildItem` will also take effect for `native`?

**Comment by gastaldi** [comment]
I haven't tested but I wouldn't bet on that. Also, you need to produce that in a separate extension if I am not mistaken

**Comment by Mkabaka** [comment]
> I haven't tested but I wouldn't bet on that. Also, you need to produce that in a separate extension if I am not mistaken

@gastaldi I just tested it successfully. When I produce `UberJarMergedResourceBuildItem` in my custom separate extension, it will merge the files which have the same name as it does in `UberJar`. And produce it in a separate extension is just what I need, so it meets my need perfectly. Thanks again and I will close this issue.

**Comment by gastaldi** [comment]
@Mkabaka that's awesome! Glad we could help 😉
