### ISSUE TITLE
[camel] initialization event fired before setting the injector to thr converter registry

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#2206]
The FastCamelRuntime [register](https://github.com/quarkusio/quarkus/blob/master/extensions/camel/camel-core/runtime/src/main/java/io/quarkus/camel/core/runtime/support/FastCamelRuntime.java#L85-L86) the injectors to the `TypeConverterRegistry` after firing the init event so in case the event consumer requires to load a converter, it will fails with an NPE

**Comment by lburgazzoli** [comment]
@gnodet fyi

**Comment by gnodet** [comment]
Fixed in #2273 / #2278

**Comment by lburgazzoli** [comment]
tested
