### ISSUE TITLE
[camel] Could not find field com.sun.beans.WeakCache.map

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#2207]
Building native images is broken because of the following error:

```
Error: should not reach here: Could not find field com.sun.beans.WeakCache.map on class io.quarkus.camel.core.runtime.graal.Target_com_sun_beans_WeakCache
    object com.sun.beans.WeakCache
    field java.beans.Introspector.declaredMethodCache
```

**Comment by lburgazzoli** [comment]
@gnodet fyi

**Comment by ppalaga** [comment]
Blocked by the current issue: https://github.com/quarkusio/quarkus-quickstarts/issues/166

**Comment by dmlloyd** [comment]
I lied, going to discuss in #2272 .

**Comment by dmlloyd** [comment]
What if instead of reverting this, we added an alias for the `map` field in the substitution class?
