### ISSUE TITLE
Console leaks startup DEBUG output even when quarkus.log.console.level=INFO

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#2209]
With an application.properties like:

```properties
# Root logger at DEBUG
quarkus.log.level=DEBUG
# INFO console logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}]] (%t) %s%e%n
quarkus.log.console.level=INFO

# Debug log file
quarkus.log.file.enable=true
quarkus.log.file.path=target/trace.log
quarkus.log.file.level=TRACE
quarkus.log.category."io.quarkus.smallrye".level=TRACE
quarkus.log.category."org.jboss.resteasy.core".level=TRACE
```

I see the following DEBUG level console output being leaked:
<img width="673" alt="console-output" src="https://user-images.githubusercontent.com/332210/56709876-75fd1480-66d8-11e9-999a-f58a1fb03cab.png">

both when using java -jar ... and mvn quarkus:dev ...;

It is not clear why this is happening at the moment as some initial debugging shows some messages being filtered and a few going through.

**Comment by Saberzun** [comment]
so，how do you resolve this  issue？
