### ISSUE TITLE
Remove the deprecated io.quarkus.arc.config.ConfigProperties

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#22101]
### Description

The annotations from the `io.quarkus.arc.config` package have been deprecated for a long time. Users are encouraged to use the `io.smallrye.config.ConfigMapping` instead. I think it's time to remove them completely!

**Comment by mkouba** [comment]
CC @geoand @radcortez

**Comment by geoand** [comment]
Thanks for opening this.

I think that as a first step we should remove the annotation as I am pretty sure we need the supporting code in order to support the Spring compatiblity part

**Comment by mkouba** [comment]
> I think that as a first step we should remove the annotation as I am pretty sure we need the supporting code in order to support the Spring compatiblity part

Is `io.quarkus.arc.config.ConfigProperties` used internally by the spring compatibility layer?

**Comment by geoand** [comment]
Yes

**Comment by mkouba** [comment]
Hm, it seems that `@ConfigMapping` can only be used in interfaces which makes the migration path a bit more difficult...

**Comment by geoand** [comment]
Exactly right...

**Comment by radcortez** [comment]
There is some limited support for classes that I need to add for the MP `ConfigProperties` (it does not support nested elements). Ideally we would like to not have to support classes :)

**Comment by mkouba** [comment]
@geoand would you care to work on this issue?

**Comment by geoand** [comment]
It will be pretty low on my list of things to do :)

**Comment by mkouba** [comment]
> It will be pretty low on my list of things to do :)

Ok, I can try to take a look. Do we actually have `@ConfigProperties` documented somewhere?

**Comment by geoand** [comment]
Not anymore I don't think

**Comment by mkouba** [comment]
Furthermore, `@ConfigPrefix` is a qualifier that can be used on an injection point. So that you can reuse one `io.quarkus.arc.config.ConfigProperties` definition for multiple prefixes. This is probably also something that cannot be implemented via `@ConfigMapping`...

**Comment by radcortez** [comment]
> Hm, the `IfBuildProfileTest` declares a class annotated with `@IfBuildProfile("prod") @ConfigProperties(prefix = "dummy.prod")`. It seems that we can't replace this with `@ConfigMapping`, right? The original feature is documented [here](https://quarkus.io/guides/config-mappings#combining-configproperties-with-build-time-conditions).

We don't support such a feature with `@ConfigMapping`. I don't believe we had users complaining about it, so I wonder how useful this feature is. Maybe we can drop it?
 
> NOTE: `@IfBuildProfile` is implemented as an annotation transformer that adds `@Vetoed` to the target bean class - this obviously does not work for synthetic beans added in `io.quarkus.arc.deployment.ConfigBuildStep.registerConfigMappingsBean()`.

`@Vetoed` is only added to the MP `@ConfigProperties`, not `@ConfigMapping`. This is because MP `@ConfigProperties` may be recognized as managed beans and we need to use a configurator bean to provide the actual implementation. Maybe there is a better way to do this?

> Ah, and there's also `@org.eclipse.microprofile.config.inject.ConfigProperties`? I'm a little bit confused now ;-).

This was added in MP Config 2.0 (against my loud advice :)). So we have:

-  ~~`io.quarkus.arc.config.ConfigProperties`~~ (deprecated in favour of `@ConfigMapping`)
- `io.smallrye.config.ConfigMapping` (recommended)
- `org.eclipse.microprofile.config.inject.ConfigProperties` (very limited in terms of specification. doesn't even specify nested elements, not recommended at all)

> Furthermore, `@ConfigPrefix` is a qualifier that can be used on an injection point. So that you can reuse one `io.quarkus.arc.config.ConfigProperties` definition for multiple prefixes. This is probably also something that cannot be implemented via `@ConfigMapping`...

- This is already supported by `@ConfigMapping`. Just add the same `@ConfigMapping` at the injection point and override the prefix. Again, I'm not completely sure how useful this is.

**Comment by mkouba** [comment]
Thanks Roberto!

>> Hm, the IfBuildProfileTest declares a class annotated with @IfBuildProfile("prod") @ConfigProperties(prefix = "dummy.prod"). It >> seems that we can't replace this with @ConfigMapping, right? The original feature is documented [here](https://quarkus.io/guides/config-mappings#combining-configproperties-with-build-time-conditions).

> We don't support such a feature with @ConfigMapping. I don't believe we had users complaining about it, so I wonder how 
> useful this feature is. Maybe we can drop it?

@geoand WDYT?

**Comment by geoand** [comment]
I don't really think we can, it was a user that requested and implenented that feature

**Comment by radcortez** [comment]
This is the PR that added the feature: https://github.com/quarkusio/quarkus/pull/17063.

To support this, we would have to implement it directly in SmallRye Config.

Anyway, the use case described in the original PR, I believe it is covered by: https://github.com/quarkusio/quarkus/pull/19965. We only registered mappings for valid and used beans, so if a bean is disabled by a build profile, and it contains an injection point to a `@ConfigMapping`, this mapping is not registered.

Also, for the mocking case described in the docs, we do support this directly with Mockito: https://quarkus.io/guides/config-mappings#mocking.

In my opinion, we shouldn't need such a feature for `@ConfigMapping`, unless we have more users requesting it.

**Comment by mkouba** [comment]
> To support this, we would have to implement it directly in SmallRye Config.

Are you sure? I think that we could try to reuse the `BuildExclusionsBuildItem` and skip the [registration of there bean here](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java#L291-L326).

**Comment by radcortez** [comment]
Well, it is possible to implement it there, but I would like SmallRye Config to be in control of all the features. A big issue we still have is config features spread all over the place, which we have been trying to concentrate slowly in SmallRye Config.

If the original use case was to exclude `@ConfigProperties` because they were being injected in a profile-based bean, but we now look into the eligible beans (and injection points) to register the `@ConfigMapping`, do we need to support this? It seems to me this is, even more, user-friendly, because you don't need to annotate two classes (the bean, plus the mapping), just the bean should be enough.

**Comment by mkouba** [comment]
Ok, so [something like this](https://github.com/mkouba/quarkus/commit/6c211bfb3c9d777d87eab51c0d17d7437b87d6e8) seems to work. 

> Well, it is possible to implement it there, but I would like SmallRye Config to be in control of all the features

That's reasonable but our code already contains a bunch of integration logic. And given the fact that `@IfBuildProfile` is a quarkus-specific feature I don't think this should go into SmallRye Config.

> If the original use case was to exclude @ConfigProperties because they were being injected in a profile-based bean...

I have no idea what the original use case was. So I'll let @geoand comment on this.

**Comment by geoand** [comment]
>> If the original use case was to exclude @ConfigProperties because they were being injected in a profile-based bean...
> I have no idea what the original use case was. So I'll let @geoand comment on this.

The use case was to not create a bean at all in case the profile did not match

**Comment by radcortez** [comment]
> > > If the original use case was to exclude @ConfigProperties because they were being injected in a profile-based bean...
> > > I have no idea what the original use case was. So I'll let @geoand comment on this.
> 
> The use case was to not create a bean at all in case the profile did not match

Which we already do with https://github.com/quarkusio/quarkus/pull/19965. 

The same user that implemented that feature, openened the exact same thing for `@ConfigMapping` in https://github.com/quarkusio/quarkus/issues/20275. It seems that he was able to move forward and use what we did in https://github.com/quarkusio/quarkus/pull/19965, so I think we should be good.

**Comment by mkouba** [comment]
BTW I've noticed two bad usages of `@IfBuildProfile` in `IfBuildProfileTest`: 

1. `IfBuildProfileTest.Hello.dummyAbsentBis`
2. `io.quarkus.arc.test.profile.IfBuildProfileTest.Hello.setDummyAbsent(Instance<Dummy>)`.

`@IfBuildProfile` should only work for producer methods and fields, not injected fields and parameters. If there's a test that expects this to work it has to pass by coincidence...

**Comment by mkouba** [comment]
Ok, so I tend to think that we should remove the "profile/property exclusion" functionality completely and if there's a new use case that would require similar feature we can add something similar to the code from my branch. WDYT?

**Comment by radcortez** [comment]
Agree. Thank you.
