### ISSUE TITLE
Log a warning if a final method is skipped when generating client proxies and subclasses

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2210]
By default, CDI fails with a deployment problem if a type that should be proxyable declares a final method. ArC is more lenient and simply ignores final methods. We should log a warning message because invocation of a final method upon a client proxy/subclass may result in unpredictable behavior (interceptors are not applied, etc.).

**Comment by machi1990** [comment]
@mkouba I can take a look at this.
