### ISSUE TITLE
Undocumented breaking change for config resteasy:singleton-resources

### ISSUE THREAD

**Issue by matthiaswronka** [quarkusio/quarkus#22104]
### Description

We just upgraded from v2.2.3 to v2.5.1 and found a breaking change regarding our REST-resources. In 2.2.3 DI was performed for the dependency-tree for every request. In 2.5.1 DI is only performed the first time a REST-resource is used.

The new behaviour is consistent to the documentation https://quarkus.io/guides/rest-json#lifecycle-of-resources, the behaviour in 2.2.3 was not.

We consider this a problem, since applications could inject security-relevant beans that might be reused in unexpected contexts when quarkus is upgraded from version 2.2.3.

### Implementation ideas

This change should be addressed in the migration guide.

**Comment by geoand** [comment]
There is nothing in the code that suggests this change.

Do you have an example application exhibiting this behavior?

**Comment by geoand** [comment]
Closing as we never got a reproducer
