### ISSUE TITLE
io.quarkus.spring.data.deployment.UnableToParseMethodException

### ISSUE THREAD

**Issue by ajaykushwaha1** [quarkusio/quarkus#22115]
### Description

Hi Team,

Thanks for your continuous support. I have another issue related to spring data jpa.

In Spring-boot when we write named query generally we declare our method on Repository and writes query on entity with annotation@NamedQuery i.e @NamedQuery(name = "User.getUserByName", query = "select u from User u where u.name=:name").

For more detail we can understand with below ss:

Entity 

![image](https://user-images.githubusercontent.com/36269701/145594752-19a05b0e-aab6-482a-b53d-e398cd2f79e3.png)

Repository :

![image](https://user-images.githubusercontent.com/36269701/145594713-bbe72e63-2fff-4c13-8248-b0ecd23f65e6.png)

The same thing when I am doing in Quarkus getting below exception during compilation. @geoand need you help on this.

![image](https://user-images.githubusercontent.com/36269701/145594541-770fb303-187d-4765-a065-2ccf756056b8.png)

@geoand need you help on this. I am using **quarkus-spring-data-jpa 2.5.0.Final**.

**Comment by geoand** [comment]
@Sgitario want to take a look at this one?

**Comment by Sgitario** [comment]
sure!

**Comment by ajaykushwaha1** [comment]
Hi @Sgitario,

Any update on this.

**Comment by geoand** [comment]
It's only been 3 days since this was opened - not to mention 2 of those days were a weekend, so it's not likely an issue will be fixed that quick, especially given the fact that everyone working on the project has a full plate and needs to prioritize.

**Comment by geoand** [comment]
Moreover, to make it easier on the maintainers of the project, it would help to have some example code that we can either run (preferable) or copy-paste.  Screenshots are the least friendly option

**Comment by ajaykushwaha1** [comment]
@Sgitario and @geoand Thanks for the quick support. Is it available in quarkus-spring-data-jpa 2.5.0.Final version?

**Comment by geoand** [comment]
It will be available in Quarkus `2.6.0.Final` or `2.5.3.Final` - whatever comes first

**Comment by ajaykushwaha1** [comment]
ok thank you.
