### ISSUE TITLE
Mediatype defaults to the first listed mediatype in MessageBodyWriter (resteasy-reactive)

### ISSUE THREAD

**Issue by carlevert** [quarkusio/quarkus#22119]
### Describe the bug

The MediaType argument in a MessageBodyWriter<>  defaults to the first listed mediatype in the resource.

```java
@Path("")
public interface MyResource {

    @GET
    @Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN})
    Response sayHello();

}
```

```java
public class MyResourceImpl implements MyResource {

    @Context
    HttpHeaders headers;

    public Response sayHello() {
        // Acceptable is set correctly according to the request
        var accept = headers.getAcceptableMediaTypes();

        return Response.ok().entity("hello").build();
    }
}
```

```java
@Provider
@Produces(MediaType.TEXT_PLAIN)
public class MyMessageBodyWriter implements MessageBodyWriter<String> {

    public boolean isWriteable(Class<?> aClass, Type type, Annotation[] annotations, MediaType mediaType) {
        // MediaType is always the first listed mediatype set in @Produces
        return aClass == String.class && mediaType.getType().equals("text") && mediaType.getSubtype().equals("plain");
    }

    public void writeTo(String message, Class<?> aClass, Type type, Annotation[] annotations, MediaType mediaType, MultivaluedMap<String, Object> multivaluedMap, OutputStream outputStream) throws IOException, WebApplicationException {
        outputStream.write(0);
    }
}
```

### Expected behavior

Expecting behaviour according to JAX-RS standard.

In the example above, the MediaType argument is always application/json in the MessageBodyWriter.
In the resource method the acceptable media types is handled correctly.

### Actual behavior

The media type in the MessageBodyWriter<> is always the first listed media type from the resources methods @Provides list of media types.

### Additional information

Sorry for the bad formatting of the code.
https://stackoverflow.com/questions/69844238/mediatype-is-always-application-json-in-messagebodywriter-in-quarkus-with-quarku

**Comment by geoand** [comment]
What HTTP request are you sending to the endpoint?

**Comment by geoand** [comment]
Closing as we did not get feedback.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/24687 fixes the problem
