### ISSUE TITLE
Qute - assign unique error codes to problems detected by parser and/or build steps

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#22116]
### Description

@angelozerr [mentioned](https://github.com/redhat-developer/quarkus-ls/issues/473#issuecomment-989917257):
> Having error code is very helpful for IDE/Editor because you can bind an error code with a quickfix (ex: it misses end tag for this section, you can bind a quick fix which will insert the missing end tag section).

**Comment by mkouba** [comment]
@angelozerr What kind of format do you recommend? For example, a number prefixed with `Q`... `Q001` ?

**Comment by angelozerr** [comment]
I'm not a big fan with error code which means nothing 'ex : Q001'. I think it's better to have an error code which means something like we have with UndefinedObject --> https://github.com/redhat-developer/quarkus-ls/blob/master/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java 

XML parsers (like Xerces) follows this same idea.

**Comment by mkouba** [comment]
Ok, I'll try to come with something similar.

**Comment by mkouba** [comment]
Resolved by https://github.com/quarkusio/quarkus/pull/24839 ([2.10.0.CR1](https://github.com/quarkusio/quarkus/milestone/183)).
