### ISSUE TITLE
New Quarkiverse extension: Renarde

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22117]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

Can you please create a quarkiverse project for `io.quarkiverse.renarde` (formerly Vixen, because people complained)?

This extension is a server-side Web Framework with Qute templating, magic/easier controllers, auth, reverse-routing, as presented on the quarkus-dev mailing list.

Thanks.

**Comment by gastaldi** [comment]
@FroMage there you go: https://github.com/quarkiverse/quarkus-renarde

**Comment by FroMage** [comment]
Thanks!

**Comment by FroMage** [comment]
Well, do I get any admin or commit rights on this repo or what?

**Comment by gastaldi** [comment]
@FroMage you need to accept the invitation to join the Quarkiverse org first, check your inbox

**Comment by FroMage** [comment]
ok thanks
