### ISSUE TITLE
ExtensionLoader attempts to load classes that shouldn't be required

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#22122]
### Describe the bug

After a production build, unused classes, like those from `testcontainers`, must still be present in certain cases otherwise the app crashes on startup. 

See https://github.com/quarkiverse/quarkus-vault/issues/12#issuecomment-991277372. For a good description of the issue.

### Expected behavior

Classes unused in production, like anything only used for DevServices, shouldn't be required.

### Actual behavior

Any type referenced in the signature of any method of a build class will always be required.

### How to Reproduce?

See https://github.com/quarkiverse/quarkus-vault/issues/12 for instructions to reproduce using the Vault extension.

**Comment by aloubyansky** [comment]
The re-augmentation process would require a significant refactoring to eliminate dev services related classes from the augmentation process. I am not sure it's worth the effort, tbh. I am going to close this one but feel free to (re)start a discussion about this.
