### ISSUE TITLE
Using record with generics breaks the build

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#22149]
### Describe the bug

When using record in a configuration, the project doesn't build:

```java
public record R<T>(T value) {
}


    @Produces
    @Singleton
    public Supplier<R<String>> r() {
        return () -> new R<>("foobar");
    }

```

### Expected behavior

It should build the app w/o problems.

### Actual behavior

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.2.Final:build (default) on project qcl-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[ERROR] 	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4165)
[ERROR] 	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1347)
[ERROR] 	at io.quarkus.arc.processor.Types.buildResolvedMap(Types.java:467)
[ERROR] 	at io.quarkus.arc.processor.Types.resolveTypeParam(Types.java:481)
[ERROR] 	at io.quarkus.arc.processor.Types.buildResolvedMap(Types.java:467)
[ERROR] 	at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:251)
[ERROR] 	at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

This is a reproducer:
* https://github.com/alesj/quarkus_cl130

Simply run "mvn clean install -DskipTests"

### Output of `uname -a` or `ver`

Darwin Skywalker 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.1 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-39) OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

### Quarkus version or git rev

2.5.2.Final

**Comment by geoand** [comment]
Is this still a problem with the latest Jandex version?
Do you know @Ladicek ?

**Comment by Ladicek** [comment]
I don't see Jandex in the stack trace, but I vaguelly recall we fixed something related to generic records in Jandex recently. Let me take a look.

**Comment by Ladicek** [comment]
Found it: https://github.com/wildfly/jandex/issues/160 This was fixed in Jandex 2.4.2.Final, so this likely isn't a Jandex issue.

**Comment by geoand** [comment]
Gotcha thanks.

@alesj is this still on issue for you with the latest version of Quarkus?

**Comment by Ladicek** [comment]
The reproducer project mentioned above uses Quarkus 2.5.2.Final, which has Jandex 2.4.1.Final. Updating to latest Quarkus should help.

**Comment by Ladicek** [comment]
I tried constructing a simple reproducer (the one linked above is unnecessarily complex) and indeed I get an build-time error with Quarkus 2.5.2.Final. After updating to Quarkus 2.9.0.Final, build finishes successfully. So this issue has IMHO been fixed by https://github.com/quarkusio/quarkus/pull/22707.
