### ISSUE TITLE
Quarkus Cache - expose metrics to monitor cache hit and miss rates

### ISSUE THREAD

**Issue by bennetelli** [quarkusio/quarkus#22147]
### Description

It would be great if it would be possible (without a big configuration effort) to configure Quarkus Cache so it exposes the cache statistics to Prometheus.

Some other frameworks are offering this already and I think it would be great for the Quarkus User Experience if we would have this as well. 

Let me know what you think about it :)

Best regards
Bennet

**Comment by ebullient** [comment]
Micrometer has metrics for some cache implementations (so adding binders for those would easy). 

Those should be enable-able without a quarkus extension (create a `@Produces` method that creates the MeterBinder).

**Comment by bennetelli** [comment]
Yea, of course I can implement it by hand. Like here for example:

    public GreetingResource(MeterRegistry registry) {
        this.cache = Caffeine.newBuilder().recordStats().build();
        CaffeineCacheMetrics.monitor(registry, cache, "greeting-cache");
        this.registry = registry;
    }
    
But can't Quarkus come with it so users won't have to create caches by hand? IMO this would be a create improvement for users.
If users use our provided annotations for creating caches like described here: https://quarkus.io/guides/cache
they would also not have to create a cache by hand as Quarkus does it for the user.

**Comment by gwenneg** [comment]
That's an interesting enhancement suggestion, thanks!

I have a rough idea of the way `quarkus-cache` could allow the Caffeine metrics collection with minimal efforts for the user. I'll have a look at it.

**Comment by bennetelli** [comment]
My use case is: 

e.g. for a method like this one:

    @CacheResult(cacheName = "weather-cache") 
    public String getDailyForecast(LocalDate date, String city) {
        try {
            Thread.sleep(2000L);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        return date.getDayOfWeek() + " will be " + getDailyResult(date.getDayOfMonth() % 4) + " in " + city;
    }

I was wondering how many requests hit the weather-cache and how many are missing it. 
The lines I added above are easy to add if you know about the CaffeineCacheMetrics class, but as a Quarkus user it would be great to get it for free to all my annotated methods :-) 

you're welcome, @gwenneg :)

**Comment by ebullient** [comment]
Micrometer has a (few) MeterBinders for caffeine: 
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache

Should be a matter of registering these if the Micrometer extension is present (benefit is broader community usage of/consistency with these metrics)

**Comment by gwenneg** [comment]
Yeah, I don't plan on creating any new metrics but only use what is available in Micrometer.

**Comment by ebullient** [comment]
Thanks for verifying. ;)

**Comment by gwenneg** [comment]
Hi @ben-manes. I started working on the enhancement suggested above and I have [something](https://github.com/gwenneg/quarkus/pull/190/files) roughly doing the job already, but I have an issue with the cache hits/misses stats because of the way things are implemented in `quarkus-cache`:

https://github.com/quarkusio/quarkus/blob/341ea2006cfc8a6a10fbdc017fe697be52673c6d/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheImpl.java#L98-L113

Hits and misses are not recorded because the cache is used as a `Map` so I'd like to do that manually from the extension code. Unfortunately, I couldn't find a way to access `StatsCounter` from Caffeine. Is it possible to change the `StatsCounter` values from the Quarkus code?

**Comment by ben-manes** [comment]
No, not unless you provide it and retain a reference. It would be kind of an odd implementation detail to expose, especially since usually the user has control over the cache instance creation anyway. Can you stash it or augment a read of Cache.stats()?

**Comment by gwenneg** [comment]
Oh I didn't see it could be provided through the Caffeine builder. I'll try to use that. Thanks!

**Comment by gwenneg** [comment]
The provided `StatsCounter` instance (I used `ConcurrentStatsCounter`) works like a charm 😃

**Comment by ben-manes** [comment]
That's great! fwiw, I believe Micrometer has an option for a custom `StatsCounter` (but you have to still register for size) and if you prefer the null object pattern there is a `StatsCounter.disabledStatsCounter()`. So you have some additional flexibility wrt to your preferred code style.
