### ISSUE TITLE
authentication doesn't work with proactive auth disabled

### ISSUE THREAD

**Issue by esorio** [quarkusio/quarkus#22150]
### Describe the bug

I have a project with form-based authentication and it works fine.
I want to customize authentication exception responses using a custom exception mapper, to this end (as stated in the [documentation](https://quarkus.io/guides/security-built-in-authentication#how-to-customize-authentication-exception-responses)) I want to disable the proactive auth.
If I disable proactive authentication setting `quarkus.http.auth.proactive = false` in application.properties the authentication doesn't work anymore.

### Expected behavior

The authentication phase should work also with proactive-auth disabled.

### Actual behavior

When I submit credentials from the login form the request to `/j_security_check` returns a 404 error.

### How to Reproduce?

https://github.com/esorio/quarkus-auth

1. ./mvnw package
2. java -jar ./target/quarkus-app/quarkus-run.jar
3. try to log in to `http://localhost:8080/login.html` (credentials are emmett\password, the problem is the same also with wrong credentials)

### Output of `java -version`

OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, can you please have a look ? I think I may have seem a form test with the proactive authentication disabled but I'm not very sure
