### ISSUE TITLE
RestClient will fail with error code 401 even on unsecure endpoint if quarkus.oidc-token-propagation.register-filter=true but there is no token

### ISSUE THREAD

**Issue by sandronm** [quarkusio/quarkus#22178]
### Describe the bug

I have a Quarkus app (let's name it App A) and another Quarkus app (let's name it App B).
App A receive request from clients and sometimes must calls App B.

Some endpoints of App A and App B are secure (Authentication + appropriate authorization) but some others aren't via bearer token (JWT and obviously OIDC).
Obviously, if App A needs to call App B, both endpoints are secured or not at all.

I'm simply using the oidc-token-propagation parameter to propagate the bearer token from A to B.
quarkus.oidc-token-propagation.register-filter=true
This parameter comes from the following extension:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc-token-propagation</artifactId>
        </dependency>
```

### Expected behavior

When my client is calling a secure rest endpoint of A (calling B behind the scene), there is no error if the bearer token is correct.

When my client is calling a not secure rest endpoint of A (calling also B behind the scene), there is no error and obviously no bearer token to propagate to B.

### Actual behavior

When my client is calling a not secure rest endpoint of A, I got the following exception:

> RESTEASY002010: Failed to execute: org.jboss.resteasy.client.exception.ResteasyWebApplicationException: Unknown error, status code 401
>         at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:107)
>         at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
>         at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
>         at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
>         at com.sun.proxy.$Proxy147.getOrganizationByIdentifier(Unknown Source)

But my app B is not called at all! (So the status code 401 is not coming from B!)

If I comment the parameter quarkus.oidc-token-propagation.register-filter=true in app A, the call is working well.

### How to Reproduce?

1. create 2 quarkus app
2. install extension quarkus-oidc on both app
3. install extension quarkus-oidc-token-propagation on app A and set the parameter quarkus.oidc-token-propagation.register-filter to true
4. create unsecure endpoint on A calling another unsecure endpoint on B
5. call unsecure endpoint of A

### Quarkus version or git rev

2.5.1.Final

**Comment by sberyozkin** [comment]
@sandronm Hi, I missed this issue completely. `register-filter` is a global property - all the clients get this filter in this case. So, the propagation filter expects a token be available, so if none is coming it is failing. What else can it do, letting the call go if the token is not available may not be the right approach either.

I believe you should have two REST client interfaces, the one used from a secure endpoint will get this filter attached using `@AccessToken` annotation, the one used from the public endpoint will have no filter in this case.

Do you agree ?

**Comment by sandronm** [comment]
Yes this sounds logical. I will have to test it but yes indeed have 2 differents clients doesn't seem impossible

**Comment by sberyozkin** [comment]
@sandronm Sure, something like 
```
interface MyClient {
// methods
}
@AccessToken 
interface TokenPropagationClient extends MyClient  {
// empty
}
```
should do

**Comment by sberyozkin** [comment]
@sandronm I've been thinking if may be I should add a property to this filter to let the request go without the tokens but then I decided it was not worth it - this filter is about propagating the tokens and not be reused between secure and non-secure clients.
Creating 2 clients as discussed or creating a simple custom filter should do, thanks
