### ISSUE TITLE
Quarkus dev service failed to download image due to short name image and no tty

### ISSUE THREAD

**Issue by uggla** [quarkusio/quarkus#22175]
### Describe the bug

The bug seems to appear due to podman configuration and short image name.
Podman usually displays a menu to select registry, but here it fails because there is no tty. (see msg below)

### Expected behavior

DB image downloaded no error msg.

### Actual behavior

Got the message:
```
Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"cause":"short-name resolution enforced but cannot prompt without a TTY","message":"failed to resolve image name: short-name resolution enforced but cannot prompt without a TTY","response":400}
```

### How to Reproduce?

It is simply running an application with dev services that require to download an image.

### Output of `uname -a` or `ver`

Linux ugglalaptop 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.13 2021-10-19 OpenJDK Runtime Environment 18.9 (build 11.0.13+8) OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)

### GraalVM version (if different from Java)

NA

### Quarkus version or git rev

2.5.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Setting the long image name into: `quarkus.datasource.devservices.image-name` configuration properties does not fix the issue.

However, commenting the following line into `/etc/containers/registries.conf`

```
short-name-mode="enforcing"
```

fixed the bug.

**Comment by geoand** [comment]
Which dev-service is causing this issue?

**Comment by uggla** [comment]
Database postgres.

**Comment by gsmet** [comment]
Yeah, we should probably check everywhere that we don't use short names for image names.

**Comment by geoand** [comment]
I'll go through all the DevServices we have an add the registry

**Comment by uggla** [comment]
Thanks you. 👍
