### ISSUE TITLE
Nested properties are not considered for module version resolving

### ISSUE THREAD

**Issue by thomasdarimont** [quarkusio/quarkus#22171]
### Describe the bug

In modern maven projects it is common to use [CI-friendly versions](https://maven.apache.org/maven-ci-friendly.html) provided by Maven. Unfortuantely `mvn quarkus:dev` fails with an error message, which indicates that version based on nested property references cannot be resolved properly. 
The code in `io.quarkus.bootstrap.resolver.maven.workspace.LocalProject#LocalProject(org.apache.maven.model.Model, io.quarkus.bootstrap.resolver.maven.workspace.LocalWorkspace)` or rather `io.quarkus.bootstrap.resolver.maven.workspace.ModelUtils#resolveVersion` seems to need a more advanced property resolution.

### Expected behavior

Given a `pom.xml` like the following:
```xml
...
<version>${revision}</version>
...
...
<properties>
  <revision>${version}.${build}</revision>
  <version>1.0.0</version>
  <build>0-SNAPSHOT</build>
...
</properties>
```
then Quarkus should resolve the revision string to `1.0.0.0-SNAPSHOT` when executed with `mvn quarkus:dev`

### Actual behavior

Quarkus fails to resolve the revision string to `1.0.0.0-SNAPSHOT` when executed with `mvn quarkus:dev`.

The error message is:
```
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.619 s
[INFO] Finished at: 2021-12-13T23:52:04+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.5.2.Final:dev (default-cli) on project quarkus-ci-friedly-versions: Quarkus code generation phase has failed: Failed to initialize Quarkus bootstrap Maven artifact resolver: Failed to load current project at /home/tom/dev/repos/gh/thomasdarimont/quarkus-dev/quarkus-ci-friedly-versions/pom.xml: No group with name {version} -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

1. `git clone https://github.com/thomasdarimont/quarkus-ci-friedly-versions`
1. `mvn quarkus:dev`

### Output of `uname -a` or `ver`

Linux neumann 5.14.16-201.fc34.x86_64 #1 SMP Wed Nov 3 13:57:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724)

### Quarkus version or git rev

2.5.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

**Comment by famod** [comment]
Just yesterday #22131 was merged that will make the error message more clear:
It is not allowed as per Maven docs to use any placeholder _within_ `revision`, `sha` or `changelist`, see https://maven.apache.org/maven-ci-friendly.html#single-project-setup

![screenshot](https://user-images.githubusercontent.com/22860528/145908288-0524e6ec-b427-4b79-a653-6c8e2e51fec0.png)

So, instead of trying to support something that is basically ruled out in Maven, we now throw a clearer error message.

Ignoring Quarkus for a moment, even if this setup of yours seems to work, I strongly suggest to go with what the Maven docs suggest because I had a _very_ strange issue ~2 years ago and in the end it was caused by such illegal placeholders in `revision`.
This was _really_ hard to find!

**Comment by geoand** [comment]
Thanks for reporting.

@famod I assume this should be closed as `won't fix`?

**Comment by famod** [comment]
@geoand yes. I just wanted to give @thomasdarimont the opportunity to leave some feedback. But sure, this is also possible for closed issues so I'll close this now.
