### ISSUE TITLE
quarkus-bootstrap-maven-plugin is missing build-tree goal

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#22186]
### Describe the bug

By triggering `./mvnw quarkus-bootstrap:build-tree`
The following error is shown
```
Could not find goal 'build-tree' in plugin io.quarkus:quarkus-bootstrap-maven-plugin:2.5.2.Final among available goals extension-descriptor, help -> [Help 1]
```

### Expected behavior

Compile-time dependencies are shown by triggering `./mvnw quarkus-bootstrap:build-tree`

### How to Reproduce?

1. Add <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
2. Execute `./mvnw quarkus-bootstrap:build-tree`

### Output of `java -version`

AdoptOpenJDK-11.0.11+9

### Quarkus version or git rev

2.5.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by kshpak** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
It was replaced with `quarkus:dependency-tree` quite some time ago and then removed.
https://quarkus.io/guides/maven-tooling#logging-quarkus-application-build-classpath-tree
