### ISSUE TITLE
Update Yasson library to support java 17 records

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#22184]
### Description

Please update the [Yasson depedency to at least 2.0.3](https://github.com/eclipse-ee4j/yasson/releases/tag/2.0.3) for proper record support. Currently (2.5.2) only 1.0.9 is shipped.

Overriding the dependency to force 2.0.3 breaks the quarkus compilation:

```
Caused by: java.lang.ClassNotFoundException: jakarta.json.bind.spi.JsonbProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
```

**Comment by gsmet** [comment]
It's not possible to upgrade to 2.0.3 for the moment as that would mean moving to the `jakarta.*` packages globally. This is on our plan but we are not there yet.

**Comment by lostiniceland** [comment]
I assume this means waiting for Quarkus 3 due to the breaking API.

**Comment by lostiniceland** [comment]
@gsmet The Yasson team backported and improved the record support to the 1.x line and the release 1.0.11 is available on Maven Central. 
https://github.com/eclipse-ee4j/yasson/pull/499#issuecomment-1012990382

I will try to override the version in our project, but I am not sure if this will work with the quarkus-extension.

**Comment by gsmet** [comment]
@lostiniceland ah cool. I'm surprised Dependabot didn't upgrade it for us. It should have.

Would you mind creating a PR with the upgrade to the BOM and we will see what CI has to say?

**Comment by lostiniceland** [comment]
I am having some issue with running all tests locally (even before changing the BOM), which are probably caused by my local setup (had the same issue with Yasson due to localisation). 
`[ERROR]   ConfigPropertiesTest.configProperties:99 expected: <empty> but was: <localhost.localdomain>` 
Hence I pushed the PR without verifying locally and relying on the workflow. 
@gsmet somebody needs to approve the workflow to start the ci.
