### ISSUE TITLE
OIDC: better user-logout

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22199]
### Description

When using public OIDC providers, most sites will want to be able to logout of their site without logging the user out of the OIDC provider. For example, when I am on StackOverflow via Google OIDC, and I log out of StackOverflow, I most definitely don't want to log out of GMail. That's the last thing I want.

So there has to be a way for users to log out of OIDC without logging out of OIDC providers. ATM this is the code I have to do:

```java
    @Inject
    OidcConfig oidcConfig;

    @Path("/logout")
    public Response logout() {
        List<NewCookie> cookies = new ArrayList<>(oidcConfig.namedTenants.size() + 1);
        // Default tenant
        cookies.add(new NewCookie("q_session", null, "/", null, null, 0, false, true));
        // Named tenants
        for (String tenant : oidcConfig.namedTenants.keySet()) {
            cookies.add(new NewCookie("q_session_"+tenant, null, "/", null, null, 0, false, true));
        }
        // Manual
        cookies.add(new NewCookie("QuarkusUser", null, "/", null, null, 0, false, true));
        return Response.seeOther(Router.getURI(Application::index)).cookie(cookies.toArray(new NewCookie[0])).build();
    }
```

I'm pretty sure we should at the very least document such logout options in our guide, and perhaps we should also add an API to support logging out? Not sure what or where, but something as easy as:

```java
    @Inject
    SecurityIdentity identity;

    @Path("/logout")
    public void logout() {
        identity.logout();
    }
```

Not sure it belongs on `SecurityIdentity`, and not sure how to make it tell `quarkus-resteasy-reactive` about the response cookies required, but it would at least forward the logout request to all current `IdentityProvider` (in my case OIDC and JWT).

WDYT, @stuartwdouglas ?

**Comment by sberyozkin** [comment]
@FroMage Steph, i just wonder, are you even paying attention to what I say :-) ? I've probably said N times `OidcSession` will do it for you and I even CC-ed you on the draft PR.

It won't be `securityIdentity.logout`

but `oidcSession.invalidate` since it is a local logout.

Also, as I said, Google and other providers must have the way to say to them that no global logout is required,  please check and try `logout.extra-params` to request it

**Comment by sberyozkin** [comment]
I'm trying to create the tests as we speak

**Comment by FroMage** [comment]
Sorry I missed that `OidcSession` would do it. Fine then.

But that still leaves me with not knowing how to logout from JWT: https://quarkus.io/guides/security-jwt doesn't have the word "logout" for me to search.

I think we 'd benefit from having IdentityProviders provide a way to logout generically.

**Comment by FroMage** [comment]
I can't seem to get this to work.
