### ISSUE TITLE
OIDC: do not inspect every unauthenticated request for a `code` param

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22195]
### Describe the bug

ATM I have the impression that I hit the `CodeAuthenticationMechanism.authenticate` code path in every unauthenticated request, even when it wasn't called by the OIDC server as a callback.

This means that user applications are banned from ever using a `code` query param on all their unauthenticated endpoints, which is not acceptable.

This inspection of the `code` query param (or the form POST) should only ever happen when an OIDC server is calling us via a redirect, so this should be checked. Perhaps it should be a referrer check, but we can't simply look at `code` query params that are not related to OIDC, that's wrong. I even wonder if it's not a security bug TBH, because anyone can call any endpoint with `?code=something` and trigger an OIDC callback when there wasn't one.

I have a commit which fixed it trivially for my application: https://github.com/FroMage/quarkus/commit/9985e30de0a7dbe24cca15dc5b2a04f5bef45294

**Comment by FroMage** [comment]
Possibly related to https://github.com/quarkusio/quarkus/issues/12756

**Comment by sberyozkin** [comment]
I agree it is a problem but there was no obvious way to fix it, I agree to revisit

**Comment by FroMage** [comment]
Why not check the referrer and the URI?
