### ISSUE TITLE
OIDC: support Apple's JWT secret generation

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22194]
### Description

Apple needs a `clientId` which is a generated JWT token. We already have support for generating such tokens, but only when using `OidcConstants.CLIENT_ASSERTION` and `formBody.add(OidcConstants.CLIENT_ASSERTION_TYPE, OidcConstants.JWT_BEARER_CLIENT_ASSERTION_TYPE);`, but here we need it for `OidcConstants.CLIENT_SECRET`

I've added preliminary support for it in https://github.com/FroMage/quarkus/commit/af37d19d96303b342a4046bb011a8369d2e14cb2 which required being able to specify the type of secret key (otherwise `KeyUtils.readSigningKey` used the wrong value and it threw an exception).

I wasn't entirely happy with the way I handled configuration, but at least now I can use:

```
quarkus.oidc.apple.auth-server-url=https://appleid.apple.com/
quarkus.oidc.apple.application-type=web-app
quarkus.oidc.apple.client-id=SECRET
quarkus.oidc.apple.credentials.jwt.key-file=SECRET
quarkus.oidc.apple.credentials.jwt.key-algorithm=ES256
quarkus.oidc.apple.credentials.jwt.token-key-id=SECRET
quarkus.oidc.apple.credentials.jwt.signature-algorithm=ES256
quarkus.oidc.apple.credentials.jwt.audience=https://appleid.apple.com
quarkus.oidc.apple.credentials.jwt.issuer=SECRET
quarkus.oidc.apple.credentials.jwt.subject=SECRET
quarkus.oidc.apple.authentication.scopes=openid,email,name
quarkus.oidc.apple.authentication.redirect-path=/Login/oidcLoginSuccess
```

**Comment by sberyozkin** [comment]
@FroMage Can you please reuse `signature-algorithm` instead of creating a new property for `key-algorithm`, `KeyUtils` has another method accepting an algo type, `KeyUtils.readSigningKey` overload exists which takes `SignatureAlgorithm` as an extra param

**Comment by sberyozkin** [comment]
@FroMage I've assigned you, I think your changes are looking good, I've only proposed to reuse the existing property and introduce a dedicated `POST_JWT` authentication method enum to avoid the ambiguities; please open a PR, I'll help with the wiremock test

**Comment by FroMage** [comment]
Done: https://github.com/quarkusio/quarkus/pull/22246

**Comment by FroMage** [comment]
Verified, thanks.
