### ISSUE TITLE
OIDC: log authentication errors

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22191]
### Describe the bug

There are many times when I had authentication fail and produce a 401 after coming back from the OIDC provider without me knowing or guessing why. No logs were produced, and https://quarkus.io/guides/security-openid-connect-web-authentication#how-to-check-the-errors-in-the-logs did not help as no error was produced.

Also that config is just way too complicated.

We should audit the OIDC code for anything that can return a direct response to the user (401 or anything else), to make sure that they can all be logged if the user wants them logged (during dev).

I'd make this configurable via `quarkus.oidc.log.failures=true` (or whatever name) instead of configuring two loggers that seem to be internal implementation details.

**Comment by sberyozkin** [comment]
@FroMage Hi Steph, I think the logs have improved in this regard, I added logs everywhere in the OIDC  when I was chasing flaky test failures and I recall you contributed as well with adding some messages so let me close this one and please create new issues if you spot the lack of info being logged in some cases, thanks

**Comment by Sanne** [comment]
As a user, let me add that adding logs is not good enough when I don't know which ones I should be enabling :)
Please mention this in the guides? A troubleshooting section would be great.

**Comment by FroMage** [comment]
> I'd make this configurable via quarkus.oidc.log.failures=true (or whatever name) instead of configuring two loggers that seem to be internal implementation details.

I agree with @Sanne, is it mentioned in the guide? Do we have a single config to enable these logs?

**Comment by sberyozkin** [comment]
Hi @FroMage @Sanne 

There will be a better logging output for the case related to the wrong redirect URI, done as part of #41890

I've been reviewing log calls now and then and as far as I know, most or all of them related to the authentication failures are warn or error level, it is just that in case of the redirect failures the data available in the response from OIDC/OAuth2 providers is not logged yet, but will be.

**Comment by FroMage** [comment]
OK, so in this case, no special config for logging is required, and documentation doesn't need to be updated, fine, thanks a lot!
