### ISSUE TITLE
RESTEasy Reactive: clarify `@RestForm File` value when not set

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22207]
### Describe the bug

I expected a `@RestForm File file` parameter to be `null` when the user didn't send it in the request, but it was a valid `File` instance of `zero` length.

I think this can be confusing because it doesn't let endpoints differentiate between:

- the user did not set it
- the user provided an empty file

I'm not sure if this was intentional, but the docs don't mention it.

**Comment by geoand** [comment]
Is this with `multipart` type? If so, I could not reproduce it.

**Comment by FroMage** [comment]
Damn. My bad. The browser does send an empty file:

```
------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="_renarde_crsf_token"

YE62OMfehS6+PxmdyQFo1g==
------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="title"

asdasd
------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="releaseDate"

2021-12-16
------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="removePhoto"

false
------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="photoUrl"


------WebKitFormBoundaryiNacmoCng7FwpmdR
Content-Disposition: form-data; name="photo"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryiNacmoCng7FwpmdR--
```

OK. So… I guess that'd be a browser issue. Thanks!

**Comment by geoand** [comment]
👍🏼
