### ISSUE TITLE
RESTEasy Reactive: add ability to invoke filters once the form parameters are read

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22209]
### Description

I need to set a filter that checks every `POST` request for the existence of a CRSF value, but when my filter is invoked, the form is not read yet:

```java
    @ServerRequestFilter
    public void filterRequest(HttpServerRequest req) {
        // check CRSF param for every method except the three safe ones
        if (req.method() != HttpMethod.GET
                && req.method() != HttpMethod.HEAD
                && req.method() != HttpMethod.OPTIONS) {
            //FIXME: can't do this for now because form values are not read when filter is invoked
            CurrentVertxRequest currentVertxRequest = CDI.current().select(CurrentVertxRequest.class).get();
            ResteasyReactiveRequestContext rrContext = (ResteasyReactiveRequestContext) currentVertxRequest
                    .getOtherHttpContextObject();
            FormData formData = rrContext.getFormData();
        }
    }
```

It would be nice to have an option to delay filters to after the form is read, perhaps with `@ServerRequestFilter(readBody = true)`

**Comment by geoand** [comment]
Sounds interesting

**Comment by FroMage** [comment]
OK, so funny thing: this works when the endpoint has `@FormParam` elements that forces us to read the body, but doesn't when the endpoint is a `@POST` method with zero `@FormParam`. Can we force the body reading if we have filters like that? Should I open a new issue?

**Comment by geoand** [comment]
We probably can. Please open a new issue

**Comment by FroMage** [comment]
Done, thanks!

**Comment by jimbogithub** [comment]
@FroMage Are you able to describe the exact circumstances under which this will currently work?  I need a filter to do an HMAC calc for security reasons and it needs all the form data.  I'm using `@ServerRequestFilter(readBody = true)` for the filter and the endpoint is `@POST` with multiple `@FormParam`s.  This seems to fit with what you describe above but in my case the `FormData` is still always null. (2.9.2.Final)

I can't do the calc just from the individual `@FormParam`s as the caller may include fields I'm unaware of that still need to be in the HMAC.

This was easy with REST Classic and is currently a showstopper for migrating to Reactive.

**Comment by jimbogithub** [comment]
Resolved.  Needed to `req.setExpectMultipart(true)` add use a binding to ensure it only applies to endpoints expecting form data, e.g.

```
@HMACAuthenticated
@ServerRequestFilter(readBody = true)
public void filterRequest(HttpServerRequest req) {
    req.setExpectMultipart(true);
}
```
