### ISSUE TITLE
RESTEasy Reactive client: add User-Agent

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22214]
### Describe the bug

Most websites straight-up refuse REST calls without a `User-Agent`. GitHub's API does. We should probably set one by default, otherwise users have to do:

```java
@ClientHeaderParam(name = "User-Agent", value = "MP REST") 
@RegisterRestClient
@Path("/")
public interface GithubClient {
}
```

And the problem is that if this value is missing, all calls will fail with an exception which does not log the GitHub response, so it takes quite a while to figure out why it fails (see https://github.com/quarkusio/quarkus/issues/22213).

**Comment by geoand** [comment]
How about also adding the ability to do this in config?

**Comment by sberyozkin** [comment]
By the way @FroMage, this will also work with the oidc-token-propagation-reactive (filter) once it is available, will open a sep issue

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22236 is what I have in mind

**Comment by FroMage** [comment]
Hang on, this doesn't appear to add a user-agent… Ah, it's #22228, fine!
