### ISSUE TITLE
OIDC: cannot use oidc-token-propagation with RESTEasy Reactive

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22216]
### Description

I wanted to use it to propagate my GitHub access token on a REST call to their API, but it depends on RESTEasy Classic, which clashes with the RESTEasy Reactive I'm using.

### Implementation ideas

We have already created a reactive `OidcClientFilter`  version with @geoand so the same should be done for `oidc-token-propagation` - I'll be OK with the current `oidc-token-propagation` be moved to Quarkiverse if necessary - though may be, since the reactive version will be light, it can coexist in the Quarkus repository.

**Comment by sberyozkin** [comment]
I've also added the implementation ideas here: #22217

**Comment by geoand** [comment]
So let's close this as a duplicate

**Comment by geoand** [comment]
My bad, reopening

**Comment by sberyozkin** [comment]
@geoand I've already closed the other one :-), I don't mind, which you prefer to reopen :-) ?

**Comment by sberyozkin** [comment]
Cool :-)

**Comment by geoand** [comment]
Done :)

**Comment by uPagge** [comment]
So is there any progress in this direction. I'm curious, since I also ran into this problem :)

**Comment by geoand** [comment]
@sberyozkin any way I can help with this one?

**Comment by sberyozkin** [comment]
Oops, I was actually looking for this issue number to open a PR, so apologies I did not reply earlier. I've no idea why I'm keeping missing so many notifications.
