### ISSUE TITLE
Rest Client Reactive default methods fail with Kotlin

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#22231]
### Describe the bug

Using a default method in a Kotlin interface defining a REST client results in an `AbstractMethodError` being thrown.

### Expected behavior

Default methods should be usable in REST client methods. This is expected behavior according to https://github.com/quarkusio/quarkus/issues/19226#issuecomment-958958661

### Actual behavior

`AbstractMethodError` is thrown for any defined default methods.

### How to Reproduce?

1. Run the Quarkus application
1. Use `curl -v http://localhost:8080/todos/block` to see failure in a blocking method.
1. Use `curl -v http://localhost:8080/todos/co` to see failure in a Kotlin coroutine.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7716460/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

macOS 12.0.1

### Output of `java -version`

17

### Quarkus version or git rev

2.6.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
I don't think we should fix this on our side actually, because it's very easy to work around the problem by adding:

```xml
          <args>
            <arg>-Xjvm-default=all</arg>
          </args>
``` 

in the `configuration` section of the `kotlin-maven-plugin`.

@michalszynkiewicz, @evanchooly do you agree?

**Comment by kdubb** [comment]
The only issue I have with this is that it is infectious, you have to remember to add this to all projects. When it fails it's pretty easy to miss that it's the default methods that are causing it. It would be nice for it to "just work" or to have a warning/error generated.

That being said it seems like this is basically a Kotlin issue.

**Comment by kdubb** [comment]
@geoand FYI, I did not know about this option previously. Thank you for the fix workaround.
