### ISSUE TITLE
Rest Client Reactive ignores `ParamConverter`s for enums

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#22232]
### Describe the bug

Using rest client reactive, enum parameters are not converted to strings using a provided `ParameterConverter`. Instead the standard enum `name` is used.

### Expected behavior

When a `ParameterConverter` is provided in the app enums should be converted to strings using its `toString(T)` method.

### Actual behavior

Registered `ParamConverter`s are ignored for enum types and the enum `name` is used.

### How to Reproduce?

1. Run the Quarkus Application.
2. `curl http://localhost:8080/test` should return enums converted with `CustomEnumConverter`.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7717192/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

macOS 12.0.1

### Output of `java -version`

17

### Quarkus version or git rev

2.6.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by gsmet** [comment]
@kdubb would you have the time to prepare a draft PR with a proper test included in the test suite? That would be a good first step to get this fixed.

**Comment by kdubb** [comment]
I can look into this. I assume this is the same issue as #22287.

**Comment by michalszynkiewicz** [comment]
I started working on #22287, will assign this one to myself too
