### ISSUE TITLE
Add support for transactional observer event

### ISSUE THREAD

**Issue by kirill-kosenko** [quarkusio/quarkus#2224]
Hi guys!

I need to fire event after transaction success
In this example event is fired immediately
Is this the correct example?
Or I missed something?

`@ApplicationScoped`
`public class FruitService {`

    @PersistenceContext
    EntityManager entityManager;

    @Inject
    Event<Fruit> fruitCreatedEvent;

   
    @Transactional
    public Fruit save(Fruit fruit) {

        entityManager.persist(fruit);
        fruitCreatedEvent.fire(fruit);

        return fruit;
    }
`}`

`@ApplicationScoped`
`public class FruitListener {`

    public void onEvent(@Observes(during = TransactionPhase.AFTER_SUCCESS) Fruit fruit) {
        ...
    }
`}`

**Comment by emmanuelbernard** [comment]
@mkouba can you chime in?

**Comment by mkouba** [comment]
So [transactional observer methods](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#transactional_observer_methods) are not supported at the moment. We could propose some JTA integration SPI but as always it depends on priority...

**Comment by wargun02** [comment]
Yes please. This feature is indeed very important.

**Comment by famod** [comment]
We are currently evaluating which way to go for migration a not so moduluar monolith based on JBoss EAP 6.4 and Quarkus seems promising but we use `TransactionPhase` quite often.
So a strong+1 from me!

**Comment by anadollu** [comment]
We need so much this feature  when migrating legacy applications to quarkus. Please consider to schedule implementation of it

**Comment by donkon** [comment]
this seems to be also the only missing functionality for migrating our existing Wildlfly based application to Quarkus

**Comment by manovotn** [comment]
I will look into this sometime next week and see how it can be done.
We will probably need an API similar to what Weld uses.
