### ISSUE TITLE
NativeMojo should add -H:+ReportExceptionStackTraces by default

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#2226]
As seen in this #2222 issue, the default output from a failed native image build is usually a useless message telling you to add -H:+ReportExceptionStackTraces. We should have a mapping for the -H:+ReportExceptionStackTraces flag on the NativeImageMojo and set this to true by default.

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/2411. Closing.
