### ISSUE TITLE
Unexpected need to @Unremoveable on a CDI bean

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#22268]
### Describe the bug

I have a REST ClientRequestFilter, which is a CDI bean.
W/o @Unremoveable it's not properly resolved when Quarkus' generated REST client is invoked

```
@ApplicationScoped
@Provider
//@Unremovable
public class TestFilter implements ClientRequestFilter {
```

### Expected behavior

There should be no need to @Unremoveable.

### Actual behavior

@Unremoveable is required.

### How to Reproduce?

https://github.com/alesj/quarkus_cl130/tree/unremove1

Ands run the app -- via IDE + Main class, or `mvn quarkus:Dev`

### Quarkus version or git rev

2.5.2.Final

**Comment by alesj** [comment]
@geoand ^

**Comment by alesj** [comment]
https://gist.github.com/alesj/1363a90de89d9ba535a2fe6148457e58

**Comment by geoand** [comment]
When running the reproducer I am getting the error described in https://github.com/quarkusio/quarkus/issues/22149

**Comment by mkouba** [comment]
It seems that providers are only marked as unremovable in the server part: https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L647-L649.

**Comment by glefloch** [comment]
Adding a `@RegisterProvider(TestFilter.class)` annotation on your rest-client will register the provider as unremovable bean. I don't know if we should register all `@Provider` as unremovable beans. WDYT @geoand @mkouba ?

**Comment by geoand** [comment]
Ah, right! Good point @glefloch. I don't remember what the speci says about the REST Client  and Providers. @michalszynkiewicz do you remember?

**Comment by gsmet** [comment]
@alesj can you confirm adding `@RegisterProvider(TestFilter.class)` works? If so, that's how you should do it and we should close this issue.

**Comment by alesj** [comment]
> can you confirm adding @RegisterProvider(TestFilter.class) works?

Yes, that works.
