### ISSUE TITLE
Quarkus REST client should support method validation

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#22267]
### Describe the bug

Currently there is no Quarkus REST client support

### Expected behavior

Custom REST client method validation should kick-in and report any violations

### Actual behavior

Custom REST client method validation is ignored

### How to Reproduce?

https://github.com/alesj/quarkus_cl130/tree/restval1

Simply run that app's Main class
(or `mvn quarkus:dev`)

### Quarkus version or git rev

2.5.2.Final

**Comment by alesj** [comment]
@gsmet ^

**Comment by gsmet** [comment]
As promised I had a look. I created a PR for your repository here: https://github.com/alesj/quarkus_cl130/pull/1 .

Executive summary: it won't work with the traditional REST Client given it uses JDK proxies but it works out of the box with REST Client Reactive.

**Comment by gsmet** [comment]
Closing as we really don't want to invest in fixing the traditional REST Client as it would require a complete change of how it works. We just need to get the Reactive REST Client up to speed so let's focus on the other issues reported.
