### ISSUE TITLE
@Inject inside JAX-RS Application subclass not working with 2.x (ok with 1.6)

### ISSUE THREAD

**Issue by geca** [quarkusio/quarkus#22277]
### Describe the bug

After upgrading Quarkus from 1.6.1.Final to 2.5.Final the following `@Inject` fails inside `javax.ws.rs.core.Application` subclass:

```java
@ApplicationScoped
public class MyBean {

    public String foo() {
        retun "bar";
    }
}
```

```java
@ApplicationPath("/")
public class MyApplication extends Application {

    @Inject
    MyBean myBean;

    @Override
    public Set<Class<?>> getClasses() {
        myBean.foo(); // Causes NPE on Quarkus 2.5.1.Final, worked well with 1.6.1.Final
    
    }
}
```

### Expected behavior

`myBean` instance above should not be null

### Actual behavior

`myBean` instance is null

### How to Reproduce?

See bug description.

### Output of `java -version`

jdk-11.0.12.7-hotspot

### Quarkus version or git rev

2.5.1.Final

**Comment by mkouba** [comment]
Does your app use `quarkus-resteasy` or `quarkus-resteasy-reactive`?

**Comment by geca** [comment]
Hi @mkouba , we use `quarkus-resteasy-jackson` (that brings in `quarkus-resteasy`).

**Comment by mkouba** [comment]
Hm, how do you access the `MyApplication` instance? It seems that resteasy extension does not suppor injecting `javax.ws.rs.core.Application` subclasses into resources via `@Context`... @geoand knows a way more about JAX-RS in quarkus though ;-) ...

**Comment by geca** [comment]
`quarkus-resteasy` intializes `MyApplication`. However, with Quarkus 2.x this seems to happen before ARC/CDI is set up, hence `@Inject MyBean myBean;` does not work (ie. `myBean` is null inside `getClasses`). This worked ok on 1.6.1.

**Comment by geca** [comment]
@mkouba Update: the same issue also happens with 1.13.x, meaning the regression wasn't introduced with 2.x as I stated above. The latest version that works for me is 12.2.Final.
