### ISSUE TITLE
Quarkus kubernetes/openshift/minikube extension should allow for common resources

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#22290]
Following the [use existing resources section of the Quarkus Kubernetes Guide](https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources) it mentions I can place files in `src/main/kubernetes` that will be picked up by the extensions.

It says

   > Those resources can be added under src/main/kubernetes directory and can be named after the target environment (e.g. kubernetes.json, openshift.json, knative.json, or the yml equivalents). Each of these files may contain one or more Kubernetes resources.

What if I have some resources that I want added to the generated `kubernetes.yml` and `openshift.yml`? It seems that only specific filenames of `kubernetes.yml` or `openshift.yml` are picked up in `src/main/kubernetes`. What if I have a resource, like a `ConfigMap`, that I want to appear in all the generated descriptors? Do I need to create both a `src/main/kubernetes/kubernetes.yml` and a `src/main/kubernetes/openshift.yml` with the same content?

@edeandrea indeed you do. @iocanel maybe it makes sense to improve on that somehow

_Originally posted by @geoand in https://github.com/quarkusio/quarkus/discussions/22258#discussioncomment-1820957_

**Comment by iocanel** [comment]
I have fixed that upstream: https://github.com/dekorateio/dekorate/pull/942.
Will pick the fix up on next dekorate release.

**Comment by edeandrea** [comment]
Thank you @iocanel ! When this gets pulled into Quarkus will [the documentation](https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources) be updated as well, showing how to use the feature?

**Comment by geoand** [comment]
@Sgitario mind updating the docs to reflect that we know support this feature?

Thanks

**Comment by Sgitario** [comment]
@iocanel was going to update it, but first Dekorate needs to release this change and Quarkus needs to be updated accordingly.

**Comment by geoand** [comment]
Oh, I thought that was already done

**Comment by edeandrea** [comment]
Hi @Sgitario / @iocanel Do you know if this has been released in dekorate yet?

**Comment by Sgitario** [comment]
Dekorate's bump version will be done in https://github.com/quarkusio/quarkus/pull/26303, which will include this feature.

**Comment by edeandrea** [comment]
Hey @geoand / @Sgitario has this been done? If it was, I don't see anything in the documentation (https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources) describing how to use this?

**Comment by geoand** [comment]
I doubt it, it probably slipped through the cracks, but @Sgitario would know more.

**Comment by edeandrea** [comment]
Sounds good. The ticket he referenced (#26303) seems to be closed, so if it is "in" I don't know how to use it.

**Comment by Sgitario** [comment]
Yes, this should be already supported as the changes in https://github.com/dekorateio/dekorate/pull/942 are included in the Dekorate version, but indeed we need to update the documentation and perhaps also some tests. 
I need to figure out how it works, and then I will provide a PR with this.

**Comment by Sgitario** [comment]
It seems that the changes in https://github.com/dekorateio/dekorate/pull/942 were not relevant for Quarkus. Therefore, I've created a pull request to implement this feature, and also to document it.
