### ISSUE TITLE
Remove vertx-kafka-client dependency

### ISSUE THREAD

**Issue by ozangunalp** [quarkusio/quarkus#22295]
### Description

Extension for SmallRye Ractive Messaging Kafka depends on vertx-kafka-client whereas the former doesn't have that dependency anymore.

The dependency is currently there solely for configuring a couple of serde classes for Vert.x types such as JsonObject, JsonArray and Buffer.

In addition, vertx-kafka-client depends on the 2.6.0 version of kafka-clients, which is no more compatible with the latest version (3.0.0 at the time). The transitive dependency exclusion is in place but it causes some confusion : #22000, https://github.com/kiegroup/kogito-examples/pull/1022

### Implementation ideas

Removing this would be a breaking change as we'll remove the mentioned serde classes completely or at least "provide" them inside the Quarkus extension with a different package name.

**Comment by cescoffier** [comment]
This is planned for after 2.7 (so 2.8 :-D)

**Comment by cescoffier** [comment]
@ozangunalp should we move forward as part of Quarkus 3.0?

**Comment by cescoffier** [comment]
@ozangunalp Friendly reminder of your last comment :-D

**Comment by cescoffier** [comment]
@ozangunalp probably the right time to do it.
