### ISSUE TITLE
Augmentation uses http.port if set instead of default http.test-port

### ISSUE THREAD

**Issue by brunoborges** [quarkusio/quarkus#2229]
If `application.properties` has `quarkus.http.port` set (e.g. `80`) alone, then augmentation during build will try to start the server in this port instead of default value in `quarkus.http.test-port`.

Workaround is to manually set `quarkus.http.test-port` as well.

**Comment by stuartwdouglas** [comment]
Where are you observing this? Is this using @SubstrateTest, @QuarkusTest or @QuarkusUnitTest?

This code in question does `return launchMode == LaunchMode.TEST ? testPort : port;` so I am not sure why this would be happening.

**Comment by brunoborges** [comment]
I got a plain project with one REST endpoint, and running in JVM mode.

**Comment by gsmet** [comment]
Closing as out of date. Please reopen with clear instructions on how to reproduce it if it still happens.
