### ISSUE TITLE
QuarkusMainTest intercepts spurious strings

### ISSUE THREAD

**Issue by andreaTP** [quarkusio/quarkus#22302]
### Describe the bug

The `QuarkusMainTest`s are spuriously intercepting output coming from different sources.

### Expected behavior

The `QuarkusMainTest`s report back only the output from the specific launched `Process`.

### How to Reproduce?

I started reducing the error down to a test in this codebase.

In `io.quarkus.it.picocli.PicocliTest` add the following test:

```java
    @Test
    public void testLogCapturing(QuarkusMainLauncher launcher) {
        org.jboss.logging.Logger.getLogger("test").error("error");
        LaunchResult result = launcher.launch("with-method-sub-command", "hello", "-n", "World!");
        assertThat(result.exitCode()).isZero();
        assertThat(result.getOutput()).isEqualTo("Hello World!");
    }
```

and the test will fail with an error similar to:

```bash
[ERROR] Failures: 
[ERROR]   PicocliTest.testLogCapturing:43 
expected: "Hello World!"
 but was: "2021-12-16 19:28:23,647 ERROR [test] (main) error
Hello World!"
[INFO] 
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0
```

The expectation is that the test should pass.

### Quarkus version or git rev

`main`

**Comment by DGuhr** [comment]
I've spent quite a few hours on this, thanks for the fix Andrea :)

**Comment by andreaTP** [comment]
You actually found it @DGuhr 👍

**Comment by gsmet** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/22303.
