### ISSUE TITLE
Gradle: quarkusBuild does not recognize configured Java Toolchain and/or defined 'compileJava.options.forkOptions.executable'

### ISSUE THREAD

**Issue by marcelhanser** [quarkusio/quarkus#22310]
Hey Quarkus-Team

Im experimenting with the java gradle toolchain, which downloads a jdk during gradle execution if necessary.
Example:
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```
If i use this configuration and execute 'gradle quarkusBuild with a jdk11 i get following issue:

> Execution failed for task ':quarkusBuild'.
 ... has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 

The same problem occurs if i try to set the compileJava executable explicitly:
```
compileJava.options.forkOptions.executable = '.../jdk-unzipped/17.0.1/bin/javac'
```

Is there configuration or workaround how i could set the JDK to use for quarkusBuild or quarkusDev?

Best & Thx
Marcel

**Comment by marcelhanser** [comment]
just seen its a duplicate:
https://github.com/quarkusio/quarkus/issues/20452

**Comment by glefloch** [comment]
@marcelhanser are you also using the `apache-cxf` extension ?

**Comment by marcelhanser** [comment]
No i dont - i attached my mini sample project in https://github.com/quarkusio/quarkus/issues/20452 i think a custom ConfigSource is the trigger
