### ISSUE TITLE
The connection exception handler of redis vertx is not called if I manually kill the redis connection

### ISSUE THREAD

**Issue by digitalsamba** [quarkusio/quarkus#22337]
### Describe the bug

I am establishing a standard redis connection with the vertx extension, and then I kill manually the connection through the redis-cli - "client kill id XXXX", or simply restarting the docker container of redis can be used. I don't see the **conn.exceptionHandler** being called. Is that normal/expected? If yes, then how can I detect that my redis connection dropped? Do I need to write a timer which polls/pings redis every second or so? That exceptionHandler callback is called only if a command execution fails - e.g. if I execute a ping command while the connection is dead. But if I add a manual ping, I would know Redis is down anyway, so I don't see the point of exceptionHandler callback.

P.S. I am using latest Quarkus version - 2.5.3.Final.

### Expected behavior

I should have a way to detect through a callback that the redis connection dropped

### Actual behavior

No error is getting thrown, callback is not called.

### How to Reproduce?

```
Redis redisClient = Redis.createClient(vertx, connectionString);
			RedisObjects result = new RedisObjects(redisClient);
			redisClient.connect()
			    .onSuccess(conn -> {			    	
			    	LOG.infof("Successfully connected to redis instance for publishing at = %s", connectionString);			    	
			    	result.setRedisConnection(conn);
			    	
			    	conn.exceptionHandler(e -> {
			    	        //This callback is not called on killing the connection manually!!!
			    		LOG.errorf(e, "Exception occurred in an existing publishing redis connection to %s", connectionString);
			    	});	
			    })
			    .onFailure(e -> {
			    	LOG.errorf(e, "Could not connect to redis instance for publishing at = %s", connectionString);
			    });
			return result;
		});
```

### Quarkus version or git rev

2.5.3.Final

**Comment by geoand** [comment]
cc @pmlopes

**Comment by cescoffier** [comment]
This issue should be reported in Vert.x. Quarkus can't do anything. Please re-open it at https://github.com/vert-x3/vertx-redis-client
