### ISSUE TITLE
Source filter/search in scheduler Dev UI

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#22335]
### Description

Having many scheduled jobs/methods, I'd like to filter or search the "Source" column on the scheduler page in Dev UI, similar to what you can do in the config editor.

**Comment by mkouba** [comment]
How many scheduled methods do you have? Wouldn't Ctrl + F be good enough? 😉

**Comment by famod** [comment]
We'll soon be reaching ~50 I guess.

Sure, Ctrl + F works, but filtering has the benefit that everything else is...well... filtered out. So when you are only interested in a specific job class, you would then only see the methods of that class.

It's clearly not a killer feature, but to me feels worth having. YMMV!
