### ISSUE TITLE
new java.io.File(TOKENS_DIRECTORY_PATH) path is not found when app is packaged in docker.jvm

### ISSUE THREAD

**Issue by richard457** [quarkusio/quarkus#22338]
### Describe the bug

I have a folder called tokens in my root folder of the project I can access it in my code with new java.io.File(TOKENS_DIRECTORY_PATH)

### Expected behavior

Should access file with no problem

### Actual behavior

I can access the file when running quarkus dev but when I packaged the app with docker.jvm the file becomes not found.

### How to Reproduce?

reproduced:
1. have a folder in root project 
2. call the file in code like new java.io.File(TOKENS_DIRECTORY_PATH)
3. then do gradle build
4. docker build -f src/main/docker/Dockerfile.jvm -t quarkus/flipper-jvm .
5. docker run -i --rm -p 8080:8080 -e="WWW" quarkus/flipper-jvm
6. The file will be not found !

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.9.1 (AdoptOpenJDK 11.0.9.1+1) OS:           Windows 10 10.0 amd64

### Additional information

Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.9.1 (AdoptOpenJDK 11.0.9.1+1)
OS:           Windows 10 10.0 amd64

**Comment by alexcheng1982** [comment]
Can you please paste your `Dockerfile.jvm` file?

By default only files in `target/quarkus-app` will be copid to the image.

**Comment by stuartwdouglas** [comment]
What is in your .dockerignore ?

**Comment by richard457** [comment]
Dockerfile.jvm ```####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the container image run:
#
#(fix for building native windows)  https://github.com/oracle/graal/issues/1852#issuecomment-572892384
# ./gradlew build
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/flipper-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 -e="WWW" quarkus/flipper-jvm
#
# If you want to include the debug port into your docker image
# you will have to expose the debug port (default 5005) like this :  EXPOSE 8080 5005
#
# Then run the container using :
#
# docker run -i --rm -p 8080:8080 -p 5005:5005 -e JAVA_ENABLE_DEBUG="true" quarkus/flipper-jvm
#
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4 

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
    && microdnf update \
    && microdnf clean all \
    && mkdir /deployments \
    && mkdir /deployments/db \
    && chown 1001 /deployments \
    && chown 1001 /deployments/db \
    && chmod "g+rwX" /deployments \
    && chmod "g+rwX" /deployments/db \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh \
    && echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/conf/security/java.security

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=1001 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=1001 build/quarkus-app/*.jar /deployments/

COPY --chown=1001 build/quarkus-app/app/ /deployments/app/
COPY --chown=1001 build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]

```

**Comment by richard457** [comment]
.dokerignore ```*
!build/*-runner
!build/*-runner.jar
!build/lib/*
!build/quarkus-app/*```

**Comment by alexcheng1982** [comment]
You are using the default `Dockerfile.jvm`.  You need to modify it to add extra files.

Replace `TOKENS_DIRECTORY_PATH`  with the actual directory name.

```Dockerfile
COPY --chown=1001 ./<TOKENS_DIRECTORY_PATH> /deployments/<TOKENS_DIRECTORY_PATH> 
```

Also modify `.dokerignore` to add `!<TOKENS_DIRECTORY_PATH>/*`.

Reference: Dockerfile's [`COPY`](https://docs.docker.com/engine/reference/builder/#copy).

**Comment by richard457** [comment]
yes, thanks @alexcheng1982 this worked.
