### ISSUE TITLE
Adding Test suites/collections/profiles to :dev

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#22345]
### Description

What would make the amazing `dev` experience even nicer would be the possibility to add different test "profiles" or "suites" that can be triggered via keystroke, besides the `r` for (re-)running the tests.

Example: Run my unit tests (that I've defined with `.*UnitTest`) with pressing `t` and `1`, run my UI tests (defined with `.*UITest`) with `t` + `2`, and so on.

Right now, I am running the `dev` mode in different versions of `quarkus.test.{exclude,include}-pattern`, but that requires a restart every time, I'm in a different "testing mode".

How we could do that is to define the different suites in the build Quarkus plugin section, or via property, such as `quarkus.test.suite[index].{exclude-include}-pattern` (`suite` only being a suggestion).

WDYT?

**Comment by famod** [comment]
Might also be nice to select from existing `@Tag` values.

**Comment by stuartwdouglas** [comment]
@sdaschner does the linked PR meet your needs? Basically it makes it easy to select which tests are enabled based on tags. e.g.:

```
:test tags include myTag
```

There are lots of other things I could do here in terms of the user experience. 

Also note that this supports aliases, so you can do:

```
alias 'ui=test tags include uitest --run=true'
```

Which would set the current tags to uitest and run all the tests, ever time you entered ':ui'.

**Comment by stuartwdouglas** [comment]
I have expanded it to include patterns. You example from above could be:
```
alias 'ui=test pattern include .*UITest -d -r'
```

Then typing `:ui` will run all your UI tests and set the filters.

**Comment by sdaschner** [comment]
This sounds very promising! But stupid question: how do you get into this "command mode" (while in `quarkus:dev` or `quarkus:test`)? I've had a look at the code and tried pressing `:`, but no effect.

Using Quarkus `2.6.0.Final` and Maven `3.6.3`.

**Comment by stuartwdouglas** [comment]
This is a new thing that is upstream only, so will be part of 2.7.

Controlling tests like this was always one of the planned features.

Stuart

**Comment by sdaschner** [comment]
Oh nice, ok let me try that out, maybe the current features help a lot already :)

**Comment by sdaschner** [comment]
Just tried it, works really well! I like the command mode

One thing that I actually wanted to have: is it possible to assign (or use) a custom shortcut? maybe it's possible to assign a fixed 'function' hotkey and then assign some second keystroke (similar to aliases) that can be assigned by the user? So, e.g. `f + 1` or something, so that one doesn't have to type `:ui<Enter>`, but can start it from the normal dev view.

**Comment by famod** [comment]
> Just tried it, works really well! I like the command mode 👍

Thanks for letting us know. I have just merged the PR.

> One thing that I actually wanted to have: is it possible to assign (or use) a custom shortcut? maybe it's possible to assign a fixed 'function' hotkey and then assign some second keystroke (similar to aliases) that can be assigned by the user? So, e.g. `t + 1` or something, so that one doesn't have to type `:ui<Enter>`, but can start it from the normal dev view.

Can you file another enhancement for this? Thanks!
