### ISSUE TITLE
quarkus-quickstarts/hibernate-orm-resteasy Postgres for tests is not stopped during mvn package

### ISSUE THREAD

**Issue by lkrzyzanek** [quarkusio/quarkus#2235]
When following quick start https://github.com/quarkusio/quarkus-quickstarts/tree/master/hibernate-orm-resteasy#building-the-demo then `mvn package` correctly start the postgres for tests but doesn't stop it.
It leads to error when trying to run the demo by `docker run ....  postgres:10.5`
```
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name quarkus_test -e POSTGRES_USER=quarkus_test -e POSTGRES_PASSWORD=quarkus_test -e POSTGRES_DB=quarkus_test -p 5432:5432 postgres:10.5
docker: Error response from daemon: driver failed programming external connectivity on endpoint quarkus_test (10e54180c8113abed012a33b26789dd2b9e37a086079cbaee54977f8ab5f2f2e): Bind for 0.0.0.0:5432 failed: port is already allocated.
```

The fix is easy - just attach `docker-stop` execution to `prepare-package` phase instead of `post-integration-test`
https://github.com/quarkusio/quarkus-quickstarts/blob/master/hibernate-orm-resteasy/pom.xml#L145

**Comment by emmanuelbernard** [comment]
Moved to https://github.com/quarkusio/quarkus-quickstarts/issues/171
