### ISSUE TITLE
Add test inheritance example to docs

### ISSUE THREAD

**Issue by davidmoshal** [quarkusio/quarkus#22356]
### Description

Current docs don't show how to create a test hierarchy.   
ie: a base test class with dependencies injected.
It's a simple thing to do, but adding this to the docs could save time researching and experimenting.

### Implementation ideas

An easy solution is to annotate the base class with  `@QuarkusTest` and the test subclass with `@Dependent`:
```kotlin
@QuarkusTest
class BaseQuarkusTest{
    @Inject
    lateinit var db:DependencyA
}

@Dependent
class Test1 : BaseQuarkusTest() {

}
```

**Comment by geoand** [comment]
The code is not really correct.

You would annotate `Test1` with `@QuarkusTest` and not with `@Dependent` and remove `@QuarkusTest` from `BaseQuarkusTest`

**Comment by davidmoshal** [comment]
Nope, works perfectly well as is.

**Comment by geoand** [comment]
It works, but it's the proper usage

**Comment by davidmoshal** [comment]
Ok, got it, though curious that both ways work, no?

There are a couple of additional mysteries btw.

a) Your way actually doesn't need the @Dependent on the base class, which I don't understand.

2) Additionally with your way the base class has to be an 'open class' wheres my way it does not.
  - I am using the allOpen library, so it's odd that it behaves differently.

I do have a separate question, I'll open an issue for that: mocking time doesn't seem to work in Quarkus, am guessitg that's a class loader thing.
