### ISSUE TITLE
High memory usage and OutOfMemoryError

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#2238]
I have an application that I run with -Xmx300m -Xms150m -Xmn8m in both jvm and native mode and I monitor rss with the following command: mailing list

    ps ax -o pid,rss,command | numfmt --header --from-unit=1024 --to=iec --field 2

When running in JVM mode I see the RSS being almost stable around 120 MB but when running in native mode the RSS starts at 55 MB and grows of ~50 MB for each invocation of the service until it reached 450 MB at that point it seems stable.

If I lower the memory in native mode, I get:

    java.lang.OutOfMemoryError: Garbage-collected heap size exceeded

To reproduce the issue you need to build in order:
1. https://github.com/lburgazzoli/quarkus/tree/camel-k-fix
2. https://github.com/lburgazzoli/apache-camel-k-runtime/tree/quarkus-runtime

Then build the [example]( https://github.com/lburgazzoli/apache-camel-k-runtime/tree/quarkus-runtime/camel-k-runtime-quarkus/camel-k-runtime-quarkus-example
) with the `native` profile active. 

Note that before to run it you need to set the env var:   

    CAMEL_K_ROUTES=file:routes.xml

To test the native code and 

    CAMEL_K_ROUTES=file:routes-jvm.xml

To run test the JVM mode.

**Comment by lburgazzoli** [comment]
@johnaohara thi si the issues we have been talking about this morning on zulip.

**Comment by johnaohara** [comment]
I am seeing different behaviour from the netty NioEventLoop for jvm mode and native mode.
In both modes the first 9 invocations on the route endpoint result in allocations of ByteBuffers. There appears to be a buffer pool that is warmed up. 

However, in native mode, there is at least one additional DirectByteBuffer allocation of 16.8MB and a thread local array of the same size.  These allocations do not happen in JVM mode.

JVM
```
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:48,022 INFO  [route1] (Camel (camel-q) thread #3 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:48,861 INFO  [route1] (Camel (camel-q) thread #5 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:49,333 INFO  [route1] (Camel (camel-q) thread #7 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:49,706 INFO  [route1] (Camel (camel-q) thread #9 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:50,122 INFO  [route1] (Camel (camel-q) thread #11 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:50,489 INFO  [route1] (Camel (camel-q) thread #13 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:50,893 INFO  [route1] (Camel (camel-q) thread #15 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:52,317 INFO  [route1] (Camel (camel-q) thread #17 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:52,691 INFO  [route1] (Camel (camel-q) thread #18 - NettyEventExecutorGroup) 
2019-04-30 20:46:53,955 INFO  [route1] (Camel (camel-q) thread #19 - NettyEventExecutorGroup) 
2019-04-30 20:46:54,356 INFO  [route1] (Camel (camel-q) thread #20 - NettyEventExecutorGroup)
```

Native
```
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 2
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 5
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:01,385 INFO  [route1] (Camel (camel-1) thread #2 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 16777216
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:02,111 INFO  [route1] (Camel (camel-1) thread #4 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 16777216
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:03,708 INFO  [route1] (Camel (camel-1) thread #6 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 16777216
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:07,300 INFO  [route1] (Camel (camel-1) thread #8 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 16777216
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:08,235 INFO  [route1] (Camel (camel-1) thread #10 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:09,407 INFO  [route1] (Camel (camel-1) thread #12 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:10,498 INFO  [route1] (Camel (camel-1) thread #14 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>
**** java.nio.DirectByteBuffer.<init>(int): 1024
2019-04-30 20:46:11,406 INFO  [route1] (Camel (camel-1) thread #16 - NettyEventExecutorGroup) 
**** java.nio.DirectByteBuffer.<init>
2019-04-30 20:46:13,579 INFO  [route1] (Camel (camel-1) thread #17 - NettyEventExecutorGroup) 
2019-04-30 20:46:14,701 INFO  [route1] (Camel (camel-1) thread #18 - NettyEventExecutorGroup) 
2019-04-30 20:46:16,122 INFO  [route1] (Camel (camel-1) thread #19 - NettyEventExecutorGroup) 
```
I am working on identifying which tasks that are passed to the NioEventLoop are causing these extra allocations

**Comment by johnaohara** [comment]
A bit further along, the ByteBuf that is passed into this method:
https://github.com/netty/netty/blob/netty-4.1.34.Final/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L268
is a direct buffer for JVM mode, but is not a a direct buffer for Natice mode.  The extra allocation comes from;

https://github.com/netty/netty/blob/netty-4.1.34.Final/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L275

**Comment by johnaohara** [comment]
The buffer types passed to AbstractNioByteChannel.filterOutboundMessage() are;

JVM - io.netty.buffer.PooledUnsafeDirectByteBuf
Native - io.netty.buffer.PooledHeapByteBuf

**Comment by johnaohara** [comment]
In native mode this call is failing:

https://github.com/apache/camel/blob/camel-3.0.0-M2/components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/DefaultNettyHttpBinding.java#L370

and the extra allocation is coming from here:

https://github.com/apache/camel/blob/camel-3.0.0-M2/components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/DefaultNettyHttpBinding.java#L375

**Comment by johnaohara** [comment]
Having dug into this, it appears that we are missing some classes in the native image.  In JVM mode, we have  `org.apache.camel.component.netty4.NettyConverterLoader$BaseTypeConverter` and `org.apache.camel.component.netty4.NettyConverterLoader$3`.  They are missing from the native image, so camel falls back to allocating a new 16MB buffer because it can not find a converter to convert a string to a ByteBuf. These will need to be register for reflection.

We should register all the anonymous inner classes in NettyConverterLoader for reflection, otherwise we will have similar issues with other message payload types.

The strange thing is I can not find org.apache.camel.component.netty4.NettyConverterLoader in the camel repo, even though the class is in the source jar , and in javadoc (https://www.javadoc.io/doc/org.apache.camel/camel-netty4/3.0.0-M2)

**Comment by lburgazzoli** [comment]
@gnodet this may fall in the same problem we have with the XmlConverter

**Comment by johnaohara** [comment]
After chatting with @lburgazzoli, org.apache.camel.component.netty4.NettyConverterLoader is auto generated, and appears to be missing from native image, alone with the anonymous convert classes. 

A converter is not found, and netty defaults to allocating a new 16MB PooledHeapByteBuf and stores in a buffer pool.  Memory usage increases with every invocation until the pool is full. In jvm mode, the buffer is a PooledUnsafeDirectByteBuf, the same behaviour occurs, but the buffer sizes are not set, so will be default buffer size.

For reference, trace trace of differences between jvm mode and native mode are;

JVM - https://gist.github.com/johnaohara/840cff71011761dbf0ebe2086e3e2557
Native - https://gist.github.com/johnaohara/286caee2706f3ca92cd8ca00452adccc

**Comment by johnaohara** [comment]
@lburgazzoli has this issue been resolved now?

**Comment by ppalaga** [comment]
What is the status of this, @lburgazzoli ?

**Comment by johnaohara** [comment]
@lburgazzoli can we close this now? AFAIK, the camel extensions have been moved from quarkus repo. Should we close this and open an issue in the camel extensions repo if this is still an issue?
