### ISSUE TITLE
Pusher beams SDK extension (server side)

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkusio/quarkus#22391]
### Description

The purpose of this extension is to integrate Pusher beams server java library to the Quarkus ecosystem and provide native support for it.

Pusher beams is a notification solution (saas) to send notifications to Android, iOS, Web clients (single/grouped notification, topic based notification, authenticated clients notifications)

**What this extension will offer**

- CDI injection of Pusher beams component
- Pusher beams configuration
- Class registration & co
- Support classes to execute Pusher operations
- Support component to handle retry system (automatic handling of 429 HTTP error since Pusher API is rate limited)

**Who this extension is for**
People interested in this extension will be people using Pusher beams product and interested in sending notifications from their Java / Quarkus backend, managing Pusher beams authenticated users, etc.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion

```
# default true, to activate/deactivate the extension at build time
quarkus.pusher.beams.enabled=true/false
# minimum configuration required to connect to your pusher beams instance.
quarkus.pusher.beams.instance-id=xxxxxx
quarkus.pusher.beams.secret-key=xxxxxx
# any other optional configuration for this extension. Example: retry system
quarkus.pusher.beams.retry.max=3
quarkus.pusher.beams.retry.delay=1
```

### Additional context

The extension is not yet developed by i already have integrated it in one of my services written with Quarkus.

I just want to share it with the community as well as maintain it in a central place and as an extension so that i can re-use it across multiple services.

This extension should belongs to the Quarkiverse Hub if accepted - i guess.

I'm of course interested in leading the development of this extension as i'm using it inside a Quarkus application and i've already proposed and wrote another extension for Datadog open tracer for Quarkiverse a while ago ([here](https://github.com/quarkiverse/quarkus-datadog-opentracing))

**Comment by nicolas-vivot** [comment]
@gastaldi sorry to bother you, any chances for this to be accepted ?

**Comment by gastaldi** [comment]
@nicolas-vivot oh sorry, I wasn't notified for this one. Of course we can include it in Quarkiverse, let me set up the repository for you

**Comment by gastaldi** [comment]
Btw any suggestions on the repository name? `quarkus-pusher`,`quarkus-pusher-beams`?
Are you planning on integrating the client SDK too?

**Comment by nicolas-vivot** [comment]
`quarkus-pusher-beams` sound good for me.

Right now i'm not planning to integrate the client, only the server side.

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-pusher-beams

**Comment by nicolas-vivot** [comment]
thanks
