### ISSUE TITLE
Posting json format containing an array does not work

### ISSUE THREAD

**Issue by richard457** [quarkusio/quarkus#22393]
### Describe the bug

posting request body containing an array result into error
``{
    "businessName": "Test",
    "businessPhoneNUmber": "0054874",
    "subscriptionStartAt": "12/20/2021",
    "subscriptionEndsAt": "13/20/2021",
    "branches": [
        {
            "id": 13,
            "active": true,
            "channels": null
        }
    ],
    "business": {
        "id": 8,
        "name": "Test",
    }
}``

### Expected behavior

this should work
``` 
    @POST
    @Path("subscription")
    public Response subs(final Subscription subscription) {
        return Response.ok(subscription).build();
    }
```

### Actual behavior

Get this error
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type
`java.util.ArrayLis

### How to Reproduce?

Reproduce
1. create a quarkus with simple resteasy dependency
2. add a model call it whatever to match the modal I am posting above
3. post to endpoint as json body request
4. should get error

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7) OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.9.1 (AdoptOpenJDK 11.0.9.1+1) OS:           Windows 10 10.0 amd64

**Comment by richard457** [comment]
FYI I am using Java not kotlin.

**Comment by geoand** [comment]
Please attach a sample application that exhibits the problematic hehavior

**Comment by richard457** [comment]
@geoand I provided all details you need above, you can use any quarkus app.

**Comment by richard457** [comment]
```package core;

import core.model.box.Subscription;
import core.objectbox.BaseBox;
import io.objectbox.Box;
import io.quarkus.security.Authenticated;
import io.quarkus.vertx.http.runtime.CurrentVertxRequest;

import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/v2/api")
@Authenticated
public class SubscriptionController {

    @Inject
    BaseBox baseBox;

    @Inject
    CurrentVertxRequest request;

    @POST
    @Path("subscription")
    @Consumes({MediaType.APPLICATION_JSON})
    @Produces({MediaType.APPLICATION_JSON})
    public Response subs(final Subscription subscription) {
        return Response.ok(subscription).build();
    }
}
```

**Comment by geoand** [comment]
> @geoand I provided all details you need above, you can use any quarkus app.

Not really. We still don't know what `Subscription` looks like nor do we know what the exact HTTP request you are making is.

**Comment by gsmet** [comment]
Please provide a zip with an application showing the problem. We have a lot on our plate and we can't experiment trying to find how you did things. Thanks.
