### ISSUE TITLE
StreamingOutput 500: since update to 2.5.1.Final

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#22394]
### Describe the bug

Since version 2.4.1, I used a StreamingOutput to return a ByteOutputStream to the user

```java
/**
 * Returns a buffer as a streaming output
 */
public static StreamingOutput outputBufferJAXToStream(final ByteArrayOutputStream output) {
    return new StreamingOutput() {
        public void write(final OutputStream os) throws IOException {
            try {
              output.writeTo(os);
                } catch (Exception e) {
                  log.error(e.toString());
                  throw e;
                }
            }
        };
    }
```

Now I'm getting a 500 without any error in the console and an empty 500 response

### Expected behavior

Return Bytes to the user, without any error

### Actual behavior

500 empty reponse

### How to Reproduce?

1 - Classic HTTP controller
2 - Return a StreamingOutput coming from a the previously defined function and a ByteOutoutStream
3 - Get an error

### Output of `uname -a` or `ver`

Linux <redacted> 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 Maven home: /usr/share/maven Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-47-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Is this still a problem with `2.5.4.Final`?

**Comment by Plawn** [comment]
Hello, sorry for the delay. I'll try to make a reproducer, but I think it could also be linked to reactive-resteasy instead of using resteasy. I'll work on it

**Comment by grossws** [comment]
Sorry for necroposting, found #18444

**Comment by Plawn** [comment]
Linked to the use of ResteasyReactive, my bad
