### ISSUE TITLE
JWT and OIDC challenge conflict

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22404]
### Describe the bug

If I am using `quarkus-jwt` and `quarkus-oidc` together to support OIDC or custom login, I can get into conflicts where logging in to an `@Authenticated` endpoint that is supposed to be handled by OIDC explictly (by selecting its tenant) will return the `www-authenticate: bearer` challenge from JWT instead of entering the OIDC web flow.

This happens randomly, based on the order of the `HttpAuthenticator.mechanisms`, and if JWT is first I'm screwed because I can't use OIDC anymore.

In the case of a web application, I never ever want such a 401 challenge to be sent to the user: I'll always want a redirect to a login page.

**Comment by sberyozkin** [comment]
Hi @FroMage 

I think this is a duplicate of #22206, I believe the issue you are seeing may be related to the workaround you proposed at #22200. Do you agree ? It has to be resolved in a generic way. I think resolving #22206 will fix it

**Comment by FroMage** [comment]
No, this is a new issue, not fixed by #22200.

**Comment by sberyozkin** [comment]
@FroMage What I meant is that #22200 provides a workaround, but we need to have a generic solution in place which is why I opened #22206; I agree we have to ensure the correct challenge will have to be returned as well, I'll test it too

**Comment by FroMage** [comment]
> What I meant is that #22200 provides a workaround

No, it does not. I'll push a new commit for this as workaround.
