### ISSUE TITLE
Update documentation to include Mysql  flyway breaking change

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22400]
### Describe the bug

Flyway 8.x requires an extra dependency in order to work with Mysql. The required dependency is already in the [BOM](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L4917), but is not documented. 

Quarkus Version: Upstream (999-SNAPSHOT)

Brother issue: https://github.com/quarkusio/quarkus/pull/21939/files

**Comment by gastaldi** [comment]
Nice catch! I forgot we had updated the guides with this, I thought we had it only in the [Migration guide
](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7#flyway)

Want to provide a PR?
