### ISSUE TITLE
add protoc  ppc64le to grpc codegen

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#22418]
### Description

At the moment an attempt to build Quarkus on ppc64le fails with Failed to find com.google.protobuf:protoc:linux-ppc64le:exe among dependencies.
We should fix it by adding the aforementioned artifact to codegen dependencies

**Comment by michalszynkiewicz** [comment]
After more investigation:

* even though the protoc artifact is available for the given architecture, another artifact `io.grpc:protoc-gen-grpc-java` is not
* this, unfortunately means that we cannot make it work on ppc64le
* please note that this only **affects building** Quarkus apps on the given architecutre and **not running** them

**Comment by michalszynkiewicz** [comment]
@cescoffier I don't know how big powerpc is nowadays but the above is another argument for java-based solution for generating stubs :)

**Comment by jamesnetherton** [comment]
@cescoffier Do you think this could be implemented? Seems there is a `ppc64le` variant of `io.grpc:protoc-gen-grpc-java` available now:

https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.58.0/

**Comment by cescoffier** [comment]
I would need to be able to test it, and I do not have access to that kind of machine.

**Comment by shreyakajbaje** [comment]
Hi @cescoffier and @jamesnetherton , getting a ppc64le node/vm can be done via a opensource community based VM request form - https://osuosl.org/services/powerdev/request_hosting/ . Please put in `Gerrit Huizenga` as the IBM Advocate while filling up the form... Please let me know if this works to get access to a debugging instance.
> I would need to be able to test it, and I do not have access to that kind of machine. cc @gerrith3  @ghatwala

**Comment by gerrith3** [comment]
Hey @cescoffier @jamesnetherton access should be no issue at all.  The form that @shreyakajbaje included above will file a ticket and send emails to a few folks, but we've put this on what should be the fast-approval track.  Let us know if you need any help or have any questions.  This access is available to any open source developer needing to port or test on Power hardware.
