### ISSUE TITLE
Quarkus, Swagger Ignore method/Class

### ISSUE THREAD

**Issue by CormegaGit** [quarkusio/quarkus#22429]
### Describe the bug

Hello,

I have a Quarkus app and i am using Swagger interface for those REST API, and all my methods are visible, i want to ignore some of them to dot be visible when i am using quarkus and i have tried like below, and also added some other @ApiOperation and so one,

When i am using Swagger all my methods are visible on Swagger interface so i dont know how to ignore some of them.

@GET
@Produces(MediaType.TEXT_PLAIN)
@Operation(hidden = true)
@Schema(hidden=true)
public TemplateInstance getGetSMTest(@QueryParam("name") String name){
    LOG.info("called page /getSMTest");
    return getSMTest.data("name", name);
}

Best Regards,
Daniel Sanchi

**Comment by phillip-kruger** [comment]
Thanks @CormegaGit , can you share the output of the openapi document as well ?

**Comment by phillip-kruger** [comment]
Also please share your imports in the class in question

**Comment by phillip-kruger** [comment]
@CormegaGit - any feedback ? Are you maybe using swagger annotations rather than MicroProfile OpenAPI ?

**Comment by CormegaGit** [comment]
Hello, I am using the below dependency in POM.xml

./mvnw quarkus:add-extension -Dextensions="quarkus-smallrye-openapi"

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>

**Comment by phillip-kruger** [comment]
Can you share a reproducer ?

**Comment by phillip-kruger** [comment]
@CormegaGit Please reopen if you have a reproducer to share. Thanks :)

**Comment by christian-screen** [comment]
The following seems to work for us and seems to be the correct syntax (tested and working in version >= 2.8), on a method, notice the hidden attribute,
`@Operation(summary = "Description of Method...", hidden = true)`, where the use of annotation `@ApiOperation` does not appear to provide the desired result.

**Comment by phillip-kruger** [comment]
From what package is @ApiOperation ?

**Comment by christian-screen** [comment]
@phillip-kruger the one we thought was correct was from `io.swagger.annotations` where as @Operation(...) seems to come from `org.eclipse.microprofile.openapi.annotations`

**Comment by phillip-kruger** [comment]
Yes, we are based on microprofile open API and does not support swagger. You can remove the swagger dependency from your classpath

**Comment by oumaima-bouhmid** [comment]
hi, i have the same issue, i am working on a Quarkus project but i want t o generate the openApi doc only for one endpoint, in spring we use pathToMatch property to define which endpoint we want to generate, but i do not find something similar in Quarkus. anyone has an idea? i am stacking on this issue for a week now

**Comment by oumaima-bouhmid** [comment]
yes i have tried this solution but it's not practical cuz i have a lot of endpoints i we might forget to hide an endpoint in the future so this could lead to a security problem. i thought there would be an efficient solution like the one of spring when we do specify in application.proprieties the path of endpoint for whom we want to generate the doc

**Comment by phillip-kruger** [comment]
The other option is to write your own OASFilter

**Comment by oumaima-bouhmid** [comment]
OK i will try this solution. thank you

**Comment by MikeEdgar** [comment]
@oumaima-bouhmid you can limit the number of `@Operation(hidden = true)` to a single class if you name the class with config property `mp.openapi.scan.classes`. All other endpoint classes should be ignored by the scanner.

**Comment by oumaima-bouhmid** [comment]
@MikeEdgar i am using smallrye-openapi to generate my doc

**Comment by oumaima-bouhmid** [comment]
i tried using this solution @MikeEdgar but the problem is my endpoint uses other classes so i end up exporting the doc without the necessary schemas

**Comment by oumaima-bouhmid** [comment]
well, that sound good, but stills with this solution i will generate the doc for a class that contains a lot of endpoints so i will end up using the annotation @Operation(hidden=true) for the other endpoint( i wanted to avoid this)
