### ISSUE TITLE
Arc - allow to modify injection points

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#2243]
Currently, Arc doesn't allow to modify injection points, e.i. doesn't have an equivalent of what CDI's `ProcessInjectionPoint`. It would be handy to have something like this in place.

The idea is to introduce a separate `BuildExtension` which will allow inspection of all injection points. Some helper methods with filtering wouldn't hurt either (as you are usually interested in IPs of given type only).

This is also blocking for integrating SmallRye CP injection feature (aka rewriting [this](https://github.com/smallrye/smallrye-context-propagation/blob/master/cdi/src/main/java/io/smallrye/context/inject/SmallryeContextCdiExtension.java) extension) into Quarkus. This isn't spec mandated though, just an extra feature.

**Comment by LightGuard** [comment]
I would find this interesting. With what we currently have in Quarkus and the ability to process injection points, we'd have the majority of useful CDI bootstrapping in place.

**Comment by mkouba** [comment]
Yes, we could introduce a new extension point, probably something like `InjectionPointConfigurator`. Nevertheless, I think that the only reasonable thing you can do is to change the set of qualifiers.
