### ISSUE TITLE
Improve OIDC client pluggability

### ISSUE THREAD

**Issue by rkraneis** [quarkusio/quarkus#22432]
### Description

It would be great to add some extension points to OIDC client to modify the requests it sends besides adding static headers.

Problem at hand:
We want to interface with an Oauth2 secured API that is using [HTTP Message Signatures](https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/) as an additional means of protection. This requires the addition of several headers, which contents are based on the actual message body. Our current workaround (result of the discussion in https://github.com/quarkusio/quarkus/discussions/22256):

In every request:
- create the body OidcClient will create manually using `OidcCommonUtils.encodeForm`
- calculate the header values
- manually create OidcClientConfig and OidcClient; tokens will still be managed nicely when using TokensHelper
The workaround could be a bit smarter by chedking if tokens are actually about to run out and not bothering with most of the above if they would not.

With that in mind, an extension mechanism to support HTTP Message Signatures would have access to body and headers of the request to be sent by OIDC client and would be able to modify (or at least add to) the List of headers.

**Comment by sberyozkin** [comment]
CC @calvernaz FYI
