### ISSUE TITLE
Find a solution for Panache active record to be competitive in these situations

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2244]
```
    @POST
    @Transactional
    @Produces("application/json")
    @Consumes("application/json")
    public Order addOrder(Order order) {
        order = entityManager.merge(order);
        orderStream.send(KafkaMessage.of(order.getId(), order.toJson().toString()));
        return order;
    }
```

I understand the argument that one should validate the JSON entry anways and straight entity reattachment would be banned, we could achieve such validation via Bean Validation annotations and thus be safe when using such model.

Today Panache has no update nor merge option making it less competitive to this kind of example

```
    @POST
    @Transactional
    @Produces("application/json")
    @Consumes("application/json")
    public Order addOrder(Order order) {
        otherOrder = Order.findById(order.id);
        otherOrder.version = order.version;
        otherOrder.number = order.number;
        otherOrder.items = someMagicToCopyItems(order.items);
        return order;
    }
```

**Comment by emmanuelbernard** [comment]
@FroMage

**Comment by FroMage** [comment]
We can totally expose `merge()`, but that's promoting a bad style that has security implications. So if we do expose it, that's only on the grounds that we can't prevent people from shooting themselves in the foot, but we can't possibly be advertising that strategy IMO. That's good for a demo, not for a real app.

**Comment by emmanuelbernard** [comment]
@FroMage I think that for the active record pattern, update is better that merge which has a "possibly copy on write" semantic. so the returned entity (the managed one) might not be the instance you passed in.
For the repository, merge is nicer as it's closer to JPA semantics.

So you don't buy my idea of Bean Validation validating the input?

**Comment by loicmathieu** [comment]
This is related to #3969 also
