### ISSUE TITLE
Unable to override (mock) system time

### ISSUE THREAD

**Issue by davidmoshal** [quarkusio/quarkus#22458]
### Describe the bug

Mocking time does not seem to work.
I've tried: Mock, JMockit, and implementation with the java api.
ie: most of the methods described   
here: https://www.baeldung.com/java-override-system-time
and here https://nieldw.medium.com/unit-testing-fixing-the-system-clock-with-mockk-fc6991afb766

### Expected behavior

should be able to mock system time.

### Actual behavior

Either has no effect, or freezes IntelliJ

### How to Reproduce?

```java
@Test
public void givenFixedClock_whenNow_thenGetFixedLocalDateTime() {
    Clock clock = Clock.fixed(Instant.parse("2014-12-22T10:15:30.00Z"), ZoneId.of("UTC"));
    String dateTimeExpected = "2014-12-22T10:15:30";

    LocalDateTime dateTime = LocalDateTime.now(clock);

    assertThat(dateTime).isEqualTo(dateTimeExpected);
}
```

```kotlin

internal class ClockFixingTest {

    private val now = 1550160535168L
    private val fixedClock = Clock.fixed(Instant.ofEpochMilli(now), ZoneId.systemDefault())

    @BeforeEach
    fun `fix the clock =)`() {
        mockkStatic(Clock::class)
        // Default system clock
        every { Clock.systemUTC() } returns fixedClock
    }

    @Test
    fun `can fix clock`() {
        assertEquals(now, Instant.now().toEpochMilli())
    }
}
```
Joda doesn't work either:
```kotlin
 DateTimeUtils.setCurrentMillisProvider {
        givenMillis
    }
```

Is this a class loader issue??

**Comment by geoand** [comment]
Indeed this is a classloading issue.

I am going to close this since it's a minor issue that would likely be pretty hard to fix

**Comment by davidmoshal** [comment]
Hang on, before you close it, I've seen numerous classloader-related issues, 
eg inability to use testing frameworks like Kotest, 
and pretty much anything to do with classloaders.

So, rather than close it, perhaps better documentation about how exactly Quarkus uses classloaders would be helpful?

Regarding this specific issue, this actually works:

```kotlin
DateTimeUtils.setCurrentMillisFixed(
    DateTime("2021-12-13T08:00:00.00-08:00").millis
)
```

Note:

a) it must be called early, before the tests are run, and

b) all the dates you want to fix MUST be created with Joda's DateTime() and not Date()
  (you can always get the Date from DateTime().toDate()

**Comment by geoand** [comment]
You can read up on how Quarkus used ClassLoaders [here](https://quarkus.io/guides/class-loading-reference).
