### ISSUE TITLE
gradle listExtensions / addExtension fails

### ISSUE THREAD

**Issue by JWood48** [quarkusio/quarkus#22450]
### Describe the bug

Trying to list or add an extension with gradle fails with

`> Task :listExtensions FAILED
Failed to resolve platform io.quarkus.platform:quarkus-bom-quarkus-platform-descriptor:2.5.4.Final:json:2.5.4.Final using the following registries: registry.quarkus.io`

### Expected behavior

list extensions or add extensions

### Actual behavior

fails with error

`
> Task :listExtensions FAILEDG [815ms]
Failed to resolve platform io.quarkus.platform:quarkus-bom-quarkus-platform-descriptor:2.5.4.Final:json:2.5.4.Final using the following registries: registry.quarkus.io

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':listExtensions'.
> Unable to list extensions
`

### How to Reproduce?

- create a random project at https://code.quarkus.io/ with gradle as build tool
- download and unzip
- run gradlew listExtensions

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

11.0.13 (Oracle Corporation 11.0.13+8)

### Quarkus version or git rev

2.5.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by glefloch** [comment]
It looks like it works for me, could you retry?

**Comment by glefloch** [comment]
@JWood48 could you confirm that you are still seeing the issue ?

**Comment by JWood48** [comment]
Hi

I just reran the test - now everything seems to work... also for the original project... migth have been the extensions service endpoint that was down or something on my part :-)

/Jakob

**Comment by glefloch** [comment]
Yes, or it could come from maven central as the artifact were published the same day you tried to get them. 
I will the close. Feel free to reopen it if you encounter a similar issue.
