### ISSUE TITLE
REST Client Reactive proxy enhancements

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#22466]
### Description

We should make sure if the following work or implement them
- [x] basic auth with proxy
- [x] app-wide client proxy configuration (configure it with one set of props and use it for all the clients in the app)
- [x] java system settings for setting proxy

**Comment by michalszynkiewicz** [comment]
@maxandersen fyi
Please add more if I missed something

**Comment by maxandersen** [comment]
where sensible align with existing properties like done in https://github.com/quarkusio/quarkus/pull/19261
and add docs for it in fairly central place as its basically impossible to find atm.

**Comment by geoand** [comment]
FWIW, the Reactive REST Client will soon work with HTTP Toolkit via https://github.com/httptoolkit/jvm-http-proxy-agent/pull/9

**Comment by onepremise** [comment]
I'm trying to use these updates to make a rest API call with user/password protected proxy.  I've gone through the examples provided in the commit. However, I'm still unable to make this work. When I go to build my client:

`
RestClientBuilderImpl restClientBuilder = (RestClientBuilderImpl) RestClientBuilder.newBuilder().register(BasicRequestFilter.class);
        emailClient = restClientBuilder.baseUri(URI.create(this.uri)).proxyAddress(proxyHost, Integer.parseInt(proxyPort))
                .proxyUser(proxyUser).proxyPassword(proxyPassword)
                .build(EmailClient.class);
`

I encounter the following error:

`
java.lang.NoClassDefFoundError: org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl
	at org.jboss.resteasy.microprofile.client.BuilderResolver.newBuilder(BuilderResolver.java:9)
	at org.eclipse.microprofile.rest.client.RestClientBuilder.newBuilder(RestClientBuilder.java:55)
	at com.relay.keycloak.rest.RelayEmailService.<init>(RelayEmailService.java:44)
	at EmailTest.testMFADisabledEmail(EmailTest.java:72)
`

Has anybody else encountered this error while trying to use a proxy with the RestClientBuilderImpl?

**Comment by geoand** [comment]
Are you including the `quarkus-rest-client-reactive` extension?

**Comment by onepremise** [comment]
I'm including the dependency:

**Comment by geoand** [comment]
Do you have a sample project that reproduces this issue?

**Comment by onepremise** [comment]
I'm sorry, but I could no longer invest time trying to get the quarkus/reactive rest call working through this library.  I ran into too many issues with the dependencies and lack of documented examples. FWIW, I ended up getting authenticated proxy to work through Apache's httpclient:4.5.13.

>         Credentials credentials = new UsernamePasswordCredentials(proxyUser, proxyPassword);
>         CredentialsProvider credProvider = new BasicCredentialsProvider();
>         credProvider.setCredentials(new AuthScope(proxyHost, Integer.parseInt(proxyPort)), credentials);

>         //
>         // Important notes to be aware of when using RestEasy api in keycloak/quarkus
>         // https://stackoverflow.com/questions/30776211/jax-rs-unable-to-authenticate-to-proxy
>         // https://github.com/quarkusio/quarkus/issues/22466
> 
>         HttpClientBuilder clientbuilder = HttpClients.custom();
> 
>         clientbuilder = clientbuilder.setDefaultCredentialsProvider(credProvider);
>         this.httpclient = clientbuilder.build();
> 
>         HttpHost proxy = new HttpHost(proxyHost, Integer.parseInt(proxyPort));
> 
>         RequestConfig.Builder reqconfigconbuilder= RequestConfig.custom();
>         reqconfigconbuilder = reqconfigconbuilder.setProxy(proxy);
>         RequestConfig config = reqconfigconbuilder.build();
> 
>         String encoding = Base64.getEncoder().encodeToString((emailUser + ":" + emailPassword).getBytes());
> 
>         this.target = new HttpHost(emailServer, Integer.parseInt(emailPort), "https");
>         this.postRequest = new HttpPost("/resource/example");
>         this.postRequest.setConfig(config);
>         this.postRequest.addHeader(HttpHeaders.AUTHORIZATION, "Basic " + encoding);
>         this.postRequest.addHeader("content-type", "application/json");
