### ISSUE TITLE
Where can I learn the principle of Quarkus

### ISSUE THREAD

**Issue by sunym1993** [quarkusio/quarkus#22463]

**Comment by sunym1993** [comment]
I see a lot of practice of Quarkus, but I want to know the principle, because the generation of class is too difficult to understand.

**Comment by geoand** [comment]
We have plenty of [guides](https://quarkus.io/guides/) for the various concepts.
There are also lots of [books](https://quarkus.io/books/) that provide a more structured learning experience.
