### ISSUE TITLE
Set correct supported maven version

### ISSUE THREAD

**Issue by llowinge** [quarkusio/quarkus#22472]
### Describe the bug

Supported maven version should start with `3.8.1`. But in https://github.com/quarkusio/quarkus/blob/2.2/build-parent/pom.xml#L57 is `3.6.2`.

**Comment by gsmet** [comment]
In 2.2, we still accepted 3.6.2 so I don't think we should change it in this branch.

**Comment by aloubyansky** [comment]
Actually, it appears we don't. The bootstrap in 2.2 depends on 3.8.1 and there is an API incompatibility.

**Comment by gsmet** [comment]
OK, I'll update it tomorrow in case we build another 2.2.
