### ISSUE TITLE
Oracle native scenario fails in combination with other datasources

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22476]
### Describe the bug

Quarkus Version: `999-SNAPSHOT`

Reproducer:
- Repository: https://github.com/quarkus-qe/quarkus-test-suite
- cmd: `mvn clean verify -Dnative -Dall-modules -Dit.test=OracleDatabaseIT -pl sql-db/sql-app`
- Error: 
```
[ERROR] Failures: 
[ERROR]   OracleDatabaseIT Failed to build Quarkus artifacts. Caused by java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'oracle' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
```
Works as expected in JVM mode. Also, a scenario with just Oracle works as expected in native mode. 
Success scenario (just Oracle)
- Repository: https://github.com/quarkus-qe/quarkus-test-suite
- cmd: `mvn clean verify -Dnative -Dall-modules -Dit.test=OracleDatabaseIT -pl sql-db/sql-app-oracle`

**Comment by rsvoboda** [comment]
CC @Sanne

**Comment by Sanne** [comment]
am I testing the right branch? It didn't fail locally

**Comment by rsvoboda** [comment]
I got confused too, but the OracleDatabaseIT gets skipped - Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s - in io.quarkus.ts.sqldb.sqlapp.OracleDatabaseIT

One needs to comment out `@DisabledOnNative` in sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java

Then I got the failure that Pablo reports. But it's false positive.
The reasoning is that `quarkus-jdbc-oracle` gets included only no other profile is activated. This is workaround to have the artifact present for JVM mode tests, but not for Native mode tests when "native" profile is activated.

So when explicitelly using the "default" profile by running `mvn clean verify -Dnative -Dall-modules -Dit.test=OracleDatabaseIT -pl sql-db/sql-app -Pdefault -Dquarkus.native.container-build=false` I have successful run - "[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0"
@Pablo you need to move `quarkus-jdbc-oracle` dependency just below `quarkus-jdbc-postgresql` and drop the "default" profile ++ drop  `sql-db/sql-app-oracle` module which was introduced to ensure native mode when just oracle jdbc driver is present.
