### ISSUE TITLE
Config generated classes are not registered for reflection

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#22474]
### Description

In `ConfigMapping` we define interfaces such as `com.acme.config.MyConfig`. At build time this generates implementation classes such as `com.acme.config.MyConfig-<hash>Impl`

If you intend to use those classes through reflection, you end up having to figure out the hash that has been generated, and add `@RegisterForReflection(classNames= {`com.acme.config.MyConfig-1234Impl`})` into your application.

In our project, we are adding the config objects into freemarker template models, and access some of the config properties from within the templates, hence the need for reflection.

Ideally those config implementation classes should be enabled for reflection, or at least (if we believe the need is rare, and/or if we fear the impact on the native exec) the application should be offered an easy way to enable those classes for reflection.

see [zulip conversation](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/RegisterForReflection.20on.20ConfigMapping.20classes)

/cc @radcortez 

### Implementation ideas

One option would be to allow adding `@RegisterForReflection` on the config interfaces, which would be interpreted as: a registration on the config impl classes need to be done.

Another option would be to add a build time parameter `register-config-classes-for-reflection/serialization`.

**Comment by vsevel** [comment]
to reproduce:

```
package org.acme.getting.started;

import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "job")
public interface JobConfig {

    String hello();
}
```
```
@Path("/hello")
public class GreetingResource {

    private static final Logger log = LoggerFactory.getLogger(GreetingResource.class);

    @Inject
    JobConfig job;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        try {
            Method helloMethod = job.getClass().getDeclaredMethod("hello");
            return (String) helloMethod.invoke(job);
        } catch (Exception e) {
            return e.toString();
        }
    }
}
```

application.properties:
```
server.host=localhost
server.port=8080

job.hello=world
```

```
@QuarkusTest
public class GreetingResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("world"));
    }
}
```

Build and start in native mode, and invoke the hello endpoint (works in jvm mode):

```
curl http://localhost:8090/hello
java.lang.NoSuchMethodException: org.acme.getting.started.JobConfig-1625885570Impl.hello()
```

**Comment by radcortez** [comment]
Sounds reasonable. I'll add a better way to do this.

**Comment by vsevel** [comment]
let me know if I can help.

**Comment by radcortez** [comment]
Thanks, no worries. It is a fairly easy change.
