### ISSUE TITLE
quarkus platform 2.6.0.Final incompatible with kogito

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#22490]
### Describe the bug

build error with kogito and quarkus new version 2.6.0.Final recently launched.
error:
Unsupported method parameter java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> arg4 of public void org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor.startDataIndexDevService(io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.builditem.LaunchModeBuildItem,org.kie.kogito.quarkus.processes.deployment.KogitoBuildTimeConfig,java.util.Optional,java.util.Optional,io.quarkus.deployment.builditem.CuratedApplicationShutdownBuildItem,io.quarkus.deployment.logging.LoggingSetupBuildItem) of class org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor

### Expected behavior

should build without any error. build works fine with 2.5.4.Final

### Actual behavior

Build throws error
Unsupported method parameter java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> arg4 of public void org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor.startDataIndexDevService(io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.builditem.LaunchModeBuildItem,org.kie.kogito.quarkus.processes.deployment.KogitoBuildTimeConfig,java.util.Optional,java.util.Optional,io.quarkus.deployment.builditem.CuratedApplicationShutdownBuildItem,io.quarkus.deployment.logging.LoggingSetupBuildItem) of class org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor

### How to Reproduce?

Reproducer:
download a sample code gen via intellij/vscode/code.quarkus.io and select kogito and persistence 
create a simple workflow or dmn and build with mvn clean compile quarkus:dev.
It will result in error
Unsupported method parameter java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> at java.util.Optional<io.quarkus.deployment.builditem.DevServicesSharedNetworkBuildItem> arg4 of public void org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor.startDataIndexDevService(io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.annotations.BuildProducer,io.quarkus.deployment.builditem.LaunchModeBuildItem,org.kie.kogito.quarkus.processes.deployment.KogitoBuildTimeConfig,java.util.Optional,java.util.Optional,io.quarkus.deployment.builditem.CuratedApplicationShutdownBuildItem,io.quarkus.deployment.logging.LoggingSetupBuildItem) of class org.kie.kogito.quarkus.processes.deployment.KogitoDevServicesProcessor

### Output of `uname -a` or `ver`

Darwin DEBABRATAs-Mini.bbrouter 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.6.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/debabratapatnaik/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 17.0.1, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.0/Contents/Home Default locale: en_IN, platform encoding: US-ASCII OS name: "mac os x", version: "11.5.2", arch: "x86_64", family: "mac"

### Additional information

need to know why the build fails with newly released platform.

**Comment by evacchi** [comment]
this is a known issue that has been fixed on `main` and `1.15` branch. We are currently working on releasing 1.15 ASAP, but we are facing issues with infrastructure /cc @radtriste @cristianonicolai

**Comment by radtriste** [comment]
Note that due to Xmas and limited people available, the release will happen beginning of next year.

**Comment by debu999** [comment]
We are new and trying to make a move to Quarkus and kogito from jbpm and spring boot. Thanks for the cool product. Happy to be part of the new era of smart coding with java

**Comment by evacchi** [comment]
well thanks for the kind words 🙏  🚀

**Comment by gsmet** [comment]
@debu999 for now, just use 2.5.4.Final. I'll make it prominent in the release notes when 2.6 supports Kogito. I should probably add a note in the 2.6 release notes.

**Comment by debu999** [comment]
Sure. Looking forward to it. Our next release is Jan end so anytime upgrade is fine .

**Comment by Sanne** [comment]
@gsmet this one is out of date, correct?

**Comment by evacchi** [comment]
1.15 has been released, we are currently releasing 1.16. I think this issue can be closed /cc @radtriste

**Comment by radtriste** [comment]
Kogito 1.15.0.Final has been integrated in Quarkus Platform 2.6.2.Final
so I guess this issue can be closed yes
