### ISSUE TITLE
Wrong level of log message in HystrixInitializer

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#2249]
I'm seeing the HystrixInitializer print out INFO level messages during shutdown of an app that includes the quarkus-smallrye-fault-tolerance extension:

```bash
Scotts-iMacPro:Qproj4MP starksm$ ./target/demo-runner 
onStart, event=io.quarkus.runtime.StartupEvent@109290660
11:09:43 INFO  [io.quarkus]] (main) Quarkus 0.14.0 started in 0.007s. Listening on: http://[::]:8080
11:09:43 INFO  [io.quarkus]] (main) Installed features: [cdi, resteasy, resteasy-jsonb, security, smallrye-fault-tolerance, smallrye-health, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-rest-client]
^ConStop, event=io.quarkus.runtime.ShutdownEvent@10929d768
11:11:08 INFO  [io.sm.fa.HystrixInitializer]] (main) ### Reset Hystrix ###
11:11:08 INFO  [io.quarkus]] (main) Quarkus stopped in 0.003s
```

That seems like unnecessary noise to be printing out.

**Comment by gsmet** [comment]
We have a couple of filters here: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L141 .

But for the ones in SmallRye Fault Tolerance itself, we should probably fix it in SmallRye and get rid of them if they are deemed too verbose for the default SmallRye FT experience.

**Comment by mkouba** [comment]
+1 for debug level. I've created https://github.com/smallrye/smallrye-fault-tolerance/issues/76.
