### ISSUE TITLE
commons-jexl3  nativeImage Out of order

### ISSUE THREAD

**Issue by Tklfree** [quarkusio/quarkus#22519]
### Describe the bug

String el = "100*Math:pow(2,n)*(1+R2*0.01)";
        long c;
        Map<String, Object> map1 = new HashMap<>();
        map1.put("n", 0);
        map1.put("R2", 2);
        long a = (long) Math.floor(Utils.evalDouble(el, map1));
        Map<String, Object> map2 = new HashMap<>();
        map2.put("n", 0);
        map2.put("R2", 2);
        long b = (long) Math.floor(Utils.evalDouble(el, map2));
        c = a + b;
        System.out.println(c);

c is 204,

but when I compile to native value is null

**Comment by gsmet** [comment]
It's probably an issue with JEXL and native image.

That's not something we are willing to fix in Quarkus given we are using Glassfish EL implementation for Hibernate Validator and we won't invest in another EL implementation.

If you're interesting in pursuing this, you will probably need to register a few things for reflection and maybe some other tweaks.
