### ISSUE TITLE
Maybe split quarkus-bootstrap-core?

### ISSUE THREAD

**Issue by jskov** [quarkusio/quarkus#2251]
I am able to run quarkus integration tests from Gradle now.

But I cannot run them from Eclipse, because BootstrapAppModelResolver and BootstrapClassLoaderFactory only have a Maven backend to rely on.

What is the best way to add Gradle support?

Maybe split Maven code in quarkus-bootstrap-core into a new quarkus-bootstrap-core-maven project, to be looked up, maybe via java.util.ServiceLoader? This service to return results entirely by types defined by (a now common) quarkus-bootstrap-core.

Then a new quarkus-bootstrap-core-gradle project could be added, to provide same service.

FWIW, in Gradle, it would be natural to do the building of "deployment.cp" entirely as a side effect of changes to the build file (so tasks "test", "eclipse", "idea" would cause this file to be rebuilt).
As such, the quarkus-bootstrap-core-gradle service would just load the cached data.

**Comment by aloubyansky** [comment]
> I am able to run quarkus integration tests from Gradle now.

I guess that's because there is still pom.xml in place and/or deployment.cp.

> Maybe split Maven code in quarkus-bootstrap-core into a new quarkus-bootstrap-core-maven project, to be looked up, maybe via java.util.ServiceLoader? This service to return results entirely by types defined by (a now common) quarkus-bootstrap-core.
> 
> Then a new quarkus-bootstrap-core-gradle project could be added, to provide same service.

That was the idea initially.

> FWIW, in Gradle, it would be natural to do the building of "deployment.cp" entirely as a side effect of changes to the build file (so tasks "test", "eclipse", "idea" would cause this file to be rebuilt).
> As such, the quarkus-bootstrap-core-gradle service would just load the cached data.

deployment.cp is supposed to be an optional file, an optimization. Perhaps we'll have to consider that or something like that as an option.

**Comment by jskov** [comment]
Ah, yes. I did not express that properly. My bad.

I made a hack to generate the deployment.cp file from Gradle.
And then changed the code in quarkus-bootstrap-core to just load this without consulting Maven.

My questions are:
 - would the use of the cache file deployment.cp be OK as a primary mechanism
 - would a split of the project into common+maven+gradle project reluy on ServiceLoader, or do you use something else in other places of the quarkus project that should be used instead.

I might be interested in giving it a shot, if I was certain I didn't start off in a wrong direction :)

**Comment by aloubyansky** [comment]
> * would the use of the cache file deployment.cp be OK as a primary mechanism

No. At least in general. IMO, that could be considered for Gradle only, atm. Until we have something better.

> * would a split of the project into common+maven+gradle project reluy on ServiceLoader, or do you use something else in other places of the quarkus project that should be used instead.

In principle that could be good. I'd like to clarify the common part first though.

> I might be interested in giving it a shot, if I was certain I didn't start off in a wrong direction :)

Great! Perhaps you can help me figure something out. Have you seen LocalWorkspace/LocalProject API? The local workspace discovery is based on POMs. Do you think an equivalent model can reliably and relatively easy be built for a Gradle project? I think the way we will split the bootstrap into common, maven and gradle subprojects depends on the answer to that.

**Comment by jskov** [comment]
Yes, I think it can be done with the Gradle Tooling API (https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html)
I can try and give it a shot.

**Comment by aloubyansky** [comment]
Looks Interesting, thanks for the link! If you feel like researching it further, go for it! Feel free to ping me on zulip about it as well.

**Comment by jskov** [comment]
I worked on it yesterday, and have something working.
I will spend some time on cleaning it up before I will ask you take a look at it.

**Comment by aloubyansky** [comment]
Excellent, looking forward to that!

**Comment by jskov** [comment]
You can have a look at https://github.com/jskov/quarkus/tree/gradleBootstrap - not sure how to make a diff without a Pull Request, which I am not ready for.

But I think the code is mostly there - if a project has a pom.xml file, it will use the Maven implementation. If only a build.gradle file is found, it will use the Gradle implementation.
I have not done a lot to change the existing Maven code, but added some interfaces to decouple the two implementations from the client code.


I have two remaining problems, I am not sure how to handle properly. Maybe you can provide some hints.

* Missing dependencies
Out of the box, a test cannot run on Gradle, because it is missing some dependencies:
    testImplementation "io.quarkus:quarkus-core-deployment:${quarkusVersion}"
    testImplementation "io.quarkus:quarkus-jaxb-deployment:${quarkusVersion}"
    testImplementation "io.quarkus:quarkus-arc-deployment:${quarkusVersion}"
    testImplementation "io.quarkus:quarkus-resteasy-common-deployment:${quarkusVersion}"
    testImplementation "io.quarkus:quarkus-resteasy-deployment:${quarkusVersion}"
    testImplementation "io.quarkus:quarkus-undertow-deployment:${quarkusVersion}"

Are these perhaps some that are added by the Maven plugin?

* Dependency filtering
With the above dependencies added, a test example gets a classpath.cp with 145(!) dependencies from Gradle, but only 19 from Maven.
The list of dependencies provided by Maven (dependency:list target) includes 55 jars.

I cannot see (but may have missed) any culling in quarkus-bootstrap-core project. Is it done by something else, or do I just not understand how Maven works, maybe?!

Cheers

**Comment by aloubyansky** [comment]
The deployments are injected by the bootstrap model resolver. the deployment.cp contains only the deployment-specific deps excluding those that are already included into the runtime (original) app deps.

I glanced through your changes. I think I am going to actually check out your branch and try a few things to see how it works.

Thanks!

**Comment by jskov** [comment]
Almost gave up figuring that out - but found the clue in DeploymentInjectingDependencyVisitor.
So the artifacts contain a link to the deployment artifact that should replace them.

This can be done in Gradle, no problem. But it cannot be done via the API I have been using.

I need to make a Gradle task that extracts the necessary information. Which becomes part of the build lifecycle - and basically generates deployment.cp directly.

I will let you know when I have something worth looking at. Not for another week, at least, I am afraid.

**Comment by aloubyansky** [comment]
AppModelGradleResolver does that for the build. Although not exactly.

**Comment by jskov** [comment]
Hi @aloubyansky 
I have created a pull-request with the parts decoupling the common code from the maven implementation.
It should be easier to review.
When it is merged, I will make another pull-request with the actual Gradle support (which also affects the Gradle plugin).
