### ISSUE TITLE
Websocket: Configurator in CDI context

### ISSUE THREAD

**Issue by speedfl** [quarkusio/quarkus#22526]
### Description

Hello Quarkus team

It could be nice to add javax.websocket.server.ServerEndpointConfig.Configurator in CDI context so we can apply custom logic inside for authentication for example.

```java
@ServerEndpoint(value = "/controller/{application}", configurator = AuthConfigurator.class)
@ApplicationScoped
@Slf4j
public class ControllerWebsocketServer {
```

```
@ApplicationScoped
public class AuthConfigurator extends Configurator {
  
  private static final String AUTHORIZATION_HEADER = "Authorization";

  @Inject
  SomeBean someBean;

  public void modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response) {
  
  }
```

**Comment by omarkad2** [comment]
Is there a workaround for this ?

**Comment by lumuniz** [comment]
how to use @Inject in javax.websocket.server.ServerEndpointConfig.Configurator class? someone?

**Comment by lumuniz** [comment]
did anyone get it?

**Comment by lumuniz** [comment]
did anyone get it? @speedfl @mkouba

**Comment by mkouba** [comment]
Hm, the [specification](https://jakarta.ee/specifications/websocket/2.0/websocket-spec-2.0.html#configurator) does not seem to define the lifecycle of the `ServerEndpointConfig.Configurator` provided by the user so :shrug:. I mean Quarkus can try to lookup the bean first but we should be careful here...

> Is there a workaround for this ?

You can lookup the beans using the `CDI.current().select(SomeBean.class).get()` or `Arc.container().instance(SomeBean.class).get()` directly in the `AuthConfigurator`. However, keep in mind that the `SomeBean` could be identified as an [unused bean and removed](https://quarkus.io/guides/cdi-reference#remove_unused_beans). You might need to [mark the bean as unremovable](https://quarkus.io/guides/cdi-reference#eliminate_false_positives).

**Comment by mkouba** [comment]
I'm going to close this issue because the original `quarkus-websockets` extension (based on the Jakarta WebSocket specification) is not developed anymore; the [`quarkus-websockets-next` extension](https://quarkus.io/guides/websockets-next-reference#quarkus-websockets-vs-quarkus-websockets-next) is the recommended approach.
