### ISSUE TITLE
Documentation idea: Show Environment Variables on properties

### ISSUE THREAD

**Issue by jorsol** [quarkusio/quarkus#22546]
### Description

Quarkus can read from different Config Sources, yet the format is generally of two forms: properties and environment variables.

The conversion of properties to environment variables is mostly straightforward, but anyway it would be nice to have in the documentation the environment variable alternative form to have easy access to the correct name.

Also when searching, allow searching from the env var name too.

### Implementation ideas

Option 1: show in the description as a piece of extra information.
```
quarkus.datasource.jdbc.initial-size

The initial size of the pool. Usually you will want to set the initial size...

Environment variable: QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE
```

Option 2: show on the side of the property
```
quarkus.datasource.jdbc.min-size / QUARKUS_DATASOURCE_JDBC_MIN_SIZE

The datasource pool minimum size
```

I honestly prefer option 1 with the same style as the title `<code>QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE</code>` but whatever is chosen would be fine.

**Comment by machi1990** [comment]
This also seems like a nice addition to the config doc generator
