### ISSUE TITLE
Panache Rest doesn't use Reactive Hibernate

### ISSUE THREAD

**Issue by indiealexh** [quarkusio/quarkus#22554]
### Description

In short the hibernate-orm-rest-data-panache module requires you to use the non reactive hibernate orm with panache:

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>

I would like to use this module with the reactive panache library:

<dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-hibernate-reactive-panache</artifactId>
</dependency>

**Comment by loicmathieu** [comment]
This would need a totaly new extension, I change the issue type to extension proposal.

/cc @gytis

**Comment by FroMage** [comment]
@loicmathieu: @gytis left Red Hat IIRC.

@indiealexh would you be willing to contribute such a new extension?

**Comment by geoand** [comment]
> @gytis left Red Hat IIRC.

That is correct

**Comment by geoand** [comment]
@Sgitario might be interested in this. This should not be terribly difficult to implement (since we can build on what is already there for the Hibernate ORM version and the fact this new extensions only needs to support RESTEasy Reactive), but it will require some changes to introduce reactive flavors.
Furthermore, once the reactive flavor is available, it could also be used by the Mongo the extension

**Comment by indiealexh** [comment]
> @loicmathieu: @gytis left Red Hat IIRC.
> 
> @indiealexh would you be willing to contribute such a new extension?

I might be able to, but it would take me a while due to time limitiations.

**Comment by Sgitario** [comment]
@indiealexh so, are you working in this issue?

**Comment by Sgitario** [comment]
FYI: I'm working on this feature.

**Comment by Sanne** [comment]
@Sgitario that's awesome :)

May I suggest though, please consider making it optional? Hibernate Reactive is extremely promising but today it only supports a few dastabases, so we'll need to allow users keep using the traditional Hibernate for a little longer.

**Comment by geoand** [comment]
It should probably a separate extension, something like `hibernate-reactive-rest-data-panache`

**Comment by Sgitario** [comment]
> It should probably a separate extension, something like `hibernate-reactive-rest-data-panache`

Yes, my proposal solution will have a new extension called `hibernate-reactive-rest-data-panache`. 
ETA: 3-4 days

**Comment by Sanne** [comment]
Right a new extension would be ideal; it would give us the flexibility to mark it experimental initially, let it grow, and switch defaults when we think it's a good time.

In parallel we could also work on allowing a Reactive datasource to wrap any JDBC driver via https://vertx.io/docs/vertx-jdbc-client/java/ - once Quarkus supports that wrapper it would open the doors to switch.

**Comment by gsmet** [comment]
> once Quarkus supports that wrapper it would open the doors to switch

I don't think we should "switch" anything to Hibernate Reactive.

Hibernate ORM is here to stay and is still the best solution for a ton of use cases.
