### ISSUE TITLE
Quarkus won't accept eureka properties 

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#22557]
I have an eureka server and i am trying to register 2 microservice in quarkus in this eureka server.
When i put theses properties:

```
quarkus.spring-cloud-config.eureka.client.serviceUrl.defaultZone=${quarkus.spring-cloud-config.url}/eureka/
eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
```

i have this errror: 'Unknown property 'quarkus.spring-cloud-config.eureka.client.serviceUrl.defaultZone'microprofile(unknown)'
And anyway, nothing works.

Where is my mistake ?

**Comment by geoand** [comment]
There is no such configuration (at least not part of any Quarkus extension). 

Did you see this in some documentation?
