### ISSUE TITLE
quarkus.application.name config property unavailable on 2.6.1.Final

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#22567]
### Describe the bug

Hello
on Quarkus 2.6.1.Final, it seems it doesnt work again...

	@ConfigProperty(name = "quarkus.application.name")

        Suppressed: java.util.NoSuchElementException: SRCFG00014: The config property application.name is required but it could not be found in any config source

### Expected behavior

quarkus.application.name should provide application name

### Actual behavior

Quarkus Failed to start

### How to Reproduce?

@ConfigProperty(name = "quarkus.application.name")

and mvn quarkus:dev

### Output of `uname -a` or `ver`

linux

### Output of `java -version`

jdk 11

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.2

**Comment by gsmet** [comment]
@srigano was it working with 2.6.0.Final?

**Comment by srigano** [comment]
No. but i remember having testing succesfully it on 2.4.x ...
let me test it again.

**Comment by radcortez** [comment]
I've tried it with a personal project with 2.6.1 and it worked fine for me. @srigano are you able to provide me with a reproducer? Maybe there is some weird combination that is causing the issue.
