### ISSUE TITLE
Kafka processing prop throttled.unprocessed-record-max-age.ms unexpected behavior

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#22561]
### Describe the bug

Hi guys!
Recently I've noticed some interesting behavior in records from kafka processing: if I set throttled.unprocessed-record-max-age.ms = 12000, and then use Thread.sleep(8000) inside a record processing method like this:

> @Blocking
@Acknowledgment(value = POST_PROCESSING)
@Incoming("test-incoming")
public void receiveEvent(SomeObject event) {
    log.info("starting processing event {}", event.getId());
    try {
        Thread.sleep(8000);
    } catch (Exception ex) {}
    log.info("finished processing event {}", event.getId());
}

And then I send, let's say 10 messages into this topic. From time to time, it fails because of "hasTooManyMessagesWithoutAck" which is not kind of clear because the message is processed much faster than 12 seconds.
I made a small investigation and found out that problem is not with the already processed message, but with the next one, which is waited for too long in Queue<OffsetReceivedAt> receivedOffsets (KafkaThrottledLatestProcessedCommit). This method takes part in hasTooManyMessagesWithoutAck consideration. The next message stays in receivedOffsets for some time before processing the record actually started. 
And it happens more often when @Retry annotation is used: 2 corrupted records (record processing ends with exception and takes all retries) in a row, and default throttled.unprocessed-record-max-age.ms = 60s is easily used in case of @Retry(delay = 5000, maxRetries = 6)

### Expected behavior

throttled.unprocessed-record-max-age.ms config applies individually for each record after its processing starts. Otherwise, there should be a way to configure something like "processing.records.queue.max.size", which does not equal 1 in the current implementation.

### Actual behavior

throttled.unprocessed-record-max-age.ms config applies to all received offsets, even for records whose processing hasn't started yet

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0

### Additional information

I believe it's not really a bug, just a way how throttled commit processing works. But I would be definitely glad to see a small explanation about such behavior in your commit strategies guide [here](https://quarkus.io/guides/kafka#commit-strategies)

**Comment by OleKsimov** [comment]
Please let me know if you didn't know about this behavior and need a reproducer. I'll attach it after the holidays.

**Comment by OleKsimov** [comment]
I would like to add that you have such beautiful reactive kafka records consuming implementation :)
The only thing I don't understand from the code is from which context and who exactly calls KafkaRecordStreamSubscription.request(long n) and who controls the demand.
As I can see, this Subscription's responsibility is to send polled from a topic (deserialized) records to downstream -> processing. But I just can't find out who decides the timeout .request(...) method is called with, and who controls these calls.

**Comment by ozangunalp** [comment]
@OleKsimov As you said the behavior you are having is expected. The throttled commit strategy registers the timestamp when each record is received. Using this timestamp, it checks periodically if any record has waited in the queue without being acked or nacked for more than `throttled.unprocessed-record-max-age.ms`. It is one of the ways to avoid queuing too many records without processing them in time.

In your example, if all 10 records are received at the same time, as records are processed sequentially at approximately 8 seconds, the second record won't be acked yet at the end of 12 seconds.

Hope this clears things up a bit. https://quarkus.io/blog/kafka-commit-strategies/ gives more details about the throttled commit strategy. It dates a bit but should be correct most of the time.

For your question about requests, in reactive messaging the downstream processing is back-pressure aware and requests messages at the rate it can process. You can read more about back-pressure on this blog post https://quarkus.io/blog/mutiny-back-pressure/#introducing-reactive-streams

**Comment by OleKsimov** [comment]
@ozangunalp 

> As you said the behavior you are having is expected

Well, I said that it's totally unexpected, and that's why I created this issue ;)

> In your example, if all 10 records are received at the same time

Unfortunately, they are not received at the same time. They are polled simultaneously but processed one by one, and 2 of them are considered "received" at the same time, others are not. And that is why I created this issue.

> The throttled commit strategy registers the timestamp when each record is received

So my exact suggestion is to provide the ability to manage the time it is received or point out in documentation that a developer is not in control of this process. Otherwise, it is unclear in the current implementation and leads to unexpected results. 

For example, if I have 10 messages in the topic and process them one by one (ordering = true, max.poll.records = 10), they all are polled simultaneously but are not considered "received" after this. And when record_1 is considered received (added to receivedOffsets queue), record_2 is considered received too, but record_3 is NOT. Property throttled.unprocessed-record-max-age.ms controlling exactly what then for 
a) record_1
b) record_2 
c) record_3
?

How can it be used properly if a developer doesn't know when the record is actually received?

**Comment by ozangunalp** [comment]
I now understand the confusion. A record is considered "received" not when it is polled from the broker but depending on how the downstream processing "requests" records to consume.

In most cases, the processing is sequential and the downstream processor make one request each time it acks/nacks a record. 

However, having the first two requests at the same time seems odd. I need to take a look. I suspect that it has to do with the part of the throttled commit strategy which initializes the offset store by fetching committed offsets from the broker for a topic partition.

**Comment by cescoffier** [comment]
Closing - was a question (use discussion instead of issues).
