### ISSUE TITLE
Generated projects are using `@NativeImageTest`, `@QuarkusIntegrationTest` should be pushed.

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#22560]
### Describe the bug

Generated projects are using `@NativeImageTest`, `@QuarkusIntegrationTest` should be pushed.

`@QuarkusIntegrationTest` was introduced with Quarkus 1.13, in guides (e.g. https://quarkus.io/guides/getting-started-testing#native-executable-testing) is mentioned as the way forward.

I think newly generated applications should use `@QuarkusIntegrationTest` at least for native testing.

### Expected behavior

Generated projects are using `@QuarkusIntegrationTest` for native testing.

### Actual behavior

Generated projects are using `@NativeImageTest`.

### How to Reproduce?

Generate application using code.quarkus || quarkus cli || maven plugin.

**Comment by geoand** [comment]
@ia3andy I thought we have already made this change

**Comment by geoand** [comment]
This was actually fixed by https://github.com/quarkusio/quarkus/pull/23488
