### ISSUE TITLE
Failure to startup with io.quarkus:quarkus-smallrye-reactive-messaging-kafka extensions

### ISSUE THREAD

**Issue by pcasaes** [quarkusio/quarkus#2258]
Error during startup:

`Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped beans must declare a non-private constructor with no parameters: CLASS bean [types=[io.smallrye.reactive.messaging.impl.StreamFactoryImpl, java.lang.Object, io.smallrye.reactive.messaging.StreamFactory], qualifiers=[@Default, @Any], target=io.smallrye.reactive.messaging.impl.StreamFactoryImpl]`

To replicate create a standard hello rest service. Add fault-tollerance and messaging kafka

`mvn quarkus:add-extension -Dextensions=io.quarkus:quarkus-smallrye-fault-tolerance,io.quarkus:quarkus-smallrye-reactive-messaging-kafka`

Simply startup dev

`mvn compile quarkus:dev`

**Comment by mkouba** [comment]
This is a bug in `smallrye-reactive-messaging`:
https://github.com/smallrye/smallrye-reactive-messaging/issues/97

**Comment by pcasaes** [comment]
Tested against master branch on https://github.com/smallrye/smallrye-reactive-messaging
Issue resolved.
