### ISSUE TITLE
No native tests in grpc-hibernate module

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#22619]
### Describe the bug

No native tests in grpc-hibernate module, just  BlockingMutinyTest and BlockingRawTest.java in https://github.com/quarkusio/quarkus/tree/main/integration-tests/grpc-hibernate/src/test/java/com/example/grpc/hibernate

Simple approach like
```java
@QuarkusIntegrationTest
public class BlockingMutinyIT extends BlockingMutinyTest {
```
can't be used be used as tests are using injection and one gets NPE when invoking method on `client`

```java
    @GrpcClient
    Test client;
```

Checked gRPC related guides on https://quarkus.io/guides/ but didn't find the right hint to construct the client instead of `@GrpcClient` usage.

CC @michalszynkiewicz 

### Expected behavior

Native tests available in grpc-hibernate module

### Actual behavior

No Native tests in grpc-hibernate module

### Quarkus version or git rev

Quarkus main

**Comment by michalszynkiewicz** [comment]
There are two ways the call to a grpc endpoint can be done in native tests:

- by manually building the channel and the client, as done in HelloWorldServiceTest in `integration-tests/grpc-proto-v2`
- by creating the client on the application side and proxying call results through resteasy or sth
