### ISSUE TITLE
Error `Circular dependencies not supported` if two beans reference each other

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#22623]
### Describe the bug

 I expect that at first only proxy beans get injected to avoid the error `Circular dependencies not supported`

### Expected behavior

Injected Proxies avoid a `Circular dependencies` error.

### Actual behavior

Error `Circular dependencies not supported`

### How to Reproduce?

[quarkus-error-reproducer.zip](https://github.com/quarkusio/quarkus/files/7809603/quarkus-error-reproducer.zip)

` ./gradlew quarkusDev`

### Output of `uname -a` or `ver`

5.15.12-zen1-1-zen

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12) OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.3.3

**Comment by mkouba** [comment]
This works as expeced - in CDI a circularity in a dependency graph is only supported if at least one bean participating in every chain has a normal scope, e.g. `@ApplicationScoped`. Both beans in your reproducer are `@Dependent`.

See also the spec - [Dependency injection and lookup](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#injection_and_resolution).

**Comment by MartinX3** [comment]
@mkouba according to the quarkus docs @dependent has the same scope as the mother class, in my case the scope of the @path annotation of resteasy.

How should I change my scope of the API, service and repo layer without performance and security reduction?
Multiple users are using the rest endpoints at the same time with their user accounts.

**Comment by mkouba** [comment]
> @mkouba according to the quarkus docs @dependent has the same scope as the mother class, in my case the scope of the @path annotation of resteasy.

Well, it does not have the same scope but is bound to the lifecycle of the target bean. In your case, a **new instance** of the service is **created per each resource class instance**, and if I'm not mistaken the default scope of a resource is `@Singleton`.

> Multiple users are using the rest endpoints at the same time with their user accounts.

Your services should be either stateless, immutable or thread-safe.

> How should I change my scope of the API, service and repo layer without performance and security reduction?

It depends. If you make the service `@ApplicationScoped` then you'll have to make sure that it's OK to share the service instance between all resources.

**Comment by MartinX3** [comment]
Ah, I thought the default scope of a @Path would be @RequestScoped, since rest APIs are usually for requests.
So I assume the best way with maintaining security would be to let the API-Layer annotated with @Path, the Repo-Layer annotated with @Depend and annotate the Service-Layer with @RequestScoped.
Because I read https://quarkus.io/guides/cdi#what-scopes-can-i-actually-use-in-my-quarkus-application and it said http requests.
Also here is mentioned that it's ApplicationScoped by default: https://github.com/quarkusio/quarkus/issues/1371#issuecomment-471503989. But instead it's @Singleton if I understand everything correctly.

The guide
https://quarkus.io/guides/resteasy-reactive
is not very clear about scopes.

The guide
https://quarkus.io/guides/rest-json#lifecycle-of-resources
is enough for me.

So in the end even if I'm using reactive only I need to find and read the non reactive guides.
I thought reactive should replace the non reactive approach, so I thought reading only the reactive guide variants is enough.

**Comment by mkouba** [comment]
> So I assume the best way with maintaining security would be to let the API-Layer...

I'm not a security expert (CC @sberyozkin) but I believe that a natural fit for a service is `@Singleton/@ApplicationScoped` as the logic can be usually shared.

> Also here is mentioned that it's ApplicationScoped by default: [#1371 (comment)](https://github.com/quarkusio/quarkus/issues/1371#issuecomment-471503989). But instead it's @singleton if I understand everything correctly.

https://quarkus.io/guides/cdi#applicationscoped-and-singleton-look-very-similar-which-one-should-i-choose-for-my-quarkus-application

> Weird, somehow my IDE IntelliJ says that quarkus.resteasy.singleton-resources doesn't exist.

Maybe it's only used for resteasy-classic and not resteasy-reactive? CC @geoand

**Comment by MartinX3** [comment]
Thank you for your response.

> I'm not a security expert (CC @sberyozkin) but I believe that a natural fit for a service is `@Singleton/@ApplicationScoped` as the logic can be usually shared.

Yes, but I read in the internet, that the application layer should be request/session scoped, to avoid sharing security relevant data.
Maybe because this layer injects other beans and communicates with the database and is behind the role credential protection of the user accounts.

> [quarkus.io/guides/cdi#applicationscoped-and-singleton-look-very-similar-which-one-should-i-choose-for-my-quarkus-application](https://quarkus.io/guides/cdi#applicationscoped-and-singleton-look-very-similar-which-one-should-i-choose-for-my-quarkus-application)

Yes, I know the difference, just the github comment confused me a bit first, but it seems that Quarkus changed the default behaviour after his comment.

> Maybe it's only used for resteasy-classic and not resteasy-reactive? CC @geoand
Yes, that would be interesting. Maybe the reactive guides need updates (to be independent from the normal guides)?

**Comment by geoand** [comment]
Indeed in RESTEasy Reactive, we always use Singleton
