### ISSUE TITLE
GraalVM issue with JsonNode serialization 

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22654]
### Describe the bug

When trying to serialize a JsonNode in native, we get the following error::

 ```
15:03:51,390 INFO  [app] 15:03:50,362 HTTP Request to /hello/big-serialize-list?expSize=99961 failed, error id: 23a57a4c-cb9d-4db1-b8a4-a0d362bdbb2f-1: org.jboss.resteasy.spi.UnhandledException: com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: com.fasterxml.jackson.databind.node.BaseJsonNode (targetConstructorClass: com.fasterxml.jackson.databind.JsonNode). Usually adding com.fasterxml.jackson.databind.node.BaseJsonNode to serialization-config.json fixes the problem.
15:03:51,392 INFO  [app]        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
15:03:51,393 INFO  [app]        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
15:03:51,394 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
15:03:51,395 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
15:03:51,396 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
15:03:51,396 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
15:03:51,397 INFO  [app]        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
15:03:51,398 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
15:03:51,399 INFO  [app]        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
15:03:51,399 INFO  [app]        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
15:03:51,400 INFO  [app]        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
15:03:51,400 INFO  [app]        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
15:03:51,401 INFO  [app]        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
15:03:51,401 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
```

Quarkus Upstream: `999-SNAPSHOT`
Java: `11`
Mandrel:  `21.2.0.2-Final Mandrel Distribution (Java Version 11.0.13+8)`

Reproducer: 
Project: https://github.com/pjgg/quarkus-test-suite/tree/feat/QUARKUS-1554
cmd: `mvn clean verify -Pnative -Dit.test=SerializationIT#serializeBigList`
Note: `serializeBigList` is disabled, so remove this tag first. 

Serialization config: https://github.com/pjgg/quarkus-test-suite/blob/feat/QUARKUS-1554/http/jaxrs/src/main/java/io/quarkus/ts/security/core/SerializationConfig.java

The test is pointing to this endpoint: https://github.com/pjgg/quarkus-test-suite/blob/feat/QUARKUS-1554/http/jaxrs/src/main/java/io/quarkus/ts/security/core/GreetingResource.java#L85

**Comment by gsmet** [comment]
Why would you serialize a Jackson JsonNode with the JDK serializer? Or did I miss something?

Because if that's what you're trying to do, maybe let's try to focus on real world use cases?

**Comment by rsvoboda** [comment]
I asked Pablo in JIRA to combine test https://github.com/quarkusio/quarkus/issues/19711 with bigger payload scenario from https://github.com/FasterXML/jackson-databind/commit/3ccde7d938fea547e598fdefe9a82cff37fed5cb which is about JDK serialization of JsonNode. We are covering Jackson update in 2.2.5.Final because of that use case.

**Comment by gsmet** [comment]
Well, maybe it's an easy fix but if it's not, I doubt it's a good investment of our time to test this in native.

**Comment by zakkak** [comment]
So shall we close this as won't fix?
