### ISSUE TITLE
Gauges annotation are not showing up his value, on a resteasy endpoint

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22662]
### Describe the bug

If a gauge is declared in a Resteasy endpoint through an annotation, the gauge value is not pushed to `/metrics`

Example: 
```
@Path("/using-microprofile-pingpong")
public class UsingMicroProfilePingPongResource {

    private static final String PING_PONG = "ping pong";
    private static final long DEFAULT_GAUGE_VALUE = 100L;

    // counters works as expected
    @GET
    @Counted(name = "simple_counter_mp", absolute = true)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/counter")
    public String simpleScenario() {
        return PING_PONG;
    }

    //TODO gauges are not promoting their values to /metrics
    @GET
    @Gauge(name = "simple_gauge_mp", unit = MetricUnits.NONE)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/gauge")
    public long highestPrimeNumberSoFar() {
        return DEFAULT_GAUGE_VALUE;
    }
}
```

But If I move on the gauge to a separate public method, then works as expected: 

```
@Path("/using-microprofile-pingpong")
public class UsingMicroProfilePingPongResource {

    private static final String PING_PONG = "ping pong";
    private static final long DEFAULT_GAUGE_VALUE = 100L;

    @GET
    @Counted(name = "simple_counter_mp", absolute = true)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/counter")
    public String simpleScenario() {
        return PING_PONG;
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/gauge")
    public long highestPrimeNumberSoFar() {
        return getDefaultGauge();
    }

    @Gauge(name = "simple_gauge_mp", unit = MetricUnits.NONE)
    public long getDefaultGauge() {
        return DEFAULT_GAUGE_VALUE;
    }
}
```

Additional when the gauge is not promoted I am getting the following warning message:
```
2022-01-05 16:48:04,996 WARN  [io.mic.cor.ins.int.DefaultGauge] (vert.x-worker-thread-0) Failed to apply the value function for the gauge 'io.quarkus.ts.micrometer.prometheus.UsingMicroProfilePingPongResource.simple_gauge_mp'. Note that subsequent logs will be logged at debug level.: javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:46)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
```

From a developer experience point of view, would be great to have the same behavior in all metrics data structures. So, if counter annotations is available in an endpoint declaration then gauges should be also valid. 

### Output of `java -version`

openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by jmartisk** [comment]
What metrics extension are you using? These look like MP Metrics annotations, but the package name of the test implies Micrometer. Is this using the Micrometer-to-MPMetrics bridge?
I can't reproduce this with pure MP Metrics, the gauge works normally.

**Comment by rsvoboda** [comment]
There is bank holiday in Spain today so Pablo will probably respond tomorrow, I will try to provide some context.

I think he was using Micrometer and bridge to MP metrics as he was working on additional test development for QUARKUS-1571  / https://github.com/quarkusio/quarkus/issues/20047

**Comment by jmartisk** [comment]
Thanks @rsvoboda. https://github.com/quarkusio/quarkus/pull/22681 should fix it

**Comment by jmartisk** [comment]
In any case, this is a bit of a silly use case and will obviously not work on REST methods that take parameters, because calling the `/metrics` endpoint does not provide any values for REST method parameters. If you try to attach a gauge to a REST method with parameters, it will blow up anyway.
