### ISSUE TITLE
Error `It's not possible to automatically add a synthetic no-args constructor to an unproxyable bean class.`

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#22669]
### Describe the bug

Using a @RequestScoped Service fails, if it extends a abstract service and uses constructor injection to redirect a Repository Bean proxy into the super constructor.

It works, if I use attribute injection via `@Inject`.

Kotlin, Gradle, AllOpen-Plugin

### Expected behavior

A working application.

### Actual behavior

```[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: It's not possible to automatically add a synthetic no-args constructor to an unproxyable bean class. You need to manually add a non-private no-args constructor to org.quarkus.error.reproducer.service.FruitAService in order to fulfill the requirements for normal scoped/intercepted/decorated beans.```

### How to Reproduce?

[quarkus-error-reproducer.zip](https://github.com/quarkusio/quarkus/files/7817591/quarkus-error-reproducer.zip)

` ./gradlew quarkusDev`

### Output of `uname -a` or `ver`

5.15.12-zen1-1-zen

### Output of `java -version`

 openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12) OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by MartinX3** [comment]
A similar problem happens with entities.
If I use the constructor injection to redirect a `@OneToOne` entity to the abstract entity constructor my used entity extends.
(It's a @MappedSuperclass).
If I inject it directly there, the entity is there.
A funny thing is, that the entity is also there if I use the IntelliJ debugger. There are two entries with the entity attribute.
The `p`-Symbol is null, but the `p`-Symbol is filled with the correct entity.

**Comment by manovotn** [comment]
> a synthetic no-args constructor

The automagical creation of a no-arg constructor is only single-level meaning is there is an [abstract] super class that doesn't have no-args constructor, it will fail.

**Comment by MartinX3** [comment]
@manovotn since I use the no-args plugin, shouldn't it extend my abstract class? It's open by default in kotlin.

**Comment by mkouba** [comment]
> @manovotn since I use the no-args plugin, shouldn't it extend my abstract class? It's open by default in kotlin.

I'm not sure about kotlin/allopen but in java a no-args constructor is only added by the compiler if there's no other constructor declared on the class.

**Comment by mkouba** [comment]
CC @evanchooly

**Comment by MartinX3** [comment]
In theory it should work since I can create an object of a class extending an abstract class without problems.

**Comment by alexcheng1982** [comment]
You forgot to add annotation configuration of no-args plugin. So no-args constructors are not generated. You can verify that using `javap`.

```kotlin
noArg {
    annotation("javax.enterprise.context.RequestScoped")
}
```

To make this work, you also need to add `@RequestScoped` to the parent abstract class `AFruitService`, or add a custom annotation and enable it in the no-args plugin settings.

**Comment by MartinX3** [comment]
Hmm, I wonder what's the problem with the abstract entity then.

**Comment by alexcheng1982** [comment]
The reproducer project doesn't have those entities you mentioned before. If the issue is related to auto-generated no-args constructors, you can use `javap` to verify that whether those constructors have been generated correctly. Otherwise, you may need to update the reproducer code to demonstrate that.

**Comment by MartinX3** [comment]
Good hint.
I think this bug ticket should be closed.
But maybe the kotlin guides should hint for the kotlin plugins, if someone uses generics and abstract classes.

Here is the new issue ticket: https://github.com/quarkusio/quarkus/issues/22689
