### ISSUE TITLE
Prevent Docker build if nothing has changed

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#22680]
### Description

In a multi module project with two separate applications, but shared modules, you can build all applications at once as Docker containers, but lets say if only application B changes, application A will be built again too.

"CI-wise" this means, both applications are getting re-deployed all the time.

Is there a way to only deploy again, what has changed?

**Comment by famod** [comment]
I think this is out of scope for Quarkus, especially if we are talking about two different apps. (/cc @geoand, maybe you see it differently)

In case you are using Maven and Git you might want to have a look at https://github.com/gitflow-incremental-builder/gitflow-incremental-builder
Disclaimer: I'm the maintainer of that Maven extension and I have been using it in my own (corporate) projects for 3 years now.
It's also in use by Quarkus' own CI and has reduced the average PR build time substantially.

**Comment by famod** [comment]
PS: There might actually be some potential towards https://reproducible-builds.org/, e.g. not embedding a new build timestamp for each build and things like that.

**Comment by geoand** [comment]
> I think this is out of scope for Quarkus, especially if we are talking about two different apps. (/cc @geoand, maybe you see it differently)

I agree this is not something Quarkus should handle.

**Comment by mklueh** [comment]
@famod wow thanks a lot, this is really helpful! Diffscope seems to be a really great fallback solution.

As I'm using Gradle, the plugin won't work for me, however on the reproducible build site there was a Gradle section, and it seems there is a built-in way to build idempotent jar archives https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
