### ISSUE TITLE
Random port configuration of port in tests

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#2269]
Currently, there is one property called `quarkus.http.test-port` where you can set the port number where to start the Quarkus server, but we should provide a special char for setting a random private port (49152 through 65535)

I purpose something like `quarkus.http.test-port=$`

This is important for allowing the system to execute tests in parallel.

If agrees I can send a PR.

**Comment by starksm64** [comment]
Just use 0 as that is the normal linux way of binding to a system defined random port and could just work on many systems.

**Comment by lordofthejars** [comment]
Ok, then please assign me this issue and when I finish my current Quarkus issue, I'll start working on it.

**Comment by gastaldi** [comment]
I gave a shot at this and implemented https://github.com/quarkusio/quarkus/pull/4140. I'd appreciate a review ;)
