### ISSUE TITLE
Kafka doesn't respect quarkus logging config

### ISSUE THREAD

**Issue by cherrydev** [quarkusio/quarkus#22698]
### Describe the bug

When logging categories relating to kafka are configured using quarkus configuration properties, they are not respected. Instead, separate configuration properties are required to be set in order to control Kafka's logging. This requires logging configuration to be duplicated.

### Expected behavior

When logging categories are configured using `quarkus.log.category`-prefixed properties, they should control logging of components in Kafka.

### Actual behavior

`quarkus.log.category`-prefixed properties for kafka components are insufficient to control logging methods. Instead, additional properties prefixed with `logging.level.` are required.

### How to Reproduce?

1. create quickstart quarkus app with kafka-streams extension enabled
2. boot app and ensure that logging messages from `org.apache.kafka` categories are appearing in the log
3. set in `application.properties` `quarkus.log.category."org.apache.kafka".level=OFF`
4. Re-run application and note that logs still appear

**Comment by ozangunalp** [comment]
Disabling Kafka logs with `quarkus.log.category."org.apache.kafka".level=OFF` doesn't work because the Kafka extension provide default WARNING logging level for verbose loggers i.e `org.apache.kafka.clients`, `org.apache.kafka.common.metrics`, `org.apache.kafka.clients.utils`. 

This should disable all if not most of the Kafka logs: 
```
quarkus.log.category."org.apache.kafka.common".level=OFF
quarkus.log.category."org.apache.kafka.clients".level=OFF
```

**Comment by cherrydev** [comment]
Indeed this seems to be correct. I would have sworn that I'd tried a more specific logging category, but this definitely fixes it. Thank you!
