### ISSUE TITLE
Rest API rest easy reactive: cannot return Buffer as response

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#22694]
### Describe the bug

Should it not be possible to return a Buffer as response body?

```java
  @Path("/searchWithBuffer")
  @POST
  public Uni<Buffer> searchWithBuffer(Buffer buffer)  {   

   
    Uni<HttpResponse<Buffer>> response = client.postAbs("http://localhost:9888/search")       
      .putHeader("Content-Type", MediaType.APPLICATION_JSON)      
      .putHeader("Accept", MediaType.APPLICATION_JSON) 
      .putHeader("Cache-Control", "no-cache")        
      .sendBuffer( buffer ) ;          
 
      return response.map(HttpResponse::body);
     
  }  
```

### Expected behavior

The body as String in the result. 

### Actual behavior

The String returned

```json
{
    "delegate": {
        "bytes": "eyJ3aGF0ZXZlciI6InllcyJ9",
        "byteBuf": {
            "direct": false,
            "readOnly": false,
            "contiguous": true,
            "readable": true,
            "writable": true
        }
    },
    "bytes": "eyJ3aGF0ZXZlciI6InllcyJ9",
    "byteBuf": {
        "direct": false,
        "readOnly": false,
        "contiguous": true,
        "readable": true,
        "writable": true
    }
}
```

### How to Reproduce?

[example.zip](https://github.com/quarkusio/quarkus/files/7822803/example.zip)

1. Run the IT test

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1415]

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

### Additional information

Another question

I want to build merely somesort of proxy between a client and server. I just want to proxy the orginal request body to the server and return the response body back to the client.

For the request part. What is the best way to read the request body. As a

-> Buffer (but then the input is parsed as JSON)
-> Inputstream but this is blocking (reactive). Eventually in memory as well as i need to transform it to a Buffer.
-> byte[] but everything is in memory

can i somehow stream it?

For the response part.  What is the best way to return the esponse body. As a

-> Buffer (probably also parses the whole response)
-> Byte[] (in body in memory)
-> Outputstream (how and is blocking)

how can i stream the response body back using reast east reactive?

**Comment by geoand** [comment]
I could not reproduce the problem. The test in your example passed when I ran `mvn verify`

**Comment by argenstijn** [comment]
That is correct.  It Just output the result instead of verify it like a real test

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by geoand** [comment]
Can you update the example to actually fail properly then?
Asking so we can focus on actually fixing the problem (if there is one), instead of trying to guess

**Comment by argenstijn** [comment]
[example.zip](https://github.com/quarkusio/quarkus/files/7827660/example.zip)

Of course, already done. See attachment.

**Comment by geoand** [comment]
Thanks!
