### ISSUE TITLE
`reactive-pg-client` incompatible with `opentelemetry-exporter-otlp` in 2.6.1

### ISSUE THREAD

**Issue by langsamu** [quarkusio/quarkus#22700]
### Describe the bug

After upgrading to 2.6.1, I can no longer use OpenTelemetry and Reactive PostgresSQL together.

### Expected behavior

The Reactive PostgreSQL extension generates spans for each query and the OpenTelemetry exporter sends them to a collector.

### Actual behavior

`OpenTelemetryVertxTracer` throws a `ClassCastException` when the SqlClient executes a query.

[`#sendRequest`](https://github.com/quarkusio/quarkus/blob/077ea2ffce5cbfbb2217a8a8e11cd952387df142/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/vertx/OpenTelemetryVertxTracer.java#L93) expects the request to be a `io.vertx.core.spi.observability.HttpRequest`, but in this case it's a `io.vertx.sqlclient.impl.tracing.QueryRequest` instead.

### How to Reproduce?

https://github.com/langsamu/quarkus-22700-reproducer

### Quarkus version or git rev

2.6.1

**Comment by langsamu** [comment]
See also https://github.com/quarkusio/quarkus/discussions/22653#discussioncomment-1914064.

**Comment by geoand** [comment]
This was already fixed in https://github.com/quarkusio/quarkus/pull/22615
