### ISSUE TITLE
Quarks CLI autocompletion for fish shell 

### ISSUE THREAD

**Issue by benkeil** [quarkusio/quarkus#22710]
### Description

It would be nice to have also autocompletion for the fish shell

**Comment by ebullient** [comment]
We get our support for shell completion directly from picocli!

It looks like someone has asked for this before: [Feature Request: fish completion](https://github.com/remkop/picocli/issues/725), but they may need some help getting that done.

**Comment by geoand** [comment]
I'll close this an a request for an feature from an upstream project
