### ISSUE TITLE
Impossible to load resource folder content into InputStream

### ISSUE THREAD

**Issue by rodrigo-loza-mojix** [quarkusio/quarkus#22714]
### Describe the bug

The following method is supposed to load the contents of a resource folder, but the InputStream is empty. I know the folder is correct because if I point the path to a file I am able to load the files. I tried both Thread.currentThread ... and the one uncommented.

```java
    public List<String> getFilesInFolder(String path) {
        List<String> filePaths = new ArrayList<>();
        //InputStream datasetStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(path);
        InputStream datasetStream = Objects.requireNonNull(getClass().getClassLoader().getResourceAsStream(path));
        try {
            List<String> filenames = IOUtils.readLines(datasetStream, StandardCharsets.UTF_8);
            LOG.info("Filenames on path {}: {}", path, filenames);
            filePaths.addAll(
                    filenames.stream()
                            .peek(filename -> LOG.info("Evaluating file: {}", filename))
                            .filter(filename -> filename.endsWith(".json"))
                            .map(filename ->
                                    Objects.requireNonNull(
                                            getClass().getClassLoader().getResource(path + filename)
                                    ).getPath()
                            )
                            .collect(Collectors.toList())
            );
        } catch (IOException exception) {
            LOG.error("No files found in path {}.", path, exception);
        }
        return filePaths;
    }
```

### Expected behavior

InputStream should contain the contents of the folder (the filenames). It works on any other project except in quarkus.

### Actual behavior

InputStream is emtpy.

### How to Reproduce?

1. Create a quarkus project with quarkus.platform version 2.2.3.Final or greater. 
2. Create a resource folder 
3. Create files inside the resource folder
4. Use the code in the description to load the filenames
5. Validate InputStream is empty

### Output of `uname -a` or `ver`

Docker image registry.access.redhat.com/ubi8/openjdk-11-runtime:1.10

### Output of `java -version`

11

### GraalVM version (if different from Java)

No native, jvm build.

### Quarkus version or git rev

2.2.3.Final or greater

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

./mvnw package

**Comment by gsmet** [comment]
Could you create a small Maven project reproducing the issue? Thanks.

**Comment by geoand** [comment]
I assume from your description that this worked with `2.2.2.Final` for example?

**Comment by geoand** [comment]
Closing as we never got a reproducer
