### ISSUE TITLE
Property values can behave unexpectedly with trailing spaces

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#22740]
### Describe the bug

If a trailing space (or presumably another whitespace character) is present at the end of a value in the src/main/resources/application.properties file, it is passed verbatim (not trimmed) to the user of the property (in at least one case, see reproducer below).

### Expected behavior

I would expect trailing (or proceeding) whitespace in a property value to be trimmed. I think it should only be preserved if the value is quoted somehow.

### Actual behavior

In some cases the trailing whitespace remains when the property is used. See the reproducer for one such case.

### How to Reproduce?

Reproducer:

1. Run the https://quarkus.io/guides/opentelemetry example.
2. When populating the `application.properties` file, copy and past from the code block in the guide
3. Observe that. whitespace character has been added to the end of every property value in the `application.properties` file.
4. When starting Quarkus, observe: `Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://localhost:4317 `
5.   Remove the traiing white space from `quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://localhost:4317 ` in the `application.properties`.
6. Re-run Quarkus and observe that the above exception is not thrown.

### Output of `uname -a` or `ver`

Darwin Pauls-Mac-mini-5.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/paul/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Users/paul/.sdkman/candidates/java/11.0.7.hs-adpt Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by gsmet** [comment]
The general rule of thumb is:
- spaces are preserved as they should be given how `.properties` file are supposed to work
- we have a converter that can trim strings and we apply it on a per case basis (it might be missing for a ton of properties as we usually apply it when we think about it or when we have a report)

/cc @radcortez

**Comment by radcortez** [comment]
I'll have a look and check which OTel configs require the trimming converter.

**Comment by paulrobinson** [comment]
Thanks @radcortez!
