### ISSUE TITLE
How to eliminate multiple levels of `subscribe().with()`

### ISSUE THREAD

**Issue by Moicen** [quarkusio/quarkus#22759]
I have some async logic like this:

![A2B82710-B4D4-48CB-800C-37B78D66FC08](https://user-images.githubusercontent.com/3773928/148716142-d3509fb6-8b8d-484b-8910-65180b35e3f0.png)

However I don’t want to deal with each level of `errs`, is there anyway to flatten above nested block and just deal with all the exceptions in one level?

**Comment by cescoffier** [comment]
I don't know what kind of item is produced by your methods but it seems they are `Uni`. In this case, you need a root Uni and chain all the operations:

```java
Uni<T> main = rootTokenWithLoginWithCert()
                .chain(u -> u)
```

You should have at most 1 subscription, and most probably 0 as I guess your top method should return a Uni.

**Comment by Moicen** [comment]
@cescoffier With your suggestion, I find this document in addition:

- https://smallrye.io/smallrye-mutiny/guides/shortcuts

With some learning I simplified my code like this and it works:

![EBECEE1F-29AB-446D-BE58-45F2A09F368B](https://user-images.githubusercontent.com/3773928/148751123-2ec471bf-d186-454a-b207-7c4b36903714.png)

Thanks for help!

**Comment by Moicen** [comment]
@cescoffier  I further modified my function with the learned knowledge:

![80F6F72F-923A-4A96-BC96-C0FD229419F1](https://user-images.githubusercontent.com/3773928/148764231-834164da-47d4-454c-83de-db2e03714cd4.png)

So all the calling methods are simplified:

![3DC4D864-E0BE-435B-A50D-FA5A24E3EC36](https://user-images.githubusercontent.com/3773928/148764269-9fcb56d4-b4fa-4b6e-b53f-811e134841f0.png)

Thanks for teaching!

**Comment by cescoffier** [comment]
Should we close this issue?
