### ISSUE TITLE
ConfigSource fails to load while executing maven verify

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#22770]
### Describe the bug

When i execute the TEST in eclipse it;s working as expected. But when i execute the request
in maven context it fails.

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.557 s <<< FAILURE! - in com.example.ExampleIT
[ERROR] com.example.ExampleIT.shouldWhen  Time elapsed: 0.008 s  <<< ERROR!
java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: com.example.InMemoryConfigSource not a subtype
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: com.example.InMemoryConfigSource not a subtype

### Expected behavior

Should load the ConfigSource.

### Actual behavior

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.ExampleIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.218 s <<< FAILURE! - in com.example.ExampleIT
[ERROR] com.example.ExampleIT.shouldWhen  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: com.example.InMemoryConfigSource not a subtype
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: com.example.InMemoryConfigSource not a subtype

### How to Reproduce?

[example.zip](https://github.com/quarkusio/quarkus/files/7839381/example.zip)

1a  Runt he exampleIT test in eclipse (works)

1b Run maven verify (fails)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1415]

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 LTS OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

**Comment by argenstijn** [comment]
The code is working when using maven-surefire-plugin. But with the maven-surefire-plugin it fails

**Comment by argenstijn** [comment]
Thanks @fwippe . That is fore sure the same issue.

@gsmet Shall i close this issue?

**Comment by gsmet** [comment]
Let's keep it open. It's simple and it has a reproducer. Just let make sure we close #20190 when we close this one.

**Comment by radcortez** [comment]
Setting the failsafe plugin configuration to `<useModulePath>false</useModulePath>` will fix this.

This is caused by the failsafe plugin using the module path service loader. @stuartwdouglas trying a workaround for this in https://github.com/quarkusio/quarkus/pull/20466, but it caused other issues.

At this point, I think we have no other fix than changing the failsafe configuration (I've verified it with the reproducer and it fixes the issue).

**Comment by gsmet** [comment]
Maybe we should generate the projects with the `failsafe.useModulePath` property set to false for the time being?

I think it would be better to use the property.

**Comment by radcortez** [comment]
Yes, we can do that. I'll send a PR for it.
