### ISSUE TITLE
Funqy unable to get event data

### ISSUE THREAD

**Issue by evanshortiss** [quarkusio/quarkus#22786]
### Describe the bug

I'm using `import io.quarkus.funqy.Funq` to create a Serverless function for use with Knative and a Knative Kafka Source. The Funq processes JSON objects. 

When I send a request via HTTP POST it works as expected. Example cURL:

```
curl -X POST -H "Content-Type: application/json; charset=utf-8" -H "ce-id: 03ce2ea0-c3a7-499c-8edd-ac4e31c6536a" -H "ce-type: shots" -H "ce-source: localhost" -H "ce-specversion: 1.0" -d @ce.body.json $URL_ENDPOINT
```

When the Kafka Source sends the data to the same Funq this error is printed. Could it be that some header is not set correctly by the Kafka source HTTP request?

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to / failed, error id: 03b90aeb-11c9-41cd-8e01-b9407e83d38f-6: java.lang.RuntimeException: Don't know how to get event data (dataContentType: 'null', javaType: 'functions.Shot').
	at io.quarkus.funqy.runtime.bindings.knative.events.HeaderCloudEventImpl.data(HeaderCloudEventImpl.java:185)
	at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.lambda$processCloudEvent$5(VertxRequestHandler.java:232)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

What makes this issue more interesting is that it only started occurring after I updated from Quarkus version 1.8.1.Final to version 2.2.3.Final. The issue is also happening with the latest Quarkus release. If I use Quarkus 1.8.1.Final the Funq is able to deserialise the incoming JSON event, but then I lose access to the CloudEventBuilder.

### Expected behavior

Events sent from Kafka Source should be correctly deserialised and processed by my Funq. 

### Actual behavior

The stack trace above is printed. 

### How to Reproduce?

1. Obtain an OpenShift/Kube cluster with Serverless/Knative installed. 
1. Enable Eventing and Serving per the docs, making sure to enable the KafkaSource option for Eventing. 

Deploy a Knative function:

1. kn func create -l quarkus
1. kn func build
1. kn service create my-service --image $IMAGE_FROM_BUILD

Create a Kafka Source that sinks events to `my-service`. Pod logs for `my-service` show the stack trace above.

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 20.6.0 Darwin Kernel Version 20.6.0

### Output of `java -version`

AdoptOpenJDK-11.0.11

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Knative Version: v0.25.1

**Comment by geoand** [comment]
Does this still happen in later versions of Quarkus?

**Comment by matejvasek** [comment]
I'll try to look into this.

**Comment by matejvasek** [comment]
how does `functions.Shot` looks like?

**Comment by matejvasek** [comment]
Oh sorry, now I see it's in cluster producer that causes issues.

**Comment by matejvasek** [comment]
@evanshortiss I would be useful to see what request form kafka looks like. I can create image logging this. Would you mind deploying it into your cluster and used is as a sink?

**Comment by evanshortiss** [comment]
> Does this still happen in later versions of Quarkus?

@geoand yes, I tried in 2.6.2 and found the same behaviour. I am using 2.2.3 since this is the default version in the `quarkus` template used by `kn func create`, i.e `kn func -l quarkus my-service`.

@matejvasek yes, happy to deploy an image that logs the request headers etc. If you have one ready I will do it ASAP.

**Comment by matejvasek** [comment]
maybe related: I recall that in past kafka returned some header with value==empty string which caused troubles to some client.

**Comment by matejvasek** [comment]
if the header wasn't set at all it worked but if the header was present with explicit empty value it was causing troubles, but it was months ago, maybe they fixed it

**Comment by matejvasek** [comment]
@evanshortiss the image is: quay.io/mvasek/fn-g:latest
```go
func Handle(ctx context.Context, res http.ResponseWriter, req *http.Request) {
	for key, vals := range req.Header {
		fmt.Printf("header: %q, values: %q\n", key, vals)
	}

	body, err := io.ReadAll(req.Body)
	if err != nil {
		panic(err)
	}

	fmt.Printf("body: %q\n", body)

	res.WriteHeader(200)

}
```

**Comment by matejvasek** [comment]
with it we should see headers/body and then hopefully reproduce the issue locally

**Comment by evanshortiss** [comment]
@matejvasek I think it's related to a missing content-type header. Here are the logs from your image:

```
Initializing HTTP function
listening on http port 8080
header: "Content-Length", values: ["152"]
header: "Accept-Encoding", values: ["gzip"]
header: "Ce-Source", values: ["/apis/v1/namespaces/cloud-services-tmm-stage/kafkasources/kafka-shots#shots"]
header: "X-Forwarded-Proto", values: ["http"]
header: "Ce-Key", values: ["69HevhP4TXkU6IK2XuIzL:_CJ0Px_yJ_Iu7qT5gH5Xd"]
header: "Ce-Specversion", values: ["1.0"]
header: "Ce-Subject", values: ["partition:3#1"]
header: "Ce-Time", values: ["2022-01-11T02:24:33.192Z"]
header: "User-Agent", values: ["Go-http-client/1.1"]
header: "Forwarded", values: ["for=10.128.5.83;proto=http"]
header: "X-Request-Id", values: ["fd996ccd-6a12-4be1-815c-b4505452754c"]
header: "Ce-Id", values: ["partition:3/offset:1"]
header: "Ce-Type", values: ["dev.knative.kafka.event"]
header: "K-Proxy-Request", values: ["activator"]
header: "Traceparent", values: ["00-6b6cef2c063130e83cffdd53514361bd-82c2968fd537ef31-00"]
header: "X-Forwarded-For", values: ["10.128.5.83, 10.128.4.25"]
body: "{\"match\":\"69HevhP4TXkU6IK2XuIzL\",\"game\":\"g_YSt4iZy2tw1Lxxm5uTz\",\"by\":{\"username\":\"Bow Warlock\",\"uuid\":\"_CJ0Px_yJ_Iu7qT5gH5Xd\"},\"shots\":28,\"human\":false}"
```

I can recreate the error locally using the curl below. Notice that the content-type is set, but empty. I had to do this since curl will default to `application/x-www-form-urlencoded`:

```
curl -X POST -H "Content-Type: " -H "ce-id: 03ce2ea0-c3a7-499c-8edd-ac4e31c6536a" -H "ce-type: shots" -H "ce-source: foo" -H "ce-specversion: 1.0" -d @ce.body.json http://localhost:8080/
```

This curl produces the `java.lang.RuntimeException: Don't know how to get event data (dataContentType: 'null', javaType: 'functions.Shot')` error that matches what I see in cluster.

It looks like the Kafka Source is not setting a content-type, and the Funq is not defaulting JSON. Should it default to JSON?

**Comment by matejvasek** [comment]
@evanshortiss I think defaulting to JSON could be OK.

**Comment by matejvasek** [comment]
but also I should report this to kafka source maintainers

**Comment by evanshortiss** [comment]
> I think defaulting to JSON could be OK.

Sorry, I should rephrase. Is there a way to instruct the Funq to assume the incoming HTTP body is JSON? Or will I need to read the input as a String type and manually parse to JSON? 

> but also I should report this to kafka source maintainers

Right, I'm not sure what's the correct approach here. Data in Kafka could be in various formats, so they might deliberately not assume content-type? Worth a discussion though.

**Comment by patriot1burke** [comment]
> I mean we should change defaulting in Quarkus code not an app. Until then the string/byte[] workaround might work, I didn't try it however.
> 
> @patriot1burke do you think that defaulting to JSON if Content-Type is not present is all right?

I really don't know.  IIRC, the spec requires setting the content-type.  I guess we can just assume json.

**Comment by matejvasek** [comment]
@evanshortiss would you mind filling and issue here: https://github.com/knative-sandbox/eventing-kafka/issues ?

**Comment by evanshortiss** [comment]
Thanks @matejvasek. Using byte[] is the magic workaround for the content-type issues 😄 

Sure I can open an issue for discussion. It sounds like omitting the datacontenttype is valid in certain scenarios though: https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#datacontenttype

**Comment by matejvasek** [comment]
I think it's valid you with structured mode:
Example:
```
curl -v "http://localhost:8080" -H "Content-Type: application/cloudevents+json" -XPOST -d '{           
        "id":"abc",
        "source": "my-src",
        "type": "my-type",
        "specversion":  1.0,
        "data": { "message": "Hello" }
}'
```
since the whole event  is in JSON the data are also implied to be JSON.

**Comment by matejvasek** [comment]
For binary mode (where metadata are in HTTP headers) there is no such implication. We really can't safely assume anything, we can just do some best effort and assume JSON and hope JSON is what most developer use. I am still not sure if I want to do that. IMHO this should be fixed in the kafka source.

**Comment by matejvasek** [comment]
@evanshortiss what triggers the kafka source?

**Comment by matejvasek** [comment]
maybe the source works ok, but he component pushing to kafka is not

**Comment by matejvasek** [comment]
the component pushing it should also set content type metadata

**Comment by evanshortiss** [comment]
@matejvasek I was just doing something similar. Good thinking :)

The first message is pushed to my Kafka topic without setting headers. Second message is pushed with `headers={ 'content-type':'application/json' }`. The Kafka Source is inspecting the header to determine the `datacontenttype` correctly for the second message.

I this is worth mentioning in the [Kafka Source page](https://knative.dev/development/eventing/sources/kafka-source/), even if it seems obvious in retrospect. WDYT?

```
 cloudevents.Event
Context Attributes,
  specversion: 1.0
  type: dev.knative.kafka.event
  source: /apis/v1/namespaces/cloud-services-tmm-stage/kafkasources/kafka-shots#shots
  subject: partition:4#1
  id: partition:4/offset:1
  time: 2022-01-11T18:08:34.955Z
Extensions,
  key: bHo2EiR1K1psnMR5BNLEb:djWRVL_gCrQV_gOIkQEew
Data,
  {"match":"bHo2EiR1K1psnMR5BNLEb","game":"78giQ2Rua08zxW0yiYZ7J","by":{"username":"Stream Oriole","uuid":"djWRVL_gCrQV_gOIkQEew"},"shots":7,"human":false}


 cloudevents.Event
Context Attributes,
  specversion: 1.0
  type: dev.knative.kafka.event
  source: /apis/v1/namespaces/cloud-services-tmm-stage/kafkasources/kafka-shots#shots
  subject: partition:4#2
  id: partition:4/offset:2
  time: 2022-01-11T18:09:19.601Z
  datacontenttype: application/json
Extensions,
  key: A0ved_CyyHK_vU-t4Mycp:oOTUAMndQKuKNqSLJXpiT
Data,
  {
    "match": "A0ved_CyyHK_vU-t4Mycp",
    "game": "0dlRhJy8uNhCnPHSRB8rV",
    "by": {
      "username": "Navy Stag",
      "uuid": "oOTUAMndQKuKNqSLJXpiT"
    },
    "shots": 1,
    "human": false
  }
  ```

**Comment by matejvasek** [comment]
@evanshortiss so you were able to fix your component that is pushing events into kafka?

**Comment by lance** [comment]
@patriot1burke the proper thing to do here, in my opinion, is to make no assumptions about content type. If the CloudEvent has a `datacontenttype` attribute, obviously, that should be used, but if there is no `content-type` header and no `ce-datacontenttype` header for the CE code to parse, then the CE data should simply be a `byte[]`.

**Comment by evanshortiss** [comment]
@matejvasek yes, that header in the Kafka payload does the trick. 

@lance I agree with this. It's a downstream issue, and Quarkus 2.x is taking the right approach by not making an assumption. Perhaps the error message could be improved and the Kafka Source doc could be improved?

**Comment by evanshortiss** [comment]
@matejvasek I'll close this issue. It seems like this was an improvement in Quarkus 2.x behaviour and my Funq worked due to an improper assumption made in the Quarkus 1.x implementation. 

I talked to a committer on the Knative project, and it sounds like adding a note to the Knative [about sources page](https://knative.dev/development/eventing/sources/) is a good idea. It can explain how sources infer the content-type/datacontenttype that will be passed to a sink service. This will probably provide enough information for developers without needing to dig into the spec/source.

**Comment by evanshortiss** [comment]
And thank you so much for your help with this BTW @matejvasek 🙏

**Comment by fjtirado** [comment]
> @matejvasek yes, that header in the Kafka payload does the trick.
> 
> @lance I agree with this. It's a downstream issue, and Quarkus 2.x is taking the right approach by not making an assumption. Perhaps the error message could be improved and the Kafka Source doc could be improved?

This is what the CE spec says about [datacontentype](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#datacontenttype) field 
_For some binary mode protocol bindings, this field is directly mapped to the respective protocol's content-type metadata property. Normative rules for the binary mode and the content-type metadata mapping can be found in the respective protocol.
In some event formats the datacontenttype attribute MAY be omitted. For example, if a JSON format event has no datacontenttype attribute, then it is implied that the data is a JSON value conforming to the "application/json" media type. In other words: a JSON-format event with no datacontenttype is exactly equivalent to one with datacontenttype="application/json".
When translating an event message with no datacontenttype attribute to a different format or protocol binding, the target datacontenttype SHOULD be set explicitly to the implied datacontenttype of the source._

Therefore I hardly any valid reason why https://github.com/quarkusio/quarkus/blob/main/extensions/funqy/funqy-knative-events/runtime/src/main/java/io/quarkus/funqy/runtime/bindings/knative/events/JsonCloudEventImpl.java#L178-L238 assume datacontentype is json and https://github.com/quarkusio/quarkus/blob/main/extensions/funqy/funqy-knative-events/runtime/src/main/java/io/quarkus/funqy/runtime/bindings/knative/events/HeaderCloudEventImpl.java#L168-L188 does not. The behaviour of binary and structured should be aligned on that regards and if datacontentype is null, assume its content type is the same one than the content type of the incoming request, in other words, json.

**Comment by ricardozanini** [comment]
@matejvasek ^

**Comment by matejvasek** [comment]
>Therefore I hardly any valid reason why...

I am confused.

The doc you are quoting says that you may assume json content type for structured json format.
For binary format we cannot cannot default. What would we default to?

**Comment by matejvasek** [comment]
In care you are decoding JSON structured event then payload is 99% JSON too. But for binary encoding we don't know unless Content-Type is set in HTTP header.

**Comment by matejvasek** [comment]
Of course you could have some heuristic that would look at body and guessed what it is.

**Comment by lance** [comment]
> The doc you are quoting says that you may assume json content type for structured json format.
> For binary format we cannot default. What would we default to?

**Comment by matejvasek** [comment]
If anything we should default to application/octet-stream for binary encoding.

**Comment by matejvasek** [comment]
>In case you are decoding JSON structured event then payload is 99% JSON too. 

In rare cases it could be blob encoded in b64 string.

**Comment by lance** [comment]
> the `datacontenttype` can be assumed based on the HTTP `contenttype` header.

My mistake - it is explicitly mapped to the `contenttype` header. I guess I'm not really sure what the question is here now...

**Comment by matejvasek** [comment]
@fjtirado could you send a patch to comment as what should be changed?
