### ISSUE TITLE
Including resource bundles for different languages doesn't work

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#22808]
### Describe the bug

When running the following code, there are differences between Native mode and JVM mode:

```java
Log.fatal(Locale.ITALY.getDisplayCountry(Locale.ENGLISH));
Log.fatal(Locale.ITALY.getDisplayCountry(Locale.GERMAN));
```

JVM mode output:

```
FATAL [] (executor-thread-1) Italy
FATAL [] (executor-thread-1) Italien
```

Native mode output:

```
FATAL [] (executor-thread-1) Italy
FATAL [] (executor-thread-1) Italy
```

The "LocaleNames" bundle was included via a resources-config.json file:

```json
{
  "bundles": [
    { "name": "sun.util.resources.LocaleNames" }
  ]
}
```

This JSON file was passed via the additional build arguments:

`quarkus.native.additional-build-args=-H:ResourceConfigurationFiles=resources-config.json,-H:+IncludeAllLocales,-H:DefaultLocale=en`

The language-specific Quarkus configurations have also been set:
```
quarkus.locales=en,de
quarkus.default-locale=en-US
quarkus.native.user-country=US
quarkus.native.user-language=en
```

### How to Reproduce?

Small reproducer example: https://github.com/andlinger/quarkus-native-locales

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.6.2.Final, 2.6.1.Final, 2.3.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          17.0.1 (GraalVM Community 17.0.1+12-jvmci-21.3-b05) OS:           Mac OS X 12.1 x86_64

**Comment by andlinger** [comment]
Is there anything I can do to help here?

**Comment by gsmet** [comment]
If you could assemble a small reproducer, that would be helpful.

**Comment by andlinger** [comment]
Here you go: https://github.com/andlinger/quarkus-native-locales

The [TranslationResource](https://github.com/andlinger/quarkus-native-locales/blob/main/quarkus/src/main/java/io/i15s/quarkus/TranslationResource.java) resource http://localhost:8080/translation returns the following in JVM mode:

```json
{
"en": "France",
"it": "Francia"
}
```

Result in native mode:
```json
{
"en": "France",
"it": "France"
}
```

**Comment by gsmet** [comment]
@zakkak @Karm could one of you have a look at the reproducer?

**Comment by Karm** [comment]
I will take a look as I have some Language setting test and this should be a part of it...

**Comment by Karm** [comment]
I think this is something we do in Quarkus with passing locale names. As you can see, a plain reproducer without Quarkus is sensitive to how locales are parsed:

```java
import java.util.Locale;
import java.util.logging.Logger;

public class Main {
    private static final Logger LOG = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) {
        System.out.printf("English: %s\n", Locale.FRANCE.getDisplayCountry(Locale.ENGLISH));
        System.out.printf("German: %s\n", Locale.FRANCE.getDisplayCountry(Locale.GERMAN));
        System.out.printf("Italian: %s\n", Locale.FRANCE.getDisplayCountry(Locale.ITALIAN));
    }
}
```

```bash
$ java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

```bash
$ native-image --version
native-image 21.3.0.0-Final Mandrel Distribution (Java Version 17.0.1+12)
```

# Good :heavy_check_mark: 

```
$ javac Main.java
$ native-image --no-fallback --initialize-at-build-time= -H:IncludeResourceBundles=sun.util.resources.LocaleNames -H:IncludeLocales=fr,en,it,de Main
$ ./main 
English: France
German: Frankreich
Italian: Francia

$ java Main
English: France
German: Frankreich
Italian: Francia

```

# Bad

```
$ native-image --no-fallback --initialize-at-build-time= -H:IncludeResourceBundles=sun.util.resources.LocaleNames -H:IncludeLocales=fr_FR,en_US,it_IT,de_DE Main
$ ./main 
English: France
German: France
Italian: France
```

I will take a look further and fix

**Comment by andlinger** [comment]
@Karm Any news on this? Is there anything I can help you with?

**Comment by Karm** [comment]
@andlinger No news. I shall circle back to it shortly and post an update :+1:

**Comment by Karm** [comment]
```
quarkus.native.auto-service-loader-registration=true
```
Registers LocaleData service loader providers and makes it work as expected. Yet it's a crude hammer. I would like to have something fine grained to just bake in those that are needed...so WIP.

**Comment by andlinger** [comment]
Thanks for the info. So there is currently no way to register specific service loaders manually?

**Comment by Karm** [comment]
@andlinger It is, programmatically, on the Quarkus side. Not via config/user app code to my best knowledge though. I will keep tinkering with it to have a such switch for Locales.
