### ISSUE TITLE
`SRCFG00020: Failed to convert value with static method` when setting log level to `OFF` via yaml

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#22817]
### Describe the bug

```yaml
quarkus:
  log:
    category:
      "io.quarkus.vertx.http.deployment.devmode.console.DevConsole":
        level: OFF
```
throws::
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: io.quarkus.runtime.configuration.ConfigurationException:
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00039: The config property quarkus.log.category."io.quarkus.vertx.http.deployment.devmode.console.DevConsole".level with the config value "false" threw an Exception whilst being converted SRCFG00020: Failed to convert value with static method
```
But the same as .properties works:
```
quarkus.log.category."io.quarkus.vertx.http.deployment.devmode.console.DevConsole".level=OFF
```

Setting other levels like `ERROR` works in YAML.

### Expected behavior

`OFF` can be used in yaml

### Actual behavior

exception is thrown

### How to Reproduce?

[q_loglevel-off.zip](https://github.com/quarkusio/quarkus/files/7849838/q_loglevel-off.zip)

`mvn clean verify` (or `quarkus:dev`).

### Quarkus version or git rev

2.6.2.Final

**Comment by radcortez** [comment]
The issue here is that the YAML specification automatically converts `OFF` to `false`, so when we read the value we get `false` which of course is not a valid value for the log level.

https://yaml.org/type/bool.html

You need to quote `"OFF"` so YAML does not convert it before it gets to us.

**Comment by geoand** [comment]
The joys of YAML...

**Comment by famod** [comment]
Ah, crap. I had this hunch about quoting just after I had filed this issue. 🤦‍♂️ 
Thanks for confirming @radcortez!
