### ISSUE TITLE
Add jitter to scheduler

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#22824]
### Description

It would be nice if the `@Scheduled` annotation also support setting a jitter. 

We have multiple instances running which are doing periodical tasks / checks. Adding a jitter would better distribute the load of the task randomly.

### Implementation ideas

It could be added to the `@Scheduled` annotation similar as it is done in the `@Retry` annotation.

**Comment by mkouba** [comment]
I must admit that I find the idea interesting. OTOH in most cases the goal of a scheduler method is to execute some logic at a specific time or at a specific interval ;-). Could you be a little more specific about the expected behavior? For example, what exactly should happen if you define `@Scheduled(every = "10s", jitter = "1000")`? Should it be executed somewhere between `interval - 1000ms` and `interval + 1000ms`?

CC @machi1990

**Comment by joggeli34** [comment]
For `@Scheduled(every = "10s", jitter = "1000")` there could be multiple solutions:
1. At create-time, an interval is fixed with `interval +- jitter`
2. For each new interval, the interval is adjusted to `interval +- jitter`
3. The interval is used for the base frequency, and each execution is adjusted by a jitter.

I think, 2. would be the simplest to describe. But actually, I don't mind exactly which one is implemented, as the interval time is not that important when someone decides to use a jitter.

**Comment by mkouba** [comment]
> 1. At create-time, an interval is fixed with interval +- jitter

Hm, this one would be probably the easiest to implement correctly, OTOH the option 2. would be more understandable... (and option 3 is functionally equivalent to option 2)

> `@Scheduled(every = "10s", jitter = "1000")`

Alternatively, we could support the jitter directly in the `@Scheduled#every()`, e.g. via the plus–minus sign: `@Scheduled(every = "10s ±1")`.

**Comment by mkouba** [comment]
Note that this could be difficult (if at all possible) to implement in `quarkus-quartz`.

**Comment by Felk** [comment]
I encountered this feature request today because we have multiple pods processing a queue of work units, and we want to minimize the chances of them trying to start the same unit of work.  
Such a jitter feature is thankfully easily emulated with e.g. this code at the beginn of the scheduled method:
```java
private static final Random random = new Random();
// ...
try {
    TimeUnit.MILLISECONDS.sleep(random.nextLong(jitter.toMillis()));
} catch (InterruptedException e) {
    return;
}
```

**Comment by mkouba** [comment]
> I encountered this feature request today because we have multiple pods processing a queue of work units, and we want to minimize the chances of them trying to start the same unit of work. Such a jitter feature is thankfully easily emulated with e.g. this code at the begin of the scheduled method:
> 
> ```java
> private static final Random random = new Random();
> // ...
> try {
>     TimeUnit.MILLISECONDS.sleep(random.nextLong(jitter.toMillis()));
> } catch (InterruptedException e) {
>     return;
> }
> ```

Keep in mind that this blocks the executor thread which is not always desirable...

**Comment by mkouba** [comment]
> I encountered this feature request today because we have multiple pods processing a queue of work units, and we want to minimize the chances of them trying to start the same unit of work.

Maybe a better solution would be to use config properties to slightly adjust the execution time for each pod. For example, something like `@Scheduled(cron = "${my.cron.expr:0 15 10 * * ?}")` where the `my.cron.expr` is the config property and `0 15 10 * * ?` is the default value - used for pod1. And then for example set ENV variables to adjust the cron expression like `MY_CRON_EXPR="0 20 10 * * ?"` for pod2 and `MY_CRON_EXPR="0 25 10 * * ?"` for pod3.

**Comment by mkouba** [comment]
Hm, I have one more idea. It's not ideal but it could work nicely. We could move the delay/jitter logic in a CDI interceptor. So instead of setting the jitter in the `@Scheduled` annotation it would be possible to add a special annotation to the scheduled method and the interceptor would delay the execution of the method.

```java
@Delayed(value = 100, jitter = 100) // Execution of the business method is delayed between 0-200ms
@Scheduled(every = "10s") 
void everyTenSeconds() {
  // ...
}
```

It should be fairly straightforward to implement.

@Ladicek maybe it would fit as a feature of SmallRye Fault Tolerance?

**Comment by Ladicek** [comment]
Yeah, there's a feature request for that already (see https://github.com/smallrye/smallrye-fault-tolerance/issues/253).

**Comment by mkouba** [comment]
> Yeah, there's a feature request for that already (see [smallrye/smallrye-fault-tolerance#253](https://github.com/smallrye/smallrye-fault-tolerance/issues/253)).

Hmm, created 4 years ago ;-). Do you think it would make sense to prototype something quarkus-specific first? (which I assume would be easier because of the integration with Vertx etc.)

**Comment by Ladicek** [comment]
To be honest, supporting jitter in the scheduler directly seems like a good idea -- too bad Quartz doesn't have that notion (didn't really check, just believing the comment above :-) ). Adding Fault Tolerance just for this seems ... a little excessive, perhaps?

**Comment by mkouba** [comment]
> To be honest, supporting jitter in the scheduler directly seems like a good idea -- too bad Quartz doesn't have that notion (didn't really check, just believing the comment above :-) ). Adding Fault Tolerance just for this seems ... a little excessive, perhaps?

Actually, we can use the same approach and overcome the limitation. I mean, we already have things like `io.quarkus.scheduler.common.runtime.SkipPredicateInvoker`  to implement `Scheduled#skipExecutionIf()`.

You're right. I will try to prototype something in the scheduler extension.
