### ISSUE TITLE
OIDC-Client: Response status 0 and null entity when OIDC client auth is failing for Rest-Client-Reactive

### ISSUE THREAD

**Issue by fwippe** [quarkusio/quarkus#22827]
### Describe the bug

When using OIDC client to authorize Rest-Client-Reactive endpoints, failing authorizations result in responses with status `0` and reason phrase `null`.

Note following code in `org.jboss.resteasy.reactive.client.handlers.ClientSetResponseEntityRestHandler#handle`:

```java
    public void handle(RestClientRequestContext context) throws Exception {
        ClientResponseContextImpl responseContext = new ClientResponseContextImpl(context);
        if (context.isCheckSuccessfulFamily()) {
            if (Response.Status.Family.familyOf(context.getResponseStatus()) != Response.Status.Family.SUCCESSFUL) {
                throw new WebClientApplicationException(context.getResponseStatus(), context.getResponseReasonPhrase());
            }
        }
        ClientRequestContextImpl requestContext = context.getClientRequestContext();
        // the spec doesn't really say this, but the TCK checks that the abortWith entity ends up read
        // so we have to write it, but without filters/interceptors
        if (requestContext != null && requestContext.getAbortedWith() != null) {
            setExistingEntity(requestContext.getAbortedWith(), responseContext, context);
        }
    }
```

When failing OIDC auth, `context.getResponseStatus()` is `0` so that `Response.Status.Family` is not `SUCCESSFUL`. Thus, a `WebClientApplicationException` with uninitialized parameters is thrown. On the other hand, the `requestContext.getAbortedWith()` is a response with status `401` and reason phrase `Unauthorized`. So that might be used instead?

Update: Reproducer: https://github.com/fwippe/issue-22827

### Expected behavior

Response status should be `401` or `403` with corresponding reason phrases.

### Actual behavior

Response status is `0` and reason phrase is `null`.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1415]

### Output of `java -version`

openjdk version "11.0.3" 2019-04-16 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by geoand** [comment]
Any chance you can put together a small project that exhibits the problematic behavior?

**Comment by fwippe** [comment]
> Any chance you can put together a small project that exhibits the problematic behavior?

Sure, no problem. I created repository https://github.com/fwippe/issue-22827. Run `./mvnw verify` to reproduce.
