### ISSUE TITLE
"Enlisted connection used without active transaction" during committing transactions with active async threads

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#22834]
### Describe the bug

Hi guys!
I've found out recently that not all of my transactions are committed. The small investigation led me to believe there is a problem in the commit transaction process: when some of the async processing is not finished yet using CompletableStage/CompletableFuture, the transaction fails with the message "Error trying to transactionCommit local transaction: Enlisted connection used without active transaction". 
I've attached a small reproducer for you with a simple test to check this behavior.

I know it's better to finish all async execution before committing the transaction. But there are cases when it's not under developer control. For example, in my project I have code like this:

```
@Transaction(REQUIRES_NEW)
public Optional<Integer> someMethod() {
	CompletableFuture<SomeResponse> timedResponse = new CompletableFuture<>();
        try {
            timedResponse = restClient.makeRequest().toCompletableFuture();
            SomeResponse response = timedResponse.get(TIMEOUT_CONST, MILLISECONDS);

            repository.persist(new Entity(response.getId));
            return Optional.of(response.getId());
        } catch (Exception ex) {
            try {
                // cancel rest request future if not completed yet
                timedResponse.cancel(true);
            } catch (Exception ignored) {}
            return Optional.empty();
        }
}
```

It's just some pseudo-code example of how hard it is to control async execution here.
And from time to time I receive 500 exception during rest request (that is OK and expected). But the problem is that there are cases when I receive a warning "commiting with 2 threads active!" and right after this exception "Enlisted connection used without active transaction".
Please see the reproducer.

### Expected behavior

The transaction is committed with a warning may be but without exception.

### Actual behavior

The transaction is not committed with warning and exception "Error trying to transactionCommit local transaction: Enlisted connection used without active transaction"

### How to Reproduce?

[transaction_commit_fail.zip](https://github.com/quarkusio/quarkus/files/7854468/transaction_commit_fail.zip)

1. Run TransactionCommitTest.test()
2. Check that transaction is not committed and there is an exception in logs

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.6.1.Final

**Comment by ahofmeister** [comment]
Got the same problem, but with the Emitter from smallrye-reactive-messaging-kafka

**Comment by lamemind-ud** [comment]
Same here.
I'm emitting some data with `smallrye-reactive-messaging-kafka` then I want to update the DB, but I can't.

I managed to write to the database using the `Event Bus`.
And even if my code is working, it throws anyway: `javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction`

Here is some example code...
~~~
@ApplicationScoped
public class KafkaProduceThenUpdate {

    @Inject
    @Channel("kafka-channel-out")
    Emitter<User> emitter;

    @Inject
    UserRepository userRepository;

    @Scheduled(every = "10s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
    @Transactional
    public void generate() {
        userRepository.getNextToSyncToKafka().ifPresent(user -> {
            System.out.println("Emitting User " + user);
            emitter.send(user).thenAccept(unused -> {
                bus.send("greeting", user);
            });
        });
    }

    @Inject
    EventBus bus;

    @ConsumeEvent(value = "greeting", blocking = true)
    @Transactional
    public void consume(User user) {
        userRepository.setSentToKafka(user);
    }
}
~~~

**Comment by ahofmeister** [comment]
@geoand  Hi Georgios, can you please ping the relevant person here? I am not sure who needs to be pinged here.

**Comment by geoand** [comment]
I am not sure what folks are actually describing here... 

Are you expecting that using `@Transactional` will work when doing async processing?

**Comment by lamemind-ud** [comment]
Hello @geoand , I don't know if this is a bug or a dev error. Maybe we're doing it wrong.
BTW we're stuck here and I cant' find any docs that explain how to do this the right way.

The starting point is: can't `emit` a kafka event in a `sync` way.

I tryed with panache reactive... but quarkus won't start (exception follows)
~~~
    @Scheduled(every = "1s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
    @Transactional
    public void generate() {
        sysOutboundEventRepository.getNextToSyncToCore()
                .ifPresent(sysOutboundEvent -> {
                    FrontendEvent event = this.createEvent(sysOutboundEvent);
                    emitter.send(event).thenAccept(unused -> {
                                Panache.withTransaction(() -> {
                                    sysOutboundEventRepository.setSentToKafka(sysOutboundEvent);
                                    return null;
                                });
                            });
                });
~~~

~~~
 javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManagerFactory and qualifiers [@Default]
        - java member: io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer#emf
        - declared on CLASS bean [types=[io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer]
        The following beans match by type, but none have matching qualifiers:
                - Bean [class=org.hibernate.SessionFactory, qualifiers=[@io.quarkus.hibernate.orm.PersistenceUnit(value = "frontend"), @Named(value = "frontend"), @Any]]
~~~

**Comment by lamemind-ud** [comment]
Is there a documentation with examples of how to go from reactive to imperative and vice versa?

**Comment by OleKsimov** [comment]
> Are you expecting that using `@Transactional` will work when doing async processing?

@geoand 
Well, I think if there are so many cases where it's not that easy (in my example, it's not possible at all) to control async thread execution, I would think about some parameter in @Transactional annotation to make it possible to commit changes despite active threads.

**Comment by geoand** [comment]
> Is there a documentation with examples of how to go from reactive to imperative and vice versa?

@cescoffier @Sanne since this seems to be a common issue, we might need some kind of blog post or actual documentation here on this...

**Comment by lamemind-ud** [comment]
> Hello @geoand , I don't know if this is a bug or a dev error. Maybe we're doing it wrong. BTW we're stuck here and I cant' find any docs that explain how to do this the right way.
> 
> My specific starting point is: can't `emit` a kafka event in a `sync` way.
> 
> I tryed with panache reactive... but quarkus won't start (exception follows)
> 
> ```
>     @Scheduled(every = "1s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
>     @Transactional
>     public void generate() {
>         sysOutboundEventRepository.getNextToSyncToCore()
>                 .ifPresent(sysOutboundEvent -> {
>                     FrontendEvent event = this.createEvent(sysOutboundEvent);
>                     emitter.send(event).thenAccept(unused -> {
>                                 Panache.withTransaction(() -> {
>                                     sysOutboundEventRepository.setSentToKafka(sysOutboundEvent);
>                                     return null;
>                                 });
>                             });
>                 });
> ```
> 
> ```
>  javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManagerFactory and qualifiers [@Default]
>         - java member: io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer#emf
>         - declared on CLASS bean [types=[io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer]
>         The following beans match by type, but none have matching qualifiers:
>                 - Bean [class=org.hibernate.SessionFactory, qualifiers=[@io.quarkus.hibernate.orm.PersistenceUnit(value = "frontend"), @Named(value = "frontend"), @Any]]
> ```

@geoand what about my exception with panache reactive? 
Should I open a new issue?

**Comment by geoand** [comment]
> @geoand what about my exception with panache reactive?
Should I open a new issue?

When using Hibernate Reactive, there is no `EntityManager` or `EntityManagerFactory`. You should be using `Mutiny.Session` and `Mutiny.SessionFactory` instead.
See the [documentation](https://quarkus.io/guides/hibernate-reactive) for more details.

**Comment by lamemind-ud** [comment]
> > @geoand what about my exception with panache reactive?
> > Should I open a new issue?
> 
> When using Hibernate Reactive, there is no `EntityManager` or `EntityManagerFactory`. You should be using `Mutiny.Session` and `Mutiny.SessionFactory` instead. See the [documentation](https://quarkus.io/guides/hibernate-reactive) for more details.

I didn't explain myself, my fault.
I'm going to open an issue.
Thanks

**Comment by cescoffier** [comment]
I believe this got fixed a long time ago. 

Also the kafka reference guide describe how to use hibernate classic and reactive (including transactions)

**Comment by geoand** [comment]
Let's close this issue then as `out of date`.

Feel free to comment / reopen if this is not the case.
