### ISSUE TITLE
Quarkus Upstream / Mutiny `collectItems()` has been removed

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22843]
### Describe the bug

As a result of [this commit](https://github.com/quarkusio/quarkus/commit/8243740c44f8bf8fc11c47c33bab8d679ed8f906) mutiny `collectItems()` has been removed. There are other breaking changes as you can see on [this Doc](https://github.com/smallrye/smallrye-mutiny/releases)

Please don't forget to attach all of this breaking changes to the future release note

**Comment by jponge** [comment]
This is documented, see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7#mutiny

These methods have been deprecated for more than a year.

**Comment by rsvoboda** [comment]
@jponge `collectItems` is not covered in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7#mutiny
