### ISSUE TITLE
snakeyaml not found in Gradle build after running Quarkus project with Maven

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#22842]
Okay, I have come across this issue before but never figured out how to replicate it (until now).

The issue seems to be that when a maven quarkus build runs, and pulls down `org.yaml:snakeyaml:1.29`, it is lacking something that the Gradle project needs. This poisons the `.m2` cache, causing the following error in the Gradle project:

```
Could not find snakeyaml-1.29-android.jar (org.yaml:snakeyaml:1.29).
Searched in the following locations:
    file:/home/gstewart/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29-android.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Simply nuking the snakyaml directory in `.m2` fixes it for the Gradle project, where it goes and gets its own copy, but the issue returns as soon as one runs the Maven Quarkus project, and the dependency is brought into `.m2` again.

I am assuming it's either something slightly off in config between maven and gradle iterations, and hopefully not something out of our control. I don't explicitly pull in the snakeyaml in either project, but do use the yaml properties plugin in my Gradle project.

**Comment by GregJohnStewart** [comment]
Important to note that the `snakeyaml-1.29-android.jar` seems to exist in `.m2`, even though Gradle says it cannot find it. Maybe there is a bad `sha` file for snakeyaml?

**Comment by glefloch** [comment]
That's really weird, the maven resolution looks good (it some case, the jar can be missing and gradle is not able to fallback to other repositories) 

Can you try to delete the `~/.m2/repository/org/yaml/snakeyaml/1.29/` directory from your repository and try to run the gradle command again? 

A better fix would be to change the order of `repositories` declared in your `build.gradle` file.
Gradle uses its own cache so unless you are referencing artifact build locally, you can avoid referencing the `mavenLocal()` repository.

**Comment by GregJohnStewart** [comment]
As I said, nuking the snakeyaml dir in `.m2` is my current fix, and swapping the order of `mavenLocal()` and `mavenCentral()` seems to have worked as well. Though I would say it is imperfect as there is still an issue with gradle pulling it from local, and it is nice having the cache to work offline (airplane/ travel work)

**Comment by glefloch** [comment]
Actually, you can use gradle offline without leveraging the `mavenLocal()` repository. If you need to run gradle offline and only rely on its cache you can use the `--offline` flag. And to make sure all dependencies are in the cache, you can run `./gradlew quarkusGoOffline`

**Comment by GregJohnStewart** [comment]
Good insight! I'll have to remember that, thanks.

**Comment by glefloch** [comment]
Your welcome ;). I will close the issue if everything is fine then.

**Comment by GregJohnStewart** [comment]
I wouldn't call this closed, there are valid workarounds but still feels like something is amiss. Leave it up to the maintainers I suppose though

**Comment by glefloch** [comment]
From the quarkus side, we can't do much more here. From my point of view, this is a Gradle issue. When dependency resolution failed, gradle could fallback to the next repository which it does not..
