### ISSUE TITLE
Rest Client exausts Threads. 

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#22862]
### Describe the bug

This is a major issue for us.
I have dozens of services in prod that from time to time they freeze due to thread exhaustion. The vertex event loop stalls. 
his can be traced back to unconfigured timeouts on rest clients that hog connections. 
We need to go to all rest clients and specify connection and read timeouts on configurations, like:
```
com.td.wfm.common.client.SomeRestClientClass/mp-rest/connectTimeout=500
com.td.wfm.common.client.SomeRestClientClass/mp-rest/readTimeout=1000
```
If you use programatic rest creation you must:
```
        return RestClientBuilder.newBuilder()
                                .baseUri(URI.create(uri))
                                .connectTimeout(connectionTimeout, TimeUnit.MILLISECONDS)
                                .readTimeout(readTimeout, TimeUnit.MILLISECONDS)
                                //...
```

There are many issues related with this. See:
https://github.com/quarkusio/quarkus/issues/15056
https://github.com/quarkusio/quarkus/issues/15383
https://github.com/quarkusio/quarkus/issues/15191

This happens on 1.13.7.Final but I believe 2.* suffers from the same problem.

### Expected behavior

If the REST Client connection is half closed in the other side, it will timeout after a default amount of time. 

### Actual behavior

If the REST Client connection is half closed in the other side it will never timeout.

### How to Reproduce?

You need a rest client calling an endpoint in a loop, in different threads. The other side must hold the connection and not reply. 

### Output of `java -version`

11

### Quarkus version or git rev

1.13.7.Final

**Comment by geoand** [comment]
I assume you are using `quarkus-rest-client`. Have you tried with `quarkus-rest-client-reactive`?

**Comment by TomasHofman** [comment]
I think I can add the same default timeouts that the reactive client uses as part of https://github.com/quarkusio/quarkus/issues/22872.

**Comment by radcortez** [comment]
I think it could be interesting to have a global timeout for REST clients (like we have other properties that set global configuration for clients).

**Comment by michalszynkiewicz** [comment]
that's a cool idea

**Comment by geoand** [comment]
> I think it could be interesting to have a global timeout for REST clients (like we have other properties that set global configuration for clients).

Definitely

**Comment by brunobat** [comment]
This is ok
