### ISSUE TITLE
Change type of rest client timeout properties to Duration

### ISSUE THREAD

**Issue by TomasHofman** [quarkusio/quarkus#22872]
### Description

Unlike most other "*-timeout" properties in Quarkus (you can filter them at https://quarkus.io/guides/all-config), the rest-client configuration has "read-timeout" and "connect-timeout" properties of type `long`. This should be changed to the `Duration` type to be consistent with other extensions.

```
quarkus.rest-client."config-key".connect-timeout
quarkus.rest-client."config-key".read-timeout
```

### Implementation ideas

We could also make the default values of the rest client timeout properties depend on some global timeout properties. See https://github.com/quarkusio/quarkus/issues/15191 or https://github.com/quarkusio/quarkus/issues/15056.

**Comment by TomasHofman** [comment]
I'm going to work on this, if the assignment looks all right.

**Comment by TomasHofman** [comment]
I realized there are some problems with this.

Firstly, the default `DurationConverter` assumes that if just a number is given, the duration is in seconds. The current semantic of the `connect-timeout` and `read-timeout` attributes is that the value is in milliseconds. Using the `DurationConverter` would therefore break backward compatibility, effectively changing existing configurations meaning from 1 second to 1000 seconds.

Secondly, the MP rest client spec says that the timeouts should be specified in milliseconds. That should be honored at least when the original MP configuration schema is used (`client-key/mp-rest/read-timeout=...`).

To stay backward compatible, I would need to use a different converter for these two fields fields (if that's possible), which would assume that the default unit is milliseconds. That would be inconsistent with all the other `Duration` type attributes where the default unit is seconds.

**Comment by TomasHofman** [comment]
I'm closing this for now, I don't see a way to do this without causing backward compatibility issues...

**Comment by YassinHajaj** [comment]
I agree with you @TomasHofman this is indeed a shame it derives from other implementations.

Can it be included in a breaking version release by any chance ? And be included in a migration guide for example ?
