### ISSUE TITLE
Cannot access web app running on WSL from a Windows-hosted client (browser)

### ISSUE THREAD

**Issue by brunoborges** [quarkusio/quarkus#22887]
### Describe the bug

Open a WSL terminal on Windows.
Create a sample app using the quickstart/archetypes.
Run `mvn quarkus:dev`.
Try to access the app.

### Expected behavior

Be able to see the expected output of the quickstart.

### Actual behavior

404

### How to Reproduce?

As described.

**Comment by geoand** [comment]
Thanks for reporting.

@rsvoboda do you have a Windows machine so you can verify this?

**Comment by rsvoboda** [comment]
I have Windows VM, but it's without nested virtualization so I can't really check WSL 2 now.

I will ask my wife to borrow me her Windows laptop when she gets home ;)

**Comment by geoand** [comment]
Thanks!

**Comment by rsvoboda** [comment]
Good news, I have managed to boot into Boot Camp based Windows with enabled Virtualization thanks to the trick mentioned in https://superuser.com/questions/717421/how-to-enable-hardware-virtualization-on-a-macbook

In WSL 2 I was able to run Quarkus sample app from code.quarkus in dev mode. Application is not accessible from Windows-hosted browser because the default host is localhost / 127.0.0.1 and wsl acts as fast VM.

Running Maven command with `-Dquarkus.http.host=0.0.0.0` solves the trouble and I can access the app from browser.

<img width="854" alt="Capture" src="https://user-images.githubusercontent.com/925259/149518054-bdffaa13-092b-489a-b84e-38f4371d9d4b.PNG">

**Comment by geoand** [comment]
Thanks @rsvoboda!

Interesting how this seems to be the opposite of https://github.com/quarkusio/quarkus/issues/12246...

**Comment by famod** [comment]
`0.0.0.0` is the way to go when running in a WSL2 distribution, using it myself that way.

The other issue seems to be about running "natively" on Windows, not in WSL2.

**Comment by brunoborges** [comment]
@famod have you tried with this setting as a Maven property in the Pom?

**Comment by famod** [comment]
@brunoborges we have it in `application-dev.yaml`. It was a team decision that it's ok for everyone all like that, even though only I am using WSL, the others are running on Windows natively.

But you should be able to set it via Maven, too.

**Comment by brunoborges** [comment]
I think I tried to set it via Maven in the pom, and did not see success. That's why I'm asking you to test as well.

Granted, my project was an older Quarkus, that then I manually updated to the latest version. So maybe I missed something.

**Comment by famod** [comment]
Right, just setting property `<quarkus.http.host>0.0.0.0</quarkus.http.host>` doesn't work, haven't checked why.

But you can either set property `<jvm.args>-Dquarkus.http.host=0.0.0.0</jvm.args>` or set `<jvmArgs>-Dquarkus.http.host=0.0.0.0</jvmArgs>` in the configuration section of the `quarkus-maven-plugin`.

**Comment by brunoborges** [comment]
Isn't this because the Maven plugin is not passing along Maven properties to Quarkus as system properties?

This sounds like a quite useful enhancement.

**Comment by geoand** [comment]
Quarkus does read properties from Maven, however it only applies them to build time configuration, i.e. configuration that cannot change at runtime - which is not the case for `quarkus.http.host`.

**Comment by famod** [comment]
Ah, right! ⬆️ 👍 

So it seems we should close this issue.
Or can we improve something on the documentation side of things?

**Comment by geoand** [comment]
> Or can we improve something on the documentation side of things?

Yeah, I think we can likely improve on that. Or maybe even try to detect if we are running in WSL (not sure that's possible) and display a warning message if `quarkus.http.host` is set to `localhost`?

**Comment by famod** [comment]
Not sure if a warning is too invasive. Nobody stops you from running a desktop in WSL, with a browser.
So if we choose to log something it should be INFO instead.

But logging is actually better than extending the docs, RTFM you know. 😉

**Comment by brunoborges** [comment]
Isn't it better if you just go with the expected behavior of the developer?

If the setting is in the pom, use it. If it is inside WSL, deploy to 0.0.0.0 by default. Document the default behavior.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22956 makes Quarkus automatically lister on `0.0.0.0` for WSL environments. 
@rsvoboda would you be able to test it please?

Thanks

**Comment by famod** [comment]
IIRC, a long time ago there was a change to not bind to 0.0.0.0 because of security reasons?
Anyway, I think it's alright to use it by default like that.

**Comment by geoand** [comment]
Yeah, this is only for WSL

**Comment by rsvoboda** [comment]
ok, booting to windows

**Comment by rsvoboda** [comment]
PR approved, fresh Quarkus build on Windows machine took ages :/

**Comment by geoand** [comment]
Thanks!

**Comment by famod** [comment]
> fresh Quarkus build on Windows machine took ages :/

Better build in WSL dist whenever you can.

**Comment by rsvoboda** [comment]
> Better build in WSL dist whenever you can.

I had my Windows machine with almost nothing in `.m2/repository/` so the download of artifacts took quite a long time.
And I was building in Windows, but I realized that the local maven repo is different in WSL and I miss `999-SNAPSHOT` artifacts :) I got through that using `-Dmaven.repo.local=`. Yeah, it can be tricky to switch between Windows cmd/powershell and WSL ...

**Comment by brunoborges** [comment]
Any tip on how to configure `<quarkus.http.host>0.0.0.0</quarkus.http.host>` in the `pom.xml`? Maybe in the quarkus plugin?

**Comment by geoand** [comment]
Something like:

```xml
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                     <systemProperties>
                        <quarkus.http.host>0.0.0.0</quarkus.http.host>
                     </systemProperties>
               </configuration>
            </plugin>
```

should work, although I haven't tried it

**Comment by famod** [comment]
Or like I have posted 2 days ago: https://github.com/quarkusio/quarkus/issues/22887#issuecomment-1013920452
