### ISSUE TITLE
Propagate OTel Context to Reactive Messaging

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#22906]
### Description

Reactive Messaging requires the OTel context to be set manually. This should be done automatically.

### Implementation ideas

Requires https://github.com/smallrye/smallrye-reactive-messaging/issues/1784

**Comment by radcortez** [comment]
I can work on this.

**Comment by pilhuhn** [comment]
Any update? Right now (2.11), incoming traces into a `@Incoming` method are just dropped. They should be used as parent Span on the same trace. Bonus points for easy forwarding that into an outgoing message via `@Channel bla Emitter emitter`.

**Comment by radcortez** [comment]
No update. We need to do some work on RM to support OTel transparently.

Right now, you can do it manually like this:

```java
// for emitter
Message.of(OBJECT, Metadata.of(TracingMetadata.withCurrent(Context.current())))
// on message
 message.getMetadata(TracingMetadata.class).ifPresent(metadata -> QuarkusContextStorage.INSTANCE.attach(metadata.getCurrentContext()));
```

**Comment by cescoffier** [comment]
PRobably time to revisit this issue with the recent work from @ozangunalp in reactive messaging.

**Comment by radcortez** [comment]
Yes, I believe that https://github.com/smallrye/smallrye-reactive-messaging/pull/1678 takes care of this.
