### ISSUE TITLE
Support OTel JDBC Driver in DevServices

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#22905]
### Description

We are not able to set the OTel JDBC Driver for DevServices, because it requires the specific prefix `jdbc:otel:` and we have the prefix for DevServices hardcoded.

**Comment by knutwannheden** [comment]
@radcortez This is interesting. Would it possibly make sense to add an explicit config property to control this? Something like `quarkus.opentelemetry.instrumentation.jdbc-datasource.enabled`? The extension could then also automatically configure the OpenTelemetry JDBC driver based on this, rather than requiring the developer to do that. What do you think?

**Comment by radcortez** [comment]
Hum, not totally sure how useful that would be.

Right now, (and forgetting about dev services), to configure the JDBC datasource with OTel we need to:
1. Add the `opentelemetry-jdbc` dependency (which contains the driver)
2. Set the `quarkus.datasource.jdbc.driver=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver`
3. Add the `otel` prefix in the JDBC url: `quarkus.datasource.jdbc.url=jdbc:otel:...`

Looking into all of these:

1. We don't want to force adding de dependency in the OTel extension if you don't need it. and we are not going to be able to control that with a configuration.
2. We could automatically set the driver based on a configuration, but I don't see much difference in having a flag.
3. If you have the driver set, the driver will fail the application if it doesn't find the `otel` prefix in the url. The url is already something that the user needs to set.

With a configuration, we are saving the user from setting the driver and fixing the url. On the other hand, we usually don't explicitly override user configuration (or change it in any way), which we would have to do in thise case.

Coming back to this PR and the DevServices, the JDBC url is not in the user control, since it is generated by TestContainers or by the Embedded flavors. In this case, we had no other alternative, because if the user sets its own url, DevServices will not come into play and we just use whatever url was provided by the user.

Did you have something different in mind?

**Comment by knutwannheden** [comment]
I think what you say makes sense. Since the URL must be explicitly set (for production), the user may as well set the driver.
