### ISSUE TITLE
CLI cannot remove registry from the list

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#22911]
### Describe the bug

Registries added to cli cannot be removed

### Expected behavior

Attempts to remove registries from config should be successfull

### Actual behavior

Attempt to remove a registry from the list leads to error `Can only remove registries from an existing configuration. The specified config file does not exist: null`

### How to Reproduce?

1.  `quarkus registry add quarkus.example.com`
2. Check the list:
``` 
$ quarkus registry
Configured Quarkus extension registries:
registry.quarkus.io
quarkus.example.com
(Config source: file: ~/.quarkus/config.yaml)
```
2. `$ quarkus registry remove quarkus.example.com`

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.15.6-100.fc34.x86_64"

### Output of `java -version`

11.0.13, vendor: Eclipse Adoptium

### Quarkus version or git rev

2.6.2.Final

**Comment by ebullient** [comment]
The message is bad, but you're removing a registry that isn't present in the file? 

registry.example.com isn't in the file. A registry that exists in the file, e.g.  quarkus.example.com should be removed.

**Comment by fedinskiy** [comment]
@ebullient I beg your pardon for an error in the reproducer( it's fixed now). To clarify: I cannot remove the registry that *is* present in the file.

On the other hand, it looks like the error is the same for existing and non-existing entries.

**Comment by ebullient** [comment]
Thanks for clarifying
