### ISSUE TITLE
Simplify exception handling for REST Client

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#22936]
### Description

Currently the way the to handle exception in REST Client is to register a Provider that implements `ResponseExceptionMapper`.

Although this is very powerful when a user needs to use CDI dependencies for example, it's overly tedious for simple cases where we simply want to throw some sort of exception based on the response.

An idea would be to introduce an annotation named `@ClientExceptionMapper` that could be placed on `default` methods of the REST Client interface, something like:

```java
    @RegisterRestClient(configKey = "client")
    @Path("/reactive")
    interface ReactiveRestClient {
        @GET
        String helloGet(@QueryParam("name") String name);
 
        @ClientExceptionMapper 
        default RuntimeException toException(Response response) {
            // create exception
        }
    }
```

**Comment by michalszynkiewicz** [comment]
Nothing in the spec I'm aware of. As I wrote on the chat, my first impression on the idea is very good :)

**Comment by FroMage** [comment]
Looks interesting.

- What's the point of returning the exception type? Something is going to throw it, no? So why not just throw it?
- Contrary to the server `ExceptionMapper` which has a sort of "filter" in the form of the exception type it maps, a bit like `catch` in Java, these ones are all going to be completely generic because they map a `Response` which has no subtypes. I suppose it could be useful to map some responses to different exceptions based on the response, so how do we compose them?
- I suppose that there might be a standard set of response mappers that turn things like 401 to `NotAuthorizedException` or 404 to `NotFoundException` (which are server exception types, so horrible horrible idea, but I do wonder if the spec doesn't sort-of force us to do something like that, JAX-RS or MP REST, we should check) so can we retrofit them?
- Do we need some sort of annotation such as:
```java
@ClientExceptionMapper 
        default RuntimeException toException(@WithStatus(466) Response response) {
            // create exception
        }
```
- Or do we go for this sort of composition:
```java
@ClientExceptionMapper 
        default RuntimeException toException(Response response) {
            if(response.status == 466)
              return new XX();
            return null; // invoke other mappers
        }
```

**Comment by geoand** [comment]
> What's the point of returning the exception type? Something is going to throw it, no? So why not just throw it?

Right, I was wondering the same, but I think returning allows for more flexibility like you have in your example.

> Or do we go for this sort of composition:

I think this second option makes more sense

**Comment by FroMage** [comment]
> Right, I was wondering the same, but I think returning allows for more flexibility like you have in your example.

Well, you could write it as such too:

```java
@ClientExceptionMapper 
        default void toException(Response response) {
            if(response.status == 466)
              throw new XX();
            // invoke other mappers
        }
```

> I think this second option makes more sense

Yeah, we can definitely start with chaining them depending on their outcome (return or throw, whatever). And extend it later if need be.

**Comment by geoand** [comment]
> We also need to determine which mechanism has priority in the case you have a global exception mapper.

I can think of two ways to deal with this. 

1. We make it a build time error.
2. We add a `priority` field to `@ClientExceptionMapper`  which will then be used to determine the proper exception mapper using the normal semantics.

WDYT?

**Comment by geoand** [comment]
Also I just thought of something else:

Does not not make sense to make the method a `static` method on the interface instead of a default method? So something like:

```java
    @RegisterRestClient(configKey = "client")
    @Path("/reactive")
    interface ReactiveRestClient {
        @GET
        String helloGet(@QueryParam("name") String name);
 
        @ClientExceptionMapper 
        static RuntimeException toException(Response response) {
            // create exception
        }
    }
```

**Comment by radcortez** [comment]
> 2. We add a `priority` field to `@ClientExceptionMapper`  which will then be used to determine the proper exception mapper using the normal semantics.

Probably use the priority, since it is already used with providers, so it is consistent.

> Does not not make sense to make the method a `static` method on the interface instead of a default method? So something like:

Maybe a `static` method could offer additional flexibility if you want to call it directly for some reason.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22965 should take care of it.
