### ISSUE TITLE
Dev UI - add a page that lists all dev services with all important details

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#22943]
### Description

A typical example could be a _connection information_ for the DB instance, e.g. host, port, username, password and dbname for a postgresql instance.

**Comment by Ladicek** [comment]
I can see that, for example, for a database, it would list separate host and port, username, password, database name, and it would also show a JDBC URL. Bonus points for showing directly how to invoke `psql`. I guess the same would be possible for all databases.

For other kinds of dev services, similar thing should be possible. Show the base information (host and port, username/password if applicable) and relevant immediately-usable things (e.g. for Apicurio Registry, it could show a URL/link to the registry UI).

**Comment by bulldog98** [comment]
This is in Quarkus 3, at least should this issue be closed?
