### ISSUE TITLE
BootstrapAppModelResolver assumes that Maven packaging === extension

### ISSUE THREAD

**Issue by evacchi** [quarkusio/quarkus#2294]
Reproducer: https://github.com/evacchi/quarkus-maven-packaging-bug

Our Maven plugin uses the custom packaging type `kjar` and we're getting this error for `mvn compile quarkus:dev`

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.1:dev (default-cli) on project drools-quarkus-example: Failed to run: Failed to resolve Quarkus application model: Failed to resolve dependencies for org.submarine:drools-quarkus-example:kjar:8.0.0-SNAPSHOT: Could not find artifact org.submarine:drools-quarkus-example:kjar:8.0.0-SNAPSHOT -> [Help 1]
```

the error goes away if I `mvn install` the project before I `mvn quarkus:dev` which I assume is unexpected. 

I have narrowed the reason [to this line in BootstrapAppModelResolver](https://github.com/quarkusio/quarkus/blob/fcbc40ba189656748ed9ab83658155ee57da4100/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/BootstrapAppModelResolver.java#L255) which seems to assume that `kjar` is not only the packaging type but also the file extension.

Packaging in our case only affects lifecycle but does not affect the file extension, which is still `jar`; in fact, the two properties are [separate in the Maven data structure](https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/handler/ArtifactHandler.java#L40-L51), and the Maven documentation describes [a few cases in the default artifact handlers when the two don't necessarily match](https://maven.apache.org/ref/3.6.1/maven-core/artifact-handlers.html)

This is currently not a real blocker to us (we are working around it somehow), but it might be a problem in the future, and it should at least be documented somewhere (the error message might be improved, for instance).

**Comment by aloubyansky** [comment]
This appears to be working in current master. I mean the launch of course fails, given there is nothing to launch but the original issue appears to be fixed. Could you please try again?

**Comment by aloubyansky** [comment]
The general issue though about relying on the packing is still not fixed. My comment was about your reproducer.

**Comment by evacchi** [comment]
ok I will check again and get back to you ASAP

**Comment by aloubyansky** [comment]
Yes, the fix was a side effect of adding more dep scopes (such as `provided`) to the dev mode classpath. The dep resolution is performed differently in this case, i.e. the root artifact (which is the app artifact) is not added as a root dependency but simply as a root artifact to the dep collection request and is not resolved (unless you are familiar with the Maven resolver API that might not make sense as an explanation).
Anyway, while that appears to "fix" the dev mode, the issue would still show up during the usual build.
I'm going to open a PR with the fix in a bit.

**Comment by gsmet** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/2391 .
