### ISSUE TITLE
Zero down time/rolling updates with Quarkus

### ISSUE THREAD

**Issue by iabughosh** [quarkusio/quarkus#22948]
### Describe the bug

I have a service which runs on Quarkus 2.6.0.Final. My goal here is to achieve zero down time deployment using rolling update strategy. My service has CORS filter and micro-profile health plugin enabled and when I update my deployment image to a newer version while there is an active user, browser logs give the below message :

    "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at xxx. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503."

while xxx is my service endpoint.

My conclusion here is that q/health/ready endpoint return 200 while CORS setup & filter for that service is not started yet!

### Expected behavior

To accept traffic after CORS filter before health/ready returns 200

### Actual behavior

It accept traffic before CORS filter initiation is completed.

### How to Reproduce?

Steps : 

- Have 2 instances running of the service
- Have a xhr/web load generator hitting your service API
- Update image with new version using rolling update strategy

### Output of `uname -a` or `ver`

inux pop-os 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS

### GraalVM version (if different from Java)

NA

### Quarkus version or git rev

2.6.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by gsmet** [comment]
@sberyozkin could you have a look at that one? I'm not sure if CORS actually requires some setup but probably worth at least checking what could be going on.

**Comment by michalvavrik** [comment]
@iabughosh I wonder if you experience same issues with let say 2.16? Please test it. If you provide a reproducer, I'll have a look. I realize that having `load generator hitting your service` and `update image...` might be hard to simulate, but at least provide quarkus app> I take it you run it in OpenShift? Then you can also provide details about your set up and template used to deploy application. You can ping me via GChat.

**Comment by michalvavrik** [comment]
Hey @iabughosh , I can't reproduce it like that. You didn't provide any information about your dependencies and didn't react on my question. I believe we should not spend time on this provide more info.

Please feel free to re-open it with reproducer. It need not to fail, I can assemble requests etc. but we need to have endpoints to call and deps.
