### ISSUE TITLE
Unable to marshall request to JSON

### ISSUE THREAD

**Issue by cpsinghal** [quarkusio/quarkus#22958]
### Describe the bug

Quarkus 2.6.x quarkus-amazon-* extension brining software.amazon.awssdk 2.17.100 version, 
that is throwing 
`software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: Can not write a field name, expecting a value
`
brining down software.amazon.awssdk:aws-json-protocol version to lower seems to fix the issue
```
<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-json-protocol</artifactId>
            <version>2.17.81</version>
        </dependency>
```

some other developers of aws-sdk also confirmed that there is an issue in the 2.17.100 version
https://github.com/aws/aws-sdk-java-v2/issues/2875

### Expected behavior

There should not be any error

### Actual behavior

latest version is throwing error
`software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: Can not write a field name, expecting a value
`

### Quarkus version or git rev

2.6.2

**Comment by geoand** [comment]
This is not a Quarkus issue, so I'll close it
