### ISSUE TITLE
io.vertx.core.http.HttpServerRequest.HttpServerRequest not initialized if called after a @RestClient invocation

### ISSUE THREAD

**Issue by agelbess** [quarkusio/quarkus#22959]
### Describe the bug

A exception is thrown if the HttpServerRequest is called after the @RestClient invocation.

javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCu
rrent()

https://github.com/agelbess/quarkus-bug-http-headers

### Expected behavior

Should not be thrown

### Actual behavior

A exception is thrown if the HttpServerRequest is called after the @RestClient invocation.

### How to Reproduce?

https://github.com/agelbess/quarkus-bug-http-headers

Clone and run the tests.

More info in the https://github.com/agelbess/quarkus-bug-http-headers#readme

**Comment by geoand** [comment]
This is actually a very interesting use case, but I am not sure I'd classify it as a bug...

What happens here is that because your whole pipeline is reactive, the Uni chain is being processed outside of the boundaries where the request scope is active.

You basically need to rewrite your `MyBuggyService` like so:

```java
@ApplicationScoped
public class MyBuggyService {

    WwwClient wwwClient;
    HttpServerRequest httpServerRequest;

    public MyBuggyService(@RestClient WwwClient wwwClient, HttpServerRequest httpServerRequest) {
        this.wwwClient = wwwClient;
        this.httpServerRequest = httpServerRequest;
    }

    public Uni<String> get() {
        String buggy = httpServerRequest.getHeader("buggy");
        return wwwClient.get().attachContext()
                .map(s -> buggy + ' ' + s);
    }
}
```

**Comment by agelbess** [comment]
Thanks George for taking the time to take a look.
As you said, changing the order of the method invocations (first the httpServerRequest.getHeader and then the wwwClient.get) solves the issue, but still, there should be a way to inform the developer (pre-execution) that what she is doing will produce errors.
One way or another, we are aware of the issue and know how to handle it.
BTW, is there a solution in Quarkus like https://github.com/jhipster/prettier-java ?
I guess that a rule could be added for such cases...food for thought.

**Comment by geoand** [comment]
> but still, there should be a way to inform the developer (pre-execution) that what she is doing will produce errors.

Ideally yes, but this would require scanning the bytecode of method implementations, which is something we have purposly stayed away from, as it's extremely error prone and performance heavy...

> BTW, is there a solution in Quarkus like https://github.com/jhipster/prettier-java ?

I have no idea what that does TBH
