### ISSUE TITLE
Hibernate Reactive: Fails creating an entity with ManyToOne relationship and optional = false

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#22966]
### Describe the bug

Having the next entity:

```java
@Entity
public class Parent extends PanacheEntity {

    public String name;

    @ManyToOne(optional = false)
    public Child child;
}
```

And:

```java
@Entity
public class Child extends PanacheEntityBase {

    @Id
    public String id;

    public String name;

    @OneToMany(mappedBy = "child")
    public List<Parent> parents = new LinkedList<>();
}
```

Given these entities already stored in database:

```
insert into child(id, name) values ('id', 'full collection');
```

When trying to update a parent entity with Hibernate reactive, for example, using a REST endpoint:

```java
@POST
    @Produces("application/json")
    public Uni<Parent> add() {
        Parent item = new Parent();
        item.name = "My Test";
        item.child = new Child();
        item.child.id = "id";
        return item.persist();
    }
```

The above fails with `java.lang.UnsupportedOperationException: reactive persistence context`.

After digging into this issue, I found that the problem is related to the `optional = false`, if I use:

```java
@Entity
public class Parent extends PanacheEntity {

    public String name;

    @ManyToOne // optional is true by default
    public Child child;
}
```

The above works ok.

Also, note that this is working fine (with optional is false) when using Hibernate classic.

**Comment by gavinking** [comment]
@DavideD This is quite likely to be a bug in Hibernate Reactive, we need to open an issue, and try to reproduce it without Quarkus or Panache.

**Comment by DavideD** [comment]
Yes, it is the same bug: https://github.com/hibernate/hibernate-reactive/issues/1077

**Comment by gavinking** [comment]
Ahah! OK, good.

**Comment by codespearhead** [comment]
@Sgitario The [upstream issue](https://github.com/hibernate/hibernate-reactive/issues/1077) mentioned by @DavideD seems to have been closed. Should this issue be closed as well?

**Comment by Sgitario** [comment]
Yeah, thanks both @DavideD @codespearhead !
