### ISSUE TITLE
AMQP Dev Services - Add the option to use other compatible images

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/quarkus#22976]
### Description

Currently, only the artemiscloud images are available to deploy the amqp broker container image. However, other compatible images like Red Hat AMQ Broker (based on ActiveMQ Artemis) can be used for dev purposes. But, there if you set this image name, you get an error that is not supported. 

### Implementation ideas

If I understand correctly, the container images valid for dev services are hardcoded into the AMQP service, it can be externalized or the RH images can be added to that list.

**Comment by cescoffier** [comment]
@hguerrero is the other image really compatible? (very same command to start and file structure)

**Comment by cescoffier** [comment]
@hguerrero Ping.

**Comment by hguerrero** [comment]
@cescoffier what is the current command?

**Comment by cescoffier** [comment]
@hguerrero See https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-reactive-messaging-amqp/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/amqp/deployment/AmqpDevServicesProcessor.java#L294-L305. It's just a few env variables.

**Comment by hguerrero** [comment]
Yes, I can confirm those values work.

I just noticed that the console is not exposed (based on the code you share) besides that, it should work.

**Comment by cescoffier** [comment]
Do we need to expose the console?

BTW do you have the coordinate of the image you want to use?

**Comment by garethahealy** [comment]
Any update on this? I'd like to use the downstream image with customers, i.e.:

```
quarkus.amqp.devservices.image-name=registry.redhat.io/amq7/amq-broker-rhel8:7.11.0
```

gahealy@rh

**Comment by cescoffier** [comment]
@garethahealy Sorry, I missed your update. I'm going to add this issue to the roadmap.
