### ISSUE TITLE
warning about missing json when just using resteasy or resteasy-reactive

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#22970]
### Describe the bug

when just using resteasy or resteasy-classic you should get a warning  that you are missing json support according to this code:

https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L220

But I get nothing. neither when using maven,gradle or jbang.

Attached is a resteasy classic reproducer. if change it to use resteasy-jackson I get json, but without it I get string and not warning.

[resteasy.zip](https://github.com/quarkusio/quarkus/files/7889504/resteasy.zip)

### Expected behavior

print during build of missing json provider.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/22980 introduces the warning for RESTEasy Reactive
