### ISSUE TITLE
[Flyway] Option to configure flyway.batch

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus#22985]
### Description

See https://flywaydb.org/documentation/configuration/parameters/batch, https://quarkus.io/guides/all-config does not seem to list this option.

**Comment by gsmet** [comment]
@coiouhkc looks like a good opportunity to make your first PR. You have an example here: https://github.com/quarkusio/quarkus/pull/22957 .

**Comment by gastaldi** [comment]
Bonus points if you could also provide a test case with this new feature 😉

**Comment by coiouhkc** [comment]
> Bonus points if you could also provide a test case with this new feature 😉

You're a funny guy, mr. @gastaldi (https://memegenerator.net/instance/61977554/goodfellas-laugh-youre-a-funny-guy) :D

**Comment by coiouhkc** [comment]
https://github.com/quarkusio/quarkus/pull/22986

**Comment by gastaldi** [comment]
It looks good. About the test, I was referring to something like it was done in https://github.com/quarkusio/quarkus/commit/180e018b3a3ba1d47c66135ecc0c2f7a07853c20

**Comment by coiouhkc** [comment]
> It looks good. About the test, I was referring to something like it was done in [180e018](https://github.com/quarkusio/quarkus/commit/180e018b3a3ba1d47c66135ecc0c2f7a07853c20)

Ok, let me check. I was thinking you're requesting to test the batch feature ;)

**Comment by gastaldi** [comment]
> Ok, let me check. I was thinking you're requesting to test the batch feature ;)

Sorry for the confusion :) This is just to make sure that the code you wrote (although trivial) is test-covered 👍🏻

**Comment by gastaldi** [comment]
Oh-oh, it seems like this is a Flyway Teams only feature, which is not supported in the Quarkus Extension: https://flywaydb.org/documentation/configuration/parameters/batch

**Comment by coiouhkc** [comment]
Oops, you're right.. :(

**Comment by coiouhkc** [comment]
Let's close it then.

**Comment by gastaldi** [comment]
Closing as the Quarkus extension does not support Flyway Team
