### ISSUE TITLE
Investigate cost of new GraalVM policy: static block run at runtime instead of build time init

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2298]
- [x] Make 19 run on Quarkus
- [x] Evaluate the cost of these blocks slipping from build time to run time
- [x] Make our main block (generated by Quarkus) a build time strategy
- [x] Optionally allow extensions to define that they are build safe except specific static

We need to define our default strategy for extensions: is extensions expected to be all build time except.

@dmlloyd I assign you as per @n1hility 's request

**Comment by dmlloyd** [comment]
Awesome 🎉

**Comment by dmlloyd** [comment]
Evaluated as part of the Graal 19 project work.  We're sticking with build-time initialization by default to favor performance.  So far so good...
