### ISSUE TITLE
Project generation - Index page - Extension list incomplete

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#22981]
### Description

In https://github.com/quarkusio/quarkus/pull/21233/files, we stumbled upon the fact that only extensions with Codestarts were somehow listed.

Typically, when you add `-Dextensions="resteasy,resteasy-jackson,hibernate-validator"`, you only get `RESTEasy JAX-RS` listed.

It's a bit of a shame because the links to the guides could be interesting, even if there's no codestart provided.

Let's talk with @ia3andy when he's back.

**Comment by ia3andy** [comment]
yeah it's weird, good catch @gsmet I will have a look

**Comment by ia3andy** [comment]
I've found the problem, I am working on the PR
