### ISSUE TITLE
Extension author guide: explain how to deal with `META-INF/services` files

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2299]
https://quarkus.io/guides/extension-authors-guide#register-resources-for-use-in-native-image led me to believe I only needed to register the file, but actually I need to call `ServiceUtil` to register the contents of the file for reflection, at the very least.

**Comment by gsmet** [comment]
@FroMage care to provide a PR? It would be nice to close all these issues that are fixable in one hour instead of having them piling up.

Thanks.

**Comment by FroMage** [comment]
> It would be nice to close all these issues that are fixable in one hour instead of having them piling up.

Famous Last Words: it's been days and no resolution in sight :(

**Comment by FroMage** [comment]
Follow up at https://github.com/quarkusio/quarkus/pull/5582
