### ISSUE TITLE
ScramLoginModule failed when using env vars

### ISSUE THREAD

**Issue by celsomarques** [quarkusio/quarkus#22991]
### Describe the bug

When you use **ScramLoginModule** you get the following error:

```
IllegalArgumentException: Value not specified for key ' password=' in JAAS config
at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig:116)
```

config:

```
%prod.mp.messaging.connector.smallrye-kafka.security.protocol=SASL_SSL
%prod.mp.messaging.connector.smallrye-kafka.sasl.mechanism=SCRAM-SHA-512
%prod.mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
```

ENV:

```
KAFKA_USERNAME: alice
KAFKA_PASSWORD: alice-secret
```

I tried different ways in order to get value setted properly inside app, as follows:

```
username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\"
username="${kafka.username}" password="${kafka.password}"
```

Using PlainLoginModule env vars was set properly as expected.

I tried to create Kafka cluster with SASL_SSL to made your life easy to reproduce this issue but I was not able to do that.
I got this error in Amazon MSK.

Dockerfile

```
## Stage 1: build native sources
FROM gradle:7.3-jdk11 AS gradle-build
USER root
COPY build.gradle /code/
COPY settings.gradle /code/
COPY gradle.properties /code/

WORKDIR /code
COPY src /code/src

RUN gradle clean build


FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:1.10

USER root
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 --from=gradle-build /code/build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 --from=gradle-build /code/build/quarkus-app/*.jar /deployments/
COPY --chown=185 --from=gradle-build /code/build/quarkus-app/app/ /deployments/app/
COPY --chown=185 --from=gradle-build /code/build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT [ "java", "-jar", "/deployments/quarkus-run.jar" ]
```

### Output of `java -version`

openjdk-11-runtime:1.10

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.3-jdk11

**Comment by cescoffier** [comment]
Sounds like a substitution issue. Adding @radcortez.

**Comment by radcortez** [comment]
Hi @celsomarques, can you please provide a reproducer? Thank you!

**Comment by celsomarques** [comment]
Hi @radcortez, sorry for my late response but I was trying to create a repository with Kafka (Scram SSL). However I was not able to do it.
So the easiest way is to clone [this](https://github.com/celsomarques/quarkus-native-app/tree/scram_ssl) and deploy to AWS/MSK in order to get the issue.

Or if you can point me to the right direction I can try to evaluate this

**Comment by radcortez** [comment]
Is the issue only reproducible in AWS? Aren't you able to reproduce it with a local Kafka instance?

**Comment by celsomarques** [comment]
I wasn't able to reproduce it locally because all docker-compose I tried broke in different ways, this ([https://github.com/hussein-joe/kafka-security-ssl-sasl](https://github.com/hussein-joe/kafka-security-ssl-sasl)) returns SSL handshake issue and I can't go further to simulate the user/password issue.

**Comment by cescoffier** [comment]
I used bearer and plain modules and everything worked OOTB.
So, we would need a reproducer to see what's wrong.

Please re-open if you have a reproducer and a hint.
