### ISSUE TITLE
Link from class to IDE does not work in JBang source

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#23001]
### Describe the bug

given this:

```
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-bom:999-SNAPSHOT@pom
//DEPS io.quarkus:quarkus-resteasy

//JAVAC_OPTIONS -parameters

import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello-resteasy")
@ApplicationScoped
public class main {

    @GET
    public String sayHello() {
        throw new IllegalStateException("What up");
        
    }

    public static void main(String[] args) {
        Quarkus.run(args);
    }
}
```

and you run it with `jbang -Dquarkus.dev main.java` then linking to class in arc bean does not work:

<img width="1656" alt="2022-01-19_10-34-26" src="https://user-images.githubusercontent.com/54129/150103519-99cdb251-3c15-48c2-9d9e-aeba5810843f.png">

looking at https://github.com/geoand/quarkus/blob/main/extensions/vertx-http/deployment/src/main/resources/dev-templates/main.html#L120 I thought maybe lack of package is causing it but even when adding `package dummy;` it does not seem to work.

### Expected behavior

that classes are possible to open from the devui

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/23470 takes care of the issue
