### ISSUE TITLE
Warnings about MetricCollectingClientInterceptor and MetricCollectingServerInterceptor when using grpc and micrometer

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#23011]
### Describe the bug

Warnings about `MetricCollectingClientInterceptor` and `MetricCollectingServerInterceptor` when using grpc and micrometer

Warnings:
 - At least one unused gRPC client interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingClientInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.
 - At least one unused gRPC interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingServerInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.

These warnings should be fixed or at least silenced using `LogCleanupFilterBuildItem`

```
[INFO] --- quarkus-maven-plugin:2.6.2.Final:build (default) @ code-with-quarkus ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[WARNING] [io.quarkus.grpc.deployment.GrpcClientProcessor] At least one unused gRPC client interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingClientInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.
[WARNING] [io.quarkus.grpc.deployment.GrpcServerProcessor] At least one unused gRPC interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingServerInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 921ms
```

### Expected behavior

No warnings

### Actual behavior

Warnings
```
[INFO] --- quarkus-maven-plugin:2.6.2.Final:build (default) @ code-with-quarkus ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[WARNING] [io.quarkus.grpc.deployment.GrpcClientProcessor] At least one unused gRPC client interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingClientInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.
[WARNING] [io.quarkus.grpc.deployment.GrpcServerProcessor] At least one unused gRPC interceptor found: io.micrometer.core.instrument.binder.grpc.MetricCollectingServerInterceptor. If there are meant to be used globally, annotate them with @GlobalInterceptor.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 921ms
```

### How to Reproduce?

 - select `Micrometer` and `gRPC` on https://code.quarkus.io/
 - download the app
 - run `mvn clean package`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.6.2.Final

**Comment by cescoffier** [comment]
Great catch! 

Yes, we should exclude the metrics interceptors from the checked list.
