### ISSUE TITLE
runjava.sh in docker images not consistent between java 11 and java 17

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#23045]
### Describe the bug

in 2.5-2.6 timeframe we ended up moving away from run-java.sh. That was probably a mistake but hope was run-java.sh from ubi-java would come available.

That is now present but not part of the delivered ubi images thus we need to find a way to handle this is in 2.7.

**Comment by gsmet** [comment]
@cescoffier I think this one can be closed? But we probably need to open a new one to use more appropriate images when we can.
