### ISSUE TITLE
REST Reactive Client: PartFilename annotation doesn't work if member is anything else than java.io.File

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#23059]
### Describe the bug

I have tested the new @PartFilename annotation in the REST Reactive client (Quarkus 2.7.0.CR1). See issue #22658 
However, the annotation seems to work only if the respective annotated member is of type java.io.File. I tested with java.nio.Buffer and java.lang.String. If one of these two types is used, the file name is not transferred.

Works as expected:
```java
public class OurForm {
  @FormParam("files")
  @PartFilename("document.txt")
  @PartType(MediaType.TEXT_PLAIN)
  private File documentFile;
}
```

Doesn't work:

```java
public class OurForm {
  @FormParam("files")
  @PartFilename("document.txt")
  @PartType(MediaType.TEXT_PLAIN)
  private String documentFile;
}

public class OurForm {
  @FormParam("files")
  @PartFilename("document.txt")
  @PartType(MediaType.TEXT_PLAIN)
  private Buffer documentFile;
}
```

### GraalVM version (if different from Java)

2.7.0.CR1

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/issues/22658#issuecomment-1017523516

**Comment by hbelmiro** [comment]
@geoand do you know if there's a definition for this? We're migrating the [quarkiverse/quarkus-openapi-generator](https://github.com/quarkiverse/quarkus-openapi-generator) extension to RESTEasy Reactive and this issue is impacting us.

**Comment by geoand** [comment]
WDYM by definition?

**Comment by hbelmiro** [comment]
Will it be supported only on `File`?

**Comment by geoand** [comment]
@FroMage does your multipart PR change ^?

**Comment by FroMage** [comment]
I don't think I touched anything related to filenames. Also, I think the file name annotation could be supported for any type, not just `File`.

**Comment by hbelmiro** [comment]
> I don't think I touched anything related to filenames. Also, I think the file name annotation could be supported for any type, not just `File`.

@FroMage @geoand Does this mean this issue is going to be fixed?

**Comment by FroMage** [comment]
Well, I'm saying we should fix it. Not that I have time to do it, sorry :( But if you send us a PR, I can help review it :)

**Comment by hbelmiro** [comment]
I understand. I'll see what I can do.
Thanks for now @FroMage and @geoand.

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus?

**Comment by hbelmiro** [comment]
@geoand Yes. It is.
Tested with 3.0.0.Alpha2.

**Comment by geoand** [comment]
Can you please attach a sample application that exhibits the problematic behavior?

**Comment by hbelmiro** [comment]
@geoand I created a reproducer: https://github.com/hbelmiro/multipart-reactive
Please see the [How to reproduce](https://github.com/hbelmiro/multipart-reactive#how-to-reproduce) section.

It seems like RESTEasy is ignoring the `PartType` annotation, which is used [here](https://github.com/hbelmiro/multipart-reactive/blob/373de6b0e72db9fcdf29bb5d24dc7bc7b43614aa/src/main/java/org/acme/UserProfileDataApi.java#L30).

The documentation states the following:
> Parameters specified as File, Path, byte[] or Buffer are sent as files and default to the application/octet-stream MIME type. Other @RestForm parameter types default to the text/plain MIME type. You can override these defaults with the @PartType annotation.

https://quarkus.io/guides/rest-client-reactive#multipart

**Comment by geoand** [comment]
Thanks, we'll have a look soon (cc @Sgitario )

**Comment by Sgitario** [comment]
> I can confirm that `@PartType` is not being used when sending a String. I'll try to make a fix tomorrow

I have a fix for this issue, coming soon...

**Comment by geoand** [comment]
Oh cool
