### ISSUE TITLE
Resource method String param annotated with @RestForm not decoded automatically

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#23055]
### Describe the bug

It seems that a String resource method param annotated with `@RestForm` is not decoded automatically. AFAIK the spec version of this annotation, i.e. `@FormParam` is decoded unless used together with `@Encoded`.

**Comment by geoand** [comment]
I am surprised we don't have any TCK issues with this... 

@FroMage any idea?

**Comment by FroMage** [comment]
Also surprised. I honestly don't remember how we implemented this.

**Comment by FroMage** [comment]
Well, I don't remember because I didn't write this part, check out `FormEncodedDataDefinition` and/or ask @stuartwdouglas ;)

**Comment by stuartwdouglas** [comment]
Do you have a reproducer? The spec and RestForm code should be exactly the same, and the TCK does test this.

**Comment by mkouba** [comment]
> Do you have a reproducer? The spec and RestForm code should be exactly the same, and the TCK does test this.

I'll try to prepare a reproducer today.

**Comment by mkouba** [comment]
@stuartwdouglas Here it is: https://github.com/mkouba/issue-23055

There is a simple form in the `index.hml` -> enter a space-separated value in the input field and submit the form.
