### ISSUE TITLE
JAXB not working properly with native images

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2305]
In https://github.com/quarkusio/quarkus/issues/2199 , we fixed the issue with live reload mentioned by @tcollignon but it's still not working for native images.

AFAICS, the issue is that the `package-info` required by JAXB is not included in the native image.

I opened https://github.com/oracle/graal/issues/1216 to get feedback from the GraalVM team.

The reproducer of @tcollignon is here: https://github.com/tcollignon/quarkus-jaxb-test .

**Comment by tcollignon** [comment]
Hi,

I have test with quarkus 0.19.1 and GraalVM 19.0.2, but it still the same

`
2019-07-12 16:48:25,904 INFO  [io.quarkus] (main) Quarkus 0.19.1 started in 0.003s. Listening on: http://[::]:8080
2019-07-12 16:48:25,904 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb]
[root@lddocedt1 ~]# docker logs -f 915
2019-07-12 16:48:25,904 INFO  [io.quarkus] (main) Quarkus 0.19.1 started in 0.003s. Listening on: http://[::]:8080
2019-07-12 16:48:25,904 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb]
javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.w3.org/2005/Atom", local:"feed"). Expected elements are <{}feed>
`

As thay said in https://github.com/oracle/graal/issues/1216, I don't know if the fix will be in quarkus or in GraalVM. WDYT ?
Thank you

**Comment by gsmet** [comment]
Totally forgot about it, sorry. Let's try to get this done for 0.20.0.

**Comment by gsmet** [comment]
Adding `good first issue` here as I think it shouldn't be too hard to fix given the information present in the GraalVM issue.

**Comment by tcollignon** [comment]
Nice, tell me if I can help you !
