### ISSUE TITLE
Continuous testing can fail after `mvn test` when run without `clean`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#23078]
### Describe the bug

I added a workaround to my project for #22552 which is setting the scope of lombok to `test` instead of `provided` via a specific `qtest` maven profile (that has `<defaultGoal>quarkus:test</defaultGoal>`).
This works if cont' testing is started on a "clean" state, but if regular testing was run before via `mvn test`, this workaround does not have any effect anymore.
In other words, I have to run `mvn clean quarkus:test` (clean!) if `mvn test` was run before, which is cumbersome and wastes time if you have many classes to generate/compile. It's also easy to forget.

### Expected behavior

Cont' testing should re-setup dependencies (if needed) and should not rely on what `mvn test` has left behind.

### Actual behavior

Doesn't re-setup dependencies and reuses what `mvn test` has left behind, which in this case means failing bedcause of the `provided` issue.

### How to Reproduce?

[q_ct-provided-2.zip](https://github.com/quarkusio/quarkus/files/7909031/q_ct-provided-2.zip) (note: uses 999-SNAPSHOT)

- `mvn quarkus:test -Dlombok.scope=test` (ok)
- `mvn clean test` (ok)
- `mvn quarkus:test -Dlombok.scope=test` (fails with `ClassNotFoundException`)
- `mvn clean quarkus:test -Dlombok.scope=test` (ok)

PS: This reproducer simply toggles the scope via a property instead of via a profile, but that's not relevant.

### Quarkus version or git rev

2.6.3.Final and current 999-SNAPSHOT

### Additional information

FWIW, `-Dquarkus.bootstrap.effective-model-builder=true` doesn't make a difference.

**Comment by aloubyansky** [comment]
Haven't yet checked but this could be related to the classpath caching. `target/quarkus/bootstrap/test-app-model.dat`. Removing only that one could be enough.

**Comment by famod** [comment]
Yes, that's sufficient!

Btw, one could argue that there should be no difference in dependencies between `quarkus:test` and `mvn test` and so a reuse is even _desired_. Yeah, maybe/probably for the vast majority of cases.

**Comment by famod** [comment]
Is that caching using some cache key or is it just "if the file exists, just reuse it!"?

**Comment by stuartwdouglas** [comment]
The issue would be that the caching does not know about the '-Dlombok.scope=test' parameter, so it will cache whatever the first value is.

**Comment by famod** [comment]
FTR, I'm now using this workaround:
```xml
        <profile>
            <id>qtest</id>
            <properties>
                <quarkus.test.continuous-testing>enabled</quarkus.test.continuous-testing>
            </properties>
            <build>
                <!-- note: remove-quarkus-cp-cache is a workaround for https://github.com/quarkusio/quarkus/issues/23078
                           (until https://github.com/quarkusio/quarkus/issues/22552 is resolved) -->
                <defaultGoal>clean:clean@remove-quarkus-cp-cache quarkus:test</defaultGoal>
                <plugins>
                    <plugin>
                        <artifactId>maven-clean-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>remove-quarkus-cp-cache</id>
                                <goals>
                                    <goal>clean</goal>
                                </goals>
                                <phase>clean</phase>
                                <configuration>
                                    <excludeDefaultDirectories>true</excludeDefaultDirectories>
                                    <filesets>
                                        <fileset>
                                            <directory>${project.build.directory}/quarkus/bootstrap</directory>
                                            <followSymlinks>false</followSymlinks>
                                            <useDefaultExcludes>false</useDefaultExcludes>
                                            <includes>
                                                <include>test-app-model.dat</include>
                                            </includes>
                                        </fileset>
                                    </filesets>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <dependencies>
                <!-- workaround for https://github.com/quarkusio/quarkus/issues/22552 (for JavaSourceTest) -->
                <dependency>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                    <version>${lombok.version}</version>
                    <scope>compile</scope>
                </dependency>
            </dependencies>
        </profile>
```

**Comment by aloubyansky** [comment]
Looks like `-Dlombok.scope=test` isn't propagated to `quarkus:test`. If you change the scope of lombok in the POM to a constant value `test`, it seems to work.

**Comment by aloubyansky** [comment]
Ah, no, it's not propagated to the default `mvn test` so it records `provided`.

**Comment by aloubyansky** [comment]
No, it is, sorry, ignore me.

**Comment by famod** [comment]
@aloubyansky FYI, I'm still seeing inconsistencies w.r.t. to that cache, so I need to reintroduce that workaround I posted previously: https://github.com/quarkusio/quarkus/issues/23078#issuecomment-1018340655
The concrete problem is with this workaround for ArchUnit: #23929
If `mvn test` (or similar) was run in a module, running  `mvn quarkus:test -Parchunit-exclude` afterwards will not respect that exclusion.
New issue or reopen?

**Comment by aloubyansky** [comment]
Is it still about changing the scope for lombok?

**Comment by famod** [comment]
No, this time it's about what I documented as a workaround in #23929, which is an exclusion for ArchUnit (in a profile).
So same same but different. 😉

**Comment by aloubyansky** [comment]
I think we need an option to ignore the cache then.
