### ISSUE TITLE
QuarkusIntegrationTest with quarkus-amazon-lambda-http and jar build doesn't work

### ISSUE THREAD

**Issue by sschulze** [quarkusio/quarkus#23077]
### Describe the bug

I generated a very simple Maven project with quarkus-amazon-lambda-http from the archetype quarkus-amazon-lambda-http-archetype. There I replaced `@NativeImageTest` with `@QuarkusIntegrationTest` as well as removed the examples for funqy, servlet and vertx. After that, `mvn verify -Pnative` runs through without any problems. 

Now I would like to be able to run the integration tests on a JAR build as well. To do this, I added a simple failsafe configuration in the POM outside of the profile (identical to the one in the profile, but without `native.image.path`). However, the `mvn verify` now fails with a SocketTimeout Read timed out.

I tested this in WSL2 (my usual environment) as well as on a real Debian machine to rule out some WSL2 related networking issues.

### Expected behavior

The `@QuarkusIntegrationTest` should go through whether it is a native build or a JAR build.

### Actual behavior

The `@QuarkusIntegrationTest` runs through for Native Build and fails for a JAR build.

### How to Reproduce?

Reproducer:

1. Clone https://github.com/sschulze/Test
2. call `mvnw verify -Pnative` -> integration tests run through sucessfully
3. call `mvnw verify`-> integration tests fail with SocketTimeout 

### Output of `uname -a` or `ver`

Linux mymachine 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Linux myserver 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1deb10u1, mixed mode, sharing)

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3-java11

### Quarkus version or git rev

2.6.2.Final & 2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /opt/apache-maven
Java version: 11.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix"

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.13, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-17-amd64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Thanks for reporting.

Can you make the reproducer available please? I am getting a `404` when accessing https://github.com/sschulze/Test

**Comment by sschulze** [comment]
@geoand Reproducer is public now.

**Comment by geoand** [comment]
@patriot1burke I get [this](https://github.com/quarkusio/quarkus/blob/2.6.3.Final/extensions/amazon-lambda/deployment/src/main/java/io/quarkus/amazon/lambda/deployment/AmazonLambdaProcessor.java#L239). What's the reason for the different behavior in native mode vs JVM mode?

**Comment by patriot1burke** [comment]
What's wrong with doing a regular @QuarkusTest?  Its executing the same exact code path that you would run in production.

**Comment by geoand** [comment]
Nothing wrong with it. 

But [@QuarkusIntegrationTest](https://quarkus.io/guides/getting-started-testing#quarkus-integration-test) was introduced to cover a different set of scenarios and people are now using with Lambda when building a JAR and it's failing

**Comment by patriot1burke** [comment]
@QuarkusIntegrationTest will not work with regular JAR/Java and any quarkus lambda extension.  For a pure Java deployment for AWS Lambda, there is no quarkus poll loop as the -runner.jar runs inside the AWS Java runtime and the AWS runtime executes the poll loop. 

Why does it work in native?  Well, with a native build quarkus has to execute a poll loop itself as the native executable does not run in any AWS runtime that handles the poll for you.

Hope that makes sense.

**Comment by patriot1burke** [comment]
BTW, I think @QuarkusIntegrationTest is overkill for 99.999999% of scenarios and just eats more CI server cpu.

**Comment by sschulze** [comment]
I understand the root cause with the poll loop - I already thought it's something in this direction, but I didn't understood how the mock-event-server comes into play when executing a native-image QuarkusIntegrationTest.

Regarding our use case:
We usually generate a native image for deployment, so we write QuarkusIntegrationTests to ensure we won't run into some problems cause by native-image (i.e. reflection used by libraries) after deployment.
During development we regularly want to run these tests too, but don't want to do a full native build because it's rather time consuming.

We could just create a QuarkusIntegrationTest and inherit from the QuarkusTests, but as far as I understood, we have a different featureset to our avail - especially no mocking in QuarkusIntegrationTest and no injection of application beans into the test class because of (i guess) running the application in a forked process.

Finally I expected that QuarkusIntegrationTest work because it was designed to [_test the generated application no matter what it is._](https://groups.google.com/g/quarkus-dev/c/zoXRyHFDAYI) and it's documented to run and test the artifact produced by the build "of whichever type"
> this means that if the result of a Quarkus build (mvn package or gradle build) is a jar, that jar will be launched as java -jar …​ and tests run against it. If instead a native image was built, then the application is launched as ./application …​ and again the tests run against the running application.
([Source](https://quarkus.io/guides/getting-started-testing#quarkus-integration-test))

So at least the documentation is currently misleading.

**Comment by geoand** [comment]
I personally don't agree with closing the issue.

IMO, we should make @QuarkusIntegrationTest work in this case as well

**Comment by patriot1burke** [comment]
> I understand the root cause with the poll loop - I already thought it's something in this direction, but I didn't understood how the mock-event-server comes into play when executing a native-image QuarkusIntegrationTest.
> 
> Regarding our use case: We usually generate a native image for deployment, so we write QuarkusIntegrationTests to ensure we won't run into some problems cause by native-image (i.e. reflection used by libraries) after deployment. During development we regularly want to run these tests too, but don't want to do a full native build because it's rather time consuming.
> 
> We could just create a QuarkusIntegrationTest and inherit from the QuarkusTests, but as far as I understood, we have a different featureset to our avail - especially no mocking in QuarkusIntegrationTest and no injection of application beans into the test class because of (i guess) running the application in a forked process.
> 
> Finally I expected that QuarkusIntegrationTest work because it was designed to [_test the generated application no matter what it is._](https://groups.google.com/g/quarkus-dev/c/zoXRyHFDAYI) and it's documented to run and test the artifact produced by the build "of whichever type"
> 
> > this means that if the result of a Quarkus build (mvn package or gradle build) is a jar, that jar will be launched as java -jar …​ and tests run against it. If instead a native image was built, then the application is launched as ./application …​ and again the tests run against the running application.
> > ([Source](https://quarkus.io/guides/getting-started-testing#quarkus-integration-test))
> 
> So at least the documentation is currently misleading.



> I personally don't agree with closing the issue. IMO, we should make @QuarkusIntegrationTest work in this case as well

Getting it to work with QuarkusIntegrationTest would be a hack and the code would be even more divergent than it would be in an actual lambda environment, especially native.  Running QuarkusTest is about the closest you can get to native without it being native.
