### ISSUE TITLE
Resteasy reactive - make it possible to extend the set of "non-blocking" return types

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#23088]
### Description

It might make sense to register additional types that would result in implicit `@NonBlocking`. For example, a resource method that returns `TemplateInstance` can be considered non-blocking as well.

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
@mkouba https://github.com/quarkusio/quarkus/pull/23098 takes care of the issue
