### ISSUE TITLE
Run integration tests against container

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#23082]
### Description

In a situation, where end users are developing on Windows or Mac and their target production platform is a linux container containing a GraalVM native executable, I believe, it would be very useful for the local development to be able to run tests directly against the container, rather than against a native executable built for the local platform that is different from their actual target platform.

@adamu asked a similar question here https://stackoverflow.com/questions/62277197/quarkus-testing-native-image-built-in-container

**Comment by geoand** [comment]
I might be missing something, but doesn't `@QuarkusIntegrationTest` cover you needs?

**Comment by ppalaga** [comment]
Indeed, `@QuarkusIntegrationTest` looks like what I am looking for. I did not know it exists, thanks for the info. 

Here is the link for future readers: https://quarkus.io/guides/getting-started-testing#quarkus-integration-test
