### ISSUE TITLE
Reduce the size of container images with DockerSlim

### ISSUE THREAD

**Issue by ThoSap** [quarkusio/quarkus#23117]
### Description

Hi,

I just read the [RedHat article (Reduce the size of container images with DockerSlim)](https://developers.redhat.com/articles/2022/01/17/reduce-size-container-images-dockerslim) from [this tweet](https://twitter.com/bibryam/status/1485188557463449603?t=uHJyxrzUfINKXuwdNBKojQ).

Could DockerSlim be something for even smaller JVM/native Docker images?
https://dockersl.im/
https://github.com/docker-slim/docker-slim

**Comment by famod** [comment]
Interesting! It seems to be a Go binary, so it's probably not directly "embeddable" in the Qaurkus container creation (like Jib for instance).

But maybe there could be a flag to execute DockerSlim (which would need to be on the PATH) after the image is built/before it's pushed?

**Comment by geoand** [comment]
@cescoffier WDYT?

**Comment by cescoffier** [comment]
We would need to try and measure the benefit. I'm not sure we will save much for `micro` and even Java `runtime` images.  But, it deserves a spin on the "Base" image and on the images including the Quarkus app.

I've looked into `micro` deeply. I know I can shave some Mb, so it would be interesting to see how much we can save with this approach.

**Comment by geoand** [comment]
@ThoSap would you be interested in carrying out an experiment to see what saving are obtained by using `docker-slim` for your images?

**Comment by ThoSap** [comment]
Of course, let me try it.

**Comment by ThoSap** [comment]
Sorry, I did not find the time to look into this due to personal reasons.

**Comment by geoand** [comment]
Closing this for now.

Feel free to reopen if you want to revisit it in the future
