### ISSUE TITLE
Move to using a config map for quarkus.hibernate-orm.cache.* config properties

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2312]
Otherwise, we end up with these warnings:
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ quarkus-integration-test-infinispan-cache-jpa ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.hibernate-orm.cache."com.example.EntityB".expiration.max-idle" provided
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.hibernate-orm.cache."com.example.EntityA".memory.object-count" provided
```

We used a workaround while the map config code was still under work but we should be able to migrate to map support now.

**Comment by machi1990** [comment]
Is having config values like these ones 
``` 
quarkus.hibernate-orm.cache."com.example.EntityA.memory.object-count"=200
quarkus.hibernate-orm.cache."com.example.EntityB.expiration.max-idle"=86400 
....
```  
an option?

**Comment by gsmet** [comment]
No, the config needs to be like this, according to our map config support:
```
quarkus.hibernate-orm.cache."com.example.EntityB".expiration.max-idle
```
the `"` allows the dots to be escaped.

Basically, you will have a:
```
Map<String, CacheConfig> cache;
```
and `CacheConfig` will contain the configuration properties `memory.object-count` and so on.

You can see an example of the map support in the Agroal extension config.

**Comment by machi1990** [comment]
@gsmet thanks for getting back. 

> No, the config needs to be like this, according to our map config support:
> 
> ```
> quarkus.hibernate-orm.cache."com.example.EntityB".expiration.max-idle
> ```
> 
> the `"` allows the dots to be escaped.

Yes. Looking at the current implementation, the corresponding `hibernate.cache` config property key is "same" as the one for `quarkus.hibernate-orm.cache`,  I though of an implementation where the config property is double quoted e.g `"<region_name>.memory.object-count"`. The quoted config property will be the key of a map i.e 
``` 
@ConfigItem(name= ConfigItem.PARENT)
Map<String,String> properties; 
```

This narrowed down `HibernateOrmProcessor` caching part implementation to something like...
```   
// Caching
   for (Map.Entry<String, String> entry : hibernateConfig.cache.properties.entrySet()) {
          String hibernateKey = "hibernate.cache." + entry.getKey();
          desc.getProperties().setProperty(hibernateKey, entry.getValue());
   }
```

**Comment by gsmet** [comment]
The idea is to propose a consistent approach to the Quarkus users.

It might not be the most optimal if you consider the number of lines of code but it will be better in the long term.

So yes, we need a layer to translate the configuration.

**Comment by machi1990** [comment]
> The idea is to propose a consistent approach to the Quarkus users.

Solid point. +1. 



> So yes, we need a layer to translate the configuration.

I'll work on this over the weekend.
