### ISSUE TITLE
How can I prevent Slowloris attacks in quarkus?

### ISSUE THREAD

**Issue by bhushanshinde07** [quarkusio/quarkus#23131]
### Discussed in https://github.com/quarkusio/quarkus/discussions/23130

<div type='discussions-op-text'>

<sup>Originally posted by **bhushanshinde07** January 24, 2022</sup>
I am trying to protect my quarkus application from Slowloris attacks so Is there any configuration setting or way available in the quarkus?</div>

**Comment by geoand** [comment]
As this is a question, let's close this in favor of the discussion
