### ISSUE TITLE
OpenTelemetry Vert.x integration doesn't create spans for Event Bus or SQL

### ISSUE THREAD

**Issue by markusdlugi** [quarkusio/quarkus#23144]
### Describe the bug

Since Quarkus 2.6 (I guess since the refactoring in https://github.com/quarkusio/quarkus/pull/21583 or the fix in https://github.com/quarkusio/quarkus/pull/22615), the OpenTelemetry Vert.x integration only creates spans for REST calls and nothing else. I tested both Event Bus and Hibernate Reactive (i.e. Vert.x SQL client), but no spans are automatically created for any of these technologies. In Quarkus 2.5 it was working fine, spans for both of these technologies were automatically created (although the spans created by Vert.x SQL client were not attached to the overall trace, but that's a different issue I guess).

### Expected behavior

Spans for Event Bus, Hibernate Reactive etc. are automatically created

### Actual behavior

No spans are created for the aforementioned technologies

### How to Reproduce?

Reproducer: https://github.com/markusdlugi/opentelemetry-bug

1. Start Jaeger + OTel Collector via `docker-compose up`
2. Start application and call `http://localhost:8080/hello`
3. Observe that only a trace with a single span for the Resteasy endpoint is created (check Jaeger at `http://localhost:16686/`)
4. After rolling back to Quarkus 2.5.3.Final, spans for Event Bus and Vert.x SQL Client are also created

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.631]

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.7.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by radcortez** [comment]
I'll have a look.

**Comment by cdmikechen** [comment]
@radcortez 
Hi~ I've tested opentelemetry in quarkus 2.8.0 and found a problem...
Suppose I use hibernate reactive to run the following codes. At present, the span viewed in Jaeger is only the first and third lines.
```java
htrepo.update("isDelete = true, updateTime = ?1 where id = ?2", now, table.id)
    .call(r -> htdrepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
    .call(r -> hdrepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
    .call(r -> hmrepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
```

I don't know what configs caused it. At present, I deploy my quarkus app according to the configuration in https://quarkus.io/guides/opentelemetry.
If you have time, can you help me see if there is anything wrong, please.

**Comment by gsmet** [comment]
@cdmikechen please create a separate issue with a simple reproducer. Thanks.
