### ISSUE TITLE
When generating Kubernetes files (minikube,openshift,kubernetes) add "common.yml" 

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkus#23188]
### Description

Now when generating the yaml files for Kubernetes , we need to put the fragments to be added on the final generated file ( target/kubernetes/{deployment-target}.yml) 

This leads to have duplicated fragments in 3 files.

### Implementation ideas

Consider a 4th file : common.yml that contains fragments that will be added in every target-deployment yaml.

kubernetes.yml = common.yml + kubernetes.yml + generated files
openshift.yml = common.yml + openshift.yml + generated files
minikube.yml = common.yml + minikube.yml + generated files

**Comment by geoand** [comment]
I like the idea!

**Comment by geoand** [comment]
This would need a change in Decorate, right @iocanel ?

**Comment by geoand** [comment]
cc @Sgitario

**Comment by Sgitario** [comment]
I think this is already working as intended. If you place your `common`manifests at `src/main/kubernetes`, the framework will use it as a base to generate the others. 
Wdyt @iocanel ?

**Comment by Sgitario** [comment]
Closing this issues because it's duplicated by https://github.com/quarkusio/quarkus/issues/22290
