### ISSUE TITLE
When renerating kubernetes deployment files, only generate the selected deployment-target

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkus#23189]
### Describe the bug

When we package a kubernetes application, now apparently it is generating always 6 files : kubernetes.{yml | json} , minikube.{yml | json } , openshift.{yml | json} even when we specify the target : -Dquarkus.kubernetes.deployment-target=kubernetes

### Expected behavior

Only generate the files for the deployment-target specified ( or fallback to kubernetes )

### Actual behavior

Generates always 6 files : kubernetes.{yml | json} , minikube.{yml | json } , openshift.{yml | json} 

### How to Reproduce?

Project : https://github.com/keycloak/keycloak/tree/main/operator
mvn clean package -Dquarkus.container-image.build=true -Dquarkus.kubernetes.deployment-target=kubernetes 

### Output of `uname -a` or `ver`

Linux localhost-live.home 5.15.14-200.fc35.x86_64 #1 SMP Tue Jan 11 16:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
I don't think we really need to fix this one, as it doesn't really affect anything
