### ISSUE TITLE
shamrock:dev cannot be run in Eclipse

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#232]
If you have a simple project and follows:

1. `Run -> Run Configurations...`
2. Right-Click on `Maven Build` and select `new Configuration`
3. Give a name to the new configuration (such as `Run dev mode`)
4. Set the base directory to `${project_loc}`
5. In the `goals` field enter: compile shamrock:dev
6. Click on `Run`

The application is served correctly.
But:

1. The hot-redeploy does not work (classpath issue)
2. The red button does not stop the process

**Comment by Dufgui** [comment]
I test it @cescoffier @FroMage  with current 999-SNAPSHOT and it seems working.
Could one them test and close it, if it 's fix for you too. I test with the getting started project

**Comment by gastaldi** [comment]
I can confirm that this works in Eclipse Version: `2019-06 (4.12.0)` Build id: `20190614-1200` by following the steps described by @cescoffier in https://github.com/quarkusio/quarkus/issues/232#issue-388932524
