### ISSUE TITLE
Consider creating a jar with the main and core annotations and API Quarkus uses

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2320]
This issue is opened not for action but instead for evaluation of popularity.
If you want the feature, please comment - ideally with your reasons.

An argument has been made that it can be confusing for newcomers unfamiliar with CDI, MP Config etc to find the right annotations and APIs to use. A proposal is to shade these APIs and place them under a `io.quarkus.core` or equivalent.
Some also dislike `javax.entreprise` at face value.

The proposal is to look at what is considered core of Quarkus usage, not to move all possible APIs.

- javax.inject
- javax.decorator
- javax.enterprise.context
- javax.enterprise.event
- javax.enterprise.inject
- javax.enterprise.util
- org.eclipse.microprofile.config

Anything else?

We could create an artificial jar which repackages those under io.quarkus.component / config and do some binding between the repackage and the standard one like we do with the Spring ones. Right know, I haven't heard people wanting that besides two persons / groups. Since it's not a trivial amount of work and implies some legal checking, I'd rather we check the popularity of this proposal.
Note that it would make auto-complete worse as for the person adding this synthetic jar, the classpath will have 2 sets of annotations and APIs with the same name. Looks like a bad user experience.

**Comment by gsmet** [comment]
Doesn't look really popular. I'm closing it.
