### ISSUE TITLE
Kafka security config params not being picked up from env vars (channel config)

### ISSUE THREAD

**Issue by ctron** [quarkusio/quarkus#23234]
### Describe the bug

Kafka configuration on the channel does not get picked up when using environment variables.

This seems to be a variant of https://github.com/quarkusio/quarkus/issues/9947

When using channel specific configuration (e.g. `MP_MESSAGING_INCOMING_<channel>_SASL_JAAS_CONFIG`) it doesn't get picked up. But it works when using e.g. the YAML file.

### Expected behavior

Should work with environment variables as well.

### Actual behavior

Does not work.

### How to Reproduce?

* Create a working configuration using Kafka configuration in the channel section
* Convert to env-vars according to the micro-profile specification

### Output of `uname -a` or `ver`

Linux brocken 5.15.13-200.fc35.x86_64 #1 SMP Wed Jan 5 16:39:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment 18.9 (build 11.0.13+8) OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

**Comment by cescoffier** [comment]
Hum, I don't see why it would not work. It is likely a bug in how we read the config in the kafka connector.

**Comment by cescoffier** [comment]
@ctron you mentioned env file in the title. Does it happen with env files or with env variables?

**Comment by ctron** [comment]
Hm, indeed I experiences this with env-vars. Not sure about env-files. Will correct the title.

**Comment by ozangunalp** [comment]
@ctron I could not trivially reproduce it. I tried different channel names and expression evaluation and it also works with those scenarios.

Could you give an example of the config you are trying to set via env var?

**Comment by cescoffier** [comment]
Also, Ozan and I tried JVM mode only. Are you using native?

**Comment by ctron** [comment]
No, didn't try native. But I can definitely reproduce it. The following config change brings it back to live (the opposite breaks it):

![image](https://user-images.githubusercontent.com/202474/151927571-2996e279-a73d-4b32-97da-ed6efb71a3ae.png)

https://github.com/drogue-iot/ditto-reconciler/commit/6dc1f7361bcbdc21fae93cfe431d7c81da1cb48a

**Comment by cescoffier** [comment]
The "kafka." properties are extracted and used as the "default" Kafka configuration. So, they are not read the same way. I would recommend "kafka." for auth as, in general, it applies to all the channels. 

That being said, I would need a reproducer as my simple tests did work smoothly.

**Comment by cescoffier** [comment]
Closing, as we would need a reproducer.

I used a similar code for a devoxx university about Kafka I gave 2 weeks ago. and everything worked OOTB.
