### ISSUE TITLE
Unsafe ResteasyContext propagation

### ISSUE THREAD

**Issue by robotmrv** [quarkusio/quarkus#23236]
### Describe the bug

I've noticed that `ResteasyContext` could share mutable state in multiple `Thread`s that could lead to `java.util.ConcurrentModificationException` or unpredictable behavior 

### Expected behavior

`ResteasyContext` mutation in parent `Thread` change values in propagated context

### Actual behavior

`ResteasyContext` mutation in parent `Thread` change values in propagated context.  
That could lead to `java.util.ConcurrentModificationException` or unpredictable behavior. 

### How to Reproduce?

Reproducer:
https://github.com/robotmrv/mutable-context

*Test case 1* 
1. start application
2. make http request GET http://localhost:8080/hello 
3. check logs 
ER: `ResteasyContext` mutation in parent `Thread` does not change values in propagated context
AR: `ResteasyContext` mutation in parent `Thread` change values in propagated context.
   see logs for `Source: helloResource.2` and `Source: async.2`. dataMap has the same hashCode value,
   and values for key `String` are the same. `Source: async.2` should have the same value as in `Source: async.1`

*Test case 2*
1. start application
2. make http request GET http://localhost:8080/hello/cme
3. check logs
   ER: no logs for logger `test`
   AR: error log
```
ERROR [test] (executor-thread-0) Error in async Thread: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1584)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1617)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1615)
	at org.acme.GreetingResource.lambda$cme$1(GreetingResource.java:59)
	at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:268)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1502)
```

### Output of `java -version`

openjdk version "11" 2018-09-25 OpenJDK Runtime Environment 18.9 (build 11+28) OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Quarkus version or git rev

2.6.3.Final

**Comment by robotmrv** [comment]
While there is an issue in `io.quarkus.resteasy.common.runtime.ResteasyContextProvider#currentContext` since it does not make defensive copy of the context `Map` I have is a question:   
Is it acceptable to interact with `ResteasyContext` in user code to add own values etc?

**Comment by geoand** [comment]
I would argue that `ResteasyContext` is not part of the public API and if you do use it, you are doing so at your own risk.

What is your actual use case that requires you to use `ResteasyContext` ?

**Comment by robotmrv** [comment]
hi @geoand 
we want to propagate among `Thread`s our business context, so we have options  
- use `ResteasyContext` - less code and automatic integration with microprofile context propagation  
- create own context and integration with microprofile context propagation

**Comment by flupec** [comment]
@geoand We are using it for request-time objects like userId and so on. In case of using Mutiny framework we suffer from sharing those objects between threads.

We found that for request-time objects ResteasyContext is used, for example, by RequestDispatcher.

If ResteasyContext is not supposed to be used by clients, then what we should use?

**Comment by geoand** [comment]
> create own context and integration with microprofile context propagation

From a Quarkus perspective, this is the way to go.
