### ISSUE TITLE
jvmTarget for kotlin-maven-plugin set to 11 even if project is generated with Java 17

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#23235]
### Describe the bug

jvmTarget for kotlin-maven-plugin set to 11 even if project is generated with Java 17

jvmTarget 11 is hardcoded in templates for Kotlin, it even has some logic for Java 8 which should be gone

```java
git grep jvmTarget | grep base-codestarts
independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle-kotlin-dsl/kotlin/build.tpl.qute.gradle.kts:
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle-kotlin-dsl/kotlin/build.tpl.qute.gradle.kts:
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle/kotlin/build.tpl.qute.gradle:
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle/kotlin/build.tpl.qute.gradle:
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/maven/kotlin/pom.tpl.qute.xml:
                    <jvmTarget>11</jvmTarget>
```

Changes similar to https://github.com/quarkusio/quarkus/pull/20849 should be done to kontlin templates

### Expected behavior

`<jvmTarget>17</jvmTarget>` in the config of kotlin-maven-plugin

### Actual behavior

`<jvmTarget>11</jvmTarget>` in the config of kotlin-maven-plugin

### How to Reproduce?

 - Use Java 17
 - https://quarkus.io/guides/kotlin#creating-the-maven-project
 - Check pom.xml

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.6.3.Final

**Comment by Sanne** [comment]
@rsvoboda why is this a problem?

**Comment by rsvoboda** [comment]
This issue is about inconsistency, when using Java 17 I expect to have all defaults set to 17, now I have `<maven.compiler.release>17</maven.compiler.release>` property set, but `<jvmTarget>11</jvmTarget>` for kotlin-maven-plugin

**Comment by Sanne** [comment]
Ok sure that makes sense, I wondered if there was a functionality problem being caused by this. Thanks for clarifying.
