### ISSUE TITLE
Not able to get request body from request context

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#23242]
### Description

I'm trying to get the body from request context

- **what I've tried**

inject `CurrentVertxRequest` context and then get body from there

```java
@Path("/map_event")
public class MapEventApi {

    @Inject
    CurrentVertxRequest reqContext;
  

    @POST
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Response create(@Valid MapEvent mapEvent, @Context SecurityContext securityContext) throws Exception {
        String body = reqContext.getCurrent().getBodyAsString();
        ...
    }

}
```
but the `getBodyAsString()` gives null value, with a warning:

```
2022-01-25 18:22:08,854 WARN  [null:-1] (executor-thread-0) BodyHandler in not enabled on this route: RoutingContext.getBodyAsString(...) in always be NULL
```

- **another try:**

inject standard JaxRS `HttpServletRequest` context
```
@Context HttpServletRequest

```
will get this error:
```
org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: javax.servlet.http.HttpServletRequest
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:155)
        at com.sun.proxy.$Proxy97.getInputStream(Unknown Source)
```
I guess it's because quarkus uses vertx under the hood so injecting regular JAX-RS context won't work since it's not the same thread.

Can not find a proper way to get the request body, anyone can help?

**Comment by geoand** [comment]
Closing this as it's a question (that has already been asked on StackOverflow now less)

**Comment by voronovmaksim** [comment]
The question is https://stackoverflow.com/questions/70858052/quarkusvertx-how-to-get-request-body-in-a-blocking-way

@geoand, it works, thanks a lot, but how can i get body in code that is different from controller and moreover i want to get the body several times? 
For example in request filter or elsewhere.
Request filter can look like it:
````
public void filter(ContainerRequestContext requestContext) throws IOException {
        final InputStream onceReadInputStream = requestContext.getEntityStream();
}
````
but in that case i can call `org.apache.commons.io.IOUtils.toString(onceReadInputStream, java.nio.charset.StandardCharsets.UTF_8.name())` only once, becasue as it is known, inpust stream can be read once.

**Comment by geoand** [comment]
Not sure I understand the question to be honest

**Comment by voronovmaksim** [comment]
I need to get RAW body as many times as it takes.
1) i need to print the body in ten filters. Of cause it is fake case, but it describes my problem well.
How can it be done?
At the moment i see only one solution:
````
  public void filter(ContainerRequestContext requestContext){
	    final byte[] bytes = requestContext.getEntityStream().readAllBytes();
		
        final ByteArrayInputStream inputStreamForPrint = new ByteArrayInputStream(bytes);
        System.out.println(org.apache.commons.io.IOUtils.toString(streamContinueHttpRequest, java.nio.charset.StandardCharsets.UTF_8.name()););
		
        final ByteArrayInputStream inputStreamToPassNext = new ByteArrayInputStream(bytes);
        requestContext.setEntityStream(inputStreamToPassNext);
  }
````
2) Also, i need to get the body in some ResourseLoader, the ResourseLoader is not controller it is just bean. 
i want to use 
````
class ResourseLoader {
	@Inject (Or @Context)
    CurrentVertxRequest reqContext;

	void load(){
		String body = reqContext.getCurrent().getBodyAsString();
	}
}
````

I Hope i desribed my problem little clearer this time. Thanks a lot.

**Comment by geoand** [comment]
If I needed to read the body many times in filter, what I would do is setup a `ContainerRequestFilter` with a very low `@Priority` (thus it would be executed very early) that read the body and saved in a property of `ContainerRequestContext`. Then my other filters would read the body from there

**Comment by voronovmaksim** [comment]
Thanks. We'll do as you suggested

**Comment by voronovmaksim** [comment]
@wtorre5 Hi,
As I remember, we did as I wrote above, but instead of 
''''
System.out.println(org.apache.commons.io.IOUtils.toString(streamContinueHttpRequest));
''''
We created our own class that can be read multiple times and placed it in the ContainerRequestFilter property as geoand suggested.
Another way is to create our own stream that can be read multiple times and then set the stream to requestContext.setEntityStream. However, in this way, you need to close the stream manually.
