### ISSUE TITLE
Quarkus maven plugin overwrite `quarkus.package.type`

### ISSUE THREAD

**Issue by glefloch** [quarkusio/quarkus#23264]
### Describe the bug

If I set `quarkus.package.type=uber-jar` in my `application.properties` file, the property will be ignored. If I set that property in my `pom.xml` then the packaging will be ok

### Expected behavior

`quarkus.package.type` property should be not be overwrite by the maven plugin (if not explicitly requested)

### Actual behavior

The plugin always overwrite the property event if not reference to `quarkus.package.type` is present in the pom.xml

### How to Reproduce?

* Create a simple projet from `code.quarkus.io`
* Set `quarkus.package.type=uber-jar` in `src/main/resources/application.properties`
* run `mvn clean quarkus:build`
* the uber jar does not exists in `target/`

* try setting `<quarkus.package.type>uber-jar</quarkus.package.type>` in the `<properties/>` block of your `pom.xml`, 
*  run `mvn clean quarkus:build`
* the uber jar exists in `target/`

### Quarkus version or git rev

2.6.3.Final / 999-SNAPSHOT

**Comment by famod** [comment]
Have you tried `mvn clean package -DskipTests`?
The thing is that `BuildMojo` is _not_ cherry-pickign any plugin executions (like e.g. `DevMojo`).
So with just `mvn clean quarkus:build` there will be no execution of `maven-resources-plugin`, hence no `application.properties` in `target/classes`.

**Comment by glefloch** [comment]
You are right @famod running `mvn package` works as expected, closing this issue.
