### ISSUE TITLE
BuildMojo does not take into account project's packaging (assuming it's a jar)

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2327]
I'm running into an odd error when building a Quarkus project: it fails when the Quarkus Maven plug-in tries to resolve the project's dependencies. You can try it by building this project here: git@github.com:debezium/debezium-examples.git/kstreams-live-update/aggregator.

```
This gives me this failure:

[INFO] --- quarkus-maven-plugin:0.13.3:build (default) @
kstreams-live-update-aggregator ---
Downloading from confluent:
http://packages.confluent.io/maven/io/debezium/examples/kstreams-live-update-aggregator/0.1-SNAPSHOT/maven-metadata.xml
Downloading from snapshots-repo:
https://oss.sonatype.org/content/repositories/snapshots/io/debezium/examples/kstreams-live-update-aggregator/0.1-SNAPSHOT/maven-metadata.xml
Downloading from snapshots-repo:
https://oss.sonatype.org/content/repositories/snapshots/io/debezium/examples/kstreams-live-update-aggregator/0.1-SNAPSHOT/kstreams-live-update-aggregator-0.1-SNAPSHOT.jar
Downloading from confluent:
http://packages.confluent.io/maven/io/debezium/examples/kstreams-live-update-aggregator/0.1-SNAPSHOT/kstreams-live-update-aggregator-0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.482 s
[INFO] Finished at: 2019-05-02T22:22:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal
io.quarkus:quarkus-maven-plugin:0.13.3:build (default) on project
kstreams-live-update-aggregator: Failed to resolve application model
io.debezium.examples:kstreams-live-update-aggregator::jar:0.1-SNAPSHOT
dependencies: Failed to resolve dependencies for
io.debezium.examples:kstreams-live-update-aggregator:jar:0.1-SNAPSHOT:
Could not find artifact
io.debezium.examples:kstreams-live-update-aggregator:jar:0.1-SNAPSHOT
in snapshots-repo
(https://oss.sonatype.org/content/repositories/snapshots)
```

It works, if the project's artifact is already installed from a previous run. I also tried with 0.14.0, but it's the same.

**Comment by gunnarmorling** [comment]
Hey @aloubyansky, could you take a look into this one? @gsmet told me you're the SME around the resolver :) Thanks!

**Comment by aloubyansky** [comment]
Sure, will do in a bit.

**Comment by aloubyansky** [comment]
I have a fix for the resolver. There is another issue though. The packaging of your project is `war`, while the Quarkus maven plugin produces a `jar` which won't be accepted by the Maven install goal.

**Comment by gsmet** [comment]
On Fri, May 3, 2019 at 10:00 AM Alexey Loubyansky <notifications@github.com>
wrote:

> I have a fix for the resolver. There is another issue though. The
> packaging of your project is war, while the Quarkus maven plugin produces
> a jar which won't be accepted by the Maven install goal.
>

Could we detect that and provide a useful error? Or do we already?

**Comment by aloubyansky** [comment]
While in most cases we could fail fast, I'd still need to look into custom packaging types to make sure it won't break them.

**Comment by gunnarmorling** [comment]
> I have a fix for the resolver

Great news! But is there anything I can do on my end to circumvent this issue before the fix is released? I'm curious about the details, what is so special about my project that it exposes this issue?

**Comment by gunnarmorling** [comment]
Ok, so I got it working by changing the packaging to JAR. Then install fails as you say, but package at least runs.
