### ISSUE TITLE
Mutiny Service Interface cannot be injected

### ISSUE THREAD

**Issue by iLem0n** [quarkusio/quarkus#23277]
### Describe the bug

Basic implementation of gRPC communication throws:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: de.ilem0n.SessionServiceInterface cannot be injected into de.ilem0n.sessions.FlinkSessionReconciler#sessionService - only Mutiny service interfaces, blocking stubs, reactive stubs based on Mutiny and io.grpc.Channel can be injected via @GrpcClient
```

The classes generated from *.proto-files (see project in reproduce steps) contains `SessionServiceInterface`, which is in fact a MutinyService-interface.   
The Error itself says that 'only Mutiny service interfaces [...] can be injected via @GrpcClient' but throws when injecting it.

I have reduced my project to the bare minimum - refer to 'How to Reproduce'-section

### Expected behavior

expecting that the Mutiny interface implementation can be injected. 

### Actual behavior

throws at runtime: 
Caused by: javax.enterprise.inject.spi.DeploymentException: de.ilem0n.SessionServiceInterface cannot be injected into de.ilem0n.sessions.FlinkSessionReconciler#sessionService - only Mutiny service interfaces, blocking stubs, reactive stubs based on Mutiny and io.grpc.Channel can be injected via @GrpcClient

### How to Reproduce?

1. clone https://gitlab.com/iLem0n/grpcmutinyexample
2. build and run it 
3. try to access the /hello endpoint

### Output of `uname -a` or `ver`

Darwin Peters-MBP.fritz.box 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java 16.0.1 2021-04-20 Java(TM) SE Runtime Environment (build 16.0.1+9-24) Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### Quarkus version or git rev

https://gitlab.com/iLem0n/grpcmutinyexample

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/ilem0n/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 16.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "11.1", arch: "x86_64", family: "mac"

**Comment by cescoffier** [comment]
I guess it's because the proto file is not included in the FlinkSessionReconciler project. Did you try adding it? 
We are working on easing the distribution of proto files.

**Comment by iLem0n** [comment]
Hello sorry for the late reply. 
Yes when I include the proto-files in both projects it works. 

So actually it's necessary to copy them around? Feels a little bit odd, but as far as I googled that's a common problem out there. 

Ok Anyway. Thanks for investigation.

**Comment by michalszynkiewicz** [comment]
I should have a pull request to add the support for proto files in dependencies this week

**Comment by lecodeski** [comment]
Since I have the very same issue in the current 2.14.1 – has the PR been merged yet?

**Comment by krmahadevan** [comment]
@michalszynkiewicz - Quickly checking if you managed to get  the PR to have this fixed ? I am currently using 

```xml
<quarkus.platform.version>2.15.1.Final</quarkus.platform.version>
```

and I noticed this error, when I tried creating a multi module maven project, wherein I had a specific module just to generate the protos and the other sub-modules (which are my microservices) tried depending on the `common-protos` module (which contains the proto generated code) and hit this exact same problem. The issue went away as soon as I added the protos back to `src/main/proto` of my microservices project.

Wanted to quickly check on the PR.

**Comment by lecodeski** [comment]
It seems to be still present in Quarkus 3. Any Updates on this?

**Comment by cescoffier** [comment]
We have added the possibility to embed protos in dependencies. So it should not be an issue. If it still a problem, please attach a reproducer.

**Comment by lecodeski** [comment]
I try it with `quarkus.generate-code.grpc.scan-for-proto=<groupId>:<artifactId>` but still it says it can't be injected during app launch.
I must admit the proto files are already used for generation in the dependency. Thus the generated java code is already included in the dependency. May that be the issue in my case?

**Comment by lecodeski** [comment]
But what would be actually the way to avoid generation in the dependency? It is happening already automatically, isn't it?

**Comment by lecodeski** [comment]
when I copy the proto files form the dependency to app's `<root>/src/main/proto` it's working fine 👌

**Comment by cescoffier** [comment]
So, you cannot rely on external generation. Mutiny services are a specific generation target.
