### ISSUE TITLE
Qute: InteliJ breaks qute templates syntax

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23287]
### Describe the bug

This tag works in Qute

```{#validation field='username'}{/validation}```

After reformat with InteliJ it looks like this:

```{#validation field = 'username'}{/validation}```

Now Qute gives me two errors: 

```
#1 Incorrect expression found: {field}
#2 Incorrect expression found: {=}
```

**Comment by mkouba** [comment]
I don't know why InteliJ does this kind of reformatting but it's definitely not a supported syntax in qute.
