### ISSUE TITLE
Guide for creating a Docker image with a custom Java 11 JRE

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#2328]
As Helidon describes in https://helidon.io/docs/latest/#/guides/04_dockerfile, it would be nice to see a Quarkus guide how to build an Docker image with a custom Java 11 JRE using ```jlink```

**Comment by rsvoboda** [comment]
Dockerfile for JVM mode is based on fabric8/java-alpine-openjdk8-jre which is 75MB small.
Quarkus getting-started example has size ~8MB, if more deps are added I think the size is still <20MB so it makes image size less than 100 MB for Quarkus app in JVM mode. 

Helidon example ends up with ~140MB.

I don't think there is any special need for further customization.

With native image you can go even further with https://github.com/quarkusio/quarkus-images/tree/graalvm-1.0.0-rc16/distroless and have 17 MB for the base + size of your app in native mode.

@cescoffier / @dmlloyd I think this could be closed, wdyt ?

**Comment by rsvoboda** [comment]
At the end of https://quarkus.io/guides/building-native-image-guide there is a note about the distroless version.

**Comment by jimbogithub** [comment]
A good reason for having a custom JRE is to be able to keep things slim but include jcmd (which can be done simply via jlink) for which you otherwise require the full JDK.
