### ISSUE TITLE
Qute: user defined tags not working with .qute.html extension

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23285]
### Describe the bug

Qute is using by convention extension .qute.html for templates

For example we have admin template ```/src/main/resources/templates/Admin/admin.qute.html``` and it works out of the box.

We can't do the same with user defined tags.

### Expected behavior

Adding template ```/src/main/resources/templates/tags/validation.qute.html``` should register tag ```validation```

### Actual behavior

Only template```/src/main/resources/templates/tags/validation.html``` is registering tag ```validation```

**Comment by kucharzyk** [comment]
@mkouba 

```java
        // Register user tags
        for (TemplatePathBuildItem path : templatePaths) {
            if (path.isTag()) {
                String tagPath = path.getPath();
                String tagName = tagPath.substring(TemplatePathBuildItem.TAGS.length(), tagPath.length());
                if (tagName.contains(".")) {
                    tagName = tagName.substring(0, tagName.lastIndexOf('.'));
                }
                builder.addSectionHelper(new UserTagSectionHelper.Factory(tagName, tagPath));
            }
        }
```

Shouldn't that be ``` tagName.indexOf('.')``` instead of ``` tagName.lastIndexOf('.')```?

**Comment by mkouba** [comment]
> Qute is using by convention extension .qute.html for templates

Well, Qute does not care about this convention but it's very useful for IDEs.

> Shouldn't that be tagName.indexOf('.') instead of tagName.lastIndexOf('.')?

Yes, it seems to be the case. Would you care to send a PR with a test? ;-)

**Comment by kucharzyk** [comment]
@mkouba I'll try to prepare PR with fix and test

**Comment by kucharzyk** [comment]
@mkouba  It's harder change that I thought.

https://github.com/quarkusio/quarkus/pull/23330

Templates with .qute.html extension can be registered after this change but it braeks tests

```java
public class UserTagIncludeTest {

    @RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .withApplicationRoot((jar) -> jar
                    .addAsResource(new StringAsset("{name}"),
                            "templates/tags/hello.txt")
                    .addAsResource(new StringAsset("{#include base}{#item}{#hello name=name /}{/item}{/include}"),
                            "templates/foo.txt")
                    .addAsResource(new StringAsset("{#insert item}NOK{/}"),
                            "templates/base.html"));

    @Inject
    Template foo;

    @Test
    public void testInjection() {
        assertEquals("OK", foo.data("name", "OK").render());
    }

}
```

Original test works without problems.

Test with different file extensions has parser errors

```
public class UserTagWithQuteExtensionIncludeTest {

    @RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .withApplicationRoot((jar) -> jar
                    .addAsResource(new StringAsset("{name}"),
                            "templates/tags/hello.qute.txt")
                    .addAsResource(new StringAsset("{#include base}{#item}{#hello name=name /}{/item}{/include}"),
                            "templates/foo.txt")
                    .addAsResource(new StringAsset("{#insert item}NOK{/}"),
                            "templates/base.html"));

    @Inject
    Template foo;

    @Test
    public void testInjection() {
        assertEquals("OK", foo.data("name", "OK").render());
    }

}
```

``` Parser error in template [foo.txt] on line 1: section block end tag [item] does not match the start tag [hello]```

How can be template location related to parsing - template is registered correctly as hello in both cases.

Am I missing something important?

**Comment by kucharzyk** [comment]
```java
        // Add tags
        for (String tag : tags) {
            // Strip suffix, item.html -> item
            String tagName = tag.contains(".") ? tag.substring(0, tag.indexOf('.')) : tag;
            String tagTemplateId = TAGS + tagName;
            LOGGER.debugf("Registered UserTagSectionHelper for %s [%s]", tagName, tagTemplateId);
            builder.addSectionHelper(new UserTagSectionHelper.Factory(tagName, tagTemplateId));
        }
```

I've found duplicated logic in EngineProducer

**Comment by kucharzyk** [comment]
@mkouba PR is ready: https://github.com/quarkusio/quarkus/pull/23330
