### ISSUE TITLE
Quarkus @ApplicationScoped working in dev run, but not in prod

### ISSUE THREAD

**Issue by LegendL3n** [quarkusio/quarkus#23282]
### Describe the bug

I have an abstract class, which has an implementation with @ApplicationScoped.

This works without an issue in `quarkusDev`, but when running the built app, it complains of a function that I have implemented in the abstract class.

`java.lang.VerifyError: class me.l3n.[...].GoodReadsCrawlerService_ClientProxy overrides final method me.l3n.bot.[...].CrawlerService .parseHtml(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; `

```kt
abstract class CrawlerService {
    protected suspend infix fun parseHtml(url: String): Document {
        /* ... */
    }
}

@ApplicationScoped
class GoodReadsCrawlerService: CrawlerService() {
    /* implements other abstract functions of base class */
}
```
Note that I'm not even overriding that `parseHtml()` function.

But if I change the GoodReadsCrawlerService to Singleton(), OR add the open keyword to `parseHtml()`, it works just fine in any case.

I'd assume the `ClientProxy` is treating the abstract class as an interface, so implements all functions for proxying, assuming they're all abstract.

But I believe this could be an issue with the prod proxy.

### Expected behavior

The proxy should have the same behavior in dev and prod environments when dealing with an abstract class implementing a method.

### Actual behavior

`java.lang.VerifyError: class me.l3n.[...].GoodReadsCrawlerService_ClientProxy overrides final method me.l3n.bot.[...].CrawlerService .parseHtml(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; `

Unless that method has the `open` keyword or the scope is changed to `Singleton`.

### How to Reproduce?

In Kotlin, create an abstract class with a method implementation, then extend it from another class, with the `@ApplicationScoped` annotation.

Test in `quarkusDev`, then running the app produced in `quarkusBuild`.

An example can be found in [my repo](https://github.com/LegendL3n/Pensador/commit/9a499367f08fefb8f75e408677209a6e0f504659).

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by stuartwdouglas** [comment]
@mkouba Could this be because of the additional interceptors that are applied in dev mode?

**Comment by mkouba** [comment]
> @mkouba Could this be because of the additional interceptors that are applied in dev mode?

I don't think so.

> But if I change the GoodReadsCrawlerService to Singleton(),

`@Singleton` works because we don't ceate a client proxy at all.

> OR add the open keyword to parseHtml(), it works just fine in any case.

So from CDI POV a normal scoped bean may not declare `final` methods (a type with a final method is not proxyable). In Quarkus, we try to relax this requirement and remove the `final` modifier if needed (and if `quarkus.arc.transform-unproxyable-classes=true`).

@stuartwdouglas Could it be that quarkus transformations are not taken into account when used together with kotlin?

**Comment by LegendL3n** [comment]
> Does the application work if `quarkus.arc.dev-mode.monitoring-enabled=false` is set?

It doesn't. (neither in dev nor prod modes)

**Comment by stuartwdouglas** [comment]
Do you have a reproducer that does not require a discord account?

**Comment by LegendL3n** [comment]
Just created one [here](https://github.com/LegendL3n/quarkus-kotlin-bug-reproducer).
