### ISSUE TITLE
Qute: Consistent behaviour for tags and include

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23292]
### Description

We can include another template using ```#include``` syntax.

```
 {#include foo limit=10 /} 
 ```
 
 for tags syntax is quite different
 
 ```
 {foo limit=10}{/foo}
 ```
 
 It would be great if tag ```{xxx limit=10}{/xxx}``` would be only a shorter syntax for ```{#include foo limit=10/}
 
 ```#include``` offers now more features than tags for example "transclusion" with ```#insert``` syntax.
 
 What do you think about unifying tag and include?

**Comment by mkouba** [comment]
> for tags syntax is quite different `{foo limit=10}{/foo}`

It's actually `{#foo limit=10 /}`

> #include offers now more features than tags for example "transclusion" with #insert syntax.

Duplicates https://github.com/quarkusio/quarkus/issues/22657.
