### ISSUE TITLE
Qute: Default values for tags

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23291]
### Description

It would be great if Qute supports default values for tag parameters

Syntax like this would allow use tags like real components like in angular or react

```
{@java.lang.Boolean showDetails=false}
```

Now we have to pass all params for each usage.

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/issues/21859 mentions default values as well.

**Comment by mkouba** [comment]
FTR a workaround exists (although it's not very nice ;-): 
```
{@java.lang.Boolean showDetails}
{#let showDetails=showDetails.or(false)}
...
{/let}
```
