### ISSUE TITLE
Opentracing logging not working with log4j2

### ISSUE THREAD

**Issue by jkalex-git** [quarkusio/quarkus#23306]
### Describe the bug

Opentracing logging values are not logged when log4j2 logger is used.
I have tested with jboss logging, log4j2 and slf4j. 
Issue is limited to log4j2 logging only.
All the tracing details(traceId, spanId, etc.) is coming empty in logs.

### Expected behavior

**Example logs:**
13:13:32 INFO  traceId=c42e07e99c316a07, spanId=c42e07e99c316a07, sampled=true [or.ac.op.TracedResource] (executor-thread-0) hello from jboss logging
13:13:32 INFO  traceId=c42e07e99c316a07, spanId=c42e07e99c316a07, sampled=true (executor-thread-0) hello from log4j
13:13:32 INFO  traceId=c42e07e99c316a07, spanId=c42e07e99c316a07, sampled=true [or.ac.op.TracedResource] (executor-thread-0) hello from slf4j

### Actual behavior

**Example logs:**
13:13:32 INFO  traceId=c42e07e99c316a07, spanId=c42e07e99c316a07, sampled=true [or.ac.op.TracedResource] (executor-thread-0) hello from jboss logging
13:13:32 INFO  traceId=, spanId=, sampled= [or.ac.op.TracedResource] (executor-thread-0) hello from log4j
13:13:32 INFO  traceId=c42e07e99c316a07, spanId=c42e07e99c316a07, sampled=true [or.ac.op.TracedResource] (executor-thread-0) hello from slf4j

### How to Reproduce?

Reproduced the issue using the below quickstart,
https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentracing-quickstart

Steps:

1. Add dependency in pom  ` <dependency>
      <groupId>org.jboss.logmanager</groupId>
      <artifactId>log4j2-jboss-logmanager</artifactId>
    </dependency>` 
2. Intialize logger in TracedResource.java `private static final org.apache.logging.log4j.Logger LOG4J = LogManager.getLogger(TracedResource.class);`
3. Add log4j log statement in hello() function ` LOG4J.info("hello from log4j");`

### Output of `uname -a` or `ver`

 5.11.0-34-generic #36~20.04.1-Ubuntu

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS

### Quarkus version or git rev

2.6.2.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by radcortez** [comment]
Closing this because we are no longer supporting OpenTracing.
