### ISSUE TITLE
Tracing additional methods in OpenTelemetry

### ISSUE THREAD

**Issue by jkalex-git** [quarkusio/quarkus#23307]
### Description

Possibility to trace additional methods other than REST calls.
Lack of this functionality prohibits from migrating to open telemetry from open tracing(which is deprecated).

### Implementation ideas

Functionality similar to 
https://quarkus.io/guides/opentracing#tracing-additional-methods

**Comment by radcortez** [comment]
This is already possible using the OTel `@WithSpan` annotation.
