### ISSUE TITLE
OpenApi: Config quarkus.smallrye-openapi.additional-docs-directory casues error if directory does not exist

### ISSUE THREAD

**Issue by serahl** [quarkusio/quarkus#23313]
### Describe the bug

Configure `quarkus.smallrye-openapi.additional-docs-directory` to point to a directory which does not exist (e.g. `META-INF/foldernamethatdoesnotexist` .
Then run Quarkus in dev mode or try running a @QuarkusTest with `mvn clean test`.

### Expected behavior

Quarkus should ignore the missing directory and not load any additional docs.

### Actual behavior

Quarkus throws an exception:

java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#configFiles threw an exception: java.lang.IllegalStateException: java.nio.file.NoSuchFileException: C:\dev\repo\...\target\classes\META-INF\openapi
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:896)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\dev\repo\...\target\classes\META-INF\openapi
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)

### How to Reproduce?

Set the given config property to point to a directory that does not exists and try to build/test the Quarkus project.

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Microsoft-28056 (build 17.0.1+12-LTS)

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

**Comment by phillip-kruger** [comment]
@serahl - I can not recreate this. Do you have a small reproducer I can look at ? It might be Windows specific.

**Comment by phillip-kruger** [comment]
@serahl - I could not recreate the issue on Linux and do not currently have a Windows Environment. This might fix it: https://github.com/phillip-kruger/quarkus/tree/additional-docs-fix but it would be great if you can test it. let me know. Thanks

**Comment by serahl** [comment]
@phillip-kruger I created a simple reproducer from the Quarkus Code Generator:
[openapi-folder-error.zip](https://github.com/quarkusio/quarkus/files/7994211/openapi-folder-error.zip)

Sadly I don't know when I'll have the time to check out, build and test your fix in the branch.

**Comment by serahl** [comment]
@phillip-kruger I managed to try out your fix. TL;DR: I don't think it's working :(

I built your branch with `./mvnw -Dquickly`.
After that, I changed the Maven properties of my example reproducer to `<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>` and `<quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>`.

When running `mvn clean package` in the sample project, I still get the same error/exception.

**Comment by serahl** [comment]
Quick note: The reproducer also fails on Debian under WSL, with the same error/exception:

...
Caused by: java.nio.file.NoSuchFileException: /mnt/c/Users/.../openapi-folder-error/target/classes/META-INF/foldernamethatdoesnotexist

**Comment by phillip-kruger** [comment]
@serahl ok thanks for checking. Let me see if I can spin up Windows and recreate the issue. I'll get back to you

**Comment by phillip-kruger** [comment]
Thanks for your help @serahl - the PR above fixes the issue
