### ISSUE TITLE
[Native] Locales bundles, ServiceLoader flow for JDK; e.g. Frankreich vs. France

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#23338]
### Describe the bug

This is a followup on: :lady_beetle:  #22808 **Including resource bundles for different languages doesn't work**

# The problem
Unless `quarkus.native.auto-service-loader-registration=true` is used, i.e. `-H:+UseServiceLoaderFeature`, to trigger [ServiceLoaderFeature](https://github.com/oracle/graal/blob/release/graal-vm/22.0/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ServiceLoaderFeature.java#L98) in Graal, JDK Locale bundles, e.g. `sun.util.resources.cldr.ext.LocaleNames_de` are not loaded.

The code in [ServiceLoaderFeature](https://github.com/oracle/graal/blob/release/graal-vm/22.0/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ServiceLoaderFeature.java#L98) is missing finer grained include/exclude, so it bloats the image too much when used.

The result is that it silently falls back to `sun.util.resources.LocaleNames` English defaults. To illustrate:

```
System.out.printf("English: %s\n", Locale.FRANCE.getDisplayCountry(Locale.ENGLISH));
System.out.printf("German: %s\n", Locale.FRANCE.getDisplayCountry(Locale.GERMAN));
System.out.printf("Italian: %s\n", Locale.FRANCE.getDisplayCountry(Locale.ITALIAN));
```
Should print:
```
English: France
German: Frankreich
Italian: Francia
```
and not
```
English: France
German: France
Italian: France
```

# The solution (Quarkus) :grey_question: 
Naively deferring to `RuntimeInitializedClassBuildItem` or using `ReflectiveClassBuildItem` to init e.g. 
```
sun.util.resources.LocaleData$SupplementaryResourceBundleProvider
sun.util.resources.provider.SupplementaryLocaleDataProvider
sun.util.resources.LocaleData$CommonResourceBundleProvider
sun.util.resources.provider.LocaleDataProvider
```
is not enough as it doesn't help with the ServiceLoader architecture used to populate these implementations.
Looking into `sun.util.resources.Bundles` and discovering Quarkus' `ServiceProviderBuildItem` lead to attempts at something like:
```
services.produce(
        new ServiceProviderBuildItem("sun.util.resources.LocaleDataProvider",
                "sun.util.resources.LocaleData$CommonResourceBundleProvider"));
 services.produce(
        new ServiceProviderBuildItem("sun.util.resources.provider.SupplementaryLocaleDataProvider",
                "sun.util.resources.LocaleData$SupplementaryResourceBundleProvider"));

or...?

services.produce(
        new ServiceProviderBuildItem(
                 "sun.util.resources.LocaleData$CommonResourceBundleProvider",
                  "sun.util.resources.LocaleDataProvider"));
services.produce(
         new ServiceProviderBuildItem(
                 "sun.util.resources.LocaleData$SupplementaryResourceBundleProvider",
                  "sun.util.resources.provider.SupplementaryLocaleDataProvider"));
```
It does not help either.

Examining some extensions such as `liquibase-mongodb` shows me that ServiceLoaders are successfully runtime-inited in Native image elsewhere, although none of these usages touch JDK's own code.

WIP, I will keep digging around, building `core/deployment/src/main/java/io/quarkus/deployment/steps/LocaleProcessor.java` that would runtime init ServiceLaoders to produce desired locales. No luck so far.

Note that having this is required:
```
        resources.produce(new NativeImageResourceBundleBuildItem("sun.util.resources.LocaleNames"));
```
and yet doing anything like:
```
        resources.produce(new NativeImageResourceBundleBuildItem("sun.util.resources.ext.LocaleNames_de"));
        resources.produce(new NativeImageResourceBundleBuildItem("sun.util.resources.cldr.ext.LocaleNames_de"));
```
does not help.

# The solution (Graal) :grey_question: 
It might be also addressable on the Graal's side and apparently, someone already put some thought to it:
From  [ServiceLoaderFeature](https://github.com/oracle/graal/blob/release/graal-vm/22.0/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ServiceLoaderFeature.java#L98):

>         // TODO write a more sophisticated include/exclude filter to handle cases like GR-27605 ?

So perhaps, instead of registering hundreds of services via all ServiceLoaders found all over the place with the hammer like `-H:+UseServiceLoaderFeature`, I could patch it do something akin to: `-H:+UseServiceLoaderFeature=include:sun.util.resources.LocaleData$CommonResourceBundleProvider,sun.util.resources.LocaleData$SupplementaryResourceBundleProvider` to enable just what is apparently needed in this particular case?

Note that while we use countries' names to illustrate the issue here, it would be likely the same for the names of currencies etc.

**Comment by Sanne** [comment]
Would it be possible to automatically register the required Locals (and only the required ones) by triggering registration of the individual resources based on e.g. `Locale.FRANCE` being reachable?

**Comment by gsmet** [comment]
Note that I created `quarkus.locales` and `quarkus.default-locale` a long time ago for the needs of HV.

See `LocalesBuildTimeConfig`.

But it looks like we have a more important issue than that :).

**Comment by Karm** [comment]
I am going to implement suggestions from Zulip chat and give it another go.

**Comment by Karm** [comment]
I have a fix in core. I am refactoring it to use the currently existing `quarkus.locales` as an indication the user is interested in non-English locales. I need to test what Hibernate Validator does with it so as there are no surprises....
