### ISSUE TITLE
Reactive Messaging (RabbitMQ) - too many connection

### ISSUE THREAD

**Issue by nuty456** [quarkusio/quarkus#23331]
### Describe the bug

smallrye-reactive-messaging-rabbitmq create as many connections to rabbit server as @Channel and @Incoming are used in application.

### Expected behavior

Expected to use some pool or less connections 1-2 for application.

### Actual behavior

smallrye-reactive-messaging-rabbitmq create as many connections to rabbit server as @Channel and @Incoming are used in application.

### How to Reproduce?

application.properties

rabbitmq-host=server_hostname
rabbitmq-port=5672
rabbitmq-username=server_username
rabbitmq-password=server_password

# Configuring the incoming channel (reading from AMQP)
mp.messaging.incoming.test-in.connector=smallrye-rabbitmq
mp.messaging.incoming.test-in.queue.name=test
mp.messaging.incoming.test-in.exchange.name=test

# Configuring the outgoing channel (writing to AMQP)
mp.messaging.outgoing.test-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.test-out.exchange.name=test

# Configuring the incoming channel (reading from AMQP)
mp.messaging.incoming.test1-in.connector=smallrye-rabbitmq
mp.messaging.incoming.test1-in.queue.name=test1
mp.messaging.incoming.test1-in.exchange.name=test1

# Configuring the outgoing channel (writing to AMQP)
mp.messaging.outgoing.test1-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.test1-out.exchange.name=test1

@Path("/hello")
class GreetingResource {

    @Channel("test-out")
    var emitter: Emitter<String>? = null

    @Channel("test1-out")
    var emitter1: Emitter<String>? = null

    @GET
    @Path("/rabbit")
    @Produces(MediaType.TEXT_PLAIN)
    fun hellorabbit(): String {
        emitter?.send("sending test message")
        return "DONE"
    }

    @GET
    @Path("/rabbit1")
    @Produces(MediaType.TEXT_PLAIN)
    fun hellorabbit1(): String {
        emitter1?.send("sending test message1")
        return "DONE"
    }
}

@ApplicationScoped
class QuoteProcessor {

    @Incoming("test-in")
    fun process(mess: String) {
        println("Message received: $mess")
    }

    @Incoming("test1-in")
    fun process1(mess: String) {
        println("Message received1: $mess")
    }
}

### Output of `uname -a` or `ver`

Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

### GraalVM version (if different from Java)

openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1) OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)

### Quarkus version or git rev

2.7.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)

**Comment by cescoffier** [comment]
@kdubb Can you have a look?

**Comment by kdubb** [comment]
This is a function of the VertX client. Each `RabbitMQClient` uses a connection and has no support for a connection pool or sharing a connection between clients.

**Comment by cescoffier** [comment]
thanks @kdubb 
Closing it as won't fix. If this feature is required, please open an issue on the vert.x rabbitmq client github repository.
