### ISSUE TITLE
Error parsing Kotlin data class

### ISSUE THREAD

**Issue by amsterdam-superchat** [quarkusio/quarkus#23342]
### Describe the bug

When using a simple Kotlin data class like this one

```kotlin
data class Payload(
    val names: List<String>,
)
```

In a resteasy reactive resource like this 

```kotlin
@Path("/hello")
class ReactiveGreetingResource {

    @POST
    @Produces(MediaType.TEXT_PLAIN)
    fun hello(payload: Payload): Uni<String> {
        return Uni.createFrom().item(payload.names.joinToString())
    }
}
```

A 500 error is thrown, with any error message.

### How to Reproduce?

Reproducer created here https://github.com/amsterdam-superchat/quarkus-kotlin-payload-error

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/23345 will fix the logging issue.

As for the the actual problem, the issue is you are missing the `com.fasterxml.jackson.module:jackson-module-kotlin` dependency
