### ISSUE TITLE
Identify JVM version / GraalVM version in Quarkus log

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2335]
More and more users are exploring native image, Quarkus is usually checked with certain version of GraalVM, plus there are issues related to certain GraalVM version.

I think it would be nice to identify JVM version / GraalVM version in Quarkus log.
Can be handy for investigation. Maybe even in production to see on what an app is based.

A) Additional log entry
B) Extending `INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.010s. Listening on: http://[::]:8080` entry

Initial proposal for A:
* JVM mode: `INFO  [io.quarkus] (main) Running on Java HotSpot(TM) 64-Bit Server VM - 11.0.2+7-LTS`
* Native mode: `INFO  [io.quarkus] (main) Application was built using GraalVM 1.0.0-rc16 CE`

Initial proposal for B:
* JVM mode: `INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM - 11.0.2+7-LTS) started in 1.110s. Listening on: http://[::]:8080`
* Native mode: `INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT (GraalVM 1.0.0-rc16 CE) started in 0.010s. Listening on: http://[::]:8080`

**Comment by emmanuelbernard** [comment]
It would be nice to not clutter the logs too much. Can we at least make this DEBUG level?

**Comment by gsmet** [comment]
Closing for now. Let's wait for users complaints with a real use case and decide from that.
