### ISSUE TITLE
Current version of graal-sdk contains several vulnerabilities

### ISSUE THREAD

**Issue by Dennis-Nilsson** [quarkusio/quarkus#23366]
https://github.com/quarkusio/quarkus/blob/3e61beaf61737e72ee748bb086506009adf00175/bom/application/pom.xml#L86

org.graalvm.sdk:graal-sdk@21.3.0 contains several vulnerabilities:
![bild](https://user-images.githubusercontent.com/79633588/152146036-11c09ff9-7cb0-47ae-a089-7945eee6e0c7.png)

io.quarkus:quarkus-arc@2.6.3.Final > io.quarkus:quarkus-core@2.6.3.Final > org.graalvm.sdk:graal-sdk@21.3.0

Upgrade org.graalvm.sdk:graal-sdk to version 20.3.5, 21.3.1 or higher.

**Comment by gsmet** [comment]
We already upgraded to 21.3.1 for Quarkus 2.7.1.Final (that we will release next week) and 22.0.0.2 for `main`.
