### ISSUE TITLE
Parent console log handler handles log despite use-parent-handlers set to false in child

### ISSUE THREAD

**Issue by PierreBtz** [quarkusio/quarkus#23361]
### Describe the bug

After configuring a specific handler for a package that should not send its output to its parent:

```
quarkus.log.category."eu.pierrebeitz".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %s%e%n

# define a specific handler for the svc package
# it should not sent its output to the root logger
quarkus.log.handler.console."SVC_HANDLER".format=%s%e%n
quarkus.log.category."eu.pierrebeitz.svc".level=DEBUG
quarkus.log.category."eu.pierrebeitz.svc".handlers=SVC_HANDLER
quarkus.log.category."SVC_HANDLER".use-parent-handlers=false
```

I notice that the log appears twice in the console:

```
Logging from the service --> this matches the format set for the child (see configuration above)
2022-02-02 10:31:35,070 INFO  Logging from the service --> this matches the root configuration
```

See full reproduction in https://github.com/PierreBtz/quarkus-logger-handler-bug

Steps to reproduce:

* `mvn quarkus:dev`, then observe the output:

```
2022-02-02 10:31:35,061 INFO  Logging from the command
Logging from the service
2022-02-02 10:31:35,070 INFO  Logging from the service
```

### Expected behavior

When setting `use-parent-handlers` to false only the `SVC_HANDLER` handles the logs for the `eu.pierrebeitz.svc` package.

### Actual behavior

The root logger handles the logs from the `eu.pierrebeitz.svc` package.

### How to Reproduce?

* clone `https://github.com/PierreBtz/quarkus-logger-handler-bug`
* `mvn quarkus:dev`, then observe the output:

```
2022-02-02 10:31:35,061 INFO  Logging from the command
Logging from the service
2022-02-02 10:31:35,070 INFO  Logging from the service
```

### Output of `uname -a` or `ver`

Darwin Pierres-MacBook-Pro-2.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

### Quarkus version or git rev

2.6.3.Final (and also 2.7.0.CR1)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

I tested with `2.7.0.CR1` out of curiosity and observed the same behavior.

**Comment by geoand** [comment]
In your configuration you have:

```
quarkus.log.category."SVC_HANDLER".use-parent-handlers=false
```

That is wrong. It needs to be:

```
quarkus.log.category."eu.pierrebeitz.svc".use-parent-handlers=false
```

**Comment by PierreBtz** [comment]
Arf... sorry about that, I must have starred at this configuration for an hour without spotting this...

Thanks for the help!

**Comment by geoand** [comment]
YW
