### ISSUE TITLE
Current H2 version contains vulnerability

### ISSUE THREAD

**Issue by Dennis-Nilsson** [quarkusio/quarkus#23364]
https://github.com/quarkusio/quarkus/blob/ebf059cc701fb63eb8e667246f91691faeea2c14/bom/application/pom.xml#L118

Current H2 version contains vulnerability. Should be updated to 2.1.210. 

See release notes for more information: https://github.com/h2database/h2database/releases/tag/version-2.1.210

**Comment by famod** [comment]
Related: #9354

/cc @Sanne @gsmet 
PS: I wasn't able to test it yet

**Comment by geoand** [comment]
Let's close this as a duplicate of #9354
