### ISSUE TITLE
Broken pipe (Write failed) using Hibernate ORM and MariaDB

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#2336]
Using ```quarkus-hibernate-orm``` along with ```quarkus-jdbc-mariadb``` with the following application.properties doesn't always work after the application been idle for a few hours. After the application been idling during the night the first few transaction fails (see stacktrace). Could it be that stale connections doesn't get evicted from the connection pool properly? 

(Quarkus version 0.14.0, MariaDB 10.2.15, MacOS Mojave and OpenJDK Runtime Environment 18.9 build 11+28)

```
quarkus.datasource.url=jdbc:mariadb://some-url...
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MariaDB102Dialect
quarkus.datasource.background-validation-interval=PT1M
quarkus.datasource.idle-removal-interval=PT1M
quarkus.datasource.username=someUserName
quarkus.datasource.password=somePwd
```

![stacktrace](https://user-images.githubusercontent.com/4103786/57136237-75394200-6dac-11e9-901f-6b826ced587c.png)

**Comment by gsmet** [comment]
@barreiro does it ring any bell?

**Comment by Sanne** [comment]
I'm guessing this could be related to Agroal's background health check for JDBC connections. @barreiro @stalep ?

**Comment by stalep** [comment]
hm, @barreiro is on PTO this week, but I know he implemented a `maxLifeTime` feature in Agroal 1.5. Before that it never timed out AFAIK which do look like this issue here. @enbohm do you mind testing with the latest version of Quarkus? I know we use Agral 1.5 in that version.

**Comment by enbohm** [comment]
@stalep sure - I will update to the latest version and see the result. I'll keep you posted, thx!

**Comment by stalep** [comment]
@gsmet do we have a `quarkus.datasource.max-life-time` or something similar for connections in Quarkus now or a default maxLifeTime?

**Comment by gsmet** [comment]
I don't think it got implemented. I'm creating an issue.

But that being said, isn't Agroal supposed to test the connections regularly anyway?

**Comment by enbohm** [comment]
@stalep just checked the logs from my Quarkus 0.18.0 service and unfortunately the issue is still there

**Comment by gsmet** [comment]
We need to check if the connections are properly validated by the Agroal logic.

**Comment by Sanne** [comment]
> just checked the logs from my Quarkus 0.18.0 service and unfortunately the issue is still there

@enbohm did you enable the new configuration properties?

```
quarkus.datasource.max-life-time 
```

And how did you set other existing properties? These could be related, but I guess we could use to see them all.
```
quarkus.datasource.background-validation-interval
quarkus.datasource.idle-removal-interval
```

**Comment by enbohm** [comment]
@Sanne 

These are the properties I have
```
quarkus.datasource.url=jdbc:mariadb://some-url...
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MariaDB102Dialect
quarkus.datasource.background-validation-interval=PT1M
quarkus.datasource.idle-removal-interval=PT1M
quarkus.datasource.username=someUserName
quarkus.datasource.password=somePwd
```

I have not tried
```
quarkus.datasource.max-life-time
```
but will enabled it and see the outcome. Will update with the result within a few days, ok?

**Comment by Sanne** [comment]
@enbohm that would be great, thanks!

**Comment by yrodiere** [comment]
@enbohm @Sanne I can confirm it's a bug. I just sent a PR.
