### ISSUE TITLE
Could not find snakeyaml-1.30-android.jar in Quarkus 2.7.0.Final

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#23371]
### Describe the bug

Get the following error when trying to run with Quarkus `2.7.0.Final`:

```
Could not find snakeyaml-1.30-android.jar (org.yaml:snakeyaml:1.30).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.30/snakeyaml-1.30-android.jar
```

Following the link, seems to not exist in Maven

gradle.properties:

```
quarkusPluginId=io.quarkus
quarkusPluginVersion=2.7.0.Final
quarkusPlatformVersion=2.7.0.Final
quarkusPlatformGroupId=io.quarkus
quarkusPlatformArtifactId=quarkus-universe-bom
org.gradle.logging.level=INFO
```

### How to Reproduce?

Assuming it is a dependency of the yaml config extension, and happens on build.

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by geoand** [comment]
What extensions are you using?

IIRC, you had this problem in the past and I could never reproduce it, correct?

**Comment by GregJohnStewart** [comment]
I actually was able to figure out how to reproduce that similar error, outlined here: https://github.com/quarkusio/quarkus/issues/22842

But I believe this to be a separate issue; in this case the jar isn't even on Maven Central

Extensions:

```
    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-mongodb-panache'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-smallrye-jwt-build'
    // https://quarkus.io/guides/security-properties
    implementation 'io.quarkus:quarkus-elytron-security'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-qute'
    implementation 'io.quarkus:quarkus-resteasy-qute'
    implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-smallrye-opentracing'
    implementation 'io.opentracing.contrib:opentracing-mongo-common'
    implementation 'io.quarkus:quarkus-container-image-jib'

    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
```

**Comment by geoand** [comment]
A sample Gradle application with those dependencies worked for me.

**Comment by GregJohnStewart** [comment]
Odd.... and my usual fix of nuking maven local isn't working either.. What does your `repositories` section look like?

**Comment by gsmet** [comment]
@GregJohnStewart it would be easier for us if you could create a small reproducer.

**Comment by geoand** [comment]
> What does your repositories section look like?

Just what code.quarkus.io populates, I didn't make any changes other than adding the deps you mention.

**Comment by geoand** [comment]
> it would be easier for us if you could create a small reproducer.

something tells me that we won't be able to reproduce it in any case :)

**Comment by GregJohnStewart** [comment]
Alright, found the culprit..... 

When I include JavaFaker, that triggers the error:

`testImplementation group: 'com.github.javafaker', name: 'javafaker', version: '1.0.2'`

**Comment by geoand** [comment]
Gotcha.

Closing this as that is not something we support

**Comment by GregJohnStewart** [comment]
Reproducer: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/tree/main/software/plugins/open-qm-plugin-demo

**Comment by GregJohnStewart** [comment]
For others might having a similar issue, apparently JavaFaker is a dead project; using DataFaker is a maintained fork:

https://github.com/datafaker-net/datafaker
