### ISSUE TITLE
Quarkus OIDC session cookie encryption support

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#23373]
### Discussed in https://github.com/quarkusio/quarkus/discussions/23365

<div type='discussions-op-text'>

<sup>Originally posted by **debu999** February  2, 2022</sup>
While using Quarkus-OIDC it seems raw access token and id token is stored in browser cookies. Can that be encrypted to make it more secured. We usually are discouraged to have raw token exposed to the client or store in browser. 
Is there anything to do to make a encryption decryption layer added to the cookie possibly a encryption key to be added to config to do encryption and decryption under the hood.</div>

**Comment by debu999** [comment]
Thanks for the update. Will try out with 2.8 once it's made available.
