### ISSUE TITLE
ResteasyReactiveScanner.scanForApplicationClass does not seem to handle excludes correctly

### ISSUE THREAD

**Issue by johnoliver** [quarkusio/quarkus#23379]
### Describe the bug

I may be incorrect on my understanding of what should be correct behaviour here, however, the logic of `ResteasyReactiveScanner.scanForApplicationClass` seems to mean that if there are multiple Application classes, the method will exit at:

```
            if (selectedAppClass != null) {
                throw new RuntimeException("More than one Application class: " + applications);
            }
```

however the `excludedClasses` list does not seem to be examined, meaning if you have multiple Application classes on your classpath it is impossible to use exclusions to remove one of them.

### Expected behavior

If you have multiple Application classes, however all but 1 are excluded, do not throw an error and use the 1 Application class.

### Actual behavior

If multiple Application classes are present, no matter what configuration you specify the application/build will fail.

**Comment by geoand** [comment]
You are absolutely right!

I opened https://github.com/quarkusio/quarkus/pull/23402 to fix this
