### ISSUE TITLE
`quarkus-kubernetes` fails when using Git submodules.

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#23399]
### Describe the bug

Any use of Git submodules causes a build crash when using `quarkus-kubernetes`; to which there is no workaround.

The cause is a parsing bug in Dekorate. I've filed a PR to fix the issue in the Dekorate repository (https://github.com/dekorateio/dekorate/pull/852).

This issue is to document the bug and track it's fix when a fixed dekorate is released. 

### Expected behavior

Gut submodules can be used.

### Actual behavior

Using Git Submodules causes an irrecoverable build crash.

### How to Reproduce?

Use Git submodules in any project along with `quarkus-kubernetes`.

### Output of `uname -a` or `ver`

macOS 12.1

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by iocanel** [comment]
I will look into it ASAP

**Comment by geoand** [comment]
There already is a PR upstream
