### ISSUE TITLE
@ClientExceptionMapper not working reliably

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#23396]
### Describe the bug

I was trying the new `@ClientExceptionMapper` in quarkus 2.7.0. I have another ExceptionMapper with a lower priority than the `@ClientExceptionMapper`.

When I use mvn quarkus:dev and force the exception. Sometimes it goes through the ClientExceptionMapper, sometimes it goes to the other ExceptionMapper with a lower priority.

Seems like sometimes the app starts "right" so it will always use the right mapper, and sometimes it starts "wrong" and I always get the exception from the lower priority ExceptionMapper

IMPORTANT: mvn quarkus:dev needs to be run multiple times, If the app is in a working state, looks like it will always work, and the opposite is also true.

### Expected behavior

It should never reach the exception mapper. It should always reach the ClientExceptionMapper

### Actual behavior

Sometime it reaches the ExceptionMapper sometimes it reaches the ClientExceptionMapper.

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-reproducer-clientexceptionmapper

To reproduce;
1. mvn quarkus:dev
2. GET http://localhost:8080/hello/test
3. Check if exception contains "FROM CLIENT" OK
3 redo step 1,2,3 sometimes the exception will be "FROM MAPPER" Wrong

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/23401 fixes the issue
