### ISSUE TITLE
Infinispan continuous Query does not work

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#23409]
### Describe the bug

Continuous query does not work on Quarkus.

### Expected behavior

Consume events and call the java methods

### Actual behavior

Throw "unexpected error consuming event".

Tested with Quarkus 2.7.0 and 2.6.3

### How to Reproduce?

Steps:

1. git clone https://github.com/viniciusfcf/quarkus-issues
2. cd infinispan-continuous-query
3. mvn quarkus:dev (with docker running)
4. Access http://localhost:8080/infinispan/put
5. See stack trace on console

### Output of `uname -a` or `ver`

Darwin vflorent-mac 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.7.0 or 2.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/vflorent/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/vflorent/.sdkman/candidates/java/11.0.11.hs-adpt Default locale: pt_BR, platform encoding: UTF-8 OS name: "mac os x", version: "11.1", arch: "x86_64", family: "mac"

### Additional information

![Uploading image.png…]()

**Comment by karesti** [comment]
working on it

**Comment by karesti** [comment]
I could not reproduce the issue anymore using the listener and the projection!

**Comment by karesti** [comment]
https://github.com/viniciusfcf/quarkus-issues/pull/1/
