### ISSUE TITLE
Resteasy Reactive serializes objects differently than Resteasy

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#23418]
### Describe the bug

I have the following object which I return via a resource and serialize with Jackson.

With Resteasy the following JSON is generated:

```json
{
   "name":"Quarkus T-Shirt",
   "price":{
      "amount":12,
      "currency":"EUR"
   }
}
```

But when I use Resteasy Reactive, the object is generated as follows:
```json
{
   "name":"Quarkus T-Shirt",
   "price":{
      "amount":12,
      "currency":{
         "context":{
            "empty":false,
            "providerName":"java.util.Currency"
         },
         "defaultFractionDigits":2,
         "currencyCode":"EUR",
         "numericCode":978
      }
   }
}
```

### Expected behavior

The JSON generated by Resteasy Reactive should look exactly like the one generated by Resteasy

### How to Reproduce?

https://github.com/andlinger/quarkus-reproducer/tree/quarkus-23418-2

### Quarkus version or git rev

Tested with 2.7.0.Final and 2.6.3.Final

**Comment by geoand** [comment]
This should simply be a matter of registering the money module with the Jackson ObjectMapper.

I guess RESTEasy Classic is doing it automatically...

**Comment by andlinger** [comment]
The reproducer project already contains a ObjectMapperCustomizer 
https://github.com/andlinger/quarkus-reproducer/blob/quarkus-23418/quarkus/src/main/java/io/i15s/quarkus/MoneyObjectMapperCustomizer.java

Without registering the MoneyModule it would not work in the Resteasy Classic either

**Comment by andlinger** [comment]
I updated the [Reproducer project ](https://github.com/andlinger/quarkus-reproducer/tree/quarkus-23418-2)(using Resteasy Reactive) with the following example:

```java

@Path("/product")
@RequestScoped
public class ProductResource {

    @Inject
    ObjectMapper mapper;

    @GET
    @Path("/mapper")
    @Produces(MediaType.APPLICATION_JSON)
    public String mapper() throws JsonProcessingException {
        var product = new Product();
        product.setName("Quarkus T-Shirt");
        product.setPrice(Money.of(12, "EUR"));

        return mapper.writeValueAsString(product);
    }

    @GET
    public Product get() {
        var product = new Product();
        product.setName("Quarkus T-Shirt");
        product.setPrice(Money.of(12, "EUR"));

        return product;
    }
}

```

The mapper() method produces the correct result:

```json
{
   "name":"Quarkus T-Shirt",
   "price":{
      "amount":12,
      "currency":"EUR"
   }
}
```

The get() method produces following:

```json
{
   "name":"Quarkus T-Shirt",
   "price":{
      "amount":12,
      "currency":{
         "context":{
            "empty":false,
            "providerName":"java.util.Currency"
         },
         "defaultFractionDigits":2,
         "currencyCode":"EUR",
         "numericCode":978
      }
   }
}
```

**Comment by geoand** [comment]
I'll take a closer look tomorrow

**Comment by geoand** [comment]
There was a bug in the Money Jackson module (that I had actually [fixed](https://github.com/zalando/jackson-datatype-money/pull/283) 🤦🏼).

If you update your reproducer to use `1.3.0` instead of `1.2.1`, everything works as expected

**Comment by geoand** [comment]
And actually you had even opened https://github.com/quarkusio/quarkus/issues/16081 :)

**Comment by andlinger** [comment]
Ohh sorry. I forgot. Sorry for stealing you time!

**Comment by geoand** [comment]
NP
