### ISSUE TITLE
2.7 Migration guide should include a new jaxb related requirement

### ISSUE THREAD

**Issue by israelst11** [quarkusio/quarkus#23416]
### Description

we migrated from 2.6.2 to 2.7.0 and suddenly lost our javax.xml.bind.* dependencies. 
We then realized we needed to add the quarkus-jaxb dependency.

This can be added to the [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guides).

**Comment by gsmet** [comment]
I'm not sure what's going on there but this extension is there since forever.

My guess is that you had a dependency somehow requiring the JAXB dependency and now it doesn't depend on it. If you want to know which one, compare the dependency trees.
