### ISSUE TITLE
Management interface and port

### ISSUE THREAD

**Issue by evilezh** [quarkusio/quarkus#23429]
### Description

I wanted to elaborate a bit on https://github.com/quarkusio/quarkus/issues/7893. 

Management port is security requirement/feature. I think - no matter of kubernetes or other context.
As part of health check we might expose some information we wouldn't like normally share.

Exposing health check or metrics on ingress or service is pointless as it is per pod.

I quite commonly run two different TLS/mTLS configurations, we might enable mTLS for main port, while I do not need it for health checks. And kubernetes do not support mTLS out of box for health checks. 

Of course there is always some kind of custom tricky workaround, but it would be much easier to have such mgmt port and capability to bind some beans to it. As I can write much more internal functionality. 

Currently it is kind of spinning up own web server and exposing everything we need on it. But really would be nice to have such thing integrated in overall design.

**Comment by geoand** [comment]
cc @sberyozkin @cescoffier

**Comment by cescoffier** [comment]
I completely agree. I will even push the requirement even further: it should be possible to move management endpoints to a separate port and interface. 

The current solution eases the routing strategy to avoid exposing the management endpoints to the public internet, but that was just a first step.

**Comment by cescoffier** [comment]
And yes both interface / port should be able to use TLS / mTLS. mTLS is particularly interesting for the management endpoints as you can limit / scope who can call these APIs.

**Comment by jogueber** [comment]
Would there be an outline on how that would be implemented @cescoffier ? 
I could pitch in if help is needed since we need this as well

**Comment by cescoffier** [comment]
It's relatively straightforward.

At the moment, Quarkus APIs are composed of two _sub-routers_: the application router and the non-application router (management). Both routers are registered on the primary router exposed by the Quarkus HTTP server.

So, the distinction between management and application is already there. You can see this distinction already as the management router uses the "/q" prefix. 

Thus, to expose the management API on a separate interface/port, we need to start a second HTTP server (in quarkus-vertx-HTTP) on a particular interface/port and register the management router to this server. It would only be enabled by configuration. TLS configuration will also be configurable (I have some work in progress regarding TLS).

**Comment by jogueber** [comment]
cool maybe I will find some time in the next days :) 
thanks @cescoffier

**Comment by jogueber** [comment]
Just as a question: Do I have to have a second `VertxHttpRecorder` 
I get that I can have seperate `BuildItem` that registers everything from the framework router 
But how do I start another server then ?

**Comment by cescoffier** [comment]
I would have added the logic to the same recorder, to create a second http server (if needed). However, you can use a second recorder if that's simpler.

I would start by locating where the management router is attached to the main router, and just before that check if we need to create a second server.

**Comment by mschorsch** [comment]
+1

**Comment by evilezh** [comment]
qq, any moevement with this. I want to move away from spring boot, but this little enhancment is holding back. :)

**Comment by cescoffier** [comment]
There are some ongoing discussions: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Non-application.20endpoints.20on.20different.20port.

**Comment by andreaTP** [comment]
Hi @cescoffier and all,
we have been discussing the importance of this feature in the Keycloak team, is there any progress on it?
Are you looking for contributions or anything else?

Thanks in advance!

**Comment by cescoffier** [comment]
Yes, I never had the time to look into it. It's a change that requires a bit of thinking, such as allowing "routes" to decide if they want to be on the main /q router, or on the admin interface instead (or both). It's not hard, I just never had the time to do it.

**Comment by andreaTP** [comment]
@cescoffier summarizing here the fixed points we agreed on 🙂 :
- start with implementing (only) one "management server/port"
- routes have an option to be bound to management but default to the main
- a secondary server will be spawned for the management port
- the management port can be enabled/disabled

with this in mind we can try to prototype a follow-up step and count on some level of guidance to proceed.
Please feel free to suggest corrections to this summary if I missed miss-interpreted anything 🙏
