### ISSUE TITLE
OpenShift extension failing to build

### ISSUE THREAD

**Issue by someth2say** [quarkusio/quarkus#23438]
### Describe the bug

A simple resteasy reactive project fails to build when adding the `quarkus-openshift` extension.

Remarkably, the project folder includes a Git submodule.
```
❯ git submodule status
 64b2200b174566321eb69bb5f029ba4defeae1b7 vale-styles (heads/master)
```

### Expected behavior

The project should build successfully (and later deploy into OCP)

### Actual behavior

```
> mvn clean package
...
[INFO] --- quarkus-maven-plugin:2.7.0.Final:build (default) @ vale-server ---
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.284 s
[INFO] Finished at: 2022-02-04T13:31:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.0.Final:build (default) on project vale-server: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: io.dekorate.DekorateException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.dekorate.knative.config.EditableKnativeConfig["project"]->io.dekorate.project.EditableProject["scmInfo"]->io.dekorate.project.EditableScmInfo["remote"]->java.util.LinkedHashMap["null"])
```

### How to Reproduce?

Create a Git Quarkus project with the `openshift` extension, and add a git submodule:
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=openshift-quickstart \
    -Dextensions="resteasy,openshift"
...
cd openshift-quickstart
git init
git submodule add ...

./mvnw package -DskipTests
```

### Output of `uname -a` or `ver`

Linux localhost.localdomain 5.15.12-100.fc34.x86_64 #1 SMP Wed Dec 29 15:21:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 16.0.1 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9) Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled) OpenJ9   - b4cc246d9 OMR      - 162e6f729 JCL      - cea22090ecf based on jdk-16.0.1+9)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/jordisola/.sdkman/candidates/maven/current Java version: 16.0.1, vendor: AdoptOpenJDK, runtime: /home/jordisola/.sdkman/candidates/java/16.0.1.j9-adpt Default locale: en_GB, platform encoding: UTF-8 OS name: "linux", version: "5.15.12-100.fc34.x86_64", arch: "amd64", family: "unix"

**Comment by iocanel** [comment]
I think that this issue has been fixed since the last upgrade to dekorate 2.9.0 so this need to be closed.
