### ISSUE TITLE
2.7.0.Final is breaking mongo+srv:// in native mode

### ISSUE THREAD

**Issue by krisgerhard** [quarkusio/quarkus#23433]
### Describe the bug

Yes yes, I know - it was supposed to be the first version where this is supported but for me it is the exact opposite.
I've successfully used mongo+srv:// connection string in native mode over a year and started getting problems when 2.7.0.Final was released. Reason being -> "JNDI disabled by default".

I don't think it's a code bug but rather I find the release notes misleading.

- mongo+srv:// support in native executables
☝️ it might be true if you are using quarkus-mongodb-client extension. But for every other application it's the opposite.

My mongo driver comes from KMongo with Kotlinx serialization.
```
<dependency>
  <groupId>org.litote.kmongo</groupId>
  <artifactId>kmongo-serialization</artifactId>
  <version>4.4.0</version>
</dependency>
```

### Actual behavior

```
com.mongodb.MongoClientException · Unable to support mongodb+srv// style connections as the 'com.sun.jndi.dns.DnsContextFactory' class is not available in this JRE. A JNDI context is required for resolving SRV records.
...
...
...
javax.naming.NamingException · JNDI has been disabled, enable it with quarkus.naming.enable-jndi=true
```

### Quarkus version or git rev

2.7.0.Final

**Comment by loicmathieu** [comment]
If you're not using our MongoDB support and needs JNDI, you must enable it via `quarkus.naming.enable-jndi=true` as explained in the exception message.

This is not related to MongoDB at all, we decided to disable JNDI by default on Quarkus.

**Comment by geoand** [comment]
Closing this as the error message is very explicit

**Comment by krisgerhard** [comment]
I can't wrap my head around how is 
> mongo+srv:// support in native executables
a new refinement/feature in this release.

All that was done was not to break a support for a feature that was already working previously.

Release notes is misleading. Migration guide should mention that using Mongo extension now enables jndi globally.

**Comment by loicmathieu** [comment]
@krisgerhard `mongo+srv://` was not working previously on native images, it cannot as it uses JNDI for the DNS query under the hood. The new release brings a substrat VM substitution to replace the uses of JNDI by Vert.x DNS client.

Even if you don't use our MongoDB support, you can still incude the `quarkus-mongodb-client` extension to have MongoDB specific Quarkus stuff, as long as you didn't configure any MongoDB connection URL it will not start any MongoDB client.

**Comment by krisgerhard** [comment]
Thanks. Let's say I might not have worked out of the box in 2.6.3.Final but with the combiation of `reflection-config.json` and `--initialize-at-run-time` changes I was using ``mongo+srv://` for oven a year with latest Quarkus versions.
