### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by tapaniantonrundgren** [quarkusio/quarkus#23435]
### Describe the bug

Using quarkus build to build and deploy in OpenShift environment.

### Expected behavior

Build and Deploy to OpenShift environment

### Actual behavior

I get this error when executing $quarkus build
...
Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: java.lang.IllegalArgumentException: Name must be provided.
...

### Output of `uname -a` or `ver`

Linux SEGOTW10426186 5.10.81.1-microsoft-standard-WSL2 #1 SMP Mon Nov 22 18:52:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java 17.0.1 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

quarkus build

### Additional information

This same build works with 2.6.3.Final and 999-SNAPSHOT

**Comment by geoand** [comment]
If this works already on `999-SNAPSHOT`, then I would say the issue is out of date :).

@iocanel do you know which PR fixed it?

**Comment by tapaniantonrundgren** [comment]
You can close this, I can wait for the next release, before upgrading from 2.6.3.Final. Seems to be working even with the latest 999-SNAPSHOT that I updated few minutes ago
