### ISSUE TITLE
Add support for native queries with the spring-data extension / Hibernate

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#23434]
### Description

In the documentation it is stated that quarkus with spring-data does not support native queries, is it possible to add the implementation to support it ?

### Implementation ideas

I never read how the spring data features were implemented on top of Panache, so i'm not of much help here

**Comment by geoand** [comment]
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/5348
