### ISSUE TITLE
Code Scan failure in CI/CD pipeline quarkus-maven-plugin

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#23440]
### Describe the bug

If we have &lt;extensions>true&lt;/extensions> in quarkus-maven-plugin getting error during sonar code scans. Please advise. Is quarkus-maven-plugin compiled in Java 17 or Java 11. Not sure why we get the error.

Removing the tag works fine for us.
`mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f pom.xml -Dsonar.host.url=https://**** -Dsonar.login=**** -Dsonar.ci-config.jenkins.jobname=**** -Dsonar.ci.config.jenkins.url=https://**** -Drevision=**** -Dsonar.projectName=****:**** -Dsonar.projectKey=****:**** -Dsonar.branch.name=**** -Dsonar.analysis.commitId=**** -Dsonar.analysis.commiter=**** -Dsonar.analysis.branchname=**** -Dsonar.analysis.scmUrl=**** -Dsonar.analysis.ciUrl=https://**** -Dsonar.analysis.buildTag=**** -Dsoanr.ci-config.scm.repo.url=ssh://**** -Dsonar.links.ci=**** -Dsonar.links.scm=ssh://**** 
`
JAVA_TOOL_OPTIONS:-Xms256m -Xmx512m

Getting Error 
`[WARNING] Error injecting: io.quarkus.maven.components.BootstrapSessionListener
java.lang.TypeNotPresentException: Type io.quarkus.maven.components.BootstrapSessionListener not present`...
`Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/maven/components/BootstrapSessionListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognises class file versions up to 52.0`

### Expected behavior

No error when we have &lt;extensions>true&lt;/extensions>

### Actual behavior

Throws error 
Getting Error 
`[WARNING] Error injecting: io.quarkus.maven.components.BootstrapSessionListener
java.lang.TypeNotPresentException: Type io.quarkus.maven.components.BootstrapSessionListener not present`...
`Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/maven/components/BootstrapSessionListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognises class file versions up to 52.0`

### How to Reproduce?

Run maven command with any quarkus app with sonar qube collection. Let us know what to do for fix.

### Output of `java -version`

17.0.12021-10-19 LTS

### GraalVM version (if different from Java)

NA

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

**Comment by debu999** [comment]
Can someone guide on which version the plugin is compiled we we see java 8 dependency during sonar. Build and app run works as expected including the tests. Only Sonar complains

**Comment by gsmet** [comment]
Prerequisites for Quarkus 2+ is Java 11.
