### ISSUE TITLE
Hibernate post-boot schema-validation fails after upgrade to Quarkus 2.6.3

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#23445]
### Describe the bug

After upgrade to 2.6.3.Final, post boot schema validation emits some warnings about missing table(s).
Migrations are managed by Flyway and database contains:
1. schema _postboot1_ holds Flyway schema history table
2. schema _postboot_ contains table _product_

Flyway is configured to use _postboot1_ as its own schema and _postboot_ as managed schema.
Hibernate is configured to use _postboot_ as default schema.
A single PanacheEntity _@Entity_ is mapped as:

```
@Entity
@Table(name="product")
class Product extends PanacheEntity {
  // properties
}
```

### Expected behavior

No warnings at all (as before the upgrade)

### Actual behavior

```
2022-02-04 16:26:25,945 ERROR [io.qua.hib.orm.run.sch.SchemaManagementIntegrator] (Hibernate post-boot validation thread for <default>) Failed to validate Schema: Schema-validation: missing table [product]
2022-02-04 16:26:25,992 ERROR [io.qua.hib.orm.run.sch.SchemaManagementIntegrator] (Hibernate post-boot validation thread for <default>) The following SQL may resolve the database issues, as generated by the Hibernate schema migration tool. WARNING: You must manually verify this SQL is correct, this is a best effort guess, do not copy/paste it without verifying that it does what you expect.

create table product (id bigint not null, code varchar(255), marketArea varchar(255), primary key (id));

```

### How to Reproduce?

https://github.com/luca-bassoricci/hibernate-postboot-validator
Repo is configured to use version 2.7.0 of Quarkus

### Output of `uname -a` or `ver`

Link to repo with sample 

### Output of `java -version`

Link to repo with sample 

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
Any chance you can check and see if the problem persists with `2.7.0.Final`?

**Comment by luca-bassoricci** [comment]
Yes, with `2.7.0.Final` problem is still present
Attached repo is configured to use version `2.7.0.Final`.
I opened this issue today because version `2.7.0.Final` was on the way and I wanted to check if the issue was still present after upgrade.

If this is information can help, I followed code during execution and during tables metadata extraction schema used is `dbo` instead of `postboot`; namespace passed along mathods is always setted with `{catalog=null, schema = null}` but with previous version of Quarkus (and Hibernate) namespace is `{catalog=null, schema = postboot}`.
During my test I stumbled in this ticket (https://github.com/hibernate/hibernate-orm/pull/4351)

**Comment by geoand** [comment]
Thanks for the information

**Comment by gsmet** [comment]
@yrodiere I wonder if this could be due to your recent work on schemas?

**Comment by gsmet** [comment]
@luca-bassoricci what is the latest version you tested and that was working?

**Comment by luca-bassoricci** [comment]
Last working version was `2.6.1.Final`.
