### ISSUE TITLE
problem using quarkus-resteasy-reactive-kotlin-serialization with AwsProxyRequestContext

### ISSUE THREAD

**Issue by Lukpier** [quarkusio/quarkus#23442]
Hi All,

I'm trying to use quarkus-resteasy-reactive-kotlin-serialization on a Kotlin jax-rs reactive endpoint deployed on AWS.
Below the method signature:

```kotlin
  @POST
  @Path("/send")
  fun signUp(request: RegistrationRequest, @Context context: AwsProxyRequestContext): RegistrationResult? =
      service.signUp(request, awsRequestId = request.requestId)
```

Unfortunately, Quarkus returns Bad request when trying to call this endpoint from APIGateway test page. No error is shown since quarkus itself intercept the request without accessing the method body.

After some trials, I managed to be able to access the context object by using quarkus-resteasy-jackson (so, no kotlin-serialization nor reactive), but this is not what I want to obtain.

Am I missing something?

Thanks for all your work!!

**Comment by geoand** [comment]
Hi,

Kotlin Serialization only works on types that are annotated with `@Serializable`.

**Comment by Lukpier** [comment]
Hi geoand,

Thanks for your response. I know that; atm, I'm trying to implement a custom serializer for that object (using KSerializer), since it is the only Aws context object i need to access in my application.

Do you think it could work? I will need to switch to Jackson otherwise.

**Comment by geoand** [comment]
> Do you think it could work? 

Can't say since I've never tried something like that. @evanchooly might now more

**Comment by evanchooly** [comment]
I'd do a bit of experimentation but I think the limitation you're going to run in to is that you need to register and serializers with the `SerializersModule` used to construct the `Json` we use.  Currently there's no way to configure that as part of quarkus and it seems that's all immutable so it can't be done after the fact.

**Comment by Lukpier** [comment]
> I'd do a bit of experimentation but I think the limitation you're going to run in to is that you need to register and serializers with the `SerializersModule` used to construct the `Json` we use. Currently there's no way to configure that as part of quarkus and it seems that's all immutable so it can't be done after the fact.

Understood, so the only solution now is to use jackson (or jsob) for request / context decoding (?)

**Comment by geoand** [comment]
Yes, Jackson is the only tested way to deserialize input for `quarkus-amazon-lambda-rest`

**Comment by Lukpier** [comment]
> Yes, Jackson is the only tested way to deserialize input for `quarkus-amazon-lambda-rest`

Ok, I will use jackson for injecting the entire AwsProxyRequest, then proceeeding as usual with kotlin-serialization.

**Comment by Lukpier** [comment]
Hi All,

Just encountered a related problem. I'm trying to use `quarkus-amazon-lambda-rest` together with quarkus-resteasy-reactive-jackson. 

Unfortunately, when trying to call the endpoint described in the main issue description, I receive an automatic BAD_REQUEST from quarkus context. Why does it is happening?

Tried also `quarkus-resteasy-jackson` and everything goes fine, but I was trying to use resteasy reactive in order to make `quarkus-rest-client-kotlin-serialization` work as a rest-client.

I noticed that in the maven archetype of `quarkus-amazon-lambda-rest` there is no trace of quarkus-restasy-reactive, but only quarkus-resteasy. So, can I assume that reactive is not supported with amazon-lambda ?

Thanks.

**Comment by geoand** [comment]
@patriot1burke can you have a look at ^ please?

**Comment by Dunmord** [comment]
@geoand @patriot1burke hey just wanted to check if there were any updates? thanks!

**Comment by geoand** [comment]
Can someone attach a sample project where RESTEasy Reactive and Java (not Kotlin) is being used and the project exhibits problematic behavior?

Thanks

**Comment by JakubWylezek** [comment]
Hi 

I also got this problem in my project.
When I try to call endpoint witch @Context param I receive BAD_REQUEST.
Problem occurs only when I using io.quarkus:quarkus-resteasy-reactive.
With io.quarkus:quarkus-resteasy everything works fine
Here some logs: 
![log](https://user-images.githubusercontent.com/38432671/216012803-9ae79fe3-39cd-4dd9-9bef-359f1dcde895.PNG)

@geoand You can find sample project with issue here https://github.com/JakubWylezek/lambdarestreactive
No param endpoint works fine, second with @Context return BAD_REQUEST
With 'io.quarkus:quarkus-resteasy' both works fine

**Comment by geoand** [comment]
Thanks, that's most helpful. 

I think I know what the problem is.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/30776 fixes the problem
