### ISSUE TITLE
RestEasy reactive InputStream response using wrong writer

### ISSUE THREAD

**Issue by Krawart** [quarkusio/quarkus#23489]
### Describe the bug

I tried to optimize a reactive endpoint streaming input of an audio file based on Quarkus REST Score Console. I replaced generic Response with Reactive RestResponse. It increased the score to 100 but it is using wrong message handler. Tried both ByteArray and InputStream as entity - same result

### Expected behavior

ServerInputStreamMessageBodyHandler should be used write to response

### Actual behavior

Using ServerStringMessageBodyHandler

### How to Reproduce?

Using Kotlin

Dependencies:
```
    implementation "io.quarkus:quarkus-resteasy-reactive"
    implementation "io.quarkus:quarkus-resteasy-reactive-jackson"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
```

```
@GET
@Path("/{lectureId}/stream")
@Produces(MediaType.APPLICATION_OCTET_STREAM)
fun getLectureStreamById(
    @RestHeader("Range") rangeParam: String?,
    @RestPath lectureId: LectureId
): Uni<RestResponse<InputStream>> {
    return lectureAudioService.getAudioFile(lectureId).map { lectureStream ->
            downloadResponse(ByteArrayInputStream(lectureStream.data), filename = "$lectureId.mp3").build()
    }
}

fun downloadResponse(
    data: InputStream,
    filename: String,
): ResponseBuilder<InputStream> {
    return ResponseBuilder.ok(data)
        .header("Content-Disposition", "attachment;filename=$filename")
}
```

### Output of `java -version`

17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.3

**Comment by geoand** [comment]
Any chance you can add a reproducer?

**Comment by Krawart** [comment]
[Here](https://github.com/Krawart/Reactive_input_stream_issue_sample_project) is sample project with simple test

**Comment by geoand** [comment]
Although https://github.com/quarkusio/quarkus/pull/23502 fixes the problem, however FWIW retuning an `InputStream` from the event loop (by leveraging `Uni` as a response type) is generally a bad idea because you are blocking the event loop thread.

It would be much safer to do something like:

```kotlin
    @Path("/{filename}/async-file")
    @GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    fun getAsyncFile(filename: String): Uni<RestResponse<AsyncFile>> {
        return Uni.createFrom().emitter { emitter: UniEmitter<in RestResponse<AsyncFile>> ->
            vertx.fileSystem().open(
                "$filename.mp3", OpenOptions()
            ) { result: AsyncResult<AsyncFile> ->
                if (result.succeeded()) emitter.complete(
                    ResponseBuilder.ok(result.result()).header("Content-Disposition", "attachment;filename=$filename.mp3").build()
                ) else emitter.fail(result.cause())
            }
        }
    }
```

**Comment by Krawart** [comment]
Thank you for your proposition but Is there some better approach for data received for example from google cloud storage? (without vertx fileSystem API)

**Comment by geoand** [comment]
If you want to stay on the event loop, you'll need to retrieve the data in an Async manner. I have not used Google Cloud Storage, so I am not aware if there is a non-blocking client for it.
