### ISSUE TITLE
quarkus:dev with quarkus-jdbc-d2 ignores db2jcc_license_cisuz dependency

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#23487]
### Describe the bug

When i try to access to db2 Z/OS from my microservice, in dev mode, it got this error:

aused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][t4][10509][13454][4.29.24] La connexion au serveur de données a échoué. La licence IBM Data Server for JDBC and SQLJ n'était pas valide
ou n'a pas été activée pour le sous-système DB2 for z/OS. Si vous vous connectez directement au
serveur de données et que vous utilisez DB2 Connect Unlimited Edition for System z, effectuez
l'étape d'activation en exécutant le programme d'activation du kit d'activation de licence.
Si vous utilisez une autre édition de DB2 Connect, procurez-vous le fichier de licence,
db2jcc_license_cisuz.jar, qui se trouve dans le kit d'activation de licence et suivez les instructions d'installation
pour inclure ce fichier dans le chemin d'accès aux classes. ERRORCODE=-4230, SQLSTATE=42968
        at com.ibm.db2.jcc.am.b7.a(b7.java:810)

### Expected behavior

it should works

### Actual behavior

licenses not detecte

### How to Reproduce?

1. add this in the pom:
    <dependency>
      <groupId>db2jccdriver</groupId>
      <artifactId>db2jcc</artifactId>
      <version>10.5.0.8</version>
    </dependency>    
    <dependency>
      <groupId>db2jccdriver</groupId>
      <artifactId>db2jcc_license_cisuz</artifactId>
      <version>10.5.0.8</version>
    </dependency>

 also try with theses params:

# quarkus.class-loading.parent-first-artifacts=db2jccdriver:db2jcc_license_cisuz-10.5.0.8
# quarkus.class-loading.reloadable-artifacts=db2jccdriver:db2jcc_license_cisuz-10.5.0.8

run mvn quarkus:dev

### Output of `uname -a` or `ver`

linux or windows, whatever

### Output of `java -version`

java 11

### Quarkus version or git rev

2.7.0 / 2.6.x also

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.2

**Comment by stuartwdouglas** [comment]
Closing as a duplicate. Please see the other issue for a fix.
