### ISSUE TITLE
Integration test 'test-host'

### ISSUE THREAD

**Issue by FedeBell94** [quarkusio/quarkus#23483]
### Describe the bug

As described in the latest [documentation](https://quarkus.io/guides/getting-started-testing#executing-against-a-running-application), I'm trying to execute the tests against a running application, using the command `./mvnw verify -Dquarkus.http.test-host=1.2.3.4 -Dquarkus.http.test-port=4321`.

This command fails, and returns the following error:  _Unrecognized configuration key "quarkus.http.test-host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo_

I'm running this command in the [official getting-started project](https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started-testing)

**Comment by famod** [comment]
This feature only works for `@QuarkusIntegrationTest`s but AFAICS the `getting-started-testing` quickstart only contains `@QuarkusTest`s and one `@NativeImageTest`, but no `@QuarkusIntegrationTest`.
Can you please double check?

/cc @geoand

**Comment by FedeBell94** [comment]
Same result when I try to run [this test](https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-openid-connect-quickstart/src/test/java/org/acme/security/openid/connect/NativeBearerTokenAuthenticationIT.java), which is annotated with `QuarkusIntegrationTest`.

When I run the `./mvnw verify -Dquarkus.http.test-host=1.2.3.4 -Dquarkus.http.test-port=4321` command, the test-host is ignored, and instead of connecting to a running application, a new Quarkus application is started on ` http://localhost:4321`

**Comment by geoand** [comment]
Indeed `quarkus.http.test-host` only works for `@QuarkusIntegrationTest`.

In the quickstart you mention, `@QuarkusIntegrationTest` is only configured to run when the `native` profile is active, so the command you mention does not run `NativeBearerTokenAuthenticationIT`

**Comment by kpavel** [comment]
Experiencing exactly same error. Using **@QuarkusIntegrationTest**.
The 'test-host' parameter in application.properties is ignored.

`Unrecognized configuration key "quarkus.http.test-host" was provided`

**Comment by franck102** [comment]
Same problem here, starting from the Greeting archetype:
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.10.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions="resteasy-reactive"
```

I simply added 
```
quarkus.http.test-host=127.0.0.1
quarkus.http.test-port=8080
```
to application.properties and started Quarkus using quarkus:dev.

The GreetingResourceIT test won't run, it spits out
```
[io.quarkus.config] Unrecognized configuration key "quarkus.http.test-host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by geoand** [comment]
What version of Quarkus are you using?

**Comment by geoand** [comment]
@ivansenic so all good with `@QuarkusIntegrationTest`?

**Comment by ivansenic** [comment]
> @ivansenic so all good with `@QuarkusIntegrationTest`?

All good works like a charm.. This is incredibly good feature, enables us to spin different complex environments that would be hard to do with test resource and simply run integration tests..

**Comment by geoand** [comment]
Awesome, glad to hear it :)

**Comment by ftrotta** [comment]
I can use the feature to run (integration) tests against a running application with HTTP.

How to use the same feature to run (integration) tests against a running application _with HTTP**S**_?

Thanks a lot
