### ISSUE TITLE
Wrong Buildpack configuration for native

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#23491]
### Describe the bug

Container image guide[1] says the following configuration:

or for native:
quarkus.buildpack.jvm-builder-image=<native builder image>

But it must be "quarkus.buildpack.native-builder-image"

[1]https://quarkus.io/guides/container-image#buildpack

### Expected behavior

quarkus.buildpack.native-builder-image=<native builder image>

### Actual behavior

quarkus.buildpack.jvm-builder-image=<jvm builder image>

**Comment by gsmet** [comment]
Thanks. https://github.com/quarkusio/quarkus/pull/23493 will address it.
