### ISSUE TITLE
Generated `DeploymentConfig` by OpenShift extension has wrong `imagePullPolicy`

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#23492]
### Describe the bug

When generating kubernetes yaml via the OpenShift extension, according to https://quarkus.io/guides/all-config#quarkus-kubernetes_quarkus.openshift.image-pull-policy the default `imagePullPolicy` should be `always`, yet when I generate resources I am seeing `imagePullPolicy: IfNotPresent` in the generated `DeploymentConfig`.

Furthermore, if I try to set `quarkus.openshift.image-pull-policy=always` it doesn't seem to work.

I tried this on the latest (`2.7.0.Final`) as well as on `2.6.3.Final`. Its broken in both places.

### How to Reproduce?

Reproducer:
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8018014/code-with-quarkus.zip)

Open this up and examine `target/kubernetes/openshift.yml`. You'll see `imagePullPolicy: IfNotPresent` in the `DeploymentConfig` for `code-with-quarkus`.

If you open `src/main/resources/application.properties` you'll also notice that `quarkus.openshift.image-pull-policy=always`. If you remove that line and run `./mvnw clean package -DskipTests` and re-examine `target/kubernetes/openshift.yml` you'll see that it didn't have an effect on anything.

**Comment by geoand** [comment]
@iocanel it seems like the `image-pull-policy` configuration is only applied to Vanilla Kubernetes. That sounds like a bug, no?
