### ISSUE TITLE
ClassLoader can't find resource since 2.7.0

### ISSUE THREAD

**Issue by camboui** [quarkusio/quarkus#23511]
### Describe the bug

Hi,

After updating from 2.6.3-Final to 2.7.0-FInal, I've been trying to load a certificate file with property:
`quarkus.http.ssl.certificate.file=META-INF/certs/server.pem` (I know it's deprecated)
but it ended with a "FileNotFoundException". 

After digging a bit, using this property then calls `Thread.currentThread().getContextClassLoader().getResourceAsStream(path);` in VertxHttpRecorder.java

I used this same code in a simple OnStart and observed the same behaviour.

I tried to dig further using debgger but only found that getResourceAsStream() from QuarkusClassLoader.java behaviour differs :
         - 2.6.3 : 'elements' property contains [MemoryClassPathElement, DirectoryClassPathElement]
         - 2.7.0 : 'elements' property contains [MemoryClassPathElement, PathTreeClassPathElement]

 

### Expected behavior

File's loaded 

### Actual behavior

File's not found, FileNotFoundException

### How to Reproduce?

1 - Download default zip from https://code.quarkus.io/ 

2 - Add class
```
@ApplicationScoped
public class AppLifecycleBean {

    void onStart(@Observes StartupEvent ev) {
        // Method invoked by VertxHttpRecorder to initialize property "quarkus.http.ssl.certificate.file"
        // Works in 2.6.3 but null in 2.7.0
        var pathValue = "META-INF/certs/server.pem";
        var path = Path.of(pathValue);
        var inputStreamNullResult = Thread.currentThread().getContextClassLoader().getResourceAsStream(path.toString());

        // Works with any version using String directly
        // Maybe something to do with Windows path somewhere ?
        var inputStreamOkResult = Thread.currentThread().getContextClassLoader().getResourceAsStream(pathValue);

        /* Note that might help digging: using debugger during getResourceAsStream() in QuarkusClassLoader.java:
         - 2.6.3 : 'elements' property contains [MemoryClassPathElement, DirectoryClassPathElement]
         - 2.7.0 : 'elements' property contains [MemoryClassPathElement, PathTreeClassPathElement]
         */
    }

}
```

3 -  Add any file in resources directory, "META-INF/certs/server.pem"

4 - Switch from version 2.6.3-Final and 2.7.0-Final to observe that `inputStream` is null in 2.7.0-Final.

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk 11.0.10 2021-01-19

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
Sure, if the path argument uses `\` as a separator, it's not expected to work. If you read the javadoc for `java.lang.ClassLoader.getResource(String)`:
````
The name of a resource is a '/'-separated path name that identifies the resource.
````

**Comment by gsmet** [comment]
@aloubyansky I'm a bit confused, I see `/` in the report?

**Comment by aloubyansky** [comment]
The property, right. The config option is mapped to `java.nio.file.Path`. I'll fix it. My comment was about the code in the class.

**Comment by aloubyansky** [comment]
Thanks for reporting the issue @camboui

**Comment by camboui** [comment]
You're welcome :)

I still can't figure out what changed between 2.6.3 and 2.7.0 to break this, even after some source diving and diff matching. I can't sleep with it ! Do you have a any clue ? (If you don't have time, don't bother 😉 )

**Comment by aloubyansky** [comment]
As you noticed we have a new ClassPathElement implementation in 2.7 which pretty much replaces Jar- and Directory- ClassPathElement impl. And now we appear to be more strict when it comes to the resource names. So it's a bug in the VertxHttpRecorder that is calling `Path.toString()` expecting it always be a valid resource name.
