### ISSUE TITLE
MS SQL dev service can't be used asap, users need to add container-license-acceptance.txt file

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#23525]
### Describe the bug

MS SQL dev service can't be used asap, users need to add container-license-acceptance.txt file

One sees quite a long stacktrace with this root cause:

```
Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04 requires 
  you to accept a license agreement. Please place a file at the root of the classpath named 
  container-license-acceptance.txt, e.g. at src/test/resources/container-license-acceptance.txt.
  This file should contain the line:
    mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
```

Can be the file generated for users with the value of the image used for dev service?
Topics for consideration:
 a) is generated container-license-acceptance.txt allowed by MS or users need to add it on their own?
 b) is it technically possible? Sounds like codestart with some property substitution for mssql would be needed.

### Expected behavior

MS SQL dev service can be used asap

### Actual behavior

MS SQL dev service can't be used asap, users need to add container-license-acceptance.txt file

### How to Reproduce?

 - Download app from code.quarkus with MSSQL JDBC and Hibernate ORM
 - run `mvn quarkus:dev`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.1.Final

**Comment by gsmet** [comment]
This is done on purpose. We can't accept a license agreement automatically.

**Comment by rsvoboda** [comment]
Ok, thanks for clarification.
