### ISSUE TITLE
Integration Test Container Network

### ISSUE THREAD

**Issue by lomanm** [quarkusio/quarkus#23531]
### Description
While running Quarkus Integration Tests with ```quarkus.container-image.build=true```, I would like to be able to prevent Quarkus from placing the Native app docker container (and my Test Resource docker container) inside a custom docker network. Alternatively, I would like to be able to specify the docker network that Quarkus placed these containers in.

My current integration tests work for Quarkus 2.4 but are broken for Quarkus 2.6 due to changes in this [commit](https://github.com/quarkusio/quarkus/commit/b6e84c8e2f117f256dff0169b25409680548280f), which is also discussed [here](https://quarkus.io/guides/getting-started-testing#launching-containers) in the getting-stared guide. 

### My Current Setup (Quarkus 2.4)
On a Jenkins server I create a docker container that runs the integration tests via Maven. This docker container is on a specific docker network. The Maven container is able to communicate with the native app (which is started in another docker container by the test) via these arguments in the maven command:

```-Dquarkus.http.host=my-native``` 
```-Dquarkus.test.argLine='--network my-network --network-alias my-native' ```

The ```--network``` argument places the native in the same network as the Maven container.  The ```--network-alias``` argument configures the native's docker container to work with the quarkus.http.host I have specified. In addition, I have a test resource (Couch DB) that is created in the tests via QuarkusTestResourceLifecycleManager.  This resource is created on the default docker "bridge" network, and I set the URL for Couch as a property in the start() method by calling org.testcontainers.containers.getContainerIpAddress().  This makes the URL discoverable by both the native, and by Maven.  The Couch resource is accessed directly by both - the tests insert data into Couch, while the native app queries Couch.

### Quarkus 2.6 Issue
In Quarkus 2.6, both the test resource and native executable docker containers are placed in a docker network created by Quarkus.  I can't find a way to override this, or control the network id that is created. The problem is that my tests, running via Maven in a container in a separate docker network, are not able to communicate with the native docker container.  The tests can communicate with the test resource via the same mechanism I am using in my current setup.

### Expected behavior

I would like to be able to prevent the docker network from being created or, alternatively, I would like to be able to specify an existing docker network.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/23543 will allow you to specify `quarkus.test.container.network=dummy-network=my-network`

**Comment by lomanm** [comment]
This fix that was implemented in 2.7.2.Final has resolved my issue.  Thanks!
