### ISSUE TITLE
Extension for Helm

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#23540]
### Description

From Dekorate 2.9.0 (unreleased yet), Dekorate will include a new module to generate Helm artifacts (see https://dekorate.io/docs/helm).
Dekorate is already used by Quarkus to generate OpenShift and Kubernetes artifacts, so it would be great to have the Quarkus Helm extension to also generate the Helm artifacts.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion

Dekorate Helm module is fully configurable via properties. The Quarkus Helm extension would look like as:

```
quarkus.helm.name=myChart
quarkus.helm.version=1.0.0-SNAPSHOT
quarkus.helm.description=Description of my Chart
```

**Comment by Sgitario** [comment]
I guess this is a good candidate for Quarkiverse.
Also, I'm interested in leading the development of this extension.

**Comment by geoand** [comment]
We'll need @gastaldi for that 😉

**Comment by gastaldi** [comment]
> We'll need @gastaldi for that 😉

@geoand All I do is https://github.com/quarkiverse/quarkiverse-devops#workflow-for-new-repositories 😉
