### ISSUE TITLE
Mention docker image user changed due to base image change in jib for 2.7.0

### ISSUE THREAD

**Issue by RuggeroDAlo** [quarkusio/quarkus#23541]
### Description

The migration guide mentions that the base image used by jib has changed from `fabric8/java-alpine-openjdk11-jre` to `registry.access.redhat.com/ubi8/openjdk-17-runtime:1.11`: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7#jib

`java-alpine-openjdk11-jre` doesn't set a `USER` by default so the container runs as `root`, while `registry.access.redhat.com/ubi8/openjdk-17-runtime:1.11` uses user `jboss/185`. Maybe this change could also be added to the migration guide?

**Comment by geoand** [comment]
Good point! Done
