### ISSUE TITLE
Cache for native images is not created when option com.redhat.fips=false is used

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#23544]
### Describe the bug

According to https://github.com/quarkusio/quarkus/pull/20355, when a native image is built, build cache  folder target/*native-image-source-jar/test. Although, when native image is run with parameter `-Dquarkus.native.additional-build-args=-Dcom.redhat.fips=false` (even on machines with FIPS disabled), this folder is not created.

### Expected behavior

Disabling FIPS should not affect creation of build cache, especially on machines without FIPS.

### Actual behavior

Build cache folder is not created

### How to Reproduce?

1. git clone git@github.com:quarkus-qe/quarkus-test-suite.git
2.``` mvn clean verify -pl io.quarkus.ts.qe:docker-build -Dall-modules -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=5g -Dquarkus.native.builder-image=registry-proxy.engineering.redhat.com/rh-osbs/quarkus-mandrel-21-rhel8:21.3 -Dquarkus.native.additional-build-args=-Dcom.redhat.fips=false ```
3. Folder docker-build/target/docker-build-1.0.0-SNAPSHOT-native-image-source-jar/test is not created, the test fails
4. ```mvn clean verify -pl io.quarkus.ts.qe:docker-build -Dall-modules -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=5g -Dquarkus.native.builder-image=registry-proxy.engineering.redhat.com/rh-osbs/quarkus-mandrel-21-rhel8:21.3```(notice the missing `additional-build-args` option)
5. Folder docker-build/target/docker-build-1.0.0-SNAPSHOT-native-image-source-jar/test is created, the test succeeds

### Output of `uname -a` or `ver`

5.15.18-200.fc35.x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

Checked for 2.2.5.Final and 11870d765d4141280040e495fea1d637e2a90283

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by zakkak** [comment]
@fedinskiy when passing `-Dquarkus.native.additional-build-args=-Dcom.redhat.fips=false` you are essentially overriding `quarkus.native.additional-build-args` which is defined as `quarkus.native.additional-build-args=-H:GenerateDebugInfo=1, -H:-SpawnIsolates, -H:DebugInfoSourceCacheRoot=test` in `docker-build/src/main/resources/application.properties`.

Running:
```
mvn clean verify -pl io.quarkus.ts.qe:docker-build -Dall-modules -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=5g -Dquarkus.native.builder-image=registry-proxy.engineering.redhat.com/rh-osbs/quarkus-mandrel-21-rhel8:21.3 -Dquarkus.native.additional-build-args=-H:GenerateDebugInfo=1,-H:-SpawnIsolates,-H:DebugInfoSourceCacheRoot=test,-Dcom.redhat.fips=false
```
works as expected.

**Comment by fedinskiy** [comment]
@zakkak is there a way to just add  parameters, without overriding them?

**Comment by zakkak** [comment]
> @zakkak is there a way to just add parameters, without overriding them?

AFAIK no. If you find a work around please let me know. I am also interested in doing so in some tests :)

**Comment by fedinskiy** [comment]
Got it, thank you! I suppose, we can close this issue?
