### ISSUE TITLE
`quarkus.hibernate-orm.sql-load-script` works with relative path but ignores absolute path

### ISSUE THREAD

**Issue by liteultom** [quarkusio/quarkus#23574]
## Describe the bug

Using `quarkus.hibernate-orm.sql-load-script` to create views in a PostgreSQL database. If I put the SQL file (`views.sql`) in a `sql` subfolder of the `resources` folder and configure the quarkus app like so :
```
%dev.quarkus.hibernate-orm.sql-load-script=sql/views.sql
```
it works, the script is executed at startup and the views are created.

##### However, if I give the absolute path of the file like so:
```
%dev.quarkus.hibernate-orm.sql-load-script=/home/username/path/to/resources/sql/views.sql
```
I have no error but no views are created.

##### Also interesting to notice, if I try to give this value:
```
%dev.quarkus.hibernate-orm.sql-load-script=../resources/sql/views.sql
```
I do have an error: 
```
io.quarkus.deployment.configuration.ConfigurationError: Unable to find file referenced in 'quarkus.hibernate-orm.sql-load-script=../resources/sql/views.sql'
```
## Expected behavior

Giving the absolute path of an SQL file to the `quarkus.hibernate-orm.sql-load-script` param should execute said SQL file

## Actual behavior

SQL file is executed only if a relative path is given, absolute path are simply ignored

## How to Reproduce?

1. Have a basic project with Panache and an SQL DB
2. Add an SQL file under `resources` folder of the quarkus app
3. Set the value of `quarkus.hibernate-orm.sql-load-script` to the relative path of the file from the `application.properties` file : **it works**
4. Set the value of `quarkus.hibernate-orm.sql-load-script` to the absolute path of the file : **it does not work**

### Output of `uname -a` or `ver`

Linux tomtom-dell 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

### Quarkus version or git rev

2.5.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by liteultom** [comment]
### Additional information
If the absolute path is wrong, I also get an error:
```
io.quarkus.deployment.configuration.ConfigurationError: Unable to find file referenced in 'quarkus.hibernate-orm.sql-load-script=/home/username/path/to/resources/sql/fake_views.sql'
```
This seems to indicate the file is found with the absolute path, just not used ?

**Comment by yrodiere** [comment]
`quarkus.hibernate-orm.sql-load-script` is a build-time configuration property. Its value fixed at build-time, and when building a native binary for your application, the file may actually be read during the build. So there is no point allowing the use of a file outside of `src/main/resources`.

I will close this issue. If you have a compelling reason to use a file outside of your resources for `sql-load-script`, even though it's fixed at build-time, please open a separate issue for your feature/enhancement request. If you think there is a bug even when using sql load scripts in `src/main/resources`, please reopen this ticket and explain what is wrong exactly.

You may also be interested in this other issue, which is somewhat related: 21866

**Comment by liteultom** [comment]
I think I have a compelling reason and will try to find time to write a proper feature/enhancement request.  

However, I think it's still a bug that it fails silently, there should be either an error or a warning, just as when the file is not found.

**Comment by yrodiere** [comment]
> However, I think it's still a bug that it fails silently, there should be either an error or a warning, just as when the file is not found.

True. I'll have a look, thanks for bringing this up.
