### ISSUE TITLE
Confusing, if not downright wrong, warning message

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#23573]
### Describe the bug

I run my app in dev mode. I change a build time property in `application.properties` and the application properly restarts but I get the following warning in the console:

```java
2022-02-10 09:57:08,244 WARN  [io.qua.run.con.ConfigRecorder] (Quarkus Main Thread) Build time property cannot be changed at runtime:
 - quarkus.operator-sdk.crd.apply was 'true' at build time and is now 'false'

```

What is this message trying to tell me? What is the state of my property, i.e. is it `true` or is it `false`?

### Expected behavior

A clear message as to what happened.

### Actual behavior

The currently ambiguous or wrong message.

### Output of `java -version`

11

### Quarkus version or git rev

2.7.0.Final

**Comment by metacosm** [comment]
Maybe better suited as a discussion? Though I'd argue that this is a bug in the current implementation because it conveys confusing information.

**Comment by maxandersen** [comment]
Is there a formulation that you think would be better?

maybe something like "Build time property cannot be changed at runtime:
 - quarkus.operator-sdk.crd.apply was requested to be 'false', but it is buildtime fixed to 'true'" ?
 
 @radcortez @geoand

**Comment by maxandersen** [comment]
yes its true but I agree its not clear - thus I asked if there is a formulation that would been better and I gave my attempt.
Does that sound better or you have suggestion on how to make it clearer?

**Comment by metacosm** [comment]
I purposefully didn't detail what I did so that it wouldn't influence how the warning is interpreted in the absence of external information.

What I did was changed, while dev mode is running, the property from `false` to `true`. So why is the warning even talking about it being requested to be `false`? If the property value is properly changed to `true`, why do we even have a warning? What purpose does it serve (apart from confusing users 😄)?

To me, the proper behavior here would be to not issue any warning at all because there is nothing that requests the value to be `false` apart from the default value specified in the configuration.

Note also that while working on this I experienced a time where the property wasn't actually changed (i.e. the behavior associated with the value being `true` was not triggered) no matter how many force restart I did (via pressing `s` on the console). Restarting the dev mode solve the issue.

**Comment by geoand** [comment]
I personally think the message clear but I realize than I am not the right person to comment since I have seen the message too many times

**Comment by geoand** [comment]
I am referring to the message itself. For me, the message is correct.

What triggers it is something different where there might be a bug...

**Comment by metacosm** [comment]
When a message tells me a property is "now false", when it's actually the opposite, sorry, but I don't find that clear as it conflicts with the rest of the message.
I see the overall logic but the wording is very poor, imo.

**Comment by radcortez** [comment]
> And when you add on top of that the fact that nothing is supposed to request the property to be false, then you can see how this message can be quite confusing. I could understand the message if there was indeed something requesting the property to be false at runtime but this isn't the case.

What happens here is that build time properties are recorded and then matched against changes in the current properties and if differences are found they are reported as a warning (the one you see).

Are you suggesting that such a warning should only happen when the property is actually used?

**Comment by metacosm** [comment]
> > And when you add on top of that the fact that nothing is supposed to request the property to be false, then you can see how this message can be quite confusing. I could understand the message if there was indeed something requesting the property to be false at runtime but this isn't the case.
> 
> What happens here is that build time properties are recorded and then matched against changes in the current properties and if differences are found they are reported as a warning (the one you see).

I'm not sure I understand. In my case, the only thing that changes is the `application.properties` that is set at build time. There is nothing (at least that I control) that requests the property to have a different value at runtime. So, in this specific case, the warning should not even be there because no one is trying to override the build time value.

> 
> Are you suggesting that such a warning should only happen when the property is actually used?

The property is used, that's not the issue. The warning should only happen if there is actually something that tries to override the value set at build time, which isn't the case here. 

The warning should also be reworded to be less ambiguous to something similar to what Max suggested (bonus point if we could tell what is requesting the property to be changed).

**Comment by calohmn** [comment]
@radcortez Could you verify the printout of property values in the committed fix is done in the wrong way around? 

I also think the log message should emphasize that the runtime value actually _isn't_ getting set/applied - see my suggestion above.

**Comment by radcortez** [comment]
Let me have a look.
