### ISSUE TITLE
Update MongoDB Panache operations

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#23588]
### Description

There are some operations that are often used in MongoDB like updating a field by the filter. I have not seen any method or anything in the documentation about this so maybe I am missing it. Currently there is a workaround for this by getting the Mongo collection:

```java
Bson filter = eq("sku", SKU);
Bson update = inc("quantity", qty * -1);
Stock.mongoCollection().updateOne(filter, update);
```

### Implementation ideas

I think it would be nice to have the `updateOne` and `updateMultiple` methods implemented in Panache where you can set a Bson acting one as a filter and the other as an update operation. Maybe I missed something and it is possible now, but then I think it would be nice to improve docs with it.

**Comment by loicmathieu** [comment]
You can update (multi-update) with a PanacheQL or a native query inside the `where`, it's documented:
```
// set the name of all living persons to 'Mortal'
long updated = Person.update("name", "Mortal").where("status", Status.Alive);
```

**Comment by lordofthejars** [comment]
But how to implement the inc operation for example. I need to find it,
increment the object, and then do the update? So two queries?

Missatge de Loïc Mathieu ***@***.***> del dia dj., 10 de
febr. 2022 a les 17:39:

**Comment by loicmathieu** [comment]
The `where` should be able to take into parameters a Bson `Document` as the query as for eg for the list operation [PanacheMongoEntityBase.list(Document query)](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache/runtime/src/main/java/io/quarkus/mongodb/panache/PanacheMongoEntityBase.java#L386) and it's missing in [PanacheUpdate](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/common/PanacheUpdate.java).

So yes, it's something to add, and not very difficult ;)

**Comment by loicmathieu** [comment]
I prepare a PR to allow `update(Document).where(Document)` for complex update use case.
But you can already do something like this (we have test for it):
```
long updated = Person.update("{'$inc': {'quantity': ?1}",  qty * -1).where("sku", SKU);
```

**Comment by lordofthejars** [comment]
oh nice, then I think it's worth putting it in the document so anyone can
get the point on how to do it.

Great,

Missatge de Loïc Mathieu ***@***.***> del dia dv., 11 de
febr. 2022 a les 10:43:

**Comment by loicmathieu** [comment]
Maybe the documentation is not clear enought but anywhere you can use a String query you can use PanacheQL or a native query.
I'll check the JavaDoc, the update() part is maybe not that clear.
