### ISSUE TITLE
Quarkus ClassLoader problem when loading a single level directory with getResource

### ISSUE THREAD

**Issue by KoxAlen** [quarkusio/quarkus#23582]
### Describe the bug

In a application running with quarkus in prod mode when using the context class loader to get the url of a **directory** resource with only one level and not finished with a `/` the resources is not found

The class loader in question is quarkus `io.quarkus.bootstrap.runner.RunnerClassLoader`

The problem is that when there is only one directory level the RunnerClassLoader gets confused and thinks is from the `fullyIndexedDirectories` (empty string/default package) but jars top level directories are not indexed in `directlyIndexedResourcesIndexMap` so is treated as a miss.

This behaviour is inconsistent with standard hotspot classloader so some code that works w/o quarkus fails when running with quarkus.
It is also inconsistent and with quarkus RunnerClassLoader when there is more that one directory level in the resource name

### Expected behavior

Lets assume that `quarkusLoader` is the context classloader from a quarkus thread and that a directory named `assets` exists in one of the jars in the classpath

Expected behaviour would be:
```java
quarkusLoader.getResource("assets") -> Url to jar:<path_to_jar>!/assets
quarkusLoader.getResource("assets/") -> Url to jar:<path_to_jar>!/assets

quarkusLoader.getResource("assets/foo") -> Url to jar:<path_to_jar>!/assets/foo
quarkusLoader.getResource("assets/foo/") -> Url to jar:<path_to_jar>!/assets/foo
```

### Actual behavior

```java
quarkusLoader.getResource("assets") -> null # Bug/inconsistent behaviour
quarkusLoader.getResource("assets/") -> Url to jar:<path_to_jar>!/assets

quarkusLoader.getResource("assets/foo") -> Url to jar:<path_to_jar>!/assets/foo
quarkusLoader.getResource("assets/foo/") -> Url to jar:<path_to_jar>!/assets/foo
```

### Output of `java -version`
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

### Quarkus version or git rev

2.6.0.Final

**Comment by KoxAlen** [comment]
> Thanks for reporting!
> 
> It seems like you have already analyzed this issue, so perhaps care to open a Pull Request with a fix?

thought about it but I feel like I'm missing context as what would be the better solution:
My initial ideas were to:
Index all top level directories in `directlyIndexedResourcesIndexMap` (which seems like too much for such a corner case) during build.
or add a fallback check to `resourceDirectoryMap` (which seems to go against the design idea of `fullyIndexedDirectories`).

**Comment by geoand** [comment]
Gotcha.

Mind adding a sample project that exhibits the problem so we can go straight to fixing the issue?

Thanks

**Comment by aloubyansky** [comment]
I can reproduce this.
