### ISSUE TITLE
Default locale can't be changed

### ISSUE THREAD

**Issue by waldimiro** [quarkusio/quarkus#23599]
### Describe the bug

Default locale is not set when:

1. I use following command line -Duser.language=en -Duser.country=CH -Duser.variant=CH -Duser.region=CH
2. I use property quarkus.default-locale

### Expected behavior

Default locale must be set based on system properties.

### Actual behavior

Default locale is not set when:

1. I use following command line -Duser.language=en -Duser.country=CH -Duser.variant=CH -Duser.region=CH
2. I use property quarkus.default-locale

### How to Reproduce?

Start a quarkus application with command line -Duser.language=en -Duser.country=CH -Duser.variant=CH -Duser.region=CH and print the Locale.getDefault() is every time "en_US"

### Output of `java -version`

openjdk-17.0.1

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

WIndows 10 Enterprise

**Comment by geoand** [comment]
`quarkus.default-locale` is a build time property and as mentioned in the Javadoc, it is used by various extensions, it's not meant to affect `Locale.getDefault()`.

As for the command line invocation you mention, my guess is that you are not using it correctly. 
System properties need to be set before the `-jar` option when running `java ....`.

**Comment by waldimiro** [comment]
I set the properties in Intellij Quarkus Configuration
![Screenshot 2022-02-11 at 10 29 25](https://user-images.githubusercontent.com/5328277/153567658-7d4bd009-eab1-484a-a118-f3421ec72222.png)

**Comment by waldimiro** [comment]
Mhh... I tryed but it doesn't work... System.out.println(Locale.getDefault()) prints out every time en_US

**Comment by geoand** [comment]
Well, I tried and it did :)

**Comment by waldimiro** [comment]
Is very strange the behaviour. I will investigate further. Do you think that is more Intellij the problem?

**Comment by geoand** [comment]
Likely

**Comment by waldimiro** [comment]
Intellij starts the app with this line: "C:\Program Files\Java\openjdk-17.0.1\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51088,suspend=y,server=n -Dmaven.multiModuleProjectDirectory=C:\development\nextperience-repo\microservice-parent\dfl\dfl-app -Dquarkus.devservices.enabled=false -Dquarkus.profile=local -Dquarkus.http.port=8068 -Dquarkus.log.level=INFO "-Dquarkus.log.category.\"com.swissimpact\".level=DEBUG" "-Dquarkus.log.category.\"com.swissimpact\".min-level=DEBUG" -Duser.language=de -Duser.country=CH -Duser.variant=CH -Duser.region=CH -Duser.timezone=Europe/Zurich "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2020.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2020.3\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2020.3\plugins\maven\lib\maven-event-listener.jar" -javaagent:C:\Users\<user>\AppData\Local\JetBrains\IntelliJIdea2021.3\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 @C:\Users\taarowa1\AppData\Local\Temp\idea_arg_file1512284394 org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 quarkus:dev

**Comment by suleymanozev** [comment]
@geoand please explain solution

**Comment by suleymanozev** [comment]
Set environment variable:

JAVA_TOOL_OPTIONS=-Duser.language=en -Duser.country=US -Duser.variant=US -Duser.region=US

**Comment by geoand** [comment]
@suleymanozev WDYM?

**Comment by col-panic** [comment]
Somehow I stumbled over this, trying to set the docker container built to a different locale too. 

I'm building the resulting docker image using https://quarkus.io/guides/container-image#jib-options and I guess that none of my approaches so far sticks (I always get en_US, despite setting de_CH in application.properties)

Seems like the [base-jvm-image](https://catalog.redhat.com/en/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f#containerfile) hardcodes lang C.utf8

```
quarkus.jib.platforms=linux/amd64,linux/arm64/v8
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24
```

Not sure how to approache this, maybe using jib jvm properties?

**Comment by col-panic** [comment]
Remark, using `quarkus.jib.jvm-additional-arguments=-Duser.language=de -Duser.country=CH` I could finally manage to get it in.
