### ISSUE TITLE
Quarkus requires the public key to be present at build time, preventing it from using keys generated at runtime

### ISSUE THREAD

**Issue by rafaelfnx** [quarkusio/quarkus#23590]
### Describe the bug

I had already created an issue, but even after about a month and a half it got no response, the only thing I got was a comment with a proposal from @sberyozkin, but he hasn't responded in the last 44 days, so since the last issue is dead, I'm creating a new one to try to come up with a solution to the problem. The original issue is #22536.

**Comment by sberyozkin** [comment]
@rafaelfnx Hi, I've closed the original issue as a duplicate.

Note, there are many issues each of us has to deal with, unortunately we can't prioritize immediately on every new issue reported.
But also, please appreciate it is an open source project - so you are welcome to help and open a PR if it is an urgent issue for you
Thanks

**Comment by geoand** [comment]
> Note, there are many issues each of us has to deal with, unfortunately we can't prioritize immediately on every new issue reported.

Very much +!

@rafaelfnx please try version `2.7.1.Final` and see if it fixes your issue
