### ISSUE TITLE
Typo on "MEASURING PERFORMANCE" page

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#23594]
### Description

There is a typo or say a word too much on the page "https://quarkus.io/guides/performance-measure".
In the Note of the section "Native Memory Tracking", it reads "this feature will add cause an approximately 5-10% performance overhead".

The sentence should have been either "this feature will cause an approximately 5-10% performance overhead" or "this feature will add  an approximately 5-10% performance overhead".

I can make the correction if needed so that you guys don't have too much work, just let me know If I should.

Regards, 
Daniel

**Comment by dwamara** [comment]
So every time I find a typo somewhere I can just make a pull request without issue?

**Comment by geoand** [comment]
Yes exactly. No issue needed

**Comment by geoand** [comment]
Closing as this has since been fixed
