### ISSUE TITLE
Dev services for JMS/ActiveMQ

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#23595]
### Description

I would like to be able to develop and test applications using the JMS/ActiveMQ OpenWire protocol - this is supported by both ActiveMQ 5 and Artemis.

### Implementation ideas

The OpenWire protocol is supported by Artemis on port 61616 https://activemq.apache.org/components/artemis/documentation/latest/openwire.html by default and we already have AMQP dev services which start up Artemis - so it could potentially be done by just supporting a way of exposing that port on Artemis with the AMQP dev services.

Or it could be its own activemq extension? In which case perhaps it could also support ActiveMQ 5 images (e.g. webcenter/activemq).

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
We should extract the AMQP dev service in some common modules. However, we are waiting on settling the images to use in the AMQP dev service (#22976). So, we would need to be sure that ALL the compatible images can support the 2 protocols the very same way.

**Comment by josephearl** [comment]
Would be great if this could also set the appropriate properties for camel-quarkus-activemq when the dev service is used

`camel.component.activemq.brokerURL`, `camel.component.activemq.username`, `camel.component.activemq.password`

**Comment by cescoffier** [comment]
While we could do that we need to be very careful not to have to add properties for all existing extensions. The dev service generates a build item, so the Camel extension should consume it and register the properties.

**Comment by josephearl** [comment]
That probably makes more sense @cescoffier

**Comment by middagj** [comment]
@zhfeng has added DevServices to the quarkus-artemis extension in https://github.com/quarkiverse/quarkus-artemis/pull/55. Would that solve this issue?

**Comment by zhfeng** [comment]
@josephearl so you want to use `quarkus-artemis` and `camel-quarkus-activemq` togather? I think you can use
```
camel.component.activemq.broker-url=%{quarkus.artemis.url}
```
when enable the Artemis DevServices.

**Comment by josephearl** [comment]
Thanks that should work
