### ISSUE TITLE
hibernate-validator Allow specifying alternative constraint validator

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#23600]
### Description

I need to replace the validator for javax.validation.constraints.Email with a custom implementation.
I found this example for programmaticly replacing the validator behind a constraint: https://docs.jboss.org/hibernate/validator/6.2/reference/en-US/html_single/#section-programmatic-constraint-definition
This custom validator should apply for the default validator factory, which lead me to believe I need to use something like this: https://docs.jboss.org/hibernate/validator/6.2/reference/en-US/html_single/#section-programmatic-api-contributor

There is however no way right now to retrieve the ConstraintMappingContributor for the default validator factory in quarkus.

(This follow up https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/How.20to.20wire.20up.20an.20ConstraintMappingContribu)

### Implementation ideas

The jackson ObjectMapper in quarkus is configured by calling all implementations of `ObjectMapperCustomizer#customize` (see
https://quarkus.io/guides/rest-json#json).

Something similar could be done for HV. I.e. call all implementations of `ConstraintMappingContributor#createConstraintMappings`.

**Comment by yrodiere** [comment]
@gsmet From the Zulip discussion, it seems you started looking for a solution, so I assigned this ticket to you. Feel free to ping me and dump the info if you want me to take over.
