### ISSUE TITLE
Test with Testcontainer doesn't create relations

### ISSUE THREAD

**Issue by g-apparence** [quarkusio/quarkus#23608]
### Describe the bug

Hi, 
I cannot run test using test_containers and table with foreign_keys. 
I can persist and check data for one table that's ok. But when this has a relation, this doesn't work.
It seems that all relations are broken launching the testcontainer. (It's currently postgres). 

I've found a log like this for all database relations that should be created. 
```
févr. 11, 2022 1:17:53 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: relation "user_projects" does not exist, skipping
```

I suspect that all foreign keys are not created  correctly and so my test fails. 

### Expected behavior

Tests should properly create the database as in a real environment. 

### Actual behavior

For example, I have this test. 
A simple project is associated to users. 
The test keeps telling me that ```assertEquals(1, project.users.size());``` is false. 

Note: running quarkus and calling http methods manually correctly persist project + users with relation.

```java
@QuarkusTest
@QuarkusTestResource(PostgresTestContainer.class)
public class ProjectCreateTest {

    @InjectMock
    UserAuthApi userAuthApiMock;

    @Inject
    UserProjectApi userProjectApi;

    @Inject
    EntityManager entityManager;

    @AfterEach
    @Transactional
    public void tearDown() {
        ProjectEntity.deleteAll();
        UserEntity.deleteAll();
        Mockito.reset(userAuthApiMock);
    }

    @Test
    @Transactional
    @DisplayName("send a non null project name => creates the project, user is associated to project")
    public void createProject() throws CreateProjectException {
        var userId = createUser();
        CreateProjectDtoReq req = new CreateProjectDtoReq("My project");
        userProjectApi.create(userId, req);
        entityManager.flush();

        List<ProjectEntity> projects = ProjectEntity.findAll().list();
        assertEquals(1, projects.size());
        var project = projects.get(0);
        assertNotNull(project.users);
        assertEquals(1, project.users.size());
    }

    @NotNull
    private UserId createUser() {
        final UserEntity user = new UserEntity();
        user.name = "John";
        user.firstname = "Doe";
        user.email = "jdoes@apparence.io";
        user.company = "apparence";
        user.password = "testtest123";
        user.persist();
        return new UserId(user.uid);
    }
}
```

### How to Reproduce?

1. Create entities with N..N relation for example
2. create a method and persist 
3. test the http method directly using restAssured

### Quarkus version or git rev

last version

**Comment by geoand** [comment]
Please attach a sample project that exhibits the problematic behavior.

In any case, I fail to see how Quarkus could be responsible for this issue, but I'll let the Hibernate folks comment

**Comment by g-apparence** [comment]
Okay that's more a problem with hibernate. 

I found a solution
```java
    @Test
    @Transactional
    @DisplayName("send a non null project name => creates the project, user is associated to project")
    public void createProject() throws CreateProjectException {
        CreateProjectDtoReq req = new CreateProjectDtoReq("My project");
        var result = userProjectApi.create(userId, req);

        List<ProjectEntity> projects = ProjectEntity.findAll().list();
        assertEquals(1, projects.size());
        var project = projects.get(0);

        assertNotNull(result.getUsers());
        assertEquals(1, result.getUsers().size());
        assertNotNull(project.users);
        entityManager.refresh(project); // <-- Without refreshing the project entity. this doesn't fetch the users list correctly. 
        assertEquals(1, project.users.size());
    }
```

The warning seems to occurs before testcontainers populate the database. Maybe removing them could remove some confusions. 
I searched way too long if that was related to a uncommited transaction when actually that was just hibernate that wasn't really refreshed.
