### ISSUE TITLE
conflict between micrometer and stork

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#23623]
### Describe the bug

When I add in the same application the stork extension and the micrometer extension I get an error.

### Expected behavior

Should not conflict with each other.

### Actual behavior

When I build the application I get:

```
[INFO] Running org.acme.ReactiveGreetingResourceTest
2022-02-11 18:56:35,295 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.273 s <<< FAILURE! - in org.acme.ReactiveGreetingResourceTest
[ERROR] org.acme.ReactiveGreetingResourceTest.testHelloEndpoint  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: javax.enterprise.inject.CreationException: 
Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_97d170e1550eee4afc0af065b78cda302a97674c
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
```

### How to Reproduce?

Get https://github.com/vsevel/stork-issue/tree/micrometer_stork_conflict
```
mvn clean package
```

### Quarkus version or git rev

2.7.1

**Comment by michalszynkiewicz** [comment]
@vsevel could you check if removing the client from the MyServiceDiscovery makes the error disappear?

**Comment by vsevel** [comment]
@michalszynkiewicz 
you are correct. it works with this https://github.com/vsevel/stork-issue/commit/bd550b63413b53f3dae9a8bac8a39e00e1b36b64

**Comment by ebullient** [comment]
Is that a case of the discovery client making outbound http requests (that should in theory be measured) before things have been initialized?

**Comment by vsevel** [comment]
I do not think it is about making the calls (it works when I lazy init the proxies), rather than trying to initialize the rest proxy too early.

**Comment by michalszynkiewicz** [comment]
Haven't started looking at it yet but it seems to that stork initialization happens to early

**Comment by ebullient** [comment]
Not sure if there is anything the micrometer initialization should change...
