### ISSUE TITLE
@IfBuildProfile should/could support mutiple profiles

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#23637]
### Description

Since smallrye-config, and quarkus support multiple profiles. It would be nice if the annotation ` @IfBuildProfile` would work the same way.

We can start the application with `-Dquarkus.profile=dev,foo`, smallrye will understand that there are two profiles dev and foo, but ` @IfBuildProfile` will see "dev,foo" as one profile, which makes it hard/impossible to restrict bean to a single of the profile.

### Implementation ideas

- ` @IfBuildProfile` could be repeatable as `@IfBuildProperty`
- should split the profiles via the comma
- should activate if one matches example if my class has `@IfBuildProfile("foo")` if I start with profiles=dev,foo; it should work.
  - otherwise  `@IfBuildProfile("foo")`  and `@IfBuildProfile("dev")` should be used

**Comment by mkouba** [comment]
`@IfBuildProfile` is built on top of [Quarkus config profiles](https://quarkus.io/guides/config-reference#profiles) and AFAIK only  _single build profile_ can be active. @radcortez correct me if I'm wrong pls.

> We can start the application with -Dquarkus.profile=dev,foo

Note that `@IfBuildProfile` completely ignores the _runtime profiles_ because the set of known beans is determined during build, i.e. it's read-only at runtime.

**Comment by radcortez** [comment]
> `@IfBuildProfile` is built on top of [Quarkus config profiles](https://quarkus.io/guides/config-reference#profiles) and AFAIK only _single build profile_ can be active. @radcortez correct me if I'm wrong pls.

Correct. SR Config does support multiple profiles, but Quarkus does not. It is possible to have some limited use of multiple profiles in Quarkus through SR Config, but it was never officially supported because there was no interest in it.

**Comment by famod** [comment]
> because there was no interest in it

I think there is general interest, but IIRC there were objections w.r.t. users shooting themselves in the foot.
I had/have mutliple occasions where the absense of that feature led to awkward and badly maintainable workarounds

**Comment by DeMol-EE** [comment]
To add my 2 cents, I feel like having the option to include/exclude a bean for only exactly one profile (`@IfBuildProfile`) or only exactly all profiles except one (`@UnlessBuildProfile`) is a little restrictive. Would it be feasible to make `@IfBuildProfile` repeatable so one could enumerate the profiles for which the bean should be included? Or to change the datatype of `value` from string to array?

**Comment by mkouba** [comment]
> To add my 2 cents, I feel like having the option to include/exclude a bean for only exactly one profile (`@IfBuildProfile`) or only exactly all profiles except one (`@UnlessBuildProfile`) is a little restrictive. Would it be feasible to make `@IfBuildProfile` repeatable so one could enumerate the profiles for which the bean should be included? Or to change the datatype of `value` from string to array?

I think there are two different problems:
1. Be able to activate multiple profiles during build
2. Be able to activate a bean for multiple profiles

I'm going to talk about (2). `@IfBuildProfile` was originally designed to work with the default profiles (prod, dev, test) where a single value was enough. I agree that if custom profiles are used then a single value is restrictive. We could change the type of `value` to an array but I'm afraid that it wouldn't be backward compatible. A repeatable annotation seems to be OK. @geoand WDYT?

**Comment by geoand** [comment]
> A repeatable annotation seems to be OK. @geoand WDYT?

Yeah, I think this makes most sense.
But what would the semantics be, `OR` or `AND`?

**Comment by mkouba** [comment]
> But what would the semantics be, `OR` or `AND`?

I think that for now it should be `OR` for `@IfBuildProfile` and `AND` for `@UnlessBuildProfile` because only single build profile can be active?

**Comment by geoand** [comment]
Yeah, that sounds most reasonable

**Comment by radcortez** [comment]
I think it will depend if we want to official support multi profile.

**Comment by mkouba** [comment]
> I think it will depend if we want to official support multi profile.

Yep, the thing is that implementation of (2) should be quite straightforward and without side-effects while (1) might be a little bit trickier.

**Comment by radu-muresan** [comment]
Hi guys,

My use case is I want to use a bean (e.g. SomeBeanImpl) for profile 'prod' and another bean (e.g. SomeBeanMock) for profiles 'dev' and 'test'.

currently I tried:
@UnlessBuildProfile('prod')
SomeBeanImpl
gives me an error when not using the 'prod' profile, can elaborate if it is the case, but the mock bean is not inserted.

after that I used:
@IfBuildProfile('prod')
SomeBeanImpl

@IfBuildProfile('dev')
SomeBeanMock

It works, but cannot use the 'test' profile for integration tests.

My goal would be to use:
@IfBuildProfile('prod')
SomeBeanImpl

@IfBuildProfile('dev')
@IfBuildProfile('test')
SomeBeanMock

which would do the trick for me. (solution 2 proposed by @mkouba)

Any update on this issue or a suggestion to solve this scenario? @geoand @mkouba 

Thanks guys!

**Comment by mkouba** [comment]
> gives me an error when not using the 'prod' profile, can elaborate if it is the case, but the mock bean is not inserted.

What kind of error? The `SomeBeanImpl` shoud be available in `test` and `dev`.

**Comment by radu-muresan** [comment]
I ended up using:
@IfBuildProfile('prod')
SomeBeanImpl

@UnlessBuildProfile('prod')
SomeBeanMock

and it did the trick.

The error probably was an incorrect use of @IfBuildProfile with @UnlessBuildProfile, please disregard that part.

Thanks!

**Comment by manovotn** [comment]
This issue got a little stale.
@radcortez is there something the PR is waiting for? It seems to have passed CI and got an approval as well.

**Comment by radcortez** [comment]
I guess we were waiting for @gsmet answer regarding which version to include.

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/pull/28091 does not seem to resolve this issue, i.e. you can't specify multiple profiles with `@IfBuildProfile`.
