### ISSUE TITLE
TracingTest failures in CI on Windows

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2363]
Test failures:
* https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=1768 (from #2321)
* https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=1744 (from #2352)
* https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=1716 (from #2343)

Possibly others?

The test was introduced in https://github.com/quarkusio/quarkus/commit/0277f3cff9cbdab7de55b950bc3b34a2247a8cb9.

**Comment by dmlloyd** [comment]
@pavolloffay is of the opinion that this seems like a bug in FT.

**Comment by dmlloyd** [comment]
My recommendation would be to disable `TracingTest` as a workaround until the problem is resolved.

**Comment by machi1990** [comment]
Possibly a duplicate of #2187 ?

**Comment by ppalaga** [comment]
Also in https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=1770 (from #2361)

I saw it happening only on Windows, so we should maybe exclude it only in the Windows job, e.g. via adding `-Dtest=!TracingTest` ?

**Comment by dmlloyd** [comment]
You're right, this is a duplicate of #2187.

**Comment by pavolloffay** [comment]
@dmlloyd yeah, it looks like a bug in FT. The method should be retried 3 times but in some cases it is only retried 2 times for more see https://github.com/quarkusio/quarkus/issues/2187#issuecomment-486600799.

We could change the asserts to deal with it if you prefer that.
