### ISSUE TITLE
Selective registration of CDI Beans classes from a third-party library

### ISSUE THREAD

**Issue by vtdmitriy** [quarkusio/quarkus#23643]
### Description

I would like to be able to register specific classes from a third-party library, and not just the entire library through the quarkus.index-dependency property.
Described my particular problem at [Stackoverflow](https://stackoverflow.com/questions/71094035/quarkus-registering-cdi-beans-classes-from-a-third-party-library).

**Comment by geoand** [comment]
This can sort of manually be done using https://quarkus.io/guides/class-loading-reference#hidingremoving-classes-and-resources-from-dependencies, so I am in favor of closing this as `won't fix`

**Comment by stuartwdouglas** [comment]
The other approach would be to create an extension and use `AdditionalBeanBuildItem`. I don't think we really want to add any user facing API's around this.

**Comment by manovotn** [comment]
> The other approach would be to create an extension and use `AdditionalBeanBuildItem`. I don't think we really want to add any user facing API's around this.

+1, this sounds like a typical use case for `AdditionalBeanBuildItem` (which is Quarkus equivalent for adding beans via portable extensions in Jakarta EE CDI).
