### ISSUE TITLE
Kubernetes deploy deletes load-balancer when service-type=load-balancer

### ISSUE THREAD

**Issue by zoperado** [quarkusio/quarkus#23651]
### Describe the bug

Up to quarkus 2.1.1, when  deploying to gke  with 
`quarkus.kubernetes.service-type=load-balancer`  the behaviour was as expected but after upgrading to 2.7.1 it started deleting already deployed services and load-balancers

if no workload service is defined then the service is created and a load-balancer gets configured with a  new IP address

When moving to quarkus 2.7.1 (and likely earlier versions) then the behaviour is this

if a service was defined then delete the service.

This leaves the deploy without a load-balancer. To get one you have to deploy twice. However, completely deleting the service now causes a new IP to get assigned (because deploying twice does work), albeit with a warning saying that it couldn't find anything to delete. 

### Expected behavior

Deploy to kubernetes with  `quarkus.kubernetes.service-type=load-balancer` and 
crete service and load-balancer only if it's not available (and don't delete existing ones)

### Actual behavior

The latest version deletes deployed services and loadbalancers causing the application to be unavailable during redeploys and also causing the newly deployed loadbalancer to acquire an new ip address. This happens because GKE thinks that this is a completely fresh service (and lb) since everything was deleted. 

The behaviour for  node-port  however, `quarkus.kubernetes.service-type=node-port' ,  seems to be still OK

**Comment by geoand** [comment]
@iocanel I think this was a deliberate change, right?

Maybe we should have a property that controls the behavior?

**Comment by iocanel** [comment]
Possibly a regression. Do we now if it works as expected In 2.7.0.Final?

**Comment by zoperado** [comment]
I noticed it does the same with node-port (wrongly said hat "The behaviour for node-port however, `quarkus.kubernetes.service-type=node-port' , seems to be still OK").

I will try to walk versions back to see when it started. I'm worried that this breaks "rolling" kubernetes updates when the entire service is take off. The environment this happens is gke autocluster btw.

**Comment by zoperado** [comment]
> Possibly a regression. Do we now if it works as expected In 2.7.0.Final?

Have walked all the way down and it seems it's happening from 2.1.2 to 2.2.2. That is, 2.1.2 is the last good one and  the kubernetes client doesn't delete anything and from 2.2.2 all the way up to 2.7.1 it deletes all services on redeploy. Load balancer or node-port, causing gke to assign new IP addresses for nodes that have been removed and recreated.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by Sgitario** [comment]
I think this is the expected behavior from https://github.com/quarkusio/quarkus/pull/19795. 
Using the latest version of Quarkus, the service will be reinstalled after being deleted. However, you can control the deployment strategy from https://github.com/quarkusio/quarkus/pull/31724 not to delete the service, and only make updates. I'm linking this pull request to the issue.
