### ISSUE TITLE
Jib jvm build permissions issues

### ISSUE THREAD

**Issue by doczico** [quarkusio/quarkus#23665]
### Describe the bug

While creating a container image using jib (fast-jar) the whole /work folder (content included) is created with 755 and root as owner even when the username is specified or the image run as another user.
which in my case lead to this issue
`Caused by: com.arjuna.ats.arjuna.exceptions.ObjectStoreException: ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: ObjectStore/ShadowNoFileLockStore/defaultStore/
`

### Expected behavior

the /work folder and sub directories to be created with the specified (or image default) user as owner

### Actual behavior

the /work folder is created with root as owner

### How to Reproduce?

use jib to build the container image as fast-jar

### Output of `java -version`

11

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8

**Comment by geoand** [comment]
Thanks for reporting!

How can reproduce this issue?

**Comment by doczico** [comment]
Thank you very much for the (ultra) quick fix
