### ISSUE TITLE
Cannot produce a Linux executable

### ISSUE THREAD

**Issue by AndreasMaita** [quarkusio/quarkus#23676]
Dear Community,

I'm new to Quarkus, and I am trying to follow along the getting-started guides. My goal is to build a Linux executable, so I can run it inside a docker container. 

I'm running a Debian Linux Machine on my MacBook Pro M1, since I have read that there are issues compiling native executables on Android Silicon Chips. 

Here is an overview of my machine's architecture:
![image](https://user-images.githubusercontent.com/47466613/153890836-2ab7b05f-1ad8-4e77-bb91-5269400afb12.png)

I installed the GraalVM and Java, as recommended by the GraalVM getting started website. Here is a Screenshot of my environment Variables:
![image](https://user-images.githubusercontent.com/47466613/153891123-648d8075-bc2f-41e4-a101-f4b35948b323.png)
![image](https://user-images.githubusercontent.com/47466613/153891003-baf7f5f9-ad6c-459e-a3f9-643ef739bf95.png)

Also Docker is running without Issues on my Machine:
![image](https://user-images.githubusercontent.com/47466613/153890934-133a46df-a868-4a4c-a634-5add35967ce0.png)

I know that i can use the mvn wrapper to execute mvn goals, I installed it anyways:
![image](https://user-images.githubusercontent.com/47466613/153891169-a76dd6e0-2852-4910-ab27-567110090a57.png)

Here is the Issue. When I'm trying to build a native image with:
```
mvn package -Dnative
```

Everything works fine and I get my *runnable.

However when i try to build a general linux image with this command 
```
mvn package -Dquarkus.native.container-build=true
```
i get following output:
![image](https://user-images.githubusercontent.com/47466613/153893211-a26590d3-c2fe-4c32-bec7-f585918e84f8.png)

I have googled for days now and can't find a solution. Can someone tell me what im doing wrong?

Thanks so much in advance!

**Comment by famod** [comment]
I suppose you have googled something like _MacBook Pro M1 docker "exec format error"_?

**Comment by AndreasMaita** [comment]
> I suppose you have googled something like _MacBook Pro M1 docker "exec format error"_?

Yes, and went down the deep rabbithole that comes with it. I have tried every single solution out there. However, This issue is not about the M1, since i already created a VM that runs Linux Debian, which should have the known chip architecture.

**Comment by lucifer4j** [comment]
Hi! 

When using `-Dquarkus.native.container-build=true`, a docker image is downloaded in which the native executable is built. As you can see from the logs, its `quay.io/quarkus/ubi-quarkus-native-image` in this case and its a `x86_64` image. The error you see
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
results from running a `x86_64` container on an `arm`  host. 

Further, it seems there is no ARM variant available for this [image](https://quay.io/repository/quarkus/ubi-quarkus-native-image?tag=latest&tab=tags). https://github.com/quarkusio/quarkus-images/issues/83 is probably the right issue to track this development. One of the comments on that issue also links to a blogpost showing how to use a custom ARM image for this purpose.

**Comment by AndreasMaita** [comment]
> 

Thank you very much for your input. I will take a look at this other issue!
