### ISSUE TITLE
Kotlin serializer - Flow - don't work

### ISSUE THREAD

**Issue by nenros** [quarkusio/quarkus#23678]
### Describe the bug

I ave problem with enabling serialization on Flow(from kotlin coroutine) response. It doesn't work at all

### Expected behavior

It should produce beautiful json.

### Actual behavior

```
Request failed: kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

### How to Reproduce?

Added such endpoint in integration test: 
```kotlin
    @Path("flow")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun flowHello() = flowOf(Person("Jim Halpert"))
```
in https://github.com/quarkusio/quarkus/blob/ea4099305aed07d0428bf4aa53de61142a2e7499/integration-tests/kotlin-serialization/src/main/kotlin/io/quarkus/it/kotser/GreetingResource.kt

and test
```kotlin

    @Test
    fun testGetFlow() {
        When {
            get("/flow")
        } Then {
            statusCode(200)
            body(`is`(
                """
[
  {
    "name": "Jim Halpert",
    "defaulted": "hi there!"
  }
]
""".trimIndent()))
        }
    }
````

in 

### Output of `uname -a` or `ver`

20.6.0

### GraalVM version (if different from Java)

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### Quarkus version or git rev

master

**Comment by pwlan** [comment]
Hi, 
I have the exact same error message, but without using flow. I did some digging and found
```
class KotlinSerializationMessageBodyWriter(private val json: Json) : AllWriteableMessageBodyWriter() {

    override fun writeTo(
        o: Any, type: Class<*>, genericType: Type, annotations: Array<Annotation>, mediaType: MediaType,
        httpHeaders: MultivaluedMap<String, Any>, entityStream: OutputStream
    ) {
        JsonMessageBodyWriterUtil.setContentTypeIfNecessary(httpHeaders)
        if (o is String) { // YUK: done in order to avoid adding extra quotes...
            entityStream.write(o.toByteArray(StandardCharsets.UTF_8))
        } else {
            json.encodeToStream(o, entityStream)
        }
    }
```
My guess is that the 'Any' from the error message is referring to the parameter 'o' here.
`encodeToStream` is using a reified type parameter to determine the Serializer. 
And this would be Any and not the exact type at runtime.

**Comment by pwlan** [comment]
Hi,
thanks for the fix, @gsmet and @evanchooly.
But it looks like this has introduced a new issue.
When using Lists, the following error ocurrs.
 
```
Serializer for class 'ArrayList' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

The issue can be easily reproduced:
```
fun main() {
    val arrayList = ArrayList<String>()
    Json{}.encodeToString(serializer(arrayList.javaClass), arrayList) // this will fail.
}
```
