### ISSUE TITLE
@Inject BeanManager in @QuarkusTest annotated class does not work

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#2368]
Hi @mkouba,

This is in regards to the issue we discussed on Zulip.

I cannot `@Inject` `BeanManager` into a `@QuarkusTest` annotated class. When I have a test class like this one:

```java
@QuarkusTest
public class EventsBypassTest {

    @Inject
    BeanManager bm;

    // ...
}
```

It fails with the following error:

```plain
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in com.github.sarxos.abberwoult.EventsBypassTest
[ERROR] test_startupEventReceived  Time elapsed: 0.007 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.github.sarxos.abberwoult.EventsBypassTest]: Failed to inject field javax.enterprise.inject.spi.BeanManager com.github.sarxos.abberwoult.EventsBypassTest.bm
Caused by: java.lang.RuntimeException: Failed to inject field javax.enterprise.inject.spi.BeanManager com.github.sarxos.abberwoult.EventsBypassTest.bm
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException
```

In the same time I can get BeanManager from CDI (and this is what I did as a workaround to the problem):

```java
@Test
public void test_eventsReceived() throws InterruptedException {
    final BeanManager bm = CDI.current().getBeanManager();
    // ... use bean manager here
}
```

This happens on Quarkus `0.14.0`.

**Comment by mkouba** [comment]
For the record: the problem is that we don't provide the real beans for built-in beans (`BeanManager`, `Event`, etc.) but resolve them directly during build. This works fine for beans but not for `@QuarkusTest`.

**Comment by sarxos** [comment]
Thank you @mkouba!

**Comment by mkouba** [comment]
Not at all. I've merged the PR from @geoand and we'll address other built-in beans in https://github.com/quarkusio/quarkus/issues/2459.
