### ISSUE TITLE
quarkus startup time very slow when datasource connection pool property overriden in application properties

### ISSUE THREAD

**Issue by allwinboss** [quarkusio/quarkus#23700]
### Describe the bug

Hi Team,

My  application is built with Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, spring-data-jpa, spring-di, vertx] .it  takes long time to startup . i,e 16.3 sec  when I override the connection pool setting as below in application.properties file, But when I remove the connection pool setting and allow application to  boot with default pool setting it takes only 4.2 secs.

Quarkus version: 
<quarkus.platform.version>2.7.1.Final</quarkus.platform.version>

application.properties:
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=10
quarkus.datasource.jdbc.initial-size=10

 command used to start the application:  java -jar  ./mymodule/quarkus-app/quarkus-run.jar

please advice on the details  to resolve this issue.

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by Sanne** [comment]
Hi, could you give us some more details? Is it possible your Database is very slow at establishing and authenticating new connections?

We certainly don't have this experience when testing on my simple local databases, so I'm going to need your help investigating a bit.

**Comment by allwinboss** [comment]
Hi Sanne,

I'm involved in migrating spring-web (springboot) microservices  to quarkus -resteasy  microservices  and both spring boot and quarkus services are connecting to same oracle database server  and with same select query and table using spring jparepository.


spring boot configuration :

Built the spring-web with hikariCp default connection pool setting 'maximumPoolSize' =10 and 'minimumIdle'  is same as maximum pool size (10). The spring boot was able to boot the app with startup time "9.969 seconds". 
----------------------------------
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-02-15 17:38:24.725  INFO 10316 --- [  
2022-02-15 17:38:30.344  INFO 10316 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-02-15 17:38:30.425  INFO 10316 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-02-15 17:38:30.519  INFO 10316 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.4.Final
2022-02-15 17:38:30.782  INFO 10316 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-02-15 17:38:31.079  INFO 10316 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.Oracle12cDialect
2022-02-15 17:38:32.376  INFO 10316 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-02-15 17:38:32.391  INFO 10316 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-02-15 17:38:33.034  WARN 10316 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-02-15 17:38:33.763  INFO 10316 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-02-15 17:38:33.851  INFO 10316 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): xxxx (http) with context path '/XXX'
2022-02-15 17:38:33.873  INFO 10316 --- [           main] c.c.a.a.f.XXXXXApplication    : Started XXXXXXApplication in 9.969 seconds (JVM running for 11.046)
----------------------------------


when "1000" user requests are  submitted to springboot microservice with 100 concurrent call ,the   total response time is "11.853 seconds".

Concurrency Level:      100
total requests:      1000
Time taken for request to complete:   11.853 seconds

stopped the spring-boot app.

Quarkus:

Built the quarkus-resteasy with agroal  default  connection pool setting (max-size=20,min-size=0,initial-size=0 ) ,The quarkus was able to boot the app with startup time "6.637s". 


started the quarkus:
--__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-15 17:56:02,256 INFO  [io.quarkus] (main) xxxx-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.6.3.Final) started in 6.637s. Listening on: http://0.0.0.0:xxxx
2022-02-15 17:56:02,259 INFO  [io.quarkus] (main) Profile xxx activated.
2022-02-15 17:56:02,262 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, spring-data-jpa, spring-di, vertx]
---------------------------------------------------------------------
when   1000 individual user requests are  submitted to quarkus microservice with 100 concurrent call, app took around "31.783 seconds" total response time .

Concurrency Level:      100
total requests:     1000
Time taken for request to complete:  31.783 seconds

-stopped the quarkus app.

On analyzing the logs further , i could see the first 1 to 10 requests took additional processing time to fetch user details ,so I decided to increase the db connection pool initial size  to handle the user request to database swiftly for first 10 individual user request .
From  Quarkus data source configuration guide  , I found that agroal data source  initial pool size is 0  ,  so I Overrode the  connection setting of agroal data source in application.properties as below  but when booted the quarkus app ,the start up time is  '21.233s' which is huge.


quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=10
quarkus.datasource.jdbc.initial-size=10

----------------------------------------------
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-15 17:25:14,914 INFO  [io.quarkus] (main) xxxxx 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.6.3.Final) started in 21.233s. Listening on: http://0.0.0.0:xxx
2022-02-15 17:25:14,924 INFO  [io.quarkus] (main) Profile xxx activated.
2022-02-15 17:25:14,926 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, spring-data-jpa, spring-di, vertx]
---------------------------------------------

though with huge start up time.  quarkus app was able to complete the next set of 1000 user requests faster after setting the initial-size to 10.

please advice on this quarkus startup time issue which is occurring when the agroal datasource initial-size is increased.

thanks
Allwin jacob

**Comment by Sanne** [comment]
Thanks, that's interesting. Good idea to make sure a defined set of connections are initialized; so you've set the Quarkus initial size to 10, but what's the initial size in Spring Boot?

**Comment by allwinboss** [comment]
Hi Sanne,
There is no 'initial-size' config property defined in hikariCp Datasource config, but the there is a config property  'minimumIdle' is same as maximum pool size by default,  which is set when spring boot starts up to have the idle connection readily available  for any database query request from Repository layer. .

spring.datasource.hikari.maximum-pool-size= 10 #maximum pool size

HikariCP Reference: 

🔢minimumIdle
This property controls the minimum number of idle connections that HikariCP tries to maintain in the pool. If the idle connections dip below this value and total connections in the pool are less than maximumPoolSize, HikariCP will make a best effort to add additional connections quickly and efficiently. However, for maximum performance and responsiveness to spike demands, we recommend not setting this value and instead allowing HikariCP to act as a fixed size connection pool. Default: same as maximumPoolSize

🔢maximumPoolSize
This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections. Basically this value will determine the maximum number of actual connections to the database backend. A reasonable value for this is best determined by your execution environment. When the pool reaches this size, and no idle connections are available, calls to getConnection() will block for up to connectionTimeout milliseconds before timing out.  Default: 10


can there be similar kind of minimum idle connection setup  that can be initiated in agraol datasource connection pool when Quarkus starts up ,so that the initial  user request can be served quickly?.

thanks
Allwin jacob

**Comment by allwinboss** [comment]
Hi Sanne,
do you have  updates on the slow boot time occurring due to initial size connection pool override in agroal?.

**Comment by allwinboss** [comment]
> Hi Sanne, There is no 'initial-size' config property defined in hikariCp Datasource config, but the there is a config property 'minimumIdle' is same as maximum pool size by default, which is set when spring boot starts up to have the idle connection readily available for any database query request from Repository layer. .
> 
> spring.datasource.hikari.maximum-pool-size= 10 #maximum pool size
> 
> HikariCP Reference:
> 
> 🔢minimumIdle This property controls the minimum number of idle connections that HikariCP tries to maintain in the pool. If the idle connections dip below this value and total connections in the pool are less than maximumPoolSize, HikariCP will make a best effort to add additional connections quickly and efficiently. However, for maximum performance and responsiveness to spike demands, we recommend not setting this value and instead allowing HikariCP to act as a fixed size connection pool. Default: same as maximumPoolSize
> 
> 🔢maximumPoolSize This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections. Basically this value will determine the maximum number of actual connections to the database backend. A reasonable value for this is best determined by your execution environment. When the pool reaches this size, and no idle connections are available, calls to getConnection() will block for up to connectionTimeout milliseconds before timing out. Default: 10
> 
> can there be similar kind of minimum idle connection setup that can be initiated in agraol datasource connection pool when Quarkus starts up ,so that the initial user request can be served quickly?.
> 
> thanks Allwin jacob

Hi Sanne,
could you please advise on the slow boot time occurring due to initial size connection pool override in agroal?.is it possible to have minimum idle connection settings on start up in agroal similar to hikariCP?.

**Comment by allwinboss** [comment]
@Sanne : could you please advise on the slow boot time occurring due to initial size connection pool override in agroal?

**Comment by Sanne** [comment]
Hi @allwinboss, sorry I'm not sure - I'd need to try reproducing this locally, but won't have the time this week.

Fundamentally it seems Agroal and HikariCP follow a slighlty different design and strategies - from reading the HikariCP it's not clear to me if it will actually pre-fill the pool: `minimumIdle` does not suggest that it would - and the name suggests it being applied onto _existing connections_.

If that's the case that would be a reasonable explanation for the difference, and if you want (need) Quarkus to behave the same you can set `initial-size=0` or to `=1` depending what you want.

Or higher if follow-up performance is more important to you than bootstrap times - frankly it would seem Quarkus lets you choose, while Hikari does not.

**Comment by allwinboss** [comment]
@Sanne : did you check in your local on the boot time response variation  when setting initial size to higher value from 0 to 5 or 10?

**Comment by initshdb** [comment]
@Sanne in a quarkus application can the default Agroal be replaced by another connection pool like HikariCP or Oracle UCP? is there any property to choose and configure for a different CP instead Agroal, like in Spring Boot allows to replace the default HikariCP with another CP? Or Quarkus only works with Agroal?

**Comment by geoand** [comment]
@initshdb Agroal is the only connection pool we support

**Comment by geoand** [comment]
Is what was originally reported here still a problem in Quarkus?

**Comment by Sanne** [comment]
I'm not even sure this is a problem - just a different _default_ behaviour. See my responses above to try reconfiguring the behaviour, but it depends on what you all want.

**Comment by Sanne** [comment]
I think we can close it, but I haven't heard back from the reporter.
Let's close, but feel free to re-open if I'm missing something.
