### ISSUE TITLE
Stack traces debugging in reactive code

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#23708]
### Description

In Spring reactive, there is good support for useful stack traces. Before running SpringBootApplication.run() one can insert

`Hooks.onOperatorDebug();//overhead -> only dev not for production`
or
`ReactorDebugAgent.init();//almost no overhead -> instrumentation with checkpointing`

Could be something similar added to quarkus. Currently, if an exception happens it is really hard to find where it has occurred.

See "Reactor Debug agent - production-ready assembly back-tracing" section under https://spring.io/blog/2019/03/28/reactor-debugging-experience

### Implementation ideas

Spring instruments the code by adding checkpoint on each operator
https://projectreactor.io/docs/core/release/reference/#checkpoint-alternative

**Comment by Ladicek** [comment]
Yea this is more like CC @jponge @cescoffier

**Comment by jponge** [comment]
We haven't had successful experiments so far, see https://github.com/smallrye/smallrye-mutiny/issues/177

**Comment by murphye** [comment]
@jponge I just want to +1 this issue. From a developer end user perspective this is very important especially for those learning reactive. Thanks.
