### ISSUE TITLE
OIDC Token Propagation only works with the non-reactive rest-client

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#23707]
### Description

The OIDC Token Propagation extension (quarkus-oidc-token-propagation) has a dependency to the `quarkus-rest-client` extension so it cannot be used with the reactive one.

### Implementation ideas

Provides two extensions, one with the blocking client and a new one with the reactive client.

**Comment by sberyozkin** [comment]
Hi Loic @loicmathieu It is in 2.7.1 now: https://github.com/quarkusio/quarkus/tree/2.7.1.Final/extensions/oidc-token-propagation-reactive

**Comment by sberyozkin** [comment]
@loicmathieu Note the reactive version does not do yet the token exchange before the propagation, is it something that you need ? I'd like to see if someone is actually interested in this option before adding that code to the reactive equivalent

**Comment by loicmathieu** [comment]
@sberyozkin so this is missing in the guide, do you want me to create a PR to add it ?

Currently, I didn't need the token exchange, only propagation

**Comment by loicmathieu** [comment]
@sberyozkin just saw it's documented just under at https://quarkus.io/guides/security-openid-connect-client#reactive-token-propagation you can close this issue, sorry about that.

**Comment by sberyozkin** [comment]
@loicmathieu Np at all, was done to help @FroMage to simplify some of Renarde's security code
