### ISSUE TITLE
Modules should allow multiple sourceDirectories

### ISSUE THREAD

**Issue by evacchi** [quarkusio/quarkus#2370]
CompilerProviders rely on the core file-watch routine for hot-reloading. However, the internal data model (`DevModeContext.ModuleInfo`) only allows for *one* single `sourcePath` per module. 

For Kotlin, the work-around is to override the default `sourceDirectory` in the Maven project to point to `scr/main/kotlin`. However, this affects the regular Java compilation process.

This is a limitation for any project that combines different languages, e.g. Kotlin + Java. Maven's data model allow for multiple source directories: these should be retrievable using the programmatic API `MavenProject#getCompileSourceRoots()` which is available to any Mojo.

I am assuming Gradle provides a similar API.

**Comment by evacchi** [comment]
Hi @aloubyansky I have just thrown together #2439 a first attempt that we can iterate upon together, if you'd like. Let me know what you think, especially on how to do proper tests (missing now).

**Comment by evacchi** [comment]
**caveat**:  because I am relying on Mojos updating the source directories, it requires that users willingly invoke `mvn $some-other-phase quarkus:dev` instead of `mvn quarkus:dev` alone, otherwise the other mojos won't be triggered and therefore, only the default source directory will be there. e.g. `mvn compile quarkus:dev`. Because this might be surprising for users, it's important to decide whether this is good enough or we should  take a better approach; 

so just to keep the discussion going, the limitation above might be annoying, besides I am not 100% sure how other plugins are supporting additional source directories, but it seems like both scala and kotlin and Maven plugin are a little ad-hoc. So one thing we could do is to ask people to add to the **quarkus plugin** a 

```
<configuration><sourceDirectories>...</sourceDirectories>
```
another thing we could do, is to add to `CompilationProvider` a way to specify the default source directory just like we do for supported extensions.

**Comment by aloubyansky** [comment]
That's good enough as a first step. It's merged. We'll create new issues for subsequent improvements. Thanks for your contribution!
