### ISSUE TITLE
ArC: Decorator for built-In Bean Event<T> broken

### ISSUE THREAD

**Issue by JHahnHRO** [quarkusio/quarkus#23713]
### Describe the bug

It seems that with 2.7.1.Final it is no longer possible to decorate the built-in bean `Event<T>`. This was still possible in October, with version 2.2.3.Final.

### Expected behavior

The built-in bean `Event<T>` should be decorate-able as per the [CDI Spec](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#decorators)

> Decorators may be associated with any managed bean that is not itself an interceptor or decorator, or with any built-in bean other than the built-in bean with type `BeanManager` and qualifier `@Default`.

### Actual behavior

The decorator is picked up by Quarkus, because if I remove the `@Priority`, then the log-message
`INFO: The decorator com.example.EventDecorator does not declare any @Priority. It will be assigned a default priority value of 0.`
appears. But it is not applied to the bean, because the test fails.

### How to Reproduce?

Define two classes like so:
```
@Decorator
@Priority(Interceptor.Priority.APPLICATION)
public abstract class EventDecorator<T> implements Event<T>, Serializable {

    @Inject
    @Delegate
    @Any
    Event<T> delegate;

    @Inject
    EventCollector eventCollector;

    @Override
    public void fire(final T event) {
        eventCollector.collect(event);
        delegate.fire(event);
    }
}
```
and
```

@ApplicationScoped
public class EventCollector {

    List<Object> firedEvents = new ArrayList<>();

    public List<Object> getFiredEvents() {
        return firedEvents;
    }

    public <T> void collect(final T event) {
        firedEvents.add(event);
    }
}
```
And run the following Test:
```

@QuarkusTest
class EventDecoratorTest {

    @Inject
    EventCollector eventCollector;

    @Inject
    Event<Integer> event;

    @Test
    void testDecorator(){
        event.fire(42);

        assertThat(eventCollector.getFiredEvents()).contains(42);
    }
}
```

### Output of `java -version`

11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by mkouba** [comment]
@JHahnHRO I don't think this ever worked because a subclass is never generated for built-in beans, including `Event`. Are you sure it worked in 2.2.3.Final? Also note that decorators support in ArC is a bit limited.

**Comment by JHahnHRO** [comment]
Reasonably sure. I used such a decorator to log uncaught exceptions thrown from `@ObservesAsync` methods, since Quarkus seems to swallow those silently.

**Comment by mkouba** [comment]
Hm, I've tried to modify the config quickstart and it did not work even in 2.2.3.Final: https://github.com/mkouba/quarkus-quickstarts/tree/event-decorator/config-quickstart

**Comment by manovotn** [comment]
I am also fairly confident this was never supported. Quarkus has only limited decorator support and having them applied to built-in beans is certainly not one of the base scenarios that were covered so far :-)

**Comment by JHahnHRO** [comment]
Then I must have made a mistake back then. I apologise for the confusion I caused.

I understand that it is a corner-case, but is it reasonable to support that? In the project I'm currently working on, a lot of the business logic is implemented by firing a variety of async events for the various stages of processing the input to output. It is not just useful to have the exception-logging decorator.

I was also planning to implement a "process overview" / "status monitoring" feature soon that would collect and display the async events of every currently active business process that have been fired so far. The idea was to collect the events at the source by decorating the generic `Event<T>` instead of duplicating a ton of observer methods for the various intermediate event types which would be comparatively work-intensive and fragile to change (there's also the wrinkle that async observer methods would potentially observe the events out of order which complicates the feature further)


While reading the docs yesterday, I stumbled upon the `@WithCaching Instance<T>` feature. I haven't bother to look through the source code, but if I was asked to implement such a thing myself, decorating the `Instance<T>` bean would have been my first instinct. Maybe that's a point in favour of decorating built-in beans?

**Comment by manovotn** [comment]
> ... instead of duplicating a ton of observer methods for the various intermediate event types which would be comparatively work-intensive and fragile to change ...

You could probably achieve the same by creating a bean with a generic observer that will catch all your events - basically observing `Object` type (in sync/async variant, whichever you want).
You can also make use of [`EventMetadata`](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#event_metadata) to figure out additional bits about the payload.
Would that sort out your problem?

Otherwise I get what you're asking for, just offering an alternative that might work for you :)

**Comment by mkouba** [comment]
I'm not sure it's worth the effort TBH. The decorators are very difficult to implement even for "regular" beans. That said, I did not look into details and how difficult it would be for built-in beans, i.e. `Instance` and `Event`. From my point of view it's a low priority nice-to-have issue.

Also note that a decorated `Event` does not cover use cases where a an event is fired via programmatic API, e.g. `BeanManager.getEvent()` or `Arc.container().beanManager().fireEvent()`.

**Comment by manovotn** [comment]
> Also note that a decorated Event does not cover use cases where a an event is fired via programmatic API, e.g. BeanManager.getEvent() or Arc.container().beanManager().fireEvent().

That's very good point.
With that in mind, using an observer to get notified of all events looks like the only proper way.

**Comment by mkouba** [comment]
> Isn't there a way to get this handled? In which case, the OP wouldn't need any decorator.

That's a good point. So in general the call site (i.e. the event emitter) should be able to handle exceptions thrown by async observers; see also https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#async_exception. I'm not sure what "Quarkus seems to swallow those silently" means.

**Comment by JHahnHRO** [comment]
I apologise for expressing myself confusingly again. I didn't mean that it is Quarkus' fault that exceptions get swallowed. The exception is inside the `CompletionStage` that `Event#fireAsync` returns just as specified. The problem I want to solve is that nobody bothers to check this return value and there is no log-every-uncaught-exception-from-a-business-method automatism in place like there is with synchronous calls.

The approach out of the CDI spec is precisely the reason why I wanted the event-logging decorator: This approach is *best* implemented by a decorator of `Event<T>` ! You can override `fireAsync`, put the logging there once and be done with it. Otherwise you'd have to remember at *every single place* were any `Event<T>` gets injected to make a call to some log-statement. We tried that in another project I'm working on (which is using Wildfly) at first and it turns out that it doesn't work well with our monkey brains. We forgot all the time to put the logging call in; sometimes some colleague remembered and still thought "I won't do it, because there's absolutely no way this could throw any exceptions" (which, of course, it did). Exceptions were silently caught, put into the CompletionStage that fireAsync returns and because that return value was ignored, the exception got lost and the poor bastard that had to debug the problem was left scratching his head. The decorator (which works fine with Wildfly, i.e. Weld) solves all of that. Every injected Event automatically is decorated, we don't have to copy&paste the logging everywhere, nobody can forget to put it in, all exceptions get logged. Yes, the odd event that gets fired directly from the BeanManager is not included in this, but that is the corner-case of the corner-case. I don't think most of my colleagues even know that they can do that. There are maybe four places in the whole million-LoC application that use the BeanManager and I've written all of them myself. Everything else is plain `@Inject Event<T>` and that's where the decorator shines.

**Comment by mkouba** [comment]
@JHahnHRO I see your point, but even if you decorate the `Event.fireAsync()` then the only thing you can do is to add some logging if a returned `CompletionStage` completes exceptionally, right? I mean you can't block the client. So would it be helpful if we log the exceptions for `@ObserveAsync` like we do for transactional observers?

**Comment by JHahnHRO** [comment]
If such a logging mechanism for async observer were built-in it would help, yes.

**Comment by JHahnHRO** [comment]
It is now decided that decorating built-in beans will not be supported in the near future, yes? If so, then that should at least be documented. Ideally I'd like Quarkus to print a big fat warning to the log if a decorator for a built-in bean is found explaining that it will not work.

**Comment by manovotn** [comment]
You're right that we should at least denote this is the [reference guide](https://quarkus.io/guides/cdi-reference) and state the the support is limited.

>  Ideally I'd like Quarkus to print a big fat warning to the log if a decorator for a built-in bean

I guess we could do that by monitoring the decorated type when processing them and log a warning or maybe straight up throw an error. WDYT @mkouba?
