### ISSUE TITLE
io.quarkus.security.UnauthorizedException is thrown when it is not expected

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#23729]
### Describe the bug

When using `quarkus-elytron-security-properties-file` with a `ExceptionMapper<io.quarkus.security.UnauthorizedException>`, we can observe partially unexpected behaviour (endpoints returning `401` instead of other, expected responses).

This behaviour can only partially reproduced: calls through, for example, the `swagger-ui` work as expected, calls through `restEasy` and `cURL` show the "wrong" status codes.

When we deactivate the custom `ExceptionMapper<io.quarkus.security.UnauthorizedException>` and debug the built-in `io.quarkus.resteasy.runtime.UnauthorizedExceptionMapper`, we can see that, when a request with correct credentials is received, an `UnauthorizedException` is thrown. 

### Expected behavior

If we provide correct credentials, no `UnauthorizedException` should be thrown.

### Actual behavior

An `UnauthorizedException` is thrown.

### How to Reproduce?

See [this bitbucket repository](https://bitbucket.org/turing85/quarkus-unauthorized-mapper/)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1526]

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by sberyozkin** [comment]
@turing85 Looks like your test code is written incorrectly, it should have a `preemptive()` included, for example:
```
RestAssured
                .given()
                .auth().preemptive().basic("admin", "admin")`
```

**Comment by turing85** [comment]
Okay. But why do the tests work if we do not add a custom `ExceptionHandler<UnauthorizedException>`?

**Comment by turing85** [comment]
@sberyozkin Okay, I figured it out. Basically, we can extend the `io.quarkus.resteasy.runtime.UnauthorizedExceptionMapper`, call it's `toResponse(...)` method and transform the body as we see fit:

```
@Provider
public class UnauthorizedExceptionMapper extends io.quarkus.resteasy.runtime.UnauthorizedExceptionMapper
    implements ExceptionMapper<UnauthorizedException> {

  @Override
  public Response toResponse(UnauthorizedException exception) {
    return Response.fromResponse(super.toResponse(exception))
        .entity("unauthorized")
        .build();
  }
}
```

Issue can be closed :)

**Comment by sberyozkin** [comment]
@turing85 Sounds good, thanks
