### ISSUE TITLE
Add a configuration to expose additional port while starting Quarkus in a container during QuarkusIntegrationTest

### ISSUE THREAD

**Issue by sdaclin** [quarkusio/quarkus#23722]
### Description

When your quarkus container is built and you are running Quarkus Integration Test container, you don't have the opportunity to expose additional port to the outside thus only conventional Rest api are able to be tested.

See the doc here => https://quarkus.io/guides/getting-started-testing#launching-containers

If someone is using Vert.x or Netty to expose a TCP service out of the traditional Http port, he isn't able to reach it from the outside of the container.

See the Zulip conversation with @geoand  => [link to the Zulip conversation](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/QuarkusIntegrationTest.2C.20container.20config)

### Implementation ideas

* add a configuration to specify additional port exposed by your quarkus app.
* expose these ports while starting the app in a container (during IntegrationTest)
* find a way to retrieve these ports with a mechanism like https://quarkus.io/guides/getting-started-testing#injecting-a-uri to be able to know it during test runtime (because the exposed ports should be dynamic)

**Comment by geoand** [comment]
Implemented `add a configuration to specify additional port exposed by your quarkus app.` in #23666
