### ISSUE TITLE
Connection URI syntax for reactive oracle client

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#23728]
### Describe the bug

I am receiving a "Wrong syntax of connection URI" whenever I try to specify a reactive URL for the new reactive Oracle client. I have tried to refer this documentation: [Reactive SQL Clients](https://quarkus.io/guides/reactive-sql-clients) and it mentions a similar URI scheme of this: **postgresql://localhost:5432/quarkus_test** but no mention of a URI scheme for Oracle. When looking at the OracleConnectionUriParser.java class in Quarkus I see that the pattern is described as follows:

`private static final Pattern FULL_URI_PATTERN = Pattern.compile("^"
    + SCHEME_DESIGNATOR_REGEX
    + USER_INFO_REGEX
    + NET_LOCATION_REGEX
    + PORT_REGEX
    + SID
    + "$");`

I have tried to follow a similar scheme as Postgres but to no avail. Can I get the URI connection pattern that is expected from the new Oracle client? I was under the impression that by following the logic of the aforementioned class I could create the connection URI as follows (but can't): **oracle:thin://HOST:PORT/SID**

**Comment by geoand** [comment]
You likely are using the wrong syntax, see https://github.com/quarkusio/quarkus/issues/23439.

@tsegismont I wonder if we need some clarification in the docs.

**Comment by LazaroR94** [comment]
Thanks @geoand. I would appreciate some more documentation on this seeing as I'm not the only one that encountered this and the Quarkus SQL Clients documentation does not mention Oracle anywhere (I know it's a new introduction, but some more documentation could help others who use similar implementations).

**Comment by tsegismont** [comment]
@geoand I don't believe we need clarification in the docs. However we need more connection url formats to be supported. I will work on this.
