### ISSUE TITLE
Gradle Unit Tests Don't Work Since 2.7.1

### ISSUE THREAD

**Issue by ethan-gallant** [quarkusio/quarkus#23735]
### Describe the bug

After moving to Quarkus 2.7.1 from 2.7.0 unit tests in Gradle no longer run. 

Quarkus says "No tests found" even though there tests.

### Expected behavior

Unit tests run and fail because my code is trash

### Actual behavior

Unit tests pass saying "No tests found" so I push it to prod and my boss gets angri :fearful: 

### Output of `java -version`

OpenJDK Runtime Environment 18.9 (build 11.0.14+9)

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by ethan-gallant** [comment]
Tried to take a crack at this myself, if anyone can hint towards the issue or suggest anything I am more than willing to open a PR :)

I found this issue/pr seems to modify the loading of test assets. https://github.com/quarkusio/quarkus/pull/23293 

Another PR seems to look for extension properties so I am guessing it's unrelated, but it's in the dev mode config? I believe it was written by @glefloch and reviewed by @stuartwdouglas. 

Thank you all for your work on this project. It has been what has kickstarted my first software engineering job and my overall journey of software development. :smile:

**Comment by glefloch** [comment]
Thanks for reporting this @ethan-gallant and sorry for the issue. 

Do you have a reproducer?

**Comment by glefloch** [comment]
Does it occurs only with continuous testing ? Does `gradle test` run test?

**Comment by ethan-gallant** [comment]
I have pushed my reproducer code here: https://github.com/ethan-gallant/quarkus-reproducers/tree/issue/23735

`gradle test` works as expected
`gradle quarkusDev` does not work
`gradle quarkusTest` also fails

Thank you for your help :)

**Comment by glefloch** [comment]
Hi @ethan-gallant sorry for the delay I'm on PTO this week. 
I think a first option would be to revert the commit you identify and test. If this work, then we will need to understand why the change introduced a regression.

**Comment by stuartwdouglas** [comment]
@aloubyansky it seems to be caused by this line: https://github.com/stuartwdouglas/quarkus/blob/9c50cfa2185c213b1959494394da7fe14aeeee55/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java#L459

`project.getWorkspaceModule().getTestSources()` seems to be returning null, which was changed in https://github.com/aloubyansky/quarkus/commit/84c4b359daeb911c04832b0c6d3b1c99c51e5493

**Comment by aloubyansky** [comment]
Thanks, I'll look into this.
