### ISSUE TITLE
Remove JBoss Threads version printing when building native

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#23748]
JBoss Thread printing version information when building native images getting in the way of the new GraalVM 22.x output:

```
[1/7] Initializing...                                                                                    (2.3s @ 0.14GB)
 Version info: 'GraalVM 22.1-dev Java 17 CE'
 C compiler: gcc (redhat, x86_64, 11.2.1)
 Garbage collector: Serial GC
 3 user-provided feature(s)
  - io.quarkus.caffeine.runtime.graal.CacheConstructorsAutofeature
  - io.quarkus.runner.AutoFeature
  - io.quarkus.runtime.graal.ResourcesFeature
[2/7] Performing analysis...  [*10:01:48,494 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
*******]                                                                 (9.1s @ 1.70GB)
  14,475 (95.76%) of 15,116 classes reachable
```

**Comment by geoand** [comment]
I had done something similar in https://github.com/quarkusio/quarkus/pull/22794, but it was only for the build

**Comment by galderz** [comment]
@geoand Hmmm, shouldn't really the way be to address it in jboss threads library and release a new version?

**Comment by galderz** [comment]
Actually, there's a [PR to change this](https://github.com/jbossas/jboss-threads/pull/102). JBoss Threads is the only one who still does this. It should follow suit as every other library has done and stop doing this.

**Comment by geoand** [comment]
You have my vote...
