### ISSUE TITLE
RESTEasy (Reactive) JSON serialization for multipart form data containing emojis is wrong

### ISSUE THREAD

**Issue by sbeigel** [quarkusio/quarkus#23756]
### Describe the bug

Serialization (string) data containing emojis as JSON form parts in multipart responses or payloads differs from serialization in non-multipart contexts:

```
@Path("/test")
public class ReactiveMultipartTestResource {

    public static class TestData {
        public String bar;

        public TestData(String bar) {
            this.bar = bar;
        }
    }

    public static class FormData {
        @RestForm
        @PartType(MediaType.APPLICATION_JSON)
        public TestData data;
        @RestForm
        public String dataAsString;
    }

    @Inject
    ObjectMapper om;

    @GET
    @Produces(MediaType.MULTIPART_FORM_DATA)
    public FormData hello() throws JsonProcessingException {
        FormData form = new FormData();
        form.data = new TestData("Bar äöü 😀");
        form.dataAsString = om.writeValueAsString(form.data);
        return form;
    }
}
```

Looking at the raw request's response shows different encodings for the emoji part. It's not a "simple" UTF-8 problem as the German umlauts for example are correct. This is taken from IntelliJ's HTTP request tool's response file, not sure how encoding is screwed by pasting and submitting here though...)

```
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88
Content-Disposition: form-data; name="data"
Content-Type: application/json

{"bar":"Bar Ã¤Ã¶Ã¼ \uD83D\uDE00"}
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88
Content-Disposition: form-data; name="dataAsString"
Content-Type: text/plain

{"bar":"Bar Ã¤Ã¶Ã¼ ð"}
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88--
```

### Expected behavior

Serialized JSON should be the same for "standard" serialization and "automatic" serialization in multipart contexts.

### Actual behavior

See above :)

### How to Reproduce?

See above :)

### Quarkus version or git rev

2.7.1

**Comment by AkMo3** [comment]
@sbeigel I believe the issue is with the Intellij HTTP request tool not with RESTEasy serialization. In my system (Ubuntu 20.04) the native file editor shows the emoji correctly but the Intellij fails to serialize it.

![ss1](https://user-images.githubusercontent.com/69365878/154828265-bad45414-6d3e-422a-a3dd-ee0c8f43bcf8.png)
![Screenshot from 2022-02-20 09-47-56](https://user-images.githubusercontent.com/69365878/154828282-d71f85a1-38b8-46f1-a3be-de91f08e2016.png)

**Comment by sbeigel** [comment]
@AkMo3 The second part ("dataAsString") is not the problem, that's ok for me as well and you are right that IntelliJ's viewer doesn't show this "correct", but that is not the point. The problem is the first part ("data") that is serialized automatically. In your screenshots, there seems to be no JSON serialization at all for this part, don't know what exactly you are doing.

To recap the issue: It should look like this:

```
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88
Content-Disposition: form-data; name="data"
Content-Type: application/json

{"bar":"Bar äöü 😀"}
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88
Content-Disposition: form-data; name="dataAsString"
Content-Type: text/plain

{"bar":"Bar äöü 😀"}
--b7ae92fe-eb4e-4a8b-b142-c77b79adbd88--
```

(IntelliJ's rendering "problems" aside) but actually the first part differs from the second using the current RESTEasy (Reactive) impl as the emoji is encoded as "\uD83D\uDE00".
