### ISSUE TITLE
Remote debug not working

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#23765]
I used the openshift extension to deploy my app to OpenShift via an S2I binary build. The app is up and running and `quarkus:remote-dev` connects to it fine and any local changes are pushed/reflected as expected.

My challenge is I can't seem to connect a remote debugger to it. I can't seem to get the pod to run in debug.

I've tried lots of combinations of environment variables/arguments, but nothing works. Here's what I've tried:
- set env var `JAVA_DEBUG=true`
- set property `quarkus.openshift.jvm-arguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005`
- set property `quarkus.openshift.jvm-arguments=-Ddebug=true`

The [Quarkus OpenShift config](https://quarkus.io/guides/all-config#quarkus-container-image-openshift_quarkus.openshift.base-jvm-image) says that the base jvm image is `registry.access.redhat.com/ubi8/openjdk-11`. When [looking at the documentation for the image](https://access.redhat.com/documentation/en-us/openjdk/11/html-single/using_openjdk_11_source-to-image_for_openshift/index#example-workflow-s2i-openshift-debugging) I should just be able to set `JAVA_DEBUG=true` and it should work, but it doesn't seem to be.

Is this a Quarkus issue? An issue with the `openjdk-11` image?

_Originally posted by @edeandrea in https://github.com/quarkusio/quarkus/discussions/23243_ - See there & https://github.com/quarkusio/quarkus/discussions/23243#discussioncomment-2064464 for more details

**Comment by geoand** [comment]
> Is this a Quarkus issue?

It can't be as Quarkus has nothing to do with JVM debugging.

> set env var JAVA_DEBUG=true

How were you setting this?

In any case, you'll need to see what the configuration of the running `Pod` is to see what environment variables and/or arguments are set.
Another thing to check is to see exec into the the running container and find the actual `java ...` command that launched the application.

**Comment by edeandrea** [comment]
> It can't be as Quarkus has nothing to do with JVM debugging.

But the `Dockerfile.jvm` that was used to create the image (https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/src/main/docker/Dockerfile.jvm) came from code.quarkus.io. That Dockerfile defines its own `ENTRYPOINT` which does not include any debug "stuff".

> > set env var JAVA_DEBUG=true
> 
> How were you setting this?

By adding the environment variable to the `DeploymentConfig` and then triggering a rollout

> In any case, you'll need to see what the configuration of the running `Pod` is to see what environment variables and/or arguments are set. Another thing to check is to see exec into the the running container and find the actual `java ...` command that launched the application.

It seems the image used (`ubi8/openjdk-11-runtime`) doesn't have any kind of cli tools installed (no `ps` nor `lsof`), so I'm not sure how to see what the actual java process looks like, although looking at the [`ENTRYPOINT`])https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/src/main/docker/Dockerfile.jvm#L40) I would suspect it is simply `java -jar`.

If I then push the app directly to OpenShift using the Quarkus openshift extension it seems to use the [`ubi8/openjdk-11` image](https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?container-tabs=technical-information). If you [look at the documentation](https://access.redhat.com/documentation/en-us/openjdk/11/html-single/using_openjdk_11_source-to-image_for_openshift/index#example-workflow-s2i-openshift-debugging) it mentions the whole `JAVA_DEBUG` thing.

I do not see the `Listening for transport dt_socket at address` message in the pod startup. 

When I follow the instructions in that guide for the OpenJDK image it works fine, so something in the `./mvnw package -Dquarkus.kubernetes.deploy=true` isn't working the way it should.

**Comment by geoand** [comment]
> But the Dockerfile.jvm that was used to create the image (https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/src/main/docker/Dockerfile.jvm) came from code.quarkus.io. That Dockerfile defines its own ENTRYPOINT which does not include any debug "stuff".

You never mentioned you were using the Dockerfile...

> It seems the image used (ubi8/openjdk-11-runtime) doesn't have any kind of cli tools installed (no ps nor lsof), so I'm not sure how to see what the actual java process looks like, although looking at the [ENTRYPOINT](https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/src/main/docker/Dockerfile.jvm#L40) I would suspect it is simply java -jar.

Does it comes with `jcmd` in the directory where `java` is found? If so, you can do things like:

```bash
jcmd <pid> VM.flags
jcmd <pid> VM.command_line
```

**Comment by edeandrea** [comment]
> You never mentioned you were using the Dockerfile...

That's what I tried first, just deploying the image that was built with that Dockerfile. When that didn't work I switched back to the s2i binary build, deploying from my local machine.

> Does it comes with `jcmd` in the directory where `java` is found? If so, you can do things like:

It does have `jcmd` but I don't know what the pid is....

If you look at the `DeplopymentConfig` that was generated by the openshift extension (see the end of my [previous comment](https://github.com/quarkusio/quarkus/issues/23765#issuecomment-1042969171), take note of the command - it completely skips/ignores/bypasses the `run-java.sh` script that is included in the base image (which respects the JAVA_DEBUG flag)

**Comment by geoand** [comment]
One question, where does `quarkus.openshift.jvm-arguments` come from? Is it mentioned somewhere in the docs?
Have you tried `quarkus.openshift.arguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005` instead?

**Comment by edeandrea** [comment]
I guess in addition was not using the provided run script (which handles the presence of the `JAVA_DEBUG` environment variable) a conscious decision by Quarkus? It seems when the openshift extension generates the `DeploymentConfig` it is overriding the `command` from the base image.

Was that a conscious choice? If so, why?

**Comment by edeandrea** [comment]
This looks like its been resolved now.

The [`DeploymentConfig`](https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/deploy/k8s/java11-openshift.yml) no longer specified the `command`.

The latest code.quarkus.io also generates a different [`Dockerfile`](https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-villains/src/main/docker/Dockerfile.jvm) - one that's based on the OpenJDK image and does not override the `ENTRYPOINT`.

**Comment by geoand** [comment]
Good to know!

**Comment by florentgarin** [comment]
Default port env variable seems not correct. On my side I had to specify
JAVA_DEBUG_PORT=*:5005 instead default 5005 to make it works.

**Comment by Sgitario** [comment]
@florentgarin do you mean that using the configuration in https://github.com/gsmet/quarkus/commit/67505dc3d5c32bcc64e3c92121c5bedccae4e3ff#diff-352a260cfb79854020efe849e44cedb10355aa4bd7b5eed1db676b77d8870a86R14, didn't work for you?
For me, it's working fine tho. But it's also working fine with "*:5005".

**Comment by florentgarin** [comment]
No I mean that if you simply use the generated Dockerfile.jvm, build it with the docker command exactly as mentioned in the comments and run it (as explained, plain basic Docker style). Then you will not be able to remote debug your container without -e JAVA_DEBUG_PORT=*:5005
