### ISSUE TITLE
zero-config devservice with hibernate set to `drop-and-create` does not create tables

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#23767]
### Describe the bug

I am trying to get the most minimal setup working in which a zero-config devservice gets populated by hibernate. When configuring [`quarkus.hibernate-orm.database.generation`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.generation) to `drop-and-create` I expected hibernate to automatically create a table `MyEntity`. Instead, I get this log at startup:

```
2022-02-16 17:34:22,226 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-5) Dev Services for the default datasource (postgresql) started.
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-16 17:34:22,751 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-02-16 17:34:22,752 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) table "myentity" does not exist, skipping
2022-02-16 17:34:22,753 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-02-16 17:34:22,753 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) sequence "hibernate_sequence" does not exist, skipping
2022-02-16 17:34:22,766 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.1.Final) started in 3.337s.
2022-02-16 17:34:22,767 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-02-16 17:34:22,767 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, smallrye-context-propagation]
```

Especially the `table "myentity" does not exist, skipping` looks suspicious to me.

And while Quarkus and therefore the devservice's postgres docker image are still running I can connect to the database on `localhost:5432` with username `quarkus` and password `quarkus` and can see that no table was created. Is it possible I am connecting with the wrong user?

### Expected behavior

I can see the tables in the database after Quarkus has booted up.

### Actual behavior

No tables were created, or I don't know how to see them.

### How to Reproduce?

- Create a new Quarkus project with the `quarkus-hibernate-orm` and `quarkus-jdbc-postgresql` extensions: https://code.quarkus.io/?j=17&e=hibernate-orm&e=jdbc-postgresql
  Using default settings the project will contain example code, notably a JPA entity `MyEntity`.
- Ensure the configuration contains:
  ```
  quarkus.hibernate-orm.database.generation=drop-and-create
  quarkus.hibernate-orm.database.default-schema=public
  quarkus.datasource.devservices.port=5432
  ```
- run `./mvnw compile quarkus:dev`

### Output of `uname -a` or `ver`

Linux NB01277 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.1 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### Quarkus version or git rev

2.7.1

**Comment by Sanne** [comment]
The warning is harmless, and can't be fixed easily in Hibernate ORM. At best we can rephrase the message but it's been like that for a long time.

It doesn't suggest that tables are not being created - please check. Might also be worth trying to save & load some data.

**Comment by Sanne** [comment]
(I didn't mean to suggest that we don't want to improve Hibernate ORM - we'll definitely want to get rid of these warnings, but I'm suggesting to do it in ORM v6 : probably not worth the effort in 5).

**Comment by Felk** [comment]
Thank you for your fast replies!

> A better way to check would be to try to persist an entity in your application, then retrieve it. If it works, the tables are definitely there. Can you please try that and post a message with the results?

That is indeed a better way to check, and I should have done this to avoid false assumptions.

> It's possible you're looking into the wrong database schema?

Indeed I connected to the wrong database. I connected to `postgres` out of habit, but quarkus creates a database called `default` (same as the datasource name I suppose?). I can confirm that everything actually works as expected 😅 Sorry for wasting your time a bit.

For the sake of debuggability, can I suggest documenting how to connect to the devservice database somewhere? E.g. logging the credentials `quarkus`:`quarkus` and the database name `postgres` (or entire jdbc url) upon starting a devservice?

> it means Hibernate ORM skipped dropping the table (since you're using drop-and-create). 

> The warning is harmless, and can't be fixed easily in Hibernate ORM. At best we can rephrase the message but it's been like that for a long time.

That makes sense. Thanks for clearing this up.

**Comment by yrodiere** [comment]
> For the sake of debuggability, can I suggest documenting how to connect to the devservice database somewhere? E.g. logging the credentials `quarkus`:`quarkus` and the database name `postgres` (or entire jdbc url) upon starting a devservice?

I'm afraid logging credentials by default is not an acceptable practice from a security standpoint. I suppose we could log the database name and username, but IIRC some people in the team are waging a war against having too much logs on startup :D 

Maybe something we could add something integrated, a summary of all connected services on startup? And display it only in dev mode. That might gain acceptance from others. We'll need a separate ticket to discuss that, I think.

In the meantime, it seems your problem was not a problem after all. Thanks for confirming that!

Closing.

**Comment by Felk** [comment]
> For the sake of debuggability, can I suggest documenting how to connect to the devservice database somewhere?

I feel like I'm slowly getting more proficient in using Quarkus effectively, including thoroughly reading up on guides and finding all the neat tools that already exist. This includes this little neat button:

![grafik](https://user-images.githubusercontent.com/1996138/156217653-2522592b-8465-4a89-8335-6deca2b48981.png)

which brings me to the config editor pre-filtered for hibernate configs. All the database information, including the JDBC url and credentials, are right there. @yrodiere there's definetely no need to print this information anywhere since this exists. I just needed to think outside the box a bit. Thanks for taking the time anyway!
