### ISSUE TITLE
Running gradle quarkusDev fails in a multi-module Gradle project

### ISSUE THREAD

**Issue by tabuyos** [quarkusio/quarkus#23776]
### Describe the bug

I am learning the tutorial: [GETTING STARTED WITH REACTIVE](https://quarkus.io/guides/getting-started-reactive)

When I run `gradle :quarkus-reactive:quarkusDev` in a multi-module gradle project, I get an exception

> Execution failed for task ':quarkus-reactive:compileJava'.
> \> Cannot change dependencies of dependency configuration ':quarkus-reactive:annotationProcessor' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.

When I comment out `implementation("io.quarkus:quarkus-hibernate-reactive-panache")` it works fine

### Expected behavior

This Quarkus plugin should work fine in other submodules

### Actual behavior

this Quarkus plugin doesn't seem to be able to execute `compileJava` task in submodule

### How to Reproduce?

Here is my example code:

[reproduce/quarkus at main · tabuyos/reproduce](https://github.com/tabuyos/reproduce/tree/main/quarkus)

Execute the `gradle :quarkus-reactive:quarkusDev` task in the quarkus directory

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.19043.1466]

### Output of `java -version`

openjdk version "16" 2021-03-16

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0.2

**Comment by ngarg-panw** [comment]
Facing the same issue after I upgraded my Quarkus from 2.0.0.CR3 to 2.7.1.Final
```* What went wrong:
Could not determine the dependencies of task ':quarkusBuild'.
> Cannot change dependencies of dependency configuration ':annotationProcessor' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.
```

**Comment by glefloch** [comment]
Thanks for reporting this @tabuyos. Could you try to remove configuration related settings in your main build.gradle (from line 47 to 55) ?

**Comment by ngarg-panw** [comment]
@glefloch I have similar code as @tabuyos . 
```configurations {
  configureEach {
    exclude(module = "slf4j-log4j12")
    exclude(module = "slf4j-jboss-logmanager")
  }
  val apc = get("annotationProcessor")
  get("compileOnly").extendsFrom(apc)
  get("testCompileOnly").extendsFrom(apc)
}```
But when I comment the lines suggested by you. In my case, following lines:
```
val apc = get("annotationProcessor")
  get("compileOnly").extendsFrom(apc)
  get("testCompileOnly").extendsFrom(apc)
```

I start getting errors for Json annotations and lombok annotations that they are not found.

**Comment by glefloch** [comment]
yes, the issue comes from the fact that we add a dependency to the `annotationProcessor` configuration if a `panache` artifact is present. I will push a fix.
