### ISSUE TITLE
RequestScoped not working in CDI

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#23774]
### Describe the bug

I annotated my context class as `@RequestScoped` and inject it into a service class, but it seems that it's still application scoped.

### Expected behavior

the class annotated as `@RequestScoped` should be request lifecycle

### How to Reproduce?

using quarkus-quickstarts example https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started

and modify `src/main/java/org/acme/getting/started/GreetingResource.java`:
```java
package org.acme.getting.started;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.jboss.resteasy.annotations.jaxrs.PathParam;

@Path("/hello")
public class GreetingResource {

    @Inject
    GreetingService service;

    @RequestScoped
    public static class MyContext {
        public String val;
        public MyContext() {
            System.out.println("my context created");
        }
    }

    @Inject
    MyContext myContext;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/greeting/{name}")
    public String greeting(@PathParam String name) {
        System.out.println("val before set context " + myContext.val);
        myContext.val = name;
        System.out.println("val after set context " + myContext.val);
        return service.greeting(name);
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```

sending two request
```
curl http://localhost:8080/hello/greeting/alex1
curl http://localhost:8080/hello/greeting/alex2
```

log:
```
2022-02-16 14:48:43,472 INFO  [io.quarkus] (Quarkus Main Thread) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.6.2.Final) started in 0.187s. Listening on: http://localhost:8080

2022-02-16 14:48:43,473 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-02-16 14:48:43,473 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
2022-02-16 14:48:43,473 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Live reload total time: 0.267s 
my context created
val before set context null
val after set context alex1
val before set context alex1
val after set context alex2
```

as you can see the `myContext` is only created once, instead of created per request.

Am I using it in the wrong way?

### Output of `uname -a` or `ver`

Darwin 106-50-161-10-in-addr.tusimple.ai 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### Quarkus version or git rev

2.6.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by manovotn** [comment]
Hi @liuzqt 

> Am I using it in the wrong way?

You are just testing it the wrong way so to speak :)
Let me clarify.

Request scoped bean uses a proxy which is injected and through which you can invoke methods on an actual bean instance.
However, if you directly reference a field, you will be referencing the proxy. I.e. in your case `myContext.val` will just try to read the field from proxy (and the state of proxy is undefined hence you shouldn't do that).

Instead, add a getter and setter for the `val` field on your bean and test again - you will see that it works:

```
@RequestScoped
    public static class MyContext {
        private String val;
        public MyContext() {
            System.out.println("my context created");
        }
       public void setVal(String val) {
         this.val = val;
       }
       public String getVal() {
         retrun val;
       }
    }
```

> as you can see the myContext is only created once, instead of created per request.

Actually, the bean is never even created; what you see is an invocation that creates the *proxy object*.
Actual bean invocation is lazy and is deferred to when you invoke any method on the bean - and this never happens in your case since you just use the proxy field. Again, adding the getter/setter will shed some more light on this.

**Comment by liuzqt** [comment]
@manovotn  that works, thank you for the explanation!

**Comment by mkouba** [comment]
FTR here's a basic introduction to CDI client proxies: https://quarkus.io/guides/cdi#client_proxies
