### ISSUE TITLE
Provide ArC version of javax.enterprise.inject.spi.Unmanaged

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2378]
ArC does not fully support some parts of the CDI SPI such as `AnnotatedType`, `InjectionTarget`. However, we should be able to [inject unmanaged instances](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestResourceProvider.java#L21-L54). We should provide an ArC version of `Unmanaged`.

**Comment by tandraschko** [comment]
@mkouba is there any progress?
I would really like to get a something like in DS: https://github.com/apache/deltaspike/blob/master/deltaspike/core/api/src/main/java/org/apache/deltaspike/core/api/provider/BeanProvider.java#L460

**Comment by mkouba** [comment]
Hi @tandraschko, no progress yet. Anyway, the `BeanProvider#injectFields()` method is not a good example. First of all the name is misleading because it also invokes initializer methods. Furthermore, if a `@Dependent` bean instance is injected it is never destroyed correctly. This is fine unless the `@Dependent` bean declares a `@PreDestroy` callback. Finally, the `InjectionTarget` is primarily designed to create and destroy instances of the bean, to perform dependency injection and lifecycle callbacks and not only to inject an existing instance.

**Comment by tandraschko** [comment]
@mkouba yep, i understand
i generell i can't use Unmanaged in this case as JSF artifacts provides wrapping via constructors.

What could be a good alternative?
Loop all methods and manually invoke PostConstruct/PreDestory and also loop a fields for Injection points and try to get them via CDI.current()?

**Comment by tandraschko** [comment]
not out-of-date ;)

**Comment by dufoli** [comment]
@mkouba can I help on this one. I want to discover arc and it seems a good way to take one ticket on it. I have start to implement interface but it is hard to understand use case, So I think I will add a test to check how it expect to work.

**Comment by manovotn** [comment]
After discussion with @mkouba and @Ladicek, we have decided to not implement this feature. Details can be seen in the comments of [this PR](https://github.com/quarkusio/quarkus/pull/19802).
