### ISSUE TITLE
Quarkus 2.7.1.Final unable to access Swagger-ui when deploying to Openshift

### ISSUE THREAD

**Issue by josephassiga** [quarkusio/quarkus#23782]
### Describe the bug

Quarkus version : 2.7.1.Final
Quarkus CLI version : 2.6.3.Final
OS: Mac Pro 13 inch Monterey version 12.0.1
Openshift version : 4.7

The swagger-ui is available when running locally, but when deploying the application to Openshift, i cannot have access to swagger-ui, but the curl localhost:8080/openapi.yaml is available, and the api respond correctly.

I have also added the property : quarkus.swagger-ui.always-include=true in the application.properties.

### Expected behavior

Bein able to see the swagger-ui deployed

### Actual behavior

The swager-ui should be available 

### How to Reproduce?

 1. Create a project with quarkus cli
 2. Deploy with this command : quarkus build -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true

### Output of `uname -a` or `ver`

Darwin xxxx-mac 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

### Quarkus version or git rev

Quarkus version : 2.7.1.Final Quarkus CLI version : 2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /usr/local/Cellar/maven/3.8.4/libexec Java version: 17.0.2, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home Default locale: en_FR, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "x86_64", family: "mac"

### Additional information

OS: Mac Pro 13 inch Monterey version 12.0.1
Openshift version : 4.7

**Comment by cescoffier** [comment]
The property to set is `quarkus.swagger-ui.always-include=true`. The one you use seems misspelled.

**Comment by cescoffier** [comment]
Also, please try locally with `mvn package. && java -jar target/quarkus-app/quarkus-run.jar` to check if the problem is due to the openshift packaging.

**Comment by josephassiga** [comment]
@cescoffier i have run the command :  mvn package  && java -jar target/quarkus-app/quarkus-run.jar locally and it works, the swager-ui is available

**Comment by cescoffier** [comment]
Ok, so it's related to the OpenShift packaging.
CC @iocanel @geoand

**Comment by geoand** [comment]
I have no idea what could be causing this... @iocanel any idea?

**Comment by maxandersen** [comment]
got a reproducer we can try out ?

**Comment by geoand** [comment]
> got a reproducer we can try out ?

Short of that, the list of extensions would probably suffice

**Comment by josephassiga** [comment]
>  
Current Quarkus extensions installed:

quarkus-hibernate-orm-panache
quarkus-hibernate-validator
quarkus-jdbc-h2
quarkus-jdbc-postgresql
quarkus-kubernetes-client
quarkus-openshift
quarkus-openshift-client
quarkus-resteasy
quarkus-resteasy-jackson
quarkus-resteasy-jsonb
quarkus-security-jpa
quarkus-smallrye-health
quarkus-smallrye-openapi

**Comment by maxandersen** [comment]
both h2 and postgresql ? (probably dont matter in this case just curious :)

**Comment by josephassiga** [comment]
I have updated the extension 
Current Quarkus extensions installed:

quarkus-hibernate-orm-panache
quarkus-hibernate-validator
quarkus-jdbc-h2
quarkus-openshift
quarkus-openshift-client
quarkus-resteasy
quarkus-resteasy-jackson
quarkus-resteasy-jsonb
quarkus-security-jpa
quarkus-smallrye-health
quarkus-smallrye-openapi

**Comment by cescoffier** [comment]
also having:
```
quarkus-resteasy-jackson
quarkus-resteasy-jsonb
```

looks odd (but should not be the problem here)

**Comment by geoand** [comment]
I just tried this with our [OpenAPI quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/openapi-swaggerui-quickstart) (with the addition of `quarkus.swagger-ui.always-include=true` in `application.properties`) and it worked as expected.
