### ISSUE TITLE
Document redis host provider or give an example

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#23787]
### Describe the bug

At the moment the redis guide is missing an example of the host provider feature

### Expected behavior

The feature should be documented

### Actual behavior

No documentation exists yet. We only have an integration test.

### Additional information

The documentation can be added based on https://github.com/quarkusio/quarkus/issues/16284#issuecomment-1042898488. The documentation can be go just before the https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/redis.adoc#creating-clients-programmatically section.

**Comment by machi1990** [comment]
@VanillaSpoon will you be interested in this?

**Comment by VanillaSpoon** [comment]
Yea, I'll work on it :) could you assign it to me?
