### ISSUE TITLE
Hibernate @Formula returns an old value in PUT response

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#23797]
### Describe the bug

If I update the child of a parent entity, the response still contains an old value in the @Formula field.

### Expected behavior

The refreshed value, after the transaction.

### Actual behavior

If I do a repo call after the transaction, I still get the cached value.

### How to Reproduce?

Entity A contains a @OneToMany list and a @Formula field, which does an AVG on a list attribute.

I first create Entity A and persist it, then I use its ID to persist the list objects in the same transaction.

### Output of `uname -a` or `ver`

5.16.9-zen1-1-zen

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12) OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

### Additional information

I use kotlin, PanacheRepositoryBase and Mutiny/Reactive.

According to
https://stackoverflow.com/questions/48641052/hibernate-formula-returns-an-old-value-in-put-response
I should do a `refresh`, which is impossible.

Would maybe a `Panache.withStatelessTransaction` help?
@Sanne mentioned it at https://github.com/quarkusio/quarkus/issues/20166#issuecomment-919870909
Sadly Panache uses only `withTransaction` from Mutiny and not `withStatelessTransaction`.
So I can't use it with PanacheRepositories.

**Comment by yrodiere** [comment]
Hey @DavideD , this seems to be about Hibernate Reactive.

**Comment by DavideD** [comment]
Panache doesn't have a `refresh` method but you can get it from the session.

After the persist, you can refresh the value via:
```
.call( entityA -> Panache.getSession().call( s -> s.refresh( entityA ) ) )
```

**Comment by DavideD** [comment]
I will close this issue but let me know  if this doesn't work. Thanks
