### ISSUE TITLE
Hibernate Reactive Panache incorrect column values for insertion w/ Reactive Oracle Client

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#23815]
### Describe the bug

I am experiencing a very strange error when I attempt to insert a 36 character String into a VARCHAR2(36) column in my Oracle database. I am generating a UUID gen4 from the application and converting it to a String before insertion into that column (I have also tested this with a random String value) but it is complaining that the value is absurdly too large in length somehow and throws this error: 

`org.hibernate.HibernateException: io.vertx.core.VertxException: [SQL INCLUDES EXPRESSIONS ADDED BY THE ORACLE JDBC DRIVER],Error : 12899, Position : 133, Sql = insert into SOME_TABLE_NAME (CREAT_TS, INTR_PYMT_ID, LOAD_FAIL_RSN_TX, UNIQUE_FAIL_TRANS_CT_NO, TRANS_DTL_TX) values (:1 , :2 , :3 , :4 , :5 ) RETURNING ROWID INTO :6 , OriginalSql = insert into SOME_TABLE_NAME (CREAT_TS, INTR_PYMT_ID, LOAD_FAIL_RSN_TX, UNIQUE_FAIL_TRANS_CT_NO, TRANS_DTL_TX) values (?, ?, ?, ?, ?) RETURNING ROWID INTO ?, Error Msg = ORA-12899: value too large for column \"SCHEMA\".\"SOME_TABLE_NAME\".\"UNIQUE_FAIL_TRANS_CT_NO\" (actual: 5596, maximum: 36)\n`

I am very confused as to how this is even possible when I can indeed confirm that I am inserting only 36 characters and even tested with a random String of <= 36 characters and still the same error. I am able to insert into this table just fine if I use SqlDeveloper.

This is how my Entity for the table is designed:

```
@Entity
@Cacheable
@Table(name = "SOME_TABLE_NAME")
class SomeTableEntityClass : PanacheEntityBase() {
    @Id
    @Column(name = "UNIQUE_FAIL_TRANS_CT_NO", length = 36)
    lateinit var uniqueTransactionIdentifier: String

    @Column(name = "INTR_PYMT_ID")
    lateinit var internalPaymentIdentifier: String

    @Column(name = "CREAT_TS")
    lateinit var createTimestamp: LocalDateTime

    @Lob
    @Column(name = "TRANS_DTL_TX")
    lateinit var transactionDetail: String

    @Column(name = "LOAD_FAIL_RSN_TX", length = 500)
    lateinit var transactionFailureReason: String
}
```

Am I doing something wrong here?

### Expected behavior

For the record to insert with the correct value(s).

### Actual behavior

`org.hibernate.HibernateException: io.vertx.core.VertxException: [SQL INCLUDES EXPRESSIONS ADDED BY THE ORACLE JDBC DRIVER],Error : 12899, Position : 133, Sql = insert into SOME_TABLE_NAME (CREAT_TS, INTR_PYMT_ID, LOAD_FAIL_RSN_TX, UNIQUE_FAIL_TRANS_CT_NO, TRANS_DTL_TX) values (:1 , :2 , :3 , :4 , :5 ) RETURNING ROWID INTO :6 , OriginalSql = insert into SOME_TABLE_NAME (CREAT_TS, INTR_PYMT_ID, LOAD_FAIL_RSN_TX, UNIQUE_FAIL_TRANS_CT_NO, TRANS_DTL_TX) values (?, ?, ?, ?, ?) RETURNING ROWID INTO ?, Error Msg = ORA-12899: value too large for column \"SCHEMA\".\"SOME_TABLE_NAME\".\"UNIQUE_FAIL_TRANS_CT_NO\" (actual: 5596, maximum: 36)\n`

### How to Reproduce?

Feel free to use a reproducer I made for this (mostly finished): https://github.com/LazaroR94/hibernate-reproducer

### Output of `uname -a` or `ver`

Darwin C02FW4DDMD6R 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

Java 11.0.12

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by DavideD** [comment]
I've tried to reproduce the error but everything seems to work.
I've updated your reproducer and added a test.  I've refactored it a bit but it doesn't affect the value of the result. 

Is it possible that the use case in the test doesn't match what you are doing in the real applicaiton?

**Comment by DavideD** [comment]
This is the reproducer: https://github.com/DavideD/hibernate-reproducer

**Comment by LazaroR94** [comment]
Thanks for looking into this @DavideD. If I could share the real application I would, but alas, I cannot as it is an enterprise application; therefore, I managed to get it looking as close to the real scenario as possible. So the entity that I provided along with the processor look okay to you? Was there anything "out-of-whack"?

**Comment by DavideD** [comment]
You don't need to share the whole application but you can try to update the reproducer I've shared so that it causes the same error.

Not that you need to have a running instance of Oracle, because the current integration with Oracle and testcontainers doesn't seem to work out of the box.

The entities looked fine, I haven't changed them.

There were some unnecessary `Uni.createItem()` calls that I've replaced with `.replaceWithVoid()`: https://github.com/DavideD/hibernate-reproducer/commit/5135aa0efe829372a7e45ee181aa611af22e4578

**Comment by LazaroR94** [comment]
I understand. The thing is, the reproducer that was shared is a good snippet of where I'm facing the issue at. I am only testing one table because an **@Id** column was recently added to it so that I may populate it with a random UUID. This actually worked before prior to this new column being introduced so I am not sure what the issue is here? I believe everything is set up correctly (even after checking your updated reproducer). I know the table is correctly structured as I am able to insert directly with SqlDeveloper.

**Comment by DavideD** [comment]
Nevermind, I can see the error. I think it has something to do with the test

**Comment by LazaroR94** [comment]
The test seemed pretty simple to me, is the calling of that processing not being done correctly or?

**Comment by DavideD** [comment]
This is really weird.
What's happening is that the fields annotated with `@Id` and `@Lob` don't get saved right.

The identifier is saved in the lob field and vice versa.
I've updated the test case so that it fails.

**Comment by DavideD** [comment]
I've never seen this error before. I'm not sure if it's something related to the fact we are using Kotlin or something in Panache.
I'm not familiar with Kotlin, maybe there something not quite right in the way the entity is defined?

**Comment by LazaroR94** [comment]
Now you see what I'm dealing with right? I've never before encountered this and I've worked with Spring hibernate before as well and never had this issue, just now coming into reactive. I should add, after adding a ridiculous amount of breakpoints I was able to see the SQL query that was being formed but with incorrect placement of values (to confirm your theory of values being out of place). I actually have another table that has a large object field defined and it does not seem to do it there.

**Comment by LazaroR94** [comment]
So I just removed `@Lob` from my entity column and it worked. Is there an explanation for why `@Lob` does not work when tied to a CLOB column in the database?

**Comment by DavideD** [comment]
None that I can think of.
In Hibernate Reactive we have test cases for this. So I'm quite confident that it's not something there that's failing (I could be wrong).

That said, now that we have  a test, we should be able to figure out what's going on.

But, unless somebody else wants to look into this, it will get back to this tomorrow

**Comment by LazaroR94** [comment]
Thank you Davide, I will wait for your response. For now, I have removed `@Lob` from the column type.

**Comment by DavideD** [comment]
@LazaroR94 The problem is that you are using Hibernate Reactive 1.1.2.Final but the integration with Oracle has been added in Hibernate Reactive 1.1.3.Final.

You need to upgrade Hibernate Reactive  or wait for Quarkus 2.7.2.Final
