### ISSUE TITLE
@MongoEntity with database parameter does not detect database when using mongo panache

### ISSUE THREAD

**Issue by romilpunetha** [quarkusio/quarkus#23813]
### Describe the bug

The following is my code structure:

```
public interface BaseMongoRepository<T extends BaseMongoEntity>
         extends ReactivePanacheMongoRepository<T>  {}

public interface UserRepository 
        extends BaseMongoRepository<UserEntity> {}

public class BaseMongoRepositoryImpl<T extends BaseMongoEntity> 
        implements BaseMongoRepository<T> {}

public class UserRepositoryImpl
        extends BaseMongoRepositoryImpl<UserEntity>
        implements UserRepository

@MongoEntity(database = "userDB", collection= "users")
public class User {}
```

When I'm running this code, mongo panache fails with IllegalArgumentException:

`The database attribute was not set for the @MongoEntity annotation and neither was the database property configured for the default Mongo Client (via 'quarkus.mongodb.database').`

If I pass the default client using `quarkus.mongodb.database`, all my collections are created in the same database. However, the collections args for @MongoEntity works fine. 

### Expected behavior

When passing @MongoEntity(database = "userDB"), the collection should be created in the userDB database.

### Actual behavior

If no default database is passed in application.properties, an error is thrown. Else the collection is created in the default database.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Homebrew (build 17.0.2+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 17.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "aarch64", family: "mac"

**Comment by loicmathieu** [comment]
@romilpunetha can you link to a reproducer or upload one inside the issue ? This would help us on it a lot.

**Comment by romilpunetha** [comment]
@loicmathieu Did you get a chance to look into this? 
We're about to move our workloads to production and it'd be difficult moving the collections into their respective DBs later.

**Comment by loicmathieu** [comment]
Hi @romilpunetha there is indead a bug inside the reactive implementation that didn't take the database name from the entity.
I provided a PR to fix it.
