### ISSUE TITLE
Config property quarkus.hibernate-orm.sql-load-script can not be overriden in custom profiles

### ISSUE THREAD

**Issue by mwalliczek** [quarkusio/quarkus#23821]
### Describe the bug

When trying to set the config property quarkus.hibernate-orm.sql-load-script in a custom profile to an existing file and to override the value "no-file" from prod-profile, that setting is ignored and the script is not executed. The only way to activate the script is to use the defined prod profile. That makes it difficult to test the complete application via integration tests in a controlled environment, without comprosing the default execution (where a script should never be executed).

### Expected behavior

When setting "%staging.quarkus.hibernate-orm.sql-load-script=import.sql" in the application.properties in src/main/resources and executing the application via "java -Dquarkus-profile=staging -jar application.jar" it is expected that the import.sql is executed, like other properties like "%staging.quarkus.hibernate-orm.database.generation=drop-and-create".

### Actual behavior

The script is not executed, and the database is created empty. During dev and test the import.sql is executed; also when setting the property like "%prod.quarkus.hibernate-orm.sql-load-script=import.sql".

### How to Reproduce?

1. Configure a valid mariadb server / database to src/main/application.properties
2. Execute the application via java -Dquarkus-profile=staging -jar target/hibernate-orm-quickstart-1.0.0-SNAPSHOT-runner.jar

Although the prod profile is not explicit activated, it is impossible to override its config quarkus.hibernate-orm.sql-load-script=no-file
[hibernate-orm-quickstart.zip](https://github.com/quarkusio/quarkus/files/8104976/hibernate-orm-quickstart.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1526]

### Output of `java -version`

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7) OpenJDK 64-Bit Server VM Zulu16.32+15-CA (build 16.0.2+7, mixed mode, sharing)

### Quarkus version or git rev

2.7.1.Final (also tested with 1.13.7.Final)

**Comment by yrodiere** [comment]
Duplicates #7358

**Comment by yrodiere** [comment]
As explained in #7358, `quarkus.hibernate-orm.sql-load-script` is a build-time property. It's set at build time, before profiles can be enabled. So indeed, it cannot be overridden.

I suppose you're using `import.sql` to load test data? If so, the solution to your problem lies here: https://github.com/quarkusio/quarkus/issues/21866

I'm going to close this; please let me know if you think #21866 won't solve your problem.

**Comment by mwalliczek** [comment]
Sorry, but I don't see any solution in the referenced issues.

Basically I want to create an integration test, which enters some test data in the database, starts the build application and performes some tests. If possible, I don't need any "real" database server at all, in fact it would be more easy to use the dev-services and a docker database image, like in the test profile. But I did not manage to configure it that way.

**Comment by yrodiere** [comment]
> which enters some test data in the database

#21866 is about adding a property to set a script to execute on startup, whose purpose is to initialize data, and which can be  different for each profile (test, dev, prod).

Doesn't that cover your use case?

**Comment by mwalliczek** [comment]
You are absolute right, #21866 would be a perfect solution. In the meantime until #21866 is implemented I need to think about a workaround.

**Comment by yrodiere** [comment]
Alright, I'll go ahead and close this issue, then. Let's move the discussion to #21866.

Thanks for your answers!
