### ISSUE TITLE
Update Quarkus release planning page

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#23833]
### Description

As a Quarkus user I found the Quarkus release planning page - https://github.com/quarkusio/quarkus/wiki/Release-Planning - quite useful to know roughly when to expect updates.
It seems this has not been updated since 2.7.

Could it be updated? Or if the plan is to communicate releases in some other way (e.g. issue milestones) then perhaps the link in the README could be replaced with a link to that.

**Comment by gsmet** [comment]
It's updated. We just haven't planned 2.8 yet. It will be done soon.
