### ISSUE TITLE
Reactive Hibernate w/ Panache insert two entities within the same persistence context

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#23845]
### Describe the bug

Hello, I have created an application that performs processing on a method and inserts into three tables. If processing on those three tables fails then the message is published to a Kafka DLQ in which the message then gets sent to the database for manual processing at a later time. Being new to reactive hibernate, I am not sure how I can make two separate inserts within the same persistence context seeing as I insert in one thread but then attempt to insert the same managed entity on another thread.

This is the error that I get when my processing fails the business-as-usual stage and fails over to get sent to the database for manual processing:
`org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.HibernateException: Illegal attempt to associate a ManagedEntity with two open persistence contexts. EntityEntry[MyEntity#786e52e3-c5c1-446f-b8b8-f4183cc60585](MANAGED)`

This is how I have my repositories set up to save to the database:
```
Panache.withTransaction {
                SomeRepo.persist(entity).chain { ->
                    SomeRepo.flush()
                }
            }
```

What am I doing wrong here?

### Expected behavior

For the managed entity from the first thread to be able to get inserted into a different table within the same persistence context instead of opening up two persistence contexts.

### Actual behavior

`org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.HibernateException: Illegal attempt to associate a ManagedEntity with two open persistence contexts. EntityEntry[MyEntity#786e52e3-c5c1-446f-b8b8-f4183cc60585](MANAGED)`

### Output of `java -version`

Java 11.0.12

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by DavideD** [comment]
Can you create a test project?
The only thing I can say right now is that the session is not thread-safe, so you cannot use the same session in different threads.

I'm not familiar with Kafka DLQ, if you can create an example I can look into it

**Comment by DavideD** [comment]
Not that it matter for this issue, but you don't need to flush if you are already in a transaction:
```
Panache.withTransaction { SomeRepo.persist(entity) }
```

**Comment by LazaroR94** [comment]
I can create a project for you, sure. Before I do that though, to your second point, being that the session isn't thread-safe should I be under the impression that I should be doing the secondary insert for the other table inside the same session where the initial Panache transaction was started? A logical flow for you: A message comes into Kafka -> the message hits the processing method and maps it to various entities before sending the entities to three separate tables (within a single Panache transaction) -> if success, then continue -> if failure, send to a Kafka DLQ -> the message hits yet another processing method and maps it to a different entity and sends that message to a different table (within a single Panache transaction). Would it be breaking somewhere in this flow? I am assuming here that since I have a persistence context open with the previous entities I cannot try to insert this entity into another table using that managed entity.

**Comment by Sanne** [comment]
> ### Expected behavior
> For the managed entity from the first thread to be able to get inserted into a different table within the same persistence context instead of opening up two persistence contexts.

This is an incorrect expectation: a particular _persistence context_ (or "Session" to use the terminology more commonly used in the Hibernate Reactive API) can't span multiple threads.

If you associated an entity to one session, you need to either dis-associate it from that session or close that session before you mark the entity as managed by a different session.

In your particular case you're using the Panache helper `SomeRepo.persist` which will use a Session instance scoped to the current request; this helper is useful for simple cases in which there is no ambiguity about which Session you actually want to use.

If you avoid the Panache helper you can use `SessionFactory.withTransaction((session, tx) -> session.persist(entity))` : this will persist the entity using the `session` instance which is scoped within that particular transaction; this will persist the object in a new session, flush, commit, and close the session. So on its return the entity will have been persisted and no longer associated with that "context".

Just two more comments:

> "instead of opening up two persistence contexts"

It's relatively efficient to open a new session - so don't try to avoid it in this case. In particular you mention "if an error happens": bear in mind that you need to dispose any Session that has thrown an exception as its internal state can no longer be relied upon.

So just close one session before you begin working with the next one.

**Comment by LazaroR94** [comment]
> > ### Expected behavior
> > For the managed entity from the first thread to be able to get inserted into a different table within the same persistence context instead of opening up two persistence contexts.
> 
> This is an incorrect expectation: a particular _persistence context_ (or "Session" to use the terminology more commonly used in the Hibernate Reactive API) can't span multiple threads.
> 
> If you associated an entity to one session, you need to either dis-associate it from that session or close that session before you mark the entity as managed by a different session.
> 
> In your particular case you're using the Panache helper `SomeRepo.persist` which will use a Session instance scoped to the current request; this helper is useful for simple cases in which there is no ambiguity about which Session you actually want to use.
> 
> If you avoid the Panache helper you can use `SessionFactory.withTransaction((session, tx) -> session.persist(entity))` : this will persist the entity using the `session` instance which is scoped within that particular transaction; this will persist the object in a new session, flush, commit, and close the session. So on its return the entity will have been persisted and no longer associated with that "context".
> 
> Just two more comments:
> 
> > "instead of opening up two persistence contexts"
> 
> It's relatively efficient to open a new session - so don't try to avoid it in this case. In particular you mention "if an error happens": bear in mind that you need to dispose any Session that has thrown an exception as its internal state can no longer be relied upon.
> 
> So just close one session before you begin working with the next one.

So how exactly can I close the session after the first persistence context finishes (with a success or failure)? Is there a helper function that I can call in Panache that closes that session after the fact? Sorry for the rudimentary question(s), I am still a bit new to reactive in general and would love to know how to do this.

**Comment by Sanne** [comment]
> So how exactly can I close the session after the first persistence context finishes (with a success or failure)? Is there a helper function that I can call in Panache that closes that session after the fact? Sorry for the rudimentary question(s), I am still a bit new to reactive in general and would love to know how to do this.

No problem :) So with Panache there is the "assumption" that everything that you do in the current web request is to be handled by the same Hibernate Session: it does lookup a Session in the current request scope, and if it doesn't find one it triggers the CDI factory which creates a Session bount to the lifecycle of that scope.

Essentially it's automatic - but it's only useful for simple use cases.

In situations like yours when you need to have control of the Session boundaries, don't use Panache so that the instance of session which you're using is explicit.

To be clear: the method `SessionFactory.withTransaction(  actions  )` will create both a Session and a Transaction object, scoped for that action. Whatever you do after the `withTransaction()` method completes it will happen after that session is closed - so technically you can chain multiple `withTransaction` blocks to define independent sequential operations: each with its own transaction and its own session.

**Comment by LazaroR94** [comment]
> > So how exactly can I close the session after the first persistence context finishes (with a success or failure)? Is there a helper function that I can call in Panache that closes that session after the fact? Sorry for the rudimentary question(s), I am still a bit new to reactive in general and would love to know how to do this.
> 
> No problem :) So with Panache there is the "assumption" that everything that you do in the current web request is to be handled by the same Hibernate Session: it does lookup a Session in the current request scope, and if it doesn't find one it triggers the CDI factory which creates a Session bount to the lifecycle of that scope.
> 
> Essentially it's automatic - but it's only useful for simple use cases.
> 
> In situations like yours when you need to have control of the Session boundaries, don't use Panache so that the instance of session which you're using is explicit.
> 
> To be clear: the method `SessionFactory.withTransaction( actions )` will create both a Session and a Transaction object, scoped for that action. Whatever you do after the `withTransaction()` method completes it will happen after that session is closed - so technically you can chain multiple `withTransaction` blocks to define independent sequential operations: each with its own transaction and its own session.

Thank you so much, I have removed Panache and just used the hibernate-reactive-orm implementation and that seems to be working like a charm. It sucks to know that Panache does this with it's simplicity mindset but it's also a nice to know :)

**Comment by LazaroR94** [comment]
> > So how exactly can I close the session after the first persistence context finishes (with a success or failure)? Is there a helper function that I can call in Panache that closes that session after the fact? Sorry for the rudimentary question(s), I am still a bit new to reactive in general and would love to know how to do this.
> 
> No problem :) So with Panache there is the "assumption" that everything that you do in the current web request is to be handled by the same Hibernate Session: it does lookup a Session in the current request scope, and if it doesn't find one it triggers the CDI factory which creates a Session bount to the lifecycle of that scope.
> 
> Essentially it's automatic - but it's only useful for simple use cases.
> 
> In situations like yours when you need to have control of the Session boundaries, don't use Panache so that the instance of session which you're using is explicit.
> 
> To be clear: the method `SessionFactory.withTransaction( actions )` will create both a Session and a Transaction object, scoped for that action. Whatever you do after the `withTransaction()` method completes it will happen after that session is closed - so technically you can chain multiple `withTransaction` blocks to define independent sequential operations: each with its own transaction and its own session.

I do have one more question for you regarding this (it may be related or it may not): What would be an efficient way of chaining multiple database inserts in reactive hibernate using the Mutiny reactive programming library? I am currently returning a combination of Unis in my program that each insert into a separate database table; however, when a failure happens it does not cancel all the other Unis if, for example, the last Uni fails in the sequence. What would you recommend when it comes to combining database inserts and ensuring that either they all succeed or they all rollback?

**Comment by LazaroR94** [comment]
> > So how exactly can I close the session after the first persistence context finishes (with a success or failure)? Is there a helper function that I can call in Panache that closes that session after the fact? Sorry for the rudimentary question(s), I am still a bit new to reactive in general and would love to know how to do this.
> 
> No problem :) So with Panache there is the "assumption" that everything that you do in the current web request is to be handled by the same Hibernate Session: it does lookup a Session in the current request scope, and if it doesn't find one it triggers the CDI factory which creates a Session bount to the lifecycle of that scope.
> 
> Essentially it's automatic - but it's only useful for simple use cases.
> 
> In situations like yours when you need to have control of the Session boundaries, don't use Panache so that the instance of session which you're using is explicit.
> 
> To be clear: the method `SessionFactory.withTransaction( actions )` will create both a Session and a Transaction object, scoped for that action. Whatever you do after the `withTransaction()` method completes it will happen after that session is closed - so technically you can chain multiple `withTransaction` blocks to define independent sequential operations: each with its own transaction and its own session.

@Sanne I also just found out that `SessionFactory.withTransaction` cannot use used with reactive messaging as it causes this issue: `Can't get the context safety flag: the current context is not a duplicated context` :'(

**Comment by DavideD** [comment]
You can try this:
```
Mutiny,SessionFactory sf = ...
sf.openSession().chain(session -> session.withTransaction(t -> ...).eventually(session::close))
```
