### ISSUE TITLE
Quarkus 3.0 code migration update facility

### ISSUE THREAD

**Issue by n1hility** [quarkusio/quarkus#23842]
### Description

In preparation for an eventual move to Jakarta, the quarkus update facility should support the transformation of existing app code, renaming calls from javax.* to jakarta.*.  Users should be able to decline if they wish to perform this work themselves.

### Analysis

Things this will solve
- All SOURCE code in the current quarkus app directory will be updated to refer to jakarta package

Things this will not solve
- Thirdparty binary dependencies outside of the Quarkus extension ecosystem which rely on javax. We will look at a separate solution for this use-case (#23847), but it is not encompased by this EPIC
- Any sort of unusual or custom project layout

Implementation Considerations
- We could reuse and/or extend as appropriate [Openrewrite's Jakarta support]( https://docs.openrewrite.org/reference/recipes/java/migrate/javaxmigrationtojakarta)
- This MUST only be performed in combination with maven dep updates to the Jakarta API deps

**Comment by maxandersen** [comment]
Looking at some options atm. Will update soon.

**Comment by maxandersen** [comment]
this was done in #29000
