### ISSUE TITLE
Out of date entrypoint documentation in container image guide

### ISSUE THREAD

**Issue by oaklandcorp-jkaiser** [quarkusio/quarkus#23841]
### Description

The [container image guide](https://quarkus.io/guides/container-image#jvm-debugging) has a section describing how to override the entrypoint of a JIB container image and it seems like the instructions in this section may be out of date. The default base image described there (`fabric8/java-alpine-openjdk11-jre`) doesn't seem to line up with the default base image described in the configuration value [quarkus.jib.base-jvm-image](https://quarkus.io/guides/container-image#quarkus-container-image-jib_quarkus.jib.base-jvm-image) (`registry.access.redhat.com/ubi8/openjdk-17-runtime:1.11` or `registry.access.redhat.com/ubi8/openjdk-11-runtime:1.11`). After a bit of testing I believe `fabric8/java-alpine-openjdk11-jre` is no longer the current default base image, so it would be good to update the instructions to reflect that.

### Implementation ideas

Either update the instructions to use the new default base image or update the instructions to override the default base image with the previous image that the instruction should still work for. If you go with using the new default base image, then I believe you'll need to update the entrypoint configuration to `quarkus.jib.jvm-entrypoint=java -jar /work/quarkus-run.jar` for it to work.

**Comment by geoand** [comment]
I'll have a look tomorrow.

**Comment by oaklandcorp-jkaiser** [comment]
Thanks for taking a look and a quick fix @geoand!

**Comment by geoand** [comment]
YW
