### ISSUE TITLE
Hibernate Panache: methods and annotations are missing building jar with Maven on Windows 10

### ISSUE THREAD

**Issue by maebl** [quarkusio/quarkus#2386]
After discussion with the Quarkus community on zulipchat, it seems that there is a bug when a project using hibernate orm with Panache is  builded with Maven on Windows. The runner jar does not work.

I have tested the build of the quarkus-quickstart/hibernate-orm-panache-resteasy project (https://github.com/quarkusio/quarkus-quickstarts commit#2cd8f7d2174b177d2fe663c75c30a82b7862e1f7):
* Directly on Windows 10 with: Maven 3.6.1 and jdk-8-amazon-corretto
* On linux (via docker) with same environment: Maven 3.6.1 and jdk-8-amazon-corretto

Then I have compared the Fruit class of each runner jar (I have decompiled class with JD-Gui).

Results: 
* in the jar generated with maven on Windows10:
  * annotations and hibernate methods are missing in the Fruit class.
* in the jar generated with maven on Linux:
  * annotations and hibernate methods are here in the Fruit class, all works fine.

You can find in attachment (see [TEST.zip](https://github.com/quarkusio/quarkus/files/3162475/TEST.zip) ) , for Windows10 build and Linux build:
* command launched (cf. run.bat)
* result log file
* generated JARs
* decompiled sources from JAR

Environment:
* Quarkus: 0.14.0
* Java JDK: 8 (Amazon Corretto)
* Maven: 3.6.1
* OS:
  * Windows10
  * Linux

Steps to reproduce:
* On Windows10:
```
mvn clean install --show-version --batch-mode -Ddocker.skip=true -DskipTests
```
* On Linux (on Windows10 via Docker):
```
docker run -it -v ./:/tmp/quarkus-quickstarts/hibernate-orm-panache-resteasy/ -w /tmp/quarkus-quickstarts/hibernate-orm-panache-resteasy maven:3.6.1-amazoncorretto-8 mvn clean install --show-version --batch-mode -Ddocker.skip=true -DskipTests
```

Related issue:  #1717

**Comment by FroMage** [comment]
Not sure what to label this because it is more general than Panache since even Hibernate methods are missing. Also, not sure how to debug this without a Windows machine.

**Comment by jycr** [comment]
I also reproduce this issue on my Windows10 pro with my JDK (AdoptOpenJdk)

**Comment by jycr** [comment]
I have launched both Maven build in debug mode (with @maebl's JDK : Amazon Coretto).
Main differences are at the end of `quarkus-maven-plugin:0.14.0:build`

On linux, we have:
```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in ¤¤¤¤ms
[DEBUG] [org.hibernate.bytecode.enhance.spi.Enhancer] Enhancing [org.acme.hibernate.orm.panache.Fruit] as Entity
[DEBUG] [org.hibernate.bytecode.enhance.spi.Enhancer] Weaving in PersistentAttributeInterceptable implementation on [org.acme.hibernate.orm.panache.Fruit]
[DEBUG] [org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer] Found @MappedSuperclass class io.quarkus.hibernate.orm.panache.PanacheEntity to collectPersistenceFields
[DEBUG] [org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer] Persistent fields for entity org.acme.hibernate.orm.panache.Fruit: [org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription@¤¤¤¤¤¤¤¤, org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription@¤¤¤¤¤¤¤¤]
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: quarkus-quickstarts/hibernate-orm-panache-resteasy/target/hibernate-orm-panache-resteasy-1.0-SNAPSHOT-runner.jar
```
On Windows:
```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in ¤¤¤¤ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: quarkus-quickstarts/hibernate-orm-panache-resteasy/target/hibernate-orm-panache-resteasy-1.0-SNAPSHOT-runner.jar
```

So on Windows, `org.hibernate.bytecode.enhance...` is not launched.

For more information, normalized partial Maven logs:
* [mvn-windows.normalized.log](https://github.com/quarkusio/quarkus/files/3165741/mvn-windows.normalized.log)
* [mvn-linux.normalized.log](https://github.com/quarkusio/quarkus/files/3165742/mvn-linux.normalized.log)

**Comment by jycr** [comment]
I also reproduce this issue on project: quarkus-quickstarts/hibernate-orm-resteasy (project without Panache)

**Comment by gsmet** [comment]
@jycr could you try to add breakpoints and understand why the enhancement is not done?

The first step would probably be to check if entities are passed to the enhancer.

BTW, do you somehow have a special character in the path to your classes (space, non ascii characters)?

**Comment by jycr** [comment]
Thanks to your reply @gsmet 
My workspace is in c:\tmp\quarkus-quickstarts\hibernate-orm-resteasy

Do you know where to put first breakpoints ?
Indeed, I do not know how the enhancer works. Is there any documentation that explain how it works ?

**Comment by sylvain-colucci-sg** [comment]
Hello,

I think i have found the source of the problem. 
In the class `AugmentPhase` (line 330), you are doing this : 

```java
final String className = pathName.substring(0, pathName.length() - 6).replace('/', '.');
```

The problem on windows, is that the `pathName` contains `\` instead of `/`. So the replacement is doing nothing, and any visitor can be found due to this (the visitor has to be executed to enhance the panache entities classes).

Hope it can help you to solve this problem.

Sylvain

**Comment by jycr** [comment]
Thanks to your reply @sylvain-colucci-sg

You right, problem fixed 

See: #2522
