### ISSUE TITLE
Quarkus.io 2.7.1 user remains authenticated, even if keycloak user session has disappeared

### ISSUE THREAD

**Issue by orivat** [quarkusio/quarkus#23869]
### Describe the bug

Within quarkus, the user will remain authenticated, even the keycloak user session has disappeared.

Steps to reproduce

Part I - keycloak configuration
----------------------------------------

Start keycloak on port 8180
sh standalone.sh -Djboss.socket.binding.port-offset=100

1. Create a quarkus realm.

2. Create a client_id application being confidential

Client_id: hello
Root URL localhost:8080/hello

Make this client confidential

3. Create a user (user1 /password)

Part II - quarkus configuration
----------------------------------------

4. Get simple hello example from getting started

mvn io.quarkus.platform:quarkus-maven-plugin:2.7.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions="resteasy"

4.  Make the /hello URL an application requiring to authenticate against keycloak

add The following to quarkus.properties

quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=hello
quarkus.oidc.credentials.secret=6ed5c221-e388-4f55-8a41-fa50ce238e94
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated 

5.  add oidc dependency to your project

./mvnw quarkus:add-extension -Dextensions="oidc"

6. start quarkus in debugging mode

mvn quarkus:dev

7. Invoke local:8080/hello URL

---> This will redirect you to keycloak
you have to log with user1/password

After authentication, you are redirected to the  local:8080/hello landing page

8. Destroy from keycloak admin console the current user session

9. Try again the hello URL  local:8080/hello

--->  local:8080/hello landing page is still displayed, whereas you should have been redirected to Keycloak for authentication

Conclusion:
Although the corresponding keycloak  user session has been destroyed, the corresponding quarkus hello landing page remains active, as if the user session was still valid.

 

 

### Expected behavior

It shall not be possible to authenticate to keycloak from hello URL

### Actual behavior

Although the corresponding keycloak  user session has been destroyed, the corresponding quarkus hello URL remains active, as if the user session was still valid.

### How to Reproduce?

already provide

### Quarkus version or git rev

2.7.1

**Comment by orivat** [comment]
[getting-started.zip](https://github.com/quarkusio/quarkus/files/8116007/getting-started.zip)

Getting started quarkus client

**Comment by orivat** [comment]
[realm-export.json.zip](https://github.com/quarkusio/quarkus/files/8116041/realm-export.json.zip)

Realm-export.json to be imported into keycloak

**Comment by sberyozkin** [comment]
@orivat I think this issue is invalid, if it were SPA which uses a Keycloak java script code then in your SPA it would be detected that the KC session has been terminated. With the quarkus `web-app` what controls the session between the browser and the Quarkus endpoint is the session cookie issued by Quarkus.
Currently the correct way to terminate this session is to do the [RP-initiated logout](https://quarkus.io/guides/security-openid-connect-web-authentication#logout) or manually remove this cookie.
However there are enhancement requests to support more advanced logout options, #23477, #23478. Specifically #23477 can help with detecting in Quarkus that the Keycloak session has been destroyed, so please watch that issue instead

**Comment by sberyozkin** [comment]
@orivat I'll make sure it is verified once #23477 is addressed, thanks

**Comment by sberyozkin** [comment]
Closing as a duplicate of #23477

**Comment by orivat** [comment]
@sberyozkin

I have made a test with:
-Keycloak
-quarkus OIDC client app  (1)
-Jboss OIDC client app (2)

step 1
Jboss and quarkus are authenticated against Keycloak

step 2:
The user session  is terminated at Keycloak

step3:
-Jboss app is disconnected
-Quarkus app remains active.


With Jboss app, keycloak is using JBoss client adapater.
When you click the Logout all button, all SSO cookies become invalid, and clients requesting authentication within active browser sessions must log in again. Keycloak notifies clients by using the Keycloak OIDC client adapter of the logout event

I agree that Quarkus client apps do not receive logout back channel notification, as mentioned in thread https://github.com/quarkusio/quarkus/issues/23477

Therefore to prepare migration from wildly /jboss app to quarkus, being able to support RP backchannel notifications is something really important  for a seamless integratin for OIDC client.
