### ISSUE TITLE
Print warning when -Dquarkus.container-image.build=true is used without a container image extension

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#23871]
### Description

Building with `-Dquarkus.container-image.build=true` without first adding a container image extension (see https://quarkus.io/guides/container-image) results in a successful build without any indications that there was no container image generated.

It would be nice to get a warning when no container image extension is added, instructing users to look up the corresponding documentation.

**Comment by geoand** [comment]
Very interesting.

@radcortez this sounds like some general which would be useful.

**Comment by radcortez** [comment]
I'll have a look

**Comment by geoand** [comment]
I guess this is similar to what we have with the unrecognized properties warning message we print at runtime. Only this time it's for build time
