### ISSUE TITLE
Bean marked with @Singleton created two times

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#23888]
### Describe the bug

We have a project consisting a couple of maven projects. One of the beans is marked as @Singleton. 
It is using quite a few quarkus features: @ActivateRequestContext, observes Startup event, uses @PostConstruct.

It is injected into a few places, one bean is getting a direct reference, the other one is using Instance<> and iterates over the beans.

In case the project is built using a newer much more powerful machine, then runner.jar produced *sometimes* contains duplicated instances of the given bean.

### Expected behavior

@Singleton beans should never instantiated twice.

### Actual behavior

Writing out registration and other information shows that in that case two instances are created.

### How to Reproduce?

I've tried to create a reproducer within a simple project, but it did not showed the symptom. 

### Quarkus version or git rev

2.2.2.Final

### Additional information

# Good machine
Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
**$ mvn --version**
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /opt/maven
Java version: 11.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-100-generic", arch: "amd64", family: "unix"

**$ uname -a**
Linux oahu 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**$ java --version**
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

# Bad machine
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**java -version**
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-suse-3.68.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.13+8-suse-3.68.1-x8664, mixed mode)

**$ uname -a**
Linux happyland 5.3.18-150300.59.49-preempt #1 SMP PREEMPT Mon Feb 7 14:40:20 UTC 2022 (77d9d02) x86_64 x86_64 x86_64 GNU/Linux

**mvn --version**
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/apache-maven-3.8.4
Java version: 11.0.13, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: hu_HU, platform encoding: UTF-8
OS name: "linux", version: "5.3.18-150300.59.49-preempt", arch: "amd64", family: "unix"

**Comment by smil2k** [comment]
As there is not reproducer, could you please help me to debug the context creation? I have runnable jar from a bad and a good build.

I've updated to quarkus 2.7.1 in the meanwhile.

**Comment by mkouba** [comment]
>  then runner.jar produced sometimes contains duplicated instances of the given bean.

How do you detect a "duplicated instance"?

> As there is not reproducer, could you please help me to debug the context creation? I have runnable jar from a bad and a good build.

Have you tried to log the stack trace inside the `@PostConstruct` callback? I'm not sure if a "runnable jar" is something that would help us.

**Comment by smil2k** [comment]
I'm printing the identityhashcodes at various locations (constructor, startup event etc)
I'll add stack traces as wel.

I'm using the quarkus maven plugin to construct the runnable application. 
This is referencing various other projects only, there is no code or resources in that particular project.

**Comment by mkouba** [comment]
> I'm printing the identityhashcodes at various locations (constructor, startup event etc)
> I'll add stack traces as wel.

Ok, more info would be really helpful.

**Comment by smil2k** [comment]
I noticed the SubClass therefore the println was added to the event handlers and the post construct calls.

In case the build creates a wrong jar then I see two beans, in case it is good, then I only see one. The difference is only that it was compiled 5 minutes later.

I'm working on adding stacktraces to the binaries. Unfortunately the odds of having such build is low, therefore I'll have to monkey patch them or add it using byteman or so.

**Comment by smil2k** [comment]
After upgrade to  2.7.1, the problem still occurs. Today the problem was more apparent, three times in a row wrong context was created:

Stacktrace for the constructor and postconstruct calls:
[ngbpdemo_backend_1_bad_stacktrace.log](https://github.com/quarkusio/quarkus/files/8132134/ngbpdemo_backend_1_bad_stacktrace.log)

After compiling only one of the modules and just recompile the runner, then the problem disappeared, even if the full project was built. Maybe there is a correlation between available memory, because it *seems* that the problem is more frequent in case the IDE is not running. 

This is how the same context and same source looks like with a good build:
[ngbpdemo_backend_1_jo1.log](https://github.com/quarkusio/quarkus/files/8132133/ngbpdemo_backend_1_jo1.log)

**Comment by mkouba** [comment]
> After compiling only one of the modules and just recompile the runner, then the problem disappeared, even if the full project was built. 

Hm, what does your app structure look like? Is it a multi-module project? Is `adapter.giro.workers.SendEventHandlerWorker` placed in a dependency or in the application itself, i.e. `src/main/java`?

**Comment by manovotn** [comment]
In case you get two beans created, is one of them ever destroyed? I.e. if you add a pre destroy callback, will it be invoked for one of them? Will the context be activated/deactivated multiple times (it definitely shouldn't be the case for singleton, I am just really shooting blind here).
Also, you mentioned that the bean has an observer for startup event - what's the chronological order of the dual bean creation and this event? Does one of them get notified, do both?

**Comment by smil2k** [comment]
@mkouba: We have 4-5 git repositories with a multi maven project inside each.
They all define beans and use jindex to help the discovery. 

One of the repositories contains the runnable jars, they have the quarkus-maven-plugin and they build the application. 

We build eigher using a pom adding all repos into one maven reactor or build the projects one by one and then as the last step the runnables. It does not matter which one is used the issue can be reproduced on that machine which more powerful CPU.

@manovotn:
Only one of the beans gets the startup notification.

It seems that in the bad case ReadModelComponent_Observer is called first, and then BatchedDBReadModelComponent_Observer. In the good case only the second.

**SendEventHandlerWorker** is extending **BatchedDBReadModelComponent** which is extending **ReadModelComponent**!

Both BatchedDBReadModelComponent and ReadModelComponent are base classes, but they are not declared abstract.

Readmodel:
    public void onStart(@Observes StartupEvent ev) {
        log.info("Subscribed {} to {}", getReadModelName() + "@" + System.identityHashCode(this), topic);
    }

Batched:
    @Override
    public void onStart(@Observes StartupEvent ev) {
        manager.load(this);
        super.onStart(ev);
    }

**Comment by mkouba** [comment]
Your setup looks fairly complex ;-).

> Both BatchedDBReadModelComponent and ReadModelComponent are base classes, but they are not declared abstract.

Well, if a non-abstract bean declares an observer method it's also registered as a bean with the scope `@Dependent`. And if `SendEventHandlerWorker` does not override the `onStart()` method it should inherit the observer method as well (and should be notified too).

> Only one of the beans gets the startup notification.

As explained above this should not be the case. But it's possible that there's a bug in impl.

What does `CurrentSettlementDateReadmodel.setupHooks()` do? From the stacktrace it seems that it instantiates the `SendEventHandlerWorker` bean as well...

**Comment by smil2k** [comment]
When I first saw the duplication I tried to make it as a reproducer and noticed that there are quite a few things are going on. I was not able to simplify it.

That class is injecting all implementations of a certain interface using @Inject Intance<Inteface> and iterates over it in postconstruct. It is only registering them as hooks.

**Comment by manovotn** [comment]
> Well, if a non-abstract bean declares an observer method it's also registered as a bean with the scope @Dependent

Or any other scope of those classes declare some (which I am not sure from the description).

I agree with Martin that I'd also expect multiple event notifications being delivered (and hence multiple bean creations) because at least two beans in that hierarchy are CDI beans.
We should probably look into how we handle event delivery in these cases, I am not sure we have a test for such hierarchical structure,

**Comment by smil2k** [comment]
I know that Startup does not happen, because this was the first thing we noticed: the connection object we wanted to use was not there, even though the log reported the successful creation of it in response to the startup event.

The one which received the event started working and the other instance was injected into an rest service class was a different class and uninitialized.

ReadModelComponent and BatchedDBReadModel component does not seem to exist on their own. The reason is probably that they have non-default constructors only with string params.

**Comment by mkouba** [comment]
> ReadModelComponent and BatchedDBReadModel component does not seem to exist on their own. The reason is probably that they have non-default constructors only with string params.

Yes, that would explain it.

**Comment by smil2k** [comment]
@mkouba 
Which parts would be particularly helpful? Unfortunately the application jars in its whole cannot be shared publicly.

**Comment by mkouba** [comment]
> @mkouba Which parts would be particularly helpful? Unfortunately the application jars in its whole cannot be shared publicly.

Hm, the `quarkus-app/quarkus/generated-bytecode.jar` might be useful. This jar contains the generated metadata classes for CDI (beans, observers, etc.).

**Comment by smil2k** [comment]
Can you give a private drop point?

**Comment by mkouba** [comment]
> Can you give a private drop point?

If possible pls join the [quarkus zulip chat](https://quarkusio.zulipchat.com) and ping me there...

**Comment by smil2k** [comment]
Leaving out the @Observes annotation on the overriding method (BatchedDBReadModel) seems to solve the duplication.

**Comment by manovotn** [comment]
Yes, that corresponds to what we wrote earlier.
I might have some time tomorrow to tinker with how Arc does event delivery in these cases with inheritance, but the chances I will spot this race condition you are seeing are low. But you never know :)

**Comment by smil2k** [comment]
I think it is probably wrong to duplicate the annotation together with inheritance. Maybe an error in the annotation processor would help to eliminate it in the first place. 

Maybe some lines of warning in the doc.

**Comment by manovotn** [comment]
> I think it is probably wrong to duplicate the annotation together with inheritance.

It is not wrong. CDI allows you to do that and the behavior should be subject to inheritance rules defined in CDI. This way you can override the logic of the method in each subclass while keeping it as an observer. However, the behavior you spotted is definitely weird.

**Comment by mkouba** [comment]
Hm, after some more investigation I found out that although the logic in the generated `_Observer` is wrong it should _still_ work... I'll continue with the investigation.

**Comment by mkouba** [comment]
My findings were actually correct. There was another problem that it was possible to store a `@Singleton` bean instance in the application context. I'll shortly send a PR with a fix.
