### ISSUE TITLE
Jib docker image working directory changed

### ISSUE THREAD

**Issue by RuggeroDAlo** [quarkusio/quarkus#23899]
### Description

I understand that due to https://github.com/quarkusio/quarkus/pull/23670 the default working directory for jib has changed from /work/ to /home/jboss.

Mounting configmaps in /work/config/application.yaml (when running the built container in k8s) no longer works, I've had to change the path to /home/jboss/config/application.yaml.

Is there a way to configure the working directory?

Also maybe a note could be added to the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7 ?

**Comment by geoand** [comment]
> Also maybe a note could be added to the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7 ?

Good point, added.

> Is there a way to configure the working directory?

I'll add it.
