### ISSUE TITLE
Qute Template when running unit tests

### ISSUE THREAD

**Issue by HugoVinhal98** [quarkusio/quarkus#23897]
### Describe the bug

I am using Quarkus Template for a base email HTML template like this:

```@Location("MailTemplate")
Template template;

... code ...

public void sendEmail(final SendEmailRequest sendEmailRequest) {
        final String html = template.data("sendEmailRequest", sendEmailRequest).render();
}
```

When I try to mock the interface using @Mock it gives me an error and the property comes as null instead of mocked. Im mocking like this:

```
@ExtendWith(MockitoExtension.class)
public class EmailServiceTest {

    @Spy
    @InjectMocks
    EmailService emailService;

    @Mock
    Template templateMock;

    @Test
    void sendEmail() {
        // Given
        SendEmailRequest sendEmailRequest = EmailDataProvider.createSendEmailRequest();

        // When
        emailService.sendEmail(sendEmailRequest);

    }
}
```

```The error: java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.Template.data(String, Object)" because "<local3>.template" is null```

I usually mock other services/repositories like this, but it seems like that for this interface this doesnt work 😢  I also already tried to place a different html file in the tests resources so that the tests would try to find it but that didnt work as well.

### Expected behavior

The Template instance should not be null and should be a valid/mocked Template.

### Actual behavior

The Template instance is null when I run the unit tests that use the instance.

**Comment by mkouba** [comment]
Where does the `@Mock` come from? Is the NPE thrown because no template is injected in the mocked `EmailService`? I think that you would need to "inject" the `Template` instance manually but it's just a blind guess, we'll need more information, ideally a reproducer app. In any case, `@InjectMock` or `QuarkusMock` would not work for an injected `Template` because the relevant beans are `@Dependent`, i.e. not normal scoped. Maybe @geoand would know some more mocking tricks...

>  I also already tried to place a different html file in the tests resources so that the tests would try to find it but that didnt work as well.

If you need to mock a `Template` injected by the container you can leverage the [CDI `@Alternative` mechanism](https://quarkus.io/guides/getting-started-testing#cdi-alternative-mechanism), i.e. place a bean like this in the `src/test/java`:

```java
import io.quarkus.test.Mock;

@ApplicationScoped 
public class MockTemplateProducer {
    
    @Produces
    @Mock
    Template produce(InjectionPoint ip, Engine engine) {
      // return a template instance based on the IP, e.g. engine.parse("Hello foo!")
    }
}

```

**Comment by HugoVinhal98** [comment]
The `@Mock` comes from Mockito. I tried creating the MockTemplateProducer but I am not sure how should I make use of it. Should I change something in the unit test to make it work?

**Comment by mkouba** [comment]
> Should I change something in the unit test to make it work?

It depends on whether the bean that injects the `Template` is mocked or not. If it is then you'll likely have to "inject" the template manually, i.e. no `MockTemplateProducer` is needed. If it's not then your mocked producer will be called when the container injects the `Template`. But as I said we'll need more info.

**Comment by HugoVinhal98** [comment]
Well I figured out what the problem is by trying to replicate this in a more basic project. Basically I am using the constructor to initialize all the dependencies of the EmailService (in this example), like this:

```
@ApplicationScoped
public class EmailService {

    /**
     * Template used for the emails being sent.
     */
    @Location("MailTemplate")
    Template template;

    private final Mailer mailer;

    private final EmailRepository emailRepository;

    /**
     * All arguments constructor.
     *
     * @param mailer quarkus service to send emails
     * @param emailRepository quarkus service to send emails
     */
    @Inject
    public EmailService(final Mailer mailer, final EmailRepository emailRepository) {
        this.mailer = mailer;
        this.emailRepository = emailRepository;
    }
```

@mkouba is there any way around this? I guess I could use `@Inject` for the Mailer and EmailRepository but this is not the convention on our projects.

**Comment by mkouba** [comment]
> is there any way around this?

I don't understand. What exactly is wrong? Also you can add the `@Location("MailTemplate") Template template` param to the constructor and make the `template` field `final` as well.

**Comment by HugoVinhal98** [comment]
Yup, this solved my problem! I changed my code to this and now everything is working properly 😄 

```
@Inject
public EmailService(final Mailer mailer, final EmailRepository emailRepository, @Location("MailTemplate") Template template) {
        this.mailer = mailer;
        this.emailRepository = emailRepository;
        this.template = template;
}
```

**Comment by mkouba** [comment]
I'm glad it works now although I don't understand the details ;-)

**Comment by HugoVinhal98** [comment]
I guess the unit tests werent able to mock the template since it wasnt being injected in the service like the Mailer and EmailRepository. By placing the Template inside the constructor the problem was resolved.
