### ISSUE TITLE
Qute template allow data to parse html

### ISSUE THREAD

**Issue by HugoVinhal98** [quarkusio/quarkus#23893]
### Description

I have started using Qute Template in my new Quarkus Notification Service and I was trying to figure out how to enable the data passed to the email template to render as html. 

This is basically what I have:

`final String html = template.data("content", content).render();`

If I pass html in this "content" data I am unable to render as HTML, and it just shows all the tags in the sent email 😢 Is there any way I can achieve this?

**Comment by mkouba** [comment]
You need to output the unescaped value: (1) either use the `raw` or `safe` computed properties  in the template (`{content.raw}` or `{content.safe}`) or (2) wrap the `String` value in a `io.quarkus.qute.RawString` (`template.data("content", new RawString(content)).render()`). See also [Character Escapes](https://quarkus.io/guides/qute-reference#character-escapes).

**Comment by HugoVinhal98** [comment]
Thank you for the fast solution 😄 I just saw that this is already covered in the documentation, I was just a bit blind 😭

**Comment by preslavrachev** [comment]
Is it possible to only keep the ampersands, ticks, parentheses, etc. unescaped, while escaping all other HTML code that may be present in the string? I noticed that when using `.safe`, the entire string value gets interpolated locally, which may result in some nasty HTML injection, or at the very least, break the layout of a web page.

**Comment by mkouba** [comment]
> Is it possible to only keep the ampersands, ticks, parentheses, etc. unescaped, while escaping all other HTML code that may be present in the string? I noticed that when using `.safe`, the entire string value gets interpolated locally, which may result in some nasty HTML injection, or at the very least, break the layout of a web page.

Well, you can implement your own `io.quarkus.qute.ResultMapper` to apply any escaping to `io.quarkus.qute.RawString` as well. The logic of the default HTML escaper is pretty straightforward - see `io.quarkus.qute.HtmlEscaper`.

You'll need to [customize the preconfigured Engine instance](https://quarkus.io/guides/qute-reference#engine-customization), i.e. register the new result mapper.
