### ISSUE TITLE
Can't use Optional with List with @QueryParam with reasteasy controller

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#23898]
### Describe the bug

When using @QueryParam("name") Optional<List<Long>> in a resteasy reactive controller, we get an error:

```
//
Caused by: java.lang.RuntimeException: Failed to find converter for java.util.List 
//
```

When used without Optional we don't get this error. 

This works: 

```java

    @GET
    @Path("/table")
    @Transactional
    public Page<Stuff> getStuff(
        @QueryParam("test") final List<Long> ids,
        @BeanParam PageReq page
    ) {
       //
    }
```

### Expected behavior

We can use an Optional<List<Long>> in a resteasy reactive controller

### Actual behavior

We get a compilation error

### How to Reproduce?

1. create a Quarkus project, with reasteasy-reactive extension
2. create a controller with the following endpoint

```java

    @GET
    @Path("/table")
    @Transactional
    public Page<Stuff> getStuff(
        @QueryParam("test") final Optional<List<Long>> ids,
        @BeanParam PageReq page
    ) {
       //
    }
```

### Quarkus version or git rev

tested with 2.6.3.Final and tested in 2.7.2.Final

**Comment by Sgitario** [comment]
fyi: I've proposed a solution for this issue in https://github.com/quarkusio/quarkus/pull/24055
