### ISSUE TITLE
OpenSearch dev-services

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#23906]
### Description

Follow-up on https://github.com/quarkusio/quarkus/pull/23753.

Currently, the Elasticsearch dev-services will only work when using Elasticsearch, not when using OpenSearch. That's a shame, because some extensions (the low-level Elasticsearch client, Hibernate Search) will work perfectly fine with OpenSearch.

Let's add support for OpenSearch dev-services.

See also: https://github.com/quarkusio/quarkus/pull/23753#discussion_r808172645

**Comment by apatrida** [comment]
See: https://github.com/sort-dev/quarkus-opensearch
as starting point, and go back to the commit for last 2.14.x Quarkus version 75645a90f4b0b37cfcd5bede60085fb13acf09d3 as the best starting point.
