### ISSUE TITLE
Elasticsearch dev-services when multiple extensions use Elasticsearch

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#23904]
### Description

Follow-up on #23753.

See the "limitations" section of the documentation of Elsaticsearch dev-services:

> Currently, Elasticsearch Dev Services cannot be used if both Hibernate Search ORM Elasticsearch and an Elasticsearch client extension are used,
this will result in an exception on startup.
> 
> Currently, only the default backend for Hibernate Search Elasticsearch is supported, because Dev Services for Elasticsearch can only start one Elasticsearch container.

We should try to address those limitations; the first one can be particularly problematic.

See also this conversation: https://github.com/quarkusio/quarkus/pull/23753#discussion_r811146353

**Comment by loicmathieu** [comment]
> Currently, Elasticsearch Dev Services cannot be used if both Hibernate Search ORM Elasticsearch and an Elasticsearch client extension are used,
this will result in an exception on startup.

I'll work on this one as it's not very complex for now: allow multiple build item and in this case list all properties and set them. I'll provide a PR soon.

**Comment by yrodiere** [comment]
I'll consider closed; I opened #24011 for the multi-PU/multi-backend scenarios with Hibernate Search.
