### ISSUE TITLE
gRPC does not discover `@Blocking` correctly

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#23912]
### Describe the bug

`io.quarkus.grpc.deployment.GrpcServerProcessor#gatherBlockingMethods` only discovers `@Blocking` on classes that directly extend the gRPC `*ImplBase` classes, but not on subclasses.

`@Blocking` discovery works in these cases:
```java
@Blocking
@GrpcService
class MyService extends MyServiceImplBase {
  // ...
}
```

and

```java
// in another artifact
@GrpcService
class MyServiceSuper extends MyServiceImplBase {
  // ...
}

class MyService extends MyServiceSuper {
  // @Blocking must be applied to all methods - aka must override all methods here
  @Blocking
  @Override
  void methodFromMyServiceImplBase() {
    // ...
  }
}
```

`@Blocking` discovery does not work in this case:
```java
// in another artifact
class MyServiceSuper extends MyServiceImplBase {
  // ...
}

@Blocking // doesn't work, not detected by GrpcServerProcessor#gatherBlockingMethods
@GrpcService
class MyService extends MyServiceSuper {
  // ...
}
```

### Expected behavior

Allow `@Blocking` on classes that indirectly extend `*ImplBase`

### Actual behavior

`@Blocking` is not detected for `class MyService extends BaseService extends MyServiceImplBase` (not proper Java...)

### Quarkus version or git rev

2.7.2

**Comment by snazy** [comment]
I'll try to prepare a PR to fix this one.

**Comment by mkouba** [comment]
Hello @snazy, I miss the `@GrpcService` annotation in the examples. Is `MyService` supposed to be the service impl that should be registered?

**Comment by snazy** [comment]
> Hello @snazy, I miss the `@GrpcService` annotation in the examples. Is `MyService` supposed to be the service impl that should be registered?

Oops, yea. Updated the description.

**Comment by mkouba** [comment]
```java
@Blocking // doesn't work, not detected by GrpcServerProcessor#gatherBlockingMethods
@GrpcService
class MyService extends MyServiceSuper {
  // ...
}
```
Yes, `@Blocking` discovery would not work for methods declared on the `MyServiceSuper` because only methods declared on the service impl are discovered.

**Comment by snazy** [comment]
@michalszynkiewicz think we can close this one too since #23927 is merged now, right?

**Comment by michalszynkiewicz** [comment]
Yes, let's do it
