### ISSUE TITLE
gRPC `@Blocking` method matching with Java methods

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#23911]
### Describe the bug

`io.quarkus.grpc.deployment.GrpcServerProcessor#gatherBlockingMethods` uses `MethodInfo` for all methods. This includes all synthetic methods like lambda methods.

The following example produces a Java class with a default constructor, a static method `doSomehting` and a synthetic method for the lambda used in the contstructor.

That synthetic method is then used for blocking-method detection, which feels wrong.

```java
class MyService extends MyServiceImplBase {
  MyService() {
    // adds a synthetic "lambda" method
    doSomething(() -> new Something());
  }

  static void doSomething(Supplier<Something> supplier) {
    // ...
  }
}
```

### Quarkus version or git rev

2.7.2

**Comment by snazy** [comment]
I'll try to prepare a PR to fix this one.

**Comment by snazy** [comment]
Tackled in #23927 as well

**Comment by mkouba** [comment]
> Tackled in #23927 as well

Where exactly do you filter out the synthetic methods in that PR?

**Comment by snazy** [comment]
> > Tackled in #23927 as well
> 
> Where exactly do you filter out the synthetic methods in that PR?

It doesn't explicitly filter anymore. Instead it looks up the `*ImplBase` class and collects the service method from there. So it doesn't need a particular check for lambda methods.
