### ISSUE TITLE
blocking gRPC w/ OpenTelemetry, interecptor order matters

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#23913]
### Describe the bug

I know that OpenTelemetry isn't fully supported in Quarkus yet, but wanted to share my findings.

When using `io.opentelemetry.instrumentation:opentelemetry-grpc-1.6` in combination with `@Blocking` gRPC methods, the order of the interceptors is important. `BlockingServerInterceptor` must be the "outermost" interceptor, otherwise opentelemetry will "bark" that spans aren't properly closed.

Further, only version 1.10.1-alphta of `io.opentelemetry.instrumentation:opentelemetry-grpc-1.6` seems to work (with Quarkus 2.7.2), but 1.11.0-alpha and 1.11.1-alpha cause client requests to "hang" (no server side activity).

### Quarkus version or git rev

2.7.2

**Comment by snazy** [comment]
Not sure whether it's an exact duplicate, but pretty related. There's also the incompatibilities/issues w/ newer opentelemetry-grpc-1.6 version. I'll try to build a reproducer and dig into why exactly it's failing with the newer versions.

**Comment by geoand** [comment]
Okay thanks

**Comment by radcortez** [comment]
Specific OTel libraries are not officially supported at this point. Until proper support is actually added, any issue/fix will probably just be a bandaid.

I would prefer to just concentrate everything into a single issue.

**Comment by snazy** [comment]
Makes sense, let's use #23805 then.

**Comment by radcortez** [comment]
Thanks :)
