### ISSUE TITLE
`TestEngine` exclude/include filter for continuous testing

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#23929]
### Description

As of Quarkus 2.7.2 there can be classloading issues when running (field-stlye) ArchUnit tests and there is no way to exclude those, because the existing filters don't cover [`com.tngtech.archunit.junit.FieldSource`](https://github.com/TNG/ArchUnit/blob/v0.23.0/archunit-junit/junit5/engine-api/src/main/java/com/tngtech/archunit/junit/FieldSource.java) yet. See also: https://github.com/quarkusio/quarkus/pull/23358#discussion_r813325181

Other auto-discovered engines might cause issues as well, so it would come in handy to exclude a certain engine via config.

PS: My workaround for ArchUnit is the following (in a `qtest` Maven profile):
```xml
                <dependency>
                    <groupId>com.tngtech.archunit</groupId>
                    <artifactId>archunit-junit5</artifactId>
                    <version>${archunit.version}</version>
                    <scope>test</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>com.tngtech.archunit</groupId>
                            <artifactId>archunit-junit5-engine</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
```

### Implementation ideas

There is already `org.junit.platform.launcher.EngineFilter`, so the change looks easy.

**Comment by maxRN** [comment]
Hi, sorry to comment on such an old issue, but is this the intended behavior regarding ArchUnit tests and continuous testing? I'm asking, because we are also running into the issue that ArchUnit tests fail when running the `quarkusTest` gradle task. So if I read this correctly the current recommended solution is to just ignore the errors during continuous testing? Is Quarkus going to support this use case in the future?

**Comment by famod** [comment]
@maxRN Greetings to Dresden from a former Dresdener ;-)

I haven't had a closer look at this topic for a long time, but I don't think anything has changed. Maybe @geoand or @holly-cummins know more.

> So if I read this correctly the current recommended solution is to just ignore the errors during continuous testing?

You should be able to avoid _executing_ archunit tests in the first place via:
https://quarkus.io/guides/continuous-testing#quarkus-test-dev-testing-test-config_quarkus.test.exclude-engines
i.e. `quarkus.test.exclude-engines=archunit`

**Comment by geoand** [comment]
> but I don't think anything has changed

This is true AFAIK
