### ISSUE TITLE
Optional not working with @QueryParam in BeanParam

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#23939]
### Describe the bug

When using @QueryParam in conjunction with @BeanParam Optional fields are not working.

I'm using resteasy-reactive

### Expected behavior

We can automatically wrap null in Optional to have a nicer developper experience and have our code behave in BeanParam the same way it does with plain controller

### Actual behavior

We have a null instead of an Optional.empty()

### How to Reproduce?

Reproducer:

1. Create a quarkus project with version 2.7.2.Final
2. Add the reasteasy-reactive and resteasy-reactive-jackson extension
3. Create a controller using a BeanParam and a Bean to receive the params

here the bean:
```java
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Slf4j
public class PageQuery {
    
    public static final Integer DEFAULT_PAGE = 0;
    public static final Integer DEFAULT_SIZE = 10;
    public static final Integer MAX_SIZE = 10;
    
    @QueryParam("page")
    private Optional<Integer> rawPage;
    @QueryParam("size")
    private Optional<Integer> rawSize;
    @QueryParam("sort")
    private Optional<String> sort;

    /**
     * Transforms the POJO to a Pageable for easy use with Spring repository
     * 
     * @return
     */
    public Pageable toPageable() {
        final var page = rawPage.orElse(DEFAULT_PAGE);
        // we limit the max size here
        final var size = Integer.max(rawPage.orElse(DEFAULT_SIZE), MAX_SIZE);
        log.info("page: " + rawPage + ", size: " + rawSize+ ", " + sort);
        return sort.map(s -> {
            final var r = s.split(",");
            final var column = r[0];
            final var direction = Sort.Direction.fromString(r[1]);
            return PageRequest.of(page, size, Sort.by(direction, column));
        }).orElse(PageRequest.of(page, size));
    }
}

```

4. Use it in a Controller with the @BeanParam annotation

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by Postremus** [comment]
I can reproduce this.

A queryparam declared as Optional<String> directly on the resource method gives an Optional.empty if not set in the request.
Optional<String> Queryparams in the beanparam are set to null.

![image](https://user-images.githubusercontent.com/1223135/167263581-0f51558c-7547-4ae2-9591-61cfea087642.png)

I will try to come up with a fix. Imo for optional we should always set Optional.empty if not specified in the request.
