### ISSUE TITLE
Opentelemetry traces for reactive services contain erroneus values

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#23940]
### Describe the bug

When running application with enabled jaeger tracing, traces contain not just endpoints but also mysterious "HTTP GET" string, but only if the application uses reactive endpoints and Quarkus 2.7.2.Final.

### Expected behavior

Tracing should work the same way for reactive and not-reactive libraries.

### Actual behavior

Traces for a non-reactive application(or for version 2.7.1.Final) contain "ping/pong", "hello", "hello", traces for a reactive application contain "hello", "HTTP GET", "ping/pong"

### How to Reproduce?

Reproducer:
git@github.com:quarkus-qe/quarkus-test-suite.git
Command to reproduce:
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry-reactive -Dquarkus.platform.version=2.7.2.Final`

Commands, which do not lead to this failure:
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry-reactive -Dquarkus.platform.version=2.7.1.Final`
`mvn clean verify -pl io.quarkus.ts.qe:monitoring-opentelemetry -Dquarkus.platform.version=2.7.2.Final` (module monitoring-opentelemetry contains the same test and code logic, but uses non-reactive REST)

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.16.7-200.fc35.x86_64"

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by radcortez** [comment]
In some situations, it may not be possible to determine the route name properly. In that case, it follows the OTel specification:

> HTTP spans MUST follow the overall [guidelines for span names](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span). Many REST APIs encode parameters into URI path, e.g. /api/users/123 where 123 is a user id, which creates high cardinality value space not suitable for span names. In case of HTTP servers, these endpoints are often mapped by the server frameworks to more concise HTTP routes, e.g. /api/users/{user_id}, which are recommended as the low cardinality span names. However, the same approach usually does not work for HTTP client spans, especially when instrumentation is provided by a lower-level middleware that is not aware of the specifics of how the URIs are formed. Therefore, HTTP client spans SHOULD be using conservative, low cardinality names formed from the available parameters of an HTTP request, such as "HTTP {METHOD_NAME}". Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.

And that is what they do in their implementation:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpSpanNameExtractor.java#L34-L45

I'll check if it is possible to determine the name in this case.

**Comment by radcortez** [comment]
https://github.com/quarkusio/quarkus/pull/24134 improved this.
