### ISSUE TITLE
Timeout when using quarkus-kafka-streams extension

### ISSUE THREAD

**Issue by fcoutinho-uolinc** [quarkusio/quarkus#23948]
In our production environment we have way too many topics.
And because of that we constantly get timeouts when initializing the application
(As of now the list topics operation timeout is fixed at 10 seconds)

https://github.com/quarkusio/quarkus/blob/36351d4412da3a529ed2c020b0fd6ad2a8145bcb/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsProducer.java#L327

We currently do not use the validation if the topic was created or not. It would be very helpful for us if we could:
1. Completely disable this verification
2. Increase the timeout of the operation

Because of this issue , we are unable to use the quarkus-kafka-streams extension :cry:

**Comment by rquinio1A** [comment]
I wonder if we could use `AdminClient#describeTopics(Collection<String> topicNames)` instead to improve the performance (and what happens in case topic doesn't exist) ?

What happens today when you set `quarkus.kafka-streams.topics=""` ? I wonder if it's mapped to an empty array or fails because it's mandatory. Also relates to #8909.

**Comment by fcoutinho-uolinc** [comment]
If I set `quarkus.kafka-streams.topics=""` the application fails because it is a mandatory field :crying_cat_face:
I think is more efficient to use the method you described, but I honestly don't know what happens when the topic is not created

**Comment by gsmet** [comment]
I would say it probably makes sense to add configuration properties for both the use cases you mentioned.

Care to create a PR?

**Comment by alesj** [comment]
I guess for me to duplicate this, I would either need a lot of topics or enough topics + shorter timeout?

**Comment by alesj** [comment]
> I would say it probably makes sense to add configuration properties for both the use cases you mentioned.

@gsmet which "both" did you have in mind
* skip the check and use `describeTopics`
* skip the check and configure timeout

I'll then have PR ready ...
