### ISSUE TITLE
oracle jdbc connection doesn't work if oracle db charset is JA16SJIS

### ISSUE THREAD

**Issue by esorio** [quarkusio/quarkus#23945]
### Describe the bug

I have a project that connects to oracle db using the jdbc-oracle extension.
When I connect to a oracle db with UTF8 charset everything works.
If I use an oracle db with a different charset (for instance JA16SJIS) the application hangs with the following exception:
`java.sql.SQLException: Non supported character set (add orai18n.jar in your classpath)`

To fix the issue I added explicitly the following dependency
`runtimeOnly group: 'com.oracle.database.nls', name: 'orai18n', version: '21.3.0.0'`

In my opinion would be better to add this dependency directly to the jdbc-oracle extension, to avoid versions mismatch between jdbc connector and the orai18n jar.

### Expected behavior

The application should work with oracle db with charset different from UTF-8.

### Actual behavior

The application hangs with the following exception:
`java.sql.SQLException: Non supported character set (add orai18n.jar in your classpath)`

### Output of `java -version`

OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)

### Quarkus version or git rev

2.6.1.Final

**Comment by gsmet** [comment]
AFAICS the version of this artifact is defined in the Oracle BOM we import in Quarkus. So you shouldn't have to define the version. Can you confirm that?

We should probably document the error and how to solve it though.

**Comment by esorio** [comment]
Yes, you are right! If I remove the version the right one is inherited.

**Comment by esorio** [comment]
Yes, you are right! If I remove the version the right one is inherited.

**Comment by esorio** [comment]
Yes, you are right! If I remove the version the right one is inherited.

**Comment by esorio** [comment]
Yes, you are right! If I remove the version the right one is inherited.

**Comment by Sanne** [comment]
We could also include this dependency by default I guess.  I'm not entirely sure about where to draw the line as there are quite some optional dependencies, but I think this one in particular is relatively harmless when unused (and useful when it is).
