### ISSUE TITLE
Reactive REST Client probably should not call ResponseExceptionMapper when Response is returned

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#23957]
### Describe the bug

I have a REST Api:

```java
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/v1/test")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface ErrorInducer {

  @Path("/add")
  @POST
  Response add(Args args);
}
```

The add method returns a '400' status code within the Response.  I do not expect any WebApplicationException to be thrown.

### Expected behavior

No exceptions thrown.

### Actual behavior

Registered ResponseExceptionMapper<RuntimeException>(s) are called to translate the response to an exception.

### How to Reproduce?

Code above

### Additional information

I'm not sure if the spec addresses what the behavior should be when API method returns a Result.

**Comment by geoand** [comment]
What version of Quarkus are you using? 
I do remember this being a problem with older versions, but I think it was fixed.

**Comment by chonton** [comment]
2.7.1.Final

**Comment by geoand** [comment]
Thanks. I'll have a look

**Comment by geoand** [comment]
Although I agree this looks weird, it seems that it's mandated by the spec (see https://github.com/quarkusio/quarkus/pull/24001 which actually fails the TCK).

What you can do however is disable `DefaultMicroprofileRestClientExceptionMapper` by configuring `microprofile.rest.client.disable.default.mapper=false`

**Comment by geoand** [comment]
> Is there a way to limit this configuration to a certain client via application.properties? It can be done [programmatically](https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html#_default_responseexceptionmapper), but an annotation would also be useful for this. 

There is not, I suggest opening a new issue asking for this

**Comment by FroMage** [comment]
I agree too, it's counter-intuitive that exceptions can come in two ways: return type and exception. When the return type allows for exceptions to be returned, that should be the only way to return exceptions.

**Comment by neon-dev** [comment]
I wanted to check the spec mentioned earlier, but the links in https://github.com/quarkusio/quarkus/pull/24001#issuecomment-1054021601 are dead and I couldn't find the test classes by name.
Would it be worth reopening #24001 to see if current tests pass, by any chance?

> There is not, I suggest opening a new issue asking for this

As it turns out, I don't need this feature at the moment, so I'd only open a new issue for it if you think it's important to have it.

**Comment by geoand** [comment]
I do think it's important yeah

**Comment by neon-dev** [comment]
> I do think it's important yeah, but it will have to be an opt-in thing

#44813
