### ISSUE TITLE
Support @Encoded for query parameters in REST Client Reactive

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#23961]
### Description

From [GitHub discussion](https://github.com/quarkusio/quarkus/discussions/23935):

Hello,

I am following this guide https://quarkus.io/guides/rest-client to communicate with a 3rd party API. Overall everything works but there is a small issue I am running with query param.

I am able to set up query param as described in the tutorial. However, I am not able to use the Encoded string as a query param.

For example

I have this endpoint

```kotlin
   @Path("/device")
   @GET
   fun deviceSelect(@QueryParam("\$select")  selectQuery: String): ListOf<DeviceMeta>
```
Also, the third-party follows the [odata](https://www.odata.org/getting-started/basic-tutorial/#select) conventions.

Now when I pass in a single field into this method, everything works, I get a list with that field.

However, when I put in multiple fields, so something like deviceSelect("name,id"), I run into malformed URL. Basically, the other endpoint is expecting the actual , but our endpoint is passing it with % encoded.

i.e valid: /device?$select=name,id
whats generated: /device?%24select=name%2Cid

I know the third-party API is supposed to handle the encoded inputs but I need a solution while they fix that.

I tried annotating the param, method, and class with @Encoded but had no luck...

**Comment by michalszynkiewicz** [comment]
CC @sraturi

**Comment by geoand** [comment]
The alternative being that the user needs to setup the proper string manually?

**Comment by michalszynkiewicz** [comment]
IIUC, curerntly @sraturi is not able to se

**Comment by geoand** [comment]
Yeah, I'm not so sure doing this on the client is correct way to go...

**Comment by bboyz269** [comment]
We really don't have any saying in 3rd party service implementations ...  
Is there any possible point we can intercept to work around?

**Comment by geoand** [comment]
Not really

**Comment by xaderfos** [comment]
I'm trying to understand if this is the same issue I'm facing with using a DOI id as a path param.
The API I'm calling is expecting it this way and DOIs have a forward slash by design that gets encoded and then it does not match the original id.
Can we not control/disable the encoding of the parameters? If not does this mean one cannot use the rest client for such use cases? That would be a bit absurd imho...
