### ISSUE TITLE
Config doesn't work with multi module and quarkus:dev

### ISSUE THREAD

**Issue by goblinbr** [quarkusio/quarkus#2396]
I've created a multi module project based on https://github.com/quarkusio/quarkus/tree/master/devtools/maven/src/test/resources/projects/multimodule

But when I run with "mvnw compile quarkus:dev" the @ConfigProperty doesn't work, it doesn't load the configuration and even the defaultValue doesn't work. But when I compile and run  the runner.jar it works.

The project:
https://github.com/goblinbr/quarkus-multimodule-test

Quarkus version: 0.14.0
Java version: 
openjdk version "1.8.0_171-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_171-1-ojdkbuild-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
OS: Windows 10 (1803)

**Comment by goblinbr** [comment]
Just built quarkus from master and this is already fixed.

**Comment by gsmet** [comment]
@goblinbr I plan to release the next one on Monday.

**Comment by Sergey80** [comment]
any link on github example that works with multi-module project?

**Comment by Sergey80** [comment]
any link to working multi-module project?
