### ISSUE TITLE
Rest Client sets own User-Agent header even if user specifies a different one

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#23966]
### Describe the bug

This issue is based on the Zulip chat: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/io.2Evertx.2Ecore.2Ehttp.2Eimpl.2ENoStackTraceTimeoutException

We have a reactive rest client where we set a custom `User-Agent` header. The user agent needs to be this specific value for the API to accept our request. 

```
@RegisterRestClient(configKey = "xxxxx")
@Produces(MediaType.APPLICATION_JSON)
interface GatewayApi {
    @GET
    @Path("zzzzz")
    suspend fun getUser(
        @HeaderParam("Accept-Language") acceptLanguage: String,
        @HeaderParam("x-request-tracing-id") traceId: String,
        @HeaderParam("x-api-key") apiKey: String,
        @HeaderParam("User-Agent") userAgent: String
    ): Response
}
```

Unfortunately, it seems that Quarkus versions >= 2.7.0 add an own `User-Agent` header value with the value: `Resteasy Reactive Client`. This value is always added, no matter if we set our own `User-Agent`. So when we make a request the `User-Agent` header has the values: `[Resteasy Reactive Client, Our_Custom_Header_Value]` compared to versions <= 2.6.3 where the `User-Agent` values is `[Our_Custom_Header_Value]`.

A workaround is to add a custom ClientHeadersFactory and register it to above interface. For example:

```
class GatewayHeadersFactory: ClientHeadersFactory {
    override fun update(incomingHeaders: MultivaluedMap<String, String>?, clientOutgoingHeaders: MultivaluedMap<String, String>?): MultivaluedMap<String, String> {
        val clientHeaders = MultivaluedHashMap<String, String>()
        "Our_Custom_Header_Value".addHeader("User-Agent", clientHeaders)
        return clientHeaders
    }
}
```

### Expected behavior

The rest client should only add its own `User-Agent` header when we do not specify our own header. This should apply when the header is set with the `@HeaderParam` annotation in the method as well as when using `@ClientHeaderParam` to set a `User-Agent` header. 

### Actual behavior

The rest client always adds it's own User-Agent header.

**Comment by michalszynkiewicz** [comment]
@stuartwdouglas I'll change it so that only if the User-Agent is not set, the default value is set.
