### ISSUE TITLE
Kafka dev services can not be used with redpanda images from outside of DockerHub

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#23978]
### Describe the bug

Devmode for Kafka explicitly requires, that images should be from vectorized/redpanda dockerhub repository. Because of that, even if the very same is copied to other docker repository, it can be used.

The reproducer uses image `quay.io/quarkusqeteam/redpanda` which was copied with docker pull/push from DockerHub to quay.io

### Expected behavior

Kafka dev services should work with redpanda images from any repository

### Actual behavior

Error: `IllegalArgumentException: Only vectorized/redpanda images are supported`

### How to Reproduce?

1. `git clone -b reproducer/redpanda git@github.com:fedinskiy/quarkus-test-suite.git`
2. `cd super-size/many-extensions`
3. `mvn clean validate compile test package verify -Dall-modules -DexcludedGroups=fips-incompatible -Dit.test=DevModeManyExtensionsIT`

### Output of `uname -a` or `ver`

5.16.7-200.fc35.x86_64

### Output of `java -version`

 11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.2.Final, 2.2.5.Final, 3bda8b29565261d2dc188f8feda6d027eb085d6f

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by cescoffier** [comment]
That's an interesting issue. What are you trying to do in your image? 

The restriction comes from the fact that we were not able to run "plain" kafka as dev service. This limitation has been lifted recently. So, we could imagine removing/reducing this check.

**Comment by ozangunalp** [comment]
For redpanda image if it contains the rpk binary in the usual place it should be ok. I think we can remove that check for good.

**Comment by fedinskiy** [comment]
@cescoffier in our case, we are trying to circumvent DockerHub download limits, but I can also imagine, that some teams may want to patch their images, eg to use another base distributive.
