### ISSUE TITLE
Solution link is broken

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#23984]
### Describe the bug

The solution is located in the hibernate-orm-panache-kotlin-quickstart [directory](https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-panache-kotlin-quickstart) which is broken in SIMPLIFIED HIBERNATE ORM WITH PANACHE AND KOTLIN guide(https://quarkus.io/guides/hibernate-orm-panache-kotlin)

### Expected behavior

https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-panache-kotlin-quickstart should exist or the guide needs to be modified.

### Actual behavior

The link(https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-panache-kotlin-quickstart) doesn't work.

**Comment by geoand** [comment]
@evanchooly so we don't have a quickstart for Hibernate ORM Panache Kotlin?
If so, please update the docs to remove the `solution` section.

**Comment by glefloch** [comment]
Actually, the quickstart exists but has never been merged https://github.com/quarkusio/quarkus-quickstarts/pull/964.

**Comment by glefloch** [comment]
This quickstart has been merged, the directory will be available as soon as quickstart development branch is merged into main.
