### ISSUE TITLE
Native build image configurations ignored - always falls back to 21.3-java11

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#23988]
### Describe the bug

I'm trying to use the graal jdk17 image unsuccessfully.

What I've tried so far is

1. Gradle DSL

```
quarkusBuild {
    nativeArgs {
        containerBuild = true
        buildImage = "quay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17"
    }
}
```

2. application.properties

```
quarkus.native.build-image=quay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17
```

and running it with the command

> ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true

and also even

> ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.build-image=quay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17

In addition, I've also deleted the docker directory with the images, because I was unsure if those are getting used by the docker extension.

No matter what I do, it always picks up 21.3-java11

```
21.3-java11: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:6d5d0c1fdb58f8ba0a2fb7db58081a16c906450dfb5ff950446766a0f61767fc
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:21.3-java11
quay.io/quarkus/ubi-quarkus-native-image:21.3-java11

```

What am I missing?

### Expected behavior

To not ignore my configurations

**Comment by gsmet** [comment]
It's builder-image not build-image: `-Dquarkus.native.builder-image-...`.

**Comment by mklueh** [comment]
@gsmet oh my god, thank you, this indeed works.

Was it previously "build-image"? Because the documentation here also says so for the Gradle DSL

https://quarkus.io/guides/gradle-tooling#building-a-native-executable


If I change that to **builderImage** as well, it also works.

```
quarkusBuild {
    nativeArgs {
        containerBuild = true
        builderImage = "quay.io/quarkus/ubi-quarkus-native-image:21.3.0-java17"
    }
}
```

**Comment by gsmet** [comment]
Ah, thanks, I created https://github.com/quarkusio/quarkus/pull/24016 to fix it.
