### ISSUE TITLE
Swagger UI don't show in dev mode  from 2.7.0.Final

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#23991]
### Describe the bug

Chrome  console error log:
```log
deburr.js:5 Uncaught SyntaxError: Invalid regular expression: /['鈥橾/: Unterminated character class
    at RegExp (<anonymous>)
    at Object.<anonymous> (deburr.js:5:15)
    at n (bootstrap:19:22)
    at Object.<anonymous> (xml.js:2:5)
    at n (bootstrap:19:22)
    at Object.<anonymous> (swagger-ui-bundle.js:2:59658)
    at Object.<anonymous> (swagger-ui-bundle.js:2:70295)
    at n (bootstrap:19:22)
    at Module.<anonymous> (system.js:34:3)
    at n (bootstrap:19:22)
```

### Expected behavior

Show swagger ui

### Actual behavior

Swagger UI don't Show in dev mode .
it works for  versions prior to 2.7.0.CR1 in dev mode. 

### How to Reproduce?

[openapibug.zip](https://github.com/quarkusio/quarkus/files/8146623/openapibug.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [ 10.0.19043.1165]

### Output of `java -version`

Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)

### Quarkus version or git rev

2.7.2.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by phillip-kruger** [comment]
Hi @yuhaibohotmail - so you are using '鈥橾' in the output somewhere? Do you have a reproducer ?

**Comment by yuhaibohotmail** [comment]
> Hi @yuhaibohotmail - so you are using '鈥橾' in the output somewhere? Do you have a reproducer ?
nothing.
I used "https://code.quarkus.io/" generate  the project.
 
here is a reproducer
[openapibug.zip](https://github.com/quarkusio/quarkus/files/8148401/openapibug.zip)

**Comment by phillip-kruger** [comment]
ok thanks. I'll have a look.

**Comment by phillip-kruger** [comment]
Hi @yuhaibohotmail - i could not recreate this. Your reproducer works fine. Can you share some more details ?
![Peek 2022-02-28 10-41](https://user-images.githubusercontent.com/6836179/155905021-6e9b138d-8971-4900-9158-bb8fd37e6dd6.gif)

**Comment by yuhaibohotmail** [comment]
Hi @phillip-kruger ， This bug only appears on Windows in dev mode, it works fine on MacOS

https://user-images.githubusercontent.com/48646226/155905836-d4f8a3c2-8adb-4ce5-b44d-3f8709995b95.mp4


https://user-images.githubusercontent.com/48646226/155905855-aa21e7e9-daf1-4297-969a-6b23913bd53a.mp4

**Comment by phillip-kruger** [comment]
Ok, I'll see if I can recreate on Windows.

**Comment by yuhaibohotmail** [comment]
I  find  '鈥橾'  in  swagger-ui-bundle.js
![image](https://user-images.githubusercontent.com/48646226/155906763-1995a68d-8921-4a61-b5a0-36576ffef1e2.png)

**Comment by yuhaibohotmail** [comment]
> @phillip-kruger I can't find the issue but someone also complained they had `^A` characters in the UI on Windows (and it was a regression in 2.7, apparently).
> 
> I wonder if it's a charset related issue.
> 
> @yuhaibohotmail what is your locale/charset on Windows?


![image](https://user-images.githubusercontent.com/48646226/156081210-96159fe4-174c-4376-a711-ff1a8f2fb75a.png)

My locale is  zh-CN.
I just tested it work on Microsoft Edge (V98.0.1108.62)  in dev mode，and can not work on firefox(V97.0.1).

**Comment by phillip-kruger** [comment]
Ok, I think this is bigger than openapi and graphql, we might need some help from someone in the vertx-http or similar extension. I have not yet managed to recreate this issue, but I left the locale/charset as default on Windows. I'll try again. @stuartwdouglas @cescoffier - do you have any idea if anything changed ?

**Comment by stuartwdouglas** [comment]
I don't see that character in the file (in smallrye-open-api-ui-2.1.17.jar). I don't really see how this could be a charset issue, this should be served just using the vert.x static file handler, no charset processing should be done.

**Comment by stuartwdouglas** [comment]
In my editor it looks like:

`o=n(434),u=RegExp("['’]","g")` rather than what you are seeing, but the back tick is 'U+2019'

**Comment by phillip-kruger** [comment]
@gsmet - There is no difference between the headers in 2.7.0 and 2.7.2 that I can see.

**Comment by yuhaibohotmail** [comment]
[swagger-ui-bundle.zip](https://github.com/quarkusio/quarkus/files/8158302/swagger-ui-bundle.zip)

This is  the js file I get from chrome 
![image](https://user-images.githubusercontent.com/48646226/156092148-540fea29-78e5-40f9-ab9f-9dc33db63622.png)

**Comment by stuartwdouglas** [comment]
Any idea what your default encoding is?

**Comment by phillip-kruger** [comment]
And you mentioned it works on Edge ? But not on Chrome and Firefox ?

**Comment by stuartwdouglas** [comment]
E.g. what happens if you run: 
`System.out.println(new String("\u2019".getBytes(StandardCharsets.UTF_8)));`

**Comment by stuartwdouglas** [comment]
The browser is interpretting it as either `GBK` or `GB18030`

If you do: `System.out.println(new String("\u2019]".getBytes(StandardCharsets.UTF_8), "GB18030"));` you get `鈥橾`

**Comment by yuhaibohotmail** [comment]
[swagger-ui-bundle.zip](https://github.com/quarkusio/quarkus/files/8158319/swagger-ui-bundle.zip)
This is   js file I get from chrome in  product mode,can not find the character

**Comment by yuhaibohotmail** [comment]
> The browser is interpretting it as either `GBK` or `GB18030`
> 
> If you do: `System.out.println(new String("\u2019]".getBytes(StandardCharsets.UTF_8), "GB18030"));` you get `鈥橾`

yes, I get   `鈥橾`

**Comment by stuartwdouglas** [comment]
What headers do you see in the network tab of chrome?

**Comment by yuhaibohotmail** [comment]
> The browser is interpretting it as either `GBK` or `GB18030`
> 
> If you do: `System.out.println(new String("\u2019]".getBytes(StandardCharsets.UTF_8), "GB18030"));` you get `鈥橾`

 System.out.println(new String("\u2019".getBytes(StandardCharsets.UTF_8)));
    I  get  鈥�

System.out.println(new String("\u2019]".getBytes(StandardCharsets.UTF_8), "GB18030"));
   I  get  鈥橾

**Comment by yuhaibohotmail** [comment]
> And you mentioned it works on Edge ? But not on Chrome and Firefox ?

yes  , it works on Edge in dev mode.

**Comment by stuartwdouglas** [comment]
Linked PR should fix the issue.

**Comment by yuhaibohotmail** [comment]
@stuartwdouglas  Thanks a lot !

**Comment by yuhaibohotmail** [comment]
@stuartwdouglas 
I just tried that fix，it works for me。
