### ISSUE TITLE
gRpc with Mutiny with external proto files does not compile (n.MutinyGrpcGenerator: not found)

### ISSUE THREAD

**Issue by siudeks** [quarkusio/quarkus#23999]
### Describe the bug

I use a few modules to compile gRpc clients with external location of proto files, one module per one set of proto files. It does compilewithout Mutiny support, and it does not compile with Mutiny support.

### Expected behavior

Should be compilable and generate gRpc code with Mutiny plugin

### Actual behavior

It does not compile - PROTOC FAILED (...) n.MutinyGrpcGenerator: not found
Please check details as described in reproduction

### How to Reproduce?

Full reproduction of the bug defined [here](https://github.com/siudeks/tech-spikes/tree/master/bugrepro_grpc_mutiny)

### Output of `uname -a` or `ver`

Linux Home1 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.14 2022-01-18

### Quarkus version or git rev

2.7.2

**Comment by cescoffier** [comment]
You need to package your external proto file in a Maven artifact and declare it as a dependency on your project. Note that you should NOT use the gRPC maven plugin, but only quarkus-grpc.

Once you have declared your dependency, you need to add:

```
quarkus.generate-code.grpc.scan-for-proto=<groupId>:<artifactId>
```

NOTE: This requires Quarkus 2.8 (or 999-SNAPSHOT).

**Comment by siudeks** [comment]
Thx @cescoffier Thx, will retest when 2.8 ver will be available

**Comment by siudeks** [comment]
Closing as I am able to create gRpc files from scanned jars using current version 2.7.3
