### ISSUE TITLE
failed build docker image  with error code 137

### ISSUE THREAD

**Issue by uhdyi** [quarkusio/quarkus#24049]
### Describe the bug

I'm following the tutorial here: https://quarkus.io/guides/building-native-image, and tried to build a docker image, but it failed with 137, searched around and tried all different approach but it didn't work

OS: macOS Catalina 10.15.7

Java: 
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)

command ran:
 ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=16g
./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.native-image-xmx=16g

Error: 
io.quarkus:quarkus-maven-plugin:2.7.2.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code was 137 which indicates an out of memory error. The most likely cause is Docker not being given enough memory. Also consider increasing the Xmx value for native image generation by setting the "quarkus.native.native-image-xmx" property

### Output of `uname -a` or `ver`

Darwin DANs-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM 21.3.1 Java 11 CE

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw: command not found

**Comment by geoand** [comment]
As the error message says, it's likely due to the fact that the Docker VM does not have enough memory.

**Comment by uhdyi** [comment]
then how do I increase the Docker VM memory?

**Comment by geoand** [comment]
See https://docs.docker.com/desktop/mac/#resources
