### ISSUE TITLE
ReactiveRedisClient: Transaction with multi() not working

### ISSUE THREAD

**Issue by dskgry** [quarkusio/quarkus#24056]
### Describe the bug

I'm trying to implement the check-and-set pattern (https://redis.io/topics/transactions#cas) using the ReactiveRedisClient. But commands after the `multi` command do not seem to get `queued`, they're executed directly. When using the blocking version, everything works as expected.

When using the following code, the log output of the reactive endpoint is:
MULTI OK
SET OK
EXEC []

The output of the blocking endpoint is:
MULTI OK
SET QUEUED
EXEC [OK]

Code:

```
import io.quarkus.redis.client.RedisClient;
import io.quarkus.redis.client.reactive.ReactiveRedisClient;
import io.smallrye.mutiny.Uni;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import java.util.List;

@Path("/")
public class ReactiveGreetingResource {
  private final Logger log = LoggerFactory.getLogger(ReactiveGreetingResource.class);

  @Inject
  RedisClient redisClient;

  @Inject
  ReactiveRedisClient reactiveRedisClient;

  @GET
  @Path("/reactive")
  public Uni<String> reactive() {
    return this.reactiveRedisClient
      .multi()
      .flatMap(response -> {
        log.info("MULTI {}", response);
        return this.reactiveRedisClient.set(List.of("a", "b"));
      })
      .flatMap(response -> {
        log.info("SET {}", response);
        return this.reactiveRedisClient.exec();
      })
      .map(response -> {
        log.info("EXEC {}", response);
        return "done";
      });
  }

  @GET
  @Path("/blocking")
  public String blocking() {
    var multi = redisClient.multi();
    log.info("MULTI {}", multi);

    var set = redisClient.set(List.of("a", "b"));
    log.info("SET {}", set);

    var exec = redisClient.exec();
    log.info("EXEC {}", exec);

    return "done";
  }
}

```

### Expected behavior

Logging output of blocking and reactive code should be the same.

### Actual behavior

Logging output of blocking and reactive code is different.

### How to Reproduce?

See the following minimal project:

[redis.zip](https://github.com/quarkusio/quarkus/files/8168663/redis.zip)

### Output of `uname -a` or `ver`

Win

### Output of `java -version`

11

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

**Comment by machi1990** [comment]
@pmlopes would be able to help here. The reactive client delegates calls to the vertx mutiny API and I feel like this is not only the issue with the quarkus reactive client but a general one.

**Comment by cescoffier** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/26268.
