### ISSUE TITLE
Kotlin Hibernate Panache repository methods are listed as untested in JaCoCo code coverage report

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#24074]
### Describe the bug

The JaCoCo code coverage report takes generated/injected methods (eg. `find`, `list`, `delete`) into account using the repository pattern with panache and kotlin. This drags down the the overall coverage.

### Expected behavior

Methods, injected by panache should not be taken into account in the code coverage report.

### How to Reproduce?

I have prepared minimal kotlin and java reproducers. The java reproducer shows, that the expected behaviour works in java. The kotlin reproducer shows the expected behaviour does not work in kotlin.

1. Execute `mvn verify`
2. Check `target/jacoco-report` directory
3. Open `index.html`
4. Verify the functions in repository

[kotlin-panache-jacoco-reproducer.zip](https://github.com/quarkusio/quarkus/files/8177255/kotlin-panache-jacoco-reproducer.zip)
[java-panache-jacoco-reproducer.zip](https://github.com/quarkusio/quarkus/files/8177256/java-panache-jacoco-reproducer.zip)

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### Quarkus version or git rev

2.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment]
It doesn't look like we can do much about this...

The reason this happens is because the Kotlin compiler copies the methods of `PanacheRepositoryBase` into the implementation (I assume because those methods have default implementations). I even tried the various options mentioned [here](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/) but nothing changed.  

This is different from the Java compiler and thus the difference in test coverage

**Comment by jogerj** [comment]
Is it not possible to do it like how [Lombok](https://projectlombok.org/features/configuration) does it? 
> Lombok can be configured to add @lombok.Generated annotations to all generated nodes where possible; useful for JaCoCo (which has built in support), or other style checkers and code coverage tools: 
```
lombok.addLombokGeneratedAnnotation = true
```

The idea being if the config is enabled, it will automatically add the `@Generated` annotation upon compile to bytecode (which JaCoCo ignores)

**Comment by jogerj** [comment]
I used a workaround that looked like this

```kotlin
@ApplicationScoped
class FruitRepository: FruitPanacheRepository() {
    // my own methods
}

@Generated
abstract class FruitPanacheRepository: PanacheRepositoryBase<Fruit, Long>
// or
// abstract class FruitPanacheRepository: PanacheRepository<Fruit>
```

so the inherited methods from Panache in `FruitPanacheRepository` will be ignored by Jacoco while the methods in `FruitRepository` will be counted towards coverage. Hope it helps
