### ISSUE TITLE
Many CVEs related to postgres in the reactive client

### ISSUE THREAD

**Issue by LarsBrenker** [quarkusio/quarkus#24091]
### Describe the bug

We would like to run a project with Quarkus Reactive against a Postgres database and have integrated the OWASP Dependency Check.

This reports a lot of CVEs related to Postgres.

If I see that correctly, this comes from the quarkus-reactive-pg-client, which in turn brings the smallrye-mutiny-vertx-pg-client.

In this context, 36 CVEs related to Postgres are reported to us. And again the same 36 CVEs by vertx-pg-client.

I'm absolutely not sure if I'm even in the right place here.

My question here is how to deal with it. Am I correct in saying that these are the profiles from the vertx project and that Postgres is only used for test purposes? If yes, would it be the right way to suppress these CVEs? It's not a pretty route, but I wanted to at least secure myself beforehand.

Or do you have a better idea?

### Expected behavior

No CVE reports from the Quarkus project

### Actual behavior

Many CVEs related to postgres in the reactive client

![grafik](https://user-images.githubusercontent.com/57911568/156728424-9f0dccb9-b9fd-4f70-b013-ce23c8df9293.png)

### How to Reproduce?

Run the Dependency Check Plugin and view the report in the Target folder

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.xx</groupId>
    <artifactId>quarkus-reactive-pg-cve</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>quarkus-reactive-pg-cve</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>2.7.2.Final</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-pg-client</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>7.0.0</version>
                <configuration>
                    <formats>
                        <format>html</format>
                        <format>json</format>
                    </formats>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by gsmet** [comment]
It's a false positive. Please have a better look at the reports before reporting things like that.

OWASP is somehow considering they are the JDBC PostgreSQL driver in old versions and some www sql thing I don't know, which is not the case.

The pattern matching on the artifact names for this thing is dodgy at best and you need to be extra careful with what it reports.

**Comment by LarsBrenker** [comment]
For me the confirmation that it is false positive was important. Thanks for the feedback.
