### ISSUE TITLE
FindOptions support in mongodb-panache extension

### ISSUE THREAD

**Issue by isnowly** [quarkusio/quarkus#24098]
### Description

Hi, 
The `find()` family of methods in `ReactivePanacheMongoRepositoryBase` does not provide the `FindOptions` parameter. It only has the `Sort` option.

```java
ReactivePanacheQuery<Entity> find(String query, Object... params);
ReactivePanacheQuery<Entity> find(String query, Sort sort, Object... params);
ReactivePanacheQuery<Entity> find(String query, Map<String, Object> params);
ReactivePanacheQuery<Entity> find(String query, Sort sort, Map<String, Object> params);
ReactivePanacheQuery<Entity> find(String query, Parameters params);
ReactivePanacheQuery<Entity> find(String query, Sort sort, Parameters params);
ReactivePanacheQuery<Entity> find(Document query);
ReactivePanacheQuery<Entity> find(Document query, Document sort);
```

I think is it possible to add a method like this:
```java
ReactivePanacheQuery<Entity> find(String query, FindOptions findOptions, Object... params);
ReactivePanacheQuery<Entity> find(String query, FindOptions findOptions, Map<String, Object> params);
ReactivePanacheQuery<Entity> find(String query, FindOptions findOptions, Parameters params);
ReactivePanacheQuery<Entity> find(Document query, FindOptions findOptions);
```

Thanks.

**Comment by loicmathieu** [comment]
There is already a lot of overload on the find() method, but what we can do is to allow adding the find option inside the resulting ReactivePanacheQuery so one may call find("<query>").withOptions(FindOptions).

This is similar to the approach we took on Hibernate ORM with Panache to allow adding locks and hints to a panache query.

**Comment by aomsweet** [comment]
@loicmathieu  Thank you for your reply. 
I see. At first, I just wanted to set the `Limit` parameter in FindOptions. You reminded me that the `page()` method in `ReactivePanacheQuery` can achieve the same effect.

Thanks.

**Comment by aomsweet** [comment]
@loicmathieu Hi,
 I think it is necessary to increase the `FindOptions` parameter. I can't set `batchSize`.

Thanks.

**Comment by loicmathieu** [comment]
@aomsweet `FindOptions` is used internally so we cannot directly allow users to set it.

However, we can support missing options. I can allow setting `batchSize` is there an other option that should also be custimizeable ? We prefere to lower the API surface so we usually choose to expose only what's needed for most use cases.

**Comment by loicmathieu** [comment]
> For me, the big question is how to expose the ability to pass in those options in the API in a way that's not a massive wart.

Wa can add `PanacheQuery.withFindOptions` (and the same for the reactive counterpart) and "merge" the user-supplied with the other options as you suggested.

**Comment by loicmathieu** [comment]
@evanchooly @isnowly `FindOptions` is an internal MongoDB class for the sync so I'm reluctant to allow passing it inside MongoDB with Panache. I know it is a limited solution but I'd rather add the `with<option>()` method for each option that need to be added to the `FindIterable`. See https://github.com/quarkusio/quarkus/pull/30117

The reactive variant do expose a FindOptions wich is a Quarkus class, I can allow passing it in this case but as there is no equivalent on the sync variant I'm not a big fan of it.
