### ISSUE TITLE
Support custom logging handlers

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2409]
It would be great if Quarkus supported registration of custom logging handlers (some frameworks like [Sentry](https://sentry.io) use it as the integration point by registering custom JUL handlers - see an example [here](https://github.com/getsentry/examples/blob/master/java/java.util.logging/src/main/resources/logging.properties))

**Comment by ia3andy** [comment]
@gsmet any update on this? Is there another framework like Sentry to capture errors that I could use with Quarkus?

**Comment by csotiriou** [comment]
+ 1 for this.

I see that JBoss logging is added as a dependency, which (taking example from the Jboss Logging Doc) supports log4j (among others). Maybe we can leverage that someway?

**Comment by ia3andy** [comment]
The Sentry extension will soon be available :)

**Comment by ia3andy** [comment]
https://github.com/quarkusio/quarkus/issues/3985
