### ISSUE TITLE
Quartz configuration misfireThreshold in application.properties file

### ISSUE THREAD

**Issue by smrtyvz** [quarkusio/quarkus#24105]
Not able to conifugrate misfireThreshold value in Quarkus

I am migrating a throntail project to quarkus. Basicly, quartz provide a property such "org.quartz.jobStore.misfireThreshold" (60000ms set as default). I wanted to change this value but couldn't achieved.

When I checked on documentation officialy quarkus is released, I couldn't find any method to change this. 
Also core class QuartzBuildTimeConfig doesn't include this property.

I am still not sure about if we are able to change this property. If thus, can you provide a documentation for this ?

### Implementation ideas

Simply, adding a variable to class QuartzBuildTimeConfig could success this feature.

Such as : 

@ConfigItem(defaultValue = "60000")
public long misfireThreshold;

**Comment by machi1990** [comment]
@VanillaSpoon if you'll be on lookout for new issue after https://github.com/quarkusio/quarkus/pull/24060, this might be a good one too. Let me know if you'll be interested

**Comment by VanillaSpoon** [comment]
Yea, count me in @machi1990. Thanks :)
