### ISSUE TITLE
Spring-DI extension not available for >= 2.7.2.Final

### ISSUE THREAD

**Issue by ertanden** [quarkusio/quarkus#24110]
### Describe the bug

spring-di extension seems to be wrongly uploaded to gradle repo since 2.7.2.Final

https://repo.gradle.org/artifactory/jcenter/io/quarkus/quarkus-spring-di/2.7.3.Final/quarkus-spring-di-2.7.3.Final.jar

It says

{
  "errors": [
    {
      "status": 404,
      "message": "No space left on device"
    }
  ]
}

### Expected behavior

spring-di extension available as dependency

### Actual behavior

spring-di extension not available

### How to Reproduce?

Quarkus 2.7.3.Final with spring-di extension. Can't download spring-di dependency

### Output of `java -version`

11

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by gsmet** [comment]
Given the error message, it looks like an infrastructure problem.

We publish to Maven Central, the rest is not in our hands.
