### ISSUE TITLE
read host and port config from vault

### ISSUE THREAD

**Issue by alinayebi9080** [quarkusio/quarkus#24123]
### Describe the bug

i'm using quarkus 2.7.1 and when use below config to load host and port config from vault, get error
quarkus.http.port=${http.port}
quarkus.http.host=${http.host}

But when i use space in the end of variable problem is fix
quarkus.http.port=${http.port: }
quarkus.http.host=${http.host: }

what's your idea?

**Comment by geoand** [comment]
Closing for lack of feedback
