### ISSUE TITLE
Support GraalVM v. 19.0

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#2412]
Several things changed, making GraalVM 19 currently not compatible with Quarkus.

So far I noticed:
 - [x] `native-image` is no longer included by default. Need to install it by running "gu install native-image" -> adapt documentation, adapt CI, adapt container images.
 - [x] `SubstrateAutoFeatureStep` needs to invoke different methods; e.g. `delayClassInitialization` was renamed to `initializeAtRunTime`
 - [x] Issue https://github.com/oracle/graal/issues/649 was resolved, we need to remove the substitutions for it from class `/core/runtime/src/main/java/io/quarkus/runtime/graal/MethodReplacement.java`.
 - [x] the default strategy to initialize static blocks changed; we should set `--initialize-at-build-time` by default, but also verify how this interactos with other flags we're setting.

There are certainly some more issues, to be investigated.

**Comment by rsvoboda** [comment]
> native-image is no longer included by default

It's true for Linux and macOS distribution.

graalvm-ce-19.0.0 for Windows contains native-image, on the other hand there is no "gu".

This may change in the future releases, but for now Windows + GraalVM are special (GraalVM has Early Adopter Windows Support atm)

**Comment by dmlloyd** [comment]
Maybe we want a dedicated project board and separate issues for each GraalVM 19 issue?

**Comment by emmanuelbernard** [comment]
Hey @dmlloyd, can you tell the status on this. I’m a little but in the dark.

**Comment by dmlloyd** [comment]
The best place to look would be the GraalVM 19 board: https://github.com/quarkusio/quarkus/projects/8

However right now we're stuck on https://github.com/oracle/graal/issues/1183.  I'm waiting for a GraalVM branch to test with.

**Comment by dmlloyd** [comment]
We've gotten past oracle/graal#1183, now we're stuck on oracle/graal#1320.

**Comment by n1hility** [comment]
Blocker list: https://github.com/quarkusio/quarkus/issues/2792
