### ISSUE TITLE
Dependency order in pom.xml - NPE during headers writing

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#24120]
### Describe the bug

Declaring `dependencies` in this order
```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-rest-client-jackson</artifactId>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>		
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy-reactive</artifactId>
</dependency>
```
will make this code
```
@GET
@Path("")
@Produces(MediaType.TEXT_PLAIN)
public Response test(@QueryParam("value") @DefaultValue("0") Number headerValue) {
  return Response.ok().entity("ok").header("numeric-header", headerValue).build();
}
```
to fail with this stacktrace
```
ERROR: Request failed
java.lang.NullPointerException
	at org.jboss.resteasy.reactive.common.headers.HeaderUtil.headerToString(HeaderUtil.java:44)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.encodeResponseHeaders(ServerSerialisers.java:493)

```

### Expected behavior

Everything should works fine regardless dependencies order

### Actual behavior

```
ERROR: Request failed
java.lang.NullPointerException
	at org.jboss.resteasy.reactive.common.headers.HeaderUtil.headerToString(HeaderUtil.java:44)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.encodeResponseHeaders(ServerSerialisers.java:493)

```

### How to Reproduce?

Link to reproducer: https://github.com/luca-bassoricci/dependency-order-problem
`mvn test` to run test

### Output of `uname -a` or `ver`

Microsoft Windows [Versione 10.0.19044.1469]

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14 LTS

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

Non-reactive version works fine.
Moving
```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-rest-client-jackson</artifactId>
</dependency>
```
after ALL reactive dependencies solve the problem.

**Comment by gsmet** [comment]
Given how old this issue is, it's probably not exactly the same problem.

Please open a new issue with a small reproducer.
