### ISSUE TITLE
Including quarkus-apicurio-registry-avro pollutes the OpenAPI / Swagger UI with non-working endpoints and data types

### ISSUE THREAD

**Issue by lw-mcno** [quarkusio/quarkus#24146]
### Describe the bug

Including the quarkus-apicurio-registry-avro dependency (for schema registry dev services), pollutes the service's Swagger UI and OpenAPI with non-working (404) endpoints from the Apicurio registry. This happens both in dev mode and when the service is deployed to a non-dev stage.

### Expected behavior

No Apicurio API definitions should be added to the service's API.

### Actual behavior

The service-defined API and Apicurio's non-woking API are presented in the API UI / endpoint.

### How to Reproduce?

1. Include the quarkus-apicurio-registry-avro dependency in the service
2. Go to the Swagger UI or call /openapi

### Output of `java -version`

17

### Quarkus version or git rev

2.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by phillip-kruger** [comment]
I'll have a look. Thanks :)

**Comment by phillip-kruger** [comment]
As a workaround you can add `quarkus.smallrye-openapi.ignore-static-document=true` in your config. I'll do a PR with a proper fix soon

**Comment by lw-mcno** [comment]
That was fast, thanks :)
