### ISSUE TITLE
Reactive Hibernate batch inserts (and updates)

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#24140]
### Description

Hi, Dear Quarkus community

At present, when reactive hibernate call `persist (list)`, I know from the SQL log printed by hibernate that it executes one insert after another. However, hibernate can support `batch` insert. I think this is very important. Such important parameters should not be omitted.
@see https://github.com/hibernate/hibernate-reactive/issues/257, https://github.com/hibernate/hibernate-reactive/pull/312

**Comment by DavideD** [comment]
Hibernate disable batching when the entity id is mapped as IDENTITY. The documentation mentions it but there is an explanation on SO:  https://stackoverflow.com/questions/27697810/why-does-hibernate-disable-insert-batching-when-using-an-identity-identifier-gen

I suspect this is the reason it wasn't working.

**Comment by DavideD** [comment]
I'm going to close this for now unless somebody provides a testcase.
