### ISSUE TITLE
WorkerInterceptor not invoked for methods returning a Multi

### ISSUE THREAD

**Issue by danielbobbert** [quarkusio/quarkus#24160]
### Describe the bug

When defining a JAX-RS WriterInterceptor with quarkus-resteasy-reactive, the WriterInterceptor is only invoked for blocking methods and those returning a Uni<?>, but not for methods returning a Multi<?>.

### Expected behavior

The WriterInterceptor should be invoked for all methods, including those returning a Multi<?>

### Actual behavior

WriterInterceptor is only invoked for blocking methods and those returning a Uni<?>, but not for methods returning a Multi<?>.

### How to Reproduce?

See attached sample app

### Output of `uname -a` or `ver`

Mac OS 12.2.1, arm64

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM (build 11.0.14+9-LTS, mixed mode)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by danielbobbert** [comment]
Attached is a small sample app that reproduces the issue.
[writer-interceptor-test.zip](https://github.com/quarkusio/quarkus/files/8204090/writer-interceptor-test.zip)

**Comment by geoand** [comment]
Actually, this is something we deliberately have avoided, because returning `Multi` is a very special case.
