### ISSUE TITLE
Quarkus CLI adding extension fails with white space

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#24161]
### Describe the bug

Quarkus CLI adding extension fails when the extension name has a white space:

```
quarkus create app org.acme:movie-plays-consumer \
    --extension=kafka, jackson \
    --no-code
```

### Expected behavior

It should add the extensions

### Actual behavior

Gets an exception:

```
quarkus create app org.acme:movie-plays-consumer \
    --extension=kafka, jackson \
    --no-code
[ERROR] ❗  Unable to create project: Unmatched argument at index 4: 'jackson'
```

### How to Reproduce?

quarkus create app org.acme:movie-plays-consumer \
    --extension=kafka, jackson \
    --no-code

### Quarkus version or git rev

Quarkus CLI version 2.7.2.Final

**Comment by gsmet** [comment]
Well, either escape the space or use quotes. That's how command line shells work, there's nothing we can do about it.

Both the following commands will work:
```
quarkus create app org.acme:movie-plays-consumer \
    --extension='kafka, jackson' \
    --no-code
```
```
quarkus create app org.acme:movie-plays-consumer \
    --extension=kafka,\ jackson \
    --no-code
```

**Comment by ebullient** [comment]
This should also work:
```
quarkus create app org.acme:movie-plays-consumer \
    --extension=kafka \
    --extension=jackson \
    --no-code
```
