### ISSUE TITLE
Put AWSRequestId into logger MDC for quarkus-amazon-lambda

### ISSUE THREAD

**Issue by Temdegon** [quarkusio/quarkus#24192]
### Description

Currently there is no out-of-the-box way to include AWSRequestId into log records.
There is com.amazonaws:aws-lambda-java-log4j2 library which does that, but it's is not very quarkus-friendly (at least last time I've tried it).
Of course developer could do MDC.put("AWSRequestId", context.getAwsRequestId()) in RequestHandler, but would be nice to have this working without additional code. And also it's not very clear how to do this for quarkus-amazon-lambda-http + quarkus-resteasy.

**Comment by einarjohnson** [comment]
@Temdegon , did you encounter any JSON log formatting issues when running your lambdas as a container? I am battling this issue here https://github.com/quarkusio/quarkus/issues/26816 and I am wondering if including the `com.amazonaws:aws-lambda-java-log4j2` library might resolve this issue.

**Comment by L154x** [comment]
Hi, I would like to open this issue again.
I just tried to use this in conjunction with the [quarkus logging json lib](https://github.com/quarkiverse/quarkus-logging-json) and seem to have encountered a bug.

When running `quarkusDev`, I can see the AWSRequestID in the logs just fine, having set the below in my application.properties
```
log.json.log-format: ecs
log.json.fields.mdc.enabled: true
```
Then the output is as you would expect the following:
```
{
   "@timestamp":"2024-01-31T16:54:41.586+01:00",
   "mdc":{
      "AWSRequestId":"213076a7-7f56-4eb0-9d98-6ec6433cd072",
      "testing":"32",
   },
   "message":"S3EventHandler called.",
   "ecs.version":"1.12.1",
   "log":{
      "level":"INFO",
      "logger":"org.apache.logging.log4j.spi.AbstractLogger"
   },
   "process":{
      "thread":{
         "name":"Lambda Thread (DEVELOPMENT)"
      }
   }
}
```

However, when I then deploy this to lambda, the AWSRequestId as part of the mdc map is no longer printed!
```
{
    "@timestamp": "2024-01-31T15:09:24.222Z",
    "mdc": {
        "testing": "1528622651"
    },
    "message": "S3EventHandler called.",
    "ecs.version": "1.12.1",
    "log": {
        "level": "INFO",
        "logger": "org.apache.logging.log4j.spi.AbstractLogger"
    },
    "process": {
        "thread": {
            "name": "main"
        }
    }
}
```

Note the "testing" field, which I manually added via MDC.put("testing", someHash). This is curiously kept across both deployed versions.

I'm wondering, do you have any idea why the AwsRequestId is showing with "quarkusDev" but not when run after a prod-build?

**Comment by Temdegon** [comment]
Really, somehow it doesn't work on real environment. I'll try to fix it

**Comment by Temdegon** [comment]
@patriot1burke could you please reopen this issue?
