### ISSUE TITLE
Allow to register JAX-RS endpoints generated by extensions

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#2419]
Currently when Quarkus extension produces JAX-RS resource it is not registered by the RESTEasy extension as it does not take into account anything else that the source of the project.

This issues aims at providing a BuildItem to allow to register JAX-RS resources produced by extensions.

**Comment by sberyozkin** [comment]
+1. That would be nice.

**Comment by dyutiman** [comment]
This issue is solved for quarkus-resteasy, but not working for quarkus-resteasy-reactive or quarkus-resteasy-reactive-jackson. How can we make it work for other reseasy modules?
