### ISSUE TITLE
OOM with QuarkusTestResourceConfigurableLifecycleManager

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#24210]
### Describe the bug

I replaced our wiremock integration tests with a QuarkusTestResourceLifecycleManager approach. Instead of starting und stopping the wiremock server in the junit `BeforeAll` and `AfterAll` methods, I provide a class the looks like the following:
```kotlin 
class WiremockServerTestResource: QuarkusTestResourceConfigurableLifecycleManager<WithWiremockedRemoteApis> {
    val server = WireMockServer(WireMockConfiguration.options().dynamicPort())
    val name = AtomicReference<String>()

    override fun init(annotation: WithWiremockedRemoteApis) {
        name.set(annotation.name)
    }

    override fun start(): MutableMap<String, String> {
        val mappingSource = JsonFileMappingsSource(ClasspathFileSource("wiremock"))
        mappingSource.loadMappingsInto(InMemoryStubMappings())

        server.loadMappingsUsing(mappingSource)
        server.start()

        return mutableMapOf(
            "org.acme.UserClient/mp-rest/url" to server.baseUrl()
        )
    }

    @Synchronized
    override fun stop() {
        server.stop()
    }
}


@QuarkusTestResource(WiremockServerTestResourceSlow::class)
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.CLASS)
annotation class WithWiremockedRemoteApis(
    val name: String = "Frufru"
)
```

I annotated all integration tests with `@WithWiremockedRemoteApis` and basically this approach looks pretty charming.  My problem is though, that my tests ran into an OOM with this approach. On my local macbook this does not happen all the time but on our gitlab runners (with lower resources), the tests do not work at all and fail with an OOM.

I also created a sample project that at least shows, that this approach is much slower than the static initialisation: https://github.com/u6f6o/slow_tests I could not reproduce the OOM though :( I think there might be an issue with the QuarkusTestResourceConfigurableLifecycleManager as the tests, even for this simple project are much slower in the test setup phase:
![image](https://user-images.githubusercontent.com/1176370/157493897-18b129d6-1eed-4c4c-ad20-335c3d3adf61.png)

### Expected behavior

Tests should be almost as fast as with static wiremock initialisation and should not run in to an OOM. 

### How to Reproduce?

1.) Check out https://github.com/u6f6o/slow_tests 
2.) Run tests in org.acme.static 
3.) Run tests in org.acme.quarkuslifecycle 
4.) Compare results (OOM does not occur in this example though)

**Comment by famod** [comment]
The thing is that as soon as you add `@QuarkusTestResource` to another annotation (a stereotype), then this resource is treated as if `restrictToAnnotatedClass` was set to `true`.
So, each of your annotated test classes will start and stop the wiremock server, instead of starting one server once and keeping it up until the last test class is done.
I cannot say I like this behaviour, but this is just how it works currently. There is a hint here: https://quarkus.io/guides/getting-started-testing#annotation-based-test-resources
> For example, this defines the @WithKubernetesTestServer annotation, which you can use on your tests to activate the KubernetesServerTestResource, **but only for the annotated test class.**

I _all_ you tests need that resource, you're better of adding that `@QuarkusTestResource` _once_ to some class, e.g. `ModuleWideTestResources` or so. It will be picked up automatically.
If you need more flexibility then I'd suggest `@TestProfile`.

As for the OOM, there might a leak due to the number of wiremock servers that might still be around, but we'd need a memory dump to check that.

/cc @geoand

**Comment by u6f6o** [comment]
> The thing is that as soon as you add @QuarkusTestResource to another annotation (a stereotype), then this resource is treated as if restrictToAnnotatedClass was set to true.
So, each of your annotated test classes will start and stop the wiremock server, instead of starting one server once and keeping it up until the last test class is done.
I cannot say I like this behaviour, but this is just how it works currently. 

Okay, but if I am not missing sth., that's the same with the static initialisers I provided in my sample project? Every test class starts and stops its own wiremock server. The intention in using `QuarkusTestResourceConfigurableLifecycleManager` was specifically to provide certain parameters per test clazz via annotation that have influence on the wiremock setup. In my real life service, I use this annotation to provide an alternative location to the stub mappings for the wiremock server. 

Thus the "limitation" that a wiremock server is started/stopped for every test clazz that is annoated is fine for me, it just takes much longer than using the static initialisers and results in an OOM in my real life service.

**Comment by geoand** [comment]
Thanks for reporting.

As @famod mentions, a memory dump will go a long way to figuring out the OOM error

**Comment by geoand** [comment]
> I cannot say I like this behaviour, but this is just how it works currently. There is a hint here: https://quarkus.io/guides/getting-started-testing#annotation-based-test-resources

I agree, it's a bad default but it's legacy carried from pre-Quarkus 1.7, where test profiles did not exist.

**Comment by famod** [comment]
> Okay, but if I am not missing sth., that's the same with the static initialisers I provided in my sample project? Every test class starts and stops its own wiremock server.

Ok, but with a LifecycleManager that is used via such a stereotype, there will also be a **Quarkus restart** for each test class.
Can you verify this?

**Comment by u6f6o** [comment]
> > Okay, but if I am not missing sth., that's the same with the static initialisers I provided in my sample project? Every test class starts and stops its own wiremock server.
> 
> Ok, but with a LifecycleManager that is used via such a stereotype, there will also be a **Quarkus restart** for each test class. Can you verify this?

Yes, it's the same as with the static approach. For every annotated test clazz, the start method is invoked before the test methods are invoked. After all test methods were executed in the given clazz, the stop method is invoiked.

**Comment by u6f6o** [comment]
> Thanks for reporting.
> 
> As @famod mentions, a memory dump will go a long way to figuring out the OOM error

Creating a heap dump is no problem but for the real life service, this dump may also contain sensitive data and I think I am not allowed to share the dump. Have to figure out if there is any way to obfuscate the data etc. 

In the meantime here is a screenshot of the leak suspects that MAT found: 
![image](https://user-images.githubusercontent.com/1176370/157657577-869f5e94-4ea3-44e2-8c92-ac5c758283ed.png)
![image](https://user-images.githubusercontent.com/1176370/157657647-63906d3f-3878-4c75-bdb4-474aca93c688.png)

**Comment by famod** [comment]
> Yes, it's the same as with the static approach. For every annotated test clazz, the start method is invoked before the test methods are invoked. After all test methods were executed in the given clazz, the stop method is invoiked.

Right, but what I meant is that with your static approach there should be *no* _Quarkus_ restarts, but with that `@WithWiremockedRemoteApis` there _will_ be _Quarkus_ restarts.
I'm really talking about _Quarkus_, not Wiremock!

This explains the runtime penalty and probably also the OOMs (in case something is not clean up during those _Quarkus_ restarts).

**Comment by u6f6o** [comment]
ah, sorry, missed that point. 👍

**Comment by u6f6o** [comment]
okay, I think you are right. I realised that the heap dump contains quite some QuarkusClassLoader objects. This is not the case for the static approach: 
![image](https://user-images.githubusercontent.com/1176370/157670150-1d204ee1-966c-4a0b-bb2f-2797503f1597.png)
As a next step, I added some big players in my build.gradle (lib-wise) in order to further blow up the QuarkusClassLoader. This caused the tests using the QuarkusTestResourceConfigurableLifecycleManager approach to fail with an OOM, even in my sample project.

**Comment by famod** [comment]
@geoand
When there is a profile change or resources need to be reloaded, we are closing the `ExtensionState`:
https://github.com/quarkusio/quarkus/blob/2.7.4.Final/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L600
During that `close()`, `runningQuarkusApplication` is set to null, but I don't see that we are closing it?
https://github.com/quarkusio/quarkus/blob/2.7.4.Final/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L1242

**Comment by geoand** [comment]
I'll have to devote some time to chase down what looks like a ClassLoader leak

**Comment by geoand** [comment]
There seems to be some deep leak in JMX that I don't see how we can work around.
The good news is though that if you exclude the micrometer extension, the OOM in the tests goes away.
So I am going to close this as there isn't much we can do on our side

**Comment by u6f6o** [comment]
By excluding you mean, removing the micrometer dependency as a whole?

**Comment by geoand** [comment]
For tests, yes

**Comment by u6f6o** [comment]
So theoretically, the micrometer team could "fix" this issue by delivering jmx support only with a separate dependency, like for example `io.micrometer:micrometer-registry-jmx`?

**Comment by geoand** [comment]
I can't comment on that since I don't know anything about micrometer internals.

FWIW, the problem seems to come from `io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$GcMetricsNotificationListener`

**Comment by u6f6o** [comment]
just for the protocol: The OOM only occurs only with `QuarkusTestResourceConfigurableLifecycleManager`. I adapted my tests and used `QuarkusTestResourceLifecycleManager` solely and the OOM vanished.
