### ISSUE TITLE
Simplified @PathParam usage is available only if project uses RESTEasy Reactive

### ISSUE THREAD

**Issue by dtsaryov** [quarkusio/quarkus#24235]
### Describe the bug

There was a [demo](https://www.youtube.com/watch?v=DCEJSBgA0T8&t=1217s) describing simplified usage of `@PathParam` when it can be omitted:

```java
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/")
public class GreetingResource {

    @Path("{name}")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(String name) {
        return "Hello " + name;
    }
}
```

But this feature is not available for a "default imperative" project.

### Output of `java -version`

OpenJDK 11

### Quarkus version or git rev

2.7.4

**Comment by geoand** [comment]
Yup, this is something that is available to RESTEasy Reactive only.

**Comment by dtsaryov** [comment]
@geoand thanks for the answer!

**Comment by geoand** [comment]
YW
