### ISSUE TITLE
Write a RESTEasy Classic -> Reactive migration guide

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#24239]
We need to collect all the most common use cases and document them.

We should also document the limitations (typically the lack of GZip support if we don't have it by then).

https://github.com/quarkusio/quarkus-quickstarts/pull/971 is a good start for that.

**Comment by geoand** [comment]
I assume this will be a standalone doc, correct?
Where will be linked from?

**Comment by geoand** [comment]
I opened https://github.com/quarkusio/quarkus/pull/24411 to start addressing this.
