### ISSUE TITLE
LDAP response read timed out, timeout used: 5000 ms.

### ISSUE THREAD

**Issue by bdepaz80** [quarkusio/quarkus#24242]
Hey, 
We're using quarkus quarkus-elytron-security-ldap 2.6.1.Final in combination with Oracle LDAP. During security authentication we get "LDAP response read timed out, timeout used: 5000 ms.".

The problem is most probably related to performance issue in our LDAP setup, but that is something we can't change just like that. 
However, it would be nice if there was a possibility to override the default connect and timeout properties that are being used. For example by providing system properties: 

-Dcom.sun.jndi.ldap.connect.timeout=60000 
-Dcom.sun.jndi.ldap.read.timeout=8000

Are there any other options to tune ldap connection with elytron? Any other idea's on this? 

Already thanks!

Ref : 
https://github.com/quarkusio/quarkus/blob/2.7/extensions/elytron-security-ldap/runtime/src/main/java/io/quarkus/elytron/security/ldap/QuarkusDirContextFactory.java

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/24245 will give you the necessary configuration knobs
