### ISSUE TITLE
Define how extensions are hosted and listed

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2425]

**Comment by Dufgui** [comment]
Hello, just a little interesting input, I don't i you know it, but jhipster handle it, by keyword on npm registry and use the npm registry api:
https://www.npmjs.com/search?q=keywords:jhipster-module

Maven repo api/pom reference not provide keyword  notion but we can use artifactid suffix like maven-plugin for exemple. 

Hope my input help a little
Bye

**Comment by gsmet** [comment]
I think this is well under way with the platform effort. We don't need an issue for that.
