### ISSUE TITLE
Allow to configure Quartz misfire handling strategy globally that will be applied to all @Scheduled methods

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#24254]
### Description

At the moment we rely on the default strategy. 
It will be useful to define all the supported strategies by quartz and define and expose them as `quarkus.quartz.misfire-strategy`. 

### Implementation ideas

Ddefine all the supported strategies by quartz and define and enum type out of them. 
Then we can expose as a quartz runtime configuration `quarkus.quartz.misfire-strategy`, which defaults to the current Quartz default. 
- The configuration will reside in `QuartzRuntimeConfig`

**Comment by machi1990** [comment]
Follow up work on https://github.com/quarkusio/quarkus/issues/24105

**Comment by rmanibus** [comment]
Hi @machi1990, do you mind if I work on a PR for this ?

**Comment by rmanibus** [comment]
as misfire instructions are different in CronScheduleBuilder and SimpleScheduleBuilder, do we need 2 strategies in the config ?
```quarkus.quartz.cron-misfire-strategy``` and ```quarkus.quartz.simple-misfire-strategy``` ?

**Comment by machi1990** [comment]
> Hi @machi1990, do you mind if I work on a PR for this ?

Thank you. Consider the issue yours.

> as misfire instructions are different in CronScheduleBuilder and SimpleScheduleBuilder, do we need 2 strategies in the config ? `quarkus.quartz.cron-misfire-strategy` and `quarkus.quartz.simple-misfire-strategy` ?

+1 that will work too but I think it will increase the surface of the configuration knobs. 
An alternative will be to allow configuring it on per scheduler using the scheduled job identity. 
`quarkus.quartz."<identity>".misfire-strategy=the given strategy`. The config item will be a map. 
The enum will contain all the strategies, with the prefix indicating if it is a `CRON_TRIGGER_MISFIRE_XXX` or `SIMPLE_TRIGGER_MISFIRE_XXX` .
If a scheduler is not defined in the map, we'll default to using the default upstream one. The advantage with this approach we'll be customizing it on per scheduled and not globally which is something a user will likely want to do. 
PS: it is shifting away from the issue title but I'll like to know what you think of the proposal before editing the issue title.
/cc @mkouba

**Comment by rmanibus** [comment]
So I have
```
    public enum QuartzMisfirePolicy {
        MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY,
        MISFIRE_INSTRUCTION_SMART_POLICY,
        SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW,
        SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT,
        SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT,
        SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT,
        SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT,
        CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW,
        CRON_TRIGGER_MISFIRE_INSTRUCTION_DO_NOTHING
    }
```
Can we simplify ```SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW``` and ```CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW``` with a single MISFIRE_INSTRUCTION_FIRE_NOW ?

**Comment by machi1990** [comment]
> So I have
> 
> ```java
>     public enum QuartzMisfirePolicy {
>         MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY,
>         MISFIRE_INSTRUCTION_SMART_POLICY,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT,
>         CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW,
>         CRON_TRIGGER_MISFIRE_INSTRUCTION_DO_NOTHING
>     }
> ```
> 
> Can we simplify `SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW` and `CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW` with a single `MISFIRE_INSTRUCTION_FIRE_NOW` ?

+1, that's much better.

**Comment by machi1990** [comment]
> So I have
> 
> ```java
>     public enum QuartzMisfirePolicy {
>         MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY,
>         MISFIRE_INSTRUCTION_SMART_POLICY,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT,
>         SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT,
>         CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW,
>         CRON_TRIGGER_MISFIRE_INSTRUCTION_DO_NOTHING
>     }
> ```
> 
> Can we simplify `SIMPLE_TRIGGER_MISFIRE_INSTRUCTION_FIRE_NOW` and `CRON_TRIGGER_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW` with a single `MISFIRE_INSTRUCTION_FIRE_NOW` ?

I am wondering if we could drop the _MISIRE_INSTRUCTION_ 
```java
public enum QuartzMisfirePolicy {
        IGNORE_MISFIRE_POLICY,
        SMART_POLICY,
        FIRE_NOW,
        SIMPLE_TRIGGER_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT,
        SIMPLE_TRIGGER_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT,
        SIMPLE_TRIGGER_RESCHEDULE_NEXT_WITH_REMAINING_COUNT,
        SIMPLE_TRIGGER_RESCHEDULE_NEXT_WITH_EXISTING_COUNT,
        CRON_TRIGGER_DO_NOTHING
    }
```

what do you think? @rmanibus 
Also I am not so sure if `CRON_TRIGGER_DO_NOTHING` is the same as `IGNORE_MISFIRE_POLICY` under the hood. If so, we could combine the two into `DO_NOTHING`.

**Comment by rmanibus** [comment]
Yes it's more readable like this. the CRON_TRIGGER_DO_NOTHING  and IGNORE_MISFIRE_POLICY  are not identical under the hood:
```java
        if(instr == Trigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY)
            return;
```
and
```java
        if (instr == MISFIRE_INSTRUCTION_DO_NOTHING) {
            Date newFireTime = getFireTimeAfter(new Date());
            while (newFireTime != null && cal != null
                    && !cal.isTimeIncluded(newFireTime.getTime())) {
                newFireTime = getFireTimeAfter(newFireTime);
            }
            setNextFireTime(newFireTime);
        }
```
