### ISSUE TITLE
JBoss Threads version logging in tests

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#24283]
I'm trying to write `@QuarkusMainTest` tests and the output is hard to test because I end up with:
```
2022-03-13 12:27:52,367 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
```
in it.

I saw it for other tests too but it's especially annoying when dealing with command mode tests as you can't test the output properly.

@famod I believe this is due to the change you made to initialize the loggers earlier in the tests. @geoand worked around it by adding a specific test in the mojo and Gradle logger but it doesn't work for all cases and I think we need a more general fix.

**Comment by gsmet** [comment]
@famod any chance you could have a look at this one?

You can reproduce it easily with the tests in: https://github.com/quarkiverse/quarkus-github-action/ .

They are passing now because I use `contains()` instead.

**Comment by famod** [comment]
@gsmet I'm probably missing something, but adding a `src/test/resources/application.properties` with:
```
quarkus.log.category."org.jboss.threads".level=WARN
```
makes those log statements go away.

Are you looking for something more convenient?

**Comment by famod** [comment]
PS: When checking for multiple lines like in `IssueOpenedActionTest`, you'll need contains anyway, no?
But I agree that JBoss Threads output is annoying.

**Comment by gsmet** [comment]
@famod any comment on that? I would prefer we do not ship 2.8 with this.

**Comment by famod** [comment]
Sorry, I must have missed your previous message.

A very straight foward hack would be:
- either set system property `quarkus.log.category."org.jboss.threads".level=WARN` in `static` initializer of `BasicLoggingEnabler`
- or try to modify the logger after the actual activation in `BasicLoggingEnabler`

There is a clean, general switch in the works for various libs, right? Or was that just an idea which never came to pass?

> I would prefer we do not ship 2.8 with this.

I think this should even be backported to 2.7.

**Comment by gsmet** [comment]
> There is a clean, general switch in the works for various libs, right? Or was that just an idea which never came to pass?

In the end, the native issue was fixed another way. But I wonder if we should do it anyway given this issue.

Anyway, we need a quick fix.

> either set system property quarkus.log.category."org.jboss.threads".level=WARN in static initializer of BasicLoggingEnabler

But are the logging categories taken into account at this point? Because the issue is that the filters are not?
In any case, if we change the category, we probably need to restore it at some point.

**Comment by famod** [comment]
> But are the logging categories taken into account at this point? Because the issue is that the filters are not?

Everything that's in `application.properties` (and other "standard" config sources) will be picked up (since 2.7.2; #23628 & #23652).
As those filters are not set via those config sources, they are not picked up.

**Comment by gsmet** [comment]
They are provided via the `LogCleanupFilterBuildItem` and pushed via `RunTimeConfigurationDefaultBuildItem`. I have no idea if it's good enough.
But it looks like these are consumed in other ways too.

TBH, I don't mind exactly how we do it, we just need to fix that. If we have to hardcode this particular ignore rule somewhere, it's no biggie.

**Comment by famod** [comment]
Turns out that this message starts appearing _before_ I even added `BasicLoggingEnabler`, more specifically since #22455!
I noticed that because I'm _unable_ to get rid of all such messages when I set `quarkus.log.category."org.jboss.threads".level=WARN` just in `BasicLoggingEnabler` _and restore/remove it as soon as logging setup is done_.
I have to leave it set instead...which is not ideal.

I'm trying to make sense of it...

/cc @geoand

**Comment by famod** [comment]
PS: `-Djunit.quarkus.enable-basic-logging=false` can be used to switch off `BasicLoggingEnabler`, but the message is still there.
Actually it's two messages. One vanishes when switching off the enabler or setting/resetting the sysprop in it.

**Comment by famod** [comment]
@geoand as I won't have time for this today, can you revisit the changes from #22455?

As mentioned previously, the message pop up (and is captured) since then.
The setup from `BasicLoggignEnabler` "only" results in an additional message (which I find irritating, but I know little about `QuarkusMainTest`), but that one isn't captured and is thus not the main isue here.

**Comment by geoand** [comment]
I'll try and have a look

**Comment by gsmet** [comment]
What bugs me is that we somehow need to understand why these are logged. My understanding is that we shouldn't initialize the logging layer without the proper config in place.
This is a bugfix so it can be included post-CR1.
