### ISSUE TITLE
LookUpIfProperty not working in Kotlin

### ISSUE THREAD

**Issue by nachogon1** [quarkusio/quarkus#24286]
### Describe the bug

I am working with quarkus in Kotlin. I would like to use LookupIfProperty. Following the quarkus documentation, this is the equivalent in Kotlin.
```Kotlin
import io.quarkus.arc.lookup.LookupIfProperty
import io.quarkus.runtime.QuarkusApplication
import io.quarkus.runtime.annotations.QuarkusMain
import javax.enterprise.context.ApplicationScoped
import javax.inject.Inject


interface Service {
    fun name(): String
}

@LookupIfProperty(name = "task", stringValue = "scheduler")
@ApplicationScoped
class ServiceBar: Service {
    override fun name(): String {
        return "bar"
    }
}
@ApplicationScoped
class ServiceFoo : Service {
    override fun name(): String {
        return "foo"
    }
}

@ApplicationScoped
class Client {

    @Inject
    lateinit var service: Service
    fun printServiceName() {
        // This would print "bar" if the property of name "service.foo.enabled" was set to false
        // Note that service.get() would normally result in AmbiguousResolutionException
        println(service.name())
    }
}

@QuarkusMain
class Main : QuarkusApplication {
    @Inject
    lateinit var client: Client

    override fun run(vararg args: String?): Int {
        println("Started")
        println(client.printServiceName())
        return 0
    }
}
```

### Expected behavior

```
Started
bar
```

### Actual behavior

```Kotlin
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type Service and qualifiers [@Default]
        - java member: Client#service
        - declared on CLASS bean [types=[Client, java.lang.Object], qualifiers=[@Default, @Any], target=Client]
        - available beans:
                - CLASS bean [types=[ServiceFoo, Service, java.lang.Object], qualifiers=[@Default, @Any], target=ServiceFoo]
                - CLASS bean [types=[ServiceBar, Service, java.lang.Object], qualifiers=[@Default, @Any], target=ServiceBar]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1202)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:272)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:134)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:462)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type Service and qualifiers [@Default]
        - java member: Client#service
        - declared on CLASS bean [types=[Client, java.lang.Object], qualifiers=[@Default, @Any], target=Client]
        - available beans:
                - CLASS bean [types=[ServiceFoo, Service, java.lang.Object], qualifiers=[@Default, @Any], target=ServiceFoo]
                - CLASS bean [types=[ServiceBar, Service, java.lang.Object], qualifiers=[@Default, @Any], target=ServiceBar]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:437)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:524)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:260)
        ... 13 more
```

### How to Reproduce?

Steps to reproduce the behaviour:
1. `./gradlew build`

### Output of `uname -a` or `ver`

Darwin Ignacios-MBP 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

11.0.12

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

I have a standard quarkus folder structure.
In my `application.yml` I have:
`task: scheduler`

In my `gradle.properties` I have:
```
#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=2.7.2.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=2.7.2.Final
awsSdk2Version=2.17.69
```

In my `build.gradle.kts` I have:
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
    id("io.quarkus")
}

repositories {
    mavenCentral()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))
// Quarkus
    implementation("io.quarkus:quarkus-kotlin:$quarkusPlatformVersion")
    implementation("io.quarkus:quarkus-arc:$quarkusPlatformVersion")

// Kotlin
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}


tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    kotlinOptions.javaParameters = true
}
```

**Comment by gsmet** [comment]
Is it working in Java?

My guess is that you need to annotate the other one with `@LookupUnlessProperty`. Or maybe `@DefaultBean` would work?

@mkouba I think the example in https://quarkus.io/guides/cdi-reference#declaratively-choose-beans-that-can-be-obtained-by-programmatic-lookup is a bit misleading. Couldn't we make it work instead of explaining why it fails in a comment?

**Comment by nachogon1** [comment]
I tried in Java and it did work. Anyway, It would be nice to indicate the imports somewhere since I imported `Instance` from `io.quarkus.arc.runtime.BeanContainer.Instance` and I was getting the same error as above (It took me a while to realize the mistake).

I found my error I forgot `Instance` when injecting the service (And the client). So injecting the service should look like this (the same when injecting `Client` ): 
```Kotlin
@Inject
lateinit var service: Instance<Service>
```

I use Intellij and I convert Java to Kotlin automatically (since the docu is written in java). Here, I remember I had multiple choices and I ended up deleting the Instance in Kotlin.

Your guess was right, I need `@DefaultBean`. Maybe ,it is better to provide an example which work for any property than one that breaks, since it is not completely obvious the need of `@DefaultBean` .

Thanks for your help.

**Comment by geoand** [comment]
Closing this as invalid, but I'll let @mkouba decide if the docs need to be improved

**Comment by mkouba** [comment]
The original snippet is wrong because it does not use programmatic lookup at all, i.e. the bean must not be injected directly but via `javax.enterprise.inject.Instance` which is explicitly mentioned in the first paragraph in [the docs](https://quarkus.io/guides/cdi-reference#declaratively-choose-beans-that-can-be-obtained-by-programmatic-lookup).

> Here, I remember I had multiple choices and I ended up deleting the Instance in Kotlin

That's never the right thing to do ;-). Anyway, we will add an import to the snippet in the docs.

> Your guess was right, I need @DefaultBean. Maybe ,it is better to provide an example which work for any property than one that breaks, since it is not completely obvious the need of @DefaultBean .

`@DefaultBean` is a different concept described in a [different section](https://quarkus.io/guides/cdi-reference#default_beans) of the docs.

> think the example in https://quarkus.io/guides/cdi-reference#declaratively-choose-beans-that-can-be-obtained-by-programmatic-lookup is a bit misleading. Couldn't we make it work instead of explaining why it fails in a comment?

The whole point of `@LookupIfProperty` is to _filter out_ the injected instances. The code itself does not work/fail - it depends on the value of the `service.foo.enabled` property as explained in the comment. Therefore, I think that it makes sense to leave it as it is.

**Comment by LegendL3n** [comment]
@mkouba Do you think it could be possible to not require the `Instance`? Maybe with a config? Just to reduce the patter

**Comment by mkouba** [comment]
> @mkouba Do you think it could be possible to not require the `Instance`? Maybe with a config? Just to reduce the patter

The `Instance` is absolutely necessary for `@LookupIfProperty` because otherwise we need to follow the spec rules and verify that exactly one bean dependency matches an injection point, othewise fail the build with an ambiguous/unsatisfied dependency.
