### ISSUE TITLE
gRPC cascaded client calls fail with timeout since v2.7.3

### ISSUE THREAD

**Issue by Octoate** [quarkusio/quarkus#24311]
### Describe the bug

Hi,
I am using Mutiny to define a call to two gRPC endpoints. If the first call was successfully completed, the second call should be executed. If an failure occurs, the client shall retry that operation again.

This is the client code, where "startPairing" (returns Uni<Boolean>) and "sendPairingKeyGetToken" (returns Uni<String>) are the gRPC calls to the server:

```java
var uniToken = pair();
uniToken.subscribe().with(
		token -> {
			Log.infov("Pairing done. New token = {0}.", token);
		},
		fail -> {
			Log.error("Pairing failed. Invalidate stored token.");
			Log.error(fail);
		});

private Uni<String> pair() {
	Log.info("Start pairing.");
	
	return grpcClient
		.startPairing()
			.onItem().transform(isPairing -> {
				Log.infov("Start pairing request returned: {0}", isPairing);
				if (Boolean.FALSE.equals(isPairing)) {
					return null;
				} else {
					return grpcClient.sendPairingKeyGetToken()
						.await().atMost(Duration.ofSeconds(gatewayConfiguration.grpcTimeout()));						
				}
			})
			.onItem().ifNull().fail()
			.onFailure().retry()
	        .withBackOff(Duration.ofMillis(100), Duration.ofSeconds(60))
	        .atMost(gatewayConfiguration.pairingRetry());
}
```

### Expected behavior

The client completes the process without a problem.

### Actual behavior

The second call to "sendPairingKeyGetToken" always times out and retries to redo the call until it completely fails.

### How to Reproduce?

Implement a very simple gRPC server that only returns directly the expected values ("true" for "startPairing" and any string for "sendPairingKeyGetToken").

I have attached a very simple example that calls an example gRPC service on the start of the Quarkus application. Until v2.7.2 this code works, but since v2.7.3 it runs into timeouts.

[gRPC-timeout-example.zip](https://github.com/quarkusio/quarkus/files/8251028/gRPC-timeout-example.zip)

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.7.3, 2.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.4 Java version: 11.0.14, vendor: GraalVM Community, runtime: C:\Program Files\GraalVM\graalvm-ce-java11-22.0.0.2 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by michalszynkiewicz** [comment]
I think that's expected, `await()` is blocking so the event loop gets blocked.
This code works:
```java
		return grpcClient.startPairing()
				.onItem().transformToUni(isPairing -> {
					Log.infov("Start pairing request returned: {0}", isPairing);
					if (Boolean.FALSE.equals(isPairing)) {
						return null;
					} else {
						return grpcClient.sendPairingKeyGetToken();
					}
				})
				.onItem().ifNull().fail()
				.onFailure().retry()
		        .withBackOff(Duration.ofMillis(100), Duration.ofSeconds(60))
		        .atMost(3);
```

**Comment by michalszynkiewicz** [comment]
@cescoffier do you know why this worked prior to 2.7.2? Can the change of the behavior be related to the context work?

**Comment by cescoffier** [comment]
It was a bug I fixed while adding support for duplicated context. The await() was executed on a gRPPC thread instead of the event loop. It should have never been the case as these threads are not managed.

**Comment by Octoate** [comment]
Ah, okay. I was not aware that I need to use "transformUni()" for the second gRPC call and because of that I tried to use "await()" here to retrieve the "String" from the second call.

It works great now. Thank you very much for your help!
