### ISSUE TITLE
llegalStateException: Request has already been read

### ISSUE THREAD

**Issue by nicpuppa** [quarkusio/quarkus#24317]
### Describe the bug

I have a chain of `@RouteFilter` which are applied at every request to authenticate the call. 
Example:
```@RouteFilter(998)
  void preAuthFilter(RoutingContext rc) {
        switch (AuthType.getType(getAuthorizationHeader(rc)))
            case BASIC:
                 ------
                 rc.next();
                 break;
            case BEARER:
                --------
                rc.next();
                break;
    }
```

After applying all the previous filter I have a `Router` class where all the method are annotated with `@Route`. 
For all GET request I have no problem, but for POST request sometimes I have an error: _llegalStateException: Request has already been read._

### Expected behavior

All request should works

### Output of `java -version`

openjdk version "11.0.10"

### Quarkus version or git rev

2.4.2.Final

**Comment by gsmet** [comment]
First, try with the latest version of Quarkus 2.7.4.Final as we have fixed a couple of similar issues.

If not fixed, please provide a small reproducer.

**Comment by nicpuppa** [comment]
With the Quarkus update it seems that the problem is solved. Thank you
