### ISSUE TITLE
DevServices for Keycloak UI is broken on 2.8-main

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#24329]
### Describe the bug

Regression has been introduced on `main`, after starting `mvn quarkus:dev` and going to `http://localhost:8080/q/dev/`, the OIDC card does not have a `Provider: Keycloak` link to `http://localhost:8080/q/dev/io.quarkus.quarkus-oidc/provider`. `http://localhost:8080/q/dev/io.quarkus.quarkus-oidc/provider` does respond if it is accessed directly but the UI is wrong there as well, `Service Path` field is shown alongside the expected `Log Into Single Page Application`.

It took me a long time to trace it down to #23781. All works as expected with the immediately preceding commit (Stork doc improvements).

The existing smoke test detects `http://localhost:8080/q/dev/io.quarkus.quarkus-oidc/provider` which is not sufficient, I think one of the OIDC devmode tests will need to be updated to check that `http://localhost:8080/q/dev` has a `Provider: Keycloak` string.

### Expected behavior

OIDC Card has a `Provider: Keycloak` and the provider page should only have a `Log Into Single Page Application` option, as shown [here](https://quarkus.io/guides/security-openid-connect-dev-services#dev-services-for-keycloak)

### How to Reproduce?

Do `mvn quarkus:dev` in `quarkus-quickstarts/security-openid-connect-quickstart` and go to `http://localhost:8080/q/dev` and observe an empty OIDC card without `Provider: Keycloak`, then go to `http://localhost:8080/q/dev/io.quarkus.quarkus-oidc/provider` and see a redundant `Service Path` field

**Comment by sberyozkin** [comment]
@mkouba @phillip-kruger Hi Martin, Phillip, can you have a look please, this branch is [embedded.html](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/resources/dev-templates/embedded.html#L5) does not work, `info:oidcProviderName` is set [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/AbstractDevConsoleProcessor.java#L33), passed from [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevConsoleProcessor.java#L46).

As far as the redundant `Service Path` field is concerned, it is defined in a few places in [provider.html](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/resources/dev-templates/provider.html).The expected `Log into Single Page Application` is displayed correctly, it is defined [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/resources/dev-templates/provider.html#L425).

**Comment by mkouba** [comment]
Hm, it does not seem to be related to https://github.com/quarkusio/quarkus/pull/23781. I've followed the steps to reproduce and the relevant `DevConsoleTemplateInfoBuildItem` is not produced at all because the `configProps` is an empty optional here: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevConsoleProcessor.java#L34. @sberyozkin which extension produces the `KeycloakDevServicesConfigBuildItem`?

**Comment by sberyozkin** [comment]
I'm sorry @mkouba, I rebuilt a few times yesterday and I was certain I located the PR which affected it, but in fact it is https://github.com/quarkusio/quarkus/commit/eff45901d57afa9fb12dc3da96bf65c6f5adef8d#diff-67404a43520250b1ebd5a0c945e070e60d70d4a3ba06b15e3fac747f820320cc, CC @ozangunalp, which affected it.

I'll see if I can fix it, sorry again @mkouba

**Comment by ozangunalp** [comment]
@sberyozkin That's my bad. I must have missed the usages of `KeycloakDevServicesConfigBuildItem`. 
I'll prepare a fix and modify the smoke test to check it.

**Comment by sberyozkin** [comment]
Hi @ozangunalp Np at all, I'm working on it right now, thanks. It was not something you could've detected as the smoke test was not providing enough evidence. I'll ask yourself and Martin to check my fix, due soon enough

**Comment by ozangunalp** [comment]
Ok! btw I tested this fix here: https://github.com/quarkusio/quarkus/compare/main...ozangunalp:fix_keycloak_dev_ui?expand=1

**Comment by sberyozkin** [comment]
@ozangunalp Thanks, this is how I started as well, but then realized it won't be enough as the `DevServicesResultBuildItem` will also be needed (to get some `configProps`). So instead of duplicating the properties again as I did originally, I thought of passing the extra properties with `DevServicesResultBuildItem`, should open a PR a bit later.

**Comment by sberyozkin** [comment]
I'll combine both items instead of using a single one
