### ISSUE TITLE
KeycloakContainer in integration-tests/kafka-oauth-keycloak is not aligned with Keycloak version used in devservices

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24320]
### Describe the bug

KeycloakContainer in integration-tests/kafka-oauth-keycloak is not aligned with Keycloak version used in devservices

Quarkus moved to  Keycloak version 17.0.0 with https://github.com/quarkusio/quarkus/pull/24108 but https://github.com/quarkusio/quarkus/blob/main/integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/containers/KeycloakContainer.java was left behind and not moved to version 17.0.00

Please update KeycloakContainer.java to version 17, my initial attempts didn't work well enough as Quarkus based Keycloak is used now in the main Keycloak image.

### Expected behavior

KeycloakContainer in integration-tests/kafka-oauth-keycloak is aligned with Keycloak version used in devservices

### Actual behavior

KeycloakContainer in integration-tests/kafka-oauth-keycloak is not aligned with Keycloak version used in devservices

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by sberyozkin** [comment]
Re assigning to Ozan

**Comment by sberyozkin** [comment]
@rsvoboda @ozangunalp I think for this test updating to `quay.io/keycloak/keycloak:17.0.0-legacy` image should do - most of OIDC tests use it as well as the next RH SSO will still be based on a WildFly based distro

**Comment by sberyozkin** [comment]
As far as using Quarkus based distro is concerned, it should become much easier for setting up the truststore, I've linked Ozan earlier to the where TLS is setup (in `integration-tests/oidc`). But at the moment Keycloak(-X) can not import a realm file itself at the startup, so an AdminClient POST request is required to upload the realm file - it is done in `DevServices for Keycloak`, Ozan, I can show all the details. 
But for now IMHO just updating the image name to `17.0.0-legacy` should do, Rostislav, do you agree ?

**Comment by rsvoboda** [comment]
That's a good point, +1 for `-legacy`

I can amend https://github.com/quarkusio/quarkus-quickstarts/pull/1080

Reassigning to me

**Comment by rsvoboda** [comment]
PR updated

**Comment by sberyozkin** [comment]
Thanks @rsvoboda, I left a comment there;
@ozangunalp I'd like to propose to pass this property https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L101 to this test, for it to pick up the next versions automatically

**Comment by geoand** [comment]
Is this issue still relevant?

**Comment by rsvoboda** [comment]
I think this is still relevant.

https://github.com/quarkusio/quarkus/blob/main/integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/containers/KeycloakContainer.java#L13 uses `quay.io/keycloak/keycloak:16.1.1`

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/DevServicesConfig.java#L38 uses `quay.io/keycloak/keycloak:20.0.3`

**Comment by gsmet** [comment]
This has been solved in `main`.
