### ISSUE TITLE
Kafka deserializer generalization issues. Code from Kafka guide doesn't work. 

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#24327]
### Describe the bug

1) I noticed that in the [Kafka guide](https://quarkus.io/guides/kafka#jackson-serialization) some deserialization constructor examples are not working, for example:

```
public class ListOfFruitDeserializer extends ObjectMapperDeserializer<List<Fruit>> {
    public ListOfFruitDeserializer() {
        TypeReference<List<Fruit>> listType = new TypeReference<>() {
        };
        super(listType);
    }
}
```

OR

```
public class ListOfFruitDeserializer extends JsonbDeserializer<List<Fruit>> {
    public ListOfFruitDeserializer() {
        Type listType = new ArrayList<MyEntity>() {}.getClass().getGenericSuperclass();
        super(listType);
    }
} 

```

You just can't call a superclass constructor if it's not the first statement in a subclass constructor.

2) I can't actually see a way to create a generic deserializer for a few different record classes as it can be done with ObjectMapperSerializer

org.apache.kafka.common.serialization.Deserializer tells in the javadoc

> A class that implements this interface is expected to have a constructor with no parameters

but io.quarkus.kafka.client.serialization.ObjectMapperDeserializer doesn't implement it

**Comment by cescoffier** [comment]
The doc should be updated to create the type reference in the parameter.

This is what is done when we generate the json serde
