### ISSUE TITLE
Reorder the Documentation web page titles

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#24326]
### Description

I realize this is sort of a nitpick, but is it possible to reorder the components of the documentation pages' titles?

Currently, it is something along the lines of:

`Quarkus - <page content title>`

Whereas the following would be better (I think):

`<page content title> - Quarkus`

The reasoning here is that when you have a bunch of tabs open, and can only see the first few characters of a particular tab's title, then you can't tell one page from another as all you can see is `Quark`. Bootstrap, for example, uses this approach and it is much easier to navigate to the documentation page based on looking at the tabs.

### Implementation ideas

I am hoping that it would be a simple change, where just the template used for all the pages would need to be tweaked slightly.

**Comment by geoand** [comment]
cc @jcobb

**Comment by insectengine** [comment]
Created this PR:
https://github.com/quarkusio/quarkusio.github.io/pull/1469

**Comment by ebullient** [comment]
Done! =)
