### ISSUE TITLE
Config like `mp.messaging.connector.smallrye-kafka.value.serializer` is ignored

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#24322]
### Describe the bug

The build step `SmallRyeReactiveMessagingKafkaProcessor#defaultChannelConfiguration()` currently ignores checking for connector-level config like `mp.messaging.connector.smallrye-kafka.value.serializer`. As a result this configuration has no effect when added to the `application.properties` file because the generated channel-level `RunTimeConfigurationDefaultBuildItem` defaults take precedence.

See also discussion in Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20Kafka.3A.20Apicurio.20for.20dev.20and.20Confluent.20for.20prod.20mode.3F

### Expected behavior

Explicit connector-level config in `application.properties` should take precedence over generated channel-level defaults.

The build step should probably check for the presence of such properties at build time to determine whether to generate a runtime default or not for a given channel's properties.

#### Use case

We are using Kafka with a schema registry and Avro encoded messages. In production the schema registry is the Confluent implementation and for development in dev mode we use Apicurio. This means that the serializer and deserializer implementation classes are different for production and non-production (i.e. test and development) launch modes. Further, since our application uses multiple channels, we would like to declare the Avro serializer and deserializer at the connector level, rather than individually for each channel. Doing it for each channel results in a lot of duplicated config.

### Actual behavior

The explicit connector-level config (like `mp.messaging.connector.smallrye-kafka.value.serializer`) in the `application.properties` file is ignored, because the autodetection generates corresponding channel-level config which takes precedence.

### Quarkus version or git rev

2.7.4.Final

**Comment by Ladicek** [comment]
Fix PR was reverted, so reopening.
