### ISSUE TITLE
The annotation io.quarkus.arc.All is not working in Kotlin

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#24339]
### Describe the bug

Injected list annotated with @All is empty in Kotlin when using constructor injection

Using the default approach with javax.enterprise.inject.Instance works as expected.

### How to Reproduce?

Reproducer created here 

https://github.com/amsterdam-superchat/quarkus-reproducer-inject-all

**Comment by manovotn** [comment]
> However, @All List<?> works similarly to Instance<?>, i.e. the required type is the type parameter specified at the injection point. I'm not sure whether Weld handles this use case differently.

@mkouba for `@Inject Instance<?>`, Weld throws `DefinitionException`.

**Comment by mkouba** [comment]
> > However, `@All List<?>` works similarly to `Instance<?>`, i.e. the required type is the type parameter specified at the injection point. I'm not sure whether Weld handles this use case differently.
> 
> @mkouba for `@Inject Instance<?>`, Weld throws `DefinitionException`.

Thanks @manovotn. In that case, we should throw a `DefinitionException` as well.

**Comment by mkouba** [comment]
I've sent a [pull request](https://github.com/quarkusio/quarkus/pull/24353) to improve the validation and I'm going to close this issue.

**Comment by amsterdam-superchat** [comment]
@mkouba Thanks!
