### ISSUE TITLE
Build failure due to parsing properties configuration

### ISSUE THREAD

**Issue by abouhabb** [quarkusio/quarkus#24331]
### Describe the bug

The build fail
Same behavior in jvm & native container mode, in java 11/17

Our modules use our own librairy for logging writing also in quarkus .

Everythings is working fine in 2.7.1.Final

The bug occure since 2.7.2.FINAL and others newer version.

### Expected behavior

build success

### Actual behavior

> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  43.160 s
> [INFO] Finished at: 2022-03-08T12:15:54+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.3.Final:build (default) on project company-module-executor: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> [ERROR] 	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit threw an exception: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
> [ERROR] 	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
> [ERROR] 	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
> [ERROR] 	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
> [ERROR] 	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
> [ERROR] 	at org.jboss.logmanager.formatters.FormatStringParser.getSteps(FormatStringParser.java:61)
> [ERROR] 	at org.jboss.logmanager.formatters.PatternFormatter.<init>(PatternFormatter.java:40)
> [ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.configureConsoleHandler(LoggingSetupRecorder.java:431)
> [ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.createNamedHandlers(LoggingSetupRecorder.java:328)
> [ERROR] 	at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeBuildTimeLogging(LoggingSetupRecorder.java:260)
> [ERROR] 	at io.quarkus.deployment.logging.LoggingResourceProcessor.setupLoggingRuntimeInit(LoggingResourceProcessor.java:222)
> [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
> [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
> [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
> [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
> [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
> [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

We found the root cause in our common librairy.  There was one spot in which property was set like :

`headerPatternLayout = %d{yyyy-MM-dd'T'HH:mm:ss,SSSXXX}\t%p\t[%t]\t[%h]\t[${company.instance.name}]\t[${company.module.name}]`

But in the company-common-logging-quarkus project we don't configure
company.instance.name, and this property is set in respective modules.
Hence placeholder ${company.instance.name} was throwing null pointer exception , which was working well till 2.7.1
So now I have set it like [${company.instance.name:}] (with colon)
So if it is defined , it will pick value , else will not throw any exception

In modules, the value of "company.instance.name" is a property getting from environnement variable.
So In the server where we build, the variable is not know

This line was working in 2.7.1.FINAL : 
`company.instance.name=${myModule_instanceName}`

Since 2.7.2.FINAL we have to do this : 
`company.instance.name=${myModule_instanceName:}`
the brackets seems unuseful here

I dont know if we fix a bug on our side or if just a workaround for a quarkus bug. But the update wasnt safe for us, is for that i open an issue

**Comment by geoand** [comment]
Is this still an issue with `2.7.4.Final`? Can you please give it a try?

**Comment by abouhabb** [comment]
yes same issue with 2.7.4.Final

**Comment by radcortez** [comment]
@abouhabb any chance you can provide a reproducer? Thanks!

**Comment by geoand** [comment]
Closing as we never got a reproducer
