### ISSUE TITLE
Missing Quarkus / Stork properties in Quarkus config all website

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#24341]
### Describe the bug

I am missing Quarkus / Stork properties in https://quarkus.io/guides/all-config

I am using Quarkus 2.7.4.Final + `io.smallrye.stork:stork-service-discovery-consul` extension and I would expect some `Quarkus` + `stork` propertiers references in all-config site. A Quarkus version of Stork properties, something like:

```
stork.pong-replica.service-discovery.refresh-period
stork.pong-replica.service-discovery
stork.pong-replica.service-discovery.consul-port
stork.pong-replica.service-discovery.consul-host
```

**Comment by aureamunoz** [comment]
This should be fixed by #24184
