### ISSUE TITLE
RestClient reactive, Post without entity: Content-Length should be set to 0

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#24349]
### Describe the bug

The application is trying send a http post request without an entity to a client, and the client rejects the request with:
Error 411. The request must be chunked or have a content length

This works for a non reactive RestClient.
I am not able to reproduce it toward a quarkus server, but a Microsoft-HTTPAPI/2.0 server rejects it.

See also: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reactive.20RestClient.20odata.20Error.20411

### Expected behavior

For a POST request without a body, Content-Length should be set to 0.
The client will then accept the request.

### Actual behavior

Client rejects the call

### How to Reproduce?

Run the test in the included reproducer.
Note!: The test doesn't fails as it works on a quarkus server.

But as it works in a non reactive environment, wireshark can be used to monitor and compare the http request in a non reactive vs reactive.

Our workaround is to set: 
HttpHeaders.CONTENT_LENGTH, value = 0
If:
!ctx.hasEntity() && "POST".endsWith(ctx.getMethod());
ClientRequestContext = ctx

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.7.4.Final

### Additional information

[rest-client-reactive-quickstart4.zip](https://github.com/quarkusio/quarkus/files/8262294/rest-client-reactive-quickstart4.zip)

**Comment by manofthepeace** [comment]
Same applies to the PUT method. In our case we added the following on top of the affected methods;
`@ClientHeaderParam(name = HttpHeaders.CONTENT_LENGTH, value = "0")`

**Comment by geoand** [comment]
I don't have a way to test it, but https://github.com/quarkusio/quarkus/pull/24392 should cover it

**Comment by manofthepeace** [comment]
> I don't have a way to test it, but https://github.com/quarkusio/quarkus/pull/24392 should cover it

I just tested using latest main that includes your commit and it seems to work as expected. Thank you

**Comment by geoand** [comment]
Awesome, thanks!
