### ISSUE TITLE
Support Karapace as an alternative Kafka schema registry devservice

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#24350]
### Description

[Karapace](https://github.com/aiven/karapace) is a lean Python-based and Confluent-compatible Kafka schema registry. As such it would be very useful to be able to use this instead of Apicurio as a devservice, when the schema registry used in production is the Confluent implementation. The Apicurio devservice has the drawback that it isn't Confluent-compatible and requires different serializers and deserializers for Avro-based messages.

See also discussion on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20Kafka.3A.20Apicurio.20for.20dev.20and.20Confluent.20for.20prod.20mode.3F

### Implementation ideas

Since the current devservice config properties are very Apicurio-specific (with an `apicurio` name segment), the evolution to support a different schema registry implementation may not be quite as straight-forward. Should the property names possibly be deprecated in favor of vendor-agnostic properties?

**Comment by alesj** [comment]
Afaik, Apicurio schema registry was designed to be Confluent-compatible -- at least when I was working on it (as initial contributer).
Is that not the case anymore?
@EricWittmann ^ ?

**Comment by cescoffier** [comment]
It is still the case, but it's a different endpoint. At the moment we inject the 'plain' apicurio url and not the confluent compatible one. This is something we should do if we detect the confluent serde on the classpath.

**Comment by knutwannheden** [comment]
@alesj Will #24526 already allow to use Karapace as an alternative?

**Comment by cescoffier** [comment]
I agree with @Ladicek. The need was to be able to use the Confluent Avro Serde. This has been fixed in #24526.

I would be in favor to close this issue.

**Comment by cescoffier** [comment]
Closing, see comments.

**Comment by alesj** [comment]
Not yet.
But let me check this and get back to you.
