### ISSUE TITLE
Using Slf4J instead of Jboss Logger

### ISSUE THREAD

**Issue by estet90** [quarkusio/quarkus#24377]
### Description

Now Jboss Logger is used everywhere in the Quarkus libraries. If I want to use a Log4J2 in my projects and send logs through it, for example, TCP, Quarkus logs do not get into the log collection system. Is it possible to do it by analogy with Spring, using Slf4J in the libraries, so that the developer himself can determine the implementation?

**Comment by estet90** [comment]
> As is mentioned in the [docs](https://quarkus.io/guides/logging#supported-logging-apis), you can use slf4j as the logging API. What Quarkus mandates is the use of JBoss Logging Manager as the implementation - i.e. you can't use Logback or Log4j2.

You did not understand me. I want quarkus logs, for example, service start logs, to be forwarded to log4j2, and then I could send them anywhere

**Comment by geoand** [comment]
What'l does forward logs to Log4j2 mean?
As I explained, we won't be supporting it.

We do however have various transport mechanisms for JBoss Logmanager
