### ISSUE TITLE
reactive: propagateHeaders don't work async

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#24375]
### Describe the bug

I need to propagate header info from the server towards the RestEasy client.

In the classic environment it works fine to propagate the Authorization header included in the server request towards the RestEasy client request, even when the client request is executed async with a ManagedExecutor.

This is accomplished with adding the following to the [application.properties](http://application.properties/) file:
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization
And adding the @RegisterClientHeaders to the RestEasy interface.

But if the same is attempted in the reactive world, the header is "lost"

Is there a workaround for that?

See also:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/reactive.3A.20propagateHeaders.20don't.20work.20async

### Expected behavior

The Authorization header should be included in the outgoing request

### Actual behavior

The Authorization header is not included in the outgoing request

### How to Reproduce?

Run the provided test and verify the logging.
For the ok test, the Authorization can be seen, but NOT for the fail test 

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.7.5.Final

### Additional information

[rest-client-reactive-quickstart4.zip](https://github.com/quarkusio/quarkus/files/8286271/rest-client-reactive-quickstart4.zip)

**Comment by geoand** [comment]
@michalszynkiewicz are you looking at this one or do you want me to?

**Comment by michalszynkiewicz** [comment]
I'm on it

**Comment by michalszynkiewicz** [comment]
thanks for handling the zero content length :)

**Comment by michalszynkiewicz** [comment]
@lthasle quarkus-rest-client-reactive relies on a request-scoped bean for propagating the headers.
That's why, smallrye context propagation needs to work when offloading client invocation elsewhere.
Unfortunately, it looks like the following (as you have in your app), doesn't propagate the context to the executed actions:
```java
   CompletableFuture.runAsync(() -> {
      resp = client.get(id);
			//System.out.println("RESP: " + resp);
      }, managedExecutor);
```

The following works:
```java
        managedExecutor.runAsync(() -> {
            String resp = client.get(id);
            //System.out.println("RESP: " + resp);
        });
```


@FroMage @manovotn is `CompletableFuture.runAsync` not supported or did we hit some edge case? I'm guessing the former because I wasn't able to find anything about it in the MP spec

**Comment by michalszynkiewicz** [comment]
BTW, Lars, what's your use case for explicit offloading of an execution? Could you do sth like this instead:
```java
@RegisterClientHeaders
@Path(MyController.DOMAIN)
@RegisterRestClient(baseUri = "http://localhost:8081")
public interface MyClient {

    @POST
    @Path(MyController.CALLBACK)
    Uni<String> get(@QueryParam("id") String id);
}
```

```java
@Path(MyController.DOMAIN)
public class MyController {

	public static final String RESULT = "hello";
	public static final String PATH_OK = "ok";
	public static final String PATH_FAIL = "fail";
	public static final String CALLBACK = "cb";
	public static final String DOMAIN = "my";

	@RestClient
	MyClient client;

	@GET
	@Path(PATH_FAIL)
	public Response fail() {
		runAsync("12");
		return Response.ok().build();
	}

	private void runAsync(String id) {
        client.get(id).subscribeAsCompletionStage()
                .thenAccept(resp -> System.out.println("RESP: " + resp));
	}

	@GET
	@Path(PATH_OK)
	public Uni<Response> get() {
		var msg = client.get("12");
		return msg.onItem().transform(m -> Response.ok(m).build());
	}
```

**Comment by manovotn** [comment]
> @FroMage @manovotn is CompletableFuture.runAsync not supported or did we hit some edge case? I'm guessing the former because I wasn't able to find anything about it in the MP spec

@michalszynkiewicz I don't think this can work if you directly invoke the static method.
CP has a wrapper for [`CompletableFuture`](https://github.com/smallrye/smallrye-context-propagation/blob/main/core/src/main/java/io/smallrye/context/CompletableFutureWrapper.java) but we cannot override the static method and hence have no means of capturing the current context before delegating to the executor.

Generally, the entry points for context propagation are `ManagedExecutor` and `ThreadContext`.

**Comment by michalszynkiewicz** [comment]
Thanks Matej!

**Comment by geoand** [comment]
So it sounds like this should be closed, correct?

**Comment by cescoffier** [comment]
Well, I would add: do not use CompletableFuture :-D

**Comment by geoand** [comment]
As we have `Uni` 😉

**Comment by lthasle** [comment]
@michalszynkiewicz 
Thanks four your feedback

Sorry for the late response!

You say that if I change the method MyController.runAsync acccording to the code below, it should work, but if you run the provided test: MyTest.fail

The Authorization header is still missing!

Are there more changes to be done?

private void runAsync(String id) {

managedExecutor.runAsync(() -> {
            String resp = client.get(id);
        });
/*CompletableFuture.runAsync(() -> {
String resp = client.get(id);
}, managedExecutor);*/
}

**Comment by michalszynkiewicz** [comment]
I think I did exactly this when trying out your project and it worked. 
Can you update the reproducer? I would take another look

**Comment by lthasle** [comment]
[rest-client-reactive-quickstart4.1.zip](https://github.com/quarkusio/quarkus/files/8379963/rest-client-reactive-quickstart4.1.zip)
@michalszynkiewicz 
I have updated the reproducer, run the test -> 
no Authorization header is printed in the output
I also notized that it works with CompletableFuture.supplyAsync, se code

**Comment by michalszynkiewicz** [comment]
@lthasle on your project, without any changes, I get the following. That is what you expect, no?
```
rest-client-reactive-quickstart4.1]$ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.acme:rest-client-reactive-quickstart >--------------
[INFO] Building rest-client-reactive-quickstart 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rest-client-reactive-quickstart ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rest-client-reactive-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.5.Final:generate-code (default) @ rest-client-reactive-quickstart ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ rest-client-reactive-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/michal/job/quarkus/tmp/rest-client-reactive-quickstart4.1/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.5.Final:generate-code-tests (default) @ rest-client-reactive-quickstart ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rest-client-reactive-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ rest-client-reactive-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/michal/job/quarkus/tmp/rest-client-reactive-quickstart4.1/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ rest-client-reactive-quickstart ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ex.MyTest
2022-03-30 21:47:38,760 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-03-30 21:47:39,445 INFO  [io.quarkus] (main) Quarkus 2.7.5.Final on JVM started in 0.975s. Listening on: http://localhost:8081
2022-03-30 21:47:39,445 INFO  [io.quarkus] (main) Profile test activated. 
2022-03-30 21:47:39,445 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
1 * Sending client request on thread executor-thread-0
1 > POST http://localhost:8081/my/cb?id=12
1 > Accept: text/plain;charset=UTF-8
1 > Authorization: Basic dXNlcjpwdw==
1 > User-Agent: Resteasy Reactive Client

2 * Sending client request on thread executor-thread-1
2 > POST http://localhost:8081/my/cb?id=12
2 > Accept: text/plain;charset=UTF-8
2 > Authorization: Basic dXNlcjpwdw==
2 > User-Agent: Resteasy Reactive Client

Resp: hello
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.7 s - in ex.MyTest

```

**Comment by michalszynkiewicz** [comment]
Hmm.. as your logging filter doesn't have a `@Priority`, and the headers factory is implemented with a filter itself, maybe the order of filters is not as you expect on your OS?
Can you try adding `@Priority(0)` to your filter? Or, perhaps even better, use the built in logging for rest client requests and responses?

**Comment by lthasle** [comment]
Thanks again for your effort
Strange! I get the same result as you with mvn.
but if I run MyTest. fail with my ide(eclipse) I don't see the Authorization header in the log.
But I see it when I run the other test: MyTest.ok

Using @Priority(0) don't do any change to the output.

"Built in logging for rest client" is new to me.
Is there a guide for this?

**Comment by lthasle** [comment]
Strange ide behaviour.
Thanks for the guide, works fine with mvn, but not in my ide.
But I think we joust leave it, THANKS!

**Comment by MarvinKlar** [comment]
I got a similar problem, but I actually need the result of the async/non-blocking method.

Something like
```
@Getter private KeycloakToken keycloakToken;

@Override
public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders, MultivaluedMap<String, String> clientOutgoingHeaders) {
  MultivaluedMap<String, String> result = new QuarkusMultivaluedHashMap<>();
  managedExecutor.runAsync(() -> {
    try {
      keycloakToken = keycloakRestClient.getToken(params).subscribeAsCompletionStage().get(3, TimeUnit.SECONDS);
    } catch (Exception e) {
      LOGGER.error("Unable to obtain Keycloak token for API.", e);
    }
  }).get(3, TimeUnit.SECONDS);
  result.add("Authorization", "Bearer " + keycloakToken.getAccessToken());
  return result;
```

The RestClient, using this ClientHeadersFactory (using `@RegisterClientHeaders(RequestAuthHeaderFactory.class)` needs the Keycloak token for the request.

But I can't figure out how to aquire this token without having a `io.vertx.core.VertxException: Thread blocked` or in this case a `TimeoutException`. Do you know how to solve this?

**Comment by MarvinKlar** [comment]
My previous attempt looks like 
```
@Override
public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders, MultivaluedMap<String, String> clientOutgoingHeaders) {
  MultivaluedMap<String, String> result = new QuarkusMultivaluedHashMap<>();
  try {
    keycloakToken = keycloakRestClient.getToken(params).subscribeAsCompletionStage().get(3, TimeUnit.SECONDS);
  } catch (Exception e) {
    LOGGER.error("Unable to obtain Keycloak token for API.", e);
  }
  result.add("Authorization", "Bearer " + keycloakToken.getAccessToken());
  return result;
```
