### ISSUE TITLE
Last-Modified response header is not properly handled in QuarkusTests using MockHttpEventServer

### ISSUE THREAD

**Issue by PieterDr** [quarkusio/quarkus#24380]
### Describe the bug

I am using RestAssured in a QuarkusTest to test a RestEasy resource endpoint that returns a response containing the header:

`Last-Modified: Tue, 26 Oct 2021 01:01:01 GMT` 

The test goes as follows:
```
@Test
void verifyLastModifiedHeader() {
        RestAssured.given()
                .accept(JSON)
                .when()
                .get("/my-endpoint")
                .then()
                .statusCode(200)
                .header("Last-Modified", "Tue, 26 Oct 2021 01:01:01 GMT");
}
```

The test fails with the following output:

> java.lang.AssertionError: 1 expectation failed.
Expected header "Last-Modified" was not "Tue, 26 Oct 2021 01:01:01 GMT", was "26 Oct 2021 01:01:01 GMT". Headers are:
content-length=84
Access-Control-Allow-Origin=*
Access-Control-Allow-Methods=GET
Last-Modified=Tue
Last-Modified=26 Oct 2021 01:01:01 GMT

This seems to be due to the MockHttpEventServer splitting all response headers on `","`. This is logical for multivalue headers, but for Last-Modified (and other related headers such as If-Modified-Since) this behaviour is incorrect.

### Output of `java -version`

openjdk version "17" 2021-09-14

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by gsmet** [comment]
@patriot1burke this looks like one for you.
