### ISSUE TITLE
Unexpected logging behavior and warning message

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#24406]
### Describe the bug

Hi guys!

I don't know if it's a bug or not.

1) When I set the following properties in a new project:

```
quarkus.log.min-level=TRACE
quarkus.log.level=TRACE
```

I receive warning in logs:

> WARN: Root log level TRACE set below minimum logging level DEBUG, promoting it to DEBUG

Some trace logs are displayed anyway.

2) In the test, I'm injecting UserTransaction class and then calling:

userTransaction.begin(); 

And I would expect TRACE logs to be shown, but when BaseTransaction.begin checks logging level:

`if (jtaLogger.logger.isTraceEnabled()) { ... }`

only INFO level is enabled. 
Could you please help me see TRACE logs from the Narayana library in this case?

The reproducer is attached.

### How to Reproduce?

[jboss-logging-check.zip](https://github.com/quarkusio/quarkus/files/8304280/jboss-logging-check.zip)

### Quarkus version or git rev

2.7.5.Final

**Comment by famod** [comment]
I'll send a PR soon that'll remove that warning
> WARN: Root log level TRACE set below minimum logging level DEBUG, promoting it to DEBUG

but turns out that this is _not_ the root cause:
The same code in a Maven project will print `BaseTransaction` messages just fine (and also that warning).

So it seems to be a gradle specific problem? cc @glefloch

**Comment by gsmet** [comment]
Well, that warning shouldn't be entirely removed. But if it appears when `min-level` is properly set up, there's probably something fishy.

**Comment by famod** [comment]
> Well, that warning shouldn't be entirely removed.

Right, that's not what I'm going to do. The warning is a false negative here and that's what I'm going to fix.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
