### ISSUE TITLE
Cannot produce native executable in Windows 10

### ISSUE THREAD

**Issue by bellrauthien** [quarkusio/quarkus#2440]

**Comment by bellrauthien** [comment]
I am not able to create a native executable file in Windows 10. I am able to do this in RHEL7 but no in Windows. This is the error I'm facing when running mvnw.cmd package -Pnative.

Found "c:\Leo\repositories\Femsa\microservices\rest\ReceiveGPS\ReceiveGPSData\.mvn\wrapper\maven-wrapper.jar"
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------------< femsa:gps >------------------------------
[INFO] Building gps 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gps ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gps ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gps ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Leo\repositories\Femsa\microservices\rest\ReceiveGPS\ReceiveGPSData\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gps ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ gps ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ gps ---
[INFO] Building jar: c:\Leo\repositories\Femsa\microservices\rest\ReceiveGPS\ReceiveGPSData\target\gps-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.14.0:build (default) @ gps ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Alpha4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 977ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: c:\Leo\repositories\Femsa\microservices\rest\ReceiveGPS\ReceiveGPSData\target\gps-1.0-SNAPSHOT-runner.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.14.0:native-image (default) @ gps ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] C:\oracle\products\graalvm-ce-19.0.0\bin\native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar gps-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.801 s
[INFO] Finished at: 2019-05-14T16:21:07-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.14.0:native-image (default) on project gps: Failed to generate a native image: Failed to build native image: Cannot run program "C:\oracle\products\graalvm-ce-19.0.0\bin\native-image" (in directory "c:\Leo\repositories\Femsa\microservices\rest\ReceiveGPS\ReceiveGPSData\target"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jclingan** [comment]
GraalVM RC15 does not support windows native binaries, so Quarkus 0.14.0 cannot compile to a Windows binary.  Track [this issue](https://github.com/quarkusio/quarkus/issues/2412) to stay on top of Windows native binary support as we work our way to support GraalVM 19.0.0.

**Comment by machi1990** [comment]
> GraalVM RC15 does not support windows native binaries, so Quarkus 0.14.0 cannot compile to a Windows binary. Track [this issue](https://github.com/quarkusio/quarkus/issues/2412) to stay on top of Windows native binary support as we work our way to support GraalVM 19.0.0.

@bellrauthien Quarkus 0.18.0 has been released with support for GraalVM 19.0.2. Can you check if you are still having this issue?
