### ISSUE TITLE
protoc-less code generation

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#24409]
### Description

Currently, we use protoc to generate code from Java. One of the drawbacks of it is that grpc code cannot be generated on powerpc.
This task is about replacing protoc with pure Java solution

### Implementation ideas

Maybe we can use/reuse some of https://github.com/square/wire

**Comment by michalszynkiewicz** [comment]
the linked library uses kotlin, would be good not to have to depend on Kotlin for this. I'll see how much work it is to create something

**Comment by geoand** [comment]
You mean wire depends on Kotlin?

Is that really a problem though given that the code generation would not be part of the Quarkus build, but a separate generation phase (I assume)?

**Comment by geoand** [comment]
Or do you mean that the generated code is Kotlin code?

**Comment by michalszynkiewicz** [comment]
Yes, I mean wire depends on Kotlin.

Code generation is done by the quarkus maven plugin in a separate goal.  So users' app won't need to depend on Kotlin

**Comment by geoand** [comment]
Right, so I see no reason why Wire itself depending on Kotlin would be problematic

**Comment by gsmet** [comment]
It might become problematic because Kotlin is sometimes lagging for new JDK support.
That would mean that you wouldn't be able to use the latest JDK for building these particular apps.
And for instance, I'm not sure we will be able to run the tests with EA if we depend on Kotlin for the build.

Now, is it enough of a problem to warrant our own solution, I don't know but that's an issue we will have for sure.

**Comment by michalszynkiewicz** [comment]
thanks for your input @geoand and @gsmet !

I'll keep looking at this and other possibilities for a while.

**Comment by geoand** [comment]
>  and other possibilities for a while.

Have you found other libraries that generate code from a `.proto` file?

**Comment by michalszynkiewicz** [comment]
Not yet :)

**Comment by geoand** [comment]
`wire` does look pretty interesting in that it [seems](https://github.com/square/wire/blob/4.3.0/samples/wire-codegen-sample/src/test/java/com/squareup/wire/sample/ServiceGeneratorTest.kt#L34) to allow you to generate whatever Java code you like...

**Comment by geoand** [comment]
Actually, `wire` is going to be problematic because the generated schema code depends on Kotlin...

For example, for this `.proto` file:

```proto
syntax = "proto2";

package squareup.geology;

option java_package = "com.squareup.geology";

enum Period {
  /** 145.5 million years ago — 66.0 million years ago. */
  CRETACEOUS = 1;

  /** 201.3 million years ago — 145.0 million years ago. */
  JURASSIC = 2;

  /** 252.17 million years ago — 201.3 million years ago. */
  TRIASSIC = 3;
}
```

the generated code is:

```java
// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.geology.Period in squareup/geology/period.proto
package com.squareup.geology;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum Period implements WireEnum {
  /**
   * 145.5 million years ago — 66.0 million years ago.
   */
  CRETACEOUS(1),

  /**
   * 201.3 million years ago — 145.0 million years ago.
   */
  JURASSIC(2),

  /**
   * 252.17 million years ago — 201.3 million years ago.
   */
  TRIASSIC(3);

  public static final ProtoAdapter<Period> ADAPTER = new ProtoAdapter_Period();

  private final int value;

  Period(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static Period fromValue(int value) {
    switch (value) {
      case 1: return CRETACEOUS;
      case 2: return JURASSIC;
      case 3: return TRIASSIC;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_Period extends EnumAdapter<Period> {
    ProtoAdapter_Period() {
      super(Period.class, Syntax.PROTO_2, null);
    }

    @Override
    protected Period fromValue(int value) {
      return Period.fromValue(value);
    }
  }
}
```

**Comment by andreas-eberle** [comment]
Could it be an option to still use wire? I mean, sure, it would add the kotlin standard library if you use quarkus-grpc then, but it would fix some issues / have some benefits that might be worth that compromise: 

* enable compilation for powerpc
* it is a working library; using it would not require to implement an own library and thus reduce maintance efforts
* generate proper Kotlin code for Kotlin users
  * data class-like messages
  * generate couroutine code
  * respecting nullable/optional fields in Kotlin types

**Comment by geoand** [comment]
We really don't want to have Kotlin as a dependency unless it's necessary.

I was initially very excited about wire, but when I saw that it has a *runtime* dependency on Kotlin the enthusiasm dampened...

**Comment by andreas-eberle** [comment]
Can you explain a bit why the Kotlin runtime dependency is so bad? Just so I can understand the situation better. Thanks!

**Comment by geoand** [comment]
Because it ties us to Kotlin for absolutely no reason - that coupling can cause unexpected problems in the mid term (we've already seen those sorts of issues) and anyone who has ever dealt with scala based libraries knows that this is something to be avoided like the plague...

I am not saying that we can't have a better Kotlin specific grpc experience, what I am saying is that it makes zero sense for our general grpc support to require Kotlin

**Comment by holly-cummins** [comment]
+1 personal confirmation for "Kotlin should be minimised on the general path". I've seen places where the presence of Kotlin drags libraries further down the chain into being parent-first, which kicks them out of our classloaders, which makes things go weird. I don't know if there's a risk of that in this particular case, but I can see the argument for caution.

**Comment by andreas-eberle** [comment]
I see. Thanks for the explanations!

**Comment by andreas-eberle** [comment]
Just an idea: It looks like wire has at least two runtime implementations (https://github.com/square/wire/tree/master/wire-library). One for jvm and one for JS. Maybe it could be an idea to implement a pure-Java wire runtime for the Java use-case. I don't know if they would be interested in something like that, but it could allow reusing most of that project.

**Comment by geoand** [comment]
Yeah, that's one possibility, but it requires that someone set aside (potentially a lot of) extra time to do this

**Comment by geoand** [comment]
I just realized we already have an [issue](https://github.com/quarkusio/quarkus/issues/24505) for Kotlin support of gRPC.

**Comment by cescoffier** [comment]
Related to #21445

**Comment by cescoffier** [comment]
It's not going to be implemented in 2024.

After discussing and evaluating the community's current interests, we've decided not to implement protoc-less approaches yet. The level of demand and the potential value to the broader Quarkus community has faded, and we believe our resources are better focused on other priorities.
We can revisit this if there's renewed interest in the future.
