### ISSUE TITLE
Reactive Rest client can not upload files bigger, than 2G

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#24405]
### Describe the bug

Quarkus Rest Reactive client fails with OutOfMemory error when uploading files bigger than 2G.

### Expected behavior

Reactive client should be able to process files of any size. 

### Actual behavior

Sending fails with `HTTP Request to /client-wrapper/upload-file failed, error id: 6fdd4d92-5bb6-49df-bd70-c5e3671bbad3-1: java.lang.OutOfMemoryError`

### How to Reproduce?

1. `git clone git@github.com:fedinskiy/quarkus-test-suite.git -b reproducer/reactive-rest-client`
2. `cd quarkus-test-suite/http/rest-client-reactive`
3. `mvn clean verify -Dit.test=FileIT#uploadFile`

### Output of `uname -a` or `ver`

  5.16.13-200.fc35.x86_64

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

See also https://github.com/quarkusio/quarkus/issues/24402 for the same error on downloading.

**Comment by fedinskiy** [comment]
When File is passed through multipart, the client fails with much more informative `Request Entity Too Large`. Steps to reporduce are the same, but last step should look like that: `mvn clean verify -Dit.test=FileIT#uploadMultipart`

**Comment by gsmet** [comment]
@michalszynkiewicz a lot of APIs out there allow to download files (typically the GitHub API).

**Comment by geoand** [comment]
I'll have a look

**Comment by geoand** [comment]
> When File is passed through multipart, the client fails with much more informative `Request Entity Too Large`

This is a message returned by the Server. You need to configure Quarkus with something like: `quarkus.http.limits.max-body-size=2050m`.
See [this](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.limits.max-body-size) for more information
