### ISSUE TITLE
Update openshift-s2i-guide.adoc to use ubi8-minimal

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2442]
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/openshift-s2i-guide.adoc refers to `ubi7-dev-preview/ubi-minimal`

Not sure if it's available anymore (couldn't find it in https://access.redhat.com/containers/)

The guide should be updated to use https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal

**Comment by gsmet** [comment]
@rsvoboda @cescoffier looks like it's still an issue in here: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/deploying-to-openshift-s2i.adoc#building-a-minimal-runtime-container 

I'm not familiar with this at all. Is it easily fixable?

**Comment by tqvarnst** [comment]
I can fix it, but I need to verify and test with the new ubi8-minimal containers. Because of other priorities, I will not be able to look at this until next week, but it is on my todo.

**Comment by gsmet** [comment]
Hi Thomas, I affected it back to you then. Thanks!

**Comment by geoand** [comment]
Closing this as the file no longer exists
