### ISSUE TITLE
URL routes not properly matched

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#24428]
### Describe the bug

Given the controller:

```java
@PATCH @Path("/recrutment/{sessionId}") //
@POST @Path("/recrutment/new") //
@GET @Path("/recrutment/open/all") //
@GET @Path("/recrutment/table") //
@GET @Path("/recrutment/{sessionId}/table") //
@GET @Path("/recrutment/{sessionId}/user") //
@GET @Path("/recrutment/{sessionId}") //
@PUT @Path("/recrutment/{sessionId}") //
```

and the url: /recrutment/7/table?page=1

i expect the `@GET @Path("/recrutment/{sessionId}/table") //` to be called but I get a 404

### Expected behavior

The proper endpoint is called

### Actual behavior

I get a 404

### How to Reproduce?

1. Create a resteasy-reactive project Quarkus 2.7.5.Final
2. Create the endpoint describe previously
3. Send a request

**Comment by Plawn** [comment]
moving it to another controller with less routes fixed the issue

**Comment by gsmet** [comment]
Could you provide a small reproducer?

**Comment by geoand** [comment]
So if I understand the issue correctly, you are saying that using the same prefix on different JAX-RS classes does not work?
If so, then that is expected by the spec AFAIR

**Comment by geoand** [comment]
Closing as we never got a reproducer
