### ISSUE TITLE
Hibernate ORM - place PersistenceProviderSetUpBuildItem in an SPI module

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#24439]
### Description

So that any extension that needs to execute a build step AFTER the persistence providers are set up can consume this SPI build item without introducing a dependency on `quarkus-hibernate-orm-deployment`.

Furthermore, it seems odd that the `PersistenceProviderSetUpBuildItem` extends `MultiBuildItem`. Is there a good reason for this design decision given the fact that ORM and HR cannot run side by side?

Note that this would be a breaking change because the SPI module cannot use the `io.quarkus.hibernate.orm.deployment` package.

**Comment by gsmet** [comment]
> given the fact that ORM and HR cannot run side by side

We want to change that at some point in the future.

**Comment by gsmet** [comment]
@mkouba I had the same thought this week-end but I was wondering if it could be a more general issue than just Hibernate ORM? E.g. maybe all persistence layers around there could have this issue.

Thus I was wondering if we should instead provide a generic `PersistenceLayerInitializerBuildItem` in `core` that would be produced by everything that provide a persistence layer. And bonus point, it wouldn't break anything.

I have no idea if it's a problem very specific to Hibernate ORM or if it's something that could happen with other extensions.

**Comment by mkouba** [comment]
> Thus I was wondering if we should instead provide a generic `PersistenceLayerInitializerBuildItem` in `core` that would be produced by everything that provide a persistence layer. And bonus point, it wouldn't break anything.

+1

> I have no idea if it's a problem very specific to Hibernate ORM or if it's something that could happen with other extensions.

It's not specific to Hibernate ORM. In general, any extension that does initialize a bean through a recorder method (which is considered a bad practice and extensions should try to leverage [synthetic beans](https://quarkus.io/guides/cdi-integration#synthetic_beans) where possible) may cause this kind of problems.

**Comment by Sanne** [comment]
Do you have a pointer to some concrete need?  In particular I'm not following why you'd want to avoid depending on `quarkus-hibernate-orm-deployment` when there's an actual need for ORM.

**Comment by mkouba** [comment]
> Do you have a pointer to some concrete need? In particular I'm not following why you'd want to avoid depending on `quarkus-hibernate-orm-deployment` when there's an actual need for ORM.

Because it might be an optional dependency? A concrete use case is described in https://github.com/quarkusio/quarkus/issues/24441 - the gRPC extension needs to initialize the server after the HT SessionFactory bean is initialized.

**Comment by Sanne** [comment]
@mkouba ok - thanks!

Just a thought then - but if it's `optional` it can possibly be broken down at the consumer side. We should avoid optional dependencies as that leads to other issues.

**Comment by gsmet** [comment]
> It's not specific to Hibernate ORM. In general, any extension that does initialize a bean through a recorder method (which is considered a bad practice and extensions should try to leverage [synthetic beans](https://quarkus.io/guides/cdi-integration#synthetic_beans) where possible) may cause this kind of problems.

Well maybe we should fix that instead. The bean creation in the ORM extension was done a long time ago before the synthetic beans infrastructure existed and maybe we could rely on synthetic beans instead.
But that's probably not something we would backport.

**Comment by Sanne** [comment]
Alternative: we seem to often need a "marker" builditem to coordinate ordering events; such build items have no other meaning other than marking phases and are identified by their class type.

Wondering if we should introduce support for such markers to be defined by a name rather than a type, so that cross-module integrations can be implemented w/o needing to extract SPI modules.  This would also allow to specify particular named resources, e.g. you could depend on a particular persistence unit, not necessarily needing to wait for all of them being ready - although I'm not sure if there's value in that.

Generally speaking I think avoiding optional dependencies would be my preference though.

**Comment by mkouba** [comment]
We're going to fix the Hibernate/gRPC issue with a special build item; see https://github.com/quarkusio/quarkus/pull/24420. So the priority of this issue is low (until we find another good use case ;-).

**Comment by gsmet** [comment]
OK, let's close it then. We can create a new one or reopen if at some point we need it.
