### ISSUE TITLE
Create a build item to emit from steps that initialize CDI beans

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#24441]
### Description

Hibernate and hibernate reactive processors initialize beans in runtime init. Possibly there are others, they maybe others outside the quarkus core repository.
`GrpcServerProcessor` needs to initialize the gRPC server after the CDI beans are initialized. 

Currently we often see failures (e.g. https://github.com/quarkusio/quarkus/pull/24398) of a test that mixes hibernate reactive and grpc because the steps to initialize hibernate reactive (`HibernateReactive#setUpPersistenceProviderAndWaitForVertxPool`) and the grpc server (`GrpcServerProcessor#initializeServer`) are not ordered.

### Implementation ideas

We could move the `PersistenceProviderSetUpBuildItem` to an spi module as suggested in https://github.com/quarkusio/quarkus/issues/24439, and then make the grpc server build step depend on it.
But I think there may be other cases like this so maybe it's worth adding a separate, generic build item, that could be emitted in hibernate and consumed by build steps such as grpc init.

WDYT @mkouba @gsmet ?

**Comment by gsmet** [comment]
Don't we have a build item emitted when all CDI beans have been initialized? If not, we should probably have ont?

**Comment by mkouba** [comment]
> Don't we have a build item emitted when all CDI beans have been initialized? If not, we should probably have one?

There are several build items that can be used for a similar use case (e.g. `SyntheticBeansRuntimeInitBuildItem` and `BeanContainerBuildItem`)  but none that can be used when a bean is initialized by a recorder method. This would require all the build steps that perform the initialization to produce a build item of this type, e.g. `BeanInitializedBuildItem`.

The downside of this approach would be that a consumer cannot specify which bean it is interested into, i.e. it would be executed when ALL beans are initialized.

**Comment by michalszynkiewicz** [comment]
For gRPC this is what we're looking for, I think

**Comment by mkouba** [comment]
My problem with this approach is that it's not easy to find all cases where it's needed. Neither can we automatically detect a problem like this. In other words, it would be a lot of manual work...

**Comment by manovotn** [comment]
A build item like this could be handy as it clearly shows a point at which it is safe to assume the bean init is over. OTOH I can easily imagine various extensions (existing or new) 'forgetting' to emit this build item which then puts you back to square one.
But I suppose it's still better than not having it at all.

>  Without it, we have to create dedicated build items for each case, no?

+1, I wouldn't be surprised to find this in existing extensions that have some intricate dependencies between them

**Comment by mkouba** [comment]
> Without it, we have to create dedicated build items for each case, no?

Yes, but given the fact that the _"initialize a bean via recorder method"_ pattern is considered a bad practice and should not be used unless really necessary (and the `SyntheticBeanBuildItem` cannot be used) I don't think this is a big problem.

**Comment by mkouba** [comment]
> A build item like this could be handy as it clearly shows a point at which it is safe to assume the bean init is over. 

Well, this "bean init" would just mean that some of the extensions that produce the `BeanInitializedBuildItem` finished their processing. It's a very coarse-grained approach and it could e.g. prevent parallel bootstrap because all the dependencies would always wait for all beans.

However, I agree that it might be sometimes useful.

**Comment by gsmet** [comment]
I had a look and I don't see an easy way out given the way Hibernate Reactive is initialized at the moment.

My guess is that we might be able to change that once we try to implement the multiple persistence units support in Hibernate Reactive but this is not coming soon.

**Comment by mkouba** [comment]
> I had a look and I don't see an easy way out given the way Hibernate Reactive is initialized at the moment.
> 
> My guess is that we might be able to change that once we try to implement the multiple persistence units support in Hibernate Reactive but this is not coming soon.

In that case, we should do what Michal suggested...

**Comment by mkouba** [comment]
@michalszynkiewicz shouldn't this be closed by https://github.com/quarkusio/quarkus/pull/24420? I don't think that we should add this to the docs given the fact that the `RecorderBeanInitializedBuildItem` is deprecated.

**Comment by michalszynkiewicz** [comment]
forgot to close it, thanks @mkouba
