### ISSUE TITLE
CDI issue with avro after migration to Quarkus 2.7

### ISSUE THREAD

**Issue by jumolinaro** [quarkusio/quarkus#24452]
### Describe the bug

We have a Quarkus application with **Java** and **Kotlin** sources.
This component contains an avro file used to produce messages for Kafka

Gradle build of this application works perfectly with Quarkus 2.6 (2.6.3.Final)
But after migration to Quarkus 2.7 (2.7.5.Final), gradle build fails with some dependencies injection issues (see below)

It seems that some classes generated from Kotlin sources are not found by @Inject annotation used in classes generated from Java sources.

If we remove avro generation from this component, gradle build works fine.

### Expected behavior

> Task :quarkusBuild
Caching disabled for task ':quarkusBuild' because:
  Build cache is disabled
Task ':quarkusBuild' is not up-to-date because:
  Task has failed previously.
building quarkus jar

> Task :quarkusBuild
Quarkus augmentation completed in 6991ms
:quarkusBuild (Thread[Execution worker for ':',5,main]) completed. Took 8.685 secs.
:assemble (Thread[Execution worker for ':',5,main]) started.

> Task :assemble
Skipping task ':assemble' as it has no actions.
:assemble (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:check (Thread[Execution worker for ':',5,main]) started.

> Task :check
Skipping task ':check' as it has no actions.
:check (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':',5,main]) started.

> Task :build
Skipping task ':build' as it has no actions.
:build (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.

BUILD SUCCESSFUL

### Actual behavior

> Task :quarkusBuild FAILED
:quarkusBuild (Thread[Execution worker for ':',5,main]) completed. Took 10.161 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 8 deployment problems:
Unsatisfied dependency for type xxx.xxx.MonitoringEventService and qualifiers [@Default]
        - java member: xxx.xxx.XxxxService#monitoringEventService
        - declared on CLASS bean [types=[xxx.xxx.XxxxService, java.lang.Object], qualifiers=[@Default, @Any], target=xxx.xxx.XxxxService]

### Output of `java -version`

11.0.10

### Quarkus version or git rev

2.7.5.Final

**Comment by gsmet** [comment]
I think we will need a small reproducer for that one.

**Comment by jumolinaro** [comment]
Hi @gsmet, 
I totally agree with you.

So here is a small reproducer with 3 files (1 avro, 1 java & 1 kotlin)
https://github.com/jumolinaro/quarkus-issue-24452

In this reproducer, usage of Avro is not useful (no messages sent to Kafka) but it reproduces the current issue.

**Comment by mkouba** [comment]
> So here is a small reproducer with 3 files (1 avro, 1 java & 1 kotlin)

I can take a look...

**Comment by aloubyansky** [comment]
@glefloch will you have time to look into what happens there on the plugin level?

**Comment by glefloch** [comment]
yes sure.

**Comment by glefloch** [comment]
The devmode is quarkus, I think the problem comes from a missing source path in the model. I will push a fix.

**Comment by mkouba** [comment]
> The devmode is working, I think the problem comes from a missing source path in the model. I will push a fix.

Hm, that's interesting... it's usually the other way around - a problem in dev mode but not in prod mode ;-).
