### ISSUE TITLE
Job scheduling in Quarkus

### ISSUE THREAD

**Issue by HugoVinhal98** [quarkusio/quarkus#24453]
### Description

So I am using ManagedScheduledExecutorService in a Java EE project that I am migrating to Quarkus, like so:

```
@Resource
private ManagedScheduledExecutorService scheduler;
``` 

The only thing I need from this dependency is to be able to schedule a command, by invoking the `shedule` function:

```
this.scheduler.schedule(this::refreshToken, TENTATIVE_LOGIN_IN_SECONDS, TimeUnit.SECONDS);
```

Is there any way I can achieve this in Quarkus?

**Comment by mschorsch** [comment]
https://quarkus.io/guides/scheduler

**Comment by machi1990** [comment]
@HugoVinhal98 you can use the scheduler extension as @mschorsch mentioned.
