### ISSUE TITLE
Expose metrics in a UI similar to what we have with Swagger UI for the endpoints

### ISSUE THREAD

**Issue by SamyBacha** [quarkusio/quarkus#2445]
----- English version -----

Hello,

I advice you to integrating in the way of swagger-ui, a "metrics-ui" in order to see properly different metrics of the application

Best Regard

BACHA Samy

----- French version -----

Bonjour,

Suite au JUG Paris du 14/05/2019 je vous propose comme convenu de penser à intégrer à la façon de swagger-ui un metrics-ui qui permettra du gagner de temps et aux dev back-end de voir proprement les différentes metrics de leur applications.

Cdt

BACHA Samy

**Comment by geoand** [comment]
@SamyBacha Although there are plenty of people that can understand French working on the project, would it be possible for you to convert to English since chances are that more people will be able to understand it?

Thanks

**Comment by phillip-kruger** [comment]
As a start we can add the `/metrics` endpoint(s) - similar to what we have done for `/health`. (see #12044 )
w.d.y.t ?

**Comment by geoand** [comment]
With the use of micrometer as the default for metrics, I think this has been covered. Right @ebullient ?
