### ISSUE TITLE
List applicable param converters for resteasy reactive endpoints in dev ui

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#24464]
### Description

I need to write a custom param converter for json.
Out of curiosity, I wanted to see which priority the built in converters have, so that mine could have a lower one.

Therefore, it would be nice if for each endpoint the applicable param converters (with their priority) are listed in dev ui.

This request is similar to #24342. where a list of exception mappers was added to each endpoint.

**Comment by geoand** [comment]
Good idea, I'll have a look
