### ISSUE TITLE
bootstrap config with field does not pick up QUARKUS_CONFIG_LOCATIONS files

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#24465]
### Describe the bug

If I define a property in a file referenced by QUARKUS_CONFIG_LOCATIONS , it will not be picked up if part of a config object with phase `BOOTSTRAP`. it works fine with `RUN_TIME`.

### Expected behavior

The value should be taken into account as if it was defined in the classpath's application.properties.

### Actual behavior

The value is ignored.

### How to Reproduce?

Define the following config object in an extension:
```
@ConfigRoot(name = "hello", phase = ConfigPhase.BOOTSTRAP)
public class HelloConfig {

    /**
     * doc
     */
    @ConfigItem(name = "map")
    public Map<String, MapConfig> map;

    @Override
    public String toString() {
        return "HelloConfig{" + "map=" + map + '}';
    }

    @ConfigGroup
    public static class MapConfig {

        /**
         * doc
         */
        @ConfigItem(name = ConfigItem.PARENT)
        String value;

        public MapConfig(String value) {
            this.value = value;
        }

        public MapConfig() {
            value = "";
        }

        @Override
        public String toString() {
            return "MapConfig{" + "value=" + value + '}';
        }
    }
}
```

Create a recorder:
```
@Recorder
public class HelloRecorder {

    private final HelloConfig config;

    public HelloRecorder(HelloConfig config) {
        this.config = config;
    }

    public void sayHello(String name) {
        System.out.println("==> Hello" + name+" with config " + config);
    }
}
```

And a build step:
```
    @Record(ExecutionTime.RUNTIME_INIT)
    @BuildStep
    public void helloBuildStep(HelloRecorder recorder) {
        recorder.sayHello("World");
    }
```

In the src/main/resources/application.yaml: 
```
quarkus:
  hello:
    map:
      mytest: foo
```

In a directory create a .env with:
```
QUARKUS_CONFIG_LOCATIONS=base-application.properties
```

And create `base-application.properties` with:
```
# ordinal between application.properties in classpath (250) and ./config/application.properties (260)
config_ordinal=255

quarkus.hello.map.mytest=bar
```

Compile and start the application:
```
$ java  -jar ../target/quarkus-app/quarkus-run.jar
==> HelloWorld with config HelloConfig{map={mytest=MapConfig{value=foo}}}
```

The value `foo` comes from the `src/main/resources/application.yaml`, which means the `base-application.properties` has been ignored.

Now change the config phase to `RUN_TIME`:
```
@ConfigRoot(name = "hello", phase = ConfigPhase.RUN_TIME)
public class HelloConfig {
```

Compile and relaunch:
```
$ java  -jar ../target/quarkus-app/quarkus-run.jar
==> HelloWorld with config HelloConfig{map={mytest=MapConfig{value=bar}}}
```

Now the `bar` value is correctly picked up.
I have tried also with a normal field (i.e. not a `Map`), and the behavior is the same. So it is essentially related to boostrap config vs runtime.

May also be related to https://github.com/quarkusio/quarkus/issues/24463
see https://quarkusio.zulipchat.com/#narrow/stream/294206-smallrye/topic/Map.20config.20env.20variable.20override
cc @radcortez 

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19042 DEVPC028554 3.1.4-340.x86_64 2020-05-19 12:55 UTC x86_64 Msys

### Output of `java -version`

OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by geoand** [comment]
Does this work if you specify `QUARKUS_CONFIG_LOCATIONS` as an env var or system property?
Asking because IIRC, `.env` does not work for bootstrap configuration

**Comment by vsevel** [comment]
no, this does not change anything:
```
$ java -Dquarkus.config.locations=base-application.properties  -jar ../target/quarkus-app/quarkus-run.jar
==> HelloWorld with config HelloConfig{map={mytest=MapConfig{value=foo}}}
```

This should be `value=bar`. If I change the config phase to be `RUN_TIME`, this works.

**Comment by vsevel** [comment]
@radcortez I could not get it to work from a file `application-default.properties` referenced by env variable `QUARKUS_CONFIG_LOCATIONS: /app/application-default.properties` with content:
```
config_ordinal=255
quarkus.vault.secret-config-kv-path.ad_account=my/path/in/vault
```

It does work however if I add system property `-Dquarkus.vault.secret-config-kv-path.ad_account=my/path/in/vault`.
I was thinking this would work with this issue and https://github.com/quarkusio/quarkus/issues/24463
Is this expected?

**Comment by radcortez** [comment]
I'll have to look.

**Comment by radcortez** [comment]
The fix was missing a piece. Unfortunately, the test that I wrote didn't take into account config recording from build time so it seemed to be working.

Can you try it with https://github.com/quarkusio/quarkus/pull/25351? Thanks!

**Comment by vsevel** [comment]
I have been trying to recompile the `2.9` branch, and I am getting:

```
$ ./mvnw -Dquickly

[ERROR] Failed to execute goal io.quarkus:quarkus-platform-bom-maven-plugin:0.0.40:generate-platform-descriptor (default) on project quarkus-bom-quarkus-platform-descriptor: The following categories referenced from extensions are missing from the generated catalog: configuration, http, websockets -> [Help 1]
```

**Comment by radcortez** [comment]
Maybe try `clean` first to make sure you don't have old stuff sitting around?

**Comment by vsevel** [comment]
I ended trying it with `2.9.0.Final`. 
because I could get it to work...
I removed the env variable `QUARKUS_VAULT_URL=https://xx.svc:8200` and replaced it with a property `quarkus.vault.url=https://xx.svc:8200` in out `application-default.properties` referenced by env variable `QUARKUS_CONFIG_LOCATIONS=/app/application-default.properties` . but that did not work.
then I moved ``quarkus.vault.url` in the regular `application.yaml`, and that worked.
@radcortez is the fix supposed to be in `2.9.0`? thanks.

**Comment by radcortez** [comment]
> @radcortez is the fix supposed to be in `2.9.0`? thanks.

I believe it was backported.

**Comment by geoand** [comment]
As indicated by the milestone, it was backported

**Comment by vsevel** [comment]
ok. let me try to do a reproducer then.

**Comment by vsevel** [comment]
good news: this works as expected with a test extension, or even the vault extension.
this must be something we are doing in our business app or its deployment (or it is a different issue). I am going to keep searching.
thanks a lot for your help @radcortez

**Comment by radcortez** [comment]
Great! :)

**Comment by vsevel** [comment]
so I confirm everything works as expected on the business app with the vault properties all in a separate file referenced by `QUARKUS_CONFIG_LOCATIONS`  with `config_ordinal=255`.
sorry to have doubted you @radcortez ;-)

**Comment by radcortez** [comment]
No need to be sorry. I make a lot of mistakes :)
