### ISSUE TITLE
Integrate with transactional/promotional e-mail providers 

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#24462]
### Description

It would be nice if `quarkus-mailer` could introduce an extension point so extensions could integrate with some major e-mail campaign providers out there (eg. Amazon Simple Email Service, Postmark, Mailjet, and SendGrid).

### Implementation ideas

It would be interesting if other extensions could provide a `Mailer`/`ReactiveMailer` implementation (through some new Build items perhaps or by introducing an SPI in `quarkus-mailer` ?).

This would allow the `ses` extension in https://github.com/quarkiverse/quarkus-amazon-services/tree/main/ses to provide a `SeSMailer` implementation, for example.

**Comment by cescoffier** [comment]
While I understand the idea, I do not believe we need this extension as the underlying mailer is enough to integrate with the provider you mention. Do I miss something obvious?
