### ISSUE TITLE
Some nicer way to configure data sources than URLs

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2448]
It would be nice if we had some kind of smart configuration that could assemble JDBC URLs for us.  Every JDBC driver has different features and syntax and it's really annoying to have to look it up in a special guide.

So we should have some generic properties that apply to all data sources, like a host list, instance name, user name, and password, along with a "data source type" indicator.  Special properties are OK too for certain databases, as long as we're clear in indicating that the property only applies for certain types and maybe giving a warning if they're provided for an unsupported database.

**Comment by cricket007** [comment]
At a bare mimumum, a basic pattern is just this right? 

```
jdbc:[protocol]://([user@credentials])?([host(:[port])?])*[extras]
```

I put hosts as plural because [cases like HiveServer2 via Zookeeper](https://cwiki.apache.org/confluence/display/Hive/HiveServer2%2BClients#HiveServer2Clients-ConnectionURLFormat)

**Comment by stuartwdouglas** [comment]
@gsmet can this be closed?

**Comment by geoand** [comment]
I think we should close this as users seem to be perfectly content with using a URL
