### ISSUE TITLE
Multiple header when use ResponseEntity.status(200).header("content-type","xxx")

### ISSUE THREAD

**Issue by liangyuanpeng** [quarkusio/quarkus#24481]
### Describe the bug

Return multiple header of content-type

### Expected behavior

Only one header of `Content-Type` and rewrite it when we use some code like that `ResponseEntity.status(200).header("content-type","application/jsonhello").build();`

### Actual behavior

Multiple header of `Content-Type`

### How to Reproduce?

Some simple code, use spring web for API.
```java
 @GetMapping("/hello")
    public ResponseEntity<BaseResponse> hello(){
        return ResponseEntity.status(200).header("content-type","application/jsonhello").build();
    }
```

Run the application and request this API. 

```shell
oem@lan:~$ curl -X GET http://localhost:8080/hello -I
HTTP/1.1 200 OK
Content-Type: application/json
Content-Type: application/jsonhello
content-length: 0
```  

### Output of `uname -a` or `ver`
```
Linux lan 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
### Output of `java -version`
```
openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 20.3.4 (build 11.0.13+7-jvmci-20.3-b24) OpenJDK 64-Bit Server VM GraalVM CE 20.3.4 (build 11.0.13+7-jvmci-20.3-b24, mixed mode, sharing)
```

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/oem/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.13, vendor: Eclipse Adoptium, runtime: /home/oem/soft/jdk-11.0.13+8 Default locale: zh_CN, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-58-generic", arch: "amd64", family: "unix"
```
### Additional information

```
quarkus.platform.version 2.7.3.Final
```

**Comment by geoand** [comment]
I was not able to reproduce this problem and even added a test in https://github.com/quarkusio/quarkus/pull/24489 to validate that we follow the proper behavior.

**Comment by liangyuanpeng** [comment]
@geoand  Thanks for your work and quick reply. I have try to do the same test for my code and unit test working for me, but i really got the two same header when i after started application.   now, my quarkus version is `2.7.5.Final.`

My test code:
```java
    @Test
    public void headerTest(){
        given()
                .when().get("/hello")
                .then()
                .statusCode(200)
                .header("content-type","application/jsontest")
                .header("custom-header","value");
    }
```

API method code:
```java
    @GetMapping("/hello")
    public ResponseEntity<BaseResponse> hello(){
        return ResponseEntity.status(200).contentType(org.springframework.http.MediaType.valueOf("application/jsontest")).header("custom-header","value").build();
    }
```

**Comment by geoand** [comment]
Thanks, let me check

**Comment by geoand** [comment]
I updated the PR to use your latest code and again everything works as expected

**Comment by liangyuanpeng** [comment]
Yes,unit test is working, but request to the really API, it in the wrong side.

This is the min reproduce code.
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8331033/code-with-quarkus.zip)

**Comment by geoand** [comment]
Now I see what the confusion is. You are using `quarkus-resteasy-jackson` while I am using `quarkus-resteasy-reactive-jackson`.
I don't think we will be providing any fixes for Spring Web support on RESTEasy Classic, so best switch to RESTEasy Reactive.

Thanks

**Comment by liangyuanpeng** [comment]
Thanks for your confirmed, Change `quarkus-resteasy-jackson` to `quarkus-resteasy-reactive-jackson`and it working for me.
