### ISSUE TITLE
Introduce type and config converter for memory sizes

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2451]
The idea is to have a type for data sizes.  It would recognize strings in this format (shown as a regular expression):

```regex
[0-9]+[KkMmGgTtPpEeZzYy]?
```
If no suffix is given, assume bytes.  I would also say that we should we should probably disregard [IEC binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) unless we want to annoy 90% of our users (and make the other 10% insufferably smug).

**Comment by dmlloyd** [comment]
Use cases:

* Native image GC and stack size settings
* Log rotation threshold

**Comment by gsmet** [comment]
@machi1990 would you be interested in taking this one?

The converter can already be written but I think we need to wait for #2399 to go in for the declaration as it changes the way converters are declared.
