### ISSUE TITLE
Introduce lenient Duration converter

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2452]
The Converter should accept values which start with a number by implicitly appending a `PT` to them.  If the value consists *only* of a number, it should implicitly treat the value as seconds.

**Comment by gsmet** [comment]
@machi1990 would you be interested in taking this one?

The converter can already be written but I think we need to wait for https://github.com/quarkusio/quarkus/pull/2399 to go in for the declaration as it changes the way converters are declared.

**Comment by machi1990** [comment]
@gsmet sure. 

I'll have a look once https://github.com/quarkusio/quarkus/pull/2399 lands.

**Comment by machi1990** [comment]
@gsmet @dmlloyd I started working on this issue. Your early feedback is welcomed.
