### ISSUE TITLE
Maven native-image build failure after upgrading to 2.7.5

### ISSUE THREAD

**Issue by fage88** [quarkusio/quarkus#24547]
### Describe the bug

I made a post on stackoverflow about an native build issue I encountered in Quarkus 2.7.5.Final https://stackoverflow.com/questions/71608733/maven-error-building-quarkus-native-image-java-nio-file-accessdeniedexception?noredirect=1#comment126560141_71608733

On my local environment (windows) as well as on github hosted Ubuntu runners I was able to build native images without issue.
However, when I switched over to using self hosted github runners I got this exception using GraalVM 22.0.0.2, Java 11.0.14, Maven 3.8.4 and Quarkus 2.7.5
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:build (default) on project prime-platform: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /./target
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:891)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.nio.file.AccessDeniedException: /./target
[ERROR]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[ERROR]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[ERROR]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[ERROR]         at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
[ERROR]         at java.base/java.nio.file.Files.createDirectory(Files.java:690)
[ERROR]         at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
[ERROR]         at java.base/java.nio.file.Files.createDirectories(Files.java:783)
[ERROR]         at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeGeneratedSchema(SmallRyeOpenApiProcessor.java:694)
[ERROR]         at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:945)
[ERROR]         at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:653)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR]         ... 6 more
[ERROR] -> [Help 1]
```
I rolled back to 2.7.4 and was able to build on my self hosted runners without issue.
I also rolled forward to 2.8.0.CR1 and was able to build without isssue.
This issue seems to only affect 2.7.5.Final

### Expected behavior

Building a native image using `mvn -U clean package -DskipTests -Pnative` run to completion without throwing exceptions on all OS/Platforms

### Actual behavior

Some Linux distributions throw a `java.nio.file.AccessDeniedException: /./target` exception

### How to Reproduce?

I am unsure of which Linux distributions can/can't reproduce this but I was able to reproduce this on a Ubuntu 20 VM by running `mvn -U clean package -DskipTests -Pnative`

### Output of `java -version`

11.0.14

### GraalVM version (if different from Java)

22.0.0.2

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

This issue seems to only affect 2.7.5 and not 2.7.4 or 2.8.0.CR1

**Comment by geoand** [comment]
@phillip-kruger (or maybe @aloubyansky ?) do you think you can open a PR against the 2.7 branch?

**Comment by aloubyansky** [comment]
I am not sure what fixed it in 2.8.0.CR1 yet. @phillip-kruger do you know?

**Comment by aloubyansky** [comment]
@fage88 is there a chance you could provide a reproducer for us? Thanks.

**Comment by fage88** [comment]
Hi @aloubyansky 

What would you need in a "reproducer" I think you would be able to reproduce this with any Quarkus project.  Are you looking for a container running linux or something?

**Comment by fage88** [comment]
sure, I won't be able to get to this until after work hours, but I should be able to slap something together

**Comment by fage88** [comment]
Hi @aloubyansky,

I am very puzzled. I made a copy of the getting-started application and used that as my recreator, but low and behold I couldn't recreate the issue.

Then I went ahead and upgrade my project to 2.7.5.Final again and the entire CI/CD pipeline ran without any issue.

I **KNOW** this was a problem when I logged the bug, but I can't explain why it isn't anymore.

**Comment by phillip-kruger** [comment]
Great !! let's close :)
