### ISSUE TITLE
Update quarkus.quartz.datasource documentation

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#24542]
### Describe the bug

The documentation https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzBuildTimeConfig.java#L46 is referring to `db` store which has long been deprecated and removed. 
We should update the javadoc to refer to `jdbc-tx` or `jdbc-cmt` job stores instead.

### Expected behavior

There is no mention of `db` store in the Quarkus documentation

### Actual behavior

`db` store is still mentioned

### How to Reproduce?

Go to https://quarkus.io/guides/quartz#quarkus-quartz_quarkus.quartz.datasource and observe the `db` in the description.

**Comment by machi1990** [comment]
@VanillaSpoon would you be interested in fixing this?

**Comment by VanillaSpoon** [comment]
Yea, I'd love to. Thanks @machi1990

**Comment by machi1990** [comment]
Thanks

**Comment by kanha-gupta** [comment]
Hey can i fix this if not fixed yet ? would be really glad

**Comment by VanillaSpoon** [comment]
Hey @kanha-gupta :) this has been resolved since. Just needs to be marked as closed. Would you like me to tag you if there are similar issues in the future?

**Comment by kanha-gupta** [comment]
> Hey @kanha-gupta :) this has been resolved since. Just needs to be marked as closed. Would you like me to tag you if there are similar issues in the future?

Yes please i would love to :)
