### ISSUE TITLE
NullPointerException on custom consraint validator when injecting a config mapping at startup

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#24540]
### Describe the bug

I am unable to start quarkus when i try to inject a ConfigMapping into a Hibernate validator constraint.

getting a quite big exception;
```
2022-03-24 13:04:14,650 WARN  [io.qua.arc.impl] (Quarkus Main Thread) An error occurred during delivery of the @BeforeDestroyed(ApplicationScoped.class) event: javax.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.scheduler.runtime.SchedulerContext not initialized yet: io_quarkus_scheduler_runtime_SchedulerContext_97d170e1550eee4afc0af065b78cda302a97674c

...

Caused by: java.lang.NullPointerException: Cannot invoke "javax.validation.Validator.forExecutables()" because the return value of "io.smallrye.config.validator.BeanValidationConfigValidator.getValidator()" is null

```

### Expected behavior

I should be able to inject a config in a constraint validator

### Actual behavior

App crashes on start

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-validator-reproducer

Step to reproduce;
1- Start the app

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

openjdk version "17.0.2"

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

**Comment by manofthepeace** [comment]
Using this works, but I am unsure why, and unsure if a fix would be needed in quarkus;

```
    @Inject
    @WithCaching
    Instance<MyConfig> config;
```

**Comment by gsmet** [comment]
@radcortez didn’t you fix something similar recently?

**Comment by radcortez** [comment]
Yes, I've added support for `Instance` injection.

The issue here is a circular dependency between the config mapping and the Validator. Because the Validator is available, we will try to validate the mapping, but the Validator tries to create the ConstraintValidator implementations, which injects a mapping class. I'm not sure if we can do something about this. Maybe something that allows you to skip the Validator on the mapping side.

**Comment by radcortez** [comment]
We can probably be a little more smart and only try to validate the mapping if there are actual Validation annotations in it.

**Comment by radcortez** [comment]
Another option would be to create a specific Validator instance just for the Config Mappings.

**Comment by manofthepeace** [comment]
Thanks for your explanation it is very clear. The error message on the other hand, really not, I would never have guessed that. A big exception chain until a NPE. Would be nice to at least detect those case so the error could be communicated better. This way it could probably be left as is.

In my case the first option I believe would not work since I do validate the config itself, but I do use that config, in a class validator, to validate stuff coming from a remote api as well. So I think having 2 validator could do the trick, or document somehow that Instance<> is needed. I was a bit lucky in my google foo to find that.

**Comment by gsmet** [comment]
@radcortez I thought about it a bit more and I think creating a second Validator instance might be harder than expected. Especially if you plan to make it work in native. Initializing a `ValidatorFactory` that works in native requires some special care.

I think having an error message in `io.smallrye.config.validator.BeanValidationConfigValidator.getValidator()` ends up being null which pushes users to use `Instance` might be easier.

**Comment by radcortez** [comment]
Sounds good.

**Comment by gsmet** [comment]
@radcortez I started ported the Hibernate Validator config to `@ConfigMapping` and do you see what's coming? Obviously, the `Validator` is not available when creating the config and we hit a wall.

Having an error message doesn't make sense in that case as it's perfectly valid.

**Comment by radcortez** [comment]
Hum... yes.

We need to consider some options:

- Have Config define its annotations and eliminate Bean Validation in Config. This is the cleanest approach, but it would duplicate a lot of stuff and probably confuse users.
- Provide a separate instance of Bean Validator for Config only. I know you said that it might be hard, but probably this is the most transparent solution.

**Comment by gsmet** [comment]
@radcortez it's a bit orthogonal to the discussion but could we disable Bean Validation entirely for the core config or would it be too complicated?

As for building your own BeanValidation factory, the only difficulty is that you need to have the full list of classes that will be validated (i.e. `@ConfigMapping` classes but also what will be considered `@ConfigGroup`). If you have it handy, it's doable.

**Comment by radcortez** [comment]
> @radcortez it's a bit orthogonal to the discussion but could we disable Bean Validation entirely for the core config or would it be too complicated?

We don't have that ability. The Config itself does not make any distinction between Quarkus config or Applicaiton config. It would be possible to provide a way to tell Config to just validate specific mappings, but I'll need to add as a feature.

> As for building your own BeanValidation factory, the only difficulty is that you need to have the full list of classes that will be validated (i.e. `@ConfigMapping` classes but also what will be considered `@ConfigGroup`). If you have it handy, it's doable.

We have all of that on the Config side. We can easily provide that list.

**Comment by radcortez** [comment]
I've started some work to see how far how could go with a separate Validator in: https://github.com/quarkusio/quarkus/pull/32586.

It seems to work, but it still has a lot of cleaning to do, and I am getting some issues with native.
