### ISSUE TITLE
resteasy-codestart is picked instead of rest-client-codestart when generating project with rest-client extension

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24552]
### Describe the bug

resteasy-codestart is picked instead of rest-client-codestart when generating project with rest-client extension, e.g.`mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client`

generated code is for sample JAX-RS endpoint, log also says resteasy-codestart

```
applying codestarts...
[INFO] 📚  java
🔨  maven
📦  quarkus
📝  config-properties
🔧  dockerfiles
🔧  maven-wrapper
🚀  resteasy-codestart
[INFO]
```

### Expected behavior

`🚀  rest-client-codestart` gets picked

### Actual behavior

`🚀  resteasy-codestart` is picked

### How to Reproduce?

 - run `mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client`
 - check `applying codestarts...` section in the console log

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.5.Final

**Comment by rsvoboda** [comment]
Wow, rest-client-codestart gets picked up when using `-DquarkusRegistryClient=false` in the command

e.g. `mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client -DquarkusRegistryClient=false`

**Comment by rsvoboda** [comment]
CC @ia3andy / @maxandersen

**Comment by ia3andy** [comment]
I can't reproduce :-/ :
```
~/Demo> mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.7.5.Final:create (default-cli) @ standalone-pom ---
[INFO] -----------
[INFO] selected extensions:
- io.quarkus:quarkus-rest-client

[INFO]
applying codestarts...
[INFO] 📚  java
🔨  maven
📦  quarkus
📝  config-properties
🔧  dockerfiles
🔧  maven-wrapper
🚀  rest-client-codestart

**Comment by rsvoboda** [comment]
ok, can be connected to my confug.yaml, let me check

**Comment by rsvoboda** [comment]
ok, it's related to the content of `.quarkus/config.yaml` (doing some experiments for info/update goals of quarkus maven plugin)

I can reproduce the problem because I have
```yaml
---
registries:
- registry.quarkus.redhat.com
- registry.quarkus.io
```

So I end up with 2.2.5 based application, gosh.

**Comment by rsvoboda** [comment]
And rest client codestart was added in 2.5 - https://github.com/quarkusio/quarkus/pull/21229

**Comment by rsvoboda** [comment]
Closing
