### ISSUE TITLE
Smallrye Config NoSuchMethodError

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#24560]
### Describe the bug

Hello, I have recently upgraded my Quarkus version to 2.7.5 and all Quarkus packages along with it. I have come to a strange issue in which I am receiving in my Gradle "test" phase and also when I run the application locally that I can only assume has to do with reactive messaging from what I can tell from the very limited stack trace. Can I get some assistance in understanding what is wrong here? I have not changed anything after the version uplift (2.6->2.7). The only library that I am using from `io.smallrye.config` is **ConfigMapping** to obtain values from my application properties file.

You may reference this post with the one I did in reactive messaging's GitHub: [#1609](https://github.com/smallrye/smallrye-reactive-messaging/issues/1609)

So far, the only way to circumvent this (for me) is to force the `io.smallrye.config` version to **2.9.0**.

`
ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoSuchMethodError: io.smallrye.config.ConfigValue.getNameProfiled()Ljava/lang/String; at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:407) at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:263) at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:179) at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104) at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328) at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252) at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60) at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92) at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455) at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66) at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150) at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106) at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132) at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
`

### Expected behavior

For the application to start normally, as it did with previous versions.

### Actual behavior

`ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoSuchMethodError: io.smallrye.config.ConfigValue.getNameProfiled()Ljava/lang/String; at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:407) at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:263) at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:179) at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104) at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328) at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252) at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60) at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92) at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455) at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66) at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150) at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106) at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132) at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)`

### How to Reproduce?

Create a fresh Quarkus Application (2.7.5) with **reactive messaging**, create a **ConfigMapping** interface to load values from the application properties file and attempt to run the application. 

### Output of `java -version`

11

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by radcortez** [comment]
I've tried to reproduce this by creating a new project with `code.quarkus.io`, with the reactive messaging extension plus kafka. Added a mapping and it worked fine.

Can you please provide your own reproducer? Thanks!

**Comment by geoand** [comment]
Closing as we never got a reproducer
