### ISSUE TITLE
Unsatisfied dependency with quarkus-arc not happening with Weld

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#2456]
I am currently stuck in a project migration from Thorntail to Quarkus because the following type of injection (classes changed for example purpose) is not working with quarkus-arc:0.15.0 while there's no problem with Weld.

```
public abstract class Vehicle<T extends Engine> {
	@Inject
	private T engine;
}

public interface Engine {}

@Dependent
public class PetrolEngine implements Engine {}

@ApplicationScoped
public class Car extends Vehicle<PetrolEngine> {}
```

The following exception is thrown during a Quarkus build (with the Gradle plugin):

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type T extends main.java.Engine and qualifiers [@Default]
        - java member: main.java.Vehicle#engine
        - declared on CLASS bean [types=[main.java.Vehicle<main.java.PetrolEngine>, main.java.Car, java.lang.Object], qualifiers=[@Default, @Any], target=main.java.Car]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:378)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:361)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:268)
        ... 12 more
```

I reproduced this in the following repository: https://github.com/gwenneg/quarkus-unsatisfied-dependency.

Run the ` ./gradlew clean build --stacktrace` command to see the error happening.

Is this an expected behavior from quarkus-arc?

**Comment by manovotn** [comment]
Doesn't seem expected to me, it looks like the IP didn't inherit the proper type (e.g. operates on `T` rather then `PetrolEngine`).

As a side note, you should try and avoid using `private` members (`private T engine`) in order for Substrate VM to work better. Take a look here https://quarkus.io/guides/cdi-reference#private-members

**Comment by manovotn** [comment]
Hmm the gradle build wasn't working for me for some reason, so I cobbled together a Maven equivalent inside Arc testsuite - https://github.com/manovotn/quarkus/tree/issue2456

**Comment by gwenneg** [comment]
Yes, I removed all `private` modifiers from my real project but I forgot to do it in the reproducer. Thanks for the reminder!

Old habits die hard...
