### ISSUE TITLE
Maven config with "quarkus.version" property results in WARNING log message

### ISSUE THREAD

**Issue by shumonsharif** [quarkusio/quarkus#24577]
### Describe the bug

When having a property named `quarkus.version` in the Maven pom.xml file, the following warning gets printed during the regular build process.

```[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.version" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo```

### Expected behavior

No WARNING message should appear in the logs.

### How to Reproduce?

A reproducer project has been attached.

Run the following to see the WARNING log message getting printed:
```./mvnw clean install -Dquarkus.version=2.8.0.CR1```

Run the following to see no WARNING getting printed with previous Quarkus versions:
```./mvnw clean install -Dquarkus.version=2.7.5.Final```

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8359129/code-with-quarkus.zip)

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/ssharif/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.13, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.3.0/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "11.6.4", arch: "x86_64", family: "mac"

**Comment by famod** [comment]
FWIW, same happens even for some of Quarkus' own "properties", e.g. https://github.com/quarkusio/quarkus/blob/2862bef1fdb52093eab15762941b4c68ffb8438d/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L253

PS: This has been the case of a long time. There are more such messages on `main`, but I think that has another cause.

**Comment by gsmet** [comment]
@famod do you have examples of such new messages and where they occur?

**Comment by shumonsharif** [comment]
> PS: This has been the case for a long time. There are more such messages on main, but I think that has another cause.

If you download the raw logs for any of the successful `main` builds (eg. [this one](https://github.com/quarkusio/quarkus/runs/5706695276)), and run the following command, a fairly large number of quarkus properties show up.

```perl -lne '/Unrecognized configuration key "(.+?)" was/&&print $1' * | sort | uniq```

**Comment by radcortez** [comment]
This is caused by https://github.com/quarkusio/quarkus/pull/23943 added to warn the used during build time about unknown properties.

Unfortunately, we don't control the properties that users add to their build scripts like `quarkus.version` so it will report as unused because it is in the quarkus namespace. The fixing PR is ignoring properties coming from the build script, so it should fix most of the warnings.

It is likely that the build script will still show some warning (some are tests) and some are probably extensions or integration tests that refer to configuration properties not expected during the build.
