### ISSUE TITLE
ClassCastException in mutiple Module project

### ISSUE THREAD

**Issue by guoxunbo** [quarkusio/quarkus#24578]
### Describe the bug

The exception like this:
```java
 class com.*.imfg.prp.domain.model.ProcessFlow cannot be cast to class com.*.imfg.core.domain.model.BaseEntity (com.*.imfg.prp.domain.model.ProcessFlow is in unnamed module of loader 'app'; com.*.imfg.core.domain.model.BaseEntity is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4dd6fd0a)
```
- The ProcessFlow is intance of BaseEntity.but when I cast it to baseEntity. I got this error.
- So I write a test to this.but I also get false. why?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/14329149/160316709-90380825-8d38-45cd-a69d-1ee5ef086810.png">
- my project like this
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/14329149/160316875-b9b519ab-1ebe-4aed-83cd-7ece278e004e.png">

### Output of `java -version`

17

### Quarkus version or git rev

2.7.2.Final

**Comment by guoxunbo** [comment]
The object o is processFlow object. but I got false.
If I cast o to baseEntity.then I got this error

**Comment by guoxunbo** [comment]
- There is a demo to show it. But I don't konw why?
[demo.zip](https://github.com/quarkusio/quarkus/files/8359509/demo.zip)
- There is the demo snapshot photo. 
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/14329149/160323748-461ab475-0dc9-4a1e-92a6-a62f2cdee1e7.png">

**Comment by famod** [comment]
I'm not 100% sure I understand your use case, but if you change
```java
clazz = ClassLoader.getSystemClassLoader().loadClass(name);
```
to
```java
clazz = Thread.currentThread().getContextClassLoader().loadClass(name);
```
it works!

(Unwritten) rule of thumb in Quarkus: Try the TCCL first. 😉

**Comment by guoxunbo** [comment]
@famod 👍.oh. Nice. Thank's a lot.
It's slove it.I will remember TCCLforever.
