### ISSUE TITLE
quarkus-resteasy-jsonb deserializes collection of Enums as collection of Strings.

### ISSUE THREAD

**Issue by tomh2013** [quarkusio/quarkus#2457]
Quarkus version 0.15.0

An enum type and a class containing a Set of the enum type are defined below.

public enum DummyEnum {
	XXX;
}

public final class DummyObject {

	private final Set<DummyEnum> _enums = new HashSet<>();
	
	@JsonbCreator
	public DummyObject(
			@JsonbProperty("enums") final Set<DummyEnum> enums) {
		_enums.addAll(enums);
	}
	
	public Set<DummyEnum> getEnums() {
		return _enums;
	}
}

The following test attempts to serialize an instance of the class to a JSON string and then deserialize it back to an object.

public class TestDummyObject {

	@Test
	public void testThatADummyObjectCanBeSerialized() {
		
		// Given
		final Jsonb jsonb = JsonbBuilder.create();
		final Set<DummyEnum> enums = EnumSet.of(DummyEnum.XXX);
		final DummyObject expected = new DummyObject(enums);
		
		// When
		final String jsonString = jsonb.toJson(expected);
		final DummyObject actual = jsonb.fromJson(jsonString, DummyObject.class);
		
		// Then
		final Set<DummyEnum> actualEnums = actual.getEnums();
		Assertions.assertEquals(DummyEnum.class, actualEnums.iterator().next().getClass());
	}

The test throws a ClassCastException when attempting to evaluate the assertion:

java.lang.ClassCastException: java.lang.String cannot be cast to com.dummy.DummyEnum

This indicates that the run time contents of the Set "actualEnums" are actually Strings and not of type DummyEnum.

[jsonb-fail.zip](https://github.com/quarkusio/quarkus/files/3185331/jsonb-fail.zip)

**Comment by gsmet** [comment]
Could you check if this is a Quarkus specific issue or a JSON-B issue?

**Comment by tomh2013** [comment]
I re-tested using yasson (1.0.3) and javax.json (1.1.2) and the problem is still present.  So it appears it is a JSON-B issue and not a Quarkus specific issue.

However, this is then a clear problem with JSON-B as serialization/deserialization should be symmetric, and is not.  JSON-B is not recognizing that the generic type of the Set is an Enum and is not converting it from the Enum name String to the Enum value as it should.  This works as expected for a single Enum argument, but not a collection of Enums.  Registering a JsonbAdapter to convert the Enum to a String and back also does not work.

Using an array of Enums rather than a collection does work, but is not really a practical alternative.

The same example using Jackson works correctly.  I was in the process of porting an existing application which uses Jackson across to Quarkus, hence my surprise at the issue.  It makes me wonder what other delights are lurking under the surface.

Is there any plan to support Jackson in Quarkus?

**Comment by tomh2013** [comment]
This appears to be a known problem in Yasson (I assume this is being used under the covers by Quarkus), and is related to the use of the @JsonbCreator annotation.   See: https://github.com/eclipse-ee4j/yasson/issues/230  I have confirmed that for a POJO with setters and getters using no annotations that deserialization works as expected.

**Comment by tomerz90** [comment]
+1 for Jackson support

**Comment by aguibert** [comment]
FYI eclipse-ee4j/yasson#230 has been closed now (fixes as of Yasson 1.0.4) so this issue can likely be closed

**Comment by gsmet** [comment]
Thanks for the heads up @aguibert , closing.
