### ISSUE TITLE
Warning regarding MP Metrics API

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#24597]
### Describe the bug

The `smallrye-fault-tolerance` extension has a dependency on `io.smallrye:smallrye-fault-tolerance` which contains the class `MetricsProvider` which has an injection for `Provider<MetricRegistry>`: https://github.com/smallrye/smallrye-fault-tolerance/blob/798a919e36973cf343d618722ef8a1f463c2706a/implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/metrics/MetricsProvider.java#L62-L64

When building an application this results in a warning being logged by the `micrometer` extension: https://github.com/quarkusio/quarkus/blob/37a4d5f1575acf01c0caee22262d1ba6fad0ed2b/extensions/micrometer/deployment/src/main/java/io/quarkus/micrometer/deployment/binder/mpmetrics/MicroprofileMetricsProcessor.java#L97-L102

### Expected behavior

I think it would make sense for Quarkus to have an exception for this particular injection, since it is part of the platform and developers shouldn't have to hunt this down as Quarkus won't be removing the compatibility layer as long as it depends on it itself.

### Actual behavior

An application using both `smallrye-fault-tolerance` and `micrometer` will see a corresponding warning when building the application.

### Quarkus version or git rev

2.8.0.CR1

**Comment by jmartisk** [comment]
Hmm yeah this is somewhat annoying, but how do we make sure that there's no other usage of MP Metrics beyond what Fault Tolerance is doing?
We might have to scan the application to detect it, which isn't exactly simple or well-performant, so I'm not so sure it's worth it.

**Comment by knutwannheden** [comment]
Shouldn't it be possible to have an exception for only this particular injection in the logic of `MicroprofileMetricsProcessor`? If you agree, I could look into providing a PR.

**Comment by ebullient** [comment]
What are you thinking? Making special cases for specific package names is fragile at best..

**Comment by jmartisk** [comment]
> Shouldn't it be possible to have an exception for only this particular injection in the logic of `MicroprofileMetricsProcessor`? If you agree, I could look into providing a PR.

Of course it is possible to detect that this injection is present, but what I wanted to say is that if there's any other usage beyond that, then the warning should be shown. So you can't remove that warning just based on the presence of that injection.

**Comment by ebullient** [comment]
Right -- would have to ignore usage of the MP Metrics API coming from some packages (is what I'm inferring).

**Comment by knutwannheden** [comment]
Well, I was thinking to only ignore the injection point `io.smallrye.faulttolerance.metrics.MetricsProvider#registry`. I suspect I should be able to retrieve the required information from `InjectionPointInfo`.

**Comment by Ladicek** [comment]
I should be able to tackle this when I (finally...) get to https://github.com/smallrye/smallrye-fault-tolerance/issues/265

It will likely require some CDI gymnastics, but should be doable. I'm thinking SmallRye Fault Tolerance would provide 2 beans with metrics support, and the Quarkus extension would veto one or the other, something like that.
