### ISSUE TITLE
Quartz scheduler to support retry on failure

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#24607]
### Description

It would be really nice if you could specify a number of retries and the delay/backoff between retries for failed scheduled jobs using the `@Scheduled` annotation.

**Comment by geoand** [comment]
Interesting, but doesn't this already work with `@org.eclipse.microprofile.faulttolerance.Retry` from `quarkus-smallrye-fault-tolerance`?

**Comment by mkouba** [comment]
I think that `@Retry` should work although I've never tried that.

**Comment by josephearl** [comment]
Great, thanks I will give that a go! 

Maybe just a mention of that in the docs for scheduled jobs would be useful for users like me 😀

**Comment by josephearl** [comment]
I will give it a go 👍

**Comment by machi1990** [comment]
Thanks

**Comment by josephearl** [comment]
Reopening because `@Retry` does not do what I need.

The issue I encountered that caused me to raise the issue was:

1. I have a scheduled job that runs every hour sending some events to Kafka.
2. I deployed a new version of the application on the hour.
3. The scheduled job started running on one of the instances of the old version of the application, but failed because the Kafka channel was shut down because the application was shutting down.

In this case `@Retry` won’t work because it will retry in-process and this will not succeed, and what I want is the job to be rescheduled with the Quartz scheduler so that it runs on a different application instance.

It seems like I can do this in a Quartz specific manner by throwing a `JobExecutionException` with `setRefireImmediately(true)`.

**Comment by mkouba** [comment]
> It seems like I can do this in a Quartz specific manner by throwing a `JobExecutionException` with `setRefireImmediately(true)`.

In that case, it's probably the right thing to do. We're not going to add anything related to the cluster mode to the `@Scheduled` annotation because it's only supported by the `quarkus-quartz` extension.

**Comment by machi1990** [comment]
> Reopening because `@Retry` does not do what I need.
> 
> The issue I encountered that caused me to raise the issue was:
> 
> 1. I have a scheduled job that runs every hour sending some events to Kafka.
> 2. I deployed a new version of the application on the hour.
> 3. The scheduled job started running on one of the instances of the old version of the application, but failed because the Kafka channel was shut down because the application was shutting down.
> 
> In this case `@Retry` won’t work because it will retry in-process and this will not succeed, and what I want is the job to be rescheduled with the Quartz scheduler so that it runs on a different application instance.
> 
> It seems like I can do this in a Quartz specific manner by throwing a `JobExecutionException` with `setRefireImmediately(true)`.

I think this can be configured on per job level. I am a bit hesitant though going only this way and not having a backoff strategy and retry limits and the job might end up firing until it succeeds - potentially blocking the quartz thread.

**Comment by manofthepeace** [comment]
@josephearl  I think you can fix your issue in a couple of ways, without any change needed in quarkus

**Using a CDI decorator**

make your job implements a custom interface which contains 2 methods, `execute(JobExecutionContext context)` and `reschedule(JobExecutionContext context)` In the decorator you can catch any kind of execption, especially JobExecutionExecution exceptions, and call your reschedule in that case. If you need retries, add a integer to the JobDataMap and a condition in the decorator to check that number.

**Using Fault Tolerance**

If you already have faulttolerance in your project you can use `@Fallback(MyJobHandler.class)`. In the fallback handle method you have access to the ExecutionContext (not quartz but faulttolerance), with it you have access to the throwable + the method parameter,so the quartz JobExecutionContext. WIth that you can do as the previous solution and reshedule yourself the task.

**Comment by josephearl** [comment]
Thanks @manofthepeace for taking the time to suggest some solutions, those both look good, will give them a try

**Comment by mkouba** [comment]
I think that we can close this issue. @josephearl  WDYT?

**Comment by josephearl** [comment]
Yep 👍

**Comment by mkouba** [comment]
> Yep +1

:+1:  thanks.
