### ISSUE TITLE
Quarkus environment variables issue with Test containers

### ISSUE THREAD

**Issue by Achyutha7** [quarkusio/quarkus#24618]
### Discussed in https://github.com/quarkusio/quarkus/discussions/24336

<div type='discussions-op-text'>

<sup>Originally posted by **Achyutha7** March 15, 2022</sup>
Developed the integration tests using Test container. Have few fields as environment variables(Eg: passing it as quarkus.datasource.username=${SER_DB_USERNAME:postgres}) in application.properties file. 

When setting environment field through test container
```
 GenericContainer<?> someService = new GenericContainer<>(img)
 .withEnv("SER_DB_USERNAME", DataLayer.DB_USERNAME)
```
                                                                
This value is being successfully taken with test containers but 

For the below environment variable, 
`app.security.enabled=${SER_SEC_ENABLE:true}` defined in application.properties file

`@IfBuildProperty(name = "app.security.enabled", stringValue = "true")`  

the environment variable is setting through cmd prompt using -DSER_SEC_ENABLED=true, but when trying to pass the same value in test containers, it's always null.

```
GenericContainer<?> someService = new GenericContainer<>(img)
.withEnv("SER_SEC_ENABLE", "true")
```
                                                               
                                                              
</div>

**Comment by geoand** [comment]
`@IfBuildProperty` is determined at build time (see [this](https://quarkus.io/guides/cdi-reference#enable_build_profile) for more details), so when the application runs in the container, the condition is **not** evaluated at runtime
