### ISSUE TITLE
hibernate-orm guide should mention JNDI is disabled

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24629]
### Describe the bug

Hibernate ORM extension has disabled use of JNDI (https://github.com/quarkusio/quarkus/pull/22901 for no-op impl, exception before that) 

hibernate-orm guide should mention that JNDI is disabled

Some guides do mention JNDI restrictions:
```
~/git/quarkus/docs:  git grep JNDI
src/main/asciidoc/mongodb.adoc:WARNING: By default Quarkus will restrict the use of JNDI within an application, as a precaution to try and mitigate any future vulnerabilities similar to log4shell.
src/main/asciidoc/mongodb.adoc:Because the `mongo+srv` protocol often used to connect to MongoDB requires JNDI, this protection is automatically disabled when using the MongoDB client extension.
src/main/asciidoc/mongodb.adoc:However, in native, the default DNS resolver, provided by the MongoDB client, uses JNDI and does not work in native mode.
src/main/asciidoc/security-ldap.adoc:WARNING: By default Quarkus will restrict the use of JNDI within an application, as a precaution to try and mitigate any future vulnerabilities similar to log4shell. Because LDAP based auth requires JNDI
```

### Expected behavior

hibernate-orm guide should mention that JNDI is disabled

### Actual behavior

hibernate-orm guide does not mention that JNDI is disabled

### How to Reproduce?

Check https://quarkus.io/guides/hibernate-orm

**Comment by Sanne** [comment]
Do you have a suggetion about what to write? N.B. it has never been an option to use JNDI for datasource configurations of Hibernate ORM in Quarkus.

I'm not inclined to include unnecessary noise in the documentation: keeping it light is a feature.

**Comment by Sanne** [comment]
Ok you convinced me :)  I'll send a PR shortly.

**Comment by rsvoboda** [comment]
Thanks! PR is merged.
