### ISSUE TITLE
Scheduler - support non-blocking scheduled methods

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#24621]
### Description

Currently, a scheduled method is always invoked on a thread from the core thread pool. As a result, you can't e.g. use Hibernate Reactive in a scheduled method. A workaround is to inject the managed `Vertx` and use `Vertx.runOnContext()`.

We could either use `@io.smallrye.common.annotation.NonBlocking` to mark a scheduled method as non-blocking or allow a scheduled method to return an async type such as `Uni`.

**Comment by mschorsch** [comment]
See also https://github.com/quarkusio/quarkus/issues/21428

**Comment by mkouba** [comment]
> See also #21428

Yup, that would be the next phase ;-).
