### ISSUE TITLE
list-extensions shows badly on small screens

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2463]
`mvn quarkus:list-extensions` is un usable with the added URL. You guys have tiny eyes and big screens. But for me I can't click on the url as it goes on two lines.
I'd recommend we put the URL in a second line.

```
         RESTEasy - JSON-B                                  quarkus-resteasy-jsonb                                                       https://quarku
s.io/guides/rest-json-guide
         Scheduler                                          quarkus-scheduler                                                            https://quarku
s.io/guides/scheduled-guide
         Security                                           quarkus-elytron-security                                                     https://quarku
s.io/guides/security-guide
         SmallRye Fault Tolerance                           quarkus-smallrye-fault-tolerance
         SmallRye Health                                    quarkus-smallrye-health                                                      https://quarku
s.io/guides/health-guide
         SmallRye JWT                                       quarkus-smallrye-jwt                                                         https://quarku
s.io/guides/jwt-guide
         SmallRye Metrics                                   quarkus-smallrye-metrics                                                     https://quarku
s.io/guides/metrics-guide
         SmallRye OpenAPI                                   quarkus-smallrye-openapi                                                     https://quarku
s.io/guides/openapi-swaggerui-guide
         SmallRye OpenTracing                               quarkus-smallrye-opentracing                                                 https://quarku
s.io/guides/opentracing-guide
         SmallRye Reactive Streams Operators                quarkus-smallrye-reactive-streams-operators
         SmallRye Reactive Type Converters                  quarkus-smallrye-reactive-type-converters
         SmallRye Reactive Messaging                        quarkus-smallrye-reactive-messaging                                          https://quarku
s.io/guides/async-message-passing
         SmallRye Reactive Messaging - Kafka Connector      quarkus-smallrye-reactive-messaging-kafka                                    https://quarku
s.io/guides/kafka-guide
         SmallRye REST Client                               quarkus-smallrye-rest-client                                                 https://quarku
s.io/guides/rest-client-guide
         Spring DI compatibility layer                      quarkus-spring-di                                                            https://quarku
s.io/guides/spring-di-guide
         Swagger UI                                         quarkus-swagger-ui                                                           https://quarku
s.io/guides/openapi-swaggerui-guide
         Undertow                                           quarkus-undertow
         Undertow WebSockets                                quarkus-undertow-websockets                                                  https://quarku
s.io/guides/websocket-guide
         Eclipse Vert.x                                     quarkus-vertx                                                                https://quarku
s.io/guides/using-vertx
         Reactive Postgres Client                           quarkus-reactive-pg-client
```

**Comment by emmanuelbernard** [comment]
CC @Dufgui

**Comment by Dufgui** [comment]
Ok i will do it

**Comment by emmanuelbernard** [comment]
Thanks!

BTW what’s the status and updated version representing precisely?
I’m asking because at least the status is empty most of the time. Maybe these should be after the extension make and artifact id. 
and if the url in the console could be made to cut vs overflow (not a console guru), that would solve the problem. 

Finally depending on the usefulness of the status and version thing, maybe simple should be the default vs full. For sure the property Quarkus. Is way too long to type. Could it be a env variable btw?

**Comment by Dufgui** [comment]
The status is previously their. So I don’t remove it. If the extension dependency have a fix version, it check if it is outdated.  but most of the time people use the bom, so it s useless.
For url, i can check the width of the console with the following lib and adapt the layout to the width, no?
https://github.com/jline/jline3

I don't understand the end of the message ? what do you talk the property quarkus ?

**Comment by emmanuelbernard** [comment]
Right know I need to use something like -Dquarkus.foo.format=simple to use the simpler format, that's really long and hard to remember as a property.

Do you know what the status mean? Anyone else?
So these extra columns seem to be about the extensions you already have in your POM and for which you want to check whether an update is necessary? I could see that be a different command actually.

**Comment by emmanuelbernard** [comment]
BTW on a parallel subject, I think this would add value https://github.com/quarkusio/quarkus/issues/2500

**Comment by Dufgui** [comment]
So I propose to change column and order. Because the artefact Id must not be split on 2 line too. 
The default format may be the simple one, this:
Artefactid description
GuideUrl

For the other display format I propose to start from the use case. 

The full format will be rename by upgrade format: this format need too search on maven central the last available version of quarkus bom and quarkus extension and provide an upgrade oriented format. 

And I add the search format. But I must test to find the better column for this. Maybe the simple one is enough.

**Comment by Dufgui** [comment]
It’s based on your idea @emmanuelbernard but my proposal is more a way of thinking

**Comment by Dufgui** [comment]
I start the dev by set simple format by default and add carriage return before guide.
Do you want I rename the full format to upgrade and I change the way we extract version from bom and get it from somewhere else (what is the reference for delivery of quarkus extension? ), because I find this a little strange. And I am not sure it's our job to fin if plugin must be upgraded (there is already https://www.mojohaus.org/versions-maven-plugin/examples/display-plugin-updates.html)

**Comment by emmanuelbernard** [comment]
I am not sure about the upgrade format. @aloubyansky how are people expected to discover the need for updates? Via `list-extensions` or differently? And if the use case is about the upgrade, then I guess a user does not care about extensions not present in its POM. My gut feeling says it should be in a separate command.

**Comment by aloubyansky** [comment]
Yes, I would also have a separate command for checking for the available updates.

**Comment by Dufgui** [comment]
Like `list-outdated`
