### ISSUE TITLE
Kubernetes Minikube extension doesn't generate the minikube.yml file while using Maven 3.8.5 

### ISSUE THREAD

**Issue by lucamolteni** [quarkusio/quarkus#24644]
### Describe the bug

If the dependency is in a separate profile, using quarkus 2.7.5 with maven 3.8.5 does not generate the minikube.yml

Here's a link of the repoducer

https://github.com/lucamolteni/mvn385bug

### Expected behavior

See the minikube.yml file inside the target directory

### Actual behavior

No file is generated

### How to Reproduce?

Follow the step in https://github.com/lucamolteni/mvn385bug with both maven 3.8.4 and 3.8.5

### Output of `uname -a` or `ver`

Darwin  21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.4 and 3.8.5

**Comment by geoand** [comment]
Also cc @famod who has followed a Maven 3.8.5 issue that could be related

**Comment by famod** [comment]
Yeah, that sounds *a lot* like https://issues.apache.org/jira/browse/MNG-7432
You'll have to wait for Maven 3.8.6 and/or use the followign workaround until then: https://github.com/quarkusio/quarkus/pull/24285#issuecomment-1067961676

**Comment by famod** [comment]
This is now listed under known issues: https://maven.apache.org/docs/3.8.5/release-notes.html#known-issues

I'll close this because it's a thirdparty issue.
