### ISSUE TITLE
Cannot create examples with Maven 3.8.5

### ISSUE THREAD

**Issue by lucamolteni** [quarkusio/quarkus#24643]
### Describe the bug

Unable to create projects using Maven 3.8.5

### Expected behavior

The example project has been created successfully

### Actual behavior

```[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.511 s
[INFO] Finished at: 2022-03-30T16:59:48+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:create (default-cli) on project standalone-pom: Execution default-cli of goal io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:create failed: An API incompatibility was encountered while executing io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:create: java.lang.NoSuchMethodError: 'org.apache.maven.model.profile.activation.FileProfileActivator org.apache.maven.model.profile.activation.FileProfileActivator.setPathTranslator(org.apache.maven.model.path.PathTranslator)'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/

```

### How to Reproduce?

Install maven 3.8.5

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=mvn385bugprova \
    -Dextensions="resteasy,kubernetes,jib" \
    -DnoCode
```

### Output of `uname -a` or `ver`

Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: /Users/lmolteni/.sdkman/candidates/maven/3.8.5 Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: /Users/lmolteni/.sdkman/candidates/java/17.0.2-tem Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "x86_64", family: "mac"

**Comment by famod** [comment]
The Quarkus update to Maven 3.8.5 was [aborted](https://github.com/quarkusio/quarkus/pull/24285#issuecomment-1067942492) due to the same reason as described here: https://github.com/quarkusio/quarkus/issues/24644#issuecomment-1083325960

/cc @aloubyansky, I don't see how we can provide a better error message, given that the plugin cannot be loaded

**Comment by Tibor17** [comment]
Hello guys.
I would like to invite you to Vote for Surefire/Failsafe Maven Plugin 3.0.0-M6.
https://lists.apache.org/thread/60j5vr86y9o24yoj4665gy1rylb7865g
Many people are asking me when we will release the final version 3.0.0. After over one decade of development, we are in the phase where we are not able to fix some issues without reworking some code internals and that's the reason why we have continuous work in milestone versions. We are still supporting our customers and we combine this activity with internal activities. The final version 3.0.0 will break the backwards compatibility in a positive manner for user.

**Comment by Tibor17** [comment]
Sunday 3pm is the end of the Vote.
