### ISSUE TITLE
RestClientBuilderResolver get Resolver from cdi or class

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#24659]
### Description

i am developing dapr-extension.
i hope dapr-client can be adpter for rest-client.
when i view the code of  rest-client-extension.
the `BuilderResolver` was wrote in `RestClientRecorder`.
can it be configuration by cdi or class.
i just do write `BuilderResolver` and `DaprRestClientBuilder `   to complete it

<img width="741" alt="image" src="https://user-images.githubusercontent.com/25682169/161006995-a86a6d1e-2f88-4fd2-8c5f-78039f9bf820.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/25682169/161007062-d16f33bb-3e34-462e-8bbc-f83f28f796e8.png">

### Configuration suggestion

get `BuilderResolver` from CDI or class

**Comment by geoand** [comment]
I would first suggest looking at `quarkus-rest-client-reactive`, as that is the extension we will be focusing on going forward

**Comment by zhfeng** [comment]
@naah69 @geoand so we need to register a implementation class in ```dapr-client/runtime/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver``` and ```quarkus-rest-client-reactive``` could inject it in the jaxrs methods ?

**Comment by geoand** [comment]
If you provide an implementation of that SPI, then the Reactive REST Client won't be used.

As I am unclear what the end goal is, can you provide some examples of what you are looking to do?

**Comment by zhfeng** [comment]
I think they are looking to use dapr-client to replace the quarkus rest client. @naah69 is it your idea ?

**Comment by geoand** [comment]
> only http-connection and apache-http-client engine can be created

Indeed we don't have an integration point. I suppose we could add an SPI, but in all honesty, we are moving away from the `quarkus-rest-client` to `quarkus-rest-client-reactive`.
WDYT @michalszynkiewicz ?

**Comment by michalszynkiewicz** [comment]
For the classic rest client, it seems that adding an option to customize the `ClientHttpEngine` wouldn't be that difficult...

For the reactive variant, I don't think the vertx http client could be easily swapped with something else.

@naah69 , what do you gain by replacing the engine with dapper?

**Comment by geoand** [comment]
Closing as we never got much feedback on the end goal.

Feel free to comment or reopen if you want this to be reconsidered
