### ISSUE TITLE
Allow reuse of containers via QuarkusTestResourceLifecycleManager or QuarkusTestResource

### ISSUE THREAD

**Issue by Tapaka** [quarkusio/quarkus#24660]
### Description

Hi,

I posted a [question on SO](https://stackoverflow.com/questions/71680113/how-can-i-reuse-containers-during-integration-tests-with-quarkus?noredirect=1#comment126694045_71680113), @geoand told me it was not possible and to ask for the feature so here I am.

I'd like to be able to take advantage of the reuse feature of testcontainers through classes implementing QuarkusTestResourceLifecycleManager. Currently containers are shutdown in between test classes and the possibility to prevent that would be great as some containers take several seconds to launch and after a few tests the startup time for containers starts to have a real impact on build time.

Thanks for the great work on the Quarkus project by the way !

**Comment by loicmathieu** [comment]
@geoand yes, we have the issue with tests that have different profiles, Quarkus was restarted for each test and the containers also. I'm not sure it's the same issue here but having a way to specify that dev services containers are bound to the full test suite and survives application restart would be great !

**Comment by famod** [comment]
@Tapaka
We are not taking about dev services, are we?
So you implement QuarkusTestResourceLifecycleManager, creating/starting a testcontainer instance _on your own_, right?

In that case I'm wondering what Quarkus could do for you?

Food for thought: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Test.20resources.20are.20re-runned.20when.20using.20test.20profiles

**Comment by Tapaka** [comment]
Hi sorry for the delay, I'm not talking about dev services and yes I do implement QuarkusTestResourceLifecycleManager and create an instance of my own.

After a bit mot research on my side, turns out that reuse actually works with Quarkus it's just that network are not well supported with reuse of testcontainers. Your link set me in the right direction so thanks :)
