### ISSUE TITLE
Validation annotations don't seem to work on a String body with quarkus-resteasy-jackson

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#24661]
### Describe the bug

Given a resource like so:

```
public Response foo(@NotBlank String foo) {
    return ok().status(CREATED).build();
}
```

I would expect to get a `400` when calling with a blank request body, but actually get a `201`

It works fine with `@PathParam` (get a `400` as expected with blank parameter):

```
public Response foo(@PathParam("foo) @NotBlank String foo) {
    return ok().status(CREATED).build();
}
```

### Output of `java -version`

17

### Quarkus version or git rev

2.7.5.Final

**Comment by geoand** [comment]
I'll let @gsmet comment on this one as I he is the SME

**Comment by geoand** [comment]
FTR, `@RequestBody` comes from Spring and has absolutely no effect when using JAX-RS

**Comment by josephearl** [comment]
In this case the `@RequestBody` is from Open API (`org.eclipse.microprofile.openapi.annotations.parameters.RequestBody`), so just for documentation.

**Comment by geoand** [comment]
Ah ok, thanks

**Comment by josephearl** [comment]
🤦 I was missing the quarkus-hibernate-validator extension. It does work.

**Comment by geoand** [comment]
Thanks for the update!
