### ISSUE TITLE
Make it possible to resume on 404 instead of mapping with RESTEasy classic and reactive

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#24671]
### Description

In the experimental [Quinoa](https://github.com/quarkiverse/quarkus-quinoa) extension, in dev mode, I need a behavior where my Handler catches everything that isn't successfully handled by other extensions. The idea is that all those not found requests should be forwarded to a node dev server.

Currently, RESTEasy Reactive has a flag for it: 
https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java#L808
This flag is only available for servlet capability.

I would like to make it possible for any extension (using a BuildItem?) to enable `resumeOn404`.

Also, I wonder why we don't always resume on 404 and put the resteasy 404 mapper handler far down the priority list so that other can plug in their handler the middle of the vertx router priority queue, without needing such an option. Ex:
 - /hello -> handled by resteasy
 - /some-file-> passed to the next by resteasy, passed to the next by quinoa, 404 handling by resteasy
 - /index.html -> passed to the next by resteasy, handled by quinoa

**Comment by ia3andy** [comment]
I am not sure if the issue is the same, but mentioning as it's similar: https://github.com/quarkusio/quarkus/issues/5236

**Comment by geoand** [comment]
Should we close this as we have done the work for RESTEasy Reactive?

**Comment by ia3andy** [comment]
Let's close this issue for now as fixing this in RESTEasy Classic would involve too much effort.
