### ISSUE TITLE
Block scheduled task execution when running tests

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#24685]
### Description

Hi, Now when you run the test, all scheduled task methods will be executed automatically. I wish there was a way to stop it, but now it seems impossible, or did I miss anything?

```java
   @Scheduled(every = "5s")
    public void transfer() {
        //do something
    }
```

```java
    @Test
    @RunOnVertxContext
    public void getPartitions(UniAsserter asserter) {
        //do something
    }
```

**Comment by geoand** [comment]
I think it would be very reasonable to provide a configuration switch for this. @mkouba @machi1990 WDYT?

**Comment by mkouba** [comment]
@aomsweet Did you try to disable the scheduler for the test profile, i.e. `%test.quarkus.scheduler.enabled=false`?

**Comment by geoand** [comment]
I completely missed that property myself... 🤦🏼

**Comment by machi1990** [comment]
> @aomsweet Did you try to disable the scheduler for the test profile, i.e. to put `%test.quarkus.scheduler.enabled=false` in the `application.properties` file?
> 
> https://quarkus.io/guides/scheduler-reference#quarkus-scheduler_quarkus.scheduler.enabled

+1. The property can also be overridden using `TestProfiles`.

Additionally, the `Scheduled` has a `skipExecutionIf` predicate. One can create a `DoNotRunSchedulerInTestProfile` that leverages the `quarkus.profile` for example or some other way specific to the application of detecting if tests are running.

**Comment by aomsweet** [comment]
@machi1990 @mkouba @geoand  Thanks, 

`%test.quarkus.scheduler.enabled=false` is ok.

> Additionally, the `Scheduled` has a `skipExecutionIf` predicate. One can create a `DoNotRunSchedulerInTestProfile` that leverages the `quarkus.profile` for example or some other way specific to the application of detecting if tests are running.

Inspired by this, I created `DoNotRunSchedulerInTestProfile` and set `skipExecutionIf = DoNotRunSchedulerInTestProfile.class` on `@Scheduled`, it work fine.
```java
@Singleton
@IfBuildProfile("test")
public class DoNotRunSchedulerInTestProfile implements Scheduled.SkipPredicate {

    @Override
    public boolean test(ScheduledExecution execution) {
        return ProfileManager.getLaunchMode() == LaunchMode.TEST;
    }
}
```

```java
@Scheduled(every = "5s", skipExecutionIf = DoNotRunSchedulerInTestProfile.class)
public void transfer() {

}
```
