### ISSUE TITLE
Gradle quarkusIntTest and testNative tasks should not depend on check

### ISSUE THREAD

**Issue by mchristiansen** [quarkusio/quarkus#24704]
### Describe the bug

The `quarkusIntTest` and `testNative` gradle tasks add a dependency on `check`. I believe this dependency is backwards - `check` should instead depend on the `Test` tasks.

This causes a circular dependency issue with our build because we run a `jacocoCoverageVerification` task after all test tasks and `jacocoCoverageVerification` is set as a dependency of `check`.

Relevant gradle configuration snippet
```
tasks.register('jacocoCoverageVerification') {
  ...
}
check.dependsOn(jacocoCoverageVerification)
tasks.withType(Test) { task ->
  jacocoCoverageVerification.dependsOn(task)
}
```

Error output
```
Circular dependency between the following tasks:
:check
\--- :jacocoCoverageVerification
     +--- :quarkusIntTest
     |    \--- :check (*)
     \--- :testNative
          \--- :check (*)
```

### Expected behavior

`check` should depend on the registered `Test` tasks

### Actual behavior

`Test` tasks depend on `check`

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.3.0

### Output of `java -version`

openjdk version "11.0.11"

### Quarkus version or git rev

2.8.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by glefloch** [comment]
Thanks for reporting this @mchristiansen I will change dependency
