### ISSUE TITLE
dev mode Startup time regression between 2.7.5.Final and 2.8.0.CR1

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#24712]
### Describe the bug

I noticed a slight regression in dev mode startup time between 2.7.5.Final and 2.8.0.CR1.
A bit of testing showed cf388350609ff4b108dacd09a187523d35b6fc4c (#24398) as main contributor.

average of 3 runs:
2.8.0.CR1
mvn quarkus:dev: 2170ms
force restart (s) 532ms

2.7.5.Final
mvn quarkus:dev: 1850ms
force restart (s) 189ms

2.8.0.Final and 2.8.0.CR1 behave the same regarding dev mode startup time.

### How to Reproduce?

Download the reproducer, or just generate any quarkus app: 
[profiling.zip](https://github.com/quarkusio/quarkus/files/8403295/profiling.zip)

mvn quarkus:dev. Take not about the reported startup time.
change version to 2.7.5.Final
mvn quarkus:dev. Take not about the reported startup time. Way faster.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.556]

### Output of `java -version`

openjdk 17.0.1 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final, 2.8.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739) Maven home: C:\tools\java\maven Java version: 17.0.1, vendor: Eclipse Adoptium, runtime: C:\tools\java\17-temurin Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by gsmet** [comment]
@Postremus do you have some profiling data for before/after? The problem is not immediately obvious even with the commit.

**Comment by Postremus** [comment]
Flamegraphs of a quarkus:dev run:

[flamegrpahs.zip](https://github.com/quarkusio/quarkus/files/8405197/flamegrpahs.zip)


Search for "ArcProcessor\.generateResources".
2.7.5.Final: 1.54%
2.8.0.CR1: 4.42&

**Comment by mkouba** [comment]
This is kind of expected. We need to wrap every construction of a _removed_ bean info with a `try-catch block` and in the reprodurer there is 82 removed beans. So the generated bytecode is more complex. From the flame graphs it seems that it's `Frame#merge()` that takes the most time. I'm not sure if we could do something about that? CC @stuartwdouglas @FroMage

**Comment by mkouba** [comment]
FTR the reproducer seems to use quarkus 1.13.1.Final in the pom ;-)

**Comment by mkouba** [comment]
So I've tried to split the bytecode that loads removed beans into larger number of smaller methods (previously 82 bens got split into 5 methods and now it's split into ~ 17 methods) and the problem with `MethodWriter#computeAllFrames()` and `Frame#merge()` seems to be gone. I'll send a draft PR so that @Postremus can verify my findings...
