### ISSUE TITLE
HttpSecurityRecorder does not honor root-path

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#24728]
### Describe the bug

If the `quarkus.http.root-path` is changed, this is not taken into account when specifying `quarkus.http.auth.permission.authenticated.paths`.

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/8405187/reproducer.zip)

1. http://localhost:8080/hello => User will be asked to sign in
2. Uncomment `quarkus.http.root-path=/example/` in `application.properties`
3. http://localhost:8080/example/hello => No authentication anymore

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by sberyozkin** [comment]
@mschorsch Thanks for reporting it, it is not `quarkus-oidc` which is dealing with these paths, so let me rename the issue
