### ISSUE TITLE
Broken docs example Dockerfile

### ISSUE THREAD

**Issue by WillSmithTE** [quarkusio/quarkus#24727]
### Description

From this guide https://quarkus.io/guides/building-native-image

The Dockerfile under "Sample Dockerfile for building with Gradle:" is broken. Line 4 is missing "gradle" so docker won't be able to build it.

### Implementation ideas

Add "gradle"

**Comment by geoand** [comment]
@WillSmithTE thanks for reporting!

Since you seem to already know how to fix it, by providing a Pull Request where you update https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/building-native-image.adoc?

Thanks

**Comment by VanillaSpoon** [comment]
Hey, I can jump on this if it hasn't been resolved yet :)

**Comment by gsmet** [comment]
@VanillaSpoon please do.
