### ISSUE TITLE
Document how to use Azure Service Hub (using the Kafka protocol)

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24726]
### Description

Add a section in the Kafka reference guide that covers configuring the application to use the Azure Service hub.

### Implementation ideas

Here is what should be added:

```properties
kafka.bootstrap.servers=my-event-hub.servicebus.windows.net:9093
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="$ConnectionString" \
    password="Endpoint=sb://my-event-hub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=...";
```

@agoncal Is `$ConnectionString` really `$ConnectionString` or a substituted variable?

**Comment by ozangunalp** [comment]
@cescoffier no, username="$ConnectionString" is not a substituted variable.

**Comment by agoncal** [comment]
@cescoffier username="$ConnectionString"  is really like that (I found it weird at the beginning). It's a reference to the connection string.

**Comment by edeandrea** [comment]
Just following up - we'd also need to figure out how to use the azure event hub schema registry.

**Comment by agoncal** [comment]
@edeandrea I managed to find someone in the team of Azure Schema Registry. Hopefully I'll know soon if we can connect to it with Quarkus or not. If we can, then we will create a new issue with some documentation

**Comment by ozangunalp** [comment]
@edeandrea I tested it a few months ago. I had to create a custom Serde using `azure-identity` and `azure-data-schemaregistry-avro`. Of course, Azure SDK uses it's own HTTP Client etc.

**Comment by edeandrea** [comment]
@ozangunalp Do you have any of the sample code you used laying around anywhere that @agoncal and I could take a look at?

**Comment by ozangunalp** [comment]
@edeandrea @agoncal I pushed my test in a repo. Here is the Serde that I used https://github.com/ozangunalp/managed-kafka-quarkus/blob/main/azure-event-hub/src/main/java/com/ozangunalp/AzureKafkaAvroSerde.java

**Comment by agoncal** [comment]
Thanks @ozangunalp !!! Can't wait to test it (after we give our talk).

**Comment by felipe-alves-moraes** [comment]
Hi, sorry to bring this topic back to life, but I'm integrating Event Hubs in my project and I was checking on how to integrate with the Azure Schema Registry.
Do we have a final solution for Azure Schema Registry apart from the one suggested by @ozangunalp?

Thanks!

C.C. @agoncal

**Comment by edeandrea** [comment]
Hi @felipe-alves-moraes I am not aware, nor did I ever try out @ozangunalp 's solution.

**Comment by felipe-alves-moraes** [comment]
I'm about to give it a try, just wanted to be sure there is not an "official" support hidden somewhere 😂 .
Thanks!
