### ISSUE TITLE
Annotated providers aren't registered if there is no @Consumes("*/*") or @Provider("*/*")

### ISSUE THREAD

**Issue by morhei** [quarkusio/quarkus#24736]
### Describe the bug

Hi,

I've encountered a weird behavior (bug) concerning classes that are annoted with `@Provider`. The problem that I have is, that I want to provide my own `MessageBodyWriter` to serialize Java classes that are returned by the endpoint. However, instead of using my custom body writer some generic writer that accesses fields via reflection is used.

### Example:
Based on `rest-client-quickstart` with added objects and adjusted methods:

*  `CustomMessageBodyWriter`: annotated with `@Provider` and `@Produces(MediaType.APPLICATION_JSON)` implementing  ` MessageBodyWriter`
* `CountrySerializer`: used by the `ObjectMapper` defined in `CustomMessageBodyWriter` to serialize the entity `Country`
* `CountriesResource` rest endpoint to retrieve a country (annotated with `@Produces(MediaType.APPLICATION_JSON)`)
* `CountryResourceTest` small test to check if the custom serializer is being used

`CustomMessageBodyWriter` is not used until some random method (not the one being called) or class is annotated with either `@Produces(MediaType.WILDCARD)` or `@Consumes(MediaType.WILDCARD)` (see `CountriesResource#noContent`). If the annotation is present the test runs through, if it is removed or replaced with another media type the test fails.

[provider-bug.tar.gz](https://github.com/quarkusio/quarkus/files/8409726/provider-bug.tar.gz)

### Expected behavior

Custom serializer is used.

### Actual behavior

Generic serializer is used.

### How to Reproduce?

Import project and run the test

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08

### Quarkus version or git rev

2.7.3.Final

**Comment by geoand** [comment]
Does the same behavior occur when using the `quarkus-rest-client-reactive`?
Asking because our efforts are focused on that instead of the legacy `quarkus-rest-client`

**Comment by morhei** [comment]
Using `quarkus-resteasy-reactive-jackson` instead of `quarkus-resteasy-jackson` seems to fix the issue in the example.
I would have to check if we can simply replace the dependencies without touching the code too much or are you aware of any issues concerning that?
Thanks for the help!

**Comment by geoand** [comment]
Thanks for checking!

You likely will not have to change anything other than the dependencies, but you can read https://github.com/quarkusio/quarkus/blob/2.8.0.Final/docs/src/main/asciidoc/resteasy-reactive-migration.adoc for more information.
