### ISSUE TITLE
Buggy behavior with annotated provider named 'JsonSerializer' or 'GenericJsonSerializer'

### ISSUE THREAD

**Issue by morhei** [quarkusio/quarkus#24738]
### Describe the bug

Hi,

I found a weird behavior concerning classes annotated with `@Provider`. I have two projects:

`providers-test` containing 14 classes annotated with `@Provider`, and the class `CustomMessageBodyWriter` implementing `MessageBodyWriter` and annotated with `@Produces({MediaType.APPLICATION_JSON, "application/*+json"})`.

The second project `rest-json-quickstarts` imports the first project and contains a class called `GenericJsonSerializer` extending my `CustomMessageBodyWriter` and annotated with `@Provider`.

Running the provided test fails since my serializer isn't picked up but rather a generic one is used. Again, annotating any random method with `@Produces("*/*")` or `@Consumes("*/*")` yields a successful test (same as https://github.com/quarkusio/quarkus/issues/24736).
**However** there is a second workaround: instead of annotating a random method it works as expected if any of the providers of `providers-test` implying a limit on the number of providers. This behavior is only reproducible if the extending class is either called `JsonSerializer` or `GenericJsonSerializer`. For names like `TestJsonSerializer` the test always fails regardless of the number of providers.

https://github.com/morhei/providers-test

### Expected behavior

Use custom serializer

### Actual behavior

Uses generic serialier

### How to Reproduce?

1. Pull repository
2. Build `provider-tests` with `mvn clean install`
3. Run the test provided in `rest-json-quickstart` -> fails
4. Remove a single provider in `provider-tests` and build it again
5. Run test -> succeeds
6. Rename `GenericJsonSerializer`
7. Run test -> fails

### Output of `java -version`

OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)

### Quarkus version or git rev

2.7.3.Final

**Comment by geoand** [comment]
Does the same behavior occur when using the quarkus-rest-client-reactive?
Asking because our efforts are focused on that instead of the legacy quarkus-rest-client

**Comment by morhei** [comment]
Took a bit longer to test:

For the tests I've used the Quarkus version `2.7.5.Final`.

### First test
* Changing `quarkus-resteasy-jackson` to `quarkus-resteasy-reactive-jackson` in project `rest-json-quickstart`
* Keeping  `quarkus-rest-client-jackson` in project `providers-test` 

Does not work, however workarounds still work.

#### Second test
* Changing `quarkus-resteasy-jackson` to `quarkus-resteasy-reactive-jackson` in project `rest-json-quickstart`
* Changing  `quarkus-rest-client-jackson` to `quarkus-rest-client-jackson` in project `providers-test`

Does not work, not even using any of the workarounds.

#### Third test
* Keeping `quarkus-resteasy-reactive-jackson` in project `rest-json-quickstart`
* Changing  `quarkus-rest-client-jackson` to `quarkus-rest-client-jackson` in project `providers-test`

Works. Changing the name of the BodyMessageWriter didn't have any influence.

**Comment by morhei** [comment]
I also quickly tested an alternative of the second test, where I chganged `quarkus-rest-client-jackson` to `quarkus-resteasy-reactive-jackson` in `project providers-test` with the same result that it doesn't work.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/24786 will fix the RESTEasy Reactive issue.

We won't be providing a fix for Classic RESTEasy since we are focused on RESTEasy Reactive going forward.
