### ISSUE TITLE
Quarkus unix domain socket path no longer used but placed onto 0.0.0.0 instead

### ISSUE THREAD

**Issue by polarctos** [quarkusio/quarkus#24739]
### Describe the bug

Quarkus supports listening on a unix domain socket instead of a TCP socket for the HTTP server.
The path for the socket is no longer correctly used.

Config sample:
https://quarkus.io/guides/vertx-reference#listening-to-a-unix-domain-socket
https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.domain-socket

```yaml
quarkus.http.host-enabled = false
quarkus.http.domain-socket = /var/run/io.quarkus.app.socket
quarkus.http.domain-socket-enabled = true
quarkus.vertx.prefer-native-transport = true
```

After upgrading to Quarkus 2.7.5 the unix domain socket is no longer correctly placed on the selected path location. Also the default path is not used. 

Quarkus startup log message prints:
`(...) Listening on: unix:0.0.0.0`

Also `netstat` shows that the domain socket is now placed on "0.0.0.0" instead of the proper path:
`unix  2      [ ACC ]     STREAM     LISTENING     28944    1/java               0.0.0.0`

### Expected behavior

The unix domain socket should be placed onto the correct path e.g. `/var/run/io.quarkus.app.socket`.

### Actual behavior

The unix domain socket is always placed onto `0.0.0.0`.

### How to Reproduce?

Reproducer:

Generate a fresh Quarkus project and configure it to use a unix domain socket instead of TCP for the HTTP server.

https://quarkus.io/guides/vertx-reference#listening-to-a-unix-domain-socket

### Output of `uname -a` or `ver`

Linux 6832a73e6fed 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.2 2022-01-18 LTS

### Quarkus version or git rev

Quarkus 2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by famod** [comment]
> After upgrading to Quarkus 2.7.5

From which Quarkus version did you upgrade?

**Comment by polarctos** [comment]
> > After upgrading to Quarkus 2.7.5
> 
> From which Quarkus version did you upgrade?

It is working e.g. in Quarkus 2.6.2

**Comment by polarctos** [comment]
Thanks for the fix!
