### ISSUE TITLE
Import Stork properties to Quarkus all configuration properties page

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24756]
### Description

Add the stork properties to the all config page and config editor (from the dev UI)

**Comment by gsmet** [comment]
If they are made proper Quarkus config, this will be automatic (the config editor needs something in the quarkus-extension.yml).

That's the way to go.

**Comment by aureamunoz** [comment]
I just asked for it to @geoand. I need to generate docs and check locally if Storks properties are there

**Comment by geoand** [comment]
That's what I answered as well 😎

**Comment by aureamunoz** [comment]
I've seen that the config part was missing in the corresponding quakus-extension.yml file
