### ISSUE TITLE
Switch to the new gRPC server provided by Vert.x

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24754]
### Description
Vert.x 4.3 is coming with a new gRPC service implementation which about using the one from gRPC Java.
There are multiple advantages to switching like:

- having a single HTTP server instead of having gRPC exposed on a different port
- no more impossible constraints to fix when trying to bump netty
- the new server is a lot more flexible which also allows integrating gRPC to pass-thought API gateway

**Comment by cescoffier** [comment]
Depends on #24753

**Comment by andreas-eberle** [comment]
@mkouba @alesj : Is there a status update on this? We would love to see the integration :) Thanks for your efforts!

**Comment by mkouba** [comment]
I'm not working on this at the moment so no update from my side ;-)

**Comment by cescoffier** [comment]
@alesj is working on it. We have something quite advanced already. There are a few gaps in the new Vert.x server that needs to be polished (gRPC context support, support of the gRPC load balancing...)
