### ISSUE TITLE
Automatic registration of ingress route for gRPC

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24751]
### Description

This issue is about exposing an OpenShift route or an ingress rule to expose a gRPC service. It will allow accessing gRPC services from outside the Kubernetes cluster. 

### Implementation ideas

We can either reuse the "expose" attribute or introduce a specific gRPC attribute to expose the route. 
That feature would need documentation:

- if the service is using plain/text, we should document how the route must be configured to use edge TLS termination
- if the service is using TLS, we should document how the route must by-pass TLS checks

**Comment by michalszynkiewicz** [comment]
We may already have it, it needs to be checked.
CC @alesj

**Comment by cescoffier** [comment]
With the new gRPC server, it reuses the same port as HTTP. So, it will be covered that way. 

Marking is as won't fix - as it's somehow already fixed using the new server.
