### ISSUE TITLE
Rest client on Windows ignores properties in new format 

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#24763]
### Describe the bug

There is a new format of properties for Rest Client, which was added in https://github.com/quarkusio/quarkus/pull/17220. Unfortunately, when running in Windows environment, properties in this format are ignored/misread by Rest Client, which leads to the `Unable to determine the proper baseUrl/baseUri` error on start-up.

### Expected behavior

Similar properties should be processed similarly in any supported OS

### Actual behavior

Application which uses Quarkus Rest Client doesn't start on Windows and fails with error `Unable to determine the proper baseUrl/baseUri`

### How to Reproduce?

1. ` git clone git@github.com:fedinskiy/quarkus-test-suite.git -b reproducer/windows-properties`
2.  `cd quarkus-test-suite/http/rest-client-reactive`
3. `mvn clean verify -Dit.test=ClassicPropertiesIT#shouldGetBookFromRestClientJson` # this works, since it uses old-style `/mp-rest/url` property
4.  `mvn clean verify -Dit.test=ClientBookResourceIT#shouldGetBookFromRestClientJson` # this fails, since it uses new-style `quarkus.rest-client."MyClass".url` property

On Linux system everything works in the same way

### Output of `uname -a` or `ver`

Microsoft Windows Server 2022   10.0.20348

### Output of `java -version`

temurin 11.0.14+101

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.5

**Comment by geoand** [comment]
cc @TomasHofman

**Comment by TomasHofman** [comment]
I will take a look.

**Comment by TomasHofman** [comment]
Hello @fedinskiy, to double check - I assume the test that is supposed to fail is `ClientBookResourceIT.shouldGetBookFromRestClientJson`?

**Comment by fedinskiy** [comment]
@TomasHofman yes, it's ClientBookResourceIT, thank you! Bug description fixed

**Comment by TomasHofman** [comment]
@fedinskiy I start to think the problem is in the test setup. When I copy the `modern.properties` file into `application.properties` in the `resources/` directory, without any other changes to the code, the test passes. I'm not sure why the `classic` one works, but this looks suspicious.

**Comment by TomasHofman** [comment]
And these are present in the test log:

```
11:43:11,340 INFO  [app] 11:43:08,621 Unrecognized configuration key "quarkus.rest-client.io.quarkus.ts.http.restclient.reactive.ReactiveRestInterface.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
11:43:11,340 INFO  [app] 11:43:08,621 Unrecognized configuration key "quarkus.rest-client.io.quarkus.ts.http.restclient.reactive.files.FileClient.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

It looks that on Windows we loose the quote (") marks in the property names. I think it happens when these properties are applied via `new RestService().withProperties("modern.properties")` call. When properties are read directly from a property file by Quarkus (i.e. when the `application.properties` file is present in the jar) it behaves correctly.

**Comment by fedinskiy** [comment]
@TomasHofman wow, thank you for the analysis!
Looks like you're right and the error is in the test framework.

**Comment by geoand** [comment]
Thanks a lot for the effort @TomasHofman
