### ISSUE TITLE
Allow us to configure dynamic query parameters in the rest client 

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#24764]
### Description

In certain scenarios it's not possible to know all query parameters in advance and to configure these accordingly with the `@QueryParam("verbose")` annotation. Other frameworks offer solutions for this, like annotating a map parameter with a `@RequestParam` annotation: 

```
@RequestMapping(
    path = "/{id}/assets/with-options",
    method = RequestMethod.GET
)
public ResponseEntity<Collection<Asset>> getAssetsWithOptions(
    @PathVariable("id") String name,
    @RequestParam Map<String, String> params
) {
    ...
}
```

It would be nice if we would have an option to configure dynamic query paramters in quarkus as well. There is a workaround for this by adding a ClientRequestFilter, i.e: 

```
@Provider
public class GetMessageBodyFilter implements ClientRequestFilter {
    @Override
    public void filter(ClientRequestContext requestContext) throws IOException {
        if (requestContext.getEntity() instanceof Map && requestContext.getMethod().equals(HttpMethod.GET)) {
            UriBuilder uriBuilder = UriBuilder.fromUri(requestContext.getUri());
            Map allParam = (Map)requestContext.getEntity();
            for (Object key : allParam.keySet()) {
                uriBuilder.queryParam(key.toString(), allParam.get(key));
            }
            requestContext.setUri(uriBuilder.build());
            requestContext.setEntity(null);
        }
    }
}
```
This method is a bit cumbersome though imo.

**Comment by geoand** [comment]
We should definitely allow this for query params and I would assume also form params and header params.

We should probably use the `@RestQuery` (and friends) annotation to mark these parameters as they don't require a name (which in this case doesn't make sense anyway).

@michalszynkiewicz does that sound good? If so, I'll pick this up.

**Comment by michalszynkiewicz** [comment]
yes, thank you! :)

**Comment by sberyozkin** [comment]
How about using `@UriInfo` injection in the endpoint without any query parameters in the method signature ?

**Comment by sberyozkin** [comment]
Never mind, sorry, forgot you are talking about the rest client

**Comment by u6f6o** [comment]
> Never mind, sorry, forgot you are talking about the rest client

👍  Np, my first example code is a bit miss-leading, as it shows the controller method instead of the rest-client method.
