### ISSUE TITLE
Datasources guide doesn't mention Oracle?

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#24771]
### Description

The Quarkus Datasources guide (https://quarkus.io/guides/datasource#dev-services) doesn't mention Oracle anywhere. Should it?

**Comment by gsmet** [comment]
It mentions Oracle already a few times but not everywhere it should be. It has already been fixed by @yrodiere here: https://github.com/quarkusio/quarkus/pull/24623/files thanks to the DeLorean we recently bought.

**Comment by edeandrea** [comment]
Thanks @gsmet !

**Comment by edeandrea** [comment]
https://github.com/quarkusio/quarkus/pull/24802

**Comment by yrodiere** [comment]
> thanks to the DeLorean we recently bought

Or maybe the one we *will* buy?

> if you would re-open it

Done!
