### ISSUE TITLE
Setting @NamedQuery to cacheable=true cause hibernate to generate N queries for Collections

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#2478]
I noticed that quarkus was generating a lot more DB load than another framework when returning simple findAll queries against postgres.  

For an entity annotated with;

```
@Entity
@Table(name = "known_fruits")
@NamedQuery(name = "Fruits.findAll",
      query = "SELECT f FROM Fruit f ORDER BY f.name",
      hints = @QueryHint(name = "org.hibernate.cacheable", value = "true") )
public class Fruit {
```
I see the following query sent over the wire;

```
select fruit0_.id as id1_0_0_, fruit0_.name as name2_0_0_ from known_fruits fruit0_ where fruit0_.id=$1
```
with postgres returning one result at a time from the table. N queries are sent for the number of records stored in the table.

If I remove the QueryHint "org.hibernate.cacheable", and the entity is annotated with;

```
@Entity
@Table(name = "known_fruits")
@NamedQuery(name = "Fruits.findAll",
      query = "SELECT f FROM Fruit f ORDER BY f.name")
public class Fruit {
```
I see the correct query being sent over the wire, and all results returned in a single resultset from postgres

```
select fruit0_.id as id1_0_, fruit0_.name as name2_0_ from known_fruits fruit0_ order by fruit0_.name
```

**Comment by johnaohara** [comment]
I am not entirely sure this is an actual issue, or expected behaviour.  

I saw this behaviour when I had QueryCache enabled for a select all query `SELECT f FROM Fruit f ORDER BY f.name` but I had disabled the second level entity cache for Fruit.  In this scenario, if hibernate finds a cached query result, but no entities in the 2lc, does hibernate send a query for each entity id it finds in the query cache?

I was comparing against Thorntail, which did not have this behaviour.  But it maybe the QueryCache was not configured correctly in Thorntail, and Quarkus was configured correctly.

@gsmet / @Sanne please could you confirm this if this expected behaviour?

**Comment by gsmet** [comment]
I'm not sure how exactly the entity are loaded when a query is cached and you don't have a 2nd level cache for the loaded entities.

@gbadner could you shed some light on this behavior?

**Comment by Sanne** [comment]
yes this is expected behaviour: caching of queries works via two independent levels: identify the ids of matching entities, then load the entities individually; in such a case you'd want to enable 2LC on the entity as well.

I guess Thorntail didn't have the same caching configuration?
