### ISSUE TITLE
quarkus.knative.image-pull-secrets does not work

### ISSUE THREAD

**Issue by loban** [quarkusio/quarkus#24784]
### Describe the bug

In one's `application.ini`,
- setting `quarkus.knative.image-pull-secrets` does **NOT** add the values to the generated `knative.yml` file
- setting `quarkus.kubernetes.image-pull-secrets` DOES add the values to the generated `kubernetes.yml` file

### Expected behavior

Both `quarkus.knative.image-pull-secrets` and `quarkus.kubernetes.image-pull-secrets` should work.

### Actual behavior

Only `quarkus.kubernetes.image-pull-secrets` works.

### Quarkus version or git rev

2.7.5.Final

**Comment by iocanel** [comment]
Thanks for pointing this out @loban I will have a look asap.
