### ISSUE TITLE
Update Early Access JDK Build to 19-ea, add 18 to regular CI

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#24789]
### Description

18 reached GA last month, time to move on.

Current issues:
- [x] as usual, Groovy and Gradle need updates:
  - [x] https://github.com/apache/groovy/pull/1690#issuecomment-1088622192
  - [x] https://github.com/gradle/gradle/issues/20372
  - [x] Groovy in `maven-invoker-plugin` is a bit of a mess, analyzing...
- [x] Mockito/ByteBuddy needs an update as well: https://github.com/raphw/byte-buddy/issues/1228
  PR: #24912
- [x] Temurin build `19-beta+15-202203260328` fails with a TLS/SSL issue while trying to download mvnw but Zulu `build 19-ea+14` gets past that
  _Obsolete since switching to java.net distribution via #26374_

See also: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Java.2018.20.26.2019.20EA

WIP: https://github.com/famod/quarkus/tree/ci-jdk-19-ea

**Comment by famod** [comment]
Switch to 19-ea was made via #26374 but we still need to stabilize via workarounds. That PR contains valuable info w.r.t. groovy toolchains.

**Comment by geoand** [comment]
@famod is there anything else to do here?

**Comment by famod** [comment]
I think it's time to close this and create more specific issues if needed.

There is at least one known issue in the EA build with Java 19 (and above): #31528

All in all, the state of the EA job is a bit messy.
