### ISSUE TITLE
Integrate JSON Schema serde

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24791]
### Description

Integrate JSON Schema serializer and deserializer for Kafka.
Initially, this work should use the Apicurio Json Schema serde but also use the Confluent alternative.

**Comment by cescoffier** [comment]
This issue was not Vert.x related, but using Apicurio and Confluent JSON Schema serializer and deserializer for Kafka. It's not about a "general-purpose" JSON Schema support.

**Comment by cescoffier** [comment]
\CC @alesj

**Comment by carlesarnal** [comment]
@cescoffier there is still interest in this? If yes I might be interested in implementing/helping.

**Comment by cescoffier** [comment]
@carlesarnal We are very interested! let me know if you want to discuss it (with me or @ozangunalp)

**Comment by carlesarnal** [comment]
> @carlesarnal We are very interested! let me know if you want to discuss it (with me or @ozangunalp)

Great, let me take a look first a the existing code regarding Avro and I will contact you. Thanks!

**Comment by carlesarnal** [comment]
Since the first one has been approved, I went ahead and created a second one containing the Confluent one https://github.com/quarkusio/quarkus/pull/37870.
