### ISSUE TITLE
Enable contextPath support for SR OpenAPI Swagger UI

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#24797]
### Describe the bug

Use case

- in production environment our app is served directly under root "/" path
- in staging environment our app is served behing a nginx proxy_pass using a contextpath of "/example" : nginx below
```
	location /example {

		proxy_pass http://localhost:8080/;
		proxy_redirect     off;
		proxy_set_header   Host $host;

	}
```

- its swagger UI openapi defaults to http://localhost/example/q/swagger-ui/
- unfortunately the "Explore" form input does not honor the contextPath, see screenshot https://imgur.com/a/L5xMF7h
- you can explore by manually entering to the input field "/example/q/openapi"
- however the openAPI paths do not honor the contextPath either, but as suggested by @phillip-kruger in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/relaxing.20build.20time.20property.20quarkus.2Ehttp.2Eroot-path.20.3F/near/277277998  using a https://download.eclipse.org/microprofile/microprofile-open-api-1.0/apidocs/org/eclipse/microprofile/openapi/OASFilter.html can fix and rewrite them, as in the pseudocode below
- still, this OASFilter does not completely solve the bug since the form input of the screenshot remains ko, see screenshot

```
class OpenApiFilter : OASFilter {

    override fun filterOpenAPI(openAPI: OpenAPI?) {
val contextPath = "/example"
            LOG.info("""!!!!! REWRITING OpenAPI paths using contextPath $contextPath for profile $profile !!!!!""")
            val rewrittenPaths = PathsImpl()
            val paths = openAPI!!.paths
            val keys = paths.pathItems.keys
            keys.forEach{ k ->
                rewrittenPaths.addPathItem("""$contextPath$k""", paths.pathItems.get(k))
            }
            openAPI.paths(rewrittenPaths)
        
        super.filterOpenAPI(openAPI)
    }
}
```

### Expected behavior

Perhaps https://github.com/quarkusio/quarkus/blob/main/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java could register a runtime processor to rewrite the contextPath at runtime - and not at build time since the path may not be known until runtime, given an nginx or apache may exist

### Actual behavior

The openAPI endpoints are not accessible using "try it out" nor "explore" Swagger UI buttons or http calls unless you rewrite them

### How to Reproduce?

1. set up an nginx proxy 
```
	location /example {

		proxy_pass http://localhost:8080/;
		proxy_redirect     off;
		proxy_set_header   Host $host;

	}
```
2. hit http://localhost/q/swagger-ui/index.html. 
3. the API paths will not work

### Output of `java -version`

jdk11

### Quarkus version or git rev

2.7.5

**Comment by MikeEdgar** [comment]
@laurentperez have you tried using the `servers` section for this? This will give you two selections in SwaggerUI.

```yaml
servers:
  - url: /
  - url: /example
```
This can be set with property `mp.openapi.servers=/,/example` (or using annotations, or the filter). In combination with [`quarkus.swagger-ui.urls`](https://quarkus.io/guides/all-config#quarkus-swagger-ui_quarkus.swagger-ui.urls-urls) set to `/q/openapi,/example/q/openapi`, you will have both options enabled in the UI.

**Comment by phillip-kruger** [comment]
@laurentperez closing as @MikeEdgar suggestion is the way to do this. If you want to discuss more please reopen

**Comment by Dougniel** [comment]
> @laurentperez closing as @MikeEdgar suggestion is the way to do this. If you want to discuss more please reopen

Unfortunately this solution only works for paths that are known in advance, not for dynamic ones (ex: per version context path). Moreover as [quarkus.swagger-ui.urls](https://quarkus.io/guides/all-config#quarkus-swagger-ui_quarkus.swagger-ui.urls-urls) is a build time property, is not possible to set it up dynamically at deployment time.

☝️ To work with dynamic paths, I set up `quarkus.swagger-ui.urls.default=../openapi` (to put it path independent) and `QUARKUS_SMALLRYE_OPENAPI_SERVERS=/my-dynamic-path` at deployment time and it works well to display swagger-ui correctly and to make a call with `Try it out` with Quarkus 2.13.3 

👉🏼 IMO it's a bit weird to setup - is there a way to have this behaviour (path independent) working out of box ?
