### ISSUE TITLE
Exception mapper not handling failed login attempts

### ISSUE THREAD

**Issue by soldev21** [quarkusio/quarkus#24790]
### Describe the bug

I want to log failed login attempt.
So I generated quarkus RESTEasy JAX-RS example from https://code.quarkus.io/
Then applied some changes shown below.

1.Added some security [configs](https://github.com/soldev21/quarkus-security-exception-mapper/blob/1644a8e6fe93f79bcb136c95a9dda90f3f4378fa/src/main/resources/application.properties#L1)
2.Added two exception mappers. [AuthenticationFailedException](https://github.com/soldev21/quarkus-security-exception-mapper/blob/1644a8e6fe93f79bcb136c95a9dda90f3f4378fa/src/main/java/org/acme/AuthenticationFailedExceptionMapper.java#L14) and [AuthenticationCompletionException](https://github.com/soldev21/quarkus-security-exception-mapper/blob/1644a8e6fe93f79bcb136c95a9dda90f3f4378fa/src/main/java/org/acme/AuthenticationCompletionExceptionMapper.java#L13)
3.Edited the test [class](https://github.com/soldev21/quarkus-security-exception-mapper/blob/1644a8e6fe93f79bcb136c95a9dda90f3f4378fa/src/test/java/org/acme/GreetingResourceTest.java#L10).
Despite of changes above the exception mappers don't catch any exception regarding the failed Basic authentication attempt.

Any thoughts on this?

### Expected behavior

Catch AuthenticationFailedException and AuthenticationCompletionException in according exception mappers.

### Actual behavior

Bypass the exception mappers.

### How to Reproduce?

1. git clone https://github.com/soldev21/quarkus-security-exception-mapper.git
2. cd quarkus-security-exception-mapper
3. Run  `./mvnw compile quarkus:dev`
4. Open http://localhost:8080/ in browser and try to login with fake credentials

### Output of `uname -a` or `ver`

Ubuntu 21.10

### Output of `java -version`

openjdk version "11.0.13"

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by soldev21** [comment]
Hi @sberyozkin, is there any estimation or plan regarding this issue. I did some investigation and found class named `io.quarkus.vertx.http.runtime.security.HttpAuthenticator`. It has `Uni<SecurityIdentity> attemptAuthentication(final RoutingContext routingContext)` method which seems handles all authentication process with predefined HttpAuthenticationMechanisms. Can we intercept this method somehow? Or is this appropriate way to intercept authentication process?

**Comment by sberyozkin** [comment]
Please try https://quarkus.io/guides/security-built-in-authentication#how-to-customize-authentication-exception-responses

**Comment by geoand** [comment]
@sberyozkin is this perhaps handled now?

**Comment by sberyozkin** [comment]
Hi @geoand I'm just checking issues and have found your comment, sorry. I think so, Michal, @michalvavrik, you've fixed it, right ?

**Comment by geoand** [comment]
👌

**Comment by michalvavrik** [comment]
@sberyozkin nope, I only fixed it for RESTEasy Reactive, but I just got familiar with how RESTEasy Classic process requests and there is a way to fix it too. Will do, thx for a hint

**Comment by michalvavrik** [comment]
> The same behavior with quarkus.http.auth.form.enabled=true. I want to send 401 response code when auth failed (to handle that in HTMX) but can't catch AuthenticationFailedException. Tried implementing both ways as describedhere https://quarkus.io/guides/security-proactive-authentication#customize-auth-exception-responses - both don't work.

Try https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-auth-form-error-page set to `quarkus.http.auth.form.error-page=`.

In general, what you describe is not nearly enough to look into the issue. If you put together a reproducer and open Quarkus issue, I'll look into it and fix the issue. Thanks
