### ISSUE TITLE
Add Spotify OIDC provider configuration

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#24793]
### Description

See https://developer.spotify.com/documentation/general/guides/authorization/code-flow/
(PKCE is also supported)

@FroMage That can be an interesting demo with Renarde, a user is authenticated via Spotify and a music is streaming via Renarde :-).

As far as this issue is concerned it would be good to have `quarkus.oidc.provider=spotify`. 
It should work though with Spotify once #24774 is merged. (@rafaelsousa - please give it a try once it is merged)

**Comment by FroMage** [comment]
If I can expense a Spotify account, I might want to do this ;)

**Comment by gastaldi** [comment]
AFAIR you don't need to be a Premium user to create an OIDC app in https://developer.spotify.com/dashboard. That looks fun, I'll give it a shot 😉
