### ISSUE TITLE
Spring Data Interface Projection only works if defined in same repository as used

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#24800]
### Describe the bug

When using the interface projection feature with the spring data layer, we have this error if we don't define the projection interface in the same repository as used.

```java
java.lang.IllegalAccessError: class org.cnje.kiwi.event.repository.EventEnrollmentRepository_3777848de63326f296cc69059d5e1dc6d2fe63e9Impl$$function$$1 tried to access method 'org.cnje.kiwi.event.dto.query.JuniorWithPlaces_5decffa0b6323520b2fbb38fbc4c77a28b3bbd2f org.cnje.kiwi.event.dto.query.JuniorWithPlaces_5decffa0b6323520b2fbb38fbc4c77a28b3bbd2f.convert_countByEventAndStateIsTrue(java.lang.Object[])' (org.cnje.kiwi.event.repository.EventEnrollmentRepository_3777848de63326f296cc69059d5e1dc6d2fe63e9Impl$$function$$1 and org.cnje.kiwi.event.dto.query.JuniorWithPlaces_5decffa0b6323520b2fbb38fbc4c77a28b3bbd2f are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @7c53a9eb)
```

### Expected behavior

We can define the interface anywhere in the project

### Actual behavior

We can only define it in the same repository as used

### How to Reproduce?

Tested with 2.7.4.Final and 2.7.5.Final

1. Create a project using the spring data extension
2. Create a custom query returning an interface
3. Use it

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.5

**Comment by geoand** [comment]
Thanks for reporting. Mind putting together a sample project that demonstrates the issue?

**Comment by Plawn** [comment]
Yes, I will provide a github repository asap

**Comment by geoand** [comment]
I was able to reproduce this and opened https://github.com/quarkusio/quarkus/pull/24865 to fix it

**Comment by Plawn** [comment]
@geoand thanks ! sorry for being late to the party

**Comment by geoand** [comment]
np!
