### ISSUE TITLE
quarkus.container-image.labels doesn't work with Jib

### ISSUE THREAD

**Issue by andreaTP** [quarkusio/quarkus#24820]
### Describe the bug

When using Jib (and also `s2i` and `buildpack`) to build container images the option `quarkus.container-image.labels` is ignored.

### Expected behavior

When building a container image the `labels` setting should be honored independently from the container image extension that is used.

### Actual behavior

With Jib (and other container image extensions such as "buildpack") the label is not injected into the container image.

### How to Reproduce?

```bash
quarkus create
cd code-with-quarkus
quarkus extension add 'container-image-jib'
mvn clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.image=test.io/test:latest -Dquarkus.container-image.labels.FOO=BAR -DskipTests
docker inspect test.io/test:latest | jq '.[0].Config.Labels.FOO'
```

Result:
```
null
```
Changing the "container-image extension" and using `container-image-docker` the output is the expected one:
```
"BAR"
```

### Output of `uname -a` or `ver`

Darwin aperuffo-mac 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8) OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

### Additional information

Issue found in the Keycloak operator here:
https://github.com/keycloak/keycloak/pull/10949/files#diff-e3946c0d4cebe6233f6aa4079b21ddcd0e24e61fa7b46fb8e6a813c40a482a32R165

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/24834 fixes the Jib problem.

I'll let @iocanel take care of the buildpack and s2i ones if they are applicable
