### ISSUE TITLE
Update to GraalVM 19.0.0 failed to generate a native image

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#2483]
quarkus.version: 0.14.0
```text
Error: Class does not implement org.graalvm.nativeimage.hosted.Feature: io.quarkus.runner.AutoFeature
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

[SDK Since: 19.0](https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html)

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/issues/2412 .

You need to use the GraalVM version we indicate when we release:
- Quarkus 0.14.0 supports rc15
- Quarkus 0.15.0 supports rc16

We are working on supporting GraalVM 19 but we are not there yet.

Closing as duplicate.

**Comment by Sergey80** [comment]
same here.
graalvm                  19.2.1              GraalVM Core        
native-image             19.2.1              Native Image        github.com

<quarkus.version>1.0.0.CR1</quarkus.version>
