### ISSUE TITLE
Inconsistent extensions listing

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24835]
### Describe the bug

Inconsistent list of Quarkus extensions when running `mvn  quarkus:list-extensions` or `quarkus extension list -i`

Some of the entries have `✬` prefix, some do not have. Seems that Quarkus core ones have the prefix, the rest from the platform doesn't. I expect all of them to have the same prefix.

```
...
✬ quarkus-spring-security                            Quarkus Extension for Spring Security API
✬ quarkus-spring-web                                 Quarkus Extension for Spring Web API
  quarkus-tekton-client                              Quarkiverse - Tekton Client - Runtime
  quarkus-tika                                       Apache Tika
✬ quarkus-undertow                                   Undertow Servlet
  quarkus-univocity-parsers                          Univocity Parsers
  quarkus-unleash                                    Quarkus - Unleash - Runtime
✬ quarkus-vault                                      Vault
✬ quarkus-vertx                                      Eclipse Vert.x
✬ quarkus-vertx-graphql                              Eclipse Vert.x GraphQL
...
```

### Expected behavior

All the entries have the same prefix

### Actual behavior

Some of the entries have `✬` prefix, some do not have

### How to Reproduce?

 - generate project using CLI or https://quarkus.io/guides/getting-started#bootstrapping-the-project
 - list quarkus extensions - e.g. `mvn  quarkus:list-extensions` or `quarkus extension list -i`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.5.Final

**Comment by netodevel** [comment]
@rsvoboda, if it really is a bug I think this problem can be set to `"good first issue"`.

**Comment by geoand** [comment]
@maxandersen @ebullient is this the expected behavior?
If so, then I'll let you close this issue

**Comment by maxandersen** [comment]
It should have a star if it is in the platform referenced by the project. So it depends what the project points to ?

**Comment by ebullient** [comment]
I would almost rather strip "Quarkus Extension for " out entirely, as it takes up space and isn't particularly informative on its own.

**Comment by netodevel** [comment]
The star is really confusing whether it is a project dependency or an official extension of the quarkus.

WDYT about adding a new column with the purpose of saying if this extension is installed in the project?

Like this: 

✬ quarkus-spring-security  |   Installed  | Quarkus Extension for Spring Security API

**Comment by ebullient** [comment]
ok. the star was always platform or not... but you're saying that you would then like a separate indicator for whether or not it is installed.

**Comment by netodevel** [comment]
@ebullient, 
Ahhhh, now I understood.
but I still think it raises doubts about the little star hahahaah.

**Comment by ebullient** [comment]
yea.. we should add something to the footer to say what the star means..

**Comment by maxandersen** [comment]
Btw. Unleash and tekton is not in the platform so the star looks right. 

It's same star as shown on code quarkus.

**Comment by geoand** [comment]
@rsvoboda I just tried this and from a cursory look at the outputs, they now seem the same. 

Can you check and see if this has been fixed? 

Thanks

**Comment by rsvoboda** [comment]
Closing, outputs are equivalent now. Tried with Quarkus 3.14.4 CLI and 3.14.4 maven plugin

```
mvn io.quarkus.platform:quarkus-maven-plugin:3.14.4:list-extensions
quarkus extension list -i
```

**Comment by geoand** [comment]
👍🏽
