### ISSUE TITLE
Add Twitch OIDC Provider

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#24833]
### Description

See https://dev.twitch.tv/docs/authentication/getting-tokens-oidc/#oidc-authorization-code-grant-flow

**Comment by sberyozkin** [comment]
Hey @gastaldi It should already work in Quarkus, but once we confirm it we will add an option to configure it compactly, instead of using 10 properties,  I'm on PTO, will ping next to discuss the details

**Comment by VanillaSpoon** [comment]
Hey :) could I take a shot at this issue?

**Comment by sberyozkin** [comment]
Sure, it would be great

**Comment by VanillaSpoon** [comment]
Thanks @sberyozkin :)

**Comment by sberyozkin** [comment]
@VanillaSpoon Np at all, thanks to @gastaldi for creating this good first issue

**Comment by VanillaSpoon** [comment]
Hey @sberyozkin @gastaldi apologies for the delay with this. Had some setbacks but I will have a PR early this week :)

**Comment by sberyozkin** [comment]
@VanillaSpoon Np, take your time please

**Comment by geoand** [comment]
Has this been implemented?

**Comment by VanillaSpoon** [comment]
Hi @geoand 
Sorry, I am unable to complete this currently. Would it be ok if I pass on the ticket?

**Comment by geoand** [comment]
Absolutely, thanks for letting us know

**Comment by geoand** [comment]
Go for it :)

**Comment by sberyozkin** [comment]
@VanillaSpoon Hey, np at all, thanks for the update. Welcome @biswassri

**Comment by geoand** [comment]
@biswassri hey, just checking in :). Were you able to look into this?

**Comment by biswassri** [comment]
@geoand hey! Yes, I have been able to progress on it and I'm currently testing out my changes. I'm hopeful I should have a PR by early next week. Sorry for the delay!

**Comment by Harshitsoni2000** [comment]
Hi @geoand, @sberyozkin, is this still open? If so, I would love to work on Twitch Integration.
