### ISSUE TITLE
Native Image JIB Builds with existing Quarkus version 2.7.3 are suddenly broken

### ISSUE THREAD

**Issue by goafabric** [quarkusio/quarkus#24837]
### Describe the bug

Existing builds, with existing Sourcecode inside Github (Actions),
with existing Version 2.7x (tested with 2.7.3 + 2.7.5) are unpexectedly broken for a couple of days now.
While previous builds had this information:
[io.quarkus.container.image.jib.deployment.JibProcessor] Starting (local) container image build for native binary using jib.

Retriggering the same build are now missing the log
and thus not building a docker image at all.
That's really confusing that we have breaking change in an existing version.

From what i can see inside quay, there seem to be changes to the existing
ubi-quarkus-native-image:21.3-java11

Maybe this is the root cause ?

When building on my local arm image, that uses its own "frozen" builder image,
it still works as expected.

### Expected behavior

Docker Image should be built

### Actual behavior

Docker images not build any more.
After the log "# Printing build artifacts to",
the jib image build is skipped and than the tests are executed

### How to Reproduce?

Rebuild an existing "quarkus-container-image-jib" build.
Worked a couple of days ago .. does now not produce an image any more

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 LTS

### Quarkus version or git rev

2.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by geoand** [comment]
Thanks for reporting, but with the information provided I don't see us being able to do much

**Comment by goafabric** [comment]
I honestly don't know what more information to provide ..
I can provide an github action link.
From the history you can see that the same build once worked and is now broken due to docker push now failing.
Because of the missing image.

From there you could also navigate to the github repo and its adherent branch
https://github.com/goafabric/callee-service-quarkus/actions/runs/2011590000

**Comment by geoand** [comment]
The base image is for the native build is `quay.io/quarkus/quarkus-micro-image:1.0` and seems to work properly

**Comment by goafabric** [comment]
This is NOT about the base image, but about the BUILDER Image.
And now the Base Image has other already acknolwledged problems.
https://github.com/quarkusio/quarkus/issues/23281#issuecomment-1025198521

But this has nothing todo with this issue.

**Comment by geoand** [comment]
Okay, understood.

But the builder image (`quay.io/quarkus/ubi-quarkus-native-image:21.3-java11`) also works (I just tried it)

**Comment by goafabric** [comment]
Ok .. and you are using the latest version of this image (according to quay it had changes 5 days ago) ?
And this is also creating an image via jib ?
Sorry for asking .. but if yes .. that would mean that something has changed inside github ..
Whatever that could be to yield to such a result.
And i don't have any intel machine to verify this locally.

![image](https://user-images.githubusercontent.com/5617159/162424178-a69bd452-afde-40d2-b584-07dc24068bcb.png)

**Comment by geoand** [comment]
Yes, I just ran everything locally using the latest images.

**Comment by goafabric** [comment]
Yep you are right ... could retest on an intel vm .. this works as expected ...
It's still odd .. because if the same build worked and now changes his behav. .. that something odd is going on in github here ...
Because the Jibprocessor does not get invoked here any more ....
Maybe you have an idea ?

Other than that .. you can close the issue, sorry for the inconvinience

**Comment by geoand** [comment]
> Because the Jibprocessor does not get invoked here any more ....

Without a log, it's hard to understand what's going on.

> Other than that .. you can close the issue, sorry for the inconvinience

No problem

**Comment by gsmet** [comment]
@geoand there is a log here: https://github.com/goafabric/callee-service-quarkus/actions/runs/2011590000 but I suppose you need more details.

I still think we should try to investigate if @goafabric can provide more information because it looks extremely odd.

**Comment by geoand** [comment]
> there is a log here: https://github.com/goafabric/callee-service-quarkus/actions/runs/2011590000 but I suppose you need more details.

Already saw it, does not contain any useful information

**Comment by goafabric** [comment]
@gsmet thanks for your support ... thats honestly all i can provide for now ...
local builds on intel and arm still work ... existing builds in github just fail, because the jib processor does not get fired any more .. but i don't know what trigger it needs to get fired ...

so it could be everything without knowing this .. if it e.g. tries to detect an existing file .. it could be that github is scraping the file 

i will trigger a build with 2.5.3 and see how this behaves

**Comment by geoand** [comment]
Darn... That maven issue has caused a lot of problems... (cc @famod)

**Comment by goafabric** [comment]
U2
