### ISSUE TITLE
Qute : Type-safe message bundle does not work if `@MessageParam` annotation is not used

### ISSUE THREAD

**Issue by arvind-das** [quarkusio/quarkus#24849]
### Describe the bug

While using the qute in type-safe mode , it causes 2 issues, this is different than provided in the documentation:

1.  The example shown [here ](https://quarkus.io/guides/qute-reference#type-safe-message-bundles) does not require the `@MessageParam` annotation and it will be picked/matched with the template value automatically. It does not happen.
2. Even after using the annotation we have to specify the value the model will be mapping, whereas annotation document says, it will be taken as element name. 

So, in order to use this is the complete format that I had to use:

```
@MessageBundle
interface AppMessages {

    @Message("Error! {model}  {message}")
    fun notFound(@MessageParam("model") model:String,@MessageParam("message") message:String):String
}
```

Verbosity is here, the default values could have been mapped. Not doing so results in 

> io.quarkus.qute.deployment.MessageBundleException: Unable to determine the name of the parameter at position 0 in method com.vibfam.posts.common.AppMessages#notFound()

### Expected behavior

The code should look like this since the default declarations must take place

```
@MessageBundle
interface AppMessages {

    @Message("Error! {model}  {message}")
    fun notFound( model:String, message:String):String
}
```

### Actual behavior

Using the structure mentiond in the doc, it throws exception

> io.quarkus.qute.deployment.MessageBundleException: Unable to determine the name of the parameter at position 0 in method com.vibfam.posts.common.AppMessages#notFound()

### How to Reproduce?

Simply use the class defined above and make a call like

`MessageBundles.get(AppMessages::class.java).notFound("User","could not be found with given name")`

### Output of `java -version`

11

### Quarkus version or git rev

2.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1 ------------------------------------------------------------  Build time:   2021-06-14 14:47:26 UTC Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e  Kotlin:       1.4.31 Groovy:       3.0.7 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.14.1 (Eclipse Adoptium 11.0.14.1+1) OS:           Windows 10 10.0 amd64

**Comment by gastaldi** [comment]
Is your Kotlin project compiling with `--parameters` JVM flag set? I have just created a test and I couldn't reproduce the issue you described here

**Comment by gastaldi** [comment]
That would be something like this in your `build.gradle.kts` file:

```kotlin
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    kotlinOptions.javaParameters = true
}
```

**Comment by arvind-das** [comment]
My gradle file did not have the above configuration mentioned.  Added this and it works. Is it there in the docs, looks like I missed that . Closing

**Comment by arvind-das** [comment]
Thanks
