### ISSUE TITLE
Support lambda function serialization in native image

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#24861]
### Description

It could be supported once it is available in the GraalVM. see https://github.com/oracle/graal/issues/3756

**Comment by gastaldi** [comment]
@zhfeng do you have a small project that reproduces the need for this feature? I think I have an idea on how to implement this enhancement.

**Comment by zhfeng** [comment]
@gastaldi not yet and I will create one based from the quarkus-mybatis lamba test. Thanks in advance!

**Comment by gastaldi** [comment]
A test would be even better 😉
