### ISSUE TITLE
`Unrecognized configuration key` warnings since 2.8.0.Final if using config property with list values in YAML

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#24878]
### Describe the bug

```yaml
quarkus:
  arc:
    ignored-split-packages:
      - foo.bar
```
results in a build warning in 2.8.0.Final, but not in 2.7.5.Final:
```
[INFO] --- quarkus-maven-plugin:2.8.0.Final:build (default) @ code-with-quarkus ---
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.arc.ignored-split-packages[0]" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1443ms
```

### Expected behavior

No warning, the key is valid.

### Actual behavior

`Unrecognized configuration key` warning

### How to Reproduce?

[q_build-warnings.zip](https://github.com/quarkusio/quarkus/files/8466095/q_build-warnings.zip)

`mvn clean package -DskipTests`

### Output of `java -version`

17.0.2, vendor: BellSoft

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

Also happens with e.g. `quarkus.qute.suffixes`.

Does not happen when using `application.properties`.

**Comment by j-be** [comment]
Same here, in our case it was `quarkus.arc.exclude-types` and `quarkus.http.cors.origins`.

It seems (only smoke tested for now) to still be working correctly though, i.e. CORS still does its thing and Arc ignores the given classes just fine.

Also, we found that using multi-line comma separated strings makes the Warning disappear, so instead of 

```yaml 
quarkus:
  http:
    cors:
      origins:
        - https://example.com
        - http://localhost:4200
```

one can simply do

```yaml
quarkus:
  http:
    cors:
      origins: >-
        https://example.com,
        http://localhost:4200,

**Comment by gsmet** [comment]
@radcortez has this been fixed by your latest SmallRye Config upgrade? If so, we should backport it.
