### ISSUE TITLE
Reactive REST client should provide value of invoked Method in the ClientRequestFilter

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#24877]
### Describe the bug

As per MP REST Client spec [0], `ClientRequestContext` passed into `ClientRequestFilter` should provide a property `org.eclipse.microprofile.rest.client.invokedMethod` of value `java.lang.reflect.Method`. This works with rest-client-classic:

```
@Provider
public class MyFilter implements ClientRequestFilter {
    @Override
    public void filter(ClientRequestContext requestContext) {
        System.out.println(requestContext);

        Method method = (Method) requestContext.getConfiguration()
            .getProperty("org.eclipse.microprofile.rest.client.invokedMethod");

        System.out.println(method.getDeclaringClass());
    }
}
```

but doesn't in the reactive version.

[0] https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/providers.asciidoc#clientrequestfilter 

### How to Reproduce?

https://github.com/xstefank/learning-tests/tree/master/rest-client-annotation

**Comment by xstefank** [comment]
@michalszynkiewicz let me know if I can help. I was able to trace down the creation of REST client subclasses but I don't see the relationship from the processor to the configuration that is passed in the filter.

**Comment by michalszynkiewicz** [comment]
Found it, it should be:

```java
 (Method) requestContext.getProperty("org.eclipse.microprofile.rest.client.invokedMethod");
```

and not 
```java
 Method method = (Method) requestContext.getConfiguration()
            .getProperty("org.eclipse.microprofile.rest.client.invokedMethod");
```

**Comment by xstefank** [comment]
thanks @michalszynkiewicz
