### ISSUE TITLE
Share the set of banned dependencies and their replacements with Quarkus ecosystem

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#24880]
### Description

This follows the discussion in https://github.com/quarkusio/quarkus-platform/pull/521

Quarkus does some conscious choices when it comes to preferring some artifacts and banning the alternatives. 

Jakarta spec jars are the most prominent example: Generally the jakarta spec artifacts are preferred and the obsolete alternatives coming from JBoss, Glassfish, javax and Geronimo are be banned. There are exceptions to this general rule (Quarkus in some cases prefers jboss or glassfish artifacts) and typically not all existing alternatives are banned (not sure why).

It is similar with logging backends: some third party artifacts are banned in favor of some JBoss logging artifacts.

It is generally beneficial for Quarkus Platform participants to stick with the policies adopted in Quarkus Core. On one hand this increases the chances to get working selection of artifacts in end user applications and on the other hand it may save time and cognitive load with deciding which alternative to choose.

From the platform participant PoV, it is easy to overtake the bans from Quarkus poms, but it is less easy and obvious to implement replacements towards the preferred alternatives. 

I wonder whether Quarkus Core maintainers, esp. @gsmet would be ready to maintain this kind of rules in structured form, so that platform participant projects and Quarkus Platform itself can observe/enforce them automatically. 

### Implementation ideas

I do not have any specific format or tool in mind. Enforcer plugin forks well for enforcing bans, but I am not aware that it would also allow enforcing replacements. I'd be thankful for any suggestions.

**Comment by ppalaga** [comment]
cc @aloubyansky @mjurc @tqvarnst

**Comment by ppalaga** [comment]
Any opinion on this @gsmet @aloubyansky ?

**Comment by gsmet** [comment]
Sorry, I'm quite busy these days with the Jakarta migration.
The enforcer doesn't allow us to provide replacements (even as a hint) and that's a bit of a bummer but if we want something done quickly, maybe we should keep using it?
I haven't found at a quick glance if we could use rules stored in a published XML file. If not, maybe we will end up having a custom rule that can get the info from a YAML file that contains both the banned dependency and the replacement and we could push the replacement as a hint in the error message?

@famod maybe you have some ideas about that?

**Comment by ppalaga** [comment]
An idea: Maybe we could add the replacement functionality to the existing enforcer ban rule?

**Comment by gastaldi** [comment]
There is the [independent-projects/enforcer-rules](https://github.com/quarkusio/quarkus/tree/main/independent-projects/enforcer-rules) module which publishes custom enforcer rules. 

I think we could move the `bannedDependencies` in the [build-parent](https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L494-L599) to a custom rule to facilitate reuse

**Comment by gastaldi** [comment]
FWIW I created https://issues.apache.org/jira/browse/MENFORCER-422 asking for reading a list of banned dependencies from an external file/URL

**Comment by gastaldi** [comment]
@ppalaga we can come up with a custom rule in the `enforcer-rules` project that would be checked against a predefined list of banned dependencies (defined in the same project, for example)

**Comment by famod** [comment]
Yeah, this could/should work.

Are we talking about rules enforced by the main repo or are we talking about multiple sets of rules?

**Comment by gastaldi** [comment]
@famod my understanding is that this request is for reusing this rule: https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L494-L599

**Comment by ppalaga** [comment]
> Are we talking about rules enforced by the main repo or are we talking about multiple sets of rules?

We (Camel Quarkus) are primarily interested in getting a way to consume the bans defined by Quarkus. 

Secondarily, it would be nice be able to define more bans and replacements in a similar way on our side, so that projects (such as Camel K) based on Camel Quarkus can consume them.

**Comment by ppalaga** [comment]
Any progress here? I am reviewing the dependency management in quarkus-cxf and having a list of banned artifacts and their replacements would be extremely useful.

**Comment by gastaldi** [comment]
No progress so far, but I can have a look if it's urgent

**Comment by gastaldi** [comment]
@ppalaga I created https://github.com/gastaldi/descriptor-rule as the initial prototype. It  is a custom enforcer rule that executes other enforcer rules declared in a shared descriptor (much like what was proposed in https://issues.apache.org/jira/browse/MENFORCER-422)

Take a look and let me know how that works for you. My plan is to release an alpha version so we can use it right away and then submit a PR to the [maven-enforcer-plugin](https://github.com/apache/maven-enforcer/) repository to incorporate as a built-in rule

**Comment by gastaldi** [comment]
I have also created a PR upstream: https://github.com/apache/maven-enforcer/pull/180
