### ISSUE TITLE
Passing Custom State Data for OIDC Auth Flows

### ISSUE THREAD

**Issue by vcatalano** [quarkusio/quarkus#24882]
### Description

Currently, the Quarkus OIDC extension doesn't allow developers to set custom state data as part of the `state` query parameter for the initial Authorization Request. Unfortunately, this state data is used quite frequently for passing information such as a "return to" URL or "invite code" as part of the user login flow. One work-around to this problem is to provide the "return to" URL or "invite code" as a query parameter to the Redirect Endpoint URI (https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2). Unfortunately, many authorization providers (e.g. Okta and Auth0) prevent developers from using wildcard parameters when configuring Redirect Endpoints thereby forcing developers to use the `state` query parameter to pass this custom data.

### Implementation ideas

A few ideas come to mind regarding how we can solve this problem.

1. Provide a configuration option with a list of query parameters that should be encoded and passed to the authentication server as part of the initial authorization request. For example, use the following Quarkus configuration property to enumerate the query parameters that would then be serialized as part of the `state` query parameter.

`quarkus.oidc.login.extra-params=invitationCode,cameFromUrl`

2. Expose functionality of the [CodeAuthenticationMechanism](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java) with dependency inject allowing developers build their own state bean. Primarily this functionality resides [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L650). Unfortunately, this would require users to create their own login endpoint within their app so this is less than ideal.

**Comment by sberyozkin** [comment]
@vcatalano Thanks for opening this enhancement request, can you clarify please, how would you calculate these extra parameter values if you were to implement the code flow directly in the endpoint, is the relevant information encoded in the current request URI ?

For example, do you have a flow similar to:
1. `GET /login?invitationCode=someCode`
2. The user is redirected, authenticates, redirected back to `/callback` and you need to access the original `invitationCode` in the `/callback` endpoint method ?

Right now we can actually restore such query parameters (they are stored in a state cookie) - but I don't recall now why exactly I restricted it to a case where the redirect URI is [the same as the original request URI](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L656) (probably to simplify things), so I think we can just relax it and restore them such that they get appended to the configured callback URL.

Would that be enough ? See, the `state` is only relevant before a `code` returned alongside this `state` is exchanged for the tokens - but `quarkus-oidc` is dealing with exchanging the code for the tokens - so if we encode this extra info in a state then it is not clear how to make these extra info available to the endpoint.

I guess 2 things will need to be done,

1. Make sure the original query parameters can be restored to the callbacks which are not the same as the original request URIs
2. Let users contribute some additional custom parameters that will need to be restored, something similar to your proposal, but probably via an injected interface like `StateParameters` which will have `Map<String, String> createStateParameters(RoutingContext)` where the users will check all what is needed in the current request.

**Comment by vcatalano** [comment]
@sberyozkin It was my understanding that the initial authorization request `state` query parameter was the same `state` query parameter returned to the authentication redirect path (the config parameter defined  using `quarkus.oidc.authentication.redirect-path`). However, this appears to not be the case. The `state` query parameter returned to the redirect path is a UUID whereas the `state` query parameter send on the initial request is the encoded [state bean](https://github.com/quarkusio/quarkus/blob/56879dde70ca4efaf65dd958392afeab9156f47f/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationStateBean.java#L3)

The login flow that you outlined is exactly the case that I am trying to handle. The main problem I seem to be having is the Auth0 `/callback` endpoint must be static it cannot have dynamic components such as `invitationCode`

> Right now we can actually restore such query parameters (they are stored in a state cookie) - but I don't recall now why exactly I restricted it to a case where the redirect URI is [the same as the original request URI](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L656) (probably to simplify things), so I think we can just relax it and restore them such that they get appended to the configured callback URL.

If we could restore the URL queries as part of the redirect URI and return them as part of the callback URL, I think that would handle this use case properly.

These steps makes sense to me.

**Comment by sberyozkin** [comment]
@vcatalano 

>It was my understanding that the initial authorization request state query parameter was the same state query parameter returned to the authentication redirect path (the config parameter defined using quarkus.oidc.authentication.redirect-path). However, this appears to not be the case. The state query parameter returned to the redirect path is a UUID whereas the state query parameter send on the initial request is the encoded [state bean](https://github.com/quarkusio/quarkus/blob/56879dde70ca4efaf65dd958392afeab9156f47f/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationStateBean.java#L3)

No, in all the case what goes to the OIDC provider is a `state` query parameter, random value - but it it tied to a cookie so that when it is returned back we can assert it is part of the same flow. The bean you linked to is currently only used to represent that state cookie's value if PKCE is required. It might change, but it is only about the state cookie value, not the query parameter.

> If we could restore the URL queries as part of the redirect URI and return them as part of the callback URL, I think that would handle this use case properly.

So can you confirm please that the only thing which is required in your case at this moment is to make sure that the query parameters from the original request are made available to the callback method ?

I'd like to avoid another bean like `StateParameters` unless a specific requirement exists.

Thanks
