### ISSUE TITLE
Classloader Issues on MultiModule Project Tests

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#24895]
### Describe the bug

A Multimodule project in test mode gets classcast exceptions injecting beans. This started in 2.7.0 +

Works fine in 2.6.*

The specific case is there the multi module project has a library which is used in 2 modules - one of which is in the project itself and another is just included in the quarkus package.

### Expected behavior

Tests should pass

### Actual behavior

Tests fails due to class cast exceptions

### How to Reproduce?

git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/multi-module/mm-2
mvn clean install
cd ..
mvn clean verify

If you change quarkus version in the mm-2 pom and main pom to 2.6.3.Final then the projects tests work fine.

If you add mm-2 as a module in MultiModule then the tests pass but that should not be necessary.

**Comment by aloubyansky** [comment]
@glefloch are you thinking of looking into this one?

**Comment by glefloch** [comment]
yes

**Comment by bcluap** [comment]
No luck on fixing this for 2.9.0?

**Comment by gsmet** [comment]
@aloubyansky @glefloch any chance one of you could have a closer look at this one? It's blocking the upgrades of @bcluap and he always have provided good feedback on the CRs and now can't.

**Comment by glefloch** [comment]
@aloubyansky if you could have a look that would be great. I tried working on it but I haven't found anything relevant :/

**Comment by aloubyansky** [comment]
I looked into this, it's not going to be a quick fix, unfortunately. However I find the issue being critical enough and will work on it this week. I think fixing this could help other projects, e.g. Kogito, with their CI configs.

**Comment by bcluap** [comment]
Great news. Will test it today

**Comment by ismailsimsek** [comment]
Running into this issue with 2.11.3.Final and 2.12.0.Final downgrading Quarkus to 2.6.3.Final fixed it. 

[Failing Code is here](https://github.com/memiiso/debezium-server-bigquery/tree/add_iso_datetime_converter)

Test class is [ChangeConsumerConverterTest.java](https://github.com/memiiso/debezium-server-bigquery/blob/add_iso_datetime_converter/debezium-server-bigquery-sinks/src/test/java/io/debezium/server/converters/ChangeConsumerConverterTest.java)

```
 java.lang.ClassCastException: class io.debezium.server.converters.TemporalToISOStringConverter cannot be cast to class io.debezium.spi.converter.CustomConverter (io.debezium.server.converters.TemporalToISOStringConverter is in unnamed module of loader 'app'; io.debezium.spi.converter.CustomConverter is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @153cfd86)
    at io.debezium.config.CommonConnectorConfig.lambda$getCustomConverters$1(CommonConnectorConfig.java:767)
    
```

**Comment by gsmet** [comment]
@ismailsimsek please create a different issue. Looks like you have a reproducer, that is great, don’t forget to mention it there. Thanks.

**Comment by aloubyansky** [comment]
I'll have a look into it. @ismailsimsek if you create a new issue, please, mention me. Thanks.
