### ISSUE TITLE
RestEasy resources cannot be accessed using absolute URI

### ISSUE THREAD

**Issue by user667** [quarkusio/quarkus#24898]
### Describe the bug

Accessing any RestEasy resource using an absolute URI results in a status code 404.

Failing example:
```http request
GET http://localhost:8081/hello/g HTTP/1.1
Accept: */*
Host: localhost:8081
```

Working example:
```http request
GET /hello/g HTTP/1.1
Accept: */*
Host: localhost:8081
```

According to  [RFC2616 Hypertext Transfer Protocol -- HTTP/1.1 > Request-URI](https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2):
> To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies.

We migrated from Thorntail to Quarkus and suddenly consumers couldn't connect to any of the resources anymore.

Sidenote: Health endpoint from `io.quarkus:quarkus-smallrye-health` and metrics endpoints from `io.quarkus:quarkus-smallrye-metrics` work both ways.

### Expected behavior

Requests using absolute URIs should work.

### Actual behavior

Requests using absolute URIs do not work and result in status code 404.

### How to Reproduce?

Reproducer: https://github.com/user667/quarkus-resteasy

Run `mvn clean install`

### Output of `uname -a` or `ver`

Darwin 21.4.0 Darwin Kernel Version 21.4.0

### Output of `java -version`

OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
Not sure what the problem is, but if you swap `quarkus-resteasy` with `quarkus-resteasy-reactive` (which is our default REST stack going forward), things work just fine.
