### ISSUE TITLE
Warning is shown in dev mode in Quarkus 2.8 / ¿Windows?

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#24897]
### Describe the bug

Today we are delivering a Quarkus Workshop and some attendees get a warning when using dev mode. I don't have much information about but it seems it was in Windows machine and maybe using mingw thingy

![unnamed](https://user-images.githubusercontent.com/1517153/163028144-7ead2c4f-64b5-4726-9bfc-f9bd69a10c04.png)
.

### Expected behavior

No warning should be shown? It's not blocker but it makes people ask things.

### Actual behavior

Shows a warning

### How to Reproduce?

I have not been able to reproduce it on my machine (Mac) but in other attendees with Windows found it.

### Quarkus version or git rev

Quarkus 2.8.1

**Comment by Erfankam** [comment]
@lordofthejars Have you used any profile in application.properties file?

**Comment by gastaldi** [comment]
Check if your settings.xml does not contain an `<activeProfile>artifactory</activeProfile>`. Closing for now, please reopen when a reproducer project is available.
