### ISSUE TITLE
Streamlined config test profiles

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#24901]
### Description

Many uses of `@TestProfile` I have encountered (including many of the uses in Quarkus core) use this mechanism to override a few config properties. I.e. the referenced class overrides `QuarkusTestProfile#getConfigOverrides()` and / or also `QuarkusTestProfile#getConfigProfile()`. This is a very useful mechanism but it has the downside of being rather verbose.

I would like to see a streamlined alternative, which doesn't require declaring a full-blown `QuarkusTestProfile` subclass, but only list the config overrides and / or config profile to be used using string literals.

### Implementation ideas

What I had in mind would be something like this:

```java
@QuarkusTest
@TestProfile(configOverrides = """
        quarkus.log.console.level=DEBUG
        quarkus.log.min-level=DEBUG
        quarkus.log.category."io.quarkus".level=DEBUG
        """, configProfile = "someotherprofile")
class MyTest {
}
```

Here both `configOverrides` and `configProfile` should be optional and probably mutually exclusive to the currently existing `value`.

As can be seen `configOverrides` here is a plain String rather than a `Map<String, String>` as returned by `QuarkusTestProfile#getConfigOverrides()`. Since I even in my `getConfigOverrides()` like to parse the overrides from a properties String literal like in this example, I consider this to be a very nice feature. The reason I like this, is because it allows me to copy and paste from / to `application.properties` files without having to manually "translate" this into arguments for `Map.of()` or similar.

See also discussion on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Profile-specific.20properties.20in.20test.20folder

**Comment by geoand** [comment]
I am pretty sure that using strings like that would lead to some nasty surprises...

Furthermore I think this has been brought up before and as then, I am kinda negative because I don't like introducing too  many ways of doing the same thing

**Comment by knutwannheden** [comment]
A utility method to parse a String (via Properties) into a Map<String, String> would already be quite nice, as that would at least allow me to consicely implement getConfigOverrides() with a text block.

**Comment by radcortez** [comment]
We could add a way to set which profile name to use on the annotation (or even a new annotation, leaving the class implementation for advanced use cases). This will provide a way to easily load an `application.properties` specific for that test.

Are you ok with that @geoand?

**Comment by geoand** [comment]
Yeah, I guess we could add the first option

**Comment by loicmathieu** [comment]
> We could add a way to set which profile name to use on the annotation

Good idea, this is what I asked a long time ago in this issue ;) https://github.com/quarkusio/quarkus/issues/12339

**Comment by loicmathieu** [comment]
But I still think having a way to directly set application properties on the test annotation would be a great addition, via an array (of @TestContigProperty for ex.) or a string, both works for me.

**Comment by knutwannheden** [comment]
> You can do it like this:
> 
> ```java
> Properties properties = new Properties();
> properties.load(new StringReader("""
>                                  foo=bar
>                                  bar=baz
>                                  """));
> Map<String, String> map = io.smallrye.config.common.utils.ConfigSourceUtil.propertiesToMap(properties);
> ```

Yes, that is also what I am currently doing. Here a complete example (with the required exception handling):
```java
    public static class RunAsUserProfile implements QuarkusTestProfile {
        @Override
        public Map<String, String> getConfigOverrides() {
            try {
                Properties properties = new Properties();
                properties.load(new StringReader(/* language=properties */ """
                        ...
                        """));
                return ConfigSourceUtil.propertiesToMap(properties);
            } catch (IOException e) {
                throw new IllegalArgumentException(e);
            }
        }
    }
```

With a simple utility method this could of course be simplified to:

```java
    public static class RunAsUserProfile implements QuarkusTestProfile {
        @Override
        public Map<String, String> getConfigOverrides() {
            return ConfigSourceUtil.propertiesToMap("""
                    ...
                    """);
        }
    }
```

**Comment by radcortez** [comment]
Ah, so you want to avoid the try-catch? 😛

**Comment by knutwannheden** [comment]
> Ah, so you want to avoid the try-catch? 😛

Well, if having the config properties as a string literal in the annotation (as proposed) isn't an option, I think a utility method would at least make it a little bit more concise.

**Comment by knutwannheden** [comment]
Also, I prefer an option where the test-specific config properties are declared in the test folder (see also #24900), so I would rather declare the properties inline with the test instead of adding them to `src/main/resources/application.properties`.

**Comment by radcortez** [comment]
> > Ah, so you want to avoid the try-catch? 😛
> 
> Well, if having the config properties as a string literal in the annotation (as proposed) isn't an option, I think a utility method would at least make it a little bit more concise.

I would prefer to keep them out of the annotation. Do you want to send a PR for it in SR Config for the utility method? :)

> Also, I prefer an option where the test-specific config properties are declared in the test folder (see also #24900), so I would rather declare the properties inline with the test instead of adding them to `src/main/resources/application.properties`.

This should be possible with `smallrye.config.locations`. You could write your own `ConfigSource`, which looks into the test classpath and add the test folder for each Test class as an entry of `smallrye.config.locations`.

**Comment by geoand** [comment]
👍🏽
