### ISSUE TITLE
Test profiles not working with JUnit `@Nested` classes

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#24910]
### Describe the bug

Specifying the `@TestProfile` on the top level test class does not work if `@Nested` classes are used. For example, the following simple test:

```
@QuarkusTest
@TestProfile(FixedTenantTestProfile.class)
class FixedTenantResolverTest {

    @Inject
    Instance<TenantResolver> tenantResolver;

    @Nested
    class Resolve {

        @Test
        public void happyPath() {
            Optional<String> result = tenantResolver.get().resolve(null, null);

            assertThat(result).contains(FixedTenantTestProfile.TENANT_ID);
        }

    }

}
```

will fail due to the instance not being injected. Furthermore, the specified test profile in the top-level class is ignored.

The `@Nested` classes work fine if no `@TestProfile` is used.

### Expected behavior

* Test profile is respected in all `@Nested` classes if top-level class is annotated. 
* Beans are correctly injected

### Output of `uname -a` or `ver`

Linux ise-Precision-5550 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-39-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@Sgitario would you be interested in this one?
