### ISSUE TITLE
Mutiny.Session.withTransaction(...) needs duplicated context

### ISSUE THREAD

**Issue by lex-em** [quarkusio/quarkus#24917]
### Describe the bug

I am trying to run task with `@Scheduled`:
```kotlin
    @Scheduled(every = "PT5S")
    fun start2() {
        var setting = vertx.executeBlocking<Setting> {
            sf.withTransaction { sess ->  sess.find(Setting::class.java, "test")} 
                .await()
                .atMost(Duration.ofSeconds(2))
        }
        setting.onSuccess { logger.info { it } }
            .onFailure { logger.error(it) { it } }
    }
```
And get error about duplicated context needed:
`java.lang.IllegalStateException: Can't get the context safety flag: the current context is not a duplicated context`

I'm tryed also with no result
```kotlin
    @Scheduled(every = "PT5S")
    fun start2() {
        var setting = vertx.executeBlocking<Setting> {
            sf.withSession { session -> sf.withTransaction { sess ->  sess.find(Setting::class.java, "test")} }
                .await()
                .atMost(Duration.ofSeconds(2))
        }
        setting.onSuccess { logger.info { it } }
            .onFailure { logger.error(it) { it } }
    }
```

Without `vertx.executeBlocking<Setting> {}` I get error:
`The current operation requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such. You can still use Hibernate Reactive, you just need to avoid using the methods which implicitly require accessing the stateful context, such as MutinySessionFactory#withTransaction and #withSession.`

### Expected behavior

Mutiy.Session.withTransaction(...) works fine in scheduler

### Actual behavior

Error:
`java.lang.IllegalStateException: Can't get the context safety flag: the current context is not a duplicated context`

### Output of `java -version`

jdk 17.0.2

### Quarkus version or git rev

2.7.5 and 2.8.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.1

**Comment by cescoffier** [comment]
That's expected. 
@Scheduled methods do not run on duplicated contexts.

In your example, you use `vertx.executeBlocking` which also does not create a duplicated context. 

You need something like:

```java
Context ctx = VertxContext.getOrCreateDuplicatedContext(vertx));
ctx.executeBlocking(....);
```

**Comment by gsmet** [comment]
@cescoffier should we change that? Because it's very error prone and not very pretty?

**Comment by cescoffier** [comment]
We have already kind of changed that. @mkoube added a way to produce a Uni from a scheduled method, which run on a duplicated context if I remember correctly.
So instead of:

```java
 @Scheduled(every = "PT5S")
    fun start2() {
        var setting = vertx.executeBlocking<Setting> {
            sf.withTransaction { sess ->  sess.find(Setting::class.java, "test")} 
                .await()
                .atMost(Duration.ofSeconds(2))
        }
        setting.onSuccess { logger.info { it } }
            .onFailure { logger.error(it) { it } }
    }
```

You will do:

```
@Scheduled(...)
Uni<Void> start() {
   return  sf.withTransaction( {sess ->  sess.find(Setting::class.java, "test") }); 
}
```

**Comment by lex-em** [comment]
@cescoffier but `sf.withTransaction(...)` didn't return Uni<Void>
I a mtruing with `.replaceWithVoid()`, but code
```kotlin
    @Scheduled(every = "PT5S")
    fun start(): Uni<Void> {
        return sf.withTransaction { sess -> sess.find(Setting::class.java, "test") }
            .replaceWithVoid()
    }
```
```
results in an error
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: Scheduled business method must return void
```

**Comment by cescoffier** [comment]
@mkouba did you know in which version we added that feature?

**Comment by lex-em** [comment]
I am trying in quarkus 2.8.0, is there any specific dependency for this feature?

**Comment by cescoffier** [comment]
no, but it may need 2.9 (main branch)

**Comment by lex-em** [comment]
ok, i'll wait

**Comment by mkouba** [comment]
> @mkouba did you know in which version we added that feature?

Yes, https://github.com/quarkusio/quarkus/pull/24658 targets 2.9.0...

**Comment by cescoffier** [comment]
#25257 has been fixed.
