### ISSUE TITLE
Mockito extension not working with `@QuarkusTest`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#24911]
### Describe the bug

Having a test with:

```
@QuarkusTest
@ExtendWith(MockitoExtension.class)
class Test {

    @Captor
    ArgumentCaptor<Whatever> captor;
}
```

will not correctly utilize the `MockitoExtension` and Mockito annotated fields will not be initialized.

### Expected behavior

* `org.mockito` annotations are correctly initialized

### Actual behavior

Seems that Mockito extension is initalizing the fields in the different test instance. Simple debugging I did showed that mockito correctly initialized fields in my test instance `{GrpcClientsTest@10823}`, while the actual instance being used in the test is `{GrpcClientsTest@10895}`.

### Output of `uname -a` or `ver`

Linux ise-Precision-5550 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

pache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-39-generic", arch: "amd64", family: "unix"

**Comment by famod** [comment]
There is a special `quarkus-junit5-mockito` dependency you'll have to use, which is providing special annotations like `@InjectMock`. See e.g. https://quarkus.io/guides/getting-started-testing#further-simplification-with-injectmock

I don't thing `@Captor` will work with this, though.

**Comment by geoand** [comment]
This is an inherent limitation of how we handle tests - we essentially need to create a proxy of the test class. 
This won't be changed any time soon.

FWIW, you can use `@InjectMock` for dealing with mocks

**Comment by ivansenic** [comment]
Would `@InjectMocks` also work for the mocks that are actually not beans? I mean let's say I want to mock a class that is not a bean and not in the CDI context, I doubt `@InjectMocks` would work. 

Also this means any Mockito extension functionality, as `@Captor` can not be used. Which kind of makes me think about the other Junit extensions out there. Are you actually saying we have limitations on how we handle tests and yes you can not use any of the extensions out there? Is this really the good approach?

**Comment by geoand** [comment]
It only works for beans

**Comment by geoand** [comment]
There are various limitations, yes.

I never said it was a good approach, it was however the only one that allowed us to support the feature set we need.

If JUnit supports loading test classes from a custon ClassLoader in the future (there is an open issue), we could ditch this approach.
