### ISSUE TITLE
Add org.eclipse.jgit.ssh.apache to the quarkus-jgit plugin

### ISSUE THREAD

**Issue by fage88** [quarkusio/quarkus#24927]
### Description

Since September 2021 github has stopped supporting RSA-1 keys (https://github.blog/2021-09-01-improving-git-protocol-security-github/)

This means users of the quarkus-jgit plugin need to use org.eclipse.jgit.ssh.apache if they want to authenticate with deployment keys as jsch does not support openssl keys.

I would like to see this dependency added to the quarkus-jgit plugin so that users don't need to add it themselves and then try to figure out all of the reflection/native-image issues on their own.

**Comment by geoand** [comment]
The `jgit` extension's source code has been moved to https://github.com/quarkiverse/quarkus-jgit, so please open the issue there.

Thanks

**Comment by fage88** [comment]
Disappointing, there is no place to enter bugs/issues over there

**Comment by gsmet** [comment]
@fage88 https://github.com/quarkiverse/quarkus-jgit/issues
