### ISSUE TITLE
NullPointerException with Quartz and Quarkus 2.8.0.Final when a job identity is changed

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#24931]
### Describe the bug

After updating to Quarkus 2.8.0.Final, one of our scheduled tasks failed with an exception I've not seen before and that seems to be coming from Quarkus:

```
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException: Cannot read field "invoker" because "this.trigger" is null]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException: Cannot read field "invoker" because "this.trigger" is null
	at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:553)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

Application is deployed as an uber-jar.

### Expected behavior

No NullPointerException is thrown when scheduling jobs

### Output of `uname -a` or `ver`

RHEL 8 Linux

### Output of `java -version`

17.0.2

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by geoand** [comment]
Do you have a sample that exhibits this behavior?

**Comment by josephearl** [comment]
I do not at the moment (but will see if I can get one) - it only seems to have affected one of our scheduled jobs that runs nightly, we have some others that run every hour and have not seen the same issue with those.

**Comment by josephearl** [comment]
After investigating further I've found this was caused by someone re-naming the identity of the job, and the error was being thrown for the old job identity. The job was running fine under the new identity.

I think prior to 2.8.0.Final this must have been failing silently.

I suppose it might be nice to have a clearer error message in this scenario (there is no job which matches the identity).

**Comment by mkouba** [comment]
CC @machi1990

**Comment by geoand** [comment]
> I suppose it might be nice to have a clearer error message in this scenario (there is no job which matches the identity).

Definitely +1

**Comment by machi1990** [comment]
> After investigating further I've found this was caused by someone re-naming the identity of the job, and the error was being thrown for the old job identity. The job was running fine under the new identity.

How was the identity renamed? Was done as part of your application dev team doing the rename of a Quarkus upgrade - we renamed the job identity from 2.1 and at some point in 2.7.x provided an automatic migration. 
If this was part of your application dev renaming the job, then what's we advise is the team also taking care of performing the migration. 

> I think prior to 2.8.0.Final this must have been failing silently.
> 
> I suppose it might be nice to have a clearer error message in this scenario (there is no job which matches the identity).

Renaming of job identities occurs and throwing a NPE is not a good dev experience. I think what happened is a manual renaming of the identity and removing the old entry should fix the issue. I also think that we should ignore old entries in https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L559  i.e `when trigger == null`, what do you think? @mkouba

**Comment by josephearl** [comment]
> How was the identity renamed? Was done as part of your application dev team doing the rename of a Quarkus upgrade

The identity in the scheduled annotation was changed, i.e. it was `@Scheduled(every = "10s", identity = "foobar")` and it was changed to `@Scheduled(every = "10s", identity = "foobaz")`.

The change was unrelated to any Quarkus upgrade, it just happened around the same time as I updated the Quarkus version.

**Comment by machi1990** [comment]
Thanks @josephearl, for those kind of changes it is up to the app developer to migrate the quartz tables accordingly. However, the quartz extension should'nt throw a NPE. Do you mind re-opening the issue to track the improvement needed on the extension side?

**Comment by josephearl** [comment]
@machi1990 np, reopened.
