### ISSUE TITLE
AnnotationsTransformer not applied to METHOD_PARAMETER kind

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#2493]
Hello,

I noticed that the `AnnotationsTransformer` is not applied to `Kind.METHOD_PARAMETER` when configured by `AnnotationsTransformer::appliesTo(Kind)`.

I have the following method:

```java
public void handleInteger(@Observed Integer i) {
  forward(ref, i);
}
```

And a `@BuildStep` like this:

```java
@BuildStep
void doSomeTransformation(BuildProducer<AnnotationsTransformerBuildItem> transformers) {
  transformers.produce(new AnnotationsTransformerBuildItem(new MyTransformer()));
}
```

And `AnnotationsTransformer` implementation given below. It does nothing but prints `TransformationContext` target to `stdout`.

```java
private static class MyTransformer implements AnnotationsTransformer {

  @Override
  public boolean appliesTo(Kind kind) {
    return kind == Kind.METHOD_PARAMETER;
  }

  @Override
  public void transform(TransformationContext tc) {
    System.out.println(tc.getTarget());
  }
}
```

This should print a bunch of contexts where `@Valid` or `@Observes` annotated parameters are present. The problem lies in the fact that nothing is printed. But when I change `applies(Kind)` to apply to `METHOD` instead of `METHOD_PARAMETER` I see interesting methods printed, with many others included.

```java
  @Override
  public boolean appliesTo(final Kind kind) {
    return kind == Kind.METHOD;
  }
```

When I grep:

```
$ mvn clean install | grep handleInteger
void handleInteger(java.lang.Integer i)
```

**Comment by mkouba** [comment]
Hi @sarxos, so `Kind.METHOD_PARAMETER` is not supported and as explained in `AnnotationTransformer`s javadoc: _"The container should use AnnotationStore to obtain annotations of any org.jboss.jandex.ClassInfo, org.jboss.jandex.FieldInfo and org.jboss.jandex.MethodInfo."_ In other words, if you want to modify the annotations of a method param you'll need to transform a method info annotations.

I agree that it's not very user-friendly but it's a limitation of Jandex API - `MethodInfo` does not expose `MethodParameterInfo` directly.

Note that `MethodInfo.annotations()` returns annotations declared on the method and method parameters and `target().kind()` could be used to determine the location.

**Comment by sarxos** [comment]
Hi @mkouba, thank you for clarifying this! I will take your suggestion into account and implement some w/a using `target().kind()` :)
