### ISSUE TITLE
Quick starts example 'Using HTTP with Reactive Messaging' is not working; the import javax.ws cannot be resolved.

### ISSUE THREAD

**Issue by OpsDevEd** [quarkusio/quarkus#24948]
### Describe the bug

Following guide [Using HTTP With Reactive Messaging](https://quarkus.io/guides/reactive-messaging-http) using the creating the Maven Project method, generates error the import javax.ws cannot be resolved.

### Expected behavior

Following a guide as a beginner, i expect the outcome is working as described.

### Actual behavior

Code does not compile, the import javax.ws cannot be resolved.

### How to Reproduce?

1. Follow the guide [Using HTTP With Reactive Messaging](https://quarkus.io/guides/reactive-messaging-http) 
2. Use the creating the Maven Project method.
3. Add the CostCollector class code

### Additional information

Extension io.quarkus:quarkus-resteasy-reactive is missing from the Create a new project with the following command example.

**Comment by geoand** [comment]
Seems like RESTEasy Reactive is not added to the `pom.xml`. @ia3andy @gsmet is there a reason for that?

**Comment by ia3andy** [comment]
I guess the command should have the `resteasy-reactive` extension like this:
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.8.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=reactive-messaging-http-quickstart \
    -Dextensions="reactive-messaging-http,resteasy-reactive" \
    -DnoCode
```

`-DnoExamples` does not exist anymore it was replaced by `-DnoCode`, we should check all the guides.

**Comment by ia3andy** [comment]
After investigation we have 3 guides still using `-DnoExamples`:
- https://github.com/quarkiverse/quarkus-reactive-messaging-http/blame/main/docs/modules/ROOT/pages/reactive-messaging-http.adoc#L46
- https://github.com/quarkiverse/quarkus-reactive-messaging-http/blame/main/docs/modules/ROOT/pages/reactive-messaging-websocket.adoc#L50
- https://github.com/quarkusio/quarkus/blame/main/docs/src/main/asciidoc/building-my-first-extension.adoc#L852

**Comment by ia3andy** [comment]
I create a PR for the first-extension guide: https://github.com/quarkusio/quarkus/pull/24957

**Comment by ia3andy** [comment]
Regarding the missing `resteasy-reactive` extension shouldn't this be a conditional dependency?

**Comment by geoand** [comment]
A conditional dependency of what?

**Comment by ia3andy** [comment]
Ok I thought it was needed by reactive-messaging, but it's just the guide example which needs it. So it's just a matter of adding it to the create command, I am updating the issue: https://github.com/quarkiverse/quarkus-reactive-messaging-http/issues/59

**Comment by cescoffier** [comment]
Closing as the _downstream_ issue is fixed.
