### ISSUE TITLE
Kafka producer gets closed after first request in the native mode

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#2495]
Due to `declaredMethods` of `BeforeDestroyed` not being present at runtime, destroying request scope causes a call to https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaMessagingProvider.java#L28

Also see: https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/Qualifiers.java#L47

**Comment by gsmet** [comment]
@michalszynkiewicz can you confirm this one was fixed by https://github.com/quarkusio/quarkus/pull/2524 ?

**Comment by michalszynkiewicz** [comment]
Yes, sorry for not confirming earlier.
