### ISSUE TITLE
@PostConstruct and @PreDestroy not working

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#24967]
### Describe the bug

I'm not sure if this is a bug or intentional, but the `@PostConstruct` and `@PreDestroy` annotated methods are never working.

```
@ApplicationScoped
public class Test {

    @PostConstruct
    public void test() {
        System.out.println("construct");
    }

    @PreDestroy
    public void test2() {
        System.out.println("destroy");
    }
}

```

If this is for some reason intentional, how to get it working?

### How to Reproduce?

https://github.com/mklueh/quarkus-reproducer-post-construct-issue

**Comment by geoand** [comment]
This issue is that your `Test` is not being used anywhere and thus Quarkus is not considering it a bean.
See https://quarkus.io/blog/unused-beans/ for more details.

The easiest way to prevent the bean from being removed is to annotate it with `@Unremovable`.

**Comment by mklueh** [comment]
@geoand thank you. 

I've tried it, but even with `@Unremovable` and a StartupEvent method nothing happens.

```
@Unremovable
@ApplicationScoped
public class Test {

    public void start(@Observes StartupEvent startup){
        System.out.println("startup");
    }

    @PostConstruct
    public void test() {
        System.out.println("construct");
    }

    @PreDestroy
    public void test2() {
        System.out.println("destroy");
    }
}

```

Does Quarkus it now consider unremovable, but still not as a bean?

**Comment by geoand** [comment]
> but even with @Unremovable and a StartupEvent method nothing happens.

You mean that nothing is printed?

**Comment by mklueh** [comment]
> > but even with @unremovable and a StartupEvent method nothing happens.
> 
> You mean that nothing is printed?

Exactly

**Comment by geoand** [comment]
I just tried it and it worked fine

**Comment by mklueh** [comment]
@geoand yes, sry seems to work.

**Comment by geoand** [comment]
NP
