### ISSUE TITLE
Ability to use InjectSpy on MicroProfile RestClient

### ISSUE THREAD

**Issue by skylar-smith** [quarkusio/quarkus#24968]
### Describe the bug

When using `@InjectSpy` for a MicroPorfile Rest Client the test instance fails to be created.

Example Injection
```
    @InjectSpy
    @RestClient
    ExampleApi exampleApi;
```

### Expected behavior

The test would run and either succeed or fail due to Mockito.verify

### Actual behavior

The test fails execution with the following error.

```
-------------------------------------------------------------------------------
Test set: org.acme.GreetingResourceTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.477 s <<< FAILURE! - in org.acme.GreetingResourceTest
org.acme.GreetingResourceTest.testHelloEndpoint  Time elapsed: 0.004 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
Caused by: org.mockito.exceptions.base.MockitoException: 

Cannot mock/spy class com.sun.proxy.$Proxy72
Mockito cannot mock/spy because :
 - final class

 ```

### How to Reproduce?

Clone https://github.com/skylar-smith/spy-rest-client

run `./mvnw verify`

### Output of `uname -a` or `ver`

Darwin LTC02XJ2T1JG5J 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Java version: 11.0.13, vendor: Eclipse Adoptium
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.1", arch: "x86_64", family: "mac"

### Additional information

**Comment by geoand** [comment]
Have you tried with `quarkus-rest-client-reactive`?

**Comment by skylar-smith** [comment]
Modifying the project to use `quarkus-rest-client-reactive` appears to have fixed the issue. `Mockito.verify` works for `@InjectSpy` and `@InjectMock`. @geoand  thank you very much.

**Comment by geoand** [comment]
Glad to hear it!
