### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by SetoKaiba** [quarkusio/quarkus#24978]
### Describe the bug

The header is missing sometimes. It's unreliable.
You can have a test here. Use ctrl + F5 to force refresh every time.
https://live.kaiba.net:8443/WebGL2/Build/WebGL2.framework.js.br
It seems that it occurs only with real online server and https.
I can't reproduce it in the local as well.
And I'm sure the System.out is printed every time.

And here's the reproduce project. You should test it with your own certificates.
https://github.com/SetoKaiba/code-with-quarkus

```Java
package org.acme;


import io.quarkus.vertx.http.runtime.filters.Filters;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class FilterRegistrator {

    void setupFilter(@Observes Filters filters) {
        filters.register((rc) -> {
            rc.next();

            if (rc.normalizedPath().contains(".gz")) {
                System.out.println(rc.normalizedPath() + ":gz");
                rc.response().headers().add("content-encoding", "gzip");
            }

            if (rc.normalizedPath().contains(".br")) {
                System.out.println(rc.normalizedPath() + ":br");
                rc.response().headers().add("content-encoding", "br");
            }

            if (rc.normalizedPath().contains(".wasm")) {
                System.out.println(rc.normalizedPath() + ":wasm");
                rc.response().headers().add("content-type", "application/wasm");
            }

        }, 0);
    }
}

```

**Comment by maxandersen** [comment]
so just so I get it right - you see the filter being applied consistently when run locally but when you run it somewhere online the filter is no longer always called (meaning system.out is also not called) ?

**Comment by SetoKaiba** [comment]
> so just so I get it right - you see the filter being applied consistently when run locally but when you run it somewhere online the filter is no longer always called (meaning system.out is also not called) ?

No. It's always called. But the header does not always exist.

**Comment by cescoffier** [comment]
@geoand any idea? I don't see how a header can be missing "sometimes", as adding headers is synchronous.

**Comment by SetoKaiba** [comment]
Yes. It's strange. Previously, I thought it might be https related. Because br encoding is only working with https in browser.
But now I use curl instead. I found that it's still missing sometimes with http.

```
C:\Users\61304>curl --head http://live.kaiba.net:8080/WebGL2/Build/WebGL2.framework.js.br
HTTP/1.1 200 OK
content-encoding: br
accept-ranges: bytes
content-length: 74411
cache-control: public, immutable, max-age=86400
last-modified: Sun, 1 May 2022 02:04:22 GMT
date: Mon, 9 May 2022 03:12:37 GMT


C:\Users\61304>curl --head http://live.kaiba.net:8080/WebGL2/Build/WebGL2.framework.js.br
HTTP/1.1 200 OK
accept-ranges: bytes
content-length: 74411
cache-control: public, immutable, max-age=86400
last-modified: Sun, 1 May 2022 02:04:22 GMT
date: Mon, 9 May 2022 03:12:37 GMT


C:\Users\61304>curl --head http://live.kaiba.net:8080/WebGL2/Build/WebGL2.framework.js.br
HTTP/1.1 200 OK
content-encoding: br
accept-ranges: bytes
content-length: 74411
cache-control: public, immutable, max-age=86400
last-modified: Sun, 1 May 2022 02:04:22 GMT
date: Mon, 9 May 2022 03:12:38 GMT
```

**Comment by SetoKaiba** [comment]
But I can't reproduce it with localhost. It's only reproducible with remote server. Is there any mechanism about the header order related? Maybe when the header is overriden, the header lost?

**Comment by SetoKaiba** [comment]
And also, it's not something related to the host firewall settings or other settings. Because I can use nginx to serve this with header always.

**Comment by geoand** [comment]
Is there any particular reason you are calling `rc.next()` as the first operation? I would expect that to be the last operation...

**Comment by SetoKaiba** [comment]
@geoand https://github.com/quarkusio/quarkus/discussions/23162#discussioncomment-2071471
I take his code.

**Comment by SetoKaiba** [comment]
@geoand It's working now with rc.next() last operation. I think this issue should be considered closed. Thank you.

**Comment by geoand** [comment]
Great yo hear
