### ISSUE TITLE
RESTEasy Reactive is not included by default when using Maven archetype in 2.8.0

### ISSUE THREAD

**Issue by mraible** [quarkusio/quarkus#24980]
### Describe the bug

[Quarkus 2.8.0.Final](https://quarkus.io/blog/quarkus-2-8-0-final-released/) says that the default REST layer has been changed to RESTEasy Reactive. This doesn't appear to apply to the Maven archetype. 

With 2.7.5, if you create a new project with the following command, `quarkus-resteasy` is included by default.

```
mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create \
    -DprojectGroupId=com.okta.rest \
    -DprojectArtifactId=quarkus \
    -DclassName="com.okta.rest.quarkus.HelloResource" \
    -Dpath="/hello" \
    -Dextensions="smallrye-jwt"
```

Test to show it's included:

```
$ cat quarkus/pom.xml | grep resteasy
      <artifactId>quarkus-resteasy</artifactId>
```

With 2.8.0, there is no RESTEasy dependency included.

```
$ cat quarkus/pom.xml | grep resteasy
<no results>
```

### Expected behavior

I expect `<artifactId>quarkus-resteasy-reactive</artifactId>` to be included by default.

### Actual behavior

No RESTEasy dependencies are included.

### How to Reproduce?

See steps above.

### Output of `uname -a` or `ver`

Darwin mando.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 11.0.14 2022-01-18 LTS OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS) OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by geoand** [comment]
@gsmet I thought we made RESTEasy Reactive the default. Is that not the case?

**Comment by gsmet** [comment]
It is the default, but as I mentioned it, we don't force a REST layer onto the users anymore (except if they don't add any extensions, in which case RESTEasy Reactive is added).
The main reason is that Quarkus is used nowadays for a ton of things and a REST server is just one of these many things.

**Comment by geoand** [comment]
Gotcha, thanks.

Maybe it's worth a note in the migration guide?

**Comment by gsmet** [comment]
I thought I added something :/. Will do.

**Comment by geoand** [comment]
Thanks!

**Comment by gsmet** [comment]
Done!
