### ISSUE TITLE
add sa-token extension support

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#24983]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

[https://github.com/naah69/quarkus-sa-token](https://github.com/naah69/quarkus-sa-token)

**Comment by geoand** [comment]
Thanks for your interest!

Might I ask what this extension does?

**Comment by sberyozkin** [comment]
Looks like something similar to `quarkus-oidc`

**Comment by sberyozkin** [comment]
@naah69 Thanks. I'm sorry, I see no point in adding yet another extension dealing with OIDC/OAuth2 to the Quarkus repository. We already have 3 extensions dealing with the tokens in general, `Elytron OAuth2`, `smallrye-jwt` and `quarkus-oidc`, with a lot of effort going into `quarkus-oidc`/SSO in particular.In addition, we have `keytcloak-authorization` which deals with Keycloak making centralized authorization decisions.
 
I recommend to create a Quarkiverse extension if you'd like to push it further.

Thanks

**Comment by sberyozkin** [comment]
My preference would be to keep enhancing `quarkus-oidc` if you think it lacks something as opposed to adding another extension which overlaps in functionality

**Comment by geoand** [comment]
Quarkiverse is definitely the place to explore such things

**Comment by naah69** [comment]
> Quarkiverse is definitely the place to explore such things

yes, I think so,Quarkiverse  is a great idea

**Comment by geoand** [comment]
cc @gastaldi

**Comment by sberyozkin** [comment]
My only concern with it is that what will our message around OIDC becomes. Are we going to have several extensions doing OpenId Connect authentication in their own ways ?
