### ISSUE TITLE
Instructions to build/run integration tests in Gradle against native image incorrect

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#24987]
### Describe the bug

The [Build a container friendly executable](https://quarkus.io/guides/gradle-tooling#build-a-container-friendly-executable) guide in the gradle tooling:

```
./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
```

Doesn't seem to work unless you also add the `-Dquarkus.container-image.build=true` flag.

For example, if I run

```
./gradlew clean build quarkusIntTest -Dquarkus.package.type=native -Dquarkus.native.container-build=true
```

it packages the native executable but then `quarkusIntTest` tries to execute the native image (not inside a container). 

Instead, if I run

```
./gradlew clean build quarkusIntTest -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
```

Then the container image is built and the integration tests are run against the built image.

See the reproducer:
[gradle-test.zip](https://github.com/quarkusio/quarkus/files/8507621/gradle-test.zip)

I'm not sure if this is just a documentation issue (if it was I would have just fixed it) or if something in the Gradle plugin isn't working correctly. 

There's also a thread on Zulip where this was discovered: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Gradle.20quarkusIntTest.3B.20configure.20packaging

**Comment by glefloch** [comment]
Thanks for reporting this @edeandrea, I think this is the expected behavior. 
````

./gradlew clean build quarkusIntTest -Dquarkus.package.type=native -Dquarkus.native.container-build=true
````
builds a native executable from inside a container, this no `native-image` installation is required. 
The `-Dquarkus.container-image.build=true` property comes from the `container-image` extension and makes sure an image is built as part of the `quarkusBuild` task. This is a not a core property, so I'm not sure this should be part of this documentation. WDYT ?

**Comment by edeandrea** [comment]
Yeah I wasn't sure what was expected or not. We definitely need something in the `quarkusIntTest` section though describing how someone would execute the integration tests against a container image containing a native image.

**Comment by edeandrea** [comment]
IDK I don't think it can hurt to mention it. I think where it really should be mentioned is on https://quarkus.io/guides/gradle-tooling#running-integration-tests.

Maybe https://quarkus.io/guides/gradle-tooling#running-integration-tests can just say something like

```
If you want to run integration tests against a built container image, in addition to running the `quarkusIntTest` task you also need to tell Gradle to [build a container image](https://quarkus.io/guides/container-image#building).
```
