### ISSUE TITLE
add dapr extension support

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#24982]
### Description

add dapr extension support to quarkus.

[https://github.com/naah69/quarkus-dapr](https://github.com/naah69/quarkus-dapr)

### Additional context

dapr extension 
dapr rest-client extension

**Comment by skyao** [comment]
Hi, I'm Sky from Dapr community, I'm very interesting in this extension and would like to provide any support if needed.

I have talked with @naah69 and we have completed the simplest verification to integrate dapr and quarkus to build a native java application. 

This is an important start.

I will invite openfunction community to work with us to complete a user story: event driven java application based on quarkus and dapr, running on serverless platform as function.

**Comment by skyao** [comment]
https://blog.dapr.io/posts/2021/02/09/running-dapr-in-production-at-roadwork/

This is a real user case of Dapr adoption, we can reference it.

**Comment by geoand** [comment]
Hey folks,

Thanks for this!

I think this extension would be great for the [Quarkiverse](https://quarkus.io/blog/quarkiverse/)

**Comment by zhfeng** [comment]
Thanks for working on the dapr support. @naah69 @skyao would you like to leading development and mantain this extesion ? I'll help you as much as possible.

**Comment by skyao** [comment]
> Thanks for working on the dapr support. @naah69 @skyao would you like to leading development and mantain this extesion ? I'll help you as much as possible.

OK. Thanks for your help.

I'm familiar with Dapr, while I'm not familiar with the extension mechanism of quarkus. Now @naah69 is working on this extension and he is leading the development.

**Comment by geoand** [comment]
@gastaldi is the subject matter expert for anything Quarkiverse related.
So feel free to ask anything you need related to releasing to Quarkiverse

**Comment by gastaldi** [comment]
@skyao that's awesome! I can create a `quarkus-dapr` repository in our `quarkiverse` repository if you like. Here are some docs about it: https://github.com/quarkiverse/quarkiverse/wiki

**Comment by naah69** [comment]
> 



> I created [quarkiverse/quarkiverse-devops#41](https://github.com/quarkiverse/quarkiverse-devops/pull/41) which invites @naah69 to the [Quarkiverse](https://github.com/quarkiverse) organization and creates a `quarkus-dapr` repository there (and automatically closes this issue).
> 
> To make sure this extension is visible in code.quarkus.io and our tooling in general, make sure to add a `quarkiverse-dapr.yaml` file in https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions. See https://github.com/quarkusio/quarkus-extension-catalog#extensions for an example on how it should look like. Since it seems to be a multimodule project (with more than 1 extension), create a YAML file for each extension.
> 
> Let me know if you need any help. I'm glad to help 😉

I'm glad to join Quarkiverse organization.

If I need help, I'll ask you for it.

Thanks for your help.

**Comment by skyao** [comment]
Let's go ahead to complete the first version of this extension, and then run up the demo with open-function.
