### ISSUE TITLE
opentelemetry tracks only half of spans in 2.8.0/2.8.1

### ISSUE THREAD

**Issue by cdmikechen** [quarkusio/quarkus#24993]
### Describe the bug

When using hibernate-reactive to trace vertx sql, I found quarkus only tracks half of spans in vertx.I'm using quarkus 2.8.0, and I have this problem with any call I make within the quarkus project.
I tried to change logic method calls order, and found that span could only be traced separated by rows.

I have mentioned the same problem in issue https://github.com/quarkusio/quarkus/issues/23144#issuecomment-1101255841  
The span viewed in Jaeger is only the first and third lines.
```java
arepo.update("isDelete = true, updateTime = ?1 where id = ?2", now, table.id)
    .call(r -> brepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
    .call(r -> crepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
    .call(r -> drepo.update("isDelete = true, updateTime = ?1 where tableId = ?2", now, table.id))
```

### Expected behavior

Quarkus should track all span with vertx

### Actual behavior

I have written an example in `How to Reproduce?`.
Normally, I should use hibernate batch to output insert statements six times. In fact, I only see three inert statements in Jaeger UI.

![image](https://user-images.githubusercontent.com/12069428/163897860-aad0a3f2-1e25-44a8-bc54-fc229c947a38.png)

### How to Reproduce?

batch save:
```java
    @POST
    @Path("/batch")
    @ReactiveTransactional
    public Uni<Void> batch() {
        List<Fruit> fruits = new ArrayList<>();
        for (long i = 0, row = 6; i < row; i++) {
            Fruit fruit = new Fruit();
            fruit.id = i + 1;
            fruit.name = "test";
            fruits.add(fruit);
        }

        return Fruit.persist(fruits);
    }
```
Fruit entity:
```java
@Entity
public class Fruit extends PanacheEntityBase {
    @Id
    @Column(name = "id")
    public Long id;

    @Column(length = 40, unique = true)
    public String name;
}
```

### Output of `uname -a` or `ver`

user

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)

### Quarkus version or git rev

2.8.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

application.yaml
```yaml
quarkus:
  opentelemetry:
    enabled: true
      tracer:
        exporter:
          otlp:
            endpoint: http://XXXX:55680
```

**Comment by cdmikechen** [comment]
@radcortez 
Hi~ I've noticed that quarkus has been upgraded to version 2.8.2 . Do we have any plans to fix this problem in version 2.8?

**Comment by radcortez** [comment]
Sorry, I've been traveling and could not look into this yet. I'll have a look next week.

The version fix may depend on how small/big the fix is. If it is something small that can be backported we can do it for Quarkus 2.8.x. If not, it will need to go to 2.9.x.

**Comment by geoand** [comment]
Closing as we never got a reproducer
