### ISSUE TITLE
Reactive REST client duplicates paths, described by subresources

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#25028]
### Describe the bug

When reactive REST client is used to access sub-resources of some HTTP resource, it duplicates paths which describe these sub-resources. For example, if there is such method in rest client:
```
@Path("/resource")
public interface Client {
 @Path("/sub")
    SubClient getSubResource()
 }
}
```
then call  `client.getSubResource().getSomething()` will lead to HTTP request to `resource/sub/sub/something`.

### Expected behavior

Sub-resources should not lead to duplicated paths.

### Actual behavior

Paths are duplicated

### How to Reproduce?

1. `git clone -b reproducer/duplicate-paths git@github.com:fedinskiy/quarkus-test-suite.git`
2. `cd  http/rest-client-reactive`
3. `mvn clean verify -Dit.test=ReactiveRestClientIT#deepLevel` ( or `ReactiveRestClientIT#subResource`)
4. There is a log which shows, that requests are send to URLs like `http://localhost:1101/books/author/profession/profession/wage/wage/currency/currency/name`

### Output of `uname -a` or `ver`

5.16.13-200.fc35.x86_64

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
@michalszynkiewicz can you take a look at this please?
As @sberyozkin mentions, this is likely causing problems with the Keycloak admin client

**Comment by michalszynkiewicz** [comment]
I'll try to fix this today

**Comment by michalszynkiewicz** [comment]
it turned out to be slightly more complex than anticipated but I should be able to fix it tomorrow :)

**Comment by nxtxdouwyjun** [comment]
> 

Hi, any news? I am troubled by this problem. When can it be fixed?

**Comment by geoand** [comment]
Michal is working on it. It will be fixed soon (in 2.8.3 at the earliest). That's as specific as we can be.

**Comment by nxtxdouwyjun** [comment]
> Michal is working on it. It will be fixed soon (in 2.8.3 at the earliest). That's as specific as we can be.

 2.8.3, how long will it take?  I'm developing a project. If it takes too long, I can't wait for 2.8.3. I may need to solve the problem in another way.

**Comment by geoand** [comment]
There is no exact date.
Could be next week or the week after

**Comment by nxtxdouwyjun** [comment]
Great! I see it has been fixed! It will be added to next version 2.8.2, right? And, when 2.8.2 will be released?@geoand

**Comment by geoand** [comment]
It's unlikely to make it into 2.8.2 (which may be in the process of being released)

**Comment by gsmet** [comment]
I will release 2.8.2 tomorrow. This patch will be in if it's merged by this evening.

**Comment by nxtxdouwyjun** [comment]
I see 2.8.2 released, great! I love quarkus! Great team! Great quarkus!

**Comment by geoand** [comment]
🥰
