### ISSUE TITLE
Vertx ClusterManager failed when generate a native image

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#2502]
Because of "io.quarkus.vertx.runtime.ClusterConfiguration" without cluster manager class "ConfigItem".
It work well and can load ClusterManager in normal mode (quarkus:dev),
but if transform to native image raise error: "No ClusterManagerFactory instances found on classpath".

Does it possible add a cluster manager configure property for built time (UnremovableBeanBuildItem) or runtime load class new instance?

**Comment by emmanuelbernard** [comment]
CC @cescoffier @vietj do we want to support that or not?

**Comment by gsmet** [comment]
@leotu any chance you could create a simple reproducer?
