### ISSUE TITLE
REST Reactive Client when retried, Authorization header is multiplied by OidcClientRequestReactiveFilter 

### ISSUE THREAD

**Issue by ertanden** [quarkusio/quarkus#25029]
### Describe the bug

When we have a REST Reactive Client with OidcClientRequestReactiveFilter, and we retry the requests through Mutiny, the Authorization header gets multiplied with each new retry.

This results in AWS API Gateway to immediately reject the requests with Bad Request.

Is there a configuration or something we can do to change this behaviour or is this something that needs to be fixed ?

### Expected behavior

Only a single Authorization header in the retried requests.

### Actual behavior

Authorization headers keep increasing with each retry request.

### How to Reproduce?

Given the rest client;

```
@RegisterRestClient(configKey = "my-api")
@RegisterProvider(OidcClientRequestReactiveFilter.class)
@Path("/api/v1")
public interface MyApi {
    @POST
    @Path("/something")
    Uni<SomethingResponse> postSomething(Something body);
}
```

When;

```
myApi.postSomething(body).onFailure().retry().indefinitely();
```

Then each retry keeps appending a new Authorization header to the request. 

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.8.1

**Comment by geoand** [comment]
Thanks for reporting.

Can you please attach a sample project that exhibits the problematic behavior?

**Comment by ertanden** [comment]
I looked into the implementation of `OidcClientRequestReactiveFilter` and saw that the `add` function is used there, which keeps adding the Authorization header every time the filter is called. How about that is changed to `putSingle` so that we make sure in a request there's always a single Authorization header?

https://github.com/quarkusio/quarkus/blob/731abc35ccad9851c8a2e8a4c3d4e6adfed5e602/extensions/oidc-client-reactive-filter/runtime/src/main/java/io/quarkus/oidc/client/reactive/filter/OidcClientRequestReactiveFilter.java#L44

Would that have any side effects?

**Comment by geoand** [comment]
Seems reasonable to me, but I am not the author of this code, so I can't comment with any authority

**Comment by sberyozkin** [comment]
@ertanden @geoand Thanks, but a new request should not see the old map of headers, right ?

I will replace `add` with `putSingle` in a few minutes anyway, in both cases the intention is to have a single `Authorization`

**Comment by ertanden** [comment]
@sberyozkin thanks for the PR. I'm curious though about your comment regarding old map of headers...

It is a `retried` request triggered by `Mutiny`, so maybe there's another root cause that the headers are still present in the retried request? Do you think it's worth to investigate?
