### ISSUE TITLE
Integration Tests for Quarkus Native Image for AWS Lambda do not work with multiple lambdas

### ISSUE THREAD

**Issue by czyba** [quarkusio/quarkus#25037]
### Describe the bug

I was running integration tests with quarkus in order to test that the native image actually works as intended, since I had issues before with forgetting to add some `@RegisterForReflection`. Our project contains multiple Lambda handlers which we test by having a `QuarkusTestProfile` overriding `quarkus.lambda.handler` for the respective lambda we want to test in a specific test.

When having multiple lambdas in the same project, as is generated by the mvn archetype described in the [documentation](https://quarkus.io/guides/amazon-lambda) it seems to be not trivially possible to run integration tests against multiple lambdas at the same time. Thus we resorted to the `QuarkusTestProfile`.

During the execution of the integration tests it seems that the test framework tries to start the native image multiple times. It ignores any port indication I might provide however:

```
Executing "target/test-1.0-SNAPSHOT-runner -Dquarkus.log.file.path=target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus-internal.aws-lambda.test-api=localhost:8081/_lambda_ -Dquarkus.lambda.mock-event-server.test-port=8082 -Dquarkus.configuration.build-time-mismatch-at-runtime=fail -Dquarkus.lambda.handler=first -Dquarkus.lambda.mock-event-server.dev-port=8082 -Dquarkus.http.port=8082 -Dquarkus.http.test-port=8082"
```

As you can see I tried overriding all ports, including `quarkus-internal.aws-lambda.test-api`. The `quarkus-internal.aws-lambda.test-api` is ignored however and set hard to port 8081.

Regular tests run fine.

### Expected behavior

Integration tests should run without issue, either be not ignoring the ports I set or by stopping the running image (or port listen) before starting the next.

### Actual behavior

Test crash because port is already in use:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.595 s <<< FAILURE! - in org.test.SecondLambdaHandlerIT
[ERROR] org.test.SecondLambdaHandlerIT.testSimpleLambdaSuccess  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.amazon.lambda.deployment.DevServicesLambdaProcessor#startEventServer threw an exception: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
...
```

### How to Reproduce?

[project.zip](https://github.com/quarkusio/quarkus/files/8521206/project.zip)

Open the project zip and run `mvn clean verify -Dnative -Dquarkus.native.container-build=true`

### Output of `uname -a` or `ver`

Linux NB01202 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.8.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by krisgerhard** [comment]
Did you find a workaround for it @czyba? Still an issue for me.

**Comment by krisgerhard** [comment]
Managed to solve it, but my usecase is a little different. I'm using same image for resteasy rest api and **one** lambda function. So for me the workaround was to not use quarkus-amazon-lambda extension :) :(

**Comment by czyba** [comment]
Unfortunately I wasn't able to get it to work. In the end we decided against using quarkus for that particular use case and stopped evaluation in our team.

**Comment by krisgerhard** [comment]
@matejvasek, @patriot1burke could you take a look at this issue?

**Comment by patriot1burke** [comment]
> Managed to solve it, but my usecase is a little different. I'm using same image for resteasy rest api and **one** lambda function. So for me the workaround was to not use quarkus-amazon-lambda extension :) :(

Resteasy (and I assume quarkus-amazon-lambda-http) and a normal, lambda function cannot be mixed together in one project (native or .jar).

**Comment by patriot1burke** [comment]
The problem is that dev services are started twice for integration testing.

@geoand The following code executes dev services again and I can't figure out why.  The performCustomBuild is not asking for dev service build item.  Any ideas?

https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java#L269

**Comment by patriot1burke** [comment]
> The problem is that dev services are started twice for integration testing.
> 
> @geoand The following code executes dev services again and I can't figure out why. The performCustomBuild is not asking for dev service build item. Any ideas?
> 
> https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusIntegrationTestExtension.java#L269

I think this line was causing it...I changed things to use CuratedApplicationShutdownBuildItem

**Comment by geoand** [comment]
👌
