### ISSUE TITLE
quarkus-oidc: logout.path does not honor root-path

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#25045]
### Describe the bug

If the `quarkus.http.root-path` is changed, this is not taken into account when specifying `quarkus.oidc.logout.path`.

see also #24728

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by mschorsch** [comment]
@sberyozkin Can you take a look in this issue. This seems to be a similar case as https://github.com/quarkusio/quarkus/issues/24728. Thanks.

**Comment by sberyozkin** [comment]
@mschorsch I'm not sure how to address this issue yet, `CodeAuthenticationMechanism` has many different paths, and I'm starting doubting if a fix for #24728 was correct and instead paths should be configured with `${quarkus.http.root-path}` prefixes when necessary, instead of individual extensions (apart from Vert.x HTTP and various `/q` handlers taking care of if `http.root.path`).

It needs to be discussed more

**Comment by sberyozkin** [comment]
@mschorsch I'm sorry but I'm going to close this issue for now. Please prepend `${http.root.path}` to the path related properties to retain a flexibility to keep switching to different root paths including a default "/" value. 
I agree it is less ideal compared to `${quarkus.http.root-path}` being added internally but I'm worried it can start a chain effect of causing different migration issues. 

I've also opened #25144 to revert the #24728 fix - it is my fault I have not thought it through carefully.

I've also started a discussion at https://groups.google.com/g/quarkus-dev/c/_5QU2yMxHCw, you are welcome to contribute to it. Perhaps we can work out a simple uniform mechanism to make the prepending happening under the hood across all the extensions similarly to what David Lloyd suggests.

**Comment by sberyozkin** [comment]
@mschorsch I've opened an issue to track it, #25154, I'm not sure when I'll look at it, but it will be tracked, thanks
