### ISSUE TITLE
Update quarkus.jacoco.includes or quarkus.jacoco.excludes with an exampel?

### ISSUE THREAD

**Issue by agreedSkiing** [quarkusio/quarkus#25063]
### Description

Just to help other people would it be possible to update and add examples to the includes or excludes configuration text? Me and a colleague spent some time (1½ hour) digging through the quarkus repo and plexus-utils repo to find an example on how the exclude filtering work.``

### Implementation ideas

Update excludes or includes with a simple exampel on filtering works. Somehting like this **\*.class, modules\*\** which was found in plexus-util code base https://github.com/sonatype/plexus-utils/blob/5ba6cfcca911200b5b9d2b313bb939e6d7cbbac6/src/main/java/org/codehaus/plexus/util/DirectoryScanner.java#L127

**Comment by gsmet** [comment]
@agreedSkiing PR welcome!

**Comment by gsmet** [comment]
PR merged here: https://github.com/quarkusio/quarkus/pull/25168 .
