### ISSUE TITLE
Quarkus proxy ForwardedParser doesn't support a defacto forwarded header fallback

### ISSUE THREAD

**Issue by luneo7** [quarkusio/quarkus#25077]
### Describe the bug

According to Quarkus docs https://quarkus.io/guides/http-reference#reverse-proxy we should be able to combine defacto proxy forwarding headers `Forwarded` with the non defacto `X-Fowarded`, and the standard headers should have precedence

> Both configurations related to standard and non-standard headers can be combined, although the standard headers configuration will have precedence.

But when setting the configs, you either set to use `Forwarded` or `X-Forwarded` and there is no way to use them both.

I've caught that when using Keycloak (https://github.com/keycloak/keycloak/issues/11580)

### Expected behavior

Check for `Forwarded` header, if doesn't exists uses `X-Forwarded` header

### Actual behavior

Uses `Forwarded` header or `X-Forwarded` header

### Additional information

It would be nice to have a way of also adding a custom handler, so we could also build a custom Vert.x handler and add it to Quarkus configuration and it would be picked up during build time.

**Comment by geoand** [comment]
The implementation seems to only consider `FORWARDED` if `quarkus.http.allow-forwarded=true` while the various `X-FORWARDED-*` headers are only considered if ``quarkus.http.allow-forwarded=false`.

I don't know if this is the expected behavior, so I'll leave this to @cescoffier and @stuartwdouglas

**Comment by sberyozkin** [comment]
@ejba did a nice work on the original code, @ejba, would you like to look at this issue ?

Given @geoand's analysis, I propose to check both `Forwarded-*` and `X-Forwarded*` if both `quarkus.http.allow-forwarded=true` and a new `quarkus.http.allow-x-forwarded=true` are set. `quarkus.http.allow-x-forwarded` should probably have no default value set at the injection time but defaulted to `true` if `quarkus.http.allow-forwarded=false` to retain the current behavior...

**Comment by ejba** [comment]
@sberyozkin it will be a pleasure to be helpful again!

**Comment by sberyozkin** [comment]
@ejba Thanks a million :-)
