### ISSUE TITLE
WiringProcessor incorrectly produces "mp.messaging.incoming."<channel name> configuration property.

### ISSUE THREAD

**Issue by ylepikhov** [quarkusio/quarkus#25089]
### Describe the bug

WiringProcessor incorrectly produces "mp.messaging.incoming."<channel name> configuration property for each injection point qualified with `@Channel` annotation and is not `Emitter` nor `MutinyEmitter`.

See extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/WiringProcessor.java
```java
            if (channel.isPresent() && !(isEmitter || isMutinyEmitter)) {
                handleChannelInjection(appChannels, channels, channel.get());
            }
``` 
There is no check for injected type being `Publisher` or `PublisherBuilder` or one with configured `EmitterFactory`.
If you also have configured outgoing channel with the same name there will be runtime exception during Smallrye initialization:
```
SRMSG00073: Invalid configuration, the following channel names cannot be used for both incoming and outgoing [<channel name>]
``` 
This behaviour prevents you from using `@Channel` as a regular qualifier for custom CDI injection. 

### Expected behavior

Quarkus deployment extension must not produce incoming channel configuration for injection points qualified with `@Channel` which is not  `Emitter`, `MutinyEmitter`, `Publisher`, `PublisherBuilder` or one with configured `EmitterFactory`.

### Actual behavior

Quarkus deployment extension produces "mp.messaging.incoming."<channel name> configuration property for each injection point qualified with `@Channel` annotation and is not `Emitter` nor `MutinyEmitter`.

### How to Reproduce?

1. Add channel outgoing configuration in config file
```
# you may use any connector name, but connector must be specified 
mp.messaging.outgoing.test.connector=test
mp.messaging.outgoing.test.address=test
```
2. Create CDI bean definition with `@Channel` qualified producer method
``` kotlin
interface TestBean {
    fun call()
}

@ApplicationScoped
class TestBeanFactory {
    @Produces
    @Channel("")
    fun testBean() = object : TestBean {
        override fun call() {

        }
    }
}
```
3. Create CDI bean to inject our test bean
```kotlin
@ApplicationScoped
class TestApp(@param:Channel("test") private val testBean: TestBean) {

    fun onStart(@Observes event: StartupEvent) {

        testBean.call()
    }
}
```

4. Run the app and you will see error:
```
SRMSG00073: Invalid configuration, the following channel names cannot be used for both incoming and outgoing: [test]
```

**Comment by geoand** [comment]
cc @ozangunalp @cescoffier

**Comment by ozangunalp** [comment]
I am not sure what you are trying to do but you can't produce an _arbitrary_ bean using reactive messaging `@Channel` qualifier and expect that it works with the framework. 
If you are trying to test out the custom emitter feature, it is not released yet upstream on Smallrye Reactive Messaging and therefore not supported by the Quarkus extension.
Also please beware that it _will_ be an experimental feature and would probably break unexpectedly if you try to use it in an unintended use case. Of course, feedback would be welcomed to improve these features.

**Comment by ylepikhov** [comment]
```
can't produce an arbitrary bean using reactive messaging @Channel qualifier and expect that it works with the framework.
```
Why not? I mean if it does not contradict CDI spec nor Eclipse Reactive Messaging spec I'm free to use qualifiers as intended. 
The described behaviour is a side effect obviously.

I'm interested in reusing `@Channel` qualifier to implement request/response component (client side). I can introduce new qualifier but it seems ugly.

**Comment by ozangunalp** [comment]
I think it was safe for Quarkus to assume that the `@Channel` is an incoming channel unless it is an `Emitter`.
In the Reactive Messaging spec as well, `@Channel` annotation is for injecting `Publisher` or `PublisherBuilder` (incoming channel), and `Emitter`s (outgoing channel).

Are you also using the `@Channel` qualifier to integrate your bean to Reactive Messaging?

**Comment by ylepikhov** [comment]
> I think it was safe for Quarkus to assume that the `@Channel` is an incoming channel unless it is an `Emitter`. In the Reactive Messaging spec as well, `@Channel` annotation is for injecting `Publisher` or `PublisherBuilder` (incoming channel), and `Emitter`s (outgoing channel).
> 
> Are you also using the `@Channel` qualifier to integrate your bean to Reactive Messaging?

Yes, but my bean has outgoing channel semantics.

**Comment by cescoffier** [comment]
Ca. You provide an example of what you are trying to do? 

It was not intended to reuse the @Channel qualifier outside of the case mentioned in the spec.

**Comment by ylepikhov** [comment]
I'm trying to implement support for request/reply exchanges. With `Emitter` I can only send messages. But I also want to be able to send (request) message and receive reply message. Idea was to provide interface `RequestReplyExchange`, which instances could be injected.

```kotlin
interface RequestReplyExchange<Rq, Rs> {
    fun request(message: Message<Rq>): CompletionStage<Message<Rs>> // not suspend fun, but CompletionStage for Java compatibility
    fun request(payload: Rq): CompletionStage<Rs>
}
```

`@Channel` qualifier was supposed to be used to specify request message destination.

```kotlin
@ApplicationScoped
class MyAppBean @Inject(@param:Channel("test") exchange: RequestReplyExchange<String, String>) {

    suspend fun doCall() {
        // injected exchange sets id and replyTo values, sends message and awaits response  
        val result = exchange.request("Hello").await()
    }
}
```

`RequestReplyExchange` is sort of `Emitter` with ability to await replies. But Quarkus extension does not support injecting qualified instances of `Emitter` subinterfaces nor custom Smallrye emitters with configured `EmitterFactory`.

**Comment by ylepikhov** [comment]
> 

Actually, I considered this, but feature was not documented (I found it in source code), and it doesn't work in current Quarkus version anyway. I will try it, when it would be released.

**Comment by cescoffier** [comment]
Custom emitters have been added. Can you re-check?

**Comment by ylepikhov** [comment]
What do you mean? Latest release (2.9.0.Final) does not have Custom emitters support yet.

**Comment by cescoffier** [comment]
You will need to build Quarkus "main" branch.

**Comment by ozangunalp** [comment]
@ylepikhov do you have any update on this? Were you able to use custom emitters for implementing request-reply semantics? I think we can close this one if the described issue is resolved.

**Comment by cescoffier** [comment]
Closing - please re-open after investigation.

**Comment by ylepikhov** [comment]
I've already tried it (thought I've responded but...). It's works.

**Comment by cescoffier** [comment]
Thanks for the feedback @ylepikhov !
