### ISSUE TITLE
JTA enlisted XAResource is neither suspended nor resumed

### ISSUE THREAD

**Issue by mensinda** [quarkusio/quarkus#25088]
### Describe the bug

Custom `XAResource`s are neither suspended nor resumed when the transaction is resumed or suspended. 

### Expected behavior

That the custom `XAResource` is suspended and resumed.

### Actual behavior

That suspend and resume (via `start` and `end`) is not called.

### How to Reproduce?

I have made a [minimal project](https://github.com/mensinda/jta-quarkus-suspend-bug) to reproduce this. Just clone the repo out and run `mvn clean verify`. There are more details in the [README.md](https://github.com/mensinda/jta-quarkus-suspend-bug/blob/master/README.md).

### Output of `uname -a` or `ver`

Linux XX_SECRET_XX 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by mmusgrov** [comment]
Thanks for the report. I discussed it with some of my transactions colleagues and it boils down to a question of interpretation of the spec. JTA was designed for use in app servers and as long as we don't explicitly contradict the spec and as long as we pass the TCK then our implementation has to be viewed as conforming. Also, JTA was modelled on the OTS spec and that matches what we do (see `Section 2.2.10 suspend`).

If we did it the way that you are expecting then the user (i.e. the application) would incur the large number of network round trips that results if you keep enlisting/delisting on context switches. The way it's implemented is that the app/tx owns the XAResource instance exclusively until it's explicitly returned (which is usually done by the connection pool) at tx completion, ie it is unavailable for use by any other app/txn, even if the owning tx is suspended.

**Comment by mensinda** [comment]
If this is the desired behavior, is there then another way to detect if / when a transaction is suspended / resumed?

**Comment by mmusgrov** [comment]
Since the suspend call disassociates the transaction context from the calling thread, calling getTransaction() on the TransactionManager should return a null transaction.

**Comment by mmusgrov** [comment]
@mensinda  Narayana did once provide events for ASSOCIATED (a transaction is associated with the current thread) and DISASSOCIATING (a transaction is just about to be disassociated from the current thread) that listeners could subscribe to but this functionality was moved into the WildFly Transaction Client project so it's only available for app servers that use that.

Why do you need this information and does TransactionManager.getTransaction() or TransactionManager.getStatus() cater for your requirement?

Can we close this one yet?

**Comment by mensinda** [comment]
Yes, I have successfully worked around this. Sorry for the delay.

**Comment by mmusgrov** [comment]
Good news @mensinda , thanks for investigating further.
@geoand This issue can be closed now.

**Comment by geoand** [comment]
Thanks for the updatye
