### ISSUE TITLE
ClassNotFoundException for a library when running native integration tests

### ISSUE THREAD

**Issue by czyba** [quarkusio/quarkus#25096]
### Describe the bug

While trying to set up a multi-module maven project to extract source code for multiple lambdas I ran across the issue that it seems that Integration tests for native images cannot use classes from dependencies that are part of the `main/src` artefact. My original issue used the class in question in an object mapper with jackson but none of that seems to be necessary to trigger the behavior, see example.

Things I tried:

 - Use a separate Test Jar (Classes could be found in the test jar but not the actual jar)
 - `@RegisterForReflection` both at the class itself and at Registers which register it for third party jars
 - Explicit reflection-config.json mapping
 - `@Unremovable`

None of that exactly helped. And I'd like to believe that the solution is not to put all my source code into the test-jar and use said jar in a compile scope.

### Expected behavior

Tests run without issue.

### Actual behavior

Integration Tests crash with a ClassNotFoundException:

```
[INFO] Running org.acme.SomeIT
2022-04-22 12:28:22,456 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
Executing "app/target/lambda-1.0-SNAPSHOT-runner -Dquarkus.log.file.path=app/target/quarkus.log -Dquarkus.log.file.enable=true"
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-04-22 12:28:23,243 INFO  [io.quarkus] (main) lambda 1.0-SNAPSHOT native (powered by Quarkus 2.8.0.Final) started in 0.322s.
2022-04-22 12:28:23,288 INFO  [io.quarkus] (main) Profile prod activated.
2022-04-22 12:28:23,289 INFO  [io.quarkus] (main) Installed features: [cdi]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.371 s <<< FAILURE! - in org.acme.SomeIT
[ERROR] org.acme.SomeIT.test  Time elapsed: 0.051 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/acme/SomeClass
Caused by: java.lang.ClassNotFoundException: org.acme.SomeClass
```

### How to Reproduce?

[project.zip](https://github.com/quarkusio/quarkus/files/8539997/project.zip)

Unzip project and run: `mvn clean verify -Dnative -Dquarkus.native.container-build=true`

### Output of `uname -a` or `ver`

Linux NB01202 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.8.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by fhm84** [comment]
I had a very similar problem. Upgrading the maven-surefire-plugin version from 3.0.0-M5 to 3.0.0-M7 solved the issue for me.

**Comment by famod** [comment]
Thanks for the pointer @fhm84!
The reproducer passes with maven-surefire-plugin 3.0.0-M7 and Quarkus will generate projects with M7 from 2.10.CR1 on, so I'm closing this.
