### ISSUE TITLE
quarkus-smallrye-reactive-messaging-kafka / quarkus-kafka-client + SSL is using too much RAM memory in Native mode

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25098]
### Describe the bug

Scenario
----------------
`git clone git@github.com:quarkus-qe/quarkus-test-suite.git`
cmd: `mvn clean verify -Dnative -Dit.test=InfinispanKafkaSslIT -Dall-modules -pl messaging/infinispan-grpc-kafka`

Memory used: `10Gb +`

This sceanrio is usgin a `quarkus-kafka-client` producer/consunmer with SSL

Sasl and a regular Kafka client work as expected.

### Expected behavior

Same memory usage as JVM mode (more or less)

### Actual behavior

more than 10Gb of memory usage

### Output of `java -version`

openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by cescoffier** [comment]
Does it also happen when you do not have infinispan? 

If that's the case there is not much we can do as we delegate the connection handling to the underlying client.

**Comment by cescoffier** [comment]
@pjgg Any update?

**Comment by cescoffier** [comment]
NOTE: I deployed kafka using TLS on OpenShift and I didn't notice a memory overhead.

**Comment by Karm** [comment]
@pjgg
Is this  the whole test that is problematic? i.e. there are no volumes of test data, it's merely a smoke check that causes the allocation *at runtime*?

```
@Test
void testKafkaClientSSL() {
    await().untilAsserted(() -> {
        given()
                .queryParam("key", "my-key")
                .queryParam("value", "my-value")
                .when()
                .post("/kafka/ssl")
                .then()
                .statusCode(200);

        get("/kafka/ssl")
                .then()
                .statusCode(200)
                .body(StringContains.containsString("my-key-my-value"));
    });

    get("/kafka/ssl/topics")
            .then()
            .statusCode(200)
            .body(StringContains.containsString("hello"));
}
```

Could you extract a minimal reproducer into a separate project that makes it clear what actually happens at the test runtime, please? The test suite repo is too convoluted and opaque for starting to dissect callgraphs and mem allocation.

**Comment by pjgg** [comment]
@Karm 
Here you have a "minimal reproducer"

https://github.com/pjgg/kafka-ssl-memory-leak

I think that I was able to reproduce and isolate the problem. Looks that the following properties (that are not used at all), are the cause of the unexpected memory usage. 

```shell
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.IntegerSerializer

mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
```

Is an application issue (this application is used in several scenarios, and these properties only apply to one scenario but don't make sense for the SSL scenario), however, I think that should be reviewed because sound quite weird that properties that are not used could have this impact into an application.

WDYT?

**Comment by cescoffier** [comment]
The incoming part is most probably polling data from kafka and accumulating them in the queue (until we pause the retrieval because the queue is full).

**Comment by cescoffier** [comment]
Also, as soon as we have a kafka client created (used or not), we have health / monitoring / and so on happening. That should not take much memory, but maybe it has an impact.

**Comment by ozangunalp** [comment]
The incoming channel would not be started as there is no subscription to it (it is not used).
But the producer channel will still try to create a Kafka producer eagerly. 
As it is not configured properly with SSL security protocol details it would fail and try to connect. 
Although I don't think this in itself would cause a memory leak.

@pjgg I don't know if it is intended but the test is actually creating a new producer client for each record produced. 
Maybe the previous reconnection of the producer and the fact that the app is constantly creating new producer instances results in a greater memory leak.

**Comment by pjgg** [comment]
This issue is under investigation but looks like is directly connected to an application miss-configuration on SSL kafka producer/consumers. 

Related to: https://cwiki.apache.org/confluence/display/KAFKA/KIP-498%3A+Add+client-side+configuration+for+maximum+response+size+to+protect+against+OOM

**Comment by pjgg** [comment]
This issue could be closed. Is not related to Quarkus itself. We had several issues with our application:
1. [producers](https://quarkus.io/guides/cdi-reference#simplified-producer-method-declaration) by default are "sessionScope/request" scope as you can see on this [doc](https://docs.jboss.org/weld/reference/3.1.9.Final/en-US/html/producermethods.html#_scope_of_a_producer_method), so in our case, we want a single instance of Kafka producer/consumer (we don't want to create an instance per msg :) ). The solution is as simple as adding a @Singleton annotation over your producer
2. There is a memory leak with Kafka + SSL that is especially visible in native mode + bare-metal, but is not related to Quarkus itself. The issue was already reported in apache Kafka and takes place when you have some misconfiguration on your KafkaSSL client.
