### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by BechirLandolsi** [quarkusio/quarkus#2509]
Hello, is it possible to use GraphQL and the GUI GraphiQL with Quarkus? @gsmet

**Comment by tlvenn** [comment]
Yes it would be great to have an official integration with GraphQL / graphql-spqr.

**Comment by kenfinnigan** [comment]
It might be possible to use the libraries directly as dependencies, though not sure about native for that.

Longer term we will likely provide an extension for MP GraphQL once https://github.com/smallrye/smallrye-graphql has an implementation.

**Comment by emmanuelbernard** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/quarkus-dev/graphql%7Csort:date/quarkus-dev/nySrZlQNBxo/9zK8pciNAAAJ

**Comment by xhumanoid** [comment]
is what do you want?

https://quarkus.io/guides/all-config#quarkus-vertx-graphql_quarkus-vertx-graphql

https://github.com/quarkusio/quarkus/commits/master/extensions/vertx-graphql

**Comment by nimo23** [comment]
Now **MP GraphQL** (https://projects.eclipse.org/projects/technology.microprofile/releases/graphql-1.0) is available. 

When will it be included in Quarkus?

**Comment by emmanuelbernard** [comment]
@kenfinnigan @phillip-kruger do you think we will add RS GraphQL in Quarkus within the next 3-6 months?

**Comment by phillip-kruger** [comment]
Hi @emmanuelbernard - I am working on this (on and off) when I get time. I believe it should be done in the next 3-6 months. @kenfinnigan ?

**Comment by kenfinnigan** [comment]
@phillip-kruger has a few tasks right now, we can discuss where GraphQL fits in relation to the others if we want this sooner

**Comment by marceloverdijk** [comment]
I hope sooner.. is there something the community can do?

**Comment by nimo23** [comment]
@marceloverdijk I think in the meantime you can add this API in your pom.xml as usual. It should work for jvm mode (not native mode).

**Comment by nimo23** [comment]
>Which api?

https://mvnrepository.com/artifact/org.eclipse.microprofile.graphql

Look https://github.com/eclipse/microprofile-graphql
```

<dependency>
  <groupId>org.eclipse.microprofile.graphql</groupId>
  <artifactId>microprofile-graphql-api</artifactId>
  <version>1.0.1</version>
</dependency>
```

Should work in non-native mode..
