### ISSUE TITLE
Traces are not propagated after #24666

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#25097]
### Describe the bug

Traces are not propagated after #24666 change in Quarkus main

We see that https://github.com/quarkus-qe/beefy-scenarios tests (mvn clean verify -pl 300-quarkus-vertx-webClient)

`ChuckNorrisResourceTest.httpClientShouldHaveHisOwnSpan` test fails on `thenTraceDataSizeMustBe(greaterThan(0));` check from jaeger endpoint
You can put `System.out.println(resp.getBody().prettyPrint());` on line 112 of ChuckNorrisResourceTest.java

Also `301-quarkus-vertx-kafka` module fails.

### Expected behavior

Spans to be propagated, tests in 301-quarkus-vertx-kafka and 300-quarkus-vertx-webClient to pass

### Actual behavior

Tests fail

### How to Reproduce?

 - `git clone https://github.com/quarkus-qe/beefy-scenarios`
 - cd beefy-scenarios
 - `mvn clean verify -pl 300-quarkus-vertx-webClient`

(make sure to have the latest Quarkus main build)

PASS:  `mvn clean verify -pl 300-quarkus-vertx-webClient -Dquarkus.platform.version=2.8.1.Final`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by rsvoboda** [comment]
CC @glefloch

**Comment by rsvoboda** [comment]
This change to Quarkus makes the traces propagated and the tests pass again
```diff
--- a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java
+++ b/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/QuarkusBootstrap.java
@@ -159,19 +159,7 @@ public class QuarkusBootstrap implements Serializable {
                 appModelFactory.setEnableClasspathCache(true);
             }
         }
-        CurationResult curationResult = appModelFactory.resolveAppModel();
-        if (curationResult.getApplicationModel().getAppArtifact() != null) {
-            if (curationResult.getApplicationModel().getAppArtifact().getArtifactId() != null) {
-                buildSystemProperties.putIfAbsent("quarkus.application.name",
-                        curationResult.getApplicationModel().getAppArtifact().getArtifactId());
-            }
-            if (curationResult.getApplicationModel().getAppArtifact().getVersion() != null) {
-                buildSystemProperties.putIfAbsent("quarkus.application.version",
-                        curationResult.getApplicationModel().getAppArtifact().getVersion());
-            }
-        }
-
-        return new CuratedApplication(this, curationResult, classLoadingConfig);
+        return new CuratedApplication(this, appModelFactory.resolveAppModel(), classLoadingConfig);
     }
```

**Comment by rsvoboda** [comment]
I will double check what's in Jaeger and under what names

**Comment by rsvoboda** [comment]
So this is false alarm. After quite some time spent on bisecting Quarkus main to identify the problematic commit and now playing with the Jaeger I realized that I need to update the service name that is queried from Jaeger

BEFORE: http://localhost:16686/api/traces?service=%3C%3Cunset%3E%3E&limit=50&lookback=1h&operation=/trace/ping
NOW: http://localhost:16686/api/traces?service=300-quarkus-vertx-webclient&limit=50&lookback=1h&operation=/trace/ping

**Comment by glefloch** [comment]
Sorry for the troubles it makes, thanks for the fix.

**Comment by rsvoboda** [comment]
That's fine. Your PR made the things right.

It was just time consuming to get to it 😀.
