### ISSUE TITLE
QuarkusTest and TestNG together

### ISSUE THREAD

**Issue by politrons** [quarkusio/quarkus#2510]
This is not an issue but a question. It´s possible use @QuarkusTest to start the service and then use @Test of TestNG to have some Stress test.

Regards

**Comment by stuartwdouglas** [comment]
At the moment we have no real plans to support TestNG. It should not be too hard to implement by just copying what the JUnit extensions do, but I am not sure we would want it in core at this stage.

We are working to enable a community ecosystem, so once this is ready we may end up with a community supported TestNG extension.
