### ISSUE TITLE
Swagger-ui webjar not found in gradle setup

### ISSUE THREAD

**Issue by jkopcsek** [quarkusio/quarkus#2511]
Hi there,

i'm trying to add swagger ui to my kotlin/gradle quarkus project (yeah, testing your non java/maven support to the bones ;-)). Sadly, when i start the app in dev mode, i get an error.

Basic project setup:
* build.gradle.kts
** quarkus dirs and 0.15.0 dependencies set up and working
** add api("io.quarkus:quarkus-swagger-ui")

What do i see?
* "gradle build quarkusDev" reports:
```
Caused by: java.lang.RuntimeException: Could not resolve artifact org.webjars:swagger-ui:null. Please make sure it is present and contains a META-INF/MANIFEST.MF file. Note that artifacts that are part of the same project may not always be resolvable, in this case you should generate a META-INF/jandex.idx file instead using the Jandex Maven plugin.
        at io.quarkus.deployment.index.ClassPathArtifactResolver.getArtifact(ClassPathArtifactResolver.java:93)
        at io.quarkus.swaggerui.deployment.SwaggerUiProcessor.getSwaggerUiArtifact(SwaggerUiProcessor.java:118)
        at io.quarkus.swaggerui.deployment.SwaggerUiProcessor.registerSwaggerUiServletExtension(SwaggerUiProcessor.java:98)
```

What did i try?
* switch between implementation and api source sets
* adding api("org.webjars:swagger-ui:3.22.1") manually
* constraining the swagger-ui version
* verify the webjars-jar exists under .gradle/lib (it does!)

Nothing seems to help :-( Any idea what might be wrong here?

**Comment by stuartwdouglas** [comment]
Do you have a simple reproducer you can share on github, it will make debugging this quicker.

Looking at the error I am guessing there must be something different with how gradle builds its class path. This is handled via https://github.com/quarkusio/quarkus/blob/a184500ad4f0410d161307db69c21333afd7c3f7/core/deployment/src/main/java/io/quarkus/deployment/index/ClassPathArtifactResolver.java#L37, which expects the class-path to contain an artifact in the standard maven repo format. 

This is kinda hacky, ideally we would plug in a resolver based on the current environment, but this also needs to be able to just run from the IDE where this info is not available. I am guessing gradle just uses a different format and we need to update this class to take it into account.

**Comment by jkopcsek** [comment]
I created a setup for this problem here:
https://github.com/jkopcsek/quarkus-kotlin-gradle-demo/tree/bug/swagger-ui-not-found

As you can see, the project is fine on the master and breaks by adding the swagger-ui dependency.

If you can give me an indication on how to debug the deployment code, i'm happy to investigate the problem myself. At the moment, intellij doesn't find those classes at all.

**Comment by aloubyansky** [comment]
This should be fixed now. Thanks!
