### ISSUE TITLE
How to reduce the use of reflections in https://quarkus.io/container-first/

### ISSUE THREAD

**Issue by dameng58** [quarkusio/quarkus#25121]
### Describe the bug

i'm see container first in quarkus.io.And I'm curious about the Reduction in Reflection usage:

As much as possible Quarkus tries to avoid reflection, reducing startup time and memory usage. During the built-time processing, extensions can analyze the application code and the classes available on the classpath and replace reflection calls with regular invocations. The usage of dynamic proxies is also prevented by using generating custom proxy at build time.

Arc, the dependency injection framework used by Quarkus, eliminates all the reflection calls and deduces the injection graph at build time. So, when the application starts, no expensive lookups; it’s done already!

Can I understand it that way?
In build-time processing, extensions can replace reflection calls with new Object(), and replace dynamic proxies with generating custom proxy, then Serialize the results to a file.In runtime, the application read the file which contains serialized results.

Arc，eliminates  all the reflection calls with new Object()？

And Where is the main source code for these two parts? I would like to refer to the reference

Thank.

**Comment by dameng58** [comment]
@sberyozkin @geoand

**Comment by geoand** [comment]
> In build-time processing, extensions can replace reflection calls with new Object(), and replace dynamic proxies with generating custom proxy, then Serialize the results to a file.In runtime, the application read the file which contains serialized results.

This is not really correct. What Quarkus does is generate classes (in bytecode) that directly instantiate and call the target classes / methods.
So the "serialization" is really just bytecode generation that the runtime JVM sees as regular classes
