### ISSUE TITLE
[Doubt] Is it possible to start a bean[EAGER] on startup time?

### ISSUE THREAD

**Issue by larchanjo** [quarkusio/quarkus#2512]
I have been testing Quarkus for one month...and now I want to inject some configuration at startup time, and this kind of beans is more infrastructure configuration than a business bean, so in quarkus, it is not possible to create a bean that creates a Queue on Rabbit, etc..

Can anyone help me with it?

**Comment by stuartwdouglas** [comment]
You can add a method that observes io.quarkus.runtime.StartupEvent and your bean will be created at startup.

**Comment by larchanjo** [comment]
Thank you @stuartwdouglas.

For curiosity this works on quarkus 0.15.0 version and there is a tutorial to help you about bean lifecycle https://quarkus.io/guides/application-lifecycle-events-guide
