### ISSUE TITLE
Support bouncyCastle libs  + Infinispan + FIPS

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25136]
### Describe the bug

Infinispan: 12.1 / 14
Quarkus: 2.7.5.Final
Java 11 / 17

Seems that bouncy castle lib is not supported until Infinispan 14.0. But If I move on to infinispan 14 and configure Quarkus in order to use `BCFIPSJSSE` then I got the following error:

```
13:51:46,057 INFO  [app] Caused by: java.security.KeyStoreException: BCFKS not found
13:51:46,057 INFO  [app]        at java.base/java.security.KeyStore.getInstance(KeyStore.java:871)
13:51:46,057 INFO  [app]        at org.infinispan.commons.util.SslContextFactory.getTrustManagerFactory(SslContextFactory.java:172)
13:51:46,057 INFO  [app]        at org.infinispan.client.hotrod.impl.transport.netty.ChannelInitializer.initSsl(ChannelInitializer.java:154)
13:51:46,057 INFO  [app]        ... 20 more
13:51:46,057 INFO  [app] Caused by: java.security.NoSuchAlgorithmException: BCFKS KeyStore not available
13:51:46,057 INFO  [app]        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
13:51:46,057 INFO  [app]        at java.base/java.security.Security.getImpl(Security.java:701)
13:51:46,057 INFO  [app]        at java.base/java.security.KeyStore.getInstance(KeyStore.java:868)

```

My infisnispan configuration looks like the following one:
```
# Infinispan
quarkus.infinispan-client.trust-store=src/main/resources/server.jks
quarkus.infinispan-client.trust-store-password=password
quarkus.infinispan-client.trust-store-type=BCFKS

quarkus.infinispan-client.server-list=localhost:11222
quarkus.infinispan-client.use-auth=true
```

In my opinion, I am missing some configurations that we already have in orders [modules](https://quarkus.io/guides/security-customization#bouncy-castle-jsse-fips), something like `quarkus.infinispan-client.trust-store-provider=BCFIPS`

[Reproducer](https://github.com/pjgg/quarkus-test-suite/blob/feat/infisnipan_fips_reproducer/messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaIT.java)
```
git clone git@github.com:quarkus-qe/quarkus-test-suite.git
git checkout feat/infisnipan_fips_reproducer
```

Scenario
```
mvn clean verify -Dall-modules -pl messaging/infinispan-grpc-kafka -Dit.test=InfinispanKafkaIT
```

I am not sure if `BCFIPS` is supported and if does then, I am not sure how to use it. Should I add `quarkus-security` extension ?, and If I am able to set `BCFIPS` as a provider I understand that then later I will not need any [JVM security custom](https://docs.oracle.com/middleware/11119/wls/SECMG/fips.htm#A1233313) configuration, isn't it? (on `quarkus.http.ssl` is not need it)

**Comment by sberyozkin** [comment]
Hi @pjgg 

I think it has to be done at the infinispan client level, similarly to
```
quarkus.http.ssl.certificate.key-store-file-type=BCFKS
quarkus.http.ssl.certificate.key-store-provider=BCFIPS
```

both a key store file type and provider type have to be configurable. I believe it is a `key-store-provider=BCFIPS` which registers `BCFKS`

**Comment by sberyozkin** [comment]
FYI, here is how a Vert.x Client is configured:

https://github.com/quarkusio/quarkus/blob/main/integration-tests/bouncycastle-fips-jsse/src/test/java/io/quarkus/it/bouncycastle/BouncyCastleFipsJsseTestCase.java#L62

**Comment by pjgg** [comment]
Yes but ... at infinispan client level there is not a `key-store-provider`.

`quarkus.infinispan-client.key-store-provider=BCFIPS`

**Comment by sberyozkin** [comment]
@pjgg Sure - at some point it was not available at the Vert.x level either so the Vertx team enhanced it to support this extra property, the same would need to be done at the Infinispan client level

**Comment by tristantarrant** [comment]
The Infinispan client already supports setting a provider since ISPN-12882 `infinispan.client.hotrod.ssl_provider`, so this needs to be exposed in the extension.
