### ISSUE TITLE
`Quarkus-cli create app`  change default extensions on upstreams

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25142]
### Describe the bug

`quarkus create app` creates an application with `quarkus-resteasy` as a default extension on Quarkus 2.7.5
The same statement with Quarkus Upstream (`999-SNAPSHOT`), add as a default extension `quarkus-resteasy-reactive`. 

I am not sure if this change is intended or was something leftover. 

Summary: 

Quarkus-cli `999-SNAPSHOT`, default RestEasy Extension -> `quarkus-resteasy-reactive`
Quarkus-cli `2.7.5.Final`, default RestEasy Extension -> `quarkus-resteasy`

**Comment by maxandersen** [comment]
This is expected. Default changed in 2.8 and 999 snapshot is newer.

**Comment by pjgg** [comment]
Thank you @maxandersen 
DocRef: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8#resteasy-reactive-by-default
