### ISSUE TITLE
Cryptic message about "END header not found" on build failure insufficient to track down the problem

### ISSUE THREAD

**Issue by Martin-Narvar** [quarkusio/quarkus#25145]
### Describe the bug

I am brand new to Java and Quarkus, and I am working on a project set up by other people. This project builds and deploys to production in CI/CD, so the issue is specific to my machine.

When I try to build my application I get this error:

Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.1.Final:generate-code (default) on project {PROJECT_NAME}: Quarkus code generation phase has failed: Failed to bootstrap the application: Failed to create the application model for {PACKAGE_NAME}::jar:1.3.0: Failed to inject extension deplpyment dependencies: Failed to create a new filesystem for /Users/{USERNAME}/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.4.1/maven-resolver-api-1.4.1.jar: zip END header not found

Note that I replaced private information with {} placeholders.
Note the mis-spelling of deployment should make it easy to find this in the code.

I am not sure if this is really a bug, but there is not enough information here for me to track down the issue.

### Expected behavior

This project compiles and deploys to production in the CI/CD pipeline, and should compile on my machine also.

### Actual behavior

The build fails with an unhelpful error message.

### Output of `uname -a` or `ver`

Darwin {MACHINE_NAME}.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "13.0.2" 2020-01-14 OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

Latest - don't know how to query this

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec Java version: 13.0.2, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by Martin-Narvar** [comment]
I was able to resolve my problem by deleting the `~/.m2/repository` folder.
It would still be a much better developer experience if the error message was more helpful.

**Comment by gsmet** [comment]
So first, if you are starting just now with Quarkus, I wouldn't use Quarkus 1.11, which is quite old.

Second, do you still have the full stracktrace around? That could help narrowing down the thing.
What would be clearer to you? Because that is a low level error obtained when you try to open a zip file.

Would having "Unable to open jar file: ..." before `Failed to create a new filesystem for /Users/{USERNAME}/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.4.1/maven-resolver-api-1.4.1.jar: zip END header not found` be enough for you?

**Comment by Martin-Narvar** [comment]
Firstly, I am personally new to the whole Java ecosystem and have never
worked with Quarkus before, but this solution was put together by other
engineers some time ago when 1.11 was probably the latest version.

I think something helpful would be along the lines of "Unable to open a
possibly corrupt JAR file. Try re-installing this package or deleting the
Maven repository so that the package will be re-downloaded" would have been
helpful.

Now that I am getting a bit more familiar with Java (this is day 3) I can
see how the original message made sense, but at the time it meant nothing
to me.

Thanks.

**Comment by geoand** [comment]
Thanks for reporting!

We are always on the lookout for better error messages (ideally actionable ones), so if you continue to have this problem with the latest versions of Quarkus, please let us know,

**Comment by cashewna** [comment]
Was getting frustrated with compile time failures, this helped, thank you!

> I was able to resolve my problem by deleting the `~/.m2/repository` folder. It would still be a much better developer experience if the error message was more helpful.
