### ISSUE TITLE
Scheduled - custom time zone support for cron-based schedules

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#25159]
### Description

The `@Scheduled` annotation could introduce the `timeZone` attribute that would allow users to specify the time zone for the cron expression.

**Comment by dhoffer** [comment]
Just checking on an ETA for this?  We could really use this feature.

**Comment by mkouba** [comment]
> Just checking on an ETA for this? We could really use this feature.

There's no ETA yet. Would you care to contribute? :wink:

**Comment by diabolicallabs** [comment]
I would. I did the same for vert.x in the cron module.
