### ISSUE TITLE
Config quarkus.config.locations is evaluated before applying profile

### ISSUE THREAD

**Issue by lamemind-ud** [quarkusio/quarkus#25186]
### Describe the bug

Hello,

the config `quarkus.config.locations` is evaluated before applying the profile.

~~~
quarkus.config.locations=file1.properties
%test.quarkus.config.locations=file1.properties,file2.properties
~~~

Launching tests, the "Test" profile is activated AFTER the `quarkus.config.locations` property being read. Thus `file2.properties` is not getting loaded.

But if you read the property via `@ConfigProperty(name = "quarkus.config.locations")`, the value is correct.

### Expected behavior

`%test.quarkus.config.locations` should be evaluated during tests

### Actual behavior

the default `quarkus.config.locations` property is evaluated

### How to Reproduce?

The bug is not reproducible using `@ConfigProperty(name = "quarkus.config.locations")`, that way the property is correctly read.

In order to reproduce you need to read a property declared in the not-loaded-config-file.

### Output of `java -version`

17.0.1

### Quarkus version or git rev

2.8.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by radcortez** [comment]
As a workaround, use `smallrye.config.locations`.
