### ISSUE TITLE
Add a default toString() implementation for PanacheEntities

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2518]
Nothing fancy but having a default `toString()` implementation for `PanacheEntity` with something like `MyClass<id>` could be helpful.

I would use the simple class name for now, and switch to the full name if people complains about it.

**Comment by machi1990** [comment]
I'll work on this one.

**Comment by Dufgui** [comment]
lol more quick then me ;o)

**Comment by FroMage** [comment]
Great!
