### ISSUE TITLE
Runner JAR is not correctly generated using Maven 3.8.5

### ISSUE THREAD

**Issue by jpechane** [quarkusio/quarkus#25209]
### Describe the bug

If I execute `mvn clean install -DskipTests=true -DskipITs=true -Passembly` on https://github.com/debezium/debezium there is a `debezium-server/debezium-server-dist/target/debezium-server-dist-2.0.0-SNAPSHOT-runner.jar` created.

This runner lacks `io.debezium` classes.

With Maven 3.8.4 the classes are there.

### Expected behavior

The classes in question should be present.

### Actual behavior

The classes in question are not present.

### How to Reproduce?

See description

### Output of `uname -a` or `ver`

Linux jpechane 5.14.0-1034-oem #37-Ubuntu SMP Tue Apr 19 14:13:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.5

**Comment by geoand** [comment]
@famod is this a known Maven bug perhaps?

**Comment by famod** [comment]
@jpechane can you try Maven 3.8.6 please?

That `assembly` profile contains many dependencies and there is a known issue in Maven 3.8.5 that affects Quarkus and was fixed in 3.8.6: https://issues.apache.org/jira/browse/MNG-7432

**Comment by jpechane** [comment]
@famod Hi, yes I can confirm the issue is no longer present in 3.8.6.

**Comment by geoand** [comment]
Thanks for the update!
