### ISSUE TITLE
EL Placeholder support in @RolesAllowed annotation

### ISSUE THREAD

**Issue by odellamaggiore** [quarkusio/quarkus#25245]
### Describe the bug

If we use an EL placeholder in @RolesAllowed annotation value, to make a reference to a config property, the placeholder is not resolved.
Example:

**MyClass.java**

```
@RolesAllowed("myrole_${role.suffix}")
public class MyClass
```

**application.yml**
```
role:
  suffix: someValue
```

This is something that works with Jakarta EE on EAP/Wildfly so I expected it to work also with Quarkus.

### Expected behavior

@RolesAllowed annotation value resolved to "myrole_someValue"

### Actual behavior

@RolesAllowed annotation value remains "myrole_${role.suffix}"

**Comment by sberyozkin** [comment]
Hi @radcortez, @dmlloyd Is it something that our configuration system can help with ? I guess it should work similar to this:
* The code which introspects in this case `@RolesAllowed` gets the annotation value and then, given the example in this issue,
* Config.resolve("myrole_${role.suffix}") and gets back `myrole_someValue`

I believe such a resolver code already exists since we already support such indirect property references in `application.properties`

Thanks

**Comment by dmlloyd** [comment]
Sure, it should be possible. The expression resolution is performed by `smallrye-common-expression` with a resolver which assesses the configuration system for its values.

**Comment by vsevel** [comment]
> I believe such a resolver code already exists since we already support such indirect property references in application.properties

hi @sberyozkin agreed. and that has been supported for many years in jboss.

**Comment by radcortez** [comment]
Check:

- https://github.com/smallrye/smallrye-common/blob/main/expression/src/main/java/io/smallrye/common/expression/Expression.java
- https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ExpressionConfigSourceInterceptor.java#L39-L68

Let me know if you need any help

**Comment by vsevel** [comment]
hello, do you think this is likely to be implemented at some point?

**Comment by radcortez** [comment]
Ideally if this could come from the community it would be faster :)

**Comment by vsevel** [comment]
thanks for this honest answer @radcortez  ;)
I have thought about it. I should have more time early next year.

**Comment by radcortez** [comment]
Great. Thanks. Feel free to reach out if you need help.

**Comment by michalvavrik** [comment]
Looks like interesting issue, I can have a look provided @vsevel is fine with that.

**Comment by michalvavrik** [comment]
Thank you.
