### ISSUE TITLE
quarkus:dev not working with 2.8.2.Final

### ISSUE THREAD

**Issue by SvenMarien** [quarkusio/quarkus#25255]
### Describe the bug

After upgrading quarkus to version 2.8.2.Final I get the following exception when starting mvn quarkus:dev

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.8.2.Final:dev
Caused by: java.lang.NullPointerException
at io.quarkus.maven.DevMojo.addProject (DevMojo.java:741)
at io.quarkus.maven.DevMojo.newLauncher (DevMojo.java:1028)
at io.quarkus.maven.DevMojo$DevModeRunner. (DevMojo.java:858)

Looking at the code of DevMojo it is due to this variable being null and called upon on line 741:
final ArtifactSources sources = module.getSources();

Is this due to one of my maven modules not having sources or resources? Bit stuck here...

### Expected behavior

The development mode should start without any exceptions.

### Actual behavior

NullPointerException at io.quarkus.maven.DevMojo.addProject (DevMojo.java:741)

### How to Reproduce?

Reproducer:
[subpersub.zip](https://github.com/quarkusio/quarkus/files/8590776/subpersub.zip)

Steps to reproduce:
1. mvn clean install
2. cd subpersub-api
3. mvn quarkus:dev -e

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 LTS OpenJDK Runtime Environment Microsoft-31205 (build 11.0.14.1+1-LTS) OpenJDK 64-Bit Server VM Microsoft-31205 (build 11.0.14.1+1-LTS, mixed mode)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\devenv\java\apache-maven-3.8.2 Java version: 11.0.14.1, vendor: Microsoft, runtime: C:\devenv\java\jdk-11.0.14.1+1 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by herasimau** [comment]
Having the same issue, in my case, removing this plugin from `pom` will permit to start quarkus without NullPointer:

```
<plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>some-id</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <classifier>some-classifier</classifier>
              <includes>
                <include>**/service/**</include>
              </includes>
            </configuration>
          </execution>
        </executions>
 </plugin>
```
