### ISSUE TITLE
RESTEasy reactive passed null media type for MessageBodyWriters

### ISSUE THREAD

**Issue by sithmein** [quarkusio/quarkus#25263]
### Describe the bug

Consider the following JAX-RS resource class and `MessageBodyWriter`:

```java
@Produces(MediaType.APPLICATION_JSON)
@Path("/")
public class MediaTypeLost {
	@Provider
	@Produces(MediaType.APPLICATION_JSON)
	public static class GenericJSONSerializer implements MessageBodyWriter<Object> {
	    @Override
	    public long getSize(final Object value, final Class<?> type, final Type genericType,
	        final Annotation [] annotations, final MediaType mediaType) {
	        return -1;
	    }

	    @Override
	    public boolean isWriteable(final Class<?> type, final Type genericType, final Annotation [] annotations,
	        final MediaType mediaType) {
	        return true;
	    }

	    @Override
	    public void writeTo(final Object value, final Class<?> type, final Type genericType,
	        final Annotation[] annotations, final MediaType mediaType,
	        final MultivaluedMap<String, Object> httpHeaders, final OutputStream entityStream)
	        throws IOException {
	        
	    	Objects.requireNonNull(mediaType);
	    }
	}

	
    @GET
    @Path("foo")
	public Response doSomething() {
    	var map = Map.of("key", "value");
	    return Response.ok(map).build();
	}
}
```
Invoking the resource method with _quarkus-resteasy-reactive_ will result in an exception because the `mediaType` parameter passed into the message body writer is `null`. This works without problems in the non-reactive version and any other JAX-RS framework that I have used in the past.
It works if the Response explicitly defines its media type it works, but according to section 3.8 of the JAX-RS specification this is not necessary and the media type can be derived from `@Produces` annotations.

### Expected behavior

The message body writer should receive the correct media type (_application/json_ in this case), according to the JAX-RS specification.

### Actual behavior

The media type is `null`.

### How to Reproduce?

Run the provided example with reactive RESTEasy.

### Output of `java -version`

17

### Quarkus version or git rev

2.8.2.Final

**Comment by geoand** [comment]
Thanks for reporting.

Do you mind attaching a sample project that exhibits this behavior?

**Comment by sithmein** [comment]
You can find reproducers/tests for this issue at https://github.com/sithmein/bugs-in-quarkus

**Comment by geoand** [comment]
I'm surprised that none of the TCK tests actually tested this...

In any case, https://github.com/quarkusio/quarkus/pull/25291 fixes the null media type issue.
