### ISSUE TITLE
Quarkus gRPC generator tries to write the same file twice 

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#25275]
### Describe the bug

Trying to generate service/message definition from https://github.com/envoyproxy/java-control-plane/tree/main/api produces "Tried to write the same file twice" errors.

### Expected behavior

Should compile

### Actual behavior

Error 

```
[INFO] --- quarkus-maven-plugin:2.8.2.Final:generate-code (default) @ grpc ---
udpa/type/v1/typed_struct.proto:14:1: warning: Import validate/validate.proto is unused.
udpa/service/orca/v1/orca.proto:18:1: warning: Import validate/validate.proto is unused.
xds/type/v3/typed_struct.proto:10:1: warning: Import validate/validate.proto is unused.
xds/service/orca/v3/orca.proto:14:1: warning: Import validate/validate.proto is unused.
io/envoyproxy/envoy/service/accesslog/v3/AccessLogService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/accesslog/v2/AccessLogService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v3/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v2/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/auth/v2alpha/Authorization.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v3/AggregatedDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/RuntimeDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/SecretDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/AggregatedDiscoveryService.java: Tried to write the same file twice.
io/envoyproxy/envoy/service/discovery/v2/HealthDiscoveryService.java: Tried to write the same file twice.
....
```

### How to Reproduce?

copy/pasting the proto folder from the given repo or using dependency :

```
quarkus.generate-code.grpc.scan-for-proto=io.envoyproxy.controlplane:api
```

```
<dependency>
      <groupId>io.envoyproxy.controlplane</groupId>
      <artifactId>api</artifactId>
      <version>0.1.31</version>
</dependency>
```

### Quarkus version or git rev

2.8.2

### Additional information

Removing `--q-grpc_out=/grpc/target/generated-sources/grpc` from the generated command line works.

**Comment by scrocquesel** [comment]
Find out that it fails when the proto file contains 

```
option java_generic_services = true;
```

I guess it is because the mutiny generator is producing its own implementation and it collides. I don't know if it can be disable from command line but this is an issue for me as I don't have ownership of those proto files and can be an issue when generating from jar file.

**Comment by michalszynkiewicz** [comment]
Did you try maven or gradle plugin as a workaround?

**Comment by scrocquesel** [comment]
maven plugin alone works but all I got is the `com.google.protobuf.Service` implementation of service and not the Mutiny one.

**Comment by scrocquesel** [comment]
Works if the MutinyGrpcGenerator is run in a second step alone.
Another solution would be to able to preprocess all .proto file to remove or comment line containing `java_generic_services`.

**Comment by cescoffier** [comment]
I need to check what `java_generic_services` is actually doing.

**Comment by scrocquesel** [comment]
@cescoffier it generates a Greeter.java file with an abstract service class. It has been deprecated since plug-ins has been introduced and should not be used anymore.
The mutiny plugin does exactly what it should by providing a custom implementation of the same name.
When using plugin to generate service, developer should remove the generic service but it's not possible when you dont have control on proto files, especially when importing them from a package dependency. Maybe only those imported proto files should be preprocessed.

**Comment by cescoffier** [comment]
Thanks @scrocquesel. 
Yes, we may need to pre-process the files when we handle the mutiny generation. 

@alesj WDYT?

**Comment by alesj** [comment]
@cescoffier pre-process them how? Or about which files are we talking exactly?

**Comment by scrocquesel** [comment]
> @cescoffier pre-process them how? Or about which files are we talking exactly?

Actually, files that are added to src/proto can be modified by the developer maybe we can intercept the output and provide a meaningful message if it happens.
Files that are fetch from a package dependency should be modified first.

Let me know what could be the best solution and I'll try to implement it.

**Comment by scrocquesel** [comment]
@alesj Have a look to the draft PR. It work in my case but there is a branch in the `extractProtosFromArtifact` I don't know when it goes through. Is it for import only ?

https://github.com/quarkusio/quarkus/blob/647dfdc13ffc76a65f2980a120ec0878cf07bfd6/extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java#L233

Also, intercepting the output would add boilerplate complexity. Maybe just add a note in the documentation would be enough as it should not be common nowadays.
