### ISSUE TITLE
RESTEasy reactive onFailure() ignored.

### ISSUE THREAD

**Issue by joseph-nun3z** [quarkusio/quarkus#25272]
### Describe the bug

Having a quarkus quickstart project (resteasy-reactive) I try to failure handling by doing the following:

``` Java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> hello() throws CustomException {
        return Uni.createFrom().item(fail()).onFailure().invoke(failure -> Log.info(failure.getMessage())); //log not invoked
    }

    private String fail() throws CustomException {
        throw new CustomException("hello");
    }
```

onFailure is ignored.

### Expected behavior

Log message

### Actual behavior

No message is logged.

### How to Reproduce?

[Reproducer](https://github.com/joseph-nun3z/quarkus-resteasy-reactive-bug)

### Output of `uname -a` or `ver`

Linux pop-os 5.16.19-76051619-generic

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 LTS OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS) OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 11.0.14, vendor: Azul Systems, Inc., runtime: /home/janunez/.sdkman/candidates/java/11.0.14-zulu Default locale: en_GB, platform encoding: UTF-8 OS name: "linux", version: "5.16.19-76051619-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Where does `Log.info` come from?

Do you observe the same behavior if you use `System.out`?

**Comment by joseph-nun3z** [comment]
> Where does Log.info come from?

It comes from `io.quarkus.logging.Log`

> Do you observe the same behavior if you use System.out?

Yes, same behaviour. It basically fails to handle the failure.

**Comment by cescoffier** [comment]
Your fail method is called synchronously, and thus fail the uni creation (assembly time).

Use: Uni.createFrom().item(() -> fail())


By passing a function, you will fail at subscription time (this on failure will be called).

**Comment by stuartwdouglas** [comment]
@cescoffier Shouldn't it still call the onFailure if we have an already failed Uni? Otherwise I am pretty sure we have some problematic code within Quarkus itself.

e.g. for this code: https://github.com/stuartwdouglas/quarkus/blob/5bb430775f2ed42172224f93ebdf43dd32019671/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java#L113

Does this mean that if the authenticator returns a failed uni that the subscription won't be processed and the request will hang?

**Comment by cescoffier** [comment]
That's the same as:

```java
Uni<Double> uni = Uni.createFrom(1000/0)
   .onFailure().recoverWith(0.0);
```

This snippet won't work as the arithmetic exception is synchronous and the uni cannot be created. 
You will need something like:

```java
Uni<Double> uni;
try {
   uni = Uni.createFrom(1000/0)
      .onFailure().recoverWith(0.0);
} catch(Exception e) {
  uni = ...
}
```

In the Quarkus case, you get a Uni, so the onFailure is called.
