### ISSUE TITLE
cookie parsing bug

### ISSUE THREAD

**Issue by lost4git** [quarkusio/quarkus#25277]
### Describe the bug

Because there is no `if branch` to match `SameSite`(or others) and **the cookie name (or value) is allowed to be overridden**, the cookie name (or value) is incorrectly set to `SameSite`(or others)

```
auth_key=123456; SameSite=None
 --> parsing to -->
cookie.name=SameSite, cookie.value=None 
```

@see https://github.dev/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/headers/NewCookieHeaderDelegate.java#L21

![Web capture_30-4-2022_94152_developer mozilla org](https://user-images.githubusercontent.com/65008815/166085818-5a12183d-0349-4776-ac5a-25c193216657.jpeg)

### Expected behavior

```
auth_key=123456; SameSite=None
 --> parsing to -->
cookie.name=auth_key, cookie.value=123456
```

### Actual behavior

```
auth_key=123456; SameSite=None
 --> parsing to -->
cookie.name=SameSite, cookie.value=None 
```

### Quarkus version or git rev

2.8.2.Final

**Comment by ejba** [comment]
Wouldn't it be better to use java.net.HttpCookie to parse the string?
