### ISSUE TITLE
Gradle build fails as the snakeyaml-android dependency referred in Quarkus do not exist

### ISSUE THREAD

**Issue by mrin9** [quarkusio/quarkus#25287]
### Describe the bug

Gradle is unable to locate the following dependency referred in Quarkus  
` https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.30/snakeyaml-1.30-android.jar`

`org.yaml:snakeyaml:1.30` do exist in  MavenCentral but Gradle's dependency resolution also includes the android classifier that creates dependency on `org.yaml:snakeyaml:1.30-android` - which doesn't exist

I think it can be fixed if you remove `<classifier>android</classifier>` from the snakeyaml dependency.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by glefloch** [comment]
Thanks for reporting this. Do you have a sample project? Or are you just trying to add a dependency on snakeyaml with the android classifier?

**Comment by mrin9** [comment]
I started getting this error after I upgraded Quarkus to `2.7.0` in this release `snakeyaml` was [upgraded from `1.29` to `1.30`](https://github.com/quarkusio/quarkus/pull/22353) which made me believe that it is stemming from the upgrade as all the prior releases of Quarkus works fine 

However, I found that there was another issue report on this #23371
but the cause was due to a different library `JavaFaker` a reproducing Repo  https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/tree/main/software/plugins/open-qm-plugin-demo is provided too.

It has fixed my issue too. 
Sorry for the false alarm, closing it
