### ISSUE TITLE
Combining @RouterFilter and JAX-RS ContainerResponseFilter does not work in reactive RESTEasy

### ISSUE THREAD

**Issue by sithmein** [quarkusio/quarkus#25283]
### Describe the bug

Consider the following code running with _quarkus-resteasy-reactive_:

```java
@Produces(MediaType.TEXT_PLAIN)
@Path("/")
public class IncompleteVaryHeader {
    public static class VaryOriginFilter {
        @RouteFilter
        void checkForCSRF(final RoutingContext rc) {
            rc.response().headers().add("Vary", "Origin");
            rc.next();
        }
    }
    
    @Provider
    public static class NoCacheControlFilter implements ContainerResponseFilter {
        @Override
        public void filter(final ContainerRequestContext requestContext, final ContainerResponseContext responseContext)
            throws IOException {
            responseContext.getHeaders().add(HttpHeaders.VARY, "Prefer");
        }
    }

    @GET
    @Path("incomplete-vary-header")
    public Response doSometing() {
        return Response.ok("Test").type(MediaType.TEXT_PLAIN).build();
    }
}
```
There are two filter, a `@RouteFilter` and a JAX-RS `ContainerResponseFilter` which both add a `Vary` header. In classic RESTEasy both values - _Origin_ and _Prefer_ are in the response headers. In reactive RESTEasy the _Origin_ value is missing. The same code works as expected with classic RESTEasy.

### Expected behavior

The `Vary` response header should contain both _Origin_ and _Prefer_.

### Actual behavior

Only _Prefer_ is returned.

### How to Reproduce?

Run `VaryHeaderTest` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `java -version`

17

### Quarkus version or git rev

2.8.2.Final

**Comment by gastaldi** [comment]
Use `request.getHeaders().set` instead of `add`
