### ISSUE TITLE
Missing default java.security.Principal producer for SecurityContext

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#2528]
**Describe the bug**
Trying to inject a java.security.Principal fails with a UnsatisfiedResolutionException

**Expected behavior**
One should expect that there is a default java.security.Principal that maps to the JAX-RS SecurityContext#getUserPrincipal()

**Actual behavior**
A failure with:
```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.security.Principal and qualifiers [@Default]
	- java member: io.quarkus.security.test.SubjectExposingResource#principal
	- declared on CLASS bean [types=[java.lang.Object, io.quarkus.security.test.SubjectExposingResource], qualifiers=[@Default, @Any], target=io.quarkus.security.test.SubjectExposingResource]
	at io.quarkus.builder.Execution.run(Execution.java:124)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:137)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:108)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:102)
	... 36 more
```

**To Reproduce**
1. Add a Principal injection to io.quarkus.security.test.SubjectExposingResource of the extensions/elytron-security/deployment/src/test/java/io/quarkus/security/test/SubjectExposingResource.java endpoint
2. Run the extensions/elytron-security/deployment/src/test/java/io/quarkus/security/test/BasicAuthTestCase.java test

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  N/A
 - Output of `java -version`:  N/A
 - GraalVM version (if different from Java): 1.8.202
 - Quarkus version or git rev: current master

**Comment by machi1990** [comment]
Looks like it was fixed by https://github.com/quarkusio/quarkus/pull/2641. Closing.
