### ISSUE TITLE
Serverless apps fails to start when deployed via quarkus-openshift extension

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#25296]
### Describe the bug

When Quarkus 2.7.5 application is deployed on OCP cluster via quarkus-openshift it fails to start, and have this error in the log: "the object has been modified; please apply your changes to the latest version and try again"

### Expected behavior

Application should not fail in this scenario and start successfully. Applications built with 2.2.5.Final version don't have these problems.

### Actual behavior

Application is not deployed and has these warnings in the log:

```
13:51:45,725 INFO  oc: 35s         Warning   InternalError           revision/app-00001                           failed to update deployment "app-00001-deployment": Operation cannot be fulfilled on deployments.apps "app-00001-deployment": the object has been modified; please apply your changes to the latest version and try again
<...>
13:51:45,726 INFO  oc: 82s         Normal    Created                 pod/app-1-build                              Created container git-clone

13:51:45,728 INFO  oc: 38s         Normal    BuildCompleted          build/app-1                                  Build ts-yvguifanbg/app-1 completed successfully
13:51:45,728 INFO  oc: 36s         Normal    Created                 service/app                                  Created Configuration "app"
13:51:45,728 INFO  oc: 36s         Normal    Created                 service/app                                  Created Route "app"
13:51:45,728 INFO  oc: 36s         Normal    Created                 configuration/app                            Created Revision "app-00001"
13:51:45,729 INFO  oc: 36s         Normal    FinalizerUpdate         route/app                                    Updated "app" finalizers
13:51:45,729 INFO  oc: 29s         Normal    ConfigurationReady      configuration/app                            Configuration becomes ready
13:51:45,729 INFO  oc: 29s         Normal    LatestReadyUpdate       configuration/app                            LatestReadyRevisionName updated to "app-00001"
13:51:45,729 INFO  oc: 29s         Normal    Created                 route/app                                    Created placeholder service "app"
13:51:45,729 INFO  oc: 29s         Normal    Created                 route/app                                    Created Ingress "app"
13:51:45,729 INFO  oc: 29s         Warning   FinalizerUpdateFailed   ingress/app                                  Failed to update finalizers for "app": Operation cannot be fulfilled on ingresses.networking.internal.knative.dev "app": the object has been modified; please apply your changes to the latest version and try again
13:51:45,730 INFO  oc: 29s         Normal    FinalizerUpdate         ingress/app                                  Updated "app" finalizers
```

### How to Reproduce?

1. Clone the reproducer: `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`. I can reproduce the issue on git hash `745cf18ae398c9bd55a144637a2f49d2c4b98292`
2. Enter the reproducer folder ` cd quarkus-test-suite/http/http-minimum`
3. Log in openshift cluster through `oc` command
4. Run tests: 
```
mvn clean verify \
-Dts.openshift.ephemeral.namespaces.enabled=true \
-Dquarkus.platform.version=2.7.5.Final -Dquarkus-plugin.version=2.7.5.Final -Dts.global.version-number=2.7.5.Final \
-Dquarkus.platform.artifact-id=quarkus-bom \
-Dopenshift -Dall-modules -Dinclude.operator-scenarios -Dinclude.serverless \
 -Dts.global.service-name=rhbq-2.7-rhel8-jdk11-openshift-ts-jvm-ocp-4-stable # the name can be any
```
5. Verify that the same tests works with 2.2:
```
git checkout 2.2
mvn clean verify \
-Dts.openshift.ephemeral.namespaces.enabled=true \
-Dquarkus.platform.version=2.2.5.Final -Dquarkus-plugin.version=2.2.5.Final -Dts.global.version-number=2.2.5.Final \
-Dquarkus.platform.artifact-id=quarkus-bom \
-Dopenshift -Dall-modules -Dinclude.operator-scenarios -Dinclude.serverless \
 -Dts.global.service-name=any-name
```

### Output of `uname -a` or `ver`

5.16.20-200.fc35.x86_64

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information
```
$ oc version
oc v3.11.420
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server <...>
kubernetes v1.23.5+9ce5071
```

**Comment by geoand** [comment]
Any chance we can get any more information?

**Comment by fedinskiy** [comment]
@geoand sorry, it looks like my browser have glitched during the issue creation :)

I added versions of Quarkus, OCP, Maven and Linux. Is there anything else I can help with?

**Comment by geoand** [comment]
Are there any more log entries from OCP?

**Comment by fedinskiy** [comment]
@geoand, I put the whole log for a single test in a separate gist([REDACTED] parts are internal IPs/URLs):
https://gist.github.com/fedinskiy/82b803b52877ec7a2fd60639759776dd

@iocanel there is always a new namespace with randomly assigned name. For the clean experiment, I run a single test and it failed with the same error.

**Comment by geoand** [comment]
> @geoand, I put the whole log for a single test in a separate gist([REDACTED] parts are internal IPs/URLs):
https://gist.github.com/fedinskiy/82b803b52877ec7a2fd60639759776dd

Thanks

**Comment by rsvoboda** [comment]
@iocanel / @geoand any update on the possible cause of the failure?

**Comment by geoand** [comment]
I have no idea, I've never worked with serverless

**Comment by iocanel** [comment]
@rsvoboda: trying to reproduce... Will post updates.

**Comment by iocanel** [comment]
I managed to deploy the project successfully both in `main` and `2.2`. 

Using the `main` I do see that `ServerlessExtensionOpenShiftHttpMinimumIT` fails. However, its not clear to me why, as there is an exception internal to the testing framework.

As far as deployment is concerned, even the failed tests succesfully deploys the `Service`. 

@Sgitario: can you have a look?

**Comment by Sgitario** [comment]
The issue is in the testing framework. To be precise, here: https://github.com/quarkus-qe/quarkus-test-framework/blob/623e3e860ad4b6ff22bc88f08e41aab711db8370/quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java#L261

When we deploy a serverless application, there is no deployment config and also, we don't need to scale apps up or down. 

To fix the issue in the framework, the `scaleToWhenDcReady` method needs to add this condition: https://github.com/quarkus-qe/quarkus-test-framework/blob/623e3e860ad4b6ff22bc88f08e41aab711db8370/quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java#L250

Therefore, this issue should be closed and properly fixed it in the testing framework repo.
