### ISSUE TITLE
Jackson deserialisation Timestamp in native mode

### ISSUE THREAD

**Issue by anthonydenecheau** [quarkusio/quarkus#25305]
### Describe the bug

Hi,

Under pub/sub for which I am trying to deserialize a message into an Event class which contains a Timestamp.

```
protected void loggerSink(Event<MyDomainClass> event) {
     logger.debug("Received a message of type " + event.getType());
      ObjectMapper mapper = new ObjectMapper();
      List<MyDomainClass>datas = mapper.convertValue(event.getMessage(), new TypeReference<List<MyDomainClass>>() {
      });
}
```
```
@Cacheable
@Entity(name = "ws_xxxx")
public class MyDomainClass extends PanacheEntityBase {
   @Column(name = "updating_date")
   public Timestamp timestamp;
}
```

It's working within PubSub Emulator But one deploy on CloudRun this exception appears:

`WARNING [co.go.cl.pu.v1.MessageDispatcher] (Gax-2) MessageReceiver failed to process ack ID: BCEhPjA-RVNEUAYWLF1GSFE3GQhoUQ5PXiM_NSAoRRABIGwLNEJcdA1oXFx1BlkNEXd4YnBrWkALAk9TVm9D2tHn_2pXJ1UJEXd8Y3BpXBoIA0RWf1tzrpauiPmbzGYXIkq8vfrJbDOu49pgZho9WxJLLD5-PTFFQV5AEkw2BERJUytDCypYEU4, the message will be nacked.: java.lang.IllegalStateException: Failed to find class `com.fasterxml.jackson.databind.deser.std.DateDeserializers$TimestampDeserializer` for handling values of type `java.sql.Timestamp`, problem: (java.lang.ClassNotFoundException) **com.fasterxml.jackson.databind.deser.std.DateDeserializers$TimestampDeserializer**`

I see an anwser using **@RegisterForReflection**. But I don't know which class i have to set.

Best regards

**Comment by gsmet** [comment]
A workaround for now is to add `@RegisterForReflection(targets = TimestampDeserializer.class)` to any of your application classes.

**Comment by anthonydenecheau** [comment]
Thanks a lot Guillaume ! :)

**Comment by gsmet** [comment]
I still think we need to do something about it.

**Comment by geoand** [comment]
> I still think we need to do something about it.

Should be a fairly easy fix

**Comment by gsmet** [comment]
Yeah, this one, yes. What I'm wondering is given the few we register, I'm pretty sure we have others that are missing. Some are using static instances so they are created at static init. But all the ones that don't should probably be registered for reflection.

Does it make sense?

**Comment by geoand** [comment]
> But all the ones that don't should probably be registered for reflection

Sure, but do we know which ones? Are you suggesting registering all subclasses of `com.fasterxml.jackson.databind.JsonDeserializer`?

**Comment by gsmet** [comment]
Well that won't work because the Jackson classes are not in Jandex. So if we want to include the serializers, we either need to index it (which might be slow and will be done when compiling any apps) or we will have to list them all manually.

@geoand don't you think we need to add them? TBH I was surprised we didn't do it and really puzzled by us not having more reports about this.

**Comment by geoand** [comment]
Given how prevalent Jackson is among our users, I think that if we really need to include them all, we would have known already :).

So I think we can just add the ones we know we need

**Comment by ejba** [comment]
@gsmet Can I add this one manually?
