### ISSUE TITLE
Multipart support broken in reactive RESTEasy

### ISSUE THREAD

**Issue by sithmein** [quarkusio/quarkus#25312]
### Describe the bug

The following code works fine with classic RESTEasy when making a `multipart/form-data` request:

```
...
import org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataInput;

@Path("/")
@Produces(MediaType.TEXT_PLAIN)
public class MultipartBroken {
    @POST
    @Path("multipart-broken")
    @Consumes(MediaType.APPLICATION_JSON)
	public Response consumeJson() {
	    return Response.ok("Works").build();
	}

    @POST
    @Path("multipart-broken")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
	public Response consumeMultipart(final MultipartFormDataInput input) {
	    return Response.ok("Works").build();
	}
}
```

It fails with 415 (Unsupported media type) when using reactive RESTEasy.

### Expected behavior

A `multipart/form-data` request should be possible.

### Actual behavior

The request fails with _Unsuported Media Type_.

### How to Reproduce?

Run the testcase `quarkus.bugs.MultipartBrokenTest` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `java -version`

17

### Quarkus version or git rev

2.8.2.Final

**Comment by geoand** [comment]
The multipart support is not broken, it just uses a different API.
See https://quarkus.io/guides/resteasy-reactive-migration#multipart-support for more details

**Comment by sithmein** [comment]
I read the documentation but this does not apply to our use case. As you can see from the example code I provided we want to process arbitrary multipart/form-data requests, i.e. we don't know in advance how many parts there will be any how they are called. The documentation explains only how to handle data where the number and names of the parts are know in advance.
Also they way my example handles form data is basic JAX-RS functionality. The last method argument is an object of a certain type and there is a `MessageBodyReader` for this type. This should work in any JAX-RS implementation, there is nothing specific to RESTEasy in that example.
Can you tell me how to make my example work in reactive RESTEasy?

**Comment by geoand** [comment]
>  i.e. we don't know in advance how many parts there will be any how they are called

So this is a new feature request

> The last method argument is an object of a certain type and there is a MessageBodyReader for this type. This should work in any JAX-RS implementation, there is nothing specific to RESTEasy in that example

It's not clear to me what you are referring to here. Care to elaborate further?

**Comment by sithmein** [comment]
My example uses an _entity parameter_ according to section 3.3.2.1 of the JAX-RS specification. For this entity parameter of type `org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataInput there is a registered provider, the `MessageBodyReader` `org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataReader`. Then the spec-compliant JAX-RS behaviour should be that this message body reader is used to read the request body and turn it into an object of type `MultipartFormDataInput`. This works in classic RESTEasy but not in reactive RESTEasy.

**Comment by geoand** [comment]
This happens because `MultipartFormDataReader` is never registered as a provider.

If you add:

```
quarkus.index-dependency.resteasy-multipart.group-id=org.jboss.resteasy
quarkus.index-dependency.resteasy-multipart.artifact-id=resteasy-multipart-provider
```

as explained in https://quarkus.io/guides/cdi-reference#bean_discovery, then your test passes

**Comment by sithmein** [comment]
Jep, this works. Maybe worth adding to the reactive migration guide that there are differences in how providers are discovered (the link to the guide on https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8 is broken, btw.).

**Comment by geoand** [comment]
> (the link to the guide on https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8 is broken, btw.)

Thanks for spotting, fixed now.

> Maybe worth adding to the reactive migration guide that there are differences in how providers are discovered

I'll add something
