### ISSUE TITLE
GRPC method with streaming input and streaming output has wrong parameter order for blocking code generation

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#25318]
### Describe the bug

When generating the code for the following proto file

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.acme";
option java_outer_classname = "HelloGrpcProto";

package hello;

service HelloGrpc {
    rpc SayHello (stream HelloRequest) returns (stream HelloReply) {}
}

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string message = 1;
}
```

the generated class `HelloGrpcGrpc.HelloGrpcImplBase` contains the following method definition

```
public static abstract class HelloGrpcImplBase implements io.grpc.BindableService {

    /**
     */
    public io.grpc.stub.StreamObserver<org.acme.HelloRequest> sayHello(
        io.grpc.stub.StreamObserver<org.acme.HelloReply> responseObserver) {
      return io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall(getSayHelloMethod(), responseObserver);
    }

...
```

This method receives a `StreamObserver` of the type of the reply (`HelloReply`) as an argument and returns a `StreamObserver` of the type of the request (`HelloRequest`). 

It looks to me as if the argument should be the `HelloRequest` and the response of the method should be of type `HelloReply`. Otherwise, it is unclear how we should use this method. 

### How to Reproduce?

1. Download the reproducer and unzip:
[2022-05-02_grpc-streaming-method-generation.zip](https://github.com/quarkusio/quarkus/files/8606247/2022-05-02_grpc-streaming-method-generation.zip)
2. generate the GRPC classes by running `./mvnw package`
3.  check the code of  `HelloGrpcGrpc.HelloGrpcImplBase`

### Quarkus version or git rev

2.7.2, 2.8.2, 2.9.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

tested mvn and gradle

**Comment by cescoffier** [comment]
No, it looks correct. That's the "bare" gRPC API. I agree, it's not the easiest to use. 
See https://www.baeldung.com/java-grpc-streaming#3-bidirectional-streaming as an example.

**Comment by andreas-eberle** [comment]
Hi @cescoffier , 
sorry, I didn't realize that. Thanks for the info and the link! Sorry to have bothered you.
Best regards!

**Comment by wfrank2509** [comment]
Thanks for the clarification. The API design of gRPC is really not that intuitive :)
