### ISSUE TITLE
Warning message about com.sun.xml.bind:jaxb-osgi:jar:2.2.10 when executing:  mvnw compile quarkus:dev:

### ISSUE THREAD

**Issue by haducloc** [quarkusio/quarkus#2532]
[WARNING] The POM for com.sun.xml.bind:jaxb-osgi:jar:2.2.10 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

**Comment by Dufgui** [comment]
Hello,
could you provide your pom please ? Is it a multi module project?

**Comment by haducloc** [comment]
I was following a tutorial and found that bug. I tried to follow hello tutorial from Quarkus website, no warning found. I closed the bug. Thanks!
