### ISSUE TITLE
Deleting a watched file in dev mode doesn't trigger a restart

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#25331]
### Describe the bug

When a build step registers a file to be watched and trigger a restart (using `HotDeploymentWatchedFileBuildItem`), deleting the file doesn't trigger a restart of the application, as it should.

Debugging shows that the call to `RuntimeUpdatesProcessor#checkForFileChange()` in `RuntimeUpdatesProcessor#doScan()` returns the empty set when a watched file is deleted.

### Expected behavior

A watched file registered to trigger a restart should trigger a restart when the file is deleted by the user.

### Actual behavior

The file deletion appears to go undetected and thus doesn't cause a restart. It may however cause other failures, since there is application state which expects the files to still exist. One such case is the Flyway extension, which will fail when triggering a _Migrate_ action from the Dev UI.

### How to Reproduce?

Steps to reproduce:
1. Create a new application
2. Make sure there is an `application.properties` file in it
3. Start the application in dev mode
4. Delete the `application.properties` file
5. Trigger some action in the Dev UI (which should trigger a restart when required)
6. Check if the application was actually restarted

### Quarkus version or git rev

2.9.0.CR1

**Comment by geoand** [comment]
cc @aloubyansky
