### ISSUE TITLE
WebSocketLogHandler catches InterruptedException without reinterrupting

### ISSUE THREAD

**Issue by wimgoeman** [quarkusio/quarkus#25359]
When trying to interrupt a Thread, as soon as the Thread hits a log statement, the WebSocketLogHandler catches the InterruptedException and ignores it. Normal behavior should be to reinterrupt the interrupted Thread by calling `Thread.currentThread().interrupt()`.

In my case, I need to use interrupt in order to terminate a manually created Thread. Due to this issue, the Thread never manages to terminate properly.

https://github.com/quarkusio/quarkus/blob/a152f8c0b4f068e19a31e5dac1b86980e4797322/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/logstream/WebSocketLogHandler.java#L70

**Comment by mkouba** [comment]
`WebSocketLogHandler` is no longer part of the runtime. 

I think that we can close this issue? CC @phillip-kruger

**Comment by phillip-kruger** [comment]
Yes !
