### ISSUE TITLE
Native build will java 17 project fail because using a java 11 image

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#25357]
### Describe the bug

Native build will java 17 project fail because using a java 11 image.

To workaround it: 
```
 quarkus build --native -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17
```

### Expected behavior

it should use `quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17` and build correctly.

### How to Reproduce?

Reproducer:
1. https://code.quarkus.io/?j=17
2. `quarkus build --native -Dquarkus.native.container-build=true`

It will fail because the image used is: [quay.io/quarkus/ubi-quarkus-native-image:22.0-java11](http://quay.io/quarkus/ubi-quarkus-native-image:22.0-java11)

**Comment by galderz** [comment]
This, if anything, is maybe about figuring the right default image to use depending source/target set? Or `java --version` in the path? @geoand @gsmet?

**Comment by geoand** [comment]
Yup, sounds totally reasonable. Lemme see if I can put something together real quick

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25410 addresses the issue
