### ISSUE TITLE
quarkus dev missing --offline/-o options

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#25362]
### Description

can't run quarkus dev in offline mode so it can/will fail in cases where no internet access despite build is possible using just local resources.

zulip conversation at https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/offline.20dev.20mode

quarkus build already have offline support thus this should  just be about enabling it to be passed through for dev.

**Comment by kanha-gupta** [comment]
Hi i am new to this & looking up to contribute

**Comment by maxandersen** [comment]
Heya. 

See https://github.com/quarkusio/quarkus/blob/498c3e189d5710f60d848376348e677d41562971/devtools/cli/src/main/java/io/quarkus/cli/Build.java#L24 which is the class that implements "quarkus build"; it has build options flags including offline. 

We need similar for the Dev.java class. 

Might even be able to include the other options but need to see what makes sense. We can discuss that in the pr.
