### ISSUE TITLE
@QueryParam with a non-native object not working as expected

### ISSUE THREAD

**Issue by D-MLink** [quarkusio/quarkus#25370]
### Describe the bug

i'm trying to port an API from Spring to Quarkus. 
I'm using Openapi generator for quarkus, and generate my classes from a yaml file.

If I define a GET endpoint with a @QueryParam that uses a object I defined (instead of a string or int). 
It's not properly parsed.

```java
    public class TestObj {
        public String a;
        public String b;
        public String c;
    }

    @GET
    public String getTest(@QueryParam("testObj") TestObj testObj){
        return null;
    }
```
Obviously if I only do this i get a error saying it can't find a converter provider. 
But even after i declare a converter, it is never used
This is because there's no "testObj" in the GET query:
http://localhost:8080/get?a=123&b=234&c=345

If I do the equivalent in spring, it grabs the values of 'a', 'b' and 'c' in to a new "TestObj" for use inside the method.

### Expected behavior

Requesting "http://localhost:8080/get?a=123&b=234&c=345" should return a new object "TestObj" with the variables properly filled, instead its looking for a "testObj" in the query string.

### Actual behavior

testObj is null

### Quarkus version or git rev

2.8.0-final

**Comment by geoand** [comment]
What does your `ParamConverter` look like?

**Comment by D-MLink** [comment]
> What does your `ParamConverter` look like?

```java
public class TestObjConverter implements ParamConverter<TestObj> {
    @Override
    public TestObj fromString(String s) {
        System.out.println("TestObjfromString");
        System.out.println(s);
        return new TestObj();
    }

    @Override
    public String toString(TestObj testObj) {
        return null;
    }
}
```
I have it returning just a new object. but from the prints i have, this method is only called if I do a GET request like this:
"http://localhost:8080/get?testObj=123"

If i do the proper request, that I have in swagger, "http://localhost:8080/get?a=123&b=234&c=345" , the method is never called.

**Comment by geoand** [comment]
Do you have a `ParamConverterProvider` that registers it?

**Comment by D-MLink** [comment]
> Do you have a `ParamConverterProvider` that registers it?
Yes

```java
@Provider
public class TestObjConverterProvider implements ParamConverterProvider {
    @Override
    public <T> ParamConverter<T> getConverter(Class<T> aClass, Type type, Annotation[] annotations) {
        if (aClass.equals(TestObj.class))
            return (ParamConverter<T>) new TestObjConverter();
        return null;
    }
}
```

**Comment by geoand** [comment]
Would you be able to attach a sample project that exhibits the problematic behavior?

From the looks of it, it should work

**Comment by D-MLink** [comment]
> Would you be able to attach a sample project that exhibits the problematic behavior?
> 
> From the looks of it, it should work
I made a repo with it
https://github.com/D-MLink/quarkus-issue

**Comment by Postremus** [comment]
@geoand @D-MLink 

AFAIK this does not work with jax rs like this.
The ParamConverter is not called, since jaxrs can not match any query paremeters on the method to the a, b, c parameters.

However, you can use a BeanParams. They are only slightly more complicated to use.
For this url
"http://localhost:8080/get?a=123&b=234&c=345"
you can use a beanparam.

```
public class TestObj {
        @QueryParam("a")
        public String a;

        @QueryParam("b")
        public String b;

        @QueryParam("c")
        public String c;
    }

    @GET
    public String getTest(@BeanParam TestObj testObj){
        return null;
    }
```

**Comment by geoand** [comment]
Looking at the reproducer now, @Postremus is totally correct.

**Comment by D-MLink** [comment]
Thank you @Postremus 
Can I define @BeanParam on the yaml I'm using with quarkus-openapi-generator?
Because the classes I am using are generated, and can't do manual changes to them.

**Comment by Postremus** [comment]
/cc @ricardozanini I saw you as the maintainer of quarkus-openapi-generator. Can you please take a look?
Can the extension automaticly generate BeanParams?

**Comment by ricardozanini** [comment]
Opened https://github.com/quarkiverse/quarkus-openapi-generator/issues/59 to track it.

**Comment by ricardozanini** [comment]
@D-MLink can you please attach to that issue the OpenAPI yaml file so we can reproduce the bug?
