### ISSUE TITLE
Add togglz extension

### ISSUE THREAD

**Issue by bennetelli** [quarkusio/quarkus#25389]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Additional context

Dear co-workers :) 

It's on my list since a while.. I would like to add a quarkiverse extension for "my" Open Source project called [togglz](https://github.com/togglz/togglz)

It's a Feature Flag / Feature Toggle library in Java and besides [Unleash](https://quarkiverse.github.io/quarkiverse-docs/quarkus-unleash/dev/index.html) which is an alternative library for Feature Flags (it's a bit different from an architectural approach) it would be good to have an alternative to it when using Quarkus.

**Comment by geoand** [comment]
Hi,

Thanks for reporting!

I think having this as a [Quarkiverse](https://quarkus.io/blog/quarkiverse/) extension would be great - cc @gastaldi

**Comment by gastaldi** [comment]
@bennetelli we noticed you haven't pushed anything to the repository, do you need any help?

**Comment by housepage** [comment]
Our organization might be interested in creating a Quarkus extension for Togglz. Where would I look for what is necessary to build a Quarkus extension around Togglz?
