### ISSUE TITLE
Panache delete query invalid

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#25391]
### Describe the bug

When I execute a delete query on PanacheEntity using
```
DataSet.delete("run.trashed = true");
```
where `DataSet` contains
```
   @ManyToOne(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
   @JoinColumn(name = "runid")
   public Run run;
```
I get an exception:
```
org.postgresql.util.PSQLException: ERROR: syntax error at or near "cross"
```
Based on `-Dquarkus.hiberate-orm.log.sql=true` the query executed against PostgreSQL is
```
    delete 
    from
        dataset cross 
    join
        run run1_ 
    where
        trashed=true
```

### Expected behavior

The proper SQL command should be
```
DELETE FROM dataset USING run WHERE dataset.runid = run.id AND run.trashed = true
```

### Actual behavior

Cross join in DELETE clause is syntactically incorrect, and an inner join should be executed rather than cross join.

### Quarkus version or git rev

2.8.2

**Comment by FroMage** [comment]
Do you know what the proper HQL would be?

**Comment by rvansa** [comment]
OK, looks like JOINs in DELETE are not legal in HQL. Googling for the query led me to https://hibernate.atlassian.net/browse/HHH-12625 - so this is not a Panache bug but Hibernate bug, rotting in JIRA for 4 years.
