### ISSUE TITLE
@Priority is not work for @Observes StartupEvent ev

### ISSUE THREAD

**Issue by kkk25641463** [quarkusio/quarkus#25409]
### Describe the bug

I create 30+ class like this:
```java
@ApplicationScoped
public class A {
    void onStart(@Observes @Priority(1) StartupEvent ev) {
         Log.Info("init A");
    }
}

@ApplicationScoped
public class B {
    void onStart(@Observes @Priority(1) StartupEvent ev) {
         Log.Info("init B");
    }
}

@ApplicationScoped
public class C {
    void onStart(@Observes @Priority(1) StartupEvent ev) {
       Log.Info("init C");
    }
}

@ApplicationScoped
public class ClassD {
    void onStart(@Observes @Priority(1) StartupEvent ev) {
        Log.info("start ClassD");
    }
}

.........

@ApplicationScoped
public class Z {
    void onStart(@Observes @Priority(100) StartupEvent ev) {
       Log.Info("init Z");
    }
}

```

### Expected behavior

I think class Z will last print.
init A
init B
init C
init D
....
init Z

### Actual behavior

But class Z maybe  print in the middle.
init A
init B
init Z
....
init D

### How to Reproduce?

1. create four class and run
```java
@ApplicationScoped
public class ClassA {
    void onStart(@Observes @Priority(Priorities.PLATFORM) StartupEvent ev) {
        Log.info("start ClassA");
    }
}

@ApplicationScoped
public class ClassB {
    void onStart(@Observes @Priority(Priorities.PLATFORM) StartupEvent ev) {
        Log.info("start ClassB");
    }
}
@ApplicationScoped
public class ClassC {
    void onStart(@Observes @Priority(Priorities.PLATFORM) StartupEvent ev) {
        Log.info("start ClassC");
    }
}

@ApplicationScoped
public class ClassD {
    void onStart(@Observes @Priority(Priorities.APPLICATION) StartupEvent ev) {
        Log.info("start ClassD");
    }
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.22000.652]

### Output of `java -version`

java 11.0.14 2022-01-18 LTS Java(TM) SE Runtime Environment GraalVM EE 22.0.0.2 (build 11.0.14+8-LTS-jvmci-22.0-b05) Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.0.0.2 (build 11.0.14+8-LTS-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

3.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by mkouba** [comment]
@kkk25641463 What's the value of `Priorities.PLATFORM`? Did you mean `javax.interceptor.Interceptor.Priority.PLATFORM_BEFORE` or `javax.interceptor.Interceptor.Priority.PLATFORM_AFTER`?

**Comment by kkk25641463** [comment]
Sorry. The value defined in io.smallrye.config

ublic final class Priorities {
    /**
     * Range for early interceptors defined by Platform specifications.
     */
    public static final int PLATFORM = 1000;

    /**
     * Range for interceptors defined by SmallRye Config or Extension Libraries.
     */
    public static final int LIBRARY = 3000;

    /**
     * Range for interceptors defined by User Applications.
     */
    public static final int APPLICATION = 5000;

    private Priorities() {
        throw new UnsupportedOperationException();
    }
}

**Comment by kkk25641463** [comment]
Thanks for your reply. Log.info is not thread safe.
