### ISSUE TITLE
@PathParam in Reactive REST Client encoding not the same as in classic REST Client

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#25418]
### Describe the bug

Usage of @PathParam with special characters don't work as in the classic world.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reactive.3A.20.40PathParam.20encoding.20not.20as.20in.20classic

### Expected behavior

It should be possible to put any value in a PathParam without hawing to do any encoding in the application code

### Actual behavior

Assigning a special character in PathParam fails

### How to Reproduce?

Run the provided test: MyTest.fails()

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.8.2.Final

### Additional information

[rest-client-reactive-quickstart8.zip](https://github.com/quarkusio/quarkus/files/8639987/rest-client-reactive-quickstart8.zip)

**Comment by gastaldi** [comment]
Wonder if https://github.com/quarkusio/quarkus/pull/25353 fixed this?

**Comment by geoand** [comment]
Ah, I thought this was about the server so I didn't check that at all...

Good point @gastaldi!

**Comment by geoand** [comment]
Closing this as it works with `2.8.3.Final` and `2.9.0.Final`

**Comment by lthasle** [comment]
@geoand Sound good, when will it 2.8.3.Final be released?

**Comment by geoand** [comment]
@lthasle https://quarkus.io/blog/quarkus-2-8-3-final-released/ 😉
