### ISSUE TITLE
Avro-Extension should support IDL

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#25416]
### Description

As mentioned [here](https://github.com/quarkusio/quarkus/issues/19350#issuecomment-1119351124), the quarkus-avro-extension currently does not support/process Avro [IDL](https://avro.apache.org/docs/current/idl.html#preamble) files like `sample.avdl`.

Since the IDL is much easier to write compared to JSON, it would be good to have the extension pickup avdl files as well and generate the classes from there.
Currently we have to fall back to the avro-maven-plugin in order to do so.

**Comment by glefloch** [comment]
@lostiniceland this is already the case, you can add a `sample.avdl` file in your `src/main/avro` and the code should be generated.

**Comment by lostiniceland** [comment]
@glefloch you are right: when executing `quarkus:build` the avdl is processed. My mistake was that I expected it to happen during Maven default compile goal.
