### ISSUE TITLE
ConfigSourceFactory not honoring profile if using profile specific files

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#25429]
### Describe the bug

I apologize in advance if this is raised on the wrong product. Not sure if it is a Quarkus issue, or a SR Config issue.

When using ConfigSourceFactory with profile specific properties file (ex. application-dev.properties). the `context.getValue()` call returns the wrong config, from the main file. If in the main file I have my property with the following format `%dev.my.config` then it takes the right one.

In the reproducer I am getting the config in a few manner
1-  ConfigMapping, value  is returned properly from the profile specific file
2- ConfigProvider, value is returned properly from the profile specific file
3- ConfigSourceFactory, wrong value is returned from the main properties file

### Expected behavior

If running a certain profile (dev in this example). The config should be taken from the right ConfigSource file.

### Actual behavior

if I have my value this way in application.properties
%dev.my.config, then the value is correctly taken into account

If I have my value in application-dev.properties.
my.config, the value is ignored in favor of the one in the main application.properties

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-configsourcefactory

Steps to reproduce

1-mvn quarkus:dev
2-observe the logs
3- uncomment the commented line in application.properties
4- rerun the app and observe the logs

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.4.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
This is indeed in SmallRye Config and not Quarkus.

Closing this one in favor of https://github.com/smallrye/smallrye-config/issues/752
