### ISSUE TITLE
Allow configuring how Stork-based REST clients are mapped to requests

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#25423]
### Description

Currently, a REST client can be configured to use Stork by using a base URL with the `stork` scheme. As a result the REST client will replace the URL scheme and hostname with whatever is returned by the `Stork.getInstance().getService()` call. For some use cases it may however be necessary to further "rewrite" the request. E.g.
* modify the URL path
* add a query parameter
* add a HTTP header

Some details regarding our use case: We use Azure API Management (an "API gateway"), which supports multiple versions for the registered APIs. To allow the API gateway to select the backend, the version needs to be included in the request. The version can be supplied as part of the URL path, a query parameter, or an HTTP header.

### Implementation ideas

Possibly a dedicated SPI could be provided, using which clients can construct or modify a `RequestOptions` object.

**Comment by michalszynkiewicz** [comment]
CC @aureamunoz @cescoffier @Sgitario

**Comment by cescoffier** [comment]
@aureamunoz @michalszynkiewicz discussed this issue.
The plan is to move the Stork management code into an HTTP request _filter_. Then, you can implement another filter (executed after the one from stork) to configure what you need.
