### ISSUE TITLE
Can not get restclient bean programmatically

### ISSUE THREAD

**Issue by lost4git** [quarkusio/quarkus#25439]
#### run result
![image](https://user-images.githubusercontent.com/65008815/167295282-156f5a77-0aed-4d45-81e2-ca5905324ffe.png)

#### MyClient.java
```java
@RegisterRestClient(baseUri = "https://www.google.com")
public interface MyClient {

  @GET
  @Path("")
  Response get();
}
```

#### ClientGetter.java
```java
@ApplicationScoped
@Blocking
public class ClientGetter {

  @Inject @RestClient MyClient myClient;

  void onStart(@Observes StartupEvent startupEvent) {
    getClientByProgrammatic();
  }

  void onStart2(@Observes StartupEvent startupEvent) {
    getClientByInject();
  }

  void getClientByProgrammatic() {
    try {
      final MyClient client = CDI.current().select(MyClient.class).get();
      System.out.println("#getClientByProgrammatic myClient = " + client);
    } catch (Exception e) {
      System.out.println("#getClientByProgrammatic err = " + e);
    }
  }

  void getClientByInject() {
    System.out.println("#getClientByInject myClient = " + myClient);
  }
}
```

#### application.properties
```properties
quarkus.arc.remove-unused-beans=false
```

### Expected behavior

Can get `MyClient` bean instance by programatically

### Actual behavior

Can not get `MyClient` bean instance by programatically, and throw exception: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type

### Quarkus version or git rev

2.8.2.Final

**Comment by geoand** [comment]
You need to use `CDI.current().select(ExtensionsService.class, RestClient.RestClientLiteral.LITERAL).get();`

**Comment by lost4git** [comment]
@geoand Thanks for your prompt answer. Can you provide a link to the relevant documentation for this?

**Comment by geoand** [comment]
We don't have any specific instance of this in the docs, but it's a standard CDI feature than beans that have a qualifer need to obtained using that qualifier.

**Comment by lost4git** [comment]
I understand, I may need to learn CDI more, thanks again
