### ISSUE TITLE
Kafka topic name with dot is failing

### ISSUE THREAD

**Issue by JohnyzHub** [quarkusio/quarkus#25437]
### Describe the bug

Kafka supports the topic names with dot symbol. 
eg: below are valid topic names:
employee.salary
public.customer.purchase
private.grocery.vegetables.sale
 
Quarkus is failing to handle such names. For example from the [kafka-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-quickstart) application, in the [processor](https://github.com/quarkusio/quarkus-quickstarts/blob/main/kafka-quickstart/processor/src/main/java/org/acme/kafka/processor), changing the outgoing topic name from 'quotes' to 'quotes.ch' will result in the failure with the below exception ::

`Failed to start application (with profile dev) java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration - the connector attribute must be set for channel quotes at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$0(ConnectorConfig.java:50) at java.base/java.util.Optional.orElseThrow(Optional.java:403) at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$1(ConnectorConfig.java:50) at java.base/java.util.Optional.orElseGet(Optional.java:364) at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.(ConnectorConfig.java:49) at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.lambda$extractConfigurationFor$0(ConfiguredChannelFactory.java:85) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.extractConfigurationFor(ConfiguredChannelFactory.java:74)`

Tried the below options, didn't work

1.  the property with single quote
mp.messaging.outgoing.'quotes.ch'.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

2. also with double quote
mp.messaging.outgoing."quotes.ch".value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

and with/without connector property mapping to kafka-connector 

### Expected behavior

Quarkus should be able to identify the topic names containing 'dot' separation. Quarkus should support the naming convention of topics and channels in line with kafka.

### Actual behavior

Failing with java.lang.IllegalArgumentException: SRMSG00071

### How to Reproduce?

1. Clone [kafka-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-quickstart) repository
2. Change the name of the topic in the [processor](https://github.com/quarkusio/quarkus-quickstarts/blob/main/kafka-quickstart/processor/src/main/java/org/acme/kafka/processor), from 'quotes' to 'quotes.ch' in all the occurrences
3. execute mvn -f processor quarkus:dev 

### Output of `java -version`

11+

### Quarkus version or git rev

2.8

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.5

**Comment by ejba** [comment]
Apparently the connector property is always duplicated where the second version doesn't have double quotes. When smallye reactive-messaging parses the second version of the property name, it only considers the first word until the first dot occurs, and then throws the mentioned exception afterwards (here)[https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/impl/ConfiguredChannelFactory.java#L81]

@geoand Does quarkus loads the configuration properties file, and later passes them to the MediatorConfiguration?

**Comment by ejba** [comment]
`WiringProcessor` generates `ConfigBuildItem`s without double quotes when the property name has dots. It turns incompatible with the Smallrye's configuration loading implementation. 

@geoand May I propose a fix in an MR?
