### ISSUE TITLE
Database rider does not work properly with Quarkus continuous test

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#25431]
### Describe the bug

I'm trying to use database rider with Continuous test, However when it's not working after the second run.

### Expected behavior

work properly, =D.

### How to Reproduce?

Steps:

git clone https://github.com/viniciusfcf/quarkus-issues
cd database-rider
mvn quarkus:dev (with docker running)
press 'r' (work)
press 'r' and re-run (fail)
See stack trace on console

### Output of `uname -a` or `ver`

Darwin vflorent-mac 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/vflorent/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/vflorent/.sdkman/candidates/java/11.0.11.hs-adpt Default locale: pt_BR, platform encoding: UTF-8 OS name: "mac os x", version: "11.3", arch: "x86_64", family: "mac"

### Additional information

1. After first time running:
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/14058396/167232099-f04f6634-aa78-484a-9cd7-4a4350f2fc52.png">

2. After press 'r' to re-run:
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/14058396/167232111-9ea68754-f653-49c7-9bd3-110b157757f6.png">

**Comment by gastaldi** [comment]
I think that's something in the Database Rider core, hopefully @rmpestano can help?

**Comment by geoand** [comment]
Can you try making making the problematic dependency parent-first using `quarkus.class-loading.parent-first-artifacts`?

**Comment by viniciusfcf** [comment]
like quarkus.class-loading.parent-first-artifacts=com.github.database-rider:rider-cdi?

It throws 

```
Caused by: java.lang.ClassNotFoundException: javax.persistence.EntityManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
```

**Comment by geoand** [comment]
So it depends on JPA, then indeed it won't work

**Comment by rmpestano** [comment]
Hey guys,

To help you I need to understand what's happening in quarkus-dev re-run. If needed we can provide a quarkus extension to handle such case, please let me know.

Cheers!

**Comment by geoand** [comment]
Quarkus Dev mode basically reloads the application in a new ClassLoader when a change is detected. 
https://quarkus.io/guides/class-loading-reference provides a few more details

**Comment by rmpestano** [comment]
I still need to check but I suspect that if you reload [this class](https://github.com/database-rider/database-rider/blob/7fe6ecdf4e9aff443bca2e1d83306d8ac8f29e36/rider-cdi/src/main/java/com/github/database/rider/cdi/JTAConnectionHolder.java) then the `init method` needs to be called again (maybe using postconstruct) to fill up the  connection cache: https://github.com/database-rider/database-rider/blob/7fe6ecdf4e9aff443bca2e1d83306d8ac8f29e36/rider-cdi/src/main/java/com/github/database/rider/cdi/JTAConnectionHolder.java#L30-L39


Another option would be disabling the cache of connections ([see here](https://github.com/database-rider/database-rider/blob/7fe6ecdf4e9aff443bca2e1d83306d8ac8f29e36/rider-examples/quarkus-postgres-sample/src/test/resources/dbunit.yml#L1)), have you tried that @viniciusfcf?

**Comment by rmpestano** [comment]
Really great that it worked! (and that you're going to update the example 😊 ) 

Cheers!
