### ISSUE TITLE
Generating project with Gradle ignores exclude clauses in dependencies

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#25454]
### Describe the bug

This report is a copy of what was originally created as SmallRye Context Propagation issue, see https://github.com/smallrye/smallrye-context-propagation/issues/363 for more details.

See steps to reproduce for details on how to create reproducer app.

The generated application includes `smallrye-context-propagation-jta` dependency which leads to the error in reproducer.
Executing `./gradlew dependencies` includes the following:
```
+--- io.quarkus:quarkus-hibernate-reactive-panache -> 2.8.3.Final
|    +--- io.quarkus:quarkus-hibernate-reactive:2.8.3.Final
|    |    +--- io.quarkus:quarkus-hibernate-orm:2.8.3.Final
|    |    |    +--- io.quarkus:quarkus-agroal:2.8.3.Final
|    |    |    |    +--- io.quarkus:quarkus-narayana-jta:2.8.3.Final
|    |    |    |    |    +--- io.smallrye:smallrye-context-propagation-jta:1.2.2
```

However, this shouldn't be the case as Hibernate Reactive excludes these, see [this pom file](https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-reactive/deployment/pom.xml#L28-L45).
At least `narayna-jta` and `agroal` should not be present.

### Expected behavior

Created app doesn't have dependencies that should be excluded.
As a side effect, this also means that the CDI lookup warning won't manifest.

### Actual behavior

Created app has dependency on Narayana JTA which brings in its module for context propagation.
As a side effect, this results in a CDI lookup warning in the log upon accessing the REST endpoint.

### How to Reproduce?

Taken from a [comment on original issue](https://github.com/smallrye/smallrye-context-propagation/issues/363#issuecomment-1119589050):

Using Quarkus CLI:

* `quarkus create app just.demo:purpose:1.0 --kotlin --gradle-kotlin-dsl --java=17`
* `quarkus ext rm quarkus-resteasy`
* `quarkus ext add quarkus-reactive-pg-client quarkus-resteasy-reactive quarkus-hibernate-reactive-panache quarkus-resteasy-reactive-jackson`

After that, change the `GreetingResource` to:
```
import io.smallrye.mutiny.Uni
import io.smallrye.mutiny.coroutines.awaitSuspending
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType

@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    suspend fun hello(): String? {
        val uni = Uni.createFrom().item { "Hellooo" }

        return uni.awaitSuspending()
    }
}
```

Start the app and go to `http://localhost:8080/hello`, there will be an error in the log.

**Comment by gsmet** [comment]
It's weird given we also have: https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-reactive/runtime/pom.xml#L16-L28 .

I wonder if it can be reproduced with Maven. If not, that would be a Gradle classpath issue. I remember we had some of those already.

**Comment by glefloch** [comment]
Yes, we already had this issue, dependency resolution differs between gradle and maven. 
From what I remember, in order to exclude an artifact, it should be excluded from all possible artifact it can come from. 

In this case, `quarkus-agroal` can come from `hibernate-reactive` (which exclude it), and deom `quarkus-hibernate-reactive-panache-common` which brings `quarkus-panache-hibernate-common` which brings `quarkus-hibernate-orm-panache`. 

You can use this command to explanation on dependency resolution: `./gradlew dependencyInsight --configuration compileClasspath --dependency io.quarkus:quarkus-agroal`

It will show where the dependency can come from:

````
io.quarkus:quarkus-agroal:2.8.3.Final
+--- io.quarkus:quarkus-hibernate-orm:2.8.3.Final
|    +--- io.quarkus.platform:quarkus-bom:2.8.3.Final
|    |    \--- compileClasspath
|    +--- io.quarkus:quarkus-hibernate-reactive:2.8.3.Final
|    |    +--- io.quarkus.platform:quarkus-bom:2.8.3.Final (*)
|    |    +--- io.quarkus:quarkus-hibernate-reactive-panache:2.8.3.Final
|    |    |    +--- compileClasspath (requested io.quarkus:quarkus-hibernate-reactive-panache)
|    |    |    \--- io.quarkus.platform:quarkus-bom:2.8.3.Final (*)
|    |    \--- io.quarkus:quarkus-hibernate-reactive-panache-common:2.8.3.Final
|    |         +--- io.quarkus.platform:quarkus-bom:2.8.3.Final (*)
|    |         \--- io.quarkus:quarkus-hibernate-reactive-panache:2.8.3.Final (*)
|    \--- io.quarkus:quarkus-panache-hibernate-common:2.8.3.Final
|         +--- io.quarkus.platform:quarkus-bom:2.8.3.Final (*)
|         \--- io.quarkus:quarkus-hibernate-reactive-panache-common:2.8.3.Final (*)
\--- io.quarkus.platform:quarkus-bom:2.8.3.Final (*)
````
However, it looks like this link has been removed by https://github.com/quarkusio/quarkus/commit/a8da122b1b12d872485c31328b92dae21702d13d 

I tested with `999-SNAPSHOT` and dependencies looks clean. @manovotn could you try it with `999-SNAPSHOT` version?

**Comment by manovotn** [comment]
@glefloch you are right, this is no longer an issue with 999-SNAPSHOT and shouldn't be an issue with 2.9.0.Final either.
Thanks for clarifying this!

@TiomanGally just an FYI ^^
