### ISSUE TITLE
maven list-outdated extension

### ISSUE THREAD

**Issue by Dufgui** [quarkusio/quarkus#2545]
**Description**
goal for maven to list outdated extension and remove the feature from current list-extensions

**Implementation ideas**
create the command. remove the code from current list-extension.
Test with and without bom. Check if current implementation works with maven repository in pom or not?

**Comment by Dufgui** [comment]
see #2463

**Comment by Dufgui** [comment]
please add maven component label and maybe good-first issue

**Comment by lamtrhieu** [comment]
Hi @Dufgui 
I would like to work on this one. Will try to read all related info and implements this. 
Hope that is fine. 
Thanks

**Comment by Dufgui** [comment]
Hi, no problem please do it ;o)
In fact, I already do "some good firt issues", so now I know quarkus better, I try to work on more complex issue.

**Comment by lamtrhieu** [comment]
Hi @Dufgui 
Just a simple question. for an extension, how can I know it's outdated ? For now, I have created all the new required class and execute the new command. But I seems cannot find any properties in Extension class to see if an extension is outdated ?

**Comment by Dufgui** [comment]
for a simple start you can just get the code from the existing list-extension which check version in the bom artifact.
If you want to go further you can try to code something based on the 
https://www.mojohaus.org/versions-maven-plugin/examples/display-plugin-updates.html
you can see the code here :
https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java

but it's really more difficult....so it 's really not mandatory.
What do you think about it @kenfinnigan  @gsmet ?

**Comment by gsmet** [comment]
I think we will push towards using a given version of the platform bom so it will be an aggregated view of all the supported extensions.

Closing this for now.
