### ISSUE TITLE
Request routing partially broken in reactive RESTEasy

### ISSUE THREAD

**Issue by sithmein** [quarkusio/quarkus#25462]
### Describe the bug

Consider the following two resource classes:

```
@Produces(MediaType.TEXT_PLAIN)
@Path("/routing-broken/{id1}")
public class RoutingBrokenA {
    @GET
    @Path("/some/other/path")
	public Response doSomething(@PathParam("id1") String id) {
	    return Response.ok(id).build();
	}
}


@Produces(MediaType.TEXT_PLAIN)
@Path("/routing-broken/{id2}")
public class RoutingBrokenB {
    @GET
    @Path("/some/path")
	public Response doSomething(@PathParam("id2") String id) {
	    return Response.ok(id).build();
	}
}
```

Note the different path parameter name on both classes. It seems that one class shadows the other class completely, i.e. requests matching `RoutingBrokenA.doSomething` are returned as 404. It works if the path parameter has the same name in both classes.

The same code works without problems in classic RESTEasy.

### Expected behavior

Both resource methods should be addressable by corresponding requests.

### Actual behavior

Only one of the two methods is accessible.

### How to Reproduce?

Run `quarkus.bugs.RoutingBrokenTest` from https://github.com/sithmein/bugs-in-quarkus.

### Output of `java -version`

17

### Quarkus version or git rev

2.8.3.Final

**Comment by sberyozkin** [comment]
@geoand This is a JAX-RS 2.0 concept which allows for having multiple class resources handle the same request. As far as I recall it does not really matter that the template vars are named differently, there is an algorithm which determines if both expressions are identical, but I don't recall it, must be in the spec. 
Workaround is to just to have these methods rooted under a single class resource

**Comment by geoand** [comment]
Thanks for the input @sberyozkin!

@stuartwdouglas since you did the route matching stuff, do you remember this?
I am surprised the TCK doesn't test this case...

**Comment by sberyozkin** [comment]
@geoand Np at all, TCK might be quite incomplete as well.

**Comment by mschorsch** [comment]
I don't think this ist a bug per se. In Resteasy exists a flag called `resteasy.wider.request.matching` to disable the described behaviour. 
> Turns off the JAX-RS spec defined class-level expression filtering and instead tries to match version every method's full path. 

https://docs.jboss.org/resteasy/docs/4.7.2.Final/userguide/html_single/index.html
 
So i think the behaviour ist spec compliant, but somtimes surprising.

**Comment by geoand** [comment]
According to @sberyozkin this is allowed per spec (I have to admit, that I have not seen this myself)

**Comment by gsmet** [comment]
@sithmein are you using `resteasy.wider.request.matching`?

**Comment by sithmein** [comment]
Not that I know. At least we didn't configure it explicitly.
I had a look at the JAX-RS spec, section 3.7.2 and it specifically mentions

> 1. Identify a set of candidate root resource classes matching the request:
> ...
>  Note that two or more classes in `C` may add the same regular expression to `E` if they are annotated with the same URI path template (modulo variable names).

It's a bit out of context but essentially this means that it's perfectly legal to have several classes share the same @Path. The correct method in one of the candidate classes (`C`) is determined at step 2.

**Comment by sithmein** [comment]
Any estimates when this issue will be fixed to make the JAX-RS functionality spec-compliant?

**Comment by geoand** [comment]
If you can find the place in the spec that mentions this, I'll look into it

**Comment by sithmein** [comment]
I mentioned it in my previous comment.

**Comment by geoand** [comment]
Ah, sorry, missed it
