### ISSUE TITLE
Support Flyway cleanOnValidationError

### ISSUE THREAD

**Issue by fabrii** [quarkusio/quarkus#25463]
### Description

It would be nice if Quarkus can support the Flyway cleanOnValidationError parameter. This would be really useful for dev and integration environments.

https://flywaydb.org/documentation/configuration/parameters/cleanOnValidationError

**Comment by gastaldi** [comment]
@fabrii want to submit a PR?

**Comment by gsmet** [comment]
Example of similar PR: https://github.com/quarkusio/quarkus/pull/11437/files .

**Comment by fabrii** [comment]
> @fabrii want to submit a PR?

Yeah, sure. First time contributing with PR. I have some questions:

1) Do I also need to update the guide in the same PR right? 
I cannot find the https://quarkus.io/guides/flyway guide in the /main/docs/src/main/asciidoc
2) In this case, do I need to run the CI tasks on my fork?

Thanks

**Comment by gastaldi** [comment]
> * Do I also need to update the guide in the same PR right?
>   I cannot find config properties of https://quarkus.io/guides/flyway guide in the /main/docs/src/main/asciidoc


The config properties doc are generated automatically during the build, so unless you want to add a section in the Flyway guide, you don't need to touch it.


> * In this case, do I need to run the CI tasks on my fork?

This is done whenever you push to your fork. You can create the PR as draft and it would allow us to review your work while your fork builds it 😉

**Comment by gsmet** [comment]
You don't need to update the doc. The configuration reference is automatically generated from the config javadoc. Just make the javadoc meaningful.

As for building, see https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build, you're in the "Contributing to an extension" case. So just build the extension locally and check the Flyway ITs work.
