### ISSUE TITLE
Mongo id duplication

### ISSUE THREAD

**Issue by fsudrot** [quarkusio/quarkus#25476]
### Describe the bug

With a native application deployed in several pods, inserting a document in mongo can fail with this kind of error :
```
com.mongodb.MongoWriteException: Write operation error on server localhost:30003. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: compiiu.events index: _id_ dup key: { _id: ObjectId('627a163a7cfc79282b2428e7') }', details={}}.
```
The ObjectId is set by the mongo driver. It is composed of several parts, see [doc](https://www.mongodb.com/docs/manual/reference/method/ObjectId/) :
- A 4-byte timestamp, representing the ObjectId's creation, measured in seconds since the Unix epoch.
- A 5-byte random value generated once per process. This random value is unique to the machine and process.
- A 3-byte incrementing counter, initialized to a random value.

In jar deployment, no problem, the unicity of the different parts is managed by the SecureRandom class.
In native mode, it appears that SecureRandom is replaced at build time. So each pod share the same SecureRandom

With such a replacement, the second part in ObjectId is the same across all application instances.
```java
static {
        try {
            SecureRandom secureRandom = new SecureRandom();
            RANDOM_VALUE1 = secureRandom.nextInt(0x01000000);
            RANDOM_VALUE2 = (short) secureRandom.nextInt(0x00008000);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
    
The third part is also impacted :
```java
private static final AtomicInteger NEXT_COUNTER = new AtomicInteger(new SecureRandom().nextInt());
```

As SecureRandom is used in several ObjectId parts, conflicts are not the majority but can occur and occur during our bench tests.

### Expected behavior

ObjectId generated by the mongo driver is intended to be unique

### Actual behavior

ObjectId duplications occcur at low rate but occur

### How to Reproduce?

Follow the [guide](https://quarkus.io/guides/mongodb).
Add 
```java
    void onStart(@Observes StartupEvent ev) {
        LOGGER.info("The application is starting...");
        LOGGER.info("ObjectId:" + new ObjectId().toHexString());
    }
```

To see the great proximity of ObjectId across several start, build application in native mode and make several starts
```
2022-05-09 17:07:11,770 INFO  [org.acm.mon.AppLifecycleBean] (main) ObjectId:62792e1fc7f7e82a7794affa
2022-05-09 17:07:14,861 INFO  [org.acm.mon.AppLifecycleBean] (main) ObjectId:62792e22c7f7e82a7794affa
```
62792e1fc7f7e82a7794affa => 62792e1f c7f7e82a77 94affa
62792e22c7f7e82a7794affa => 62792e22 c7f7e82a77 94affa

First part, the timestamp is here different, but it is easy to have the same timestamp with threads and/or pods with several invocations per seconds.
Second part is always the same  :-(
Third part, the counter starts with the same value due to its initialization with SecureRandom

### Output of `uname -a` or `ver`

Linux compiiu-492-7g8kp 3.10.0-957.12.2.el7.x86_64 #1 SMP Fri Apr 19 21:09:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

17

### GraalVM version (if different from Java)

GraalVM 22.0.0.2-Final Java 17 Mandrel Distribution

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by geoand** [comment]
@zakkak can an entire static init method be substituted in GraalVM?

Asking because as @fsudrot mentions, the problematic code is:

```
    static {
        try {
            SecureRandom secureRandom = new SecureRandom();
            RANDOM_VALUE1 = secureRandom.nextInt(0x01000000);
            RANDOM_VALUE2 = (short) secureRandom.nextInt(0x00008000);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25479 actually takes care of it

**Comment by fsudrot** [comment]
Thanks
In which version this fix will be available ?

**Comment by geoand** [comment]
`2.9.1.Final`

**Comment by zakkak** [comment]
> @zakkak can an entire static init method be substituted in GraalVM?

FTR No, unfortunately there is no way to substitute static init methods...

**Comment by geoand** [comment]
That's what I though, thanks!
