### ISSUE TITLE
Document guidelines for RESTEasy implementation-agnostic extensions

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#25481]
### Description

RESTEasy Reactive has become very stable and also provides some features unavailable in RESTEasy Classic. For Quarkus extensions it thus makes sense to support both RESTEasy flavors and it would be nice with some documentation on how to implement a RESTEasy flavor-agnostic Quarkus extension.

I am currently in a position where a document like this would be useful. Without having looked into what is necessary to make my RESTEasy Classic specific Quarkus extensions compatible with RESTEasy Reactive, here are some topics that I would expect the document to touch:

- Can the Quarkus extension in question itself supply any JAX-RS resources?
- Can the extension use the MP REST Client?
- Are optional dependencies required for the two RESTEasy implementations or should the extension instead depend on some common module?
- Are there situations where it would become necessary to create two flavors of the extension?

**Comment by geoand** [comment]
Thanks for opening the issue!

A few question before I add the documentation:

> Can the Quarkus extension in question itself supply any JAX-RS resources?

I assume you mean that the extension has some JAX-Rs resources in its `runtime` module and you would like to have them exposed as well?

> Can the extension use the MP REST Client?

Can you elaborate on what kind of usage you mean here?

**Comment by knutwannheden** [comment]
> I assume you mean that the extension has some JAX-Rs resources in its `runtime` module and you would like to have them exposed as well?

Yes, that is correct. We do have such extensions with resources using standard JAX-RS annotations (including e.g. `@RolesAllowed`)



> > Can the extension use the MP REST Client?
> 
> Can you elaborate on what kind of usage you mean here?

We also have extensions which at startup (runtime init) will call some remote REST service to do some kind of registration. Can that then be done using the MP REST Client or would more primitive mechanisms be required due to the Classic / Reactive split?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25494 is what I have in mind. Let me know if it answers your questions
