### ISSUE TITLE
reactive-messaging-kafka: CNFE: io.quarkus.netty.runtime.NettyTemplate

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#2548]
**Describe the bug**
A project with `quarkus-smallrye-reactive-messaging-kafka` and `quarkus-smallrye-reactive-messaging` works fine in the `quarkus:dev` mode but fails to start from jar.
Also fails to build to a native image.

**Expected behavior**
The application should start without error and it should be possible to build a native image.
Adding a dependency on `quarkus-vertx` solves the problem.
I think it may be that the dependency on `quarkus-vertx` is missing from  `quarkus-smallrye-reactive-messaging-kafka`. There is a dependency between the deployment modules.

**Actual behavior**
The following exception is thrown when the jar is executed:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
        ... 1 more
Caused by: java.lang.NoClassDefFoundError: io/quarkus/netty/runtime/NettyTemplate
        at io.quarkus.deployment.steps.NettyProcessor$createExecutors2.deploy(Unknown Source)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.netty.runtime.NettyTemplate
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```

**To Reproduce**
1. generate a project
2. add quarkus-smallrye-reactive-messaging-kafka
3. add quarkus-smallrye-reactive-messaging
4. build with `mvn clean package`
5. execute with java -jar target/<my-app>-runner.jar

**Configuration**
```properties
# Add your application.properties here, if applicable.
smallrye.messaging.sink.queries.type=io.smallrye.reactive.messaging.kafka.Kafka
smallrye.messaging.sink.queries.topic=queries
smallrye.messaging.sink.queries.bootstrap.servers=localhost:9092
smallrye.messaging.sink.queries.key.serializer=org.apache.kafka.common.serialization.StringSerializer
smallrye.messaging.sink.queries.value.serializer=org.apache.kafka.common.serialization.StringSerializer
smallrye.messaging.sink.queries.acks=1
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux t580 5.0.16-200.fc29.x86_64 #1 SMP Tue May 14 18:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
 - GraalVM version (if different from Java): 1.0.0-rc15
 - Quarkus version or git rev: master

**Comment by cescoffier** [comment]
Can you try to add the `quarkus-vertx` extension and if you still have an issue the, `smallrye-reactive-stream-operators` extension?

**Comment by cescoffier** [comment]
Don't worry, I've reproduced it... Fix on its way.

**Comment by michalszynkiewicz** [comment]
Adding quarkus-vertx works around the problem, yes

**Comment by cescoffier** [comment]
at the same time, I'm fixing a native build issue.

**Comment by cescoffier** [comment]
Can you check #2551?

**Comment by rsvoboda** [comment]
@cescoffier any idea why `quarkus:dev` worked fine ?

@michalszynkiewicz can you share your sample app ?

**Comment by rsvoboda** [comment]
kafka-quickstart doesn't reveal the problem as it has explicit dependency on quarkus-vertx

**Comment by rsvoboda** [comment]
Plus there is https://github.com/quarkusio/quarkus-quickstarts/issues/145

**Comment by michalszynkiewicz** [comment]
@rsvoboda the simplest possible reproducer: https://github.com/michalszynkiewicz/quarkus-kafka-error-reproducer
It's enough to build the project to observe the problem
