### ISSUE TITLE
Quarkus CLI installed with JBang prints warning: SLF4J: Class path contains multiple SLF4J bindings 

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#25484]
### Describe the bug

When Quarkus CLI is installed by JBang using an **explicit version**, a SLF4J warning is printed on every run of the CLI.
```
jbang app install --name myquarkus --fresh --force io.quarkus:quarkus-cli:2.8.3.Final:runner
```
However, without specific version, the CLI works fine:
```
$ jbang app install --name myquarkus --fresh --force quarkus@quarkusio
...
$ myquarkus --version
2.8.3.Final
```

### Expected behavior

```
2.8.3.Final
```

### Actual behavior

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.m2/repository/io/quarkus/quarkus-cli/2.8.3.Final/quarkus-cli-2.8.3.Final-runner.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.1.0.Final/slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Slf4jLoggerFactory]
2.8.3.Final
```

### How to Reproduce?

Install JBang, if needed:
```
curl -Ls https://sh.jbang.dev | bash -s - app setup
source ~/.bashrc
```
Install Quarkus CLI using explicit version:
```
jbang app install --name myquarkus --fresh --force io.quarkus:quarkus-cli:2.8.3.Final:runner
```
Invoke Quarkus CLI:
```
myquarkus --version
```

Optionally, uninstall CLI:
```
jbang app uninstall myquarkus
```

### Output of `uname -a` or `ver`

Linux 5.17.5-200.fc35.x86_64

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10) OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

### Quarkus version or git rev

2.8.3.Final

**Comment by maxandersen** [comment]
This is expected as maven pom says it needs dependencies but it's actually a fat jar. 

You'll need to use the https url rather than the maven gav.

**Comment by geoand** [comment]
@maxandersen so should we close this?

**Comment by maxandersen** [comment]
Yup. Thought I already did.

**Comment by ia3andy** [comment]
In that case we should update the doc: https://quarkus.io/guides/cli-tooling

**Comment by ia3andy** [comment]
Closing, I created a specific issue for this.
