### ISSUE TITLE
Dockerfile.jvm build fails with kaniko: user: unknown user 1001

### ISSUE THREAD

**Issue by weltonrodrigo** [quarkusio/quarkus#25499]
### Describe the bug

This is a known bug in kaniko https://github.com/GoogleContainerTools/kaniko/issues/1456, where commands like 

```Dockerfile
COPY --chown=1001 target/quarkus-app/lib/ /deployments/lib/
```

fail with:
```
error building image: error building stage: failed to execute command: getting user group from chown: user: unknown user 1001
```

It would be nice, as the kaniko bug is >1 year old, that quarkus could provided a (probably harmless) workaround on it's Dockerfiles:

```Dockerfile
RUN microdnf install shadow-utils
RUN adduser -u 1001 appuser

COPY --chown=1001 target/quarkus-app/lib/ /deployments/lib/
```

This bug makes quarkus impossible to build on gitlab CICD, as a kaniko build is the recommended way to build a docker image there.

**Comment by geoand** [comment]
Seems reasonable. @maxandersen WDYT?

**Comment by maxandersen** [comment]
Hmmm - doesn't this end up conflicting with kuberneteS/openshift owner ids?

**Comment by geoand** [comment]
According to the proposal, we wouldn't change the user ids, we'd just run `RUN adduser -u 1001 appuser` to make sure the user exists.

**Comment by maxandersen** [comment]
As long as we can verify It still works in openshift It's fine. 

I.e. take particular notice of https://docs.openshift.com/container-platform/4.2/openshift_images/create-images.html section of "support arbitrary user ids"

**Comment by geoand** [comment]
> As long as we can verify It still works in openshift It's fine.

Summoning @rsvoboda for this :)

**Comment by ejba** [comment]
giving my two cents if I can :) 

IMHO, there's a concern here that it's adding a new layer to the image with more libraries that another set of users probably don't need. May I suggest creating some cli option to give developers the option to choose to create the user?

**Comment by geoand** [comment]
If we are concerned about the extra layer, then I would not go so far as to add a new flag to the Dockerfile. We could just keep the commands in the Dockerfile but commented out with an explanation of when it might make sense to use them.

**Comment by ejba** [comment]
> We could just keep the commands in the Dockerfile but commented out with an explanation of when it might make sense to use them.

After that, adding some documentation on website telling gitlab users to uncomment those lines.

**Comment by geoand** [comment]
Makes sense

**Comment by rsvoboda** [comment]
Hi @gastaldi / @iocanel, could you check the suggested approach in the engineering OCP env before we will put our hands on it, please? Right now, we are busy with other priority tasks.

**Comment by rsvoboda** [comment]
Would be handy to have kubernetes/openshift checks (https://github.com/quarkusio/quarkus/pull/17674) in place.

**Comment by Sgitario** [comment]
@geoand @weltonrodrigo I think this issue is gone thanks to the changes in https://github.com/quarkusio/quarkus/commit/c24179a306ba0cb0639b745a769be505532cf0e4. The new template is no longer using the user 1001 (I could reproduce this issue and after updating the Dockerfile, it works fine in OpenShift).

**Comment by geoand** [comment]
Thanks for investigating @Sgitario! 

Let's close this in light of the information you mention above.
