### ISSUE TITLE
@Form replacement in Reactive RestClient

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#25503]
### Describe the bug

Trying to adopt `Reactive RestClient`. However couldn't able to locate the replacement for `@Form`

```java

import org.jboss.resteasy.annotations.Form;

@RegisterClientHeaders(RequestUUIDHeaderFactory.class)
public interface MyRestClient {

  @POST
  @Path("/greetings")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
  TestResponse getFormData(@Form TestRequest request);


}


```

```java
@Getter
@Setter
public class TestRequest {

  @FormParam("test_name")
  private final String name;

  public TestRequest() {
    this.name = "Hello TEST";
    
  }

}
```

### Expected behavior

Reactive Rest Client offers an replacement for @form

### Actual behavior

Compile time error

### How to Reproduce?

Try to compile the above classes with only reactive client as dependency, the compilation will fail

### Output of `uname -a` or `ver`

linux 

### Output of `java -version`

11

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.8.2

**Comment by geoand** [comment]
Thanks for reporting!

I opened https://github.com/quarkusio/quarkus/pull/25523 to add a note that users should use the standard `@BeanParam` annotation (which also happens to be more powerful)
