### ISSUE TITLE
@QuarkusIntegrationTest starts native executable in prod profile instead of test profile

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#25519]
### Describe the bug

I was struggling with database test data population during native-image test in a project and it boiled down to the simple fact that the native-executable is started in *prod* profile (hence expecting `%prod` values) instead of the *test* profile the JVM test correctly uses. 

### Expected behavior

native-image executable is started in *test* profile during test execution.

### Actual behavior

native-image executable is started in *prod* profile during test execution.

### How to Reproduce?

I reproduced it with this tiny example downloaded from code.quarkus.io:
```
$ curl -O -J  https://code.quarkus.io/d?e=io.quarkus:quarkus-resteasy
$ unzip code-with-quarkus.zip 
$ cd code-with-quarkus 
```
Patch with this patch:
```diff
diff --git a/src/main/java/org/acme/GreetingResource.java b/src/main/java/org/acme/GreetingResource.java
index 055f53c..b4e1e1e 100644
--- a/src/main/java/org/acme/GreetingResource.java
+++ b/src/main/java/org/acme/GreetingResource.java
@@ -1,5 +1,7 @@
 package org.acme;
 
+import org.eclipse.microprofile.config.inject.ConfigProperty;
+
 import javax.ws.rs.GET;
 import javax.ws.rs.Path;
 import javax.ws.rs.Produces;
@@ -8,9 +10,12 @@ import javax.ws.rs.core.MediaType;
 @Path("/hello")
 public class GreetingResource {
 
+    @ConfigProperty(name = "my.property")
+    String property;
+
     @GET
     @Produces(MediaType.TEXT_PLAIN)
     public String hello() {
-        return "Hello RESTEasy";
+        return property;
     }
 }
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
index e69de29..7f9990a 100644
--- a/src/main/resources/application.properties
+++ b/src/main/resources/application.properties
@@ -0,0 +1,2 @@
+%test.my.property=Hello, test!
+my.property=Hello.
diff --git a/src/test/java/org/acme/GreetingResourceTest.java b/src/test/java/org/acme/GreetingResourceTest.java
index 87fbd5c..e58f732 100644
--- a/src/test/java/org/acme/GreetingResourceTest.java
+++ b/src/test/java/org/acme/GreetingResourceTest.java
@@ -15,7 +15,7 @@ public class GreetingResourceTest {
           .when().get("/hello")
           .then()
              .statusCode(200)
-             .body(is("Hello RESTEasy"));
+             .body(is("Hello, test!"));
     }
 
 }
```

Running the tests as:
```
./mvnw  verify -Pnative
```
Passes the JVM mode:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.953 s - in org.acme.GreetingResourceTest
```
And fails with native:
```
[ERROR] org.acme.GreetingResourceIT.testHelloEndpoint  Time elapsed: 1.452 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello, test!"
  Actual: Hello.
```
Note how the Quarkus app starts:

```
Executing "/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/tmp/code-with-quarkus/target/quarkus.log -Dquarkus.log.file.enable=true"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.9.0.Final) started in 0.020s. Listening on: http://0.0.0.0:8081
INFO  [io.quarkus] (main) Profile prod activated. 
INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
```
i.e. the profile should be **test**, not **prod**. 

### Output of `uname -a` or `ver`

Linux amd64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### GraalVM version (if different from Java)

native-image 22.1.0.0-Final Mandrel Distribution (Java Version 17.0.3+7)

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by Karm** [comment]
I'll try to make the test framework to append `-Dquarkus-profile=test` and see.     Unless this behavior is intentional for some reason...

**Comment by Karm** [comment]
Appending it explicitly to the maven command makes it work:
```
./mvnw  verify -Pnative -Dquarkus-profile=test
```
Adds the profile here [DefaultNativeImageLauncher.java](https://github.com/quarkusio/quarkus/blob/main/test-framework/common/src/main/java/io/quarkus/test/common/DefaultNativeImageLauncher.java#L134)

So...I don't know. Close this "issue"? It's somewhat annoying that the Jar Launcher doesn't need it set explicitly then.

**Comment by geoand** [comment]
This is the intended behavior

**Comment by Karm** [comment]
@geoand Ack.

I'll open a doc PR though.

**Comment by geoand** [comment]
Great, thanks!

**Comment by Karm** [comment]
@geoand I took a look at the [building-native-image.adoc#L275](https://github.com/quarkusio/quarkus/blame/main/docs/src/main/asciidoc/building-native-image.adoc#L275), but I don't know how to explain there why in one case `-Dquarkus.test.native-image-profile=test` is O.K. and in another it is not and you have to do `-Dquarkus-profile=test`. It doesn't feel right.

If you could take a look at this small reproducer (just a Hello world with 1 tiny entity):

```
$ git clone https://github.com/Karm/dev-null.git
$ cd dev-null/issue-25519/
$ export JAVA_HOME=/home/karm/workspaceRH/mandrel-release/CPU/mandrel-java11-22.1.0.0-Final/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
```

## PASS :heavy_check_mark: 
$ ./mvnw verify -Pnative -Dquarkus-profile=test

## FAIL :x: 
$ ./mvnw verify -Pnative -Dquarkus.test.native-image-profile=test

You can see that in both cases, the `%test` prefixed string property is injected as expected, so far so good. 
Although the database test data import is not executed with `-Dquarkus.test.native-image-profile=test` and the test fails. You have to run it with `-Dquarkus-profile=test` to have the database populated.

Weirdly enough, the **failing** scenario executed with `-Dquarkus.test.native-image-profile=test`, as [documentation](https://github.com/quarkusio/quarkus/blame/main/docs/src/main/asciidoc/building-native-image.adoc#L275) tells you, has a `-Dquarkus.profile=test` appended to the execution args of the native, see:

![screenshot](https://user-images.githubusercontent.com/691097/168027868-2a7e50d7-9dca-4c8d-8341-f55ec573450c.png)


I can carry on with my project, using `$ ./mvnw verify -Pnative -Dquarkus-profile=test`, but I still think this is at least confusing to a random user out there :(

**Comment by geoand** [comment]
This is a tricky one, but it comes down to the fact that unless otherwise specified (i.e. `-Dquarkus.profile` is set at **build time**), the native image binary is built with the `prod` profile.
So when `mvn verify -Dquarkus.test.native-image-profile=test` is used, the application is built with the prod profile, which in turn leads to `import-dev.sql` not being included in native image.
When the application is then run using the `test` the load script cannot be found and it thus not executed.

**Comment by Karm** [comment]
@geoand Ah, it all clicked together now. I have this in my CI that deploys to a server:

```
      - name: Package
        # We don't want the native executable to be built wth test profile (e.g. including superfluous test resources)
        run: |
          ./mvnw clean verify -Pnative -Dquarkus-profile=test && ./mvnw package -DskipTests -Pnative
```

I know enough to update the doc now.  Thx.  :+1:

**Comment by geoand** [comment]
🎉

**Comment by gian1200** [comment]
Isn't it supposed to be `-Dquarkus.profile=test`, with dot instead of hyphen?

**Comment by geoand** [comment]
You are right!
