### ISSUE TITLE
Calling `.stream()` on List returned from REST client (Classic) throws java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public default java.util.stream.Stream java.util.Collection.stream()

### ISSUE THREAD

**Issue by softmetz** [quarkusio/quarkus#25517]
### Describe the bug

I use the classic REST client to retrieve a collection (e.g. `[]`). The signature of the method in the REST client 
 is `List<SomeDTO> getSomeDTOs()`.

When on the result the method `.stream()` gets called, I get a runtime exception `java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public default java.util.stream.Stream java.util.Collection.stream()` at `org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:74)`

From looking at `org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy` and the conditions the error occurs, I could imagine that interface (default) methods not being added to `methodMap` properly, but that's just my uneducated guess.

It first occured to me in 2.8.3 and is still in 2.9.0.

### Expected behavior

The `stream()` method gets called through the proxy

### Actual behavior

Exception gets throws: `java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public default java.util.stream.Stream java.util.Collection.stream()` at `org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:74)`

### How to Reproduce?

1. Request an JSON array through REST client and map it to `java.util.List` 
2. Call `List#stream()` on this list

### Output of `uname -a` or `ver`

Linux nb0mws009 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-post-Debian-1deb11u1) OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1deb11u1, mixed mode, sharing)

### Quarkus version or git rev

2.9.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
This works properly with the Reactive REST Client which is where our focus is on going forward, so I'll close this.

**Comment by softmetz** [comment]
Thank you. I ported it to reactive and then the error message was somewhat clearer:

`Caused by: org.eclipse.microprofile.rest.client.RestClientDefinitionException: org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface com.foobar.FooRestAPIClient : Sub resource type is not a class: java.util.List`

In the end I forgot to add `@GET` to the method. So I am leaving this note for anybody who stumbles upon this in the future. ;)
