### ISSUE TITLE
OpenTelemetry: Support exclusion of non-application URIs if custom Sampler is used

### ISSUE THREAD

**Issue by calohmn** [quarkusio/quarkus#25525]
### Description

This refers to the `quarkus-opentelemetry` extension.

We have opted for using a custom `io.opentelemetry.sdk.trace.samplers.Sampler` CDI Bean in order to extend the existing sampling logic.
As stated in the documentation, this means that the `quarkus.opentelemetry.tracer.suppress-non-application-uris` option has no effect, so that the logic for suppressing non-application uris has to be added manually to the custom Sampler.

For applications not using a common `/q` prefix for the non-application uris, assembling the URIs and applying the path resolution shows to be quite cumbersome.

It would be helpful, if the
```
List<String> dropNonApplicationUris,
List<String> dropStaticResources
```
information, given to the [TracerRecorder.setupSampler()](https://github.com/quarkusio/quarkus/blob/2205bb989655970f4da72b752ff2c2be7c5103cc/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java#L139-L140) method is somehow made available for the creation of a custom Sampler.

### Implementation ideas

Instead of checking for a Sampler bean, the `TracerRecorder.setupSampler()` method could check for a bean of a new `SamplerFactory` class, containing a factory method to which the above mentioned `dropNonApplicationUris` and `dropStaticResources` can be supplied by the `TracerRecorder.setupSampler()` method.

**Comment by radcortez** [comment]
Please, go ahead @mun711. Thank you!

**Comment by mun711** [comment]
added the changes in https://github.com/quarkusio/quarkus/pull/26367
Updated the TracerUtil:mapSampler method to search for a sampler bean and use it instead of a baseSampler if found.
Please let me know if that looks good to you or we still want to move this logic to a SamplerFactory.

**Comment by calohmn** [comment]
FMPOV, this kind of approach of applying the DropNamesSampler and parentBased Sampler on top of the custom sampler also looks ok. The [configuration properties documentation](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_configuration) would then have to be adapted, dropping the "Providing a custom [...]" part for the `quarkus.opentelemetry.tracer.suppress-non-application-uris` and `quarkus.opentelemetry.tracer.include-static-resources` descriptions.
