### ISSUE TITLE
Websocket @ServerEndpoint - have a way to retrieve http headers

### ISSUE THREAD

**Issue by petarminchev** [quarkusio/quarkus#25536]
### Description

I have the simple need to access the http headers, so I can retrieve user-agent, ip, etc... of the incoming request.
These properties are inside **HandshakeRequest** object, which I have no access to inside my @**ServerEndpoint** class.

One of the options mentioned in Java docs is to configure a custom **Configurator** and grab the headers inside this method:
**public void modifyHandshake(ServerEndpointConfig conf, HandshakeRequest req,  HandshakeResponse resp) {**

And after the header values are grabbed to put them inside the ServerEndpointConfig user properties object which the @**ServerEndpoint** class can inject inside the @**OnOpen** method.

**@OnOpen
public void onOpen(Session session, EndpointConfig config) {**

BUT there is a huge **blocker** here -> the ServerEndpointConfig is a **singleton** and all requests are sharing this object. That means the same underlying map is used and it will break under concurrency, also it is a HashMap not a ConcurrencyHashMap.

This is a very well known inconsistency issue in the Java Websockets Implementations in servers. Here is some information:

https://stackoverflow.com/questions/17936440/accessing-httpsession-from-httpservletrequest-in-a-web-socket-serverendpoint
https://stackoverflow.com/questions/28939581/access-useragent-in-websocket-session

So I am completely stuck here with the simple task of having access to the http headers in my WebSocket class.

What do you suggest? I see 2 options:
1. Provide a way to inject HandshakeRequest inside the @OnOpen method
2. Make ServerEndpointConfig not to be a singleton and be per request and to use ConcurrentHashMap. Then the getUserProperties() could be used in the custom configurator.

To be honest I prefer option 1.

Thank you in advance!

**Comment by geoand** [comment]
cc @cescoffier @mkouba seems like this is a popular feature so maybe we should address it in the new websockets implementation

**Comment by mkouba** [comment]
@petarminchev Hm, if I understand the javadoc of `jakarta.websocket.server.ServerEndpointConfig.Configurator.modifyHandshake()` (see below) correctly, you should be able to modify the `ServerEndpointConfig#getUserProperties()` inside the `modifyHandshake()` method and then obtain the modified properties with `jakarta.websocket.Session#getUserProperties()` in a callback.

_"The user properties made available via `ServerEndpointConfig#getUserProperties()` must be a per WebSocket connection (i.e. per `jakarta.websocket.Session`) copy of the user properties. This copy, including any modifications made to the user properties during the execution of this method must be used to populate the initial contents of `jakarta.websocket.Session#getUserProperties()`"_.

**Comment by mkouba** [comment]
> But I just tested latest `Quarkus` and seems `getUserProperties()` is unfortunately still global and shared between all sessions. It is not making a copy of the user properties.

That's unfortunate :-(.

> I am not 100% sure what websocket implementation Quarkus uses underneath, but I think it is worth if you double-check the behaviour. 

The Quarkus websocket extension is currently based on [a fork](https://github.com/quarkusio/quarkus-http) of [Undertow](https://undertow.io/). And yes, we should double-check the behavior.

FYI we're currently working on a new declarative API for WebSockets (running on top of Vert.x WebSockets). Hopefuly, we'll have something merged in the main branch later next week.

**Comment by mkouba** [comment]
> cescoffier @mkouba seems like this is a popular feature so maybe we should address it in the new websockets implementation

For the record, in WS Next a user can inject the [`io.quarkus.websockets.next.HandshakeRequest`](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/HandshakeRequest.java) in an endpoint callback argument or obtain it directly from a connection and then access the HTTP headers from the initial HTTP handshake request [like this](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/deployment/src/test/java/io/quarkus/websockets/next/test/args/HandshakeRequestArgumentTest.java#L48).

**Comment by cescoffier** [comment]
Following what @mkouba said, I'm going to close this issue. The new WebSocket implementation (websocket next) provides this feature. It's now the recommended approach for WebSocket, as it is much more in line with the rest of Quarkus. 

Not that WebSocket Next is NOT an implementation of Jakarta WebSocket - it's a different model (in term of annotation it's close, but how it behaves is very different)
