### ISSUE TITLE
grpc-service doesn't start in native binary

### ISSUE THREAD

**Issue by iskhakovt** [quarkusio/quarkus#25549]
### Describe the bug

Native binary doesn't start grpc-server if its interface is generated outside of quarkus.

### Expected behavior

`@GrpcServer` annotation should be enough to run grpc-server. For example, protoc generation may happen in a separate sub-project.

### Actual behavior

grpc-server doesn't start in native image, but does start in jvm build.

### How to Reproduce?

For simplicity, in this example grpc service implementation doesn't implement any interface, but the same happens if the implemented interface is generated outside of quarkus.

1. Clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/grpc-plain-text-quickstart
2. Modify `./src/main/java/io/quarkus/grpc/examples/hello/HelloWorldService.java` to
```
package io.quarkus.grpc.examples.hello;

import io.quarkus.grpc.GrpcService;

@GrpcService
public class HelloWorldService {}
```
3. Build the native binary: `./mvnw clean install -Pnative`
4. run `./target/grpc-plain-text-quickstart-1.0.0-SNAPSHOT-runner` => **grpc-service doesn't start**
6. run `quarkus dev` => **grpc-service starts**

### Output of `uname -a` or `ver`

Linux 5.15.32-1-MANJARO

### Output of `java -version`

openjdk version "17" 2021-09-14 LTS OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS) OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537

**Comment by michalszynkiewicz** [comment]
Does the jar that brings in the java interface have a jandex index?

**Comment by iskhakovt** [comment]
@michalszynkiewicz looks like no

```
❯ jar -tf target/grpc-plain-text-quickstart-1.0.0-SNAPSHOT.jar
META-INF/
META-INF/MANIFEST.MF
examples/
io/
io/quarkus/
io/quarkus/grpc/
io/quarkus/grpc/examples/
io/quarkus/grpc/examples/hello/
application.properties
examples/HelloRequestOrBuilder.class
examples/Greeter.class
examples/HelloRequest$Builder.class
examples/HelloRequest$1.class
examples/HelloRequest.class
examples/HelloReply$Builder.class
examples/HelloReply$1.class
examples/HelloReply.class
examples/HelloReplyOrBuilder.class
examples/GreeterBean.class
examples/GreeterGrpc$1.class
examples/GreeterGrpc$2.class
examples/GreeterGrpc$3.class
examples/GreeterGrpc$GreeterImplBase.class
examples/GreeterGrpc$GreeterStub.class
examples/GreeterGrpc$GreeterBlockingStub.class
examples/GreeterGrpc$GreeterFutureStub.class
examples/GreeterGrpc$MethodHandlers.class
examples/GreeterGrpc$GreeterBaseDescriptorSupplier.class
examples/GreeterGrpc$GreeterFileDescriptorSupplier.class
examples/GreeterGrpc$GreeterMethodDescriptorSupplier.class
examples/GreeterGrpc.class
examples/MutinyGreeterGrpc$MutinyGreeterStub.class
examples/MutinyGreeterGrpc$GreeterImplBase.class
examples/MutinyGreeterGrpc$MethodHandlers.class
examples/MutinyGreeterGrpc.class
examples/GreeterClient.class
examples/HelloWorldProto.class
io/quarkus/grpc/examples/hello/HelloWorldService.class
META-INF/maven/
META-INF/maven/org.acme/
META-INF/maven/org.acme/grpc-plain-text-quickstart/
META-INF/maven/org.acme/grpc-plain-text-quickstart/pom.xml
META-INF/maven/org.acme/grpc-plain-text-quickstart/pom.propertie
```

**Comment by cescoffier** [comment]
I need to check, but a @GrpcService without any interface may not be valid.
Also, the "other" module must be jandexed, if not Quarkus cannot find the gRPC classes and will not register them in the native image.

Try to jandex the other module and if it still does not work, please provide a reproducer using that extra module.

**Comment by michalszynkiewicz** [comment]
The most likely cause is the lack of the jandex index, see https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index for how to create an index

**Comment by cescoffier** [comment]
Closing, please re-open if it's still valid.
