### ISSUE TITLE
Custom authentication and elytron-security-properties-file for specific endpoint not working as expected

### ISSUE THREAD

**Issue by fabrii** [quarkusio/quarkus#25540]
### Describe the bug

I have a service with an api rest that has a custom filter for authentication.
I also want that service to expose the logging manager, only for admins.

Dependencies:

```
<dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-elytron-security-properties-file</artifactId>
</dependency>
<dependency>
        <groupId>io.quarkiverse.loggingmanager</groupId>
        <artifactId>quarkus-logging-manager</artifactId>
        <version>2.1.3</version>
        <scope>runtime</scope>
</dependency>
```

Application.properties:

```
quarkus.http.auth.permission.basic.paths=/q/logging-manager/*
quarkus.http.auth.permission.basic.policy=authenticated
quarkus.http.auth.permission.basic.auth-mechanism=basic

quarkus.security.users.file.enabled=false
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.user=password
quarkus.security.users.embedded.roles.user=auth
```

Endpoint

```
   @GET
   @Path("/test")
   @Produces(MediaType.TEXT_PLAIN)
   @Transactional
   @RolesAllowed({"ROL1"})
   public boolean test(@PathParam long id) {
       return true;
   }
```

The /q/loggin-manager auth works as expected. When I try to access the URL, the basic authentication dialog appears.
The problem is that when I try to invoke the /test endpoint, I am getting a 403 forbidden, even though my Custom authentication filter allowed the access.

### Expected behavior

The /entity endpoint should not be processed by the embedded security domain.  Is there a way to use quarkus-elytron-security-properties-file only for /q/logging-manager/* ?

### How to Reproduce?

Reproducer in: 

https://github.com/fabrii/quarkus-playground/tree/basic_auth_app_properties

### Output of `java -version`

java version "11.0.13" 2021-10-19 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

### Quarkus version or git rev

2.7.5.Final

**Comment by sberyozkin** [comment]
@fabrii But you have a role `auth` assigned to a user in the properties but `ROL1` is expected so it is `403`

**Comment by fabrii** [comment]
> @fabrii But you have a role `auth` assigned to a user in the properties but `ROL1` is expected so it is `403`

Yes, but I want that user to only consume the  /q/logging-manager/* endpoint.

The rest of the endpoints have their custom authentication filters, using JWT.

**Comment by sberyozkin** [comment]
In general you can use custom pre-match JAX-RS authentication filters only if you disable the proactive authentication but in this case it is better to represent it as an `HttpAuthenticationMechanism`

**Comment by sberyozkin** [comment]
@fabrii Thanks for the clarifications, good you've made some progress, in the future, if you'd like, you can add a custom mechanism like this one: https://quarkus.io/guides/security-customization#httpauthenticationmechanism-customization

In your case you'd not need to delegate, you'd just return something directly from it.

Sorry, I got confused, the point about the proactive authentication is relevant if one would like to catch the exceptions thrown by Quarkus Security, since by default it runs before the JAX-RS chain: https://quarkus.io/guides/security-built-in-authentication#proactive-authentication.

thanks

**Comment by fabrii** [comment]
Thank you for the explanation! :smiley:
