### ISSUE TITLE
Elastic search connection using oidc client

### ISSUE THREAD

**Issue by anisharoofi** [quarkusio/quarkus#25558]
### Describe the bug

In our application we want to connect to elastic search using oidc client but as I see only support for basic auth has been provided. I wanted to know if there is any other way to connect to elastic search using oidc client.

### Expected behavior

Connects to Elastic search using oidc client

### Actual behavior

Only basic auth is supported

### How to Reproduce?

https://quarkus.io/guides/elasticsearch

### Output of `uname -a` or `ver`

w

### Output of `java -version`

17.0.2

### GraalVM version (if different from Java)

17.0.2

### Quarkus version or git rev

2.8.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

### Additional information

https://quarkus.io/guides/elasticsearch

**Comment by anisharoofi** [comment]
Please help with this issue

**Comment by geoand** [comment]
cc @loicmathieu @yrodiere

**Comment by yrodiere** [comment]
I have honestly no idea how to use oidc with the Elasticsearch client. That's probably not currently supported, but maybe it should be. @sberyozkin I think there was a push on quarkus-dev at some point to standardize authentication across Quarkus, do you know if there is some progress on that front?

However, what I know is that you can [configure the low-level client manually](https://quarkus.io/guides/elasticsearch#programmatically-configuring-elasticsearch), adding headers to the request in particular. Maybe that would allow you to work around the missing feature?

**Comment by loicmathieu** [comment]
Yes, the low level client can be built with an OIDC token, see https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/_other_authentication_methods.html#_elasticsearch_token_service_tokens

It is not currently possible to configure it this way in Quarkus. As the token must be set at client creation time, this is not really compatible with the way we currently build the client that is application scoped, in this case the client would need to be request scoped.

**Comment by yrodiere** [comment]
> It is not currently possible to configure it this way in Quarkus. As the token must be set at client creation time, this is not really compatible with the way we currently build the client that is application scoped, in this case the client would need to be request scoped.

I suppose we could add some interface to allow developers to declare a callback to be applied to `RestClientBuilder`.
Or we could make `RestClientBuilder` a `@Dependent` bean, so that it becomes possible to use CDI observers to customize the builder.

That being said, what I suggested can still work:

> However, what I know is that you can [configure the low-level client manually](https://quarkus.io/guides/elasticsearch#programmatically-configuring-elasticsearch), adding headers to requests in particular. Maybe that would allow you to work around the missing feature?

You can definitely add headers to eveery request just by configuring the http client using `RestClientBuilder.HttpClientConfigCallback`.

**Comment by anisharoofi** [comment]
Thanks for the reply, I was able to add oidc token to header to elastic search high level client using RequestOptions and I had to Request Scope the RequestOptions though and Inject it while making the high level client Request. 

`
public RequestOptions getOptions() {
RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
builder.addHeader( "Authorization", "Bearer + tokens.getAccessToken());
return builder.build();
}`

Then while making the call I would add it like this  while injecting the above code
`this.elasticsearchclient.ping(requestOptions.getOptions())`

I think this solved my problem. Thank you
