### ISSUE TITLE
Newline in Response-Header causes RestEasy-Service to hang forever

### ISSUE THREAD

**Issue by fkeichfe** [quarkusio/quarkus#25554]
### Describe the bug

I have just downloaded the minimal project pom.xml from Quarkus with quarkus-resteasy-dependency.

This small modification causes the GreetingService to hang forever when called:

`
@GET  
    @Produces(MediaType.TEXT_PLAIN)  
    public Response hello() {  
        return Response.ok("Hello RESTEasy").header("MY_HEADER", "a\nb").build();  
    }
`
When I omit the newline-character from the Header-Value, everything works fine.
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8685537/code-with-quarkus.zip)

### Expected behavior

A call to `curl http://localhost:8080/hello` shouldn't hang forever

### Actual behavior

A call to `curl http://localhost:8080/hello` hangs forever

### How to Reproduce?

1. Extract zip-file
2. start application with `mvn quarkus:dev`
3. Call  `curl http://localhost:8080/hello`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.613]

### Output of `java -version`

 Corretto-17.0.0.35.1

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by Karm** [comment]
@fkeichfe Could you elaborate more on what you are trying to achieve? 
The header you are sending back is illegal. There must be a space or a tab after the '\n' char...and that would still be probably considered illegal by modern clients.

> A sender MUST NOT generate a message that includes
> line folding (i.e., that has any field-value that contains a match to
> the obs-fold rule)

https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4

**Comment by fkeichfe** [comment]
Thanks for the RFC link, I strongly suspected that linebreaks in header values are not allowed. I only checked the JAX-RS specification and Javadoc for any indications.
But I think it would be a better solution to throw an IllegalArgumentException or something else to indicate an illegal usage than to block forever, or how do you think about it?

**Comment by fkeichfe** [comment]
Ok, I am still using quarkus-resteasy, not quarkus-resteasy-reactive...

**Comment by geoand** [comment]
We will be putting most of our effort into RESTEasy Reactive going forward. 
If you want this fixed in RESTEasy Classic, I propose you open an issue in the RESTEasy repository.
