### ISSUE TITLE
JDBC Sqlite driver 

### ISSUE THREAD

**Issue by alexeysharandin** [quarkusio/quarkus#25556]
### Description

Quarkus support H2 embedded database but w/o native mode.
People asked to support native because it's somethimes required but it's not done yet by some reason.

In this case I propose to use java sqlite implementation.
Links to java implementation and quarkus extention for sqlite available below.

### Additional context

Java implementation of Sqlite available here - https://github.com/xerial/sqlite-jdbc/

Basic driver for Quarkus with Agoral and native mode support implemented by me here - https://github.com/alexeysharandin/quarkiverse-jdbc-sqlite and can be copied to quarkus repo.

If this driver will be interesting for Quarkus platform I'll work with Julien Viet/Thomas Segismont from Vert.x to implement reactive driver.

**Comment by maxandersen** [comment]
Definitely interesting and worth introducing in quarkiverse. 

Not sure sqlite is sql Compliant enough to standin for h2 but SQLite databases are everywhere especially on smaller devices so good fit for quarkus.

**Comment by alexeysharandin** [comment]
Yes, and native-image support provided by library out of the box - https://github.com/xerial/sqlite-jdbc/tree/master/src/main/resources/META-INF/native-image/org.xerial/sqlite-jdbc
From the Quarkus perspective - need only create quarkus JDBC extention(copy from my repo) and support one.

It's will be interesting for small devices or for some local/configuration storages in microservices apps.

**Comment by gastaldi** [comment]
I wonder if https://github.com/xerial/sqlite-jdbc/ is still actively maintained given that the last commit happened on Oct 2021 and there are plenty of opened PRs there 😬

**Comment by gastaldi** [comment]
@alexeysharandin there you go: https://github.com/quarkiverse/quarkus-jdbc-sqlite

I have prepared a checklist you can follow after the repository is created: https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created

Have fun!
