### ISSUE TITLE
Gradle extension plugin suggests incorrect DSL update when the deployment extension is not found

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#25567]
### Describe the bug

This code in [QuarkusExtensionPlugin.java](../tree/2.8.3.Final/devtools/gradle/gradle-extension-plugin/src/main/java/io/quarkus/extension/gradle/QuarkusExtensionPlugin.java) fires when the Gradle plugin runs in the "runtime" module and cannot find the "deployment" module:
```java
    private Project findDeploymentProject(Project project, QuarkusExtensionConfiguration configuration) {
// snip
            if (deploymentProject == null) {
                project.getLogger().warn("Unable to find deployment project with name: " + deploymentProjectName
                        + ". You can configure the deployment project name by setting the 'deploymentArtifact' property in the plugin extension.");
            }
// snip
    }
```
It should instead suggest "deploymentModule" because further up in the same method it is actually calling `getDeploymentModule`:
```java
    private Project findDeploymentProject(Project project, QuarkusExtensionConfiguration configuration) {

        String deploymentProjectName = configuration.getDeploymentModule();
        if (deploymentProjectName == null) {
            deploymentProjectName = DEFAULT_DEPLOYMENT_PROJECT_NAME;
        }
// snip
        return deploymentProject;
    }
```

### Quarkus version or git rev

2.8.3.Final

### Additional information

I did not fill the rest of the form out as I feel the bug is self-explanatory. If more detail or a reproduction is required let me know.

**Comment by glefloch** [comment]
Nice catch it used to named deployment artifact in the past. I will rename it.
