### ISSUE TITLE
ClassLoader cannot load non-static resource

### ISSUE THREAD

**Issue by jie-huang** [quarkusio/quarkus#25570]
### Describe the bug

1. Just create a normal Quarkus project with grade
2. Using grade to create a properties file by adding below codes into build.gradle
```
task createMyProps(type: WriteProperties) {
    outputFile = file("${buildDir}/resources/main/dynamic.properties")
    encoding = "UTF-8"
    
    property("dynamic_key", "dynamic value")
}

processResources {
  dependsOn createMyProps
}
```
3. Add a file resources/main/static.properties with content "static_key=static value"
4. Try to access the files
```
  @GET
  @Path("/static")
  @Produces(MediaType.TEXT_PLAIN)
  public String readStatic() throws IOException {
    InputStream is = Thread.currentThread().getContextClassLoader().getResourceAsStream("/static.properties");
    Properties props = new Properties();
    props.load(is);
    return props.toString();
  }

  @GET
  @Path("/dynamic")
  @Produces(MediaType.TEXT_PLAIN)
  public String readDynamic() throws IOException {
    InputStream is = Thread.currentThread().getContextClassLoader().getResourceAsStream("/dynamic.properties");
    Properties props = new Properties();
    props.load(is);
    return props.toString();
  }
```
5. run the project `Quarkus dev`

Expected: both /static and /dynamic should work correctly
Result: /static works correctly. /dynamic failed because is is null.

I checked the generated .jar file. Both static.properties and dynamic.properties are in the correct position.

BTW, if I add `quarkus.native.resources.includes=dynamic.properties` into application.properties, /dynamic works.

My questions is, since both static.properties and dynamic.properties are in the correct position in the jar file (it should be treated as the classes), `quarkus dev` should pick up it correctly.

### Expected behavior

both /static and /dynamic should work correctly

### Actual behavior

 /static works correctly. /dynamic failed because is is null.

### How to Reproduce?

Just follow the upper description

### Output of `uname -a` or `ver`

Darwin sd-lmc-1a8902 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

OpenJDK Runtime Environment (build 18+36-2087)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by geoand** [comment]
Please attach a sample project that exhibits this behavior.

Thanks

**Comment by glefloch** [comment]
@jie-huang, I built a reproducer following steps you mentioned above. Everything work, both endpoints return the content of the file. I tested with both the CLI and `gradle quarkusDev`, do you have a reproducer that shows the error ?

**Comment by jie-huang** [comment]
@glefloch Thanks for the confirmation. I tried to reproduce. But this time it works.
I thought that may relate to cache at that time since I used getClass().getResourceAsStream() at beginning.
Later I changed to Thread.currentThread().getContextClassLoader().getResourceAsStream.

Sorry about it.
