### ISSUE TITLE
Use short-circuit operators when possible

### ISSUE THREAD

**Issue by clara0** [quarkusio/quarkus#25581]
### Description

Short-circuit operators don't check the second condition if the value of first one already determines whether the whole statement is true/false, meaning they are more efficient.

- ClassScanResult:
`ret.compilationHappened = m1.compilationHappened | m2.compilationHappened;`
- ResteasyViolationExceptionMapper:
```
if (e != null | restEasyException.getReturnValueViolations().size() != 0) {
        // This is an internal error: handle through the QuarkusErrorHandler,
        // which will return HTTP status 500 and log the exception.
        throw restEasyException;
}
```

However, the second condition in the if statement for ResteasyViolationExceptionMapper seems to have intended side 
effects that require the method to be run regardless of whether the entire statement is true or false, so I have only changed ClassScanResult in my pull request.

**Comment by geoand** [comment]
Closing this as `won't fix`
