### ISSUE TITLE
Use a particular field of a Class as CacheKey

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#25588]
### Description

I have a method having an Class as parameter. The documentation says the following
- If the method has no arguments, then the cache key is an instance of io.quarkus.cache.DefaultCacheKey built from the cache name.
- If the method has exactly one argument, then this argument is the cache key.
- If the method has multiple arguments but only one annotated with @CacheKey, then this annotated argument is the cache key.
- In all other cases, the cache key is an instance of io.quarkus.cache.CompositeCacheKey built from multiple method arguments (annotated with @CacheKey or not).

I would like to be able to use just one single field of the class as a CacheKey

### Implementation ideas

If a method is annotated with @CacheName, I could be able to have an annotation @CacheKey("name_of_parameter.name_of_field_in_class") where the parameter of the method is named "name_of_parameter" of type Clazz and it has a field  "name_of_field_in_class" that will be used as cache key or in the Class of name_of_parameter Clazz, I could place the annotation @CacheKey on the field name_of_field_in_class so that it can automatically by used as a cache key when passed to a method annotated with @CacheName.

That would be helpful.

**Comment by geoand** [comment]
Hi,

Thanks for reporting. Although I see the rationale behind this, I would like to see some real world examples of what you have in mind. Mind adding some?

**Comment by gwenneg** [comment]
This may be possible with https://github.com/gwenneg/quarkus/pull/209 which I really need to finish 😃

**Comment by dwamara** [comment]
> Hi,
> 
> Thanks for reporting. Although I see the rationale behind this, I would like to see some real world examples of what you have in mind. Mind adding some?

Sure because I have need of this feature all the time :-) most of all for updates : I normally put object in the cache when I do a GET with only a "code" as parameter, using that "code" as the cache key. It works fine.
When I want to do an update, I pass a form with different properties and one of the properties is the "code" (I don't like to use RestForm because a form could have 6 or 10 properties, that will pollute my method's arguments).
In my code, I will use the "code" to retrieve the object from the database, update it and save it. But AFAIK I have no mean to remove that particular element from the cache and make an update out of it in the cache so normally I just empty the whole cache...
As the method will have only one argument (see bullet #2), the Cache key will be that argument, my form object, some magic will happen to make a key out of it that will be unique.
If I call the same method with the same form for the same database object (meaning the same "code") on which I would like to do a new update, I would have loved to invalidate only that object from the cache using the "code" and not invalidate the whole cache, update and put it back in the cache.
Hum, is it understandable?
I also would like to have the mean to put the object in the cache after I have created it (in a create method earlier) before returning it to the user and not wait for the first @GET to be able to do it.

**Comment by geoand** [comment]
> Hum, is it understandable?

Sort of, but some pseudo code would also be very helpful :)

**Comment by dwamara** [comment]
:-) Let me make it simple by putting real code
here I retrieve the candidate and put him in the cache
```	
        @GET
	@Path("{code}")
	@CacheResult(cacheName = "candidates-cache")
	public GatewayResponse retrieve(@PathParam("code") final String code) {
		var action = (this.getClass().getSimpleName() + "." + getInstance().walk(frames -> frames.findFirst().map(StackWalker.StackFrame::getMethodName)).get());
		logEntry(LOGGER, applicationName, action, code);
		var timer = registry.timer(applicationName + "." + action);
		return timer.record(() -> {
			GatewayResponse response;
			try {
				final var candidate = ofNullable(Candidate.findByCode(code)).orElseThrow(() -> new GatewayException("CND-404", format("Candidate with code '%s' not found", code)));
				response = new GatewayResponse.Builder().withEntity(candidate).build(FOUND);
			} catch (GatewayException exc) {
				response = new GatewayResponse.Builder().withException(exc).build(NOT_FOUND);
			}

			logExit(LOGGER, applicationName, action, code, response.entity != null ? response.entity : response.errorMessage);
			return response;
		});
	}
```
Here is how the CreateCandidate/UpdateCandidate class looks (not yet reactive, I know...)
```
public class CreateCandidate {
	@FormParam("code") public String code;
	@FormParam("name") public String name;
	@FormParam("picture") public byte[] picture;
	@FormParam("description") public String description;
	@FormParam("adherence_code") public String adherenceCode;
	@FormParam("adherence_name") public String adherenceName;
	@FormParam("adherence_logo") public byte[] adherenceLogo;

	public String toString() {
		return create().toJson(this);
	}
}
```
And here is how my update method looks like
```
	@PUT
	@Consumes(MULTIPART_FORM_DATA)
	@CacheInvalidateAll(cacheName = "candidates-cache")
	public GatewayResponse update(@MultipartForm UpdateCandidate request) {
		var action = (this.getClass().getSimpleName() + "." + getInstance().walk(frames -> frames.findFirst().map(StackWalker.StackFrame::getMethodName)).get());
		logEntry(LOGGER, applicationName, action, request);
		var timer = registry.timer(applicationName + "." + action);
		return timer.record(() -> {
			GatewayResponse response;
			try {
				final var candidate = candidates.update(request);
				response = new GatewayResponse.Builder().withEntity(candidate).build(UPDATED);
			} catch (GatewayException exc) {
				response = new GatewayResponse.Builder().withException(exc).build(NOT_FOUND);
			}

			logExit(LOGGER, applicationName, action, request, response.entity != null ? response.entity : response.errorMessage);
			return response;
		});
	}
```
I would have loved to have something like this for example
```
	@PUT
	@Consumes(MULTIPART_FORM_DATA)
       @CacheInvalidate(cacheName = "candidates-cache", key="{request.code}")
	public GatewayResponse update(@MultipartForm UpdateCandidate request) {
		var action = (this.getClass().getSimpleName() + "." + getInstance().walk(frames -> frames.findFirst().map(StackWalker.StackFrame::getMethodName)).get());
		logEntry(LOGGER, applicationName, action, request);
		var timer = registry.timer(applicationName + "." + action);
		return timer.record(() -> {
			GatewayResponse response;
			try {
				final var candidate = candidates.update(request);
				response = new GatewayResponse.Builder().withEntity(candidate).build(UPDATED);
			} catch (GatewayException exc) {
				response = new GatewayResponse.Builder().withException(exc).build(NOT_FOUND);
			}

			logExit(LOGGER, applicationName, action, request, response.entity != null ? response.entity : response.errorMessage);
			return response;
		});
	}
```
Or 
```
public class CreateCandidate {
	@CacheKey @FormParam("code") public String code;
	@FormParam("name") public String name;
	@FormParam("picture") public byte[] picture;
	@FormParam("description") public String description;
	@FormParam("adherence_code") public String adherenceCode;
	@FormParam("adherence_name") public String adherenceName;
	@FormParam("adherence_logo") public byte[] adherenceLogo;

	public String toString() {
		return create().toJson(this);
	}
}
```

**Comment by gwenneg** [comment]
Did you try to combine `@CacheInvalidate(cacheName = "candidates-cache")` and `@CacheResult(cacheName = "candidates-cache")` on the same method to update the cached value? This will first remove the old entry from the cache and then compute a new entry by executing the method.

**Comment by geoand** [comment]
Thanks for taking the time to post the use case, very useful!

I personally think this is a useful feature, WDYT @gwenneg?

**Comment by gwenneg** [comment]
Cache keys definitely need something more flexible than the current possibilities. That's why I started https://github.com/gwenneg/quarkus/pull/209 (draft on my fork) which allows to build the key from almost anything. I'm pretty sure it could work in that case.

```java
public class UpdateCandidateKeyGen implements CacheKeyGenerator {
    @Override
    public Object generate(Method method, Object... methodParams) {
        return ((UpdateCandidate) methodParams[0]).code;
    }
}
```

```java
@PUT
@Consumes(MULTIPART_FORM_DATA)
@CacheInvalidate(cacheName = "candidates-cache", keyGenerator = UpdateCandidateKeyGen.class)
public GatewayResponse update(@MultipartForm UpdateCandidate request) {
    // Same body than above
}
```

**Comment by dwamara** [comment]
> Did you try to combine `@CacheInvalidate(cacheName = "candidates-cache")` and `@CacheResult(cacheName = "candidates-cache")` on the same method to update the cached value? This will first remove the old entry from the cache and then compute a new entry by executing the method.

No and I don't think it would work as the UpdateCandidate request is always different, so the cache key will also be different and how will I get the right Candidate from the cache in my retrieve method as I wouldn't know which key it has been cached with?

**Comment by gwenneg** [comment]
You would need to pass the code in a separate method param alongside with the UpdateCandidate param, assuming you know it from the client side at update time.

**Comment by dwamara** [comment]
This is feasible, I also thought and used it but my thinking was "why put a parameter in my call when I already have it in the Object?". For me the less parameters I can have the better.
