### ISSUE TITLE
[resteasy-reactive] unrecognized configuration key "quarkus.security.jaxrs.deny-unannotated-endpoints"

### ISSUE THREAD

**Issue by PhilippParis** [quarkusio/quarkus#25591]
### Describe the bug

when using `resteasy-reactive` in combination with the configuration `quarkus.security.jaxrs.deny-unannotated-endpoints` quarkus prints an "unrecognized configuration key" warning on startup
altough the configuration is recognized and works as expected.

when using resteasy-classic, no such warning is printed

### Expected behavior

quarkus starts without "unrecognized configuration key" warning

### Actual behavior

warning on startup:

`Unrecognized configuration key "quarkus.security.jaxrs.deny-unannotated-endpoints" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### Quarkus version or git rev

2.9.0-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.0 Maven home: /usr/share/maven Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64

**Comment by geoand** [comment]
@radcortez to fix this, we would need a new build item that would remove items from `unknownBuildProperties` in `BuildTimeConfigurationReader`. If that is acceptable, I can open a PR

**Comment by radcortez** [comment]
Hum, do we have a different rule or behaviour for this particular configuration property between classic and reactive?

**Comment by geoand** [comment]
No, the issue with this is that we have the exact same configuration class for both RESTEasy Classic and Reactive, but we cannot have a Quarkus config class for both, because otherwise an application that mixes RESTEasy Classic and Reactive will get errors that are totally non-actionable (as opposed to now, where there is a great error message stating that the two can't be mixed).

**Comment by radcortez** [comment]
Ah, I see this here:
https://github.com/quarkusio/quarkus/blob/4094b4f616d9413abff9dd10b75a82b69b9577bf/extensions/resteasy-reactive/quarkus-resteasy-reactive-common/deployment/src/main/java/io/quarkus/resteasy/reactive/common/deployment/ResteasyReactiveCommonProcessor.java#L76-L80

Do we have something that prevents double mapping in the ConfigRoot? Can't remember, I'll have to check. I don't see a reason for that. Did you tried that before? Did you got an error? Do you remember?

**Comment by geoand** [comment]
The exception looks something like:

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Multiple matching properties for name "security.jaxrs.deny-unannotated-endpoints" property was matched by both public boolean io.quarkus.resteasy.reactive.common.runtime.JaxRsSecurityConfig.denyJaxRs and public boolean io.quarkus.resteasy.runtime.JaxRsSecurityConfig.denyJaxRs. This is likely because you have an incompatible combination of extensions that both define the same properties (e.g. including both reactive and blocking database extensions)
```

(an example reported can be found [here](https://github.com/quarkusio/quarkus/issues/20688))

**Comment by radcortez** [comment]
I understand that we would add the build step to remove such cases. I'm just not sure if this is something that we want to add since it will create an exception to our current configuration rules.

I'm wondering if we should lift the restriction of the double mapping. I believe it should be ok. I think it is perfectible acceptable for different extensions to refer to the same configuration names (especially considering that you can get the values programmatically anyway).

**Comment by geoand** [comment]
> I'm wondering if we should lift the restriction of the double mapping. I believe it should be ok. I think it is perfectible acceptable for different extensions to refer to the same configuration names (especially considering that you can get the values programmatically anyway).

In sounds fine in theory :)

**Comment by radcortez** [comment]
Ok, I'll have a look into this.

**Comment by geoand** [comment]
👍🏼

**Comment by radcortez** [comment]
Lifting the `@ConfigRoot` restriction for the double mapping requires some work (because internally, the backing classes do not support it). `@ConfigMapping` does not have that restriction, so I use that instead to avoid the warnings.
