### ISSUE TITLE
MP rest client interfaces do not support MP FT annotations

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2560]
SmallRye FT implementation is using an additional interceptor binding `@HystrixCommandBinding` to bind `HystrixCommandInterceptor` to all bean clasess that declare an MP FT annotation (such as `@Fallback`). In order to make it work SM FT portable extension adds `@HystrixCommandBinding` to [all FT annotations](https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java#L66-L71) and since interceptor bindings are transitive it works as expected.

However, quarkus does not support transitive interceptor bindings yet and so the `HystrixCommandInterceptor` is not bound to the following rest client interface:
```java
@RegisterRestClient
interface MyClient {

        @Fallback(MyFallback.class)
        @GET
        @Path("/data")
        JsonArray get();
    }
```
WORKAROUND: annotate the rest client with `@HystrixCommandBinding` (this annotation comes from SM FT).

I think we should support transitive interceptor bindings.

**Comment by mkouba** [comment]
@manovotn Would you care to take this one? ;-)

**Comment by manovotn** [comment]
Alright, I'll give it a go.
