### ISSUE TITLE
Oidc client does not support the property org.eclipse.microprofile.rest.client.propagateHeaders

### ISSUE THREAD

**Issue by xiaolong2015** [quarkusio/quarkus#25604]
### Description

We have a kubernetes cluster with the following components:
+ keycloak
+ a service based on quarkus which uses a keycloak-client to communicate with the keycloak

We use Jaeger to trace our requests. We can not configure the quarkus oidc client to propagate the tracing headers to the keycloak. So our traces are broken on the token requests.

It will be very helpful that the oidc client can propagate the tracing headers.

**Comment by sberyozkin** [comment]
@xiaolong2015 Hi, the wildcard propagation of the request headers is not a secure option. I doubt `quarkus-oidc-client` can do such kind of propagation of some headers it is not aware of, it is beyond its core concern. So you'd like the incoming headers be propagated not only to the downstream endpoint but to Keycloak itself, but I'm not sure this is what this property is about, i.e it is about `client->endpointA->endpointB` and the headers flowing from `client` to `endpointB` but not to every other destination which might be called on the route from `endpointA` to `endpointB` - the headers destined for endpoint B will be visible everywhere.

**Comment by sberyozkin** [comment]
I agree it would be useful to trace oidc client calls though and such traces can be shown as the independent traces but in scope of the outer traces from endpoint A to endpoint B, IMHO it would be a correct approach

**Comment by johgoe** [comment]
Maybe something similar like "org.eclipse.microprofile.rest.client.propagateHeaders" so the special headers for tracing like
  'x-request-id',  'x-b3-traceid',  'x-b3-spanid',  'x-b3-parentspanid',  'x-b3-sampled',  'x-b3-flags',  'x-ot-span-context' can be propagated

**Comment by sberyozkin** [comment]
This headers propagation is facilitated with RestEasy server/client code cooperation, OidcClient is Vertx Client based. it can't access headers available in the RestEasy context
