### ISSUE TITLE
Json serialization error with Kotlin 

### ISSUE THREAD

**Issue by mmaryo** [quarkusio/quarkus#25618]
### Describe the bug

Hello 

I return a simple data object in Kotlin 

And this error appears 

```
Request failed: kotlinx.serialization.SerializationException: Serializer for class 'Trade' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

I use the last version of Kotlin, Java and Quarkus 
Built the project from here https://code.quarkus.io/

Please find a zip with an example 

[Api.zip](https://github.com/quarkusio/quarkus/files/8706841/Api.zip)

You can run `http://localhost:8080/trades/1` and see the result 

Best 

### Expected behavior

No error

### Actual behavior

an error 

### How to Reproduce?

just run the server  `http://localhost:8080/trades/1`

**Comment by geoand** [comment]
Is there a reason you are using both Jackson and Kotlin serialization? You should be using one or the other

**Comment by mmaryo** [comment]
No reason, I thank it is the thing to do 
What should I choose ?

**Comment by geoand** [comment]
You'll need to study Jackson vs Kotlin Serialization to see what fits your needs

**Comment by geoand** [comment]
Jackson is certainly more widely used. Hard to comment on the other questions.

**Comment by mmaryo** [comment]
thank you

**Comment by geoand** [comment]
👍🏼

**Comment by mmaryo** [comment]
but kotlin is fastest 
https://litote.org/kmongo/performance/
do you try to remove jackson?
it still not working for me
