### ISSUE TITLE
Build failure when using many OpenApi anotations

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#2561]
**Describe the bug**
We have an application with ~10 endpoints, each one have CRUD+List operations and they are extensively documented with:
`@Operation`
`@RequestBody` (when it makes sense)
`@APIResponse` (at least 5 different ones for OK and error conditions)
`@Parameter` (when it makes sense)

We Also use:
`@OpenAPIDefinition` and `@Schema` on 20+ DTOs and their fields.

The build fails with the error bellow. After commenting a few annotations, the build passed again.

**Expected behavior**
`mvn clean install` works

**Actual behavior**
`mvn clean install` fails with the following error:

Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.**MethodTooLargeException**: Method too large: io/quarkus/deployment/steps/SmallRyeOpenApiProcessor$build16.deploy (Lio/quarkus/runtime/StartupContext;)V

Full stack trace:
[stack-trace.txt](https://github.com/quarkusio/quarkus/files/3208187/stack-trace.txt)

**To Reproduce**
See bug description... Basically, add a lot of OpenApi annotations. 

**Environment (please complete the following information):**
brunobat@sagan:/devel/projects/talkdesk/wfm-core$ mvn -version
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T19:41:47+01:00)
Maven home: /devel/tools/apache-maven-3.6.0
Java version: 11.0.2, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/jdk-11.0.2+9
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-50-generic", arch: "amd64", family: "unix"

**Comment by machi1990** [comment]
A dup of #2498? https://github.com/quarkusio/quarkus/pull/2550 was proposed to fix the issue. 

@brunobat could you please try with a clean build of the master to see if it solves the issue?

**Comment by brunobat** [comment]
@machi1990 Do you mean build quarkus master, change my project dependency and see if it fixes the issue?

**Comment by machi1990** [comment]
> @machi1990 Do you mean build quarkus master, change my project dependency and see if it fixes the issue?

Hey @brunobat Yes, that's what I meant. 

Sorry, I could have been more clear in my message.

**Comment by brunobat** [comment]
Thanks @machi1990 . I've tested my code with your master and it works well. You guys rock! looking forward for next release!

**Comment by machi1990** [comment]
> Thanks @machi1990 . I've tested my code with your master and it works well. You guys rock! looking forward for next release!

Good to hear that it solves your issue. Do not hesitate to flag it as `duplicate`  and to close the issue. 

The next release 0.16.0 is planned for the 29/05.  Stay tuned :-)
