### ISSUE TITLE
Resteasy reactive - Missing builditem ?

### ISSUE THREAD

**Issue by mcanzerini** [quarkusio/quarkus#25621]
### Describe the bug

I am upgrading my extension to quarkus 2.9.0 and migrating to resteasy reactive. 

Some of existing builditems in resteasy classic do not exist anymore in reactive implementation. I was using ResteasyJaxrsProviderBuildItem to record an Exception Mapper and a ClientRequestFilter.

### Actual behavior

For my Exception Mapper, I use now an ExceptionMapperBuildItem without any problem. But for my ClientRequestFilter, I do not know which builditem i have to choose (there is no such ClientRequestFilterBuildItem)

### Quarkus version or git rev

2.9.0

**Comment by geoand** [comment]
Good point, reopening

**Comment by geoand** [comment]
So, we don't have a build item for that, because the client providers are supposed to be registered via `@RegisterProvider`

**Comment by mcanzerini** [comment]
Ok thanks it works.
Just to be sure: the app which uses my extension will have to add the `@RegisterProvider` on the RestClient and the filter will be registered ?

**Comment by geoand** [comment]
Correct
