### ISSUE TITLE
UUID id is not supported for MySQL

### ISSUE THREAD

**Issue by annaazizova** [quarkusio/quarkus#25637]
### Describe the bug

I've got an error on row.getUUID("id"):
java.lang.UnsupportedOperationException: Can not retrieve row value[11c7160e-d629-11ec-a153-0242ac160002] as class[java.util.UUID], columnName=[id]
Please bump vertx-sql-client version at least to 4.2.3 version instead of 4.2.2 to support UUID (https://github.com/eclipse-vertx/vertx-sql-client/pull/1109).

### Expected behavior

UUID successfully retrieved from row

### Actual behavior

java.lang.UnsupportedOperationException: Can not retrieve row value[11c7160e-d629-11ec-a153-0242ac160002] as class[java.util.UUID], columnName=[id]

### How to Reproduce?

row.getUUID("id")

**Comment by geoand** [comment]
What version of Quarkus are you seeing this in?

Quarkus `2.9.1.Final` uses Vert.x `4.2.6`.

**Comment by annaazizova** [comment]
I use 2.6.2.Final, I just need an upgrade then, thank you!

**Comment by avivmu** [comment]
I'm still getting this
```
CREATE TABLE IF NOT EXISTS testing_uuid
(
    id BINARY(16) NOT NULL,
    PRIMARY KEY (id)
);
```
```
Can not retrieve row value[0c592601-9a7f-448a-8959-cdd4b4cd9a62] as class[java.util.UUID], columnName=[id]
java.lang.UnsupportedOperationException: Can not retrieve row value[0c592601-9a7f-448a-8959-cdd4b4cd9a62] as class[java.util.UUID], columnName=[id]
```
quarkus 3.8.3
