### ISSUE TITLE
`quarkus.webauthn.relying-party.icon` should be removed or deprecated

### ISSUE THREAD

**Issue by ynojima** [quarkusio/quarkus#25676]
### Description

From Quarkus 2.9.0, security-webauthn introduced `quarkus.webauthn.relying-party.icon` configuration property as a preview feature.
But [W3C WebAuthn specification already deleted `icon` from `PublicKeyCredentialEntity`](https://github.com/w3c/webauthn/pull/1337), and no browsers support the icon option, the configuration property should be removed or deprecated.

**Comment by geoand** [comment]
cc @FroMage @sberyozkin

**Comment by FroMage** [comment]
@pmlopes any opinion on this?

**Comment by pmlopes** [comment]
Yes, remove it. in vert.x auth we need to do a sync with the level-2 spec (current release) and remove it too.
