### ISSUE TITLE
Swagger-UI spec validation cannot be disabled

### ISSUE THREAD

**Issue by timbrueckner** [quarkusio/quarkus#25681]
### Describe the bug

I am using the OpenAPI extension in my application and I include the bundled `swagger-ui` in my deployment. I want to disable the spec validation of swagger-ui. I am using the YAML-based configuration, by the way.

```xml

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-config-yaml</artifactId>
</dependency>
```

And I configured swagger-ui like this:

```yaml
quarkus:
  swagger-ui:
    always-include: true
    validator-url: none
```

The docs of the extension mention the following:
> [quarkus.swagger-ui.validator-url](https://quarkus.io/guides/openapi-swaggerui#quarkus-swaggerui_quarkus.swagger-ui.validator-url)
By default, Swagger UI attempts to validate specs against swagger.io’s online validator. You can use this parameter to set a different validator URL, for example for locally deployed validators (Validator Badge). Setting it to either none, 127.0.0.1 or localhost will disable validation.

However, when I run the application, it still renders the validation badge. Setting the value to `localhost` or `127.0.0.1` didn't work either. When I run the app in development mode locally, the validation seems disabled. The badge does not appear.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/510849/169298508-202a9d68-ff6c-4b27-9abb-cb758f0e964d.png">

### Expected behavior

The spec validation is disabled when the value of `validator-url` is set to either `none` or `localhost` or `127.0.0.1`.

### Actual behavior

The validation is executed despite those values being set.

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by phillip-kruger** [comment]
@timbrueckner do you perhaps have a small reproducer ? I did not manage to recreate the issue and `quarkus.swagger-ui.validator-url=none` is working for me.

**Comment by timbrueckner** [comment]
@phillip-kruger We can close this issue. I just noticed, the property was missing in the `application.yaml` file used to build the application. It was only present on the file mounted into the docker container, but it is a config property, which is fixed at build time. Thanks for taking the time to dig into the issue. Sorry, I didn't notice that earlier.
