### ISSUE TITLE
Add support for logging async handler

### ISSUE THREAD

**Issue by Sparow199** [quarkusio/quarkus#2568]
**Description**
async-handler
Defines a handler which writes to the sub-handlers in an asynchronous thread. Used for handlers which introduce a substantial amount of lag. 

**Implementation ideas**
I tried to implement this feature in my [fork](https://github.com/Sparow199/quarkus/commit/1d79a3be33ac768c105760d0c211d7a1d8cbd50f) based on log rotation integration (Work in progress). 
I'm waiting for your feedbacks.
Thanks

**Comment by dmlloyd** [comment]
What handler would require wrapping with the async handler?

**Comment by Sparow199** [comment]
Console and File handlers. It's disabled by default and could be enabled via configuration properties.  This improves the application’s performance because it allows the application to not have to wait for the logging subsystem to complete the action.

**Comment by Sparow199** [comment]
I'm agree with you that's optional, but it's could be interesting to give the developers this feature.
