### ISSUE TITLE
Gradle integration tests mischaracterize "FROM-CACHE" as a failure when caching is enabled

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#25693]
### Describe the bug

When the Gradle cache is enabled, the Gradle integration tests fail when a Gradle task is run and returns "FROM-CACHE" as its status, because the test is looking for the "SUCCESS" string. The "FROM-CACHE" means that Gradle recognizes the build environment and the task inputs and had enough confidence to reuse the task outputs from the last run.

This issue is low priority, in my opinion, as it is somewhat cosmetic, and it only happens if incubating features are used.

In my opinion, there's two ways to think about this:
- You do not have confidence (yet?) in Gradle's caching abilities, and don't want to invest in supporting it just yet. This is fair; Gradle's cache has been reliable _for me_ but that's by no means proof that it's working as intended for these tests.
- Gradle's caching of these tests could be checked to make sure there are no issues, then the tests could be fixed to accept the "FROM-CACHE" status result, even if not enabled by default.

### Expected behavior

The integration tests pass.

### Actual behavior

Some of the integration tests fail, reporting that the Gradle status "FROM-CACHE" does not equal "SUCCESS".

### How to Reproduce?

Steps to reproduce:
1. Append "org.gradle.caching=true" to ~/.gradle/gradle.properties (possibly also is fine to place in "integration-tests/gradle/gradle.properties" file as well)
2. Run `./mvnw -Dquickly && ./mvnw -f integration-tests/gradle/ install`

### Output of `uname -a` or `ver`

Linux jacob-ubuntu-dev 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)

### Quarkus version or git rev

3bd0588c1c53bd0bf303bde40cac74ba78482680 (or, main as of this morning)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by glefloch** [comment]
Nice catch, I will update that in tests.
