### ISSUE TITLE
Quarkus for embedded systems

### ISSUE THREAD

**Issue by alexeysharandin** [quarkusio/quarkus#25700]
### Description

Hi,
I'm not sure what is interesting because targed for Quarkus is cloud native but let's discuss because this feature already implemented by me year ago for JVM/Native modes and need to add only Quarkus integration.
 
**Disclaimer:**
I will deliberately simplify the description of feature to better undersanding of community because embedded systems it's separated world.

**Intro:**
at this moment all embedded systems devided by 2 big groups - simple devices (like teapot) with small chipsets(like STM32*) and something like RTOS on board and more poverfull devices with Linux(OpenWRT, Armbian, Android, etc). In second group I can include your home router/repeater, mobile phone, drone and a lot of other devices).
To better undersanding of these devices - good example is Raspberry Pi.
"Old school" guys can understand what hardware in RPI4 more powerfull what we have in enterprise servers 10-15 years ago :) (it's if you want to ask question about java and performance).

Technically Oracle tried to intoduce embedded in J2ME and in https://openjdk.java.net/projects/dio/ but both projects was hardcoded to specific hardware and looks like dead at this moment.

**What will be implemented:**
Access to [SPI bus](https://en.wikipedia.org/wiki/Serial_Peripheral_Interface)
Access to [I2C bus](https://en.wikipedia.org/wiki/I%C2%B2C)
Access to [Serial(USB/COM/etc)](https://en.wikipedia.org/wiki/Serial_communication)
in JVM/native without any dependency to vendor hardware. Library will re-use linux drivers for HW.

Limitation:
Only Linux platforms[tested in Raspberrian/Armbian/Ubuntu in Broadcom/Allwinner chipset at this moment].

Is it interesting?
I propose to implement this feature in quarkiverse project

**Comment by maxandersen** [comment]
Definitely sounds interesting!

**Comment by aloubyansky** [comment]
@alexeysharandin you mentioned that you already implemented something, is it available somewhere for us to look into? Thanks.

**Comment by alexeysharandin** [comment]
@aloubyansky, yes. It's available(only native part not published). You can start read from here - https://habr.com/ru/post/580368/
I know what we have 2 parallel projects - pi4j and diozero but both of them going over the same way what Oracle did before. Hardcode to hardware and hardware offsets and a lot of JNI code for this.

I selected different way - integrate with POSIX directly over JNA for JVM mode and over org.graalvm.nativeimage.c.* for native. It's give me ability to work with any hardware what supported by linux drivers.

**Comment by alexeysharandin** [comment]
BTW: What is current status of this extention will be:
1. Core part for SPI/I2C/Serial - already implemented
2. Need to add some Quarkus features. Like beans/configs and etc to simplify work with API.

I'll be lead maintainer for this extention.

**Comment by gastaldi** [comment]
Interesting indeed. Any ideas on how should this extension be called? `quarkus-embedded` seems too generic to me 😉

**Comment by alexeysharandin** [comment]
@gastaldi I think it's will be parent...

Currently functionality devided by:
linux-core module - where POSIX interfaces implemened + JVM mode
linux-native-core module - where graalVM native-image implementation for POSIX

additionally will be runtime/deployment added for quarkus... 

Technically it's "door to direct access from Java to Linux or POSIX " and implementation for interfaces from first post only small part how this API can be used.

But... all these interface - "serial" and maybe something "quarkus-lowlevel-serial-access" will be fine at this moment.
I tried to add bluetooth support for this library (what wireless instead of serial) but [BlueZ](http://www.bluez.org/) API kills me...

I think at this moment something like "quarkus-lowlevel-serial-access" will be okey... If someone will have a plant to reuse or add POSIX access functions - we can extract part of this library to something like "quarkus-posix" or "quarkus-posix-access" and re-use in this one.

**Comment by aloubyansky** [comment]
For those looking for the code repo it's https://github.com/java-embedded-framework/jef

**Comment by maxandersen** [comment]
If it's to enable jef in quarkus maybe start with quarkus-jef as name ?

**Comment by maxandersen** [comment]
I see the jef readme mentions only commercial graalvm works - is that true / still a limit today ?

**Comment by alexeysharandin** [comment]
@maxandersen 
Initially I has a plans to close JEF repo and move all code to Quarkus with Apache2.0.
But If Quarkus community prefer to keep old repo for code and create integration with quarkus - not a problem to change license and add native part to same repo. but in this case need help from George or someone else to implement automatization in JEF repo for auto-publish to maven.

**Comment by alexeysharandin** [comment]
BTW: Initially it's release over dual-licensed and it's means what for Quarkus licence will be changed to Apache2.0

**Comment by gastaldi** [comment]
@alexeysharandin out of curiosity: is the https://github.com/java-embedded-framework/jef repository maintained solely by yourself at the moment? 

It's really up to you to decide about moving these sources to the new Quarkiverse repository (with whatever name we come up with). The main driver of this decision is if the code you'll maintain is meant to be Quarkus only. 

I'd recommend keeping the core functionality in a separate repository (as you have now) with independent releases and having a Quarkiverse extension depending on this core functionality.

But that's me, let me know what you would like to do and let me know how I can help 😉

**Comment by maxandersen** [comment]
> I see the jef readme mentions only commercial graalvm works - is that true / still a limit today ?
> 

Curious to know the above ?

**Comment by alexeysharandin** [comment]
@maxandersen ,
to make long story short: from today(21.05.2022) licence changed to Apache2.0 and repo updated.
Native part will be uploaded in github in some time(need to retest few function before in SVM21.+)

**Comment by alexeysharandin** [comment]
@gastaldi,
>> out of curiosity: is the https://github.com/java-embedded-framework/jef repository maintained solely by yourself at the moment?
yes.

>> It's really up to you to decide about moving these sources to the new Quarkiverse repository (with whatever name we come up with). The main driver of this decision is if the code you'll maintain is meant to be Quarkus only.
Not right :) repo separated by modules and these modules can be used as part of quarkus or separatly.

>> I'd recommend keeping the core functionality in a separate repository (as you have now) with independent releases and having a Quarkiverse extension depending on this core functionality.
For me both options fine. If possible to add some CI to publish to maven in current repo - it's fine for me (I give you rights).
Options with coping all sources to quarkiverse - fine too. Nothing will be changed from functions perspective in "classic java mode" only additional modules for quarkus integration will be added.

**Comment by gastaldi** [comment]
> Not right :) repo separated by modules and these modules can be used as part of quarkus or separatly.

Sure, my point is that the artifacts produced in the Quarkiverse repository must start with the group ID `io.quarkiverse`, and probably that doesn't make much sense for the code that's not specific to Quarkus Maven-wise.

**Comment by maxandersen** [comment]
> @maxandersen ,
> 
> to make long story short: from today(21.05.2022) licence changed to Apache2.0 and repo updated.
> 
> Native part will be uploaded in github in some time(need to retest few function before in SVM21.+)

So this is no longer reliant on graalvm enterprise features ?

**Comment by alexeysharandin** [comment]
@maxandersen,
library never depends on graalvm enterprise features before. I used CE features to build native-image what available in public MVN but not documented in Graal at this moment.

**Comment by gastaldi** [comment]
@alexeysharandin in order to publish to Maven central, you need to create a JIRA ticket in the OSSRH Sonatype JIRA for your groupId: check https://central.sonatype.org/publish/publish-guide/#initial-setup for more information.

**Comment by aloubyansky** [comment]
I don't see an issue including the core library in a quarkiverse repo, assuming there are no current users, if it makes it easier to evolve the extension. It could be extracted later, if necessary.

**Comment by gastaldi** [comment]
I'll create a `quarkus-jef` repository then and we can evolve from that

**Comment by alexeysharandin** [comment]
@aloubyansky Thanks Alexey. I'm about the same. 
@gastaldi Many thanks.
