### ISSUE TITLE
starts slowly

### ISSUE THREAD

**Issue by acliufan** [quarkusio/quarkus#25723]
### Describe the bug

Hi Team,

My application is built with Installed features: Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, resteasy-mutiny, servlet, smallrye-context-propagation, spring-data-jpa, spring-di, spring-web, vertx].

I packaged the quarkus project with native *.exe mode. And I registered the quarkus service as a Windows 10 startup self startup service, and the startup time of the service is almost 30s every time I restart the computer.

However, at this time, when I restart the service again in windows10 Task Manager, the startup time is still very short, which is at the millisecond level.

I configure the log level to trace, and I can probably locate the cause of the problem that the log file between the first line and the second line  is almost 10s.The first line of log is printed before the run () of the project startup class.

Trace is already the most fine-grained log. I don't know what quarkus has done in this time. Why does it take so long?
Content of the problem log file is as follows,More detailed logs are in the module[Additional information].
-----------------------
2022-05-23 15:52:21,060 desktop-g8tdbba NativeImageGeneratorRunner$JDK9Plus[1000] INFO  [com.sup.mar.AreLogApplication] (main) starting...
2022-05-23 15:52:31,651 desktop-g8tdbba NativeImageGeneratorRunner$JDK9Plus[1000] TRACE [com.arj.ats.common] (main) Loading class com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple
-----------------------

### How to Reproduce?

Every time I restart the computer,It will reproduce.

### Output of `java -version`

Java Version 11.0.14+9-jvmci-22.0-b05

### GraalVM version (if different from Java)

GraalVM 22.0.0.2

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

<groupId>io.quarkus.platform</groupId><artifactId>quarkus-maven-plugin</artifactId><version>2.7.3.Final</version>

### Additional information

[system.log](https://github.com/quarkusio/quarkus/files/8753389/system.log)

**Comment by acliufan** [comment]
The config of my application is as follows:
server.ip=127.0.0.1
quarkus.http.host=0.0.0.0
quarkus.http.port=18300

custom.level.my.log=TRACE
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${server.ip}:5432/fusionsite_are_log?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.log.level=${custom.level.my.log}
quarkus.log.console.enable=true
quarkus.log.console.level=${custom.level.my.log}

quarkus.log.file.async=true
quarkus.log.file.enable=true
quarkus.log.file.path=./logs/fusionsite-are-log.log
quarkus.log.file.level=${custom.level.my.log}
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.rotation.max-file-size=10240000
quarkus.log.file.rotation.rotate-on-boot=true
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.min-level=${custom.level.my.log}
quarkus.log.category."io.quarkus".level=${custom.level.my.log}
quarkus.log.category."io.quarkus.smallrye.jwt".level=${custom.level.my.log}
quarkus.log.category."io.undertow.request.security".level=${custom.level.my.log}
log.capacity=10000000

# JTA
# The timeout for transactions processing outbox events.
quarkus.hibernate-search-orm."persistence-unit-name".coordination.tenants."tenant-id".event-processor.transaction-timeout=30S
quarkus.transaction-manager.object-store-directory=./transaction/fusionsite-are-log.transaction
quarkus.transaction-manager.default-transaction-timeout=30S
quarkus.transaction-manager.node-name=fusionsite-are-log

**Comment by geoand** [comment]
Can start the application with `-Dquarkus.debug.print-startup-times=true` and report the result please?

**Comment by acliufan** [comment]
I put the `-Dquarkus.debug.print-startup-times=true` and  I find a warning message .
> WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.debug.print-startup-times" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo.

I found it on the Internet. It may be a problem with the quarkus version. So I upgraded the quarkus version to 2.9.1 Final.
However,I found that the warning is also exists.But there are more detailed log information and more time statistics.The result is as follows:
[add-startup-time.out.log](https://github.com/quarkusio/quarkus/files/8760283/add-startup-time.out.log)

**Comment by geoand** [comment]
You don't need to worry about the warning, it's a false positive.

**Comment by geoand** [comment]
For some reason your hardware seems to be performing very very poorly. The steps that are slow have no reason to be slow.

**Comment by geoand** [comment]
Closing, as this is certainly not a Quarkus issue.

**Comment by acliufan** [comment]
Thank you very much and I wish to consult you on a last question.
I used two computers. After the computer was restarted, the startup time of quarkus service was about 30 seconds, which was easy to reproduce.

Their configuration is as follows：
-------------------------------
- Host1
CPU:             Intel Xeon W-2104 CPU @ 3.20GHz
Cores:	    4
Threads:	    4
Memory:      dural 3200HZ 2*8 DDR4
Hard drives: TOSHIBA DT01ACA100 1T SATA-III 6.0Gb/s

- Host2
CPU:            I5 9500 @ 3.00GHz
Cores:	    6
Threads:	    6
Memory:      dural 2666HZ 2*8 DDR4
Hard drives: ST1000DM010-2EP102 1T SATA-III 6.0Gb/s
--------------------------------
This part `RuntimeConfigSetupBuildStep.setupRuntimeConfig` takes about 8 seconds and the `HibernateOrmProcessor.startPersistenceUnits` takes about 10 seconds.

I agree that my host configuration is really not high. If the service starts for the first time after the computer is restarted, is there a recommended configuration to reach the millisecond startup time you officially say?
