### ISSUE TITLE
@TestTransaction take no effect

### ISSUE THREAD

**Issue by BlackSharkCZE** [quarkusio/quarkus#25727]
### Describe the bug

In the @QuarkusTest with JUnit 5 in in the @Test method, annotation @TestTransaction does not rollback data from the database at the end of test when using io.quarkus.hibernate.reactive.panache

### Expected behavior

At the end of the @Test method, data from the database are removed (rollback).

### Actual behavior

Data stored in the database during @Test keep in the database.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8754028/code-with-quarkus.zip)
Extract simple app and run test more then once. Number of rows are increasing by 1 on every test run.

### Output of `uname -a` or `ver`

Linux jiri-hp360 5.15.38-1-MANJARO #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.15 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10) OpenJDK 64-Bit Server VM (build 11.0.15+10, mixed mode)

### Quarkus version or git rev

2.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

https://user-images.githubusercontent.com/2845869/169814269-018eecfa-84ee-4468-8440-8184507df4c6.mp4

**Comment by geoand** [comment]
You should be using `io.quarkus.test.TestReactiveTransaction` when working with Hibernate Reactive.
