### ISSUE TITLE
@JwtSecurity works with Resteasy Classic but stopped working with Resteasy Reactive

### ISSUE THREAD

**Issue by tonyherstell** [quarkusio/quarkus#25722]
### Describe the bug

@JwtSecurity(claims = { @Claim(key = "xxxxx", value = "XXXXXXXX") })

[https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JwtSecurity.20problem](url)

### Expected behavior

Claim is added to be used in a test

### Actual behavior

Claim ignored

### How to Reproduce?

[https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JwtSecurity.20problem](url)

**Comment by tonyherstell** [comment]
>>> Sergey Beryozkin[8:55 PM](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/JwtSecurity.20problem/near/283288429)
@Tony Herstell No, this annotation remains, so it works with Resteasy Classic but stopped working with Resteasy Reactive ? Can you open an issue please ?

**Comment by geoand** [comment]
Can you attach a sample project that exhibits the problematic behavior please?

**Comment by sberyozkin** [comment]
@tonyherstell I was not able to reproduce it, so please create a reporducer if you'd like this issue be revisited
