### ISSUE TITLE
Stork custom ServiceDiscovery doesn't work on Quarkus 2.8.0+

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25746]
### Describe the bug

Works as expected with Quarkus 2.7.5.Final and Stork 1.0.0

QuarkusVersion: 2.8.0 or Upstream
StorkVersion: [1.1.2](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L55)

Extensions: 
```
io.smallrye.stork:stork-core
io.smallrye.stork:stork-configuration-generator
```
Error: 
```
Fatal error compiling: java.lang.RuntimeException: Failed to generate configuration classes: Attempt to recreate a file for type io.quarkus.ts.stork.custom.SimpleConfiguration
```

Based on [this Doc](http://smallrye.io/smallrye-stork/1.1.2/load-balancer/custom-load-balancer/) looks like Quarkus stork property names has changed: 

Quarkus 2.7.5.Final + Stork 1.0.0
```
stork.pong.load-balancer=simple
stork.pong.service-discovery=simple
```

Quarkus  999-SNAPSHOT + Stork 1.1.2

```
quarkus.stork.pong.load-balancer=simple
quarkus.stork.pong.service-discovery=simple
```

But after update, my `application.properties` still don't work on Quarkus 2.8.0.Final+
MigrationGuideRef: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8#stork-extension-properties-config-moved-to-the-quarkus-namespace

Reproducer:
`git clone -b  feat/swapp_upstream git@github.com:pjgg/quarkus-test-suite.git`
`mvn clean verify -Dall-modules -pl service-discovery/stork-custom`

Note: be sure that module `service-discovery/stork-custom` is [not commented](https://github.com/pjgg/quarkus-test-suite/blob/feat/swapp_upstream/pom.xml#L368)

**Comment by geoand** [comment]
I would be great if you included a reproducer. The information in the ticket makes it hard to pinpoint the problem.

Thanks

**Comment by michalszynkiewicz** [comment]
The reason for the failure is that types for both SD and LB are set to `simple`. If you move one of the classes to a different package or change the type, it should work. 

Having said that, we should at least provide a more descriptive error message for it

**Comment by geoand** [comment]
> Having said that, we should at least provide a more descriptive error message for it

Actionable error messages should always be our goal :)

**Comment by pjgg** [comment]
Thank you @michalszynkiewicz !

Also, I notice some other minor "breaking changes" that I am going to comment on in this ticket (most of them are obvious but...):

Quarkus Stork 1.0.0 Vs Quarkus Stork 1.1.2 
----------------------------------------------------------------
### Application.properties
```
1.1.2: quarkus.stork.my-service.service-discovery.type=acme
1.0.0: stork.my-service.service-discovery=acme
```
Taking into account that now the keyword "type" is required

### Generated code
New config class names for generated configuration. 

On version 1.0.0 generated config from a custom load balancer or service discovery used to have the following generated name

Loadbalancer "simple"

```
@LoadBalancerType("simple")
public class SimpleLoadBalancerProvider implements ... 
```
Generated config: `SimpleLoadBalancerProviderConfiguration`

Version 1.1.2

Loadbalancer "simplelb"

```
@LoadBalancerType("simplelb")
public class SimpleLoadBalancerProvider implements ... 
```
Generated config: `SimplelbConfiguration`

### Services type name must be unique

On stork 1.0.0 was possible to have the same type name for different services: 

 ```
stork.pong.load-balancer=simple
stork.pong.service-discovery=simple
stork.pong-replica.load-balancer=simple
stork.pong-replica.service-discoverysimple
 ```

On Stork 1.1.2 load balancer and service discovery type must be unique (per service)

```
quarkus.stork.pong.load-balancer.type=simplelb
quarkus.stork.pong.service-discovery.type=simple
quarkus.stork.pong-replica.load-balancer.type=simplelb
quarkus.stork.pong-replica.service-discovery.type=simple
```

**Comment by cescoffier** [comment]
This is because of the config generation. 
To use the same name, you must have the load balancer provider and the service discovery provider in different packages.
