### ISSUE TITLE
Provide running context to `TestResource` implementations

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#25749]
### Description

Test resources currently don't have much in the way of knowing the context in which they execute. It could be interesting to provide more information to these so that they can adapt their processing based on the context. One particularly interesting bit of information would be whether or not the tests have failed.

For example, I've created an extension that creates a Kubernetes namespace before the tests run and destroy it when done. However, I'd like to be able to keep the namespace around for inspection in case the tests failed. This isn't currently feasible with the current framework.

Other information that could be interesting, though maybe not feasible due to the test resource lifecycle, would be test class name and method.

### Implementation ideas

Maybe that information could be provided via `QuarkusTestResourceLifecycleManager.Context` interface?

**Comment by geoand** [comment]
Wondering if the callback mechanism described in https://quarkus.io/guides/getting-started-testing#enrichment-via-quarkustestcallback would help you?

**Comment by geoand** [comment]
I'm not sure what is described in this ticket is the proper way to go (see my previous comment) but I'm interested in seeing what you came up with
