### ISSUE TITLE
Reactive Messaging (RabbitMQ) - Support Queue type and mode configuration

### ISSUE THREAD

**Issue by gpor0** [quarkusio/quarkus#25754]
### Description

RabbitMQConnectorIncomingConfiguration supports queue options (durable, exclusive, auto-delete,...) through the properties in the application configuration. Currently is not possible to define queue type, queue mode and other arguments when queue is being defined by the application through the RabbitMQ amqp-client queueDeclare method.

Please add an option to set missing properties for queue definition through the application configuration. Support:

x-queue-type: [quorum, classic, stream]
x-queue-mode: [lazy, default]
...

**Comment by cescoffier** [comment]
@kdubb is this one fixed with the latest SR RM release?

**Comment by kdubb** [comment]
No. This should be an enhancement added to SM RM.

Also, support should be through a freeform set of options as that's how it's passed to `queueDeclare`.

**Comment by ozangunalp** [comment]
This has been implemented in Reactive Messaging, released with version 3.20.0, and integrated in Quarkus since 2.14.0.Final.
