### ISSUE TITLE
Allow to put routes between the default route and RESTEasy

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#25759]
### Description

Currently the default route order (for static resources) is `DEFAULT_ROUTE_ORDER = 10000;`

RESTEasy classic and reactive are using `DEFAULT_ROUTE_ORDER + 1`, this doesn't let any other route in between in a consistant way. As the Integer space is pretty large, maybe a +1000 or +100 could allow a bit more flexibility.

The reason behind is that by default RESTEasy is a dead end route (without the ResumeOn404 option which is only in reactive) and some extensions might want to be in between and keep RESTEasy as a 404 handler.

**Comment by ia3andy** [comment]
Currently in Quinoa using `DEFAULT_ROUTE_ORDER + 1` the route is placed just before RESTEasy, but I guess it depends on the order in which the extension are processed so it's not very reliable right?  @geoand any thought?

**Comment by ia3andy** [comment]
Currently the only way (hack) to be in between the default route and RESTEasy is to use the same order as RESTEasy, my question is to know if somehow that's reliable. As explain the right fix would be to change the RESTEasy route order but it's not trivial because of the side effect it could have.

**Comment by geoand** [comment]
I don't think it's reliable, but I haven't checked.

You can always try and change the RESTEasy Route order and see if CI is happy
