### ISSUE TITLE
Possibility to customize JAX-B Marshaller in quarkus-resteasy-reactive-jaxb

### ISSUE THREAD

**Issue by j-be** [quarkusio/quarkus#25753]
### Description

Currently, the `JaxbMessageBodyWriter` from `quarkus-resteasy-reactive-jaxb-common` uses `javax.xml.bind.JAXB.marshal()` to marshal objects to XML. There is no way to customize the marshaller, apart from forking the whole extension and replacing `JaxbMessageBodyWriter` all together.

So if for example I'd need to change the `Marshaller.JAXB_FORMATTED_OUTPUT` property, I have no easy way of doing so.

### Implementation ideas

I see a couple of ways how this could be done, each with its own pros and cons:

* provide settings for properties and pass them via `javax.xml.bind.Marshaller.setProperts(String, Object)`
* some SPI/Injection based approach would allow to provide own implementations of the `javax.xml.bind.Marshaller`, which could offer more flexibility then a simple `setProperty` based approach, but most probably at the cost of complexity
* an annotation based approach (e.g. via `org.jboss.resteasy.spi.DecoratorProcessor`) would have the benefit of being able to even provide different marshallers for the various resources, but may add even more complexity
* make it easier to extend and replace the default `JaxbMessageBodyWriter` implementation, e.g. by introducing a `protected Marshaller createMarshaller(JaxbContext context)` or `protected void marshal(Object, OutputStream)`, and a setting to replace the default `JaxbMessageBodyWriter` by any class extending it

**Comment by geoand** [comment]
cc @Postremus who did the `quarkus-resteasy-reactive-jaxb` extensions

**Comment by Sgitario** [comment]
I did the `quarkus-resteasy-reactive-jaxb` extension, so I will implement this by following the same approaches as done in the Jackson extension +1

**Comment by geoand** [comment]
Ah, it was @Postremus who proposed it, my bad.

Thanks @Sgitario !

**Comment by Postremus** [comment]
yep, Sgitario did the extension, I proposed it and did a review.
