### ISSUE TITLE
Quarkus-cli 2.8.2.Final create app doesn't include test examples with just a jacoco extension

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25761]
### Describe the bug

Quarkus 2.8.2.Final and also Upstream (999-SNAPSHOT)
Worked as expected with Quarkus 2.7.5.Final

Quarkus-cli 2.8.2.final doesn't add a `quarkus-resteasy` extension by default, so if I create an application with just `jacoco` extension then I don't have a test folder. I am not sure if this could be an issue? 

Reproducer: 
1. create an app with jacoco extension
`quarkus create app app -x=jacoco`

2. build your app
`quarkus build`

3. Verify is a jacoco folder was created
```
ls target 
app-1.0.0-SNAPSHOT.jar  classes  generated-sources  maven-archiver  maven-status  quarkus-app  quarkus-artifact.properties
```
No jacoco report was generated because there is no test folder/examples.

**Comment by gsmet** [comment]
Yes, we are not forcing a REST implementation on the users anymore IF they specify at least an extension.
If they want one, they need to specify it.

If they don't specify any extension, they end up with a RESTEasy Reactive example.

**Comment by geoand** [comment]
Should this be closed?

**Comment by pjgg** [comment]
Ok, got it! thank you @gsmet
