### ISSUE TITLE
Dynamic Keycloak Policy Enforcer for multi-tenancy

### ISSUE THREAD

**Issue by ansonquarkus** [quarkusio/quarkus#25774]
### Description

Support creating keycloak authorization policy dynamically

**Comment by albert0815** [comment]
Hi @sberyozkin,

I am currently planning to create a multi tenant application with dynamic tenants. Using the OIDC TenantConfigResolver works to configure the tenants for authentication. Based on the documentation and this issue I assume that nothing similar exists for the authorisation using policy enforcer. Is there any plan to also build a dynamic solution for the policy enforcer? And maybe you could help recommending how to deal with this in the meantime.

Thanks

**Comment by michalvavrik** [comment]
#39643 makes it possible through alternative and priority CDI annotations, though I would strongly encourage you to stick with dynamic tenant config resolution as I find it more practical.
