### ISSUE TITLE
Custom resource started in tests that are not annotated with `@QuarkusTestResource`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#25782]
### Describe the bug

I have a custom resource that uses test containers to start needed components for the integration tests:

`class StargateTestResource implements QuarkusTestResourceLifecycleManager, DevServicesContext.ContextAware `

This is then used as:

```
@QuarkusTest
@QuarkusTestResource(StargateTestResource.class)
class ExampleResourceIntegrationTest
```
In the maven, the `*/*IntegrationTest` classes are excluded from the `maven-surefire-plugin`. Thus they are not run as part of the `test` phase:

```
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
          <excludes>
            <exclude>**/*IntegrationTest.*</exclude>
            <exclude>**/*EndToEndTest.*</exclude>
          </excludes>
        </configuration>
      </plugin>
```      

Thus, although these tests are not running in the `test` phase, the resource seems to be started. Seems that starting the resource is done even if no test that will run is annotated with the `@QuarkusTestResource`. 

The same thing happens even when starting a single test from the IDE that does not have the `@QuarkusTestResource` at all. Seems that the trigger is the `@QuarkusTest` annotation. 

### Expected behavior

Don't start the resource for the test that does not have the `@QuarkusTestResource` annotation.

### Actual behavior

Resource started for every test annotated with `@QuarkusTest`, no matter if resource annotation exists or not.

### Quarkus version or git rev

2.9.1.Final

**Comment by geoand** [comment]
As mentioned in the [documentation](https://quarkus.io/guides/getting-started-testing#quarkus-test-resource), `@QuarkusTestResource` are **global** resources (this was likely a mistake, but it would be too costly to change this behavior).

f you want to only enable a test resource on a single test class or test profile, you can use `@QuarkusTestResource(restrictToAnnotatedClass = true)`.

**Comment by ivansenic** [comment]
> 

Thanks @geoand

**Comment by geoand** [comment]
No problem!

**Comment by geoand** [comment]
BTW, I you have any questions regarding your Quarkus investigation for stargate, feel free to reach out :)

**Comment by ivansenic** [comment]
> BTW, I you have any questions regarding your Quarkus investigation for stargate, feel free to reach out :)

Thanks.. But I think we are over the investigation phase.. Our V2 APIs are gonna be based on Quarkus :)

**Comment by geoand** [comment]
Then my offers stands for the implementation :)
