### ISSUE TITLE
Jackson support

### ISSUE THREAD

**Issue by tomerz90** [quarkusio/quarkus#2578]
It would be great to have Jackson support (also for native image) to be able to use Jackson directly to serialize and deserialize Java objects using Jackson's `ObjectMapper`

**Comment by Dufgui** [comment]
Hello, I think you can use yasson for this, no?
It's added by jsonb extension:
https://github.com/quarkusio/quarkus/blob/master/extensions/jsonb/runtime/pom.xml#L19
and according to the yasson readme:
https://github.com/eclipse-ee4j/yasson
you can use their mapper:
```
Jsonb jsonb = JsonbBuilder.create();
String result = jsonb.toJson(someObject);
```
Could you try like this ?

**Comment by tomerz90** [comment]
Yes I could, my problem is I have an application that I wanted to migrate to Quarkys but it makes heavy use of Jackson and replacing Jackson is not an option currently

**Comment by Dufgui** [comment]
I try to create extension without changing anything and it seems working without doing anything. 
https://github.com/Dufgui/quarkus/tree/2578_jackson
https://github.com/Dufgui/quarkus-quickstarts/tree/2578_jackson

What error have you experimented in native ? Could you provide the substrat log ?

**Comment by tomerz90** [comment]
I didnt try it yet, I just assumed that since it wasnt in the extension list its not supported, I'll close this issue for now then and re-open if I'll run into problems.
Thanks!

**Comment by Dufgui** [comment]
ok ;)

**Comment by ChristopheMaldivi** [comment]
Hi @Dufgui ,
Basically I have the same question : how to use jackson instead of json-b (yasson).
It is mainly because yasson will fail to deserialize a json where some fields are missing (I did not find a way to do that with yasson). Jackson can do it quite simply (if the field is not found, it will initialize it with null).
To get `quarkus-restasy` use jackson, I've done the following so far:
```
<!-- FIXME: FORCE JACKSON, replace it with quarkus-jackson if available -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.jboss.resteasy</groupId>
          <artifactId>resteasy-json-binding-provider</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.resteasy</groupId>
          <artifactId>resteasy-json-p-provider</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-jsonb</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-jackson2-provider</artifactId>
      <version>4.1.0.Final</version>
    </dependency>
```

For sure I would prefer to use your `quarkus-jackson` extension, but is seems that it has not been merged in the main tree.
Do you plan to get it integrated, or could you advise me another way to solve my problem?

Thanks a lot for your help.

**Comment by ancgate** [comment]
@ChristopheMaldivi,

I was having the error JSON Binding serialization error java.lang.StackOverflowErrorError with quarkus. I have applied your fixed and I no longer have this issue anymore.

**Comment by matejbizjak** [comment]
ObjectMapper works just fine in Quarkus, even in native mode. Just add **quarkus-resteasy-jackson** dependency and use it normally. But make sure you attach **@RegisterForReflection** annotation to every class you need for serialization and deserialization to make it work in native mode!

[Check Quarkus documentation here](https://quarkus.io/guides/rest-json-guide#more-on-our-jackson-support)

**Comment by machi1990** [comment]
Hi @ancgate , on top of @matejbizjak suggestion (thanks :-)), I'll suggest to upgrade to the latest version `0.20.0` if it not already the case.
