### ISSUE TITLE
Ambiguous Module Name for quarkus-security

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#25795]
### Describe the bug

io.quarkus:quarkus-security and io.quarkus.security:quarkus-security artifacts share the same automatic module name.

This make it extremelly painful to customize security features in a modularized application (I was trying to extend HttpAuthenticationMechanism which use classes from both modules).

With gradle I was able to do it with the following config for the moduleplugin:
```
modularity.patchModule("quarkus.security", "quarkus-security-2.9.1.Final.jar")

compileJava {
    moduleOptions {
        addExports = ['quarkus.security/io.quarkus.security.runtime': 'yourModule']
    }
}
```

### Expected behavior

HttpAuthenticationMechanism  can be extended without additional configuration

### Output of `java -version`

17

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by sberyozkin** [comment]
Not sure what can be done now, @aloubyansky, @stuartwdouglas, can you recommend something apart from for example, renaming  `io.quarkus.security:quarkus-security` to `io.quarkus.security:quarkus-security-core` or something like that (which probably won't happen) ?

**Comment by stuartwdouglas** [comment]
We could maybe rename it to `quarkus-security-api`

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, `quarkus-security-api` sounds good

**Comment by rmanibus** [comment]
> @sberyozkin yeah I think this would be the proper solution. Also the hot reload is completely broken with this setup. I guess when quarkus recompile it does not take in account the module related options passed by gradle to javac.

@sberyozkin should I open another issue for that ? or is it a known problem ? I can't find anything about it in the github issues.

**Comment by maxandersen** [comment]
@sberyozkin is there something blocking us for doing this rename + relocation of artifacts?

**Comment by sberyozkin** [comment]
Closing as duplicate as we have a newer issue: #40417
