### ISSUE TITLE
CDI.current().select(...) fails due to bean class being loaded in both RuntimClassLoader and Launcher$AppClassLoader

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#2579]
**Describe the bug**
In working on a fix for #2528 , I have run into an issue where a request scoped bean is being loaded by two different class loaders and this causes a CDI.current().select(SecurityContextPrincipal.class) query to fail.

**Expected behavior**
The code is similar to what the smallrye-jwt extension is doing to provide a java.security.Principal producer, so I expected similar behavior.

**Actual behavior**
The SecurityContextPrincipalHandler fails to select the SecurityContextPrincipal:
```
javax.enterprise.inject.UnsatisfiedResolutionException
	at io.quarkus.arc.InstanceImpl.get(InstanceImpl.java:93)
	at io.quarkus.elytron.security.runtime.SecurityContextPrincipalHandler.handleRequest(SecurityContextPrincipalHandler.java:22)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at 
...
```

**To Reproduce**
1. git clone https://github.com/starksm64/quarkus.git starksm64-quarkus
2. cd starksm64-quarkus
3. git checkout bugs
4. mvn install

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Scotts-iMacPro:deployment starksm$ uname -a
Darwin Scotts-iMacPro 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
Scotts-iMacPro:deployment starksm$ $JAVA_HOME/bin/java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode

 - GraalVM version (if different from Java): 
Scotts-iMacPro:deployment starksm$ echo $GRAALVM_HOME
/Users/starksm/Dev/JBoss/Protean/graalvm-ce-1.0.0-rc16/Contents/Home

**Additional context**
You can rerun the failing test by going into the starksm64-quarkus/extensions/elytron-security/deployment directory and running:
mvn clean test -Dtest=io.quarkus.security.test.BasicAuthTestCase#testJaxrsInjectedPrincipalSuccess

The target/quarkus.log is configured to use TRACE level logging. I have added a trace log check to the BeanTypeAssignabilityRules class where I traced the CDI select failure to:

```java
    private static boolean matches(Class<?> requiredType, Class<?> beanType) {
        boolean matches = requiredType.equals(beanType);
        if (!matches && log.isTraceEnabled() && requiredType.getName().equals(beanType.getName())) {
            StringBuilder tmp = new StringBuilder("requiredType.CL: ");
            tmp.append(requiredType.getClassLoader());
            tmp.append("\nbeanType.CL: ");
            tmp.append(beanType.getClassLoader());
            log.tracef("Failed to match classes(%s), ClassLoaders: %s", requiredType.getName(), tmp);
        }
        return matches;
    }
```
In the quarkus.log I am finding that the SecurityContextPrincipal bean class has been loaded by both the sun.misc.Launcher$AppClassLoader and the io.quarkus.runner.RuntimeClassLoader:
```
22:33:28 TRACE [io.qu.ar.BeanTypeAssignabilityRules]] (executor-thread-1) Failed to match classes(io.quarkus.elytron.security.runtime.SecurityContextPrincipal), 
ClassLoaders: requiredType.CL: sun.misc.Launcher$AppClassLoader@75b84c92
beanType.CL: io.quarkus.runner.RuntimeClassLoader@8458f04
```

**Comment by stuartwdouglas** [comment]
This is not a bug, but an issue with the new code. In particular:

- The AdditionalBeanBuildItem is not actually produced
- The test should not include SecurityContextPrincipal in the test archive

I have some fixes at: https://github.com/stuartwdouglas/quarkus/commit/c098540758021f98a3262dc6c34d66a231189a99
