### ISSUE TITLE
Important log message shown during Dev Services for Keycloak initialization is lost

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#25809]
### Describe the bug

Not sure it is a bug, as I recall there was an issue related to some of the dev services related to the excessive logging.

But in any case, I recall it was possible to see various log messages logged by `KeycloakDevServicesProcessor` but now it is all being collapsed and all I see is 
```
--
2022-05-26 12:38:41,657 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-37) Dev Services for Keycloak started.
```

For example, `KeycloakDevServicesProcessor` logs if it can not find the configured realm file [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L457), but it is not visible and the user has just spent a lot of time trying to figure out what went wrong in his replica of the `keycloak-authorization` quickstart which proved to be caused by a missing realm file.

I'm not sure throwing the exception in case of a missing realm would be a good dev experience given that one way to fix it is to go to Keycloak Admin UI from DevConsole and import a realm there if one sees a message that no realm is found. 

### Expected behavior

I think the messages logged by various Dev Services processors themselves (such as `KeycloakDevSericesProcessor`) should be visible, while the test containers logging can indeed be collapsed to minimize the noise. 

### How to Reproduce?

Go to the `security-keycloak-authorization-quickstart` in quarkus-quickstarts and change path to the realm to point to a non-existent location. `mvn quarkus-dev` will fail with error caused by the fact DevServices for Keycloak did not import it but no log message informing the user that the realm is missing will be shown

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas I've looked at the code and I'm not sure I see how some log messages can be selectively shown in the console, what do you think ?

**Comment by iocanel** [comment]
I was affectected by the issue myself. I had no way of knowing what is going on and I had to actually debug to get an idea.

Some options that could make for a better developer experience:

- If a realm is explicitly provided by the user, but failed to apply for wahtever reason, should result in an Exception. 
- Provide an option that disable the log message removal. Also log a message informing the user about this option.

Any of the above will save significant amount of time from users and will make for a way better experience than we currently have.

**Comment by sberyozkin** [comment]
Hi @iocanel I agree with the first point, my original thinking was, in devmode, one just continues by clicking on `Keycloak Admin` and continues dealing with realms there, importing them, etc, but the experience shows, that indeed, not failing early just causes problems.
Though thinking a bit more about it, if we see an error log message that for ex REAL json is malformed, then the user goes ahead, updates the realm, `DevServices for KC` is already checking the file modification date so it should restart and retry to upload the realm. This flow may fit better into the dev mode style of working...
I propose that we try to see first what can be done with controlling the log messages :-)

**Comment by iocanel** [comment]
Sounds good to me.

**Comment by gsmet** [comment]
I created a PR for it here: https://github.com/quarkusio/quarkus/pull/28533 .

Not sure if it actually do what you expect but if you want it to be non fatal, I think it's the way to go.
If you want to switch to more fatal errors, then this PR should show you when to adjust the errors and throw exceptions.
