### ISSUE TITLE
Vert.x Context doesn't get propagated when using Infrastructure.getDefaultWorkerPool()

### ISSUE THREAD

**Issue by luneo7** [quarkusio/quarkus#25818]
### Describe the bug

Vert.x Context doesn't get propagated when using `Infrastructure.getDefaultWorkerPool()`

Whenever you use reactive programming and you run Mutiny with `runSubscriptionOn(Infrastructure.getDefaultWorkerPool()` Vert.x context doesn't get propagated, whereas with `Infrastructure.getDefaultExecutor()` does get propagated.

This impacts OpenTelemetry, MDC and any other people/feature that uses Vert.x context for something, since context data is stored inside Vert.x Context and it doesn't get propagated.

### Expected behavior

Using `Infrastructure.getDefaultWorkerPool()` with Mutiny should behave the same as with `Infrastructure.getDefaultExecutor()` and Vert.x Context should be set

### Actual behavior

Using `Infrastructure.getDefaultWorkerPool()` Vert.x Context is null

### How to Reproduce?

_OPENTELEMETRY IS ONLY BEING USED AS AN EXAMPLE AND REPRODUCER, THE ISSUE IS NOT RESTRICTED TO IT_

https://github.com/luneo7/opentelemetry-reproducer

Just run `./mvnw clean test` and you will see that Vert.x Context doesn't get propagated so OTEL span doesn't have the right parent id when using worker pool.

When doing `curl http://localhost:8080/hello-worker-pool` you will see that two distinct spans are created:

![Screenshot 2022-05-26 at 13-44-28 Jaeger UI](https://user-images.githubusercontent.com/8834774/170560638-da8f5389-9729-42a7-a3bb-a58aa015fbd2.png)

When doing `curl http://localhost:8080/hello-default-executor` you will see that the spans are created correctly and there are two spans that correlates to each other:

![Screenshot 2022-05-26 at 13-46-38 Jaeger UI](https://user-images.githubusercontent.com/8834774/170561015-3141edfe-58d8-466b-a563-766b7c9f9131.png)

### Quarkus version or git rev

2.9.2.Final

**Comment by luneo7** [comment]
For what I see, it is a design flaw, the executor that Quarkus uses is the EnhancedQueueExecutor (https://github.com/jbossas/jboss-threads/blob/main/src/main/java/org/jboss/threads/EnhancedQueueExecutor.java) it has a context handler that is set to get the current Vertx context. But SmallRye Infrastructure. getDefaultWorkerPool() uses a MutinyScheduler that wraps the EnhancedQueueExecutor and it is a ScheduledThreadPoolExecutor, the EnhancedQueueExecutor just fetches the context when the task is about to run, not when you submit the task to the executor, so when/where the task is actually run in the MutinyScheduler the vertx context doesn't exists, thus it is always null, and it doesn't get propagated.


So, that is what happens when you use Infrastructure.getDefaultWorkerPool(), when the task is run the context is null, so nothing is propagated =]
<img width="1271" alt="Screen Shot 2022-05-26 at 9 51 52 AM" src="https://user-images.githubusercontent.com/8834774/170561332-51eb8786-61aa-48dc-8a85-74e43818951c.png">
<img width="1332" alt="Screen Shot 2022-05-26 at 9 52 12 AM" src="https://user-images.githubusercontent.com/8834774/170561366-0533c050-3460-4e32-95e5-ff40416aff63.png">

**Comment by luneo7** [comment]
The way that I got `Infrastructure.getDefaultWorkerPool()` to work was to create a `VertxContextProvider.java`

```
package org.acme.opentelemetry;

import io.vertx.core.Context;
import io.vertx.core.Vertx;
import io.vertx.core.impl.ContextInternal;
import org.eclipse.microprofile.context.spi.ThreadContextProvider;
import org.eclipse.microprofile.context.spi.ThreadContextSnapshot;

import java.util.Map;

public class VertxContextProvider implements ThreadContextProvider {

    @Override
    public ThreadContextSnapshot currentContext(Map<String, String> props) {
        Context context = Vertx.currentContext();
        return () -> {
            Context currentContext = Vertx.currentContext();
            if (context != null && currentContext == null) {
                final ContextInternal vertxContext = (ContextInternal) context;
                vertxContext.beginDispatch();
                return () -> vertxContext.endDispatch(null);
            }
            return () -> {};
        };
    }

    @Override
    public ThreadContextSnapshot clearedContext(Map<String, String> props) {
        return () -> () -> {};
    }

    @Override
    public String getThreadContextType() {
        return "Vertx";
    }
}
```

And later create a `src/main/resources/META-INF/services/org.eclipse.microprofile.context.spi.ThreadContextProvider` file with `org.acme.opentelemetry.VertxContextProvider`

With this class the Vertx context gets propagated with smallrye context propagation... since the `currentContext` method is called in the calling thread and not in the executor thread =]

Don't know the approach that you guys want to take either fixing the scheduler/queue executor, use the thread context provider, something else, or even if you guys want `Infrastructure.getDefaultWorkerPool()` to propagate Vert.x Context...

**Comment by jponge** [comment]
We've noted the issue, it's under investigation

**Comment by jponge** [comment]
@luneo7 I've investigated `Infrastructure.getWorkerPool()` and indeed callback decorators wouldn't be activated.

Since there are more moving pieces than Mutiny but also Quarkus and various context-support bits could you please check a locally-built 999-SNAPSHOT of the following draft in your code? https://github.com/smallrye/smallrye-mutiny/pull/954

Thanks! 🙏

**Comment by jponge** [comment]
Note that the PR impacts 2 modules for which you'll have to enforce `999-SNAPSHOT` from a `mvn install`:

- mutiny
- mutiny-smallrye-context-propagation

**Comment by luneo7** [comment]
Still think it has something to do with `EnhancedQueueExecutor`, since the `contextHandler` there that is propagating the Vert.x Context... So this is the contextHandler set by `VertxCoreRecorder`

<img width="729" alt="image" src="https://user-images.githubusercontent.com/8834774/173882710-a1119a51-3b84-4a47-8d7c-47f6df9a30c4.png">

When using the default executor that code is run and `context` is not null, and when running with the worker pool, it is null, just because when/where context handler is executed (inside the `EnhancedQueueExecutor`'s `execute` method) the vertx context doesn't exists... 

Screenshot of it running with worker pool:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/8834774/173884292-9713daa2-ad27-4780-b356-863b61b5d724.png">

Screenshot of it running with default pool:

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/8834774/173884973-395f0550-6e78-44db-9e29-480b754e371e.png">

**Comment by jponge** [comment]
Did you forget to enable an extension?

```
2022-06-15 19:28:08,828 WARN  [io.qua.res.com.dep.ResteasyCommonProcessor] (build-7) Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. Reactive REST endpoints in your application that return Uni or Multi will not function as you expect until you add this extension. Endpoints that need Mutiny are: org.acme.opentelemetry.TracedResource{io.smallrye.mutiny.Uni<java.lang.String> helloWorkerPool()}, org.acme.opentelemetry.TracedResource{io.smallrye.mutiny.Uni<java.lang.String> helloDefaultExecutor()}
```

**Comment by luneo7** [comment]
Nope, this is actually another bug in Quarkus where we are using `quarkus-resteasy-reactive` and not `quarkus-resteasy-mutiny` (https://github.com/quarkusio/quarkus/issues/16884 - this was closed but wasn't fixed)... just changing the pom to use `quarkus-rest-client-reactive` instead of `quarkus-rest-client` makes that warning vanish....

**Comment by jponge** [comment]
Ok we're going to dig other places.

BTW would you have a `docker-compose` configuration that works in `minikube`? I'm not on Linux and not using Docker Desktop, so I can't make the Jaeger/Otel containers work.

I'm using `minikube` as an easy Docker/K8s development environment as in:

- `minikube start`
- `eval $(minikube docker-env)`

**Comment by jponge** [comment]
@luneo7 We've had a look with @cescoffier and he's found a potential solution across the Mutiny and Quarkus code bases. I'll get back to you once I have PRs.

**Comment by luneo7** [comment]
What I thought was to actually remove the `contextHandler` from VertxCoreRecorder, and add a ThreadContextProvider that supports the Vertx context... that would make default and worker pool work out of the box (something like https://github.com/quarkusio/quarkus/issues/25818#issuecomment-1138934118)... the removal of context handler is just to not do the same thing two times

**Comment by jponge** [comment]
@luneo7 so here are 2 branches with the fix and an OTel-free reproducer

- https://github.com/smallrye/smallrye-mutiny/pull/955
- https://github.com/jponge/quarkus/tree/scratchpad/fix-mutiny-workerpool-integration

You can try on your side. This will require a new Mutiny release (likely next week) before the Quarkus branch can be turned into a PR.

**Comment by luneo7** [comment]
@jponge it did work =] the only downside that I see with that approach is that `DefaultExecutor` == `DefaultWorkerPool`, before the when running `.runSubscriptionOn(Infrastructure.getDefaultExecutor())` it would call the executor `execute` right away, and `.runSubscriptionOn(Infrastructure.getDefaultWorkerPool())` would call the scheduled thread pool executor (MutinyScheduler) that would schedule it to be run with 0 delay, it would go to the scheduled executor Q, and later it would call the delegated executor to run it, and now it behaves the same as the default executor, it won't schedule anything just will call the executor `execute` right away, and it wouldn't have any diff those two pools in essence, is that one approach that we want to take? Wouldn't there be any unforeseen side effects?

**Comment by cescoffier** [comment]
We want to avoid having to rely on context propagation.

**Comment by luneo7** [comment]
Makes sense, I was just wondering about the implication on having `DefaultExecutor` == `DefaultWorkerPool` so using `Infrastructure.getDefaultExecutor()` and `Infrastructure.getDefaultWorkerPool()` would yield in the same thing

**Comment by cescoffier** [comment]
From the Mutiny POV, the two polls are different. One is used to create a scheduled executor.
However, from the Quarkus POV, using the same "pool" is ok.

**Comment by luneo7** [comment]
If when setting the default executor you can actually pass an executor and a mutiny scheduler we could maintain the same behavior. In Quarkus we could extend the mutiny scheduler and in the schedule methods we would wrap the tasks with a context aware execution code, almost like what jboss enhanced queue executor does. If we do that all the schedule methods will be able to propagate the Vertx context and not only the execute method.

**Comment by jponge** [comment]
Mutiny needs a scheduled executor, but Quarkus isn't providing us with one (just a regular non-scheduled pool) so we need the hack of `MutinyScheduler` when receiving an _executor_ in the Mutiny `Infrastructure` class.

**Comment by luneo7** [comment]
Yup, so instead of using the same scheduled executor as default and worker pool, we could have a method in ’Infrastructure’ that accepts two parameters to set the default executors, one regular one and a scheduled one

**Comment by cescoffier** [comment]
it's what happens with the next mutiny release. If you pass a scheduled executor, it won't wrap it.

**Comment by luneo7** [comment]
Not really, what I am proposing is passing two arguments instead of one, a regular executor, and a scheduled one.

**Comment by cescoffier** [comment]
which will be done using 2 methods (like today). I don't see the point of introducing a breaking change for something we can workaround easily.

**Comment by luneo7** [comment]
This is what I was proposing: https://github.com/quarkusio/quarkus/compare/main...luneo7:mutiny-executors
https://github.com/luneo7/quarkus/tree/mutiny-executors

It is not a breaking change

**Comment by luneo7** [comment]
With that change ^ we can easily enable vertx context to be propagated in whole for the Scheduled Executor, and for the Default executor, the method overload will be compatible with the existing version, note that I added a `RemovedResourceBuildItem` in the mutiny processor just to not have to compile mutiny from source to test my changes.

But the changes in mutiny would be: 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/8834774/174635525-7d028b57-a2f7-4f9f-82e6-3644ce446f00.png">

And the rest of the changes in Quarkus, we would leverage the existing context handler build item to do context stuff in mutiny scheduler

**Comment by luneo7** [comment]
The only thing is that we are not fixing everything, the scheduled methods are all broken in the worker pool, just the execute method that is not... and we would also keep default executor != from scheduled executor... I can already reproduce another bug with the current approach... just try to schedule something with the Infrastructure worker pool, and the vertx context won't be propagated... 

This is also a simpler approach: https://github.com/quarkusio/quarkus/compare/main...luneo7:mutiny-executors-simple
