### ISSUE TITLE
Inconsistent deps for spring-web based app when using code.quarkus versus command line tooling 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#25822]
### Describe the bug

Inconsistent deps for spring-web based app when using code.quarkus versus command line tooling.

https://code.quarkus.io/?e=spring-web based application uses
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
```

`quarkus create app app -x=quarkus-spring-web` based application uses
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
```

I think `quarkus-resteasy-reactive-jackson` should be used in code.quarkus
`quarkus-resteasy-reactive-jackson` is defined in https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/spring-web-codestart/codestart.yml#L19

### Expected behavior

Consistent deps (quarkus-resteasy-reactive-jackson) for spring-web based app when using code.quarkus versus command line tooling.

### Actual behavior

Inconsistent deps for spring-web based app when using code.quarkus versus command line tooling.

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.9.2.Final

**Comment by ia3andy** [comment]
I've update quarkus core in code.quarkus.io, it is now fixed.
