### ISSUE TITLE
RESTEasy Reactive JsonGenerator not aware of jackson-datatype-jsr310 

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#25820]
### Describe the bug

Migrating from `quarkus-resteasy-jackson` to `quarkus-resteasy-reactive-jackson` breaks existing `JsonSerializer`.

This code ...
```
import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;

public class EchoCustomBeanSerializer extends JsonSerializer<EchoCustomBean> {

	@Override
	public void serialize(EchoCustomBean value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
		gen.writeStartArray();

		/*- Works for quarkus-resteasy-jackson but not for quarkus-resteasy-reactive-jackson. */
		gen.writePOJO(value.getTimestamp());

		/*- Works for both:
		  	serializers.defaultSerializeValue(value.getTimestamp(), gen);
		 */

		gen.writeString(value.getMessage());
		gen.writeEndArray();
	}

}
```
... is throwing this error:
```
io.quarkus.resteasy.reactive.jackson.runtime.mappers.NativeInvalidDefinitionExceptionMapper toResponse
ERROR: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
```
Worked OK with REASTEasy Classic.  Default serialization also works OK.  Workaround is to delegate to the `serializers` as commented in the example code.

### Expected behavior

Successful serialization.

### Actual behavior

Exception thrown.

### How to Reproduce?

Reproducer: [rest-reactive-jackson.zip](https://github.com/quarkusio/quarkus/files/8783033/rest-reactive-jackson.zip)

Run the `EchoServiceTest`.

### Quarkus version or git rev

2.9.2.Final

### Additional information

Although there is a workaround delegating to the `serializers`, this could be a significant effort across a large project and could be easy to miss cases if test coverage isn't 100%.

Of course I'm assuming that the existing code was spec compliant.  If it was only working by accident then the workaround is the solution.  Please advise if that's the case.

**Comment by geoand** [comment]
The commented version is the proper way to handle this
