### ISSUE TITLE
Can not set HTTP Header from ENV variable

### ISSUE THREAD

**Issue by EnriqueHernandezL** [quarkusio/quarkus#25833]
### Describe the bug

I tried to pass `quarkus.http.header."Cache-Control".value=no-cache` as a environmental variable to my Quarkus Server by setting `QUARKUS_HTTP_HEADER__CACHE_CONTROL__VALUE` as the variable name.

### Expected behavior

Expected server response

```
...
Cache-Control: no-cache
...
```

### Actual behavior

Actual server response

```
...
Cache.control: no-cache
...
```

### How to Reproduce?

Make a quarkus HTTP Server and try to set the described header as an environmental variable. Then `curl` the server.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by mschorsch** [comment]
CC @radcortez

**Comment by geoand** [comment]
Does `QUARKUS_HTTP_HEADER_CACHE_CONTROL_VALUE` work?

**Comment by mschorsch** [comment]
> Does `QUARKUS_HTTP_HEADER_CACHE_CONTROL_VALUE` work?

It doesn't work.

`QUARKUS_HTTP_HEADER__CACHE_CONTROL__VALUE` is correct. I think that the environment variable name does not contain enough information to convert `_` in `.` or `-`.
