### ISSUE TITLE
Project generator for amazon S3 extension is incorrect

### ISSUE THREAD

**Issue by nicolas-vivot** [quarkusio/quarkus#25872]
### Describe the bug

When using the Quarkus project configurer and selecting amazon S3 extension, the generated pom.xml is incorrect.

On the dependency management, both groupId and version are incorrect, refering to quarkus platform group id and version:
![image](https://user-images.githubusercontent.com/79290619/171068882-c31978fe-9555-4fa7-9ba4-4c2cd2e97bf8.png)

### Expected behavior

Expecting to be something like this instead:

```
<dependency>
          <groupId>io.quarkiverse.amazonservices</groupId>
          <artifactId>quarkus-amazon-services-bom</artifactId>
          <version>1.1.1</version>
          <type>pom</type>
          <scope>import</scope>
</dependency>
```

### How to Reproduce?

Just using the quarkus project configurer

https://code.quarkus.io/?e=io.quarkiverse.amazonservices%3Aquarkus-amazon-s3&extension-search=origin:platform%20amazon

**Comment by geoand** [comment]
cc @gastaldi @ia3andy

**Comment by aloubyansky** [comment]
That is correct actually. This extension is included in the platform. Extensions present in the platform should be accompanied by the platform BOMs to make sure they are transitive dependencies are properly aligned with other platform extensions.
Every platform member (Quarkus core, Camel, Kogito, etc) have their own BOMs but they get properly aligned in the platform and released under the `io.quarkus.platform` groupId.
