### ISSUE TITLE
Extension to generate Cert-Manager resources

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#25874]
### Description

From Dekorate 2.9.4 (unreleased yet), Dekorate will include a new module to generate the Cert-Manager artifacts (see https://dekorate.io/docs/cert-manager).
[Cert-Manager](https://cert-manager.io/) is an operator that generates certificates and issuers in Kubernetes/OpenShift.
Dekorate is already used by Quarkus to generate OpenShift and Kubernetes artifacts, so it would be great to have a new Quarkus Cert-Manager extension within the Quarkiverse to also generate the Cert-Manager artifacts.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion

Dekorate Cert-Manager module is fully configurable via properties. The Quarkus Cert-Manager extension would look like this:

```
dekorate.certificate.secret-name=tls-secret
dekorate.certificate.self-signed.enabled=true
```

Additionally, this extension will also configure the Quarkus application to enable SSL transparently to users, so they don't need to do anything else apart from configuring the Quarkus Cert-Manager properties.

**Comment by Sgitario** [comment]
Also, I'm interested in leading the development of this extension.

**Comment by geoand** [comment]
Very interesting. Given this is kinda niche, I think this would be more appropriate for Quarkiverse. WDYT @maxandersen ?

**Comment by maxandersen** [comment]
Are we sure its niche ? Wont certificate be necessary for Any inter Cluster https traffic ?

**Comment by geoand** [comment]
I am not, which is why I asked for your input :)

If this is a niche however, it would be easier to have this as a Quarkiverse extension first and then move to the core if it's important, rather than the other way around.
In any case, I don't have a strong opinion.

**Comment by Sgitario** [comment]
Any updates on this?

**Comment by Sgitario** [comment]
I think we need @gastaldi to create a new project for the Quarkus Cert-Manager extension in Quarkiverse. Can you help with that?

**Comment by gastaldi** [comment]
Sure, I can do that. How will it be called? `quarkus-cert-manager`?

**Comment by Sgitario** [comment]
> Sure, I can do that. How will it be called? `quarkus-cert-manager`?

+100
