### ISSUE TITLE
Misleading error for multipart non-blocking method in resteasy-reactive

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#25909]
### Describe the bug

Current implementation requires, that endpoint, which returns multipart, should be *blocking*. User is notified about it via build-time error, which says `Endpoints that produce a Multipart result can only be used on non blocking methods`.

### Expected behavior

Error message should describe behavior properly.

### Actual behavior

If endpoint annotated with both `@Produces(MediaType.MULTIPART_FORM_DATA)` and `@NonBlocking`, build fails with `Endpoints that produce a Multipart result can only be used on non blocking methods` error.

### How to Reproduce?

Add two endpoints to class:

```java
    @GET
    @Produces(MediaType.MULTIPART_FORM_DATA)
    @Path("/download-multipart")
    @Blocking //this will compile
    public Uni<FileWrapper> downloadMultipartBlocking() {
        FileWrapper wrapper = new FileWrapper();
        wrapper.file = file;
        wrapper.name = file.getName();
        return Uni.createFrom().item(() -> wrapper);
    }
```
and 
```java
    @GET
    @Produces(MediaType.MULTIPART_FORM_DATA)
    @Path("/download-multipart")
    @NonBlocking  //this will not
    public Uni<FileWrapper> downloadMultipartNonBlocking() {
        FileWrapper wrapper = new FileWrapper();
        wrapper.file = file;
        wrapper.name = file.getName();
        return Uni.createFrom().item(() -> wrapper);
    }
```

Build fails with the following error:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.6.Final:build (build) on project http-rest-client-reactive: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'io.quarkus.ts.http.restclient.reactive.files.FileResource#downloadMultipartNonBlocking'
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:294)
<...>
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Failed to process method 'io.quarkus.ts.http.restclient.reactive.files.FileResource#downloadMultipartNonBlocking'
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:666)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:382)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:265)
[ERROR] 	... 12 more
[ERROR] Caused by: javax.enterprise.inject.spi.DeploymentException: Endpoints that produce a Multipart result can only be used on non blocking methods. Offending method is 'io.quarkus.ts.http.restclient.reactive.files.FileResource#io.smallrye.mutiny.Uni<io.quarkus.ts.http.restclient.reactive.files.FileWrapper> downloadMultipartNonBlocking()'
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:630)
[ERROR] 	... 14 more
[ERROR] -> [Help 1]
```

### Output of `uname -a` or `ver`

5.17.11-300.fc36.x86_64

### Output of `java -version`

11.0.12, vendor: GraalVM Community

### Quarkus version or git rev

2.7.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by fedinskiy** [comment]
@geoand yes, but first I need to understand, what is intended relation between blocking and multipart. 
1. If the condition is right, and multipart should only be used with blocking endpoints, when I need to fix the message.
2. If the message is right, and multipart should only be used with non-blocking endpoints, when I need to fix the condition

Most of the original MR[1] describes it as Multipart+Blocking (so, the first point), could you confirm that?

[1] https://github.com/quarkusio/quarkus/commit/0b74d1fce68f9bc48bbb90d81b8afb92f26937f5#diff-942c5cb229a33319730d979b7e6b8777b37a5ceb84b1ba0b135598b69780b241R517

**Comment by geoand** [comment]
> when I need to fix the message.

This is what needs to be done
