### ISSUE TITLE
outdated jakarta.enterprise.cdi-api

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#25906]
### Describe the bug

the corresponding version thats used in quarkus is outdated 

jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2

please upgrade to

jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.0

its just a package move i think.

the documentation altho leads to the old outdated cdi-api

![image](https://user-images.githubusercontent.com/8830888/171364516-c4f96082-bd84-4db9-adee-c50f9db1f054.png)

we have to use the old version to make it work with quarkus

![image](https://user-images.githubusercontent.com/8830888/171364686-b197010e-70ba-47e7-9dab-95b2f2304a16.png)

**Comment by gsmet** [comment]
This is part of the Jakarta 10 migration that is planned here: https://github.com/quarkusio/quarkus/issues/21574 .

It's an ongoing project.
