### ISSUE TITLE
building master creates changes on file

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#2592]
**Describe the bug**
After Quarkus has been locally build with `mvn clean install -DskipTests=true` and I check `git status` I can see changes on files I haven'ts touched :  
```

modified:   extensions/smallrye-context-propagation/deployment/src/test/java/io/quarkus/context/test/TransactionalBean.java
modified:   extensions/smallrye-context-propagation/runtime/src/main/java/io/quarkus/smallrye/context/runtime/SmallRyeContextPropagationTemplate.java
modified:   integration-tests/main/src/test/java/io/quarkus/it/main/ContextPropagationTestCase.java

```

**Expected behavior**
 After a build i would expect only changes on the files I changed myself

**To Reproduce**
1. `mvn clean install -DskipTests=true`
2. `git status`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux localhost.localdomain 5.0.13-300.fc30.x86_64 #1 SMP Mon May 6 00:39:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_212"
 - GraalVM version (if different from Java): rc16
 - Quarkus version or git rev: master

**Comment by Dufgui** [comment]
I fix the organize import, but i check the formater chek in the build before create the PR

**Comment by Dufgui** [comment]
in fact it's already checked by the build:
 https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=2353
