### ISSUE TITLE
REST Data Panache with ResteasyReactive: field 'id' was not found error

### ISSUE THREAD

**Issue by olekp** [quarkusio/quarkus#25920]
### Describe the bug

When using REST Data Panache with ResteasyReactive for entity that has an id field not named "id" application crashes on start with exception: 

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.RuntimeException: Class 'java.lang.Object' field 'id' was not found
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:146)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:144)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.getFieldInfo(LinksProcessor.java:144)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:103)
	at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:65
```

example entity:
```java
public class ExampleEntity extends PanacheEntityBase {
    @Id
    long companyId;
}
```
example resource:
```java
@ResourceProperties(path =  "/example")
public interface ExampleResource extends PanacheEntityResource<ExampleEntity, Long> {
}
```
Data Panache generate resource with path "/example/{id}" so `io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#getFieldInfo` scans for field "id", ignoring the fact that entity can have id field with whatever name but with annotation `@Id`

### Expected behavior

REST Data Panache with ResteasyReactive should work with an entity with id field not named "id" but annotated with `@Id`

### How to Reproduce?

use 
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-rest-data-panache</artifactId>
        </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```
example entity:
```java
public class ExampleEntity extends PanacheEntityBase {
    @Id
    long companyId;
}
```
example resource:
```java
@ResourceProperties(path =  "/example")
public interface ExampleResource extends PanacheEntityResource<ExampleEntity, Long> {
}
```

### Quarkus version or git rev

2.9.2.Final

**Comment by loicmathieu** [comment]
Can you change the type of your id to `Long` instead of the primitive type `long` ?

By the way, this is the default ID field provided by `PanacheEntity` so you better use `PanacheEntity` instead of `PanacheEntityBase`.

**Comment by olekp** [comment]
changing `long` to `Long` didn't help

**Comment by olekp** [comment]
according to doc for `PanacheEntity`
> Represents an entity with a generated ID field id of type Long.

but I need not generated id with different name, hence I use `PanacheEntityBase`

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25925 takes care of it
