### ISSUE TITLE
RESTEasy Reactive: Content type incorrect for Qute templates

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#25932]
### Describe the bug

efecf5eff03937167db81146667d6b4f1773f47a introduced a bug because the `TemplateResponseFilter` used to set the Content Type:

```java
            if (mediaType != null) {
                responseContext.setEntity(r, null, mediaType);
            } else {
                responseContext.setEntity(r);
            }
```

While the new behaviour in `TemplateResponseUniHandler` does not:

```java
        requestContext.setResult(createUni(requestContext, (TemplateInstance) result, engine));
    }

    private Uni<String> createUni(ResteasyReactiveRequestContext requestContext, TemplateInstance result, Engine engine) {
        setSelectedVariant(result, requestContext.getRequest(),
                requestContext.getHttpHeaders().getAcceptableLanguages());
        return toUni(result, engine);
    }
```

As a result, Qute HTML templates now get their content type set to `text/plain; charset=utf8` which is incorrect. A bit scary that we don't have a test for this too…

**Comment by geoand** [comment]
Also, it would be great to have a simple way to reproduce this

**Comment by geoand** [comment]
@FroMage could you test https://github.com/quarkusio/quarkus/pull/25945?
