### ISSUE TITLE
RestClient errors statuscode are not shown in micrometer

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#25951]
### Describe the bug

When using rest-client reactive with micrometer-registry-prometheus. We can see the following metrics for 200 calls, and the one that have runtime exceptions (not `javax.ws.rs.WebApplicationException` or the ones custom with ExceptionMapper)

```
# HELP http_client_requests_seconds  
# TYPE http_client_requests_seconds summary
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 1.0
http_client_requests_seconds_sum{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 0.480164288
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 1.0
http_client_requests_seconds_sum{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 2.009740992
# HELP http_client_requests_seconds_max  
# TYPE http_client_requests_seconds_max gauge
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="SUCCESS",status="200",uri="/{statusCode}",} 0.480164288
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="UNKNOWN",status="UNKNOWN",uri="/{statusCode}",} 2.009740992
```
The ones for error status codes (4xx/5xx) are missing. 

### Expected behavior

400 errors and others should show in the metrics endpoint. Something like that;
```
# HELP http_client_requests_seconds  
# TYPE http_client_requests_seconds summary
http_client_requests_seconds_count{clientName="httpstat.us",method="GET",outcome="FAILURE",status="400",uri="/{statusCode}",} 1.0
# HELP http_client_requests_seconds_max  
# TYPE http_client_requests_seconds_max gauge
http_client_requests_seconds_max{clientName="httpstat.us",method="GET",outcome="FAILURE",status="400",uri="/{statusCode}",} 0.480164288

```

### Actual behavior

Error status codes are not shown in the metrics

### How to Reproduce?

Reproducer; https://github.com/manofthepeace/quarkus-restclient-micrometer

Steps to reproduce;

1.run the app via mvn quarkus:dev
2.Wait about 10 sec for all calls to go through (there should be 2 stacktraces in the logs)
3. go to http://localhost:8080/q/metrics
4. The reproducer does 3 calls, 
   - 200 OK, will show in metrics endpoint
   - TimeoutException, will show in metrics endpoint
   - 400, wont show in the metrics api

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.5.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

When trying similar test with the resteasy server I can see all status code printed to the metrics.

**Comment by geoand** [comment]
cc @brunobat
