### ISSUE TITLE
I am new to Quarkus and running a simple program and every time get an error. Although I have used various plugin versions. 2.5, 2.9, 2.2 but no one

### ISSUE THREAD

**Issue by Furqan-Iqbal** [quarkusio/quarkus#25961]
### Describe the bug

org.apache.maven.InternalErrorException: Internal error: com.google.inject.ProvisionException: Unable to provision, see the following errors:

Error in custom provider, java.lang.TypeNotPresentException: Type io.quarkus.maven.components.BootstrapSessionListener not present at ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.7.5.Final, parent: sun.misc.Launcher$AppClassLoader@4e25154f] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule) while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with @com.google.inject.name.Named(value=quarkus-bootstrap)

**Comment by gastaldi** [comment]
What Maven version are you using? What's the output of `mvn --version`?

**Comment by Furqan-Iqbal** [comment]
> Also what's the JDK you're using to build the app

**Comment by Furqan-Iqbal** [comment]
@gastaldi thank you, i solved the problem.

**Comment by Furqan-Iqbal** [comment]
@gastaldi I have another problem. When I run the ./mvnw package so it fails, due to test fails. I cloned the code again and tried but failed. secondly, it is running on my colleague machine. I have same maven, java version as he have. But still error. don't know exactly.

**Comment by gastaldi** [comment]
Can you paste the error here?
