### ISSUE TITLE
 ResourceReferenceProvider  Injection accidental failure

### ISSUE THREAD

**Issue by MrYang-Jia** [quarkusio/quarkus#25979]
### Describe the bug

I refer to how to introduce CDI (https://quarkus.io/guides/cdi-integration)
So I want to introduce Dubbo

My problem is that after the resourcereferenceprovider is introduced, the user-defined annotation will become invalid accidentally. Each time it becomes invalid, the project can only be recompiled and started. In this way, the user can resume the injection of the user-defined annotation normally. Miraculously, the index is a generated class that prints the resourcereferenceprovider, but I don't know what factors affect the probability of injection failure

我的问题是 ResourceReferenceProvider 引入后，自定义注解偶然性会失效，每次失效，就只能重新编译启动项目，这样子才能正常恢复自定义注解的注入，神奇的是，index 是有打印 ResourceReferenceProvider 的生成类，却不知道是什么因素影响了概率性注入失败的问题

``` deployment

 private static final DotName DubboReferenceName = DotName.createSimple(DubboReference.class.getName());

    @BuildStep
    void setupResourceInjection(BuildProducer<ResourceAnnotationBuildItem> resourceAnnotations, BuildProducer<GeneratedResourceBuildItem> resources) {
   // When an entity object is generated from a dubboreference annotation, the dubboreferenceprovider may not be triggered after each startup The get method starts quarkus for 10 times, and fails to intercept CDI injection for 2-3 times. This is not a dubboreferenceprovider There is a bug in the internal method of get, and the return of a separate new entity in the get method is the same. Therefore, it is not a problem of introducing Dubbo. When various breakpoints are accessed for the first time, the internal breakpoints are also accidental and will not enter
        // @DubboReference 的注解生成实体对象时，每次启动后，不一定会触发 DubboReferenceProvider.get 方法，10次启动quarkus，有2-3次遇到拦截 CDI 注入失败的情况，造成这种不是 DubboReferenceProvider.get 内部方法有bug，该get方法里单独new 实体返回也是一样的情况，所以不是引入 dubbo 的问题，断点各种时，首次访问，内部断点也是偶然性不会进入
// 奇怪的是，每次quarkus 启动的时候，都会打印 index DubboReferenceProvider ，这说明类是没有丢失的，但是就是有时候没有拦截生成对象
        resources.produce(new GeneratedResourceBuildItem("META-INF/services/io.quarkus.arc.ResourceReferenceProvider",
                DubboReferenceProvider.class.getName().getBytes()));
        resourceAnnotations.produce(new ResourceAnnotationBuildItem(DubboReferenceName));
    }

    @BuildStep
    void load(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
        // 不可移除的类 -- 做增强，避免丢失
        additionalBeans.produce(AdditionalBeanBuildItem.builder().setUnremovable()
                .addBeanClass(DubboReferenceProvider.class)
                .addBeanClass(DubboServiceExporttProvider.class)
                .addBeanClass(DubboService.class)
                .addBeanClass(DubboReference.class)
                .build()
        );
    }

```
use @DubboReference accidental  is null not every time
but get method of DubboReferenceProvider  accidental failure

### Expected behavior

I want to get the object through @Dubboreference, which is not null every time

### Actual behavior

this get method of DubboReferenceProvider  accidental failure

### How to Reproduce?

maven
<properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <failsafe-plugin.version>${surefire-plugin.version}</failsafe-plugin.version>
    <failsafe.useModulePath>false</failsafe.useModulePath>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.version>2.9.2.Final</quarkus.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
    <dubbo.version>2.7.15</dubbo.version>
</properties>

  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo</artifactId>
      <version>${dubbo.version}</version>
    </dependency>
  </dependencies>

### Output of `java -version`

11

### GraalVM version (if different from Java)

11

### Quarkus version or git rev

2.7.5-2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.1

#### 以下日志是由 [io.qua.arc.dep.ArcProcessor] (build-77)  打印的片段
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Bean
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Subclass$$function$$1
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Subclass$$function$$2
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Subclass$$function$$3
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Subclass$$function$$4
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Subclass
Add FWK class: com.fjkuu.vescort.plugin.dubbo.DubboReferenceProvider_Observer_Synthetic_d70cd75bf32ab6598217b9a64a8473d65e248c05	

The above is the log of quarkus. In fact, it is found that the dubboreferenceprovider object has been successfully created. However, in fact, every time you restart, there is a probability that the get method in the dubboreferenceprovider will not be triggered. Through breakpoint tracking, it is found that the method will not be triggered sometimes. At present, 2.7 X (including version 2.7.6) and all versions of 2.9.2 are the same. I don't know how to solve this problem?

以上是quarkus的日志,实际上发现 DubboReferenceProvider 对象是有创建成功的，但是实际上，每次重启，都有概率没有触发 DubboReferenceProvider 里的get方法，通过断点跟踪，发现总会有时候不触发该方法，目前2.7.x(包括 2.7.6的版本也一样 )-2.9.2 的各个版本都是一样的情况，不知道这种情况怎么解决？

**Comment by manovotn** [comment]
I am sorry but I am having a hard time understanding the problem.
Do you think you could share a small reproducer? That would make the problem more obvious and debug-able for me.

**Comment by MrYang-Jia** [comment]
@manovotn Thank you for your attention
You can refer to this project https://github.com/MrYang-Jia/quarkus-demo

You need to compile "edb-ext-resource-ref" and "edb-ext-rocketmq" first

Then start the "edb-demo" project

Next, please call http://127.0.0.1:8080/hello , and then modify any string change in the code "demoserviceimpl.java", and then re initiate the request response so that the application can be hot loaded. Repeat this for 3-5 times, and the prompt is null will be returned at least once

I wonder if it is because I have loaded the extensions of different applications twice at the same time that it is most likely? Because it is difficult to reproduce when I only keep one extension


您可以参考下这个项目 https://github.com/MrYang-Jia/quarkus-demo
需要先编译 "edb-ext-resource-ref" 和 "edb-ext-rocketmq"
然后启动 "edb-demo" 项目
接着请您调用 http://127.0.0.1:8080/hello ，然后修改代码 "DemoServiceImpl.java" 里随便一个字符串的改变，然后重新发起请求响应，以便让应用热加载，以此重复3-5次，会出现至少1次的返回提示 is null 的情况，这个就是问题重现的最快方式之一
我想会不会是因为我同时加载了两次的不同应用的扩展导致的可能性最大呢？因为我只保留一个扩展的时候，很难复现

**Comment by MrYang-Jia** [comment]
> I am sorry but I am having a hard time understanding the problem. Do you think you could share a small reproducer? That would make the problem more obvious and debug-able for me.
Thank you for your attention
You can refer to this project https://github.com/MrYang-Jia/quarkus-demo
You need to compile "edb-ext-resource-ref" and "edb-ext-rocketmq" first
Then start the "edb-demo" project

**Comment by MrYang-Jia** [comment]
> I am sorry but I am having a hard time understanding the problem. Do you think you could share a small reproducer? That would make the problem more obvious and debug-able for me.

Hello, there should be no problem with the examples I provided. If you still need my adjustment or assistance, please feel free to let me know. Thank you

**Comment by MrYang-Jia** [comment]
It's just to tell you this method for faster reproduction of the scene. In fact, it will be skipped when starting, but it will be more troublesome. Therefore, it tells you this convenient reproduction method

At the same time, thank you for your help. I hope we can get to the problem node as soon as possible. Thank you

**Comment by manovotn** [comment]
After some more debugging, I can see that the problem is that both libraries (`edb-ext-resource-ref` and `edb-ext-rocketmq`) register `GeneratedResourceBuildItem` with the same _name_.
I.e. they both do something like this:

> `new GeneratedResourceBuildItem("META-INF/services/io.quarkus.arc.ResourceReferenceProvider", XXX.class.getName().getBytes())`

I don't know if this is legit and I am trying to figure that out.
In the meantime, a way to workaround this would be to merge the generation of this file into single place.
I found the following [piece of code from Quarkus guides](https://quarkus.io/guides/writing-extensions#multi-build-items) that does just that. Look at the `produceServiceFiles` method.

**Comment by MrYang-Jia** [comment]
@manovotn Thank you. I also discovered that this may be the reason, but I really didn't expect to try it. Thank you very much for the scheme you provided. I'll try it for the first time

**Comment by manovotn** [comment]
After discussion with colleague, I think this is an _expected_ behavior and you need to declare resource providers as described in my [previous comment](https://github.com/quarkusio/quarkus/issues/25979#issuecomment-1151389518)

**Comment by MrYang-Jia** [comment]
Do you mean to make all extension projects one? I specially operated according to the way you said, and found that it is indeed possible to merge into one, but if it is split into two extension projects, how should I declare it in the code? Because all registered objects are the same ResourceReferenceProvider.java

    @BuildStep
    public ServiceWriterBuildItem registerOneService() {
        return new ServiceWriterBuildItem(
                ResourceReferenceProvider.class.getName(),
                AReferenceProvider.class.getName(),
                BReferenceProvider.class.getName()
        );
    }

**Comment by manovotn** [comment]
> Do you mean to make all extension projects one? I specially operated according to the way you said, and found that it is indeed possible to merge into one, but if it is split into two extension projects, how should I declare it in the code? Because all registered objects are the same ResourceReferenceProvider.java

You can merge it into one project, that would work for sure.
Or perhaps you could create another project that declares dependencies on all these other projects and that creates the aggregated `GeneratedResourceBuildItem` for them? I am not sure this would work, just tossing ideas around.

**Comment by MrYang-Jia** [comment]
非常感谢您的耐心回复，因为我想做很多类似的插件,类似于自定义注解在不同的场景应用里的实现，也希望后面自己能尝试开放一些生态提供相应的帮助，所以对这些知识点特别像摸清楚，接着我自己多尝试尝试，也希望能早点攻克类似的问题，再次表示感谢您的耐心解答，谢谢
Thank you very much for your patient reply, because I want to make many similar plug-ins, similar to the implementation of custom annotations in different scenarios. I also hope that I can try to open some ecosystems to provide corresponding help later, so I am particularly clear about these knowledge points. I will try more and hope to overcome similar problems as soon as possible. Thank you again for your patience. Thank you

**Comment by MrYang-Jia** [comment]
我刚刚尝试了下，您说的构建一个第三方的依赖模块去将对应的扩展去做兼容依赖，确实是可以的
但好像不太适合作为开放插件去让第三方使用
I just tried. You said that it is really possible to build a third-party dependency module to make compatible dependencies on the corresponding extensions
But it seems that it is not suitable to be used by third parties as an open plug-in

```
// A and B ServiceWriterBuildItem.java must same class
// A -- ext
    @BuildStep
    void setupResourceInjection(BuildProducer<ResourceAnnotationBuildItem> resourceAnnotations,
                                BuildProducer<GeneratedResourceBuildItem> resources) {
        resourceAnnotations.produce(new ResourceAnnotationBuildItem(AReferenceName));
    }

    @BuildStep
    public void registerSeveralServices(
            BuildProducer<ServiceWriterBuildItem> providerProducer
    ) {       
        providerProducer.produce(new ServiceWriterBuildItem(
                ResourceReferenceProvider.class.getName(),
                AProvider.class.getName()
        ));
    }

// B ext 
    @BuildStep
    void setupResourceInjection(BuildProducer<ResourceAnnotationBuildItem> resourceAnnotations,
                                BuildProducer<GeneratedResourceBuildItem> resources) {
        resourceAnnotations.produce(new ResourceAnnotationBuildItem(BReferenceName));
    }

    @BuildStep
    public void registerSeveralServices(
            BuildProducer<ServiceWriterBuildItem> providerProducer
    ) {       
        providerProducer.produce(new ServiceWriterBuildItem(
                ResourceReferenceProvider.class.getName(),
                BProvider.class.getName()
        ));
    }
	
// C ext	

/**
     * This build step aggregates all the produced service providers
     * and outputs them as resources.
     */
    @BuildStep
    @Priority(100)
    public void produceServiceFiles(
            List<ServiceWriterBuildItem> items,
            BuildProducer<GeneratedResourceBuildItem> resourceProducer,
            BuildProducer<ResourceAnnotationBuildItem> resourceAnnotations
            ) throws IOException {
		// items.size() = A+B 
        System.out.println("====A+B=====>"+items.size());

        // Aggregate all of the providers
        Map<String, Set<String>> map = new HashMap<>();
        for (ServiceWriterBuildItem item : items) {
            String serviceName = item.getServiceName();
            System.out.println("====111=====>"+item.getImplementations());
            for (String implName : item.getImplementations()) {
                map.computeIfAbsent(
                        serviceName,
                        (k) -> new LinkedHashSet<>()
                ).add(implName);
            }
        }

        // Now produce the resource(s) for the SPI files
        for (Map.Entry<String, Set<String>> entry : map.entrySet()) {
            String serviceName = entry.getKey();
            try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
                try (OutputStreamWriter w = new OutputStreamWriter(os, StandardCharsets.UTF_8)) {
                    for (String implName : entry.getValue()) {
                        w.write(implName);
                        w.write(System.lineSeparator());
                    }
                    w.flush();
                }
                resourceProducer.produce(
                        new GeneratedResourceBuildItem(
                                "META-INF/services/" + serviceName,
                                os.toByteArray()
                        )
                );
            }
        }
    }

```
