### ISSUE TITLE
OIDC `quarkus.oidc.tls.trust-store-provider` missing documentation / examples

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#25972]
### Describe the bug

Based on Quarkus configuration [site](https://quarkus.io/guides/all-config#quarkus-oidc_quarkus-oidc-openid-connect) there is a new property `quarkus-oidc_quarkus.oidc.tls.trust-store-provider` that allow you to setup a trust-store and key-store provider.

Def: `An optional parameter to specify a provider of the trust store file. If not given, the provider is automatically detected based on the trust store file type.`

However, my impression is that this configuration is not taken into account, because IF I set a random name into this property the application doesn't complain at all. 

For example:
Application properties:
```
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.token.lifespan-grace=5
quarkus.oidc.token.principal-claim=email
quarkus.oidc.token.issuer=${quarkus.oidc.auth-server-url}
quarkus.oidc.tls.verification=certificate-validation
quarkus.oidc.tls.key-store-file=client-keystore.${ks-file-extension}
quarkus.oidc.tls.trust-store-file=client-truststore.${ks-file-extension}
quarkus.oidc.tls.key-store-password=${ks-pwd}
quarkus.oidc.tls.trust-store-password=${ks-pwd}

// RANDOM providers

quarkus.oidc.tls.trust-store-provider=Random1,Random2
quarkus.oidc.tls.key-store-provider=Random1,Random2

quarkus.native.additional-build-args=-H:IncludeResources=.*\\.p12||.*\\.jks||.*\\.unknown-extension
```

Also based on the documentation, to me is not clear if is possible to define a list of available providers as Quarkus does on [`quarkus-security` extension](https://quarkus.io/guides/security-customization#default-providers), or just a single one. In my opinion, would be great to rename this property to "providerS" and support more than one valid provider

suggested changes: `quarkus.oidc.tls.trust-store-provider` -> `quarkus.oidc.tls.trust-store-providers`

**Comment by sberyozkin** [comment]
@pjgg Hey, as you can see from [this commit](https://github.com/quarkusio/quarkus/pull/25234/files#diff-ed91fc95ad9c343a3060086e5b531ba1d372b360f3e7594e5789eac3bed372e1) they are set on the corresponding options.
I don't think it should be a list - here a provider is specific to a configured keystore or truststore.
I've added this properties on your request, I'm not sure what else should be added to the doc, a store provider is a well-known Java security concept...
To verify it works with OIDC you should also be able to have Keycloak MTLS be configurable in a similar way on the Keycloak end. Keycloak issue exists AFAIK.

I think these random values are ignored by Java keystore implementations for well-known key store types, it probably defaults to a default P12 format if a given provider can't be found - if you debug then you'll be able to confirm
