### ISSUE TITLE
Custom logging filters

### ISSUE THREAD

**Issue by janinko** [quarkusio/quarkus#25981]
### Discussed in https://github.com/quarkusio/quarkus/discussions/25912

<div type='discussions-op-text'>

<sup>Originally posted by **janinko** June  1, 2022</sup>
Hi,

Is there a way how to configure custom logging filter for handlers in quarkus? Something like this in WildFly: https://www.wildfly.org/news/2020/01/04/Custom-Logging-Filter/

Alternatively, is there a way how to filter logs messages that go to handled by specific Marker or logger name?</div>

**Comment by geoand** [comment]
I am also wondering whether enabling the various logging components using annotations instead of config would make sense...

**Comment by geoand** [comment]
I like approach no.1.

I'll try and have a look in a few weeks

**Comment by manofthepeace** [comment]
I just played with that for smallrye-faulttolerance and Ladicek found me a way to make it work. If it runs early enough it seems to work well. In my case I used it in a `@Startup` bean and it works.

In my case it looks like this;
`Logger.getLogger("io.smallrye.faulttolerance.core.retry").setFilter(new LoggingFilter());`

**Comment by famod** [comment]
@ geoand

> I'll try and have a look in a few weeks

Do 6 weeks already qualify as "few"? 😜

**Comment by geoand** [comment]
Other things always come up

**Comment by geoand** [comment]
But yeah, I agree I should try and take care of this soon

**Comment by geoand** [comment]
Looking at this again, I am actually torn between `Approach 1` and `Approach 2` mentione by @dmlloyd.
What do you folks think?

**Comment by gastaldi** [comment]
![image](https://i.kym-cdn.com/photos/images/original/000/538/731/0fc.gif)

**Comment by gastaldi** [comment]
### Approach 1: Register by name

This seems to be an alternative to using the FQN, so I am not sure if it wouldn't be more confusing.

### Approach 2: Configured fully at the component

I think in practice people will already know the categories they are planning to filter, so I think it makes sense for these use cases. I'm leaning towards on a solution based on that

**Comment by gastaldi** [comment]
Does Category have to be an annotation? I'd rather make them a String[] for simplicity :)

**Comment by famod** [comment]
Sure! 🤦‍♂️

**Comment by geoand** [comment]
> And then you could override the categories via config.

How so?

**Comment by geoand** [comment]
@famod ^

**Comment by janinko** [comment]
You are talking here about filtering categories, but my original request was for filters in handlers.
For example I have console and file handlers and I want to have filter to log only specific categories or certain keyword into the file.

**Comment by geoand** [comment]
Filters in handlers... Interesting 😎.

I'll have to see how we can support that

**Comment by geoand** [comment]
I updated the PR with tests and docs

**Comment by janinko** [comment]
Great thanks. However, It would be nice that the filter is also configurable from config file. Wildfly has it like this:
```
/subsystem=logging/filter=clFilter:add(module=org.jboss.example.filter, class=org.jboss.example.filter.ClassLoaderFilter, properties={pattern=".*deployment\.app.*"})
```
Note that the filters can also have properties like `pattern` here, that should be configurable from config too.

**Comment by geoand** [comment]
We tend to shy away from configuring class names in a configuration file as it's very error prone and IDEs can't really help users.

**Comment by janinko** [comment]
Fair enough, but I would really like the properties configurable.

**Comment by geoand** [comment]
`properties` of the filter you mean? As in the ability to set arbitrary fields in configuration?

**Comment by janinko** [comment]
Yup. I for example use a message pattern filter and would like to have the pattern configurable.

**Comment by geoand** [comment]
I understand the desire, but again that is something we really don't do in Quarkus.

**Comment by janinko** [comment]
So how is this done in Quarkus? I believe that logging is something that should be widely configurable.

**Comment by geoand** [comment]
How is what done? Logging configuration you mean?
Normally, it would be done with CDI, but in this case I don't think it will fly as logging needs to be configured super early. 

If for whatever reason you need to configure the filters introduced here, we could provide some kind of Customizer style interface, or even a way to provide a factory for the filter.

**Comment by janinko** [comment]
Our usecase is that we have a Filter class that we use in all of our applications and want to configure each application to have different pattern that is being filtered.

It looks to me that this way it is implemented means that we would have to create custom subclass for each application with the pattern hardcoded and would need to recompile the application if we need the pattern to change.

**Comment by geoand** [comment]
Sure, we want to avoid that.

The solutions I propose above would allow you do what you need

**Comment by geoand** [comment]
It's just a proposal for now 🙂

**Comment by geoand** [comment]
@janinko can you take a look at https://github.com/quarkusio/quarkus/pull/27917?

The test I changed should give you a pretty good idea of how users would configure such filters.

WDYT?

**Comment by janinko** [comment]
> @janinko can you take a look at #27917?
> 
> The test I changed should give you a pretty good idea of how users would configure such filters.
> 
> WDYT?

Sorry for late reply, had 2 bussy weeks. Yes, that looks perfectly fine for me, thanks!

**Comment by geoand** [comment]
👍🏼

**Comment by aveeshek** [comment]
Full example: [add-a-logging-filter-to-your-log-handler](https://quarkus.io/guides/logging#add-a-logging-filter-to-your-log-handler)
