### ISSUE TITLE
Guide fix after code change

### ISSUE THREAD

**Issue by demtnt** [quarkusio/quarkus#25980]
### Description

It is looks like mistake in [https://quarkus.io/guides/gradle-tooling#running-integration-tests](https://quarkus.io/guides/gradle-tooling#running-integration-tests). Instead of `This task depends on both check and quarkusBuild tasks. ` should be `This task depends on both test and quarkusBuild tasks. `  As we can see in [https://github.com/quarkusio/quarkus/pull/24711/commits/17b51b899350bd1f5af5d72e88298015f3a00c43](https://github.com/quarkusio/quarkus/pull/24711/commits/17b51b899350bd1f5af5d72e88298015f3a00c43)

### Implementation ideas

Replace `This task depends on both check and quarkusBuild tasks.` with `This task depends on both test and quarkusBuild tasks.`

**Comment by demtnt** [comment]
with pleasure, but have no idea where sources of https://quarkus.io/guides/gradle-tooling#running-integration-tests are located

**Comment by geoand** [comment]
The source can be found at https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/gradle-tooling.adoc
