### ISSUE TITLE
Qute - add a generic template extension method for or()/elvis operator

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#25995]
### Description

`ValueResolvers.orResolver()` does not allow for type-safe validation, i.e. in the expression `{foo.name.or('John').toUpperCase}` the `toUpperCase` property is not validated.

**Comment by michalvavrik** [comment]
@mkouba

thoughts
1. extension method is basically `ValueResolver` but more costly as it has to be built by `io.quarkus.qute.generator.ExtensionMethodGenerator.NamespaceResolverCreator.ResolveCreator#addMethod`
2. when `or`/`elvis` formal parameters are validated here https://github.com/quarkusio/quarkus/blob/main/extensions/qute/deployment/src/main/java/io/quarkus/qute/deployment/QuteProcessor.java#L779 and param type info is available, you inherently knows the return type, so the type-safe validation is possible.
3. when `foo.name` has known  type information (f.e. param declaration) you can validate `toUpperCase` for `foo.name` only
4. when `John` (in that case you do know it's string, but it could be `clazz.PropertyName`) has known type information and `foo.name`, you can validate `toUpperCase` for `John` only
5. when both `foo.name` and `John` has type information, you can  validate both 

questions
- Is there an advantage in adding a generic template extension? Would adding a few lines in `validateNestedExpressions` be fine?
- Should only be validated that both sides has `toUpperCase`? Consider please following example - in Java, you couldn't call `toUpperCase` with f.e. `java.util.Optional#orElse` as there is no common interface with `toUpperCase`, but in Qute it won't be an issue as we only care that there is `toUpperCase`, so basically we can validate both sides independently?

``` Java
package io.quarkus.qute.deployment.typesafe;

import static org.junit.jupiter.api.Assertions.assertEquals;

import javax.inject.Inject;

import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.quarkus.qute.Template;
import io.quarkus.test.QuarkusUnitTest;

public class BuiltInResolversValidationTest {

    public static final String ITEM_NAME = "Test Name";

    @RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .withApplicationRoot((jar) -> jar
                    .addClasses(Item.class, OtherItem.class, ItemWithName.class, ItemWithName.Name.class)
                    .addAsResource(new StringAsset(
                            "{@io.quarkus.qute.deployment.typesafe.Item item}\n" +
                                    "{@io.quarkus.qute.deployment.typesafe.ItemWithName itemWithName}\n"
                                    +
                                    "{#for item in item.otherItems}\n" +
                                    "  {data:item.name.or(itemWithName.name).toUpperCase}\n" +
                                    "{/for}\n"),
                            "templates/item.html"));

    @Inject
    Template item;

    @Test
    public void testOrValueResolver() {
        assertEquals(
                ITEM_NAME.toUpperCase(),
                item.data("item", new Item(ITEM_NAME.toUpperCase(), new OtherItem())).render().trim());
        assertEquals(
                ITEM_NAME.toUpperCase(),
                item.data("item", new Item(null, new OtherItem()), "itemWithName", new ItemWithName(new ItemWithName.Name()))
                        .render().trim());
    }

}

package io.quarkus.qute.deployment.typesafe;

public class ItemWithName {
    private final Name name;

    public ItemWithName(Name name) {
        this.name = name;
    }

    public Name getName() {
        return name;
    }

    public static class Name {

        public String toUpperCase() {
            return BuiltInResolversValidationTest.ITEM_NAME.toUpperCase();
        }
    }
}

package io.quarkus.qute.deployment.typesafe;

public class Item {

    String name;

    OtherItem[] otherItems;

    public Item(String name, OtherItem... otherItems) {
        this.name = name;
        this.otherItems = otherItems;
    }

    public String getName() {
        return name;
    }

    public OtherItem[] getOtherItems() {
        return otherItems;
    }
}

```

**Comment by mkouba** [comment]
> Is there an advantage in adding a generic template extension? Would adding a few lines in validateNestedExpressions be fine?

The `validateNestedExpressions()` method body is already very complex. So the advantage is that we don't add anything special but rely on existing API.

> Should only be validated that both sides has toUpperCase? Consider please following example - in Java, you couldn't call toUpperCase with f.e. java.util.Optional#orElse as there is no common interface with toUpperCase, but in Qute it won't be an issue as we only care that there is toUpperCase, so basically we can validate both sides independently?

That's a very good question. And I have no answer yet. I need to think about it a bit more ;-)

**Comment by michalvavrik** [comment]
Okay, I read `io.quarkus.qute.deployment.QuteProcessor#findTemplateExtensionMethod` again and I can imagine generic extension method with little adjustments, but it can't validate the 2 parts separately (see above), so I'll wait till you think about it (no hurry). Thanks

**Comment by mkouba** [comment]
So generic template extension methods should be validated. There's for exampe this [test](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/deployment/src/test/java/io/quarkus/qute/deployment/extensions/CollectionTemplateExtensionsTest.java#L67-L70) that validates the this [built-in extension method](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/extensions/CollectionTemplateExtensions.java#L69-L74).

The question whether we should validate the original and/or the "other" value is a bit tricky. The `ValueResolvers.orResolver()` from the core allows to return an "other" value of any type which is perfectly fine in an environment which is not type-safe.

If we implement the new template extension method like this:
```java
static <T> T or(T value, T other) {
     if (value == null || Results.isNotFound(value) || (value instanceof Optional && ((Optional<?>) value).isEmpty())) {
        return other;
     }
    return value;
}
```
then it should only be used for the argument of type `T`. I.e. it would not be used for `{foo.name.or(1).toUpperCase}`. In this case, no validation would be perfomed. And it would be similar to the case where a method param has no type information associated.

**Comment by mkouba** [comment]
@michalvavrik WDYT? ^

**Comment by michalvavrik** [comment]
definitely @mkouba , thanks for taking your time to write this down. I'm now finishing 2 other PRs, then I'll rewrite #26826 to use generic template extension.

**Comment by mkouba** [comment]
> definitely @mkouba , thanks for taking your time to write this down. I'm now finishing 2 other PRs, then I'll rewrite #26826 to use generic template extension.

Yw, no rush at all ;-)

Looking forward to the updated version of this PR!
