### ISSUE TITLE
Allow to create runtime only ConfigSource

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#25999]
### Description

Currently, if we define a ConfigSource via a ConfigSourceFactory, this ConfigSource is initialized once at build time (and the `getPropertyNames()` method is called) and once at runtime.

We should be able to define runtime only ConfigSource / ConfigSourceFactory for exemple for ConfigSource that load a file at runtime which can be not found at build time. As ConfigSourceFactory allow to access the `ConfigSourceContext` which can be different at build and runtime it's important to have this functionality.

See this Zulip discussion for context: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/ConfigSourceFactory.20initialized.20at.20build.20time

**Comment by raoua-eng** [comment]
It would be very helpful if the configuration source is initialized at runtime, this will help avoid the chicken egg problem.

But what about configurations that need to be initialized at build time?

**Comment by radcortez** [comment]
I'll have to think about this.

I guess the best option is to introduce a new annotation that allows you to control the registration of all Config components per phase.
