### ISSUE TITLE
CLI allows to create project with comma in the name

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#25991]
### Describe the bug

CLI allows to create project with comma in the name. Comma is not allowed character for `artifactId` in maven projects

```
quarkus create app app,with,comma
cd app,with,comma
quarkus build

...

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'artifactId' with value 'app,with,comma' does not match a valid id pattern. @ line 6, column 15
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.acme:app,with,comma:1.0.0-SNAPSHOT (/Users/rsvoboda/tmp/app,with,comma/pom.xml) has 1 error
[ERROR]     'artifactId' with value 'app,with,comma' does not match a valid id pattern. @ line 6, column 15
```

### Expected behavior

CLI complains about problematic character

### Actual behavior

CLI allows to create project with comma in the name. Comma is not allowed character for `artifactId` in maven projects

### How to Reproduce?

```
quarkus create app app,with,comma
cd app,with,comma
quarkus build
```

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.9.2.Final

**Comment by ebullient** [comment]
what do you think is the right answer: a failure, or a fixed artifact Id?

**Comment by gsmet** [comment]
We should make sure it is a valid artifactId and fail IMO.
