### ISSUE TITLE
Specify (build log and the like) why appcds archive cannot be created although quarkus.package.create-appcds is enabled

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#26004]
### Description

I am currently struggling in getting app-cds to work. If I run my build locally everything works like a charm and gradle prints information to the command line regarding app cds archive being created: 

```
> Task :quarkusBuild
Caching disabled for task ':quarkusBuild' because:
  Build cache is disabled
Task ':quarkusBuild' is not up-to-date because:
  Class path of task ':quarkusBuild' has changed from 1369d7a3f64390dba45ef73fbba197d2 to 136041e4eafed42423320d7e02138b57.

JBoss Threads version 3.4.2.Final

Launching AppCDS creation process.
AppCDS successfully created at: '/home/u6f6o/projects/internal/sup/build/quarkus-app/app-cds.jsa'.

Starting (local) container image build for jar using jib.
Base image 'registry.access.redhat.com/ubi8/openjdk-17-runtime:1.11' does not use a specific image digest - build may not be reproducible
```
Also if I have a look at the build directory, it shows the appcds directory: 
```
ls -l build/appcds
total 320
-rw-r--r--  1 u6f6o  staff  125638 Jun  8 12:51 classes.lst
-rw-r--r--  1 u6f6o  staff   24937 Jun  8 12:50 generatedAndTransformed.lst
``` 
Furthermore,  if I inspect the created image (created by jib) with dive, it shows a `app-cds.jsa` file under /home/jboss in the resulting jib image. 

As soon as I run the same build on the gitlab pipeline though, the app cds archive is not created for some reason. There is no log output on in the builid pipeline, nor is there a appcds directory in the gradle build directory. When I open the resulting jib image with dive, it also does not contain the app-cds.jsa file. 

### Implementation ideas

Add additional log messages that indicate why the appcds archive cannot be created although the  quarkus.package.create-appcds property is set to true. Thus we'll be able to find out what is gong wrong and what we can do to make appcds work even in gitlab.

**Comment by geoand** [comment]
`io.quarkus.deployment.pkg.steps.AppCDSBuildStep` does plenty of logging already. 
The simplest way to see it would be to do `./gradlew clean quarkusBuild -Dquarkus.container-image.build=true -Dquarkus.package.create-appcds=true --debug` and look for entries containing `io.quarkus.deployment.pkg.steps.AppCDSBuildStep`

**Comment by geoand** [comment]
That's a good point. I'll convert some of the debug messages to warnings
