### ISSUE TITLE
JAX-RS SubResources are not working if no default constructor is present.

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#26008]
### Describe the bug

Arc thinks that _SubResource_ is a bean and tries to create it.

```java
    @Path("{id}")
    public SubResource get(@PathParam("id") String id) {
        return new SubResource(id);
    }
```

There is no scope annotation added to the resource:

```java
    @Consumes("application/json")
    @Produces("application/json")
    public static class SubResource {

        private String id;
        
        public SubResource(String id) {
            this.id = id;
        }

        @GET
        public String greeting() {
            return "Hello " + id;
        }
    }
```

In case the _SubResource_ is not static, then the problem transforms into:

```
The INNER class subresource.TestClass$SubResource has a scope annotation but it must be ignored per the CDI rules
```

### Expected behavior

_SubResources_ should not be part of the context per default. They can be created with "new". (test should pass:)

### Actual behavior

Build time failure thrown:

```posh
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
	- java member: subresource.TestClass$SubResource():id
	- declared on CLASS bean [types=[subresource.TestClass$SubResource, java.lang.Object], qualifiers=[@Default, @Any], target=subresource.TestClass$SubResource]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
```

### How to Reproduce?

Build the attached source and start test.

### Quarkus version or git rev

2.9.2

**Comment by smil2k** [comment]
[src.tar.gz](https://github.com/quarkusio/quarkus/files/8862443/src.tar.gz)

**Comment by geoand** [comment]
Thanks for reporting. Can you please attach the entire project (with the `pom.xml` file) please instead of just the java source?

**Comment by smil2k** [comment]
[integration-test.tar.gz](https://github.com/quarkusio/quarkus/files/8912401/integration-test.tar.gz)

**Comment by geoand** [comment]
This works properly with RESTEasy Reactive and since we are putting all our efforts into that, I'm going to close this as won't fix.
