### ISSUE TITLE
rest-client-reactive does not inject Providers in ClientRequestFilter

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#26003]
### Describe the bug

https://github.com/Shohou/rest_client_reactive_inject_bug
this project demonstrates an issue. It has two branches. One is called `classic` and uses `quarkus-rest-client` and another is called `reactive` and has the only difference - changed library to `quarkus-rest-client-reactive`. Reactive branch fails to inject `Providers` to `ClientRequestFilter`

### Expected behavior

My expected behavior is that both branches work

### Actual behavior

Reactive branch fails with NPE
```
java.lang.NullPointerException: Cannot invoke "javax.ws.rs.ext.Providers.getMessageBodyWriter(java.lang.Class, java.lang.reflect.Type, java.lang.annotation.Annotation[], javax.ws.rs.core.MediaType)" because "this.providers" is null

	at org.acme.MyRemoteServiceAuthFilter.filter(MyRemoteServiceAuthFilter.java:36)
        ...
```
Exception happens in [MyRemoteServiceAuthFilter.java](https://github.com/Shohou/rest_client_reactive_inject_bug/blob/reactive/src/main/java/org/acme/MyRemoteServiceAuthFilter.java). There is an injection of `Providers` and it doesn't work for reactive case

### How to Reproduce?

Try to execute a MyRemoteServiceTest

### Quarkus version or git rev

quarkus 2.9.2

**Comment by geoand** [comment]
This is an interesting edge case. To be honest, I don't like what the classic REST Client does... It's counter intuitive as you are creating the instance on your own...

**Comment by Shohou** [comment]
Is there other way how I can get Providers in ClientRequestFilter? I tried to inject it outside of filter and pass as argument, and tried to find programmatically in filter method. Both attempts failed because there is no injectable instance of Providers.

**Comment by geoand** [comment]
You should be able to get it using `CDI.current().select(Providers.class).get()`

**Comment by Shohou** [comment]
it doesn't work, I get exception:
```
javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface javax.ws.rs.ext.Providers] and qualifiers [[]]

	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:188)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)
	at org.acme.MyRemoteServiceAuthFilter.filter(MyRemoteServiceAuthFilter.java:32)
	at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:24)
	at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:9)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:219)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:262)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:252)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.method(AsyncInvokerImpl.java:212)
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:336)
	at org.acme.MyRemoteServiceDefinition$$QuarkusRestClientInterface.getZen(Unknown Source)
	at org.acme.MyRemoteService.getZen(MyRemoteService.java:24)
	at org.acme.MyRemoteService_ClientProxy.getZen(Unknown Source)
	at org.acme.MyRemoteServiceTest.textZen(MyRemoteServiceTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
[MyRemoteServiceAuthFilter.java](https://github.com/Shohou/rest_client_reactive_inject_bug/blob/reactive_cdi/src/main/java/org/acme/MyRemoteServiceAuthFilter.java)

**Comment by geoand** [comment]
Hm... It seems that only works on the server

**Comment by Sgitario** [comment]
It's not working because you're not using the Resteasy Reactive Server extension, but the Resteasy REST Client Reactive which does not provide the `Providers` instance. 
To fix your issue, you need to inject the list of MessageWriters instead of the `Providers` instance:

```java
@Inject
Instance<MessageBodyWriter> writers;
```

And then replace "providers.getMessageBodyWriter(" with:

```java
for (MessageBodyWriter writer : writers) {
                if (writer.isWriteable(requestContext.getEntityClass(), requestContext.getEntityType(), requestContext.getEntityAnnotations(),
                        requestContext.getMediaType())) {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    writer.writeTo(request, requestContext.getEntityClass(), requestContext.getEntityType(),
                            requestContext.getEntityAnnotations(), requestContext.getMediaType(), requestHeaders, baos);
                    byte[] body = baos.toByteArray();
                    requestContext.setEntity(body, new Annotation[0], requestContext.getMediaType());

                    URI uri = requestContext.getUri();
                    requestHeaders.putSingle("Key", apiKey);
                    requestHeaders.putSingle("Signature", createSignature(uri.getPath(), body));
                    break;
                }
            }
```

I did check that this is working fine using the repository you provided.

**Comment by Shohou** [comment]
Thank you for solution. It works

I probably should have looking in Microprofile Rest client documentation... And nothing mentions there that @Context should work in providers

I guess this can be closed then unless you want to add this case to your migration guide - https://quarkus.io/guides/resteasy-reactive-migration#client

**Comment by Sgitario** [comment]
Considering that we could inject the providers using the classic version of the REST Client, we should support the same in the Reactive REST Client. 
I will work on this.

**Comment by Shohou** [comment]
@Sgitario tried to switch my project to resteasy-reactive using your approach with selecting MessageBodyWriters from CDI... and it didn't work...
It seems that returned MessageBodyWriters are for the server side resteasy library. If I do `CDI.current().select(MessageBodyWriter.class)` it returns two instances - `BasicServerJacksonMessageBodyWriter` and `FullyFeaturedServerJacksonMessageBodyWriter`, which as name suggests serialize my entity to json. But I need urlencoded body.
I debugged down to the place where resteasy client gets writers and I see that it gets two other instances - MapAsFormUrlEncodedProvider and StringMessageBodyHandler

I ended up with this code which is not as clean as getting writers from CDI, but works... with 2.16.6 at least

```
    public void filter(ClientRequestContext requestContext) throws IOException {
        if (requestContext.hasEntity()) {
            Object entity = requestContext.getEntity();

            MessageBodyWriter<Object> writer = findWriterFor(requestContext, requestContext.getEntityClass(),
                    requestContext.getEntityType(), requestContext.getEntityAnnotations(), requestContext.getMediaType());
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            writer.writeTo(entity, requestContext.getEntityClass(), requestContext.getEntityType(),
                    requestContext.getEntityAnnotations(), requestContext.getMediaType(), requestHeaders, baos);
            body = baos.toByteArray();
            requestContext.setEntity(body, new Annotation[0], requestContext.getMediaType());
        }
        ...
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private MessageBodyWriter<Object> findWriterFor(ClientRequestContext requestContext, Class<?> entityClass, Type entityType, Annotation[] annotations, MediaType mediaType) {
        List<MessageBodyWriter<Object>> writers = (List) ((ClientImpl) requestContext.getClient()).getClientContext().getSerialisers().findWriters((ConfigurationImpl) requestContext.getConfiguration(), entityClass, mediaType);
        for (MessageBodyWriter<Object> writer : writers) {
            if (writer.isWriteable(entityClass, entityType, annotations, mediaType)) {
                return writer;
            }
        }
        throw new NotFoundException("Could not find writer for entity");
    }
```

**Comment by Sgitario** [comment]
@Shohou I've proposed a solution for this in https://github.com/quarkusio/quarkus/pull/32976. 
Please, let me know if that would work for you.
