### ISSUE TITLE
hibernate reactive and kotlin: session closed if used delete in multis and a normal delete at the ned

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#26012]
### Describe the bug

I have have Entity A
Entity A has the One to Many lists
B[] and C[]

I get A by its ID
fetch B[] and C[]
do a disjoint to get the lists as multis
and do a delete on each

then I do a delete on A

And it errors out

### Expected behavior

Everything deleted in my transaction

### Actual behavior

It can't delete A.
It errors out with the error "unmanaged entity in hibernate"

I guess the repo.delete() and repo.deleteByID() close the session before.

### How to Reproduce?

```kotlin
 @OneToMany(mappedBy = "a", orphanRemoval = true)
    val b: List<B> = emptyList(),
```

```kotlin
@ManyToOne(optional = false)
var a: A
```

```kotlin
    fun deleteBy(id: UUID): Uni<Void> = repoA.findById(id)
        .onItem().ifNotNull().transformToUni { entity -> fetch(entity.d).map { if (it.isEmpty()) entity else null } }
        .onItem().ifNotNull().call { entity ->
            fetch(entity!!.b)
                .onItem().disjoint<B>()
                .onItem().transformToUniAndMerge(repoB::delete).collect().asList()
        }.onItem().ifNotNull().call { entity ->
            fetch(entity!!.c)
                .onItem().disjoint<C>()
                .onItem().call { it -> repoC.deleteById(it.id) }.collect().asList()
        }.onItem().ifNotNull().call { entity ->
            fetch(entity!!.e)
                .onItem().disjoint<E>()
                .onItem().transformToUniAndMerge { repoE.persist(it.apply { a = null }) }.collect().asList()
        }.onItem().ifNotNull().transformToUni(repo::delete)
```

### Output of `uname -a` or `ver`

Linux hostname 5.15.45-1-lts #1 SMP Mon, 06 Jun 2022 09:19:52 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22 OpenJDK Runtime Environment (build 18.0.1.1+2) OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.4.2 ------------------------------------------------------------  Build time:   2022-03-31 16:40:07 UTC Revision:     <unknown>  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          18.0.1.1 (Oracle Corporation 18.0.1.1+2) OS:           Linux 5.15.45-1-lts amd64

**Comment by DavideD** [comment]
Could you provide a working test case, please?
