### ISSUE TITLE
LocalDate and other JDK8 time classes are not parsed by rest easy classic

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#26010]
### Describe the bug

I found this bug #5860, which added support for reactive-resteasy, but the classic rest easy components are not.

This pull request contains my use case and tests:
https://github.com/quarkusio/quarkus/pull/15451/files#diff-c173c85371fe5efb3ba43734edc528583114986607dcdc3a8c3c70d954d0405e

### Expected behavior

It should work similarly as reactive rest easy.

### Actual behavior

No param converter is registered.

### Quarkus version or git rev

2.9.2

**Comment by geoand** [comment]
We won't be adding this feature to RESTEasy Classic (at least not from Quarkus), because our focus is on RESTEasy Reactive going forward.

Do you have issues moving to RESTEasy Reactive?
