### ISSUE TITLE
Custom extension is looking for missing `quarkus-extension-maven-plugin:JAR:2.9.2.Final` 

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#26014]
### Describe the bug

When I create a custom extension and then build this custom extension, build fails because of missing dependency ` io.quarkus:quarkus-extension-maven-plugin:2.9.2.Final`.

### Expected behavior

Avoid exception or emphasize this behavior in documentation, please.

### Create Quarkus CLI in version `999-SNAPSHOT`

```
git clone https://github.com/quarkusio/quarkus.git
cd quarkus
mvn -Dquickly
mkdir ../example
cd ../example
cat <<EOF > ./quarkus-dev-cli
#!/bin/bash
java -jar $PWD/../quarkus/devtools/cli/target/quarkus-cli-999-SNAPSHOT-runner.jar "\$@"
EOF
chmod +x ./quarkus-dev-cli
```
### Create extension

```
./quarkus-dev-cli create extension extension-abc
```

### Build extension

```
cd quarkus-extension-abc
../quarkus-dev-cli build
```
### Resulting Exception

```
[ERROR] Plugin io.quarkus:quarkus-extension-maven-plugin:2.9.2.Final or one of its dependencies could not be resolved: io.quarkus:quarkus-extension-maven-plugin:jar:2.9.2.Final was not found in https://repository.jboss.org/nexus/content/groups/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jboss-public-repository has elapsed or updates are forced -> [Help 1]
```

### Workaround

```
../quarkus-dev-cli build -Dquarkus.version=999-SNAPSHOT
```

### Output of `uname -a` or `ver`

Linux fedora 5.17.11-300.fc36.x86_64 #1 SMP PREEMPT Wed May 25 15:04:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

CLI version: 999-SNAPSHOT, git rev-parse --short HEAD 1e25972ec20

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: /home/mvavrik/.sdkman/candidates/maven/current Java version: 17.0.3, vendor: GraalVM Community, runtime: /home/mvavrik/.sdkman/candidates/java/22.1.0.r17-grl Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.17.11-300.fc36.x86_64", arch: "amd64", family: "unix"

**Comment by rsvoboda** [comment]
Hi @michalvavrik. Pablo noticed the same on the testsuite and I've have identified the commit which changes plugings for Quarkus 2.10. 
See https://github.com/quarkusio/quarkus/pull/25880#issuecomment-1149671224 and my comments there. There is also https://github.com/quarkus-qe/quarkus-test-suite/issues/693 with some details

@aloubyansky commented on https://github.com/quarkusio/quarkus/pull/25880 about version check.

**Comment by aloubyansky** [comment]
Yes, thanks for creating the issue. I'll look into adding a condition on the quarkus version in the templates.
