### ISSUE TITLE
Panache @CreationTimestamp and @UpdateTimestamp not working

### ISSUE THREAD

**Issue by fastluca** [quarkusio/quarkus#26024]
### Describe the bug

Entity having colums annotated with @CreationTimestamp and @UpdateTimestamp are not automatically updated on entity persist with Hibernate Panache ORM.

### How to Reproduce?

Example Entity:

```
@Builder
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Insertion  {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "INSERTION_SEQ_GENERATOR")
	@SequenceGenerator(name = "INSERTION_SEQ_GENERATOR", sequenceName = "INSERTION_SEQ", allocationSize = 50)
	@EqualsAndHashCode.Include
	private Long id;

	@UpdateTimestamp
	private LocalDateTime updatedAt;

	@CreationTimestamp
	@Column(nullable = false, updatable = false)
	private LocalDateTime createdAt;

}
```
Repository:
```
@ApplicationScoped
public class InsertionRepository implements PanacheRepository<Insertion> {

    public Stream<Insertion> findByCreatedBetween(Instant from, Instant to) {
        return find("created_at BETWEEN ?1 AND ?2", from, to).stream();
    }

}
```
Test Class:
```
@QuarkusTest
public class InsertionRepositoryUnitTest {

    @Inject
    InsertionRepository insertionRepository;

    @Test
    @TestTransaction
    public void should_populate_crated_at() {
         var insertion = Insertion.builder()
                .build();

        this.insertionRepository.persist(insertion);

        insertion = this.insertionRepository.findById(insertion.getId());

        Assertions.assertNotNull(insertion.getId());
        Assertions.assertNotNull(insertion.getUpdatedAt());
        Assertions.assertNotNull(insertion.getCreatedAt());
    }
}
```

### Output of `uname -a` or `ver`

Linux CH-ADN-3DVB3F3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final

**Comment by fastluca** [comment]
Small update: if I force the flush with `this.insertionRepository.flush()`, the fields are correctly updated.

**Comment by gastaldi** [comment]
> Small update: if I force the flush with `this.insertionRepository.flush()`, the fields are correctly updated.

AFAIR this is the intended behavior. WDYT @Sanne ?

**Comment by Sanne** [comment]
right, operations are only executed when the transaction commits.
