### ISSUE TITLE
@Transactional does not work in Quarkus tests

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2602]
Running test methods does not respect the `@Transactional` annotation. Since users are testing entity methods in their tests, they expect transactions to work (without transactions, Hibernate does not seem to execute any code #2172).

@mkouba @stuartwdouglas any idea why CDI interceptors would not work for test methods? Is this not supported yet? Or not supported on purpose?

**Comment by mkouba** [comment]
AFAIK test instances are not CDI beans and so interceptors are not supported. However, we could make it work using `BeanManager.resolveInterceptors()`... we already use this kind of trick for MP rest client.

**Comment by stuartwdouglas** [comment]
It might be easier to just make the test a bean, but it will result in fairly different behaviours between the native image and JVM mode ones. The behaviour is already different though so I don't know if that is really a problem.

**Comment by mkouba** [comment]
> It might be easier to just make the test a bean...

I think we discussed this already and for some reason (I don't remember the details) we decided not to make them beans...

**Comment by stuartwdouglas** [comment]
The conversation just kinda stalled, it was not really decided against. The original PR that made them beans had some unrelelated problems, and there was a lot of debate about how transactions should be handled, so it just kinda got lost.

**Comment by mkouba** [comment]
I know we had to add quite some hacks because of the test instances are not beans - `InjectionPoint` metadata injection, skip removal of injected beans, etc. So if we decide to go this way (test instance -> bean instance) we should not forget to do a proper cleanup.

**Comment by emmanuelbernard** [comment]
In particular people need to do the following

```
@QuarkusTest
public class MyTests
@Test
	public void testThatAPersonCanBeRetrievedByName() {
		
		/callInTransaction();
		
		// When
		final Person retByID = Person.findById(person.id);
		final Person retByName = Person.findByName("Bob");
		
		// Then
		Assertions.assertNotNull(retByID);
		Assertions.assertNotNull(retByName);
	}

        @Transactional // note the private, should we make things public by bytecode transformation? or throw an exception
        private void callInTransaction() {
		// Given
		final Person person = new Person();
		person.name = "Bob";
		person.birth = LocalDate.now();
		person.status = Status.ALIVE;
		
		person.persist();

        }
}
```

**Comment by mkouba** [comment]
This wouldn't work even if the test instances were intercepted beans. "self-invocation" is not a business method from the CDI POV and so interceptors are not applied. Also why the private stuff?

**Comment by emmanuelbernard** [comment]
@mkouba because I would have done it like that not knowing the CDI restrictions. Since it's build time bytecode enhancement, you could make the self invocation intercept ;)
But we would go far from the spec which probably sucks unless we restrict it to tests maybe?

Or simply have a `doInTransaction` helper method that would do the tx start / stop for the user @Sanne ?

**Comment by FroMage** [comment]
A `doInTransaction` is a very useful thing. Where would it live?

**Comment by stuartwdouglas** [comment]
QuarkusTransaction.doTransaction in the TX module would be my preference. There probably should be a method for each type of transaction attribute though, doInTransaction is not really clear if it would stay within an outer transaction or always create a new one.

**Comment by Sanne** [comment]
+1 for a `doInTransaction` helper. We have such helpers within the ORM testsuited and they've proven to be useful.

But let's start simple and not overload it too much? For example I wouldn't personally be able to guess what the differences are between `doInTransaction` and `doInNewTransaction`

Should we really use the _QuarkusX_ prefix ? Seems unnecessary to me.

**Comment by emmanuelbernard** [comment]
My proposal would be to have `doInTransaction(Runnable)` doing the nested approach.
Then have an overloaded methid `doInTransaction(Transactional.TxType,Runnable)` to override the semantic the same way `@Transactional` would.
