### ISSUE TITLE
Add some way to keep an original name of a dependency jar when it is placed in `target/lib` directory

### ISSUE THREAD

**Issue by ynojima** [quarkusio/quarkus#26039]
### Description

When using `legacy-jar` type, Quarkus renames a dependency jar with `<groupName>.<fileName>` format when placing it in `target/lib` directory.
https://github.com/quarkusio/quarkus/blob/2.7.5.Final/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java#L907

Since some libraries is not designed to be renamed, there should be some workaround.
https://stackoverflow.com/questions/65003590/quarkus-and-provided-dependencies-sapjco3-jar

### Implementation ideas

- Add an option to keep original file name
- Add an option to add an external directory to classpath

**Comment by geoand** [comment]
Thanks for reporting.

Looking at the stackoverflow response (cc @loicmathieu) there seems to be a workaround. Given that, the fact that this is a very  niche use case and the the fact that the fast-jar does not do this sort of rename, I am going to close this as `won't fix`.

**Comment by ynojima** [comment]
@geoand, Thank you for quick response.
The workaround mentioned in the stackoverflow seems an unintended behavior, and might be changed in the future version.
It's hard to rely on.

> the fact that the fast-jar does not do this sort of rename,

Is that true? As far as I checked, fast-jar packaging also renames the dependency jar files with `<groupName>.<fileName>` format.
