### ISSUE TITLE
Generate REST CRUD Resource based on Entity Model

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#2603]
**Description**
Like we had in JBoss Forge, it would be nice to be able to generate a REST Resource with the 4 CRUD methods based on an entity. 

**Implementation ideas**
Looks like the "framework" to support this is already there (templating etc ..): https://github.com/quarkusio/quarkus/tree/master/devtools/common/src/main/java/io/quarkus

**Comment by stuartwdouglas** [comment]
I think we need to be careful with what we do code generation wise. I think we should definitely support it rather than just doing this ad-hoc I think we need to consider all the use cases and exactly how we want it to work.

**Comment by FroMage** [comment]
I'd much rather have a CRUD extension that allows me to have a Web UI that lets me do CRUD operations on any entity, like we've been using for years for RDEV @sebastienblanc .

This allows people to build admin interfaces super quickly.

**Comment by sebastienblanc** [comment]
@FroMage I like this feature as well but it's more like a dynamic scaffolding at runtime , correct ? 
My idea idea was more of a "one-shot" code generation command available through a maven/gradle/aesh command.

**Comment by gastaldi** [comment]
There are `PanacheEntityResource` and `PanacheRepositoryResource` classes for this matter. 

More info at https://quarkus.io/guides/rest-data-panache
