### ISSUE TITLE
QuarkusProdModeTest should pick up the dependencies with scope "test" in Maven

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#26044]
### Describe the bug

If I have the following pom:

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache-deployment</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2-deployment</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jsonb-deployment</artifactId>
            <scope>test</scope>
        </dependency>
```

And I'm using the `QuarkusProdModeTest` JUnit extension as:

```java
@RegisterExtension
    static final QuarkusProdModeTest TEST = new QuarkusProdModeTest()
            .withApplicationRoot((jar) -> jar
                    .addAsResource("application.properties")
                    .addAsResource("import.sql"))
            .setRun(true);
```

This won't work because the Quarkus dependencies declared with scope `test` won't be included. Therefore, I had to include them as forced dependencies:

```java
@RegisterExtension
    static final QuarkusProdModeTest TEST = new QuarkusProdModeTest()
            .withApplicationRoot((jar) -> jar
                    .addAsResource("application.properties")
                    .addAsResource("import.sql"))
            .setForcedDependencies(List.of(
                    new AppArtifact("io.quarkus", "quarkus-jdbc-h2-deployment", Version.getVersion()),
                    new AppArtifact("io.quarkus", "quarkus-resteasy-jsonb-deployment", Version.getVersion())))
            .setRun(true);
```

Note that the other JUnit extensions as `QuarkusUnitTest` and `QuarkusDevModeTest` include the test dependencies. So, I think `QuarkusProdModeTest` should work the same.

**Comment by geoand** [comment]
I am not sure about this... I actually think the current behavior is more correct

**Comment by Sgitario** [comment]
I see that the `QuarkusProdModeTest` extension should be the most realistic mode, but taking into account that is a test extension and the other extensions already work like this, I'd be more in favor of changing it. 

Having said that, as there is an easy workaround, feel free to close this issue without not doing it as we can always reopen it if more people ask for it.
