### ISSUE TITLE
Native image fails to start due to missing libfreetype.so.6 library and glibc version 2.29

### ISSUE THREAD

**Issue by chimanos** [quarkusio/quarkus#26058]
### Describe the bug

Hello,

I'm currently trying to run a Docker container based on native image using `quarkus-container-image-docker`.
I'm also using `quarkus-awt` because I use ImageIO to read and write images.

When I try to run the container I have the follinwg error: 

=> `./application: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
`
I know the ubi container doesn't have libfreetype by default so I tried to add libfreetype manually in the container using:

=> `RUN microdnf install freetype fontconfig`

After running this in the container, the error about libfreetype disappears but I have a new error I'm stuck with:

=> `./application: /lib64/libm.so.6: version GLIBC_2.29 not found (required by ./application)
`

My current Dockerfile:

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5

RUN microdnf upgrade
RUN microdnf install freetype fontconfig

WORKDIR /work/

RUN chown 1001 /work && chmod "g+rwX" /work && chown 1001:root /work

COPY --chown=1001:root build/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

Thanks for your help.

### Expected behavior

The application should start.

### Actual behavior

Without libfreetype:

`./application: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory`

With libfreetype added:

`./application: /lib64/libm.so.6: version GLIBC_2.29 not found (required by ./application)`

### How to Reproduce?

Steps to reproduce:

1) Add  `quarkus-container-image-docker` and `quarkus-awt`.
2) Use ImageIO.write or ImageIO.read
3) Build the docker container using native image
4) Try to run the container

### Output of `uname -a` or `ver`

Linux rpamart-XPS-15-9560 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1) OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### GraalVM version (if different from Java)

graalvm-ce-java17-22.1.0

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2  Build time:   2022-03-31 15:25:29 UTC Revision:     540473b8118064efcc264694cbcaa4b677f61041  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.3 (Private Build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1) OS:           Linux 5.11.0-43-generic amd64

**Comment by gsmet** [comment]
My guess is that the libraries you have locally are not compatible with the container image you are using.

I would recommend to do the native build in a compatible container with `-Dquarkus.native.container-build=true`.

**Comment by chimanos** [comment]
Hello, thanks for your reply.

I tried to use the container build (I use this to build the production image with Github Action) but I have the same problem (libfreetype).

**Comment by Karm** [comment]
Hello, 
You need glibc and additional libraries (in case of AWT) to be compatible between the system the binary is built and the system where it runs. It is generally O.K. to build with older, e.g. Ubuntu 18 and run with newer, e.g. CentOS 8 Stream.
It does not work to build with newer, e.g. Ubuntu 20 and run with older, e.g. CentOS 8 Stream.

What you can do is to rely on a builder image to run the build in a container, e.g. as we did with the CI here, where we needed to switch to Ubuntu 20 GitHubAction worker while our server is set on CentOS 8 Stream: [Start using builder image](https://github.com/Karm/collector/pull/9/files#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R40)

Regarding additional libraries needed for AWT and what would need to be in your system or *runtime* image, check: https://github.com/quarkusio/quarkus-quickstarts/blob/9c794616777c546e3fb1ab0a7d8ba7daef1830b8/awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native#L24
