### ISSUE TITLE
ExceptionMapper does not work when using RESTEasy reactive routes

### ISSUE THREAD

**Issue by jehrenzweig-leagueapps** [quarkusio/quarkus#26056]
### Describe the bug

I'm trying to globally handle a custom exception that's thrown when a RESTEasy reactive endpoint, written in Kotlin, is called.  When I submit the following `GET` request via Postman:
```
http://localhost:7333/greetings/null
```

The request gets processed by the following endpoint:
```
@Singleton
class HelloWorldController {
    @Route(methods = [Route.HttpMethod.GET], path = "/greetings/:name", produces = [MediaType.TEXT_PLAIN])
    fun greetingsToPerson(@Param name: String): Uni<String> {
        if (name == "null") {
            throw CustomException("Argument \"name\" contains an invalid value.")
        }

        return Uni.createFrom().item("Greetings, ${name}!")
    }
}
```

The application contains the following custom global exception handler:
```
import com.example.exceptions.CustomException
import com.example.models.ProblemDetails
import javax.ws.rs.core.Response
import javax.ws.rs.ext.ExceptionMapper
import javax.ws.rs.ext.Provider


@Provider
class CustomExceptionHandler : ExceptionMapper<CustomException> {
    override fun toResponse(e: CustomException): Response {
        var problemDetails = ProblemDetails(
            status = Response.Status.BAD_REQUEST,
            detail = "Something bad happened.",
            data = mapOf("someValue" to e.someValue)
        )

        var response = Response
            .status(problemDetails.status)
            .entity(problemDetails)
            .build()

        return response
    }
}
```

### Expected behavior

The `CustomExceptionHandler.toResponse()` method should be called, which would then produce a response that looks something like this:
```
{
    "status": 400,
    "detail": "Something bad happened.",
    "instance": null,
    "data": {
        "someValue": "This value was set by the CustomException(message: String) constructor."
    },
    "type": "about:config"
}
```

### Actual behavior

The `CustomExceptionHandler.toResponse()` method is not being called; a response body like this is being returned instead:
```
{
    "details": "Error id 315741ed-bb70-4bf9-8ebd-3a97a8d7d9ec-3, com.example.exceptions.CustomException: Argument \"name\" contains an invalid value.",
    "stack": "com.example.exceptions.CustomException: Argument \"name\" contains an invalid value.\n\t<STACK TRACE SPAM>"
}
```

### How to Reproduce?

See https://github.com/jehrenzweig-leagueapps/quarkus-global-exception-handling/ for an example of this behavior.

### Output of `uname -a` or `ver`

Darwin Kernel Version 19.6.0

### Output of `java -version`

Java(TM) SE Runtime Environment (build 1.8.0_301-b09)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
Reactive Routes (not to be confused with RESTEasy Reactive) does not support JAX-RS types like ExceptionMapper
