### ISSUE TITLE
Bean tree/graph in Quarkus Dev UI

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#26065]
### Description

In the Quarkus Dev UI it would be really cool to see how beans are being pulled in. Like a tree or graph showing the hierarchy of bean resolution.

I have a few beans that I think should be considered "unused", but they are still pulled in (I know because they fail with missing config properties). It would be helpful to debug these cases.

**Comment by mkouba** [comment]
Yep, a dependecy graph might be useful. We had a similar feature in [Weld Probe](https://weld.cdi-spec.org/news/2016/10/07/tip2-devmode/).

That said, a bean can be considered _unremovable_ for many reasons: is annotated with `@Named`, declares an observer, is excluded from removal by an extension, etc. So it might make sense to add some TRACE logging with exatct reason.
