### ISSUE TITLE
Azure Web App - Websocket is closed once the client (browser) receive a message

### ISSUE THREAD

**Issue by spaykit** [quarkusio/quarkus#26063]
### Describe the bug

For simplicity I deployed Quarkus's websockets-quickstart to an Azure-Webapp using maven plugin.
Websocket is closed once it receive a message at the client side (browser). 

### Expected behavior

Websocket should receive messages from chat.

### Actual behavior

On the 3rd message I send, I can see the error message at the console that `WebSocket is already in CLOSING or CLOSED state.`
![image](https://user-images.githubusercontent.com/46862743/173154841-50248829-0973-4d0e-af5e-b8a3f4d85797.png)

### How to Reproduce?

Steps to reproduce:
1. git clone https://github.com/quarkusio/quarkus-quickstarts.git
2. cd websockets-quickstart
3. edit index.html at line 81 from 'ws' to 'wss'
4. add application.properties under src/main/resources
5. add 'quarkus.http.port=80' to application.properties
6. add 'quarkus.package.type=uber-jar' to application.properties
7. configure azure webapp plugin by executing: mvn com.microsoft.azure:azure-webapp-maven-plugin:2.3.0:config
8. (linux, java 11)
9. mvn package azure-webapp:deploy
10. navigate to the deployed app

This is the deployed app https://quarkus-websockets-quickstart.azurewebsites.net/

### Output of `java -version`

11

### Quarkus version or git rev

2.9.2.Final

**Comment by gastaldi** [comment]
No errors in the application log?

**Comment by spaykit** [comment]
> No errors in the application log?

The log is clean.
[2022_06_10_pl1sdlwk00029K_default_docker.log](https://github.com/quarkusio/quarkus/files/8884058/2022_06_10_pl1sdlwk00029K_default_docker.log)

**Comment by spaykit** [comment]
I added a CloseReason to:
```
@OnClose
    public void onClose(Session session, @PathParam("username") String username, CloseReason closeReason) {
        LOG.info("Closing session " + session.getId() + " for user " + username);
        LOG.info("CloseReason: " + closeReason.getReasonPhrase() + " Code: (" + closeReason.getCloseCode() + ")");
        sessions.remove(username);
        broadcast("User " + username + " left");
    }

```
It seems that the code is (GOING_AWAY)

```
2022-06-11T16:32:49.541513976Z: [INFO]  2022-06-11 16:32:49,541 INFO  [org.acm.web.ChatSocket] (vert.x-eventloop-thread-1) Closing session u9cSze3niJuiG6xKecOrZ-zs_6nrPv3cOL5KFWPX for user daniel

2022-06-11T16:32:49.542790949Z: [INFO]  2022-06-11 16:32:49,541 INFO  [org.acm.web.ChatSocket] (vert.x-eventloop-thread-1) CloseReason:  Code: (GOING_AWAY)
```

> 1001 indicates that an endpoint is "going away", such as a server going down or a browser having navigated away from a page.

**Comment by spaykit** [comment]
It was an issue @ Azure.
