### ISSUE TITLE
RefreshScope equivalent in Quarkus Arc

### ISSUE THREAD

**Issue by dicksonprof** [quarkusio/quarkus#26079]
### Describe the bug

Is there any way to refresh the beans during runtime that is trigger due to config change without having to restart the quarkus application

**Comment by manovotn** [comment]
Hmm, I don't think you can do that.
In theory, single change in configuration of a bean could cascade into many other beans depending on this one which (in worst case) can affect whole deployment so you'd be back to restart/redeploy anyway.

**Comment by mkouba** [comment]
It also depends on what _refresh_ actually means.. Could you be more specific?

**Comment by dicksonprof** [comment]
Was looking whether there is an equivalent of spring boot @RefreshScope. Example when we add change configs from a centralized configuration store, we would want to refresh the beans, example redis connections to different host.

We were looking at a use-case where we build remote agents in multiple servers, and we can refresh the config without a full restart.
It becomes a problem when we deploy the program in too many servers and need to restart all of them

**Comment by mkouba** [comment]
In CDI, all beans that declare a scope backed by an `AlterableContext` (all built-in contexts) can be destroyed/recreated via `javax.enterprise.inject.Instance.destroy(T)` and `javax.enterprise.context.spi.AlterableContext.destroy(Contextual<?>)`. And if I understand it correctly that exactly what `@RefreshScope` is for, or?

**Comment by manovotn** [comment]
> It also depends on what refresh actually means..

Good point, I assumed different requirements so disregard my earlier comment.

I agree that Spring's `@RefreshScope` is akin to CDI's ability to destroy bean with given scope (actually, it seems a bit like custom scope that does this for all its beans?).
Although in CDI you need to know which bean *instances* you want to destroy to use what Martin suggested.
Perhaps you could also create custom CDI scope for all these beans and then control their re-creation per-scope as opposed to per instance?

**Comment by mkouba** [comment]
> Although in CDI you need to know which bean _instances_ you want to destroy to use what Martin suggested.

In Quarkus, all built-in contexts implement the `io.quarkus.arc.InjectableContext` with method `InjectableContext#destroy()`  which destroys all existing contextual instances.

**Comment by mkouba** [comment]
Closed. @dicksonprof feel free to reopen if you have more questions.
