### ISSUE TITLE
Trouble with @RestHeader annotation

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#26076]
### Describe the bug

I'm trying to use @RestHeader annotation. Here is my test:

```java
@Path("/toto")
public class testResource {
    @GET
    public String test(@RestHeader String password) {
        return "header value:" + password;
    }
```

-> Postman with 'password' header return the value of the header. Nice.

```java
@Path("/toto")
public class testResource {
    @GET
    public String test(@RestHeader String newPassword) {
        return "header value:" + newPassword;
    }
```

-> Postman with 'newPassword' header return null .... ---> FAIL!

to make it work, i need to do that :

```java
@Path("/toto")
public class testResource {
    @GET
    public String test(@RestHeader("newPassword") String newPassword) {
        return "header value:" + newPassword;
    }
```

Do you know why ?

Not sure this behavior is explained somewhere...

### Output of `uname -a` or `ver`

linux

### Output of `java -version`

17

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.2

**Comment by geoand** [comment]
Do things work properly if you create a Quarkus test that uses RestAssured?

**Comment by srigano** [comment]
> Do things work properly if you create a Quarkus test that uses RestAssured?

Yes it does. But I need my code work not only on test mode :-)

**Comment by geoand** [comment]
My point is that if it works with a RestAssured test, then there is likely some mistake in the postman call.
I suggest using Wireshark to see what is going on at wire level
