### ISSUE TITLE
Ban org.javassist:javassist

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#26071]
### Describe the bug

Similar case as #26066

quarkus-scheduler depends on org.javassist:javassist but we do not manage it and so other platform participants may bring an incompatible version.

Hence we should start managing org.javassist:javassist.

**Comment by gsmet** [comment]
@ppalaga do you know what's bringing Javassist? Ideally we should get rid of it.

**Comment by ppalaga** [comment]
> do you know what's bringing Javassist? 

quarkus-scheduler via com.cronutils:cron-utils

> Ideally we should get rid of it.

Why?

**Comment by gastaldi** [comment]
> > do you know what's bringing Javassist?
> 
> quarkus-scheduler via com.cronutils:cron-utils (not sure this is the only path)

FTR I opened https://github.com/jmrozanec/cron-utils/pull/521 removing it as it doesn't seem to be used in the codebase

**Comment by ppalaga** [comment]
Should I remove the javassist commit from https://github.com/quarkusio/quarkus/pull/26069 ?

**Comment by gsmet** [comment]
If it's indeed not used by cron-utils, I would rather exclude it from there while waiting for @gastaldi 's PR to get in.

**Comment by ppalaga** [comment]
Ok, let me do it in #26069

**Comment by gastaldi** [comment]
> If it's indeed not used by cron-utils, I would rather exclude it from there while waiting for @gastaldi 's PR to get in.

FWIW cron-utils 9.1.7 is now out without the dependency on Javassist
