### ISSUE TITLE
Document recommended Kotlin version

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#26093]
### Description

The Quarkus BOM contains a Kotlin version (currently 1.6.21) which is also used for quite a few managed Kotlin dependencies. I suppose this is also the recommended Kotlin version to use when developing a Kotlin-based Quarkus app. I think it would make sense to mention this prominently in the [Kotlin guide](https://quarkus.io/guides/kotlin) and possibly also mention how to properly use a different version of Kotlin (with regards to the order of BOMs).

**Comment by geoand** [comment]
Good idea!

Would you like to take a shot at implementing this?

**Comment by knutwannheden** [comment]
I will make a PR with a basis for discussion.

**Comment by knutwannheden** [comment]
@geoand Writing this makes me wonder if it wouldn't make sense for the Quarkus BOM to include the Kotlin BOM `org.jetbrains.kotlin:kotlin-bom`. Thoughts?

**Comment by geoand** [comment]
That depends on what the BOM includes. If it only includes Kotlin stuff, then I think it's a good idea.

cc @gsmet

**Comment by gsmet** [comment]
AFAICS, the BOM is clean. Not sure it contains things we want that we don't have already.

**Comment by knutwannheden** [comment]
I am thinking it might include dependencies which the application developer may want (e.g. [kotlin-test-junit5](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test-junit5)), and having the Quarkus BOM already provide the "correct" version, would be nice, IMHO.

**Comment by gsmet** [comment]
If it makes sense, we can do it. Can you take care of it?

**Comment by knutwannheden** [comment]
@gsmet I will make it part of the PR.

**Comment by knutwannheden** [comment]
No idea about that, sorry. I suspect you will have to keep them in sync manually.
