### ISSUE TITLE
Reactive REST client: Configure Vert.x HttpClientOptions 

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#26116]
### Description

After switching from resteasy classic to reactive some rest-client call fails with `io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.` because of a large header in the response. 

[RestClientBuilderImpl](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive/runtime/src/main/java/io/quarkus/rest/client/reactive/runtime/RestClientBuilderImpl.java#L49) has a [clientBuilder](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientBuilderImpl.java#L62) that initialises with `httpClientOptions = new HttpClientOptions();`
It also has method `httpClientOptions(io.vertx.core.http.HttpClientOptions httpClientOptions)`, but it does not seems to be accessible programmatically or through configuration.

Workaround: Create a service provider for `org.eclipse.microprofile.rest.client.spi.RestClientListener`, use reflection to access `RestClientBuilder.clientBuilder`, then cast to `ClientBuilderImpl` and invoke `.httpClientOptions(new HttpClientOptions().whatEver(value))`.

### Implementation ideas

Expose all config for Vert.x client in config, not only 
[the timeout and a few others](https://github.com/quarkusio/quarkus/blob/853d8d789ab4ed7f168c4fdd1ac27c91d42cff5d/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/api/QuarkusRestClientProperties.java).

**Comment by geoand** [comment]
Reopening because https://github.com/quarkusio/quarkus/pull/27521 reverted the change in https://github.com/quarkusio/quarkus/pull/26495 that originally closed this issue.
