### ISSUE TITLE
quarkus.http.root-path not honored when using quarkus-undertow

### ISSUE THREAD

**Issue by BarDweller** [quarkusio/quarkus#26137]
### Describe the bug

Had an app using REST endpoints, with quarkus.http.root-path set to /myhttp/prefix without undertow, endpoints responded as expected, but app relied on injection of HttpServletContext via @Context, so added undertow dependency, and endpoints ceased functioning. 

Subsequently I found my endpoints were now back at the root, and ignoring the quarkus.http.root-path value. 

### Expected behavior

Endpoints should have remained functional at the expected paths, regardless of undertow being used or not.

the overall path should be something like.. 
{quarkus.http.root-path}/@ApplicationPath/@Path 

### Actual behavior

Once undertow was added 
```
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-undertow</artifactId>
    </dependency>  
```

the overall path stopped being 
{quarkus.http.root-path}/@ApplicationPath/@Path 

and became
@ApplicationPath/@Path 

### How to Reproduce?

I'll try to create a small github repo for an example if required. 

### Output of `uname -a` or `ver`

Linux MONSTA 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-post-Debian-1deb11u1) OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1deb11u1, mixed mode, sharing)

### GraalVM version (if different from Java)

graalvm-ce-java11-linux-amd64-22.1.0.tar.gz

### Quarkus version or git rev

<quarkus.platform.version>2.6.3.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 Maven home: /usr/share/maven Java version: 11.0.15, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix"

### Additional information

Additionally quarkus.http.root-path doesn't seem to work with WebSockets registered programmatically via the ServerApplicationConfig route. This may be related if undertow is involved in websocket hosting?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
