### ISSUE TITLE
`quarkus.smallrye-openapi.servers` property should be configurable at runtime

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#26136]
### Description

The `quarkus.smallrye-openapi.servers` property is currently a build-time only property. This should be configurable at runtime.

The use case was discussed in #26124, but the **TL;DR;** is that users may have `quarkus.swagger-ui.always-include=true` set in their configuration. If so, when the application is deployed anywhere but on the user's local machine, the Swagger UI "try it" no longer works because it is attempting to connect to http://localhost.

Furthermore, it would be pretty impossible to know the URLs of where an application is going to be deployed at build time.

@phillip-kruger did provide a workaround - use the `mp.openapi.servers` property at runtime instead of `quarkus.smallrye-openapi.servers`, but shouldn't a configuration property that references a URL be configurable at runtime (like with things like databases/rest clients/etc)?

**Comment by JohnneSouza** [comment]
This feature doesn't work on Native Mode (when comes to a value from an environment variable).

**Comment by edeandrea** [comment]
Which feature? The `quarkus.smallrye-openapi.servers` property or `mp.openapi.servers`?

**Comment by nicolas-vivot** [comment]
The documentation clearly refers to a specific Quarkus environment variable, so unless the documentation is wrong it should be runtime instead of build time, and this has nothing to do with JVM or Native modes.

**Comment by JohnneSouza** [comment]
@nicolas-vivot Yeah, that's what I meant, sorry for the lack of details.
