### ISSUE TITLE
Request logging does not work in @QuarkuTests

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#26138]
### Describe the bug

[This reproducer](https://github.com/oscarfh/quarkus-request-log-issue) shows the issue: there I used a template from code.quarkus.com and the [resteasy reactive client tutorial](https://quarkus.io/guides/rest-client-reactive) and tried to log the traffic as described in the [documentation](https://quarkus.io/guides/rest-client-reactive#logging-traffic).

If I run `./gradlew quarkusDev` and manually open my browser in `localhost:8080/hello`, then I can see the request logs. The problem is that this does not happen in tests: if I run a test using `@QuarkusTest`, the logs are not shown.
(The same applied to CLI applications).

### Expected behavior

Logs should be shown both in tests and in "production" environments.

### Actual behavior

Log configuration is ignored in tests.

### How to Reproduce?

Reproducer: https://github.com/oscarfh/quarkus-request-log-issue

1. Check out the repository
2. Run `./gradlew quarkusDev`
3. Open localhost:8080/hello in your browser/curl
4. Notice that there are logs for the call made to `https://stage.code.quarkus.io/api`
5. Stop the app
6. Run org.acme.ApplicationMainIT#myTest
7. Notice how the traffic logging does not happen

### Output of `uname -a` or `ver`

Linux laptoip 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1) OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

2.9.2.Final

**Comment by albers** [comment]
https://stage.code.quarkus.io/ is down at the moment (showing "Failed to load Quarkus config" but still serving a status code of 200).

I came across this issue while trying the _rest-client-reactive-quickstart_, too.

Maybe your issue is caused by that.

**Comment by albers** [comment]
https://stage.code.quarkus.io/ is available again.

**Comment by oscarfh** [comment]
@albers Thanks for you reply, but that was not the case because I got the replies when debugging and because when running the application as jar, the logs were printed.

**Comment by geoand** [comment]
This has to do with how logging is (not) configured in generated Gradle projects.

In Maven projects we make sure that JBoss Logmanager is used (by setting a system property for surefire and failsafe), but in Gradle projects we don't do this.

By adding:

```gradle
test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
```

logging works correctly.

@glefloch @gsmet @dmlloyd any idea why we don't do ^?

**Comment by dmlloyd** [comment]
Not sure; it seems reasonable to me.

**Comment by glefloch** [comment]
That's what we do in sample test projects and what recommanded in the doc. I can add it to the gradle code start as well, I don't know why it's not the case yet

**Comment by geoand** [comment]
Okay thanks.

Let's add it then as logging in tests is pretty broken without it.
