### ISSUE TITLE
RESTEasy Reactive: Support for "quarkus.resteasy-reactive.ignore-application-classes" Configuration

### ISSUE THREAD

**Issue by mkueng1** [quarkusio/quarkus#26145]
### Description

I tried migrating from RESTEasy Classic to RESTEasy Reactive.
As I have multiple JAX-RS applications which seems to be still not supported I have the need to ignore them in the ResteasyReactiveScanner. Actually, these would also fail as the Scanner doesn't inject the CDI bean members.
Therefore I'm currently using the configuration property "quarkus.resteasy.ignore-application-classes=true" in combination with the property "javax.ws.rs.Application" and let RestEasy instantiate my application class (org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap).
As there are a few discussions in the issues about the usefullness of the Application - in my case there many resource/api classes some of them used in most of my "service" applications, but also common JsonB configuration, ExceptionMappers ... but of course not everything is relevant for every project.

### Implementation ideas

Use the configuration property "quarkus.resteasy-reactive.ignore-application-classes" in ResteasyReactiveScanner analogous to ResteasyServerCommonProcessor.

**Comment by geoand** [comment]
There are various ways to effectively do the same thing:

*  https://quarkus.io/guides/all-config#quarkus-core_quarkus.class-loading.removed-resources-removed-resources 
* Annotate with `@IfBuildProperty` / `@UnlessBuildProperty`

**Comment by geoand** [comment]
I can't say I understand the problem you are describing with `quarkus.class-loading.removed-resources`.

**Comment by mkueng1** [comment]
```
                   com.web-lib.AbstractApplication (web-lib.jar)
                    /                           \
                   /                             \
        com.app1.App1Application        com.app2.App2Application
```
I have AbstractApplication (extends Application) in web-lib.jar which is included in app1 and app2 where App1Application extends from it and just adds its applications specific resources so that these are added to the common resources defined/added by AbstractApplication (ExceptionMapper, JsonB configuration, RequestFilter, ...)

**Comment by geoand** [comment]
So then why not exclude `App1Application` and `App2Application`?

**Comment by mkueng1** [comment]
App1Application (and App2Application) are the real implementations with project/application/microservice specific rest resource endpoints yet having some common resource endpoint plus the common configuration.

**Comment by geoand** [comment]
I still don't understand why you can't exclude `App1Application` and/or `App2Application`?
If you did that, would it not solve your problem?

**Comment by mkueng1** [comment]
Now it works for me. I got a bit misled as concrete and abstract javax.ws.rs.core.Application implementations of the library are listed in the error message that only one is supported. It would be really a benefit having the possibility of multiple Application implementations same as in JEE servers or at least have the possibility when bringing in the servlet engine (which I need anyway for static resource filters).
Perhaps it helps someone stumbling over this ticket:
- I'm using `quarkus.class-loading.removed-resources` to leave out the concrete implementation class of the library
- implementing the library's abstract Application
- had to rewrite all ExceptionMappers as CDI Inject's are not supported in the Application class with programmatic lookups (if RestEasy instantiates CDI is supported)
