### ISSUE TITLE
Starting from 2.9.0.Final container-image-jib requires a configured container runtime if not directly pushing the image

### ISSUE THREAD

**Issue by wpernath** [quarkusio/quarkus#26146]
### Describe the bug

My typical use case for container-image-jib is to create tekton pipelines which are easily producing container images in Kubernetes / OpenShift. But with the new behaviour of quarkus-container-image-jib, I can't have separate build steps any longer as the pure build requires a docker/podman environment to be available, which is not the case in an OpenShift environment. 

(See here: [Getting GitOps Example](https://github.com/wpernath/book-example.git) in the folder /gitops/tekton).

### Expected behavior

Having a possibility (for example via a property `quarkus.container-image.jib.storeindockerregistry=false`) to use container-image-jib to produce a container image without the requirements of having a properly setup Docker/Podman environment.

### Actual behavior

Build breaks with an IllegalStateException:

`[package : mvn-goals] [ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.IllegalStateException: No container runtime was found to. Make sure you have Docker or Podman installed in your environment.
[package : mvn-goals] [ERROR] 	at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:38)
[package : mvn-goals] [ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.createContainerizer(JibProcessor.java:275)
[package : mvn-goals] [ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:220)
[package : mvn-goals] [ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:166)
[package : mvn-goals] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[package : mvn-goals] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[package : mvn-goals] [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[package : mvn-goals] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[package : mvn-goals] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[package : mvn-goals] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[package : mvn-goals] [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[package : mvn-goals] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[package : mvn-goals] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[package : mvn-goals] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[package : mvn-goals] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[package : mvn-goals] [ERROR] -> [Help 1]`

### Output of `java -version`

17.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.5

**Comment by geoand** [comment]
IIUC, you want to create a container image locally and **not** push it, but also **not** use docker / podman?

If so, then Jib cannot do that.

**Comment by geoand** [comment]
No problem :)
