### ISSUE TITLE
Move undertow-handlers.conf to application.properties

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2615]
This is a follow-up to https://github.com/quarkusio/quarkus/issues/2533

**Description**
One of the key features in Quarkus is the unified configuration (everything in one place). By allowing configuration to be set in a separate file, this breaks the one-config philosophy.

**Implementation ideas**
Move the `undertow-handlers.conf` contents to an entry in `application.properties` (eg. `quarkus.undertow.handlers`)

cc @dmlloyd @stuartwdouglas

**Comment by dhartford** [comment]
Recently ran into this challenge, it may be something to address on a 'feature' basis? For example, there is a CORS filter configuration, but I was looking for a response Cache-control feature to specify a pattern of files with no-cache, but couldn't find an elegant way to handle that scenario.

**Comment by stuartwdouglas** [comment]
This is complicated now by the base layer being vert.x. We can implement basically the same thing in vert.x but application.properties is not really a great file for this as properties files do not really support the ordering that this sort of file needs. 

We could do something with ordinals like 

quarkus.http.handler.1=set(%{o,Cache-Control,no-cache})

But I am not really sure if I like it.

**Comment by dmlloyd** [comment]
One existing example of a case where ordering is required in an essentially unordered string-based system is the convention of using file names for configuration stages in various *nix programs.

For example, `sysctl.d` uses a convention of `<nn>-description.conf`, where `<nn>` might be a zero-padded digit sequence.  The files are sorted lexicographically.

It's important that any configuration that is spread across multiple config properties be treated as a sparse array.  This allows different configuration layers to insert items at arbitrary points, and also means we don't have to renovate the existing config implementation (again).

**Comment by dhartford** [comment]
From a developer-consumer point of view, I've seen enough similar ordinal-based configurations that it isn't necessarily foreign.  If do choose to go that route, just need some scenario/examples so developers can run with it.

> quarkus.http.handler.1=set(%{o,Cache-Control,no-cache})

The 'in application.properties' versus separate files will forever be a never ending debate, first functional in whatever way is quickest to get feedback :-D  (maybe undertow-experimental.properties type files to both classify which extension it is specific to, and to identify it as experimental)

**Comment by gsmet** [comment]
@dhartford weren't you talking about applying the headers only for specific files? If so I wonder if implementing a Vert.x filter wouldn't be easier than providing something in the `application.properties`.

**Comment by dhartford** [comment]
@gsmet  Based on my initial experience and cross-referencing 'the internet' (i.e. stackoverflow, quarkus dev group on google, blogs, quarkus extensions and guides, etc) there is confusion, at least for me, on where/how to do 'non-functional-feature x' (such as setup the nocache headers).  My first thought was undertow, which may have gone down a path that may not be correct.

Would you have an example of how to accomplish something like Cache-Control=no-cache on the http response headers for specific files as a vert.x filter within the quarkus ecosystem? 

(reviewing 3312 and a snapshot of the CORS filter impl, I can see where this might get a bit challenging: https://github.com/quarkusio/quarkus/commit/31b8852cdcb0c08a3c0c5036034357184e426ba2 )

**Comment by stuartwdouglas** [comment]
I don't think we should do this, closing. If we were going to do anything like this then it should be done at the vert.x level.
