### ISSUE TITLE
Report invalid @MultipartForm format

### ISSUE THREAD

**Issue by Ratoone** [quarkusio/quarkus#26158]
### Description

In case a `multipart/form-data` request is handled, for example:
```java
@ApplicationScoped
@Path("/uploads")
public class UploadsResource {
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public Response upload(@MultipartForm UploadDto uploadDto) {
        // do sth
    }
}
```
With a DTO:
```java
@Getter
@NoArgsConstructor
public class UploadDto {
    @FormParam("format")
    @PartType(MediaType.APPLICATION_JSON)
    private List<MyEnum> format;

    @FormParam("file")
    @PartType(MediaType.APPLICATION_OCTET_STREAM)
    private File file;
}
```
If the `format` is provided correctly, it works as expected, otherwise it fails silently with a 500 - whether the JSON is wrongly formatted or the elements do not respect the `MyEnum` values. But in this case I want to be able to notify the user that the request is wrong, returning a custom message - or at least being able to see in the logs why the request failed.

**Comment by geoand** [comment]
Thanks for reporting. https://github.com/quarkusio/quarkus/pull/26170 takes care of it
