### ISSUE TITLE
quarkus-cli failing to install

### ISSUE THREAD

**Issue by mkmpnataraj** [quarkusio/quarkus#26166]
### Describe the bug

Quarkus CLI depends on internet explorer -- which is not available on windows.

- Please make it installable via winget : https://docs.microsoft.com/en-us/windows/package-manager/winget/

```log
PS> iex "& { $(iwr https://ps.jbang.dev) } trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/"
iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:12
+ iex "& { $(iwr https://ps.jbang.dev) } trust add https://repo1.maven. ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d
```

```
winget install quarkus-cli
No package found matching input criteria.
```

**Comment by maxandersen** [comment]
Winget don't allow zip based installs yet. 

What version of windows are you running here ? This been working for 2+ years so wonder what changed ?

**Comment by gsmet** [comment]
Probably a good idea to get to the bottom of this as @maxandersen asked but you have installation alternatives for Windows here: https://quarkus.io/guides/cli-tooling .

**Comment by mkmpnataraj** [comment]
Windows version: Version	10.0.19042 Build 19042

>so wonder what changed ?

Windows introduced their own package manager, winget, So people may not prefer to install scoop/chocolaty (I've used those in the past). Simple binary download would make it easy (similar to maven and other tools). Integration with winget would be great too.

**Comment by maxandersen** [comment]
If you can point to winget apps that installs without a windows specific installer let me know. 

Afaik the feature is just not available yet though it is planned in winget 1.3. 

https://github.com/microsoft/winget-cli/issues/182

So no we cannot provide this yet. Soon. But not yet.

**Comment by mkmpnataraj** [comment]
> Simple binary download 

Do we have binary download, i.e no need for choco/scoop?

**Comment by maxandersen** [comment]
If you mean a native executable. No. That is not there (yet). 

If you mean a jar then yes there is a single jar you can download and run. That is what all of these tools to download installs and setup. 

See the direct url for latest released jar in this file: https://github.com/quarkusio/jbang-catalog/blob/296cdd84656d1be94f5d4477b8d556a5eb332cad/jbang-catalog.json#L23

**Comment by maxandersen** [comment]
fyi, got access to my windows install again and could test this.

Can you try `iex "& { $(iwr -Uri https://ps.jbang.dev/ -UseBasicParsing) } app setup"` apparently without internet explorer default commands in  windows needs extra argument which is unfortunate.
