### ISSUE TITLE
Quarkus Reactive support download multiple files multipart/form-data

### ISSUE THREAD

**Issue by eye0fra** [quarkusio/quarkus#26164]
### Description

Quarkus Reactive supports multipart response thanks to the #21038 commit.

The download feature is incomplete, at least compared to the upload capability. In particular, I would like multiple files with their filename under the same `content-disposition` name to be generated as a list of `content-disposition` on the wire. I desire `List<FileDownload>` attribute in my multipart DTO to be supported. 

The code of `MultipartMessageBodyWriter` seems to cover only the multipart DTO with a simple static attribute (not a list), not a list of `FileDownload`. On the contrary, the upload supports lists of `FileUpload`. So the current implementation is not symmetric.

**Comment by geoand** [comment]
@Sgitario are you interested in this feature?
I think it shouldn't be too difficult - but I am also waiting for additional clarification.

**Comment by geoand** [comment]
@Sgitario do you want to take a look?

**Comment by Sgitario** [comment]
> @Sgitario do you want to take a look?

Sure, working on it.
