### ISSUE TITLE
Spring Data JPA sorting with NullHandling parameter

### ISSUE THREAD

**Issue by nrankovic** [quarkusio/quarkus#26172]
### Describe the bug

While using Spring Data JPA extension and its Sorting and Pageable API, I encountered an issue with NullHandling parameter. It looks like it is ignored while constructing SQL query. 

``` java
var order = new Sort.Order(Direction.DESC, "modifiedDate", NullHandling.NULLS_LAST);
```

I would expect `NULLS LAST` directive to be added before `limit` in this case. I guess this is something from Spring API that was overlooked, or perhaps I am not using it correctly.

### Expected behavior

Constructed SQL query to look something like this:

``` sql
...
order by
  ticket0_.MODIFIED_DATE DESC NULLS LAST limit ?
```

### Actual behavior

Constructed SQL query looks like this:

``` sql
...
order by
  ticket0_.MODIFIED_DATE DESC limit ?
```

### Output of `uname -a` or `ver`

Darwin my-hostname 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
Thanks for reporting!

I'll try and have a look next week

**Comment by geoand** [comment]
@Sgitario would you be interested in taking a look at this?
