### ISSUE TITLE
OpenShift binary build targeting to another namespace failing

### ISSUE THREAD

**Issue by fhavel** [quarkusio/quarkus#26180]
### Describe the bug

We have Jenkins running in OpenShift project/namespace (jenkins-namespace) and we have also another namespace(s) where Quarkus applications are deployed. Jenkins is running with Service Account "jenkins" which has access to another namespaces but implicitly "jenkins-namespace" is selected for it. When I try:
`mvn clean package -Dquarkus.openshift.namespace=target-namespace-name -Dquarkus.kubernetes.deploy=true`
then correct namespace is set in openshift.yaml, but OpenshiftProcessor is then trying to start build in user's current namespace (jenkins-namespace):

`[INFO] [io.quarkus.container.image.openshift.deployment.OpenshiftProcessor] Starting (in-cluster) container image build for jar using: BINARY on server: https://serverUrl/ in namespace:jenkins-namespace.`

This behaviour could be workarounded by calling `oc project target-namespace-name` beforehand.

### Expected behavior

Application is deployed in namespace which is defined by `quarkus.openshift.namespace` property

### Actual behavior

Build failure

### How to Reproduce?

``` bash
oc project jenkins-namespace
mvn clean package -Dquarkus.openshift.namespace=target-namespace-name -Dquarkus.kubernetes.deploy=true
```

**Comment by geoand** [comment]
@iocanel this is one you I believe as it seems Quarkus is populating the proper decorators

**Comment by Sgitario** [comment]
I was surprised that this issue is still around. https://github.com/quarkusio/quarkus/pull/31737 should fix this.
