### ISSUE TITLE
Poor rendering of AsciiDoc documentation of configuration properties in DevUI config editor

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#26199]
### Describe the bug

It seems the config editor in the DevUI does not render AsciiDoc at all, resulting in hard-to-read documentation for some configuration properties.

### Expected behavior

I would expect AsciiDoc to be rendered properly, or at least the asciidoc meta-characters to be removed (though that solution would make a mess of tables, for example...).

### Actual behavior

AsciiDoc is not rendered and instead is displayed as-is.

![Screenshot from 2022-06-17 10-13-17](https://user-images.githubusercontent.com/412878/174256583-3fb321fb-1916-4cb7-a956-24ea43016974.png)

### How to Reproduce?

Go to the config editor of an application that depends on an extension using asciidoc in the documentation of some of its configuration properties, e.g. Hibernate ORM or Hibernate Search (there are probably others).

### Quarkus version or git rev

2.10

**Comment by yrodiere** [comment]
One relatively low-effort solution could be to leave the asciidoc as-is but at least make sure line breaks are rendered as they are in the source (some CSS just for asciidoc should do the trick). We could always introduce full-blown AsciiDoc rendering later.

Ideally we'd also remove the trailing `@asciidoctlet`.

**Comment by phillip-kruger** [comment]
THis is fixed
