### ISSUE TITLE
Add property to set the global default Quartz misfire instruction

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#26208]
### Description

Basically the same as #24254, but that issue took a turn for job identity specific properties which is not a solution for me because we have over 50 occurrences of `@Scheduled`.
All of our crons (jobs respectively) are designed in a way that missing one run is not problematic since the next execution is not far away. Instead, the current default instruction to fire now _is very_ problematic because it causes a spike of executions after the service is back up.

So please introduce a global property.

### Implementation ideas

`quarkus.quartz.misfire-strategy` or maybe `quarkus.quartz.default-misfire-strategy`?
(FWIW, in Quartz it's called "misfire _instruction_", not "misfire _strategy_")

Identity-specific instructions should take precedence over the global one.

**Comment by machi1990** [comment]
+1. It makes sense to have a default/global.

**Comment by PratikDey** [comment]
Hey @machi1990 , I am new to open source. Can I work on this issue?

**Comment by famod** [comment]
Hi @PratikDey, I'm sure you can go ahead with that. Thanks!

**Comment by famod** [comment]
@PratikDey have you started working on this? If yes I'll assign the issue to you.

Btw, one thing to keep in mind with this is that there are different instructions (strategies) for different trigger types. So we might need more than one new property.

**Comment by PratikDey** [comment]
No @famod , since I am new to this project I am taking my time to understand how everything works. It would be nice if you could work on this issue with me.

**Comment by gsmet** [comment]
Fixed in https://github.com/quarkusio/quarkus/issues/24254 .

**Comment by famod** [comment]
As written in the description of this issue, the PR for #24254 did *not* add a global flag.
So I'll have to reopen this.

@PratikDey sorry, I'm very busy ATM.

**Comment by mun711** [comment]
@PratikDey , @famod I'd like to work on this issue, seems to be silent for quite a bit, but please let me know if there is something in progress already

**Comment by famod** [comment]
@mun711 not from my side and I don't think @PratikDey started working on this back then. So please do go ahead! Thanks.

**Comment by mun711** [comment]
@famod  I added 2 new config properties as part of a new config group for the default misfire policy. Could not find any way to define possible values for the configuration via existing config annotations or any such method, so added the possible value validation checks in QuartzSchedulerImpl similar to what was done for the per job configurations. Please let me know if there is a better mechanism in place to do this.

quarkus.quartz.default-misfire-policy.cron=smart-policy
quarkus.quartz.default-misfire-policy.simple=smart-policy

https://github.com/quarkusio/quarkus/pull/28716

**Comment by mun711** [comment]
The following properties were added
quarkus.quartz.cron-trigger.misfire-policy
quarkus.quartz.simple-trigger.misfire-policy

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/28716

**Comment by machi1990** [comment]
Thanks @mun711
