### ISSUE TITLE
Upgrade Netty to 4.1.78.Final

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#26211]
### Description

We are getting security scan failures with the current Netty 4.1.74.Final, I see there is a 4.1.78.Final available.  I have not verified they are fixed in 4.1.78.Final but seems Quarkus should always move to the latest service pack version to pickup bug fixes.

**Comment by geoand** [comment]
We do plan to do this soon, but it needs to be tested with Vert.x

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
We won't bump for now. We have found a graalvm bug that prevent native compilation.

**Comment by abstractj** [comment]
@cescoffier @geoand @dhoffer I was about to report a similar issue while reviewing the issues for Keycloak, when I found this ticket. The issue should be considered as low-impact considering that only Java 6, or below are impacted.

More details here:  https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-2812456

**Comment by cescoffier** [comment]
Yes, I am aware of the CVE, but let's say that Java 6 is slightly out of scope :-).
