### ISSUE TITLE
Messaginghub Pooled JMS extension

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#26219]
### Description

I'd like to introduce an extension for [messaginghub-pooled-jms](https://github.com/messaginghub/pooled-jms) which could provide the pooling and transaction manager integration support.

Also it is able to make `quarkus-artemis` to work with XA JTA transaction. see https://github.com/quarkusio/quarkus/issues/14871

The extension name could be `quarkus-pooled-jms`.

**Comment by zhfeng** [comment]
@gastaldi can you help me to create this extension on quarkivers?

**Comment by fvaleri** [comment]
Thanks @zhfeng.

When using Camel JMS component extension (which uses Spring JMS), the the producer creates one connection for every message, slowing down the application. This is much more evident when you enable TLS or transactions.

**Comment by zhfeng** [comment]
Thanks @gastaldi !
