### ISSUE TITLE
gRPC Context propagation does not work

### ISSUE THREAD

**Issue by shakhar** [quarkusio/quarkus#26222]
### Describe the bug

We use OpenTelemetry with Quarkus version of 2.9.2 that already has a support for gRPC.
We has a gRPC server that get a request with OpenTelemetry's context and the context isn't propagated to the service's handler.

In addition, I used the `GrpcTracingServerInterceptor` interceptor and saw that the interceptor gets the context. 
I think the problem is that this interceptor close the scope `scope.close()` and doesn't pass any contextual data to the handler level.

### Expected behavior

I expect to be able to use `Context.current()` inside the gRPC service's handler and get the context.

### Actual behavior

`Context.current()` returns an empty context.

### How to Reproduce?

1. Setup a gRPC service
2. Send a request with context to the service
3. Debug and look on the value of `Context.current()` inside the service's handler

### Output of `uname -a` or `ver`

Darwin ShakharArad 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 14.0.2 2020-07-14 OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          14.0.2 (AdoptOpenJDK 14.0.2+12) OS:           Mac OS X 10.16 x86_64

**Comment by radcortez** [comment]
We already implemented proper OTel Support for gRPC in https://github.com/quarkusio/quarkus/pull/24117, available since Quarkus 2.8.0.

Are you able to update your Quarkus version? We are not supporting Quarkus Community 1.x anymore.

**Comment by shakhar** [comment]
@radcortez I set the wrong version in the issue by mistake, the quarkus version we use is 2.9.2 and not 1.9.2.

**Comment by radcortez** [comment]
Ok, in that case, we will have a look.

**Comment by shakhar** [comment]
If it helps, I copied your `GrpcTracingServerInterceptor` and changed it according to [this](https://stackoverflow.com/questions/57370763/how-to-pass-data-from-grpc-rpc-call-to-server-interceptor-in-java) with `scope = spanContext.makeCurrent()` at the start of each function in `TracingServerCallListener` and  `scope.close()` at the end of each function (inside `finally` scope of the try catch). 

This change fixed the issue so you can adjust it to your `TracingServerCallListener` :)

**Comment by c0va23** [comment]
> If it helps, I copied your `GrpcTracingServerInterceptor` and changed it according to [this](https://stackoverflow.com/questions/57370763/how-to-pass-data-from-grpc-rpc-call-to-server-interceptor-in-java) with `scope = spanContext.makeCurrent()` at the start of each function in `TracingServerCallListener` and `scope.close()` at the end of each function (inside `finally` scope of the try catch).
> 
> This change fixed the issue so you can adjust it to your `TracingServerCallListener` :)

I reproduce this changes and can confirm - it work! Now span of gRPC interceptors and span created by code called into handler - is linked.

**Comment by radcortez** [comment]
Thanks!

If any of you could submit a PR with tests it would considerably speed up the process.
