### ISSUE TITLE
Missing details about constraint violations with GraphQL after a reload in dev mode

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#26233]
### Describe the bug

At first start in dev mode, if I execute an operation with values that fail bean validation, I get a proper error response with details about the constraint violation. But after a reload and executing the same operation, I get only a generic

```
{
  "errors": [
    {
      "message": "System error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "rate"
      ],
      "extensions": {
        "classification": "DataFetchingException",
        "code": "constraint-violation",
        "exception": "javax.validation.ConstraintViolationException"
      }
    }
  ],
  "data": {
    "rate": null
  }
}
```

**Comment by phillip-kruger** [comment]
Those are set using config. I wonder if that has something to do with rhis

**Comment by jmartisk** [comment]
This seems to be caused by the fact that in some cases, the validation is handled by our `io.smallrye.graphql.cdi.validation.ValidationService` which throws a `io.smallrye.graphql.cdi.validation.BeanValidationException` when necessary, but sometimes, instead of the validation service, it is handled by a Hibernate Validator interceptor directly. I'm not sure why sometimes that interceptor is called and sometimes not.
In any case, when it's handled by a HV interceptor, it throws a different exception (`javax.validation.ConstraintViolationException`) which is why the details aren't present in the response.

**Comment by jmartisk** [comment]
Ah no, so the problem is a bit different. Our `ValidationService` is always called (before the Hibernate Validator interceptor, which is also always called, but later), but after a reload, the service fails to detect the constraint validation, because:
It stores a `ValidatorFactory` inside a static variable: https://github.com/smallrye/smallrye-graphql/blob/1.6.0/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/validation/ValidationService.java#L19
And because this is a library class, it doesn't get reloaded, so it keeps using the original `ValidatorFactory` from before the reload, and that factory doesn't work properly anymore.
So the validation service returns without throwing an error, and then the HV interceptor, which runs later, picks up the violation.

So we either need to always repeat the CDI lookup for the `ValidatorFactory`, or detect that there has been a reload.
I'll prepare something for this tomorrow.
