### ISSUE TITLE
HttpFilter doFilter not called for /hello path.

### ISSUE THREAD

**Issue by whitingjr** [quarkusio/quarkus#26244]
### Describe the bug

 Using Quarkus Resteasy Reactive 2.9.2 I am using HttpFilter.doFilter implementations to add headers to a response. The issue is the doFilter method is not called.

### Expected behavior

The test assertions should pass.
```
              .header("quarkus", "rocks")
              .header("power", "ballad")
              .header("rock", "star")
```

### Actual behavior

Assertions reveal the header value(s) are not present.

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.466 s <<< FAILURE! - in org.jboss.perf.acme.GreetingResourceTest
[ERROR] org.jboss.perf.acme.GreetingResourceTest.testHelloEndpoint  Time elapsed: 1.514 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected header "quarkus" was not "rocks", was "null". Headers are:
content-length=28
Content-Type=text/plain;charset=UTF-8

	at org.jboss.perf.acme.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.java:18)

```

### How to Reproduce?

 Fetch my reproducer project named [acmewebreproducer](https://gitlab.cee.redhat.com/jwhiting/acmewebreproducer) to run the tests that assert the header values.
`$ ./mvnw package`

### Output of `uname -a` or `ver`

$ uname -a Linux burtha-f36 5.18.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:51:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.4

### Additional information

 3 filters ([AcmeFilter](https://gitlab.cee.redhat.com/jwhiting/acmewebreproducer/-/blob/master/src/main/java/org/jboss/perf/acme/AcmeFilter.java), [PowerFilter](https://gitlab.cee.redhat.com/jwhiting/acmewebreproducer/-/blob/master/src/main/java/org/jboss/perf/acme/PowerFilter.java), [StarFilter](https://gitlab.cee.redhat.com/jwhiting/acmewebreproducer/-/blob/master/src/main/java/org/jboss/perf/acme/StarFilter.java)) are added. The [test](https://gitlab.cee.redhat.com/jwhiting/acmewebreproducer/-/blob/master/src/test/java/org/jboss/perf/acme/GreetingResourceTest.java) case checks for a header added by each filter.

**Comment by geoand** [comment]
As @famod said, the Servlet API is **not** supported in RESTEasy Reactive.
