### ISSUE TITLE
Gotcha: io.quarkus.arc.config.ConfigProperties to io.smallrye.config.ConfigMapping

### ISSUE THREAD

**Issue by Akaame** [quarkusio/quarkus#26243]
### Description

Hello,

When you migrate from `ConfigProperties` to `ConfigMapping` it breaks at the startup if your `prefix` root had properties which were originally not part of the configuration class.

For this application.properties file

```
foo.bar=1
foo.qux=2
```

and this configuration class 
```java
@ConfigProperties(prefix = "foo")
public class FooConfiguration {
    public int bar;
}
```

Moving to `ConfigMapping`

```java
@ConfigMapping(prefix = "foo")
public interface FooConfiguration {
    int bar();
}
```

will result in:

```
io.smallrye.config.ConfigValidationException: Configuration validation failed:
	foo.qux does not map to any root
```

Is this sort of "eager" behaviour to map everything intended?

Cheers.

**Comment by Akaame** [comment]
Sorry. Did not realise there was a "Discussions" board. I think this "issue" fits there more than it does here. Will move it to discussions and close this if you also see it fit.

**Comment by radcortez** [comment]
Yes, this is intended as an extra validation step to make sure you didn't forget to map configuration, or if your configuration is not used anymore and should be removed: https://smallrye.io/smallrye-config/latest/config/mappings/

You can disable this behavior with `smallrye.config.mapping.validate-unknown=false`
