### ISSUE TITLE
ServerExceptionMapper with JsonMappingException exception mapper result is not used as main response but as property value in result

### ISSUE THREAD

**Issue by aurimasniekis** [quarkusio/quarkus#26270]
### Describe the bug

I have an exception mapper using `@ServerExceptionMapper` for exception `JsonMappingException` which generates a `Response` for an issue that happened. The generated response is used as the property value of caused issue property in result.

I am not sure which side is the issue is it Jackson or Quarkus exception mapper.

### Expected behavior

The exception mapper returned response should be the main response of the request.

### Actual behavior

The returned response is used as a property value inside the result object JSON and not Response.

### How to Reproduce?

Reproducer:

Steps to reproducer the behavior:

1. Create an exception mapper using `@ServerExceptionMapper`  for exception `JsonMappingException`
2. Create a `JsonMappingException` causing code that would trigger an exception.
3. Observe response returned.

### Output of `uname -a` or `ver`

Darwin Aurimas.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by geoand** [comment]
I can't say I understand exactly what the issue is, so it would be great if you attached a sample project with a test that shows what is happening now and what you expect to be happening

**Comment by aurimasniekis** [comment]
I tried quickly to reproduce the issue:

https://github.com/aurimasniekis/quarkus-exception-mapper-issue-reproduction

The endpoint is `http://127.0.0.1:8080/hello/1` 

You can see it started to output the `MyEntity` object, encountered an exception, and then wrote the response of the exception mapper not discarding the started output of the `MyEntity` object.

```
➜ demo1 (main) ✔ curl -v http://localhost:8080/hello/1
*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /hello/1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-length: 49
< Content-Type: application/json
<
* Connection #0 to host localhost left intact
{"id":1,"field":"cool","subSet"JacksonErrorMapper
```

**Comment by aurimasniekis** [comment]
@geoand maybe you have looked into it? I have added a test case to test it...

**Comment by geoand** [comment]
Thanks.

I was traveling last week so didn't get a chance. Lots of things have pilled up but I am hoping I'll be able to take a look this week.

**Comment by aurimasniekis** [comment]
It's fine, I am spending some time today to figure out this. So far I managed to make it work correctly by changing to non-reactive ORM and removing `@Transactional` made it work, but the reactive the `main` branch removing `@Transactional` changed nothing. I am thinking maybe it's related to reactive behaviour

**Comment by aurimasniekis** [comment]
Oh, wait no it's not related 😮‍💨 without Transactional it doesn't produce error that's why :D

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26376 fixes the issue

**Comment by aurimasniekis** [comment]
@geoand oh nice, I was just around here trying to understand things (Java is not my main language so it was a bit difficult to navigate) 

Offtopic: I love how on first play around with things I usually managed to get into bugs :D
