### ISSUE TITLE
Shorthand for setting a config property to the same value in dev and test profiles

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#26283]
### Description

It's quite common to want to set multiple configuration properties to the same value in multiple profiles, but not all of them.

For example, a developer not relying on dev services might want to set the following properties for both the `dev` profile and the `test` profile:

```
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.username=testuser
quarkus.datasource.password=testpassword
```

Currently, people have to specify all properties twice:

```
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%dev.quarkus.datasource.username=testuser
%dev.quarkus.datasource.password=testpassword
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%test.quarkus.datasource.username=testuser
%test.quarkus.datasource.password=testpassword
```

Alternatively, they can define a [parent profile](https://quarkus.io/guides/config-reference#parent-profile):

```
%test.quarkus.config.profile.parent=nonprod
%dev.quarkus.config.profile.parent=nonprod
%nonprod.quarkus.hibernate-orm.database.generation=drop-and-create
%nonprod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%nonprod.quarkus.datasource.username=testuser
%nonprod.quarkus.datasource.password=testpassword
```

None of these solutions feel straightforward enough to be used in the documentation of our extensions: the first one is obviously messy, and the second one relies on a relatively advanced configuration feature that would need to be explained.

Can we provide a way to set properties for both the `test` and `dev` profiles in a single line, without duplicates (first snippet above) or using advanced features that need to be explained (second snippet above)?

### Implementation ideas

Some special syntax after `%` could work:

```
%[dev,test].quarkus.hibernate-orm.database.generation=drop-and-create
%[dev,test].quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%[dev,test].quarkus.datasource.username=testuser
%[dev,test].quarkus.datasource.password=testpassword
```

This would be fairly straightforward for users, but may complicate the config implementation unreasonably, given we just want to introduce syntactic sugar. For example it may complicate parsing, in particular when setting config properties through environment variables.

Alternatively, we could just introduce a built-in [parent profile](https://quarkus.io/guides/config-reference#parent-profile) shared by the `test` profile and the `dev` profile:

```
# No need to set %test.quarkus.config.profile.parent / %dev.quarkus.config.profile.parent: that's implicit!
%nonprod.quarkus.hibernate-orm.database.generation=drop-and-create
%nonprod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%nonprod.quarkus.datasource.username=testuser
%nonprod.quarkus.datasource.password=testpassword
```

This probably wouldn't require much changes to the Quarkus code, but the snippet above would be a bit less clear to the uninitiated, unless we find a profile name that makes it extra clear that it's about both tests and dev mode (which will be challenging...).

**Comment by geoand** [comment]
Interesting idea, +1 for the first option

**Comment by yrodiere** [comment]
> But please ensure there's strict validation against users who'd set the same property in multiple profiles or it gets very messy :)

Ok, but what do you want to validate? Setting the same property in multiple profiles is exactly what I'm trying to achieve...

Maybe you mean setting the property multiple times for the same profile? E.g. this:

```
%[dev,test].quarkus.datasource.password=testpassword
%dev.quarkus.datasource.password=anotherpassword
```

That seems dangerously ambiguous indeed... Though I'd expect the last one to win, similarly to this:

```
%dev.quarkus.datasource.password=testpassword
%dev.quarkus.datasource.password=anotherpassword
```

**Comment by radcortez** [comment]
> I wasn't aware of a "last one wins" rule - not sure I like that but if you say it's common knowledge and commonly expected, fine... I'd still prefer a hard failure to warn me, but no strong position.

No specific rule, it is dependent on the implementation of `Properties`. It works that way because the implementation read the file line by line and calls `put` in an `Hashtable`. I would also prefer to have different behavior, but on the other hand, I don't think we should change the way that `Properties` behave, since most developers are already used to it.

**Comment by yrodiere** [comment]
@radcortez So you'd prefer the "parent profile" solution, whose name is yet to be determined (that'll be a hard one)? Or do you have another solution in mind?

**Comment by radcortez** [comment]
How about this?

**profile-aware files**

_application-common.properties_
```
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.username=testuser
quarkus.datasource.password=testpassword
```

_application-dev.properties_
```
quarkus.config.profile.parent=common
```

_application-test.properties_
```
quarkus.config.profile.parent=common
```

**Comment by radcortez** [comment]
BTW, I think that more and more users go with the profile-aware file approach because that is how they used to do it with Spring, and when `application.properties` gets too big, it becomes a mess to manage.

**Comment by yrodiere** [comment]
> Are we saying that it is an issue for the user to have to pick a name to store these common properties?

Not per se. I'm sure it's a negligible overhead for reasonably complex applications.

It's more an issue when I have to show a demo or document another extension: even when trying to simplify things and to show only minimal configuration, I end up having to duplicate keys (which gives a bad impression) or to explain how `parent.profile` works (which sidetracks the conversation). It just makes minimal (demo) configuration unnecessarily complex.

BTW, in demos/documentation I could also set properties without using profiles at all, but then the problem is that the demo/documentation promotes bad practices (setting test properties that could affect prod).

So, yeah. It would be great to be able to gloss over that kind of complexity (which is unrelated to the problem at hand).

> How about this?

Sure, that's roughly equivalent to what I suggested in the issue description (separate files aside). I'd argue that calling the profile "common" is a bit misleading when it's not used in prod, though. I would rather call "common" whatever is directly in `application.properties`, and this `application-common.properties` would be... I don't know, `application-nonprod.properties`?  `application-test-and-dev.properties`? :/

Really, if we could just have a "built-in" parent profile that's common to test and dev, so that we don't need to include `parent.profile` in the configuration, that would eliminate the problem completely. But finding a good, explicit name is going to be challenging... hence the `%[test,dev]` syntax, which at least is relatively explicit.

> BTW, I think that more and more users go with the profile-aware file approach because that is how they used to do it with Spring, and when application.properties gets too big, it becomes a mess to manage.

Definitely a best practice. Spring doesn't face the problem of having separate profiles for `dev` and `test`, though...

**Comment by radcortez** [comment]
Yes, I understand the issue.

If we are to support a `%[test,dev]` syntax, we need to provide a similar ability to the profile-aware files. Maybe we need to add support to read profile-aware files for multiple profiles like `application-[P1]and[P2].properties`. The problem, here again, is what if you actually have a profile named `P1andP2`? :)

Maybe a crazy idea, but what if we fall back to `dev` properties when running `test` if the properties are not available in `test`. In this case, you just define the properties for `dev` and override them in `test`. We do have the mechanism to fall back to other property names, I'm just not sure about the overall implications of this for every configuration.

**Comment by radcortez** [comment]
> So essentially make `dev` the parent profile of `test`, or alternatively enable both the `test` and `dev` profile when running tests? 

Yes, similar. Basically, we would do what we currently do with `prod`, where we record the build time properties in a MIN ordinal source as defaults for fallback. We could do the same for `dev` to `test`.

**Comment by yrodiere** [comment]
> Yes, similar. Basically, we would do what we currently do with `prod`, where we record the build time properties in a MIN ordinal source as defaults for fallback. We could do the same for `dev` to `test`.

I see, I suppose this has some advantages over simply using `dev` as the default "parent profile" for `test`? I'm asking because doing that would at least provide an easy way for people to roll back to the older behavior (useful in supported products, in particular): `%test.quarkus.config.profile.parent=nothing` could override the new behavior. But maybe that's exactly what you want to avoid :)

**Comment by radcortez** [comment]
Well, both would work, I was just trying to go with the safer alternative to avoid possible issues. Right now, we can probably try the parent profile directly and observe the behavior.

**Comment by yrodiere** [comment]
@radcortez I see you self-assigned this ticket... Given the impact of the last solution we discussed, I feel like we may need to discuss the problem more broadly. Is it okay with you if I start a conversation on the mailing list before we try to address this?

**Comment by radcortez** [comment]
Sure. I was not going to do heavy work on this.

I was thinking of just hardcoding a couple of lines of code to set the `dev` profile in the parent one for `test` and run the tests to see what breaks.

**Comment by yrodiere** [comment]
Alright.

> Is it okay with you if I start a conversation on the mailing list before we try to address this?

Done: https://groups.google.com/g/quarkus-dev/c/40iwFnPj3PM/m/pwqgMtnsAwAJ

**Comment by yrodiere** [comment]
Adding a link to the change in Smallrye, if anyone (like me) ends up here and wonders: https://github.com/smallrye/smallrye-config/pull/830/files#diff-98d847827bf51b93c8b47206117535279cc86686e8f7255241118cd10068a797R102-R123

Thanks @radcortez !
