### ISSUE TITLE
Panache projection doesn't work with aggregate JPQL functions

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#26284]
### Describe the bug

Let's take this example using the `Fruit` entity in the [hibernate-reactive-panache-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-reactive-panache-quickstart):

```
package org.acme.hibernate.orm.panache;

import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection
class Result {
	public final Double amount;

	public Result(Double amount) {
		this.amount = amount;
	}
}


Fruit
    .find( "select count(f) from Fruit f" )
    .project( Result.class )
    .singleResult();
```

It will throw the following exception:
```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: select near line 1, column 59 [SELECT new org.acme.hibernate.orm.panache.Result (amount) select count(f) from org.acme.hibernate.orm.panache.Fruit f]
```
It happens because Panache generates the wrong query.

The correct HQL query should be:
```
SELECT new org.acme.hibernate.orm.panache.Result(count(f)) from org.acme.hibernate.orm.panache.Fruit f
```
As a workaround, It works without the `.project( Result.class )`:
```
Fruit
    .find( "select new org.acme.hibernate.orm.panache.Result(count(f)) from Fruit f" )
    .singleResult();
```

Tested with Quarkus 2.9.2
When fixed, we should update [the SO question](https://stackoverflow.com/questions/72706797/quarkus-panache-reactive-select-single-column/72707284).

**Comment by loicmathieu** [comment]
@DavideD Panache `.project()` generates a DTO projection (I think this is documented but it may not be clear). DTO projection cannot work with `count()` that returns a number.

**Comment by DavideD** [comment]
Is this explained somewhere? I'm confused because this seems a typical use case that works everywhere else.

**Comment by loicmathieu** [comment]
Yes, it's clearly documented here: https://quarkus.io/guides/hibernate-orm-panache#query-projection

But the JavaDoc can be improved https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/PanacheQuery.java#L41

For this use case, you need to use the `count()` method not a `find().project()`.

What we could do also, is to throw an error when someone use `project()` on a method that already have a `SELECT` clause as it will always generates a wrong query.

**Comment by DavideD** [comment]
I think there's something I'm missing. Because this description for me doesn't mean that one cannot use aggregated functions:

> Query projection can be done with the project(Class) method on the PanacheQuery object that is returned by the find() methods.
> 
> You can use it to restrict which fields will be returned by the database.

I guess when it says  fields it doesn't mean the columns returned by the query.

> it's clearly documented 

I wouldn't use the word  "clearly" in this context.

> What we could do also, is to throw an error when someone use project() on a method that already have a SELECT clause as it will always generates a wrong query.

That would be better than the error we have now. At least, it would make it clear that that's a design decision.
And it seems something worth mentioning in the javadocs and guides.

Still, by changing the query it's possible to make it work, so I'm not sure why we want to have these limitations.

Also, are you sure that's true? the documentation states that `You can also write your queries in plain HQL`. Wouldn't this be valid? `.find("select p.name, p.surname from Person p").project(PersonDTO.class)`?

**Comment by loicmathieu** [comment]
Projection in database means the selection of fields. So aggregation is not part of it. Our current implementation is to use DTO projection, it's documented in the guide. 
DTO projection means we will write the SELECT clause ourself so even if `.find("select p.name, p.surname from Person p").project(PersonDTO.class)` seems legit it isn't. 

In this case a simple `.find("from Person p").project(PersonDTO.class)` will works or even `findAll().project(PersonDTO.class)`.

We can improve the documentation and the JavaDoc, and generate a more helpful exception.

> Still, by changing the query it's possible to make it work, so I'm not sure why we want to have these limitations.

The limitations are mandated by the usage of DTO projection, DTO projection have some advantages over other technics and it plays nicely whith what we already have in Panache which often allow to not write the SELECT clause.

What we already discuss with @FroMage is the fact that we add a bound to the entity type in a PanacheQuery that prevent us to map to a different type (like a long or a PersonDTO class without the usage of the supported projection). This can be discussed again but keep in mind that Panache purpose is not to support all use case but only the more used ones. We are open to suggestion of course for improvements ;)

**Comment by DavideD** [comment]
I think the problem is that `.project` is accessible from `.find` and `.find` is too flexible to be use with it.
Why don't we have something like (this is just a quick example):
```
Person.project(PersonDTO.class).from("Person p").where("...")
```
This way there wouldn't be any confusion.

But what I'd really want is something that allows me to map the result to a class or interface easily. Frankly, I don't think nobody care if it's a projection or not.

**Comment by loicmathieu** [comment]
> Actually, why can't we just assume that, when the query starts with a select, it doesn't need any change and it will return the value we need?

Yes, we can do this, it will be coherent with what we already have: if a query start with SELECT we keep it, if not we build the SELECT clause (and the WHERE clause in case of shorthand query).

Regarding your proposal : 
```
Person.asProjection(PersonDTO.class).from("Person p").where("...")
Person.asProjection(PersonDTO.class, "p").from("Address a join a.person p").where("...")
```
It's a more broad change and not the direction we took years ago when we built Panache ...

**Comment by DavideD** [comment]
> Yes, we can do this, it will be coherent with what we already have: if a query start with SELECT we keep it, if not we build the SELECT clause (and the WHERE clause in case of shorthand query).

What I mean is, that the result will be something that we can pass to the constructor of the class specified in `.projection`.

**Comment by loicmathieu** [comment]
@DavideD I'm not an Hibernate expert but when I try to change the bound of the query without using a DTO projection it fails with the following exception : 

```
2022-06-30 10:28:11,327 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /test/projection failed, error id: 4e741ad5-fefb-4b61-809a-3d16860c65e7-1: org.jboss.resteasy.spi.UnhandledException: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class io.quarkus.it.panache.CatProjectionBean ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; io.quarkus.it.panache.CatProjectionBean is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4a5dc126)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
```

My test query is : 

```
Cat.find("select c.name, c.owner.name as ownerName from Cat c")
                .project(CatProjectionBean.class).firstResult();
```

Where `CatProjectionBean` is a java bean.

You can find my prototype here: https://github.com/quarkusio/quarkus/compare/main...loicmathieu:quarkus:panache-projection-improvement

**Comment by loicmathieu** [comment]
Looking at how we build the JPA Query, it cannot work as we didn't pass the result class so only entity class or DTO projection can work.

```
jpaQuery = em.createQuery(orderBy != null ? query + orderBy : query);
```

**Comment by DavideD** [comment]
Hibernate ORM is not going to transform the result on its own.

One has to specify the transformation:

1. In the query: `select new CatProjectionBean( "c.name, c.owner.name as ownerName") from Cat c`
2. Or, [using a ResultTransformer](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#sql-dto-query): 
    ```
    List<CatProjectionBean> dtos = session
         .createQuery(select c.name, c.owner.name as ownerName from Cat c")
         .setResultTransformer( Transformers.aliasToBean( CatProjectionBean.class ) )
         .list();
    ```

With Hibernate Reactive only the first option is available.

> Looking at how we build the JPA Query, it cannot work as we didn't pass the result class so only entity class or DTO projection can work.

I don't have enough familiarity with the code of Panache, but this is something to apply just before running the query.
I would expect that by the time we run the query we can gather everything we need.

**Comment by DavideD** [comment]
I haven't tested it, but something like this wouldn't work?
```
        if ( query.startsWith( "SELECT new " )) {
        	throw new RuntimeException("Cannot use .project with 'select new' query");
        }
        if ( query.startsWith( "SELECT " ) || query.startsWith("select ")) {
        	int endSelect = query.indexOf( " from " );
        	StringBuilder select = new StringBuilder("SELECT new " )
        			.append(type.getName())
        			.append(" (")
                                // Add the select clause
        			.append( query.substring( "SELECT ".length(), endSelect ) )
        			.append( ")" )
                                // Add the from clause
        			.append( query.substring(endSelect) );

        	return new CommonPanacheQueryImpl<>(this, select.toString() + query, "select count(*) " + query.substring( endSelect ));
        }
```

It's not perfect, but I think it would work for most common scenarios

**Comment by DavideD** [comment]
I've applied my changes here: https://github.com/DavideD/quarkus/pull/50/commits/89d6b54c46519ff7b4567ace6c4b2414cc08dbfd

But I cannot run the tests so  I don't know if it works or not.
