### ISSUE TITLE
CORS response headers not present with quarkus.http.non-application-root-path

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#26296]
### Describe the bug

When using `quarkus.http.root-path` and `quarkus.http.non-application-root-path` to customize the location of REST endpoints (not `/`), but keeping the non-application endpoints (`/openapi`, etc.) available at `/q`, the CORS filter is not executed for the non-application endpoint calls.

Example config:
```
quarkus.http.cors=true
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=/q
```

Making an HTTP request to `/api/hello` will return CORS response headers;  a request to `/q/openapi` will not.

If the non-application root path is changed to not have a leading `/`, then the CORS headers are available, but the `q` path is now available at `/api/q`.

### Expected behavior

CORS headers should be available (when CORS enabled and Origin header present in requests) for non-application endpoints if the root path has been customized.

### Actual behavior

No CORS headers are present.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8958794/code-with-quarkus.zip)

1. Run in dev mode (./mvnw clean compile quarkus:dev)
2. `curl --head -H "Origin: https://www.google.com" localhost:8080/api/hello`
3. Note the response has the `access-control-allow-origin` and `access-control-allow-credentials` headers
4. `curl --head -H "Origin: https://www.google.com" localhost:8080/q/openapi`
5. Note the response does not have and CORS related headers returned
6. Change `quarkus.http.non-application-root-path` to `q`
7. Repeat step 2, note same results as step 3
8. `curl --head -H "Origin: https://www.google.com" localhost:8080/api/q/openapi`
9. Note the CORS headers are present in the response

### Output of `uname -a` or `ver`

Linux laverne 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/nde/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-44-generic", arch: "amd64", family: "unix"

### Additional information

This problem exists since at least 2.7.5.Final.

**Comment by sberyozkin** [comment]
@nderwin Thanks, would like to have a look and tweak CORS filter a bit ?

**Comment by nderwin** [comment]
> @nderwin Thanks, would like to have a look and tweak CORS filter a bit ?

I don't think it's a problem with `CORSFilter` itself;  it's just not getting called at all for the non-application endpoints, but I'm not sure where in the code it's added to the call chain or needs to be added.

**Comment by sberyozkin** [comment]
Non application path is handled in https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java I believe, also CC-ing to Erin, @ebullient

**Comment by nderwin** [comment]
Any updates on this?  It's kind of a show-stopper for me for using this in a customer's project;  I'd be happy to contribute some code, but I haven't had much luck in understanding how to write a test to simulate this situation so I could try changing the code to fix it.

**Comment by michalvavrik** [comment]
I'll have a look.
