### ISSUE TITLE
Failed to build quarkus application:

### ISSUE THREAD

**Issue by Hashdhi** [quarkusio/quarkus#26297]
### Describe the bug

Failed to build quarkus after windows security update in my org . it was working before . i think treats transformed-bytecode.jar has a virus . 
how  do we disable it ? is there any settings ?

quarkus-maven-plugin:2.10.0.Final

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.10.0.Final:build (default) on project document-management-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.io.IOException: Failed to create a new filesystem for \target\quarkus-app\quarkus\transformed-bytecode.jar
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:953)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.io.IOException: Failed to create a new filesystem for \target\quarkus-app\quarkus\transformed-bytecode.jar
[ERROR]         at io.quarkus.fs.util.ZipUtils.newZip(ZipUtils.java:133)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:611)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:218)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
[ERROR]         ... 6 more
[ERROR] Caused by: java.nio.file.FileSystemException: \target\quarkus-app\quarkus\transformed-bytecode.jar: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
[ERROR]
[ERROR]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:343)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:367)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:108)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
[ERROR]         at io.quarkus.fs.util.ZipUtils.newZip(ZipUtils.java:130)
[ERROR]         ... 13 more

### Output of `java -version`

1.8

### Quarkus version or git rev

quarkus-maven-plugin:2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
This is already being discussed on the mailing list, so let's not have multiple threads open...

**Comment by yuvrajjsingh0** [comment]
Hi, is there any update on this?
