### ISSUE TITLE
Command Mode Applications don't work with Kotlin 1.7

### ISSUE THREAD

**Issue by mhenze-exaring** [quarkusio/quarkus#26290]
### Describe the bug

If you create a Command Mode Application for kotlin and change the kotlin version to 1.7 the application fails to work .

### Expected behavior

- When using `@QuarkusMain` the application should execute the `run()` method of the QuarkusApplication
- When using `quarkus.package.main-class` the application should execute the `run()` method of the QuarkusApplication
- When using `@Command` the application should execute the `run()` method of the Runnable 

### Actual behavior

- When using `@QuarkusMain` the application _**silently does not execute**_ the `run()` method of the QuarkusApplication
- When using `quarkus.package.main-class` the application fails to start with:
  ```
  ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#mainClassBuildStep threw an exception: java.lang.IllegalArgumentException: The supplied 'main-class' value of 'de.exaring.commandmode.MyMain' does not correspond to either a fully qualified class name or a matching 'name' field of one of the '@QuarkusMain' annotations
  ```
- When using `@Command` the application fails to start with:
  ```
  Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.DevModeContext$ModuleInfo.getMain()" because the return value of "io.quarkus.deployment.dev.DevModeContext.getApplicationRoot()" is null
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:137)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
  Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.DevModeContext$ModuleInfo.getMain()" because the return value of "io.quarkus.deployment.dev.DevModeContext.getApplicationRoot()" is null
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:90)
  ```

### How to Reproduce?

Steps to reproduce:
- run `quarkus create cli org.acme:kotlin-cli-test --extension=kotlin --gradle`
- edit the generated `build.gradle` and set kotlin-plugin versions to `1.7.0`
- run `quarkus dev`

### Output of `uname -a` or `ver`

Linux pop-os 5.17.5-76051705-generic

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

It works, if you downgrade kotlin to `1.6.21` in the `build.gradle` again

**Comment by famod** [comment]
The exact same thing seems to happen in CI: #26278

To be fair, Kotlin is still on 1.6.21 in the Quarkus BOM, so 1.7 is not officially supported yet.

/cc @glefloch

**Comment by u6f6o** [comment]
@famod : are you aware of any possibility to enforce the versions suggested by the bom for gradle plugins? If I omit the version string for the plugins, it does not work.

**Comment by jsjant** [comment]
This is because how GradleApplicationModelBuilder in Quarkus [looks](https://github.com/quarkusio/quarkus/blob/d65ab1d32728fc554f713a11f7c68d4c76163984/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/GradleApplicationModelBuilder.java#L440) for source code. There is the following code

`project.getTasks().withType(AbstractCompile.class, t -> {`

However, KotlinCompile task does not extend AbstractCompile anymore. Here is code from [1.6](https://github.com/JetBrains/kotlin/blob/1.6.20/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt#L78) and [1.7](https://github.com/JetBrains/kotlin/blob/1.7.0/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt#L77)

Because of this model is empty when you are trying to switch to Kotlin 1.7 But even if you do some hacks and run the application, runtime will be Kotlin 1.6.21, as it's bundled with Quarkus plugin runtime.

**Comment by famod** [comment]
@jsjant that's very valuable info, thanks!

**Comment by evanchooly** [comment]
That might explain why the 1.7.0 PR had such problems...

**Comment by evanchooly** [comment]
@famod I was going to take another stab at the 1.7.0 upgrade but I see you have another PR under way.  You might take a look at this issue as I think they're related and we won't be able to fix one without the other.

**Comment by jsjant** [comment]
> @famod I was going to take another stab at the 1.7.0 upgrade but I see you have another PR under way. You might take a look at this issue as I think they're related and we won't be able to fix one without the other.

Can you please provide a link to that PR?

**Comment by famod** [comment]
@evanchooly do you mean #26278?
I stopped working on it due to lack of time. You are more than welcome to take it from there (see most recent PR comment).

**Comment by evanchooly** [comment]
ah.  yes, i do.  i'll pull it down and see if I can't get it unstuck then.  was thinking about it all weekend. :)
