### ISSUE TITLE
@Provider unable to handle Exceptions / default Quarkus error response is used instead

### ISSUE THREAD

**Issue by spirostz** [quarkusio/quarkus#26314]
### Describe the bug

Since we are handling all Exceptions with the  `ExceptionMapper<Throwable>` we should never get the default Quarkus error response. 
There is at least one case that an Exception is not handled by our Custom ExceptionMapper.

### Expected behavior

Error response when we call http://localhost:8080/hello should always be:

 "This is custom handler!"

### Actual behavior

Error response when Keycloak server is offline and we call http://localhost:8080/hello with Authorization header in place

```
{
    "details": "Error id b849414c-7207-4533-9cfd-4206733da866-1, io.quarkus.oidc.OIDCException: OIDC server is not available at the 'http://localhost:8001/realms/testing' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'",
    "stack": "io.quarkus.oidc.OIDCException: OIDC server is not available at the 'http://localhost:8001/realms/testing' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'\r\n\tat io.quarkus.oidc.runtime.OidcRecorder.toOidcException(OidcRecorder.java:236)\r\n\tat io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:305)\r\n\tat io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:299)\r\n\tat io.smallrye.context.impl.wrappers.Slo
```

![image](https://user-images.githubusercontent.com/11974067/175280101-a8f532a9-8206-420a-90cd-0c67eba2c988.png)

### How to Reproduce?

1. Generate a new Quarkus project:
![image](https://user-images.githubusercontent.com/11974067/175280599-b67faf32-68d0-429f-bd55-f61269720aef.png)

2. Change GreetingResource.java to:
``` java
package org.acme;

import io.quarkus.arc.Priority;

import javax.annotation.security.RolesAllowed;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @RolesAllowed("user")
    public String hello() {
        throw new IllegalStateException("Forcing error that handle successfully");
        //return "Hello from RESTEasy Reactive";
    }

    @Provider
    @Priority(Integer.MIN_VALUE)
    public static class AllMissingExceptionsHandler implements ExceptionMapper<Throwable> {

        @Override
        public Response toResponse(Throwable throwable) {
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity("This is custom handler!").build();
        }
    }

}
```

3. Change application.properties to:
```
quarkus.oidc.client-id=testing-service
quarkus.oidc.auth-server-url=http://localhost:8001/realms/testing
quarkus.keycloak.devservices.enabled=false
```
4. Call http://localhost:8080/hello with postman by providing a new header 
`Authorization:Bearer Just_a_Random_Text` (image)

![image](https://user-images.githubusercontent.com/11974067/175281447-e5c727c2-7c8f-4a9b-bf92-05dda692029a.png)

5. Response is not the expected one (expected:  "This is custom handler!")

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22000 spirospc 3.3.3-341.x86_64 2022-01-17 11:45 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: C:\tools\apache-maven-3.8.5-bin\apache-maven-3.8.5 Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\tools\openjdk-17.0.2\jdk-17.0.2 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Although I understand the rationale of this, however JAX-RS `ExceptionMapper` classes are not invoked for exceptions that happen outside of JAX-RS, like in this case.

So I am going to close this as `wont fix`.

However I would like to ask @sberyozkin if there is a way for users to handle such Oidc exceptions.

**Comment by sberyozkin** [comment]
@spirostz Is the issue here is that you don't want this kind of message returned to the client ? (too much internal info ?)

**Comment by sberyozkin** [comment]
@spirostz The only option which might work is disabling the proactive authentication as it pushes the security chain to run alongside JAX-RS chain so the exception mapper might work. #25732 is related, one specific exception can not be caught, but you may have better luck with other ones, can you try please to disable the proactive auth, `http. auth. proactive=false` and retry ?

**Comment by sberyozkin** [comment]
A better option is to log it only but simply return 500

**Comment by sberyozkin** [comment]
I think the better option may be just return 500

**Comment by spirostz** [comment]
> @spirostz Is the issue here is that you don't want this kind of message returned to the client ? (too much internal info ?)

Exactly, from security perspective, we should never expose anything unhandled to the user.

**Comment by spirostz** [comment]
> 

I tried with the `http.auth.proactive=false` but didn't worked

**Comment by spirostz** [comment]
Hi @sberyozkin. I agree with you. By returning another (custom?) 500 message and log the error it's a nice alternative.
Similar, in a previous message you suggest "_A better option may be to log it only but simply return 500_". This is also good solution as well, but how to implement it? '@Provider' approach is not working there? (Maybe I misunderstood something? )

**Comment by sberyozkin** [comment]
Hi @spirostz, I meant I could update `OidcRecorder` code to get  `OIDC Server is not available`  reported only (without the details such as connection url for ex), as it has to be a consistently neutral message, without depending on users trying to intercept it with JAX-RS mappers, and which won't work anyway in the default proactive authentication case.

Let me open a PR and CC you

**Comment by sberyozkin** [comment]
@spirostz FYI, #26528

**Comment by sberyozkin** [comment]
@spirostz I'll keep this issue open for a while, as I'll need to check why some exceptions are not caught by JAX-RS mappers, so once I'll get to it, I'll check this one and #25732, it will take some time to prioritize but we'll check
