### ISSUE TITLE
Start and keep @QuarkusIntegrationTest running, without executing tests, for faster test development cicle

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#26315]
###
There should be an easy way to start and keep the `@QuarkusIntegrationTest` environment running for a rapid test development and verification cicle.

### The current way
Wenn working with `@QuarkusIntegrationTest`, the current procedure for developing new tests looks like this:

1. Write a test for my api
2. Start `@QuarkusIntegrationTest` with everything that comes with it (Dev services, TestResources, container under test, etc) and wait to verify the just-written test (wait 5 minutes)
3. Watch the whole test setup gets torn down again.
4. Refactor test or write next one, anyway repeat from step 1.

Each cicle (without the writing of the test!), depending on the project, takes 5 minutes. This is very discouraging and will lead to sloppy tests, if at all, and is simply a waste of time.

To kinda achiev this with the tools today I could:

1. Try to replicate the whole setup in a separate docker compose, which is prone to errors, as it is not the same environment as in a regular `@QuarkusIntegrationTest` run and needs to be in sync with the test setup all the time.
2. Set a debug breakpoint and start my test in a different process.

Both seems not to be a good way.

### The way it could be

1. Start `@QuarkusIntegrationTest` in e.g. _dev-mode_ (maybe diectly as property of the annotation), which will cause the whole test environment to start up and keep running. 
3. Then I can develop my test and execute them independently as unit test in my ide for verification against my running environment.

This way I can write and verify, without having to reup the whole environment every time. Obviously, executing a test can change the state of the deployed artefacts, but this is acceptable fact. As each test class can be annotated with different `@QuarkusTestResource`,  there might be an option, or maybe even a must, to do this within a scope of a single test class.

**Comment by geoand** [comment]
`QuarkusIntegrationTest` can't run in dev-mode - this is by design.

However we can definitely explore ways to make it more friendly.

**Comment by HerrDerb** [comment]
I think we can close this issue. A good setup with `@QuarkusTest` does already help a lot. Further more, the runnable artefact can be reused to. maybe this option could have more coverage in the documentation.
