### ISSUE TITLE
Run test cases in IntelliJ IDEA error and can't run the test cases

### ISSUE THREAD

**Issue by guanchao-yang** [quarkusio/quarkus#2632]
When I clone this project and run the test cases in IntelliJ IDEA, the follow error occurs :

![image](https://user-images.githubusercontent.com/32863418/58541563-5e143580-822e-11e9-957d-da019261eb59.png)

And my IntelliJ IDEA will be stop and responseless ,so I have no method except restart my  IntelliJ IDEA

**Comment by guanchao-yang** [comment]
@jmesnil Thanks very much

**Comment by stuartwdouglas** [comment]
Downloading the dependencies will take some time. You can't run the test until Intellij has downloaded all the dependencies.
