### ISSUE TITLE
Proactive Authentication creates excessive SecurityIdentityAugmentor calls

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#26324]
### Describe the bug

As per https://quarkus.io/guides/security-built-in-authentication#proactive-authentication, proactive auth is enabled by default. (yes you can disable it, but it is enabled by default, why?)

When implementing security a common implementation detail is to add a SecurityIdentityAugmentor to enrich the identity (such as DB lookup of the user).

When Proactive Authentication is enabled this creates a lot of calls to SecurityIdentityAugmentor.

Opening something like DevUi or Swagger UI creates 8-10+ invocations of SecurityIdentityAugmentor.

### Expected behavior

This feels excessive.  Is there a way to detect if the specific endpoint being called requires authentication?  It would seem there ~should be a way to mitigate the calls to blocking resources instead of enriching the securityIdentity on every resource against the app. (as per proactive auth implementation)

This could also be mitigated with some sort of local caching? Is there a ability to cache the Augmentor based on the same identity?

### Quarkus version or git rev

latest

**Comment by sberyozkin** [comment]
Hmm. I don't think it is the case for a prod profile call, right ?
@StephenOTT It looks like, in Dev UI, multiple calls are made per various components/cards loaded in Dev UI, so if you have a very wide, `/*` kind of protection then every call will require an authentication.
Or, similarly, if the credentials are posted to the public resource, then the same will happen with the proactive authentication enabled.
I do not think there is anything that needs to be enhanced here, the extra complexity with some caching/etc to avoid the excessive calls in the dev ui mode, will far outweigh the cost of just disabling the proactive authentication.

**Comment by sberyozkin** [comment]
Closing as not a bug, `SecurityIdentityAugmentor` will be called once per every incoming request, so if a given client system sends N requests in parallel, `SecurityIdentityAugmentor` will be called N times, once per each client request. if the resource is public then it can be avoided easily by either disabling the proactive authentication if the client system is sending the credentials or making the target endpoints public, for example, 
```
quarkus.http.auth.permission.public.paths=/q/*
quarkus.http.auth.permission.public.policy=permit
```
etc

or require the authentication only in the prod profile.

Additionally, `SecurityIdentityAugmentor` can cache the info extracted from the DB as well if needed
