### ISSUE TITLE
Allow access log to also access the exchange data

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#26338]
### Description

The (Vert.x) routing context has a generic data store. Allow to log entries from that store in access log.

In our project we have a need to e.g. also log the tenantId of a logged in user in addition to the login-name.
We put that tenant id into the routing context 

`routingContext.put(X_RH_ACCOUNT, rhIdentity.identity.accountNumber);`

Now it would be neat to easily log that value
E.g.

`2022-06-24 09:05:48,960 INFO  [access_log] (executor-thread-2) "127.0.0.1 - joe-doe-user 24/Jun/2022:09:05:48 +0200 "GET / HTTP/1.1" 403 - accountId= 1234" `

### Implementation ideas

Follow the example of other AccessLog attribute handlers in vertx-http

**Comment by pilhuhn** [comment]
@gsmet Shall I just close this one?

**Comment by gsmet** [comment]
I adjusted the description of the PR using `Fixes` so that the issue is linked to the PR properly.
