### ISSUE TITLE
cannot setup on win10/MinGW with JAVA_HOME contains space

### ISSUE THREAD

**Issue by jukzi** [quarkusio/quarkus#26345]
### Describe the bug

I tried to follow the "Get Started" https://quarkus.io/get-started/ guide on windows.
Results in Error on the very first step: `.jbang/bin/jbang: line 229: C:\Program: No such file or directory`
my JAVA_HOME is "C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\"  - which contains 2 spaces (pretty normal on windows)

### Expected behavior

no error, proper escape space

### Actual behavior

Error: `.jbang/bin/jbang: line 229: C:\Program: No such file or directory`

### How to Reproduce?

curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044 msno-it11113 3.3.4-341.x86_64 2022-05-09 11:56 UTC x86_64 Msys

### Output of `java -version`

java version "18.0.1.1" 2022-04-22 Java(TM) SE Runtime Environment (build 18.0.1.1+2-6) Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

**Comment by maxandersen** [comment]
Can you run "jbang --version" and show output ?

This issue was fixed in older jbang so just checking if regression or old jbang.

**Comment by jukzi** [comment]
```
$ curl -Ls https://sh.jbang.dev | bash -s - --version
/c/Users/jkubitz/.jbang/bin/jbang: line 229: C:\Program: No such file or directory

```

**Comment by jukzi** [comment]
i deleted .jbang and tried again to get the newest version:
```
$ curl -Ls https://sh.jbang.dev | bash -s - --version
Downloading JBang...
Installing JBang...
/c/Users/jkubitz/.jbang/bin/jbang: line 229: C:\Program: No such file or directory
```

**Comment by maxandersen** [comment]
Okey. That is weird. 

@quintesse a regression ?

**Comment by quintesse** [comment]
@maxandersen no, I just think it's just another case of needing to cover all the os/shell permutations that exist. We had problems with Cygwin which were fixed, but this is MINGW.

@jukzi Could you perhaps test something for me? Can you edit the `/c/Users/jkubitz/.jbang/bin/jbang` file and put quotes around any `${JAVA_EXEC}` you see? There should be 2, one on line 218 and one on 229. Just change `${JAVA_EXEC}` to `"${JAVA_EXEC}"`. Let us know if that fixes things.

**Comment by jukzi** [comment]
> @jukzi Could you perhaps test something for me? Can you edit the `/c/Users/jkubitz/.jbang/bin/jbang` file and put quotes around any `${JAVA_EXEC}` you see? There should be 2, one on line 218 and one on 229. Just change `${JAVA_EXEC}` to `"${JAVA_EXEC}"`. Let us know if that fixes things.

That works. Thanks!

**Comment by quintesse** [comment]
This has now been fixed in "main" and will be part of the next Jbang release. Thanks for your help @jukzi !

**Comment by geoand** [comment]
Thanks for getting to the bottom of this everyone.

Closing this as an upstream issue.
