### ISSUE TITLE
Integrate GraphQL Typesafe Client into QuarkusTest

### ISSUE THREAD

**Issue by t1** [quarkusio/quarkus#26365]
### Description

I'd like to directly inject a GraphQL Client into a test, i.e.:

```java
@QuarkusTest
class UserTest {

    @GraphQLClientApi interface Api {
        @Query User user(int id);
    }

    public static class User {
        String name;
    }

    @Inject Api api;

    @Test void shouldGetJane() {
        var jane = api.user(1);

        then(jane.name).isEqualTo("Jane");
    }
}
```

But then I get a `RuntimeException`: "URL not configured for client."

The workaround I have to use is:

```java
    @TestHTTPResource("graphql")
    URI uri;

    Api api() {return TypesafeGraphQLClientBuilder.newBuilder().endpoint(uri).build(Api.class);}

    @Test void shouldGetJane() {
        var jane = api().user(1);

        then(jane.name).isEqualTo("Jane");
    }
}
```

**Comment by jmartisk** [comment]
And do you have the URL configured somewhere? To have the client point at the testing Quarkus instance, your application.properties will need something like

```
%test.quarkus.smallrye-graphql-client.CLIENT_CONFIG_KEY.url=http://localhost:${quarkus.http.test-port:8081}/graphql
```

**Comment by t1** [comment]
That would be another workaround, but as it works out-of-the-box with the MP REST Client, it would be nice to have this for GraphQL as well.

**Comment by t1** [comment]
and I suppose the change could be rather miniscule.
