### ISSUE TITLE
Zookeeper client extension

### ISSUE THREAD

**Issue by morphy76** [quarkusio/quarkus#26368]
### Description

Hello

I would like to propose the subject extension to provide a seamless integration with the latest version of Apache Zookeeper.

The purpose of this extension is to provide an injectable, application scoped, zookeeper client so that providing:
- Client interactions for znodes operations
- CDI events triggered by zookeeper watchers

Once the basic capabilities are achieved, the idea is to enhance the extension with some common recipes:
- Locks
- Groups & leader election
- etc etc etc

Let me say, a Quarkus version of Apache Curator (anyway the idea is not to bring Curator in the extension and just leverage the Apache Zookeeper client).

edit: and if it is needed I agree to lead the project but I don't really have so much practice about contributing to OSS

Best regards
Riccardo

### Configuration suggestion

Draft idea, strictly inspired by the zookeeper client connection parameters.
So far, no named connections are expected but in a multitenant context it should be taken into consideration.

```
quarkus.zookeeper.health.enabled
quarkus.zookeeper.session.connectionString
quarkus.zookeeper.session.timeout
quarkus.zookeeper.session.canBeReadOnly
quarkus.zookeeper.client.disableAutowatchReset
quarkus.zookeeper.client.secure
quarkus.zookeeper.client.clientCnxnSocket
quarkus.zookeeper.client.jute.maxbuffer
quarkus.zookeeper.client.ssl.keyStore.location
quarkus.zookeeper.client.ssl.keyStore.password
quarkus.zookeeper.client.ssl.keyStore.type
quarkus.zookeeper.client.ssl.trustStore.location
quarkus.zookeeper.client.ssl.trustStore.password
quarkus.zookeeper.client.ssl.trustStore.type
quarkus.zookeeper.client.auth.sasl.enabled
quarkus.zookeeper.client.auth.clientconfig
quarkus.zookeeper.client.auth.serverPrincipal
quarkus.zookeeper.client.auth.clientUsername
quarkus.zookeeper.client.auth.clientCanonicalizeHostname
quarkus.zookeeper.client.auth.serverRealm
```

### Additional context

Zookeeper could be useful to coordinate multiple instances of the same microservice:  a pure stateless design is not always achievable finding in zookeeper a resource to store small shared runtime data without the need to deploy an RDBM or whatever, a resource to identify a leader within a replicaset and so on.

**Comment by morphy76** [comment]
> Hi,
Hi Georgios

> Two things come to mind:
>     * Does Camel Quarkus already have something like this?
I'm going to check as soon as possible but it could be somehow of interest the evolution of "recipes" for high level patterns which I don't believe are a Camel concern.

>     * Any such work would be best placed in the [Quarkiverse](https://quarkus.io/blog/quarkiverse/).
That's welcomed :)

Rick

**Comment by iocanel** [comment]
There is a `camel-quarkus-zookeeper` component. However, I think that there is value in having a `quarkus-zookeepr` in the Quarkiverse and possibly a `quarkus-curator`. Not sure if they need to be one extension or two.

**Comment by morphy76** [comment]
Hello

it's not clear to me how to move on.

I have a baseline implementation but before moving on with "Quarkus Ecosystem-CI", "Announce on quarkus-dev mailing list with the repo location", ... namely the documented steps... my understanding is that I need the repo resources provided by the quarkiverse itself... is it? am I missing something or it is just "required wait time"?

Thank you in advance
Riccardo

**Comment by gastaldi** [comment]
Hey @morphy76,

Yeah, we need to provision the repository in the Quarkiverse org, it should be done by Monday. I'll let you know when it's ready :+1

**Comment by morphy76** [comment]
@gastaldi thanks a lot!

**Comment by gastaldi** [comment]
@morphy76 The repository is now available in https://github.com/quarkiverse/quarkus-zookeeper-client
