### ISSUE TITLE
Authentication token inspected at the end of the request / after body completes

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#26378]
### Describe the bug

In case of a large PUT request, quarkus waits until the whole body is available prior checking the access token's validity.

This has two implications:
- In case the download is taking longer then the access token might expire before the upload finished (this can be fixed by using the Expect header)
- Unauthorized clients might put a strain on the machine by sending large spam requests

### Expected behavior

Authorization header should be interpreted as soon as the headers section finished.

### Actual behavior

Authorization header consulted only after the full request is there.

### How to Reproduce?

1. Create a quarkus application with a REST interface
2. Use a short living access token. (I've 2 minutes at my example)
3. Try to upload a large file large enough to take more than 2 minutes (without "Expect:100-continue")

### Quarkus version or git rev

2.9.2.Final

**Comment by sberyozkin** [comment]
@stuartwdouglas @cescoffier Is it technically possible to start a security chain as soon the Vert.x router consumes the headers but before it attempts to read the body.

@smil2k Can you please clarify more info about your set up ?
Does it really apply to the case where a proactive authentication is disabled (i.e, when JAX-RS chain starts and deserializes the parameters) ?
Do you use quarkus-oidc or smallrye-jwt ?

**Comment by smil2k** [comment]
@sberyozkin I'm using oidc. 

Can you elaborate your 2nd question? We are using Bearer auth, the client is handling the refresh of the token.

This issue is masked somewhat, because normally we keep replace tokens T-1 minutes. 
Generally we need to make sure that we refresh the access token at least so much earlier than we expect a request will be processed at maximum. This bites with larger POST and PUT. 

Another unfortunate fact that browsers are not supporting setting "Expect: 100-continue" programatically on XHR.

**Comment by cescoffier** [comment]
@sberyozkin in pure Vert.x yes, but in Quarkus that would mean removing the body handler and handling the body conditionally.

**Comment by sberyozkin** [comment]
@smil2k 

For example, lets say you have a JAX-RS Resource such as 
```
@Path("/service")
@Authenticated
public class MyService {

    @PUT
    @Consumes("application/json")
    public Response put(BigPayload payload) {}
}
```

By default, Quarkus Security starts early, before the JAX-RS chain starts, and will authenticate the data, it is a proactive authentication mode. It will do it before `InputStream` is consumed and deserialized into `BigPayload`.

I'd really be surprised if in this case Vertx was caching the payload, I don;t know the lower lever details of the way Vert.x HTTP works but it would be unexpected to me.

But then we can disable the proactive authentication, https://quarkus.io/guides/security-built-in-authentication#proactive-authentication. In this case the authentication will only be initiated if the runtime sees that for example, `MyService#put` requires an authenticated access. Here I can imagine that a `BigPayload` MBR converting `InputStream` to the `BigPayload` bean has already run. Can it be the case in your case ?

**Comment by smil2k** [comment]
@sberyozkin I've checked, we use the default proactive method.

**Comment by sberyozkin** [comment]
@smil2k Thanks.

Hey @cescoffier, @stuartwdouglas, so Vert.x body handler consumes the body before the target method is even determined ? Given that @smil2k says that the security check, which in case of the proactive authentication, will run before the JAX-RS chain, starts after the body is consumed. Can you clarify please  ?

**Comment by sberyozkin** [comment]
@smil2k Is it Resteasy Classic or Reactive ? Do you use Undertow ?

**Comment by smil2k** [comment]
quarkus-resteasy-reactive-jackson
quarkus-keycloak-authorization

**Comment by smil2k** [comment]
I did not purposefully enabled something like this. Did not want to use KC authz policies at all.

I've checked we did not defined any properties in relation the KC policy enforcement. All we wanted was role based authz a'la @RolesAllowed

**Comment by smil2k** [comment]
Sure

**Comment by smil2k** [comment]
Removed, but the issue remained.

**Comment by smil2k** [comment]
@sberyozkin  I had a suspect already, because I was using a reactjs proxy, but turning it off did not help. 

I'll try to run it on my own machine now to be sure that no reverse proxy is involved in between. HAProxy is known to buffer requests, but I don't think that 500mb is what HAProxy would wait together.

**Comment by smil2k** [comment]
You were right: the reverse proxy before quarkus did the buffering. Nginx buffers the requests entirely in order to be able to send it elsewhere in case of a loss of communication and/or protecting against slow byte sending attacks.

```
$ curl -X PUT ... yadda ...
....
> Connection: keep-alive
> Content-Length: 1599998240
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer
< content-length: 0
* HTTP error before end of send, stop sending
< 
* Closing connection 0
```

**Comment by sberyozkin** [comment]
@smil2k Thanks for confirming it, I appreciate it must've been dificult
