### ISSUE TITLE
Quarkus image build fails when using fake registry name with quarkus.kubernetes.deploy=true

### ISSUE THREAD

**Issue by spolti** [quarkusio/quarkus#26385]
### Describe the bug

When trying to building a application tagging for a non existing registry or using a image name that was not pushed yet, Quarkus Jib build will fail.

Use case: using minikube remote docker daemon to be able to build and deploy on Minikube without the need to push the container to a registry.

The issue below only happens in case you tag the image and set the kubernetes deployment to true together.
If only the Container image is done, it will work.

```
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'registry.access.redhat.com/ubi8/openjdk-11-runtime:1.11' does not use a specific image digest - build may not be reproducible
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:0aca47bf03430b5ee5033d67ba9b38871470af00fa7d80a38c1cc0ae34270935
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] GET https://dev.local/v2/ failed and will be retried
```

### Expected behavior

Build is finished with no errors.

### Actual behavior

Jib tries do validate the registry or query the image metadata leading the image build to fail.

### How to Reproduce?

1- enable minikube remote docker daemon
2- build the application with the following properties:

```shell
quarkus build -Dquarkus.container-image.build=true -DskipTests  \
    -Dquarkus.container-image.group=kogito \
    -Dquarkus.container-image.name=serverless-workflow-greeting-quarkus \
    -Dquarkus.container-image.tag=1.0-native \
    -Dquarkus.container-image.registry=dev.local \ # required to skip knative image verification
    -Dquarkus.kubernetes.deployment-target=knative \
    -Dquarkus.knative.name=greeting-quarkus-cli \
    -Dquarkus.kubernetes.deploy=true \
    -Dquarkus.kubernetes.namespace=serverless-workflow-greeting-quarkus
```

### Output of `uname -a` or `ver`

Linux 5.18.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:51:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment 21.9 (build 17.0.3+7) OpenJDK 64-Bit Server VM 21.9 (build 17.0.3+7, mixed mode, sharing)

### GraalVM version (if different from Java)

version from Quarkus native builder image

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by spolti** [comment]
> Essentially for Minikube we don't push to a registry but instead but to the docker daemon.

That's the point, the container a.b.c and image I tag it, shouldn't be verified at build time, which in this case, is happening.

**Comment by geoand** [comment]
Can you try adding `quarkus.container-image.push=false`?

**Comment by spolti** [comment]
Hi @geoand sry for the delay, I got the same behavior.

**Comment by geoand** [comment]
I have opened https://github.com/quarkusio/quarkus/pull/26460. Can you check it out?

**Comment by iocanel** [comment]
> Can you try adding `quarkus.container-image.push=false`?
This is the way!

This should be working as expcted, as I recently fixed some bugs around it. If not, then @spolti is either using a version prior to the fix or we have a regression.

**Comment by spolti** [comment]
Hi @geoand, @iocanel sry for the late reply.
With the changes mentioned in the PR the issue is fixed.

Thanks very much for the assistance.

**Comment by iocanel** [comment]
Yay!

**Comment by geoand** [comment]
Excellent!
