### ISSUE TITLE
Pushing Additional Tags to Docker Hub fails

### ISSUE THREAD

**Issue by dlabordus** [quarkusio/quarkus#26383]
### Describe the bug

When using the parameter 'quarkus.container-image.additional-tags' to set additional tags on a docker container pushing fails with a message 'An image does not exist locally with the tag: latest'. 

After analyzing the problem it looks like a problem in the class [DockerProcessor.java](https://github.com/quarkusio/quarkus/blob/main/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java) at line 219.
I think the wrong method is used,  'getAdditionalTags()' should be replaced with 'getAdditionalImageTags()'.
The [old code](https://github.com/quarkusio/quarkus/commit/26cd681f8f6bf00036a79a01ed061b3eedc764e7) was also using this method and it also seems logical.

### Expected behavior

To not use `<tag-name>`, but `<image-name>:<tag-name>`

### Output of `uname -a` or `ver`

Linux ubuntu 5.13.0-52-generic #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.21.10.1, mixed mode, sharing)

### Quarkus version or git rev

2.10.0.final

### Additional information

If needed you can check the [failed build](https://github.com/com-pas/compas-scl-auto-alignment/runs/7073533402?check_suite_focus=true)

**Comment by geoand** [comment]
Thanks for reporting. https://github.com/quarkusio/quarkus/pull/26393 takes care of the issue
