### ISSUE TITLE
Quarkus error after compiling native with Jaeger Tracing

### ISSUE THREAD

**Issue by cesarjv** [quarkusio/quarkus#26384]
### Describe the bug

I am trying to compile an application in Quarkus Native and monitor it using Jaeger Traicing, however, I am encountering a problem that when compiling it is taking the wrong url and not the one I should use to work with opentracing:

Example application.properties file:

```
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.driver=io.opentracing.contrib.jdbc.TracingDriver
quarkus.datasource.jdbc.url=jdbc:tracing:oracle:thin:@172.28.2.134:1522/IVR
quarkus.datasource.username=${USERNAME_CONNECTION_BD:xxxxxxxxxxxxx}
quarkus.datasource.password=${PASSWORD_CONNECTION_BD:xxxxxxxxxx}
quarkus.http.port=${PORT:8082}
quarkus.http.ssl-port=${PORT-SSl:8083}

quarkus.jaeger.service-name=find-puk-code-tracing
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.endpoint=${URL_JAEGER:http://10.161.169.24:14268/api/traces}
quarkus.native.add-all-charsets=true
quarkus.swagger-ui.path=/api/FindPukCodeBS/swagger-ui
quarkus.smallrye-openapi.path=/api/FindPukCodeBS/swagger
quarkus.swagger-ui.always-include=true
```

Locally it works wonderfully, but when I deploy at the kubernetes level it is not taking the url correctly, as follows::

quarkus.datasource.jdbc.url=jdbc:tracing:oracle:thin:@172.28.2.134:1522/IVR

In the logs that appear to me it seems to take the url without the word tracing, however as you can see at the log level it prints the url that is being passed in the application.properties:

![error](https://user-images.githubusercontent.com/31625237/175974197-5e6ea911-4305-427e-9bb1-259d85ef1a41.png)

That could be happening? I don't understand, and I don't have the value burned anywhere, I'm taking it directly from the application.properties.

### Expected behavior

Monitoring with Jaeger Tracing

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 22.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.5.4 (Red Hat 3.5.4-5)

**Comment by brunobat** [comment]
Jaeger tracing extension is now part of Quarkiverse here: https://github.com/quarkiverse/quarkus-opentelemetry-exporter
Is this still a problem @cesarjv? Please let me know or I'll close the issue.

**Comment by brunobat** [comment]
Stale. Closing for now.
