### ISSUE TITLE
Gradle plugin incorrectly requires Gradle 6.1

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/quarkus#26392]
### Describe the bug

The Gradle plugin checks Gradle version when starting, checking for minimum 6.1 but 7.4 is required since 2.10.0.Final

### Expected behavior

Update the test so that 7.4 is required

### Actual behavior

Test is wrong

### Quarkus version or git rev

2.10.0.Final

**Comment by glefloch** [comment]
Thanks for reporting this @jeffmaury, I will check why we need 7.4 but I think we should switch back to support older gradle version.

**Comment by jeffmaury** [comment]
FTR if not using Gradle 7.4 then there are some class cast exceptions between internal Gradle classes that are used by the plugin

**Comment by glefloch** [comment]
Yes I can reproduce the exception
