### ISSUE TITLE
log4j: java.lang.IllegalStateException: Maximum number of attachments exceeded

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#26401]
### Describe the bug

adding dependency `log4j-jboss-logmanager` to the application leads to the following exception when executing the integration test:

```
2022-06-28 11:00:12,440 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /foo failed, err
or id: 9985f0d2-3c6f-4b03-938f-c76130e6048b-1: java.lang.ExceptionInInitializerError
...
Caused by: java.lang.IllegalStateException: Maximum number of attachments exceeded
        at org.jboss.logmanager.LoggerNode.attachIfAbsent(LoggerNode.java:485)
        at org.jboss.logmanager.Logger.attachIfAbsent(Logger.java:196)
        at org.apache.log4j.JBossLogManagerFacade$2.run(JBossLogManagerFacade.java:102)
        at org.apache.log4j.JBossLogManagerFacade$2.run(JBossLogManagerFacade.java:85)
        at org.apache.log4j.JBossLogManagerFacade.doPrivileged(JBossLogManagerFacade.java:269)
        at org.apache.log4j.JBossLogManagerFacade.getLoggerRepository(JBossLogManagerFacade.java:85)
        at org.apache.log4j.JBossLogManagerFacade.getLoggerRepository(JBossLogManagerFacade.java:73)
        at org.apache.log4j.LogManager.getLoggerRepository(LogManager.java:49)
        at org.apache.log4j.LogManager.getLogger(LogManager.java:57)
        at org.apache.log4j.Logger.getLogger(Logger.java:39)
        at com.lodh.foo.Bar.<clinit>(Bar.java:14)
        ... 33 more
```

Surprisingly it works when I compile the application with `skipTests`, and I execute the `java -jar` command. It only fails when the application is started through the integration tests.

### Expected behavior

log4j logging working.

### Actual behavior

It fails during the tests with an exception.

### How to Reproduce?

Not sure at this point. This is happening on the integration test application that validates an extension with multiple dependencies.
I have tried to go back to `2.9.2`, and this fails also. So it is not a regression in `2.10.0`
Would you be able to suggest some things I could test in my build (beside trying to create a full reproducer)?

### Quarkus version or git rev

2.10.0.Final

**Comment by gsmet** [comment]
hey @jamezp does ^ ring a bell?

**Comment by vsevel** [comment]
I tried creating a reproducer (an extension with an integration tests module, which contains a dependency using log4j) but could not reproduce the issue :(

**Comment by jamezp** [comment]
We'd need to defer to @dmlloyd here. The embedded-logmanager has a limit to the number of attachments available.

@vsevel Do you use a combo of different logging facades like log4j, slf4j, log4j2?

**Comment by vsevel** [comment]
this seems to be the same topic as: https://github.com/quarkusio/quarkus/issues/12659 and https://github.com/jboss-logging/slf4j-jboss-logmanager/pull/10

I have rebuilt `org.jboss.logmanager:jboss-logmanager-embedded:jar:1.1.0` with some additional information:

```
s = "==> key=" + key + " value=" + value + " att1Key=" + att1Key + " att2Key=" + att2Key + " att3Key=" + att3Key;
throw new IllegalStateException("Maximum number of attachments exceeded ==> " + s);
```

how come I have 2 different `org.apache.log4j.spi.RootLogger`, and 2 `org.apache.log4j.Hierarchy`?

I checked the dependency tree only has `org.jboss.logmanager:log4j-jboss-logmanager:jar:1.3.0.Final:compile` with respect to log4j.

here are the other embedded logging libraries inside the quarkus test app: 
```
[INFO] |  |  +- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.5.0.Final:compile
...
[INFO] |     +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile
[INFO] |     +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |     +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile
```

during the test execution, I get:

```
        Caused by: java.lang.IllegalStateException: Maximum number of attachments exceeded ==>
 key=5 value=org.apache.log4j.Hierarchy@405ac683
 att1Key=0 att1=org.apache.log4j.spi.RootLogger@3e59d5af
 att2Key=1 att2=org.apache.log4j.Hierarchy@5c74bb78
 att3Key=4 att3=org.apache.log4j.spi.RootLogger@56c4ce99
```

> Do you use a combo of different logging facades like log4j, slf4j, log4j2?

- log4j2 no I do not think so
- log4j yes (dependent lib I don't have an immediate access to)
- slf4j yes
- jboss logging yes
- apache commons logging no

**Comment by vsevel** [comment]
I added a fourth slot for the attachments. my test passes. `4` is the magic number :-)

and it shows:
```
using att4 ==>
 key=5 value=org.apache.log4j.Hierarchy@46f47c38
 att1Key=0 att1=org.apache.log4j.spi.RootLogger@224f3302
 att2Key=1 att2=org.apache.log4j.Hierarchy@57fd2fa9
 att3Key=4 att3=org.apache.log4j.spi.RootLogger@3cbc6a6b
 att4Key=5 att4=org.apache.log4j.Hierarchy@46f47c38
```

how far am I to fail on a fifth one? seems fragile, doesn't it?

**Comment by jamezp** [comment]
Having two different entries for `Hierarchy` and the `RootLogger` seems odd for sure. I was somewhat wondering if there ended up being attachments for slf4j and log4j, but that doesn't seem to be the case here.

It would be interesting to see why entries keep getting added.

**Comment by vsevel** [comment]
this is probably what happens. when I run the test, I get:

```
AK-0:org.apache.log4j.spi.RootLogger@434a63ab[jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93] ,
AK-4:org.apache.log4j.spi.RootLogger@1efe698f[QuarkusClassLoader:Quarkus Base Runtime ClassLoader: TEST@53b7bf01] ,
AK-1:org.apache.log4j.Hierarchy@54a7079e[jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93] ,
AK-5:org.apache.log4j.Hierarchy@3a1aa031[QuarkusClassLoader:Quarkus Base Runtime ClassLoader: TEST@53b7bf01]
```

when I run the application, and exercise the same use case, I get:

```
att has 2 entries ==> 
AK-3:org.apache.log4j.spi.RootLogger@2f7cd4bc[io.quarkus.bootstrap.runner.RunnerClassLoader@26f0a63f] ,
AK-4:org.apache.log4j.Hierarchy@41402ddc[io.quarkus.bootstrap.runner.RunnerClassLoader@26f0a63f]
```

**Comment by vsevel** [comment]
Hello @dmlloyd I prepared https://github.com/dmlloyd/jboss-logmanager-embedded/pull/5 for discussion.
Would you be open to something like this? It does save memory like the previous impl, and is extendable.
There is probably an issue with classloading (either caused by quarkus, or by the libs I am trying to pull in my extensions), and it would be better to fix it.
But regardless, the PR might be a good workaround today for the classloading issue, and a less fragile future proof data structure.
WDYT?

**Comment by dmlloyd** [comment]
It should be fine, I'll review in detail once I've started the day. We are going to converge the forks of JBoss LogManager at some point in the near future, and this change would actually be consonant with that effort.
