### ISSUE TITLE
reactive-oracle-client - connection URI syntax is unclear

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#26426]
### Describe the bug

What is the current situation with proper URI syntax?

From previous bug reports, I'm getting a confusing message:
- https://github.com/quarkusio/quarkus/issues/23439
- https://github.com/quarkusio/quarkus/issues/23728

I did my own experiments with two formats (using `gvenzl/oracle-xe:21-slim` image):
1. `oracle:thin:@localhost:49169:quarkus_test`
    - This worked up until 2.7.5.Final.
2. `oracle:thin:@localhost:49169/quarkus_test`
    - Works since 2.7.6.Final and later.

Vert.x documentation mentions option 1.: https://vertx.io/docs/vertx-oracle-client/java/#_connection_uri.
Quarkus documentation is vague:
- https://quarkus.io/version/main/guides/reactive-sql-clients
- https://quarkus.io/version/main/guides/datasource

The new format (option 2.) is more in line with other reactive DB clients. But it feels to me that, to some extent, users have to guess the correct format.

**Comment by jsmrcka** [comment]
cc @tsegismont

**Comment by geoand** [comment]
@tsegismont can we clarify what works and what doesn't in the docs please?

Thanks

**Comment by gsmet** [comment]
@ebullient could you check that the documentation team received the notification? The teams are not linked in bot comments but I never figured out if the members were receiving the notifications anyway. Probably worth checking and switch to a list of GitHub handles if not.

**Comment by tsegismont** [comment]
> ### Describe the bug
> 
> What is the current situation with proper URI syntax?
> 
> From previous bug reports, I'm getting a confusing message:
> 
>     * [quarkus 2.7 - quarkus-reactive-oracle-client - Wrong syntax of connection URI #23439](https://github.com/quarkusio/quarkus/issues/23439)
> 
>     * [Connection URI syntax for reactive oracle client #23728](https://github.com/quarkusio/quarkus/issues/23728)
> 
> 
> I did my own experiments with two formats (using `gvenzl/oracle-xe:21-slim` image):
> 
>     1. `oracle:thin:@localhost:49169:quarkus_test`
>        
>        * This worked up until 2.7.5.Final.

It doesn't work since 2.7.6? What's the error message?

> 
>     2. `oracle:thin:@localhost:49169/quarkus_test`
>        
>        * Works since 2.7.6.Final and later.

:+1: 

> 
> 
> Vert.x documentation mentions option 1.: https://vertx.io/docs/vertx-oracle-client/java/#_connection_uri. Quarkus documentation is vague:
> 
>     * https://quarkus.io/version/main/guides/reactive-sql-clients
> 
>     * https://quarkus.io/version/main/guides/datasource
> 

This example should be updated. Would you mind filing an issue on `vertx-sql-client` repo ?

> 
> The new format (option 2.) is more in line with other reactive DB clients. But it feels to me that, to some extent, users have to guess the correct format.

We should add a URL reference section similar to https://quarkus.io/guides/datasource#jdbc-url

**Comment by jsmrcka** [comment]
> > I did my own experiments with two formats (using `gvenzl/oracle-xe:21-slim` image):
> > ```
> > 1. `oracle:thin:@localhost:49169:quarkus_test`
> >    
> >    * This worked up until 2.7.5.Final.
> > ```
> 
> It doesn't work since 2.7.6? What's the error message?

Here is what I'm getting with 2.7.6 and later:
```
10:07:38,577 INFO  [app] 10:07:36,776 Mutiny had to drop the following exception: java.sql.SQLException: Listener refused the connection with the following error:
10:07:38,578 INFO  [app] ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
10:07:38,579 INFO  [app]   (CONNECTION_ID=16HA7wUdRS2i9fM1ZShLPA==)
10:07:38,580 INFO  [app] 	at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:903)
10:07:38,581 INFO  [app] 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:708)
10:07:38,581 INFO  [app] 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1089)
10:07:38,582 INFO  [app] 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
10:07:38,583 INFO  [app] 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:733)
10:07:38,584 INFO  [app] 	at oracle.jdbc.datasource.impl.OracleDataSource.getPhysicalConnection(OracleDataSource.java:681)
10:07:38,585 INFO  [app] 	at oracle.jdbc.datasource.impl.OracleDataSource.getConnection(OracleDataSource.java:375)
10:07:38,586 INFO  [app] 	at oracle.jdbc.datasource.impl.OracleDataSource.getConnectionInternal(OracleDataSource.java:2120)
10:07:38,587 INFO  [app] 	at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1845)
10:07:38,588 INFO  [app] 	at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1779)
10:07:38,589 INFO  [app] 	at io.vertx.oracleclient.impl.OracleConnectionFactory.lambda$connect$0(OracleConnectionFactory.java:50)
10:07:38,590 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
10:07:38,591 INFO  [app] 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
10:07:38,592 INFO  [app] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
10:07:38,592 INFO  [app] 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
10:07:38,592 INFO  [app] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:559)
10:07:38,593 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
10:07:38,593 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
10:07:38,594 INFO  [app] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
10:07:38,594 INFO  [app] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
10:07:38,595 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
10:07:38,595 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:829)
10:07:38,596 INFO  [app] Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
10:07:38,596 INFO  [app] ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
10:07:38,596 INFO  [app]   (CONNECTION_ID=16HA7wUdRS2i9fM1ZShLPA==)
10:07:38,596 INFO  [app] 	at oracle.net.ns.NSProtocolNIO.createRefusePacketException(NSProtocolNIO.java:816)
10:07:38,597 INFO  [app] 	at oracle.net.ns.NSProtocolNIO.handleConnectPacketResponse(NSProtocolNIO.java:396)
10:07:38,597 INFO  [app] 	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:207)
10:07:38,598 INFO  [app] 	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:350)
10:07:38,598 INFO  [app] 	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2558)
10:07:38,598 INFO  [app] 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:667)
10:07:38,599 INFO  [app] 	... 20 more
```

> > Vert.x documentation mentions option 1.: https://vertx.io/docs/vertx-oracle-client/java/#_connection_uri. Quarkus documentation is vague:
> > ```
> > * https://quarkus.io/version/main/guides/reactive-sql-clients
> > 
> > * https://quarkus.io/version/main/guides/datasource
> > ```
> 
> This example should be updated. Would you mind filing an issue on `vertx-sql-client` repo ?

Sure, here it is: https://github.com/eclipse-vertx/vertx-sql-client/issues/1209.

**Comment by tsegismont** [comment]
> Here is what I'm getting with 2.7.6 and later:

So it seems it's actually the version of the driver (or of the database) that does not allow to use SID. I wanted to make sure it wasn't a bug in the Vert.x Client URI parser.
