### ISSUE TITLE
Flyway & Liquibase hold up reporting healthy liveness

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#26421]
In a K8s environment a container that is migrating a production database might be expected to take a considerable amount of time. Currently since these migration tools disallow reporting a healthy liveness during migrations. This could cause K8s to kill and restart the container during the migration.

During migrations the Liveness should be reported as healthy while Readiness should be reported unhealthy. This would ensure K8s always allows the correct amount of time for migrations.

**Comment by geoand** [comment]
This is definitely sounds like something we want to address @xstefank @jmartisk

**Comment by xstefank** [comment]
I suppose we have health checks in flyway and/or liquibase extensions? Sorry, I am not familiar with these extensions enough to be able to recommend the correct way to approach this without more context.

**Comment by geoand** [comment]
Nope, they don't provide health checks

**Comment by gsmet** [comment]
Are the health checks even available when the migration is executed? My recollection is that we are waiting for the schema to be migrated before opening the gates for requests.

**Comment by kdubb** [comment]
@gsmet I think you are correct. I investigated a bit last night and from what I could tell the first issue is that the HTTP layer isn't initialized until after migrations are completed.

**Comment by geoand** [comment]
I just tried this and indeed hitting the HTTP health endpoints does not yield a result while the migrations are running.

That sounds like proper behavior to me.

**Comment by kdubb** [comment]
In terms of K8s I cannot agree that this is the proper behavior. I think the proper behavior is to report Liveness while initialization is happening and Readiness after.

Migration is one example, but anything slowing down initialization will cause container restart.

**Comment by geoand** [comment]
Hold on... If you set a proper `initialDelaySeconds` value, you will not get restarted.
I would argue, that setting such a value should be done regardless of whether you are running migrations or not.

**Comment by kdubb** [comment]
Yes but those values are tricky to set correctly because you cannot always know the proper value. K8s added a new "Startup" probe for this reason.

**Comment by geoand** [comment]
Which again you would set to a proper value, right?

**Comment by gsmet** [comment]
I agree with @kdubb that our behavior is not ideal. We are doing stuff, we are live and we shouldn't be restarted. Finding a proper `initialDelaySeconds` will be impossible given you might have from time to time a migration exceeding the delay.

Now... that being said... I have no idea how to properly fix this as we decided quite early that we would open the HTTP gates only when the database is ready.

Maybe that subject is related to the fact that we wanted to have a separate HTTP instance for `q` that might listen on another port. In that case, we could start this one before having the schema migrated.
But my bet is that it's a lot of work.

**Comment by geoand** [comment]
> Now... that being said... I have no idea how to properly fix this as we decided quite early that we would open the HTTP gates only when the database is ready.

I don't think we can fix this without significant refactoring

**Comment by geoand** [comment]
> Finding a proper initialDelaySeconds will be impossible given you might have from time to time a migration exceeding the delay.

That's why k8s has additional settings

**Comment by kdubb** [comment]
I concede this may be a large amount of work to fix and that may preclude it from happening anytime soon. Currently `initialDelaySeconds` might be the only workaround but there are much better features of K8s to support proper startup & initialization.

**Comment by xstefank** [comment]
We do support Startup probes but if you don't expose HTTP there is nothing we can do. We have already a request to make /q endpoints run on a different port in https://github.com/quarkusio/quarkus/discussions/23848.

**Comment by xstefank** [comment]
If you would have HTTP open that should be doable.

**Comment by brunobat** [comment]
If we open HTTP, how long should we wait for readiness? 
Some of these DB operations can be extremely long. Updating an index on a large table can take 20m or 30m long. K8s will have a readiness timeout as well...
If the Flyway and Liquibase operacions operations take a consistent amount of time to run, I believe this is a K8s property tuning problem and will happen independently of the app side lifecycle (pre-deployment, liveness, readiness).
However, there is one problem not covered: Exceptional operations or One-offs. Sometimes we know a schema update will take a very long time and it cannot be predicted. Maybe we are missing some mechanism to just say "Look, I know I'm late, but I'm still working".

**Comment by lostiniceland** [comment]
> Maybe that subject is related to the fact that we wanted to have a separate HTTP instance for `q` that might listen on another port. In that case, we could start this one before having the schema migrated. But my bet is that it's a lot of work.

If I remember correct, this is what the classic application-servers are doing: running the healthcheck outside the actual application deployment/startup (Wildfly runs it under the management-port)

**Comment by dorianm** [comment]
The best way to execute database schema migration it in Kubernetes is to use an init container. See this Liquibase blog post about this problematic : https://www.liquibase.com/blog/using-liquibase-in-kubernetes

At my company, we have multi-module Quarkus project, one module is a Picocli which implement the following job : 

```java
@CommandLine.Command(name = "liquibase-migration")
public class LiquibaseMigration implements Callable<Integer> {

    @Inject
    protected LiquibaseFactory liquibaseFactory;

    @Override
    public Integer call() {
        try (Liquibase liquibase = liquibaseFactory.createLiquibase()) {
            liquibase.validate();
            liquibase.update(liquibaseFactory.createContexts(), liquibaseFactory.createLabels());
        } catch (LiquibaseException ex) {
			// Log error
            return 1;
        }
        return 0;
    }
}
```

And our Kubernetes deployment looks like this : 

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  # [...]
  template:
    spec:
      initContainers:
        image: my-picocli-image:v1.0.0
        name: api-init
      - args:
        - liquibase-migration
      containers:
        image: my-api-image:v1.0.0
        name: api
        ports:
        - containerPort: 8080
          name: http
       livenessProbe:
          httpGet:
            path: /api/q/health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/q/health/ready
            port: 8080
```

I admit if we have a mono-module project, this solution is not very easy to implement… but it can be a good start to resolve this issue.

**Comment by iocanel** [comment]
I think that the kubernetes way of dealing with issues like this is setting up `initContainers` that either perfroms the migration or wait for a `Job` that does. I am not sure which approach is better, so input from people with more experience in flyway and liquidbase could come in handy.

The `kubernetes` extension could detect extensions like flyway/liquidbase and setup intitContainers.

If we introduce an option like: `quarkus.liquibase.migrate-and-exit` we could theoretically use the same image for both the `application` and `migration` and control the behavior via environment variables. 


Thoughts?

**Comment by geoand** [comment]
That's an interesting idea and indeed hearing from people that use flyway/liquidbase in production would be nice.

If we did go down that route, what image would we use for the the initContainer?

**Comment by iocanel** [comment]
> If we did go down that route, what image would we use for the the initContainer?

The app image itself with proper environment variables so that it performs: `migrate & exit`.

**Comment by geoand** [comment]
Ah, good idea!

**Comment by geoand** [comment]
@iocanel we would also need to include some way to stop Quarkus when the migration is done in the initContainer.

**Comment by cthiebault** [comment]
And by using an init container to run Liquibase, it would facilitate the adoption of Hibernate Reactive...
Today, Liquibase does not support reactive jdbc drivers... so we can't use it with Hibernate Reactive :(
The init container would run liquibase with classic JDBC, and the main Quarkus container would use reactive jdbc! :-)

**Comment by geoand** [comment]
That's an excellent point!

**Comment by kdubb** [comment]
I agree with init containers, we use them for all our K8s deployments (dev, test, and prod). This issue actually stemmed from a discussion with another Quarkus user who didn't or had not started using them.

One nice thing, without resorting to full blown image building from the K8s extension, would be to allow manually adding a startup mode to our current application.

Our services are built using a multi-module Gradle project and we refactored the database code & DDL scripts into a separate library specifically so we could create a `@QuarkusMain` application similar to @dorianm's above.

A nice feature, which may not be doable, would be to support building an image "normally" and with a `@QuarkusMain` bean that overrides the normal startup. This would make this support much easier.

**Comment by kdubb** [comment]
Maybe even better, add an `QuarkusAlternateMain` annotation (that is effectively the same as `@QuarkusMain`) and accompanying option that allows you to switch to using that startup bean.

That would allow one container and codebase to support being an `initContainer` and the normal `container`.

**Comment by geoand** [comment]
@iocanel already has: https://github.com/quarkusio/quarkus/pull/29026, which uses some internal configuration to control how much of the application is booted.

**Comment by kdubb** [comment]
That seems perfect. @iocanel Nice work!

**Comment by gastaldi** [comment]
What's the status of this issue? Can it be considered fixed now that https://github.com/quarkusio/quarkus/pull/29026 is merged?
