### ISSUE TITLE
Display information about datasources that are "up" in Agroal healthcheck

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#26431]
### Description

Essentially, in [DataSourceHealthCheck.java](https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java) we'd call `data(...)` even when the datasource is up, simple putting the data `"UP"`.

This would be more consistent with `ReactiveDatasourceHealthCheck`.

See https://github.com/quarkusio/quarkus/pull/26418#pullrequestreview-1022848196

EDIT: Also, we should display the datasource name as `<default>` for the default datasource, not `default`.

**Comment by gsmet** [comment]
@yrodiere also I asked the question about `default` because in the JDBC health check, we use `default` not `<default>`.

**Comment by yrodiere** [comment]
@gsmet That seems like a bad idea given someone can just use `default` as their datasource/PU name. We should probably open another ticket to change that?

**Comment by gsmet** [comment]
@tmihalac this one could be an easy win. The idea is to make the Agroal health check more consistent with the `ReactiveDatasourceHealthCheck`.
