### ISSUE TITLE
Define Extensions via stack

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus#2646]
**Description**
The extensions can be defined using stack - stack basically defines list extensions with single logical name. The users can the define it via `-Dstack="mystack"

**Implementation ideas**

e.g. 

crud-rest.yaml
```yaml
extensions:
 - panache
 - resteasy
 - swagger-ui
 - openapi
```

myapp-stack which extends from `crud-rest`:

```yaml
extensions:
 base: crud-rest
 extras:
  - mariadb
```

It will also be nice if we define it via CLI like 

`mvn io.quarkus:quarkus-maven-plugin:0.15.0:create -Dstack="curd-rest"`

We can also add and remove the extensions from the stack like 

`mvn io.quarkus:quarkus-maven-plugin:0.15.0:create -Dstack="curd-rest,+kubernetes,-swagger-ui"`

cc: @emmanuelbernard

**Comment by emmanuelbernard** [comment]
So the idea behind it is to defined profile stacks for expected types of apps. The one stack we identified is REST CRUD + DB (Hibernate) but we need to identify a list of stacks we would want to see define. A list of "typical apps really". If we see 7+ emerging, we can consider the extra semantic overhead of stacks vs what we currently have.

So let's try and get a list:

- REST CRUD + Hibernate
- Kafka consumer
- ...

**Comment by gsmet** [comment]
I'm not entirely sure this is valuable and won't be a pain to maintain. We want things to be flexible and I don't see a lot of value to it. Adding the extensions you want is not hard IMHO.
