### ISSUE TITLE
Automatic Kubernetes Service Binding extension with Kafka breaks on new deploy

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#26463]
### Describe the bug

Using Automatic Service Binding with Kafka, new deployment breaks the DeploymentConfig.

It seems that when creating the Service Binding in OpenShift, it adds some binding to the DC (which was originialy generated and deployed by the Openshift extension), it adds envs: `SERVICE_BINDING_ROOT=/bindings`, storage & secrets.

Which makes the app work with Kafka.

But when deploying again:
```bash
mvn clean package  -Dquarkus.kubernetes.deploy=true
```
The DC is "reseted" to original and all the binding stuff is removed leading to an exception:
```
'kafka.bootstrap.servers' must be set when 'quarkus.kubernetes-service-binding.enabled' 
```

### Expected behavior

We should inform the user that deploying is breaking the bindings:
- build warning on deploy
- guide with info on what the DC should contains for service bindings
- exception could inform the user to check if the in the DC environment if the binding is present (and link to a guide section)

or make it keep the bindings (but I don't see how).

### Actual behavior

There is no way to know what is going on beside debugging for hours, the pod crashes in loop.

### How to Reproduce?

1. Setup an OpenShift Sandbox with a Managed Kafka (and its topics and roles)
2. Create the "Red Hat OpenShift Streams for Apache Kafka" in OpenShift
3. Create a Quarkus App with Kafka and deploy it `mvn clean package  -Dquarkus.kubernetes.deploy=true`
4. Add the Service Binding link between Quarkus and Kafka 
5. It should work (maybe a rollout if it doesn't)
6. Redeploy: `mvn clean package  -Dquarkus.kubernetes.deploy=true`
7. Should crash in loop

### Quarkus version or git rev

1.10.1.Final

### Additional information

I am not sure if it also breaks for other bindings (storage...)

### Workaround

Use this to update the app (It won't update the resources, but just the Quarkus containers):
```bash
mvn clean package  -Dquarkus.container-image.build=true
```

If a re-deployment is necessary, after the deployment, delete the Service Binding and the "Red Hat OpenShift Streams for Apache Kafka", and re-create it.

**Comment by ozangunalp** [comment]
@ia3andy I am pretty sure this is related to the SBO not mounting service credentials to the service binding root. As you noticed, a container image update resolves the issue. 

I am not sure though if this is related to the credentials provider being rhoas. I noticed the same thing for service registry.

**Comment by iocanel** [comment]
Can you please provide more details on: `Add the Service Binding link between Quarkus and Kafka`?

**Comment by ia3andy** [comment]
> Can you please provide more details on: `Add the Service Binding link between Quarkus and Kafka`?

Just draw the arrow from Quarkus to Kafka from the topology view.

**Comment by geoand** [comment]
I think this is the problem that @cescoffier had mentioned a months ago and that there is nothing we can do on our side

**Comment by ia3andy** [comment]
> I remember having a different behavior on DeploymentConfig. Can you try deploying the quarkus app as Deployment?

I think it works, @sebastienblanc told me he was using the Kubernetes extension instead of the Openshift one and it was working fine (I haven't tested myself).

**Comment by ia3andy** [comment]
> I think this is the problem that @cescoffier had mentioned a months ago and that there is nothing we can do on our side

Yes we discussed it already, but documenting it would be way better than nothing to avoid dev frustration.
