### ISSUE TITLE
Allowed multiple named configurations for Infinispan client

### ISSUE THREAD

**Issue by tristantarrant** [quarkusio/quarkus#26478]
### Description

The current Infinispan extension only supports a single RemoteCacheManager. Ideally we should allow specifying multiple named configurations, using an annotation such as `@InfinispanClientName`.

```java
// Inject the default client
@Inject
RemoteCacheManager remoteCacheManager;

// Inject the "other" client
@Inject @Remote("other")
RemoteCacheManager remoteCacheManager;
```

```
quarkus.infinispan-client.server-list=hotrod://host:11222
quarkus.infinispan-client.other.server-list=hotrod://host-other:11222
```

**Comment by geoand** [comment]
We definitely want something like this. We do something similar for most of the other datasources.

**Comment by karesti** [comment]
@tristantarrant @geoand taking this point. https://issues.redhat.com/browse/ISPN-14012
