### ISSUE TITLE
Quarkus create app does not work on Mac and lacks documentation

### ISSUE THREAD

**Issue by myfingersarebroken** [quarkusio/quarkus#26487]
### Describe the bug

I followed all the steps to use Quarkus, but project initialization does not work and documentation lacks information on how to resolve it.
Using the quarkus create app returns the following error.

```
$ quarkus create app
[WARN] 🔥  Configured Quarkus extension registries appear to be unavailable at the moment. It should still be possible to create a project by providing the groupId:artifactId:version of the desired Quarkus platform BOM, e.g. 'quarkus create -P io.quarkus.platform:quarkus-bom:2.10.0.Final'
[ERROR] ❗  Unable to create project: Failed to resolve the Quarkus extension registry descriptor of registry.acme.org from registry.acme.org (https://registry.acme.org/maven)
```

**Comment by maxandersen** [comment]
Is that the *Actual* error?

I assume it actually says some specific names and the issue is that somehow you are running behind a proxy and some host name is not accessible. 

If you can show the actual full stack trace it should be more telling and we can better help.

**Comment by ruby-ts** [comment]
I'm new to Quarkus. In my case, the issue is resolved after deleting this folder in my home directory: `~/.m2`.  It must be some really old Maven cache.

**Comment by maxandersen** [comment]
Any chance you got the full error/stack trace ?

**Comment by cw-20022016** [comment]
I had same error, 
![image](https://github.com/quarkusio/quarkus/assets/132977999/fd65d5b8-4680-4246-a02c-df626cd8e96a)

**Comment by maxandersen** [comment]
Same question - can you provide the full stack trace? Run the command with -e and --verbose ?

You should be able to create a default project without a internet connection as long as you have quarkus dependencies available...

**Comment by cw-20022016** [comment]
sorry to late response. I'm trying to reproduce same issue, but it hasn't happened since then. 

Is there a way to view system logs for the quarkus command?
