### ISSUE TITLE
How do we pass password in user configuration

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2648]
**Description**
Right now, passwords are written in plain text in the user configuration. 

**Implementation ideas**

Several choices:

* a specific encrypted password.properties file
* a mechanism to encrypt and decrypt the password

**Comment by starksm64** [comment]
This is on my topic list for the security arch discussion. I have been distracted on getting this kicked off, but I'm going to start something next week one way or another to get a comment direction.

**Comment by gsmet** [comment]
See https://github.com/eclipse/microprofile-config/issues/451 or https://github.com/quarkusio/quarkus/issues/3937 or https://github.com/quarkusio/quarkus/issues/3279

**Comment by gsmet** [comment]
I think I will close this one as we have already some issues to track the Vault effort and that seems the way to go.

**Comment by anborg** [comment]
App developer must be able to use Quarks safely (encryped db passwords) even without quarkus. 

Is't it?

**Comment by jcunliffe1** [comment]
I agree with @anborg - currently we are facing serious issues running quarkus in an enterprise environment without vault and have to basically implement password encryption/decryption ourselves.
