### ISSUE TITLE
Quarkus startup time is 2x or more slower on slow networks

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2649]
We had several reports of people on non controlled networks like at conferences where Quarkus startup time was very slow. 2x or much more. I experienced it myself a few times and ended up disabling network on stage.

I think the problem is a JVM issue or one of our framework network stack.

There is a famous slow down of the JVM on macOS if people don't have a local resolution rul in their `etc/hosts`

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost
```

But even with that, I see startup time going from .5 to 1s on conference networks

It would be good to get a OpenJDK+Perf+Quarkus+RESTEasy team to investigate that and find the bottom of this problem

CC @stuartwdouglas @dmlloyd @n1hility @stalep

**Comment by dmlloyd** [comment]
Is there an example app that can be used for testing?

**Comment by stuartwdouglas** [comment]
Does -Dquarkus.http.host=127.0.0.1 help at all?

**Comment by loicmathieu** [comment]
Hi,
Maybe this is related to the issue I reported #2558 as I works on WIFI and it is sometimes slow. Maybe the investigation for this one should be focused on OpenAPI. But a commented on #2558 it should be fixed on 0.16.0 as OpenAPI annotations will be processed at build time.

**Comment by emmanuelbernard** [comment]
The skeleton app with the rest en point generated by maven does it.

**Comment by rsvoboda** [comment]
@emmanuelbernard should we keep this open?

**Comment by emmanuelbernard** [comment]
It's something I'd love to go to the bottom of as it affect presentations. But among other things, this is low priority.

**Comment by famod** [comment]
@emmanuelbernard Is this still a problem?

**Comment by emmanuelbernard** [comment]
I have not tried since we are no longer travelling and physical crappy networks are out of my reach :)

**Comment by gsmet** [comment]
Let's close this and open a new one later if needed.
