### ISSUE TITLE
Enabling the SmallRye Metrics extension on a project with the AWS Lambda extension breaks the behaviour of the lambda

### ISSUE THREAD

**Issue by StFS** [quarkusio/quarkus#26505]
### Describe the bug

Developing a lambda using the AWS Lambda extension (quarkus-amazon-lambda) allows me to run the Quarkus dev server (`./mvnw quarkus:dev`) and call the lambda using curl:

```
curl -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{"greeting":"herzlich willkommen", "name":"aaron"}'
"Hello aaron"%
```

However, if I add the SmallRye Metrics extension (`quarkus-smallrye-metrics`) to the project, it results in the curl command not working anymore:

```
curl -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{"greeting":"herzlich willkommen", "name":"aaron"}'
<html><body><h1>Resource not found</h1></body></html>%
```

### Expected behavior

The curl command that invokes the lambda should continue working even though the SmallRye Metrics extension is added to the project.

### Actual behavior

The curl command doesn't invoke the lambda as expected but instead returns a "Resource not found" error.

### How to Reproduce?

The simplest way is to create a Quarkus project using code.quarkus.io.

Only enable the two extensions:

- quarkus-amazon-lambda
- quarkus-smallrye-metrics

Java version probably doesn't matter but I've verified this happens if I use Java 11. Select "Yes" for "Starter Code". I used Maven as the Build Tool.

Now, comment out the quarkus-smallrye-metrics dependency in the pom.xml file to establish the baseline of a working project:

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-amazon-lambda</artifactId>
    </dependency>
    <!--
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-metrics</artifactId>
    </dependency>
    -->
```

Run the Quarkus development server: `./mvnw quarkus:dev`

Verify that the curl command works as expected:

```
curl -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{"greeting":"herzlich willkommen", "name":"aaron"}'
"Hello aaron"%
```

Now enable the quarkus-smallrye-metrics dependency by commenting it back in.

Now the curl command doesn't work as before:

```
curl -XPOST "http://localhost:8080/2015-03-31/functions/function/invocations" -d '{"greeting":"herzlich willkommen", "name":"aaron"}'
<html><body><h1>Resource not found</h1></body></html>%
```

**Comment by brunobat** [comment]
@StFS Smallrye Metrics is no longer under active development and is to be marked as deprecated soon. Would you be able to switch to Micrometer and give it a try?

**Comment by brunobat** [comment]
@StFS Will Micrometer do it?
Please let me know or I will close the issue.

**Comment by brunobat** [comment]
Stale. Closing for now
