### ISSUE TITLE
Evaluate quarkus:remote-dev vs odo watch vs ksync

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2650]
CC @stuartwdouglas @gorkem

We have quarkus:remote-dev which is nice for running live reload from your container based on local file cahnges. I think it's based on websockets?. There are a couple of gotchas I think though:

- @cescoffier was having concerns that websocket has a buffer limit so will it fail at some point?
- it works by having the local dev mode connect the container dev mode and sustain the connection. Upon request the container dev mode asks the local dev mode for list of changes. 
    - that means we need a route from local to the container whether you really want to expose a route or not in the end: it would be automated when setup in remote dev mode

There is an alternative model via a tool call ksync that @kameshsampath mentioned to me. See his usage https://www.youtube.com/watch?v=VoaC_jbGqGs&feature=youtu.be and the tool proper https://github.com/vapor-ware/ksync 

I don't know the drawbacks of ksync (poll vs event driven?) but it seem to support even replicas which is interesting. Also being a simple file sync it should be fairly robust and support all "request protocols" beyond the HTTP one we have today (say raw TCP or Kafka).

So this issue is to spend a bit of time to decide were we want to go, rebase remote-dev off ksync or keep remote-dev.

One positive thing about remote-dev is:

- i don't think it's that much code
- it's abstracted from Kube so works everywhere even on a remote bare metal
- with the plan for a wider quarkus:go or wider quarkus:dev user experience, maybe keeping remote-dev makes more sense (I don't see why atm).

**Comment by stuartwdouglas** [comment]
I think we can mark this as resolved, as we now support a sync based remote dev, as well as a HTTP based one. The sync based approach lets you use whatever tool you want to sync the file systems.
