### ISSUE TITLE
Dependency Graph Walk leads to StackOverflowError

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#26502]
### Describe the bug

Our `ConsumerPactTest` throws `java.lang.StackOverflowError`. I tracked this issue down to the #26411.

### Expected behavior

No stack issues.

### How to Reproduce?

Reproducer:

1. `git clone https://github.com/quarkus-qe/quarkus-test-suite`
2. `cd quarkus-test-suite/test-tooling/pact`
3. `mvn clean verify`

### Output of `uname -a` or `ver`

Linux fedora 5.18.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:51:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Lin

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

999-SNAPSHOT; HEAD d94c5a1d0a55787a2349cbb103a1f42771d23c0a

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by michalvavrik** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
@michalvavrik thanks for reporting the issue. We also caught it in https://github.com/quarkusio/quarkus/issues/8593#issuecomment-1172052700
