### ISSUE TITLE
Kubernetes extension(s) have stopped generating the app.openshift.io/runtime label

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#26516]
### Describe the bug

I'm not sure which extension it is, but since Quarkus 2.10.1.Final the `app.openshift.io/runtime: quarkus` label is now missing from resources generated when using `quarkus.kubernetes.deployment-target=openshift`. For some reason it is still working when setting `quarkus.kubernetes.deployment-target=knative`.

You can see this in this diff: https://github.com/quarkusio/quarkus-super-heroes/commit/fe02dae8e887df95e903bda3b5a36baf6f075336?diff=unified#diff-dc6194623579af548ca3da8872f2c72c20d41fb010026243a203b2d52da3defaL48

This commit is the diff between `2.10.0.Final` & `2.10.1.Final`. There were no other commits in between the upgrade to `2.10.0.Final` (where it was behaving correctly) and `2.10.1.Final` (where it is missing).

**Comment by geoand** [comment]
Seems related to https://github.com/quarkusio/quarkus/issues/26273. 
However we do have tests that ensure that `app.openshift.io/runtime` is set to `quarkus` when `quarkus.openshift.labels."app.openshift.io/runtime"` is not set.

Does the application perhaps have any relevant configuration?

**Comment by edeandrea** [comment]
Nope. Not a single line of code changed between 2.10.0.Final and 2.10.1.Final. The label disappeared in 2.10.1.Final.

**Comment by geoand** [comment]
I couldn't reproduce this.

In the `rest-fights` service I updated to `2.10.1.Final` and when doing `mvn clean package -DskipTests -Dquarkus.kubernetes.deployment-target=openshift` I still saw `app.openshift.io/runtime: quarkus` being set to `quarkus`.

**Comment by edeandrea** [comment]
Did you remove https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/main/resources/application.properties#L109 ?

As I mentioned in my last comment I added that in after I noticed the label missing.

**Comment by geoand** [comment]
Yes, the configuration was not present in my test

**Comment by edeandrea** [comment]
@geoand Remove `quarkus.openshift.labels."app.openshift.io/runtime"=quarkus` from `rest-fights/src/main/resources/application.properties` & run this command from the `rest-fights` directory:

```shell
./mvnw clean package -DskipTests -Dquarkus.kubernetes.deployment-target=openshift -Dquarkus.knative.labels.\"app.openshift.io/runtime\"=quarkus
```

Then look at `target/kubernetes/openshift.yml`. You'll notice the `app.openshift.io/runtime: quarkus` label is missing

**Comment by geoand** [comment]
Gotcha, I see what the problem is.
