### ISSUE TITLE
ListExtensionsTest has never reached code

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2651]
https://github.com/quarkusio/quarkus/blame/master/devtools/common/src/test/java/io/quarkus/cli/commands/ListExtensionsTest.java#L143

`checkGuideInLineAfter` is false so code can never be reached.

@Dufgui what was the plan with this `} else if (checkGuideInLineAfter) {`

**Comment by Dufgui** [comment]
I want to code more test but I wait for the issue on list outdated to do it
