### ISSUE TITLE
Rest client reactive does not follow POST redirects

### ISSUE THREAD

**Issue by joern19** [quarkusio/quarkus#26517]
### Describe the bug

When requesting a GET resource using the reactive rest client, which returns any redirect code, and `quarkus.rest-client."config-key".follow-redirects` is set to true, quarkus follows the redirect as expected. However, doing the same thing but using POST instead, quarkus throws an exception: `org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Server response is: 307'`. 

### Expected behavior

POST redirects are followed just like GET redirects.

### Actual behavior

An exception is thrown.

### How to Reproduce?

Set `quarkus.rest-client."rest-client".follow-redirects` to true.

Here is the broken POST example:

```java
public class Simple {

  @Path("/redirect")
  @RegisterRestClient(configKey = "rest-client", baseUri = "http://localhost:8080")
  public static interface SimpleService {
    @POST
    Uni<String> getRootAsUni();
  }

  @Path("/")
  @ApplicationScoped
  public static class SimpleResource {

    @RestClient
    SimpleService simpleService;

    @POST
    @Path("redirect")
    public Uni<Response> redirect() throws URISyntaxException {
      return Uni.createFrom().item(Response.temporaryRedirect(new URI("/hello")).build());
    }

    @POST
    @Path("hello")
    public String get() {
      return "Hello World!";
    }

    @GET
    @Path("makeRequest")
    public Uni<String> makeRequest() {
      return simpleService.getRootAsUni().log().replaceWith("ok");
    }
  }
}
```

And here is the working GET example:

```java
public class Simple {

  @Path("/redirect")
  @RegisterRestClient(configKey = "rest-client", baseUri = "http://localhost:8080")
  public static interface SimpleService {
    @GET
    Uni<String> getRootAsUni();
  }

  @Path("/")
  @ApplicationScoped
  public static class SimpleResource {

    @RestClient
    SimpleService simpleService;

    @GET
    @Path("redirect")
    public Uni<Response> redirect() throws URISyntaxException {
      return Uni.createFrom().item(Response.temporaryRedirect(new URI("/hello")).build());
    }

    @GET
    @Path("hello")
    public String get() {
      return "Hello World!";
    }

    @GET
    @Path("makeRequest")
    public Uni<String> makeRequest() {
      return simpleService.getRootAsUni().log().replaceWith("ok");
    }
  }
}
```

### Output of `uname -a` or `ver`

5.18.5-1-MANJARO

### Output of `java -version`

openjdk 11.0.15 2022-04-19

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
It seems like this is intended Vert.x behavior, see [this](https://vertx.io/docs/vertx-core/java/#_30x_redirection_handling).
Furthermore, [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-10.3.8) explicitly mentions that redirection for HTTP 307 should only happen on `GET` and `HEAD` requests:

```
   If the 307 status code is received in response to a request other
   than GET or HEAD, the user agent MUST NOT automatically redirect the
   request unless it can be confirmed by the user, since this might
   change the conditions under which the request was issued.
```

So I am going to close this as `won't fix`

**Comment by geoand** [comment]
@jdussouillez something like you describe would indeed be useful.

The issue I see is coming up with a proper API for the `RedirectHandler` interface as we don't want to expose the Vertx types.

**Comment by jdussouillez** [comment]
> The issue I see is coming up with a proper API for the RedirectHandler interface as we don't want to expose the Vertx types.

Yeah that's a problem. Maybe it's possible to reuse `javax.ws.rs` classes ? But I doubt it'll match perfectly the Vert.x types, especially for the [RequestOptions](https://vertx.io/docs/apidocs/io/vertx/core/http/RequestOptions.html) type...

For example :

```java
import javax.ws.rs.core.Response; // This is the type used in ResponseExceptionMapper (Microprofile) but I guess it would work here
// TODO: implement a new RequestOptions class?

public interface RedirectHandler {
    Uni<RequestOptions> handleRedirect(Response response); // Or Uni<Optional<RequestOptions>> to avoid returning "null"
}
```

Do you want me to create another issue with this feature request ?

**Comment by geoand** [comment]
> Do you want me to create another issue with this feature request ?

Sure yeah
