### ISSUE TITLE
Darwin native toolchain target architecture problem

### ISSUE THREAD

**Issue by crionuke** [quarkusio/quarkus#26527]
### Describe the bug

Hello, there!

Tried to compile java code with quarkus framework to native binary.
As result got next error:
Error: Darwin native toolchain (x86_64) implies native-image target architecture class jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.

Many thanks for any help of how to solve this issue.

**My configuration:**
Chip -> Apple M1 Pro
xcode-select --install -> xcode-select: error: command line tools are already installed, use "Software Update" to install updates
GraalVM distr from this - https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/22.3.0-dev-20220702_0120/graalvm-ce-java11-darwin-aarch64-dev.tar.gz
echo $GRAALVM_HOME -> /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0-dev/Contents/Home
java -version ->
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.3.0-dev (build 11.0.16+7-jvmci-22.2-b04)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0-dev (build 11.0.16+7-jvmci-22.2-b04, mixed mode)
Checked my terminal by command arch, and got arm64

Use this to build ./mvnw clean package -Dnative

**Comment by zakkak** [comment]
This turned out to be caused by setting `JAVA_HOME` to point to an x86_64 JDK instead of an arm64 JDK, see https://github.com/oracle/graal/issues/4694
