### ISSUE TITLE
RESTEasy Reactive - support binary content streaming with header control

### ISSUE THREAD

**Issue by huw0** [quarkusio/quarkus#26523]
### Description

**Summary** - Quarkus RESTEasy Reactive should natively support `Uni<RestResponse<Multi<byte[]>>>`

**Description**

I am using the solution outlined [here](https://groups.google.com/g/Quarkus-dev/c/odN4RjU_ybE) for streaming binary content using `Multi<byte[]>`.

It is essential that the response and headers can be set dynamically. For example `Content-Type` and `ETag`. The latter allows dynamically sending `304 Not Modified` on any later duplicate requests.

There has been [discussion](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Dynamic.20content.20type.20and.20Multi.3Cbyte.5B.5D.20.3E/near/286638048) about this on Zulip.

**Comment by geoand** [comment]
Thanks for reporting.

I would say that supporting `Uni<RestResponse<Multi<byte[]>>>` is not ideal as that type is very complicated and not very intuitive...

**Comment by FroMage** [comment]
Well, the type is far from ideal, for sure. But I can think of cases where this is required, for example if the header data comes from the DB (size, file name) and the content is then streamed from FS or online storage or whatever. So unfortunately it makes a lot of sense :(
