### ISSUE TITLE
mention of "quarkus.rest.path" resteasy-reactive guide

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#26535]
### Describe the bug

In https://quarkus.io/guides/resteasy-reactive#declaring-endpoints-uri-mapping, there is a mention of "quarkus.rest.path":
"This will cause all rest endpoints to be resolve relative to /api, so the endpoint above with @Path("rest") would be accessible at /api/rest/. You can also set the `quarkus.rest.path build time property to set the root path if you don’t want to use an annotation."

It should be "quarkus.resteasy-reactive.path"

**Comment by geoand** [comment]
This was fixed in #26513
