### ISSUE TITLE
The option "--debug=true" of quarkusDev is catched by gradle

### ISSUE THREAD

**Issue by mar9000** [quarkusio/quarkus#2653]
**Can't use --debug=true with gradle to activate suspend=y**

As the documentation states this command should be fine:
```
quarkus-quickstarts-0.15.0/getting-started $ ./gradlew quarkusDev  --debug=true
```
but with it gradle complains with this message:
```
Command-line option '--debug' does not take an argument.
```
The option is indeed catched by gradle instead of been passed to QuarkusDev.
**To reproduce**:  
I've used the *quarkus quick starts* so it can be used also to reproduce the problem.

**Comment by geoand** [comment]
If use you plan `--debug` is the option passed correctly to the task or is it intercepted by Gradle?

**Comment by mar9000** [comment]
It's intercepted by gradle as well, logging lots of additional logs as expected:
```
quarkus-quickstarts-0.15.0/getting-started $ ./gradlew  quarkusDev  --debug
09:15:09.016 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/marco/.gradle/native
09:15:09.149 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Executing build 361ac7a1-b9e9-4a95-919d-1f3432b25946 in daemon client {pid=28087}
09:15:09.151 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface docker0
09:15:09.151 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
09:15:09.151 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:42:43ff:fe5f:f87e%docker0
09:15:09.151 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.17.0.1
[snip]
```

**Comment by geoand** [comment]
@gsmet I think the only viable option here is to change the name of the property in the gradle plugin. Not a great option admitedly (since the name of the property will differ between Maven and Gradle) but I don't think there are other options.

**Comment by gwenneg** [comment]
Any approving reviewer available for the PR?

**Comment by gwenneg** [comment]
Thanks @geoand!

**Comment by geoand** [comment]
Thank you for your work on the PR!

**Comment by gwenneg** [comment]
@gsmet I don't know how important the `milestone` is, but this will be part of `0.19.0` and there's no milestone on the issue or the PR.

**Comment by geoand** [comment]
Good catch, I added the milestone to the PR
