### ISSUE TITLE
Openapi Shema annotations default value issue

### ISSUE THREAD

**Issue by KyriacosP** [quarkusio/quarkus#26546]
### Describe the bug

When using the @Schema annotation with the defaultValue parameter the value is not converted to the correct type when the OpenAPI specification is generated by quarkus-smallrye-openapi. The issue happens with the integer and boolean types as you can see in the screenshots.

![image](https://user-images.githubusercontent.com/44581807/177170068-88f9be32-93cc-488c-a327-85baffb8098c.png)
![image](https://user-images.githubusercontent.com/44581807/177170092-e10ff123-6199-44f0-aced-d4935b69b73c.png)

### Expected behavior

The corrected behavior is that the defaultValue is converted to the correct type like it happens with the example value.

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by MikeEdgar** [comment]
This is an issue/bug for smallrye-open-api. I've opened https://github.com/smallrye/smallrye-open-api/issues/1174 to track it.

**Comment by KyriacosP** [comment]
ok thank you!
