### ISSUE TITLE
Add support for avro.codegen.avsc.imports during the Avro generation

### ISSUE THREAD

**Issue by hendrik-bammel** [quarkusio/quarkus#26560]
### Describe the bug

As i follow the documentation from [avro-code-generation-details](https://quarkus.io/guides/kafka-schema-registry-avro#avro-code-generation-details) and set the the "avro.codegen.avsc.imports" property to the path where my schema files are stored, the code generation only works if there is at least an empty "src/main/avro" folder.

### Expected behavior

The code generation should work, if there is no avro folder ("src/main/avro").

### Actual behavior

No code generation takes place and neither any error nor info is raised if the folder is not there.

### How to Reproduce?

Steps to reproduce
1. Set the property "avro.codegen.avsc.imports" to a folder
2. Delete the avro folder under "src/main/avro"
3. Execute gradle task "quarkusGenerateCode"
4. No code for avro files of given path path in property is generated

**Comment by cescoffier** [comment]
@alesj would you be interested to have a look?

**Comment by cescoffier** [comment]
@ozangunalp has a quick look, and it does not look nice. It could be fixed with a hack, but we may need to re-implement the codegen support of Avro to use resources instead of the file system (as it could potentially access files from outside the project scope (like ../../../etc/passwd). I will let @ozangunalp give more details.

**Comment by ozangunalp** [comment]
I looked at this more closely. 
The primary utility of `avro.codegen.avsc.imports` config is to allow schema files to reference each other and codegen coherently without setting up a complex schema resolver. It is the same functionality as the avro-maven-plugin `imports` config. (Same applies for avdl, avpr files) It'll basically parse imports before the files in the main source directory, for the latter to reference already parsed schema. 

As @cescoffier mentioned we can fix the issue to compile only imports, it is what the avro-maven-plugin does. 
But these imports won't be watched during Quarkus dev mode. Unless there isn't a compelling use case I don't think we need to change that. (It does work of course if the imports directories/files are inside `src/main/avro` directory, which is watched.) 

@cescoffier As for the security aspect, these files are now on source directories so during codegen they are not in the classpath – as opposed to resources. To be fair it is the same for avro-maven-plugin. 

All in all, I am planning to enable imports without the existence of `src/main/avro` and add some debug logs.

**Comment by ayushdgupta** [comment]
How to change the path of generated java files from one avro schema in build.gradle
