### ISSUE TITLE
Serialization support

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2656]
Introduce support for Java serialization

**Comment by dmlloyd** [comment]
Emmanuel says we should wait for someone who needs it, which I agree with.  I believe Bela has some interest in this from a JGroups perspective though.

**Comment by dmlloyd** [comment]
See also: https://github.com/oracle/graal/issues/460

**Comment by mschorsch** [comment]
Java Serialization Support was added to GraalVM.

https://github.com/oracle/graal/issues
/460#issuecomment-754114425

**Comment by ppalaga** [comment]
GraalVM 21.0.0 with serialization support is out.

**Comment by ppalaga** [comment]
Camel Quarkus definitely interested in having some sort of SerializableClassBuildItem on Quarkus. 

I'd give a try unless there is somebody else working on it already?

**Comment by ppalaga** [comment]
There is https://github.com/quarkusio/quarkus/pull/15380

**Comment by geoand** [comment]
With https://github.com/quarkusio/quarkus/pull/15380 in, is there something else that should be done around this issue or can we close it?

**Comment by ppalaga** [comment]
Although there still are ways how #15380 can be improved (@JiriOndrusek may know more), the serialization is there now and is usable. Let's close.
