### ISSUE TITLE
Reactive Mongo  and message not work

### ISSUE THREAD

**Issue by rosell** [quarkusio/quarkus#26576]
### Describe the bug

When try to a reactive action over the Mongo database when an event is consumed, the onItem or onFailure are never called.

I created a [project](https://github.com/rosell/quarkus-reactive-mongo-events-error)  that shows this. This project contains a startup point that try to populate the database with some data. And how you can see on the unit test the database is not populated. I provide an example with the client directly, with a panache repository and a panache entity and on the 3 cases does not work.

### Expected behavior

To do the action into the database and continue.

### Actual behavior

Nothing happens.

### How to Reproduce?

1.  git clone https://github.com/rosell/quarkus-reactive-mongo-events-error.git
2. If you have docker you can start using the ./startDevelopmentenvironment.sh . Otherwise you need to install the OpenJdk-17
3. ./mvnw clean install
4. After some time you can see that the unit test fails

### Output of `uname -a` or `ver`

Linux 80cf2b3bd797 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /root/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Oracle Corporation, runtime: /usr/local/openjdk-17 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.10.104-linuxkit", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
You are not using Mutiny properly - basically you have not created a subscription for the data. 
Reactive Messaging will create this subscription automatically if you return a `Multi` from your method. 
I propose refactoring your `Populate` class to remove the `Emitter` and do what I mention above
