### ISSUE TITLE
workingDir in quarkusDev not respected by gradle anymore

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#26586]
### Describe the bug

We set the workingDir in gradle like the following:

```gradle
        quarkusDev {
            workingDir = rootProject.projectDir
        }
```

We use this, so that the configuration `config/application.properies` is found and loaded for dev-mode. Since 1.10.x this isn't working anymore and it tries to load the config `\build\classes\java\main\config\application.properties` like when the workingDir is not set.

### Expected behavior

It should load the configuration from the `workingDir/config/application.properties`

### Output of `java -version`

17

### Quarkus version or git rev

1.10.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.2

**Comment by glefloch** [comment]
@joggeli34 do you mean version 1.10.x or 2.10.x ?

**Comment by joggeli34** [comment]
My fault, I mean 2.10.x. 
Sorry

**Comment by joggeli34** [comment]
Any chance this get backported to 1.11.x? As this is blocking us from upgrading to 1.10 and also 1.11
