### ISSUE TITLE
Generic runtime exception mapper used for `javax.ws.rs.WebApplicationException`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#26584]
### Describe the bug

When using the `quarkus-resteasy-reactive` and adding the generic exception mapper with the default priority `Priorities.USER`, then the `org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper` that should handle "infrastructure" exceptions like `javax.ws.rs.WebApplicationException` is not actually doing it.

We have seen this for the `javax.ws.rs.NotAllowedException: HTTP 405 Method Not Allowed`. Once raised, it will still reach the generic exception mapper that we defined.

Seems that the issue can be the following. Although the `RuntimeExceptionMapper#mapException` is intercepting the `WebApplicationException`, it's not returning the response it creates as entity is `null`:

```
        if (isWebApplicationException) {
            response = ((WebApplicationException) throwable).getResponse();
        }
        if (response != null && response.hasEntity()) {
            context.setResult(response);
            return;
        }
```

Would this be expected behavior?

### How to Reproduce?

Add the following exception mapper and make HTTP call that should return `405`.

```
  @ServerExceptionMapper
  public RestResponse<ApiError> runtimeException(RuntimeException exception) {
    return ResponseBuilder.create(Response.Status.INTERNAL_SERVER_ERROR).build();
  }
```

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.3, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-52-generic", arch: "amd64", family: "unix"

### Additional information

Workaround currently would be to manually check in the user-defined exception mapper and exception is `javax.ws.rs.WebApplicationException` and return response that it contains. Or add an explicit `javax.ws.rs.WebApplicationException` mapper.

**Comment by geoand** [comment]
I assume this works with RESTEasy Classic?

**Comment by ivansenic** [comment]
> I was not able to reproduce this.
> 
> Do you have a sample application that exhibits this behavior?

Can make it, but earliest tomorrow..

**Comment by geoand** [comment]
Thanks

**Comment by ivansenic** [comment]
Reproducer:

* https://github.com/ivansenic/quarkus-26584
* start the app and issue a `POST` request that does not exists on the `/hello` endpoint 
* returns `500` from the added [exception mapper](https://github.com/ivansenic/quarkus-26584/blob/master/src/main/java/org/acme/RuntimeExceptionMapper.java), instead `405`

```
curl -X POST -v http://localhost:8080/hello

*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by geoand** [comment]
Ah okay. Now I see what you mean. I had understood the issue backwards, sorry.

What you are seeing is standardized JAX-RS behavior, as it allows you to handle exceptions thrown from the framework itself. 
For that reason it is not a good idea to handle all `WebApplicationException` or `RuntimeException` classes. Unfortunately the spec does not give a ton of flexibity when it comes to handling exceptions.

**Comment by geoand** [comment]
It does seem weird, but it is most likely mandated by the spec. 

I tried removing the entity check and about 100 started failing, so there is really not much we can do here.

**Comment by ivansenic** [comment]
OK, thanks. Will use my workaround.
