### ISSUE TITLE
@InjectMock with reactive RestClient breaks the RestClient for subsequent tests

### ISSUE THREAD

**Issue by vonatzigenc** [quarkusio/quarkus#26594]
### Describe the bug

If a RestClient is mocked with `@InjectMock` (from `io.quarkus:quarkus-junit5-mockito`) in a test, the reactive RestClient will not work correctly for subsequent tests without mocks.

However, the error occurs only when `io.quarkus:quarkus-rest-client-reactive-jackson` is used. With the classic RestClient (`io.quarkus:quarkus-rest-client-jackson`), the RestClient is reset as expected after the tests.

### Expected behavior

RestClient from `io.quarkus:quarkus-rest-client-reactive-jackson` can be used in different tests both as a mock and without.
The order in which the tests are run should not matter either.

The behavior should be the same for `io.quarkus:quarkus-rest-client-reactive-jackson` as for `io.quarkus:quarkus-rest-client-jackson`.

### Actual behavior

After the first QuarkusTest, in which a RestClient is mocked with `@io.quarkus.test.junit.mockito.InjectMock`, the RestClient can no longer be used without a mock.
The requests, which are executed over the RestClient, are not executed and an empty response is always returned.

In the tests, which are executed before, the RestClient works as expected.

Subsequent tests, which also use a `@InjectMock` mocked RestClient, also work correctly.

### How to Reproduce?

Reproducer: https://github.com/vonatzigenc/reproducer_quarkus_reactive_restclient_mockito

1. Run ` ./mvnw clean verify`
2. Test `TestWithoutMockAfterUsingInjectMock.testHelloEndpoint` fails

**Description of the tests:**
- Error does not occur when tests are run individually
- Error can also be reproduced directly in IntelliJ. (Run all tests)
- Tests are executed in the following order:
  - `TestWithoutMockBeforeUsingInjectMock`
  - `TestWithInjectMock`
  - `SecondTestWithInjectMock`
  - `TestWithoutMockAfterUsingInjectMock`
- The first and the last test are equal (first works, last one doesn't)
- the second and third test use InjectMock

**"Workarounds"**
- When `io.quarkus:quarkus-rest-client-reactive-jackson` is replaced by `io.quarkus:quarkus-rest-client-jackson` all tests pass
- If the tests are run with `@InjectMocks` with a custom TestProfile, the tests will pass

### Quarkus version or git rev

2.10.2.Final

**Comment by famod** [comment]
I wouldn't be surprised if this is connected to https://github.com/quarkusio/quarkus/pull/26556#issuecomment-1176730396 because that test of mine that breaks subsequent tests is using `@Nested` _and `@InjectMock`!_ (but not `@RestClient`)

**Comment by geoand** [comment]
I'll take a look

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26597 takes care of the issue
