### ISSUE TITLE
Injection point marked with @Autowired(required=false) results in a build error

### ISSUE THREAD

**Issue by masquerade0x1** [quarkusio/quarkus#26591]
### Describe the bug

I have a multi-module application that I am experimenting with to migrate to Quarkus from Spring. I am currently using the quarkus-spring-di API. The utility/library module has an interface for which a bean would be provided by a higher-level consumer package. I currently make use of the Autowired(required=false) to implement this.

I was able to reproduce the issue with a simpler sample project linked below.

While the spring-di API supports the `required` attribute, when an injection point is marked with `@Autowired(required=false)`, it results in a build failure with the following error message:
```
2022-07-06 21:45:25,902 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.Utils and qualifiers [@Default]
```
Since the annotation carries `required=false`, I was expecting that the build would be fine even though the bean is not available at build time for this particular package.

### Expected behavior

I expected the build to succeed as the injection was marked as `required=false`

### Actual behavior

An error was observed indicating `javax.enterprise.inject.UnsatisfiedResolutionException`.

Sample error:
```
2022-07-06 21:45:25,902 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.Utils and qualifiers [@Default]
```

### How to Reproduce?

Simplified example that reproduces the error: https://github.com/masquerade0x1/quarkus-autowired-sample

1. Clone the repo
2. Run `mvn quarkus:dev` inside the directory

### Output of `uname -a` or `ver`

`Linux pc 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### GraalVM version (if different from Java)

Not using GraalVM

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
We don't really support `required=false` on `@Autowired`.

@mkouba I assume there isn't anything analogous in CDI is there?

**Comment by mkouba** [comment]
> I assume there isn't anything analogous in CDI is there?

Nope. You can only inject `javax.enterprise.inject.Instance` and then test `Instance.isResolvable()` if needed.

**Comment by geoand** [comment]
That's what I thought, thanks

**Comment by geoand** [comment]
Closing as `won't fix`
