### ISSUE TITLE
add support for parts with same name in resteasy reactive

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#26600]
### Description

I want to map my request using a multipart/form-data (for file upload), but I also need to support a dynamic amount of input fields.
These could be mapped liked this:

```
public class FormData {
    @RestForm("text")
    public List<String> texts;
}
```

This is however currently not supported by resteasy-reactive.
I get a status code 415 as response.

The request can be send like this:
```
curl -v -F text=abc -F text=efg localhost:8080/hello
```

Resulting in this message body:
```
--------------------------461b0178b64f9d77
Content-Disposition: form-data; name="text"

abc
--------------------------461b0178b64f9d77
Content-Disposition: form-data; name="text"

efg
--------------------------461b0178b64f9d77--
```

### Implementation ideas

#17039 Added support to upload multiple files with the same form name. Maybe this could be extended for other part types?

**Comment by geoand** [comment]
I think this is reasonable.

**Comment by geoand** [comment]
As a workaround for the time being, you can use a Java array... Definitely not ideal, so I'll add List support as well.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26606 takes care of it

**Comment by Postremus** [comment]
yes, thank you. The workaround with array, while not pretty, enables this use case in the mean time.
