### ISSUE TITLE
`QuarkusTestResource` with `restrictToAnnotatedClass` restarts for `@Nested` classes

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#26639]
### Describe the bug

When `QuarkusTestResource` is configured to be `restrictToAnnotatedClass`, it restarts for nested classes annotated with `@Nested`. This is also the case for `QuarkusTestResourceConfigurableLifecycleManager`, which apply `restrictToAnnotatedClass` automatically.

```java
@QuarkusTest
@QuarkusTestResource(value = DummyTestResource.class, restrictToAnnotatedClass = true)
public class DummyNestedTest {

    @InjectDummyString
    String bar;

    @Test
    public void testBar() {
        Assertions.assertEquals("bar", bar); // this assertion works
    }

    @Nested
    class NestedTestClass {

        @Test
        public void testBar() {
            Assertions.assertEquals("bar", bar); // this assertions fails
        }
    }
}
```

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface InjectDummyString {
}
```

```java
public class DummyTestResource implements QuarkusTestResourceLifecycleManager {

    @Override
    public Map<String, String> start() {
        return null;
    }

    @Override
    public void stop() {

    }

    @Override
    public void inject(TestInjector testInjector) {
        testInjector.injectIntoFields("bar", new AnnotatedAndMatchesType(InjectDummyString.class, String.class));
    }
}
```

### Expected behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` should not restart for nested classes annotated with `@Nested`.  
Or, should be capable of injecting fields into the parent class.

### Actual behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` restarts for nested classes and can not inject fields located in the parent class.

### How to Reproduce?

Reproducer: [reproducer.zip](https://github.com/quarkusio/quarkus/files/9079579/reproducer.zip)

How to reproduce: Execute the tests.

The reproducer introduces a `QuarkusTestResourceLifecycleManager` which injects the string "bar" using the `@InjectDummyString` annotation.  
The `DummyNestedTest` shows, that the string is actually `null` in a nested class annotated with `@Nested`. Also you can see, that Quarkus is restarting for the nested class.

### Quarkus version or git rev

2.10.2

**Comment by geoand** [comment]
@Sgitario do you want to take a look at this one?
