### ISSUE TITLE
@Singleton bean with @ServerRequestFilter is removed in @QuarkusTest

### ISSUE THREAD

**Issue by franck102** [quarkusio/quarkus#26635]
### Describe the bug

Starting from a barebone Greeting project:
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.10.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions="resteasy-reactive"
```
I have added a single LoggingFilter bean:
```
@Singleton
public class LoggingFilter {
 
    @ServerRequestFilter(priority = 0)
    public void getFilter(UriInfo info, ...
```
The filter works fine if I start Quarkus in dev mode using the quarkus:dev maven goal:
```
2022-07-10 09:27:58,135 INFO  [com.eas.LoggingFilter] (executor-thread-0) [1] 200 GET /hello "Hello from RESTEasy Reactive"
```
... however the filter is not registered when running QuarkusTest or QuarkusIntegrationTest:
```
@QuarkusTest
public class GreetingResourceTest
```
The test passes but requests/responses are not logged

### Expected behavior

I would expect the LoggingFilter to be registered, and to log requests & responses

### How to Reproduce?

Create Greeting project, add LoggingFilter class, and run GreetingResourceTest

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22 OpenJDK Runtime Environment (build 18.0.1.1+2-6) OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 18.0.1.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.1.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"

**Comment by franck102** [comment]
Adding @Unremoveable to the LoggingFilter bean fixes the issue... is that the correct approach?

After reading [https://quarkus.io/blog/unused-beans/](url) I would assume the the filter should be recognized by the resteasy extension, and not removed?

**Comment by geoand** [comment]
Do you mind sharing a project that exhibits the problem with a failing test?

Thanks

**Comment by franck102** [comment]
I shared the project here:
https://github.com/franck102/quarkus-greeting

Running com.easypass.GreetingResourceTest#testHelloEndpoint generates logs if the @Unremovable annotation is present only.

**Comment by geoand** [comment]
I tried your sample and works flawlessly with or without `@Unremovable`
