### ISSUE TITLE
Add feature to introspect Java class without using Reflection

### ISSUE THREAD

**Issue by rhuan080** [quarkusio/quarkus#26641]
### Description

Looking at the Micronault, I have seen the annotation `@Introspected` (see [here](https://blog.johnowl.com/a-anotacao-introspected-do-micronaut/) ) that permits introspect Java class in Runtime, without using reflection. I searched for a similar feature inside Quarkus and could not find it. 

My request is to include a feature to introspect Java classes without using reflection.

**Comment by geoand** [comment]
What are the use cases for such a feature?

**Comment by geoand** [comment]
Thanks.

I understand how it is used, but I would like to know some actual usages of this - not just theoretically what it can be used for.

Ask because we don't really see many people implementing such dynamic behavior in their applications.

**Comment by rhuan080** [comment]
Hi @geoand, thanks!

In my scenario, I`m starting to use Quarkus in a core of a solution that my end-user are developers. I have custom annotations and we have some decisions according to these annotations. One solution that I have seen is to create my own extension, however, it is just a small part of my application and I think it is a lot to the problem I want to solve now. I think it is a great feature to scenarios in that we want to create a solution for developers. I agree that in general use case it will not be used, but I think it is important in some cases as I described here.

**Comment by geoand** [comment]
Thanks for that information.

As you've probably guessed, my answer is to create a custom extension 🙂.

It should not be that hard (and the Quarkus community is glad to help anyone on their endeavor) and could lead to better performance than the outlined scenario.

**Comment by rhuan080** [comment]
Yes, I know it should not be hard when we think about the complex, however, with this feature I can solve the problem using 3 or 4 lines. Thus, comparing both options, creating a new extension is a lot. 

I really don`t know if it is very used on Micronault, but maybe the Quarkus community can take a look at this and check if it is a feature worthwhile.

**Comment by geoand** [comment]
I personally think that writing an extension is the way to go, but I'd like to hear what @mkouba and @gsmet think as well.

**Comment by mkouba** [comment]
Well, I'm not sure if the the _BeanIntrospection API_ brings any additional value. I mean, if you really need to introspect java classes at runtime then just use the reflection API or build a thin layer on top the reflection API. 

My point is that we would have to persist the introspection data at built time and I doubt that our format would be more efficient than the one used by reflection...

And as Georgios said - the Quarkus way is to write an extension and do the introspection at built time, using the Jandex index.

**Comment by geoand** [comment]
Closing as `won't fix`
