### ISSUE TITLE
LiquibaseMongodbFactory.createLiquibase() check for database name in database connection string is broken

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#26655]
With mongodb connection string as following:
`mongodb+srv://user:password@cluster0.1234.mongodb.net/?retryWrites=true&w=majority`
createLiquibase will fail with 
`IllegalArgumentException: Database not specified in URL`
even if database name is specified. 
Maybe 
`Pattern HAS_DB = Pattern.compile("(mongodb|mongodb\\+srv)://[^/]*/.*");` 
should support connection string with properties in it.

Also if HAS_DB will pass, createLiquibase() method will just concatenate database name to connection string
`connectionString += "/" + this.mongoClientConfig.database....`
which will lead to the same exception as database name is placed after connection properties in db url as following:
`mongodb+srv://user:password@cluster0.1234.mongodb.net/?retryWrites=true&w=majority/databaseName`

Quarkus version 2.10.2

**Comment by loicmathieu** [comment]
Yes, this implementation was a bit naive.
You can send a PR if you're up to or I can try to find some time later to have a look if nobody else can.
