### ISSUE TITLE
Configuration Property in an Injected Bean is null during Startup (observes startupEvent)

### ISSUE THREAD

**Issue by jesuino** [quarkusio/quarkus#2668]
**Describe the bug**

If I use a bean with property prop, which is injected from a configuration file (`@ConfigProperty`) it is null when reading it from a method that observes `StartupEvent`

**Expected behavior**
Attribute should not be null.

**Actual behavior**
Attribute is null.

**To Reproduce**

1.  Class with the property:

~~~
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class Conf {
    
    @Inject
    @ConfigProperty(name = "prop")
    String prop;
    
    public String getProp() {
        return prop;
    }

    @Override
    public String toString() {
        return "Conf [prop=" + prop + "]";
    }
    
}
~~~
2.  Class that reads it:
~~~
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import io.quarkus.runtime.StartupEvent;

public class Startup {
    
    @Inject
    Conf conf;
    
    @Inject
    @ConfigProperty(name = "prop")
    String prop;
    
    public void start(@Observes StartupEvent ev) {
        System.out.println("CONF IS " + conf);
        System.out.println("PROP IS " + conf.prop);
        System.out.println("PROP GETTER IS " + conf.getProp());
        System.out.println("INJECTED PROP IS " + prop);
    } 

}
~~~
3. When reading the property directly it is null (conf.prop). The injected property and the use from a get method works.

Full code is here: https://github.com/jesuino/reproducers/tree/master/quarkus-null-property

**Configuration**
```properties
# Add your application.properties here, if applicable.
prop=test value
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 

~~~
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
~~~
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  0.15

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@dmlloyd @mkouba not sure if it's expected or something we should fix. Could you have a look?

**Comment by mkouba** [comment]
I'm on it.

**Comment by mkouba** [comment]
This issue duplicates https://github.com/quarkusio/quarkus/issues/1632. See [my comment](https://github.com/quarkusio/quarkus/issues/1632#issuecomment-475527981) which explains why the injected field is `null`.

**Comment by jesuino** [comment]
Thank you, sorry I didn't find the original issue.

**Comment by mkouba** [comment]
No problem at all. We should add some FAQ for this particular problem.
