### ISSUE TITLE
@RegisterRestClient annotation not available with Rest Client extensions enabled

### ISSUE THREAD

**Issue by abeosoft** [quarkusio/quarkus#26695]
### Describe the bug

I created a rest client project using the Quarkus Rest Client Reactive Extension. But, the @RegisterRestClient is not available.

### Expected behavior

I expect the @RegisterRestClient to be available after extension is enabled and build is run. I am following this Quarkus Guide: https://quarkus.io/guides/rest-client-reactive

### Actual behavior

I can't find @RegisterRestClient annotation.

### How to Reproduce?

Steps to reproduce the bug:

Create a sample Quarkus project.
Add Rest Client Reactive extensions as shown in this guide.
Open project in an IDE.
The annotation @RegisterRestClient won't be available for import

### Output of `uname -a` or `ver`

Darwmin Mac OS

### Output of `java -version`

11

### GraalVM version (if different from Java)

11

### Quarkus version or git rev

2.10.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

**Comment by geoand** [comment]
The annotations is part of the `org.eclipse.microprofile.rest.client:microprofile-rest-client-api`dependency which **is** included as a transitive dependency when you add `io.quarkus:quarkus-rest-client-reactive`.

`mvn dependency:tree -Dincludes=:microprofile-rest-client-api` gives:

```
[INFO] org.acme:code-with-quarkus:jar:1.0.0-SNAPSHOT
[INFO] \- io.quarkus:quarkus-rest-client-reactive:jar:2.10.2.Final:compile
[INFO]    \- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0:compile
```

I also tried this in the IDE and it worked as expected

**Comment by abeosoft** [comment]
I have tried the build from the command line. It is working without any issues. IntelliJ is complaining about the annotation.

**Comment by geoand** [comment]
That sounds like an IntelliJ issue
