### ISSUE TITLE
Reactive @Transactional-equivalent without Hibernate+Panache

### ISSUE THREAD

**Issue by technical-debt-collector** [quarkusio/quarkus#26705]
### Description

Working with reactive transactions doesn't feel very good right now.
The reactive SQL client offers some intuitive transaction handling (PgPool.withTransaction) but this only feels practical for smaller one-statement-transactions or statements that are closely enough related to justify calling them in the same method. It seems hard to implement proper transaction handling that spans across multiple less related operations without requiring larger refactoring efforts or breaking of code patterns.

It would be great to have an annotation to easily establish transaction boundaries such as JTA's @Transactional.
Spring R2DBC already seems to such an annotation in place from what I can tell (although I haven't really researched too thoroughly around it).
The @ReactiveTransaction annotation makes Hibernate and Panache a lot more tempting to us but we're not interested in converting to Hibernate just for this.

I'm a little bit on the fence on whether or not this request fits better in the Quarkus ecosystem or directly in the [Vert.x SQL client project](https://github.com/eclipse-vertx/vertx-sql-client), I'd be happy to move this request over there if you think that is more appropriate.

**Comment by gavinking** [comment]
> I'm a little bit on the fence on whether or not this request fits better in the Quarkus ecosystem or directly in the [Vert.x SQL client project](https://github.com/eclipse-vertx/vertx-sql-client), I'd be happy to move this request over there if you think that is more appropriate.

I would say it's probably more of an issue for the Vert.x SQL client.

**Comment by geoand** [comment]
I think we already have an issue asking for this, but I can't find it ATM

**Comment by technical-debt-collector** [comment]
Guess there's no need to keep this one open anymore, so I'm closing it.
@gavinking, thanks for great help on this one! 🥇
