### ISSUE TITLE
Gizmo is not considering the type parameters in `DescriptorUtils.typeToString()`

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2671]
Panache is using that to generate the return type of the getters.

Right now, considering a field `List<Dog> dogs`, we end up with the following getter `List getDogs()`.

We only see that now because, before ORM 5.4.3, ORM did not see the getters injected by Panache. It's now the case.

This is blocking for the release as we can't upgrade to ORM 5.4.3, which we want to do in this release.

/cc @FroMage

**Comment by gsmet** [comment]
With this branch https://github.com/quarkusio/quarkus/pull/2672 , if you do:
```
mvn clean install
```
you end up with:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-hibernate-orm-panache: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class io.quarkus.it.panache.Person: Could not locate field -> [Help 1]
```
The issue is caused by the getter generated by Panache losing their potential type parameters (in this case, the `getDogs()` getter has a return type of `List`).

The problem only appears now because, prior to 5.4.3, ORM does not see the getters generated by Panache but this behavior has changed.

You can then reproduce it more easily with:
```
cd integration-tests/hibernate-orm-panache
mvn clean install -DskipTests
```
(the `-DskipTests` is important as when running the tests, there is a weird bug, probably caused by this issue)

Obviously, the goal is to have the tests passing but there might be other unrelated issue so let's start with having the build passing.

**Comment by stuartwdouglas** [comment]
This is actually just that the generic type was not being passed to ASM.

**Comment by FroMage** [comment]
Thanks everyone :)

**Comment by kaqqao** [comment]
@stuartwdouglas How was this addressed exactly (there's no related PR)? I was hoping to see what changed and understand how to use Gizmo to generate a method with a generic return type...

**Comment by stuartwdouglas** [comment]
I think this was actually an issue in how Gizmo was being used from Quarkus, it did not result in any Gizmo changes.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/2672/commits/6fef5e5b78a35e67a73b3efa29c942667d3649e9 was the actual fix for the Quarkus issue.
