### ISSUE TITLE
Resteasy Reactive client not propagating mdc

### ISSUE THREAD

**Issue by RuggeroDAlo** [quarkusio/quarkus#26717]
### Describe the bug

After calling any method of a Resteasy reactive client the reactive MDC is lost.

After adding a key to the jboss MDC (https://github.com/RuggeroDAlo/resteasyreactiveclientpropagation/blob/main/src/main/java/org/acme/Controller.java#L34) it is correctly logged by jboss thanks to the `%X` formatter. 
But the same log called after any method of a resteasy reactive client is called shows an empty MDC.  

Not sure if this is the same issue of https://github.com/quarkusio/quarkus/issues/24318

### Expected behavior

Resteasy reactive clients should propagate MDCs.

In the reporducer after calling the / endpoint the following lines should be logged:
```
{id=1} 1 started
{id=1} 1 End
```

### Actual behavior

Resteasy reactive clients doesn't propagate MDCs.

In the reproducer the following lines are logged:
```
{id=1} 1 started
{} 1 End
```
The `end` log comes after calling a resteasy reactive client.

### How to Reproduce?

1. clone repo https://github.com/RuggeroDAlo/resteasyreactiveclientpropagation
2. Start with ./mvnw quarkus:dev
3. curl localhost:8080 to call endpoint and observe log

### Output of `uname -a` or `ver`

5.15.0-41-generic

### Output of `java -version`

11.0.15

### GraalVM version (if different from Java)

NA

### Quarkus version or git rev

2.11.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by RuggeroDAlo** [comment]
@radcortez I've tried to figure out why this is happening, as far as I can tell PR #26332 changed

https://github.com/quarkusio/quarkus/blob/37a6c9faeba1920a08b0f4527473f69313258235/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java#L59

to

https://github.com/quarkusio/quarkus/blob/ba968f88b0626f51747356ff60360829952ac27f/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientRequestContextImpl.java#L60

So the data saved in the original MDC is not forwarded when calling any resteasy reactive client methods.

I'm not sure if what I'm trying to do is supported. I can't use opentelemetry but I would like to set a key in the MDC and then automatically log it locally by setting `%X{property}` in the log format, without any other tracing information.

**Comment by brunobat** [comment]
This should be a duplicated from [RestClient Reactive, MDC lost](https://github.com/quarkusio/quarkus/issues/24318)
Do you agree @RuggeroDAlo ?

**Comment by RuggeroDAlo** [comment]
@brunobat  I think it is the same issue, I'll close this one

**Comment by RuggeroDAlo** [comment]
@brunobat https://github.com/quarkusio/quarkus/issues/26857 could also be the same?
