### ISSUE TITLE
RolesAllowed always giving 403 Forbidden

### ISSUE THREAD

**Issue by DMaxter** [quarkusio/quarkus#26721]
### Describe the bug

I use an enum for the roles, and when I put the value in `@RolesAllowed`, when a user with the allowed roles tries to make a request, they receive a 403 error. I am using JWT authentication where the roles are one of the fields in the token. Each user can have a set of roles.

### Expected behavior

Execute the request if the role is allowed

### Actual behavior

HTTP 403 error is given

### How to Reproduce?

I am using Kotlin, `security-jpa`, `smallrye-resteasy-reactive` and `hibernate-reactive-panache` packages

For the user, I have the following structure:

```Kotlin
@Entity
@UserDefinition
class User() {
    constructor(name: String, email: String, password: String, roles: MutableSet<Role>) : this() {
        this.name = name
        this.email = email
        this.password = password
        this.roles = roles
    }

    @Id
    @Username
    lateinit var email: String

    @Password
    lateinit var password: String

    lateinit var name: String

    @Roles
    @Enumerated(EnumType.STRING)
    @ElementCollection(targetClass = Role::class, fetch = FetchType.EAGER)
    lateinit var roles: MutableSet<Role>
}
```

The roles are as simple as 
```Kotlin
const val COMMERCIAL_ROLE = "COMMERCIAL"
const val UPLOADER_ROLE = "UPLOADER"
const val MANAGER_ROLE = "MANAGER"
const val ADMIN_ROLE = "ADMIN"

enum class Role(@RolesValue val label: String) {
        COMMERCIAL(COMMERCIAL_ROLE), // Regular user
        UPLOADER(UPLOADER_ROLE),     // Can upload images
        MANAGER(MANAGER_ROLE),       // Can add new users/clients
        ADMIN(ADMIN_ROLE),           // Can attribute roles to users
}
```

Users are created as follows (using the enum):
```Kotlin
User("Admin", ADMIN_NAME, BcryptUtil.bcryptHash(ADMIN_PASS), mutableSetOf(Role.ADMIN))
```

And when protecting an endpoint, I use the string (which is the same as it is saved in the database):
```Kotlin
    @POST
    @RolesAllowed(MANAGER_ROLE, ADMIN_ROLE)
    fun registerClient(client: ClientDto): Uni<Response> {
        return clientService.register(client)
    }
```

In the database, the `User_roles` table has the following:

| User_email | roles |
| ------------ | ------- |
| admin      | ADMIN |

But if I login and try to access this endpoint, it just gives me a 403 error code

The JWT contains the following fields:

```JSON
{
  "iss": "https://localhost:8080",
  "sub": "admin",
  "roles": [
    "ADMIN"
  ],
  "iat": 1657757124,
  "exp": 1657757424,
  "jti": "13bd5ec3-412a-44d3-9151-0f365699ad64"
}
```

### Output of `uname -a` or `ver`

Linux zirconium 5.18.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)

### Quarkus version or git rev

2.10.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 16:40:07 UTC
Revision:     <unknown>

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1.1 (Oracle Corporation 18.0.1.1+2)
OS:           Linux 5.18.9-zen1-1-zen amd64
```

**Comment by geoand** [comment]
Can you attach a sample that reproduces the issue please?

Thanks

**Comment by sberyozkin** [comment]
So @DMaxter, I think we can close this issue, sorry for the confusion of any, not sure what we have missed in the docs, that section looks clear to me. JWT represents a user/client authentication so it does not need some matching endpoint local mapping with the user name and password and roles, it is all in JWT already, so you just need to verify it, with `quarkus-smallrye-jwt` or `quarkus-oidc`

**Comment by DMaxter** [comment]
I forgot to mention, I was already using the JWT package, but this error occurs. Users authenticate using username and password, and if it matches I set a cookie with the JWT token. Authentication works if I use `@Authenticated` but not if I use the `@RolesAllowed`, but what you are saying is that I should drop `security-jpa`? So how is the program supposed to fetch the users from the database automatically?

**Comment by DMaxter** [comment]
> @DMaxter Also, how do you have JWT verified ? You haven't listed `smallrye-jwt` so I'm wondering. In case it is `smallrye-jwt`, it will take the roles from a `groups` claim by default, so in your case you'd need to customize the path to the claim representing the groups, `smallrye.jwt.path.groups=roles` 

I just saw this now, I will try it, thank you

**Comment by sberyozkin** [comment]
@DMaxter In that case, you can simply make sure `groups` is used in a newly created JWT, if you generate tokens with `smallrye-jwt-build` (https://quarkus.io/guides/security-jwt-build) then you can use a typed `groups()` method for it: `Jwt.issuer("http://localhost:8080").subject("admin").groups("ADMIN").sign()` (`issuer` can be configurable too), and you'd not need to customize the path

**Comment by DMaxter** [comment]
Using `smallrye.jwt.path.groups=roles` solved it, thank you

**Comment by sberyozkin** [comment]
@DMaxter no problems, thanks
