### ISSUE TITLE
Better structure for bean dependency graph in dev ui

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#26723]
### Description

My bean dependency graph in dev ui is unreadable:
![image](https://user-images.githubusercontent.com/1223135/178902472-dc303c15-ec29-45a9-9a93-41794db34a9c.png)

Any chances to get this a bit better structured / readable at all for my app?

Some ideas:
* Allowing to scrool and zoom. Idealy none of the bean names would be cut off at the end of the screen
* Shorten package names, like it is already done for the build steps graph
* Make lines of the arrows a bit narrower, so they take up less space
* decrease font size of the bean names a bit

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
Hm, we could use some of the ideas but I doubt it would help a lot with a very complex dependency graph (like yours ;-). What we could do is to make the number of visible levels configurable, i.e. only show the direct dependencies/dependents by default.

**Comment by maxandersen** [comment]
How big is this app really? curious to know at what point things get this "messy" :)

Agree fully on the suggestions (especially on shorten package names) + need for zoom.

@mkouba a "depth gauge" would be interesting. In other similar visualizations I've seen that adding the ability to pick a "focus" node to then use that to highlight  from helps.

Other is a way to filter based on name.

Other is allowing selecting different graph layouts. remind me which library we use for it ? d3?

**Comment by Postremus** [comment]
@maxandersen 
The app is now in development (and production use) since a few years, started originally on wildfly 8.

![image](https://user-images.githubusercontent.com/1223135/184585152-dd0e8e88-611b-4356-a994-f74b94e5d1e9.png)

**Comment by mkouba** [comment]
> How big is this app really? curious to know at what point things get this "messy" :)
>> The app is now in development (and production use) since a few years, started originally on wildfly 8.

Oh, 677 beans and 130 entities :D 

> Other is allowing selecting different graph layouts. remind me which library we use for it ? d3?

Yes, we use [d3js](https://d3js.org/).

I will try to apply some of the suggestions but I'm no UI/d3js expert sooo...

@Postremus do you use some custom CSS for the Dev UI console? I mean it looks like some dark theme...

**Comment by Postremus** [comment]
@mkouba oh, sorry, did not notice dark mode.

I use the dark reader plugin for google chrome, which allows me to view any website in dark mode.
Afaik this only changes colors, and no other stylings.
