### ISSUE TITLE
Allow AuthorizationControllers to access request for their decision

### ISSUE THREAD

**Issue by jcunliffe1** [quarkusio/quarkus#26724]
### Description

We have a use case, where we would like the activation of authorization to depend on the domain, under which the server was accessed. For this, the AuthorizationController needs access to the request, which I can't get injected.

Any help is appreciated, but also we should maybe put the request into the parameters for io.quarkus.security.spi.runtime.AuthorizationController#isAuthorizationEnabled

**Comment by geoand** [comment]
What aspects of the request do you need?

Also, what HTTP stack are you using?

**Comment by jcunliffe1** [comment]
classic resteasy now, reactive in a few years hopefully. at the moment, all I need is the HttpServerRequest. maybe we can change io.quarkus.vertx.http.runtime.security.HttpAuthorizer#checkPermission
to

``` 
    public void checkPermission(RoutingContext routingContext) {
        if (!this.controller.isAuthorizationEnabled(**routingContext.request()**)) {
            routingContext.next();
        } else {
            this.doPermissionCheck(routingContext, QuarkusHttpUser.getSecurityIdentity(routingContext, this.identityProviderManager), 0, (SecurityIdentity)null, this.policies);
        }
    }
```

and 
```
public class AuthorizationController {
    public AuthorizationController() {
    }

    public boolean isAuthorizationEnabled() {
        return true;
    }

    public boolean isAuthorizationEnabled(HttpServerRequest request) {
        return isAuthorizationEnabled();
    }
}
```

Or something similar? This will allow me to base the decision wether authorization gets enabled or not on the content of the current request, including the request URL that I need.

**Comment by jcunliffe1** [comment]
If you are happy with this quick fix, I'm happy to send a PR. For more sophisticated changes, I probably lack the background.

**Comment by geoand** [comment]
To be honest, I don't think we should change the signature.
But you can however in your own bean just inject the `CurrentVertxRequest currentVertxRequest` bean and do whatever you like with it :)

**Comment by sberyozkin** [comment]
@jcunliffe1 You may need to add `@ActivateRequestContext` to have the injection working if it does not work right now

**Comment by jcunliffe1** [comment]
> To be honest, I don't think we should change the signature as that would tie it to a specific request stack.
> 
> But you can however in your own bean just inject the `CurrentVertxRequest currentVertxRequest` bean and do whatever you like with it :)

I tried it, but this doesn't work - nor does injecting the other various HttpRequest beans.

**Comment by jcunliffe1** [comment]
> @jcunliffe1 You may need to add `@ActivateRequestContext` to have the injection working if it does not work right now

I tried it on 

```
	@ActivateRequestContext
	public boolean isAuthorizationEnabled() { ...
```

doesn't work. have now tried it also on the bean

```
@RequestScoped
@ActivateRequestContext
public class RequestResolver {

	@Inject
	CurrentVertxRequest currentVertxRequest;
...
```
Also doesn't work:

![image](https://user-images.githubusercontent.com/97282647/178983002-c035d504-cb96-4904-9944-eef6e8b2cfd0.png)

**Comment by jcunliffe1** [comment]
> Define `doesn't work` please
```
final Instance<HttpServerRequest> select = CDI
			.current()
			.select(HttpServerRequest.class);
		HttpServerRequest HSR = select.isResolvable() ? select.get() : null;
		final Instance<javax.servlet.http.HttpServletRequest> select2 = CDI
			.current()
			.select(javax.servlet.http.HttpServletRequest.class);
		javax.servlet.http.HttpServletRequest HSR2 = select2.isResolvable() ? select2.get() : null;
		final Instance<org.jboss.resteasy.spi.HttpRequest> select3 = CDI
				.current()
				.select(org.jboss.resteasy.spi.HttpRequest.class);
		org.jboss.resteasy.spi.HttpRequest HSR3 = select3.isResolvable()
				? select3.get()
				: null;
		final Instance<javax.ws.rs.core.Request> select4 = CDI
				.current()
				.select(javax.ws.rs.core.Request.class);
		javax.ws.rs.core.Request HSR4 = select4.isResolvable()
				? select4.get()
				: null;
		final Instance<io.vertx.core.spi.observability.HttpRequest> select5 = CDI
				.current()
				.select(io.vertx.core.spi.observability.HttpRequest.class);
		io.vertx.core.spi.observability.HttpRequest HSR5 = select5.isResolvable()
				? select5.get()
				: null;
```
All of those are null inside io.quarkus.security.spi.runtime.AuthorizationController#isAuthorizationEnabled

**Comment by jcunliffe1** [comment]
no, there is. it's just not visible here.

**Comment by jcunliffe1** [comment]
this debug point was breaking after I hit the quarkus application via a browser request.

**Comment by jcunliffe1** [comment]
Will produce one. I forgot to mention that we are still using quarkus-undertow for servlet filtering and csp strict dynamic rewriting.

**Comment by jcunliffe1** [comment]
https://github.com/jcunliffe1/quarkus-bug-authorisation-race-condition

please start in debug mode, set breakpoint on `org.acme.CustomAuthorizationController#isAuthorizationEnabled`

and send a request against http://localhost:8080/hello

please let me know if you find any way of retreiving the request url at that point.

**Comment by jcunliffe1** [comment]
removing undertow doesn't help:

![image](https://user-images.githubusercontent.com/97282647/179007620-dfb4f40a-3cbc-431f-a759-03c24eda3a82.png)

**Comment by jcunliffe1** [comment]
@sberyozkin any ideas?
@geoand why is this closed?

**Comment by geoand** [comment]
I'll have a look the next few days

**Comment by jcunliffe1** [comment]
Sure. Please let me know if this will take longer. There are 30 developers and some very emotional managers waiting for this to work for their respective test environments.

**Comment by geoand** [comment]
I don't think it will take longer

**Comment by geoand** [comment]
I would like to limit things as much as possible, so what info from `request` do you need?

**Comment by sberyozkin** [comment]
@geoand We pass `RoutingContext` to `HttpAuthenticationMechanism`, which and also indirectly to `IdentityProvider`, so IMHO it is better to keep `RoutingContext`

**Comment by sberyozkin** [comment]
We even support injecting it the application code

**Comment by sberyozkin** [comment]
Actually, thinking more about it, I wonder if we should avoid passing `HTTP` related info at all, as `AuthorizationController` can be used I guess with GRPC as well. I think this is why Stuart may have decided to avoid passing it to `IdentityProvider` and `AuthorizationController`.

@jcunliffe1 What happens if you add `@ActivateRequestContext` to your bean, can you have `@RoutingContext` injected ?

**Comment by geoand** [comment]
@sberyozkin there is no way to get the HTTP request from CDI at that point, we need to pass down information.

We should find the minimum set of info

**Comment by sberyozkin** [comment]
@geoand 

>We should find the minimum set of info

Not sure about it, `RoutingContext` is available to users everywhere in Quarkus, and it is not really possible to determine what the minimum amount of information is based on this issue alone. It would be inconsistent IMHO with the fact RoutingContext is visible across a lot of Quarkus anyway

**Comment by geoand** [comment]
But like you said, would that work in grpc?
If so, then okay

**Comment by sberyozkin** [comment]
I'm contradicting myself, thanks for gently pointing it out :-), I thought you were referring to HTTP specific fragments from RoutingContext, sorry about that. Yeah. I don't know. If the injection were working then it would've been simplest.

So may we should have `AuthorizationContext` bean passed around and it would include some info like the request address and Map of name/value pairs which can be be headers for ex in case of HTTP ?

**Comment by jcunliffe1** [comment]
> I would like to limit things as much as possible, so what info from `request` do you need?

in my case just the domain name, under which the ip and istio route was resolved.

**Comment by jcunliffe1** [comment]
I'm a little surprised about your reluctancy to pass down the routing context, but at the same time suggesting to access it via injection. If io.quarkus.vertx.http.runtime.CurrentVertxRequest#setCurrent(io.vertx.ext.web.RoutingContext, java.lang.Object) is accesible from io.quarkus.vertx.http.runtime.security.HttpAuthorizer#checkPermission, then you can also set the routingContext there, to fix the broken injection in the AuthorizationController.

**Comment by sberyozkin** [comment]
@jcunliffe1 

> I'm a little surprised about your reluctancy to pass down the routing context

The problem is not all Quarkus Services are Verx-HTTP aware services. 

> But at the same time suggesting to access it via injection

This could give an option those Vertx HTTP aware services which need it to access it

> If io.quarkus.vertx.http.runtime.CurrentVertxRequest#setCurrent(io.vertx.ext.web.RoutingContext, java.lang.Object) is accesible from io.quarkus.vertx.http.runtime.security.HttpAuthorizer#checkPermission, then you can also set the routingContext there, to fix the broken injection in the AuthorizationController.

I'd not go as far as saying it is `broken` as it may have been done by design for the reasons outlined above.
This sounds like though it might fix it, would you like to experiment ? We may agree with Georgios on the alternative solution but of this one you propose works then it could definitely be an option to consider

Thanks

**Comment by geoand** [comment]
> So may we should have `AuthorizationContext` bean passed around and it would include some info like the request address and Map of name/value pairs which can be be headers for ex in case of HTTP ?

Yeah, I think that makes sense

**Comment by sberyozkin** [comment]
I can have a look later, perhaps it can be even simplified to pass a request address plus a Map of attribute objects, where one of the attributes is `RoutingContext`, which we don't even have to set yet to support the current case since the domain name will be in the request address String.
All Quarkus `HttpAuthenticationMechanism` use a similar approach for indirectly passing `RoutingContext` to `IdentityProvider`s, it may be simpler as copying the headers esp the multi valued ones can be messy. And then someone will ask, we need to check cookies :-).
It will be a breaking change though to change the signature...

**Comment by geoand** [comment]
> It will be a breaking change though to change the signature...

We can make it work by making a new method that will be a default method calling the existing one, no?

**Comment by sberyozkin** [comment]
Or yeah, of course, this idea is even shown in the code example above :-). Several OIDC interfaces have been updated this way...

**Comment by geoand** [comment]
👍🏼

**Comment by sberyozkin** [comment]
I've prototyped some code, https://github.com/sberyozkin/quarkus/pull/new/authorization_controller_context, however, while `HttpAuthorizer` can create it as it has an access to `RoutingContext`, many interceptors such as `EagerSecurityCheck` which check `authorizationController.isAuthorizationEnabled()` don't have access to `RoutingContext` so I'm not sure if this option works...

**Comment by geoand** [comment]
I'm on sick leave until further notice, so I can't help out on this for a while

**Comment by jcunliffe1** [comment]
hope you get better soon @geoand.

**Comment by geoand** [comment]
Thanks!

@sberyozkin mind opening a draft PR with your prototype so we can work from there?

**Comment by ambition-consulting** [comment]
@geoand - since we are not making progress here, and I urgently need this, I have created a PR following my original idea, which is guaranteed to be downwards compatible. Can somebody please review and comment how to proceed - or merge?

**Comment by ambition-consulting** [comment]
The solution in https://github.com/quarkusio/quarkus/pull/29071?notification_referrer_id=NT_kwDOAEBd3rI0NzU4ODIyODYxOjQyMTgzMzQ#issuecomment-1304115821 helps me with this specific requirement. I believe this ticket can be closed.
