### ISSUE TITLE
Support Federation in Quarkus GraphQL

### ISSUE THREAD

**Issue by oo00spy00oo** [quarkusio/quarkus#26722]
### Description

Supporting GraphQL federation with:
- Apollo Federation: https://www.apollographql.com/docs/federation
- GraphQL Hive: https://graphql-hive.com/

### Implementation ideas

- The same idea with Apollo Federation on the JVM: https://github.com/apollographql/federation-jvm
- Integrating with DGS framework with federation supported: https://netflix.github.io/dgs/federation/

**Comment by phillip-kruger** [comment]
This is already planned in SmallRye here: https://github.com/smallrye/smallrye-graphql/issues/521. Closing this one.
