### ISSUE TITLE
Expose `getIfPresent` in the `CaffeineCache`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#26730]
### Description

Expose the `com.github.benmanes.caffeine.cache.AsyncCache#getIfPresent` function in the `io.quarkus.cache.CaffeineCache`. Currently, there is no way to get the value from the cache, without the loader.

### Implementation ideas

Would implement it as:

```
public <K, V> Uni<V> getIfPresent(K key);
```

The Uni can emit `null` item in case the key is not in cache. The processing could be very similar to the current `io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl#get`, just without the value loader.

I am willing to contribute this.

**Comment by geoand** [comment]
Seems useful to me, WDYT @gwenneg ?

**Comment by gwenneg** [comment]
Yes, that would be an interesting addition to `io.quarkus.cache.CaffeineCache`.

**Comment by ivansenic** [comment]
Will tackle this next week then..

**Comment by ivansenic** [comment]
Implementing the improvement in the #26863
