### ISSUE TITLE
@TestSecurity ans Principal injection

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#26765]
### Describe the bug

```java
import io.quarkus.arc.Arc;
import io.quarkus.security.identity.SecurityIdentity;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.security.TestSecurity;
import org.junit.jupiter.api.Test;

import java.security.Principal;

import static org.assertj.core.api.Assertions.assertThat;

@QuarkusTest
class AuthTest {

    @Test
    @TestSecurity(user = "admin")
    void workingTest() {
        Principal principal = Arc.container().select(SecurityIdentity.class).get().getPrincipal();
        assertThat(principal.getName()).isEqualTo("admin");
    }

    @Test
    @TestSecurity(user = "admin")
    void failingTest() {
        Principal principal = Arc.container().select(Principal.class).get();
        assertThat(principal.getName()).isEqualTo("admin"); // it is actually empty string
    }
}
```

I'm using ```@TestSecurity``` annotation to mock current user.
It works when in production code I'm using SecurityIdentity to get principal, but it is not working when I'm injecting Principal directly. 

I think it is a bug and behaviour should be consistent in both cases.

**Comment by sberyozkin** [comment]
@kucharzyk if you use `smallrye-jwt` or `quarkus-oidc` `service` apps then check https://quarkus.io/guides/security-jwt#integration-testing-security-annotation or https://quarkus.io/guides/security-openid-connect#integration-testing-security-annotation.
The base `TestSecurity` module does not provide a `Principal` producer

**Comment by kucharzyk** [comment]
Thanks @sberyozkin 

I’m using ```quarkus-test-security-jwt``` and no principal (mocked) is provided. Shouldn’t  ```JsonWebToken``` be returned as a  ```Princial ``` in this case?

**Comment by sberyozkin** [comment]
@kucharzyk np, the example in the linked doc uses `@JwtSecurity`, `quarkus-test-security-jwt` code which creates `JsonWebToken`is activated by this annotation. It can't do it with `@TestSecurity` alone.
IMHO, when working with JWT, it can be easier in inject `JsonWebToken`.

**Comment by kucharzyk** [comment]
Most of the time its easier to use JsonWebToken but sometimes when you need only principal name it easier to use Principal.
For me it's very confusing that you can get different ```Principal``` in test by injecting ```Principal``` and different using ```SecurityIdentity.getPrincipal()```.

**Comment by sberyozkin** [comment]
@kucharzyk 

>For me it's very confusing that you can get different Principal in test by injecting Principal and different using SecurityIdentity.getPrincipal()

Can you clarify please as with `@JwtSecurity` it will be the same instance ?
As I said, `@TestSecurity` does not have a `Principal` producer as it will be causing its own confusion if it is combined with the extensions which have `Principal` produced

**Comment by kucharzyk** [comment]
@sberyozkin 

For me it's not working even with ```@JwtSecurity```.

Consider the following test

```java
import io.quarkus.arc.Arc;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.security.TestSecurity;
import io.quarkus.test.security.jwt.Claim;
import io.quarkus.test.security.jwt.JwtSecurity;
import org.junit.jupiter.api.Test;

import java.security.Principal;

import static org.assertj.core.api.Assertions.assertThat;

@QuarkusTest
class AuthTest {

    @Test
    @TestSecurity(user = "admin")
    @JwtSecurity(claims = {@Claim(key = "upn", value = "other")})
    void successfulTest() {
        Principal principal = Arc.container().select(Principal.class).get();
        assertThat(principal.getName()).isEqualTo("");
    }

}
```

I'm trying to set user but injected ```Principal``` is still empty.

Should I stick to using ```SecurityIdentity``` instead of ```Principal```?

**Comment by kucharzyk** [comment]
Silly mistake. ```quarkus-smallrye-jwt``` was missing in my classpath.
I've thought that  ```quarkus-test-security``` and ```quarkus-test-security-jwt``` will include everything I need.
I have multi-module application and my module contained only ```quarkus-test-security-jwt```.

With ```quarkus-smallrye-jwt``` on classpath the following test is passing even without ```@JwtSecurity```

```java
import io.quarkus.arc.Arc;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.security.TestSecurity;
import org.junit.jupiter.api.Test;

import java.security.Principal;

import static org.assertj.core.api.Assertions.assertThat;

@QuarkusTest
class AuthTest {

    @Test
    @TestSecurity(user = "admin")
    void successfulTest() {
        Principal principal = Arc.container().select(Principal.class).get();
        assertThat(principal.getName()).isEqualTo("admin");
    }

}
```

```quarkus-smallrye-jwt```  contains ```JwtPrincipalProducer``` that is producing valid ```Principal``` object.
