### ISSUE TITLE
NoSuchMethodException in Resteasy-reactive when running in native mode (RestResponse<InputStream>)

### ISSUE THREAD

**Issue by manusa** [quarkusio/quarkus#26780]
### Describe the bug

I'm facing a similar issue to the one described in #25973 fixed by #26021.

In my case the method signature and annotations look like:
```java
  @GET
  @Path("/{fileName:.+}")
  public RestResponse<InputStream> getStaticFile(@PathParam("fileName") String fileName) throws IOException {
```

Maybe accounting for RestResponse/InputStream in [`ResteasyReactiveProcessor`](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveProcessor.java) might fix it :shrug:.

I can workaround this issue by annotation the affected class with `@RegisterForReflection`

### Expected behavior

No exception should be thrown, method should pipe an input stream to the response.

### Actual behavior

Fails with:
```
2022-07-18 11:59:15,376 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.example.fullstack.GatewayResource.getFrontendStaticFile(java.lang.String)

```

### How to Reproduce?

https://github.com/marcnuri-demo/202207-quarkus-26780

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)

### GraalVM version (if different from Java)

- quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
- quay.io/quarkus/ubi-quarkus-mandrel:22.1-java17

### Quarkus version or git rev

<=2.10.2.Final

**Comment by mihaipoenaru** [comment]
@manusa does it still happen with ubi-quarkus-mandrel:22.1-java17 ? I had similar issues with reflection, but it was solved when I bumped the mandrel version

**Comment by manusa** [comment]
> @manusa does it still happen with ubi-quarkus-mandrel:22.1-java17 ? I had similar issues with reflection, but it was solved when I bumped the mandrel version

Let me try it

**Comment by manusa** [comment]
> > @manusa does it still happen with ubi-quarkus-mandrel:22.1-java17 ? I had similar issues with reflection, but it was solved when I bumped the mandrel version
> 
> Let me try it

No luck, same result. I'm inclined to think that this should be fixed at the deployment processor level.

**Comment by gsmet** [comment]
I'm surprised @GET is not sufficient to trigger the registration. Could you create a small reproducer?

**Comment by manusa** [comment]
> I'm surprised @get is not sufficient to trigger the registration. Could you create a small reproducer?

:+1: I'll try to create one tomorrow and update the description.

**Comment by manusa** [comment]
I created a reproducer project https://github.com/marcnuri-demo/202207-quarkus-26780

The project [README.md](https://github.com/marcnuri-demo/202207-quarkus-26780/blob/main/README.md) contains the necessary steps to reproduce the issue.

**Comment by gsmet** [comment]
@geoand I'm not exactly sure how you're supposed to register the methods in RESTEasy Reactive so I'll let you have a look when you're back from sick leave.

**Comment by geoand** [comment]
They are not automatically registered for reflection, it only happens under certain conditions.

I'll add this to my increasing list of things to do when I get back

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26923 fixes the issue

**Comment by manusa** [comment]
> #26923 fixes the issue

Awesome, thx :raised_hands:

**Comment by geoand** [comment]
🙏🏼
