### ISSUE TITLE
Add a config converter for enums

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2678]
**Description**
Add a converter for enums that would translate between the idiomatic Java enum syntax and the idiomatic skewered-lowercase syntax of configuration.  For example:

Java enum constant name | Canonical equivalent
---------- | --------
`DISCARD` | `discard`
`READ_UNCOMMITTED` | `read-uncommitted`
`SIGUSR1` | `sigusr1`
`TrendBreaker` | `trend-breaker`
`MAKING_LifeDifficult` | `making-life-difficult`
`YeOldeJBoss` | `ye-olde-jboss`

Hyphens and underscores would be interchangeable on input.  Values would be case-insensitive.  Note the special exception `JBoss` is always treated as a whole word (see `io.quarkus.deployment.util.StringUtil`).

**Comment by machi1990** [comment]
Hi @dmlloyd 
I was giving this a thought and I have got a question regarding the conversion.
What happens when converting the following values:
-  `makingLifeDifficult`: is it `making-life-difficult`?
-  `READ__UNCOMMITTED`: is it `read-committed` or `read--committed`?

**Comment by dmlloyd** [comment]
I would say:

* `makingLifeDifficult` would be `making-life-difficult` as you say
* `READ__UNCOMMITTED` could go either way (whichever way is easier to specify): such a constant is so poorly named that it probably should be changed. :)

**Comment by machi1990** [comment]
@dmlloyd thanks for the clarifications.

So I have given this a thought and gave it a go [here](https://github.com/quarkusio/quarkus/compare/master...machi1990:2678?expand=1)

- Some enums are not / need not to be in skewCase e.g `Protocol` cf `ServerSslConfig.java`, I thought of adding an option `skewCase` for `@ConfigItem` to opt out the conversion.
- Some modifications had to be done for `ObjectConfigType` `OptionalObjectConfigType ` and `ObjectListConfigType ` as I could not find a way to make it by implementing a MP Config  `Converter`. Did you have something similar in mind? Or is there a way to make it simple?

**Comment by dmlloyd** [comment]
> @dmlloyd thanks for the clarifications.
> 
> So I have given this a thought and gave it a go [here](https://github.com/quarkusio/quarkus/compare/master...machi1990:2678?expand=1)
> 
> * Some enums are not / need not to be in skewCase e.g `Protocol` cf `ServerSslConfig.java`, I thought of adding an option `skewCase` for `@ConfigItem` to opt out the conversion.

You're right, we do need a way to opt out.  Maybe `hyphenate-values` is a better name?  But it only applies to `enum` properties, so maybe a separate `@Hyphenate(false)` is better.  We could give an error if the `@Hyphenate` annotation is given on non-enum properties.

> * Some modifications had to be done for `ObjectConfigType` `OptionalObjectConfigType ` and `ObjectListConfigType ` as I could not find a way to make it by implementing a MP Config  `Converter`. Did you have something similar in mind? Or is there a way to make it simple?

I think your approach is correct, generally speaking.

**Comment by machi1990** [comment]
> You're right, we do need a way to opt out. Maybe `hyphenate-values` is a better name? But it only applies to `enum` properties, so maybe a separate `@Hyphenate(false)` is better. We could give an error if the `@Hyphenate` annotation is given on non-enum properties.
> 

Re: `skewCase` I was not sure about the naming either so I decided to went to the very end of my approach. Finally, I like what you propose better regarding an `@Hypenate` annotation.  
I will go along that line and allow opting in for hypnated-values by `@Hyphenate(true)`. The default value is `false`. 


> > * Some modifications had to be done for `ObjectConfigType` `OptionalObjectConfigType ` and `ObjectListConfigType ` as I could not find a way to make it by implementing a MP Config  `Converter`. Did you have something similar in mind? Or is there a way to make it simple?
> 
> I think your approach is correct, generally speaking.

Okay, let me prepare a commit and open a draft PR so that we can continue with the discussion there.
