### ISSUE TITLE
Ability to Configure Update Behavior for Kubernetes/OpenShift Resources

### ISSUE THREAD

**Issue by nexus-Six** [quarkusio/quarkus#26789]
### Description

The current implementation of the Kubernetes/OpenShift extensions use **createOrReplace** to apply the resources generated in target/kubernetes/openshift.yml to OpenShift. This leads to the replacement of all these Openshift resources on every redeploy, including the **ServiceAccount**. This new ServiceAccount in turn triggers the creation of three Openshift **Secrets**. Over time, this leads to a vast amount of stale **Secrets** in the namespace.

There should be a way to control this update behavior such as choosing between **Replace** (`oc replace ...`) and **Update** (`oc apply ...`).

**Reproducer:**
- Clone https://github.com/codingFonnegra/getting-started
-` oc login` and create an OCP project
- In  /getting-started execute multiple times : `mvn package -Dquarkus.kubernetes.deploy=true -Dquarkus.profile=kube -DskipTests -Dquarkus.openshift.route.expose=true`
- You can see how 3 new Secrets are created on every deploy
  
 

### Implementation ideas

Perhaps a new configuration such as

`quarkus.openshift.resources.creation-strategy=replace|update`

could be a solution

**Comment by geoand** [comment]
Also cc @manusa

**Comment by manusa** [comment]
We do have a flag like this on JKube.

> Perhaps a new configuration such as
> 
> `quarkus.openshift.resources.creation-strategy=replace|update`

I like this idea, having a well set defined creation/deployment strategies and then performing the appropriate operation in the deployment phase sound like a great solution and would add flexibility for the users.

There's now the option to perform [server-side apply](https://github.com/fabric8io/kubernetes-client/blob/211095c1d9446475cba451092fe4ebdf0c7e6b62/doc/CHEATSHEET.md#server-side-apply) replacements too (#3334).

- `create`: Create only -> fails if resource exists ?
- `replace`: Delete and then create
- `server-side-apply`
- ...

**Comment by geoand** [comment]
@nexus-Six would the proposal from @manusa work for you?

**Comment by nexus-Six** [comment]
Yes, this looks like good solution

Am 26. Juli 2022 06:57:30 UTC schrieb Georgios Andrianakis ***@***.***>:
***@***.*** would the proposal from @manusa work for you?

**Comment by geoand** [comment]
Was closed due to my erroneous linkage to a PR
