### ISSUE TITLE
Support acr_values in quarkus-oidc extension

### ISSUE THREAD

**Issue by DCCSKrezovic** [quarkusio/quarkus#26793]
### Description

We use acr_values to request multi-factor authentication from our provider and have to send the claim to the authorization endpoint as a query param. There seems to be no way to add additional query< parameters to the call to the openid authorization URL.

Please add support to either hardcode an acr_value read from configuration, or add any arbitrary request parameters sent to the authorization code flow endpoint.

See also: https://openid.net/specs/openid-connect-eap-acr-values-1_0.html

**Comment by sberyozkin** [comment]
Closing it as adding additional query parameters to the authorization endpoint URL is already supported and tested.
@DCCSKrezovic Please reopen if you find any problems related to passing `acr_values`

**Comment by DCCSKrezovic** [comment]
@sberyozkin  Thank you for the hint. I must have gone 3 times through the whole params list and I did not notice it.

**Comment by sberyozkin** [comment]
@DCCSKrezovic Sorry about it, I see them being generated without being grouped together; you can ping us on `Discussions` as well or on Zulip
