### ISSUE TITLE
Jackson property extension accept-case-insensitive-enums doesn't work

### ISSUE THREAD

**Issue by MarcAntoine-Beauvais** [quarkusio/quarkus#26798]
### Describe the bug

When using property
quarkus.jackson.accept-case-insensitive-enums=true

It should ignore case during Enum deserialization but it doesn't.

### Expected behavior

It should ignore case during Enum deserialization.

### Actual behavior

404 Not Found when trying to pass enum not matching the case

### How to Reproduce?

![image](https://user-images.githubusercontent.com/463919/179580630-5752cb9e-9247-4f6b-a0f0-1c23f69e7e34.png)

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### GraalVM version (if different from Java)

22.1.0.r17-grl

### Quarkus version or git rev

2.10.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
Please attach a sample project that exhibits the problem.

**Comment by geoand** [comment]
Closing as we never got a reproducer
