### ISSUE TITLE
OpenTelemetry: Can't get trace/parent/span Ids in Quarkus logs

### ISSUE THREAD

**Issue by NMichas** [quarkusio/quarkus#26804]
### Describe the bug

I'm following the example in https://quarkus.io/guides/opentelemetry to configure OpenTelemetry in my Quarkus service. The integration works fine and I can see the spans in Jaeger UI.

However, Quarkus logs don't include information on the tracing context, i.e.
```
 09:53:37 INFO  traceId=, parentId=, spanId=, sampled= [or.ac.HelloWorld] (executor-thread-0) Hello world executed.
```

Is there some configuration I might be missing? I've made a tiny project below if you want to see this in action.

### Expected behavior

Logs populated with tracing context info.

### Actual behavior

Logs not populated with tracing context info:
```
 09:53:37 INFO  traceId=, parentId=, spanId=, sampled= [or.ac.HelloWorld] (executor-thread-0) Hello world executed.
```

### How to Reproduce?

See the project in:
https://github.com/NMichas/quarkus-opentelemetry

**Comment by tellisnz-shift** [comment]
I upgraded to 2.11.0.CR1 and I can see them, I think it's this fix: https://github.com/quarkusio/quarkus/issues/26258

Although in dev mode a live reload will cause them to be 000000 all the time

**Comment by NMichas** [comment]
Thanks, 2.11.0.CR1 fixes it, closing this one in favour of #26258.

**Comment by famod** [comment]
> Although in dev mode a live reload (i.e.. hit `s`) will cause OTEL to stop exporting and them to be `traceId: '00000000000000000000000000000000' parentId: '' spanId: '0000000000000000' sampled: 'false'` and a rerun of tests (i.e. hit `r`) will cause OTEL to stop exporting and them to be `traceId: '' parentId: '' spanId: '' sampled: ''`
> 
> Need to fully restart `quarkus dev` to get them back.

FWIW, I have created #29645 for that specific problem.

**Comment by einarjohnson** [comment]
Hi. I am facing this same problem when using the quarkus-opentelemetry extension with alongside the quarkus-amazon-lambda extension. When I send a POST request to my local development endpoint on http://localhost:8080/2015-03-31/functions/function/invocations all the trace id's are logged as empty
image

I am using the latest 2.16.1.Final version of Quarkus. Is this normal behaviour when I am in dev mode? I wonder if I am missing some configuration detail or a dependency here?
