### ISSUE TITLE
GitHub Action CI failing on Windows when the filename is "long"

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#26807]
Windows 😫 
```
  Error: error: unable to create file independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/extension-codestart/java/runtime/src/main/codestarts/quarkus/{extension.id}-codestart/base/src/main/resources/META-INF/resources/index.entry.qute.html: Filename too long
```
This path is not that long, I don't see any simple workaround.

Should we enable longpath for Windows in the CI? 
https://github.community/t/filename-too-long-error-for-windows-2019-checkout/16676

_Originally posted by @ia3andy in https://github.com/quarkusio/quarkus/issues/26806#issuecomment-1188775116_

**Comment by ia3andy** [comment]
cc @gsmet @famod

**Comment by ia3andy** [comment]
I'll add a commit with the change on my codestart PR and we may decide

**Comment by gsmet** [comment]
I don't have any objections but I don't really know what it does :).

**Comment by famod** [comment]
This setting seems to have some potential side effects: https://stackoverflow.com/a/22575737/9529981

But if it doesn't reduce stability, I'm all for it.
