### ISSUE TITLE
Prefix kafka consumer client.id with quarkus.application.name

### ISSUE THREAD

**Issue by mrickly** [quarkusio/quarkus#26809]
### Description

- The auto-configuration of the client.id is described here: https://quarkus.io/guides/kafka#incoming-channel-configuration-polling-from-kafka
- The client.id is displayed for instance in the Clients dashboard of https://confluent.cloud/ 
- In order to distinguish the clients, we would have to prefix every channel with the quarkus.application.name
- It seems simpler to let quarkus prefix the client.id with the quarkus.application.name (and it would be consistent with the auto-configuration of the group.id).

**Comment by cescoffier** [comment]
Can't you set the client id explicitly in your application using ${quarkus.application.name}-your-id?

I'm not against that change, but it's a breaking change. So, we need to have an attribute to change the behavior (which would be another attribute, that's why my initial proposal could work as it is.)

**Comment by mrickly** [comment]
Sure we could. I'd rather not force every developing team to configure it explicitly for each incoming channel in their application though. We do pre-configure certain properties in our own extensions (quarkus-extension.yaml). However I don't see how that would work with variable channels... Maybe you have an idea how it could be done?

**Comment by cescoffier** [comment]
I like your proposal. We could define a global prefix attribute, and if the prefix is configured, it will be prepended. 

@ozangunalp WDYT?

**Comment by ozangunalp** [comment]
This needs to be done in Smallrye Reactive Messaging.
Here is my proposal : https://github.com/smallrye/smallrye-reactive-messaging/pull/1909

**Comment by cescoffier** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/28117.
