### ISSUE TITLE
@InjectMock is used in follow up @QuarkusTest classes

### ISSUE THREAD

**Issue by Krawart** [quarkusio/quarkus#26811]
### Describe the bug

Incorrect @Inject when Mocking was used in previous tests. Happens after upgrade from Quarkus 2.10.1 -> 2.10.2

### Expected behavior

Mocked bean should be used only for class where it lives

### Actual behavior

@Inject is injecting mocked bean from previous @QuarkusTest classes

### How to Reproduce?

Kotlin quarkus app with mockito:

1. Init kotlin quarkus project
2. Create @ApplicationScope bean
3. Create @QuarkusTest with mocked bean
4. Create another @QuarkusTest class with injected implementation (@Inject). Make sure, that this test runs after the test created in step 3

### Output of `java -version`

17

### Quarkus version or git rev

2.10.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Does this happen with 2.11.0.Final?

**Comment by Krawart** [comment]
In version 2.10.3 it is already fixed. Thank You

**Comment by geoand** [comment]
Thanks for checking
