### ISSUE TITLE
Panache - Support specifying whether NULLs come first or last when using `Sort`

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#26814]
### Description

When using `ORDER BY` in SQL you can specify where nulls should appear using `NULLS FIRST` or `NULLS LAST`, e.g. `ORDER BY x DESC NULLS LAST`

It would be nice to have this functionality available when using `Sort.by` and `Sort.ascending` etc.

### Implementation ideas

Add directions `ASCENDING_NULLS_FIRST`, `ASCENDING_NULLS_LAST`, `DESCENDING_NULLS_FIRST` ... etc

Add shortcuts `Sort.ascendingNullsFirst`, `Sort.ascendingNullsLast` ... etc

**Comment by Sgitario** [comment]
This has been recently implemented in https://github.com/quarkusio/quarkus/pull/26394.

Example: Sort.by("foo", Sort.NullPrecedence.NULLS_FIRST);

**Comment by josephearl** [comment]
Awesome, in which case this can be closed
