### ISSUE TITLE
Fault Tolerance - Retry not working with Vertx's WebClient

### ISSUE THREAD

**Issue by GustavoGramajo** [quarkusio/quarkus#26821]
### Describe the bug

I need to request info from an external service; said service is not that reliable, so it could fail under several circumstances. While implementing a Retry strategy, i found that it does not always work.

### Expected behavior

I expect APIClientVerticle.sendRequest to be called 5 times in a row when making a request to http://localhost:8081/retrySkipped

### Actual behavior

The exception is thrown right away; it does not seems to be catched by the retry mechanism:

            try {
                CompletionStages.propagateCompletion((CompletionStage)this.delegate.apply(ctx), result);
            } catch (Exception var4) {
                result.completeExceptionally(var4); // the debugger does not stop here for {host}/retrySkipped
            }

### How to Reproduce?

Reproducer: https://gitlab.com/gus.gramajo/quarkus-ft-retry-reproducer

Steps to repro:

1 - ./mvnw quarkus: dev
2 - Make a request to http://localhost:8081/retryWorks
3 - Make a request to http://localhost:8081/retrySkipped

### Quarkus version or git rev

2.9.1.Final, 2.10.2.Final

**Comment by Ladicek** [comment]
First off, it is idiomatic for methods that return a future type, such as `CompletionStage<JsonObject>` in the case of `APIClientVerticle.sendRequest`, to never throw exceptions -- instead, the future should be completed exceptionally.

That said, SmallRye Fault Tolerance does attempt to catch exceptions from such methods, so this really should work. I'll take a look at the reproducer.

**Comment by Ladicek** [comment]
Okay so the difference between `retryWorks` and `retrySkipped` is that in the first one, the `RuntimeException` is thrown synchronously (probably because DNS resolution is synchronous even in Vert.x), while in the second, the `RuntimeException` is thrown asynchronously. At that time, there's no SmallRye Fault Tolerance code on the stack that could catch it, so this really can't work and there's nothing SmallRye Fault Tolerance can do about it.

Your code needs to look like this:

```java
client.getAbs(url)
    .send()
    .onComplete(res -> {
        future.completeExceptionally(new RuntimeException("Unauthorized request"));
    });
```

**Comment by GustavoGramajo** [comment]
Excellent! Thanks for your time and your clear explanations, i can confirm it works on my end too after making the recommended adjustments.
