### ISSUE TITLE
Lost context in @Blocking gRPC Service behind a GlobalInterceptor

### ISSUE THREAD

**Issue by spencercjh** [quarkusio/quarkus#26830]
I found that Quarkus Server register `io.quarkus.grpc.runtime.supports.blocking.BlockingServerInterceptor` for each blocking gRPC service with the `@Blocking` annotation before it starts.

If some global interceptors (with `@GlobalInterceptor`) set the Context value will not work. The `Context` will still be empty in the actual rpc method handler.

Is it a normal phenomenon because `Context` should be placed after `BlockingServerInterceptor` 's `vert.x.executeBlocking`? There are some associated issues: https://github.com/quarkusio/quarkus/issues/14665, https://github.com/quarkusio/quarkus/issues/13959.

Finally, I replace the `@GlobalInterceptor` with `@RegisterInterceptor(MyInterceptor.class)`, and everything is to be ok which seems to prove my point.

I don't particularly understand the technical details of it, and these are what I got from trying and debugging. I've been only using Spring and Micronaut before.

origin question:

https://stackoverflow.com/questions/73039706/lost-context-in-blocking-grpc-service-with-quarkus-behind-a-globalinterceptor

**Comment by spencercjh** [comment]
If my description is correct, I would like to add the above to the relevant docs(gRPC interceptor, `@Blocking`) with a PR.

**Comment by cescoffier** [comment]
@spencercjh sorry for the delay. 
By any chance, do you have a reproducer?

**Comment by cescoffier** [comment]
I was able to reproduce it.

**Comment by spencercjh** [comment]
@cescoffier sorry for the delay...

```
                                                                                                                                                        
                                                                                                                                                             
                                                                                                                                                             
                                                                                                                                                             
                                     Global gRPC interceptor      vert.x BlockingServerInterceptor   Actual request handler                                  
                                             +----+                           +----+                         +----+                                          
                                             |    |                           |    |                         |    |                                          
                                  request    |    |                           |    |                         |    |                                          
                        -------------------->|    | ------------------------->|    |-----------------------> |    |---------+                                
                                             |    |                           |    |                         |    |         |                                
                                             |    |                           |    |                         |    |         | process                        
                                             |    |                           |    |                         |    |         |                                
                                             |    |                           |    |                         |    |         v                                
                                             |    |                        -->|    | <---------------------- |    |<---------                                
                                             +----+                    ---/   +----+    throw exception      +----+                                          
                                                      hang up here  --/                                                                                      
                                                      and no response to stub becasue  onError isn't invoked.                                                
                                                                                                                       
```

The best practice for gRPC is to use the Global gRPC Interceptor to handle exceptions as a last resort, but due to the problems mentioned in this issue, this operation is not feasible (under @Blocking gRPC), the thread will hang, the request will not be responded to correctly, and the code will not run to the interceptor as expected.

I actually wanted to write the gRPC service with the asynchronous API that Quarkus recommends more, but the gRPC and Protobuf we use are managed by [Buf](https://docs.buf.build/tour/generate-code#generate-c-and-java-stubs), not just pure protoc, and we can't generate a whole new set of gRPC code like in the documentation.

Maybe we need another issue.
