### ISSUE TITLE
Support `Keycloak` injection in `quarkus-keycloak-admin-client` and `quarkus-keycloak-admin-client-reactive`

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#26837]
### Description

Right now, the users how to initialize `Keycloak` directly in the code, using a typical sequence:
```
KeycloakBuilder.builder()
                .serverUrl(KEYCLOAK_SERVER_URL)
                .realm("master")
                .clientId("admin-cli")
                .username("admin")
                .password("admin")
                .build();
```

However, as shown by @omar-zahid  in #26836, it would really be simpler to have an injected `Keycloak`, which would also provide some extra value to using `quarkus-keycloak-admin-client`.

The same applies to `quarkus-keycloak-admin-client-reactive`

**Comment by michalvavrik** [comment]
This is interesting for me, but on level of the `quarkus-keycloak-admin-client/-reactive`, this can't be done without introducing configuration properties for server url and credentials... right?

**Comment by sberyozkin** [comment]
@michalvavrik Great, yes, you are right, I believe we'll need to have a `KeycloakAdminClient` group. You can then update the existing tests where `Keycloak` is currently created manually. Have a look please when you get a chance :-)

**Comment by omar-zahid** [comment]
Thanks a lot. Appreciate it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by omar-zahid** [comment]
Thanks all.
