### ISSUE TITLE
Update h2 database

### ISSUE THREAD

**Issue by timonzi** [quarkusio/quarkus#26841]
### Description

Quarkus in version 2.10.3.Final defines a Maven dependency to com.h2database:h2 with version 2.1.210.
This contains some issues, like the following one which is problematically for us:

> [PR #3464](https://github.com/h2database/h2database/pull/3464) / [Issue #3457](https://github.com/h2database/h2database/issues/3457): increase max length of VAR* types

Source: http://www.h2database.com/html/changelog.html

I would suggest to update from 2.1.210 to 2.1.214 (or a newer version if available).

In the meantime we will override the version in our projects.

**Comment by timonzi** [comment]
When does the Dependabot create the "bump" issue? I would close this issue as soon as I can see the bump issue.

**Comment by gsmet** [comment]
It will automatically be closed when https://github.com/quarkusio/quarkus/pull/26855 is merged.

**Comment by gsmet** [comment]
Thanks for raising the issue!

**Comment by timonzi** [comment]
Thank you for solving it (sustainably) :+1:
