### ISSUE TITLE
2.10.2.Final, ContextualData lost in rest-client-reactive response

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#26857]
### Describe the bug

ContextualData lost in the rest client reactive(vert.x-eventloop) response

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/2.2E10.2E2.2EFinal.2C.20ContextualData.20lost.20in.20rest-client-reactive.20re

### Expected behavior

ContextualData should be availiable in the response

### Actual behavior

ContextualData is  lost

### How to Reproduce?

See provided reproducer

run provided test & verify the log in MyClientResponseFilter

It works for 2.10.1.Final, ie. ContextualData is not lost

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.10.2.Final & 2.11.0.Final

### Additional information

[rest-client-reactive-quickstart11.zip](https://github.com/quarkusio/quarkus/files/9158703/rest-client-reactive-quickstart11.zip)

**Comment by RuggeroDAlo** [comment]
@lthasle Probably the same issue as https://github.com/quarkusio/quarkus/issues/26717 ? I think it is caused by #26332

**Comment by lthasle** [comment]
Any progress on this?
I tried with the latest Quarkus version: 2.11.2.Final and found that it is still not fixed

**Comment by gsmet** [comment]
@cescoffier I had a look at the reproducer and it turns out `ContextualData` is `io.reactiverse.contextual.logging.ContextualData`. Wondering if it's something we support and if we have a similar feature if not.

**Comment by cescoffier** [comment]
@gsmet not really, we have some support of it in https://github.com/quarkusio/quarkus/blob/main/extensions/vertx/latebound-mdc-provider/src/main/java/io/quarkus/vertx/mdc/provider/LateBoundMDCProvider.java.

ContextualData is data associated with the Vert.x duplicated context.

**Comment by lthasle** [comment]
Hi!

As it is working in previous Quarkus versions (up to 2.10.1.Final)
I expect it also work in later versions?
Migration-Guides, don't include any information about this breaking change.

@cescoffier was helpful and provided us with this solution when we migrated to reactive some time ago.

Any advice on this issue is much appreciated, as we need to be on the latest Quarkus version, due to other solved issues in latest version.

**Comment by cescoffier** [comment]
I believe it's a context propgation related bug. We are working on this from different angle and hope to provide a fix (like #27443) soon. 

There are two issues:

- there is a duplication of the duplicated context due to OpenTelemetry 
- the context is lost when resteasy reactive suspend the request (and the context is not re-activated)

**Comment by lthasle** [comment]
@cescoffier 
Any news on this?
Will it be fixed in: #27443

**Comment by cescoffier** [comment]
Ah yes! Sorry! It should be fixed in the release that should go out today (CR1).

Basically, as you saw the contextual data was lost. It's not the case anymore. 

It would be great if you could verify, and let us know.

**Comment by cescoffier** [comment]
Ok due to Sonatype being picky (ask @gsmet), it may be only released tomorrow.

**Comment by RuggeroDAlo** [comment]
@cescoffier I just did a quick test with 2.13.0.CR1 and the issue using MDC seems to be fixed (I opened duplicate issue #26717 ), thanks!

**Comment by lthasle** [comment]
@cescoffier Works fine, thanks!
