### ISSUE TITLE
Native image generation fails with 'Invalid signature file digest' if 'uberJar' is enabled

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#2686]
**Describe the bug**
If the `quarkus-maven-plugin` enables a `uberJar` property and signed jars such as BouncyCastle ones are pulled in then the native image generation fails with the `java.lang.SecurityException: Invalid signature file digest for Manifest main attributes`.
Excluding `META-INF/*.SF`, `META-INF/*.DSA` and `META-INF/*.RSA` has no effect.

**Comment by sberyozkin** [comment]
This can be reproduced with the `integration-tests/keycloak`

**Comment by sberyozkin** [comment]
I've assigned it to myself but if someone already knows how to approach this issue please reassign otherwise I'll try to investigate later on, thanks

**Comment by emmanuelbernard** [comment]
Discussing with some others, the best would be for us to filter out the signature files for the moment. If anyone wants to take that action, please open a PR.

**Comment by jaikiran** [comment]
> If anyone wants to take that action, please open a PR.

@emmanuelbernard Here's a PR for this change https://github.com/quarkusio/quarkus/pull/4259

**Comment by machi1990** [comment]
@sberyozkin I am assigning @jaikiran to the issue since he proposed a PR to fix it.

**Comment by jaikiran** [comment]
The PR has been merged, so I think this enhancement can now be closed.

**Comment by machi1990** [comment]
Fixed by #4259
