### ISSUE TITLE
Default Health Group

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#26877]
### Description

We are currently splitting of health checks because a certain part only concerns departement A and the other part only concerns departement B. I thought this would be done easily with the `@HealthGroup`. And actually, it is. There is only one thing that really bugs me. 

We already have an X amount of existing health checks that only concerns departement A. a new health check now only concerns dep B.

I now need to go ahead an annotate all existing HealthChecks with group "A" and the new one with group "B".

Therefor, it would be great to be able to define a default health group with a property like `quarkus.health.defaulthealthgroup=myDefaultGroup` which would cause, that all health checks which are not specifically annotated with `HealthGroup` are automatically registered with the default health group.

**Comment by xstefank** [comment]
OK, why not :) I will implement this in the next SR Health release.

**Comment by xstefank** [comment]
@HerrDerb did you try it please? Can we close this?

**Comment by HerrDerb** [comment]
@xstefank Sorry for letting you hang there. Yes it does work es expected :) Thank you very much for this.

**Comment by xstefank** [comment]
@HerrDerb I forgot to close it too :) Thanks!

**Comment by xstefank** [comment]
@gsmet @geoand this can be closed but I don't have the button.

**Comment by geoand** [comment]
Any idea which Quarkus version it was delivered with?
