### ISSUE TITLE
MicroProfile Rest Client @RegisterRestClient ignoring baseUri property

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#2687]
**Describe the bug**
MicroProfile Rest Client 1.2 added the baseUrl property to the @RegisterRestClient annotation, which seems to be ignored.

**Expected behavior**
Utilize the baseUrl from the @RegisterRestClient(baseUrl = ...) even when.../mp-rest/url property in application.properties does not exist.

**Actual behavior**
"NoSuchElementException: Property org.acme.restclient.CountriesService/mp-rest/url not found"

**To Reproduce**
1. In the rest-client Quarkus quickstart, comment out the mp-rest/url property in application.properties
2. In the rest-client Quarkus quickstart, in CountriesService.java replace @RegisterRestClient with:
`@RegisterRestClient(baseUri = "https://restcountries.eu/rest"`
3. Run `mvn quarkus:dev` and hit the endpoint ([http://localhost:8080/country/name/greece](http://localhost:8080/country/name/greece)). Kablooey!

**Environment (please complete the following information):**
 Quarkus 0.15.0 rest-client quickstart, which I believe supports MP Rest Client 1.2

**Additional Information**
Visual Studio Code does offer the option to auto-complete baseUri, so it does exist, implying MP Rest Client 1.2 support.

**Comment by geoand** [comment]
Interesting, I'll try and take a look at it soon, unless anyone beats me to it

**Comment by jclingan** [comment]
BTW, I'm not sure if [this commit](https://github.com/resteasy/Resteasy/pull/2052/commits/386077e9ef0447b49597f3497b9623b33d950c5b) fixes the problem (RestClientExtension.java). Haven't tracked down if it fixes the problem and, if so, when it will be pulled into Quarkus.

**Comment by geoand** [comment]
@jclingan I tried against the latest master and the problem was still there. PR #2690 should take care of the issue

**Comment by jclingan** [comment]
Thank you sir!

**Comment by geoand** [comment]
You are most welcome :)
