### ISSUE TITLE
jandex.Indexer.sizeToFit inside quarkus-maven-plugin: OOM on builds with many (generated) files

### ISSUE THREAD

**Issue by jcunliffe1** [quarkusio/quarkus#26875]
### Describe the bug

I have a project with a bunch of files getting generated. When I remove some, I can avoid the OOM below on my gitlab runner pipeline. Locally on my Mac all is fine either way.

Currently I'm struggling with setting the XMX jvmArgs for the maven plugin. I tried the regular jvm.config and the maven-quarkus-plugin's configuration/jvmArgs - nothing seems to be picked up by the build. This would be quite important to allow for further debugging - any ideas?

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.10.3.Final:build (default) on project ecom-gatewayservices-ipg-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.vertx.http.deployment.webjar.WebJarProcessor#processWebJarProdMode threw an exception: java.lang.OutOfMemoryError: Java heap space
[ERROR] 	at java.base/java.io.InputStream.readNBytes(InputStream.java:445)
[ERROR] 	at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.InMemoryTargetVisitor.visitFile(InMemoryTargetVisitor.java:20)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil$ResourcesFileVisitor.visitFile(WebJarUtil.java:215)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil$ResourcesFileVisitor.visitFile(WebJarUtil.java:163)
[ERROR] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
[ERROR] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2876)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil$1.accept(WebJarUtil.java:85)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil$1.accept(WebJarUtil.java:71)
[ERROR] 	at io.quarkus.paths.PathTreeVisit.consume(PathTreeVisit.java:48)
[ERROR] 	at io.quarkus.paths.ArchivePathTree.accept(ArchivePathTree.java:95)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil.copyResources(WebJarUtil.java:71)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarUtil.copyResourcesForProduction(WebJarUtil.java:59)
[ERROR] 	at io.quarkus.vertx.http.deployment.webjar.WebJarProcessor.processWebJarProdMode(WebJarProcessor.java:78)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at io.quarkus.builder.BuildContext$$Lambda$810/0x0000000801886a38.run(Unknown Source)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:831)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] 
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.ApplicationIndexBuildStep#build threw an exception: java.lang.OutOfMemoryError: Java heap space

### Expected behavior

the build to work with a few more java classes

### Output of `uname -a` or `ver`

linux

### Output of `java -version`

16

### Quarkus version or git rev

2.10.3.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.2

**Comment by jcunliffe1** [comment]
this concerns regular jar builds with fast-jar

**Comment by famod** [comment]
`jvmArgs` is only for `quarkus:dev` and `quarkus:test` goals.

`.mvn/jvm.config` should work though. Have you tried `MAVEN_OPTS`?

**Comment by jcunliffe1** [comment]
yes I have with     MAVEN_OPTS: "-Xmx4g -XX:MaxRAMPercentage=50.0 -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintFlagsFinal -XX:MaxMetaspaceSize=1g -Xlog:gc*=debug:file=build.txt"

here is what the heap dump gives away

Thread 'build-36' with ID = 88
	java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	java.util.Arrays.copyOf(Arrays.java:3536)
	org.jboss.jandex.Indexer.sizeToFit(Indexer.java:238)
	org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1881)
	org.jboss.jandex.Indexer.index(Indexer.java:1981)
	io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:49)
	io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:34)

**Comment by jcunliffe1** [comment]
do I have to jandex only on libraries, or also the application itself?

**Comment by jcunliffe1** [comment]
I will retest a few times to find out if the oom happens in the same procedure always.

**Comment by famod** [comment]
First off, for Quarkus 2.10.3.Final you should be using jandex plugin 1.2.2 instead of 1.2.1, see https://github.com/quarkusio/quarkus/blob/2.10.3.Final/bom/application/pom.xml#L21
vs. https://github.com/wildfly/jandex-maven-plugin/blob/1.2.1/pom.xml#L116
But I don't think this (alone) will resolve your issue.

Furthermore, I also have loads of generated classes in my project and we don't configure any fileSets for jandex-maven-plugin.

Btw, I'd recommend to just use an empty beans.xml instead. Might be a bit slower but you'll have less to maintain.

The Quarkus build process will create an index anyway, so you usually only need an explicit index when multiple modules and/or external libs are involved.

**Comment by jcunliffe1** [comment]
ok, where does the empty beans.xml go? src/main/resources? or META-INF ?

**Comment by jcunliffe1** [comment]
found the answer here https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module

**Comment by jcunliffe1** [comment]
after removing the jandex scans from annotation heavy maven modules, I could get rid of the OOM. would have preferred not to learn this lesson, but anyway - I'm good... until the next OOM happens out of nowhere.

**Comment by famod** [comment]
Glad you got it sorted.

Bean discovery is documented here, btw: https://quarkus.io/guides/cdi-reference#bean_discovery

**Comment by jcunliffe1** [comment]
... and its back

**Comment by gsmet** [comment]
Can you get a heap dump when you have a OOM? Because right now, I think you just have random stacktraces that might or might not be related.

**Comment by Ladicek** [comment]
I'm reopening this issue, because I think it's the place where this conversation can happen. It makes no sense to open issues on random projects based on which thread was unlucky enough to hit the OOM condition.

As @gsmet said, we'd need a JVM heap dump. I see you already have `-XX:+HeapDumpOnOutOfMemoryError`, so we'll just need that `.hprof` file.

**Comment by jcunliffe1** [comment]
I'm sorry for all the confusion. Basically out gitlab pipeline ignored xmx settings, and I had to 

```
MAVEN_SKIP_RC: "true"
```

to the jobs variables to make maven accept my MAVEN_OPTS with the xmx settings.

After this, the job was passing again. Previously it always ended up with the OOM during Jandex Indexing - but probably only, because this took a large junk of memory and thus was likely to be hit by the OOM.

I'm thus closing it, because really it's a pipeline configuration problem.

BTW this tool was quite helpful: https://devcenter.heroku.com/articles/java-memory-issues#memory-logging-agent

you might want to consider adding it to the quarkus maven plugin to allow easier oom debugging.
