### ISSUE TITLE
RabbitMQ without dev services now requires `rabbitmq-http-port`

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#26873]
### Describe the bug

When using RabbitMQ in dev mode, but without dev services, now requires `rabbitmq-http-port` to be set and it may not be available or exposed.

### Expected behavior

`rabbitmq-http-port` shouldn't be required.

### Actual behavior

Startup fails with

      SRCFG00014: The config property rabbitmq-http-port is required but it could not be found in any config source

### How to Reproduce?

Run an application that uses RabbitMQ in dev mode while providing values for `rabbitmq-host`, `rabbitmq-port`, `rabbitmq-username` & `rabbitmq-password`.

Startup will fail with the above error message.

### Output of `uname -a` or `ver`

macOS 12.4

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.11.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26930 fixes the issue
