### ISSUE TITLE
Quarkus extensions for Chatbot Platform "EDDI"

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#26894]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

--
We have recently released version 5 of our open source chatbot platform EDDI which has been migrated to quarkus. 
Announcement article: https://eddi.labs.ai/cloud-native-chatbot-engine-goes-quarkus/
Github Repo: https://github.com/labsai/eddi

Moving on, we would like to build two extensions making EDDI easily available for other quarkus developers looking for (state-based) conversational (chatbot) capabilities.
The two extensions:
* eddi-client (acts as a client-library connecting to an eddi-server instance)
* eddi-server (spin up an eddi instance within another quarkus application, [and possibly extend it])

### Additional context

We have set ourselves the goal of becoming the go-to framework for adding conversational/NLP capabilities to other quarkus apps being build out there. Any feedback or suggestions for improvements of whatever parts of our project are welcomed!

**Comment by sberyozkin** [comment]
Hi @ginccc I believe such new extensions have to be created in https://github.com/quarkiverse
@gastaldi Can you please advise @ginccc on the next steps ?

**Comment by gastaldi** [comment]
Sure, we have a checklist for new projects in https://github.com/quarkiverse/quarkiverse/wiki/Checklist. This issue is the first step.

@ginccc I'm assuming that a single multimodule repository named `quarkus-eddi` is what you need, I'll create it and send you an invitation to join the [Quarkiverse Hub organization](https://github.com/quarkiverse)

**Comment by gastaldi** [comment]
@ginccc there you go: https://github.com/quarkiverse/quarkus-eddi

Let me know if you need anything else. Enjoy! 😉

**Comment by sberyozkin** [comment]
Thanks @gastaldi :+1:

**Comment by ginccc** [comment]
Thanks a lot, @gastaldi!
As we are planning to build two separate extensions (eddi-server, eddi-client), should we perhaps have two repositories - one for each, or do you want us to manage both extensions inside one repo?

**Comment by gastaldi** [comment]
@ginccc it's up to you, really. IMHO making it as a multimodule project may be easier to manage the releases (and even to introduce other related extensions). Here is an example of a multimodule project: https://github.com/quarkiverse/quarkus-google-cloud-services

Let me know if you prefer two repositories instead
