### ISSUE TITLE
Warning about failed substitution registrations

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2689]
I'm seeing these warnings during native builds:

> Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
> Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.

It's not quite clear to me what the implications of this is and whether it's a real problem or not. Would be good to clarify this, e.g. by adding another message in case this is something originating from SVM but can be ignored.

**Comment by speedfl** [comment]
+1

**Comment by gsmet** [comment]
@dmlloyd I think you were discussing this very issue the other day with Bill. Did you end up with a solution?

**Comment by dmlloyd** [comment]
I was discussing it with Bob... I think he has a fix for it.

**Comment by kid7st** [comment]
+1

**Comment by gsmet** [comment]
@dmlloyd should we release a new version of JBoss Threads and upgrade to it?

**Comment by dmlloyd** [comment]
Sure.  I've released 3.0.0.Beta5, PR coming in a bit.
