### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by reda-alaoui** [quarkusio/quarkus#26901]
### Description

I forked this project but do not find how to release my fork.

It seems that `./mvnw versions:set -DnewVersion=2.10.3.0.cosium` does an incomplete job.
Also since they are gradle modules, I am not sure it is the only command to run.

In the end, I'd like to know how a revision like https://github.com/quarkusio/quarkus/commit/55cf39d7c545f9b5d3670bd46827e4aaa9a7a274 was created.

Could this be documented?

**Comment by gsmet** [comment]
This script handles the full version update: https://github.com/quarkusio/quarkus/blob/main/update-version.sh .

**Comment by reda-alaoui** [comment]
Thank you ! I don't understand how I could have miss it :)

**Comment by gsmet** [comment]
I recently added it to the repo so it's probably not in the 2.10 branch (but you can just push it there, it will work).

**Comment by geoand** [comment]
So should we close this?

If we do document things, my fear is that the documentation will not be up to date with the script.

**Comment by reda-alaoui** [comment]
I think mentionning the script location in CONTRIBUTING.md would be nice.
I can open a PR for this if you agree.
