### ISSUE TITLE
Profile is not test in QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#26908]
### Describe the bug

https://github.com/quarkiverse/quarkus-zeebe/issues/76

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 LTS

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
It's very hard to understand what the reported issue is.

Please attach more information and preferable a sample that does not include extensions not part of the Quarkus core.

**Comment by geoand** [comment]
Closing as we never received the necessary information
