### ISSUE TITLE
Quarkus Profile doesn't work

### ISSUE THREAD

**Issue by khush2704** [quarkusio/quarkus#26909]
### Describe the bug

I have [application.properties]aving different profiles configured , eg : %windows.quarkus.http.ssl.certificate .... = ${CSPKI_WEB_CERT} and other profile as %ci.quarkus.http.ssl.certificate.... = src/main/resources/certs/cert.p12 . When I run CI build with this - maven(command: '-B -Dquarkus.profile= ci clean deploy) , Jenkin is reading even the windows profile configuration, And yes I have provided my default profile as windows.

### Expected behavior

It should pick active profile which is set and not read all properties mentioned in application.properties.

### Actual behavior

Currently it reads all the profiles mentioned in application.properties file.

### Output of `java -version`

11.0.15

### Quarkus version or git rev

1.21.0.Final

**Comment by geoand** [comment]
Can you please try to format the description a little better? It's currently hard to understand.

Thanks

**Comment by radcortez** [comment]
Please, can you provide a reproducer and clarify the Quarkus version? I don't think we have a `1.21.0.Final`. Thank you!

**Comment by geoand** [comment]
Closing as we never got a reproducer
