### ISSUE TITLE
RESTEasy Reactive - Improve documentation around mutiny and reactive

### ISSUE THREAD

**Issue by navkast** [quarkusio/quarkus#26903]
### Description

I've seen people get confused, thinking that using Mutiny will automatically push blocking work to worker threads.
See for example: https://stackoverflow.com/questions/71754982/quarkus-mutiny-and-imperitave-vs-reactive.

I've also fallen into this trap. First, I wanted to demonstrate that using Mutiny automatically shoves blocking calls into a separate worker thread pool:

```java
return Uni
  .createFrom()
  .nullItem()
  .onItem()
  .delayIt()
  .by(Duration.ofSeconds(5))
  .onItem()
  .transform(o -> doExpensiveWork());
```

In the logs - it looks great! The work is done in a separate thread pool. Ok, now I decide this works well and remove the `delayIt()` to get it ready for production:

```java
return Uni
  .createFrom()
  .nullItem()
  .onItem()
  .transform(o -> doExpensiveWork());
```
only to notice that all of the work continues to happen on the `vert.x-event-loop-thread-0`. Everything slows to a crawl.

This happens because internally, onDelay switches the stream to using `Infrastructure.getDefaultWorkerPool()`. 
```java
    @CheckReturnValue
    public UniOnItemDelay<T> delayIt() {
        return new UniOnItemDelay<>(upstream, null);
    }
```
```java
    /**
     * Creates a new {@code UniOnItemDelay} instance.
     *
     * @param upstream the upstream uni
     * @param executor the executor, can be {@code null}, if {@code null} used the default worker executor.
     */
    public UniOnItemDelay(Uni<T> upstream, ScheduledExecutorService executor) {
        this.upstream = upstream;
        this.executor = executor == null ? Infrastructure.getDefaultWorkerPool() : executor;
    }
```
It's only visible in the code - I couldn't find it documented anywhere that the `onDelay()` switches the stream to a different thread pool  `.call()`, `.invoke()`, .`transform()` etc happen on the same thread. 

Only after reading these comments inside StackOverflow did everything click: 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/4895027/180615277-47a28687-d4ae-4542-b44d-19063942beb8.png"> 
(from https://stackoverflow.com/questions/71754982/quarkus-mutiny-and-imperitave-vs-reactive)
After seeing that, I saw the `.emitOn()` and `.runSubscriptionOn()` methods where i can orchestrate the async calls to separate thread pools.

Relatedly, using `i/o thread` and `worker thread` has been confusing to me. When seeing `i/o thread`, I think that this is a thread where I/O happens. Instead, it's actually the vertx event loop thread where such blocking I/O shouldn't happen. For example, this is a screenshot from the documentation:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/4895027/180615311-87cbbbd6-8333-4905-b847-e6420b2ba378.png">

It's much more clear to me if we write it as:
![image](https://user-images.githubusercontent.com/4895027/180615319-6df401eb-6678-46b8-930e-3d33178e7ef0.png)

**Comment by cescoffier** [comment]
The table you give is not correct. The thread depends of the emission / subscription thread. We cannot generalize like this. We could add something about RestEasy reactive, but even in this case it may not be right.

Note that the mutiny documentation and javadoc covers a lot of what you mentioned.

**Comment by navkast** [comment]
Yes, I was looking at it only from the resteasy-reactive http request context.

**Comment by jponge** [comment]
Closing this old issue.

The documentation is actually correct and accurate _wrt_ the dispatch strategies, and Mutiny itself does have a good documentation (guides, javadoc, etc) that explain what it is doing, and what it is not doing.
