### ISSUE TITLE
Make Quarkus Kubernetes gitops friendly.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#26928]
### Description

Currently the generated resources are not very gitops friendly.

- [ ] The resources are not idempotent (affected by commit, date and user).
- [ ] The resources are generated under `target` which is usually not version controlled.

### Implementation ideas

We should disable the presence of non-idempotent labels by default.
We should also generate resources somewhere in the module root. Maybe `.kubernetes` or something like this.

**Comment by geoand** [comment]
Very good idea!

cc @Sgitario as well

**Comment by lburgazzoli** [comment]
Not sure if this is a quarkus specif things but we should ensure that arrays are always generated in the same order, as example, this is what I get time to time:

![image](https://user-images.githubusercontent.com/1868933/185412230-27adf5f1-7624-48c2-8f2c-e372c05eb8ea.png)


```xml
 <!-- secret -->
        <quarkus.kubernetes.secret-volumes.app-secret.secret-name>${app-secret.name}</quarkus.kubernetes.secret-volumes.app-secret.secret-name>
        <quarkus.kubernetes.secret-volumes.app-secret.default-mode>0644</quarkus.kubernetes.secret-volumes.app-secret.default-mode>
        <quarkus.kubernetes.mounts.app-secret.path>/mnt/app-secret</quarkus.kubernetes.mounts.app-secret.path>

        <!-- config map -->
        <quarkus.kubernetes.config-map-volumes.app-config.config-map-name>${app-config.name}</quarkus.kubernetes.config-map-volumes.app-config.config-map-name>
        <quarkus.kubernetes.config-map-volumes.app-config.default-mode>0644</quarkus.kubernetes.config-map-volumes.app-config.default-mode>
        <quarkus.kubernetes.mounts.app-config.path>/mnt/app-config</quarkus.kubernetes.mounts.app-config.path>

        <!-- smallrye -->
        <quarkus.kubernetes.env.vars.SMALLRYE_CONFIG_LOCATIONS>/mnt/app-config</quarkus.kubernetes.env.vars.SMALLRYE_CONFIG_LOCATIONS>
        <quarkus.kubernetes.env.vars.SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS>/mnt/app-secret</quarkus.kubernetes.env.vars.SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS>
```
