### ISSUE TITLE
Hibernate-validator won't properly work when using @Observes for ApplicationScoped.class

### ISSUE THREAD

**Issue by i96751414** [quarkusio/quarkus#26931]
### Describe the bug

When using hibernate-validator on a class containing a `@Observes @Initialized(ApplicationScoped.class)` method, all the methods containing constraint annotations throw a NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "javax.validation.Validator.forExecutables()" because "this.validator" is null

	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:59)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        ...
```

### How to Reproduce?

One can reproduce the problem with a QuarkusTest: 

```java
@QuarkusTest
class HibernateValidatorTest {

    @Inject
    TestClass testClass;

    @Test
    void test() {
        testClass.call(null); // or testClass.call("");
    }

    @ApplicationScoped
    static final class TestClass {

        void startUp(@Observes @Initialized(ApplicationScoped.class) final Object event) {

        }

        void call(@NotNull final Object o) {

        }

    }
}
```

**Comment by gsmet** [comment]
@mkouba @manovotn any idea if this is something we could support with adjustments to the Hibernate Validator extension?

In any case, if we can't, I'll add a better error message than a NPE.

**Comment by mkouba** [comment]
@gsmet Does it occur because the HV is initialized at runtime?

**Comment by manovotn** [comment]
@gsmet does the validator have some non CDI fallback? I am looking at the code but so far I don't understand how do you get instance of `MethodValidationInterceptor` without getting unsatisfied dependency on its injection

**Comment by gsmet** [comment]
@mkouba yeah, the `ValidatorFactory` and the shared `Validator` instance are created in a `BeanContainerListener`.

One important thing is that I consume CDI beans to initialize the `ValidatorFactory` as CDI beans are used to customize/populate it.
And no, I don't have a non CDI fallback.

**Comment by manovotn** [comment]
@i96751414 just to make sure you know, you can make this work by using `@Observes Startup` instead of the observer you have now.
Details can be seen in this guide -> https://quarkus.io/guides/lifecycle#listening-for-startup-and-shutdown-events

**Comment by mkouba** [comment]
> I don't understand how do you get instance of MethodValidationInterceptor without getting unsatisfied dependency on its injection

@manovotn The injected bean is most probably a producer initialized during RUNTIME_INIT, hence returning `null` during STATIC_INIT.

**Comment by manovotn** [comment]
Hmm, that is what I initially thought but in such case using `Instance<Validator>` might help as validation methods are invoked in runtime.
But it does it opposite, with `Instance` it starts failing on unsatisfied dep, hmm.

**Comment by mkouba** [comment]
> @mkouba yeah, the `ValidatorFactory` and the shared `Validator` instances are created in a `BeanContainerListener`.
> 
> One important thing is that I consume CDI beans to initialize the `ValidatorFactory` as CDI beans are used to customize/populate it. And no, I don't have a non CDI fallback.

Ok, so you need to build the `ValidatorFactory` after the CDI container init is finished. In theory, you can make the `MethodValidationInterceptor` aware of the fact that the injected factory/validator can be `null` and log some useful warning/error message.

**Comment by mkouba** [comment]
> Hmm, that is what I initially thought but in such case using `Instance<Validator>` might help as validation methods are invoked in runtime. But it does it opposite, with `Instance` it starts failing on unsatisfied dep, hmm.

Like `@Inject Instance<javax.validation.Validator>`?

**Comment by manovotn** [comment]
@gsmet Actually you can make this work if instead of using `@Inject Validator` you introduce helper method such as:

```
    protected Validator getValidator() {
        return Arc.container().instance(Validator.class).get();
    }
```

This will make the resolution dynamic and only executed at runtime when you have `Validator` instance ready.

With that and the example above, I am getting correct error from validator - `Constraint violations:  ...`

**Comment by manovotn** [comment]
> > Hmm, that is what I initially thought but in such case using `Instance<Validator>` might help as validation methods are invoked in runtime. But it does it opposite, with `Instance` it starts failing on unsatisfied dep, hmm.
> 
> Like `@Inject Instance<javax.validation.Validator>`?

Yes, we probably pre-resolve set of candidate beans for `Instance` at the time of injection, right?

**Comment by gsmet** [comment]
> You might need to cache it the first time it is invoked since the bean is dependent and hence you'd create more instances this way

Hmmm. I don't think it was our intention to make the bean dependent. It's stored statically so I don't think it changes things too much but I'll have a look at changing that.

**Comment by manovotn** [comment]
The reason you have it dependent might be because you need to be able to return `null` from its producer in some cases?
But since it is static, it doesn't really matter.

Either way, I had a slightly wrong config before, you can use `Instance<Validator>` and you can leverage `@WithCaching` to make it look clearer as well.
PR incoming shortly.

**Comment by gsmet** [comment]
Ah OK, I was implementing this with a volatile. But if you have a better option, I'm waiting for your PR :).

**Comment by gsmet** [comment]
> The reason you have it dependent might be because you need to be able to return null from its producer in some cases?

No, they should always be set... see here we have NPEs otherwise :). I think it was just an oversight.

**Comment by i96751414** [comment]
@manovotn My application couldn't have (due to some requirements) any Quarkus specific annotations/calls, hence having the observer of the above example.

Thank you guys for solving this!

**Comment by gsmet** [comment]
@i96751414 expect a fixed version next Wednesday.

**Comment by spolti** [comment]
@gsmet hi, about native mode, what is the recommended way to have it at static_init?
With 
```
Arc.container().instance(ValidatorFactory.class).get(); 
```

it seems that the bean is not validated and no constraint violations are thrown.

Any idea?
