### ISSUE TITLE
Maven artifacts from additional repo not found during quarkus:build

### ISSUE THREAD

**Issue by vonatzigenc** [quarkusio/quarkus#26938]
### Describe the bug

Services with dependencies on Maven artifacts that are not on maven-central cannot be built if the repositories are declared only in `settings.xml` and not in the `pom.xml` project. (If the repo is entered in pom.xml, the build for repos works without credentials.)

Error message:
```
Failed to execute goal io.quarkus:quarkus-maven-plugin:2.11.0.Final:build (default) on project example-artifact: 
Failed to build quarkus application: Failed to bootstrap application in NORMAL mode:
Failed to resolve dependencies for org.acme:example-artifact:jar:999-SNAPSHOT: 
Could not find artifact io.confluent:kafka-avro-serializer:jar:7.2.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

### Expected behavior

Maven artifacts from additional Maven repositories (such as confluent or private repositories) are not found when running mvn quarkus:build.

The behavior only occurs if the repositories are defined exclusively in settings.xml.

With version 2.10.3.Final, the build still worked correctly.

### Actual behavior

Plugin tries to download artifact only from "central" repository and the build breaks with "Could not find artifact" error.

Example:
```
Failed to execute goal io.quarkus:quarkus-maven-plugin:2.11.0.Final:build (default) on project example-artifact: 
Failed to build quarkus application: Failed to bootstrap application in NORMAL mode:
Failed to resolve dependencies for org.acme:example-artifact:jar:999-SNAPSHOT: 
Could not find artifact io.confluent:kafka-avro-serializer:jar:7.2.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

`mvn compile` can resolve the dependency. Only the quarkus-maven-plugin isn't able to locate the jar.

### How to Reproduce?

- Add dependency to an artifact, that isn't on maven-central
- Declare the repository only in settings.xml
- run mvn quarkus:build

Repository in profile in settings.xml:
```
<profiles>
	<profile>
		<id>3rdParty-repos</id>
		<activation>
			<activeByDefault>true</activeByDefault>
		</activation>
		<repositories>
			<!-- Repository for Confluent-->
			<repository>
				<id>confluent</id>
				<url>https://packages.confluent.io/maven/</url>
				<snapshots>
					<enabled>false</enabled>
				</snapshots>
			</repository>
		</repositories>
		<pluginRepositories>
			<pluginRepository>
				<id>confluent-plugins</id>
				<url>https://packages.confluent.io/maven/</url>
				<snapshots>
					<enabled>false</enabled>
				</snapshots>
			</pluginRepository>
		</pluginRepositories>
	</profile>
</profiles>
```

### Quarkus version or git rev

2.11.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

### Additional information

Dependency loading was changed with https://github.com/quarkusio/quarkus/commit/bd30d5cfa498e908e4bea41c508a9da1a820b0b1

AppModel is built only with the `managedRepos` and the repositories of the main-artifact. Other repositories from maven are ignored.

- aggregatedRepos with `mangedRepos` and all maven repos: https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/BootstrapAppModelResolver.java#L254
- Reduce aggregatedRepos to managedRepos and repositories from artifact: https://github.com/quarkusio/quarkus/blob/main/independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/BootstrapAppModelResolver.java#L280-L281

When the reassignment of aggregatedRepos is omitted, `quarkus:build` will work again. But I cannot judge whether this restriction was made deliberately.

**Comment by aloubyansky** [comment]
I'll look into this next week. Thanks for the report.
