### ISSUE TITLE
OpenTelemetry sampler ratio config impossible with yaml configuration

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#26935]
### Describe the bug

I am using the `quarkus-config-yaml` and seems that I am not able to configure the tracer sampler ratio value using smth like:

```
quarkus:
  opentelemetry:
    tracer:
      sampler:
        ratio: 0.01
```

In the [configuration quide](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.opentelemetry.tracer.sampler) the two properties are mentioned, but it seems that above configuration does not work.

```
quarkus.opentelemetry.tracer.sampler     The sampler to use for tracing.  Valid values are off, on, ratio.  Defaults to on. | string | on
quarkus.opentelemetry.tracer.sampler.ratio | double |  
```

I guess `quarkus.opentelemetry.tracer.sampler` should have a string value `ratio` and `quarkus.opentelemetry.tracer.sampler.ratio ` the double value, but that's impossible with yaml.

### Expected behavior

Samples at the given ratio.

### Actual behavior

Samples everything.

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.3, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-41-generic", arch: "amd64", family: "unix"

**Comment by radcortez** [comment]
Use:

```yaml
quarkus:
  opentelemetry:
    tracer:
      sampler:
        ~: ratio
        ratio: 0.01
```

This is documented in the YAML Configuration guide: https://quarkus.io/guides/config-yaml#configuration-key-conflicts

**Comment by ivansenic** [comment]
> Use:
> 
> ```yaml
> quarkus:
>   opentelemetry:
>     tracer:
>       sampler:
>         ~: ratio
>         ratio: 0.01
> ```
> 
> This is documented in the YAML Configuration guide: https://quarkus.io/guides/config-yaml#configuration-key-conflicts

Thanks 🙏

It s great when you learn something new every day..
