### ISSUE TITLE
APIstax client extension

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#26952]
### Description

Hi!
I would like to implement a Quarkus extension for the [APIstax](https://apistax.io) platform. The plan would be to develop an injectable client with which all APIs of the platform are callable.

### Configuration suggestion

```
quarkus.apistax.apikey
```

**Comment by andlinger** [comment]
I can gladly take over the lead of the extension

**Comment by geoand** [comment]
Sounds like a great addition to the Quarkiverse 😉

**Comment by gastaldi** [comment]
@andlinger Once https://github.com/quarkiverse/quarkiverse-devops/pull/67 is merged the https://github.com/quarkiverse/quarkus-apistax/ repository will be created and you should receive an invitation to join the Quarkiverse organization. 
Please follow the checklist in https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created to enable this extension in our tooling, publish docs and integrate with our ecosystem CI.

PS: It would be nice to also somehow integrate this extension with https://openapi-generator.tech/docs/generators/java
