### ISSUE TITLE
Panache ORM  findBy UUID Quarkus >2.8

### ISSUE THREAD

**Issue by cs8898** [quarkusio/quarkus#26972]
### Describe the bug

When searching for an particular entity by UUID as ID in Quarkus > 2.8 there will be no found entity.
This also happens when searching with the find("query",  arg) method.

The Query seems to be good, probably the UUID Serialization is bad.

I also manually set the H2 Dialect.
For my use-case i only used H2...

## Test Outcomes

For testing i created the Repo https://github.com/cs8898/quarkus-panache-uuid-canary

| Version | Test Result |
|---------|-------------|
|2.7.6| :heavy_check_mark: |
|2.8.3| :heavy_check_mark: |
|2.9.2| :x: |
|2.10.4| :x: |
|2.11.1| :x: |

### Expected behavior

It's expected that `findById` and `find` will correctly handle UUIDs.

### Actual behavior

The Entity can't be found by an search for the UUID

### How to Reproduce?

1. clone Repo https://github.com/cs8898/quarkus-panache-uuid-canary
2. switch branches and change version when needed, the repo master is currently `2.7.6`
3. run `./mvnw clean test`

### Output of `uname -a` or `ver`

Linux XXXX 5.18.11-arch1-1 1 SMP PREEMPT_DYNAMIC Tue, 12 Jul 2022 15:40:51 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9) OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

```log
> $ ./mvnw quarkus:info    
[...]
[INFO] Quarkus platform BOMs:
[INFO]   io.quarkus.platform:quarkus-bom:pom:2.11.1.Final
[INFO] 
[INFO] Extensions from io.quarkus.platform:quarkus-bom:
[INFO]   io.quarkus:quarkus-hibernate-orm-panache
[INFO]   io.quarkus:quarkus-arc
[INFO]   io.quarkus:quarkus-resteasy
[INFO]   io.quarkus:quarkus-jdbc-h2
[...]
```

**Comment by cs8898** [comment]
Probaply H2 Driver Update in 2.9.0

H2 got updated from 1.4 to 2.1

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/discussions/25535#discussioncomment-3099579 might help.

**Comment by cs8898** [comment]
# Solution

> @gsmet 
> https://github.com/quarkusio/quarkus/discussions/25535#discussioncomment-3099579 might help.

```
@Column(columnDefinition = "uuid")
```

Did the job https://github.com/cs8898/quarkus-panache-uuid-canary/tree/dependabot/maven/quarkus.platform.version-2.11.1.Final Test is now green :heavy_check_mark:

Seems i have to review the changes and migrate the columns

**Comment by gsmet** [comment]
For the record, the native H2 `uuid` type be the default mapping with Hibernate ORM 6 (it's not possible to change the default mapping easily in ORM 5) so when Quarkus moves to Hibernate ORM 6, it will be automatic.

It's still a few months away though so in the meantime the best way to fix it is to define the type manually with `@Column(columnDefinition = "uuid")`.
