### ISSUE TITLE
Jakarta - EE 10 - Hibernate ORM 6 upgrade and JPA 3.1

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#26986]
@Sanne is leading this effort.

Note that once we have Hibernate ORM 6 integrated, we will have to:
- integrate a new version of Hibernate Reactive based on 6
- adjust the Hibernate Search extensions
- figure out if the Envers extension needs adjustments
- figure out impact on all downstream extensions
- update quickstarts, docs

**Comment by guitcastro** [comment]
Any updates on this?

**Comment by Sukitly** [comment]
@manovotn 
What is the difference between jakarta-10-cdi, jakarta-10-jaxrs and jakarta-rewrite?
And when Quarkus will finally be compatible with JakartaEE 10?
Thanks.

**Comment by manovotn** [comment]
@Sukitly there is already an alpha release running on Jakarta EE10, look for `3.0.0.Alpha1`
I don't know the exact state of what's in it and what's not yet ready though.

@gsmet do we have some public issue or roadmap that would capture jakarta EE 10 readiness and some rough dates?

>  What is the difference between jakarta-10-cdi, jakarta-10-jaxrs and jakarta-rewrite?

Currently, the jakarta variant is built automatically by performing a package and dependency transformation and then applying a few specific commits on top. `jakarta-10-cdi` and `jakarta-10-jaxrs` are an example of those specific commits that are cherry picked for jakarta build. `jakarta-rewrite` is the final result of the rewrite and is nightly updated.

**Comment by manovotn** [comment]
Ah found it, take a look at this post @Sukitly - https://groups.google.com/g/quarkus-dev/c/xjHIBk6Mx7k/m/4sfjhP6IAwAJ

**Comment by geoand** [comment]
Closing as this was delievered in https://github.com/quarkusio/quarkus/pull/31235
