### ISSUE TITLE
Jakarta - EE 9 - Narayana LRA Jakarta implementation missing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#26985]
We currently don't have a Narayana LRA Jakarta artifact released on Maven Central and we are building something locally from a branch.

@mmusgrov is currently working on it and hopefully the artifact will land soon, creating the issue to keep track of the integration.

Note:
- we need to upgrade Narayana
- integrate OpenRewrite recipes to adjust the artifact
- remove the local building from `jakarta/prepare.sh`

**Comment by mmusgrov** [comment]
@gsmet I've tested the snapshot versions of the jakarta dependencies and they work fine.
The blockage now is fixing some unrelated WildFly/JDK 17 issues (WildFly recently moved over to jakarta native) and we don't have the ability to release individual components (I am looking into releasing a narayana alpha with reduced testing against the WildFly main branch).
