### ISSUE TITLE
Jakarta - EE 10 - RESTEasy Reactive and JAX-RS 3.1

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#26987]
For now, we are working on the EE 9 upgrade which only rewrites the packages. This doesn't require any big adjustments in RESTEasy Reactive.

EE 10 introduces new features with JAX-RS 3.1 though.

If there are features in JAX-RS 3.1 that we want to support in RESTEasy Reactive, we need to:
- implement the features we want
- probably add the TCK tests that were added to test these features to our fork of the TCK

**Comment by geoand** [comment]
Closing as for now as we have done the minimum to get it working
