### ISSUE TITLE
Add QuarkusBeforeTestExecutionCallback

### ISSUE THREAD

**Issue by Cs4r** [quarkusio/quarkus#26999]
### Description

Hello,

As we have in JUnit5 a callback to be invoked just before the test execution, but after BeforeEach (named `org.junit.jupiter.api.extension.BeforeTestExecutionCallback` indeed). It would be good to incorporate to quarkus-junit5 library a callback named `QuarkusBeforeTestExecutionCallback`  that has similar behaviour. 

e.g: 

```
public class MyQuarkusBeforeTestExecutionCallback implements QuarkusBeforeTestExecutionCallback {

    @Override
    public void beforeTest(QuarkusTestMethodContext context) {
        System.out.println("Just before executing " + context.getTestMethod());
    }
}
```

Regards.

**Comment by geoand** [comment]
Hi,

The current callbacks are modeled after JUnit's test lifecycle. This doesn't seem to have an analog, or am I mistaken?

**Comment by Cs4r** [comment]
Currently there are 4 callbacks supported by quarkus-junit:

- `io.quarkus.test.junit.callback.QuarkusTestBeforeClassCallback`
- `io.quarkus.test.junit.callback.QuarkusTestAfterConstructCallback`
- `io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback`
- `io.quarkus.test.junit.callback.QuarkusTestAfterEachCallback`


The analog would be `QuarkusBeforeTestExecutionCallback`, it would be called after `@BeforeEach` but before `@Test`.

If you still have doubts, don't hesitate to ask :)

**Comment by Cs4r** [comment]
Yes, JUnit5 has that feature, the callback name is `org.junit.jupiter.api.extension.BeforeTestExecutionCallback`.

The use case is about having a method that is invoked before the `@Test`, mainly to fill some variables/pass some parameters before the test executes. It's like a `@BeforeEach`.

**Comment by geoand** [comment]
Interesting, I did not know about that one.

**Comment by geoand** [comment]
Would you be willing to try out https://github.com/quarkusio/quarkus/pull/27019 and see if it fits your needs?

**Comment by Cs4r** [comment]
It seems it's what we are looking for. However, I am finding trouble building a jar with the changes

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/pull/27019#issuecomment-1199083728 for instructions on how to test the Pull Request

**Comment by GavinRay97** [comment]
Just out of curiosity -- when would you use this instead of `@BeforeEach`?
I didn't know this existed either

**Comment by Cs4r** [comment]
@GavinRay97:


In the company I work for we have a library on top of JUnit 5 to create more readable tests. In our library we have three annotations for methods: `@Given`, `@When` and `@Then` and here is an example of how we use them:


```
@GivenWhenThen // Our own extension 
public class ExampleTest {

     int number;

    @Given // This is equivalent to @BeforeEach
    void aCondition(){
          number = 72;
    }

    @When // This is executed just before @Test, but after @BeforeEach
    void performingAnAction(){
           number = number * 4;
    }

    @Then // This is equivalent to @Test
    void assertEffects(){
         assertThat(number).isEqualTo(288);
    }
}


```
