### ISSUE TITLE
Kubernetes extension for Command line apps

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#27024]
### Description

I'm developing a command line Quarkus application that I want to execute as a Kubernetes Job. 

If I add the Kubernetes extension, it's not creating a Kubernetes Job but a Deployment. Also, if I try to configure the `kind` through `application.properties`, it says that only Deployment or StatefulSet is possible.

I think as a first step, it would be nice to be able to set the kind Job. But as a second step, it would be nice to detect the `QuarkusMain` annotation and automatically create a `Job`.

**Comment by geoand** [comment]
I like the idea, should be doable

**Comment by Sgitario** [comment]
> I like the idea, should be doable. @Sgitario WDYT?

It's now possible to implement this as we are now using Dekorate 2.11 which already supports the generation of Job resources. 
If you don't mind, I will work in this ticket.
