### ISSUE TITLE
MongoDB present when not needed

### ISSUE THREAD

**Issue by kyngs** [quarkusio/quarkus#27038]
### Describe the bug

I have the following Gradle configuration:
```gradle
plugins {
    id 'java'
    id 'io.quarkus' version '2.11.1.Final'
}

repositories {
    mavenCentral()
    mavenLocal()
    gradlePluginPortal()
}

dependencies {
    implementation project(':Core') //This project contains (and exposes) the org.mongodb:mongodb-driver-sync:4.7.0 dependency

    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-reactive-routes'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

task prepareKotlinBuildScriptModel { // I have no idea why, but this is necessary to make Gradle with IJ work
}
```

However, when I build with quarkusBuild, the result does contain some older version of the MongoDB java driver (Features from 4.7.0 are missing)

It appears, that the quarkus core bundles in its own version of the MongoDB java driver.

### Expected behavior

My dependency gets included in the final jar.

### Actual behavior

Quarkus' (unneeded) dependency gets included in the final jar.

### How to Reproduce?

1. Setup a basic quarkus project with Gradle
2. Build it with quarkusBuild
3. Observe, that the MongoDB java driver is present for no reason

### Output of `uname -a` or `ver`

Linux 5.18.15-arch1-1

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment (build 17.0.4+8) OpenJDK 64-Bit Server VM (build 17.0.4+8, mixed mode)

### GraalVM version (if different from Java)

Not applicable

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

In my specific case, this issue could also be solved by updating the bundled-in mongo java driver to 4.7.0.

**Comment by geoand** [comment]
I would say this is expected behavior as the Quarkus BOM dictates what the version of the MongoDB driver. 

@glefloch do you agree?

**Comment by glefloch** [comment]
Right, the ˋenforcedPlatform` will override all dependency version. You could use a simple ˋplatform` dependency to the bom but we cannot guarantee everything will be compatible with quarkus.

**Comment by kyngs** [comment]
Thanks for your help.
