### ISSUE TITLE
Support multiple AsyncObserverExceptionHandler implementations

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#27047]
### Description

We could leverage the [@Inject @All List](https://quarkus.io/guides/cdi-reference#injecting-multiple-bean-instances-intuitively) functionality and take `AsyncObserverExceptionHandler` with highest priority.

**Comment by manovotn** [comment]
Looking at the code, we now treat `AsyncObserverExceptionHandler` as classic bean and even perform a[ validation on ambiguity](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java#L801-L816) at build time.

We could utilize `@Inject @All` and hence avoid throwing that exception but how is that useful?
I think in the rare case where user application contains several implementations of `AsyncObserverExceptionHandler`, it is actually useful to see the error and address it (usually by deciding which one to use and making it a prioritized alternative). Or is there something I am missing?
Also, I haven't checked how do we order beans in case they have equal priority, but I assume that would be based on name?

**Comment by mkouba** [comment]
> We could utilize @Inject @All and hence avoid throwing that exception but how is that useful?

I probably stumbled upon a use case where this was needed but I don't remember the details TBH.

> Also, I haven't checked how do we order beans in case they have equal priority, but I assume that would be based on name?

I believe that it's undefined.

Let's close this issue for now and reopen/file a new one if this problem comes along.
