### ISSUE TITLE
Create a remote dev setup goal

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#2706]
**Description**
Currently, to use the remote dev awesomeness, some manual steps are required:
1. Create a Dockerfile for remote dev that includes sources, mvnw etc.
2. Configure the secret in the application.properties
3. Add a bunch of extensions that enable remote dev mode  (e.g. web sockets etc).

It would be awesome if there was a simple goal that would automate all the above.

**Comment by geoand** [comment]
Having a maven goal to set this up in an existing project would be great. Or maybe this should be setup OOTB when a project is created?

**Comment by jglick** [comment]
As noted in #1720, the [documentation](https://quarkus.io/guides/maven-tooling#remote-development-mode) is rather thin. What is involved in

> Start Quarkus in dev mode on the remote host.

exactly?

**Comment by stuartwdouglas** [comment]
I don't think this is really relevant any more, as the process is much simpler with the new design.
