### ISSUE TITLE
Jakarta - EE 9 - Native - Quartz and JTA

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27065]
Quartz has a JTA layer and it relies on the `javax` classes.

Unfortunately the latest Quartz version dates from October 2019 so I wonder if it's still maintained.
There are a few commits that are more recent in the repository though.

I don't know if we are supporting this JTA setup in Quarkus.

**Comment by mkouba** [comment]
I found this comment: ["2.4.0 should be released in the near future."](https://github.com/quartz-scheduler/quartz/issues/409#issuecomment-1058585439). However, the [2.4.0 milestone](https://github.com/quartz-scheduler/quartz/milestone/6?closed=1) does not seem to contain anything Jakarta-related.

> I don't know if we are supporting this JTA setup in Quarkus.

I think that `quarkus.quartz.store-type=JDBC_TX` does rely on JTA...

**Comment by gsmet** [comment]
I will reuse the same technique @Sanne used for the Db2 JDBC so we can have this fixed while we wait for a Quartz release.
