### ISSUE TITLE
@QuarkusMain not executed with Lambda Function at AWS

### ISSUE THREAD

**Issue by claudiney-silva** [quarkusio/quarkus#27073]
### Describe the bug

I am building a Lambda Function with Quarkus Funqy. I have a class annoted with @QuarkusMain to do statics initilization for Provisioned concurrency.

@QuarkusMain class is executed with `mvn quarkus:dev`, but is not executed when Lambda function is called or initilized.

My code looks like below:

```java
@QuarkusMain
public class Main {
    public static void main(String... args) {
        Quarkus.run(MyApp.class, args);
    }

    public static class MyApp implements QuarkusApplication {

        @Override
        public int run(String... args) throws Exception {
            System.out.println("Static initilization");
            Quarkus.waitForExit();
            return 0;
        }
    }
}

public class Sample {

   @Funq
   public String sample(JsonNode event) {
      return "OK";
   }

}
```

With `mvn quarkus:dev` it runs properly
![intellij](https://user-images.githubusercontent.com/74375073/182277581-2cdbe9cc-6a4d-4ba6-8c72-1c165af35b75.png)

But on AWS not
![aws](https://user-images.githubusercontent.com/74375073/182277622-a351fb8e-fae6-4afd-aae1-80e549a7a367.png)

The handler configured: io.quarkus.funqy.lambda.FunqyStreamHandler::handleRequest

I already tested with Quarkus 2.10.0 and 2.11.1.

Thanks!

### Expected behavior

I expect that on lambda cold start, the @QuarkusMain should be executed.

### Quarkus version or git rev

2.10.0

**Comment by michalvavrik** [comment]
Hello @claudiney-silva, I think (please happily ignore what I think as I'm not an expert here!) that Funqy functions don't have lifecycle managed (they are starting and stopping the application themselves), therefore main is never called or some lifecycle events (like ShutdownEvent) are never fired. Invokine Application directly should make boot startup faster. 

Judging from `io.quarkus.arc.runtime.ArcRecorder#handleLifecycleEvents` though, I think StartupEvent could be fired, but I supposed you tried it and it didn't work?
