### ISSUE TITLE
Hot replacement upon incoming/outgoing Kafka message

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2709]
Details of this are a bit blurry to me, but essentially, what I'd want is to have hot code replacement without having to refresh an application's web view when

* receiving an inbound Kafka message after a code change
* emitting a Kafka message e.g. from af `Flowable` after a code change

Perhaps it could be expanded to work with Reactive Messaging in general, but using Kafka made me wish for this. I might also be able to help out with it provided someone can give me some general hints on where to hook this in.

**Comment by gsmet** [comment]
Closing in favor of https://github.com/quarkusio/quarkus/issues/3217 .
