### ISSUE TITLE
Support `ignoreMigrationPatterns` config in Flyway

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#27099]
### Description

As requested in https://github.com/quarkusio/quarkus/pull/27096#discussion_r936069360, Flyway supports configuring certain patterns to ignore migrations during validate and repair.
It would be nice to be able to specify that in the Flyway Config. 

More info: https://flywaydb.org/documentation/configuration/parameters/ignoreMigrationPatterns

### Implementation ideas

Include a `quarkus.flyway.ignore-migration-patterns` in the [FlywayDataSourceRuntimeConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceRuntimeConfig.java) and create a test for it.

See [`c31af2a` (#27096)](https://github.com/quarkusio/quarkus/pull/27096/commits/c31af2a05ffcec623762812a6176fafc62434d7c) for an example

**Comment by geoand** [comment]
Seems reasonable to me.

**Comment by gsmet** [comment]
@tmihalac might be a good one for you.

**Comment by tmihalac** [comment]
> @tmihalac might be a good one for you.

Working on it

**Comment by tmihalac** [comment]
@gsmet @gastaldi I just want to point out that if you look at the documentation you pointed out to: https://flywaydb.org/documentation/configuration/parameters/ignoreMigrationPatterns

You can see that `repeatable` and
 `versioned` migration types are supported only by the `flyway teams` product but we are dependent on the community version.
