### ISSUE TITLE
Add metrics for Reactive REST Client

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#27102]
### Description

The Reactive REST Client is what we promote to users for making downstream HTTP calls.
Currently there is no micrometer metrics integration for this, but it would be awesome to have metrics for each named client so users can easily identify issues with each service separately.

### Implementation ideas

At a very high level, we'll need to plug in a proper implementation of `HttpClientMetrics` that will be able to disambiguate between calls originating from the REST client and delegate to micrometer.

**Comment by geoand** [comment]
If we agree on this, I can start something towards the end of August (when coming back from PTO) that we can then iterate on.

**Comment by ebullient** [comment]
Yes. There are solid patterns to follow here. Shouldn't be difficult.

**Comment by geoand** [comment]
It's probably a little more complicated than the server metrics handling because we need to incorporate information for each specific named rest client, but it's almost certainly doable.

**Comment by geoand** [comment]
I have been talking with @ebullient about this. It seems like a lot of the functionality is already there, we just need to see if it makes sense to break things down further

**Comment by geoand** [comment]
I am going to close this as the REST Client already has some metrics and for more detailed information tracing information already provides what I had in mind
