### ISSUE TITLE
smallrye-opentracing issue with reactive endpoints

### ISSUE THREAD

**Issue by kjeldpaw** [quarkusio/quarkus#27107]
### Describe the bug

Hi, I have an issue using the quarkus-smallrye-opentracing extension together with quarkus-resteasy-reactive. When I have an endpoint returning 204 (no content) the span is not finished. When I look in the source for the quarkus-smallrye-opentracing extension I have only found that spans are finished in io.smallrye.opentracing.contrib.jaxrs2.serialization.TracingInterceptor which might explains why I'm not able to find traces for endpoints not returning entities. 

### Expected behavior

Able to view traces for endpoints created with quarkus-resteasy-reactive not returning entities in the Jaeger UI:

`@GET
    @Path("/hello")
    public void hello() {
    }`

### Actual behavior

Only able to see traces from endpoints returning entities in the responses

### How to Reproduce?

Create an endpoint:

``@GET
    @Path("/hello")
    public void hello() {
    }``

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

**Comment by radcortez** [comment]
OpenTracing is mostly abandoned. We even had to copy that code to SmallRye OpenTracing from OpenTracing to be able to migrate it to Jakarta, because no one is maintaining the original repos anymore.

It is unlikely that we will focus any effort in OpenTracing. We do accept PR's.

Our recommendation is to move and use OpenTelemetry.

**Comment by kjeldpaw** [comment]
We have decided to move to OpenTelemetry due to the situation with OpenTracing
