### ISSUE TITLE
Upgrade from Codehaus Groovy 3.x to Apache Groovy 4.x

### ISSUE THREAD

**Issue by apupier** [quarkusio/quarkus#27111]
### Description

Groovy 4.0.0 has been released at the beginning of 2022. it might be nice to move to the latest version.

There is a long list of features and bug fixes http://groovy-lang.org/changelogs/changelog-4.0.0.html

Based on https://groovy.apache.org/versioning.html 3.x will have one or two bugfixes release (in fact already 3 happened). So good chances that there will be only security release of 3.x soon.

**Comment by gsmet** [comment]
We haven't upgraded REST Assured and thus Groovy because of https://issues.apache.org/jira/browse/GROOVY-10307 .

See https://github.com/quarkusio/quarkus/pull/24569 when .

But is Quarkus enforcing the Groovy version somewhere? I don't see it in our BOM.

**Comment by gsmet** [comment]
This is done in Quarkus 3, together with the update to recent REST Assured versions.

FWIW, Groovy 4 performances are still not on par with Groovy 3 performances but they are making progress.

**Comment by gsmet** [comment]
For reference: https://github.com/quarkusio/quarkus/pull/31195
