### ISSUE TITLE
The exception reported after using the @Valid annotation does not enter the global exception handling

### ISSUE THREAD

**Issue by TheBlindM** [quarkusio/quarkus#27148]
### Describe the bug

The exception reported after using the @Valid annotation does not enter the global exception handling

```java
@Provider
public class ErrHandle implements ExceptionMapper<Exception> {
    @Inject
    ObjectMapper objectMapper;


    @Override
    public Response toResponse(Exception exception){
        log.error("失败 to handle request", exception);
        int code = 500;
        if (exception instanceof WebApplicationException) {
            code = ((WebApplicationException) exception).getResponse().getStatus();
        }
        BaseResponse response = new BaseResponse();
        response.setCode(code);
        response.setMessage(exception.getMessage());

        if (log.isDebugEnabled()) {
            response.setDevMessage(exception.getMessage());
        }
        return Response.ok()
                .entity(JSONUtil.toJsonStr(response))
                .build();
    }
}
```

actual response

```json
{
    "exception": null,
    "propertyViolations": [],
    "classViolations": [],
    "parameterViolations": [
        {
            "constraintType": "PARAMETER",
            "path": "create.addHostDTO.osType",
            "message": "系统不能为空",
            "value": ""
        }
    ],
    "returnValueViolations": []
}
```

### Output of `java -version`

Java version info: '17.0.4+11-LTS-jvmci-22.2-b05'

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\NINGMEI\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 17.0.4, vendor: Oracle Corporation, runtime: C:\Users\NINGMEI\.jdks\graalvm-ee-java17-22.2.0 Default locale: zh_CN, platform encoding: GBK OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Are you using RESTEasy Classic or RESTEasy Reactive? 

It would be great if you attached a sample application that exhibits the problematic behavior you mention in the ticket.

**Comment by geoand** [comment]
I get you are not using Reactive capabilities, but what JAX-RS stack are you using, `quarkus-resteasy` or `quarkus-resteasy-reactive`?

In any case, see my comment above about providing a sample project. Otherwise we'll be shooting in the dark.

**Comment by geoand** [comment]
What you are seeing is correct JAX-RS behavior because Quarkus provides `io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyViolationExceptionMapper` which handles the exception.

If you want to handle the `ValidationException` yourself, you need to change `ErrHandle` to handle `ValidationException` instead of `Exception`
