### ISSUE TITLE
InterceptorBindingRegistrarBuildItem not registering Annotation for RestClient

### ISSUE THREAD

**Issue by forsti0506** [quarkusio/quarkus#27151]
### Describe the bug

Hello,

if I register a Annotation in the BuildStep with an "InterceptorBindingRegistrarBuildItem" this added Annotation is not working if I annotate a RestClient method with the same one. For example:

`javax.Cache.annotation.CacheResult`

Is this a bug

### Expected behavior

All registerted Annotations in the InterceptorBindingRegistrarBuildItem are working in every context

### Actual behavior

For example @CacheResult added with "InterceptorBindingRegistrarBuildItem" is ignored in a RestClient

### How to Reproduce?

1. Add a BuildStep with "InterceptorBindingRegistrarBuildItem" and register there @CacheResult
2. Make an RestClient and annotate an methode with @CacheResult
3. Make a breakpoint in your used CacheImplentation (there should be an @CacheResult Interceptor)
4. See that the annotation is ignored and the interceptor is not invoked

### Output of `java -version`

17

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
Given the complexity of what you are describing, the best way for us to determine what is going on is for this issue to amended to include a sample extension + application.

**Comment by mkouba** [comment]
Georgios is right, we'll need a simple reproducer. Also what kind of rest client do you use?

BTW the usage of CDI interceptors on interfaces is somewhat non-standard, from the CDI spec POV (although the MicroProfile spec explicitly requires it to work).
