### ISSUE TITLE
Upx exception under windows

### ISSUE THREAD

**Issue by TheBlindM** [quarkusio/quarkus#27178]
### Describe the bug

Produced artifacts:
 D:\study\demo1\target\demo1-1.0-SNAPSHOT-native-image-source-jar\demo1-1.0-SNAPSHOT-runner.build_artifacts.txt (txt)
 D:\study\demo1\target\demo1-1.0-SNAPSHOT-native-image-source-jar\demo1-1.0-SNAPSHOT-runner.exe (executable)
========================================================================================================================
Finished generating 'demo1-1.0-SNAPSHOT-runner' in 2m 19s.
[ERROR] [io.quarkus.deployment.pkg.steps.UpxCompressionBuildStep] Unable to compress the native executable. Either install `upx` from https://upx.github.io/ on your machine, or enable in-container build using `-Dquarkus.native.container-build=true`.

Environment variables have been declared

![image](https://user-images.githubusercontent.com/48701152/183386942-19cabe39-d013-4b81-a05e-de1c38b263b6.png)

### Output of `java -version`

Java version info: '17.0.4+11-LTS-jvmci-22.2-b05'

### GraalVM version (if different from Java)

GraalVM 22.2.0 Java 17 EE'

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\NINGMEI\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 17.0.4, vendor: Oracle Corporation, runtime: C:\Users\NINGMEI\.jdks\graalvm-ee-java17-22.2.0 Default locale: zh_CN, platform encoding: GBK OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Is `upx` part of the `PATH` variable?

**Comment by geoand** [comment]
What's wrong with it?

**Comment by gastaldi** [comment]
> When I double-click the exe, the windows cmd flashes by, and the exe double-click can run normally when upx is not used

Do you see any stacktrace when running the `.exe` in the CMD?

**Comment by gastaldi** [comment]
Can you provide a reproducer project? Or fill in the steps to reproduce?

**Comment by geoand** [comment]
Thanks a lot for the link @n-kremer! 

In light of this information, I'll close this issue as an `upstream` issue
