### ISSUE TITLE
AutoAddScopeBuildItem.isUnremovable() is ignored

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#27194]
https://github.com/quarkusio/quarkus/discussions/27103

An additional `UnremovableBeanBuildItem` should be used as a workaround

Thanks @azzazzel for spotting the issue!

**Comment by azzazzel** [comment]
Thank you for picking this up so quickly @mkouba !

Just to clarify on the 

> An additional `UnremovableBeanBuildItem` should be used as a workaround

is [this](https://github.com/azzazzel/quarkus-unremovable-issue/commit/35b149b1eda58f5c33e1aae5e3bd55f53f838425) what you had in mind or is there a better way to do it?

**Comment by mkouba** [comment]
> is [this](https://github.com/azzazzel/quarkus-unremovable-issue/commit/35b149b1eda58f5c33e1aae5e3bd55f53f838425) what you had in mind or is there a better way to do it?

Yes, something like this should do it.
