### ISSUE TITLE
New Redis API, too many subscriber timeout

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#27209]
### Describe the bug

edited -> see reproducer

### Expected behavior

We are subscribed

### Actual behavior
 Error

### How to Reproduce?

Create a quarkus app with version 2.11.1.Final 
Use the given files

### Output of `java -version`

11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8

**Comment by Plawn** [comment]
After some more work, this however seems to work

```java
package org.cnje.kiwi.config;

import java.util.Collection;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import org.cnje.kiwi.event.dto.event.EventDto;
import org.cnje.kiwi.organizations.dto.BasicOrgDto;
import org.cnje.kiwi.organizations.dto.OrganizationDto;
import org.cnje.kiwi.users.dto.user.BasicUserWithHistoriesDto;
import org.cnje.kiwi.users.dto.user.UserDto;
import org.cnje.utils.cache.HttpCacheHandler;
import org.cnje.utils.cache.store.redis.RedisStoreProvider;
import org.cnje.utils.cache.store.redis.RedisStoreProvider.InsufficientNamespaceNamesAvailable;

import io.quarkus.runtime.Startup;

/**
 * This class produces the httpCacheHandlers for the app, they are used to keep track of the
 * last-modified date in order to provide 304 Not Modified handling on the client side <br>
 * This enables the server to send less data over the wire and to keep the data consumption of the
 * client low
 */
@Startup
@ApplicationScoped
public class HttpCacheProvider {

    private final HttpCacheHandler<Collection<BasicOrgDto>, Long> subOrgCache;
    private final HttpCacheHandler<OrganizationDto, Long> orgCache;
    private final HttpCacheHandler<EventDto, Long> eventCache;
    private final HttpCacheHandler<UserDto, Long> userCache;
    private final HttpCacheHandler<Collection<BasicUserWithHistoriesDto>, Long> orgUserHistoriesCache;
    
    public HttpCacheProvider(final RedisStoreProvider redisProvider) throws InsufficientNamespaceNamesAvailable {
        this.subOrgCache = new HttpCacheHandler<>(redisProvider.getStore());
        this.orgCache = new HttpCacheHandler<>(redisProvider.getStore());
        this.eventCache = new HttpCacheHandler<>(redisProvider.getStore());
        this.userCache = new HttpCacheHandler<>(redisProvider.getStore());
        this.orgUserHistoriesCache = new HttpCacheHandler<>(redisProvider.getStore());
    }

    @Named("orgCache")
    @ApplicationScoped
    public HttpCacheHandler<OrganizationDto, Long> makeOrgCache() throws InsufficientNamespaceNamesAvailable {
        return orgCache;
    }

    @Named("subOrgCache")
    @ApplicationScoped
    public HttpCacheHandler<Collection<BasicOrgDto>, Long> makeSubOrgCache() throws InsufficientNamespaceNamesAvailable {
        return subOrgCache;
    }

    @Named("eventCache")
    @ApplicationScoped
    public HttpCacheHandler<EventDto, Long> makeEventCache() throws InsufficientNamespaceNamesAvailable {
        return eventCache;
    }

    @Named("userCache")
    @ApplicationScoped
    public HttpCacheHandler<UserDto, Long> makeUserCache() throws InsufficientNamespaceNamesAvailable {
        return userCache;
    }

    @Named("orgUserHistoriesCache")
    @ApplicationScoped
    public HttpCacheHandler<Collection<BasicUserWithHistoriesDto>, Long> makeOrgUserHistoriesCache() throws InsufficientNamespaceNamesAvailable {
        return orgUserHistoriesCache;
    }
}

```

**Comment by Plawn** [comment]
Hello, after even more debugging I found out, that the issue is having too many listeners, or at list the issue appears when i have 5 or more listeners

**Comment by gsmet** [comment]
Better provide a full reproducer in the form of a small Maven project.

**Comment by Plawn** [comment]
yes will do 👍

**Comment by Plawn** [comment]
Hello, 
Here is the reproducer

https://github.com/Plawn/redis-quarkus-reproducer

here is the main test file

https://github.com/Plawn/redis-quarkus-reproducer/blob/master/src/main/java/org/acme/HttpCacheProvider.java

To test: just mvn quarkus:dev

When having too many listener there is a timeout

**Comment by cescoffier** [comment]
This is kind of expected. Subscribers need to hold a connection to the Redis server (that's the Redis protocol). However, by default, the connection pool is set to have only six connections.  

So you should restructure your application to reduce the number of connections (use a single subscribers listening to multiple keys) or increase the number of connections:

```
quarkus.redis.max-pool-size=....
```
```

**Comment by Plawn** [comment]
Ok I see, in the redis documentation it stated that up to 10 000 listeners could listen to the same channel, so I did not expect this kind of issue. 
Thanks !
However is it expected to only be able to start listening at the start of the Quarkus app ? If I'm not listening inside a Bean annotation with @Startup the subscription won't work because of a null context

**Comment by cescoffier** [comment]
Can you give more details about this startup issue? 
Do you mean you can only register subscribers during the startup of the application?

**Comment by Plawn** [comment]
Hello !

Yes, If I don't mark the bean creating the redis subscriber with @Startup (like in the example), I will have a vertx null context exception.

**Comment by cescoffier** [comment]
Can you provide a reproducer? The Redis data source requires Vert.x but the Vert.x instance is created quite early in the process.

**Comment by cescoffier** [comment]
I believe I reproduced it:

```
2022-08-18 11:25:20,674 WARN  [io.net.uti.con.AbstractEventExecutor] (vert.x-eventloop-thread-11) A task raised an exception. Task: io.vertx.core.impl.EventLoopContext$$Lambda$1042/0x00000008007fef90@1dac7cf9: java.lang.IllegalArgumentException: Parameter 'context' may not be null
        at io.smallrye.common.constraint.Assert.checkNotNullParamChecked(Assert.java:32)
        at io.smallrye.common.constraint.Assert.checkNotNullParam(Assert.java:26)
        at io.smallrye.common.vertx.VertxContext.isDuplicatedContext(VertxContext.java:114)
        at io.smallrye.common.vertx.VertxContext.getOrCreateDuplicatedContext(VertxContext.java:31)
        at io.quarkus.redis.runtime.datasource.ReactivePubSubCommandsImpl$AbstractRedisSubscriber.lambda$subscribe$2(ReactivePubSubCommandsImpl.java:149)

```

**Comment by cescoffier** [comment]
(and it's likely a bug)

**Comment by Plawn** [comment]
> I believe I reproduced it:
> 
> ```
> 2022-08-18 11:25:20,674 WARN  [io.net.uti.con.AbstractEventExecutor] (vert.x-eventloop-thread-11) A task raised an exception. Task: io.vertx.core.impl.EventLoopContext$$Lambda$1042/0x00000008007fef90@1dac7cf9: java.lang.IllegalArgumentException: Parameter 'context' may not be null
>         at io.smallrye.common.constraint.Assert.checkNotNullParamChecked(Assert.java:32)
>         at io.smallrye.common.constraint.Assert.checkNotNullParam(Assert.java:26)
>         at io.smallrye.common.vertx.VertxContext.isDuplicatedContext(VertxContext.java:114)
>         at io.smallrye.common.vertx.VertxContext.getOrCreateDuplicatedContext(VertxContext.java:31)
>         at io.quarkus.redis.runtime.datasource.ReactivePubSubCommandsImpl$AbstractRedisSubscriber.lambda$subscribe$2(ReactivePubSubCommandsImpl.java:149)
> ```

Yes I exactly got this error !

**Comment by cescoffier** [comment]
@Plawn see https://github.com/quarkusio/quarkus/pull/27361. 

Closing this issue, as our discussion is about another issue. Please use #27361 to discuss that other issue.
