### ISSUE TITLE
RunOnVertxContext annotation duplicateContext is not taken into account if the annotation is on the class

### ISSUE THREAD

**Issue by luc-rovio** [quarkusio/quarkus#27212]
### Describe the bug

I'm using the `@RunOnVertxContext(duplicateContext = true)` annotation in my tests since the tests calls a Hibernate reactive data source. This works when I put the annotation on each method, but it doesn't work when I put the annotation on the class.

Looking at `RunOnVertxContextTestMethodInvoker`, it appears that we're looking for the annotation on the class and method in `supportsMethod` but we only look at the method annotation in `shouldContextBeDuplicated`.

### Expected behavior

Running a test on a Hibernate reactive repository with a `@RunOnVertxContext(duplicateContext = true)` annotation on the test class should succeed.

### Actual behavior

Running the test yields the following message:
```
Can't get the context safety flag: the current context is not a duplicated context
```

### How to Reproduce?

```java
@QuarkusTest
@RunOnVertxContext(duplicateContext = true)
class MinCaseTest {
    @Inject
    TestRepository testee;

    @Test
    void testRetrieveAll(UniAsserter asserter) {
        asserter.assertThat(() -> testee.retrieveAll(),
                result -> assertEquals(0, result.size()));
    }
}
```
Where TestRepository has the following:
```java
    @Inject
   Mutiny.SessionFactory sf;

   public Uni<TestEntity> retrieveAll() {
      return sf.withTransaction((s, t) -> s.createQuery(...).getResultList());
   }
```
### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1826]

### Output of `java -version`

openjdk version "17" 2021-09-14 LTS OpenJDK Runtime Environment Corretto-17.0.0.35.1 (build 17+35-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.0.35.1 (build 17+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven (Version 3.8.1)

### Additional information

Putting the annotation on each method is a valid workaround so this is not a blocker. The current behavior looks a bit inconsistent (compared to TestReactiveTransaction)

**Comment by gsmet** [comment]
Maybe you could provide a pull request?

See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md

**Comment by luc-rovio** [comment]
> Maybe you could provide a pull request?
Sure!

**Comment by geoand** [comment]
Thanks! Feel free to ping me for a review

**Comment by luc-rovio** [comment]
@geoand Please take a look at my pull request. I see the following message: "First-time contributors need a maintainer to approve running workflows."

**Comment by geoand** [comment]
Thanks for the PR!
