### ISSUE TITLE
Implement BeanManger#isPassivatingScope

### ISSUE THREAD

**Issue by tandraschko** [quarkusio/quarkus#2721]
Some frameworks like JSF or DeltaSpike use bm#isPassivatingScope to check if the scope is passivating, and based on this value, the CustomContext#get implementation checks the bean instanceof PassivationCapable (https://github.com/apache/myfaces/blob/4619df600ba130f6e6f8d26d2e7c960d2d36f0de/impl/src/main/java/org/apache/myfaces/cdi/util/AbstractContext.java#L46)

If quarkus would implement isPassivatingScope with "return false" per default, such frameworks as MyFaces don't need to introduce config flags.
It maybe be a bit nicer as throwing a UnsupportedOperationException.

WDYT @mkouba?

**Comment by mkouba** [comment]
`isPassivatingScope()` returning `false` is probably reasonable because passivation is intentionally ignored ATM. Would you care to send a PR?

**Comment by tandraschko** [comment]
@mkouba created!
