### ISSUE TITLE
UriInfo.resolve always returns null with resteast-reactive

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#27221]
### Describe the bug

After switching from RESTeasy Classic to the reactive counterpart, `UriInfo.resolve` does not work anymore and always returns `null`. `UriInfo.getBaseUri().resolve` still works, though.

### Expected behavior

`UriInfo.resolve` does not return `null`, similar to the behavior of RESTeasy classic.

### Actual behavior

`UriInfo.resolve` always returns `null`.

### How to Reproduce?

https://github.com/languitar/resteasy-reactive-uriinfo-resolve-bug

Start the project in dev mode

Afterwards, call the implemented `/hello` endpoint:

```
❯ curl http://localhost:8080/hello
UriInfo.resolve: null
UriInfo.getBaseUri().resolve: http://localhost:8080/test⏎   
```
Here's the implementation of the endpoint: https://github.com/languitar/resteasy-reactive-uriinfo-resolve-bug/blob/main/src/main/java/org/acme/GreetingResource.java#L20

### Output of `uname -a` or `ver`

Linux pres 5.15.59-2-lts #1 SMP Sat, 06 Aug 2022 21:34:17 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by languitar** [comment]
I received a Github pipeline notification that the automatic classification of this issue failed

**Comment by languitar** [comment]
Playing quarkus-bot:

/cc @FroMage, @geoand, @stuartwdouglas

**Comment by geoand** [comment]
Thanks for reporting. 

https://github.com/quarkusio/quarkus/pull/27409 takes care of it
