### ISSUE TITLE
Support for emptyDir kubernetes volumes

### ISSUE THREAD

**Issue by antssilva96** [quarkusio/quarkus#27222]
### Description

One of the types of volumes in kubernetes is the emptyDir described in https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

and from https://quarkus.io/guides/deploying-to-kubernetes#quarkus-kubernetes-kubernetes-config_configuration there seems to be no support in quarkus-lubernetes for this type of volumes

**Comment by Sgitario** [comment]
We need to first support it in Dekorate side. Pull request: https://github.com/dekorateio/dekorate/pull/1032
