### ISSUE TITLE
Quarkus-scheduler Adds a method for obtaining the running status of a task

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#27239]
### Description

It is used to ensure that only one node of a user-defined cluster scheduled task is running at the same time. By obtaining the task status periodically, the task running status (which may be saved in Redis with an expiration time) is continuously continued. This ensures that when the task runs for a long time, the status of the task will not expire, resulting in repeated running.

### Implementation ideas

In `io.quarkus.scheduler.Scheduler`add `boolean isRunning(String identity);` method to return the current running state of the task.

Running status similar to `SkipConcurrentExecutionInvoker.running` field.

**Comment by mkouba** [comment]
> It is used to ensure that only one node of a user-defined cluster scheduled task is running at the same time.

So I assume that you don't want to use the `quarkus-quartz` extension and the clustered scheduler which should take care of this, or?

In any case, the `quarkus-scheduler` extension itself is intentionally not designed to work accross a cluster to avoid the numerous pitfalls common for this kind of configuration. However, you can try to implement this manually, i.e. set a flag (stored in redis) inside your scheduled method and provide a `io.quarkus.scheduler.Scheduled.SkipPredicate` that would read this flag. In theory, you could also implement a [CDI interceptor](https://quarkus.io/guides/cdi#interceptors) to set the flag automatically for a scheduled method annotated with a specific interceptor binding.

**Comment by liuzhaozhao** [comment]
@mkouba 
Yes, quarkus-quartz is a cluster timing task solution

I hope to only rely on quarkus-scheduler to implement another (extension plug-in) without relying on database resources. Quartz also supports other dependent resources to implement cluster timing tasks, but I do not want to implement it on the basis of quartz, because quarkus-scheduler already provides A very convenient interface annotation (skipExecutionIf), I only need Scheduled.SkipPredicate in my extension plug-in, just because I can't get the task running status, it can't be implemented well.

I think adding the method of obtaining the task running status is not necessarily to achieve cluster scheduling, it is the proper status of task running, which is in line with generality;

**Comment by mkouba** [comment]
> I can't get the task running status, it can't be implemented well.

Like I mentioned in https://github.com/quarkusio/quarkus/issues/27239#issuecomment-1211694414 - you can implement a CDI interceptor that sets/unsets the flag for a scheduled method. If you implement a quarkus extension then it's even possible to add the interceptor binding annotation to a `@Scheduled` method automatically via [an annotation transformer](https://quarkus.io/guides/cdi-integration#annotations_transformer_build_item).

**Comment by liuzhaozhao** [comment]
Okay, thanks

**Comment by mkouba** [comment]
Feel free to reopen if it turns out to be "unimplementable" ;-) or if you have more questions...
