### ISSUE TITLE
Dev mode failing to compile changes on external JAR dependencies

### ISSUE THREAD

**Issue by fercomunello** [quarkusio/quarkus#27242]
I'm developing a web application using Quarkus, it's a normal Maven project, but part of my business code is developed on another project that uses Gradle as it's a requirement for building a [Kotlin MPP](https://kotlinlang.org/docs/multiplatform-library.html) library, so I configured this library written in Kotlin to compile for the following platforms: JVM (Quarkus), Android SDK (Android app) and Swift (iOS app). For JVM, the kotlin-multiplatform gradle plugin generates a JAR that works as expected on any JVM platform. 

The idea behind this is a shared library to avoid duplicate code, I know that Kotlin MPP is more common to be used only for mobile apps, but I need to share unit code between client and server because my app also works offline and process the same logic used on the backend in some situations.

**Quarkus behavior**
The issue is that Quarkus dev mode is unable to reload changes on this external library. Doing some research on existent issues, I found a closed issue [#2865](https://github.com/quarkusio/quarkus/issues/2865) and @stuartwdouglas says "If you have a multi module maven project this should work, as it will monitor the source directories of all the modules in the project.".

I know that Quarkus dev mode can reloads a multi-module Maven project, but as sayed before, my business library cannot be compiled on Maven as kotlin multiplatform plugin only works with Gradle. There's no magic to build the multiplatform artifacts, I just execute: `$ ./gradlew build publishToMavenLocal`. 

I also attempted to migrate my Quarkus project to use Gradle as build tool instead of Maven and uses the business library as a Gradle module, but when I did it, I found a similiar problem that is already reported on issue [#1098](https://github.com/quarkusio/quarkus/issues/10987#issuecomment-1200597965), then I prefered to just use Maven for Quarkus as it's more stable.

**NOTE:** **there is no need to configure Kotlin multiplatform specific features to reproduce the issue, you can do it with a normal Java project that generates a JAR.**

### Expected behavior

Quarkus dev mode should also reload code changes made to external JAR artifacts if configured to do so.

### Actual behavior

Quarkus dev mode fails to compile changes made in a external JAR artifact, forcing me to stop and start dev mode again after each build of the external JAR.

### How to Reproduce?

**How to Reproduce**

1. Get the sample business project that generates JAR artifact.
[business-sample.zip](https://github.com/quarkusio/quarkus/files/9307269/business-sample.zip)

2. Get the sample Quarkus project.
[quarkus-service.zip](https://github.com/quarkusio/quarkus/files/9307271/quarkus-service.zip)

3. Build the business project: `mvn install `
4. Run Quarkus Dev Mode: `mvn compile quarkus:dev`
5. Send a request to http://localhost:8080/uuid endpoint.
6. Look that the UUID was successful generated using the external business code
7. Now, uncomment the `randomUpperCase()` method on the external business project.
```java
public class JavaUUID {
  public String random() {
      return String.format("JAVA-%s",
          UUID.randomUUID().toString());
  }
  
  public String randomUpperCase() {
      return random().toUpperCase();
  }
}
```

8. Build the business project: mvn clean install
9. **Change JAX-RS GET endpoint to use the external** `randomUpperCase()` **method instead of** `random()`:

```java
@Path("/uuid")
@Produces(MediaType.APPLICATION_JSON)
public class UUIDResource {

  @GET
  public Response generate() {
      final String uuid = new JavaUUID().randomUpperCase();
      final LocalDateTime dateTime = LocalDateTime.now();
  
      return Response.ok(new UUIDResponse(uuid, dateTime)).build();
  }
}
```

10. Send a request http://localhost:8080/uuid endpoint again.
11. **Look that Quarkus throws a RuntimeException and fails to compile the changes**.
```
java.lang.NoSuchMethodError: 'java.lang.String org.acme.business.JavaUUID.randomUpperCase()'
	at org.acme.UUIDResource.generate(UUIDResource.java:18)
	at org.acme.UUIDResource_Subclass.generate$$superforward1(Unknown Source)
	at org.acme.UUIDResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.UUIDResource_Subclass.generate(Unknown Source)
```
12. Comment any reference and import of the external business class on the JAX-RS resource.
13. Send the request to the endpoint and see that the exception goes away.
14. Restart Quarkus by pressing _"S"_ on the terminal.
15. Uncomment business code on the JAX-RS resource.
16. Send the request again and you'll **see the same exception as before**.
17. **Repeat steps 1 to 10 and see that this approach works only if you stop dev mode and starts again after each business project build**. I think there could be a way to restart the application from scratch.

### Output of `uname -a` or `ver`

Fernandos-iMac-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "17.0.3" 2022-04-19 LTS Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

### Quarkus version or git rev

Tested on 2.11 (stable) and master (999-SNAPSHOT)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/fernando/.sdkman/candidates/maven/current Java version: 17.0.3, vendor: Oracle Corporation, runtime: /Users/fernando/.sdkman/candidates/java/17.0.3-oracle Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "12.4", arch: "x86_64", family: "mac"

### Additional information

I research about Quarkus ClassLoader and I found a [article](https://quarkus.io/blog/solving-problems-with-custom-extensions/#the-jandex-index) written by @gsmet on the Quarkus Blog and it says _"An important assumption of Quarkus is that the application lives in a closed world. You cannot dynamically add a jar at runtime to your Quarkus application and expect it to work."_

**So, this is a limitation or it's possible to do a workaround to enable a JAR redeployment at runtime?** I'm happy with the development experience that Quarkus provide us, is fast even when I need to restart the dev mode from scratch...just curious about this behaviour.

**Comment by aloubyansky** [comment]
The issue is that only modules of the project the application module originates from are live-reloadable by default. External modules aren't. However, you could configure [quarkus.class-loading.reloadable-artifacts](https://quarkus.io/guides/class-loading-reference#quarkus-class-loading-configuration-class-loading-config_quarkus.class-loading.reloadable-artifacts) if you really have to. Let us know if that worked for you. Thanks.

**Comment by fercomunello** [comment]
@aloubyansky I already tested this workaround, so I defined the following:

```properties
quarkus.class-loading.reloadable-artifacts=org.acme.business:business-jar
```

But it only works on the first change, then dev mode throws a runtime exception after the next change.

```logs
Listening for transport dt_socket at address: 5005
2022-08-11 16:45:39,580 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-16)
 Can not find {} in the classpath, fallback to system defaults. 
This may result in incorrect DNS resolutions on MacOS.
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-11 16:45:40,149 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-service 1.0-SNAPSHOT on 
JVM (powered by Quarkus 2.11.2.Final) started in 1.315s. Listening on: http://localhost:8080

2022-08-11 16:45:40,150 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-08-11 16:45:40,150 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: 
[cdi, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]
2022-08-11 16:46:11,571 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) 
Restarting quarkus due to changes in UUIDResource.class.
2022-08-11 16:46:11,580 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-service stopped in 0.008s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-11 16:46:11,762 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-service 1.0-SNAPSHOT on JVM 
(powered by Quarkus 2.11.2.Final) started in 0.178s. Listening on: http://localhost:8080

2022-08-11 16:46:11,762 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-08-11 16:46:11,762 INFO  [io.quarkus] (Quarkus Main Thread) 
Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]
--
Compilation Failed:
/Users/fernando/Sandbox/Quarkus/issues
/issue-27242/quarkus-service/src/main/java/org/acme/UUIDResource.java:3: error: 
cannot access org.acme.business.JavaUUID
import org.acme.business.JavaUUID;
                        ^
  bad class file: /Users/fernando/.m2/repository/org/acme/business/business-jar/1.0
/business-jar-1.0.jar(/org/acme/business/JavaUUID.class)
    unable to access file: java.io.EOFException: Unexpected end of ZLIB input stream
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/fernando/Sandbox/Quarkus/issues
/issue-27242/quarkus-service/src/main/java/org/acme/UUIDResource.java:18: error: cannot find symbol
        final String uuid = new JavaUUID().randomLowerCase();
                                ^
  symbol:   class JavaUUID
  location: class org.acme.UUIDResource
```

**Comment by aloubyansky** [comment]
@fercomunello I could not reproduce the issue with `quarkus.class-loading.reloadable-artifacts=org.acme.business:business-jar`.
I tried commenting and uncommenting the `randomUpperCase()` method multiple times. Is there a specific sequence of changes and reloads that is 100% reproducible in your environment with the `quarkus.class-loading.reloadable-artifacts` configured? If so, could you write it down here? Thanks.

**Comment by fercomunello** [comment]
@aloubyansky You need to change JAX-RS endpoint to use the new method added on the external JAR:

1. Run quarkus:dev
2. Create a new method or class on the business project.
3. Build the JAR file.
4. Change the JAX-RS endpoint to call the business method or class that you added before.
5. The request will be processed correctly.
6. But, change business code and the JAX-RS endoint again.
7. You'll get a compilation exception at runtime.

**Comment by aloubyansky** [comment]
Still not seeing it. Here is what I was trying:
1. `mvn clean quarkus:dev`
2. Load `localhost:8080/uuid`
3. add method `randomUpperCase` in the `JavaUUID`
4. modify the `UUIDResource` to use `randomUpperCase`
5. Re-load `localhost:8080/uuid` and make sure it's in upper case
6. modify the `generate` method by adding `-UUID` suffix to the generated uuid
7. Re-load `localhost:8080/uuid` and make sure the suffix is added

Does the above sequence fail in your environment?

**Comment by fercomunello** [comment]
This sequence does not fail here. Try to repeat your procedure but instead of adding "-UUID" suffix directly in the Quarkus project add that on the external project (e.g. on the randomUpperCase or random method). What is failing is the 2th change on the external JAR.

**Comment by aloubyansky** [comment]
Got it, thanks.

**Comment by fercomunello** [comment]
For now, I am using a shell script to automate my workflow. First, the script runs a publish gradle task to generate the JAR for JVM and then boots my Quarkus application, then I wait 5 ˜ 7 seconds to send the first request.

```shell
#!/usr/bin/env bash

cd ../../business-api && ./gradlew publishJvmPublicationToMavenLocal || exit
cd ../quarkus-rest && ./mvnw quarkus:dev
```

I only stop and run the script again each time I do some change on the external library.

**Comment by aloubyansky** [comment]
I suspect the issue isn't in the Quarkus code but is related to the fact that the external lib is in the system classloader and the Java compiler is somehow affected by that.

**Comment by fercomunello** [comment]
As you saw, the first reload works with `quarkus.class-loading.reloadable-artifacts` configuration, so when I tryed to debug the `QuarkusCompiler` class I found my external classes loaded there but on second attempt to change external code and reload, the classloader was no longer updated with my external lib changes. 

Can you explain to me a way to debug Quarkus dev mode code properly? Thanks!

**Comment by aloubyansky** [comment]
The class actually isn't in the system classloader, so it's something else. However, if I may a copy of the original external JAR right before compilation and use that copy of the JAR for the compiler's classpath, it works.

**Comment by fercomunello** [comment]
@aloubyansky I finally figured out what is caused the issue after debug JavaCompilationProvider class. To be more directly, it is a cache feature of FileManager that causes this issue. Take a look at this commit: https://github.com/quarkusio/quarkus/commit/175665d862b98b13c8e33a85c9fbbc352952b12e

I'm not shure, but the internal cache that should be invalidated for reloadable JARs is: ((CacheFSInfo) ((JavacFileManager) fileManager).fsInfo).attributeCache

If you want to be sure before develop a fix, put a breakpoint on [L53 ](https://github.com/quarkusio/quarkus/blob/175665d862b98b13c8e33a85c9fbbc352952b12e/core/deployment/src/main/java/io/quarkus/deployment/dev/JavaCompilationProvider.java#L53) and assign fileManager variable to null, then skip all the execution and check that the procedure now works without compilation errors.

It would be nice to send a contribution but without reverting the commit of @stuartwdouglas as it is a 100 ms optimization that should be considered in my opinion ˆˆ

**Comment by fercomunello** [comment]
@aloubyansky @stuartwdouglas  I can send a pull request with some changes I've made to quarkus-core-deployment and quarkus-bootstrap-core modules to not consider caching compiler objects when there is one or more reloadable artifacts configured in the project 👍. 

Here is the changes: [fix_issue_27242.patch.zip](https://github.com/quarkusio/quarkus/files/9347432/fix_issue_27242.patch.zip)

```diff java
diff --git a/core/deployment/src/main/java/io/quarkus/deployment/dev/CompilationProvider.java b/core/deployment/src/main/java/io/quarkus/deployment/dev/CompilationProvider.java
index 91cd9106f2..77cd7cc8b5 100644
--- a/core/deployment/src/main/java/io/quarkus/deployment/dev/CompilationProvider.java
+++ b/core/deployment/src/main/java/io/quarkus/deployment/dev/CompilationProvider.java
@@ -49,6 +49,7 @@ default void close() throws IOException {
         private final String targetJvmVersion;
         private final List<String> compilePluginArtifacts;
         private final List<String> compilerPluginOptions;
+        private final boolean cacheEnabled;
 
         public Context(
                 String name,
@@ -62,7 +63,8 @@ public Context(
                 String sourceJavaVersion,
                 String targetJvmVersion,
                 List<String> compilePluginArtifacts,
-                List<String> compilerPluginOptions) {
+                List<String> compilerPluginOptions,
+                boolean cacheEnabled) {
             this.name = name;
             this.classpath = classpath;
             this.projectDirectory = projectDirectory;
@@ -75,6 +77,7 @@ public Context(
             this.targetJvmVersion = targetJvmVersion;
             this.compilePluginArtifacts = compilePluginArtifacts;
             this.compilerPluginOptions = compilerPluginOptions;
+            this.cacheEnabled = cacheEnabled;
         }
 
         public String getName() {
@@ -124,5 +127,9 @@ public String getTargetJvmVersion() {
         public List<String> getCompilerPluginOptions() {
             return compilerPluginOptions;
         }
+
+        public boolean isCacheEnabled() {
+            return cacheEnabled;
+        }
     }
 }


diff --git a/core/deployment/src/main/java/io/quarkus/deployment/dev/JavaCompilationProvider.java b/core/deployment/src/main/java/io/quarkus/deployment/dev/JavaCompilationProvider.java
index 477638127e..8eae18458f 100644
--- a/core/deployment/src/main/java/io/quarkus/deployment/dev/JavaCompilationProvider.java
+++ b/core/deployment/src/main/java/io/quarkus/deployment/dev/JavaCompilationProvider.java
@@ -36,9 +36,9 @@
     private static final Set<String> COMPILER_OPTIONS = new HashSet<>(Arrays.asList("-g", "-parameters"));
     private static final Set<String> IGNORE_NAMESPACES = new HashSet<>(Collections.singletonList("org.osgi"));
 
-    JavaCompiler compiler;
-    StandardJavaFileManager fileManager;
-    DiagnosticCollector<JavaFileObject> fileManagerDiagnostics;
+    private JavaCompiler compiler;
+    private StandardJavaFileManager fileManager;
+    private DiagnosticCollector<JavaFileObject> fileManagerDiagnosticListener;
 
     @Override
     public String getProviderKey() {
@@ -59,43 +59,58 @@ public void compile(Set<File> filesToCompile, Context context) {
         if (compiler == null) {
             throw new RuntimeException("No system java compiler provided");
         }
+
+        DiagnosticCollector<JavaFileObject> compilationDiagnosticListener = new DiagnosticCollector<>();
+
+        boolean compilationSucceed;
+
         try {
-            if (fileManager == null) {
-                fileManager = compiler.getStandardFileManager(fileManagerDiagnostics = new DiagnosticCollector<>(), null,
-                        context.getSourceEncoding());
+            if (this.fileManager == null || !context.isCacheEnabled()) {
+                this.fileManager = compiler.getStandardFileManager(
+                        this.fileManagerDiagnosticListener = new DiagnosticCollector<>(), null, context.getSourceEncoding());
             }
-
-            DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
-            fileManager.setLocation(StandardLocation.CLASS_PATH, context.getClasspath());
-            fileManager.setLocation(StandardLocation.CLASS_OUTPUT, Collections.singleton(context.getOutputDirectory()));
+            this.fileManager.setLocation(StandardLocation.CLASS_PATH, context.getClasspath());
+            this.fileManager.setLocation(StandardLocation.CLASS_OUTPUT, Collections.singleton(context.getOutputDirectory()));
 
             CompilerFlags compilerFlags = new CompilerFlags(COMPILER_OPTIONS, context.getCompilerOptions(getProviderKey()),
                     context.getReleaseJavaVersion(), context.getSourceJavaVersion(), context.getTargetJvmVersion());
 
-            Iterable<? extends JavaFileObject> sources = fileManager.getJavaFileObjectsFromFiles(filesToCompile);
-            JavaCompiler.CompilationTask task = compiler.getTask(null, fileManager, diagnostics,
-                    compilerFlags.toList(), null, sources);
+            Iterable<? extends JavaFileObject> sources = this.fileManager.getJavaFileObjectsFromFiles(filesToCompile);
+            JavaCompiler.CompilationTask task = compiler.getTask(null, this.fileManager,
+                    compilationDiagnosticListener, compilerFlags.toList(), null, sources);
 
-            if (!task.call()) {
-                StringBuilder sb = new StringBuilder("\u001B[91mCompilation Failed:");
-                for (Diagnostic<? extends JavaFileObject> i : diagnostics.getDiagnostics()) {
-                    sb.append("\n");
-                    sb.append(i.toString());
+            compilationSucceed = task.call();
+
+            try {
+                logDiagnostics(compilationDiagnosticListener);
+                logDiagnostics(this.fileManagerDiagnosticListener);
+
+                if (!this.fileManagerDiagnosticListener.getDiagnostics().isEmpty()) {
+                    logDiagnostics(this.fileManagerDiagnosticListener);
+                    closeFileManager();
                 }
-                sb.append("\u001b[0m");
-                throw new RuntimeException(sb.toString());
+            } catch (IOException e) {
+                throw new RuntimeException("Cannot close file manager", e);
             }
 
-            logDiagnostics(diagnostics);
+            if (!context.isCacheEnabled() || !compilationSucceed) {
+                try {
+                    closeFileManager();
+                } catch (IOException e) {
+                    throw new RuntimeException("Cannot close file manager", e);
+                }
+            }
 
-            if (!fileManagerDiagnostics.getDiagnostics().isEmpty()) {
-                logDiagnostics(fileManagerDiagnostics);
-                fileManager.close();
-                fileManagerDiagnostics = null;
-                fileManager = null;
+            if (!compilationSucceed) {
+                StringBuilder stackTrace = new StringBuilder("\u001B[91mCompilation Failed:");
+                for (Diagnostic<? extends JavaFileObject> diagnostic : compilationDiagnosticListener.getDiagnostics()) {
+                    stackTrace.append("\n").append(diagnostic.toString());
+                }
+                stackTrace.append("\u001b[0m");
+                throw new RuntimeException(stackTrace.toString());
             }
         } catch (IOException e) {
-            throw new RuntimeException("Cannot close file manager", e);
+            throw new RuntimeException(e);
         }
     }
 
@@ -115,15 +130,22 @@ public Path getSourcePath(Path classFilePath, PathCollection sourcePaths, String
 
     @Override
     public void close() throws IOException {
-        if (fileManager != null) {
-            fileManager.close();
-            fileManager = null;
-            fileManagerDiagnostics = null;
+        closeFileManager();
+    }
+
+    private void closeFileManager() throws IOException {
+        if (this.fileManager != null) {
+            this.fileManager.close();
+            this.fileManager = null;
+            this.fileManagerDiagnosticListener = null;
         }
     }
 
-    private void logDiagnostics(final DiagnosticCollector<JavaFileObject> diagnostics) {
-        for (Diagnostic<? extends JavaFileObject> diagnostic : diagnostics.getDiagnostics()) {
+    private void logDiagnostics(final DiagnosticCollector<JavaFileObject> diagnosticListener) {
+        if (diagnosticListener.getDiagnostics().isEmpty())
+            return;
+
+        for (Diagnostic<? extends JavaFileObject> diagnostic : diagnosticListener.getDiagnostics()) {



diff --git a/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusCompiler.java b/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusCompiler.java
index 47cbd93072..3a92104584 100644
--- a/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusCompiler.java
+++ b/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusCompiler.java
@@ -47,6 +47,7 @@
      */
     private final Map<String, CompilationProvider.Context> compilationContexts = new HashMap<>();
     private final Set<String> allHandledExtensions;
+    private final boolean compilationProviderCacheEnabled;
 
     public QuarkusCompiler(CuratedApplication application,
             List<CompilationProvider> compilationProviders,
@@ -150,6 +151,8 @@ public QuarkusCompiler(CuratedApplication application,
         for (CompilationProvider compilationProvider : compilationProviders) {
             allHandledExtensions.addAll(compilationProvider.handledExtensions());
         }
+
+        this.compilationProviderCacheEnabled = !application.isReloadableArtifactsConfigured();
     }
 
     public void setupSourceCompilationContext(DevModeContext context, Set<File> classPathElements, DevModeContext.ModuleInfo i,
@@ -179,7 +182,8 @@ public void setupSourceCompilationContext(DevModeContext context, Set<File> clas
                                 context.getSourceJavaVersion(),
                                 context.getTargetJvmVersion(),
                                 context.getCompilerPluginArtifacts(),
-                                context.getCompilerPluginsOptions()));
+                                context.getCompilerPluginsOptions(),
+                                this.compilationProviderCacheEnabled));
             }
         }
     }


diff --git a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/ConfiguredClassLoading.java b/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/ConfiguredClassLoading.java
index 723b6ed728..e93f7fb0fa 100644
--- a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/ConfiguredClassLoading.java
+++ b/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/ConfiguredClassLoading.java
@@ -205,6 +205,10 @@ public boolean isReloadableArtifact(ArtifactKey key) {
         return reloadableArtifacts.contains(key);
     }
 
+    public boolean hasReloadableArtifacts() {
+        return !reloadableArtifacts.isEmpty();
+    }
+
     public boolean isRemovedArtifact(ArtifactKey key) {
         return removedArtifacts.contains(key);
     }


diff --git a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java b/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java
index 8236688afa..03bccb210a 100644
--- a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java
+++ b/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java
@@ -65,6 +65,7 @@
     private final QuarkusBootstrap quarkusBootstrap;
     private final CurationResult curationResult;
     private final ConfiguredClassLoading configuredClassLoading;
+    private final boolean reloadableArtifactsConfigured;
 
     final ApplicationModel appModel;
 
@@ -76,6 +77,7 @@
         this.curationResult = curationResult;
         this.appModel = curationResult.getApplicationModel();
         this.configuredClassLoading = configuredClassLoading;
+        this.reloadableArtifactsConfigured = configuredClassLoading.hasReloadableArtifacts();
     }
 
     /**
@@ -99,6 +101,10 @@ public QuarkusBootstrap getQuarkusBootstrap() {
         return quarkusBootstrap;
     }
 
+    public boolean isReloadableArtifactsConfigured() {
+        return reloadableArtifactsConfigured;
+    }
+
     public Object runInAugmentClassLoader(String consumerName, Map<String, Object> params) {
         return runInCl(consumerName, params, getAugmentClassLoader());
     }

```

The dev mode is still super fast, I didn't even notice a difference but I'm also working on other approach to make use of the cache only when there are no external classpath changes to be scanned and recompiled, but I will definitely need some help if that'll be the case...

**Comment by aloubyansky** [comment]
@fercomunello thanks a lot for the research. I want to spend a bit more time on this but next week. When you compare compile time/reload differences, how big is your project? How big is the classpath and how many classes do you recompile?

**Comment by stuartwdouglas** [comment]
In principal I am ok with the fix. Although maybe we should just be creating a new file manager each time anyway? I can't actually remember if it was the file manager or compiler that was the bit that was slowing down reload time.

**Comment by stuartwdouglas** [comment]
Also if we are going to support this we should add some tests for it.

**Comment by aloubyansky** [comment]
I created a branch with a test for this last week. It's waiting for the fix.

**Comment by fercomunello** [comment]
@aloubyansky Thank you very much. I created a integration test for the fix based on your branch's test, it helped me a lot. I'm also preparing a pull request, it'll be ready be reviewed soon ;)

**Comment by aloubyansky** [comment]
@fercomunello have you tried to measure the compilation time with and w/o your change? It'd be useful to know how it compares. Thanks.

**Comment by fercomunello** [comment]
@aloubyansky Yes, I did it. The conclusion is: the changes adds a overhead of about 50 ms. I talked to Stuart and we agreed that this object cache in the compiler should only be considered if there are no reloadable artifacts configured in the application properties file.

Here is the results of normal compilation times with JDK 11 & 17: https://pastebin.com/raw/WQyBT3fU

**Comment by aloubyansky** [comment]
Thanks @fercomunello I'll have a closer look next week.
