### ISSUE TITLE
In a Gradle Quarkus application build, quarkusGenerateCode triggers a deprecation warning when sourcesJar is enabled

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#27259]
### Describe the bug

In a simple Quarkus app build, by simply enabling sources JAR, Gradle produces deprecation warnings:
```groovy
java {
    withSourcesJar()
}
```

This is a sample of the error:
`
Reason: Task ':app:sourcesJar' uses this output of task ':app:quarkusGenerateCode' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
`

### How to Reproduce?

Reproducer: https://github.com/jskillin-idt/quarkusio-quarkus-issues-27259

### Output of `uname -a` or `ver`

Linux jacob-ubuntu-dev 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-122.04) OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-122.04, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by jskillin-idt** [comment]
I've added a reproducer.

**Comment by jskillin-idt** [comment]
It's possible compileJava is also affected. I'll need to make a reproducer to verify, however.

**Comment by glefloch** [comment]
Right, We need to catch those warning without breaking the compatibility with gradle 6.5
