### ISSUE TITLE
Cannot do blocking operation on external module gRPC module

### ISSUE THREAD

**Issue by kingtran2112** [quarkusio/quarkus#27264]
### Describe the bug

I create a simple application using gRPC and ORM. All of my gRPC model and service is generated to Java class in another project and publish as a Java package. And it is imported to Quarkus application by gradle. In Quarkus application, I implemented the service in Quarkus and tried to persist a dummy Entity. When I call to the application, it throws an error `io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.`. I tried to add `@Blocking` to the method and it doesn't help.

### Expected behavior

Can specify worker thread for gRPC service in external module.

### Actual behavior

Throw `io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.` even put `@Blocking` on the method.

### How to Reproduce?

I created a small project to reproduce the problem here
https://github.com/kingtran2112/quarkus-demo
Please notice that my gRpc module `com.kawaii:service-proto` defined in `build.gradle` is private package so you cannot access that.
The problem happen in the file `ProductController.java`, I tried to make the simple class `HelloGrpcService.java` with the same function but work for internal proto and it works fine.

### Output of `uname -a` or `ver`

Darwin Kings-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Homebrew (build 17.0.4+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.4+0, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by michalszynkiewicz** [comment]
Can you create a full reproducer? Maybe by adding a separate module or project to the repo?

**Comment by michalszynkiewicz** [comment]
Does your dependency have a Jandex index?

**Comment by kingtran2112** [comment]
Hi, I updated the repository to using subproject. It produced the same issue. But thanks for your keyword about `Jandex index`. I found the guide [here](https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index). After I add 
```
quarkus.index-dependency.example.group-id=com.proto.example
quarkus.index-dependency.example.artifact-id=service-proto
```
The problem's gone. Thanks a lot

**Comment by sgrissom-rxss** [comment]
Thanks for posting this. I had a similar problem with a reactor project.

```
reactor/
  protos/              <-- proto and grpc service defs
  java-service/    <--  java library
  grpc-impl/        <--  grpc service implementaitons
```

I had a `beans.xml` in `java-service/` module and everything worked fine. Or so I thought. I didn't notice `@Blocking` was being ignored until I added in transactions and noticed everything running on a IO thread. Adding `beans.xml` to the `protos/` module fixed the issue.

Seems there's a subtle situation where application developers can inadvertently execute on the IO thread even when using `@Blocking` and there's no notification. Wouldn't go so far as calling it bug, but I wonder if it's possible to detect this situation and warn about it?

**Comment by michalszynkiewicz** [comment]
@sgrissom-rxss without an index, it's difficult for us to figure out the annotation is there...
