### ISSUE TITLE
Headers are duplicated by resteasy-reactive when a WriterInterceptor is added

### ISSUE THREAD

**Issue by johnoliver** [quarkusio/quarkus#27268]
### Describe the bug

Repeated calls to `ServerSerialisers.encodeResponseHeaders` will duplicate the headers in the response. This is specifically an issue if a `WriteInterceptor` is added, which results in the method being called from `WriterInterceptor.proceed` and then further on in the response processing.

This means that if you add any response headers and have a `WriteInterceptor`, the headers are duplicated on the response.

Either the call needs to be removed from `WriterInterceptor.proceed` (is it really needed there?), or `ServerSerialisers.encodeResponseHeaders` needs to be modified to allow repeat calls and prevent duplication.

Would the logic of `ServerSerialisers.encodeResponseHeaders` refusing to re-add a header who's key and value is already present on the response work? I am not sure there is any value in having multiple identical key+value headers on a response so would probably be fine.

**Comment by geoand** [comment]
This is actually a duplicate of https://github.com/quarkusio/quarkus/issues/27325 and is fixed by https://github.com/quarkusio/quarkus/pull/27406
