### ISSUE TITLE
container-image-podman for Podman-related builds

### ISSUE THREAD

**Issue by kereis** [quarkusio/quarkus#27274]
### Description

Normally, `container-image-docker` would be enough as Podman implements OCI standards pretty much the same as Docker. However, if you are working on Windows, you may run into limitation with setting `DOCKER_HOST` to Podman's `npipe` and command aliases, as `container-image-docker`'s `DockerProcessor` calls `docker` command directly. Unfortunately, I haven't found a way to create Windows CMD/PowerShell aliases that apply for Java too.

I can imagine that this extension is pretty much built the same like `container-image-docker`, but using `podman` command instead.
Maybe there can also be integrations for other opencontainers tools like `buildah`.

### Configuration suggestion

Pretty much the same configuration properties used for `container-image-*`/`container-image-docker` extension.

**Comment by iocanel** [comment]
an extension that changes the behavior of `container-image-docker` to use `podman` sgtm

**Comment by gastaldi** [comment]
Does it have to be a separate extension? Can't we support that in `container-image-docker` (in the same way we support Podman while building to native)?

**Comment by gastaldi** [comment]
Maybe @geoand can answer that. If that's the recommended approach we should at least document in its guide for posterity

**Comment by geoand** [comment]
Yes, you can do that with Jib. We don't have every feature in the docs, but all the configuration properties are documented
