### ISSUE TITLE
ArcDevConsoleProcessor.collectBeanInfo() is taking a long time

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#27281]
### Describe the bug

Quarkus 2.11 takes 13s to do a restart in dev mode, forced by pressing s in the terminal.

A large chunk of this time is spent on ArcDevConsoleProcessor.collectBeanInfo.

The app has 730 non removed beans, and 130 entities.

I can't export a flamegraph file on my current environment, however I can send you a .nps (sampling snapshot created by visualvm) privatly.

Thread, build-41 taking 71% of overall profiling time.
![image](https://user-images.githubusercontent.com/1223135/184624362-0612bfb7-c2de-4c68-b2b2-6a53b9182fa6.png)

Timeline:
![image](https://user-images.githubusercontent.com/1223135/184624000-a743db2e-a465-4fe9-b20c-934c3f5819a6.png)

Screenshot from another run sampled with visualvm:
![image](https://user-images.githubusercontent.com/1223135/184624074-12b26c0e-c7eb-4053-869b-263569b59949.png)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1826]

### Output of `java -version`

openjdk 18.0.2 2022-07-19 OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 18.0.2, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\18 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment]
@Postremus https://github.com/quarkusio/quarkus/pull/27287 should help significantly. It would be great if you could test your app with this changeset, i.e. build quarkus from the branch and run your app in the dev mode with quarkus `999-SNAPSHOT`.
