### ISSUE TITLE
Use @PathParam without parameter when the path has the same name as the attribute

### ISSUE THREAD

**Issue by heltonricardo** [quarkusio/quarkus#27299]
### Description

Use @PathParam without parameter when the path has the same name as the attribute. Example:

Current:
```java
@GET
@Path("/{userId}/{productId}")
public Response get(@PathParam("userId") Long userId, @PathParam("productId") Long productId) {
    // Implementation
}
```

Proposal:
```java
@GET
@Path("/{userId}/{productId}")
public Response get(@PathParam Long userId, @PathParam Long productId) {
    // Implementation
}
```

The parameter remains mandatory when the path has a different name than the attribute:
```java
@GET
@Path("/{id}/{productId}")
public Response get(@PathParam("id") Long userId, @PathParam Long productId) {
    // Implementation
}
```

**Comment by andreas-eberle** [comment]
Hey @heltonricardo,

if I recall correctly, `@PathParam` is defined to require the parameter by the spec. However, they added `@RestPath`, `@RestQuery`, ... which allow to do exactly what you ask for. 

Also see: https://quarkus.io/guides/resteasy-reactive#accessing-request-parameters

**Comment by heltonricardo** [comment]
Hi @andreas-eberle!

I saw that this annotation works for reactive projects (you need to include quarkus-resteasy-reactive and consequently remove quarkus-resteasy).

Do you know if there is an annotation similar to @RestPath for non-reactive projects?

**Comment by andreas-eberle** [comment]
Hey @heltonricardo,

no, unfortunately, I think these are only available for resteasy-reactive. However, in most cases, you should not have much trouble switching to resteasy-reactive. I use it in all my projects my now and you can use it blocking (it is automatically blocking when your method does not use Uni or Kotlin's suspend). Afaik only minor things differ and need adapting (e.g. Multipart is a bit different). 

Mabye it could make sense for you to switch to reactive (if it isn't a big effort for you) and by that also benefit from a slight speed gain :)

**Comment by heltonricardo** [comment]
Understood, @andreas-eberle! I will make this modification to test.

Thank you very much for your attention and for the tips.

**Comment by gsmet** [comment]
In RESTEasy Classic, there are two different `@PathParam` annotations, the one from the spec and the one from RESTEasy itself.
The one from RESTEasy has the behavior you're asking for so just use this one.

**Comment by heltonricardo** [comment]
Thank you, @gsmet!
