### ISSUE TITLE
Kotlin: Rest Client Reactive @ClientExceptionMapper not usable

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#27309]
### Describe the bug

When you try to define a [@ClientExceptionMapper](https://quarkus.io/guides/rest-client-reactive#using-clientexceptionmapper) with Kotlin like this:

```kotlin
@RegisterRestClient(baseUri = "https://swapi.dev/api")
interface SwapiRestClient {
    @GET
    @Path("/people/{id}")
    suspend fun getPersonById(@RestPath id: Int, @RestQuery format: SwapiFormat?): Person

    companion object {
        @JvmStatic
        @ClientExceptionMapper
        fun toException(response: Response): RuntimeException? {
            return when (response.status) {
                400 -> NotFoundException("not found")
                else -> null
            }
        }
    }
}
```

the application will fail on startup with the exception:

```
Caused by: java.lang.IllegalStateException: io.quarkus.rest.client.reactive.ClientExceptionMapper is only supported on static methods of REST Client interfaces that take 'javax.ws.rs.core.Response' as a single parameter and return 'java.lang.RuntimeException'.
	at io.quarkus.rest.client.reactive.deployment.ClientExceptionMapperHandler.generateResponseExceptionMapper(ClientExceptionMapperHandler.java:78)
```

However, the `@JvmStatic` annotation should create a normal static interface method in the bytecode since Kotlin 1.3 (see https://kotlinlang.org/docs/java-to-kotlin-interop.html#static-methods).

I can confirm the rest client interface method is usable from Java with a normal static access: 

```java
public class TestStaticAccess {

	public void testStatic() {
		RuntimeException ex = SwapiRestClient.toException(Response.accepted().build());
		if (ex != null) {
			throw ex;
		}
	}
}
```

### Expected behavior

It should be possible to use a rest client with `@ClientExceptionMapper` with Kotlin as shown above. If possible, it would be great to even check if the method exists on the Companion object so we could avoid using `@JvmStatic` and make the usage more Kotlin idiomatic. 

### Actual behavior

App does not start and shows exception that the annotated method would not be valid.

```
Caused by: java.lang.IllegalStateException: io.quarkus.rest.client.reactive.ClientExceptionMapper is only supported on static methods of REST Client interfaces that take 'javax.ws.rs.core.Response' as a single parameter and return 'java.lang.RuntimeException'.
	at io.quarkus.rest.client.reactive.deployment.ClientExceptionMapperHandler.generateResponseExceptionMapper(ClientExceptionMapperHandler.java:78)
```

### How to Reproduce?

Reproducer:
[2022-08-15-quarkus.zip](https://github.com/quarkusio/quarkus/files/9350320/2022-08-15-quarkus.zip)
 
1. Download and unzip
2. start with `./gradlew quarkusDev`
3. observe error

### Output of `java -version`

JDK 17

### Quarkus version or git rev

Quarkus 2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/27407 takes care of the issue

**Comment by andreas-eberle** [comment]
Thanks @geoand for the fix!

If I understand the test in your PR correctly, then it will work with @JvmStatic in the future, right? Is it also possible to avoid that we even need the @JvmStatic? I know it is just a small convenience thing, so no worries if it would be a lot of effort. But if it is possible, I think it would be great to support the more Kotlin idiomatic way as well :)

**Comment by geoand** [comment]
> f I understand the test in your PR correctly, then it will work with @JvmStatic in the future, right?

Correct

>  Is it also possible to avoid that we even need the @JvmStatic

I am not sure how this could be done TBH, but it might be possible

**Comment by andreas-eberle** [comment]
So what I understand from the Kotlin docs (https://kotlinlang.org/docs/java-to-kotlin-interop.html#static-methods), a "normal" Kotlin Companion object method (without @JvmStatic) could be called by calling

`SwapiRestClient .Companion.toException()`

So it should be possible to check if there is a static object named "Companion" on the rest client class and check if that has one of the annotated methods.

**Comment by evanchooly** [comment]
That is correct. It's a little less than ideal to require `@JvmStatic` on kotlin code that won't necessarily be Java code facing but this is certainly better than nothing.
