### ISSUE TITLE
Illegal reflective access warning with GraalVM 22.2.0 Java 11 CE for com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#27308]
### Describe the bug

Illegal reflective access warning with GraalVM 22.2.0 Java 11 CE for com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator

```
[1/7] Initializing...                                                                                   (14.8s @ 0.31GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
...
11:54:09,790 INFO  [org.jbo.res.res.i18n] RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.example.quarkus.QuarkusRestApplication
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator (file:/Users/rsvoboda/git/quarkus-startstop/app-full-microprofile/target/quarkus-native-image-source-jar/lib/com.fasterxml.jackson.core.jackson-databind-2.13.3.jar) to field java.util.EnumSet.elementType
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2/7] Performing analysis...  [********]                                                                (27.9s @ 3.63GB)
  15,328 (92.30%) of 16,606 classes reachable
  24,814 (66.35%) of 37,400 fields reachable
  76,568 (64.12%) of 119,412 methods reachable
...
```

No warning when using GraalVM 22.2.0 Java 17 CE

### Expected behavior

no warning for com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator 

### Actual behavior

warning for com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator

### How to Reproduce?

 - get https://github.com/quarkus-qe/quarkus-startstop
 - use GraalVM 22.2.0 Java 11 CE
 - run `mvn clean package -DskipTests -Dnative -pl app-full-microprofile`
 - check log

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

GraalVM 22.2.0 Java 11 CE

### GraalVM version (if different from Java)

GraalVM 22.2.0 Java 11 CE

### Quarkus version or git rev

2.11.2.Final

**Comment by geoand** [comment]
I could replicate this with `2.11.1.Final` but not with Quarkus from `main`.
@rsvoboda please try and if you can confirm, I propose closing the issue

**Comment by rsvoboda** [comment]
`mvn clean package -DskipTests -Dnative -pl app-full-microprofile -Dquarkus.platform.group-id=io.quarkus -Dquarkus.version=2.12.0.CR1` works fine, no Illegal reflective access warning
