### ISSUE TITLE
The build step within the Knative processor to add decorators is always invoked causing cycle detected issues

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#27313]
### Description

When adding the Quarkus OpenShift extension, the decorators for Knative are being added. This is causing issues in a custom extension raising cycle detected extensions:

```
io.quarkus.builder.ChainBuildException: Cycle detected:
[ERROR]                    io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftRequirementsJvm produced class io.quarkus.kubernetes.spi.KubernetesCommandBuildItem
[ERROR]                 to io.quarkus.kubernetes.deployment.KnativeProcessor#createDecorators produced class io.quarkus.kubernetes.spi.DecoratorBuildItem
[ERROR]                 to io.quarkus.kubernetes.deployment.KubernetesProcessor#build produced class io.quarkus.kubernetes.spi.GeneratedKubernetesResourceBuildItem
[ERROR]                 to io.quarkiverse.helm.deployment.HelmProcessor#generateResources produced class io.quarkus.deployment.builditem.FeatureBuildItem
[ERROR]                 to io.quarkus.deployment.steps.MainClassBuildStep#build produced class io.quarkus.deployment.builditem.GeneratedClassBuildItem
[ERROR]                 to io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar produced class io.quarkus.deployment.pkg.builditem.JarBuildItem
[ERROR]                 to io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftRequirementsJvm
```

The problem is that the Knative processor and the OpenShift processor are both building KubernetesCommandBuildItem. But this is only one example. 

### Implementation ideas

Add something similar to `@BuildStep(onlyIf = DeploymentTarget contains Knative) if the knative processor add decorators.

**Comment by mkouba** [comment]
I think that the real cause of the cycle above is that the `OpenshiftProcessor#openshiftRequirementsJvm()` build step consumes the `JarBuildItem` which is produced by the `JarResultBuildStep.buildRunnerJar()` that consumes the `MainClassBuildItem` and `MainClassBuildStep.build()` consumes the features. 

If `HelmProcessor#generateResources()` produces a feature then it must be executed before the `OpenshiftProcessor#openshiftRequirementsJvm()`. However, if the `HelmProcessor#generateResources()` also consumes `GeneratedKubernetesResourceBuildItem` then it must be ultimately executed after the `OpenshiftProcessor#openshiftRequirementsJvm()` and hence the cycle.

**Comment by Sgitario** [comment]
> I think that the real cause of the cycle above is that the `OpenshiftProcessor#openshiftRequirementsJvm()` build step consumes the `JarBuildItem` which is produced by the `JarResultBuildStep.buildRunnerJar()` that consumes the `MainClassBuildItem` and `MainClassBuildStep.build()` consumes the features.
> 
> If `HelmProcessor#generateResources()` produces a feature then it must be executed before the `OpenshiftProcessor#openshiftRequirementsJvm()`. However, if the `HelmProcessor#generateResources()` also consumes `GeneratedKubernetesResourceBuildItem` then it must be ultimately executed after the `OpenshiftProcessor#openshiftRequirementsJvm()` and hence the cycle.

Yep. But I could not find any solution for it. I tried to split it up or not to return a feature build item (but it never got executed).

**Comment by mkouba** [comment]
> Yep. But I could not find any solution for it. I tried to split it up or not to return a feature build item (but it never got executed).

I understand. We need to find a build item that can be produced and is consumed after the `OpenshiftProcessor#openshiftRequirementsJvm()`. And chances are that it doesn't exist yet...

**Comment by Sgitario** [comment]
> > Yep. But I could not find any solution for it. I tried to split it up or not to return a feature build item (but it never got executed).
> 
> I understand. We need to find a build item that can be produced and is consumed after the `OpenshiftProcessor#openshiftRequirementsJvm()`. And chances are that it doesn't exist yet...

Unfortunately, it's not as easy as it seems. Even when I managed to create a new build item to resolve the cycle issue, then my build step is still not executed as the FeatureBuildItem items have been already processed.

**Comment by mkouba** [comment]
So does the [`BuildProducer<ArtifactResultBuildItem>`](https://github.com/quarkusio/quarkus/issues/27314#issuecomment-1217896713) solve your problem?

**Comment by Sgitario** [comment]
> So does the [`BuildProducer<ArtifactResultBuildItem>`](https://github.com/quarkusio/quarkus/issues/27314#issuecomment-1217896713) solve your problem?

Yep, it did. I'm closing this ticket spite of I think we should refactor the kubernetes solution.
