### ISSUE TITLE
Flyway: New config property to run `repair` before `migrate`

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#27329]
### Description

Flyway has a `repair` command (see https://flywaydb.org/documentation/command/repair), which has the following uses:
- Remove failed migration entries (only for databases that do NOT support DDL transactions)
- Realign the checksums, descriptions, and types of the applied migrations with the ones of the available migrations
- Mark all missing migrations as deleted

I really like the Quarkus Flyway `migrate-at-start` option. When using that I don't quite see how I can easily run a `repair` command in production, should that ever be necessary. So I propose that there is something like a `repair-at-start` or `repair-before-migrate` config which can be set to allow for this use case.

**Comment by geoand** [comment]
Seems reasonable to me. @knutwannheden would you like to take a stab at implementing it?

**Comment by knutwannheden** [comment]
@geoand Yes, it looks like we will have time to look into this for one of the next few Quarkus minor releases.

**Comment by geoand** [comment]
Cool!
