### ISSUE TITLE
Resteasy Reactive duplicates headers when custom WriterInterceptor is present

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#27325]
### Describe the bug

After migrating my app to resteasy-reactive, I noticed that all response headers I set myself are being duplicated.
Headers set by quarkus, like content-length and content-type, are only present once in the response as expected

Essentially, whenever a custom writerinterceptor is present in the app, all custom response headers are duplicated. The interceptor does not even have to do anything.

This duplication did not happen with resteasy classic.

```
@Provider
public class CachePolicyHeaderProvider implements WriterInterceptor {

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        context.proceed();
    }
}
```

```
@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response hello() {
        return Response.ok("123").lastModified(new Date()).header("etag", 0).build();
    }
}
```

### Expected behavior

No headers are getting duplicated.

### Actual behavior

![image](https://user-images.githubusercontent.com/1223135/185046176-0b622b31-a9b6-4d19-a7ca-bc2d13096662.png)

### How to Reproduce?

Reproducer: 
[Uploading etag-duplication.zip…]()

1. mvn quarkus:dev
2. go to http://localhost:8080/hello in a browser
3. look at the servers response in the network view
4. notice the response headers being duplicated

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1889]

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19 OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 18.0.2, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\18 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Postremus** [comment]
FTR.
I can work around this bug by using a ContainerResponseFilter instead of a WriterInterceptor.

**Comment by geoand** [comment]
Thanks for reporting. https://github.com/quarkusio/quarkus/pull/27406 takes care of it
