### ISSUE TITLE
Gradle plugin does not detect all extensions in the dependency tree

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#27323]
### Describe the bug

This one took me a bit to pin down in [Zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Direct.20dependencies.20are.20the.20only.20extensions.20that.20are.20active.3F). I appreciate the patience. I may still have some details wrong but I feel like I understand enough to write an issue.

It appears that, simply put, the Quarkus Gradle plugin scans the entire tree for extensions, but it stops iterating through a branch of transitive dependencies once it finds that a dependency is an extension. This means that if an extension ("upper" in the repro) has a dependency on another extension ("lower" in the repro) that second "lower" extension won't be activated.

The code that triggers this bug seems to be a simple if-else [here](https://github.com/quarkusio/quarkus/blob/584db00f9cf8828cb1f344dbf3e575fb0897a37f/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ApplicationDeploymentClasspathBuilder.java#L280):
```java
    private Set<ExtensionDependency> collectQuarkusExtensions(ResolvedDependency dependency, Set<String> visitedArtifacts,
            Collection<ExtensionDependency> knownExtensions) {
        String artifactKey = String.format("%s:%s", dependency.getModuleGroup(), dependency.getModuleName());
        if (!visitedArtifacts.add(artifactKey)) {
            return Collections.emptySet();
        }

        Set<ExtensionDependency> extensions = new LinkedHashSet<>();
        ExtensionDependency extension = getExtensionOrNull(dependency.getModuleGroup(), dependency.getModuleName(),
                dependency.getModuleVersion(), knownExtensions);
        if (extension != null) {
            extensions.add(extension);
        } else {
            for (ResolvedDependency child : dependency.getChildren()) {
                extensions.addAll(collectQuarkusExtensions(child, visitedArtifacts, knownExtensions));
            }
        }
        return extensions;
    }
```

The "for" loop at the end of this block appears to be something that might be worth running regardless of whether the dependency is an extension or not, as right now it is skipped if the dependency is an extension.

### Expected behavior

Per the Zulip chat, "all extensions wherever they are in the dependency tree are expected to be picked up." I was not sure what was expected before the chat, so hopefully my interpretation here is correct.

### Actual behavior

All extensions, as long as they are not _solely_ transient dependencies of another extension, will be picked up.

### How to Reproduce?

Reproducer: https://github.com/jskillin-idt/quarkusio-quarkus-issues-27323

This reproducer is a little busy because it's built on a repro I wrote for Camel, but the goal is to simply have some beans fly around and do something so that I can prove whether or not an extension is activated properly.

What is failing here is that, while the "app" project depends on the "upper" extension, and the "upper" extension depends on the "lower" extension, the "lower" extension is never activated. The "app" instead must explicitly depend on both.

1. Clone the reproducer.
2. Run `./gradlew build`. There should be a unit test failure as the extension that provides the bean is not activated.
3. The workaround for the issue is to add the missing runtime dependency explicitly. See `app/build.gradle` in the repro for an example.

### Output of `uname -a` or `ver`

Linux jacob-ubuntu-dev 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-122.04) OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-122.04, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by jskillin-idt** [comment]
> You added a link to a Zulip discussion, please make sure the description of the issue is comprehensive and doesn't require accessing Zulip.
> 
> > This message is automatically generated by a bot.

The Zulip link is just for historical context. The issue should contain everything required.

**Comment by jskillin-idt** [comment]
The reproducer has been added and I also added an explanation for exactly what in the repro is not working when the unit test fails.

**Comment by jskillin-idt** [comment]
Another diagnostic I discovered late in the debugging process for this issue is `./gradlew :app:dependencies --configuration quarkusTestRuntimeClasspathConfigurationDeployment` will reveal what deployment extensions got activated by the plugin.

**Comment by gsmet** [comment]
I think this was fixed long ago.

I applied the following patch and had the tests green:

```
diff --git a/app/build.gradle b/app/build.gradle
index 21f23ab..7971e54 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -1,7 +1,6 @@
 plugins {
     id 'java-library'
     id 'io.quarkus'
-    id 'org.kordamp.gradle.jandex'
 }
 
 group 'org.acme'
@@ -23,4 +22,4 @@ test {
         showStandardStreams = true
         exceptionFormat = 'full'
     }
-}
\ No newline at end of file
+}
diff --git a/gradle.properties b/gradle.properties
index 9d40bf8..03bfd8f 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,2 +1,2 @@
-quarkusVersion=2.11.2.Final
+quarkusVersion=3.13.3
 org.gradle.configureondemand=true
diff --git a/lower-deployment/src/main/java/org/acme/ExampleProcessor.java b/lower-deployment/src/main/java/org/acme/ExampleProcessor.java
index a0c79ff..5ef0851 100644
--- a/lower-deployment/src/main/java/org/acme/ExampleProcessor.java
+++ b/lower-deployment/src/main/java/org/acme/ExampleProcessor.java
@@ -8,7 +8,7 @@ import io.quarkus.deployment.annotations.BuildStep;
 import io.quarkus.deployment.annotations.Record;
 import java.util.List;
 import java.util.stream.Collectors;
-import javax.enterprise.context.ApplicationScoped;
+import jakarta.enterprise.context.ApplicationScoped;
 import org.acme.builditem.ExampleBuildItem;
 import org.acme.config.ExampleConfig;
 
diff --git a/settings.gradle b/settings.gradle
index c539129..080f89e 100644
--- a/settings.gradle
+++ b/settings.gradle
@@ -6,7 +6,7 @@ pluginManagement {
     plugins {
         id 'io.quarkus' version "${quarkusVersion}"
         id 'io.quarkus.extension' version "${quarkusVersion}"
-        id 'org.kordamp.gradle.jandex' version '0.13.2'
+        id 'org.kordamp.gradle.jandex' version '2.0.0'
     }
 }
 
diff --git a/upper-deployment/build.gradle b/upper-deployment/build.gradle
index 6b8726e..6bdc2bb 100644
--- a/upper-deployment/build.gradle
+++ b/upper-deployment/build.gradle
@@ -9,4 +9,5 @@ version '1.0-SNAPSHOT'
 dependencies {
     implementation platform("io.quarkus:quarkus-bom:${quarkusVersion}")
     implementation project(':upper')
+    implementation project(':lower-deployment')
 }
```

**Comment by jskillin-idt** [comment]
Hey @gsmet,

Am I right in understanding that upper-deployment depending on upper, which depends on lower, which is an extension, means that lower-deployment should appear in upper-deployment without needing the extra explicit dependency? That is what this bug was originally demonstrating.

If I apply your patch but comment out the added `implementation project(':lower-deployment'` line from `upper-deployment/build.gradle` this produces a validation error:

```
> Task :upper:validateExtension FAILED                                                       
Quarkus Extension Dependency Verification Error                                              
The following deployment artifact(s) were found to be missing in the deployment module:      
- org.acme:lower-deployment                                                                  
- io.quarkus:quarkus-core-deployment                                                         
```

Is this expected? The dependency tree was specifically set up to demonstrate one extension depending on another, and trying to get them to both activate in the dependent's tests. The error seems to indicate that you must exhaustively direct and transitive extension dependencies? The existing documentation seems to suggest "[Quarkus extension dependencies are usually configured in the same way as any other project dependencies in the project’s build file, e.g. the Maven pom.xml or the Gradle build scripts"](https://quarkus.io/guides/conditional-extension-dependencies) but I don't know if the documentation is behind the times?
