### ISSUE TITLE
Mssql updated driver requires an undocumented configuration property

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#27330]
### Describe the bug

Quarkus Upstream
Extension: `quarkus-jdbc-mssql`
Related to: https://github.com/quarkusio/quarkus/commit/bccd9a1b3e125649cd0b91fb5e4d3af34bed92fc#diff-f1a3b4e6df9f63193be9632bac4425e522e28a3445149dfde5510c213f4a4493R8

When I am running a Quarkus application with Mssql I am getting an error due to a missing required property that should be added to your application.properties

application.properties

```
quarkus.datasource.jdbc.additional-jdbc-properties.trustservercertificate=true
```

I am missing some notes or documentation that point to this required property. 

### Output of `uname -a` or `ver`

Linux localhost.localdomain 5.18.13-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:20:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8) OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

### Quarkus version or git rev

upstream

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

**Comment by pjgg** [comment]
@Sanne

**Comment by Sanne** [comment]
Yes this is annoying but it's the default behaviour and requirements of SQL Server.

I understand it's for safety so I'm not going to patch our extensions to set such a property automatically; we could consider disabling TLS for dev-services though.

We could add a link to the microsoft documentation? But in general I'm expecting people that use database X to also read the documtation of database X :)

**Comment by geoand** [comment]
I think we can close this as no one complained about it, so I assume that people are doing what @Sanne hoped for :)
