### ISSUE TITLE
Resteasy-reactive void endpoint reported as "Run time writers required"

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#27338]
### Describe the bug

In dev the UI in the reasteasy reactive endpoint scoring part, my "void" 204 controller are shown as "Run time writers required" but the writer can be determined at compile time  

### Expected behavior

The correct writer is reported in the Dev UI console

### Actual behavior

The endpoint is reported "Run time writers required"

### How to Reproduce?

1. Create a 2.11.2.Final Quarkus app
2. Add the resteasy reactive extension
3. Create an endpoint returning "void"
4. Go to the dev UI

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/27413 takes care of the issue.
