### ISSUE TITLE
vertx cluster fail in native mode:java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath

### ISSUE THREAD

**Issue by hellomaybe** [quarkusio/quarkus#27347]
This is a complete example of Vert Cluster running properly in JVM mode, but not in native mode. You can download the project from Github and reproduce the error

>  git clone git@github.com:hellomaybe/quarkus-native-test.git
>  cd quarkus-native-test/
>  mvn clean package -Dnative
>  cd target/native-test-1.0.0.RELEASE-native-image-source-jar
>  java -jar native-test-1.0.0.RELEASE-runner.jar

  **it will run success , log below**

>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:45:29,881 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] (executor-thread-0) Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
>  --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
> 2022-08-18 15:45:29,928 INFO  [com.haz.system] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Hazelcast 4.2.2 (20210811 - c38011e) starting at [192.168.66.17]:5701
> 2022-08-18 15:45:30,064 INFO  [com.haz.spi.dis.int.DiscoveryService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] No discovery strategy is applicable for auto-detection
> 2022-08-18 15:45:30,107 INFO  [com.haz.ins.imp.Node] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Using Multicast discovery
> 2022-08-18 15:45:30,108 WARNING [com.haz.cp.CPSubsystem] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
> 2022-08-18 15:45:30,234 INFO  [com.haz.int.dia.Diagnostics] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
> 2022-08-18 15:45:30,237 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTING
> 2022-08-18 15:45:33,359 INFO  [com.haz.int.clu.ClusterService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2]
> 
> Members {size:1, ver:1} [
>         Member [192.168.66.17]:5701 - fa091a3b-ffa9-4064-ab4f-fefe943a99e1 this
> ]
> 
> 2022-08-18 15:45:33,364 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTED
> 2022-08-18 15:45:33,405 INFO  [com.haz.int.par.imp.PartitionStateManager] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Initializing cluster partition table arrangement...
> 2022-08-18 15:45:33,462 INFO  [io.quarkus] (main) native-test 1.0.0.RELEASE on JVM (powered by Quarkus 2.11.2.Final) started in 4.069s. Listening on: http://0.0.0.0:8082
> 2022-08-18 15:45:33,463 INFO  [io.quarkus] (main) Profile prod activated.
> 2022-08-18 15:45:33,464 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, resteasy-reactive-jackson

**but if run in native mode** 

> cd  /quarkus-native-test/target/
> ./native-test-1.0.0.RELEASE-runner

it will fail , log below 

> __  ____  __  _____   ___  __ ____  ______
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:50:42,358 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath
>         at io.vertx.core.impl.VertxBuilder.clusteredVertx(VertxBuilder.java:245)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:222)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:589)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:571)
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:280)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
>         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
>         at io.quarkus.runtime.Application.start(Application.java:101)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
>         at io.quarkus.runner.GeneratedMain.main(Unknown Source)

**Comment by Sgitario** [comment]
@hellomaybe we're going to need a reproducer to better help with this issue. Thanks.

**Comment by hellomaybe** [comment]
@Sgitario  This is a complete example of Vert Cluster running properly in JVM mode, but not in native mode. You can download the project from Github and reproduce the error

>  git clone git@github.com:hellomaybe/quarkus-native-test.git
>  cd quarkus-native-test/
>  mvn clean package -Dnative
>  cd target/native-test-1.0.0.RELEASE-native-image-source-jar
>  java -jar native-test-1.0.0.RELEASE-runner.jar

  **it will run success , log below**

>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:45:29,881 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] (executor-thread-0) Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
>  --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
> 2022-08-18 15:45:29,928 INFO  [com.haz.system] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Hazelcast 4.2.2 (20210811 - c38011e) starting at [192.168.66.17]:5701
> 2022-08-18 15:45:30,064 INFO  [com.haz.spi.dis.int.DiscoveryService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] No discovery strategy is applicable for auto-detection
> 2022-08-18 15:45:30,107 INFO  [com.haz.ins.imp.Node] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Using Multicast discovery
> 2022-08-18 15:45:30,108 WARNING [com.haz.cp.CPSubsystem] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
> 2022-08-18 15:45:30,234 INFO  [com.haz.int.dia.Diagnostics] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
> 2022-08-18 15:45:30,237 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTING
> 2022-08-18 15:45:33,359 INFO  [com.haz.int.clu.ClusterService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2]
> 
> Members {size:1, ver:1} [
>         Member [192.168.66.17]:5701 - fa091a3b-ffa9-4064-ab4f-fefe943a99e1 this
> ]
> 
> 2022-08-18 15:45:33,364 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTED
> 2022-08-18 15:45:33,405 INFO  [com.haz.int.par.imp.PartitionStateManager] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Initializing cluster partition table arrangement...
> 2022-08-18 15:45:33,462 INFO  [io.quarkus] (main) native-test 1.0.0.RELEASE on JVM (powered by Quarkus 2.11.2.Final) started in 4.069s. Listening on: http://0.0.0.0:8082
> 2022-08-18 15:45:33,463 INFO  [io.quarkus] (main) Profile prod activated.
> 2022-08-18 15:45:33,464 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, resteasy-reactive-jackson

but if run in native mode 

> cd  /quarkus-native-test/target/
> ./native-test-1.0.0.RELEASE-runner

it will fail , log below 

> __  ____  __  _____   ___  __ ____  ______
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:50:42,358 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath
>         at io.vertx.core.impl.VertxBuilder.clusteredVertx(VertxBuilder.java:245)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:222)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:589)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:571)
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:280)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
>         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
>         at io.quarkus.runtime.Application.start(Application.java:101)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
>         at io.quarkus.runner.GeneratedMain.main(Unknown Source)

**Comment by hellomaybe** [comment]
@Sgitario  This is a complete example of Vert Cluster running properly in JVM mode, but not in native mode. You can download the project from Github and reproduce the error

>  git clone git@github.com:hellomaybe/quarkus-native-test.git
>  cd quarkus-native-test/
>  mvn clean package -Dnative
>  cd target/native-test-1.0.0.RELEASE-native-image-source-jar
>  java -jar native-test-1.0.0.RELEASE-runner.jar

  **it will run success , log below**

>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:45:29,881 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] (executor-thread-0) Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
>  --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
> 2022-08-18 15:45:29,928 INFO  [com.haz.system] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Hazelcast 4.2.2 (20210811 - c38011e) starting at [192.168.66.17]:5701
> 2022-08-18 15:45:30,064 INFO  [com.haz.spi.dis.int.DiscoveryService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] No discovery strategy is applicable for auto-detection
> 2022-08-18 15:45:30,107 INFO  [com.haz.ins.imp.Node] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Using Multicast discovery
> 2022-08-18 15:45:30,108 WARNING [com.haz.cp.CPSubsystem] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
> 2022-08-18 15:45:30,234 INFO  [com.haz.int.dia.Diagnostics] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
> 2022-08-18 15:45:30,237 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTING
> 2022-08-18 15:45:33,359 INFO  [com.haz.int.clu.ClusterService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2]
> 
> Members {size:1, ver:1} [
>         Member [192.168.66.17]:5701 - fa091a3b-ffa9-4064-ab4f-fefe943a99e1 this
> ]
> 
> 2022-08-18 15:45:33,364 INFO  [com.haz.cor.LifecycleService] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] [192.168.66.17]:5701 is STARTED
> 2022-08-18 15:45:33,405 INFO  [com.haz.int.par.imp.PartitionStateManager] (executor-thread-0) [192.168.66.17]:5701 [dev] [4.2.2] Initializing cluster partition table arrangement...
> 2022-08-18 15:45:33,462 INFO  [io.quarkus] (main) native-test 1.0.0.RELEASE on JVM (powered by Quarkus 2.11.2.Final) started in 4.069s. Listening on: http://0.0.0.0:8082
> 2022-08-18 15:45:33,463 INFO  [io.quarkus] (main) Profile prod activated.
> 2022-08-18 15:45:33,464 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, resteasy-reactive-jackson

but if run in native mode 

> cd  /quarkus-native-test/target/
> ./native-test-1.0.0.RELEASE-runner

it will fail , log below 

> __  ____  __  _____   ___  __ ____  ______
>  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
>  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
> --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
> 2022-08-18 15:50:42,358 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath
>         at io.vertx.core.impl.VertxBuilder.clusteredVertx(VertxBuilder.java:245)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:222)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:589)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:571)
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:280)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
>         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
>         at io.quarkus.runtime.Application.start(Application.java:101)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
>         at io.quarkus.runner.GeneratedMain.main(Unknown Source)

**Comment by hellomaybe** [comment]
> @hellomaybe we're going to need a reproducer to better help with this issue. Thanks.

Can you run this demo successfully in Native packaging mode?
demo：https://github.com/hellomaybe/quarkus-native-test

**Comment by Sgitario** [comment]
I see you're using `vertx-hazelcast` which is not compatible with native yet. 
This issue is duplicated by https://github.com/quarkusio/quarkus/issues/9877.

**Comment by jpforevers** [comment]
> I see you're using `vertx-hazelcast` which is not compatible with native yet. This issue is duplicated by #9877.
