### ISSUE TITLE
can't find the redis client

### ISSUE THREAD

**Issue by PyAntony** [quarkusio/quarkus#27344]
### Describe the bug

Hi,

I can't find the redis client with the following dependency (as indicated in https://quarkus.io/guides/redis-reference):
```
<dependency>
    <groupId>io.quarkiverse.redis</groupId>
    <artifactId>quarkus-redis</artifactId>
</dependency>
```

I get the following message:

io.quarkiverse.redis:quarkus-redis:jar:unknown was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced

Where should I get the *RedisDataSource*?

**Comment by cescoffier** [comment]
The group id is io.quarkus. Let me check if we miss a few occurrences.

**Comment by PyAntony** [comment]
Thanks for quick response. Yes it works with:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-redis-client</artifactId>
    </dependency>
 ```   

version has to be 2.11 though:
```
<quarkus.platform.version>2.11.1.Final</quarkus.platform.version>
```

2.10 doesn't work.

**Comment by PyAntony** [comment]
Found another typo in the documentation (https://quarkus.io/guides/redis-reference). There are a few instances of **RedisReactiveDataSource**, but it should be **ReactiveRedisDataSource**. **RedisReactiveDataSource** doesn't exist. Is there an easy way to contribute to documentation without cloning/forking?

**Comment by cescoffier** [comment]
You can do it from the GitHub interface. It will fork the repo behind the hood, but you will do everything in the browser.
