### ISSUE TITLE
Jackson: also detect class referenced by `@JsonTypeIdResolver`

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#27346]
### Describe the bug

`io.quarkus.jackson.deployment.JacksonProcessor` detects the classes referenced by e.g. `@JsonSerialize`, `@JsonDeserialize`, but it doesn't handle classes referenced by `@JsonTypeIdResolver` annotations.

It seems that "just handling" the value of `JsonTypeIdResolver.value()` like `JsonDeserialize.using()` should fix this.

Could someone quickly cross-check whether my assumption sounds legit? Happy to provide a PR with the described change to fix this issue.

**Comment by gsmet** [comment]
@snazy yes, it makes perfect sense.

**Comment by snazy** [comment]
@gsmet created the PR
