### ISSUE TITLE
Quarkus 2.12.0.CR1 - Map style config property resolution does not work in native mode 

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#27353]
### Describe the bug

In Camel Quarkus it's possible to have some configuration like the following in `application.properties`:

```
camel.threadpool.config[customPool].id = customPool
camel.threadpool.config[customPool].pool-size = 1
camel.threadpool.config[customPool].rejectedPolicy = Abort
```

Where the `config[customPool]` part denotes a map key that Camel can resolve internally. This all works fine in JVM mode. Since ` 2.12.0.CR1`, resolution of such properties no longer seems to work in native mode. The config keys seem to be present, but their associated values are not resolvable.

### Expected behavior

The properties are resolvable as expected in native mode.

### Actual behavior

See comments in the main description. 

### How to Reproduce?

There's a reproducer project here:

https://github.com/jamesnetherton/smallrye-config-demo

See instructions in the README for how to run. Tests fail with `2.12.0.CR1`, they pass with `2.11.2.Final`.

**Comment by gsmet** [comment]
@radcortez could you have a look at this one? It looks like a blocker for 2.12.

**Comment by geoand** [comment]
This is almost certainly caused by https://github.com/quarkusio/quarkus/pull/26802.

The reason it works in JVM mode is because in that case the property read directly from the JAR file. 
However in native mode, the property is attempted to be read by `DefaultsConfigSource` and it's superclass (`KeyMapBackedConfigSource` which I don't really understand as it's complex and I've never looked at it before) does not handle `[` and `]` correctly.

**Comment by gsmet** [comment]
So question: is the cure worst than the disease? My understanding is that any map based config won't work in native from now on? It seems like something problematic and I wonder if we should revert this particular patch until @radcortez can revisit it.

WDYT?

**Comment by gsmet** [comment]
After discussion with @geoand , it only affects using brackets which is not what we recommend (we recommend the dot notation even for maps). So we can live with it for .0.Final and we will discuss it when @radcortez is back.

**Comment by radcortez** [comment]
This requires a new release of SR Config with https://github.com/smallrye/smallrye-config/pull/805.
