### ISSUE TITLE
Investigate if it makes sense to generate Job instead of Deployement for cli projects

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#27365]
### Description

Currently, if the user creates a cli project with soemthing like: `quarkus crate cli foo` and adds the `quarkus-kubernetes` extension a `Deployement`will get generated. It might make sense to generate a `Job` instead that will fire a once of job instead.

I am not sure myself what is the best option here, so let's investigate.

**Comment by geoand** [comment]
Isn't this a duplicate of https://github.com/quarkusio/quarkus/issues/27024?

**Comment by iocanel** [comment]
It is
