### ISSUE TITLE
OpenAPI extension does not honour BV @NotNull / @NotEmpty

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#27375]
### Describe the bug

Putting a `@NotNull` or `@NotEmpty` annotation on a method parameter should end up in openapi.json as marking the parameter required

```
    @POST
    public void addFoo(@NotEmpty @NotNull String foo) {
        ;
    }
```

results in 

```
      "post" : {
        "tags" : [ "Main" ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "string"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Created"
          }
        }
      }
    }

```

Even with those two annotations present an explicit `@RequestBody(required = true)` is needed

### Expected behavior

Mark the method parameter as required once one of the 2 bean-validation annotations are present

**Comment by phillip-kruger** [comment]
@MikeEdgar this is probably something we need to do in SmallRye ?

**Comment by pilhuhn** [comment]
Actually I think that should even be put into the MP-OpenAPI spec to start with.

**Comment by MikeEdgar** [comment]
> something we need to do in SmallRye ?

Yes - I'll look at it.
