### ISSUE TITLE
MockitoExtension is ignored during continuous testing

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#27383]
### Describe the bug

Applying `@ExtendWith(MockitoExtension.class)` to a test annotated with `@QuarkusTest` will work, but only with "normal" testing (`mvn clean test`), not with continuous testing (`mvn quarkus:test` or `mvn quarkus:dev` + type `r`).

One of the goals of `MockitoExtension` is to enable "strict stubs", which among other things will remove the need for verifying each stubbed invocation explicitly (`Mock.verify(...)`).

Evidently, in continuous testing, "strict stubs" are *not* enabled, resulting in test failures if the tests were written with strict stubs in mind.

### Expected behavior

I would expect continuous testing to yield the same result as a normal `mvn clean test`: Mockito interaction verifications pass without me needing to verify each stubbed invocation explicitly.

### Actual behavior

Mockito interaction verifications fail because some stubbed invocations were not verified (`Mockito.verify(...)`) explicitly.

### How to Reproduce?

See reproducer: https://github.com/yrodiere/quarkus-playground/tree/mockito-extension (careful, the reproducer is not on the main branch, but on branch `mockito-extension`)

### Output of `uname -a` or `ver`

Linux yrodiere.redhat 5.18.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 3 15:44:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /home/yrodiere/tools/sdkman/candidates/maven/current Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: /home/yrodiere/tools/java/jdk-17.0.2+8 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.18.16-200.fc36.x86_64", arch: "amd64", family: "unix"

### Additional information

The cause for this problem seems to be that `MockitoExtension` relies on a static variable (a threadlocal, but that's irrelevant) to store the information "strict stubs are enabled", and it turns out the classloader is different when `MockitoExtension` executes and when the test executes.

* When `MockitoExtension` executes:
  * With "normal" testing, the TCCL is `jdk.internal.loader.ClassLoaders$AppClassLoader`
  * With continuous testing, the TCCL is `QuarkusClassLoader:Deployment Class Loader: TEST`
* When the test executes, the TCCL is (always) `Quarkus Base Runtime ClassLoader: TEST`

I suspect that `Quarkus Base Runtime ClassLoader: TEST` is a child of `AppClassLoader` and thus eventually reuses classes from `AppClassLoader` (and the corresponding static variables). It's not a child of `QuarkusClassLoader:Deployment Class Loader: TEST`, though, so it cannot "see" the classes and static variables from that classloader.

Shouldn't continuous testing and normal testing use a similar TCCL when initializing tests / executing extensions?

**Comment by famod** [comment]
FWIW, `@ExtendWith(MockitoExtension.class)` does work in general in CT for **non**-`@QuarkusTest`s, but it also has some classloading issues: #38987

**Comment by Ladicek** [comment]
I can't reproduce this with current Quarkus. In fact, it seems to have been fixed in Quarkus 2.15.3.Final (and 2.16.0.Final), which is a _long_ time ago :-) I can't attribute the fix directly to any change in https://github.com/quarkusio/quarkus/releases/tag/2.15.3.Final, but `mvn clean quarkus:test` just passes with that version (and fails with 2.15.2.Final).

Unless anyone objects, I'll remove this from the Test CL WG and close.

**Comment by yrodiere** [comment]
I just checked, and can confirm continuous testing now passes in my project that uses `@ExtendWith(MockitoExtension.class)`.

Closing as obsolete, thank you for digging this up!
