### ISSUE TITLE
OpenTelemetry: server spans of failed requests have no exception event

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#27384]
### Describe the bug

When a REST request fails with a 500 status code I think the corresponding OpenTelemetry trace span would be expected to contain an exception event. But it seems like there is no information regarding the exception in the span.

### Expected behavior

See issue description. I think this should work for both RestEasy Reactive and RestEasy Classic.

I am almost sure that this worked at some point, but I checked with a few older versions now and couldn't get it to work.

### Actual behavior

When a REST endpoint throws a runtime exception then a OpenTelemetry span with an error status is created, but it doesn't have any exception event attached to it with the exception message, type, and stack trace.

I think that the mentioned information should be available as an event attached to the span. Possibly it would make sense to have a config property with which this behavior can be toggled, but I honestly don't know if the spec has anything to say about this.

### How to Reproduce?

Steps to reproduce:

1. Download und unzip [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9382988/code-with-quarkus.zip)
2. Run `mvn verify` to check results of `org.acme.GreetingResourceTest#testExceptionInTrace`

### Quarkus version or git rev

2.12.0.CR1

### Additional information

I am however positive that this was working properly while Quarkus was still using OpenTracing. Possibly it is still working with the OpenTracing extension.

**Comment by brunobat** [comment]
This might be similar to [RestClient errors statuscode are not shown in micrometer #25951](https://github.com/quarkusio/quarkus/issues/25951)
