### ISSUE TITLE
Native build runtime lib error

### ISSUE THREAD

**Issue by csscriptplus** [quarkusio/quarkus#27382]
### Describe the bug

I use Jenkins to build my native application. Jenkins is running as a Pod in a Kubernetes cluster. Jenkins doesn't have a docker runtime environment. I use JIB for container building.
This is a part of my Jenkinsfile:

```
sh('''
                        	    wget -c https://github.com/graalvm/mandrel/releases/download/mandrel-22.2.0.0-Final/mandrel-java17-linux-amd64-22.2.0.0-Final.tar.gz
			                  	tar -xf mandrel-java17-linux-amd64-22.2.0.0-Final.tar.gz
								export JAVA_HOME="$( pwd )/mandrel-java17-22.2.0.0-Final"
								export GRAALVM_HOME="${JAVA_HOME}"
								export PATH="${JAVA_HOME}/bin:${PATH}"	  
                        
                            mvn clean package -U -Pnative \
								-Dintegration-tests.skip=true \
								-Dmaven.test.skip=true \
								-DsendCredentialsOverHttp=true \
								-Dquarkus.container-image.push=true \
								-Dquarkus.container-image.group=kubernetes \
								-Dquarkus.container-image.tag=${RELEASE_VERSION} \
								-Dquarkus.container-image.name=${ARTIFACT_ID} \
								-Dquarkus.container-image.insecure=true \
								-Dquarkus.container-image.registry=nexus-docker.xxxx.local \
								-Dquarkus.container-image.username=${NEXUS_USERNAME} \
								-Dquarkus.container-image.password=${NEXUS_PASSWORD} \
								-Dquarkus.container-image.build=true \
								-Dquarkus.jib.base-registry-username=${DOCKER_USERNAME} \
								-Dquarkus.jib.base-registry-password=${DOCKER_PASSWORD} \
								-Dquarkus.jib.base-native-image=quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17 \
								-Dquarkus.kubernetes.version=${RELEASE_VERSION} \
								-Dquarkus.kubernetes.image-pull-secrets=regcred \
								-Dquarkus.kubernetes.deployment-target=kubernetes \
								-Dquarkus.kubernetes.deployment-kind=StatefulSet \
								-Dquarkus.kubernetes.namespace=${Namespace} \
								-Dquarkus.kubernetes.ingress.expose=true \
								-Dquarkus.kubernetes.ingress.host=${ARTIFACT_ID_LOWERCASE}.xxxxx.local \
								-Dquarkus.native.native-image-xmx=6G
								
							cp target/kubernetes/kubernetes.yml target/kubernetes/${ARTIFACT_ID_LOWERCASE}.yml
                        ''')
```

The docker image is building and deployed as a Pod on the Kubernetes cluster. After the Pod started I got this exception:
./application: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./application)

### Quarkus version or git rev

2.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by geoand** [comment]
What base image are you using?

**Comment by geoand** [comment]
@galderz is there any reason why the base image `quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17` would not have glibc?

**Comment by galderz** [comment]
@csscriptplus What does the `Dockerfile` for the runtime container image look like?

**Comment by jerboaa** [comment]
>  After the Pod started I got this exception:
./application: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./application)

It appears the *runtime* image that you deploy your application to (via native), doesn't have the required `glibc` version of at least `GLIBC_2.29`. It should have the same or a later version of glibc than the build system (`quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17` in your case it seems). This requirement could also come from some application code. It's odd it's `2.29` as the ubi 8 image has glibc 2.28.

**Comment by zakkak** [comment]
@csscriptplus appears to be using a Mandrel tarball to build their image. So they are not using `quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17`, thus nor `ubi 8`, which explains how the application is ending up depending on glibc 2.29.

@csscriptplus, as @jerboaa mentions above, please make sure that your _runtime_ image includes the same or a later version of glibc than your _build_ system.

**Comment by csscriptplus** [comment]
@zakkak my runtime environment is the official Jenkins docker image and that is based on Debian 11. This contains glibc 2.31.
There are now 2 ways:

- I build my own runtime image.
- I change Jenkins, so that the build is no longer done in the Jenkins container, but in a slave Kubernetes pod and so I can also use the quarkus native image.

**Comment by zakkak** [comment]
Correct, IMO the second approach is the best:
1. You decouple your CI/CD env from the native-image build env
2. You build using the official/supported quarkus native image container (including the mandrel variant)
3. You keep using the official/supported quarkus generated runtime container images

**Comment by csscriptplus** [comment]
@zakkak a Kubernetes pod with Docker environment does not work for me, because the Kubernters cluster does not have a Docker environment. I have now created a Docker container with local Mandrel environment.

**application.properties:**
- quarkus.log.level=INFO
- quarkus.http.host=0.0.0.0
- quarkus.http.cors=true
- quarkus.smallrye-jwt.enabled=true
- mp.jwt.verify.publickey.location=publicKey.pem
- mp.jwt.verify.issuer=scriptplus
- smallrye.jwt.sign.key.location=privateKey.pem
- quarkus.datasource.db-kind=mysql
- quarkus.datasource.username=Unterboden
- quarkus.datasource.password=unterboden
- quarkus.datasource.jdbc.url=jdbc:mysql://mysql-8.development:3306/unterboden
- %eclipse.quarkus.datasource.db-kind=postgresql
- %eclipse.quarkus.datasource.username=postgres
- %eclipse.quarkus.datasource.password=postgrespw
- %eclipse.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:55000/unterboden
- quarkus.flyway.migrate-at-start=true
- quarkus.flyway.locations=db/migration/mysql
- %eclipse.quarkus.flyway.locations=db/migration/postgres
- quarkus.smallrye-openapi.path=/swagger
- quarkus.swagger-ui.always-include=true
- quarkus.swagger-ui.path=/swagger-ui
- image.path=/Users/Documents/
- quarkus.kubernetes.ingress.annotations."kubernetes.io/ingress.class"=nginx

**Maven command:**
` export JAVA_HOME=/mandrel-java17-22.2.0.0-Final
 export PATH=/mandrel-java17-22.2.0.0-Final/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 mvn clean package -U -Pnative -Dintegration-tests.skip=true -Dmaven.test.skip=true -DsendCredentialsOverHttp=true -Dquarkus.container-image.push=true -Dquarkus.container-image.group=kubernetes -Dquarkus.container-image.tag=1.0.0.71 -Dquarkus.container-image.name=unterboden-user-rest -Dquarkus.container-image.insecure=true -Dquarkus.container-image.registry=****-docker.****.local -Dquarkus.container-image.username=**** -Dquarkus.container-image.password=**** -Dquarkus.container-image.build=true -Dquarkus.jib.base-registry-username=**** -Dquarkus.jib.base-registry-password=**** -Dquarkus.jib.base-native-image=quay.io/quarkus/ubi-quarkus-native-image:22.2-java17 -Dquarkus.kubernetes.version=1.0.0.71 -Dquarkus.kubernetes.image-pull-secrets=regcred -Dquarkus.kubernetes.deployment-target=kubernetes -Dquarkus.kubernetes.deployment-kind=StatefulSet -Dquarkus.kubernetes.namespace=development-rest -Dquarkus.kubernetes.ingress.expose=true -Dquarkus.kubernetes.ingress.host=unterboden-user-rest.****.local`

**The native build is successful. But when deploying the image to the Kubernetes cluster I get the following error message:**
Sep 08, 2022 8:50:44 AM io.quarkus.runtime.ApplicationLifecycleManager run                                                                                                               
│ ERROR: Failed to start application (with profile prod)                                                                                                                                  
│ java.lang.NullPointerException                                                                                                                                                          
│     at java.util.Objects.requireNonNull(Objects.java:208)                                                                                                                                
│     at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)                                                                                                                        
│     at java.nio.file.Path.of(Path.java:147)                                                                                                                                              
│     at java.nio.file.Paths.get(Paths.java:69)                                                                                                                                            
│     at com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)                                                                                            
│     at java.security.AccessController.executePrivileged(AccessController.java:145)                                                                                                       
│     at java.security.AccessController.doPrivileged(AccessController.java:569)                                                                                                            
│     at com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)                                                                                                    
│     at com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)                                                                        
│     at com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)                                                                         
│     at com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)                                                                                
│     at com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)                                                                             
│     at com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)                                                                  
│     at com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)                                                                               
│     at com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)                                                                                     
│     at com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)                                                                                      
│     at com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)                                                                                                  
│     at java.lang.reflect.Method.invoke(Method.java:568)                                                                                                                                  
│     at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)                                                                                                             
│     at com.oracle.svm.core.containers.Container.metrics(Container.java:44)                                                                                                               
│     at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)                                                                                                                   
│     at com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)                                                                                                          
│     at java.lang.Runtime.availableProcessors(Runtime.java:245)                                                                                                                           
│     at org.wildfly.common.cpu.ProcessorInfo.availableProcessors(ProcessorInfo.java:29)                                                                                                   
│     at io.quarkus.vertx.core.runtime.VertxCoreRecorder.calculateDefaultIOThreads(VertxCoreRecorder.java:382)                                                                            
│     at io.quarkus.vertx.core.runtime.VertxCoreRecorder.calculateEventLoopThreads(VertxCoreRecorder.java:506)                                                                             
│     at io.quarkus.deployment.steps.VertxCoreProcessor$eventLoopCount1012482323.deploy_0(Unknown Source)                                                                                  
│     at io.quarkus.deployment.steps.VertxCoreProcessor$eventLoopCount1012482323.deploy(Unknown Source)                                                                                    
│     at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)                                                                                                                         
│     at io.quarkus.runtime.Application.start(Application.java:101)                                                                                                                        
│     at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)                                                                                          
│     at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)                                                                                                                                   
│     at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)                                                                                                                                   
│     at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)                                                                                                                                  
│     at io.quarkus.runner.GeneratedMain.main(Unknown Source)

I don't understand what Linux path is being looked for now.

**Comment by zakkak** [comment]
@csscriptplus does the same application work locally and only fail on the CI/CD environment?

Have you tried running the native image on a local machine instead of a kubernetes cluster?

**Comment by jerboaa** [comment]
@csscriptplus The issue you are observing looks to me the GraalVM equivalent of: https://bugs.openjdk.org/browse/JDK-8272124

Could you please create a native-image issue and tag me? I will try to fix it.

As a work-around, you could pass `-Dquarkus.native.additional-build-args=-H:-UseContainerSupport` when building the native image.

**Comment by jerboaa** [comment]
Anyway, it's not a quarkus issue and we should close this.

**Comment by gunnarmorling** [comment]
For future reference for folks also running into this, here's the issue in GraalVM: https://github.com/oracle/graal/issues/4757.
