### ISSUE TITLE
`QuarkusTestResource` with `restrictToAnnotatedClass` restarts for `@Nested` classes

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#27400]
### Describe the bug

Referencing #26639 and #26646.

When `QuarkusTestResource` is configured to be `restrictToAnnotatedClass`, it restarts for nested classes annotated with `@Nested`. This is also the case for `QuarkusTestResourceConfigurableLifecycleManager`, which apply `restrictToAnnotatedClass` automatically.

### Expected behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` should not restart for nested classes annotated with @Nested.

### Actual behavior

`QuarkusTestResource` configured with `restrictToAnnotatedClass=true` restarts for nested classes.

### How to Reproduce?

Can be reproduced using the tests introduced in #26646.

### Quarkus version or git rev

2.11.2

**Comment by geoand** [comment]
@Sgitario are you interested in this?

**Comment by Sgitario** [comment]
> @Sgitario are you interested in this?

Sure, will add it to my TODO list.

**Comment by Sgitario** [comment]
See my changes in https://github.com/quarkusio/quarkus/pull/27477.
I think that the resources should never be restarted for nested classes, regardless the value of the `restrictToAnnotatedClass` is. wdyt? @geoand

**Comment by geoand** [comment]
Yeah, I think that makes sense.
