### ISSUE TITLE
Add support for HandshakeRequest for a WebsocketEndpoint

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#27404]
### Description

Add support to be able to use `javax.websocket.server.HandshakeRequest` in a @Open endpoint in a websocket server.

This should enable better use of the onOpen event for websocket controllers, such as rate limiting ips 

### Implementation ideas

None

**Comment by mkouba** [comment]
It is possible to access the `io.quarkus.websockets.next.HandshakeRequest` in WS Next; either directly as an [`@OnOpen` callback method param](https://quarkus.io/guides/websockets-next-reference#method-parameters), or with [`@Inject WebSocketConnection conn`](https://quarkus.io/guides/websockets-next-reference#ws-connection) and `conn.handshakeRequest()`.

There is no plan to implement this as a non-portable feature of `quarkus-websockets`, i.e. the Jakarta WebSocket implementation.
