### ISSUE TITLE
Since 2.10.x, org.bson.types isn't present in quarkus & quarkus mongo dependency

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#27412]
### Describe the bug

Until 2.9.2, i can use this import:
`import org.bson.types.ObjectId;`

My pom contains theses following dependencies:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
    </dependency> 
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-panache</artifactId>
    </dependency>
```

Since Quarkus 2.10.x, this import isn't resolved.

But there is no update from the doc https://quarkus.io/guides/mongodb-panache, or in the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.10

**Comment by loicmathieu** [comment]
`org.bson.types.ObjectId` is in the classpath, it is provided by the bson library wich is a dependency of the MongoDB client. It is also directly used by the Quarkus code so if it was not present Quarkus MongoDB extension will not compile, see https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache/runtime/src/main/java/io/quarkus/mongodb/panache/PanacheMongoEntity.java#L3

Try to clean your project and make a fresh package via `mvn clean package`.
You can also clean your Maven repository, maybe a corrupted dependency was downloaded.

I'm closing this issue as it's not an issue on Quarkus side as the class is present.
