### ISSUE TITLE
Quarkus - MDC - Azure Application Insights

### ISSUE THREAD

**Issue by DominiqueClaes** [quarkusio/quarkus#27415]
### Describe the bug

I'm having trouble with configuring MDC for the default Quarkus Jboss logger and to expose the additional information to Azure Application Insight. When I run the application locally, than the information is shown correctly in my console but not in Azure Application Insights.

More information can also be found here: https://stackoverflow.com/questions/73388626/quarkus-mdc-azure-application-insights

### Expected behavior

The MDC information for the default Quarkus Jboss logger is available in Azure Application Insights.

### Actual behavior

The MDC information for the default Quarkus Jboss logger is not available in Azure Application Insights

### How to Reproduce?

application.yml:
```
quarkus:
    log:
        console:
            format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) [%X] %s%e%n"
```
code example:
```
import org.jboss.logging.Logger;

@Inject
Logger log;

@GET
@Path("/hello")
public String sayHello() {
    MDC.put("example", "abc");
    log.info("Say hello...");
    return "Hello";
}
```
### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.856]

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

The Quarkus application is deployed as an Azure Function where the application setting 'APPLICATIONINSIGHTS_CONNECTION_STRING' references the connection string of Azure Application Insights.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
