### ISSUE TITLE
Add default config sources to codegen config

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#27431]
### Description

Seems that the `Config` instance passed to the `CodeGenProvider` implementation does not have the default config sources configured. Therefore, if you need to resolve system properties, you're forced to look them up manually via `System.getProperty`.

It'd be nicer if you could resolve them automatically via the `Config` instance. It'd make overriding of config values via the command line a bit simpler to handle.

### Implementation ideas

Add `setAddDefaultSources(true)` to the config builder in `CodeGenerator.trigger()`.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/27436 takes care of it
