### ISSUE TITLE
Update tests with OTel semantic conventions

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#27441]
### Description

Once this OTel PR is done and opentelemetry-semconv is released: https://github.com/open-telemetry/opentelemetry-java/issues/4715, we need to update some tests that were failing here:

extensions/opentelemetry/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/GrpcOpenTelemetryTest.java
integration-tests/opentelemetry-grpc/src/test/java/io/quarkus/it/opentelemetry/grpc/OpenTelemetryGrpcTest.java

Code needs to be uncommented and updated to the correct convention.

**Comment by geoand** [comment]
Is this done and if not, is it still relevant?

**Comment by brunobat** [comment]
It is being done... It's a process. Will close.

**Comment by geoand** [comment]
,👌
