### ISSUE TITLE
Fix TODO in DropTargetsSampler.java

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27452]
See https://github.com/quarkusio/quarkus/pull/26898/files#r952770353

(Opening an issue as Roberto is on PTO)

**Comment by brunobat** [comment]
Please hold any work on this until https://github.com/quarkusio/quarkus/pull/26760 is merged.
Many things will change on the way can do samplers.

**Comment by geoand** [comment]
What's the status of this one?

**Comment by radcortez** [comment]
I believe this can move forward with the config stuff out of the way.

**Comment by brunobat** [comment]
@geoand this is fixed by https://github.com/quarkusio/quarkus/pull/34510, right?

**Comment by geoand** [comment]
Good point!
