### ISSUE TITLE
Quarkus native executable returns BAD 400 and no logs

### ISSUE THREAD

**Issue by guitcastro** [quarkusio/quarkus#27466]
### Describe the bug

I Have an simple API (1 endpoint), I can run it with success. But when running the native executable it always return 400 BAD request.

I can access the open-api UI, but the request always fail with no logs even when using Dquarkus.log.level=DEBUG  (It does log some initialization and others stuffs, but not the failed request).

The request is failing with an empty body message, which I never return on my API. 

### Expected behavior

The endpoint should work

### Actual behavior

The endpoint is not working and no log is provider 

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Guilherme.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.11.2-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
Can you please attach a sample application that exhibits the behavior you describe?

**Comment by guitcastro** [comment]
Sorry. That was my fault. Not a bug.

**Comment by geoand** [comment]
No problem, thanks for the update
