### ISSUE TITLE
Honour DOCKER_CONFIG location for jib credentials

### ISSUE THREAD

**Issue by njlaw** [quarkusio/quarkus#27460]
### Description

Presently, [jib looks in multiple locations for Docker registry credentials](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#using-docker-configuration-files); however, the JibProcessor in Quarkus does not use the same order and only looks for `${user.home}/.docker/config.json`.  Ideally the Quarkus jib processor would use the same lookup order as the upstream jib tools.

### Implementation ideas

Perhaps leveraging the [DefaultCredentialRetrievers](https://github.com/GoogleContainerTools/jib/blob/master/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java) from the upstream project would make the most sense?  I'm happy to attempt a pull request, but I'm not particularly familiar with the Quarkus coding style or project in general.

**Comment by geoand** [comment]
This is not true, see [this](https://github.com/quarkusio/quarkus/blob/2.12.0.CR1/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L327).

Are you seeing an issue where this does not work?>

**Comment by njlaw** [comment]
> This is not true, see [this](https://github.com/quarkusio/quarkus/blob/2.12.0.CR1/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L327).
> 
> 
> 
> Are you seeing an issue where this does not work?

If I'm reading it correctly, the logic in that function uses the supplied username and password if present; otherwise, it adds the credential helpers and the default Docker config.json file to the credential search path.  However, it does not take into account the DOCKER_CONFIG environment variable if it is set.

The upstream DefaultCredentialRetrievers [does] and adds a fair number of other Docker config locations (https://github.com/GoogleContainerTools/jib/blob/master/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java#L206).

Here's some log output from an instance where the DOCKER_CONFIG environment variable is set, but it still uses the default path:
```
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for njlaw/some-private-image:11...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=Docker config auths section defines credentials for registry-1.docker.io]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=LIFECYCLE, message=Using credentials from Docker config (/home/njlaw/.docker/config.json) for njlaw/some-private-image:11]
```

**Comment by geoand** [comment]
Thanks for the update.

Fair enough, we can add support for `DOCKER_CONFIG` as well.
