### ISSUE TITLE
Service binding doesn't work when using quarkus-reactive-mysql-client for MariaDB

### ISSUE THREAD

**Issue by xieshenzh** [quarkusio/quarkus#27468]
### Describe the bug

The `quarkus-reactive-mysql-client` extension is designed to work for [MariaDB](https://quarkus.io/guides/reactive-sql-clients#reactive-sql-clients-details), but it only supports [service binding for MySQL](https://github.com/quarkusio/quarkus/blob/709f09dab6b4549f8401f2238b0d0c819c1a1af7/extensions/reactive-mysql-client/runtime/src/main/resources/META-INF/services/io.quarkus.kubernetes.service.binding.runtime.ServiceBindingConverter#L1).
When using `quarkus-reactive-mysql-client` to connect MariaDB database service with `kubernetes-service-binding`, the binding doesn't work.

### Expected behavior

Quarkus reactive SQL client for MariaDB should support service binding for MariaDB.

### Actual behavior

The Quarkus reactive SQL client for MariaDB (i.e. `quarkus-reactive-mysql-client`) doesn't support service binding for MariaDB.

### How to Reproduce?

1. Create a simple quarkus application which connects to MariaDB with the `quarkus-reactive-mysql-client` extension. For example, use an application similar to [hibernate-reactive-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-reactive-quickstart).
2. Add the `kubernetes-service-binding` extension to the project.
3. Run the MariaDB service.
4. Follow the [instructions](https://quarkus.io/guides/deploying-to-kubernetes#service_binding) to configure the binding for MariaDB.
5. Build and run the quarkus application.

**Comment by geoand** [comment]
What exactly does not work?

**Comment by xieshenzh** [comment]
> What exactly does not work?

There is no specific reactive client for MariaDB. Users can only use `quarkus-reactive-mysql-client` for MariaDB.

But `quarkus-reactive-mysql-client` only has a `ServiceBindingConverter` for [MySQL](https://github.com/quarkusio/quarkus/blob/709f09dab6b4549f8401f2238b0d0c819c1a1af7/extensions/reactive-mysql-client/runtime/src/main/java/io/quarkus/reactive/mysql/client/runtime/MySQLServiceBindingConverter.java#L15), nothing for MariaDB. 
So if a user try to do MariaDB service binding (i.e. using the `kubernetes-service-binding` extension) with `quarkus-reactive-mysql-client`, it won't work.

**Comment by geoand** [comment]
> So if a user try to do MariaDB service binding

Do you know what the service binding type is in this case?

**Comment by xieshenzh** [comment]
> > So if a user try to do MariaDB service binding
> 
> Do you know what the service binding type is in this case?

I used the binding type `mariadb`. I should use `mysql` instead. 
Sorry for that. I am closing the issue.

**Comment by geoand** [comment]
👍🏼
