### ISSUE TITLE
o.fabric8.tekton-client as a quarkus library

### ISSUE THREAD

**Issue by manuelwallrapp** [quarkusio/quarkus#27470]
### Description

We are using o.fabric8.tekton-client quite often and need it for native build as well. So at the moment we wrap it ourselves but would appreciate if it would be part of the quarkus library like all the other kubernetes libs.
Would that be possible? 

### Implementation ideas

Here is an outdated version which references an old tekton-client library:
https://github.com/quarkiverse/quarkus-tekton-client

Could be done the same, as we do it internally, just maintained by the Quarkus team.

**Comment by geoand** [comment]
I am not sure if anything Tekton related would be part of the Quarkus core repositoryu - my preference would be no.

If the quarkiverse extension is not up to date, why not propose a PR to update it?

**Comment by maxandersen** [comment]
Yes, I would suggest just updating the quarkiverse repo. 

At some point might make sense to include in quarkus platform but yes not something we would put in quarkus core repo.

**Comment by manuelwallrapp** [comment]
That would be fine, if somebody would merge these.
https://github.com/quarkiverse/quarkus-tekton-client/pulls

I would do it if I have the right to.

**Comment by geoand** [comment]
@maxandersen can you perhaps help push that forward?

**Comment by geoand** [comment]
In any case, I'll close this issue as `won't fix`
