### ISSUE TITLE
RESTEasy Reactive: Explicit @RequestScoped resource and instance variable with @PathParam or @RestPath does not work

### ISSUE THREAD

**Issue by knuspertante** [quarkusio/quarkus#27473]
### Describe the bug

Hey Guys, 

when I currently switched to RESTEasy Reactive the following issue came up. 

The instance variable environment is always null if the annotation `@Requestscoped` is explicitly used.

```java
@Path("/hello/{environment}")
@RequestScoped
public class GreetingResource {

  @PathParam("environment")
  private String environment;

  @GET
  @Path("/{helloMessage}")
  @Produces(MediaType.TEXT_PLAIN)
  public String hello(@PathParam("helloMessage") String message) {

    StringBuilder stringBuilder = new StringBuilder();
    stringBuilder.append("Hello from RESTEasy Reactive");
    stringBuilder.append("\nEnvironment: ");
    stringBuilder.append(environment);
    stringBuilder.append("\nMessage: ");
    stringBuilder.append(message);

    printInstanceVariableFromPathParam();
    return stringBuilder.toString();
  }

  private void printInstanceVariableFromPathParam() {
    System.out.println(this.environment);
  }
}
```

### Expected behavior

`curl -X GET --location "http://localhost:8080/hello/env1/message1"`

Output: 
Hello from RESTEasy Reactive
Environment: env1
Message: message1%

### Actual behavior

`curl -X GET --location "http://localhost:8080/hello/env1/message1"`

Output: 
Hello from RESTEasy Reactive
Environment: null
Message: message1%

### How to Reproduce?

Reproducer: https://github.com/knuspertante/quarkus-issue-27473

To reproduce remove `@Requestscoped` from resource class.

### Output of `java -version`

17.0.4

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/27475 fixes the issue
