### ISSUE TITLE
Mutiny Dropped Exception on SSE Cancel

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#27489]
### Describe the bug

Undesirable `ERROR` message appears in logs, e.g:

`2022-08-25 11:30:51,013 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-2) Mutiny had to drop the following exception: io.vertx.core.http.HttpClosedException: Connection was closed`

### Expected behavior

Would prefer not to have these appearing in Production logs.  Can they be avoided or suppressed?

### How to Reproduce?

https://github.com/jimbogithub/mutiny-sse

Run the server and the client.  Observe client logs.

### Additional information

Mutiny SSE otherwise looks much better than legacy SSE (https://github.com/quarkusio/quarkus/issues/23997).

**Comment by geoand** [comment]
When do these show up?

**Comment by jimbogithub** [comment]
> When do these show up?

Does the reproducer not work for you?

**Comment by geoand** [comment]
I missed that, sorry
