### ISSUE TITLE
Let user to provide own KeyManager and TrustManager for HTTPS server

### ISSUE THREAD

**Issue by tsaarni** [quarkusio/quarkus#27481]
### Description

Let user provide their own custom `KeyManager` and `TrustManager`, which would be used for the HTTPS server (by Vert.x).

This could allow implementing certificate hot-reload https://github.com/quarkusio/quarkus/issues/15926 in the application side.

**Comment by sberyozkin** [comment]
@dmlloyd Hi David, I recall you were looking at some options awhile back, to provide custom factories dealing with SSL ? Sorry if it was not related

**Comment by tsaarni** [comment]
I found interesting PR https://github.com/quarkusio/quarkus/pull/26767 that @cescoffier has kindly contributed quite recently. I'm testing this with Quarkus 2.12.0.CR1.  It works very nicely even for setting own keymanager that has hot-certificate-reload capability:

```java
@ApplicationScoped
public class VertxCustomizer implements HttpServerOptionsCustomizer {

    @Override
    public void customizeHttpsServer(HttpServerOptions options) {
        // First do whatever is required to create custom keymanager.
        ...

        // Set it to VertX HttpServerOptions
        KeyCertOptions kco = KeyCertOptions.wrap((X509KeyManager) km);
        options.setKeyCertOptions(kco);
    }
}
```

As far as I can see, I still have to define server certificate in `quarkus.http.ssl.certificate.*` config options as well, since that will enable HTTPS in the first place.  Otherwise I don't get callback to `customizeHttpsServer()`.  This feels bit clumsy, as the certificate given as config option will not end up being used, due to the customization.

Is there any workaround that I could avoid setting the certificates in `quarkus.http.ssl.certificate.*` but still enable HTTP?

**Comment by dmlloyd** [comment]
> @dmlloyd Hi David, I recall you were looking at some options awhile back, to provide custom factories dealing with SSL ? Sorry if it was not related

IIRC what I was looking at was providing a single configuration strategy for TLS. Using the Elytron APIs we can plug in handlers for customized authentication and other things, at abstraction points that are more logical than replacing the trust manager and key manager. I'd have to review whether that would in turn allow support for hot-swapping certificates, but it seems feasible at least.

**Comment by tsaarni** [comment]
Currently the `HttpServerOptionsCustomizer.customizeHttpsServer()` call happens only if Vert.x SSL config was created

https://github.com/quarkusio/quarkus/blob/36ea30a7a58d974107f2b47df4cb7231b8e0fc82/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L662-L664

But i fuser does not set certificate & key or keystore in `quarkus.http.ssl.certificate.*` then SSL config is not created

https://github.com/quarkusio/quarkus/blob/36ea30a7a58d974107f2b47df4cb7231b8e0fc82/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L844-L857

That makes it impossible for the implementer of `HttpServerOptionsCustomizer` to _enable_ SSL config  :-(. It can only _customize_ existing SSL config.

Would it be acceptable to allow `HttpServerOptionsCustomizer` to create SSL config?  I can work with this, but would appreciate if someone could point me into the right direction with the API change.

**Comment by tsaarni** [comment]
I have submitted #27682 to allow application to set custom `KeyManager` without setting dummy placeholder values in  `quarkus.http.ssl.certificate.*`.
