### ISSUE TITLE
Jakarta - EE 9 - Issue with Gradle and Jackson (due to RESTEasy Classic referencing an old version)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27503]
The way Gradle resolves versions cause issues with Jackson as they totally changed their Jakarta approach between two versions and some artifacts are missing due to RESTEasy Classic referencing older version.

Problem is RESTEasy Classic is waiting for a Jackson fix to move to the next version.

See https://github.com/FasterXML/jackson-modules-base/issues/175

**Comment by glefloch** [comment]
Isn't jackson version set in the platform? if the correct version is set in the platform, Gradle should resolve jackson using the platform version and not use the RESTEasy Classic version

**Comment by gsmet** [comment]
Fixed with the upgrade to RESTEasy 6.2.0.Beta1 which is targeting Jackson 2.13.
