### ISSUE TITLE
Jakarta - EE 9 - MP TCK - Failures in JWT TCK

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27512]
We have two failures in the MP JWT TCK. I'm not sure if it's due to the Jakarta version not having the latest changes or if there is a problem somewhere.

:heavy_multiplication_x: org.eclipse.microprofile.jwt.tck.container.jaxrs.InvalidTokenTest.callEchoAgedToken line 97

:heavy_multiplication_x: org.eclipse.microprofile.jwt.tck.container.jaxrs.jwe.RolesAllowedSignEncryptRsaOaep256Test.callEchoRsaOaep256 line 106

**Comment by sberyozkin** [comment]
Hmm, interesting, these are from MP JWT 2.1.RC2 - but the smallrye-jwt Jakarta branch has an MP JWT 2.0 version.

**Comment by sberyozkin** [comment]
See https://github.com/eclipse/microprofile-jwt-auth/tree/2.0/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe
and
https://github.com/eclipse/microprofile-jwt-auth/tree/2.1-RC2/tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/jwe

and `RolesAllowedSignEncryptRsaOaep256Test` is in `2.1-RC2`.

(similarly for the `InvalidTokenTest.callEchoAgedToken`).

So how this code could've been picked up ?

**Comment by sberyozkin** [comment]
I see the problem the TCK version is not set correctly in the tcks module, will fix now

**Comment by sberyozkin** [comment]
Resolved by #27536 which Guillaume cherry-picked into `main`
