### ISSUE TITLE
Does @DenyAll work as expected

### ISSUE THREAD

**Issue by jie-huang** [quarkusio/quarkus#27547]
Based on https://openejb.apache.org/security-annotations.html,
`The @DenyAll annotation can be used to restrict business interface access from anyone, logged in or not. The method is still invokable from within the bean class itself.`

But, it seems it is NOT invokable in Quarkus. e.g.
```
@Path("/test")
public class TestResource {
  @GET
  @Path("/call-denied")
  @RolesAllowed("**")
  public JsonObject callDenied() {
    return new JsonObject().put("processedBy", "/test/call-denied").mergeIn(denied());
  }


  @GET
  @Path("/denied")
  @DenyAll
  public JsonObject denied() {
    return new JsonObject().put("warning", "This should be denied if access with /test/denied");
  }
}
```

After login, accessing `/test/denied`, it returns 403. That is expected.
accessing `/test/call-denied`, it returns 403 too. I think it should be return 200 because `denied()` method is just be invoked in another method (which is accessible).

**Comment by sberyozkin** [comment]
Looks like it is a `call-denied` access which was denied.

**Comment by geoand** [comment]
Is is the called to `denied()` that is causing the exception?

If so, then AFAIK that is expected as Quarkus **does** intercept calls to the methods of the class (@mkouba can confirm or deny this).

**Comment by geoand** [comment]
I am going to close this as it works as expected (I also tried something similar locally to verify)

**Comment by jie-huang** [comment]
Thanks for the explanation.

_"the behavior does not seem to standardized in any way"_.

To me, it seems any implementation of the method (noted with @DenyAll) is meaningless. Because no one can invoke it. Neither calls from @Path nor another method. That causes also @DenyAll meaningless almost. An implementation to throw exception should satisfy interface requirement in need without annotation. (To reject in runtime)

Since @DenyAll is a security annotation, my interpretation of it is, it can NOT be invoked from @Path, but it should be invoked from other methods. That makes it more meaningful.
https://docs.oracle.com/javaee/7/api/javax/annotation/security/DenyAll.html

Of course, it is easy to work around it. Just my 2 cents.

Thanks
