### ISSUE TITLE
Generated static OpenAPI file is not loaded

### ISSUE THREAD

**Issue by hbelmiro** [quarkusio/quarkus#27541]
### Describe the bug

I'm working on an extension that generates a static OpenAPI file programmatically. The problem is that Quarkus tries to read the static file before it is created, and the result is an effective OpenAPI document that doesn't have the information from the generated static file.

I created [a reproducer](https://github.com/hbelmiro/generated-static-openapi-reproducer) that contains:
* [The extension that generates the static OpenAPI file](https://github.com/hbelmiro/generated-static-openapi-reproducer/tree/main/static-openapi-document-generator-extension)
* [A project that uses the above extension](https://github.com/hbelmiro/generated-static-openapi-reproducer/tree/main/generated-static-openapi-reproducer)

We can see this happening when we run a `mvn clean quarkus:dev` in the `generated-static-openapi-reproducer` directory:
1. Quarkus reads static OpenAPI files from `target/classes/META-INF`
2. The extension generates the static OpenAPI file (too late)

However, when we run `mvn install quarkus:dev`, the extension generates the file on the `install` goal and when Quarkus looks for static files (on the `quarkus:dev` goal) the file already exists and the effective OpenAPI document is properly generated.

### Expected behavior

When we run `mvn clean quarkus:dev`, the effective OpenAPI document should contain the information from the generated static file, as described in  https://quarkus.io/guides/openapi-swaggerui#loading-openapi-schema-from-static-files.
![Screenshot from 2022-08-26 16-28-29](https://user-images.githubusercontent.com/11776454/186983413-19748f57-3297-414e-996f-0887791f5e3e.png)

### Actual behavior

The effective OpenAPI document doesn't contain the information from the generated static OpenAPI file.
![Screenshot from 2022-08-26 17-12-12](https://user-images.githubusercontent.com/11776454/186983722-14062cb4-a99a-41fe-8d87-fd1ee40f6a8c.png)

### How to Reproduce?

Follow the instructions from https://github.com/hbelmiro/generated-static-openapi-reproducer#how-to-reproduce-the-issue.

### Output of `uname -a` or `ver`

Linux 192.168.10.47 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8) OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

2.11.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /home/helber/Applications/apache-maven-3.8.6 Java version: 11.0.13, vendor: Eclipse Adoptium, runtime: /home/helber/dev/jdk/jdk-11.0.13+8 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.18.19-200.fc36.x86_64", arch: "amd64", family: "unix"

**Comment by phillip-kruger** [comment]
So the current openapi extension already generate a static document, that gets included with the distribution. Maybe you can share more context on what you are trying to do ? For extensions that want to take part in the openapi generation you best option is to use filters. See https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/HealthOpenAPIFilter.java for and example.

**Comment by hbelmiro** [comment]
@phillip-kruger a filter doesn't seem to help, since I don't need to filter (remove/update stuff), but actually, add more stuff to the OpenAPI document, like what is done [here](https://quarkus.io/guides/openapi-swaggerui#loading-openapi-schema-from-static-files).

Context: The extension I'm working on is in the [Kogito](https://kogito.kie.org/) codebase, which is a runtime that implements the [Serverless Workflow specification](https://serverlessworkflow.io/). This runtime reads a workflow definition in build time and creates endpoints and other things based on that. One of these other things is the OpenAPI document, which needs to be updated with more information that is defined in the workflow definition, like input schemas, for instance.

**Comment by phillip-kruger** [comment]
Filter does allow you to add stuff. Have a go at it

**Comment by hbelmiro** [comment]
It really works with the filter @phillip-kruger :)
Many thanks for your help.
