### ISSUE TITLE
Provide a flush() fonction to Panache

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#2755]
**Description**
Panache doesn't provide a way to flush the persistence context, making difficult to catch exception on repository/entity as they are generated out of the method when the transaction is committed.

For exemple, on the following code, the try/catch block didn't work :
```java
@Inject ParameterRepository parameterRepository;

@Transactional
public void createParameter(Parameter param)
  try { 
    parameterRepository.persist(param);//this will trigger a constraint violation
  }
  catch (PersistenceException pe {
    //never reach as the exception is thrown a transaction commit so outside of the method
   doSomethingInsteadOfCrashing();
  }
}
```

So we need to implement this:
```java
@Inject ParameterRepository parameterRepository;
@Inject EntityManager entityManager;

@Transactional
public void createParameter(Parameter param)
  try { 
    parameterRepository.persist(param);//this will trigger a constraint violation
    entityManager.flush();
  }
  catch (PersistenceException pe {
    //This will works ;)
   doSomethingInsteadOfCrashing();
  }
}
```

**Implementation ideas**
There is multiple way (that can be mixed) to implements this features:
- provide a PanacheEntity.flush() and PanacheRepository.flush() method
- provide a PanacheEntity.persistAndFlush() and PanacheRepository.persistAndFlush() method
- always flush() on after calling persist()
- add callback method to persist => persist(Entity entity, Runnable onFailedTx)

**Comment by FroMage** [comment]
We can add the `flush()` and/or `persistAndFlush()` methods, but I'll defer to @emmanuelbernard to see if this is a common-enough use-case to warrant.

You can also use `Panache.getEntityManager().flush()` in your method.

I don't think we can add a callback though, because this would either force a `flush()` to run inline, and then the first solution is better, or delay the callback until the operations are flushed, which would have confusing semantics because your callback would sit after the transaction and not actually able to do much useful things.

**Comment by loicmathieu** [comment]
@FroMage the callback is to have a way to "compensate" the code that have side effect on the method that have a `@Transactional` annotation. The transaction manager will automatically compensate the database side effect (with a rollback) but if you have other side effect (for exemple an HTTP call to an API that is very common on a microservice architecture) it will not be compensated.

Maybe if we don't want to pollute Panache with JPA specific methods (like flush or lock) that will prevent us to cleany apply Panache principle to NoSQL database, we need to create a PanacheJpaEntity (and the corresponding PanacheJpaRepository) that will extends the PanacheEntity and hold the JPA specific methods (like flush(), persistAndFlush() and others if needed).

**Comment by emmanuelbernard** [comment]
@FroMage There is a static `Panache.` holder? It's not in the guide.

**Comment by emmanuelbernard** [comment]
I think `flush()` belongs in the `PanacheEntity` / `PanacheRepository` because we decided to keep the  JPA delayed semantic. T clarify the semantic, maybe we should call it `flushAll()` to explain that we are flushing all objects, not just that specific entity.

**Comment by loicmathieu** [comment]
@emmanuelbernard it will be soon => https://github.com/quarkusio/quarkus/pull/2788/files ;)

**Comment by emmanuelbernard** [comment]
CC @Sanne ^

**Comment by loicmathieu** [comment]
@emmanuelbernard I'll prepare a PR tomorrow so we can start discussing about the namming. I have already a prototype working.

**Comment by FroMage** [comment]
> @FroMage There is a static Panache. holder? It's not in the guide.

Huh, true. I should fix that.

**Comment by FroMage** [comment]
@loicmathieu I should really backport the work I have in panache-rx to panache that makes it MUCH easier to add magic methods, but now that you have a proto working, I wonder if it would help you or the opposite. Basically with that change, magic methods are automatically wired in, no more changes to the enhancer required.

**Comment by gsmet** [comment]
@FroMage 
> Huh, true. I should fix that.

Not sure we should advertise the `getEntityManager()` there as, if we support several persistence units, the entity manager will depend on the entity.

**Comment by loicmathieu** [comment]
@FroMage This is what I have in mind, I tested it OK, no need of magic methods ;)
https://github.com/quarkusio/quarkus/compare/master...loicmathieu:feat/panache_flush

I add a persistAndFlush method because it's very common but not a shorthand method for the other persist method. I can if needed.

**Comment by emmanuelbernard** [comment]
@loicmathieu you really think `persistAndFlush` are important. I'm having doubts so it's on your shoulders. What would be your pitch in fronot of people on stage?

**Comment by FroMage** [comment]
@loicmathieu #2818 makes it much simpler to add new magic methods, if you want to wait until it's merged. Otherwise I can help you rebase around it.

**Comment by FroMage** [comment]
@loicmathieu ok forget it, I see you don't need any magic methods for this, you're right, great :)

**Comment by emmanuelbernard** [comment]
@FroMage I can't find a reference to it but at some point we imagine that we would need a `entity.validate()` method right? the persistAndFlush reminded me of that. This method better address the specific exmample @loicmathieu gave. Though I do understand `flush` is useful for other things like optimistic locking.

**Comment by loicmathieu** [comment]
@emmanuelbernard My pitch for `persistAndFlush()` is the same as for other existing method like `stream()` : it's a shorthand method for a very common use case calling the method `persist()` then the method `flush()` (like `stream()` is like calling `findAll().stream()`).

But I'm agree it's not really needed and it can feel strange that the other persist methods (`persist(List)`, `persist(stream)`, ...) didn't have the corresponding persistAndFlush methods. I just copied the implementation concurrent framework did on this subject ;)

For the `entity.validate()` method, I don't know what wil be it's behaviour but I didn't expect something around persistence but somethingh arount bean validation ...
What is a bit strange with a flush() on repository or an entity is that is flushes all the presistence context and not just the corresponding entity or the entity managed by the repository. But again I don't think there is a better way to povide this features and concurrent framework do the same.

Relying on the `Panache` holder is not good for unit testing (difficult to mock a holder class).

**Comment by emmanuelbernard** [comment]
Yes `entity.validate()` would call bean validation.

**Comment by emmanuelbernard** [comment]
For sure we need flush as update/merge is kinda implicit in panache. 
I don’t think we would need persistAndFlush for all variants of persist. Spring Data does not for example. 

I don’t know really how to evaluate the weight vs benefit. Your call.

**Comment by loicmathieu** [comment]
@emmanuelbernard I will prepare a PR with my changes and a few lines in the transaction section of the Panache Guide.
I'll stick to flush() and persistAndFlush(Entity) as they are the more common usage (and it's the way Spring Data implement it).

**Comment by emmanuelbernard** [comment]
The one tiny improvement could be a `persistAndFlush(Object o, Object...
otherOs)` but come to think of it, it semi defeats the purpose as you don't
know from which object the exception would come from. But you don't
necessarily know with persistAndFlush either since other operations might
be queued. 🤷
