### ISSUE TITLE
CDI programmatic lookup failure on @Typed bean

### ISSUE THREAD

**Issue by DCCSKrezovic** [quarkusio/quarkus#27569]
### Describe the bug

When trying to lookup a @Typed bean that implements an interface using CDI.current().select() API, the .get() call fails with UnsatisfiedResolution exception.

If I @Inject the @Typed bean at any point and do a programmatic lookup, it will work. If no @Inject are present for given bean, it will fail.

Reproducer here:  https://github.com/DCCSKrezovic/cdi-programmatic-lookup

Simply run: ./mvnw clean package

### Output of `uname -a` or `ver`

Linux xxx 5.15.63-1-lts #1 SMP Thu, 25 Aug 2022 13:40:16 +0000 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM (build 11.0.16.1+1, mixed mode)

### Quarkus version or git rev

2.12.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
This is expected behavior when using programmatic lookup, see [this](https://quarkus.io/guides/cdi-reference#remove_unused_beans).

If you add `@Unremovable` to your bean, things will work

**Comment by famod** [comment]
The is also a big hint in the logs:
```
2022-08-29 15:18:41,309 WARN  [io.qua.arc.impl] (main)
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: org.acme.CdiBeanClassTest.doTestProgrammatic(CdiBeanClassTest.java:16)
Required type: class org.acme.CdiBeanClass
Required qualifiers: [@javax.enterprise.inject.Default()]
Removed beans:
        - CLASS bean  [types=[class org.acme.CdiBeanClass], qualifiers=null]
Solutions:
        - Application developers can eliminate false positives via the @Unremovable annotation
        - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
        - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
        - Enable the DEBUG log level to see the full stack trace
================================================================================
```

Alternatively, you can set [`quarkus.arc.remove-unused-beans=fwk`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.remove-unused-beans) so that Quarkus will never remove any "application beans".
