### ISSUE TITLE
Improve custom entrypoint configuration documentation for JIB images

### ISSUE THREAD

**Issue by schmittjoaopedro** [quarkusio/quarkus#27575]
### Description

By looking at the JIB's documentation on configuring custom entry points [JIB Docs](https://quarkus.io/guides/container-image#jvm-debugging) there is not enough information on the different ways you can configure custom startup scripts for `ubi8/openjdk-11-runtime` or `ubi8/openjdk-17-runtime` images, I mean it´s quite challenging to find the right way to set the values to customize the entry point.

### Implementation ideas

For example, the documentation could be improved to provide two ways of configuring it:

1. Configuring an in-line entry point start-up command in the `application.properties` file:
```bash
quarkus.jib.jvm-entrypoint=java,-agentlib:jdwp=transport=dt_socket\\,server=y\\,suspend=n\\,address=*:5005,-jar,quarkus-run.jar
```

2. Creating a custom startup file at `src/main/jib/jboss/home/run-java.sh` with some content like below:
```bash
java \
  -Djavax.net.ssl.trustStore=/deployments/truststore \
  -Djavax.net.ssl.trustStorePassword=$TRUST_STORE_PASSWORD \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 \
  -jar quarkus-run.jar
```
and providing the custom jvm-entrypoint configuration `quarkus.jib.jvm-entrypoint=/bin/sh,run-java.sh`

**Comment by geoand** [comment]
@schmittjoaopedro would you like to contribute the docs improvement you have in mind? [This](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/container-image.adoc) is the doc that would need to be updated

**Comment by schmittjoaopedro** [comment]
Hi @geoand , of course, I'll create a PR for it.
