### ISSUE TITLE
Jakarta - EE 10 - Support JAX-RS 3.1.0 in RESTEasy Reactive

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27570]
JAX-RS 3.1.0 introduces some new methods and classes and we will need to implement them in RESTEasy Reactive.

How to reproduce:
- get the `jakarta-rewrite` branch from the upstream repository (this branch is already transformed to Jakarta) - it is rewritten daily (but these parts are not moving parts so it shouldn't be a problem)
- `mvn -Dquickly`
- `cd independent-projects/resteasy-reactive`
- change `jakarta.ws.rs-api.version` to `3.1.0` in `pom.xml`
- `mvn clean install`

First failure will be:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project resteasy-reactive-common: Compilation failure
> [ERROR] /data/home/gsmet/git/quarkus-jakarta/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/jaxrs/RuntimeDelegateImpl.java:[30,8] org.jboss.resteasy.reactive.common.jaxrs.RuntimeDelegateImpl is not abstract and does not override abstract method createEntityPartBuilder(java.lang.String) in jakarta.ws.rs.ext.RuntimeDelegate
[ERROR]

Once this is done, I know there is another one related to the bootstrap and I think that's pretty much it - but I wasn't able to experiment fully.

Note: the tree won't function fully if you fix that because RESTEasy Classic is pointing to the EE 9 version for now but the idea is to have a compilable RESTEasy Reactive in `independent-projects` so that I can upgrade RESTEasy Classic and JAX-RS in the main bom _(I will handle that part)_.

I think the easiest way to work on that would be to create a branch in one's fork and push a commit on top of the `jakarta-rewrite` branch. 

Then I would get it and apply it on top of the transformation each night. And we would have an error if the patch doesn't apply cleanly but I don't think these areas change a lot. _(I will handle that part)_

These methods/classes have already been implemented in RESTEasy Classic 6.1.0.Final so that could be a source of inspiration.

Ideally, the `jakarta.ws.rs-api.version` upgrade will be done in a separate first commit as I think I will rely on OpenRewrite to change the version so that everything is centralized.

/cc @geoand

**Comment by geoand** [comment]
Thanks for the thorough description of the current state @gsmet.

I'll have a look soon

**Comment by gsmet** [comment]
Best is to do the same as for CDI: let's make the outcome a branch named jakarta-10-jaxrs in the main repo with:

- one commit to upgrade the JAX-RS version in independent-projects/resteasy-reactive (I won't take that one as I will include the pom upgrades in OpenRewrite)
- one commit that actually adjust the APIs, I will apply this one on top of the other changes

My guess is that you only need to care about getting `independent-projects/resteasy-reactive` to compile and for the tests to run there, no real need to go further. For the rest, I will adjust the RESTEasy Classic version too, push to CI and we will see how things go.

**Comment by geoand** [comment]
Sounds good! I might do this tomorrow

**Comment by geoand** [comment]
@gsmet pushed to `jakarta-10-jaxrs` on the main repo

**Comment by geoand** [comment]
Should I close this or do we keep it open?

**Comment by gsmet** [comment]
I will close it when I incorporate the commit into the Jakarta work. Probably on Monday.

**Comment by geoand** [comment]
🆗
