### ISSUE TITLE
Set datasource password via environment variable (Postgres)

### ISSUE THREAD

**Issue by segersb** [quarkusio/quarkus#2760]
**Describe the bug**
According to the Quarkus guide it should be possible to set the datasource password via an environment variable QUARKUS_DATASOURCE_PASSWORD
https://quarkus.io/guides/application-configuration-guide

In my case (with a Postgres DB) this was not enough, I has to add the following line to the application.properties file:
quarkus.datasource.password=QUARKUS_DATASOURCE_PASSWORD

Without this line I got a Postgres exception saying the password was not provided.

**Expected behavior**
Either setting the environment variable QUARKUS_DATASOURCE_PASSWORD should be enough or the additional line in the application.properties should be added to the guide.

**Additional context**
When adding a startup bean I was able to verify that only setting the environment property was enough to inject the datasource password with a ConfigProperty:
@ConfigProperty(name="quarkus.datasource.password")

**Comment by joan-miralles** [comment]
Related with #988

**Comment by gsmet** [comment]
and to https://github.com/quarkusio/quarkus/issues/1887#issuecomment-480978983

**Comment by machi1990** [comment]
@dmlloyd  patch should fix this. Let's keep this open till the patch is merged. For info, I tested this manually using the patch and it worked.
