### ISSUE TITLE
Extend form auth cookie configuration

### ISSUE THREAD

**Issue by dector** [quarkusio/quarkus#27609]
### Description

**Suggested configurations**:

- Make cookie [`HttpOnly`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security) / add configuration option to force this.
	- **Why?** Current cookie is not `HttpOnly` which is [not a safe way](https://owasp.org/www-community/HttpOnly) of using session cookie.
	- **Workaround?** Can you advice any? Is it possible intercept **single** endpoint response and modify it's cookies?

- or Add ability to modify session cookie after it was created by injecting some mapper function and calling it on the cookie instance (e.g. I would love to use `Secure` as my application server is running behind the reverse proxy (Caddy <---http--> Quarkus)).

**Comment by michalvavrik** [comment]
I'll have a look provided no-one is working on this (?). Any preferences/requirements on impl. @sberyozkin ?
