### ISSUE TITLE
undocumented uberjar behavior

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#2762]
**Describe the bug**
uberjar switch generates artifact-version-runner.jar and artifact-version.jar.original.  The documentation does not say that the uber jar generated is -runner.jar

**Comment by machi1990** [comment]
Hey @patriot1burke, is this still an issue? 
In this [guide](https://quarkus.io/guides/application-configuration-guide), section **Package and run the application**  there is a mention of which jar file to run
i.e `... the application can be packaged using ./mvnw clean package and executed using the -runner.jar file`.
