### ISSUE TITLE
Async startup code

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#27623]
### Description

For blocking code, we can use:

```java
@ApplicationScoped
public class Startup {
    
    @Transactional
    public void init2(@Observes StartupEvent evt){
        Person p = new Person();
        p.firstName = "Stef";
        p.lastName = "Epardaud";
        Person.deleteAll();
        p.persist();
    }
}
```

But for reactive code, I don't know how to do it. This doesn't work:

```java
@ApplicationScoped
public class Startup {
    
    public Uni<Object> init(@Observes StartupEvent evt){
        Person p = new Person();
        p.firstName = "Stef";
        p.lastName = "Epardaud";
        return Person.deleteAll()
                .chain(ignore -> p.persist());
    }
}
```

Because `ArC` doesn't subscribe to the returned `Uni`, and there's no transaction anyway.

This doesn't work either:

```
@ApplicationScoped
public class Startup {
    
    @ReactiveTransactional
    public Uni<Object> init(@Observes StartupEvent evt){
        Person p = new Person();
        p.firstName = "Stef";
        p.lastName = "Epardaud";
        return Person.deleteAll()
                .chain(ignore -> p.persist());
    }
}
```

Because again, ArC doesn't subscribe to the `Uni` returned by the `io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactionalInterceptorBase` interceptor.

If it did, there's a chance it might work, pending the question of whether it would have a request context, and whether that request context would be propagated to the IO thread we would move this code to, because the interceptor calls:

```java
            return AbstractJpaOperations.getSession().flatMap(session -> session.withTransaction(tx -> {
                inTransactionCallback(tx);
                try {
                    return (Uni) ic.proceed();
                } catch (RuntimeException e) {
                    throw e;
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }));
```

And `getSession()` moves this to the IO thread like this:

```java
    public static Uni<Mutiny.Session> getSession() {
        // Always check if we're running on the event loop: if not,
        // we need to delegate the execution of all tasks on it.
        if (io.vertx.core.Context.isOnEventLoopThread()) {
            return Uni.createFrom().item(lookupSessionFromArc());
        } else {
            // FIXME: we may need context propagation
            final Executor executor = AbstractJpaOperations::executeInVertxEventLoop;
            return Uni.createFrom().item(AbstractJpaOperations::lookupSessionFromArc)
                    .runSubscriptionOn(executor);
        }
    }
```

Notice that FIXME. It's entirely possible that ArC doesn't enable the request context, or doesn't extend its life-time, once it will actually subscribe to the returned `Uni`, and that even if it did, we'd need CP or something to propagate it here.

So this is likely a multi-person cooperation job.

**Comment by FroMage** [comment]
Note that this is related to #27591 but should have no impact on injection points, so this should not delay injection and cause async injection with all the headaches that #27591 implies.

**Comment by mkouba** [comment]
FTR [this workaround](https://github.com/quarkusio/quarkus/issues/27854#issuecomment-1245026347) seems to work.

**Comment by mkouba** [comment]
> so this should not delay injection and cause async injection with all the headaches

Hm, the question is whether we want to delay the startup or not, i.e. we can execute the code asynchronously or block and await the `Uni` item. @FroMage WDYT?

**Comment by FroMage** [comment]
Good question. I guess it should delay startup, like regular startup listeners, no?

**Comment by mkouba** [comment]
Users are encouraged to use the [`VertxContextSupport.subscribeAndAwait()`](https://quarkus.io/version/main/guides/vertx#executing-asynchronous-code-from-a-blocking-thread) util method to execute an asynchronous code from a blocking thread, e.g. from an `@Observes StartupEvent` observer method.

**Comment by holomekc** [comment]
Hi @mkouba,

what would be the appropriate way to handle a Multi in ```@Observes StartupEvent```?

**Comment by mkouba** [comment]
> Hi @mkouba,
> 
> what would be the appropriate way to handle a Multi in `@Observes StartupEvent`?

`Multi` represents a stream so you can't really `await()` the result. In other words, it would be more like a fire-and-forget operation. In theory, we could add a method like `void subscribe(Supplier<Multi<T>> multiSupplier, Consumer<MultiSubscribe<T>> subscribeConsumer)` to the `VertxContextSupport`.

@cescoffier WDYT?

**Comment by mkouba** [comment]
FYI I've created https://github.com/quarkusio/quarkus/pull/36088.
