### ISSUE TITLE
Multiple Application error with ignore-application-classes set to true

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#27638]
### Describe the bug

I'm running `quarkusDev`, and I set `quarkus.resteasy.ignore-application-classes=true`. But I still get an error that `More than one Application class` exists. With that config property set, shouldn't that error not be possible?

### Expected behavior

Successful startup with no `Application` classes.

### Actual behavior

```
RuntimeException: More than one Application class: [my.services.service1.Service1Application, my.services.service2.Service2Application]
```

### How to Reproduce?

1. Create 2 projects with `Application` classes
2. Reference one project from another as a dependency
    - `quarkusDev project(':service2')`
3. `./gradlew service1:quarkusDev`
4. Error

### Output of `java -version`

Temurin JDK 17.0.3

### Quarkus version or git rev

Quarkus 2.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by geoand** [comment]
What extensions are you using?

**Comment by mweber03** [comment]
@geoand 

    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-smallrye-context-propagation'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-undertow'
    implementation 'org.amqphub.quarkus:quarkus-qpid-jms'

**Comment by geoand** [comment]
Understood, thanks.

Can you please attach a sample project that exhibits the problematic behavior?

**Comment by mweber03** [comment]
Attempting to isolate the issue in a reproducer.

**Comment by geoand** [comment]
@mweber03 where you able to come up with a sample application?
