### ISSUE TITLE
More global Rest Client configs

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#27635]
### Description

I saw some configs are both global and available per "config-key", like:
```
quarkus.rest-client.connect-timeout
quarkus.rest-client.read-timeout
```

could other variables be global too? such as:
```
quarkus.rest-client."config-key".hostname-verifier -> quarkus.rest-client.hostname-verifier
quarkus.rest-client."config-key".connection-pool-size -> quarkus.rest-client.connection-pool-size
quarkus.rest-client."config-key".max-redirects -> quarkus.rest-client.max-redirects
```

**Comment by geoand** [comment]
@TomasHofman since you did a lot of this work, would you be interested in this?

**Comment by TomasHofman** [comment]
@geoand Sure, I will look at this.

**Comment by geoand** [comment]
Thanks!

**Comment by TomasHofman** [comment]
To provide some info, I'm now working with following plan.

These are properties that are already available as both client specific and global properties, no change here:

```
connect-timeout
read-timeout
proxy-address
proxy-user
proxy-password
non-proxy-hosts
user-agent
```

These properties are currently available only as client-specific, and will newly become available also as "global" properties:

```
scope
providers
follow-redirects
query-param-style
hostname-verifier
connection-ttl
connection-pool-size
max-redirects
headers

trust-store
trust-store-password
trust-store-type

key-store
key-store-password
key-store-type
```

These properties will remain available only as client-specific properties:

```
url / uri
shared
name
```

Let me know if it seemed like an overkill.

**Comment by geoand** [comment]
Seems reasonable to me
