### ISSUE TITLE
List all Quarkus Managed Built-in Beans

### ISSUE THREAD

**Issue by jadedevin13** [quarkusio/quarkus#2763]
Spring Boot has actuator that can list Spring Managed Beans by going to /beans endpoint. What is the quarkus equivalent of this? I know that we can programmatically use ...

```java
@Inject
BeanManager beanManager;

...
Set<Bean<?>> beans = beanManager.getBeans(Object.class,new AnnotationLiteral<Any>() {}));

for (Bean<?> bean : beans) {
     System.out.println(bean.getBeanClass().getName());
}

```

But it can be useful if there's equivalent like Spring Actuator or at least a documentation.

[Relevant stack-o link.](https://stackoverflow.com/questions/56511783/list-all-quarkus-managed-built-in-beans)

**Comment by geoand** [comment]
I personally like the idea of having extra diagnostics printed either in the log (when the level is set to DEBUG for example) or added to some specific endpoint

**Comment by gastaldi** [comment]
It's `/quarkus/arc/beans` when running with `mvn quarkus:dev`. 

See https://quarkus.io/guides/cdi-reference#dev-mode
