### ISSUE TITLE
quarkus.uuid is missing in 2.12.0

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#27630]
### Describe the bug

    ConfigProvider.getConfig().getValue("quarkus.uuid", UUID.class);

This works well in Quarkus 2.11.3. However, it throws an exception in Quarkus 2.12.0:

```
2022-08-31 17:43:28,918 [] ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.NoSuchElementException: SRCFG00014: The config property quarkus.uuid is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:282)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:239)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:167)
	...
```

**Comment by gsmet** [comment]
@radcortez I don't think we have removed it so I suspect a config issue. Feel free to redirect to someone else if it's not.

**Comment by gsmet** [comment]
And we should probably have a test for that too.

**Comment by radcortez** [comment]
I was not able to reproduce the issue. I've tried with a sample project with `2.12.0.Final` and it worked as expected. I've also added a test in https://github.com/quarkusio/quarkus/pull/27634 and it also works.

@Eng-Fouad can you please provide us with a reproducer? Thank you.

**Comment by Eng-Fouad** [comment]
@radcortez https://github.com/Eng-Fouad/quarkus-2_12-bug

**Comment by Eng-Fouad** [comment]
Even this simple resource class does not let the server to start normally:

```
@Path("/uuid")
public class UuidResource {

    @ConfigProperty(name = "quarkus.uuid")
    UUID uuid;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public UUID uuid() {
        return uuid;
    }
}
```

> Failed to load config value of type class java.util.UUID for: quarkus.uuid

changing Quarkus version back to `2.11.3.Final` makes it working well.

**Comment by radcortez** [comment]
Caused by https://github.com/quarkusio/quarkus/pull/26967.

**Comment by ia3andy** [comment]
I also had this bug on some of my apps, let me know if you need another reproducer

**Comment by radcortez** [comment]
No worries. I was already able to reproduce it. It only happens with RESTEasy Reactive, and I was using RESTEasy Classic. Thanks!

**Comment by geoand** [comment]
> It only happens with RESTEasy Reactive, and I was using RESTEasy Classic

Very interesting... Why the difference?

**Comment by radcortez** [comment]
We had an issue with `DefaultValuesConfigSource`. If a namespace was already present it was being overridden if we needed to update it. So what happened was that we write `quarkus.uuid` with `SmallRyeConfigBuilder.withDefault` and then mappings will also write their defaults. In this step, the `quarkus.uuid` was discarded.

This was caused when we added the mapping for RESTEasy Reactive Security: It was because https://github.com/quarkusio/quarkus/pull/26967. The issue was already there, just not very visible because you needed a combination of using extension mappings and `quarkus.uuid`, and we don't have many extensions using mappings yet :)

**Comment by geoand** [comment]
Gotcha, thanks for the explanation1

**Comment by sstefano** [comment]
I have the same issue with the latest version of quarkus 2.12.0 + RESTEasy Reactive so, we need to wait for the next release, is it correct?

**Comment by gsmet** [comment]
We have a 2.12.1.Final planned for tomorrow. I will check if I can backport the SmallRye Config upgrade.
