### ISSUE TITLE
The config reference is not generated for child config classes annotated with `@ConfigMapping`

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#27668]
### Describe the bug

Having the following configuration classes:

```java
@ConfigMapping(prefix = "quarkus.certificate")
@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
public interface CertificateConfig {
    /**
     * The name of the certificate resource to be generated.
     * If not provided, it will use the default name for the application resources.
     */
    Optional<String> name();

    /**
     * SecretName is the name of the secret resource that will be automatically created and managed by this Certificate
     * resource.
     * It will be populated with a private key and certificate, signed by the denoted issuer.
     */
    String secretName();

    /**
     * The reference to the issuer for this certificate.
     */
    Optional<IssuerRefConfig> issuerRef();
....
}

public interface IssuerRefConfig {
    /**
     * The name of the resource being referred to.
     */
    String name();

    /**
     * The kind of the resource being referred to.
     */
    Optional<String> kind();
}

```

The autogenerated config reference table does not include the `name` and `kind` properties of the IssuerRefConfig class:
![Captura de pantalla de 2022-09-01 15-26-02](https://user-images.githubusercontent.com/6310047/187927141-302f46b5-b6d2-4cab-a3a0-94008eecaac5.png)

I do need the `@ConfigMapping` to handle optional subclasses, so I can't use the other approach `@ConfigRoot` which works fine for this. Therefore, I could not find any workaround for this.

**Comment by Sgitario** [comment]
The `@ConfigMapping` support was added as part of https://github.com/quarkusio/quarkus/pull/19230.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
I think this worked, but maybe it got broken with another change. I'll check.
