### ISSUE TITLE
Kubernetes env vars do not allow empty values

### ISSUE THREAD

**Issue by antssilva96** [quarkusio/quarkus#27663]
### Describe the bug

When using quarkus kubernetes I need to set up a environment variable with value _null_

but I get

> The config property quarkus.kubernetes.env.vars.TESTVAR is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter -> [Help 1]

I think the problem is that in https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/EnvVarsConfig.java the vars map is String->String and should be String->Optional<String> if we do want this behavior to be possible.

### Expected behavior

Being able to define env variables with empty values.

### Actual behavior

An error prevents this.

### How to Reproduce?

1. Add quarkus kubernetes dependency
2. Add to your application.properties an entry with a kubernetes env var with empty value like `quarkus.kubernetes.env.vars.TESTVAR=`

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

<quarkus.platform.version>2.11.3.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by Sgitario** [comment]
It makes sense to me to allow empty values. I've already provided a fix for this: https://github.com/quarkusio/quarkus/pull/27681
