### ISSUE TITLE
Panache Entity @Id Does Not Support Self-Assigned String Value

### ISSUE THREAD

**Issue by wargun02** [quarkusio/quarkus#2768]
**Describe the bug**
if I have an Entity class of:

```
@Entity
@Table( name = "t_boo" )
public class BooEntity extends PanacheEntity implements Serializable {
    @Id
    @Column( name = "uuid" )
    public String uuid;

    @Column( name = "created_datetime" )
    public LocalDateTime createdDateTime;
}
```

And a portion of codes which persist the entity: 
```
BooEntity boo = new BooEntity();
boo.uuid = UUID.randomUUID( ).toString( );
boo.createdDateTime = LocalDateTime.now( )
boo.persist()
````
**Actual behavior**
Throws an exception of: 
```
Caused by: java.sql.SQLException: Table 'quarkusdemo.hibernate_sequence' doesn't exist
```
**Expected behavior**
This should persist without a problem. In fact an Entity class without extending Panache persisted properly without throwing any exception even if the @Id field (with an assigned value of course) has no @GeneratedValue.

The @Id field without @GeneratedValue should be allowed self assign of identity/primary key value.

**Environment (please complete the following information):**
Running on MacOSX
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)

**Comment by FroMage** [comment]
Perhaps the bytecode modification for id fields goes wrong and ORM does not see the annotations.

**Comment by FroMage** [comment]
Ah hold on, you should be extending `PanacheEntityBase` since you have a custom ID. This actually looks correct to me because by extending `PanacheEntity` you have two IDs, one of which is generated, hence the exception. Can you please reopen the bug if it does not work for you when you extend `PanacheEntityBase`?

Thanks.

**Comment by wargun02** [comment]
Excellent, it worked as suggested. Thank you for the heads up.
