### ISSUE TITLE
hibernate extension support Query Methods like Sping Data

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#27680]
### Description

now it is so hard when we need query dynamic. it must use Specification 、generate hql or CriteriaBuilder/CriteriaQuery and so on,code of both of them are so long.

we have to abstract the code to common.

so we hope that quarkus hibernate extension support  Query Methods  feature like spring data.

the doc is [Spring Data Doc - Query Methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods)

### Implementation ideas

[Spring Data Doc - Query Methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods)

**Comment by geoand** [comment]
You can always use the [Spring Data JPA compatibility layer](https://quarkus.io/guides/spring-data-jpa) or our idiomatic [Hibernate Panache](https://quarkus.io/guides/hibernate-orm-panache) layer.

Don't those APIs cover your use case?

**Comment by geoand** [comment]
@yrodiere I think we can close this, WDYT?

**Comment by yrodiere** [comment]
> @yrodiere I think we can close this, WDYT?

Agreed: either use the Spring Data JPA compatibility layer or (preferably) [Panache](https://quarkus.io/guides/hibernate-orm-panache). If that doesn't work, please open another issue to report what's wrong exactly.

As far as I know, not implementing Query methods in Panache was a conscious design choice. Its goal is not to be a Spring Data clone, but to make persistence simpler, and it offers its own solutions for that.

Closing. If @FroMage disagrees and thinks we need Spring Data Query Methods in Panache, I'll let him re-open this.
