### ISSUE TITLE
KeycloakTestClient only reads client.quarkus.oidc.auth-server-url property to connect to Keycloak instance

### ISSUE THREAD

**Issue by viswatejan** [quarkusio/quarkus#27703]
### Describe the bug

Both `AUTH_SERVER_URL_PROP` and `CLIENT_AUTH_SERVER_URL_PROP` constants in `KeycloakTestClient` are set as `client.quarkus.oidc.auth-server-url` and it seems the idea is `client.quarkus.oidc.auth-server-url` takes the precedence and is used to override if we want to not to use the default `quarkus.oidc.auth-server-url` which will be set when using quarkus-oidc extension.[](url)

### Expected behavior

`AUTH_SERVER_URL_PROP` should be set to `quarkus.oidc.auth-server-url`

### Actual behavior

Both `AUTH_SERVER_URL_PROP` and `CLIENT_AUTH_SERVER_URL_PROP` constants in `KeycloakTestClient` are set as `client.quarkus.oidc.auth-server-url` which will never pick the default `quarkus.oidc.auth-server-url` configuration property.

### How to Reproduce?

1. Create a quick start with quarkus-oidc extension.
2. Create a Rest Resource and secure it with quarkus-oidc.
3. Write integration test utilizing Keycloak dev services and quarkus-test-keycloak-server library.
4. Use KeycloakTestClient to generate the access token.
5. That will not work unless the configuration property is configured like below
`client.quarkus.oidc.auth-server-url=${quarkus.oidc.auth-server-url}`

### Output of `uname -a` or `ver`

Darwin macx-60bdmd6m 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 LTS OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS) OpenJDK 64-Bit Server VM Zulu17.36+13-CA (build 17.0.4+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

Also present in main 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by viswatejan** [comment]
This is the PR for this issue
https://github.com/quarkusio/quarkus/pull/27702

**Comment by sberyozkin** [comment]
Fixed by #27702
