### ISSUE TITLE
Changing the root-path with a QUARKUS_HTTP_ROOT_PATH environment doesn't work

### ISSUE THREAD

**Issue by wmacibnc** [quarkusio/quarkus#27705]
### Describe the bug

When the command is executed
java -jar target/quarkus-app/quarkus-run.jar is not overridden value of quarkus.http.root-path with environment variable QUARKUS_HTTP_ROOT_PATH.

Displays the error:

2022-09-03 14:12:46,719 WARN [io.qua.run.con.ConfigRecorder] (Thread-0) Build time property cannot be changed at runtime:
  -quarkus.http.root-path is set to '/output' but it is build time fixed to '/'. Did you change the quarkus.http.root-path property after building the application?

### How to Reproduce?

Report the env QUARKUS_HTTP_ROOT_PATH

### Output of `uname -a` or `ver`

Linux xxxxx 5.3.18-150300.59.87-default #1 SMP Thu Jul 21 14:31:28 UTC 2022 (cc90276) x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75.0 openjdk version "11.0.15" 2022-04-19 LTS OpenJDK Runtime Environment 18.9 (build 11.0.15+9-LTS) OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.12.0-Final

**Comment by geoand** [comment]
As the warning message indicates (and as can also be see [here](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.root-path)), `quarkus.http.root-path` is a **build time** property. This means whatever value was set during build time, **cannot** be changed at runtime. See [this](https://quarkus.io/guides/config#build-time-configuration) for more information on build time properties.

**Comment by wmacibnc** [comment]
Thanks!

**Comment by geoand** [comment]
🙏
