### ISSUE TITLE
Remove LANG and LANGUAGE ENV declaration in Dockerfile

### ISSUE THREAD

**Issue by dometec** [quarkusio/quarkus#27714]
**Describe the bug**
Running a quarkus project with docker with image compiled using Dockerfile.jvm provided, on the System out I see "??" instead of UTF8 character (es: "è").

**Expected behavior**
UTF8 support on System out.

**Actual behavior**
I see "??" in the output instead of "é"

**To Reproduce**
1. run *docker run -it --rm -e "LANG=en_US.UTF-8" registry.access.redhat.com/ubi8/openjdk-17:1.11 jshell*
2. write some non-ascii character (es: è)

**Screenshots**

**Environment (please complete the following information):**
 - Browser: N/A
 - OS: Linux

**Additional context**
The base image (FROM registry.access.redhat.com/ubi8/openjdk-17:1.11) does not contain the relative lang file, see:

[ec2-user@metric1 ~]$ docker run --rm registry.access.redhat.com/ubi8/openjdk-11:1.11 locale -a
C
C.utf8
POSIX

If I do not specify LANG env, it works ( *docker run -it --rm registry.access.redhat.com/ubi8/openjdk-17:1.11 jshell* )

**Comment by ia3andy** [comment]
This should have been fixed by #27129 on 2.12
