### ISSUE TITLE
Make MongoDB version configurable

### ISSUE THREAD

**Issue by MandMaric** [quarkusio/quarkus#27717]
### Description

Hi

It would be nice if the MongoDB version would be configurable in MongoTestResource: https://github.com/quarkusio/quarkus/blame/main/test-framework/mongodb/src/main/java/io/quarkus/test/mongodb/MongoTestResource.java

Currently, version 4.0 is set by default and 6.0 has already been released.

We are currently writing our own QuarkusTestResource class to override this property.

**Comment by loicmathieu** [comment]
This sounds legit, we should update to the last 4.x version as I think it's the most used and allow to configure it.

**Comment by geoand** [comment]
Good idea. I'll make an update to the code and the documentation
