### ISSUE TITLE
Pact consumer-driven contract testing extension

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#27729]
### Description

[Pact](https://pact.io/) is a widely-recommended framework for consumer-driven contract testing. Because Quarkus is optimised for microservices and consumer-driven contract tests are an important part of a microservices development workflow, Pact is particularly relevant for Quarkus.

## Why is an extension needed? Functional issues 

Although it is possible to use Pact with Quarkus (see https://github.com/skattela/pact-workshop-jvm-quarkus and https://github.com/holly-cummins/house-of-microservices-quarkus-contract-testing-sample), Pact tests do not work in continuous testing mode. 
- Pact relies on Kotlin and is affected by classloading issues. See, for example, a reference to Pact problems on a [broader issue about Kotlin classloading](https://github.com/quarkusio/quarkus/issues/11549). The Pact issues need a bigger fix than just including the `quarkus-kotlin` extension.
- Pact tests also have problems if they store contracts in a local resources folder.

## Usability enhancements

Although fixing the functional issues is most important, there are also a range of enhancements that could improve the Pact user experience:
- Eliminating the need to `@BeforeEach` a `context.setTarget(new HttpTestTarget("localhost", 8081))` on every test
- Quarkus-style configuration of pact location and broker
- Dev UI view of contract contents and status
- Potentially, integration with other frameworks such as RestAssured, [WireMock]( https://bitbucket.org/atlassian/wiremock-pact-generator/src/master/) and [OpenAPI](https://docs.pactflow.io/docs/bi-directional-contract-testing#use-cases). This is a complex area with existing activity and a number of existing converters.   

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion

```properties
pact.rootDir: # [existing system property, where to write generated pacts]
pact.writer.overwrite: # [existing system property, whether to overwrite generated pacts]
pact.readFrom: # [new property, universal config for pact location to eliminate need for per-test config, see https://docs.pact.io/implementation_guides/jvm/provider/junit#pact-source]
```

### Additional context

This has been requested up occasionally in the broader community. 

There was a [long discussion on the google groups](https://groups.google.com/g/quarkus-dev/c/f8hJRm8oWbQ) a year ago.

See also, for example, https://lightrun.com/answers/quarkusio-quarkus-consumer-driven-contracts-integrationsupport: "CDC is a big part of our Spring Boot microservice qa process, and it would be very desirable to have an equivalent in quarkus." 

Note also that Pact is not the only contract testing option; Spring has Spring contract, although it is not as polyglot as Pact. It is also possible to use tools such as Schemathesis, Prism, and OpenAPI in combination (see a [tutorial here](https://appdev.consulting.redhat.com/tracks/contract-first/automated-testing-with-schemathesis.html)).

**Comment by holly-cummins** [comment]
> It would be hosted in the Quarkiverse, right?

That's my intention.

**Comment by holly-cummins** [comment]
This should also have the "area/testing" label.

**Comment by holly-cummins** [comment]
See also #6276, which is arguably a duplicate of this but which I missed in my searches (and this one has the extension-proposal issue type).

**Comment by holly-cummins** [comment]
It might also be possible to address #22611 with an extension but that would need a lot of thought.

**Comment by holly-cummins** [comment]
Could you do the repository-making, @gastaldi? :) Unless there are any objections?

**Comment by gastaldi** [comment]
@holly-cummins only if you don't mind waiting me return from my PTO on October😛

Could you create a PR in the quarkiverse-devops repo according to https://github.com/quarkiverse/quarkiverse-devops#workflow-for-new-repositories?

Here is an example: https://github.com/quarkiverse/quarkiverse-devops/pull/91

**Comment by holly-cummins** [comment]
https://github.com/quarkiverse/quarkus-pact/ is the new home of the extension.
