### ISSUE TITLE
Jackson ObjectMapper configuration broken if JsonObject.mapTo is used in test resource

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#27725]
### Describe the bug

When using `JsonObject.mapTo` in the `start` method of a test resource, the object mapper used in the running Quarkus app in Quarkus tests is not configured properly. This can be shown with the jackson Kotlin module, which should be automatically loaded once the dependency is available. As soon as `JsonObject.mapTo` is used in the `start` method, the Kotlin module is not loaded automatically anymore.

### Expected behavior

Using `JsonObject.mapTo` in a test resource is possible without breaking the Quarkus app.

### Actual behavior

The Kotlin module is not loaded anymore once the method is called.

### How to Reproduce?

https://github.com/languitar/quarkus-mapper-reproducer

#. `mvn verify`

Once the line

```kotlin
JsonObject.mapFrom(Model(42)).toString()
```

is removed from `BreakingResource` the tests pass.

### Output of `uname -a` or `ver`

Linux pres 5.15.63-1-lts #1 SMP Thu, 25 Aug 2022 13:40:16 +0000 x86_64 GNU/Linux

### Output of `java -version`

11.0.16.1

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6 

### Additional information

The problem here seems to be the on-demand initialization of the mapper in QuarkusJacksonJsonCodec in a static block. Due to the fact that the test resource executes before the ArcContainer is available. The fallback in this case initializes a default object mapper and initialization with an ArcContainer is not reattempted as the static code block was already executed.

**Comment by geoand** [comment]
We could theoretically reset the `mapper`. Currently it would be safe as the codec initialization is not triggered, but there is no telling that it won't happen in future (for example if we load the `Json` class anywhere in the startup code), so I am not really sure about it

**Comment by languitar** [comment]
At least the behavior now is pretty confusing. If the Vertx JsonObject should only be usable from within a running Quarkus  application, then it would probably best to throw an IllegalStateException in cases where it is used outside.

**Comment by geoand** [comment]
Yeah, that would be nice, but it shifts the problem to detecting those cases 😉

**Comment by geoand** [comment]
I am going to close this as there is no good way to address the issue
