### ISSUE TITLE
Support injecting RUNTIME_INIT configuration to RESTEasy Reactive filters

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#27751]
### Description

Currently it is not possible to have features depending on RESTEasy Reactive filters configured at run time as pointed out in #27726.

IMHO it is a serious restriction and hopefully it is possible to enhance it.

CC @geoand

**Comment by geoand** [comment]
Although it's not ideal, it's not so big of a restriction in practice - it has never come up until now

**Comment by sberyozkin** [comment]
@geoand May be it means the users have not started yet building features which depend on configurable reactive filters.
#27726 is a concrete feature which won't be possible to change at run time, so not sure what you mean by `it's not so big of a restriction in practice`

**Comment by sberyozkin** [comment]
@geoand I have a feeling #27752 is actually related - as it seems both issues stem from the fact that filters are created at the static init time. Have a look please, a single tweak might get both issues addressed

**Comment by geoand** [comment]
@sberyozkin we can't do that. The entire RESTEasy Reactive Deployment is done at build time by design

**Comment by sberyozkin** [comment]
@geoand Sure - by the design ideas can be revisited, right ? Can we at least think of the possible options how to handle such an enhancement request ?

Users do want to change configuration properties at runtime and therefore the features which depend on reactive filters will have an adoption problem as in practical cases the users often want to tweak things at runtime. FYI, `OidcClientReactiveFilter` has also a built time config but it is of no real concern as its configuration is not particularly useful (not dynamic enough). But in case of #27752, so many cookie and form properties that may need to be changed that it will be a problem...

However that fact the filters can't even use `SecureRandom` effectively is a real problem, no ?

@FroMage @stuartwdouglas Can you also comment please

Cheers

**Comment by geoand** [comment]
> Sure - but the design ideas can be revisited, right ? Can we at least think of the possible options how to handle such an enhancement request ?

Not without serious implications. The way I see it, this use case does not warrant such a drastic change.

From the user's point of view, configuration will work just fine. What does not work from what you showed is the injection of Quarkus configuration.

Furthermore, no user has ever reported such an issue, so my feeling is that only people with really deep integrations (such as yours) will run into these issues. 

Finally, as I commented on the PR, the filter is likely not the way to go to implement what you want here.

**Comment by sberyozkin** [comment]
@geoand 

>What does not work from what you showed is the injection of Quarkus configuration.

I don't really think that was the real problem, one just can't configure a filter with a runtime init property, which way one supplies it.

>Furthermore, no user has ever reported such an issue, so my feeling is that only people with really deep integrations (such as yours) will run into these issues.

What `deep integration` you are referring to - this is a straightforward feature which just needs to be configured

>Finally, as I commented on the PR, the filter is likely not the way to go to implement what you want here.

Sigh. May be I can get you explaining eventually `why`. And it is really related, which handler to use since neither one can be configured at runtime init ?

**Comment by geoand** [comment]
> I don't really think that was the real problem, one just can't configure a filter with a runtime init property, whichever way one supplies it.

Not true. What users want to do inject their own configuration properties and doing something like:

```java
public class Filters {
    private final String name;

    public Filters(@ConfigProperty(name = "my.property") String name) {
        this.name = name;
    }

    @ServerRequestFilter
    public void filter() {
        System.out.println("my name is: " + name);
    }
}
```

works perfectly and will output whatever the runtime value of `my.property` is.

> What deep integration are you referring to - this is a straightforward feature which just needs to be configured

My point is the same as above. You are trying to integrate the Quarkus config system into this - this is not what a user will do.

> Sigh. May be I can get you explaining eventually why. And it is really related, which handler to use since neither one can be configured at runtime init ?

I have since walked back my statement that lead to this - although the filter is still not written in the intended way

**Comment by sberyozkin** [comment]
@geoand 

>You are trying to integrate the Quarkus config system into this

Right, see your point.

>Not true. What users want to do inject their own configuration properties and doing something like:...

Yes, I ignored this one. As I said in the PR which led me to opening this issue, I have 8 configuration properties - but I think listing 8 properties in the constructor wins if it will get that feature the RUNTIME_INIT config capability.

Close this issue please if you prefer...

**Comment by geoand** [comment]
> Yes, I ignored this one. As I said in the PR which led me to opening this issue, I have 8 configuration properties - but I think listing 8 properties in the constructor wins if it will get that feature the RUNTIME_INIT config capability.

Users would likely use `@ConfigMapping` for this. But I just saw that this won't work... So I'll leave the issue open

**Comment by mkouba** [comment]
@sberyozkin FYI you can try to use programmatic lookup to inject the root configuration beans and obtain the instance lazily, i.e. instead of `@Inject HttpConfiguration config` just do `@Inject Instance<HttpConfiguration> config` and then `config.get().port`. This way the configuration bean is obtained lazily when needed.

**Comment by geoand** [comment]
This does seem a bit problematic, so I'll have to spend more time on (when I do have some that is)

**Comment by sberyozkin** [comment]
@mkouba Thanks for the idea, sounds promising, let me do a quick try

**Comment by sberyozkin** [comment]
@mkouba, @geoand, Guys, it works perfectly, see  https://github.com/quarkusio/quarkus/pull/27726/commits/287f884901aca9c95e93db69adf4a3f576e17712, I believe this issue can definitely be closed now as invalid, what do you think ?

**Comment by geoand** [comment]
I'd say let's keep it open as I want to explore alternatives

**Comment by sberyozkin** [comment]
Sure, sounds good (before I saw Martin's comment, I was wondering if a build time resteasy reactive property can be introduced which can tell it when to init the filters - so the most optimized way is done by default per the original design, but can be tweaked if necessary with a single property - sorry if it sounds silly :-)). And thanks Georgios for bearing with me today :-)

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
@sberyozkin I think we have addressed this, have we not?
