### ISSUE TITLE
Make it possible to have non-static SecureRandom in RESTEasy Reactive filters

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#27752]
### Description

Declaring a `SecureRandom` instance variable in a RESTEasy Reactive filter causes a native build failure - therefore the implementations have to create it during the request processing which can be expensive.

Please investigate if the way RESTEasy Reactive filters are created can be changed to support it

CC @geoand

**Comment by sberyozkin** [comment]
Georgios, IMHO it is still a serious enough restriction...

**Comment by geoand** [comment]
It may be, but I don't want to address it unless there is an actual need for it.

**Comment by sberyozkin** [comment]
@geoand Well, #27726 shows a concrete requirement (see the current request filter implementation). Does it count or it has be reported by real users :-) ?

**Comment by geoand** [comment]
I'll take a look sometime soon

**Comment by sberyozkin** [comment]
@geoand It is not a major issue for now, I agree, take your time please. In the #27726 case, the random value would really be expected in practice on specific request paths, those returning HTML forms, not for all GETs, so the cost would not be great unless the app has a real lot of users

**Comment by geoand** [comment]
@sberyozkin https://github.com/quarkusio/quarkus/pull/28079 should address your issue

**Comment by sberyozkin** [comment]
Great stuff, look forward to updating `quarkus-csrf-reactive`, thanks Georgios
