### ISSUE TITLE
Reactive native returns "400 bad request" in case of bean params with template parameters

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#27762]
### Describe the bug

In case the beam param has template type quarkus fails without proper error.
Rest easy classic was working fine.

### Expected behavior

400 bad requests should be throwing some kind of hint into the log + it should work as before.

### Actual behavior

Error

### How to Reproduce?

Compile the attached test: classic works or type parameters removed.
[resteasy-reactive-problem-project.zip](https://github.com/quarkusio/quarkus/files/9497773/resteasy-reactive-problem-project.zip)

**Comment by Sgitario** [comment]
This issue is not only happening in Native, but also in JVM mode. It's a known issue, already reported by https://github.com/quarkusio/quarkus/issues/23592. Using the latest Quarkus, it does not fail, but it returns bad request.

**Comment by geoand** [comment]
I wonder if https://github.com/quarkusio/quarkus/pull/27526 already handles this as I remember @FroMage mentioning he fixed something along these lines

**Comment by Sgitario** [comment]
> I wonder if #27526 already handles this as I remember @FroMage mentioning he fixed something along these lines

I've just confirmed that this is still not working after using the changes in #27526

**Comment by geoand** [comment]
Okay, thanks for checking
