### ISSUE TITLE
Some Quarkus mode are enforcing a specific profile making it impossible to use another config profile

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#27760]
### Describe the bug

I am trying to use remote dev mode on openshift, I have a specific profile for openshift named `openshift`.

When I activate remote dev mode, `dev` profile gets activated breaking the configuration which needs the `openshift` profile to work.

### Expected behavior

Have both `dev` and `openshift` profiles enabled when it was used at build time or when it is set with `quarkus.profile`.

### Actual behavior

Only `dev` gets activated

### How to Reproduce?

I can prepare a reproducer if needed.

**Comment by ia3andy** [comment]
cc @radcortez @dmlloyd

**Comment by dmlloyd** [comment]
There needs to be clear semantic rules around how the profiles combine. For example, if profiles `%a` and `%b` are both active, then properties `%a.foo` and `%b.foo` in the same configuration file are in conflict.

I would suggest that the order of profile activations would determine the relative priority of the properties. Just as `%a.foo` would take precedence over `foo` when `%a` is activated, then activating profiles in the order `%a`, `%b` would cause `%a.foo` to have precedence over `%b.foo`, and in turn `%b.foo` has precedence over `foo`. In this way, a virtual "empty" profile can be seen as an always-activated profile which always has lower priority in comparison to explicitly activated profiles. Thoughts?

**Comment by radcortez** [comment]
This is what we already have implemented in SmallRye Config:
https://smallrye.io/smallrye-config/Main/config/profiles/

The difference is that we reverse the order of the profile listing, meaning that if we have profile `a` and `b` in this order, `b` has precedence over `a`. The rationale was that you are most likely going to define the generic profiles first and the specific ones later, for instance, if you have a profile `common` and another `dev`, you most certainly want to have `dev` override common, so it is more natural to express that by `common,dev` (in my opinion :)).

**Comment by ia3andy** [comment]
That sounds good, @radcortez let me know if I can help on this ;-)
