### ISSUE TITLE
Jackson property extension accept-case-insensitive-enums doesn't work

### ISSUE THREAD

**Issue by MarcAntoine-Beauvais** [quarkusio/quarkus#27797]
### Describe the bug

When using property
`quarkus.jackson.accept-case-insensitive-enums=true`

It should ignore case during Enum deserialization but it doesn't.

### Expected behavior

It should ignore case during Enum deserialization.

### Actual behavior

404 Not Found when trying to pass enum not matching the case

### How to Reproduce?

https://github.com/MarcAntoine-Beauvais/4j-template-quarkus

`quarkus dev`

Working:
`curl -X 'GET' 'http://localhost:8080/my-application?my_enum=STATUS_1' -H 'accept: application/json'`

Not working:
`curl -X 'GET' 'http://localhost:8080/my-application?my_enum=status_1' -H 'accept: application/json'`

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

22.2.r17-grl

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1

### Additional information

I already reported that issue but didn't had time then to upload an example, sorry for that.

**Comment by geoand** [comment]
Although I understand why one would think this is a bug, but it's actually really not.

Jackson is only used to convert the HTTP request **body**, not the various parameters (like query in this case). Those are handled differently as per the JAX-RS spec (see section `3.3.2` of [this](https://download.oracle.com/otn-pub/jcp/jaxrs-2_1-final-eval-spec/jaxrs-2_1-final-spec.pdf?AuthParam=1662617310_9ba1f2c0e3115556d8c49e9a258ebe80))
