### ISSUE TITLE
Memory Leak when using PlatformLogger

### ISSUE THREAD

**Issue by querdenker2k** [quarkusio/quarkus#27800]
### Describe the bug

When the PlatformLogger is used there will be left empty LoggerWeakRef instances of JBoss logging. This causes a memory leak.
This regards to all usages of PlatformLogger, as well these which are implicit in internal java classes. For me there is a memory leak in nearly every Quarkus application.

### Expected behavior

The instances should not be there.

### Actual behavior

Over time there will be more and more instances of this class.

### How to Reproduce?

1. Clone https://github.com/querdenker2k/quarkus-platformlogger-reproducer.git
2. Make a breakpoint here: https://github.com/querdenker2k/quarkus-platformlogger-reproducer/blob/master/src/main/java/quarkus/weakrefreproducer/WeakRefReproducer.java, Line 32
3. Evaluate the expression from Line 34

### Output of `uname -a` or `ver`

Linux s2140414 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 21.3.3 (build 11.0.16+8-jvmci-21.3-b20) OpenJDK 64-Bit Server VM GraalVM CE 21.3.3 (build 11.0.16+8-jvmci-21.3-b20, mixed mode, sharing)

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /opt/maven/current Java version: 11.0.16, vendor: GraalVM Community, runtime: /opt/java/graalvm-ce-java11-21.3.3 Default locale: de_DE, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-47-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
cc @dmlloyd @jamezp

**Comment by geoand** [comment]
@querdenker2k is this still an issue?

**Comment by querdenker2k** [comment]
I updated some dependencies of jaxws I think and the problem disappeared

**Comment by geoand** [comment]
Thanks for the update. Let's close based on that information
