### ISSUE TITLE
Kotlin - unrecommended usage of private members warning for public field injection

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#27803]
### Describe the bug

Kotlin - unrecommended usage of private members warning for public field injection

```
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field org.acme.GreetingResource$ErrorMapper#request
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1358ms
```

Equivalent java code has no warning.

Another example are quarkus quickstarts - `mvn clean package -DskipTests -pl hibernate-orm-panache-kotlin-quickstart,hibernate-orm-panache-quickstart`

CC @mkouba 

### Expected behavior

No warning

### Actual behavior

Found unrecommended usage of private members (use package-private instead) in application beans warning

### How to Reproduce?

 - get sample kotlin app - https://code.quarkus.io/?e=kotlin&extension-search=origin:platform%20quarkus-kotlin
 - extend GreetingResource.kt 
 - run `mvn clean package -DskipTests` and check the log
 
GreetingResource.kt:
```java
package org.acme

import io.quarkus.logging.Log
import io.vertx.core.http.HttpServerRequest
import javax.inject.Inject
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.WebApplicationException
import javax.ws.rs.core.MediaType
import javax.ws.rs.core.Response
import javax.ws.rs.ext.ExceptionMapper
import javax.ws.rs.ext.Provider

@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello() = "Hello from RESTEasy Reactive"

    @GET
    @Path("/fail")
    fun getFail() {
        throw WebApplicationException("Custom fail", 404)
    }

    @Provider
    public class ErrorMapper : ExceptionMapper<Exception> {
        @Inject
        public var request: HttpServerRequest? = null

        override fun toResponse(exception: Exception): Response {
            Log.info("Exception for client " + request!!.remoteAddress());

            var code = 500
            if (exception is WebApplicationException) {
                code = exception.response.status
            }
            return Response.status(code).build()
        }
    }
}
```

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.12.1.Final

**Comment by geoand** [comment]
Does the same happen if instead of 

```kotlin
        @Inject
        public var request: HttpServerRequest? = null
```

you use

```kotlin
        @Inject
        public lateinit var request: HttpServerRequest?
```

?

**Comment by geoand** [comment]
That's what I thought. 

Using `lateinit` is actually the "proper" way to do field injection in Kotlin, so I propose this being closed.

**Comment by rsvoboda** [comment]
Well, the construct that I used is what users get suggested by IntelliJ Idea when inserting Java based version.

We use the same construct in Quarkus Quickstarts. Docs cover `lateinit` example - https://quarkus.io/guides/kotlin#cdi-inject-with-kotlin

**Comment by rsvoboda** [comment]
Not saying it's correct, but many users can end up with that code.

**Comment by geoand** [comment]
Which is why they should use constructor injection in the first place 😉

**Comment by evanchooly** [comment]
It shouldn't even compile without the lateinit because you have to initialize a nonnull property.  Constructor injection is much 'cleaner' for but not always an option.  But in this case it should be favored, I think.

**Comment by geoand** [comment]
@mkouba an example without `lateinit`:

![Screenshot from 2022-09-08 17-12-01](https://user-images.githubusercontent.com/4374975/189144751-4f8a2ad8-f220-4baf-a88f-28e866b38c5c.png)

and the same field with `lateinit`:

![Screenshot from 2022-09-08 17-13-57](https://user-images.githubusercontent.com/4374975/189145122-e61017fd-0c45-4c23-9324-6fe26a59e283.png)

The code I used is coming from [here](https://github.com/quarkusio/quarkus/blob/2.12.1.Final/integration-tests/mongodb-panache-kotlin/src/main/kotlin/io/quarkus/it/mongodb/panache/book/BookRepositoryResource.kt#L28)

**Comment by geoand** [comment]
I am going to close this, as aside from transforming the bytecode, there is not much we can do.

**Comment by rsvoboda** [comment]
Thanks for the investigation, I will update the hibernate-kotlin QS to use `lateinit`

**Comment by geoand** [comment]
Great, thank you!
