### ISSUE TITLE
"HTTPS required" when creating Keycloak realm in Devservices

### ISSUE THREAD

**Issue by jendib** [quarkusio/quarkus#27818]
### Describe the bug

I'm using the Keycloak devservices and it's working fine on my local computer, however I'm getting this error in the CI:
```
2022-09-08 19:34:01,066 INFO  [🐳 .io/.0.2]] (build-35) Container quay.io/keycloak/keycloak:18.0.2 started in PT12.64803184S
2022-09-08 19:34:01,431 ERROR [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-35) Realm quarkus can not be created: {"error":"invalid_request","error_description":"HTTPS required"}
2022-09-08 19:34:01,436 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-35) Dev Services for Keycloak started.
```

### Expected behavior

No error on starting Keycloak container.

### Actual behavior

"HTTPS required" on creating realm.

### Output of `java -version`

17

### Quarkus version or git rev

2.12.1

**Comment by sberyozkin** [comment]
There are a few tests depending on Dev Services for KC in Quarkus, mainly in quickstarts but also a couple of them are in the main repo. These tests import realms, I don't recall seeing such an error. Can it be a CI specific issue ?

**Comment by jendib** [comment]
It might be, but my CI is running well for other devservices (PostgreSQL, Kafka, etc) and it's fairly standard (Docker).

**Comment by jendib** [comment]
I found out the issue. On my CI the Docker engine is running remotely (another node in the Swarm). I changed to a localhost Docker engine and the KC devservice is now running.
Feel free to close this issue if you think it doesn't need to be fixed.

**Comment by sberyozkin** [comment]
@jendib Thanks, I think it suggests that a start-up command sequence used by DevServices for KC is not quire precise, as it is really Keycloak which is enforcing HTTPS in this case. May be we should also support talking to HTTPS based endpoints. Worth keeping the issue open

**Comment by pallavi0412** [comment]
Need help for resolving HTTPS required error in development mode. Is it possible to go with http in development mode for keycloak quarkus?

**Comment by shivamtiwari18** [comment]
same issue with the "HTTPS required"

**Comment by michalvavrik** [comment]
> Need help for resolving HTTPS required error in development mode. Is it possible to go with http in development mode for keycloak quarkus?

You can see in `io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor` that by default Quarkus creates realm via HTTP and default startup command sets HTTP as well. Please if you have an issue, I'd suggest to provide reproduce (I'd go as far as open new issue, but that depends on your issue)

**Comment by michalvavrik** [comment]
> same issue with the "HTTPS required"

Hey @shivamtiwari18 , that too little information. Me for example, I don't see it in DEV mode, I'd suggest to provide reproducer. Thank you

**Comment by gastaldi** [comment]
Closing as the original issue seems to have been solved
