### ISSUE TITLE
Inject ServletContext in Quarkus application

### ISSUE THREAD

**Issue by mthmulders** [quarkusio/quarkus#2781]
**Description**
I was trying to get the [`ServletContext`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletContext.html) injected in my application:

```java
@Controller
@Path("/greeting/")
@RequestScoped
public class GreetingResource {
    @Inject
    ServletContext servletContext;
}
```

Packaging failed with:

    [1] Unsatisfied dependency for type javax.servlet.ServletContext and qualifiers [@Default]
    	- java member: exampleapp.GreetingResource#servletContext
    	- declared on CLASS bean [types=[java.lang.Object, exampleapp.GreetingResource], qualifiers=[@Default, @Any], target=exampleapp.GreetingResource]

**Implementation ideas**
I figured I needed a producer for this... Got it working with `io.undertow.servlet.handlers.ServletRequestContext#.current().getCurrentServletContext()`

Would a PR in this sense be welcomed?

**Comment by machi1990** [comment]
@mthmulders 

Is replacing `@Inject` with `@Context` (see code below) work ?  

 ```java
 @Path("/greeting/")
 @RequestScoped
 public class GreetingResource {
     @Context
     ServletContext servletContext;
 }
 ```

**Comment by mthmulders** [comment]
Yep, that works. As I've understood [at Stackoverflow](https://stackoverflow.com/a/56532909/1523342), using `@Inject` for the `ServletContext` only works in a Java EE environment. So I guess it makes sense that Quarkus doesn't do it?
