### ISSUE TITLE
Upgrade quarkus-arquillian to use JUnit 5

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#27812]
### Description

The quarkus-arquillian extension is still using the old JUnit 4 framework.
Most usages are under the tcks.
It's getting outdated because It seems that MP is trying to move towards Junit, starting that after MP 6.0.
Also, MP Telemetry tracing is based on JUnit 5.

**Comment by gastaldi** [comment]
For the record: support for JUnit 5 was introduced in Arquillian 1.7.0, which is still in Alpha stage.

**Comment by brunobat** [comment]
looks like quarkus is already using aquillian 1.7.0-alpha, however quarkus-arquillian is excluding all junit5 dependencies.
