### ISSUE TITLE
Native image build NPE

### ISSUE THREAD

**Issue by csscriptplus** [quarkusio/quarkus#27828]
### Describe the bug

@jerboaa I'll refer to ticket [#27382](https://github.com/quarkusio/quarkus/issues/27382)
The local native build on my MacBook with Docker environment works. 
The build in Jenkins with a Kubernetes pod for the native build and no Docker environment then has the NPE at runtime. So I use JIB for the container build.

Your workaround worked.

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.11.2

**Comment by geoand** [comment]
@jerboaa is there anything we need to do with this?

**Comment by jerboaa** [comment]
@geoand No. Not on the quarkus side. Feel free to close. There needs to be an upstream GraalVM issue (at https://github.com/oracle/graal/issues) and I can take a look at the NPE issue pertaining to the container code in Graal.

**Comment by geoand** [comment]
Thanks for the information.
