### ISSUE TITLE
Run Panache reactive transactional operation when application is starting

### ISSUE THREAD

**Issue by siudeks** [quarkusio/quarkus#27854]
### Describe the bug

I need to run custom transactional database logic when application is starting. My stack is only reactive, no JDBC.

I decided to put database-related logic when StartupEvent is published by Quarkus.

### Expected behavior

Working transactional reactive code when application is starting

### Actual behavior

Error:
The current operation requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such. You can still use Hibernate Reactive, you just need to avoid using the methods which implicitly require accessing the stateful context, such as MutinySessionFactory#withTransaction and #withSession

### How to Reproduce?

https://github.com/siudeks/repro-examples/tree/master/001-quarkus-reactive-panache

mvn clean test

### Output of `java -version`

java 11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/issues/27623 and this [zulip discussion](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Reactive.20code.20at.20startup) are related.

**Comment by mkouba** [comment]
This workaround seems to work:

```java
import io.quarkus.runtime.StartupEvent;
import io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle;
import io.smallrye.common.vertx.VertxContext;
import io.vertx.core.Context;
import io.vertx.core.Handler;
import io.vertx.core.Vertx;

public class Starter {

    void onStart(@Observes StartupEvent event, Vertx vertx, Mutiny.SessionFactory factory) {
        // We need a duplicated vertx context for hibernate reactive
        Context context = VertxContext.getOrCreateDuplicatedContext(vertx);
        // Don't forget to mark the context safe
        VertxContextSafetyToggle.setContextSafe(context, true);
        // Run the logic on the context created above
        context.runOnContext(new Handler<Void>() {
            @Override
            public void handle(Void event) {
                // We cannot use the Panache.withTransaction() and friends because the CDI request context is not active/propagated
                factory.withTransaction(session -> {
                    Foo f = new Foo();
                    f.name = "Foo";
                    return session.persist(f);
                })
               // We need to subscribe to the Uni to trigger the action
               .subscribe().with(v -> {});
            }
        });
    }
}
```

**Comment by siudeks** [comment]
@mkouba  is working perfectly thx
