### ISSUE TITLE
--docker-build flag seems to have no effect with Gradle plugin

### ISSUE THREAD

**Issue by vsodaitis** [quarkusio/quarkus#2786]
Since 0.15.0 version, when buildNative gradle task is invoked it asks for GRAALVM_HOME environment variable regardless of whether it is being run with --docker-build=true or --docker-build=false

**Expected behavior**
I would expect the build to not require GRAALVM_HOME set when using docker image as a build environment

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: **Linux localhost.localdomain 5.1.7-300.fc30.x86_64 #1 SMP Wed Jun 5 12:32:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**
 - Output of `java -version`: **openjdk version "1.8.0_212"**
 - GraalVM version (if different from Java): **graalvm-ce-1.0.0-rc16**
 - Quarkus version or git rev: **0.16.1**

**Comment by gwenneg** [comment]
Hi @vsodaitis and thanks for reporting this issue!

I'm really sorry you had to wait so long, but it should be fixed in Quarkus `0.21.0`.
