### ISSUE TITLE
native image JWT sign java.net.MalformedURLException: no protocol

### ISSUE THREAD

**Issue by csscriptplus** [quarkusio/quarkus#27869]
### Describe the bug

I have an application that creates a JWT and signs it. The following error occurs:
`java.net.MalformedURLException: no protocol: privateKey.pem `

As a docker image build everything works.

**application.properties**
```
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
```

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.11.2

**Comment by geoand** [comment]
Mind attaching a sample project we can test?

**Comment by csscriptplus** [comment]
@geoand here an example project: 
[quarks-test-master.zip](https://github.com/quarkusio/quarkus/files/9548290/quarks-test-master.zip)

**Comment by sberyozkin** [comment]
Let me try it, I've just tested the same setup on the main branch, works ok

**Comment by csscriptplus** [comment]
@sberyozkin: Here is my special feature. I use Jenkins to build and deploy my application and sample into my Kubernetes cluster. My Kubernetes cluster does not have a Docker environment. Therefore, the native build is done via a Kubernetes pod with a self-built image. This build image contains a Mandrel installation.
Here the files: [quarkus.zip](https://github.com/quarkusio/quarkus/files/9548570/quarkus.zip)

**Comment by geoand** [comment]
@sberyozkin the way you mention with `quarkus.native.additional-build-args` is the harder way actually. Using `quarkus.native.resources.includes`  is easier, if it fits one's use case.

**Comment by sberyozkin** [comment]
@geoand Sure, thanks, I've just seen `quarkus.native.additional-build-args=-H:IncludeResources=...` somewhere in the tests awhile back and keep copying it ever since :-).

I think we should close this issue now, @csscriptplus hope the info we provided here helps, thanks
