### ISSUE TITLE
OIDC Code Flow diagram does not fit well into the document

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#27876]
### Description

The new diagram can be seen at https://quarkus.io/version/main/guides/security-openid-connect-web-authentication
but it does not fit alongside the TOC on the right, so there is a big space there one has to scroll through before seeing it.

I wonder is it possible to add some attribute to the included image to make it align better or should the image itself become more compact ?
CC @sheilamjones, @gsmet, @phillip-kruger

**Comment by sberyozkin** [comment]
`276_0822` is also visible in the bottom right corner

**Comment by sberyozkin** [comment]
The doc recommending how to control an image positioning is here: https://docs.asciidoctor.org/asciidoc/latest/macros/image-position/

But it is hard to test it - when I build the docs locally I see TOC at the top of the generated page so the image fits underneath it so I do not see the problem locally.
While on the main website the TOC is on the right so the image does not fit and goes below, not opposite TOC. 
I guess it is `align=left` and may be `float=left` ? Does it have to have a specific size set ?
@phillip-kruger @mkouba @insectengine, can you recommend something ? thanks

**Comment by phillip-kruger** [comment]
Hi @sberyozkin - I had a quick look, but no suggestions. I think this is a ascidoc thing that I do not know well enough to comment.

**Comment by mkouba** [comment]
> But it is hard to test it - when I build the docs locally I see TOC at the top of the generated page so the image fits underneath it so I do not see the problem locally.

You can add `:toc-position: right` just bellow the `:toc:` and you should see the TOC on the right. On the other hand, it's always better to send a pull request so that the bot renders the preview of the website and adds a link to the comment ;-)

However, `float=left` does not seem to help. It looks like the image is not scaled down to fit the width.

But I'm no asciidoc expert either :-(

**Comment by mkouba** [comment]
Something like `image::authorization_code_flow.png[alt=Authorization Code Flow,width="60%",align="center"]` seems to work but no guarantee :-)

**Comment by sberyozkin** [comment]
Thanks @mkouba :-). I wonder how can we check it before opening a PR ? In my local builds I can see TOC on the top, the image - beneath it. @gsmet are you OK if we'll keep experimenting with @sheilamjones and submit a few PRs and see if the page in snapshot docs site looks OK ?

**Comment by sheilamjones** [comment]
Hi Sergey, Hi all, 
Thanks for your insights into how this could be fixed. After further research, I think the "role=center" attribute could fix this issue as that attribute allows you to scale the image relative to the content area  I updated the file to change this attribute (in PR https://github.com/quarkusio/quarkus/pull/27972). Would it be possible to verify this fix in the snapshot docs output (as my local builds also display the TOC on top with the image underneath)?

**Comment by sberyozkin** [comment]
Hi @sheilamjones Thanks, let me merge your PR and then we can compare with the way the images are shown in Bearer token guide and choose the best option, thanks for looking into it

**Comment by sberyozkin** [comment]
Hi @sheilamjones replacing the `align` with `role` did not make a difference, see https://quarkus.io/version/main/guides/security-openid-connect-web-authentication

But @mkouba's `width=60%` suggestion does better: https://quarkus.io/version/main/guides/security-openid-connect

Can you please open a PR and set `width="60%", align=center` attributes ?

**Comment by sberyozkin** [comment]
It looks better now, https://quarkus.io/version/main/guides/security-openid-connect-web-authentication

Thanks @sheilamjones @mkouba

**Comment by sberyozkin** [comment]
Fixed by #28020

**Comment by sheilamjones** [comment]
Thanks for your verification @sberyozkin
