### ISSUE TITLE
Qute puts encoding in Content-Type header for located templates and doesn't put for injected

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#27872]
### Describe the bug

I have one HTML file with Qute template.
If I inject it automagically, via `@Inject` annotation, and then return it from Resteasy endpoint, then resulting HTTP response has header `Content-Type=text/html`.
If I inject it ia `@Location` annotation, and then return from a similar endpoint, then resulting HTTP response has header `Content-Type=text/html;charset=UTF-8`.

### Expected behavior

Responses should have the same content-type for the same data and not depend on the way, which templates were acquired.

### Actual behavior

The same file injected via different annotations has different Content-Type.

### How to Reproduce?

1. `git clone -b reproducer/qute-charset git@github.com:fedinskiy/reproducer.git`
2. `cd reproducer`
3. `mvn clean verify`

The application:
```
    @Inject
    Template basic;

    @Location("basic.html")
    Template located;

    @GET
    @Path("/base")
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance base() {
        return addData(basic);
    }

    @GET
    @Path("/located")
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance located() {
        return addData(located);
    }

    private TemplateInstance addData(Template template) {
        return template.data("server", "Quarkus");
    }
```

The tests:

```
    @Test
    void smoke() {
        Response response = given().get("/base");
        assertEquals(200, response.statusCode());
        assertTrue(response.body().asString().contains("<p>This page is rendered by Quarkus</p>"),
                response.body().asString());
        assertEquals(MediaType.TEXT_HTML, response.contentType()); //This works
    }

    @Test
    void location() {
        Response response = given().get("/located");
        assertEquals(200, response.statusCode());
        assertTrue(response.body().asString().contains("<p>This page is rendered by Quarkus</p>"),
                response.body().asString());
        assertEquals(MediaType.TEXT_HTML, response.contentType());  //This fails
    }
```

### Output of `uname -a` or `ver`

5.19.4-200.fc36.x86_64

### Output of `java -version`

11.0.16 temurin

### Quarkus version or git rev

2.12.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by mkouba** [comment]
Could you test the reproducer with `resteasy-reactive-qute` as well?

**Comment by mkouba** [comment]
So the difference between `@Inject Template basic` and `@Location("basic.html") Template located` is that for the first one the template path is "incomplete" and the actual template is _selected_ in the `io.quarkus.resteasy.qute.runtime.TemplateResponseFilter` right before the rendering (based on accept headers). For `@Location("basic.html")` the path is "complete" and the `TemplateResponseFilter` does not set the media type explicitly.

**Comment by fedinskiy** [comment]
@mkouba with `quarkus-resteasy-qute`replaced with `quarkus-resteasy-reactive-qute` in pom.xml, both endpoints return `Content-Type=text/html;charset=UTF-8`.

**Comment by geoand** [comment]
In RESTEasy Reactive we explicitly add the charset when it makes sense. I have no idea why there is a difference in RESTEasy Classic.

**Comment by mkouba** [comment]
@fedinskiy Is `quarkus-resteasy-reactive-qute` a viable solution of your problem?

**Comment by fedinskiy** [comment]
@mkouba my "problem" was to test `quarkus-resteasy-reactive-qute` and `quarkus-resteasy-qute`  :)

As I mentioned earlier, this behaviour doesn't happen when `quarkus-resteasy-reactive-qute` is used.

**Comment by mkouba** [comment]
> As I mentioned earlier, this behaviour doesn't happen when `quarkus-resteasy-reactive-qute` is used.

Yes, I know. My question is whether switching to `quarkus-resteasy-reactive-qute` is an option?

**Comment by fedinskiy** [comment]
Option for who?

We (Quarkus QE team) have coverage for both classic[1] and reactive[2] scenarios and will keep it for foreseeable future anyway. This quirk does not stop us from performing other tests, so it is not a problem for us.
I can not predict, if it will be a problem for other users, and whether they can switch from regular `quarkus-resteasy-qute` to `quarkus-resteasy-reactive-qute` to solve it.

[1] https://github.com/quarkus-qe/quarkus-test-suite/blob/main/qute/synchronous/src/test/java/io/quarkus/ts/qute/QuteIT.java#L33
[2] https://github.com/quarkus-qe/quarkus-test-suite/blob/main/qute/reactive/src/test/java/io/quarkus/ts/qute/QuteReactiveIT.java#L33

**Comment by mkouba** [comment]
> Option for who?
> 
> We (Quarkus QE team) have coverage for both classic[1] and reactive[2] scenarios and will keep it for foreseeable future anyway. This quirk does not stop us from performing other tests, so it is not a problem for us. I can not predict, if it will be a problem for other users, and whether they can switch from regular `quarkus-resteasy-qute` to `quarkus-resteasy-reactive-qute` to solve it.
> 
> [1] https://github.com/quarkus-qe/quarkus-test-suite/blob/main/qute/synchronous/src/test/java/io/quarkus/ts/qute/QuteIT.java#L33 [2] https://github.com/quarkus-qe/quarkus-test-suite/blob/main/qute/reactive/src/test/java/io/quarkus/ts/qute/QuteReactiveIT.java#L33

Ok, I forgot that you're from the Quarkus QE team and the description did not mention this. So I thought that it's a problem of a user ;-).

In any case, I have no idea how to fix this in `resteasy-classic` and as I mentioned in https://github.com/quarkusio/quarkus/issues/27872#issuecomment-1243786296 - it's expected from the qute point of view.
