### ISSUE TITLE
JPA overridden properties from MapperSuperclass is not evaluated correctly

### ISSUE THREAD

**Issue by faskan** [quarkusio/quarkus#27893]
### Describe the bug

I am working on a spring-boot to quarkus migration project and I came through this issue when copying my JPA entities as it is from spring boot to quarkus. I have replicated the issue in a sample project (https://github.com/faskan/quarkus-hibernate-sample)

There exists a MappedSuperClass with name AbstractEntity, with the following field which is mapped to database column `name`
```
@MappedSuperclass
public class AbstractEntity {

    @Column(length = 40, unique = true)
    private String name;

}
```

And my entity class overrides the name property like shown below. In my spring boot project, the overridden property (name) gets evaluated correctly. But in quarkus, it gets evaluated to null.

```
@Entity
@Table(name = "known_fruits")
@NamedQuery(name = "Fruits.findAll", query = "SELECT f FROM Fruit f ORDER BY f.name", hints = @QueryHint(name = "org.hibernate.cacheable", value = "true"))
@Cacheable
public class Fruit extends AbstractEntity {

    @Id
    @SequenceGenerator(name = "fruitsSequence", sequenceName = "known_fruits_id_seq", allocationSize = 1, initialValue = 10)
    @GeneratedValue(generator = "fruitsSequence")
    private Integer id;

    @Column(length = 40, unique = true)
    private String name;

    public Fruit() {
    }

    public Fruit(String name) {
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```

The test case results in failure
```
[ERROR] Failures: 
[ERROR]   FruitsEndpointTest.testListAllFruits:21 3 expectations failed.
Response body doesn't match expectation.
Expected: a string containing "Cherry"
  Actual: [{"name":null,"id":2},{"name":null,"id":3},{"name":null,"id":1}]

Response body doesn't match expectation.
Expected: a string containing "Apple"
  Actual: [{"name":null,"id":2},{"name":null,"id":3},{"name":null,"id":1}]

Response body doesn't match expectation.
Expected: a string containing "Banana"
  Actual: [{"name":null,"id":2},{"name":null,"id":3},{"name":null,"id":1}]
```

The test case gets successful when I remove `@MappedSuperclass` annotation, but I am not sure if it would break something else.

I expect hibernate orm to evaluate the overridden property correctly when the MappedSuperclass annotation is present.

### Expected behavior

I expect hibernate orm to evaluate the overridden property correctly when the MappedSuperclass annotation is present.

### Actual behavior

The value of the overridden properties gets evaluated to null when the MappedSuperclass annotation is present in the super class.

### How to Reproduce?

Steps to reproduct:

1. Clone this repo https://github.com/faskan/quarkus-hibernate-sample
2. run `mvn quarkus:dev`
3. Test cases will fail because of incorrect evaluation of properties

### Output of `uname -a` or `ver`

Darwin Faisals-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### GraalVM version (if different from Java)

2.12.1.Final

**Comment by yrodiere** [comment]
Thanks for reporting.

The fact that the behavior is different is annoying, no argument there.

However... I'd like to point out that your `Fruit` entity has *two* `name` fields: one in the mapper superclass, and one in `Fruit`. The one from the superclass never gets used and is always null as far as I can tell.

It's really a weird setup. Ideally, you would not repeat the `name` field in your `Fruit` class. If you need overrides, then switching to getter access `@Access(AccessType.PROPERTY)` and then putting overrides on the getter would probably be a safer approach.

That being said, I'll have a closer look at the problem, maybe there's an easy solution...

**Comment by yrodiere** [comment]
I reproduced the issue in plain Hibernate ORM; the problem is not in Quarkus: https://hibernate.atlassian.net/browse/HHH-15505
Will try to address the problem in ORM.

**Comment by faskan** [comment]
@yrodiere Thank you for picking it up. 

I agree, it is a weird setup. Unfortunately the repository that I am working on (to migrate) is a legacy code with hundreds of such usages. Refactoring it like you suggested would mean a lot of effort. I'm looking forward for a better alternative.
