### ISSUE TITLE
Support Qute "Array" operations over Lists

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#27903]
### Description

According to the guide[1] Qute can use some convenience operators when accessing arrays(length, access by index, virtual method "get" and so on). It would be convenient, if the same methods could be used when accessing lists.

Examples
1. This works
```
        return Qute.fmt("There are {colors.length} colors")
                .data("colors", new String[]{"red", "green", "blue"})
                       .instance();
```

2. This fails
```
        return Qute.fmt("There are {colors.length} colors")
                       .data("colors", Arrays.asList("red", "green", "blue"))
                       .instance();
```

Since generally it is more convenient to use Lists as variables and, especially, class fields, lack of this functionality is a bit frustrating.

[1] https://quarkus.io/guides/qute-reference#arrays

**Comment by mkouba** [comment]
For lists you should use `{colors.size}`. I tend to disagree that we should treat arrays as lists although it's a very similar data structure. If we support array operations on lists we should also support list operations on arrays, or? Also do you expect that [additional List operations](https://quarkus.io/guides/qute-reference#lists) would work for arrays as well?

**Comment by fedinskiy** [comment]
Ok, in that case my suggestion would be "put all datatypes closer in the guide"(Arrays are in 3.4.5 and all other are in 4.6.4) :) Thank you, I guess this solves myproblem.

**Comment by mkouba** [comment]
> Arrays are in 3.4.5 and all other are in 4.6.4

Well, this is on purpose. Arrays are described in the core because they're handled specifically. You can call existing methods from collections and maps but 4.6.4. is about additional operations implemented by template extensions (e.g. `{list.reversed}`).
