### ISSUE TITLE
Kafka configuration reported as unknown config

### ISSUE THREAD

**Issue by itatdcer** [quarkusio/quarkus#27904]
### Describe the bug

I have configured a property for a kafka incoming topic which quarkus report as unknown:
`mp.messaging.incoming.topic-test1-in.pause-if-no-requests=false`

The documentation has this propertties available to use but I get a warning on startup:
`2022-09-13 17:34:03,125 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (main) The configuration 'pause-if-no-requests' was supplied but isn't a known config.`

In DEV mode, sometimes, it also issues a warning for the property:
`mp.messaging.incoming.topic-test1-in.group.id=my-consumer-group`
The warning is issues on the AdminClientConfig class:
`2022-09-13 17:38:29,082 WARN  [org.apa.kaf.cli.adm.AdminClientConfig] (executor-thread-0) The configuration 'group.id' was supplied but isn't a known config`

### Expected behavior

No warning issued if these property is present

### Quarkus version or git rev

2.12.1.Final

**Comment by ozangunalp** [comment]
The `pause-if-no-requests` log is already fixed upstream, and will soon land in Quarkus. \
The `group-id` log comes from the global kafka broker health check. We pass the default kafka configuration directly to the admin client we use to check the cluster.
We cannot filter for only admin config keys, as there can be security related config as well, but we can at least filter out the `group.id`.

**Comment by cescoffier** [comment]
I would add that these warnings are totally normal. If you write a serializer/deserializer/partitioner/interceptor.... anything that receives a config will display these warnings. 

We can clean up the configuration with what we know is unrelated, but imagine that your _thing_ requires the `group.id` config. It won't receive it. So, we need to clean up per target (consumer/producer/admin) and make sure we are not removing anything that could be used. It's an open set, so impossible to say exactly.
