### ISSUE TITLE
mail extension - `socket was closed unexpected` when shutting down the app

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#27918]
### Describe the bug

mail extension - `socket was closed unexpected`when shutting down the app

```
2022-09-13 17:03:59,937 ERROR [io.ver.ext.mai.imp.SMTPConnection] (vert.x-eventloop-thread-0) socket was closed unexpected. [Error Occurred After Shutdown]
2022-09-13 17:03:59,938 ERROR [io.ver.ext.mai.imp.SMTPConnection] (vert.x-eventloop-thread-1) socket was closed unexpected. [Error Occurred After Shutdown]
```

Based on the discussion with @cescoffier 
 - we keep a connection opened with the SMTP server
 - we are closing the connection, but the server didn't say BYE (yet)
 - so, we abruptly cut it (as we are shutting down)

AIs:
 - have a note in mailer reference guide
 - update the error message to mention that the remote server didn't reply when closing the connection

### Expected behavior

More context in guide / error message.

### Actual behavior

Not clear that the errors can occur.

### How to Reproduce?

 - use mailer-quickstart
 - adjust application.properties and "To:" in MailResource.java
   - was using Gmail to send the emails
 - build the app - `mvn clean package -DskipTests`
 - run the app - `java -jar target/quarkus-app/quarkus-run.jar`
 - run `curl localhost:8080/mail` twice
 - hit `Ctrl+C` and check the logs

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by gaol** [comment]
It relates to https://github.com/vert-x3/vertx-mail-client/issues/185

**Comment by cescoffier** [comment]
Thanks, @gaol, it's exactly that issue. Do you have an ETA?

**Comment by gaol** [comment]
@cescoffier these cases are inevitable IMO, when the connections are idle for a while, the SMTP server will close the connection, which will lead to this logging. 

It does not break sending of emails, but it is a noisy message, so I proposed a fix of changing the log level back to debug like what it was in v3. https://github.com/vert-x3/vertx-mail-client/pull/188

**Comment by cescoffier** [comment]
Probably a good idea to reduce the level. 

I can also filter out the message in our logging configuration.

**Comment by cescoffier** [comment]
Issue fixed upstream.

**Comment by rsvoboda** [comment]
Thanks, tried the latest Quarkus main and the error message is no longer present when shutting down the app.
