### ISSUE TITLE
quarkus-redis-client: 'fromCoordinate(double, double)' has private access in 'io.quarkus.redis.datasource.geo.GeoSearchArgs' blocking my usage of geosearch FROMLONLAT

### ISSUE THREAD

**Issue by iedwin** [quarkusio/quarkus#27913]
### Describe the bug

According to the manual of Redis geosearch command, it supports to calculate the nearist points from the given longitude and latitude as below. However when I want to use this command via quarkus-redis-client, I found the GeoSearchArgs.fromCoordinate() had private access thus I couldn't use it in my code. I believe this method should have public access as the same as GeoSearchArgs.fromMember().

GEOSEARCH key <FROMMEMBER member | FROMLONLAT longitude latitude>
  <BYRADIUS radius <M | KM | FT | MI> | BYBOX width height <M | KM |
  FT | MI>> [ASC | DESC] [COUNT count [ANY]] [WITHCOORD] [WITHDIST]
  [WITHHASH]

### Expected behavior

GeoSearchArgs.fromCoordinate() should have public access as the same as GeoSearchArgs.fromMember().

### Actual behavior

 GeoSearchArgs.fromCoordinate() has private access so I cannot use geosearch FROMLONLAT.

### How to Reproduce?

n/a

### Output of `uname -a` or `ver`

Linux a176656f74a6 5.4.0-117-generic

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19

### GraalVM version (if different from Java)

OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mavem 3.8.6

**Comment by gsmet** [comment]
My plan is to release 2.12.3.Final next Tuesday. It will contain this fix.

**Comment by iedwin** [comment]
> My plan is to release 2.12.3.Final next Tuesday. It will contain this fix.

Got it, thanks for your quick reply!
