### ISSUE TITLE
Quartz: Do not create QuartzScheduler bean, if it is not used.

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus#27929]
### Description

I'm working on the camel-quarkus (issue https://github.com/apache/camel-quarkus/issues/4076). I encountered a problem.
Camel Quartz component is trying to autowire a quartz scheduler (recent change - https://issues.apache.org/jira/browse/CAMEL-18143). 
**Before** Camel change - the scheduler was created in the component. 
**After** the change -  Quarkus's Quartz scheduler is created every time, even if it is not required by any code. Which causes IllegalStateException `Quartz scheduler is either explicitly disabled through quarkus.scheduler.enabled=false or no @Scheduled methods were found. If you only need to schedule a job programmatically you can force the start of the scheduler by setting 'quarkus.quartz.start-mode=forced'.` ([code](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L340)).

The exception is correct in the sense that no `@Scheduled` method is created. 

### Implementation ideas

It would be nice if the scheduler was not created in case that there is no demand for it (like no `@Scheduled` method).
It doesn't make sense to create a scheduler if it is not asked for, and more importantly if a creation of such bean fails, because there is no `@Scheduled` method. 
(idea is to set 'quarkus.quartz.start-mode=forced' if there is no scheduled bean)

Do you think that the proposed solution breaks any known use-case?

**Comment by JiriOndrusek** [comment]
If the proposed solution is "approved", I can work on this issue.

**Comment by mkouba** [comment]
> Do you think that the proposed solution breaks any known use-case?

Unfortunately, the `quarkus.quartz.start-mode` is a runtime config property, i.e. we cannot just skip registration of [the QuartzScheduler here](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/deployment/src/main/java/io/quarkus/quartz/deployment/QuartzProcessor.java#L74-L77).

However, you could try to obtain the `org.quartz.Scheduler` bean programatically via `@Inject javax.enterprise.inject.Instance<Scheduler>` and catch the exception while invoking the `Instance#get()`.

**Comment by JiriOndrusek** [comment]
Thanks for the hint. I will look into it.
