### ISSUE TITLE
GraalVM 19.0 Blocker List

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2792]
- [x] oracle/graal/pull/649
- [x] oracle/graal/issues/1183
- [x] oracle/graal/issues/1320 (via oracle/graal/pulls/1321)
- [x] GraalVM 19 release with aforementioned fixes

Problems for post-19:
- [ ] oracle/graal/pull/1371

**Comment by cstancu** [comment]
It looks like https://github.com/oracle/graal/pull/1371 is the only outstanding issue. That issue can be avoided by always specifying `--allow-incomplete-classpath`. (We're also considering making `--allow-incomplete-classpath` a default.) Can you check if [19.0.2](https://github.com/oracle/graal/releases/tag/vm-19.0.2) works for you? It contains a number of backported bug fixes.

**Comment by dmlloyd** [comment]
I'll be trying it out hopefully today (I have one other issue ahead of it).  With each round of testing, it's possible that more issues will be uncovered though.  We have a few undiagnosed problems yet that might or might not have roots in GraalVM itself.

**Comment by bobmcwhirter** [comment]
There's also:

https://github.com/oracle/graal/issues/1335

Which simply makes life more difficult.

**Comment by cstancu** [comment]
https://github.com/oracle/graal/pull/1371 is fixed and merged into master. Do you need it backported to a 19.0.x release?

**Comment by bobmcwhirter** [comment]
David says he doesn’t see the same issue with 19.

Granted I am also working with jdk11 where he’s working with 8.

I defer to David Lloyd.

**Comment by bobmcwhirter** [comment]
David also says (always blame David) it probably wouldn’t hurt to backport to 19.
