### ISSUE TITLE
Multi-Factored Authentication (MFA) Enhanced Form Based Authentication Extension

### ISSUE THREAD

**Issue by aaronanderson** [quarkusio/quarkus#27939]
### Description

A prototype is available here: [quarkus-form-mfa](https://github.com/aaronanderson/quarkus-form-mfa)

This optional extension would satisfy industry standard MFA requirements for Quarkus web applications where the built-in authentication mechanisms are insufficient and OIDC configuration is impractical. The ideal uses for this extension is for administrative web applications where there is a limited number of users or to provide a native bypass authentication method into a web application in case a self-administrated OIDC configuration is invalid and is no longer functional.

Key Features:

* An encrypted cookie is used to track authentication state, similar to the form based authentication mechanism
* A [JWE](https://en.wikipedia.org/wiki/JSON_Web_Encryption) [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token), similar to the OIDC ID Token except encrypted, is saved as a cookie and is used to track authentication state.
* As a user proceeds through the authentication flow the authentication context JWE is eventually upgraded to an authenticated session cookie, similar to the cookie set by the OIDC extension.
* Time Based One-Time Password ([TOTP](https://en.wikipedia.org/wiki/Time-based_one-time_password)) support
* Plugable Identity Store implementations allow interactions with back-end Cloud database user stores
* Account Lock
* Password Reset
* TOTP QR Code Key Registration
* TOTP Passcode Validation
* Application provided login and log out presentation pages
* [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) presentation support allowing views to be rendered based on the login state
* Single Page Application ([SPA](https://en.wikipedia.org/wiki/Single-page_application)) Support
    * The authentication action controller supports both HTML form encoding and JSON
    * SPAs can perform a GET request to obtain details about the current authentication state
    * Based on authentication state SPAs can post login attempts, password resets, or TOTP passcode validation requests and respond accordingly based on the result. 
    * The authentication context cookie gets updated identically to the forms based login mechanism

### Repository name

quarkus-form-mfa

### Short description

Enhanced Form Based Authentication with TOTP MFA for both HTML and JSON based authentication

### Repository Homepage URL

https://github.com/aaronanderson/quarkus-form-mfa

### Repository Topics

- quarkus-extension
- MFA
- Authentication
...

### Team Members

- @aaronanderson

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by sberyozkin** [comment]
Hi @aaronanderson It is a nice quality effort - please pursue it further in quarkiverse if you'd like.
I'm not sure though what kind of message we'd like to send with such an extension - according to the description it can be used when OIDC is too excessive, but I wonder is it really excessive - the provider manages the users, MFA if needed, etc, and a lot of effort has to go into this new extension to achieve much of what the OIDC provider's admin console supports.
This is only my opinion though...

**Comment by sberyozkin** [comment]
If you decide to keep going with it in Quarkiverse then consider renaming it to `quarkus-form-mfa` as `quarkus-mfa` is a too generic name

**Comment by aaronanderson** [comment]
Hi @sberyozkin , thanks for the feedback. I would like to pursue adding the extension to Quarkiverse if there are no objections. 
I agree OIDC should be the strongly recommended as the primary means of protecting Quarkus web applications. This extension really serves two use cases:

1. Delegated OIDC configuration administration - I am building a multi-tenanted Quarkus web application where clients will be able to configure OIDC SSO with their tenant through a self service interface. It is possible the OIDC IDP they configure is for a test environment that gets decommissioned, refreshed, or they enter in incorrect connection information that would lock them out of their tenant. This extension provides a backdoor secure direct login to their tenant to revise their security settings. Many companies security policies now require MFA so a Quarkus native authentication mechanism would need to support it.

2. Secure access to administrative application - My organization is small and we do not have a centralized OIDC IDP yet. Setting up an AWS Cognito IDP or managing a Keycloak AWS ECS to protect an administrative application that will only have a handful of users in it is not cost effective. 

Most likely not many people would use this extension but having it in Quarkiverse would make it available if need arises.

**Comment by sberyozkin** [comment]
Hi @aaronanderson

>thanks for the feedback. I would like to pursue adding the extension to Quarkiverse if there are no objections.

No problems at all, and I don't think any objections can follow as Quarkiverse is a place for the users to innovate, so please go ahead. CC @gastaldi 

>Most likely not many people would use this extension but having it in Quarkiverse would make it available if need arises.

Who knows, may be many users will find it useful :-). It would make sense IMHO to describe some typical use cases where such an extension can be used, similarly to what you've typed above. Perhaps your original extension name proposal is best, `quarkus-mfa`

**Comment by gastaldi** [comment]
> Perhaps your original extension name proposal is best, `quarkus-mfa`

+1 on `quarkus-mfa`, I think it makes more sense, given the description above. I'll setup the repository

**Comment by sberyozkin** [comment]
Thanks @gastaldi

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-mfa

Please follow the next steps in https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created
