### ISSUE TITLE
Please add support for Caffeine JCache

### ISSUE THREAD

**Issue by javaduke** [quarkusio/quarkus#27935]
### Description

Caffeine has support for JCache (https://github.com/ben-manes/caffeine/tree/master/jcache) but it is not supported by Quarkus. Yet it may be useful to support it as it can be used, for example, in `camel-quarkus` by the `camel-quarkus-jcache` extension.

### Implementation ideas

I think all it takes is modifying the existing `caffeine` extension by adding one dependency and one class to register for reflection. To be specific, 
```
<dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>jcache</artifactId>
        </dependency>
```
and add the class `"com.github.benmanes.caffeine.jcache.copy.JavaSerializationCopier"` to the list of classes to register for reflection in the `CacheConstructorsFeature.java`

**Comment by gwenneg** [comment]
As discussed [here](https://github.com/quarkusio/quarkus/pull/27937#discussion_r973045797), this will be addressed in `camel-quarkus`.
