### ISSUE TITLE
Add mock mailer

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2793]
The new mailer extension is nice but there's no way to test emails. I've gotten used to having a `MockMailer` instance in DEV/TEST mode that I can use to test email sending: it stores rendered emails in a bean that you can look up to verify things and prints them on stdout.

I'll make a PR about this because it's very useful.

**Comment by cescoffier** [comment]
Did you tried `quarkus.mailer.mock=true` ?

**Comment by cescoffier** [comment]
but it does not do what you said, it just prints the content of the mail in the console.

**Comment by FroMage** [comment]
No, because it's not documented prominently enough. This is great, but it should be ON by default in DEV/TEST modes, and it should store the emails in a bean so that tests can find it.

**Comment by FroMage** [comment]
How far do you want to go to hide Vert.x? In Redpipe, the mock mailer is an instance of `ReactiveMailer` that you can cast to `MockMailer` to get access to emails sent. I can expose the sent emails as `MailMessage` (Vert.x type) or wrap it to hide it.

For Quarkus, either I make the `MockMailer` a subtype of `ReactiveMailer` that you get if `mock=true` (defaults to true for DEV/TEST) and you have to cast down, or I was thinking it could be better to have another bean named something like `MockMailDeliveries` that contains the sent emails. WDYT?

**Comment by cescoffier** [comment]
It would be confusing if the sent email is not an instance of the `Mail` class the user has sent no? We can just store a reference in the ReactiveMailer.

**Comment by FroMage** [comment]
You're right, I was confused by Redpipe's need to make the "sent email" class different to the "email to send" class because I wanted the result of template rendering in the "sent email" class. I did it in #2804

**Comment by FroMage** [comment]
Thanks
