### ISSUE TITLE
Quarkus extensions for Azure services

### ISSUE THREAD

**Issue by majguo** [quarkusio/quarkus#27932]
### Description

This repository will host Quarkus extensions for different Azure services, e.g.:
- [Key Vault](https://azure.microsoft.com/services/key-vault/)
- [App Configuration](https://docs.microsoft.com/azure/azure-app-configuration/overview)
- [Cosmos DB](https://docs.microsoft.com/azure/cosmos-db/introduction)
- [Blob storage](https://docs.microsoft.com/azure/storage/blobs/storage-blobs-introduction)
- [Service Bus](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-messaging-overview)
- [Event Hubs](https://docs.microsoft.com/azure/event-hubs/event-hubs-about)
- ...

### Repository name

quarkus-azure-services

### Short description

Quarkus extensions for Azure services

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-azure-services/dev/

### Repository Topics

- quarkus-extension
- quarkus
- azure

### Team Members

- m-reza-rahman
- edburns
- majguo
- zhengchang907
- galiacheng

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by melloware** [comment]
I would love this!  1 thing is I ran into Native Image issues with Quarkus using Azure Blob Storage due to this issue: https://github.com/Azure/azure-sdk-for-java/issues/30332

**Comment by gastaldi** [comment]
Welcome to the Quarkiverse! :)

The repository was created in https://github.com/quarkiverse/quarkus-azure-services and permissions were granted to the team members. 

Please follow the checklist in  https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created with the next onboarding steps.

**Comment by majguo** [comment]
Hello @gastaldi , could you pls also add the same permissions to @agoncal for https://github.com/quarkiverse/quarkus-azure-services?

**Comment by agoncal** [comment]
@gastaldi yes please ;o)

**Comment by gastaldi** [comment]
PR created: https://github.com/quarkiverse/quarkiverse-devops/pull/103

BTW any Quarkiverse member is allowed to create PRs in the quarkiverse-devops repository (note that the branch needs to be in the same repository, forks won't work)

**Comment by freydsb** [comment]
@agoncal Hi Antonio - I cant seem to find the artifact  on https://mvnrepository.com/
```
<dependency>
    <groupId>io.quarkiverse.azureservices</groupId>
    <artifactId>quarkus-azure-app-configuration</artifactId>
    <version>{project-version}</version>
</dependency>
```

Did it move or is the project dead?

**Comment by majguo** [comment]
@freydsb Thanks for asking. The project is in progress and tracked in https://github.com/quarkiverse/quarkus-azure-services. As for now, the extensions are not released to mvn repository yet, and this is exactly the goal we're targeting next.
