### ISSUE TITLE
[OTEL]: Setting OTEL Java Agent option in `application.properties` does not work

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#27945]
### Describe the bug

I am trying to disable a feature which strips all whitespace from traced SQL queries:
- https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#db-statement-sanitization

According to [this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6610) issue, I should set:
`otel.instrumentation.common.db-statement-sanitizer.enabled=false`

In my `application.properties`

However I have done this, and it seems to make no difference.
Is there a special way I need to configure this in Quarkus?

```properties
quarkus.opentelemetry.enabled=true
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://localhost:4317
# For SmallRye config, try both ways I guess due to ENV var naming convention translation
otel.instrumentation.common.db.statement.sanitizer.enabled=false
otel.instrumentation.common.db-statement-sanitizer.enabled=false 
```

```kt
dependencies {
    // ... omitted
    implementation("io.quarkus:quarkus-opentelemetry-exporter-otlp")
    implementation("io.opentelemetry.instrumentation:opentelemetry-jdbc")
```

### Quarkus version or git rev

2.12.2-Final

**Comment by GavinRay97** [comment]
If I manually set it in my Quarkus Application main it works 🤔 
When I log the value, it logs `null`:

```kt
@QuarkusMain
object Application {

    @JvmStatic
    fun main(args: Array<String>) {
        Quarkus.run(MyApp::class.java, *args)
    }

    class MyApp : QuarkusApplication {
        override fun run(vararg args: String): Int {
            init()
            Quarkus.waitForExit()
            return 0
        }

        private fun init() {
            val otelSanitizerProp = "otel.instrumentation.common.db-statement-sanitizer.enabled"
            val otelSanitizerValue = System.getProperty(otelSanitizerProp)
            println("otel.instrumentation.common.db-statement-sanitizer.enabled: $otelSanitizerValue")
            System.setProperty(otelSanitizerProp, "false")
        }
    }
}
``

![image](https://user-images.githubusercontent.com/26604994/190273910-56c77cfb-60a4-4df7-a28f-4b52d277ba79.png)

**Comment by geoand** [comment]
cc @brunobat

**Comment by brunobat** [comment]
We are aware of this issue and we are working on the OTel autoconfiguration on Quarkus. 
Currently, otel side properties are not supported.  
Related issue: https://github.com/quarkusio/quarkus/issues/26444

**Comment by geoand** [comment]
Sounds like this is a duplicate issue then, right?

If so, please close it and apply the corresponding label

**Comment by GavinRay97** [comment]
I'll close the issue but if I could ask for some clarification on _why_ (just for my own understanding) setting it in the `application.properties` doesn't work that would be much appreciated.

I thought that the app properties were universal, and also that SmallRye Config would set the corresponding ENV vars for each of them.
