### ISSUE TITLE
quarkus.platform.version not in config sources

### ISSUE THREAD

**Issue by Joofthan** [quarkusio/quarkus#27947]
### Describe the bug

The property "quarkus.platform.version" is not available.

It is listed in the Guide: https://quarkus.io/guides/all-config

### Expected behavior

Response with Text: 
"Quarkus Version: 2.12.2.Final"
 or 
"Quarkus Version: 999-SNAPSHOT"

### Actual behavior

Failed to load config value of type class java.lang.String for: quarkus.platform.version

### How to Reproduce?

Empty Quarkus Project with new class:
```
@Path("/version")
public class VersionResource {
    @ConfigProperty(name = "quarkus.platform.version")
    String quarkusVersion;
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Quarkus Version: "+quarkusVersion;
    }
}
```

mvn clean package -DskipTests
java -jar target/quarkus-app/quarkus-run.jar

GET -Request to:  
localhost:8080/version

### Output of `uname -a` or `ver`

Darwin XXXXX 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode)

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/XXXXX/Applications/apache-maven-3.8.4 Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /Users/XXXXXX/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home Default locale: de_DE, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
What does your `pom.xml` look like?

**Comment by Joofthan** [comment]
It looks like Defaut + Java 17 ( https://code.quarkus.io/?j=17 ) without any changes.

**Comment by radcortez** [comment]
@geoand the issue here is that we are mapping `quarkus.platform.version` as build time only: https://github.com/quarkusio/quarkus/blob/8c980c4695515df4f39a705f1c243174f2f4ccf1/core/deployment/src/main/java/io/quarkus/deployment/PlatformConfig.java

So the values are not recorded for runtime. Do we want to change this?

**Comment by geoand** [comment]
I personally don't see a very compelling reason to do so, but on the other hand it wouldn't add any overhead, so I'll leave it up to you

**Comment by Joofthan** [comment]
I just wanted to display the Quarkus version on the UI. If there is a better way to do it, a hint is welcome.
I expected the value to be readable, because it is listed on the page. Also the Default value "999-SNAPSHOT" is confusing me as a User.

**Comment by radcortez** [comment]
You should be able to use https://github.com/quarkusio/quarkus/blob/c9cba824e8812fa3f15474b8382ac5d90f7238aa/core/builder/src/main/java/io/quarkus/builder/Version.java#L12 to get the version.

The `999-SNAPSHOT` is because that is the default version assigned when nothing else can be found.

**Comment by Joofthan** [comment]
mvn package says: package io.quarkus.builder does not exist.
I also can not find the "Version.properties" file. I am building with "quarkus.package.type=uber-jar".

But thanks for the hint. I can read the Version from "META-INF/maven/io.quarkus/quarkus-core/pom.properties"
This does work for me.

**Comment by geoand** [comment]
So I'll go ahead and close this.

**Comment by knutwannheden** [comment]
Possibly it would be good if the generated documentation could also reflect which properties are only available at build-time.

**Comment by gsmet** [comment]
Hum. I think we should have an easy way to get the Quarkus version. Reading `META-INF/maven/io.quarkus/quarkus-core/pom.properties` doesn't sound exciting to me.

**Comment by radcortez** [comment]
If we add the dependency: 

```xml
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-builder</artifactId>
</dependency>
```

Then you can use `Version.getVersion()`. The `quarkus-builder` jar contains the `Version.properties` file with the Quarkus version. This should work in any mode.

Maybe what we need is to have this directly into the core instead of requiring to add the dependency.
