### ISSUE TITLE
@Transactional on default method

### ISSUE THREAD

**Issue by lgarin** [quarkusio/quarkus#27949]
### Describe the bug

The `@Transactional` annotation is not observed by Quarkus if placed on a default method. If such a method is used to persist an entity then the call will fail with a `TransactionRequiredException`.

**Example**
```java
public interface MyInterface {
  void nonTransactionalMethod(String field);

  @POST
  @Path("/createDefault")
  @Transactional
  default void transactionalDefaultMethod(@QueryParam("field") String field) {
    nonTransactionalMethod("Default: " + field);
  }
}
```
**Example**
```java
public interface MyInterface {
  void nonTransactionalMethod(String field);

  @POST
  @Path("/createDefault")
  @Transactional
  default void transactionalDefaultMethod(@QueryParam("field") String field) {
    nonTransactionalMethod("Default: " + field);
  }
}
```

### Expected behavior

A default method annotated with `@Transactional` must start a transaction if no current transaction is active.

### Actual behavior

The `@Transactional` annotation on default methods is ignored and persisting an entity in such a method fails with a `TransactionRequiredException`.

### How to Reproduce?

A sample project in GitHub reproduces this issue. 
[https://github.com/lgarin/transactional-interface/](url)

This projects includes two unit tests in the class `MyResourceTest`.
- `testTransactionEndpoint` uses an endpoint implemented by a class method. This test correctly stores a new entity using a new transaction.
- `testDefaultTransactionEndpoint` uses an endpoint implemented by a default method. This test fails to store a new entity because no transaction has been started.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1889]

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-39) OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

This issue is very similar to #14696 but with this new issue the annotation has been defined at the method level instead of interface level.

**Comment by geoand** [comment]
@mkouba is this behavior expected or is it a bug?

**Comment by mkouba** [comment]
So in CDI the interceptor bindings are never inherited from interfaces. It's forbidden by the spec. See [Inheritance and specialization](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#inheritance): _"Type-level metadata is never inherited from interfaces implemented by a bean."_ and _"Member-level metadata is not inherited."_.

What does work is that the default method is intercepted if you add an interceptor binding to the implementation bean class, i.e. something like:

```java
@Transactional
public class MyClass implements MyInterface {
  // -> transactionalDefaultMethod() will be intercepted
}
```
You'll need to annotate all non-transactional methods with `@Transactional(Transactional.TxType.SUPPORTS)` though.

**Comment by geoand** [comment]
@mkouba Thanks!

I am going to close as `won't fix` based on your explanation.
