### ISSUE TITLE
MicroProfile Rest Client property mp/scope has not been implemented

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2797]
**Describe the bug**
MicroProfile Rest Client property mp/scope has not been implemented resulting in some TCK tests failing, like for example `org.eclipse.microprofile.rest.client.tck.cditests.HasAppScopeTest` .

These tests are currently being [skipped](https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L25)

**Comment by machi1990** [comment]
https://github.com/quarkusio/quarkus/pull/2940 also treats this.
