### ISSUE TITLE
CloudEvent deserialization does not work with quarkus-resteasy-reactive

### ISSUE THREAD

**Issue by wojciechkopciewicz** [quarkusio/quarkus#27970]
### Describe the bug

When using quarkus-resteasy-reactive (plus quarkus-resteasy-reactive-jackson) CloudEvent class cannot be deserialized on REST endpoints. Everything works fine with quarkus-reasteasy.

### Expected behavior

CloudEvent class should be deserialized.

### Actual behavior
The following exception is being thrown and 500 Internal Server Error is returned from the server:
```
ERROR [io.qua.res.rea.jac.run.map.NativeInvalidDefinitionExceptionMapper] (vert.x-eventloop-thread-0) com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.cloudevents.CloudEvent` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (ByteArrayInputStream); line: 1, column: 1]
```
### How to Reproduce?

[cloudevents-reactive-sample.zip](https://github.com/quarkusio/quarkus/files/9576834/cloudevents-reactive-sample.zip)

### Quarkus version or git rev

2.12.2.Final

**Comment by geoand** [comment]
I'll have a look later on today or tomorrow

**Comment by geoand** [comment]
It seems to work in Classic RESTEasy because of an undocumented feature there: The extension code scans the classpath for JAX-RS Providers. I am a little weary of adding the same feature to RESTEasy Reactive.

I propose adding the [Jandex plugin](https://github.com/wildfly/jandex-maven-plugin) to the build of `io.cloudevents:cloudevents-http-restful-ws`.

**Comment by wojciechkopciewicz** [comment]
@geoand would you be able to provide a working example?

**Comment by geoand** [comment]
I'm actually rethinking this and it probably does make sense to do what RESTEasy Classic does

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/27981 should take care of the issue

**Comment by wojciechkopciewicz** [comment]
In the meantime I tried to use jandex option using application.properties approach described here: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index and it works fine.

**Comment by geoand** [comment]
Yeah, that's the general way to index libraries on the classpath that are not searched by default
