### ISSUE TITLE
Unused Narayana is started upon application start

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#27982]
### Describe the bug

`mongodb-panache-common` adds the `narayana-jta` extension. Although added, the transaction manager was never used and thus not started. 

As of `2.13.0.CR1` the transaction manager is started nearly immediately at startup

### Expected behavior

Narayana is not started if not used.

Additionally, it would be nice to not have it included if it's not going to be used.

### Actual behavior

Narayana JTA is started almost immediately on startup.

In an application with Flyway enabled, the JTA is started prior to running migrations and a message is produced.
```
20:29:15 INFO  ARJUNA032010: JBossTS Recovery Service (tag: 518c8dd50a9ae8e70eb15dfe8fc764adcabef8ab) - JBoss Inc.
20:29:15 INFO  ARJUNA032013: Starting transaction recovery manager
20:29:15 INFO  Flyway Community Edition 9.3.0 by Redgate
```

In applications without Flyway **no message is produced** but the application creates the telltale `ObjectStore` directory indicating that some portion of the JTA is starting.

### How to Reproduce?

Add `mongodb-panache` to an application to you'll see `ObjectStore` directories.

Additionally add Flyway and observe the logging related to started the JTA.

### Output of `uname -a` or `ver`

macOS 12.6

### Output of `java -version`

OpenJDK 17.0.1

### Quarkus version or git rev

2.13.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment]
cc @loicmathieu who added the transaction support for Mongo

**Comment by loicmathieu** [comment]
@mmusgrov @gsmet does something changed on the Narayana side that can cause this issue ?
@kdubb does it creates a real issue or it's just an observation that it is started now and not before ?

**Comment by kdubb** [comment]
Everything works but I would argue that spending time starting unused subsystems is a "real" issue for Quarkus.

**Comment by kdubb** [comment]
@gsmet Here is a reproducer using Gradle. This was created by code.querkus.io, no code changes were made at all.

To reproduce, start the app (I used `quarkus dev`) and all will seem correct but after quitting the application (using `q`) the `ObjectStore` directory structure will be created in the root project directory.

[gradle-object-store-at-quit.zip](https://github.com/quarkusio/quarkus/files/9586729/gradle-object-store-at-quit.zip)

**Comment by gsmet** [comment]
Are you sure the transaction manager was not started? Or was it more that it wasn't logging anything so you didn't know it was started? (honest question)

**Comment by kdubb** [comment]
Haha how's that for timing. I'm working on Maven now.

**Comment by kdubb** [comment]
Only because in the 2.12 series no directories are created at any time and no startup messages are logged. I'm going to add Flyway to the above example and you'll see both startup log messages and the ObjectStore is created at that point rather than at exit.

**Comment by kdubb** [comment]
Here is Maven. It has the exact same behavior as the Gradle reproducer above. For Maven I used `man quarkus:dev` to start the app.
[maven-object-store-at-quit.zip](https://github.com/quarkusio/quarkus/files/9586778/maven-object-store-at-quit.zip)

**Comment by kdubb** [comment]
This is Maven with Flyway. I added a small simple migration. Started app using `mvn quarkus:dev` again.

In this case you will see the Narayana/Arjuna startup messages during initialization and prior to Flyway's migrations.
[maven-flyway-object-store-at-start.zip](https://github.com/quarkusio/quarkus/files/9586822/maven-flyway-object-store-at-start.zip)

**Comment by geoand** [comment]
@gsmet are you looking at this one?

**Comment by mmusgrov** [comment]
Narayana checks the transaction logs to determine whether or not there are in doubt transactions that may need to be recovered.

**Comment by gsmet** [comment]
I think we found a good compromise for 2.13 here: https://github.com/quarkusio/quarkus/pull/28025 .

More involved changes will have to be made in 2.14.
