### ISSUE TITLE
Scope of MP REST Client is singleton by default

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2798]
**Describe the bug**
The rest client beans use the `Singleton` scope by default, which seems to be at odds with the spec and leads to some TCK tests failing (for example `org.eclipse.microprofile.rest.client.tck.cditests.CDIInvokeSimpleGetOperationTest`).

These tests are currently being [skipped](https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L47).

**Comment by machi1990** [comment]
@geoand I can take a look at this. Do you know how I can activate and test the skipped TCKs?

**Comment by geoand** [comment]
@machi1990 cool!

To run the TCK tests you just need to add `-Dtcks`.

Then just take a look at `tck-suite.xml` and see the comments on the disabled tests to see which ones you should enable once you have the fix.

Let me know if you need anything else, although it should be pretty straightforward to tackle this one (I am guessing anyway since I haven't actually looked into the code that would need changing)

**Comment by machi1990** [comment]
> Then just take a look at `tck-suite.xml` and see the comments on the disabled tests to see which ones you should enable once you have the fix.

Sorry,  I am pretty new on running TCKs tests. So I am going to ask will it suffice to remove these lines? https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L47-L57


> Let me know if you need anything else, although it should be pretty straightforward to tackle this one (I am guessing anyway since I haven't actually looked into the code that would need changing)

Yes, I think I know where to look at.

**Comment by geoand** [comment]
> > Then just take a look at `tck-suite.xml` and see the comments on the disabled tests to see which ones you should enable once you have the fix.
> 
> Sorry, I am pretty new on running TCKs tests. So I am going to ask will it suffice to remove these lines?
> 
> https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L47-L57
>

Exactly! That file contains (among other things) the tests have been currently excluded due to the fact that the current implementation doesn't pass them. So removing those line will re-enable the tests (you can verify it by doing it and running the testsuite and seeing the them fail)
 
> > Let me know if you need anything else, although it should be pretty straightforward to tackle this one (I am guessing anyway since I haven't actually looked into the code that would need changing)
> 
> Yes, I think I know where to look at.

:+1:
