### ISSUE TITLE
`@TestHTTPResource` should also consider `quarkus.http.root-path`

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#27988]
### Describe the bug

Currently, the `@TestHTTPResource` annotation doesn't appear to respect the `quarkus.http.root-path` config. I.e. an injected path is not resolved against that root, but always against `/`.

### Expected behavior

The injected path should be a path that is prefixed with `quarkus.http.root-path`.

### Actual behavior

See description.

### Quarkus version or git rev

2.12.2.Final

**Comment by geoand** [comment]
This should be fixed in `2.13.CR1`. Can you check/

**Comment by knutwannheden** [comment]
I will look into it next week.

**Comment by geoand** [comment]
Okay. I'll close this for now but feel free to comment if it does not work in your case
