### ISSUE TITLE
OpenTelemetry CLIENT spans must have an `Error` status on 4xx status codes

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#27984]
### Describe the bug

According to the [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) the CLIENT spans must have an `ERROR` status when the server returns a HTTP 4xx status:

> For HTTP status codes in the 4xx range span status MUST be left unset in case of `SpanKind.SERVER` and MUST be set to `Error` in case of `SpanKind.CLIENT`.

### Expected behavior

See description.

### Actual behavior

Currently, the RestEasy Reactive REST Client emits client spans, which don't have any error status set.

Server spans don't have any error status in this case, which is correct.

Note: I didn't check if the server or client spans have an error status in the case of a 5xx status. AFAICT they should, but the specification isn't entirely clear to me in this area:
> For HTTP status codes in the 5xx range, as well as any other code the client failed to interpret, span status MUST be set to `Error`.

### Quarkus version or git rev

2.12.2.Final

**Comment by geoand** [comment]
@brunobat @radcortez let me know if you need any REST Client help with this

**Comment by brunobat** [comment]
A reproducer would be nice, @knutwannheden

**Comment by knutwannheden** [comment]
> A reproducer would be nice, @knutwannheden

I am quite busy at the moment and it will unfortunately take me some time until I get to this.

**Comment by geoand** [comment]
Closing as we never got a reproducer.
