### ISSUE TITLE
Unable to @Inject MP REST Client beans with the @RestClient qualifier

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2799]
**Describe the bug**
We are unable to @Inject MP REST Client beans with the @RestClient qualifier which leads to some TCK failures (like `org.eclipse.microprofile.rest.client.tck.InvokeWithJsonPProviderTest`).

These tests are currently [skipped](https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L59).

**Comment by kenfinnigan** [comment]
Resolved as part of #4520
