### ISSUE TITLE
When executing a Test/start the app, which has an Rest endpoint annotated with @Parameter a warning is given

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#28006]
### Describe the bug

I am not sure if it is a bug or not but is a change compared to the previous Quarkus version, which I have not seen described in any migration guide.

If it is not a bug, how can we achieve the same functionality, without the warning?

### Expected behavior

No warning should be seen in the console when starting the application or executing a test.
No warning is given in: 2.10.1.Final

### Actual behavior

A warning is seen in the console when starting the application or executing a test:

WARN: SROAP07902: @Parameter annotation missing JAX-RS parameter. Class: q.MyController, Method: javax.ws.rs.core.Response ep1(), Parameter.name: some, Parameter.in: header

Same behavior can be seen also in 2.12.2.Final 
[rest-client-reactive-quickstart14.zip](https://github.com/quarkusio/quarkus/files/9584130/rest-client-reactive-quickstart14.zip)

### How to Reproduce?

Run the provided test

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.13.0.CR1

**Comment by geoand** [comment]
Shouldn't you be using

```java
	@Parameter(in = ParameterIn.HEADER, required = true, name = "some", example = "some", schema = @Schema(type = SchemaType.STRING), description = "message id")
	@GET
	@Path(EP1)
	public Response ep1(@HeaderParam("some") String some) {
		
		return Response.ok().build();
	}
```

or 

```java
	@Parameter(in = ParameterIn.HEADER, required = true, name = "some", example = "some", schema = @Schema(type = SchemaType.STRING), description = "message id")
	@GET
	@Path(EP1)
	public Response ep1(@RestHeader String some) {
		
		return Response.ok().build();
	}
```

?

I mean what's the point of using the `@Parameter` if the JAX-RS method does not actually use the header value?

**Comment by lthasle** [comment]
@geoand 
Thanks for your proposal, they work.
The @Parameter is used in a common Interceptor for all our Controllers.
I don't like the idea of adding several @RestHeader to all of our method signatures.

**Comment by geoand** [comment]
I'll leave it up to @MikeEdgar to decide if there should be a way to disable to OpenAPI warning. In any case, I'm going to close this as it's not a Quarkus issue.

**Comment by lthasle** [comment]
@geoand 
It would help if it was possible to use a constant in @Parameter when we use  @RestHeader

@Path(MyController.DOMAIN)
public class MyController {

	public static final String DOMAIN = "my";
	public static final String EP1 = "/ep1/";
	public static final String EP2 = "/ep2/";
	
	private static final String MSG = "msg";
	
	// works:
	@Parameter(in = ParameterIn.HEADER, required = true, name = MSG, example = MSG, schema = @Schema(type = SchemaType.STRING), description = "message id")
	@GET
	@Path(EP1)
	public Response ep1(@HeaderParam(MSG) String some) {
		
		return Response.ok().build();
	}
	
	// Using a constant in the @Parameter for @RestHeader, gives a warning:
	@Parameter(in = ParameterIn.HEADER, required = true, name = MSG, example = MSG, schema = @Schema(type = SchemaType.STRING), description = "message id")
	@GET
	@Path(EP2)
	public Response ep2(@RestHeader String givesAWarn) {
		return Response.ok().build();
	}	
}
`

**Comment by MikeEdgar** [comment]
> It would help if it was possible to use a constant in `@Parameter` when we use `@RestHeader`

Does it warn if the argument is named `msg` instead of `givesAWarn` ?

**Comment by lthasle** [comment]
@MikeEdgar 
No warning is given when using the code below.

`
@Parameter(in = ParameterIn.HEADER, required = true, name = MSG, example = MSG, schema = @Schema(type = SchemaType.STRING), description = "message id")
	@GET
	@Path(EP1)
	public Response ep1(@RestHeader String msg) {
		return Response.ok().build();
	}	
`

**Comment by MikeEdgar** [comment]
Ok, thanks. So the constant works as long as it matches the argument name, which is expected.
