### ISSUE TITLE
Jakarta - EE 10 - Weird Jackson serialization issue in REST Data Panache

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#28016]
The `extensions/panache/hibernate-orm-rest-data-panache/deployment` tests in `jakarta-rewrite` has started to fail (not every time AFAICS) with stackoverflow errors:

> Infinite recursion (StackOverflowError) (through reference chain: io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Collection["items"]->org.hibernate.collection.internal.PersistentBag[0]->io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.Item["collection"]

I always get the error in `io.quarkus.hibernate.orm.rest.data.panache.deployment.entity.PanacheEntityResourcePathCustomisationTest` locally. It seems the other tests are OK.
We have some Jackson annotations to prevent this issue so not sure what's going on. And also not sure what's specific to Jakarta.

What I don't understand is that it's not an issue in main Quarkus. Also once we have this error, Quarkus is in a very weird state as once I reproduce this, the build is stuck for several minutes until it's cancelled by our test infrastructure.

**Comment by geoand** [comment]
cc @Sgitario

**Comment by Sgitario** [comment]
As far I'm seeing, this is the issue: `java.lang.ClassNotFoundException: javax.annotation.Nonnull`.

**Comment by Sgitario** [comment]
I tried to dig further into this issue but am unsure what can be done to overcome it. The `byte-buddy` dependency is used by the Hibernate ORM Quarkus extension and internally is using the NotNull Javax annotation which is not in the classpath any longer in the `jakarta-rewrite` branch. 
Any ideas/tips? @gsmet

**Comment by Sgitario** [comment]
I could find the root cause of this issue. From Jackson 2.13.4, they changed the primary annotation instrospector (the entity that *inspect* the annotations in use) from `ParameterNamesAnnotationIntrospector` to `JakartaXmlBindAnnotationIntrospector` (see commit [here](https://github.com/FasterXML/jackson-modules-base/commit/62475cf5ca46201ba98ffbf2969353ca33efb4ef)).

This was done because a new module for jakarta was added. 

And the problem is that we add dynamically the `@XmlTransient`  annotation to all the fields of an entity: https://github.com/quarkusio/quarkus/blob/9bc683f75218169a5a613de87e75102532330586/extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheEntityClassAccessorGenerationVisitor.java#L92

Therefore, the new behaviour in `JakartaXmlBindAnnotationIntrospector` makes the annotations within the field to be ignored.

**Comment by gsmet** [comment]
I always forget that they based the JAX-RS JSON support in Jackson on the XML one...

**Comment by Sgitario** [comment]
> @Sgitario are you sure it was only `ParameterNamesAnnotationIntrospector` before? Because I don't see it actually doing anything with the ignore annotations?
> 
> Trying to make sure I understand why the behavior change. Because I would have expected Jackson 2.13 non-jakarta to have a javax equivalent of this.

Actually, before it was working because `ParameterNamesAnnotationIntrospector` was ignoring the `XmlTransient` annotations and now `JakartaXmlBindAnnotationIntrospector` is taking into account it.

**Comment by gsmet** [comment]
@Sgitario so https://github.com/FasterXML/jackson-modules-base/blob/2.13/jaxb/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java is not used in the javax flavor?
What I would like to understand is how we switched from one to another, because I thought we would have `JaxbAnnotationIntrospector` around before.

From what I read from the Jackson commit, we need to explicitly register the module. So was the JAXB module not registered before? And now the JakartaXmlBind one is?
And how did that affect the JSON `ObjectMapper` we should use?

**Comment by Sgitario** [comment]
The `jackson-module-jakarta-xmlbind-annotations` dependency is coming from `resteasy-jackson2-provider` which is used by the Resteasy Jackson extension. And having this dependency in the classpath will replace the previous setup that was defined by the Quarkus Jackson extension.

**Comment by gsmet** [comment]
@Sgitario can you point me where it's done? Because that's not obvious to me that it should.
