### ISSUE TITLE
Qute fails on illegal map identifiers, even when using bracket notation

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#28013]
### Describe the bug

According to Qute guide[1], when working with maps, it is possible to use "illegal" keys(e.g. keys with spaces), but user needs to use a bracket notation(map.['illegal key']). It looks this notation doesn't work with such keys.

[1] https://quarkus.io/guides/qute-reference#maps

### Expected behavior

Qute should be able to handle any valid java String as a key

### Actual behavior

Qute fails with error `#1 Parser error in template [basic.html] line 3: invalid identifier found`

### How to Reproduce?

Steps:
1. Clone the reproducer: https://github.com/fedinskiy/reproducer/tree/reproducer/qute-maps
2. Run in dev mode
3. See logs or access http://localhost:8080/test

Used template:
`The capital of Tasmania is {map.Tasmania}, {map.['Germany']} is a capital of Germany and {map.['The Great Britain']} is a capital of the UK.`
Corresponding map:
```
  Map<String, String> map = new HashMap<>();
        map.put("Tasmania", "Hobart");
        map.put("The Great Britain", "London");
        map.put("Germany", "Berlin");
```

### Output of `uname -a` or `ver`

5.19.4-200.fc36.x86_64

### Output of `java -version`

11.0.16 temurin

### Quarkus version or git rev

2.12.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by mkouba** [comment]
> but user needs to use a bracket notation(map.['illegal key'])

But the bracket notation is `map['illegal key']`, i.e. the dot is not used at all. It's similar to the [bracket notation in javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors#bracket_notation).

**Comment by fedinskiy** [comment]
@mkouba if so, why `{map.['Germany']}` works?

**Comment by mkouba** [comment]
> if so, the why {map.['Germany']} works?

I think that it does not work but it does not result in a parser error because `['Germany']` is not an invalid identifier as defined in [Identifiers and Tags](https://quarkus.io/guides/qute-reference#identifiers).

**Comment by fedinskiy** [comment]
> I think that it does not work but it does not result in a parser error because `['Germany']` is not an invalid identifier as defined in [Identifiers and Tags](https://quarkus.io/guides/qute-reference#identifiers).

I updated[1] the reproducer, run it in dev mode see it for yourself.

[1] https://github.com/fedinskiy/reproducer/commit/8004d67821bee6453890e4bbb1b84e745fa79049

**Comment by fedinskiy** [comment]
And `map['The Great Britain']` doesn't work either. @mkouba the issue should be reopened.
Also, we need to find, why `map.['key']` works. Do you want a separate issue created for that?

**Comment by mkouba** [comment]
> I updated[1] the reproducer, run it in dev mode and see it for yourself.

Yes, you're right and it works. I don't remember the details but it seems that we wanted to be more lenient and just ignore adjacent separators, e.g. `name[['value']` and `name.['value']`.

> And map['The Great Britain'] doesn't work either.

This is really a bug and I think that we should create a separate issue for that.

**Comment by mkouba** [comment]
FYI I've created https://github.com/quarkusio/quarkus/pull/28051.

Thanks for noticing this bug!
