### ISSUE TITLE
Various Provider related problems in MP REST Client TCK

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2801]
**Describe the bug**
Some MP REST Client TCK tests (like `org.eclipse.microprofile.rest.client.tck.InvokeWithBuiltProvidersTest`) are failing with the result being different than expected.

These tests are currently being [skipped](https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L111).

**Comment by kenfinnigan** [comment]
Resolved as part of #4520
