### ISSUE TITLE
Caffeine cache with native image

### ISSUE THREAD

**Issue by Borisca** [quarkusio/quarkus#28012]
### Describe the bug

When you use caffeine cache and you add the property 'expire-after-access' or 'expire-after-write', it works as it should on jdk but in native image, the properties are ignored.

### Expected behavior

Properties should not be ignored

### How to Reproduce?

- Define a cache in the propeties file like this : 
  quarkus.cache.caffeine."cache-name".initial-capacity=15000
  quarkus.cache.caffeine."cache-name".maximum-size=15000
  quarkus.cache.caffeine."cache-name".expire-after-access=10S
- Inject the cache in a service : 
    @CacheName("cache-name")
    Cache cache;
- Write a method like this : `    boolean isInCache(String key){
        AtomicBoolean atomicBoolean = new AtomicBoolean(true);
        cache.get(key, k -> {
            atomicBoolean.set(false);
            return new Object();
        }).await().indefinitely();
        return atomicBoolean.get();
    }`
- Call the method with API or by consuming a kafka topic. 
- Wait 10s so the cache is supposedly evicted.

### Output of `java -version`

openjdk 11.0.12 2021-07-20

### GraalVM version (if different from Java)

.0.12+6OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2..7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by gwenneg** [comment]
Thanks for reporting this @Borisca. I'll take a look shortly.

**Comment by gwenneg** [comment]
A quick test with Quarkus 2.12.2.Final and `quarkus.cache.caffeine."cache-name".expire-after-access` shows no issue on my machine. The data is correctly expired if it is not accessed for at least the duration provided in the configuration.

@Borisca Did you try this with a Quarkus version newer than 2.7.2?

I'll check again later.

**Comment by Borisca** [comment]
@gwenneg Thank you for the fast reply. I only tried with the 2.7.2 version of quarkus and building the native with graalvm 21.2 . I will upgrade my graalvm to 22.2 and quarkus version 2.12.2. I will let you know if the bug is still there

**Comment by Borisca** [comment]
So i just tried with graalvm 22.2 and quarkus version 2.12.2 and i have the same issue. In JDK in works fine but with native image it doesnt evict the cache after the time is up.

**Comment by Borisca** [comment]
I think I know where the issue is. It seems that in native, it doesnt take into account the override of the property expire-after-access that I set for the profile dev. It takes instead the property that is set in the default profile. I let you know if I find more about it.

**Comment by Borisca** [comment]
@gwenneg  Okay. I found the problem. The thing is that when i build the native image, I did not specify any profile. I thought you could choose the profile when you run the app so it picks the right properties. It seems that even though I specify the dev profile, it uses the prod properties. Does that mean that I need 1 native image per environment?

**Comment by gwenneg** [comment]
Did you specify the profile with a command like `./my-app-1.0-runner -Dquarkus.profile=dev`?

**Comment by Borisca** [comment]
Yes I did. But I just read again the doc on caffeine cache with quarkus and all the fields are displayed with the padlock on the left side.
I never noticed it before but that explains pretty well my problem:
With lock : 'Configuration property fixed at build time - All other configuration properties are overridable at runtime'

**Comment by gwenneg** [comment]
Good catch! Sorry, I should have thought about this 😄 `quarkus-cache` config values are indeed fixed at build time.
