### ISSUE TITLE
Wrong type detection in hibernate-reactive on postgres bigint PK

### ISSUE THREAD

**Issue by rsc1975** [quarkusio/quarkus#28027]
### Describe the bug

Versions:

Quarkus: 2.12.1.Final
Postrgres: 14.5-1.pgdg110+1

I'm getting the following error: 
```java.lang.IllegalArgumentException: Provided id of the wrong type for class tech.laude.h3lp3r.domain.Person. Expected: class java.lang.Long, got class java.lang.Integer ```

I've tried generating the table from Quarkus and manually, same result.

Entity code:
```java
@Entity
public class Person extends PanacheEntity {
    public String name;
 }
```
Using `PanacheEntityBase` with manual `id` definition shows same problem.

Generated table in postgres:

```
# \d person
                      Table "public.person"
 Column |          Type          | Collation | Nullable | Default
--------+------------------------+-----------+----------+---------
 id     | bigint                 |           | not null |
 name   | character varying(255) |           |          |
Indexes:
    "person_pkey" PRIMARY KEY, btree (id)
```

My endpoint:
```java
    @GET
    @Path("/test")
    @Produces(MediaType.APPLICATION_JSON)
    public Person test() {
        return Person.findById(1);
    }
```

### Expected behavior

No error

### Actual behavior

An exception is raised:

```
Caused by: org.hibernate.TypeMismatchException: Provided id of the wrong type for class acme.domain.Person. Expected: class java.lang.Long, got class java.lang.Integer
        at org.hibernate.event.internal.DefaultLoadEventListener.checkIdClass(DefaultLoadEventListener.java:155)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:71)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1220)
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:202)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2835)
```

### How to Reproduce?

Reproduce:

1. Configure a postgresql instance with docker
```
docker run --name db1 --rm -p 5432:5432 -e POSTGRES_DB=db1 -e POSTGRES_USER=sarah -e POSTGRES_PASSWORD=connor -d postgres:14
```
2. Configure application.properties to connect to the db
```
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = sarah
quarkus.datasource.password = connor
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/db1
quarkus.hibernate-orm.database.generation = drop-and-create
```
3. Create an entity Person like the described previously
4. Create a Resource like:
```java
@Path("/")
public class PersonResource {
    @GET
    @Path("/test")
    @Produces(MediaType.APPLICATION_JSON)
    public Person test() {
        return Person.findById(1);
    }
}
```
5. `./mvnw compile`
6. `quarkus dev`
7. Create a record in the table: `insert into person (id, name) values (1, 'Rob');`
8. Call the service with curl or whatever toool:
```sh
curl localhost:8080/test
```

### Output of `uname -a` or `ver`

`Linux ThinkPad-Rob 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 GNU/Linux`

### Output of `java -version`

```openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment (build 17.0.4+8-Debian-1) OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1, mixed mode, sharing)```

### Quarkus version or git rev

2.12.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`quarkus dev`

**Comment by gavinking** [comment]
And ... what happens if you use `findById(1L)`?

**Comment by rsc1975** [comment]
It works !!!
```java
return Person.findById(1L);
```

Is this the expected behavior ?

**Comment by gavinking** [comment]
Yes, it's correct, a `bigint` can't be represented using a java `int`.

And yeah, the lack of type safety is unfortunate, it's basically a downside if the Active Record pattern compared to DAOs.

**Comment by rsc1975** [comment]
A postgres `bigint` is a 8-byte numeric type, java `int` is a 4-byte type length. IMO, Bigint column should be resolved to Long... 

Am I wrong?

https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by rsc1975** [comment]
Ok, understood, I like the resulting code using Active Record, IMO, It's a bit more intuitive, but not using safe types is something I have to get used to. 

I close the issue. Thanks for your help.
