### ISSUE TITLE
Kubernetes (ap4k) Guide missing deployment documentation

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#2802]
**Describe the bug**
The last sentence of the [Kubernetes (ap4k) guide](https://quarkus.io/guides/ap4k) is "The next section will walk you through how this can be done." That is the last sentence in the guide. There are no steps that explain how to apply the generated kubernetes.[yaml|json] file.

**Expected behavior**
Include steps to apply the kubernetes resource files

**Comment by geoand** [comment]
Ah yes, this was left over from the previous implementation that did a whole lot more. Currently that can't be done, but I have opened an ap4k [issue](https://github.com/ap4k/ap4k/issues/227)  to track that.
For the time being I will just remove the sentence.
