### ISSUE TITLE
Allow multiple realms to be configured with quarkus.keycloak.devservices.realm-path (multi-tenancy)

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#28031]
### Description

For the keycloak devservice, it is possible to define the property `quarkus.keycloak.devservices.realm-path` with a realm.json which initializes the dev service.

This works great if you only need one realm. File content -> `{ ... }`

It does not work, when more than one realm are needed.
It would be great if one could define an array of realms inside the realm.json of which all are getting initialized. File content -> ```[
{ ... }, 
{ ... }
]```
Currently, a file like this simply gets ignored.

**Comment by sberyozkin** [comment]
@HerrDerb, it can be simpler to support multiple files, and then upload each file in turn as opposed to parsing this JSON document. 
However, what is your use case ? A single OIDC tenant has a client id/secret specific to a given realm. So not sure having more than 1 realm uploaded really helps - or do you have a multi-tenancy support in mind ?

**Comment by HerrDerb** [comment]
@sberyozkin , yes I'm building a multi-tenancy system. I forgott to mention this. That why I would like to be able to initialize a keycloak devservice with more then one realm.

**Comment by sberyozkin** [comment]
It will require a significant effort as importing multiple realms will not in itself affect a DevUI experience. Worth thinking though how it all can be managed

**Comment by sberyozkin** [comment]
@HerrDerb  I've been thinking about it, I believe we can let users select a realm they would like to login to at the OIDC Dev UI login page if more than one realm is available - I'll have a look

**Comment by HerrDerb** [comment]
@sberyozkin That be cool 👍Thanks
