### ISSUE TITLE
Redis-client should upgrade vertx-redis-client next version

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#28042]
### Description

Ref [https://github.com/vert-x3/vertx-redis-client/issues/348](https://github.com/vert-x3/vertx-redis-client/issues/348)
Quarkus connect Redis server failed when specific "username"

```txt
quarkus.redis.hosts=redis://[username:password@][host][:port][/database]
```

Startup failed log

```sh
[io.quarkus.runtime.ApplicationLifecycleManager:195,run()] Failed to start application (with profile dev): WRONGPASS invalid username-password pair
```

**Comment by cescoffier** [comment]
Vert.x update is scheduled already - waiting for the release.

**Comment by geoand** [comment]
Let's close this as we already have a process in place for doing Vert.x releases and we do them as soon as everything is in place
