### ISSUE TITLE
gRPC ServerInterceptor throwing exceptions are not catched

### ISSUE THREAD

**Issue by slinkydeveloper** [quarkusio/quarkus#28053]
### Describe the bug

Hi all, I'm trying to use an interceptor coming from an external package, which throws an exception when executing `interceptCall`. When this happens, quarkus will print the exception as uncaught but won't reply back.

Looking at the docs of [`ServerInterceptor`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptor.html#interceptCall-io.grpc.ServerCall-io.grpc.Metadata-io.grpc.ServerCallHandler-), throwing an exception there looks like a valid implementation:

> If the implementation throws an exception, call will be closed with an error.

### Expected behavior

Response back with error grpc status code `INTERNAL` and some status message indicating the failure (or maybe just "Internal server error")

### Actual behavior

No response back

### How to Reproduce?

1. Create an interceptor throwing an exception
2. Try to send a request using grpcurl, e.g. `grpcurl -vv -plaintext -d '{"name":"Francesco"}' localhost:9000 hello.HelloGrpc/SayHello`

See the reproducer attached

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9598156/reproducer.zip)

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12

### Quarkus version or git rev

2.12.2.Final

**Comment by alesj** [comment]
New Vert.x gRPC impl already responds with 500:
* https://gist.github.com/alesj/98dd7b39cff1a65ae36abcbc9e94d266

@cescoffier I guess this could be fixed as part of current work?
(but I would probably need some hint on where / how to fix it)

**Comment by alesj** [comment]
Currently you get this (on my WIP branch ...):
* https://gist.github.com/alesj/5917a9d39512107b362f060aa19bcf1d

**Comment by alesj** [comment]
This could work ...
* https://gist.github.com/alesj/2d57b75096bc3df28838889244028b8b

**Comment by cescoffier** [comment]
@alesj we may want to fix in the current server too (if it does not require breaking something), as I would qualify this as a bug (and thanks for the report @slinkydeveloper !)

**Comment by cescoffier** [comment]
The question is does the current server let us catch these exceptions?

**Comment by alesj** [comment]
> The question is does the current server let us catch these exceptions?

See VertxCoreRecorder ...

```
        vertx.exceptionHandler(new Handler<Throwable>() {
            @Override
            public void handle(Throwable error) {
                LOGGER.error("Uncaught exception received by Vert.x", error);
            }
        });
```

**Comment by alesj** [comment]
And it looks like we would have to have 2 diff solutions / fixes:
* https://gist.github.com/alesj/18ef28dc319a2df5b490a7e5fd57f6fa

Unless we leave the new gRPC with already provided 500 ...

**Comment by cescoffier** [comment]
@alesj  the Vert.x exceptionHandler is not going to be able to close the gRPC connection. I'm actually surprised that grpc-java does not handle that automatically.

**Comment by cescoffier** [comment]
Yes, it does not do anything, so it bubbles up.

**Comment by slinkydeveloper** [comment]
> I'm actually surprised that grpc-java does not handle that automatically.

The regular grpc server handles this case AFAIK

**Comment by cescoffier** [comment]
ah yes, in `runInternal`. So, why does our server not doing this? Might be a gap in Vert.x

**Comment by alesj** [comment]
```
          try {
            listener = startWrappedCall(methodName, Futures.getDone(future), headers);
          } catch (Throwable ex) {
            stream.close(Status.fromThrowable(ex), new Metadata());
            context.cancel(null);
            throw new IllegalStateException(ex);
```

The question is why there is no response ... 
Where I guess Vert.x exceptionHandler catches this ISE.

**Comment by cescoffier** [comment]
Ok, I may be on something...

**Comment by cescoffier** [comment]
So... it was my fault. Opened https://github.com/quarkusio/quarkus/pull/28063.
