### ISSUE TITLE
Quarkus Test: Initialize REST Assured before `@BeforeAll` methods get called

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#28066]
### Description

It would be nice if `@BeforeAll` annotated methods would be able to call REST endpoints of the Quarkus application under test using REST Assured just like in `@Test` annotated methods. This currently works but paths have to be specified differently, because the Quarkus test framework hasn't yet initialized REST Assured at this point (this is currently being done in `io.quarkus.test.junit.QuarkusTestExtension#beforeEach()`.

**Comment by geoand** [comment]
What's the use case for this?

**Comment by knutwannheden** [comment]
The use case is to set up a test fixture for all tests. Of course this can also be done differently, but it wasn't straight-forward to understand what is going on, since the Quarkus application had been started already.

**Comment by geoand** [comment]
My point is that in a `@QuarkusTest` you have access to the application itself (it's **NOT** a blackbox), so doing something like seems like overkill

**Comment by knutwannheden** [comment]
Using the REST API could also be more convenient. I just found it a bit odd when I stumbled across this and thought I should report it. If you think it doesn't really make sense, then feel free to close the issue again. Possibly a note in the documentation would make sense.

**Comment by geoand** [comment]
I'll leave it open in case others want to chine in

**Comment by geoand** [comment]
Let's close this as won't fix
