### ISSUE TITLE
Serializer for class 'ArrayList' is not found.

### ISSUE THREAD

**Issue by pwlan** [quarkusio/quarkus#28096]
**Describe the bug**

Hi,
thanks for the fix of https://github.com/quarkusio/quarkus/issues/23678

But it looks like this has introduced a new issue.
When using Lists, the following error ocurrs.
 
```
Serializer for class 'ArrayList' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

The issue can be easily reproduced:
```
fun main() {
    val arrayList = ArrayList<String>()
    Json{}.encodeToString(serializer(arrayList.javaClass), arrayList) // this will fail.
}
```

or 
```
    @Path("list")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun listHello() = listOf(Person("Jim Halpert"))
```

In the case of a list, the Kotlin ListSerializer needs to be used. The same applies to Sets.

**Quarkus Version**

Quarkus 2.12.2

**Expected behavior**

It should produce beautiful json.

_Originally posted by @pwlan in https://github.com/quarkusio/quarkus/issues/23678#issuecomment-1065332302_

**Comment by gsmet** [comment]
Can you provide a small reproducer?

**Comment by geoand** [comment]
As Guillaume mentions, a reproducer is essential here.

**Comment by pwlan** [comment]
Thanks for the super fast response!

Interesting... we get it every time in our app... but are having trouble reproducing it with a fresh hello world... this might take a moment.

Otherwise, in the case of Lists, is https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-kotlin-serialization/runtime/src/main/kotlin/io/quarkus/kotlin/serialization/KotlinSerializationMessageBodyWriter.kt still used to serialize the data?

**Comment by geoand** [comment]
Yeah, that should be coming into play

**Comment by pwlan** [comment]
Ok, we are 1 step closer. It all comes down to the KotlinSerializationMessageBodyWriter.kt.

On the Reproducer App, `KotlinSerializationMessageBodyWriter#writeRsponse` is callled and that works.
On our App, `KotlinSerializationMessageBodyWriter#writeTo` is called and that failes. 
The line is 29, `json.encodeToStream(serializer(o.javaClass) , o, entityStream)`. If `o` is, for example, HashArray it will fail.

So 2 questions:
 1. Any info on how to control what method is called? 
 2. Should  `KotlinSerializationMessageBodyWriter#writeTo` work if o is an Array?

**Comment by geoand** [comment]
Would you be able to try out https://github.com/quarkusio/quarkus/pull/28134 (see [this](https://github.com/quarkusio/quarkus/pull/28134) for how to build the project)

**Comment by geoand** [comment]
Seems like some of the tests are failing, so there is more I need to look into

**Comment by pwlan** [comment]
Ok, found the culprit.

When adding "io.quarkus:quarkus-smallrye-opentracing" as a dependency `KotlinSerializationMessageBodyWriter#writeTo` is called, whichs fails.

I can create a reproducer later....

**Comment by geoand** [comment]
@pwlan any change you have a reproducer? It would really help in narrowing down what is going on here.

**Comment by pwlan** [comment]
Of course
[quarkus-issue.zip](https://github.com/quarkusio/quarkus/files/9714195/quarkus-issue.zip)

Just run the tests.

**Comment by geoand** [comment]
Great, thanks!
