### ISSUE TITLE
A way to inject dependencies when the class is instantiated with new operator or Utils.newInstance

### ISSUE THREAD

**Issue by GauriBhat22** [quarkusio/quarkus#28100]
### Description

I am trying to implement a custom login module for Kafka which implements javax.security.auth.spi.LoginModule. 
Lets name the custom login module - KafkaLoginModule.  I need to fetch the username, password from HashiCorp and then use the credentials in KafkaLoginModule to connect to Kafka. 

KafkaLoginModule has some dependencies which need to be injected. But injection does not work as the class is instantiated during runtime using Utils.newInstance within the quarkus-kafka-client jar.

The below code instantiates KafkaLoginModule and is present in the class Target_org_apache_kafka_common_security_authenticator_SaslClientCallbackHandler  in quarkus-kafka-client jar.  

**LoginModule result = Utils.newInstance(entry.getLoginModuleName(), LoginModule.class);**

Due to this, I cannot inject the RestClient which needs to connect to HashiCorp.  

Is there anyway to inject dependencies into a class which is not a managed bean?

**Comment by GavinRay97** [comment]
If I understand you, you're asking for how to get instances of CDI managed beans if the class that is using them is manually constructed with `new MyClass()`?

To do this, you can programmatically access the CDI container and ask it for the things you want:

```java
MyClass foo = CDI.current().select(MyClass.class).get();
```

**Comment by GauriBhat22** [comment]
This worked. Thanks a lot !

Can this be included in the documentation?  I looked for a way to do this in the documentation and did not find anything which solved the issue.

**Comment by geoand** [comment]
This has been discussed in past IIRC and it's something we likely do not want to do as there are too many corner cases to cover. 

@mkouba @manovotn @Ladicek anything you want to add, or should we close this?

**Comment by Ladicek** [comment]
Programmatic lookup using `CDI.current()` (or `Arc.container()`) is the way to go here, in my opinion.

There are APIs in CDI for more fine-grained handling of these situations (`InjectionTarget`, `Unmanaged` etc.), but those are not (and will not be) supported in ArC.

**Comment by mkouba** [comment]
> Programmatic lookup using CDI.current() (or Arc.container()) is the way to go here, in my opinion.

That said, you can't inject an unmanaged instance (e.g. `new Foo()`) unless you perform the injection manually, i.e. iterate over all injection points, do programmatic lookup and set the values.
