### ISSUE TITLE
Unresolveable build extension io.quarkus.platform:quarkus-maven-plugin:2.12.3.Final

### ISSUE THREAD

**Issue by stephaneoverlen** [quarkusio/quarkus#28113]
### Describe the bug

Hi,

This quick message to tell you that I went to [quarkus.io](https://code.quarkus.io/), selected RestEasy Reactive Jackson, downloaded the zip, extracted it, nothing more.
Then "mvn clean package" and the message appears :
_[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin io.quarkus.platform:quarkus-maven-plugin:2.12.3.Final or one of its dependencies could not be resolved: Failed to collect dependencies at io.quarkus.platform:quarkus-maven-plugin:jar:2.12.3.Final -> io.quarkus:quarkus-core-deployment:jar:2.12.3.Final @_ 
I never had the problem before (and still have many things to learn).
Tried to downgrade to 2.12.2.Final and it works.
(openjdk-11.0.4.11-1 ; Maven 3.8.6 ; IntelliJ Ultimate 2020.2)

Regards,
Stephane

### Expected behavior

mvn clean package -> BUILD SUCCESS

### Actual behavior

mvn clean package -> [ERROR] Unresolveable build extension: Plugin io.quarkus.platform:quarkus-maven-plugin:2.12.3.Final or one of its dependencies could not be resolved: Failed to collect dependencies at io.quarkus.platform:quarkus-maven-plugin:jar:2.12.3.Final -> io.quarkus:quarkus-core-deployment:jar:2.12.3.Final @

### How to Reproduce?

Go to[ quarkus.io](https://code.quarkus.io/), select RestEasy Reactive Jackson, download the zip, extract it.
Then "mvn clean package"

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-18362 LAPTOP 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.4" 2019-07-16 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

### Quarkus version or git rev

2.12.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0 Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: mypath\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: C:\Progs\Java\openjdk-11.0.4.11-1 Default locale: fr_CH, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
This worked for me so I am assuming something went wrong when Maven downloaded the dependencies. 
I propose clearing your `.m2/repository` directory from the problematic dependencies and trying again

**Comment by stephaneoverlen** [comment]
It worked, thank you for your help.
I assumed there was some kind of problem with the new version.
