### ISSUE TITLE
Revisit the non-standard behavior of ArcContainer#instanceSupplier()

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#28115]
### Description

Namely this part: https://github.com/quarkusio/quarkus/blob/2.13/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L266-L276

Note that a change would break the compatibility because some extensions rely on this behavior (e.g. undertow).

**Comment by mkouba** [comment]
> The method doesn't use any reference to standard CDI API and has proper documentation it terms of what it does.

Well, it does not behave as other `instance()` and lookup methods in general. That "filtering" got added later for one particular use case and I believe that an idiomatic solution would be to use the restricted bean types, i.e. `@Typed`.

> but at that point the only added value over using standard API is returning a supplier wrapper, right?

Yes, and that was the only original added value leveraged in `io.quarkus.arc.runtime.BeanContainer.instanceFactory()` and recorders.

**Comment by manovotn** [comment]
> Well, it does not behave as other instance() and lookup methods in general. That "filtering" got added later for one particular use case and I believe that an idiomatic solution would be to use the restricted bean types, i.e. @Typed.

I see, originally I thought that the type "filtering" was the initial reason for this method.
Ok, I can take a look at what would it take to transfer this to standard behavior.

**Comment by mkouba** [comment]
> Ok, I can take a look at what would it take to transfer this to standard behavior.

It should be fairly straightforward to modify the undertow extension but this change could break existing extensions from quarkiverse etc. Also we can't deprecate the method (because we want to keep the original functionality) which makes it more difficult.
