### ISSUE TITLE
Reduce reliance on `-H:` options

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#28148]
Reduce reliance on `-H:` options when invoking `native-image`.

`-H:` options are not public API. During a native image meeting @christianwimmer said some of those should become API (e.g. `--blah` option) and others might no longer be used.

This work has been split out from https://github.com/quarkusio/quarkus/issues/25943.

**Comment by zakkak** [comment]
Closing as duplicate of https://github.com/quarkusio/quarkus/issues/27784 (I linked the Epic to it as well)
