### ISSUE TITLE
quarkus-hibernate-orm entity manager merge of detached entity does not work

### ISSUE THREAD

**Issue by waldimiro** [quarkusio/quarkus#2815]
With quarkus-hibernate-orm extension, entityManager.merge(entity) for a detached entity in a transactional method does not work. Entity will not be updated.

**Comment by gsmet** [comment]
@waldimiro could you create a reproducer?

**Comment by waldimiro** [comment]
@gsmet I have a simple multi module scenario where:

**module-1**
Contains my JPA model (Entities)

**module-2**
Imports _module-1_
Exposes a REST endpoint that consumes a JSON
A service class serialize the JSON in a _module-1_ entity
A transactional method of service class try to merge the entity

**Comment by gsmet** [comment]
@waldimiro a simple reproducer would help. It shouldn't take you too much time.

**Comment by gsmet** [comment]
We had several reports of this. We should try to investigate.

**Comment by gsmet** [comment]
This might be related to this issue: https://github.com/quarkusio/quarkus/issues/3127 .

**Comment by Sanne** [comment]
@dreab8 could you add a test for this?

**Comment by dreab8** [comment]
Hi @waldimiro,
 I created a project https://github.com/dreab8/qurkus-merge-detached that tries to replicate the issue you described but without any luck, can you please give a look at it and tell me if I am missing anything?  thanks a lot

**Comment by waldimiro** [comment]
Hi @dreab8 

Thank you for your time. The differences are:

model module
1. there are no application.properties, persistence properties are declared in service.
2. All my entities inherits from AbstractEntity<Object> (with an abstract getId, setId) 

service moule
1. application.properties contains persistence properties (quarkus.hibernate-orm.database.generation=none)
2. TestEntityService inherits from AbstractRepository where is injected the EntityManager.
3. TestEntityService has at class level the @Transactional annotation.
4. TestEntityService has at class level another interceptor @Lock(LockType.READ) (the concurrency solution that you can find here https://www.knitelius.com/2016/01/25/concurrency-control-for-cdi/)
5. MergedEntityResource is @RequestScoped

**Comment by waldimiro** [comment]
mhh I ask me if it is related to https://github.com/quarkusio/quarkus/issues/2918, please read my last comment.

**Comment by gsmet** [comment]
@waldimiro I don't think we will be able to make progress on this this way.

Could you create a simple reproducer so that we can clearly see what's going wrong. It shouldn't be too hard and it would help us a lot.

Thanks.

**Comment by gsmet** [comment]
Please open another issue with a full reproducer if you end up having one.

**Comment by Sanne** [comment]
Reopening, we crafted a reproducer in ORM.

**Comment by rsvoboda** [comment]
@Sanne any update on this ?

**Comment by Sanne** [comment]
It's very complex but at last week's meeting we brainstormed this. I think I know now what we should do, but will need the time to explore further.

Described as:
 - https://hibernate.atlassian.net/browse/HHH-13826

**Comment by EfraimLA** [comment]
So there's not other way to merge entire entity collections?

**Comment by guoxunbo** [comment]
any update related to this merge issue? We're facing the same issue？

**Comment by yrodiere** [comment]
FWIW this seems to relate to https://hibernate.atlassian.net/browse/HHH-17761, which was fixed in Hibernate ORM 6.5 and thus should be fixed when we upgrade to that version in Quarkus (PR incoming).
