### ISSUE TITLE
Fatal:error parsing buffer at index 16/ 0*10

### ISSUE THREAD

**Issue by pavhittal** [quarkusio/quarkus#28158]
I am using vertex-db2-client v4.3.3 and spring boot v2.6.6 to connect to DB2 and it is not working. I see following error 
[io.ver.db2.imp.cod.DB2Decoder] (vert.x-eventloop-thread-14) FATAL: Error parsing buffer at index 16/ 0x10
+-------------------------------------------------+
| 0 1 2 3 4 5 6 7 8 9 a b c d e f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 90 d0 [43 00 01 00](tel:43 00 01 00) 8a [14 43 00 44 11](tel:14 43 00 44 11) 5e 84 82 |...C.....C.D.^..|
|00000010| f2 [82 86 97 84](tel:82 86 97 84) a3 84 82 f2 [81 87 85 95](tel:81 87 85 95) a3 f0 f1 |................|
Java.Lang.illegalstateException:found unexpected codepoint:4435
At io.vertex.db2cient.impl.dead.DRDAConnectResponse.parseSECCHKRM(DRDAConnectResponse.Java:1133)~[vertx-db2-client-4.3.3.jar:4.3.3]

My code looks like below
DB2ConnectOptions connectOptions = new DB2ConnectOptions()
  .setPort(50000)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUser("user")
  .setPassword("secret");

// Pool options
PoolOptions poolOptions = new PoolOptions()
  .setMaxSize(5);

// Create the client pool
DB2Pool client = DB2Pool.pool(connectOptions, poolOptions);

// A simple query
client
  .query("SELECT * FROM users WHERE id='julien'")
  .execute(ar -> {
  if (ar.succeeded()) {
    RowSet<Row> result = ar.result();
    System.out.println("Got " + result.size() + " rows ");
  } else {
    System.out.println("Failure: " + ar.cause().getMessage());
  }

  // Now close the pool
  client.close();
});

I see the DB2pool is created however while executing the query exception is thrown.

**Comment by tsegismont** [comment]
@pavhittal  how is this related to Quarkus? It seems you use the Db2 client in Spring Boot. In this case, please report this to the Reactive DB2 Client repo.

**Comment by tsegismont** [comment]
Which issue?

**Comment by pavhittal** [comment]
Please refer this
https://github.com/quarkusio/quarkus/issues/11035#issuecomment-699018724
