### ISSUE TITLE
hibernate validator manual validation, usage with kogito bpmn

### ISSUE THREAD

**Issue by Mert18** [quarkusio/quarkus#28151]
### Describe the bug

Hi, I want to do manual validation and return my custom exception on my POJO classes but when importing models into bpmn files, my function does not even work and hibernate validator returns its json error (it validates before my function works).

This is my POJO class with validations added from *javax.validation.constraints*
```
public class UserRegister {

  @NotBlank(message = "Username is required")
  @Size(min = 2, max = 20, message = "Username must be between 2 and 20 characters")
  @Pattern(regexp = "^[a-zA-Z0-9]+$", message = "Username must be alphanumeric with no spaces")
  private String username;

  @NotBlank(message = "First name is required")
  @Size(min = 2, max = 32, message = "First name must be between 2 and 32 characters")
  private String firstName;

  @NotBlank(message = "Last name is required")
  @Size(min = 2, max = 32, message = "Last name must be between 2 and 32 characters")
  private String lastName;

  @NotBlank(message = "Email is required")
  @Email(message = "Email must be valid")
  private String email;

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }
```

imported my UserRegister model here.
![Screenshot from 2022-09-22 15-17-26](https://user-images.githubusercontent.com/40024436/191744547-457db856-2186-427c-ad52-0a25c8a4ca97.png)

kogito calls this function
![Screenshot from 2022-09-22 15-18-22](https://user-images.githubusercontent.com/40024436/191744722-d9f897a5-9db5-412b-800d-9feaf5b42da7.png)

And the function, notice that my function does not even entered, i do not see the system out println on my console.
```
  public void validateUserRegister(UserRegister userRegister) throws MyApplicationException {
        System.out.println("Does not see this.");
        Set<ConstraintViolation<UserRegister>> violations = validator.validate(userRegister);
        if (!violations.isEmpty()) {
            throw new MyApplicationException("My exception: " + violations.iterator().next().getMessage());
        }
    }

```

Then I send a json that is not valid,
I was expecting to get my exception thrown, but this is the result from hibernate:
```
{
    "exception": null,
    "propertyViolations": [],
    "classViolations": [],
    "parameterViolations": [
        {
            "constraintType": "PARAMETER",
            "path": "createResource_reguser.resource.userRegister.email",
            "message": "Email must be valid",
            "value": "fgsdgsdggmail.com"
        }
    ],
    "returnValueViolations": []
}
```

There is no @Valid annotation in my code so I was expecting to get my exception. What do I do wrong?
Is there any other method disabling automatic validaton? Maybe this will solve my issue.

### Expected behavior

Getting my exception instead of hibernate validator's json.

### Actual behavior

returns hibernate validator message

### How to Reproduce?

I explained this at first step.

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.6

**Comment by gsmet** [comment]
Hard to know what's going on without a simple reproducer.

**Comment by geoand** [comment]
Closing as we never got a reproducer.

Feel free to comment / reopen if one becomes available.
