### ISSUE TITLE
Variable replacement does not work for quarkus-smallrye-rest-client /mp-rest/url

### ISSUE THREAD

**Issue by waldimiro** [quarkusio/quarkus#2816]
Variable replacement does not work for quarkus-smallrye-rest-client /mp-rest/url

```
my.endpoint=http://xxxxxx.xx
foo.bar.MyEndpoint/mp-rest/url=${my.endpoint}
```

${my.endpoint} is not resolved.

**Comment by geoand** [comment]
Are you sure about this? I just tried it and it worked on Quarkus 0.16.1.

**Comment by waldimiro** [comment]
@geoand can be related to a multi module scenario?

My case:

**module-1** that exposes REST Endpoint and logic
**module-2** contains the REST Client interface (related to _module-1_)
**module-3** imports _module-2_ and declares in application.properties module-2 classes /mp-rest/url properties

**Comment by geoand** [comment]
Would it be possible for you to supply a small reproducer?

**Comment by waldimiro** [comment]
Unfortunately I don't have much time right now. But I think the case is very simple to reproduce.

**Comment by geoand** [comment]
Sure, I just want to make sure we are doing the same thing. But I'll give it a show later on

**Comment by waldimiro** [comment]
Thank you so much for what you are doing! Quarkus is formidable!

**Comment by geoand** [comment]
So I tried a simplified version of the multi-module set and still couldn't reproduce the problem. Since there are a few moving parts that could affect the outcome, I would very much appreciate it if you could supply a simple reproducer of the problem.

**Comment by dmlloyd** [comment]
This could be the same issue as #4077.
