### ISSUE TITLE
Swagger UI stopped working in Dev Services for Keycloak

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#28178]
### Describe the bug

It is possible to use Swagger UI to test the endpoint with the token acquired using the code flow via a Dev UI for Keycloak,  if `quarkus-smallrye-openapi` dependency is present then a user select a `Swagger UI` link and start testing the endpoints using this token, bypassing the `Authorize` options offered by Swagger UI:

https://quarkus.io/guides/security-openid-connect-dev-services#test-with-swagger-ui-or-graphql-ui

Unfortunately it no longer works on `main` at least, `Swagger UI` is ignoring the access token acquired via Dev UI and tries basic authentication requests.

@phillip-kruger Can you please have a quick look (ex, with `quarkus-quickstarts/security-openid-connect-quickstart`) ?
I'm not sure what happened, I could see it working yesterday, and a couple of times today, but now it just keep trying to send basic auth credentials, despite the fact the access token acquired via Dev UI is available - it can be used when testing manually from the `provider.html`.

One thing I recall, that after getting into Swagger UI, I pressed its `Authorize` option by mistake but then clicked there a few times, and I wonder if some local storage is involved, as even after restarting the browser, the problem persists

Have a look please, thanks

**Comment by phillip-kruger** [comment]
@sberyozkin this work for me. Maybe clear your local storage ? Let me know ?

**Comment by sberyozkin** [comment]
Hey @phillip-kruger Thanks for checking, indeed looks like it was a false alarm, I cleared some storage in `Firefox/Web Developer Tools/Storage` and it is working now again :-).

What do you think about hiding the `Authorize` Swagger UI option in this case ? It is very tempting to press it and once it is pressed several options are offered which are not related, since we have a token ready.

**Comment by phillip-kruger** [comment]
I am not sure if it is possible

**Comment by sberyozkin** [comment]
@phillip-kruger You've made impossible work before by getting Swagger UI accept a token out of band from DevUI :-). How does Swagger UI decide it needs to show `Authorize` ? I guess it is because `quarkus-oidc` is producing the build items recognized by `quarkus-smallrye-openapi` so may be `KeycloakDevServicesProcessor` can somehow cancel them, even indirectly with the build item of its own...
