### ISSUE TITLE
Dev services for Kubernetes client

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#28189]
### Description

Kubernetes mock server has some limitations and currently a developper needs to run a k8s cluster by itself (k3s, minikube, etc...) to run against a real one.

[Testcontainers](https://www.testcontainers.org/modules/k3s/) and https://github.com/dajudge/kindcontainer provide test containers implementations for api server or full featured k8s cluster.

### Implementation ideas

I'm was doing a PR (https://github.com/quarkiverse/quarkus-operator-sdk/pull/413) for quarkus operator SDK to add support for dev services for a kubernetes client and was wondering if it better fit in this repo.

**Comment by iocanel** [comment]
+1

**Comment by geoand** [comment]
Yeah, I think it's a good idea

**Comment by mschorsch** [comment]
+1

**Comment by Sgitario** [comment]
+1

**Comment by scrocquesel** [comment]
@Sgitario @geoand @iocanel @stuartwdouglas If you could look at the PR description, I have some questions requiring some advice. Other than that, the PR should be working just fine.
