### ISSUE TITLE
quarkus-smallrye-graphql: @ErrorDataFetch event is not emitted in batch query

### ISSUE THREAD

**Issue by ikenox** [quarkusio/quarkus#28184]
### Describe the bug

When executing a non-batch query, the following code can receive the error that is thrown during data-fetching process.
```
  public void onError(@Observes @ErrorDataFetch ErrorInfo errorInfo) {
    System.out.println("[error] " + errorInfo.getT().getMessage());
  }
```

But, when executing a [batch query](https://quarkus.io/guides/smallrye-graphql#batching) and an error is thrown in the batch process, the above observer can't receive the error.

I guess that we should call `eventEmitter.fireOnDataFetchError(...)` like [this code of non-batching query](https://github.com/quarkusio/quarkus/blob/7744dec/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/spi/datafetcher/QuarkusDefaultDataFetcher.java#L90).

### How to Reproduce?

I wrote a minimum reproducible example.
https://github.com/ikenox/code-with-quarkus/blob/e794dddd21d75d09e9a3e68b4602f5da48d7ca62/src/main/java/info/ikenox/ExampleResolver.java

You can reproduce the issue by executing the following GraphQL query.
```
query {
  example{
    fooValue
    bar{
      barValue
    }
  }
}
```

**Comment by jmartisk** [comment]
Thanks for reporting, I'll take a look into it
