### ISSUE TITLE
5005 port is not freed in devmode during the restart

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#28187]
### Describe the bug

Sometimes, in devmode, after modifying `pom.xml` by adding a new dependency, an error message is displayed during the restart that 5005 is busy and no debug mode will be activated

### How to Reproduce?

Start `quarkus-quickstarts/hibernate-orm-panache-quickstart` in devmode, then add `quarkus-oidc` to pom.xml and the error will be displayed in the console that 5005 is busy

**Comment by sberyozkin** [comment]
CC @stuartwdouglas, Let me know please where it can be fixed, I can try to handle it or open a PR if you can find a few mins

**Comment by stuartwdouglas** [comment]
It probably just needs a sleep + busy wait loop for a second or two to wait for the socket to be released in QuarkusDevModeLauncher. Basically if the socket was ok on the first launch, it should be ok on the second so re-run the checking code in a loop with a small sleep util it either works or some other timeout.
