### ISSUE TITLE
all-config guide - incorrect render of default values for hibernate-orm.active and hibernate-envers.active

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#28196]
### Describe the bug

all-config guide - incorrect render of default values for hibernate-orm.active and hibernate-envers.active

<img width="1421" alt="Screenshot 2022-09-26 at 11 32 57" src="https://user-images.githubusercontent.com/925259/192243361-210d8cc8-7ced-41ec-b490-912542c05107.png">

```
git grep "if Hibernate ORM is enabled" 
extensions/hibernate-envers/runtime/src/main/java/io/quarkus/hibernate/envers/HibernateEnversBuildTimeConfigPersistenceUnit.java:    @ConfigItem(defaultValueDocumentation = "`true` if Hibernate ORM is enabled; `false` otherwise")
extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/HibernateOrmRuntimeConfigPersistenceUnit.java:    @ConfigItem(defaultValueDocumentation = "`true` if Hibernate ORM is enabled; `false` otherwise")
```

### Expected behavior

Nicer render of default values for hibernate-orm.active and hibernate-envers.active

### Actual behavior

Incorrect render of default values for hibernate-orm.active and hibernate-envers.active

### How to Reproduce?

 - https://quarkus.io/version/main/guides/all-config
 - type `ORM is enabled` into `FILTER CONFIGURATION` field

### Quarkus version or git rev

Quarkus main

**Comment by yrodiere** [comment]
Thanks for reporting.

It seems you already had a look at source code, are you planning to send a PR? I expect this should be a two-liner :) The easiest solution is probably to switch from backticks (\`) to single quotes (')

**Comment by rsvoboda** [comment]
PR: https://github.com/quarkusio/quarkus/pull/28197
