### ISSUE TITLE
Default Kafka devservice provider switcher

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#28194]
### Description

As a developer, I would like to have a Quarkus property that allows me to set a default DevService Kafka provider (Strimzi / Redpanda). Currently, I am able to set a Kafka devservide docker image by the property `quarkus.kafka.devservices.image-name`, the problem is that forces me to define a docker image version or use the latest one. My proposal is to create a new property...lets call it `quarkus.kafka.devservices.provider` that allow me to define who is going to be my Kafka provider. Kafka BOM version will be used by default. 

### Implementation ideas

New Quarkus Kafka property:

`quarkus.kafka.devservices.provider: strimzi | redpanda`

Quarkus Kafka BOM version must be used under this configuration. If `quarkus.kafka.devservices.provider` and `quarkus.kafka.devservices.image-name` are defined in the same property file, then `quarkus.kafka.devservices.image-name` will have more priority

**Comment by ozangunalp** [comment]
If I understand correctly, basically you'd like to have a default image for strimzi and a default image for redpanda ?

**Comment by pjgg** [comment]
if you set `quarkus.kafka.devservices.provider` to `strimzi` then you should have de default strimzi image with the BOM kafka version for this image

**Comment by cescoffier** [comment]
I would be careful. The strimzi ad dev service experience is not great yet. That's why we want the user that wants to switch to be perfectly aware of it.
