### ISSUE TITLE
Add traceId to metrics when relevant

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#28208]
### Description

TraceId attribute could be injected in metics when relevant AND possible (eg when quarkus-opentelemetry is present), it would allow using examplar to correlate metric, span and log.

Gauges on endpoints provides min and max values, and it would be great to have more insights on those..

**Comment by jtama** [comment]
It coulld maybe be done using MDC (as per logging).

**Comment by brunobat** [comment]
@jtama traceId is created per request and metrics, by definition aggregate data on multiple requests. 
This is something that would provide little help due to high cardinality and could potentially explode the storage requirements. 
Can you provide an example where this could be useful?

**Comment by jtama** [comment]
Gauges on requests provide a max value, it could be usefull to have more insights on those, no ?

**Comment by brunobat** [comment]
That's interesting. Min Max values could be a good use case. 
Do you see other cases? 
Can you please re-write the issue in a more concrete way with use cases?

**Comment by jtama** [comment]
Done, no other use case I can think of for the moment.

**Comment by ebullient** [comment]
Micrometer now has support for exemplars (which is where this trace id would go.. ), and that's what this is.. 

https://github.com/micrometer-metrics/micrometer/issues/2672

I think we only need some glue: https://github.com/micrometer-metrics/micrometer/pull/3091#issue-1177411405

**Comment by jtama** [comment]
I can maybe try to write the glue.

**Comment by jtama** [comment]
@brunobat : I think this one is closed.
