### ISSUE TITLE
Getting-start example Error running docker native container

### ISSUE THREAD

**Issue by Panciz** [quarkusio/quarkus#2822]
I followed the instruction on https://quarkus.io/guides/building-native-image-guide but I get this error when I run the docker image.

I did all the steps in the tutorial

1. `./mvnw package -Pnative -Dnative-image.docker-build=true`
2. `docker build -f src/main/docker/Dockerfile.native -t quarkus-quickstart/getting-started .`
3. `docker run -i --rm -p 8080:8080 quarkus-quickstart/getting-started`

but I get this error:

```
./application: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```
**Environment (please complete the following information):**

 - Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
-  java version 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190420092731.buildslave.jdk8u-src-tar--b03)
OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)
```

 - quarkus version 0.16.1

**Additional context**

The non native Docker image `Dockerfile.jvm` works fine.
In the container I can find the lib `/lib64/libcrypt.so.2`.

**Comment by Panciz** [comment]
As suggested in by Michal Szynkiewicz in [Quarkus Google-Groups](https://groups.google.com/forum/#!topic/quarkus-dev/dREc4GjsqkE) I change the base image to 

`FROM registry.access.redhat.com/ubi8/ubi-minimal
`
and It works

**Comment by gwenneg** [comment]
Considering `registry.fedoraproject.org/fedora-minimal` was replaced with `registry.access.redhat.com/ubi8/ubi-minimal` in all quickstarts `Dockerfile.native` files. I'd say this issue can be closed.
