### ISSUE TITLE
Qute guide mentions Publisher, which was removed long ago

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#28230]
### Description

The title says it all
Guide:
https://quarkus.io/version/main/guides/qute#reactive-and-asynchronous-apis
PR, which removed Publisher API:
https://github.com/quarkusio/quarkus/pull/10489

**Comment by mkouba** [comment]
Ok, the [reference guide](https://quarkus.io/guides/qute-reference#rendering-output) is correct. I'd just remove this section completely.
