### ISSUE TITLE
Unable to get Multipart file upload work in openapi/swaggerUI in quarkus 2.12

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#28231]
### Describe the bug

I was trying to see if I could have a mutipart file upload within the swagger UI. I stumbled on that github project that does exactly that; https://github.com/felipewind/quarkus-swagger-upload-file 

The project works and uses quarkus 2.9.2. But when updating quarkus 2.12.3. It does not work anymore, the swagger shows an array of objects, instead of an array of string/binary

I was able to get it to work for a single file by going from;

```java
    @Schema(implementation = UploadFormSchema.class)
    public static class MultipartBody {
        @RestForm("files")
        public List<FileUpload> files;
    }
```

to 

```java
    public static class MultipartBody {
        @RestForm("files")
        @Schema(type = SchemaType.STRING, format = "binary")
        public List<FileUpload> files;
    }
```

But still could not making work as a list as the initial project does in quarkus 2.9.x.

### Expected behavior

swagger-ui should show a list of string/binary file upload in quarkus 2.12.x

### Actual behavior

swagger-ui shows a list of object types

### How to Reproduce?

Reproducer: https://github.com/felipewind/quarkus-swagger-upload-file

Steps;
1- run mvn quarkus:dev and go to the swagger-ui and see the file upload working
2- update the pom file and change the quarkus version to 2.12.3
3- run mvn quarkus:dev and see the file upload not working anymore

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by MikeEdgar** [comment]
@manofthepeace - does this give you the output you're looking for?

```java
@Schema(type = SchemaType.STRING, format = "binary")
public static class UploadItemSchema {
}

public static class MultipartBody {
    @RestForm("files")
    @Schema(implementation = UploadItemSchema[].class)
    public List<FileUpload> files;
}
```

**Comment by manofthepeace** [comment]
It does work as expected! Thank you very much. Mind explaining minimally why the other version stopped working, I am curious.

Thanks for your time

**Comment by MikeEdgar** [comment]
> Mind explaining minimally why the other version stopped working, I am curious

I haven't figured it out yet :-) I'll post back here when I find out

**Comment by MikeEdgar** [comment]
@manofthepeace , the change was due to support being added for `org.jboss.resteasy.reactive.MultipartForm` in release 2.1.23. There are differences between how request bodies are handled when they are found to be `@BeanParam`s, or forms rather than something like a JSON body.
