### ISSUE TITLE
Register all BouncyCastle algorithms for reflection in quarkus-security

### ISSUE THREAD

**Issue by erik-wramner** [quarkusio/quarkus#28250]
### Description

See discussion [Problems with BouncyCastle in native images ](https://github.com/quarkusio/quarkus/discussions/28234).

Right now Quarkus registers many of the individual BC algorithms for reflection, but that is tricky for applications that need to support many and unforeseen algorithms. Specifically, our application receives messages and based on the content we need to use different digest, signature and encryption algorithms.

It  would be great to have an option to set in application.properties that enables reflection for ALL algorithms in BC. That way we can sleep better, knowing there will not be an unexpected failure when a message with an unsupported algorithm arrives.

### Implementation ideas

In the discussion @sberyozkin mentioned that Camel Quarkus is already registering all algorithms, so it should be possible to do the same in quarkus-security when a new option in application.properties is set.

**Comment by michalvavrik** [comment]
Hello @erik-wramner ,

please give me one example (algorithm, signature or message digest) that needs to be registered for reflection. I could easily be wrong, but I don't think it is really necessary as all providers algorithms seems to be registered. Just give me one example that's failing.

Thank you,

Michal

**Comment by erik-wramner** [comment]
Since I registered things correctly (as suggested in the linked discussion) things are working and this is more of a nagging fear. If you think everything is registered, then it is probably fine. However, I will write a test program that uses some of the more exotic but still likely algorithms to see if I can find one that fails. I'm a bit busy with other things, but hopefully I should have an answer by the end of next week. Thanks for looking into this.

**Comment by michalvavrik** [comment]
That's great Erik, please take your time. So far we have established here https://github.com/apache/camel-quarkus/issues/2922 that what Camel Quarkus is also unnecessary. It would be nice to have it confirmed from you, thanks.

**Comment by erik-wramner** [comment]
I have tested all the likely algorithms now and they work. Please don't take that as a guarantee that ALL algorithms work - BC supports a wide range of exotic algorithms and I have not tested them all. Still, from my point of view you can close this issue, and I will open a new one if we actually run into an unsupported algorithm instead. Hopefully you are correct and that won't happen.

**Comment by michalvavrik** [comment]
Thanks for checking it out. I agree with your suggestion, let's open an issue if you ever run into problem. From my digging, that won't happen till Bouncy Castle provider stop initializing all algorithms they support.
