### ISSUE TITLE
Quarkus CLI - Unrecognized configuration key "quarkus.home"

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#28257]
### Describe the bug

I've installed the Quarkus CLI tool foollowing the SDK! Man instructions on https://quarkus.io/guides/cli-tooling.

Next step of the guide, it suggest running
> quarkus --version

The output is:

> 2022-09-28 14:13:29,703 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.home" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Client Version 2.0.0.CR3

### Expected behavior

It shouldn't log warnings out of the box.

**Comment by gsmet** [comment]
Hmmmm `Client Version 2.0.0.CR3`?!?

**Comment by gsmet** [comment]
Maybe you had very old metadata and it installed an old version? If so maybe we should add a step to update the metadata before installing.

(But I'm not sure what I just wrote makes sense in the SDKMan! world)

**Comment by Sanne** [comment]
oh, good catch about the version. I had an older version of the app installed as a "jbang app"
