### ISSUE TITLE
application.properties ConfigSource has ordinal different than 250 when running in native mode

### ISSUE THREAD

**Issue by hbelmiro** [quarkusio/quarkus#28269]
### Describe the bug

The application.properties ConfigSource should have ordinal equal to 250 as stated [in the docs](https://quarkus.io/guides/config-reference#configuration-sources), but when running a native image, the ordinal is `Integer.MIN_VALUE`.

### Expected behavior

application.properties ConfigSource having ordinal equal to 250.

### Actual behavior

application.properties ConfigSource has ordinal equal to `Integer.MIN_VALUE`.

### How to Reproduce?

1) Create an application with the following application.properties file:

`application.properties`
```properties
a.simple.property=the-awesome-value
```

2) Create a Resource class with the following code:

```java
@Path("/hello")
public class GreetingResource {

    @Inject
    Config config;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public int hello() {
        return config.getConfigValue("a.simple.property").getSourceOrdinal();
    }
}
```

3) Build and run a native image
4) Access http://localhost:8080/hello
5) It returns -2147483548 (`Integer.MIN_VALUE`)

### Output of `uname -a` or `ver`

Linux 192.168.10.47 5.19.8-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 8 19:02:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10) OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by radcortez** [comment]
When building the native image, we record the lookup result in a low ordinal source to remove `application.properties` from the native image.

This usually works fine because you get the value recorded from `application.properties` (already considering that lower ordinal sources were evaluated during build time). Or, if you override it, you get the new value.

Is the provided source dynamic? Meaning that it may provide different values between build (event none at all) and runtime?

**Comment by hbelmiro** [comment]
@radcortez the provided source is not dynamic. This behaviour is a problem when we have a ConfigSource with ordinal > `Integer.MIN_VALUE` and < 250.

In my use case, we have this ConfigSource with ordinal = 99 and the properties end up behaving differently between JVM and native modes.

## When JVM

| ConfigSource | Ordinal | Property | Value     |
|-----------|----|---|---|
| Default ConfigSource | 99 | `my_property` | `default-value`     |
| `application.properties` | 250 | `my_property` | `custom-value` |

Effective `my_property`'s value when JVM: `custom-value`

## When native

| ConfigSource | Ordinal | Property | Value     |
|-----------|----|---|---|
| Default ConfigSource | 99 | `my_property` | `default-value`     |
| `application.properties` | `Integer.MIN_VALUE` | `my_property` | `custom-value` |

Effective `my_property`'s value when native: `default-value`

As a workaround, I changed our ConfigSource's ordinal to `Integer.MIN_VALUE`. (actually, I think it's a good practice to do this in default ConfigSources)

**Comment by radcortez** [comment]
Yes, this can happen if the custom source is not removed from the native image. If the source is not dynamic, the values could be read during build time and removed. We do this to optimize the native image and not require rereading the values on the native image runtime.

Let me have a look.

**Comment by radcortez** [comment]
I had a look into https://github.com/hbelmiro/kogito-runtimes/blob/92c0ad8ee1dc51d11a63a49b50739699fc85f6ee/quarkus/addons/knative/eventing/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/eventing/KnativeEventingConfigSource.java and I believe there is a better way to implement the feature. Usually, calling `ConfigProvider.getConfig` may cause some issues when called from a `ConfigSource`.

My recommendation is to either use a `SmallRyeConfigFactory`:
https://smallrye.io/smallrye-config/2.12.1/config-sources/factories/

We can query the current configuration as it is being build and provide the default if the expected values are missing in a new source.

Or use a `SmallRyeConfigSourceInterceptor`:
https://smallrye.io/smallrye-config/2.12.1/extensions/interceptors/

When querying a specific key, we are able to return a completely different value, depending on the implementation rules (which seems to align with what we have here).

I think we generally want to avoid having to include all the configuration resources in the native image (and querying, when that work can be done during compilation).

**Comment by hbelmiro** [comment]
I'm not sure I'm following @radcortez.
You mean moving all the logic or just the logging?

**Comment by radcortez** [comment]
All the logic could be moved.

The issue with calling `ConfigProvider.getConfig` from the `ConfigSource` is that it can cause `StackoverflowErrors`. `ConfigProvider.getConfig` creates a new `Config` instance if there is none present in the current `Classloader`, including initializing the discovered `ConfigSource`. Usually, you already expect to have a `Config` in the classloader, but the user can release it and create it again. Yes, it is a long shot for it to happen, but I saw it a lot of times :)

So, my recommendation is to avoid that call and either use the factory or the interceptor to write that logic (which provides you safe access to the current configuration).

**Comment by radcortez** [comment]
Great. Closing this, then.
