### ISSUE TITLE
Expose information to extensions whether a build targets containers

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2827]
See the discussion in https://github.com/quarkusio/quarkus/pull/2794, there should be a way extensions can easily find out whether a build is targeting containers without having to query the `native-image.container-runtime` and `native-image.docker-build` system properties themselves.

**Comment by gsmet** [comment]
I'm not entirely sure if we have a way to do that now with the new stuff @stuartwdouglas worked on for the native image build.

@stuartwdouglas do you know off the top of your head if there is a way to do that now?

**Comment by stuartwdouglas** [comment]
You can inject io.quarkus.deployment.pkg.NativeConfig and look at the containerBuild field

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/pull/5459 shows how this can be done
