### ISSUE TITLE
@Retry and @Transactional -> @RetrieableTransactional

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#28286]
### Description

On I transaction error, I would like to retry the transaction, if it did fail because of an optimistic lock exception.

First thought obviously is to do it this way:
```
@Transactional
@Retry(OptimisticLockException.class)
void myMethodDoingSomeDBStuff(){
  ...
}
```
This sadly does not work, as the `@Retry` interceptor is beeing processed before the `@Transactional` interceptor is finishing. This means, I cannot retry on a exception which originates of a failed transaction. I could wrap this method with another bean to make it work, but this seems odd.

I also could change the global priority of the `@Retry` interceptor, but I really don't want to open the pandoras box.

As I haven't found another way to solve this (please correct me if there is), it leads me to want a cross over of both: `@RetrieableTransactional` that implements an interceptor that wraps both of them, but in the order
1. Transactional interceptor
2. Retry interceptor

Does this sound reasonable?

**Comment by Ladicek** [comment]
Technically you don't have to create another bean, because Quarkus supports self-interception. You could just do something like:

```java
@Retry(OptimisticLockException.class)
void myMethodDoingSomeDBStuff(){
  internal_myMethodDoingSomeDBStuff();
}

@Transactional
void internal_myMethodDoingSomeDBStuff(){
  ...
}
```

However, I find this dangerous in general. If you use Hibernate (ORM or Reactive), you _may not_ use the session if any of its methods throws an exception, and I'm not sure we can possibly write a generic interceptor that would drop the session and create a new one. If you use JDBC directly, then this might be possible, but I'm no JDBC/JTA expert really.

**Comment by HerrDerb** [comment]
I finally found an acceptable solution for my case. I added a new `@FaultToleranceBinding` interceptor with a priority which is higher than the transactional interceptor. Inside I reuse the regular `FaultToleranceInterceptor` interceptor, only if there is also a `@Transactional` annotation on the same method (which fits my usecase for OptimisticLockException and StaleStateException)

```
@Interceptor
@FaultToleranceBinding
@Priority(Interceptor.Priority.PLATFORM_BEFORE + 100)
public class TransactionalFaultToleranceInterceptor {
    ....
    
    @AroundInvoke
    public Object intercept(InvocationContext interceptionContext) throws Exception {
        boolean isTransactional= interceptionContext.getMethod().isAnnotationPresent(Transactional.class);
        if (isTransactional) {
            return faultToleranceInterceptor.intercept(interceptionContext);
        }
        return interceptionContext.proceed();
    }
```

This generally works, but has one minor downside, but which does not really bother me:
The method now has two `FaultToleranceInterceptor`: One before the transaction interceptor and one after. If I would retry on a exception which is not resulting from a transaction, the retry count would be pow(2). But as I won't use it that way, its not a problem for me.

Anyway, we thought about a nice solution for this too. We tried to wrap the `@Retry` annotation and bind the `TransactionalFaultToleranceInterceptor` only to the `@OptimisticLockRetry` annotation

```
@InterceptorBinding
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
@Retry(retryOn = {OptimisticLockException.class, StaleStateException.class})
public @interface OptimisticLockRetry {}
```

```
@Interceptor
@OptimisticLockRetry
@Priority(Interceptor.Priority.PLATFORM_BEFORE + 100)
public class CustomFaultToleranceInterceptor {
    ....
}
```

Sadly this is not supported at the moment, as the implementation of `FaultToleranceInterceptor` seems to not see or respect `@Retry`  when passed as meta annotation. Maybe this could be changed?
