### ISSUE TITLE
`StorkClientRequestFilter` not registered when using `ClientBuilder` to build a jax-rs client

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#28292]
### Describe the bug

When using Stork with a manually-created jax-rs client (via `ClientBuilder.newClient()`), the `StorkClientRequestFilter` is not automatically registered.

Stork worked fine with the jax-rs client in Quarkus 2.12, but in 2.13 this is broken unless the user manually registers the filter.

See https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/main/java/io/quarkus/sample/superheroes/fight/client/VillainClient.java#L38

If the user does not manually register the filter then they will end up with a failure that looks something like

```
java.lang.IllegalArgumentException: Invalid REST Client URL used: 'stork://villain-service/api/villains/random'
```

At a very minimum, this should be documented in the Quarkus 2.13 release notes.

### Expected behavior

I would expect Stork to "just work" with the jax-rs client, as it did prior to Quarkus 2.12.

### Actual behavior

The application fails if the user does not manually register the filter.

### Additional information

The `OpenTelemetryClientFilter` seems to be registered automatically when creating the jax-rs client this way, so there must be a way to do this as well for the `StorkClientRequestFilter`.

**Comment by cescoffier** [comment]
When using the client API 9not using the declarative approach), the filters is not registered. 
I don't know if there is a way to register it explicitly.

**Comment by edeandrea** [comment]
The `OpenTelemetryClientFilter` seems to get registered, so there's gotta be a way :)

In 2.12 I had to manually register the `OpenTelemetryClientFilter`, but in 2.13 its magic - its just there :)

**Comment by Sgitario** [comment]
Would you mind if I work on this issue? It seems a good one to get started with the Stork extension.

**Comment by Sgitario** [comment]
As far I'm seeing, there is a test that covers that this filter is automatically injected: https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/stork/PassThroughResource.java

The main difference is that it works when using `RestClientBuilder.newBuilder()` and not with `ClientBuilder.newClient()`, which I think it's expected. However, I wonder how it could be working in 2.12. The commit https://github.com/quarkusio/quarkus-super-heroes/commit/6792685957567ac95c914b0e73873fe4e8f900fe changed the manual registry from `OpenTelemetryClientFilter` to `StorkClientRequestFilter`.

@edeandrea are you sure this was working on 2.12?

**Comment by edeandrea** [comment]
@cescoffier mentioned on Zulip chat that he had a fix in mind for this.

**Comment by Sgitario** [comment]
> You're correct in 2.12 there was no `StorkClientRequestFilter`. That class didn't exist until 2.13. What I was trying to say, though, is that stork worked fine in 2.12 without the user having to do anything.

ah ok ok! 

Looking into the commit: https://github.com/quarkusio/quarkus/commit/238a6ecfa522d13609b21e05cc78d6e8b3a50ad1, it's expected that it was working 2.12 with doing nothing, but not from 2.13. 


> @cescoffier mentioned on Zulip chat that he had a fix in mind for this.

ok ok, so I will let him figure it out. I'm curious about the solution he has in mind.

**Comment by Sgitario** [comment]
> Whether or not it is currently "working as intended/expected" or not, it is a change in behavior that does break any user between 2.12 & 2.13, so this should be documented in the 2.13 release notes.

Indeed

**Comment by edeandrea** [comment]
@gsmet we still should have something in the 2.13.0.Final release notes about this.

**Comment by aureamunoz** [comment]
Great! thanks @edeandrea
