### ISSUE TITLE
Native compilation again does't like spaces in project directory in 0.15.0 and 0.16.0 ver

### ISSUE THREAD

**Issue by krishkir** [quarkusio/quarkus#2830]
**Describe the bug**
Native compilation doesn't like space in project directory. It is a old bug anf fixed in 0.13.0 release reference ticket no: #1673 . i am facing the samer issue with 0.15.0 and 0.16.0 releases.

**Expected behavior**
Native compilation should allow spaces in the project directory path.

**Actual behavior**
Throwing the below error
12:57:08 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /home/jenkins/workspace/Online%20Service%20Name%20CRP/NameService/target/NameService-0.0.1-SNAPSHOT-runner.jar (No such file or directory)
12:57:08 	at io.quarkus.undertow.runtime.graal.URLResourceSubstitution$ResourceInfo.<clinit>(URLResourceSubstitution.java:103)
12:57:08 	... 40 more
12:57:08 Caused by: java.io.FileNotFoundException: /home/jenkins/workspace/Online%20Service%20Name%20CRP/NameService/target/NameService-0.0.1-SNAPSHOT-runner.jar (No such file or directory)

**To Reproduce**
1. Create project directory name with space and execute a native compile

**Comment by machi1990** [comment]
I can take a look at this.
