### ISSUE TITLE
Quarkus requires `{` and `}` to be URL encoded in the query param

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#28303]
### Describe the bug

I have hit a strange issue that Quarkus requires `{` and `}` to be URL-encoded in the query param value.. Seems that different clients choose different behavior wrt encoding those chars, and it's kind of a gray area.. There are bunch of RFCs that define different approaches, and the [WHATWG (URL) standards](https://url.spec.whatwg.org/) that specifies that for query params these chars does not have to be encoded.

Some clients, for example Postman (from version `8.0` and up), will not URL encode the `{` and `}` when those are in the query param value. In the same way, some HTTP server implementations do not require those to be encoded. With Quarkus, any HTTP request that has `{` or `}` non encoded in the query value will fail with `400`. 

Now I am not interested here in going into deeper discussion on what's the right approach. But the previous HTTP server implementation we used allowed those chars to be not-encoded and our new services are now failing those requests. This means we are breaking the backward-compatibility in a way.

I would like to know if there is any way to change this behavior? Any property, specification, anything that we could quickly use to fix the issue. Any solution is fine, maybe an interceptor that can perform additional encoding or something like this :pray:  
   

### Quarkus version or git rev

2.12.3.Final

**Comment by geoand** [comment]
Hi,

Is there any quick way I can see this in action on a Quarkus application?

**Comment by ivansenic** [comment]
Try sending `{` as the query param value, should be as simple as that (seen on reasteasy-reactive).. You will get a straight `400` response back without even reaching the application..

**Comment by geoand** [comment]
You can get around this by starting the application with `-Dvertx.disableURIValidation=true`. 
It's totally undocumented and we usually only use it in benchmarks, but it's not going to go away.

**Comment by ivansenic** [comment]
Oh that's great.. I owe you a box of Mythos..

**Comment by geoand** [comment]
😆

**Comment by geoand** [comment]
So should we close this?

**Comment by ivansenic** [comment]
Yup, closing it..

**Comment by geoand** [comment]
👍🏼

**Comment by ivansenic** [comment]
@geoand Any idea why is there a note not to disable the option in production?

https://github.com/quarkusio/quarkus/blob/e37be4694aaef028733802065212f954dc4d408d/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L162-L163

**Comment by geoand** [comment]
Because you could end up with server side errors like https://github.com/quarkusio/quarkus/issues/10801
