### ISSUE TITLE
Hibernate validator responses with wrong Content-Type header when working in reactive mode

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#28324]
### Describe the bug

I have two Resteasy Reactive endpoints, both have `@Digits` annotation from Hibernate Validator. One of the endpoint doesn't have any `@Produces` annotations, another has `@Produces(MediaType.TEXT_PLAIN)`. When querying both with invalid values, both return message with header `Content-Type=application/json`(1) and with body, which is not json(2). 

When `quarkus-resteasy-reactive` is replaced with `quarkus-resteasy`, both headers contain "text/plain".

### Expected behavior

Validation messages should have "Content-Type" header, which faithfully describes content of body.
If endpoint has `@Produces` annotation, then content and headers of validation messages should conform to it.
If endpoint has no `@Produces` annotation, then validation messages should return text, to mirror the behavior of classic implementation.

### Actual behavior

Both endpoints return responses with header `Content-Type=application/json` and bodies like that:
```
ViolationReport{title='Constraint Violation', status=400, violations=[Violation{field='validate.id', message='numeric value out of bounds'}]}
```

for comparison, proper json endpoints return bodies, like this:
```
{
    "title": "Constraint Violation",
    "status": 400,
    "violations": [
        {
            "field": "validate.id",
            "message": "numeric value out of bounds"
        }
    ]
}
```

### How to Reproduce?

1. Clone: `git clone git@github.com:fedinskiy/reproducer.git -b reproducer/validator-json-header`
2. Run tests `mvn clean verify -Preactive`
3. Run `mvn clean verify -Pclassic` to verify, that classic version works as expected

### Output of `uname -a` or `ver`

2.12.3.Final

### Output of `java -version`

11.0.16 temurin

### Quarkus version or git rev

2.12.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gsmet** [comment]
@geoand looks more like a RESTEasy Reactive issue to me. The OP provided a reproducer above.

I think there are two issues here: the content type and the content itself, which should probably be made more readable (not sure how RESTEasy Classic handles text plain validation).

**Comment by geoand** [comment]
I'll have a look next week.

Thanks for the heads up

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28343 takes care of it
