### ISSUE TITLE
RestEasy + Panache + OpenApi: did you forget to annotate your entity with @Entity?

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#2833]
**Describe the bug**
When I add the openApi dependency to the project I get:
This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?

**Expected behavior**
No error

**Actual behavior**
Stacktrace:
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?

**To Reproduce**
1: https://github.com/andrejpetras/quarkus-quickstarts/tree/bug-openapi-panache/hibernate-orm-panache-resteasy
2. https://github.com/andrejpetras/quarkus-quickstarts/commit/4fa8d6f85745408b52e6dc8b549d828e5a9c6f31
4. mvn clean install
5. remove the openApi dependency

Also I have a issue if the ElementCollection was LAZY
```
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "PARENT",
            joinColumns = @JoinColumn(name = "PARENT_GUID")
    )
    public Set<String> parents = new HashSet<>();
```

**Comment by gsmet** [comment]
@andrejpetras 

Thanks for reporting the issue.

So what you're saying is that, just adding the openapi dependency to the quickstart project makes it fail?

It's not clear how the first issue is related to `Also I have a issue if the ElementCollection was LAZY`?

**Comment by andrejpetras** [comment]
@gsmet 
Yes, when I add the openApi dependency I get an error.

"LAZY": Sorry probably I am mixing two different issues. But I have another project where I added the openAPI dependency and I got a lazy load exception on the ElementCollection. When I change it to the EAGER or remove the openAPI dependency it is working.

**Comment by FroMage** [comment]
This could be due to #2961

**Comment by FroMage** [comment]
I've merged a fix for #2961. Could you tell us if it fixes your problem?

**Comment by Dufgui** [comment]
I check with his branch on 0.18 it fail, on 0.21.1 it's works. Please close it.

**Comment by FroMage** [comment]
Great, thanks!
