### ISSUE TITLE
First mail executed from Vertx's ordered blocking pool gets stuck

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#28353]
### Describe the bug

My application is trying to send emails from a thread in vertx's blocking pool with `ordered=true`. The first mail sent from the application get's stuck/times out when I use the reactive mailer directly with .await.atMost(...). The email is still sent (I get it) after the exception is raised.

I suspect that something in the SMTP connection handshake requires ordered execution, too, and the threads deadlock.

### How to Reproduce?

[first-mail.zip](https://github.com/quarkusio/quarkus/files/9697322/first-mail.zip)

Start this application in dev mode and then run `curl localhost:8080/pooled?ordered=true -v -X POST`. The request should complete with 204 but this appears in server log:

```
2022-10-03 14:10:09,101 INFO  [com.exa.GreetingResource] (executor-thread-0) About to send mail through pool, ordered=true
2022-10-03 14:10:09,102 INFO  [com.exa.GreetingResource] (vert.x-worker-thread-0) Sending mail...
2022-10-03 14:10:14,124 ERROR [com.exa.GreetingResource] (vert.x-worker-thread-0) Failed to send: io.smallrye.mutiny.TimeoutException
...
```

Note that the SMTP server used in this example requires you to execute it from within Red Hat internal network.

### Quarkus version or git rev

2.12.3, also 2.13.0

**Comment by mkouba** [comment]
Why do you use the reactive mailer on a vertx worker thread? I mean it would make sense to use the imperative/blocking version on a worker thread and the reactive version on the even loop (an I/O thread), i.e. in a non-blocking resource or scheduler method.

Could you please provide a simple project that would reproduce this behavior?

**Comment by rvansa** [comment]
@mkouba The reproducer is already attached to the report, under 'How to Reproduce'. I run the code in a transaction that involves JPA, hence the blocking/worker thread. The `ordered=true` is a different matter, it's actually a workaround for a ordering conflict in PostgreSQL that fails the transaction, so it is not strictly necessary (I plan to work on a better solution).
Initially I've used the blocking mailer but this is just a wrapper over the reactive version that gets stuck forever, rather than timing out.

@cescoffier already explained that this can't be fixed as the mailer connection process relies on ordering, but in that case I really think that calling mailer from the ordered thread should throw an exception immediately.

**Comment by cescoffier** [comment]
It's not that simple. It only happens during the connection establishment. So it's not all calls (and not only the first one, as it depends on connection cut and keep-alive)

**Comment by rvansa** [comment]
@cescoffier Yes, though if it's unsafe to establish connection this way, given that it might be racy/out of control, invoking that should be prohibited in all cases, and in mail mock mode, too.

**Comment by mkouba** [comment]
> The reproducer is already attached to the report, under 'How to Reproduce'. 

Ah, sorry. I completely missed this.

> Initially I've used the blocking mailer but this is just a wrapper over the reactive version that gets stuck forever, rather than timing out.

I see.

@cescoffier It seems that the blocking API does not provide any form of timeout?

> @cescoffier already explained that this can't be fixed as the mailer connection process relies on ordering,

IIUIC the underlying vetx client is using `Vertx.executeBlocking()` with `ordered=true` as well. Would you guys mind elaborating a bit more?

**Comment by cescoffier** [comment]
The problem comes from the usage of ordered `executeBlocking`, which creates a Frankenstein monster in terms of the execution model (you are on an event loop, you switch to a worker, but you can't go back to the event loop because of `ordered=true`)
Either use the reactive mailer, and use Uni / Multi, or use the imperative mailer.
