### ISSUE TITLE
Can't use custom java.util.Date ParamConverterProvider when using Quarkus-Renarde

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#28363]
### Describe the bug

I submitted an issue with that project as well and am just posting here because I thought I saw @FroMage and others in this repo as well.

This is the issue I posted: https://github.com/quarkiverse/quarkus-renarde/issues/65

It looks like Renarde's custom `java.util.Date` `ParamConverterProvider` implementation prevents the one I wrote from being used and I can't use any Date fields in my beans using the `@BeanParam` annotation because I want to group all my HTML FORM fields in a POJO and not list them all out in my method signature.

### Expected behavior

My custom provider should be registered and find all instances of `.java.util.Date` fields in my POJO

### Actual behavior

My instance is registered but NONE of the `java.util.Date` fields are passed to the instance, only the Strings, Booleans, etc are passed to the providers `getInstance()` method.

### How to Reproduce?

I downloaded the `rr-paramconverter.zip` from this issue which lead me down this path.
https://github.com/quarkusio/quarkus/issues/21664

I then simply added a print statement in the JavaTimeParamConverterProvider class to print out ANY `rawType` being passed to it on Quarkus startup.

```java
@Provider
public class JavaTimeParamConverterProvider implements ParamConverterProvider {

    @Override
    public <T> ParamConverter<T> getConverter(Class<T> rawType, Type genericType, Annotation[] annotations) {
      System.out.println("Checking type: " + rawType);
      
        if (rawType.isAssignableFrom(LocalDate.class)) {
            return (ParamConverter<T>) new LocalDateParamConverter();
        }

        if (rawType.isAssignableFrom(LocalTime.class)) {
            return (ParamConverter<T>) new LocalTimeParamConverter();
        }

        if (rawType.isAssignableFrom(LocalDateTime.class)) {
            return (ParamConverter<T>) new LocalDateTimeParamConverter();
        }

        if (rawType.isAssignableFrom(OffsetDateTime.class)) {
            return (ParamConverter<T>) new OffsetDateTimeParamConverter();
        }
        return null;
    }

}
```

I also modified the `FilterData` class to add a Date field.

```java
public class FilterData {

    @QueryParam("creationDateTimeTo")
    private LocalDateTime creationDateTimeTo;

    @FormParam("expireData")
    private Date expireDate;

    public void setExpireDate(Date date) {
      this.expireDate = date;
    }

    public Date getExpireDate() {
      return expireDate;
    }

    public LocalDateTime getCreationDateTimeTo() {
        return creationDateTimeTo;
    }

    public void setCreationDateTimeTo(LocalDateTime creationDateTimeTo) {
        this.creationDateTimeTo = creationDateTimeTo;
    }
}
```

After modifying the file, do a `mvn clean quarkus:dev` and watch the console. 

WITHOUT the dependency for Renarde, the console prints that the provider is being passed a `java.util.Date`

```
Checking type: class java.time.LocalDateTime
Checking type: class java.util.Date
```

Now, add in the latest Renarde version and run again, and you'll see that `java.util.Date` no longer is being passed into the provider.

```
<dependency>
      <groupId>io.quarkiverse.renarde</groupId>
      <artifactId>quarkus-renarde</artifactId>
      <version>1.0.3</version>
    </dependency>
```

```
Checking type: class java.time.LocalDateTime
```

### Output of `uname -a` or `ver`

Darwin mars.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode)

**Comment by FroMage** [comment]
I don't think this is a bug. Renarde has a date param converter for the ISO format, but if you add a `@Priority(Priorities.USER-1)` to your `ParamConverterProvider`, your provider should be used first.
Please reopen if this doesn't work.

**Comment by tmulle** [comment]
Thank You.. your suggestion seemed to work for me.
