### ISSUE TITLE
Support `StreamingOutput` or document alternative in RESTEasy Reactive

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#28385]
### Description

I have seen this issue discussed in both #26473 and #15891, but it still remains unclear to me how to do the equivalent of `StreamingOutput` with RESTEasy Reactive. If `StreamingOutput` cannot be directly supported as return type for blocking endpoints, I think it would make sense if the documentation provided some clear guidance on how to do this, including how to set headers (e.g. `Content-Disposition` as in the linked discussion), as RESTEasy Reactive is being promoted as the JAX-RS implementation of choice.

As in the discussion #26473 we also have a blocking endpoint which returns the output of some third-party library and having to first store that as a temporary file is IMO not very nice.

**Comment by geoand** [comment]
The alternative is to use `Multi`. Now I do acknowledge that using Multi does not give you a good way to set headers... 
@FroMage WDYT?

**Comment by knutwannheden** [comment]
Would the return type then be `Multi<byte[]>`? I think a concrete example in the docs would be really helpful.

**Comment by geoand** [comment]
> Would the return type then be Multi<byte[]>

It really depends on what you are trying to do.

> I think a concrete example in the docs would be really helpful.

I agree. We have various tests in the codebase, but documentation would definitely help. @FroMage would you like to add something?

**Comment by Postremus** [comment]
@knutwannheden I usually just return an inputstream for file downloads. Not sure if it helps in your situation though.
```
        return Response.ok(blob.getBinaryStream(), document.getMimeType())
                .header("Content-length", document.getFileSize())
                .header("content-disposition", "attachment; filename = " + document.getFileName())
                .build();
```

**Comment by geoand** [comment]
Yeah, that is one way of doing this - if you don't care about blocking that is :)

**Comment by knutwannheden** [comment]
> @knutwannheden I usually just return an inputstream for file downloads. Not sure if it helps in your situation though.

No, in our case we are dealing with a third-party library which writes to a given output stream. We then want to stream this output as the response. So with RESTEasy Classic the code looked something like this:

```java
        StreamingOutput stream = os -> {
            Document document = new Document();
            PdfWriter.getInstance(document, os);
            document.open();
            generatePdf(document, id);
            document.close();
        };
        return Response.ok().entity(stream).build();
```

**Comment by FroMage** [comment]
Supporting streaming directly over the wire in a blocking way like `StreamingOutput` implies that a slow client IO will block a thread for as long as the bytes take to tranfer, locking up that thread which is an easy attack vector.

I can't think of any way to implement `OutputStream` without locking up a thread over IO. IMO the only solution is to either buffer to temp files, or in memory for smaller files, to decouple the task (CPU) from IO. Now, we could certainly add support for a type of `OutputStream` implementation that stores stuff in memory until a certain size, then delegates to a temp file if it exceeds that, and that is automatically deleted once the request is finished (this bit is probably missing ATM). This would then be sent by RESTEasy Reactive async and the user would have the impression that they streamed.

But honestly, I have a vague memory that @stuartwdouglas already implemented something like that somewhere, but I can't quite remember where.

**Comment by FroMage** [comment]
`ResteasyReactiveOutputStream` was it. But it looks to be a bit different, because it appears to support blocking. So… perhaps we actually support streaming while blocking, provided the endpoint is `@Blocking` and done in a worker thread.

If we do… from there to supporting `StreamingOutput`, it should be fairly simple. I would still prefer my suggested solution though, which would not lock a thread for IO.

**Comment by knutwannheden** [comment]
In our case having the endpoint as blocking is not an issue. But `ResteasyReactiveOutputStream` looks like it can only be directly used by interceptors, filters, etc.

I also looked into creating a temp file, but then I couldn't figure out how to get it deleted automatically after the request finishes processing.

Please note that I would be content with a complete example in the documentation, which shows how an endpoint can return a response based on an API returning an `OutputStream`. It doesn't have to be like `StreamingOutput` (even though that would be a nice option for blocking endpoints), but it would be nice if it were complete (e.g. also handle resource cleanup).

**Comment by stuartwdouglas** [comment]
IMHO there is no reason not to support this for @Blocking endpoints, we already have support for returning an InputStream which is just as blocking.

**Comment by knutwannheden** [comment]
I will have to do some more testing, but I think this may do the trick and would allow my endpoints to transparently use `StreamingOutput`:

```java
@Provider
public class StreamingOutputMessageBodyWriter implements MessageBodyWriter<StreamingOutput> {

    @Override
    public boolean isWriteable(Class<?> aClass, Type type, Annotation[] annotations, MediaType mediaType) {
        return StreamingOutput.class.isAssignableFrom(aClass);
    }

    @Override
    public void writeTo(StreamingOutput blob, Class<?> aClass, Type type, Annotation[] annotations, MediaType mediaType, MultivaluedMap<String, Object> httpHeaders, OutputStream outputStream) throws IOException, WebApplicationException {
        blob.write(outputStream);
    }
}
```

**Comment by knutwannheden** [comment]
FWIW, the workaround with the custom `MessageBodyWriter` works as expected.

**Comment by Manfred73** [comment]
This workaround is a lifesaver!
Been troubleshoothing for hours why I got some weird result back from the StreamingOutput (when processing it showed the classname$1..... instead of the filecontent).
Adding this ```StreamingOutputMessageBodyWriter``` does the trick.

**Comment by eggoyster** [comment]
@Manfred73 , @knutwannheden, how to actually use this class?

**Comment by Manfred73** [comment]
All I did was adding this class to my codebase as @knutwannheden described and it automagically works.

**Comment by Manfred73** [comment]
I managed to get it working with the `StreamingOutputMessageBodyWriter`. I have a rest endpoint which returns a 
`Uni<RestResponse<StreamingOutput>>` but now I want to call that endpoint from another rest service and do some processing on the `StreamingOutput`. I've been following https://quarkus.io/guides/rest-client-reactive guide for that, but I'm not sure if this is the right way.

The service which returns the `StreamingOutput`:

```
@Path("/v1/files")
public class FileRepoQueryResource {
   @GET
   @Path("/{id}")
   @Produces(MediaType.APPLICATION_OCTET_STREAM)
   public Uni<RestResponse<StreamingOutput>> readFileById(@PathParam("id") String id) {
      // retrieve file by id and return as StreamingOutput
   }
}
```

Now I have another rest service which should retrieve the file by calling the above endpoint, so I have created a client interface and a resource implementation:

```
@Path("/v1/files")
@RegisterRestClient
public interface FileRepoQueryClient {
   @GET
   @Path("/{id}")
   @Produces(MediaType.APPLICATION_OCTET_STREAM)
   Uni<RestResponse<StreamingOutput>> readFileById(@PathParam("id") String id);
}
```

```
@Path("/v1/files")
public class FileResource {
   @Inject
   @RestClient
   FileRepoQueryClient fileRepoQueryClient;

   @GET
   @Path("/{id}")
   @Produces(MediaType.APPLICATION_OCTET_STREAM)
   public Uni<RestResponse<StreamingOutput>> readFileById(@PathParam("id") String id) {
      return fileRepoQueryClient.readFileById(id);
   }
}
```

And then a service which uses the `FileResource.readFileById` to get the `StreamingOutput` and count all lines starting with 2:
```
@AllArgsConstructor
@ApplicationScoped
public class FileProcessService {
   private final FileResource resource;

   public Integer getNumberOfLinesStartingWith2(String id) {
      // How to process the streaming output here and count all lines starting with 2?
      return resource.readVerzuimbestandById(id).subscribe().with() .......
   }
}
```

**Comment by HugoVinhal98** [comment]
Just want to thank @knutwannheden for the awesome solution! Been struggling with this all morning and the new class worked like a charm 😍

**Comment by geoand** [comment]
I just looked at what `StreamingOutput` actually is... I never realized how simple it was...

@knutwannheden your solution seems correct (and FWIW, it's also what RESTEasy Classic) does, so would you like to contribute the fix (we would ideally have a few tests as well)?

**Comment by geoand** [comment]
I actually went ahead and did this myself as it also required updating the TCK.

**Comment by knutwannheden** [comment]
Cool, thanks!

**Comment by sven-geisenhainer** [comment]
Hi folks, please correct me if I'm wrong but StreamingOutput can only be used with non-reactive upstream data sources because the output stream is closed after StreamOutput.write has returned which means one has to block within that method until the last byte is written - but blocking is not allowed.

Because returning Multi<Byte[]> currently does not support content negotiation / dynamic content type, there is no way to stream dynamic content in a reactive way. Are there plans to add support for it?

**Comment by geoand** [comment]
@sven-geisenhainer there is a way to do what you are asking, see https://quarkus.io/guides/resteasy-reactive#streaming-support

**Comment by sven-geisenhainer** [comment]
@geoand my case is a bit more complicated than just streaming bytes as shown in the documentation samples, I also need to retrieve some meta data like content-type from upstream (cloud) before streaming the actual content. So in fact I need to combine Uni and Multi. Consider the following test class:

```
public class StreamTestResource {
    private static class FileInfo {
        String name;
        String contentType;
        long size;

        public FileInfo(String name, String contentType, long size) {
            this.name = name;
            this.contentType = contentType;
            this.size = size;
        }
    }

    private final Uni<FileInfo> fileInfoSource  = Uni.createFrom().item(new FileInfo("test", "application/octet-stream", 100_000));
    private final Multi<byte[]> fileContentSource = Multi.createFrom().emitter(emitter -> {
        for (int i=0; i<100_000; ++i) emitter.emit(new byte[] {(byte)i});
        emitter.complete();
    });

    @GET
    public Multi<byte[]> streamDynamicContent() {
        return fileInfoSource
            .onItem()
            .transformToMulti(fileInfo ->
                RestMulti.fromMultiData(fileContentSource)
                .header("Content-Type", fileInfo.contentType)
                .header("Content-Length", Long.toString(fileInfo.size))
                .header("Content-Disposition", "attachment; filename=\"" + fileInfo.name + "\"")
                .build()
            );
    }
}
```

Requesting that endpoint gives the following exception: 

```
java.lang.IllegalStateException: Negotiation or dynamic media type not supported yet for Multi: please use the @Produces annotation when returning a Multi
```

But I cannot use `@Produces` as I do not know the content-type at compile time. How to solve this?

**Comment by geoand** [comment]
@sven-geisenhainer doesn't the example from the docs:

```java
@Path("logs")
public class Endpoint {

    interface SomeService {
        Uni<SomeResponse> get();
    }

    interface SomeResponse {
        Multi<byte[]> data;

        String myHeader();
    }

    private final SomeService someService;

    public Endpoint(SomeService someService) {
        this.someService = someService;
    }

    @GET
    public Multi<String> streamLogs() {
        return RestMulti.fromUniResponse(someService.get(), SomeResponse::data, (r -> Map.of("MyHeader", List.of(r.myHeader()))));
    }
}
```

cover your use case?

**Comment by sven-geisenhainer** [comment]
@geoand Unfortunately no because that example requires to know the content-type in advance in order to set a header map like `Map.of("Content-Type", List.of(retrievedContentType))`, but I need to obtain it from another reactive source, see my example above. What about that exception - are there plans to add the missing support?

**Comment by geoand** [comment]
Isn't that the same exact case as the example?

It's getting a header from a downstream service.

**Comment by sven-geisenhainer** [comment]
@geoand Oh sorry, yes this perfectly works, didn't get the idea behind that code, thank you for persistently pointing me towards the right solution!

**Comment by geoand** [comment]
Thanks for checking!

As you found it confusing, do you have any pointers of how the example could be improved to be clearer?

**Comment by sven-geisenhainer** [comment]
@geoand I stumbled over that exception message "Negotiation or dynamic media type not supported yet for Multi: please use the @Produces annotation when returning a Multi" that actually is not correct as there is a working solution, so at least a better message would be helpful like "Use RestMulti.fromUniResponse for dynamic media type instead". The sample code is perfectly working, was my laziness to not carefully enough reading it. Thanks again!

**Comment by geoand** [comment]
That's a great suggestion, thanks!
