### ISSUE TITLE
Devmode reload broken, NPE in `io.q.deployment.dev.ClassComparisonUtil` - "Cannot invoke "org.jboss.jandex.ClassInfo.flags()" because "old" is null"

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#28387]
### Describe the bug

Suddenly, the below has started happening. This is only in the last few days, and I'm not sure if I can recall any change which prompted it:

```java
     13:26:36 ERROR traceId=575186d570bcca1e91df6c43c102e6c5, parentId=, spanId=6f2a1952011172f6, sampled=true [io.qu.de.de.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Failed to replace classes via instrumentation: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.flags()" because "old" is null
        at io.quarkus.deployment.dev.ClassComparisonUtil.isSameStructure(ClassComparisonUtil.java:23)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:497)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:436)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

What is interesting is that this only seems to happen when launched via `./gradlew quarkusDev`
If I launch Quarkus by clicking "Start" in IntelliJ through the IDE launcher, it doesn't happen

Unfortunately, attaching a reproducer may be hard because the codebase isn't open-source and I'm not sure how to minimize it while removing all confidential code and keeping the same behavior 🙁 

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22622.601]

### Output of `java -version`

18

### Quarkus version or git rev

2.13.0-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle v7.5.1

**Comment by geoand** [comment]
Very weird. I don't see how `old` can be `null` here, although it would be trivial to guard against this case.

**Comment by GavinRay97** [comment]
This is unfortunately still breaking devmode for the folks on our team =/
(Our dev flow consists of manually stopping and starting with `./gradlew quarkusDev` after each edit)

I thought maybe upgrading to v3.0 would fix it but no such luck

I can try to make the PR to guard against the NPE, but do you think that'd fix it @geoand 
or is there potentially a bigger issue at play here?

What is really a bummer is that I can't share a reproducer because this is one of the few projects I work on that is proprietary

**Comment by geoand** [comment]
There could certainly be a bigger issue at play, but we can try the guard and see if we get lucky 🙂

**Comment by GavinRay97** [comment]
Unfortunately the NPE guard pushes the problem down the stack, now it moves into the Devmode process:

```SH
> Task :app:quarkusDev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:quarkusDev'.
> Failed to run

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:quarkusDev'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:144)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
....
Caused by: org.gradle.api.GradleException: Failed to run
        at io.quarkus.gradle.tasks.QuarkusDev.startDev(QuarkusDev.java:324)
```

**Comment by geoand** [comment]
Lovely... :(

**Comment by GavinRay97** [comment]
Yeah, let me try swapping around some gradle versions in `gradle wrapper` file and see if it makes any difference?

**Comment by GavinRay97** [comment]
Okay, so I have tested the following versions:
- `Gradle 7.6`
- `Gradle 8.0 RC2`

Both result in identical behavior, RIP 😢 

My guess this is maybe due to 1 of 2 things:
- The fact that we have a multi-module build, with a `buildSrc` fold. Our project is setup like below
- The fact that we have some Gradle knobs tuned to improve compile times

Our project structure is as:
```
/buildSrc
/lib-1
/lib-2
/quarkus-app
```

And Gradle config is:
```properties
# org.gradle.caching=(true,false)
# When set to true, Gradle will reuse task outputs from any previous build, when possible, resulting in much faster builds
org.gradle.caching=true
#
# org.gradle.configureondemand=(true,false)
# Enables incubating configuration on demand, where Gradle will attempt to configure only necessary projects. Default is false.
org.gradle.configureondemand=true
#
# org.gradle.parallel=(true,false)
# When configured, Gradle will fork up to org.gradle.workers.max JVMs to execute projects in parallel.
# To learn more about parallel task execution, see the section on Gradle build performance. Default is false.
org.gradle.parallel=true
#
# The org.gradle.jvmargs Gradle property controls the VM running the build.
# It defaults to -Xmx512m "-XX:MaxMetaspaceSize=256m"
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Xverify:none \
                   -XX:+UseParallelGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8 \
                   --add-opens=java.base/java.lang=ALL-UNNAMED \
                   --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
                   --add-opens=java.base/java.nio=ALL-UNNAMED
#
# https://kotlinlang.org/docs/whatsnew17.html#a-new-approach-to-incremental-compilation
kotlin.incremental.useClasspathSnapshot=true
```

I'm not really sure what to do, maybe try to restructure the whole repo from a fresh app into a single build folder 🤔

**Comment by geoand** [comment]
cc @aloubyansky in case he has any ideas

**Comment by GavinRay97** [comment]
Oh wow, I figured out what it was!!!

We have a custom Application entrypoint
Deleting this makes it work.

It also seems like some of our code was getting run twice (IE some log statements).
Very strange

```kt
@QuarkusMain
object Application {

    val IS_PRODUCTION = ProfileManager.getActiveProfile().equals(LaunchMode.NORMAL.defaultProfile)
    const val OTEL_DB_STMT_SANITIZER_ENABLED = "otel.instrumentation.common.db-statement-sanitizer.enabled"

    @JvmStatic
    fun main(args: Array<String>) {
        Quarkus.run(MyApp::class.java, ::exitHandler, *args)
    }

    @JvmStatic
    fun exitHandler(exitCode: Int, cause: Throwable) {
        val logger = Logger.getLogger(Application::class.java)
        logger.debugf("Shutting down with exit code %s", exitCode)
        if (logger.isTraceEnabled) {
            logger.tracef(RuntimeException("Shutdown Stack Trace"), "Shutdown triggered")
        }
        exitProcess(exitCode)
    }

    class MyApp : QuarkusApplication {

        // Allow disabling the OpenTelemtry SQL sanitizer, which strips all whitespace and values from SQL statements
        // Useful for debugging, but not recommended to be set to "false" for production
        val dbStmtSanitizerEnabled: String

        init {
            val config = ConfigProvider.getConfig()
            val enabled = config.getValue(OTEL_DB_STMT_SANITIZER_ENABLED, String::class.java)
            dbStmtSanitizerEnabled = enabled ?: "false"
        }

        override fun run(vararg args: String): Int {
            init()
            Quarkus.waitForExit()
            return 0
        }

        // Start
        private fun init() {
            System.setProperty(OTEL_DB_STMT_SANITIZER_ENABLED, dbStmtSanitizerEnabled)
        }
    }
}
```

**Comment by geoand** [comment]
That is super weird indeed

**Comment by GavinRay97** [comment]
Yeah that definitely gets my "strangest Quarkus bug I've ever encountered" trophy 🏆 🤣

**Comment by aloubyansky** [comment]
@GavinRay97 do you know on which class it fails and from which dependency/location that class is coming from?
Another possible workaround would be to disable instrumentation for dev mode.

**Comment by GavinRay97** [comment]
Unfortunately it will fail for what seems to be most any of our classes that touch the web routes

> Another possible workaround would be to disable instrumentation for dev mode.

How would we do this?

**Comment by geoand** [comment]
> How would we do this?

`quarkus.live-reload.instrumentation=false` (which is the default however)

**Comment by GavinRay97** [comment]
Ah we have `quarkus.live-reload.instrumentation=true` so maybe that comes into play too?
I also thought maybe since the `@QuarkusMain` is in Kotlin it might make an impact but I'm not sure about that one

**Comment by geoand** [comment]
> Ah we have quarkus.live-reload.instrumentation=true so maybe that comes into play too?

Perhaps. The reason we have that disabled by default is that we did on occasion see weird things that we could not explain.

> I also thought maybe since the @QuarkusMain is in Kotlin it might make an impact but I'm not sure about that one

Probably less likely, but still not impossible

**Comment by GavinRay97** [comment]
Ah, so `live-reload.instrumentation` is much like Einstein's `Spooky Action at a Distance` is what you're saying? 😅

**Comment by geoand** [comment]
Hahaha.

It shouldn't be because conceptually it does not do anything weird, but 🤷🏼

**Comment by geoand** [comment]
Let's close for now as there is nothing we can currently do
