### ISSUE TITLE
Smallrye-OpenAPI: Don't produce any CORS headers by default in production when CORS is disabled

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#28397]
### Description

Currently, when Smallrye-OpenAPI is included in the application, and [CORS filters](https://quarkus.io/guides/http-reference#cors-filter) are not enabled, the endpoint returning the OpenAPI definitions will automatically add wildcard CORS headers to its responses, effectively silencing browser CORS errors without actually securing CORS.

Even though this is only for a read-only, theoretically safe OpenAPI endpoint, this is admittedly a questionable practice on paper. To the point that we're [warning about CORS filters needing to be enabled in the documentation](https://quarkus.io/guides/openapi-swaggerui#cross-origin-resource-sharing) and logging about it at info level on startup (#28377), partly because it's not a best practice and partly because vulnerability detection tools would otherwise complain about it.

Since the log message is annoying, and the general opinion seems to be that wildcard CORS headers are insecure, maybe we should stop doing that?

In production mode, we would simply not add any CORS header when there's no CORS configuration. Some users, depending on their use case, would get CORS errors in their browser, which would lead them to look for information about CORS in Quarkus, and hopefully to configuring CORS properly. Whether or not they do that, their application would be, in the worst case, just as secure as it is now.

Because some users would get CORS errors in their browser, this is a breaking change and must been planned carefully (next major?).

See #28377 / #28384 for the full conversation.

### Implementation ideas

In the next major of Quarkus, I would:

* Change `io.quarkus.smallrye.openapi.runtime.OpenApiHandler` to not add any CORS headers by itself **in production mode**, and let Vert.x take care of that if CORS is configured (`quarkus.http.cors`).
* Remove the (now irrelevant) log on startup: https://github.com/quarkusio/quarkus/blob/1f63436a8b2d94c7dd21ea31bc8c16a69dd08e47/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiRecorder.java#L47-L49
* Add an entry to the migration guide ("you now need to configure CORS if requesting the OpenAPI definition from another domain in your browser, as the INFO message has been telling you since forever")
* Maybe update the [CORS documentation](https://quarkus.io/guides/http-reference#cors-filter) and [warning about CORS filters in the Smallrye-OpenAPI documentation]https://quarkus.io/guides/openapi-swaggerui#cross-origin-resource-sharing) to mention the symptoms we'd expect if CORS restrictions become a problem for the OpenAPI endpoint, and provide a few examples of CORS policies would solve that in the specific case of the OpenAPI endpoint.

**Comment by sberyozkin** [comment]
I thought it could be a problem removing it as it is in the product, but if we look at removing it as fixing the security bug then it should be ok - removing it won't affect the users running and accessing Open API on the local host, and if it goes multi-domain then it is a risk that needs to be eliminated, so I think we should be fine with removing it for 2.14.0.CR1

**Comment by yrodiere** [comment]
@sberyozkin I understand your concern, that's why I was merely suggesting doing this in the next major of Quarkus.

Also yes, I agree that we could consider this a security vulnerability, in which case backwards-incompatible changes are more acceptable.

**Comment by stuartwdouglas** [comment]
What is the actual perceived risk here?

Basically the only scenario where I can see a potential issue is:

1) OpenAPI is hidden behind authentication
2) A malicious site that a logged in user was tricked into visiting could potentially then send a cross origin request to get the openapi document, which could potentially expose internal information. 

On the flip side disabling this will likely break a lot of users. 

If 1) is not true (which is not the case by default) then IMHO there is no security risk here, as the attacker can just hit the endpoint directly without needing to go through all the effort of tricking a user into visiting their malicious site.

**Comment by maxandersen** [comment]
@stuartwdouglas if we have #29626 in with same site origin enabled is it then not ok to remove default * ?

**Comment by sberyozkin** [comment]
@maxandersen The same origin check done by Stuart is a secure version of `*` when it comes to checking such same origin requests (`*` also works, but yes, for the 3rd party origins as well), so disabling `*` by default won't affect it

Let me close this issue though as #29626 fixed it

**Comment by sberyozkin** [comment]
@maxandersen I'll rebase other PRs against this one

**Comment by yrodiere** [comment]
@sberyozkin I'm not really following so I'll leave y'all decide what's best. Does this mean we'll still get that annoying warning on startup, though? I can't tell for sure what's more secure, but that warning is definitely annoying and (worse) confusing :/

But I wanted to point out that you already closed this issue, while there is still a PR that is supposed to fix it (https://github.com/quarkusio/quarkus/pull/29666) and that hasn't been merged yet. That seems strange?

**Comment by sberyozkin** [comment]
Hey @yrodiere, I honestly have no idea why I closed this issue, I guess I got confused with all the CORS activities going on around,  oh, yes, I meant to close #29542 instead which I did now, thanks very much for keeping an eye, but yes, the problem is meant to be fixed anyway with #29666, I just need an approval

**Comment by sberyozkin** [comment]
Hi @stuartwdouglas, missed your comment, right, your bullets 1 & 2 are describing the risk precisely if the authentication is session cookie based.

>On the flip side disabling this will likely break a lot of users.

I haven't seen any side-effects in devmode, I tried it with the PR.
And if it is prod - then users should actually be setting CORS Filter anyway which will cover OpenApi paths as well. So removing this wildcard window at the OpenApi level will not (should not) affect the user experience. 

This is why trying to get the PR for 2.16.0.CR1 will give us a good chance to see what kind of side-effects can be there - if all we'll hear is that it no longer works in production when we try to access from multiple sites then it won't be a real issue - CORS filter is there to help

**Comment by stuartwdouglas** [comment]
> Hi @stuartwdouglas, missed your comment, right, your bullets 1 & 2 are describing the risk precisely if the authentication is session cookie based.
> 
> > On the flip side disabling this will likely break a lot of users.
> 
> I haven't seen any side-effects in devmode, I tried it with the PR. And if it is prod - then users should actually be setting CORS Filter anyway which will cover OpenApi paths as well. So removing this wildcard window at the OpenApi level will not (should not) affect the user experience.

Of course you would not see any effects in dev mode. You need to actually be running this as part of a multi domain system with multiple origins to see things break.

Forcing users to now configure CORS is a breaking change, it needs to be documented in the migration guide at the very least.

**Comment by sberyozkin** [comment]
@stuartwdouglas 

>Of course you would not see any effects in dev mode. You need to actually be running this as part of a multi domain system with multiple origins to see things break.

Sure, but I think we agree now accepting all origins by default is not safe, at least Quarkus should not do it itself for its own CORS filter - which means users working with such multiple origins would configure CORS filter in any case with wildcard or specific origins, whatever they prefer, and by configuring CORS filter they will take care of OpenAPI queries as well.

>Forcing users to now configure CORS is a breaking change, it needs to be documented in the migration guide at the very least.

FYI, as far as CORS filter not supporting all origins by default any longer is now mentioned at https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16#no-wildcard-origin-support-by-default-for-cors-filter
(I can expand as needed). I hope there won't be much pushback, same origins would not be affected, it is a common sense now not to open to all origins, so it should be fine starting from 2.16.0.CR1

But #29666 is not merged yet, so nothing to doc in the migration guide yet :-). I'll do it once it is merged. If you agree that OpenApiHandler CORS configuration should be handled by CORS filter then please approve.  Makes sense to use a single source of CORS config IMHO.

**Comment by sberyozkin** [comment]
@stuartwdouglas Yes, now, by default CORS filter has to be configured anyway when multiple origins are involved, and because of that, #29666 now simply removes the redundant code :-), as it will never be activated. It is totally safe to be removed I believe
