### ISSUE TITLE
QuarkusTest**Callback not executed when running QuarkusIntegrationTest

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#28402]
### Describe the bug

When running a `@QuarkusIntegrationTest` the registered QuarkusTest**Callback are not executed. 

Setup:

```
integrationTest
|-src
|   |-MyIntegrationTest.java  (extends MyQuarkusTest)
|-resources
    |-META_INF
        |-services
            |- io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback  (same as in test)

test
|-src
|   |-MyQuarkusTest.java
|-resources
    |-META_INF
        |-services
            |- io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback

```

### Expected behavior

The test callback should also be executed when running integration tests.

### Actual behavior

When running a `@QuarkusIntegrationTest` the registered QuarkusTest**Callback are not executed. 

### Quarkus version or git rev

2.13.0.Final

**Comment by geoand** [comment]
These indeed are not taken into account, but I am not sure if they actually should be. 

WDYT @Sgitario @famod ?

**Comment by Sgitario** [comment]
I don't see any technical limitation to not execute them, so we could support this.

**Comment by geoand** [comment]
Yeah, technically we could, no question. My point is more of compatibility... We have not done this so far and if we start doing it now, we could potentially break a lot of people's tests.

**Comment by HerrDerb** [comment]
Most of the people will have the services file in the `test` package.  One hsould need to define a seperate one for the `integrationTest` package. This way, they would not interfere with the different tests stages, which probably defuses the risk of braking existing tests. Would that be possible?

**Comment by geoand** [comment]
That only works for Gradle :)

**Comment by HerrDerb** [comment]
Hm well then how about a quarkus test property? `quarkus.testcallbacks.enableForIntegrationTests` or something like that?

**Comment by geoand** [comment]
Yeah, we could likely introduce something like that, but it would have to be disabled by default.

**Comment by HerrDerb** [comment]
That would serve me perfect :)

**Comment by geoand** [comment]
@Sgitario WDYT?

**Comment by Sgitario** [comment]
It sounds a good idea to me as well, and it's safer way to introduce this. 
But I would add this new property as part of the existing `TestConfig`, something like `quarkus.test.enable-callbacks-for-integration-tests`.

**Comment by geoand** [comment]
Yeah, definitely.

**Comment by geoand** [comment]
Would you like to look into this @Sgitario ?

**Comment by HerrDerb** [comment]
Works like a charm 👍👌 Thank you

**Comment by geoand** [comment]
👌
