### ISSUE TITLE
Adding quarkus-smallrye-jwt extension to Lambda Results in 404

### ISSUE THREAD

**Issue by luketn** [quarkusio/quarkus#28418]
### Describe the bug

When working on a Java Lambda project, I added the smallrye extension for JWT validation, intending to validate a JWT header in the HTTP request headers passed from an ALB listener event.
The Lambda tests were passing until I added this extension, whereupon they started failing with a 404 error.

### Expected behavior

You can run unit tests on Lambdas after adding the quarkus-smallrye-jwt extension.

### Actual behavior

404 error:
```
2022-10-06 12:33:25,829 ERROR [io.qua.test] (Test runner thread) Test DefectHandlerTest#testDefectLambda() failed 
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.
```
(the unit test invokes the lamdba test endpoint passing an ALB event like this:
```

)

### How to Reproduce?

Build a Quarkus lambda handler, with a unit test for ALB events, e.g. 

```
ApplicationLoadBalancerRequestEvent input = new ApplicationLoadBalancerRequestEvent();
        input.setPath("/webapp/config/fruit");
        input.setQueryStringParameters(Map.of("name", "blueberry"));
        input.setHttpMethod("GET");

        given()
                .contentType("application/json")
                .accept("application/json")
                .body(input)
                .when()
                .post()
                .then()
                .statusCode(200)
                .body(containsString("Common Blueberry"))
                .log().all();
```

Check the test is passing.

Add the extension quarkus-smallrye-jwt.

See the test fails with a 404 error.

### Output of `uname -a` or `ver`

Darwin ip-192-168-1-4.eu-central-1.compute.internal 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.13.8.1 (build 11.0.13+8-LTS, mixed mode)

### GraalVM version (if different from Java)

Not used.

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/lthompson/tools/apache-maven-3.8.1 Java version: 11.0.13, vendor: Amazon.com Inc., runtime: /Users/lthompson/Library/Java/JavaVirtualMachines/corretto-11.0.13/Contents/Home Default locale: en_AU, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

### Additional information

_No response_

**Comment by sberyozkin** [comment]
@luketn I think it can't work because `quarkus-smallrye-jwt` provides `HttpAuthenticationMechanism` and brings `vertx` (HTTP) which will conflict with amazon-lambda. Also as far as I understand, JWT token is already verified in such cases, if not then have a look at https://quarkus.io/guides/amazon-lambda-http#custom-security-integration, CC @patriot1burke

**Comment by sberyozkin** [comment]
Closing it as not a bug. @luketn If you'd like to use `smallrye-jwt` to verify the token, assuming the token has not already been verified, then please use `smallrye-jwt` directly (but not quarkus-smallrye-jwt)

**Comment by luketn** [comment]
@sberyozkin FYI - I'm continuing to use the quarkus-smallrye-jwt extension with a workaround as I like all of it's behaviour and functionality except for the web server. 

I found a workaround by adding this property to the lambda's application.properties file:
```
quarkus.http.host-enabled=false
```

Essentially this disables the dev mode web server that would have been started by the dependency on vertx http.

I say this is a workaround, because I would still prefer a version of a JWT quarkus extension which did not start a web server in dev mode (for Lambdas and perhaps other non-web-server use-cases like command line apps).

Works a treat though, and I can resume testing the lambda using the recommended approach.
