### ISSUE TITLE
Nested required properties with dot in ConfigItem's name lead to compilation error

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#28430]
### Describe the bug

If we have two configuration classes
```java
@ConfigRoot(name = "my-config")
public class MyConfigs {
  /**
   * Named configurations
   */
  @ConfigItem(name = ConfigItem.PARENT)
  Map<String, MyConfig> namedConfigs;
}
```
and
```java
@ConfigGroup
public class MyConfig {
  /**
   * The all-mighty fooBar config
   */
  @ConfigItem(name = "foo.bar", defaultValue= "baz")
  String fooBar;
}
```

The compiler will complain when an application using the extension is compiled.

### Expected behavior

No compiler error

### Actual behavior

Compilation fails with

```bash
...
Caused by: java.util.NoSuchElementException: SRCFG00014: The config property quarkus.my-config."named".foo.foo.bar is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:294)
...
```

### How to Reproduce?

Steps to reproduce the behaviour:
1. checkout https://github.com/turing85/quarkus-extension-config-bug
2. run `./mvn install`

### Output of `uname -a` or `ver`

N/A

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.13.1.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

This is caused by:
- the `"."` in `@ConfigItem(name = "foo.bar", defaultValue= "baz")` in `MyConfig.java` and
- the `@ConfigItem(name = ConfigItem.PARENT) Map<String, MyConfig> namedConfigs;` in `MyConfigs.java`.

If we replace all occurrences of `foo.bar` with `fooBar`, everything works as expected.

**Comment by radcortez** [comment]
This has been fixed in SmallRye Config `@ConfigMapping`. This is the new recommended way to configure extensions:
https://quarkus.io/guides/writing-extensions#configuration

I'll probably won't fix this on the current mechanism, so it becomes an additional incentive to move to the new way :)
