### ISSUE TITLE
quarkus.args not work with gradle and quarkus 2.13.0

### ISSUE THREAD

**Issue by deblockt** [quarkusio/quarkus#28443]
### Describe the bug

I try to write my own main like that:
```
@QuarkusMain
public class Main {
    public static void main(String... args) {
        System.out.println(args.length);
    }
}
```

And execute it using `quarkus cli` like that 
> quarkus dev --verbose -- param
or
> quarkus dev --verbose -Dquarkus.args="param"

### Expected behavior

The main is executed and display "1"

### Actual behavior

The main is executed and display "0"

### Output of `uname -a` or `ver`

Darwin --- 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

### Output of `java -version`

1.17

### GraalVM version (if different from Java)

2.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.4.2

### Additional information

In verbose mode I can see that parameter is set on quarkus.args but seem not used:

> gradlew --console=rich -DquarkusRegistryClient=true quarkusDev -Dquarkus.args='param' -Dio.quarkus.devmode-args=/var/folders/4q/z24jsww13cv73x6jqyqlj_880000gn/T/quarkus-dev2169293274555449898.txt

**Comment by glefloch** [comment]
Thanks for reporting this @deblockt I will have a look into it.

**Comment by geoand** [comment]
@glefloch any idea what's going on?

**Comment by glefloch** [comment]
Yes I think we just don't forward system property from the gradle process to the quarkus dev process. It should be easy to fix

**Comment by jacobdotcosta** [comment]
I can take a look at this issue, it seems to be an affordable first issue for me after reading @glefloch comments.

**Comment by glefloch** [comment]
Yes you can, I gave it a try a week a go, but it wasn't as easy as I thought, I tried declaring gradle system properties to the quarkus process system properties but it had no effects :/

**Comment by jacobdotcosta** [comment]
It isn't the _affordable first issue_ I was expecting 😃 as I've made several tests and it seems that no project context is reaching the QuarkusDev task. I'll keep investigating.

**Comment by jacobdotcosta** [comment]
Finally have it 🎉 !!! Will try creating a test case for this and prepare a PR.

**Comment by geoand** [comment]
Awesome, thanks!

**Comment by geoand** [comment]
I think `--` is a shell thing that allows you pass an entire string
