### ISSUE TITLE
Application startup problems when running tests via the @QuarkusTest annotation

### ISSUE THREAD

**Issue by poker303** [quarkusio/quarkus#28448]
### Describe the bug

Reservation: I'm not sure if this's a bug or a work limitation of the annotation @QuarkusTest. This is our first big project on this framework, so please don't judge strictly.

My team and I write a project on Kotlin, using Quarkus as the main framework, and Gradle as the main build system. We have an application that we are currently covering with tests. The problem arises when we write REST-http tests to our EndPoints. The tests work out correctly, but only when we run them, with the application running. But if we turn off the application and put the @QuakusTest annotation, which, according to the documentation, should run the application itself before running the tests, an exception occurs:

"Connection refused: no further information
java.net.ConnectException: Connection refused: no further information"

Please answer - did we understand correctly that @QuakusTest annotation allows to run tests without running the main application, and if not - is there any other way to run tests without running the application and preferably on some kind of abstract database so that the test call and its operation do not affect the main DB.

### Expected behavior

Automatic launch of the application before the tests themselves start working when they are called. The actions performed by the tests occur with a virtual, not a real database.

### Actual behavior

The tests work correctly when the application is turned on manually. But when the application is turned off, when trying to launch, they start to fall with an exception:

"Connection refused: no further information
java.net.ConnectException: Connection refused: no further information"

### How to Reproduce?

A link to our small test project on github, on which we tested the work of a real project: 
https://github.com/Bazalii/Interactive-map

### Output of `java -version`

Java 17, Kotlin 1.6.21

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

We searched Internet for information about this problem, but the only thing we found was a bit similar question on StackOverflow, where the solution was - to connect "io.quarkus:quarkus-resteasy-reactive-jackson". We tried this option, but it didn't help(
![image](https://user-images.githubusercontent.com/70962483/194545657-8593fdcf-e3aa-41c8-ba26-3718c9c74ce5.png)

**Comment by geoand** [comment]
Hi,

Thanks for the thorough report and for using Quarkus in general :).

The problem is that your tests are using port `8080` but Quarkus uses port `8081` in [testing](https://quarkus.io/guides/getting-started-testing#controlling-the-test-port). 
Furthermore, when using Quarkus and RestAssured, you don't need to set the port as Quarkus does that [automatically](https://quarkus.io/guides/getting-started-testing#restassured).

`@QuarkusTest` always starts the Quarkus application, it can't be used to test an already running application. 
If you need to run tests against an already running application, you'll need to use `@QuarkusIntegrationTest` - see [this](https://quarkus.io/guides/getting-started-testing#executing-against-a-running-application) for more details.

**Comment by Bazalii** [comment]
> Hi,
> 
> Thanks for the thorough report and for using Quarkus in general :).
> 
> The problem is that your tests are using port `8080` but Quarkus uses port `8081` in [testing](https://quarkus.io/guides/getting-started-testing#controlling-the-test-port). Furthermore, when using Quarkus and RestAssured, you don't need to set the port as Quarkus does that [automatically](https://quarkus.io/guides/getting-started-testing#restassured).
> 
> `@QuarkusTest` always starts the Quarkus application, it can't be used to test an already running application. If you need to run tests against an already running application, you'll need to use `@QuarkusIntegrationTest` - see [this](https://quarkus.io/guides/getting-started-testing#executing-against-a-running-application) for more details.

Sorry for distracting, but could you please clarify to which actual endpoint in our configuration requests should be sent? Is it http://localhost:8081/mapins ? If so, we get such response: _GraphQL Schema not generated. Make sure you have a GraphQL Endpoint. Go to https://quarkus.io/guides/microprofile-graphql to learn how_. When we exclude the path from requests for autoconfiguration we get the same result as in the case when we send requests to http://localhost:8081/ - responses are just empty. We have already tried to use using quarkus.http.test-port but result are the same...

**Comment by geoand** [comment]
I propose having a look at https://github.com/quarkusio/quarkus-quickstarts/tree/main/microprofile-graphql-quickstart and / or https://github.com/quarkusio/quarkus-quickstarts/tree/main/microprofile-graphql-client-quickstart
