### ISSUE TITLE
Quarkus Mongodb Panache: How to get array from collection using query projection?

### ISSUE THREAD

**Issue by sag1** [quarkusio/quarkus#28459]
### Describe the bug

I have a collection as below. I would like to get only countries value based on email and offers. I tried to use Query projection as described [here](https://quarkus.io/guides/mongodb-panache#query-projection)

```
{
  "_id": {
    "$oid": "62a0ba9542657e5007b64c96"
  },
  "email": "abcde@xxxx.com",
  "name": "rrr",
  "offers": [
    {
      "module": "Streaming",
      "countries": [
        "India",
        "Thailand",
        "China"
      ],
      "rights": "WRITE"
    }
  ]
}
```

I have created a DTO for projection as below
```
@ProjectionFor(VideoUser.class)
public class UserCountry {
    public List<String> countries;
}
```

My query is
```
PanacheQuery<UserCountry> countryQuery = find("email like ?1 and offers.module like ?2", email, offerName).project(UserCountry.class);
List<String> countries = countryQuery.stream().map(UserCountry::getCountries).findFirst().get();
System.out.println(countries);
```

I am facing NullPointerException on **countryQuery.stream().map(UserCountry::getCountries).findFirst().get();** Can anyone help me ? How to do it ?

### Quarkus version or git rev

2.11.1.Final

**Comment by sag1** [comment]
found a solution in another way

**Comment by parthd-fens** [comment]
Can you please share the solution ?
