### ISSUE TITLE
CookieParam is not correctly handled by the default Resteasy Reactive converter

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#28453]
### Describe the bug

If I have `@CookieParam("csrftoken") Cookie token` then `Cookie token` will have its `name` set to the value of the `csrftoken` cookie and the value will remain empty.

I'm sorry if I got it wrong, but after tracing the request and debugging the test endpoint it does look like the case.

### Expected behavior

 Given `@CookieParam("csrftoken") Cookie token`, the `Cookie` name should be set to `csrftoken`, and value to the actual cookie value

### How to Reproduce?

Check out #28383, go to `integration-tests/csrf-reactive`, do `mvn test -Dtest=CsrfReactiveTest#testCsrfTokenMultipart`, have a breakpoint in `TestResource#postCsrfTokenMulltipart` to confirm

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28464 takes care of the issue. Seems weird that we never encountered a case of using `Cookie`  in a JAX-RS method...

**Comment by sberyozkin** [comment]
Yeah, interesting, I suppose it shows manually dealing with cookies is done rarely

**Comment by geoand** [comment]
Very likely!

**Comment by FroMage** [comment]
Well, cookies work, but they're usually deserialised to `String` ;)
