### ISSUE TITLE
Move MongoDB Client Tracing to OpenTelemetry

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#28473]
### Description

The MongoDB Client Extension uses OpenTracing for Tracing. We need to move it to OpenTelemetry because CNCF has archived OpenTracing: https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project.

**Comment by radcortez** [comment]
Sure. Updated the description.

**Comment by loicmathieu** [comment]
Maybe we should support both not ?
Or does Quarkus plan to drop support to OpenTracing ?

**Comment by radcortez** [comment]
Yes, the plan is to drop OpenTracing. As pointed out here: https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project, OpenTracing is archived by CNCF.

We have problems fixing current issues because no new releases are being cut. In some cases, we had to fork the code and release it in a different GAV. We want to encourage users to move to OpenTelemetry, since OpenTracing is dead now.

**Comment by loicmathieu** [comment]
@radcortez if we plan to drop support for Quarkus so OK for me to move the current MongoDB support from OpenTracing to OpenTelemetry. There is a command listener used to trace each MongoDB command (request / query) here: https://github.com/quarkusio/quarkus/blob/main/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/tracing/MongoTracingCommandListener.java it currently delegates to a command listener from the OpenTracing contrib MongoDB instrumentation. If such instrumentation exist for OpenTelemetry it should be updated to use it.

**Comment by radcortez** [comment]
There is some instrumentation available here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/mongo, but I didn't look into it yet.

**Comment by loicmathieu** [comment]
@radcortez these are based on a Java agent which is a different strategy that should not need anything on our side but as it required JVMTI will not work in native.

**Comment by loicmathieu** [comment]
It also uses a command listener so we may be able to use it like we did for OpenTracing, I don't know why it is for 3.1 maybe it can also be used for the version 4, it needs to be tested anyway.

**Comment by sifraden** [comment]
Hi guys, do you have any updates on this one?

**Comment by brunobat** [comment]
Not yet but I moved the implementation target to next quarter, @sifraden

**Comment by jyemin** [comment]
FYI, I've tested the OpenTelemetry agent's MongoDB driver instrumentation, and it works with the latest release of the driver (4.10 at the time I tested). 

CC @evanchooly

**Comment by vkn** [comment]
Hi @radcortez, since you are the assignee, maybe you could review [PR](https://github.com/quarkusio/quarkus/pull/40191)? thx

**Comment by loicmathieu** [comment]
Fixed by #40191
