### ISSUE TITLE
Testing and packaging fails with ClassNotFoundException: io.quarkus.deployment.steps.ConfigDescriptionBuildStep

### ISSUE THREAD

**Issue by mthmulders** [quarkusio/quarkus#2847]
**Describe the bug**
I've followed the [Getting Started Guide](https://quarkus.io/guides/getting-started-guide). Both testing and packaging fail.

**Expected behavior**
Both packaging and testing succeed.

**Actual behavior**
The test phase fails with

```
[ERROR] testHelloEndpoint  Time elapsed: 0.006 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingResourceTest]: java.lang.ClassNotFoundException: io.quarkus.deployment.steps.ConfigDescriptionBuildStep
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.deployment.steps.ConfigDescriptionBuildStep
Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.steps.ConfigDescriptionBuildStep
```

Skipping tests doesn't work either, because the package phase fails with a similar message:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.16.1:build (default) on project getting-started: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: io.quarkus.deployment.steps.ConfigDescriptionBuildStep
```

**To Reproduce**
1. `git clone git@github.com:mthmulders/quarkus-config-description-build-step.git`
2. `mvn test` or `mvn package`
3.  There is no step 3 ;-)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
> Darwin leonardo 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
> java version "1.8.0_212"
> Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
> Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
 - GraalVM version (if different from Java): 
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (build 1.8.0_212-20190420112649.buildslave.jdk8u-src-tar--b03)
> OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)
 - Quarkus version or git rev: 
> 0.16.1

**Comment by mthmulders** [comment]
The file `quarkus-build-steps.list` in quarkus-core-deployment-0.16.1.jar:/META-INF contains a line with `io.quarkus.deployment.steps.ConfigDescriptionBuildStep`, but in the 0.16.1 source code there is no Java source file with that name. It does exist in master, though; it was introduced in comit [adc2557e](https://github.com/quarkusio/quarkus/commit/adc2557e642a26394a495277c041261068c5499e), one day _after_ the 0.16.1 tag was created.

**Comment by geoand** [comment]
I just tried your example and it worked for me.
Could you also post the output of `mvn -version` please?

**Comment by mthmulders** [comment]
`mvn -version` gives

> Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Seems legit. Let's see if others on a Mac can reproduce the issue

**Comment by mthmulders** [comment]
Also, for good measure, I've thrown away everything related to io:quarkus:*:0.16.1 in ~/.m2/repository. Just in case I would've downloaded a corrupted JAR somewhere. Retrying indeed downloads a bunch of artifacts from Maven Central, but the problem persists.

@geoand What platform are you on?

**Comment by geoand** [comment]
I'm on Linux and couldn't reproduce your issue

**Comment by mthmulders** [comment]
A few more observations:

* with `quarkus.version=999-SNAPSHOT` ([a3c12456](https://github.com/quarkusio/quarkus/commit/a3c12456)) on macOS, both `mvn test` and `mvn package` succeed (`mvn package -Pnative` does not, but the error message is clearly different from this issue)
* Inside the [oracle/graalvm-ce:19.0.2](https://hub.docker.com/r/oracle/graalvm-ce) Docker image (based on Oracle Linux Server release 7.6), both `mvn test` and `mvn package` succeed (again, `mvn package -Pnative` does not succeed, but the error message is clearly different from this issue).
* On a Windows Server 2012 box, both `mvn test` and `mvn package` succeed.

**Comment by stuartwdouglas** [comment]
I don't think this is correct "The file quarkus-build-steps.list in quarkus-core-deployment-0.16.1.jar:/META-INF contains a line with io.quarkus.deployment.steps.ConfigDescriptionBuildStep"

I just downloaded it fresh and checked and it is not there. 

Is it possible you built from the tag without doing a clean first?

**Comment by mthmulders** [comment]
Well, that's strange. I had already removed all 0.16.1 artifacts from my local repo, so Maven would download a fresh copy. After that the problem persisted, and I filed this bug.
But today, I just re-did that exercise and this time, it succeeds. So I guess we can close this one.
