### ISSUE TITLE
Using QuarkusTest and QuarkusMainTest in the same package breaks in 2.13.*

### ISSUE THREAD

**Issue by ebullient** [quarkusio/quarkus#28486]
### Describe the bug

Dependabot update from 2.12.3.Final to 2.13.0.Final failed in one of my projects with an error about using `QuarkusTest` and `QuarkusMainTest` "in the same run".

This behavior change was introduced in https://github.com/quarkusio/quarkus/issues/27247

Agreed this should be doable in zulip thread: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/QuarkusTest.20and.20QuarkusMainTest/near/303196430, perhaps by treating these two types as different profiles so things are cleaned up around them.

Note that putting the two types of tests in different packages avoided this check, so I think some implied scoping is happening (which suggests "in the same run" phrasing would be a minimal improvement, if we decide the profile-esque behavior won't work).

### Expected behavior

QuarkusTest and QuarkusMainTest should not be mutually exclusive, especially not "in the same run."

### Actual behavior

https://github.com/ebullient/fc5-convert-cli/actions/runs/3175704762

```
Error:  Errors: 
Error:    Import5eToolsConvertTest.testCommandHelp(LaunchResult) » IllegalState Cannot mix both @QuarkusMainTest based tests and io.quarkus.test.junit.QuarkusTest based tests in the same run
Error:    Import5eToolsConvertTest.testIndexXmlData(TestInfo,QuarkusMainLauncher) » IllegalState Cannot mix both @QuarkusMainTest based tests and io.quarkus.test.junit.QuarkusTest based tests in the same run
Error:    Import5eToolsConvertTest.testMarkdownBook(TestInfo,QuarkusMainLauncher) » IllegalState Cannot mix both @QuarkusMainTest based tests and io.quarkus.test.junit.QuarkusTest based tests in the same run
Error:    Import5eToolsConvertTest.testMarkdownData(TestInfo,QuarkusMainLauncher) » IllegalState Cannot mix both @QuarkusMainTest based tests and io.quarkus.test.junit.QuarkusTest based tests in the same run
```

### How to Reproduce?

Check out commit c0175664809447d6354a3b5e1528b08736f42466 of https://github.com/ebullient/fc5-convert-cli, and update to 2.13.(whatever is latest).

What "fixed" the broken project: ensuring that `@QuarkusTest` and `@QuarkusMainTest` weren't both used by classes in the same package (does that count as "in the same run"?)

### Additional information

I have two (similar) CLI repos:

https://github.com/ebullient/json5e-convert-cli
https://github.com/ebullient/fc5-convert-cli

The latter failed moving up to 2.13 while the former did not. It was luck that I spotted the test package difference.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28499 should take care of the issue
