### ISSUE TITLE
Include minimum/recommended JDK version in the platform stream descriptor

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#28497]
### Description

From @rsvoboda:

>RHBQ 2.7 has a support cycle for 6+6 months, soon we will have RHBQ 2.13 and Quarkus upstream will be 2.14 (maybe 2.15 CR1) when we release RHBQ 2.13.
Each stream can have its own specifics (e.g. default Java version) and we will have multiple streams running together for a longer time.

### Implementation ideas

Include the minimum and recommended JDK version in the platform stream (extension catalog) descriptor

**Comment by ia3andy** [comment]
@gastaldi we need both minimum and recommended versions, why "or"?

**Comment by gastaldi** [comment]
@ia3andy when I created the issue I thought it would not be necessary, but now that you mention, I think both makes sense (eg. because GraalVM might not work with the latest JDK)

**Comment by ia3andy** [comment]
@gastaldi any update on this as it will need it to flow all the way down to the tooling?

**Comment by gastaldi** [comment]
We'll need to include this in the stream metadata. 
Now we need to decide if this needs to be added in the extension catalog JSON that is distributed in Maven central or in the quarkus-extension-catalog repo?

@aloubyansky any thoughts?

**Comment by aloubyansky** [comment]
We don't deploy stream metadata as part of platform releases. It's true though that we could add a Java version preference directly to https://github.com/quarkusio/quarkus/blob/main/devtools/bom-descriptor-json/src/main/resources/catalog-overrides.json under `metadata/project/properties` for example. That will end up in the platform release though, not under stream.
Stream metadata is currently provided by the registry. So if this into is to be associated with a stream, it would have to be implemented in the registry.

**Comment by gastaldi** [comment]
@aloubyansky Now that you mention I think it makes sense to have this in the platform release metadata. That would give us finer control over the recommended/minimum JDK per platform release. I'll submit a PR

**Comment by aloubyansky** [comment]
@ia3andy would that work for you?
