### ISSUE TITLE
Allow application to shutdown itself

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2851]
I'd like to have my Quarkus app shutdown upon a specific error condition. I'm calling `Application.currentApplication().stop();` but it still remains waiting in `Application#run()`, awaiting the shutdown hook thread to set the `shutdownRequested` flag.

**Comment by gastaldi** [comment]
It looks like #6498 has more information about this. Should we close this issue?

**Comment by gunnarmorling** [comment]
Sure, feel free to close it, if this requirement is tracked elsewhere.

>

**Comment by gastaldi** [comment]
@gunnarmorling thanks. Closing in favor of #6498
