### ISSUE TITLE
OpenTracing to OpenTelemetry migration guide

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#28528]
### Description

We need a howto detailing the process and best practices around migrating Quarkus applications from OpenTracing to OpenTelemetry.

**Comment by gsmet** [comment]
@brunobat still planning to work on this one? If so, let's keep it open but if not let's close it.

**Comment by brunobat** [comment]
Yes, @gsmet, this is going to happen. I already have code examples and a skeleton.
