### ISSUE TITLE
Invalid classpath entry in MANIFEST.MF

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2852]
Using that reproducer: https://github.com/vietk/QuarkusReproducer , we end up with the following entry `lib/maven.dependency.pom.xml` in the `Class-Path` entry of the `MANIFEST.MF` file of the runner.

Which is invalid and leads to the following error when trying to build the native image:
```
Error: Invalid or corrupt jarfile /.../Reproducer/application/target/application-1.0-SNAPSHOT-runner.jar
```

@stuartwdouglas WDYT would be better: Should we filter out the XML files or include just the jar files in the entry? I know some people use specific extensions for their artifacts so I'm not sure only including jar files is a good idea.

/cc @vietk

**Comment by stuartwdouglas** [comment]
I think we should just copy jar files, they are the only file type that really make sense in a Class-Path manifest entry.

**Comment by aloubyansky** [comment]
While it may make sense to include only the JARs, is it wrong though to have an XML file there? Isn't it a bug in Graal?

**Comment by gsmet** [comment]
I don't know. I don't think adding an XML file to the classpath makes sense TBH.

**Comment by aloubyansky** [comment]
Is it illegal?

**Comment by vietk** [comment]
I did not have the issue with hotspot, but I don't know if it's because it lazy loads jars (which I doubt) or it filters out non-jar file
In any case, the error reporting in GraalVm should be enhanced, took me a while to realize among all jar files in the manifest.

**Comment by aloubyansky** [comment]
That's my point. Will be good to have the Graal team comment on this.

**Comment by emmanuelbernard** [comment]
@aloubyansky I've created https://github.com/oracle/graal/issues/1417 to get to the bottom of it.

**Comment by bobmcwhirter** [comment]
I'm working on an upstream fix for this.

**Comment by bobmcwhirter** [comment]
See https://github.com/oracle/graal/pull/1418
