### ISSUE TITLE
Hibernate ORM MultipleLinesSql Support

### ISSUE THREAD

**Issue by axlernwerkstatt** [quarkusio/quarkus#2854]
**Description**
In my import.sql file, I have some complex and extensive SQL statements. For a better orientation, I would like to be able to enter SQL commands across multiple lines.

I am using quarkus 0.14.0.

**Implementation ideas**
According to [this answer](https://stackoverflow.com/questions/4674828/how-to-break-expression-into-more-lines-in-hibernates-import-sql), it is possible to use the hibernate MultipleLinesSqlCommandExtractor-attribute to activate multiple lines statements in other frameworks like Hibernate4. Yet, I haven't seen a possibility to do this in quarkus.

Is there already another way to do this that I've missed?

Otherwise, would it be possible to add this property to quarkus so that it is configurable in the application.properties?

**Comment by gsmet** [comment]
@emmanuelbernard I think it would make sense to make it our default (and not introduce a configuration knob for that).

Obvious drawback: it will break all the existing `import.sql` as they would need a semi-colon at the end of each statement.

WDYT?

**Comment by emmanuelbernard** [comment]
@gsmet we could also try a `MultipleLinesSqlCommandExtractorFallingBackToSingleLineWhenItLooksGood` but that's another soft choice algorithm you won't like :)

Still I think with the doc outside mentioning the import without `;`, it would be nice to detect obvious errors and raise an error at build time.

**Comment by FroMage** [comment]
FTR in Panache RX I made that change a few months back in order to allow table defniitions on multiple lines.

**Comment by gsmet** [comment]
@emmanuelbernard I think we are still early in the Quarkus life and it would be nice to avoid making choices we would regret.

Supporting only files with `;` makes sense IMHO as it's the standard SQL files. TBH, I was surprised we didn't need a `;` at first.

We could test if the file contains a `;` but that would be a bit fragile and would break when a `;` is introduced. And I don't think having a specific parser for that makes sense.

I would think otherwise if we were post 1.0 but now is the right time to not add technical debt and have a clean slate.

**Comment by FroMage** [comment]
@gsmet +1

**Comment by emmanuelbernard** [comment]
Ok

**Comment by Sanne** [comment]
Is there a matching HHH jira for this?

**Comment by gsmet** [comment]
@Sanne hmmm, the idea was to change the default value in Quarkus.

**Comment by Sanne** [comment]
ok, ignore me then. I assumed some work was needed in ORM upstream - in that case please link to it.

**Comment by gsmet** [comment]
@machi1990 wondering if you would be interested in taking this one? We need to push the other extractor in the config (we don't want it to be configurable for now) and we need to fix all the SQL files in the tree (and in the quickstarts tree) to add `;` at the end of the lines.

I thought I would have the time to do it but there are a lot of things to review before Wednesday and I doubt I will get to it.

**Comment by machi1990** [comment]
@gsmet I'll take a look.
