### ISSUE TITLE
Extend @RegisterRestClient capabilities

### ISSUE THREAD

**Issue by bharatnpti** [quarkusio/quarkus#28557]
### Description

**Motivation** - I want to build on top of resteasy-reactive and provide different structure of the RestClientsConfig to provide some additional capabilities

### Implementation ideas

**Current** - RestClientBuilderFactory's getInstance method throws IllegalStateException if multiple implementation of RestClientBuilderFactory is found.

**New** - Incase of multiple implementation provide the name of the class to be used via configuration and use it instead of throwing exception.

**Comment by geoand** [comment]
Can you please add some sample code showing in more detail what you are trying to do?

**Comment by geoand** [comment]
Actually, `@RegisterRestClient ` is not a Quarkus annotation, but a Microprofile annotation, so we can't really do much here unfortunately.
