### ISSUE TITLE
The default test-port is not compatible with mvnd (Maven deamon) nor parallel maven builds

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#28563]
### Description

By default, Quarkus uses `quarkus.http.test-port=8081`.
In large projects, it's common to use Maven Daemon (mvnd) or a parallel maven build to speed up the build.

These two don't work well together: when 2 quarkus modules are tested in parallel, one of them runs into a

```
Port(s) already bound: 8081: Address already in use
```

Mvnd for Quarkus projects should work out of the box.

### Implementation ideas

One solution would be to use  `quarkus.http.test-port=0` by default. But what if that takes port `8080` before the dev mode was started up?

Another solution is to use port 8081 if it's free, otherwise 8082 if it's free, and so on.

**Comment by famod** [comment]
FWIW, I have been using `quarkus.http.test-port=0` for a very long time and I have never seen it coming anywhere close to 8080.

**Comment by geoand** [comment]
I'd be kind of weary of changing the default port for testing (although it should be mostly transparent for users).

I assume that the port of `mvnd` is configurable, correct? If so, then maybe we should just document that needs to be changed

**Comment by gsmet** [comment]
Please use `quarkus.http.test-port=0` in your test suite and open an issue if it appears not to be working.

As Falko said, my wild guess is that it will be good enough.

I don't think we want to make the port random by default.
