### ISSUE TITLE
Kafka - Endpoint that returns `org.reactivestreams.Publisher` produces occasionally invalid SseEvent JSON

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#28567]
### Describe the bug

We generate Kafka events (please see [here](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/KStockPriceProducer.java#L37)) in Quarkus Scheduler every second and [our test uses](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroIT.java#L53) `SseEventSource` to consume events from [this endpoint](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StockPriceEndpoint.java#L49) that produces `Publisher<List<String>>`. Usually `InboundSseEvent` looks like this:
```
InboundSseEvent{id=null', comment=[], data=["{\"id\":\"IBM\",\"price\":0.4873994757961053}", ...,"{\"id\":\"IBM\",\"price\":0.8913893432164612}"]}
```
but sometimes, `InboundSseEvent` is not finished and new one is produced (please see `IBMdata`):
```
InboundSseEvent{id=null', comment=[], data=["{\"id\":\"IBM\",\"price\":0.4873994757961053}",..., "{\"id\":\"IBMdata: ["{\"id\":\"IBM\",\"price\":0.482\",\"price\":0.29906010974526076}", ,...,"{\"id\":\"IBM\",\"price\":0.8913893432164612}"]}
```
Tests are failing as far in past as I went (couple of months), but before 16.9.2022 failures were rare (our impl. didn't change back then).

### Expected behavior

Endpoint produces valid JSON.

### Actual behavior

Sometimes, endpoint produces invalid JSON.
`SEVERE Invalid token=CURLYOPEN at (line no=1, column no=16385, offset=16384). Expected tokens are: [COMMA]`

I mentioned there are following differences (might help with debugging):
- Only for failing runs following message is not logged
```bash
Kafka consumer kafka-consumer-channel-stock-price, connected to Kafka brokers 'localhost:49168', belongs to the 'f0c4a380-1418-463e-bc4c-69cbeb80bd16' consumer group and is configured to poll records from [stock-price]
```
- on average, successful runs has 500 events, while failing runs has 670 events (always more than successful runs)

### How to Reproduce?

Reproducer:

1. `git clone https://github.com/michalvavrik/quarkus-test-suite.git & cd quarkus-test-suite`
2. `git checkout kafka-reproducer`
3. `mvn clean verify -f messaging/kafka-strimzi-avro-reactive-messaging/ -Dit.test=StrimziKafkaAvroIT`
4. run step 3. about 5000 times, it may fail after first run, or much later on. On my workstation, the issue failed just once, however you can check logs of our CI, where the failure is pretty regular (every couple of days): https://github.com/quarkus-qe/quarkus-test-suite/actions

Apart from`quay.io/strimzi/kafka0.28.0-kafka-3.1.0` (steps above), the issue can also be reproduced with:

- DEV mode with Apicurio Registry `quay.io/apicurio/apicurio-registry-mem:2.2.3.Final` and Redpanda `docker.io/vectorized/redpanda:v22.1.7` (`mvn clean verify -f messaging/kafka-strimzi-avro-reactive-messaging/ -Dit.test=DevModeApicurioIT#batchMustBeGreaterThanSingleEvent`)

- Confluent Kafka `confluentinc/cp-kafka` (run `mvn clean verify -f messaging/kafka-confluent-avro-reactive-messaging/ -Dit.test=ConfluentKafkaAvroIT#batchMustBeGreaterThanSingleEvent`), you can also see Github CI logs from 23.9.)

### Output of `uname -a` or `ver`

Linux fedora 5.19.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 31 17:58:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.3.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by ozangunalp** [comment]
I don't think that `Error while fetching metadata` logs you are seeing are concerning, I am guessing that `stock-price` topic is being auto-created on first record and producer metadata are not yet in sync.

**Comment by michalvavrik** [comment]
Thanks, I'll remove it from the description.

**Comment by cescoffier** [comment]
We would need a reproducer to understand what's going on.

**Comment by cescoffier** [comment]
Also, does it also happen when returning a `Multi`?

**Comment by michalvavrik** [comment]
@cescoffier you mean standalone simplified reproducer? Because there is reproducer (even more, there are 2). I didn't try this with `Multi`. I can try (again) to create one, but why can't you use the reproducer you have?

**Comment by michalvavrik** [comment]
Alright, I'll try then.

**Comment by michalvavrik** [comment]
Didn't manage so far to create standalone reproducer (well, I created same thing without test framework, but so far it didn't fail), but I set up CI with test framework that already failed for this (build number 14) https://github.com/michalvavrik/quarkus-test-suite-kafka-reproducer/actions

**Comment by geoand** [comment]
Let's close this for now. If there is more information, we can reopen
