### ISSUE TITLE
Allow configuring Jackson ObjectMapper property naming strategy

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#28580]
### Description

This property is useful to deserialize snake_case JSON properties into Java camelCase POJO properties. 
It doesn't seem to be configurable currently via the quarkus.jackson options.

**Comment by geoand** [comment]
Makes sense to me.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28588 takes care of it

**Comment by davidfrickert** [comment]
Thanks @geoand for the quick PR.
I created a similar issue for another useful property #28605.
