### ISSUE TITLE
Add globally_quoted_identifiers_skip_column_definitions to quarkus.hibernate-orm.database

### ISSUE THREAD

**Issue by gmuellerinform** [quarkusio/quarkus#28593]
### Description

The flag globally_quoted_identifiers_skip_column_definitions is missing. See here: https://stackoverflow.com/questions/64259356/hibernate-globally-quoted-identifiers-true-breaking-integration-tests-with-h2-in

Thanks!

**Comment by yrodiere** [comment]
Thanks for reporting, we'll have a look. I suspect @Sanne will have a strong opinion :)

Until this gets supported, feel free to force the setting through [`quarkus.hibernate-orm.unsupported-properties`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key). Maybe it will work already.

**Comment by yrodiere** [comment]
Hey @Sanne we now have a PR: https://github.com/quarkusio/quarkus/pull/30184

Still no opinion on this?

**Comment by Sanne** [comment]
> Still no opinion on this?

Not really, I normally don't like adding such things as there most likely is room for doing something better (and automate it) but there's only so much we can focus on.. so I guess it's ok.

**Comment by vinicius03** [comment]
This is a common problem specially with PostgreeSql, at the current version, you can already set the property quarkus.hibernate-orm.database.globally-quoted-identifiers=true, if you don't, even if you use the org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl the tables and properties on PostgreSql will be lower case when you use the drop-and-create generation or update strategy.
