### ISSUE TITLE
Automatic config name management for build and run time config

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2860]
**Description**
Sometimes it's nice to have both build and run time config for an extension.  The user should be able to configure both together, like this:

```properties
quarkus.doodad.fuggle=true  # this is build time
quarkus.doodad.miggle=1234 # this is run time
```

This means you need two different config roots like this:

```java
@ConfigRoot(phase = BUILD_TIME, name = "doodad")
public class DoodadBuildTimeConfig {
    @ConfigItem
    boolean fuggle;
}
```

```java
@ConfigRoot(phase = RUN_TIME, name = "doodad")
public class DoodadRunTimeConfig {
    @ConfigItem
    int miggle;
}
```

It's already annoying enough to have to have two classes.  It's doubly annoying to have to give the name twice.  The extension step loader should, in addition to the existing behavior of dropping any trailing `Config(uration)` string, also drop any trailing `BuildTimeConfig(uration)` for config roots marked `BUILD_TIME` and `RunTimeConfig(uration)` for config roots marked `RUN_TIME`.  This behavior should not be extended to non-root `ConfigGroup` classes because such classes are allowed to be used in both build and run time situations.

This behavior could also extend to `BUILD_AND_RUN_TIME_FIXED` using the `BuildTimeConfig(uration)` behavior.

**Comment by stuartwdouglas** [comment]
Wouldn't it be nicer to be able to just specify the build vs runtime on the individual members so that there is no need for multiple classes?

**Comment by dmlloyd** [comment]
Yeah, it would also be more complex though.  But sure, that could be an enhancement.

**Comment by FroMage** [comment]
> Wouldn't it be nicer to be able to just specify the build vs runtime on the individual members so that there is no need for multiple classes?

@stuartwdouglas @dmlloyd I've merged this PR since it's a cheap improvement over the current situation. Could you open a new issue about this additional feature?
