### ISSUE TITLE
 Allow disabling Jackson ObjectMapper WRITE_DURATIONS_AS_TIMESTAMPS

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#28605]
### Description

It would be nice is to disable `WRITE_DURATIONS_AS_TIMESTAMPS` using config.
Currently quarkus supports disabling `WRITE_DATES_AS_TIMESTAMPS` which is very similar.

**Comment by geoand** [comment]
I think this makes sense.

Would you be interested in contributing this? It should not be hard based on what we do for existing similar property

**Comment by davidfrickert** [comment]
Yes that sounds like a simple task to contribute, do I need to sign any contributor agreement?
-------- Mensagem original --------

**Comment by geoand** [comment]
Nope, just open a Pull Request when you are ready 🙂.

Obviously if you need any help, we'll here to assist

**Comment by davidfrickert** [comment]
Ok, I'll work on it then!

**Comment by geoand** [comment]
💪
