### ISSUE TITLE
Kafka consumer or producer config is never logged

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#28612]
### Describe the bug

Is there a way to see how Kafka producer or consumer is configured in Quarkus? 
I remember that in previous versions it was possible to see it in logs. For example, properties like 
`max.partition.fetch.bytes` 
`max.poll.records `
In the latest version even when I set `quarkus.log.level=DEBUG` no additional information is shown about consumer/producer configs.

### Expected behavior

ConsumerConfig or ProducerConfig is shown in logs

### Actual behavior

No ConsumerConfig or ProducerConfig present in logs

### How to Reproduce?

[no-logs-reproducer.zip](https://github.com/quarkusio/quarkus/files/9789762/no-logs-reproducer.zip)

### Quarkus version or git rev

2.13.2

**Comment by cescoffier** [comment]
See https://quarkus.io/guides/kafka#logging.

**Comment by OleKsimov** [comment]
@cescoffier
Why the issue was closed? There are no mentioned logs shown after these properties are set.

**Comment by OleKsimov** [comment]
My bad, thank you.
