### ISSUE TITLE
Using raw `RestResponse` return type has unexpected consequences

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#28627]
### Describe the bug

Specifying the raw `RestResponse` type as an endpoint's return type causes Quarkus to configure the `ServerStringMessageBodyHandler` for this endpoint. This will most often not be what the user wants.

In the following example, where the endpoint returns `multipart/form-data` responses, but has the raw `RestResponse` type as its return type, the POJO entity gets serialized using its `toString()` method rather than using `MultipartMessageBodyWriter`:

```java
    @GET
    @Produces(MediaType.MULTIPART_FORM_DATA)
    @Path("file2")
    public RestResponse getFile2() {
        return RestResponse.ok(new DownloadFormData("test.txt", new File("test.txt")));
    }
```

The use case for returning `RestResponse` is to allow dynamically setting response headers, as [documented](https://quarkus.io/guides/resteasy-reactive#manually-setting-the-response). Of course the return type should be specified with a generic type parameter.

### Expected behavior

Since `RestResponse` is the counterpart of the JAX-RS `Response` type, which isn't generic, I think it would make sense if Quarkus would log a build-time usage warning, whenever an endpoint returns the raw `RestResponse` type.

### Actual behavior

Currently there is no warning and Quarkus will "silently" configure the `ServerStringMessageBodyHandler`.

### How to Reproduce?

Create an endpoint with `RestResponse` as the return type.

### Quarkus version or git rev

2.13.2.Final

**Comment by geoand** [comment]
We'll should wait for https://github.com/quarkusio/quarkus/pull/27526 to be merged before addressing this one

**Comment by knutwannheden** [comment]
I just noticed that if I supply a generic type parameter (I hadn't noticed that `RestResponse` was generic 🤦 ) then the response  looks a lot better:
```shell
❯ curl http://localhost:8080/hello/file2 -i
HTTP/1.1 200 OK
content-length: 322
Content-Type: multipart/form-data

--2b496fef-3c0a-469e-89f3-2ff04b5355d1
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: application/octet-stream

test test
--2b496fef-3c0a-469e-89f3-2ff04b5355d1
Content-Disposition: form-data; name="name"
Content-Type: text/plain

test.txt
--2b496fef-3c0a-469e-89f3-2ff04b5355d1--
```
rather than:
```shell
❯ curl http://localhost:8080/hello/file2 -i
HTTP/1.1 200 OK
content-length: 34
Content-Type: multipart/form-data

org.acme.DownloadFormData@20accfa0
```

I suppose that would be a good reason to log a warning (or even an error) at build-time if there is no generic type parameter.

Yet, as you may notice, the `boundary` parameter is missing in the content type. For reference, here is what a proper response looks like:
```shell
❯ curl http://localhost:8080/hello/file -i
HTTP/1.1 200 OK
content-length: 322
Content-Type: multipart/form-data;boundary=736e7384-ca9b-4c3b-8cec-5231fe5e1d00

--736e7384-ca9b-4c3b-8cec-5231fe5e1d00
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: application/octet-stream

test test
--736e7384-ca9b-4c3b-8cec-5231fe5e1d00
Content-Disposition: form-data; name="name"
Content-Type: text/plain

test.txt
--736e7384-ca9b-4c3b-8cec-5231fe5e1d00--
```
The only difference being the `Content-Type` which is missing the `boundary` parameter when the return type is `RestResponse<DownloadFormData>` instead of `DownloadFormData`.

@geoand I propose to change this issue to log a warning when an endpoint returns `RestResponse` without supplying a generic type parameter and create a new issue for the problem with the missing `boundary` parameter on `Content-Type`. What do you think?

**Comment by knutwannheden** [comment]
I went ahead and filed #28634 for the problem regarding the `Content-Type` header.

**Comment by geoand** [comment]
> @geoand I propose to change this issue to log a warning when an endpoint returns RestResponse without supplying a generic type parameter and create a new issue for the problem with the missing boundary parameter on Content-Type. What do you think?

👍🏼

**Comment by FroMage** [comment]
What's weird is that the `@Produces` should be used for determining how to serialise the contents of the `RestResponse`, no? Does the same bug happen when using `Response`? Intuitively I say this should work OOTB and pick the right `MessageBodyWriter`, even with a raw `RestResponse`, no?

**Comment by geoand** [comment]
We should definitely at least log a warning.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28657 adds a warning
