### ISSUE TITLE
Support programmatic `multipart/form-data` responses

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#28631]
### Description

With RESTEasy Classic there is the [MultipartFormDataOutput](https://docs.jboss.org/resteasy/docs/3.1.0.Final/javadocs/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.html) API which allows programmatic creation of `multipart/form-data` responses, when the actual parts need to be created dynamically. In RESTEasy Reactive there is no such counterpart and I could not find any easy way to do this without basically implementing everything from scratch.

Also note the [OutputPart#getHeaders()](https://docs.jboss.org/resteasy/docs/3.1.0.Final/javadocs/org/jboss/resteasy/plugins/providers/multipart/OutputPart.html#getHeaders--) API which would allow to programmatically add additional headers to the individual parts. This currently isn't possible with `org.jboss.resteasy.reactive.server.core.multipart.PartItem`.

**Comment by geoand** [comment]
Can you show an example use of RESTEasy Classic's `MultipartFormDataOutput`?

Thanks

**Comment by knutwannheden** [comment]
The Kotlin code we have which uses this API looks like this:
```kt
    fun toMultipartFormDataOutput(): MultipartFormDataOutput = MultipartFormDataOutput().apply {
        for ((key, result) in results) {
            val part = addFormData(key, result.content, result.mediaType)
            result.pageCount?.let {
                part.headers[Param.CONTENT_RANGE] = listOf("pages 0-${it - 1}/$it")
                part.headers["x-page-count"] = listOf(it)
            }
        }
    }
```

**Comment by geoand** [comment]
cc @Sgitario who did the multipart output stuff in RR
