### ISSUE TITLE
RESTEasy Reactive: Allow using `RestResponse` for endpoints producing `multipart/form-data`

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#28634]
### Describe the bug

A `MessageBodyWriter` cannot overwrite the content type (using `CurrentRequestManager.get().setResponseContentType()`) if the endpoint uses `RestResponse` as its return type. This works properly when the endpoint's return type is the corresponding POJO type (without the `RestResponse` wrapper).

### Expected behavior

A `MessageBodyWriter` should be able to update the content type (using `CurrentRequestManager.get().setResponseContentType()`) as e.g. `MultipartMessageBodyWriter` does it, independently of whether the endpoint returns a `RestResponse` in its signature or not.

### Actual behavior

When an endpoint returns a `RestResponse` the `Content-Type` is given by the endpoint and the context is updated with a `LazyResponse.Existing` instance, which returns `true` for `isCreated()`: https://github.com/quarkusio/quarkus/blob/5df6480bca82b3d9d61e9398ba93144e6a0d17a0/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResponseHandler.java#L127-L136

Later, after the `MessageBodyWriter` has done its work, when the `io.vertx.ext.web.impl.RoutingContextImpl#headersEndHandlers` are processed, the response content type is not read again, because `isCreated()` returns `true`: https://github.com/quarkusio/quarkus/blob/5df6480bca82b3d9d61e9398ba93144e6a0d17a0/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L477-L493

As a consequence a custom `MessageBodyWriter` such as the built-in `MultipartMessageBodyWriter` effectively cannot overwrite the content type anymore. This works properly when the endpoint doesn't return a `RestResponse`, because then the `isCreated()` method returns `false` (even though the `MessageBodyWriter` has in fact already been processed).

### Quarkus version or git rev

2.13.2.Final

**Comment by knutwannheden** [comment]
@FroMage There is a multipart specific build-time error when using `Response` with the following root cause:
```
Caused by: javax.enterprise.inject.spi.DeploymentException: Endpoints that produce a Multipart result cannot return 'javax.ws.rs.core.Response' - consider returning 'org.jboss.resteasy.reactive.RestResponse' instead. Offending method is 'org.acme.GreetingResource#javax.ws.rs.core.Response getFile3()'
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.creurceMethod(EndpointIndexer.java:631)
        ... 14 more
```

**Comment by geoand** [comment]
> ### Expected behavior

> A `MessageBodyWriter` should be able to update the content type (using `CurrentRequestManager.get().setResponseContentType()`) as e.g. `MultipartMessageBodyWriter` does it, independently of whether the endpoint returns a `RestResponse` in its signature or not.

I am not sure why you think should be the proper behavior.

**Comment by knutwannheden** [comment]
> I am not sure why you think should be the proper behavior.

In a first step I would like to be able to use use `RestResponse<MyDto>` as the return type for a `multipart/form-data` producing endpoint, so that I can dynamically set some additional headers on the response. By extension I think it is reasonable that a custom `MessageBodyWriter` should also be able to achieve this in the same way that `MultipartMessageBodyWriter` does it. Although, maybe you will decide to change that mechanism.

**Comment by geoand** [comment]
First of all, I should say thanks for the in depth analysis you have done here.

I am rather reluctant to address this (at least in the way mentioned) because all of the APIs mentioned here are inherently implementation details, not meant to be depended upon from user code.

**Comment by knutwannheden** [comment]
I think it would be reasonable for RESTEasy Reactive to support `RestResponse` return types for `multipart/form-data` endpoints, so that additional response headers can be added dynamically. I can change the issue title to reflect this request more clearly.

Until #28631 is addressed I will try to use some workaround which hopefully doesn't require me to implement it fully from scratch. This workaround might then depend on some internal implementation details, which I of course understand could change any time. That being said, as an outsider it is hard to discern public from internal APIs, since there is no package naming convention in place.

**Comment by geoand** [comment]
> I think it would be reasonable for RESTEasy Reactive to support RestResponse return types for multipart/form-data endpoints, so that additional response headers can be added dynamically

Sure, that's a valid request - my whole point is how you want this to be done does is not something we want to do.

**Comment by geoand** [comment]
cc @Sgitario ^

**Comment by geoand** [comment]
Is this still an issue?

**Comment by Sgitario** [comment]
To be honest, I don't fully follow how is intended to overwrite the Content-Type header after the Multipart message writer has been called. Maybe, a reproducer would help me to understand the issue. 

However, taking into account the title, RestResponse can be used along with Multipart objects, so this scenario works (not sure about how you want to overwrite the Content-Type header tho). See related pull requests:
- https://github.com/quarkusio/quarkus/pull/29799
- https://github.com/quarkusio/quarkus/pull/24447

@geoand @knutwannheden  can you clarify if there is something else required here? Or try again with Quarkus 2.16?

**Comment by geoand** [comment]
Yes, I think we need a small sample application showing whatever problem exists in 2.16 - if indeed there still is such a problem
