### ISSUE TITLE
Hot Reload on external jars

### ISSUE THREAD

**Issue by brigolini** [quarkusio/quarkus#2865]
**Description**
I have some java classes in a separate JAR file. It's very important to have Hot Reload working for those external JARs too as it's very common for an application to be distributed in more than one Jar file.

**Comment by stuartwdouglas** [comment]
If you have a multi module maven project this this should work, as it will monitor the source directories of all the modules in the project.

**Comment by brigolini** [comment]
I will try this.

**Comment by emmanuelbernard** [comment]
I'll close it in the mean time but if you feel it is not addressed @brigolini, I can reopen to further the conversation.

**Comment by brigolini** [comment]
> I'll close it in the mean time but if you feel it is not addressed @brigolini, I can reopen to further the conversation.
Sorry it take too long.
I did what you said and got this error from Quarkus:
 "The project CC-Parent has no output yet. Make sure it contains at least one source or resource file and then run `mvn compile quarkus:dev`"

It looks that Quarkus expect me to have a source file in the parent project.
My tree is:
cc-parent -> Parent Project
--->cc = has the services for the project
--->cc-web-quarkus = has the endpoints

**Comment by stuartwdouglas** [comment]
Don't add the plugin to the parent, only add it to the module that you actually want to run quarkus:dev on and this should work ok (I think cc-web-quarkus).

**Comment by brigolini** [comment]
Thanks for the reply. It worked fine now!
