### ISSUE TITLE
AMQP non-durable queue creation does  not work

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#28679]
### Describe the bug

I have an artemis  server, with a setup that allows auto creation of queues and addresses, and a client that uses the reactive-messaging-amqp module to receive events through a queue. The module fails because the user can't create a durable queue, but I specified that I wanted a non-durable one.

### Expected behavior

A non-durable queue should be created when the client tries to connect to the queue system and the queue does not exist.

### Actual behavior

The client fails because it does not have permission to create a durable queue.

### How to Reproduce?

See reproducer project: https://github.com/iompo/amqp-connection

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.3.3

**Comment by ozangunalp** [comment]
Thanks for the reproducer! 
I don't think this is a bug. `durable` on incoming configuration refers to consumer subscriptions, not queue creation. 
The broker is trying to auto-create queues when listeners are trying to connect and auto-created queues are durable.

If you want non-durable queues you need to create them on the broker config. And I think the queue address should match the address you are consuming from in `incoming` channel config.

**Comment by iompo** [comment]
Thanks @ozangunalp, reading the doc I did not understand the durable option was referred to incoming configurations. Why auto-created queues are only durable? I didn't find anything in the doc about it..

**Comment by ozangunalp** [comment]
When you are configuring an incoming channel it is configuring the amqp receiver : https://smallrye.io/smallrye-reactive-messaging/3.21.0/amqp/receiving-amqp-messages/#configuration-reference

I agree that the doc is not very explicative.

For auto create queues I need to look for Artemis docs.

**Comment by ozangunalp** [comment]
There https://activemq.apache.org/components/artemis/documentation/latest/address-settings.html#:~:text=slow%20consumers.-,auto%2Dcreate%2Dqueues,-.%20Whether%20or%20not
