### ISSUE TITLE
configuration section of scheduler guide has no content

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#28671]
### Describe the bug

In the 2.13 Version of the guide, the configuration section for the scheduler guide is empty.
![image](https://user-images.githubusercontent.com/1223135/196612658-4aa9c409-60ed-40af-9670-3913d1eb92e2.png)

https://quarkus.io/guides/scheduler#scheduler-configuration-reference

**Comment by mkouba** [comment]
We're experiencing some problems with config-related stuff in the docs. It should be fixed soon.

**Comment by mkouba** [comment]
And it's fixed now.
