### ISSUE TITLE
Quarkus test with @ParameterizedTest and @MethodSource using List.subList does not work

### ISSUE THREAD

**Issue by jakubbrzeski** [quarkusio/quarkus#28677]
### Describe the bug

This is similar to [#25413](https://github.com/quarkusio/quarkus/issues/25413), [#25027](https://github.com/quarkusio/quarkus/issues/25027) and [#24492](https://github.com/quarkusio/quarkus/issues/24492).

When I provide arguments to `@ParameterizedTest` via `@MethodSource` and use `list.subList(...)`, there is an error:
```
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.ImmutableCollections$SubList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private final java.util.ImmutableCollections$AbstractImmutableList java.util.ImmutableCollections$SubList.root accessible: module java.base does not "opens java.util" to unnamed module @76a3e297
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.ImmutableCollections$SubList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private final java.util.ImmutableCollections$AbstractImmutableList java.util.ImmutableCollections$SubList.root accessible: module java.base does not "opens java.util" to unnamed module @76a3e297
```

Adding `--add-opens java.base/java.lang=ALL-UNNAME` etc. proposed in other issues does not work for me unfortunately.

### How to Reproduce?
```
@QuarkusTest
public class ExampleTest {

    @ParameterizedTest
    @MethodSource("params")
    void testLists(List<Integer> ints) {
        assertTrue(true);
    }

    private static Stream<Arguments> params() {
        return Stream.of(
            Arguments.of(
                List.of(1, 2, 3).subList(1,2)
            )
        );
    }
}
```

### Output of `java -version`

openjdk 17.0.3 (Temurin-17.0.3+7)

### Quarkus version or git rev

2.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.5.1

**Comment by elmodeer** [comment]
I am facing the same problem whenever there is a `record` class inside the arguments list. 

```com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : java.lang.UnsupportedOperationException
cause-message       : can't get field offset on a record class: private final java.lang.String com.sap.**
class               : com.sap.**
required-type       : com.sap..**
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /com.sap..**
line number         : 2
version             : 1.4.20
-------------------------------
```

any ideas why is that ? 

it also seems to be the same problem as this issue [here](https://github.com/quarkusio/quarkus/issues/15892#issuecomment-1781678096), with the fix being to implement `serializable`. But this is shouldn't be the solution in my opinion.

**Comment by zakkak** [comment]
> I am facing the same problem

It looks like a different problem to me.

> it also seems to be the same problem as this issue https://github.com/quarkusio/quarkus/issues/15892

That indeed looks like the same issue with yours, could you please provide any additional feedback you might have there instead?
