### ISSUE TITLE
e.printStackTrace() in TransactionalInterceptorBase

### ISSUE THREAD

**Issue by dbathon** [quarkusio/quarkus#2867]
**Describe the bug**
In da8212107dd210ebc0207273a755e4f3686ca82b e.printStackTrace() was added in TransactionalInterceptorBase#handleExceptionNoThrow(). Now every exception that causes a transaction rollback is printed in the log.

I assume this was added for debugging and then was committed accidentally. So just removing that line again should fix the issue.

**Expected behavior**
The exception and stack trace should not be printed by TransactionalInterceptorBase.

**Actual behavior**
The exception and stack trace are printed by TransactionalInterceptorBase.

**To Reproduce**
1. Throw a RuntimeException in a `@Transactional` method.
2. Catch it and handle it outside the `@Transactional` method without printing or logging it.
3. The exception is still printed.

**Environment:**
 - Output of `java -version`: openjdk version "1.8.0_212"
 - Quarkus version: 0.16.1

**Comment by FroMage** [comment]
Wooops, sorry about this and thanks for reporting!
