### ISSUE TITLE
Add Option to remove '%dev' and '%test' properties on prod build

### ISSUE THREAD

**Issue by mbuchner** [quarkusio/quarkus#28686]
### Description

As some people tend to set the %dev and %test properties directly in the applications.properties file it would be good to have an option to clean them out when doing a prod build.

So that  e.g.:
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://dev-db:5654/myapp
%dev.quarkus.datasource.username=test123
%dev.quarkus.datasource.password=mys3cur3pw

Is not in the final build anymore.

### Implementation ideas

Probably with:

-Dquarkus.cleanup-properties=dev
-Dquarkus.cleanup-properties=dev,test

**Comment by mkouba** [comment]
I think that you don't need to include the `application.properties` in your production jar at all. The values should be recorded during build, i.e. you can add `quarkus.package.user-configured-ignored-entries=application.properties` to your `application.properties` and the `target/quarkus-app/app/foo.jar` will not contain the config file at all. But I'm not 100% sure. Also `%dev` and `%test` are recorded as well so you'd be able to find the property values in the quarkus app anyway :shrug:.

CC @radcortez

**Comment by radcortez** [comment]
I agree with @mkouba 

Also, you have plenty of options to avoid this:

- For `test`, the `application.properties` files can sit on `src/test/resources`
- You can use profile-aware files `application-dev.properties` and `application-test.properties` and use those.
- You can have other specific files for test/development outside the main sources and include them in the config scan with `quarkus.config.locations`.

I think that having the option to clean is not going to work very well. We may be able to do it with the configuration files sitting in the project, but we can't do that with the ones sitting inside dependencies jars, or even config sources that we cannot change.
