### ISSUE TITLE
Unexpected behavior during unordered processing record from Kafka in blocking pool 

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#28694]
### Describe the bug

Hi guys!
Please help me to understand if this is expected behavior or a bug.
When I process messages from Kafka using @Blocking annotation and ordered processing, the next properties combination works as expected: 
```
throttled.unprocessed-record-max-age.ms = 3000
max-queue-size-factor = 1
```
So when the processing is blocked for more than 3 seconds, I receive a warning "At the moment 1 messages from this partition are awaiting acknowledgement"
BUT when I configure the blocking pool to the exact size and set ordering processing = false 
```
@Blocking(value = "custom-pool", ordered = false) 
```
```
smallrye:
  messaging:
    worker:
      custom-pool:
        max-concurrency: 3
```
when the processing is blocked for more than 3 seconds, I receive a warning "At the moment **256** messages from this partition are awaiting acknowledgement"

I think something is wrong here and there should not be so many messages waiting for processing in the configured blocking pool of such a small size. This batch size results in restarts because of health check reasons in our project. And I'm trying to understand how it actually works and how I can configure this processing.

### Expected behavior

A small number of unprocessed records (~3) are waiting in the processing queue.

### Actual behavior

A large number of unprocessed records (~256) are waiting in the processing queue.

### How to Reproduce?

[kafka-qsize-reproducer.zip](https://github.com/quarkusio/quarkus/files/9823527/kafka-qsize-reproducer.zip)

Just run the only test and check the logs and application.yaml properties

### Quarkus version or git rev

2.13.2

**Comment by ozangunalp** [comment]
When you are using unordered processing, the reactive stream needs to merge concurrently running processing threads back into the channel stream. That's where a queue is needed. The default value of that queue is on Mutiny side and smallrye reactive messaging is not configuring it per channel.

You can set the queue size using system property `mutiny.buffer-size.s`, the default is 256.

**Comment by OleKsimov** [comment]
@ozangunalp 
Thanks for the explanation. Does it mean that if I configure `mutiny.buffer-size.s`, it will affect only topics processing? 
I mean this property name looks like it can be used for some other processing except Kafka topics. And it would be awful to have performance degradation in non-kafka processing after I configure this queue 5 times smaller for example.

**Comment by ozangunalp** [comment]
Yes the mutiny config would be global.
I guess decreasing `max.poll.records` wouldn't help you neither, as it'll keep buffering records for the merge.
I think it is reasonable to give the ability to configure concurrency on Mutiny merges with blocking processing, @cescoffier wdty? 
It would be a core channel config like broadcast or merge.

**Comment by cescoffier** [comment]
Yes, that could work. 

It would be rather advanced, but should not be hard to implement.

**Comment by ozangunalp** [comment]
This is fixed upstream in https://github.com/smallrye/smallrye-reactive-messaging/commit/d02a5a51230429d9a1aced64d6d783d06117eb1f as reactive messaging now honours the max-concurrency in internal operations.

**Comment by cescoffier** [comment]
@ozangunalp what's the status of this one?

**Comment by ozangunalp** [comment]
@cescoffier internal queue sizes are now controlled by the `max-concurrency` so I think we can close this one.

**Comment by cescoffier** [comment]
Thanks, that's what I was thinking.
