### ISSUE TITLE
Support for mp-config prop substitution in undertow-handlers.conf

### ISSUE THREAD

**Issue by alexlitovsky** [quarkusio/quarkus#28699]
### Description
Currently undertow-handlers.conf does not allow for any variable substitution.
It would be great to allow undertow-handlers.conf to handle mp-config properties.
E.g. `samesite-cookie(mode=${session-cookie.samesite})`

**Comment by radcortez** [comment]
We haven't seen much support for this feature, and unfortunately, we don't have much spare time to work on it. We are closing for now. We can reconsider if we see interest in this or if someone in the community is willing to submit a PR.
