### ISSUE TITLE
Introduce APIs to register endHandler and exceptionHandler in Redis client (Pub/Sub)

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#28696]
### Description

Currently, there is no API to catch exceptions occurs at connection level and there is no API to handle onClose events, when using subscribe commands.

### Implementation ideas

The underlying client (vert.x Redis Client) exposes `RedisConnection#endHandler` and `RedisConnection#exceptionHandler` which are used to register callbacks.

**Comment by Eng-Fouad** [comment]
@cescoffier @gsmet Will this feature be integrated with the next release?

**Comment by cescoffier** [comment]
It will be in 2.14.
