### ISSUE TITLE
Unable to build native image with latest graalvm 22.2.0 with language:js

### ISSUE THREAD

**Issue by aigens** [quarkusio/quarkus#28705]
### Describe the bug

With 22.2.0 , Oracle removed the JS language support by default,

Running the following will give a missing js language support error:
 
./mvnw clean package -Dnative -Dquarkus.native.additional-build-args=--language:js -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17

Whats the proper way to build native image with docker builder image with JS support?

We tried building a new docker builder image with this Dockerfile. It can build but the result have other issues such as the reflection and resource jsons missing.

```
FROM quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17
USER root
RUN gu install js
```

Can someone give us a hint on how to build with JS support?
Is there a native builder image that we can use with JS support pre-installed?

We need JS support for the polygot feature.

Thank you. Help much appreciated.

Peter

### Expected behavior

Successfully build native image as with previous graalvm version.

### Actual behavior

Build failed with missing javascript language support.

### How to Reproduce?

Run:

./mvnw clean package -Dnative -Dquarkus.native.additional-build-args=--language:js -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.2.0-java17

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.2.0

**Comment by yrodiere** [comment]
I might be wrong and I'll ask @galderz for confirmation, but I don't think polyglot support has ever been worked on, tested or even intended to work in Quarkus. The main "clue" I could find about that is [the native image building guide](https://quarkus.io/guides/building-native-image) which mentions that:

> Mandrel is recommended for building native executables that target Linux

And:

> Mandrel releases are built from a code base derived from the upstream Oracle GraalVM CE code base, with only minor changes but some significant exclusions that are not necessary for Quarkus native apps. [...] Notably, they do not include support for polyglot programming

So, even before that change in upstream GraalVM, Quarkus was already recommending a distribution of GraalVM (Mandrel) that didn't include support for polyglot programming.

Maybe someone can provide you with alternatives to `language:js`, though? No idea what that would be.

**Comment by geoand** [comment]
> but I don't think polyglot support has ever been worked on, tested or even intended to work in Quarkus

It certainly has never been supported or much tested. Users trying to use this stuff are on their own

**Comment by aigens** [comment]
I see. So it's not officially supported and we understand.

But it's great feature that we definitely will be using it for eval() JS scripts within java code.

Can anyone give me a hint on how to extend the (or any) native build docker image properly with js language installed?

It seems we just need to include the line
"RUN gu install js" in addition to the native-image when making the docker build image. 

Anyway or where we can examine the docker file for these images?

https://quay.io/repository/quarkus/ubi-quarkus-native-image?tab=tags&tag=22.2.0-java17

Thanks!

**Comment by yrodiere** [comment]
> Can anyone give me a hint on how to extend the (or any) native build docker image properly with js language installed?

Personally, no idea.

> Anyway or where we can examine the docker file for these images?

There's a link to the source in the ["info" page](https://quay.io/repository/quarkus/ubi-quarkus-native-image?tab=info): https://github.com/quarkusio/quarkus-images

**Comment by geoand** [comment]
@galderz @zakkak @jerboaa do you have any insights on this one?

**Comment by zakkak** [comment]
> Anyway or where we can examine the docker file for these images?

You can generate a Dockerfile from https://github.com/quarkusio/quarkus-images with `mvn install -Djdock.dry-run=true`. The location of each Dockerfile is printed in the log.

> Can anyone give me a hint on how to extend the (or any) native build docker image properly with js language installed?

The `RUN gu install js` you suggest makes sense. I suggest giving that a try by building your own image builder.
If that turns out to work for you I guess you can then create a Dockerfile with `FROM ubi-quarkus-graalvmce-builder-image` and generate an extended image with js support.

Note that this will not work with mandrel images.

**Comment by aigens** [comment]
Thanks guys for your input. We managed to get it work by extending the
docker image with gu install js.

**Comment by geoand** [comment]
Thanks for letting us know!
