### ISSUE TITLE
Broken Redis client for cluster mode (MOVED Exception)

### ISSUE THREAD

**Issue by PyAntony** [quarkusio/quarkus#28704]
### Describe the bug

Hi,

there is an issue with the Redis client in cluster mode. Here is my config:
```
quarkus.redis.hosts=redis://localhost:7001,redis://localhost:7002,redis://localhost:7003,redis://localhost:7004,redis://localhost:7005,redis://localhost:7006
quarkus.redis.client-type=cluster
quarkus.redis.replicas=share
```
I have my cluster up and running in local for all those ports:
```
antony@pop-os:~$ redis-cli -c -p 7001
127.0.0.1:7001> CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_ping_sent:107731
cluster_stats_messages_pong_sent:107678
cluster_stats_messages_sent:215409
cluster_stats_messages_ping_received:107673
cluster_stats_messages_pong_received:107731
cluster_stats_messages_meet_received:5
cluster_stats_messages_received:215409
total_cluster_links_buffer_limit_exceeded:0
...
antony@pop-os:~$ redis-cli -c -p 7001
127.0.0.1:7001> PING
PONG
antony@pop-os:~$ redis-cli -c -p 7002
127.0.0.1:7001> PING
PONG
antony@pop-os:~$ redis-cli -c -p 7003
127.0.0.1:7003> PING
PONG
...
```
I am running this simple code for testing:
```java
    // get cluster info and create a new field in a map
    @Scheduled(every = "4s", delayed = "3s")
    Uni<Void> test() {
        System.out.println("\nRunning test...");
        return redisClient.execute("CLUSTER", "INFO")
            .invoke(r -> System.out.println("\nCluster Info --->\n: " + r))
            .chain(() -> redisClient.execute("HSET", "myDict", "field-" + UUID.randomUUID(), "val"))
            .onFailure().recoverWithItem(e -> {
                Log.error("Error returned: ", e);
                return null;
            })
            .replaceWithVoid();
    }
```
This is the output I am getting:
```
Cluster Info --->
: cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
...

2022-10-20 00:26:31,039 ERROR [com.cha.pau.scu.Test] (vert.x-eventloop-thread-1) Error returned: : MOVED 9564 127.0.0.1:7002
```
So I do get the cluster info but any other command fails (I have tried multiple commands). I have tried with different profiles (dev, prod), with `quarkus dev` and running the jar; I always get the same error. After reading a bit it seems like this is just a redirect notification for the client to resend the request to the indicated node (https://redis.io/docs/reference/cluster-spec/), but the quarkus client doesn't do the redirect, it just throws the error. 

### Output of `java -version`

openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS, mixed mode)

### Quarkus version or git rev

2.13.0

### Additional information

Redis version:
```
antony@pop-os:~$ redis-server --version
Redis server v=7.0.5 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=82289c7437798a30
antony@pop-os:~$ redis-cli --version
redis-cli 7.0.5
```
To create the cluster I am simply running `create-cluster start` and `create-cluster create` (https://redis.io/docs/manual/scaling/#create-and-use-a-redis-cluster).

##### UPDATE:
Just run it with Redis version 6.2 (cluster mode) and I get the same error.

**Comment by pmlopes** [comment]
I believe the calculation of the slot for the given command is returning the wrong id and the command gets executed on the wrong node.

I need to reproduce the issue and debug it. Which version of vertx is used here?

**Comment by gsmet** [comment]
@pmlopes given the OP says Quarkus 2.13.0.Final, that would be Vert.x 4.3.3.

**Comment by cescoffier** [comment]
ah yes... sorry.

**Comment by PyAntony** [comment]
##### UPDATE:
The same issue is observed when increasing the number of shards in the cluster (in AWS: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Shards.html). When having more than 1 shard we see this `MOVED` exception everywhere; basically we are unable to work with more than 1 shard. I wonder if there is a special way to set up the config for multishard cluster?

**Comment by cescoffier** [comment]
@PyAntony can you open an issue on https://github.com/vert-x3/vertx-redis-client?

**Comment by PyAntony** [comment]
sure, will do. Thanks.

**Comment by PyAntony** [comment]
@OmerShemesh  Some description for the issue is here: https://github.com/vert-x3/vertx-redis-client/issues/365. If your situation is similar then just using `quarkus.redis.replicas=never` should fix it (which it seems to be the default, but I guess most people pass `share` since it is suggested in the documentation). If `quarkus.redis.replicas=never` doesn't fix your problem then I have no idea.

**Comment by Ladicek** [comment]
The problem here is using the generic `execute()` method, which doesn't correctly recognize known Redis commands, so it doesn't know where the key in the command is, so it just selects a random node in the cluster. You really should use the proper API for calling HSET:

```java
redisClient.hash(String.class, String.class. String.class).hset("myDict", "field" + UUID.randomUUID(), "val");
```

Also, we really should recognize known Redis commands and treat them properly, instead of treating all custom commands as generic unknowns. I'll fix that both in Vert.x Redis client and in Quarkus (so that we don't have to wait for a Vert.x release -- we'll remove it in Quarkus after upgrading to a fixed Vert.x Redis client).

**Comment by Ladicek** [comment]
Fix in Quarkus is:

- https://github.com/quarkusio/quarkus/pull/36580

Fixes in Vert.x Redis client are:

- 4.x: https://github.com/vert-x3/vertx-redis-client/pull/414
- master: https://github.com/vert-x3/vertx-redis-client/pull/413
