### ISSUE TITLE
QuarkusTransaction does not fire @Initialized(TransactionScoped.class)

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#28709]
### Describe the bug

When starting a new transaction with `QuarkusTransaction.run`, listeners listening with `@Observes @Initialized(TransactionScoped.class) Object notUsed` are not notified.

### Expected behavior

Listeners should be notified.

### Actual behavior

Listeners are not notified.

### How to Reproduce?

1. Execute [transaction-event-reproducer.zip](https://github.com/quarkusio/quarkus/files/9827630/transaction-event-reproducer.zip)
2. Wait 10s
3. See log output...it is fired for `@Transactional`, but not for `QuarkusTransaction.run`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2006]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by mkouba** [comment]
So the difference is that `@Transactional` interceptors use the injected `TransactionManager` to begin the tx. And this TM is in fact a delegating wrapper - `CDIDelegatingTransactionManager` - that fires the relevant events. However, the `QuarkusTransaction` leverages the injected  `UserTransaction` to begin the tx - no events are fired.

**Comment by mkouba** [comment]
FTR the injected `UserTransaction` would not fire these events either.

**Comment by wicksim** [comment]
So I think, also `@TransactionScope`-beans will not work with `UserTransaction` and `QuarkusTransaction`?

**Comment by mkouba** [comment]
> So I think, also `@TransactionScope`-beans will not work with `UserTransaction` and `QuarkusTransaction`?

Nope, the `@TransactionScoped` beans should work because the [`TransactionContext`](https://github.com/quarkusio/quarkus/blob/main/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/context/TransactionContext.java) implementation looks up the current transaction via the `TransactionManager` and stores the beans in the `TransactionSynchronizationRegistry`.

**Comment by wicksim** [comment]
@mkouba IMHO this still does not work (with Quarkus 2.16.1.Final).

I think the problem is, that `QuarkusTransactionImpl` gets the `TransactionManager` by `return cachedTransactionManager = com.arjuna.ats.jta.TransactionManager.transactionManager();` which returns a `com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple`. I think a `NotifyingTransactionManager` would be needed here for the listener to work?

My original reproducer can still be used to reproduce the problem. Just update to the new Quarkus-Version.

Can we re-open this issue?

**Comment by yrodiere** [comment]
> I think that we should try to modify the `QuarkusTransactionImpl.getUserTransaction()` and `QuarkusTransactionImpl.getTransactionManager()` methods to use the injected variants.

Makes sense to me. Are you working on this or do you want me to send a patch (+ non-regression tests)?
