### ISSUE TITLE
Error with @JsonCreator on record

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#28717]
### Describe the bug

```java
@RegisterForReflection
public record MyRecord(String value) {

    @Override
    @JsonValue
    public String toString() {
        return value;
    }

    @JsonCreator
    public static MyRecord of(String value) {
        return new MyRecord(value);
    }

}

@QuarkusTest
public class MyRecordQuarkusTest {

    @Inject
    ObjectMapper objectMapper;

    @Test
    void deserialization() throws JsonProcessingException {
        System.out.println(Arrays.asList(objectMapper.readerForArrayOf(MyRecord.class).readValue("[\"bla\"]")));
    }

}
```

Deserialization test fails with:

```java
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.acme.MyRecord` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('bla')
 at [Source: (String)"["bla"]"; line: 1, column: 2] (through reference chain: java.lang.Object[][0])
```

### Expected behavior

Record is deserialized properly, like the following cases which work:

Non Quarkus test

```java
public class MyRecordTest {

    @Test
    void deserialization() throws JsonProcessingException {
        System.out.println(Arrays.asList(new ObjectMapper().readerForArrayOf(MyRecord.class).readValue("[\"bla\"]")));
    }

}
```

Using class instead of record:

```java
@RegisterForReflection
public class MyClass {

    private final String value;

    public MyClass(String value) {
        this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
        return value;
    }

    @JsonCreator
    public static MyClass of(String value) {
        return new MyClass(value);
    }

}

@QuarkusTest
public class MyClassQuarkusTest {

    @Inject
    ObjectMapper objectMapper;

    @Test
    void deserialization() throws JsonProcessingException {
        System.out.println(Arrays.asList(objectMapper.readerForArrayOf(MyClass.class).readValue("[\"bla\"]")));
    }

}
```

### How to Reproduce?

Reproducer: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9829800/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

Darwin N4MFM06QYD 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by xtaixe** [comment]
No, just running those test.

**Comment by gsmet** [comment]
No this thing is weird so I was asking to triage it :).

**Comment by gsmet** [comment]
Using `@JsonCreator(mode = Mode.DELEGATING)` makes it work in both cases.

Found some hints here: https://github.com/FasterXML/jackson-databind/issues/3097 .

Now I'm not sure why an `ObjectMapper` instantiating with `new` would behave differently in this regard. Maybe you can have a look in this area and try to understand what's going on if you have some time?

**Comment by xtaixe** [comment]
It really looks like it could be https://github.com/FasterXML/jackson-databind/issues/2112 but I haven't found if Quarkus registers the `ParameterNamesModule`.

**Comment by gsmet** [comment]
Yes we actually do include it.
So I would say that's an upstream issue for which we cannot do anything in Quarkus.

Anyway it's nice to have it documented in our tracker.

Workaround is to use `@JsonCreator(mode = Mode.DELEGATING)`.
