### ISSUE TITLE
Doc: Missing dekorate upgrade on Quarkus 2.14 Migration guide

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#28720]
### Describe the bug

The current [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.14) doesn't have any reference to [dekorate upgrade](https://github.com/quarkusio/quarkus/pull/28438). In my opinion, this upgrade should  be documented, because fix some issues but also introduce some incompatibilities, for example, the current Quarkus-helm (v0.1.1) [doesn't support](https://github.com/quarkiverse/quarkus-helm/issues/114) this Dekorate  upgrade.

**Comment by Sgitario** [comment]
The Dekorate upgrade does not introduce any change that users need to migrate, so I don't know what we should document here.
The Quarkus Helm extension is compatible with the latest versions of Quarkus and Quarkus 2.14 has not been released yet, so obviously, users won't be hit with this issue (see the compatibility version table for further reference https://github.com/quarkiverse/quarkus-helm#compatibility-with-quarkus). I've also closed the Quarkus helm issue. 

wdyt @gsmet ?

**Comment by Sgitario** [comment]
I'm closing this issue. In case you spot something that we should remark in the migration guide, please let me know.
