### ISSUE TITLE
@ClientHeaderParam is ignored when ClientHeadersFactory impl is used

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#28738]
### Describe the bug

Adding @ClientHeaderParam to a resteasy reactive interface don't work,
ie. the key and value is NOT added to the http request.

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40ClientHeaderParam.20resteasy.20reactive

### Expected behavior

ClientHeaderParam should not be ignored

### Actual behavior

The usage of ClientHeaderParam is ignored

### How to Reproduce?

Run the provided test.
Verify the logging

# with the usage of: ClientHeadersFactory
[org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Request: GET http://localhost:8081/my/ep2/ Headers[myKey=myValue User-Agent=Resteasy Reactive Client], Empty body

# without the usage of: ClientHeadersFactory
 [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-1) Request: GET http://localhost:8081/my/ep2/ Headers[lostKey=lostValue User-Agent=Resteasy Reactive Client], Empty body
[rest-client-reactive-quickstart15.zip](https://github.com/quarkusio/quarkus/files/9836996/rest-client-reactive-quickstart15.zip)

### Output of `uname -a` or `ver`

Linux hty80028.sb1a.sparebank1.no 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: /home/sb1a.sparebank1.no/a11882/opt/maven Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /home/sb1a.sparebank1.no/a11882/opt/jdk-17.0.4.1_1 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "4.18.0-372.26.1.el8_6.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
I am not sure what the proper behavior is here honestly...

@Sgitario WDYT?

**Comment by Sgitario** [comment]
> I am not sure what the proper behavior is here honestly...
> 
> @Sgitario WDYT?

I think this is definitely a bug. Actually, the documentation introduces a very similar example with the usage of `@RegisterClientHeaders` and `@ClientHeaderParam` altogether: https://quarkus.io/guides/rest-client-reactive#custom-headers-support

**Comment by geoand** [comment]
Do you want to take a look at it or should I?

**Comment by Sgitario** [comment]
> Do you want to take a look at it @Sgitario or should I?

I will :D
