### ISSUE TITLE
Rename `Template` to `Recorder` or something

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2874]
I've heard Quarkus users yesterday who were _very_ confused as to what our `Template` recorders did and how they worked. Part of it is due to this functionnality being original (haven't seen it elsewhere), but part of it is due to the name `Template` which does mean at all what it does (record any calls made through the object) and does not mean the most common industry term for template (rendering, text-replacement).

Could we rename it to something more obvious such as `Recorder` or `CallRecorder` or any other suggestion? Naturally we can keep the current name as an alias for compat, even if we end up only documenting the new name.

WDYT?

**Comment by emmanuelbernard** [comment]
+1 for me. I get confused too. CC @stuartwdouglas

**Comment by stuartwdouglas** [comment]
Recorder is probably a better name. Originally we had a recorder object that used templates, however that is not really part of the API any more.

**Comment by dmlloyd** [comment]
Maybe "recordable" would be a bit more idiomatic?

**Comment by stuartwdouglas** [comment]
I think either is fine. I think the distinction between recorder and recording proxy is more of an implementation detail. Technically they are recorders, it is basically an implementation detail that they delegate to another class that is also called a recorder.

**Comment by emmanuelbernard** [comment]
I tend to prefer Recorder as it shows to the user the intent / end result.

**Comment by mkouba** [comment]
Current state:
```java
@Template
public class ArcDeploymentTemplate {
}
```
`@Recorder`:
```java
@Recorder
public class ArcTemplate {
}
```
`@Recordable`:
```java
@Recordable
public class ArcTemplate {
}
```

I personally like `@Recordable` because it reads "recordable template". `@Recording` sounds also good to me:

```java
@Recording
public class ArcTemplate {
}
```

**Comment by emmanuelbernard** [comment]
The point is more that we would get a `ArcRecorder`

**Comment by mkouba** [comment]
```java
@Recorder
public class ArcRecorder {
}
```
Like this? If so I'm fine with that.

**Comment by gsmet** [comment]
+1 too.

Let's make this change just after a release.

**Comment by stuartwdouglas** [comment]
Can we make the change ASAP? I will be talking about extension development next week.

**Comment by n1hility** [comment]
+1 FWIW  I like this name style the best.
