### ISSUE TITLE
Testcontainers not terminating

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#28769]
### Describe the bug

Testcontainers that are launched during the build aren't terminating and keep running

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1553757/197412360-6b97bdc6-3b68-44ee-bb69-3cd0b921d2cc.png">

### Expected behavior

I was expecting they are shut down when the process is finished

**Comment by geoand** [comment]
I am pretty sure that this is a duplicate of https://github.com/quarkusio/quarkus/issues/25852, but we would need more information on how you reproduce this issue to be certain.

**Comment by geoand** [comment]
Closing as per my comment above (and as we never got a reproducer)
