### ISSUE TITLE
Qute: Nested templates

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#28771]
### Description

Hello,

I would like to propose a new  feature for Qute - nested templates.

My use case is following:

I am using htmx and I would like to render template differently based on incoming headers.
* When page is requested directly from browser I would like to render whole page
* But when page is requested using ajax with specific headers I would like to render only partial content of page

Currently it could be done this way:

base.qute.html
```html
<!DOCTYPE html>
<html>
<head>
// some scripts and metadata
</head>
<body>
<header>
// some layout stuff like menu
</header>
<content>
    {#insert}{/}
</content>
<footer>
// footer
</footer>
</body>
</html>
```

full_page.qute.html
```html
{#include base}
    <span>some content</span>
{/include}
```

partial_page.qute.html
```html
    <span>some content</span>
```

Then I could render full page or only partial page but it requires lots of boilerplate.

I would like to improve this by allowing passing template instance to other template instance like this.

full_page.qute.html
```html
{#include base}
   {childPage}
{/include}
```

This way I could render partial page directly or pass it to full page as parameter.

What do you think about such feature?

**Comment by kucharzyk** [comment]
@mkouba I've added PR with initial implementation

**Comment by mkouba** [comment]
Recetnly, we added a feature called template fragments in the main branch. See the docs [here](https://quarkus.io/version/main/guides/qute-reference#fragments) and [here](https://quarkus.io/version/main/guides/qute-reference#type_safe_fragments). I wonder if this could be used for your use case?

**Comment by kucharzyk** [comment]
I didn’t know about fragments. They definitely suits my needs. Thanks. 

I think this issue can be closed now
