### ISSUE TITLE
Complete OpenAPI for PanacheEntityResource 

### ISSUE THREAD

**Issue by gmuellerinform** [quarkusio/quarkus#28786]
### Description

PanacheEntityResource is using Resource as return value and therefore the OpenAPI is not picking up the correct return type. It would be great if this could be fixed. Including the correct return types for errors.

Thank you!

**Comment by geoand** [comment]
cc @Sgitario

**Comment by Sgitario** [comment]
I think that this was already done in https://github.com/quarkusio/quarkus/pull/26074. Are you using the Quarkus Smallrye OpenApi extension?

**Comment by gmuellerinform** [comment]
Yes, I am. This is ho wit looks:

![image](https://user-images.githubusercontent.com/113999547/197542674-f215e14e-9b51-460e-a2c3-7d6e4c0230d4.png)

and this how it should look like, using the code:

`public List<ApplicationRole> list(@PathParam("user_id") Long user_id) {`

![image](https://user-images.githubusercontent.com/113999547/197542386-d4ca1a36-462c-4de0-bb14-9e6ebeb711d2.png)

It is a nice to have feature, not too high a priority. Thanks!

**Comment by Sgitario** [comment]
Oh, I see what is going on. This works for the reactive version of REST Data Panache because Uni is generic, but not for the classic one because Response is not a generic type. 
I will address this issue asap. Thanks for reporting!
