### ISSUE TITLE
RESTEasy Reactive - mapping MULTIPART_FORM_DATA to request body don't work

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#28782]
### Describe the bug

with https://github.com/quarkusio/quarkus/pull/27526 in place, my multiplart form data request body is always null. My endpoint looks like:
```Java
    // resource method
    @POST
    @Path("/echo")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public String echo(String requestBody) {
        return requestBody;
    }
```

same situation is for wrapper
```Java
    // resource method
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/upload-multipart")
    @Blocking
    public String uploadMultipart(FileWrapper body) {
        deathRow.add(body.file);
        return utils.getSum(body.file.getAbsoluteFile().toPath());
    }
...
    @RegisterForReflection
    public class FileWrapper {
        @RestForm("file")
        @PartType(MediaType.APPLICATION_OCTET_STREAM)
        public File file;
    
        @RestForm("name")
        @PartType(MediaType.TEXT_PLAIN)
        public String name;
    }
```

### Expected behavior

- Provide a way how I can map the request to the String (ideally OOTB).
- Make docs dummy proof (customize docs for me).

### Actual behavior

`requestBody` is always null. `body` is not null but its fields are null.

### How to Reproduce?

Reproducer:

1. `git clone https://github.com/quarkus-qe/quarkus-test-suite.git`
2. cases 
- `cd quarkus-test-suite/http/jaxrs-reactive && mvn clean verify -Dit.test=MultipartClientIT`
- `cd quarkus-test-suite/http/rest-client-reactive && mvn clean verify -Dit.test=LargeFileHandlingIT#uploadMultipart`

**Comment by michalvavrik** [comment]
@FroMage @geoand updated PR as I found another issue and they are pretty similar

**Comment by geoand** [comment]
Thanks!

@FroMage can you please take a look at this? It would be great to have this fixed for the first CR if possible

**Comment by FroMage** [comment]
Yes, this must be related to the multipart change. I'll look.

**Comment by FroMage** [comment]
OK, so the first good news is that if I add these tests to the RESTEasy Reactive test suite, they pass.

**Comment by FroMage** [comment]
Perhaps it's a client issue then, because I see that's involved.

**Comment by FroMage** [comment]
I guess the `@QuarkusScenario` runs things via a different VM, making this hard to debug :(

**Comment by FroMage** [comment]
OK, I can reproduce it outside the QE tests. It appears to be a problem with the client indeed, not sending anything.

**Comment by FroMage** [comment]
Huh. So, that's embarassing… It appears `BeanParamParser` doesn't support the `@Rest*` annotations, which means on the client side only the JAX-RS annotations are supported for bean params. How we did not notice that before, I wonder. I'll fix this ASAP.

**Comment by michalvavrik** [comment]
Thank you

**Comment by FroMage** [comment]
This is the gift issue that keeps on giving.

So apparently, on the header we auto-hyphenate headers, so `@RestHeader String fooBar` is equivalent to `@RestHeader("foo-Bar") String fooBar`, which is almost useful, I guess, though the initial letter should be capitalised to be useful, as specified in the original issue: https://github.com/quarkusio/quarkus/issues/13665. But this isn't done on the client, so it's not symmetrical.

And, since we designed `@RestHeader` (and others) for the server, we allowed it for fields and parameters, but not properties (methods). And the client allows and supports the original `@HeaderParam` on properties as well, which I can notice in `@BeanParam` tests. Pretty sure the server doesn't support properties. But the client does. What do you think of that @geoand ? Should I file an issue?

**Comment by geoand** [comment]
> Pretty sure the server doesn't support properties

Not sure I am following what you mean here. Can you please elaborate?

**Comment by FroMage** [comment]
Well, given that `@RestHeader` (and the rest) are not allowed on methods, I don't think the server side supports them being defined on `@BeanParam` or endpoint properties. Now that I think about it, I'm not even sure we support `@HeaderParam` on those either, even though these are allowed on methods.

**Comment by geoand** [comment]
I must be missing something entirely as I don't understand what you mean by `@RestHeader (and the rest) are not allowed on methods`

**Comment by FroMage** [comment]
You must be as incredulous as I was:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.PARAMETER })
public @interface RestHeader {
    String value() default "";
}
```

Notice the missing `ElementType.METHOD` ;)

**Comment by geoand** [comment]
Oh... Now I see...

Yeah, putting them on a method was not something we really envisioned

**Comment by geoand** [comment]
Darn... I guess we need to formally support it then

**Comment by FroMage** [comment]
Well, I will start with filing an issue, then we can wait for people to need that. Seems pretty useless IMO.

**Comment by FroMage** [comment]
Properties: https://github.com/quarkusio/quarkus/issues/28846
And I reopened https://github.com/quarkusio/quarkus/issues/13665 for the headers

**Comment by geoand** [comment]
Great, thanks

**Comment by FroMage** [comment]
OK, done.

**Comment by michalvavrik** [comment]
Hello @FroMage , thank you for #28851, are there other steps required to fix this issue?

**Comment by michalvavrik** [comment]
Ah, still not fixed, I get it.
