### ISSUE TITLE
Java records toString() prints null (Integer) in JVM mode, 0 (Integer) in native mode

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#28794]
### Describe the bug

Given the following sample code:

```java
@ApplicationScoped
public class AppLifecycle {
	
	@RegisterForReflection
	record Foo(Integer x){}
	
	void onStart(@Observes StartupEvent ev) {
		Log.info(new Foo(null).x());
		Log.info(new Foo(null).toString());
	}
}
```

JVM mode output:

> null
> Foo[x=null]

Native mode output:

> null
> Foo[x=0]

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Very weird, although likely not a Quarkus issue.

@zakkak are you aware of any upstream GraalVM issue that this corresponds to?

**Comment by zakkak** [comment]
> Very weird, although likely not a Quarkus issue.

Correct. This is not a Quarkus issue.

It's reproducible outside of Quarkus with the following code:

```java
public class Records {
    record Foo(Integer x) {}

    public static void main(String[] args) {
        System.out.println(new Foo(null).x());
        System.out.println(new Foo(null).toString());
    }
}
```

> @zakkak are you aware of any upstream GraalVM issue that this corresponds to?

No, but I will create one shortly (and update my comment to link to it).

**Comment by geoand** [comment]
> No, but I will create one shortly (and update my comment to link to it).

Thanks

**Comment by geoand** [comment]
I'm going to close this as an upstream issue
