### ISSUE TITLE
Missing Service Binding example for Strimzi

### ISSUE THREAD

**Issue by matzew** [quarkusio/quarkus#28806]
### Description

Looking here, I see that service binding to an on-cluster strimzi seems to be supported:
https://github.com/quarkusio/quarkus/blame/647dfdc13ffc76a65f2980a120ec0878cf07bfd6/extensions/kubernetes-service-binding/deployment/src/main/java/io/quarkus/kubernetes/service/binding/buildtime/ServiceBindingProcessor.java#L63

I am not sure I am seeing some documementation or example on this somewhere - or is this not really supported?

**Comment by geoand** [comment]
I personally have no idea if it's supported or not as I have not used Strimzi.

@cescoffier do you know? If it's supported, we should probably document it.

**Comment by cescoffier** [comment]
I don't believe it is, at least I never tried myself.

**Comment by geoand** [comment]
@matzew would be able to test this?

**Comment by iocanel** [comment]
@matzew: AFAIK strimzi is not supported by the Service Binding Operator (yet). So, even though we are generting the needed resources they won't be of much use until SBO or any other operator that follows the spec adds support for strimzi.

**Comment by matzew** [comment]
funny that the code contains strimzi coordinates even it is not supported :smiley:
