### ISSUE TITLE
Inject ApplicationScoped inside ApplicationScoped throws NullPointerException

### ISSUE THREAD

**Issue by vinland-saga** [quarkusio/quarkus#28826]
### Describe the bug

Basically:
I want the Controller class to have a generic IUseCase (constructor injected) and the UseCase to have a generic IService (constructor injection).

Controller -> UseCase -> Server
Controller -> UseCase -> MockServer
Controller -> UseCaseMock	             

```
public class Controller {
    private final IUseCase useCase;

    @Inject
    public Controller(IUseCase getUseCase) {
        this.useCase = getUseCase;
    }
```
	
```
@ApplicationScoped
public class UseCase implements IUseCase {

    private IService service;

    @Inject
    public UseCase(IService webService) {
        this.service = webService;
        service.init();
    }
}
```
	
```
public class UseCaseMock implements IUseCase {
...
}
```	
	
```
@ApplicationScoped
public class Service implements IService {
...
}
```

```
public class ServiceMock implements IService {
...
}
```

### Expected behavior

When running the application, because of the @ApplicationScoped annotation, I expect that:
Controller has the UseCase constructor injected 
and 
that the UseCase has Service constructor injected.

### Actual behavior

Method threw 'java.lang.NullPointerException' exception. Cannot evaluate ...usecases.impl.UseCase_ClientProxy.toString()

it didnt inject it, even tho it was annotated with ApplicationScoped.

### How to Reproduce?

In a nutshell:
have a class which constructor injects an ApplicationScoped class which constructor injects an ApplicationScoped class.

```
public class Controller {
    private final IUseCase useCase;

    @Inject
    public Controller(IUseCase getUseCase) {
        this.useCase = getUseCase;
    }
```
	
```
@ApplicationScoped
public class UseCase implements IUseCase {

    private IService service;

    @Inject
    public UseCase(IService webService) {
        this.service = webService;
        service.init();
    }
}
```
	
```
public class UseCaseMock implements IUseCase {
...
}
```	
	
```
@ApplicationScoped
public class Service implements IService {
...
}
```

```
public class ServiceMock implements IService {
...
}
```

### Output of `java -version`

openjdk version "1.8.0_312"

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by geoand** [comment]
I see that `Controller` is not annotated with a CDI annotation. How are you creating / using it?

**Comment by mkouba** [comment]
@geoand is right that the `Controller` is missing a bean defining annotation (e.g. a scope). Also we'll need the full stack trace. Ideally, a small reproducer app that shows the problem...

**Comment by vinland-saga** [comment]
Controller has as well the annotation ApplicationScoped
sorry about that

**Comment by mkouba** [comment]
> Controller has as well the annotation ApplicationScoped
> sorry about that

Ok no problem.

> Controller is successfully injected with UseCase, but UseCase throws the NullPointerException becauase it cannot inject the Service.

Where is the NPE thrown? What does the stack look like?

**Comment by vinland-saga** [comment]
Here is the stack trace:
(note: in the stackTrace, I have altered the production classes paths: example: .usecases.impl.UseCase.<init>(UseCase.java:46), is fine)
 
[stackTrace_inject_applicationScoped.txt](https://github.com/quarkusio/quarkus/files/9873272/stackTrace_inject_applicationScoped.txt)

**Comment by vinland-saga** [comment]
Here is the stackTrace if you dont want to donwload the file:

`
      "details": "Error handling 0725c1ac-f20c-4d18-b080-e692e778214e-2, org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException",

      "stack": "org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
 org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
 org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
 org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
 org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
 org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
 org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
 org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
 org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
 io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
 io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
 io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
 io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
 org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
 org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
 org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.base/java.lang.Thread.run(Thread.java:829)
 
 
Caused by: java.lang.NullPointerException
 .usecases.impl.UseCase.<init>(UseCase.java:46)
 .usecases.impl.UseCase_Subclass.<init>(UseCase_Subclass.zig:33)
 .usecases.impl.UseCase_Bean.create(UseCase_Bean.zig:197)
 .usecases.impl.UseCase_Bean.create(UseCase_Bean.zig:213)
 io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
 io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
 io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
 io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
 io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
 io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
 io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
 .usecases.impl.UseCase_ClientProxy.arc$delegate(UseCase_ClientProxy.zig:67)
 .usecases.impl.UseCase_ClientProxy.getData(UseCase_ClientProxy.zig:125)
 .controller.Controller.getBy(Controller.java:60)
 .controller.Controller_Subclass.getBy$$superforward1(Controller_Subclass.zig:256)
 .controller.Controller_Subclass$$function$$3.apply(Controller_Subclass$$function$$3.zig:33)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
 io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor.restMethodInvoke(QuarkusRestPathTemplateInterceptor.java:31)
 io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor_Bean.intercept(QuarkusRestPathTemplateInterceptor_Bean.zig:328)
 io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
 io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
 io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:24)
 io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle$$superforward1(SecurityHandler_Subclass.zig:137)
 io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass$$function$$2.apply(SecurityHandler_Subclass$$function$$2.zig:33)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
 io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
 io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
 io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
 io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle(SecurityHandler_Subclass.zig:296)
 io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
 io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(RolesAllowedInterceptor_Bean.zig:386)
 io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
 io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
 io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
 .controller.Controller_Subclass.getBy(Controller_Subclass.zig:336)
 .controller.Controller_ClientProxy.getBy(Controller_ClientProxy.zig:189)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.base/java.lang.reflect.Method.invoke(Method.java:566)
 org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
 org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
 org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
 org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
 org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
 org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
 org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
 org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
 org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
 org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
 org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)

org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by geoand** [comment]
Can you provide a sample of your code? It's not easy to see what's going on currently

**Comment by mkouba** [comment]
@geoand is right - we cannot proceed without a reproducer app. I did try to test the following configuration and it worked just fine:

```java
   @ApplicationScoped
    public static class Controller {

        private final IUseCase useCase;

        @Inject
        public Controller(IUseCase getUseCase) {
            this.useCase = getUseCase;
        }
    }

    @ApplicationScoped
    public static class UseCase implements IUseCase {

        private IService service;

        @Inject
        public UseCase(IService webService) {
            this.service = webService;
            service.init();
        }
    }

    @ApplicationScoped
    public static class Service implements IService {

        @Override
        public void init() {
        }
    }

    interface IService {
        public void init();
    }

    interface IUseCase { }
```

**Comment by vinland-saga** [comment]
Greatly appreciate your help.
Thank you.

I will create today a sample application which showcases the problem.

**Comment by vinland-saga** [comment]
here is the sample app:
https://github.com/vinland-saga/quarkusBugSample

when running it, it give the expected behavior: no NPE, no exceptions
which is different from what I get in the production app that we are building (as shown in stacktrace) with the same implementation of injections and applicationScoped

I will again take a look and try to pinpoint the issue.


Greatly appreciate your time.

**Comment by mkouba** [comment]
I'm going to close this issue. @vinland-saga Feel free to reopen if you find a way to reproduce the NPE.

**Comment by L154x** [comment]
@vinland-saga I'm experiencing the same issue, how was it solved?
