### ISSUE TITLE
Update to SmallRye Fault Tolerance 5.6.0 / 6.1.0

### ISSUE THREAD

**Issue by ThoSap** [quarkusio/quarkus#28822]
### Description

Updating to SmallRye Fault Tolerancre 5.6.0 / 6.1.0 would finally bring the **rate limiting** onto the table 🥳
https://github.com/smallrye/smallrye-fault-tolerance/releases/tag/5.6.0

**Comment by Ladicek** [comment]
How did you notice so fast?! :-) PR to Quarkus will follow tomorrow.

**Comment by ThoSap** [comment]
I'm watching the releases of `SmallRye Fault Tolerancre` on GitHub ^^
Oh and another one ;)
https://github.com/smallrye/smallrye-fault-tolerance/releases/tag/6.1.0

**Comment by Ladicek** [comment]
6.1.0 is a `jakarta.*` counterpart of 5.6.0 (which is still `javax.*`), so it will actually be both 5.6.0 and 6.1.0.

**Comment by ThoSap** [comment]
Is this going to be merged in Quarkus `2.14.0.Final`?

**Comment by Ladicek** [comment]
2.14 was already branched, so it's landing in 2.15.
