### ISSUE TITLE
Hibernate-validation fails to validate @Column(unique = true)

### ISSUE THREAD

**Issue by clochardpagan** [quarkusio/quarkus#2883]
Column annotation with unique = true, is not accounted as expected.

Field is defined as follow:

```
@Entity
public class User extends PanacheEntity {
    ...
    @Email
    @NotNull
    @NotBlank
    @Column(unique = true)
    public String email;
    ...
}
```
Call of validator in resource:
```
@Inject
Validator validator;

...

@POST
@Path("/save")
@Transactional
public Response save(User user) {        
    Set<ConstraintViolation<User>> violations = validator.validate(user);
    if (violations.isEmpty()) {
      user.persist();
      return Response.ok(user).build();
    } 
    ...
}
```

**Expected behavior**
Some ConstraintViolation<> returned from validation.validate(user).

**Actual behavior**
Validation passes and we have exception from DB layer:
> org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "smth"

**To Reproduce**
1. Create any domain class
2. Add any fields
3. Add `@Column(unique = true)` annotation to it
4. Create object A
5. Try to validate A - validation will pass
6. Persist A
7. Create object B
8. Try to validate B - validation will pass ????
9. Persist B - exception from DB

**Comment by emmanuelbernard** [comment]
This is the expected behavior. There is no way to reliably validate that an object has a unique property via Bean Validation. There would be at best race condition. Also, `@Column` is not considered by Bean Validation

**Comment by emmanuelbernard** [comment]
I'd recommend you write your own query logic to validate but again it will be best effort unless you use transaction at a serializable level otherwise you are not protecting against phantom reads. It is very unlikely your DBA set up your database to guarantee that.
