### ISSUE TITLE
[Extension Proposal] Web Assets extension

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#28840]
### Description

It would deal with everything for a webapp but html
- scss to css
- fonts
- javascript (minification...)
- image optim
- ...

It's a missing piece for Renarde,  but at the same time it should be usable without it, so better have an extension for it.

It could be consumed directly by Qute template through helper tags, something like this (and equivalent for style and all):
```html
{#web-assets script="my-script.js" /}
```
would render:
```html

<script>
	content of my-script.js
</script>
```

```html
{#web-assets script="my-script.js" served /}
```
would render:
```html
<script src="/webmedia/my-script.js">
	content
</script>
```

This extension would also provide entrypoint for other extensions to use its features.

### Repository name

quarkus-web-assets

### Short description

Provide processing and helpers for you web-app assets (js, css, scss, ...).

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-web-assets/dev/

### Repository Topics

- quarkus-extension
- web
- assets
- frontend
- renarde

### Team Members

- @ia3andy 
- @mkouba 
- @phillip-kruger 
- @FroMage

**Comment by ia3andy** [comment]
@phillip-kruger it would be nice to also have a way to pull javascript libraries like webjar does but configurable through a list in the config (instead of having one dep per library). WDYT?

**Comment by ia3andy** [comment]
I am so conflicted between delegating all this shit to npm or using Java, because in the end this is kinda what webpack does. 

Still we should be able to cover much of it from Java so I think it's worth a shot.

**Comment by phillip-kruger** [comment]
I think the whole point of doing it using dependencies is (1) That is how dependencies is managed in Java (2) Dependabot can notify you if there is a update (3) the dependencies will follow the graph, pulling in all the needed other dependencies. So I do not think we would manage this in config. (Let dependencies live with dependencies). However, what we can do is create bundles. So webjars (or similar) that contain a set of other dependencies. Like rather than pulling in every vaadin component by itself, we can have one vaadin components dependency. Or even sets that contain commonly used things in one bundle. Example 'lit' + 'route' + something = some meta dependency.

**Comment by melloware** [comment]
I forgot to mention you can see both plugins in action in my QuarkusFaces project: https://github.com/melloware/quarkus-faces

**Comment by maxandersen** [comment]
Why was this closed ?

interesting idea but why the name webmedia ? Webmedia is commonly used to refer to compression and streaming technologies. Thus using webmedia here is a misnomer is it not ?

**Comment by maxandersen** [comment]
Maybe webartifact ?

**Comment by gastaldi** [comment]
> Why was this closed ?

@maxandersen this issue is requesting the creation of https://github.com/quarkiverse/quarkus-webmedia, once the repository is created the issue is no longer necessary :)

About the name, I can revert https://github.com/quarkiverse/quarkiverse-devops/commit/2911e626b23a34d8a28fb65005eb34c996b56a20 until we settle on a name

**Comment by ia3andy** [comment]
media-type (https://www.iana.org/assignments/media-types/media-types.xhtml) -> web -> web-media

**Comment by ia3andy** [comment]
> Why was this closed ?
> 
> interesting idea but why the name webmedia ? Webmedia is commonly used to refer to compression and streaming technologies. Thus using webmedia here is a misnomer is it not ?

web-media is everything around the html page, streaming and video is part of it, but images, styles, fonts are also. It seems to be a perfect fit IMO

**Comment by ia3andy** [comment]
@melloware how does it compare to https://github.com/wro4j/wro4j?

**Comment by Ladicek** [comment]
I thought the traditional overarching name for scripts, stylesheets, image atlases etc. is _assets_, but _resources_ is also fine. I agree with Max that _media_ sounds like something else [to me].

**Comment by ia3andy** [comment]
> I thought the traditional overarching name for scripts, stylesheets, image atlases etc. is _assets_, but _resources_ is also fine. I agree with Max that _media_ sounds like something else [to me].

yeah you are right Lad `quarkus-web-assets` is a good name

**Comment by ia3andy** [comment]
@Ladicek @gastaldi @maxandersen @FroMage @melloware @phillip-kruger could you  🚀 the previous comment if you approve.

**Comment by maxandersen** [comment]
Webassets works for me.

**Comment by ia3andy** [comment]
quarkus-webassets or quarkus-web-assets?

**Comment by phillip-kruger** [comment]
I would not cast anything in stone yet t.b.h. let's  build an extension first and see what we can do. At some point I was thinking of going a bit finer grain. Like a css preprocessor extension. Then another for ts. Then another for images. Etc. But maybe grouping them together is the way to go. Not sure. But I think we can defer this decision to later ? Or not ?

**Comment by ia3andy** [comment]
> I would not cast anything in stone yet t.b.h. let's build an extension first and see what we can do. At some point I was thinking of going a bit finer grain. Like a css preprocessor extension. Then another for ts. Then another for images. Etc. But maybe grouping them together is the way to go. Not sure. But I think we can defer this decision to later ? Or not ?

for splitting, if it wasn't Quarkus, I would agree as such libraries are making your app grow large so you want to be able to pick only what you need. 

With Quarkus, it's only build time concern so I think having all together makes it a lot whole simpler.

**Comment by FroMage** [comment]
This might be useful for inspiration: https://guides.rubyonrails.org/asset_pipeline.html

**Comment by ia3andy** [comment]
thanks @FroMage it's indeed a really good inspiration
