### ISSUE TITLE
Transform `-D` arguments to system properties

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2885]
Transform `-D` arguments to system properties so that users can just append properties to the command and don't need to jump back and forth.

Currently users have to pass properties prior to`-jar` - e.g. `java -Dfoo=bar -Dgoo=baz -jar myApplication-runner.jar`

it would be helpful to support also following style `java -jar myApplication-runner.jar -Dfoo=bar -Dgoo=baz -D...`

This works for Thorntail and some other projects, we should have similar usability experience

**Comment by gsmet** [comment]
This is a duplicate of https://github.com/quarkusio/quarkus/issues/372 .
