### ISSUE TITLE
Update the MicroProfile Health guide and quickstart

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2886]
We updated to 2.0 which introduces quite a lot of changes, especially the separate readiness/liveness probe.

The guide and the quickstart should be updated to take that into account.

**Comment by gsmet** [comment]
@antoinesd any chance you could take a look at that one for the next release?

**Comment by antoinesd** [comment]
Yes @gsmet, I'm on it

**Comment by gsmet** [comment]
Done by @xstefank in the end.

**Comment by xstefank** [comment]
ah, sorry, I totally missed this issue. @antoinesd sorry for this.
