### ISSUE TITLE
Quarkus CLI removes comments from pom.xml

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#28873]
### Describe the bug

My team recently tried to "introduce" the CLI in an old project (which basically means reformatting the POM with the CLI as a first step) but the CLI removed all existing XML comments from the POM. We need these comments for maintenance purposes, so the CLI can't be used in that project until it stops removing XML comments.

### Expected behavior

XML comments from the POM are preserved.

### Actual behavior

XML comments from the POM are removed.

### How to Reproduce?

Reproducer: https://github.com/gwenneg/quarkus-cli-pom-comment

1. `quarkus extension add quarkus-cache`
2. `git diff`: the CLI removed an XML comment

### Quarkus version or git rev

2.13.3.Final

**Comment by gwenneg** [comment]
Related thread on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20CLI.3A.20preserve.20comments.20in.20pom.2Exml.3F/near/306180835

**Comment by maxandersen** [comment]
@gastaldi didn't we fix this earlier ?

**Comment by gsmet** [comment]
Yes, this is fixed.
