### ISSUE TITLE
Gradle plugin output tracking breaks if `quarkus.package.output-directory` is configured

### ISSUE THREAD

**Issue by britter** [quarkusio/quarkus#28897]
### Describe the bug

The `QuarkusBuild` task does not provide a way to reconfigure it's output location. Instead it's hardcoded to `$buildDir/quarkus-app`. At the same time, users can configure the output location by setting the `quarkus.package.output-directory`. This will cause the build to create the output in a different location. However Gradle is unaware of this location, so UP-TO-DATE checking and build caching breaks because Gradle will track the location returned from `QuarkusBuild.getFastJar()`. Furthermore it's not possible to easily consume `QuarkusBuild` output from another task, because `QuarkusBuild` is unaware of the changed location.

### Expected behavior

When changing the output location via `quarkus.package.output-directory` this should also change the value returned from `QuarkusBuild.getFastJar()` accordingly. #28896 is related to this.

### Actual behavior

Gradle is unaware of changes to `QuarkusBuild` output location configured by `quarkus.package.output-directory`

**Comment by glefloch** [comment]
Thanks for reporting this issue, we need to take care of that variable.

**Comment by geoand** [comment]
@jacobdotcosta would you be interested in this?

**Comment by jacobdotcosta** [comment]
Yes, I'll take a look.
