### ISSUE TITLE
Make Gradle plugin configuration more idiomatic

### ISSUE THREAD

**Issue by britter** [quarkusio/quarkus#28896]
### Describe the bug

Currently in order to configure the behavior of the Quarkus Gradle plugin, a build author needs to set project properties, e.g. if I want to change the package type I need to add the following to the build script:

```kotlin
ext {
  set("quarkus.package.type", "mutable-jar")
}
```

From a Gradle perspective this is a quite strange way to configure a plugin, especially because the plugin adds a custom project extension, which would be the place a Gradle build author would look for configuration options.

### Expected behavior

The QuarkusExtension that is added to the build should provide ways to configure aspects of the packaging:

```kotlin
quarkus {
    package {
        type.set("mutable-jar")
    }
}
```

### Actual behavior

QuarkusExtension does not provide options to configure packaging so one has to know that it's configured via project properties.

**Comment by geoand** [comment]
Makes perfect sense to me.

**Comment by geoand** [comment]
@acosta would you be interested in this?

**Comment by glefloch** [comment]
@geoand that would having configuration both in the build file and in the application.properties file. Is that ok ?

**Comment by geoand** [comment]
I would say that whatever is in `application.properties` overrides what's in the build file, that's what we've done so far.

The way I see it, this issue is just about providing an idiomatic way of setting some properties

**Comment by geoand** [comment]
> will require creating a field for each of the properties being set (e.g. type for quarkus.package.type). Is this acceptable for all the 29 properties with prefix quarkus.package

I personally don't think we should do this but only allow setting some of the basic ones like this. WDYT @glefloch ?

> On the other hand, package is a Java reserved word and I'm not sure I can use it as a method name.

Good point, I have no idea of the DSL allows it or not.

**Comment by glefloch** [comment]
As @geoand mentionned, I don't think we should expose all properties in the build file but limit to some specific properties. 
Using the gradle DSL we should be able to do something like:
```
quarkus {
    properties {
        "package.type" = "mutable-jar"
    }
}
```
