### ISSUE TITLE
[2.14.CR1] Keycloak is failing to build

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#28893]
### Describe the bug

Trying to build Keycloak using 2.14.CR1 results in this error:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.14.0.CR1:build (default) on project keycloak-quarkus-server-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.steps.ApplicationIndexBuildStep#build threw an exception: java.lang.NoSuchMethodError: 'void org.jboss.jandex.Indexer.index(java.io.InputStream)'
[ERROR]         at io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:49)
[ERROR]         at io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:34)
[ERROR]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2812)
[ERROR]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2883)
[ERROR]         at io.quarkus.deployment.steps.ApplicationIndexBuildStep.build(ApplicationIndexBuildStep.java:34)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

Successful buid

### Actual behavior

Build failures

### How to Reproduce?

1. Clone https://github.com/keycloak/keycloak
2. cd keycloak
3. mvn -Pdistribution -DskipTests clean install
4. cd quarkus
5. ./set-quarkus-version.sh 2.14.0.CR1
6. mvn -DskipTests clean install

### Output of `java -version`

openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

### Quarkus version or git rev

2.14.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /pedroigor/development/tools/maven/current Java version: 18.0.2.1, vendor: Oracle Corporation, runtime: /pedroigor/development/sdk/java/jdk-18 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.19.16-200.fc36.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@Ladicek is this an issue with the Jandex update?

**Comment by Ladicek** [comment]
`java.lang.NoSuchMethodError: 'void org.jboss.jandex.Indexer.index(java.io.InputStream)'` looks like something is pulling Jandex 2 on classpath. #28941 should help, but in the meantime, Keycloak can look at its dependency management to figure out what brings Jandex 2 into play.

**Comment by pedroigor** [comment]
@geoand @Ladicek Removing Jandex 2 from classpath fixes the issue.

We also had another error due to the new version being set to Caffeine but we can solve by upgrading Infinispan.

Running our CI here https://github.com/pedroigor/keycloak/actions/runs/3372670628.

**Comment by pedroigor** [comment]
Thanks, main tests passing.

**Comment by geoand** [comment]
Thanks for the update!
