### ISSUE TITLE
Deadlock when using 'System.exit(1)'

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#28899]
### Describe the bug

If `System.exit` is used on the `quarkus-main-thread` the complete application deadlocks. If i execute `System.exit` on a different thread then the application terminates as expected.

Maybe this is an expected behaviour as stated in [Quarkus#blockingExit](https://javadoc.io/static/io.quarkus/quarkus-core/2.13.3.Final/io/quarkus/runtime/Quarkus.html#blockingExit()) but it feels odd. 

The behavior should at least be explicitly described in the documentation. What do you think?

### How to Reproduce?

1. [deadlock_reproducer.zip](https://github.com/quarkusio/quarkus/files/9886533/deadlock_reproducer.zip)
2. `./mvnw quarkus:dev`

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus 2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by geoand** [comment]
This is expected as per the Javadoc you linked:

```
Starts the shutdown process, then waits for the application to shut down. Must not be called by the main thread, or a deadlock will result.
```

**Comment by geoand** [comment]
> The behavior should at least be explicitly described in the documentation. What do you think?

Which documentation do you mean here? I don't see `Quarkus.blockingExit` being explicitly mentioned in any docs.

**Comment by mschorsch** [comment]
> > The behavior should at least be explicitly described in the documentation. What do you think?
> 
> Which documentation do you mean here? I don't see `Quarkus.blockingExit` being explicitly mentioned in any docs.

Thats the problem, the Quarkus documentation does not mention this behaviour.

**Comment by geoand** [comment]
The Javadoc does however. 

I am interested in hearing where you would expect to see this behavior mentioned. Asking because if we just add it to some random place, there is little chance people will actually see it.

**Comment by geoand** [comment]
Actually, I have another idea... We can detect if this being called on the main thread and print an error

**Comment by mschorsch** [comment]
> Actually, I have another idea... We can detect if this being called on the main thread and print an error

Great 👍

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28939
