### ISSUE TITLE
Something like BeanPostProcessor in Spring framework

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#28918]
### Description

I introduce some external libraries into my projects, these libraries contain some managed beans that I would like to customize further.

In spring I can use BeanPostProcessor, what’s the equivalent mechanism in Quarkus ArC?

**Comment by geoand** [comment]
What kind of customization would you like to perform?

**Comment by Dieken** [comment]
> What kind of customization would you like to perform?

This is an example of BeanPostProcessor, it registers some MyBatis customized type handlers to the SqlSessionFactory instance, this  has to be done just after the creation of SqlSessionFactory instance, because other beans will register MyBatis mappers to the SqlSessionFactory instance, the registration of mappers depends on those customized type handlers.

I tried to use @Interceptor and @PostConstruct, but I can't put @InterceptorBinding on the SqlSessionFactory bean creation because that's in a third-party library.

```java
package my.example;

import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.stereotype.Component;

@Component
public class SqlSessionFactoryPostProcessor implements BeanPostProcessor {

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof SqlSessionFactory) {
            SqlSessionFactory factory = (SqlSessionFactory) bean;
            factory.getConfiguration().getTypeHandlerRegistry().register(..., SomeTypeHandler.class);
        }

        return bean;
    }
}
```

**Comment by geoand** [comment]
I am pretty sure we don't have anything like that at runtime code but @mkouba can say more

**Comment by Dieken** [comment]
It doesn't have to be at runtime, I need some magic at build time to insert some further initialization code after bean creation.

**Comment by Dieken** [comment]
Maybe create a Quarkus extension to support annotation @InterceptorFor(Foo.class):

```java
@InterceptorFor(SqlSessionFactory.class)
public class MoreInitialization {

    @PostConstruct
     public void postConstruct(InvocationContext ctx) {
         …
     }
 }
 ```

Quarkus automatically binds this interceptor to some bean which implements or extends `SqlSessionFactory`.

**Comment by geoand** [comment]
@mkouba do we have anything like ^ already?

**Comment by mkouba** [comment]
So first of all @geoand is right that we can't do anything like this at runtime because beans are discovered and metadata are completed during build.

> I tried to use @interceptor and @PostConstruct, but I can't put @InterceptorBinding on the SqlSessionFactory bean creation because that's in a third-party library.

You can register an [annotation transformer](https://quarkus.io/guides/cdi-integration#annotations_transformer_build_item) and add the interceptor binding to any bean class.

**Comment by geoand** [comment]
Closing as per Martin's comment.

Feel free to comment and/or reopen if you are not satisfied with the resolution

**Comment by Dieken** [comment]
Could you help how to complete the logic in the comment?  @mkouba 

```java
package io.quarkiverse.interceptor.deployment;

import io.quarkiverse.interceptor.runtime.InterceptorFor;
import io.quarkus.arc.deployment.AnnotationsTransformerBuildItem;
import io.quarkus.arc.processor.AnnotationsTransformer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.FeatureBuildItem;
import javax.interceptor.InterceptorBinding;
import org.jboss.jandex.AnnotationTarget;
import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.DotName;
import org.jboss.jandex.Type;

class InterceptorProcessor {

    private static final String FEATURE = "interceptor";
    private static final DotName INTECEPTOR_FOR = DotName.createSimple(InterceptorFor.class.getName());

    @BuildStep
    FeatureBuildItem feature() {
        return new FeatureBuildItem(FEATURE);
    }

    @BuildStep
    AnnotationsTransformerBuildItem transform() {
        return new AnnotationsTransformerBuildItem(
                AnnotationsTransformer.builder()
                        .appliesTo(AnnotationTarget.Kind.CLASS)
                        .whenContainsAll(InterceptorFor.class, InterceptorBinding.class)
                        .transform(ctx -> {
                            ClassInfo interceptorBinding = ctx.getTarget().asClass();
                            Type interceptorFor = interceptorBinding.classAnnotation(INTECEPTOR_FOR)
                                    .value().asClass();

                            // how to add `interceptorBinding` annotation to the `interceptorFor` class?

                            ctx.transform().done();
                        }));
    }
}
```

My interceptor:

```
@Interceptor
@TestBinding
public class TestInterceptor {
  @PostConstruct
  public void postConstruct(InvocationContext ctx) {
       ...
  }
}

@InterceptorFor(SqlSessionFactory.class)   // <--- need add `@TestBinding` to `SqlSessionFactory`
@InterceptorBinding
@Target(TYPE)
@Retention(RUNTIME)
public @interface TestBinding {
}
```

**Comment by mkouba** [comment]
> Could you help how to complete the logic in the comment?

If you need to add the `@TestBinding` to the `SqlSessionFactory` then you'll have to transform the annotations of the `SqlSessionFactory`, i.e. something like this should work:

```java
 @BuildStep
  AnnotationsTransformerBuildItem transform() {
        DotName sqlSessionFactoryName = DotName.createSimple(SqlSessionFactoryName.class.getName());
        return new AnnotationsTransformerBuildItem(
                   AnnotationsTransformer.builder()
                        .appliesTo(AnnotationTarget.Kind.CLASS)
                        .when(tc -> tc.getTarget().asClass().name().equals(sqlSessionFactoryName))
                        .transform(ctx -> ctx.transform().add(TestBinding.class).done()));
}
```

**Comment by Dieken** [comment]
Is it possible to generalize to an special annotation `@InterceptorFor(SomeClass)` as demonstrated above? I wouldn’t like to write a specialized Quarkus extension for each intercepted class.

**Comment by mkouba** [comment]
> Is it possible to generalize to an special annotation `@InterceptorFor(SomeClass)` as demonstrated above? I wouldn’t like to write a specialized Quarkus extension for each intercepted class.

Well, the problem with this approach is that interceptor bindings _should not_ define which beans should be annotated with the binding and thus intercepted. The bindings _should be_ used to associate interceptors with beans. Also it would not make any sense for interceptor binding types with members.

**Comment by Dieken** [comment]
The requirement is to intercept class constructor like Spring BeanPostProcessor,  `@PostConstruct` interceptor is the closest thing I can find, it's indeed a little weird to know beans first before intercepting.

This injection is totally static and can be done at build time in theory, but I can't figure out how to do with Quarkus ArC which implementation is rather complex to me.

**Comment by mkouba** [comment]
> The requirement is to intercept class constructor like Spring BeanPostProcessor, @PostConstruct interceptor is the closest thing I can find,

In CDI, there's also `@AroundConstruct`.

>  it's indeed a little weird to know beans first before intercepting.

It depends. But it's definitely not weird in Quarkus, quite the opposite ;-)

> This injection is totally static and can be done at build time in theory, but I can't figure out how to do with Quarkus ArC which implementation is rather complex to me.

I'm not sure I fully understand... CDI injection is static and ArC does resolve all injection point at build time. You can still use programmatic lookup at runtime, but there are [some limitations](https://quarkus.io/guides/cdi-reference#remove_unused_beans).
