### ISSUE TITLE
Unable to run native image built using maven + jib on arm64 using new base image 

### ISSUE THREAD

**Issue by thedewpoint** [quarkusio/quarkus#28933]
### Describe the bug

I was able to successfully build a native image for arm64 using the new base image. I have these 2 properties set in my `application.properties` file

```properties
quarkus.jib.platforms=linux/arm64
quarkus.jib.base-native-image=quay.io/quarkus/quarkus-micro-image:2.0
```

and I build /deploy it with this command
`mvn package $MAVEN_CLI_OPTS -Pnative -DskipTests -Dquarkus.container-image.image=$AWS_ECR:latest -Dquarkus.container-image.push=true -Dquarkus.container-image.username=AWS -Dquarkus.container-image.password=$(cat password.txt)`

I have the following dependency

```xml
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-jib</artifactId>
    </dependency>
```

Everything seems to build properly but when I try to run the image that gets built on an arm64 machine i get the classic
`standard_init_linux.go:228: exec user process caused: exec format error`

Is there anything wrong with the way I built this?

### Expected behavior

I expected the app to start successfully running on an arm64 device

### Actual behavior

application does not start

### How to Reproduce?

I provided the steps above, the application is a boilerplate generated from the quarkus cli without any additional functionality

**Comment by geoand** [comment]
@gastaldi as you have an M1, can you try this and see if it works or not for you?

Thanks

**Comment by gastaldi** [comment]
Can you paste the full stacktrace? I tried to reproduce locally but I have no idea what is the value of `AWS_ECR` in `-Dquarkus.container-image.image=$AWS_ECR:latest`

**Comment by gastaldi** [comment]
I haven't used JIB, but I can confirm that doing a build in a container (`-Dquarkus.native.container-build=true`) gives the same error when running it: `exec format error: target/code-with-quarkus-1.0.0-SNAPSHOT-runner`

**Comment by thedewpoint** [comment]
@gastaldi @geoand is there any other info i can provide that would be helpful? Or anyone else we should tag in?

**Comment by geoand** [comment]
I have no idea TBH

**Comment by thedewpoint** [comment]
@cescoffier maybe I opened this in the wrong repo, but maybe you could also take a look?

**Comment by cescoffier** [comment]
If you build from an ARM cpu you get a ARM container. Is the machine running the container using an ARM64 architecture?

**Comment by thedewpoint** [comment]
@cescoffier no I was building for multi-architecture. I was building for amd64 and arm64 originally using the platforms configuration

**Comment by cescoffier** [comment]
Can you show me how you did that? I don't believe it's supported.

**Comment by cescoffier** [comment]
Ah using jib platforms? We need to ask @geoand but I doubt it would trigger a native build for that platform (not without emulation)

**Comment by geoand** [comment]
https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image is the Jib platforms feature

**Comment by thedewpoint** [comment]
Ah ok so I guess what you're saying is there is 2 components to this, the native image being built and then the native image being containerized.
The native image isn't being built on an ARM based architecture so even if i containerize it for one it's still not compatible.

For my use case, I guess I need to update my CI to use an ARM based container to actually build the native image, and then containerize it for ARM using JIB. If that sounds correct then I think this isn't an issue with quarkus but more a misunderstanding on my part and I will close the ticket. Can you confirm my understanding @cescoffier

**Comment by cescoffier** [comment]
@thedewpoint Yes. We are working on a GH Action workflow to do that (we already have something, but it's pretty complex).
Look at the quarkus superheroes workflows (and fasten your seat belt): https://github.com/quarkusio/quarkus-super-heroes/blob/main/.github/workflows/build-push-container-images.yml

**Comment by thedewpoint** [comment]
Thank you!
