### ISSUE TITLE
Native build fails on request with Kotlin-"when"- expression

### ISSUE THREAD

**Issue by SebastianHanke** [quarkusio/quarkus#28954]
Expected behavior

The jar, native and development build should behave the same.

Actual behavior

After native build. Request to resource fails (at Kotlin "when"-expression). 
Other builds work without error.

org.jboss.resteasy.spi.UnhandledException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class de.xxx.yyy.zzz.FindByNameResult$Success and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

How to Reproduce?

- create a resource. 
- introduce when expression to return response.
- build native with ```./gradlew build -Dquarkus.package.type=native```
- call endpoint with success response

```kotlin
fun fetchSomething(): Response {
        return when (val profile = repository.findByName("myName")) {
            is FindByNameResult.NotFound         -> Response
                .noContent()
                .build()

            is FindByNameResult.Success          -> Response
                .ok()
                .entity(profile)
                .build()
        }
    }
```

Output of uname -a or ver

Darwin Kernel Version 21.6.0

Output of java -version

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

GraalVM version (if different from Java)

No response

Quarkus version or git rev

2.13.3.Final

Build tool (ie. output of mvnw --version or gradlew --version)

Gradle 7.3.3
Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (GraalVM Community 17.0.2+8-jvmci-22.0-b05)

Additional information

No response

**Comment by geoand** [comment]
Any chance you can provide a sample application that fails like you mentioned?

**Comment by SebastianHanke** [comment]
[demo.zip](https://github.com/quarkusio/quarkus/files/9904233/demo.zip)

**Comment by geoand** [comment]
There is not much we can do in Quarkus for this case. You will need to [register](https://quarkus.io/guides/writing-native-applications-tips#registerForReflection) these classes for reflection manually.
