### ISSUE TITLE
Keycloak Policy enforcer supposed to work with Client Roles / Resource_access.{client-id}.roles?

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#28965]
### Description

Based on some testing, (unless I have a config incorrect, but is difficult to tell give the complexities), the Policy Enforcement for Keycloak quarkus-keycloak-authorization works with Realm Roles, but is it also supposed to work with Client Roles that appear under the `resource_access.{client-id}.roles` path in the JWT?

I just get 403 responses when trying to use Resource access.  I update the roles path as well to: `quarkus.oidc.roles.role-claim-path=resource_access/backend-service/roles` but this did not seem to work.

Is there any example of this usage?

What i have found is required to make PEP work with regular roles is something like:

```properties
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.tls.verification=none
quarkus.oidc.token.issuer=any

quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.lazy-load-paths=false
quarkus.keycloak.policy-enforcer.paths.1.path=/account
quarkus.keycloak.policy-enforcer.http-method-as-scope=true
```

and authorization config:

```json
{
    "allowRemoteResourceManagement": true,
    "policyEnforcementMode": "ENFORCING",
    "resources": [
      {
        "name": "Account",
        "ownerManagedAccess": false,
        "attributes": {},
        "_id": "4f2bde8d-41a6-4e46-8cbf-2840ed1923fd",
        "uris": [
          "/account"
        ],
        "scopes": [
          {
            "name": "GET"
          }
        ],
        "icon_uri": ""
      }
    ],
    "policies": [
      {
        "id": "0af1f193-0d4a-4352-b248-b149b6266324",
        "name": "has Account Manager",
        "description": "",
        "type": "role",
        "logic": "POSITIVE",
        "decisionStrategy": "UNANIMOUS",
        "config": {
            "roles": "[{\"id\":\"AccountManager\",\"required\":true},{\"id\":\"AccountManager\",\"required\":false}]"
        }
      },
      {
        "id": "1a53d29d-00c7-46f8-9384-c50b3eff60ed",
        "name": "Account Permission",
        "description": "",
        "type": "resource",
        "logic": "POSITIVE",
        "decisionStrategy": "UNANIMOUS",
        "config": {
          "resources": "[\"Account\"]",
          "applyPolicies": "[\"has Account Manager\"]"
        }
      }
    ],
    "scopes": [
      {
        "id": "6759f487-be0e-4e2f-8560-38b5b3b4ae32",
        "name": "GET",
        "iconUri": "",
        "displayName": ""
      }
    ],
    "decisionStrategy": "UNANIMOUS"
  }
```

I am using `quarkus-hibernate-reactive-rest-data-panache` to generate the endpoints

**Comment by sberyozkin** [comment]
@StephenOTT I think this question should be asked at https://github.com/keycloak/keycloak/discussions,
FYI, the roles which are available in the token can be used for the Quarkus RBAC decisions made at the Quarkus level, Keycloak Authorization is about Keycloak returning an authorization decision based on the Keycloak authorization policies set up in Keycloak

**Comment by sberyozkin** [comment]
@StephenOTT Let me close this issue, sorry, I can't move it to Discussions for some reasons (GitHub reports `Unable to convert this issue to a discussion. Category is not accessible to the actor`), please try to convert it to either a Keycloak or Quarkus discussion. It looks like to me you may not need to use `quarkus-keycloak-authorization` if you'd like to use the roles, lets continue the discussion in Discussions

**Comment by StephenOTT** [comment]
Discussion raised in https://github.com/quarkusio/quarkus/discussions/28989
