### ISSUE TITLE
Quarkus cache size modification at runtime

### ISSUE THREAD

**Issue by Jojal** [quarkusio/quarkus#28966]
### Description

Actually the cache configuration is only possible at build time. So it's not possible to override the cache size at runtime.
It would be a good enhancement to allow the possibility to override cache configuration at runtime.

**Comment by Jojal** [comment]
Hi, 
Is there an activity planned for this issue guys :) ?
Thanks

**Comment by gwenneg** [comment]
Sorry for the delay before my answer. Unfortunately I'm super busy with several high priority topics so I can't take a look right now, but I'll try to check tomorrow if that enhancement request is possible from a Caffeine perspective.

**Comment by gwenneg** [comment]
We'll continue in #29934.
