### ISSUE TITLE
Quarkus Maven Plugin unable to handle maven exclusions

### ISSUE THREAD

**Issue by javaduke** [quarkusio/quarkus#28971]
### Describe the bug

One of the artifacts in my POM has `ehcache` as a dependency, but when I'm trying to exclude it as follows:
```
        <dependency>
            <groupId>io.quarkiverse.cxf</groupId>
            <artifactId>quarkus-cxf-rt-ws-security</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.ehcache</groupId>
                    <artifactId>ehcache</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
I'm getting this error:
```
[ERROR]         [error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.RuntimeException: Could not resolve artifact org.ehcache:ehcache::jar among the runtime dependencies of the application
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addIndexDependencyPaths(ApplicationArchiveBuildStep.java:188)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:151)
[ERROR]         at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:108)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:835)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

Is it a known bug?

I tried to downgrade to the older version (from 2.13.0.Final to 2.12.1.Final) and it worked, so it must be a regression.

### Expected behavior

Successful build without an error.

### Actual behavior

Plugin throws java.lang.RuntimeException.

**Comment by aloubyansky** [comment]
The actual reason is
```
	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.RuntimeException: Additional dependency to be indexed (added via 'quarkus.index-dependency' configuration) org.ehcache:ehcache:jakarta:jar could not be found among the runtime dependencies of the application. Either remove the indexing configuration or add the dependency to your build system.
```
We should probably skip missing dependencies instead of failing.
FYI @ppalaga, it's related to CXF

**Comment by ppalaga** [comment]
@javaduke could you please explain why you are excluding ehcache?

@aloubyansky I must say I'd prefer throwing an exception for non-existent artifacts. The new behavior hides potential issues caused by typos, artifact renames, etc. I think @javaduke's issue should have been fixed in Quarkus CXF. Could we please revert https://github.com/quarkusio/quarkus/pull/33645 ?

**Comment by ppalaga** [comment]
> I had issues with ehcache when compiling to native, I had to add --initialize-at-run-time for a lot of ehcache classes, so I thought it would be easier if I just exclude it from the dependencies.

That's exactly what [EhcacheProcessor](https://github.com/quarkiverse/quarkus-cxf/blob/53449d882e62101d7ccca2cba5146e9fab6aaf5a/extensions/ws-security/deployment/src/main/java/io/quarkiverse/cxf/ws/security/deployment/EhcacheProcessor.java) aims at doing. Was it with some recent version of quarkus-cxf? Some hits for reproducing would be nice.

**Comment by javaduke** [comment]
Actually there were more problematic classes, this is what I have in my build args:
```
                    --initialize-at-run-time=org.ehcache.sizeof.impl.JvmInformation,
                    --initialize-at-run-time=org.ehcache.jsr107.Eh107CacheManager,
                    --initialize-at-run-time=org.ehcache.sizeof.impl.AgentSizeOf,
                    --initialize-at-run-time=org.ehcache.shadow.org.terracotta.offheapstore.paging.UpfrontAllocatingPageSource,
                    --initialize-at-run-time=org.ehcache.shadow.org.terracotta.offheapstore.util.PhysicalMemory
```

The `quarkus-cxf-rt-ws-security` version I used is 1.5.1.

**Comment by ppalaga** [comment]
1.5.1 is really old. We keep backporting to 1.5 branch. Could you please try with 1.5.14?

**Comment by javaduke** [comment]
Sure, I'll give it a try later this week.

**Comment by aloubyansky** [comment]
@ppalaga right, I had that concern too about typos, otoh, other somewhat related config options are also implemented in this way, I.e. ignoring if a match isn't found. Basically it seemed like we might want to separate handling if dependencies from asserting their presence, I.e. configuring that some artifacts are required to be present.

**Comment by ppalaga** [comment]
> Basically it seemed like we might want to separate handling if dependencies from asserting their presence

We could perhaps add some sort of optional parameter to IndexDependencyBuildItem having default false?

**Comment by aloubyansky** [comment]
How would it be (re)configured though?

**Comment by ppalaga** [comment]
Ah, you mean it is bound to an end user config parameter? I admit, I have not thought of it. But looking at the current config options

```
quarkus.index-dependency."dependency-name".group-id
quarkus.index-dependency."dependency-name".artifact-id
quarkus.index-dependency."dependency-name".classifier
```

We could add a fourth one?

```
quarkus.index-dependency."dependency-name".optional
```

**Comment by javaduke** [comment]
I like this idea, looks very nice and clean. So is it a part of the `application.properties` or `application.yml` or is it configured somewhere else? Can it be a property in the pom.xml, just like, e.g. `quarkus.package.type` or `quarkus.native.additional-build-args`?

**Comment by ppalaga** [comment]
It definitely works in `application.properties` or `application.yml`. @aloubyansky might know whether it works in pom.xml
