### ISSUE TITLE
Native, micrometer: jvm_info_total unpopulated fields

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#28993]
### Describe the bug

Micrometer metrics seem to present unpopulated `jvm_info_total` fields in Native mode, e.g. 

```
jvm_info_total{runtime="unknown",vendor="Oracle Corporation",version="unknown",} 1.0
```

### Expected behavior

It should display more information, akin to JVM mode:

```
jvm_info_total{runtime="OpenJDK Runtime Environment",vendor="Eclipse Adoptium",version="17.0.5+8",} 1.0
```

### How to Reproduce?

Use https://github.com/quarkusio/quarkus-quickstarts/tree/main/micrometer-quickstart
```
./mvnw clean  package -Dnative 
./target/microprofile-metrics-quickstart-runner 
```
http://localhost:8080/q/metrics

### Output of `uname -a` or `ver`

Linux amd64

### Output of `java -version`

native-image 22.3.0.1-Final Mandrel Distribution (Java Version 17.0.5+8)

### Quarkus version or git rev

2.13.3.Final

**Comment by ebullient** [comment]
We return what is provided by System properties by the JVM: https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmInfoMetrics.java

This issue, in my opinion, should be raised against GraalVM.

**Comment by Karm** [comment]
Thx for the notes @ebullient,   (PR pending)
I patched GraalVM and it works for me now :+1: 

```
# HELP jvm_info_total JVM version info
# TYPE jvm_info_total counter
jvm_info_total{runtime="Substrate VM",vendor="Oracle Corporation",version="GraalVM 23.0.0-dev71c7f0d86e29 Java 17 Mandrel Distribution",} 1.0
```

**Comment by galderz** [comment]
FYI The patch that makes this work is https://github.com/oracle/graal/pull/5355
