### ISSUE TITLE
PanacheEntityResource not propagating javax.annotation.security

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#28995]
### security is not respected

we have custom endpoints and generated one with PanacheEntityResource.

all have security annotations. the security has no effect on PanacheEntityResource:

<img width="1430" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/8830888/199424971-65298bd6-b59b-4a88-acba-c7fba6c7d809.png">

@DenyAll but is still reachable:

<img width="1440" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/8830888/199425001-06fdca70-08a7-4c00-a87c-33e2065ec4eb.png">

### Expected behavior

work like intended as on the custom resources

### Actual behavior

security is not respected

**Comment by punkratz312** [comment]
thanks for the fix.


what about javax.transaction.Transactional ? 

we dont have dedicated tests yet for this scenario. 
if the annotation inheritance flow is discontuned and must be whilelisted maybe this one is missing too?

<img width="810" alt="image" src="https://user-images.githubusercontent.com/8830888/199536484-bade9e19-3e66-4aeb-8785-8c6b4e6e6cf7.png">

**Comment by punkratz312** [comment]
@geoand 
would you please consider releasing this critical security fix in 2.14 already? 
we need to release our product very soon and would highly appreciate the bugfix. thanks

**Comment by geoand** [comment]
@Sgitario should this be backported to 2.14 and perhaps 2.13?

**Comment by Sgitario** [comment]
Label to backport it to 2.14 added.

**Comment by punkratz312** [comment]
thank you ver much, awesome. i'm sure we have chosen the right framework for our product.

**Comment by geoand** [comment]
Thanks for your kind words :)
