### ISSUE TITLE
Core API needs a diagnostics interface

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#290]
We need a general diagnostics interface that can plug in to Maven, `javax.annotation.processing`, or a generic log output.  The interface should be able to capture error, warning, info, and debug level events with full source/location context.

This API would be consumed by build steps as well as the core code.

**Comment by gastaldi** [comment]
Is this still a thing? I see we have `io.quarkus.builder.diag.Diagnostic` which seems to provide the information above.

**Comment by dmlloyd** [comment]
I suppose the real issue isn't the lack of API, but rather that we aren't using it in any way at present.

**Comment by emmanuelbernard** [comment]
Hey there, I'm thinking of closing this issue. If you feel that would be wrong, can you say so and tell why.

**Comment by gastaldi** [comment]
+1 to close it

**Comment by dmlloyd** [comment]
It's still needed IMO - as are a few other really fundamental design changes - but OTOH we've scraped by with our current more ad-hoc error reporting.  Perhaps as the world turns, the right conditions to fix this will come around again in the future and we can address it then.
