### ISSUE TITLE
Not able to perform @Inject on class which implements ConstraintValidator

### ISSUE THREAD

**Issue by wargun02** [quarkusio/quarkus#2900]
Say if I have a custom validator annotation:

```
@Target( { ElementType.TYPE, ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.ANNOTATION_TYPE } )
@Retention( RetentionPolicy.RUNTIME )
@Constraint( validatedBy = PayloadValidator.class )
@Documented
public @interface PayloadCheck {
    String message( ) default "Not a valid blah blah";
    Class< ? >[] groups( ) default { };
    Class< ? extends Payload >[] payload( ) default { };
}
```

and custom payload class:
```
@PayloadCheck
public class CustomPayload {
    // all fields, setters and getters
}
```
and a custom implemented validator class:
```
@ApplicationScoped
public class PayloadValidator implements ConstraintValidator< PayloadCheck, Payload > {

    @Inject
    SomeQueryService someQueryServ;    // This will be "null"

    @Override
    public void initialize( PayloadCheck ca ) {
    }

    @Override
    public Class< ? extends Annotation > annotationType( ) {
        return PayloadCheck.class;
    }

    @Override
    public boolean isValid( CustomPayload payload, ConstraintValidatorContext ctx ) {
        someQueryServ.doSomething();    // someQueryServ will not be injected and will throw a NullPointerException
        return false;
    }
}
```

For any other class annotated with @ApplicationScope that has:
```
@Inject
Validator validator;
```
and later
```
CustomPayload customPayload = someWaysOfGettingThis();
Set< ConstraintViolation< CustomPayload > > violations = validator.validate( customPayload );
```

this will throw a NullPointerException because "someQueryServ" in PayloadValidator is not injected.

There are some issues and solution from other framework on this, which you may reference: 
[https://github.com/micronaut-projects/micronaut-core/issues/1143](https://github.com/micronaut-projects/micronaut-core/issues/1143)

[https://github.com/micronaut-projects/micronaut-core/blob/master/configurations/hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/ValidatorFactoryProvider.java#L74](https://github.com/micronaut-projects/micronaut-core/blob/master/configurations/hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/ValidatorFactoryProvider.java#L74)

Quarkus Version: 0.17.0
JDK Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)

Many thanks!

**Comment by emmanuelbernard** [comment]
CC @gsmet
