### ISSUE TITLE
Adding Content-Type for PGP in Quarkus RESTEasy Reactive

### ISSUE THREAD

**Issue by oo00spy00oo** [quarkusio/quarkus#29002]
### Description

Adding Content-Type for PGP in Quarkus RESTEasy Reactive

```
application/pgp-encrypted
application/pgp-keys
application/pgp-signature
```

Ref:
https://www.rfc-editor.org/rfc/rfc3156.html
https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by Ladicek** [comment]
Smallrye RESTEasy doesn't exist. What exactly do you have in mind?

**Comment by oo00spy00oo** [comment]
> Smallrye RESTEasy doesn't exist. What exactly do you have in mind?

I've just updated the name to Quarkus RESTEasy Reactive

**Comment by Ladicek** [comment]
Ah that makes a lot more sense, thanks.

CC @geoand @FroMage, I guess :-)

**Comment by geoand** [comment]
I am not sure what kind of support you are looking for.
Can you elaborate please?

**Comment by oo00spy00oo** [comment]
> I am not sure what kind of support you are looking for. Can you elaborate please?

In my case: when I send a request with header `Content-Type: application/pgp-encrypted` from client (E.g. Postman), I got the response with http code `415` (Unsupported Media Type)

**Comment by geoand** [comment]
But that is expected if you don't have a JAX REsource Method that consumes that type.

**Comment by oo00spy00oo** [comment]
> But that is expected if you don't have a JAX REsource Method that consumes that type.

My bad, add `@Consumes("application/pgp-encrypted")` and it worked. Thank for your support

**Comment by geoand** [comment]
Thanks for the update
