### ISSUE TITLE
quarkus-resteasy-reactive-jackson with JsonView AND SecureField

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#29010]
### Discussed in https://github.com/quarkusio/quarkus/discussions/28901

<div type='discussions-op-text'>

<sup>Originally posted by **lenped** October 28, 2022</sup>
In the Quarkus guide https://quarkus.io/guides/resteasy-reactive#json-serialisation  JsonView and SecureField is mentioned as supported. This seems to work if I am using one OR the other, but if I try to use both in same entity only securefield will work. Is this a bug?</div>

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/29011 takes care of the issue

**Comment by geoand** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/29011
