### ISSUE TITLE
Move all OTel tests away of sorted start time

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#29013]
### Description

This is a follow up to the work done on this PR: https://github.com/quarkusio/quarkus/pull/28471
We must not compare by start time like in RestClientOpenTelemetryTest which uses  TestSpanExporter.getFinishedSpanItems(...)
We need to fix the remaining tests.

**Comment by gsmet** [comment]
Note: I'm disabling the failing test for now here: https://github.com/quarkusio/quarkus/pull/29060 .
