### ISSUE TITLE
Define default scope for @Health, @Liveness and @Readiness bean defining annotations

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2904]
I think that `@Singleton` would be the best match. Also add a NOTE to the docs - so that it's clear that we differ from the standard behavior.

**Comment by emmanuelbernard** [comment]
BTW what is the difference between `@Singleton` and `ApplicationScoped`?

**Comment by emmanuelbernard** [comment]
That's to be implemented in the health extension I suppose right @mkouba ? In that case I'll CC @kenfinnigan for further triage.

**Comment by mkouba** [comment]
Yes, it would be a minor change in the health extension build step.

`@Singleton` is very similar to `@ApplicationScoped` except for it's not a normal scope and so no client proxies are injected, instead a direct reference to the bean is used. 

There are few consequences:
* no lazy init; `@ApplicationScoped` beans in weld and arc are instantiated lazily, when first used
* not possible to destroy and recreate the instance; since CDI 1.1 you can destroy a normal scoped bean instance and it's automatically recreated if needed
* no proxy = no delegation needed = less overhead
* problems with serialization - not supported in arc anyway, see https://docs.jboss.org/weld/reference/latest/en-US/html/scopescontexts.html#_the_singleton_pseudo_scope

**Comment by mkouba** [comment]
@antoinesd What's your opinion on this? Currently, the "default" scope is `@Dependent`.

**Comment by geoand** [comment]
I really think we should default to `@Singleton` for this...

**Comment by mkouba** [comment]
In fact, this was already implemented and merged: https://github.com/quarkusio/quarkus/pull/9749

There is one minor glitch though - a health check annotated with a stereotype that has no default scope remains `@Dependent`. But that's a corner case. I'm going to close this issue and I'll send a PR to fix this glitch today.
