### ISSUE TITLE
Improve quarkus-hibernate-reactive-rest-data-panache Hibernate Validation Violation Errors - Property Path 

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#29047]
### Description

Currently when you generate violations such as:

Using a validator on a annotation that is used at the class level and using the generated POST method for entity creation/insert.

entity:

```java
@Entity
@SomeClassLevelConstraint()
public class SomeEntity extends PanacheEntity {
....
```

Validator

```java
...

public boolean isValid(Object value, ConstraintValidatorContext context) {
     context.buildConstraintViolationWithTemplate("some error").addPropertyNode("some path").addConstraintViolation().disableDefaultConstraintViolation();

...

```

This generates a json response of:

```json
{
  "title": "Constraint Violation",
  "status": 400,
  "violations": [
    {
      "field": "add.arg0.somepath",
      "message": "some error"
    }
  ]
}
```

the `add.arg0` appears to be coming from `RestDataResource` with the `Entity add(Entity entity);` method? (https://github.com/quarkusio/quarkus/blob/main/extensions/panache/rest-data-panache/runtime/src/main/java/io/quarkus/rest/data/panache/RestDataResource.java#L52)

Would be great if we could tailor this so the root makes sense for the output.

**Comment by geoand** [comment]
cc @Sgitario
