### ISSUE TITLE
Ensure that content-length is not set when transfer-encoding exists while propogating headers from rest client

### ISSUE THREAD

**Issue by sag1** [quarkusio/quarkus#29059]
### Describe the bug

I am using `quarkus-resteasy-reactive-jackson` and `quarkus-rest-client-reactive-jackson` extensions for my API. All works well, but my acceptance tests are failing on postman due to the presence of `content-length: 1723` and `transfer-encoding: chunked`.  The client sends these headers

 content-type: application/json;charset=UTF-8 
 date: Fri,04 Nov 2022 10:05:39 GMT 
 server: nginx/1.20.2 
 transfer-encoding: chunked 

These headers are propogated well to my application but it adds `content-length` too as below:

 content-length: 1723 
 content-type: application/json;charset=UTF-8 
 date: Fri,04 Nov 2022 10:05:39 GMT 
 server: nginx/1.20.2 
 transfer-encoding: chunked 

According to [RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2),  "Content-Length" and "Transfer-Encoding" can't be present in the response headers together. 

I searched for a while, even I tried with **@RegisterClientHeaders** on my client service. But still the problem persists. I don't understand why it's adding `content-length`.  Could please look into it ?

### Expected behavior

Propogate the headers as it is, don't include extra headers

### Actual behavior

Although `transfer-encoding` exists, restEasy reactive adds `content-length` 

### How to Reproduce?

Create a resteasy reactive endpoint which consumes rest client reactive

### Output of `java -version`

18

### Quarkus version or git rev

2.13.3.Final

**Comment by geoand** [comment]
Any chance you can create a sample application for us that will exhibit the problem being described?

**Comment by geoand** [comment]
Not really

**Comment by cescoffier** [comment]
The fix is 'easy' but having a reproducer would be great as we would need to write a test for it.

The easy fix is to sanitize the headers before sending them and removing the content length if set.

**Comment by geoand** [comment]
Exactly

**Comment by geoand** [comment]
@sag1 any luck with creating a sample we can use to reproducer the issue?

**Comment by anderscore-alambertz** [comment]
Simple Reproduction:

- Use Quarkus "Start Coding" with following configs:
    - Build Tool: Maven (Gradle probably also works, not tested it)
    - RESTEasy Reactive Jackson Dependendy

In generated GreetingResource class:
- change return type to "Response"
- use Response.ResponseBuilder to create a variable "responseBuilder" and initializie it with "Response.ok("Hello World")
- next line, use "responseBuilder.header("Transfer-Encoding", "chunked");"
- build and return the response
- test e.g. via postman: "Parse Error: "Content-Length" and "Transfer-Encoding" can't be present in the response headers together"

**Comment by geoand** [comment]
Thanks. https://github.com/quarkusio/quarkus/pull/29460 takes care of the issue

**Comment by sag1** [comment]
Thanks a lot for the fix, really sorry, I haven't had time to provide a reproducer and managed to sanitize the headers

> @sag1 any luck with creating a sample we can use to reproducer the issue?

**Comment by geoand** [comment]
No problem
