### ISSUE TITLE
Reimplement BeanDefiningAnnotation default scope

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2905]
A bean defining annotation produced by `BeanDefiningAnnotationBuildItem` with a default scope value set is currently recognized as a stereotype. For example:

```java
@Path("foo")
class MyResource {
}
```
`@Path` is by default recognized as a stereotype with `@Singleton`. This works fine even if a user adds a custom scope:

```java
@RequestScoped
@Path("foo") // -> stereotype is ignored
class MyResource {
}
```
However, the app would fail if a user adds a strereotype with a different scope:

```java
@Model // -> stereotype - declares @RequestScoped
@Path("foo") // -> stereotype - declares @Singleton
class MyResource {
}
```
We could try to add the scope annotation directly if the bean class does not declare any scope annotation. But the problem is that we can't register an `AnnotationTransformer` because the custom scopes are not known during registration and so we may end up with unpredictable results. I'm not sure what the right approach would be.

**Comment by manovotn** [comment]
Looking into this I think the easiest way is to mark all stereotypes originating from additional bean defining annotations and them subsequently filter them in `io.quarkus.arc.processor.Beans.initStereotypeScope(List<StereotypeInfo>, AnnotationTarget)`

I'll take a shot at that.
