### ISSUE TITLE
Produced beans don't generate metrics on methods @Timed

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#29067]
### Describe the bug

When a produced bean has a public method annotated with `@Timed`, no metrics will be generated. `@ApplicationScoped` beans work as expected

### Expected behavior

Metrics are generated for produced beans

### Actual behavior

no metrics generated

### How to Reproduce?

[quarkus-timed-producers.tar.gz](https://github.com/quarkusio/quarkus/files/9939109/quarkus-timed-producers.tar.gz)

execute tests in the attached project

**Comment by geoand** [comment]
Also cc @mkouba in case this is an Arc issue

**Comment by jmartisk** [comment]
Removed area/smallrye, the reproducer is using Micrometer

**Comment by jmartisk** [comment]
I think this use case can't work, `RemoteApiSingleton` is not a CDI bean at all in your application, therefore the metric interceptors don't apply. It's just a POJO returned from a producer, and you build it by calling its constructor directly. Annotated metrics only work on CDI beans.

**Comment by mkouba** [comment]
@jmartisk is right. In CDI, interceptors are _not applied_ to the return value of a [producer method](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#binding_interceptor_to_bean) and the `InterceptionFactory` introduced in CDI 2.0 is [not supported yet](https://github.com/quarkusio/quarkus/issues/3532).
