### ISSUE TITLE
io.smallrye.reactive.messaging.mqtt Override send Topic does not work

### ISSUE THREAD

**Issue by brunohorta82** [quarkusio/quarkus#29064]
### Describe the bug

mp.messaging.outgoing.mqtt-out.type=smallrye-mqtt
mp.messaging.outgoing.mqtt-out.host=${mqtt.host}
mp.messaging.outgoing.mqtt-out.port=${mqtt.port}
mp.messaging.outgoing.mqtt-out.username=${mqtt.username}
mp.messaging.outgoing.mqtt-out.password=${mqtt.password}
mp.messaging.outgoing.mqtt-out.auto-generated-client-id=false
mp.messaging.outgoing.mqtt-out.topic=to-override
mp.messaging.outgoing.mqtt-out.client-id=api-available
%dev.mp.messaging.outgoing.mqtt-out.client-id=api-test-available
mp.messaging.outgoing.mqtt-out.reconnect-attempts=20000
mp.messaging.outgoing.mqtt-out.connect-timeout-seconds=120    

@Inject
    @Channel("mqtt-out")
    MutinyEmitter<String> emitter;

emitter.sendMessage(MqttMessage.of("teste","message test", MqttQoS.AT_MOST_ONCE, false))

The editor publish the message always on topic: to-override

### Expected behavior

Publish message on topic: teste

### Actual behavior

the message is publish  on topic: to-override

### How to Reproduce?

Install quarkus 2.13.3.Final 
send mqtt message to one topic set using emitter.sendMessage(MqttMessage.of("teste","message test", MqttQoS.AT_MOST_ONCE, false))

### Quarkus version or git rev

2.13.3.Final 

### Additional information

On quarks 2.13.0.Final  works fine

**Comment by ozangunalp** [comment]
I confirmed the bug and it was older than 2.13. There will be a fix upstream.

**Comment by cescoffier** [comment]
Fixed in Reactive Messaging 3.22.0

**Comment by cescoffier** [comment]
Closed, as the 3.22.0 release of Reactive Messaging has been integrated.
