### ISSUE TITLE
OpenAPI with static files instead of annotation scanning

### ISSUE THREAD

**Issue by jmini** [quarkusio/quarkus#2907]
**Describe the bug**
It seems that all the `microprofile-open-api` features are not supported yet by quarkus.

One setup example:
Add the config property `mp.openapi.scan.disable=true` and a static OpenAPI file in `src/main/resources/META-INF/openapi.yaml`.

In that case, the `microprofile-open-api` annotation scanning should be disabled and the openapi spec should be served from the static file.

See https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#static-openapi-files

**Expected behavior**
You see the static file served at http://localhost:8080/openapi

**Actual behavior**
I did not manage to see my local file, the server is always serving the generated one

**To Reproduce**
1. Create a project with Quarkus RESTEasy
2. Add the openapi extension and configure as described

**Configuration**
```properties
mp.openapi.scan.disable=true
```

Static OpenAPI file (that would be different from the generated one):
```yaml
---
openapi: 3.0.1
info:
  title: My HelloWorld API
  version: "1.0"
  license:
    name: Eclipse Public License 2.0
    url: 'https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html'
paths:
  /hello:
    get:
      description: hello world method
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin  18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
 - GraalVM version (if different from Java): [not used]
 - Quarkus version or git rev: 0.16.1

---

We had a quick look at the code with @emmanuelbernard at Voxxed Days Luxembourg 2019.

There is one integration test for the default setup (generated spec based on the annotation)
https://github.com/quarkusio/quarkus/blob/master/integration-tests/main/src/test/java/io/quarkus/it/main/OpenApiTestCase.java

But other scenario should be tested as test of the "deployment" module of "smallrye-openapi"
https://github.com/quarkusio/quarkus/tree/master/extensions/smallrye-openapi/deployment/

cc: @kenfinnigan

**Comment by emmanuelbernard** [comment]
I looked at the extension code and the expected behavior seems to be half there as the static files are marked for hot reload and detected. But I think there might be path problems or sort. We should definitely add more tests to cover different configuration approaches like I did for Hibernate and it’s handling of persistence.xml

**Comment by jmini** [comment]
I investigated a little bit more. If you restart your quarkus-server completely (something that you tend to forget to do/try), then the static file is taken into account.

So this issue is more about the hot-reload not working for `src/main/resources/META-INF/openapi.yaml`.

---

In addition, I am also not sure how `mp.openapi.scan.disable` is supported (I did not manage to make it work).

**Comment by gsmet** [comment]
This needs to stay open, #3244 only fixed hot reload.

**Comment by jmini** [comment]
Thank you for the first fix.

---

I tried other eclipse-mp-openapi properties such as 
```
mp.openapi.servers=https://xyz.com/v1,https://abc.com/v1
```

This is working well.

---

Only `mp.openapi.scan.disable` is a problem. In my opinion following code must only run when `mp.openapi.scan.disable` is not set or when `mp.openapi.scan.disable=false` (as additional check next to `resteasyJaxrsConfig.isPresent()`):

https://github.com/quarkusio/quarkus/blob/b5b7ff119833427c09e58c6e209e59afab3d0cb4/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L200-L204

Something like:

```java
        Config config = ConfigProvider.getConfig();
        Optional<Boolean> scanDisable = config.getOptionalValue(OASConfig.SCAN_DISABLE, Boolean.class);
        OpenAPI annotationModel;
        if (resteasyJaxrsConfig.isPresent() && !(scanDisable.isPresent() && scanDisable.get())) {
            annotationModel = generateAnnotationModel(index, resteasyJaxrsConfig.get());
        } else {
            annotationModel = null;
        }
```

---

I wanted to write a test, similar to [OpenApiDefaultPathTestCase](https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiDefaultPathTestCase.java).

But when I run this:

```java
private static final String OPEN_API_PATH = "/openapi";

@RegisterExtension
static QuarkusUnitTest runner = new QuarkusUnitTest()
        .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                .addClasses(OpenApiResource.class));

@Test
public void testOpenApiPathAccessResource() {
    String s = RestAssured.given().header("Accept", "application/json")
            .when().get(OPEN_API_PATH)
            .then().extract().asString();

    System.out.println(s);
}
```

I get:

```
RESTEASY003210: Could not find resource for full path: http://localhost:8081/openapi
```

Of course my plan for the test was also to add config files `.addAsManifestResource(..)` and `addAsResource(..)`

**Comment by jmini** [comment]
The second part of this issue (`mp.openapi.scan.disable=true`) is fixed with PR https://github.com/quarkusio/quarkus/pull/3362
