### ISSUE TITLE
org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111

### ISSUE THREAD

**Issue by guoxunbo** [quarkusio/quarkus#29080]
### Describe the bug

Hello. When i use hibernate type as a dependency。but i got this warning in quarkus 2.13.3.Final.
How can I to solve this. I had saw [21129](https://github.com/quarkusio/quarkus/issues/21129)
It said it solve in 2.4.1. But When i use 2.13.3 i already got this exception. my entity is like this.
```java
@TypeDef(name = "json", typeClass = JsonType.class)
public class BaseEntity extends PanacheEntityBase implements Serializable, Cloneable {

    @Type(type = "json")
    @Getter
    @Setter
    @Column
    private Map<String, String> extProperties = Maps.newConcurrentMap();

   

}

```

### Expected behavior

嗯

### Output of `java -version`

17

### Quarkus version or git rev

2.13.3.Final

**Comment by yrodiere** [comment]
Hey,

Please include the full stack trace (message, all frames, and nested exceptions if any).

Also, we'll most likely need you to provide a reproducer: a simple project set up with all necessary dependencies and exhibiting your problem on startup.

Thanks in advance.

**Comment by gsmet** [comment]
No reproducer, closing.
