### ISSUE TITLE
Simplify JVM Heap size config options w/ Docker/Jib/S2I/Buildpack

### ISSUE THREAD

**Issue by The-Funk** [quarkusio/quarkus#29082]
### Description

I've been having trouble setting the JVM config options "Xms" and "Xmx" for my applications that are being packaged as docker container images using Jib. I've read that JVM options like these can be set using "additional properties" but I've had no luck,

I think, particularly for these two options, it would be beneficial to simplify the process of setting these options, or modify the base image Quarkus applications rely on to use more of the available system resources. The reason I believe this is important with containerization is simple. A container's job is to do one thing. The container isolates your application, and runs that application. If there are no other services running on a container, which there should not be, then why restrict the JVM to the standard 1/4 of system RAM? The other ~3/4 of the system RAM (minus what the OS uses) are going to waste. In an environment like Kubernetes, wasted RAM can be very costly.

### Implementation ideas

I see two potential solutions to this:

1. A smallrye config option to set heap size manually. This has the benefit of letting the user be explicit about their RAM utilization. The drawback to this approach is that the user could specify a heap size that is unacceptable for their environment.

2. Modifying the ubi8 image w/ Java to by default allow Java processes to use a larger automatically configured chunk of system RAM (something like 70% maybe?) This has the benefit of automatically scaling to the environment, but has the drawback of potentially starving ultra low resource systems for RAM. The latter should be a rarity. ubi8 uses very little RAM by itself, so a vast majority of systems would be fine with this higher permitted usage.

**Comment by geoand** [comment]
Thanks for reporting.

Option 1 we can't do unfortunately because by the time Config is setup, it's far to late to set JVM config options.

Options 2 is interesting. IIRC, that's what the purpose of the old `run-java` script was in the fabric8  docker images.

cc @cescoffier @Ladicek

**Comment by The-Funk** [comment]
> Thanks for reporting.
> 
> Option 1 we can't do unfortunately because by the time Config is setup, it's far to late to set JVM config options.
> 
> Options 2 is interesting. IIRC, that's what the purpose of the old `run-java` script was in the fabric8 docker images.
> 
> cc @cescoffier @Ladicek

Thanks for considering it :)

We might be slightly out of sync on the first solution, or I might not understand how the container building plugins work. I mean a config option for Jib or the other container builders to instruct them to build the container such that the internal jar is executed with Xmx specified. Jib specifically has something for this but I could never get it to work.

https://github.com/GoogleContainerTools/jib/issues/1082

**Comment by geoand** [comment]
Oh, now I see what you mean.
Yeah, that's something we could add

**Comment by geoand** [comment]
I should note that you can already do something like this using `quarkus.jib.jvm-additional-arguments`

**Comment by The-Funk** [comment]
Yes, I just can't seem to get additional-arguments to work. I think because it has extra = signs in the value. Maybe I need to encapsulate the additional arguments value in quotation marks? Can you send a working example of additional-arguments?

**Comment by geoand** [comment]
What do you want to set?

**Comment by The-Funk** [comment]
Hello! I left you on read for this for the longest time, I apologize. It's been a busy few months.

I have now run into another instance where I need to configure the JVM at the command line. I am implementing Azure Application Insights and near as I can tell, they require -javaagent to be specified on the command line in order to use their auto instrumentation. [You can check out their docs here.](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) 

The recommendation for this, from what I have found, is to put the command line option "-javaagent" in the quarkus-maven-plugin configuration. 

[Here's a sample project I found doing exactly that](https://github.com/mtaghavi2005/quarkus-application-insight/blob/master/pom.xml), and[ the user's link to the process in discussions](https://github.com/quarkusio/quarkus/discussions/27695).

So what I have now in my POM file under the quarkus-maven-plugin is:

```
<configuration>
  <jvmArgs>-javaagent:${project.build.directory}/libs/appinsights.jar</jvmArgs>
</configuration>
```

At the same time, I am still interested in overriding the default heap size characteristics. Should I put those in the pom as well or use the application.properties additional.args ?

I think the specific argument I'm interested in most is -XX:MaxRAMPercentage. [Here is a quick article talking about MaxRamPercentage](https://medium.com/@marketing_864/best-practices-java-memory-arguments-for-containers-1d704a65f7db). I think this heap option is perfect for my scenario. I have several K8s environments and the containers in each environment are constrained in different ways. I am using Quarkus and have done a lot of work to make things run lean and mean, but more RAM is always better. That said, setting Xmx in my case doesn't work the best because I don't control the container sizes in the different K8s environments and I don't control when they might change. That's kinda tossed over the wall to Dev-Ops. So with that in mind, being dynamic about how I allocate RAM could be more future-proofed than setting a hard value.

**Comment by geoand** [comment]
Soon our Jib based images will provide a way for the container to determine such memory flags automatically (see [this](https://github.com/jboss-container-images/openjdk/blob/ubi9/modules/run/artifacts/opt/jboss/container/java/run/run-java.sh)).

As for the agent, do you want to use in development or production?

**Comment by The-Funk** [comment]
@geoand that's awesome news! I cant wait to see how that works.

For the agent, I want to use in development to test, and then once I am sure it's working, I will remove it from my local dev environment and apply it only to production. I'm not a big fan of how MS implemented this auto-instrumentation but I think it should work.

**Comment by geoand** [comment]
I see. Configuring the agent for dev mode the way you mentioned above should work

**Comment by The-Funk** [comment]
Hey @geoand I'm finally testing this out but this issue can probably be closed.

Just wanted to ask if there are any gotchas if I use a custom entrypoint shell script? I'm not sure what the default arguments passed to the JVM are when I build with JIB. Is it just java -jar quarkus-run.jar?

Ideally I'd like to keep the defaults and just add -XX:MaxRAMPercentage=75

Going to test this today and will let you know how it goes!

**Comment by The-Funk** [comment]
Works like a charm! Closing this out!

**Comment by geoand** [comment]
💪🏼
