### ISSUE TITLE
Support some sort of Pre and Post (lifecycle) processing hooks on quarkus-hibernate-orm-rest-data-panache generated endpoints

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#29095]
### Description

when generating endpoints with quarkus-hibernate-orm-rest-data-panache I have found there is a need to often make pre or post processing changes:

Example: May want to modify or manually validate data (outside of scope/configs of hibernate validation annotations) before passing it into the endpoint

Example: May want to further modify the response before sending it for serialization/final response.  Example maybe i want to redact some data from the returned entities.

is there a way? and if not, it would be nice to have some form of pre and post processing capability.

Initially it seems like maybe we should support carrying annotations applied on the interface into the generated classes?   But i have seen that in the latest builds of quarkus-hibernate-orm-rest-data-panache, the ability to add Roles were added as ResourceProperties configs.  Why would we do this vs allowing the application of `@RolesAllowed(...)` on the interface methods and carry those methods into the generated classes?  If this type of pattern was used, it seems we could generate `Around` annotations for pre and post processing, similar to how Cache annotations work.  Otherwise would be fine as well with lifecycle hooks in the Resource and method properties configs that allow the application of classes that are called allowing us the ability to modify the data as needed.

**Comment by Sgitario** [comment]
I created this pull request to support the feature you asked for: https://github.com/quarkusio/quarkus/pull/27994
However, these changes are stale because Hibernate ORM already provides this feature using listeners,  see the example in https://github.com/quarkusio/quarkus/commit/0852b104d7341445af3cf8f41fa7be4e2758fd9d#diff-7ed082417d8730c92d0dcf5c59e547878a5c298311afbd529f1a5c9591f150cc

Let me know if JPA listeners work for your use case.

**Comment by StephenOTT** [comment]
@Sgitario I tested similar behaviour using a Hibernate validator on the class level, and hit a few issues:

Will your JPA listeners model allow querying the panache repository for the same entity?  ie: SomeEntity.class is being persisted and you want to do a findBySomeValue() on SomeEntityRepository.  

Also using the listeners means we do not have access to the additional request info that would be valuable in a post/pre listener: for example, maybe i want to send in some additional properties and i modify the data, or check a header, identity's roles, etc for some additional logic handling.

JPA listeners are good as well, but there seems to be missing the layer before it going into JPA and after it comes out of JPA/post-DB response

**Comment by StephenOTT** [comment]
another note: one of the most valuable aspects of the generation i have found is around all of the helpers for common needs:

Generating a endpoint is pretty simple in terms of quantity of code: we can see the ~generated-sample in the docs that says something to the affect of "the generated code looks something like this..."

Maybe we are saving 30 lines of code.  

But when i look into the rest-data-panache package(s), there are lots of under-the-hood helpers going on that I feel is the real value: Validator Exception Mappers, ORM mappers, Sort Helpers, etc.

Would be valuable IMO if these types of helpers were further exposed to provide the rapid generation of these endpoints with the common helpers that reduce the repetitive custom code.

**Comment by Sgitario** [comment]
Hey @yrodiere , see the feedback from @StephenOTT about the pre and post hooks. This is related to your commend in https://github.com/quarkusio/quarkus/pull/27994#issuecomment-1249248900. 
I do think that there is real value in adding this feature in REST Data with Panache (ORM and Reactive). Perhaps, we could refactor the pull request not to call it `EntityListener` but something like Pre/Post-<name of the resource>.

**Comment by Sgitario** [comment]
Many thanks for your useful feedback @yrodiere ! 
So I will resume the linked pull request and rename the entity listeners to something else that matches better within the rest-data-panache extension and also to avoid confusion with the JPA listeners.

**Comment by StephenOTT** [comment]
Thanks for the great work on this

**Comment by BenF99** [comment]
It's ashame this support is only scoped to hibernate-orm. The docs make this slightly misleading. Would've been good to have support for Mongo too.
