### ISSUE TITLE
security-ldap-quickstart NOT FOUND

### ISSUE THREAD

**Issue by sdtechnos** [quarkusio/quarkus#29113]
### Description

https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-ldap-quickstart page response not found

**Comment by sberyozkin** [comment]
@sdtechnos It will be available once 2.14.0.Final quickstarts tag is created, it is here: https://github.com/quarkusio/quarkus-quickstarts/tree/development/security-ldap-quickstart, thanks
