### ISSUE TITLE
Image generation fails with 2.13.4

### ISSUE THREAD

**Issue by fsudrot** [quarkusio/quarkus#29124]
### Describe the bug

With the previous Quarkus version 2.13.3 and quay.io/quarkus/ubi-quarkus-native-image:22.2-java17, everything works, compile, test, image generation
But with Quarkus 2.13.4 and quay.io/quarkus/ubi-quarkus-native-image:22.3-java17, I have a problem with image generation which fails with : Fatal error: Failed while initializing the performance data.

### Expected behavior

The image is correctly generated

### Actual behavior

error in image generation

### How to Reproduce?

Change
```xml<quarkus.platform.version>2.13.3.Final</quarkus.platform.version>```
For 
```xml<quarkus.platform.version>2.13.4.Final</quarkus.platform.version>```
In your pom.

And you will have :
```
Current timestamp: 1667913693297

Printing Instructions (ip=0x00000000004889f0):
  0x00000000004889d0: 0x00 0x41 0xc7 0x87 0x34 0x01 0x00 0x00 0xfe 0xfe 0xfe 0x7e 0x48 0x8b 0x7c 0x24
  0x00000000004889e0: 0x20 0x48 0x8b 0x74 0x24 0x10 0x48 0x8b 0x54 0x24 0x18 0xe8 0x60 0xfd 0xff 0xff
  0x00000000004889f0: 0x90 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc
  0x0000000000488a00: 0x48 0x83 0xec 0x18 0x49 0x3b 0x67 0x08 0x0f 0x86 0x9f 0x00 0x00 0x00 0x48 0x8b

Top of stack (sp=0x00007fd271afedc0):
  0x00007fd271afedc0: 0x0000800000008000 0x00000000004cd3d3
  0x00007fd271afedd0: 0x00007fd272a256a8 0x00007fd272700000
  0x00007fd271afede0: 0x00000000004bc4eb 0x00000000004ef524
  0x00007fd271afedf0: 0x00007fd272d7cc68 0x00000000004bc4eb
  0x00007fd271afee00: 0x00000000004d1f6b 0x00007fd272ecbd68
  0x00007fd271afee10: 0x00007fd272cedc80 0x00000000004bc53b
  0x00007fd271afee20: 0x00007fd271aff700 0x00000000004d1809
  0x00007fd271afee30: 0x00007fd272cbd410 0x00007fd272f1f3e8
  0x00007fd271afee40: 0x00007fd272cedc80 0x00000000004e642a
  0x00007fd271afee50: 0x00007ffd4878dd6f 0x00007fd272700000
  0x00007fd271afee60: 0x00007fd272cedc80 0x00007fd272db5200
  0x00007fd271afee70: 0x0000000000000002 0x00000000004d1e17
  0x00007fd271afee80: 0x00007fd272700000 0x0000000100000000
  0x00007fd271afee90: 0x0000000000000002 0x000000000043a55f
  0x00007fd271afeea0: 0x0000000000000000 0x0000000000000000
  0x00007fd271afeeb0: 0x0000000000000000 0x0000000000000000
  0x00007fd271afeec0: 0x0000000002de2c30 0x0000000000000000
  0x00007fd271afeed0: 0x00007fd271afefc0 0x00007ffd4878de30
  0x00007fd271afeee0: 0x00007ffd4878dd6f 0x00007ffd4878dd6e
  0x00007fd271afeef0: 0x0000000000000000 0x00007fd273a321cf
  0x00007fd271afef00: 0x0000000000000000 0x00007fd271aff700
  0x00007fd271afef10: 0x00007fd271aff700 0x3e1385ffc6fa7d7c
  0x00007fd271afef20: 0x00007ffd4878dd6e 0x00007ffd4878dd6f
  0x00007fd271afef30: 0x00007ffd4878de30 0x00007fd271afefc0
  0x00007fd271afef40: 0xc1b766a018fa7d7c 0xc1b762b984287d7c
  0x00007fd271afef50: 0x0000000000000000 0x0000000000000000
  0x00007fd271afef60: 0x0000000000000000 0x0000000000000000
  0x00007fd271afef70: 0x0000000000000000 0x0000000000000000
  0x00007fd271afef80: 0x0000000000000000 0x0000000000000000
  0x00007fd271afef90: 0x0000000000000000 0x04ff0bab8d57a700
  0x00007fd271afefa0: 0x0000000000000000 0x00007fd271aff700
  0x00007fd271afefb0: 0x00007ffd4878de30 0x00007fd273292dd3

Top frame info:
  TotalFrameSize in CodeInfoTable 48
  
Threads:
  0x00007fd264000b80 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "Performance data" - 0x00007fd272cedc80, daemon, stack(0x00007fd271301000,0x00007fd271b00000)
  0x00007fd26c000b80 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x00007fd272cee6f0, daemon, stack(0x00007fd271d01000,0x00007fd272500000)
  0x0000000002de22c0 STATUS_IN_JAVA (ALLOW_SAFEPOINT) "main" - 0x00007fd272cee630, stack(0x00007ffd47f8f000,0x00007ffd4878f000)
  
VM thread locals for the failing thread 0x00007fd264000b80:
  0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    0x00007fd264000b80: 0x00007fd272b53010
  8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)
  16 (4 bytes): Safepoint.safepointRequested = (int) 2147470175 (0x7fffcb5f)
  20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)
  24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes) 
    0x00007fd264000b98: 0x00007fd271100000 0x00007fd271200000
    0x00007fd264000ba8: 0x00007fd2711014b0 0x0000000000000000
  56 (8 bytes): PlatformThreads.currentThread = (Object) com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread (0x00007fd272cedc80)
  64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 0 (0x0000000000000000)
  72 (8 bytes): AccessControlContextStack = (Object) null
  80 (8 bytes): ExceptionUnwind.currentException = (Object) null
  88 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  96 (8 bytes): IsolatedCompileClient.currentClient = (Object) null
  104 (8 bytes): IsolatedCompileContext.currentContext = (Object) null
  112 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x00007fd2711011c8)
  120 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null
  128 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  136 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  144 (8 bytes): JfrThreadLocal.javaEventWriter = (Object) null
  152 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null
  160 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null
  168 (8 bytes): JfrThreadLocal.dataLost = (Word) 0 (0x0000000000000000)
  176 (8 bytes): JfrThreadLocal.javaBuffer = (Word) 0 (0x0000000000000000)
  184 (8 bytes): JfrThreadLocal.nativeBuffer = (Word) 0 (0x0000000000000000)
  192 (8 bytes): JfrThreadLocal.parentThreadId = (long) 1 (0x0000000000000001)
  200 (8 bytes): JfrThreadLocal.threadId = (long) 41 (0x0000000000000029)
  208 (8 bytes): SamplerThreadLocal.localBuffer = (Word) 0 (0x0000000000000000)
  216 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 
    0x00007fd264000c58: 0x0000000000000000
  224 (8 bytes): ThreadLocalAllocation.allocatedBytes = (Word) 0 (0x0000000000000000)
  232 (8 bytes): VMThreads.IsolateTL = (Word) 140541839802368 (0x00007fd272700000)
  240 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 140541827217152 (0x00007fd271aff700)
  248 (8 bytes): VMThreads.OSThreadIdTL = (Word) 140541827217152 (0x00007fd271aff700)
  256 (8 bytes): VMThreads.StackBase = (Word) 140541827219456 (0x00007fd271b00000)
  264 (8 bytes): VMThreads.StackEnd = (Word) 140541818834944 (0x00007fd271301000)
  272 (8 bytes): VMThreads.StartedByCurrentIsolate = (bytes) 
    0x00007fd264000c90: 0x0000000000000001
  280 (8 bytes): VMThreads.nextTL = (Word) 140541731801984 (0x00007fd26c000b80)
  288 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 140541597584224 (0x00007fd264000b60)
  296 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)
  300 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)
  304 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)
  308 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)
  312 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)
  316 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)
  
No VMOperation in progress

The 15 most recent VM operation status changes (oldest first):
  
Counters:
  
Java frame anchors for the failing thread 0x00007fd264000b80:
  No anchors
  
Stacktrace for the failing thread 0x00007fd264000b80:
  SP 0x00007fd271afedc0 IP 0x00000000004889f0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:116)
  SP 0x00007fd271afedc0 IP 0x00000000004889f0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:109)
  SP 0x00007fd271afedf0 IP 0x00000000004ef524  [image code] com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:65)
  SP 0x00007fd271afee00 IP 0x00000000004bc4eb  [image code] com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
  SP 0x00007fd271afee00 IP 0x00000000004bc4eb  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.initializeMemory(PerfManager.java:208)
  SP 0x00007fd271afee20 IP 0x00000000004bc53b  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.run(PerfManager.java:187)
  SP 0x00007fd271afee50 IP 0x00000000004e642a  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  SP 0x00007fd271afee80 IP 0x00000000004d1e17  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
  SP 0x00007fd271afeea0 IP 0x000000000043a55f  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(IsolateEnterStub.java:0)
  
VM mutexes:
  mutex "thread" is unlocked.
  mutex "referencePendingList" is unlocked.
  mutex "jfrThreadRepository" is unlocked.
  mutex "perfDataInitialization" is locked by thread 0x00007fd264000b80
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  mutex "jfrRecorder" is unlocked.
  mutex "SamplerBufferPool" is unlocked.
  
AOT compiled code is mapped at 0x0000000000406000 - 0x0000000000a7e3cf

Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x00007fd272700000
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 0
  Complete collections: 0
  
Native image heap boundaries:
  ReadOnly Primitives: 0x00007fd272801028 - 0x00007fd2729a4150
  ReadOnly References: 0x00007fd2729a4150 - 0x00007fd272b52688
  ReadOnly Relocatables: 0x00007fd272b53000 - 0x00007fd272c01840
  Writable Primitives: 0x00007fd272c02000 - 0x00007fd272c89588
  Writable References: 0x00007fd272c89588 - 0x00007fd272f4ae50
  Writable Huge: 0x00007fd273000030 - 0x00007fd273029d60
  ReadOnly Huge: 0x00007fd27302a030 - 0x00007fd2731beb98

Heap:
  Young generation: 
    Eden: 
      edenSpace:
        aligned: 0/0 unaligned: 0/0
    Survivors: 
      Survivor-1 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-1 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 To:
        aligned: 0/0 unaligned: 0/0
  Old generation: 
    oldFromSpace:
      aligned: 0/0 unaligned: 0/0
    oldToSpace:
      aligned: 0/0 unaligned: 0/0
    
  Unused:
    aligned: 0/0

Fatal error: Failed while initializing the performance data.
```

### Output of `uname -a` or `ver`

Current timestamp: 1667913693297  Printing Instructions (ip=0x00000000004889f0):   0x00000000004889d0: 0x00 0x41 0xc7 0x87 0x34 0x01 0x00 0x00 0xfe 0xfe 0xfe 0x7e 0x48 0x8b 0x7c 0x24   0x00000000004889e0: 0x20 0x48 0x8b 0x74 0x24 0x10 0x48 0x8b 0x54 0x24 0x18 0xe8 0x60 0xfd 0xff 0xff   0x00000000004889f0: 0x90 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc   0x0000000000488a00: 0x48 0x83 0xec 0x18 0x49 0x3b 0x67 0x08 0x0f 0x86 0x9f 0x00 0x00 0x00 0x48 0x8b  Top of stack (sp=0x00007fd271afedc0):   0x00007fd271afedc0: 0x0000800000008000 0x00000000004cd3d3   0x00007fd271afedd0: 0x00007fd272a256a8 0x00007fd272700000   0x00007fd271afede0: 0x00000000004bc4eb 0x00000000004ef524   0x00007fd271afedf0: 0x00007fd272d7cc68 0x00000000004bc4eb   0x00007fd271afee00: 0x00000000004d1f6b 0x00007fd272ecbd68   0x00007fd271afee10: 0x00007fd272cedc80 0x00000000004bc53b   0x00007fd271afee20: 0x00007fd271aff700 0x00000000004d1809   0x00007fd271afee30: 0x00007fd272cbd410 0x00007fd272f1f3e8   0x00007fd271afee40: 0x00007fd272cedc80 0x00000000004e642a   0x00007fd271afee50: 0x00007ffd4878dd6f 0x00007fd272700000   0x00007fd271afee60: 0x00007fd272cedc80 0x00007fd272db5200   0x00007fd271afee70: 0x0000000000000002 0x00000000004d1e17   0x00007fd271afee80: 0x00007fd272700000 0x0000000100000000   0x00007fd271afee90: 0x0000000000000002 0x000000000043a55f   0x00007fd271afeea0: 0x0000000000000000 0x0000000000000000   0x00007fd271afeeb0: 0x0000000000000000 0x0000000000000000   0x00007fd271afeec0: 0x0000000002de2c30 0x0000000000000000   0x00007fd271afeed0: 0x00007fd271afefc0 0x00007ffd4878de30   0x00007fd271afeee0: 0x00007ffd4878dd6f 0x00007ffd4878dd6e   0x00007fd271afeef0: 0x0000000000000000 0x00007fd273a321cf   0x00007fd271afef00: 0x0000000000000000 0x00007fd271aff700   0x00007fd271afef10: 0x00007fd271aff700 0x3e1385ffc6fa7d7c   0x00007fd271afef20: 0x00007ffd4878dd6e 0x00007ffd4878dd6f   0x00007fd271afef30: 0x00007ffd4878de30 0x00007fd271afefc0   0x00007fd271afef40: 0xc1b766a018fa7d7c 0xc1b762b984287d7c   0x00007fd271afef50: 0x0000000000000000 0x0000000000000000   0x00007fd271afef60: 0x0000000000000000 0x0000000000000000   0x00007fd271afef70: 0x0000000000000000 0x0000000000000000   0x00007fd271afef80: 0x0000000000000000 0x0000000000000000   0x00007fd271afef90: 0x0000000000000000 0x04ff0bab8d57a700   0x00007fd271afefa0: 0x0000000000000000 0x00007fd271aff700   0x00007fd271afefb0: 0x00007ffd4878de30 0x00007fd273292dd3  Top frame info:   TotalFrameSize in CodeInfoTable 48    Threads:   0x00007fd264000b80 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "Performance data" - 0x00007fd272cedc80, daemon, stack(0x00007fd271301000,0x00007fd271b00000)   0x00007fd26c000b80 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x00007fd272cee6f0, daemon, stack(0x00007fd271d01000,0x00007fd272500000)   0x0000000002de22c0 STATUS_IN_JAVA (ALLOW_SAFEPOINT) "main" - 0x00007fd272cee630, stack(0x00007ffd47f8f000,0x00007ffd4878f000)    VM thread locals for the failing thread 0x00007fd264000b80:   0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes)      0x00007fd264000b80: 0x00007fd272b53010   8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)   16 (4 bytes): Safepoint.safepointRequested = (int) 2147470175 (0x7fffcb5f)   20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)   24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes)      0x00007fd264000b98: 0x00007fd271100000 0x00007fd271200000     0x00007fd264000ba8: 0x00007fd2711014b0 0x0000000000000000   56 (8 bytes): PlatformThreads.currentThread = (Object) com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread (0x00007fd272cedc80)   64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 0 (0x0000000000000000)   72 (8 bytes): AccessControlContextStack = (Object) null   80 (8 bytes): ExceptionUnwind.currentException = (Object) null   88 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null   96 (8 bytes): IsolatedCompileClient.currentClient = (Object) null   104 (8 bytes): IsolatedCompileContext.currentContext = (Object) null   112 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x00007fd2711011c8)   120 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null   128 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null   136 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null   144 (8 bytes): JfrThreadLocal.javaEventWriter = (Object) null   152 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null   160 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null   168 (8 bytes): JfrThreadLocal.dataLost = (Word) 0 (0x0000000000000000)   176 (8 bytes): JfrThreadLocal.javaBuffer = (Word) 0 (0x0000000000000000)   184 (8 bytes): JfrThreadLocal.nativeBuffer = (Word) 0 (0x0000000000000000)   192 (8 bytes): JfrThreadLocal.parentThreadId = (long) 1 (0x0000000000000001)   200 (8 bytes): JfrThreadLocal.threadId = (long) 41 (0x0000000000000029)   208 (8 bytes): SamplerThreadLocal.localBuffer = (Word) 0 (0x0000000000000000)   216 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes)      0x00007fd264000c58: 0x0000000000000000   224 (8 bytes): ThreadLocalAllocation.allocatedBytes = (Word) 0 (0x0000000000000000)   232 (8 bytes): VMThreads.IsolateTL = (Word) 140541839802368 (0x00007fd272700000)   240 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 140541827217152 (0x00007fd271aff700)   248 (8 bytes): VMThreads.OSThreadIdTL = (Word) 140541827217152 (0x00007fd271aff700)   256 (8 bytes): VMThreads.StackBase = (Word) 140541827219456 (0x00007fd271b00000)   264 (8 bytes): VMThreads.StackEnd = (Word) 140541818834944 (0x00007fd271301000)   272 (8 bytes): VMThreads.StartedByCurrentIsolate = (bytes)      0x00007fd264000c90: 0x0000000000000001   280 (8 bytes): VMThreads.nextTL = (Word) 140541731801984 (0x00007fd26c000b80)   288 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 140541597584224 (0x00007fd264000b60)   296 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)   300 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)   304 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)   308 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)   312 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)   316 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)    No VMOperation in progress  The 15 most recent VM operation status changes (oldest first):    Counters:    Java frame anchors for the failing thread 0x00007fd264000b80:   No anchors    Stacktrace for the failing thread 0x00007fd264000b80:   SP 0x00007fd271afedc0 IP 0x00000000004889f0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shutdown(VMErrorSubstitutions.java:116)   SP 0x00007fd271afedc0 IP 0x00000000004889f0  [image code] com.oracle.svm.core.jdk.VMErrorSubstitutions.shouldNotReachHere(VMErrorSubstitutions.java:109)   SP 0x00007fd271afedf0 IP 0x00000000004ef524  [image code] com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:65)   SP 0x00007fd271afee00 IP 0x00000000004bc4eb  [image code] com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)   SP 0x00007fd271afee00 IP 0x00000000004bc4eb  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.initializeMemory(PerfManager.java:208)   SP 0x00007fd271afee20 IP 0x00000000004bc53b  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.run(PerfManager.java:187)   SP 0x00007fd271afee50 IP 0x00000000004e642a  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)   SP 0x00007fd271afee80 IP 0x00000000004d1e17  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)   SP 0x00007fd271afeea0 IP 0x000000000043a55f  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(IsolateEnterStub.java:0)    VM mutexes:   mutex "thread" is unlocked.   mutex "referencePendingList" is unlocked.   mutex "jfrThreadRepository" is unlocked.   mutex "perfDataInitialization" is locked by thread 0x00007fd264000b80   mutex "mainVMOperationControlWorkQueue" is unlocked.   mutex "jfrRecorder" is unlocked.   mutex "SamplerBufferPool" is unlocked.    AOT compiled code is mapped at 0x0000000000406000 - 0x0000000000a7e3cf  Heap settings and statistics:   Supports isolates: true   Heap base: 0x00007fd272700000   Object reference size: 8   Aligned chunk size: 1048576   Incremental collections: 0   Complete collections: 0    Native image heap boundaries:   ReadOnly Primitives: 0x00007fd272801028 - 0x00007fd2729a4150   ReadOnly References: 0x00007fd2729a4150 - 0x00007fd272b52688   ReadOnly Relocatables: 0x00007fd272b53000 - 0x00007fd272c01840   Writable Primitives: 0x00007fd272c02000 - 0x00007fd272c89588   Writable References: 0x00007fd272c89588 - 0x00007fd272f4ae50   Writable Huge: 0x00007fd273000030 - 0x00007fd273029d60   ReadOnly Huge: 0x00007fd27302a030 - 0x00007fd2731beb98  Heap:   Young generation:      Eden:        edenSpace:         aligned: 0/0 unaligned: 0/0     Survivors:        Survivor-1 From:         aligned: 0/0 unaligned: 0/0       Survivor-1 To:         aligned: 0/0 unaligned: 0/0       Survivor-2 From:         aligned: 0/0 unaligned: 0/0       Survivor-2 To:         aligned: 0/0 unaligned: 0/0       Survivor-3 From:         aligned: 0/0 unaligned: 0/0       Survivor-3 To:         aligned: 0/0 unaligned: 0/0       Survivor-4 From:         aligned: 0/0 unaligned: 0/0       Survivor-4 To:         aligned: 0/0 unaligned: 0/0       Survivor-5 From:         aligned: 0/0 unaligned: 0/0       Survivor-5 To:         aligned: 0/0 unaligned: 0/0       Survivor-6 From:         aligned: 0/0 unaligned: 0/0       Survivor-6 To:         aligned: 0/0 unaligned: 0/0       Survivor-7 From:         aligned: 0/0 unaligned: 0/0       Survivor-7 To:         aligned: 0/0 unaligned: 0/0       Survivor-8 From:         aligned: 0/0 unaligned: 0/0       Survivor-8 To:         aligned: 0/0 unaligned: 0/0       Survivor-9 From:         aligned: 0/0 unaligned: 0/0       Survivor-9 To:         aligned: 0/0 unaligned: 0/0       Survivor-10 From:         aligned: 0/0 unaligned: 0/0       Survivor-10 To:         aligned: 0/0 unaligned: 0/0       Survivor-11 From:         aligned: 0/0 unaligned: 0/0       Survivor-11 To:         aligned: 0/0 unaligned: 0/0       Survivor-12 From:         aligned: 0/0 unaligned: 0/0       Survivor-12 To:         aligned: 0/0 unaligned: 0/0       Survivor-13 From:         aligned: 0/0 unaligned: 0/0       Survivor-13 To:         aligned: 0/0 unaligned: 0/0       Survivor-14 From:         aligned: 0/0 unaligned: 0/0       Survivor-14 To:         aligned: 0/0 unaligned: 0/0       Survivor-15 From:         aligned: 0/0 unaligned: 0/0       Survivor-15 To:         aligned: 0/0 unaligned: 0/0   Old generation:      oldFromSpace:       aligned: 0/0 unaligned: 0/0     oldToSpace:       aligned: 0/0 unaligned: 0/0        Unused:     aligned: 0/0  Fatal error: Failed while initializing the performance data.

### Output of `java -version`

Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

2.13.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by geoand** [comment]
Any chance you can provide us with a sample application that behaves like this?

**Comment by fsudrot** [comment]
I can try to keep the entire pom but without corporate source.

**Comment by gsmet** [comment]
I think @loicmathieu already reported it and @zakkak and @galderz created a GraalVM issue for it. IIRC, Mandrel is not affected by this issue but @zakkak can confirm.

**Comment by zakkak** [comment]
> I think @loicmathieu already reported it and @zakkak and @galderz created a GraalVM issue for it. IIRC, Mandrel is not affected by this issue but @zakkak can confirm.

Correct, upstream issue is https://github.com/oracle/graal/issues/5303

**Comment by fsudrot** [comment]
In fact it's not due to my own project. It fails even with rest-json-quickstart

**Comment by gaetancollaud** [comment]
For the lazy that don't want to lookup the workaround in https://github.com/oracle/graal/issues/5303


*src/main/resources/application.yaml*
```yaml
quarkus:
  native:
    container-build: true
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
```

**Comment by gsmet** [comment]
Closing:
- it will be fixed once GraalVM release a fixed version
- in the meantime, you can use Mandrel as it is not affected by the issue
