### ISSUE TITLE
SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image

### ISSUE THREAD

**Issue by bharatnpti** [quarkusio/quarkus#29132]
### Describe the bug

Build failure in multi-module gradle project

 * What went wrong:
2022-11-08T21:35:48.146+0530 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-core:quarkusBuild'.
2022-11-08T21:35:48.146+0530 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image

### Expected behavior

build should be successfully completed

### Actual behavior

build failure with error - **SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image**

### How to Reproduce?

Reproducer:

Steps to reproduce :-

1) Checkout dev branch - https://github.com/techpleiad/core-quarkus/tree/dev
2) build using command - ./gradlew clean build

### Output of `java -version`

17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by bharatnpti** [comment]
@mklueh @aloubyansky - Can you please help me with this issue

**Comment by gsmet** [comment]
@radcortez that might be one for you?

**Comment by aloubyansky** [comment]
That's a assign of the quarkus-bom not being enforced. If I add
````
diff --git a/core-quarkus-parent/platform-quarkus-anonymiser/platform-quarkus-anonymiser-core/build.gradle.kts b/core-quarkus-parent/platform-quarkus-anonymiser/platform-quarkus-anonymiser-core/build.gradle.kts
index 9576883..3a2e0c2 100644
--- a/core-quarkus-parent/platform-quarkus-anonymiser/platform-quarkus-anonymiser-core/build.gradle.kts
+++ b/core-quarkus-parent/platform-quarkus-anonymiser/platform-quarkus-anonymiser-core/build.gradle.kts
@@ -10,6 +10,7 @@ repositories {
 }
 
 dependencies {
+    implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:2.13.2.Final"))
````
it gets passed that error but then fails for another reason. Looks like a Gradle project config issue so far.

**Comment by bharatnpti** [comment]
@aloubyansky - enforcing the quarkus-bom in the "platform-quarkus-anonymiser-core" does help.
However, the same has been already done in base build.gradle.kts, so should we really have to enforce it in sub modules as well ?

**Comment by aloubyansky** [comment]
You should be able to enforce it on subprojects in the root script under `subprojects`. You should consult Gradle docs about that. Since it's not a Quarkus issue, I'm closing this one.

**Comment by bharatnpti** [comment]
Thank you for the help @aloubyansky

**Comment by jmini** [comment]
Related issue/discussion: https://github.com/quarkusio/quarkus/issues/19139

**Comment by windrpha** [comment]
Updating quarkusPluginVersion and quarkusPlatformVersion fixed the issue for me
