### ISSUE TITLE
OIDC token refresh causes NPE if no ID token is returned

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#29144]
### Describe the bug

Some OIDC providers do not return ID token in the refresh token grant response since it is optional in the OIDC spec, which causes NPE since Quarkus OIDC does expect it be returned as is done with Keycloak.

### Expected behavior

If no ID token is returned - then if the previous ID token has not expired - use it, otherwise use the internally generated ID token which is the case now with the previous token claims minus `iat` and `exp` copied

**Comment by DCCSKrezovic** [comment]
@sberyozkin I have a working prototype that I have tested in production-like scenarios. Should I submit a PR, or have you already done something?

**Comment by sberyozkin** [comment]
@DCCSKrezovic I've been working on it since yesterday, just about to open a PR; glad you are willing to help :-)
