### ISSUE TITLE
Java 11+GraalVM: Kafka Crc32C uses method handle

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2914]
**Describe the bug**
The `org.apache.kafka.common.utils.Crc32C` class is using a method handle under Java 9+ to access the public constructor of `java.util.zip.CRC32C`; this fails with `native-image`.

Ideally the Kafka library would utilize a multi-release JAR to just call the constructor directly instead of resorting to reflection to solve this issue.  Failing that, we should just do it ourselves using a MR-JAR substitution.

**Comment by emmanuelbernard** [comment]
Just to clarify, you are talking about the experimental Java 11 GraalVM support or does it also fail with Java 8 GraalVM?

**Comment by dmlloyd** [comment]
This is Java 11 with GraalVM.  Maybe we should have a label for these issues (I've just indicated it by the issue title only) because there may be many of them over the next few weeks.
