### ISSUE TITLE
A Kafka header baggage is propagated to the TracingMetadata. previousSpancontext, but not to the currentSpanContext

### ISSUE THREAD

**Issue by mrickly** [quarkusio/quarkus#29151]
### Describe the bug

The ` KafkaSource` maps an incoming OTEL baggage header to the `TracingMetadata.previousSpanContext`. 
The baggage cannot be accessed via `Baggage.current()` in an incoming method for instance. 
Instead, one has to do something like 
`Baggage.fromContext(message.getMetadata(TracingMetadata.class).get().getPreviousContext());` 
in order to access the baggage. 

### Expected behavior

In an incoming method, independently of the type of the method argument (it could be a payload type only), the baggage from the incoming Kafka record can be accessed with `Baggage.current()`.

### Actual behavior

In an `@Incoming` method with a `Message<Offer>` argument type (where `Offer` is a trivial dto), the `Baggage.current()` is empty. In order to access the baggage, one has to do `Baggage.fromContext(message.getMetadata(TracingMetadata.class).get().getPreviousContext());`, which wouldn't work if the argument type wasn't a `Message`. 

### How to Reproduce?
Class with incoming method and QuarkusTest class: 

```
@ApplicationScoped
public class OfferProcessor {

    private static final Logger LOGGER = Logger.getLogger(OfferProcessor.class);

    public static final String EXPECTED_BAGGAGE_KEY = "mykey";

    @Incoming("offer")
    public CompletionStage<Void> process(Message<Offer> message) {
        if (Baggage.current().isEmpty()) {
            LOGGER.info("baggage current is empty");
        }
        Baggage baggageFromCurrentContext =
                Baggage.fromContext(message.getMetadata(TracingMetadata.class).get().getCurrentContext());
        if (baggageFromCurrentContext.isEmpty()) {
            LOGGER.info("empty baggage in current context");
        }
        Baggage baggageFromPreviousContext =
                Baggage.fromContext(message.getMetadata(TracingMetadata.class).get().getPreviousContext());
        if (!baggageFromPreviousContext.isEmpty()) {
            String entryValue = baggageFromPreviousContext.getEntryValue(EXPECTED_BAGGAGE_KEY);
            LOGGER.info(String.format("found non-empty baggage in previous context: key=%s, value=%s ", EXPECTED_BAGGAGE_KEY,
                    entryValue));
        } return message.ack();
    }

}

@QuarkusTest
@QuarkusTestResource(KafkaCompanionResource.class)
public class NoBaggageIT {

    @InjectKafkaCompanion
    KafkaCompanion kafkaCompanion;

    @Test
    void willLogBaggagesReceivedByProcessor() throws InterruptedException {
        kafkaCompanion.registerSerde(Offer.class, new ObjectMapperSerializer<>(), new ObjectMapperDeserializer<>(Offer.class));
        String key = UUID.randomUUID().toString();
        String offerId = UUID.randomUUID().toString();
        Offer offer = new Offer(offerId, "offer details");
        List<Header> headers = new ArrayList<>();
        RecordHeader baggageHeader =
                new RecordHeader("baggage", (EXPECTED_BAGGAGE_KEY + "=" + "myvalue").getBytes(StandardCharsets.UTF_8));
        headers.add(baggageHeader);
        kafkaCompanion.produce(String.class, Offer.class).fromRecords(new ProducerRecord<>("offer", null, key, offer, headers));
        Thread.sleep(2000L);
    }

}

```

### Output of `java -version`

17.0.2

### Quarkus version or git rev

2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.4

**Comment by mrickly** [comment]
#28244 @brunobat: Let me know if you need more info in the reproducer (like pom, properties, etc.)

**Comment by mrickly** [comment]
Our current workaround for this is to add the baggage to the context and make that the new current context in our own decorator (with priority=3000), which runs after `ReactiveMessagingTracingDecorator`.

**Comment by brunobat** [comment]
Hi @ozangunalp! Do you plan to work on this in the near future?

**Comment by ozangunalp** [comment]
@brunobat it'll be great if you can take a look! I am not sure if OTel propagates baggage automatically. So maybe the mentioned workaround is the way to go?

**Comment by brunobat** [comment]
Yes, I think the proposed solution can work. Get the data from the headers and make it part of the current Baggage in order to be accessed and propagated forward.

**Comment by mrickly** [comment]
Hi @ozangunalp , @brunobat : I'm back from a two weeks vacation. I need to check this, I'm not sure that it is still relevant. I'll get back to you this week.

**Comment by mrickly** [comment]
@ozangunalp , @brunobat : Verified today that a baggage key-value pair transported via producer record `baggage` header is now mapped and available in the `Baggage.current()`. The workaround mentioned above was removed from our code around 6 months ago. The change coincides with our upgrade to Quarkus 3.0. So apparently that was fixed in the Otel propagation.

**Comment by ozangunalp** [comment]
@mrickly thank you for the feedback!
