### ISSUE TITLE
Integrate FileVault Utils with Quarkus CLI

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#29172]
### Description

It would be useful for Quarkus users working with `ConfigSource` based on  Java `KeyStore` (which will be introduced into Quarkus via smallrye config) be able to run the command line utility which can encrypt the keystore password (which will be decrypted by ConfigSource with an earlier priority than the `KeyStore` based `ConfigSource`).
The utility is currently hosted here: https://github.com/quarkiverse/quarkus-file-vault/tree/main/vault-utils

CC @maxandersen @tqvarnst

**Comment by maxandersen** [comment]
@sberyozkin @radcortez where we are we on this? reusing vault-utils or something else?

**Comment by radcortez** [comment]
I've recently added JBang scripts to encrypt the passwords in SmallRye Config, since I didn't want to add a CLI utility. In Quarkus we already have one, so we can push it there.
