### ISSUE TITLE
@ServerResponseFilter and @ServerRequestFilter fails on startup with NoSuchMethodException

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#29170]
### Describe the bug

When upgrading to Quarkus 2.14.10 startup of application with @ServerResponseFilter and @ServerRequestFilter crash on startup with
```
... 
Caused by: java.lang.NoSuchMethodException: org.acme.RequestLogger$GeneratedServerRequestFilter$filter.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3617)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2786)
	at io.quarkus.arc.runtime.BeanContainerImpl$DefaultInstanceFactory.create(BeanContainerImpl.java:78)
	... 26 more
```
(Or org.acme.RequestLogger$GeneratedServerResponseFilter$filter.<init>())

### Expected behavior

The filters are created and app starts successfully

### Actual behavior

Application crash on startup

### How to Reproduce?

https://github.com/computerlove/NoSuchMethodException-GeneratedServerRequestFilter
The application crash on startup when running `mvn quarkus:dev`

### Output of `java -version`

17

### Quarkus version or git rev

2.14.0

**Comment by geoand** [comment]
Actually there may be more to it... I need to take another look

**Comment by geoand** [comment]
It was a mistake on my part. https://github.com/quarkusio/quarkus/pull/29171 fixes the issue

**Comment by geoand** [comment]
@gsmet this seems like a very nasty one that slipped through, so if possible, it would probably make sense to not wait long for `2.14.1`

**Comment by gsmet** [comment]
@geoand I can do one on Tuesday but not before that. I think it should work, people can use 2.13.4.Final until then.

**Comment by geoand** [comment]
Sounds good, thanks!
