### ISSUE TITLE
Multipart broken in RESTEasy Reactive when using new CSRF filter

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#29187]
### Describe the bug

When using the new CSRF security filter, multipart support is broken in RESTEasy Reactive, leading to only the form elements that have no `filename` to be picked up. This is because the CSRF pre-matching filter suspends the request and waits for Vert.x to read the form body:

```java
    private static Uni<MultiMap> getFormUrlEncodedData(HttpServerRequest request) {
        request.setExpectMultipart(true);
        return Uni.createFrom().emitter(new Consumer<UniEmitter<? super MultiMap>>() {
            @Override
            public void accept(UniEmitter<? super MultiMap> t) {
                request.endHandler(new Handler<Void>() {
                    @Override
                    public void handle(Void event) {
                        t.complete(request.formAttributes());
                    }
                });
                request.resume();
            }
        });
    }
```

While RESTEasy Reactive usually handles the form body parsing itself, so it has not set up Vert.x with a `BodyHandler` that would do things properly. The result is that Vert.x only populates the `formAttributes()` with the attributes it gets from Netty's `HttpPostRequestDecoder`, which don't include the attributes with a `filename`. Those would only get handled by `BodyHandler`.

Then, when RESTEasy Reactive's `FormBodyHandler` gets called after the CSRF filter, before it handles the custom parsing, it checks if Vert.x already read the form, and yes it did (partially):

```java
        FormData existingParsedForm = requestContext.serverRequest().getExistingParsedForm();
        if (existingParsedForm != null) {
            requestContext.setFormData(existingParsedForm);
            return;
        }
```

But this will only get half the form attributes. So when using the CSRF filter as it currently stands, all multipart form elements with a `filename` will be omitted, and also the custom RESTEasy Reactive form parsers are bypassed entirely, which was added because of https://github.com/quarkusio/quarkus/pull/17687 and perhaps that's more of an issue.

I'm not sure if we should fix the side-effect and make sure that Vert.x populates the `fileUploads()` properly for the CSRF filter, or to find a way to make the filter run the `FormBodyHandler` before it runs. Given that it's a pre-matching filter, this appears very intrusive.

Perhaps we've looked at this the wrong way, and it can't be implemented by a filter at all. Perhaps this CSRF checking should be a RR Handler that sits after the `FormBodyHandler` and before we invoke the endpoint.

This would actually allow me to solve another issue that I have in UX of this new CSRF module, because I've noticed that because we can only enable CSRF for the entire application, it means turning it on secures the HTML POST endpoints (fine) but also any REST API POST endpoints that are not meant to be called by HTML. Now, perhaps this is actually fine, because any REST API POST endpoints we define would be reacheable by HTML anyway, given that they have the same origin, and so would be vulnerable, so we should secure them anyway, or offer them via another origin. I'm not too sure about this.

/CC @ser

### How to Reproduce?

Test:

```java
    @Test
    public void testPost() {
        RenardeCookieFilter cookieFilter = new RenardeCookieFilter();
        String csrfToken = given()
                .filter(cookieFilter)
                .when().get("/Application/csrfToken")
                .then()
                .statusCode(200)
                .extract().asString();
   
        given()
                .filter(cookieFilter)
                .when()
                .multiPart("csrf-token", csrfToken)
                .multiPart("param", "myParam")
                .multiPart("file", "file.txt", "file contents".getBytes(), MediaType.TEXT_PLAIN)
                .multiPart("fileUpload", "fileUpload.txt", "upload file contents".getBytes(), MediaType.TEXT_PLAIN)
                .log().all()
                .post("/Application/form")
                .then()
                .statusCode(200)
                .body(is("param: myParam, file: file contents, fileUpload: fileUpload.txt"));
    }
```

Endpoint:

```java
@Path("Application")
public class Application {

    @Inject
    CsrfTokenParameterProvider csrfToken;

@GET
@Path("csrfToken")
    public String csrfToken() {
        return csrfToken.getToken();
    }

    public static class DamnMultiPart {
        @RestForm
        File file;
        @RestForm
        public FileUpload fileUpload;
    }

    @Consumes(MediaType.MULTIPART_FORM_DATA)
@Path("form")
    @POST
    public String form(@RestForm String param,
            @MultipartForm DamnMultiPart damnit) throws IOException {
        return "param: " + param + ", file: " + Files.readString(damnit.file.toPath()) + ", fileUpload: "
                + damnit.fileUpload.fileName();
    }
}
```

**Comment by sberyozkin** [comment]
>Perhaps this CSRF checking should be a RR Handler that sits after the FormBodyHandler and before we invoke the endpoint.

If it is how it should be fixed then sure

**Comment by geoand** [comment]
Let me know if you need any help on this

**Comment by sberyozkin** [comment]
Thanks, I'll try to have a look next week
