### ISSUE TITLE
invocationContext.getTarget().getClass().getMethods() in @Interceptor @PostConstruct does not contains custom Method annotations

### ISSUE THREAD

**Issue by waldimiro** [quarkusio/quarkus#2918]
**Describe the bug**
invocationContext.getTarget().getClass().getMethods() in @Interceptor @PostConstruct does not contains custom Method annotations.

**Expected behavior**
invocationContext.getTarget().getClass().getMethods() contains custom method annotations.

**Actual behavior**
To retrieve method annotations, I must iterate methods over ((Class<?>) invocationContext.getTarget().getClass().getGenericSuperclass()).getMethods()

**To Reproduce**
Given  

```
@MyInterceptor
@ApplicationScoped
public class MyIntercepted {

	@MyAnnotation
	public void myMethod() {
	}
}

@MyInterceptor
@Interceptor
@Priority(Interceptor.Priority.APPLICATION)
public class MyInterceptor {

	@PostConstruct
	public void postConstruct(InvocationContext invocationContext) throws Exception {

		// Scan for external task method annotation
		Arrays.stream(invocationContext.getTarget().getClass().getMethods())
				.forEach(method -> {
// Methods have no annotations
				});
}
}

```

**Environment (please complete the following information):**
 - RedHat OpenJDK 11.0.3.7
 - Quarkus version 0.17.0

**Comment by gsmet** [comment]
@mkouba I suppose it's related to Arc? Not sure what the behavior should be but I'm pretty sure you're the person to answer that :).

**Comment by mkouba** [comment]
I'm sorry but I wasn't able to reproduce the issue. In your case, `invocationContext.getTarget()` should return the instance of `MyIntercepted` and if so, then it's up to the JDK reflection ad eveything should work as expected. You're mentioning `getGenericSuperclass()` in the description. For `MyIntercepted` this method should return `null` so I suppose that was another example?

**Comment by waldimiro** [comment]
In my case invocationContext.getTarget() returns a "MyIntercepted_Subclass" class...

**Comment by mkouba** [comment]
I see. In that case, the `MyIntercepted` bean has some methods intercepted as well and a subclass instance must be used as a contextual instance and also as `InvocationContext.getTarget()`. The methods declared on the subclass do not declare any annotations and so your solution using `getGenericSuperclass()` is correct. You may also test the target class to implement `io.quarkus.arc.Subclass` to be sure you need to inspect the superclass instead.

**Comment by mkouba** [comment]
@manovotn I would expect the same behavior in Weld, right?

**Comment by manovotn** [comment]
Yes, Weld subclasses (and proxies) do not inherit annotations either. These subclasses are generally considered to be hidden away from user so having annotations doesn't make much sense plus you would get into troubles detecting which annotations are to be there (`@Inherited` ones and so on).

**Comment by waldimiro** [comment]
I have more information about this problem. When I add to MyIntercepted another interceptor (in my case @Lock from https://www.knitelius.com/2016/01/25/concurrency-control-for-cdi/), the invocationContext.getTarget() object in MyInterceptor. postConstruct is different as when I have only MyIntercepted interceptor.

**Comment by mkouba** [comment]
@waldimiro could you be more specific? Also your interceptor is `@PostConstruct` whereas the `LockInterceptor` is `@AroundInvoke`...
