### ISSUE TITLE
Add "hibernate.query.in_clause_parameter_padding" as a supported configuration parameter

### ISSUE THREAD

**Issue by rhotz-bossard** [quarkusio/quarkus#29196]
### Description

We're using `quarkus.hibernate-orm.unsupported-properties."hibernate.query.in_clause_parameter_padding"=true` to improve the statement caching for heavily used IN clause queries.

I propose to add `hibernate.query.in_clause_parameter_padding` as a supported Quarkus parameter.

Thanks!

**Comment by gsmet** [comment]
I think it's a good idea. Looks like a good first issue!

**Comment by zedbeit** [comment]
Would love to take a stab at this, any ideas on how to go abt this @gsmet ?

**Comment by Ashyum** [comment]
Hey, I want to contribute to this project, but I don't know how to start. I know Java. What else do I need to learn before I can start contributing? Please help me little in understanding this issue or give me some direction. Thank you

**Comment by zedbeit** [comment]
@Ashyum to learn about quarkus, the [quarkus guides](https://quarkus.io/guides/) is the best place to get started. You should also try to play around with it by building some applications with it.

**Comment by zedbeit** [comment]
I reckon the task is to add a configuration property as a supported Quarkus parameter, so I'm thinking that may be there should be a list of properties somewhere, but I checked in the hibernateorm extension but could not find it. @gsmet

**Comment by mfpc** [comment]
Hi,

I want to do this. Which files I should start to look? Could you @gsmet give me a explaning. Thank you!

**Comment by gsmet** [comment]
It should be added in the configuration here: https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java#L305 .

Then you should be able to figure out where to use the config by having a look at how we deal with others.

**Comment by mfpc** [comment]
@gsmet Thanks
