### ISSUE TITLE
How to set SSL required to NO_REQUIRED?

### ISSUE THREAD

**Issue by GuangjieZHANG** [quarkusio/quarkus#2921]
I'am configuring a quarkus project with Keycloak.
When I test it locally, it works well.
But when I deployed it in docker with a remote address and then I test it with Postman, it said:   WARN  [org.key.ada.RequestAuthenticator] (executor-thread-1)  SSL is required to authenticate. Remote address 176.***.***.** is secure: false, SSL required for: EXTERNAL .
And it returns a 403 Forbidden.
Is there a solution to modify this parameter for SSL required? I tried to find it online but failed.
I tried to use traefik but it didn't work.

**Comment by gsmet** [comment]
@pedroigor any chance you could answer this one?

**Comment by pedroigor** [comment]
@GuangjieZHANG, could you please try to set `quarkus.keycloak.ssl-required=NONE` ?

For more details about the different configuration options, see https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config.

**Comment by GuangjieZHANG** [comment]
Thanks so much!!!!!  It works!!!! I've spent at least 10 days and now it works well. 
Merci beaucoup! @pedroigor @gsmet

**Comment by pedroigor** [comment]
@GuangjieZHANG, thank you for trying this out. We do have a link to that doc at https://quarkus.io/guides/keycloak-guide. But maybe we should make it more visible given that it is quite hidden at the bottom of the page :)

**Comment by GuangjieZHANG** [comment]
Yes it really was. I was looking for a document like this for a long time but always not getting it. 
Btw Quarkus is really cool~ Thanks for you all ! @pedroigor

**Comment by GuangjieZHANG** [comment]
I have found this document and configured the project according to this page : https://quarkus.io/guides/keycloak-guide. but in this guide I did't find how to disable the ssl-required.  
Now it really works.
BTW, Quarkus is really cool and thanks so much to you all ! @pedroigor

**Comment by ahamid** [comment]
> @GuangjieZHANG, could you please try to set `quarkus.keycloak.ssl-required=NONE` ?
> 
> For more details about the different configuration options, see https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config.

I arrived at this issue even though this is a Keycloak-specific question.  I am using the quay.io Keycloak 18 image. It is not clear where to "set" the `quarkus.keycloak.ssl-required`. Is this a Java system property?

```
Appending additional Java properties to JAVA_OPTS: -Dquarkus.keycloak.ssl-required=NONE
2022-05-23 20:46:52,889 WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.keycloak.ssl-required" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by MRiabov** [comment]
I know I am like 4 years late, but isn't quarkus.keycloak.ssl-required=NONE is borderline insecure? That's what we are trying to avoid, are we not?
