### ISSUE TITLE
Some release candidate or or alpha versions are not marked as "Pre-release"

### ISSUE THREAD

**Issue by marcwrobel** [quarkusio/quarkus#29226]
### Description

Usually release candidates or alpha versions in https://github.com/quarkusio/quarkus/releases, such as https://github.com/quarkusio/quarkus/releases/tag/2.13.0.CR1, are marked in GitHub as "Pre-release".

But some are not :

- https://github.com/quarkusio/quarkus/releases/tag/1.5.0.CR1
- https://github.com/quarkusio/quarkus/releases/tag/1.4.0.CR1
- https://github.com/quarkusio/quarkus/releases/tag/1.3.0.CR2
- https://github.com/quarkusio/quarkus/releases/tag/1.3.0.CR1
- https://github.com/quarkusio/quarkus/releases/tag/1.3.0.Alpha2
- https://github.com/quarkusio/quarkus/releases/tag/1.3.0.Alpha1
- https://github.com/quarkusio/quarkus/releases/tag/1.2.0.CR1
- https://github.com/quarkusio/quarkus/releases/tag/1.1.0.CR1
- https://github.com/quarkusio/quarkus/releases/tag/1.0.0.CR2
- https://github.com/quarkusio/quarkus/releases/tag/1.0.0.CR1

This make it more difficult for automation tools to filter out those versions.

### Implementation ideas

Edit the above versions in GitHub and set each of them as "Pre-release".

**Comment by gsmet** [comment]
Yeah we automated it at some point but the releases prior to that point were not marked appropriately.

It should be fixed now.

**Comment by marcwrobel** [comment]
Thanks, fix confirmed.
