### ISSUE TITLE
Add metrics to the gRPC client and server

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#29236]
### Description

The idea is to provide a set of meaningful metrics for the gRPC client and server (using the new gRPC backend), such as:
- response time
- the amount of errors + code
- payload size
- ...

**Comment by cescoffier** [comment]
We already have metrics in place, so this issue is modestly about verifying we have meaningful ones.

**Comment by cescoffier** [comment]
#29690 produces metrics for the Vert.x gRPC clients.

**Comment by geoand** [comment]
> We already have metrics in place, so this issue is modestly about verifying we have meaningful ones.

@cescoffier has this been done?

**Comment by cescoffier** [comment]
Not yet - short on resources. 

We have the metrics, we need to see if the exposed ones are:

1) actionable (and not dark metrics, which are metrics reported but unusable)
2) descriptive
3) contain the key ones 

Actually, this exercise should not only be done for gRPC but almost everything.

**Comment by cescoffier** [comment]
I just checked and everything is already supported (with the grpc java server and client and the Vert.x server (use-separate-server=false) and Vert.x client (use-quarkus-grpc-client=true)
