### ISSUE TITLE
Qute: Provide a clean way to return multiple fragments in one response (Htmx OOB Swap)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#29247]
### Description

HTMX allow to do Out of band swapping of content:
https://htmx.org/attributes/hx-swap-oob/

This means that the response contains multiple fragments of the view to be updated.

Example:
![Kapture-2022-11-14-at-09 33 16](https://user-images.githubusercontent.com/2223984/201635523-32c967ab-f597-45a6-91ce-fcf83e94d5b0.gif)

When you click on the note, you need to update both the editor and the list of note.

### Implementation ideas

I currently use this as a workaround:
oob.html
```html
{#for i in items}
{i.raw}
{/for}
```

```java
    public static native TemplateInstance oob(Uni<String>... items);
...
    @Path("/note/{id}")
    public TemplateInstance editNote(@PathParam("id") Long id) {
        final Note note = Note.findById(id);
        if(note == null) {
            notes(null);
            return null;
        }
        if (isHxRequest()) {
            return  Templates.oob(
                    Templates.notes$noteList(Note.listAllSortedByLastUpdated(), id).createUni(),
                    Templates.notes$noteForm(note).createUni()
                    );
        }
        return Templates.notes(Note.listAllSortedByLastUpdated(), id, note);
    }
```

**Comment by mkouba** [comment]
I'm not quite sure this would be useful outside HTMX so it might be reasonable to introduce a static util method like this:
```java
public final Htmx {

  public static TemplateInstance concatTemplates(TemplateInstance... templates) {
        return Qute.fmt("{#each elements}{it.raw}{/each}")
                .cache()
                .data("elements", Arrays.stream(templates).map(TemplateInstance::createUni))
                .instance();
   }
}
```

**Comment by ia3andy** [comment]
This seems like a very good solution, I'll add it to the Renarde HxController for now.

**Comment by ia3andy** [comment]
Thanks!
