### ISSUE TITLE
Jakarta - EE 10 - @Inject should work instead of the deprecated @Context in RESTEasy Classic

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#29240]
### Describe the bug

In JAX-RS we used to use `@Context` to inject several managed objects, including `UriInfo`:

```
import jakarta.ws.rs.core.Context;

@Path("/hello")
public class GreetingResource {

    @Context
    UriInfo uriInfo;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        System.out.println("Base URI: " + uriInfo.getBaseUri());
        return "Hello RESTEasy";
    }
}
```

With Jakarta EE 10 and JAX-RS 4 we can use `@Inject` [instead](https://jakarta.ee/specifications/restful-ws/4.0/):

```    
@Inject
UriInfo uriInfo;
```

ATM, this code breaks with RESTEasy Classic (it works with RESTEasy Reactive) with the following exception:

```
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type jakarta.ws.rs.core.UriInfo and qualifiers [@Default]
        - java member: org.acme.GreetingResource#uriInfo
        - declared on CLASS bean [types=[org.acme.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.GreeetingResource]
````

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```

See https://jakarta.ee/specifications/restful-ws/4.0
Relates to: https://github.com/jakartaee/rest/issues/951

### Quarkus version or git rev

3.0.0.Alpha1

**Comment by geoand** [comment]
Are you using `quarkus-resteasy` or `quarkus-resteasy-reactive`?

Asking because the latter should already support what you are asking for (I don't know about the former)

**Comment by agoncal** [comment]
@geoand good point. I've just updated the title and body of the issue. It works with RestEasy Reactive but not RestEasy Classic

**Comment by geoand** [comment]
Thanks for checking.

cc @jamezp @gsmet for RESTEasy Classic

**Comment by jamezp** [comment]
It should work with RESTEasy 6.2 if the `org.jboss.resteasy:resteasy-cdi` dependency is used. Method parameter injection does not currently work, but it's also not required in Jakarta REST 3.1.

**Comment by agoncal** [comment]
Correct, if I have the following 2 dependencies, it works. Will it stay like that or will depending just on `quarkus-resteasy` be enough in future releases?

```
  <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy</artifactId>
  </dependency>
  <dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-cdi</artifactId>
  </dependency>
```

**Comment by gsmet** [comment]
We should definitely add `resteasy-cdi`. I will take care of it.
