### ISSUE TITLE
Resteasy + Hibernate Validator : @Produces on super interface is not taken into account, JSON is default

### ISSUE THREAD

**Issue by YassinHajaj** [quarkusio/quarkus#29253]
### Describe the bug

I have a `ResourceInterface` and a `ResourceImplementation`.

The `ResourceInterface` defines everything related to JAX-RS and OpenAPI.x

It looks like this

```
// ...
@Produces("application/xml")
@Consumes("application/xml")
public interface ResourceInterface {
    //...
    @POST
    Output method(@Valid Input input);
    //....
```

The `ResourceImplementation` looks like this

```
@ApplicationScoped
public class ResourceImplementation implements ResourceInterface {
    //...
    public Output method(Input input) {
        //....
    }
}
```

When I get a validation exception, it gets outputted as JSON, even though I specified XML on the class as described by the JAX-RS specification.

The guilty piece of code is the following, that only checks on the invoked method and class but not the super.

This comes from `JaxrsEndPointValidationInterceptor`

```
    @AroundInvoke
    @Override
    public Object validateMethodInvocation(InvocationContext ctx) throws Exception {
        try {
            return super.validateMethodInvocation(ctx);
        } catch (ConstraintViolationException e) {
            throw new ResteasyViolationExceptionImpl(e.getConstraintViolations(), getProduces(ctx.getMethod()));
        }
    }

    @AroundConstruct
    @Override
    public void validateConstructorInvocation(InvocationContext ctx) throws Exception {
        super.validateConstructorInvocation(ctx);
    }

    private List<MediaType> getProduces(Method method) {
        MediaType[] producedMediaTypes = MediaTypeHelper.getProduces(method.getDeclaringClass(), method);

        if (producedMediaTypes == null) {
            if (resteasyConfigSupport.isJsonDefault()) {
                return JSON_MEDIA_TYPE_LIST;
            }

            return Collections.emptyList();
        }

        return Arrays.asList(producedMediaTypes);
    }

```

### Expected behavior

Return validation error as XML

### Actual behavior

Returns validation error as JSON

PS : Of course, a workaround is possible. The annotation should be put on the implementating class' method. It doesn't work when put on the interface's class method.

### How to Reproduce?

Create the classes as described above and produce a validation error.
It will get outputed as JSON and not XML.

**Comment by YassinHajaj** [comment]
I just noticed that adding the `@Produces` on the method of the interface does not fix it.
It should really be put on the classes method to workaround the problem.

**Comment by YassinHajaj** [comment]
Hi @gsmet,

Here it is : https://github.com/YassinHajaj/quarkus-issue-29253

**Comment by yrodiere** [comment]
Hey @gsmet, in case you missed it:

> Hi @gsmet,
> 
> Here it is : https://github.com/YassinHajaj/quarkus-issue-29253
