### ISSUE TITLE
Remove confusing reference to libcrypt

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2925]
Fedora 29 ships with libcrypt.so.1
Fedora 30 ships with libcrypt.so.2

GraalVM uses libcrypt.so.1 so we moved to ubi as base image to avoid this problem.
GraalVM is planning to remove that dependency: https://github.com/oracle/graal/issues/1340#issuecomment-498653502

So not to confuse people I'll remove the reference

**Comment by cescoffier** [comment]
PR merged.
