### ISSUE TITLE
Docker templates and docs say to use `JAVA_OPTS` but `run-java.sh` docs say `JAVA_OPTIONS`, and `JAVA_OPTS_APPEND` does not exist

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#29283]
### Describe the bug

We ran into a production issue where the `JAVA_OPTS` variable was not being honored.
Some of our users have stringent vulnerability requirements so we cannot use the default Dockerfile image.

To get around this, we created a custom Dockerfile where we use a more recent base image and emulate the same functionality:

```dockerfile
FROM registry.access.redhat.com/ubi9-minimal:9.0.0-1580

ARG RUN_JAVA_VERSION=1.3.8
ARG JAVA_PACKAGE=java-17-openjdk-headless

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

RUN microdnf install -y ${JAVA_PACKAGE} \
    && microdnf update -y \
    && microdnf clean all \
    && mkdir /deployments \
    && chown 185 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 185:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 185 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080 5005
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT ["/deployments/run-java.sh"]
```

The generated Docker template says this:

https://github.com/quarkusio/quarkus/blob/affcf54e6f2d202b8a40989718d0dc264736c72e/integration-tests/maven/src/test/resources-filtered/projects/codegen-config-factory/app/src/main/docker/Dockerfile.jvm#L26-L29

But in the `run-java` repo, there doesn't seem to be a `JAVA_OPTS` or `JAVA_OPTS_APPEND`:

![image](https://user-images.githubusercontent.com/26604994/201981944-79d28f21-034f-471c-ba92-451b4cd9f3f8.png)

**Comment by geoand** [comment]
Perhaps Things have changed in the run-java script and we have not updated the comments in our generated Dockerfile?

**Comment by GavinRay97** [comment]
I guess literally nobody is setting non-default JVM options on their Quarkus containers? 🤣 
Quite wild

**Comment by mkouba** [comment]
FTR the source of the generated dockerfile is here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute

**Comment by mkouba** [comment]
CC @cescoffier

**Comment by cescoffier** [comment]
So, we need to check as we had several `run-java.sh` over the years...
I need to check the one provided by the lastest UBI Java runtime image. The template is quite old, and the property name likely changed.

**Comment by cescoffier** [comment]
Confirmed, here is the line:
```
  echo "${JAVA_OPTS} $(run_java_options) ${debug_opts} ${proxy_opts} ${java_opts} ${JAVA_OPTS_APPEND}" | awk '$1=$1'
```

I will update the template.

**Comment by cescoffier** [comment]
Hum, that sucks...

The old one is:
```
  echo "${JAVA_OPTIONS:-} $(run_java_options) $(debug_options) $(proxy_options) $(java_default_options)" | awk '$1=$1'
  ```

It's what I was afraid of.... something changed, and it's a breaking change.

**Comment by cescoffier** [comment]
Basically, for docker file downloading run-java with this line:
```
 https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh
```

The current documentation is correct.

For dockerfile using the built-in run-java, it's not...

**Comment by cescoffier** [comment]
So, it's correct.

The new template uses the built-in `run-java.sh `. As you can see in `https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute`, it does download the script from maven central. 

However, if you use a docker file using the fabric8 version of the script (not sure it's maintained), it's `JAVA_OPTIONS`.

In this case, it uses:

- `FROM registry.access.redhat.com/ubi9-minimal:9.0.0-1580` -> does not have a built-in run-java, and we do not run any test with ubi 9 at the moment
- `&& curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \` - so download the fabri8 version of the script which is not the one we recommend anymore.

**Comment by GavinRay97** [comment]
@cescoffier Ah, sorry to waste your time. This is slightly confusing to me.

Could anyone point me to where the `run-java.sh` that the default Quarkus templates use come from, please? 🙏

**Comment by cescoffier** [comment]
@GavinRay97 here: https://github.com/jboss-container-images/openjdk/tree/ubi9/modules - the main script in the run module.

**Comment by GavinRay97** [comment]
Thank you!!
