### ISSUE TITLE
Qute- Let let refernce previous assignments

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#29290]
### Description

Currently, the following fails, as the first variable assignment isn't present when the second is processed:

```
{#let calculatedObj=calculator.calculate() someResult=calculatedObj.getResultOne()}
   ...
{/let}
```
It would be nice to be able to do this and be able to assign more variables based on previous assignments in the same `let` statement

**Comment by mkouba** [comment]
A workaround is to use a nested `{#let}` for dependent _variables_:

```
{#let calculatedObj=calculator.calculate()}
{#let someResult=calculatedObj.getResultOne()}
   ...
{/}{/}
```
