### ISSUE TITLE
ServerJacksonMessageBodyReader and JacksonBasicMessageBodyReader "should" catch JsonProcessingException

### ISSUE THREAD

**Issue by damonsutherland** [quarkusio/quarkus#29316]
### Describe the bug

When de-serializing JSON in a request, we want to catch client input errors due to malformed data. Unfortunately, we have run into situations where the exception Jackson is throwing is one of several JsonProcessingExceptions, i.e., a JsonMappingException, JsonParseException or DatabindException. As a result, the intended BAD_REQUEST is met with a SERVER_ERROR. 

Using ExceptionMappers can work, if we are diligent in catching JsonProcessingException's in any location we use an ObjectMapper. If we are not diligent, then an ExceptionMapper will lead to a client error when it is actually a server error.

Corresponding locations: 
[JacksonBasicMessageBodyReader](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/jackson/src/main/java/org/jboss/resteasy/reactive/server/jackson/JacksonBasicMessageBodyReader.java#L35)

[ServerJacksonMessageBodyReader](https://github.com/quarkusio/quarkus/blob/2.14/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/runtime/src/main/java/io/quarkus/resteasy/reactive/jackson/runtime/serialisers/ServerJacksonMessageBodyReader.java#L36)

Updating these locations to catch JsonProcessingException should resolve the issues we are seeing.

### Expected behavior

BAD_REQUEST is thrown when input is malformed.

### Actual behavior

SERVER_ERROR is thrown.

### How to Reproduce?

This is a simplified version of what we are doing, only the details causing the issue are included.

```
public class Data {
  private String type;

  @JsonCreator
   public Data(
      @JsonProperty("type") String type
      ...
   ) {
      this.type = Objects.requireNonNull(type);
   }
}
```

Deserialize with the following line of code (throws a ValueInstantiationException):

```
mapper.readValue("{}", Data.class)
```

When via a controller, i.e., we should get 400 if the request body is "{}".
```
public Controller {

  @POST
  @Path("/")
  public void receive(Data data) {
  
  }
}
```

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64

### Output of `java -version`

17.0.3 (Eclipse Adoptium 17.0.3+7)

### Quarkus version or git rev

2.8.3-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3 ------------------------------------------------------------  Build time:   2021-11-09 20:40:36 UTC Revision:     96754b8c44399658178a768ac764d727c2addb37  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.3 (Eclipse Adoptium 17.0.3+7) OS:           Mac OS X 12.6.1 x86_64

**Comment by damonsutherland** [comment]
As a side note, the work-around is easy; just posting this bug to help keep the intention of the ServerJacksonMessageBodyReader pure.

**Comment by geoand** [comment]
Are you sure that `JsonProcessingException` isn't too broad? I can't really tell from its Javadoc whether it's only about malformed input

**Comment by damonsutherland** [comment]
We could certainly be more targeted. JsonProcessingException seemed appropriate to me. That said, there are two general issues I am hoping to address:

1. **Malformed JSON:** Missing a closing brace, comma's in the wrong place, i.e., basic syntax issues. From what I can tell, these types of issues manifest as a JsonParseException (which inherits StreamingReadException, which inherits JsonProcessingException).
2. **Syntactically correct JSON with invalid constraints:** Missing required field(s). These types of exceptions seem to manifest as ValueInstantiationException when Object construction is initiated by constructor injection or factory method. ValueInstantiationException is a sibling to MismatchedInputException and InvalidDefinitionException. All of these inherit JsonMappingException, which is slated to go away in favor of DatabindException. DatabindException inhereits JsonProcessingException. 

Looking at the docs, there are basically two paths through Jackson, parsing and generating. JsonProcessingException is used in both paths, so in that sense, it is too broad. However, in the context of a MessgeBodyReader, only the parsing path is exercised. 

The other place that it may be too broad is with InvalidDefinitionException, which generally would indicate a problem with the target type definition and not necessarily the input.  Generally, I would expect a mistake that would prevent de-serialization to be caught in unit tests, but when used in a broader framework like Quarkus, it is probably naive to think unit tests would be used that vigorously. So ...

While JsonProcessingException works for our case, it would probably be better to be surgical and catch the following Exceptions:
* ValueInstantiationException
* MismatchedInputException
* StreamReadException (it will eventually replace JsonParseException)

There maybe others, but I haven't done an exhaustive search.

**Comment by geoand** [comment]
> While JsonProcessingException works for our case, it would probably be better to be surgical and catch the following

I think this is the safest thing to do. Would you like to contribute this fix?

**Comment by damonsutherland** [comment]
Sure

**Comment by damonsutherland** [comment]
Sorry, I’ve been on vacation. I am back today though. I will work on it this afternoon.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by geoand** [comment]
Thanks for the update!

**Comment by damonsutherland** [comment]
@geoand, I submitted the following PR (https://github.com/quarkusio/quarkus/pull/29548).

**Comment by damonsutherland** [comment]
@geoand, I wasn't happy with my work and I found a couple things I missed. Just letting you know I am still working on this and will issue a new PR in the next day or so. I will close/reject the current open PR.

**Comment by geoand** [comment]
That's perfectly fine, not a problem at all

**Comment by damonsutherland** [comment]
@geoand, my replacement PR has been linked above. 

Thanks again for all your help.
