### ISSUE TITLE
Async API  

### ISSUE THREAD

**Issue by fjtirado** [quarkusio/quarkus#29311]
### Description

This extension will define a set of java interfaces that allows accessing information hold by an AsyncAPI file  (An interface equivalent in functionality to [OpenAPI](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java)) 

As part of its deployment part, this extension will parse a set AsyncAPI file and generates:

- A quarkus config source containing smallrye channel configuration
- A Java implementation of the AsyncAPI mentioned before

The idea is that async API files does not need to be parsed again during runtime by the application code. 

### Repository name

quarkus-asyncapi-metaconfig

### Short description

Async api quarkus configuration and metadata generator 

### Repository Homepage URL

https://www.asyncapi.com/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- fjtirado
- ricardozanini

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

### Additional context

We are going to use this generator for Kogito, but we feel is generic enough to be delivered as extension

**Comment by gastaldi** [comment]
I think it makes sense to name it `quarkus-asyncapi`, and separate into Maven modules if necessary, WDYT?

**Comment by fjtirado** [comment]
> FTR there is a project in SmallRye: https://github.com/smallrye/smallrye-async-api/

Ill take a deeper look, since the purpose of this one is unclear to me

**Comment by fjtirado** [comment]
> I think it makes sense to name it `quarkus-async-api`, and separate into Maven modules if necessary, WDYT?

I would create one quarkus-async-api foled and under it quarkus-async-api-config-generator and quarkus-async-api-metadata, wdyt?

**Comment by gastaldi** [comment]
You can skip the `quarkus-async-api` prefix in the subfolders' names (while keeping it in the artifactId)

**Comment by gastaldi** [comment]
Actually I think `quarkus-asyncapi` makes more sense, I'll create the repository now
