### ISSUE TITLE
Camel component gets created twices if using CDI

### ISSUE THREAD

**Issue by kjozsa** [quarkusio/quarkus#29328]
### Describe the bug

When using the Camel Quarkus extension, if a Camel component is also marked with a CDI annotation, it gets created twice.

```
@ApplicationScoped
class FirstRoutes : RouteBuilder() {

    init {
        println("@@@@@@@@ init routes")
    }

    override fun configure() {
        println("### setting up routes")

        from("timer:first?period=5s")
            .log("boo")
    }
}
```

the initialization messages is shown twice. If I remove `@ApplicationScoped` then the class only gets instantiated once. 

### Output of `uname -a` or `ver`

Linux manta 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+1) OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

### Quarkus version or git rev

2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnd 0.8.2 linux-amd64 native client (2bba2d6a4d3a5012ddf9f1f42a22784cad4011e3) Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /usr/share/java/mvnd/mvn Java version: 17.0.5, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.0.8-arch1-1", arch: "amd64", family: "unix"

**Comment by mkouba** [comment]
In fact, the component itself is not created twice but CDI injects a [client proxy](https://quarkus.io/guides/cdi#client_proxies) for each normal scoped bean and a client proxy is created via a no-args constructor of a bean; and `@ApplicationScoped` is a normal scope. That's the reason why you see the kotlin initializer block called twice (because it's placed in the class constructror; no-args constructor in this particular case). Note that in CDI an idiomatic way to initialize a bean is to use a [`@PostConstruct` callback](https://quarkus.io/guides/cdi#lifecycle-callbacks).

**Comment by kjozsa** [comment]
Thanks @mkouba, it makes sense, and I do agree on the `@PostConstruct` part too. The part I don't see is that why this client proxy is only causing this in case the CDI-enabled component is a Camel one. Anyway, it might be worth to note this somewhere in the Camel extension's documentation because it's a bit counter-intuitive, and at the first glance it really looks like a trivial bug.

**Comment by manovotn** [comment]
> The part I don't see is that why this client proxy is only causing this in case the CDI-enabled component is a Camel one. 

The behavior @mkouba  explained will happen with any bean that needs a proxy (any normal scoped bean); it has nothing to do with Camel.

**Comment by kjozsa** [comment]
Thanks for the explanation, much appreciated.
