### ISSUE TITLE
Reactive - Support multi hosts connection to Postgres

### ISSUE THREAD

**Issue by mcanzerini** [quarkusio/quarkus#29348]
### Description

I need to connect to multiple postgres hosts with hibernate-reactive.

With the classic jdbc driver, we can define this property to connect to our HA postgres instance:

`quarkus.datasource.jdbc.url=jdbc:postgresql://my.host-1.com,my.host-2.com,my.host-3.com:5432/myDB`

But [here](https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L42) I saw that the vert.x PgClient does not support multi host connections directly in connection URI.

I created an issue in vertx-sql-client [here](https://github.com/eclipse-vertx/vertx-sql-client/issues/1250) and a developer said me that it would be already possible by using the PgConnectOptions and a PgPool.

Can you support connection pool to multi hosts through your implementation ?

**Comment by tsegismont** [comment]
@geoand do you know if it is possible to customize connect options in user code?

@mcanzerini as a workaroud, you create the PgPool directly in your application (with your own config options)

**Comment by geoand** [comment]
> @geoand do you know if it is possible to customize connect options in user code?

If you are looking for a way to customize the `PgConnectOptions` that Quarkus creates, then no. But I do think it would be something useful.

**Comment by tsegismont** [comment]
Are there some extensions which do something similar and which I could
inspire from?

**Comment by geoand** [comment]
None of the datasource extensions do this IIRC.

I'll open a draft tomorrow to show you what I have in mind (which is in line with the way other extensions like Jackson for example handle such cases)

**Comment by tsegismont** [comment]
Cool, thanks

**Comment by geoand** [comment]
> you create the PgPool directly in your application (with your own config options)

If you do this, make sure to make the `PgPool` a bean in order to override the Quarkus provided bean.

**Comment by geoand** [comment]
@tsegismont https://github.com/quarkusio/quarkus/pull/29397 is what I have in mind (cc @gsmet for awareness as well)

**Comment by geoand** [comment]
Hopefully soon :)

**Comment by mcanzerini** [comment]
Great, thanks for your time 🙏
