### ISSUE TITLE
Add support for web-app type OIDC applications to forward specified query params to the OIDC provider 

### ISSUE THREAD

**Issue by viswatejan** [quarkusio/quarkus#29345]
### Description

Many OIDC Identity providers use the `login_hint` query param to auto-fill the username/email on the login page. 

In addition to that, Keycloak uses `kc_idp_hint` to force authentication with a specific configured identity provider like google, facebook, etc. And also Keycloak JS adapter supports forwarding kc_idp_hint and login_hint from the app URL to the identity provider authorization code flow URL.

It will be good to have the configuration support in the `quarkus-oidc` extension to specify wchich query params in the application URL need to be forwarded to the identity provider's tion code flow URL. 

> **Example:**
*Application URL:*
https://my-app.com?kc_idp_hint=google
*Authorization code flow URL:*
https://my-identity-provider.com/auth/realms/my-realm/protocol/openid-connect/auth?client_id=my-client&redirect_uri=https://my-app.com&kc_idp_hint=google&state=d98e6908-4259-4cfa-9867-95c40cafdb8f&response_mode=fragment&response_type=code&scope=openid&nonce=ba330033-61c0-4c21-90e4-ff25387cb339

### Implementation ideas

Currently `quarkus-oidc` supports passing extra query params in the authorization code flow URL by specifying them in the `quarkus.oidc.authentication.extra-params` property but they are static query params with values and the values cannot be changed at the runtime from the application URL. 

It will be nice if we have a property `quarkus.oidc.authentication.forward-params` which takes an array of query param names that can be forwarded from the application URL to the authorization code flow URL.

**Comment by sberyozkin** [comment]
Makes sense
