### ISSUE TITLE
sqs dev services not respecting quarkus.sqs.devservices.service-name

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#29363]
### Describe the bug

I set quarkus.sqs.devservices.service-name for a profile like

```
%localstack.quarkus.sqs.devservices.enabled=true
%localstack.quarkus.sqs.devservices.shared=true
%localstack.quarkus.sqs.devservices.service-name=localSQS
```

as documented in
https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-sqs.html#_provision_sqs_locally_via_dev_services

I start quarkus application with quarkus profile 'localstack'

There is no container created with name 'localSQS'

### Expected behavior

container created with name 'localSQS'

### Actual behavior

![image](https://user-images.githubusercontent.com/845093/202849121-4b584ad0-8dd7-4a0f-95c5-b75d5f22a081.png)

### How to Reproduce?

https://github.com/syr/sqs-otel-quartz/tree/sqs-devservices-bug

**Comment by geoand** [comment]
This issue should opened in https://github.com/quarkiverse/quarkus-amazon-services as SQS related code is no longer part of the core repo
