### ISSUE TITLE
OpenTelemetry: 'Failed to export spans' of ignored endpoints, on Kubernetes if otel-collector container starts after Quarkus container

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#29374]
### Describe the bug

I have a Quarkus 2.14.1 service running on Kubernetes in a pod with an otel-collector. The Quarkus service connects to this otel-collector correctly.

In some cases, the otel-collector container may start after the Quarkus container has started. Every time Kubernetes probes Quarkus at `q/health/live` and `q/health/ready`, Quarkus tries to export spans to the otel-collector, despite `q/` endpoints being ignored (see [Quarkus doc](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.opentelemetry.tracer.suppress-non-application-uris), we have not changed the default `true` setting, or provide any custom samplers, and we do not see traces for these endpoints in Jaeger, suggesting that it does work), resulting in the following error:

```
SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) {} Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317
```

After the otel-collector starts, the issue resolves itself.

As a workaround, we have to use a startUp probe on the service container that waits for the otel-collector container to have started, to prevent health check calls on the service container producing the error.

### Expected behavior

No `Failed to export spans` error messages when calls to ignored `q/` are made.

### Actual behavior

```
SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) {} Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317
```

is logged when calls to `q/health/live` and `q/health/ready` are made when otel-collector has yet to start.

### How to Reproduce?

Using Quarkus 2.14.1 with dependencies:

```
'io.quarkus:quarkus-opentelemetry'
'io.opentelemetry.instrumentation:opentelemetry-jdbc'
'io.quarkus:quarkus-smallrye-health'
```

and configuration

```
quarkus.opentelemetry.propagators=tracecontext,baggage,jaeger
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://localhost:4317
```

1. Start the Quarkus service. Do _not_  start an otel-collector on localhost:4317, simulating that an otel-collector container has not yet started.
2. Call `q/health/live` and `q/health/ready`
3. Observe the following log statement: `SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) {} Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2130]

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10) OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

### Quarkus version or git rev

2.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.2 ------------------------------------------------------------  Build time:   2021-08-17 09:59:03 UTC Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad  Kotlin:       1.5.21 Groovy:       3.0.8 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.15 (Eclipse Adoptium 11.0.15+10) OS:           Windows 10 10.0 amd64

**Comment by brunobat** [comment]
I Tried to reproduce this using Smallrye HealhCheck and I could't reproduce the issue.
Filtered spans will not trigger span export.
However, if even one non existing endpoint is called, this will kick the export. 
Also... Could this be related with DB calls that are done inside a health check?

**Comment by AndreasPetersen** [comment]
You could be right, we have a connection to a database

**Comment by AndreasPetersen** [comment]
This reproduces the issue https://github.com/AndreasPetersen/quarkus-issue-29374

**Comment by brunobat** [comment]
@AndreasPetersen I couldn't reproduce the issue with your reproducer:
The severe line will not show. Please mind you need Entities in oder to launch the entity manager.
<img width="1512" alt="Screenshot 2022-11-21 at 14 21 59" src="https://user-images.githubusercontent.com/2318030/203078909-9f508c24-6dc4-47b4-a3ad-cfafcf1b6e34.png">

**Comment by AndreasPetersen** [comment]
Very strange. It was able to reproduce the issue on my end, but now it does not. I'll investigate further.

**Comment by AndreasPetersen** [comment]
Just a side observation, /q/dev does seem to trigger the issue at least

**Comment by AndreasPetersen** [comment]
Okay, I'm able to reproduce it again now.

![image](https://user-images.githubusercontent.com/2496648/203097294-f4ec5bee-bca9-47f5-8590-2e7f43622c99.png)

(The changes to the files in the screenshot is just some proxy settings to get through my company proxy)

The trick is to ctrl+F5 in the browser (I've tried on both Brave and Chrome). I noticed that if I just make a simple curl request

```
curl http://localhost:8080/q/health/ready
```

Then the error does not appear. If I, however, copy the curl request from the Chrome DevTools,

```
curl 'http://localhost:8080/q/health/ready' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: Idea-d65f5f69=08480bca-b4ad-40c9-857e-6492d0836ccc' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-GPC: 1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  --compressed ;
curl 'chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content.min.css' \
  -H 'Referer: http://localhost:8080/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  --compressed ;
curl 'http://localhost:8080/favicon.ico' \
  -H 'Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: Idea-d65f5f69=08480bca-b4ad-40c9-857e-6492d0836ccc' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:8080/q/health/ready' \
  -H 'Sec-Fetch-Dest: image' \
  -H 'Sec-Fetch-Mode: no-cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-GPC: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  --compressed
```

Then the issue appears.

**Comment by brunobat** [comment]
Because the span is related with `curl 'http://localhost:8080/favicon.ico'` Not the Healthcheck.

**Comment by AndreasPetersen** [comment]
You're right. I just put the example service up on a Kubernetes cluster with the following probes:

```
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: container-port
    initialDelaySeconds: 60
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: container-port
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 7
    failureThreshold: 7
```

without a otel-collector container (to simulate it not having started yet). Every 30 seconds I'm getting the error.

**Comment by AndreasPetersen** [comment]
I had prometheus scraping for metrics:

```
      annotations:
        prometheus.io/path: /q/metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
```

Disabling that, the service not longer produces the error. I guess this is what is causing the issue, though I wouldn't think prometheus would be able to scrape on a pod, where all containers are not yet ready?

Anyway, I tried adding a 

```
@ApplicationScoped
@PermitAll
@Path("/q/metrics")
public class MetricsEndpoint {

    @GET
    public void metrics() {

    }
}
```

to the service (we expose a custom metrics endpoint like this in our service, we don't use the micrometer extension), and when I call that endpoint

```
curl http://localhost:8080/q/metrics
```

running the service locally, the error appears. Shouldn't /q/metrics be ignored?

**Comment by brunobat** [comment]
@AndreasPetersen We filter out URLs from frameworks... You created a user endpoint. Has the same path but we know it's yours. 
I think this is issue is not a bug.

**Comment by AndreasPetersen** [comment]
The issue does not appear when using the micrometer extension `/q/metrics` endpoint. We'll be looking into filtering our user endpoint then. Thanks for the help, and apologies for the confusion.

**Comment by brunobat** [comment]
No worries at all. Your question will certainly help someone else. 
Thanks for contributing!

**Comment by geoand** [comment]
Should this be closed or is there still something we need to do?

**Comment by brunobat** [comment]
yes
