### ISSUE TITLE
Quarkus picocli -V default.

### ISSUE THREAD

**Issue by jyterrien** [quarkusio/quarkus#29379]
### Description

Hi,

Quarkus-picocli extension
When running the command with the -V option
It is not possible to display the version of the Quarkus application.

Indeed the version of the Picocli command is defined in the annotation
```java
@Command(name = "run", mixinStandardHelpOptions = true, exitCodeOnSuccess = 0, version = ...)
```
Or with versionProvider which must be a class.
However in Quarkus the name and the version of the application are only available by injection.
```java
    @ConfigProperty(name = "quarkus.application.name")
    String app;

    @ConfigProperty(name = "quarkus.application.version")
    String version;
```
This information is available in the extension during compilation.
Wouldn't it be possible when "version" and "versionProvider" members are not provided, to inject at compile time a versionProfider that provides the appName and appVersion
of the quarkus app?

**Comment by jyterrien** [comment]
```java
public class QuarkusVersionProvider implements IVersionProvider
{

   @Override
   public String[] getVersion() throws Exception{
      Config cf = ConfigProvider.getConfig(getClass().getClassLoader());
      String[] versions =
         {cf.getValue("quarkus.application.name", String.class), cf.getValue("quarkus.application.version", String.class)};
      return versions;
   }

}
```

**Comment by maxandersen** [comment]
An more typesafe alternative is:

```java
@Unremovable @Singleton
public class VersionProvider implements IVersionProvider {

    @ConfigProperty(name = "quarkus.application.version")
    String version;

    @Override
    public String[] getVersion() throws Exception {
        return new String[] { version };
    }
}
```

That will also work.

Its annoying having to specify @Unremovable, but I suggest we close this issue and replace it with the improvement that handles unremovable for types known by picocli: #38077
