### ISSUE TITLE
[Extension Proposal] Pretty Time NLP

### ISSUE THREAD

**Issue by joes** [quarkusio/quarkus#29404]
### Description

PrettyTime :: NLP is an OpenSource, Java Library – enabling simple parsing and computer understanding of natural language, and social date references like, “let’s go to dinner at 6,” or “I’ll be on vacation for three days”.

This extension would allow you to use this library in Quarkus native applications.

The extension provides a singleton `org.ocpsoft.prettytime.PrettyTimeParser` in the same fashion as https://github.com/quarkiverse/quarkus-prettytime provides a singleton `org.ocpsoft.prettytime.PrettyTime`.

The extension is already implemented here: https://github.com/joes/quarkus-prettytime-nlp

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-prettytime-nlp

### Short description

Quarkus extension providing org.ocpsoft.prettytime.PrettyTimeParser for parsing and computer understanding of natural language, and social date references

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-prettytime-nlp/dev/

### Repository Topics

- quarkus-extension
- date
- nlp
- social-date-reference

### Team Members

- @joes

### GitHub Applications?

- [X] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by gastaldi** [comment]
@joes I prefer having this extension as another module in https://github.com/quarkiverse/quarkus-prettytime

**Comment by joes** [comment]
I could make a pull request which introduces `prettytime-nlp` to https://github.com/quarkiverse/quarkus-prettytime if that is desirable @gastaldi.

But I need to understand what exactly do you mean with ”another module”. Another maven submodule (another pair of deployment and runtime)? Or do you mean to add a new `AdditionalBeanBuildItem` into `PrettyTimeProcessor`?

**Comment by gastaldi** [comment]
I mean another Maven submodule with another pair of deployment and runtime, like https://github.com/quarkiverse/quarkus-micrometer-registry

**Comment by gastaldi** [comment]
I'm closing this issue as this should be implemented as a new extension in https://github.com/quarkiverse/quarkus-prettytime
