### ISSUE TITLE
Recent change introduced warnings while building native image of MongoDB Client (and possibly others)

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#29413]
### Describe the bug

With a recent change native compilation of the MongoDB Client integration test results in warnings.

See https://github.com/quarkusio/quarkus/actions/runs/3523161137/jobs/5909184730#step:12:380

### Expected behavior

No warnings should be printed.

### Actual behavior

```
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.protobuf.ProtobufDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite.
```

### How to Reproduce?

1. `git clone git@github.com:quarkusio/quarkus.git`
2. `cd quarkus`
3. `./mvnw -Dquickly -T2`
4. 
```
./mvnw -e --settings .github/mvn-settings.xml --fail-at-end \
    -f integration-tests -pl mongodb-client \
    -Dtest-containers -Dstart-containers \
    -Dquarkus.native.native-image-xmx=5g -Dnative \
    -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests \
    clean install -DskipDocs \
    -Dquarkus.native.container-build=true
```

### Quarkus version or git rev

e67b1333eb51512e031c225c291a50628bc2b23d

**Comment by geoand** [comment]
When did this start, do you know?

**Comment by geoand** [comment]
Is it GraalVM that is printing this warning?

**Comment by zakkak** [comment]
> When did this start, do you know?

I did not bisect but based on the CI runs it appears to be between a2e7f7e8502b0e730083a301892e5a26251393c7 and 93b08464f0a6abe5aaa19744d4aad9c04a925d16

> Is it GraalVM that is printing this warning?

Correct, see https://github.com/oracle/graal/blob/829e49f551f44835f7b81ec9e28ae92bd220bc9e/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ReflectionConfigurationParser.java#L181

**Comment by jerboaa** [comment]
Is somebody looking into this or should we allow-list those warnings for now? This is creating unnecessary noise in CI.

**Comment by zakkak** [comment]
I'll take a look.

**Comment by zakkak** [comment]
So the issue appears to be that with `4.1.85` GraalVM finds the reflection configurations shipped with netty and it tries to load the following classes and register them for reflection:

* `io.netty.handler.codec.compression.Lz4FrameDecoder`
* `io.netty.handler.codec.compression.Lz4FrameEncoder`
* `io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder`
* `io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder`
* `io.netty.handler.codec.marshalling.MarshallingDecoder`
* `io.netty.handler.codec.marshalling.MarshallingEncoder`
* `io.netty.handler.codec.protobuf.ProtobufDecoder`

These classes however reference the following classes that are not on the classpath:

* `net/jpountz/lz4/LZ4Exception`
* `org/jboss/marshalling/ByteInpu`
* `org/jboss/marshalling/ByteOutput`
* `com/google/protobuf/ExtensionRegistryLite`

The solutions I see are the following:

1. Include the necessary dependencies in the classpath.
2. Don't load the reflection configuration from netty (@Sanne I think you are the one who know how to achieve this, do we do it for any other extension?).

I suggest going for 2 since we have had no issues so far with our own configuration, although it might be worth inheriting upstream project configurations at some point.

Unfortunately substitutions are of no help here (since the class loading happens before they are applied and the classes are explicitly loaded).

**Comment by geoand** [comment]
For `2`, I assume you mean `ExcludeConfigBuildItem`?

**Comment by Sanne** [comment]
Yes I'd agree with using `ExcludeConfigBuildItem` ; @zakkak see an example here: https://github.com/quarkusio/quarkus/blob/23f43c3d3be6f479f86f697888856a8c65d8136d/extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java#L110-L117

 needs a bit of fiddling with Regexp :/ And careful, I had to iterate on the current regex as the regex needs to be passed as command line, not all symbols are valid on Windows so it's a bit tricky.

**Comment by Sanne** [comment]
For my sanity I even used unit tests on the constants to be used:

https://github.com/quarkusio/quarkus/blob/23f43c3d3be6f479f86f697888856a8c65d8136d/extensions/jdbc/jdbc-oracle/deployment/src/test/java/io/quarkus/jdbc/oracle/deployment/RegexMatchTest.java#L18
