### ISSUE TITLE
Quarkus project update tool

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#29410]
### Description

Following on https://github.com/quarkusio/quarkus/issues/29000

- [x] Create a "Quarkus project update" repo and find a structure (streams, platforms, extensions)
- [x] Find a way to plug the CLI update command to this repository

**Comment by ia3andy** [comment]
cc @quarkusio/devtools

**Comment by geoand** [comment]
Has this been completed?

**Comment by gsmet** [comment]
Yes, we can close it!

**Comment by geoand** [comment]
👍
