### ISSUE TITLE
DOCKER_HOST-strategy in class isDockerWorking.java excludes expected "unix:"-path where it should include "unix:" - broken.

### ISSUE THREAD

**Issue by janderssonse** [quarkusio/quarkus#29426]
### Describe the bug

In the file
IsDockerWorking.java.
line 129 -see https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L129

 the check for the DOCKER_HOST-variable is negatated. However, setting the DOCKER_HOST variable to a unix socket usually involves a path like "unix:\\\the\path\to\socket". This is also clearly mentioned and recommened in your documentation -> https://quarkus.io/guides/podman#setting-docker_host-on-linux. The negation should most likely be removed so that the logic it now hides can run correctly (connection to the "unix:" socket in the DOCKER_HOST-env.

### Expected behavior

It should find a DOCKER_HOST-path (according to practices, according to your documentation linked in descrioption starting with unix:\\\the-path-to-the-socket. 

### Actual behavior

It instead excludes DOCKER_HOST paths starting with "unix:" due to starting with neg !.

### How to Reproduce?

Set a DOCKER_HOST starting with "unix:\\" for example as per docu, qurkus will fail finding it and connecting to it . https://quarkus.io/guides/podman#setting-docker_host-on-linux

### Output of `java -version`

17

### Quarkus version or git rev

2.13.4

**Comment by geoand** [comment]
@Sanne you seem to have added the `!dockerHost.startsWith("unix:")` check in 7dc74758 to make Podman work.
Do you know if it's still needed?

**Comment by janderssonse** [comment]
@geoand If the logic is correct then the documentation is wrong - It says to set this as 

> export DOCKER_HOST=unix:///run/user/${UID}/podman/podman.sock
https://quarkus.io/guides/podman#setting-docker_host-on-linux which makes perfectly sense. I would in practice still argue that it is the 
> !dockerHost.startsWith("unix:")
that should not have an !

**Comment by geoand** [comment]
I'll let @Sanne comment as I have never used podman

**Comment by janderssonse** [comment]
> I'll let @Sanne comment as I have never used podman

Thanks, note though that one does not have to run Podman though to see that the documentation line refered and the condition logic contradicts each other.

**Comment by geoand** [comment]
I agree, I just don't know which one is wrong :)

**Comment by geoand** [comment]
That would be great, thanks

**Comment by janderssonse** [comment]
Thanks @Sanne . Heads up, Another note is that the current documentation example mentioned above for setting DOCKER_HOST is also pointing to a podman socket path that might differs on different setups of linuxes. To see which is the correct path see 

` podman info | grep -A2 'remote'`

and you should get roughly like 
![bild](https://user-images.githubusercontent.com/37870813/203593262-36996ced-2675-404f-91c1-8df62e1ad548.png)

back which shows the correct podman socket path  - ie set DOCKER_HOST=unix://THE_ABOVE_PATH.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/29562 to take care of this.
