### ISSUE TITLE
DevUI - config editor doesn't notify user when something goes wrong

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29422]
### Describe the bug

DevUI - config editor doesn't notify user when something goes wrong

When the value gets updated there is "Configuration update successful" window in the top right corner.

But when things do not get updated, the is no notification to the end used
One needs to open console of web browser to see something like 403 Forbidden.

Users need to be informed when their config changes do not get updated.

### Expected behavior

Users are informed when their config changes through DevUI config editor do not get updated.

### Actual behavior

One needs to open console of web browser to see something like 403 Forbidden.

### How to Reproduce?

 - Use Quarkus main + #29342
 - pick an app, use 999-SNAPSHOT, configure `quarkus.http.host=0.0.0.0`
 - open DevUI on another machine, point the browser to the instance running on the first machine
 - update anything under `/q/dev/io.quarkus.quarkus-vertx-http/config`

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main + #29342

**Comment by rsvoboda** [comment]
CC @maxandersen / @gsmet / @geoand

**Comment by geoand** [comment]
cc @radcortez @phillip-kruger

**Comment by phillip-kruger** [comment]
@rsvoboda - is this also the case with the new Dev UI ?

**Comment by rsvoboda** [comment]
I will check it later today or tmr.

**Comment by rsvoboda** [comment]
The old dev ui has the same same behaviour as described here - 403 with CORS rejected message in the console log.
`2023-05-24 14:17:58,277 ERROR [io.qua.ver.htt.run.dev.DevConsoleCORSFilter] (vert.x-eventloop-thread-1) Only localhost origin is allowed, but Origin header value is: http://10.20.30.189:8080`

The new / default dev UI is able to modify properties from the other machine without troubles.
And that behaviour (changes were done) is a bit strange to me tbh, I thought only localhost is allowed when cors on dev-ui is enabled. CC @sberyozkin 

And docs do not say much about CORS on dev ui :/

Tested with Quarkus main 071a89c3b8.

**Comment by phillip-kruger** [comment]
The new dev ui use a Web socket connection, that might be why ?
