### ISSUE TITLE
DevUI - config editor doesn't work well over https, UI doesn't get updated

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29431]
### Describe the bug

DevUI - config editor doesn't work well over https, the value gets updated in `application.properties` but the UI gets grey for the updated entry and new value is not reflected.

Browser console shows `GET http://localhost/q/dev/io.quarkus.quarkus-vertx-http/config net::ERR_CONNECTION_REFUSED` when I access I https://localhost:8443/q/dev/io.quarkus.quarkus-vertx-http/config and update something

As if the Dev UI counts only with port 8080 / `quarkus.http.port`.

<img width="1649" alt="Screenshot 2022-11-23 at 8 33 58" src="https://user-images.githubusercontent.com/925259/203493579-b6a5be5a-4f42-4311-aeaa-092a38fd5cdd.png">

CC @radcortez @phillip-kruger @geoand

### Expected behavior

UI gets updated, no `net::ERR_CONNECTION_REFUSED`

### Actual behavior

UI doesn't get updated

### How to Reproduce?

 - Use any Quarkus 2.14.1.Final application
 - Enable https - `quarkus.http.ssl.certificate.key-store-file` and `quarkus.http.ssl.certificate.key-store-password`
 - Access https://localhost:8443/q/dev/io.quarkus.quarkus-vertx-http/config
 - Open browser console - righ-click - Inspect - Console tab
 - Edit any value and hit Enter of click ✅

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.14.1.Final, 2.13.4.Final

**Comment by rsvoboda** [comment]
Reproducer app - https://github.com/rsvoboda/code-with-quarkus

`quarkus.datasource.password` added to have something simple for editing in https://localhost:8443/q/dev/io.quarkus.quarkus-vertx-http/config

**Comment by gsmet** [comment]
From what I can see, the problem is when `DevConsolePostHandler` tries to redirect.

`event.request().absoluteURI()` returns `http://localhost/q/dev/io.quarkus.quarkus-vertx-http/config` even in HTTPS, which is incorrect.

I worked around it here by using `uri()`, which IMHO is better anyway but I think we should still try to understand what's going on at the Vert.x level.

PR is here: https://github.com/quarkusio/quarkus/pull/29586

**Comment by rsvoboda** [comment]
Thanks @gsmet, tried the latest main and happy now. Should be  #29586 marked for backport(s) or you want to wait for proper fix?
