### ISSUE TITLE
Application startup  fails using Lombok's @NonNull on a method annotated with @ConsumeEvent

### ISSUE THREAD

**Issue by benjaminrau** [quarkusio/quarkus#29434]
### Describe the bug

When annotating a method parameter with @NonNull for a Vertx Consumer Method (means its annotated with @ConsumeEvent) then the application startup fails, throwing an exception.

Mentioned on: https://github.com/quarkusio/quarkus/discussions/29322

### Expected behavior

No exception is thrown when using @NonNull.

### Actual behavior

Exception is thrown when using @NonNull, application can not be started.

### How to Reproduce?

1. Clone the repo: https://github.com/benjaminrau/quarkus-nonnull-reproducer
2. Start the application

### Output of `uname -a` or `ver`

Linux br-builders-nb 5.14.0-1052-oem #59-Ubuntu SMP Fri Sep 9 09:37:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

>= 2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Noticable is that @NonNull is included in the ClassName for EventBusCodec registration too:
`2022-11-23 10:29:52,634 INFO  [io.qua.ver.dep.EventBusCodecProcessor] (build-5) Local Message Codec registered for type org.acme.@NonNull HelloEvent
`

**Comment by luca-bassoricci** [comment]
I had a vague memories about something similar
Found in [this]( https://github.com/quarkusio/quarkus/discussions/28406) discussion

**Comment by famod** [comment]
I'm under the impression that this has the same root cause as #29425. /cc @Ladicek

**Comment by Ladicek** [comment]
Okay, it is _not_ the same issue. Looks like someone uses `Type.toString()` to generate a class name, which is wrong. Let me check.

**Comment by Ladicek** [comment]
Found it: https://github.com/quarkusio/quarkus/blob/2.14.1.Final/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusCodecProcessor.java#L91

Here, `entry.getKey()` is a Jandex `Type`, so `entry.getKey().toString()` may include type annotations. Fix is simple: `entry.getKey().name().toString()`.

**Comment by benjaminrau** [comment]
Thanks a lot for your efforts! Quarkus is really awesome!
