### ISSUE TITLE
Allow incomplete classpaths by default

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2946]
**Description**
Add a configuration switch to allow incomplete class paths for native image; the default should be `true`.

As discussed on [the development list topic](https://groups.google.com/d/topic/quarkus-dev/Yx3Z00wFtXw/discussion).

**Comment by zakkak** [comment]
@gsmet @dmlloyd I feel like this Issue is now outdated. Judging by the discussions in https://github.com/oracle/graal/issues/2762 Quarkus is against enabling `--allow-incomplete-classpath` by default.

**Comment by gsmet** [comment]
Right.
