### ISSUE TITLE
Add support for HTTP operation retries (with exponential backoff) in Kubernetes Client

### ISSUE THREAD

**Issue by ManasMaji** [quarkusio/quarkus#29467]
### Description

Fabric8's Kubernetes client has exposed HTTP operation retry configuration options with exponential backoff since version 5.5.0 [0]:
* `kubernetes.request.retry.backoffLimit`
* `kubernetes.request.retry.backoffInterval`

Request Quarkus to add similar configurations in [KubernetesClientBuildConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/runtime-internal/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesClientBuildConfig.java) to support retries when the HTTP status code is 500 (Status Internal Server Error), 503 (Status Service Unavailable), or 504 (Status Server Timeout).

[0] https://developers.redhat.com/articles/2021/07/16/whats-new-fabric8-kubernetes-client-version-550

**Comment by geoand** [comment]
Good idea! https://github.com/quarkusio/quarkus/pull/29470 does just that

**Comment by ManasMaji** [comment]
Hi @geoand, thank you for adding the changes quickly! When can we expect this change to be released?

**Comment by geoand** [comment]
Hi,

They will be part of Quarkus 2.15, which should be released in a few weeks
