### ISSUE TITLE
Subclass type not marshalled in rest GET return type List<X>

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#29463]
### Describe the bug

Given rest endpoint:

```java
@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Parent> hello() {
        return List.of(new Parent.ChildA());
    }
}
```

and classes:

```java
@JsonPropertyOrder({ "type" })
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Parent.ChildA.class, name = ".ChildA"),
        @JsonSubTypes.Type(value = Parent.ChildB.class, name = ".ChildB") })
public abstract class Parent {
    
    public List<Shape> shapes = List.of(new Shape.Circle());
    
    @JsonTypeName(".ChildA")
    public static class ChildA extends Parent {
        public String attChildA = "valA";
    }

    @JsonTypeName(".ChildB")
    public static class ChildB extends Parent {
        public String attChildB = "valB";
    }
}
```

I expect the `type` attribute to be returned for the `Parent` subclass. e.g. `[{"type":".ChildA",...`
It does work however, on object lists, assuming they are not at the top level.
We checked on `EAP`, and we have the expected behavior (`type` attribute is always returned, regardless of the object list being at the top level or not).

### Expected behavior

We expect the endpoint to return: `[{"type":".ChildA","shapes":[{"type":".Circle","attChildA":"circle"}],"attChildA":"valA"}]`

### Actual behavior

`[{"shapes":[{"type":".Circle","attChildA":"circle"}],"attChildA":"valA"}]`

### How to Reproduce?

```
git clone https://github.com/vsevel/reproducer_rest_list_subclass
mvn clean package
```

### Output of `java -version`

17

### Quarkus version or git rev

2.14.1

**Comment by geoand** [comment]
This is **not** a Quarkus issue, but a Jackson issue.

This can be proven by running the following standard JUnit test:

```java
public class ObjectMapperTest {

    @Test
    public void doesNotWork() throws JsonProcessingException {
        String json = new ObjectMapper().writeValueAsString(List.of(new Parent.ChildA()));
        String expected = "[{\"type\":\".ChildA\",\"shapes\":[{\"type\":\".Circle\",\"attChildA\":\"circle\"}],\"attChildA\":\"valA\"}]";
        Assertions.assertEquals(expected, json);
    }

    @Test
    public void works() throws JsonProcessingException {
        String json = new ObjectMapper().writeValueAsString(new Parent.ChildA());
        String expected = "{\"type\":\".ChildA\",\"shapes\":[{\"type\":\".Circle\",\"attChildA\":\"circle\"}],\"attChildA\":\"valA\"}";
        Assertions.assertEquals(expected, json);
    }

    @JsonPropertyOrder({ "type" })
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = org.acme.Parent.ChildA.class, name = ".ChildA"),
            @JsonSubTypes.Type(value = org.acme.Parent.ChildB.class, name = ".ChildB") })
    public static abstract class Parent {

        public List<Shape.Circle> shapes = List.of(new Shape.Circle());

        @JsonTypeName(".ChildA")
        public static class ChildA extends org.acme.Parent {
            public String attChildA = "valA";
        }

        @JsonTypeName(".ChildB")
        public static class ChildB extends org.acme.Parent {
            public String attChildB = "valB";
        }
    }

    @JsonPropertyOrder({ "type" })
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = org.acme.Shape.Circle.class, name = ".Circle"),
            @JsonSubTypes.Type(value = org.acme.Shape.Square.class, name = ".Square") })
    public static abstract class Shape {
        @JsonTypeName(".Circle")
        public static class Circle extends org.acme.Shape {
            public String attChildA = "circle";
        }

        @JsonTypeName(".Square")
        public static class Square extends org.acme.Shape {
            public String attChildB = "square";
        }
    }

}
```

If you run it, you'll see that the first test fails while the second one works.


I propose opening an issue in Jackson Databind

**Comment by dmaio** [comment]
The sample endpoint provided as a sample by @vsevel works perfectly as expected in EAP6 and Wildfly 21.0.1 even though the unit tests gives a different result.
As stated here: https://github.com/FasterXML/jackson-databind/issues/3656#issuecomment-1309497539 Jackson-databind never supported this. 
As this case works at endpoint level, compared to EAP and Wildfly it can be seen as a regression.

**Comment by geoand** [comment]
I understand that it worked in EAP, but Quarkus is not EAP, so this definitely cannot be characterized as a regression.

Moreover, the workaround where we would need to use a TypeReference introduces extra logic and a performance cost in order to cater to this very subtle case, so I don't see it as a good tradeoff.

**Comment by vsevel** [comment]
@geoand  I agree it is not a regression per se, since we are talking about 2 different products. but it will be felt that way, since quarkus is a new stack in the continuation of jboss, and it is a major selling point for quarkus that there is a migration path from eap. I call this disruptive continuity ;-)
people will have some expectations to find in quarkus what was working well in eap. and in that case it feels it works better in eap, than in quarkus. if I had to guess I would say that it did not work initially in eap, and somebody provided a feedback that led the product to evolve to support this use case.
I sympathize with the judgment call and the benefit/inconvenient ratio. and you may be correct this might not be worth it in that particular case (although we spent quite a bit of time with @dmaio on trying to understand that one, so we did feel the inconvenience as well), but there is a clear path between jboss and quarkus, and with it natural expectations that things that make sense and work well in eap should work just as well in quarkus.

**Comment by geoand** [comment]
I totally sympathize, but this is such an edge case, that I don't really see it making a tremendous amount of sense both development wise and performance wise in handling it.
