### ISSUE TITLE
Duplicated Context in StartupEvent Observers

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#29466]
### Description

In #28017 the scheduler was changed so that scheduled methods run in the context of a duplicated context. Now I have encountered similar problems in the context of a `StartupEvent` observer. I am thus wondering whether it would again make sense to change Quarkus, so that a duplicated context (and thus context locals) are available.

**Comment by cescoffier** [comment]
@mkouba I think we discussed it at some point, but I can't remember the outcome.

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/issues/27623 and https://github.com/quarkusio/quarkus/issues/27854 are related. I think that we should introduce some way (annotation?) to [wrap the notification like this](https://github.com/quarkusio/quarkus/issues/27854#issuecomment-1245026347).

**Comment by cescoffier** [comment]
@mkouba fancy to propose the feature?

**Comment by mkouba** [comment]
> @mkouba fancy to propose the feature?

I'm still not sure how this should/could work. One of the questions is: do we want to execute the logic asynchronously, i.e. not necessarily during the startup sequence? Otherwise, we'd have to block and wait (and this should be fine in the context of `StartupEvent`).

**Comment by cescoffier** [comment]
That's what I would have done: call all the observers and join them before going further. 

Maybe instead of join, it might be easier to invoke them sequentially.

**Comment by mkouba** [comment]
In theory, we could support this for any observer. I.e. something along the lines of: an observer method annotated with `@NonBlocking` is executed on the event loop (vertx duplicated context more precisely). OTOH it might be a bit confusing. 

@manovotn @Ladicek WDYT?

**Comment by Ladicek** [comment]
I've got this feeling that you would need the observer method to return a `Uni` (or a `CompletionStage`), so that the observer can actually _do_ something non-blocking. At which point, this looks dangerously close to #29191.

**Comment by mkouba** [comment]
> I've got this feeling that you would need the observer method to return a `Uni` (or a `CompletionStage`), so that the observer can actually _do_ something non-blocking. At which point, this looks dangerously close to #29191.

Not really. This is mostly about executing the observer method on the event loop; not about asynchronous invocation or participating in a reactive stream. In other words, a user just needs to execute the observer method on the event loop but block the current thread (and wait for the result).

```java
   void onStart(@Observes StartupEvent event, Vertx vertx, Mutiny.SessionFactory factory) {
        Context context = VertxContext.getOrCreateDuplicatedContext(vertx);
        VertxContextSafetyToggle.setContextSafe(context, true);
        CompletableFuture<Void> fu = new CompletableFuture<>();
        context.runOnContext(new Handler<Void>() {
            @Override
            public void handle(Void event) {
                // do something with the session factory
               fu.complete(null); 
            }
        });
       fu.get(); // wait for the result
    }
```

Could be replaced with something like:

```java
   @NonBlocking
   void onStart(@Observes StartupEvent event, Mutiny.SessionFactory factory) {
      // do something with the session factory
   }
```

**Comment by Ladicek** [comment]
It actually can't be replaced the way you mention without significantly limiting what the observer method can do. In particular, it cannot start any asynchronous action, because there's no way to signal its completion.

**Comment by mkouba** [comment]
> In particular, it cannot start any asynchronous action, because there's no way to signal its completion.

Why? You can just subscribe to the `Uni` returned from the session factory for example...

**Comment by mkouba** [comment]
OTOH I agree that returning `Uni` or `CompletionStage` from the observer method would be more convenient. And that's what you can do with a `@Scheduled` method by the way.

**Comment by Ladicek** [comment]
You can subscribe to the `Uni`, but you can't wait for it to complete (as you're on the event loop) and you can't return it so that the original thread waits for it. So you can do "fire and forget" kind of thing, yes. I don't think that's good, as you lose the ability to rely on startup tasks being finished when the application finishes startup, but you're right that it's possible.

**Comment by mkouba** [comment]
> You can subscribe to the `Uni`, but you can't wait for it to complete (as you're on the event loop) and you can't return it so that the original thread waits for it. So you can do "fire and forget" kind of thing, yes. I don't think that's good, as you lose the ability to rely on startup tasks being finished when the application finishes startup, but you're right that it's possible.

You're right.

**Comment by mkouba** [comment]
So it seems that the only reasonable thing we could do is:

1. Require such an observer to return an async type; which goes against https://github.com/jakartaee/cdi/issues/636
2. Provide a util method to wrap the execution; which is not very convenient

```java
public class VertxContexts {
   public static void runOnVertxContext(Supplier<Uni<Void>> uniSupplier) {
     Vertx vertx = lookupVertx();
     Context context = VertxContext.getOrCreateDuplicatedContext(vertx);
     VertxContextSafetyToggle.setContextSafe(context, true);
     CompletableFuture<Void> fu = new CompletableFuture<>();
     context.runOnContext(new Handler<Void>() {
         @Override
         public void handle(Void event) {
             uniSupplier.get().subscribe().with(i -> fu.complete(null), e -> fu.completeExceptionally(e))
         }
     });
    fu.get();
   }
}
```

and then:

```java
void onStart(@Observes StartupEvent event, Mutiny.SessionFactory factory) {
   VertxContexts.runOnVertxContext(() -> {
      // do something with the session factory and return Uni<Void>
   });
}
```

Am I missing something?

**Comment by Ladicek** [comment]
I think the 2nd option is sensible in the short term.

Longer term, I think we could add support for async observers returning `Uni` (or `CompletionStage`), but this use case would require firing the startup event asynchronously (in addition to synchronously), which is probably a more interesting topic...

**Comment by mkouba** [comment]
> I think the 2nd option is sensible in the short term.

Ok, I'll try to prepare something...
