### ISSUE TITLE
Quarkus Panache reactive caching entities

### ISSUE THREAD

**Issue by silviu-negoita** [quarkusio/quarkus#29526]
### Describe the bug

I'm having an issue when running update query from Panache reactive. Apparently my entities are cached and never updated. 

Operations:
1. Persist test data 
2. Select - fetch query to assert the old value are present 
4. Do a PanacheEntity.update()
5. Do another fetch to assert the new values are correctly set  - this fails, the old value are still in place in my JPAs, despite the fact that DB is correctly updated. 

In non reactive, I usually inject EntityManager and manually refresh entities. In reactive I only have `Mutiny.SessionFactory` but didn't figured out how to proper use it to force my entity to refresh and get the new values from DB. 

My workaround is to fetch JPA entities and set the new value instead of running `update` query(can be found in reproducer). It works, but this is very inefficient. 

Any help would be appreciated.  

### How to Reproduce?

Please follow the reproducer README file.

I started from official `hibernate-reactive-panache-quickstart`. 
[hibernate-reactive-panache-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/10102638/hibernate-reactive-panache-quickstart.tar.gz)

### Quarkus version or git rev

`2.14.1.Final`

**Comment by geoand** [comment]
Using Hibernate Reactive Panache inside tests won't work really well. Can you update your code and try using the API shown [here](https://github.com/quarkusio/quarkus-super-heroes/blob/85385441cae896a9bc7527fb79351f5c9c9cc2fb/rest-heroes/src/test/java/io/quarkus/sample/superheroes/hero/repository/HeroRepositoryTests.java#L30)?

**Comment by silviu-negoita** [comment]
@geoand it is ok now?
[hibernate-reactive-panache-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/10104359/hibernate-reactive-panache-quickstart.tar.gz)

**Comment by geoand** [comment]
cc @DavideD

**Comment by DavideD** [comment]
@silviu-negoita As you've said, it's getting the value from the cache.

The solution is to clear the session after the update:
```
        Fruit.update("SET name = ?1 WHERE externalId = ?2", NEW_TEST_NAME, ID_001)
                .call( () -> Panache.getSession().map( Mutiny.Session::clear )  )
                .await().indefinitely();
```

I'm not sure on top of my head if we can do better with vanilla Hibernate Reactive.
Anyway, it should work if you update the test.

I'm closing the issue, but feel free to comment again here if you have more questions.

Thanks

**Comment by silviu-negoita** [comment]
@DavideD  Thanks! I confirm now it works! But, how can I know all of these tricks? Are there anywhere documented?

**Comment by DavideD** [comment]
We definitely need to improve the docs, and this kind of feedback is helpful for figuring out what's lacking.

That said, Panache is built on top of Hibernate Reactive, and Hibernate Reactive is built on top of Hibernate ORM.
Panache makes it easier to execute some of the most common operations, but if you want to learn all the tricks
you need to get familiar with all those projects and understand which features are available.

`Panache.getSession` (or `Panache.getEntityManager` for the non reactive) will then give you full access to the session underneath.
