### ISSUE TITLE
KafkaDevServicesBuildTimeConfig uses redpanda:v22.1.7, v22.3.4 is available

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29521]
### Describe the bug

KafkaDevServicesBuildTimeConfig uses redpanda:`v22.1.7`, `v22.3.4` is available

https://github.com/quarkusio/quarkus/blame/main/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/KafkaDevServicesBuildTimeConfig.java#LL48C54-L48C70

`v22.3.4` is available - https://hub.docker.com/r/vectorized/redpanda/tags

**Comment by cescoffier** [comment]
I believe we can update safely. WDYT @ozangunalp ?
