### ISSUE TITLE
AnnotationProxyBuildStep is racy

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#2954]
`AnnotationProxyBuildStep` leaks a build producer outside of its build step.  Build producers can only be executed within the duration of that step's execution.  Once the step method returns, build producers must no longer be used, otherwise produced items might silently go missing (in the case where there's nothing to catch the exception that is thrown).

**Comment by mkouba** [comment]
> in the case where there's nothing to catch the exception that is thrown

What does this actually mean?

>  Build producers can only be executed within the duration of that step's execution.

If that's the case then we should definitely update the `BuildProducer`'s javadoc.

From what i remember we use this "approach" quite often, for example https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java#L181. 

How would you recommend reimplementing a similar stuff where some logic is inherently performed outside the build step but still needs to produce some build items?

**Comment by dmlloyd** [comment]
> > in the case where there's nothing to catch the exception that is thrown
> 
> What does this actually mean?

It means that when you call `BuildProducer.produce()` outside of the scope of your build step, it is (probably) throwing an exception that is silently discarded.  Though looking at the code, there might not be a check for this after all.

> > Build producers can only be executed within the duration of that step's execution.
> 
> If that's the case then we should definitely update the `BuildProducer`'s javadoc.

Sure.

> From what i remember we use this "approach" quite often, for example https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java#L181.
> 
> How would you recommend reimplementing a similar stuff where some logic is inherently performed outside the build step but still needs to produce some build items?

You'll need another build step if you want to produce build items later.  If you want to produce a build item earlier which represents some action that should occur later, your build item could contain a function of some sort that is executed in a later build step.

**Comment by dmlloyd** [comment]
In fact this has been in the doc since November 2018:

> Injected objects are only valid during a `@BuildStep` method invocation, once the method is complete they are no longer valid.

**Comment by mkouba** [comment]
> You'll need another build step if you want to produce build items later. If you want to produce a build item earlier which represents some action that should occur later, your build item could contain a function of some sort that is executed in a later build step.

Well, in my use case I need to produce a build item within an "unknown" build step (not the one which injected the build producer). In the referenced example we produce a `BeanDeploymentValidatorBuildItem` with a `BeanDeploymentValidator` instance that is executed during `ArcAnnotationProcessor.build()` and when executed may produce some build items. Would it make sense to make it possible to produce a build item during ANY build step invocation?

**Comment by dmlloyd** [comment]
Can you run the instance, but instead of producing the values directly, collect them into a list or something, and then produce the list from a known build step?

**Comment by mkouba** [comment]
I'm not sure. In any case, that would make the usage less flexible and more verbose :-(

**Comment by dmlloyd** [comment]
Ping... any more thoughts/updates on this?

**Comment by mkouba** [comment]
Ok, let's say that I would like to reimplement this build step: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/VertxProcessor.java#L158-L190 where the `BeanDeploymentValidator` is invoked within `ArcAnnotationProcessor.build()` during `STATIC_INIT`. 

We would have to add the `EventConsumerBusinessMethodItem`s in an instance variable, let's say `VertxProcessor.consumerBusinessMethods` and then add a build step that would consume `BeanContainerBuildItem` and invoke `BuildProducer<EventConsumerBusinessMethodItem>`. That would work provided a single instance of `VertxProcessor` is used for all build steps. Which is probably not the case. So the question is how to share the state between multiple build steps where the state could be modified by "async" operations, that means outside the current build step?

**Comment by dmlloyd** [comment]
> So the question is how to share the state between multiple build steps where the state could be modified by "async" operations, that means outside the current build step?

That's the key question.  The answer is "it's not allowed under any circumstances".  The problem has to be solved with a different approach.  Do you *need* actual build items for the produced `EventConsumerBusinessMethod` instances?

**Comment by mkouba** [comment]
> Do you need actual build items for the produced EventConsumerBusinessMethod instances?

I think I do. The workflow is: 
1. Register a `BeanDeploymentValidator`
2. This validator is invoked during Arc init, after all beans are discovered
3. For a method declared on a bean class and annotated with `@ConsumeEvent` produce `EventConsumerBusinessMethodItem`
4. For each `EventConsumerBusinessMethodItem` generate an invoker class and register the class for reflection
5. Finally, call a runtime template with config built from all `EventConsumerBusinessMethodItem`s

**Comment by mkouba** [comment]
Another similar use case is `io.quarkus.arc.deployment.ConfigBuildStep.analyzeConfigPropertyInjectionPoints()`:

1. Register a `BeanRegistrar`
2. Analyze all injection points in the application
3. For each IP with `@ConfigProperty` qualifier:
   1. Produce `ConfigPropertyBuildItem` which is consumed by a `@Record` build step and runs validation during `RUNTIME_INIT`
   2. For types that are not handled by `QuarkusConfigProducer` register a custom bean
   3. Produce `ReflectiveClassBuildItem` (to support implicit converters)

I think we'll have to modify/split the ArC bootstrap API so that quarkus extensions can only work with build items. So for example, instead of producing `new BeanRegistrarBuildItem(new BeanRegistrar())` and using callbacks a build step would consume something like `BeanRegistrationContextBuildItem` and access the `io.quarkus.arc.processor.BeanRegistrar.RegistrationContext` directly. But I have no idea how to implement this yet ;-).

**Comment by dmlloyd** [comment]
Let me know if you want to discuss or brainstorm this sometime this week.  I'll make sure my calendar is updated with my availability.

**Comment by mkouba** [comment]
This issue is blocked by https://github.com/quarkusio/quarkus/issues/3151

**Comment by mkouba** [comment]
I think that this one is fixed. Feel free to reopen.
