### ISSUE TITLE
Quarkus Quartz jdbc datasource + reactive datasource error

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#29540]
### Describe the bug

Hey all! Currently I have a reactive application with the Postgres driver that I am trying to integrate Quartz with. From what I read in [Quarkus Datasources](https://quarkus.io/guides/datasource#jdbc-and-reactive-datasources-simultaneously), I am able to have both a reactive and jdbc datasource working in-tandem. The issue I am having is that I can't seem to get my application to build when I create a custom quartz datasource using jdbc and I am met with this error at build time `io.quarkus.runtime.configuration.ConfigurationException: JDBC Store configured but the 'quartz' datasource is not configured properly.`.

This is how I have it set up:
```
quarkus:
  quartz:
    datasource: quartz
    clustered: true
    store-type: jdbc_tx
    table-prefix: quartz.qrtz_
```
and
```
datasource:
    db-kind: postgresql
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    jdbc: false
    reactive:
      url: ${POSTGRES_URL:postgresql://localhost:5430/db}
      max-size: ${POSTGRES_REACTIVE_POOL_SIZE:30}
      reconnect-attempts: ${POSTGRES_REACTIVE_RECONNECT_ATTEMPTS:1}
      reconnect-interval: ${POSTGRES_REACTIVE_RECONNECT_INTERVAL:PT1S}
      idle-timeout: ${POSTGRES_REACTIVE_IDLE_TIMEOUT:PT5S}
    quartz:
      db-kind: postgresql
      username: ${POSTGRES_USERNAME:postgres}
      password: ${POSTGRES_PASSWORD:password}
      reactive: false
      jdbc:
        url: ${POSTGRES_URL:postgresql://localhost:5430/db}
        max-size: ${POSTGRES_JDBC_POOL_SIZE:10}
        leak-detection-interval: ${POSTGRES_JDBC_LEAK_DETECTION_INTERVAL:5M}
```

Am I missing something in the configuration?

### Expected behavior

Quartz should start with the configured custom datasource using JDBC.

### Actual behavior

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.quartz.deployment.QuartzProcessor#driver threw an exception: io.quarkus.runtime.configuration.ConfigurationException: JDBC Store configured but the 'quartz' datasource is not configured properly. You can configure your datasource by following the guide available at: https://quarkus.io/guides/datasource
```

### How to Reproduce?

I created a very simple reproducer here to reproduce this behavior (created on-the-fly as I am not home yet): https://github.com/LazaroR94/Quartz-Quickstart

### Output of `uname -a` or `ver`

Darwin C02FW4DDMD6R 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

Additional stacktrace:
```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: JDBC Store configured but the 'quartz' datasource is not configured properly. You can configure your datasource by following the guide available at: https://quarkus.io/guides/datasource
	at io.quarkus.quartz.deployment.QuartzProcessor.driver(QuartzProcessor.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by gsmet** [comment]
I think a simple Maven reproducer would be welcome. There's probably something wrong with the config but it's not obvious.

**Comment by LazaroR94** [comment]
> I think a simple Maven reproducer would be welcome. There's probably something wrong with the config but it's not obvious.

Sure, I added a simple reproducer.

**Comment by mkouba** [comment]
> > I think a simple Maven reproducer would be welcome. There's probably something wrong with the config but it's not obvious.
> 
> Sure, I added a simple reproducer.

Hm, I can see a different error when I try to build the reproducer: `Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Datasource must be defined for persistence unit '<default>'`.

**Comment by LazaroR94** [comment]
> > > I think a simple Maven reproducer would be welcome. There's probably something wrong with the config but it's not obvious.
> > 
> > 
> > Sure, I added a simple reproducer.
> 
> Hm, I can see a different error when I try to build the reproducer: `Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Datasource must be defined for persistence unit '<default>'`.

Thank you for reporting that. Unfortunately I am not near my work computer to be able to run this. I created this on-the-fly with identical settings to that of my enterprise project so it should behave similarly logically-speaking of course. Have you been able to debug further?

**Comment by LazaroR94** [comment]
I'm not sure if this issue is also related to this: https://github.com/quarkusio/quarkus/issues/21110 seeing the ask for additional persistence units (and more specifically the last comment).

**Comment by LazaroR94** [comment]
Also, upon digging a little deeper, when using a reactive datasource + a jdbc datasource, the latter takes precedence and the default persistence unit becomes JDBC. Maybe this is the reason for my confusion?

**Comment by mkouba** [comment]
> Also, upon digging a little deeper, when using a reactive datasource + a jdbc datasource, the latter takes precedence and the default persistence unit becomes JDBC. Maybe this is the reason for my confusion?

I'm not quite sure how do the hibernate-orm and hibernate-reactive extensions cooperate but it seems that kind of configuration is not supported ATM.

CC @Sanne @gsmet @DavideD

**Comment by LazaroR94** [comment]
> > Also, upon digging a little deeper, when using a reactive datasource + a jdbc datasource, the latter takes precedence and the default persistence unit becomes JDBC. Maybe this is the reason for my confusion?
> 
> I'm not quite sure how do the hibernate-orm and hibernate-reactive extensions cooperate but it seems that kind of configuration is not supported ATM.
> 
> CC @Sanne @gsmet @DavideD

Correct, that is what I am understanding as well. When I configure both and disable jdbc on the default datasource then this new error is observed: `io.quarkus.runtime.configuration.ConfigurationException: Model classes are defined for the default persistence unit, but no default datasource was found. The default EntityManagerFactory will not be created.` 

What I find interesting is that I have another application running Quarkus `2.11.1` that seems to be running this configuration without a problem (I'm on Quarkus `2.14.2`).

**Comment by LazaroR94** [comment]
To further add, whenever I use YAML configuration (reactive + jdbc), the datasource seems to configure itself with `DataSourceJdbcRuntimeConfig`; whereas, when using .properties configuration, it seems to configure itself with `DataSourceBuildTimeConfig`?

**Comment by LazaroR94** [comment]
@Sanne @gsmet @DavideD Any input on this? This is blocking my reactive application because I am now needing to use Quartz for clustered job execution in a cloud environment.

**Comment by LazaroR94** [comment]
From what I could find, this still seems to be an open issue with hibernate-reactive not allowing multiple persistence units. I am closing this for now and hoping a fix can be done in the near future.

[#13425](https://github.com/quarkusio/quarkus/issues/13425)
