### ISSUE TITLE
CORS Rejected Error on same-origin requests when CORS is enabled

### ISSUE THREAD

**Issue by grasfrosch** [quarkusio/quarkus#29542]
### Describe the bug

Since Quarkus 2.14.2, requests return status `403` if CORS is enabled and the origin is not in the list of allowed CORS origins, even if the request is not cross-origin at all.

### Expected behavior

CORS Settings should have no impact on same-origin requests.

### Actual behavior

Enabling CORS seems to prevent all requests with an `Origin`-header that isn't explicitly whitelisted, even same-origin requests. `GET`-Requests may still work as browsers don't add the `Origin`-Header to same-origin `GET`-requests.

### How to Reproduce?

Reproducer: [cors.zip](https://github.com/quarkusio/quarkus/files/10106358/cors.zip)

See the test or just start the project and try to use the Dev UI - anything that isn't a plain GET request like the attempts to establish websockets for test and logstream will fail.

### Quarkus version or git rev

2.14.2.Final

**Comment by sberyozkin** [comment]
@grasfrosch What Origin header is being sent in your case ? The actual host name, is #29462 related ?
Also why do you enable CORS for the local DevUI work ?

Thanks

**Comment by sberyozkin** [comment]
Ok, I see
```
# Allow cors with different app running on port 9000
quarkus.http.cors=true
quarkus.http.cors.origins=localhost:9000
```
What does it mean, you have an application page served from `localhost:9000` which needs access to Demode endpoints running on `localhost:8080` ?

**Comment by sberyozkin** [comment]
I think we can enhance DevUI CORS filter to include the already configured `quarkus.http.cors.origins`, @stuartwdouglas, @cescoffier, do we want to support the main CORS filter `Origin` configuration  as well ?

**Comment by grasfrosch** [comment]
@sberyozkin I don't really care about the DevUI, that was just an example of something that breaks. I basically have some quarkus application (in this example running on localhost:8080) that includes an API and some frontend making requests to that API. Then I have a different frontend page running somewhere else (for example on localhost:9000) which also makes requests to the api on the first application. This second application is the reason why CORS is enabled and is still working fine, however the original application is now broken since 2.14.2. This does not seem limited to dev mode, though running in prod mode gives generic 403 FORBIDDEN responses without the status message referencing CORS.

**Comment by grasfrosch** [comment]
@sberyozkin So basically the request ```
POST https://my-internal-deployment.mycompany.com/api/doSomething
Origin: https://my-internal-deployment.mycompany.com
```
returns `403 Forbidden` since quarkus 2.14.2.Final. In devmode, the status message is something about Invalid CORS origin, I can provide details tomorrow if needed. Everything worked fine in 2.14.1 and CORS is enabled for unrelated reasons. As the request is not cross-origin that shouldn't matter.

**Comment by sberyozkin** [comment]
@grasfrosch Ok, 8 think I get it now

 in 2.14.2 you will get this error if you have  a simple request with Origin header which has not been proved to be valid.
I think thos issue is invalid,  I suspect the reason you saw it qorking was due to a bug in Quarkus which nowvis fixed.
Can you chech what Origin value is being actually sent by the browser ?

**Comment by maxandersen** [comment]
@sberyozkin why would 

```
POST https://my-internal-deployment.mycompany.com/api/doSomething
Origin: https://my-internal-deployment.mycompany.com
```

not be proven to be valid?

should that not work?

and @grasfrosch we did change CORS behavior in 2.14.2 but not in a way that knowingly should break valid requests - hence would be great with a reproducer!

**Comment by maxandersen** [comment]
Ah just re-read https://github.com/quarkusio/quarkus/issues/29542#issuecomment-1329566868.

indicates the ports are different which is not allowed with CORS (https://html.spec.whatwg.org/multipage/browsers.html#same-origin).

I can see how that might be interesting to loosen up for local dev cases...may I ask why you have a need to run it on different ports?

**Comment by grasfrosch** [comment]
@maxandersen I have added a button illustrating the behavior to the `index.html`-page in the reproducer:
[cors.zip](https://github.com/quarkusio/quarkus/files/10111633/cors.zip)

Just run it and open localhost:8080 in your browser.
If you disable CORS in `application.properties`, both the simple same-origin fetch on the demo page as well as the included test case work without issue.
If it is enabled like in the provided reproducer, these **same-origin** requests throw errors - cross-origin requests from the indicated origin are working perfectly fine.  

Now I might be misunderstanding CORS, so please correct me if I'm wrong. But my understanding of Cross-Origin Resource Sharing is that it allows to relax the same-origin policy in browsers. So if I enable CORS from a different origin - in our example `localhost:9000` - I would expect that to enable requests from a website hosted under `localhost:9000` **in addition** to the same-origin requests from my own website hosted under `localhost:8080` that already worked earlier. Or, to quote [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (emphasis mine): 
> Cross-Origin Resource Sharing ([CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS)) is an [HTTP](https://developer.mozilla.org/en-US/docs/Glossary/HTTP)-header based mechanism that allows a server to indicate any [origins](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (domain, scheme, or port) **other than its own** from which a browser should permit loading resources.

**Comment by pmlopes** [comment]
@grasfrosch I think there's confusion about what CORS is. The CORS protocol consists of a set of headers that indicate whether a response can be shared cross-origin.

The origin isn't "guessed" by the application server, it is the public facing name that clients use to reach your server.

If your application is running on `https://localhost:8000` the origin is that `https://localhost:8000`. Setting it to a different name will always render a bad origin. Why can you use a different origin or origins on the config? This is because your application can be deployed in different ways. For example, if you deploy it on a docker container, probably the name used by the server is: `http://172.17.0.2:10000` however the docker network or k8s will expose it as `http://my-k8s-cluster.local:80` so you need to use that name in the config. Alternatively, your server could respond under a different name by the DNS, or you may want to allow more applications to reach your server.

You need to specify the allowed origins, they are not trivially computed.

In your case, you have to list both `http://localhost:8081` and `http://localhost:9000`.

**Comment by sberyozkin** [comment]
@maxandersen 

>why would
>POST https://my-internal-deployment.mycompany.com/api/doSomething
>Origin: https://my-internal-deployment.mycompany.com
>not be proven to be valid?
>should that not work?

We don't want the requests coming from not-the-same Origin host to get through unless the user has allowed it by configuring Quarkus CORS filter to accept such Origin

**Comment by maxandersen** [comment]
> We don't want the XHR/Fetch requests coming from not-the-same Origin host to get through unless the user has allowed it by configuring Quarkus CORS filter to accept such Origin

I must be missing something:

How is `https://my-internal-deployment.mycompany.com/` not valid  origin as `https://my-internal-deployment.mycompany.com/api/doSomething` - the schme, host and port are the same. 

The only difference is the path but afaik that doesn't change the validation of origin here.

p.s. I agree the issue reported here is about port not matching; but just wanted to clarify if I'm blind on the example where port is not involded.

**Comment by sberyozkin** [comment]
@maxandersen I see, that was me not checking the question carefully.

So, right now, CORS filter does not try to compare the actual request URI and the Origin.

If it is the same Origin request then the browser must not be even setting `Origin`.
So it appears to me that @grasfrosch showed

```
POST https://my-internal-deployment.mycompany.com/api/doSomething
Origin: https://my-internal-deployment.mycompany.com/
```

to prove there is a bug but I don't think such a request can actually happen in practice where the page was loaded from `https://my-internal-deployment.mycompany.com/` and then this page tried to access `https://my-internal-deployment.mycompany.com/` and the browser set `Origin` - it is a same Origin so the browser is not supposed to do it.

**Comment by grasfrosch** [comment]
@sberyozkin Excatly that is my problem. And browsers actually do set the `Origin`-header even for same origin request. You can try the button in the second reproducer I linked [here](https://github.com/quarkusio/quarkus/issues/29542#issuecomment-1330353738), it does a simple `fetch('hello', {method: 'POST'})` or look at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin#description) again:

> Broadly speaking, user agents add the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) request header to:
> * [cross origin](https://developer.mozilla.org/en-US/docs/Glossary/CORS) requests.
> * [same-origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) requests except for [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) or [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests (i.e. they are added to same-origin [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST), [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS), [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH), and [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) requests).

**Comment by sberyozkin** [comment]
@grasfrosch Right, OK, so we have a case where the same Origin XHR/fetch request includes an Origin.

So as @pmlopes has said, why can't you list the Origin where you app is running in CORS config, ex, 
`quarkus.hhtp.cors.origin=http://localhost:8081,http://localhost:9000` ?

**Comment by sberyozkin** [comment]
If CORS filter is configured with something that does not match `Origin` header then, as a fallback, we can just check the current request URI and make sure it starts with the provided Origin, but we'd also need to do a reverse DNS lookup to prove this Origin binds to a localhost, and it will slow down things

**Comment by sberyozkin** [comment]
If CORS is enabled without configuring anything then a wildcard is supported OOB, so no any issues here, but of course we would not want users do it in production, so if the users have configured CORS to accept some not the same Origin requests then they should also configure it to allow the same Origin. Note it only applies if `POST` is involved - so it looks reasonable

**Comment by sberyozkin** [comment]
I think it warrants a Migration note, that the same Origin POST requests have to be explicitly allowed now.
Additionally I can have a look at fixing https://github.com/quarkusio/quarkus/issues/29462 both for DevUI and main CORS filters - but it will only be done optionally, doing it by default would be slow and the Origin header can be deliberately set to a value which can cause a long and failed resolution process.
IMHO we just can't go back now and allow same Origin POSTs through without CORS filter making it possible by configuring the Origin or in the future - allowing a reverse DNS lookup

**Comment by grasfrosch** [comment]
@sberyozkin sure, setting the origin where the app is running (or all possible origins, if proxies are involved) would work as a workaround, even if it would be annoying to communicate the configuration changes to the customers actually running our app. However, the behaviour seemed very suprising and unintended, which is why I reported it as a bug. As enabling CORS is fundamentally about *allowing* stuff that was previously forbidden, it denying previously working requests seems very strange. At the very least I would expect some documentation about this behaviour and a clearer warning about a breaking change in a patch update. 

To be honest I don't really see the security value in this check, as you need to trust browsers to accurately report the origin header anyways, you might as well trust them to actually honor the result of the preflight request and deny forbidden cross-origin requests at browser level. It would certainly be nice to be able to configure origin header validation separately from CORS.

**Comment by sberyozkin** [comment]
@grasfrosch The problem is, the preflight request is not guaranteed to happen when XHR makes a POST request from the not the same Origin host. So we need to be able to block such simple requests which have Origin header.

@pmlopes, all, I think that we can support such cases by 1) if the origin status check is false then check if the current request URI starts with the Origin header value and if it does start with the Origin value then let it go 2) Optionally make the previous check  stricter by supporting a reverse DNS lookup to prove this Origin binds to a localhost

@maxandersen @gsmet I think it is not a blocker though I agree with @grasfrosch that having to add the same Origin values can be annoying. Not I believe it is only a case where same Origin POST is involved

**Comment by pmlopes** [comment]
I'm not sure you can resolve all local domains, for example:

127.0.0.1 can be resolved:

```
~ $ nslookup 127.0.0.1
1.0.0.127.in-addr.arpa	name = localhost.
```

But... we can always bind to any available device with 0.0.0.0:

```
~ $ nslookup 0.0.0.0
** server can't find 0.0.0.0.in-addr.arpa: NXDOMAIN
```

While the 1st address will only allow local connections, I cannot connect to your "127.0.0.1" the second will allow connections from any device, and in fact it is a common listening address, which you can't resolve.

**Comment by pmlopes** [comment]
Just my opinion here, I don't think you should do DNS lookup to "prove" the origin binds to local host. A couple of issues here:

1. The example above, 0.0.0.0 doesn't resolve, but you can use it to connect from localhost.
2. containers, in containers, addresses are usually on a separate network, which isn't (generally) reachable from outside
3. k8s, besides the example above, it is common to deploy a control plane, like istio or something else that does, TLS termination, extra security/auditing/etc as a side-car, you may now get wrong values as the connection is now performed to another network layer
4. Can you assume that DNS is always available? and that it resolves to the external address?

My opinion is that security configuration should be explicit instead of implicit.

**Comment by sberyozkin** [comment]
Thanks @pmlopes, probably makes sense to leave the reverse lookup out for now, it can also have performance side-effects.

I've opened #29557 to check to try to determine if the request is the same origin, have a look please

**Comment by sberyozkin** [comment]
#29626 fixed it
