### ISSUE TITLE
JAX-RS resource not discovered when annotations are on interface in different jar

### ISSUE THREAD

**Issue by bdemers** [quarkusio/quarkus#29545]
### Describe the bug

I have a JAX-RS (Jakarta WS) resource defined as an interface with the various annotations in one jar, and an implementation in another one.  Quarkus does not discover this endpoint.

For example, my interface looks like this:

```java
package com.example.api;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public interface GreetingResourceInterface {
  @GET
  @Produces(MediaType.TEXT_PLAIN)
  String hello();
}
``` 

Its actual implementation is in a different jar and does NOT contain any annotations:

```java
package com.example.impl;

import org.apache.directory.scim.protocol.GreetingResourceInterface;

public class GreetingResourceImpl implements GreetingResourceInterface {

  public String hello() {
    return "Hello RESTEasy";
  }
}
```

Example directory layout:

```txt
.
├── project-a/
│   └── src/
│       └── main/
│           └── java/
│               └── com.example.api/
│                   └── GreetingResourceInterface.java
└── project-b/
    └── src/
        └── main/
            └── java/
                └── com.example.impl/
                    └── GreetingResourceImpl.java
```

### Expected behavior

Resources are discovered across jars, and appear in dev console:

`http://localhost:8080/q/dev/io.quarkus.quarkus-resteasy-reactive/endpoints`

### Output of `java -version`

3.8.5

### GraalVM version (if different from Java)

17.0.2

### Quarkus version or git rev

3.0.0.Alpha1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```txt
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) 
Maven home: /Users/bdemers/.sdkman/candidates/maven/current 
Java version: 17.0.2, vendor: Azul Systems, Inc., runtime: /Users/bdemers/.sdkman/candidates/java/17.0.2-zulu/zulu-17.jdk/Contents/Home 
Default locale: en_US, platform encoding: UTF-8 
OS name: "mac os x", version: "12.6.1", arch: "aarch64", family: "mac"
```

### Additional information

Tested with app run through IDE (IntelliJ) and via the Quarkus Maven Plugin `quarkus:dev`

Using: `quarkus-resteasy-reactive-jackson`

### Workaround

If I copy the `@Path` annotation from the interface to the implementation or move the interface and implementation into the same jar, the resource is discovered (and works fine)

**Comment by geoand** [comment]
Have you configured `project-a/` to be indexed (see [this](https://stackoverflow.com/a/55513723/2504224) for options)?

**Comment by bdemers** [comment]
Yes, I added the indexes.
The odd part is if both the above classes are in ‘project-a’ and my “application” is in ‘project-b’ everything works.

Is there something in the annotation scanning that stops on jar boundaries?

**Comment by geoand** [comment]
If the projects are indexed, it should work.

If it doesn't, we'll need a sample application which we can test

**Comment by bdemers** [comment]
Ugg... I'm a liar...
One of my jars was not getting indexed 🤦
I almost stubbed out a sample for this, and of course, when I did it proved the code was working fine.

Sorry about that!
