### ISSUE TITLE
Quickstart for Hibernate Rest data panache

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#29555]
### Description

Module quarkus-hibernate-orm-rest-data-panache was promoted[1] to full support, but there is no quickstart for it in the quicktstarts repo[2]. It is used in the optaplanner quickstart, but I presume, the standalone one will provide a better usage example.

[1] https://github.com/quarkusio/quarkus/pull/28569
[2] https://github.com/quarkusio/quarkus-quickstarts/

**Comment by Sgitario** [comment]
Pull request: https://github.com/quarkusio/quarkus-quickstarts/pull/1218
