### ISSUE TITLE
Check availability of native-image command in NativeImagePhase

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2957]
Check availability of native-image command in NativeImagePhase

Starting with GraalVM 19 native-image is not standard part of GraalVM installation.
When running Quarkus native-image plugin user gets not so great `No such file or directory`  exception. On the first sight it's not clear what file is not present as the message mentions `target` directory too.

User may think that the build went wrong and some .jar files are not availabe

**Comment by gsmet** [comment]
It would be nice if we could take care of this one today as we plan to release tomorrow with GraalVM 19 support and we could have a lot of reports.

**Comment by rsvoboda** [comment]
Wanted to keep it open for community, but I can look into it.

**Comment by gsmet** [comment]
If you can, please do. Definitely better to have it for tomorrow’s release.
