### ISSUE TITLE
Quarkus Vertx HTTP defines default keystore password

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29573]
### Describe the bug

Quarkus defines default keystore password, this is imo bad practice and we should remove that.

Noticed when looking into custom CredentialsProvider related test and confirmed in https://github.com/quarkusio/quarkus/pull/29561 description.

CC @sberyozkin

**Comment by cescoffier** [comment]
I agree, this is inherited from Vert.x but we should avoid that. 
I will require a change in Vert.x - as if we pass `null` (like no password), vert.x will use "password". I was thinking using an empty string in this case, but it's not really the same.

@vietj WDYT?
