### ISSUE TITLE
Infinispan - unable to cache uni values with @CacheResult annotation

### ISSUE THREAD

**Issue by Sirz3chs** [quarkusio/quarkus#29571]
### Describe the bug

I'm trying to use infinispan in a 100% reactive project. The method i need to cache with `@CacheResult` return an `Uni` and when it is called it never completes. It ends if i set `lockTimeout` but my values are never cached.

### Expected behavior

Be able to cache values returned from a method with `Uni` with or without `lockTimeout`.

### Actual behavior

The method never completes without `lockTimeout` parameter, and with it doesn't cache values.

### How to Reproduce?

I've made a reproduction project: https://github.com/Sirz3chs/quarkus-infinispan-client-issue

It just need to create a ressource with a method annotated with `@CacheResult(cacheName = "foo")` that returns an `Uni`.

### Output of `uname -a` or `ver`

Linux 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

While testing, i supposed that the `UnresolvedUniValue` in [InfinispanGetWrapper.java](https://github.com/quarkusio/quarkus/blob/main/extensions/infinispan-client/runtime/src/main/java/io/quarkus/infinispan/client/runtime/cache/InfinispanGetWrapper.java) is never cached, so it is never replaced. But i'm not really confident while debugging reactive.

Moreover it seems ifinispan keeps dead transations after my method was called. [out.log](https://github.com/quarkusio/quarkus/files/10122236/out.log)
```
2022-11-30 10:39:13,341 WARN  (ForkJoinPool.commonPool-worker-1) [org.infinispan.server.core.transport.NettyTransport] ISPN005007: [id: 0x91d097c7, L:/172.17.0.2:11222 - R:/172.17.0.1:47424] is still connected to /172.17.0.1:47424
```

**Comment by Sirz3chs** [comment]
I've also tried diffrent cache configuration:
- SYNC without tansaction
- SYNC with tansaction
- ASYNC

But nothing changed

**Comment by karesti** [comment]
I'm on it, thanks

**Comment by jdussouillez** [comment]
Any updates ?

**Comment by karesti** [comment]
@jdussouillez I've been working on a refactoring and sidetracked by other issues, not yet fixed but near planning

**Comment by jdussouillez** [comment]
@karesti Any updates ?

**Comment by karesti** [comment]
i've been working on the infinispan-cache-extension to replace these annotations so far, my priorities have also been somewhere else, sorry for the time getting this fixed 
I hope the cache extension will land sooner than later
