### ISSUE TITLE
@ConsumeEvent annotated method is called twice per message when generic parent class has an abstract method for it

### ISSUE THREAD

**Issue by benjaminrau** [quarkusio/quarkus#29585]
### Describe the bug

Having a class extending a class with generics which has an abstract method for the consumer method, this will result in the method annotated with `@ConsumeEvent` on the extending class to be called twice per eventbus message.

### Expected behavior

Its expected that a method annotated with `@ConsumeEvent` is invoked only once per message.

1. Remove `public abstract void consume(@NonNull T event);` from `GreetingService`
2. Start the application
3. You will notice that the consumer is invoked only once per message

### Actual behavior

Having a class extending a class with generics which has an abstract method for the consumer method, this will result in the method annotated with `@Consume` on the extending class to be called twice per eventbus message.

1. Start the application
2. You will notice duplicated outputs from consumer like `consuming HelloEvent on HelloService: ee73ab41-6b9a-465a-967c-d264046e0cc0`

### How to Reproduce?

Reproducer:

1. Clone https://github.com/benjaminrau/genericdoublesconsumer
2. Start the application
3. See the duplicated output for same UUID (there should be only one)

Ive also prepared a test which shows that the consumer is registered twice in Vertx HandlerMap: `https://github.com/benjaminrau/genericdoublesconsumer/blob/master/src/test/java/org/acme/EventBusTest.java`

### Output of `uname -a` or `ver`

Linux br-builders-nb 5.14.0-1052-oem #59-Ubuntu SMP Fri Sep 9 09:37:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Additional information
The log output clearly shows that the consumer is called twice for the same message since the payload is a randomized UUID string.

```
2022-11-30 17:39:41,659 INFO  [org.acm.HelloService] (vert.x-eventloop-thread-1) consuming HelloEvent on HelloService: cdd635b3-f7ee-4a07-adea-56fbebfc5366
2022-11-30 17:39:41,659 INFO  [org.acm.HelloService] (vert.x-eventloop-thread-0) consuming HelloEvent on HelloService: cdd635b3-f7ee-4a07-adea-56fbebfc5366
2022-11-30 17:39:43,659 INFO  [org.acm.HelloService] (vert.x-eventloop-thread-1) consuming HelloEvent on HelloService: eedb7070-d1e8-4686-8e53-c6733926ad52
2022-11-30 17:39:43,659 INFO  [org.acm.HelloService] (vert.x-eventloop-thread-0) consuming HelloEvent on HelloService: eedb7070-d1e8-4686-8e53-c6733926ad52
```

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
Hm, it has to be something related to the `lombok.NonNull` annotation. I'm not able to reproduce the problem when I remove the annotation.

**Comment by benjaminrau** [comment]
@mkouba Maybe i understand you wrong but if you wonder why the test fails that might be probably misleading by me: I made the test fail until the bug is fixed. When the bug is fixed it should pass (only one consumer on the address)

**Comment by benjaminrau** [comment]
I justed tested it and NonNull makes no difference here. The issues persists. Ive updated the reproducer (removed NonNull) to not  be misleading there.

**Comment by mkouba** [comment]
@benjaminrau https://github.com/quarkusio/quarkus/pull/29620 should fix the problem. It would be great if you could give it a try.

**Comment by mkouba** [comment]
> Actually i didnt check the issue for explicit mode, so i didnt notice there is no issue in dev mode.

It seems that the compiler used in the dev mode does not copy the annotations from the original method to the generated bridge method.

**Comment by benjaminrau** [comment]
@mkouba Id ready love to but ive to admit that i dont know how to include quarkus at the given commit hash on my repo. Is ther probably some documentation you could refer to how to do so?

**Comment by benjaminrau** [comment]
@mkouba Will try later today, will let you know whether i was successful or not. Thanks for the hints! Looks quite interesting!

**Comment by benjaminrau** [comment]
@mkouba Following the steps i cant reproduce the issue any longer :) It seems you are fixing bugs faster than i am able to describe them. Incredible! Wants again you (Quarkus team) leave me stunned.

Offtopic:
When i did mvnw -Dquickly it seemed to have failed with a lot of error messages like below but when i was stuck trying to fix that build i continued by doing the changes on the pom.xml and wondered that somehow my reproducer was anyway using the quarkus version from the pull request branch.

Is there an easy explanation for that?

```
[ERROR] /home/benjaminrau/Projects/quarkus-fix/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/sortedset/SortedSetCommands.java:[182,47] Possible heap pollution from parameterized vararg type K
```

**Comment by mkouba** [comment]
> Offtopic: When i did mvnw -Dquickly it seemed to have failed with a lot of error messages like below but when i was stuck trying to fix that build i continued by doing the changes on the pom.xml and wondered that somehow my reproducer was anyway using the quarkus version from the pull request branch.
> 
> Is there an easy explanation for that?

Hm, I thought that "Possible heap pollution" is a compiler warning... not an error.
