### ISSUE TITLE
@ConfigMapping throws java.util.NoSuchElementException

### ISSUE THREAD

**Issue by floresmleonardo** [quarkusio/quarkus#29583]
### Describe the bug

Declaring a ConfigMapping in a quarkus extension runtime module as:

```java
@ConfigMapping(prefix = "test")
public interface MyConfigMapping {

String id();

}
```

Then, using the quarkus extension deployment module to set it as **Unremovable**:

```java
  @BuildStep
  UnremovableBeanBuildItem addUnremovable() {
    return UnremovableBeanBuildItem.beanTypes(MyConfigMapping.class);
  }
```

or:

```java
 @BuildStep
  AdditionalBeanBuildItem addUnremovable() {
    return AdditionalBeanBuildItem.builder()
        .addBeanClass(MyConfigMapping.class)
        .setUnremovable()
        .build();
  }
```

throws:

 `java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for org.test.MyConfigMapping`

### Expected behavior

It is expected the bean been marked as unremovable programmatically by the deployment module, be picked for the Configuration system

### Output of `uname -a` or `ver`

Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

**NOTE**: Using the annotation `@Unremovable` directly on the ConfigMapping class works as expected.

**Comment by geoand** [comment]
cc @radcortez
