### ISSUE TITLE
Qute add a way to get the raw String content of a template

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#29587]
### Description

When using a Template with a @Location, add a way to get the raw String content of the Template

**Comment by mkouba** [comment]
What's the use case? I think it would make more sense to add the `Optional<TemplateLocation> locate(String id)` method to the `io.quarkus.qute.Engine`. This method would use all the registered `TemplateLocator` s.

**Comment by Plawn** [comment]
In the mean time I read the code of the engine and saw that the rawString was not kept in the TemplateInstance at the moment

**Comment by mkouba** [comment]
> In the mean time I read the code of the engine and saw that the rawString was not kept in the TemplateInstance at the moment

Yep, because it's useless. We only keep the _compiled_ template.

**Comment by Plawn** [comment]
Hum, you are right

**Comment by mkouba** [comment]
I think that we could add the `Engine#locate()` method...
