### ISSUE TITLE
UniAsserter - make it easier to share data between assertions

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#29584]
### Description

Currently, if you want to share some data the only way is to use some "external" holder, e.g.
```java
@RunOnVertxContext
public void testSomething(UniAsserter asserter) {
   AtomicReference<Foo> holder = new AtomicReference<>();
   asserter.execute(() -> {
      Foo f = new Foo();
      // do something with Foo
      holder.set(f);
   }
   asserter.assertThat(() -> findAnotherFoo(), f -> assertEquals(f.getName(), holder.get().getName()));
}
```

### Implementation ideas

We could add some method directly to the `UniAsserter` or even consider [Mutiny context passing API](https://smallrye.io/smallrye-mutiny/2.0.0/guides/context-passing/#how-to-access-a-context).

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
Do you have examples of how you want to use this?

**Comment by mkouba** [comment]
> Do you have examples of how you want to use this?

The simplest possible example could be:

```java
@RunOnVertxContext
public void testSomething(UniAsserter asserter) {
   asserter.execute(() -> {
      Foo f = new Foo();
      asserter.putData(f);
   }
   asserter.assertThat(() -> findAnotherFoo(), f -> assertEquals(f.getName(), asserter.getData().getName()));
}
```

The asserted data can be stored in a concurrent `Map<String,Object>` in `UniAsserter`; `asserter.getData()` could delegate to `asserter.getData("defaultKey")` and `asserter.putData(value)` could delegate to `asserter.putData("defaultKey", value)`. This way you would not need any external holder.

**Comment by geoand** [comment]
Sounds good to me. Do you have something already?

**Comment by geoand** [comment]
Cool, thanks!
