### ISSUE TITLE
`Redis host not configured` exception when using certain extensions with devservices disabled (using custom TestResources)

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29606]
### Describe the bug

After https://github.com/quarkusio/quarkus/pull/29491 I receive `Redis host not configured` exception 
In one old project we are using relatively large set of extensions and custom TestResources with devservices disabled.

I was able to trim down the set of extensions that trigger the trouble ++ one needs to specify `quarkus.devservices.enabled=false`.

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-redis-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
```

### Expected behavior

Tests pass

### Actual behavior

`io.quarkus.runtime.configuration.ConfigurationException: Redis host not configured - you must either configure 'quarkus.redis.hosts` or 'quarkus.redis.host-provider-name' and have a bean providing the hosts programmatically.`

### How to Reproduce?

 - get https://github.com/rsvoboda/code-with-quarkus (see commit https://github.com/rsvoboda/code-with-quarkus/commit/7bd15efeb2c49760c4b3a27a2175290bda931255)
 - run `mvn clean verify -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.devservices.enabled=false`

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by rsvoboda** [comment]
CC @ozangunalp

**Comment by ozangunalp** [comment]
I think there are two problems in this:
1/ There is no default value for `quarkus.redis.host` as @afalhambra mentioned this should be removed:  to be double-checked by @cescoffier 
2/ The smallrye-kafka extension creates a redis client (unused if not necessary) but that triggers the creation of a redis client by config. In the fix the smallrye-kafka extension needs to create the redis client only when it is necessary by config.

**Comment by cescoffier** [comment]
having a default value to `quarkus.redis.host` is problematic, as we need to check if the user was expecting it (no value because my redis is running on the default port) to know if we need to start a dev service.
