### ISSUE TITLE
https://code.quarkus.io/ doesn't provide 2.13 stream

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29616]
### Describe the bug

https://code.quarkus.io/ doesn't provide 2.13 stream

2.13 is important for RHBQ, same as 2.7 stream.

CC @maxandersen @gsmet

**Comment by gsmet** [comment]
@ia3andy that's probably something for you.

**Comment by maxandersen** [comment]
this is registryrecommend list that needs adjustment; @gastaldi ?

**Comment by gastaldi** [comment]
@maxandersen yes. Because 2.14 and 2.15 are out  the 2.13 stream needs to be pinned, just like we did with 2.7

**Comment by gastaldi** [comment]
Done in https://github.com/quarkusio/quarkus-extension-catalog/commit/2c737bb9a97fd47df71a874fdcfb92f1a341b446
