### ISSUE TITLE
Build warnings when using quarkus-smallrye-health extension

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2963]
**Describe the bug**
The following warnings are shown during the build:
```
[WARNING] [io.quarkus.arc.processor.Methods] Method io.smallrye.health.SmallRyeHealthReporter.getHealth() is final, skipped during generation of corresponding intercepted subclass
[WARNING] [io.quarkus.arc.processor.Methods] Method io.smallrye.health.SmallRyeHealthReporter.getHealth() is final, skipped during generation of corresponding client proxy
```

**Expected behavior**
No warnings

**Actual behavior**
Warning is shown

**To Reproduce**
1.
```
 mvn io.quarkus:quarkus-maven-plugin:0.17.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" \
    -Dextensions="quarkus-smallrye-health"
```
2. cd getting-started 
3. mvn package

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ggastald-laptop 5.1.6-300.fc30.x86_64 #1 SMP Fri May 31 17:43:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```
 - GraalVM version (if different from Java): Not installed
 - Quarkus version or git rev: 0.17.0

**Comment by machi1990** [comment]
@gastaldi the warning is expected: introduce by this PR https://github.com/quarkusio/quarkus/pull/2644.

**Comment by gastaldi** [comment]
@machi1990 I am not saying that the warning shouldn't exist, but I think the smallrye-health extension needs to be enhanced to not trigger that warning, no?

**Comment by mkouba** [comment]
Moreover, [this method](https://github.com/smallrye/smallrye-health/blob/master/implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java#L102) is private and should be completely ignored.
