### ISSUE TITLE
manage.sh in lambda guide does not exist

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#29636]
### Describe the bug

https://quarkus.io/guides/amazon-lambda#create-an-execution-role mentions manage.sh should be in the generated project but no such file are created when running the archetype creating project.

**Comment by maxandersen** [comment]
scratch that - its just that its generated into `target/manage.sh` - which is hidden when searching in intellji thus I didn't spot it.

This detail is mentioned *after* manage.sh is mentioned so easy fix here is to state to look in build output folder will help :)

**Comment by patriot1burke** [comment]
Docs state "generated by the build"
