### ISSUE TITLE
Auto-create trace/span context via OTEL for simple `@Scheduled` methods 

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#29647]
### Description

I would like to have my scheduled job methods traced by default so that I don't have to add `@WithSpan`on each such method. 

PS: Separated from the Quartz scheduler flavor as advised here: https://github.com/quarkusio/quarkus/issues/28552#issuecomment-1332540691

### Implementation ideas

`quarkus.scheduler.tracing.enabled`, in analogy to [quarkus.scheduler.metrics.enabled](https://quarkus.io/guides/scheduler#quarkus-scheduler_quarkus.scheduler.metrics.enabled)?

**Comment by Ladicek** [comment]
> I would like to have my scheduled job methods traced by default so that I don't have to add `@WithSpanon` each such method.

That's some proper laziness there :laughing:

I believe we treat `@WithSpan` as an interceptor binding, so perhaps a simple annotation transformation would do the trick. WDYT @mkouba?

**Comment by famod** [comment]
> > I would like to have my scheduled job methods traced by default so that I don't have to add `@WithSpanon` each such method.
> 
> That's some proper laziness there laughing

It partially is! :sweat_smile:
Then again we have 63 usages of `@Scheduled` and it's too easy to forget to add `@WithSpan` to a new scheduled method (ArchUnit helps greatly, though).

**Comment by mkouba** [comment]
> > I would like to have my scheduled job methods traced by default so that I don't have to add `@WithSpanon` each such method.
> 
> That's some proper laziness there laughing
> 
> I believe we treat `@WithSpan` as an interceptor binding, so perhaps a simple annotation transformation would do the trick. WDYT @mkouba?

That's exactly what we do for metrics: https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/deployment/src/main/java/io/quarkus/scheduler/deployment/SchedulerProcessor.java#L332-L372. In fact, `@WithSpan` is even more straightforward...

**Comment by Ladicek** [comment]
Ah, very nice!

**Comment by brunobat** [comment]
Yeah... That's a nice improvement.
