### ISSUE TITLE
Can we have simple session authentification

### ISSUE THREAD

**Issue by clochardpagan** [quarkusio/quarkus#2966]
**Description**
Quarkus is new, modern, fancy all the good things you have, when you are young. But there are some not-so-young systems we deal with, and it will be a huge relief to have something similar to good old sessions id cookies stored somewhere.

**Implementation ideas**
No big ideas, but there are some reasons why it's not possible, convenient or secure to use JWT secured service. For example: http://cryto.net/%7Ejoepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/ is a good read. Every problem can be fixed on it's own, but dealing with all of them at a scale will be a hard. So it's a good move to add some old-school techniques in a deck.

We can use Elytron security and extend it backup session storage in some fashion, some well designed key-value storage (Infinispan, Redis, etc.), but at the moment I have no more detailed plan, sorry.

**Comment by emmanuelbernard** [comment]
Let's refine a bit you needs. If you need is to be able to do user state without JWT, one option is to rely on an external key/value system like Infinispan https://quarkus.io/guides/infinispan-client-guide to store that per user state outside of the Quarkus app proper. That way your Quarkus app remains stateless and more easily scalable.

We then can imagine an easier way to define and propagate a userid header, parameter, etc and be able to fetch it for your key lookup.

We have had several conversations around finding valid use cases for a Session object of sort. All came out empty handed so far. If you can give use cases around the need to keep a session state that would not be covered by a key/value backend or JWT more naturally, let's list them here.

**Comment by clochardpagan** [comment]
Hmmm... There can be any production scenario where we really need session. Always we can offload state to somewhere (JWT, kv-pair, remote-service, etc.) But in case of development mode it is a neat feature. For example, we'd like to work on some service (initial development phase) and create primitive security layer to split users activity. But in case of Infinispan we'll need to setup server on developers machine (docker is an option, but do we really need it or permitted to use it?). In case of JWT we'll use some generator embedded in app - not a good idea again.

So in refined state need can be proposed as "give a way to developer to create primitive session without any external hassle in development mode"

**Comment by emmanuelbernard** [comment]
We do have an internal local cache implementation that could be used for your development mode to simulate infinispan. Let's explore that idea.

> In case of JWT we'll use some generator embedded in app - not a good idea again.

If that's development mode, is that a problem?

CC @tristantarrant and @sebastienblanc to brainstorm these dev simulation ideas.

**Comment by stuartwdouglas** [comment]
We have encrypted cookie support as part of FORM auth, which does a similar thing but without needed any state on the server.

**Comment by iriikoad** [comment]
Is there an example how to read this cookie?

> We have encrypted cookie support as part of FORM auth, which does a similar thing but without needed any state on the server.
