### ISSUE TITLE
Warning log "Unrecognized configuration key" on native build occurs for known properties 

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#29660]
### Describe the bug

When starting a native-build quarkus application we get some of the following warnings:
```
Unrecognized configuration key "yyy.images.duration" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
The mentioned properties are used in the application with `@ConfigProperty` or in an interface with `@ConfigMapping`.
The properties are also read correctly and applied as configured. So it is more about the warning-logging that is wrong.

I tried to create a reproducer, but there it works without a problem, so I currently have no clue when this happen and when not.

### Output of `java -version`

Java 17.0.5

### GraalVM version (if different from Java)

Mandrel 22.3.0

### Quarkus version or git rev

2.14.2.Final

**Comment by gsmet** [comment]
Could you provide a simple reproducer? Thanks!

**Comment by joggeli34** [comment]
I tried to create a reproducer, but there it works without a problem, so I currently have no clue when this happen and when not.
I will give it another try tomorrow, perhapse I find a dependency or something that causes the problem.

**Comment by joggeli34** [comment]
After some testing I found out following:

We are having a custom extension which has a configuration like this:
```java
@ConfigRoot(prefix = "yyy", name = "mqtt.connection", phase = ConfigPhase.RUN_TIME)
public class MqttConnectionConfiguration {
    @ConfigItem(name = "url")
    public String brokerUrl;
}
```

The `yyy` here stands for our company name, so we have also additional configuration in the projects directly starting with `yyy` like in the example from this issue:
```properties
yyy.images.duration=2s
```

The above warning is shown for all properties starting with `yyy` inside the properties. The warning appears at the start of a native application and during the build process of the jar.

So it seems that we can't have properties starting with the same name as the prefix in a dependent extension. This makes perfect sense for the default "quarkus"-prefix, but I'm not sure if this should also be checked for other prefixes?

If this is works as designed, we can close the issue (probably add a doc somewhere?).

**Comment by gsmet** [comment]
@radcortez not sure if you have all the relevant information for this one but it's probably best if you ask for additional info yourself.

**Comment by radcortez** [comment]
I'll have a look.
