### ISSUE TITLE
Flyway reactive

### ISSUE THREAD

**Issue by DMaxter** [quarkusio/quarkus#29677]
### Description

I have been using Quarkus along with RestEASY Reactive and Hibernate Reactive and now the time has come to use Flyway.

Searching through the documentation I wasn't able to find any mention to Flyway using reactive datasources.
Is it possible to implement this behavior in Flyway?

Thanks in advance.

**Comment by geoand** [comment]
It's not possible yet (but that will hopefully change soon). See https://github.com/quarkusio/quarkus/issues/10716 for more details
