### ISSUE TITLE
@InjectMock for user defined mocks (fakes)

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#29707]
### Description

Given I have some user defined mock (fake), it would be nice to have an easy, declarative way of injecting it like I can for Mockito mocks with `@InjectMock`, e.g.

```java
class Test {
  @InjectMock(mockClass = MyMock.class)
  MockableBean mockableBean;
}
```

would inject an instance of `MyMock` into the application and test.

This would make injecting user defined mocks per test as simple as injecting Mockito mocks and avoid a bunch of JUnit boilerplate in setting up mocks with `QuarkusMock`.

### Implementation ideas

Could add a parameter to `@QuarkusMock` annotation, e.g. `mockClass`, which if set creates an instance of that class and uses it (same as if you annotated the class itself with `@Mock`, but per-test).

Or it could be a new annotation e.g. `@InjectFake`.

**Comment by geoand** [comment]
So you essentially want to be able to create a custom instance that is not a Mockito mock?

**Comment by josephearl** [comment]
Yes, like `@InjectMock` provides a shortcut for creating and installing Mockito mocks. This would be a bit like `@Mock`, but applied per test

**Comment by geoand** [comment]
Thanks, I'll consider it

**Comment by geoand** [comment]
As `@InjectMock` has been [deprecated](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2#injectmock), I'm going to close this

**Comment by mjedwabn** [comment]
@geoand as both tickets have been closed - https://github.com/quarkusio/quarkus/issues/29706 and this - could you elaborate what is the plan for installing mocks for an interface (test scoped, not global)?

**Comment by geoand** [comment]
@mjedwabn what's your use case exactly?
