### ISSUE TITLE
Fix reflection registration of unknown class

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2971]
We have to revert https://github.com/quarkusio/quarkus/pull/2970 and see if allowing incomplete classpath fixes the issue.

Or we need to find a better fix.

**Comment by rsvoboda** [comment]
Some details in https://github.com/quarkusio/quarkus/issues/2959 and https://github.com/quarkusio/quarkus/pull/2969

**Comment by emmanuelbernard** [comment]
Is it obsolete?

**Comment by gsmet** [comment]
No, I just never had the time to get to it.

**Comment by gsmet** [comment]
I think we can close this one.
