### ISSUE TITLE
Maven Javadoc Plugin fails because of a Quarkus module name

### ISSUE THREAD

**Issue by triceo** [quarkusio/quarkus#29719]
### Describe the bug

When upgrading Maven Javadoc Plugin to 3.4.1, we get the following exception:

    Execution build-javadoc-jar of goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar failed: Unable to derive module descriptor for /var/home/triceo/.m2/repository/io/quarkus/quarkus-class-change-agent/2.14.1.Final/quarkus-class-change-agent-2.14.1.Final.jar: quarkus.class.change.agent: Invalid module name: 'class' is not a Java identifier

It appears that `quarkus.class.change.agent` is not a valid JPMS module name, note the `class` keyword. And this transitively breaks our build.

### Expected behavior

Quarkus does not transitively break downstream projects' Javadoc generation.

### Actual behavior

An exception is thrown during Javadoc generation.

### How to Reproduce?

Build this PR:
https://github.com/kiegroup/optaplanner/pull/2412

See exception in `optaplanner-quarkus-deployment` module.

### Output of `uname -a` or `ver`

Linux degrasse 6.0.10-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:55:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

2.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/triceo/.sdkman/candidates/maven/current Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: /var/home/triceo/.sdkman/candidates/java/17.0.4-tem Default locale: cs_CZ, platform encoding: UTF-8 OS name: "linux", version: "6.0.10-300.fc37.x86_64", arch: "amd64", family: "unix"

**Comment by famod** [comment]
Related: #28919
