### ISSUE TITLE
Application beans are not shown first in Arc DevUI

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#29723]
### Describe the bug

Some RR beans are shown before application beans in the DevUI ArC tab.
![2022-12-07-1670405973_1274x462](https://user-images.githubusercontent.com/9353101/206144957-be138df3-a659-43ee-9028-8d03e6a424d2.png)

### Expected behavior

Applications beans used to be shown first.

### Quarkus version or git rev

2.14.3.Final

**Comment by xstefank** [comment]
hmm, I should have mentioned RR in the description I guess :) Who from RR can decide whether these beans need to be marked as "application" beans?

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
I'll have a look in a few days
