### ISSUE TITLE
Liquibase changelog with more than one file fails in native mode

### ISSUE THREAD

**Issue by joaomfas** [quarkusio/quarkus#29728]
### Describe the bug

I have a db folder with the following structure:
db/
├── changeLog.xml
├── 1.0.0/
│   ├── changeLog-1.0.0.xml
└── 2.0.0/
                    └── changeLog-2.0.0.xml

If I include both changeLogs in the changeLog.xml file an error occurs while running the app stating that the second changeLog is not found:
Failed to start application (with profile prod): liquibase.exception.ChangeLogParseException: The file db/2.0.0/db.changelog-2.0.0.xml was not found in the configured search path.

This problem does not occur in dev mode.

![image](https://user-images.githubusercontent.com/4108854/206169041-50deabf3-0a5b-4c5c-9469-9ea4291f94c3.png)

### Expected behavior

Both changeLogs should be detected and executed in native mode.

### Actual behavior

Only the first changeLog is detected and an error occurs stating that the second changeLog is not found.

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.14.2

**Comment by geoand** [comment]
Do you mind including as a sample application that exhibits the problematic behavior?
