### ISSUE TITLE
Developing Extension error - Deployment artifact xxx is missing the following dependencies from its configuration

### ISSUE THREAD

**Issue by bharatnpti** [quarkusio/quarkus#29759]
### Describe the bug

Getting error while building custom extension.

Console output

[INFO] quarkus-extension-atom ............................. SUCCESS [  0.280 s]
[INFO] quarkus-extension-atom-example ..................... SUCCESS [  0.842 s]
[INFO] quarkus-extension-atom-parent ...................... SUCCESS [  0.008 s]
[INFO] quarkus-extension-atom-anonymiser .................. SUCCESS [  0.008 s]
[INFO] quarkus-extension-atom-anonymiser-core ............. SUCCESS [  1.507 s]
[INFO] Anonymiser-Mask - Parent ........................... SUCCESS [  0.011 s]
[INFO] Anonymiser-Mask - Runtime .......................... FAILURE [  2.132 s]
[INFO] Anonymiser-Mask - Deployment ....................... SKIPPED

[ERROR] Failed to execute goal io.quarkus:quarkus-extension-maven-plugin:2.14.0.Final:extension-descriptor (default) on project quarkus-extension-atom-anonymiser-mask-runtime: Deployment artifact org.quarkus.extension.atom:quarkus-extension-atom-anonymiser-mask-runtime-deployment::jar:1.0-SNAPSHOT is missing the following dependencies from its configuration: org.quarkus.extension.atom:quarkus-extension-atom-anonymiser-mask-runtime::jar, io.quarkus:quarkus-arc-deployment::jar, io.quarkus:quarkus-core-deployment::jar, io.quarkus:quarkus-config-yaml-deployment::jar, io.quarkus:quarkus-resteasy-deployment::jar, io.quarkus:quarkus-vertx-http-deployment::jar, io.quarkus:quarkus-mutiny-deployment::jar, io.quarkus:quarkus-smallrye-context-propagation-deployment::jar, io.quarkus:quarkus-vertx-deployment::jar, io.quarkus:quarkus-netty-deployment::jar, io.quarkus:quarkus-resteasy-server-common-deployment::jar, io.quarkus:quarkus-resteasy-common-deployment::jar -> [Help 1]

### Expected behavior

The build should be successful

### Actual behavior

build fails with error

### How to Reproduce?

Reproducer:    https://github.com/techpleiad/core-quarkus.git 

Steps to reproduce - 

1) Clone and switch to branch dev_maven
2) run mvn clean install

**Comment by bharatnpti** [comment]
@aloubyansky - Can you please help with this

**Comment by aloubyansky** [comment]
https://github.com/techpleiad/core-quarkus/blob/dev_maven/quarkus-extension-atom-parent/quarkus-extension-atom-anonymiser/quarkus-extension-atom-anonymiser-core/pom.xml declares dependencies on other extensions. Your deployment module does not depend on the corresponding deployment artifacts of those extensions.
Please consider using discussions or zulip for these kinds of questions next time.

**Comment by bharatnpti** [comment]
@aloubyansky - sure thank you for the quick response
