### ISSUE TITLE
Downgrading Log Level  For Category Doesn't Work For Console Logging

### ISSUE THREAD

**Issue by brianwyka** [quarkusio/quarkus#29764]
### Describe the bug
Attempted to change the log level to `DEBUG` for a certain category when logging to console, but it does not output logs to console when console log level is `INFO`.

### Expected behavior
Given the following in my properties file I should see `DEBUG` logs for `com.brianwyka.example`

```properties
quarkus.log.console.level = INFO
quarkus.log.category."com.brianwyka.example".level = DEBUG
```

Obtaining Logger from SLF4J
```java
private static final Logger LOGGER = LoggerFactory.getLogger("com.brianwyka.example.ClassName");
```

When I remove the `quarkus.log.console.level = INFO`, I get the `DEBUG` logs...

### Output of uname -a or ver
`MacOS Monterey 64-bit`

### Output of java -version
`17.0.5`

### GraalVM version (if different from Java)
No response

### Quarkus version or git rev
`2.14.3.Final`

### Build tool (ie. output of mvnw --version or gradlew --version)
`gradlew 7.5.1`

### Additional information
No response

**Comment by geoand** [comment]
This is expected as `quarkus.log.console.level` acts as the minimum level for the console logs.

**Comment by brianwyka** [comment]
@geoand , doesn't this contradict what is documented for the "root" logger?
https://quarkus.io/guides/logging#runtime-configuration

Does it make sense to have a `min-level` for console logging so it's not confusing, or at least to document this?

Is there a workaround where I can achieve this?

**Comment by geoand** [comment]
I personally don't see how the docs could be less confusing, but let's see if @gastaldi has any insights

**Comment by gastaldi** [comment]
I agree with @geoand. Whatever is set in `quarkus.log.console.level` is considered the minimum level. There is an example here: https://quarkus.io/guides/logging#examples

**Comment by brianwyka** [comment]
So, I need to set the log level for the console  to `DEBUG`, and then explicitly set all `categories` to `INFO` excluding the one I want for `DEBUG`?  That seems backwards...

**Comment by gastaldi** [comment]
You don't set `quarkus.log.console.level`, just the category you want as `DEBUG`

**Comment by brianwyka** [comment]
Thanks, this worked.
