### ISSUE TITLE
CSRF not working on POST actions that require no form parameters

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#29763]
### Describe the bug

I'm pretty sure this is related to the problem I had in https://github.com/quarkusio/quarkus/issues/22444 where the body was not read if the endpoint didn't have a single `@RestForm` parameter.

If your endpoint doesn't have any `@RestForm` or `@FormParam` parameter, RESTEasy Reactive doesn't add the body filter that reads the form parameters (urlencoded or multipart) and so the CSRF filter can't work:

```java
@Path("Application")
public class Application {

    @Inject
    CsrfTokenParameterProvider csrfToken;

@Path("csrfToken")
    public String csrfToken() {
        return csrfToken.getToken();
    }

@Path("csrfForm1")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @POST
    public String csrfForm1(@RestForm String name) {
        return "OK: " + name;
    }

@Path("csrfForm2")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @POST
    public String csrfForm2(@RestForm String name) {
        return "OK: " + name;
    }

@Path("csrfForm3")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @POST
    public String csrfForm3() {
        return "OK";
    }

@Path("csrfForm4")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @POST
    public String csrfForm4() {
        return "OK";
    }
}
```

```java
@QuarkusTest
public class RenardeResourceTest {

    @Test
    public void testCsrf() {
        RenardeCookieFilter cookieFilter = new RenardeCookieFilter();
        String token = given()
                .filter(cookieFilter)
                .when().get("/Application/csrfToken")
                .then()
                .statusCode(200)
                .extract().asString();
        Assertions.assertTrue(token.length() > 0, "Empty token in form: " + htmlForm);
        // no token, no dice
        given()
                .filter(cookieFilter)
                .when()
                .param("name", "Stef")
                .post("/Application/csrfForm1")
                .then()
                .statusCode(400);
        // token: good
        given()
                .filter(cookieFilter)
                .when()
                .param("csrf-token", token)
                .param("name", "Stef")
                .post("/Application/csrfForm1")
                .then()
                .statusCode(200)
                .body(is("OK: Stef"));
        // no token, no dice
        given()
                .filter(cookieFilter)
                .when()
                .multiPart("name", "Stef")
                .post("/Application/csrfForm2")
                .then()
                .statusCode(400);
        // token: good
        given()
                .filter(cookieFilter)
                .when()
                .multiPart("csrf-token", token)
                .multiPart("name", "Stef")
                .post("/Application/csrfForm2")
                .then()
                .statusCode(200)
                .body(is("OK: Stef"));
        given()
        .filter(cookieFilter)
        .when()
        .param("csrf-token", token)
        .post("/Application/csrfForm3")
        .then()
        .statusCode(200)
        .body(is("OK: Stef"));
        given()
        .filter(cookieFilter)
        .when()
        .multiPart("csrf-token", token)
        .post("/Application/csrfForm4")
        .then()
        .statusCode(200)
        .body(is("OK: Stef"));
    }
}
```

This currently prevents using the CSRF filter in any application that doesn't need form parameters, except for the CSRF token one. So it should be fixed in 2.15 (because I don't think the CSRF handler fix was backported to 2.14 so it doesn't work there anyway, unless i'm mistaken).

CC @sberyozkin

**Comment by sberyozkin** [comment]
Hi Steph, well, we have now removed vertx handling it, CSRF feature is now a `ServerRestHandler`, to get multipart/form-data supported. So for this to work RestEasy Reactive should be configured to read the body even if no form parameters are present - CSRF feature can not control it.
In principle, we could fallback to trying to read the body the Vertx way if the form map provided to CsrfHandler is empty but the content type matches and Content-Length is > 0, would it be a good idea, I don't know...

**Comment by FroMage** [comment]
Well, doesn't matter how, but the CSRF handler needs to force the body being read if it's multipart/urlencoded. This can be via a build item or a general purpose annotation like we proposed in #22444.

I've added a comment to #22444 to move the discussion along.

**Comment by sberyozkin** [comment]
@FroMage Sounds good, I can add a CSRF test once a fix to #22444 is merged

**Comment by FroMage** [comment]
The ironic thing is that with `@WithFormRead`, we can probably turn this back into a request filter.

**Comment by FroMage** [comment]
OK, it's merged. Hope it's enough to get this fixed quickly :)

**Comment by sberyozkin** [comment]
Thanks @FroMage I'll have a look soon, should be simple enough :-) (we can always migrate back to the filter if there will be a real need for it, having it as a handler right now seems OK)

**Comment by FroMage** [comment]
Well, there's no way to make a handler force the form being read. I could add it, but I'm not sure we have to, because we made this a handler precisely to bypass the limitation that I removed on filters.

**Comment by sberyozkin** [comment]
@FroMage Are you saying we have to go back to https://github.com/quarkusio/quarkus/blob/2.14.3.Final/extensions/csrf-reactive/runtime/src/main/java/io/quarkus/csrf/reactive/runtime/CsrfRequestResponseReactiveFilter.java, and add `@WithFormRead` to it ? What about this code, https://github.com/quarkusio/quarkus/blob/c78fd2ccd33cd6e28c8a4680bea72a50fd033dc6/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java#L490 ?

**Comment by sberyozkin** [comment]
Steph, may be I'm missing something, please clarify what kind of fix you expect

**Comment by FroMage** [comment]
Yes, that's what I mean, except you don't have to read the form yourself it will always be read before your filter.

**Comment by sberyozkin** [comment]
@FroMage I see what you mean, I was wondering how to access form parameters, I see it there, https://github.com/quarkusio/quarkus/pull/29825/files#diff-17360eebd1bfeec18218337a7ce737d98943bd55df9d940243051645053bd5ceR108.
