### ISSUE TITLE
 After project generated , when exec command ` ./mvnw package -Pnative -DskipTests` and  I got errors as below

### ISSUE THREAD

**Issue by guanchao-yang** [quarkusio/quarkus#2978]
**Please use StackOverflow for questions.**

This helps the community to be able to find answers to their similar issues more easily.

[Click this link to ask on StackOverflow with the "quarkus" tag](https://stackoverflow.com/questions/ask?tags=quarkus).

**Comment by geoand** [comment]
This is most likely due to the use of incorrect GraalVM version. If you are using `0.18.0` version of Quarkus, you need to have GraalVM 19.0.2 installed

**Comment by guanchao-yang** [comment]
@geoand Thanks

**Comment by geoand** [comment]
You are welcome
