### ISSUE TITLE
Ability to set multiple ExceptionMapper for different paths and provide context information

### ISSUE THREAD

**Issue by tisaksen** [quarkusio/quarkus#29796]
### Description

I have a RestClient where I have two endpoints which both return 404 with no further explanation so it's impossible to know the context of the error because a ResponseExceptionMapper does not provide any context information for the request and we can only define a 'global' ResponseExceptionMapper.

Given the snipped example:

```
@Path("/myservice")
@RegisterRestClient
@RegisterProvider(MyServiceClientExceptionMapper.class)
public interface MyServiceClient
{
    @GET
    @Path("/path/a")
    String getA();

    @GET
    @Path("/path/b")
    String getB();
}
```
Both endpoints return 404 with no further explanation in the response, there is just no way I can figure out the cause of the error and handling this in a single ResponseExceptionMapper is tedious and error prone. 

Can you provide a way to handle this, provide context of the request and a way to deal with exceptions at path level. Maybe a suitable place is ClientExceptionMapper ?

**Comment by geoand** [comment]
I don't think we'll do down the different mapper per path route, but I am pretty sure we can provide context information when using `@ClientExceptionMapper`

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/30270 adds support for using `Method` as a parameter to the method annotated with `@ClientExceptionMapper`
