### ISSUE TITLE
Clarify the situation with the Infinispan extension and the javax.annotation-api artifact

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#29801]
In Quarkus, we prefer using jakarta artifacts even for the javax packages. We need to have a look at the Infinispan extension about that.

**Comment by gsmet** [comment]
Most probably, we just need to add an exclusion and a dependency.

**Comment by karesti** [comment]
let me take this now

**Comment by gsmet** [comment]
@karesti I assigned it to me, I will take care of it.

**Comment by gsmet** [comment]
@rsvoboda I had a look today and couldn't find the javax.annotation-api artifact in the dependency tree of the Infinispan extension be it for 2.13 or main.

Could you explain how I can reproduce the issue you had?

**Comment by gsmet** [comment]
After looking at the original issue, I think it's not a problem in Quarkus and we already made the necessary adjustments in Quarkus for `javax.annotation-api` to not be around due to Infinispan.

Please reopen if not.

**Comment by rsvoboda** [comment]
Thanks for looking into this. It's more productization issue, I will update the JIRA.

I have checked the dependency tree and maven debug build log for Infinispan client extension and jakarta artifacts are enforced. javax.annotation-api is used by maven tooling (e.g. maven-plugin-api pulls javax.annotation-api 1.2).
