### ISSUE TITLE
Avoid errors on `JaxbContextCustomizer` priority order. 

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#29803]
### Describe the bug

Quarkus 2.13.4 +

Interface `io.quarkus.jaxb.runtime.JaxbContextCustomizer` allows you to customize the JAXBContext. Is possible to have more than one JaxbContext in the same application. The CDI resolution that will prioritizes one bean on the other is based on the method "priority()"

```
int DEFAULT_PRIORITY = 0;
/**
     * Defines the priority that the customizers are applied.
     * A lower integer value means that the customizer will be applied after a customizer with a higher priority
     */
    default int priority() {
        return DEFAULT_PRIORITY;
    }
```

By default if the end user doesn't override the `priority()`, then the priority is going to be set to `0`, so an other bean on this project or in a dependency with a lower priority could override the intended behavior (I am thinking about hacking or a possible vulnerability). 

For example: 

End user app

```
@Singleton
public class CustomJaxbContextCustomizer implements JaxbContextCustomizer {

    @Override
    public void customizeMarshaller(Marshaller marshaller) throws PropertyException {
        marshaller.setProperty("jaxb.formatted.output", Boolean.TRUE);
    }
}

```

Dependency
```
@Singleton
public class CustomJaxbContextCustomizer implements JaxbContextCustomizer {

    @Override
    public void customizeMarshaller(Marshaller marshaller) throws PropertyException {
        marshaller.setProperty("jaxb.formatted.output", false);
    }

    @Override
    public int priority() {
        return -1;
    }
}
```

Suggested change:
```
int DEFAULT_PRIORITY = Integer.MIN_VALUE;

Also in the compare method check "if the incoming priority is the same as the current one" and in this case be sure to give priority to the current one(I think that the current implementation is fine on this topic, but just double check). 
```

If the enduser wants to leave open the `CustomJaxbContextCustomizer`, she/he could always `Override` his priority and set it to 0.

**Comment by Sgitario** [comment]
Linked pull request https://github.com/quarkusio/quarkus/pull/29822.
I don't think this is a security risk because all the customizers are processed, but I agree with the proposed changes are better in terms of usability.

**Comment by Sgitario** [comment]
As agreed in the comments from https://github.com/quarkusio/quarkus/pull/29822, I'm closing this issue with won't fix.
