### ISSUE TITLE
ArC - improve the way a wildcard in a producer return/field type is detected

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#29836]
### Describe the bug

It seems that we don't search through the "nested" parameterized types.

Note that wildcards are not legal in a a producer return/field type. See also https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#producer_field.

This is a follow-up of https://github.com/quarkusio/quarkus/pull/4756.

### How to Reproduce?

Replace the return type of `io.quarkus.arc.processor.TypesTest.Producer.produce()`; `List<? extends Number>` -> `List<Set<? extends Number>>`

**Comment by gonciarz** [comment]
Guys, I believe that you forgot to mention about problem with Kotlin's suspend functions as Quarkus supports Kotlin.
https://github.com/quarkusio/quarkus/issues/29789

```
CDI 2.0 says about producer's definition, so I guess we should focus on a class / function definition.
The question is can we can create a smart analyzer that could detect that we deal with 
Kotlin's suspend function and we can exclude Continuation. 
It depends on a context that calls it and in theory you may inject producer to different contexts.
```
