### ISSUE TITLE
Quarkus Redis PubSub Client loses subscribers

### ISSUE THREAD

**Issue by CosminBadea1** [quarkusio/quarkus#29830]
### Description

I have a simple use case where I need to publish some Strings using ReactivePubSubCommands and subscribe to them at application start-up so that I can have a listener active for the entire app lifecycle. 

The problem is my Redis subscribers somehow disappear after some time of running on the remote environment (~2 hours). The logs don't show any error and I was not able to reproduce the issue locally. 

Running `pubsub numsub <topic>` returns 0 after the subscriber stops working

Any thoughts on what could be the route cause? From what I saw, Redis subscribers don't have any expiry time so I was expecting to have my listener be active for the entire app lifecycle. Instead, the subscriber just stops receiving new data after some time.

### Code samples:
```
ReactivePubSubCommands<String> redisPubSub = reactiveRedisDataSource.pubsub(String.class);

// Publisher
redisPubSub.publish("notifications", someStringId).subscribe().with(
                ignored -> log.info("Published id {}", someStringId),
                failure -> log.error("Failed to publish id {}", someStringId, failure));

// Subscriber
public void onStart(@Observes StartupEvent ev, ReactiveRedisDataSource redis) {
        redis.pubsub(String.class).subscribe("notifications")
                .onItem().invoke(id -> doSomethingWithTheId(id))
                .subscribe().with(
                        id -> log.info("New id has been processed {}", id),
                        err -> log.error("Error while listening for new ids ", err));
}
```

**Comment by cescoffier** [comment]
Check that the connection does not expire. Redis subscriber keeps a connection opens, the pool may get it back after some time.

**Comment by CosminBadea1** [comment]
Thanks for the response. Is there a property I can set so that the connection would stay open indefinitely?

**Comment by cescoffier** [comment]
Also, does it keep receiving data regularly? 

Are you deploying on the cloud, or on an environment where the TCP connection could be closed and recycled?

**Comment by CosminBadea1** [comment]
- Data is not necessarily received regularly. The app listens on a GCP PubSub subscription and calls the publish logic when new items arrive. 
- Deployment is done on a K8s cluster on Google Cloud

**Comment by cescoffier** [comment]
Ok, you need to make sure that it's not GCP that is closing the connection because of inactivity - I would recommend sending a "ping" message (ignored on the receiver side) every 10s.

**Comment by CosminBadea1** [comment]
Thanks a lot for the idea. I will try ASAP
