### ISSUE TITLE
Maven create app command is ignoring the version

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#29843]
### Describe the bug

Base on the Doc if I run the following command
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.6.Final:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId
```

I should be  able to create an app pointing to Quarkus 2.7.6.Final but is pointing to the latest version.
So basically the issue is that I am not able to create a Quarkus app pointing to...2.7.6.Final

### Expected behavior

The following command should create a Quarkus app pointing to Quarkus 2.7.6.Final
```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.6.Final:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId
```

### Actual behavior

The created app is always pointing to the latest version

### How to Reproduce?

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.6.Final:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId
```

### Output of `uname -a` or `ver`

Linux fedora 6.0.11-200.fc36.x86_64

### Output of `java -version`

openjdk 17.0.5 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (Red Hat 3.8.4-3)

**Comment by gsmet** [comment]
@aloubyansky I know we discussed that several times but I don't remember the outcome.

**Comment by pjgg** [comment]
Sorry is my fault! this is the right way to setup the platform version

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.6.Final:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId -DplatformVersion=2.7.6.Final
```

As you can see on the [Doc](https://quarkus.io/guides/maven-tooling#project-creation)
