### ISSUE TITLE
Ability to set ingressClassName

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#29858]
### Description

It would be convenient and helpful to be able to set the `ingressClassName` on generated Kubernetes manifests.  

Currently, we use the Quarkus Helm Extension to templatize that as a Helm chart _but_ it does not add new properties only augments existing one.  We work around this by having a `/kubernetes/ingress.yml` with just that property now.

This would help us in adopting the new ingress rules that can be set in the application.yml and remove the need for an additional configuration resource.

**Comment by Sgitario** [comment]
This needs to be done first in Dekorate: https://github.com/dekorateio/dekorate/pull/1111

**Comment by kjq** [comment]
Hah, thanks for telling me - i was excited to pull down the codebase and try my hand at a PR.

**Comment by Sgitario** [comment]
@kjq, after the mentioned pull request is merged, if you are interested in working on this, go ahead! :)

**Comment by Sgitario** [comment]
FYI, @kjq , I've already provided a fix for this issue: https://github.com/quarkusio/quarkus/pull/30007

**Comment by kjq** [comment]
@Sgitario - Thanks!  It looks like I was on the right track comparing my changes to yours, i'll be ready now next time at least to submit a PR.

**Comment by Sgitario** [comment]
Great!!
