### ISSUE TITLE
OpenTracing JaxRs Client Async Starting new Trace

### ISSUE THREAD

**Issue by snsbe** [quarkusio/quarkus#2985]
**Describe the bug**
When using JaxRS Client to call out using `.rx()`, there is started a new trace instead continue existing.

Tried also adding `TracedExecutorService`, without any success.
```java
new ResteasyClientBuilderImpl()
                .executorService(new TracedExecutorService(Executors.newSingleThreadExecutor(), tracer))
```
**Expected behavior**
Expected to continue existing trace, with new spans.

**Actual behavior**
A completely new trace is started.

**To Reproduce**
I have created a repo to reproduce the error [https://github.com/snsbe/opentracing-jaxrs-client-rx](https://github.com/snsbe/opentracing-jaxrs-client-rx).

There is a junit test for both sync and async.

**Configuration**
Take a look at the project link above.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.16299.1217]
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - Quarkus version or git rev: 0.17.0

**Comment by kenfinnigan** [comment]
I don't believe the JAX-RS Client has any built-in functionality for propagating trace span headers from incoming to outgoing request.

If you want that behavior, you need to use the REST Client: https://quarkus.io/guides/rest-client-guide

**Comment by snsbe** [comment]
It's working when do synchronous call, with a client .registered with the `ClientTracingFeature`.

**Comment by snsbe** [comment]
For the Resteasy 3, there is some doc here [https://github.com/opentracing-contrib/java-jaxrs#resteasy](https://github.com/opentracing-contrib/java-jaxrs#resteasy)

**Comment by kenfinnigan** [comment]
Though you've included the `smallrye-rest-client` into your project, you're still using the JAX-RS Client only.

If you switch to using the SmallRye REST Client, I believe that works for synchronous or asynchronous calls. As `smallrye-opentracing` registers asynchronous tracers into the REST Client

**Comment by snsbe** [comment]
It looks likes it's possible to do something like this:
```java
ClientBuilder
                .newBuilder()
                .executorService(new TracedExecutorService(Executors.newSingleThreadExecutor(), tracer))
                .register(new SmallRyeClientTracingFeature(tracer))
                .build()
```
But what is the correct way to get the `ExecutorService`?

**Comment by kenfinnigan** [comment]
To use Asynchronous with the REST Client you would define an interface to the external service:

```
@Path("/name")
public interface NameService {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public CompletionStage<String> name() {
        return "name";
    }
}
```

Notice the use of `CompletionStage` as a return type, which indicates we want an asynchronous response.

Then you would use it as:
```
RestClientBuilder.newBuilder()
            .baseUri("SomeURL to NameService")
            .build(NameService.class);
```

Tracing and ExecutorService should be completely hidden.

https://download.eclipse.org/microprofile/microprofile-rest-client-1.3.2/microprofile-rest-client-1.3.2.html contains further information on how to use the MP REST Client

**Comment by gsmet** [comment]
@kenfinnigan do you know what the status of that one is with the switch to RESTEasy for the client?

**Comment by kenfinnigan** [comment]
I think this was raised after we began using RESTEasy.

I believe it's not a problem
