### ISSUE TITLE
All guides throw 404 on the website

### ISSUE THREAD

**Issue by imperatorx** [quarkusio/quarkus#29878]
### Describe the bug

As title says

### Expected behavior

Guides show up

### Actual behavior

Guides throw 404 e.g. https://quarkus.io/version/latest/guides/building-native-image

**Comment by imperatorx** [comment]
![img](https://user-images.githubusercontent.com/10324575/207823989-8e81b312-9bfe-41e9-aeeb-a37b49e0de23.png)

**Comment by mkouba** [comment]
This problem should be fixed with https://github.com/quarkusio/quarkusio.github.io/commit/b3971d680e7e4588d866690983c63544728c186d.

**Comment by mkouba** [comment]
The site was fixed. The correct link to the latest `Building a Native Executable` is https://quarkus.io/guides/building-native-image.
