### ISSUE TITLE
Many of the links of guides/mutiny-primer is broken.

### ISSUE THREAD

**Issue by ssetoredhat** [quarkusio/quarkus#29895]
**Describe the bug**
Many of the links to Mutiny documentation are 404 not found.
like:
https://smallrye.io/smallrye-mutiny/pages/philosophy
https://smallrye.io/smallrye-mutiny/getting-started/transforming-items
https://smallrye.io/smallrye-mutiny/getting-started/transforming-items-async
https://smallrye.io/smallrye-mutiny/getting-started/handling-failures

**Which pages**
https://quarkus.io/guides/mutiny-primer

**Comment by gsmet** [comment]
I moved the issue to the main Quarkus repository as we will need to fix things here.

**Comment by jponge** [comment]
Noted, I will check

**Comment by jponge** [comment]
I found some minor link issues, but all links for `mutiny-primer.adoc` are correct.
Also see https://quarkus.io/guides/mutiny-primer, all links are correct.

@ssetoredhat Are you using older docs?
