### ISSUE TITLE
Unable to start devservices for MariaDB

### ISSUE THREAD

**Issue by oaklandcorp-jkaiser** [quarkusio/quarkus#29891]
### Describe the bug

The [Dev Services for Databases guide](https://quarkus.io/guides/databases-dev-services) suggests that MariaDB has dev services available but I've been unable to get them working. When I use the config `quarkus.datasource.db-kind=mariadb` I'm unable to start database dev services. [An issue](https://stackoverflow.com/questions/71071989/how-to-use-mariadb-devservices-on-quarkus-tests) on StackOverflow seems to have discovered the same issue I'm having back in Quarkus 2.4.

### Expected behavior

When using `quarkus.datasource.db-kind=mariadb` and `quarkus.datasource.devservices=true` the [MariaDB TestContainer](https://www.testcontainers.org/modules/databases/mariadb/) should be started when dev mode or tests are run.

### Actual behavior

```
Unable to start devservices for default datasource as this datasource type (mariadb) does not support devservices
```

### How to Reproduce?

1. Use https://code.quarkus.io/ to create a project with Hibernate Rx
2. Add `quarkus.datasource.db-kind=mariadb` to `application.properties`
3. Run `./mvnw quarkus:dev`

### Output of `uname -a` or `ver`

Linux 5.15.0-56-generic

### Output of `java -version`

openjdk version "17.0.4"

### Quarkus version or git rev

2.15.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by gsmet** [comment]
This is specific to using the Reactive stack. We don't promote the MariaDB dev service for reactive as we don't have an actual MariaDB reactive driver.

My understanding is that the Reactive MySQL Client supports both MySQL and MariaDB so we should make it work.

https://vertx.io/docs/vertx-mysql-client/java/#_mysql_and_mariadb_version_support_matrix

I'll go do that.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/29894 should fix it.
