### ISSUE TITLE
OpenAPI: RESTEASY003210 issue with @ApplicationPath("")

### ISSUE THREAD

**Issue by jmini** [quarkusio/quarkus#2991]
I am not a JAX-RS expert, but I think that `@ApplicationPath("")` and `@ApplicationPath("/")` are the same.

Javadoc for `String value();` in `@ApplicationPath`:

> Defines the base URI for all resource URIs. A trailing '/' character will be automatically appended if one is not present.

If this is correct you can continue to read this issue.

---

**Describe the bug**
When using `@ApplicationPath("")` the OpenAPI specification is not served.

**Expected behavior**
```
GET http://localhost:8080/openapi
```

Returns a Yaml OpenAPI.

**Actual behavior**
```
GET http://localhost:8080/openapi
```

Returns:

```
RESTEASY003210: Could not find resource for full path: http://localhost:8080/openapi
```

**To Reproduce**
1. Create a simple project with `[cdi, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]`
2. Create 2 simple classes:
```java
package com.example.openapi;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("")
public class RestApplication extends Application {
}
```

```java
package com.example.openapi;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import java.io.InputStream;
import java.util.Map;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

@Path("/ping")
public class PingApi {

    @GET
    public Response pingGet() {
        return Response.ok().entity("magic!").build();
    }
}
```
3. Open http://localhost:8080/openapi

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 0.17.0

**Comment by gsmet** [comment]
I think this issue will be fixed by https://github.com/quarkusio/quarkus/pull/3161 .

Could you check, either using master or with 0.19.0 when it's released.

Thanks!

**Comment by jmini** [comment]
I will do, thank you!

**Comment by stuartwdouglas** [comment]
This is definitely the same issue.
