### ISSUE TITLE
rest client can`t establish connection in native mode when you use virtual thread 

### ISSUE THREAD

**Issue by wssy001** [quarkusio/quarkus#29910]
### Describe the bug

I found that：<br>
 if you use restClient in this way
```java
@Inject
@RestClient
ApiService apiService;

private final ExecutorService executorService = Executors.newVirtualThreadPerTaskExecutor();

private void executeWithVirtualThread(){
    executorService.execute(()->apiService.sendHello());
}
```
rest client can`t connect to target http server  and  there is no log like  that in terminal
```shell
DEBUG [org.apa.htt.imp.con.DefaultHttpClientConnectionOperator] (executor-thread-0) Connection established 192.168.123.73:55777<->192.168.123.73:5700
```

but if you use rest client whitout virtual thread , everything is worked

the same issue also exists in <code>StructuredTaskScope</code>

### Expected behavior

in native mode , rest client should establish connection when you use virtual thread 

### Actual behavior

 rest client establishes connection failed

### Output of `uname -a` or `ver`

Darwin AlexdeAir.lan 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

### Output of `java -version`

```shell
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)
```

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by wssy001** [comment]
> Does it work in JVM mode? 

 it works in JVM Mode and Native mode without using  <code>VirtualThreadPerTaskExecutor</code> or <code>StructuredTaskScope</code><br>

how about this case，I tested , it did not work only in native mode (<code> StructuredTaskScope</code> didn`t work too)
```java
@RunOnVirtualThread
public class Test{
   @Inject
   @RestClient
   ApiService apiService;

   private final ExecutorService executorService = Executors.newVirtualThreadPerTaskExecutor();

   private void executeWithVirtualThread(){
       executorService.execute(()->apiService.sendHello());
   }
}
```

**Comment by cescoffier** [comment]
Ok, so it does work in jvm mode. So probably something in the native implementation of virtual threads.

**Comment by cescoffier** [comment]
\CC @zakkak

**Comment by zakkak** [comment]
@wssy001 can you please provide a complete reproducer including how you compile and run it?

**Comment by zakkak** [comment]
Hi @wssy001 ,

The project doesn't seem to compile. It first complained about `TestController` being defined in `TestController2.java`, but even after renaming the class I am getting:

```
src/main/java/controller/TestController2.java:[70,45] cannot find symbol
  symbol:   method testApi()
  location: variable testRestApi of type api.TestRestApi
```

Can you please have a look?

**Comment by zakkak** [comment]
Thank you @wssy001 it now builds fine, but it's still not clear to me how to replicate the issue. 

Please provide clear instructions on how to test (how to start the app and what requests to send) and what's the expected behavior.

**Comment by wssy001** [comment]
@zakkak  
instructions:
sorry for Windows users

1. Run command ` mvn clean package -Dmaven.test.skip=true -Dnative ` to build an native image
2. Run command `./target/restclient-vt-test-1.0-SNAPSHOT-runner` to run native image
3. Be sure that the native image works fine
4. send the following GET Requests and check console log

```shell
GET  http://localhost:8080/test/normal
GET  http://localhost:8080/test/pool
GET  http://localhost:8080/test/structuredTaskScope
GET  http://localhost:8080/test/vtThread

GET http://localhost:8080/test/underRunOnVirtualThread/normal
GET http://localhost:8080/test/underRunOnVirtualThread/pool
GET http://localhost:8080/test/underRunOnVirtualThread/structuredTaskScope
GET http://localhost:8080/test/underRunOnVirtualThread/vtThread
```

if you run on JVM Mode , everything will be fine .
As for me, only in "normal" endpoints ("/test/underRunOnVirtualThread/normal" and "/test/normal") can the rest client establish connection and get JSON data back .

**Comment by zakkak** [comment]
I gave this a try with graal `master` and JDK 20 and it works as expected, so it looks like the issue is fixed upstream (by https://github.com/oracle/graal/pull/5656) and will land in the next GraalVM release.

In the meantime, once a new build (that will include the above PR) gets published on https://github.com/graalvm/graalvm-ce-dev-builds/releases/ you will be able to test it yourself without having to build GraalVM from `master`.
