### ISSUE TITLE
Files in multipart form are null

### ISSUE THREAD

**Issue by kyngs** [quarkusio/quarkus#29945]
### Describe the bug

I have the following Java code:
```java
    @Path("create")
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.WILDCARD)
    public void create(@RestForm("sale") boolean forSale, @RestForm("type") String type, @RestForm("photo") FileUpload photo) {
        System.out.println(photo.uploadedFile());
    }
```

And the following JS code:
```js
        const data = new FormData();
        data.append("type", newType);
        data.append("sale", forSale.toString())
        data.append("photo", file)

        let response = fetch("<redacted>/create", {
            method: "POST",
            body: data,
        }).then(() => {
            refreshCallback();
        });
```

The request sent from the client:

```
POST <redacted>/create HTTP/1.1
Host: localhost:8069
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:8069/<redacted>
Content-Type: multipart/form-data; boundary=---------------------------14145789041259461299383314053
Content-Length: 426
Origin: http://localhost:8069
Connection: keep-alive
Cookie: session="dmAeXiWyujy/VoNixfloOPKyRel+K8nNd+/FPU43OQ=="
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache

-----------------------------14145789041259461299383314053
Content-Disposition: form-data; name="type"

test
-----------------------------14145789041259461299383314053
Content-Disposition: form-data; name="sale"

true
-----------------------------14145789041259461299383314053
Content-Disposition: form-data; name="photo"

C:\fakepath\4631466951_1.jpg
-----------------------------14145789041259461299383314053--

```

When the request is handled by the server, the FileUpload field photo is null.

### Expected behavior

All fields should have values

### Actual behavior

The FileUpload field "photo" is null. 

### How to Reproduce?

Use the snippets in the description to reproduce.

### Output of `uname -a` or `ver`

Linux dada 6.0.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:40 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+1) OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

### GraalVM version (if different from Java)

Not applicable

### Quarkus version or git rev

2.14.2.Final also on 2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.5.1 ------------------------------------------------------------  Build time:   2022-08-05 21:17:56 UTC Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918  Kotlin:       1.6.21 Groovy:       3.0.10 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.5 (Oracle Corporation 17.0.5+1) OS:           Linux 6.0.12-zen1-1-zen amd64

### Additional information

Maybe this could be related to #27215

**Comment by geoand** [comment]
Can you give `2.15.0.Final` a try please?

**Comment by kyngs** [comment]
> Can you give `2.15.0.Final` a try please?

Hi, thanks for the response, unfortunately the issue persists with 2.15.0.Final

**Comment by geoand** [comment]
Can you please attach a sample application that exhibits the problematic behavior? It will allow us to more easily identify the issue  and have a test for it

**Comment by kyngs** [comment]
Oh no, this is quite embarrassing.

I've sent the file path on the front end, not the file itself. Now when sending the file, it works correctly. Thanks for your time and work.

**Comment by geoand** [comment]
Thanks for the update :)
