### ISSUE TITLE
QUARKUS_TEST_PROFILE env variable is not honored

### ISSUE THREAD

**Issue by siudeks** [quarkusio/quarkus#29944]
### Describe the bug

Issue:
Can't change test profile using environmente variable *QUARKUS_TEST_PROFILE*, as described at https://quarkus.io/guides/continuous-testing#quarkus-test-dev-testing-test-config_quarkus.test.profile

Reproduction:

Actual:
```
Green test: *mvn clean test -Dquarkus.test.profile=my_profile*
Red test: *QUARKUS_TEST_PROFILE=my_profile mvn clean test*
```

Expected:
```
Green test: *mvn clean test -Dquarkus.test.profile=my_profile*
Green test: *QUARKUS_TEST_PROFILE=my_profile mvn clean test*
```

### Expected behavior

See 'Describe the bug'

### Actual behavior

See 'Describe the bug'

### How to Reproduce?

https://github.com/siudeks/repro/tree/quarkus-test-profile

### Output of `uname -a` or `ver`

Linux PC1 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java 17

### Quarkus version or git rev

maven

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
Thanks for spotting this. 

https://github.com/quarkusio/quarkus/pull/29951 should take care of it

**Comment by geoand** [comment]
It turns out that `main` has already fixed the issue with https://github.com/quarkusio/quarkus/pull/28091
