### ISSUE TITLE
Hibernate reactive disregarding quarkus.hibernate-orm.jdbc.timezone

### ISSUE THREAD

**Issue by agreedSkiing** [quarkusio/quarkus#29956]
### Describe the bug

I have the last couple of days been trying to understand why my code does not consider `TIMESTAMP WITH TIME ZONE` in my main postgresSQL application that uses hibernate reactive so I created two smaller applications to test just test how hibernate-orm and hibernate-reactive work in quarkus with time zones.

First of I tried hibernate reactive and stumbled across the issue listed in #10768 on my own whilst running my `@QuarkusIntegrationTest` and `@QuarkusTest` and then changed my approach to use the normal “jdbc driver” to get flyway working to have it more like main PostgreSQL project. After the jdbc change I once of my test suits with `quarkus.hibernate-orm.jdbc.timezone` set to `UTC` with no effect whilst always running with `user.timezone=Etc/GMT-1` to simulate a consistent time zone, but neither of these settings helped ☹. So after that I created a `user.timezone=UTC` test which works since now both my postgres container and quarkus application now run in UTC. 

So then does it work in the normal quarkus hibernate-orm implementation? Well yeah everything works fine there when having `quarkus.hibernate-orm.jdbc.timezone` set to `UTC`.

P.S. One thing I forgot to comment about in my findings is the code that converts a `TIMESTAMP WITH TIME ZONE` from a database field (that is stored in postgres as UTC) to UTC again without taking into regard the time zone part of the original value in the database before converting it to the java object with the user.timezone so… the conversion loses one hour in my GmtIT.java tests… 👏🎉🧨😂. But this is releated to the other issue that has already been created.

P.S.S. Create a branch in the hibernate reactive application with no flyway.

### Expected behavior

quarkus.hibernate-orm.jdbc.timezone works according to specificaiton and can take into account database timezone when converting

### Actual behavior

Does nothing application boot timezone is used for all convertion of date and time

### How to Reproduce?

Github repos with my test code:
- [hibernate-reactive repo](https://github.com/agreedSkiing/test-hibernate-reactive-timezone-postgres)
- [hibernate-orm repo]( https://github.com/agreedSkiing/test-hibernate-timezone-postgres)

### Output of `uname -a` or `ver`

Linux DI-001000104447 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191) Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gsmet** [comment]
@agreedSkiing I created https://github.com/quarkusio/quarkus/pull/29981 but I have no idea if it will actually fix your issue :).

**Comment by gsmet** [comment]
Reopening this one as IIUC there's more to it.

**Comment by Sanne** [comment]
@gsmet , @agreedSkiing let's remember that Hibernate Reactive does not use JDBC at all and this is specificcally tied to the JDBC driver layer: I wouldn't expect this to work.

That said, we should make this much clearer; perhaps log some warnings if such JDBC settings are being set rather than silently ignoring them - or perhaps fail fast with a more visile error. cc/ @DavideD should we raise this as an improvement on HR ?

**Comment by agreedSkiing** [comment]
@Sanne true it uses the `vertx-reactive:postgresql` datasource connection instead, but aren’t most of the propriety names just reusing legacy names for easier conversion or something like that?

**Comment by DavideD** [comment]
> That said, we should make this much clearer; perhaps log some warnings if such JDBC settings are being set rather than silently ignoring them - or perhaps fail fast with a more visile error. cc/ @DavideD should we raise this as an improvement on HR ?

If we don't support them, it's probably better to just fail. That said, this option (`quarkus.hibernate-orm.jdbc.timezone`) is actually used in Hibernate Reactive. I have  a unit test that fails depending on if we set it or not. But I haven't had the time to check exactly what's going on.

**Comment by agreedSkiing** [comment]
@gsmet Thanks for the fix 👍 that solved the missing property :).
