### ISSUE TITLE
Issue using keycloak admin client

### ISSUE THREAD

**Issue by heineson** [quarkusio/quarkus#29958]
### Describe the bug

When using the Keycloak Admin Client by following the steps in https://quarkus.io/guides/security-keycloak-admin-client I get 
`ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of SYNTHETIC bean [class=org.keycloak.admin.client.Keycloak, id=1fb0e5144418a307281a16ae5d071d5d262b7891]`
when using an `@Injected` client. Easy to workaround by creating the client manually as also shown in the guide.

So my question is probably: Is the guide not working (due to written too long ago perhaps?) or is there a bug somewhere in the quarkus libraries?

### Expected behavior

That the code in https://quarkus.io/guides/security-keycloak-admin-client works when instructions are followed.

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gsmet** [comment]
Could you attach a zip with the version not working so that we can have a look? Thanks!

**Comment by sberyozkin** [comment]
The test is here:
https://github.com/quarkusio/quarkus/blob/main/integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java#L41
https://github.com/quarkusio/quarkus/blob/main/integration-tests/keycloak-authorization/src/main/java/io/quarkus/it/keycloak/AdminClientResource.java#L29

**Comment by heineson** [comment]
Hello! Thanks for replying. 
As you can imagine, of course this is because of an error on my side. So, if I forget to set the property `quarkus.keycloak.admin-client.server-url` in application.properties, then it will fail with `ContextNotActiveException`. If the property is present, it will not. However, consider this as an improvement request for a better error message in case someone makes similar mistakes!

**Comment by geoand** [comment]
This has already been fixed in https://github.com/quarkusio/quarkus/pull/29772
