### ISSUE TITLE
Global test resouce keeps restarting after `2.15.0` upgrade

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#29979]
### Describe the bug

After the upgrade to `2.15.0` we have seen that our integration tests are starting and stopping the defined `@QuarkusTestResource` after each test class is being processed. Before the resource was started only once and all tests were run against it.. No Quarkus test profile is defined.. 

This makes the complete behavior different and increases our CI time to app 25:00 mins from a nice 3:30 that we had before. The `integration-test` maven goal gets also very unstable, for example we are seeing smth like: `Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"}`.

The test resource is defined as simple as:

```
@QuarkusIntegrationTest
@QuarkusTestResource(StargateTestResource.class)
```

We are using a lot of `@Nested` annotations and seems like the restart is there for every single nested class defined. Could be related to that.

If needed I can create a quick reproducer.

### Quarkus version or git rev

2.15.0

**Comment by geoand** [comment]
This is already fixed in `main` by #2994, right @Sgitario ?

@ivansenic would you be able to test it?

**Comment by ivansenic** [comment]
> This is already fixed in `main` by #29774, right @Sgitario ?
> 
> @ivansenic would you be able to test it?

Sure give me an hour..

**Comment by ivansenic** [comment]
@geoand Confirming that `main` already contains a fix for this. And closing.

**Comment by geoand** [comment]
Thanks for checking!

**Comment by ivansenic** [comment]
Any idea when `2.15.1` will be out?

**Comment by geoand** [comment]
It's already out 😉
