### ISSUE TITLE
OTel `LateBoundSampler` logs warning if using Liquibase and JDBC instrumentation

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#29987]
### Describe the bug

I was irritated by the following message very early during boot and started digging:
```
WARN  [io.qua.ope.run.tra.LateBoundSampler] (JPA Startup Thread) No Sampler delegate specified, no action taken.
```
Turns out that when you have [JDBC instrumentation](https://quarkus.io/guides/opentelemetry#jdbc) _and_ Liquibase migration at startup (using the same datasource and OTEL driver as the rest of the app), the sampler is apparently not set yet, hence the warning.

### Expected behavior

No warning from OTEL extension, even if using "startup time features" such as the liquibase extension.

### Actual behavior

Warning logged

### How to Reproduce?

[liquibase-quickstart-with-otel.zip](https://github.com/quarkusio/quarkus/files/10280148/liquibase-quickstart-with-otel.zip)

`mvn quarkus:dev`

### Quarkus version or git rev

2.15.0.Final

### Additional information

`LateBoundBatchSpanProcessor` issues a similar warning (if otlp export is not disabled).

Of course it doesn't make much sense to trace liquibase JDBC operations, but simply using the regular app datasource is the default setup for simple cases.

**Comment by famod** [comment]
I think this has more to do with tracing, cc @brunobat @radcortez

**Comment by brunobat** [comment]
Hi @famod can you please provide a reproducer?

**Comment by famod** [comment]
Hi @brunobat, I added a reproducer. AFAICS, this issue is not specific to dev mode, but it was the fastest way to reproduce.

The reproducer is basically identical to the official liquibase quickstart, only with two added OTel deps and two additional config settings.

**Comment by brunobat** [comment]
Thanks very much @famod

**Comment by geoand** [comment]
In more recent versions of Quarkus, the warning is always displayed when OpenTelemetry is used (regardless of what other extension or configuration are used).

I am looking into a fix

**Comment by geoand** [comment]
[Here](34545) it is.
