### ISSUE TITLE
Offer a JNIBuildItem to let extensions enable JNI

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2999]
See https://groups.google.com/d/topic/quarkus-dev/pLwbEB1VCP0/discussion for the conversation

**Comment by dmlloyd** [comment]
Related: https://groups.google.com/d/topic/quarkus-dev/qJCKz-CU3RU/discussion

**Comment by Dufgui** [comment]
quarkusio/quarkus-quickstarts#235
I can continue on it ? Are you ok with my quickstart/integration test case ?

**Comment by dmlloyd** [comment]
I think that we're going to want to get the native image extension work underway first (see #3013).

**Comment by emmanuelbernard** [comment]
I don't know, is the native image extension planned for soon? The JNI thing
seems relatively easy to squeeze in a week.

**Comment by dmlloyd** [comment]
Is it?  It didn't seem easy to me, but that might be due to my familiarity (or lack thereof) with the current build phase system and the way it integrates with Maven/Gradle.

**Comment by emmanuelbernard** [comment]
I was thinking it would look like SslNativeConfigBuildItem but I did not
evaluate further.

**Comment by gsmet** [comment]
Yeah, it's a hack that was present before and I refined for the SSL native support.

Basically, we push properties to the `native-image.properties` file which is read in `NativeImagePhase` (see https://github.com/quarkusio/quarkus/blob/master/core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java#L384 ).

So, while having native image build as an extension is definitely more future proof, we could probably use this machinery temporarily to fix this one (and https://github.com/quarkusio/quarkus/issues/3014 while we're at it).

**Comment by Dufgui** [comment]
I do the code just by following what SSL native do. Now I will think about what must really done to work and test it ;o)

**Comment by emmanuelbernard** [comment]
oops
