### ISSUE TITLE
hibernate-search-orm-elasticsearch fail in multi-module projects

### ISSUE THREAD

**Issue by alexeysharandin** [quarkusio/quarkus#30004]
### Describe the bug

TC:
1. create multi module maven project.
2. Put domain model to my-common with some item like
```java
@Entity
@Indexed
public class MyClass extends PanacheEntityBase {
    @Id
    @SequenceGenerator(
            name = "my_sequence",
            sequenceName = "my_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "my_sequence")
    Long id;

    @Column(nullable = false)
    @FullTextField(analyzer = "name")
    @KeywordField(name = "name_sort", sortable = Sortable.YES, normalizer = "sort")
    String name;
}
```
and add dependency to ```quarkus-hibernate-search-orm-elasticsearch```

3. Create other module with main application and controller and include p.2 dependency to one
4. In application properties define ```quarkus.hibernate-search-orm.elasticsearch.version=7``` 

try to compile

### Expected behavior

ER: project will compile and work fine

### Actual behavior

Get error:
```
[INFO] my-parent ......................................... SUCCESS [  0.094 s]
[INFO] my-frontend ....................................... SUCCESS [01:02 min]
[INFO] my-common ......................................... FAILURE [  8.647 s]  <-- @Entity hete
[INFO] my-test ........................................... SKIPPED
[INFO] my-backend ........................................ SKIPPED <-- application.properties here
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2022-12-21T13:45:34+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.12.3.Final:build (default) on project my-common: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.hibernate.search.orm.elasticsearch.deployment.HibernateSearchElasticsearchProcessor#processPersistenceUnitBuildTimeConfig threw an exception: io.quarkus.runtime.configuration.ConfigurationException: The Elasticsearch version needs to be defined via properties: quarkus.hibernate-search-orm.elasticsearch.version.
[ERROR]         at io.quarkus.hibernate.search.orm.elasticsearch.deployment.HibernateSearchElasticsearchProcessor.processPersistenceUnitBuildTimeConfig(HibernateSearchElasticsearchProcessor.java:280)
[ERROR]         at io.quarkus.hibernate.search.orm.elasticsearch.deployment.HibernateSearchElasticsearchProcessor.processPersistenceUnitBuildTimeConfig(HibernateSearchElasticsearchProcessor.java:243)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

### How to Reproduce?

Root cause (after my quick search):
Hibernate search validate property at build time in the same module and fail - https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-search-orm-elasticsearch/deployment/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/deployment/HibernateSearchElasticsearchProcessor.java

In the reality config exist in the real application.

BTW: maybe make sense to 

### Output of `java -version`

jdk 11 (graal)

### Quarkus version or git rev

2.12.3.Final (but will be reproduced in any)

### Additional information

w/a at this moment:
in my-common module remove:
```
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-search-orm-elasticsearch</artifactId>
</dependency>
```
and add ORM and annotations directly:
```
         <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
 <dependency>
            <groupId>org.hibernate.search</groupId>
            <artifactId>hibernate-search-mapper-orm</artifactId>
            <exclusions>
                <!-- We use Jakarta Persistence artifacts instead -->
                <exclusion>
                    <groupId>javax.persistence</groupId>
                    <artifactId>javax.persistence-api</artifactId>
                </exclusion>
                <!--
                The activation implementation is coming from the quarkus-hibernate-orm extension.
                The implementation contains the API.
                -->
                <exclusion>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

dependency to 
```
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-search-orm-elasticsearch</artifactId>
</dependency>
```

will be added only in module with controller.

@yrodiere maybe make sense to separate it in quarkus level(like add quarkus-hibernate-search-orm-elasticsearch-spi) and update docs?

**Comment by yrodiere** [comment]
Naive question: I wonder why you need to execute `quarkus-maven-plugin` in your common module? I thought that plugin was supposed to build a Quarkus application, so it wouldn't generally be used in libraries (which is, in truth, what your common module is).

If your problem is Quarkus not detecting your entities, try applying the Jandex plugin instead of the Quarkus plugin in your common module. More information [here](https://quarkus.io/guides/maven-tooling#multi-module-maven).

As to this:

> @yrodiere maybe make sense to separate it in quarkus level(like add quarkus-hibernate-search-orm-elasticsearch-spi) and update docs?

I'm a bit reluctant, because that's opening the door to doing the same in about every single extension out there. Also I wouldn't call it spi, because it's not an SPI, at least not how we define it in Hibernate/Quarkus.

**Comment by yrodiere** [comment]
Hey @alexeysharandin , did you try *not* executing `quarkus-maven-plugin` in your common module?

> Naive question: I wonder why you need to execute `quarkus-maven-plugin` in your common module? I thought that plugin was supposed to build a Quarkus application, so it wouldn't generally be used in libraries (which is, in truth, what your common module is).

**Comment by alexeysharandin** [comment]
@yrodiere , please close this issue. You was right with pom configuration.

**Comment by yrodiere** [comment]
Thanks for the feedback!
