### ISSUE TITLE
@QuarkusIntegrationTest Log File Retention

### ISSUE THREAD

**Issue by watermelonjam** [quarkusio/quarkus#30009]
### Description

`@QuarkusIntegrationTest` classes that launch a container for each `@Test` use `DefaultDockerContainerLauncher.start` to send container output to `Path logFile = PropertyTestUtil.getLogFilePath()`, which is helpful... but it gets truncated at the start of every test by `Files.deleteIfExists(logFile)`.

Suspending tests interactively can facilitate manual log inspection, but ultimately that log output should _all_ be retained at the end of mvn verify to support CI/CD pipelines where developers will need to consult container output to diagnose integration test failures.

### Implementation ideas

A system property that allows `DefaultDockerContainerLauncher.start` to skip log file truncation would do the trick, I think.  For my use case, an option to set `ProcessBuilder().inheritIO()` would also be handy.

**Comment by geoand** [comment]
> but it gets truncated at the start of every test

This isn't actually the case. The file only gets truncated when the application needs to get relaunched.

I do see the usefulness of this idea however. The problem is that we actually need that log file to determine if the process started correctly, so if we do no truncate it, things will get messed up.
I am wondering however if we can have a different file that contains the logs of all runs.

**Comment by watermelonjam** [comment]
> The file only gets truncated when the application needs to get relaunched

Fair enough.  In my case, it's a `@QuarkusIntegrationTest` annotated with `@TestHTTPEndpoint` and it's starting a new container for every test method.  I'll need to figure out why on my own.  Still, multiple container starts are possible in many real-world integration test scenarios.

Would it be possible to use 

```
Process quarkusProcess = new ProcessBuilder(args).redirectError(java.lang.ProcessBuilder.Redirect.PIPE).redirectOutput(java.lang.ProcessBuilder.Redirect.PIPE).start();
InputStream quarkusProcessStream = quarkusProcess.getInputStream();
```

with something like the commons-io `TeeInputStream` to ensure Quarkus can read startup info from its expected location while also streaming the container output to a more durable destination?  Managing the life-cycle of those streams in a way that is acceptable to everything else Quarkus might be doing with container launches is, unfortunately, beyond me.

**Comment by geoand** [comment]
It's certainly something worth considering

**Comment by watermelonjam** [comment]
Took a stab at it in [PR 30063](https://github.com/quarkusio/quarkus/pull/30063).  Using `Redirect.PIPE` makes `DefaultDockerContainerLauncher` responsible for managing the I/O, so I used the least intrusive method I know of for doing that.
