### ISSUE TITLE
`@LookupIfProperty` does not work for JAX-RS REST resources

### ISSUE THREAD

**Issue by cowtowncoder** [quarkusio/quarkus#30022]
### Describe the bug

We have a use case where in one of REST resources (endpoints) should be dynamically included, only if specific system property has specific value: if not included it should neither be accessible nor visible via OpenApi/Swagger ui etc.

This seems like exact use case for `@LookupIfProperty` annotation. It does not, however, look like this annotation is considered when registering endpoints: as far as I can see it will get added regardless of annotation setting.

It is possible that I have misunderstood the scope, or intent. It also seems possible that if there is an issue it might be with other components (RESTeasy). But I thought I should start somewhere and I hope this is a reasonable starting point.

### Expected behavior

Depending on `@LookupIfProperty` annotation and system properties (and equivalents) passed, end point annotated would either included as usual, or excluded, as per annotation's documented behavior for injectable beans.

### Actual behavior

It looks like `@LookupIfProperty` is ignored wrt registering of JAX-RS endpoints, at least at class level (I haven't tried it on endpoint methods -- will do it next).

### How to Reproduce?

Defining resource similar to:

```
@ApplicationScoped
@Path("/v2/adminui")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.TEXT_PLAIN)
@SecurityRequirement(name = RestOpenApiConstants.SecuritySchemes.TOKEN)
@LookupIfProperty(name = "ourapi.admin.enabled", stringValue = "true", lookupIfMissing = false)
public class AdminUIResource {
}
```

and running without specifying `ourapi.admin.enabled=true` will include resource although it should not (if I understand expected DI behavior).

### Output of `uname -a` or `ver`

20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 LTS OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS) OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

**Comment by famod** [comment]
I don't think `LookupIfProperty` is the right choice because you are not looking up the resource "programmatically" via `Instance`.

`@IfBuildProperty` will work just fine, but that's obviously only evaluated at build time, not runtime.

/cc @mkouba

**Comment by cowtowncoder** [comment]
@famod Ok. I was afraid it might be that way. From user perspective it seemed like a possibility at a high level.

Good to know about `@IfBuildProperty` but you are correct in that it won't quite do what I am trying to achieve.

I hope someone might have other ideas of how to achieve this; googling was unable to point to anything obvious (although TBH I did not find `@LookupIfProperty` either so my search-fu is lacking).

**Comment by geoand** [comment]
I agree with @famod. The use case described here is a better match for `@IfBuildProperty`. `@LookupIfProperty` is meant to be used with `Instance` CDI injection.

**Comment by mkouba** [comment]
> I hope someone might have other ideas of how to achieve this; googling was unable to point to anything obvious (although TBH I did not find `@LookupIfProperty` either so my search-fu is lacking).

https://quarkus.io/guides/cdi-reference#declaratively-choose-beans-that-can-be-obtained-by-programmatic-lookup ;-)

There's no way to dynamically include/exclude beans at runtime. Quarkus does resolve all injection points (dependencies) at build time, i.e. the set of available beans is set to stone when the app is built. This allows for various optimizations that represent the core design ideas of Quarkus.

**Comment by ivansenic** [comment]
But this really means you can not disable an endpoint with a runtime property, seems kinda strange. How is it done for example with the [quarkus.smallrye-health.ui.enable](https://quarkus.io/guides/smallrye-health#quarkus-smallrye-health_quarkus.smallrye-health.ui.enable), which seems to be a runtime config and is able to enable/disable UI. Wouldn't something like this be highly desired feature by users?

**Comment by geoand** [comment]
It's a tradeoff (what a surprise :)).

The fact that we can at build time determine all the metadata for JAX-RS endpoints, allows us to do as little work as possible at runtime for serving REST requests - thus saving memory and improving throughput.
Moreover, it makes the architecture of RESTEasy Reactive pretty clean (once one gets to know the basic concepts).

We _might_ be able to support such a feature, but it would come at a cost, which is why I don't want to do it unless there is high demand for something like this.

**Comment by ivansenic** [comment]
> It's a tradeoff (what a surprise :)).
> 
> The fact that we can at build time determine all the metadata for JAX-RS endpoints, allows us to do as little work as possible at runtime for serving REST requests - thus saving memory and improving throughput. Moreover, it makes the architecture of RESTEasy Reactive pretty clean (once one gets to know the basic concepts).
> 
> We _might_ be able to support such a feature, but it would come at a cost, which is why I don't want to do it unless there is high demand for something like this.

Got it thanks.. At least I guess there is a workaround for this, if the runtime property is set to disable and endpoint, you can simply respond directly with `404` in a programmatic way.. Not ideal, but doable..

**Comment by geoand** [comment]
Indeed :)

**Comment by cowtowncoder** [comment]
I understand the design choices and philosophy, and that is what it is. Thank you for your explanation.

The only other thing I'll mention is that it seems to me that ability to disable endpoints via properties would not necessarily require big changes during initial build, set up, planning.
Most of processing could be done for the full set, and only at a later point REST endpoint registration would note that possibly fully wired instance is just not being exposed (that is, I wouldn't worry about all injection etc having been done).

As to blocking access programmatically, yeah, if we must. Just adding code in methods would be poor man's approach.

**Comment by cowtowncoder** [comment]
Oh. And as to demand for this feature -- I obviously cannot evaluate that. We do need it for Stargate, and it seems like many web frameworks provide something like this at least for their own core pieces (admin-ui s included via opt-in).
But at least you can see if anyone else actually requests something similar in the future.

Once again, thank you for time!

**Comment by geoand** [comment]
I'll have a closer look soon and see if we can provide something that would fit all the requirements :)

**Comment by geoand** [comment]
I opened a draft [here](https://github.com/quarkusio/quarkus/pull/30051). The problem I have is that I don't really know what annotation should be used... Opinions are welcome on the PR :)
