### ISSUE TITLE
I can't discover automatically spring beans of external dependencies

### ISSUE THREAD

**Issue by cob0** [quarkusio/quarkus#30042]
### Describe the bug

Hi!

I think that this can be a bug, but I'm not sure. I'm testing quarkus with external and custom spring libraries, but Quarkus doesn't detect the beans annotated with `@Bean`.

Some example classes:
AWS LambdaHandler
```java
@Named("whateverRequestHandler")
@Slf4j
public class WhateverRequestHandler implements
    RequestHandler<Event, Object> {

  private final WrapperRequestHandler wrapperRequestHandler;
  private final RestTemplate restTemplate;

  @Inject
  public WhateverRequestHandler(WrapperRequestHandler wrapperRequestHandler, @Named("whateverRestTemplate") RestTemplate restTemplate) {
    this.wrapperRequestHandler = wrapperRequestHandler;
    this.restTemplate = restTemplate;
  }

  @Override
  public Object handleRequest(DynamicEvent event,
      Context context) {
    // it's completely necessary to register the request guid in the log appender manually
    MDC.put("AD.requestGUID", context.getAwsRequestId());
    return wrapperRequestHandler.handleRequest(event, context);
  }

}
```

External dependency class:
```java
public class WhateverComponentClass {

  public WhateverComponentClass() {
  }

  @Bean("whateverRestTemplate")
  public RestTemplate restTemplate() {
    return restTemplateBuilder.build();
  }
}
```

I'm using the `quarkus-spring-di` dependency in pom.xml.

Thanks!

### Expected behavior

I don't know.

### Output of `uname -a` or `ver`

Darwin XXXXXXXXXX 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.3 2022-04-19 LTS OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.3.6.1 (build 17.0.3+6-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

I'm not using native images

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739) Maven home: /Users/XXXXXXX/Maven/apache-maven-3.8.3 Java version: 17.0.3, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home Default locale: es_ES, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Have you indxed the external dependency?

See [this](https://stackoverflow.com/a/55513723/2504224) for all the options.

**Comment by cob0** [comment]
@geoand 
I added the jandex dependency to the parent and then added quark properties for indexing:
```properties
quarkus.index-dependency.whatever.group-id=com.acme
quarkus.index-dependency.whatever.artifact-id=external-spring-dependency
```

It just doesn't works.

Unfortunately, I can't change the original source code.

**Comment by geoand** [comment]
If you attach a sample application that exhibits the problematic behavior, I can take a look

**Comment by cob0** [comment]
@geoand you can see this repo with the example: https://github.com/cob0/quarkus-sample

**Comment by geoand** [comment]
Thanks, but it's missing `com.acme:spring-boot-template`

**Comment by cob0** [comment]
Sorry, I'm using github packages for that. Would it help if I attached it as a zip from this comment?
[quarkus-spring-dependency-develop.zip](https://github.com/quarkusio/quarkus/files/10295252/quarkus-spring-dependency-develop.zip)

**Comment by geoand** [comment]
I just want to be able to run `mvn test` :)

**Comment by cob0** [comment]
Can you run `mvn test` with this zip?
[quarkus-sample.zip](https://github.com/quarkusio/quarkus/files/10372562/quarkus-sample.zip)

**Comment by geoand** [comment]
Two things need to be done:

1. Add and empty `beans.xml` to `src/main/resources/META-INF/beans.xml`
2. Change the code of `RestTemplateContext` to:

```java
@Configuration
public class RestTemplateContext {

  @Bean(name = "whateverRestTemplate")
  public RestTemplate restTemplate() {
    return new RestTemplate();
  }

}
```
