### ISSUE TITLE
MultiPartConfig in HTTP Vert.x extension is insufficiently documented

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#30046]
### Describe the bug

Hello,

I have one opinion (you can ignore that one) and one concern (IMO bug) regarding https://github.com/quarkusio/quarkus/pull/29729 documentation.

**Opinion**: Please document this feature in more detail and ideally provide an example in docs. Documentation does not provide single example on `MultiPartConfig` and `fileContentTypes`. I understand you (and me) know what `MultiPartConfig#fileContentType` should be used for because we read this PR, but users didn't not, they only see this configuration property with text `A list of {@code ContentType} to indicate whether a given multipart field should be handled as a file part.`
With context of #29729 that sentence is completely clear, but you can only find this in configuration properties list.

**Concern** This PR added `MultiPartConfig` to Vert.x HTTP extension. `MultiPartConfig` only used by RESTEasy Reactive and ignored by every other extension (RESTEasy Classic, Reactive Routes, ...) while that fact is literally nowhere mentioned. 
 How is it possible to have the configuration in Vert.X HTTP extension and do not mention it only works for RESTEasy Reactive? How should user know that?

### Expected behavior

one of:
- I expect `MultiPartConfig#fileContentType` configuration property works for RESTEasy Classic, Reactive Routes etc.
- Document that it only works for RESTEasy Reactive

### Actual behavior

- only works for RESTEasy Reactive
- docs don't tell me that the property only works for single extension

**Comment by geoand** [comment]
You are right, I totally missed this...

We probably do need to mention that it only works for RESTEasy Reactive (currently)

**Comment by rsvoboda** [comment]
And the fix for this issue needs to be back-ported to 2.13 branch as https://github.com/quarkusio/quarkus/pull/29729 was back-ported to 2.13.6.Final

**Comment by pedroigor** [comment]
@geoand Do you want me to make the change?

**Comment by geoand** [comment]
@pedroigor sure, that would be nice

**Comment by pedroigor** [comment]
@michalvavrik I'm trying to improve the documentation for the option:

```
A comma-separated list of {@code ContentType} to indicate whether a given multipart field should be handled as a file part. You can use this setting to force HTTP-based extensions to parse a message part as a file based on its content type.

?This setting only works if you are using Resteasy Reactive?
```

I'm kinda stuck trying to explain that it only works for RR because the setting (as mentioned by @michalvavrik) is a top-level HTTP setting. Looks like the right thing to do is to deprecate this one and move the option to RR, but I'm not sure if we can fix that now ...

Otherwise, if you think we can just mention RR in the documentation above it works for me too.

**Comment by geoand** [comment]
> but I'm not sure if we can fix that now ...

Yeah, I think it's too late for that.

> Otherwise, if you think we can just mention RR in the documentation above it works for me too

I'm fine with this

**Comment by pedroigor** [comment]
@geoand @michalvavrik Not ideal. Can you please check if it is better [1]?

[1] https://github.com/quarkusio/quarkus/pull/30214
