### ISSUE TITLE
Resteasy Reactive Rest Client fails to re-construct large chunks of streamed json (stream+json) and fails deserialization

### ISSUE THREAD

**Issue by fleckware** [quarkusio/quarkus#30044]
### Describe the bug

Note: This is related to #30040 in that both result in `JsonMappingException`s, but this is a different issue.

I am trying to use `RestMediaType.APPLICATION_STREAM_JSON` to stream a `Multi` that contains a few larger objects (think ~25 kB each) from my reactive java server to a reactive java client, using the rest client.

However, the deserialization of the objects fails with `Unexpected end-of-input` errors, either at the end of `1943` bytes or `8192` bytes. (For the `1943` case,  I think there is potentially header info on the first chunk that is cutting into the `8192` total, since when I try to collect the chunks as Strings instead of reading them as my custom objects, all but the first String are 8192 chars long)

Through my own investigation I have found the workaround is to increase the Vertx `HttpClientOptions` for `DEFAULT_MAX_CHUNK_SIZE` and `DEFAULT_RECEIVE_BUFFER_SIZE`, both of which are defaulted to `8192`

Maybe that is the final solution, but I would think that the rest client should be able to use the newline-delimited json to determine when it has received an entire object, and buffer/hold in memory up to that point before attempting to deserialize. 

### Expected behavior

Rest client can properly receive and deserialize a stream of larger json objects, without having to fiddle with the http client options myself

### Actual behavior

Errors in the client:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in field name
 at [Source: (ByteArrayInputStream); line: 1, column: 1943]
...
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_STRING
 at [Source: (ByteArrayInputStream); line: 1, column: 8192]
```

### How to Reproduce?

Reproducer: `service3` (client) and `service4` (server) in https://github.com/fleckware/quarkus-test

1. in one terminal `./gradlew service4:quarkusDev`
2. in a separate terminal `./gradlew service3:quarkusDev`
3. in a separate terminal `curl localhost:8081/service4/test/large > output.json`
4. observe that when hitting the streaming endpoint on the server directly, there is no issue
5. now try to hit it using the rest client `curl localhost:8080/service3/test/large`
6. observe the json mapping error in the `service3` terminal

### Output of `java -version`

openjdk 11.0.10

### Quarkus version or git rev

2.15.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.2

**Comment by cescoffier** [comment]
Thank you for the report and the very nice reproducer.
The problem is the absence of a proper parser for application/stream+json. 

https://github.com/quarkusio/quarkus/pull/30255 contains the fix.

**Comment by fleckware** [comment]
Thank you! Will that PR close https://github.com/quarkusio/quarkus/issues/30040 as well? I notice you used the endpoint from that issue as a unit test
