### ISSUE TITLE
Generated grpc code cannot be compiled for "ınt" data type

### ISSUE THREAD

**Issue by ahmethmo** [quarkusio/quarkus#30047]
### Describe the bug

First of all sorry for my english. I'm trying to generate grpc files but cannot be compiled. Because data type is rendered as "ınt" instead of "int".

Proto file:

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.hmo";
option java_outer_classname = "HelloGrpcProto";

package helloworld;

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string message = 1;
}
```

### Expected behavior

public static final int MESSAGE_FIELD_NUMBER = 1;

### Actual behavior

public static final ınt MESSAGE_FIELD_NUMBER = 1;

### How to Reproduce?

Download Quarkus sample for grpc.

### Output of `java -version`

java 11.0.10 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: D:\app\apache-maven-3.8.6
Java version: 11.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.10
Default locale: tr_TR, platform encoding: Cp1254
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

![image](https://user-images.githubusercontent.com/9382055/209233588-5513e17f-e9a2-4a4e-ba45-5b2d087dc33d.png)

**Comment by geoand** [comment]
I tried this and it works correctly. I suggest taking a look at our [quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/2.15.1.Final/grpc-plain-text-quickstart)

**Comment by ahmethmo** [comment]
I found the solution. It's about "Default locale: tr_TR". Solution like that.

on cmd ->
set MAVEN_OPTS=-Duser.language=en
mvn compile

**Comment by geoand** [comment]
WOW, great find!
