### ISSUE TITLE
How can I change the default objectmapper in quarkus-amazon-lambda?

### ISSUE THREAD

**Issue by cob0** [quarkusio/quarkus#30041]
Hi!

I would need to change the default object mapper to add more Jackson modules, but I have seen that I can't. I'm trying to load modules with an ObjectMapperCustomizer but it doesn't work.

My ObjectMapperCustomizer class:
```java
package com.whatevver;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fasterxml.jackson.module.afterburner.AfterburnerModule;
import io.quarkus.jackson.ObjectMapperCustomizer;
import javax.inject.Singleton;

@Singleton
public class ModuleCustomizer implements ObjectMapperCustomizer {

  @Override
  public int priority() {
    return MINIMUM_PRIORITY;
  }

  @Override
  public void customize(ObjectMapper objectMapper) {
    objectMapper.registerModules(new AfterburnerModule(), new JavaTimeModule());
  }
}

```

Is there some way to do it?

Thank you!

**Comment by geoand** [comment]
It seems like we don't allow configuring the `ObjectMapper` for `quarkus-amazon-lambda`.

@patriot1burke would it make sense to allow for some customization?

**Comment by geoand** [comment]
> @patriot1burke would it make sense to allow for some customization?

@patriot1burke WDYT?

**Comment by patriot1burke** [comment]
You can do this via Arc/CDI @Produces

`@ApplicationScoped
public class ObjectMapperProducer {

    @Singleton
    @Produces
    public ObjectMapper objectMapper(...) {  ... }
}`
