### ISSUE TITLE
testcontainers.reuse.enable always set to false 

### ISSUE THREAD

**Issue by LaunchPairs** [quarkusio/quarkus#30059]
### Describe the bug

When any Quarkus DevService is used, the property `testcontainers.reuse.enable` is always set to `false` in the `~/.testcontainers.properties` file, after starting in dev mode.

### Expected behavior

The property should not be changed by Quarkus.

### Additional information

At the following statement `oldReusePropertyValue` is always `false`.

https://github.com/quarkusio/quarkus/blob/6776f0deeb8537c5207ddb5ad08e7b3c5db83722/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L90-L92

This has the effect, that its always set to `false` with:

https://github.com/quarkusio/quarkus/blob/6776f0deeb8537c5207ddb5ad08e7b3c5db83722/core/deployment/src/main/java/io/quarkus/deployment/IsDockerWorking.java#L103-L104

I think the issue should be solved when using the method `TestcontainersConfiguration#getEnvVarOrUserProperty` instead of `TestcontainersConfiguration#getUserProperty`. 

This because the method `TestcontainersConfiguration#getUserProperty` strangely ignores `TestcontainersConfiguration#userProperties`. Probably the name of the method `getUserProperty` is simply wrong.

**Comment by geoand** [comment]
Thanks for the excellent analysis @LaunchPairs!

I have opened https://github.com/quarkusio/quarkus/pull/30140 to address this issue.
