### ISSUE TITLE
2.15.1.Final breaks command mode with main class extends from `QuarkusApplication` in kotlin

### ISSUE THREAD

**Issue by bboyz269** [quarkusio/quarkus#30054]
### Describe the bug

Pretty sure it's from this pull https://github.com/quarkusio/quarkus/pull/29755.
`sanitizeMainClassName` method overlooks that main class extends from `QuarkusApplication` still compiled as original name (no postfix Kt)
https://github.com/quarkusio/quarkus/blob/6776f0deeb8537c5207ddb5ad08e7b3c5db83722/core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java#L416-L427

---

**With**
```kt
@QuarkusMain(name = "my-main")
class MyMainClass : QuarkusApplication {
  override fun run(vararg args: String?): Int {
    // omitted
  }
}
```
**Running**
```
./gradlew quarkusDev -Dquarkus.package.main-class=my-main
```
**would produces following error**
```
Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#mainClassBuildStep threw an exception: java.lang.IllegalArgumentException: The supplied 'main-class' value of '...MyMainClassKt' does not correspond to either a fully qualified class name or a matching 'name' field of one of the '@QuarkusMain' annotations
```

**Comment by geoand** [comment]
You are right, we need to cover that case
