### ISSUE TITLE
smallrye-opentracing + resteasy-reactive doesn't create spans for tracing in Jaeger

### ISSUE THREAD

**Issue by afalhambra** [quarkusio/quarkus#30052]
### Describe the bug

We are trying to upgrade from `quarkus-resteasy-mutiny` to `quarkus-resteasy-reactive`.

There is an issue when using `quarkus-smallrye-opentracing` along with `quarkus-resteasy-reactive` and making calls between different endpoints, Jaeger doesn't create the corresponding spans for all the calls between them nor link them between the calling endpoint and the called one.

However, it works fine when using `quarkus-smallrye-opentracing` +  `quarkus-resteasy-mutiny`. i.e. all the spans are created fine in Jaeger from the caller endpoint to the called endpoint, linking between them.

### Expected behavior

Having `quarkus-smallrye-opentracing` along with `quarkus-resteasy-reactive`, when making calls between different rest endpoints, we expect Jaeger to create different spans for all the calls, and link them properly.

### Actual behavior

Having `quarkus-smallrye-opentracing` along with `quarkus-resteasy-reactive`, making calls between different rest endpoints, in Jaeger we can only see one single span created, without the corresponding spans for the parent caller, and the child.

### How to Reproduce?

Reproducer:
```
git clone -b opentracing-resteasy-reactive-issue git@github.com:afalhambra/code-with-quarkus.git
cd code-with-quarkus
mvn clean verify
```

It will work fine, if you change the `pom.xml` from:

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```

to

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-mutiny</artifactId>
    </dependency>
```

### Output of `uname -a` or `ver`

Linux antferna.remote.csb 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
@brunobat is this something you are already aware of?

**Comment by radcortez** [comment]
Unfortunately, OpenTracing is abandoned in favor of OpenTelemetry. For that reason, we deprecated `smallrye-opentracing` and `quarkus-smallrye-opentracing` and we are no longer actively developing them (except for security fixes). Please check: https://quarkus.io/blog/quarkus-observability-roadmap-2023/

Our recommendation is to move to `quarkus-opentelemetry`. We are sorry for any inconvenience.

**Comment by rsvoboda** [comment]
Hi @radcortez, opentracing is still supported (marked as deprecated) on RHBQ 2.13.

RHBQ 2.13 will be supported for 1 year. We will need to check with @tqvarnst about the message that went out on product side.

**Comment by radcortez** [comment]
Sure. If we get an issue open on RHBQ we will have a look at it, but not on the community one.
