### ISSUE TITLE
Blocking anotation does not work with Mutiny and gRPC

### ISSUE THREAD

**Issue by Schallabajzr** [quarkusio/quarkus#30075]
### Describe the bug

When using Blocking on a Mutiny style gRPC service it fails with 

```
WARN  [io.qua.grp.stu.ServerCalls] (vert.x-eventloop-thread-0) gRPC service threw an exception other than StatusRuntimeException: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException
```

### Expected behavior

I expect it to work the same as Non-Mutiny style - without failing with the above exception and returning the answer.

```
@GrpcService
public class SteamService  extends GameServiceGrpc.GameServiceImplBase{
    @Inject
    GameFetch gameFetch;

    @Blocking
    @Override
    public void getGamesBySearchString(GetGamesBySearchStringRequest request, StreamObserver<GetGamesBySearchStringResponse> responseObserver) {
        List<GamesBySearchResponse> gameBySearch = gameFetch.getGameBySearch(request.getSearchString());
        responseObserver.onNext(GetGamesBySearchStringResponse.newBuilder()
                .addAllGames(() -> gameBySearch.stream()
                        .map(gbsr ->
                                GameBySearchDto.newBuilder()
                                        .setAppid(gbsr.appid())
                                        .setName(gbsr.name())
                                        .setStoreEnum(StoreEnum.STEAM)
                                        .build()
                        ).iterator())
                .build());
        responseObserver.onCompleted();
    }

}

```

### Actual behavior

Example code where gameFetch is blocking the method fails with org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException.

```
@GrpcService
public class MutinyStreamService implements GameService {

    @Inject
    GameFetch gameFetch;

    @Blocking
    @Override
    public Uni<GetGamesBySearchStringResponse> getGamesBySearchString(GetGamesBySearchStringRequest request) {
        List<GamesBySearchResponse> gameBySearch = gameFetch.getGameBySearch(request.getSearchString());
        return Uni.createFrom().item(() ->
                GetGamesBySearchStringResponse.newBuilder()
                        .addAllGames(() -> gameBySearch.stream()
                                .map(gbsr ->
                                        GameBySearchDto.newBuilder()
                                                .setAppid(gbsr.appid())
                                                .setName(gbsr.name())
                                                .setStoreEnum(StoreEnum.STEAM)
                                                .build()
                                ).iterator())
                        .build()
        );
    }
}
```

### Output of `uname -a` or `ver`

Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk-19 (19.0.1)

### Quarkus version or git rev

2.15.1.Final

### Additional information

GameFetch is a simple Bean that calls a RestClient

```
@RequestScoped
public class GameFetch {

    @RestClient
    SteamCommunityService steamCommunityService;

    @PostConstruct
    void init() {
        ObjectMapper objectMapper = Arc.container().instance(ObjectMapper.class).get();
        objectMapper.enable(DeserializationFeature. ACCEPT_SINGLE_VALUE_AS_ARRAY);
    }

    public List<GamesBySearchResponse> getGameBySearch(String searchString) {
        return steamCommunityService.getGameBySearch(searchString);
    }
}
```

And the .proto

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.acme";
option java_outer_classname = "GameSearchProto";

package game.search;

enum StoreEnum {
  STORE_ENUM_UNSPECIFIED = 0;
  STEAM = 1;
  GOG = 2;
}

message GameBySearchDto {
  string name = 1;
  string appid = 2;
  StoreEnum store_enum = 3;
}

service GameService {
  rpc GetGamesBySearchString(GetGamesBySearchStringRequest) returns (GetGamesBySearchStringResponse);
}

message GetGamesBySearchStringRequest {
  string search_string = 1;
}

message GetGamesBySearchStringResponse {
  repeated GameBySearchDto games = 1;
}
```

**Comment by cescoffier** [comment]
Could you provide a simple reproducer?

The current behavior is kind of expected, as @Blocking works with Mutiny. However, we can probably improve.

**Comment by cescoffier** [comment]
MY bad, you kind of provided a reproducer - having a look.

**Comment by cescoffier** [comment]
Hum, it seems to work fine for me. 

Can you provide a reproducer that demonstrates the issue?

**Comment by Schallabajzr** [comment]
@cescoffier provided a full example. I didn't know how to switch implementations of the non working and working class so I commented some code for the working example as explained in readme.

https://github.com/Schallabajzr/quarkus_blocking_bug_example

**Comment by cescoffier** [comment]
Thanks @Schallabajzr.

However, the reproducer works for me. I switched to the non-mutiny implementation and got the correct results (no exception). I checked on which thread the gRPC service was called, and, as expected, I'm on a worker thread.

**Comment by cescoffier** [comment]
ah! Got it! It's the mutiny variant that is problematic.

**Comment by Schallabajzr** [comment]
@cescoffier yes Mutiny version fails, sorry if it was unclear. Were you able to reproduce it?

**Comment by cescoffier** [comment]
@Schallabajzr Yes! I even have a fix. Polishing it right now. Expect a PR in a few hours.

**Comment by alesj** [comment]
@cescoffier otoh ... was just thinking about this issue ...
Why do we ever want to "start" from `ImplBase` class, and not always from `service` class ?

```
        ClassInfo classInfo;
        var classes = classHierarchy(service, index);
        if (isExtendingMutinyService) {
            classInfo = service;
        } else {
            // Collect all gRPC methods from the *ImplBase class, if present
            classInfo = classes.get(classes.size() - 1);
        }
```

**Comment by alesj** [comment]
> Do you mean why would a user implement the base impl instead of the mutiny interface?

No.
I mean why does our code use `ImplBase` class for `classInfo`.
Why doesn't it alway just use `service` class, as does your latest fix.

**Comment by alesj** [comment]
Yeah, I understand all of that, but that doesn't answer my question. ;-)

What I'm trying to say is that we use `ImplBase` classInfo for no reason -- see code,
since imho we could be just doing what you just did for the fix -- use `service` classInfo always.

Just trying to get to the bottom if my observation is true, or am I missing something?

**Comment by cescoffier** [comment]
ah got it, yes, we could use `service` every time I think.
To be honest, I didn't fully understand why getting the last from the hierarchy (which is the concrete implementation).
