### ISSUE TITLE
KeycloakTestResourceLifecycleManager doesn't specify cmd

### ISSUE THREAD

**Issue by iskhakovt** [quarkusio/quarkus#30072]
### Describe the bug

KeycloakTestResourceLifecycleManager [starts](https://github.com/quarkusio/quarkus/blob/main/test-framework/keycloak-server/src/main/java/io/quarkus/test/keycloak/server/KeycloakTestResourceLifecycleManager.java#L58) the keycloak container without any cmd override, which does not allow to run the non-legacy keycloak. Devservices [specify](https://github.com/sberyozkin/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L110) the cmd and allow to [override](https://github.com/sberyozkin/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L486) it.

### Expected behavior

KeycloakTestResourceLifecycleManager to use the same default cmd override as devservices and allow a manual value.

**Comment by sberyozkin** [comment]
@iskhakovt There are no plans to have `KeycloakTestResourceLifecycleManager` match how `DevServices for Keycloak` support Quarkus based and Wildfly based Keycloak distributions.
  
`DevServices for Keycloak` should be used for testing as well. Have you tried it ?

**Comment by sberyozkin** [comment]
@iskhakovt Closing as not planned - if you find that testing with `DevServices for Keycloak` needs some enhancements/fixes - please open the dedicated issues

**Comment by iskhakovt** [comment]
Thanks, I'll try it out.
