### ISSUE TITLE
Invalid documentation regarding client grpc deadlines

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#30082]
### Describe the bug

I assume this is a mistake in the documentation and not in the implementation. Maybe it's also something on the grpc-java iteself.

However, the documentation here: https://quarkus.io/guides/grpc-service-consumption#client-deadlines says it's defining a RPC timeout, but in fact this config property is used when creating a stub and thus is related to a stub deadline.

The stub deadline is something completely different, and is actually not related to a RPC but the stub in general. Every call will start hitting a timeout after specified deadline on the stub expires:

```
  /**
   * Returns a new stub with a deadline that is after the given {@code duration} from now.
   *
   * @since 1.0.0
   * @see CallOptions#withDeadlineAfter
   */
  public final S withDeadlineAfter(long duration, TimeUnit unit) {
    return build(channel, callOptions.withDeadlineAfter(duration, unit));
  }

```

Deadline for a call is defined using `CallOptions#withDeadlineAfter`.

### Quarkus version or git rev

2.15.1

**Comment by ivansenic** [comment]
Example that showcases that all calls fail if deadline is defined: https://github.com/stargate/stargate/actions/runs/3788189376

**Comment by cescoffier** [comment]
The documentation is wrong.
As you mentioned, it allows setting a deadline on the call options - which means that once passed, you cannot use the stub anymore. 

If you want a call timeout, you would need to use the following:

- Mutiny `ifNoItemAffter(...)`
- Fault Tolerance `@Timeout`

**Comment by pcasaes** [comment]
What is the use case for configuring a stub this way?

**Comment by cescoffier** [comment]
https://grpc.io/blog/deadlines/

**Comment by pcasaes** [comment]
More specifically, what is the use case for setting a deadline such that the stub becomes unusable until the application is restarted (or the stub recreated)?

My understanding is that deadlines should be by call.

> As a client you should always set a deadline for how long you are willing to wait for **a reply from the server**
(emphasis mine)

**Comment by pcasaes** [comment]
Will using timeout set a deadline and send it through the call's context?

**Comment by pcasaes** [comment]
I'm also trying to understand how this is useful:

> If you need to configure a deadline for a gRPC stub, i.e. to specify a duration of time after which the stub will always return the status error DEADLINE_EXCEEDED.
