### ISSUE TITLE
jbang does not persist Q:CONFIG keys nor build set keys

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#30087]
### Describe the bug

this probably always been case but not noticed as only recently jbang changed to run jbang integration build externally.

when running jbang build integration quarkus sets system properties based on Q:CONFIG keys and these are not persisted into the next run if run with -Dquarkus.dev. They do seem to get stored when packaging for prod builds.

```
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:2.11.2.Final}@pom
//DEPS io.quarkus:quarkus-resteasy
// //DEPS io.quarkus:quarkus-smallrye-openapi
// //DEPS io.quarkus:quarkus-swagger-ui
//JAVAC_OPTIONS -parameters
//Q:CONFIG quarkus.myproperty=stored in q:config
import io.quarkus.runtime.Quarkus;
import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/")
@ApplicationScoped
public class main {

    @ConfigProperty(name = "quarkus.myproperty", defaultValue = "this is the default value") 
    String myProperty;

    @GET
    public String sayHello() {
        return "myProperty: " + myProperty;
    }

}
```

using above you'll see that `jbang main.java` just has default value. if you run with `jbang -Dquarkus.myproperty=cmdline main.java` it does change.

...I kinda also assumed -Dquarkus.myproperty at build time would persist to runtime but does not seem to happen.

### Expected behavior

Q:CONFIG should be loaded into the build generated defaults and should work even when -Dquarkus.dev mode used.

**Comment by radcortez** [comment]
It doesn't work because we don't record system properties from the build system. See https://github.com/quarkusio/quarkus/blob/78045ea67413518f7c77271d08a70d03d1fffbbd/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L1023-L1106
