### ISSUE TITLE
[Extension Proposal]  Support for AWS step functions 

### ISSUE THREAD

**Issue by Cs4r** [quarkusio/quarkus#30081]
### Description

Dear Quarkus team,

I propose adding an extension to the Quarkus framework for interacting with Amazon Web Services (AWS) Step Functions.

AWS Step Functions is a fully managed service that enables developers to build, test, and run workflows that execute as a series of steps. These workflows can be triggered by a variety of events, such as an HTTP request, a scheduled time, or the completion of a downstream task. Step Functions make it easy to coordinate and execute complex, long-running processes asynchronously, which can be particularly useful in microservices architectures.

Adding an extension for AWS Step Functions to Quarkus would enable developers to easily incorporate Step Functions into their applications, making it possible to build, deploy, and run workflows that coordinate the execution of microservices and other components.

The extension would be called something like `io.quarkiverse.amazonservices:quarkus-amazon-stepfunctions`

I believe that this extension would be a valuable addition to the Quarkus framework, as it would allow developers to take advantage of the benefits of Step Functions when building cloud-native applications.

Thank you for considering this proposal.

Sincerely,
César Aguilera

if you are interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-amazon-stepfunctions

### Short description

Quarkus support for AWS stepfunctions 

### Repository Topics

- quarkus 
- aws 
- stepfunctions 
- microservices 
- cloudnative 
- workflow 
- coordination 
- async 
- extension proposal

### Team Members

- 

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by gastaldi** [comment]
I think this makes sense to live as a new module in https://github.com/quarkiverse/quarkus-amazon-services? WDYT?

**Comment by Cs4r** [comment]
Yes, you are right. Opening a ticket in https://github.com/quarkiverse/quarkus-amazon-services

**Comment by gastaldi** [comment]
Thanks! Closing it
