### ISSUE TITLE
Setting `add-version-to-label-selectors: false` removes the app.kubernetes.io/version label

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#30100]
### Describe the bug

It seems that setting `add-version-to-label-selectors: false` completely removes the version label.

### Expected behavior

The version should not be used in the selector but still be in the labels.

### Actual behavior

Version is not in the selector but it has been removed from the labels as well.

### Output of `java -version`

17

### Quarkus version or git rev

2..15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

**Comment by geoand** [comment]
Makes sense!

https://github.com/quarkusio/quarkus/pull/30142 takes care of it
