### ISSUE TITLE
HTTP access log contains duplicate entries when rerouting requests

### ISSUE THREAD

**Issue by brahim-raddahi** [quarkusio/quarkus#30105]
### Describe the bug

When using a RouteFilter to reroute requests, the access log handler seems to be added multiple times, resulting in multiple lines for the same request in the access log.

This:
https://github.com/quarkusio/quarkus/blob/3.0.0.Alpha2/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/filters/accesslog/AccessLogHandler.java#L145

Should only be triggered once per RoutingContext

Sidenote: there does not seem to be an option to refer to the "original request" variables vs the rewritten ones (Apache uses ">" and "<" for this), the logged path for example will be the rewritten/rerouted one

### Expected behavior

The access log should contain only one line per request

### Actual behavior

The access log contains multiple lines per request

### How to Reproduce?

Add a RouteFilter to your application: https://quarkus.io/guides/reactive-routes#intercepting-http-requests
In that RouteFilter -> reroute the request: rc.reroute(...)
Enable the http access log: https://quarkus.io/guides/http-reference#configuring-http-access-logs

**Comment by geoand** [comment]
Can you please provide a sample application that behaves the way you describe?

**Comment by geoand** [comment]
Closing as we never got feedback

**Comment by brahim-raddahi** [comment]
Sorry for the late response, I opened a new issue which contains code required to reproduce this: https://github.com/quarkusio/quarkus/issues/30845
