### ISSUE TITLE
Support generic types as @ConfigItem data types

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#30113]
### Description

Recently I had to introduce wrapper as code similar to this one failed:
```Java
@ConfigItem
Predicate<CustomDataType> customPropertyName 
```
as my converter could never be matched - more specifically, this line was reached https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/configuration/type/ConverterType.java#L92 and Quarkus seems to only support collections, Class and Optional for parametrized typed.

IMO one of 2 things should be done :

1. Quarkus allows me to define converter with parametrized type (no build time validation of that specific option) and failure happens when property is looked up and converter is never found. If we don't support parametrized converters, let's validate it during build time and provide clearer message (smth like _Converts do no support generic types apart of ..._)
2. Support at least exact data type matches (no inheritance, no interfaces etc.), so that if I define `Predicate` and `CustomDataType`, converter that handles `Predicate<CustomDataType>` is chosen

I prefer second one :-)

**Comment by michalvavrik** [comment]
cc @radcortez

**Comment by radcortez** [comment]
The current configuration system based on classes will be deprecated in favour of interfaces and `@ConfigMapping`, so it is unlikely that we will be adding features to the class approach: https://quarkus.io/guides/writing-extensions#configuration.

You can do what you want with `@ConfigMapping` like this:

```java
@ConfigMapping(prefix = "predicate")
public interface PredicateMapping {
    @WithConverter(PredicateCustomDataType.class)
    Predicate<CustomDataType> custom();

    class CustomDataType {
        String value;

        public CustomDataType(final String value) {
            this.value = value;
        }
    }

    class PredicateCustomDataType implements Converter<Predicate<CustomDataType>> {
        @Override
        public Predicate<CustomDataType> convert(final String value) throws IllegalArgumentException, NullPointerException {
            return new Predicate<CustomDataType>() {
                @Override
                public boolean test(final CustomDataType customDataType) {
                    return value.equals(customDataType.value);
                }
            };
        }
    }
}
```

**Comment by michalvavrik** [comment]
Thank you for taking your time @radcortez , I tested your example and it works. Can't see an advantage in using class approach, so I'll close the issue.

I went through https://quarkus.io/guides/writing-extensions and https://quarkus.io/guides/config-mappings and while all examples are using `interface`, there is no mention that you should use only interface or do not use classes. Should Quarkus validate target and either fail or log warning?

**Comment by michalvavrik** [comment]
Ah, I see `The @ConfigMapping annotation can only be placed in interfaces, class io.quarkus.it.smallrye.config.PredicateMapping is a class`. Ok, thanks.

**Comment by radcortez** [comment]
Yes :)
