### ISSUE TITLE
Introduce a native image extension

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#3013]
**Description**
Make native image be an extension rather than a dedicated Mojo.  Make sure the extension can be explicitly disabled by a configuration property.  Make sure all the current Mojo configuration flags are moved into the build-time configuration of the extension.

**Implementation ideas**
Produce the native image during the augment phase.  Use a virtual build item as a pseudo target for the native image output.  The virtual item would be declared as a final item if the extension is present and enabled.  Build steps can use weak production to produce code that is conditional on native image being enabled.

**Comment by gsmet** [comment]
@dmlloyd hasn't this been addressed by Stuart's latest work on the subject?

**Comment by dmlloyd** [comment]
Yes, I think this can be considered solved.
