### ISSUE TITLE
Question : why is field based injection preferred for QuarkusTests ? 

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#30136]
Hello

Given https://github.com/quarkusio/quarkus/blob/bd66b8657d9d854de6e1aabdb0434536c516d11b/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L721

And https://quarkus.io/guides/getting-started-testing#injection-into-tests

What is the rationable behind constructor injection being "forbidden" ?

thanks

**Comment by mkouba** [comment]
@geoand It seems that you added the aforementioned comment in the `QuarkusTestExtension`...

**Comment by geoand** [comment]
The reason is that when the test is constructed, we cannot guarante that all the "dependencies" exist
