### ISSUE TITLE
MVN test does not take the custom settings.xml

### ISSUE THREAD

**Issue by Lory1990** [quarkusio/quarkus#30147]
### Describe the bug

Hi! I created my own library and published on my nexus `https://nexus.mywebsite.eu`, here it is
```
<dependency>
        <groupId>step</groupId>
        <artifactId>quarkus-common-int</artifactId>
        <version>0.0.1</version>
    </dependency>
```

I use IntelliJIdea and I have a custom `settings.xml` file who points to the nexus, it works really good when i run `mvn install` but when i run `mvn test` it breaks.

It seems maven is trying to download the library from central and not from nexus. 

Here is the intellij command
```
/Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/lorenzo.defrancesco/projects/spain/step-youlend-be-es -Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=50431:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2022.2.4 -s /Users/lorenzo.defrancesco/projects/settings.xml test
```

The error is 
```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact step:quarkus-common-int:jar:0.0.1 in central (https://repo.maven.apache.org/maven2)
```

And this is the surefire config
```
<plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```

### Expected behavior

Downloads artifact from https://nexus.mywebsite.eu instead of central

### Actual behavior

Downloads the artifact from central

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22 OpenJDK Runtime Environment (build 18.0.1.1+2-6) OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

### Quarkus version or git rev

2.15.1.Final

**Comment by geoand** [comment]
This doesn't look like a Quarkus issue, but I'll let @famod and @aloubyansky decide

**Comment by aloubyansky** [comment]
By custom settings you mean you use -s?
We also recommend adding the following to the surefire and failsafe plugin configs:

<maven.repo.local>${settings.localRepository}</maven.repo.local>
<maven.settings>${session.request.userSettingsFile.path}</maven.settings>
