### ISSUE TITLE
GraphQL federation directives, which allow multiple values, do not match Apollo contract

### ISSUE THREAD

**Issue by alexpoletaev** [quarkusio/quarkus#30145]
### Describe the bug

GraphQL federation directives, which allow multiple values, like `@provides`, `@key`, etc., do not match Apollo [contract](https://www.apollographql.com/docs/federation/federated-types/federated-directives/). It seems that in Apollo those directives  have value of type `FieldSet!`, which represents whitespace-separated string of values, but Smallrye module represents those directives just as arrays of values. As a result, those directives are not valid for the Apollo server.

### Expected behavior

The `@provides` directive is shown in the schema like that:
`@provides(fields : "rating reviews")`

### Actual behavior

The `@provides` directive is shown in the schema like that:
`@provides(fields : ["rating", "reviews"])`

### How to Reproduce?

Reproducer: [quarkus-graphql-issue.zip](https://github.com/quarkusio/quarkus/files/10336796/quarkus-graphql-issue.zip)

- unzip a reproducer
- start service
- go to graphql UI
-  execute next query:
`query { _service { sdl } }`
- observe that `@provides` directive in the graphql schema has a type of array
- uncomment a workaround method in the `GraphQLSchemaObserver` class
- observe that `@provides` directive in the graphql schema has a type of whitespace-separated string (FieldSet)

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

This reproducer uses a workaround from the #30129 issue. It also provides a temporary workaround to convert `@key` and `@provides` directives from type of array to type of FieldSet (string).

**Comment by jmartisk** [comment]
Here I think we will need the help of @t1 who wrote the code handling these directives -would you be willing to fix this in SmallRye?
It's an API breaking change, but since federation is marked experimental, it shouldn't be a huge deal

**Comment by t1** [comment]
I'm taking a look into this. The problem is, that the `@Key` annotation then needs to be repeatable.

**Comment by jmartisk** [comment]
But right, there's also the `resolvable` parameter and if you want to have a different value of it for different fields, then we really need a repeatable annotation.

**Comment by t1** [comment]
No, `@Key(fields="a b")` means you can resolve this with the combination of `a` and `b`... a compound key, so to speak, while `@Key(fields="a")` plus `@Key(fields="b")` means that you can resolve either with `a` or with `b`.

**Comment by jmartisk** [comment]
Ah, ok gotcha.
