### ISSUE TITLE
mssql JDBC driver requiring non-default character sets

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#3014]
**Describe the bug**
The MSSQL JDBC Driver is requiring users to set the _addAllCharsets_ property on native-image build plugins.

This should ideally be automated, or at least we should document this need.

**Expected behavior**
Users shouldn't need to know this.

**Comment by gsmet** [comment]
Once we have https://github.com/quarkusio/quarkus/issues/3013 , it should just be a matter of pushing a build item.

**Comment by gsmet** [comment]
@Dufgui would you be interested in taking this one? It's very similar to what you did with JNI.

**Comment by Dufgui** [comment]
done, could you find a more touchy one please ?
