### ISSUE TITLE
Resteasy-reactive block connection to same application from ServerRequestFilter

### ISSUE THREAD

**Issue by jota-coelho** [quarkusio/quarkus#30156]
### Describe the bug

I'm migrating a project from resteasy-classic to resteasy-reactive, and I found something that could be a bug, or an error. 
I need help to understand.
I use a request filter to implement authentication (JWT). In my application, depending on business rules, the database (Intersystems Cache) makes a request to API that is implemented in the same project. there were no problems when using resteasy-classic, but when switched to reactive it started to block the request.
 
I made a public project, very simple, that simulates the problem. If anyone can help me understand the problem I would appreciate it

https://github.com/jota-coelho/resteasy-reactive

### How to Reproduce?

Clone the github project example:
Start quarkus
execute a curl to consume resource example:

curl -X GET http://localhost:8090/auth -H 'accept: application/json' -H 'Authentication: true'

### Output of `uname -a` or `ver`

Linux deathnote 6.0.12-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18

**Comment by gastaldi** [comment]
Try changing your `Filters` implementation to do the following:

```java
	@ServerRequestFilter(preMatching = true, nonBlocking = true)
	public Uni<Response> getLogin(ContainerRequestContext context) {
		String auth = context.getHeaders().getFirst("Authentication");
		if ("true".equals(auth)) {
			
			// This list simulate business rule.
			return Uni.createFrom()
					.future(client.target(url).request().async().get(new GenericType<List<User>>() {}))
					.onItem().transform(
							users -> Response.status(Status.OK).entity(users).build());

		}
		return null;
	}
```

**Comment by gastaldi** [comment]
But nevertheless I think we should investigate why your code freezes the application and how we can prevent that from happening

**Comment by geoand** [comment]
The issue is that Vert.x HTTP client (that is used under the hood to implement the JAX-RS Client) limits the number of concurrent connections to 5 per target.

You can increase the limit by doing the following:

```java
ClientBuilder.newBuilder().property(QuarkusRestClientProperties.CONNECTION_POOL_SIZE, 100).build();
```
