### ISSUE TITLE
Facilitate running the application locally via the tooling

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#30168]
### Description

Currently, to run the application locally in prod mode you must package the application then locate the JAR and launch it via the java command.
However, the location of the JAR is non standard and depends of which type of packaging is used.

Providing a way to package and run the application in one command would be a great improvements to the developer experience.

For example:

```shell
# Using quarkus CLI
quarkus run

# Using Maven
mvn quarkus:run

# Using Gradle
gradle quarkusRun
```

**Comment by geoand** [comment]
This is a duplicate of https://github.com/quarkusio/quarkus/issues/9315, no?

**Comment by loicmathieu** [comment]
Yes, I searched but didn't find it (it should have been far in the search list). Apparently it's a long awaited enhancements ;)
