### ISSUE TITLE
Support for mongodb embed flapdoodle 4.3.x

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#30178]
### Description

Currently quarkus uses flapdoodl 3.x and not 4.3.x team have pushed a few changes and refactoring.
replica set is not configured to have version change to flapdoodle and defaults to v4.0 can we have it move to vPRODUCTION instead.

io.quarkus.test.mongodb.MongoTestResource will start a single instance on port 27017.

io.quarkus.test.mongodb.MongoReplicaSetTestResource will start a replicaset with two instances, one on port 27017 and the other on port 27018.

### Implementation ideas

provide option to use flapdoodl new vesion for embed mongo.

**Comment by loicmathieu** [comment]
@debu999 users are encourage to use MongoDB Dev Service and not flapdoodle that is designed for Quarkus internal tests. MongoDB Dev Service is built on top of testcontainers which setup a one-node replicaset and you can easily switch MongoDB version by changing the image.

You can also change the MongoDB version with the `version` parameter of the testresource.

Regarding updating flapdoodle, I agree it should be done some day. Moreover, we have issue with making it working on our Windows CI, maybe it will fix it.

**Comment by debu999** [comment]
We have our build running from within pods and we can't have docker daemon to use test containers

**Comment by debu999** [comment]
I am trying out with flap doodle referring to the spring implementation if successful will share the same to be added for new flapdoodle version for anyone in similar situation.
@loicmathieu

**Comment by debu999** [comment]
https://github.com/quarkusio/quarkus/pull/30243 This has the fix on the new version of flapdoodle 4.3.3.

**Comment by loicmathieu** [comment]
Fixed by #30366
