### ISSUE TITLE
RestEasy returns 405 instead of 500 for POST

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#3017]
**Describe the bug**
405 is returned for POST requests on internal server errors.
It works fine with GET

**Expected behavior**
500 should be returned

**To Reproduce**
- clone it and start it:
```
git clone https://github.com/michalszynkiewicz/quarkus-resteasy-invalid-status-code reproducer && cd reproducer
mvn clean package
java -jar target/foo-1.0-SNAPSHOT-runner.jar
```
- query:
```
curl -v localhost:8080/foos -X POST -H "Content-Type: text/plain" -H "Accept: text/plain"
```

**Environment (please complete the following information):**
Quarkus 0.18.0, java 8

**Comment by loicmathieu** [comment]
Duplicated with #2657

**Comment by michalszynkiewicz** [comment]
@loicmathieu why do you think it's a duplicate of 2567? The other one is about the client, isn't it?

**Comment by gsmet** [comment]
ping @asoldano
