### ISSUE TITLE
[Quarkus 3 migration] Migration script changes security packages

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#30198]
### Describe the bug

After using the Quarkus 3 migration script (OpenRewrite recipe), within our project, we've encountered some insufficiencies for the migration. 

#### You can check it here: https://github.com/keycloak/keycloak/issues/16247
-----------------------------------------

Packages in our codebase were changed from `javax.security.*` to `jakarta.security.*` even though any dependency of `javax.security` is included in the project. The security packages are included in the JDK itself, and for JDK 11, it still contains the prefix `javax.*`, so probably these packages should not be updated in the codebase as there should still be support for JDK 11 and also JDK 17.

### Expected behavior

Packages references for the `javax.security` are NOT changed

### Actual behavior

Packages references for the `javax.security` are changed

### How to Reproduce?

Execute the migration script for Quarkus 3

**Comment by gsmet** [comment]
There is an ongoing PR here: https://github.com/quarkusio/quarkus/pull/30205 .

**Comment by gsmet** [comment]
This should now be handled in https://github.com/quarkusio/quarkus-updates/blob/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml .
