### ISSUE TITLE
[Quarkus 3 migration] Include JBoss conversions for JakartaEE APIs

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#30196]
### Description

After using the Quarkus 3 migration script (OpenRewrite recipe), within our project, we've encountered some insufficiencies for the migration. 

#### You can check it here: https://github.com/keycloak/keycloak/issues/16247
-----------------------------------------

For migration to `jakarta.ws.rs-api` and `jakarta.transaction-api`, it'd also be good to consider adding to the script conversion from `org.jboss.spec.*` specs. Not only conversion from `javax.*`.

**Comment by gsmet** [comment]
This should now be handled properly in https://github.com/quarkusio/quarkus-updates/blob/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml .
