### ISSUE TITLE
[Quarkus 3 migration] Include Sun conversions for JakartaEE APIs

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#30197]
### Description

After using the Quarkus 3 migration script (OpenRewrite recipe), within our project, we've encountered some insufficiencies for the migration. 

#### You can check it here: https://github.com/keycloak/keycloak/issues/16247
-----------------------------------------

It's necessary to include conversions from `com.sun.*` to `jakarta.*` deps to the migration script.

**Comment by gsmet** [comment]
This should now be handled properly in https://github.com/quarkusio/quarkus-updates/blob/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml .

I haven't taken exactly all the rules that are in the original file but I think we have a migration path that is in line with 99.9% of the usages of Quarkus.
