### ISSUE TITLE
(resteasy reactive) quarkus.rest-client.user-agent=foo is not honored

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#30271]
### Describe the bug

Hello

I'm trying to set a User Agent string for the _reactive_ HTTP client
Per configuration https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.user-agent is applicable to reactive

https://github.com/quarkusio/quarkus/pull/22236#issue-1080969633 states "I did not do this for the classic"

But quarkus.rest-client.user-agent=foo seems ignored. It defaults to "Resteasy Reactive Client"

Client headerMap is :  
```
writeEntity:243, RestClientRequestContext (org.jboss.resteasy.reactive.client.impl)
setRequestHeadersAndPrepareBody:497, ClientSendRequestHandler (org.jboss.resteasy.reactive.client.handlers)
```

Screenshot of headerMap is attached

How should I configure the UA string ?

thanks

### Expected behavior

quarkus.rest-client.user-agent=foo is honored

### Actual behavior

quarkus.rest-client.user-agent=foo is ignored

### How to Reproduce?

1. use latest quarkus alpha
2. quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

### Additional information

![qUA](https://user-images.githubusercontent.com/1085201/211491072-e11e4ac6-fff3-44be-993a-7a3292d15faa.png)

**Comment by geoand** [comment]
I just tested this and both the global user-agent setting and the per-client user-agent setting work correctly.

My guess is that you the debugging information is tricking you - to do a proper verification you need to either capture the network traffic on your end (for example using Wireshark), or you need to control the server which is receiving the request
