### ISSUE TITLE
Send button for GRPC in dev mode broken

### ISSUE THREAD

**Issue by knoma** [quarkusio/quarkus#30288]
### Describe the bug

Currently I'm unable to send a request via the dev UI for for GRPC, the call doesn't get triggered.

In the javascript console I can see this error at startup

```
Uncaught SyntaxError: Unexpected token '-' (at service?name=hello.HelloGrpc:571:40)

                            var quarkus-generated-sourcesPackages = [];
``` 

When I click send I get this error 

```
Uncaught ReferenceError: sendTestRequest is not defined
                          onclick="sendTestRequest('hello.HelloGrpc','SayHello', 'UNARY')">

```
I get the errors on Chrome and Safari, I tried restart and a empty browser cache. 

I just created a new grpc project using quarkus 2.15.2 and running the example  

### Output of `uname -a` or `ver`

22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.5 2022-10-18 LTS

### Quarkus version or git rev

2.15.2

### Additional information

<img width="2026" alt="image" src="https://user-images.githubusercontent.com/2001088/211593632-ffb4f336-d552-4bb0-9bfc-f9a77d521d9f.png">

**Comment by cescoffier** [comment]
I just tried with the gRPC quickstart and Quarkus 2.15.3.Final, and it works.

Can you attach a reproducer?

**Comment by knoma** [comment]
thank you for checking, no luck. Still same error even after creating a new app. 

I tried this on macOS 13.1 with Quarkus 2.15.3 and java 17 using these param to create the grpc starter  

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/2001088/212373055-59773a5f-68f0-4336-b279-1e84d758b979.png">


I just run `./gradlew quarkusDev` after the download but the error was still in Safari and Chrome (private and incognito mode)

<img width="2040" alt="image" src="https://user-images.githubusercontent.com/2001088/212372851-d1373706-cab2-46bc-967e-873c138c51e2.png">


<img width="2048" alt="image" src="https://user-images.githubusercontent.com/2001088/212374128-585dff84-dd23-421f-b6bb-fcd3f0a61c88.png">

**Comment by cescoffier** [comment]
Ah, there is one big difference: you used Gradle. Can you try with maven, so we can pinpoint the problem?

**Comment by knoma** [comment]
With maven I have no errors in the js console and I can submit the req successfully.


I also saw this message when I open unary query site `Web Socket bridge to gRPC connected`, before I just have yellow spot (I thought it's a html glitch), plus in the console it says `websocket connected`.


<img width="2048" alt="image" src="https://user-images.githubusercontent.com/2001088/212479400-67f0e9ff-c130-46d3-a35f-279f4c8a83b3.png">
 
In the cradle version the js var is called 

``
                            var sourceMap = {};
                            var quarkus-generated-sourcesPackages = [];
                            quarkus-generated-sourcesPackages.push("grpc.org.acme")
``

In the maven version this shows up

``

                           var sourceMap = {};
                            var javaPackages = [];
                            javaPackages.push("org.acme")
 ``


I also the function `sendTestRequest` is defined now


``
        function sendTestRequest(serviceName, methodName, methodType) {
            const queryIdentifier = `${serviceName}#${methodName}`;
            var connection = Array.from(connections.values()).find(conn => conn.queryIdentifier == queryIdentifier);
            const testRequest = document.getElementById(serviceName + "/" + methodName + "_request");
            if (!connection || methodType == 'UNARY') {
                requestId ++;
                connection = {
                    id: requestId,
                    queryIdentifier: queryIdentifier,
                    responseElement: document.getElementById(serviceName + "/" + methodName + "_response"),
                    responseText: '',
                    unary: methodType == 'UNARY'
                };
                connections.set(requestId, connection);
            }

            const request = {
                serviceName: serviceName,
                methodName: methodName,
                id: requestId,
                content: testRequest.value
            };

            grpcWS.send(JSON.stringify(request));

            if (methodType != 'UNARY') {
              showConnected(connection);
            }
``

**Comment by cescoffier** [comment]
So, the bug is actually not related to gRPC but to the dev UI.
It injects the source map, but the code does not handle Gradle correctly. It would happen in many other places as soon as you use Gradle with generated sources. 

There is a template in each Dev UI pages which does:

```
{#for sourcePackageEntry in ideInfo:sourcePackages}
    var {sourcePackageEntry.key}Packages = [];
{#for rootPackage in sourcePackageEntry.value}
    {sourcePackageEntry.key}Packages.push("{rootPackage}")
{/for}
```

But with Gradle it generates:

```
var quarkus-generated-sourcesPackages = [];
quarkus-generated-sourcesPackages.push("grpc.org.acme")
sourceMap["quarkus-generated-sources"] = quarkus-generated-sourcesPackages;
```

As you can expect, `quarkus-generated-sourcesPackages` is not a valid identifier. 

\CC @geoand

**Comment by geoand** [comment]
Interesting, I'll have a look next week (I will be out this week)

**Comment by cescoffier** [comment]
I'm having a look - but do be clear, I'm not sure I understand what I'm doing :-D
