### ISSUE TITLE
Trust store property fields for DynamicGraphQLClientBuilder to fix "SSL Handshake Error"

### ISSUE THREAD

**Issue by Archana0510** [quarkusio/quarkus#30313]
### Description

Please add fields to DynamicGraphQLClientBuilder for below corresponding properties
quarkus.smallrye-graphql-client."clients".trust-store
quarkus.smallrye-graphql-client."clients".trust-store-password

We are using DynamicGraphQLClientBuilder to add header, as the token is not fixed and gets refreshed periodically.
So could not use **quarkus.smallrye-graphql-client."clients".header.HEADER-KEY=HEADER-VALUE** for adding header

We have to add trust store properties to fix "SSL Handshake Error"

### Implementation ideas

Add two fields "trust-store", "trust-store-password" to DynamicGraphQLClientBuilder class

**Comment by jmartisk** [comment]
The `VertxDynamicGraphQLClientBuilder ` class (you may have to cast your builder to this class) has a method `options(WebClientOptions options)`, you can build an appropriate `WebClientOptions`, which is a vert.x class that allows setting trust store options. Will this work for you?

**Comment by jmartisk** [comment]
I'll close this as it was explained, please let me know should you have further questions
