### ISSUE TITLE
QuarkusUnitTest: proper error message when not in a deployment module

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#30310]
### Description

I wrote a `QuarkusUnitTest` and placed it in a module that is not a deployment module, and the errors I got were puzzling to me:

```
Couldn't make the test class LoginControllerTest an unremovable bean (probably because a dependency on io.quarkus:quarkus-arc-deployment is missing); other beans may also be removed and injection may not work as expected
… lots of things that seemed normal
Could not find LoginControllerTest bean
```

The documentation at https://quarkus.io/guides/writing-extensions mention `These tests should be placed in the deployment module` but really it should be `MUST`. If an error was thrown that detected it was not in a deployment module and told me that it had to be in a deployment module I would have saved a lot of time. This can be helpful to other users.

**Comment by geoand** [comment]
Mind giving https://github.com/quarkusio/quarkus/pull/30319 a try?

**Comment by geoand** [comment]
It turns out that `QuarkusUnitTest` can be used in non `-deployment` modules, so there is not much we can do here
