### ISSUE TITLE
Kafka dev UI is not showing messages from topic

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/quarkus#30321]
### Describe the bug

When connecting to Red Hat OpenShift Streams for Apache Kafka, I can retrieve information from the cluster and the topics. Still, when clicking on the topic to browse the messages available, I get a none.

### Expected behavior

UI shows the messages in the topic

### Actual behavior

The table where I should see the messages is empty

### How to Reproduce?

Create a Kafka Instance in Red Hat OpenShift for Apache Kafka

Configure the quarkus application to use the instance using the `kafka.*` application.properties config format.

Create a topic and send messages.

Use the dev UI from quarkus to browse the messages.

### Output of `uname -a` or `ver`

Darwin hguerrer-mac 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8) OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/hguerrer/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 11.0.16, vendor: Eclipse Adoptium, runtime: /Users/hguerrer/.sdkman/candidates/java/11.0.16-tem Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.1", arch: "x86_64", family: "mac"

**Comment by cescoffier** [comment]
The Dev UI is not intended to connect to "random" Kafka instances, but only the ones that started using dev services. It may work, but if the instance is behind a proxy of some sort, the chances are relatively low.
