### ISSUE TITLE
plz introduce kotlin 1.8

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#30326]
### outdated kotlin version

https://quarkus.io/guides/kotlin#kotlin-version

plz bump the kotlin version at least to 1.7.22 or better directly to 1.8. i have used it locally and it worked perfect. 

with latest java version the kotlin bump to 1.8 is no problem:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/8830888/212023137-380f8541-8c14-49bb-b284-ad4482ccc646.png">

ci as not the latest java but locally i have so it should be fine:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/8830888/212022664-7e0c6609-5f58-4890-8e9c-320bcdc3576f.png">

openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)

Ich bekomme folgende Fehlermeldung: 
```
file:///C:/dev/therapybuilder/02_Software/TherapyExecutor/serverless/src/main/kotlin/com/movisens/therapydesigner/executor/serverless/persistence/repository/TherapyVariableValueRepository.kt:58:39 Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public inline fun <T> Enumeration<TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin.collections
public fun <T> Array<out TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin.collections
public fun BooleanArray.toList(): List<Boolean> defined in kotlin.collections
public fun ByteArray.toList(): List<Byte> defined in kotlin.collections
public fun CharArray.toList(): List<Char> defined in kotlin.collections
public fun CharSequence.toList(): List<Char> defined in kotlin.text
public fun DoubleArray.toList(): List<Double> defined in kotlin.collections
public fun FloatArray.toList(): List<Float> defined in kotlin.collections
public fun IntArray.toList(): List<Int> defined in kotlin.collections
public fun LongArray.toList(): List<Long> defined in kotlin.collections
public fun <T> Pair<TypeVariable(T), TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin
public fun ShortArray.toList(): List<Short> defined in kotlin.collections
public fun <T> Triple<TypeVariable(T), TypeVariable(T), TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin
public fun <T> Iterable<TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin.collections
public fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.toList(): List<Pair<TypeVariable(K), TypeVariable(V)>> defined in kotlin.collections
public fun <T> Sequence<TypeVariable(T)>.toList(): List<TypeVariable(T)> defined in kotlin.sequences
```

Das ist das Ergebnis, wenn ich java --version ausführe: 
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

**Comment by geoand** [comment]
We have [already](https://github.com/quarkusio/quarkus/pull/29673) bumped to Kotlin `1.7.22`. The bump will be available with Quarkus `2.16.0.CR1`

**Comment by punkratz312** [comment]
all right great, thanks for that. could you please consider to go for 1.8 directly. imho there is no big reason or risk against this approach.

our application and test stack is pretty sensitive to issues that might come from or within quarkus, its not the first time we double checc your stuff.

**Comment by geoand** [comment]
We already have a [PR](https://github.com/quarkusio/quarkus/pull/30219) for that, but last time I checked, CI was failing so it will need more work.
