### ISSUE TITLE
With the Kubernetes client version 6, using the client load method forces to register builders for reflection in native mode

### ISSUE THREAD

**Issue by PierreBtz** [quarkusio/quarkus#30336]
### Describe the bug

As explained in the title, when running something like:

```
var resources = kubernetesClient.load(new URL("https://raw.githubusercontent.com/kubernetes/ingress-nginx/5f2a79495a65c57106d8fab00bc95a029c3a8aab/deploy/static/provider/kind/deploy.yaml").openStream()).get();
kubernetesClient.resourceList(resources).createOrReplace();
```

In native mode this will yields an error like:

```
java.lang.IllegalStateException: Failed to create builder for: class io.fabric8.kubernetes.api.model.rbac.ClusterRole
	at io.fabric8.kubernetes.api.builder.BaseFluent.builderOf(BaseFluent.java:31)
	at io.fabric8.kubernetes.api.model.KubernetesListFluentImpl.addToItems(KubernetesListFluentImpl.java:122)
// ommited for brievity
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.model.rbac.ClusterRoleBuilder
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132)
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105)
	at io.fabric8.kubernetes.api.builder.BaseFluent.builderOf(BaseFluent.java:28)
	... 19 more
```

*Workaround*: register all the missing builders for reflection.

I'm not 100% sure that what I'm asking for is reasonable since maybe in the more general case it's desirable not to have all the builders in the native image, but this scenario was working prior to the Kubernetes client version 6, so in a sense it's a regression :)

### Expected behavior

I don't have to declare those builders.

### Actual behavior

Builders are pruned when building the native image.

### How to Reproduce?

Please refer to https://github.com/PierreBtz/quarkus-kubernetes-client-bug:

Have a Kubernetes cluster ready to receive an nginx ingress deployment in the ingress-nginx namespace.

* clone this repository
* run the command as a jar: `mvn quarkus:dev`, observe that the example is working.
* build a native binary (`mvn verify -Pnative`) and run it `./target/quarkus-kubernetes-client-bug-1.0.0-SNAPSHOT-runner`, observe the failure.
* uncomment the annotations, rebuild the binary, observe the example is working.

### Output of `uname -a` or `ver`

Darwin *****.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.16.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Note: I have to run this sample on the release candidate since because of https://github.com/quarkusio/quarkus/issues/29532, this is the first version I can have the `load` method working on this example.

**Comment by geoand** [comment]
Unfortunately there is not much we can do in this case.

What happens here is that because GraalVM never encounters any code that of the Builder types when parsing bytecode, it completely discards the types.
Registering all the Builder for reflection unconditionally is not really an option as it would lead to a huge native binary.
