### ISSUE TITLE
hibernate-orm-rest-data-panache ignores additional resource methods

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#30330]
### Describe the bug

With `quarkus-hibernate-orm-rest-data-panache`, we should be able to define additional methods in a panache resource:
```
@ResourceProperties(path = "/entity")
public interface PersonEntityResource extends PanacheEntityResource<Person, Long> {
    @GET
    @Path("/customGet")
    default void customGet() {
    }
}
```
```
@ResourceProperties(path = "/repository")
public interface PersonRepositoryResource extends PanacheRepositoryResource<PersonRepository, Person, Long> {
    @GET
    @Path("/customGet")
    default void customGet() {
    }
}
```
See also [1].

This does not happen and the custom methods are missing in the generated JAX-RS resources.

With Reactive (e.g. `quarkus-hibernate-reactive-rest-data-panache` + `quarkus-resteasy-reactive-jackson` + `quarkus-reactive-pg-client` in the reproducer), this feature works as expected.

[1] https://quarkus.io/version/main/guides/rest-data-panache#adding-additional-methods-to-the-generated-resource.

### Expected behavior

```
curl -I http://localhost:8080/entity/customGet
HTTP/1.1 204 No Content
```

### Actual behavior

```
curl -I http://localhost:8080/entity/customGet
HTTP/1.1 404 Not Found
```

### How to Reproduce?

```
git clone git@github.com:jsmrcka/orm-rest-data-panache-custom-methods-reproducer.git
cd ./orm-rest-data-panache-custom-methods-reproducer
./mvnw clean test
```

### Output of `uname -a` or `ver`

Linux ... 6.0.15-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by Sgitario** [comment]
@jsmrcka you're missing the `@Produces` annotation. In resteasy reactive, this is automatically added, but not in resteasy classic. 
I've just confirmed that it works with it. I will amend the guide to avoid this confusion.

**Comment by jsmrcka** [comment]
@Sgitario Thank you for the docs fix.
