### ISSUE TITLE
QuarkusTest not passing Authorization

### ISSUE THREAD

**Issue by BobanNikolov** [quarkusio/quarkus#30346]
### Describe the bug

I have Keycloak OIDC server which is used to give me tokens and authorize the user in the application. When I try to write an integration or endpoint test (GraphQL), the authorization throws a strange error. I have put the following dependency :
```xml
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-oidc-server</artifactId>
      <scope>test</scope>
</dependency>
```

The test class is annotated with the following annotations:
```java
@QuarkusTest
@QuarkusTestResource(OidcWiremockTestResource.class)
```

The test is being called with the following  code:
```java
given()
 .when()
 .contentType("application/json")
.auth().oauth2(getAccessToken("test", Set.of("user")))
.body(query)
 .post("/graphql")
.then()
 .statusCode(200);
```

The getAccessToken method has the following:
```java
private String getAccessToken(String userName, Set<String> groups) {
    return Jwt.preferredUserName(userName)
       .groups(groups)
      .claim("roles", List.of("role"))
      .issuer("issuer_url")
      .sign();
```

### Expected behavior

The test should accept the claims that are put into the Jwt and pass the test.

### Actual behavior

Throws 
```
java.lang.reflect.InvocationTargetException
which is caused by:
javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
	at javax.xml.transform.TransformerFactory.newInstance(Unknown Source)
	at com.github.tomakehurst.wiremock.common.xml.Xml.optimizeFactoriesLoading(Xml.java:52)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<clinit>(WireMockApp.java:75)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:73)
	at io.quarkus.test.oidc.server.OidcWiremockTestResource.start(OidcWiremockTestResource.java:55)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:452)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	... 4 more
```

### Output of `java -version`

17

### Quarkus version or git rev

2.8.0-Final

**Comment by geoand** [comment]
I see you are using a pretty old version of Quarkus. Can you try and see if the problem persists with Quarkus `2.15.3.Final`?

**Comment by BobanNikolov** [comment]
The previous error is fixed, but new popped up :(

`WARN: OIDC Server is not available:`
`javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

The OIDC Server is clearly available because localy it works just fine.

**Comment by geoand** [comment]
This is one that perhaps @sberyozkin and / or @michalvavrik could help with

**Comment by BobanNikolov** [comment]
Just for reference, the same error pops up upon starting the application, so it's not about the test.

**Comment by michalvavrik** [comment]
Ad warning in general - `OidcWiremockTestResource` is only mocking required paths (introspection endpoint), so it doesn't provide you with full OIDC server and warning is expected. Your tests should still pass. Personally I'd look to https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-wiremock/src/test/java/io/quarkus/it/keycloak/BearerTokenAuthorizationTest.java for working example (not ssl).

Ad warning exception message - looks like your OIDC server doesn't have trusted certificates (possibly self-signed). For testing only, you can work around it with `quarkus.oidc.tls.verification=none`, here is nice example in docs https://quarkus.io/guides/security-keycloak-authorization#configuring-the-application

Ad reproducer and issue desc - for your latest exception, that's way to little information, full reproducer would safe everyone's (including yours) time :-)

**Comment by BobanNikolov** [comment]
I will try fixing it with the links you provided and if I hit a dead end (hope not), I will make a reproducer and send it your way ASAP.

**Comment by sberyozkin** [comment]
Make sure the `quarkus.oidc.auth-server-url` starts with a `${keycloak.url}` as in the application.properties accompanying the test @michalvavrik linked to, for the link to the Wiremock Keycloak endpoint to resolve.

**Comment by michalvavrik** [comment]
> Make sure the `quarkus.oidc.auth-server-url` starts with a `${keycloak.url}` as in the application.properties accompanying the test @michalvavrik linked to, for the link to the Wiremock Keycloak endpoint to resolve.

hmm, I run couple of scenarios before I replied and I think the error message would be different if the issue was in `quarkus.oidc.auth-server-url` because I could only reproduce it with untrusted certificate; but I can easily be wrong as I certainly didn't test all the scenarios

**Comment by sberyozkin** [comment]
Looks like this one can be closed as @BobanNikolov said a reproducer would be provided if the suggestions above would not help resolving the problem.
@BobanNikolov Please reopen with the reproducer if the problem persists, thanks
