### ISSUE TITLE
Boostrap resolver : Do not merge managed dependencies before collection process

### ISSUE THREAD

**Issue by vietk** [quarkusio/quarkus#3035]
**Describe the bug**
I have a dependency in the pom.xml of my quarkus application that IS managed by the bootstrap resolver out of the << maven resolving policy >> making the build overriding the version of my dependency.

**Expected behavior**
Direct dependencies should not be managed

**Actual behavior**
Direct dependencies are managed

**To Reproduce**
https://github.com/vietk/QuarkusReproducer

I tried to fix that with : #3033

**Comment by radcortez** [comment]
+1

**Comment by tdferreira** [comment]
+1

**Comment by brunobat** [comment]
+1 This was working on v.0.17.0

**Comment by gsmet** [comment]
@vietk @radcortez @tdferreira @brunobat can any of you check that https://github.com/quarkusio/quarkus/pull/3054 fixes the issue for you?

We release the 0.19.0 tomorrow so it would be nice to get a confirmation today. Thanks!

**Comment by radcortez** [comment]
Wonderful. Will test with 0.19. Thanks!

**Comment by vietk** [comment]
@gsmet I tested with the reproducer, and I have the expected result, so I consider this fixed :D 
thanks

**Comment by gsmet** [comment]
@vietk  Thanks for confirming!
