### ISSUE TITLE
OpenTelemetry traces are not exported while running Uber Jar

### ISSUE THREAD

**Issue by UtkarshBhatt** [quarkusio/quarkus#30363]
### Describe the bug

I have implemented the Quarkus and OpenTelemetry integration to generate the traces and see it on Jaeger UI.

The traces are generated and visible when we run the application in dev mode, using `mvn compile quarkus:dev`

But, the traces are not visible when I run the application using the uber jar, using the command: `java -jar <application-uber>.jar`
Also, I am getting below line in the logs (which is not there in case of running application in dev mode).

**No BatchSpanProcessor delegate specified, no action taken**

Logs:

```
15:06:04 WARN  traceId=, parentId=, spanId=, sampled= [io.qu.op.ru.ex.ot.LateBoundBatchSpanProcessor] (vert.x-eventloop-thread-0) No BatchSpanProcessor delegate specified, no action taken.
15:06:04 INFO  traceId=fd64acddc1445f46d0313f87a98e061b, parentId=, spanId=334592b6880dbaa5, sampled=true [co.ro.id.ad.AdminResource] (executor-thread-0) AdminResource : admin
15:06:04 INFO  traceId=fd64acddc1445f46d0313f87a98e061b, parentId=, spanId=334592b6880dbaa5, sampled=true [co.ro.id.ad.AdminService] (executor-thread-0) AdminService : admin
15:06:05 INFO  traceId=c8d83eeef41057f4ec1a0247f71c4e8e, parentId=, spanId=46afa6dbe4f73685, sampled=true [co.ro.id.ad.AdminResource] (executor-thread-0) AdminResource : admin
15:06:05 INFO  traceId=c8d83eeef41057f4ec1a0247f71c4e8e, parentId=, spanId=46afa6dbe4f73685, sampled=true [co.ro.id.ad.AdminService] (executor-thread-0) AdminService : admin
```

Can someone guide about how to proceed with the traces when we run the application using JAR and not using dev mode.

Thanks.

### Expected behavior

The OpenTelemetry traces should be visible on JaegerUI while running the application with JAR file.

### Actual behavior

The application generating the traces when we run application using JAR file. But the traces are not visible on Jaeger UI.

### How to Reproduce?

1. Add dependency for OpenTelemetry in your Quarkus application.
2. Add one endpoint (`/hello`) which returns a string. (this is for testing purpose).
3. Configure `package.type=uber-jar` from application.yaml in order to generate the uber-jar artifact.
4. Run: `mvn clean install` in order to generate the artifact. (i.e, your generated artifact is application-uber.jar
5. Run the application using: `java -jar <application-uber>.jar` 
6. Hit the endpoint `/hello` which will generate the traces in logs.
7. The `traceId` and `spanId` are visible in logs but the same information is not visible in Jaeger UI.

Let me know in case any more details are required.

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by radcortez** [comment]
You must set `quarkus.opentelemetry.tracer.exporter.otlp.endpoint` and point it to your OTel Collector.

In dev mode, we automatically generate the configuration and point it to localhost. We assume the `uber-jar` is to run in production, so we cannot set a default configuration for that endpoint.

We could probably improve the log message.

**Comment by UtkarshBhatt** [comment]
Hi @radcortez , 

Thanks for your reply.

I have already set the `quarkus.opentelemetry.tracer.exporter.otlp.endpoint` property, even though the traces are not getting exported to OTel Collector while running the `uber-jar`.

Also, I have observed below WARN log when I set above property, :
```
07:20:38 WARN  traceId=, parentId=, spanId=, sampled= [io.qu.config] (main) Unrecognized configuration key "quarkus.opentelemetry.tracer.exporter.oltp.e
ndpoint" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

I have added below dependency only (let me know if anything more is required):
```
<dependency>
     <groupId>io.quarkus</groupId>
     <artifactId>quarkus-opentelemetry</artifactId>
</dependency>
```

Please suggest the way for exporting the traces from application to OTel Collector while running `uber-jar`.

Thank you.

**Comment by UtkarshBhatt** [comment]
Hi @radcortez @brunobat Thanks for your inputs. 

I just saw that I have misconfigured the `otlp` property. 

As soon as I configured the correct property, the traces started showing on Jaeger UI and `BatchSpanProcessor delegate` error disappears.

I am closing this issue as it is resolved now.

Thanks a lot for your support and guidance.

**Comment by missaeldenadai** [comment]
Hi @UtkarshBhatt.

Your configuration key "quarkus.opentelemetry.tracer.exporter.oltp.endpoint" appears to be correct. Could you share how it was misconfigured? I'm struggling with the same warning message.

Thanks.

**Comment by brunobat** [comment]
https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.opentelemetry.tracer.exporter.otlp.endpoint expects a proper URI like `http://localhost:4317/`... This is the default value

**Comment by radcortez** [comment]
We need to change this configuration to be required and set the default in `dev` mode only.

I didn't do this yet, because of the big config change coming. Unless you want to include this change in that PR as well.

**Comment by brunobat** [comment]
> We need to change this configuration to be required and set the default in `dev` mode only.
> 
> I didn't do this yet, because of the big config change coming. Unless you want to include this change in that PR as well.

Actually, the spec defines the default and I think we should stick with it.

**Comment by radcortez** [comment]
We probably need to suggest a change.

Aside from this issue, I've seen more people having the same issue. Usually, in production environments, you don't run the collector on `localhost`, and we don't complain either because of the default. You just get some nasty logs that it failed to connect.
