### ISSUE TITLE
Support reading .conf HOCON configuration

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#30376]
### Description

The [com.typesafe config](https://github.com/lightbend/config) is a popular Java configuration library. 

It reads from .conf files following the "HOCON" format (Human-Optimized Config Object Notation).
This format is similar to json, but with some modifications. The full documentation can be viewed [here](https://github.com/lightbend/config/blob/main/HOCON.md).

Some examples of valid HOCON can be viewed [here](https://github.com/lightbend/config#examples-of-hocon).

### Implementation ideas

Since this format is already supported in `smallrye-config-source-hocon`, the implementation should be rather straightforward, very similar to `quarkus-config-yaml`.

**Comment by davidfrickert** [comment]
I have an almost complete implementation of this done, so if you agree this is a desired extension, I'll submit a PR.

**Comment by gsmet** [comment]
@radcortez what's your take on this?

Do we want that? If so, should it live in core or in https://github.com/quarkiverse/quarkus-config-extensions (obviously the latter has my preference but I'm unsure if it's going to break too often or not)?

**Comment by radcortez** [comment]
I'm not opposed to it since it is part of SR Config, but not in core.

@davidfrickert Please, submit the extension to https://github.com/quarkiverse/quarkus-config-extensions.

**Comment by radcortez** [comment]
Yes, please.

**Comment by davidfrickert** [comment]
Closed, will be implemented in: https://github.com/quarkiverse/quarkus-config-extensions/issues/107
