### ISSUE TITLE
Elasticsearch Dev Services restarts container on every auto-compile

### ISSUE THREAD

**Issue by apatrida** [quarkusio/quarkus#30384]
### Describe the bug

In DevMode, when having ElasticSearch dev services enabled and you modify code, causing dev mode to recompile, it restarts the ElasticSearch container on build.

This is not supposed to happen if configuration does not change.

The issue is the comparison of configurations `ElasticSearchDevServicesBuildTimeConfig` has no implementations of `.equals()` nor `hashCode()` so the comparison ALWAYS fails causing a container restart.

### Expected behavior

No restart if configuration did not change.

### Actual behavior

Container restarts every time regardless of wht changed.

**Comment by geoand** [comment]
Thanks for the analysis @apatrida.

Would you be interested in contributing a fix?

**Comment by apatrida** [comment]
sure, I already fixed it in my opensearch version of the same:
https://github.com/sort-dev/quarkus-opensearch

here:
https://github.com/sort-dev/quarkus-opensearch/commit/1d9bfdc1d24a98470fb42f8dead99bcca85bea85

I can do the same change for Quarkus and do a PR.

**Comment by apatrida** [comment]
Will check the standard way other equals/hashcode are written in Quarkus and match to that style if it differs.
