### ISSUE TITLE
Add support for Redis Streams

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#30387]
### Description

Add support for the Redis Streams commands. See:

* https://redis.io/docs/data-types/streams-tutorial/
* https://redis.io/docs/data-types/streams/
* https://redis.io/commands/?group=stream

At the moment, the stream support requires using the low-level API. This enhancement is about adding support for streams into the data source API.

**Comment by PyAntony** [comment]
This is much needed. But not only to add support for Streams commands but to make it work as an extension for Reactive Streams Messaging.

**Comment by cescoffier** [comment]
That issue is just about the data source API. The reactive streams connector should be handled by another issue. Can you open one?

**Comment by PyAntony** [comment]
sure, thanks.
