### ISSUE TITLE
Qute I18N should support standard Java resource bundle filenames

### ISSUE THREAD

**Issue by vagelis-savvas** [quarkusio/quarkus#30382]
### Describe the bug

The I18N part of Qute does not allow someone to use the standard filename convention of Java resource bundle files, meaning we can't have e.g. msg.properties, msg_en.properties and msg_en_US.properties files. I believe it is related to the fact that quarkus.default-locale accepts values in IETF BCP 47 such as en-US, where a hyphen separates the locale components instead of an underscore.

### Expected behavior

Qute should take into account standard Java resource bundle filenames, i.e. ones that separate the locale components with an underscore.

### Actual behavior

Qute only considers resource bundle filenames where the locale components are separated with hyphens.

**Comment by mkouba** [comment]
> I believe it is related to the fact that quarkus.default-locale accepts values in IETF BCP 47 such as en-US, where a hyphen separates the locale components instead of an underscore.

Yes, this is documented in https://quarkus.io/guides/qute-reference#localization: _"The file name consists of the relevant bundle name (e.g. msg) and underscore followed by the ~~locate~~ language tag (IETF)"_. (note that there's a typo: `locate`  -> `language`  ;-)

**Comment by mkouba** [comment]
@vagelis-savvas In fact, we don't require/validate the IETF language tag. I've just verified `message_cs_CZ.properties` in this draft PR https://github.com/quarkusio/quarkus/pull/30391 and it works as expected. Of course, you need to use the same locale string when selecting the current locale, i.e. `@Localized("cs_CZ")` and `templateInstance.setAttribute("locale", "cs_CZ")`.

What kind of error did you get in your application?

**Comment by vagelis-savvas** [comment]
@mkouba Hello, I've created a MCVE here https://github.com/vagelis-savvas/code-with-qute-mcve which I bootstrapped from  code.quarkus.io

I've only added an I18N 'greet' key: I use a @MessageBundle interface, some resource bundle files and edited the page.qute.html template to have a {msg:greet} instead of the hardcoded 'Hello'
If you mvn quarkus:dev you will see the errors.
If you rename the msg_en_US.properties and msg_en_GB.properties to msg_en-US.properties and msg_en-GB.properties it works.

**Comment by mkouba** [comment]
Hm, so the build fails because `org.acme.AppMessages.greet()` defines no message && `MessageBundle#locale()` for `AppMessages` is the default locale specified via the `quarkus.default-locale` (`${user.language:en}-${user.country:}` by default; e.g. `en-US`). As a result Qute attempts to find the `msg_en-US.properties` file. It works if you do `@MessageBundle(locale = "en_US") public interface AppMessages {}`.

In any case, we can just convert the locale info from the file to the expected language tag, i.e. replace `_` with `-`; see https://github.com/quarkusio/quarkus/pull/30391.
