### ISSUE TITLE
OIDC extension does not describe a capability

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#30386]
I want to check if certain extensions are available or not. I found that this is best done by checking the available capabilities. I arrived at a dead end as I found that the oicd extension currently does not describe a cabability.
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/pom.xml

Please add a capability to to the oidc  extension.

**Comment by geoand** [comment]
@HerrDerb would you be interested in contributing this enhancement?

**Comment by HerrDerb** [comment]
@geoand already is: https://github.com/quarkusio/quarkus/pull/30388

**Comment by sberyozkin** [comment]
Fixed by #30388
