### ISSUE TITLE
Explicit quarkus.datasource.devservices.enabled=true makes devservices restart DB container on live reload

### ISSUE THREAD

**Issue by plevart** [quarkusio/quarkus#30390]
### Describe the bug

Dev mode restarts database (mysql) container on liver reload when there's an explicit property in `application.properties`:

`quarkus.datasource.devservices.enabled=true`

When there's no such explicit property (the default value `true` doesn't count), database container is not restarted on live reload.

### Expected behavior

No restart is expected always.

### Actual behavior

DB container is restarted and data is lost after live reload.

### Additional information

Here's a debug session when live reload triggers container restart (class DevServicesDatasourceProcessor):

![image (1)](https://user-images.githubusercontent.com/1580058/212667395-9b658922-fadd-4de4-8158-8c554232348a.png)

..the `cachedProperties` at that time only contains the following two entries:

![image (2)](https://user-images.githubusercontent.com/1580058/212667546-c25601dd-3ace-4968-8a1e-b7a28c951326.png)

**Comment by geoand** [comment]
@plevart it seems like you have done some nice investigation work. Do you perhaps have a fix in the works?

**Comment by plevart** [comment]
I think @alesj is volunteering to fix this. Right @alesj ?

**Comment by alesj** [comment]
Yeah, just assigned it to myself ... but need to finish some gRPC work before.
