### ISSUE TITLE
Extend mail client to support Gmail SMTP server

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3039]
This issue covers:

* the test of the mail client with Gmail SMTP server
* the update of the guide to explain the required configuration

Requires Vert.x 3.8

**Comment by Dufgui** [comment]
I will take a look at it

**Comment by Dufgui** [comment]
Hello,

i test to send a simple mail and a second one with attachement and it's work with vertx 3.7.1.
We must just before set an application password in the gmail account. and put it in the code.
`mailer.client = MailClient.createShared(mailer.vertx,
                new MailConfig().setPort(587).setStarttls(StartTLSOptions.REQUIRED).setHostname("smtp.gmail.com")
                        .setPassword("myGeneratedApplicationPassword").setUsername("guillaume.duff@gmail.com"));`

**Comment by Dufgui** [comment]
So I will create a PR for the doc update

**Comment by Akejelu-Nelu** [comment]
I have difficulty in getting the response code for each email i sent with reactive mailer.

 return reactiveMailer.send(mail)
                .subscribeAsCompletionStage()
                .thenApply(response -> Response.accepted().build())
                .exceptionally(throwable -> Response.serverError().build());

this is what my return statement looks like after building the mail. The mail object also has a list of recipients. I'm not sure how i can get the response code / status of that email if it was sent or not. Any suggestion is appreciated.

**Comment by cescoffier** [comment]
`reactiveMailer.send(mail)` produces a failure if the mail cannot be sent to the SMTP server. Now, it's an email, you can't know if the mail is delivered to all the recipients.
