### ISSUE TITLE
Native image S2I build support

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#304]
Would you guys have any interest in a contribution (from me..) for OpenShift S2I support?

Background & "motivation" for this is that, AFAIK `oc new-build --binary` ([as doc here](http://10.8.247.58/nfs/protean/kubernetes-guide.html#deploying-the-application-in-openshift)) from a `Dockerfile` is not always available in all OpenShift instances. For example, AFAIK we don't enable that in our own OpenShift Online (at least in our free tier; it's security related); the same may be the case for future customers.

Full disclosure: I've some S2I experience as the current maintainer over on [fabric8io-images/s2i](https://github.com/fabric8io-images/s2i) ... see also [this blog post where](http://blog2.vorburger.ch/2018/11/s2i-with-java-11-gradle-builds-for.html) I introduced [Java 11 and Gradle support](https://github.com/fabric8io-images/s2i/blob/master/CHANGELOG.md) for that S2I Java Builder.

The way I imagine this would work is that there would have to be a `protean-s2i` Builder image (perhaps extending _s2i-java)_ which would have to include the GraalVM binary, build with `-Pnative` (and probably `-Dnative-image.docker-build=true` althought I don't yet get what that's really good for..), and then copy and launch the built native, instead of `java -jar` - just [like the example Dockerfile](https://github.com/jbossas/protean-quickstarts/blob/master/getting-started-native/Dockerfile) (but a new TBD _getting-started-native-s2i protean-quickstarts_ would have no Dockerfile).

I do fully realize that with where S2I stands right now, this will lead to a horribly fat image, which will include the Graal VM. While we could hack it to wipe that (as an option, as that prevents incremental builds), which would help for security but may be not even for image size (layers?), the longer term solution is work in S2I (Knative build?) to sort this out; see e.g. https://github.com/fabric8io-images/s2i/issues/180 (and https://github.com/fabric8io-images/s2i/issues/192). I would propose to let such possible future work be out of scope of this initial issue.

If this isn't a priority or actively not welcome because you have other plans, just say so & close this.

**Comment by siamaksade** [comment]
Image size is very important for the S2I native build. [Chained builds](https://docs.openshift.com/container-platform/3.11/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds) might help with that a bit. One build produces the binary, the chained build lays it over a minimal image.

**Comment by vorburger** [comment]
This issue is now about *Native* image S2I build support; #1306 is about non-native Java S2I building.

**Comment by vorburger** [comment]
Closing this issue as I consider this Done with today's merge of #1358.
