### ISSUE TITLE
Warning: Option 'AllowVMInspection' is deprecated and might be removed from future versions: Please use --enable-monitoring

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#30408]
### Describe the bug

When running a native build with `-Dquarkus.native.enable-vm-inspection=true`, then the message below is issued:

```
Warning: Option 'AllowVMInspection' is deprecated and might be removed from future versions: Please use --enable-monitoring
```

### Expected behavior

Now warning should be issued.

### How to Reproduce?

`mvn clean package -Dnative -Dquarkus.native.enable-vm-inspection=true`

### Output of `uname -a` or `ver`

Linux 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM 22.3.0 Java 17 CE (Java Version 17.0.5+8-jvmci-22.3-b08)

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
Good catch!

https://github.com/quarkusio/quarkus/pull/30410 should take care of the issue

**Comment by aldettinger** [comment]
Nice @geoand, many thanks for the pr :clap:
