### ISSUE TITLE
quarkus-test-security-(jwt and oidc): support non-string claims (integers, arrays, maps)

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#30442]
### Description

Currently the `quarkus-test-security-jwt` extension only supports configuring `String` claims, so it becomes a little difficult to configure more complex claims.
For example, my code needs to read the `exp`, `iat`, `realm_access` claims, which are not `String` claims.
It isn't very hard to adapt my code to parse these claims as `String` if necessary, but it is a bit bothersome as this code should not be necessary.

Example:

```
@Test
@TestSecurity(user = "testUser", roles = {"active_user"})
@JwtSecurity(
		claims = {
			@Claim(key = "language", value = "pt"),
			@Claim(key = "country", value = "PT"),
			@Claim(key = "exp", value = "9999999999"),
			@Claim(key = "iat", value = "0"),
			@Claim(key = "azp", value = "test"),
			@Claim(key = "sub", value = "testUser"),
			@Claim(key = "realm_access", value = "{\"roles\":[\"active_user\"]}")
		}
)
void activateCampaign_ValidPayload() {

}
```

Can you add support for this extension to, at least, map `JSON` and `Array` type claims properly?

**Comment by sberyozkin** [comment]
We probably need to add a `@type` property to `Claim`, to give hints to the jwt test security, as guessing if "3" is a string or a number won't really work.
@davidfrickert Can you clarify how you access these map/array claims in the code ? As JSONB JsonObject/JsonArray objects which is what `JsonWebToken` supports ?

**Comment by davidfrickert** [comment]
@sberyozkin I'm using `getClaim` into `Map<String, List<JsonString>>` (javax.json), which seems to work in real use. It doesn't work currently all claims are mapped into `String`. The `type` property sounds like a good idea. I think that `quarkus-test-security-oidc` also has this problem.

```
// (...)

if (principal instanceof JsonWebToken jwt) {
	MDC.put(MdcConstants.AUTH_EXPIRES_AT, Instant.ofEpochSecond(Long.parseLong(jwt.getClaim(Claims.exp))).toString());
	MDC.put(MdcConstants.AUTH_CLIENT_ID, jwt.getClaim(Claims.azp));
	MDC.put(MdcConstants.AUTH_SUBJECT, jwt.getSubject());
	final Map<String, List<JsonString>> realmAccess = jwt.getClaim("realm_access");
		MDC.put(MdcConstants.AUTH_ROLES, String.join(",",realmAccess.get("roles")
									.stream()
									.map(JsonString::getString).toList()));
				}
//...
```

**Comment by sberyozkin** [comment]
Thanks @davidfrickert This cast works because JsonObject is an instance of Map as far as I recall, I think we can introduce a type hint like `jsonobject`, `jsonarray` and it will be parsed into either `JsonObject` or `JsonArray`

**Comment by davidfrickert** [comment]
That would be great @sberyozkin 
Those are the most important I think, but please add support for `int` / `long` as well. (not sure if the implementation will have a limited set of types or if will just receive a `Class`) 

For now, I'll add a hammer to parse these claims as string if needed but hopefully I will be able to delete it sometime after this issue is complete!

**Comment by sberyozkin** [comment]
There is a queue of issues but this one seems simple enough to get fixed so I might be able to handle it soon enough
