### ISSUE TITLE
Ability to set validation mode using a hibernate-orm property

### ISSUE THREAD

**Issue by VadimPostu** [quarkusio/quarkus#30448]
### Description

I am using quarkus platform version: 2.9.2.Final

I have a use-case where I need to disable the hibernate validation of entities but still be able to control it on demand, in a later step, by using an injected Validator.

It seems like this is currently possible only using a persistence.xml file where the property <property name="javax.persistence.validation.mode" value="NONE"/> is set.

Using a persistence.xml is a step back and adds some configuration burdens on the project this is why I'd prefer to have a property using which the validation mode could be controlled.

P.S. I've tried with: quarkus.hibernate-orm.unsupported-properties."javax.persistence.validation.mode"=NONE
but it still did not work

### Implementation ideas

Would be nice to have a hibernate-orm property: **quarkus.hibernate-orm.validation.mode**  that controls how the hibernate validator behaves.

**Comment by yrodiere** [comment]
Hu, that's interesting. Indeed, it seems we force Hibernate Validator to be enabled in Hibernate ORM and don't provide a way to disable it if it's in the classpath:

https://github.com/quarkusio/quarkus/blob/00433dc1d4bdf8145241d4620277a94ddf7096b1/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1177-L1181

@gsmet Any objection to adding `quarkus.hibernate-orm.validation.mode`?

**Comment by mfpc** [comment]
Hi,

I'm working on it.

**Comment by mfpc** [comment]
Hi,

Could anyone confirm if this solutions  can applied. Before the if  below check if the propertie was setted.
`if (capabilities.isPresent(Capability.HIBERNATE_VALIDATOR)) {`

**Comment by gastaldi** [comment]
I think it would be better to have a `quarkus.hibernate-orm.validation-enabled` boolean (true by default) that sets the 
`AvailableSettings.JPA_VALIDATION_MODE` to `CALLBACK` or `NONE` only if the `HIBERNATE_VALIDATOR` capability is present

**Comment by yrodiere** [comment]
> I think it would be better to have a `quarkus.hibernate-orm.validation-enabled` boolean (true by default) that sets the `AvailableSettings.JPA_VALIDATION_MODE` to `CALLBACK` or `NONE` only if the `HIBERNATE_VALIDATOR` capability is present

+1

I'd suggest `quarkus.hibernate-orm.validation.enabled` though, just in case we need to introduce other `quarkus.hibernate-orm.validation.*` settings.

**Comment by yrodiere** [comment]
That being said, if `quarkus.hibernate-orm.validation.enabled` is `true` and HV is not in the classpath, shouldn't we fail, just to make sure the user knows validation is NOT enabled?

**Comment by gastaldi** [comment]
> That being said, if `quarkus.hibernate-orm.validation.enabled` is `true` and HV is not in the classpath, shouldn't we fail, just to make sure the user knows validation is NOT enabled?

What happens in Hibernate if the ValidationMode is set to `CALLBACK` if no Validator provider is found?

**Comment by yrodiere** [comment]
It's supposed to fail:

```
    /**
     * The persistence provider must perform the lifecycle event
     * validation.  It is an error if there is no Bean Validation
     * provider present in the environment.
     */
    CALLBACK,
```

**Comment by mfpc** [comment]
Hi,

If my understanding is correct, my piece of code below is correct only have to create a test for it ?

  

>  

> if (capabilities.isPresent(Capability.HIBERNATE_VALIDATOR)) {
> 
>             if (persistenceUnitConfig.validationEnabled) {
>                 descriptor.getProperties().setProperty(AvailableSettings.JPA_VALIDATION_MODE, ValidationMode.CALLBACK.name());
>             } else {
>                 descriptor.getProperties().setProperty(AvailableSettings.JPA_VALIDATION_MODE, ValidationMode.NONE.name());
>             }
>         }

**Comment by yrodiere** [comment]
@mfpc It seems correct, yes.

**Comment by mfpc** [comment]
Hi,

Could you describe the best scenario for this test? 

Best Regards,
Marcell Cruz
