### ISSUE TITLE
quarkus-test-security-jwt: injecting org.eclipse.microprofile.jwt.JsonWebToken injects a NullJsonWebToken instance

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#30445]
### Describe the bug

When using the `quarkus-test-security-jwt` extension, like this:

```
@Test
@TestSecurity(user = "testUser", roles = {"active_user"})
@JwtSecurity(
	claims = {
		@Claim(key = "language", value = "pt"),
		@Claim(key = "country", value = "PT"),
		@Claim(key = "exp", value = "9999999999"),
		@Claim(key = "iat", value = "0"),
		@Claim(key = "azp", value = "test"),
		@Claim(key = "sub", value = "testUser"),
	}
)
void activateCampaign_ValidPayload() {
    //....
}
```

If I have some class that wants to read data from the JWT:

```
@RequestScoped
public class AuthenticationIdentity {

	private static final Logger log = LoggerFactory.getLogger(AuthenticationIdentity.class);
	private final JsonWebToken jwt;

	AuthenticationIdentity() {
		this.jwt = null;
	}

	@Inject
	public AuthenticationIdentity(JsonWebToken jwt) {
		if (!jwt.containsClaim("language") || !jwt.containsClaim("country") ||
			!jwt.containsClaim("sub")) {
			UnauthorizedException exception = new UnauthorizedException();
			log.warn("JsonWebToken not valid");
			throw exception;
		}
		this.jwt = jwt;
	}
}
```

The test jwt is not what is injected here, I actually get a `NullJsonWebToken` instance.
In order to actually get the test jwt here, I had to instead receive a `CurrentIdentityAssociation` and from that, fetch the jwt:

```
@RequestScoped
public class AuthenticationIdentity {

	private static final Logger log = LoggerFactory.getLogger(AuthenticationIdentity.class);
	private final JsonWebToken jwt;

	AuthenticationIdentity() {
		this.jwt = null;
	}

	@Inject
	public AuthenticationIdentity(CurrentIdentityAssociation identityAssociation) {
		final Principal principal = identityAssociation.getIdentity().getPrincipal();

		if (principal instanceof JsonWebToken jwt) {
			if (!jwt.containsClaim("language") || !jwt.containsClaim("country") ||
				!jwt.containsClaim("sub")) {
				UnauthorizedException exception = new UnauthorizedException();
				log.warn("JsonWebToken not valid");
				throw exception;
			}
			this.jwt = jwt;
		} else {
			throw new UnauthorizedException("No JWT token found");
		}
	}
}
```

Not sure if this is intended, or a bug. I'd say it's a bug as the test jwt should be injected here and not a `NullJsonWebToken`.

### Expected behavior

Classes that inject `JsonWebToken` should receive the test token when `quarkus-test-security-jwt` is in use.

### Actual behavior

Classes that inject `JsonWebToken` a `NullJsonWebToken` instance, when `quarkus-test-security-jwt` is in use. 

### How to Reproduce?

Create a test that uses `quarkus-test-security-jwt`, like so: 

```
class TestJwtSecurity {
    @Test
	@TestSecurity(user = "testUser", roles = {"active_user"})
	@JwtSecurity(
		claims = {
			@Claim(key = "language", value = "pt"),
			@Claim(key = "country", value = "PT"),
			@Claim(key = "exp", value = "9999999999"),
			@Claim(key = "iat", value = "0"),
			@Claim(key = "azp", value = "test"),
			@Claim(key = "sub", value = "testUser"),
			@Claim(key = "realm_access", value = "{\"roles\":[\"active_user\"]}")
		}
	)
	void activateCampaign_ValidPayload() {
	
	}
}
```

Create a class that injects `JsonWebToken` and performs some validations: 

```
@RequestScoped
public class AuthenticationIdentity {

	private static final Logger log = LoggerFactory.getLogger(AuthenticationIdentity.class);
	private final JsonWebToken jwt;

	AuthenticationIdentity() {
		this.jwt = null;
	}

	@Inject
	public AuthenticationIdentity(CurrentIdentityAssociation identityAssociation) {
		final Principal principal = identityAssociation.getIdentity().getPrincipal();

		if (principal instanceof JsonWebToken jwt) {
			if (!jwt.containsClaim("language") || !jwt.containsClaim("country") ||
				!jwt.containsClaim("sub")) {
				UnauthorizedException exception = new UnauthorizedException();
				log.warn("JsonWebToken not valid");
				throw exception;
			}
			this.jwt = jwt;
		} else {
			throw new UnauthorizedException("No JWT token found");
		}
	}
}
```

Run the test. It will fail since it will inject a `NullJsonWebToken`, instead of the test token with the custom claims.

### Output of `uname -a` or `ver`

Linux PM-DFrickert 6.1.6-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jan 15 02:14:14 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+1) OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/maven Java version: 17.0.5, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.1.6-1-manjaro", arch: "amd64", family: "unix"

**Comment by sberyozkin** [comment]
@davidfrickert Hmm, [this test](https://github.com/quarkusio/quarkus/blob/main/integration-tests/smallrye-jwt-token-propagation/src/test/java/io/quarkus/it/keycloak/TestSecurityLazyAuthTest.java#L53) is passing though, can you create a reproducer please ?

**Comment by davidfrickert** [comment]
@sberyozkin https://github.com/davidfrickert/quarkus-issue-reproducer/tree/30445

**Comment by sberyozkin** [comment]
@davidfrickert Thanks, can you please check what happens if you inject JsonWebToken directly into the resource class, and what happens if you remove `@RequestScoped` ?

**Comment by davidfrickert** [comment]
@sberyozkin 

Replaced `@RequestScoped` with `@ApplicationScoped` => doesn't work => https://github.com/davidfrickert/quarkus-issue-reproducer/tree/30445-application-scoped

Direct injection of jwt into Resource class => doesn't work => https://github.com/davidfrickert/quarkus-issue-reproducer/tree/30445-jwt-inject-into-resource

Direct injection of jwt into Resource class and Replaced `@RequestScoped` with `@ApplicationScoped` => doesn't work => https://github.com/davidfrickert/quarkus-issue-reproducer/tree/30445-jwt-inject-into-resource-application-scoped

Not sure if i'm doing something wrong, but none of them seem to work unfortunately.

**Comment by sberyozkin** [comment]
@davidfrickert 
The problem is that you combine `quarkus-oidc` and `quarkus-test-security-jwt` as opposed to `quarkus-test-security-oidc` the former is recommended for testing with `smallrye-jwt` in the JWT docs, the latter - with OIDC  in the OIDC docs.
The reason you need to use `quarkus-test-security-oidc` with `quarkus-oidc` not only because it offers more OIDC specific support, but mainly because it sets `AccessTokenCredential` and `IdTokenCredential` expected by the OIDC JWT producers.
The fix is here:
```
diff --git a/pom.xml b/pom.xml
index 909cff6..6467f24 100644
--- a/pom.xml
+++ b/pom.xml
@@ -57,7 +57,7 @@
     </dependency>
     <dependency>
       <groupId>io.quarkus</groupId>
-      <artifactId>quarkus-test-security-jwt</artifactId>
+      <artifactId>quarkus-test-security-oidc</artifactId>
       <scope>test</scope>
     </dependency>
   </dependencies>
diff --git a/src/test/java/org/acme/GreetingResourceImplTest.java b/src/test/java/org/acme/GreetingResourceImplTest.java
index 5374c1b..88c6637 100644
--- a/src/test/java/org/acme/GreetingResourceImplTest.java
+++ b/src/test/java/org/acme/GreetingResourceImplTest.java
@@ -2,8 +2,8 @@ package org.acme;
 
 import io.quarkus.test.junit.QuarkusTest;
 import io.quarkus.test.security.TestSecurity;
-import io.quarkus.test.security.jwt.Claim;
-import io.quarkus.test.security.jwt.JwtSecurity;
+import io.quarkus.test.security.oidc.Claim;
+import io.quarkus.test.security.oidc.OidcSecurity;
 import org.junit.jupiter.api.Test;
 
 import static io.restassured.RestAssured.given;
@@ -14,7 +14,7 @@ public class GreetingResourceImplTest {
 
     @Test
     @TestSecurity(user = "testUser", roles = {"arole"})
-    @JwtSecurity(
+    @OidcSecurity(
             claims = {
                     @Claim(key = "language", value = "pt"),
                     @Claim(key = "country", value = "PT"),
@@ -32,4 +32,4 @@ public class GreetingResourceImplTest {
                 .body(is("Hello testUser"));
     }
 
-}
\ No newline at end of file
+}
``` 
Thanks

**Comment by davidfrickert** [comment]
Thanks @sberyozkin.
Sorry, I should have done that as I actually knew about that dependency, but thought that the jwt dependency would work.

**Comment by davidfrickert** [comment]
Well I just tested this and if i switch to `quarkus-test-security-oidc` my code blows up :D 

```
2023-01-23 17:34:40,787 WARN  [io.sma.jwt.aut.principal] (vert.x-eventloop-thread-2) SRJWT08002: getClaimValue failure for: exp: org.jose4j.jwt.MalformedClaimException: The value of the 'exp' claim is not the expected type (9999999999 - Cannot cast java.lang.String to java.lang.Long)
	at org.jose4j.jwt.JwtClaims.getClaimValue(JwtClaims.java:256)
	at io.smallrye.jwt.auth.principal.DefaultJWTCallerPrincipal.getClaimValue(DefaultJWTCallerPrincipal.java:110)
	at io.smallrye.jwt.auth.principal.JWTCallerPrincipal.getClaim(JWTCallerPrincipal.java:75)
	at org.eclipse.microprofile.jwt.JsonWebToken.getClaim(JsonWebToken.java:158)
```

I guess I will stick to `quarkus-test-security-jwt` until #30442 is completed and released.
@sberyozkin
