### ISSUE TITLE
Reactive Messaging - Implement a HTTP & WebSocket connector for Quarkus

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3044]
this issue is about implementing a Reactive Messaging Connector that:

* receives HTTP request and wrap them into a `Message`
* call HTTP endpoints for each received `Message`
* receives WebSocket message and wrap them into a `Message`
* support SSE and SockJS

**Comment by michalszynkiewicz** [comment]
does this task depend on any tasks in other projects?

**Comment by cescoffier** [comment]
No, this task is about implementing a Connector in Quarkus. As it's quarkus specific, it should not involve any code in the upstream project.

**Comment by michalszynkiewicz** [comment]
A few notes from conversations with Clement:

Supported methods: `PUT`, `POST`.

Types supported out of the box: (at least) `Json` and `byte[]`

Example configuration:
```
mp.messaging.my-channel.connector=quarkus-http
mp.messaging.my-channel.path=/foo
mp.messaging.my-channel.verb=post
```

The http endpoint should return `202 Accepted` and pass the message to the stream.

**Comment by michalszynkiewicz** [comment]
Update:
`JsonObject`, `String`, `byte[]` supported; may need to support `ProtoBuf`

Pausing the works waiting for undertow on vert.x

**Comment by michalszynkiewicz** [comment]
please keep it

**Comment by questionaut** [comment]
Does it mean Quarkus does not support reactive websockets similar to Spring WebFlux/Websockets?

**Comment by cescoffier** [comment]
It does, it's just not integrated with Reactive Messaging yet.

**Comment by michalszynkiewicz** [comment]
I'm thinking of resurrecting this, wdyt @cescoffier ?

**Comment by cescoffier** [comment]
Yes, it would be nice
