### ISSUE TITLE
Return protobuf from JAX-RS endpoint

### ISSUE THREAD

**Issue by Plawn** [quarkusio/quarkus#30451]
### Description

Allow returning a protobuf, from a JAXRS endpoint like a classical POJO

The POJO could be generated and handled by the developper (using the correct .proto format)

Using the presence of  "accept":"application/x-protobuf" (or the correct answer), the endpoint would return the protobuf or the json format if absent

### Implementation ideas

\o/ ?

**Comment by geoand** [comment]
What's the use case for this?

**Comment by Plawn** [comment]
I want to use protobuf instead of JSON in my applications for performance purposes, and making this available make it idiomatic

**Comment by geoand** [comment]
@alesj @cescoffier WDYT?

**Comment by cescoffier** [comment]
It's not that simple. First, if you pay the price to use proto, why using Jax-RS and not switch to gRPC, which is much richer. Indeed, both your client and server will need to handle that format.

Then, this requires adding a code generation phase to RestEasy reactive. It's possible but not that simple, as this generation cannot reuse the gRPC one (maybe actually, if you omit the services). However you will likely generate too much. 

Finally, I'm wondering if it's not already possible with the right interceptor. If we omit the generation part, can an interceptor handle the serialization and deserialization?

On a different note, we are looking at providing a jaxrs-like approach to gRPC. It's planned for Q4

**Comment by Plawn** [comment]
Indeed, I will look into using Grpc instead then

**Comment by Plawn** [comment]
Sorry, to reopen, I forgot this point:
The need was also to avoid using a proxy layer to transform the grpc traffic to http traffic and using a performance binary format instead of JSON without having the whole infrastructure

**Comment by cescoffier** [comment]
Sounds like you would need gRPC web. This is on the roadmap (and also it's a bit my nemesis).

**Comment by geoand** [comment]
@cescoffier if you and @alesj need help with that, I can try and assist

**Comment by cescoffier** [comment]
At the moment, it's in the hands of the vertx team.

**Comment by geoand** [comment]
Okay 👌

**Comment by treo** [comment]
@cescoffier 
> At the moment, it's in the hands of the vertx team.
Is there github issue or something that one can follow for any news on this?

@Plawn 
You probably want something like this: https://gist.github.com/AlexJReid/e894346ee252326fa941a5d3d7486696

I haven't tried it with Quarkus yet, but given that it is using JAX-RS functionality (MessageBodyReader, MessageBodyWriter), I expect that it should work.

**Comment by Plawn** [comment]
@treo Looks like what I need !

**Comment by cescoffier** [comment]
@Plawn if the approach mentioned by @treo works, yes.

**Comment by geoand** [comment]
Closing as per the comments above
