### ISSUE TITLE
RestClient does not suppport _ in url

### ISSUE THREAD

**Issue by Kizoku-Dev** [quarkusio/quarkus#30463]
### Describe the bug

I configured the base url through the application.yml. My url is working as I can request it through postman for exemple.
The URL is : http://test.some_url.domain.com
As you can see there is an _ in the URL. If I run the app with this when I try to make a call through the rest client, it try to connect to locahost instead of my URL.
But when I try an URL without _ or when I call my rest service through the IP instead of the URL it works.

### Expected behavior

Rest client connect to my URL in order to process my call.

### Actual behavior

Rest client try to connect to localhost.
![trace](https://user-images.githubusercontent.com/7711201/213390166-a63ef3fd-93c1-43c9-96dc-ee5d6f13691e.PNG)

### Quarkus version or git rev

2.15.3

### Additional information

When I use the URL with an _ I can see that my rest client is build with the URL in its authority field.
![authority](https://user-images.githubusercontent.com/7711201/213390194-090b1acc-a773-4293-84df-9ad79395d723.PNG)

When I use the URL without an _ or with an IP I can see that my rest client is build with the URL in its host field.
![host](https://user-images.githubusercontent.com/7711201/213391179-da94f8cd-8849-473d-9387-094701bc1aff.PNG)

**Comment by geoand** [comment]
Very interesting...

We'll take a look soon

**Comment by gsmet** [comment]
Hmmm, is `_` actually valid in domain names?

**Comment by geoand** [comment]
I'm looking into that now

**Comment by geoand** [comment]
It appears that host names are limited to letters-digits-hyphen according to [RFC 1123](http://www.ietf.org/rfc/rfc1123.txt), section 2.1 "Host Names and Numbers".

**Comment by gsmet** [comment]
I'm not saying we should fix this but the error we throw is a bit weird to me.

@Kizoku-Dev if you provide a small reproducer, I will have a look at trying to improve the user feedback.

**Comment by gsmet** [comment]
My guess is that you should have a better error message with the following PR: https://github.com/quarkusio/quarkus/pull/30490 .

I'm closing this. If you can come up with a small reproducer, please attach it so I can make sure the error message is now actionable.
