### ISSUE TITLE
queryConfigEnabled config property missing from SwaggerUI config

### ISSUE THREAD

**Issue by dastrobu** [quarkusio/quarkus#30464]
### Describe the bug

in #12782 support for configuring [SwaggerUI properties](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) was added. 
However, the property `queryConfigEnabled` seems to be missing from the config.

### Expected behavior

`quarkus.swagger-ui.query-config-enabled=true`
or 
`quarkus.swagger-ui.queryConfigEnabled=true`
allows to set the respective config property for swagger ui.

### Actual behavior

noting happened when the property is set.

**Comment by gsmet** [comment]
You would need to change things there:
- https://github.com/quarkusio/quarkus/blob/main/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
- https://github.com/quarkusio/quarkus/blob/main/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java#L196

**Comment by phillip-kruger** [comment]
You would have to first add this in SmallRye OpenAPI (see https://github.com/smallrye/smallrye-open-api/blob/main/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/Option.java).

**Comment by mfpc** [comment]
I will work on it.

**Comment by mfpc** [comment]
https://github.com/smallrye/smallrye-open-api/pull/1366
