### ISSUE TITLE
[Extension Proposal] Java Money

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#30468]
### Description

I would like to create an extension for the Java Money RI Moneta library so that it can be used seamlessly in Quarkus.

### Repository name

quarkus-moneta

### Short description

Quarkus JSR 354 Java Money Extension

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- javamoney
- jsr354
- currency

### Team Members

- andlinger
- holzleitner

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by gsmet** [comment]
Hey @andlinger 

Is Moneta still alive? I see the latest version was published mid-2020.

What would be necessary for it to work? Some reflection registration?

**Comment by andlinger** [comment]
The official JSR status is ´Maintenance`. So it can be considered as not inactive.
The library uses java SPI to initialize components. I just started a GitHub discussion to find out, how to implement it best.
https://github.com/quarkusio/quarkus/discussions/30466
