### ISSUE TITLE
gRPC server started although no services exist

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#30476]
### Describe the bug

We use the `quarkus-grpc` to consume gRPC services. After updating the `2.15.3`, seems that gRPC server is started although we are not exposing any services, we just have clients. This was previously not the case. Seem that there is also no option to disable the gRPC server.

```
WARN  [main] 2023-01-19 13:04:40,715 GrpcServerRecorder.java:108 - Using legacy gRPC support, with separate new HTTP server instance. Switch to single HTTP server instance usage with quarkus.grpc.server.use-separate-server=false property
INFO  [vert.x-eventloop-thread-1] 2023-01-19 13:04:40,852 GrpcServerRecorder.java:223 - gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
INFO  [main] 2023-01-19 13:04:40,884 Channels.java:216 - Creating Netty gRPC channel ...
```

We also have `quarkus.grpc.dev-mode.force-server-start` set to `false` which also has no influence now and the server is started. This was also not the case before.

### Expected behavior

Do not start the gRPC server.

### Quarkus version or git rev

2.15.3

**Comment by ivansenic** [comment]
> That's expected in dev mode, but it should not start it in prod mode.

How is it expected in the dev mode? From the configuration documentation:

```
[quarkus.grpc.dev-mode.force-server-start](https://quarkus.io/guides/all-config#quarkus-grpc_quarkus.grpc.dev-mode.force-server-start)

Start gRPC server in dev mode even if no gRPC services are implemented. By default set to true to ease incremental development of new services using dev mode.
```

So having the `quarkus.grpc.dev-mode.force-server-start=false` should also not start it in the dev mode as well.

**Comment by cescoffier** [comment]
hum, let me check, maybe we are ignoring this config property.

This property won't be used for the new server as it's the main HTTP server.

**Comment by cescoffier** [comment]
Just checked: `quarkus.grpc.dev-mode.force-server-start=false` is handled as expected (tried on the `main` branch). 

Note that it's a build-time property.

**Comment by cescoffier** [comment]
@ivansenic any update?

**Comment by ivansenic** [comment]
Hey @cescoffier, what do you need from me? A reproducer?

**Comment by cescoffier** [comment]
Yes, that would be awesome.

My attempts failed to reproduce the issue. But I may be missing something.

**Comment by ivansenic** [comment]
Will do it by the EOB.

**Comment by ivansenic** [comment]
@cescoffier I am sorry, but you are fully correct here. The issue does not exist and this can be closed.

It was a mistake in our code. However, let me give you few details on how this happened. Maybe there is a small issue here. The PR that fixes the code in question is here: https://github.com/stargate/stargate/pull/2410

So what happened:
* I wanted to create a retriable implementation of the grpc client
* However, I was getting a strange build-time error, like this:
  ```
  [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final:build (default) on project sgv2-docsapi: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  [ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: A gRPC service bean must be annotated with @io.quarkus.grpc.GrpcService: CLASS bean [types=[io.stargate.sgv2.api.common.grpc.RetriableStargateBridge, io.stargate.bridge.proto.StargateBridge, io.quarkus.grpc.MutinyService, java.lang.Object], qualifiers=[@Retriable, @Any], target=io.stargate.sgv2.api.common.grpc.RetriableStargateBridge]
  [ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
  [ERROR] 	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:161)
  [ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:559)
  [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
  [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
  [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
  [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
  [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
  [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  [ERROR] Caused by: java.lang.IllegalStateException: A gRPC service bean must be annotated with @io.quarkus.grpc.GrpcService: CLASS bean [types=[io.stargate.sgv2.api.common.grpc.RetriableStargateBridge, io.stargate.bridge.proto.StargateBridge, io.quarkus.grpc.MutinyService, java.lang.Object], qualifiers=[@Retriable, @Any], target=io.stargate.sgv2.api.common.grpc.RetriableStargateBridge]
  [ERROR] 	at io.quarkus.grpc.deployment.GrpcServerProcessor.validateBindableService(GrpcServerProcessor.java:477)
  [ERROR] 	at io.quarkus.grpc.deployment.GrpcServerProcessor.validateBindableServices(GrpcServerProcessor.java:465)
  [ERROR] 	... 11 more
  [ERROR] -> [Help 1]
  [ERROR] 
  ```
* This error made me add that `@GrpcService` annotation, which in fact was starting the grpc server than
* However, it's questionable why was I getting this error?
   * My thinking it's due to the fact that a service interface extends the `MutinyService`? And since I am using protos for the client side, this is maybe an issue?
   * Second, why is the fix with the `@Produce` method working now and I am not getting the build error (see PR)?

All in all this should be maybe explored more.

**Comment by cescoffier** [comment]
Please open separate issues for the follow-up tasks/questions

Closing - see the last comment.
