### ISSUE TITLE
Docs - default value of `quarkus.native.builder-image` is not shown

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#30474]
### Describe the bug

Docs - default value of `quarkus.native.builder-image` is not evaluated

`${platform.quarkus.native.builder-image}` is shown instead of `mandrel`.

One needs to git grep sources for that info or know to check `build-parent/pom.xml` in https://github.com/quarkusio/quarkus/ repo

https://quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus.native.builder-image:
<img width="1255" alt="Screenshot 2023-01-19 at 11 33 20" src="https://user-images.githubusercontent.com/925259/213420831-8c8bb613-9387-426b-880a-d932d2c4efb5.png">

CC @gsmet / @max

### Expected behavior

mandrel

### Actual behavior

`${platform.quarkus.native.builder-image}`

### Quarkus version or git rev

2.15

**Comment by gsmet** [comment]
Well, we can hardcode it in the documentation with a `defaultValueDocumentation` now it's Mandrel for everything. But I'm not sure it's worth making something complex.

Feel free to create a PR.

**Comment by rsvoboda** [comment]
1) I'm looking a bit into various `defaultValue = "${` cases and it's quite complex. So +1 not to make something complex and possibly fragile.
There are references to:
   - pom.xml based property like in this platform.quarkus.native.builder-image
   - another Quarkus configuration property - e.g. `quarkus.application.name`
   - environment variable - e.g. `GRAALVM_HOME`
   - JVM system property - e.g. `java.home`

2) `defaultValueDocumentation` ... will probably do that

3) > now it's Mandrel for everything

not in our docs though :/

https://quarkus.io/guides/building-native-image can be an example, or just git grep here vvv
```
 ~/git/quarkus/docs  main  git grep ubi-quarkus-graalvmce-builder-image | wc -l
      15
 ~/git/quarkus/docs  main  git grep ubi-quarkus-mandrel-builder-image | wc -l
       6
```
