### ISSUE TITLE
Upgrade to Narayana 6.0.0.CR1 in the Jakarta branch

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#30475]
My guess is that we will have to tweak the rewrite rules to go back to the standard artifacts which should be Jakarta-enabled now.

**Comment by Sanne** [comment]
Actually, that previous commit failed non-core integration tests; this should work:
 - https://github.com/hibernate/hibernate-orm/commit/66143d4059ca5265e207e79f79830a2f5eca1098

**Comment by mmusgrov** [comment]
> @mmusgrov any other transitive dependencies we should be mindful of?

@Sanne The JTA spec API only specifies two dependencies: `jakarta.enterprise.cdi-api` and `jakarta.interceptor-api`  (https://github.com/jakartaee/transactions/blob/master/api/pom.xml#L315). Narayana itself pulls in lots of jakarta dependencies (`cd ArjunaJTA; mvn dependency:tree | grep jakarta`).

**Comment by Sanne** [comment]
thanks @mmusgrov , but yes I was asking about the Narayana dependencies: we can ignore the build time and test dependencies, but for each of the runtime dependencies we will need them aligned to the BOM in Quarkus - especially in case other components might depend on the same.

Sometimes there is more flexibility, other times you might need a very specific version, so it would be great if the owning team could provide some guidance beyond the content of the pom files. 

Incidentally, the pom files seem incomplete as well as I had to manually pull in the CDI and Jakarta Interceptor APIs; if these are required I would expect them to be declared as transitive dependencies of Narayana.

**Comment by mmusgrov** [comment]
@Sanne I made a local fix and built `6.0.0.Final-SNAPSHOT`. But when I include this version in `hibernate-orm` like this
```
alias( "jbossJta" ).to( "org.jboss.narayana.jta", "narayana-jta" ).version( "6.0.0.Final-SNAPSHOT" )
```

the build fails with `Could not find org.jboss.narayana.jta:narayana-jta:6.0.0.Final-SNAPSHOT`.

How do I tell grade to look in my local repo when resolving 6.0.0.Final-SNAPSHOT?

**Comment by mmusgrov** [comment]
Found it (I needed to include mavenLocal() in the dependencyResolutionManagement section of settings.gradle). I'll update 6.0.0.Final-SNAPSHOT with the missing transitive dependencies so the fix will appear when we release 6.0.0.Final.

Regarding your other comment about aligning Narayana dependencies with versions as specified in the Quarkus BOM. Are you referring to versions of Jakarta dependencies that Narayana and Quarkus share or more than just those.

**Comment by Sanne** [comment]
> Found it (I needed to include mavenLocal() in the dependencyResolutionManagement section of settings.gradle). I'll update 6.0.0.Final-SNAPSHOT with the missing transitive dependencies so the fix will appear when we release 6.0.0.Final.

Right, exactly that. Thanks!

> Regarding your other comment about aligning Narayana dependencies with versions as specified in the Quarkus BOM. Are you referring to versions of Jakarta dependencies that Narayana and Quarkus share or more than just those.

I'm referring to any dependency that Naryana will require: including Jakarta APIs but not only. If there's anything in the Quarkus BOM that you know needs to be strictly aligned with Narayana needs.

In general we can rely on integration tests, but since integration testing doesn't have as high coverage as Narayana's own testsuite, it might be best for you to occasionally have a look - especially if you know of strict expectations, such as cases in which you had to upgrade a dependency to a particular version to fix/avoid some issues.

Sometimes the opposite is true as well; for example I just upgraded Hibernate ORM's dependencies to match some newer versions of dependencies that Quarkus was using.
For example:
 - https://hibernate.atlassian.net/issues/?jql=project%20%3D%20%22HHH%22%20AND%20fixVersion%20%3D%20%226.2.0%22%20and%20summary%20~%20Upgrade

Then when all dependencies are aligned we have the reassurance of both integration testsuites.

**Comment by mmusgrov** [comment]
Thanks @Sanne we have started working on a narayana bom (narayana pr/2079) which will help us with aligning dependencies.

Regarding transitive dependency issue; we already include `jakarta.enterprise.cdi-api` in the narayana-jta pom [1].

I also created a small JTA transaction example [2] whose pom only pulls in `org.jboss.narayana.jta:narayana-jta:6.0.0.CR1` (and `org.jboss.logging:jboss-logging:3.5.0.Final`) - it runs without issue. How can I test your transitive dependency issue other than running/debugging your hibernate-orm tests?

[1] https://github.com/jbosstm/narayana/blob/main/ArjunaJTA/narayana-jta/pom.xml#L135
[2]
```
        TransactionExample txeg = new TransactionExample();
        
        txeg.commitUserTransaction();
        txeg.commitTransactionManager();
        txeg.rollbackUserTransaction();
        txeg.setRollbackOnly();
        txeg.transactionStatus();
        txeg.transactionTimeout();
```

**Comment by Sanne** [comment]
thanks @mmusgrov , the failures of Hibernate ORM's integration tests are triggered when we run it on the modules path; but let's not digress too much about that here as this is the Quarkus PR - I was just letting you know, as Narayana end users might benefit from those dependencies being included, but it's not essential to Quarkus.

Thanks for the link to the pom file - I'll use that to check alignment with Quarkus and send subsequent PRs as (and if) needed.

**Comment by Sanne** [comment]
@mmusgrov I found a single dependency misaligned - not sure how important it is:

Narayana has a dependency to `io.smallrye.reactive:smallrye-reactive-converter-api` and seems to be using version `1.0.10`; in Quarkus we're using version `2.7.0` - that seems like a significant difference, I'd recommend to upgrade Narayana to make sure it's not a problem?
