### ISSUE TITLE
[area/documentation] Fix SuppressNonRuntimeConfigChangedWarningBuildItem documentation 

### ISSUE THREAD

**Issue by Nutrymaco** [quarkusio/quarkus#30484]
As far as i undestood, `ConfigGenerationBuildStep.checkForBuildTimeConfigChange` is called at static section in `ApplicationImpl`.So in documentation for SuppressNonRuntimeConfigChangedWarningBuildItem at sentence "An example usage of this is when a user provides some test value in application.properties for a build-time only property and only provides the actual value on the command line when **building** Quarkus" should be "**running/initializing** Quarkus".

**Comment by radcortez** [comment]
Correct. The check is only performed during runtime init. Can you send us a PR to fix it? Thanks :)

**Comment by Nutrymaco** [comment]
PR #30496
