### ISSUE TITLE
I can't connect Quarkus application to Keycloak with custom certificate

### ISSUE THREAD

**Issue by kambei** [quarkusio/quarkus#30504]
### Describe the bug

As [this issue](https://github.com/quarkusio/quarkus/issues/12442) My keycloak does not have a trusted certificate, so i put the property `quarkus.oidc.tls.verification=none`

Even so, it is unable to perform the request!!!

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I tried to add the custom CA Root certifate `ca.crt` when I build the image with:
```
      gradle build -Dquarkus.container-image.build=true \
      -Dquarkus.container-image.group=$CI_REGISTRY_IMAGE -x test \
      -Dquarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=/certs/ca.crt,-J-Djavax.net.ssl.trustStorePassword=changeit
```

but with no luck!

### Expected behavior

Start the application

### Actual behavior

Application doesn't start

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

**Comment by sberyozkin** [comment]
@kambei Is the stack trace coming from the keycloak authorization or oidc extension ?

**Comment by kambei** [comment]
@sberyozkin I solved with `quarkus.oidc-client.tls.verification=none`

**Comment by sberyozkin** [comment]
@kambei I see, so it was the oidc client issue, ok, thanks
