### ISSUE TITLE
Fix config editor when using HTTPS

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#30503]
### Describe the bug

Quarkus 2.13.7.Final (Fixed on main)

Related to: https://github.com/quarkusio/quarkus/pull/29586

The above issue wasn't backported to Quarkus 2.13.7.Final or at least the issue is still happening. 

### How to Reproduce?

```
git clone --branch 2.13 git@github.com:quarkus-qe/quarkus-test-suite.git
cd  quarkus-test-suite/http/http-advanced-reactive
```

Works

```
mvn clean verify -Dit.test=DevModeHttpsIT#uiChange -Dquarkus.platform.version=999-SNAPSHOT
```

Fails

```
mvn clean verify -Dit.test=DevModeHttpsIT#uiChange -Dquarkus.platform.version=2.13.7.Final
```

Note: be sure that the scenario is enabled

### Output of `uname -a` or `ver`

Linux ovpn-193-134.brq.redhat.com 6.0.16-300.fc37.x86_64

### Output of `java -version`

openjdk 17.0.5 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

**Comment by gsmet** [comment]
@pjgg was it tested for 2.13.6.Final? Because AFAICS it was backported in 2.13.6.Final (and I just checked, the commit is there).

**Comment by pjgg** [comment]
Yes, the issue that is behind is still happening, so maybe something else needs to be backported.

**Comment by rsvoboda** [comment]
I have checked the original PR, Pablo is checking 2.13 branch.

**Comment by rsvoboda** [comment]
I think there is issue on test side,  Quakus 2.13.7 + reproducer app from https://github.com/quarkusio/quarkus/issues/29431#issuecomment-1331951858 work fine, I have double checked the application.properties and new value is persisted there.
