### ISSUE TITLE
Add support for the new Vert.x SQL Client in Quarkus

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3051]
We need to support the new SQL client coming with Vert.x 3.8 to support more type of database (Postgres and MySQL).

This includes:

* updating the Vert.x version to 3.8
* integrating this new API (and the 2 clients: Postgres and MySQL)

**Comment by vietj** [comment]
note we will have SQL server support in fall for the same API.

**Comment by cescoffier** [comment]
Closing as this has been done.
