### ISSUE TITLE
Dev UI — edited property is saved with currently active profile

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#30511]
### Describe the bug

I have an app, which contains several properties without a profile. When I run the application, edit property via Dev UI and save it, the property is saved in `application.properties` with currently activated profile (and old property is not changed).

### Expected behavior

Saved property should keep it's original profile (or lack of it)

### Actual behavior

Property is saved with active profile

### How to Reproduce?

1.  ` git clone https://github.com/rsvoboda/code-with-quarkus `
2. 
```
$ cat src/main/resources/application.properties 
quarkus.http.ssl.certificate.key-store-file=META-INF/resources/server.keystore
quarkus.http.ssl.certificate.key-store-password=password
quarkus.datasource.password=foo
```
4. `mvn quarkus:dev -Dquarkus.profile=any`
5.  Access http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/config, edit `quarkus.datasource.password` value to `bar`, and save it
6.  
```
$ cat src/main/resources/application.properties 
quarkus.http.ssl.certificate.key-store-file=META-INF/resources/server.keystore
quarkus.http.ssl.certificate.key-store-password=password
quarkus.datasource.password=foo
%any.quarkus.datasource.password=bar
```
   

### Output of `uname -a` or `ver`

8.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.4, vendor: GraalVM Community

### Quarkus version or git rev

2.14.2.Final

### Additional information

This bug also reproduces on 2.15.3.Final

**Comment by fedinskiy** [comment]
Probably this belongs to https://github.com/quarkusio/quarkus/labels/area%2Fdev-ui , same as the original https://github.com/quarkusio/quarkus/issues/29431

**Comment by fedinskiy** [comment]
Result on the latest build(653954d73c3c44a952526f25c5d32e4cae020e9a) is slightly different:
```
quarkus.http.ssl.certificate.key-store-file=META-INF/resources/server.keystore
quarkus.http.ssl.certificate.key-store-password=password
quarkus.datasource.password=foo
quarkus.datasource.password=foobar # new value
```

**Comment by fedinskiy** [comment]
@iocanel @phillip-kruger you seem to be handling most of https://github.com/quarkusio/quarkus/labels/area%2Fdev-ui issues, any chance one of you can take a look at this?

**Comment by phillip-kruger** [comment]
This is in v2? What is the behaviour in v3?

**Comment by fedinskiy** [comment]
@phillip-kruger hmm, looks like it is working as expected in http://localhost:8080/q/dev-ui/configuration-form-editor of 3.7.2
