### ISSUE TITLE
Reactive Messaging (RabbitMQ) - RejectedExecutionException stopping container

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#30524]
### Describe the bug

When stopping containers in a kubernate environment, I can see a RejectedExecutionException.
This only happens if I use the Reactive Messaging RabbitMQ extension.

### Expected behavior

No exception should be thrown.
Everything should gracefully stop.

### Actual behavior

> Ccode-with-quarkus-5b6b4c49df-7t849[pod-event]Stopping container code-with-quarkus
Ccode-with-quarkus-5b6b4c49df-7t849[pod-event]Readiness probe failed: Get "http://10.8.14.128:8080/q/health/ready": dial tcp 10.8.14.128:8080: connect: connection refused
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus13:06:51 INFO traceId=, parentId=, spanId=, sampled= [io.ve.ra.im.RabbitMQClientImpl] (Shutdown thread) Stopping rabbitmq client
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus13:06:51 INFO traceId=, parentId=, spanId=, sampled= [io.ve.ra.im.RabbitMQClientImpl] (Shutdown thread) Stopping rabbitmq client
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus13:06:51 INFO traceId=, parentId=, spanId=, sampled= [io.ve.ra.im.RabbitMQClientImpl] (pool-9-thread-4) Stopping rabbitmq client
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus13:06:51 ERROR traceId=, parentId=, spanId=, sampled= [co.ra.cl.im.ForgivingExceptionHandler] (pool-9-thread-4) Consumer io.vertx.rabbitmq.impl.QueueConsumerHandler@561a5e24 (amq.ctag-eaIT363NWaUyVllOJODZDckDz7yQ00-D) method handleShutdownSignal for channel AMQChannel(amqp://bbthatdm@13.50.3.232:5672/bbthatdm,1) threw an exception for channel AMQChannel(amqp://bbthatdm@13.50.3.232:5672/bbthatdm,1) [Error Occurred After Shutdown]: java.util.concurrent.RejectedExecutionException
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2076)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:793)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.core.impl.ContextBase.executeBlocking(ContextBase.java:148)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.core.impl.ContextBase.executeBlocking(ContextBase.java:115)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.core.Vertx.executeBlocking(Vertx.java:606)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.core.Vertx.executeBlocking(Vertx.java:613)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.stop(RabbitMQClientImpl.java:786)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.stop(RabbitMQClientImpl.java:777)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.execRestart(RabbitMQClientImpl.java:258)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.restartConnect(RabbitMQClientImpl.java:244)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.restartConsumer(RabbitMQClientImpl.java:207)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$null$11(RabbitMQClientImpl.java:306)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at io.vertx.rabbitmq.impl.QueueConsumerHandler.handleShutdownSignal(QueueConsumerHandler.java:58)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at com.rabbitmq.client.impl.ConsumerDispatcher.notifyConsumerOfShutdown(ConsumerDispatcher.java:197)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at com.rabbitmq.client.impl.ConsumerDispatcher.notifyConsumersOfShutdown(ConsumerDispatcher.java:189)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at com.rabbitmq.client.impl.ConsumerDispatcher.access$200(ConsumerDispatcher.java:36)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at com.rabbitmq.client.impl.ConsumerDispatcher$6.run(ConsumerDispatcher.java:176)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus Suppressed: java.util.concurrent.RejectedExecutionException: Executor is being shut down
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2078)
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus ... 23 more
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus
Ccode-with-quarkus-5b6b4c49df-7t849code-with-quarkus13:06:51 INFO traceId=, parentId=, spanId=, sampled= [io.quarkus] (Shutdown thread) code-with-quarkus stopped in 0.250s

### Quarkus version or git rev

3.0.0.Alpha3

### Additional information

This happens in Kubernates environment, with both native and non native compilation.

**Comment by ozangunalp** [comment]
This is to be fixed upstream in RabbitMQ connector.

**Comment by amoscatelli** [comment]
upgraded to CR1 and it's solved now
