### ISSUE TITLE
Log a warning when a deprecated extension config item is used

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#30538]
### Description

It seems that we don't show the deprecated config items in the docs (which is good, although it might be better to list them with a big exclamation mark instead?); but we do not log anything if a deprecated config item is used and so a user is never warned until the config item is actually removed.

**Comment by mkouba** [comment]
CC @radcortez 

I can try to help with this one but I'm a bit lost in quarkus config. A hint/advice would be much appreciated ;-).

**Comment by radcortez** [comment]
Sure :)

Documentation is generated in the annotation processor:
https://github.com/quarkusio/quarkus/blob/01499ace4f29c2573564369e6c9c3f05c040dc1f/core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDoItemFinder.java#L180-L183

The processing of `@ConfigRoot` is here:
https://github.com/quarkusio/quarkus/blob/17a8174c51ff28ca205a347d8cde1c41d8bc473f/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L99

I guess the easiest way is to collect the deprecated property names and match them to the property names coming from `Config`. We need to split these between build / runtime. Also, the metadata from SR Config `@ConfigMapping` does not contain the information if a property is deprecated, so I need to add that on the SR Config side.

Feel free to look into it. If not, I can pick this up.

**Comment by mkouba** [comment]
Thanks. This [prototype branch](https://github.com/mkouba/quarkus/tree/issue-30538) solves the build time part but I don't have a solution for the runtime part yet.
