### ISSUE TITLE
missing release version 2.16.0.Final

### ISSUE THREAD

**Issue by najibk** [quarkusio/quarkus#30534]
### Describe the bug

Hello,

I am interested in this release version 2.16.0.Final, I can see the tag and maven artifacts for some of the libraries but not all of them.

Example :
Found :  https://mvnrepository.com/artifact/io.quarkus/quarkus-resteasy/2.16.0.Final
Missing : https://mvnrepository.com/artifact/io.quarkus/quarkus-universe-bom

is this expected ?

thanks

### Expected behavior

release for all quarkus dependencies for the same version are available 

### Actual behavior

some of quarkus dependencies for the same version are missing

**Comment by gsmet** [comment]
Yes, it is expected.

Quarkus releases are done in two phases:
- the core release
- the full platform release one week after

2.16.0.Final has not been fully released yet and has not been announced yet. It will be on Wednesday.
