### ISSUE TITLE
Allow configuring the port for the http probe

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#30547]
### Description

Currently, there is no configuration option for setting the port of the `httpAction` for probes. The port number is infered from the build system, by looking up for a port named `http`.

There are cases where we need to use another port (e.g. the management port). We should provide the option in `PortConfig` to use a differnet port name or value.

**Comment by cescoffier** [comment]
The config could be either an int or a string (port binding name).

**Comment by iocanel** [comment]
> We should probide the option in `PortConfig` to use a differnet port name or value

**probide** ?

This is a typo, no pun intended!
