### ISSUE TITLE
Quarkus jacoco coverage not working in a multi module project where code and tests are in separate modules

### ISSUE THREAD

**Issue by JakubKubena** [quarkusio/quarkus#30555]
### Describe the bug

I have a quarkus microservice with 2 modules, `module-api` and `module-impl.` I have unit tests for both modules combined in `module-impl`. When I run `mvn verify`, then a jacoco report is generated, which only shows coverage for the code in `module-impl`, even though I have code from `modue-api` also covered by tests. I wanted the report to include correct coverage of all modules.

### Expected behavior

Quarkus jacoco should generate coverage of code in all project modules, even those which do not contain unit tests.

### Actual behavior

Quarkus jacoco only reports coverage for modules which contain unit tests. The code from other modules is reported as uncovered.

### How to Reproduce?

Example repo: https://github.com/JakubKubena/jacoco-coverage-demo

Branch: `quarkus-tests-in-impl-module`

run `mvn verify`

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

### Quarkus version or git rev

2.15.3.Final

**Comment by aleboulanger** [comment]
is there any workaround to have a working solution please ?

**Comment by pipinet** [comment]
same issues.

**Comment by beto20** [comment]
Hello, is there any solution to this?
I have the same problem

**Comment by gsmet** [comment]
@famod are you using Jacoco in your multi module project?

**Comment by famod** [comment]
The problem goes away if you add a `beans.xml` to that api module (of the reproducer). I suppose otherwise classes in the module are not present in the index that is used by the jacoco extensions.
I suppose generating a `jandex.idx` would work as well.
See also: https://quarkus.io/guides/cdi-reference#bean_discovery

I think at very least, the jacoco guide should mention that relevant classes all need to be indexed.

/cc @geoand

**Comment by geoand** [comment]
@famod that is very good point!

Would you like to add a note to the docs?

**Comment by famod** [comment]
I have very little time ATM but I'll see what I can do. I'll let you know when I have to pass.

**Comment by geoand** [comment]
I can take if you like, just don't want to take the "credit" since you "fixed" the issue :)

**Comment by famod** [comment]
No worries, feel free to take it! :-)
