### ISSUE TITLE
Log exception caught by GrpcDuplicatedContextGrpcInterceptor.ListenedOnDuplicatedContext#invoke

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#30561]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/28063 added handling of uncaught exceptions from gRPC downstream interceptors, so now gRPC call is properly closed. This is good.

But now the exception is no longer logged. I had to spend quite a lot of time debugging to get to the real reason why gRPC call was closed by the server.

Could you please log the exception, that triggered closing of gRPC call in GrpcDuplicatedContextGrpcInterceptor.ListenedOnDuplicatedContext#invoke?

### Expected behavior

Exception logged and gRPC call closed

### Actual behavior

gRPC call is closed silently, leaving no trace in the log

### Quarkus version or git rev

Quarkus 2.13.6

**Comment by alesj** [comment]
Msg like this?

```
                log.warn("Closing gRPC call ...", t);
```

Or something with more info?

**Comment by vladykin** [comment]
That would be sufficient, thanks!

**Comment by cescoffier** [comment]
Fixed by #30579
