### ISSUE TITLE
should set `app.kubernetes.io/managed-by=quarkus` when we generate deploy schemas

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#30572]
### Description

in https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ is documented that `app.kubernetes.io/managed-by` should be set to the app that setup the deployment, i.e. `helm`

we should set it to `quarkus` to separate it from hand edited deployments.

**Comment by geoand** [comment]
Does Dekorate have any support for this @iocanel, @Sgitario ? Or should we just add this to the Quarkus extension?

**Comment by iocanel** [comment]
I recall wanting to add it to dekorate. Don't recall if we did. Regardless, we should add it something like this for quarkus.

**Comment by geoand** [comment]
I'll add it

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/30573 should take care of it
