### ISSUE TITLE
Quarkus 3.0 codestarts for Gradle have `javax` in `allopen` rather than `jakarta`

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#30582]
### Describe the bug

Not sure if intentional, but generating a Quarkus 3.0 Gradle KTS codestart gives me:

```properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.0.0.Alpha3
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.0.0.Alpha3
```

```kt
allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}
```

**Comment by gastaldi** [comment]
Looks like we need to apply the changes in the following commit too in 3.0:  

https://github.com/quarkusio/quarkus/commit/9a74058898a405118b3630903ce28c684f38470a#diff-1fdf13c3faf1e270925515b7c829a57d03c1e4742330f889b30b369976928005R303-R304

**Comment by glefloch** [comment]
right, I will update kotlin codestart code.

**Comment by GavinRay97** [comment]
Ah, sorry for an invalid issue!

**Comment by gastaldi** [comment]
Actually it doesn't seem to be fixed - https://github.com/quarkusio/quarkus/blob/3.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle/kotlin/build.tpl.qute.gradle

I think @glefloch 's PR may fix it

**Comment by gsmet** [comment]
I will have a look as if you’re using Alpha3, it should be already fine.

**Comment by gsmet** [comment]
There's something fishy.

AFAICS, the Gradle Kotlin script is OK:
https://github.com/quarkusio/quarkus/blob/3.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle-kotlin-dsl/kotlin/build.tpl.qute.gradle.kts

But the Gradle one is not:
https://github.com/quarkusio/quarkus/blob/3.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle/kotlin/build.tpl.qute.gradle

I have no idea yet what's going on. I'm digging.

**Comment by gastaldi** [comment]
@gsmet isn't https://github.com/quarkusio/quarkus/pull/30587 supposed to fix this?

**Comment by gsmet** [comment]
I'm not sure yet. I think it fixes the issue with the gradle file AFAICS (but I'm unsure as I have no real idea about what was the initial issue...) but the kts file was already correct so I need to test it more.

**Comment by gsmet** [comment]
@gastaldi https://github.com/quarkusio/quarkus/pull/30587 broke the Jakarta build so that doesn't help to get the issue fixed :). I will push a fix soon.

**Comment by gsmet** [comment]
BTW, I'm still unsure as to why the Gradle Kotlin Script build file also has the issue while this particular file has been transformed.
