### ISSUE TITLE
Add support for Syslog logging handler

### ISSUE THREAD

**Issue by Sparow199** [quarkusio/quarkus#3059]
**Description**
Expose syslog-handler via application.properties

**Implementation ideas**
I'm working in this feature in my [fork](https://github.com/Sparow199/quarkus/commit/57a010643aefbd6d7b36866fcc3a02cd5df977dc) (Work in progress)

I'll make a PR ASAP.
Thanks

**Comment by Sparow199** [comment]
Hi @dmlloyd , i'm working on Syslog handler integration but i need some help to determine which properties to expose in application.properties. 

I looked at [this file](https://github.com/dmlloyd/jboss-logmanager/blob/master/src/main/java/org/jboss/logmanager/handlers/SyslogHandler.java) and this [documentation](https://docs.jboss.org/author/display/AS72/Logging+Configuration) to lookup for the properties.

Thanks

**Comment by dmlloyd** [comment]
I'd do the following:

* `appName`, make it optional and use `org.wildfly.common.os.Process#getProcessName` if it is not given
* `level`, similarly to the other handlers
* `facility`, default to `USER_LEVEL`
* `hostname`, make it optional and use `org.wildfly.common.net.HostName#getQualifiedHostName` if it is not given
* `syslogType`, default to `RFC5424`
* `protocol`, default to `TCP`
* `autoFlush`, similarly to the other handlers
* NOT `useMessageDelimiter` and `messageDelimiter`: these should not be configurable, at least at first (this should be based on `Protocol` as defined by the `SyslogHandler` constructor)
* `encoding`, similarly to the other handlers
* `formatter`, similarly to the file handler
* `blockOnReconnect`, default to `true` (users should generally use the async handler if this is a problem though)
* NOT `maxLength`: let this be based on `syslogType`
* `truncate`: default to `true`
* `useCountingFraming`: default to `false` (make sure it's spelled correctly)

The rest - error manager, filter, and async - look correct.

**Comment by Sparow199** [comment]
Great. @dmlloyd what do you think if we refactor `public void initializeLogging(LogConfig config) ` like this: 
```java
    public void initializeLogging(LogConfig config) {
        final Map<String, CategoryConfig> categories = config.categories;
        final LogContext logContext = LogContext.getLogContext();
        final Logger rootLogger = logContext.getLogger("");
        ErrorManager errorManager = new OnlyOnceErrorManager();
        rootLogger.setLevel(config.level.orElse(Level.INFO));
        for (Map.Entry<String, CategoryConfig> entry : categories.entrySet()) {
            final String name = entry.getKey();
            final Logger logger = logContext.getLogger(name);
            final CategoryConfig categoryConfig = entry.getValue();
            if (!"inherit".equals(categoryConfig.level)) {
                logger.setLevelName(categoryConfig.level);
            }
        }
        final Map<String, CleanupFilterConfig> filters = config.filters;
        List<LogCleanupFilterElement> filterElements = new ArrayList<>(filters.size());
        for (Entry<String, CleanupFilterConfig> entry : filters.entrySet()) {
            filterElements.add(new LogCleanupFilterElement(entry.getKey(), entry.getValue().ifStartsWith));
        }
        ArrayList<Handler> handlers = new ArrayList<>(3);
        if (config.console.enable) {
            errorManager = initConsoleHandler(config, errorManager, filterElements, handlers);
        }

        if (config.file.enable) {
            initFileHandler(config, errorManager, filterElements, handlers);
        }

        if (config.syslog.enable) {
            initSyslogHandler(config, errorManager, filterElements, handlers);
        }

        InitialConfigurator.DELAYED_HANDLER.setHandlers(handlers.toArray(EmbeddedConfigurator.NO_HANDLERS));
    }

```

**Comment by dmlloyd** [comment]
Sure, I think that would be OK.
