### ISSUE TITLE
Support @InjectSpy on javax.inject.Singleton classes

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#30608]
### Description

Currently, if I try to `@InjectSpy` a `javax.inject.Singleton` class, like `javax.transaction.TransactionManager`, I get the error:
```
Invalid use of io.quarkus.test.junit.mockito.InjectSpy - the injected bean does not declare a CDI normal scope but: javax.inject.Singleton
```

By checking this issue: https://github.com/quarkusio/quarkus/issues/8983, it seems that `@InjectMock` has a param `convertScopes` that addresses this issue. Could this also work on `InjectSpy`?

I wanted to do something like this in my tests:
```
// (...)
verify(transactionManagerSpy).setRollbackOnly();
//
```

**Comment by davidfrickert** [comment]
I solved my problem by creating a wrapper bean `@ApplicationScoped` that injects the `TransactionManager`. Then I can `@InjectSpy` it and verify that the method is being called. 
But it should still be nice to have a proper way of validating that the transaction was committed or rolled back.

**Comment by geoand** [comment]
Good idea!

https://github.com/quarkusio/quarkus/pull/30623 will take care of it

**Comment by davidfrickert** [comment]
thanks for the quick fix @geoand !

**Comment by geoand** [comment]
YW

**Comment by adrianbob** [comment]
Was this ever released? I do not see convertScopes to be available for @InjectSpy. Is there another way to achieve the test scope convertion?
