### ISSUE TITLE
Migration to Quarkus 3 fails on records and sealed classes

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#30639]
### Describe the bug

jbang --verbose upgrade-to-quarkus3@quarkusio

```

[INFO] --- rewrite-maven-plugin:4.36.0:run (default-cli) @ quarkus-timed-producers ---
[INFO] Using active recipe(s) [io.quarkus.openrewrite.Quarkus3]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Project [quarkus-timed-producers] Resolving Poms...
[INFO] Project [quarkus-timed-producers] Parsing Source Files
[WARNING] Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = ~/tmp/quarkus-timed-producers/src/main/java/org/acme/GreetingResource.java)
JCClassDecl(name = GreetingResource, line = 10)
JCClassDecl(name = HelloService, line = 22)
--- END PATH ---

[WARNING] Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = ~/tmp/quarkus-timed-producers/src/main/java/org/acme/GreetingResource.java)
JCClassDecl(name = GreetingResource, line = 10)
--- END PATH ---

[WARNING] Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = ~/tmp/quarkus-timed-producers/src/main/java/org/acme/GreetingResource.java)
--- END PATH ---

[WARNING] Unexpected modifier sealed
[INFO] Running recipe(s)...
[WARNING] Changes have been made to pom.xml by:
[WARNING]     io.quarkus.openrewrite.Quarkus3
[WARNING]         org.openrewrite.maven.ChangePropertyValue: {key=quarkus.platform.version, newValue=3.0.0.Alpha3}
[WARNING] Please review and commit the results.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
`
```

### Expected behavior

must be able to migrate classes with record and sealed interfaces

### Actual behavior

error while migrating, the code was not migrated and doesn't compile anymore
[project.tar.gz](https://github.com/quarkusio/quarkus/files/10511744/project.tar.gz)

### How to Reproduce?

Run migration script in attached project, see the output, try to re-run

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### Quarkus version or git rev

2.15.3.Final

**Comment by maxandersen** [comment]
can confirm I can reproduce the issue.

This is openrewrite parsing failing somehow. I've opened https://github.com/openrewrite/rewrite/issues/2738 to see if we can get some info.

**Comment by maxandersen** [comment]
so looks like rewrite just made a recent release that fixes the sealed classes issues BUT even though using `org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run` result in no errors the javax references are not updated.

So something more is going on here.

**Comment by ia3andy** [comment]
I've assigned this to you Max, let me know if you need me for something.

**Comment by maxandersen** [comment]
I don't plan on looking further in this for now - hoping @ia3andy  or others would have an idea on what is going on with this one.

**Comment by ia3andy** [comment]
I've just ran:
```shell
mvn org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run \
  -Drewrite.configLocation=/Users/.../Downloads/quarkus-timed-producers/quarkus3.yml \
  -DactiveRecipes=io.quarkus.openrewrite.Quarkus3 -e
```
and it seems to work fine now:

```java
package org.acme;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @Inject
    HelloService helloService;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return " " + helloService.hello();
    }

    @ApplicationScoped
    public static class HelloService {
        public static String HELLO = "hello ";
        record Msg(String msg) {}
        sealed interface Foo permits Bar,Baz{}
        static final class Bar implements Foo {}
        static final class Baz implements Foo {}
        public String hello() {
            return new Msg(HELLO).toString() + new Bar();
        }
    }
}
```

We should update and make the open-rewrite version configurable in the jbang script.

PS: this makes me think we should do the same in the future CLI update (have a fixed version that we gather from the quarkus-update repository but also configurable with an option in the command)

**Comment by maxandersen** [comment]
hmm - so you see changes to jakarta?

is it then `jbang --fresh upgrade-to-quarkus3@quarkusio` that is broken/missing things?

**Comment by ennishol** [comment]
resolved
