### ISSUE TITLE
PreDestroy hooks fail depending on method modifiers

### ISSUE THREAD

**Issue by Saladoc** [quarkusio/quarkus#30636]
### Describe the bug

Given classes `SuperClass` and `ImplClass` in different packages with `ImplClass extends SuperClass`, a `@PreDestroy` annotated method on the `SuperClass` can not be called by quarkus.

Error message reads: 
`Error occurred while destroying instance of bean [ImplClass_Bean]: java.lang.IllegalAccessError: ImplClass_Bean tried to access method 'void SuperClass.preDestroyHook()' (ImplClass_Bean and SuperClass are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader`

### Expected behavior

The `preDestroyHook()` gets called successfully regardless of modifiers.

### Actual behavior

The `preDestroyHook()` only gets called successfully if it is `public`.

For default and `protected` visibility, the behavior as described above occurs.

For `private`, the method gets called successfully, but arc warns about private visibility not being recommended.

### How to Reproduce?

[Minimal reproducer app](https://github.com/Saladoc/quarkus-problem-demo)

### Quarkus version or git rev

tested for each of 3.0.0.Alpha3, 2.16.0.Final, 2.13.7.Final

### Additional information

[Zulip conversation](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40PreDestroy.20method.20not.20recognized.20.2F.20accessible)

**Comment by mkouba** [comment]
We need to apply the same strategy as we use for `@PostConstruct` callbacks, i.e. use a reflection fallback for non-public methods inherited from a class in a different package.
