### ISSUE TITLE
allow additional text in clientheader

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#30631]
### Description

clientheaderparam cannot include additional text outside the ${}.

this fails:

```
@POST
    @ClientHeaderParam(name = "Authorization", value = "Bearer ${openai.token}")
    Set<String> getCompletions(Completion payload);
```

where as this works but now I have to include "Bearer " in the property:

```
@POST
    @ClientHeaderParam(name = "Authorization", value = "${openai.token}")
    Set<String> getCompletions(Completion payload);
```

if possible to do without  overhead this seems like a nice touch/simplification.

**Comment by geoand** [comment]
Makes sense, I'll add it
