### ISSUE TITLE
Quarkus CLI: quarkus build gets stuck with application generated with quarkus app create if there's spaces in output directory

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#30642]
### Describe the bug

With Quarkus CLI built from current main (commit `baa1c2f30ca4fbbe2841bb35ad9f075a983a6a8f` as of writing), create app creats unbuildable application if there's spaces in output directory,

### Expected behavior

Same as with 2.16.0.Final: 

```
[mjurc@tigris code-with-quarkus]$ quarkus version
2.16.0.Final
[mjurc@tigris Playground]$ quarkus create app --output-directory='s p a c e s/app'
-----------

applying codestarts...
📚  java
🔨  maven
📦  quarkus
📝  config-properties
🔧  dockerfiles
🔧  maven-wrapper
🚀  resteasy-reactive-codestart

-----------
[SUCCESS] ✅  quarkus project has been successfully generated in:
--> /home/mjurc/Playground/s p a c e s/app/code-with-quarkus
-----------
Navigate into this directory and get started: quarkus dev
[mjurc@tigris Playground]$ cd '/home/mjurc/Playground/s p a c e s/app/code-with-quarkus'
[mjurc@tigris code-with-quarkus]$ quarkus build
--2023-01-26 21:57:14--  https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.1/maven-wrapper-3.1.1.jar
.
.
.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.593 s
[INFO] Finished at: 2023-01-26T21:57:23+01:00
[INFO] ------------------------------------------------------------------------
```

### Actual behavior

`quarkus build` gets stuck without any output

### How to Reproduce?

Reproducer:

Steps to reproduce:
1. build Quarkus from main
2. create launcher for Quarkus CLI:

```
cat <<EOF > ./quarkus-dev-cli
#!/bin/bash
java -jar ~/.m2/repository/io/quarkus/quarkus-cli/999-SNAPSHOT/quarkus-cli-999-SNAPSHOT-runner.jar "\$@"
EOF
chmod +x ./quarkus-dev-cli
```

3. run the CLI commands:

```
./quarkus-dev-cli create app --output-directory='s p a c e s/app'
cd 's p a c e s/app/code-with-quarkus'
../../../quarkus-dev-cli build
```

### Output of `uname -a` or `ver`

Linux tigris 6.1.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 18 17:11:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

baa1c2f30ca4fbbe2841bb35ad9f075a983a6a8f

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

N/A

### Additional information

If the application is generated with `2.16.0.Final` Quarkus CLI in directory with spaces, `quarkus build` works even with Quarkus CLI built from main.

**Comment by rsvoboda** [comment]
Compared generated app by 2.16 based CLI vs. Quarkus main based CLI and the diff is in mvnw and .mvn files

<img width="1158" alt="Screenshot 2023-01-31 at 15 52 34" src="https://user-images.githubusercontent.com/925259/215794110-92fc84be-764b-4719-8d87-5ca5cfe3208c.png">

This fail is probably related to https://github.com/quarkusio/quarkus/pull/30108 changes

@gsmet  @jorsol

**Comment by rsvoboda** [comment]
So the problem is in `BASE_DIR=$(find_maven_basedir "$(dirname $0)")` from `mvnw`

The change was introduced in https://github.com/apache/maven-wrapper/commit/e87947e893bbf8aba1827cf1fae10b422655c9b7 by @jorsol 

I will update `mvnw.tpl.qute` to use old approach with `pwd`
```
-BASE_DIR=$(find_maven_basedir "$(dirname $0)")
+BASE_DIR=$(find_maven_basedir "$(pwd)")
```
