### ISSUE TITLE
OIDC adapter should use smallrye-jwt extension

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#3064]
**Description**
smallrye-jwt should be able to let the Keycloak adapter validate the tokens as well take care of all the subtleties associated with the OIDC flows and 'extend' it by letting the users access the tokens via MP JWT Api

**Implementation ideas**
Bill: "smalrye-jwt could just look for a marker BuildItem and not wire in the defaut implementation if that exists.  Keycloak would just publish that marker BuildItem"
plus: possibly provide a handler for converting the token into a `Principal`; KC adapter would check for it before providing its own `Principal`

**Comment by sberyozkin** [comment]
Checking one of the KC @BuildStep capabilities should be enough

**Comment by sberyozkin** [comment]
@stuartwdouglas FYI

**Comment by sberyozkin** [comment]
Hi @cescoffier, @stuartwdouglas 
Here is one possible way which it might work. 
1. Introduce `PrincipalProvider` spi:
```
interface PrincipalProvider {
    Principal toPrincipal(Credential cred);
}
```
2. `quarkus-smallrye-jwt` ships `JsonWebTokenProvider`:

```
class JsonWebTokenProvider implements PrincipalProvider {
    public Principal toPrincipal(Credential cred) {
          if (cred instanceof TokenCredential) {
              return convertToJsonWebToken(cred);
          } else {
              return null;
          }
    }
}
```
3. Have the 'master' token validators, example, a keycloak adapter, checking for `PrincipalProvider` before using its own Principal implementation

It looks like it can work...thanks

**Comment by stuartwdouglas** [comment]
You can already do this via io.quarkus.security.identity.SecurityIdentityAugmentor

**Comment by sberyozkin** [comment]
@stuartwdouglas this is very nice :-) I guess `smallrye-jwt` should first be updated to work with the vertx-web, but I can definitely experiment with this enhancement independently

**Comment by sberyozkin** [comment]
Hi Stuart, @stuartwdouglas, 
I've started looking at it. As agreed, [this code](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-keycloak/runtime/src/main/java/io/quarkus/vertx/keycloak/VertxOAuth2IdentityProvider.java#L56) should not be there (with [this one](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-keycloak/runtime/src/main/java/io/quarkus/vertx/keycloak/VertxJwtPrincipalProducer.java) to be offered by 'smallrye-jwt', along with other producers and customizations, and [this one](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-keycloak/runtime/src/main/java/io/quarkus/vertx/keycloak/VertxJwtCallerPrincipal.java) - by `quarkus-smallrye-jwt` :-) ). 
The question is, what to put [here](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-keycloak/runtime/src/main/java/io/quarkus/vertx/keycloak/VertxOAuth2IdentityProvider.java#L56) for the soon to be added `quarkus-smallrye-jwt`'s `SecurityIdentityAugmentor` be recognized ?
Thanks

**Comment by stuartwdouglas** [comment]
The augmenter is just a CDI bean, so you just install it with an unremovable AdditionalBeanBuildItem.

You do need to be a bit careful as if there is other forms of authentication present then not every identity may have a JWT token, so you will need to verify that the credential is the correct type, or add some kind of attribute to the identity to indicate that it was created from a JWT credential.

Maybe it even makes sense to subclass TokenCredential with JwtTokenCredential and put that in the credentials list instead of the original TokenCredential.

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, I've been thinking more, and I'm not sure the augmentation model in the current form works for this task. If the `vertx-keycloak` module is validating the token and then parsing again to prepare a JWT principal then there is nothing that quarkus-smallrye-jwt can augment.  

My understanding was there would be some intermediate model that would be passed around.

For example, at [this point](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-keycloak/runtime/src/main/java/io/quarkus/vertx/keycloak/VertxOAuth2IdentityProvider.java#L53) AccessToken is available. So one approach is to get all the claims from it and make them available as a `Map` to `quarkus-smallrye-jwt`, I've looked at `AccessToken` and it can returns an extension of the Map which is a good news - so the question is, how would the augmentation approach help to make this Map visible to `quarkus-smallrye-jwt` ?

But there is also one more thing, I'd really like the `smallrye-jwt` code which deals with the various mappings (like supporting the 3rd party tokens without `groups` with the roles or scope info being in some other claims, etc) be of use for the `vertx-keycloak` too. So I'm not sure if an indirection with `quarkus-smallrye-jwt` is needed or your original idea of depending directly on `smallrye-jwt` is the best one.

I wish it were actually Vertx Web which was using `smallrye-jwt` to parse and verify the token :-)

**Comment by stuartwdouglas** [comment]
You just make the AccessToken available in the SecurityIdentity under a property name. The augmenter can then retrieve it and do whatever it wants, including any role mapping.

**Comment by sberyozkin** [comment]
@stuartwdouglas that is well thought out, cool. In this case then we'd need to have `vertx-keycloak` depending on `quarkus-smallrye-jwt` to guarantee a principal would be provided as I'd have to remove a double parsing code. I'd still need to refactor smallrye-jwt to deal with a Map when manipulating the mappings, etc but the good news you've already set the good expectations with this module, which is about the tokens be available via MP-JWT :-), so even if my changes won't make it to 1.0, it would still work as expected for the users...

I will experiment

**Comment by sberyozkin** [comment]
Copying from the related issue:

Right now we have to double parse the token in the adapter code to create JsonWebToken because VertxOAuth2 has already got it parsed and it has no way to map that to JsonWebToken.

Implementation ideas
It is impossible to avoid the double parsing unless VertxOAuth2, at the moment of seeing the parsed token, could map it to JsonWebToken (possibly with the help of smallrye-jwt) or create a complete Map view of the token for the adapter itself to convert it to JsonWebToken

Likely a medium term issue

**Comment by sberyozkin** [comment]
I'll close this issue for now as realistically we'd need to bypass Vertx oAuth2 for it to work, I can revisit once we have an OAuth2 client support code in place
