### ISSUE TITLE
Conditionally (required) properties

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#30668]
### Description

I have properties which are conditionally required, where as the conditions are values of certain other properties. Currently, I simply set the conditionally required properties to `""` and check them during build time if the dependent property has a certain value:
```
@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED, name = "myfeature")
public class WebFilterConfig {
    /**
     *  Enables the web filter for HTTP requests over resteasy. Default: true
     */
    @ConfigItem(name = "enabled", defaultValue = "true")
    boolean webfilterEnabled;
    /**
     *  Base path on which the filter will be applied. Example "/api".
     */
    @ConfigItem(name = "webfilter.path", defaultValue = "")
    @ConvertWith(MyEmtpyConverter.class)
    String path;
}
```
```
 if (webFilterConfig.webfilterEnabled() && getPath().isBlank()) {
            throw new ConfigurationException(
                    "ContextWebfilter property 'myfeature.webfilter.path' is missing or blank.");
        }
```

This feels and is quite a workaround wich bloats the code and is spread accross the application.

### Implementation ideas

Instead, it would be much nicer and understandable if I directly could define a conditionally property. I imagine this be done with a new annotation e.g. `@OnlyIf` like this:
```
@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED, name = "myfeature")
public class ContextWebFilterConfig {
    /**
     *  Enables the web filter for HTTP requests over resteasy. Default: true
     */
    @ConfigItem(name = "enabled", defaultValue = "true")
    boolean webfilterEnabled;
    /**
     *  Base path on which the filter will be applied. Example "/api".
     */
    @OnlyIf(name="enabled", value ="true")
    @ConfigItem(name = "webfilter.path")
    String path;
}
```
If `webfilterEnabled` is `true` and `path` is not set, the regular Quarkus exception  for a missing property will be thrown .
If `webfilterEnabled` is `false`and `path` is not set nothing is happening and the application will start.

This way, I have all my configuration code in one class and understand whats going on.

**Comment by AKARSHITJOSHI** [comment]
Hi @HerrDerb I would like to give this a try .

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Unlikely we would support it in this way. The `@ConfigRoot` with classes design is a frozen feature. The recommended way is to use `@ConfigMapping`: https://quarkus.io/guides/writing-extensions#configuration

A `@ConfigMapping` does support Bean Validation. Right now, it does work for Runtime. For Build time, it is currently disabled because we need to figure out how to plug in the Validator. We have a chicken-egg problem.

**Comment by geoand** [comment]
@radcortez should we close this as `won't fix`?

**Comment by HerrDerb** [comment]
I just bump into this in a slightly different situation again. I think it actually would not be necessary to do this on per property value base-
I think the problem actually would be solved, if one could add `@IfBuildProperty` onto a interface annotated with `@ConfigMapping` and/or `@ConfigGroup`.  I think this already gets discussed somewhere, right?

**Comment by radcortez** [comment]
Hum... Yes, I think this was discussed before, but I can't remember the outcome :D

While possible to implement, I think one of the cons was that `@IfBuildProfile` is only intended for CDI Beans, but a ConfigMapping is not a CDI bean.

**Comment by radcortez** [comment]
It is now possible to use Bean Validation annotation at build time with https://github.com/quarkusio/quarkus/pull/32586.

**Comment by HerrDerb** [comment]
Cool thanks, that looks very promising 🙂👍
