### ISSUE TITLE
How to add local jar file with gradle?

### ISSUE THREAD

**Issue by DemiusAcademius** [quarkusio/quarkus#3066]
standard way:
dependencies {
   compile files("path/to/jar")
}
not work
if starting with quakusDev, we see java.lang.NoClassDeffoundError: oracle/jdbc/driver/OracleDriver

**Comment by emmanuelbernard** [comment]
Hi.

Can you offer a reproducable.
CC @aloubyansky

**Comment by DemiusAcademius** [comment]
Hi!.

I solved the problem for the development mode.
I add oracle library to local maven repository via maven { url: 'libs' }
and it all worked

пт, 5 июл. 2019 г. в 11:03, Emmanuel Bernard <notifications@github.com>:

**Comment by gsmet** [comment]
Thanks!

**Comment by chyiro** [comment]
Hi.

I have the same question so I created a simple reproducible.
It will be a great help if anyone could have check on this.
https://github.com/chyiro/quarkus-with-gradle

I tried 3 kinds of methods for including local jar files. Please refer to build.gradle in the reproducible for more details.
1. `implementation files('lib/sample.jar')` in dependencies
2.  `compile files('lib/sample.jar')` in dependencies
3.  `id 'java-library' in plugins with `api files('lib/sample.jar')` in dependencies

All methods succeeds in compilation but produces `java.lang.NoClassDefFoundError: foo/bar/Sample` in runtime.

**Comment by aloubyansky** [comment]
We just don't see these files. We rely on `ResolvedConfiguration.getResolvedArtifacts()` [1] which does not include files. `ResolvedConfiguration.getFiles()` does.

[1] https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/AppModelGradleResolver.java#L241

**Comment by chyiro** [comment]
That explains the behavior.
So is there any plans to support flat directory repository in the future?
https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver

The developer experience is kind of weird to register JARs with Maven in advance while using Gradle as main build tool.
Supporting flat directory repository should be a small but good improvement.

Thanks!

**Comment by aloubyansky** [comment]
I can't give an estimation when now but I think we should support it.

**Comment by iwasa-kosui** [comment]
Hello @aloubyansky !

To use AWS ElastiCache for Memcached with Java, we should use local `.jar` file that is provided by AWS. Thus, supporting this is very important for AWS ElastiCache user.

![image](https://user-images.githubusercontent.com/24590869/91279033-fac1dc00-e7bf-11ea-98f1-09a0ccb39d46.png)

Thank you.

**Comment by aloubyansky** [comment]
https://github.com/aloubyansky/quarkus/commit/289ce6e6fba509ffbf3fdcad824a39ea02bf4270 appears to work.
Our classpath/dependency model is based on artifacts that come from a repo. We completely overlooked direct FS paths.
I'll test the change above on windows and if it goes well, I'll add your reproducer to our testsuite and open a PR.
