### ISSUE TITLE
Reuse Rest Client with custom Qualifiers

### ISSUE THREAD

**Issue by Serkan80** [quarkusio/quarkus#30677]
### Description

It's currently not possible to define 1 Rest Client interface and reuse it as multiple clients  in a declarative way by defining custom qualifiers. 

### Implementation ideas

I'd like to have something like shown below to be possible:

```java
public interface MyClient  {

    @GET
    @Path("/foo")
    Response foo();
    
}
```

```java
@Qualifier
@Retention(RUNTIME)
@Target({METHOD, FIELD, PARAMETER, TYPE})
@RegisterRestClient(configKey = "client-a")
public @interface ClientA {
}

@Qualifier
@Retention(RUNTIME)
@Target({METHOD, FIELD, PARAMETER, TYPE})
@RegisterRestClient(configKey = "client-b")
public @interface ClientB {
}
```

```properties
quarkus.rest-client.client-a.url=https://url1.com
quarkus.rest-client.client-b.url=https://url2.com
```

And I'd like to use this client with the qualifiers:

```java
@ClientA
@RestClient
MyClient clientA;

@ClientB
@RestClient
MyClient clientB;
```

But this doesn't work. It gives `UnsatisfiedResolutionException`.

Although you can make it work by doing a programmatic lookup with `RestClientBuilder`, but it would be nice to make it also work with the declartive way.

**Comment by geoand** [comment]
IMHO, this would be handled best at the MP REST Client spec level - the idea being that the `@RestClient` qualifier would have a name that corresponds to the name used to configure the client in properties.

cc @radcortez

**Comment by radcortez** [comment]
You can probably do it independently, with some extra code using a CDI Producer and the builder approach.

I agree with @geoand. Please propose this in https://github.com/eclipse/microprofile-rest-client

**Comment by geoand** [comment]
> You can probably do it independently, with some extra code using a CDI Producer and the builder approach.

Definitely
