### ISSUE TITLE
RESTEasy Reactive: SSE broadcaster fails if a sink has been closed

### ISSUE THREAD

**Issue by Foobartender** [quarkusio/quarkus#30681]
### Describe the bug

SseBroadcasterImpl#broadcast() throws an exception if one of its sinks has already been closed (which is to be expected).

### Expected behavior

SseBroadcasterImpl#broadcast() should handle sink errors gracefully.

### Quarkus version or git rev

2.16.0.Final

### Additional information

See non-reactive [SseBroadcasterImpl](https://github.com/resteasy/resteasy/blob/ab69a05700e6df987d6bf8de00d58fc57263c4fb/resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java#L136) for comparison. It doesn't propagate any exceptions, notifies error listeners instead.

Also, implicit close events (i.e. connection closed by client) don't seem to be fired.

**Comment by Foobartender** [comment]
Error listener notification was already happening [here](https://github.com/quarkusio/quarkus/blob/c943decfb636a345f2e2681d15d709e967542da8/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/SseEventSinkImpl.java#L39) - sorry, I missed that. Now happens twice, the one in SseEventSinkImpl should be removed.

**Comment by geoand** [comment]
Feel free to open a Pull Request
