### ISSUE TITLE
[gRPC] Allow to exclude/include proto files from dependencies

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#30685]
### Description

When generating code from dependency containing a large amount of proto files, I would like to filter out which proto files to uses to reduce compile time and size of the produced binary.
Enumerating each of them will not be practical and being able to provide comma separated glob patterns should be easier.

```
quarkus.generate-code.grpc.scan-for-proto=io.envoyproxy.controlplane:api
quarkus.generate-code.grpc.scan-for-proto-include=/envoy/service/ext_proc/**,/udpa/**
quarkus.generate-code.grpc.scan-for-proto-exclude=/udpa/annotations/**
```

By default,

```
quarkus.generate-code.grpc.scan-for-proto-include=all
quarkus.generate-code.grpc.scan-for-proto-exclude=none
````

**Comment by scrocquesel** [comment]
`quarkus.generate-code.grpc.scan-for-proto` can accept multiple dependency so inclusions and exclusions may not apply to all of them. I scoped the pattern by package but didn't succeed with a property key containing `:`. Some help on the PR to be able to do :

```
quarkus.generate-code.grpc.scan-for-proto=io.envoyproxy.controlplane:api
quarkus.generate-code.grpc.scan-for-proto-include.io.envoyproxy.controlplane:api=/envoy/service/ext_proc/**,/udpa/**
quarkus.generate-code.grpc.scan-for-proto-exclude.io.envoyproxy.controlplane:api=/udpa/annotations/**

# or
quarkus.generate-code.grpc.scan-for-proto-include."io.envoyproxy.controlplane:api"=/envoy/service/ext_proc/**,/udpa/**
quarkus.generate-code.grpc.scan-for-proto-exclude."io.envoyproxy.controlplane:api"=/udpa/annotations/**

#instead of
quarkus.generate-code.grpc.scan-for-proto-include.io.envoyproxy.controlplane_api=/envoy/service/ext_proc/**,/udpa/**
quarkus.generate-code.grpc.scan-for-proto-exclude.io.envoyproxy.controlplane_api=/udpa/annotations/**
```

**Comment by alesj** [comment]
I guess I would go with that `# or` ... similar to most of the thing we do per package ... e.g. logging, etc

**Comment by scrocquesel** [comment]
> I guess I would go with that `# or` ... similar to most of the thing we do per package ... e.g. logging, etc

It seems quoted string do not avoid colon from being parsed as a key / value separator.

**Comment by cescoffier** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/30687
