### ISSUE TITLE
Json stream item is not processed immediately after receiving in ChunkedStreamingMultiSubscriber.class

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#30690]
### Describe the bug

When using rest endpoint with `application/stream+json` content type, after receiving json object is not processed immediately. 
Client is expecting stream element separator to process element. Separator is sent as prefix with subsequent elements. This means that stream element is processed after receiving next one.

### Expected behavior

Stream element should be processed immediately after receiving.

Maybe ChunkedStreamingMultiSubscriber should add separator as postfix, not as prefix with next item.

### Actual behavior

Strem element is processed after receiving next one (or stream closed).

### How to Reproduce?

Reproducer: https://github.com/paloliska/json-stream

steps:
1. Run test in reproducer project.

### Output of `uname -a` or `ver`

Linux user 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

2.16.0.Final, 3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
@Sgitario mind taking a look at this?

**Comment by Sgitario** [comment]
Fix: https://github.com/quarkusio/quarkus/pull/30737
