### ISSUE TITLE
Quarkus 2.16 and Mockito 5.1.0 --> java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by KaiSuchomel** [quarkusio/quarkus#30707]
### Describe the bug

When try to use the newest Mockito Version (5.1.0) wiht Quarkus (2.16.0) a java.lang.NoClassDefFoundError occurs:

`java.lang.NoClassDefFoundError: org/mockito/internal/util/JavaEightUtil
	at io.quarkus.test.junit.mockito.internal.MutinyAnswer.returnValueForClass(MutinyAnswer.java:123)
	at io.quarkus.test.junit.mockito.internal.MutinyAnswer.answer(MutinyAnswer.java:54)
	at javax.enterprise.inject.Instance.stream(Instance.java:182)`

The Extension "quarkus-junit5-mockito" uses a Class that is not longer available in Mockito V5.

![image](https://user-images.githubusercontent.com/79638648/215490725-3d9c85b3-b8f1-4f53-89a1-b8a5cb5f194c.png)
****

### Expected behavior

Mockito V5 should work.

### Actual behavior

java.lang.NoClassDefFoundError during TestExecution

### Output of `uname -a` or `ver`

Linux kai-Latitude-5420 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.4.1" 2022-08-18 LTS Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2) Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

### Quarkus version or git rev

2.16.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/apache/maven/apache-maven-3.8.6 Java version: 17.0.4.1, vendor: Oracle Corporation, runtime: /opt/java/jdk/jdk-17.0.4.1 Default locale: de_DE, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-58-generic", arch: "amd64", family: "unix"

**Comment by gsmet** [comment]
Thanks for the heads up. We haven't updated to Mockito 5 yet.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/30710 . I don't think we will backport the upgrade though as it is a major version upgrade.
