### ISSUE TITLE
Consider using `OpenId Connect` instead of `OIDC` in the guide and link names

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#30705]
### Description

IMHO having `OIDC` instead of `OpenId Connect` is making it less descriptive/searchable.

We do use `OIDC` everywhere in the OIDC docs content but introduce it as `OpenId Connect (OIDC)`. 
I believe the guides/link names should continue using `OpenId Connect` - `OIDC` is not what some/(many ?) users will search for, it is an acronym, quite well known, but `OpenId Connect` is more informative and easier to read/pronounce compared to `OIDC`.

@rolfedh @sheilamjones Please discuss it and if agreed, update the affected content

**Comment by rolfedh** [comment]
Thanks for your comments, @sberyozkin. We'll standardize our approach to specific acronyms in titles. The standard will vary according to the recognition factor of the specific acronym. 

Here's a proposal:

- We'll categorize acronyms as well-known, lesser-known, and obscure.
- **Well-known** acronyms like SSL, TLS, mTLS, will probably appear **abbreviated** in titles; expanded in the first paragraph; and then abbreviated in the rest of the document.
- **Lesser-known** acronyms (like OIDC?) should appear both **expanded and abbreviated** in titles, and then abbreviated in the rest of the document. This makes titles longer and clunker, but might help some users reading the titles or using ctrl+f to find the right topic.
- **Obscure** acronyms should appear expanded in titles, expanded and abbreviated in the first paragraph, and then abbreviated in the rest of the document.

**Comment by sberyozkin** [comment]
Thanks @rolfedh, it sounds reasonable, lets see how it looks for the `Lesser-known` ones, the policy for the `Obscured` ones is the one which seems good  for OIDC, but you have a good point about `OpenId Connect (OIDC)` in the title improving the searchability, so lets give it a try :-)

**Comment by rolfedh** [comment]
Revised proposal for simplicity:
- We'll categorize acronyms as well-known and lesser-known.
- **Well-known** acronyms like SSL, TLS, and mTLS will probably appear **abbreviated** in titles, expanded and abbreviated in the first instance/first paragraph, and then abbreviated in the rest of the document.
- **Lesser-known** acronyms (like OIDC?) should appear both **expanded and abbreviated** in titles, expanded and abbreviated in the first instance/paragraph, and then abbreviated in the rest of the document. This makes titles longer and clunkier, but helps some users who are reading the titles or using ctrl+f find the right topic.


| First Header  | Second Header | Third Header
| ------------- | ------------- |
| Content Cell  | Content Cell  |Content Cell  |
| Content Cell  | Content Cell  |Content Cell  |

**Comment by sberyozkin** [comment]
Thanks @rolfedh
