### ISSUE TITLE
when use @PathParam , generic parameters is error   

### ISSUE THREAD

**Issue by wglnint** [quarkusio/quarkus#30702]
### Describe the bug

i copy quarkus demo，io.quarkus.resteasy.reactive.server.test.resource.basic.resource.GenericResourceCrudResource
but idea tips error, Details below：

![image](https://user-images.githubusercontent.com/123947449/215459249-e0dfb736-bdc1-4fe4-a4ff-7243b3015a43.png)

error info is

java.lang.RuntimeException: Could not create converter for java.lang.Object for method io.smallrye.mutiny.Uni<ENTITY_IDENTIFIER_TYPE> get(ENTITY_IDENTIFIER_TYPE entityIdentifierType) on class io.isdp.permit.crud.cmd.AbstractCurdCmd of type PATH

so，please solve IT。3Q

**Comment by geoand** [comment]
Please provide a sample application that behaves in the way you describe in the issue.

**Comment by wglnint** [comment]
hi：
so sorry，it's my falut， i miss  declare generic type。
please close it；




| |
王岗
|
|
***@***.***
|
---- Replied Message ----
| From | Georgios ***@***.***> |
| Date | 1/31/2023 15:18 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [quarkusio/quarkus] when use @PathParam , generic parameters is error (Issue #30702) |

Please provide a sample application that behaves in the way you describe in the issue.

**Comment by geoand** [comment]
Thanks for the update
