### ISSUE TITLE
OIDC Bearer tutorial doc name is very long

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#30704]
### Description

The name of the OIDC bearer authentication tutorial file is very long:
`security-protect-service-application-using-oidc-bearer-authentication-tutorial`.

Having such long path segments in doc URLs is not great - it does not have to match precisely the doc title.

FYI, the concept is named as `security-oidc-bearer-authentication-concept` and I'd like to propose to have
`security-oidc-bearer-authentication-tutorial`.
 
A bit more precise and quite descriptive can be
`security-oidc-bearer-token-authentication-concept`
`security-oidc-bearer-token-authentication-tutorial`

@rolfedh Can you please rename as proposed or would you like me open a PR ?

**Comment by rolfedh** [comment]
Thanks for your feedback. I'll update this.

**Comment by rolfedh** [comment]
@sberyozkin  would you add me to the repo as a contributor?

**Comment by rolfedh** [comment]
See https://issues.redhat.com/browse/QDOCS-119

**Comment by sberyozkin** [comment]
Thanks @rolfedh
