### ISSUE TITLE
Upgrade to GraalVM 19.1.0

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#3073]
- https://medium.com/graalvm/graalvm-19-1-compiling-faster-a0041066dee4
 - https://www.graalvm.org/docs/release-notes/

**Comment by gsmet** [comment]
I pushed an initial PR here: https://github.com/quarkusio/quarkus/pull/3074 .

I had a failure locally related to JAXB, let's see what CI has to say.

**Comment by cescoffier** [comment]
Also, only the native-image docker image has been produced. We would need to also publish the S2I and "maven" docker images when we have everything working.

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/3074
