### ISSUE TITLE
`cancel-previous-runs` GH action is still using deprecated Node.js 12 (only in forked repos)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#30733]
### Description

![screenshot](https://user-images.githubusercontent.com/22860528/215613294-f868d148-7bbc-4f7c-8e22-f40b4374e8fd.png)
https://github.com/famod/quarkus/actions/runs/4047994738

We only use this action in foked repos: https://github.com/quarkusio/quarkus/blob/2.16.0.Final/.github/workflows/ci-actions-incremental.yml#L123-L125

### Implementation ideas

- update the action (hi @n1hility 😉)
- or find a replacement
- or drop it without a replacement (devs need to cancel the run themselves...meh!)

**Comment by gastaldi** [comment]
+1 to update the action

**Comment by n1hility** [comment]
will update this

**Comment by n1hility** [comment]
@famod actually, I just noticed we are already  using a concurrency group, with cancel in progress, I don't think this is needed anymore. Unless you are aware of a problem with it?

**Comment by gsmet** [comment]
I don't remember the specifics but I think we kept in on purpose for some edge cases. @yrodiere do you remember?

Probably something we could rewrite in Java now that we have Quarkus GitHub Action.

**Comment by yrodiere** [comment]
> I don't remember the specifics but I think we kept in on purpose for some edge cases. @yrodiere do you remember?

No, I didn't even know this existed. This seems related? https://github.com/quarkusio/quarkus/pull/16643

**Comment by gsmet** [comment]
OK so here is the history:
- we moved cancellation to the bot and dropped the cancel actions
- we reintroduced it for forks because forks were not covered
- we switched to using the concurrency feature of GitHub Actions and dropped the bot feature

Forks should be properly covered now so I think we can remove `cancel-previous-runs` safely. I'll go do that.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/30779 .

**Comment by n1hility** [comment]
@gsmet cool thanks, i did update the (now obsololeted) project to a v3 now if something goes wrong
