### ISSUE TITLE
Quarkus native building is failing with default configs

### ISSUE THREAD

**Issue by wmoraes99** [quarkusio/quarkus#30732]
### Describe the bug

I'm getting this error when running my Github actions CI to native build the application today. Please tell me if you need a reproducer.

![image](https://user-images.githubusercontent.com/99416199/215611116-8d2feeb9-372b-43f8-a5d3-58d24a7c5b3b.png)

i saw in [repository  ](https://quay.io/repository/quarkus/ubi-quarkus-native-image?tab=history) this tag was deleted today.

![image](https://user-images.githubusercontent.com/99416199/215612031-8f1fc0e6-832c-43bf-b51a-6a7fb188ecb2.png)

### How to Reproduce?

run ./mvnw package -Pnative -Dquarkus.native.container-build=true

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.13.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by geoand** [comment]
@cescoffier any idea what's going on?

**Comment by cescoffier** [comment]
Hum, yes... we deleted these tags yesterday to inform users to move to the new images (multi-archs, same graalvm/mandrel versions).

I can restore them, but these images are not maintained and so are behind in term of updates and CVE fixes.

**Comment by geoand** [comment]
Then I think we can close the issue as this is expected

**Comment by cescoffier** [comment]
I'm still going to restore the tags and send an email.

**Comment by cescoffier** [comment]
I've recreated the tags for the graalvm CE image.

**Comment by geoand** [comment]
👌
