### ISSUE TITLE
Documentation - Mandrel is not promoted as the default native image builder

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#30745]
### Describe the bug

Documentation - Mandrel is not promoted as the default native image builder, `ubi-quarkus-graalvmce-builder-image` is still heavily used.

https://quarkus.io/guides/building-native-image can be an example, or just git grep docs like here vvv:
```
 ~/git/quarkus/docs  main  git grep ubi-quarkus-graalvmce-builder-image | wc -l
      15
 ~/git/quarkus/docs  main  git grep ubi-quarkus-mandrel-builder-image | wc -l
       6
```

### Expected behavior

`ubi-quarkus-mandrel-builder-image` to be used as the main builder image

### Actual behavior

`ubi-quarkus-graalvmce-builder-image` is still heavily used

### How to Reproduce?

Check the docs (online or in git)

### Quarkus version or git rev

Quarkus main

**Comment by zakkak** [comment]
Related to https://github.com/quarkusio/quarkus/issues/29252
