### ISSUE TITLE
Provide a simple way to install Quarkus CLI in a container image without an additional package manager.

### ISSUE THREAD

**Issue by cgruver** [quarkusio/quarkus#30756]
### Description

Current methods for installing the Quarkus CLI require an additional package manager like SDKMAN!, Jbang, etc...

When building a container for developer use, it would be nice to have a mechanism to install the Quarkus CLI without having to install a package manager.  The package managers like SDKMAN!, or JBang, also install locally to the user running the command which can make it difficult with images which run as arbitrary users.

### Implementation ideas

Ideas:

1. Provide an RPM install
1. Provide a shell script which installs to a specified path, aka `/usr/local/bin`

**Comment by cgruver** [comment]
Here's an example of how I'm doing it in a UBI9 container image for use in an Eclipse Che workspace:

```bash
FROM registry.access.redhat.com/ubi9/ubi-minimal
...
ARG QUARKUS_VERSION=2.16.0.Final
ARG JAVA_PACKAGE=java-17-openjdk-devel
...
ENV JAVA_HOME=/etc/alternatives/jre_17_openjdk
RUN microdnf --disableplugin=subscription-manager install -y openssl compat-openssl11 libbrotli git tar gzip zip unzip which shadow-utils bash zsh wget jq podman buildah skopeo glibc-devel zlib-devel gcc libffi-devel libstdc++-devel gcc-c++ glibc-langpack-en ca-certificates ${JAVA_PACKAGE}; \
    microdnf update -y ; \
    microdnf clean all ; \
    
    ## Lots of other stuff here...

    ## Install Quarkus CLI
    mkdir -p /usr/local/libexec/lib ; \
    mkdir /usr/local/libexec/bin ; \
    curl -fsSL -o /usr/local/libexec/lib/quarkus-cli-${QUARKUS_VERSION}-runner.jar https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/${QUARKUS_VERSION}/quarkus-cli-${QUARKUS_VERSION}-runner.jar ; \
    curl -fsSL -o /usr/local/libexec/bin/quarkus https://raw.githubusercontent.com/quarkusio/quarkus/${QUARKUS_VERSION}/devtools/cli/distribution/java-binary/bin/quarkus ; \
    sed -i "s|__RUNNER_JAR__|quarkus-cli-${QUARKUS_VERSION}-runner.jar|g" /usr/local/libexec/bin/quarkus ; \
    chmod +x /usr/local/libexec/bin/quarkus ; \
    ln -s /usr/local/libexec/bin/quarkus /usr/local/bin/quarkus

...

```

**Comment by ebullient** [comment]
rpm is also an additional package manager. :-P

You should be able to simplify the above, as the quarkus CLI is attached as a zip to the quarkus release on github, e.g. https://github.com/quarkusio/quarkus/releases/download/2.16.1.Final/quarkus-cli-2.16.1.Final.zip

Unpacking that zip contains everything you need to use the CLI, and you can put it in your image wherever you would like to.

**Comment by cgruver** [comment]
You're correct...  RPM is yet another.  :-)   It just happens to already be there if I'm starting from a UBI image.

@ebullient That tip above solves the need for me.  Thanks!
