### ISSUE TITLE
[ORM] Add option for logging bind variables

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#3075]
**Description**
Instead of only seeing the executed DML, I'd also like to see the values for bind parameters (akin to org.hibernate.type=trace in old times).

**Comment by gunnarmorling** [comment]
Ok, realizing now I still can increase the log level to TRACE and see the bind params. It still feels a bit irregular to me, perhaps `quarkus.hibernate-orm.log.sql` should not only allow for `true` and `false` but also for some option showing the bind params, like `extended` or so?

**Comment by Sanne** [comment]
hi @gunnarmorling , I like your proposal. "extended" is nice, and we could add it to the existing booleans, making it a smooth upgrade.

Are you going to send a PR?

**Comment by Postremus** [comment]
@gunnarmorling I kinda want this feature. Are you going to send a PR?
Otherwise I could also try to create one for this.

**Comment by gunnarmorling** [comment]
@Postremus, no immediate plans on my side to tackle this, so it's all yours :) Thanks a lot!
