### ISSUE TITLE
Metrics endpoint returning content-type application/openmetrics-text instead of text/plain

### ISSUE THREAD

**Issue by mubashirrbaig** [quarkusio/quarkus#30769]
### Describe the bug

In the previous release(**2.15.3.Final**) we were running "/q/metrics" used to return **"content-type: text/plain"**, which meant we can view our metrics in the browser. But since we have upgraded to **2.16.0.Final** we noticed that the metrics endpoint is returning with **"content-type: application/openmetrics-text"** which means that when we try to access the metrics endpoint it starts downloading the file rather than viewing the browser, which is not the expected behavior.

### Expected behavior

metrics endpoint should return **Content-Type: text/plain**

### Actual behavior

metrics endpoint is returning **Content-Type: application/openmetrics-text**

### How to Reproduce?

1. Use 2.16.0.Final version of quarkus.
2. Go to metrics endpoint, http://localhost:8080/q/metrics

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.2364]

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19

### Quarkus version or git rev

2.16.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

**Comment by gsmet** [comment]
I backported #30576 for 2.16.1.Final and added a note in the 2.16 migration guide.

I think we can close this one, thanks for reaching out.
