### ISSUE TITLE
CLI - introduce clean command

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#30774]
### Description

Introduce clean command for CLI.

ATM CLI has commands `build`, `dev`, `test`, ... But there is no `clean` command.

As a workaround I run `mvn clean` to get fresh start, e.g. when running dev mode and changing Quarkus version.

I think clean could be invoked for maven and gradle, not sure about JBang.
For JBang based app there is no `quarkus dev` support for it, so maybe similar error message approach could be used.
```
quarkus dev
[ERROR] ❗  Unable to launch project in dev mode: Not there yet. ;)
```

**Comment by maxandersen** [comment]
Clean is done with 'quarkus build --clean' afair?

Deliberately not added as seperate command as we don't allow combinations like mvn/gradle does. 

Ps. jbang -Dquarkus.dev ... should work at least for single files. Should get that wired up to quarkus dev

**Comment by rsvoboda** [comment]
Got it. One needs to check `quarkus build --help` or `quarkus dev --help` to see `--[no-]clean` options.

I'm not sure if we document it in cli tooling guide (or if it's worth doing so).

I was unaware of that option and got annoyed by my flow when I was running `mvn clean` instead of just using Quarkus CLI.

**Comment by rsvoboda** [comment]
I have created https://github.com/quarkusio/quarkus/pull/30790 for a note in CLI guide, assigned to @maxandersen .
