### ISSUE TITLE
QuarkusMock.installMockForInstance() does not inject the mock to the target bean [regression]

### ISSUE THREAD

**Issue by rsynek** [quarkusio/quarkus#30788]
### Describe the bug

The `QuarkusMock.installMockForInstance()` does not seem to work anymore with the Quarkus `main`. With `2.16.0.Final`, the `QuarkusMock` works as expected.

See the reproducer (requires 999-SNAPSHOT of Quarkus):
https://github.com/rsynek/quarkus-mock-reproducer

### Expected behavior

Install the mock into the @Inject field.

### Actual behavior

The @Inject field contains the normal instance, not the mock.

### How to Reproduce?

https://github.com/rsynek/quarkus-mock-reproducer

### Output of `uname -a` or `ver`

Linux 5.15.0-58-generic #64~20.04.1-Ubuntu

### Output of `java -version`

Java version: 17.0.5, vendor: Eclipse Adoptium,

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.3

### Additional information

Maven home: /opt/maven/apache-maven-3.8.3
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /home/rsynek/.sdkman/candidates/java/17.0.5-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-58-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@mkouba @manovotn are they any Arc changes that could have broke this?

The weird thing is that none of our tests have broken

**Comment by manovotn** [comment]
> @mkouba @manovotn are they any Arc changes that could have broke this?
> 
> The weird thing is that none of our tests have broken

None that I am aware of, this should be handled by code inside proxies and I don't think that changed.
Also, the test that we have ([link](https://github.com/quarkusio/quarkus/blob/main/integration-tests/main/src/test/java/io/quarkus/it/main/MockTestCase.java)) seems very similar to what's done in the reproducer.

**Comment by Ladicek** [comment]
I suspect this particular reproducer fails due to the Mockito 5 changes (#30710, #30730, #30761). Just look at what `Mockito.mock(MyBean.class)` returns, no dependency injection involved.

Could you please share your specific problem?

**Comment by Ladicek** [comment]
With the present reproducer, it is actually fairly easily to demonstrate that mocking in fact still works. Here's a diff:

```diff
diff --git a/src/main/java/org/example/MyClass.java b/src/main/java/org/example/MyClass.java
index c0ec974..12f4424 100644
--- a/src/main/java/org/example/MyClass.java
+++ b/src/main/java/org/example/MyClass.java
@@ -1,4 +1,8 @@
 package org.example;
 
 public class MyClass {
+    @Override
+    public String toString() {
+        return "normal";
+    }
 }
diff --git a/src/test/java/org/example/MockTest.java b/src/test/java/org/example/MockTest.java
index 8a2d126..dd9da71 100644
--- a/src/test/java/org/example/MockTest.java
+++ b/src/test/java/org/example/MockTest.java
@@ -20,10 +20,11 @@ public class MockTest {
 
     @Test
     void mockingWorks() {
+        MyClass myClassMock = mock(MyClass.class);
+        when(myClassMock.toString()).thenReturn("mocked");
         MyBean myBeanMock = Mockito.mock(MyBean.class);
-        // OptaPlanner detects the mock is not the class nor subclass of the PlanningSolution.
-        when(myBeanMock.getMyClass()).thenReturn(mock(MyClass.class));
+        when(myBeanMock.getMyClass()).thenReturn(myClassMock);
         QuarkusMock.installMockForInstance(myBeanMock, myBean);
-        assertThat(myBean.getMyClass().getClass().getName()).contains("$MockitoMock");
+        assertThat(myBean.getMyClass().toString()).isEqualTo("mocked");
     }
 }
```

**Comment by rsynek** [comment]
There is a negative test making sure that a proper error message is returned. To trigger the error path, I use Mockito to pass there a proxy class instead of the original class, which is detected.

From what I read here is that with Mockito 5 this behavior has changed.

**Comment by Ladicek** [comment]
Yeah, Mockito 5 seems to create mocks differently. I'm removing the _area/arc_ label.

**Comment by geoand** [comment]
Is there still something we need to do about this one?

**Comment by manovotn** [comment]
I don't think we can do much. It's a behavior change in Mockito but as Ladislav showed, mocking as such still works.

I suspect in the example @rsynek showed, they're only using Mockito to get a proxy. They need to either adjust the test or force Mockito to use the old way of generating mocks (according to release notes it's possible but I am not sure how, didn't look further).
