### ISSUE TITLE
Run microservice with Mocks from test-profile

### ISSUE THREAD

**Issue by windspawn** [quarkusio/quarkus#30810]
### Description

So, when developing a large system we have many different microservices working together. Two of the default quarkus profiles help with testing this. The quarkus:test profile runs out automatic tests using mocks, and quarkus:dev starts up the microservice but needs somewhere to forward external calls to.

Usually we either have a large dev-kluster [1] somewhere that we connect out local running dev microservice to, or we start up all the other microservices [2] locally and connect to those. Now, these have potential problems of their own. For option [1] there is always the possibility that someone else is testing something in the dev-kluster, maybe they are restarting something, maybe they are testing something peculiar or maybe the cluster is down for maintenance for some reason. Option [2] lets us avoid that problem, but sometimes you don't really want to fire up 7 other microservices, only to figure out that those 7 in turn need 12 other services to run and so on, eventually starting up the entire system locally in the worst case.

It would be swell to be able to run the service locally (like the dev profile), but inject the same mocks that we use for the test profile.
The easiest way I can think of would be some kind of flag/setting/property to just leave everything running after the tests have been executed in the test profile. Alternatively it should be possible to tell a profile (e.g. dev) to load up the standard mocks we use for the test profile.

I have seen a similar thing implemented for wiremocks here: https://github.com/quarkusio/quarkus/issues/27039
So this would be the same only using the io.quarkus.test.Mock annotation instead which is loaded automatically in the test profile.

**Comment by geoand** [comment]
Hi,

Thanks for reporting. 
Do you mind adding some code example of what exactly you would like to see?

**Comment by geoand** [comment]
Closing as we never got a follow up
