### ISSUE TITLE
Certain maven group id's result in a IllegalStateException

### ISSUE THREAD

**Issue by JanoschHirsch1819** [quarkusio/quarkus#30819]
### Describe the bug

I want to run a dockerized aws lambda using quarkus and mongo panache.
This works fine as long as the maven group id starts with `org.`.
If the group id starts with `com.` or `de.` I get a `IllegalStateException` when I try to call panache methods.

### Expected behavior

No exceptions.

### Actual behavior

I get this exception when calling panache methods:
```
This method is normally automatically overridden in subclasses: java.lang.IllegalStateException
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses
at io.quarkus.mongodb.panache.common.runtime.MongoOperations.implementationInjectionMissing(MongoOperations.java:773)
at io.quarkus.mongodb.panache.PanacheMongoEntityBase.findById(PanacheMongoEntityBase.java:83)
at de.example.repository.Repository.find(Repository.java:13)
at de.example.repository.Repository_ClientProxy.find(Unknown Source)
at de.example.handler.LambdaHandler.handleRequest(LambdaHandler.java:22)
at de.example.handler.LambdaHandler.handleRequest(LambdaHandler.java:11)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:83)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

### How to Reproduce?

This is a minimal project to reproduce the error: https://github.com/JanoschHirsch1819/panache-error-minimal

You just need to execute the `run.sh` file.

### Output of `uname -a` or `ver`

Darwin S0140669 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.13.2.Final up to 2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

This behaviour only occurs if:
- the quarkus version is 2.13.2.Final or higher (with 2.13.1.Final it works)
- containerized lambda (copying `target/lib` and `target/lambda-module-1.0.0-SNAPSHOT-runner.jar` in the `Dockerfile`). (As a regular packaged lambda uploading the `target/function.zip` it works.)
- repository in a separate maven module. (As a regular maven project without modules it works.)
- the maven group id is something else than `org.` (`com.` and `de.` do not work)

I also found that the lambda `.jar` filename in the `Dockerfile` has some influence as well.
(If the group id is `org.` some filenames will trigger the same error behaviour.)

**Comment by BastianSperrhacke-Otto** [comment]
+1

**Comment by gsmet** [comment]
@loicmathieu it seems related to MongoDB with Panache, could you have a look?

**Comment by loicmathieu** [comment]
MongoDB with Panache needs a Jandex index to be able to generate bytecodes for Panache repository. The Jandex index is automatically generated for your application Maven module, but here the repository is in a separate Maven module so you need to create a Jandex index for this module.
The easiest way is to add the Jandex Maven plugin in the module: https://github.com/JanoschHirsch1819/panache-error-minimal/blob/master/repository-module/pom.xml

You can read this documentation for that: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

**Comment by JanoschHirsch1819** [comment]
@loicmathieu Thank you for your response. I tried exactly what you suggested but I still get the same exception. I also tried to add the plugin in all three `pom.xml`'s but no success.

**Comment by loicmathieu** [comment]
@JanoschHirsch1819 you may also need to add the Panache marker file to make bytecode enhancement works: https://quarkus.io/guides/mongodb-panache#defining-entities-in-external-projects-or-jars

**Comment by JanoschHirsch1819** [comment]
@loicmathieu That unfortunately does not fix it either.

**Comment by gsmet** [comment]
@loicmathieu given @JanoschHirsch1819 was kind enough to provide a reproducer, could you have a look at it directly?

**Comment by JanoschHirsch1819** [comment]
Im about to push a producer that is simpler to startup.

**Comment by loicmathieu** [comment]
>@loicmathieu given @JanoschHirsch1819 was kind enough to provide a reproducer, could you have a look at it directly?

@gsmet yes, it's on my todo list

**Comment by JanoschHirsch1819** [comment]
Thank you for taking a look @loicmathieu . I pushed an easy run.sh script. Just execute it and you will be greeted by the error message.

**Comment by JanoschHirsch1819** [comment]
Are there any updates on this?

**Comment by loicmathieu** [comment]
@JanoschHirsch1819 sorry, I forgot about it.

I still didn't see the Jandex plugin inside your repository module, so it will still miss the jandex index which is mandatory for Panache.
Can you add the plugin inside the repository module as I suggested ?

**Comment by geoand** [comment]
Closing for lack of feedback
