### ISSUE TITLE
Response bodies from reactive rest client don't get properly serialized/deserialized

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#30814]
### Describe the bug

Since https://github.com/quarkusio/quarkus/commit/b60b23def77cbd4b31896259239ea46784abee25 I'm seeing issue where response bodies from reactive rest client don't properly get serialized/deserialized, e.g. test expecting response body alike 

```
--22042239dc1d74f3
content-disposition: form-data; name="pojoData"
content-length: 23
content-type: application/json
content-transfer-encoding: binary

{"foo":"test1","bar":1}
--22042239dc1d74f3--
```

completely misses plaintext object since the aforementioned commit.

### Expected behavior

The response contains json in plaintext form, like in Quarkus 2.16 and before

### Actual behavior

Response body doesn't contain the object

### How to Reproduce?

Automated test in RHBQ QE test suite:

```
git clone git@github.com:quarkus-qe/quarkus-test-suite.git
cd quarkus-test-suite/http/jaxrs-reactive
mvn clean verify -Dit.test=MultipartClientIT
```

### Output of `uname -a` or `ver`

Linux tigris 6.1.8-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan 24 20:32:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### Quarkus version or git rev

b60b23def77cbd4b31896259239ea46784abee25

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (Red Hat 3.8.5-3)

### Additional information

There's another reactive resteasy client test in test suite failing due to serialization/coding issues in the test suite since the same commit:

```
git clone git@github.com:quarkus-qe/quarkus-test-suite.git
cd quarkus-test-suite/security/keycloak-oidc-client-reactive-basic
mvn clean verify -Dit.test=KeycloakOidcClientSecurityIT
```

Here, the request with the following upon invoking the resteasy reactive client endpoint:
```
14:35:15,357 INFO  [app] 14:35:14,327 HTTP Request to /client-request-headers/authorization-repeatedly failed, error id: ea81b5e5-3d41-411d-bee1-cfabe5e7ebc5-1: javax.ws.rs.ProcessingException: Response could not be mapped to type java.util.List<java.lang.String>. Hints: Consider adding one the 'quarkus-rest-client-reactive-jackson' or 'quarkus-rest-client-reactive-jsonb' extensions
```

The extension is present and the response should be simply mappable.

**Comment by geoand** [comment]
Do the failing projects contain `quarkus-rest-client-reactive-jackson` or `quarkus-rest-client-reactive-jsonb`?

**Comment by mjurc** [comment]
Yes.

**Comment by geoand** [comment]
I'll have a look tomorrow or Monday

**Comment by geoand** [comment]
> Yes, they contain
> 
> ```
>         <dependency>
>             <groupId>io.quarkus</groupId>
>             <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
>         </dependency>
> ```

This is the problem. 

They only contain the server serialization / deserialization parts, not the client parts (which I mentioned in my previous comment).
You'll need to add `quarkus-rest-client-reactive-jackson`.

**Comment by mjurc** [comment]
@geoand My bad - adding the client dependency worked, thank you!

If this change is intended, let's close this issue.

**Comment by mjurc** [comment]
@geoand It would be helpful to have the decoupling in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#resteasy-reactive imho

**Comment by geoand** [comment]
Sure, we can do that

**Comment by geoand** [comment]
Done: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#rest-client
