### ISSUE TITLE
Packaging type -Dquarkus.package.create-appcds=true isn't documented

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#30821]
### Describe the bug

I've just heard that there is application class data sharing support in Quarkus via `-Dquarkus.package.create-appcds=true`, but it isn't documented. So without anyone explicitly asking/knowing about it there is no way to discover that feature.

### Expected behavior

Find a guide explaining what `-Dquarkus.package.create-appcds=true` does and why I should be using it.

### Actual behavior

No way to find documentation other than looking through the code

```
$ grep -rn SharedArchiveFile
core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:108:                            "run the application jar from its directory and also add the '-XX:SharedArchiveFile=app-cds.jsa' " +
core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:239:        // We use the relative paths because at runtime 'java -XX:SharedArchiveFile=... -jar ...' expects the AppCDS and jar files
core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:242:        // The end result is that users can simply use 'java -XX:SharedArchiveFile=app-cds.jsa -jar app.jar'
core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/AppCDSBuildStep.java:243:        javaArgs.add("-XX:SharedArchiveFile=" + appCDSPath.getFileName().toString());
extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:621:                if (effectiveJvmArgument.startsWith("-XX:SharedArchiveFile")) {
extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java:627:                effectiveJvmArguments.add("-XX:SharedArchiveFile=" + appCDSResult.get().getAppCDS().getFileName().toString());
integration-tests/maven/src/test/java/io/quarkus/maven/it/JarRunnerIT.java:497:                List.of("-XX:SharedArchiveFile=app-cds.jsa", "-Xshare:on", "-Xlog:class+path=info"))
```

Or find the property once you know it exists:
https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.appcds-use-container

**Comment by geoand** [comment]
Thanks!

I'll take care of this soon

**Comment by geoand** [comment]
I am not really sure where to add the documentation. Should it be in a standalone doc, or part of the existing ones (I really don't know which would be the best fit)?

@gsmet @gastaldi WDYT?

**Comment by gastaldi** [comment]
I think a new guide about packaging in Quarkus would be nice to have

**Comment by geoand** [comment]
Packaging?

**Comment by gastaldi** [comment]
Yeah, talkimg about the `quarkus package.type` modes and CDS as a new section

**Comment by geoand** [comment]
Hm... I am not sure there is a lot of value in describing the package types.

**Comment by gastaldi** [comment]
Sure, one about CDS only would be fine too :)

**Comment by geoand** [comment]
@maxandersen do you have any suggestions on where this should be documented?

**Comment by gsmet** [comment]
Yeah, I would go with either a `Packaging your Quarkus application` guide or a specific AppCDS one.

**Comment by geoand** [comment]
At long last, I conquered my laziness and actually [wrote](https://github.com/quarkusio/quarkus/pull/30916) some docs 😆
