### ISSUE TITLE
Quartz configuration useProperties in application.properties file

### ISSUE THREAD

**Issue by FelixA** [quarkusio/quarkus#30834]
### Describe the bug

It seems that it is not possible to configure the quartz property useProperties in Quarkus

The [Quartz documentation](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJobStoreCMT.html ) provides a property called  "org.quartz.jobStore.useProperties" 

According to the quarkus quartz documentation, this property is not configurable. Actually, the QuartzSchedulerImpl is setting this value hardcoded to true for every dbStore-Type even though the quartz documentation default-value is false.

I wonder if there is any reason to not make this property configurable, since we need the ability to store blob values in the database.

### Expected behavior

Extend the Quarkus Quartz config to be able to override the property "org.quartz.jobStore.useProperties" 

### Actual behavior

According to the QuartzSchedulerImpl class it seems that for non-DB store configuration the property will default to false,
whereas for any dbStore type the property is set to true.

### Additional information

Apparently, when using the graalvm due to https://github.com/oracle/graal/issues/460 the property has to be set to true. Yet we are using the JVM and need the ability to set the property.

**Comment by machi1990** [comment]
> Apparently, when using the graalvm due to https://github.com/oracle/graal/issues/460 the property has to be set to true. Yet we are using the JVM and need the ability to set the property.

The reason why this property is not configurable was that back in the days it didn't work for native image and we wanted to have a consistent working behavior between JVM mode and native image.
Over the recent graalvm release, serialiazation is supported and maybe we could evaluate exposing this property again depending on how far/stable serialization support is in native image.

**Comment by machi1990** [comment]
Worth noting that, once we've the https://github.com/quarkusio/quarkus/pull/24636 PR in, it'll be possible to have this sort of customization

**Comment by machi1990** [comment]
I've opened https://github.com/quarkusio/quarkus/pull/33534 to allow configuring the use of properties or not. The configuration know will be `quarkus.quartz.serialize-job-data` which can be either `true` or `false`.  The default is `false` which will equate to `useProperties=true`.
