### ISSUE TITLE
Netty/Vert.x - Share the worker thread pool

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3083]
Quarkus provides a worker thread pool which should be shared by all parties including Vert.x

**Comment by gsmet** [comment]
@stuartwdouglas @cescoffier has this been fixed as part of the new HTTP layer optimizations?

**Comment by stuartwdouglas** [comment]
Not as such, there is still a vert.x blocking pool and a 'core' executor pool. At the moment AFAIK there is no way to tell vert.x to use our pool

**Comment by geoand** [comment]
https://github.com/eclipse-vertx/vert.x/pull/3749 for Vert.x 3.9 and https://github.com/eclipse-vertx/vert.x/commit/fc823eafffd1eaff77ca17e9cb1f5c18b9d4c5e7 for Vert.x 4.x should cover this

**Comment by cescoffier** [comment]
This has been recently fixed by @kenfinnigan .
