### ISSUE TITLE
Non blocking HTTP/REST client

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3084]
Provides an implementation of the Rest client using a non-blocking transport layer.

**Comment by cescoffier** [comment]
The non-blocking transport should be done in resteasy first.

**Comment by emmanuelbernard** [comment]
Is that the general issue related to the work going on when one refers to "the REST client work"?

**Comment by cescoffier** [comment]
@emmanuelbernard Yes

For the record, work has been started: https://github.com/resteasy/Resteasy/pull/2087.

**Comment by Nunalves** [comment]
If I use a rest client like so:
```java
@Path("/person")
@RegisterRestClient
@ApplicationScoped
@Consumes("application/json")
public interface PersonsService {
    @GET
    CompletionStage<Response> retrieve();
}
```

Isn't it already async and non-blocking?

**Comment by kenfinnigan** [comment]
It's async, but whether it's non-blocking depends on the underlying transport.

And at present that underlying transport is blocking

**Comment by patriot1burke** [comment]
I was under the impression that @vietj already did a non-blocking resteasy implementation for client based on vertx.  That the work to do was get client and server using the same Vertx instance (and thus same event loop)

**Comment by cescoffier** [comment]
@patriot1burke @kenfinnigan What's the status of this one? Is it non-blocking now? If so, @kenfinnigan how did we get the TCK to pass as it was clearly anti-non-blocking.

**Comment by cescoffier** [comment]
@patriot1burke @kenfinnigan What's the status of this one? Is it non-blocking now? If so, @kenfinnigan how did we get the TCK to pass as it was clearly anti-non-blocking.

**Comment by kenfinnigan** [comment]
I don't believe it's been done yet

**Comment by EricTing** [comment]
> I don't believe it's been done yet

I am confused by the official doc: https://quarkus.io/guides/rest-client. 
If one uses `org.eclipse.microprofile.rest.client.inject.RegisterRestClient`, and return types can be `CompletionStage` or `Uni`, but under the hood it is still blocking?

**Comment by cescoffier** [comment]
@EricTing yes, under the hood, at the moment (because we are actively working on that) it uses a blocking http client. What is means is that it does not block the caller thread (when returning a Uni or a CS) but it offloads them work to another thread which is blocked.

**Comment by EricTing** [comment]
> @EricTing yes, under the hood, at the moment (because we are actively working on that) it uses a blocking http client. What is means is that it does not block the caller thread (when returning a Uni or a CS) but it offloads them work to another thread which is blocked.

Thanks for the explanation.
Is it still recommended to use `org.eclipse.microprofile.rest.client.inject.RegisterRestClient`? 
I am assuming in the near future, implementation will be async http client and that is transparent to the end user?

**Comment by cescoffier** [comment]
Yes, you can still use the rest client. The update will be transparent for you. 

The vertx web client is already non blocking and provide a lower level API. 

So basically you decide if you want a declarative approach (rest client) or a more low level experience (vertx web client)

**Comment by geoand** [comment]
@michalszynkiewicz https://github.com/quarkusio/quarkus/pull/15141 should address this, right?

**Comment by michalszynkiewicz** [comment]
@geoand yes
