### ISSUE TITLE
HTTP access log contains duplicate entries when rerouting requests

### ISSUE THREAD

**Issue by brahim-raddahi** [quarkusio/quarkus#30845]
### Describe the bug

When using a RouteFilter to reroute requests, the access log handler seems to be added multiple times, resulting in multiple lines for the same request in the access log.

This:
https://github.com/quarkusio/quarkus/blob/3.0.0.Alpha2/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/filters/accesslog/AccessLogHandler.java#L145

Should only be triggered once per RoutingContext

Sidenote: there does not seem to be an option to refer to the "original request" variables vs the rewritten ones (Apache uses ">" and "<" for this), the logged path for example will be the rewritten/rerouted one

### Expected behavior

The access log should contain only one line per request

### Actual behavior

The access log contains multiple lines per request

### How to Reproduce?

1. start from the "getting-started" project at https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started
2. add the dependency quarkus-vertx-web to the pom.xml file
3. add this class: [GreetingRerouter.txt](https://github.com/quarkusio/quarkus/files/10578423/GreetingRerouter.txt)
4. compile the project
5. run it with access logs enabled: java -Dquarkus.http.access-log.enabled=true -Dquarkus.http.access-log.log-to-file=true -Dquarkus.http.access-log.log-directory=/opt/testapp/log -jar quarkus-run.jar
6. start a request: curl http://localhost:8080/
7. the access log contains two entries per request

**Comment by geoand** [comment]
This happens because you are rerouting requests

**Comment by sschellh** [comment]
Hello,

I observe the same behavior and for me this feels like a bug. Rerouting should not cause two entries in the access log. Otherwise it looks like two requests did hit the server, while in fact it was just one (that was internally reroutet).
