### ISSUE TITLE
Gradle: `@CacheableTask` causes build/test errors / re-think caching approach

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#30852]
### Describe the bug

[This commit](https://github.com/quarkusio/quarkus/commit/74da3d7b6b7ab38d914b2f92832d4ee11d9d4cc1) introduced a serious regression. We pretty much run into CI failures, like [in this CI run](https://github.com/projectnessie/nessie/actions/runs/4082501919) ([Gradle build scan](https://scans.gradle.com/s/eyzzvozwuazss/tests/:nessie-quarkus:intTest/org.projectnessie.server.ITBasicOperations?expanded-stacktrace=WyIwIl0&top-execution=1)).

It might be that the cached artifact of a native-build is messed up with a build for a fast-jar - or something else?

The relevant configuration of the `QuarkusBuild` task [is here](https://github.com/projectnessie/nessie/blob/6de524d/servers/quarkus-server/build.gradle.kts#L132-L154). 
We made [`GradleBuild` caching](https://github.com/projectnessie/nessie/pull/5974) with 2.15.3.Final before, which _seemed_ to work.

While it is generally nice that the `QuarkusBuild` task is cacheable, the size of the cached artifact(s) is really huge, because it contains literally all dependencies. In our case, a cached `QuarkusBuild` execution ("standard" runner jar) occupies about 130M, where 129M are just dependencies in `build/quarkus-app/lib/`, which are available from elsewhere.

The Gradle cache keeps _recent_ and not just the _most recent_ output of a cacheable task, so the above 129M are cached over and over again, letting the Gradle cache "explode" just due to the cacheable output of the `QuarkusBuild` task - in numbers: the build-cache stored by the GitHub actions is currently about 2G big, grown from a few-10M.

IMO the `QuarkusBuild` task should be cacheable, but definitely _not_ include dependencies that are available from elsewhere.

Running the `QuarkusBuild` ("fast jar" or even "uber jar") during  every CI run is not that much of an issue. The real issue is that if other projects/tasks _depend_ on the output of `QuarkusBuild`, those are not able to cache or "pass" their "up to date" checks, because the output of a quarkus build is _not_ reproducible. Means, even if the inputs of the `QuarkusBuild` task are the same, it produces a different output every time.
* the generated jar files have different zip-entry timestamps
* the generated `quarkus-application.dat` is different every time, even if the inputs are exactly the same

(We did not notice this issue earlier due to #30453)

### Actual behavior

Stack trace:
```
java.lang.IllegalStateException: Unable to locate the artifact metadata file created that must be created by Quarkus in order to run integration tests. Make sure this test is run after the 'quarkusBuild' Gradle task.
at io.quarkus.test.junit.IntegrationTestUtil.readQuarkusArtifactProperties(IntegrationTestUtil.java:434)
at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:137)
at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:123)
at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
```

### Quarkus version or git rev

2.16.1.Final

**Comment by geoand** [comment]
> the generated quarkus-application.dat is different every time, even if the inputs are exactly the same

This would probably be fixed by ensuring the data is written in sorted order (although I have no checked)
