### ISSUE TITLE
Shared Vert.x instance producer

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3087]
This issue is about having a single shared Vert.x instance shared among the different components.

This is related to:

* #3036 
* #3083 
* #3082

**Comment by mkouba** [comment]
What does it mean? We do share a `Vertx` instance, or?

**Comment by cescoffier** [comment]
@mkouba Yes, things are changing a little bit with the new transport layer.

**Comment by cescoffier** [comment]
It's been done.
