### ISSUE TITLE
Kotlin-version reference as indicated in the documentation is not present and build fails

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#30912]
### Describe the bug

We ran into an issue lately because our quarkus and kotlin version were not compatible with. In order to address this issue I added the `{kotlin-version}` variable as indicated in the [documentation](https://github.com/quarkusio/quarkus/blob/2.16/docs/src/main/asciidoc/kotlin.adoc#important-gradle-configuration-points): 

```groovy 
plugins {
    id 'java'
    id 'io.quarkus'

    id "org.jetbrains.kotlin.jvm" version "{kotlin-version}" // (1)
    id "org.jetbrains.kotlin.plugin.allopen" version "{kotlin-version}" // (1)
}
```
If I do so, the build fails with the following exception: 
```

 quarkus-bug-kotlin-version-missing git:(main) ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ugitschthaler/Projects/github.com/u6f6o/quarkus-bug-kotlin-version-missing/build.gradle' line: 5

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '{kotlin-version}'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:{kotlin-version}')
  Searched in the following repositories:
    MavenRepo
    Gradle Central Plugin Repository
    MavenLocal(file:/Users/ugitschthaler/.m2/repository/)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Expected behavior

The `{kotlin-version}` should be resolved automatically by referring to the quarkus bom and the build should succeed. 

### Actual behavior

The build fails with an error: 

```

 quarkus-bug-kotlin-version-missing git:(main) ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ugitschthaler/Projects/github.com/u6f6o/quarkus-bug-kotlin-version-missing/build.gradle' line: 5

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '{kotlin-version}'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:{kotlin-version}')
  Searched in the following repositories:
    MavenRepo
    Gradle Central Plugin Repository
    MavenLocal(file:/Users/ugitschthaler/.m2/repository/)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### How to Reproduce?

1. Clone https://github.com/u6f6o/quarkus-bug-kotlin-version-missing
2. Execute `./gradlew build`

### Output of `uname -a` or `ver`

Darwin MB-52-P14.fritz.box 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment Homebrew (build 17.0.4.1+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.4.1+0, mixed mode, sharing)

### Quarkus version or git rev

2.16.1-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.5.1 ------------------------------------------------------------  Build time:   2022-08-05 21:17:56 UTC Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918  Kotlin:       1.6.21 Groovy:       3.0.10 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.4.1 (Homebrew 17.0.4.1+0) OS:           Mac OS X 12.6 aarch64

**Comment by geoand** [comment]
Those variables are variables for the documentation, not variables for user to substiture.
[This](https://quarkus.io/guides/kotlin#important-gradle-configuration-points) is the documentation for Quarkus 2.16 and as you can see from the code, a specific Kotlin version is used.

**Comment by u6f6o** [comment]
Ok, my bad, sorry. Would be nice nevertheless though imo, if the gradle-quarkus-plugin could help us in choosing a compatible kotlin version.

**Comment by u6f6o** [comment]
I believe the confusion arose because of this side https://quarkus.pro/guides/kotlin.html#important-gradle-configuration-points that seems to be no official quarkus documentation source though

**Comment by geoand** [comment]
Indeed it's not

**Comment by u6f6o** [comment]
Just in case somebody stumbles over this topic as well, here is the workaround I created to harmonise the quarkus and kotlin version: 

```groovy
pluginManagement {
    def kotlinVersion = null
    def quarkusBomUrl = "https://repo1.maven.org/maven2/io/quarkus/quarkus-bom/${quarkusVersion}/quarkus-bom-${quarkusVersion}.pom"
    try (
        def quarkusBomIs = new URL(quarkusBomUrl).openStream()
    ) {
        def slurpedBom = new XmlSlurper().parse(quarkusBomIs)
        kotlinVersion = slurpedBom
            .dependencyManagement
            .dependencies
            .dependency
            .find { it.groupId.text() == "org.jetbrains.kotlin" && it.artifactId.text() == "kotlin-compiler"}
            .version
            .text()
    }
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id "io.quarkus" version "${quarkusVersion}"
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.toString().startsWith("org.jetbrains.kotlin")) {
                useVersion(kotlinVersion)
            }
        }
    }
}
```
