### ISSUE TITLE
OpenAPI for contains different parameters for Spring Data in 2.13 and 2.16

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#30921]
### Describe the bug

I have an application which uses Spring Data and OpenAPI. When I look into OpenAPI endpoint, it turns out that REST endpoints have "namedQuery" as a first parameter  in 2.16.1.Final and don't have this parameter in 2.13.7.Final. Otherwise, these endpoints are identical. Is that behavior expected?

### Expected behavior

Endpoints expose same parameters.

### Actual behavior

2.16:
```
"paths" : {
    "/article-jpa" : {
      "get" : {
        "tags" : [ "ArticleJpaRepository" ],
        "parameters" : [ {
          "name" : "namedQuery",
          "in" : "query",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "page",
          "in" : "query",
          "schema" : {
            "format" : "int32",
            "default" : 0,
            "type" : "integer"
          }
        },
```
2.13:
```
  "paths" : {
    "/article-jpa" : {
      "get" : {
        "tags" : [ "ArticleJpaRepository" ],
        "parameters" : [ {
          "name" : "page",
          "in" : "query",
          "schema" : {
            "format" : "int32",
            "default" : 0,
            "type" : "integer"
          }
        },
```

### How to Reproduce?

1. `git clone git@github.com:fedinskiy/quarkus-test-suite.git -b reproducer/openapi-failure`
2. `cd quarkus-test-suite/spring/spring-data`
3. `mvn clean quarkus:dev -Dnative -Dquarkus.platform.version=2.16.1.Final -Pfail`
4. `curl http://localhost:8080/q/openapi > 216api.json`
5. `mvn clean quarkus:dev -Dnative -Dquarkus.platform.version=2.13.7.Final -Pfail` 
6.`curl http://localhost:8080/q/openapi > 213api.json`
7. `diff 216api.json 213api.json`

### Output of `uname -a` or `ver`

6.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

**Comment by geoand** [comment]
cc @Sgi

**Comment by Sgitario** [comment]
Yes, this is expected. It was added in Quarkus 2.15 by https://github.com/quarkusio/quarkus/pull/29323 and It's documented in https://quarkus.io/guides/rest-data-panache#complex-filtering-to-list-entities-using-namedquery.

**Comment by geoand** [comment]
If it's expected, feel free to close and add the `question` label

**Comment by fedinskiy** [comment]
@Sgitario thank you!
