### ISSUE TITLE
Unable to create two connections to the same database with different users

### ISSUE THREAD

**Issue by surbhimahajan93** [quarkusio/quarkus#30920]
### Describe the bug

Unable to create two connections to the same database in MySQL but will different credentials. I used the named data source concept (https://quarkus.io/guides/datasource) but resulted in an error
` WARN  [io.agr.pool] (agroal-11) Datasource 'app': Communications link failure`

application.properties
```
quarkus.datasource."app".db-kind=mysql
quarkus.datasource."app".username=read_only_user
quarkus.datasource."app".password=read_only_user
quarkus.datasource."app".jdbc.url=<sameurl>

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=default
quarkus.datasource.password=default
quarkus.datasource.jdbc.url=<sameurl>
```

Dao layer using the "app" data source

```
@ApplicationScoped
public class Dao {

  @Inject
  @PersistenceUnit("app")
  EntityManager em;
```
Default data source

```
 @ApplicationScoped
    public class Dao2 {
    
      @Inject
      EntityManager em;
```

### Expected behavior

To be able to use both data sources with the same URL but different credentials in the application.

### Actual behavior

Getting error while trying to use the same URL and different credentials in two data sources instances 
`WARN  [io.agr.pool] (agroal-11) Datasource 'app': Communications link failure`

### How to Reproduce?

Described above

### Output of `java -version`

17

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

**Comment by gsmet** [comment]
I don't see how this would fail. Could you provide a reproducer (preferably using a Docker setup so that we don't have to set up the databases ourselves).

**Comment by geoand** [comment]
Closing as we did not get a reproducer
