### ISSUE TITLE
Unable to find a MessageBodyReader after switch to Quarkus 3.0.0.Alpha3 / Mutiny 2.0 that moves from `org.reactivestreams.Publisher` to `java.util.concurrent.Flow.Publisher`

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#30935]
### Describe the bug

I have app that's using SSE and quarkus-resteasy-mutiny with quarkus-rest-client-mutiny.

I'm migrating it to Quarkus 3.0.0.Alpha3. 

My rest-client interface (pongClient) is using `org.reactivestreams.Publisher<String> getPong();` construct, that is later called from rest endpoint using `return Multi.createFrom().publisher(pongClient.getPong()).map(response -> "ping " + response);`

Quarkus 3 and Mutiny moves to java.util.concurrent.Flow and thus java.util.concurrent.Flow.Publisher.
`Multi.createFrom().publisher` expects `Flow.Publisher<T> publisher`

When I adjust the interface to use `java.util.concurrent.Flow.Publisher` I receive error when running the tests / app: `Caused by: jakarta.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/event-stream and type interface java.util.concurrent.Flow$Publisher`

On Quarkus 2.x the code was working OOTB. The same behaviour should be preserved after the switch from `org.reactivestreams.Publisher` to `java.util.concurrent.Flow.Publisher` in Quarkus 3

### Expected behavior

No fail

### Actual behavior

Exception: `Caused by: jakarta.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/event-stream and type interface java.util.concurrent.Flow$Publisher`

### How to Reproduce?

Use https://github.com/rsvoboda/code-with-quarkus/tree/sse-publisher
Run `mvn clean verify`

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.0.Alpha3

**Comment by cescoffier** [comment]
@rsvoboda, just to be sure, it's all about resteasy classic, right? 

If it does, I'm afraid it will require changes in RESTEasy itself which might not be easy or possible to do (it requires Java 9+). So, in that case, I would rather document what's required using an adapter instead of trying to fix the _unfixable_.

**Comment by geoand** [comment]
cc @jamezp

**Comment by rsvoboda** [comment]
yes, RESTEasy Classic.

Tried with RESTEasy Reactive and it gives `jakarta.ws.rs.ProcessingException: Response could not be mapped to type java.util.concurrent.Flow$Publisher<java.lang.String>`

What does the user need to do to fix this?

**Comment by jamezp** [comment]
RESTEasy 6.2 requires Java 11. I've got a JIRA to move the reactive io from the client https://issues.redhat.com/browse/RESTEASY-3262. The idea is to move it to the resteasy-rxjava2 and create the java.util.concurrent in the client by default.

**Comment by geoand** [comment]
@rsvoboda I don't think `Publisher` ever worked with the `Reactive REST Client` to begin with :)

**Comment by cescoffier** [comment]
@jamezp rxjava does not use Flow, they are still using reactive streams (RXjava 2 and 3).

Flow is part of the jdk, so there is no additional dependency.

**Comment by jamezp** [comment]
> @jamezp rxjava does not use Flow, they are still using reactive streams (RXjava 2 and 3).
> 
> Flow is part of the jdk, so there is no additional dependency.

@cescoffier Right, I guess I don't really need to remove the reactive IO dep first. We just need to add readers/writers for the JDK types.

**Comment by cescoffier** [comment]
\CC @jponge

**Comment by diogocarleto** [comment]
Hi guys, same issue here after migrating to Quarkus 3.6.9, I'm using resteasy classic too

**Comment by rsvoboda** [comment]
Thanks @diogocarleto, org.reactivestreams.Publisher - java.util.concurrent.Flow.Publisher adapter approach works well

Just a small correction to the code example: `mutiny.zero.flow.adapters.AdaptersToFlow.publisher(pongClient.getPong());`

**Comment by cescoffier** [comment]
Using the adapter is the recommended way.

**Comment by rsvoboda** [comment]
> Using the adapter is the recommended way.

@cescoffier Is there any pointer in Quarkus docs? If not, should be there a note?

**Comment by cescoffier** [comment]
@rsvoboda https://smallrye.io/smallrye-mutiny-zero/1.0.0/flow-adapters/

And so, duplicating all documentation is not desirable.

**Comment by rsvoboda** [comment]
Cool, thanks @cescoffier
