### ISSUE TITLE
ConfigMapping - multiple 'parent' prefix code files and 'child' code files - confusing errors

### ISSUE THREAD

**Issue by connorsadlervelo** [quarkusio/quarkus#30948]
### Describe the bug

(Not sure if this is a bug or something we're doing which isn't supported or advised)

In our project we have a mix of @ConfigMapping files, multiple of which use the same "parent" prefix name e.g. @ConfigMapping(prefix = "org.acme")
and others use a "child" or "module" prefix name e.g. @ConfigMapping(prefix = "org.acme.mymodule")

We use application.yaml config files with a normal hierarchy of keys and sub keys etc.
We use Kotlin code for our @ConfigMapping files.

We're not sure if multiple ConfigMapping files using the same parent prefix is allowed.
Are we doing something wrong here?

This all worked fine until I tried to add a new 'child' branch and settings, which were very similar to an existing 'child' but with a different 'child'/'module' name. Then I started getting errors on Quarkus startup like this:

Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
  org.acme.mymodule.mysetting does not map to any root

The correct "mysetting" setting was in the config file and in the correct place in the hierarchy, and the @ConfigMapping file was present. The error appears to say that the setting has been found in application.yaml but the corresponding code was not found.
As part of the investigation I noticed:
1. This 'parent' vs 'child' @ConfigMapping usage - if I remove all the 'parent' ones, it fixes the problem.
2. If I add @Startup to an @ApplicationScoped service which uses the @ConfigMapping class, it fixes the problem.
3. I can also configure SmallRye to ignore these errors, but I'd rather fix it another way if possible.

I've created a small reproducible which reproduces the problem to a certain extent (the error in the reproducible mentions the parent setting, not a child setting, but is similar and can be 'fixed' in similar ways as above)

### Expected behavior

Quarkus should startup successfully

### Actual behavior

Quarkus Startup Fails with an error as described above

### How to Reproduce?

Please see attached, including README.md
[quarkus-config-mapping-problem-feb-2023.zip](https://github.com/quarkusio/quarkus/files/10674528/quarkus-config-mapping-problem-feb-2023.zip)

### Output of `uname -a` or `ver`

Darwin Connors-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.4.1 2022-08-12 LTS OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS) OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)

### Quarkus version or git rev

main project: 2.13.3.Final, reproducible: 2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/connor/dev/tools/apache-maven-3.8.4 Java version: 17.0.4.1, vendor: Azul Systems, Inc., runtime: /Users/connor/.sdkman/candidates/java/17.0.4.1-zulu/zulu-17.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Yes, you can have multiple mapping classes sharing the prefix.

The issue here is something else. The mapping class is not injected or annotated with `@Unremoveable`, so that excludes the class from the Config system, and then there is no mapping available to satisfy the configuration.

If you add an injection point or use the `@Unremoveable` annotation, it works as expected.

**Comment by radcortez** [comment]
Yes, this also prevents requiring configuration from mappings found in the classpath, but that is not in use by the application.
