### ISSUE TITLE
Register a custom redirect handler in REST clients

### ISSUE THREAD

**Issue by jdussouillez** [quarkusio/quarkus#30942]
### Description

Add a new feature so we can register a custom redirect handler in REST clients.

**Why?**
One of the case if to prevent errors when running POST requests and the server responds HTTP 307: `ClientWebApplicationException: Received: 'Server response is: 307' when invoking: Rest Client method: ...`

[RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-10.3.8) says:

> If the 307 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

So it should be possible to "confirm" the redirect on non GET/HEAD requests by using a custom redirect handler that will check if we must redirect or not.

More details in https://github.com/quarkusio/quarkus/issues/26517

### Implementation ideas

Vert.x [`HttpClient::redirectHandler`](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClient.html#redirectHandler-java.util.function.Function-) method can do that.

[In the current Quarkus version, it's used to log the HTTP 3xx response](https://github.com/quarkusio/quarkus/blob/2.16.1.Final/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientImpl.java#L177)

Maybe register a custom redirect handler (like it's done for HTTP filters and exception mappers) would be the simplest solution.

```java
// quarkus.rest-client.test0.follow-redirects=true

@Path("/")
@RegisterRestClient(configKey = "test0")
@RegisterProvider(MyCustomRedirectHandler.class) // <----- Right there
public interface Test0ApiClient {

    @POST
    @Path("foo")
    Uni<FooResponse> foo(/* ... *.);
}
```

```java
import io.vertx.core.http.RequestOptions; // TODO: Do not use "RequestOptions" class because we don't want to expose Vert.x types
import javax.ws.rs.core.Response;

@ApplicationScoped
public class MyCustomRedirectHandler implements RedirectHandler {

    @Override
    public Uni<RequestOptions> handleRedirect(Response response) {
        // Return null item to keep the original response (redirect).
        // Return request options to send a new request. See https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClient.html#redirectHandler-java.util.function.Function-
    }
}
```

The major problem is we would probably need new API types (to wrap Vert.x types and not expose them).

**Comment by geoand** [comment]
I think this is something we want, the only issue being figuring out the proper types to expose.

**Comment by Serkan80** [comment]
Correct me if I'm wrong but this is already possible with MicroProfile Rest Client, see the documentation:

https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_following_redirect_responses

Try to add this in your application.properties:

`<client_interface_name>/mp-rest/followRedirects=true`

**Comment by geoand** [comment]
It is, but this is about letting the client decide when to redirect or not

**Comment by Sgitario** [comment]
The property `follow-redirects` only redirects on GET and HEAD methods

To give a better context: this feature was also requested in Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/There.20is.20a.20way.20to.20auto.20redirect.20POST.20on.20rest-client-react.3F

To sum up, we can certainly support this feature, but we need to find a common API, so it's supported in both rest-client classic and reactive vendors. Then, internally for each one:

- `quarkus-rest-client-reactive` uses the Vert-x HTTP Client see related topic [here](https://vertx.io/docs/vertx-core/java/#_30x_redirection_handling).
- `quarkus-rest-client` uses the apache HTTP Client by default which similarly to the Vert.x HTTP Client, needs special configuration to make redirections work on POST methods.

**Comment by geoand** [comment]
> so it's supported in both rest-client classi

This is not a hard requirement actually

**Comment by Sgitario** [comment]
I've added a first implementation to support this feature only in REST Client Reactive: https://github.com/quarkusio/quarkus/pull/31142

For REST Client classic, let's add it into a separate pull request in the future. Taking into account that:
- We could use the same RedirectHandler API in REST Client Reactive
- In REST Client classic is going to be more complex to support it because we don't have access to the internal HTTP Client implementation, so perhaps we should support it first in RESTEasy.
