### ISSUE TITLE
Error of quarkus:dev when the project.build.directory is overridden by a profile

### ISSUE THREAD

**Issue by nghialunatech** [quarkusio/quarkus#30961]
### Describe the bug

In a project I have configured the following profile that overrides the default project build directory with `target-api`:

```xml
    <profile>
      <id>api</id>
      <build>
        <directory>target-api</directory>
      </build>
    </profile>
```

With that profile, I have no problem compiling / packaging the app (`mvn clean package -Papi`), the artifacts are found under `target-api` instead of `target`

However when launching the quarkus dev mode (`mvn clean quarkus:dev -Papi`), it failed with an error indicating that the dev mojo still looks for compiled classes under `target`

> Hot reloadable dependency com.example:quarkus_playground:1.0-SNAPSHOT has not been compiled yet (the classes directory /quarkus-project/target/classes does not exist)

### Expected behavior

The quarkus:dev mojo should launch normally

### Actual behavior

The following error is thrown:

> Hot reloadable dependency com.example:quarkus_playground:1.0-SNAPSHOT has not been compiled yet (the classes directory /quarkus-project/target/classes does not exist)

### How to Reproduce?

Steps to reproduce:

1. Init an empty project with the latest version of quarkus (2.16.1.Final as the time of writing)
2. Add a profile that overrides the build directory (as in the bug description)
3. Run `quarkus:dev` with the profile, e.g. `mvn quarkus:dev -P<profile>`

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

2.16.1.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

Here is the quick fix I'm applying to get rid of the issue (I'm not sure if it is the right place to patch but it works :D)

Add this line after line 74 of the file below

`mp.getOriginalModel().getBuild().setDirectory(mp.getModel().getBuild().getDirectory());`

https://github.com/quarkusio/quarkus/blob/e48aace483cf24d24b566b5786731e98351a7027/devtools/maven/src/main/java/io/quarkus/maven/QuarkusBootstrapProvider.java#L67-L78

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
Until this gets fixed, a workaround would be to add `-Dquarkus.bootstrap.effective-model-builder` to the command line.

**Comment by nghialunatech** [comment]
@aloubyansky thank you, I confirm that the workaround works well in my case, but the fix #31099 doesn't, I got the following error (note the double space between 'directory' and 'does'):
`Hot reloadable dependency com.example:quarkus_playground:1.0-SNAPSHOT has not been compiled yet (the classes directory  does not exist)`

**Comment by aloubyansky** [comment]
@nghialunatech thank for giving a try! Any suggestion how I could adjust https://github.com/quarkusio/quarkus/pull/31099/files#diff-dc99e382b2438c2e7d943842a3ccb85601e871933ff86a567639972daf359db4 to reproduce this next issue?

**Comment by nghialunatech** [comment]
> @nghialunatech thank for giving a try! Any suggestion how I could adjust https://github.com/quarkusio/quarkus/pull/31099/files#diff-dc99e382b2438c2e7d943842a3ccb85601e871933ff86a567639972daf359db4 to reproduce this next issue?

Oh now I cannot reproduce the error either, it's weird 😅 Seems to be a problem of cache in my local repository, after I cleaned it up and installed a fresh patched version of quarkus-maven-plugin, it is working just fine now (tested against 2.15.1.Final and 2.16.1.Final). Sorry for the false alarm.

**Comment by aloubyansky** [comment]
No problem, thanks for verifying!
