### ISSUE TITLE
Offer facilities to separate the notion of Quarkus core from the Quarkus platform

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3098]
We know there will be a Quarkus git repo and repos hosting other extensions (up to one per extension).
We know we want Quarkus extension writers to join a given Quarkus platform train compatibility wise.
We know some extensions are more aligned with the Quarkus mission of Cloud Native focused platform, and we need to differentiate them.
We know we may want to offer an "golden path" technology wise for people that want to get things to work and are not after a specific underlying implementation.

**Comment by gsmet** [comment]
I think this is well in progress with the platform effort. I don't think we need an issue for it anymore.
