### ISSUE TITLE
Multiple handlers for amazon-lambda extension

### ISSUE THREAD

**Issue by evdh** [quarkusio/quarkus#3099]
**Description**
Currently, only a single Handler/Function is allowed in the Amazon Lambda extension. Meaning you would have to build a single artifact/zipfile for each lambda. If you have a large project consisting of dozens of endpoints/lambdas, building all this would take forever. It should be possible to build one artifact with multiple lambdas and then specify which handler you want to to use when deploying.

**Implementation ideas**
See the following: https://github.com/marcinczeczko/quarkus-lambda-native/issues/1#issuecomment-508665645

**Comment by evanchooly** [comment]
this is provided via #3180
