### ISSUE TITLE
Make sure we have an upgrade recipe for migrating the persistence.xml (and maybe web.xml?)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31007]
/cc @ia3andy @maxandersen @aloubyansky

**Comment by ia3andy** [comment]
@gsmet https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/jakarta-ee-9.yml#L865

**Comment by gsmet** [comment]
Yes, I saw that yesterday, I will test it.
