### ISSUE TITLE
Impossible to create a project with Maven 3.9.0

### ISSUE THREAD

**Issue by josephassiga** [quarkusio/quarkus#31011]
### Describe the bug

When tring to bootstrap a Quarkus project with  this command 
`mvn com.redhat.quarkus.platform:quarkus-maven-plugin:2.13.5.SP1-redhat-00002:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=quarkus-backend \
    -DplatformGroupId=com.redhat.quarkus.platform \
    -DplatformVersion=2.13.5.SP1-redhat-00002 \
    -DclassName="org.mycompany.quarkusbackend" \
    -Dpath="/quarkus-backend" \
    -Dextensions="resteasy,openshift`

And keep having this errors : 
` A required class was missing while executing com.redhat.quarkus.platform:quarkus-maven-plugin:2.13.5.SP1-redhat-00002:create: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory`

### Expected behavior

Bootstrap succeed

### Actual behavior

Errors with this message : ` A required class was missing while executing com.redhat.quarkus.platform:quarkus-maven-plugin:2.13.5.SP1-redhat-00002:create: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory`

### Output of `uname -a` or `ver`

Darwin mac 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0

**Comment by rsvoboda** [comment]
```
git grep BasicRepositoryConnectorFactory
devtools/cli/src/main/java/io/quarkus/cli/core/Reflections.java:        org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.class,
independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java:import org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory;
independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext.java:            locator.addService(RepositoryConnectorFactory.class, BasicRepositoryConnectorFactory.class);
```
CC @aloubyansky

**Comment by crowne** [comment]
I also ran into this problem while on maven 3.8.6, then upgraded maven to 3.9.0
I also tried the following plugin versions with the same result
- io.quarkus.platform:quarkus-maven-plugin:2.16.2.Final
- io.quarkus.platform:quarkus-maven-plugin:2.16.1.Final
- io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final
- io.quarkus.platform:quarkus-maven-plugin:2.15.3.Final

**Comment by agoncal** [comment]
I even tried with the latest 3Alpha4 but it also fails: `mvn -U io.quarkus:quarkus-maven-plugin:3.0.0.Alpha4:create`

**Comment by gsmet** [comment]
Yes, Maven 3.9.0 is not supported at the moment, for all versions of Quarkus.

**Comment by CharlieQiu2017** [comment]
It appears that Quarkus is not the only project affected by this issue. A similar bug report has appeared in an unrelated project: https://help.mulesoft.com/s/article/Issues-with-Maven-3-9-0-when-deploying
This Maven bug report might be related: https://issues.apache.org/jira/browse/MNG-7471
Basically, both maven itself and quarkus-maven-plugin depends on connector-basic, but they use different versions with incompatible API. The Maven bug above is currently "closed", but it is "fixed" by forcing all plugins to use the new version: https://github.com/apache/maven/pull/732

**Comment by joergsesterhenn** [comment]
Will this be backported into 2.16.x as well? This would be great, since we really want to move to maven 3.9.x. timely.

**Comment by lucasmelz** [comment]
which version of Maven should I use for it to compile and work...?

**Comment by aloubyansky** [comment]
The minimum Maven version would be 3.6.3.

**Comment by joergsesterhenn** [comment]
Sorry to see this didn't get backported to 2.16.6? I really hoped this would be fixed in the new version of quarkus. Will this be in the next 2.x patch @aloubyansky ?

**Comment by aloubyansky** [comment]
I meant "to go into a micro release", not minor, just fixed my comment above

**Comment by geoand** [comment]
> but it looks a bit too risky for a micro

I completely agree with this

**Comment by aloubyansky** [comment]
I could prepare a 2.16 branch with Maven 3.9 support backported in case somebody wants to build a test it in their environment and give feedback. That could potentially help with the decision.

**Comment by agoncal** [comment]
Is having a 2.17 totally out of the way? This looks pretty important to me, as most developers have the latest Maven version installed.

**Comment by rsvoboda** [comment]
> most developers have the latest Maven version installed

Maybe most developers you work with :) But I would say there is quite a group of people who install one version locally and stay with it for quite some time. CI tooling on the other hand can be pretty eager with updates. GH Actions for example use the latest versions quite quickly.

**Comment by agoncal** [comment]
GH Actions is already using 3.9 (we had this issue a few weeks ago and had to patch our workflows)

**Comment by rsvoboda** [comment]
yup, I needed to do the same on our repos. Windows runners were updated sooner than Ubuntu ones.

**Comment by tauzinger** [comment]
It's hard to get started on quarkus with this error occurring.

**Comment by maxandersen** [comment]
Use Quarkus 3 ie. Use more recent Quarkus. Its on cr2 now. Final soon here. 

Or use maven 3.8 with Quarkus 2. 

Thats the current workarounds
