### ISSUE TITLE
Offer a Gradle project template via gradle init

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3101]
https://stackoverflow.com/questions/34856834/create-custom-build-init-type-for-gradle-build-init-plugin

`gradle init --type quarkus` would be awesome

Check if that can be done so we decide to keep it in 1.0 or not

**Comment by Dufgui** [comment]
`gradle init` seems to be not used for this, it's more artifact and language approach, you can see it here: 
https://github.com/gradle/gradle/tree/master/subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal
or 
https://docs.gradle.org/current/userguide/build_init_plugin.html

So their is some other approach:

- gradle init-script : https://docs.gradle.org/current/userguide/init_scripts.html but seems we must have some local conf file first
- gradle custom-init : https://github.com/maxbalan/gradle-custom-init but it's a third party tools with just one contributor but still active
- use our existing maven template generator
- fork one of this : https://github.com/townsfolk/gradle-templates or https://github.com/blackbaud/gradle-templates and create our gradle plugin to do it

Any preference @emmanuelbernard @gsmet  ?

**Comment by emmanuelbernard** [comment]
No real preference for me.

**Comment by Dufgui** [comment]
personnaly i prefere the last 2 approaches:
- use our existing maven template generator
- fork one of this : https://github.com/townsfolk/gradle-templates or https://github.com/blackbaud/gradle-templates and create our gradle plugin to do it

we can do it as //

**Comment by aloubyansky** [comment]
Just to make it clear, we are not offering this feature in a pure Gradle way. Instead, the existing Maven plugin has been enhanced with `buildTool` parameter which when set to `GRADLE` will make it produce the initial Gradle project.

**Comment by Dufgui** [comment]
gradle have n't custom "project free" task, so I am not sure we can do it, and keep a tool usefull.
