### ISSUE TITLE
HTTP access log %t missing enclosing brackets

### ISSUE THREAD

**Issue by konfilios** [quarkusio/quarkus#31010]
### Describe the bug

According to the [Common Log Format (CLF)](https://en.wikipedia.org/wiki/Common_Log_Format) the datetime specified as `%t` in http access logs should be enclosed in brackets as in `[10/Oct/2000:13:55:36 -0700]`, however this is not what you get when configuring your own pattern.

The problem lies in the following code ([see link here](https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/attribute/DateTimeAttribute.java#L16)):

```
    private static final String COMMON_LOG_PATTERN = "[dd/MMM/yyyy:HH:mm:ss Z]";
```

This pattern is fed to `DateTimeFormatter.ofPattern()` which, [according to the docs](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html), treats the brackets as special characters denoting the start and end of an optional datetime part.

The trivial fix involves single-quoting the brackets in the pattern string as follows:

```
    private static final String COMMON_LOG_PATTERN = "'['dd/MMM/yyyy:HH:mm:ss Z']'";
```

### Expected behavior

The `%t` modifier in http access logs should print common log format datetime enclosed in brackets as in `[10/Oct/2000:13:55:36 -0700]`

### Actual behavior

The `%t` modifier in http access logs prints datetime without brackets as in `10/Oct/2000:13:55:36 -0700`

### How to Reproduce?

Either check access logs in a simple web app or contrast the output of the following expressions' evaluation:

1. `DateTimeFormatter.ofPattern("'['dd/MMM/yyyy:HH:mm:ss Z']'", Locale.US).format(ZonedDateTime.now())`
2. `DateTimeFormatter.ofPattern("[dd/MMM/yyyy:HH:mm:ss Z]", Locale.US).format(ZonedDateTime.now())`

### Output of `uname -a` or `ver`

Darwin Users-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Output of `java -version`

1.8.0_351

### Quarkus version or git rev

2.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by gsmet** [comment]
@konfilios would you be interested in providing a PR?

**Comment by konfilios** [comment]
@gsmet sure, I'll fork the repo and raise a PR

**Comment by geoand** [comment]
@konfilios are you still interested in fixing this or do you want us to handle it?

**Comment by cescoffier** [comment]
We should go ahead and fix it.

**Comment by geoand** [comment]
@cescoffier are you taking it or should I whip up a fix?

**Comment by cescoffier** [comment]
I will provide a fix _soonish_(tm)

**Comment by geoand** [comment]
🎉
