### ISSUE TITLE
Jakarta SOAP service in native mode

### ISSUE THREAD

**Issue by droger88** [quarkusio/quarkus#31021]
### Describe the bug

We are using an existing soap client built using Jakarta EE, and it works fine in the JVM mode. However it does not work in Native mode.

The client is using following dependencies:
```
   <dependency>
      <groupId>jakarta.xml.ws</groupId>
      <artifactId>jakarta.xml.ws-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <scope>runtime</scope>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-ri</artifactId>
      <type>pom</type>
      <version>4.0.0</version>
    </dependency>
```
To Inject the client
```
    @Produces
    @ApplicationScoped
    public AwesomeClient awesomeClient() {
        return AwesomeClient.builder().url("localhost:8080").connectTimeout(30).build();
    }
```

### Expected behavior

It should successfully communicate with the soap service

### Actual behavior

when triggering the soap call, getting following error
```
20:00:01 SEVERE b91d1ca4-5060-41ea-8760-a4e2e09686cc [ja.xm.ws] (executor-thread-0) Class org.glassfish.hk2.osgiresourcelocator.ServiceLoader cannot be loaded: java.lang.ClassNotFoundException: org.glassfish.hk2.osgiresourcelocator.ServiceLoader. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
```

### Output of `uname -a` or `ver`

Darwin B09S9O22 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

The error seems like it can't find the class when it is looking for the provider implementation, which is documented here https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/

So I tried adding following to the reflection configuration
```
[
  {
    "name": "jakarta.xml.ws.spi.Provider",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "com.sun.xml.ws.spi.ProviderImpl",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]
```
Then it starts to fail at build time
```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: jakarta.annotation.PreDestroy. This error is reported at image build time because class com.sun.xml.ws.server.SingletonResolver is registered for linking at image build time by command line
```
So I am just wondering if there is a solution for this? We clearly don't want to rebuild our client using the extension quarkus-cxf, since we do have other applications are using those soap clients.

**Comment by geoand** [comment]
The SOAP client is not something we support in Quarkus.

I propose having a look at https://github.com/quarkiverse/quarkus-cxf
