### ISSUE TITLE
How to initialize io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration before RuntimeConfigSetupBuildStep

### ISSUE THREAD

**Issue by anvo1115** [quarkusio/quarkus#31025]
I need to get some application configuration as RunTimeConfigurationSourceValueBuildItem sending http requests.
When I turned on metrics using
`quarkus.micrometer.binder.http-client.enabled = true`

I got an error:
```
io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
javax.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_97d170e1550eee4afc0af065b78cda302a97674c
- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
```

How can I initialize HttpBinderConfiguration before my RunTimeConfigurationSourceValueBuildItem is initialized?

**Comment by geoand** [comment]
Could you provide a little more detail on what exactly you are trying to achieve? 
Some sample code you have tried would also be nice

**Comment by anvo1115** [comment]
I have a build step

`    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    public RunTimeConfigurationSourceValueBuildItem configure(MyConfigSourceRecorder recorder,
                                                              MySourceConfig myConfig,
                                                              BuildProducer<MyConfigSourceEnabledBuildItem> myConfigEnabled) {
        RuntimeValue<ConfigSourceProvider> myConfigSourceProvider = recorder.configSources(myConfig);
        myConfigEnabled.produce(new MyConfigSourceEnabledBuildItem());
        return new RunTimeConfigurationSourceValueBuildItem(myConfigSourceProvider);
    }`

In recorder.configSources I sent a request to the Consul server using Http client.
So at this point application with 'quarkus.micrometer.binder.http-client.enabled = true' failed with the error from the description.

**Comment by geoand** [comment]
So essentially you are looking to obtain a configuration value from Consul?

**Comment by anvo1115** [comment]
yes

**Comment by geoand** [comment]
@anvo1115 I am going to close this. If you still have questions, feel free to comment and/or reopen
