### ISSUE TITLE
Redirect in graphql

### ISSUE THREAD

**Issue by Bazalii** [quarkusio/quarkus#31034]
### Description

There are no opportunities to redirect to another resource in graphQL response. For example, if authentication request succeeds, redirect user to their profile and if not, redirect them again to registration page.

### Implementation ideas

To my mind, the most native way to implement this feature would be to allow adding custom status codes to successful responses(3xx in this case) without force overriding them in [this class](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/SmallRyeGraphQLExecutionHandler.java).

**Comment by jmartisk** [comment]
I'm not sure I understand what you're expecting - you want to be able to, inside a GraphQL API class, when a GraphQL operation arrives from a client, be able to send an HTTP redirect instead of sending a GraphQL response?

**Comment by Bazalii** [comment]
@jmartisk I want to return a response to the client(in my case a browser) that sent a request with a "message" to redirect to another source. It is common for browsers to redirect to another resource when response contains Location header and response code, which is, for example, 303.

**Comment by Bazalii** [comment]
> While I'm not sure it's a good idea to do this, you can already do this by injecting a `io.vertx.ext.web.RoutingContext` into your GraphQL api, and then calling
> 
> ```
> routingContext.redirect("http://new-url.com");
> ```
> 
> within the GraphQL operation

Yes, but it seems like a forced compromise because it will result in `java.lang.IllegalStateException: Response head already sent` because we don't have an option to make graphql query/mutation void or to return `Void`

**Comment by phillip-kruger** [comment]
GraphQL (Spec) does not concern itself with the transport layer (HTTP in our case), for that we follow another spec called GraphQL Over HTTP (see https://github.com/graphql/graphql-over-http). See specifically the section on response here : https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#response.

"When a server receives a well-formed GraphQL-over-HTTP request, it must return a well‐formed GraphQL response."

There is no mention of redirects in that spec, and not something I thing we should do. Our target clients is not browsers (in the same way that HTML is). If you are doing something in a browsers then you typically should use JavaScript and handle the response that decides if another request needs to be made. 

I think we can move this to a discussion (it's not an issue) and discuss there further if this should be allowed somehow. Thoughts ?

**Comment by jmartisk** [comment]
I'd say we could maybe "support" this by just downgrading the `IllegalStateException` to be logged at DEBUG level only so that your log doesn't get polluted. That wouldn't be a very big deal, but I probably wouldn't go any further, because we think this is not really a legitimate thing to do.
You would then do a redirect by calling `routingContext.redirect()` and, then preferably returning null, because the returned value will be ignored anyway.

**Comment by Bazalii** [comment]
> I'd say we could maybe "support" this by just downgrading the `IllegalStateException` to be logged at DEBUG level only so that your log doesn't get polluted. That wouldn't be a very big deal, but I probably wouldn't go any further, because we think this is not really a legitimate thing to do. You would then do a redirect by calling `routingContext.redirect()` and, then preferably returning null, because the returned value will be ignored anyway.

I agree with you. That would be a good solution.
