### ISSUE TITLE
Support testing with Gradle

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3103]
**Description**
(Describe the feature here.)

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

**Comment by emmanuelbernard** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/quarkus-dev/ZXla0Oak9UE

**Comment by Dufgui** [comment]
@aloubyansky you have fixed it no ? You can close it ?
