### ISSUE TITLE
Custom Kafka header cannot be consumed through reactive messaging

### ISSUE THREAD

**Issue by iabughosh** [quarkusio/quarkus#31044]
### Describe the bug

I am following the Quarkus Kafka Avro guide to apply Avro schema with Schema registry. Everything is working fine so far; however, when I tried to add a custom header (Named it with 'JWT'), it appears in Kafka and I can see it through Kafka-ui tool but when I consume the message through reactive messaging (@Incoming), the custom header cannot be found, only Avro headers appears in the metadata.

### Expected behavior

To read custom header as well.

### Actual behavior

Custom header is not being read.

### How to Reproduce?

Reproducer:https://github.com/iabughosh/kafka-avro

Steps:

1. Run docker-compose shipped with project.
2. execute curl command  
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"title":"The Godfather","year":1972}' \
```
3. Try reading custom header or debug the incoming Message. Custom header cannot be found.
4. Verify custom header in Kafka using CLI or UI.

### Output of `uname -a` or `ver`

22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by iabughosh** [comment]
Great, Thanks @ozangunalp!, it worked like a charm.

Appreciate if I can have more resources on this.

**Comment by ozangunalp** [comment]
@iabughosh Thanks!

You can get more info on http://smallrye.io/smallrye-reactive-messaging/ and https://quarkus.io/guides/kafka
