### ISSUE TITLE
In memory postgress

### ISSUE THREAD

**Issue by fjtirado** [quarkusio/quarkus#31047]
### Description

An extension that add embedded sql library ([zonkyo](https://github.com/zonkyio/embedded-postgres)) as quarkus service

The idea is to copy the code available in this [location](https://github.com/kiegroup/kogito-apps/tree/main/persistence-commons/quarkus-postgresql-inmemory-parent) to the quarkiverse

### Repository name

quarkus-postgresql-inmemory

### Short description

embedded in-memory sql library based on zonkyo

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- postgresql
- zonkyo
- embedded db
...

### Team Members

- ftirado
- cristianonicolai

**Comment by Sanne** [comment]
Hi,

interesting, I didn't know about the embedded-postgres - but could you elaborate on why this might be preferrable over the containerized instances?

I can appreciate that not everyone has Docker / podman available; on the other hand I'd prefer to not have many different options to broadly accomplish the same thing.

cc/ @gastaldi opinions?

**Comment by gastaldi** [comment]
@Sanne I share the same opinion, however I think this may be useful for CIs that (as you said) do not provide a functional Docker environment (eg.Windows in GitHub). 

But I am curious on what other use cases besides testing this is useful

**Comment by fjtirado** [comment]
@Sanne 
Short answer, memoty footprint
Long answer, this is an embedder library, not a real postgres server, it takes less memory and should be used for development pods, not for production

**Comment by gastaldi** [comment]
How about calling it `quarkus-embedded-postgresql` to match the library name?

**Comment by fjtirado** [comment]
@gastaldi yes, thats a far better name

**Comment by ricardozanini** [comment]
This embedded library can still have persistence, right? So one could use it as a replacer for SQLite, for example? I think we can explain the limitations, but not come to conclusions for users saying "this is for development only". I'd rather say something like "this is an embedded database and has limitations XYZ". WDYT?

In complex CIs spamming multiple containers is resource hungry, having a lightweight option could benefit the whole ecosystem, IMO.

**Comment by Sanne** [comment]
Thanks for all quick answers!

I like lightweight (obviously), but if it's not exactly the same thing it's not a great form of integration testing.
Also what's the postgresql container actual cost? I didn't measure and I could be wrong, but it certainly "feels" light.

In short I'm still skeptical, wondering how many other users would ask for this. On the other hand, if it lives in Quarkiverse and you're volunteering to maintain it I don't see why I should deny you the fun :)
