### ISSUE TITLE
Combining @Separator and @BeanParam

### ISSUE THREAD

**Issue by jesjos** [quarkusio/quarkus#31050]
### Describe the bug

In a recent [PR](https://github.com/quarkusio/quarkus/pull/29735), `@org.jboss.resteasy.reactive.Separator` was changed so that it can be applied to fields as well as parameters, with the expressed intention of making it work within classes used as `@BeanParams`.

This does not work as expected. Given `@Separator(",")` and `foo,bar,baz` I get a list with a single element `foo,bar,baz` instead of a list with three elements `foo`, `bar`, `baz`

### Expected behavior

If a collection field in a class is annotated with `Separator`, and that class is used as a `@BeanParam` in a web service, the values should be present in the field as separate items in the collection. 

### Actual behavior

The collection field is a collection with a single item, containing the entire parameter string.

### How to Reproduce?

https://github.com/jesjos/quarkus-separator-bean-param-bug-repro

In the `feature/main` branch the same behavior is reproduced for the latest Quarkus 3.x snapshot

### Output of `uname -a` or `ver`

Darwin computername 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Output of `java -version`

penjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/home/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.6, vendor: Amazon.com Inc., runtime: /Users/home/.sdkman/candidates/java/17.0.6-amzn Default locale: en_FI, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

**Comment by gastaldi** [comment]
I can confirm this is a bug with the following test in `io.quarkus.resteasy.reactive.server.test.simple.SeparatorQueryParamTest`: 


```java
    @Test
    public void multipleQueryParamBean() {
        get("/hello/bean?name=foo,bar&name=one,two,three&name=yolo")
                .then()
                .statusCode(200)
                .body(is("hello foo bar one two three yolo"))
                .header("x-size", "6");
    }
```

**Comment by geoand** [comment]
@FroMage do you want to have a look at this one?
