### ISSUE TITLE
Unable to get javax.servlet.http.HttpServletRequest and javax.servlet.http.HttpServletResponse

### ISSUE THREAD

**Issue by MarcAntoine-Beauvais** [quarkusio/quarkus#31054]
### Describe the bug

I am trying to use https://github.com/tomdesair/tus-java-server for uploading files but for that I will need javax.servlet.http.HttpServletRequest and javax.servlet.http.HttpServletResponse.
But when I try, I get: "No request is currently active"

### Expected behavior

I would like to have current HttpServletRequest and HttpServletResponse.

### Actual behavior

When launching the application and calling:
curl -X 'GET' \
  'http://localhost:8080/upload/**' \
  -H 'accept: */*'

I get the error "No request is currently active".

### How to Reproduce?

Sources are here:
https://github.com/MarcAntoine-Beauvais/quarkus-tus

You might have to give executable rights to `gradlew`.
Then run: `quarkus dev`
And call:
```
curl -X 'GET' \
  'http://localhost:8080/upload/**' \
  -H 'accept: */*'
```

### Output of `uname -a` or `ver`

Linux WSL

### Output of `java -version`

17.0.4

### GraalVM version (if different from Java)

GraalVM CE 22.2.0

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment]
When using RESTEasy Reactive you don't need those Servlet types to handle files. See [this](https://quarkus.io/guides/resteasy-reactive#accessing-the-request-body) part of the documentation.
