### ISSUE TITLE
Outdated SLF4J version in bom

### ISSUE THREAD

**Issue by cameronprater** [quarkusio/quarkus#31058]
Seems like the slf4j version in the bom is outdated (still on 1.7.36, latest is 2.0.6), despite the dependency being checked for by dependabot. Is there a reason why the dependency hasn't been bumped? I am revamping my Quarkiverse extension with a custom Discord API built with Mutiny Vertx (sorry for the long delay for release), and having a dependency conflict with SLF4J. Can't seem to prevent Quarkus from importing the old version despite excluding it.

**Comment by cameronprater** [comment]
Seems like the jboss slf4j logmanager was updated to 2.0.6 recently if that was the roadblock:

https://github.com/jboss-logging/slf4j-jboss-logmanager/commits/main/pom.xml

**Comment by gsmet** [comment]
We could probably try upgrading now. I'll give it a try.
