### ISSUE TITLE
Offer template engine that is build time and reactive

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3106]
CC @mkouba

**Comment by FroMage** [comment]
Well, fine, but then you guys will have to start commenting on the syntax choice that are being made because the two of us are not enough eyes.

**Comment by FroMage** [comment]
I mean, look at https://github.com/mkouba/qute/issues issues and start commenting.

**Comment by jorsol** [comment]
Vert.x includes some support for the following template engines out of the box:

- Handlebars
- Jade
- MVEL
- Thymeleaf
- Apache FreeMarker
- Pebble
- Rocker

But probably some don't support all the features required for Quarkus.

**Comment by nimo23** [comment]
Maybe templating can be done by  [Jakarta Expression Language](https://projects.eclipse.org/projects/ee4j.el)?

**Comment by emmanuelbernard** [comment]
Closing as Qute is not a thing

**Comment by mkouba** [comment]
@emmanuelbernard What do you mean "not a thing"? ;-) Anyway, +1 for closing this issue.

**Comment by emmanuelbernard** [comment]
s/not/now/ Sorry :D

**Comment by erichelgeson** [comment]
Just a link for those of us (like me) who are not familiar https://quarkus.io/guides/qute-reference
