### ISSUE TITLE
gradle tooling not JDK 20 compatible

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#31063]
### Describe the bug

We run integration tests (e.g. `io.quarkus.gradle.nativeimage.BasicJavaNativeBuildIT`) on latest JDK 20 early access builds and we see a failure in the gradle tooling. It looks like gradle doesn't like the bytecode version just yet:

```
 Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
	... 176 more
```

See: https://github.com/graalvm/mandrel/actions/runs/4140128711/jobs/7158708230#step:11:198

### Expected behavior

Gradle tooling works with JDK 20

### Actual behavior

Fails to eat JDK 20 produced bytecode.

### How to Reproduce?

Run the mentioned integration test on JDK 20 EA.

**Comment by geoand** [comment]
We are aware of this and waiting for the next Gradle version

**Comment by famod** [comment]
Gradle 8.0 was released yesterday but it seems we need 8.1?
- https://github.com/gradle/gradle/issues/23488
- https://github.com/gradle/gradle/issues/23489

**Comment by geoand** [comment]
It appears so...

**Comment by tklinchik** [comment]
Any updates on this? Seems like the latest version of gradle still doesn't have this addressed.

**Comment by famod** [comment]
Newly released Gradle 8.1 [says](https://docs.gradle.org/8.1/release-notes.html):
> In [JVM-based projects](https://docs.gradle.org/8.1/release-notes.html#jvm), it is now possible to use Java 20 for compiling, testing, and running Java projects.

It's not stated here though (yet?): https://docs.gradle.org/current/userguide/compatibility.html

**Comment by renegrob** [comment]
> It's not stated here though (yet?): https://docs.gradle.org/current/userguide/compatibility.html

Gradle 8.3 seems now to support Java 20

**Comment by geoand** [comment]
A PR bumping the Gradle version is worth a try I would say
