### ISSUE TITLE
Make sure each relevant extension offer a liveliness and readiness data

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3107]
Of course first checking if MP Health is an enlisted extension

**Comment by loicmathieu** [comment]
+1 I miss this functionality from other framework :
- When Agroal is in the classpath, we should automatically check the DS and add a health check about it
- When Kafka is in the classpath we should automatically check the broker and add a health check
- ...

Of course we need to be able to disable those health checks if needed.

As Quarkus is build time and prevent the usage of reflection, I don't know how to implement this as we need from one extension (agroal) to test if another is here (health check) and if yes provide the needed build items ...

I'm interested in this functionality so I'm happy to help if needed ;)

**Comment by loicmathieu** [comment]
As I understand liveness : it's about restarting the application so the extension should not provide liveness because I don't want to restart my apps if my DB is down because it will be useless (it's the DB that needs to be restarted).

**Liveness**: global UP for the apps without checking any dependecies (so any extension)
**Readiness** : UP for my apps and all it's dependecies (DB, broker, LDAP, external rest, ...)

So I think only health check needs to be provided by extentions, they map to readiness checks (in k8s).

**Comment by emmanuelbernard** [comment]
@loicmathieu on the build time discovery, the idea is to have a `LivenessBuildItem` and a `ReadinessBuildItem` probably in a shared extension like `health-producer-extension` or something like that.
Every extension wanting to produce a health check would add a dependency to this shared extension and produce the relevant build item.
The healthcheck extensions proper would depend on `health-producer-extension` and consume the build items.

There is I think a trick to make sure to push these health check classes in the runtime path if and only if the build item is consumed.
Only if there is a build item consumer would this build step be called. That solves that problem.
The second problem is to have this healthcheck code pushed at runtime.
@stuartwdouglas  can advise but I imagine either or a combination of the SR health check extension registering the class for reflection or generating this class via the gizmo based recorder?

**Comment by stuartwdouglas** [comment]
I have made a start on this here: https://github.com/stuartwdouglas/quarkus/pull/new/build-in-health-checks

No tests but it should work, it just needs some actual health check implementations.

**Comment by kenfinnigan** [comment]
Though I think it's a good idea to offer built in health checks for our extensions, we need to do it in a way that's very easy to turn off.

My concern is that users will want very specific to their application ways for different extensions, so we need a way to turn them off so it's an "all or nothing" type approach

**Comment by emmanuelbernard** [comment]
Can you provide guidance for a uniform mechanism? We need to push that in
the extension author guide.

**Comment by kenfinnigan** [comment]
TBH I'm not sure.

One option might be extensions having an `optional` dep on MP Health API jar to then create a `HealthCheck` implementation in the runtime. I *think* that would mean the implementation would be DCE'd unless the health check extension was present to bring along the impl.

However, I'm not sure optional dependencies play with the augmentation stuff, so could be way off base

**Comment by emmanuelbernard** [comment]
@kenfinnigan we already have that problem solved. If sr-health is not present the extension e.g. Quarkus-agroal` won’t add  healthchecks. That’s what Stuart did. Or are you saying we need an extension per specific healthcheck implémentation manually added by the user e.g.
`quarkus-agroal-healthcheck-dbready`, `quarkus-agroal-healthcheck-dblowlatency`, etc. The latter does not sound reasonable. 

So would we be fine with having the health check activated as long as sr-health is in the class path. Or do we want some ways to disable health check per extension?
I suppose the Quarkus-sr-health extension could react to a property to whitelist or blacklist extension propagated healthchecks. The BulitItem can pass the extension name + health check name for supporession. It will all be suppressed at build time in this case

**Comment by stuartwdouglas** [comment]
Some way to disable it based on name would probably be useful. A simple way would be to enable them all by default, but then have a quarkus.health.disable-builtin={regex}

**Comment by kenfinnigan** [comment]
We also need a way to disable them all with a config setting.

Would the disable config be using extension name or health check name?

**Comment by emmanuelbernard** [comment]
Right that's what I was trying to say, have a property to override which one is enabled or disabled. Though I think regexp is a universal standard for non user friendly right alongside Perl code :D

On the granularity, you tell me, I'm not expert but I suspect we don't initially want the healthcheck name to be part of an extension API
So I would start with extension name only and keep the door open for `/health-check-name` Doesn't MP do something like that in the config somewhere?

```
#none
quarkus.health.built-in=none 
#all but orm and validator
quarkus.health.built-in=-quarkus-hibernate-orm -quarkus-hibernate-validator
#only orm and validator
quarkus.health.built-in=quarkus-hibernate-orm quarkus-hibernate-validator
#only orm but non canonical
quarkus.health.built-in=+quarkus-hibernate-orm -quarkus-hibernate-validator
#only orm except the 2nd level cache one
quarkus.health.built-in=+quarkus-hibernate-orm -quarkus-hibernate-orm/cache
#assumes LivenessBuildItem offers a name field
#should name be unique within an extension between Liveness and readiness?
```

Do health

**Comment by kenfinnigan** [comment]
Yes I think you can hit each health check endpoint by going to `/health/[health-check-name]`, so makes sense to use that.

Would the below

```
#only orm but non canonical
quarkus.health.built-in=+quarkus-hibernate-orm -quarkus-hibernate-validator
```

actually be:

```
quarkus.health.built-in=+quarkus-hibernate-orm
```

as we've already disabled everything by specifying a value for the property?

Might also help if we used `+` when adding, even if there's no `-`:
```
#only orm and validator
quarkus.health.built-in=+quarkus-hibernate-orm +quarkus-hibernate-validator
```

**Comment by emmanuelbernard** [comment]
Yes, that's why I said it's non canonical (not encouraged form). I jsut wanted to make sure we had an implementation that would not fail and was relatively regular.
Yes we can definitely make + optional.

**Comment by loicmathieu** [comment]
Hello,

I like the way it evolves but please, implements a more friendly-way to
de-active health checks! (regex, or +name -name => too complex)

As each health check will be provided by an extension, I think it's the
extension responsability to offers a simple enable property that is true by
defaults like:
quarkus.agroal.health.enable=false
quarkus.kafka.health.enable=false

Then we can provide in the health extension a global kill switch to disable
all extension health check
quarkus.health.extension.enable=false

So each extension that provides health check will document it and take care
of providing the correct property.
There will be no "magic health check management" for all extensions with a
single property.

By the way, it like other framework do ;)

**Comment by emmanuelbernard** [comment]
The drawback with your proposal is that each extension must implement the same logic , make sure to document it and not forget about it. That's why I was trying to avoid that.
But if we really feel that `quarkus.foo.health.enable` is  better and overweight the future bugs and code burden, we can go for it.

**Comment by michael-simons** [comment]
Great discussion here.

My 2 cents:

```
quarkus.health.enabled=true # Generally enabled
quarkus.health.kafka.enabled=false # Selectively disabled
quarkus.health.agroal.enabled=true # Should be the default
```

and an infrastructure that detects the individual `HealthCheck` who's identifier fits the extension and uses or discards them depending on the above flag. Of course the extension must not implement this logic over and over again.

Structuring the above properties this way round makes it IMHO clear in which responsibility things are.

**Comment by rsvoboda** [comment]
I like this. The only concern is around kafka/agroal naming, we would need some logic similar to "add extension" in quarkus maven plugin.

This should be safer, but not so nice ...
```
quarkus.health.${atrifactId}.enabled=false
```

**Comment by emmanuelbernard** [comment]
The artifactId trick would suck UX wise and not be aligned with an extension config namespace. So my proposal is to:

1. have the extension push the Readiness/LivenessBuildItem where the build item has the namespace provided (`agroal`, `hibernate-orm` etc)
    The extension would be responsible to push a reasonable name often based on its `quarkus.[foo]` namespace use (agroal is funny enough an exception).
2. Have the health extension silence the BuildItems according to `quarkus.health.*`

That looks like readable for a userr and minimal code dupe on the extensions side.

**Comment by emmanuelbernard** [comment]
oh an +1 on the global default `quarkus.health.extensions.enabled`

**Comment by loicmathieu** [comment]
I someone working on this now? I'm interesting of providing an implementation for agroal

**Comment by loicmathieu** [comment]
@emmanuelbernard now that the extension health check mechanism is implemented and some health check are on there way thanks to #5073 and #4793 can we close this one ?

**Comment by emmanuelbernard** [comment]
We could close this one and have a uber issue listing the extensions that should and don't have them.

**Comment by loicmathieu** [comment]
This is the purpose of #5073 :)
If you feel that some extensions are missing health check, please add them to the list !
