### ISSUE TITLE
Make the Mongo CodecRegistry available for @Inject

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#31087]
### Description

Unless I missed something, it does not appear possible to get Codecs used by the system to map to/from `Document` by hand.

I have an edge case where I would like to use a pojo for a file's metadata in Gridfs, but the client only supports a plain `Document`, rather than allow mapping from a pojo like with a collection.

I have tried injecting `CodecRegistry`, `Codec<MyPojo>`, but these were not resolvable.

I also tried `MongoClientSettings.getDefaultCodecRegistry().get(MyPojo.class)`, but seemed to not be able to find a codec, leading me to believe that it perhaps isn't the same registry Quarkus uses?

**Comment by evanchooly** [comment]
Try injecting the `MongoClient` and getting the codec registry from there.

**Comment by GregJohnStewart** [comment]
@evanchooly Happen to know how? I actually already am but see no method to get a codec registry

**Comment by GregJohnStewart** [comment]
ah, I see, need to get the database first:

`client.getDatabase("...").getCodecRegistry()`

**Comment by evanchooly** [comment]
I'm looking it up on my phone which is awkward but if you get the database you can get the registry from there
