### ISSUE TITLE
Unresolved javax usages on 3.0

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#31083]
### Describe the bug

Normal maven build without tests of main succeeds, however the intellij build for debugging purposes fails because it cannot resolve javax in the following classes:

Issue:
```java 
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.52.1)",
    comments = "Source: health/v1/health.proto")
```
On generated classes at `quarkus-grpc-stubs`: 
`grpc.health.v1.HealthGrpc`
`io.grpc.reflection.v1alpha.ServerReflectionGrpc`

Also at `quarkus-ark-deployment`, class `io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject` this annotation cannot be resolved: `@org.gradle.internal.impldep.javax.inject.Inject`

### Expected behavior

javax usages not found and intellij is able to build

### Actual behavior

intellij build fails like this:

```
quarkus/extensions/grpc/stubs/target/generated-sources/protobuf/grpc-java/grpc/health/v1/HealthGrpc.java:7:18
java: cannot find symbol
  symbol:   class Generated
  location: package javax.annotation
```

### How to Reproduce?

1. checkout 
2. debug the `io.quarkus.opentelemetry.deployment.OpenTelemetrySamplerConfigTest` at `opentelemetry/opentelemetry-deployment`

### Output of `uname -a` or `ver`

Darwin ... 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)

### Quarkus version or git rev

main

### Additional information

% mvn --version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home:...../maven/current
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: ..../.sdkman/candidates/java/17.0.4.1-tem
Default locale: en_PT, platform encoding: UTF-8
OS name: "mac os x", version: "13.2", arch: "aarch64", family: "mac"

IntelliJ IDEA 2022.1.4 (Ultimate Edition)

**Comment by gsmet** [comment]
@cescoffier assigning to you for the gRPC generated stuff. I don't think what you did is broken or gone though as I was unable to build the tree without your stuff in. So that might be a corner case or an oddity.

**Comment by cescoffier** [comment]
I found the reason and I don't like it....
That stub project is using the regular `protoc` to generate the stub, so... no post-processing.

**Comment by paomian** [comment]
have same issue in 3.0.1.Final

```
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.51.1)",
    comments = "Source: exapmle.proto")
```
