### ISSUE TITLE
Unable to locate persister with named datasource and hibernate-orm

### ISSUE THREAD

**Issue by ddlenz** [quarkusio/quarkus#31091]
Hi,
I'm configuring two datasources and hibernate ORM for a legacy application that uses DAOs (yeah)
Version 2.16.1.Final

Named (oracle) endpoint fails:
```
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${PDR_HOST}:${PDR_PORT}/${PDR_NAME}
quarkus.datasource.username=${PDR_USER}
quarkus.datasource.password=${PDR_PASSWORD}
quarkus.hibernate-orm.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
quarkus.hibernate-orm.packages=org.neoninc.cds.pdr

quarkus.datasource.asset.db-kind=other
quarkus.datasource.asset.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.asset.jdbc.url=jdbc:oracle:thin:@${ASSET_HOST}:${ASSET_PORT}:${ASSET_NAME}
quarkus.datasource.asset.username=${ASSET_USER}
quarkus.datasource.asset.password=${ASSET_PASSWORD}
quarkus.hibernate-orm.asset.dialect=org.hibernate.dialect.Oracle10gDialect
quarkus.hibernate-orm.asset.packages=org.neoninc.cds.asset
quarkus.hibernate-orm.asset.datasource=asset
```
Endpoints on the default datasource work as expected.

Endpoint on the named datasource returns:
```
REST error: Cause=IllegalArgumentException: Unable to locate persister: org... RootCause=UnknownEntityTypeException: Unable to locate persister: org...
```
The oracle endpoint works if I reconfigure the named datasource to be the default datasource.
Default (oracle) endpoint works:
```
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@${ASSET_HOST}:${ASSET_PORT}:${ASSET_NAME}
quarkus.datasource.username=${ASSET_USER}
quarkus.datasource.password=${ASSET_PASSWORD}
quarkus.hibernate-orm.dialect=org.hibernate.dialect.Oracle10gDialect
quarkus.hibernate-orm.packages=org.neoninc.cds.asset
```

Any thoughts will be much appreciated!

**Comment by yrodiere** [comment]
It's hard to say with an incomplete stacktrace, but I'd be willing to be you're trying to use an entity from package `org.neoninc.cds.pdr` in the `asset` endpoint.

If you need more help, please provide the full stacktrace, and preferably a reproducer.

**Comment by ddlenz** [comment]
If the default datasource is oracle and the named datasource is postgres, the named datasource endpoint fails with the same error.
If both datasources are postgres, the named datasource endpoint fails with the same error.

**Comment by ddlenz** [comment]
Thanks to a colleague's suggestion, this is working having changed the asset entity manager annotations as follows:
```
	@Inject
	@PersistenceUnit("asset")
	private EntityManager entityManager;
```

**Comment by yrodiere** [comment]
Glad you were able to fix this, thanks for reporting back!
