### ISSUE TITLE
Wrong dependency of Quarkus Redis in docs 

### ISSUE THREAD

**Issue by spencercjh** [quarkusio/quarkus#31095]
### Description

Refer to https://quarkus.io/guides/redis-reference#installation, I can't install dependencies about Quarkus Redis with the following Gradle dependency:

```groovy
implementation("io.quarkus:quarkus-redis")
```

but it can work with:

```groovy
implementation "io.quarkus:quarkus-redis-client"
```

![image](https://user-images.githubusercontent.com/29922079/218243759-85435797-dd97-4136-bce2-c3288842bdc3.png)

I think it's a mistake of docs. How can I fix it?

**Comment by cescoffier** [comment]
Yes, it's a documentation issue. You can fix it by updating https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/redis-reference.adoc

**Comment by spencercjh** [comment]
Duplicate with https://github.com/quarkusio/quarkus/issues/27344 but problems still there. I will fix it.
