### ISSUE TITLE
Custom error page for code 403 is ignored when using Open ID Connect Authorization Code Flow for web applications

### ISSUE THREAD

**Issue by dirkweil** [quarkusio/quarkus#31103]
### Describe the bug

When using Open ID Connect Authorization Code Flow for a web application with 
- server-side rendering (e. g. JSF) and
- requesting a page with a security constraint restricting it to some specific security role,
the browser is redirected to the OIDC provider (e. g. Keycloak for authentication.

If a user with insufficient rights (aka roles) logs in, the application responds with a code `403`.
There seems to be no way of specifying a custom page for that case. It tried `<error-page>` in `web.xml` as well as `quarkus.oidc.authentication.redirect-path` and `quarkus.oidc.authentication.restore-path-after-redirect` properties - none worked.

### Expected behavior

Logging in with insufficient rights should redirect to a custom error page specified in `web.xml` or by some Quarkus property.

### Actual behavior

Logging in with insufficient rights produces a code `403` causing the browser to display a generic error page, leaving the user with no option to return to the login process (back button does not really work).

### How to Reproduce?

Reproduce:

1. `git clone https://github.com/GEDOPLAN/quarkus-demo.git` (You need the module `quarkus-keycloak` only - the other subprojects are demos for other, unrelated Quarkus features).
2. `cd quarkus-keycloak`
3. `mvn quarkus:dev`
4. Use a browser and navigate to http://localhost:8080
5. Click the link `private`
6. Log in as `willi` with password `willi_123`

### Output of `uname -a` or `ver`

Linux dw-sv14 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by sberyozkin** [comment]
@dirkweil It is not really a bug, you need to intercept `ForbiddenException` first, with a custom JAX-RS `ExceptionMapper` and then either create a final Response there or redirect to the public page which will provide a custom response.

**Comment by sberyozkin** [comment]
@dirkweil I'll keep the issue open till you confirm using the custom exception mapper helps

**Comment by dirkweil** [comment]
A custom exception mapper for io.quarkus.security.ForbiddenException helped me out, but ...

- Beware of the name clash io.quarkus.security.ForbiddenException vs. javax.ws.rs.ForbiddenException!
- The custom mapper is called regardless of the originating request being made for the server side rendered web app or the REST api. Therefore I had to create different responses in the mapper based on the request uri. The solution is working but is not very intuitive. Maybe I'll try to extract the code into a small library and make it configurable by application properties. 

Thanks for your quick help!

**Comment by sberyozkin** [comment]
@dirkweil 

Thanks for confirming using the mapper works, hmm, it would've been better to have `javax.ws.rs.ForbiddenException` thrown in JAX-RS flows but it is unlikely we will change it now to avoid breaking the existing mappers.

>The custom mapper is called regardless of the originating request being made for the server side rendered web app or the REST api.

Can you clarify please what do you mean ? Is this web app protected, if yes, how ?

>Therefore I had to create different responses in the mapper based on the request uri.

Perhaps the mapper should, in both cases, return Response redirecting the user to a public page ?

**Comment by sberyozkin** [comment]
@dirkweil OK, I've looked at your quarkus demo code, so you have a requirement to have 403 returned for non OIDC web-app flows (API calls) but an HTML page for the requests originating from the browser.

**Comment by sberyozkin** [comment]
@dirkweil I think in cases like this one where different types of clients expect different types of response it is reasonable to expect that the error handler has to decide how to handle the error for a given request. Quarkus Security can't decide if it is a web-app or an API so can't really be throwing different types of forbidden exceptions depending on the request context.
Perhaps, you can use `@Authenticated` instead of `@RolesAllowed` , checks the roles in the code and throw different types of exceptions depending on the context - something like that, but it has its own side-effects as far as the code simplicity is concerned.

HTH, let me close this issue now. Please open new Discussions to continue discussing if you'd like

**Comment by dirkweil** [comment]
The application offeres a JSF web ui as well as a REST api. Both are secured. I used a `TenantResolver` for differentiating between web ui and REST, but both security property sets refer to the same Keycloak realm and client.

For the web ui, trying to request a secured page without sufficient roles shall result in a redirect to a public error page explaining the situation to the requesting user and giving them appropriate links to work on.

For the REST part, it is totally expected to get a 403 response when calling an endpoint without sufficient roles - that's what die code is for, isn't it.

So my solution is to return a 403 response from the mapper, if the request uri starts with the REST application path and a 302 response in other cases. That's not brilliant but works for now.

It would have been nice, if <error-page> in web.xml would have been taken into account. But I guess, the OIDC security layer is on top of the servlet layer. 

A spontanuous proposal: A new Quarkus property for specifying a redirect path in case of forbidden requests, e. g. quarkus.oidc.authentication.forbidden-path. If set, create a redirect response. If unset create a 403 response.
