### ISSUE TITLE
CORS application configuration seems broken/not working as expected

### ISSUE THREAD

**Issue by coolersham** [quarkusio/quarkus#31116]
### Describe the bug

Since version 2.16 the CORS configuration has changed. However, even when applying the configuration proposed in the official migration guide (which should result in the exact behaviour as before 2.16) or manually configuring origins URLs requests from the client will not go through.
```
quarkus:
  http:
    cors:
      origins: /.*/
```

### Expected behavior

Request from the client should go through.

### Actual behavior

Following CORS error is presented on the client side.

```
Access to fetch at 'http://localhost:8080/<resource-path>' from origin 'http://localhost:<port>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Output of `java -version`

18.0.1.1

### Quarkus version or git rev

2.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1

**Comment by sberyozkin** [comment]
@coolersham Can you please create a reproducer ? The only thing which has changed in 2.16 is that a wildcard origin support has to be enabled by the user if the  CORS restriction is not really needed.

>or manually configuring origins URLs 

do you mean it does not work even if you add `http://localhost:8080` to the list of Origins ?

**Comment by coolersham** [comment]
As mentioned in my initial issues description I tried both. Setting the origins to the wildcard `/.*/` (also tried only `*`). The former regex should by documentation 'revert' the behaviour to the one pre V16. However, that is not the case. Using V15.3 with the old way of configuring CORS works without any problems.
 
>do you mean it does not work even if you add http://localhost:8080 to the list of Origins ?
Correct, I tried adding (among other URLs) `http://localhost:8080` or even the local IP `http://X.X.X.X:8080`.

**Comment by sberyozkin** [comment]
@coolersham Hmm, I'd like to see a reproducer, more details, please. If even configuring an Origin manually does not work (removing  the wildcard support OOB was the only major change in 2.16) then something is broken, but without a reproducer is not really possible to tell what.

**Comment by coolersham** [comment]
@sberyozkin alright, will do so once I got the time for that.
Strangely it even results in an `HTTP 200` status code through an `OPTION` request.
```
Origin http://localhost:<application-port> is not allowed by Access-Control-Allow-Origin. Status code: 200
```

**Comment by sberyozkin** [comment]
@coolersham Sure, please do. FYI, if Quarkus fails to match Origins it will now fail with 403. So yes, please create a reproducer as it feels like something is interfering

**Comment by sberyozkin** [comment]
@coolersham Please re-open with the reproducer if you still can't make it work as expected

**Comment by bertrandp** [comment]
@sberyozkin looks like I have the same issue so I am not opening a new one.

As said, the migration guide mention :
```
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
```
But I think YAML does not allow us to translate these two lines into one YAML file, see this invalid file : 
```
quarkus:
  http:
    cors: 
      true
      origin: http://localhost:8080
``` 

I think you can quickly reproduce it from https://code.quarkus.io/ with 2 extensions : RESTEasy Reactive and YAML configuration

**Comment by bertrandp** [comment]
Ok there is a hack, cf https://quarkus.io/guides/config-yaml#configuration-key-conflicts
```
quarkus:
  http:
    cors:
      ~: true
      methods: GET,PUT,POST
```
