### ISSUE TITLE
Make sending message to the event bus more tightly integrated

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3111]
Just a slightly different API hiding the `Message` sent and received:

* `send(payload)`
* `publisher(payload)`
*`request(payload) : CompletionStage<O>` (the response)

Mostly the sending part of #2529

**Comment by geoand** [comment]
I am pretty sure this has been covered by the introduction of `io.vertx.mutiny.core.eventbus.EventBus` so I'll close this. Feel free to reopen if there is still work to do
