### ISSUE TITLE
RESTEasy Reactive: support NewCookie `sameSite` attribute

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#31122]
### Description

In `main` for Jakarta 3.1 there's support for `NewCookie.SameSite` but our `org.jboss.resteasy.reactive.common.headers.NewCookieHeaderDelegate` does not serialise it, so it doesn't end up in the response.

We should support it.

Also see https://github.com/quarkiverse/quarkus-renarde/issues/100

**Comment by geoand** [comment]
Seems like RESTEasy Classic has yet to implement this as well

**Comment by geoand** [comment]
It was easier than I thought: https://github.com/quarkusio/quarkus/pull/31124

**Comment by geoand** [comment]
Closed by https://github.com/quarkusio/quarkus/pull/31124
