### ISSUE TITLE
Decorate reactive messaging connectors with health and metrics

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3113]
For each connector:

1. define the liveness and readiness sensors
2. define the key metrics 
3. implement the sensors
4. implement the metrics

**Comment by jmartisk** [comment]
Hi @cescoffier, would you mind if I took this and tried to come up with some initial implementation? I'd start with Health and then perhaps Metrics as well. Or do you want to wait until these get into the specification? (I saw some open issues for it) Perhaps if we tried to implement this early, it could serve as a base for backporting it into the spec.

The liveness checks should be 'true' in all cases, I'd say (?). A broken connector is probably not the reason to discard the whole application. Perhaps one exception here would be reporting 'false' once we detect that the application is going down (after `@BeforeDestroyed(ApplicationScoped.class)` is called)

The readiness checks would be
- MQTT - this would be composed from the `isSubscribed` status of all sources and `isReady` status of all sinks
- AMQP - attempt to do `AmqpClient.connect()` to see if that works
- Kafka - perhaps just check that the connector wasn't closed, not sure how else to determine whether it is working at the moment

More details to be thought through later...

**Comment by francois-travais** [comment]
Hi @jmartisk, for MQTT, I think you could also check `mqttClient.isConnected()`

**Comment by vietk** [comment]
Hello

Does the Health of a reactive messaging application will be impacted by the back-pressure overflow?  
i.e:  in a case of blocking JaxRs endpoint that floods an outgoing channel, we could imagine to switch the application in a "not ready" state

Regards

**Comment by cescoffier** [comment]
The overflow would be more a "live" check.

**Comment by cescoffier** [comment]
Metrics have been done already. Health in progress.

**Comment by vietk** [comment]
> The overflow would be more a "live" check.

An overflow is not something recoverable by the application ?

**Comment by cescoffier** [comment]
you can recover but it does not involve the readiness check, only the liveness check. You cannot switch from alive to not-ready.

**Comment by cescoffier** [comment]
Health support added for the Kafka and AMQP connectors (upstream).

**Comment by cescoffier** [comment]
Fixed by #10779
