### ISSUE TITLE
RESTEasy Reactive @Context is empty or not mapping correctly

### ISSUE THREAD

**Issue by JakubWylezek** [quarkusio/quarkus#31147]
### Describe the bug

I'm trying to receive context using @Context AwsProxyRequestContext or @Context AwsProxyRequest.
Thanks to 2.16.2 Final release, resteasy reactive no longer produce 404. 
However now context data is missing.

This is my app code:

    @GET
    @Path("/hello1")
    public String hello(@Context AwsProxyRequestContext context) {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        log.info("hello1 " + gson.toJson(context));
        return "hello1";
    }

    @GET
    @Path("/hello2")
    public String hello2(@Context AwsProxyRequest contex) {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        log.info("HEH " + gson.toJson(contex));
        return "hello2";
    }

Logs for lambda AWS: 
hello1
![image](https://user-images.githubusercontent.com/38432671/218706525-9d566c55-47c5-4de4-b0f2-e52ee51979e8.png)

hello2
![image](https://user-images.githubusercontent.com/38432671/218706761-d98ebe7e-0d32-4d8d-9717-f39caf376c40.png)

Dependencies I use: 

    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-amazon-lambda-rest'

    implementation 'io.quarkiverse.amazonservices:quarkus-amazon-s3:1.6.1'
    implementation 'software.amazon.awssdk:netty-nio-client:2.19.22'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.quarkus:quarkus-junit5'
    implementation 'com.google.code.gson:gson:2.9.1'

### Expected behavior

After I changed dependency from 

 implementation 'io.quarkus:quarkus-resteasy-reactive'

to 

 implementation 'io.quarkus:quarkus-resteasy'

also using 2.16.2 Final release version, without any changes in code, context data is filled correctly 

Logs from lambda AWS:
hello1

![image](https://user-images.githubusercontent.com/38432671/218715211-baf4dd6d-4fdc-489b-95ac-aa6080ba7e95.png)

hello2

![image](https://user-images.githubusercontent.com/38432671/218713114-a89086fd-b4e3-4c18-8d14-c8087a0e3e5e.png)

### Output of `uname -a` or `ver`

Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04) OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1 ------------------------------------------------------------  Build time:   2022-08-05 21:17:56 UTC Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918  Kotlin:       1.6.21 Groovy:       3.0.10 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          11.0.18 (Azul Systems, Inc. 11.0.18+10-LTS) OS:           Windows 10 10.0 amd64

**Comment by geoand** [comment]
This should have been fixed in Quarkus `2.16.2.Final` by https://github.com/quarkusio/quarkus/pull/30776.

Can you attach a sample application that suffers from the problem?

**Comment by Sgitario** [comment]
I think that the problem here is that the `AwsProxyRequestContext` instance in Resteasy Reactive is a proxy of the actual instance. So, the fields of this proxy are null, but when you call any getter, then you will get the correct value. 

And `gson` is only using the fields to generate the JSON, that's why you see it empty. 

Instead of using `gson`, you can use ObjectMapper as:

```java
ObjectMapper objectMapper = new ObjectMapper();
String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(ctx);
```

And I think you should see all the context now.

**Comment by geoand** [comment]
Thanks for the analysis @Sgitario.

Closing this as it is not a Quarkus issue

**Comment by geoand** [comment]
Aside from the correctness issue mentioned by @Sgitario, you probably want to avoid using Gson and instead opt for Jackson because Jackson is already used for deserialization and including another JSON library will do you no favors in terms of runtime footprint.
