### ISSUE TITLE
camel application properties are not overridden at runtime

### ISSUE THREAD

**Issue by alainpham** [quarkusio/quarkus#3116]
**Describe the bug**
When using the camel extension, application properties such ```quarkus.camel.servlet.url-patterns``` or ```quarkus.camel.routes-uris``` are not overridden at runtime with the native executable. 

**Expected behavior**
When overriding application variables with a config/application.properties file or environment variables. They should be taken into account by the executable.

**Actual behavior**
Still takes the value from the development version in resources/application.properties no matter what.

**To Reproduce**
1. ```git clone https://github.com/alainpham/quarkus-kafka-camel-servlet.git```
2. ```cd quarkus-kafka-camel-servlet```
3. Add some configuration change regarding camel in the docker-compose.xml as environment vars file. We can try to change the url patterns or the uris to the routes.xml.
```
    environment:
      - 'MP_MESSAGING_INCOMING_IN_EVENTS_BOOTSTRAP_SERVERS=kafka:9092'
      - 'MP_MESSAGING_OUTGOING_OUT_EVENTS_BOOTSTRAP_SERVERS=kafka:9092'
      - 'QUARKUS_CAMEL_SERVLET_URL_PATTERNS=/camelsss/*'
      - 'QUARKUS_CAMEL_ROUTES_URIS=file:/camel/routessss.xml'
```
4. ```docker-compose up```
5. The new values are not taken into account

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 3.10.0-957.21.3.el7.x86_64
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
 - GraalVM version (if different from Java): 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183340.buildslave.jdk8u-src-tar--b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
```
 - Quarkus version or git rev: 0.18.0

**Comment by geoand** [comment]
The corresponding Camel Config is configurable at build time only as can be seen [here](https://github.com/quarkusio/quarkus/blob/256a120ce6c910630139225f73ec2dd18daa068f/extensions/camel/camel-core/runtime/src/main/java/io/quarkus/camel/core/runtime/CamelConfig.java#L14).

It very much looks like that was intentional but I have no experience with Camel on Quarkus so I can't provide any meaningful insight here

**Comment by alainpham** [comment]
Ok, thanks. I just discovered that there were different Configuration Root Phases. It does make sense for most of those properties to be fixed & unchangeable at run time like disable jaxb & xml, however I think that routesUris should be changeable at run time. When I configure routesUris to read a file on some file system path, the file is read dynamically during run time even with the native executable. But maybe there is something I'm missing here that would have a big impact if we make it changeable during run time.

**Comment by gsmet** [comment]
@alainpham yes, it makes perfectly sense.

@lburgazzoli ?

**Comment by geoand** [comment]
It's probably best to ping the author(s) of the extension to get more feedback on the questions you raised.

**Comment by lburgazzoli** [comment]
@alainpham there is a property `deferInitPhase` that changes the way camel deal with routes: if set to true, routes are loaded at runtime however this reduces the optimization that camel can do as when building the route at build time, then the materialization of the route to the underlying processors is done at build time which has impacts on memory and start-up time (no need to parse xml, build the model and then materialize it).

**Comment by alainpham** [comment]
Thanks for the hint @lburgazzoli. I wan't so sure about what deferInitPhase really meant. The picture is becoming a bit clearer now but I still have to figure out a few things. 

1) If `deferinitPhase=false`, does that mean that the option `-H:IncludeResources=...` must to be added so that the resources are part of the native executable or are the xml routes declared in the property `routesUris` automatically baked into the executable?

2) If `deferinitPhase=true` then, wouldn't it make sense to have the property `routesUris` configured as `ConfigPhase.RUN_TIME`, to be able to then change it during runtime?

Many thanks.

**Comment by lburgazzoli** [comment]
> Thanks for the hint @lburgazzoli. I wan't so sure about what deferInitPhase really meant. The picture is becoming a bit clearer now but I still have to figure out a few things.
> 
>     1. If `deferinitPhase=false`, does that mean that the option `-H:IncludeResources=...` must to be added so that the resources are part of the native executable or are the xml routes declared in the property `routesUris` automatically baked into the executable?
> 

As I can recall, in such cases the resources are not included but they are processed at build time so the generated bytecode contains the materialized routes and there's no more need to have the original XMLs.

>     2. If `deferinitPhase=true` then, wouldn't it make sense to have the property `routesUris` configured as `ConfigPhase.RUN_TIME`, to be able to then change it during runtime?
> 

That make sense. We are now in the process of moving camel-quarkus in its new [home](https://github.com/apache/camel-quarkus) ad we have a number of thing to improve, can you raise an issue there ? 

> 
> Many thanks.

**Comment by alainpham** [comment]
@lburgazzoli, thanks it's clear to me now.
Sure I'll raise the issue on the apache repos.

Many thanks
