### ISSUE TITLE
ResponseExceptionMapper return null for entity object in response error #31154

### ISSUE THREAD

**Issue by rahilfayz** [quarkusio/quarkus#31161]
### Describe the bug

I implemented rest API which is calling in another microservice.
I build a response object that included an error message when it returns an error. When I called API through postman, I got an error message.
But I called this rest API in another micro service, I implemented a custom exception mapper. When I tried to get the entity object of response error, it returned null.
Please check attached file. I created a simple project that included two modules rest-client and rest API.
rest-client called rest API, and returned null for the entity object there is an error.
[quarkus-issue.zip](https://github.com/quarkusio/quarkus/files/10736203/quarkus-issue.zip)

### Expected behavior

I expect that it sends an entity object with a value which I created in rest-API resource.

### Actual behavior

It sends a null value for the entity object for the response error object.

### How to Reproduce?

1. Run two modules with this command:
  ./gradlew quarkusDev
  rest-api is running o localhost:8081
 rest-client running on localhost:8080
2. When reaching this endpoint
  http://localhost:8080/users/4
Response is : error + { null} 
We expect to show this : error + { user not exist with this id} 
Because this value wrapped for rest-api: http://localhost:8081/users/4modules

### Output of `java -version`

jave version 17

### Quarkus version or git rev

2.16.2.Final

**Comment by Sgitario** [comment]
This is indeed something we need to fix.
As a workaround, you can replace:
```java
println("error + {${response.entity}}")
RuntimeException("error + {${response.entity}}")
```

With:

```java
var responseEntity = String((response as ClientResponseImpl).entityStream.readAllBytes())
println("error + {${responseEntity}}")
RuntimeException("error + {${responseEntity}}")
```

And now you will get the expected message.

**Comment by Sgitario** [comment]
I've updated my previous comment and I think there is no much we can do here. Wdyt @geoand ?

**Comment by geoand** [comment]
Ah yeah, you are right.

**Comment by rahilfayz** [comment]
@Sgitario and @geoand 
Thanks for reply. 
I've tried with your suggestion, but it's not working. It still is null. 
Anyway, is there another way that I can get client message?

**Comment by anthonydenecheau** [comment]
@rahilfayz ,

I have same issue ? Did you fix it on your side ?

**Comment by anthonydenecheau** [comment]
Ok thanks @rahilfayz
