### ISSUE TITLE
Resteasy Reactive Server & Client error handling changes in case of Jackson exceptions.

### ISSUE THREAD

**Issue by holomekc** [quarkusio/quarkus#31163]
### Describe the bug

Resteasy Reactive Server & Client are wrapping error causes behind WebApplicationException, which changed the application error handling, so that our application was throwing 500 status codes instead of 400. In the case of the client the errors logs showed 400 status codes, although server returned 200.

### Expected behavior

I am able to handle errors the way I want to. Applies for server and client.

### Actual behavior

The changes in 0785582523e64d2f7d2128fdd4eadb04ae8bc1d2 are handling jackson errors and throw a WebApplicationException with 400 Bad request. Maybe there is a good reason behind this, which I do not see at the moment.

Our @ServerExceptionMapper are not able to handle jackson exceptions properly anymore. We have to log errors with a certain format. To recreate the old behavior of our application we were forced to unwrap the causes to handle the error properly again. 

For the client it is even more confusing. In a test we simulate the case that we are not able to parse the response properly. The test failed with info that server returned 400 error although the server response was 200 actually. The reason was again the mentioned changes. This was really confusing. 

I guess we can unwrap this as well, but I want to ask if this is really intended? It seems a bit inconsistent to wrap jackson errors but not everything else.

### How to Reproduce?

-

### Output of `uname -a` or `ver`

Darwin LMUCM870527 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 LTS

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

-

**Comment by geoand** [comment]
Thanks for reporting.

Can you please attach a sample application that exhibits the problem? It will be immensely useful so we can zero in on the problem and compare with the old behavior
