### ISSUE TITLE
OIDC Challenge response has JSON content type without body

### ISSUE THREAD

**Issue by Adelrisk** [quarkusio/quarkus#31184]
## Background

I configured my quarkus service for our SPA as described:

https://quarkus.io/guides/security-openid-connect-web-authentication#single-page-applications

When I send a request with the header " X-Requested-With: JavaScript", the response has all the expected characteristics from the article.

## Bug

The response includes a header `Content-Type` but no body. That is a conflict.

For example, the fetch API https://developer.mozilla.org/en-US/docs/Web/API/Response does not provide introspection methods to identify this case, and calling `json()` leads to the error: `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

### Expected behavior

The `Content-Type` should not be included in the response when there is no content.

### Actual behavior

This the a typical response in the browser:

```
HTTP/1.1 499 Client Error (499)
access-control-allow-origin: http://localhost:3000
access-control-allow-credentials: true
Content-Type: application/json
WWW-Authenticate: OIDC
content-length: 0
```

### How to Reproduce?

Use reproducer: https://github.com/Adelrisk/quarkus-reproducer-31184

OR

Follow the described instructions in https://quarkus.io/guides/security-openid-connect-web-authentication#single-page-applications

1. Add the extension `quarkus-oidc`
2. Disable redirects for javascript calls
```properties
quarkus.oidc.authentication.java-script-auto-redirect=false
```
3. Declare a protected resource
4. Access the protected resource as a JavaScript client. Here using curl:

```
curl 'http://0.0.0.0:8080/api/v1/profile' -H 'Accept: application/json' -H 'x-requested-with: JavaScript' -v
*   Trying 0.0.0.0:8080...
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> GET /api/v1/profile HTTP/1.1
> Host: 0.0.0.0:8080
> User-Agent: curl/7.87.0
> Accept: application/json
> x-requested-with: JavaScript
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 499 Client Error (499)
< Content-Type: application/json
< WWW-Authenticate: OIDC
< content-length: 0
< 
* Connection #0 to host 0.0.0.0 left intact
```

### Output of `uname -a` or `ver`

Linux Rechner 6.1.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.11-1 (2023-02-09) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2-ea" 2022-07-19

### Quarkus version or git rev

2.16.1.Final

**Comment by sberyozkin** [comment]
Hmm, `Content-Type: application/json` is definitely not added by `quarkus-oidc`.

@geoand @FroMage hey, are you aware of `RestEasy Reactive` or Vert.x route filter setting this content type if no content type is set ?

**Comment by sberyozkin** [comment]
I know JSON is supported by default by Resteasy Reactive

**Comment by geoand** [comment]
Yeah, it's used as the default in RR when a Resource method returns a POJO.
It would be nice to have a reproducer here in order to investigate exactly what's going on.

**Comment by sberyozkin** [comment]
@geoand I'll do a quick check with one of the local tests a bit later

**Comment by geoand** [comment]
👌

**Comment by Adelrisk** [comment]
Here is a reproducer: https://github.com/Adelrisk/quarkus-reproducer-31184

**Comment by sberyozkin** [comment]
Thanks @Adelrisk. I also did an independent test not even related to OIDC as such but to the authorization failure,

@geoand, FYI, if you update [this test](https://github.com/quarkusio/quarkus/tree/main/integration-tests/oidc-client-reactive), specifically, [ProtectedResource#userNameReactive](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client-reactive/src/main/java/io/quarkus/it/keycloak/ProtectedResource.java#L32) to have some random value in `@RolesAllowed` and then run the test as `mvn clean install -Dstart-containers -Dtest-containers > out.txt` and then search for `Response:`, you'll see: 
```
2023-02-15 19:08:17,450 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-4) Response: GET http://localhost:8081/protected/userNameReactive, Status[403 Forbidden], Headers[Content-Type=text/plain;charset=UTF-8 content-length=0], Body:
``` 

I guess the technical problem is, that when `Content-Type` is set in the response, it is now known yet if the actual body will be available ? If it is somehow possible to check then it would be simplest. Alternatively, set `Content-Type` only if it is `HTTP 200`, but there is a small risk of even `403` or `401` returning some custom data...

**Comment by geoand** [comment]
That's the question... I'd have to check and see

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/31205 takes care of it
