### ISSUE TITLE
Setting "quarkus.smallrye-openapi.open-api-version" in application.yml has no effect

### ISSUE THREAD

**Issue by jehrenzweig-leagueapps** [quarkusio/quarkus#31197]
### Describe the bug

The following code in a Quarkus project's `application.yml` file will not change the generated OpenAPI document's `openapi:` root property value, as the documentation on the "_Using OpenAPI and Swagger UI_" [page]([quarkus.smallrye-openapi.open-api-version](https://quarkus.io/guides/openapi-swaggerui#openapi)) indicates it should:
```
quarkus:
  smallrye-openapi:
    enable: true
    open-api-version: 3.0.1
```

### Expected behavior

Quarkus 2.16.2.Final targets OpenAPI 3.0.3 by default.  However, if you attempt to override this value with an earlier supported version (e.g. 3.0.1) in `application.yml`, the override value should appear in the root `openapi:` property in the OpenAPI document generated by the URL `/q/openapi?format=json`.

Example:
```
{
    "openapi" : "3.0.1",
    "info" : {
      "title" : "Testing OpenAPI Version Setter",
    }
}
```

### Actual behavior

Quarkus' default OpenAPI value (3.0.3) is still visible in the OpenAPI document generated by the URL `/q/openapi?format=json`; the value defined in `application.yml` is not applied.

Example:
```
{
    "openapi" : "3.0.3",
    "info" : {
      "title" : "Testing OpenAPI Version Setter",
    }
}
```

### How to Reproduce?

1. Verify that your Quarkus project's OpenAPI specification targets version 3.0.3 in the `/q/openapi?format=json` URL route, as described [here](https://quarkus.io/guides/openapi-swaggerui#expose-openapi-specifications).
2. Update your Quarkus project's `application.yml` code so that the `open-api-version` property value is set to `3.0.1`:
```
quarkus:
  smallrye-openapi:
    enable: true
    open-api-version: 3.0.1
```
3. Verify that your Quarkus project's OpenAPI specification targets version still targets 3.0.3.

### Output of `uname -a` or `ver`

Darwin LeagueAppss-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by phillip-kruger** [comment]
Have you tried `mp.openapi.extensions.smallrye.openapi=3.0.1` ?
or the yaml would be something like:

```
---
mp:
   openapi:
      extensions:
         smallrye:
            openapi: 3.0.1
```

see https://quarkus.io/guides/openapi-swaggerui#changing-the-openapi-version

**Comment by phillip-kruger** [comment]
It might not have been mapped. Let me check. Hold on

**Comment by phillip-kruger** [comment]
Yes it's not mapped. If you keen you can do a PR for that ? It's basically a mapping here: https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiConfigMapping.java

**Comment by phillip-kruger** [comment]
Yes ! Good catch ! That should solve it. So it was mapped to a constant and not the config key. Please make a PR with your change !

**Comment by phillip-kruger** [comment]
Hi @jehrenzweig-leagueapps , no worries you can ask here. Try this:

(I usually cd into the extension/deployment folder)

```
./mvnw -Dtest=io.quarkus.smallrye.openapi.test.jaxrs.OpenApiWithConfigTestCase surefire:test
```

**Comment by phillip-kruger** [comment]
it's surefire:test not surefire:tests (note the s).

**Comment by phillip-kruger** [comment]
And on Windows you might have to put the test in "" ,so :
```
./mvnw -f extensions/smallrye-openapi/deployment -Dtest="io.quarkus.smallrye.openapi.test.jaxrs.OpenApiWithConfigTestCase" surefire:test
```

**Comment by ygyg70** [comment]
I am able to configure the version using mp.openapi.extensions.smallrye.openapi when running dev UI, and by using openApiVersion configuration when using the maven plugin.
Was anyone able to use the application.properties value when running the maven plugin?

**Comment by phillip-kruger** [comment]
For the maven plugin you need to use maven properties. Also, I am not sure if all properties is supported in the maven plugin.
