### ISSUE TITLE
When running the native tests, the prod profile is used

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3119]
When running the tests on the native executable, the `test` profile should be used by default.

This is not the case as currently, the `prod` profile is used.

I thought it would be an easy fix but I had some weird behavior after fixing it. I think I'll need to discuss it with @stuartwdouglas .

I will create a PR as a base for discussion.

**Comment by gwenneg** [comment]
This was fixed by #3154, right?

**Comment by gsmet** [comment]
Yes, thanks for noticing!
