### ISSUE TITLE
Add native support for Hibernate Envers

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#3120]
**Description**
Hello,

is it possible to add Hibernate Envers module to easily audit JPA entities under Quarkus

Thanks by advance.

Damien

**Comment by atzoum** [comment]
Currently if envers is in the classpath quarkus:dev fails with:

```
Caused by: org.hibernate.service.UnknownServiceException: Unknown service requested [org.hibernate.envers.boot.internal.EnversService]
       at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
       at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.getService(SessionFactoryServiceRegistryImpl.java:98)
       at org.hibernate.envers.boot.internal.EnversIntegrator.integrate(EnversIntegrator.java:44)
       at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:275)
       at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
       at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:64)
       ... 13 more
```

After some quick investigation looks like `PreconfiguredServiceRegistryBuilder#buildQuarkusServiceInitiatorList` ignores `EnversServiceInitiator` even though the `RecordedState` holds the relevant `EnversIntegrator`. As a result the destroyed `StandardServiceRegistryImpl` is resetAndReactivated without `EnversServiceInitiator`, causing the aforementioned exception.

I would be very interested to have Envers working with Quarkus since this is currently blocking our migration from Wildfly. I could undertake this task with the appropriate guidance.

**Comment by gwenneg** [comment]
Was this issue fixed with #3250?

**Comment by dcdh** [comment]
It only works in jvm mode, not un native.

Regards,

Damien

Le mar. 20 août 2019 à 00:46, Gwenneg Lepage <notifications@github.com> a
écrit :

**Comment by gsmet** [comment]
@dcdh what's the issue you have with native?

**Comment by dcdh** [comment]
Hello Guillaume,

When I start my application it fails with this stacktrace:

2019-08-21 02:57:21,580 WARN  [io.qua.jae.run.JaegerDeploymentRecorder]
(main) Jaeger service name has not been defined, either as
'quarkus.jaeger.service-name' application property or JAEGER_SERVICE_NAME
environment variable/system property
2019-08-21 02:57:21,587 INFO  [org.fly.cor.int.lic.VersionPrinter] (main)
Flyway Community Edition 5.2.4 by Boxfuse
2019-08-21 02:57:21,628 INFO  [org.fly.cor.int.dat.DatabaseFactory] (main)
Database: jdbc:postgresql://localhost:5433/todoquery (PostgreSQL 11.4)
2019-08-21 02:57:21,634 WARN  [org.fly.cor.int.dat.bas.Database] (main)
Flyway upgrade recommended: PostgreSQL 11.4 is newer than this version of
Flyway and support has not been tested.
2019-08-21 02:57:21,672 INFO  [org.fly.cor.int.com.DbValidate] (main)
Successfully validated 2 migrations (execution time 00:00.016s)
2019-08-21 02:57:21,684 INFO  [org.fly.cor.int.com.DbMigrate] (main)
Current version of schema "public": 2
2019-08-21 02:57:21,685 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema
"public" is up to date. No migration necessary.
javax.persistence.PersistenceException: [PersistenceUnit: default] Unable
to build Hibernate SessionFactory
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
        at
io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
        at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
        at
io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
        at
io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
        at
io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:77)
        at
io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits27.deploy_0(HibernateOrmProcessor$startPersistenceUnits27.zig:70)
        at
io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits27.deploy(HibernateOrmProcessor$startPersistenceUnits27.zig:36)
        at
io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:211)
        at io.quarkus.runtime.Application.start(Application.java:84)
        at io.quarkus.runtime.Application.run(Application.java:196)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: org.hibernate.HibernateException: Unable to instantiate default
tuplizer [org.hibernate.tuple.component.DynamicMapComponentTuplizer]
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructTuplizer(ComponentTuplizerFactory.java:107)
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructDefaultTuplizer(ComponentTuplizerFactory.java:128)
        at
org.hibernate.tuple.component.ComponentMetamodel.<init>(ComponentMetamodel.java:77)
        at
org.hibernate.tuple.component.ComponentMetamodel.<init>(ComponentMetamodel.java:52)
        at org.hibernate.mapping.Component.getType(Component.java:227)
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
        at org.hibernate.mapping.RootClass.validate(RootClass.java:268)
        at
org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
        at
org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
        ... 12 more
Caused by: java.lang.NullPointerException
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructTuplizer(ComponentTuplizerFactory.java:104)
        ... 21 more
2019-08-21 02:57:21,716 INFO  [io.sma.rea.mes.ext.MediatorManager] (main)
Cancel subscriptions
Exception in thread "main" java.lang.RuntimeException: Failed to start
quarkus
        at
io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:247)
        at io.quarkus.runtime.Application.start(Application.java:84)
        at io.quarkus.runtime.Application.run(Application.java:196)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit:
default] Unable to build Hibernate SessionFactory
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
        at
io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
        at
javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
        at
io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
        at
io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
        at
io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:77)
        at
io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits27.deploy_0(HibernateOrmProcessor$startPersistenceUnits27.zig:70)
        at
io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits27.deploy(HibernateOrmProcessor$startPersistenceUnits27.zig:36)
        at
io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:211)
        ... 3 more
Caused by: org.hibernate.HibernateException: Unable to instantiate default
tuplizer [org.hibernate.tuple.component.DynamicMapComponentTuplizer]
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructTuplizer(ComponentTuplizerFactory.java:107)
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructDefaultTuplizer(ComponentTuplizerFactory.java:128)
        at
org.hibernate.tuple.component.ComponentMetamodel.<init>(ComponentMetamodel.java:77)
        at
org.hibernate.tuple.component.ComponentMetamodel.<init>(ComponentMetamodel.java:52)
        at org.hibernate.mapping.Component.getType(Component.java:227)
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
        at org.hibernate.mapping.RootClass.validate(RootClass.java:268)
        at
org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
        at
org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
        at
io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
        ... 12 more
Caused by: java.lang.NullPointerException
        at
org.hibernate.tuple.component.ComponentTuplizerFactory.constructTuplizer(ComponentTuplizerFactory.java:104)
        ... 21 more

My application is available here:

https://github.com/dcdh/eventstore-quarkus-sample-app/tree/master/todo-query-app

Before building: start containers by doing *docker rm $(docker ps -aq) &&
docker-compose up* in the same directory.

just build in native by changing env variable in *build_native.sh* next run
it and execute the app.

I will do a ticket tonight.

Regards,

Damien

Le mar. 20 août 2019 à 10:12, Guillaume Smet <notifications@github.com> a
écrit :

**Comment by dcdh** [comment]
Good news.
Envers fails at startup in native mode because some classes are missing after doing native compilation.

I have follow the `reflection-config.json` tutorial and this content fix this issue:

```json
[
  {
    "name" : "org.hibernate.tuple.component.DynamicMapComponentTuplizer",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  },
  {
    "name" : "org.hibernate.envers.DefaultRevisionEntity",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  },
  {
    "name" : "org.hibernate.persister.entity.SingleTableEntityPersister",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  },
  {
    "name" : "org.hibernate.tuple.entity.DynamicMapEntityTuplizer",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

Are there a way to include it in the extension ?

**Comment by machi1990** [comment]
@dcdh great news.
