### ISSUE TITLE
using PanacheQuery#project with multi-line string in Kotlin fails

### ISSUE THREAD

**Issue by bard-kristian** [quarkusio/quarkus#31210]
### Describe the bug

[This line](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/panache-hibernate-common/runtime/src/main/java/io/quarkus/panache/hibernate/common/runtime/PanacheJpaUtil.java#L70) checks if the query starts with `select ` (note the trailing space), but in Kotlin you normally use (I do at least) this type of string for queries
```
val hql = """
    select myStuff
    and do more hql stuff here
""".trimIndent()
```
which doesn't have the trailing space that's checked for unless you manually add one. Instead theres a \n after `select`. This in turns messes with the generated HQL when you use `io.quarkus.hibernate.orm.panache.kotlin.PanacheQuery#project` since it will insert its own select at the beginning if it's missing (if I've understood everything correctly).

EDIT: I thought these strings were a Kotlin feature, but it seems it's a Java feature ref https://docs.oracle.com/en/java/javase/15/text-blocks/index.html

### Expected behavior

That text blocks work with .project().

### Actual behavior

Using text blocks do not work .project() when generating the HQL for .project() since Quarkus looks for `select ` with the space to see if we supplied our own select.

### How to Reproduce?

See the reproducer.

### Quarkus version or git rev

Discovered in 2.16.0.Final, reproducer is 2.16.3.Final

### Additional information
[panache-project-reproducer.zip](https://github.com/quarkusio/quarkus/files/10818465/panache-project-reproducer.zip)

_No response_

**Comment by bard-kristian** [comment]
Kind of related, but [this](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L95) also prevents having a select within a select when projecting.

For example I want to get the total amount of children as a number, but also need the count of children that match some condition:
```
select
    pe.id,
    count(ce.*) as matchingCount,
    (select count(*) from ChildEntity cee where cee.parentId = pe.id) as totalCount
from
    ParentEntity pe
    join pe.child ce
where
    ce.prop1 = 'SomeValue'
group by pe.id
```

Next week I should have time to make reproducers for both of these, and I'll make a seperate issue for this.

**Comment by bard-kristian** [comment]
I have added a reproducer to the issue.

**Comment by geoand** [comment]
Thanks for the analysis.

Would you be willing to contribute a fix?

**Comment by bard-kristian** [comment]
It will be my first time contributing to open source, but I supposed I could give it a try.

**Comment by geoand** [comment]
Excellent 👍.

Let us know if you need any help
