### ISSUE TITLE
[Extension Proposal] PrimeFaces

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#31219]
### Description

I am the owner of [Quarkus OmniFaces](https://github.com/quarkiverse/quarkus-omnifaces) and we realized we have been maintaining too much code in MyFaces Extensions to support PrimeFaces so we need its own extension.

### Repository name

quarkus-primefaces

### Short description

Ultimate Component Suite for JavaServer Faces

### Repository Homepage URL

https://github.com/primefaces/primefaces

### Repository Topics

- quarkus-extension
- primefaces
- jsf
- faces
- myfaces
- web

### Team Members

- @melloware
- @tandraschko 
- @jepsar

**Comment by gastaldi** [comment]
The repository is now available in https://github.com/quarkiverse/quarkus-primefaces.

**Comment by melloware** [comment]
You guys rock!
