### ISSUE TITLE
[Extension Proposal] PrimeFaces Extensions

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#31220]
### Description

I am the owner of [Quarkus OmniFaces](https://github.com/quarkiverse/quarkus-omnifaces) and we realized we have been maintaining too much code in MyFaces Extensions to support PrimeFaces Extensions so we need its own extension.

### Repository name

quarkus-primefaces-extensions

### Short description

Components and utilities for PrimeFaces

### Repository Homepage URL

https://github.com/primefaces-extensions/primefaces-extensions

### Repository Topics

- quarkus-extension
- primefaces
- jsf
- faces
- myfaces
- web
...

### Team Members

- @melloware
- @tandraschko 
- @jepsar

**Comment by gastaldi** [comment]
Can this live in the same repository as proposed in #31219 ?

**Comment by melloware** [comment]
Can I produce two artifacts from the same extension.  As we need a Primefaces one and a Primefaces Extension one since they are separate libs?

**Comment by gastaldi** [comment]
Of course! See https://github.com/quarkiverse/quarkus-pact for a multimodule example

**Comment by melloware** [comment]
OK then 1 repo just called `quarkus-primefaces` should do!
