### ISSUE TITLE
Empty array in yaml should be valid

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#31229]
### Describe the bug

I should be able to use the yaml representation of an empty array in a config for a required property.

### Expected behavior

Successfully loads empty list

### Actual behavior

```
ConfigurationException: Failed to load config value of type java.util.List<java.lang.String> for: app.my-list
```

### How to Reproduce?

```java
@ConfigProperty(name = "app.my-list")
List<String> myList;
```

```yaml
app:
  my-list: []
```

### Quarkus version or git rev

Quarkus 1.16.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by mikethecalamity** [comment]
@radcortez

**Comment by radcortez** [comment]
The config conversion rules for empty values override the yaml rules:

https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc#config-value-conversion-rules

An empty array must throw a `NoSuchElementException`.

**Comment by gsmet** [comment]
@radcortez is it a case where using Optional is necessary?

**Comment by radcortez** [comment]
Yes, it could be represented as an `Optional`. My bad, I could have mentioned it.

The link I've posted has a comprehensive list of the rules when an empty value is found. Each source may represent empty values differently, so the idea of the rules is to make them consistent.

**Comment by mikethecalamity** [comment]
It just seems weird to me because empty and null are different cases. For example, requiring that a configuration representing a list must exist, but it is allowed to be an empty list. That's a different case than the configuration not existing at all, which I do agree would necessitate the need for an `Optional`.

**Comment by radcortez** [comment]
While in YAML is easy to represent an empty list or a null list, how do you do it with property format?

The problem here is that the `ConfigSource` API is a `String` to `String` lookup, so we don't have a very good way to distinguish between empties or nulls (hence the rules in the specification).
