### ISSUE TITLE
ManyToMany Hibernate w/ Panache insert two entities within the same persistence context

### ISSUE THREAD

**Issue by glmanhtu** [quarkusio/quarkus#31239]
### Describe the bug

Hello, 

I have created an Rest API application that performs creating an Entity and save it into a database. The schema of the database is including 3 tables:

chat_user (user_id, full_name, ...)
chat_group (group_id, group_name, ...)
chat_join_record (group_id, user_id, date, ...)

By using Quarkus Hibernate w/ Panache, I was able to create new users and save it into database. However, when I was trying to create a group and associate these users into the group, I have faced an exception of "Illegal attempt to associate a ManagedEntity with two open persistence contexts..."

### Entities definitions:

```java
@Entity
@Table(name = "chat_user")
public class ChatUser {
    @Id
    @Column(name = "user_id", length = 127)
    private String userId;

    @OneToMany(mappedBy = "chatUser")
    private Set<ChatJoinRecord> chatJoinRecords;
    ....
}

@Entity
@Table(name = "chat_group")
public class ChatGroup {
    @Id
    @Column(name = "group_id", nullable = false, length = 127)
    private String groupId;

    @OneToMany(mappedBy = "chatGroup", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<ChatJoinRecord> chatJoinRecords = new HashSet<>();
    ....

    public void addMember(ChatUser chatUser, GroupRole role) {
        var chatJoinRecord = new ChatJoinRecord(this, chatUser, role);
        chatUser.getChatJoinRecords().add(chatJoinRecord);
        chatJoinRecords.add(chatJoinRecord);
    }
}

@Entity
@Table(name = "chat_join_record")
public class ChatJoinRecord {
    @EmbeddedId
    private ChatUserGroupKey userGroupKey;

    @ManyToOne
    @MapsId("groupId")
    @JoinColumn(name = "group_id")
    private ChatGroup chatGroup;

    @ManyToOne
    @MapsId("userId")
    @JoinColumn(name = "user_id")
    private ChatUser chatUser;
    ....
}


@Embeddable
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ChatUserGroupKey implements Serializable {

    @Column(name = "group_id", length = 127)
    private String groupId;

    @Column(name = "user_id", length = 127)
    private String userId;
}
```

### Repository definitions:

```java
@ApplicationScoped
public class ChatGroupRepository implements PanacheRepositoryBase<ChatGroup, String> {
}
```

### Service definitions:

```java
@ApplicationScoped
@AllArgsConstructor
public class ChatGroupService {
    private final ChatGroupRepository chatGroupRepository;

    @Transactional
    public ChatGroup createChatGroup(ChatGroup chatGroup) {
        chatGroup.setGroupId(generateGroupId(chatGroup));
        chatGroupRepository.persist(chatGroup);
        return chatGroup;
    }
}
```

### Logic call:

```java
var chatUsers = new ArrayList<ChatUser>();
for (String participant : listUserIds) {
    var chatUser = chatUserService.getUser(participant);
    chatUsers.add(chatUser);
}

var chatGroup = new ChatGroup();
for (var chatUser : chatUsers) {
    var role = chatUser.getUserId().equals(principal.getName()) ? GroupRole.ADMIN : GroupRole.MEMBER;
    chatGroup.addMember(chatUser, role);
}

chatGroupService.createChatGroup(chatGroup);             // Exception occurred here !

```

Could you please help me to check what is the root cause of the problem ?

### Expected behavior

The Panache repository should be able to save the record to database

### Actual behavior

javax.persistence.PersistenceException: org.hibernate.HibernateException: Illegal attempt to associate a ManagedEntity with two open persistence contexts. EntityEntry[com.mtvu.usermanagementservice.model.ChatUser#alice](MANAGED)

### How to Reproduce?

```bash
git clone https://github.com/chat-socket/user-management-service.git 
cd user-management-service
git checkout quarkus-jpa-issue
./gradlew test --tests com.mtvu.usermanagementservice.api.GroupManagementControllerTest.whenCreateGroupWithValidUsersThenAcceptTheRequest
```

### Output of `uname -a` or `ver`

Darwin Manhs-Mac-mini.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 22.3.1

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.5.1 ------------------------------------------------------------  Build time:   2022-08-05 21:17:56 UTC Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918  Kotlin:       1.6.21 Groovy:       3.0.10 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.6 (GraalVM Community 17.0.6+10-jvmci-22.3-b13) OS:           Mac OS X 13.2.1 x86_64

**Comment by yrodiere** [comment]
Hello,

Here, you call `chatUserService`, which starts a transaction, and thus a Hibernate `Session` (which, in the weird JPA linguo, is called a "persistence context"), to retrieve the user from the database:

```
     var chatUser = chatUserService.getUser(participant);
```

And down here, you call `chatUserService`, which starts **another** transaction, and thus **another** Hibernate `Session` :

```
chatGroupService.createChatGroup(chatGroup);             // Exception occurred here !
```

That second call will probably manipulate entities from both sessions and try to mix them. That's not allowed.

There are ways around this (`merge` etc.), but I'd recommend against that. Your problem here is that you're starting multiple transactions. You should not.

Try wrapping your "Logic call" code in a single transaction, which will support the whole operation with a single session:

Either annotate the method that code is in with `@Transactional`:

```
@Transactional
public void myLogicCall() {
    var chatUsers = new ArrayList<ChatUser>();
    for (String participant : listUserIds) {
        var chatUser = chatUserService.getUser(participant);
        chatUsers.add(chatUser);
    }
    
    var chatGroup = new ChatGroup();
    for (var chatUser : chatUsers) {
        var role = chatUser.getUserId().equals(principal.getName()) ? GroupRole.ADMIN : GroupRole.MEMBER;
        chatGroup.addMember(chatUser, role);
    }
    
    chatGroupService.createChatGroup(chatGroup);
}
```


... or use `QuarkusTransaction`:

```
QuarkusTransaction.joiningExisting().run(() -> {
    var chatUsers = new ArrayList<ChatUser>();
    for (String participant : listUserIds) {
        var chatUser = chatUserService.getUser(participant);
        chatUsers.add(chatUser);
    }
    
    var chatGroup = new ChatGroup();
    for (var chatUser : chatUsers) {
        var role = chatUser.getUserId().equals(principal.getName()) ? GroupRole.ADMIN : GroupRole.MEMBER;
        chatGroup.addMember(chatUser, role);
    }
    
    chatGroupService.createChatGroup(chatGroup);
});
```

I will close this issue as this does not look like a bug. Feel free to continue discussing your problem, though; I'll answer and may reopen if it turns out to actually be a bug.
