### ISSUE TITLE
Empty array of values in WebTargetImpl.queryParam method is added to the final URI as an `&`

### ISSUE THREAD

**Issue by vladtf** [quarkusio/quarkus#31249]
When the `Object... values` is an empty array at  https://github.com/quarkusio/quarkus/blob/7abe8ae58dcfa24e9312d0cef668f38ec78d8802/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/WebTargetImpl.java#L240 it is consider to be valid value and in the final URI appears a trailing & because of that empty array. This leads to the scenarios when in the final URI appears '&&' which is not accepted by some servers.

**Comment by vladtf** [comment]
My expectation is that an empty array will result in entering the true branch of that if and in the URI this query parameter won't be anyhow reflected.

**Comment by geoand** [comment]
Thanks for reporting.

As you seem to have already analyzed the code, would you like to provide a Pull Request with the fix you have in mind?

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/31462 should fix this.
