### ISSUE TITLE
Rest client call times-out when called within a mutiny verticle

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#31244]
### Describe the bug

I have registered a mutiny verticle that listens to messages on the event bus and uses a rest client to retrieve some information. The execution fails because the client request times out.
The same execution works fine if I define a vertx verticle.

### Expected behavior

Rest request within the mutiny verticle should work as it works within the vertx verticle

### Actual behavior

request times out

### How to Reproduce?

run [this](https://github.com/iompo/deferred-execution) reproducer tests 

### Output of `java -version`

openjdk version "11.0.16.1"

### Quarkus version or git rev

2.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.5.1

**Comment by cescoffier** [comment]
I've tried with 999-SNAPSHOT and I can't reproduce it. 

Several notes about the reproducer:

- you should use the Mutiny API of the event bus - that will simplify the code a lot
- avoid creating new ObjectMapper, use `@Inject ObjectMapper mapper` - mappers are pretty heavy
- `StringGenerator` could be in the application scopes - any reason making it dependent? IT does not have a state.
- `StringGeneratorJob` is deployed as a worker verticle? Why, all your API is reactive and your code non-blocking. Just avoid the await in `StringGeneratorJob` by subscribing to the returned Uni.

**Comment by cescoffier** [comment]
Yes, 999-SNAPSHOT is the development version (Quarkus 3.x).
