### ISSUE TITLE
[ORM6] Make sure we document how to use the ORM 5 model with ORM 6

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31256]
From what I can see, several behaviors have changed as to the model that is generated by Hibernate ORM (table-specific sequences for instance) and I'm not sure how things go if you upgrade to ORM 6 without changing your model and start your application.

This needs to be clarified and documented, especially if there are options that can easily make Hibernate ORM 6 compatible with the ORM 5-generated schema.

Maybe it's a non-issue and all goes well but let's make sure of it.

/cc @Sanne @beikov

**Comment by Sanne** [comment]
The schema expectations are most likely going to be different - at least by default; defaults can be overriden but the OOB experience won't be straight forward for sure.

If you're suggesting the migration guide needs further improvements, I agree; and we should point Quarkus users to the Hibernate migration guides.

Or did you have something more Quarkus specific in mind?

**Comment by gsmet** [comment]
Well, my problem is that we are providing an easy migration path in Quarkus but for applications using Hibernate ORM, this won't work because the schema won't fit Hibernate ORM 6 new expectations, probably leading to all sort of errors when starting the application.

I have no idea if the Hibernate ORM migration guide provides a way to set properties to get back to some working state or if we are expecting the users to upgrade their schema following some instructions (but I would expect it to be very tedious, typically just the sequence per table change might require some scripting to get it fixed).

That would make our upgrade experience to Quarkus 3 significantly worse.

If there are properties improving the path of migration, we might want to add them automatically in the migration script.

If there are recipes on how to upgrade the schema in the most common cases and for the most common databases, it might be a good idea to provide them.

Note that I haven't had a look at the migration guide, I'm asking questions to clarify the situation.

/cc @maxandersen for your awareness

**Comment by beikov** [comment]
>If there are properties improving the path of migration, we might want to add them automatically in the migration script.

For the sequence per table part, there is a config option that can restore the old behavior, but we thought that real applications wouldn't use a single sequence for all tables anyway, so changing the default wouldn't affect real applications.

Either way, I have some todos for adding sections to the migration guide. Would be good if you point people to that.

* https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html
* https://docs.jboss.org/hibernate/orm/6.1/migration-guide/migration-guide.html
* https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html

**Comment by gsmet** [comment]
Please, as stated before, we are working on that already, let's not have a different discussion about this.

**Comment by gsmet** [comment]
@yrodiere I think we are in good enough shape that we can close this one, right?
