### ISSUE TITLE
Upgrade tool - Add option to OpenRewrite to consider additional source files (md/adoc and codestarts files)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31255]
As discussed with @ia3andy , we need to define the plain text masks to make OpenRewrite consider additional source files like the md/adoc or the codestarts files.

Pointers:
- For Maven: https://github.com/quarkusio/jbang-catalog/blob/main/q3upgrade.java#L101
- For Gradle: https://github.com/quarkusio/jbang-catalog/blob/main/openrewriteinit.gradle#L28-L33

**Comment by ia3andy** [comment]
This is where it should be update: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/UpdateProjectCommandHandler.java#L81
