### ISSUE TITLE
Calling response.bufferEntity() in ResponseExceptionMapper throws BlockingNotAllowedException

### ISSUE THREAD

**Issue by kekbur** [quarkusio/quarkus#31265]
### Describe the bug

When a RESTEasy Reactive client API interface has a method that returns an `InputStream`, calling `response.bufferEntity()` in a `ResponseExceptionMapper` throws a `BlockingNotAllowedException`. If the API client method has a different return type, such as `String`, calling `response.bufferEntity()` succeeds.

If this is intended behavior the documentation at https://quarkus.io/guides/rest-client-reactive should be updated with instructions on how to deal with this situation.

Strangely, annotating the API client method with `@Blocking` made no difference.

Moreover, the behavior is dependent on the response body being empty or not. Here is the list of combinations I've tested:

| RESTEasy client variant  | Method return type | Response body is empty | bufferEntity() throws |
| ------- | ------- | ------- | ------- |
| reactive  | InputStream | no | 🟥yes |
| reactive  | InputStream | yes | 🟩no |
| reactive  | String | no | 🟩no |
| reactive  | String | yes | 🟩no |
| classic  | InputStream | no | 🟩no |
| classic  | InputStream | yes | 🟩no |
| classic  | String | no | 🟩no |
| classic  | String | yes | 🟩no |

### Expected behavior

Calling response.bufferEntity() should be possible in all cases, or the documentation should be updated to point out the special cases.

### Actual behavior

See above.

### How to Reproduce?

Reproducer: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/10771415/code-with-quarkus.zip)
1. Run `mvn test`. Observe RestApiTest#testGetStream failing and RestApiTest#testGetText succeeding.

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0-22000

### Output of `java -version`

java version "17.0.3.1" 2022-04-22 LTS Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by Sgitario** [comment]
Thanks for reporting! This is duplicated by https://github.com/quarkusio/quarkus/issues/30312.
