### ISSUE TITLE
resteasy-reactive: MessageBodyWriter/MessageBodyReader Priority not properly handled

### ISSUE THREAD

**Issue by forsti0506** [quarkusio/quarkus#31271]
### Describe the bug

Hello,

I believe that the prioritization of MessageBodyWriters/MessageBodyReaders is incorrect. Typically, JAX-RS providers with a lower priority are handled before those with a higher priority. Have I missed any other declarations related to this use case?

I suggest switching the comparison to achieve the desired ordering. What is your opinion?

Here's the code for the comparison:
`
https://github.com/quarkusio/quarkus/blob/e4d6fbf13a62240a63af6b83ec3f835f3e0fb51e/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/model/ResourceWriter.java#L151

### How to Reproduce?

1. Include 2 MessageBodyWriters for Strings.
2. Assign a priority of 10 to one MessageBodyWriter and a priority of 100 to the other.
3. Observe that the MessageBodyWriter with a priority of 100 is invoked before the one with a priority of 10.

### Quarkus version or git rev

3.0

**Comment by geoand** [comment]
That is only partly true.

The JAX-RS spec says that for the request chain the lower priority providers are considered first, while for the response chain the inverse is true.

It certainly is confusing, but it is what it is 🤷
