### ISSUE TITLE
Jsonb FieldAccessStrategy prevent Hibernate dirty fields tracking

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#3127]
**Describe the bug**
Using Jsonb FieldAccessStategy it seems that Hibernate is unable to track dirty fields

**Expected behavior**
Merge should understand that the detached entity is changed and update accordingly

**Actual behavior**
Merge does nothing

**To Reproduce**
1. Download reproducer project
2. run "mvn clean compile quarkus:dev"
3. launch "execute-testcase.sh" and see that merge is not done
4. comment  JsonbContextResolver line 26 to remove FieldAccessStrategy
5. launch again 'execute-testcase.sh' and now merge will be done and the last curl will return a correct 409 Status Code

**Configuration**
```properties
quarkus.datasource.url: jdbc:h2:mem:testdb
quarkus.datasource.driver: org.h2.Driver
quarkus.datasource.username: sa
quarkus.datasource.password:

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql: true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin WMICTLM1P 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
W
 - Quarkus version or git rev: 0.18.0

**Comment by masini** [comment]
[test-case.zip](https://github.com/quarkusio/quarkus/files/3364695/test-case.zip)

**Comment by gsmet** [comment]
@masini so this one is expected: if you force JSON-B to use fields, then the dirty tracking code is not triggered as this code is in the setters.

**Comment by RohanHart** [comment]
https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-accessors states that getters/setters are not required. I've not found any documentation indicating that they are required to be used for bytecode-enhanced dirty checking to work.
