### ISSUE TITLE
[Extension Proposal]  angus mail

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#31285]
### Description

Integration of Eclipse Angus mail to access mail protocols like IMAP and POP3

### Repository name

quarkus-angus-mail

### Short description

Integration of Eclipse Angus mail to access mail protocols like IMAP and POP3

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-angus-mail/dev/

### Repository Topics

- quarkus-extension
- jakarta
- imap
...

### Team Members

- ppalaga
- maxandersen

### Additional context

as discussed and already created repo but no reason we don't follow our own rules :)

**Comment by maxandersen** [comment]
angus-mail have a set of providers...should we have extension per provider or group them more coarse grained, i.e. angus-imap be gimap+imap ?

angus-mail  gimap  imap  jakarta.mail  mbox  pop3  smtp?

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkiverse/quarkiverse-devops/pull/122

**Comment by gastaldi** [comment]
Closing as the repository was created already. Please file discussions about it in the repository's issue tracker
