### ISSUE TITLE
[Extension Proposal] jasperreports

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#31288]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

A few years back while migrating from widfly to quarkus, I had issues using jasperreports.
This was caused by some strict depency ordering I had to follow, so that the XML Providers all loaded successfully. Or something like that.

This is intended as quarkiverse extension.

In this extension, I want to
* first, encapsulate all the tricks I had to do for jasper, so that it also works correctly with normal jaxb.
* Document how to setup a docker image which also allows template printing (e.g. installing fonts)
* Ensure quarkus 3 compatibility.
I did a quick case study at work of pain points for a migration of my product to q3, and jasperreports stood out with some javax depencies - at least in older versions.
* maybe try going native, If there is interest for that.

### Repository name

quarkus-jasperreports

### Short description

Print reports created using JasperReports using the java api

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- jasperreports
...

### Team Members

- Postremus

**Comment by gastaldi** [comment]
Nice! This is definitely useful 👍🏻

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-jasperreports
