### ISSUE TITLE
Native Build on Windows has incorrect resource slashes

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#31307]
### Describe the bug

original conversation: https://github.com/quarkusio/quarkus/issues/13275

When building a Native image on Windows the `quarkus-native-resources.txt` has mixed slashes which then causes the resources not to be found.

**Windows (Incorrect):**
`META-INF/resources/resources\showcase\images\layouts\manhattan.jpg`

**Linux (Correct):**
`META-INF/resources/resources/showcase/images/layouts/manhattan.jpg`

### Expected behavior

No matter the slashes the resource should be added .

### Actual behavior

Resource gets a "FileNotFoundException" at runtime.

### How to Reproduce?

1. On Windows `git clone https://github.com/quarkiverse/quarkus-primefaces`
2. Run `mvn -B install -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip`

You will see the slashes are wrong.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1265]

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### GraalVM version (if different from Java)

Mandrel 22.3

### Quarkus version or git rev

2.16.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

**Comment by zakkak** [comment]
Note that https://github.com/quarkusio/quarkus/pull/31185 is going to remove the use of `quarkus-native-resources.txt`. But the issue will probably remain as the paths are added to resource-config.json instead.

**Comment by Sanne** [comment]
Let's keep in mind that these are *resource paths* - not filesystem paths. Does it actually break something on Windows?

**Comment by melloware** [comment]
Let me double check I was getting "java.io.FileNotFoundException" when building in Windows but not in Linux so maybe the issue is somewhere else I just saw the slashes as incorrect here and thought it looks weird.

**Comment by melloware** [comment]
I originally ran into this where my Integration Tests won't run on Windows but run fine on Linux: https://github.com/quarkusio/quarkus/issues/13275#issuecomment-1435737892

**Comment by melloware** [comment]
I have confirmed it does not work on Windows I can see the files are in the proper path in the executable but is getting FileNotFoundExceptions.

**Comment by Karm** [comment]
I have it reproduced on my Win10 system using Podman for Windows:
```
[INFO] Running io.quarkiverse.primefaces.it.PrimeFacesResourceIT
Executing "C:\tmp\quarkus-primefaces\quarkus-primefaces\integration-tests\target/quarkus-primefaces-integration-tests-2.12.1-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=C:\tmp\quarkus-primefaces\quarkus-primefaces\integration-tests\target\quarkus.log -Dquarkus.log.file.enable=true"
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 11.219 s <<< FAILURE! - in io.quarkiverse.primefaces.it.PrimeFacesResourceIT
[ERROR] shouldAllowTemplate  Time elapsed: 0.062 s  <<< ERROR!
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\tmp\quarkus-primefaces\quarkus-primefaces\integration-tests\target/quarkus-primefaces-integration-tests-2.12.1-SNAPSHOT-runner": CreateProcess error=193, %1 is not a valid Win32 application
Caused by: java.io.IOException: Cannot run program "C:\tmp\quarkus-primefaces\quarkus-primefaces\integration-tests\target/quarkus-primefaces-integration-tests-2.12.1-SNAPSHOT-runner": CreateProcess error=193, %1 is not a valid Win32 application
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   PrimeFacesResourceIT.shouldAllowTemplate » Runtime java.io.IOException: Cannot...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ quarkus-primefaces-integration-tests ---
```

**Comment by Karm** [comment]
Well, this is a misunderstanding. The application is in fact an elf Linux amd64 binary, because it was built in the Linux builder container.

The fix for the test is to run it in a container too....

**Comment by Karm** [comment]
I'll refactor the PrimeFaces test run with jib extension and see how it goes.

**Comment by Karm** [comment]
I almost got it, currently hinging on Docker vs. JVM process locking the log file :) 
```
Caused by: java.nio.file.FileSystemException: target\quarkus.log: The process cannot access the file because it is being used by another process
```
I'll open a PR to quarkus-prime faces when I get it unstuck.

**Comment by melloware** [comment]
Thank you for working on this!

**Comment by Karm** [comment]
@melloware Here is a PR to Quarkus PrimeFaces: https://github.com/quarkiverse/quarkus-primefaces/pull/12
PR to Quarkus is pending, I'd like to add a specific test first...     

I suggest migrating to Jakarta and Quarkus 3 too. Otherwise the Primefaces integration would be stuck with Q 2.16.x...

**Comment by melloware** [comment]
Yeah My plan was to get a JSF app fully native with PF on the 2.x branch.  Then migrate to the 3.x Quarkus branch!  Thanks for all your hard work on this!
