### ISSUE TITLE
Quarkus 2.15.3 -> 2.16.0 fails for @ServerEndpoint("/data") @ApplicationScoped

### ISSUE THREAD

**Issue by DaveO-Home** [quarkusio/quarkus#31310]
### Describe the bug

The @OnOpen methed does not execute

Searched the release notes for 2.16.0/2.16.3 and there is nothing about @ServerEndpoint (also fails in 2.16.3)

### Expected behavior

The @OnOpen method to run on the websocket open

### Actual behavior

No errors and the method does to execute

### Output of `uname -a` or `ver`

Linux mini-pc 6.1.11-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  9 19:20:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10) OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing) and OpenJDK Runtime Environment (Red_Hat-19.0.2.0.7-1.rolling.fc37) (build 19.0.2+7) OpenJDK 64-Bit Server VM (Red_Hat-19.0.2.0.7-1.rolling.fc37) (build 19.0.2+7, mixed mode, sharing)

### Quarkus version or git rev

2.15.3(works) 2.16.0 - 2.16.3(fails)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.6 ------------------------------------------------------------  Build time:   2022-11-25 13:35:10 UTC Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8  Kotlin:       1.7.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          19.0.2 (Red Hat, Inc. 19.0.2+7) OS:           Linux 6.1.11-200.fc37.x86_64 amd64

**Comment by geoand** [comment]
Any chance you can get us a sample application that work in `2.15` and not in `2.16`?

**Comment by DaveO-Home** [comment]
@geoand - I do have a project on github, https://github.com/DaveO-Home/dodex-quarkus. It may be more than what you want to deal with but here's a quick start:
1. in .../dodex-quarkus/src/main/resources/META-INF/resources execute `npm install`
2. in .../dodex-quarkus execute `gradlew quarkusDev
3. in browser run "localhost:8089/dodex
4. Ctrl double-click either a dial or the bottom card
5. a login should popup - enter a handle
6. the chat box should say "connected" - it works
With v16 the chat box is blank - see the websocket error in the console

**Comment by DaveO-Home** [comment]
@geoand - anyway with 2.16.4, this is a cors config problem. For Dev I added;
```
quarkus.http.cors=true
%dev.quarkus.http.cors.origins=/.*/
```

**Comment by geoand** [comment]
Thanks for the update
