### ISSUE TITLE
Cannot use JsonbSerializer with Hibernate ORM

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#3131]
**Describe the bug**
A custom JsonbSerializer for a collection returned by Hibernate (can be an ArrayList or a *Bag) launch a JsonbException complaining that there is a recursive serialization.

**Expected behavior**
Should understand that List<MyPojo>, ArrayList<MyPojo> and PersistentBag<MyPojo> are the same

**Actual behavior**
Don't understand the difference

**To Reproduce**
1. Use a custom serializer for an Entity Pojo which implements JsonbSerializer<List<MyPojo>>
2. Serialize something returned by a query or collection
3. JsonbException is launched

**Environment (please complete the following information):**

    Output of uname -a or ver: Darwin WMICTLM1P 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
    Output of java -version: OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
    OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
    W
    Quarkus version or git rev: 0.18.0

**Comment by geoand** [comment]
I am assuming the problem only manifests during in native mode, correct?

**Comment by masini** [comment]
Hi Georgios, I haven't tried in native mode.

I reproduced with quarkus:dev and @QuarcusTest.

Thanks for your interest.

**Comment by geoand** [comment]
Hi, thanks for the extra info!

**Comment by geoand** [comment]
@masini could you please provide some code snippets of how you are recreating the problem? Because reading the issue some things just don't add up in my mind.

Thanks

**Comment by masini** [comment]
Hi Georgios, I retrieve a "RootPojo" using the EntityManager, which has a lazy collection:

public class RootPojo {
...
...
...
@OneToMany
@JsonbCustomSerializer(MySerializer.class)
List<ReferencedPojo> myCollection
}

when RESTEasy try to send the JSON from the JAX-RS service I got the Exception because Jsonb is unable to understand that the PersistentBag returned by the ORM is the same thing.

In case I'm again not so clear I'll create a test case.

Let me know.

**Comment by geoand** [comment]
Thanks for the code, the use case is now clear. Would you also be able to add the exception that you are seeing from JsonB?

**Comment by masini** [comment]
The Exception is thrown by:

`org.eclipse.yasson.internal.serializer.UserSerializerSerializer`

at line 57.

Thanks

**Comment by geoand** [comment]
Could you perhaps provide a larger part of the stacktrace? Thank you

**Comment by gsmet** [comment]
@masini if this is still an issue, can you provide a proper reproducer? Looks like a lot of unnecessary backs and forths.

Thanks!

**Comment by famod** [comment]
I'll close this one due to lack of feedback.

@masini Please feel free to reopen this issue if you are still seeing this problem. If you do, please provide a reproducer. Thanks!

**Comment by masini** [comment]
Sorry guys, I switched to Jackson, so I completely forget about JSONB.

I'll take some time to check if now is solved in the new release of Quarkus.
