### ISSUE TITLE
Quarkus#blockingExit is being called regularly from the main thread

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#31317]
### Describe the bug

When running the full build, the following message is logged at least 236 times:

> 'Quarkus#blockingExit' was called on the main thread. This will result in deadlocking the application!

The number 236 is the number of matches for grepping the error logs in the builds - and this was just one of the CI actions.

### Expected behavior

We shouldn't risk deadlocking.  If the message is misleading, then we shouldn't log it.

### How to Reproduce?

Build Quarkus, look into the logs.

### Quarkus version or git rev

main

**Comment by geoand** [comment]
Do we have any sample tests that result in this?

**Comment by Sanne** [comment]
> Do we have any sample tests that result in this?

Any log from CI running integration tests should contain >200 of these

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/31333 takes care of the problem
