### ISSUE TITLE
If a REST client call fails, the status code is forwarded to the client

### ISSUE THREAD

**Issue by lorenzobenvenuti** [quarkusio/quarkus#31326]
### Describe the bug

Hi,

if a REST calls fails while serving a request, the application forwards the status code to the client (and nothing is logged on the server). Since the underlying error is caused by an unhandled exception on the server, I was expecting a 500. 

It looks like the same issue was addressed in [this PR](https://github.com/quarkusio/quarkus/pull/19630), I'm wondering if there was a regression.

Thanks,

lorenzo

### Expected behavior

The server returns a 500

### Actual behavior

The server returns the status code of the response that caused the REST call to fail.

### How to Reproduce?

`GreetingResourceTest#helloEndpointReturnsA500WhenTheRestClientCallFails` test in https://github.com/lorenzobenvenuti/rest-client-exception-bug

### Quarkus version or git rev

2.16.3

**Comment by geoand** [comment]
Actually, this has been fixed in the Reactive REST Client.

If you substitute `quarkus-rest-client-jackson` with `quarkus-rest-client-reactive-jackson`, everything works as expected

**Comment by lorenzobenvenuti** [comment]
TYVM!

**Comment by geoand** [comment]
🙏
