### ISSUE TITLE
Using custom config source seems to be not working

### ISSUE THREAD

**Issue by nyko29** [quarkusio/quarkus#31327]
### Describe the bug

I have a maven multi module project using quarkus (I am currently migrating from wildfly to quarkus, so the problem described here is not present with wildfly). The architecture can be simplified like this:

**module1**  -> configuration file such as application.properties
---src
 ------main 
 ---------resources
 ------------ application.properties
 ------------ application-devlocal.properties

**module2**   -> entities + MyCustomConfigSource

---src
------main
---------java
------------MyEntity1.java
------------MyCustomConfigSource.java
---------resources
------------META-INF
---------------services
------------------org.eclipse.microprofile.config.spi.ConfigSource

**module3**  -> first quarkus module
**module4**   -> second quarkus module

The goal of my custom config source is to get properties from a database table and if the property is not in the database then take it from application.properties. But when I launch the quarkus module4 in dev mode, it seems that the config source is not registered. As I have the following error:

`The config property MyPropertyFromDB is required but it could not be found in any config source.
`

The application is able to read properties from application.properties.Moreover if I inject my MyCustomConfigSource in another bean, I am able to see all properties stored in by database (by calling the method getProperties of the config source). So it is not a connection issue.

Here is the content of my custom config source MyCustomConfigSource.

`
@ApplicationScope
@Transactional
public class MyCustomConfigSource implements ConfigSource{

    @Inject
    private EntityManager entityManager;
    private Config config;

    @Override
    public int getOrdinal()
    { 
        return 500;
    }

    @Override
    public Set<String> getPropertyNames() {
       //...
    }

    @Override
    public Map<String, String> getProperties() {
        //...
    }

    @Override
    public String getValue(String key) {
        //...
    }

    @Override
    public String getName() {
        //...
    }

}
`
Moreover, during my tests, I see that if I add the annotation @io.quarkus.runtime.Startup then I am able to access the properties store in my database but quarkus is not able to access custom properties from application.properties anymore.

### Expected behavior

Be able to load properties from application.properties and from database at the same time as it was the case with wildfly.

### Actual behavior

It seems that the config source is not registered. And thus when I try to inject the property with the following code

`
@ConfigProperty(name="MyPropertyFromDB")
Provider<String> myVar
`
I got the exception

`The config property MyPropertyFromDB is required but it could not be found in any config source`

### Output of `uname -a` or `ver`

Ubuntu 22

### Output of `java -version`

openjdk version "11.0.16"

### Quarkus version or git rev

3.0.0.Alpha4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache maven 3.8.5

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Ideally, I would like to see an actual code reproducer if you can send me one.

Looking only at the pasted code, a ´ConfigSource´ is not a CDI Bean, and cannot be injected (at least in Quarkus). I don't know if Wildfly has some other mechanism to allow this. In Quarkus, the `ConfigSource` instance is obtained via the ServiceLoader mechanism. If you inject your source in another bean, yes it will work because CDI will create its own instance but is not part of the `Config`.

We already have sources to retrieve things from the database. Please check https://github.com/quarkiverse/quarkus-config-extensions

**Comment by nyko29** [comment]
I try the extension from the quarkivers and it works ! Thanks. I don't understand why it doesn't work without it but it doesn't matter.

For anyone having the same problem, be sure to get a version of the extension after the commit [#121](https://github.com/quarkiverse/quarkus-config-extensions/pull/121). Indeed I spend few hours try to understand why it didn't work with the extension. It was just because I didn't have this fix.

**Comment by nyko29** [comment]
See previous comment.

**Comment by radcortez** [comment]
Great. Thanks!
