### ISSUE TITLE
How to add application metrics in /metrics path

### ISSUE THREAD

**Issue by CarlosPanarello** [quarkusio/quarkus#3135]
Is there any configuration to add all application metrics in same the metrics path?

**Comment by kenfinnigan** [comment]
For application metrics to appear in /metrics for an application there needs to be metrics created with the MP Metrics annotations.

See https://quarkus.io/guides/metrics-guide for some example usage

**Comment by CarlosPanarello** [comment]
In the examples, that annotations used are showing only in metrics/application path. In metrics path showed only metrics from server. My doubt is about how to change the default path "metrics/application" for metrics used with annotations.

**Comment by kenfinnigan** [comment]
Can you provide a reproducer, as it might be a bug.

I know that once you've defined application metrics they won't show up in /metrics until you've actually received requests that use the metrics.

If that's not the problem it's likely a bug

**Comment by CarlosPanarello** [comment]
Sorry, my mistake. I found my metrics in /metrics, it is because they only create a metric after used.

**Comment by kenfinnigan** [comment]
No problem, glad it's sorted out
