### ISSUE TITLE
Kubernates extension doesn't propagate Datasource environment variables

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#31352]
### Describe the bug

Datasource environment variables seems not propagated automatically in the kubernate container and are not honored at runtime

QUARKUS_DATASOURCE_JDBC_DRIVER
QUARKUS_DATASOURCE_JDBC_URL
QUARKUS_DATASOURCE_USERNAME
QUARKUS_DATASOURCE_PASSWORD

With quarkus dev everything works propertly
The issue is present only with quarkus build (native mode, I rely on podman, I didn't manually install graal vm)

### Expected behavior

Specifying datasource environment variables at compile time should be the same as specify those values in application.properties

This is true for every other environment variables I already use : 

QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
QUARKUS_OPENTELEMETRY_ENABLED
QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT
QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_HEADERS
etc etc

### Actual behavior

Environment variables values are not propagated or honored at runtime and this leads to errors like : 

2023-02-22 10:53:50.29 UTCgreetings-84f475797f-s55s2greetingsModel classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.

### Output of `java -version`

17

### Quarkus version or git rev

3.0.0 Alpha4

### Additional information

As a workaroud, I **ALSO** specify this values to force propagation of values

QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_DATASOURCE_JDBC_DRIVER__
QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_DATASOURCE_JDBC_URL__
QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_DATASOURCE_USERNAME__
QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_DATASOURCE_PASSWORD__

I say "ALSO" because the _normal_ environment variables are required for build/test steps.

**Comment by iocanel** [comment]
This is something that could slightly simplify your workflow but is generally not a good idea. Credentials are better kept in secrets instead of environment variables. It's also not a great idea to generate manifests that are env specific.

**Comment by amoscatelli** [comment]
I may agree with you,
still this seems an issue to me since secrets put in application.properties and secrets put in environment variables are diffently managed

![image](https://user-images.githubusercontent.com/16684470/220846696-697f01ec-db76-4d81-90ab-82e8ea585760.png)

the docs seems to state otherwise

**Comment by amoscatelli** [comment]
Anyway I am switching to secrets, I completely missed this guide : 

https://quarkus.io/guides/kubernetes-config

Thank you for pointing me in the right direction !

**Comment by amoscatelli** [comment]
@iocanel to tell the truth seems to be a problem with secrets too : 

QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__FROM_SECRET
QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__WITH_KEY

environment variables (written as in the documentation) seem not to work.

If you use the application properties, everything works : 

quarkus.kubernetes.env.mapping."mapping".from-secret
quarkus.kubernetes.env.mapping."mapping".with-key

Another workaround is to use environment variables EXACTLY written as the application properties (so lowercase and with dot separator). In this case everything works too.

Should I file a separate issue ?

**Comment by amoscatelli** [comment]
By working and not working I mean that kubernetes.yml is not correctly updated with the env from secret, of course.
