### ISSUE TITLE
Quarkus Flyway - all schemas do not sync at startup

### ISSUE THREAD

**Issue by kirankolli-addepar** [quarkusio/quarkus#31391]
### Discussed in https://github.com/quarkusio/quarkus/discussions/31377

<div type='discussions-op-text'>

<sup>Originally posted by **kirankolli-addepar** February 23, 2023</sup>
Hi,
I have a unit test with a Postgres test container resource that is initialized and a test profile which overrides the "quarkus.datasource.jdbc.url" to point to the container I just started. 
In this unit test I wanted to test my DAO class against the postgres resource that I have initialized. 
As part of startup I rely on Quarkus Flyway to synchronise the schemas and I have this prop : 
```
quarkus.flyway.schemas=schema1,schema2
quarkus.flyway.create-schemas=true
quarkus.flyway.migrate-at-start=true
```
What I find is that on startup only 'schema1' is getting synced up but not schema2.

```
@QuarkusTest
@QuarkusTestResource(MyPostGres.class) //inits postgres test container statically
@TestProfile(MyTestProfile.class) // extends QuarkusTestProfile and overrides quarkus jdbc url
public class MyTest {
@Inject AgroalDataSource testDataSource; 
@Inject MyDAO daoToTest; 
}
```

How do I resolve this ? The test fails because it cannot find the tables it intends to test against.

**Update :** 
I have also tried the below **but it did not work** : 

Adding a separate named datasource : 
```
quarkus.datasource.schema2.jdbc.url=<same url as quarkus jdbc url>
quarkus.datasource.schema2.db-kind=postgresql
quarkus.datasource.schema2.username=user
quarkus.datasource.schema2.password=pwd
quarkus.datasource.schema2.jdbc.max-size=16
```

Then add migrate at start for that named datasource.
```
quarkus.flyway.schema2.schemas=schema2
quarkus.flyway.schema2.create-schemas=true
quarkus.flyway.schema2.migrate-at-start=true
```

Tagging @geoand / @maxandersen for help</div>

**Comment by geoand** [comment]
Can you please provide a sample application that exhibits this behavior?

**Comment by geoand** [comment]
Closing as never got a reproducer
