### ISSUE TITLE
How to set record-request-start-time attribute for undertow?

### ISSUE THREAD

**Issue by fmutluay** [quarkusio/quarkus#3140]
After enabling the access-log handler via undertow-handlers.conf file, the %D or %T pattern not print the response time into log file.

Contents of ../src/main/resources/META-INF/undertow-handlers.conf
access-log('%h %{i,X-Forwarded-For} %l %u %t %r %s %b %I %D')

Is there any way to set this attribute to true?

**Comment by gsmet** [comment]
@stuartwdouglas any idea on that one?

**Comment by stuartwdouglas** [comment]
We should address this (and access logging) at the vert.x level.

**Comment by gsmet** [comment]
This is related to https://github.com/quarkusio/quarkus/issues/5556 .

**Comment by stuartwdouglas** [comment]
Closing this, as access logging is now handled at the vert.x level.
