### ISSUE TITLE
Propagate SystemProperties set in Failsafe plugin to the Test launcher

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#31405]
### Description

Check: https://github.com/quarkusio/quarkus/issues/27266#issuecomment-1397482713

**Comment by geoand** [comment]
@radcortez I see in the comments of the original issue that you said you would start something if you had time. 
Just so we avoid doing duplicate work, did you get something going or should I have a look?

**Comment by radcortez** [comment]
Didn't get into it yet. If you have some spare cycles, feel free to move it forward :)

**Comment by geoand** [comment]
I might be able to spend 10 minutes on it :). If that's enough to fix the problem, great 😆. If not, let's just leave it for when either of us has time

**Comment by radcortez** [comment]
Sure :)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/31465 should take care of it :)
