### ISSUE TITLE
@ServerExceptionMapper doesn't support multiple exception types

### ISSUE THREAD

**Issue by annaazizova** [quarkusio/quarkus#31406]
### Describe the bug

```
@ServerExceptionMapper(value = {MyExceptionOne.class, MyExceptionTwo.class})
    public Uni<Response> mapException(RuntimeException e) {
        return Uni.createFrom().item(() ->  Response.status(Response.Status.CONFLICT)
                .entity(Map.of(MESSAGE, message))
                .build(););
    }
```

### Expected behavior

multiple exception classes are supported

### Actual behavior

```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveScanningProcessor#handleCustomAnnotatedMethods threw an exception: java.lang.RuntimeException: Parameter 'e' of method 'mapException of class '...' is not allowed

```

### Output of `uname -a` or `ver`

Darwin RDU-W4HVVTY7VT 21.4.0 Darwin Kernel Version 21.4.0

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

I see that this issue was fixed in https://github.com/quarkusio/quarkus/issues/20202, but it appeared again

**Comment by Sgitario** [comment]
To support multiple exceptions handling, you need to use `Throwable` instead of `RuntimeException`.

**Comment by geoand** [comment]
We should probably make that clear in the error message :)

**Comment by Sgitario** [comment]
I think that we should not force users to use Throwable, I'm working on a fix that will allow this use cause.

**Comment by geoand** [comment]
Sure, allowing the "closest" common exception parent would be better

**Comment by Sgitario** [comment]
Fix: https://github.com/quarkusio/quarkus/pull/31436
