### ISSUE TITLE
GZIP Compression not working in servlet application

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#31415]
### Describe the bug

I am working on the JSF/Faces extensions for Quarkus for OmniFaces and PrimeFaces.

Using `quarkus.http.enable-compression=true` is not compressing any of my JS or CSS files as expected based on Mime Type.

### Expected behavior

GZIP compression should occur

### Actual behavior

No Gzip compression is happening with `quarkus.http.enable-compression=true`

### How to Reproduce?

Reproducer: [quarkus-compression.zip](https://github.com/quarkusio/quarkus/files/10831165/quarkus-compression.zip)

1. Unzip the reproducer
2. Run `mvn quarkus:dev`
3. Open browser to http://localhost:8080/ 
4. Open F12 and inspect the traffic GZIP compression is not taking place even though the `Content-Type: application/javascript` is correct.

![image](https://user-images.githubusercontent.com/4399574/221357554-8219f1a7-19f5-4fb5-bf63-5c354180c098.png)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1265]

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)

### Quarkus version or git rev

2.16.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

I have also tested trying to custom set mime-types and it has no effect using `quarkus.http.compress-media-types=` but it also has no effect.  But the defaults of ` text/html, text/plain, text/xml, text/css, text/javascript and application/javascript.` are all I need anyway.

**Comment by melloware** [comment]
cc @stuartwdouglas

**Comment by stuartwdouglas** [comment]
@mkouba looks like https://github.com/stuartwdouglas/quarkus/commit/670a205d3870a517001a53006d46ac08c5cb5437 broke compression for Servlet (and likely Resteasy Classic)? 

There is now always a `Content-Encoding: identity` header, which needs to be removed to enable compression. The docs for https://github.com/stuartwdouglas/quarkus/blob/933a7ef7b7b1ec9c6071cf0e52eeae7edd7d1ca4/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpBuildTimeConfig.java#L72 are also no longer correct.

**Comment by mkouba** [comment]
Hm, for RESTEasy Classic it's [documented that `quarkus.http.enable-compression` has no effect](https://quarkus.io/guides/resteasy#gzip-support) and `quarkus.resteasy.gzip.enabled=true` plus the `@org.jboss.resteasy.annotations.GZIP` should be used.

The case for servlets was actually never discussed in the scope of https://github.com/quarkusio/quarkus/pull/24558 and related issues :thinking:. 

I think that we should honor the `quarkus.http.compress-media-types` by default.

**Comment by mkouba** [comment]
@stuartwdouglas I was trying to fix the problem in https://github.com/mkouba/quarkus/commit/e3aceb96c2b004e1a72d0e4775023e44c409c9c0, i.e. wrap the UT handler and remove the `Content-Encoding: identity` header in an "end" handler regitered via `RoutingContext.addEndHandler()`. But the end handler does not seem to be called at all for UT. Do you have an idea about what could be wrong?

**Comment by mkouba** [comment]
Hm, maybe it's because the `VertxHttpExchange` [does set its own end handler](https://github.com/quarkusio/quarkus-http/blob/main/vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java#L210-L220); so the end handlers added previously are just ignored...

**Comment by mkouba** [comment]
> Hm, maybe it's because the `VertxHttpExchange` [does set its own end handler](https://github.com/quarkusio/quarkus-http/blob/main/vertx/src/main/java/io/undertow/vertx/VertxHttpExchange.java#L210-L220); so the end handlers added previously are just ignored...

That seemed to be the cause - a workaround is to add the handler logic after the `VertxHttpExchange` is created.

**Comment by melloware** [comment]
Thanks you for investigating and resolving @mkouba !

**Comment by melloware** [comment]
Thank you team!

**Comment by melloware** [comment]
Confirmed this works in my Servlet app in 3.0.0.Alpha5!
