### ISSUE TITLE
Quarkus CLI Upgrading to 3 failed in Windows Powershell

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#31421]
### Describe the bug

I followed the guide in https://quarkus.io/blog/quarkus-3-0-0-alpha4-released/ and tried to upgrade my Quarkus examples to the next generation of Quarkus 3.0.0.Alpha4.

Failed.

### Expected behavior

It should be executed sucessfully.

### Actual behavior

It is failed with following exception.

```bash
Downloading https://raw.githubusercontent.com/quarkusio/quarkus-updates/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml to temporary file.
Executing:
mvn -e org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run -DplainTextMasks=**/META-INF/services/**,**/*.txt,**/*.adoc,**/*.md,**/src/main/codestarts/**/*.java,**/src/test/resources/__snapshots__/**/*.java -Drewrite.configLocation=C:\Users\hantsy\AppData\Local\Temp\merged-recipe6441423025574932875.yml -DactiveRecipes=io.quarkus.updates.core.quarkus30.Quarkus3 -Drewrite.pomCacheEnabled=false
java.io.IOException: Cannot run program "mvn": CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at q3upgrade.executeCommand(q3upgrade.java:180)
        at q3upgrade.handleMaven(q3upgrade.java:105)
        at q3upgrade.run(q3upgrade.java:69)
        at q3upgrade.main(q3upgrade.java:51)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 5 more
```

### How to Reproduce?

1. Open Windows PowerShell, enter a Quarkus 2.x project
2. And execute the following command.

   ```bash
    iex "& { $(iwr https://ps.jbang.dev) } --fresh upgrade-to-quarkus3"
   ``` 

### Output of `java -version`

java 17.0.6 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584) Maven home: D:\build\maven Java version: 17.0.6, vendor: Oracle Corporation, runtime: D:\jdks\jdk17 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

It is possible an issue related to Powershell. In Powershell, the mvn command parameters must be wrapped with quotes.

Changed the failed mvn command to the following.
 
```bash
 mvn -e org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run
-D"plainTextMasks=**/META-INF/services/**,**/*.txt,**/*.adoc,**/*.md,**/src/main/codestarts/**/*.java,**/src/test/resources/__snapshots__/**/*.java"
-D"rewrite.configLocation=C:\Users\hantsy\AppData\Local\Temp\merged-recipe7115927254550273296.yml"
-D"activeRecipes=io.quarkus.updates.core.quarkus30.Quarkus3"
-D"rewrite.pomCacheEnabled=false"
```

Now it is executed successfully.

**Comment by gsmet** [comment]
I will have a look.

**Comment by gsmet** [comment]
@hantsy it should be fixed, can you give it a try on your projects?
