### ISSUE TITLE
Kotlin Support for Quarkus CLI Upgrading to 3

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#31423]
### Description

When running the command on a Quarkus Kotlin project, it seems it only update the POM file, and ignore all Kotlin source codes.

```bash
iex "& { $(iwr https://ps.jbang.dev) } --fresh upgrade-to-quarkus3"
```

Due to the issue #31421, in fact I ran the following command in the project folder instead.

```bash
 mvn -e org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run
-D"plainTextMasks=**/META-INF/services/**,**/*.txt,**/*.adoc,**/*.md,**/src/main/codestarts/**/*.java,**/src/test/resources/__snapshots__/**/*.java"
-D"rewrite.configLocation=C:\Users\hantsy\AppData\Local\Temp\merged-recipe7115927254550273296.yml"
-D"activeRecipes=io.quarkus.updates.core.quarkus30.Quarkus3"
-D"rewrite.pomCacheEnabled=false"

```

**Comment by maxandersen** [comment]
Yes. Openrewrite don't yet have kotlin support and unfortunately not much we can do - except source code text replacements which would not be complete :/

**Comment by hantsy** [comment]
There is a https://github.com/openrewrite/rewrite-kotlin, it can not process Kotlin?

**Comment by maxandersen** [comment]
That had its first release this month and still work in progress. 

Existing rewrite rules are not utilizing it. 

Would you be up for trying it out and make PRs to enable it?

**Comment by gsmet** [comment]
I will have a look.

**Comment by gsmet** [comment]
@hantsy it should be fixed, can you give it a try on your projects?

**Comment by maxandersen** [comment]
@gsmet your fix wasn't about kotlin Afaics. Thus kotlin still not supported yet for migration yet, right?

**Comment by gsmet** [comment]
It sure was, it's just that it was done in multiple repositories to cover the update recipe https://github.com/quarkusio/quarkus-updates/pull/10 , the current JBang script https://github.com/quarkusio/jbang-catalog/pull/37 and https://github.com/quarkusio/jbang-catalog/pull/39 and the future update command https://github.com/quarkusio/quarkus/pull/31598/files#diff-43132b4e06cc97c5847639def551dd006fbb96d5ce3d9665c11f72ca36fd3715R80 .

The JBang script should handle Kotlin just fine (at least in the common cases as it's just a text replacement).

I tested it on a simple Kotlin project.

Have some faith :).

**Comment by maxandersen** [comment]
Interesting. That's awesome. 

I'll assume package and class renames works but less for more lower less AST transforms. 

Anyhow awesome!

**Comment by maxandersen** [comment]
Oh wait - the pr does text replace on kotlin. Gotcha - grok it now :)
