### ISSUE TITLE
Kubernetes extension does not always honor secret mapping environment variables

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#31437]
### Describe the bug

Environment variables to read Kubernetes secrets are not honored and the kubernetes.yml is not filled accordingly.

Even the ones from the documentation do not work : 

QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__FROM_SECRET
QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__WITH_KEY

Application properties properly work, instead :

quarkus.kubernetes.env.mapping."mapping".from-secret
quarkus.kubernetes.env.mapping."mapping".with-key

Strange fact, if the environment variables are written exactly like the application properties (I mean lower case and using dot as separating character) then eveything works properly.

The issue seems to be related to conversion rules when reading environment variables.

### Expected behavior

QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__FROM_SECRET
QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__WITH_KEY

environment variables should be honored, with the documented case

### Actual behavior

QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__FROM_SECRET
QUARKUS_KUBERNETES_ENV_MAPPING__MAPPING__WITH_KEY

are not honored and kubernetes.yml is not updated accordingly during building

### Output of `java -version`

17

### Quarkus version or git rev

3.0.0 Alpha4

**Comment by radcortez** [comment]
When setting up environment variables that are ambiguous in their names to their dotted format, we need to disambiguate them. In this case, `FROM_SECRET` and `WITH_KEY` can either represent `from.secret` or `from-secret` and `with.key` or `with-key`.

The way to resolve this is to add an empty property name with the correct name in a lower ordinal source (like `application.properties`).

```properties
quarkus.kubernetes.env.mapping."mapping".from-secret=
quarkus.kubernetes.env.mapping."mapping".with-key=
```

You can find a more detailed explanation on the docs: https://quarkus.io/version/main/guides/config-reference#environment-variables.

**Comment by amoscatelli** [comment]
Thank you @radcortez 
I have read that docs before, but I didn't correctly understand what you just exaplained, I am sorry.

Thank you again for the explanation

**Comment by radcortez** [comment]
No worries. I'm already too biased on this, so if you can think of a better way to explain it, I'm happy to change the docs :)
