### ISSUE TITLE
SmallRye Reactive Messaging - Kafka depends on Hibernate Reactive but is built before it

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#31446]
### Describe the bug

The build order is currently defined by Maven Reactor as:

1. Quarkus - Hibernate Reactive - Runtime
2. Quarkus - SmallRye Reactive Messaging - Kafka - Runtime
3. Quarkus - SmallRye Reactive Messaging - Kafka - Deployment
4. Quarkus - Hibernate Reactive - Deployment

This results in tricky problems during the maintenance and development of Quarkus; not sure if it also affects releases.

### Quarkus version or git rev

Current `main` at 1d45952917c

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by ozangunalp** [comment]
@Sanne SmallRye Reactive Messaging - Kafka runtime has optional dependencies for redis-client, hibernate-reactive and hibernate-orm runtime modules. 

But the SmallRye Reactive Messaging - Deployment module doesn't have any of those dependencies. 
The reactor order seems correct to me.

**Comment by Sanne** [comment]
Are you sure the hibernate-reactive extension doesn't get activated during integration tests?

I had a failure earlier which clearly was triggered by me making changes to both the Hibernate Reactive Runtime and Deployment modules; so the order looks suspicious to me as Maven recognized the need to rebuild the HR runtime module first, but not the matching deployment.

Remember that in Quarkus the deployment modules get pulled in automatically to match their runtime counterparts, but Maven doesn't know about it. This is handled by our customizations, therefore it's not automatic but we need to handle the order with care, and sometimes add an artificial dependency to ensure correct order of build is defined.

Unfortunately since I'm working with snapshtos and it's hard to try reproduce the earlier error, but the order looks wrong to me - it would certainly be safer to ensure that Runtime and Deployment modules of each extension are not build "interleaved".

You need something like this:

https://github.com/quarkusio/quarkus/blob/main/integration-tests/hibernate-orm-envers/pom.xml#L49-L75

Alternatively, get rid of the optional dependency and move that into a dedicated module which provides the bridge code and depends on both. Optional dependency are a pain to maintain ;)

**Comment by ozangunalp** [comment]
I knew about the deployment modules getting pulled in, but didn't imagine it would cause such an issue, especially since the deployment modules are not really dependent. Did you have that using --also-make ?

There are IT modules testing hibernate-orm with smallrye-reactive-kafka and hibernate-reactive with smallrye-reactive-kafka. But the `-deployment` module dependencies are there for those IT modules.

I know optional dependencies are hard. But sometimes it is practical :) At least they are in the same repo.

**Comment by Sanne** [comment]
> I knew about the deployment modules getting pulled in, but didn't imagine it would cause such an issue, especially since the deployment modules are not really dependent. Did you have that using --also-make ?

Right, when making changes to some module I run the tests targeting the patched modules with `-amd` , so to have it rebuild my modules and anything dependent on it.
But I need to be able to trust the Maven reactor order to build things in the right sequence, and not least to identify which modules need to be rebuilt at all. Unfortunately the way our build works this is all quite fragile.

> I know optional dependencies are hard. But sometimes it is practical :) At least they are in the same repo.

Ok, as you prefer :)

**Comment by ozangunalp** [comment]
Ok, I think I have a lead for the problem. Those integration tests use panache dependencies and so adds its `...panache-deployment` dependency with * exclusions. But that won't pull `quarkus-hibernate-reactive-deployment` or `quarkus-hibernate-orm-deployment`.

**Comment by ozangunalp** [comment]
The easiest way I can think of to force the build order is to add a test dependency from reactive-messaging-kafka-deployment to other deployment modules.

**Comment by cescoffier** [comment]
@ozangunalp any update on this one?

**Comment by ozangunalp** [comment]
Sorry I forgot about this. Did some tests and opened #36070
