### ISSUE TITLE
Flyway + Hibernate 6.2 Breaks the previous SEQUENCE  behavior

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#31451]
### Describe the bug

On Quarkus `999-SNAPSHOT` we have bumped a [new Hibernate version](https://github.com/quarkusio/quarkus/pull/31235) that has introduced several changes. The [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#hibernate-reactive) didn´t say anything about default ID SEQUENCE generator behavior. 

In the previous version, I didn´t have to define the `SEQUENCE` of entities that extends `PanacheEntity` but now I am getting the following error:

```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing sequence [application_SEQ]
```

The workaround is to create this `SEQUENCE` by hand on my flyway init script
```
CREATE SEQUENCE application_SEQ START 1 INCREMENT 50;
CREATE SEQUENCE service_SEQ START 1 INCREMENT 50;
```

Also note that I need to define the increment value otherwise I got a `Schema-validation: sequence [service_SEQ] defined inconsistent increment-size; found [1] but expecting [50]` error

### Expected behavior

Same as the previous version or some documentation on the migration guide. 

### How to Reproduce?

`git clone git@github.com:quarkus-qe/beefy-scenarios.git`

`cd 011-quarkus-panache-rest-flyway`

`mvn clean verify -Dit.test=PostgreSqlApplicationResourceTest#shouldFindApplicationWhenFilteringByServiceName`

Be sure that `resources/db/migration/V1.0.0__init.sql` doesn´t have the above `SEQUENCE` statements

**Comment by gsmet** [comment]
I'm going to close this one as we are tracking this effort here: https://github.com/quarkusio/quarkus/issues/31475 .
