### ISSUE TITLE
Unable to inject synthetic bean

### ISSUE THREAD

**Issue by tarvfx** [quarkusio/quarkus#31466]
### Describe the bug

Hi, guys

I customized an extension and created a `named synthetic bean` using `@Named`. But I can't inject it. Can synthetic beans not declare the `@Named` annotation? Am I missing something or is this a bug? Exception output from the console:

```log
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 63584
Connected to the target VM, address: '127.0.0.1:63584', transport: 'socket'
Tests paused
2023-02-28 19:03:19,120 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-02-28 19:03:19,577 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type io.github.demo.DemoBean and qualifiers [@Default]
	- java member: io.github.tarvfx.ExampleResource#demoBean
	- declared on CLASS bean [types=[io.github.tarvfx.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=io.github.tarvfx.ExampleResource]
	- available beans:
		- SYNTHETIC bean [types=[io.github.demo.DemoBean], qualifiers=[@javax.enterprise.inject.Default, @Any], target=n/a]
		- SYNTHETIC bean [types=[io.github.demo.DemoBean], qualifiers=[@Named("b1"), @Default, @Any], target=n/a]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:288)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:148)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

extension code:

```java

    private static final DotName NAMED_ANNOTATION = DotName.createSimple(Named.class);

    private <T> SyntheticBeanBuildItem createSyntheticBean(Class<T> beanClass, String name, RuntimeValue<T> value) {
        SyntheticBeanBuildItem.ExtendedBeanConfigurator configurator = SyntheticBeanBuildItem
            .configure(beanClass)
            .unremovable()
            .setRuntimeInit()
            .runtimeValue(value)
            .scope(Singleton.class);

        if (name == null) {
            configurator.addQualifier(Default.class);
        } else {
            configurator.named(name);
        }
        return configurator.done();
    }
```

inject code:

```java
    @Inject
    DemoBean demoBean;

    @Inject
    @Named("b1")
    DemoBean b1Bean;
```

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.3.0

### Quarkus version or git rev

2.16.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by tarvfx** [comment]
From the [CDI spec](http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#builtin_qualifiers):

> If a bean does not explicitly declare a qualifier other than `@Named`, the bean has exactly one additional qualifier, of type `@Default`. This is called the default qualifier.

But quarkus adds the `@Default` qualifier to the named synthetic bean, is this expected?

```log
- SYNTHETIC bean [types=[io.github.demo.DemoBean], qualifiers=[@Named("b1"), @Default, @Any], target=n/a]
```

**Comment by Ladicek** [comment]
If you read that quote from the CDI spec again, you'll see that Quarkus actually _must_ add `@Default` in this case (when nothing else but `@Named` is present).

Now, we can debate whether the quote from the spec should apply to synthetic beans too, but I'd say yes.

**Comment by Ladicek** [comment]
I guess @tarvfx tries to have one `@Default` bean and multiple `@Named` beans, which seems perfectly natural to me, except CDI prevents that by treating `@Named` specially. I'd recommend using a different qualifier -- we have `@Identifier` for exactly this purpose.

**Comment by manovotn** [comment]
> I guess @tarvfx tries to have one `@Default` bean and multiple `@Named` beans, which seems perfectly natural to me, except CDI prevents that by treating `@Named` specially. I'd recommend using a different qualifier -- we have `@Identifier` for exactly this purpose.

Could be, the code in issue description is not saying enough to be able to tell what the end goal of this setup is :)

**Comment by tarvfx** [comment]
@Hi, @manovotn @Ladicek 

Thanks for your reply! As @Ladicek guessed, I'm going to have a Default Bean and multiple Named Beans. Sorry I didn't fully state the intent.
I adjusted the code and Named worked.

```java
SyntheticBeanBuildItem.ExtendedBeanConfigurator configurator = SyntheticBeanBuildItem
            .configure(beanClass)
            .unremovable()
            .setRuntimeInit()
            .runtimeValue(value)
            .scope(Singleton.class);

if (clientName == null) {
    configurator.defaultBean();
    // configurator.addQualifier(DotNames.DEFAULT);
    // configurator.addQualifier(Default.class);
} else {
    configurator.named(name);
}
```

**Comment by tarvfx** [comment]
> I guess @tarvfx tries to have one `@Default` bean and multiple `@Named` beans, which seems perfectly natural to me, except CDI prevents that by treating `@Named` specially. I'd recommend using a different qualifier -- we have `@Identifier` for exactly this purpose.

Inspired by you, I think `@Identifier` is more suitable for me. `@Named` seems to be deprecated in the CDI spec. I know from practice that the value of Named must be globally unique (even if the injected target type is different), and @Identifier will not have such restrictions. Please correct me if I am wrong. Thanks!

**Comment by tarvfx** [comment]
Since there is `@Identifier`, why are `@RedisClientName` and `@ReactiveDataSource` identifiers defined in the extension of Redis client and reactive data sources? I think it's a good idea to use `@Identifier` to unify identifiers. Or am I wrong, if so please correct me. Thanks!

**Comment by Ladicek** [comment]
I think specific qualifiers are generally better than generic `@Named`/`@Identifier`, just because the intent is more visible. There's some element of personal preference in that, though. The entire Quarkus is not totally consistent in this matter, unfortunately.

**Comment by manovotn** [comment]
> I know from practice that the value of Named must be globally unique (even if the injected target type is different), and @Identifier will not have such restrictions. Please correct me if I am wrong. Thanks!

Right, `@Named` gives a bean a unique name and spec has to check it's uniqueness. The purpose of this name was referencing the bean only by its name (and not its type or qualifiers), such as in EL.
`@Indentifier` is "just another qualifier" meaning it has no special treatment but that's just fine because each bean is identified by its *type and qualifiers* so there is nothing wrong about having `@Identifier("something") Foo` and `@Identifier("something") Bar` as they are technically different.

> Since there is @Identifier, why are @RedisClientName and @ReactiveDataSource qualifiers defined in the extension of Redis and reactive data sources?

Like Ladislav said, it's partly a personal preference and partly also clarity. Frameworks use their own qualifiers because then they also know which qualifiers to look for when identifying and working with their beans and can set certain expectations/standard on how the name should look like, what the default will be and so on.

**Comment by manovotn** [comment]
@tarvfx since you solved your original problem, can we close this issue?

**Comment by tarvfx** [comment]
Thanks a lot, let me know more. @manovotn and @Ladicek
