### ISSUE TITLE
Guide USING OPENTELEMETRY is not working

### ISSUE THREAD

**Issue by liudas-stonys** [quarkusio/quarkus#31464]
### Describe the bug

I'm trying to run your guide on using Opentelemetry, but it's not working. I followed every step in your guide. Tried 2 times, so I'm sure I did everything correct. Opentelemetry container in Docker is logging this: `Err: connection error: desc = "transport: Error while dialing: dial tcp: lookup jaeger-all-in-one on 127.0.0.11:53: no such host`.

### How to Reproduce?

Follow the guide:  https://quarkus.io/guides/opentelemetry

I think the issue is in the config: https://quarkus.io/guides/opentelemetry#run-the-application

### Output of `uname -a` or `ver`

Darwin Liudass-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.14" 2022-01-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)

### Quarkus version or git rev

2.16.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

I run using `quarkus dev`
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/local/Cellar/maven/3.8.6/libexec
Java version: 11.0.14, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.3", arch: "x86_64", family: "mac"

**Comment by liudas-stonys** [comment]
@brunobat, I'm just starting to learn Docker, so I thought, since my logs reach `opentelemetry-collector`, that all the magic lies in `docker-compose` and `otel-collector-config`.

docker-compose:
`jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger-all-in-one`

otel-collector-config:
`receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
service:
  pipelines:
    traces:
      exporters: [jaeger]`

I thought the guide should work, but maybe I need to add additional config to `docker-compose`? Like `collector.host-port=localhost:4317`?
I will try this tomorrow and let you know how it goes. Thank you!:)

**Comment by brunobat** [comment]
Have you configured your app's configs like this? https://quarkus.io/guides/opentelemetry#create-the-configuration

**Comment by liudas-stonys** [comment]
I messed up so bad... I must have used `mvn clean quarkus:dev` instead of just using `quarkus dev` or `mvn quarkus:dev`.

Thank you for your time! 🙏

**Comment by brunobat** [comment]
No worries :)
You are always welcome.
