### ISSUE TITLE
Extension runtime config not recognized when passing as env

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#31461]
### Describe the bug

I have an extension that defines a runtime config containing a map. It does work when directly defining the property in applications.properties, but when I pass the arguments as ENV var, the config fails to parse.

### Expected behavior

A config containing a map like
```
@ConfigMapping(prefix = "my.props")
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
public interface BadConfig {

    /**
     * @return
     */
    @WithParentName
    Map<String, NestedProperties> nested();

    public interface NestedProperties {

        /**
         * @return
         */
        @WithName("sub.id")
        int id();
    }

}
````

should successfully be initialized when passing the config property as env variables like so:
`MY_PROPS__THIS__SUB_ID=1 ./gradlew :application:quarkusDev`

### Actual behavior

Exception gets thrown
`io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00014: The config property my.props.this.sub.id is required but it could not be found in any config source`
        
This shows that the property got picked up, as the error includes the `this` property token in the message, but then somhow failed to resolve the nested group.

When adding an additional wrapper interface to the config like: https://github.com/HerrDerb/extension-config-issue/blob/main/runtime/src/main/java/com/example/GoodConfig.java, it will work.

### How to Reproduce?

Reproducer:
https://github.com/HerrDerb/extension-config-issue

Execute steps for error

1. `./gradlew clean publishToMavenLocal`
2. `MY_PROPS__THIS__SUB_ID=1 ./gradlew :application:quarkusDev`

When removing BadConfig an republish, GoodConfig with the additional wrapper will work.

**Comment by geoand** [comment]
The environment variable is incorrect, you need to use `MY_PROPTHIS_SUB_ID=1`

**Comment by HerrDerb** [comment]
@geoand this seems to be an entierly different property as I have defined. Thats also why my example project does not error, as it does not try to resolve  the described properties. I updated the project accordingly to fail, if the config map is empty.

**Comment by geoand** [comment]
Sorry, I updated the previous comment

**Comment by HerrDerb** [comment]
Oh, thanks. We had the double underscore from when we thought the dynamic property token might contain a dash or so, but this doesn't work anyway. So yes, single underscore did solve the problem. Thanks :)

**Comment by geoand** [comment]
💪🏼
