### ISSUE TITLE
Loadbalance for reactive mysql client

### ISSUE THREAD

**Issue by benstonezhang** [quarkusio/quarkus#31492]
### Description

There is built-in loadbalance support from MySQL Connector/J driver, so we can write `quarkus.datasource.jdbc.url=jdbc:mysql:loadbalance://192.168.32.101,192.168.32.102/dbname` in application.properties to take the advantage of load balance.

For reactive mysql client similar config not work because vert.x mysql client not support the `loadbalance` keyword within url. But vert.x do support server load balance. https://vertx.io/docs/vertx-mysql-client/java/#_advanced_pool_configuration

Do we have any plan to support config like this? `quarkus.datasource.reactive.url=mysql:loadbalance://192.168.32.101,192.168.32.102/dbname`

### Implementation ideas

update io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder, change `MySQLPool.pool(Vertx vertx, MySQLConnectOptions database, PoolOptions options)` to `MySQLPool.pool(Vertx vertx, List<MySQLConnectOptions> databases, PoolOptions options)` if keyword `loadbalance` present in the url

**Comment by geoand** [comment]
Quarkus 3 will provide a (programmatic) way to do this by using `io.quarkus.reactive.mysql.client.MySQLPoolCreator`.
Some documentation using PostgreSQL can be found [here](https://quarkus.io/version/main/guides/reactive-sql-clients#customizing-pool-creation) while a very simple sample used in our tests can be found [here](https://github.com/quarkusio/quarkus/blob/3.0.0.Alpha4/extensions/reactive-mysql-client/deployment/src/test/java/io/quarkus/reactive/mysql/client/LocalhostMySQLPoolCreator.java).

So I think we can close this instead of providing some hard coded support.

**Comment by benstonezhang** [comment]
Excuse me, but I do found neither any config nor code relate to load balance between multi servers.

**Comment by geoand** [comment]
The idea is that you can create the `MySQLPool` on your own

**Comment by benstonezhang** [comment]
@geoand Would you please help me create a Quarkiverse extension name  as "quarkus-reactive-mysql-pool-client", so I can work on it to add load balance support for Quarkus 2 ? Thanks in advance.

**Comment by benstonezhang** [comment]
@gastaldi Would you please help me create a Quarkiverse extension name  as "quarkus-reactive-mysql-pool-client", so I can work on it to add load balance support for Quarkus 2 ? Thanks in advance.

**Comment by gastaldi** [comment]
@benstonezhang sure, but before we do that, may I ask: Is there any reason preventing you from upgrading to Quarkus 3 and using the new API?

**Comment by benstonezhang** [comment]
Our project had finish development and turn to deployment phase, we can not afford migration to quarkus 3 at this time.
While our project have pulsar, mariadb-galera and redis clusters, most of micro-services which use mariadb jdbc driver have JDBC driver build-in support of fatal toleration and load balance. Only the core service which take advance of the whole quarkus reactive routines and based on mysql reactive client can not support fatal toleration and load balance. This issue just been recognized while we deploy the project to production cluster. That's why we must make it work.

**Comment by benstonezhang** [comment]
for the proposed url "jdbc:mysql:loadbalance://192.168.32.101:3306,192.168.32.102:3306/dbname", it's just to minic mysql jdbc driver, so easy to maintain config for all services. We may also accept "jdbc:mysql://192.168.32.101:3306,192.168.32.102:3306/dbname".

**Comment by gastaldi** [comment]
Understood. To be honest, given we really want users to migrate to Quarkus 3, I'd be inclined to have this feature supported in Quarkus 3 (eg. by providing a custom MySQLPoolCreator implementation ourselves) rather than having it in a Quarkiverse extension that would only work for 2.x. This would be my personal opinion.

What are your thougths on this @gsmet @maxandersen ?

**Comment by benstonezhang** [comment]
We do have plan to investigate migration to Quarkus 3, maybe on next several months. But we do want reactive mysql client with fatal toleration and load balance is available soon.

**Comment by maxandersen** [comment]
@gastaldi rather than we form a quarkiverse extension could we not explore making a branch with the migration tools we have and see what fails first?

**Comment by maxandersen** [comment]
Ah sorry - misread. Thought there already was an extension.

**Comment by maxandersen** [comment]
No objection on having something in quarkiverse hub to hanndle things differently for quarkus 2 vs quarkus 3 if someone wants to maintain it. Let's just make sure it's clearly documented.

**Comment by benstonezhang** [comment]
@gastaldi We had the code ready, would you please help to create the "quarkus-reactive-mysql-pool-client" project?

**Comment by maxandersen** [comment]
reopening for @gastaldi

**Comment by benstonezhang** [comment]
Thanks to push this happen. I know it's not easy. Thanks a lot.
To be honest, I don't think the new introduced "io.quarkus.reactive.mysql.client.MySQLPoolCreator" can handle such style of url. If you do so, it will fail within MySQLPoolRecorder::toMySQLConnectOptions -> MySQLConnectOptions.fromUri(url).

**Comment by gastaldi** [comment]
@benstonezhang mind creating a PR or opening an issue for that case?

**Comment by benstonezhang** [comment]
OK. I will try to porting the code to main branch and create a PR.

**Comment by benstonezhang** [comment]
Sorry, I must misunderstand. I mean even with MySQLPoolCreator, nobody can make it accept the load balance style url, for example "mysql://192.168.32.101:3306,192.168.32.102:3306/dbname".

**Comment by benstonezhang** [comment]
Sorry, I must misunderstand. I mean even with MySQLPoolCreator, nobody can make it accept the load balance style url, for example "mysql://192.168.32.101:3306,192.168.32.102:3306/dbname".

**Comment by gastaldi** [comment]
Hm, that's bad. I think it would be great if you could provide a PR

**Comment by benstonezhang** [comment]
@gastaldi PR #31852 opened for this.
