### ISSUE TITLE
Quarkus 2.16 Migration guide / Transaction API examples

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#31508]
### Describe the bug

Related to: https://github.com/quarkusio/quarkus/pull/31507

Migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16 are talking about the new Transaction API, more in detail is providing some example where this transaction result is returned `RunOptions.ExceptionResult.ROLLBACK`. In my opinion, based on what I saw on the source code, we should return `TransactionExceptionResult.ROLLBACK`

**Comment by gsmet** [comment]
@pjgg I understand this was fixed by your PR? Should we close?

**Comment by pjgg** [comment]
This is talking about the migration guide(GitHub Wiki) not the Quarkus/doc snippets, so is pending to be updated.

For example:
```
// After
QuarkusTransaction.requiringNew()
        .timeout(10)
        .exceptionHandler((throwable) -> {
            if (throwable instanceof SomeException) {
               return RunOptions.ExceptionResult.COMMIT;
            }
            return RunOptions.ExceptionResult.ROLLBACK;
        })
        .run(() -> { ... });
QuarkusTransaction.requiringNew()
        .timeout(10)
        .exceptionHandler((throwable) -> {
            if (throwable instanceof SomeException) {
               return RunOptions.ExceptionResult.COMMIT;
            }
            return RunOptions.ExceptionResult.ROLLBACK;
        })
        .call(() -> { ... });
```


All the references to `RunOptions.ExceptionResult.ROLLBACK` are deprecated.

**Comment by geoand** [comment]
Let's close this as we've moved way beyond `2.16`
