### ISSUE TITLE
`ExtensionDescriptorMojoTest.shouldFlagMissingDependenciesInARealisticExtension` fails in Early Access JDK build

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#31528]
### Description

```
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< io.quackiverse:quarkus-fake-extension >----------------
[INFO] Building Quarkus - Fake extension - Deployment 999-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.quarkus:quarkus-core:jar:999-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.157 s
[INFO] Finished at: 2023-03-01T01:23:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project quarkus-fake-extension: Could not resolve dependencies for project io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT: Could not find artifact io.quarkus:quarkus-core:jar:999-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------< io.quackiverse:quarkus-fake-extension-deployment >----------
[INFO] Building Quarkus - Fake extension - Deployment 999-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.259 s
[INFO] Finished at: 2023-03-01T01:23:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project quarkus-fake-extension-deployment: Could not resolve dependencies for project io.quackiverse:quarkus-fake-extension-deployment:jar:999-SNAPSHOT: Could not find artifact io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.097 s <<< FAILURE! - in io.quarkus.maven.ExtensionDescriptorMojoTest
[ERROR] io.quarkus.maven.ExtensionDescriptorMojoTest.shouldFlagMissingDependenciesInARealisticExtension  Time elapsed: 3.528 s  <<< ERROR!
junit.framework.AssertionFailedError: 
Message format does not match expectations: 
Failed to resolve dependencies of io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT
```
https://github.com/quarkusio/quarkus/actions/runs/4298664366/jobs/7493035836

> [ERROR] Failed to execute goal on project quarkus-fake-extension: Could not resolve dependencies for project io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT: Could not find artifact io.quarkus:quarkus-core:jar:999-SNAPSHOT -> [Help 1]

Doesn't look right in terms of build reactor order. `extension-maven-plugin` is located under `independent-projects` and I don't think it should depend on core like that?
This issue does not pop up in regular CI because it builds everything initially, before running any tests.
In case this test has to stay like that we might need to adjust the EA build.

**Comment by radcortez** [comment]
Its @holly-cummins actually :)

https://github.com/quarkusio/quarkus/commit/c008d888347dde0836f07e0b238946d0a0b96ff7

**Comment by holly-cummins** [comment]
Hm, interesting. I agree that dependency isn't ideal - it's a tradeoff between making the test more realistic, and making the tests able to run independently. I'll have a look and see what I can do. We could move it to be an integration test, where depending on other things would be totally expected, but I don't think that's the right thing here because it's such a simple, low-level, test. I could soft-disable the test if the dependency is missing, or accept the 'dependency cannot be found' as a realistic complaint in that scenario. Or maybe I can just remove that dependency without sacrificing much realism.

**Comment by famod** [comment]
Hi @holly-cummins, any news on this? The very short term workaround would be to disable that test (which I could do later).

**Comment by holly-cummins** [comment]
Thanks for bringing this back to the top of my list, @famod. Attempting to reproduce now!

**Comment by holly-cummins** [comment]
PR submitted: https://github.com/quarkusio/quarkus/pull/32035

Once I put my mind to it, the fix was obvious. And about twelve characters. :) 

Sorry for the slowness! And thanks for doing the initial analysis of why it was failing, @famod .

**Comment by holly-cummins** [comment]
By coincidence, I was just working on a build that was also affected by this exact issue. I rebased against upstream, and my problem was fixed ... by my own fix. Karma. :)

**Comment by famod** [comment]
You should thank your previous me then 😉

**Comment by holly-cummins** [comment]
Definitely! If you hadn't diagnosed and chased, I'd still be scratching my head over the self-inflicted problem. :)
