### ISSUE TITLE
Missing newline characters in config error message

### ISSUE THREAD

**Issue by geertschuring** [quarkusio/quarkus#31536]
When running a Quarkus application in production profile with missing required configuration properties the error messages are not printed on individual console lines. Instead they are appended without newline characters in between, as seen in this output:

```
D:\Workspace\examples\person-service>java -jar target\person-service-1.0.0-SNAPSHOT-runner.jar
Failed to load config value of type class java.lang.String for: activemq.broker.urlFailed to load config value of type class java.lang.String for: activemq.broker.passwordFailed to load config value of type class java.lang.String for: activemq.broker.username
```

This is caused by 

https://github.com/quarkusio/quarkus/blob/41921fa6b550db709897ed5dcd3ef4d867ebeca6/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ConfigRecorder.java#L62-L63

What is missing here is an append of System.lineSeparator();

**Comment by manovotn** [comment]
@geertschuring can you please file that PR (https://github.com/geertschuring/quarkus/pull/1) against this Quarkus repo? It's currently against your fork.

**Comment by geertschuring** [comment]
Done: https://github.com/quarkusio/quarkus/pull/31545
