### ISSUE TITLE
Improving the sam.jvm.yaml

### ISSUE THREAD

**Issue by faermanj** [quarkusio/quarkus#31543]
### Description

The default sam.jvm.yaml template generated by the lambda extension contains two unnecessary spaces on the beggining of each line
```
  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
```
It would better be:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
```

### Implementation ideas

Fix that template.

**Comment by geoand** [comment]
@faermanj Thanks for reporting. Would you be willing to contribute the fix?
