### ISSUE TITLE
Support building `RestResponse<Void>` responses with resteasy-reactive response builder

### ISSUE THREAD

**Issue by mzuber** [quarkusio/quarkus#31541]
### Description

The `RestResponse.ResponseBuilder` class currently fixes the return type of the response to `RestResponse<Object>` when building an "empty" response with status type 204 (no content);

```java
RestResponse<Object> response = ResponseBuilder.noContent().build();
```

When implementing for example the delete methods of my REST API, this doesn't necessarily seem intuitive to me. I would expect to be able to use a return type `RestResponse<Void>` for API methods which return no content:

```java
@DELETE
@Path("{entityId}")
public RestResponse<Void> deleteEntity(@RestPath UUID entityId) {
    // Delete logic ...
    return ResponseBuilder.noContent().build();
}
```

At the moment it doesn't seem to be possible to influence the type parameter of the RestResponse when using the response builder in the way outlined above. It would be great if this would be possible.

### Implementation ideas

The first idea coming to mind would be to provide an overloaded `ResponseBuilder.noContent()` method which allows setting the desired type parameter for the builder via an explicit argument, e.g.

```java
RestResponse<Void> response = ResponseBuilder.noContent(Void.class).build();
```

**Comment by vukzeka** [comment]
@mzuber @geoand as a workaround(without using ResponseBuilder) is possible to have below form using `RestResponse.status(...)`

```
@DELETE
@Path("{entityId}")
public RestResponse<Void> deleteEntity(@RestPath UUID entityId) {
    // Delete logic ...
    return RestResponse.status(Status.NO_CONTENT);
}
```

**Comment by mzuber** [comment]
> Can't you use `ResponseBuilder.<Void>noContent().build()`?

Yes, that (of course) works. I now better understand the chosen type parameter naming (`T`, `IGNORED`) in the static methods of the `RestResponse.ResponseBuilder<T>` class. In case someone else stumbles on this question:
- In static methods like `public static <T> ResponseBuilder<T> create(StatusType status, T entity)` the type parameter <T> is inferred from the `entity` argument:
  ```java
  String foo = "foo";
  RestResponse<String> response = ResponseResponseBuilder.create(RestResponse.Status.CREATED, foo).build();
  ```
- In static methods like `public static <IGNORED> ResponseBuilder<IGNORED> noContent()` the type parameter <IGNORED> cannot be inferred from anything and needs to be explicitly stated if a return type other than `RestResponse<Object>` is desired:
  ```java
  RestResponse<Void> response = ResponseBuilder.<Void>noContent().build();
  ```
