### ISSUE TITLE
Scheduler - it's possible to declare two scheduled methods of the same name on the same class

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#31547]
### Describe the bug

More precisely, it's possible to declare a method with name `x` and (1) no parameters and (2)  with the `ScheduledExecution` parameter. E.g. `Alpha#foo()` and `Alpha#foo(ScheduledExecution)` . However, some internals use the `{declaringClass}#{methodName}` as a unique key.

### Expected behavior

I think that this should be forbidden and result in a build failure.

**Comment by machi1990** [comment]
> I think that this should be forbidden and result in a build failure.

+1, unless otherwise the `Scheduled#identity` is different.

**Comment by mkouba** [comment]
> > I think that this should be forbidden and result in a build failure.
> 
> +1, unless otherwise the `Scheduled#identity` is different.

Well, the `Scheduled#identity()` is bound to the trigger and a scheduled method can declare multiple triggers. So it's something a little bit different... but I think that you get my point ;-)

**Comment by machi1990** [comment]
> Well, the Scheduled#identity() is bound to the trigger and a scheduled method can declare multiple triggers. So it's something a little bit different... but I think that you get my point ;-)

Ah yes, you are right. Where I was coming from was that we could somehow know if the two methods with same name are different based on the `Scheduled#identity()` - forgetting the fact that a method can declare multiple of them. So, I am fine with just banning (throwing a build time error) for this kind of setup makes sense all the time.
