### ISSUE TITLE
Em dash not rightly encoded as form param type string as part of a MultipartForm

### ISSUE THREAD

**Issue by vanalex** [quarkusio/quarkus#31564]
### Describe the bug

Sending a MultipartForm with a Em dash in a string, it is not rightly encoded and appears as a ? char.

### Expected behavior

Em dash is rightly encoded.

### Actual behavior

Sending a MultipartForm with a Em dash in a string, it is not rightly encoded and appears as a ? char.

### How to Reproduce?

https://github.com/hantsy/quarkus-sandbox/tree/master/multipart

You can use this example and there is a test to check the multipartform. As an example you set the field test as
... 
given().formParam("test", "—")
...

### Output of `uname -a` or `ver`

Linux alex-workstation 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux alex@alex-workstation:~$ 

### Output of `java -version`

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 3.0.0.Alpha4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by geoand** [comment]
Can you try using [RESTEasy Reactive](https://quarkus.io/guides/resteasy-reactive#multipart) instead of RESTEasy Classic and see if it works?

**Comment by vanalex** [comment]
I will try it. Thanks for the quick answer.

**Comment by vanalex** [comment]
I have refactored it a bit to apply reactive as you
![Screenshot from 2023-03-03 14-35-17](https://user-images.githubusercontent.com/14924728/222733889-40ea28cb-b128-455e-8a60-f9748d7d0dc9.png)
 suggested, but still no luck.

**Comment by geoand** [comment]
Can you update the reproducer with your code?

**Comment by vanalex** [comment]
Here is a new reproducer cleaner than the previous one -> https://github.com/vanalex/quarkus-multipart-demo

**Comment by vanalex** [comment]
Forgot to mention. Thanks for your help again :)

**Comment by geoand** [comment]
Thanks. I'll try and have a look next week.

**Comment by geoand** [comment]
@vanalex I tried your latest sample and a lot of things do not compile. Can you please push an fixed version?

Thanks

**Comment by vanalex** [comment]
Hi, I am really sorry. Now it compiles.

**Comment by geoand** [comment]
Thanks for the updated sample. 

I checked and this is not a Quarkus issue, it happens because RestAssured is sending `charset=US-ASCII` as shown in this Wireshark capture:

![Screenshot from 2023-03-06 11-52-41](https://user-images.githubusercontent.com/4374975/223077162-7d137c79-ef65-4683-b85f-c9b6bf23bf0f.png)

See https://github.com/rest-assured/rest-assured/issues/844 for an example on how to configure RestAssured to use UTF-8

**Comment by vanalex** [comment]
Ok, thanks for your support. I will try to apply rest easy reactive firstly to our project and lets see if it fixes the enconding problem.
