### ISSUE TITLE
Spring Data API Extension not implementing repository function

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#31570]
### Describe the bug

I have a Base Repository where i extend from JpaRepository. Then i extend from my own BaseRepository to create an ItemBaseRepository. (Both annotated with @NoRepositoryBean). Finally i define my Repository by extending ItemBaseRepository.
The Problem is the custom functions defined in my own BaseRepository are not implemented they are still abstract. If you remove the ItemBaseRepository so that the ItemRepoistory directly extends from my BaseRepository it works.
With SpringBoot there are no issues when extending twice.

### Expected behavior

The functions should be implemented.

### Actual behavior

The functions are abstract.

### How to Reproduce?

[QuarkusJPATest.zip](https://github.com/quarkusio/quarkus/files/10879080/QuarkusJPATest.zip)

### Output of `java -version`

java 17

### Quarkus version or git rev

2.16.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/31574 fixes the issue
