### ISSUE TITLE
Automatic mapping of configured deprecated Hibernate ORM Dialects to the ORM 6 dialect + version

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#31588]
Extracted from #31475, quoting @gsmet:

> Dialect compatibility - Still undecided on this one, should we try to migrate people to the new dialects automatically or not? (should probably be moved to a separate issue at some point but might be part of this compatibility work so dropping it here for now)

Relates to #31474, where we'll expose a configurable min-db-version. We could use the configured dialect to infer that version, e.g. `org.hibernate.dialect.PostgreSQL10Dialect` would be `db-kind=postgresql` + `min-db-version=10.0`.

**Comment by Sanne** [comment]
I think this was a nice idea but if it comes very late compared to the migration to ORM6 it's of limited usefulness.

@yrodiere I'd consider closing this one, unless you have plans for it? We can always reopen things when new feedback emerges.

**Comment by yrodiere** [comment]
Right, we didn't have time to work on this, and now it's a bit late.

@gsmet I'll let you reopen if you think we can still add this to `quarkus update`, but personally I wouldn't make that a priority.
