### ISSUE TITLE
"My Second Quarkus Application" guide

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#31618]
### Description

We have "My first application" which is hello world, but there is a gap for a "My second application" guide. I had to prep a client demo today, and I found myself doing steps I think I've done a few times before, but not written down before. I needed something less trivial than https://quarkus.io/guides/getting-started, but more trivial than https://quarkus.io/guides/hibernate-orm-panache. This guide would be useful as a simple demo script and also for users who want to a written tutorial which showcases dev services.

What we want is something that allows users to experience the magic of "look, you're using postgres, but you didn't configure postgres .... amazing!"

Existing documentation about dev services is more of a reference, and assumes quite a lot of knowledge about them.  https://quarkus.io/guides/rest-data-panache showcases nice set of capability but it doesn't have any dev services content (which is sensible, since it's a guide about panache, not dev services). It also has a lot of 'new' code a user has to write, which is good as a rich reference, but for a quick tutorial/demo may be a bit too slow.

See discussion here https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.22My.20second.20application.22.20guide/near/339431983

### Implementation ideas

I have a skeleton set of instructions that I could polish up and then either collaborate with someone on the docs team to make comprehensible, or polish up fully myself. 

In the end I used [code.quarkus.io](http://code.quarkus.io/) to make an app with postgres, resteasy reactive, and panache. Then I added a few lines so that my rest endpoint would return my entity. The ideal was something where I didn't need to download any external code, and I could type my code changes without templates or copy and pasting.

**Comment by ingmarfjolla** [comment]
i'd like to help with something like this! I think something similar for extension writing would be very helpful as well

**Comment by holly-cummins** [comment]
Thanks, @ingmarfjolla! I've just created https://github.com/quarkusio/quarkus/pull/34401 as a skeleton, and would welcome your suggestions!

**Comment by holly-cummins** [comment]
The ink is barely dry on the merge, and I already need to refer to this guide. :)
