### ISSUE TITLE
Quarkus-kubernetes extension doesn't generate expected resources

### ISSUE THREAD

**Issue by jtama-op** [quarkusio/quarkus#3162]
Following the [Generating Kubernetes Resources](https://quarkus.io/guides/ap4k) doesn't generate any files in `target/wiring-classes/META-INF/kubernetes/`

**Expected behavior**
I expect the extension to generate sample kubernetes configuration file.

**Actual behavior**
Nothing is generated.

**To Reproduce**
Follow the guide to reproduce

**Configuration**
Nothing added to the generated code.

**Environment (please complete the following information):**
 - `uname -a` : ` 18.6.0 Darwin Kernel Version 18.6.0:` 
 - `java -version`: `openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)`

**Comment by gsmet** [comment]
@geoand I let you take a look at this one?

**Comment by geoand** [comment]
Sure thing, I'll check it out

**Comment by geoand** [comment]
@jtama-op I just followed the guide and everything worked as expected.

Essentially I created a project:

```
mvn io.quarkus:quarkus-maven-plugin:0.18.0:create     -DprojectGroupId=org.acme     -DprojectArtifactId=test     -DclassName="org.acme.rest.GreetingResource"     -Dpath="/greeting"     -Dextensions="kubernetes"
```

Then inside the project I did:

```
./mvnw package
```

which results in the following:

```
ls -l

...
-rw-r--r-- 1 gandrian gandrian 2367 Ιουλ 10 11:13 kubernetes.json
-rw-r--r-- 1 gandrian gandrian 1635 Ιουλ 10 11:13 kubernetes.yml
...
```

Are you doing anything different?

**Comment by jtama-op** [comment]
@geoand Ho i am sorry I add missread the guide, and was looking into `target/classes/META-INF/` very sorry.

Closing the bug.

**Comment by geoand** [comment]
No problem at all!
