### ISSUE TITLE
Report port already in use in production mode

### ISSUE THREAD

**Issue by rdebusscher** [quarkusio/quarkus#31628]
### Description

In Dev mode, there is a message when the port is already in use that you try to use within Quarkus.

In Production mode, no such message is shown and thus it can be hard to find out why your app is not working (status 404 on endpoints because it is another app :) )

**Comment by geoand** [comment]
Are you an error message (not necessarily the same one) does not show up?

**Comment by rdebusscher** [comment]
I retested with runnable Jar and Native compiled app and I do now get the message.

So I can't reproduce this. Not sure what happened.

Closing this.

**Comment by geoand** [comment]
Thanks for the update
