### ISSUE TITLE
Quarkus info metric

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#31636]
### Description

Similar to the [jvm.info](https://github.com/quarkusio/quarkus/blob/main/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/JVMInfoBinder.java#L11) metric, there could be a metric that exposes some information about the quarkus instance.

Ideas for potential useful information:
- Quarkus application version
- Quarkus platform version
- Quarkus package type (either jvm or native)

Potential use-case:
Imagine managing multiple quarkus applications in different versions. Visualizing the current version and package type using eg. grafana could be very useful.

### Implementation ideas

```java
package io.quarkus.micrometer.runtime.binder;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.binder.MeterBinder;

public class QuarkusInfoBinder implements MeterBinder {

    @Override
    public void bindTo(MeterRegistry registry) {
        Counter.builder("quarkus.info")
            .description("Quarkus version info")
            .tags("application_version", System.getProperty("quarkus.application.version", "unknown"),
                "platform_version", System.getProperty("quarkus.platform.version", "unknown"),
                "package_type", System.getProperty("quarkus.package.type", "unknown"))
            .register(registry)
            .increment()
    }
}
```

**Comment by geoand** [comment]
I am going to close this as we now have the [Info extension](https://quarkus.io/version/main/guides/getting-started#info-endpoint) which provides more information in a dedicated endpoint
