### ISSUE TITLE
Recent CORS changes broke requests with Origin: null

### ISSUE THREAD

**Issue by dteleguin** [quarkusio/quarkus#31631]
### Describe the bug

It is not unusual for the browser applications to send the `Origin: null` header in some cases (while in the rest of the cases the actual non-null `Origin` would be sent). These include, but are not limited to:
* form POST with `Referrer-Policy: no-referrer` (example: Keycloak)
* AJAX call from a page that has been created programmatically with `createDocument()`
(more exhaustive list [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin))

Such applications used to work just fine with `quarkus.http.cors=true` and `quarkus.http.cors.origins` defined. With the recent [change](https://github.com/quarkusio/quarkus/commit/e8865318eb5a9b14ffe7bc4dc603db5e3fb8765c), a request with `Origin: null` would get a 403 and "CORS Rejected - Invalid origin". It seems that `null` is not recognized as a valid value for `Origin` anymore.

### Expected behavior

CORS filter would allow the request having `Origin: null`

### Actual behavior

CORS filter rejects the request having `Origin: null` with a 403 and "CORS Rejected - Invalid origin"

### How to Reproduce?

```
docker run -p 8080:8080 \
  -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e QUARKUS_HTTP_CORS=true \
  -e QUARKUS_HTTP_CORS_ORIGINS=http://localhost:8080 \
  quay.io/keycloak/keycloak:latest start-dev
```

Navigate to admin console and try to log in. (Used to work with KC 20.0.2 and earlier on Quarkus 2.13.3.Final)

### Quarkus version or git rev

2.13.6.Final (and later)

**Comment by sberyozkin** [comment]
@dteleguin If the application needs to accept `Origin: null` then it has to enable it itself, you mentioned you already have the origins configured, so add `null` to the configured origins list if `null` is a valid Origin value. It was working before as an indirect consequence of the bug fixed in 2.13

**Comment by sberyozkin** [comment]
@dteleguin FYI, we have followed up with some updates related to the same origin check, i.e, if for example, we have `Origin: http://localhost:8080` which represents the current application's base address then it has to be accepted without users having to manually add such addresses to `quarkus.http.cors.origins`.
But I've just checked, `null` is certainly not accepted as an evidence this Origin is same host Origin request.

@stuartwdouglas @pmlopes @cescoffier @maxandersen What do you think ? Should we accept `null` as well in the same host origin check ? IMHO this is something that the actual application should add to the list of origins.

Note the 2.16 update where the wildcard support was removed OOB is not related to the reported problem. It is related to the fact a bug analyzed by Paulo was fixed

@dteleguin If Keycloak does need CORS support OOB then please consider adding and configuring the CORS filter at the startup without requiring the users to provider `null` as one of the valid origins, I agree it can be a bit scary for the users

**Comment by sberyozkin** [comment]
I don't know, given something  like https://portswigger.net/web-security/cors/lab-null-origin-whitelisted-attack, I wonder if it will be sound at all for Quarkus do it

**Comment by sberyozkin** [comment]
[@dteleguin Are there any other headers in the request that can help Quarkus decide that it is safe to accept null](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) discourages accepting null

**Comment by sberyozkin** [comment]
I think I can imagine some cases where it might be safe, but Quarkus does not know when it can be the case, which is why it seems reasonable to expect the application to make such a sensitive decision when it knows it can be accepted

**Comment by geoand** [comment]
Is there anything we need to do here?

**Comment by sberyozkin** [comment]
Let me close it, @dteleguin @pedroigor - if you feel we need to do some work around it - please reopen

**Comment by dteleguin** [comment]
I'm fine with this one being closed. Seems like not supporting "null" origin is better from the security perspective.

As for Keycloak, we had to use Quarkus CORS as a workaround for CORS issues with our custom code, but finally sorted that and got rid of Quarkus CORS.

For Keycloak users, I'd recommend to use the Keycloak's internal CORS implementation which is tailored to OAuth/OIDC; Quarkus CORS seems to be too permissive, and using it with Keycloak could introduce potential security holes.

**Comment by maxandersen** [comment]
Which version of Qurkus are you using ? We changed cors to be more strict thus would like to know which cases you believe we are not doing the right thing ?

**Comment by dteleguin** [comment]
@maxandersen after investigation I don't think Quarkus is doing anything wrong :)

We tried to use Quarkus CORS (which is really basic) with a complex software like Keycloak, and relied on Quarkus CORS implementation which became more strict. The problem was with that and not with Quarkus :)

**Comment by olawalejuwonm** [comment]
Hi.

Please what's thr advice? Set cors to null?
