### ISSUE TITLE
Allow third party extensions to avoid validating the default JAXB context

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#31646]
### Describe the bug

The change 46f348c85934b914f8d986f4f4535134e4ffba03 by @Sgitario has brought hard times to Quarkus CXF and Camel Quarkus. Basically all our CXF related tests fail, because duplicate JAXB classes seem to a normal situation in CXF. 

Here an example of the stack trace see when running [quarkus-cxf-integration-test-client](https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-client): 

```
Caused by: java.lang.IllegalStateException: Failed to configure JAXB context
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:395)
        at io.quarkus.jaxb.deployment.JaxbProcessor.setupJaxbContextConfig(JaxbProcessor.java:318)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://www.w3.org/2005/08/addressing}EndpointReferenceType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
        this problem is related to the following location:
                at org.apache.cxf.ws.addressing.EndpointReferenceType
                at public org.apache.cxf.ws.addressing.EndpointReferenceType org.apache.cxf.ws.addressing.ObjectFactory.createEndpointReferenceType()
                at org.apache.cxf.ws.addressing.ObjectFactory
                at protected java.util.List org.apache.cxf.ws.addressing.ReferenceParametersType.any
                at org.apache.cxf.ws.addressing.ReferenceParametersType
        this problem is related to the following location:
                at jakarta.xml.ws.wsaddressing.W3CEndpointReference

        at org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:83)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:421)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:255)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1115)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:144)
        at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:368)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:546)
        at io.quarkus.jaxb.deployment.JaxbProcessor.validateContext(JaxbProcessor.java:393)
        ... 10 more
```

In this particular case, both conflicting classes come through transitive dependencies of CXF:

* `jakarta.xml.ws.wsaddressing.W3CEndpointReference` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-rt-bindings-soap:4.0.0:jar:
        -> jakarta.jws:jakarta.jws-api:3.0.0:jar
```

* `org.apache.cxf.ws.addressing.EndpointReferenceType` comes via

```
io.quarkiverse.cxf:quarkus-cxf-integration-test-client:2.0.0-SNAPSHOT:jar:
        -> io.quarkiverse.cxf:quarkus-cxf:2.0.0-SNAPSHOT:jar:
        -> org.apache.cxf:cxf-rt-frontend-jaxws:4.0.0:jar:
        -> org.apache.cxf:cxf-core:4.0.0:jar
```

I doubt we can exclude the artifacts and I doubt we can exclude the classes via `quarkus.jaxb.exclude-classes`.

Advising all users of `camel-quarkus-cxf` and `quarkus-cxf` to always have `quarkus.jaxb.validate-jaxb-context=false` in their `application.properties` does not seem to be a good UX.

I think the best way forward would be to find a programmatic way of disabling the JAXB context validation. 

I see three options:

### B. Split quarkus-jaxb into quarkus-jaxb-core and quarkus-jaxb

quarkus-jaxb would contain the config, the properties, the validation and the default context bean

quarkus-jaxb-core would keep all the rest. 

quarkus-cxf would depend only on quarkus-jaxb-core. If quarkus-cxf users need to inject the default JAXB context, they are on their own to add quarkus-jaxb dependency and resolve the conflicts.

## Assessment:

I see C as rather problematic. I think it would be hard to find the right semantics (esp. how it would combine with `quarkus.jaxb.validate-jaxb-context=false/true`), keep it transparent enough for end users and even document comprehensibly.

If A is technically possible, we should go with A. What do others think?

This blocks 
* https://github.com/apache/camel-quarkus/issues/4603
* https://github.com/quarkiverse/quarkus-cxf/issues/730

**Comment by Sgitario** [comment]
To sum up, we're now validating the generated JAXBContext at build time, so users can fix this kind of failure before running the application, but the Quarkus CXF and Camel Quarkus extensions use third-party dependencies that produce an invalid JAXBContext and you can't fix this because you do need these dependencies. 

About the options you suggest:
- A. Validate the JAXB context only if some JAXBContext injection point is available in the user application.

I would not go in this direction because at the moment users want to use the JAXBContext and use one of your extensions, it would fail and users would not directly see how to address it. 

- C. Have some sort of ValidateDefaultJAXBContextBuildItem that would allow third-party...

Again, I would not go in this direction because users would miss this feature if they do want to use the generated JAXBContext. 

Therefore, option B looks good to me. However, I think it would be simpler to create a new build item to exclude the class that causes the conflict. But, on your side, you would need to produce this build time with the mentioned classes. 

Wdyt? @gsmet @ppalaga

**Comment by ppalaga** [comment]
> I think it would be simpler to create a new build item to exclude the class that causes the conflict. But, on your side, you would need to produce this build time with the mentioned classes.

I agree, this would be doable, but how can I as a developer of an extension wrapping third party libs know, which classes my users want in their default JAXB context? I frankly do not know which ones I should exclude. I am by no means a JAXB expert. Is there maybe some clear choice here? I'd spontaneously say this should be left up to end users. WDYT?

**Comment by Sgitario** [comment]
Yes, end users would need to use the following properties to ensure the generated JAXBContext is ok:
- quarkus.jaxb.validate-jaxb-context=false to disable the validation altogether
- quarkus.jaxb.exclude-classes=a.b.c to exclude the classes that cause the conflict

About how to know it. The JAXB exception should give users this information, so they can address it accordingly. 

I will create a pull request with the new build item.

**Comment by ppalaga** [comment]
I must admit I am not sure how can https://github.com/quarkusio/quarkus/pull/31651 help me to solve my problem? As I stated above, I have no idea which classes my end users may wish to exclude from the default JAXB context, so I can hardly make any use the new `ExcludeJaxbClassesToBeBoundBuildItem`.

I am trying to implement the option A and it looks quite promissing. Let me send a PR after I add some tests.

**Comment by Sgitario** [comment]
I thought in your case, you had identified the conflicts:

this problem is related to the following location:
                at org.apache.cxf.ws.addressing.EndpointReferenceType
                at public org.apache.cxf.ws.addressing.EndpointReferenceType org.apache.cxf.ws.addressing.ObjectFactory.createEndpointReferenceType()
                at org.apache.cxf.ws.addressing.ObjectFactory
                at protected java.util.List org.apache.cxf.ws.addressing.ReferenceParametersType.any
                at org.apache.cxf.ws.addressing.ReferenceParametersType
        this problem is related to the following location:
                at jakarta.xml.ws.wsaddressing.W3CEndpointReference

**Comment by Sgitario** [comment]
> And would not a user have the same issue if they inject the jaxbcontext?

By the way, we are considering splitting the extension into two. This is what you mentioned in the option 2. I think it's what have more sense if you dont need a jaxbcontext at all.

**Comment by ppalaga** [comment]
Yes, my extensions do not need the default JAXBContext bean to work properly. Splitting would be a valid solution. But still, more modules mean more maintenance so option A. might be better from that point of view.

**Comment by Sgitario** [comment]
Still users that want to use the jaxb extension and your extension would see this issue. So excluding for example, the class org.apache.cxf.ws.addressing.EndpointReferenceType might still be necessary

**Comment by ppalaga** [comment]
> Still users that want to use the jaxb extension and your extension would see this issue. So excluding for example, the class org.apache.cxf.ws.addressing.EndpointReferenceType might still be necessary

Yes, I agree the issue would pop up and I believe it should be the given user's responsibility to choose which of the two classes she wants in the default context. Or she may choose to create her own context instance where she puts only the classes she knows she needs.

Here is my attempt to implement the option A: https://github.com/quarkusio/quarkus/pull/31666 
I think I was able to cover it with tests properly and I prefer it to B.

**Comment by ppalaga** [comment]
To sum up my standpoint, I believe user apps should not fail at build time as long as they actually do not use the default JAXBContext.
