### ISSUE TITLE
Make the environment specific properties of Keycloak runtime overridable

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3164]
Right now, properties for keycloak are read in a `STATIC_INIT` block which means it is recorded and replayed from the build time value.
Most properties are fine at build time and executed in a static init block (bruned into the native image by substrate vm). But some like `auth-server-url` should be read at runtime as it can be overridden by users via e.g. environment variables.

I can imagine two options:

- move the static init to a `RUNTIME_INIT` block but that's the hacky way to do it
- create a specific config object with runtime phase (e.g. `@ConfigRoot(name = "..., phase = ConfigPhase.RUN_TIME)` and have the ability to take a keycloak instance and change the auth-server-url on the fly: that would be the best model
- an intermediary model would be to prepare the framework in the `STATIC_INIT` phase but finish the last wiring call including `auth-server-url` setting in the `RUNTIME_INIT` phase.

**Comment by gsmet** [comment]
@sberyozkin I think we should address this one sooner rather than later. Having all the Keycloak config build time is really something that won't fly.

(stumbled upon this while answering a user question)

**Comment by sebastienblanc** [comment]
Option 2 looks like the way to go, I can look into it but I will probably need your help. Is there for instance another extension that has the same approach which I could look at ?

**Comment by emmanuelbernard** [comment]
@sebastienblanc Infinispan does that. You can caht a bit with @karesti which had to dig on that spoecific subject a while back

**Comment by sberyozkin** [comment]
@sebastienblanc, @emmanuelbernard @gsmet, hi, here is a proposal:
- introduce `DefaultKeycloakDeployment` which will only hold `AdapterConfig` and pass it to `QuarkusDeploymentContext` and `QuarkusKeycloakConfigResolver` instead of the default `KeycloakDeployment`
- update `QuarkusKeycloakConfigResolver` to ask `DefaultKeycloakDeployment` to `getDeployment`
- `DefaultKeycloakDeployment.getDeployment` will check the properties which can be overridden at runtime, update the earlier recorded AdapterConfig if needed, create the default deployment

Does it work ?
Thanks

**Comment by emmanuelbernard** [comment]
I am not familiar with `DefaultKeycloakDeployment` and `QuarkusKeycloakConfigResolver` so I cannot comment :)

**Comment by sberyozkin** [comment]
@emmanuelbernard thanks, `DefaultKeycloakDeployment` was just an idea of how to encapsulate the runtime properties check away from `QuarkusKeycloakConfigResolver` which is used by the extension at the moment to provide the default (recorded) configuration; hoping we will make it work with @sebastienblanc :-)

**Comment by sberyozkin** [comment]
Hmm, I've just realized this specific plan will never work because of the module update

**Comment by xfh** [comment]
Hi, in the refactoring of the keycloak extension to `vertx-keycloak` by stuartwdouglas@d3be8351584689db2102c181fec2bdaca80205e0 the KeycloakConfig was set to `BUILD_AND_RUN_TIME_FIXED`. @stuartwdouglas could this issue be fixed by setting the ConfigPhase to `RUN_TIME`?

**Comment by sberyozkin** [comment]
@xfh FYI, we are also discussing with @stuartwdouglas the idea of renaming `vertx-keycloak` to something more generic: #4235

**Comment by mat2e** [comment]
Pleased to see, this one has already come up. I agree, most static settings are fine, but without `auth-server-url` as runtime-property we cannot easily address our dynamic environments.

**Comment by gsmet** [comment]
The properties in the new OIDC extension are now runtime overridable. This should fix this issue.
