### ISSUE TITLE
Integration Test Profile

### ISSUE THREAD

**Issue by jefrog1844** [quarkusio/quarkus#31673]
### Description

Please update the documentation found here:  https://quarkus.io/guides/getting-started-testing

For anyone interested in changing the profile used for integration testing, knowing the config used to specify the profile would be very helpful if they don't want to use the default of prod.

### Implementation ideas

Could the documentation be updated with a short section explaining how the profile is configured by default to prod and then how to change it:

quarkus.test.integration-test-profile=test

quarkus.test.integration-test-profile=prod (default)

**Comment by geoand** [comment]
@jefrog1844 would you like to contribute this documentation update?
The source to be updated can be found [here](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/getting-started-testing.adoc).
