### ISSUE TITLE
native image fails to start due to missing libfreetype.so.6 library (again)

### ISSUE THREAD

**Issue by s-seidel** [quarkusio/quarkus#31682]
Using Quarkus 2.16.4 with the jib builder (container build) as usual and I cannot get the container image to run. Both ubi and quarkus-micro images fail with
```
./application: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory
```

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by Karm** [comment]
@s-seidel The dependency is needed to perform server side fonts rendering/processing or image processing.

You can see what is needed e.g. over here:
https://github.com/quarkusio/quarkus/pull/31490/files#diff-ced281edcb76fa211af926ccc6c978a35c4173f79a80f86b43e28fa545a989d1

or over here:
https://github.com/quarkusio/quarkus-quickstarts/blob/development/awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native#L24

If you are into very minimal runtime image size, this might be helpful:
https://github.com/quarkusio/quarkus-quickstarts/blob/development/awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-micro

**Comment by geoand** [comment]
Thanks a lot for the info @Karm! 

I'm going to close the issue

**Comment by s-seidel** [comment]
> @s-seidel The dependency is needed to perform server side fonts rendering/processing or image processing.

We're not doing any of this. I guess I'll open an issue at the quarkus-tika project asking if the new native library usage was intentional.

**Comment by Karm** [comment]
@s-seidel, The usage might be subtle, opaque to the user. E.g. processing PDF file invoking something in Java2D font code...

**Comment by Karm** [comment]
If there is a case for more granular modularity of Tika usage in Quarkus Tika, it would be an issue for Quarkus Tika...
