### ISSUE TITLE
`gradle imageBuild` and `imagePush` is not supported for `container-image-jib`

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#31698]
### Describe the bug

quarkus gradle plugin in 2.16.x branch support building and pushing container image with specific tasks `imageBuild` and `imagePush` instead `-Dquarkus.container-image.build=true` and `-Dquarkus.container-image.push=true`. 
However `container-image-jib` does not support this gradle tasks.

### Expected behavior

`gradle imageBuild` will build container image with 'container-image-jib' extension.
`gradle imagePush` will push container image with 'container-image-jib' extension.

### Actual behavior

calling `gradle imageBuild` or `gradle imagePush` does not build/push image, log message about missing 'container-image-docker' extension.

### Output of `uname -a` or `ver`

Linux xxx 6.1.0-1007-oem #7-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  8 15:41:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Private Build 17.0.6+10-Ubuntu-0ubuntu122.04)
OS:           Linux 6.1.0-1007-oem amd64

**Comment by aloubyansky** [comment]
FYI @iocanel

**Comment by iocanel** [comment]
> FYI @iocanel
Thanks!
