### ISSUE TITLE
@CreationTimestamp and @UpdateTimestamp not working with MongoDB

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#31695]
### Describe the bug

We want to ensure Hibernate @CreationTimestamp and @UpdateTimestamp to work with mongodb with PanacheEntity.
We have extended from ReactivePanacheMongoEntityBase and do not see the autopopulation working and the fields get updated with whatever is passed on. Need to know how it can be implemented.

### Expected behavior

Reactive MongoDB must support @CreationTimestamp and @UpdateTimestamp

### Actual behavior

It doesnot support @CreationTimestamp and @UpdateTimestamp.

### How to Reproduce?

Create a panache entity and add a datetime field then it will show the issue with non autopopulation of the date fields annotated with @CreationTimestamp and @UpdateTimestamp

**Comment by geoand** [comment]
`@CreationTimestamp` and `@UpdateTimestamp` are Hibernate ORM specific annotations. 

Quarkus' MongoDB Panache support has nothing to do with Hibernate ORM, so these annotations are not expected to work.
