### ISSUE TITLE
Jackson JAXB annotations not working

### ISSUE THREAD

**Issue by barredmolar** [quarkusio/quarkus#31704]
### Describe the bug

JAXB annotations don't work in Quarkus even when registering JaxbAnnotationModule with ObjectMapperCustomizer.

### Expected behavior

Endpoint should return:
```
{
	"user": {
		"id": 1,
		"name": "John"
	}
}
```

### Actual behavior

Endpoint returns:
```
{
	"id": 1,
	"name": "John"
}
```

### How to Reproduce?

Reproducer: https://github.com/barredmolar/quarkus-jackson-jaxb-example

1. Call http://localhost:8080/hello
2. Observe the returned JSON

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1265]

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

**Comment by Sgitario** [comment]
What is happening is that by default Jackson is unwrapping the root element (your user entity) to the output. 
If you want to wrap the root element, you need to enable this feature by doing:

```java
@Singleton
public class RegisterCustomModuleCustomizer implements ObjectMapperCustomizer {

    public void customize(ObjectMapper mapper) {
        // Wrap root value
        mapper.enable(SerializationFeature.WRAP_ROOT_VALUE);
        // Support JAXB annotations
        mapper.registerModule(new JaxbAnnotationModule());
    }
}
```

And now, the output will be as you expect. 

Note that this is the expected behavior, so I think we can close this as won't fix. Wdyt @geoand ?

**Comment by geoand** [comment]
Yes I agree, let's close.

**Comment by geoand** [comment]
> I have tested this in WildFly, and it works correctly there.

That only means that Wildfly provides a different out of the box configuration for Jackson.
