### ISSUE TITLE
Quarkus OIDC Session Cookie not deleted in case of 401 unauthorized

### ISSUE THREAD

**Issue by sschellh** [quarkusio/quarkus#31717]
### Describe the bug

In case the verification of the oidc session cookie fails (for instance because the id token is malformed, expired, ...), then the server response with an http 401. however, the server is not deleting the session cookie. hence all subsequent requests also fail with 401 without the change for the user to recover. Only deleting the session cookie or waiting for it to expire is possible.

### Expected behavior

If the server response with http 401, then the server also deletes the q_session cookie.

### Actual behavior

If the server response with http 401, then the (invalid) q_session cookie is not deleted automatically.

### How to Reproduce?

1) Login into your web application
2) manipulate the session cookie
3) perform another activity in the web application

### Quarkus version or git rev

2.16.3.Final

**Comment by sberyozkin** [comment]
@sschellh It is definitely removed in the challenge method but the challenge method is not called if the existing ID token's signature/etc is invalid, I think in some branches we need to make sure the challenge is called leading to the session tojen removal and redirection to the OIDC provider
