### ISSUE TITLE
SAML with quarkus possible? How much functionality of Spring security is available?

### ISSUE THREAD

**Issue by dwagner320** [quarkusio/quarkus#31719]
I SAML with quarkus possible? I only found an two years old thread were it was stated that quarkus cannot do saml and probably it will not come in the future?

Also how much of Spring Security is available in quarkus, somewhere I read that only reduced spring security functionality is available? Is there a way to see what you can do and what not?

**Comment by dwagner320** [comment]
ok thank you for confirming. so theoretically saml would only work with serviceprovider with oicd to keycloak then from keycloak with saml to identityprovider?

**Comment by geoand** [comment]
That question is one for @sberyozkin :)

**Comment by sberyozkin** [comment]
@dwagner320 The only option I can think of is to use `quarkus-oidc` with Keycloak or other OIDC provider which can be configured to federate to SAML, example, https://www.keycloak.org/docs/latest/server_admin/#_protocol-mappers

**Comment by sberyozkin** [comment]
@dwagner320 This issue might get re-opened - at this time though it is unlikely SAML will be supported in Quarkus directly - instead we'd expect users interposing with Keycloak or other OIDC providers capable of federating to SAML providers
