### ISSUE TITLE
Re-activate MP Telemetry Tracing using the new OTel extension configs 

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#31721]
### Description

This is a follow up issue because of https://github.com/quarkusio/quarkus/pull/30033

**Comment by geoand** [comment]
@brunobat has this been delivered? If so, please close the issue and link the milestone it was first available in for users.

**Comment by brunobat** [comment]
No, This has not been delivered because MP Telemetry is behind in the OTel version. The TCK is no longer compatible with OTel 1.23+.
 We should keep moving forward and hope MP Telemetry catches up. However, we now support MP mandatory features like disable the TCK in runtime.

**Comment by brunobat** [comment]
We are not reactivating this in the future because MP Telemetry Tracing is too far behind on the OTel version.
