### ISSUE TITLE
There are two AddJobResourceDecorator decorators

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#31723]
### Description

There are two decorators for apparently the same thing: 
- [AddJobResourceDecorator.java](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddJobResourceDecorator.java) that is used to generate the Job resources from the configuration
- [AddJobResourceDecorator2.java](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddJobResourceDecorator2.java) that was added in https://github.com/quarkusio/quarkus/pull/29026 as a workaround to add init jobs

### Implementation ideas

We should merge both decorators or look for a more suitable name for the latter. 
wdyt @iocanel ?

**Comment by iocanel** [comment]
Feel free to merge them.

**Comment by Sgitario** [comment]
I think it makes more sense to rename the [AddJobResourceDecorator2.java](https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/AddJobResourceDecorator2.java) instead of merging as these two classes serve to a different purpose. 

https://github.com/quarkusio/quarkus/pull/31752
