### ISSUE TITLE
Reintroduce Gradle ITs in main tree

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3174]
I just caught a major regression in the Gradle plugin at the end of the release process.

This is definitely not something we want to happen again.

We need to reintroduce some Gradle IT. There is a PR here: https://github.com/quarkusio/quarkus/pull/2783 not sure if it is good (in any case, the ITs should be in the `integration-tests` directory).

@stalep @aloubyansky @geoand @garyttierney who can help on that?

**Comment by geoand** [comment]
I will try out the PR and see what happens

**Comment by geoand** [comment]
Added comments to #2783

**Comment by stalep** [comment]
I'm on PTO this and next week. I won't have much time to look at it until I'm back.

**Comment by gsmet** [comment]
Just got hit by yet another Gradle regression while releasing 0.21.0.

We really need to work on this.

**Comment by geoand** [comment]
What kind of Gradle regression was it this time?

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/3522

**Comment by geoand** [comment]
So it's actually blowing up on something that is a problem but we hadn't noticed it, interesting :)

**Comment by gsmet** [comment]
Yup. It would be interesting to notice it before having all the artifacts
pushed to Central :).

**Comment by gsmet** [comment]
@gastaldi @maxandersen if you're working on improving the Gradle support, this one is important.

**Comment by geoand** [comment]
I can also help out on this

**Comment by cescoffier** [comment]
Anything done on this issue? It's marked for 0.25.0, but I doubt it was fixed already.

**Comment by geoand** [comment]
@gastaldi have you done anything with this? I know I haven't :P

**Comment by gastaldi** [comment]
@geoand no, I'll have a look at that open PR

> @gastaldi have you done anything with this? I know I haven't :P

Me neither, I'll have a look at that open PR and see what is missing

**Comment by geoand** [comment]
Cool, thanks

**Comment by gsmet** [comment]
@gastaldi any chance you could have a look at some point? Not sure if you will have the cycles?

**Comment by gastaldi** [comment]
@gsmet sure, I'll have a look now.

**Comment by gastaldi** [comment]
Closing this as in https://github.com/quarkusio/quarkus/pull/5761 support for functional tests were added which IMHO should be enough. Reopen if needed.
