### ISSUE TITLE
Push Gradle properties to the configuration (again)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3176]
In https://github.com/quarkusio/quarkus/pull/3173 , we reverted the copy of Gradle properties to config because the Gradle properties contain null values and complex objects.

We could only push String keys and values.

But let's wait for https://github.com/quarkusio/quarkus/issues/3174 to be implemented.

**Comment by dmlloyd** [comment]
We might want to revise the whole thing (Maven side too) to only push String keys in the `quarkus.` namespace.

**Comment by geoand** [comment]
I think that makes a lot sense. If we don't apply such a filter, we will end up with a ton of properties in Gradle's case

**Comment by gsmet** [comment]
+1 from me too.

**Comment by geoand** [comment]
On a super simple sample project, I came up with 10+ properties whose value was an instance of String

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/issues/3177 so that we track the filter idea properly.
