### ISSUE TITLE
Ignoring existing 'persistence.xml' files do not ignore all executions

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#31766]
### Describe the bug

Related to: **Quarkus 3.0.0.Alpha5 and Hibernate ORM 6**

When I use config property `quarkus.hibernate-orm.persistence-xml.ignore` or System property `SKIP_PARSE_PERSISTENCE_XML` for ignore evaluation of `persistence.xml` files, there's a particular build step which still processes them. It means these `persistence.xml` files are not completely ignored, and IMHO, they should be.

Log shown even when the config property or the system property is set to true:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.Alpha2:build (default) on project keycloak-quarkus-server-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: A legacy persistence.xml file is present in the classpath, but Hibernate ORM is also configured through the Quarkus config file.
[ERROR] Legacy persistence.xml files and Quarkus configuration cannot be used at the same time.
[ERROR] To ignore persistence.xml files, set the configuration property 'quarkus.hibernate-orm.persistence-xml.ignore' to 'true'.
[ERROR] To use persistence.xml files, remove all 'quarkus.hibernate-orm.*' properties from the Quarkus config file.true
[ERROR]         at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:892)
[ERROR]         at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.configurationDescriptorBuilding(HibernateOrmProcessor.java:415)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

### Expected behavior

Evaluation of 'persistence.xml' files should be ignored after setting mentioned properties.

### Actual behavior

Evaluation of 'persistence.xml' files IS NOT ignored after setting mentioned properties.

### How to Reproduce?

1. Add `persistence.xml` file to your application
2. Also set config property in `application.properties` related to the Hibernate ORM (`quarkus.hibernate-orm.*`)
3. Set config property (`quarkus.hibernate-orm.persistence-xml.ignore=true`) system property (`-DSKIP_PARSE_PERSISTENCE_XML=true`)
4. Reaugment the server

### Output of `uname -a` or `ver`

Linux fedora 6.1.14-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.6 2023-01-17

### Quarkus version or git rev

3.0.0.Alpha5

**Comment by yrodiere** [comment]
The PR can't be the solution as it basically disables all persistence units (even the ones configured through `application.properties` as soon as you set `quarkus.hibernate-orm.persistence-xml.ignore=true`.

I think I'll need to have a closer look, in debug mode, to see what is going on in your case exactly. 

Is the reproducer still at https://github.com/mabartos/keycloak/tree/quarkus3-alpha5 ?

**Comment by yrodiere** [comment]
> Reaugment the server

That's probably the key here, as I don't think we test that.

**Comment by yrodiere** [comment]
See https://github.com/quarkusio/quarkus/pull/31767#discussion_r1132583030 ; the problem is related to a custom extension producing its own "synthetic" `persistence.xml` files:

> @yrodiere Oh, god. I've just found our custom build producer for `PersistenceXmlDescriptor`.
> 
> However, I'm not sure if it's the correct approach to only restrict producing the `PersistenceXmlDescriptor`s from `QuarkusPersistenceXmlParser.locatePersistenceUnits()`. IMHO, this fact should also be considered as in custom applications, there can be some additional `PersistenceXmlDescriptor` producers, right?
> 
> Or what's your input on this? (@yrodiere @Sanne @gsmet )

**Comment by mabartos** [comment]
The issue was caused by our extension steps processing and is outdated.

**Comment by yrodiere** [comment]
Thanks for updating the issue @mabartos!
