### ISSUE TITLE
Order of config alternations is not obvious

### ISSUE THREAD

**Issue by clochardpagan** [quarkusio/quarkus#3182]
Not sure, but may we need to reorder environment and system property checks. System property is something issued by user to force change in behaviour, and environment variables is a part of host system. So we can assume that if user starts application with some system configs that's his wish, if none - take what environment has, if it's also empty - let it be default.

[ProfileManager.java](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ProfileManager.java#L28)

```
public static String getActiveProfile() {
        String profile = System.getenv(QUARKUS_PROFILE_ENV);
        if (profile != null) {
            return profile;
        }
        profile = System.getProperty(QUARKUS_PROFILE_PROP);
        if (profile != null) {
            return profile;
        }
        return launchMode.getDefaultProfile();
}
```

Current code rejects system config in favor of environment variable.

Spent over 10 minutes to understand, that someone set QUARKUS_PROFILE to dev on staging server and all builds are failing to start because of it. If it is decided to be as it is, please write some clarification in docs.

**Comment by gwenneg** [comment]
Hi @clochardpagan.

I'm also more familiar with system properties taking precedence over environment variables than the current Quarkus profile resolution logic. There might be a reason why it was done that way in Quarkus, @stuartwdouglas will probably have this answer to this.

Anyway, the current behavior is documented in the [Quarkus application configuration guide](https://quarkus.io/guides/application-configuration-guide#configuration-profiles).

**Comment by stuartwdouglas** [comment]
My thinking was that for for cloud/containers this is the reverse, the system property is something that is build into your container image, and the environment variable is something that is explicitly set for the deployment.

That said I just realised that MP config uses the opposite rules so I will change it.

**Comment by gwenneg** [comment]
@stuartwdouglas I can take care of this if you want.

**Comment by stuartwdouglas** [comment]
Great
