### ISSUE TITLE
Opentelemetry sampler configuration ignored

### ISSUE THREAD

**Issue by enrico-niccoli** [quarkusio/quarkus#31832]
### Describe the bug

Hi!
I'm trying to modify the sampler configuration through application.properties because I need the "sampled" field to be always true.
I've tried to change these properties
`quarkus.opentelemetry.tracer.sampler`
`quarkus.opentelemetry.tracer.sampler.parent-based`
`quarkus.opentelemetry.tracer.sampler.ratio`
but they seem to be ignored because the application behavior is always the same. 
At the moment it seems that when my application reloads new code changes, the "sampled" field is set to "false" and each log  has traceId, span ecc to "000...00".

I'm doing something wrong? How can I assure that "sampled" will be always true?
Thanks

### Expected behavior

By changing the related properties in .properties, the behavior of the sampler varies

### Actual behavior

The sampler always behaves the same

### How to Reproduce?

1. Modify the properties related to the sampler
2. Make changes to the code to get a Quarkus reload
3. Observe if the logs have the "sampled" parameter populated in a manner consistent with what is set in application properties

### Output of `uname -a` or `ver`

Linux asset-00287 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.13.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by brunobat** [comment]
Hi @enrico-niccoli the valid values to [quarkus.opentelemetry.tracer.sampler](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.opentelemetry.tracer.sampler) 
are `on`,`off` and `ratio`... 'false' will not work

**Comment by enrico-niccoli** [comment]
Hi @brunobat , sorry I miswritten! I was referring to the "**sampled**" field in `quarkus.log.console.format` which is based, if I have not misunderstood, on the various properties of the sampler.
So I have "**sampled**" always to false after a reload and It seems that sampler properties are ignored

**Comment by geoand** [comment]
@enrico-niccoli if this is still a problem, please attach a sample application that exhibits the problematic behavior.

**Comment by geoand** [comment]
Closing as we did not receive a reproducer
