### ISSUE TITLE
inconsistent nullable handling when generating Graphql schema

### ISSUE THREAD

**Issue by lcareto** [quarkusio/quarkus#31845]
### Describe the bug

When using `?` Kotlin nullable types with `Uni`, the generated graphql schema set the nullable fields as required

eg. the following code
```kotlin
import io.smallrye.mutiny.Uni
import org.eclipse.microprofile.graphql.GraphQLApi
import org.eclipse.microprofile.graphql.Query
import org.eclipse.microprofile.graphql.Source
import javax.json.bind.annotation.JsonbCreator

data class Foo @JsonbCreator constructor(val bar: String?)

@GraphQLApi
class Example {
  @Query
  fun nullable(): Foo? = null

  @Query
  fun nullableItemInUni(): Uni<Foo?> = Uni.createFrom().nullItem()

  @Query
  fun nullableNestedItem(@Source foo: Foo): String? = foo.bar

  @Query
  fun nullableNestedItemInUni(@Source foo: Foo): Uni<String?> =
    foo.bar?.let { Uni.createFrom().item(it) } ?: Uni.createFrom().nullItem()
}

```

generates the following graphql schema

```graphql
type query {
  nullable: Foo
  nullableItemInUni: Foo!
  nullableNestedItem(foo: FooInput!): String
  nullableNestedItemInUni(foo: FooInput!): String!
}
```

#### Notes: 
a workaround is to annotate the query with the `io.smallrye.graphql.api.@Nullable` annotation

### Expected behavior

expecting the schema to be
```graphql
type query {
  nullable: Foo
  nullableItemInUni: Foo
  nullableNestedItem(foo: FooInput!): String
  nullableNestedItemInUni(foo: FooInput!): String
}
```

### Actual behavior

```graphql
type query {
  nullable: Foo
  nullableItemInUni: Foo! #WRONG
  nullableNestedItem(foo: FooInput!): String
  nullableNestedItemInUni(foo: FooInput!): String! #WRONG
}
```

### Output of `uname -a` or `ver`

Darwin Ls-MacBook-Pro.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (Amazon.com Inc. 17.0.1+12-LTS)
OS:           Mac OS X 13.1 x86_64

**Comment by jmartisk** [comment]
Thanks for reporting, I'll have a look into it

**Comment by jmartisk** [comment]
I think this will be quite tricky to implement due to how the Kotlin compiler works. The metadata about nullability of the type argument isn't stored directly in the class metadata, it's stored in a separate meta-annotation named `kotlin.Metadata` applied on the class where the type relevant method resides. 
That annotation, however, doesn't use a publicly defined format which would allow us to retrieve the nullability information - see https://stackoverflow.com/questions/36816521/is-the-format-of-the-data-held-in-kotlin-metadata-documented-anywhere so we can't reliably parse this information from a Jandex index. We would have to add a dependency on the `kotlinx-metadata-jvm` project, which I'm not sure is feasible.
Also merging metadata from Jandex with metadata obtained this way will be quite complex.. This will need some thinking..

**Comment by evanchooly** [comment]
Jetbrains provides an API for reading/writing that metadata [here](https://github.com/JetBrains/kotlin/tree/master/libraries/kotlinx-metadata/jvm).  I've not looked at the API too deeply so it might be not be a complete solution but perhaps it could us further down that road.

**Comment by jmartisk** [comment]
Yeah that's the `kotlinx-metadata-jvm` I mentioned. It kinda works, but I'm not sure about the potential impact of introducing this as a dependency, and how much reliable we can consider it (for future Kotlin versions) due to the metadata format being a private API...

**Comment by evanchooly** [comment]
oh, i missed that buried in the bottom.  my eye gravitated toward the SO link.  :)  apologies.

I think relying on that library is a smarter choice than trying to roll our own at least.  There's a reasonable expectation that Jetbrains would keep it current.  And I don't think the metadata changes all that much at this point.

**Comment by phillip-kruger** [comment]
If we only depend on it when building the schema metadata I think it's ok, as we do this in build time (that is why the schema creation is in a separate module in smallrye). So the kotlin dependency should never end up in runtime
