### ISSUE TITLE
Support for jakarta.enterprise.event.Startup

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#31841]
### Description

Hi everybody !
I am aware of io.quarkus.runtime.StartupEvent and I wonder if would be possible for quarkus to use/fire the [jakarta startup event](https://jakarta.ee/specifications/webprofile/10/apidocs/jakarta/enterprise/event/startup) instead of the quarkus custom one.
Is there a reason for the custom event ?

Thank you in advance

### Implementation ideas

Just fire  jakarta.enterprise.event.Startup instead of io.quarkus.runtime.StartupEvent ... or maybe both of them ?

**Comment by mkouba** [comment]
`jakarta.enterprise.event.Startup` is supported since 3.0.0.Alpha5. In fact, the `StartupEvent` extends the `jakarta.enterprise.event.Startup`.

**Comment by amoscatelli** [comment]
Thank you !

**Comment by Ladicek** [comment]
@mkouba is exactly right. The reason for the custom event is that `jakarta.enterprise.event.Startup` only exists since CDI 4.0, while `io.quarkus.runtime.StartupEvent` has existed long before that.
