### ISSUE TITLE
EventBusCodecProcessor does not accept Java Records

### ISSUE THREAD

**Issue by lordvlad** [quarkusio/quarkus#31861]
If you want to use `@ConsumeEvent` annotation, currently you cant use Java Records. Automatic and explicit codec registration fails.

Current workaround is to accept a `Message<MyRecord>` instead. 

Hunch: the processor explicitely expects `Type.Kind.CLASS` or `PARAMETERIZED` object, maybe records fall through here?

https://github.com/quarkusio/quarkus/blob/71ba94e9bff54b73bb2ee90e39321a0e8bfc5eed/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusCodecProcessor.java#L177

**Comment by geoand** [comment]
Thanks for checking.

Have you actually run into this problem in practice or are you deducing it won't work based on reading the code?

**Comment by lordvlad** [comment]
Ran into this in practice, hence the workaround. The linked line is
admittedly only a hunch which would require investigation.

**Comment by geoand** [comment]
Can you post the exact error you are getting?

**Comment by lordvlad** [comment]
I've since moved on to using CDI. I tried to reproduce it now but for the love of god I cannot reproduce this issue :(
I'm going to close this and reopen should I ever encounter this again.
