### ISSUE TITLE
Body size > 8KB are not returned from quarkus + Azure Function application

### ISSUE THREAD

**Issue by franden** [quarkusio/quarkus#31871]
### Description

We are developing an quarkus applications which will run as Azure Function. The project was created according to the description: https://quarkus.io/guides/azure-functions-http .We are using `quarkus-resteasy` to be able to use JAX-RS specification for coding. 

The application produces response body which can be greater the 8KB, but it is not a problem if the application is started in dev mode with e.g. `mvnw quarkus:dev`. If the application is started with with Azure Functions Core Tools or deployed zu Azure, it do not respond anymore if the request response exceeds the size of 8KB. 

If `quarkus-undertow` is **in additional** is added to the `pom.xml` file, the application hangs only if the body size exceeds 16KB.

The issue does not appear if:
1. `quarkus-funqy-http` is used in the application
2. only Azure APIs are used (without quarkus) to create the function  

### Expected behavior

Bodies greater then 8KB  can be returned from quarkus + Azure Function application

### Actual behavior

Bodies greater then 8KB can NOT be returned from quarkus + Azure Function application. The application hangs.

![image](https://user-images.githubusercontent.com/20822716/225361595-cd958a74-53a3-422d-a907-0283263bd75b.png)

### How to Reproduce?

I created an example which can be use to reproduce the issue: https://github.com/franden/quarkus-azure-fn-issue-8k-body
This example creates an endpoint which produces a response with a string length depending on the input parameter.

1. install Azure Functions Core Tools
2. `git clone https://github.com/franden/quarkus-azure-fn-issue-8k-body`
3. `mvnw clean package azure-functions:run -DskipTests=true -DenableDebug`
4. `curl http://localhost:7071/api/hello/getString?times=79 --get -v`
The last line will let the application produce and return a string with length of 8295 Bytes.

`curl http://localhost:7071/api/hello/getString?times=78 --get -v` will work, because it produces a string with length 8190 Bytes

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.2604]

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**Comment by franden** [comment]
> Might be an issue with azure functions itself.

I pasted the link to the example how to reproduce the issue. The example is based on the quarkus sample project which will be generated with the command described [in the official quarkus quide](https://quarkus.io/guides/azure-functions-http) The only method I added was to the resource is to generate a String with a dedicated length an return as a body. 
```java
 @Path("getString")
    @GET
    public String getString(@QueryParam("times")@DefaultValue("1") Integer times) {
        String basicString = "123456789asdfghjkl3245ffffff23t4rg4rt45zrt57h5g4jhg54kk4jj5k4hj3lk45jh4l5hjk4öl5kjl4ö5jk3lö453lkä4lö";
        StringBuilder sb = new StringBuilder();
        for (int i=0; i<times;i++ ) {
            sb.append(basicString);
        }
        String finalString = sb.toString();
        Logger logger = LoggerFactory.getLogger(getClass());
        logger.info("Built string with {} chars. bytes: {}",finalString.length(), finalString.getBytes(StandardCharsets.UTF_8).length);

        logger.info("java.version: " + System.getProperty("java.version"));
        return finalString;
    }
```
Which issue could it have?

In additional 
1. the issue does not appear if only Azure APIs are used (without quarkus) to create the function 
2. the issue does not appear if quarkus funqy is used

**Comment by franden** [comment]
I set the values to higher value but the issue is still remaining :-(
```
quarkus.http.limits.max-chunk-size=50000K
quarkus.http.limits.max-body-size=50000K 
```

@patriot1burke  Could you reproduce the issue? Do you have any other ideas to fix the issue?

**Comment by patriot1burke** [comment]
I'll get back to you later today.  I'll need to reproduce and dive in further.

**Comment by geoand** [comment]
Does the same behavior occur when `quarkus-resteasy-reactive` is used? My guess is that it does not change things, just wanted to be sure

**Comment by geoand** [comment]
Thanks for the updated information, that's very useful

**Comment by phuckn2015** [comment]
I faced this problem. When the issue fixed, plz mention me.

**Comment by franden** [comment]
we now migrated our Azure function to funqy to avoid the issue. The functionality of funqy seems to be very limited, I don't think that we can use it for production. 
This bug is a show stopper in our project to for usage of Qaurkus + Azure function. 
@geoand , @patriot1burke: can you somehow estimate the priority of this issue and when it probably will be fixed?

**Comment by geoand** [comment]
I think @patriot1burke was looking into it
