### ISSUE TITLE
Test and document default storage change for `OffsetTime` in Hibernate ORM 6

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#31898]
### Description

If https://hibernate.atlassian.net/browse/HHH-16287 gets addressed before 6.2, this means a change in behavior when persisting OffsetTime, except when using the `normalized` timezone storage (the default one).

We should test it (see `io.quarkus.hibernate.orm.mapping.AbstractTimezoneDefaultStorageTest` and subclasses) and document a migration path (see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#property-sql-type, we'll have to add something about `OffsetTime`). We might want to update the 5.6 compatibility tests as well, see `integration-tests/hibernate-orm-compatibility-5.6`.

**Comment by gsmet** [comment]
@yrodiere did you sort that out? I think I have seen related commits but not sure it's this exact thing.

**Comment by yrodiere** [comment]
@gsmet Yes it's on my todo list. I need to add tests, that's all.
