### ISSUE TITLE
Hibernate reactive MySQL - underlying connection lost unexpectedly.

### ISSUE THREAD

**Issue by anar-orujov** [quarkusio/quarkus#31892]
### Describe the bug

I use Hibernate Reactive Panache and developed small microservice according to official Quarkus tutorials. It usually works fine, but randomly I get the following error:

**io.vertx.core.impl.NoStackTraceThrowable: Fail to read any response from the server, the underlying connection might get lost unexpectedly.**
My problem is similar to https://github.com/quarkusio/quarkus/issues/14608. It seems that the problem is solved for PostgreSQL library, but still exists for MySQL client.

I use the latest Quarkus version, Hibernate Reactive Panache and MySQL client. I use the following dependencies for database connection:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-reactive-mysql-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-reactive-panache</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-flyway</artifactId>
</dependency>
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-mysql</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-mariadb</artifactId>
</dependency>
```

And I have the following configurations:

```
quarkus.datasource.username = user
quarkus.datasource.password = pass
quarkus.datasource.reactive.url = vertx-reactive:mysql://mysql-server:3306/mydb?useCompression=True&useUnicode=yes&characterEncoding=utf8&serverTimezone=UTC
quarkus.datasource.reactive.max-size = 20
quarkus.datasource.reactive.idle-timeout = 5M
quarkus.datasource.reactive.cache-prepared-statements = true
quarkus.datasource.reactive.reconnect-attempts = 5
quarkus.datasource.reactive.reconnect-interval = PT0.3S
quarkus.datasource.jdbc = false
quarkus.datasource.health.enabled = false
```

I also had the same random problem before configuring connection pool properties.

### Expected behavior

The connection should be validated (maybe by a query), before return an available connection.

### Actual behavior

An end-user could get a connection that is not available anymore.

### How to Reproduce?

The problem happens randomly for the simple GET request. Sometimes it returns successful result, sometimes throws error. I can't reproduce the error.

### Output of `uname -a` or `ver`

5.15.0-60-generic x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.16.4.Final

**Comment by Sanne** [comment]
cc/ @tsegismont

**Comment by tsegismont** [comment]
> It seems that the problem is solved for PostgreSQL library, but still exists for MySQL client.

@anar-orujov the pool `idle-timeout` config properties applies to all reactive SQL clients (it's a pool level property)

https://github.com/eclipse-vertx/vertx-sql-client/blob/883a144f37c848a5bdea785aff89602d4650dfeb/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/PoolImpl.java#L79-L85

> `quarkus.datasource.reactive.idle-timeout = 5M`

Can you try `quarkus.datasource.reactive.idle-timeout = PT5M` ? I am not sure `5M` is a valid duration value.

And perhaps `5M` is too big in your system, maybe a lower value would help (you need to know how the proxy / firewalls between your application and your database are configured to determine an optimal value).

**Comment by anar-orujov** [comment]
@tsegismont thanks for your response, I'll check idle-timeout with lower values, then will share the result.

**Comment by anar-orujov** [comment]
@tsegismont Decreasing the `idle-timeout` value helped to solve the problem. Also, I added `PT` in front of the duration.

Thank you very much for your help.
