### ISSUE TITLE
[2.16.4] CDI fails when the OpenAPI extension is added to the project

### ISSUE THREAD

**Issue by roguexz** [quarkusio/quarkus#31923]
### Describe the bug

Configuration data is no longer being injected when the OpenAPI plugin is added to the project. This was working properly in the 2.15.x line.

### Expected behavior

CDI should work as advertised and extensions should play nice with each other 🙂 
The reproducer tests should work well

### Actual behavior

Configuration data is not being injected into beans when the OpenAPI extension is added

### How to Reproduce?

Reproducer: Clone this repository: https://github.com/roguexz/quarkus-sample/tree/3b7ea0293f5206a231ba0d4c19161637441b41d3

**Steps:**
* Run `./gradlew clean test`. You will observe that the tests are failing
* In `build.gradle` comment the OpenAPI extension and run the command again, you will observe that the test passes properly

### Output of `uname -a` or `ver`

Darwin xxxxxx 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+20-SA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+20-SA (build 11.0.17+8-LTS, mixed mode)

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

./gradlew --version

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.17 (Azul Systems, Inc. 11.0.17+8-LTS)
OS:           Mac OS X 13.2.1 x86_64

**Comment by gsmet** [comment]
@EricWittmann @Ladicek @mkouba I'm not sure if it's an OpenAPI issue or a CDI issue.

**Comment by mkouba** [comment]
> @EricWittmann @Ladicek @mkouba I'm not sure if it's an OpenAPI issue or a CDI issue.

I can take a look...

**Comment by mkouba** [comment]
It seems that something from the `quarkus-smallrye-openapi` brings in the `org.eclipse.microprofile.config:microprofile-config-api:3.0` which is built on top CDI 3.0 (which includes the `javax` to `jakarta` rename) but Quarkus 2.16 requires CDI 2.0. As a result the `org.eclipse.microprofile.config.inject.ConfigProperty` is not recognized as a CDI qualifier and the build process itself is kind of "broken". My gradle-fu is not sufficient to find out more...

**Comment by Ladicek** [comment]
As @mkouba correctly diagnosed, this is a dependency convergence problem. If you use `implementation enforcedPlatform("io.quarkus:quarkus-bom:$VERSION_QUARKUS")`, which is what Quarkus recommends, it will work too.

**Comment by mkouba** [comment]
> As @mkouba correctly diagnosed, this is a dependency convergence problem. If you use `implementation enforcedPlatform("io.quarkus:quarkus-bom:$VERSION_QUARKUS")`, which is what Quarkus recommends, it will work correctly.

I wonder if this should be mentioned in the docs? I've only found [this](https://quarkus.io/guides/gradle-tooling#publishing-your-application). And not everyone is using CLI/maven to create a project skeleton.

**Comment by roguexz** [comment]
Thank you for looking at it @mkouba. I can confirm that the builds are working well on my end after enforcing the platform. Eagerly looking forward to migrating to Quarkus 3.x line.

**Comment by mkouba** [comment]
> > And not everyone is using CLI/maven to create a project skeleton.
> 
> But code.quarkus.io also adds it, right?

Yes, it does. So that means that we have majority of users covered.

Maybe it would make sense to add a "Gradle configuration" section in the docs that would contain the `implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")`, similar to [Maven configuration](https://quarkus.io/version/main/guides/maven-tooling#build-tool-maven) that shows the bom dependency.

In any case, I've removed the area/arc label as it's not an ArC issue.

**Comment by geoand** [comment]
Is this still an issue with Quarkus 3.2?

**Comment by geoand** [comment]
Closing for lack of feedback
