### ISSUE TITLE
Quarkus 3.0.0.Alpha5+ Vert.x HTTP returns a 405 when there is no resource found

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#31928]
### Describe the bug

Quarkus 3.0.0.Alpha5 and 6 vertx http returns a 405 when there is no resource found instead of a 404 in previous versions (Alpha4 and before.

**I am not sure if it's a bug or an expected change.**

### Expected behavior

Return a 404 when there is not resource on this path.

### Actual behavior

Return a 405 when there is not resource on this path.

### How to Reproduce?

https://github.com/ia3andy/reproducer-405

Run the test and switch the version of Quarkus, the test passes on Alpha4 but not on Alpha5

**Comment by ia3andy** [comment]
@vietj @tsegismont  did something change in Vertx?

**Comment by geoand** [comment]
cc @cescoffier

**Comment by ia3andy** [comment]
it seems the version of vertx hasn't changed `4.3.7` so this is not a Vertx change (AFAIK)

**Comment by ia3andy** [comment]
cc @phillip-kruger I see you've been actively editing the vertx-http extension

**Comment by cescoffier** [comment]
We had something like this when we started the new dev ui. I was thinking we fixed it. 

Basically 405 is correct, because somewhere this is a route accepting any path but setting a method. Which means that even if there are no resources, there is a matching route. So 405 is correct... I know it's disturbing.

The fix would be to investigate which route does match.

**Comment by tsegismont** [comment]
> @vietj @tsegismont did something change in Vertx?

I don't believe so.

**Comment by ia3andy** [comment]
> @ia3andy have you tried `Alpha6`?

Alpha6 is also 405

**Comment by cescoffier** [comment]
@ia3andy I would add that it has always been the case, just that we didn't have such a route. It's the correct behavior from a pure HTTP standpoint. It can come from anywhere, as soon as a route without a path but with a method is added.

Try in prod mode instead of dev mode, that would help identify the route.

**Comment by ia3andy** [comment]
> We had something like this when we started the new dev ui. I was thinking we fixed it.
> 
> Basically 405 is correct, because somewhere this is a route accepting any path but setting a method. Which means that even if there are no resources, there is a matching route. So 405 is correct... I know it's disturbing.
> 
> The fix would be to investigate which route does match.

405 means "Method not allowed", While 404 is "Not found", IMO, 404 seems to be a better fit to a "Resource not found" no?

**Comment by cescoffier** [comment]
No @ia3andy, it's found! That's the problem, there is a route matching. So, it's not "not found", it's found but for another method. So, 405 is correct.

**Comment by ia3andy** [comment]
> No @ia3andy, it's found! That's the problem, there is a route matching. So, it's not "not found", it's found but for another method. So, 405 is correct.

Ok you mean, 405 is correct from the Vertx standpoint, but from a user standpoint, it is not right?

**Comment by cescoffier** [comment]
Well, it depends, from the application code, it's correct.

**Comment by ia3andy** [comment]
So we have different behavior in dev/test/prod which is definitively a bug (whatever code is meant to be used)

**Comment by cescoffier** [comment]
so, there is a route added in dev mode, which might be in the new dev UI, or anywhere else. 

Note that, if the user adds a filter, you will have a 405. So, don't base your logic on that.

**Comment by ia3andy** [comment]
> so, there is a route added in dev mode, which might be in the new dev UI, or anywhere else.
> 
> Note that, if the user adds a filter, you will have a 405. So, don't base your logic on that.

I think it should be consistent, if having a Filter change the behavior to a 405, then at least it consistent across envs. 
Still IMHO, this is quite disturbing that adding a Filter is changing the behavior.

**Comment by cescoffier** [comment]
Well, that's the HTTP spec.

**Comment by ia3andy** [comment]
I am reading the spec to find a mention of this, I haven't found it yet.

**Comment by cescoffier** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405 - it's precisely the case, it matches a resource but for another method.

**Comment by ia3andy** [comment]
From an Application point of view, there is no Resource that match the request, I don't see why having a Filter actually changes that. Also when there is no resources and no filter, it seems it should also be a 404: 

[15.5.5. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.5)[404 Not Found](https://www.rfc-editor.org/rfc/rfc9110.html#name-404-not-found)
The 404 (Not Found) status code indicates that the origin server did not find a current representation for the [target resource](https://www.rfc-editor.org/rfc/rfc9110.html#target.resource) or is not willing to disclose that one exists. A 404 status code does not indicate whether this lack of representation is temporary or permanent; the [410 (Gone)](https://www.rfc-editor.org/rfc/rfc9110.html#status.410) status code is preferred over 404 if the origin server knows, presumably through some configurable means, that the condition is likely to be permanent.

A 404 response is heuristically cacheable; i.e., unless otherwise indicated by the method definition or explicit cache controls (see [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc9111#section-4.2.2) of [[CACHING](https://www.rfc-editor.org/rfc/rfc9110.html#CACHING)]).

[15.5.6. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.6)[405 Method Not Allowed](https://www.rfc-editor.org/rfc/rfc9110.html#name-405-method-not-allowed)
The 405 (Method Not Allowed) status code indicates that the method received in the request-line is known by the origin server but not supported by the [target resource](https://www.rfc-editor.org/rfc/rfc9110.html#target.resource). The origin server MUST generate an [Allow](https://www.rfc-editor.org/rfc/rfc9110.html#field.allow) header field in a 405 response containing a list of the target resource's currently supported methods.

A 405 response is heuristically cacheable; i.e., unless otherwise indicated by the method definition or explicit cache controls (see [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc9111#section-4.2.2) of [[CACHING](https://www.rfc-editor.org/rfc/rfc9110.html#CACHING)]).

**Comment by ia3andy** [comment]
Ok I just tested with NodeJS express and it returns a 404 even when there are filters.

**Comment by gsmet** [comment]
I agree with @ia3andy that the current behavior is incorrect from a user point of view.

Having all non existing resources returning a 405 in dev mode and a 404 in prod mode is not a behavior we want.

It might be the behavior we expect given the code we have, but that's not the behavior we want.

**Comment by ia3andy** [comment]
> > Also when there is no resources and no filter, it seems it should also be a 404
> 
> Yes, but that's not the case here. There is a resource (a filter is a resource, a route is a resource).

But maybe this is wrong to assume that a filter or a route is a resource from the Application standpoint

**Comment by cescoffier** [comment]
> Having all non existing resources returning a 405 in dev mode and a 404 in prod mode is not a behavior we want.

I agree with that. I'm just trying to explain that 405 is right here in this case. The bug is not 405, the bug is the route that match. We now need to find that route. Unfortunately, I don't have the time to do it, as @ia3andy has the reproducer, it would be great if he can tell us which routes are registered. Just look at the router and iterate over the routes, and print the path and method (be careful both can be null). 

>  Ok I just tested with NodeJS express and it returns a 404 even when there are filters.

node.js filters != filters we have. Our filters are routes, in node, they are just functions (so they do not match a request).

**Comment by ia3andy** [comment]
> > Having all non existing resources returning a 405 in dev mode and a 404 in prod mode is not a behavior we want.
> 
> I agree with that. I'm just trying to explain that 405 is right here in this case. The bug is not 405, the bug is the route that match. We now need to find that route. Unfortunately, I don't have the time to do it, as @ia3andy has the reproducer, it would be great if he can tell us which routes are registered. Just look at the router and iterate over the routes, and print the path and method (be careful both can be null).

on it!

> 
> > Ok I just tested with NodeJS express and it returns a 404 even when there are filters.
> 
> node.js filters != filters we have. Our filters are routes, in node, they are just functions (so they do not match a request).

IMO, it seems to be internal matters and shouldn't affect the application behavior but this is another subject. Let's first, fix the Route issue.

**Comment by ia3andy** [comment]
I believe I've found the commit which changes the behavior:
https://github.com/quarkusio/quarkus/commit/8cac0e2c86695f436f6a4299dc9b450c937331c4

**Comment by gsmet** [comment]
Well, the problem is that we need to know the route that catches everything.

As @cescoffier the behavior is expected because of this commit but we need to find out which route is catching the non existing resources.

**Comment by ia3andy** [comment]
Ok so the behavior is expect as the test is using a POST request and not a GET, GET returns a 404.
I've also tested with RR  and `quarkus.resteasy-reactive.path=/api` and POST on a `/api/something` is a 404.

So we are fine, the change of behavior is a fix and not a bug.

**Comment by ia3andy** [comment]
Just a note that it is expected application wise to have a 405 on POST as we have a static file server by default on GET/HEAD only.

**Comment by ia3andy** [comment]
Also note that if I remove the META-INF/resources, I also get a 404 when doing a POST which makes total sense

**Comment by gsmet** [comment]
I don’t think we got to the bottom of this tbh. It’s still not normal that the behavior is different between dev and prod. We shouldn’t have a catch all in dev mode.

**Comment by ia3andy** [comment]
> I don’t think we got to the bottom of this tbh. It’s still not normal that the behavior is different between dev and prod. We shouldn’t have a catch all in dev mode.

You are right, I went to the bottom. I intended to edit that comment when back (I went for lunch):
https://github.com/quarkusio/quarkus/issues/31928#issuecomment-1473449029

So we are consistent across envs.

**Comment by ia3andy** [comment]
@gsmet  The only question that remains is, do we want the Static Handler to catch all GET and HEAD methods on all paths when active (even when there is no static resource behind a given path).

**Comment by ia3andy** [comment]
Something weird is that in my original Quinoa test (a `QuarkusDevModeTest` which detected the behavior change), I don't have a `META-INF/resources` but there are `AdditionalStaticResourceBuildItem` for the dev-ui making the behavior change.

I wonder why it's behaving differently when running a normal app in dev mode (the StaticResourcesRecorder is not added)
