### ISSUE TITLE
Add support for TLS insecure option in opentelemetry oltp exporter

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#31941]
### Description

It would be convenient to support for development:
```
quarkus.opentelemetry.tracer.exporter.otlp.tls.insecure=true
```

**Comment by brunobat** [comment]
What would be the expected behaviour.
Could you please provide an example?

**Comment by vsevel** [comment]
hello, the expected behavior would be to support `https` when exporting spans to the apm server, but not check the certificate presented by the apm.

currently, if I do not add the target certificate into the truststore, I get:
```
2023-03-20 09:56:14,505 ERROR [io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter] (OkHttp https://the-apm-server....com:8200/...) Failed to export spans. The request could not be executed. Full error message: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

the behavior is the same even if I set:
```
quarkus.tls.trust-all=true
```

the only way to get the spans to get sent to the apm is to configure the truststore `-Djavax.net.ssl.trustStore=...`
for dev it would be convenient to connect to the apm and not check its certificate.

**Comment by brunobat** [comment]
I understand now. Makes sense to me.
We need to work on the exporter, in order to remove OkHttp, for multiple reasons. 
Will consider this issue then.

**Comment by brunobat** [comment]
@geoand would you like to pick this one up?

**Comment by geoand** [comment]
I'll have a look next week

**Comment by geoand** [comment]
I think it will be pretty easy as we completely control the export process now (since we have removed the OkHttp exporter)

**Comment by geoand** [comment]
@vsevel would you like to give #35062 a try?

**Comment by vsevel** [comment]
sure. give me a bit of time

**Comment by geoand** [comment]
👌

**Comment by vsevel** [comment]
@geoand I confirm this works, however `quarkus.tls.trust-all` is a build time config property. correct?
this is not very useful, as we typically want to disable tls on a local test, but not in the other envs.
it would be nice to have a dedicated oltp tls property.

**Comment by geoand** [comment]
Thanks for checking!

You can override test specific properties, no?

**Comment by vsevel** [comment]
when I start the app I get:
```
2023-08-17 13:41:01,056 WARN  [io.qua.run.con.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.tls.trust-all is set to 'true' but it is build time fixed to 'false'. Did you change the property quarkus.tls.trust-all after building the application?
...
2023-08-17 13:41:12,135 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-1) Failed to export spans. The request could not be executed. Full error message: Failed to create SSL connection
```

when I add the `trust-all` to the `src/main/resources/application.properties` , the `SEVERE` disappears.
I am missing something?

**Comment by geoand** [comment]
How are you setting the property in the first case?

**Comment by vsevel** [comment]
on the disk, specifically in `./config/base-application.properties` with `QUARKUS_CONFIG_LOCATIONS=./config/base-application.properties`

**Comment by geoand** [comment]
Ah okay, I see.

You would need to use a TestProfile to set the build time properties you need

**Comment by vsevel** [comment]
I added this to `src/main/resources/application.yaml`:

``` 
"%mytest":
  quarkus:
    tls:
      trust-all: true
```

I start the app with:
```
 java -Dquarkus.profile=mytest ...
```

I see:
```
2023-08-17 14:47:17,030 WARN  [io.qua.run.con.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.tls.trust-all is set to 'true' but it is build time fixed to 'false'. Did you change the property quarkus.tls.trust-all after building the application?
...
2023-08-17 14:47:18,327 INFO  [io.quarkus] (main) Profile mytest activated. 
...
2023-08-17 14:47:43,110 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-1) Failed to export spans. The request could not be executed. Full error message: Failed to create SSL connection
```

is that what you meant by `TestProfile`?

**Comment by geoand** [comment]
https://quarkus.io/guides/getting-started-testing#writing-a-profile is what
I have in mind

**Comment by geoand** [comment]
Sure yeah, we can have a dedicated property

**Comment by geoand** [comment]
I can do that  next week when I can get from PTO

**Comment by geoand** [comment]
One question for @cescoffier though: What was the reason we chose to make `quarkus.tls.trust-all` runtime fixed instead of overridable at runtime?

**Comment by cescoffier** [comment]
Good question. I think it can be revisited.

**Comment by cescoffier** [comment]
Note that you need to know whether you plan to use ssl at build time as the native compilation paths are very different.

**Comment by geoand** [comment]
That makes sense, but does the `trust-all` property make any difference to whethere TLS will be enabled or not?

**Comment by vsevel** [comment]
`trust-all` as a build time property removes a lot of usefulness.
the usual use case is when running in dev and you do not have the appropriate certs locally.
but when going to test/uat/prod you want to be strict about it.

**Comment by geoand** [comment]
Right, that's why I asked before adding a specific property for OTel
