### ISSUE TITLE
3.0.0.Alpha6 - org.hibernate.annotations.Type Cannot find a parameter with this name: type No value passed for parameter 'value'

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#31957]
### Describe the bug

<img width="533" alt="image" src="https://user-images.githubusercontent.com/8830888/226098540-536747ee-4364-4010-8f35-0ff239bfd320.png">

bump to alpha6 changed following situation:

im not quite sure if this is an actual issue.
it looks like the interface(enum) has changed and a new value is expected by implicit enum field 'value' and the type has to be adjusted maybe? so i checked the expected class and searched for some text implementation. maybe you can help me out here, what im doing wrong?

thanks

<img width="845" alt="image" src="https://user-images.githubusercontent.com/8830888/226098603-b7376d74-2eae-406f-9583-9cf7ba06a962.png">
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/8830888/226098611-67ee1495-4f34-42de-b35b-1a8c9aceee51.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/8830888/226098672-7fda508e-f21f-4eb0-a33a-0bece10ff2d9.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/8830888/226098183-ab94e3cb-7221-427e-b276-082a389eeca9.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/8830888/226098195-b2e8e2fb-387c-493d-b4bf-35eedec9f3a8.png">
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8830888/226098816-ddfa6f4e-84a4-4186-8a75-e9114a916727.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8830888/226098278-90aaf4e7-4d17-4615-bc8b-dc73617ebacf.png">

**Comment by gsmet** [comment]
With Alpha5+ comes the upgrade to Hibernate ORM 6, which is a new major version and a lot of things have changed including the `@Type` annotation.

We have a dedicated migration guide here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration .

@yrodiere I wonder if we should add a quick reference for the `@Type` change?

**Comment by punkratz312** [comment]
merci

**Comment by yrodiere** [comment]
> @yrodiere I wonder if we should add a quick reference for the `@Type` change?

Will do, but probably next week.

**Comment by yrodiere** [comment]
I tried to document the changes and solutions in the migration guide, there: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#type-system

@gsmet any comment? If the guide seems ok to you, I think we can close this issue.

**Comment by gsmet** [comment]
Perfect, thanks.
