### ISSUE TITLE
Gradle `quarkusIntTest` produces `container.log` in `target` directory

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#31950]
### Describe the bug

Gradle `quarkusIntTest` generates the `container.log` in `<project>/target` not `<project>/build`.

Pedantically, for Gradle this should be in `build/test-results/quarkusIntTest` as this is where all results from this test run are stored.

### Expected behavior

`container.log` is generated in `build/test-results/quarkusIntTest` or at least in `build`.

### Actual behavior

`container.log` is generated in `target`.

### How to Reproduce?

Run a `quarkusIntTest` task in a Gradle build.

### Output of `uname -a` or `ver`

macOS 13.2.1

### Output of `java -version`

java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### Quarkus version or git rev

2.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment]
@Karm with the changes you made, we no longer produce this file, correct?

**Comment by Karm** [comment]
@geoand Correct.

**Comment by geoand** [comment]
Thanks for confirming.

So let's close this as out of date

**Comment by Karm** [comment]
@kdubb, the log file used to be produced here, with hardcoded `target` dir: 

https://github.com/quarkusio/quarkus/blob/b0b743439edaa0acf1969093c22cc319bc3e221d/test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java#L145

We no longer do that, there is just quarkus.log now and the container simply spits output to stdout:

https://github.com/quarkusio/quarkus/blob/main/test-framework/common/src/main/java/io/quarkus/test/common/DefaultDockerContainerLauncher.java#L135

**Comment by kdubb** [comment]
@Karm Thanks!
