### ISSUE TITLE
WebSocket automatic reflection registration

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#31972]
### Description

Hi guys !
I think that quarkus should automatically register for reflections classes to serialize or deserialize in websockets.
This should be similar to what it's done for REST endpoints.

What do you think ?

### Implementation ideas

I think this could be done inside a BuildStep, scanning jandex index, looking for implementations of jakarta.websocket.Decoder or jakarta.websocket.Encoder and producing ReflectiveHierarchyBuildItem accordingly.

**Comment by amoscatelli** [comment]
If you want I can make a pull request,
I would add this here : 
https://github.com/quarkusio/quarkus/blob/main/extensions/websockets/server/deployment/src/main/java/io/quarkus/websockets/deployment/ServerWebSocketProcessor.java

**Comment by geoand** [comment]
Hi,

Do you have some sample application that fails in native mode as is?

**Comment by amoscatelli** [comment]
@geoand  Ummmn it's quite hard to extract a sample application but I just created a web socket like this : 

```
@ServerEndpoint(
        value = "/chat",
        encoders = ChatMessageEncoder.class,
        decoders = ChatMessageDecoder.class
)
public class ChatSocket {

    @OnMessage
    public void onMessage(ChatMessageDTO message) {
        chatController.publish(
                this.mapper.from(
                        message
                )
        );
    }
    
}
```

```
public class ChatMessageDTO {
    
    private String id;
    
    private String from;

    private String content;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }
    
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    
}
```

And the only way I have to make it work is to have this reflection-config.json :

```
[
    {
        "name": "com.techedge.dto.ChatMessageDTO",
        "allDeclaredConstructors": true,
        "allPublicConstructors": true,
        "allDeclaredMethods": true,
        "allPublicMethods": true,
        "allDeclaredFields": true,
        "allPublicFields": true
    }
] 
```

I believe this should work out of the box

**Comment by geoand** [comment]
Okay, then yeah, I think it makes sense.

Feel free to contribute this fix :)

**Comment by amoscatelli** [comment]
I'll work on it in the next days !
I believe it'll be pretty simple

**Comment by geoand** [comment]
Thanks. yeah it should be straightfoward.

**Comment by amoscatelli** [comment]
@geoand here you are ! 
https://github.com/quarkusio/quarkus/pull/32017

**Comment by amoscatelli** [comment]
This works correctly now in CR1 !

**Comment by geoand** [comment]
🎉
