### ISSUE TITLE
Restore tests of Dev UI page content for Hibernate extensions following the switch to the new Dev UI

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#31970]
### Description

See `integration-tests/devmode/src/test/java/io/quarkus/test/devconsole/DevConsoleHibernateOrmSmokeTest.java` and other Hibernate-related tests.

See https://github.com/quarkusio/quarkus/pull/31946/files#diff-a2c77b179a0ebbc7a5838f9ea5bf0cdd50c77b92299017a82ab4e022ca28d3e1R45

> Yes, the plan is to use [playwrite](https://playwright.dev/java/)

**Comment by yrodiere** [comment]
Hey @phillip-kruger , any news on using [playwrite](https://playwright.dev/java/) for Dev UI testing? Just so I know if we can consider restoring the Hibernate Dev UI tests.

**Comment by phillip-kruger** [comment]
No new yet, maybe @ia3andy can help here....

**Comment by ia3andy** [comment]
@yrodiere the tricky part with Playwright is to setup the CI, they have their own images with the drivers and all.
