### ISSUE TITLE
'quarkus.oidc.auth-server-url' property must be configured (only in uber jar)

### ISSUE THREAD

**Issue by kubecutle** [quarkusio/quarkus#31993]
### Describe the bug

1) Take the security-jwt-quickstart project from: https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-jwt-quickstart. 
2) Add the quarkus-oidc dependency to the pom.

`
<dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-oidc</artifactId>
    </dependency>
`
3) Create an uber jar: quarkus build -Dquarkus.package.type=uber-jar
4) Run the uber jar: java -jar target/security-jwt-quickstart-runner.jar 

Result: application doesn't start. Error message is: 'quarkus.oidc.auth-server-url' property must be configured

HOWEVER. The application runs fine if I just run it without creating the uber jar: 'quarkus dev' does not produce the same error.

To address this, I added `quarkus.oidc.tenant-enabled=false` to application.properties. Then the uber jar starts without problem. BUT if I added the following configuration, the issue appears again:

quarkus.oidc.manual.tenant-enabled=true

I am trying to use this last configuration to have a manual OIDC process where the jwt is not generated by an auth/oidc server. I was under the impression that disablin instropection would resolve this issue. So I added following:

`
quarkus.oidc.manual.token.allow-jwt-introspection=false
quarkus.oidc.manual.token.allow-opaque-token-introspection=false
`
Unfortunately it did not help.

### Actual behavior

I would expect a consistent behavior when running the app with `quarkus dev` and with uber jar. Currently, I am having this error ONLY in the case of uber jars.

### How to Reproduce?

Reproducer:
1) git clone https://github.com/quarkusio/quarkus-quickstarts.git
2) cd security-jwt-quickstart
3) run: quarkus dev --> no error
4) run: quarkus build -DskipTests -Dquarkus.package.type=uber-jar
5) run:  java -jar target/security-jwt-quickstart-runner.jar  --> failure

### Output of `uname -a` or `ver`

Linux pf 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:19 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Output of `java -version`

penjdk version "11.0.18" 2023-01-17

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.6

**Comment by sberyozkin** [comment]
@kubecutle I'm not sure why you combine `smallrye-jwt` and `quarkus-oidc`, can you clarify please why ?

**Comment by kubecutle** [comment]
@sberyozkin to allow users to login manually as well as through oidc providers such as google, facebook, etc.
In the manual case, we create a jwt token that we put in the cookies. I believe following project does the same: https://github.com/FroMage/quarkus-renarde-todo

**Comment by kubecutle** [comment]
Sorry. there is a step missing in the reproducer. Between 3) and 4), add the oidc dependency to the pom:

`<dependency> <groupId>io.quarkus</groupId> <artifactId>quarkus-oidc</artifactId> </dependency>`

**Comment by sberyozkin** [comment]
@kubecutle Thanks for the clarification.

So, the reason you see the error is that it is not devmode anymore once you run the jar, so `quarkus-oidc` complains it can't find a property it needs to get started. 
Add this property with `%prod.` profile and then in devmode you can start without it but n prod it will be used

**Comment by kubecutle** [comment]
Thanks @sberyozkin. Are there ways to resolve this and prevent app from just stopping?

**Comment by sberyozkin** [comment]
@kubecutle Well, in the product profile, if you would like to use OIDC, it has to be configured, if you'd like to keep it without having to configure it then indeed, use that tenant-enabled property - use a system/env property to control it as you prefer (set it to false in prod for ex) - hope it helps

@geoand IMHO it is not a bug, let me close it

**Comment by geoand** [comment]
Thanks @sberyozkin
