### ISSUE TITLE
[smallrye-messaging] dev ui table too small Quarkus 3.0.0.Alpha5

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#31998]
### Describe the bug

In the Channel Page of the dev ui, the vaadin-grid element only takes up 400px of height.

### Expected behavior

The table takes up the whole height available

### Actual behavior

It takes up only 400px

### How to Reproduce?

1. Have a project with smallrye-messaging
2. have at least 3 channels used in the app
3. start the dev ui
4. go to channels page

**Comment by phillip-kruger** [comment]
Do you have a reproducer? And a screenshot? That will help...

**Comment by bulldog98** [comment]
I'll put a reproducer and a screenshot together when I'm no longer at work

**Comment by bulldog98** [comment]
![grafik](https://user-images.githubusercontent.com/314259/226681899-76335686-dbc9-4709-8e48-28dc5276233f.png)
In red you see where there is information missing. Page ends maybe 50% of the way.

Reproducer:  https://github.com/bulldog98/smallrye-messaging-reproducer-31998
