### ISSUE TITLE
Implement OpenshiftClient on Kubernetes Client Extension

### ISSUE THREAD

**Issue by luszczynski** [quarkusio/quarkus#3200]
**Description**
I've been using Kubernetes Client Extension for a while and I can't find a way to create a `DefaultOpenShiftClient` [1]. It seems to me that this class is not available yet on Quarkus 0.19.0. Am I right?

Any plans to solve this? 

[1] https://github.com/fabric8io/kubernetes-client

**Comment by geoand** [comment]
You are correct, currently we only offer the Kubernetes Client. It should be fairly easy to add the Openshift Client (probably a new extension that would add the openshift client dependency and maybe add some more reflection registering and/or substitution)

**Comment by gsmet** [comment]
Definitely looks like something we should do.

**Comment by geoand** [comment]
@luszczynski if you want to get your hands dirty on Quarkus, I will gladly help out. Otherwise, I can probably take this up sometime before the `0.20.0` release

**Comment by luszczynski** [comment]
@geoand I could give it a try. But I would definitely need some guidance on how to do it.
Do we need to create another extension? Or just improve the kubernetes client?

**Comment by geoand** [comment]
I would say that adding a new extension that utilizes the existing one but also adds the new dependency would be the way to go.
It also might need some work to create the proper bean in the producer method.

**Comment by luszczynski** [comment]
Hey @geoand,

I've been busy traveling these last weeks and will continue on the next two weeks. It may take a while until I can get my hands on quarkus and openshift client. I just want to give some feedback to you so you can plan your work for quarkus `0.20.0`

**Comment by geoand** [comment]
Hi @luszczynski,

Thanks for the update! I probably won't have time to start working on this for 0.20.0 either, so I guess we'll have to wait for 0.21.0

**Comment by gastaldi** [comment]
+1 to a `quarkus-openshift-client` extension that depends on `quarkus-kubernetes-client`

**Comment by vsevel** [comment]
hello @geoand @gastaldi 
we started porting our java lib to provision our apps on our ocp cluster, and although most of our objects are pure k8s, we still use a few openshift objects (projectrequest, route, imagestream). without support for the openshift-client, I think we are down to not using the quarkus fabric8 k8s client unfortunately.
how much effort do you think this would be?

**Comment by geoand** [comment]
@vsevel Hey

It should not be much effort TBH. It should be very similar to the `quarkus-kubernetes` extension,

**Comment by gastaldi** [comment]
BTW if your application is not compiled to native, you can add the fabric8 openshift-client dependency and use it right away

**Comment by vsevel** [comment]
@gastaldi great. we will add the dependency for now
@geoand and I will give a shot at the extension next, since we want to evaluate the native approach in the context of this migration
I will keep you updated on the progress

**Comment by vsevel** [comment]
do you think we should just add the fabric8 openshift-client library (plus any required quarkus related classes) into the existing the kubernetes-client extension, or should we create a new openshift-client extension that depends (maven-wise) on the kubernetes-client extension?

**Comment by geoand** [comment]
I believe we should not have the openshift model/client in the kubernetes extension as to keep the number of classes small when needed.

**Comment by gastaldi** [comment]
I'm still convinced that https://github.com/quarkusio/quarkus/issues/3200#issuecomment-517771636 is the best approach 😉
