### ISSUE TITLE
RESTEasy Reactive endpoint returns a "200" response automatically after some duration, preventing an eventual error from being returned.

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#32014]
### Describe the bug

We have an endpoint which looks something like this:

```
1. Try to establish a JDBC connection using input parameters from request
2. Do stuff with the JDBC connection
```

The problem is that for Snowflake, if you use an invalid URL, there is a 60-second name lookup timeout before it errors.
So what is happening is that:
1. The REST endpoint is returning "200" (and who knows what as a response?)
2. Then some moments later, an error is thrown and shows up in the terminal, but this never reaches the client because we've already sent 200.

My questions are:

1. Is there a default response middleware or something, where Quarkus will send an empty response body after some period of time?
2. How can I make the endpoint wait for the `val conn = driverManager.connect(connInfo.jdbcUrl, Properties())` line before continuing?
3. How can I check the contents of the "200" response body?

Really confused here as to what is going on :thinking:

---

This looks like:
```java
11:47:25 INFO  traceId=, parentId=, spanId=, sampled= [io.qu.ht.access-log] (vert.x-eventloop-thread-1) 127.0.0.1 - - 21/Mar/2023:11:47:25 -0400 "GET /api/v1/snowflake/schema? HTTP/1.1" 200 -
11:47:57 SEVERE traceId=, parentId=, spanId=, sampled= [ne.sn.cl.jd.RestRequest] (executor-thread-0) Stop retrying since elapsed time due to network issues has reached timeout. Elapsed: 61,267(ms), timeout: 60,000(ms)
11:47:57 ERROR traceId=, parentId=, spanId=, sampled= [io.ha.ap.ExceptionHandler] (executor-thread-0) Uncaught exception: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error.
Message: Exception encountered for HTTP request: xxxxxx.us-east-2.aws.com.
        at net.snowflake.client.jdbc.RestRequest.execute(RestRequest.java:301)
        at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:737)
        at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:672)
        at net.snowflake.client.core.HttpUtil.executeGeneralRequest(HttpUtil.java:594)
        at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:596)
        at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:286)
        at net.snowflake.client.core.SFSession.open(SFSession.java:461)
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:104)
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
        at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
        at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
        at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:176)
        at io.x.services.dataConnectors.BaseDataConnectorService.getSchema(BaseDataConnectorService.kt:77)
```

Where the logic for that endpoint looks something like:
```kt
fun getSchema(sourceName: DatasourceName, config: Map<String, Any>): Schema {
    val connInfo = DatasourceConnectionInfo(sourceName, config["jdbc_url"])

    val driverManager = DriverManager.getDriver(connInfo.jdbcUrl)
    val conn = driverManager.connect(connInfo.jdbcUrl, Properties())
    
    // It should never make it here if the conn fails, and without a valid conn the rest of the info can't be gathered
    return ...
}
```

### Output of `java -version`

17

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle-8.0-milestone-2

**Comment by geoand** [comment]
This is super weird indeed... I personally can't think of what might be causing this.

Is there any chance you could put together  a sample that behaves as you describe so we can dig into it?

Thanks

**Comment by GavinRay97** [comment]
I can try, let me give it a shot

**Comment by GavinRay97** [comment]
Wow this is super strange, I cannot seem to reproduce it on a fresh `code.quarkus.io` Java app.

That leaves basically no way of investigating it I suppose =/
For example, the following fails just fine:

```java
@Path("/schema")
@GET
@Produces(MediaType.APPLICATION_JSON)
public Schema schema() throws SQLException {
    String snowflakeJdbcUrl = "jdbc:snowflake://akXXXX.us-east-2.aws.com/?user=USER&password=xxxx&db=CHINOOK&schema=PUBLIC&warehouse=COMPUTE_WH&role=ACCOUNTADMIN";

    Driver driver = DriverManager.getDriver(snowflakeJdbcUrl);
    Connection conn = driver.connect(snowflakeJdbcUrl, new Properties());

    var tables = conn.getMetaData().getTables(null, null, null, null);
    var tableList = new ArrayList<Table>();

    while (tables.next()) {
        // ...
    }

    return new Schema(tableList);
}
```

**Comment by geoand** [comment]
Right, that's the expected behavior although it would certainly have made for an easier debugging experience had it not been :)

**Comment by GavinRay97** [comment]
Could a Caffeine cache lookup have anything to do with it?

In the full business code, we do some cache lookups that I omitted for the sake of brevity here.
Just curious if that would impact anything.

(I would think not, but just to double-check)

**Comment by geoand** [comment]
No problem, thanks
