### ISSUE TITLE
Spring 6 / Spring Boot 3 compatibility layer

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#32027]
### Description

Our current Spring compatibility layer targets Spring 5 / Spring Boot 2.

I assume that Spring 6 / Spring Boot 3 have slightly different APIs/dependencies, be it only when it comes to Jakarta EE, which could make the Spring 5 / Spring Boot 2 compatibility layer unusable for people migrating from Spring 6 / Spring Boot 3 to Quarkus (though I'd be happy to be proven wrong).

If that's the case, should we duplicate the current Spring 5 / Spring Boot 2 compatibility layer and create a separate Spring 6 / Spring Boot 3 compatibility layer?

### Implementation ideas

We're not there yet, I just wanted to discuss whether this is necessary or not.

**Comment by yrodiere** [comment]
Creating this because the question of the upgrade was mentioned in #32016 (though upgrading is unlikely to do anything to solve #32016; it's just a separate matter that seems worth discussing).

**Comment by geoand** [comment]
So is this essentially just about upgrading our Spring API dependencies?

**Comment by yrodiere** [comment]
I don't know. Do we want to just upgrade, or to have compatibility layers for both versions co-exist? Either would make sense IMO, if the Spring 5 APIs are not "tainted" by Java EE dependencies.

**Comment by geoand** [comment]
Let's take a step back as I am unsure what the actual issue being reportes is.

The Quarkus Spring compatibility extensions only depend on a part of the Spring API surface. AFAIK, nothing should have changed WRT the stuff we support between SB 2 and SB 3 (although there might be things that were missed).
Also, those  APIs don't really depend on Java EE: Spring supporteds javax  and now jakarta annotations so I don't really see an issue here.

**Comment by yrodiere** [comment]
> AFAIK, nothing should have changed WRT the stuff we support between SB 2 and SB 3
> Also, those APIs don't really depend on Java EE

If so then that's fine, we can close this ticket. I just reported this so that we don't forget to check.

**Comment by geoand** [comment]
Okay cool, thanks

**Comment by gsmet** [comment]
Just my 2 cents but given the move to Jakarta, I think we should probably move to Spring 6/SB 3 APIs.

There might not be any changes but it looks more consistent to me.

**Comment by gsmet** [comment]
Totally agree.

**Comment by rquinio** [comment]
I could help with this.
Given Spring 6 and SB 3 use Java 17 bytecode, upgrading the dependency versions would mean the Quarkus 3.0 spring extensions would only support JDK17+ and they have to be moved to a Maven profile ?
This means a component built against Spring 5 wouldn't build with Quarkus 3 on JDK11.

**Comment by rquinio** [comment]
I've opened https://github.com/quarkusio/quarkus/pull/32187 as draft to show the impacts.

But until new Spring 6 features need to be supported (ex:  new ListCrudRepository/ListPagingAndSortingRepository interfaces) I'm not sure it's actually required to bump ?

Note that technically quarkus-spring-web-resteasy-classic extension already has a runtime dependency on spring 6 via org.jboss.resteasy.spring:resteasy-spring-web 3.0.x.

**Comment by geoand** [comment]
Exactly, we don't really need to bump unless / until there are features from the Spring 6 API we need

**Comment by geoand** [comment]
I am actually going to close this because doing something along these lines would mean the Spring extensions would only work on Java 17
