### ISSUE TITLE
K8s is moving it's images

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#32041]
### Describe the bug

As described in this [blog post](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/) kubernetes is moving it's registry to eventually sunset the old one.

When starting a devservice for k8s we should use the image from the new registry

### Expected behavior

Dev service starts container
registry.k8s.io/kube-apiserver

### Actual behavior

Dev service starts container
k8s.gcr.io/kube-apiserver

### How to Reproduce?

Build an app with extension quarkus-kubernetes-client and run the dev mode

**Comment by geoand** [comment]
@bulldog98 thanks for reporting. 

Would you be interested in contributing a fix?

**Comment by bulldog98** [comment]
@geoand I'm willing to contribute a fix.

**Comment by geoand** [comment]
Cool
