### ISSUE TITLE
OpenSearch compatibility documentation

### ISSUE THREAD

**Issue by kontoeniki** [quarkusio/quarkus#32051]
### Describe the bug

The [documentation](https://quarkus.io/version/main/guides/hibernate-search-orm-elasticsearch#opensearch) refers that you should only set the quarkus.hibernate-search-orm.elasticsearch.version=opensearch:1.2 to be compatible with opensearch. But when trying to connect and as described in hibernate [documentation](https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/#backend-elasticsearch-configuration-version) you should also set the quarkus.hibernate-search-orm.elasticsearch.version-check.enabled=false . An update to the documentation would be very usefull

**Comment by yrodiere** [comment]
> But when trying to connect and as described in hibernate [documentation](https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/#backend-elasticsearch-configuration-version) you should also set the quarkus.hibernate-search-orm.elasticsearch.version-check.enabled=false . An update to the documentation would be very usefull

That's not true... Quoting the documentation:

> **If necessary**, you can disable the call to the Elasticsearch cluster on startup

You can totally use OpenSearch without disabling the call on startup. It will check the OpenSearch version, that's all.

**Comment by yrodiere** [comment]
I opened an issue on Hibernate Search to clarify the documentation: https://hibernate.atlassian.net/browse/HSEARCH-4823

I will close this issue as the required changes are exclusively in Hibernate Search.

Feel free to comment if you feel there's something else to be done on Quarkus.
