### ISSUE TITLE
Native binary and Java app size increase between 2.15.1.Final and 3.0.0.Beta1

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#32057]
### Describe the bug

Native binary size increase between 2.15.1.Final and 3.0.0.Beta1 from 40M to 42M
Edit: I have checked size of jars and the apps are differing by ~0.8M - 15.7M vs 16.5M, details in comment below.

I have small Quarkus app using just `quarkus-resteasy`, `quarkus-smallrye-metrics` and `quarkus-scheduler` for the functionality, `quarkus-container-image-docker` to build the image. Repo: https://github.com/rsvoboda/gh-exporter/blob/main/pom.xml

I moved from 2.15.1.Final to 3.0.0.Beta1 and noticed increase size increase of the binary, from 40M to 42M.
In both cases the same Mandrel version was used - GraalVM 22.3.1.0-Final Java 17 Mandrel Distribution

Output of natime-image indicated bigger size and more classes  and packages too.

2.15.1.Final:
```
  19.38MB (48.36%) for code area:    33,001 compilation units
  20.38MB (50.84%) for image heap:  268,010 objects and 10 resources
 327.62KB ( 0.80%) for other data
  40.08MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.63MB sun.security.ssl                                     4.28MB byte[] for code metadata
   1.00MB java.util                                            2.44MB java.lang.String
 733.87KB java.lang.invoke                                     2.44MB java.lang.Class
 717.65KB com.sun.crypto.provider                              2.31MB byte[] for general heap data
 450.58KB sun.security.x509                                    1.90MB byte[] for java.lang.String
 449.75KB java.lang                                          886.70KB com.oracle.svm.core.hub.DynamicHubCompanion
 428.32KB java.util.concurrent                               626.44KB java.util.HashMap$Node
 389.85KB io.netty.buffer                                    542.95KB byte[] for reflection metadata
 384.39KB java.io                                            470.00KB java.lang.String[]
 342.82KB io.netty.handler.codec.http2                       368.44KB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
  12.69MB for 386 more packages                                4.05MB for 2495 more object types
```

3.0.0.Beta1:
```
  19.98MB (47.75%) for code area:    33,931 compilation units
  21.55MB (51.49%) for image heap:  273,029 objects and 10 resources
 327.32KB ( 0.76%) for other data
  41.85MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.63MB sun.security.ssl                                     4.43MB byte[] for code metadata
   1.01MB java.util                                            2.51MB java.lang.Class
 733.91KB java.lang.invoke                                     2.49MB java.lang.String
 717.66KB com.sun.crypto.provider                              2.34MB byte[] for general heap data
 450.58KB sun.security.x509                                    1.95MB byte[] for java.lang.String
 449.99KB java.lang                                          910.94KB com.oracle.svm.core.hub.DynamicHubCompanion
 446.05KB io.netty.buffer                                    629.81KB java.util.HashMap$Node
 428.57KB java.util.concurrent                               557.43KB byte[] for reflection metadata
 391.83KB java.io                                            481.20KB java.lang.String[]
 349.39KB io.quarkus.runtime.generated                       377.81KB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
  13.21MB for 399 more packages                                4.09MB for 2551 more object types
```

### Expected behavior

No increase in binary size, or maybe just a few kB.

### Actual behavior

Native binary size increase between 2.15.1.Final and 3.0.0.Beta1 from 40M to 42M

### How to Reproduce?

 - clone https://github.com/rsvoboda/gh-exporter
 - run `mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true`
 - run `du -cskh target/gh-exporter-*-runner`

`git checkout main` or `git checkout 1.1.22.Final` for Quarkus 3.0.0.Beta1 based app
`git checkout 1.1.21.Final` for Quarkus 2.15.1.Final based app

### Output of `uname -a` or `ver`

macOS 13.2.1 (22D68) Ventura

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)

### GraalVM version (if different from Java)

Mandrel image 22.3.1

### Quarkus version or git rev

Quarkus 3.0.0.Beta1

**Comment by rsvoboda** [comment]
I have checked size of jars and the apps are differing by ~0.8M - 15.7M vs 16.5M

ADDED JARS ... 687K
```
com.sun.activation.jakarta.activation 64K
org.glassfish.jakarta.el 232K
org.glassfish.jakarta.json 137K
org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec 143K
org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec 111K
```

ADDED JARS ... 1143K
```
jakarta.activation.jakarta.activation-api 65K
jakarta.enterprise.jakarta.enterprise.lang-model 26K
jakarta.json.jakarta.json-api 49K
jakarta.servlet.jakarta.servlet-api 339K
jakarta.ws.rs.jakarta.ws.rs-api 151K
jakarta.xml.bind.jakarta.xml.bind-api 124K
org.eclipse.angus.angus-activation 27K
org.eclipse.parsson.parsson 119K
org.glassfish.expressly.expressly 168K
org.jboss.resteasy.microprofile.microprofile-config 12K
org.jboss.resteasy.resteasy-cdi 31K
org.jboss.weld.weld-api 32K
```

Move to Jakarta brought in additional weight (~460K), but that's not all. CC @gsmet @radcortez .

There are several artifact which got bigger than before, e.g. io.quarkus.quarkus-vertx-http went from 459K to 538K (CC @cescoffier). But that's not the only one, vertx-http is the most noticeable one from the existing artifacts. The remaining artifacts add few K, better to see the diff.

Attaching files with files listing - [quarkus-app-2.15.1.Final-deps-size.txt](https://github.com/quarkusio/quarkus/files/11048940/quarkus-app-2.15.1.Final-deps-size.txt) and [quarkus-app-3.0.0.Beta1-deps-size.txt](https://github.com/quarkusio/quarkus/files/11048939/quarkus-app-3.0.0.Beta1-deps-size.txt)

Generated using:
```
ls -lh quarkus-app-2.15.1.Final/lib/main | awk '{print $9, $5}' | sed "s/-[0-9].*jar//g" | sort > quarkus-app-2.15.1.Final-deps-size.txt
ls -lh quarkus-app-3.0.0.Beta1/lib/main | awk '{print $9, $5}' | sed "s/-[0-9].*jar//g" | sort > quarkus-app-3.0.0.Beta1-deps-size.txt 
```
You can see the diff using for example `code --diff quarkus-app-2.15.1.Final-deps-size.txt quarkus-app-3.0.0.Beta1-deps-size.txt`

**Comment by maxandersen** [comment]
shouldn't we be able to avoid that devui resources end up in the prod image?

**Comment by rsvoboda** [comment]
Reports generated with `quarkus.native.enable-reports `
 - [gh-exporter-1.1.21.Final-native-image-source-jar.zip](https://github.com/quarkusio/quarkus/files/11120453/gh-exporter-1.1.21.Final-native-image-source-jar.zip) (Quarkus 2.15.1.Final based)
 - [gh-exporter-1.1.22.Final-native-image-source-jar.zip](https://github.com/quarkusio/quarkus/files/11120454/gh-exporter-1.1.22.Final-native-image-source-jar.zip) (Quarkus 3.0.0.Beta1 based)

Generated using
```
git checkout 1.1.22.Final
mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.enable-reports 

git checkout 1.1.21.Final
mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.enable-reports 
```

**Comment by geoand** [comment]
Was there a conclusion on this one?

**Comment by franz1981** [comment]
@geoand The additional footprint should be related to HB 6, due to the many additional classes generated by antlr related Hql (that's about 1K classes).
There's something I have looked into with @Sanne to help on this but tbh is probably a long road.
Right now let's say that this is the tax to be paid to the improvement on Hibernate side, and every other framework using it will pay for it as well.

**Comment by geoand** [comment]
Okay thanks for the info.,

**Comment by Sanne** [comment]
This particular issue is not related to Hibernate though as it's not being used.

**Comment by rsvoboda** [comment]
> This particular issue is not related to Hibernate though as it's not being used.

Exactly, no HHH involved. Just `quarkus-resteasy`, `quarkus-smallrye-metrics` and `quarkus-scheduler` for the functionality, `quarkus-container-image-docker` to build the image

**Comment by galderz** [comment]
> Reports generated with `quarkus.native.enable-reports `
> 
> * [gh-exporter-1.1.21.Final-native-image-source-jar.zip](https://github.com/quarkusio/quarkus/files/11120453/gh-exporter-1.1.21.Final-native-image-source-jar.zip) (Quarkus 2.15.1.Final based)
> * [gh-exporter-1.1.22.Final-native-image-source-jar.zip](https://github.com/quarkusio/quarkus/files/11120454/gh-exporter-1.1.22.Final-native-image-source-jar.zip) (Quarkus 3.0.0.Beta1 based)
> 
> Generated using
> 
> ```
> git checkout 1.1.22.Final
> mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.enable-reports 
> 
> git checkout 1.1.21.Final
> mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.native.enable-reports 
> ```

These might offer some clues since the universe looks slightly bigger, e.g.

2.15:
```
❯ wc -l reports/used_classes_gh-exporter-1.1.21.Final-runner_20230331_093151.txt
    7069 reports/used_classes_gh-exporter-1.1.21.Final-runner_20230331_093151.txt

❯ wc -l reports/used_methods_gh-exporter-1.1.21.Final-runner_20230331_093151.txt
   45929 reports/used_methods_gh-exporter-1.1.21.Final-runner_20230331_093151.txt

❯ wc -l reports/used_packages_gh-exporter-1.1.21.Final-runner_20230331_093151.txt
     424 reports/used_packages_gh-exporter-1.1.21.Final-runner_20230331_093151.txt
```

vs

3.0:
```
❯ wc -l reports/used_classes_gh-exporter-1.1.22.Final-runner_20230331_092631.txt
    7252 reports/used_classes_gh-exporter-1.1.22.Final-runner_20230331_092631.txt

❯ wc -l reports/used_methods_gh-exporter-1.1.22.Final-runner_20230331_092630.txt
   47207 reports/used_methods_gh-exporter-1.1.22.Final-runner_20230331_092630.txt

❯ wc -l reports/used_packages_gh-exporter-1.1.22.Final-runner_20230331_092631.txt
     436 reports/used_packages_gh-exporter-1.1.22.Final-runner_20230331_092631.txt
```

[Here's a diff of the classes](https://gist.github.com/galderz/c519f21338d6e48558ef16f3ec4d46ae).

The other thing to check is the size of the sections in the binary, e.g. `svm_heap`.

All we know about debugging issues like this is explained in the [ref guide](https://quarkus.io/guides/native-reference).

**Comment by franz1981** [comment]
thanks @galderz looking at the Netty side it seems that 3.0.0.Beta1 got noUnsafe = true @gsmet can confirm?

**Comment by geoand** [comment]
Is there anything more we plan to do on this or should it be closed?

**Comment by rsvoboda** [comment]
I checked 3.2.5.Final and the size reduced a bit to 41M (40M was for 2.15, 42M was for 3.0).

@galderz @franz1981 do you plan further investigation or we close this as the diff is "just" 2.5 % now?

**Comment by geoand** [comment]
TY
