### ISSUE TITLE
Support more structured layout of config properties in docs

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#32052]
### Description

We have had a user feedback about a massive number of OIDC properties making it difficult to find what has to be configured. 
Total number of OIDC properties shown in the docs is 200+. 

### Implementation ideas

First, I'd like to propose to  introduce an `area` attribute to `ConfigItem` and then the property generator would output them in blocks, properties without the area go first,  and then a section per each area, ex, with `OIDC`, it could be `Discovery`, etc. It will make it easier for users to spot a required property. 

The other thing, in context of OIDC, is that tenant configuration duplicates the default configuration so doubling the number of actually available properties,  so for such properties there should be an option to block the property generation

**Comment by radcortez** [comment]
If you use `@ConfigMapping` with a `@WithDefaults @WithUnnamedKey Map<Key, Group>` as a container for defaults and user-defined they will be generated in a single area. Check the `quarkus.hibernate-orm.*` configuration.
