### ISSUE TITLE
Include OpenTelemetry configuration mapping in upgrade recipes

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32064]
See https://github.com/quarkusio/quarkus/pull/32050/files#diff-ce0b5beb6a1b039064cc19f31a98739c58721ab1c51f90f4fbfe3568c7eb7f5cR17-R28 .

**Comment by rsvoboda** [comment]
@brunobat @radcortez is this on your radar?

**Comment by brunobat** [comment]
It is now. When do you need it, @rsvoboda ?

**Comment by rsvoboda** [comment]
I just noticed this on https://github.com/orgs/quarkusio/projects/13/views/25 marked as P1, so that's why I asked.

**Comment by rsvoboda** [comment]
Guillaume self assigned this on March, but not sure if he has something planned. @gsmet is on PTO today and tomorrow, he should be back on Monday I think.
