### ISSUE TITLE
Can't inject list of interfaces with wildcards twice into beans

### ISSUE THREAD

**Issue by insideworld** [quarkusio/quarkus#32080]
### Describe the bug

ARC has a problem while resolving injection points for types with wilcards.
If create an parametirized interface and several implementation and after try to inject List (with All annotion) more than one time - ARC can't resolve syntetic bean more than one time.

More details with screenshoots in additional information.

### Expected behavior

Shold inject list of beans in any injection point.

### Actual behavior

If inject List in two or more beans will cause exception about unsatisfied dependency.

### How to Reproduce?

Example here https://github.com/insideworld/quarkusbug
Just try to build it using maven and take exception about Unsatisfied dependency.
If comment BeanB - all works fine.

Test case:
1. Need to create an interface with generic parameter.
2. Create two or more implementation of generic interface and mark it as singleton.
3. Create two or more independed beans and try to inject list of interfaces with all annotation.
4. Try to build it or launch.

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

ARC try to resolve bean at first iteration in io.quarkus.arc.processor.Beans#resolveInjectionPoint and found possible syntetic bean to inject.
In io.quarkus.arc.processor.BeanResolverImpl#matchesNoBoxing all good because comparation by reference get true:
![image](https://user-images.githubusercontent.com/24254398/227261804-a972cc33-d4b1-4f53-9675-e33e8e50142e.png)

But in the second (and other) times when ARC try to compare 2 types, references are different:
![image](https://user-images.githubusercontent.com/24254398/227262412-3ac67b42-b9fb-4e13-a729-4b3e93e3d4df.png)

After some recursive operation, arc try to resolve wildcards types:
![image](https://user-images.githubusercontent.com/24254398/227263392-87028001-a6fa-459f-b401-d12243e8eaca.png)
But here we don't have comparation by references or comparation by 2 wildcards and validation return negative result.

**Comment by manovotn** [comment]
If nobody beats me to it, I can take a stab at this on Mon.

**Comment by manovotn** [comment]
So, the issue here is that for given injection point, we create a synthetic bean which contains a wildcard in its bean type (in this case we create `List<Some<?>>`).

This is normally not OK from [CDI spec standpoint](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#legal_bean_types):

> A parameterized type that contains a wildcard type parameter is not a legal bean type.

and we therefore don't have the assignability rules to deal with it, hence the unsatisfied resolution.

There are two ways we can fix this:
* Change the type of the bean we register to avoid having wildcard in it
* Change the assignability rules to take into account this case can happen for our added beans


As a side note - the fact that the reproducer provided here passes with only one bean implementation is coincidental as it only passes because the two compared parameterized types will be completely identical, hence passing the reference equality check.

**Comment by mkouba** [comment]
Thanks for your analysis Matej. Indeed, we don't have [a test](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInjectionTest.java) for parameterized types. There's only [test to verify that `@All List<T>` and `@All List<?>`](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/lookup/ListInvalidTypeParamTest.java) are illegal.

In theory, the `List<Some<?>>` should be satisfied with `List<Some<T>>` but I think that we need a more robust solution to cover all use cases with generics. 

Maybe we should reimplement the `@Inject @All` completely. Right now,  we discover all `@All` injection points, then we add a `@Identified` qualifier where the id is based on the required type and all annotations of an IP. Later we register a synthetic bean that satisfies these requirements. The bean delegates to `io.quarkus.arc.impl.Instances.listOf()` at runtime.

**Comment by manovotn** [comment]
Thanks for comment Martin, I am digging deeper into it as I discovered some other discrepancies (part of which you described here).
For this very case, I have a fix ready but I am currently exploring how to handle wildcard with upper/lower bounds.
