### ISSUE TITLE
MongoDB extension test failure in CI

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#3210]
**Describe the bug**
When working on https://github.com/quarkusio/quarkus/pull/3208, I got CI failure for Linux JDK build for MongoDB extension. 

**Expected behavior**
The CI build to succeed.

**Actual behavior**
The build fails: https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=4430&view=logs.

**Environment (please complete the following information):**
 - ci (Linux jdk build) 

**Additional context**
Build failed with 
````
[mongod output] 2019-07-12T12:20:36.984+0000 I STORAGE  [conn28] WiredTigerKVEngine shutting down
[mongod output] 2019-07-12T12:20:37.064+0000 I STORAGE  [conn28] shutdown: removing fs lock...
[mongod output] 2019-07-12T12:20:37.064+0000 I CONTROL  [conn28] now exiting
[mongod output] 2019-07-12T12:20:37.064+0000 I CONTROL  [conn28] shutting down with code:0
[mongod output] 
[ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.91 s <<< FAILURE! - in io.quarkus.mongodb.BasicInteractionTest
[ERROR] testIndexCreation  Time elapsed: 0.454 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<1> but was:<2> in:
<[{"key"={"_id"=1}, "name"="_id_", "ns"="mongo-extension-test-db.NPYADPQL", "v"=2},
    {"key"={"i"=1}, "name"="my-index", "ns"="mongo-extension-test-db.NPYADPQL", "v"=2}]>
  at io.quarkus.mongodb.BasicInteractionTest.testIndexCreation(BasicInteractionTest.java:310)
```

**Comment by loicmathieu** [comment]
Hi @machi1990 do you have the complete output of mongodb logs ?

I face issues on local build (I run Unbuntu 19.04) and I need to launch mongodb integration tests on sudo mode or else MongoDB refuses to start. 

I suspect some intraction with the system (like filesystem authentication) occurs.

If we could switch to TestContainers for this kind of tests it will be easier but it will needs Docker installed locally to execute the test (so maybe add a way to ignore the test if Docker is not present)

**Comment by machi1990** [comment]
Hi @loicmathieu 

> Hi @machi1990 do you have the complete output of mongodb logs ? 

I included the link to the logs but it does not exists anymore. Maybe @gsmet or @cescoffier or anyone with admin rights on Azure pipelines maybe able to retrieve them if it helps with the investigation. Too bad I did not save the complete log locally. 

> I face issues on local build (I run Unbuntu 19.04) and I need to launch mongodb integration tests on sudo mode or else MongoDB refuses to start.

You think it might be related?

**Comment by gsmet** [comment]
No we don't have access to them. I don't know what triggers the build suppression but it's really annoying :/

**Comment by loicmathieu** [comment]
What is strange is that it didn't occurs on all builds, this one just pass a few minutes ago: https://github.com/quarkusio/quarkus/pull/3063/checks?check_run_id=166783060

**Comment by machi1990** [comment]
@gsmet +1 on the annoyance part. I would expect the builds artifacts to be kept for some time (configurable via an expire timeout maybe)

@loicmathieu really strange. Looks like a one off thingy or random failure. Hard to investigate on either case.

**Comment by machi1990** [comment]
@loicmathieu the issue appeared again for PR #3216 and I managed to get hold of the full
[CI log](https://github.com/quarkusio/quarkus/files/3389268/16.txt)

**Comment by loicmathieu** [comment]
Hello, 
I check the log and it's not the same issue as I ran in my local environement. This seems to be a real issue with the test cases but I launch them twice and never it that one. Maybe the test cases should be more permissive in there assertions ...
I do run into an issue where the database didn't succeed in stopping and this generates an error.

So the tests are not stable but as the issues are always different I don't know what can be done. I'll send a PR with a small change to allow the test to pass if it cannot stop the database but this will not solves all issues ...
