### ISSUE TITLE
Qute Eclipse plugin error when using CompletableFutures

### ISSUE THREAD

**Issue by TonyWeston** [quarkusio/quarkus#32103]
### Describe the bug

When adding a CompletableFuture data item to a qute template,  eclipse shows an error:

For example: I am adding a CompletableFuture here:
<img width="592" alt="Screenshot 2023-03-24 at 09 16 25" src="https://user-images.githubusercontent.com/46684275/227476820-789b235b-b30e-4ef2-b7a0-94e0074906fb.png">

In eclipse Qute editor, I see this error :

<img width="909" alt="Screenshot 2023-03-24 at 09 18 07" src="https://user-images.githubusercontent.com/46684275/227477163-88214782-d1fc-4183-906e-e25de4636a8e.png">

If I complete the future in the java code:
<img width="557" alt="Screenshot 2023-03-24 at 09 18 59" src="https://user-images.githubusercontent.com/46684275/227477372-cf3e345d-50a0-4aeb-9bab-cda97d13bcc1.png">

The warning goes away, though the code is no longer reactive....
<img width="432" alt="Screenshot 2023-03-24 at 09 19 50" src="https://user-images.githubusercontent.com/46684275/227477597-f86b43d8-943c-4d67-a164-1fabcec742df.png">

### Expected behavior

Use of completablefuture should work the same as just passing data objects.

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

eclipse

### Additional information

Doesn't actually prevent anything from working as it should.  Just an annoying eclipse error.

Using eclipse plugin "Quarkus Tools 4.26.0.Final'

**Comment by angelozerr** [comment]
@TonyWeston please create the issue in https://github.com/redhat-developer/quarkus-ls

**Comment by gastaldi** [comment]
Issue https://github.com/redhat-developer/quarkus-ls/issues/826 created. Closing this now
