### ISSUE TITLE
quarkus-class-change-agent has an invalid JMPS module name

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#32108]
### Describe the bug

When building a project that has an Automatic Module Name and depends on Quarkus 2.16.4, the maven-javadoc-plugin  build crashes because javadoc thinks that `quarkus-class-change-agent` has module name - and that module name is invalid:

```
Execution build-javadoc-jar of goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar failed: Unable to derive module descriptor for /.../.m2/repository/io/quarkus/quarkus-class-change-agent/2.16.4.Final/quarkus-class-change-agent-2.16.4.Final.jar: quarkus.class.change.agent: Invalid module name: 'class' is not a Java identifier
```

I suspect the problem is accidentally triggered because of the word "class" in the artifactId "quarkus-class-change-agent"...

Given that  `quarkus-class-change-agent` doesn't do JPMS, but projects that depend on it can prepare themselves for JPMS by adding Automatic Module Name, this is a difficult situation.

**Comment by maxandersen** [comment]
hmm - not sure what the solution is. Is this not a bug in the maven javadoc plugin?

@ge0ffrey got a (recent) reproducer?

**Comment by ge0ffrey** [comment]
Let's close this.
I see no workaround in https://github.com/TimefoldAI/timefold-solver/blob/main/quarkus-integration%2Fquarkus%2Fruntime%2Fpom.xml

It must be resolved already.

**Comment by ge0ffrey** [comment]
Thanks for considering this issue.

**Comment by dmlloyd** [comment]
You can probably work around the problem by adding the following line to your `maven-javadoc-plugin` execution configuration:

```xml
<legacyMode>true</legacyMode>
```

This will tell it not to use module mode when generating the API docs.
