### ISSUE TITLE
OpenAPI generation: `@RolesAllowed` roles are sometimes missing (random behavior)

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#32112]
### Describe the bug

We have OIDC security provider with RESTEasy Classic and our endpoint `/secured/admin` is annotated with `@RolesAllowed("admin")`. Sometimes, generated security scheme is empty (once in a few days, you can see our CI). Interestingly, we have identical endpoint with RESTEasy Reactive and this problem occasionally occur too.

### Expected behavior

OpenAPI definition must be deterministic (and ideally with roles).

### Actual behavior

Most of the times, we get `"/secured/admin":{"get":{"tags":["Secured Resource"],"responses":{"200":{"description":"OK","content":{"application/json":{"schema":{"type":"string"}}}},"403":{"description":"Not Allowed"},"401":{"description":"Not Authorized"}},"security":[{"SecurityScheme":["admin"]}]}}`, but sometimes we get `"/secured/admin":{"get":{"tags":["Secured Resource"],"responses":{"200":{"description":"OK","content":{"application/json":{"schema":{"type":"string"}}}},"403":{"description":"Not Allowed"},"401":{"description":"Not Authorized"}},"security":[{"SecurityScheme":[]}]}}`

### How to Reproduce?

Steps to reproduce:

1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git`
2. `cd quarkus-test-suite && git checkout reproducer/openapi-definition-generation`
3. `cd security/keycloak-oidc-client-extended/`
4. `mvn clean verify -Dit.test=OpenApiStoreSchemaIT` (repeat till you experience failure, good luck)

Please checkout daily builds of our CI for failures we experienced https://github.com/quarkus-qe/quarkus-test-suite/actions/workflows/daily.yaml, notably build #770.

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 23.2

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by MikeEdgar** [comment]
@michalvavrik , when did this start happening? I'm curious if it coincides with https://github.com/quarkusio/quarkus/pull/31671

**Comment by michalvavrik** [comment]
@MikeEdgar hard to say because I added this check when you removed roles from basic scheme (to make ti compliant with specs). so I don't know about 2.16

**Comment by michalvavrik** [comment]
that is I added this test right after #31671

**Comment by MikeEdgar** [comment]
@michalvavrik I haven't been able to reproduce it using the instructions you gave with your fork/branch. Looking at [daily build 770](https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4506103973), it looks like it only failed in the native test - or am I missing something?

**Comment by michalvavrik** [comment]
@MikeEdgar nah, it's not related to native/jvm mode, for example https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4463205558 (that's build 766, before I added debugging info). I'm not surprised you have not been able to reproduce it, welcome to the club :-) Sometimes things behaves differently in CI as it's naturally slower than your workstation (or it's not related to performance; like it can only happen at certain build step order, don't know) . So far, we have experienced it 3 times (770, 766. 762), which is not that little considering I added this test a week and half back. There will be no more failures as we disabled the check on Friday, you can set up similar CI on your fork if needed.

**Comment by michalvavrik** [comment]
@MikeEdgar I've got good news, it also fails with RESTEasy Reactive. Please see build number 779 https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4585690826/jobs/8098110705, thank you

**Comment by michalvavrik** [comment]
For reasons I explained here https://github.com/quarkus-qe/quarkus-test-suite/pull/1217#issuecomment-1539030555 I'd like to keep issue opened. WDYT @MikeEdgar ? If there won't be a fix for this, short note in docs should do. I realize this is the edge case, but it is important to have this recorder. Thank you

**Comment by michalvavrik** [comment]
hey @MikeEdgar , the very first daily build failed with disabled Basic auth. I'm afraid there are other factors that are (also?) causing this behavior. I'm going to disable tests again https://github.com/quarkus-qe/quarkus-test-suite/pull/1218 as when it one test fails other runs are cancelled and it doesn't really provide us with new information about failure.

https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4921408854/jobs/8791517634 module `Keycloak + OIDC Client + Extended` test `io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.OpenApiStoreSchemaIT.testJsonOpenApiPathAccessResource` you can check logs.

I still appreciate you took a time to look at this, thank you.

**Comment by michalvavrik** [comment]
Wait a minute, now that I'm thinking about it, why there is still `"SecurityScheme":{"type":"http","description":"Authentication","scheme":"basic"}` in generated OpenAPI definition? I don't really have time to check this week, but if you are not quicker, I'll check next week!

**Comment by MikeEdgar** [comment]
I think that perhaps `quarkus.http.auth.basic=false` needs to be set in the application.properties. I was running with the debugger and that probably influences the build/runtime application of the configuration properties.

**Comment by michalvavrik** [comment]
JAR is reused if only runtime properties has changed, so that makes sense.

**Comment by michalvavrik** [comment]
Well, I don't really know at which moment the resources are generated, sorry, don't have time to think about that right now. Let's try `quarkus.http.auth.basic=false` in app properties as you suggested and see.

**Comment by MikeEdgar** [comment]
@michalvavrik I see the daily job had failures, but they don't seem related to this issue anymore.

The next phase for this issue will be to address the missing support for multiple security configurations.

**Comment by michalvavrik** [comment]
Sorry @MikeEdgar, I missed your comment somehow. Sounds good, sure, I'd report it here if there were any related failures. 

> The next phase for this issue will be to address the missing support for multiple security configurations.

I'm glad we are further now, but bug (or missing support, whatever we call it) still can affect customers, therefore I'd prefer to keep issue open. Thanks again

**Comment by michalvavrik** [comment]
@MikeEdgar fix certainly did a trick, so I'll close the issue, thanks
