### ISSUE TITLE
Define how an extension or feature of an extension is marked as beta

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3212]
We need to define a way to set an extension or a set of features as "beta".
If an extension, I imagine that the metadata will hold that per release.

**Comment by kenfinnigan** [comment]
That's what we did with TT. We had metadata that indicated the stability of the extension.

We went so far as to create several BOMs based on that stability, but we probably don't need that extreme

**Comment by gsmet** [comment]
Done in the platform.
