### ISSUE TITLE
@InjectMock should enable RETURNS_SMART_NULLS for Mockito

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#32134]
### Description

Mockito returns null for unstubbed methods. This is problematic for methods that expect a non-null value and can be hard to track down.

Mockito has a solution to make locating these unstubbed calls easier using https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#RETURNS_SMART_NULLS.

I don't think there's a downside to enabling for all mocks generated by `@InjectMock`.

**Comment by geoand** [comment]
I am a little confused, can this be uses together with `Mockito.RETURNS_DEEP_STUBS` or are they mutually exclusive?

**Comment by kdubb** [comment]
I've never used `RETURNS_DEEP_STUBS` but it sounds like they might be. `RETURNS_SMART_NULLS` returns a special "null" that I guess you could consider a mock; it's just a mock that throws exceptions if it is ever used.

**Comment by kdubb** [comment]
I noticed that `@InjectMock` allows you to enable `RETURNS_DEEP_STUBS`. Maybe we can enable smart nulls unless the user has enabled deep stubs. I found the special nulls to be immensely helpful when updating or fixing tests that use mocks.

**Comment by geoand** [comment]
If we do make `RETURNS_SMART_NULLS` the default, I assume it's sort of a breaking change?

**Comment by kdubb** [comment]
Not really. Currently, if you don't provide a stub for a method of a mock and it is called it simply returns null. If that null is ever used you'll get an NPE. With this change an exception will still be raised but it will be more descriptive of what has happened and includes what line the unstubbed method was called.

**Comment by geoand** [comment]
I see, thanks

**Comment by geoand** [comment]
I opened https://github.com/quarkusio/quarkus/pull/32149 to take care of this.

I also did label it as a breaking change as the changes to the tests show.

**Comment by geoand** [comment]
I am actually going to close this as it causes too many issues with the reactive tests
