### ISSUE TITLE
upgrade-to-quarkus3 jbang script | switch/case issues

### ISSUE THREAD

**Issue by heubeck** [quarkusio/quarkus#32145]
### Describe the bug

Using the Quarkus 3 migration script acc. to https://quarkus.io/blog/quarkus-3-0-0-beta1-released/#automated-migration rewrote switch expressions (Java 19 with preview-features):

Git diff before/after running `jbang --fresh upgrade-to-quarkus3@quarkusio`:

![image](https://user-images.githubusercontent.com/40993644/227792170-a694cd60-d915-4a46-bdcc-26e49287a742.png)

### Expected behavior

Switch expressions keep untouched.

### Actual behavior

Switch expressions gone wild.

### How to Reproduce?

Migrate a Quarkus 2.16 app using Java 19 with preview-features that contains switch expressions with pattern matching to Quarkus 3 using the jbang migration script.

### Output of `uname -a` or `ver`

Linux fedora 6.2.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 17 16:16:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "19" 2022-09-20 OpenJDK Runtime Environment Temurin-19+36 (build 19+36) OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)

### GraalVM version (if different from Java)

not used

### Quarkus version or git rev

2.16.5 to 3.0.0.Alpha5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

Thanks for the Quarkus-Experience!

**Comment by maxandersen** [comment]
This looks like a openrewrite limitation. Thanks for reporting it.

Any chance you have a project/reproducer? 

It could be dependent on other factors than just the  presence of switch statements thus having the exact project would ensure we are fixing the right thing.

**Comment by gsmet** [comment]
I'm surprised OpenRewrite rewrite the Java code while we don't have any rule for that.

We definitely need a reproducer so that we can report it to OpenRewrite.

Thanks.

**Comment by heubeck** [comment]
Please find the reproducer attached: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/11089986/code-with-quarkus.zip)

Just run `jbang --fresh upgrade-to-quarkus3@quarkusio` with JDK 17 in the project.

**Comment by gsmet** [comment]
@knutwannheden I can reproduce the issue here and `case` is rewritten to `defaultcase`. I will try to upgrade to a newer version of the Maven plugin and see how it goes.

**Comment by gsmet** [comment]
@knutwannheden same result with the Maven plugin 4.42.0.

The upgrade reports:
```
[WARNING] Changes have been made to pom.xml by:
[WARNING]     io.quarkus.updates.core.quarkus30.Quarkus3
[WARNING]         org.openrewrite.maven.ChangePropertyValue: {key=quarkus.platform.version, newValue=3.0.0.Alpha5}
[WARNING]             org.openrewrite.Recipe$AdHocRecipe
[WARNING]         org.openrewrite.maven.ChangePropertyValue: {key=quarkus.version, newValue=3.0.0.Alpha5}
[WARNING]             org.openrewrite.Recipe$AdHocRecipe
[WARNING] Changes have been made to src/main/java/org/acme/GreetingResource.java by:
[WARNING]     io.quarkus.updates.core.quarkus30.Quarkus3
[WARNING]         org.openrewrite.java.migrate.jakarta.JavaxWsToJakartaWs
[WARNING]             org.openrewrite.java.ChangePackage: {oldPackageName=javax.ws, newPackageName=jakarta.ws, recursive=true}
```

so I'm not sure why OpenRewrite actually changes `case` to `defaultcase`.

**Comment by maxandersen** [comment]
Ive seen similar in other langue constructs introduced in newer java. Openrewrite reads the source into and ast and writes it back out. If a new specialized node is introduced ie. Defaultcase is a subclass of case things like this happens. 

It would be great if openrewrite would fail if it bumps into a new node type rather than try to approximate.

**Comment by jtama** [comment]
Maybe though this could be documented somewhere, as switch case are a thing and are used more and more commonly.
