### ISSUE TITLE
CORS bug when preflight request is made to REST resource

### ISSUE THREAD

**Issue by cristhiank** [quarkusio/quarkus#3215]
**Describe the bug**
When you enable CORS and your REST endpoints are installed in root, the RESTEasyFilter overlaps the CORSFilter and it nevers get called.

**Expected behavior**
The CORS headers should be added to the reponse.

**Actual behavior**
No CORS headers added to the response.

**To Reproduce**
1. Create a REST Enpoint located in the root [@]Path("/") or [@]ApplicationPath("/")
2. Enable cors quarkus.http.cors=true
3. Make a preflight request to the endpoint curl -v -X OPTIONS -H "Origin: whatever" http://localhost:8080/

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.cors=true
```

**Screenshots**
![Screen Shot 2019-07-13 at 9 52 18 AM](https://user-images.githubusercontent.com/1218220/61173099-10d8f280-a554-11e9-9a34-6d162e728b59.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macOS
 - Output of `java -version`:  11.0.3
 - GraalVM version (if different from Java):  19.0.2
 - Quarkus version or git rev:  0.19.1 / or master

**Additional context**
Found this while trying to help to resolve this question: https://groups.google.com/forum/#!topic/quarkus-dev/zrXlgRgdoD4

**Comment by gwenneg** [comment]
I assigned you this issue since you said you'd submit a PR in the mailing list discussion.
