### ISSUE TITLE
JNDI confguration

### ISSUE THREAD

**Issue by ouazou** [quarkusio/quarkus#32165]
### Discussed in https://github.com/quarkusio/quarkus/discussions/25039

<div type='discussions-op-text'>

<sup>Originally posted by **hikemachado** April 20, 2022</sup>
Hi All,
I'm using pantaho reports and the reports files (.prpt) are configured to use JNDI datasource connection, I'm trying to configure JNDI in quarkus , I've already changed the property quarkus.naming.enable-jndi=true, but I still not able to connect using the JNDI name "mydb"

My `application properties` :

```properties
quarkus.naming.enable-jndi=true
quarkus.datasource.mydb.db-kind=mysql
quarkus.datasource.mydb.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.mydb.jdbc.url=jdbc:mysql://localhost:3306/mydb
quarkus.datasource.mydb.username=root
quarkus.datasource.mydb.password=root
```

trying to access jndi using name =  "mydb"

the exception is:

Failed to access the JNDI system: Cannot find the requested datasource 'mydb' anywhere in the JNDI system.

Thanks
Henrique</div>

**Comment by geoand** [comment]
Can you attach a sample application we can use to debug?

Thanks

**Comment by geoand** [comment]
Closing as we never got a reproducer
