### ISSUE TITLE
Implement a CLI plugin for helm

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#32174]
### Description

Currently, when using quarkus with helm, the user need to use the `helm` cli in order to install, uninstall and update the chart.
These commands do require some arguments that are boilerplate. 

For example:
```
helm install helm-example ./target/helm/kubernetes/<chart name>
```

It would be great if we had a very simple cli plugin that could pickup the boilerplating values from the project. So, that the user would just need to write:

```
quarkus helm install
```

### Implementation ideas

AFAIK Helm v3 is working purely on client side (there is no server side). This means that we pretty much have to reuse the `helm` binary, as I don't think there is a java library that we can use for installing the chart itself.

The CLI itself could be a picocli moudle under the helm extension, and we could declarate that the extension brings in a cli plugin using something like: https://github.com/quarkiverse/quarkus-authzed-client/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L12

**Comment by bulldog98** [comment]
There is already a community driven extension for helm (https://github.com/quarkiverse/quarkus-helm).

**Comment by maxandersen** [comment]
The extension generates helm. The cli here is to be able to invoke/install the helm binary to use the output of the extension. 

That's at least how I understand @iocanel s description

**Comment by cmoulliard** [comment]
Not sure that it could help as the project has been created 6 years ago around Helm2, is using Fabric8 Java client: see microbean-helm - https://stackoverflow.com/questions/40783681/kubernetes-helm-java-api

@iocanel

**Comment by iocanel** [comment]
> Not sure that it could help as the project has been created 6 years ago around Helm2, is using Fabric8 Java client: see microbean-helm - https://stackoverflow.com/questions/40783681/kubernetes-helm-java-api
> 
> @iocanel

I am afraid that this doesn't help. In helm v2 most of the job was done server side and therefore it was possible to just create a client the sends the charts to the server. In helm v3 all the work is done in the client side.  This means that we need to use the client or rewrite the thing in java.

**Comment by cmoulliard** [comment]
> I am afraid that this doesn't help. In helm v2 most of the job was done server side

I fully agree. If we use then the helm binary, how will it be possible to configure the quarkus client to figure out the path to be used to access the binary ? How will it be possible to know how the `helm install` command and their parameters will be mapped to `quarkus helm install` or `quarkus helm uninstall`.

**Comment by iocanel** [comment]
All the information we need can be easily be obtained from the project.
All we need to do is get the info and pass it to `helm install`.

**Comment by cmoulliard** [comment]
> so this extension is just to help wrap invocation of helm with standard parameters?

Yes. 

We should, of course, review which helm commands we will invoke but for the standard one `helm install`, the quarkus extensions (kubernetes, openshift and helm) will help us to populate this command 

```
helm install \
  fruits-app // maven name or quarkus.kubernetes.name
  halkyonio/fruits-app // helm chart (= what it has been generated locally) \
  -n (optional) // quarkus.kubernetes.namespace=mynamespace
  --set app.image=quay.io/halkyonio/atomic-fruits:latest \ // helm value generated by quarkus helm
  --set app.host=atomic.127.0.0.1.nip.io \ // helm value generated by quarkus helm
  --set db.auth.database=atomic-fruits \ // helm value generated by quarkus helm
  --set db.auth.password=Secr3t \ // helm value generated by quarkus helm
  --set db.auth.username=admin // helm value generated by quarkus helm
```
**Remark**: As the quarkus helm extension supports also to include helm dependencies, then it will also be possible when we execute the `quarkus helm install` to deploy them too

**Comment by iocanel** [comment]
This might not be as trivial as I initially thought as it most probably requires: #32567

**Comment by ebullient** [comment]
Thanks. My suggestion, just by the bye, is that we always print out the helm command we're invoking (once parameters have been determined), to make the magic understandable.

**Comment by iocanel** [comment]
Added to quarkus-helm.

**Comment by cmoulliard** [comment]
Can you share the commit/PR where code and/or documented has been pushed please ? @iocanel

**Comment by iocanel** [comment]
@cmoulliard here you are: https://github.com/quarkiverse/quarkus-helm/pull/249
