### ISSUE TITLE
Generated application.properties.example doesn't include CORS property

### ISSUE THREAD

**Issue by MasterEx** [quarkusio/quarkus#3218]
**Describe the bug**

When generating an example application.properties files the `quarkus.http.cors` entry is missing. The other cors related entries are present as expected (i.e. `quarkus.http.cors.exposed-headers`).

**Expected behavior**

I would expect the example file to include all the available possible properties, including `quarkus.http.cors` along-side a relative comment.

**Actual behavior**

The `quarkus.http.cors` entry is not present

**To Reproduce**
1. Create a quarkus project `mvn io.quarkus:quarkus-maven-plugin:0.19.1:create` with the default values (or use an existing one)
2. From within the project `cd my-quarkus-project/` generate an `application.properties.example` file `./mvnw quarkus:generate-config`
3. Check the created file `src/main/resources/application.properties.example` for the missing entry. There is not a `quarkus.http.cors` present. The other cors related entries are present:

```bash
grep 'cors' src/main/resources/application.properties.example 
#quarkus.http.cors.exposed-headers=
#quarkus.http.cors.headers=
#quarkus.http.cors.methods=
#quarkus.http.cors.origins=
```

**Environment:**
 - Quarkus version or git rev: reproduced on quarkus 0.18, 0.19 and 0.19.1
 - Maven version: `Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T21:41:47+03:00)`
 - Maven wrapped version: `Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T22:00:29+03:00)`

**Comment by gwenneg** [comment]
Hi @MasterEx and thanks for reporting this!

**Comment by gwenneg** [comment]
@dmlloyd: It seems that all classes annotated with `@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED)` are ignored when the `application.properties.example` is generated. Is this an expected behavior?

**Comment by gwenneg** [comment]
If it is not expected, then my PR is ready for a review.
