### ISSUE TITLE
Support registering a ClientHeadersFactory in the rest client programmatic API

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#32189]
### Description

It would be useful to be able to register client headers factories through the programmatic API. Example :
```
@Inject
RequestUUIDHeaderFactory  factory;
...
MyService myService = RestClientBuilder.newBuilder()
            .baseUri(URI.create("https://stage.code.quarkus.io/api"))
            .clientHeadersFactory(factory)
            .build(MyService.class);
```
Using a programmatic rest client is one solution when using a rest interface coming from a jar external to the application (most likely coming from non quarkus applications). In that case it is not possible to add additional quarkus annotations, such as `@RegisterRestClient` or `@RegisterClientHeaders`.

See this zulip [chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/rest-client)

**Comment by radcortez** [comment]
Yes, but this was requested a long time ago without considerable progress:
https://github.com/eclipse/microprofile-rest-client/issues/283

Maybe we need to consider providing our own enhanced ClientBuilder API.

**Comment by geoand** [comment]
> Maybe we need to consider providing our own enhanced ClientBuilder API

+1

**Comment by Sgitario** [comment]
> > Maybe we need to consider providing our own enhanced ClientBuilder API
> 
> +1

I've created this issue https://github.com/quarkusio/quarkus/issues/32856 for this.

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/32880 should take care of this feature request.
