### ISSUE TITLE
quarkus-mailer: Mocking does not work when using a service

### ISSUE THREAD

**Issue by Doogiemuc** [quarkusio/quarkus#32206]
The MockMailboxImpl introduces here

https://github.com/quarkusio/quarkus/pull/2804/commits/fa4e88f9977cd81de3902e602b49694e7c5af073

Does not work, when the mail is sent from a service, but then you try to fetch the (mocked) mail from within a `@QuarkusTest`. There are two different instances of MockMailbox impl.  See this Stackoverflow issue with all detailed infos:

https://stackoverflow.com/questions/75873242/quarkus-mailer-does-not-receive-mail-in-test-when-mocked

**Comment by geoand** [comment]
Can you please attach a sample project that exhibits the problematic behavior?

Thanks

**Comment by Doogiemuc** [comment]
Ok, yes, will do as soon as I can.

**Comment by Doogiemuc** [comment]
ooh nooo. I created a small test project. And there the MockMailbox works as expected :-)   

So I have to dig into my bigger project, why it doesn't work there :-(

I have a lot of quarkus dependencies  (panache, graphql, ...)  I have to search why I seem to have to instances of the Mock Mailer ...

This is the little test. That works ..
https://www.dropbox.com/s/wrq3zf0dx9uu5f3/quarkus-test-mailer.zip?dl=0

**Comment by geoand** [comment]
Thanks for the update
