### ISSUE TITLE
devui for resteasy reactive give 0% rating when no endpoints yet

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#32216]
### Describe the bug

if you create a project and add resteasy extension devui shows this by default:

![2023-03-29_12-17-14](https://user-images.githubusercontent.com/54129/228510009-0e8c2420-7b9f-4400-9e36-83dc59ae636d.png)

Its a bit discouraging getting a red arrow 0% fail graphic when one haven't even started yet :)

### Expected behavior

show nothing or "no end points" graphic/text  instead?

**Comment by geoand** [comment]
@phillip-kruger is there anything you need from the "server side" for this?

**Comment by phillip-kruger** [comment]
@geoand No I think we are ok. Do you (and / or @FroMage ) want to also change the look ? There are some concerns on the gauge on the dashboard . How  about just the score in a big number ?

**Comment by geoand** [comment]
I'm the last person that should comment on the UI.

I personally like the gauge very much, but I see others are concerned...

**Comment by phillip-kruger** [comment]
@geoand Yea I also like the gauge, but I am happy to go with what the extension owners want to do... :)

**Comment by geoand** [comment]
My vote is to keep it. But there seems to be mounting criticism of it 😎
