### ISSUE TITLE
Qute template extensions are not resolved reliably

### ISSUE THREAD

**Issue by c-classen** [quarkusio/quarkus#32220]
### Describe the bug

I am working on a Quarkus project where Qute is used to render an HTML file. The project uses Kotlin with annotation processing (for generating a Hibernate meta model) and gradle as build tool. The template file contains a call to an Qute extension method of `ZonedDateTime` which is defined in `TimeTemplateExtensions`:

```
{deliveryNote.createdAt.atZoneSameInstant(timezone).format('dd.MM.yyyy')}
```
which on some builds causes the following error:
```
io.quarkus.qute.TemplateException: deliveryNotePdf.html:132:22 - {deliveryNote.finishedAt.atZoneSameInstant(timezone).format('HH:mm')}: Property/method [format('HH:mm')] not found on class [java.time.ZonedDateTime] nor handled by an extension method
```

The problem is that I cannot reproduce the error reliably. Sometimes, I will get this error and when I run the `assemble` or `quarkusDev` task again without changing the source code, it will work. Sometimes, it will still fail on subsequent tries, but when I change an unrelated part of the source code, it will work again.

Maybe there is some sort of race condition in the process of type checking the template where the extension methods are not available yet when the template is processed.

### Expected behavior

I expect the build to succeed or at least fail consistently in case I actually did something wrong when calling the extension method

### Actual behavior

It says `Property/method [format('HH:mm')] not found on class [java.time.ZonedDateTime] nor handled by an extension method`, even though there is a method
```
static String format(TemporalAccessor temporal, String pattern)
```
in `TimeTemplateExtensions` and `ZonedDateTime` implements `TemporalAccessor`.

### How to Reproduce?

Sadly I have not been able to build a reproducer. I tried building a project using Kotlin, Gradle and using Kapt, but the error never occurred there.

### Output of `uname -a` or `ver`

5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "14.0.2" 2020-07-14 OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

**Comment by mkouba** [comment]
I believe that [this pull request](https://github.com/quarkusio/quarkus/pull/30593) fixes the problem. @c-classen Could you pls test your app with Quarkus 2.16.5.Final or 3.0.0.CR1?

**Comment by c-classen** [comment]
Thank you for the suggestion. I tried 2.16.5.Final and the next few builds worked. Due to the seemingly nondeterministic nature of this issue, I don't know for sure it was fixed, but I'll close this issue for now and reopen it in case the problem comes up again
