### ISSUE TITLE
Dev UI 2 - Fonts are blurry (Chrome / Fedora)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32230]
Using Chrome on a standard Fedora desktop, the fonts for title are very blurry. It's especially visible in light mode.
Firefox is a bit better but not so much.

I tried to check which fonts were used and apparently it's something called `Red Hat text`. Is it a webfont we load?

I'm not sure if I'm the only one observing this but it doesn't look very good and makes it very hard to read for me.

![2023-03-29 16 26 15 localhost 23da7fe75f0a](https://user-images.githubusercontent.com/1279749/228572103-f912fe11-9b3d-4aaf-aec6-268aaa024a36.png)

**Comment by gastaldi** [comment]
Weird, mine looks okay

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/54133/229204957-5db7cb47-fea0-403a-9638-e85ec0450445.png">

**Comment by gastaldi** [comment]
Actually I am seeing some errors in the console with may be related:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/54133/229205434-21bf44e7-7a9b-4909-a3c4-7ab28cea3cbd.png">

**Comment by gastaldi** [comment]
About the RedHat font, I think it's this one: https://github.com/RedHatOfficial/RedHatFont

**Comment by phillip-kruger** [comment]
Ok, for me it also loading fine, but this still comes from when I was prototyping with patternfly-elements. We can probably remove it. and use the default ? Or see what is loaded with vaadin ?

**Comment by phillip-kruger** [comment]
We can probably just remove and use https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/typography

**Comment by gastaldi** [comment]
> We can probably just remove and use https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/typography

That makes sense I guess

**Comment by susobhandas07** [comment]
check for fractional scaling, if featured turned on fonts in chromium based instances are blurred, when turned off everything seems sharp again, worked for me, I am on fedora 39
