### ISSUE TITLE
Dev UI 2 - Generalize No Dev Services element

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32234]
When we don't have any RESTEasy Reactive endpoints, we have a big blank page, which is not very user friendly.

Especially since you have the same blank page if an error occurred in the Dev UI.

Someone created a nice component for Dev Services and I wonder if we should generalize it and have a component to call when no items are available.

The component would take a full message (i.e. `You do not have any Dev Services running.`) and an optional link to a guide (maybe with a default `See the documentation for more information` and possibility to tweak the message).

The component looks like:

![2023-03-29 17 07 36 localhost 279f6e09862c](https://user-images.githubusercontent.com/1279749/228584748-c006c3a6-4440-4a8d-9c85-9a5ba1d618d0.png)

Note that this is not a priority but something nice to have for the future.

**Comment by phillip-kruger** [comment]
Sounds good to me. Do you want to build that component?
