### ISSUE TITLE
Showing the profile in the first line of log after start running Quarkus

### ISSUE THREAD

**Issue by ma-sharifi** [quarkusio/quarkus#32231]
### Description

I was wondering why we have to wait to see which profile is loaded in log. 
The problem is:
In the Spring Boot application, I can even see my profile, on the first line of the log.
But in Quarkus, After loading everything, and ruining TestContainers, and Flyway scripts,... eventually, I can see my profile.

```java
@ApplicationScoped
class Starter
{
  @Inject
  Logger LOGGER;

  void onStart(@Observes StartupEvent ev)
  {
    LOGGER.info("#The application is starting... ." + " Profile is: " + ProfileManager.getActiveProfile());
  }
  void onStop(@Observes ShutdownEvent ev)
  {
    LOGGER.info("#The application is stopping...");
  }
}
```
I used the above code to see, which profile is selected.
Quarkus log it after above code:
2023-03-29 16:29:34,715 INFO  [io.quarkus] Profile test activated. 

### Implementation ideas

I expected there was a way can see which profile is selected in the first lines of the application log.

**Comment by Crossbears** [comment]
Hi:
Could you please assign this one to me? I want to try to pick this up.

**Comment by Chu3laMan** [comment]
Hi,

Already fix this issue on the following MR, https://github.com/quarkusio/quarkus/pull/44408 

If there is any remarks, let me know.

Thanks

**Comment by geoand** [comment]
Closing as per https://github.com/quarkusio/quarkus/pull/44408#issuecomment-2510114485
