### ISSUE TITLE
io.vertx:vertx-web:4.3.7 has a known vulnerability

### ISSUE THREAD

**Issue by eijckron** [quarkusio/quarkus#32241]
### Description

Quarkus uses io.vertx:vertx-web:4.3.7 which has a [known vulnerability]( https://github.com/advisories/GHSA-53jx-vvf9-4x38)

### Implementation ideas

Update to at least version 4.3.8 in which the vulnerability is fixed.

**Comment by cescoffier** [comment]
We cannot update to 4.3.8. The next update will use 4.4.1.
