### ISSUE TITLE
Jacoco doesn't cover a class that is an injection by constructor

### ISSUE THREAD

**Issue by mpusg** [quarkusio/quarkus#32254]
### Describe the bug

Hi guys 

Today we have a coverage problem with jacoco. An ApplicationScope bean that use an injection by constructor isn't cover by jacoco. 

### Expected behavior

Jacoco should cover all classes, whatever the way of dependency injection. 

### How to Reproduce?

You have an example project by file zip file just at the end of this message. 

### Output of `uname -a` or `ver`

MSYS_NT-10.0-19045 3.3.6-bec3d608-341.x86_64 2023-02-22 08:29 UTC x86_64 Msys

### Output of `java -version`

Java version: 17.0.6, vendor: BellSoft, runtime: scoop\apps\liberica17-full-jdk\current

### Quarkus version or git rev

2.16.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

### Additional information

[jacoco.zip](https://github.com/quarkusio/quarkus/files/11109154/jacoco.zip)

Thanks !

**Comment by vsevel** [comment]
when we use the injection by constructor, we see:
```
[INFO] --- jacoco-maven-plugin:0.8.8:report (report) @ getting-started ---
[INFO] Loading execution data file E:\tmp\getting-started-jacoco\target\jacoco.exec
[INFO] Analyzed bundle 'getting-started' with 3 classes
[WARNING] Classes in bundle 'getting-started' do not match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class org/acme/MyBean does not match.
```

and `/target/site/jacoco/org.acme/MyBean.java.html#L11` has 0 coverage.

instead of:
```
[INFO] --- jacoco-maven-plugin:0.8.8:report (report) @ getting-started ---
[INFO] Loading execution data file E:\tmp\getting-started-jacoco\target\jacoco.exec
[INFO] Analyzed bundle 'getting-started' with 3 classes
```

**Comment by vsevel** [comment]
you are right @mkouba: a default constructor with `package` or `public` visibility makes jacoco happy  (does not work with `private`).

**Comment by vsevel** [comment]
> In fact, there is more bytecode tempering Quarkus can do (and not just in CDI), so technically you should feed jacoco the sources after Quarkus finishes build, but I am not sure that's possible

hmm. that would be nice. especially because jacoco fails on the class silently (just a warn in the build logs).
the only reason we spotted it was because we failed the coverage quality gate on sonar.

**Comment by geoand** [comment]
IIRC, Jacoco skips over code if it has the `synthetic` modifier, but I was also under the impression that Arc does add that modifier when it adds a no-args constructor

**Comment by geoand** [comment]
[This](https://github.com/quarkusio/quarkus/blob/2b32749ce9253fa221f85f089c22a3d49d4fa3d5/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Beans.java#L1043) seems to indicate that we do add the proper modifier.

**Comment by geoand** [comment]
Maybe the fact that it's `public` is causing the problem? Can the constructor be made package private @mkouba @manovotn ?

**Comment by geoand** [comment]
In any case, I opened: https://github.com/quarkusio/quarkus/pull/32267. Would anyone be able to try it on their application?

**Comment by manovotn** [comment]
> IIRC, Jacoco skips over code if it has the synthetic modifier, but I was also under the impression that Arc does add that modifier when it adds a no-args constructor

Interesting, didn't know that.

> Maybe the fact that it's `public` is causing the problem? Can the constructor be made package private @mkouba @manovotn ?

Yes, that should work. CDI needs any non-private.

**Comment by vsevel** [comment]
does not seem to happen when using the quarkus jacoco extension

**Comment by geoand** [comment]
Thanks for the update @vsevel
