### ISSUE TITLE
Quarkus seems to need source files in the maven root folder in order to work

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#3226]
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.19.1:dev (default-cli) on project eddi: The project eddi has no output yet. Make sure it contains at least on source or resource file
```
In this case, i try to build a multi maven project. The root doesn't have a src folder therefore also no target folder. However, all the sub-modules have source folders, therefore a valid structure.

mvn clean package works fine.

./mvnw compile quarkus:dev  however throws the above error. 

only if there is a target folder containing build information is quarkus satisified.

In a multi-module maven project quarkus should ignore if there is a src folder or not in case there are sub-modules available.

**Comment by rquinio** [comment]
This is same cause as #3240: quarkus-maven-plugin is not supposed to be executed on a parent aggregator with pom packaging, but on a jar packaging sub-module.

**Comment by ginccc** [comment]
I moved it to the packaging sub-module, but now it complains about not know about quarkus in maven

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.684 s
[INFO] Finished at: 2019-07-19T12:41:34+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'quarkus' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (c:\dev\.m2), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

This is the pom file of the sub-module that should build the application: https://github.com/labsai/EDDI/blob/feature/quarkus/apiserver/pom.xml#L169

And this is the parent pom file, in which i originally had defined it: https://github.com/labsai/EDDI/blob/feature/quarkus/pom.xml#L70


What am I doing wrong here?

**Comment by rquinio** [comment]
I guess you are trying to run `mvn quarkus:dev` at the root of the project ?
It complains that there's no quarkus plugin defined in the root poms.

What you can do from root folder is `mvn quarkus:dev -pl apiserver` and it will watch for file changes in the other sub-modules as well, to hot-redeploy on the next request. I tried to wrote a quickstart about that here: https://github.com/quarkusio/quarkus-quickstarts/pull/229/files#diff-22d4fe842bd671f22e489d0917d9d707

**Comment by ginccc** [comment]
> I guess you are trying to run mvn quarkus:dev at the root of the project ?
yes, you are absolutely right about that!

Thanks!

**Comment by Funmi5160** [comment]
i have the error of  "No plugin found for prefix 'quarkus' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories..."
I am new on this,
Please what do I do?

**Comment by lsolier** [comment]
I have the same problem that @Funmi5160

**Comment by angelojrp** [comment]
Add the configuration in the pom parent, works fine for me
```
<build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <parameters>${maven.compiler.parameters}</parameters>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>${quarkus.platform.group-id}</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.platform.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```
