### ISSUE TITLE
Dev Ui unavailable without resteasy or resteasy-reactive

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#32274]
### Describe the bug

If you write a consumer for one of the message based brokers (mqtt, rabbitmq, ...) one should not need the resteasy(-reactive) extension to see the dev ui.

### Expected behavior

Dev UI should start

### Actual behavior

Dev UI is not started without one of quarkus-resteasy or quarkus-resteasy-reactive

### How to Reproduce?

https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=smallrye-reactive-messaging-mqtt&e=scheduler&S=io.quarkus.platform%3A3.0&extension-search=resteasy

Note this also is the case with the 2.x line.

**Comment by maxandersen** [comment]
minimal requirement to have dev/ui is to add vertx-http.

you can have it be optional as part of a maven profile or gradle config.

**Comment by geoand** [comment]
Closing as per Max's comment above

**Comment by bulldog98** [comment]
It would be nice, if there was a doc for that. I had to fumble around in intelli sense to find out that the gradle plugin has a `quarkusDev` function that works like `implementation`, but only for the dev mode. Also I did not see something like that in docu for maven

**Comment by aloubyansky** [comment]
See https://quarkus.io/guides/gradle-tooling#dev-mode
