### ISSUE TITLE
Test execution fail on Intellij

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#32273]
### Describe the bug

On a fully built and loaded Quarkus 3, with main, trying to run or debug tests with the IDE  triggers this error:

```
quarkus/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/wrongannotations/BeanWithIncorrectInject.java:18:46
java: package org.gradle.internal.impldep.javax.inject does not exist
```

This annotation is not resolved:
`@org.gradle.internal.impldep.javax.inject.Inject`

Example test to trigger the issue:
`io.quarkus.opentelemetry.deployment.OpenTelemetryHttpCDITest`

### Output of `uname -a` or `ver`

Darwin ... 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

temurin-17.0.4.1

### Quarkus version or git rev

Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven/3.8.7 

### Additional information

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

**Comment by geoand** [comment]
Are you saying that IntelliJ can't run the tests of the Quarkus repo itself?

If so, that is unsurprising given the complexity of the project.

**Comment by brunobat** [comment]
It was possible before and if you comment that annotation, all works.

**Comment by geoand** [comment]
I have personally never been able to run anything from the IDE on the Quarkus repo.

**Comment by geoand** [comment]
@mkouba where does `@org.gradle.internal.impldep.javax.inject.Inject` in `io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject` come from?

**Comment by mkouba** [comment]
> @mkouba where does `@org.gradle.internal.impldep.javax.inject.Inject` in `io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject` come from?

It's bundled in the `quarkus-bootstrap-gradle-resolver` which is a dependency of `quarkus-test-common`.

**Comment by geoand** [comment]
Hm... 

Maybe as trips up IDEs we can just use some custom annotation for the purposes of the test?

**Comment by mkouba** [comment]
> I have personally never been able to run anything from the IDE on the Quarkus core repo.

The same here.

> Maybe as trips up IDEs we can just use some custom annotation for the purposes of the test?

We could just remove this annotation from the test. `javax.inject.Inject` and `com.google.inject.Inject` are the important ones that need to be tested explicitly.

**Comment by geoand** [comment]
@brunobat would you like to do a PR with ^?

Asking because we can't get the IDE to work anyway and you seem to be able to :)

**Comment by brunobat** [comment]
Cool, will do

**Comment by brunobat** [comment]
Curious... once I remove that annotation, the WrongInjectTest test fails:
```
org.opentest4j.AssertionFailedError: jakarta.enterprise.inject.spi.DeploymentException: Found 4 deployment problems: 
[1] @com.google.inject.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm1, use @jakarta.inject.Inject instead
[2] @javax.inject.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm2, use @jakarta.inject.Inject instead
[3] @javax.inject.Inject declared on io.quarkus.arc.test.wrongannotations.WrongInjectTest.beanManager, use @jakarta.inject.Inject instead
[4] @com.oracle.svm.core.annotate.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm3, use @jakarta.inject.Inject instead ==> 
Expected :true
Actual   :false
````

**Comment by mkouba** [comment]
> Curious... once I remove that annotation, the WrongInjectTest test fails:
> 
> ```
> org.opentest4j.AssertionFailedError: jakarta.enterprise.inject.spi.DeploymentException: Found 4 deployment problems: 
> [1] @com.google.inject.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm1, use @jakarta.inject.Inject instead
> [2] @javax.inject.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm2, use @jakarta.inject.Inject instead
> [3] @javax.inject.Inject declared on io.quarkus.arc.test.wrongannotations.WrongInjectTest.beanManager, use @jakarta.inject.Inject instead
> [4] @com.oracle.svm.core.annotate.Inject declared on io.quarkus.arc.test.wrongannotations.BeanWithIncorrectInject.bm3, use @jakarta.inject.Inject instead ==> 
> Expected :true
> Actual   :false
> ```

That's expected - you need to update[ the assertion](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/wrongannotations/WrongInjectTest.java#L23-L38) as well.

**Comment by geoand** [comment]
@brunobat can this be closed now?

**Comment by brunobat** [comment]
Yes. It's fixed now.
