### ISSUE TITLE
Quarkus uses deprecated WildFlyElytronProvider

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3227]
Quarkus uses deprecated WildFlyElytronProvider, this should be adjusted to the changes which caused that deprecation.

Deprecated via https://github.com/wildfly-security/wildfly-elytron/commit/e6b8dbed4e81ed00a27a9b4183374d8c3b42f03e, per-module providers were introduced.

@fjuma @darranl what should be used instead of WildFlyElytronProvider for Quarkus ?
CC @starksm64

**Comment by darranl** [comment]
There are some general security discussions that will clarify this further.

**Comment by gsmet** [comment]
@sberyozkin what's the status of this one? Does it still make sense?
