### ISSUE TITLE
DEVUI: Dynamic Labels broken in CR1

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32280]
### Describe the bug

Using a Dynamic Label this was working in Alpha6 and failing in CR1.

```java
final PageBuilder<ExternalPageBuilder> sessionPage = Page.externalPageBuilder("Session Timeout")
                .icon("font-awesome-regular:hourglass")
                .url("https://omnifaces.org/")
                .doNotEmbed()
                .dynamicLabelJsonRPCMethodName("getSessionTimeout");
```

Is failing because in `qwc-extension-links.js` with:

![image](https://user-images.githubusercontent.com/4399574/228949681-dfb630cc-78db-4ff9-bcfd-8f938220dbbc.png)

I can see the JsonRPC `extensionName` is null ?

cc @phillip-kruger 

### Quarkus version or git rev

3.0.0.CR1

**Comment by phillip-kruger** [comment]
Can you share a reproducer? Or do you have the extension code somewhere I can look at?

**Comment by melloware** [comment]
Yep git clone this: https://github.com/quarkiverse/quarkus-omnifaces

Run `mvn clean install` then go to integration tests and run `mvn quarkus:dev`

**Comment by phillip-kruger** [comment]
Great thanks. Will look at this later today
