### ISSUE TITLE
Quarkus 3.0.0.Alpha4 introduces a performance regression

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#32289]
### Describe the bug

A drop in mean throughput performance has been spotted while validating Camel Quarkus 3.0.0-M1 staging release upstream:
```
  2.16.0  |       30m  |  38804.35 req/s [+0.00%]  |   22357.99 req/s [+0.00%]  |                                OK  |
3.0.0-M1  |       30m  |  38857.07 req/s [+0.14%]  |   21166.75 req/s [-5.33%]  |  Potential performance regression  |
```

After investigation, it looks like the regression has been introduced when we switched to Quarkus 3.0.0.Alpha4.
From this version onward, there is a noticeable log related to direct buffers that could be a good candidate to explain the regression as shown below:
```
2023-03-29 19:32:02,511 INFO  [io.net.uti.int.PlatformDependent] (Thread-1)
Your platform does not provide complete low-level API for accessing direct buffers reliably.
Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
```

And we see in the native-image command line that a new argument has been introduced: `-J-Dio.netty.noUnsafe=true`
This new behavior comes from commit below: https://github.com/quarkusio/quarkus/commit/ca155cae76c7caf7d6c4bbf27e9ac22305d2dbf0

I've then tested with `-Dquarkus.native.additional-build-args=-J-Dio.netty.noUnsafe=false` and the performance regression is gone. Somehow, it could mean that netty could not use unsafe and so couldn't use direct buffers.
In the end resulting in a performance penalty.

### How to Reproduce?

The simplest way to to reproduce would be to run the Camel Quarkus performance regression tool, something like:
```
git clone git@github.com:apache/camel-quarkus.git
git checkout aa942c217a3dab5900ff175964641b798ccc62b5
mvn clean install -Dquickly
cd tooling/performance-regression
java -jar target/quarkus-app/quarkus-run.jar -an 2.16.0 3.0.0-SNAPSHOT
```

After 45 minutes run on a machine equally loaded over that period, it should print a report like:
```
                             Camel Quarkus Throughput Performance Increase Compared to Previous Version                             
 Camel Quarkus version  |  Duration  |   JVM req/s [%increase]   |  Native req/s [%increase]  |               Status               |
------------------------------------------------------------------------------------------------------------------------------------
                2.16.0  |       30m  |  38804.35 req/s [+0.00%]  |   22357.99 req/s [+0.00%]  |                                OK  |
        3.0.0-SNAPSHOT  |       30m  |  38857.07 req/s [+0.14%]  |   21166.75 req/s [-5.33%]  |  Potential performance regression  |
```

### Output of `uname -a` or `ver`

Linux me.csb 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

22.3.1.0-Final Mandrel Distribution (Java Version 17.0.6+10)

### Quarkus version or git rev

3.0.0.Alpha4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.7

**Comment by geoand** [comment]
cc @franz1981 @johnaohara

**Comment by gsmet** [comment]
FWIW, one option we have would be to revert the patch from @zakkak for the time being until we have a better understanding on how we can fix the original issue without disabling unsafe.

Given the schedule, that's probably the safest course of action.

**Comment by geoand** [comment]
> Given the schedule, that's probably the safest course of action.

+1

**Comment by luneo7** [comment]
And also backport the revert to the 2.16.x branch, since we also saw performance drop when bumping a minor version...

**Comment by gsmet** [comment]
thanks @luneo7 !
