### ISSUE TITLE
Cannot register an additional StandardServiceInitiator in hibernate-orm extension

### ISSUE THREAD

**Issue by atzoum** [quarkusio/quarkus#3231]
When building the `StandardServiceRegistry` inside `FastBootHibernatePersistenceProvider` there should be some way to register an additional `StandardServiceInitiator` apart from the default ones contained in `PreconfiguredServiceRegistryBuilder`. If this was possible, using Envers without including it in the hibernate-orm extension might be possible (see #3120).

The following TODO that exists in the source code might be relevant to that.
https://github.com/quarkusio/quarkus/blob/b11c1261626376c59744389551061174abae5d3d/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/FastBootHibernatePersistenceProvider.java#L191

@gsmet  any plans adding such a support or do you have something else in mind regarding this issue?

**Comment by gsmet** [comment]
It seems reasonable. TBH, I thought I fixed it when I worked on Hibernate Search. I'll take another look.

**Comment by atzoum** [comment]
Hibernate Search doesn't have a `ServiceInitiators` but has `org.hibernate.search.mapper.orm.mapping.impl.HibernateSearchContextServiceContributor` which adds `Service` objects in the  `io.quarkus.hibernate.orm.runtime.boot.registry.PreconfiguredServiceRegistryBuilder` which are passed afterwards as provided services when `StandardServiceRegistryImpl#resetAndReactivate` is called.

**Comment by gsmet** [comment]
Yup but I thought I did all of the extension points in one go. I'll take a look.

**Comment by atzoum** [comment]
Good to know that you will look into it! I will also try to mess a bit with the code and ping you if I believe I have found something

**Comment by atzoum** [comment]
`EnversService`needs to be initialized before calling `org.hibernate.envers.boot.internal.EnversIntegrator#integrate`. Currently initialization happens at `org.hibernate.envers.boot.internal.AdditionalJaxbMappingProducerImpl`. So it is not enough to just register `EnversServiceInitiator` in `PreconfiguredServiceRegistryBuilder` because the service won't be initialized...
I don't understand why the `PreconfiguredServiceRegistryBuilder` does this
https://github.com/quarkusio/quarkus/blob/89ea3f68e586a6c2b90b5f186918ddb9ca7b74dd/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/registry/PreconfiguredServiceRegistryBuilder.java#L105

Would it be enough for Envers to keep the initialized EnversService from the previous step by adding it in the providedServices list?

**Comment by machi1990** [comment]
@atzoum are you working on this?

**Comment by atzoum** [comment]
I am only trying to figure out the necessary changes in hibernate-orm so that I can use Envers in a quarkus app in jvm mode. So yes, sort of. I don't plan though to come up with an Envers extension, unless it is not possible without it.

**Comment by machi1990** [comment]
Okay great, thanks for the contribution. It is very welcomed. I think @gsmet should be available to give you some direction on how to go about it.

**Comment by atzoum** [comment]
@gsmet @machi1990  I managed to find some sort of solution, the cleanest I could think of given the circumstances! Please review and keep in mind that I still need to test this with an actual quarkus deployment (I don't know if the test I created using `@RegisterExtension` counts as an actual deployment or there will be any further surprises when doing a normal quarkus build or quarkus:dev)
