### ISSUE TITLE
Review all the configuration properties

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3232]
We need a full review of all the configuration properties before 1.0 to improve consistency across the core extensions.

When doing so, we should try to document the conventions for future extension writers.

A few examples of issues:
- having `feature.enable = true`/`enable-feature = true`/`feature-enabled = true`/`feature = true`
- CORS configuration inconsistent in HTTP config and Keycloak extension (we should try to get the config keys consistent)
- when the underlying framework provide a default, should we define the default in Quarkus or not? The good thing is that it would be automatically documented and stable, the bad thing is that the underlying framework might tweak the default and we wouldn't benefit from these changes.

**Comment by rquinio** [comment]
A minor discrepancy I noticed is that `@ConfigItem` is not mandatory on fields whose type is annotated with `@ConfigGroup`: https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/HttpConfig.java#L54-L62
Technically it's only needed if you need to override the name of the group: https://github.com/quarkusio/quarkus/blob/688ee16b0641ac60239c0c7970ce23b6cbff35ff/extensions/hibernate-search-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/elasticsearch/runtime/HibernateSearchElasticsearchRuntimeConfig.java#L29-L30
But I see some extension using it explicitly in any case: https://github.com/quarkusio/quarkus/blob/18219efcc6870eef467c49c5c024362ddc4d454a/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/EventBusConfiguration.java#L16-L17

**Comment by emmanuelbernard** [comment]
We did our best :D
