### ISSUE TITLE
Pressing ‘d’ for open dev mode should provide info on how to enable devui if devui not available

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#32334]
### Description

Like seen in https://github.com/quarkusio/code.quarkus.io/issues/1173 And related if you dont have vertx-http in dependencies you dont have working devmode. 

Instead of forcing technically unnecessary dependencies we could at least have ‘d’ give detail like:

“Devui is not available. You can enable it by including vertx-http dependency. See more at <url to guide describing how to do it best (i.e. not add it to normal dependency chain in maven use devmode dependency in gradle>”

**Comment by geoand** [comment]
#32396 provides the essential capability needed. I'll leave it up to others to enhance with links to the proper guide (if necessary).
