### ISSUE TITLE
Unknown enum constant org.osgi.annotation.bundle.Requirement.Resolution.OPTIONAL

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#32332]
### Describe the bug

Quarkus 3.0.0.CR1 is showing the following warning during compilation:

```
[WARNING] unknown enum constant org.osgi.annotation.bundle.Requirement.Resolution.OPTIONAL
  reason: class file for org.osgi.annotation.bundle.Requirement$Resolution not found
```

### How to Reproduce?

1. Use code.quarkus.io to create new project with Quarkus 3.0.0.CR1 using default settings
2. Add the following service

```java
package org.acme;

import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class SampleService {

    private final String issuer;

    public SampleService(@ConfigProperty(name = "mp.jwt.verify.issuer") String issuer) {
        this.issuer = issuer;
    }
}
```

It's important to use microprofile ConfigProperty annotation

3. mvn clean package

### Quarkus version or git rev

3.0.0.CR1

**Comment by kucharzyk** [comment]
Looks like it's the problem with microprofile-config

https://github.com/eclipse/microprofile-config/pull/732#issuecomment-1482128111

**Comment by DCCSKrezovic** [comment]
Just found https://github.com/quarkusio/quarkus/issues/19970. Subscribing here ...

**Comment by wjglerum** [comment]
I commented here last weekend on the same issue https://github.com/quarkusio/quarkus/issues/30037

**Comment by radcortez** [comment]
Unfortunately, the fix didn't make it into the released version of the Jakarta artifact. We need a new release of MP Config API.
