### ISSUE TITLE
Defining message in msg.properties file doesn't work with default locale

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#32354]
### Describe the bug

I  have defined an AppMessages like this:

```java
@MessageBundle
public interface AppMessages {

    @Message("Hello {name ?: 'Qute'}")
    String hello_name(String name);
}
```

In my template I use it like this:

`{msg:hello_name('Lucie')}`

it works perfectly.

Now I want to manage message in msg.properties. So I define a `src/main/resources/messages/msg.properties`like this:

`hello_name=Hello {name ?: 'Qute'}`

and I remove the message value from the class:

```java
@MessageBundle
public interface AppMessages {

    @Message
    String hello_name(String name);
}
```

It throws the following error:

`io.quarkus.qute.deployment.MessageBundleException: Message template for key [hello_name] is missing for default locale`

Please note if I define `src/main/resources/messages/msg_fr.properties` and I configure `quarkus.default-locale=fr` in `application.properties` it works perfecly.

`

**Comment by mkouba** [comment]
It seems that we don't support a localized file without a locale tag. In fact, it's even documented: _"The file name consists of the relevant bundle name (e.g. msg) and underscore followed by the locate tag (IETF)."_  Note that historically, it was not possible to use a localized file for the default bundle.

But I think that it  would make sense to add the default locale suffix automatically. 

@michalvavrik WDYT?

**Comment by michalvavrik** [comment]
I actually already thought about this when reviewing one of your PRs. I think it makes sense. I'll find a time to do it later this month (it's not time sensitive right?).

**Comment by michalvavrik** [comment]
Ah, just realized @angelozerr might want to fix it himself :-) sorry, will you work on it?

**Comment by angelozerr** [comment]
@michalvavrik I'm sorry I will not have time to do that, I just noticed this problem while implementing Qute support for messages https://github.com/redhat-developer/quarkus-ls/pull/845#issuecomment-1492120629
