### ISSUE TITLE
Scheduled job appearing in different module

### ISSUE THREAD

**Issue by BobanNikolov** [quarkusio/quarkus#32367]
### Describe the bug

I have one module where I have a scheduled cron job with the quarkus Scheduler.

I have another module with dependency to the previous one with the Scheduler explicitly excluded from Jandex.

I have another module where I don't have any dependency to the first module, I have dependency to the second module,  but I still get the job running at the set time.

### Expected behavior

The scheduled cron job should not run.

### Actual behavior

The scheduled cron job runs.

### How to Reproduce?

Steps to reproduce:
1. Create a module with a @Scheduled cron job and add a jandex index(with the class where the cron job is explicitly excluded)
2. Create a module with dependency to the first one and add a jandex index (with the class where the cron job is explicitly excluded)
3. Create another module without any dependency to the second one and a jandex index (with the class where the cron job is explicitly excluded)

### Output of `uname -a` or `ver`

dev

### Output of `java -version`

17

### Quarkus version or git rev

2.8.0-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by mkouba** [comment]
Hi @BobanNikolov, we'll need more information to reproduce the issue. Are those modules part of a multi-module project? How do you run Quarkus? A simple reproducer app/project would be very useful.

**Comment by BobanNikolov** [comment]
The modules are part of a multi-module project. Project is run with java quarkus:dev

**Comment by mkouba** [comment]
> As far as I can understand and what am also facing is that ModuleA doesn't need(want) to know in which context it is used, but define itself that some of its own beans cannot be used in another module.

That does not make any sense to me. Anyway, you can use the [`quarkus.arc.exclude-types` config property](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.exclude-types) if you need to exclude some types from bean discovery. Alternatively, you can also [exclude the whole dependency](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.exclude-dependency-artifacts-that-should-be-excluded-from-discovery) via `quarkus.arc.exclude-dependency."dependency-name".group-id` and `quarkus.arc.exclude-dependency."dependency-name".artifact-id`.

**Comment by mkouba** [comment]
I'm going to close this issue. (A) we don't have a proper reproducer and (B) there is a workaround to accomplish the task (at least from what I understand).
