### ISSUE TITLE
DevUI: Configuration Changes Not Sticking

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32443]
### Describe the bug

Configuration changes on the Dev UI not sticking.

### Expected behavior

Change configuration should Live Reload and the value should stick and be respected.

### Actual behavior

Configuration changes seem to not be taking effect.

### How to Reproduce?

1. Go to Dev UI Configuration http://localhost:8080/q/dev-ui/configuration
2. Filter for "health"
3. Uncheck `quarkus.datasource.health.enabled`
4. Now navigate to Extensions and check the Health card and see the Datasource is no longer reporting in Health (good).
5. Navigate back to Configuration page and see that the UI has the `quarkus.datasource.health.enabled` checked again.

### Quarkus version or git rev

3.0.0.CR2

**Comment by phillip-kruger** [comment]
@phillip-kruger
