### ISSUE TITLE
 after bumping to 3.0.0.CR2  > Could not find io.quarkus:quarkus-logging-sentry:.

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#32445]
### Could not find io.quarkus:quarkus-logging-sentry:.

after bumping to 3.0.0.CR2 the not found error occures. the package does not seem to be deprecated or anything and its new to me, so it might correlate with CR2.

thanks

```

> Task :scheduler:quarkusGenerateCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scheduler:quarkusGenerateCode'.
> Could not resolve all files for configuration ':scheduler:quarkusProdBaseRuntimeClasspathConfiguration'.
   > Could not find io.quarkus:quarkus-logging-sentry:.
     Required by:
         project :scheduler

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

**Comment by punkratz312** [comment]
same with 3.0.0.CR1


<img width="971" alt="image" src="https://user-images.githubusercontent.com/8830888/230179976-8568cee1-0db7-4a36-ae33-a2b8f4b87756.png">


the 2.* is compiling fine musst be an 3.0 issue

<img width="993" alt="image" src="https://user-images.githubusercontent.com/8830888/230180441-5b57d1d5-1e55-4564-a754-47dc5c176139.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/8830888/230180503-0ee3d578-c458-43ec-a008-3b1df23eddf7.png">


@gsmet

**Comment by gsmet** [comment]
This artifact has been relocated since 2.6. 

See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6#extensions-moved-to-the-quarkiverse-hub

When using Maven, you get a warning during the build. 

We dropped the relocations recently as part of the work on Quarkus 3.

**Comment by punkratz312** [comment]
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/8830888/230713316-70ef30f5-3488-4e64-8de0-dbaff80d2882.png">

the mandatory version tag is because of the different root module. 

@gsmet it there a possibility to include this artefact as transient to quarkus, so no version handling must be done anymore? 
or is this intended, as not everybody demands sentry and therefor an explicit declaration is crucial?

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/8830888/230713387-007f1e2c-f122-4713-9c50-f4d88f473421.png">
