### ISSUE TITLE
Add possibility to enable/disable features for Keycloak devservices

### ISSUE THREAD

**Issue by martaisty** [quarkusio/quarkus#32444]
### Description

Add a way to enable/disable features for Keycloak devservices. There several ways how [Keycloak](https://www.keycloak.org/server/features) suggests doing this. It's especially useful when you need something like `token-exchange` feature.

Earlier `quarkus.keycloak.devservices.java-opts=-Dkeycloak.profile.feature.token_exchange=enabled` worked just fine. However, after Quarkus `2.16.6` bumped Keycloak to `21.0.1` this doesn't work anymore. Maybe, it's Keycloak's bug but I haven't found `keycloak.profile.feature.token_exchange=enabled` option in their documentation, so can't rely on that.

### Implementation ideas

Add optional `features` and `features-disabled` to [DevServicesConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/DevServicesConfig.java) and append Keycloak's [start command](https://github.com/quarkusio/quarkus/blob/4c7ca3b704394d2d31722758df55d4832e682986/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L488) with `--features=...` and `--features-disabled=..` if the options are present.

**Comment by antonvovk** [comment]
Hi! @martaisty 
Thanks for starting a discussion on this one. I have faced precisely the same issue.
@sberyozkin please take a look at it. Thanks!

**Comment by martaisty** [comment]
`--features-disabled` is not really needed, at least for my usage of Keycloak. I just thought it would be nice to have. You're right @sberyozkin `features` property will probably be sufficient. I've opened an [issue](https://github.com/keycloak/keycloak/issues/19577) in the Keycloak repository to clarify this behavior.

Having analyzed a bit Keycloak's changes between versions, I've found a workaround to use `quarkus.keycloak.devservices.java-opts=-Dkc.features=token-exchange,admin-fine-grained-authz,map-storage` to suffice my needs. I am not really sure if it's a good idea to configure it in this way.

**Comment by sberyozkin** [comment]
Thanks @martaisty, so if you can continue using JAVA_OPTS, are we going to save anything with `--features` ?
I.e as far as DevServices config is concerned, it would about users doing either
```
java_opts=-Dkc.features=token-exchange,admin-fine-grained-authz,map-storage
``` 
vs
```
features=token-exchange,admin-fine-grained-authz,map-storage
```
The latter option looks nicer for sure, but does it warrant adding a new config property which only optimizes what is already possible with `java_opts` albeit in a bit more verbose way ?

I may be missing something though...

**Comment by martaisty** [comment]
> The latter option looks nicer for sure, but does it warrant adding a new config property which only optimizes what is already possible with `java_opts` albeit in a bit more verbose way ?

@sberyozkin actually, it depends on Keycloak team's answer to the opened issue...

If they claim that usage of `java_opts=-Dkc.features=token-exchange,admin-fine-grained-authz,map-storage` is fine, then we can close the issue and keep using it. Otherwise, I believe adding `--features=...` worth efforts to have an ability to customize Keycloak devservices.

By the way, adding `--features=...` to the start command is not the only option. There are [other ways](https://www.keycloak.org/server/configuration) for Keycloak configuration:

> Keycloak loads the configuration from four different configuration sources:
>    - command-line parameters
>    - environment variables
>    - user-created .conf file
>    - keycloak.conf file located in the conf directory.

Maybe, adding support of environment variables to Keycloak devservices will be easier and better, because it can cover more usecases. Then such config can look like this `quarkus.keycloak.devservices.envs.KC_FEATURES=token-exchange`

**Comment by martaisty** [comment]
Hi @sberyozkin :wave: Back to the issue... I received an answer from Keycloak team. Please check it out: https://github.com/keycloak/keycloak/issues/19577#issuecomment-1516482327

Therefore, I believe support of features config for Keycloak devservices should be added

**Comment by Eng-Fouad** [comment]
> > The latter option looks nicer for sure, but does it warrant adding a new config property which only optimizes what is already possible with `java_opts` albeit in a bit more verbose way ?
> 
> @sberyozkin actually, it depends on Keycloak team's answer to the opened issue...
> 
> If they claim that usage of `java_opts=-Dkc.features=token-exchange,admin-fine-grained-authz,map-storage` is fine, then we can close the issue and keep using it. Otherwise, I believe adding `--features=...` worth efforts to have an ability to customize Keycloak devservices.
> 
> By the way, adding `--features=...` to the start command is not the only option. There are [other ways](https://www.keycloak.org/server/configuration) for Keycloak configuration:
> 
> > Keycloak loads the configuration from four different configuration sources:
> > 
> > * command-line parameters
> > * environment variables
> > * user-created .conf file
> > * keycloak.conf file located in the conf directory.
> 
> Maybe, adding support of environment variables to Keycloak devservices will be easier and better, because it can cover more usecases. Then such config can look like this `quarkus.keycloak.devservices.envs.KC_FEATURES=token-exchange`

It's possible now (since Quarkus 3.2.0.Final) to pass environment variables to devservices containers. See #34223

**Comment by martaisty** [comment]
Environment variables made devservices much more flexible 🎉  Closing the issue
