### ISSUE TITLE
Unable to register CustomExceptionMapper in extension using Resteasy-Classic

### ISSUE THREAD

**Issue by enrico-niccoli** [quarkusio/quarkus#32459]
### Describe the bug

Hi,

I'm trying to create a QuarkusExtension which contains a simple MyCustomException and a MyCustomExceptionMapper for this specific exception.
I'm having some troubles finding the right BuildItem for MyCustomExceptionMapper since CustomExceptionMapperBuildItem works only for Reasteasy-Reactive and others BuildItems I've tried have not worked, resulting in crashes or unwanted behavior. 
For clarity, this is what I'm trying to do in deployment module.

```
    //What kind of BuildItem should I use?
    @BuildStep
    CustomExceptionMapperBuildItem createMapper(){
        return new CustomExceptionMapperBuildItem("MyCustomExceptionHandler");
    }
```
Is there a way to do it?
Thanks in advance,

Enrico.

### Expected behavior

MyCustomExceptionHandler, once imported into an application, works correctly

### Actual behavior

MyCustomExceptionHandler, once imported into an application, is ignored and doesn't catch MyCustomException

### Output of `uname -a` or `ver`

Linux asset-00287 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5"

### Quarkus version or git rev

2.13.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
For RESTEasy Classic, you should use `io.quarkus.resteasy.common.spi.ResteasyJaxrsProviderBuildItem` from the `io.quarkus:quarkus-resteasy-common-spi` dependency

**Comment by enrico-niccoli** [comment]
Hi @geoand, thanks for the reply! I tried `ResteasyJaxrsProviderBuildItem` but now, when I add my extension in a simple project as a dependency, I keep getting `java.lang.RuntimeException: Unable to find class for provider MyCustomExceptionMapper` during startup.
Is there something more I have to add to the extension? Or to the project in which I want to import it?

**Comment by geoand** [comment]
Does `MyCustomExceptionMapper` actually exist as part of the runtime classpath?

**Comment by enrico-niccoli** [comment]
I'm not sure how to check it: if I try to run a test containing 
`Class.forName("path.to.MyCustomExceptionMapper", false, getClass().getClassLoader());`
I get the same error as before during initialization and I'm not able to execute the test method

**Comment by geoand** [comment]
That means the class is not part of the runtime classpath. 

Where is `path.to.MyCustomExceptionMapper` supposed to come from?

**Comment by geoand** [comment]
Unless you set it up in the build tool (Maven or Gradle), things will not work

**Comment by enrico-niccoli** [comment]
Ok sorry but I'm a bit confused: I thought it was sufficient to import my extension as a dependency in pom...
