### ISSUE TITLE
kotlin lateinit var injection does not work with qualifiers

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [quarkusio/quarkus#32460]
### Describe the bug

In integration tests, we have a class that looks similar to this:
```kotlin
@QuarkusTest
class SomeTest {

    @Inject
    lateinit var adminClient: KubernetesClient

    //   ...
}
```

To inject specific kubernetes client, we use an annotation that extends `@Qualifier`:
```kotlin
@Qualifier
@Retention(RUNTIME)
@Target(FUNCTION, VALUE_PARAMETER, FIELD, PROPERTY)
annotation class AdminClient
```

When we try to inject a bean with `@AdminClient` qualifier, using the code from below:
```kotlin
@QuarkusTest
class SomeTest {

    @Inject
    @AdminClient
    lateinit var adminClient: KubernetesClient

    //   ...
}
```

The default bean is injected, however, when we change `@AdminClient` to `@field:AdminClient`, then the proper bean is injected:

```kotlin
@QuarkusTest
class SomeTest {

    @Inject
    @field:AdminClient
    lateinit var adminClient: KubernetesClient

    //   ...
}
```

### Expected behavior

In this case:
```kotlin
@QuarkusTest
class SomeTest {

    @Inject
    @AdminClient
    lateinit var adminClient: KubernetesClient

    //   ...
}
```
the bean with `@AdminClient` qualifier should be injected

### Actual behavior

At the moment a default bean is injected instead of the one with `@AdminClient` qualifier.

### Quarkus version or git rev

2.16.4.Final

**Comment by mschorsch** [comment]
There is a dedicated entry in the quarkus kotlin guides.

https://quarkus.io/guides/kotlin#cdi-inject-with-kotlin

**Comment by mkouba** [comment]
In CDI a qualifer must be declared on a field for field injection and method parameter for initializer methods/setters. So it really depends on what the `@Inject @AdminClient lateinit var adminClient: KubernetesClient` is translated to...

**Comment by Ladicek** [comment]
It should also work correctly if you remove `PROPERTY` from `@Target`. In that case, the annotation should be applied to the field instead.

**Comment by AleksanderBrzozowski** [comment]
> It should also work correctly if you remove `PROPERTY` from `@Target`. In that case, the annotation should be applied to the field instead.

Nice, it works! 🙂 
Do you think this should be somehow documented?

**Comment by Ladicek** [comment]
Yes, this is documented here: https://kotlinlang.org/docs/annotations.html#annotation-use-site-targets

**Comment by AleksanderBrzozowski** [comment]
Thanks for help, I am closing the issue 🙂
