### ISSUE TITLE
Spring Data API Extension not updating generic mapping

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#32464]
### Describe the bug

I have a generic baseclass (annotated with `@MappedSuperclass`) with a one to one (unidirectional) mapping. Then i save the entity which extends the base class. The property child (which is the mapped entity) is null. Now when i create a child i also update the parent so that the parent is connected to child. But only the child is stored to the database but the parent column won't get updated with the id of the child. 
If the mapping is not done with a generic it works as expected. In Spring Boot it also works with a generic.

### Expected behavior

The parent should be correctly updated.

### How to Reproduce?

1. Go to the swagger: [http://localhost:42000/test/q/swagger/]
2. Call POST /test/rest/parents with the following data
```
{
  "child": null,
  "id": null,
  "name": "string"
}
```
3. Call POST /test/rest/parents/{parentId}/children with the following data
`parentId = 1`
```
{
  "id": null,
  "childName": "string"
}
```
4. Call GET /test/rest/parents/{parentId} with the following data
`parentId = 1`
Now the response should be:
```
{
  "child": null,
  "id": 1,
  "name": "string"
}
```
If it worked correctly the child shouldn't be null
The reproducer is with version 3.0.0.CR2 it also does not work with 2.16.5
[reproducerGenericMapping.zip](https://github.com/quarkusio/quarkus/files/11169477/reproducerGenericMapping.zip)

### Output of `java -version`

17

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by geoand** [comment]
I can't say I really understand how this is meant to work. If you attach a similar Spring Boot example I can try and compare the two and see what's going on.

**Comment by Michael-AT-Corporation** [comment]
1. POST localhost:8085/create
```
{
    "id": null,
    "name": "Parent",
    "child": null
}
```
2. POST localhost:8085/1/createChild
```
{
    "id": null,
    "childName": "new child"
}
```
3. GET localhost:8085/1 this returns as expected:
```
{
    "child": {
        "id": 1,
        "childName": "new child"
    },
    "id": 1,
    "name": "Parent"
}
```
I created the tables with the generated create.sql script.
[SpringBootGenericMapping.zip](https://github.com/quarkusio/quarkus/files/11177826/SpringBootGenericMapping.zip)

**Comment by geoand** [comment]
@Sanne @yrodiere there is clearly something I don't understand in Hibernate and I would like your help. Let me explain with some code:

Here is a base class:

```java
@MappedSuperclass
public class ParentBase<T> {

    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
    private T child;

    public T getChild() {
        return child;
    }

    public void setChild(T child) {
        this.child = child;
    }
}
```

Here is an example `Child` class:

```java
@Entity
public class Child {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String childName;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChildName() {
        return childName;
    }

    public void setChildName(String childName) {
        this.childName = childName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        Child child = (Child) o;
        return id != null && Objects.equals(id, child.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
```

and example `Parent` class that extends `ParentBase` and uses `Child` as the generic type:

```java
@Entity
public class Parent extends ParentBase<Child> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        Parent that = (Parent) o;
        return id != null && Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
```

Now when I run something like:

```java

AtomicLong parentId = new AtomicLong(-1);

            // create the parent
            QuarkusTransaction.requiringNew().run(() -> {
                Parent parent = new Parent();
                parent.setName("parent");
                entityManager.persist(parent);
                parentId.set(parent.getId());
            });

            // create the child and update the parent
            QuarkusTransaction.requiringNew().run(() -> {
                Child child = new Child();
                child.setChildName("child");
                entityManager.persist(child);
                Parent parent = entityManager.find(Parent.class, parentId.get());
                parent.setChild(child);
                entityManager.merge(parent);
            });

            QuarkusTransaction.requiringNew().run(() -> {
                Parent parent = entityManager.find(Parent.class, parentId.get());
                Child child = parent.getChild();
                Objects.requireNonNull(child, "The child of the updated parent should not be null");
            });
```

I fully expected it to work properly as what I think I am doing is creating a `Parent`, then a `Child` then updating the `Parent` to set the `Child` and saving it.
Finally I f tech the `Parent` expecting to get the `Child` I saved earlier, but the `Child` is `null`....

Clearly I am missing something fundamental here...

I am attaching a [sample](https://github.com/quarkusio/quarkus/files/11179037/code-with-quarkus.zip) you can use to see the problem in action.

**Comment by yrodiere** [comment]
@geoand This looks like a bug, for some reason your call to `setChild` is not being detected by Hibernate ORM, which (wrongly) assumes the `Parent` entity does not need to be updated in your second transaction.

I'll try to see where that comes from...

**Comment by yrodiere** [comment]
Confirmed as an upstream bug: https://hibernate.atlassian.net/browse/HHH-16459

**Comment by geoand** [comment]
Thanks! 

That also explains why it works in Spring and not Quarkus :)

**Comment by Sanne** [comment]
> That also explains why it works in Spring and not Quarkus :)

And why is that, don't they use Hibernate ORM as well?

**Comment by geoand** [comment]
The issue mentions the problem happens when bytecode enhancing is used

**Comment by Sanne** [comment]
> The issue mentions the problem happens when bytecode enhancing is used

@geoand ok well we enforce it, but it's an option for other platforms as well. I guess it's more of a problem for us when people can't disable it :)

**Comment by geoand** [comment]
I am not complaining, we definitely should enforce it.

I am just mentioning why it works in Spring and currently not in Quarkus

**Comment by Sanne** [comment]
didn't mean to imply you were complaining :)
Just thinking out loud about the differences, and yes our choices come with some risks.

**Comment by geoand** [comment]
👌
