### ISSUE TITLE
Quarkus 3.0.0.CR2  Failed to start application (with profile [dev]): java.lang.IllegalStateException: No current Vertx context found

### ISSUE THREAD

**Issue by flynndi** [quarkusio/quarkus#32466]
### Describe the bug

Listening for startup and shutdown events

I want to insert a piece of data into the startup event, and if it is not found, I will insert it

```java

         void onStart(@Observes StartupEvent ev) {

        LOGGER.info("Default Charset = " + Charset.defaultCharset());
        LOGGER.info("file.encoding = " + System.getProperty("file.encoding"));
        LOGGER.info("Default Charset in use = " + this.getDefaultCharset());
        LOGGER.info("The application is starting...");
        LOGGER.info("The application model is " + LaunchMode.current());
        this.initRegisterClient();
        }
```

```java


           public void initRegisterClient() {
            RegisteredClient registeredClient = new RegisteredClient();
            //Filling parameter
            Long count = iRegisteredClientRepository.findByClientIdCount(registeredClient.getClientId())
                    .log().await().indefinitely();
            if (0L == count) {
                iRegisteredClientRepository.save(registeredClient).log() .await().indefinitely();
                LOGGER.info("The registerClient insert data complete...");
            }
        }



```

It works in quarkus2      It doesn't work in quarkus3

I went through the code and tried to write it this way

```java
   

       public Uni<Void> initRegisterClient() {

      Context context = VertxContext.getOrCreateDuplicatedContext(vertx);
        VertxContextSafetyToggle.setContextSafe(context, Boolean.TRUE);
        sessionFactory.openSession().chain(session -> {
                    RegisteredClient registeredClient = new RegisteredClient();
                   
                      //Filling parameter

                    Long count = iRegisteredClientRepository.findByClientIdCount(registeredClient.getClientId())
                            .log().await().indefinitely();
                    if (0L == count) {
                        iRegisteredClientRepository.save(registeredClient)
                                .log()
                                .await()
                                .indefinitely();
                        LOGGER.info("The registerClient insert data complete...");
                    }
                    return Uni.createFrom().voidItem();
                })
                .eventually(() -> sessionFactory.close()).await().indefinitely();
                return Uni.createFrom().voidItem();
            }


```
Failed to start application (with profile [dev]): java.lang.IllegalStateException: No current Mutiny.Session found
	- no reactive session was found in the context and the context was not marked to open a new session lazily
	- you might need to annotate the business method with @WithSession

`@WithSession` It doesn't work either

### Expected behavior

Successful execution statement

### Actual behavior

failure

### Output of `java -version`

17

### Quarkus version or git rev

Quarkus 3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

**Comment by flynndi** [comment]
A piece of code is missing

`
         
         public Uni<Void> initRegisterClient() {

        Context context = VertxContext.getOrCreateDuplicatedContext(vertx);

        VertxContextSafetyToggle.setContextSafe(context, Boolean.TRUE);

        context.runOnContext(event -> {
            sessionFactory.openSession().chain(session -> {
                        RegisteredClient registeredClient = new RegisteredClient();
                        registeredClient.setTokenSettings(TokenSettings.builder().accessTokenTimeToLive(Duration.ofHours(24)).build());
                        registeredClient.setClientSettings(ClientSettings.builder().build());
                        registeredClient.setClientId(new ClientId("messaging-client"));
                        registeredClient.setClientSecret(new ClientSecret("{noop}secret"));
                        registeredClient.setClientAuthenticationMethods(new ClientAuthenticationMethods(Collections.singleton("client_secret_basic")));
                        registeredClient.setAuthorizationGrantTypes(new AuthorizationGrantTypes(Collections.singleton("refresh_token,password,authorization_code")));
                        registeredClient.setRedirectUris(new RedirectUris(Collections.singleton("https://www.baidu.com")));
                        registeredClient.setScopes(new Scopes(Collections.singleton("openid,message.read")));
                        registeredClient.setClientName(new ClientName("messaging-client"));
                        registeredClient.setClientIdIssuedAt(new ClientIdIssuedAt(LocalDateTime.now()));
                        Long count = iRegisteredClientRepository.findByClientIdCount(registeredClient.getClientId())
                                .log().await().indefinitely();
                        if (0L == count) {
                            iRegisteredClientRepository.save(registeredClient)
                                    .log()
                                    .await()
                                    .indefinitely();
                            LOGGER.info("The registerClient insert data complete...");
                        }
                        return Uni.createFrom().voidItem();
                    })
                    .eventually(() -> sessionFactory.close()).await().indefinitely();
        });
       return Uni.createFrom().voidItem();}

`

**Comment by gsmet** [comment]
Could you provide a small Maven project reproducing the issue? That will help us a lot. Thanks.

**Comment by flynndi** [comment]
https://github.com/flynndi/report-code/tree/master

sorry, I didn't install maven 
This is built with gradle

> Could you provide a small Maven project reproducing the issue? That will help us a lot. Thanks.

**Comment by geoand** [comment]
To be honest, the current behavior seems more correct, but I'll let @DavideD and @Sanne comment further

**Comment by flynndi** [comment]
> To be honest, the current behavior seems more correct, but I'll let @DavideD and @Sanne comment further



This is my current solution, I have a question, why is the current VertxContext not safe

`

    Context context = VertxContext.getOrCreateDuplicatedContext(vertx);
    VertxContextSafetyToggle.setContextSafe(context, Boolean.TRUE);
    context.runOnContext(v -> this.initCheckRegisterClient()
                    .subscribe()
                    .with(count -> {
                        if (0L == count) {
                            this.insertRegisterClient().subscribe().with(x -> {
                                LOGGER.info("The RegisterClient insert data complete...");
                            });
                        }
                    }));

`

**Comment by mkouba** [comment]
Hi @flynndi, so first of all the problem you're facing is related to a [breaking change introduced in Hibernate Reactive Panache](
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#sessions-and-transactions). The current reactive `Mutiny.Session` is no longer stored in the CDI request context and a Panache entity/repository method execution is not offloaded on the current Vert.x context anymore. As a consequence you can't perform any Panache entity/repo method from a blocking thread, neither use `Uni.await().indefinitely()`.

You can try to leverage the `VertxContextSupport` util class to [execute asynchronous code from a blocking thread](https://quarkus.io/version/main/guides/vertx#executing-asynchronous-code-from-a-blocking-thread). It does execute the code on the "correct" Vert.x context.

Something like this should work in your app:

```java
public void init() throws Throwable {
        VertxContextSupport.subscribeAndAwait(() -> // offload to the correct Vert.x context
            Panache.withTransaction(() -> { // use a tx to persist the Book entity
                Book book = new Book();
                book.setContent("3");
                book.setId("3");
                book.setName("3");
                return bookDao.persist(book);
        }));
    }
```

**Comment by geoand** [comment]
Closing as per @mkouba's comment

**Comment by franz-see** [comment]
@mkouba using `VertxContextSupport.subscribeAndAwait`,  I get 

```
2023-06-23 02:51:32,946 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[#237,vert.x-eventloop-thread-1,5,main] has been blocked for 2481 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
```

This happens for anything longer than 2 seconds and I dont know how to add just time limit.

**Comment by mkouba** [comment]
> @mkouba using `VertxContextSupport.subscribeAndAwait`, I get
> 
> ```
> 2023-06-23 02:51:32,946 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[#237,vert.x-eventloop-thread-1,5,main] has been blocked for 2481 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
> 	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
> ```
> 
> This happens for anything longer than 2 seconds and I dont know how to add just time limit.

@franz-see the `VertxContextSupport` should be used to execute some _async code_ from a blocking thread, i.e. the execution is offloaded to an event loop. But the async code must not block. That's the golden rule of async programming. How does your code look like? Is it using async API? If not then you can just inject the default blocking `java.util.concurrent.ExecutorService` and submit a blocking task.

If you need to execute some long-running blocking operation and incorporate it in a reactive chain (a chain of async API calls) there are other solutions as well. For example, you can `@Inject Vertx` and use [`Vertx.executeBlocking()`](https://vertx.io/docs/vertx-core/java/#blocking_code). You can also use the [Vert.x event bus](https://quarkus.io/guides/vertx-reference#blocking-processing).
