### ISSUE TITLE
Quarkus 3.0.0.CR2 - quarkus-kafka-client triggers NativeImageBuildStep in JVM mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#32461]
### Describe the bug

Quarkus 3.0.0.CR2 - `quarkus-kafka-client` extension triggers NativeImageBuildStep in JVM mode

Regression comparing to 3.0.0.CR1, visible through this warning on LINUX machines

```
 [WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Cannot find the `native-image` in the 
  GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image` 
  Attempting to fall back to container build.
```

Other extensions do not trigger this warnings. 

### Expected behavior

No warning from NativeImageBuildStep

### Actual behavior
```
 [WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Cannot find the `native-image` in the 
  GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image` 
  Attempting to fall back to container build.
```

### How to Reproduce?

generate sample app using `mvn io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR2:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-quarkus-kafka-client -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.0.0.CR2 -Dextensions=quarkus-kafka-client`

run `mvn clean package -DskipTests -f app-quarkus-kafka-client`

Check the log for the warning

CR1 has no warning on Linux machines using `mvn clean package -DskipTests -f app-quarkus-kafka-client -Dquarkus.platform.version=3.0.0.CR1` command

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 11

### Quarkus version or git rev

3.0.0.CR2

**Comment by cescoffier** [comment]
I don't see why this would be related to kafka. It seems to be a bigger underlying issue.

**Comment by rsvoboda** [comment]
This one is quite strange, as I said above, the warning is not triggered by other extensions

I tried these: quarkus-jaxrs-client-reactive,quarkus-resteasy-reactive,quarkus-resteasy-reactive-jackson,quarkus-resteasy-reactive-qute,quarkus-rest-client-reactive,quarkus-rest-client-reactive-jackson,core,hibernate-orm,hibernate-orm-panache,hibernate-validator,jackson,jaxb,jdbc-mysql,jdbc-postgresql,jsonb,jsonp,kubernetes-config,mailer,narayana-jta,oidc,quarkus-quartz,reactive-pg-client,scheduler,spring-boot-properties,smallrye-reactive-streams-operators,spring-data-jpa,spring-di,spring-security,spring-web,undertow,vertx,quarkus-reactive-routes,grpc,infinispan-client,cache,micrometer,micrometer-registry-prometheus,quarkus-openshift-client,quarkus-smallrye-graphql 

I noticed this when updating https://github.com/quarkus-qe/quarkus-startstop to CR2

**Comment by mmusenbr** [comment]
We have a build here of a small quarkus application, and when trying to use CR2 instead of CR1 I also get the same warning. But as it is build inside an image, which does not have docker/podman inside it leads to a build error:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR2:build (default) on project qcer-distribution-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#resolveNativeImageBuildRunner threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
```
Currently trying to determine why he is taking the new route via the NativeImageBuildStep.

**Comment by mmusenbr** [comment]
Could this be a starting point: https://github.com/quarkusio/quarkus/pull/32236 ?

**Comment by gsmet** [comment]
@geoand could you have a look at this one? It looks like a problematic regression.

**Comment by geoand** [comment]
Sure, I'll have a look

**Comment by geoand** [comment]
It does look like https://github.com/quarkusio/quarkus/pull/32236  is responsible and it also looks like the issue is Kafka specific (because the Kafka Client consumes `NativeImageRunnerBuildItem`).

cc @yrodiere

**Comment by geoand** [comment]
Let me try something real quick and see if the problem goes away

**Comment by geoand** [comment]
What I had in mind seems to work, opening a PR soon

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/32476 is the solution
