### ISSUE TITLE
Quarkus 3 kotlin generation missconfigures allopen

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#32474]
**Describe the bug**
Generating an new app with quarkus-kotlin for Quarkus 3 generates an allopen configuration for `javax.` instead of for `jakarta.`

**Expected behavior**
The list of allopen with annotation should be the jakarta imports

**Actual behavior**
The list of allopen with annotation should be the javax imports

**To Reproduce**
1. https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=kotlin&S=io.quarkus.platform%3A3.0&extension-search=kotlin
2. Have a look into the zip
3. Happens in maven and gradle

**Comment by gsmet** [comment]
I just tested your link and I get:

```
allOpen {
    annotation("jakarta.ws.rs.Path")
    annotation("jakarta.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}
```

**Comment by geoand** [comment]
Same for me

**Comment by bulldog98** [comment]
@gsmet as I commented since a recent commit it happens only in the 2.x lines so link would be https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL&e=kotlin&S=io.quarkus.platform%3A2.16&extension-search=kotlin

**Comment by gsmet** [comment]
Ah OK, I see your point.

@ia3andy it seems that code.quarkus.io is using the templates from 3 to generate Quarkus 2.x projects, now that you migrated it to Quarkus 3. Which won't work as we have some `jakarta.` packages hardcoded in the build files.

**Comment by ia3andy** [comment]
> Ah OK, I see your point.
> 
> @ia3andy it seems that code.quarkus.io is using the templates from 3 to generate Quarkus 2.x projects, now that you migrated it to Quarkus 3. Which won't work as we have some `jakarta.` packages hardcoded in the build files.

Ahhh snap, I missed that ... base codestarts are supposed to stay version agnostic :-/

**Comment by ia3andy** [comment]
We need to add a {#if depending on the quarkus version then..

**Comment by gsmet** [comment]
Could you take care of it? I'm more than full.

**Comment by ia3andy** [comment]
@quarkusio/devtools this is a bad situation as it means that until the next version for code.quarkus (and forever with this CLI version) we are generating those wrong gradle projects.

**Comment by maxandersen** [comment]
It's a CR2. Not final. This is why we do those. To find where we missed an assumption.
