### ISSUE TITLE
Enhance Azure functions extension to support `JsonWebToken`

### ISSUE THREAD

**Issue by salmipa** [quarkusio/quarkus#32479]
### Describe the bug

Adding dependency quarkus-smallrye-jwt makes the function unusable, always returning 401. 

### Expected behavior

I should be able to use JsonWebToken injected by Quarkus and containing information about the bearer token.

### How to Reproduce?

Just add dependency 

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-jwt</artifactId>
		</dependency>

and you'll see

**Comment by sberyozkin** [comment]
@salmipa I think it should be re-qualified as an `enhancement`. It sounds pretty similar to the Amazon Lamda issue we had earlier where the token entering the Quarkus function is not provided as an HTTP Bearer token but the Amazon Lamda or in this case Azure runtime. 
I recommend you to provide more information and investigate what channel is used by the Azure Functions runtime to provide the token and re-qualify it as an enhancement request if you'd like to have it eventually resolved

Thanks

**Comment by sberyozkin** [comment]
@salmipa I've renamed and re-qualified the issue as an enhancement, please provide more info about Azure mechanics related to providing the token to functions and hopefully we'll find a way to handle it similarly to Amazon Lambda

**Comment by salmipa** [comment]
I made it work already by implementing JsonWebToken without any help from smallrye. I had to ContainerRequestFilter which collects HttpHeaders, gets authorization header, parses the payload to javax.json.JsonObject and passes claims and "raw token" to my custom JsonWebToken implementation. Two classes and definitely less than 100 rows of code altogether. So, in the end I think smallrye is just harmful in this case because there's absolutely no need to verify the token anymore (it's done by Azure Function App itself). It would be though, if quarkus azure functions would support this instead of my custom solution.

```
import org.eclipse.microprofile.jwt.Claims;

@Provider
@Priority(javax.interceptor.Interceptor.Priority.LIBRARY_BEFORE + 5)
public class ContainerRequestFilterImpl implements ContainerRequestFilter {
	@Context
    HttpHeaders headers;
	@Inject
	JsonWebTokenImpl jwt;
	
	@Override
	public void filter(ContainerRequestContext context) throws IOException {
		try {
			var authorization = headers.getHeaderString("authorization");
			if (authorization != null) {
				var serializedClaims = authorization.replaceFirst("Bearer\\s+[^.]+\\.([^.]+)\\..+$", "$1");
				var jsonClaims = Base64.getUrlDecoder().decode(serializedClaims);
				var reader = Json.createReader(new StringReader(new String(jsonClaims, StandardCharsets.UTF_8)));
				var claims = Json.createObjectBuilder(reader.readObject())
					.add(Claims.raw_token.name(), authorization.replaceFirst("Bearer\\s+(.+)$", "$1"))
					.build();
				jwt.setClaims(claims);
			}
		} catch (RuntimeException e) {
			throw e;
		}
	}
}
```

**Comment by sberyozkin** [comment]
@salmipa All right, as far as I recall now, this is similar to what was done for Amazon Lambda.

>Two classes and definitely less than 100 rows of code altogether. So, in the end I think smallrye is just harmful in this case because there's absolutely no need to verify the token anymore (it's done by Azure Function App itself)

I agree, that if it has been already verified, re-verifying it makes no sense. FYI, you can configure quarkus-smallrye-jwt to use a custom factory which will do exactly what you do with the filter, and it is documented. But in any case I'd like to encourage you to avoid all these dramatizations like `wrecks the day`, `harmful`, etc, in the future, we are here to help.

If you'd like to be of help, and since you have an experience with the Azure functions, can you consider opening a PR where what you did with the custom filter can be done by the azure functions extension itself ? (See how some relevant work has been done for Amazon Lambda: #28545 )

**Comment by salmipa** [comment]
We decided to do something little bit more dramatic with Azure functions & Quarkus, including supporting non-http triggers, too. (For example, when a document is inserted to CosmosDB or timer is elapsed). Also the build process itself needs some attention (for example we want to use Microsoft's maven plugin which is detecting FunctionName and HttpTrigger annotation so that function.json is not needed at all). So, it may happen that we make a PR, but it takes some time since our scope is now much larger.

**Comment by amal-sebs** [comment]
> I made it work already by implementing JsonWebToken without any help from smallrye. I had to ContainerRequestFilter which collects HttpHeaders, gets authorization header, parses the payload to javax.json.JsonObject and passes claims and "raw token" to my custom JsonWebToken implementation. Two classes and definitely less than 100 rows of code altogether. So, in the end I think smallrye is just harmful in this case because there's absolutely no need to verify the token anymore (it's done by Azure Function App itself). It would be though, if quarkus azure functions would support this instead of my custom solution.
> 
> ```
> import org.eclipse.microprofile.jwt.Claims;
> 
> @Provider
> @Priority(javax.interceptor.Interceptor.Priority.LIBRARY_BEFORE + 5)
> public class ContainerRequestFilterImpl implements ContainerRequestFilter {
> 	@Context
>     HttpHeaders headers;
> 	@Inject
> 	JsonWebTokenImpl jwt;
> 	
> 	@Override
> 	public void filter(ContainerRequestContext context) throws IOException {
> 		try {
> 			var authorization = headers.getHeaderString("authorization");
> 			if (authorization != null) {
> 				var serializedClaims = authorization.replaceFirst("Bearer\\s+[^.]+\\.([^.]+)\\..+$", "$1");
> 				var jsonClaims = Base64.getUrlDecoder().decode(serializedClaims);
> 				var reader = Json.createReader(new StringReader(new String(jsonClaims, StandardCharsets.UTF_8)));
> 				var claims = Json.createObjectBuilder(reader.readObject())
> 					.add(Claims.raw_token.name(), authorization.replaceFirst("Bearer\\s+(.+)$", "$1"))
> 					.build();
> 				jwt.setClaims(claims);
> 			}
> 		} catch (RuntimeException e) {
> 			throw e;
> 		}
> 	}
> }
> ```

Hi @salmipa,
I tried to use your code but I am not able to find JsonWebTokenImpl class to inject. Requesting your guidance on this.

**Comment by sberyozkin** [comment]
Closing as a duplicate of the newer #39107

**Comment by jumper404** [comment]
> I made it work already by implementing JsonWebToken without any help from smallrye. I had to ContainerRequestFilter which collects HttpHeaders, gets authorization header, parses the payload to javax.json.JsonObject and passes claims and "raw token" to my custom JsonWebToken implementation. Two classes and definitely less than 100 rows of code altogether. So, in the end I think smallrye is just harmful in this case because there's absolutely no need to verify the token anymore (it's done by Azure Function App itself). It would be though, if quarkus azure functions would support this instead of my custom solution.
> 
> ```
> import org.eclipse.microprofile.jwt.Claims;
> 
> @Provider
> @Priority(javax.interceptor.Interceptor.Priority.LIBRARY_BEFORE + 5)
> public class ContainerRequestFilterImpl implements ContainerRequestFilter {
> 	@Context
>     HttpHeaders headers;
> 	@Inject
> 	JsonWebTokenImpl jwt;
> 	
> 	@Override
> 	public void filter(ContainerRequestContext context) throws IOException {
> 		try {
> 			var authorization = headers.getHeaderString("authorization");
> 			if (authorization != null) {
> 				var serializedClaims = authorization.replaceFirst("Bearer\\s+[^.]+\\.([^.]+)\\..+$", "$1");
> 				var jsonClaims = Base64.getUrlDecoder().decode(serializedClaims);
> 				var reader = Json.createReader(new StringReader(new String(jsonClaims, StandardCharsets.UTF_8)));
> 				var claims = Json.createObjectBuilder(reader.readObject())
> 					.add(Claims.raw_token.name(), authorization.replaceFirst("Bearer\\s+(.+)$", "$1"))
> 					.build();
> 				jwt.setClaims(claims);
> 			}
> 		} catch (RuntimeException e) {
> 			throw e;
> 		}
> 	}
> }
> ```

This workaround is not working

**Comment by jumper404** [comment]
@salmipa can u share the JsonWebTokenImpl class as well
