### ISSUE TITLE
[Extension Proposal] iText PDF Library

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32485]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

Using an up to date fork of the last known MPL licensed iText2: https://github.com/albfernandez/itext2

Similar to the Qverse POI plugin goals.

### Repository name

quarkus-itext

### Short description

Create and manipulate PDFs on the fly

### Repository Homepage URL

https://github.com/albfernandez/itext2

### Repository Topics

- quarkus-extension
- itext
- pdf
- reader
- writer

### Team Members

- melloware

**Comment by gastaldi** [comment]
Is this fork being actively maintained? It looks like it hasn't any activity for almost a year?

**Comment by gastaldi** [comment]
One that would be interesting to have is https://pdfbox.apache.org/. Perhaps we could extract some stuff from the Tika extension and evolve separately

**Comment by melloware** [comment]
iText2 has been around for a decade as MPL. This fork simply fixed a bunch of bugs in it but its really stable. So anyone stuck using iText2 because of licenses (like PrimeFaces) uses a lib like this.  OpenLibre PDF is another one but it has added too much bloat including Barocde and Apache FOP which makes it really difficult to maintain as a Quarkus Extension.

I am ok leaving this one open for now if I get it working I can always just add the Quarkus native stuff to my PrimeFaces extension!

**Comment by maxandersen** [comment]
Having extension for ipdf will be nice. Even if just the stale cut stable branch.

**Comment by mschorsch** [comment]
+1 for [pdfbox](https://pdfbox.apache.org/)

**Comment by melloware** [comment]
So I have used both PdfBox and iText in my career.  My current focus is on iText only because that is how two extensions generate PDFs.

- [ ] Primefaces Quarkus Extension
- [ ] JasperReports Quarkus Extension

**Comment by maxandersen** [comment]
Yes. Sorry i meant to write itext. Pdfbox would but separate one

**Comment by gastaldi** [comment]
Repository https://github.com/quarkiverse/quarkus-itext created

**Comment by melloware** [comment]
Available now as:

```xml
        <dependency>
            <groupId>io.quarkiverse.itext</groupId>
            <artifactId>quarkus-itext</artifactId>
            <version>3.0.0</version>
        </dependency>
```

**Comment by maxandersen** [comment]
Is there a reason we end up with a clone/copy of the forked library rather than using it as a dependency?

**Comment by melloware** [comment]
2 reasons...

1. as @gastaldi pointed out that developer I don't think is maintaining it much anymore
2. I was able to rip out all dead code
3. Lastly, read this thread on issues and my comment is last explaining what I had to do to get it working in GraalVM. https://github.com/oracle/graal/issues/5711

**Comment by melloware** [comment]
Forgot to mention it will be easy to switch back to a 3rd party lib if we need to but I thought for now this allows us better control over any JDK or Quarkus changes.

**Comment by maxandersen** [comment]
The issue is the license. 

Repost in Quarkiverse is expected to be under apache license. See https://github.com/quarkiverse/quarkiverse/wiki#license

Extensions can be under ASL and then use MPL/license library. 

But whole inclusion is something we haven't accounted for. Hence my question/concern. 

Could we possibly isolate the LGPL/mpl in one subdirectory/submodule ? Or even host that elsewhere ?

**Comment by melloware** [comment]
That is a great idea. Let me move all the code to another submodule JAR with that license.

**Comment by melloware** [comment]
OK done: https://github.com/quarkiverse/quarkus-itext/issues/5
