### ISSUE TITLE
`quarkus.datasource.devservices.db-name` not applied to MS-SQL

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#32493]
### Describe the bug

I'm trying to setup a MS-SQL database in devservices, and hitting a snag where the `quarkus.datasource.devservices.db-name` not applied to `DataSource` or mapped Java objects (`@Entities`); it seems that it is using the `master` database.

Configuration:

```yaml
quarkus:
  datasource:
    devservices:
      image-name: "mcr.microsoft.com/mssql/server:2017-latest"
      db-name: "APISO"
      init-script-path: "db/migration/V1.0.0__apiso.sql"
```

Test Code:

```java
try(Connection db = ds.getConnection()){
	try(
			CallableStatement stmt = db.prepareCall("SELECT DB_NAME();");
	){
		stmt.execute();
		ResultSet dbResult = stmt.getResultSet();
		dbResult.next();
		log.info("Database used: {}", dbResult.getString(1));
	}

	try(
			CallableStatement tstmt = db.prepareCall("SELECT * FROM APISO.INFORMATION_SCHEMA.TABLES;");
	){
		tstmt.execute();
		
		ResultSet tablesResult = tstmt.getResultSet();
		ResultSetMetaData rsm = tablesResult.getMetaData();
		
		List<String> cols = new ArrayList<>();
		for(int i = 1; i < rsm.getColumnCount(); i++) {
			cols.add(rsm.getColumnName(i));
		}
		log.info("Columns: {}", cols);
		
		
		while(tablesResult.next()) {
			Map<String, Object> results = new HashMap<>();
			
			for(String curCol : cols) {
				results.put(
						curCol, 
						tablesResult.getObject(curCol)
						);
			}
			
			log.info("Table: {}", results);
		}
	}
}
```

Excerpt of `db/migration/V1.0.0__apiso.sql`:

```sql
CREATE DATABASE [APISO];

USE [APISO];

CREATE SCHEMA [tst\SQL-APPDEV]
;
SET ANSI_NULLS ON
;
SET QUOTED_IDENTIFIER ON
;

CREATE TABLE [dbo].[ExpectedTable](
 -- ...
);
```

### Expected behavior

```
2023-04-07 07:23:26,056 INFO  [org.tst.RunSetupTest] (main) Database used: APISO
2023-04-07 07:23:26,234 INFO  [org.tst.RunSetupTest] (main) Columns: [TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME]
2023-04-07 07:23:26,235 INFO  [org.tst.RunSetupTest] (main) Table: {TABLE_CATALOG=APISO, TABLE_NAME=ExpectedTable, TABLE_SCHEMA=dbo}
...
```

### Actual behavior

```
2023-04-07 07:23:26,056 INFO  [org.tst.RunSetupTest] (main) Database used: master
2023-04-07 07:23:26,234 INFO  [org.tst.RunSetupTest] (main) Columns: [TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME]
// Note still get expected tables as the sql query specified the database, so I know it is being created and setup
2023-04-07 07:23:26,235 INFO  [org.tst.RunSetupTest] (main) Table: {TABLE_CATALOG=APISO, TABLE_NAME=ExpectedTable, TABLE_SCHEMA=dbo}
...
```

### Output of `uname -a` or `ver`

Windows 11, with Docker on Ubuntu on WSL2

### Output of `java -version`

openjdk 11.0.18 2023-01-17 LTS OpenJDK Runtime Environment Microsoft-7208460 (build 11.0.18+10-LTS) OpenJDK 64-Bit Server VM Microsoft-7208460 (build 11.0.18+10-LTS, mixed mode)

### Quarkus version or git rev

2.16.6

**Comment by gsmet** [comment]
This is a known limitation. The SQL Server container in Testcontainers doesn't support setting the database name nor the username.
You can create an issue upstream if you want but we will need support there and then you could create a PR once available upstream.

The code to adjust is here: https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/mssql/src/main/java/io/quarkus/devservices/mssql/deployment/MSSQLDevServicesProcessor.java#L46-L48

Closing as we can't do anything on our side for now. Please reopen or even better create a PR when addressed upstream.

**Comment by Eng-Fouad** [comment]
> This is a known limitation. The SQL Server container in Testcontainers doesn't support setting the database name nor the username. You can create an issue upstream if you want but we will need support there and then you could create a PR once available upstream.
> 
> The code to adjust is here: https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/mssql/src/main/java/io/quarkus/devservices/mssql/deployment/MSSQLDevServicesProcessor.java#L46-L48
> 
> Closing as we can't do anything on our side for now. Please reopen or even better create a PR when addressed upstream.

In my application, I create new DB using JDBC at application initialization. Then I have to use fully qualified table name ‘DbName.dbo.TableName’ in DB queries. I think it is necessary to support specifying DB name using ‘ quarkus.datasource.devservices.db-name’.

**Comment by Eng-Fouad** [comment]
I even tried to set additional JDBC properties, but it didn't work:

> %dev.quarkus.datasource.jdbc.additional-jdbc-properties=databaseName=myDB
> %dev.quarkus.datasource.devservices.container-properties=databaseName=myDB

**Comment by Eng-Fouad** [comment]
My bad, I was using wrong configs.

This worked:

> %dev.quarkus.datasource.devservices.properties.databaseName=myDB
