### ISSUE TITLE
Doc incorrectly states -Dnative instead of -Pnative

### ISSUE THREAD

**Issue by FredTreg** [quarkusio/quarkus#32523]
### Describe the bug

In the directory `docs/src/main/asciidoc/_includes/devtools/`, the docs:

- build-native-container-parameters.adoc
- build-native-container.adoc
- build-native.adoc

Incorrectly states to use the Maven `-Dnative` flag instead of using the `-Pnative` flag

**Comment by FredTreg** [comment]
Could we at least agree that for a Quarkus newbie it is confusing to see both `-Dnative` and `-Pnative` on the same page:
https://quarkus.io/guides/building-native-image

One line says:
```
./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
```
And a few lines below:
```
./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
```

**Comment by geoand** [comment]
Yes, that certainly is confusing. 

If you want to contribute a fix to the docs, that would certainly be welcome

**Comment by FredTreg** [comment]
ok, will do. Would you recommend normalizing toward -D or -P

**Comment by geoand** [comment]
I would recommend using whatever is used more often in the docs :)

**Comment by gsmet** [comment]
Yes, please use the property. Thanks.

**Comment by gsmet** [comment]
The documentation is hosted here: https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
