### ISSUE TITLE
devui 2 continous testing layout issues

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#32522]
### Describe the bug

The circle is using a lot of real estate and the way the layout performs makes it hide the real good info.

![2023-04-11_10-23-36](https://user-images.githubusercontent.com/54129/231101777-e21b4057-204f-47d5-b339-a86b043c4311.png)

https://user-images.githubusercontent.com/54129/231102301-42846e28-fcb1-43eb-9211-fcd9fa6140c8.mp4

### Expected behavior

i suggest we put a flat progress bar sticky at the top rather than this 30% land grab :)

**Comment by gsmet** [comment]
@phillip-kruger I agree with @maxandersen that we should optimize the space. It can be done for 3.0.1 though.

**Comment by phillip-kruger** [comment]
Yes this is on my to-do list, as discussed with @maxandersen this will change to a horizontal bar
