### ISSUE TITLE
3.0.0.CR2 Statement Leak reported by Agroal

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#32539]
### Describe the bug

Logs show "[io.agr.pool] (executor-thread-1) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)"
When JPA gets an exception

### Expected behavior

Should not have warnings about leaked statements

### Actual behavior

Get warning:
[io.agr.pool] (executor-thread-1) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)

### How to Reproduce?

1. git clone https://github.com/bcluap/quarkus-examples.git
2. cd code-with-quarkus
3. Update src/main/resources/application.properties to reference a valid database
4. mvn verify
5. Logs will show a statement is leaked. This does not happen on version 2.16.6.Final

### Output of `uname -a` or `ver`

Any

### Output of `java -version`

Any

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

This is caused by any SQL exception from what I can see. I've seen it with lock wait timeout, permissions errors etc

**Comment by bcluap** [comment]
Thanks @yrodiere

**Comment by yrodiere** [comment]
Created https://hibernate.atlassian.net/browse/HHH-16458 and sent https://github.com/hibernate/hibernate-orm/pull/6394

**Comment by yrodiere** [comment]
This was fixed by https://github.com/quarkusio/quarkus/commit/a73fbb09b964d99767f6594200224902b2d89478 in Quarkus 3.2.0.CR1
