### ISSUE TITLE
Quarkus kubernetes and helm extension setting values defined in application properties as environment variables in values and deployment.yml

### ISSUE THREAD

**Issue by mehab** [quarkusio/quarkus#32549]
### Describe the bug

If a user has a custom property defined in the application.properties file of a project for example:
` api.topic.prefix= `
And then this property is used by another property in the same file for example: 
`quarkus.kafka-streams.application-id=${api.topic.prefix}test `
And we are using the helm and kubernetes extension for this project, then upon doing mvn clean install the list of env vars created in the values.yml would contain and env var api.topic.prefix : 
```
api:
      topic:
        prefix: ""
```
and there would be a corresponding field in the deployment.yml:
`- name: api.topic.prefix
              value: {{ .Values.app.envs.api.topic.prefix }}`

In this process when a custom property was actually called base-url in the application properties and got added as an env var in values.yaml and deployment.yaml, helm complains of "-" not allowed in deployment.yaml and bad syntax upon doing `helm install`

### Expected behavior

Custom application properties used as variables in the properties file should not get added to the environment variables created in the values and deployment.yaml

### Actual behavior

If a user has a custom property defined in the application.properties file of a project for example:
` api.topic.prefix= `
And then this property is used by another property in the same file for example: 
`quarkus.kafka-streams.application-id=${api.topic.prefix}test `
And we are using the helm and kubernetes extension for this project, then upon doing mvn clean install the list of env vars created in the values.yml would contain and env var api.topic.prefix : 
```
api:
      topic:
        prefix: ""
```
and there would be a corresponding field in the deployment.yml:
`- name: api.topic.prefix
              value: {{ .Values.app.envs.api.topic.prefix }}`

### Output of `java -version`

`openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)`

### GraalVM version (if different from Java)

`openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)`

### Quarkus version or git rev

`2.16.6.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /opt/homebrew/Cellar/maven/3.8.3/libexec
Java version: 17.0.5, vendor: GraalVM Community, runtime: /Users/kt/.sdkman/candidates/java/22.3.r17-grl
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "x86_64", family: "mac"`

**Comment by Sgitario** [comment]
This is a Quarkus Helm issue that should be reported at https://github.com/quarkiverse/quarkus-helm.
As a workaround, you can disable the mapping of system properties by using `quarkus.helm.map-system-properties=false`.
