### ISSUE TITLE
High memory utilization using Quarkus Native

### ISSUE THREAD

**Issue by JBailes** [quarkusio/quarkus#32547]
### Describe the bug

When running performance tests comparing quarkus native to spring native, quarkus native uses significantly more memory than expected. Our results closely mirror https://www.baeldung.com/spring-boot-vs-quarkus with Quarkus utilizing on average 2.5x to 3x the amount of RAM of Spring Boot, up to a peak of 5x RAM. This applies to both K8S and Serverless testing.

### Expected behavior

The RAM utilization to more closely mirror what Spring native does.

### Actual behavior

When running performance tests comparing quarkus native to spring native, quarkus native uses significantly more memory than expected. Our results closely mirror https://www.baeldung.com/spring-boot-vs-quarkus with Quarkus utilizing on average 2.5x to 3x the amount of RAM of Spring Boot, up to a peak of 5x RAM. This applies to both K8S and Serverless testing.

### How to Reproduce?

Create a simple Spring Boot native project and a Quarkus native project.

Implement the bare minimum needed to create a "ping" endpoint that simply responds "pong".

Begin pushing traffic against the relevant endpoints.

**Comment by JBailes** [comment]
@melloware My personal test results replicated closely what I saw from Baeldung, as I noted in the original issue. Could you please provide more information as to why you feel that the information regarding memory utilization is wrong?

**Comment by melloware** [comment]
Well the Red Hat article above explains why the Baeldung tests were incorrect comparison.  I would read it first.

**Comment by melloware** [comment]
I am saying the article you cited is incorrect in its comparison.  Please post both your Spring Boot and Quarkus projects here so it can be seen exactly.

**Comment by JBailes** [comment]
@melloware Could you please provide more information on why you feel it is incorrect for it's comparison for memory utilization? I'll be putting up my projects on github to reference this evening/tomorrow as I have time, but the key point I am not understanding here is why this impacts memory utilization. I've read the linked article, and I'm trying to understand the feedback from you, and I am not understanding how this would impact memory utilization. Thanks.

**Comment by melloware** [comment]
@JBailes I am saying you cited an already that has already been proved to be an invalid test so I am saying don't reference that Baeldung article. If you have a real issue please post your projects.  That is what I am saying is that baeldung had incorrect code.  So others will need to see your code to see if there is a real issue.

Are you not understanding what I am saying?

**Comment by melloware** [comment]
Also you conveniently left out all the other info in the ticket like which Quarkus version?  OS version? JDK Version?

**Comment by geoand** [comment]
cc @johnaohara who wrote the redhatperf article.

@johnaohara please have a look here when you have time and feel free to close  if there is nothing to be done.

**Comment by JBailes** [comment]
@melloware I think you've hit the nail on the head, that explains the results I was getting last night. I also suspect Quarkus caches much more aggressively then Spring Boot, as I am seeing Quarkus use substantially (~30%) less CPU then Spring. This evening I'm planning on playing around more with the memory settings.

**Comment by johnaohara** [comment]
I am offline until Mon 17th, @galderz performed are more recent analysis and tuning of GC for Quarkus native images. 

@galderz do you have any further insight that might explain this behavior

**Comment by galderz** [comment]
> Also you conveniently left out all the other info in the ticket like which Quarkus version? OS version? JDK Version?

@melloware makes a crucial point here. The lack of information is disappointing to say the least, but ignoring that, you should be aware that have seen similar memory behaviour to what the Baeldung blog post showed in the past. However, this behaviour should be resolved by now. A [recent Quarkus blog post](https://quarkus.io/blog/native-adopts-adaptive-gc-policy/) tells the story of this issue, as well as providing links to more technical explanations etc.

**Comment by geoand** [comment]
I am going to close this as there does not seem to be a real issue.

**Comment by melloware** [comment]
@JBailes and company this is also why I have petitioned Baeldung to take down their article or make it accurate as its leading to misinformation out in the space about Spring Boot vs Quarkus.  I have used both heavily and I dread working in Spring Boot and I enjoy every second of working in Quarkus. 😄

**Comment by geoand** [comment]
>  have used both heavily and I dread working in Spring Boot and I enjoy every second of working in Quarkus

Quite the praise 💌

**Comment by melloware** [comment]
@JBailes if you did make updates I would be interested to hear about your final comparison results?
