### ISSUE TITLE
How to configure quarkus app on gke to use a sidecar proxy

### ISSUE THREAD

**Issue by Endagegnehu** [quarkusio/quarkus#32556]
### Discussed in https://github.com/quarkusio/quarkus/discussions/32550

<div type='discussions-op-text'>

<sup>Originally posted by **Endagegnehu** April 11, 2023</sup>
Hello, new to Quarkus; how do I connect to a cloud SQL sidecar proxy that is running on GKE?    </div>

**Comment by geoand** [comment]
As this is a question, let's close it and keep the discussion in https://github.com/quarkusio/quarkus/discussions/32550
