### ISSUE TITLE
Smalllrye openapi (swagger?) does not take registered Jackson ObjectMapperCustomizer into account

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#32568]
### Describe the bug

The smallrye openapi (Swagger?) UI shows fields that aren't part of the RestEasy output. It seems like the Jackson ObjectMapperCustomizer only applies to RestEasy, not Swagger.

For example, OptaPlanner has a HardSoftScore class with 3 fields (initScore, hardScore and softScore) and helper methods like isFeasible() which returns (hardScore >= 0).
The REST API renders HardSoftScore as a String in Json, but the Swagger API description shows it as an object class with feasible etc:
    
![image](https://user-images.githubusercontent.com/176880/231422200-96a1048c-bb43-4dc8-95b2-d25a90df40b8.png)

It seems like RestEasty takes this into account, but Swagger does not:
    
```
    @BuildStep
    void registerOptaPlannerJacksonModule(BuildProducer<AdditionalBeanBuildItem> additionalBeans) {
        additionalBeans.produce(new AdditionalBeanBuildItem(OptaPlannerObjectMapperCustomizer.class));
    }
```
    
    https://github.com/kiegroup/optaplanner/blob/main/optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/src/main/java/org/optaplanner/quarkus/jackson/deployment/OptaPlannerJacksonProcessor.java
    
    https://github.com/kiegroup/optaplanner/blob/main/optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/src/main/java/org/optaplanner/quarkus/jackson/OptaPlannerObjectMapperCustomizer.java

### Expected behavior

REST API:
```
myClass {
  score : "0hard/5soft"
}
```
Swagger API:
```
myClass {
  score : String
}
```

### Actual behavior

REST API:
```
myClass {
  score : "0hard/5soft"
}
```
Swagger API:
```
myClass {
  score : HardSoftScore
}
HardSoftScore {
 initScore: number
 hardScore: number
 softScore: number
 feasible: boolean
 ...
}
```
### How to Reproduce?

1. Add these dependencies:

    <dependency>
      <groupId>org.optaplanner</groupId>
      <artifactId>optaplanner</artifactId>
    </dependency>
    <dependency>
      <groupId>org.optaplanner</groupId>
      <artifactId>optaplanner-quarkus-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    
2. Create a REST method that returns MyClass with a field of type HardSoftScore.
Jackson will customize the json marshalling with OptaPlannerObjectMapperCustomizer.

3. Check the Swagger API screen, notice that there is a HardSoftScore model that includes "feasible", so OptaPlannerObjectMapperCustomizer is not active.

**Comment by MikeEdgar** [comment]
Hi @ge0ffrey , have you raised this issue with OptaPlanner? Since there is a Quarkus extension, perhaps it could be updated to take the OpenAPI output into account. With the types being serialized/de-serialized with customizations, the class information used by Quarkus to generate OpenAPI won't be enough to stay aligned with the actual REST types.

**Comment by phillip-kruger** [comment]
Closing. No response. Please reopen if needed
