### ISSUE TITLE
q/dev-ui should be just q/dev

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#32575]
### Describe the bug

3.0 seem to redirect to q/dev-ui instead of q/dev

should just use the short form.

**Comment by phillip-kruger** [comment]
This was intentional. `/q/dev` will always just work, but redirect to `/q/dev-ui`. All our ui's in Quarkus ends with `-ui` so this is in line with that (`/swagger-ui`, `health-ui`, `graphql-ui`)

**Comment by maxandersen** [comment]
that is super annoying though. why make the default URL longer and flash with a reload?

**Comment by phillip-kruger** [comment]
I think we can close this ?
