### ISSUE TITLE
404 Response Status on partialliy overlapped endpoints

### ISSUE THREAD

**Issue by lasteris** [quarkusio/quarkus#32588]
### Describe the bug

The problem is that if the value of the @Path annotation above the class matches the partial value of the @Path annotation but inside another class above the method, and then the delimiter "-" follows in the value above the method, then I get 404 Not Found anyway.
I am using resteasy-reactive, Gradle 8.0.2, Java 17+

Imagine that we have 2 classes:

```

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
}
```

and

```
@Path("")
public class RootResource {
    @Path("hello-not")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
}
```

Then when i do curl /hello-not i get 404 Status Not Found

I suggest that Resource class have priority is higher then methods, so quarkus trying to find resource '-not' in GreetingResource (not in Root as it should by my opinion). But if its not bug but feature where i missed info about it and why is that ?

### Expected behavior
200 OK

### Actual behavior

404  Not Found

### How to Reproduce?

To make reproducer i created simple project via https://code.quarkus.io
and placed in it 2 classes from previous section. It is in attached zip. [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/11215717/code-with-quarkus.zip)
So,to reproduce problem you need just quarkusDev project and curl http://host:port/hello-not

### Output of `java -version`

17.0.6

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.0.2

**Comment by lasteris** [comment]
> 

Thank you !)

**Comment by lasteris** [comment]
> Thanks for reporting and providing a sample that shows the problem.
> 
> Although indeed I can reproducer the problem in Quarkus 2.16, in Quarkus 3 everything works as expected, so I will close this.

Thank you for fast reply )

**Comment by geoand** [comment]
👌
