### ISSUE TITLE
Quarkus 3.0.0.CR2 : DevUI error with custom root path

### ISSUE THREAD

**Issue by sombraglez** [quarkusio/quarkus#32581]
### Describe the bug

After migrating an application with a custom root path (`quarkus.http.root-path`) to Quarkus 3.0.0.CR2 the expected redirect from http://localhost:8080/my-root-path/q/dev to http://localhost:8080/my-root-path/q/dev-ui is not working. 

Furthermore, trying to access the DevUI at http://localhost:8080/my-root-path/q/dev-ui also fails due too missing components (for example, HTTP 404 accessing http://localhost:8080/_static/es-module-shims/dist/es-module-shims.js)

It seems like the root path it's ignored during the building of the new DevUI

### Expected behavior

DevUI should be also available for applications with a custom root path 

### Actual behavior

DevUI is currently not available for applications using Quarkus 3.00.CR2 and a custom root path

### How to Reproduce?

Using the https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started service:

1. Manually migrate from current 2.16.6.Final to version 3.0.0.CR2 or applying the available OpenRewrite migration recipe as described here https://quarkus.io/blog/quarkus-3-0-0-cr2-released/#automated-migration
2. Configure a custom root path. For example `quarkus.http.root-path=/my-root-path/`
3. Start the application in dev mode `mvn quarkus:dev`
4. Access the DevUI pressing `d` or accessing http://localhost:8080/my-root-path/q/dev-ui or http://localhost:8080/my-root-path/q/dev

### Output of `java -version`

17.0.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by phillip-kruger** [comment]
Thanks for the bug, this is missing in the new Dev UI, I'll add support for it a.s.a.p.

**Comment by cescoffier** [comment]
About the redirect, yes, my bad. It should redirect to root + q/dev-ui.

**Comment by phillip-kruger** [comment]
@cescoffier no worries, I am busy fixing

**Comment by sombraglez** [comment]
Thanks for the fix @phillip-kruger 👍
