### ISSUE TITLE
CDI observer methods should be inherited if not overriden

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#3260]
See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#member_level_inheritance for more information.

**Comment by michalszynkiewicz** [comment]
@mkouba do you know of any out of the box way of checking if a method has not been overriden? As I understand, if a bean overrides the method that `@Observes`, the observing method should not be called.

**Comment by mkouba** [comment]
I think that you will need to walk the hierarchy and compare the method signatures (name + params).
