### ISSUE TITLE
[quarkus-resteasy] All classes are scanned and registered even though the javax.ws.rs.core.Application returns a non-empty set of classes

### ISSUE THREAD

**Issue by atzoum** [quarkusio/quarkus#3262]
**Describe the bug**
Assuming that 2 `javax.ws.rs.ext.Provider`classes are available in the classpath:
1. `UriInfoFilter`
2. `JacksonJsonProvider`

And the following `javax.ws.rs.core.Application` exists

```
@ApplicationPath("/")
public class App extends Application {

    public Set<Class<?>> getClasses() {
        return Stream.of(UriInfoFilter.class).collect(toSet());
    }
}
```

**Expected behavior**
According to the JAX-RS spec, only `UriInfoFilter` should be registered.

> When an Application subclass is present in the archive, if both Application.getClasses
and Application.getSingletons return an empty collection then all root resource classes and
providers packaged in the web application MUST be included and the JAX-RS implementation is
REQUIRED to discover them automatically by scanning a .war file as described above. If either
getClasses or getSingletons returns a non-empty collection then only those classes or singletons returned MUST be included in the published JAX-RS application.

**Actual behavior**
Both providers are registered and additionally the following warning is logged

```
INFO  RESTEASY002205: Adding provider class UriInfoFilter from Application class App
WARN  RESTEASY002155: Provider class UriInfoFilter is already registered.  2nd registration is being ignored.
```

**Comment by atzoum** [comment]
It is fine I guess for quarkus to always register its own internal provider classes, nevertheless it is equally important to be able to control which application's JAX-RS classes will finally get registered in the JAX-RS application instead of always relying to classpath scanning. 
Developers sometimes need to be in control of the registered classes in order to avoid unpleasant surprises when upgrading external dependencies!

**Comment by sberyozkin** [comment]
Probably a property should be introduced to optionally disable the auto registration if the custom Application exists

**Comment by gsmet** [comment]
@kenfinnigan any thought about that one?

**Comment by kenfinnigan** [comment]
From a quick look through the extensions, it appears we only take into account `@ApplicationPath`, and not what might be defined by `Application` child.

**Comment by atzoum** [comment]
Any progress?

**Comment by Erfankam** [comment]
Still no progess :(. I can not disable auto scan feature in Resteasy to avoid register all @Provider annotated classes.

**Comment by Erfankam** [comment]
Could I work on this issue? I think this could be done by using resteasy.scan and other related properties.

**Comment by essobedo** [comment]
Here is a potential PR https://github.com/quarkusio/quarkus/pull/14207
