### ISSUE TITLE
Undertow: ServletContainerInitializer not loading

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32625]
### Describe the bug

Same code in 2.16.6 and 3.0.0.Final I am not seeing the output from ServletContainerInitializer.

2.x Reproducer: 
[quarkus-servlet-2x.zip](https://github.com/quarkusio/quarkus/files/11223921/quarkus-servlet-2x.zip)

3.0.0 Reproducer:
[quarkus-servlet-3x.zip](https://github.com/quarkusio/quarkus/files/11223940/quarkus-servlet-3x.zip)

run `mvn quarkus:dev` and watch the output.

2.x you see the ServletInitializer output:
![image](https://user-images.githubusercontent.com/4399574/231812779-d67870cd-951c-4c93-88ee-e7669aa80150.png)

3.x you see nothing:
![image](https://user-images.githubusercontent.com/4399574/231812878-55e55c56-e572-4530-ab81-835e931c9f00.png)

### Expected behavior

ServletContainerInitializer initializes and log messages appear.

### Actual behavior

Nothing appears to be happening

### How to Reproduce?

Run `mvn quarkus:dev` on both attached reproducers.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1555]

### Output of `java -version`

Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10

### Quarkus version or git rev

3.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

### Additional information

```java
package org.acme;

import java.util.Set;
import java.util.logging.Logger;

import jakarta.servlet.ServletContainerInitializer;
import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletException;

import lombok.extern.jbosslog.JBossLog;

@JBossLog
public class ApplicationInitializer implements ServletContainerInitializer {

	@Override
	public void onStartup(Set<Class<?>> c, ServletContext servletContext) throws ServletException {
		log.info("Checking servlet resource paths...");

		Set<String> resourcePaths = servletContext.getResourcePaths("/");
		for (String resourcePath : resourcePaths) {
			log.info("Resource: " + resourcePath);
		}
		
		if (resourcePaths.isEmpty()) {
			log.warn("NO servlet resource paths found!");
		}
	}
}
```

**Comment by melloware** [comment]
I tested on Windows and Linux and the behavior is the same on both. so this can be untagged Windows it should be marked for Undertow.

**Comment by gsmet** [comment]
Did you rename your service file? It should be `META-INF/services/jakarta.servlet.ServletContainerInitializer`. It's probably something we need to include in the migration recipe.

**Comment by melloware** [comment]
Yep that was it.  Closing :)

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus-updates/pull/29/files .

It will be in the next version of the update (I have a few other tweaks planned).
