### ISSUE TITLE
gRPC Health is not exposed for services from external dependency

### ISSUE THREAD

**Issue by guven** [quarkusio/quarkus#32622]
### Describe the bug

When exposed gRPC services are all from external dependencies, gRPC health endpoint is not exposed.

```
$ grpcurl -plaintext localhost:8080 list
service.from.dependency.SomeService
```

But when you add a dummy service in a dummy proto file locally to the project, the gRPC health endpoint is then exposed properly.

```
$ grpcurl -plaintext localhost:8080 list
grpc.health.v1.Health
service.from.dependency.SomeService
dummy.DummyGrpc
```

Setting `quarkus.grpc.server.health.enabled = true` does not change the behaviour.

### Expected behavior

gRPC health endpoint is exposed properly if at least one gRPC service is registered, regardless of where the service is defined.

When `quarkus.grpc.server.health.enabled = true`, gRPC health endpoint should be exposed even if there are no gRPC services registered.

### Actual behavior

gRPC health endpoint is exposed only when at least one service local to the project is registered.

### Output of `uname -a` or `ver`

Darwin XLGXYGX9JF 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000 arm64 arm Darwin

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Homebrew (build 17.0.3+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.3+0, mixed mode, sharing)

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)

**Comment by alesj** [comment]
How do you make `service.from.dependency.SomeService` findable?
Via Jandex index or beans.xml ?

**Comment by guven** [comment]
Apparently, we do not have either Jandex or beans.xml.

I added a Jandex index, and the issue is solved.

Thanks @alesj :)

**Comment by guven** [comment]
To aid with easier diagnostics, does it make sense to add a warning when a gRPC service is started but does not have an index pointing to it?

**Comment by guven** [comment]
I extended from the ImplBase and annotated with `@GrpcService`

**Comment by alesj** [comment]
> I extended from the ImplBase and annotated with @GrpcService

Hmmm, it's still strange then that it's picked up -- as there is no Jandex index or beans.xml ...

```
    @BuildStep
    void discoverBindableServices(BuildProducer<BindableServiceBuildItem> bindables,
            CombinedIndexBuildItem combinedIndexBuildItem) {
        IndexView index = combinedIndexBuildItem.getIndex();
        Collection<ClassInfo> bindableServices = index.getAllKnownImplementors(GrpcDotNames.BINDABLE_SERVICE);
```

Any idea @geoand on how this could be -- that the external service is found ^^ ?

**Comment by cescoffier** [comment]
No matter what, the external dependency needs an index or be added to the indexed dependencies (https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index)

**Comment by alesj** [comment]
Trying to replicate this here
* https://github.com/alesj/quarkus_cl130/tree/health1

**Comment by alesj** [comment]
@guven can you check what's different in my case ... since it doesn't pickup my external service ...

Note: if I add Jandex plugin to `common` pom.xml then it works

**Comment by guven** [comment]
I could not see which service you tried this on. I created a sample repo for this:

https://github.com/guven/quarkus-grpc-health

**Comment by alesj** [comment]
@guven see `common` module, that's "your" external

**Comment by alesj** [comment]
> I created a sample repo for this:

@guven where do you configure the use of new Vert.x gRPC server?
As there is no application.properties ...

**Comment by alesj** [comment]
Ah, sorry ... missed it
* https://github.com/guven/quarkus-grpc-health/blob/main/external/src/main/resources/application.properties

**Comment by gsmet** [comment]
The initial issue reported was fixed by indexing the external libraries with Jandex.
