### ISSUE TITLE
Quarkus Mutiny guide mistake

### ISSUE THREAD

**Issue by SetoKaiba** [quarkusio/quarkus#32635]
### Describe the bug

https://quarkus.io/guides/mutiny-primer#shortcuts
It's said that there is a method `uni.then(() → uni2)` which is a shortcut of `uni.onItem().transformToUni(ignored → uni2)`.
But it seems that there's no method called `then`.

https://github.com/smallrye/smallrye-mutiny/pull/1228/files
This PR is related.

Maybe it's a deprecated method. And also, it can be updated to `uni.chain(() → uni2)` I think.

**Comment by jponge** [comment]
This is correct, thanks for spotting that!
