### ISSUE TITLE
Openshift application has no access to secrets

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#32640]
### Describe the bug

I have secrets already created. I deploy an application to OpenShift for the first time in this namespace / project. The application cannot access the secrets I created before.

I'm using the kubernetes-config extension. Seems to be another service account issue, not applied at the right time.

If I delete the deployment config and re-deploy it, it works.

**Comment by Sgitario** [comment]
This is similar to https://github.com/quarkusio/quarkus/pull/32208. 
Will provide a fix asap.
