### ISSUE TITLE
Flyway migration: JavaMigration doesn't respect location

### ISSUE THREAD

**Issue by morhei** [quarkusio/quarkus#32654]
### Describe the bug

Hi,

I found an issue with the Flyway migration.
I have two projects
* Project **A**
  *  /src/main/resources/db/migration/V01__init_a.sql
  * /src/main/java/db/migration/V02__update.java
* Project **B**
  *  /src/main/resources/db/migration_b/V01__init_b.sql
  
with project **A** having a dependency to project **B**. Each project gets their separate datasources (e.g. **A** is setup to use schema **AS** and **BS** is setup to use schema BS).
While the sql migrations in the resource folder are applied to their respective datasources, the JavaMigration is applied to both yielding errors since the datasource for **B** doesn't have the tables that are altered in the migration.

My guess is that the `applicationCallbackClasses` [here](https://github.com/quarkusio/quarkus/blob/b73c1d68007ed0ea4d84012f9261e60a79354688/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/QuarkusPathLocationScanner.java#L27)  are only set once and have as a physical location `/JavaMigration.java` whereas the migration files have the proper path and hence can be filtered.

### Expected behavior

The JavaMigration is applied to only the original intended datasource

### Actual behavior

The JavaMigration is applied to both datasources

### How to Reproduce?

1. clone https://github.com/morhei/quarkus-flyway-migration-bug
2. build project `lib`
3. build project `service`
4. run the testcase in project `service` -- this triggers the migration

**Comment by morhei** [comment]
I was so free and created a PR to fix the issue. I tested it in my application where the bug originally occurred. Unfortunately I didn't see any unit tests where I could add a test to.

**Comment by morhei** [comment]
Thanks for merging the PR!

I've noticed that it's for the 3.1 milestone. Would it be possible to backport since we're blocked by this issue?

**Comment by geoand** [comment]
I have added the `backport` label so we can get this into a `3.0.z` release
