### ISSUE TITLE
Mailer - Add the ability to configure a list of approved recipients

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32688]
### Discussed in https://github.com/quarkusio/quarkus/discussions/32685

<div type='discussions-op-text'>

<sup>Originally posted by **canidae** April 17, 2023</sup>
Prior to Quarkus 3.0.0.Final I could extend MutinyMailerImpl to implement a whitelisting of email recipients. Unfortunately, a [recent change](https://github.com/quarkusio/quarkus/commit/fb2affe542af486181755282763023c411865a42) broke this, and I don't see an easy way to reimplement my whitelisting with the latest iteration of the mailer.

This was implemented as a library used by 20 or so internal projects who all simply would `@Inject ReactiveMailer` as if they used `quarkus-mailer` directly, but with a whitelisting feature. Whitelisting is a useful feature for us, as we'd like to limit who we may send mails to during QA-testing (where the mock mailbox is not sufficient as we'd still like to send mails to some select recipients, but prevent accidentally sending to i.e. customers due to inadequately washed test data).

Preferably I'd like to see whitelisting as a feature in `quarkus-mailer`, but it seems like this isn't a feature requested by many other people. Thus my question is if I can easily modify the code below to work with Quarkus 3.0.0.Final.

Code:
```java
@Alternative
@Priority(1)
@ApplicationScoped
public class WhitelistMailerImpl extends MutinyMailerImpl {
    @Inject
    Logger log;

    @ConfigProperty(name = "mailer.whitelist.enabled")
    Optional<Boolean> whitelistEnabled;

    @ConfigProperty(name = "mailer.whitelist.emails")
    Optional<List<String>> whitelistEmails;

    @Override
    public Uni<Void> send(Mail... mails) {
        if (!whitelistEnabled.orElse(!LaunchMode.current().isDevOrTest()))
            return super.send(mails);

        var allowedMails = new ArrayList<Mail>();
        for (var mail : mails) {
            var to = filterWhitelisted(mail.getTo());
            var cc = filterWhitelisted(mail.getCc());
            var bcc = filterWhitelisted(mail.getBcc());
            if (to.isEmpty() && cc.isEmpty() && bcc.isEmpty()) {
                log.warnf("A mail to %s, cc %s, bcc %s with subject '%s' was not sent. Whitelisting is enabled and there were " +
                        "no whitelisted email addresses in the mail.", mail.getTo(), mail.getCc(), mail.getBcc(), mail.getSubject());
            } else {
                mail.setTo(to);
                mail.setCc(cc);
                mail.setBcc(bcc);
                allowedMails.add(mail);
            }
        }
        return allowedMails.isEmpty() ? Uni.createFrom().voidItem() : super.send(allowedMails.toArray(Mail[]::new));
    }

    private List<String> filterWhitelisted(List<String> emails) {
        var allowedRecipients = whitelistEmails.orElse(Collections.emptyList());
        var keep = new ArrayList<String>();
        for (var email : emails) {
            for (var regex : allowedRecipients) {
                if (email.matches(regex)) {
                    keep.add(email);
                    break;
                }
            }
        }
        return keep;
    }
}
```</div>

**Comment by gsmet** [comment]
@canidae could you check if https://github.com/quarkusio/quarkus/pull/32689 fixes the issue for you?

Follow the instructions in https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main and use my PR branch instead of `main`.

**Comment by canidae** [comment]
Thanks for the quick reply. As for just using my code as it is, this does not seem to fix the problem (I did check out and build from your branch). The (only) constructor of MutinyMailerImpl is obviously still package protected, so extending the class as I've done won't work.
Perhaps you have another solution in mind, but I'll need some pointers in the right direction for that :)

**Comment by gsmet** [comment]
Reopening as my fix didn't fix anything. See, that's why it's better to describe the problem precisely ;).

I'll have a look later this week but for now, I'm leaning towards implementing your feature in Quarkus directly. We have options more exotic than that.

**Comment by canidae** [comment]
Sounds great, thanks!
I did start looking into making a PR, but I currently don't have a beefy enough computer to endure compiling Quarkus :sweat_smile: 
I'll just leave my first idea here as "inspiration" in case it's of any value (didn't get to actually test this...). Idea was to add a config property `quarkus.mailer.whitelist`, a list of regexes used to filter out recipients.

*MutinyMailerImpl.java*:
```java
    private Uni<Void> send(Mail mail, MailMessage message) {
        if (mock) {
            LOGGER.infof("Sending email %s from %s to %s, text body: \n%s\nhtml body: \n%s",
                    message.getSubject(), message.getFrom(), message.getTo(),
                    message.getText() == null ? "<empty>" : message.getText(),
                    message.getHtml() == null ? "<empty>" : message.getHtml());
            return mockMailbox.send(mail, message);
        } else {
            if (whitelistEmails.isPresent()) {
                message.setTo(filterWhitelisted(message.getTo()));
                message.setCc(filterWhitelisted(message.getCc()));
                message.setBcc(filterWhitelisted(message.getBcc()));
                if (message.getTo().isEmpty() && message.getCc().isEmpty() && message.getBcc().isEmpty()) {
                    log.warnf(
                            "A mail to %s, cc %s, bcc %s with subject '%s' was not sent. There were no whitelisted email addresses in the mail.",
                            mail.getTo(), mail.getCc(), mail.getBcc(), mail.getSubject());
                }
            }
            return client.sendMail(message)
                    .replaceWithVoid();
        }
    }

    private List<String> filterWhitelisted(List<String> emails) {
        var allowedRecipients = whitelist.orElse(Collections.emptyList());
        var keep = new ArrayList<String>();
        for (var email : emails) {
            for (var regex : allowedRecipients) {
                if (email.matches(regex)) {
                    keep.add(email);
                    break;
                }
            }
        }
        return keep;
    }
```

**Comment by gsmet** [comment]
I wasn't able to work on that for 3.0.1 but it's still on my TODO list for the next micro, I didn't forget about it.

**Comment by gsmet** [comment]
@canidae could you give a try to this pull request: https://github.com/quarkusio/quarkus/pull/33278 ?

You have an example in the added tests.

It would be awesome if you could test the PR by following https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main (except you build my branch instead of the PR). Make sure to switch to the io.quarkus:quarkus-bom when testing (and go back to the platform one after).

Thanks!

**Comment by canidae** [comment]
Thanks for working on this. I'd like to help out, but right now I'm exceptionally busy. I might not be able to test within a reasonable amount of time :(

**Comment by gsmet** [comment]
@canidae no worries. I merged it. Let us know if it works for you when you have time to test the feature.
