### ISSUE TITLE
Enable @InjectSpy to skip @PostConstruct methods

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#32695]
### Description

Whenever injecting a spy by `@InjectSpy Service service` the service's @PostConstruct method is executed.
Would be nice to have a flag like `@InjectSpy(skipPostConstruct=true)` or nicer.
Without changing productioin code/config, this can be AFAIK only achieved by creating the spy by `Mockito.spy(Service.class)` which brings other problems (injected fields in Service are null).

**Comment by geoand** [comment]
Can you give a little more information on why this would be useful?

**Comment by geoand** [comment]
Closing as we did not get additional feedback about how the proposed feature is intended to be used
