### ISSUE TITLE
Add well-known `service` OIDC provider configurations

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#32698]
### Description

Right now, when we say `quarkus.oidc.provider=google` it means Quarkus acts in the `web-app` mode, controlling the authorization code flow itself and it can verify the ID token.
However, if we try to test Quarkus from OIDC DevUI where we login to Google, and pass the access token, it will fail unless we configure Quarkus to accept binary access tokens by indirectly verifying them by acquiring UserInfo - which requires 2 extra properties, plus another one overriding `quarkus.oidc.application-type=web-app` indirectly set by `quarkus.oidc.provider=google` to `quarkus.oidc.application-type=service`, which is 3 extra properties for devmode

But it would be easier if we could just say `quarkus.oidc.provider=google-service` or `quarkus.oidc.provider=github-service` and for all other well known (all of them ?) providers we support which return binary access tokens and do not allow to introspect them

### Implementation ideas

Expand `quarkus.oidc.provider=google-service` into OidcTenantConfig with the application type set to service and the indirect access token verification enabled

**Comment by jainhitesh9998** [comment]
there is an 
```
quarkus.oidc.application-type=web-app
```
where we can mention the type of service.
when this property along with
 ```
quarkus.oidc.provider=google
```
are set by user may be the autoconfig of a few specific properties could be done, this way one won't have to maintain
no. of providers * no. of application types of config [here] https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/providers/KnownOidcProviders.java?

**Comment by sberyozkin** [comment]
These providers will support the binary token verification via the userinfo acquisition by default, so for now I'm closing this issue
