### ISSUE TITLE
OIDC role claim path with URL json keys

### ISSUE THREAD

**Issue by dlymann** [quarkusio/quarkus#32694]
### Summary
The URL needs to be defined as follows for the `role-claim-path` to make the feature work. Note the double quote character at the end of the URL.
`role-claim-path: https://my-domain.com/roles"`

It neither works with double quote prefix and postfix or none at all.

### Setup

- Quarkus 2.16.6
- quarkus-oidc, resteasy, ...
- OIDC provider auth0

### Token example
`{
  "https://my-domain.com/roles": [
    "my-app-user"
  ],
  "https://my-domain.com/nickname": "dlmn.com",
  "iss": "https://mdm-mbp.eu.auth0.com/",
  "sub": "auth0|my-subject-id",
  "aud": [
    "https://mdm-mbp.eu.auth0.com/api/v2/",
    "https://mdm-mbp.eu.auth0.com/userinfo"
  ],
  "iat": 1681742848,
  "exp": 1681829248,
  "azp": "........",
  "scope": "openid profile email"
}`

### Expected behavior

The postfix double quote should not be necessary for the role claim part.

### Actual behavior

It seems that the OidcUtils uses the CLAIM_PATH_PATTERN that splits the URL in several paths. 
- https
- 
- my-domain 
- roles

Using the double quote at the end, the split results in a single string which matches with the json key for the roles.
- https://my-domain.com/roles

### How to Reproduce?

Define a token claim e.g. in auth0 and use the roles claim path `role-claim-part`

### Output of `uname -a` or `ver`

Darwin  22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by sberyozkin** [comment]
@dlymann Hi,

As far as I recall, it was dealt with, for example, I don't think we have an OIDC test, but the same pattern is used in smallrye-jwt, so for example:
https://github.com/smallrye/smallrye-jwt/blob/main/testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath.java#L69
will correctly get to 
https://github.com/smallrye/smallrye-jwt/blob/main/testsuite/basic/src/test/resources/TokenGroupsPath.json#L20

Oh, sorry, we actually have it for OidcUtils as well:
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/test/java/io/quarkus/oidc/runtime/OidcUtilsTest.java#L432..L450

These 2 tests work with this resource:
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/test/resources/tokenCustomPath.json

Can you check again please, maybe some extra spaces are interfering ?
If it still does not work, can you please create a test token and paste here, in the encoded format and I'll try it.

**Comment by dlymann** [comment]
@sberyozkin Thanks a lot for your quick reply.

- There doesn't seem to be any spaces or other characters.
- I forgot to mention that I use YAML config files.
- I realized that the role-claim-path configuration is actually a list. I tried to adapt accordingly, but the issue persists.
- Please find attached a test token and the config.

[test-token.txt](https://github.com/quarkusio/quarkus/files/11254686/test-token.txt)
[application.yml.txt](https://github.com/quarkusio/quarkus/files/11254691/application.yml.txt)

**Comment by sberyozkin** [comment]
Thanks @dlymann , will have a look tomorrow

**Comment by sberyozkin** [comment]
@dlymann As it happens, in YAML, one need to use single quotes to have double quotes retained, it is a pure YAML escaping issue. So if you set do something like`'"http://service/roles"' as a value then it will work, thanks
