### ISSUE TITLE
Rest-client throw a "HTTP 400 Bad Request" instead of "Bad Response From Server"

### ISSUE THREAD

**Issue by benDeMtp** [quarkusio/quarkus#32710]
### Describe the bug

With quarkus-rest-client-reactive, and quarkus-rest-client-reactive-jackson

When the service called return an invalid body, for example an invalid json, and a success status code, rest-client will throw :

org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'HTTP 400 Bad Request' when invoking: Rest Client method: 'org.acme.Endpoint#getDumb'

But the request is fine, in fact, this is the response that is incorrect.

This issue misleads investigations when we want to troubleshoot a problem between the client and the service.

The project contained in badrequest-reproducer.zip reproduce the issue with MockServer.

### How to Reproduce?

[badrequest-reproducer.zip](https://github.com/quarkusio/quarkus/files/11259348/badrequest-reproducer.zip)

### Quarkus version or git rev

2.16.6-Final

**Comment by geoand** [comment]
I'll have a look

**Comment by benDeMtp** [comment]
I just tried with 3.0.0.CR2, the behavior is the same.

**Comment by tanton81** [comment]
Hello, 
I am able to reproduce the issue with a well formed body but in the same time, it is not the client expects from the server.
I have quarkus 3.2.5.Final or may be 3.2.6.Final
