### ISSUE TITLE
quarkus.init-and-exit no longer works

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#32729]
### Describe the bug

The runtime configuration property: `quarkus.init-and-exit' is meant to be used to interrupt the execution right after the initialization is complete.

Interruption is achieved by firing a `PreventFurtherStepsException`. However, even when the exception is fired the application stays in a hung state. It does neither start nor exit.

**Comment by geoand** [comment]
This is unfortunate.

We should probably add a test for it.

@iocanel are you handling this or should I take a look?

**Comment by iocanel** [comment]
> @iocanel are you handling this or should I take a look?
I am trying to verify my findings just to make sure I am not doing something wrong. Will let you know.

**Comment by iocanel** [comment]
I rebuilt main and tried it with a few differnet examples. The issue is definitely there.
My understanding is that the `PreventFurtherStepsException` never reaches the `ApplicationLifeCycle` manager as is the expected and therefore it seems to end up waiting here: https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L152

The exception seems to be caught by the generated `ApplicationImpl` and trigger a `close` in the `StartupContext`. Not sure if this is how it should be working. Here I will definitely need some help @geoand.

**Comment by geoand** [comment]
I'll have a look tomorrow

**Comment by geoand** [comment]
I see that the AppCDs generation feature which depends on `PreventFurtherStepsException` works as expected.

Now let me try and see what is going on in your case.

**Comment by geoand** [comment]
#32750 should fix the issue. Can you give it a try please?
