### ISSUE TITLE
Edit Release Notes Quarkus 3.0.0 CR1 

### ISSUE THREAD

**Issue by lasteris** [quarkusio/quarkus#32736]
### Description

Please. can somebody add to list "Bump JDBC PostgreSQL Driver to 42.6.0" ? Because i see it in fresh pom (at CR1 tag),
but can't see it in Release notes. i was waitng release, where version would be updated, but it is already done silently...
Besides, 42.6.0 provides very important patch. They mostly replaced synchronized blocks with Reentrant Lock. So, now it is production ready to work with Loom (Virtual Threads).
See https://jdbc.postgresql.org/changelogs/2023-03-17-42.6.0-release/

### Implementation ideas

just add one line to release notes, please :D

**Comment by gsmet** [comment]
The release notes are generated automatically and it's there: https://github.com/quarkusio/quarkus/releases/tag/3.0.0.CR1 .

But the release notes are truncated weirdly in the list of releases so that might be why you missed it.
