### ISSUE TITLE
Bug in MDC Context Propagation with WebSocket ServerEndpoint and Redis Client

### ISSUE THREAD

**Issue by omarkad2** [quarkusio/quarkus#32745]
### Describe the bug

When attempting to propagate MDC context using a WebSocket server endpoint, a bug has been identified that causes the context to not be properly propagated in the `onMessage` handler, but it is successfully propagated in the `onOpen` handler, even when the same method is called.

This bug is consistently reproducible when using a Redis client. The exact nature of the bug may vary depending on the specific implementation, but it appears that the MDC context is not properly maintained when processing messages received by the server. This can lead to unexpected behavior and errors when attempting to use MDC in conjunction with WebSocket server endpoints.

### Expected behavior

I expect to have MDC context propagated in the `onMessage` handler the same way as in `onOpen` handler given that both are calling the exact same method

### Actual behavior

In `onMessage` handler the MDC is not propagated as expected. In the logs below, you can see that MDC was only set for first line but lost in the others
```
""01:05:12 INFO  user=Oussama [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-1) start
""01:05:12 INFO  user= [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-3) New heartbeat: 1681866312671
""01:05:12 INFO  user= [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-3) end
```

### How to Reproduce?

I created a reproducer project https://github.com/omarkad2/quarkus-mdc-propagation 
Each time a new websocket is opened or a new message is received we store the username (key) and current date (value) in redis

Notice that MDC is propagated on `onOpen` handler but not `onMessage` handler:
`onOpen` logs:
```
""01:05:08 INFO  user=Oussama [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-1) start
""01:05:08 INFO  user=Oussama [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-1) New heartbeat: 1681866308036
""01:05:08 INFO  user=Oussama [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-1) end
```
`onMessage` logs:
```
""01:05:12 INFO  user=Oussama [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-1) start
""01:05:12 INFO  user= [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-3) New heartbeat: 1681866312671
""01:05:12 INFO  user= [or.ac.qu.md.pr.ChatSocket] (vert.x-eventloop-thread-3) end
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 x86_64

### Output of `java -version`

GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

**Comment by cescoffier** [comment]
Just looked at the reproducer. The MDC in this case is stored as a thread local, not in the duplicated context. Because the subscribe callbacks are called on an event loop it cannot work.

Use the blocking API instead of the reactive one.

**Comment by omarkad2** [comment]
Ok I see. Is there a way to run async methods inside WebSocket handlers using Mutiny or should I be using blocking APIs ?

**Comment by cescoffier** [comment]
Yes you can but your MDC is not going to work.
I mentioned rendent l'y that we need to make onMessage invoked on duplicated context. That will simplify things.

**Comment by omarkad2** [comment]
@cescoffier Should we keep this issue open so that it's taken into account or you prefer that I close it ?

**Comment by cescoffier** [comment]
Can you open another feature request about the invocation on `onMessage` on a duplicated context?

**Comment by omarkad2** [comment]
Will do that thank you
