### ISSUE TITLE
Is quarkus 3.0.0.Final released?

### ISSUE THREAD

**Issue by DCCSKrezovic** [quarkusio/quarkus#32758]
### Describe the bug

There's a tag https://github.com/quarkusio/quarkus/releases/tag/3.0.0.Final

And some artifacts have 3.0.0.Final published on maven central.

https://mvnrepository.com/artifact/io.quarkus/quarkus-arc

But not all of them, for example

https://mvnrepository.com/artifact/io.quarkus/quarkus-universe-bom

### Expected behavior

I am unable to use 3.0.0.Final as quarkus version in my app due to missing quarkus-universe-bom package (at least).

**Comment by gsmet** [comment]
No. It's not released. The core artifacts have been released but the full release and announcement will be done next Wednesday.
