### ISSUE TITLE
Upgrade the Jandex plugin with OpenRewrite

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32769]
See git@github.com:gsmet/quarkus-openfga-client.git for instance.

**Comment by mkouba** [comment]
> See [git@github.com](mailto:git@github.com):gsmet/quarkus-openfga-client.git for instance.

Did you mean the https://github.com/gsmet/quarkus-openfga-client/tree/quarkus-3 branch?

Also did you mean the [Jandex plugin](https://github.com/smallrye/jandex/tree/main/maven-plugin) or what exactly?

**Comment by gsmet** [comment]
Sorry, it was more of a mental note for me. It's about using OpenRewrite to update to the new GAV for the Jandex plugin. And I posted an example of project where it is used and I can test the upgrade.

**Comment by mkouba** [comment]
> Sorry, it was more of a mental note for me. It's about using OpenRewrite to update to the new GAV for the Jandex plugin. And I posted an example of project where it is used and I can test the upgrade.

No problem.
