### ISSUE TITLE
Quarkus Cache not working with multiple or list @CacheInvalidateAll annotations

### ISSUE THREAD

**Issue by krisgerhard** [quarkusio/quarkus#32786]
### Description

Currently doc says private methods can not be used and this is checked during build time.
As [documentation](https://jakarta.ee/specifications/interceptors/1.2/apidocs/javax/interceptor/aroundinvoke) states that ` The method must not be declared as abstract, final, or static.` - Quarkus could implement additional checks or at least clarify it in documentation.

Could save hours of debugging for quarkus-cache users :)

**Comment by krisgerhard** [comment]
To be accurate my issue was with Kotlin.

`
object CacheHelper {

  @CacheInvalidateAll.List(
    CacheInvalidateAll(cacheName = "cache-one"),
    CacheInvalidateAll(cacheName = "cache-two"),
  )
  fun invalidateCaches() {
  }
}
`

This did not invoke the interceptor.

**Comment by mkouba** [comment]
> To be accurate my issue was with Kotlin.
> 
> ```
> object CacheHelper {
> 
>   @CacheInvalidateAll.List(
>     CacheInvalidateAll(cacheName = "cache-one"),
>     CacheInvalidateAll(cacheName = "cache-two"),
>   )
>   fun invalidateCaches() {
>   }
> }
> ```
> 
> This did not invoke the interceptor.

Did you mean `class CacheHelper`? In any case, a bean class should be annotated with a bean defining annotation, e.g. a scope (`@ApplicationScoped`).

**Comment by krisgerhard** [comment]
No. I was using this - https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview.
When defining CacheHelper as class and bean this is working indeed, but it's also not static anymore.

**Comment by krisgerhard** [comment]
This starts to look like a bug. Adding @JvmStatic fixes intercepting, but not with @CacheInvalidateAll.**List**

This works 👇 
```
object CacheHelper {
  @CacheInvalidateAll(cacheName = "cache-one")
  @JvmStatic
  fun invalidateCalculationCaches() {
  }
}
```

**Comment by krisgerhard** [comment]
I've created a reproducer as KotlinResourceTest.kt 2/4 tests are failing.
https://github.com/krisgerhard/quarkus

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/pull/32805 should fix the problem.

**Comment by krisgerhard** [comment]
Looks promising.
![image](https://user-images.githubusercontent.com/11822359/233457680-3e4f0748-9c62-4225-9128-456325d513af.png)

**Comment by mkouba** [comment]
@krisgerhard do you agree to close this issue?

**Comment by krisgerhard** [comment]
Yes. Thank you for fixing it so quickly! 🤘

**Comment by krisgerhard** [comment]
@gsmet let me know if you'd want a PR to add these tests which I used to demonstrate the issue. 
https://github.com/quarkusio/quarkus/commit/34e391cdd8c8029fdc6d0046ed191a4b65e4106b
