### ISSUE TITLE
Flyway: support `outputQueryResults`

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#32791]
### Description

Flyway has the option [outputQueryResults](https://documentation.red-gate.com/fd/output-query-results-184127523.html) which controls whether flyway will print out the results of SELECTs in migrations. This option does not seem to be available using standard means (application.properties).

### Implementation ideas

Either forward the property, or add a way to forward yet unsupported properties to flyway, e.g. something like [`quarkus.hibernate-orm.unsupported-properties`](https://quarkus.io/guides/all-config#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key)

**Comment by Felk** [comment]
I just noticed that this option is a Flyway Teams feature. Do you support those in quarkus?

**Comment by geoand** [comment]
We do not

**Comment by geoand** [comment]
🙏🏼
