### ISSUE TITLE
Hibernate exception when using Uni.join.all

### ISSUE THREAD

**Issue by eamelink** [quarkusio/quarkus#32790]
### Describe the bug

There appears to be some issue with combining several Hibernate activities using `Uni.join.all`. 

The following code:

```
 return Uni.join().all(
                        repository.save(entity1),
                        repository.save(entity2),
                        repository.save(entity3),
                        repository.save(entity4))
                .andFailFast()
                .replaceWithVoid();
```

where `save()` is:

```
public Uni<Void> save(TestEntity entity) {
        return getSession().flatMap(session ->
                session.merge(entity).replaceWithVoid());
    }
```

causes an exception:

```
org.hibernate.HibernateException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState

	at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:28)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$fireMerge$23(ReactiveSessionImpl.java:1021)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
```

But it doesn't throw the exception when I add `.usingConcurrencyOf(1)` to the `Uni.join.all`.

### Expected behavior

No exception is expected.

### Actual behavior

A `org.hibernate.HibernateException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState` is observed

### How to Reproduce?

Here's a reproducer repository: https://github.com/eamelink/mutiny-join-hibernate-issue

It contains a single test that fails.

### Output of `uname -a` or `ver`

Darwin Eriks-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

### Quarkus version or git rev

3.0.0-CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by geoand** [comment]
If I recall correctly, `Uni.join.all` is not supported with Hibernate Reactive, correct @DavideD?
If so, would it be possible to have an explicit error message?

**Comment by DavideD** [comment]
That's correct, [one cannot use Uni.join.all](https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_sessions_and_vert_x_contexts) if the unis are using the same session (like I think it's happening in this case).

I don't think Hibernate Reactive can detect if the session is shared among unis.
That's actually an ORM message warning us that some operation didn't happen at the right time. But it might be a different operation depending on how the session is used.

But I think we can add some details to the error message to make it more user friendly

**Comment by geoand** [comment]
> But I think we can add some details to the error message to make it more user friendly

That would be awesome!

**Comment by geoand** [comment]
Closing this as an upstream issue

**Comment by Sanne** [comment]
I'm fine tracking the need for improvements in HR, but I'm not sure it can be done in HR.

It's also surprising that we don't detect this via the "duplicated context" tricks we had introduced in Quarkus; I'm wondering if the Uni.join.all pattern is inherently duplicating a context which we already had marked as "safe" but it should perhaps unmark it.

**Comment by The-Funk** [comment]
I've been running into this a lot lately. I don't remember where I read all of this, I know the docs @DavideD linked to above are pretty clear about it, but for anyone looking for a quick fix way to run a couple queries in parallel. The short version is:

1. You must use a Mutiny.SessionFactory and create a new session for each query you intend to join/combine.
2. You must use openSession() specifically, withTransaction() or withSession() will allow reuse of your session and you don't want this.
3. You must utilize the session, you cannot use Panache queries within the context of the chained method, you must directly utilize the session.
4. openSession() does not automatically close your session when you're done, so make sure to call close!

Here is a template for how I do it, I am not sure if this is good practice or not.

```java

@Inject
Mutiny.SessionFactory msf;

public Uni<CombinedThing> getMyCombinedThing(long id) {
    // session.createQuery() or session.find() will work below, you can use JPQL or Hibernate functions, just no Panache
    Uni<MyThing> myUniThing = msf.openSession().chain(session -> session.find(MyThing.class, id).eventually(session::close));
    
    // rinse and repeat with other queries then call Uni.combine().all().unis()
}
```

**Comment by Sanne** [comment]
For the record, I don't think it's a good idea to run multiple operations in different Sessions: that will imply necessarily that you're running them in separate transactions.

The correct approach, until we figure out how to improve on this, is to not run operations in parallel. I can't say it's a good idea to run operations in parallel for many other reasons as well.. at the DB level these will compete for resources, and if your problem is compound latency there's better solutions such as being more explicit about what needs to be loaded in a single roundtrip.

**Comment by Mulgish** [comment]
@DavideD @Sanne Is it acceptable to use `.usingConcurrencyOf(1)`?

It seems to have fixed the problem for me:
```java
Panache.withTransaction(() ->
                Uni.combine().all().unis(panacheUnis)
                    // Hibernate session can not be shared across threads https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_obtaining_a_reactive_session
                    .usingConcurrencyOf(1)
                    .discardItems()
            )
```

Please note that I am not sure if Mutiny will always use the same eventloop thread with a concurrency of 1. 
Perhaps @jponge or @cescoffier can confirm?

**Comment by DavideD** [comment]
`Uni.combine().all()` makes any promise related to the execution order of the unis. So, even if there is only one thread, there's no guarantee the the operations will run in the correct order.

It might work for simple or specific use cases, but it's not something you should rely on.

The main issue with the session is that the operations need to run in the right order. With blocking code, this means being careful it's not shared between threads. In reactive code, you also need to make sure it's not shared between unis that could run in unpredictable order.

**Comment by Mulgish** [comment]
@DavideD In my case I am not worried about the order of execution as I am using `Uni.combine().all()` to persist/update multiple entities in 1 go.

**Comment by The-Funk** [comment]
@Mulgish I just may use that. In my case I need to query a few disparate tables to return data for the frontend. I think this works for my case perfectly because otherwise I have to explicitly remove Panache from the equation or add awaits to do a few simple DB queries.

**Comment by miltonlm** [comment]
> I've been running into this a lot lately. I don't remember where I read all of this, I know the docs @DavideD linked to above are pretty clear about it, but for anyone looking for a quick fix way to run a couple queries in parallel. The short version is:
> 
> 1. You must use a Mutiny.SessionFactory and create a new session for each query you intend to join/combine.
> 2. You must use openSession() specifically, withTransaction() or withSession() will allow reuse of your session and you don't want this.
> 3. You must utilize the session, you cannot use Panache queries within the context of the chained method, you must directly utilize the session.
> 4. openSession() does not automatically close your session when you're done, so make sure to call close!
> 
> Here is a template for how I do it, I am not sure if this is good practice or not.
> 
> ```java
> @Inject
> Mutiny.SessionFactory msf;
> 
> public Uni<CombinedThing> getMyCombinedThing(long id) {
>     // session.createQuery() or session.find() will work below, you can use JPQL or Hibernate functions, just no Panache
>     Uni<MyThing> myUniThing = msf.openSession()
>                             .chain(session -> session.find(MyThing.class, id)
>                             .eventually(session::close));
>     
>     // rinse and repeat with other queries then call Uni.combine().all().unis()
> }
> ```

Thanks, it worked.
