### ISSUE TITLE
Use encrypted password for quarkus.mailer.password

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#3279]
**Description**
As of now, the password value for quarkus.mailer.password has to be written in the application.properties file as plain text. 
It would be interesting and more secure to be able to have the value encrypted in the properties file.

**Comment by gsmet** [comment]
We should probably have the option to use Vault for that. @vsevel ?

**Comment by vsevel** [comment]
hello @gsmet 
I see a few possible options:
 - support configuring a `credentials-provider` for the mailer extension. this requires a modification to the extension itself, similar to what I did for [agroal](https://github.com/quarkusio/quarkus/blob/master/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AbstractDataSourceProducer.java#L140-L155)
 - make progress on property indirection. that way you can use vault, without having to implement support for the `credentials-provider` https://github.com/quarkusio/quarkus/issues/3937
 - provide general support for encrypted values in the properties file. see [discussion](https://groups.google.com/d/msg/quarkus-dev/PJuHmYoNDFs/k4Q0PTnHBQAJ) and associated [issue](https://github.com/eclipse/microprofile-config/issues/451)

**Comment by vsevel** [comment]
@gsmet since https://github.com/quarkusio/quarkus/issues/3937 has been closed, may be all is needed at this point is some documentation saying that all you need to do is configure the vault extension, and use some property indirection on one of the mounted properties from the vault path:
```
...
# vault contains a key 'mail-password' in path 'secret/myapp/config'
quarkus.vault.secret-config-kv-path=myapp/config
quarkus.mailer.password=${mail-password}
```
