### ISSUE TITLE
Allow onMessage WebSocket handler to be invoked in a duplicated context

### ISSUE THREAD

**Issue by omarkad2** [quarkusio/quarkus#32801]
### Description

Not having a duplicated context can be limiting in a websocket `onMessage` handler (Context propagation not working properly for example https://github.com/quarkusio/quarkus/issues/32745, lack of tracing with OpenTelemetry)

**Comment by Feavy** [comment]
`Vertx.currentContext()` is null in `onMessage` handler, seems like it is not executed in a Vertx context at all.

**Comment by cescoffier** [comment]
Part of https://github.com/quarkusio/quarkus/issues/34188.
