### ISSUE TITLE
Reactive Postgres pipelining cannot be enabled 

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#32822]
### Describe the bug

Setting pipelining level of a postgres reactive configuration is not picked it up by Vert-x while creating the connection pool.

### Expected behavior

https://github.com/eclipse-vertx/vertx-sql-client/blob/a58127877a6fbb5b9ece9c58509637f699181826/vertx-pg-client/src/main/java/io/vertx/pgclient/spi/PgDriver.java#L48 requires https://github.com/quarkusio/quarkus/blob/85d9e172b57539c204b237464d1ba1e3a97c0600/extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/PgPoolRecorder.java#L94 to allocate a `PgPoolOptions` options type to make the pipelining settings available while allocating the connection pool.

**Comment by tsegismont** [comment]
@geoand thank you for the quick fix.

I think we need additional changes:

- users shouldn't have to create a `PgPoolCreator` object, setting `pipelining-limit` in configuration should be enough
-  Pg client is not the only one affected, MySQL and DB2 are affected too

I'm out of the office and will return on May 2. If can take care of this when I'm back.

**Comment by franz1981** [comment]
Thanks @tsegismont !

**Comment by tsegismont** [comment]
> I think we need additional changes:

I gave this a second thought, we need to revert https://github.com/quarkusio/quarkus/pull/32821

PgPoolOptions is an impl detail, it should not be exposed. It is created internally when the user wants a pooled client, not a connection pool (see https://vertx.io/docs/vertx-pg-client/java/#_pool_versus_pooled_client).

What Quarkus shall provide to users is a connection pool, not a pooled client. Pipelining for Quarkus users is possible, provided they acquire a connection and then submit several queries at once instead of waiting results between queries.

**Comment by geoand** [comment]
How would we provide a proper pool? What needs to be configured in Vertx?

**Comment by franz1981** [comment]
Yeah, and not only: at this point why we should expose pipelining config in Quarkus if we currently cannot make use of it?

**Comment by geoand** [comment]
> What Quarkus shall provide to users is a connection pool, not a pooled client. Pipelining for Quarkus users is possible, provided they acquire a connection and then submit several queries at once instead of waiting results between queries.

Care to elaborate on this a little further please?

**Comment by vietj** [comment]
@geoand Thomas refers to this https://vertx.io/docs/vertx-pg-client/java/#_pool_versus_pooled_client

**Comment by geoand** [comment]
Reading that, I don't really see how Quarkus users can use pipelining. @tsegismont I see you have assigned yourself to the issue, so I guess I'll just wait for the PR :)

**Comment by vietj** [comment]
@geoand  they can use the pool to acquire a connection, then do pipelining over this connection and then release the connection

**Comment by tsegismont** [comment]
> I see you have assigned yourself to the issue, so I guess I'll just wait for the PR :)

@geoand sorry if I wasn't clear enough in https://github.com/quarkusio/quarkus/issues/32822#issuecomment-1518689376

As @vietj explained later, pipelining can be used by:

- activating the feature in the config
- getting a connection from the pool and sending queries without waiting for results

No changes are needed, so I'm closing the issue

**Comment by geoand** [comment]
@tsegismont thanks.

I would like it if we could add some docs to Quarkus about how to do that.

**Comment by tsegismont** [comment]
Sounds good. I'll take care of this.

**Comment by geoand** [comment]
Thanks!
