### ISSUE TITLE
[arc/narayana-jta] observer notification during transaction phases

### ISSUE THREAD

**Issue by atzoum** [quarkusio/quarkus#3282]
**Description**
The CDI spec states that if a transaction is present, observer notification is possible during the following transaction phases:
- in progress
- before completion
- after completion
- after failure
- after success

Currently ARC ignores the `during` parameter of the `@Observes` annotation and notifies all observers.

**Implementation ideas**
ARC should detect the beginning of a transaction and register a TransactionSynchronization in the TransactionSynchronizationRegistry in order to be able to notify observers on the requested phase.

**Comment by mkouba** [comment]
This issue duplicates https://github.com/quarkusio/quarkus/issues/2224.
