### ISSUE TITLE
Prevent exposing of new DEV UI in remote development mode 

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#32836]
### Describe the bug

We use application in remote development mode with non-application path set to `/q`.  Old DEV UI is intentionally not available (please see https://github.com/quarkusio/quarkus/pull/15560), but when new DEV UI was enabled by default 
https://github.com/quarkusio/quarkus/commit/c20b4bbb9571d08001c170e878f20a81ed87eead, the test that verified it is not available was simply migrated to `/q/dev-v1` https://github.com/quarkusio/quarkus/blob/main/integration-tests/maven/src/test/java/io/quarkus/maven/it/RemoteDevMojoIT.java#L58 I can't find anything about this in migration guide [3.0](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#management-interface) or [3.1](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1) or in documentation https://quarkus.io/version/main/guides/maven-tooling#remote-development-mode. We detected behavior change after https://github.com/quarkusio/quarkus/pull/32673 got merged.

### Expected behavior

- inform me that I should use management interface with basic auth in order to secure new DEV UI
- highlight sensitive change in migration guide or documentation so that I can mention it when migrating my app

### Actual behavior

It is possible to access configuration page and read all my secrets and password and I'm unaware of danger.
I still can't access old DEV UI (`/q/dev-v1`), but I can access a new one.

### How to Reproduce?

Reproducer:

https://github.com/quarkusio/quarkus/blob/main/integration-tests/maven/src/test/java/io/quarkus/maven/it/RemoteDevMojoIT.java#L58 - change path to `/q/dev` or `/q/dev-ui`.

**Comment by gsmet** [comment]
That is a mistake. It shouldn't be available and we need to fix it.

Given you know where it is, could you fix it? We need it done by Monday evening to be included in 3.0.1.

**Comment by michalvavrik** [comment]
@gsmet I'll do it.
