### ISSUE TITLE
Speed up check for overriden methods in BeanDeployment

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#3285]
This issue is about the `MetodUtils.isOverriden` check. 
With the current approach it is easy to create a unique method identifier, a String, e.g. "<methodName>|<param 1 DotName>|<param 2 DotName>|...". With it the whole check if a method is overriden would be just:
```
if (!methods.add(method)) {
   continue;
}
```

Before PRing, check if it's indeed faster on the integration-test/main

**Comment by michalszynkiewicz** [comment]
I'd like to keep this issue

**Comment by geoand** [comment]
This seems to be way out of date now so I'll close it. Feel free to reopen if it's still an issue
