### ISSUE TITLE
Provide new API to programmatically create REST Client reactive

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#32856]
### Description

When creating a REST Client reactive programmatically, we use the Microprofile API `RestClientBuilder` as:

```java
var myClient = RestClientBuilder.newBuilder().baseUri(URI.create(uri)).build(Client.class);
```

However, having to use the Microprofile API limits the ability of Quarkus to programmatically configure some features, so this issue is about providing our Quarkus-specific RestClientBuilder API. 

At the moment, the additional options would include:
- verifyHost
- trustStore by truststore and password (it was requested in https://github.com/quarkusio/quarkus/pull/31891#issuecomment-1471591600)
- proxyUser
- proxyPassword
- nonProxyHosts

In next iterations, we could extend the API with:
- clientHeadersFactory (requested by https://github.com/quarkusio/quarkus/issues/32189)
- clientRequestFilter
- redirectHandler
- httpClientOptions
- ...

**Comment by geoand** [comment]
I'm +1 for this. 

@radcortez do you think this should be Quarkus specific or something we can have in Smallrye?

**Comment by radcortez** [comment]
SmallRye doesn't provide the REST Client implementation (it used to, but it was moved to RESTEasy).

My recommendation is to do it in RESTEasy.

**Comment by geoand** [comment]
That wouldn't allow us however to share it for RESTEasy Reactive and RESTEasy Classic.

It would definitely be easier at this point to have this be Quarkus specific and only have it apply to RESTEasy Reactive

**Comment by Sgitario** [comment]
> That wouldn't allow us however to share it for RESTEasy Reactive and RESTEasy Classic.
> 
> It would definitely be easier at this point to have this be Quarkus specific and only have it apply to RESTEasy Reactive

Note that we will keep supporting the existing Microprofile API. The idea is to provide a new Quarkus-specific API to extend the options to configure the REST Client Reactive.

**Comment by Sgitario** [comment]
> And do we want to exclude RESTEasy Classic?

We could provide another API for RESTEasy Classic, with the supported options for only RESTEasy Classic, but I would keep our efforts to improve the user experience on RESTEasy Reactive for now.

**Comment by geoand** [comment]
> but I would keep our efforts to improve the user experience on RESTEasy Reactive for now

+1

**Comment by usr000** [comment]
Also very interested in the functionality.
Some additional ideas for features:

1. Ability to reuse Quarkus out of the box instrumentation - e.g for tracing/context propagation
2. Ability for multiple clients to share the underlying resources - e.g. set max connection pool, and then when creating a client - supply this same connection pool.
