### ISSUE TITLE
`SimpleResourceInfo` parameter is null in a response filter when an exception is raised

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#32862]
Hi,
I am facing the following issue ...
I have a Quarkus RESTeasy Reactive based application and a filter which I use for logging and has the following declaration ...

```java
@ServerResponseFilter
    public void responseFilter(ContainerRequestContext requestContext, ContainerResponseContext responseContext, SimpleResourceInfo resourceInfo) {
```

when everything is fine and my invoked REST method returns a proper response, I get a correct (not null) `resourceInfo` which I use to get the called method for my purpose (so `resourceInfo.getMethodName()`).
But my REST method could even raise and exception which I handle with a custom exception mapper like this:

```java
@Provider
public class CompletionExceptionMapper implements ExceptionMapper<CompletionException>  {
    @Override
    public Response toResponse(CompletionException exception) {
        if (exception.getCause() instanceof RestBridgeException) {
            return RestUtils.buildResponseFromError(((RestBridgeException) exception.getCause()).getHttpBridgeError());
        } else {
            // re-throwing the CompletionException just allows the framework to handle the default way
            throw exception;
        }
    }
}
```

So when a specific `RestBridgeException` is raised I handle it by building a response.
It works fine but when the above filter is executed, the `resourceInfo` instance is null this time. Why?
What's the cause of having `resourceInfo` parameter to be ok on the "happy" path but null when the REST method raises an exception?

**Comment by geoand** [comment]
Hi,

What version of Quarkus are using? If it's not a recent version, does the same problem occur with latest version of Quarkus?

Moreover, it you can attach a sample project that demonstrates the issue, it will be a great help

**Comment by ppatierno** [comment]
I am using 2.15.3.Final.
Which latest version should I try? I would assume not 3.x because it could need some migration path?
Said that, the project is big (it is the refactoring we are doing on the Strimzi HTTP Kafka bridge to move from Vert.x to Quarkus). I will try to find time to write a reproducer. Meanwhile any possibile reasons this could happen?

**Comment by ppatierno** [comment]
The overall code is here, mostly in the `quarkus` package.
https://github.com/ppatierno/strimzi-kafka-bridge/tree/road-to-quarkus

**Comment by geoand** [comment]
> Which latest version should I try? I would assume not 3.x because it could need some migration path?

`2.16.6.Final` first, but Quarkus 3.0 we will available today or tomorrow most likely

**Comment by geoand** [comment]
I see, thanks

**Comment by ppatierno** [comment]
@geoand I was able to update to Quarkus 2.16.6 but the issue is still there :-(

**Comment by geoand** [comment]
I am pretty pressed for time, but I'll try to have a quick look tomorrow

**Comment by ppatierno** [comment]
@geoand really sorry to come back to this so late ... but here what you can do to reproduce the problem.

Be sure not having a Kafka cluster running. Not having it running will help you to reproduce the error condition in the bridge.

Start the bridge with something like `mvn quarkus:dev -Dquarkus.config.locations=/home/ppatiern/github/strimzi-kafka-bridge/config/application.properties` (adapt the path to the application.properties file on your local machine)

Run this cURL request against the bridge (which will be listening on localhost:8080 by default):

```shell
curl --location 'http://localhost:8080/topics' \
--header 'content-type: application/vnd.kafka.v2+json' \
--data ''
```

With this call the following things will happen:

1. The `RestLoggingFilter.requestFilter()` [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/RestLoggingFilter.java#L28) will be invoked and you can check that the `SimpleResourceInfo` parameter instance is ok. We can log the operation.
2. Then the `RestBridge.listTopics()` [REST method](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/RestBridge.java#L160) is called which calls `RestAdminBridgeEndpoint.listTopics()` [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/RestAdminBridgeEndpoint.java#L69).
3. Because Kafka is not running, the previous method will end with an exception (after 60 secs timeout), which is handled in order to throw a `RestBridgeException` [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/RestAdminBridgeEndpoint.java#L83).
4. The `CompletionExceptionMapper.toResponse()` [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/CompletionExceptionMapper.java#L25) is called to build a response to be sent to the client.
5. Finally the `RestLoggingFilter.responseFilter()` is called [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/quarkus/RestLoggingFilter.java#L40) but this time the `SimpleResourceInfo` parameter instance is null.

NOTE: I have done my investigation by running the bridge with `-Dsuspend` flag for a step by step (but it's not something I should teach you ;-)).

**Comment by geoand** [comment]
Thanks. Hopefully I'll be done with my catch up early next week and try have time to take a look

**Comment by ppatierno** [comment]
Thanks @geoand ;-)

**Comment by geoand** [comment]
YW!
