### ISSUE TITLE
Microprofile annotations not working on interface but working on controller class

### ISSUE THREAD

**Issue by Fa2bio** [quarkusio/quarkus#32887]
### Describe the bug

I'm trying to use quarkus-smallrye-openapi to generate a complete Swagger UI page, but I can't get it to work. When defining the annotations directly in the controller , customization of the /q/swagger-ui/#/ page is generated, but when removing the annotations from the controller to insert them into an interface, the annotations are ignored and the page /q/swagger -ui/#/ is generated using the default controller information.

### Expected behavior

I have the following:

the interface:

###
```xml
public interface ProdutoOpenApi {
	@Operation(description = "Lista todos os Produtos")
	@APIResponses({
                @APIResponse(responseCode = "200", description = "ok"),
		@APIResponse(responseCode = "204", description = "no_content")
	})
	List<Produto> findAllProdutos() ;
}
```
And its implementation:
 ###
```xml
@Path("/produtos")
@Tag(name = "Produto")
public class ProdutoController implements ProdutoOpenApi{
	@Inject
	private ProdutoRepository produtoRepository;
	@Override
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	public Response findAllProdutos() {
                List<Produto> todosProdutos = produtoRepository.listarProdutos();
                 if(todosProdutos.isEmpty()) return Response.status(Status.NO_CONTENT).build();
		return Response.ok(todosProdutos).build();
	}
}
```

### Actual behavior

![Captura de tela_2023-04-25_13-10-00](https://user-images.githubusercontent.com/41877566/234339472-e7a0345c-a497-45e2-94bb-9bd8c19acdc8.png)

### Output of `java -version`

openjdk 17.0.6 2023-01-17

### Quarkus version or git rev

Quarkus 2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

.mvnvm/apache-maven-3.8.8

**Comment by geoand** [comment]
Closing for lack of feedback
