### ISSUE TITLE
@PathParam does not encode "/" in classic rest client

### ISSUE THREAD

**Issue by justinasdauksa** [quarkusio/quarkus#32884]
### Describe the bug

It seems that `@PathParam` annotation in classic rest client encodes all special characters except `/`. Because of this, even if encoding is done before calling method which uses `@PathParam`, the end result will be invalid as encoding will happen once again on `%` character.

### Expected behavior

Encoding should be applied to either all special characters or none of them.

### Actual behavior

Encoding is not applied to `/`, but is applied to other special characters.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22621 NB-R9127TPH 3.3.4-341.x86_64 2022-05-13 22:10 UTC x86_64 Msys

### Output of `java -version`

17.0.5

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment]
A sample application would be useful in determining if this actually an issue or not.

**Comment by geoand** [comment]
Closing as we did not received feedback.

If a sample application does become available, feel free to comment and we can reopen the issue.
