### ISSUE TITLE
Keycloak DevServices fails on a Ryzen 3900X

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#32895]
### Describe the bug

Keycloak DevServices fails to start on my Ryzen 3900X with the following error:

```
[0.003s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.

```

My guess is that the large number of cores available means that KeyCloak is creating lots of threads, which use lots of memory, and the default 1gb memory limit is not enough.

### Quarkus version or git rev

2.16.6.Final

**Comment by geoand** [comment]
Interesting, I tried it on my Ryzen 5950X and it started as expected

**Comment by stuartwdouglas** [comment]
That is odd. I just tried outside of Keycloak and got the same error with`docker run quay.io/keycloak/keycloak:21.0.1`

**Comment by geoand** [comment]
Super weird...

**Comment by stuartwdouglas** [comment]
Turns out my docker version is just old.

**Comment by geoand** [comment]
Good to know!
