### ISSUE TITLE
Native image on windows fails "Windows AWT integration is not ready in native-image"

### ISSUE THREAD

**Issue by pelletier197** [quarkusio/quarkus#32924]
### Describe the bug

When trying to build a native image with Quarkus 3.0 on windows, using the Tika extension, Quarkus fails with an error indicating 

```
Caused by: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep$NativeImageInvokerInfo$Builder.build(NativeImageBuildStep.java:924)
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:253)
```

### Expected behavior

Expected behaviour is that native image compiles without any issue, as my application does not use AWT directly. Tika does use it however, but it seems to be a very small, limited portion of it.

### Actual behavior

Native image fails with the following exception

```
[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:286)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
    at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
    at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at java.base/java.lang.Thread.run(Thread.java:833)
    at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep$NativeImageInvokerInfo$Builder.build(NativeImageBuildStep.java:924)
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:253)
    ... 11 more
```

### How to Reproduce?

I've created a very minimal repository that allows to reproduce the issue. https://github.com/pelletier197/quarkus-tika-reproduction

Note that the exact command equivalents do succeed on linux, they must be executed on windows. In case this helps

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 16.05 GB / 31.68 GB
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1555]

### Output of `java -version`
openjdk version "17.0.7" 2023-04-18 
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) 
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### GraalVM version (if different from Java)
I am using Mandrel 22.3.2.0 - Java 17 version

### Quarkus version or git rev

Quarkus 3.0.0.CR2 (latest) as well as Quarkus Tika 2.0.0 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1.

**Comment by geoand** [comment]
Have you tested this with Quarkus `3.0.1.Final`?

**Comment by geoand** [comment]
cc @Karm

**Comment by pelletier197** [comment]
@Karm @geoand I just tried version `3.0.1.Final` and I have the same issue. I updated the reproduction repository with it. It's a big blocker for me, so I appreciate your help.

**Comment by geoand** [comment]
Thanks for checking.

It seems like @Karm has already assigned himself the issue.

**Comment by pelletier197** [comment]
Awesome! I looked a bit into the code that throws and I haven't really found a way to work around the issue. Let me know if you have an idea to work around it.

**Comment by jerboaa** [comment]
I don't think the AWT extension ever worked on Windows (tika needs that?)?

**Comment by pelletier197** [comment]
@jerboaa Tika does need some things in AWT. From what I found out, the PDF parser uses `BufferedImage`, `Color` and `Point` from AWT (for instance, maybe more). All those things should work on Windows because they are not UI related. 

For information, I've used Tika V1 successfully with Quarkus V1. Now needed to upgrade to Quarkus V3 for Tika V2 and I got stuck there. 

I think the check simply throws an error because there is an AWT dependency, but these dependencies should work on every platform and should be whitelisted. Would that make sense ?

**Comment by Karm** [comment]
Hello, 
* Tika needs AWT extension for docs processing, e.g, pdf
* if it could be modularized so as not the whole Tika needs awt, that is a question for https://github.com/quarkiverse/quarkus-tika IMHO
* you can build, test, run with Linux containers on Windows, the same as PrimeFaces do https://github.com/quarkiverse/quarkus-primefaces/pull/12
* Running with AWT extension natively on Windows, without Linux containers might be possible when AWT extension is ported to Windows, it is not possible now

**Comment by Karm** [comment]
Please reopen if needed. Perhaps AWT Windows port feature request might be in order.

**Comment by pelletier197** [comment]
@Karm The thing is that my executable must run on windows, not in Linux. This is not a server side executable, it will be installed on a real windows machine. Linux containers is not an option.

**Comment by Karm** [comment]
@pelletier197 I feel you. That is definitely not possible  with Quarkus AWT extension right now.
I created a Feature request to port AWT Extension to Windows: https://github.com/quarkusio/quarkus/issues/32993

**Comment by pelletier197** [comment]
@Karm In the meantime, is there really no way at all to have something work for windows ? I don't mind the dirty solutions, I just need something that will work :fearful:

**Comment by Karm** [comment]
@pelletier197 I don't have any workaroud for you. As soon as you touch image processing, you need AWT extension and that extension doesn't work on Windows in its current state. There is a lot of JNI bound C code and some of that just takes a different paths on Windows, some stuff is called differently etc. 

Basically this class: [AwtProcessor.java](https://github.com/quarkusio/quarkus/blob/main/extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java)
needs some `if windows then...else`. Not sure how many atm.

**Comment by pelletier197** [comment]
I have managed to find something that works for me. Inspired from https://github.com/oracle/graal/issues/4344#issuecomment-1047077621 .

1. I forked `quarkus-awt` and overrided it in my project to remove the windows check that stopped me from compiling
   - From there, I indeed got the `java.lang.UnsatisfiedLinkError: no awt in java.library.path` indicated by the exception

2. From there, I had to copy `jvm.dll`, `awt.dll` and `java.dll` that can be found in the `jvm/bin` folder at the same level as my executable. 

3. Those dependencies should then be automatically dynamically linked at runtime.  From there, I had some errors like 
```
Exception in thread "main" java.lang.NoSuchMethodError: java.awt.Toolkit.getDefaultToolkit()Ljava/awt/Toolkit;
```
All I had to do is modify my `jni-config.json` file to add everything that was missing. (For this specific error)

```json
[
{
  "name": "java.awt.Toolkit",
  "methods": [
    {"name": "getDefaultToolkit", "parameterTypes": []}
  ]
}
]
```

@Karm Think it would be great to not throw an error for this on windows. Just print a `WARN` should be good enough. Worse that happens is that you get a runtime error and will end up on this issue... Up to you at this point, i'm alright with my solution for now.

**Comment by Karm** [comment]
@pelletier197 I advise against doing this, because the worst that happens is that someone sends you a picture or a document that takes down your server, i.e. kills the process.

To make sure this is not possible, there is an [extensive test suite](https://github.com/quarkusio/quarkus/tree/main/integration-tests/awt/src) exercising various code paths that deliberately go places, like .tiff image with such and such color space or such and such compression etc.

So you are on a right track:
 - add everything that is missing (conditionally on Windows) for the test suite to pass
 - test with JDK 17 + GraalVM 22.x and 23-dev, the same for JDK 19 and JDK 20
 - take a look in Visual Studio/WinDBG what happens e.g. with jpeg libs init, grep JDK sources to look for calls made from C (JNI) to Java
 - [native agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) aids with some of that config, but it cannot be simply copied as it's both superfluous for Quarkus and also inadequate

For the danger of allowing someone to take down your server just by sending a picture with an unexpected format/compression I think it's pertinent to mark AWT as Error on Windows until the TS passes.
