### ISSUE TITLE
Quarkus-3.0.1 - Ignores Kubernetes Service account property

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#32933]
### Describe the bug

Just upgraded to quarkus **3.0.1.Final**. Kubernetes manifest generation ignores this property and it works in **2.16.5..Final**

`quarkus.kubernetes.service-account=quarkus-tester-sa`

### Expected behavior

Manifest generation should work like 2.16.5

### Actual behavior

Service account being ignored

### How to Reproduce?

Declare the above mentioned property in `application.properties` and do `./mvnw clean package` and notice that service account property is missing in the `kubernetes.yaml`

### Output of `uname -a` or `ver`

mac m1

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

./mvnw 3.8.2

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/32934 addresses this issue. Thanks for reporting!
