### ISSUE TITLE
Dev UI 2 - Infinite Page View

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkusio/quarkus#32931]
### Describe the bug

I encountered a bug while trying out the new Dev UI, more specifically, the GraphQL feature. Essentially, what happens is that when you click on the Quarkus logo in the GraphQL view, it opens the main page but in place of graphql UI.

![image](https://user-images.githubusercontent.com/60035933/234698953-25c19e4e-8840-411e-998b-b6be7450a9d9.png)

### Expected behavior

Probably should not be clickable or just return to the main page correctly.

### How to Reproduce?

Launch the GraphQL project and try using the Dev UI.

### Quarkus version or git rev

3.0.1.Final

**Comment by phillip-kruger** [comment]
Let's keep this open until fix is in quarkus
