### ISSUE TITLE
Quarkus 3 : mockito-inline don't work anymore after upgrade

### ISSUE THREAD

**Issue by fmarissel** [quarkusio/quarkus#32952]
### Describe the bug

After upgrading a project with : 
`curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio`

Junit tests containing static mocks don't work anymore.
Same issue with new project initialized with Quarkus 3.

> Caused by: java.lang.IllegalStateException: Cannot set up environment mocking: 
> The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks
> 
> Mockito's inline mock maker supports static mocks based on the Instrumentation API.
> You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
> Note that Mockito's inline mock maker is not supported on Android.. This may be a result of not having the right mockito-inline installed, or may be down to a Java internals change.
> 	at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.<clinit>(EnvironmentVariableMocker.java:45)
> 	... 66 more
> Caused by: org.mockito.exceptions.base.MockitoException: 
> The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks
> 
> Mockito's inline mock maker supports static mocks based on the Instrumentation API.
> You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
> Note that Mockito's inline mock maker is not supported on Android.
> 	at uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker.<clinit>(EnvironmentVariableMocker.java:29)
> 	... 66 more

I am using _uk.org.webcompere:system-stubs-core_ and _uk.org.webcompere:system-stubs-core_ to mock environment variables.

You can pull my repo to reproduce : 
https://github.com/fmarissel/quarkus3-mockito-inline

### How to Reproduce?

https://github.com/fmarissel/quarkus3-mockito-inline

### Output of `uname -a` or `ver`

Darwin FRL-HJ6N529V4W 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.1

**Comment by famod** [comment]
Please try removing the mockito-inline dependency from your project.
Quarkus 3.0.1 uses Mockito 5.3.0 and from that version on there is no mockito-inline anymore: https://redirect.github.com/mockito/mockito/issues/2877

**Comment by aduursma** [comment]
It looks like Quarkus 3.0.1 is not using the latest 5.3.1 Mockito version, but still Mockito version 5.2.0.

Could that perhaps have to do with the issue related to the mockito-inline dependency?

**Comment by famod** [comment]
> It looks like Quarkus 3.0.1 is not using the latest 5.3.1 Mockito version, but still Mockito version 5.2.0.

You are right. I was mislead by #32554 (which did not touch the BOM).

> Could that perhaps have to do with the issue related to the mockito-inline dependency?

This commit says it all: https://github.com/quarkusio/quarkus/commit/ed74dd79aa62b3b36141d12a65bfe6517c881478

I'll let @geoand take it from here.

**Comment by famod** [comment]
PS: You can work around this by adding the following exclusion to `quarkus-junit5-mockito`:
```
      <exclusions>
        <exclusion>
          <groupId>org.mockito</groupId>
          <artifactId>mockito-subclass</artifactId>
        </exclusion>
      </exclusions>
```
and then add a dependency to `mockito-core` to your project.
You might then run into #31251 though.

**Comment by famod** [comment]
@gsmet looks like @geoand is not around (?), so I'm asking you: Should we add something to the migration guide?
With Q3 it's not obvious:
1. how to use inline until Quarkus properly supports it (see my workaround above), which is particularly irritating given that Mockito normally uses inline by default
2. that you can run into situations like #31251 (once you've figured out how to use inline in the first place)

**Comment by geoand** [comment]
Yup, out for team meetings most of the week.

I'm gonna have a lot of catching up next week...

**Comment by gsmet** [comment]
@famod does upgrading to Mockito 5.3 somehow fix the issue? If so, maybe we should do it in 3.0.2.Final.

**Comment by famod** [comment]
@gsmet no, it doesn't.
Some might say updating to 5.3 makes it worse because there is no `mockito-inline` in Mockito 5.3+ anymore.
Personally I'd say it doesn't make much of a difference, given you'll have to fiddle around with exclusions and dependencies anyway (if you want inline behaviour).

**Comment by gsmet** [comment]
@famod yeah so please let's add something to the migration guide. And we should probably stay away from upgrading Mockito to 5.3 then.
And hopefully, we will be able to improve the situation a bit in upcoming micros.

**Comment by famod** [comment]
> @famod yeah so please let's add something to the migration guide.

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#fixation-of-the-mockito-subclass-mockmaker

> And we should probably stay away from upgrading Mockito to 5.3 then. And hopefully, we will be able to improve the situation a bit in upcoming micros.

TBH, I personally would bring the mockito deps in sync already in 3.0.2 (5.3.1 everywhere including the BOM) but as you suggested I'll remove the backport label from #33037.

**Comment by HerrDerb** [comment]
Should this be closed? 🙂
