### ISSUE TITLE
Quarkus 3 : 400 Bad Request on Post when used Kotlin data class with one field

### ISSUE THREAD

**Issue by serrg1994** [quarkusio/quarkus#32957]
### Describe the bug

I'm building a new service using Quarkus 3 and noticed when I have request body DTO class using Kotlin data class with one field I'm getting 400 Bad Request. If I add one more field it starts working fine

### How to Reproduce?

1 Create simple data class 
```kotlin 
data class TestTDO(val name: String)
```

2 Create controller with Post method that will receive this data class and return as response 

```kotlin 
import jakarta.ws.rs.POST
import jakarta.ws.rs.Path

@Path("/test")
class TestResource {

    @POST
    fun post(body: TestTDO): TestTDO {
        return body
    }
}
```

**Comment by geoand** [comment]
What sort of error are you getting?

Also what extensions are you using? Better yet, a sample application that behaves as you describe would be most helpful

**Comment by serrg1994** [comment]
@geoand I created a repository where you can reproduce it https://github.com/serrg1994/quarkus3-issue-reproducer

![image](https://user-images.githubusercontent.com/9201885/235147159-c3501a91-291d-4656-adc2-7ef86528e3f9.png)

After I added lastName field to GreetingDTO data class it started working fine
![image](https://user-images.githubusercontent.com/9201885/235147477-c680281f-f4be-44da-ab06-30cfd107ee25.png)

**Comment by serrg1994** [comment]
@geoand com.fasterxml.jackson.module:jackson-module-kotlin worked, Thanks

implementation("io.quarkus:quarkus-resteasy-reactive-kotlin-serialization") it's for kotlin serialization. Right ?

**Comment by geoand** [comment]
Yup
