### ISSUE TITLE
Tests may fail to start when workspace is not clean

### ISSUE THREAD

**Issue by hwellmann** [quarkusio/quarkus#3297]
**Describe the bug**
I'm using a JUnit 5 `@QuarkusTest` to test and debug my application in Eclipse. 

Sometimes, when re-running the test, it fails to start, complaining about ambiguous CDI dependencies.

**Expected behavior**
Running a test should be deterministic.

**Actual behavior**
Tests fail to start in a seemingly random manner.

**To Reproduce**
It seems this is caused by synthetic class files like `Foo_Bean.class` left lying around by a previous test run which was manually aborted via the IDE.

It looks like these classes get deleted by a shutdown task when the test terminates normally (even with a failure).

So maybe  it would help to do the same cleanup in a startup task.

**Environment (please complete the following information):**
 - Quarkus version or git rev:  0.19.1

**Comment by MaartenTutak** [comment]
I'm having this issue as well with IntelliJ IDEA.

**Comment by jaikiran** [comment]
Perhaps this PR might help https://github.com/quarkusio/quarkus/pull/4457?

**Comment by FroMage** [comment]
I just merged #4457 on master, can you try it out?

**Comment by FroMage** [comment]
Let's pretend it fixed the issue. Feel free to reopen if not.
