### ISSUE TITLE
Support JAX-RS Exception Mappers in REST Client Reactive

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#32974]
### Describe the bug

At the moment, we can provide custom exception mappers via:
- Either using the `@ClientExceptionMapper` annotation [[1](https://quarkus.io/guides/rest-client-reactive#using-clientexceptionmapper)]. 
- Or providing a custom `org.eclipse.microprofile.rest.client.ext.ResponseExceptionMapper` class [[2](https://quarkus.io/guides/rest-client-reactive#exception-handling)]

My proposal is also to support the standard JAX-RS Exception Mapper `jakarta.ws.rs.ext.ExceptionMapper` [[3](https://jakarta.ee/specifications/platform/9/apidocs/jakarta/ws/rs/ext/exceptionmapper)].

I see a couple of advantages:
- Users used to work `jakarta.ws.rs.ext.ExceptionMapper` instead of the Microprofile-based exception mapper.
- We can support exception mappers directly in the independent project REST Client Reactive (without needing to use a special handler in the Quarkus extension).

What do you think? @geoand

**Comment by geoand** [comment]
I don't really see how that would work as the server and client mappers do exactly the opposite thing.

Do you mind elaborating further?

**Comment by Sgitario** [comment]
> I don't really see how that would work as the server and client mappers do exactly the opposite thing.
> 
> Do you mind elaborating further?

Never mind. Not my day!

**Comment by geoand** [comment]
Happens to everyone 😎
