### ISSUE TITLE
Cover Mapstruct in Jakarta update

### ISSUE THREAD

**Issue by RvLhh** [quarkusio/quarkus#32983]
### Describe the bug

After running  _quarkus update --stream=3.0_ , my project build correctly, but when i run  _./mvnw compile quarkus:dev_ 
i got: 
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.957 s
[INFO] Finished at: 2023-04-28T11:51:05+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project datahub-api: Compilation failure: Compilation failure: 
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### Expected behavior
no errors

### How to Reproduce?
quarkus update --stream=3.0
./mvnw compile quarkus:dev

### Quarkus version or git rev

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.6

**Comment by tomperr** [comment]
Quarkus 3.0 moved from `javax.*` to `jakarta.*`, just import `jakarta.enterprise.context.ApplicationScoped` instead of `javax.enterprise.context.ApplicationScoped`
But still, their might be a bug with the auto update tool, as this change should have been handled according to the [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#automatic-update-tool)

**Comment by RvLhh** [comment]
yep, the build was successed with update tool but then i run ./mvnw compile quarkus:dev
i got errors

**Comment by lordpizzo** [comment]
I got the same error. I has been changed all imports. but when try to compile, got the error

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project sigat: Compilation failure: Compilation failure: 
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?
[ERROR] Couldn't find type javax.enterprise.context.ApplicationScoped. Are you missing a dependency on your classpath?

**Comment by lordpizzo** [comment]
Just complementing. I imagine it's some intellij or maven cache problem. but I haven't had time yet to see where the problem is.

**Comment by vaclavsvejcar** [comment]
> SOLVED - Just complementing. I imagine it's some intellij or maven cache problem. but I haven't had time yet to see where the problem is.
> 
> EDITED
> 
> if u use an mapper... just change @Mapper(componentModel = "cdi”) to @Mapper(componentModel = “jakarta”)
> 
> maybe u need to update your mapper code

This ⬆️ is the solution and it's really nasty issue, because from Maven build error it's really unclear what's wrong and fulltext search for `javax.enterprise.context.ApplicationScoped` doesn't help at all. Maybe it would be worth mentioning in migration guide?

**Comment by RvLhh** [comment]
thanks guys

**Comment by debu999** [comment]
Thanks **@vaclavsvejcar**. It indeed is a weird error. Phew what a catch.

**Comment by gsmet** [comment]
@vaclavsvejcar @lordpizzo could you tell us what exactly is `@Mapper`? Because from what I have read, I have no idea where it comes from.

**Comment by vaclavsvejcar** [comment]
> @vaclavsvejcar @lordpizzo could you tell us what exactly is `@Mapper`? Because from what I have read, I have no idea where it comes from.

Sure, it's part of [MapStruct](https://mapstruct.org), annotation processor for generating mappings between java classes.

**Comment by gsmet** [comment]
What's the FQCN of the annotation? I think we could automate it in our update tool with https://docs.openrewrite.org/recipes/java/addorupdateannotationattribute .
That way it will be automatically covered.

(And yes, we can also add a note in the migration guide)

**Comment by gsmet** [comment]
For now, I added a note in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#mapstruct . The OpenRewrite recipe is not flexible enough to only update the `@Mapper` annotation if the CDI component model is used so it could be counterproductive.

**Comment by Postremus** [comment]
@gsmet @vaclavsvejcar 

`jakarta-cdi` is the replacement for the old `cdi` componenent model.

With `@Mapper(componentModel = "cdi")` the generated mapper was annotated using `@javax.inject.ApplicationScope`. `jakarta-cdi` annotates the impl with `@jakarta.inject.ApplicationScope` - the direct replacement therefore.
This component model is only available since mapstruct 1.5.4.Final though.

With `@Mapper(componentModel = "jakarta"), the mapper is annotated using `@jakarta.inject.Singleton`. This was available since mapstruct 1.5.0.Final.


Alternativly, there is also `jsr330` which automaticly tries to figure out if javax or jakarta annotations should be generated based on what is available. Never used it though.
https://mapstruct.org/news/2022-03-20-mapstruct-1_5_0_RC1-is-out/#support-for-jakarta-dependency-injection

**Comment by piether** [comment]
@gsmet Could you please add a note that Mapstruct must be upgraded to at least 1.5.0.Final? This would have saved me some time today 😊

**Comment by gsmet** [comment]
A bit late but I added an additional note in the migration guide about updating to 1.5+.
