### ISSUE TITLE
Custom bean validator against standard constraint stopped working on Quarkus 3

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#32981]
### Describe the bug

I have this validator for `Duration` against the standard `javax.validation.constraints.Positive` constraint which works fine in Quarkus `2.16`

```java
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import javax.validation.constraints.Positive;
import java.time.Duration;

public class PositiveDurationValidator implements ConstraintValidator<Positive, Duration> {

    @Override
    public boolean isValid(Duration value, ConstraintValidatorContext context) {
        return value == null || value.compareTo(Duration.ZERO) > 0;
    }

}
```

After upgrading and migrating to Quarkus 3 it becomes:

```java
import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import jakarta.validation.constraints.Positive;

import java.time.Duration;

public class PositiveDurationValidator implements ConstraintValidator<Positive, Duration> {

    @Override
    public boolean isValid(Duration value, ConstraintValidatorContext context) {
        return value == null || value.compareTo(Duration.ZERO) > 0;
    }

}
```

and all tests fail with `jakarta.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'jakarta.validation.constraints.Positive' validating type 'java.time.Duration'`

Attaching reproducer, but the test is as follows:

```java
@QuarkusTest
final class PositiveDurationValidatorTest {

    @Inject
    Validator validator;

    @Test
    void valid() {
        validator.validate(new DurationTestObject());
    }

    class DurationTestObject {

        @Positive
        Duration duration = Duration.ZERO;

    }

}
```

### Expected behavior

Same as before the validator is detected, loaded and works.

### Actual behavior

The validator is not found.

### How to Reproduce?

[validation-quickstart.zip](https://github.com/quarkusio/quarkus/files/11352032/validation-quickstart.zip)

### Output of `uname -a` or `ver`

Darwin N4MFM06QYD 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

### Additional information

Validators for custom constraints work fine.

**Comment by xtaixe** [comment]
And just after all this work and hitting "Submit new issue" I see the `META-INF/services/javax.validation.ConstraintValidator` which wasn't renamed and I had completely forgotten about. Let me check that everything works and I'll close the issue.

**Comment by gsmet** [comment]
I will include this in our update tool.
