### ISSUE TITLE
Provide a way to customize quarkus' micrometer MeterRegistry/CompositeMeterRegistry 

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#32996]
### Description

We use `quarkus-micrometer-registry-prometheus` and it took us a long (very long) while to realize we had an issue with some of our metrics, because we do not get the micrometer errors via its MeterRegistry.

We found out about our issue by adding a `onMeterRegistrationFailed` listener to the quarkus' `CompositeMeterRegistry`.

To add that listener we had to modify and injecter MeterRegistry in a startup bean so it can be done early enough.

It would be nice to have a way to tweak the `CompositeMeterRegistry` out of the box so we can modify it's configuration.

**Comment by geoand** [comment]
#34573 is what I have in mind
