### ISSUE TITLE
new devui does not show experimental status

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33009]
### Describe the bug

old:
![2023-04-29_01-46-06](https://user-images.githubusercontent.com/54129/235270647-5af65111-61b8-4d2e-9788-449c71581986.png)

new:
![2023-04-29_01-46-22](https://user-images.githubusercontent.com/54129/235270649-234d044c-69ad-4947-862b-847ba378ecc9.png)

### Expected behavior

that experimental still shown

**Comment by melloware** [comment]
@phillip-kruger might be the perfect use for Badge component? https://vaadin.com/docs/latest/components/badge

**Comment by phillip-kruger** [comment]
I mean qui-badge (see https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qui/qui-badge.js)

**Comment by melloware** [comment]
Nice!
