### ISSUE TITLE
gRPC server reflection is broken in 3.0.1.Final

### ISSUE THREAD

**Issue by abuinitski** [quarkusio/quarkus#33015]
### Describe the bug

gRPC server reflection is not working in 3.0.1.Final.

### Expected behavior

Various tooling is able to introspect gRPC schema in a running Quarkus service.

### Actual behavior

Postman is not able to utilize server reflection, renders error: `Details: 12 UNIMPLEMENTED: Method not found: grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo`

### How to Reproduce?

1. Go to [Quarkus project generator](https://code.quarkus.io/), and generate a new project, with only gRPC extension enabled. No other defaults changed (assuming, starter code is enabled).
2. Run it with `./mvnw quarkus:dev`
3. Open Postman, create a new gRPC request on `localhost:9000`, attempt to bootstrap it with server reflection
4. Observe error: `Details: 12 UNIMPLEMENTED: Method not found: grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo`

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-Arseni.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/arseni/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_BY, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.3", arch: "x86_64", family: "mac"

### Additional information

1. Same steps render expected result when `2.16` version is selected in Quarkus project generator, instead of `3.0`.
2. Postman renders `UNKNOWN` error when `quarkus.grpc.server.use-separate-server` is set to `false`.

**Comment by cescoffier** [comment]
That's because we switch to the reflection service v1. v1alpha has been deprecated 2 years ago.

**Comment by abuinitski** [comment]
@cescoffier just to get it right - so this is not a Quarkus issue, but Postman issue?

**Comment by abuinitski** [comment]
I've tested with Insomnia and Kreya, unfortunately, both are also not capable to parse Quarkus 3 server reflection.

**Comment by cescoffier** [comment]
That's tricky. Exposing a service that was deprecated 2 years ago is not great. 

But looks like no one moved from it... supporting both might be doable, but annoying (code duplication).

**Comment by abuinitski** [comment]
@cescoffier could you recommend me what to mention (any links to discussions etc), so that I could at least help by creating issues in each of these tools?

**Comment by cescoffier** [comment]
You can create an umbrella issue listing the tools.

**Comment by c0va23** [comment]
We are faced with it issue into integration tests, which make some calls with reflection. Our integration tests are written in Python, and [latest version of Python gRPC reflection package](https://github.com/grpc/grpc/tree/v1.54.1/src/python/grpcio_reflection/grpc_reflection) does not support v1.

Temporarily, we fix it issue by rewriting path to reflection call on load-balancer level. Both APIs v1 and v1apha have equal structures.

Workaround with HAProxy:

```
backend rpc
    http-request replace-path /grpc\.reflection\.v1alpha.(.+) /grpc.reflection.v1.\1
```

**Comment by cescoffier** [comment]
I discussed with @alesj. We will support both reflection service. I will work on that soon (next week)

**Comment by cescoffier** [comment]
You can test with https://github.com/quarkusio/quarkus/pull/33162.
