### ISSUE TITLE
Error trailers are not propagated when using new Vert.x gRPC support

### ISSUE THREAD

**Issue by abuinitski** [quarkusio/quarkus#33024]
### Describe the bug

Java gRPC has a feature: when `RuntimeStatusException` is thrown with additional trailers, these trailers are propagated into the response. It was working in legacy mode with separate server for gRPC, but it is not working with `quarkus.grpc.server.use-separate-server=false`

### Expected behavior

When `io.grpc.StatusRuntimeException` is thrown with extra trailers from a gRPC server method, these trailers are serialized into the response.

### Actual behavior

No trailers are propagated.

### How to Reproduce?

1. Use quarkus project generator to generate a new project with only "quarkus-grpc" extension (assuming Starter Code is included, as per default)
2. Replace implementation of `HelloGrpcService#sayHello` with following:
```
    @Override
    public Uni<HelloReply> sayHello(HelloRequest request) {
        return Uni.createFrom().failure(() -> {
            ErrorInfo errorInfo = ErrorInfo.newBuilder()
                .setDomain("org.acme.test")
                .setReason("stub-error")
                .build();

            return StatusProto.toStatusRuntimeException(
                Status.newBuilder()
                    .setCode(io.grpc.Status.INTERNAL.getCode().value())
                    .setMessage("this is a test error")
                    .addDetails(Any.pack(errorInfo))
                    .build()
            );
        });
    }
```
3. Use Postman to trigger `HelloGrpc/sayHello` endpoint (default endpoint - `localhost:9000`), observe trailers are propagated, and error details are displayed.

response tab:
<img width="1059" alt="Screenshot 2023-04-30 at 23 33 42" src="https://user-images.githubusercontent.com/159410/235375050-199e4e84-3483-411e-9016-3c34cfe05b34.png">
trailers tab:
<img width="1062" alt="Screenshot 2023-04-30 at 23 34 11" src="https://user-images.githubusercontent.com/159410/235375068-fd618c6f-a8a8-4fc1-99ce-54ec9dc3366f.png">

4. Add line into main `application.properties`: `quarkus.grpc.server.use-separate-server=false`, restart application
5. Trigger endpoint again (this time updated default endpoint - `localhost:8080`)
6. Observe provided status (INTERNAL) is not resolved correctly, and no further error details are present, and `StatusProto` is not added to trailers.

response tab:
<img width="1069" alt="Screenshot 2023-04-30 at 23 28 46" src="https://user-images.githubusercontent.com/159410/235374848-13bab3e8-36f8-41e1-a254-949074b97497.png">
metadata tab:
<img width="807" alt="Screenshot 2023-04-30 at 23 29 16" src="https://user-images.githubusercontent.com/159410/235374873-9ba6712d-0233-4380-816e-3db79de0ebad.png">

### Output of `uname -a` or `ver`

Darwin 192.168.1.48 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final, 2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/arseni/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_BY, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.3", arch: "x86_64", family: "mac"

**Comment by alesj** [comment]
OK, here is a reproducer
* https://github.com/alesj/quarkus/tree/i33024

And I can see the diff as @abuinitski mentioned ...

"old" server: `trailers = Metadata(content-type=application/grpc,grpc-status-details-bin=CAMSFHRoaXMgaXMgYSB0ZXN0IGVycm9yGkcKKHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnJwYy5FcnJvckluZm8SGwoKc3R1Yi1lcnJvchINb3JnLmFjbWUudGVzdA)`

"new" server: `trailers = Metadata(content-type=application/grpc,grpc-accept-encoding=gzip,content-length=0)`

Something is eating "details" on the server side, @vietj / @cescoffier

**Comment by vietj** [comment]
Thanks @alesj here is a PR for 4.4.3 that will fix this issue https://github.com/eclipse-vertx/vertx-grpc/pull/52
