### ISSUE TITLE
Race between datasources and Camel start

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#3303]
Race condition as seen here:

https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=4827

Camel should probably be started via the CDI StartupEvent. I don't think we want a full MSC style dependency mechanism but we may want some kind of phased startup/shutdown to solve problems like this.

**Comment by gsmet** [comment]
@lburgazzoli I'm closing this one. Feel free to transfer it to the Camel issue tracker.
