### ISSUE TITLE
Cannot override values from additional config locations with env variable

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#33044]
### Describe the bug

When an application is started with `-Dquarkus.config.locations=application-xyz.properties`, the properties defined in this file have higher priority than existing environment variables.

If it is not a bug, is it possible then to set env vars to have a higher priority than the ones from the `-Dquarkus.config.locations=application-xyz.properties`

### How to Reproduce?

- unpack [config-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/11372344/config-quickstart.tar.gz)

- `./mvnw package -Dmaven.test.skip`
- `export GREETING_NAME=java`
- `java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar target/quarkus-app/*.jar&`
- `curl localhost:8080/greeting` -> hello java!

- stop the app: `fg` `ctrl+c`
- re-run with 
`java -Dquarkus.config.locations=application-xyz.properties -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar target/quarkus-app/*.jar&`
- `curl localhost:8080/greeting` -> xyz xyz! The expected output is still `xyz java!` as `echo $GREETING_NAME` has still value `java`

**Comment by ennishol** [comment]
I see. I'd understand if I would have passed `-Dgreeting.name` as `-D` flag. But in this case, I just specify an additional config file. And I thought it would have a lower priority as env vars (as it is with regular application.properties).

My use case is that the application is built once and deployed with different additional config files in Kubernetes and my intuition was that I could also overwrite any config with env var if needed, without re-deploying the app and modifying values in the additional properties file. But apparently, it is not possible.

I will probably do `greeting.name=${GREETING_NAME:xyz}` for each property in the additional file

**Comment by manovotn** [comment]
> My use case is that the application is built once and deployed with different additional config files in Kubernetes and my intuition was that I could also overwrite any config with env var if needed, without re-deploying the app and modifying values in the additional properties file. But apparently, it is not possible.

When deploying to Kubernetes (of which I know very little :)), perhaps you could define additional configuration via [`.env` file](https://quarkus.io/guides/config-reference#env-file)?
That way you could still use env vars and system properties for overrides.

> I will probably do greeting.name=${GREETING_NAME:xyz} for each property in the additional file

Yea, I suppose that works as well.
