### ISSUE TITLE
Outdated slf4j-jboss-logmanager is inconsistent with slf4j version

### ISSUE THREAD

**Issue by nielspardon** [quarkusio/quarkus#33045]
### Describe the bug

This [issue](https://github.com/quarkusio/quarkus/issues/31058) led to SLF4J being updated to version 2.0 which requires the slf4j-jboss-logmanager dependency to be also updated to 2.x for consistency. Otherwise you will end up with something like this where the outdated 1.7 bindings in slf4j-jboss-logmanager 1.2 are being detected but ignored:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:~/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.2.0.Final/slf4j-jboss-logmanager-1.2.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

### Quarkus version or git rev

2.16.6.Final

**Comment by gsmet** [comment]
SLF4J was only updated in 3.0 AFAICS. Quarkus 2.16 still points to 1.7.36 AFAICS.

Could you clarify how you end up with SLF4J 2.x in your Quarkus application?

**Comment by nielspardon** [comment]
Sorry, you're right. I need to check my dependencies. I think might be something else bringing it in.

**Comment by gsmet** [comment]
No worries :).
