### ISSUE TITLE
Quarkus Smallrye Fault Tolerence extension guide

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#3304]
**Description**
There is no guide for the Smallrye Fault Tolerence extension, despite the extension is ready to use.

**Implementation ideas**
A guide should exist and be linked from the main Quarkus website.

**Comment by loicmathieu** [comment]
I will provide a first guide while testing the features, this could be that basis of a more complete one if needed.

**Comment by gsmet** [comment]
Wait wait wait: we have one https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/fault-tolerance-guide.adoc

Maybe it’s just a link missing?

**Comment by kenfinnigan** [comment]
Ok, so looks like it's just a link not present in the guides index for website?

**Comment by gsmet** [comment]
Yeah it might just be an oversight. I’ll fix it as soon as I’m at the office.

**Comment by kenfinnigan** [comment]
I can take a look and see if I can fix, or break it! ;-)

**Comment by kenfinnigan** [comment]
Anyone have a view as to whether the guide fits under "Observability" or "Web"?

I'm torn

**Comment by machi1990** [comment]
> Anyone have a view as to whether the guide fits under "Observability" or "Web"?
> 

I'd say Observability.

**Comment by kenfinnigan** [comment]
https://github.com/quarkusio/quarkusio.github.io/pull/253

**Comment by loicmathieu** [comment]
Web

**Comment by kenfinnigan** [comment]
PR to add to site is merged, and it's now available under Web and Observability.

Covering both bases for now. We can adjust later if needed

**Comment by gsmet** [comment]
Thanks Ken and thanks Loïc for noticing.
