### ISSUE TITLE
Cannot inject opentelemetry Tracer in quarkus-3 app

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#33043]
### Describe the bug

Application is failing to start:
``` ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.opentelemetry.api.trace.Tracer and qualifiers [@Default]
	- java member: org.acme.opentelemetry.Config#tracer
```

### Expected behavior

app should work with ./mvnw quarkus:dev and via java -jar

### How to Reproduce?

Unpack and run ./mvnw quarkus:dev [opentelemetry-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/11372202/opentelemetry-quickstart.tar.gz)

**Comment by brunobat** [comment]
Will look into it

**Comment by brunobat** [comment]
Not sure what you are trying to do but you are missing the extension dependency:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-opentelemetry</artifactId>
    </dependency>
````

That's why you get that error.

**Comment by brunobat** [comment]
closing the issue

**Comment by ennishol** [comment]
Hi @brunobat , 
sorry for the wrong reproducer. Here is the right one:
[opentelemetry-quickstart.tar.gz](https://github.com/quarkusio/quarkus/files/11455505/opentelemetry-quickstart.tar.gz)

The problem happens only if you run it as jar:
```mvnd clean package -Dmaven.test.skip && java  -jar target/quarkus-app/*.jar```

with rest easy reactive it does work btw. Only classic rest easy has this problem
