### ISSUE TITLE
Create OIDC questionnaire 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#33059]
### Description

@sberyozkin will work on creating OIDC questionnaire asking the users to provide the feedback about OIDC - what works, what does not, about docs, with many specific questions. 

### Implementation ideas

Collect and analyse user input,  share the results on the dev forum, create a plan

CC @maxandersen @cescoffier @stuartwdouglas @FroMage @n1hility

**Comment by maxandersen** [comment]
@sberyozkin what is the end goal here ? is there things we believe the questionnaire will provide we don't know by now?

**Comment by geoand** [comment]
Is this still relevant?

**Comment by sberyozkin** [comment]
Hi Everyone, yes, sorry, it is relevant, I'll look into preparing it after PTO

**Comment by sberyozkin** [comment]
@cescoffier @maxandersen 

FYI, an initial version, https://docs.google.com/forms/d/1MOjnHO3QvVqn3_e0exMkxLZE_9Nm0dWcfjFzX9o2Ffk/printform
