### ISSUE TITLE
Document happy path Google auth and augmentation

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#33053]
### Description

Current OIDC tutorials and reference documents can be considered quite technical and some users might find it challenging to figure out how to setup OIDC.
This issue will continue with the idea of creating Getting Started Fast with Security series of tutorials, with the Basic and JPA tutorial being the first and only such a guide so far, with the plan always being to follow up with something for OIDC.
The next guide will show a Happy path Google authentication with 3 properties only

### Implementation ideas

- Show how to register Quarkus App in Google dashboard
- Show  a simple endpoint injecting ID token and using it to interact with the user
- Show a typical structure of ID token, explain how it differs from access token
- The endpoint will show how to logout using the injected OidcSession
- Security identity augmentor is introduced showing how to augment Google tokens for them to go through RBAC check
- Make it all work with 3 lines of config only

CC @maxandersen @cescoffier @stuartwdouglas @FroMage @n1hility

**Comment by maxandersen** [comment]
A low hanging fruit is to add keywords to existing docs so when you search for "GitHub", "Twitter" etc. It will show up.

**Comment by sberyozkin** [comment]
Hi @maxandersen Indeed, thanks for proposing it the first place, #33056

**Comment by faermanj** [comment]
This would be super nice, would be glad to help
Another suggestion would be to document where tokens are stored and how they are passed around.

**Comment by sberyozkin** [comment]
Hi @faermanj  

>Another suggestion would be to document where tokens are stored and how they are passed around.

It is not Google specific and we try to explain it here:

https://quarkus.io/guides/security-oidc-code-flow-authentication#token-state-manager
