### ISSUE TITLE
Duplicate native image system property under io.netty.noUnsafe conflicting values of true and true

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3305]
I see following exception when building (`mvn clean package`) project with neo4j+vertx extensions or neo4j+infinispan-client extensions.

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project getting-started: Failed to build a runnable JAR: Failed to build a runner jar: 
 Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.
 SubstrateSystemPropertiesBuildStep#writeNativeProps threw an exception: 
 java.lang.RuntimeException: Duplicate native image system property under
 io.netty.noUnsafe conflicting values of true and true
```

 * Does SubstrateSystemPropertiesBuildStep need to run when native mode is not targeted ?

 * https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateSystemPropertiesBuildStep.java#L18 could check both key and value and throw error only if values differ

 * Interesting observation: combination of vertx+infinispan-client doesn't fail the quarkus-maven-plugin:999-SNAPSHOT:build phase.

```
git grep io.netty.noUnsafe
extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java:        systemProperties.produce(new SystemPropertyBuildItem("io.netty.noUnsafe", "true"));
extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/NettyProcessor.java:                .addNativeImageSystemProperty("io.netty.noUnsafe", "true")
extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java:                .addNativeImageSystemProperty("io.netty.noUnsafe", "true")
integration-tests/hibernate-search-elasticsearch/src/test/resources/elasticsearch-maven-plugin/configuration/jvm.options:-Dio.netty.noUnsafe=true
```

When checking dependency tree of neo4j extension I didn't see netty there, maybe we can remove extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/NettyProcessor.java

Sample projects:
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
     -DprojectGroupId=org.acme \
     -DprojectArtifactId=getting-started \
     -DclassName="org.acme.quickstart.GreetingResource" \
     -Dpath="/hello" \
     -Dextensions=neo4j,vertx
```
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
     -DprojectGroupId=org.acme \
     -DprojectArtifactId=getting-started-x \
     -DclassName="org.acme.quickstart.GreetingResource" \
     -Dpath="/hello" \
     -Dextensions=neo4j,infinispan-client
```

**Comment by rsvoboda** [comment]
@michael-simons Just to be sure, NettyProcessor.java [1] under neo4j extension is intentional as netty is shaded in neo4j-java-driver - org/neo4j/driver/internal/shaded/io/netty ?

[1] https://github.com/quarkusio/quarkus/blob/master/extensions/neo4j/deployment/src/main/java/io/quarkus/neo4j/deployment/NettyProcessor.java

**Comment by michael-simons** [comment]
Yes, Netty is shaded in our driver, we need that processor. Without it, native compilation did work, but it doesn’t actually run. 

I have been trying around to keep all those non-Neo4j specific shims into our driver itself, but I’m not quite there yet. 

As the values actually don’t conflict, maybe merging them would do.

**Comment by michael-simons** [comment]
Having all those shims in the driver will make the extension much nicer and other projects will benefit as well.

**Comment by rsvoboda** [comment]
Created https://github.com/quarkusio/quarkus/pull/3310 to avoid throwing exception when values are the same.

Still would like to know if it's necessary to run SubstrateSystemPropertiesBuildStep when native mode is not targeted ... @stuartwdouglas can you shed some light on this ?

**Comment by stuartwdouglas** [comment]
At the moment when building a runnable jar we assume it may want to be turned into a native image at some point. This will change at some point, but it requires some architectural to move processing out of the maven plugin and into build steps.

**Comment by gsmet** [comment]
I think this issue can be closed.
