### ISSUE TITLE
quarkus-cxf

### ISSUE THREAD

**Issue by TomBrz** [quarkusio/quarkus#33071]
### Describe the bug

When generating classes in apache cxf from a wsdl file: 
apache cxf allows for the setting :  <autoNameResolution>true</autoNameResolution> In order to prevent problems such as the following: 
Parameter: header already exists for method ping but of type be.belgium.fsb.v1_00.SyncHeader instead of be.belgium.fsb.v1_00.SyncResponseHeader.  Use a JAXWS/JAXB binding customization to rename the parameter.

This is solved by adding autoNameResolution.

Is there a way to do this in quarkus and solve the issue?  I turned to other platforms before i opened the question here?

### Expected behavior

Parameter: header already exists for method ping but of type be.belgium.fsb.v1_00.SyncHeader instead of be.belgium.fsb.v1_00.SyncResponseHeader.  Use a JAXWS/JAXB binding customization to rename the parameter.
 should be resolved automatically using autNameresolution in apache cxf

### Actual behavior

there is no option to do it

### How to Reproduce?

take any wsdl containing a naming conflict and it will produce the error

### GraalVM version (if different from Java)

11

### Quarkus version or git rev

3.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven using the quarkus-cxf dependency

**Comment by famod** [comment]
Any specific reason why you didn't report it over here: https://github.com/quarkiverse/quarkus-cxf/issues ?
