### ISSUE TITLE
Oracle DB container image not booting

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#33081]
### Description

It seems the latest snapshot of `docker.io/gvenzl/oracle-free:23-slim-faststart` is not booting correctly.

This is urgent as it's causing our CI jobs to fail (e.g. #33070 ) ; I suspect end users of already released Quarkus tags are also affected via devservices.

cc/ @gvenzl 

### Implementation ideas

Switch to a specific "real tag" of the image, or try the non-faststart. Unfortunately neither will fix the experience of already released versions of Quarkus using the Oracle devservice.

**Comment by gvenzl** [comment]
Hey @Sanne,

The issues in the docker image have been resovled.

**Comment by Sanne** [comment]
Many thanks @gvenzl , indeed it's all good on our side now.

**Comment by gvenzl** [comment]
Great, glad to hear that!
