### ISSUE TITLE
quarkus-amazon-lambda-http extension doesn't use Java 17 runtime for SAM deployment

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#33080]
### Describe the bug

When the SAM template (JVM) is generated based on Java 17 project in Quarkus 3.0.1, the "sam.jvm.yaml" template still uses "Runtime: java11". It should be "Runtime: java17". Besides, there's no config to override this value programmatically. 

### Expected behavior

Runtime: java17

### Actual behavior

Runtime: java11

### How to Reproduce?

1. Add "quarkus-amazon-lambda-http" extension
2. Package the app via maven clean package
3. Check the target/sam.jvm.yaml file

### Output of `uname -a` or `ver`

Darwin doh-mac 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1

**Comment by patriot1burke** [comment]
generated sam files exist as a template.  Users can copy and modify to make it jdk 17.  Many customers/users still on JDK 11 so, the default stands here.

**Comment by maelstrom0x8** [comment]
hello @danieloh30 i'm facing this same issue. how were you able to resolve it?

**Comment by danieloh30** [comment]
@maelstrom0x8 You should update the sam file manually.

**Comment by maelstrom0x8** [comment]
alright. thanks
