### ISSUE TITLE
quarkus kubernetes creates job with unsupported `on spec.completionMode`

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#33085]
### Describe the bug

Project containing kubernetes and liquibase extensions creates kubernetes.yml deployment file. Liquibase migration scripts are run inside job defined in this file as following: 
```apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-mongodb-init
spec:
  completionMode: OnFailure
```
Kuberentes job specification does not define such completion mode: https://kubernetes.io/docs/concepts/workloads/controllers/job/#completion-mode

### Expected behavior

Deployment success

### Actual behavior

Deployment to kubernetes failed with 
`The Job "liquibase-mongodb-init" is invalid: spec.completionMode: Unsupported value: "OnFailure": supported values: "NonIndexed", "Indexed"`

### How to Reproduce?

1. create quarkus 3 project with kubernetes and  liquibase extensions
2. build
3. deploy generated kubernetes.yml

### Output of `uname -a` or `ver`

Linux palo-liska 6.1.0-1009-oem #9-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 09:59:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04) OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/33086 should fix this issue.
The only workaround I see for you is to provide your Job resource in `src/main/kubernetes/common.yml` with the correct value.
