### ISSUE TITLE
new Info Log since Q3 HHH000157: Lazy property fetching available for

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#33089]
### Describe the bug

I am currently preparing our migration to quarkus 3.
I noticed a new info log, which was not present in 2.16.6.

Can this please be removed?
This might be distracting in our bigger applications.

```
2023-05-03 10:13:50,149 INFO  [org.hib.tup.ent.EntityMetamodel] (JPA Startup Thread) HHH000157: Lazy property fetching available for: <packagename>.RuleActionExecutionLog

2023-05-03 10:13:50,172 INFO  [org.hib.tup.ent.EntityMetamodel] (JPA Startup Thread) HHH000157: Lazy property fetching available for: <packagename>.Rule
2023-05-03 10:13:50,206 INFO  [org.hib.tup.ent.EntityMetamodel] (JPA Startup Thread) HHH000157: Lazy property fetching available for: <packagename>.RuleExecutionLog
```

For example, the RuleExecutionLog entity has the following fields.

```
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "rule_execution_log_id_generator")
    @SequenceGenerator(name = "rule_execution_log_id_generator", schema = "webruleservice", sequenceName = "seq_rule_execution_log_id", allocationSize = 1, initialValue = 1000)
    @Column(name = "id")
    private Long id;

    @Convert(converter = YesNoConverter.class)
    @Column(name = "dry_run", nullable = false)
    private Boolean dryRun;

    @Column(name = "execution_date_time", nullable = false)
    private LocalDateTime executionDateTime;

    @Enumerated(EnumType.STRING)
    @Column(name = "rule_execution_state", nullable = false)
    private RuleExecutionState state;

    @JdbcTypeCode(java.sql.Types.VARCHAR)
    @Column(name = "correlation_id", nullable = false)
    private UUID correlationId;

    @Type(JsonNodeBinaryType.class)
    @Column(name = "data")
    @Basic(fetch = FetchType.LAZY)
    private JsonNode data;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_rule_id", nullable = false)
    private Rule rule;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "ruleExecutionLog")
    @BatchSize(size = 30)
    @OrderBy("actionType asc, fk_action_id asc")
    private List<RuleActionExecutionLog> ruleActionExecutionLogs;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "ruleExecutionLog")
    @BatchSize(size = 30)
    @OrderBy("key asc")
    private List<RuleExecutionLogSearchNumber> searchNumbers;
```

I believe this might be caused by the `@Basic(fetch = FetchType.LAZY)` annotation.

This corresponds to the info log in:

https://github.com/hibernate/hibernate-orm/blob/18ddbe15d6a8b83f3bae25183518640b8c615cc7/hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java#L397-L399

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk 17.0.4 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by yrodiere** [comment]
Hey @Postremus , I agree this does not seem normal. That being said, this particular log has been around for years (at least since 2015). Did you make any other change to your application that might explain this is being logged only now? E.g. added `fetch = LAZY` only when you migrated to Quarkus 3? Or reworked `JsonNodeBinaryType` somehow?

**Comment by yrodiere** [comment]
Created https://hibernate.atlassian.net/browse/HHH-16546 and https://github.com/hibernate/hibernate-orm/pull/6498 to address this upstream. I'll try to also add a log filter in Quarkus in the meantime.

> That being said, this particular log has been around for years (at least since 2015). Did you make any other change to your application that might explain this is being logged only now? E.g. added `fetch = LAZY` only when you migrated to Quarkus 3? Or reworked `JsonNodeBinaryType` somehow?

**Comment by Postremus** [comment]
@yrodiere 
The fields in `RuleActionExecutionLog` and `RuleExecutionLog` where already set to LAZY before migrating to Q3.

I noticed that in the `Rule` entity however, no field is set as LAZY. There is still this `@Type(JsonNodeBinaryType.class)` on one of the fields.

The `JsonNodeBinaryType` is part of hypersistence-utils:
```
        <dependency>
            <groupId>io.hypersistence</groupId>
            <artifactId>hypersistence-utils-hibernate-62</artifactId>
            <version>3.3.2</version>
        </dependency>
```

I set a breakpoint at org.hibernate.tuple.entity.EntityMetamodel Line 349.
Following properties are recognized as lazy, and cause this info log to be written:

```
[...]
class RuleActionExecutionLog {
[...]

    @Basic(fetch = FetchType.LAZY)
    @Lob
    @JavaType(ByteArrayJavaType.class)
    @Column(name = "message")
    private String message;

[...]
}

[...]
class Rule {
[...]

@OneToOne(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY, mappedBy = "rule")
    private Access access;

[...]
}

[...]
class RuleExecutionLog {
[...]

    @Type(JsonNodeBinaryType.class)
    @Column(name = "data")
    @Basic(fetch = FetchType.LAZY)
    private JsonNode data;

[...]
}
```

So yeah, this has nothing to do with the `JsonNodeBinaryType`.

**Comment by yrodiere** [comment]
Okay, thanks for the additional info @Postremus . As the properties involved seem to be expected to be lazy anyway, and we have a fix for the extra log, and I don't really have time to investigate further, I'll just assume the log appears now because the properties were not correctly detected as lazy in previous versions of Hibernate ORM.

I marked my PR as ready, let's see how that goes.
