### ISSUE TITLE
S3 connecstion

### ISSUE THREAD

**Issue by uriaahar** [quarkusio/quarkus#33099]
### Describe the bug

quarkus 3
after upgrading to quarkus 3 i cannot open a connection to my local S3.
i receive the following error:  
`software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.`

in my application.properties i define the host like that: `%dev.quarkus.s3.endpoint-override=http://localhost:4566
...
...`

do I need to set it somehow else?

**Comment by uriaahar** [comment]
there was not a single change but the quarkus version and the imports

**Comment by kjq** [comment]
I dont know if this is related or if you are using LocalStack but recently I had something really similar when I upgraded LocalStack.  First, the configuration needed to be changed and then there was an issue with the region I was using.

My endpoint override had to be changed to this: `endpoint-override: http://s3.localhost.localstack.cloud:4566`

https://github.com/quarkusio/quarkus/issues/32434

**Comment by geoand** [comment]
Is this still occuring?

**Comment by kjq** [comment]
No at the moment.  The fix was more on the LocalStack side because of how the regions were handled so when I changed the region in the properties it worked.

**Comment by geoand** [comment]
Thanks for the update @kjq

**Comment by geoand** [comment]
@kjq I am going to close this. If it's still a problem, please comment and we can reopen
