### ISSUE TITLE
Suspect memory leak in Quarkus Maven plugin

### ISSUE THREAD

**Issue by tristantarrant** [quarkusio/quarkus#33117]
### Describe the bug

We've been having OOM errors in the nightly Infinispan `main` build. Maven is being run with `-Xmx1g`.
While the OOM is not entirely attributable to the Quarkus Maven plugin, the heap dump we get contains two `QuarkusClassLoader` instances lingering even in later modules.
In particular, referring to https://ci.infinispan.org/job/Infinispan/job/main/939/ and the heap dump in https://ci.infinispan.org/job/Infinispan/job/main/939/artifact/java_pid4140227.hprof.xz we have:

* one with a retained heap of ~37MiB
* one with a retained heap of ~25MiB

We use the plugin in the `quarkus/cli` and `quarkus/server` modules and the error happens during the execution of the `assembly` plugin in the `distribution` module. 

Please use the following commit: https://github.com/infinispan/infinispan/commit/30f423efc9da23ca351a5a9c3b7983a90487ef33
as we have made some changes (increasing the heap to `-Xmx1200m`) in later commits and we're about to rearrange some modules.

Note: we are building with early-access builds of JDK 21 obtained from https://jdk.java.net/21/

### Expected behavior

We expect to not see instances of `QuarkusClassLoader` retained until the end of the build. While the OOM error is certainly not attributable exclusively to the Quarkus Maven plugin, it is a contributor to the issue.

### Actual behavior

The heap dump generated on OOME contains references to two `QuarkusClassLoader` instances.

### How to Reproduce?

The build is launched with the following command-line:

`MAVEN_OPTS="-Xmx1g -XX:+HeapDumpOnOutOfMemoryError" mvn clean install surefire-report:report pmd:cpd pmd:pmd spotbugs:spotbugs dependency-check:check -B -V -e -DskipTests -Pnative -Pdistribution`

Lowering the `Xmx` will make this fail with more certainty.

### Output of `uname -a` or `ver`

Linux rhos-infinispan-ci-3 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21-ea" 2023-09-19 OpenJDK Runtime Environment (build 21-ea+20-1677) OpenJDK 64-Bit Server VM (build 21-ea+20-1677, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584) Maven home: /opt/maven Java version: 21-ea, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "4.18.0-425.3.1.el8.x86_64", arch: "amd64", family: "unix"

### Additional information

https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/quarkus.20maven.20.20plugin.20classloader.20leak

**Comment by aloubyansky** [comment]
@tristantarrant could you try with `<extensions>true</extensions>` such as 
```
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
```
?

**Comment by aloubyansky** [comment]
Although no, it won't help.

**Comment by geoand** [comment]
> The heap dump generated on OOME contains references to two QuarkusClassLoader instances.

This does not actually indicate there is a problem as we need multiple ClassLoaders

**Comment by tristantarrant** [comment]
Sure, and I have no clue how Maven instantiates plugins per module. However, I'm a bit surprised that in a low memory situation those two classloaders have not been GCed before throwing an OOME

**Comment by geoand** [comment]
Are you still running into this

**Comment by tristantarrant** [comment]
We haven't seen it recently. We can close this

**Comment by geoand** [comment]
Thanks for the update
