### ISSUE TITLE
ArC removes indirect referenced beans

### ISSUE THREAD

**Issue by dkellenb** [quarkusio/quarkus#3311]
Quarkus in version 19.1 removes indirect referenced beans.

Lets have following scenario. You define an interface for your strategies and an services that depending on any argument, returns the appropriate strategy. These strategies are defined as beans. As these beans are not referenced directly with injections, but only through the interface, the are removed by ArC. The only way to fix it, is by setting `quarkus.arc.remove-unused-beans=false`

```java
public interface Exporter<T extends Exportable> {
    boolean accept(Class<T> clazz);
    String export(T object);
}

@ApplicationScoped
public class ApplicationExporter implements Exporter<Application> {
   boolean accept(Class<Application> clazz) { return clazz instanceof Application; }
   String export(Application application) {
     ...
   }
}

@ApplicationScoped
public class ExporterService {
  @Inject
  Instance<Exporter<? extends Exportable>> exporters; 
  public <T>Exporter<T> getExporter(Class<T> exporterClazz) {
    // BUG: exporters are empty!
    return StreamSupport.stream(exporters.spliterator(), false)
            .filter(exporter -> exporter.accept(exporterClazz))
            .findFirst().orElseThrow(...);
  }
}
```

If there is an `@Inject javax.enterprise.inject.Instance<T>` Quarkus (ArC) should keep all classes implementing `T`.

**Comment by geoand** [comment]
Although not a real solution, you can use `quarkus.arc.remove-unused-beans=framework` instead of the more invasive `quarkus.arc.remove-unused-beans=false`.

Furthermore you could also annotate your exporters with `@Unremovable`

**Comment by dkellenb** [comment]
Unfortunately we are not able to use `@Unremovable` or `=framework`, as these beans are from other libraries, but these note may be interesting for other readers.

**Comment by geoand** [comment]
I see

**Comment by gsmet** [comment]
@mkouba should we improve the removal algorithm to deal with this case?

**Comment by mkouba** [comment]
> If there is an @Inject javax.enterprise.inject.Instance<T> Quarkus (ArC) should keep all classes implementing T.

@dkellenb We do keep those beans but there's probably a bug with matching a parameterized type with a wildcard. I'm going to verify this particular use case.

**Comment by mkouba** [comment]
Yep, it's a bug. I'll send a PR with a fix shortly.

**Comment by dkellenb** [comment]
> Yep, it's a bug. I'll send a PR with a fix shortly.

Great, looking forward to the fix.

**Comment by mkouba** [comment]
@dkellenb Are you sure the injection point is `Instance<Exporter<? extends Exportable>>` and not something like `Instance<? extends Exporter<? extends Exportable>>`? It seems the bug I've found only occurs if the `Instance` param is wildcard or type variable... it should work if the param is a parameterized type though.
