### ISSUE TITLE
Not able to Quarkus native build

### ISSUE THREAD

**Issue by ShabiBaig** [quarkusio/quarkus#33129]
### Describe the bug

We are trying to consume SOAP api from AWS quarkus lambda function. during the native build we are getting following error:"Provider com.sun.xml.internal.ws.spi.ProviderImpl not found".  Can anyone help here

### Expected behavior

native build should be completed without any error

### Actual behavior

We are getting following error at the time native build
error:"Provider com.sun.xml.internal.ws.spi.ProviderImpl not found"

### How to Reproduce?

Quarkus native build for SOA integration

**Comment by geoand** [comment]
We don't have out of the box support for SOAP in Quarkus core, however you can have a look at the [CXF extension](https://quarkus.io/extensions/io.quarkiverse.cxf/quarkus-cxf)
