### ISSUE TITLE
Support Publisher<ByteBuffer>in RESTEasy reactive

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#33130]
### Description

I would like to be able to pipe a ` Publisher<ByteBuffer>` into a `RestResponse`.

Given a `Uni<Publisher<ByteBuffer>>`, I would like to be able to do 

```java
    @GET
    @Path("download/{objectKey}")
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Uni<RestResponse<Publisher<ByteBuffer>>> downloadFile(String objectKey) {
        return Uni.createFrom().item( (Publisher<ByteBuffer>)getPublisherByteBuffer())
                .onItem()
                .transform(publisher -> ResponseBuilder.ok( (Publisher<ByteBuffer>)publisher)
                        .header("Content-Disposition", "attachment;filename=" + objectKey)
                        .header("Content-Type", MediaType.APPLICATION_OCTET_STREAM).build());
    }
```

I tried to produce `Multi<byte[]>` with 

```java
    @GET
    @Path("download/{objectKey}")
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Uni<RestResponse<Multi<byte[]>>> downloadFile(String objectKey) {

        return Uni.createFrom().item( (Publisher<ByteBuffer>)getPublisherByteBuffer())
                .onItem()
                .transform(object -> ResponseBuilder.ok(Multi.createFrom().publisher(AdaptersToFlow.publisher(object))
                        .onItem().transform(this::getByteArray))
                        .header("Content-Disposition", "attachment;filename=" + objectKey)
                        .header("Content-Type", MediaType.APPLICATION_OCTET_STREAM).build());
    }
```

but got an exception :

```
 java.lang.ClassCastException: class io.smallrye.mutiny.operators.multi.MultiMapOp cannot be cast to class [B (io.smallrye.mutiny.operators.multi.MultiMapOp is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @290dbf45; [B is in module java.base of loader 'bootstrap')
        at org.jboss.resteasy.reactive.server.providers.serialisers.ServerByteArrayMessageBodyHandler.writeResponse(ServerByteArrayMessageBodyHandler.java:16)

```

**Comment by geoand** [comment]
Seems like a reasonable ask

**Comment by geoand** [comment]
But I do I need to think of how we can address the general idea of what is being attempted here - which is to to support streaming data but also setting headers

**Comment by geoand** [comment]
@FroMage @cescoffier what if we introduce some kind of custom `Multi` or `Publisher` that would allow users to first set HTTP headers and then use a `Multi<T>` for the data?

**Comment by cescoffier** [comment]
Yes, we can try this. If you implement Publisher, Mutiny will consider you unsafe and may introduce additional checks. If you extend AbstractMulti we can avoid these checks (but you must make sure your code is correct)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/33197 is what I have in mind. 

We still need to see about supporting `ByteBuffer` although I think that our support for  `io.vertx.core.buffer.Buffer`  should suffice.

**Comment by scrocquesel** [comment]
> #33197 is what I have in mind.
> 
> We still need to see about supporting `ByteBuffer` although I think that our support for `io.vertx.core.buffer.Buffer` should suffice.

@geoand  Thanks, got it working with 

```
    @GET
    @Path("download/{objectKey}")
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Multi<Buffer> downloadFile(String objectKey, RoutingContext ctx) {

        return Uni.createFrom()
                .completionStage(() -> s3.getObject(buildGetRequest(objectKey),
                        AsyncResponseTransformer.toPublisher()))
                .onItem()
                .transformToMulti(object -> RestMulti
                        .from(Multi.createFrom().safePublisher(AdaptersToFlow.publisher((Publisher<ByteBuffer>) object))
                                .map(this::getBuffer))
                        .header("Content-Disposition", "attachment;filename=" + objectKey)
                        .header("Content-Type", object.response().contentType()).build());
    }

    private Buffer getBuffer(ByteBuffer bytebuffer) {
        byte[] result = new byte[bytebuffer.remaining()];
        bytebuffer.get(result);
        return Buffer.buffer(result);
    }
```

Regarding ByteBuffer, I don't know if there is a better way to avoid copying the backed array of bytes back and forth.

**Comment by scrocquesel** [comment]
> > #33197 is what I have in mind.
> > We still need to see about supporting `ByteBuffer` although I think that our support for `io.vertx.core.buffer.Buffer` should suffice.
> 
> @geoand Thanks, got it working with
> 
> ```
>     @GET
>     @Path("download/{objectKey}")
>     @Produces(MediaType.APPLICATION_OCTET_STREAM)
>     public Multi<Buffer> downloadFile(String objectKey, RoutingContext ctx) {
> 
>         return Uni.createFrom()
>                 .completionStage(() -> s3.getObject(buildGetRequest(objectKey),
>                         AsyncResponseTransformer.toPublisher()))
>                 .onItem()
>                 .transformToMulti(object -> RestMulti
>                         .from(Multi.createFrom().safePublisher(AdaptersToFlow.publisher((Publisher<ByteBuffer>) object))
>                                 .map(this::getBuffer))
>                         .header("Content-Disposition", "attachment;filename=" + objectKey)
>                         .header("Content-Type", object.response().contentType()).build());
>     }
> 
>     private Buffer getBuffer(ByteBuffer bytebuffer) {
>         byte[] result = new byte[bytebuffer.remaining()];
>         bytebuffer.get(result);
>         return Buffer.buffer(result);
>     }
> ```
> 
> Regarding ByteBuffer, I don't know if there is a better way to avoid copying the backed array of bytes back and forth.

Speak a bit fast, actually custom headers are not produce in my case

**Comment by geoand** [comment]
Yeah, you need my PR for that

**Comment by scrocquesel** [comment]
I see the tests but headers are hard coded and they will usually come from a call to something else, thus from a Uni or something alike.

I also tried to do it without `transformToMulti` returning `Uni<RestMulti<ByteBuffer>>` but it return the toString value of the RestMulti instance.

**Comment by geoand** [comment]
In your case the header just comes from a method parameter, correct?

That should just work

**Comment by geoand** [comment]
RestMulti needs to be the return type, you can't mix it with Uni

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by geoand** [comment]
This request actually becomes very problematic in light of: https://github.com/quarkusio/quarkus/issues/22762 - i.e. when returning SSE events we need to return the initial HTTP frame ASAP, we can't wait for the actual response.

**Comment by scrocquesel** [comment]
> This request actually becomes very problematic in light of: https://github.com/quarkusio/quarkus/issues/22762 - i.e. when returning SSE events we need to return the initial HTTP frame ASAP, we can't wait for the actual response.
> 
> So I am wondering if we should limit the feature to non-SSE streamed responses...

That's what I thought at first. I was thinking of a dedicated server message serializer but I struggle to wire up the multi with the resteasy server response object. Trying to make things like the asyncfile support.

Will look at your second commit soon
