### ISSUE TITLE
WARN  [org.hib.met.int.MetadataContext] (JPA Startup Thread) HHH015011: Unable to locate static metamodel field :

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#33149]
### Describe the bug

I have the following field in my entity:

```
[...]
public class Rule {
    [...]
   @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "condition", columnDefinition = "json")
    private Predicate condition;
[..]
}
```

During quarkus startup I now get following warning:
```
2023-05-05 11:36:39,583 WARN  [org.hib.met.int.MetadataContext] (JPA Startup Thread) HHH015011: Unable to locate static metamodel field : com.activelogistics.wolf.webruleservice.rule.db.model.Rule_#condition; this may or may not indicate a problem with the static metamodel 
```

The metamodel is generated by following dependency:
```
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
            <scope>provided</scope>
        </dependency>
```

The field condition is indeed missing in the metamodel.

During the Q3 migration, I changed the field from this:
```
    @Type(type = "io.hypersistence.utils.hibernate.type.json.JsonNodeBinaryType")
        @Column(name = "condition", columnDefinition = "json")
    private Predicate condition;
```

And the condition was included in the metamodel.

Could it be, that `JdbcTypeCode` is not respected by the metamodel generator and therefore the field not included?

### How to Reproduce?

Reproducer: 
[orm-warning-json.zip](https://github.com/quarkusio/quarkus/files/11406031/orm-warning-json.zip)

1. mvn clean compile quarkus:dev
2. Warning is printed

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Sanne** [comment]
That could be - thanks for reporting! @beikov could you have a look (when you're back)?

**Comment by beikov** [comment]
Please create a [Hibernate JIRA](https://hibernate.atlassian.net) for this problem and we will look into it.

**Comment by yrodiere** [comment]
I'm going to close this issue as this looks like a bug in Hibernate ORM and there's no particular reason to think it's related to Quarkus.

If I'm wrong, feel free to explain and we'll consider reopening.

Otherwise, please report the problem on the [Hibernate ORM JIRA instance](https://hibernate.atlassian.net/) as suggested above.

**Comment by Postremus** [comment]
@beikov @yrodiere 
https://hibernate.atlassian.net/browse/HHH-16587
