### ISSUE TITLE
Allow configuring debug port in quarkus:dev without suspending JVM

### ISSUE THREAD

**Issue by devauxbr** [quarkusio/quarkus#3316]
Hello

**Description**
Here is my problem : I am often running 2 quarkus projects in maven quarkus:dev mode at the same time. So in order to start them both with the JVM debugger enabled, I need to change the default debug mode of at least one of them by specifying a port different that the default one (5005), for instance `-Ddebug=1234` to get the debugger listening on port 1234

It all works well, except that this `-Ddebug=1234` parameter also **forces the debugger to suspend** ([see here](https://github.com/quarkusio/quarkus/blob/767bff502cfa7f91c348097fc272e4c8fb699f33/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L203)) and prevents quarkus to start until any debugger is attached. 
I often find my self waiting several seconds, thinking that quarkus is slowly booting, before realizing that I need to toggle the debugger in my IDE to actually let quarkus start, and this happens to me several times a day...

=> To improve the developer experience, it would be awesome to allow configuring debug port in quarkus:dev **without suspending JVM**

**Implementation ideas**
I was thinking one possible solution would be to introduce another `@Parameter` in the DevMojo, for instance `suspend`, so that if the developer provides `-Dsuspend=false` (or maybe `-Dsuspend=n` to be consistent with the JVM argument) then we force this JVM argument to be of value `n` ([here](https://github.com/quarkusio/quarkus/blob/767bff502cfa7f91c348097fc272e4c8fb699f33/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L188), [here](https://github.com/quarkusio/quarkus/blob/767bff502cfa7f91c348097fc272e4c8fb699f33/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L192), [here](https://github.com/quarkusio/quarkus/blob/767bff502cfa7f91c348097fc272e4c8fb699f33/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L195) and [here](https://github.com/quarkusio/quarkus/blob/767bff502cfa7f91c348097fc272e4c8fb699f33/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L203)). Otherwise we stick to the existing behaviour ?

If you agree with my proposal I may submit a PR implementing this idea in the days to come

In any case thanks for the awesomeness of Quarkus ! I am converting all my colleagues at work to use it :rocket:

**Comment by jaikiran** [comment]
>I was thinking one possible solution would be to introduce another @Parameter in the DevMojo, for instance suspend, so that if the developer provides -Dsuspend=false (or maybe -Dsuspend=n to be consistent with the JVM argument) then we force this JVM argument to be of value n (here, here, here and here). Otherwise we stick to the existing behaviour ?

That's probably one way of doing it. But for what you are after:
> I need to change the default debug mode of at least one of them by specifying a port different that the default one (5005), for instance -Ddebug=1234 to get the debugger listening on port 1234

where  you just want to change the default port, I think it perhaps makes sense to just not suspend the VM by default and instead make it behave like what the default debug port behaves.

@stuartwdouglas, @gsmet, this feature was introduced here https://github.com/quarkusio/quarkus/pull/523. Do you guys think it would be OK, if we changed this implementation from:
```
<td><b>{port}</b></td><td>The JVM is started in debug mode and suspends until a debugger is attached to {port}</td>
```
to:
```
<td><b>{port}</b></td><td>The JVM is started in debug mode without suspending and will listen on {port}</td>
```

**Comment by stuartwdouglas** [comment]
I think this is ok. Most users probably don't want to suspend, as they generally won't want to debug the Quarkus boot process.

**Comment by geoand** [comment]
I am not a fan of it, but that is probably just because I am too used to using to actually debug Quarkus.
I agree with @stuartwdouglas that is makes sense for most users

**Comment by jaikiran** [comment]
@devauxbr, this has now been implemented and merged in https://github.com/quarkusio/quarkus/pull/4395.
@gsmet, I think we can close this one now.

**Comment by gsmet** [comment]
Yes, closing, thanks!

**Comment by devauxbr** [comment]
That's awesome! :tada: Thanks ! :pray:
