### ISSUE TITLE
Broken link in graphql client docs

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33176]
### Describe the bug

Graphql client guide at https://quarkus.io/guides/smallrye-graphql-client links to https://graphql.org/swapi-graphql which gives 404

**Comment by jmartisk** [comment]
Aw snap, I guess that's what we get for depending on a remote service that is not under our control. I don't know if they are planning to bring it back up. I've reported an issue to ask: https://github.com/graphql/swapi-graphql/issues/219
If it's not coming back, we either might have to host our own instance of the same app, or rewrite the quickstart and docs to use something else..

**Comment by jmartisk** [comment]
This is now resolved, the link is back online
