### ISSUE TITLE
JWT token test injection with claims

### ISSUE THREAD

**Issue by NinekoTheCat** [quarkusio/quarkus#33180]
### Description

the demonstration repository for this feature is:
https://github.com/NinekoTheCat/JWT-madness 
but basically instead of manually injecting claims using a claims producer you should be able to automatically do it using an annotation, I thought this was already in quarkus but here we are.

This is useful for testing JWT based authentication methods like OPID or Auth2.0 

### Implementation ideas

generate a claims producer at compile time so that it may be injected into the passed JWT token

**Comment by sberyozkin** [comment]
@NinekoTheCat 

>basically instead of manually injecting claims using a claims producer you should be able to automatically do it using an annotation, I thought this was already in quarkus but here we are.

It is already in Quarkus, it works right now for a typical case of `JsonWebToken` being injected, individual claims injection is not used that often, so it was not supported in the test module. 

It is worth clarifying it is only a unit test limitation

**Comment by NinekoTheCat** [comment]
Right, to clarify this is a feature request for claims injection working properly. as this while a neache case should be supported. This is a unit test issue.

**Comment by michalvavrik** [comment]
@sberyozkin what happens here is that @NinekoTheCat is using smallrye-jwt extension together with oidc extension and `io.quarkus.oidc.runtime.OidcJsonWebTokenProducer` has higher priority but `SecurityIdentity` produced by the `io.quarkus.test.security.jwt.JwtTestSecurityIdentityAugmentor` doesn't have `AccessTokenCredential` credential nor it is instance of `OidcJwtCallerPrincipal` so it returns `NullJsonWebToken`.

hey @NinekoTheCat:

When smallrye jwt extension is used as standalone `quarkus-test-security-jwt` then claim injection works.

when oidc extension is used as standalone with `quarkus-test-security-jwt` then it doesn't work for reasons explained above.

when oidc extension is used as standalone with `quarkus-test-security-oidc` and claims are set like this:

```
@OidcSecurity(claims = {
          @Claim(key = "sub", value = "test-id"),
          @Claim(key = "upn", value = "john")
  })
```
then claims injection works.

So I don't believe these 2 should be used together and I'm going to close this. Please shout if you disagree.
