### ISSUE TITLE
Reactive Messaging support kinesis client

### ISSUE THREAD

**Issue by rverma-nikiai** [quarkusio/quarkus#3319]
**Description**
In AWS environments kinesis can be considered as somewhat equivalent to Kafka.
Looking forward to developing a reactive kinesis client which can be used as a drop-in replacement for reactive Kafka client. 

Being new to quarkus, can you please outline some pointers required for this implementation. Is there a design doc for extension development? 

Thanks

**Comment by gsmet** [comment]
I think the first step would be to have a Reactive Messaging implementation, then we would include it in Quarkus.

/cc @cescoffier

**Comment by rverma-nikiai** [comment]
You meant here https://github.com/smallrye/smallrye-reactive-messaging, correct?

**Comment by gsmet** [comment]
Yes, exactly.

The best is to discuss this with @cescoffier to coordinate.

**Comment by gsmet** [comment]
Follow-up: https://github.com/smallrye/smallrye-reactive-messaging/issues/160

**Comment by gsmet** [comment]
I'm closing this one in favor of the SmallRye Reactive Messaging one. We can revisit once something has been done upstream.
