### ISSUE TITLE
Native build failed when using additional-build-args with container-build

### ISSUE THREAD

**Issue by shakhar** [quarkusio/quarkus#33192]
### Describe the bug

When we run a native build with the following command:
```
./gradlew apps:bianka-daemon:quarkusBuild \
  -Dquarkus.package.type=native \
  -Dquarkus.native.additional-build-args="--initialize-at-run-time=org.apache.kafka.common.security.authenticator.SaslClientAuthenticator\\,org.apache.http.impl.auth.NTLMEngineImpl\\,org.newsclub.net.unix.AFUNIXSocketAddress\\,org.newsclub.net.unix.AFUNIXDatagramSocket\\,org.newsclub.net.unix.NativeUnixSocket\\,org.newsclub.net.unix.AFUNIXSelector, -H:ResourceConfigurationFiles=../../META-INF/native-image/resource-config.json, -H:ReflectionConfigurationFiles=../../META-INF/native-image/reflect-config.json, -H:JNIConfigurationFiles=../../META-INF/native-image/jni-config.json, -H:SerializationConfigurationFiles=../../META-INF/native-image/serialization-config.json"
```
the build pass but then we got the following error on runtime:
```
 ./application: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./application)
```
According to [this](https://stackoverflow.com/questions/68633582/quarkus-native-container-missing-glibc-2-32), we tried to add `-Dquarkus.native.container-build=true` but it failed to build because all specified paths inside the `quarkus.native.additional-build-args` can't be found:
```
[1/7] Initializing...                                                                                    (0.0s @ 0.90GB)
Error: The serialization configuration file "/home/********/project/apps/bianka-daemon/build/bianka-daemon-0.1.0-native-image-source-jar/../../META-INF/native-image/serialization-config.json   -Dquarkus.native.container-build=true" does not exist.
```

### Expected behavior

The native build pass and the app runs successfully

### Actual behavior

The native build fails / The native build pass but than the app fails on runtime

### Output of `uname -a` or `ver`

Darwin ShakharArad 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### GraalVM version (if different from Java)

22.3.1

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.1 ------------------------------------------------------------  Build time:   2023-04-12 12:07:45 UTC Revision:     40ba32cde9d6daf2b92c39376d2758909dd6b813  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.6 (GraalVM Community 17.0.6+10-jvmci-22.3-b13) OS:           Mac OS X 13.2.1 aarch64

**Comment by geoand** [comment]
@zakkak can you help here please?

**Comment by zakkak** [comment]
@shakhar it looks like you are trying to build an application that uses 3rd party libraries not supported by Quarkus and requires some additional native image configuration.

The simpler way to make this work (given you already have the configuration in json files) is to include the configuration files in your application as resources by following https://quarkus.io/guides/writing-native-applications-tips#including-resources. In theory, if you include them under `META-INF/native-image` you won't even need to pass the `-H:SerializationConfigurationFiles` etc. options.

Alternatively you can also try the "Quarkus way":

For reflection and serialization you may instead use the [RegisterForReflection annotation](https://javadoc.io/doc/io.quarkus/quarkus-core/latest/io/quarkus/runtime/annotations/RegisterForReflection.html), also see https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

For JNI accesses, Proxies, Resources, etc. , you may create a new Quarkus extension and use the Build Items from [package io.quarkus.deployment.builditem.nativeimage](https://javadoc.io/doc/io.quarkus/quarkus-core-deployment/latest/io/quarkus/deployment/builditem/nativeimage/package-summary.html) 

HTH

**Comment by shakhar** [comment]
@zakkak Thanks! I tried the first suggestion and it indeed solved the path issue, but now when running with the `-Dquarkus.native.container-build=true` I think that it ignores the `--initialize-at-run-time` flag and I am getting the following error:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.newsclub.net.unix.AFUNIXSelector.select0(int) 
Parsing context:
   at org.newsclub.net.unix.AFUNIXSelector.select0(AFUNIXSelector.java:112)
   ....
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image runtime.A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.   To see how this object got instantiated use --trace-object-instantiation=java.nio.DirectByteBuffer. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at parsing org.newsclub.net.unix.AFUNIXSelector.consumeAllBytesAfterPoll(AFUNIXSelector.java:134)
        ...
```
