### ISSUE TITLE
A URI that includes a # does not send all URI information

### ISSUE THREAD

**Issue by zbowness** [quarkusio/quarkus#33204]
### Describe the bug

http://localserver/containers/container01#?mode=overwrite&signing=true

I am making a put request to my server using the URL above to create a container with id "container01#". Unfortunately, my server is not receiving the mode or signing variables needed to create the containers when a # is included in the URL. 

### Expected behavior

I was expecting my server to receive the mode and signing variables regardless of if a # is included in the URL. 

### Actual behavior

The mode and signing variables are not sent to my server and only "http://localserver/containers/container01" is received by the server. 

### Additional information

If this is a feature that I am unaware of, I would appreciate some input on how to work around this issue so that my server can receive the whole URL including the #.

**Comment by geoand** [comment]
Can you please attach a sample application that exhibits this problematic behavior?

**Comment by zbowness** [comment]
![URL_no_hastag](https://github.com/quarkusio/quarkus/assets/128477443/65c2d7fe-848a-4832-829d-e41703cc7e33)
![Put_request_no_hashtag_outline](https://github.com/quarkusio/quarkus/assets/128477443/a650c59e-417f-4995-ab61-88aed27a33eb)
![URL_hashtag](https://githu
![Put_request_hashtag_outline](https://github.com/quarkusio/quarkus/assets/128477443/0abf6161-3a11-4adf-a7d5-3a174be982c0)
b.com/quarkusio/quarkus/assets/128477443/ca740723-83a3-483a-be89-c499752d96f7)

In the above images the only change made was the # in the third image

**Comment by geoand** [comment]
Screenshots are super hard to work with. Can you attach a Quarkus project that exhibits this behavior?

**Comment by zbowness** [comment]
Here is a link to a repo with a simple Quarkus Project that exhibits this behavior: https://github.com/zbowness/SimpleQuarkusProject

**Comment by geoand** [comment]
This is expected as `#` see [this](https://en.wikipedia.org/wiki/URI_fragment).
