### ISSUE TITLE
Document Keycloak CORS support

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3320]
We have a lot of questions on KeyCloak CORS support (mostly by people trying to use the standard HTTP CORS support to no avail).

We need to have it properly documented so we can point people to it.

/cc @sebastienblanc @sberyozkin

**Comment by sebastienblanc** [comment]
few things we have to check : 
* In the guide, CORS is not needed (if you follow really the steps as described) so we can add information about CORS but it must not confuse the user trying out the guide/quickstart
* In the Quarkus Keycloak guide we point to this https://www.keycloak.org/docs/latest/securing_apps/index.html#_java_adapter_config which describes the CORS options but only using the JSON format. One possibility would be to fix the Keycloak documentation to add a `quarkus` section.

**Comment by gsmet** [comment]
So in a few guides, we are starting to have some `Going further` section.

The idea is to start populating this section and, when we have enough of them, separate them in separate pages.

So feel free to add this sort of section to the guide and we will reorganize later. At least we would have a pointer.
