### ISSUE TITLE
Error message for an invalid log format should state what is invalid

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#33218]
### Describe the bug

When I put this in application.properties:

```
quarkus.log.console.format=%d{HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %blue([%-15.15t]) %m%n

```

I get an error message that lacks information:

```
Caused by: java.lang.IllegalArgumentException: Encountered an unknown format character
        at org.jboss.logmanager.formatters.FormatStringParser.getSteps(FormatStringParser.java:204)
        at org.jboss.logmanager.formatters.PatternFormatter.setPattern(PatternFormatter.java:76)

```

### Expected behavior

Caused by: java.lang.IllegalArgumentException: Encountered an unknown format character (%b).

### Actual behavior

It doesn't tell me the invalid formatChar.

### Additional information

The problem is in org.jboss.logmanager.formatters.FormatStringParser:

```
                    default: {
                        throw new IllegalArgumentException("Encountered an unknown format character");
                    }
```
should be something like:

```
                    default: {
                        throw new IllegalArgumentException("Encountered an unknown format character (%" + formatChar  + ")");
                    }
```

**Comment by geoand** [comment]
cc @jamezp

**Comment by jamezp** [comment]
@dmlloyd and I are looking at log manager changes now. This seems like something we could do.

**Comment by dmlloyd** [comment]
Upstream issue: [LOGMGR-325](https://issues.redhat.com/projects/LOGMGR/issues/LOGMGR-325)

**Comment by gsmet** [comment]
This is an upstream issue, closing.
