### ISSUE TITLE
create-extension Maven mojo should allow creating from scratch

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#3321]
A followup of #2113 .

create-extension Maven mojo added via #3191 allows creating new extension modules inside an existing source tree. It should be enhanced to be able to create new extension projects from scratch.

cc @aloubyansky @Dufgui

**Comment by ppalaga** [comment]
I wonder if this "from scratch" scenario should create a source tree for hosting 

(a) a single extension 

or 

(b) multiple extensions (similar to [camel-quarkus](https://github.com/apache/camel-quarkus)). 

While I have quite a clear idea about (b), what would (a) look like?

Maybe something like this?

```
parent
 `- runtime
 `- deployment
 `- integration-tests
     `- it1
     `- it2
```

**Comment by aloubyansky** [comment]
I think it should be (a) and your sketch looks good to me.

**Comment by ppalaga** [comment]
Maybe it would be even enough to generate a single itest

```
parent
 `- runtime
 `- deployment
 `- integration-test
```

Do we already have a pom here in Quarkus that can serve as a parent of the `parent`?

**Comment by aloubyansky** [comment]
I would say, no, we don't. And it's a question what it should be if we want to offer one. I did prototype it in platform but currently I pushed one only for the applications. Partly because I was not sure whether it should live in the platform or on the core (or in both, e.g. platform extending the core). E.g. in case of Camel you are depending on the core and that makes good sense. However if your extension depended on other extensions that were not part of core, perhaps the platform would make sense in that case.

**Comment by ppalaga** [comment]
Implementation of the "from scratch" scenario would be easier if there was a parent to inherit from. I'd expect it to manage all necessary plugins and perhaps also define the `quarkus.version` property so that the external extension projects can use it to import the runtime and deployment BOMs. 

Quarkus core sounds like the most natural home for it. If the platform should aggregate the core plus some external extensions, then this grand parent pom cannot live there, because it would be a circular dep. I think external deps depending among each other will be rather rare, but with the grand parent pom in core still possible.

**Comment by ppalaga** [comment]
I am going to propose a minimalistic grand parent for third party extension projects here under quarkus unless somebody has a better idea?

**Comment by ppalaga** [comment]
@aloubyansky could you please have a look at the external-parent in https://github.com/quarkusio/quarkus/pull/3427 ?

**Comment by ppalaga** [comment]
Blocked by https://github.com/quarkusio/quarkus/issues/1594
