### ISSUE TITLE
Deeplinks to DEV UI extension page removes query params

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#33235]
### Describe the bug

For https://github.com/quarkusio/quarkus/issues/32031 I need that query params are sustained when I get redirected from external page to extension component page (here from OIDC provider where I log in and I return with state and tokens as query params).

### Expected behavior

Keep query params.

### Actual behavior

I go to `http://localhost:8080/q/dev-ui/io.quarkus.quarkus-oidc/keycloak-provider?state=whatever&etc` then I'm redirected to `http://localhost:8080/q/dev-ui/extensions?from=/q/dev-ui/io.quarkus.quarkus-oidc/keycloak-provider` and then I'm redirected to `http://localhost:8080/q/dev-ui/io.quarkus.quarkus-oidc/keycloak-provider`. That is `RouterController.addRoute` is not according my needs.

### How to Reproduce?

Use some component page as deeplink with query params.

### Additional information

I am in hurry so I'll try to fix it.

**Comment by phillip-kruger** [comment]
I fixed that in an upcoming PR.

**Comment by phillip-kruger** [comment]
We can maybe merge that PR then you can test on that?

**Comment by michalvavrik** [comment]
@phillip-kruger sure, whatever works for you

**Comment by phillip-kruger** [comment]
No let's merge this, I'll rebase
