### ISSUE TITLE
java.lang.UnsatisfiedLinkError with Tensorflow library

### ISSUE THREAD

**Issue by XciD** [quarkusio/quarkus#3324]
Hello,

I'm trying to create a `native-image` that contains the [Tensorflow Java API](https://www.tensorflow.org/install/lang_java)

I've started from the gettings started tutorial.
Just added:
```xml
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow</artifactId>
  <version>1.12.0</version>
</dependency>
```

And in a resources:
```java
@GET
@Produces(MediaType.TEXT_PLAIN)
public String hello() {
    return TensorFlow.version();
}
```

Building with `mvn verify -Pnative`
With `native-image` options:
```
<enableJni>true</enableJni>
 <additionalBuildArgs>-H:IncludeResources='.*/(dylib|so)$'</additionalBuildArgs>
```

And when I start the server, I've this Exception:
```
Caused by: java.lang.UnsatisfiedLinkError: org.tensorflow.TensorFlow.version()Ljava/lang/String; [symbol: Java_org_tensorflow_TensorFlow_version or Java_org_tensorflow_TensorFlow_version__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at org.tensorflow.TensorFlow.version(TensorFlow.java)
        at org.acme.quickstart.GreetingResource.hello(GreetingResource.java:29)

```

Just to be sure, I've made a small maven module with :

```java
public static void main(String[] args) {
    System.out.println(TensorFlow.version());
}
```
Made an uber jar and native image with:
native-image --no-server -jar target/getting-started-1.0-SNAPSHOT-runner.jar -H:+JNI --no-server -H:IncludeResources=''

Had an error from Tensorflow saying that it couldn't found the library.
I've copied `libtensorflow_jni.dylib` and `libtensorflow_framework.so` from the jar, put it on the same folder as the native-image and succed priting 1.12.

Maybe be this repository could help ?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/NativeLibrary.java#L48

Thanks

**Environment **
 - Output of `uname -a` or `ver`: Darwin laptop.localdomain 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.1.0 (build 25.212-b03-jvmci-20-b04, mixed mode)
 - Quarkus version or git rev: 0.19.1

**Comment by gsmet** [comment]
It would be interesting to have an extension wiring everything for the user.

Would you be interested in giving it a try?

**Comment by XciD** [comment]
Of course, but I may need some help :)

**Comment by emmanuelbernard** [comment]
CC @murphye as he did some work in the area
