### ISSUE TITLE
Elytron Security JDBC tests have become unstable

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#33257]
### Describe the bug

Security JDBC deployment tests have become unstable recently, I don't recall any security JDBC specific changes made at all for a long while though. They pass on my laptop, for now at least.

**Comment by sberyozkin** [comment]
#33245 from Georgios should get it fixed, I'll keep an eye on these tests for a couple of days and then close

**Comment by sberyozkin** [comment]
#33245 fixed it for sure, thanks @geoand

**Comment by geoand** [comment]
💪🏼
