### ISSUE TITLE
Index custom JAX-RS providers

### ISSUE THREAD

**Issue by matejvasek** [quarkusio/quarkus#33262]
### Description

When a developer uses custom JAX-RS message reader/writer they are not included in build index.
This may pose difficulty for creating native-image with custom providers -- Quarkus build is not registering endpoints for reflection.

Developer can workaround this by quarkus.index-dependency in application.properties, however it would be nice if this worked automatically.

**Comment by matejvasek** [comment]
I encountered this when trying to make RESTEasy reactive work with custom message writer/reader from CloudEvent SDK.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/33267 fixes the issue
