### ISSUE TITLE
Support https for quarkusIntTest against a running application

### ISSUE THREAD

**Issue by bonneval** [quarkusio/quarkus#33261]
### Description

TestHostLauncher.listensOnSsl() utilized by QuarkusIntegrationTestExtension always returns false (hardcoded).

AFAIK there is no way to test against a running application using HTTPS

### Implementation ideas

`quarkus.http.test-ssl-port` could be used as a criteria to decide if the running application is using HTTPS.

**Comment by geoand** [comment]
Delivered in #34507
