### ISSUE TITLE
Groups and Roles aren't in UserRepresentation with Keycloak Admin Client

### ISSUE THREAD

**Issue by kambei** [quarkusio/quarkus#33280]
### Describe the bug

With Quarkus `3.0.2.Final` and `io.quarkus:quarkus-keycloak-admin-client`

Groups and Roles aren't in the UserRepresentation:

```
log.info("groups: {}", keycloak.realm("test").users().list().stream().map(UserRepresentation::getGroups).collect(Collectors.toSet()));
log.info("roles: {}", keycloak.realm("test").users().list().stream().map(UserRepresentation::getRealmRoles).collect(Collectors.toSet()));
```

### Expected behavior

2023-05-10 19:36:27,555 INFO  [ser.ImportService] (executor-thread-1) groups: [LIST of GROUPS]
2023-05-10 19:36:27,585 INFO  [ser.ImportService] (executor-thread-1) roles: [LIST of ROLES]

### Actual behavior

2023-05-10 19:36:27,555 INFO  [ser.ImportService] (executor-thread-1) groups: [null]
2023-05-10 19:36:27,585 INFO  [ser.ImportService] (executor-thread-1) roles: [null]

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.0.2 ------------------------------------------------------------  Build time:   2023-03-03 16:41:37 UTC Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d  Kotlin:       1.8.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.6 (Oracle Corporation 17.0.6+9-LTS-190) OS:           Linux 5.15.0-71-generic amd64

**Comment by sberyozkin** [comment]
Hi @kambei 

Unfortunately, it is out of Quarkus control, and currently the only way to export users and roles is to follow a Keycloak specific process on the Keycloak server side.

Please follow #30097, I did not have time to discuss it further with the Keycloak team yet, only briefly mentioned it to Pedro Igor Silva.

If you'd like to help then please open a Keycloak Discussion and ask if the Keycloak team can consider supporting exporting this information via its Admin endpoint (CC myself, @pedroigor, @geoand who proposed an idea how to make it work )

**Comment by sberyozkin** [comment]
@kambei Hope you are OK with me closing this issue too fast :-), we have a high volume of various reports so if we can see it is not a valid issue, it is better to close such issues asap.

**Comment by sberyozkin** [comment]
Hey @kambei I've just opened https://github.com/keycloak/keycloak/issues/20294

**Comment by kambei** [comment]
@sberyozkin no problem. :)
Thanks.
