### ISSUE TITLE
Quarkus Platform Repository

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#3329]
The Quarkus Platform will be aggregating extensions from Quarkus Core and extensions developed externally, including their testsuites. The platform build process will be generating the BOMs and parent POMs for applications as well as the catalog of extensions as a JSON file for Quarkus tooling (such as the starter).

proposed action-plan made on 2019-09-25 (made by @aloubyansky  and @maxandersen)
  - [x] create a separate git repo in quarkusio
  - [x] release a handdrafted platform bom referencing camel with quarkus bom that is known to work
  - [x] create a separate `quarkus-platform-tools` - move project create/manipulation tools away from core and keep build/dev-mode/native-image where they are  
   - [x] release quarkus platform tools 
   - [x] make quarkus platform tools capable of reading online metadata to get latest versions to default to (if offline we'll fallback to what was there when platform tools release)

**Comment by emmanuelbernard** [comment]
Other todos:

- define a extensions.yml or otherwise to be consumed by code.quarkus.io and our maven tooling to know the list of extensions
    - for example override a label as needed, set a category etc
- create a process to generate and manually add the settings specific to extensions.yml
- define the notion of beta or experimental for an extension (label?)
- define the notion of a preferred extension (label). I think we had a better name but we need that

**Comment by aloubyansky** [comment]
Here is an example how the extensions.json can be generated from a BOM https://github.com/aloubyansky/quarkus/commit/c80e58e315b248af0b034fcbc1016bda1893eda2

**Comment by emmanuelbernard** [comment]
Right but this one is the per extension.json file. I'm also thinking of the extensions aggregating file.

**Comment by emmanuelbernard** [comment]
And generally how people will enlist their extension for the platform

**Comment by aloubyansky** [comment]
No, that's actually aggregating all the extensions from the bom.

**Comment by gastaldi** [comment]
Looks like this issue can be closed now?

**Comment by aloubyansky** [comment]
There are a couple of points from Emmanuel's list we could use to create a couple of issues. Otherwise, yes, can be closed, imo.

**Comment by aloubyansky** [comment]
Ok, I created #4771 and #4772
