### ISSUE TITLE
SQL injection vulnerability with Panache persist

### ISSUE THREAD

**Issue by games1232002** [quarkusio/quarkus#33291]
I am not sure if I'm missing out something, but I noticed that Panache seems to not check for SQL vulnerability before persisting data into SQL databases. For example consider the following code:

```
@Entity
@Data
@Table(name = "SomeTable")
@AllArgsConstructor
public class SomeEntity extends PanacheEntityBase {
    @Id
    public Integer rowid
    public String colNameA
    public String colNameB
}


public void static main (String[] args) {
     SomeEntity entity = new SomeEntity (1, ";DROP TABLE B", "1=1")
     entity.persist()
}
```

The persist will execute without errors but note that the parameters for `entity` object pose risks of SQL injection. If we check the database we will see that all the values are being entered into a new row in the corresponding table "as-is". In otherwords, the semicolon and sort of stuff are all persisted into the SQL table.

I cant seem to find any information if Panache does any of input sanitization before inserting into SQL table. So I guess if it's not a bug, can someone explain how Panache minimize risk of SQL injection.

Thank you.

**Comment by Ladicek** [comment]
>  If we check the database we will see that all the values are being entered into a new row in the corresponding table "as-is". In otherwords, the semicolon and sort of stuff are all persisted into the SQL table.

That is exactly what should happen. `";DROP TABLE B"` is as good a string as `"Little Bobby Tables"` and there's no reason why it shouldn't be persisted into the database.

When you say "Panache", I take it you mean Hibernate ORM with Panache -- and while I'm no expert at Hibernate ORM, I'm fairly certain it uses prepared statements and parameters (or something similar), where the SQL command reads e.g. `INSERT INTO SomeTable (rowid, colNameA, colNameB) VALUES (?, ?, ?)` and the values are passed outside of the command itself.

**Comment by games1232002** [comment]
@gsmet Can you confirm if Panache is using some kind of prepared statements or parameterized query that will minimize risk of injection attack? I cannot find it in the source code...
