### ISSUE TITLE
Restart API on each test

### ISSUE THREAD

**Issue by XciD** [quarkusio/quarkus#3330]
**Description**
I've an API that load files at start up that modify the behavior of my endpoint.

I've written two test, but only one works because the API stays running.

Could we have any option that says that we need to reload the API for a Test ?

Thank you

**Comment by geoand** [comment]
Relates to #2866

**Comment by XciD** [comment]
How can I help with this ?

**Comment by geoand** [comment]
@XciD thanks for volunteering! For the time being, we need to see how this will play out in #2866. Once that is figured out, we should have a clearer path to move this ahead

**Comment by geoand** [comment]
We need to see how the command line mode things are going to play out before moving on this

**Comment by geoand** [comment]
You can now do various things to address this:

* Use `@QuarkusTestProfile`: https://quarkus.io/guides/getting-started-testing#testing_different_profiles
* Use `QuarkusTest*Callback`: https://quarkus.io/guides/getting-started-testing#enrichment-via-quarkustestcallback
