### ISSUE TITLE
Support @ObservesAsync run after event fire transactional committed

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#33309]
### Description

```java
@Transactional
public void update(UpdateStockCommand command) {
     var entity = new AEntity(); 
     repository.persist(entity)
    event.fireAsync(new AEvent(entity.getId()));    <----- fire event in here
   //some business code
}
```

```java
public void onEvent(@ObservesAsync AEvent event){
   repository.findById(event.getId());      <----- here maybe can not found entity when fire transactional not committed
}
```

### Implementation ideas

Add some annotation mark @ObservesAsync like @Observes but async, like flow code

```java
public void onEvent(@ObservesAsync @TransactionPhase(during = AFTER_SUCCESS) AEvent event) {
}
```

**Comment by pipinet** [comment]
@mkouba onEvent(@Observes(during=AFTER_SUCCESS) AEvent event) { ... } is not asnyc,  will block fire thread until event handler completed.

**Comment by pipinet** [comment]
@mkouba if support onEvent(@observes(during=AFTER_SUCCESS) AEvent event) { ... } in async, will better that @ObservesAsync.

cause most of the producer's business has both synchronous consumers and asynchronous consumers，according to the concept of jakarta, such a business requires fire sync and async at the same time, which is very unfriendly

**Comment by mkouba** [comment]
> @mkouba onEvent(@observes(during=AFTER_SUCCESS) AEvent event) { ... } is not asnyc, will block until event handler completed in event fire thread .

Not really, a tx observer results in a `jakarta.transaction.Synchronization` registered for the current transaction. So the notification of the observer does not block the thread that fired the event.

**Comment by pipinet** [comment]
> 

graphql response will until both completed in observer and fire thread  that i tested.

**Comment by mkouba** [comment]
> > 
> 
> graphql response will until both completed in observer and fire thread that i tested.

Well, we'll need a reproducer app...

**Comment by pipinet** [comment]
> 

ok, thanks, i will reproduce soon.

**Comment by Ladicek** [comment]
If I understand correctly, @pipinet's objection here is that a transactional observer _will_ block the thread calling the observer -- it's just that it doesn't block when the event is fired, it's later.

**Comment by mkouba** [comment]
> If I understand correctly, @pipinet's objection here is that a transactional observer _will_ block the thread calling the observer -- it's just that it doesn't block when the event is fired, it's later.

Yes, the truth is that you can't use a transactional observer in a reactive stream at all (because of JTA).

@pipinet Do you use Hibernate Reactive in your app?

**Comment by pipinet** [comment]
> > If I understand correctly, @pipinet's objection here is that a transactional observer _will_ block the thread calling the observer -- it's just that it doesn't block when the event is fired, it's later.
> 
> Yes, the truth is that you can't use a transactional observer in a reactive stream at all (because of JTA).
> 
> @pipinet Do you use Hibernate Reactive in your app?

not use hibernate reactive.

**Comment by pipinet** [comment]
https://github.com/pipinet/quarkus-event

steps:
-  start project use command:   ./gradlew quarkusDev
- open url:  http://localhost:8080/q/graphql-ui
- use graphql query send query
```graphql
mutation {
  createA(name: "name"){
    id
  }
}
```

will go logs,  The graphql response returned  until  observer code  completed.

```log
Listening for transport dt_socket at address: 5005
Press [h] for more options>NG [4s]
Tests pausedv
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
2023-05-15 20:32:24,798 INFO  [io.qua.dev.h2.dep.H2DevServicesProcessor] (build-15) Dev Services for H2 started.
2023-05-15 20:32:24,829 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-15) Dev Services for the default datasource (h2) started
2023-05-15 20:32:24,834 INFO  [io.qua.hib.orm.dep.dev.HibernateOrmDevServicesProcessor] (build-28) Setting quarkus.hibernate-orm.database.generation=drop-and-create to initialize Dev Services managed database
     __  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-05-15 20:32:27,151 INFO  [org.hib.too.sch.int.exe.GenerationTargetToDatabase] (JPA Startup Thread) HHH000476: Executing script '[injected ScriptSourceInputNonExistentImpl script]'
     2023-05-15 20:32:27,314 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-event 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.3.Final) started in 4.511s. Listening on: http://localhost:8080
2023-05-15 20:32:27,315 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-05-15 20:32:27,315 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, narayana-jta, smallrye-context-propagation, smallrye-graphql, vertx]
     2023-05-15 20:32:29,668 ERROR [com.qwl.AEventHandler] (vert.x-worker-thread-1) 1------This message will print before graphql response===========--> 90% EXECUTING [10s]
> :qu2023-05-15 20:32:39,668 ERROR [com.qwl.AEventHandler] (vert.x-worker-thread-1) 2-------This message will print before graphql response==========--> 90% EXECUTING [20s]
```

**Comment by pipinet** [comment]
> I see. Well, I think that you may need to use `void onEvent(@Observes(during=AFTER_SUCCESS) AEvent event) { ... }` and inside this observer method, i.e. during the notification, call some other async code (e.g. fire an async event or `@Inject ExecutorService` and submit a task) that would perform the business logic (and possibly start a new transaction if you need to access JPA entities).

in my business case,  event handler will new transaction. 
> 1、i need event handler do not block graphql response.
> 2、i need event handler run after fire event transaction commited.

**Comment by mkouba** [comment]
> > I see. Well, I think that you may need to use `void onEvent(@Observes(during=AFTER_SUCCESS) AEvent event) { ... }` and inside this observer method, i.e. during the notification, call some other async code (e.g. fire an async event or `@Inject ExecutorService` and submit a task) that would perform the business logic (and possibly start a new transaction if you need to access JPA entities).
> 
> in my business case, event handler will new transaction.
> 
> > 1、i need event handler do not block graphql response.
> > 2、i need event handler run after fire event transaction commited.

Yes, that's what I described above. Something like this should work:

```java
@ApplicationScoped
class MyBean {

   void onEvent(@Observes(during=AFTER_SUCCESS) AEvent event, ExecutorService executor) {
      // this method is executed when the transaction used to serve the graphql request is commited
      // and returns immediately
      executor.submit(() -> doSomething());
   }

   // the method must not be private otherwise the transactional interceptor would not work
   @Transactional
   void doSomething() {
      // this method is executed asynchronously on a different thread...
   }
}
```

**Comment by pipinet** [comment]
> > > I see. Well, I think that you may need to use `void onEvent(@Observes(during=AFTER_SUCCESS) AEvent event) { ... }` and inside this observer method, i.e. during the notification, call some other async code (e.g. fire an async event or `@Inject ExecutorService` and submit a task) that would perform the business logic (and possibly start a new transaction if you need to access JPA entities).
> > 
> > 
> > in my business case, event handler will new transaction.
> > > 1、i need event handler do not block graphql response.
> > > 2、i need event handler run after fire event transaction commited.
> 
> Yes, that's what I described above. Something like this should work:
> 
> ```java
> @ApplicationScoped
> class MyBean {
> 
>    void onEvent(@Observes(during=AFTER_SUCCESS) AEvent event, ExecutorService executor) {
>       // this method is executed when the transaction used to serve the graphql request is commited
>       // and returns immediately
>       executor.submit(() -> doSomething());
>    }
> 
>    // the method must not be private otherwise the transactional interceptor would not work
>    @Transactional
>    void doSomething() {
>       // this method is executed asynchronously on a different thread...
>    }
> }
> ```

@mkouba OK, thanks。that's all we can do, there is no other better way, but usually AFTER_SUCCESS will be handled asynchronously.
