### ISSUE TITLE
OpenTelemetry SDK autoconfiguration ignores OTEL service name in favor of Quarkus app name

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#33317]
### Describe the bug

With https://github.com/quarkusio/quarkus/pull/30033 I expected autoconfiguration work for properties listed here https://github.com/quarkusio/quarkus/blob/main/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/OTelFallbackConfigSourceInterceptor.java#L85 and [OTEL documentation](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#opentelemetry-resource) says that `otel.service.name` should have preference over `otel.resource.attributes`. However, Quarkus OpenTelemetry extension creates Tracer resource directly and is using Quarkus application name (or artifact if not available)
https://github.com/quarkusio/quarkus/blob/43a53588daa126477e24e81c75abfbf017547df5/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/TracerRecorder.java#L52
https://github.com/quarkusio/quarkus/blob/43a53588daa126477e24e81c75abfbf017547df5/extensions/opentelemetry/deployment/src/main/java/io/quarkus/opentelemetry/deployment/tracing/TracerProcessor.java#L158

### Expected behavior

Quarkus documentation says `otel.service.name` should have priority
https://github.com/quarkusio/quarkus/blob/43a53588daa126477e24e81c75abfbf017547df5/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/OTelRuntimeConfig.java#L52

### Actual behavior

Quarkus application name is used.

### How to Reproduce?

Define `otel.service.name` and check traces (I'm using Jaeger). IMHO it's straight forward, but ping me if you really need one.

### Quarkus version or git rev

999-SNAPSHOT

**Comment by brunobat** [comment]
`otel.service.name` is not even being mapped. We use the standard `quarkus.application.name` for quarkus. 

Somewhere around here: https://github.com/quarkusio/quarkus/blob/43a53588daa126477e24e81c75abfbf017547df5/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryProducer.java#L86
We should map `otel.service.name` into the oTelConfigs and agree on a priority for it. Something like:

`quarkus.application.name` > `otel.service.name` > `otel.resource.attributes`

Test for the resource: https://github.com/quarkusio/quarkus/blob/3e6b2a557205e7b726885792c9d616fd28042b08/extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/OpenTelemetryResourceTest.java#L54

**Comment by michalvavrik** [comment]
Thanks, makes sense, I'll look at this next week unless someones quicker.

**Comment by geoand** [comment]
@michalvavrik are you still planning on tackling this one?

**Comment by michalvavrik** [comment]
Thanks for the reminder, I'll take care of it this week.

**Comment by jorgebsa** [comment]
Are you sure this has been fixed? I'm trying to use the service name on 3.2.2 and 3.2.1, and on neither it takes precedence over the application's name. I've tried setting it via config file, via -D, via env vars, running via qaurkus:dev or built jib image. I always end up with the app name on the traces and jaeger.

I've put breakpoints on the changed lines of #34581. On `OpenTelemetryProducer` I can see that the service name is loaded from the property, but ends up discarded on the merged resource. On `TraceUtil`, the debug never stopped on the serviceName nullability check.

![image](https://github.com/quarkusio/quarkus/assets/7410139/a05c395e-1941-4100-8f0c-8504b5d61609)
![image](https://github.com/quarkusio/quarkus/assets/7410139/b809ce3a-9e66-4d7c-bc56-ff20245635c3)
![image](https://github.com/quarkusio/quarkus/assets/7410139/ae13a977-5a4e-4b00-bfaa-6e18eeebaa99)
![image](https://github.com/quarkusio/quarkus/assets/7410139/5f9c9ace-46ad-4b61-a272-f12042f24a93)

**Comment by brunobat** [comment]
There is a test for this here: https://github.com/michalvavrik/quarkus/blob/main/extensions/opentelemetry/deployment/src/test/java/io/quarkus/opentelemetry/deployment/OpenTelemetryServiceNameTest.java

Please note that the service name from OTel:
`quarkus.otel.service.name` is different from the one loaded in resources: `quarkus.otel.resource.attributes=service.name=cats`

**Comment by michalvavrik** [comment]
> By reading its description, I've assumed that if I were to set this value to something else different than the app's name, then the traces generated by quarkus would use such value as the service name on the traces, such that I could find this service name on Jaeger.

> From my experience with 3.2.1 and 3.2.2, such property has no impact at all on the name used on the traces exported to jaeger, everything is exported with the artifact id as the service name. So, if i were to differentiate them, I would need to apply extra filters on each trace, such as the host that exported it or any other.

`quarkus.otel.service.name` should have precedence over `quarkus.application.name`. Please open an issue with reproducer. Comments in closed issue are not ideal platform since they don't provide way to to reproduce it. 

The point is, we have test that shows it works under certain circumstances, if there are circumstances when it doesn't work, it needs to be fixed. Please help by providing reproducer or as much code / info as you manage.

Thanks for reporting it.

**Comment by michalvavrik** [comment]
> From my experience with 3.2.1 and 3.2.2, such property has no impact at all on the name used on the traces exported to jaeger, everything is exported with the artifact id as the service name. 

So if I get it right then you don't set `quarkus.application.name` and then it doesn't work? And when you set it to `quarkus.application.name=ignored` does it work? Reproducer would made the difference.

**Comment by jorgebsa** [comment]
@michalvavrik so, I was going to create a reproducer, but I guess I don't even need to do it. I've just created a new project on Idea using the built-in quarkus integration. 

Told it to create the project with maven, java 17, name `otel-service-name-reproducer`, and extensions `quarkus-opentelemetry` and `quarkus-resteasy-reactive` and it ended up creating the project with 3.2.3 (which is good, as i had already reproduced it on 3.2.1 and 3.2.2 locally)

![image](https://github.com/quarkusio/quarkus/assets/7410139/4df79049-a159-4ad2-b94c-0ae99bcb4122)

On it was setup, I've started the all-in-one Jaeger container and then I've ran the application with the `quarkus.application.name` undefined and later defined as `app-name`, while the `quarkus.otel.service.name` was always set to `service-name`

![image](https://github.com/quarkusio/quarkus/assets/7410139/8f97e46e-bbae-4fa2-b20c-7572e52674a8)

Once it was up, I called the example GET endpoint 

![image](https://github.com/quarkusio/quarkus/assets/7410139/1310dcd4-abb5-4722-9ff6-75b319a2c6f0)

![image](https://github.com/quarkusio/quarkus/assets/7410139/7eab27fa-4385-4893-999a-996398545525)

When I checked jaeger, I could find as services only the `app-name` and the artifact's id `otel-service-name-reproducer`, but not the `service-name` which was configured on the OTel service name property.

![image](https://github.com/quarkusio/quarkus/assets/7410139/62c687f0-2322-4b65-8775-ffbb5c56bf5c)


Would you like me to push this reproducer to github? Should I open a new Issue as well?

**Comment by jorgebsa** [comment]
If I try to configure `quarkus.otel.resource.attributes=service.name=attribute-name` it doesn't have any effect either:

![image](https://github.com/quarkusio/quarkus/assets/7410139/387a3303-3722-4264-972d-8c0dd0ba3211)

And after executing the requests:

![image](https://github.com/quarkusio/quarkus/assets/7410139/a624c99b-7272-43a3-937a-0d9b267caa92)

**Comment by michalvavrik** [comment]
@jorgebsa I created a reproducer and you are right indeed! I tested it with the configuration that we have tested in Quarkus project and the only difference I can see is a **span exporter**, however I don't have time to look properly today. I'll check over the weekend. Sorry for your trouble.

**Comment by jorgebsa** [comment]
@michalvavrik haha i was about to comment that I pushed the reproducer to github. Anyway, glad that you are able to reproduce it as well and it is not happening on my project only hehe. 

Looking forward to the fix :) let me take this opportunity here to say how much I appreciate Quarkus as a whole. Keep up the excellent work, your team makes my programmer life much more enjoyable and productive!

**Comment by michalvavrik** [comment]
I'm sure Quarkus team appreciates it. Here is the fix https://github.com/quarkusio/quarkus/pull/35193.

**Comment by michalvavrik** [comment]
@jorgebsa as workaround, you can set some resource attributes which should do the trick as that was the difference between your case and our test: `quarkus.otel.resource.attributes`. IIRC 3.2.4.Final is due soon, I added backport label so maybe the fix will get in. Let see.

**Comment by jorgebsa** [comment]
@michalvavrik you are amazing, not only you implemented a fix this quickly after reported, you also provided a workaround that can be used on the current version :) thank you so much!

**Comment by brunobat** [comment]
@jorgebsa you mentioned that you have a reproducer... Do you have the link?

**Comment by jorgebsa** [comment]
@brunobat yes, here it is: https://github.com/jorgebsa/otel-service-name-reproducer

**Comment by brunobat** [comment]
Thanks @jorgebsa
