### ISSUE TITLE
Index _all_ dependencies with a certain `groupId`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#33316]
### Description

For the migration to Quarkus 3, I'm about to remove jandex-maven-plugin from my ~20 modules Maven project to have one thing less to keep in sync for each Quarkus update.

As I don't really like empty `beans.xml` and listing all artifactIds is pretty verbose (especially in a distributed config setup), having Quarkus index _all_ artifacts that belong to a configured `groupId` would really help.
Relevant docs: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

### Implementation ideas

It probably boils down to making `quarkus.index-dependency.<name>.artifact-id` optional.

**Comment by famod** [comment]
Also /cc @geoand

**Comment by manovotn** [comment]
> As I don't really like empty `beans.xml`

Is there some actual reason why this wouldn't work for you or is it just a matter of preference?
Adding a marker file seems like, by far, the easiest solution here that wouldn't require any further work even if using distributed config setup. Or is there something I am missing?

**Comment by famod** [comment]
Empty beans.xml do absolutely work. It's 20 empty files vs. one single config setting though.

**Comment by famod** [comment]
PS: external libs are a different story w.r.t. beans.xml.

**Comment by manovotn** [comment]
> PS: external libs are a different story w.r.t. beans.xml.

Sure this one I can understand and that's what the configs are primarily for.

> Empty beans.xml do absolutely work. It's 20 empty files vs. one single config setting though.

Right, but do they hurt anyhow? You basically add it and forget about it, not need for config as well.
I mean it sure is possible to add what you're asking for, I am just curious why are marker files bad.

Also note that CDI 4 uses this syntax to mark a bean archive in CDI Lite, see https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_archive

**Comment by famod** [comment]
> Right, but do they hurt anyhow? You basically add it and forget about it, not need for config as well.

They don't, it's just more inconvenient. You have to remember to add them to new modules, for example (rare case, admittedly).
I'm not saying empty beans.xml files are bad per se. It's just about developer joy and getting things done quickly and neatly and DRY. 😉

**Comment by geoand** [comment]
I'm +0 on this

**Comment by Ladicek** [comment]
This could be done using an extension I think? Collect all the relevant vartifacts from the `CurateOutcomeBuildItem` and produce `IndexDependencyBuildItem` for them. Then, you don't even have to configure anything :-)

**Comment by gsmet** [comment]
I think it could be a valuable addition if you're willing to do the work.

**Comment by mkouba** [comment]
If we decide to implement this then it could be more practical to turn the `artifact-id` into a regex (or support wildcards?) so that it's possible to select a subset of artifacts with a given `groupId`.
