### ISSUE TITLE
Slight inaccuracy in ORM 5 to 6 migration guide

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#33320]
### Describe the bug

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#query-syntaxbehavior-changes

The migration guide states `Any application using JPQL/HQL/SQL strings for queries, and relying on the syntax elements listed below.`

Can this please be changed to something like
`Any application using JPQL/HQL/SQL strings for queries or criteria queries, and relying on the syntax elements listed below.`

Main reason ist, that I was hoping that my criteria queries still worked somehow. Which they do not :)

On further reading, the hibernate migration guide itself already mentions that criteria queries are also affected.
https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#query-path-comparison

I still believe that the Quarkus specific hibernate migration guide should also mention this.

`2023-05-12 06:12:13,361 ERROR [com.act.wol.web.com.jax.han.RuntimeExceptionHandler] (executor-thread-2) d59e9bee-39e9-4b24-977b-92994dd267a6 No dedicated ExceptionHandler for IllegalArgumentException. Wrapping to UnknownTechnicalException.: java.lang.IllegalArgumentException: 
Can't compare test expression of type [Repository] with element of type [BasicSqmPathSource(id : Long)]
        at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.assertComparable(SqmCriteriaNodeBuilder.java:2098)
        at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:2109)
        at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:182)
     [...]
`

### Expected behavior

better migration guide

### Quarkus version or git rev

3.0.3.Final

**Comment by yrodiere** [comment]
Fixed, thanks for reporting!
