### ISSUE TITLE
Thread pinning with PostgreSQL JDBC driver

### ISSUE THREAD

**Issue by davecramer** [quarkusio/quarkus#33337]
### Discussed in https://github.com/quarkusio/quarkus/discussions/33325

<div type='discussions-op-text'>

<sup>Originally posted by **davecramer** May 12, 2023</sup>
This https://quarkus.io/guides/virtual-threads#pinning-cases should now be historical with the release of 42.6.0 of the PostgreSQL JDBC driver. Virtually all synchronized methods have been replaced with reentrant lock. See https://jdbc.postgresql.org/changelogs/2023-03-17-42.6.0-release/ for details.
It would be great if you could update your site to reflect the current state.</div>

**Comment by rolfedh** [comment]
Hi @davecramer. Thanks for reporting this doc issue. I've validated the [Pinning cases](https://quarkus.io/guides/virtual-threads#pinning) content with @cescoffier, and added a link to the [When Quarkus meets Virtual Threads](https://quarkus.io/blog/virtual-thread-1/) blog post. Please let me know if you're satisfied with the results. If so, I'll close this issue.

**Comment by davecramer** [comment]
@rolfedh Hi, thanks for addressing this. Any chance you could add something to the effect of "as of version 42.2.6 this is no longer the case" or even "old versions (before 42.2.6)" ? 

Cheers,
Dave

**Comment by rolfedh** [comment]
Hi, @cescoffier. What do you think about Dave's proposal?

**Comment by cescoffier** [comment]
Sure, we can mention the version.

**Comment by rolfedh** [comment]
Hi @davecramer, please have a look at https://github.com/quarkusio/quarkus/pull/36553/files and leave any suggestions or an `lgtm`. Thanks. Then, I'll run it by the team for approval and merge.
