### ISSUE TITLE
ServerExceptionMapper AmbiguousResolutionException during testing only

### ISSUE THREAD

**Issue by heshamz** [quarkusio/quarkus#33347]
### Describe the bug

Hello,

I am facing the following exception while running the tests, and I am not facing something while running through Quarkus dev command.

If I put the ServerExceptionMapper inside the end point, then no issue, but if I placed it outside it, I am facing the error.

**Gradle File**

`plugins {
    id 'org.jetbrains.kotlin.jvm' version "1.8.20"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.8.20"
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-smallrye-jwt-build'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'io.quarkus:quarkus-smallrye-graphql'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.quarkus:quarkus-arc'
    implementation "io.quarkus:quarkus-hibernate-reactive-panache"
    implementation "io.quarkus:quarkus-reactive-mysql-client"
    implementation 'io.quarkus:quarkus-elytron-security-common'
    implementation "io.quarkus:quarkus-reactive-pg-client"
    compileOnly 'org.projectlombok:lombok:1.18.26'
    annotationProcessor 'org.projectlombok:lombok:1.18.26'

    testCompileOnly 'org.projectlombok:lombok:1.18.26'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.quarkus:quarkus-test-vertx'
}

group 'com.demo'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
allOpen {
    annotation("jakarta.ws.rs.Path")
    annotation("jakarta.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

compileKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17
    kotlinOptions.javaParameters = true
}

compileTestKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
    main.java.srcDirs += 'src/main/java'    
}
`

**Test File**

`package com.demo;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.vertx.RunOnVertxContext;
import jakarta.ws.rs.core.MediaType;
import org.jose4j.json.internal.json_simple.JSONObject;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

@QuarkusTest
class AuthenticateRoutesTest {

    @BeforeEach
    void setUp() {
    }

    @AfterEach
    void tearDown() {
    }

    @Test
    @RunOnVertxContext
    void testAuthenticate() {
        Map<String, String> paramsMap = new HashMap<>();
        paramsMap.put("username", "admin");
        paramsMap.put("password", "password");
        JSONObject joParams = new JSONObject(paramsMap);

        JSONObject joResponse = given()
                .when()
                .body(joParams)
                .contentType(MediaType.APPLICATION_JSON)
                .post("/security/authenticate")
                .then()
                .statusCode(200)
                .contentType(MediaType.APPLICATION_JSON)
                .extract().response().as(JSONObject.class);

        assertNotNull(joResponse.get("token"));

    }
}`

**Exception Mapper**

`package com.demo;

import jakarta.ws.rs.core.Response;
import org.jboss.resteasy.reactive.RestResponse;
import org.jboss.resteasy.reactive.server.ServerExceptionMapper;

public class SecurityExceptionsMapper {
    @ServerExceptionMapper(value = InvalidUsernameOrPasswordException.class)
    public RestResponse<String> mapInvalidUsernameOrPasswordException(InvalidUsernameOrPasswordException ex) {
        return RestResponse.status(Response.Status.UNAUTHORIZED, "InvalidUsernameOrPasswordException");
    }
}
`

**Build Exceptions during testing**

`
> Task :processResources UP-TO-DATE
> Task :quarkusGenerateCode UP-TO-DATE
> Task :compileQuarkus-test-generated-sourcesKotlin NO-SOURCE
> Task :compileQuarkusTestGeneratedSourcesJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :compileKotlin
> Task :compileJava
> Task :classes
> Task :quarkusGenerateCodeTests
> Task :compileTestKotlin
> Task :compileTestJava UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :test
Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: %s
> Task :test FAILED
2023-05-14 01:49:43,447 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-19) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "com.demo" found in [com.demo::jar, e82ef38503f957aa096ebfbac35bf0bed110c474:main::jar]

java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type com.demo.SecurityExceptionsMapper and qualifiers [@Default]
	- java member: com.demo.SecurityExceptionsMapper$GeneratedExceptionHandlerFor$InvalidUsernameOrPasswordException$OfMethod$mapInvalidUsernameOrPasswordException():arg0
	- declared on CLASS bean [types=[org.jboss.resteasy.reactive.server.spi.ResteasyReactiveExceptionMapper, com.demo.SecurityExceptionsMapper$GeneratedExceptionHandlerFor$InvalidUsernameOrPasswordException$OfMethod$mapInvalidUsernameOrPasswordException, java.lang.Object, jakarta.ws.rs.ext.ExceptionMapper], qualifiers=[@Default, @Any], target=com.demo.SecurityExceptionsMapper$GeneratedExceptionHandlerFor$InvalidUsernameOrPasswordException$OfMethod$mapInvalidUsernameOrPasswordException]
	- available beans:
		- CLASS bean [types=[com.demo.SecurityExceptionsMapper, java.lang.Object], qualifiers=[@Default, @Any], target=com.demo.SecurityExceptionsMapper]
		- CLASS bean [types=[com.demo.SecurityExceptionsMapper, java.lang.Object], qualifiers=[@Default, @Any], target=com.demo.SecurityExceptionsMapper]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1395)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:305)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:156)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

### Expected behavior

To work during testing the same way like during quarkus dev command

**Comment by heshamz** [comment]
Ok, I will work on that, but just an update, when I removed Kotlin and the project was only with Java, it worked fine, but when both Java and Kotlin were configured together, the issue happened.

**Comment by geoand** [comment]
@heshamz were you able to come up with a sample?

**Comment by geoand** [comment]
Closing as we never got a reproducer
