### ISSUE TITLE
Performance degraded in 3.0.3.Final release

### ISSUE THREAD

**Issue by OS-ramamurtisubramanian** [quarkusio/quarkus#33341]
### Describe the bug

I was benchmarking a simple app, which uses RestEasy-reactive, I am using a blocking endpoint where it receives a POST json body and it does some json manipulation and forwards it to another service.

I ran 2 pods in k8s with 1 cpu and 1 GB ram, with default thread pool and worker pool settings.

with quarkus 3.0.2.Final, they were able to serve more than 36k requests/second.
with quarkus 3.0.3.Final, it went down to 18k requests/second.

### Expected behavior

Quarkus server should be able to serve 18k requests/second.

### Actual behavior

Quarkus server is serving 9k requests/second.

### Quarkus version or git rev

3.0.3.Final

**Comment by melloware** [comment]
you should post your Quarkus project you used for benchmark so devs can review it.

**Comment by geoand** [comment]
> with quarkus 3.0.2.Final, they were able to serve more than 36k requests/second.
> with quarkus 3.0.3.Final, it went down to 18k requests/second.

Do you have a sample to share?

**Comment by geoand** [comment]
cc @franz1981 just for your awareness

**Comment by franz1981** [comment]
>  I am using a blocking endpoint where it receives a POST json body and it does some json manipulation and forwards it to another service.


Please share more details about what the code does and the configuration or we won't be able to help...
