### ISSUE TITLE
Contextualizing problem when using panache count operation

### ISSUE THREAD

**Issue by EliasZ** [quarkusio/quarkus#33348]
### Describe the bug

Not sure if I'm missing something, but tried finding anything related in the docs and online but couldn't find anything. In the docs it says:

>It takes fragments of HQL (JP-QL) queries and contextualizes the rest. 

I have no idea where the contextualizing starts and what the limits are:
- there seems to be a problem contextualizing the query fed to `count` - didn't test with other operations
- contextualized queries lack aliases (and no way to introduce them?) meaning we can get attribute-conflicts

For example:

### Given (simplified):
```
class Fruit  {
    int id;
    @ManyToOne
    Basket basket;
    LocalDateTime createdAt;

class Basket {
    int id;
    boolean isOpen;
    LocalDateTime createdAt;
}

class FruitRepository implements PanacheRepository<Fruit> {}
```

### When:
querying the amount of fruits in open baskets created since 10 minutes ago could be something like this:

```
Fruit.count("join basket b where createdAt >= ?1 and b.isOpen = true", now().minusMinutes(10));
```

### Then:
SELECT COUNT(*) 
FROM org.acme.Fruit SOMEALIASHERE
JOIN basket b
WHERE SOMEALIASHERE.createdAt >= ?1
AND b.isOpen= true

### This is what actually happens:
SELECT COUNT(*) 
FROM org.acme.Fruit 
WHERE <<< query is contextualized as WHERE part, wouldn't be valid JPQL
JOIN basket b
WHERE createdAt >= ?1 <<< alias is missing here
AND b.isOpen= true

And the actual exception:
```
java.lang.IllegalStateException: Multiple from-elements expose unqualified attribute : createdAt
```

Probably because the duplicate `createdAt` reference is detected before the invalid JPQL is. At this point I could find no way to supply an alias to use in queries.

### Workaround
Writing the query like this works but would be nice (and expected?) if it would work as described above as we already type-hinted to `Fruit`:
```
Fruit.count("from Fruit f join basket b where f.createdAt >= ?1 and b.isOpen = true", now().minusMinutes(10));
```

Closest related is maybe #23343 which seems to have a similar problem: when letting operations generate JPQL, difficulties arise when conflicts arise due to conflicting names in entities.

### Quarkus version or git rev

3.0.2

**Comment by Kaderjan** [comment]
hii everyone, I also wanna contribute to open projects. But I am new to contributing, can anyone help me please?

**Comment by EliasZ** [comment]
@FroMage ah I see, I completely missed that part of the documentation. Then this is not an issue, I'm impartial to it being added as a feature. I will close this.
