### ISSUE TITLE
`ConsoleProcessor.java` references `quarkus.log.console.color`, which was deprecated in Quarkus 2.1

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#33356]
### Describe the bug

[Line 77 in core/deployment/src/main/java/io/quarkus/deployment/console/ConsoleProcessor.java](https://github.com/quarkusio/quarkus/blob/78c3e36b846168b6cce37c92aa642164436c7228/core/deployment/src/main/java/io/quarkus/deployment/console/ConsoleProcessor.java#L77) references `quarkus.log.console.color`, which [was deprecated in Quarkus 2.1](https://github.com/quarkusio/quarkus/pull/18506):

E.g.,:
```
ConfigProvider.getConfig().getOptionalValue("quarkus.log.console.color",
```

Should it reference `quarkus.console.color` instead?

**Comment by geoand** [comment]
cc @stuartwdouglas
