### ISSUE TITLE
Exclusion in optional dependency are not honor in 2.x

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#33354]
### Describe the bug

I have a different result with Quarkus 2.16.7 and 3.0.3 regarding exlcusion in a dependency optionaly included.
It seems that 2.16.7 do not honor exclusion of a dependency inside the chain of dependency.

The reproducer extension has a conditional dependency. The condition is `software.amazon.awssdk:apache-client`.
This lib includes `org.apache.httpcomponents:httpclient` which in turn includes `commons-logging:commons-logging`.
When activated the extension should include `quarkus-apache-httpclient` which include `org.apache.httpcomponents:httpclient` excluding `commons-logging:commons-logging`

### Expected behavior

`commons-logging` should not be included

### Actual behavior

- In 3.x, `commons-logging` is not included
- In 2.x, `commons-logging` IS included

### How to Reproduce?

Small extension reproducer : <https://github.com/scrocquesel/quarkus-conditional-test>

Initial commit is with 3.x, second comit with 2.x.
I have push a dependency-tree.md to compare easily between commits.
This is the line that should not be added in 2.x https://github.com/scrocquesel/quarkus-conditional-test/commit/7d31010200774091c68ce1b9b4ae97750b4e2307#diff-4f5422ff0b71f943534780e86dbe91d2fae56cc051dcc4b1b70f274773e9f786R108

### Additional information

Note that in 2.x, quarkus:dependency-tree doesn't work with maven 3.9, so the dependency tree has been generated with 3.8 version but the bug occured with both. I didn't test with earlier version of mvn.

**Comment by aloubyansky** [comment]
It's just a difference in the config of the dependency constraint in 3.0.3 and 2.16.7.
In quarku-bom 3.0.3 it's
```
<dependency>
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpclient</artifactId>
<version>4.5.14</version>
<exclusions>
<exclusion>
<groupId>commons-logging</groupId>
<artifactId>*</artifactId>
</exclusion>
</exclusions>
</dependency>
```
while in quarkus-bom 2.16.7 it's
```
<dependency>
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpclient</artifactId>
<version>4.5.14</version>
</dependency>
```
You can also replicate it with `mvn dependency:tree`.
Also the test in your project doesn't actually trigger conditional inclusion of an extension, since it declares a direct dependency on the extension. In this case the condition is ignored.
