### ISSUE TITLE
[Extension Proposal] Sentry exporter for OpenTelemetry

### ISSUE THREAD

**Issue by derari** [quarkusio/quarkus#33359]
### Description

Quarkus has an OpenTelemetry extension, and there is a Quarkiverse extension for Sentry logging.

With a bit of glue code and some extension points for customization, the OpenTelemetry data can be exported to Sentry.

It would probably also be possible to include this extension in the existing Sentry repository, but it wouldn't be a perfect fit as this is about tracing, and the existing repository is about logging.

This extension could be called quarkus-sentry-opentelemetry-exporter or quarkus-opentelemetry-exporter-sentry.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-sentry-opentelemetry-exporter

### Short description

Exports OpenTelemetry spans to Sentry

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- sentry
- opentelemetry
- logging
- tracing

### Team Members

- @derari

**Comment by gastaldi** [comment]
Please submit the exporter as a new module in https://github.com/quarkiverse/quarkus-opentelemetry-exporter instead

**Comment by brunobat** [comment]
Correct, all OTel exporters should go to the quarkiverse repo.
