### ISSUE TITLE
[3.0.3] quarkus-jaxb broken

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#33369]
### Describe the bug

Hi!

I've upgraded my project to 3.0.3 version from 2.13.3 and a lot of errors appeared regarding to javax.xml.bind package, which is missing.

![image](https://github.com/quarkusio/quarkus/assets/7142948/a22672b0-c318-4571-8cb5-97870118a349)

Can you provide any solution to this?

Thanks,
Viktor

### Expected behavior

javax.xml.bind can be resolved

### Actual behavior

Cannot resolve javax.xml.bind

### Output of `java -version`

11.0.18

### GraalVM version (if different from Java)

22.3.1

### Quarkus version or git rev

3.0.3

**Comment by robp94** [comment]
You need to use the `jakarta` namespace, `javax` is not used anymore. If possible, try to use the migration scripts provided in the migration guides.

**Comment by Sgitario** [comment]
As an additional resource, this is the automatic update tool that @robp94 mentioned: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#automatic-update-tool
