### ISSUE TITLE
allow quarkus dev to pick random debug port

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33363]
### Description

I tend to run a lot of quarkus dev instances on my machine and its a bit tedious having to manually find a free debug port.

We already check debug port and print "Port 5005 in use, not starting in debug mode"  (in core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java) - couldn't we have a magic value like -1 or 0 to indicate "pick one" or a explicit flag to let quarkus dev try first on the configured port but if not free pick a random port and print it out.

Then user can either manually or using IDE's attach features figure connect to the process without having to stop, adjust flag, start again.

**Comment by geoand** [comment]
Do we know if this would work with IDE launch modes? My guess is that it won't...

**Comment by geoand** [comment]
> As in quarkus dev invoked by an IDE tool?

Yeah, that's what I meant.

**Comment by geoand** [comment]
I just tried the built-in Quarkus Launcher that IntelliJ Ultimate has and it essentially ignored debug port setting and does what you describe. 

So we if we do use a random port, the IntelliJ launcher should just ignore and life will be good for everyone.

So consider this my +1 and https://github.com/quarkusio/quarkus/pull/33521 takes care of choosing a random port when the debug port is set to `0` or a negative value.
