### ISSUE TITLE
Error handling with @WithSpan (OpenTelemetry)

### ISSUE THREAD

**Issue by mskacelik** [quarkusio/quarkus#33372]
### Describe the bug

If an exception occurs in a method that's annotated with `@WithSpan`, the error won't be recorded in the trace.

### Expected behavior

Trace will contain error span.

### Actual behavior

Currently the error span is missing from the trace. Or in the reproducer's case the entire trace is missing.

### How to Reproduce?

Slightly modified `TracedResources` class from the OpenTelemetry quickstart. https://quarkus.io/guides/opentelemetry
```java
package org.acme.opentelemetry;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import io.opentelemetry.instrumentation.annotations.WithSpan;
import org.jboss.logging.Logger;

@Path("/hello")
public class TracedResources {
    private static final Logger LOG = Logger.getLogger(TracedResources.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(){
        LOG.info("hello");
        doSomething();
        return "hello";
    }

    @WithSpan
    public String doSomething() {
        throw new RuntimeException("foo");
    }
}
```
When the app is running, execute the command `curl http://localhost:8080/hello` and look at the trace result.

### Output of `java -version`

openjdk version "17.0.5"

**Comment by brunobat** [comment]
We are not adding exceptions to the span... Will submit a PR.
