### ISSUE TITLE
REST Client Reactive: Listener & Request-scoped bean

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#33377]
### Describe the bug

We try to migrate from `quarkus-rest-client` to `quarkus-rest-client-reactive`. In one of our projects, there is a `org.eclipse.microprofile.rest.client.spi.RestClientListener` which accesses a request-scoped bean by using `CDI`. The REST Client itself is of course also request-scoped as described here: https://quarkus.io/guides/rest-client#create-the-configuration.

This works with `quarkus-rest-client`. When using `quarkus-rest-client-reactive`, an exception is thrown: `jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance...`.

### Expected behavior

It should be possible to access request-scoped beans in listeners when using also request-scoped client.

### Actual behavior

Exception `jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance...` is thrown.

### How to Reproduce?

Reproducer: [rest-client-reactive-request.zip](https://github.com/quarkusio/quarkus/files/11477173/rest-client-reactive-request.zip)

1. Import project
2. Run the only available test
3. See exception
4. Switch dependency to non-reactive
5. See success

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.2846]

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by Sgitario** [comment]
I will look into this issue to see what we can do to support this.
