### ISSUE TITLE
Make sure OTel receives standard duration string properties 

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#33381]
### Description

Following up this PR:
https://github.com/quarkusio/quarkus/pull/33326

We identified that OTel does not understand some of the Quarkus defined duration properties due to be more permissive.
We need a transformation to normalize all duration values to something OTel will accept.

### Implementation ideas

This should be done around here: https://github.com/quarkusio/quarkus/blob/de16f435b6e3112fc73b0f032a98e0e838739dab/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/OpenTelemetryProducer.java#LL157C26-L157C26

Or use converters in each prop... This would be cleaner.

**Comment by mcruzdev** [comment]
hi @brunobat, how are you?
can I help with it?

**Comment by brunobat** [comment]
I see that you opened a PR. Many thanks for that. Will take a look.
