### ISSUE TITLE
INFO message is confusing 

### ISSUE THREAD

**Issue by ggallen** [quarkusio/quarkus#33389]
### Describe the bug

I get the following info message when building my code:
```posh
[INFO] [io.quarkus.arc.processor.Types] Producer method io.fabric8.kubernetes.client.dsl.MixedOperation<com.redhat.agogos.v1alpha1.Component, com.redhat.agogos.v1alpha1.ComponentList, io.fabric8.kubernetes.client.dsl.Resource<com.redhat.agogos.v1alpha1.Component>> components() contains a parameterized typed with a wildcard. This type is not a legal bean type according to CDI specification and will be ignored during bean resolution.
```
And here is methods that seems to be causing hte message to be generated:
```java
    @Override
    @Produces
    public MixedOperation<Component, ComponentList, Resource<Component>> components() {
        return kubernetesClient.resources(Component.class, ComponentList.class);
    }
```
Finally, here is the Component declaration:
```java
@ToString
@RegisterForReflection
@Kind("Component")
@Group("agogos.redhat.com")
@Version("v1alpha1")
public class Component extends AgogosResource<ComponentSpec, Status> implements Namespaced {
```

### Expected behavior

I'd like to be able to resolve whatever issue the messages is indicating. It is not clear how to do that.

### Actual behavior

I can resolve the issue so the message no longer appears.

### How to Reproduce?

The repository is internal to Red Hat:

https://gitlab.cee.redhat.com/agogos/agogos

Build with:
```
./mvnw clean package -DskipTests
```

### Output of `uname -a` or `ver`

Linux localhost.localdomain 5.19.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 4 15:42:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.16.1 2022-08-12 OpenJDK Runtime Environment (Red_Hat-11.0.16.1.1-1.fc36) (build 11.0.16.1+1) OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.1.1-1.fc36) (build 11.0.16.1+1, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f) Maven home: /home/gallen/.m2/wrapper/dists/apache-maven-3.8.2-bin/1um3pu5poco57pibs3g92d6vrf/apache-maven-3.8.2 Java version: 11.0.16.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.16.1.1-1.fc36.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.19.13-200.fc36.x86_64", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by geoand** [comment]
I'll have a look tomorrow

**Comment by geoand** [comment]
I've requested access to the code

**Comment by geoand** [comment]
I am pretty sure that Arc is being overzealous here but the type hierarchy of the Kubernetes Client is very confusing...

Arc reports the issue on this type:

```java
public interface DeletableWithOptions extends GracePeriodConfigurable<PropagationPolicyConfigurable<? extends Deletable>>,
    PropagationPolicyConfigurable<GracePeriodConfigurable<? extends Deletable>>, Timeoutable {

}
```

The problem is that there is nothing the application can do to remedy the warnig

**Comment by mkouba** [comment]
Well, the CDI spec is pretty clear that this is not a [legal bean type](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#legal_bean_types). So the message is IMO correct.

CC @manovotn

**Comment by manovotn** [comment]
Actually, I think it might be overzealous because the spec says:

> The resulting set of bean types for a producer method consists only of [legal bean types](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#legal_bean_types), all other types are removed from the set of bean types.

Lemme take a closer look...

**Comment by manovotn** [comment]
I'd personally keep the logging level as I believe it can help people identify erroneous setups.

**Comment by ggallen** [comment]
@manovotn, so how do I resolve this issue in my code?

**Comment by manovotn** [comment]
@ggallen if your code, or code where that bean is supposed to be used, doesn't attempt to inject the offending type which contains a wildcard, this is a non-issue and you can ignore it.
If it causes issues or if you want to remove the INFO msg, you can add `@Typed(...)` on your producer method and list the types that the bean is supposed to have and omit the offending one. [Here](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#restricting_bean_types) is a spec paragraph explaining how that works.

Note that by default a set of bean types (for producer method) is derived from a transitive closure of the method return type, minus types that are illegal ([spec text](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#producer_method_types)).

**Comment by manovotn** [comment]
> @manovotn does @Typed worked with generics?

The spec snippet shows `@Typed(Shop.class)` for a bean that has the following types - `{BookShop, Business, Shop<Book>}` so it'd say it does :)

> Also, is there a way to exclude types instead of including them?

I don't think so. I guess you'd get more power over bean types when registering synth bean but that's another story.
Point is, usually you don't need your bean to have all the types in its type hierarchy (which can be very deep) as bean types. Many are impl classes that aren't even user facing interfaces for example; so it's mostly easier to instead declare which types are supposed to be there.

**Comment by manovotn** [comment]
Sure, I'll take a look

**Comment by geoand** [comment]
🙏🏼

**Comment by manovotn** [comment]
Thanks for coming back with your discoveries @ggallen!
It turns out I was wrong and `@Typed` won't make the `INFO` go away.

The fact that we still log it is IMO not wrong because Arc does it while determining what's called an "unrestricted set of bean types" ([spec part](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_types)). Using `@Typed` merely restricts the set but doesn't play any role in discovering all the types a bean may have - which makes sense.

That brings back the question whether this `INFO` is actually useful and having seen this scenario, I'm now leaning towards saying we should just remove it or make it a debug level as it affects even users who are aware of this limitation and explicitly restrict set of bean types.

@mkouba WDYT?

**Comment by mkouba** [comment]
I'm not quite sure it makes sense to keep the `DEBUG` message. I mean users will never see this message and if something goes wrong there are/could be better ways to debug this kind of problem. So I'm personally +0 for `DEBUG` and +1 for removal.

**Comment by manovotn** [comment]
My thinking was that debug could still have some value in case users cannot pinpoint why they get unsatisfied dependencies due to removed bean types. But frankly, I don't mind removing it either :)
