### ISSUE TITLE
ValueResolvers added to EngineBuilder from a library are not recognized by type-safe templates check

### ISSUE THREAD

**Issue by dscoppelletti** [quarkusio/quarkus#33390]
### Describe the bug

I have to develop few webapps related to each other, so I would like extract common feature in a JAR module with Jandex index - I don't want to develop a real Quarkus extension because I will not publish the JAR library as an Open Source Software.  
Classes `@TemplateExtension` are not recognized by the main app from the common library, so I have developed some `ValueResolver`s and I have added them to the `EngineBuilder`.  
The `ValueResolver`s work properly in the templates in the WebApp, but if I enable Type-safe templates
(`@CheckedTemplate` annotation, `{@org.company.Model model}` and so on), then the build fails complaining that my extended functions are not recognized.

### Expected behavior

I would like collect Qute extension functions in a common library with Jandex index and I would like enabled 
Type-safe templates.

### Actual behavior

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.1.Final:build (default) on project seller-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found incorrect expressions (3):
[ERROR] 	[1] subscription-template/edit.qute.html:60:31 - {model.validStartDate.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.time.LocalDate] nor handled by an extension method
[ERROR] 	[2] subscription-template/edit.qute.html:151:35 - {model.price.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.math.BigDecimal] nor handled by an extension method
[ERROR] 	[3] subscription-template/edit.qute.html:179:31 - {model.discountDate.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.time.LocalDate] nor handled by an extension method
[ERROR] 
[ERROR] 	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:246)
...
```

### How to Reproduce?

1. Develop a parent Mave project with two subprojects: a  Quarkus WebApp and a Java library with Jandex index.
2. In the library, develop a `ValueResolver` and add it to the `EngineBuilder` using a bean that `@Observes` the `EngineBuilder`.
3. In the WebApp, develop a template that uses the `ValueResolver` and emit the template instance by a Reactive Controller.
4. Enable Type-safe templates (`@CheckedTemplate` annotation, `{@org.company.Model model}` and so on)
5. Run the WebApp in the dev profile.

### Output of `uname -a` or `ver`

MAC OSX 13.3.1 x86_64

### Output of `java -version`

17.0.6

### Quarkus version or git rev

3.0.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.8

**Comment by dscoppelletti** [comment]
I've returned to the official Quarkus way using the `@TemplateExtensions` annotation and I attach a demo solution.  
In the common library the `WebtvExtensions` class implements two extension functions `toFormValue(BigDecimal)` and `toFormValue(LocalDate)`.  The class `WebtvNamespace` implements a namespace function `webtv:withRootPath`.  
The webapp contains two templates using all of the extensions function enabling Type-safe templates (`@CheckedTemplate` annotation, `{@org.company.Model model}` and so on).
If I run the app (`./mvnw clean install && ./mvnw quarkus:dev -pl seller-app`), the build fails:

```
[ERROR] 	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found incorrect expressions (3):
[ERROR] 	[1] subscription-template/edit.qute.html:58:31 - {model.validStartDate.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.time.LocalDate] nor handled by an extension method
[ERROR] 	[2] subscription-template/edit.qute.html:149:35 - {model.price.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.math.BigDecimal] nor handled by an extension method
[ERROR] 	[3] subscription-template/edit.qute.html:177:31 - {model.discountDate.toFormValue().or(null)}: Property/method [toFormValue()] not found on class [java.time.LocalDate] nor handled by an extension method
```

But only functions `toFormValue(BigDecimal)` and `toFormValue(LocalDate)` are not recognized; the function `webtv:withRootPath` seems to be OK.

If I move the classes  `WebtvExtensions` and `WebtvNamespace` from the library to the app, all of the functions are recognized.

Forget all the rest, I just want put some extension functions in a library.
Is it possible?

[webtv.zip](https://github.com/quarkusio/quarkus/files/11485809/webtv.zip)

**Comment by mkouba** [comment]
> I've returned to the official Quarkus way using the @TemplateExtensions annotation...

:+1: 

> Forget all the rest, I just want put some extension functions in a library. Is it possible?

Yes, it should be possible. The template extension methods are discovered in the bean archives, so you can (1) try to add an empty `META-INF/beans.xml` descriptor in the `common` module, or (2) [generate a jandex index](https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index) for the `common` module.

> the function `webtv:withRootPath` seems to be OK.

I don't think so. Namespace expressions are not validated if a namespace extension method is not found which is exactly the case here.

**Comment by dscoppelletti** [comment]
Actually, I have configured the generation of the Jandex index for the `common` module, in fact, in the real solution, the app `seller-app` can see the beans defined in the `common` module.

The `@TemplateExtension` classes are not _real_ bean, are they?

What do you mean for "Namespace expressions are not validated if a namespace extension method is not found which is exactly the case here."?  
Actually, I have annotated the `WebtvNamespace` class with `@TemplateExtension(namespace = 'webtv')`, so `withRootPath` should be a namespace extension method, shouldn't be?

**Comment by mkouba** [comment]
> Actually, I have configured the generation of the Jandex index for the common module...

Ok, let me check the reproducer...

> The `@TemplateExtension` classes are not _real_ bean, are they?

No, they're not.

> What do you mean for "Namespace expressions are not validated if a namespace extension method is not found which is exactly the case here."?

If qute finds an expression like `{webtv:withRootPath}` and no template extension is found for the `webtv` namespace then the validation is skipped.

> Actually, I have annotated the WebtvNamespace class with @TemplateExtension(namespace = 'webtv'), so withRootPath should be a namespace extension method, shouldn't be?

Yes, but it seems that those extension methods are not discovered at all...

**Comment by mkouba** [comment]
> > Actually, I have configured the generation of the Jandex index for the common module...
> 
> Ok, let me check the reproducer...

You're right. An empty `beans.xml` does the trick. The index only helps if the archive also contains at least one class annotated with bean defining annotation or a CDI qualifier/interceptor binding.

**Comment by dscoppelletti** [comment]
Wow! I've added the empy `beans.xml` and everthing goes OK!  
Thank you very much.
