### ISSUE TITLE
Using ZipProjectWriter with CreateProject, Projects should be generated in a folder 

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#3340]
This issue was reported on the launcher https://github.com/fabric8-launcher/launcher-quarkus/issues/65 by @jclingan 

When unzipping a project, the contents are extracted into the current directory. Example:

```
$ unzip -t my-app.zip
Archive:  my-app.zip
    testing: src/main/java/           OK
    testing: src/test/java/           OK
    ...
```
Project content should be extracted into a folder based on the project name:
```
$ unzip -t my-app.zip
Archive:  my-app.zip
    testing: my-app/src/main/java/           OK
    testing: my-app/src/test/java/           OK
    ...
```

**Comment by gsmet** [comment]
@ia3andy isn't this one solved for a long time?

**Comment by ia3andy** [comment]
@gsmet no it's only solved on Code Quarkus. I started something with common zip and need some time to complete it. I am adding it to my task list..

**Comment by ia3andy** [comment]
I will pick that one up when I start working on the codegen..

**Comment by ia3andy** [comment]
This is the related codegen issue:
https://github.com/quarkusio/quarkus/issues/8178

I intend to remove the `ZipProjectWriter`  and instead provide a way to zip/unzip a project folder (when it's already generated).

**Comment by ia3andy** [comment]
Finally done: https://github.com/quarkusio/quarkus/pull/9631

Instead of having a `ZipProjectWriter` we now have a `QuarkusProjectCompress#zip` able to zip any existing Quarkus project.
