### ISSUE TITLE
Quarkus Website tooltip shows quarkus 2 for quarkus 3 parts

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#33408]
### Discussed in https://github.com/quarkusio/quarkus/discussions/32955

<div type='discussions-op-text'>

<sup>Originally posted by **bulldog98** April 27, 2023</sup>
![grafik](https://user-images.githubusercontent.com/314259/234867252-db47270e-3d9f-42fd-94bd-48ab278331ae.png)
</div>

**Comment by gsmet** [comment]
I fixed the issue, it will be deployed in ~15 minutes. Thanks!
