### ISSUE TITLE
OpenTelemetry custom SpanProcessor doesn't work in native mode

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#33407]
### Discussed in https://github.com/quarkusio/quarkus/discussions/33349

<div type='discussions-op-text'>

<sup>Originally posted by **amoscatelli** May 14, 2023</sup>
Hi guys !
Are OpenTelemetry SpanProcessor 's supported by current quarkus integration ?
When I run locally everything works when using extra/custom SpanProcessor, when I compile in native mode and deploy on kubernetes I see the SpanProcessor is correctly called, I see no errors but no spans are exported.

```java
import io.opentelemetry.context.Context;
import io.opentelemetry.sdk.trace.ReadWriteSpan;
import io.opentelemetry.sdk.trace.ReadableSpan;
import io.opentelemetry.sdk.trace.SpanProcessor;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class EndUserSpanProcessor implements SpanProcessor {

    @Override
    public void onStart(Context parentContext, ReadWriteSpan span) {
        System.out.println("HELLO!");
    }

    @Override
    public boolean isStartRequired() {
        return Boolean.TRUE;
    }

    @Override
    public void onEnd(ReadableSpan span) {
    }

    @Override
    public boolean isEndRequired() {
        return Boolean.TRUE;
    }

}

```

I also tried with this official example : 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/src/main/java/com/example/javaagent/DemoSpanProcessor.java

Thanks in advance</div>

Of course we are talking about Quarkus 3.
Also I underline the issue is for native mode only, in JVM mode everything works out.
To reproduce the issue an empty/do-nothing SpanProcessor should be enough (like the one above).

Please tell me if you need more information.

Thank you in advance.

PS :
The issue is "spans are not sent to the trace endpoint when registering any application scoped custom SpanProcessor".
Sadly no error is shown and spans stop showing up on the otel backend.
When removing the custom SpanProcessor everything starts working again.

**Comment by geoand** [comment]
What exactly does not work?

**Comment by amoscatelli** [comment]
> What exactly does not work?

Sorry for missing a concise description of the issue.
I added such information in the post scriptum.

**Comment by geoand** [comment]
I tried this and the problem occurs both in native and JVM mode. I am looking into a fix now.

**Comment by antoniordz96** [comment]
Hey does anyone have a working example of this? We are adding a SpanProcessor but are not seeing it be picked up. We are not doing native but jvm mode.

Sampe processor

```java
package com.company.ccoe.sample;

import io.opentelemetry.context.Context;
import io.opentelemetry.sdk.trace.ReadWriteSpan;
import io.opentelemetry.sdk.trace.ReadableSpan;
import io.opentelemetry.sdk.trace.SpanProcessor;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class CustomSpanProcessor implements SpanProcessor {

    @Override
    public void onStart(Context parentContext, ReadWriteSpan span) {
        span.setAttribute("domain", "developer experience");
        span.setAttribute("region", "us-east-1");
    }

    @Override
    public boolean isStartRequired() {
        return false;
    }

    @Override
    public void onEnd(ReadableSpan readableSpan) {

    }

    @Override
    public boolean isEndRequired() {
        return false;
    }


}
```

**Comment by brunobat** [comment]
@antoniordz96 can you please post a question on [discussions](https://github.com/quarkusio/quarkus/discussions)?
