### ISSUE TITLE
quarkus:update not working on Windows when project is without mvnw

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33403]
### Describe the bug

`quarkus:update` not working on Windows when project is without mvnw

We this thanks to https://github.com/quarkus-qe/quarkus-startstop testsuite

Log output from GH actions based run:
```
[INFO] Executing:
C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.7\bin\mvn.cmd -e org.openrewrite.maven:rewrite-maven-plugin:4.43.0:run -D"plainTextMasks=**/src/main/codestarts/**/*.java,**/*.txt,**/META-INF/services/**,**/*.adoc,**/src/test/resources/__snapshots__/**/*.java,**/*.kt,**/*.md" -D"rewrite.configLocation=C:\Users\RUNNER~1\AppData\Local\Temp\quarkus-project-recipe-17955793016890682862.yaml" -D"activeRecipes=io.quarkus.openrewrite.Quarkus" -D"rewrite.pomCacheEnabled=false"
[INFO] 
[ERROR] =**/src/main/codestarts/**/*.java was unexpected at this time.
```

I'm able to reproduce this on sample app from code.quarkus (just with mvnw related bits removed and changed Quarkus version to 3.0.2.Final)

<img width="674" alt="Capture" src="https://github.com/quarkusio/quarkus/assets/925259/55875dc1-3279-448e-8969-f14c5bc74da8">

### Expected behavior

Update works without fail

### Actual behavior

Update procedure fails

### How to Reproduce?

 - Get sample app from https://code.quarkus.io/
 - Remove mvnw related bits from the project
 - Changed Quarkus version to 3.0.2.Final so the full update procedure is triggered
 - run `mvn quarkus:update`

`[ERROR] =**/src/test/resources/__snapshots__/**/*. java was unexpected at this time.` can be seen in the log

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 3.0.2.Final

**Comment by rsvoboda** [comment]
CC @ia3andy @gsmet

**Comment by gsmet** [comment]
@rsvoboda any chance someone from the QE team could try https://github.com/quarkusio/quarkus/pull/34056 with various Windows shells (cmd, git-bash, Powershell)?

**Comment by rsvoboda** [comment]
We are quite busy this week, will next week work for you @gsmet? Probably Tue or Wed.

**Comment by gsmet** [comment]
Sure!

**Comment by rsvoboda** [comment]
@gsmet, I tried this on Windows 10 using `cmd`, `powershell`, and `cmder`. The issue I reported in https://github.com/quarkusio/quarkus/issues/33403 is fixed by the https://github.com/quarkusio/quarkus/pull/34056.

Tried updates on a sample project with and without mvnw related bits. Also tried on macOS to check for regressions on a platform which was working fine

**Comment by rsvoboda** [comment]
Closing, https://github.com/quarkusio/quarkus/pull/34056 is merged
