### ISSUE TITLE
GraphQL / Jaeger test scenario failure after #33301

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33412]
### Describe the bug

I see GraphQL / Jaeger test scenario failure after https://github.com/quarkusio/quarkus/pull/33301

Test is located in https://github.com/quarkus-qe/quarkus-jdkspecifics repository
Link to the test: https://github.com/quarkus-qe/quarkus-jdkspecifics/blob/main/jdk17/graphql/src/test/java/io/quarkus/ts/http/graphql/TracingIT.java#L49

CC @jmartisk @mskacelik 

Test can be executed using `mvn clean verify -Dit.test=TracingIT -f jdk17/graphql`. It assumes 2 spans to be present, but 0 is received.

There is no breaking change label or noteworthy label on the #33301 PR, nothing in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1

### Expected behavior

TracingIT passes

### Actual behavior

TracingIT fails

### How to Reproduce?

 - build latest Quarkus main
 - clone https://github.com/quarkus-qe/quarkus-jdkspecifics repository
 - run `mvn clean verify -Dit.test=TracingIT -f jdk17/graphql`

Run `mvn clean verify -Dquarkus.platform.version=3.0.2.Final -Dit.test=TracingIT -f jdk17/graphql` to see old behaviour / test passes.

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by jmartisk** [comment]
We've replaced support for OpenTracing with support for OpenTelemetry, that is the reason. Would you be able to update the test to work with OTel?

**Comment by rsvoboda** [comment]
Hi @jmartisk. We will update the test scenario. The bigger problem imho is the end user impact.

There is no breaking change label or noteworthy label on the https://github.com/quarkusio/quarkus/pull/33301 PR, nothing in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1

This move needs to be well communicated describing the implications and idealy with some steps how to adjust the applications.

**Comment by jmartisk** [comment]
You're right, I'll write up something in the migration guide.
We didn't consider it very important because the OpenTracing support was quite broken anyway, so I don't think people were really turning it on with GraphQL.

**Comment by rsvoboda** [comment]
You never know, at least now you now that the qe team was testing that and we see failures on 2 test suites :)

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.1#smallrye-graphql was added, closing the issue.
