### ISSUE TITLE
Log a warning when transactional observers are used

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#3341]
Transactional observers are not supported yet. We should log a warning when a transactional observer is used.

We should also update the guide and mention the missing feature in the "Limitations" chapter.

**Comment by mkouba** [comment]
For the record - there's an open issue to implement transactional observers:
https://github.com/quarkusio/quarkus/issues/2224

**Comment by machi1990** [comment]
Hi @mkouba I’d like to take a look at this over the weekend.
