### ISSUE TITLE
Quarkus redis reactive pubsub disconnecting handler

### ISSUE THREAD

**Issue by silviu-negoita** [quarkusio/quarkus#33418]
### Describe the bug

I have the following code:
```
ReactiveRedisDataSource redis; -> Injected
ReactivePubSubCommands<String> pubsub = redis.pubsub(String.class);
pubsub.subscribe('my-channel')
                .onItem().call(this::consume)
                .subscribe().with(
                        notificationId -> log.debug("New notification has been processed {}", notificationId),
                        err -> log.error("Error while listening for new notifications ", err));
```

Everything is working fine, I receive data via the subscription, but for some reason, after a while (days, weeks), my subscription is gone. It can be checked by running in redis the folowing command:
```
PUBSUB NUMSUB my-channel
```
Initially returns 1, but when my issues occurs, it is going to 0. No other failures can be seen in the application. 

It is very easy to reproduce the issue:
1. Connect via the code above to a redis docker instance.
2. Check `PUBSUB NUMSUB my-channel -> 1`
3. Stop redis container
4. Start redis container
5. Now `PUBSUB NUMSUB my-channel -> 0` and no errors thrown in code.

**How can I watch the disconnected state to be able to manually reconnect?** I tried to add handlers like `onTermination`, `onCanncelation`, `onFailure`, `onCompletion` but they are never triggered. 

An undesired solution is to use 
```
pubsub.Uni<ReactiveRedisSubscriber> subscribe(String channel, Consumer<V> onMessage, Runnable onEnd,
            Consumer<Throwable> onException);
```

I noticed that when my redis connection is going down, it triggers `onEnd` handler.

But this cuts my reactivity in the process for consuming the event. I want to use `pubsub.Multi<V> subscribe(String... channels)`

### Quarkus version or git rev

2.14.3.Final

**Comment by geoand** [comment]
The only way to know is to try 😉.

The reason we ask is because there are regularly fixes across the board

**Comment by silviu-negoita** [comment]
@geoand so I updated to quarkus 3.0.3. After fixing a loot of issues, now I am stuck into this: ` java.lang.IllegalStateException: No current Vertx context found` . 

This is because I really don't have a vertx context, because Im trying to interact with the DB from a GCP pubsub receiver(no rest call). Before Quarkus 3.xx, I used `@ActivateRequestContext` to manually activate the context to be able to manipulate the DB.  

Is there another approach for this new version? :( 


P.S. I am using reactive approach - resteasy and panache reactive.

**Comment by silviu-negoita** [comment]
@geoand So after updating the quarkus, I tested again just t by adding these lines:
```
pubsub.subscribe('my-channel')
                .onItem().call(this::consume)
                .onTermination().invoke(() -> log.info("please do smt"))
                .onFailure().invoke(() -> log.info("please do smt"))
                .onCompletion().invoke(() -> log.info("please do smt"))
                .onCancellation().invoke(() -> log.info("please do smt"))
                .subscribe().with(
                        notificationId -> log.debug("New notification has been processed {}", notificationId),
                        err -> log.error("Error while listening for new notifications ", err));

```

And after simulating a redis downtime, I still dont see any of the logs above. Any other suggestions? What am I missing?

**Comment by geoand** [comment]
> Is there another approach for this new version? :(

No, the same approach can be used

**Comment by geoand** [comment]
> And after simulating a redis downtime, I still dont see any of the logs above. Any other suggestions? What am I missing?

Without running the code, it's hard to tell. Can you attach a sample that behaves as you describe?

**Comment by cescoffier** [comment]
Updating to 3 won't help unfortunately. I didn't change anything on that area.
