### ISSUE TITLE
Quarkus MongoDB Client: Connect to multiple MongoDB clusters from the same app

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#3343]
**Description**
Reading the guide about mongo here: https://quarkus.io/guides/mongo-guide there doesn't seem to be a straightfoward way of connecting to two clusters simultaneously in the same app. 

Reading the code, I couldn't find this feature anywhere - unless I am missing something.

I would expect a configuration like the Quarkus Rest Client (https://quarkus.io/guides/mongo-guide), something maybe like:

```
quarkus.mongodb.cluster1.connection-string = mongodb://mongo1:27017,mongo2:27017
quarkus.mongodb.cluster2.connection-string = mongodb://mongo1:27017,mongo2:27017
```

And then use annotations above the instances of MongoClient to indicate which instance we are going to use (example imaginary `@Connection` annotation used):

```
@Connection("cluster1")
@Inject
ReactiveMongoClient mongoClientCluster1
```

**Comment by gsmet** [comment]
Yes, that would be doable. A good example of that is the `agroal` extension where we support multiple datasources.

I think it's a good issue for a beginner as the `agroal` extension should . Would you be interested in taking a look at it?

**Comment by MMarus** [comment]
@gsmet @csotiriou Hello guys is someone working on this? Could I take a stab at this one? Thank you for the answer :).

**Comment by csotiriou** [comment]
I will not be able to touch this for at least a month, due to heavy workload, so at least from my part I am not working on it.

**Comment by geoand** [comment]
@MMarus I don't see anyone assigned to it or anyone mention they are working on it, so if you would like to take it up, feel free :)

**Comment by MMarus** [comment]
@geoand Great, thank you very much :).

**Comment by dufoli** [comment]
hello, I have start to work on this one. It was pretty complicated because I do not understand all the concept in quarkus right now. But I have start to work on it. How Can I tag my branch to this bug and get some help ?

**Comment by dufoli** [comment]
here is the branch https://github.com/dufoli/quarkus/tree/mongo-cluster

**Comment by geoand** [comment]
Hi, you can create a draft Pull Request where you mention that it fixes this issue.
In that PR you describe the details of what you need help with, what might not be working currently, what you think the limitations of your approach are etc.

**Comment by dufoli** [comment]
I have commit and send the draft PR with some fixes.
I just need help to fix one remaining test because error is really strange to me.
CollectionManagementTest

**Comment by dufoli** [comment]
I need review and help to format. Because it seems to be ok now( all test pass) but failing on code format....

**Comment by dufoli** [comment]
@gsmet @geoand why not reuse Datasource attribute of agroal instead of new attribute connection to name the connection ?

**Comment by geoand** [comment]
@dufoli I haven't really been involved in the data source stuff so I don't have an opinion I'm afraid.

**Comment by geoand** [comment]
@dufoli I am personally super short on time right now so I can't promise I'll do a review soon. Sorry...

**Comment by loicmathieu** [comment]
@dufoli I will make a review, I hope today. But maybe a second reviewer will be needed ...
