### ISSUE TITLE
Cannot generate Quarkus GRPC code from proto

### ISSUE THREAD

**Issue by drsarutobi8** [quarkusio/quarkus#33452]
### Describe the bug

when I upgrade from quarkus 2.16.6-Final to 3.0.3.Final the gradle reports error.

### Expected behavior

Build Successful

### Actual behavior

* What went wrong:
Execution failed for task ':module1:quarkusGenerateCode'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.CodeGenWorker
      > Failed to generate sources in the QuarkusPrepare task for testProject:module1:unspecified due to java.lang.reflect.InvocationTargetException

After run with --stacktrace it shows:
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.gradle.tasks.worker.CodeGenWorker.execute(CodeGenWorker.java:66)
        ... 22 more
Caused by: io.quarkus.bootstrap.prebuild.CodeGenException: 
 Failed to generate Java classes from proto files: [ .... ]] to
 /home/../build/classes/java/quarkus-generated-sources/grpc with command /home/.../build/com.google.protobuf-protoc-linux-x86_64-exe -I=/home/.../build/protoc-dependencies/338b8d23adc6fe2688381c53c8ae36f231ea0a95 -I=/home/.../build/protoc-dependencies/e310c4419f6b721d6d5ad2fdefa0015835a3fa19 -I=/home/.../build/ddlcodegen-src/main/proto --plugin=protoc-gen-grpc=/home/.../build/io.grpc-protoc-gen-grpc-java-linux-x86_64-exe --plugin=protoc-gen-q-grpc=/home/.../build/quarkus-grpc6394473256610594280.sh --q-
grpc_out=/home/.../build/classes/java/quarkus-generated-sources/grpc --grpc_out=/home/.../build/classes/java/quarkus-generated-sources/grpc --java_out=/home/.../build/classes/java/quarkus-generated-sources/grpc /home/.../build/ddlcodegen-src/main/proto/warehouseEntityNameValue.proto /home/.../build/ddlcodegen-src/main/proto/docStatusEnumNameEnum.proto /home/.../build/ddlcodegen-src/main/proto/customerEntityNameService.proto /home/.../build/ddlcodegen-src/main/proto/binaryObjectEntityNameService.proto /home/.../build/ddlcodegen-src/main/proto/stationStatusEnumNameEnum.proto /home/.../build/ddlcodegen-src/main/proto/stationTypeEnumNameEnum.proto /home/.../build/ddlcodegen-src/main/proto/receiptEntityNameService.proto /home/.../build/ddlcodegen-src/main/proto
to
        at io.quarkus.grpc.deployment.GrpcCodeGen.trigger(GrpcCodeGen.java:135)
        at io.quarkus.deployment.CodeGenerator.lambda$trigger$3(CodeGenerator.java:176)
        at io.quarkus.deployment.CodeGenerator.callWithClassloader(CodeGenerator.java:151)
        at io.quarkus.deployment.CodeGenerator.trigger(CodeGenerator.java:173)
        at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:63)

### Output of `uname -a` or `ver`

Linux mrwhite 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2) OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.7 (Private Build 17.0.7+7-Ubuntu-0ubuntu122.04.2) OS:           Linux 5.19.0-41-generic amd64

**Comment by drsarutobi8** [comment]
Sorry, I find that this is not a bug. I put the different versions of quarkusPluginVersion and quarkusPlatformVersion and caused the problem.
Thank you

**Comment by geoand** [comment]
Thanks for the update
