### ISSUE TITLE
quarkus-resteasy-jackson needed

### ISSUE THREAD

**Issue by cg-d** [quarkusio/quarkus#3345]
**Description**
Please provide a configuration dependency to use jackson as object mapper instead of json-b.
The reason for this is the superior support for Kotlin data classes in jackson. Using jackson-module-kotlin jackson can directly marshal data classes w/o a no args constructor.

**Comment by gsmet** [comment]
So this was a conscious decision but I started a thread on the quarkus-dev mailing list to see if we should revisit it.
