### ISSUE TITLE
Upgrade vertx to 4.4.* to allow TLS Server certificate rotation without restarts

### ISSUE THREAD

**Issue by pierDipi** [quarkusio/quarkus#33468]
### Description

I'm interested in creating a Vert.x server that updates TLS certificates without restarts using the new Vert.x feature implemented in https://github.com/eclipse-vertx/vert.x/commit/f288f356bcdd9a03273cd1bb9c46b9a720d604c6 and documented at https://vertx.io/docs/vertx-core/java/#_updating_ssltls_configuration

The feature is available with Vertx 4.4 but the current Vertx version for Quarkus is 4.3.

### Implementation ideas

Upgrade vertx to 4.4.2

**Comment by sberyozkin** [comment]
CC @cescoffier

**Comment by cescoffier** [comment]
PR opened already.

**Comment by pierDipi** [comment]
Thank you!

**Comment by pierDipi** [comment]
ref: https://github.com/quarkusio/quarkus/pull/33416

**Comment by pierDipi** [comment]
@cescoffier the plan it to include it in Quarkus 3.1.0 ?

**Comment by cescoffier** [comment]
Yes. If the PR gets merge in time. It's marked for backport.
