### ISSUE TITLE
ReactiveMongoClient is always null. Plain MongoClient works.

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#3346]
I am using MongoDB client in quarkus 0.19.1.

I have started my database using docker, and put this in my `application.properties`:

```
quarkus.mongodb.connection-string = mongodb://localhost:27017
```

Then, in my resource, I have put:
```    
@Inject ReactiveMongoClient appMongo;
```
It seems that `ReactiveMongoClient` is always null. If I change `ReactiveMongoClient` to `MongoCient`, however, the instance is instantiated properly.

That renders `ReactiveMongoClient` unable to be used. Is there any additional setup needed for `ReactiveMongoClient` compared to the plain `MongoClient`?

**Comment by gsmet** [comment]
I don't think you need some special configuration. They are initialized the same way.

Could you prepare a reproducer?

**Comment by csotiriou** [comment]
@gsmet I will do it later today, but I searched a bit deeper into the issue and I would like to show you my findings.

I found that the `MongoClient` and the `ReactiveMongoClient` have a difference as to when they are instantiated and called for the first time.

This piece of code in the `MongoClientProducer` is called only once.

```
    @Singleton
    @Produces
    public MongoClient client() {
        return this.client;
    }

    @Singleton
    @Produces
    public ReactiveMongoClient axle() {
        return this.reactiveMongoClient;
    }
```

This piece of code in the `MongoClientRecorder` is also called once per application run.

```
 public RuntimeValue<MongoClient> configureTheClient(MongoClientConfig config, BeanContainer container, LaunchMode launchMode, ShutdownContext shutdown, List<String> codecProviders) {
        this.initialize(config, codecProviders);
        MongoClientProducer producer = (MongoClientProducer)container.instance(MongoClientProducer.class, new Annotation[0]);
        producer.initialize(client, reactiveMongoClient);
        if (!launchMode.isDevOrTest()) {
            shutdown.addShutdownTask(this::close);
        }

        return new RuntimeValue(client);
    }

    public RuntimeValue<ReactiveMongoClient> configureTheReactiveClient() {
        return new RuntimeValue(reactiveMongoClient);
    }
```

However, in the case of the `ReactiveMongoClient`, the `configureTheClient()` is called *after* the initial call to the `axle()` method. The `axle()` method returns a null object, this object is cached because of the `@produces` annotation, and but the `ReactiveMongoClient` is initialized after the initial call.

This is not the case with the plain MongoClient, and this is the reason for the failure I believe.

**Comment by geoand** [comment]
When using `@Inject`, you shouldn't normally get a `null` value, so this is very weird. As @gsmet said, a reproducer would go a long way to enable us to track down the issue.

Thanks

**Comment by csotiriou** [comment]
@geoand @gsmet thanks for your help. As the problem is not noticeable in new projects, I have only a closed-source project where this happens.

I will try to play with its dependencies and code, and provide you with a new open source project where the problem is apparent.

**Comment by csotiriou** [comment]
I finally managed to properly reproduce the problem in the project attached.

[quark.zip](https://github.com/quarkusio/quarkus/files/3438123/quark.zip)

Ways to reproduce:

1. `cd` into the project
2. do an `mvn compile quarkus:dev`

The project will fail to start.

In the `MongoProducer`, you can remove the `@Provider` from the `produceAssetDatabase()` method. The project will then start normally.

It seems to me that if we use `@Producer`, it tries to access the injected `MongoClient` before it has had the chance to be initialized and used. As it turned out, this is indeed the case with both MongoClient and its reactive counterpart.

I really don't know if this is a bug, or if I use `@Produces` and `@Inject` the wrong way (because it seems like an issue with the priority with which these two dependencies are resolved)

**Comment by geoand** [comment]
Thanks @csotiriou, I'll try and take a look soon

**Comment by geoand** [comment]
@csotiriou unless I am missing something you are not using CDI correctly. When I change your code to:

```
@ApplicationScoped
public class MongoProducer {

    @Produces
    public ReactiveMongoDatabase produceAssetDatabase(ReactiveMongoClient mongoClient) {
        return mongoClient.getDatabase("test");
    }
}
```

and 

```
@Path("/api")
public class GreetingResource {

    @Inject
    ReactiveMongoDatabase reactiveMongoDatabase;

    @GET
    @Path("/dbName")
    @Produces(MediaType.TEXT_PLAIN)
    public String dbName() {
        return reactiveMongoDatabase.getName();
    }
}

```

then by starting the (`mvn quarkus:dev` or vanilla `java -jar`) and hitting `http://localhost:8080/apid/bName` correctly gives me `test`.

So I am going to take the liberty and close this issue. If you feel it hasn't be resolved, feel free to reopen and provide your thoughts

**Comment by csotiriou** [comment]
@geoand I now see what I was missing. Thanks a lot, my issue is probably invalid, thanks for the patience.

**Comment by geoand** [comment]
Don't mention it 😎
