### ISSUE TITLE
Livereload doesn't work for AMQP reactive messaging

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#3347]
**Describe the bug**
I follow the AMQP guide (https://quarkus.io/guides/amqp-guide) and the livereload was not working. When I update one of my classes I need to restart Quarkus.

**Expected behavior**
Livereload avoid restarting Quarus for each source modification.

**To Reproduce**
1. Follow the guide
2. Send a message (I use Artemis admin console to send a message)
3. Update one source file
4. Send a message

**Configuration**
```properties
# Configures the AMQP broker credentials.
amqp-username=quarkus
amqp-password=quarkus

# Configure the AMQP connector to read from the `carte-cadeau-creation` queue
mp.messaging.incoming.carte-cadeau-creation.connector=smallrye-amqp
mp.messaging.incoming.carte-cadeau-creation.durable=true

# Configure the AMQP connector to read from the `carte-cadeau-transaction` queue
mp.messaging.incoming.carte-cadeau-transaction.connector=smallrye-amqp
mp.messaging.incoming.carte-cadeau-transaction.durable=true

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.3" 2019-04-16
 - Quarkus version or git rev: 0.19.1

**Comment by geoand** [comment]
Last I knew, this was expected (since the live-reload is triggered on incoming http requests). @stuartwdouglas, @cescoffier has anything changed in that area?

**Comment by loicmathieu** [comment]
@geoand I saw that a PR will provides hot replacements for kafka-stream (#3500) so if a messaging technology provides live reload I think all should provides it.

**Comment by gsmet** [comment]
Sure, that would be the ultimate goal. But for now, I think only HTTP and soon Kafka Streams are supported.

**Comment by geoand** [comment]
Yeah, the live reload for Kafka looks really Kafka specific at this point

**Comment by loicmathieu** [comment]
I still think that we should provides live reload for all reactive messaging implementation: AMQP, MQTT and Kafka.

**Comment by gsmet** [comment]
I generalized this older issue for reactive messaging: https://github.com/quarkusio/quarkus/issues/3217 .

Closing this one as duplicate.
