### ISSUE TITLE
Warning message if quarkus.oidc.application-type=service

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#33475]
### Describe the bug

I got the warning message:

> Secret key for encrypting tokens is missing, auto-generating it

despite `quarkus.oidc.application-type=service` and I am not using cookies.

https://github.com/quarkusio/quarkus/blob/0e63bfcfc468a48081c0ed54771d37ea75bcec3b/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/TenantConfigContext.java#L77-L78

### Quarkus version

3.0.2.Final

### Workaround

Set `quarkus.oidc.token-state-manager.encryption-required=false`

**Comment by sberyozkin** [comment]
I'll need to fix it now
