### ISSUE TITLE
Request body verification not working correctly

### ISSUE THREAD

**Issue by MarkusKramer** [quarkusio/quarkus#33482]
### Describe the bug

After updating from Quarkus 2.10 to 3.0.3 the request body validation no longer seems to work correctly.

I have an endpoint like this:
```
    @POST
    @Path("login")
    suspend fun login(request: LoginRequest): LoginResponse {
        log.debug("Login requested for '${request.email}'")
        ...
```
with the LoginRequest.kt being:
```
@Serializable
data class LoginRequest constructor(
    val email: String,
    val passwordHash: String
)
```

An empty request body now leads to a NullPointerException in the log.debug line. However, there are no nullable types used.
If an attribute is missing I see an exception like "kotlinx.serialization.MissingFieldException: Fields [email, passwordHash] are required for type with serial name ..." and the client is getting a HTTP 500 response when it should be a 4xx bad request response.

Tested as native image. Using
 * quarkus-kotlin
 * quarkus-resteasy-reactive
 * quarkus-resteasy-reactive-kotlin-serialization

### Quarkus version or git rev

3.0.3

**Comment by geoand** [comment]
Closing as we did not did not get a reproducer
