### ISSUE TITLE
[CreateProject] Empty directory levels in zipped archive

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#3348]
**Describe the bug**
This bug has initially been created by @johnaohara:
https://github.com/fabric8-launcher/launcher-quarkus/issues/39

The created Zip archive contains additional directory levels, e.g. `/src/main/java//org/example//QuarkusApp.java`, or `/src/test/java//org/example//QuarkusAppTest.java`.

When the file is unzipped, the directory structures appear to be created correctly. Browsing the archive with an archive manage lookes like we have emtpy directories

**Expected behavior**
No extra directory level

**To Reproduce**
1. Create a zip project
2. List zip content

**Comment by ia3andy** [comment]
@gsmet I've noticed it too, that could be the source of the Windows bug no?
https://github.com/quarkusio/quarkus/issues/3339

**Comment by geoand** [comment]
@ia3andy Has this been fixed perhaps in `master`?

**Comment by ia3andy** [comment]
@geoand yes!!
