### ISSUE TITLE
Quarkus 3.0.3 - Kubernetes client exception => ERROR Max frame length of 65536 has been exceeded

### ISSUE THREAD

**Issue by YvesZelros** [quarkusio/quarkus#33494]
### Describe the bug

Kubernetes client failed on Kubernetes ressources with size that extend 65K =>
` ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) Max frame length of 65536 has been exceeded.`

Root cause is on the library **fabric8io/kubernetes-client**

A fix is already merged =>
https://github.com/fabric8io/kubernetes-client/pull/5047/files#diff-186abf5859513fd0ce0d19d3748f6c5de9f965e7827eda007cdd3d18e0a36caeR70

Please update the version of **fabric8io/kubernetes-client** to 6.6.2 

### Expected behavior

Allow to read Kubernetes objects of any size

### Actual behavior

Object with a size that exceed 65536 bytes fail

### How to Reproduce?

Read a big Kubernetes object like a CRD.

### Output of `java -version`

17.0.7

### GraalVM version (if different from Java)

Not use

### Quarkus version or git rev

3.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by geoand** [comment]
Quarkus `3.1.0.CR1` has already updated to 6.6.2

**Comment by geoand** [comment]
Please open a new issue providing as much detail as you can and we will look into it
