### ISSUE TITLE
The `ConfigValue` instance for `quarkus.otel.sdk.disabled` is null during relocation

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#33493]
While porting our Strimzi HTTP bridge from Quarkus 2.x to 3.x, I found a potential issue around the `quarkus.otel.sdk.disabled` property.

Let me set the use case first ... with Quarkus 2.x.
In our bridge we are currently using a `bridge.tracing=opentelemetry` property to enable/disable OpenTelemetry. We know that it's not possible enable/disable tracing at runtime with Quarkus 2.x and together with @brunobat we came with a workaround about just disabling the sampler to avoid sending traces. It was done by using a configuration relocator interceptor like this one [here](https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/config/BridgeRelocateConfigInterceptor.java#L79). The relocator purpose is to take backward compatibility (user still needs to set or not `bridge.tracing` property).

When moving to Quarkus 3.x we have the `quarkus.otel.sdk.disabled` property which allows to enable/disable tracing at runtime so the "sampler" workaround is not needed anymore.
Following the same logic I was going to relocate that property via our own `bridge.tracing` but when the following snippet of code runs, the `quarkus.otel.sdk.disabled`  result to be null.

```java
ConfigValue original = context.proceed("quarkus.otel.sdk.disabled");
```

I am just following the same logic as before but using the `quarkus.otel.sdk.disabled`  instead of the `quarkus.opentelemetry.tracer.sampler` which is not null and works fine.

**Comment by brunobat** [comment]
I'm not sure I follow. 
Will `quarkus.otel.sdk.disabled` not disable the OTel SDK?
Where is this snippet? `ConfigValue original = context.proceed("quarkus.otel.sdk.disabled");`
In the service code? At which point? Do you have a reproducer?

**Comment by ppatierno** [comment]
I haven't pushed the code yet, I will do soon but if you follow the link I pasted before, so this one https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/config/BridgeRelocateConfigInterceptor.java#L79 and replace `quarkus.opentelemetry.tracer.sampler` with `quarkus.otel.sdk.disabled`, the line with `ConfigValue original = context.proceed("quarkus.otel.sdk.disabled");` return null.

**Comment by ppatierno** [comment]
FYI I pushed the code.
The code where this is happening is here https://github.com/ppatierno/strimzi-kafka-bridge/blob/road-to-quarkus/src/main/java/io/strimzi/kafka/bridge/config/BridgeRelocateConfigInterceptor.java#L73
