### ISSUE TITLE
Warning:  Corrupted channel by directly writing to native stream in @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#33507]
### Describe the bug

All native test of `quarkus-artemis` produce a warning after test execution, e.g. [here (`github.com`)](https://github.com/quarkiverse/quarkus-artemis/actions/runs/5029160470/jobs/9020540336#step:5:614):
```
Warning:  Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/quarkus-artemis/quarkus-artemis/integration-tests/core/empty-config/target/failsafe-reports/2023-05-19T23-41-12_048-jvmRun1.dumpstream
```

### Expected behavior

No warning should occurr

### Actual behavior

Warning occurrs

### How to Reproduce?

Reproducer:

- checkout `quakrus-artemis`:
  ```bash
  git clone https://github.com/quarkiverse/quarkus-artemis.git
  cd quarkus-artemis
  git fetch --all
  git checkout feature/maven/quarkus.version-3.1.0.CR1
  ```
- build and test one of the integration-test modules:
  ```bash
  ./mvnw \
    --file integration-tests/core/empty-config/pom.xml \
    --also-make \
    --define native \
    --define native.surefire.skip \
    clean verify
  ```
- observe the warning.

### Output of `uname -a` or `ver`

Linux xxx 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### GraalVM version (if different from Java)

mandrel 22.3.2.1-java17

### Quarkus version or git rev

3.1.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

Pipeline-artifacts form the pipeline-run above: [test-report-native.zip](https://github.com/quarkusio/quarkus/files/11521173/test-report-native.zip)

**Comment by geoand** [comment]
This has already been fixed in `main` by #33432 and the fix should be available with the Final release.
