### ISSUE TITLE
org.eclipse.microprofile.config.spi.Converter implementations not found

### ISSUE THREAD

**Issue by jayr33n** [quarkusio/quarkus#33500]
I am trying to add a custom `org.eclipse.microprofile.config.spi.Converter` implementation in an empty `Quarkus 3.0.3.Final` application following this guide
https://quarkus.io/guides/config-extending-support#custom-converter

`CustomConverter.java`
```
package com.example;

import org.eclipse.microprofile.config.spi.Converter;

public class CustomConverter implements Converter<Integer> {
    @Override
    public Integer convert(String value) throws IllegalArgumentException, NullPointerException {
        return 0;
    }
}
```

`resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter`
```
com.example.CustomConverter
```

However when executing `./mvnw clean test` the build fails and outputs:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.3.Final:generate-code (default) on project grpc-demo-quarkus: Quarkus code generation phase has failed: InvocationTargetException: org.eclipse.microprofile.config.spi.Converter: Provider com.example.CustomConverter not found -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Expected behavior

Build should not fail and the `CustomConverter` class should be found.

### Actual behavior

Build fails.

### How to Reproduce?

1. Create a new `Quarkus 3.0.3.Final` application
2. Add `CustomConverter.java` under the `com.example` package
```
package com.example;

import org.eclipse.microprofile.config.spi.Converter;

public class CustomConverter implements Converter<Integer> {
    @Override
    public Integer convert(String value) throws IllegalArgumentException, NullPointerException {
        return 0;
    }
}
```
3. Add a file named `org.eclipse.microprofile.config.spi.Converter` under `resources/META-INF/services/` with the following content:
```
com.example.CustomConverter
```
4. Execute `./mvnw clean test`

### Output of `uname -a` or `ver`

Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by geoand** [comment]
I just tried this and it works just fine.

Please attach a sample application that exhibits the problem you are describing

**Comment by geoand** [comment]
Closing as we did not get a reproducer
