### ISSUE TITLE
CLI - docker build with jib doesn't work with Windows PowerShell

### ISSUE THREAD

**Issue by ygyg70** [quarkusio/quarkus#33508]
### Describe the bug

Building container image using Quarkus CLI works with Windows Command Prompt and doesn't work with PowerShell

### Expected behavior

To be able to execute all Quarkus CLI commands using Windows PowerShell

### Actual behavior

When I run 
`quarkus build "-Dquarkus.container-image.build=true"`

I get the following error:
`[ERROR] Unknown lifecycle phase ".container-image.build=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]`

### How to Reproduce?

1. Create a startup quarkus project
2. Add jib extension: ` quarkus extension add 'container-image-jib'`
3. Run build: `quarkus build "-Dquarkus.container-image.build=true"`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1702]

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by maxandersen** [comment]
It should print out what command it executes - can you paste those lines?

Thx.

**Comment by ygyg70** [comment]
This is the full console output:
`quarkus build "-Dquarkus.container-image.build=true"      
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.acme:testdocker >-------------------------
[INFO] Building testdocker 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.968 s
[INFO] Finished at: 2023-05-20T23:19:37-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".container-image.build=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-s
ources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
`

**Comment by famod** [comment]
Have you tried single quotes instead of double quotes?

**Comment by ygyg70** [comment]
I did try single quotes, same result

**Comment by ygyg70** [comment]
Issue resolved of container group and container name are explicitly configured
