### ISSUE TITLE
@AroundInvoke method in custom interceptor not called

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#33506]
### Describe the bug

I created a custom annotation with a boolean field
```
@Inherited
@InterceptorBinding
@Retention(RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface MyAnnotation {
    boolean value() default false;
}
```

and an interceptor class with an @AroundInvoke method
```
@MyAnnotation
@Interceptor
public class MyInterceptor {
    @AroundInvoke
    Object log(InvocationContext ctx) throws Exception {
        if (ctx.getMethod().isAnnotationPresent(MyAnnotation.class)) {
            Log.info("MyAnnotation found");
        }
        boolean flag = ctx.getMethod().getAnnotation(MyAnnotation.class).value();

        Log.info("inside MyInterceptor @AroundInvoke. flag is " + flag);
        Object o = ctx.proceed();
        return o;
    }
}
```

When I now define the annotation at a service method like 
```
@MyAnnotation(value = false)
    public void serviceMethod(){...}
```

the `@AroundInvoke` method (`log(..)`) is called

However, when define the annotation (with value=true) at a service method like 
```
@MyAnnotation(value = true)
    public void serviceMethod(){...}
```
the `@AroundInvoke` method (`log(..)`) is NOT called (???)

Atm I have no idea if I have mistake in the config or if this a bug.

### Expected behavior

 `@AroundInvoke` method (`log(..)`) is called  when using `@MyAnnotation(value = true)`

### Actual behavior

 `@AroundInvoke` method (`log(..)`) is NOT called when using `@MyAnnotation(value = true)`

### How to Reproduce?

https://github.com/syr/quarkus-resteasy-postgres/blob/aroundinvoke_not_called/src/test/java/org/acme/CustomInterceptorTest.java

The test testAroundInvoke2 with same unexpected behaviour with unchanged code from from https://github.com/quarkusio/quarkus/blob/2.16/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/

**Comment by luca-bassoricci** [comment]
Probably you need  @nonbinding on your boolean value to make interceptor work. 
(https://docs.jboss.org/cdi/spec/1.0/html/interceptors.html)

**Comment by syr** [comment]
> Probably you need @nonbinding on your boolean value to make interceptor work. (https://docs.jboss.org/cdi/spec/1.0/html/interceptors.html)

Thanks man, this was solving it. This problem was driving me crazy. I guess I need to study the spec, as that's not really intuitive when not having the spec in the head alredy
