### ISSUE TITLE
Package application to an Azure Function

### ISSUE THREAD

**Issue by DominiqueClaes** [quarkusio/quarkus#33525]
### Describe the bug

We were on the process to upgrade our existing Quarkus application from version 2.16.3 to 3.0.3. The application is build so that it can be deployed as an Azure Function. The issue is that an uber-jar is no longer created. It seems that the issue is caused by the following Maven dependency which did work in version 2.16.3.Final:

`<dependency>
   <groupId>io.quarkus</groupId>
   <artifactId>quarkus-azure-functions-http</artifactId>
   <version>3.0.3.Final</version>
</dependency>`

Even when I explicitly set the packaging to type 'uber-jar', nothing changes. Is this a known issue or is there a different implementation path?

### Expected behavior

The upgrade to Quarkus version 3.x should not break the creation of an uber JAR when used in combination with the dependency 'quarkus-azure-functions-http'.

### Actual behavior

The uber JAR is no longer created while version 2.16.3 did work.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1702]

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
cc @patriot1burke

**Comment by DominiqueClaes** [comment]
@geoand No updates?

**Comment by patriot1burke** [comment]
you do not need an uber jar for azure functions.  We force legacy jar deployment.  In general, uber jars are not good as depending on the libraries you use, the may overwrite resources, etc that have similar names.

**Comment by DominiqueClaes** [comment]
@patriot1burke Do you have an example how to create a project? The configuration for version 2.16.6.Final works but version 3.x does not. I must be missing something... Previously we had something like the added screenshot. It's packed as a zip and used by the Azure Function.

![image](https://github.com/quarkusio/quarkus/assets/5258985/69a21a61-808e-470c-b368-4981d1bc8a50)

**Comment by patriot1burke** [comment]
https://code.quarkus.io/d?e=azure-functions-http&cn=code.quarkus.io

**Comment by DominiqueClaes** [comment]
I finally had some time to implement the example but our situation is a little bit different. Our Maven run may only build the Azure Function but must not deploy the result to Azure. So our 'package' result must be like the screenshot but that's were we are missing the jar.

**Comment by patriot1burke** [comment]
azure-maven-plugin will package everything properly, including the dependencies, I'm not understanding the problem here.

**Comment by DominiqueClaes** [comment]
@patriot1burke 

I finally had some time to implement the example but our situation is a little bit different. Our Maven run may only build the Azure Function but must not deploy the result to Azure. So our 'package' result must be like the screenshot but that's were we are missing the jar.

So I just want to create the Azure Function locally but not deploy it. It's a company policy that after we build the application that additional company specific tasks need to be done on the output before we can deploy it. The deployment is done later through Azure CLI.

**Comment by patriot1burke** [comment]
The azure maven plugin supports packaging separately from deploying it, so again, I don't know what the problem is here.

**Comment by DominiqueClaes** [comment]
Ah, I believe I've found the issue. I will close this ticket... Thanks for the help!
