### ISSUE TITLE
quarkus-amazon-lambda @Inject doesn't work in JVM mode

### ISSUE THREAD

**Issue by drissamri** [quarkusio/quarkus#3354]
**Describe the bug**
@Inject of services is not working, throwing a nullpointer at runtime.

**Expected behavior**
Services are created and injected 

**Actual behavior**
No injection is happening: 
```
java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
at com.drissamri.ProductLambda.validateHealth(ProductLambda.java:39)
at com.drissamri.ProductLambda.handleRequest(ProductLambda.java:27)
at com.drissamri.ProductLambda.handleRequest(ProductLambda.java:12)
```

**To Reproduce**
1. `git clone git@github.com:drissamri/quarkus-jvm-dev-bug.git`
2. Install [Serverless Framework ](https://serverless.com/framework/docs/providers/aws/guide/installation/) for deployment to AWS
3. `mvn clean package -DskipTests`
4. `serverless deploy`
5. Invoke the outputted endpoint

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
➜  ~ uname -a
Darwin localhost 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)
```
 - Quarkus version or git rev: 
`0.19.1` 

**Additional context**
I'm unable to test this locally due to https://github.com/quarkusio/quarkus/issues/3352
Annotating the Handler class with @Singleton doesn't help. I'm pretty sure it worked in native mode.

**Comment by drissamri** [comment]
https://stackoverflow.com/questions/56620352/quarkus-aws-lambda-function-cdi-doesnt-work-in-handler-class mentions CDI only works in native mode but I'm unable to find any official reference to this?

**Comment by drissamri** [comment]
@evanchooly any idea on this one?

**Comment by evanchooly** [comment]
i'll take a look today.  it's on my list to revisit that module today.

**Comment by evanchooly** [comment]
having the serverless framework in the mix muddies the waters a bit but I'll see what I can find out.  I think they're circumventing what what the quarkus module is doing somehow.

**Comment by drissamri** [comment]
Serverless Framework only uploads the deployment package and doesn't impact any code, the same can be done with SAM CLI or CloudFormation

**Comment by drissamri** [comment]
Were you able to revisit that part @evanchooly? Does this have anything to do with the LambdaRecorder in native vs JVM mode?

**Comment by drissamri** [comment]
Which other tickets are this so I can have a look? 

Serverless Framework just invokes the handler you define just you would in AWS SAM/AWS CLI/other frameworks, so I'm afraid this is not something related to Serverless Framework?

**Comment by rkraneis** [comment]
Is there anything new? We have similar problems using ``quarkus-amazon-lambda-resteasy`` extension (NPE in ``StreamLambdaHandler`` as ``initHandler`` is not called before ``handleRequest``).

**Comment by miron4dev** [comment]
Check the handler definition, it should be `io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest`

**Comment by jkristof94** [comment]
And it really works using https://github.com/quarkusio/quarkus/issues/3354#issuecomment-555052647 this method 😮 Can you share how you got to the solution?

**Comment by evanchooly** [comment]
The docs are being updated as we speak (release pending) but here you can see the handler definition:  https://quarkus.io/guides/amazon-lambda#create-the-function

I was able to run your project using the correct handler and correcting for a bug in checking the path ( if there is no path, the healthcheck code gets an NPE ).  The `HealthCheckService` is properly injected.  Updating accordingly should get you past it.

**Comment by rsvoboda** [comment]
@evanchooly can be this closed ?
