### ISSUE TITLE
Custom ConfigSource not working with extensions that implement CodeGenProvider

### ISSUE THREAD

**Issue by shumonsharif** [quarkusio/quarkus#33567]
### Describe the bug

Any extension that implements CodeGenProvider results in a broken build when used in conjunction with a custom ConfigSource.  This is currently impacting quarkus-cxf, quarkus-grpc, and any other extensions that implement CodeGenProvider.

Error below shows up with `mvn clean verify`:

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.3.Final:generate-code (default) on project code-with-quarkus: Quarkus code generation phase has failed: InvocationTargetException: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.acme.config.InMemoryConfigSource not found -> [Help 1]

### How to Reproduce?

Reproducer is attached: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/11549332/code-with-quarkus.zip), it was created as follows:

1. Generate project using https://code.quarkus.io/
2. Add custom ConfigSource as per https://quarkus.io/guides/config-extending-support (running `mvn clean verify` executes successfully at this stage).
3. Add `quarkus-cxf` or `quarkus-grpc` dependency (or any extension that uses CodeGenProvider) to project (running `mvn clean verify` fails at this point).

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

**Comment by TunaYagci** [comment]
@radcortez any updates about this?

**Comment by radcortez** [comment]
I still need to look into it. Does it block you? You can follow one of my suggestions to move forward.
