### ISSUE TITLE
Redis Geo - error with args

### ISSUE THREAD

**Issue by JoaoBrandao** [quarkusio/quarkus#33562]
### Describe the bug

Hi,
I am trying to add and get the object from Redis Geo using GeoCommands.Search() but seems there is a problem with all args.

### Error

java.util.concurrent.CompletionException: ERR unknown command `geosearch`, with args beginning with: `weather`, `FROMLONLAT`, `13.361389`, `38.115558`, `BYRADIUS`, `5.0`, `km`, `ASC`, 

	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.quarkus.redis.runtime.datasource.BlockingGeoCommandsImpl.geosearch(BlockingGeoCommandsImpl.java:155) 

**Quarkus Version:** 3
**Redis docker:** 6.0-alpine --> not working
**Redis docker** 7.0.1-alpine --> working fine
_I am using Azure Redis, this only allows me to use Redis version 4 or 6._

### Redis code to add/search data in redis

@ApplicationScoped
public class RedisGeo {

    private final RedisDataSource redisDataSource;
    private final KeyCommands<String> keyCommands;
    private final GeoCommands<String, String> geoCommands;

    @Inject
    public RedisGeoUtil(final RedisDataSource redisDataSource) {
        this.redisDataSource = redisDataSource;
        keyCommands = redisDataSource.key();
        geoCommands = redisDataSource.geo(String.class, String.class);
    }

    public void add(String key, double longitude, double latitude, String text) {
        geoCommands.geoadd(key, longitude, latitude, text);
        keyCommands.expire(key, 60);

    }

    public void del(String key) {
        keyCommands.del(key);
    }

    public Object search(final Double latitude, final Double longitude, final Double radius, final String key) {

        GeoSearchArgs args = new GeoSearchArgs<>();
        args.fromCoordinate(latitude, longitude);
        args.byRadius(distanceInKm, GeoUnit.KM);
        args.ascending();
        List weather = geoCommands.geosearch(key, args);
        return weather.get(0); // just for tests
    }

}`

### Class RedisContainer.class
public class RedisContainer implements QuarkusTestResourceLifecycleManager {

    static GenericContainer<?> redis =
            new GenericContainer<>("redis:6.0-alpine").withExposedPorts(6379);

    @Override
    public Map<String, String> start() {
        redis.start();

        return Map.of("quarkus.redis.hosts", "redis://" + redis.getHost() + ":" + redis.getFirstMappedPort(),
                "quarkus.redis.password", "");
    }

    @Override
    public void stop() {
        redis.close();
    }
}

### Integration Test code:
@QuarkusTest
@QuarkusTestResource(RedisContainer.class)
public class RedisGeoUtilTest {

    @Inject
    RedisGeoUtil redisGeoUtil;

    @Test
    @DisplayName("Test adding and getting geo coordinates")
    void addLocationsToWeatherCache() {

        String sample = "Test Geo";
        redisGeoUtil.add("weather", 13.361389, 38.115556, sample);

        Object search = redisGeoUtil.search(13.361389, 38.115558, 5.0);
    }
}

### Expected behavior

The search method should retrieve the object "Test Geo" from the provided example.

To see the same solution working just switch the Redis docker image to redis:7.0.11-alpine  in RedisContainer class

### Actual behavior

Getting issues with args with version 6.0-alpine of Redis

Error: java.util.concurrent.CompletionException: ERR unknown command `geosearch`, with args beginning with: `weather`, `FROMLONLAT`, `13.361389`, `38.115558`, `BYRADIUS`, `5.0`, `km`, `ASC`, 
![Screenshot 2023-05-23 at 17 42 47](https://github.com/quarkusio/quarkus/assets/13374459/1f03304f-6e9a-43c0-a20e-d47298266f2a)

### How to Reproduce?

1. Create the class RedisContainer.class with the code provided in the test packages
2. Create class RedisGeo with all code - code provided
3. Create test class RedisGeoTest as Integration Test - code provided
4. Run the Integration test

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

I have follow almost the same approach from the ticket: https://github.com/quarkusio/quarkus/issues/27831

**Comment by JoaoBrandao** [comment]
@agoncal any client from Microsoft will have the same issue since Azure only allows using Redis version 6.0
![image](https://github.com/quarkusio/quarkus/assets/13374459/a3d0157d-a42d-4364-892d-d565d655b9a0)

**Comment by cescoffier** [comment]
Geosearch was added in Redis 6.2 - See https://redis.io/commands/geosearch/.
