### ISSUE TITLE
Is it a Typo? seems like a bug in code. As it always returns false

### ISSUE THREAD

**Issue by avinash2fly** [quarkusio/quarkus#33579]
https://github.com/quarkusio/quarkus/blame/0a42ca8b5fafacf39ee77641d013503c43fb218d/extensions/jaxb/runtime/src/main/java/io/quarkus/jaxb/runtime/JaxbContextConfigRecorder.java#LL26C40-L26C40

below line checks String in set of class and always returns false.

```Java
classesToBeBound.contains(clazz.getName());
```

should be

```Java
classesToBeBound.contains(clazz);
```

**Comment by gsmet** [comment]
I would say "good catch!" but I will let @Sgitario have a look :).

**Comment by Sgitario** [comment]
Good catch! Do you want to create a pull request with the fix?

**Comment by avinash2fly** [comment]
Pull Request for the same: https://github.com/quarkusio/quarkus/pull/33581

**Comment by geoand** [comment]
Fixed by : https://github.com/quarkusio/quarkus/issues/33579
