### ISSUE TITLE
Kubernetes to enforcing quarkus.kubernetes.replicas=0

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#33582]
### Describe the bug

If I set 

```
quarkus.kubernetes.replicas=0
```

It still creates one replica:

```
spec:
  replicas: 1
```

**Comment by iocanel** [comment]
It seems that this is a bug in the decorator itself. We need to fix on dekorate side.

**Comment by iocanel** [comment]
Created and working on: https://github.com/dekorateio/dekorate/issues/1201
