### ISSUE TITLE
Dev UI - Configuration - unable to filter configuration properties defined in application.properties

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33587]
### Describe the bug

Dev UI - Configuration - unable to filter configuration properties defined in application.properties

This is functional regression comparing to the old Dev UI where the defined properties were at the top

Use-case: be efficient when adjusting already defined properties through web ui

Old Dev UI shows properties defined in application.properties at the top
<img width="1657" alt="Screenshot 2023-05-29 at 17 48 06" src="https://github.com/quarkusio/quarkus/assets/925259/23c60ee7-435d-43d0-b663-6e503ea27b6a">

### Expected behavior

Be able to filter defined configuration properties

### Actual behavior

Unable to filter defined configuration properties

### How to Reproduce?

 - Start an app in dev mode
 - Access http://127.0.0.1:8080/q/dev-ui/configuration-form-editor
 - Compare it with http://127.0.0.1:8080/q/dev-v1/io.quarkus.quarkus-vertx-http/config

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.3.Final / Quarkus main 071a89c3b8

**Comment by phillip-kruger** [comment]
Thanks @rsvoboda - I am looking at this now
