### ISSUE TITLE
GrpcClientConfiguration.inProcess results in NPE when config not present

### ISSUE THREAD

**Issue by nahguam** [quarkusio/quarkus#33593]
### Describe the bug

If `quarkus-grpc-inprocess` is on the classpath, you have a grpc test that needs to test with real ports and you have not explicitly declared the property to disable inprocess, e.g. 

```
quarkus.grpc.clients.foo.in-process.enabled=false
```

...then they fail with:

```
Caused by: java.lang.NullPointerException: Cannot read field "enabled" because "configuration.inProcess" is null
	at io.quarkus.grpc.inprocess.InProcessGrpcServerBuilderProvider.providesChannel(InProcessGrpcServerBuilderProvider.java:72)
```

I would expect it to honour the default value of enabled (false) if the config is not present.

Should `GrpcClientConfiguration.inProcess` be `Optional` or should `InProcessGrpcServerBuilderProvider.providesChannel` defend against the NPE? Or is there a way to express the `GrpcClientConfiguration.inProcess` `@ConfigItem` whereby `InProcess` will be a valid default instance?

**Comment by jbonofre** [comment]
Thanks. I gonna take a look as well.
