### ISSUE TITLE
Missing release 3.1.0.Final for io.quarkus:quarkus-vertx-web

### ISSUE THREAD

**Issue by amarktl** [quarkusio/quarkus#33596]
### Describe the bug

Latest release of **io.quarkus:quarkus-vertx-web** is currently **3.0.0.Beta1** which makes it rather odd to manage the deps separately of the used quarkus version.

### Expected behavior

Release matching version of **io.quarkus:quarkus-vertx-web**

**Comment by gsmet** [comment]
`quarkus-vertx-web` has been relocated to `quarkus-reactive-routes` for several versions before being dropped in `3.0.0.Beta2`.

See https://repo1.maven.org/maven2/io/quarkus/quarkus-vertx-web/3.0.0.Beta1/quarkus-vertx-web-3.0.0.Beta1.pom .

Just adjust your artifact and it should be fine (you should have had a warning in your build before that, at least if you're using Maven, I'm not sure how Gradle reacts to relocations).

**Comment by amarktl** [comment]
@gsmet thanks for the hint - gradle did not show me a notification or i missed it. 
Works as expected.
