### ISSUE TITLE
Add the possible to skip mapping configuration for some parameters

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#33592]
As per this discussion https://github.com/quarkusio/quarkus/discussions/33557 with @radcortez  I am opening this issue about allowing to skip the mapping (to the corresponding configuration beans) for some environment variables, application properties and so on.

**Comment by radcortez** [comment]
This is possible with `StaticInitConfigBuilderBuildItem` and/or `RunTimeConfigBuilderBuildItem`. These build items allow you to add a `io.quarkus.runtime.configuration.ConfigBuilder`, which has access to the underlying `SmallRyeConfigBuilder` used by Quarkus to build the configuration.

In the builder, use `io.smallrye.config.SmallRyeConfigBuilder#withMappingIgnore` to add paths to ignore.

**Comment by stephanpelikan** [comment]
I needed this in the augmentation phase (see [Stackoverflow](https://stackoverflow.com/questions/79660219/classcast-exception-in-custom-extension-having-pure-static-properties-levaraging)). I achieved this by using `io.smallrye.config.SmallRyeConfigBuilderCustomizer` (see [smallrye.io/smallrye-config/3.12.3/config/customizer](https://smallrye.io/smallrye-config/3.12.3/config/customizer/)).
