### ISSUE TITLE
Random HTTP 401 failures from endpoints secured with `@RolesAllowed`

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#33602]
### Describe the bug

Please see https://stackoverflow.com/questions/76329979/how-can-i-prevent-quarkus-with-rolesallowed-from-randomly-returning-a-401-respo

### Expected behavior

`401` can only be returned for unauthenticated requests 

### Actual behavior

According to the report, `401` might happen due to an anonymous `SecurityIdentity` even when the authentication credentials are provided

### How to Reproduce?

https://github.com/florian-signoret-ibm/quarkus-basic-auth-issue

**Comment by sberyozkin** [comment]
Hey @gsmet @geoand the bot has incorrectly deduced that `bearer-token` is this issue's theme

**Comment by geoand** [comment]
Thanks for the heads up

**Comment by geoand** [comment]
I don't see why it would do that since that id should only be added if bearer is in the title

**Comment by sberyozkin** [comment]
may be `401` or `RolesAllowed` trigger it via the OIDC route somehow

**Comment by geoand** [comment]
Dunno really

**Comment by gsmet** [comment]
There's something very odd indeed.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus-github-bot/issues/342 .

**Comment by florian-signoret-ibm** [comment]
Hello,
We added a branch using quarkus 3.
We reproduce the issue as well.

**Comment by sberyozkin** [comment]
Hi @florian-signoret-ibm, can you please check one thing, it will save us some time when we end up looking at this issue.
Can you have, on the test side, trace every call before and including the one leading to the first few unexpected `401`s and confirm that `Authorization` header is present in every single request ?

Thanks

**Comment by michalvavrik** [comment]
I'll have a look.

**Comment by michalvavrik** [comment]
Reproduced bug couple times now. It is quite random, I had to run test roughly 15 times (each test takes about 7 minutes) before it failed first time and then it failed twice in row.

> For the failing request, you will notice that the authorization header is present, but the principal is null.

I don't think it is true @florian-signoret-ibm, at least in my case failed request never reaches `SecurityRequestFilter`. Did you tested it, please? I just want to check so that it is clear we are experiencing same issue because my 401 is never logged there.

**Comment by florian-signoret-ibm** [comment]
Hello,
Thanks for investigating.

Yes, I noticed with my colleagues that the issue frequency depends on the environment (machine, docker or not).
On my machine, I reproduce it fast everytime, but only without docker.
Here are the logs:

2023-06-01 09:08:58,850 ERROR [com.qua.TestResourceTest] (pool-1-thread-26) Caught exception for request 25-2
2023-06-01 09:08:59,319 INFO  [com.qua.TestResourceTest] (main) Received 250 requests out of 2250000

org.opentest4j.AssertionFailedError
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:46)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:158)
	at com.quarkus401.TestResourceTest.testBasicAuth(TestResourceTest.java:56)
	...

When I search for "25-2" in the quarkus logs, I see:

...
2023-06-01 09:08:58,826 INFO  [com.qua.SecurityRequestFilter] (executor-thread-1) Received request from '78-1' with authorization header: 'Basic YWRtaW46cGFzc3dvcmQ=' and principal 'admin'
2023-06-01 09:08:58,828 INFO  [com.qua.SecurityRequestFilter] (executor-thread-1) Received request from '25-2' with authorization header: 'Basic YWRtaW46cGFzc3dvcmQ=' and principal '**[null]**'
2023-06-01 09:08:58,831 INFO  [com.qua.SecurityRequestFilter] (executor-thread-0) Received request from '78-2' with authorization header: 'Basic YWRtaW46cGFzc3dvcmQ=' and principal 'admin'
...

**Comment by michalvavrik** [comment]
thanks @florian-signoret-ibm , grep of my logs never contains `[null]`, but as long as I can reproduce 401, I can debug it.

**Comment by michalvavrik** [comment]
By bad, it's there.

**Comment by michalvavrik** [comment]
This must be Mutiny or Vert.X bug, there is no other explanation possible. Problem is that so far pure Mutiny reproducer didn't fail on my workstation.

I verified that at this point 

https://github.com/quarkusio/quarkus/blob/947d3a94e1b07be9e733c674872728ace4d3b8d0/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java#L97

https://github.com/quarkusio/quarkus/blob/947d3a94e1b07be9e733c674872728ace4d3b8d0/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java#L131

identity was created with `admin` principal, executed on `executor-thread`.

While at this point:

https://github.com/quarkusio/quarkus/blob/947d3a94e1b07be9e733c674872728ace4d3b8d0/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java#L422

identity is `null`, executed on same `vert.x-eventloop-thread`. There is no code between except for `.memoize().indefinitely()`, so it can't be bug on our side. It is extremely hard to reproduce for me, I had to run tests for 40 h + to reproduce it 5 times (e.g. no failure for 12 hours and then 2 failures in row; tested with `999-SNAPSHOT`). Also at my workstation there is no chance to reproduce it in DEV mode or JVM mode, just docker. Only way to debug this is additional logging.

/cc @cescoffier @jponge, @sberyozkin

**Comment by michalvavrik** [comment]
@florian-signoret-ibm I can't help with this issue, but I would like to have confirmed you can reproduce this bug with different runtime than `ibm-semeru-runtimes:open-11-jre-focal` (personally I have problem to reproduce this at all, please see above). For example Quarkus Quickstarts are using `registry.access.redhat.com/ubi8/ubi-minimal:8.3`. Thanks

**Comment by florian-signoret-ibm** [comment]
Hello,
I could reproduce it on this JVM as well.
What I noticed is that we generally reproduce the issue much faster when running quarkus out of docker.

**Comment by michalvavrik** [comment]
Great, thanks.

**Comment by sdehors-ibm** [comment]
I can confirm that I reproduce the issue locally running quarkus with temurin jdk
```
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode) 
```

**Comment by michalvavrik** [comment]
Copy that. I'll experiment with creating standalone reproducer over weekend, in unlikely case I succeeded I'll write a note here.

**Comment by sberyozkin** [comment]
Hey @michalvavrik Thanks for spending the time on this one. 
I wonder, if there is indeed a race condition with the Vert.x context propagation.
Hey @cescoffier @jponge, can you check please https://github.com/quarkusio/quarkus/issues/33602#issuecomment-1575635342 ? Might be an interesting issue related to the way Mutiny handles it

**Comment by cescoffier** [comment]
It might be a memorize race condition (but I kind of doubt it). @jponge may know more.

**Comment by jponge** [comment]
We have a good coverage on concurrent invalidations of memoization, so I don't think the problem is here.

**Comment by sberyozkin** [comment]
Thanks @cescoffier @jponge. I wonder if we can try to narrow it down somehow, example, can we avoid `memoize()` to 100% confirm it is not what is affecting it ?

Hi @stuartwdouglas, what is your take on it ?

Thanks

**Comment by stuartwdouglas** [comment]
I was able to reproduce it with the following code: @jponge I am pretty sure this proves it is a Mutiny bug:

```
@Test
    public void foo() throws ExecutionException, InterruptedException {
       var ex = Executors.newFixedThreadPool(1);
           for (;;) {
               CompletableFuture cf = new CompletableFuture();
               Uni.createFrom().emitter(new Consumer<UniEmitter<? super Object>>() {
                   @Override
                   public void accept(UniEmitter<? super Object> uniEmitter) {
                       ex.submit(new Runnable() {
                           @Override
                           public void run() {
                               uniEmitter.complete(new Object());
                           }
                       });
                   }
               }).memoize().indefinitely()
                        .subscribe().withSubscriber(new UniSubscriber<Object>() {
                           @Override
                           public void onSubscribe(UniSubscription subscription) {

                           }

                           @Override
                           public void onItem(Object identity) {
                               cf.complete(identity);
                           }

                           @Override
                           public void onFailure(Throwable failure) {

                           }
                       });
               if (cf.get() == null) {
                   throw new RuntimeException();
               }

           }

    }
```

**Comment by stuartwdouglas** [comment]
It took a while to see a failure, I have only seen one so far so I am not sure how common it is. wrapping the whole thing into multiple threads might make it show up faster.

**Comment by jponge** [comment]
Here's a shorter rewrite:

```java
@Test
    public void foo() throws ExecutionException, InterruptedException {
        var ex = Executors.newFixedThreadPool(1);
        for (; ; ) {
            CompletableFuture<Object> cf = new CompletableFuture<>();
            Uni.createFrom().emitter(emitter -> ex.submit(() -> emitter.complete(new Object())))
                    .memoize().indefinitely()
                    .subscribe().with(cf::complete);
            if (cf.get() == null) {
                throw new RuntimeException();
            }
        }
    }
```

**Comment by jponge** [comment]
Well actually the test case in itself is not correct, because there's no memoization at all across the loop iterations. A new `Uni` pipeline is re-created every time, but the various subscribers do not share the same upstream `Uni`.

It does reveal some race condition though.

**Comment by jponge** [comment]
That's what you'd want to test for memoization:

1. Regularly create a new `Uni` with memoization,
2. Have concurrent subscribers over the same `Uni`, because the code above doesn't use memoization as it should be.

```java
    @Test
    public void foo() throws ExecutionException, InterruptedException {
        var ex = ForkJoinPool.commonPool();
        while (true) {
            // Create a new Uni with memoization
            Uni<Object> uni = Uni.createFrom().emitter(emitter -> ex.submit(() -> emitter.complete(new Object())))
                    .memoize().indefinitely()
                    .onItem().ifNull().failWith(RuntimeException::new)
                    .runSubscriptionOn(ex);
            for (var i = 0; i < 30_000; i++) {
                AtomicBoolean failed = new AtomicBoolean();
                // Here comes a new subscriber that uses from memoization
                uni.subscribe().with(ok -> {
                }, err -> failed.set(true));
                if (failed.get()) {
                    throw new IllegalStateException("Failed");
                }
            }
        }
    }
```

**Comment by stuartwdouglas** [comment]
yes, but it still fails even with one subscriber.

**Comment by jponge** [comment]
Absolutely, there's a race condition, even if that's not how to use memoization.

**Comment by stuartwdouglas** [comment]
Yea, but this test is exactly the code that is run in `HttpSecurityRecorder` where the bug is. I was trying to reproduce the bug, not demonstrate memoization :-)

**Comment by jponge** [comment]
There's a fix in Mutiny.

**Comment by sberyozkin** [comment]
@jponge Hi Julien, can we get it in time for Quarkus 3.2.0.Final ?

**Comment by jponge** [comment]
Hi @sberyozkin, I'm on PTO tomorrow but I can cut a release next Monday

**Comment by jponge** [comment]
If that's too tight let me know and I'll try doing a release sooner

**Comment by jponge** [comment]
Ok looking at schedules I need to release Mutiny 2.3.0 ASAP 😄

**Comment by gsmet** [comment]
@jponge Monday is fine if @cescoffier doesn't need to release other components.

**Comment by jponge** [comment]
@gsmet I've started a release train (Mutiny 2.3.0, Vert,x bindings 3.5.0) then will open a Quarkus PR. @cescoffier can always amend early next week

**Comment by sberyozkin** [comment]
Hi @jponge Great, thanks, and enjoy the day off :+1:

**Comment by sberyozkin** [comment]
Hey @jponge @cescoffier Looks like #34249 got this fixed, right ?

**Comment by jponge** [comment]
Yes

**Comment by sberyozkin** [comment]
Great stuff,  thanks for your help Julien @jponge

**Comment by sberyozkin** [comment]
@florian-signoret-ibm Please check the main branch, backports for 3.2 and 3.1 are also proposed for #34249

**Comment by michalvavrik** [comment]
No, in order to test the fix, you would have to follow build main https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main then use quarkus version 999-SNAPSHOT and group id io.quarkus (not a platform in it).

**Comment by florian-signoret-ibm** [comment]
I tested and could not reproduce the issue
Thanks!
