### ISSUE TITLE
Quarkus Redis Cache: expire-after-access config property

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#33615]
### Description

The Quarkus Cache with Caffeine as backend has the following property:

[quarkus.cache.caffeine.expire-after-access](https://quarkus.io/guides/cache#quarkus-cache-cache-config_quarkus.cache.caffeine.expire-after-access)

The Redis Cache backend, however, only has the following property:

[quarkus.cache.redis.ttl](https://quarkus.io/guides/cache-redis-reference#quarkus-cache-redis_quarkus.cache.redis.ttl)

corrosponding to the Caffeine backend property:

[quarkus.cache.caffeine.expire-after-write](https://quarkus.io/guides/cache#quarkus-cache-cache-config_quarkus.cache.caffeine.expire-after-write)

### Implementation ideas

A new property for the Redis backend similar to the one for the Caffeine backend:

[quarkus.cache.caffeine.expire-after-access](https://quarkus.io/guides/cache#quarkus-cache-cache-config_quarkus.cache.caffeine.expire-after-access)

**Comment by cescoffier** [comment]
This can be implemented using the GETEX command.

**Comment by AndreasPetersen** [comment]
Thanks for the suggestion @cescoffier . The Quarkus [Redis Cache](https://quarkus.io/guides/cache-redis-reference) guide does not seem to mention commands. The [Redis Reference](https://quarkus.io/guides/redis-reference) does however. Do I understand it correctly that we can use the Quarkus Cache with Redis as backend, in combination with the commands as described in the Redis reference?

**Comment by cescoffier** [comment]
That was more a note about how we could implement the feature (the backend implementation use the redis client underneath). 

You can of course combine both, you just need to compute the keys.

**Comment by AndreasPetersen** [comment]
Amazing, thanks!
