### ISSUE TITLE
absolute path in quarkus.keycloak.devservices.realm-path for integration-tests/oidc-client-reactive

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33626]
### Describe the bug

`quarkus.keycloak.devservices.realm-path=/Users/manderse/code/quarkusio/gradle-enterprise-maven-build-validation/.data/02-validate-local-build-caching-different-locations/20230526T083333-647052bd/first-build_quarkus/integration-tests/oidc-client-reactive/target/classes/quarkus-realm.json`

should be made relative or ignored

**Comment by sberyozkin** [comment]
Hi Max, can you clarify the problem please ?

**Comment by maxandersen** [comment]
the issue is that because of the hardcoded path it is not possible to reuse build cache between builds.

we need to decide if we just ignore it for these cases or need to change the build.
