### ISSUE TITLE
rest-client-reactive tests has absolute path in application.properties

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33629]
### Describe the bug

https://ge.quarkus.io/c/nk5vgua7gpx2u/k4ldeu42numus/goal-inputs?expanded=WyJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiMmI1NTRwNDJxbmV6bS1hbm5vdGF0aW9ucHJvY2Vzc29ycGF0aCIsImhsbDZsbWYydnZodjYtYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJobGw2bG1mMnZ2aHY2LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsInR5bWNvcXM1bnNoZnktYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJ0eW1jb3FzNW5zaGZ5LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsImU3dmx6b2xwbXptY28tYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiXQ#e7vlzolpmzmco

```
quarkus.rest-client.self-signed.trust-store=/Users/manderse/code/quarkusio/gradle-enterprise-maven-build-validation/.data/02-validate-local-build-caching-different-locations/20230526T083333-647052bd/first-build_quarkus/integration-tests/rest-client-reactive/target/self-signed.p12
quarkus.rest-client.wrong-host.trust-store=/Users/manderse/code/quarkusio/gradle-enterprise-maven-build-validation/.data/02-validate-local-build-caching-different-locations/20230526T083333-647052bd/first-build_quarkus/integration-tests/rest-client-reactive/target/wrong-host.p12
quarkus.rest-client.wrong-host-rejected.trust-store=/Users/manderse/code/quarkusio/gradle-enterprise-maven-build-validation/.data/02-validate-local-build-caching-different-locations/20230526T083333-647052bd/first-build_quarkus/integration-tests/rest-client-reactive/target/wrong-host.p12
```

**Comment by Sgitario** [comment]
These paths are automatically set by the Maven build, so it should be ok.
