### ISSUE TITLE
config.yml has absolute path in test of integration-tests/gradle

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33625]
### Describe the bug

link: https://ge.quarkus.io/c/nk5vgua7gpx2u/k4ldeu42numus/goal-inputs?cacheability=cacheable&expanded=WyI3Y3dyYmU0bGY2dXprLWFubm90YXRpb25wcm9jZXNzaW5ncmVzb3VyY2VzIiwiN2N3cmJlNGxmNnV6ay1hbm5vdGF0aW9uUHJvY2Vzc2luZ1Jlc291cmNlcy0wLTAiLCI3Y3dyYmU0bGY2dXprLWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiN2N3cmJlNGxmNnV6ay1hbm5vdGF0aW9uUHJvY2Vzc29yUGF0aC0xLTAiXQ#7cwrbe4lf6uzk

.quarkus/config.yaml ends up with:

```
---
debug: true
registries:
- test.registry.quarkus.io:
    maven:
        repository:
            url: file:///Users/manderse/code/quarkusio/gradle-enterprise-maven-build-validation/.data/02-validate-local-build-caching-different-locations/20230526T083333-647052bd/first-build_quarkus/integration-tests/gradle/target/classes/test-registry-repo
```

### Expected behavior

not sure it is avoidable but if not we should mark it as ignorable.

**Comment by aloubyansky** [comment]
It's https://github.com/quarkusio/quarkus/blob/main/integration-tests/gradle/src/main/resources/.quarkus/config.yaml. The issue is that the config needs a valid repo URL. Could we ignore this file?
