### ISSUE TITLE
SnapStart optimizations (PreloadClassBuildItem?) not executed during build for Lambda

### ISSUE THREAD

**Issue by L154x** [quarkusio/quarkus#33624]
### Describe the bug

Hi all,
I want to deploy my quarkus application to Lambda with Snapstart Optimizations in place.
However, even though the documentation states that the optimizations are enabled by default when using the extension, I do not see anything related to preloading the classes.
I followed the guideline defined here: https://quarkus.io/guides/amazon-snapstart but still the application is super slow.

### Expected behavior

I would expect that there is somewhere some log output (at least for debug output) describing that the list of classes that is defined in `app/src/main/resources/META-INF/quarkus-preload-classes.txt` is somehow ingested and used for the snapstart opimizations. So could also be that the optimizations don't run at all?

### Actual behavior

The build succeeds and the application runs, but even with Lambda Snapstart enabled and the lambda restoring from the snapshot when invoked via its version, the execution time of the Lambda is still super slow.
There is no log output indicating that any snapstart optimizations are being run, therefore I'm guessing that they are not running?

### How to Reproduce?

Steps to reproduce:

1. Set up project with extension "quarkus-amazon-lambda"
```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkiverse.amazonservices:quarkus-amazon-dynamodb:1.6.3'
    implementation 'io.quarkus:quarkus-amazon-lambda'
    implementation 'io.quarkus:quarkus-amazon-lambda-xray'
``` 
2.  Add file with list of classes under `app/src/main/resources/META-INF/quarkus-preload-classes.txt`

```
...
com.amazonaws.services.lambda.runtime.LambdaRuntime
com.amazonaws.services.lambda.runtime.LambdaRuntime$1
com.amazonaws.services.lambda.runtime.RequestHandler
com.amazonaws.services.lambda.runtime.RequestStreamHandler
com.amazonaws.services.lambda.runtime.api.client.AWSLambda
com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader
...
```
3. Execute build: `./gradlew -d build`
4. Check log output, it states nothing there that classes are preloaded 

### Output of `uname -a` or `ver`

Darwin C02CJ3MJLVDL 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Quarkus version or git rev

2.16.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

### Additional information

I have also added this to my application.properties, even though they are just the defaults anyway, but still don't see that it's actually applied.

```
quarkus:
  snapstart:
    enable: true
    generate-application-class-list: true
    full-warmup: true
```

Also, I'm also using client priming and this already reduced the runtime by 3 seconds. I'm just missing any proof that also the class preloading is working, because the Lambda still takes 4 seconds to resolve the invocation.

**Comment by gsmet** [comment]
@cescoffier that might be one for you?

**Comment by cescoffier** [comment]
I don't have enough details. If the file is there the classes will be preloaded.

But the startup time depends also on the function. 

To check if the classes are preloaded, add a System.out in a static initializer of a class. 

Can you also post the snapshot log and the execution log?
