### ISSUE TITLE
native.image.path have absolute path in generated pom

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33630]
### Describe the bug

 <native.image.path> is set to an absolute path in lots of pom.xml in  `integration-tests/maven/target/test-classes`

![2023-05-26_11-39-20](https://github.com/quarkusio/quarkus/assets/54129/4ed6957b-caa3-4ba9-8fdb-c2e4f1d2507a)

https://ge.quarkus.io/c/nk5vgua7gpx2u/k4ldeu42numus/goal-inputs?expanded=WyJ2YmRzbTZ5ZmYzeG55LWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiMmI1NTRwNDJxbmV6bS1hbm5vdGF0aW9ucHJvY2Vzc29ycGF0aCIsImhsbDZsbWYydnZodjYtYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJobGw2bG1mMnZ2aHY2LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsInR5bWNvcXM1bnNoZnktYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCJ0eW1jb3FzNW5zaGZ5LWFubm90YXRpb25Qcm9jZXNzb3JQYXRoLTAtMCIsImU3dmx6b2xwbXptY28tYW5ub3RhdGlvbnByb2Nlc3NvcnBhdGgiLCI3YmR0bmxmdm03azZrLWFubm90YXRpb25wcm9jZXNzb3JwYXRoIiwiN2JkdG5sZnZtN2s2ay1hbm5vdGF0aW9uUHJvY2Vzc29yUGF0aC0xLTAiXQ#change-7bdtnlfvm7k6k-annotationProcessorPath-1-0-0

same for `integration-tests/kubernetes/maven-invoker-way/`:

![2023-05-26_11-41-03](https://github.com/quarkusio/quarkus/assets/54129/40848745-f8d2-4d13-b731-36322af9287e)

**Comment by geoand** [comment]
I don't really understand this, the file is in the `target` directory, so why is it a problem?

**Comment by gsmet** [comment]
I think it's worth fixing because the absolute path shouldn't be used anyway. I'll do it.

**Comment by maxandersen** [comment]
@geoand by having absolute paths it is not cacheble. Meaning you will be required to build this even though no changes between builds. 

Thus by fixing this (or mark it on in this specific test the file is not important) everyone running with caching enabled can greatly reduce build times locally and in CI. 

Given that I do find the build scans useful :)

**Comment by geoand** [comment]
🆗
