### ISSUE TITLE
UnresolvedElementException: Discovered unresolved method during parsing when adding legacy rest client binding

### ISSUE THREAD

**Issue by deodorel** [quarkusio/quarkus#33636]
### Describe the bug

After adding a new rest client binding into an `@ApplicationScoped` service that already had 2 other such bindings, now the native compilation fails with 

```posh
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.redacted.redacted.bond.service.svc.service.base.BondValuationRequestProviderImpl.<init>(com.redacted.redacted.bond.service.svc.service.rules.RulesLoaderService, com.redacted.redacted.bond.service.svc.client.tradeLoader.TradeLoaderResource). This error is reported at image build time because class co com.redacted.redacted.bond.service.svc.service.base.BondValuationRequestProviderImpl_Bean is registered for linking at image build time by command line
```

I tried multiple solutions like encapsulating the rest client in a resource, changing the scopes, injecting it in different manners, etc.

I presume this Bean class is like a proxy generated for DI at compile time.
The application runs normally on non native, AND was building natively without issues before adding this new service.

The service definition is quite simple:

```java
@RegisterRestClient
@Path("/")
public interface TradeLoaderClientService {
    @GET
    @Path("trade")
    @Produces("application/json")
    @Retry(delay = 5000, retryOn = {Exception.class, RuntimeException.class})
    TradeDO trade(@QueryParam String clientName,@QueryParam String tradeId);
}
```

This is injected into
```java
@Path("/")
@Dependent
public class TradeLoaderResource {

    @Inject
    @RestClient
    TradeLoaderClientService tradeLoaderClientService;


    @GET
    @Path("trade")
    @Produces("application/json")
    @Retry(delay = 5000, retryOn = {Exception.class, RuntimeException.class})
    public TradeDO trade(@QueryParam String clientName, @QueryParam String tradeId) {
        return tradeLoaderClientService.trade(clientName, tradeId);
    }
}
```

Then directly injected in the above service with constructor injection

```java
    RulesLoaderService rulesLoaderService;

    TradeLoaderResource tradeLoaderResource;

    public BondValuationRequestProviderImpl(RulesLoaderService rulesLoaderService,TradeLoaderResource tradeLoaderResource) {
        this.rulesLoaderService = rulesLoaderService;
        this.tradeLoaderResource = tradeLoaderResource;
    }

```

### Expected behavior

The application should compile natively.

### Actual behavior

The compile fails.

### How to Reproduce?

could try to build a test project but this is a complex project otherwise

### Output of `uname -a` or `ver`

docker linux machine on aws

### Output of `java -version`

11.0.18+10-jvmci-22.3-b13 openjdk

### GraalVM version (if different from Java)

GraalVM 22.3.1 Java 11 CE

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.2

**Comment by gsmet** [comment]
Please provide a small self-contained reproducer. Thanks!

**Comment by deodorel** [comment]
Hello, unfortunately i wasn't able to produce an usable project that reproduces the issue, as if i remove all the proprietary stuff not much is left of the project. However, i was able to find the issue. The error happens if the following line has the try catch. If i remove the try catch the code compiles natively. 

```
 try {
        final BondDO bondDO = service.load(clientName, tradeId);
        } catch (RestClientResponseException e) {
            throw new CustomException(e.getResponseBodyAsString());
        } catch (Exception e) {
            throw new CustomException(String.format("Failed to load %", someVar), e);
        }
```
So just the line 
`        final BondDO bondDO = service.load(clientName, tradeId);`

Compiles. Service is an injected service that has a restclient injected into it and makes a rest call. 

Feel free to close this, as i have this work around let's call it, i will rely on outside code to catch those exceptions.
But very strange and annoying, i spent a lot of time to pinpoint the exact lines that cause the issue ....

**Comment by geoand** [comment]
Thanks for the input

**Comment by kjq** [comment]
Just adding but it looks like we came across this recently too with a package-default method.  Added `protected` to the method and the native build worked fine.
