### ISSUE TITLE
Endpoint with RestSseElementType doesn't produce events in native

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#33652]
### Describe the bug

Since Quarkus 3.0.1, endpointed annotated as follows does not emit SSE events in native mode:

```java
    @GET
    @Path("/monitor/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.TEXT_PLAIN)
    public Publisher<String> stream() {
        return alerts;
    }
```

This is a deprecated annotation. This scenario works in JVM mode, or with `@RestStreamElementType`, which is now the documented way to emit SSEs.

### Expected behavior

The endpoint produces SSE event.

### How to Reproduce?

```posh
oc login
git clone git@github.com:quarkus-qe/quarkus-test-suite.git
cd monitoring/micrometer-prometheus-kafka-reactive
mvn clean verify -Dopenshift -Dnative -Dit.test=OpenShiftAmqStreamsAlertEventsReactiveIT # fail with current snapshot
mvn clean verify -Dopenshift -Dnative -Dit.test=OpenShiftAmqStreamsAlertEventsReactiveIT -Dquarkus.platform.version=3.0.0.Final #3.0.0 - still works
mvn clean verify -Dopenshift  -Dit.test=OpenShiftAmqStreamsAlertEventsReactiveIT #JVM mode - still works
```

### Output of `uname -a` or `ver`

Linux tigris 6.2.15-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

17.0.7+7

### GraalVM version (if different from Java)

GraalVM 22.3.2.1-Final Java 17 Mandrel Distribution

### Quarkus version or git rev

since 3.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (Red Hat 3.8.6-4)

**Comment by geoand** [comment]
Does the problem also occur in 3.1?

**Comment by mjurc** [comment]
Yeah, it happens consistently since 3.0.1 throughout to current `main`

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by geoand** [comment]
#33663 fixes the issue
