### ISSUE TITLE
redirect of /q/dev too permanent?

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33658]
### Describe the bug

was using quarkus dev with quarkus 3 using dev UI all good.

now switch to quarkus 2.x by running quarkus dev in https://github.com/quarkusio/todo-demo-app

pressing 'd' gets me to http://localhost:8080/dev which then redirects to http://localhost:8080/dev-ui presumably because of previous quarkus 3 returned a permanent redirect?

### Expected behavior

dont break quarkus 2 dev ui just because I ran a quarkus 3 dev mode app

**Comment by maxandersen** [comment]
looks like https://github.com/quarkusio/quarkus/pull/32151/ made it a 303 redirect - would it not be more appropriate to make it a 307 (temporary) ?

**Comment by geoand** [comment]
We seem to be using HTTP 308: https://github.com/quarkusio/quarkus/blob/e184046bda9ecddf1d20dd9fe42fb9be7ca5d812/extensions/vertx-http/runtime/src/main/java/io/quarkus/devui/runtime/DevUIRecorder.java#L102

We probably don't want 307 (as per the comment in the code), but 302?

**Comment by maxandersen** [comment]
Yeah 308 definitely will cause this which ain't right thing imo. 

+1 on 302

**Comment by geoand** [comment]
@cescoffier do you agree?

**Comment by maxandersen** [comment]
> Well, I would argue it's a cache issue. So, no matter what we change now, you would need to clear your cache, which would have worked initially.

sure; but that is once. and yes of course its a cache issue - a cache issue because we tell the browser that localhost:8080/q/dev have movd.



> Now, we can use a 302, and hope that all browsers will have sane behavior (which was not the case before). We are in the easy case here: `GET` - so should work reliably well (except curl and such which would not follow the redirect automatically).

we could also just have `/q/dev` return the result directly - the redirect to `/q/dev-ui` isn't really not worth it if it makes quarkus 2 behave badly imo

**Comment by maxandersen** [comment]
related to #32575 where its stated /q/dev-ui was introduced to have consistency. Which I get the rationale for but i honestly don't see the value if it result in bad developer experience things like this issue.
