### ISSUE TITLE
Clarify the behavior of `InstanceHandle.close()`

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#33665]
### Description

The CDI specification currently says that `Instance.Handle.close()` unconditionally calls `destroy()`. This behavior is inherited from Weld.

ArC's `InstanceHandle.close()` only calls `destroy()` if the bean pointed to by the handle is `@Dependent`, leaving lifecycle management of other beans to the respective context.

In #33523, we made `InstanceHandle.close()` behavior dependent on the container running mode: by default, it follows the previous ArC behavior, but in the strict mode, it follows the specified behavior. This is confusing and needs to be clarified.

### Implementation ideas

One option is to propose a change to the specification.

**Comment by mkouba** [comment]
@manovotn Do you happen to know if this was discussed in a spec issue?

**Comment by manovotn** [comment]
> @manovotn Do you happen to know if this was discussed in a spec issue?

No, I don't think this was proposed on the spec level at all.

**Comment by Ladicek** [comment]
My personal opinion is that we shouldn't have added `Instance.Handle.close()` to the CDI API, but alas, I didn't notice the difference back then and now it's too late :-/ I honestly don't know what we can do with this.

**Comment by mkouba** [comment]
> My personal opinion is that we shouldn't have added `Instance.Handle.close()` to the CDI API, but alas, I didn't notice the difference back then and now it's too late :-/ I honestly don't know what we can do with this.

I propose to add a note to the list of [Non-standard Features](https://quarkus.io/guides/cdi-reference#nonstandard_features) and mark this issue as resolved.

**Comment by Ladicek** [comment]
I guess that makes sense.
