### ISSUE TITLE
Quarkus CLI not working on Windows with Gradle

### ISSUE THREAD

**Issue by LimitlessGreen** [quarkusio/quarkus#33683]
### Describe the bug

If I  create a new gradle (and gradle-kotlin-dsl) project on Windows and try to run it with `quarkus dev` on Windows (with Docker), I'm getting the following error:

```bash
> quarkus dev
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 57s
9 actionable tasks: 9 executed
Listening for transport dt_socket at address: 5005
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff88adb17a7, pid=38228, tid=7872
#
# JRE version: OpenJDK Runtime Environment (17.0.2+8) (build 17.0.2+8-86)
# Java VM: OpenJDK 64-Bit Server VM (17.0.2+8-86, mixed mode, emulated-client, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3e17a7]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\workspace\TestProj\hs_err_pid38228.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```

Using `./gradlew quarkusDev` does work.

Mentioned log file: [hs_err_pid38228.log.txt](https://github.com/quarkusio/quarkus/files/11594223/hs_err_pid38228.log.txt)

### Expected behavior

It should run in dev mode.

### How to Reproduce?

1. install Docker for Windows
2. `scoop install quarkus-cli`
3. `quarkus create --gradle-kotlin-dsl`
4. enter dir
5. `quarkus dev`

### Output of `uname -a` or `ver`

Win 11, Docker on wsl2

### Output of `java -version`

openjdk17

### Quarkus version or git rev

3.0.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

- I installed openjdk17 with scoop

```bash
> java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

**Comment by gsmet** [comment]
I would recommend you to try to upgrade your JDK to the latest 17.x as core dump are usually issues in the JDK itself (if you are not using any native libraries).

**Comment by marvedly** [comment]
I experienced the same issue when using `OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)`. I am using Kotlin. `quarkus dev` does not work, but `./gradlew quarkusDev` works.

Have you tried to reproduce it?

**Comment by maxandersen** [comment]
Does it work when You create non kotlin based project ?
