### ISSUE TITLE
Make the io.quarkus.platform groupId an attribute in the documentation

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#33701]

**Comment by rolfedh** [comment]
Is this the attribute you're looking for:
https://github.com/quarkusio/quarkus/blob/25eb435de00cf2fb0b79ac0cbeeb6acb7dec5d06/docs/src/main/asciidoc/_attributes.adoc?plain=1#L5

**Comment by gsmet** [comment]
I fixed it in https://github.com/quarkusio/quarkus/pull/33745 .
