### ISSUE TITLE
Self-updating CLI

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#33708]
### Description

https://quarkus.io/guides/cli-tooling lists several ways to install the quarkus cli. It doesn't have any top-level docs for how to update the cli, although there's something about updates in each package manager's tab. 

However, for a user to be able to follow those instructions, they have to remember what package manager they used the first time. Some users (me!) may forget. It'd be great to be able to call `quarkus update-self` or `quarkus upgrade` or `quarkus refresh` or equivalent. (Naming the self-update of a thing that also updates other things is always tricky, but the principle of self-update is the important part.)

### Implementation ideas

Although (some) users don't know how they installed the cli, the quarkus cli itself likely knows how it was installed (or it would be easy to give it that knowledge, either by instrumenting the distributed package for each manager, or just looking at its install path).

If quarkus knows how it was installed, we could then provide a `quarkus upgrade` that would delegate to the right package manager to do an update.

**Comment by maxandersen** [comment]
It's not feasible to call out to update. 

At least not portably and definitely windows won't let you update what you are actually running. 

On top comes the different package managers/installer approaches. 

At best we can tell there is an update but even that can be tricky as it really can depends on your project if you want do update or stay. 

Maybe we could make something 'quarkus version' do a check and print if newer version available ?

**Comment by ebullient** [comment]
> Maybe we could make something 'quarkus version' do a check and print if newer version available ?

Reasonable and meets w/ expectations.

**Comment by yuokada** [comment]
Duplicate with #31690?

**Comment by holly-cummins** [comment]
Closing as a duplicate of #31690.
