### ISSUE TITLE
Update tool: Some javax.* application properties not updated

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#33705]
### Describe the bug

Reproducer: https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes/super-heroes/rest-fights

After running `quarkus update --stream=3.0`, the application properties still had the following: 

```
io.quarkus.workshop.superheroes.fight.client.HeroProxy/mp-rest/scope=javax.inject.Singleton
```

### Expected behavior

The application.properties should be updated to 

```
io.quarkus.workshop.superheroes.fight.client.HeroProxy/mp-rest/scope=jakarta.inject.Singleton
```

### Quarkus version or git rev

3.0.3 of the CLI

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus-updates/pull/37 to fix it.
