### ISSUE TITLE
Configurable body size

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#3372]
I tried to change the default body size via undertow-handlers.conf but it's not working.

The undertow-handlers.conf file contains the following :

`method(POST) -> buffer-request(buffers=20000000)`

Also, @gsmet suggested that it would be better expose this kind of configuration in application.properties

P.S. This is the first time that i use undertow so i might got the configuration wrong.

**Comment by machi1990** [comment]
Re-opening this one since https://github.com/quarkusio/quarkus/pull/3404 is not merged yet - waiting for a new release of `quarkus-http` after https://github.com/quarkusio/quarkus-http/pull/1 landed.

**Comment by machi1990** [comment]
I think this should be kept open until #3404 is merged (which depends on a new release of `quarkus-http`). WDYT @cescoffier ?
