### ISSUE TITLE
Blaze Persistence support/extension.

### ISSUE THREAD

**Issue by soberich** [quarkusio/quarkus#3374]
**Description**
First, a link to a parent issue in `blaze-persistence` tracker.
https://github.com/Blazebit/blaze-persistence/issues/817

I would like to see support of Blaze Persistence `entity-view` capabilities in Quarkus. I want to implement support try to implement it, thought I have to controversial opinion on ability to do so and, primarily to complexity/simplicity of implementation. 

On one hand:

1. Blaze relies heavily on reflection and generates proxies with `javassist` at runtime which sounds like the worst scenario for Quarkus Integration.
See [`ProxyFactory.java`](https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java)

2. Also, it relies on Hibernate internal integration APIs and I assume those are somewhat different though Quarkus clams "Hibernate" it is massively re-writted and transformed. I hope I am wrong and Blaze attempt to make integration through `Integrator` API is still very possible.

3. I am not a guru. When I read a guide in implementing extensions for Quarkus ideas does not come out as I haven't develop "frameworks"/"libraries" before. Only business solutions. That said any help and advise highly appreciated.

 <a name="dark">On the other hand:</a>
1. "Blaze persistence" already nicely integrated with "CDI" (e.g. "Weld") so it may be that 90% of work is done. 

**Implementation ideas**
As pointed out in [WRITING YOUR OWN EXTENSION - 1.5. Some types of extensions](https://quarkus.io/guides/extension-authors-guide#some-types-of-extensions)

1. _~Bare library running~_ - this one is not option

2. _Get a framework running_ - probably the one we need.

3. _**Get a CDI portable extension running**_ - this one actually even sounds more attractive and interesting and very close to what I mentioned in ["On the other hand..."](#dark). Wish this is the one we need.

[Here is a Blaze Persistence guru comment](https://github.com/Blazebit/blaze-persistence/issues/817#issuecomment-512037795) (@JWGmeligMeyling):
> An NPE at [line 58](https://github.com/Blazebit/blaze-persistence/blob/1.3.2/integration/hibernate-5.3/src/main/java/com/blazebit/persistence/integration/hibernate/Hibernate53Integrator.java#L58) indicates that the [Database](https://github.com/Blazebit/blaze-persistence/blob/1.3.2/integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/Database.java) service binding is not available. Missing services indicate a classpath problem. Java's Service Provider mechanism is described in for example this blogpost. The services are usually registered through resource files in `META-INF/services`. Recently I stumbled upon a very similar issue myself, when I was creating a WildFly module for Blaze-Persist (documented on [Slack](https://blazebit.slack.com/archives/C2MPH23V0/p1551196645049700)). I don't know how Quarkus works, but I suppose it creates some sort of special classpath where services from libraries are hidden, or the Service Provider API is not available at all. From a simple Google search I cannot easily find examples of the Service Provider API within Quarkus.
> One thing that you might want to try is to copy the contents of the `META-INF/services` folder of the jar dependencies to your applications `META-INF/services` folder.
> This should at least contain the files:
>
> ```
> com.blazebit.persistence.integration.hibernate.base.HibernateAccess
> com.blazebit.persistence.spi.EntityManagerFactoryIntegrator
> org.hibernate.boot.spi.MetadataContributor
> org.hibernate.integrator.spi.Integrator
> org.hibernate.persister.spi.PersisterClassResolver
> org.hibernate.service.spi.ServiceContributor
> ```
>these are the ones from `blaze-persistence-integration-hibernate-5.3:1.3.2`, but the other jars probably have services too
 
What do you think guys?

**Comment by Sanne** [comment]
Very interesting idea, but to be honest we also strive to be "opinionated": suggest one single good apprach to do something.

Did you have a look at our Panache extension?
 - https://quarkus.io/guides/hibernate-orm-panache-guide

How would that play out with Blaze, would you see them as competing approaches?

Regarding the concerns you have:

**1 - basing on javassist**

we would prefer it to use Byte Buddy or ASM, but it's not a blocking problem. Generally speaking maintaining javassist has been a challenge with all the new JDKs being released frequently - I'd hope Blaze could migrate, or use the Quarkus native enhancers ?

**2 - Hibernate internal APIs**

no worries, Quarkus is using the real Hibernate ORM: it's not a fork. All patches we needed have been integrated in Hibernate ORM, this was released and that's what Quarkus uses.
The only restriction would be that Quarkus can only use very up to date version of Hibernate libraries, as obviously they need to include the patches we needed.

**I am not a guru. **

Don't worry, nobody is ;) We're friendly and will be happy to have a look at prototypes and any early stage patches, to help and learn from each other.

**Comment by Sanne** [comment]
P.S. Quarkus has been created by the same people maintaining Hibernate : that might help clarify some things?

Also, Hibernate is deprecating the use of javassist as well.

**Comment by soberich** [comment]
@Sanne 
1. Which of the extensions is most similar to this one which should be implemented? To borrow ideas..
2. Which of the extensions is the number 3 in the list of possible approaches? E.g. "flexible CDI extension"
3. Which is number 2?
4. Which approach do you recommend from between the two for Blaze Persistence extension?

**Comment by JWGmeligMeyling** [comment]
AFAIK only Blaze-Persists entity-views require javassist, and the exception thrown currently is not javassist related. If a recent version of Hibernate works without changes, the majority of Blaze-Persist should have worked out of the box. Currently  the problem seems to be related to the frameworks internal Service Bindings (which are used to separate interface and implementation) not being resolved.

@Sanne are you aware of any limitations w.r.t. ServiceBindings in Quarkus?

**Comment by Sanne** [comment]
The problem with service providers is just that they load by reflection.

You can't load classes dynamically, so we try to differentiate between
 a) classes which need to be discovered during "initialization" e.g. discovery of extension points should be run at build time, not at runtime. You'll see that most of Hibernate ORM is initialized during the build, we then take a snapshot of it - that's also why it's much faster to boot.
 b) classes which need to be accessed via reflection at runtime (e.g. Entities) need to be registered for reflective access explicitly.

I'm sure both of these points will come at a surprise as they are very new concepts comparing to traditional Java development, but be reassured that it's not that hard once you overcome the new concepts - and the Quarkus extensions API give you simple access to make such things happen.

Specifically, to get a service provider to work have a look at `io.quarkus.deployment.builditem.substrate.ServiceProviderBuildItem`.

Also worth reading:
 - https://quarkus.io/guides/extension-authors-guide
 - https://quarkus.io/guides/writing-native-applications-tips

> AFAIK only Blaze-Persists entity-views require javassist

Ok that might simplify things, however the native-image compiler can't deal with "broken classpath" aka "optional dependencies": if some code needs Javassist, it needs to be fully disabled or you will need Javassist compiled too - which is probably much harder.

I guess this is more easily understood when you'll see the compiler error :)
We'll either need a flag in Blaze to fully disable this capability, or patch it to remove javassist, or use a Substitution to disable the feature in Quarkus only.

**Comment by JWGmeligMeyling** [comment]
Thanks @Sanne for your remarks, these will definitely help with getting an initial integration going! We'll see how far we get before running into the next compiler errors 😉

**Comment by soberich** [comment]
Regarding NPE while staring up Blaze on Quarkus, I believe it should go away if we build a descent  integration between the two.
It looks like [ProxyFactory.java](https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/proxy/ProxyFactory.java) should be re-written to ByteBuddy. I don't see integration much attractive without EntityViews.
@Sanne just a ping regarding my questions. Thank you in advance.

**Comment by gsmet** [comment]
@beikov the extension needs to have a proper `quarkus-extension.yaml` and be added to the platform here: https://github.com/quarkusio/quarkus-platform .

See the already existing ones and also how they integrate their IT into the platform with rpkg.

Also it needs to be part of the Quarkus ecosystem CI so that you and the Quarkus team are notified if master breaks your extension: https://github.com/quarkusio/quarkus-ecosystem-ci/ .

@geoand can help you on the latter.

**Comment by gsmet** [comment]
It might also be cool to add a guide and a quickstart but this can be done later.

**Comment by geoand** [comment]
Sure thing.  @beikov feel to reach out to me for anything you need about ecosystem-ci or Quarkus platform

**Comment by Mobe91** [comment]
@gsmet The guide under https://github.com/quarkusio/quarkus-ecosystem-ci/ says that I need to generate a github token from the user that opened this issue (in this case @soberich ). Since I am dealing with this integration it would be nice if I could use my own token. Should I create a new issue for this or how do you want me to go about it? As far as I understand, this token is only used initially for closing the extension request issue once the CI passes, right?

**Comment by geoand** [comment]
@Mobe91 your understanding is correct.

You should open a new issue with your user  and then create a token for you user and configure it in the secrets of your repo. You can see the process [here](https://www.youtube.com/watch?v=VpbRA1n0hHQ)

**Comment by soberich** [comment]
@Mobe91 For sure. I never get to this and only viewing this great progress from the side.

**Comment by beikov** [comment]
The ecosystem-ci almost works now and we are about to release our current version. How can we get listed then in the extension catalog at https://code.quarkus.io/ ?

**Comment by geoand** [comment]
That requires adding the extension (when it's released) to the Quarkus platform: https://github.com/quarkusio/quarkus-platform

**Comment by geoand** [comment]
I'm closing this as the desired extension is part of the Quarkus Platform
