### ISSUE TITLE
Tests run in DEV mode are now logged with short names, previously signature was present

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#33744]
### Describe the bug

Before https://github.com/quarkusio/quarkus/pull/33685 our DEV mode test contained: 
```
17:45:10,608 INFO  [app] Running 1/1. Running: io.quarkus.ts.http.minimum.HelloResourceTest#HelloResourceTest
```
now it contains
```
17:53:53,032 INFO  [app] Running 1/1. Running: #HelloResourceTest
```

I can so no information about this in PR description or note in migration guide or anything, therefore there is no way to tell whether this change is intentional or side effect.

### Expected behavior

Previous behavior was clearer, but I just need a confirmation this was intentional change, that's all.

### Actual behavior

`io.quarkus.ts.http.minimum.HelloResourceTest#HelloResourceTest` => `HelloResourceTest`

### How to Reproduce?

Reproducer:

1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git`
2. `cd quarkus-test-suite/http/http-minimum-reactive`
3.  `git checkout -b reproducer/domain-socket-vertx-bump`
4. `mvn clean verify -Dit.test=DevModeHttpMinimumReactiveIT`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1

**Comment by rsvoboda** [comment]
I would say FQCN should be present in the log
