### ISSUE TITLE
RequireUpperBoundDeps error when having dependency on quarkus-universe-bom and quarkus-picocli

### ISSUE THREAD

**Issue by kerogers-cloudbees** [quarkusio/quarkus#33751]
### Describe the bug

Maven project that has dependencies declared for quarkus-universe-bom version 3.1.0.Final and quarkus-picocli 3.1.0.Final will encounter a maven RequiredUpperBoundDeps error during enforcement.

The quarkus-universe-bom declares a dependency on io.smallrye:mutiny:2.1.0. The quarkus-picocli project depends on quarkus.arc:3.1.0.Final and that project does not depend on the quarkus-universe-bom and declares a dependency on io.smallrye:mutiny:2.2.0.

### Expected behavior

The goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (upper-bounds) will not have any errors when depending on the same version of quarkus-universe-bom and quarkus-picocli.

### Actual behavior

The goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (upper-bounds) produces an error:
```
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for io.smallrye.reactive:mutiny:2.1.0 paths to dependency are:
+-com.example:example:1.0.0-dev
  +-io.quarkus:quarkus-picocli:3.1.0.Final
    +-io.quarkus:quarkus-arc:3.1.0.Final
      +-io.quarkus.arc:arc:3.1.0.Final
        +-io.smallrye.reactive:mutiny:2.1.0 (managed) <-- io.smallrye.reactive:mutiny:2.2.0
]
``` 

### How to Reproduce?

Reproducer: https://github.com/kerogers-cloudbees/mutiny-reproducer

Steps to reproduce:
1. mvn validate

### Output of `uname -a` or `ver`

Darwin cb-laptop 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by kerogers-cloudbees** [comment]
I think this is a specific case of the issue #30804

**Comment by gsmet** [comment]
I will close this one.
We can improve on specific projects that are in our reach but we can't guarantee everything is aligned in our dependency tree as we would have to release a significant part of the ecosystem to keep things aligned (including projects we don't maintain): that's also why we have our BOM.
