### ISSUE TITLE
OpenTelemetry Context not propagated when using Quarkus Reactive Rest Client on Startup

### ISSUE THREAD

**Issue by siewp** [quarkusio/quarkus#33791]
### Describe the bug

When I am trying to fetch data with the Rest Client on start of the Application and trace it using OpenTelemetry, the spans result in different traces as you can see in the screenshots of Jaeger below. I annotated the Application startup method with `@WithSpan` and was expecting that the context is propagated to the corresponding Rest Client span such that, there is only one trace containing the two spans.

![grafik](https://github.com/quarkusio/quarkus/assets/8521288/c4a8f9b2-ee2f-4cc6-b446-f8fe7c811365)

### Expected behavior

The span context of the startup method is propagated to the Rest Client span and there is only one trace.

### Actual behavior

It seems, the span context of the startup method is not propagated correctly to the Rest Client span. This results in two different traces.

### How to Reproduce?

Just add the @WithSpan Annotation to the Startup method and use the RestClient there.
I pushed a reproducer here: https://github.com/siewp/startup-otel-propagation-issue

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

17

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by brunobat** [comment]
@siewp does this happen only on startup and later gets better?

**Comment by siewp** [comment]
@brunobat I saw this only when a method is annotated with `@Startup` and `@WithSpan`. Same behavior if the Rest Client is nested in another method and this method is called from the startup method. But it works in other methods e.g. REST endpoints.

**Comment by Sgitario** [comment]
@brunobat is this something entirely for opentelemetry or is there something to be updated in REST Client instead? Just asking if you want me to look at this.

**Comment by brunobat** [comment]
Not sure. Will have to debug it. It might be a race condition issue like in here: https://github.com/quarkusio/quarkus/issues/32923

**Comment by geoand** [comment]
@siewp is this still a problem with `Quarkus 3.2.0.Final`?

**Comment by siewp** [comment]
@geoand Sorry, I was on vacation. I tried it in Quarkus `3.2.0.Final` and it works now 👍

**Comment by geoand** [comment]
Thanks for  checking!
