### ISSUE TITLE
Is there any problem with relative paths in Quarkus native ?

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#33797]
### Discussed in https://github.com/quarkusio/quarkus/discussions/33796

<div type='discussions-op-text'>

<sup>Originally posted by **nicolasduminil** June  2, 2023</sup>
Hi,

I'm compiling in native mode a Quarkus application that works as expected in JVM mode. It happens to be a Camel application which one of the routes looks like:

       ...
       fromF("file://%s?include=.*.xml&delete=true&idempotent=true&bridgeErrorHandler=true", inBox)
         .doTry()
           .to("validator:xsd/money-transfers.xsd")
       ...
This route is polling an input folder and, as soon as an XML file lands in it, it tries to validate it against the schema named `money-transfers.xsd`, found in the `xsd` directory. This directory is located in `src/main/resources` folder of the maven project and, after the build, it lands at the root of the resulting JAR.

This works as expected in JVM mode but, trying to run it in native mode raises the following exception:

    2023-06-02 14:18:48,788 ERROR [org.apa.cam.imp.eng.AbstractCamelContext] (main) Error starting CamelContext (camel-1) due to exception thrown: Failed to start route route1 because of null: org.apache.camel.FailedToStartRouteException: Failed to start route route1 because of null
    ...
    Caused by: org.apache.camel.RuntimeCamelException: java.io.FileNotFoundException: Cannot find resource: xsd/money-transfer.xsd for URI: xsd/money-transfer.xsd
        at  org.apache.camel.component.validator.DefaultLSResourceResolver$DefaultLSInput.getByteStream(DefaultLSResourceResolver.java:139)

In the JAR associated to the native image I have:

    $ jar tvf target/aws-camelk-file-native-image-source-jar/aws-camelk-file-runner.jar
      ...
          0 Fri Jun 02 14:16:44 CEST 2023 xsd/
          890 Fri Jun 02 14:16:44 CEST 2023 xsd/money-transfers.xsd
         2118 Fri Jun 02 14:16:44 CEST 2023 xsd/money-transfer.xsd
    ...

Is there any reason not to be able to locate the mentioned file ?

Many thanks in advance.

Nicolas

</div>

**Comment by nicolasduminil** [comment]
Just wanted to mention that running the docker image produced by Quarkus native doesn't raise the mentioned exception. Also, connecting to this runtime, I get this:

    $ docker exec -ti aws-camelk-file /bin/bash
    [jboss@cec73e80f55c ~]$ ls
    app  lib  quarkus  quarkus-run.jar
    [jboss@cec73e80f55c ~]$ ls app
    aws-camelk-file.jar
    [jboss@cec73e80f55c ~]$ ls quarkus
    generated-bytecode.jar  quarkus-application.dat

Here the only relevant file is `app/aws-camelk-file.jar` which contains:

         0 Sat May 27 00:36:48 CEST 2023 xsd/
       890 Sat May 27 00:36:48 CEST 2023 xsd/money-transfers.xsd
      2118 Sat May 27 00:36:48 CEST 2023 xsd/money-transfer.xsd
       548 Sat May 27 00:36:48 CEST 2023 application.properties
         0 Sat May 27 00:36:48 CEST 2023 fr/
         0 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/
         0 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/quarkus/
         0 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/quarkus/camel/
         0 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/quarkus/camel/integrations/
         0 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/quarkus/camel/integrations/file/
      5112 Sat May 27 00:36:48 CEST 2023 fr/simplex_software/quarkus/camel/integrations/file/FileToS3Route.class
So, here I see that the file xsd/money-transfers.xsd, flagged as not found, exists in deed.

**Comment by nicolasduminil** [comment]
Anyone please ?

**Comment by jamesnetherton** [comment]
If you want `validator` to read from the classpath, then any files you want to read need to be added to the native image.

https://camel.apache.org/camel-quarkus/3.0.x/user-guide/native-mode.html#embedding-resource-in-native-executable

So this should work for you:

```
quarkus.native.resources.includes = xsd/*
```

**Comment by nicolasduminil** [comment]
It should but it doesn't. I didn't think to mention that I was using already this property, given that inspecting the native image, I've confirmed that the files flagged as not found were, as a matter of fact, in the native image. Please read above for more explanations. And in doubt, [here](https://github.com/nicolasduminil/aws-camelk/blob/native/aws-camelk-file/src/main/resources/application.properties) is the reproducer.
