### ISSUE TITLE
Smal typo in OIDC recorder

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#33798]
### Describe the bug

If the oidc server is not available at startup, the recorder will state : 

'OIDC Server is not available'. OIDC server is not available yet, an attempt to connect will be made duiring the first request. Access to resources protected by this tenant may fail if OIDC server will not become available'

### Expected behavior

The error message should be :

'OIDC Server is not available'. OIDC server is not available yet, an attempt to connect will be made duiring the first request. Access to resources protected by this tenant may fail if OIDC server will not become available'

### Quarkus version or git rev

main

**Comment by sberyozkin** [comment]
Fixed by #33799
