### ISSUE TITLE
Update generated Dockerfiles .. using `quarkus update`?

### ISSUE THREAD

**Issue by kdubois** [quarkusio/quarkus#33792]
### Description

Unless I'm missing something, right now there doesn't seem an automated way to update the generated Dockerfiles with the latest (stable) base images.   

I usually create a new app and copy/paste the newer Dockerfiles into my project but I feel like there could be a better way to keep images up to date and not have users inadvertently use outdated base images with potential security issues. 

### Implementation ideas

Would it be feasible to add this capability to the quarkus update script?  

I suppose it may need a prompt to ask if you want this to happen in case you've customized your Dockerfiles though, some ideas on how to make this less intrusive could be to either prompt the user if it's part of the standard `quarkus update` script; or maybe it can be made part of the quarkus image subcommand? eg. `quarkus image update`?

**Comment by maxandersen** [comment]
i think the "right" solution for this is https://github.com/quarkusio/quarkus/issues/24502

then we can generate dockerfiles based on the app rather than rely on updates.
