### ISSUE TITLE
 Quarkus 3.1.0 Infinite recursion (StackOverflowError)

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#33801]
### Describe the bug

In some cases I get `com.fasterxml.jackson.databind.JsonMappingException Infinite recursion (StackOverflowError)` error with quarkus 3.1.0 but not with 3.0.4
How to reproduce:
[json-serialization-error.tar.gz](https://github.com/quarkusio/quarkus/files/11638397/json-serialization-error.tar.gz)
- extract and run `./mvnw verify`
or
- run `./mvnw quarkus:dev` and then curl `localhost:8080/hello`, `curl localhost:8080/greeting`, `curl localhost:8080/greetingrecord`

Expected behavior as with 3.0.4, no errors should be thrown

**Comment by geoand** [comment]
This is not a Quarkus specific issue. Please open an issue on the Jackson Databind repository.

**Comment by gsmet** [comment]
That might be relevant for us though. Maybe we need to downgrade Jackson if there is a blocking issue in it?
