### ISSUE TITLE
Support letsencrypt

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#3380]
We want to make ssl with letsencrypt trivial to do with quarkus. We need a new `quarkus-letsencrypt` extension which has two modes of operation:

- standalone: quarkus is assumed to be terminating its own ssl connection. In PROD mode, the extension will contact letsencrypt to ask for a certificate, and serve the challenge over port 80. Once the certificate is obtained, the extension will store it in a configurable location, then start the ssl port and bootstrap is done. A scheduled quarkus task will then check for certificate renewal, redo the challenge when the time is right, overwrite the certificate and make sure it's reloaded.
- certbot: quarkus can run in openshift, or anything with load-balancing, and `certbot` is responsible for managing certificate obtention and renewal. Quarkus does not terminate its SSL connection, so we're only listening on port 80. The new extension only has to make sure that it serves any file present in a configurable filesystem folder on the `/.well-known` path. Certbot will then be responsible for putting the challenges on that folder and we only have to serve it for `certbot` to obtain/renew the certificate.

I think `certbot` mode should be the default, because the `standalone` mode is network-active, and it should only be called in production.

Configuration:

`quarkus.letsencrypt.mode`: `certbot*, standalone`
`quarkus.letsencrypt.certificate.path`: path to where we store the certificate/private key, defaults to `run/letsencrypt/cert`
`quarkus.letsencrypt.challenge.path`: path to where we store/serve the challenges, defaults to `run/letsencrypt/challenge`

**Comment by gsmet** [comment]
@ia3andy I'm interested in your feedback setting Let's Encrypt on the launcher with OpenShift. Did you have to include things in your Quarkus application or was it all taken care of by OpenShift?

**Comment by gsmet** [comment]
@ia3andy pointed me to https://servicesblog.redhat.com/2019/03/15/dynamic-ssl-certificates-using-letsencrypt-on-openshift/ .

AFAICS, on OpenShift, you can manage everything via OpenShift and it doesn't require anything in the Quarkus app.

**Comment by FroMage** [comment]
Oh cool, then OpenShift does not need this extension :)

**Comment by FroMage** [comment]
Well, we can always wait until someone asks for this.

**Comment by KrisGerhard** [comment]
This would be neat! We could really use it!

**Comment by janseeger** [comment]
Second that. Would be really nice to have.

**Comment by ia3andy** [comment]
I just configured a cluster with openshift-acme and it works great:
https://github.com/tnozicka/openshift-acme

Once installed you just need to add the acme annotation on the normal http route:
```yaml
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
```

Something nice would be to make the annotations configurable from Quarkus config.

Currently I override the route through `src/main/kubernetes/openshift.yml`:
```yaml
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ...
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  to:
    kind: Service
    name: ...
    weight: 100
  port:
    targetPort: 8080
```

**Comment by indiealexh** [comment]
Something to note, if youre OS cluster is setup for it you can just add

```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
```

to the route definition and it'll automagically attach the TLS too
