### ISSUE TITLE
A normal scoped bean implemented as Java record cannot be serialised to json

### ISSUE THREAD

**Issue by JackyAnn** [quarkusio/quarkus#33810]
### Describe the bug

``` 
  /**
   * 
   * Can not be serialised
   * @return
   */
  @Produces
  @ApplicationScoped
  public ApplicationRecord create1(){
    return new ApplicationRecord("ApplicationRecord");
  }

  @Produces
  @Singleton
  public SingletonRecord create2(){
    return new SingletonRecord("SingletonRecord");
  }

  public record ApplicationRecord(String name){

  }

  public record SingletonRecord(String name){

  }
```

```
@QuarkusTest
public class GreetingResource1Test {
    @Inject
    private JsonConfigCustomizer.ApplicationRecord applicationRecord;
    @Inject
    private JsonConfigCustomizer.SingletonRecord singletonRecord;
    @Inject
    private Jsonb jsonb;

    @Test
    public void testHelloEndpoint() {
        /**
         * print
         * {}
         */
        System.out.println("---"+jsonb.toJson(applicationRecord));
        
        /**
         * print
         * {
         *     "name": "SingletonRecord"
         * }
         */
        System.out.println("---"+jsonb.toJson(singletonRecord));
    }




}

```

### Output of `uname -a` or `ver`

Darwin jackydeMacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "20" 2023-03-21 Java(TM) SE Runtime Environment (build 20+36-2344) Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

### Quarkus version or git rev

3.1.0.Final

**Comment by JackyAnn** [comment]
demo
https://github.com/JackyAnn/quarkus-devui-issues.git

**Comment by mkouba** [comment]
@JackyAnn thanks for the rerport. Could you be more specific? What exactly does not work? It seems that you're trying to serialize an `@ApplicationScoped` CDI bean represented by a Java record to JSON using jsonb, right?

**Comment by Ladicek** [comment]
At first glance, I don't think it really matters that the bean is a `record` -- the cause here is that it is normal scoped. That is, you're trying to serialize the client proxy. Could you please try `jsonb.toJson(ClientProxy.unwrap(applicationRecord))` and report back?

**Comment by JackyAnn** [comment]
@mkouba 
It does not matter whether the bean is a record or a class.

**Comment by Ladicek** [comment]
OK, _that_ sounds weird. I'll take a proper look.

**Comment by Ladicek** [comment]
I have reproduced this locally with my own code and there's one _really_ frustrating thing. If I declare

```java
public class Producers {
    @Produces
    @ApplicationScoped
    public App app() {
        return new App("Application");
    }

    @Produces
    @Singleton
    public Sing sing() {
        return new Sing("Singleton");
    }

    public record App(String name) {
    }

    public record Sing(String name) {
    }
}
```

then `Producers.App.class.isRecord()` returns `false` for me (while `Producers.Sing.class.isRecord()` is `true` as expected). I have _no_ idea why.

I'm using OpenJDK 17.0.7.

**Comment by Ladicek** [comment]
Ahh I think I know! We do a bytecode transformation on `App` which removes the `final` flag from the class and adds a zero-parameter constructor. In my JDK source code, `Class.isRecord()` looks like this:

```java
public boolean isRecord() {
    // this superclass and final modifier check is not strictly necessary
    // they are intrinsified and serve as a fast-path check
    return getSuperclass() == java.lang.Record.class &&
            (this.getModifiers() & Modifier.FINAL) != 0 &&
            isRecord0();
}
```

The class doesn't have the `final` flag, therefore `Class.isRecord()` returns `false`, and that causes Yasson to not use the special case for treating record component accessor methods as getters. Phew!

**Comment by Ladicek** [comment]
I think we probably shouldn't remove the `final` flag from records. That would prevent using records as normal scoped beans, which is probably a good idea anyway.

**Comment by manovotn** [comment]
> That would prevent using records as normal scoped beans, which is probably a good idea anyway.

Yea, that sounds fishy anyway.
I was thinking about records and CDI anyway - now that next CDI version is on JDK 17+, we should perhaps add a note about this into the spec? I can create an issue

**Comment by mkouba** [comment]
> I think we probably shouldn't remove the `final` flag from records. That would prevent using records as normal scoped beans, which is probably a good idea anyway.

:+1:
