### ISSUE TITLE
No current Vertx context found in Startup Bean

### ISSUE THREAD

**Issue by DMaxter** [quarkusio/quarkus#33814]
### Describe the bug

When using Hibernate Panache Reactive on Quarkus 3, I need to initialize some data at the very start of the server.

To achieve this I have a bean with the `@Startup`  annotation and to perform the needed operations I have a method with the `@PostConstruct` annotation.

Whenever I try to start the Quarkus Server I obtain this error:
```
Failed to start application (with profile [dev]): java.lang.IllegalStateException: No current Vertx context found
```

And the line it occurs is on `Panache.withTransaction`.

This wasn't an issue back on Quarkus 2.X

### Expected behavior

Access to the database should be provided

### Actual behavior

Exception raised when trying to create a transaction

### How to Reproduce?

Reproducer:  [reproducer.zip](https://github.com/quarkusio/quarkus/files/11645838/reproducer.zip)

Steps:
1. Run the server and see the exception

### Output of `uname -a` or `ver`

Linux zirconium 6.3.4-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 29 May 2023 13:57:55 +0000 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7)
OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)
```

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 15:50:53 UTC
Revision:     <unknown>

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Oracle Corporation 17.0.7+7)
OS:           Linux 6.3.4-zen2-1-zen amd64
```

**Comment by mkouba** [comment]
@DMaxter thanks for the report! 

You'll need to execute your async code via the `io.quarkus.vertx.VertxContextSupport.subscribeAndAwait()` util method. See the [Executing Asynchronous Code From a Blocking Thread](https://quarkus.io/guides/vertx#executing-asynchronous-code-from-a-blocking-thread) docs.

> This wasn't an issue back on Quarkus 2.X

Yes, some breaking changes in Hibernate Reactive Panache were introduced in quarkus 3.0. See also the [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#hibernate-reactive-panache).

**Comment by DMaxter** [comment]
I can't find `VertxContextSupport` in the package `io.quarkus.vertx`

**Comment by DMaxter** [comment]
With VertxContextSupport it worked. Thanks for your help
