### ISSUE TITLE
Quarkus BOM references many missing artifacts

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#33835]
### Describe the bug

The Quarkus BOM references many artifacts which don't appear to exist, at least in Maven Central:

```
com.google.auto.service:auto-service-annotations:1.3.5
com.google.auto.service:auto-service:1.3.5
io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-jaeger-deployment:1.0.0
io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-jaeger:1.0.0
io.smallrye.reactive:smallrye-mutiny-vertx-health-checks:3.3.0
io.vertx:vertx-consul:4.4.1
io.vertx:vertx-jgroups:4.4.1
io.vertx:vertx-jwt:4.4.1
io.vertx:vertx-lang-groovy-parent:4.4.1
io.vertx:vertx-lang-kotlin-compiler:4.4.1
io.vertx:vertx-maven-service-factory-parent:4.4.1
io.vertx:vertx-sql-common:4.4.1
org.gradle:gradle-tooling-api:8.1.1
org.jboss.resteasy:resteasy-context-propagation:6.2.1.Final
org.opensaml:opensaml-saml-impl:4.2.0
org.opensaml:opensaml-xacml-impl:4.2.0
org.opensaml:opensaml-xacml-saml-impl:4.2.0
```

### Quarkus version or git rev

3.0.3.Final

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by gsmet** [comment]
@jskillin-idt thanks for the report. Could you clarify the groupId:artifactId of the BOM you're talking about?

Thanks.

**Comment by jskillin-idt** [comment]
The GAV is io.quarkus:quarkus-bom:3.0.3.Final

**Comment by gsmet** [comment]
Hmmm, I will have a look. I could have understood the presence of them in the `io.quarkus.platform` BOM given it's an aggregation of several BOM files but I'm surprised our own BOM contains non-existing artifacts.

**Comment by aloubyansky** [comment]
That's not news @gsmet. @cescoffier has already opened PRs in Vert.X to clean most of them up.

**Comment by aloubyansky** [comment]
I think the rest of the platform BOMs will be clean due to filtering applied during the alignment. Some projects managed in quarkus-bom are still leaking non-existing constraints due to their special handling.

**Comment by cescoffier** [comment]
* For Vert.x is will be fixed with the next update.
* I'm still chasing `io.smallrye.reactive:smallrye-mutiny-vertx-health-checks:3.3.0`
* I don't know about the other ones.

**Comment by gsmet** [comment]
> com.google.auto.service:auto-service-annotations:1.3.5
> com.google.auto.service:auto-service:1.3.5

These ones come from an external BOM we import.

> io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-jaeger-deployment:1.0.0
> io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-jaeger:1.0.0

The versions in the relocations were wrong. I fixed them.

> io.smallrye.reactive:smallrye-mutiny-vertx-health-checks:3.3.0
> io.vertx:vertx-consul:4.4.1
> io.vertx:vertx-jgroups:4.4.1
> io.vertx:vertx-jwt:4.4.1
> io.vertx:vertx-lang-groovy-parent:4.4.1
> io.vertx:vertx-lang-kotlin-compiler:4.4.1
> io.vertx:vertx-maven-service-factory-parent:4.4.1
> io.vertx:vertx-sql-common:4.4.1

Either already fixed or @cescoffier is on them.

> org.gradle:gradle-tooling-api:8.1.1

This one we need but Gradle doesn't publish the artifacts to Maven Central.

> org.jboss.resteasy:resteasy-context-propagation:6.2.1.Final

This one doesn't exist anymore, I dropped it.

> org.opensaml:opensaml-saml-impl:4.2.0
> org.opensaml:opensaml-xacml-impl:4.2.0
> org.opensaml:opensaml-xacml-saml-impl:4.2.0

These ones come from an external BOM.

I created https://github.com/quarkusio/quarkus/pull/33898 with the fixes I could apply. @aloubyansky do you have a tool to understand where the ones coming from external BOMs are coming from?

**Comment by gsmet** [comment]
@aloubyansky btw, if you have a tool, maybe you can tell @cescoffier where io.smallrye.reactive:smallrye-mutiny-vertx-health-checks is coming from.

**Comment by aloubyansky** [comment]
Not sure about the actual chain but just in case I see it in https://github.com/smallrye/smallrye-mutiny-vertx-bindings/blob/main/vertx-mutiny-clients-bom/pom.xml

**Comment by cescoffier** [comment]
I've fixed it this morning. I'm cutting a release right now.

**Comment by gsmet** [comment]
I think we can close this one. We fixed what was on our side. For things coming from external BOMs, please report them to the appropriate projects.
