### ISSUE TITLE
Error Code 137 and 143 on OCP while downscaling

### ISSUE THREAD

**Issue by MengdanCode** [quarkusio/quarkus#3383]
**Describe the bug**
After deploying the Quarkus quick start sample application to OCP3.11, I'm seeing errors while downscaling the application. If the application is deployed using s2i, error code 137 is shown. And if the application is compiled locally using the given Dockerfile then deployed to OCP, error code 143 will be given while downscaling. 

**Expected behavior**
The application should be downscaled gracefully.  

**Actual behavior**
OCP is showing errors while downscaling. 

**To Reproduce**
1. Deploy Quarkus Quick Start sample project to OCP using s2i 
```oc new-app quay.io/quarkus/ubi-quarkus-native-s2i:19.0.2~https://github.com/quarkusio/quarkus-quickstarts.git --context-dir=getting-started --name=quarkus-quickstart-native```
2. After a successful build and deployment, scale up to 5 pods 
3. Scale down to 1 pod
4. An error message 137 will be shown as below: 
<img width="1017" alt="Screenshot 2019-07-31 at 15 59 17" src="https://user-images.githubusercontent.com/8488558/62201429-fb6c2100-b3b9-11e9-94f7-4c5f7ca1f453.png">
5. Build  sample project into docker images manually using command
```docker build -f src/main/docker/Dockerfile.native -t quarkus/getting-started .```

6. Push docker image to a docker registry
7. Create a new application on OCP using the remote docker image
8. Scale up to 5 pods
9. Scale down to 1 pod
10. An error message 143 will be shown:
<img width="1003" alt="Screenshot 2019-07-31 at 16 33 03" src="https://user-images.githubusercontent.com/8488558/62201666-746b7880-b3ba-11e9-95dc-a3c4d0d30fa1.png">

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - OCP version: 3.11
 - Quarkus version or git rev: https://github.com/quarkusio/quarkus-quickstarts

**Comment by geoand** [comment]
Closing this as it has not been issue since
