### ISSUE TITLE
Add Support for Mongo DB Client-Side Field Level Encryption (CSFLE)

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#33839]
### Description

In the construction of the mongo client, we need the ability to pass the CSFLE configuration object `autoEncryptionOpts`.

see [CSFLE-Specific MongoClient Options](https://www.mongodb.com/docs/manual/core/csfle/reference/csfle-options-clients/#std-label-csfle-reference-mongo-client)

### Implementation ideas

In `MongoClientConfig` add an additional configuration parameter `autoEncryptionOpts`. One question is whether the quarkus config object should reflect the entire `autoEncryptionOpts` data structure, or if we should just make it a json or yaml document that is later interpreted as a `autoEncryptionOpts` using jackson or json-b databinding.
In [MongoClients.createMongoConfiguration()](https://github.com/quarkusio/quarkus/blob/main/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClients.java#L255), use this parameter and populate the `MongoClientSettings` object accordingly.

**Comment by vsevel** [comment]
see [the zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Support.20to.20allow.20mongodb.20CSLFE.20in.20config.20file)

**Comment by loicmathieu** [comment]
I think it has been decided to allow customization of the client, this PR implement it: https://github.com/quarkusio/quarkus/pull/36503.

If it fits your need, we will close this issue.

**Comment by vsevel** [comment]
hi @loicmathieu checking with the team this week to see if we can test the feature

**Comment by vsevel** [comment]
from the documentation, the dev team is confident we will be able to work with this configuration approach.
thanks a lot for helping out.
