### ISSUE TITLE
AppCDS generation failed with `Permission denied`

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#33842]
### Describe the bug

Building application with AppCDS `gradle build -Dquarkus.package.create-appcds=true` failed with error
```
   > Could not copy file '/home/palo/git/app-cds-fail/build/quarkus-build/app/quarkus-app/app-cds.jsa' to '/home/palo/git/app-cds-fail/build/quarkus-app/app-cds.jsa'.
   > /home/palo/git/app-cds-fail/build/quarkus-app/app-cds.jsa (Permission denied)
```

### Expected behavior

AppCDS generation success.

### How to Reproduce?

Reproducer: https://github.com/paloliska/app-cds-fail

1. build with `gradle build -Dquarkus.package.create-appcds=true`

### Output of `uname -a` or `ver`

Linux *** 6.1.0-1013-oem #13-Ubuntu SMP PREEMPT_DYNAMIC Thu May 18 16:45:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2) OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.1.1

**Comment by geoand** [comment]
Interestingly enough, I was able to reproduce this after all.

**Comment by paloliska** [comment]
Just want to add: app-cds.jsa has read-only permissions:
```
drwxrwxr-x 1 palo palo      128 Jun  6 12:12 .
drwxrwxr-x 1 palo palo       76 Jun  6 12:12 ..
drwxrwxr-x 1 palo palo       62 Jun  6 12:12 app
-r--r--r-- 1 palo palo 23359488 Jun  6 12:12 app-cds.jsa
drwxrwxr-x 1 palo palo      138 Jun  6 12:12 quarkus
-rw-rw-r-- 1 palo palo     9548 Jun  6 12:12 quarkus-app-dependencies.txt
-rw-rw-r-- 1 palo palo      652 Jun  6 12:12 quarkus-run.jar
```

**Comment by snazy** [comment]
Wonder whether it's important that the AppCDS file is read-only (not sure whether that has some effect to how a JVM maps that file into memory).

Otherwise it might help to change the `sync` in `io.quarkus.gradle.tasks.QuarkusBuild#assembleFastJar` to:
```java
        getFileSystemOperations().delete(delete -> delete.delete(appTargetDir));
        getFileSystemOperations().copy(copy -> {
            copy.into(appTargetDir);
            copy.from(appBuildDir, depBuildDir);
        });
```

**Comment by geoand** [comment]
> Wonder whether it's important that the AppCDS file is read-only (not sure whether that has some effect to how a JVM maps that file into memory)

Yeah, it seems that the JVM creates it as read-only, but I have no idea why.

> Otherwise it might help to change the sync in io.quarkus.gradle.tasks.QuarkusBuild#assembleFastJar to:

I'll leave the Gradle stuff up to you :)
