### ISSUE TITLE
Can't detect the S3Client configuration in native mode

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#33849]
### Describe the bug

In a Quarkus 2.16.6.Final application, I'm using `software.amazon.awssdk.services.s3.S3Client `class. I have declared the following dependency:

        ...
        <dependency>
          <groupId>io.quarkus.platform</groupId>
          <artifactId>quarkus-amazon-services-bom</artifactId>
          <version>${quarkus.platform.version}</version>
          <type>pom</type>
          <scope>import</scope>
        </dependency>
        ...
        <dependency>
          <groupId>software.amazon.awssdk</groupId>
          <artifactId>url-connection-client</artifactId>
        </dependency>
        ...

And in the source code I'm injecting:

      @Inject
      S3Client s3client;
Everything worsk as expected in JVM mode but, in native mode, the following exception is raised:

    Caused by: java.lang.IllegalStateException: The S3Client is required but has not been detected/configured.
        at io.quarkus.amazon.s3.runtime.S3ClientProducer.client(S3ClientProducer.java:34)
        at  io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(Unknown Source)
        at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)

What am I doing wrong here ? My understanding is that the default value of the `quarkus-amazon-s3_quarkus.s3.sync-client.type` is `url`, so I don't need to declare it in `application.properties`, right ?

Many thanks in advance for any help.

Kind regards,

Nicolas

### Expected behavior

I expect that the application runs in native mode the same way it does in JVM mode, i.e. to detect the S3Client configuration.

### Actual behavior

In native mode, the application raises the mentioned exception.

### How to Reproduce?

Do the following in order to reproduce:

    $ git clone https://github.com/nicolasduminil/aws-camelk
    $ cd aws-camelk
    $ git checkout native
    $ cd aws-camelk-file
    $ mvn -DskipTests clean install
    $ ./target/aws-camelk-file-runner

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: /opt/apache-maven-3.6.3 Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-73-generic", arch: "amd64", family: "unix"

**Comment by galderz** [comment]
Have you installed the amazon s3 quarkus extension? https://quarkus.io/extensions/io.quarkiverse.amazonservices/quarkus-amazon-s3

**Comment by nicolasduminil** [comment]
I did, as you can see in the reproducer project:

    ...
    <dependency>
      <groupId>io.quarkiverse.amazonservices</groupId>
      <artifactId>quarkus-amazon-s3</artifactId>
   </dependency>
    ...
If I didn't, how could I compile things like:

    ...
    @Inject
    S3Client s3client;

Or how could I have managed to get it running in JVM mode ?

**Comment by gsmet** [comment]
Could you please open an issue in the Quarkus Amazon Services project here: https://github.com/quarkiverse/quarkus-amazon-services/issues ?

They will be able to help you more there. Make sure you also attach the reproducer.

Closing the issue as it's not a Quarkus issue per se.
