### ISSUE TITLE
`quarkus.otel.sdk.disabled` property doesn't follow naming standard to use `.enabled` suffix

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33845]
### Describe the bug

`quarkus.otel.sdk.disabled` property doesn't follow naming standard to use `.enabled` suffix

https://quarkus.io/guides/all-config#quarkus-opentelemetry_quarkus.otel.sdk.disabled

The common practice is to use `.enabled` suffix. There are 100+ cases with `.enabled` suffix when looking at https://quarkus.io/guides/all-config.

The only one with `.disabled` suffix is `quarkus.otel.sdk.disabled`. 

### Expected behavior

Use `.enabled` suffix

### Actual behavior

`quarkus.otel.sdk.disabled` property doesn't follow naming standard to use `.enabled` suffix

### How to Reproduce?

https://quarkus.io/guides/all-config#quarkus-opentelemetry_quarkus.otel.sdk.disabled

### Quarkus version or git rev

Quarkus 3.1.0.Final

**Comment by brunobat** [comment]
@rsvoboda this is per spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#general-sdk-configuration

It's like that because it's a safe default.

**Comment by geoand** [comment]
@brunobat should this be closed?

**Comment by brunobat** [comment]
I think so.
