### ISSUE TITLE
Quarkus gRPC guide doesn't have Gradle examples

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#33854]
### Describe the bug

The Quarkus gRPC guide (https://quarkus.io/guides/grpc-getting-started) only has maven examples but not the tabs with both Maven & Gradle like most of the other guides do.

Was it forgotten?

**Comment by cescoffier** [comment]
Not forgotten, it was written BEFORE we had that possibility.

Now... I've no idea how to configure it with Gradle :-D, so, delegating to @alesj .

**Comment by alesj** [comment]
Tnx ... :-)

**Comment by glefloch** [comment]
it looks like it has been addressed by #33437
