### ISSUE TITLE
Allow keycloak integration to be disabled

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#3385]
**Description**
Also a project might have quarkus-keycloak in the classpath, it should be possible to enable/disable it via a config param. 

**Implementation ideas**
this is how the config could look like: (at least how i use it in EDDI, being able to configure whether to use keycloak or basic auth, and which paths should not be protected by either method)

```
# quarkus.webServer.securityHandlerType -> none | basic | keycloak
quarkus.webServer.securityHandlerType=none
quarkus.webServer.publicAccessPaths=/bots/unrestricted/*;/health;/text/*;/binary/*
quarkus.webServer.basicAuth.defaultUsername=eddi
quarkus.webServer.basicAuth.defaultPassword=labsai
```

**Comment by sberyozkin** [comment]
As @loicmathieu suggested, for the consistency purposes with the other security extensions, the `enable` property should be introduced

**Comment by loicmathieu** [comment]
@sberyozkin now that keycloack is based on the OIDC extension and that OIDC extension provides an `enabled` property this should be close right ?

**Comment by gsmet** [comment]
Right.
