### ISSUE TITLE
Support passing environment variables to devservices containers

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#33864]
### Description

testcontainers has API to pass environment variables to the container:

https://www.javadoc.io/doc/org.testcontainers/testcontainers/latest/org/testcontainers/containers/GenericContainer.html#addEnv-java.lang.String-java.lang.String-

One possible usage, setting collation of `MSSQLServerContainer`:

    mssqlServerContainer.addEnv("MSSQL_COLLATION", "Arabic_100_CS_AS_KS_WS_SC_UTF8");

### Implementation ideas

Obtain environment variables from `application.properties` and pass them to devservices container:

> quarkus.datasource.devservices.container-enironment-variables.MSSQL_COLLATION=Arabic_100_CS_AS_KS_WS_SC_UTF8

similar to the [existing property](https://quarkus.io/guides/all-config#quarkus-datasource_quarkus.datasource.devservices.container-properties-container-properties):

> quarkus.datasource.devservices.container-properties.TC_MY_CNF

**Comment by geoand** [comment]
Seems reasonable.

Would you like to contribute this feature?

**Comment by Eng-Fouad** [comment]
Yes sure. This feature will be applied to all devservices not just database ones, right?

**Comment by geoand** [comment]
Ideally, yes

**Comment by gsmet** [comment]
@Eng-Fouad were you able to make progress on this? I saw another person asking something similar thus why I ask.

I think it would be a nice addition for Quarkus 3.2 so if you don't think you can make it done by next Monday, I might have a look at it.

Thanks for your feedback.

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad were you able to make progress on this? I saw another person asking something similar thus why I ask.
> 
> 
> 
> I think it would be a nice addition for Quarkus 3.2 so if you don't think you can make it done by next Monday, I might have a look at it.
> 
> 
> 
> Thanks for your feedback.

I haven't started yet. I am on vacation and will be back home after 10 days. If anyone wants to implement this, I am fine with that :)

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/34223 . I would appreciate if you could check it solves your problem.
