### ISSUE TITLE
Create developers profile in `pom.xml`

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkusio/quarkus#33862]
### Description

Create developers profile in `pom.xml` and add name, org and email id of Quarkus developers

### Implementation ideas

```
<developers>
        <developer>
            <name>Guillaume Smet</name>
            <email>guillaume.smet@gmail.com</email>
            <organization>Red Hat</organization>
            <organizationUrl>http://www.redhat.com</organizationUrl>
        </developer>
<developers>

**Comment by geoand** [comment]
Thanks for the suggestion, but I don't think we want to do this as there are too many developer to credit and would make the `pom.xml` unreadable.

**Comment by shivam-sharma7** [comment]
Np
