### ISSUE TITLE
[quarkus-container-image-docker] Build docker image with --pull option and more

### ISSUE THREAD

**Issue by Jacopo47** [quarkusio/quarkus#33866]
### Description

Let's take the initial dockerfile proposed by Quarkus in order to build a docker image with a native application:

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

My need is to not consider any kind cache while building. So, using plain docker command, something like: ```docker build --pull --no-cache .```

But looking at Quarkus' docker documentation: https://quarkus.io/guides/container-image#DockerOptions I don't find any useful option.

Looking at this class: https://github.com/quarkusio/quarkus/blob/main/extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerProcessor.java

I wasn't able to recognize any part in which is handling these options.

### Implementation ideas

I think that it would be helpful a property that allows to specify a list of additional options.
Something like: 

```quarkus.docker.options=--no-cache --pull --whatever-you-need```

P.S. Originally reported on [SO](https://stackoverflow.com/q/76415647/2504224).

**Comment by geoand** [comment]
I think it would be reasonable to add options for `--no-cache` and `--pull` to `DockerConfig`.

**Comment by geoand** [comment]
Actually you are probably right, giving users the ability to add whatever flags they want probably makes most sense and that is what https://github.com/quarkusio/quarkus/pull/33876 does.
