### ISSUE TITLE
quarkus-rest-client-reactive-jaxb does not support direct marshalling of JAXBElement<T>

### ISSUE THREAD

**Issue by rudiger3d** [quarkusio/quarkus#33875]
### Describe the bug

After writing the below explanation, I'm unsure if this should have been filed as a _Feature request_ or I'm just pointing out an implicit inconsistency in the support of JAXB. But anyway:

I'm doing a port of an old SB/camel service and I'm defining a REST client interface and need XML serialisation support. My "Xml" classes are generated with `xsdtojava` from a couple of xsd-files. I'm providing my own `JAXBContext` like described in this [guide](https://quarkus.io/guides/resteasy-reactive#customize-the-jaxb-configuration).

Because I'm just using the supplied xsd-files, my request model object is is in the form of `JAXBElement<eu.request.SomeType>`. I would have assumed that defining a method like this

```java
    @POST
    @Produces(MediaType.APPLICATION_XML)
    @Consumes(MediaType.APPLICATION_XML)
    eu.response.Response getVehicleByRegno(JAXBElement<eu.request.SomeType> request)
```

that the http-client would correctly serialize this xml element: 
```
JAXBElement<eu.request.SomeType> req = objectFactory.createKehys(messageType);
```

as

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<kehys>
...
</kehys>
```

However the element is marshalled as
 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<JAXBElement>
<kehys>
...
</kehys>
</JAXBElement>
```

After looking into the [implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive-jaxb/runtime/src/main/java/io/quarkus/rest/client/reactive/jaxb/runtime/ClientMessageBodyWriter.java)  of JAXB/Xml `MessageBodyWriter` I can see that only classes annotated with `XmlRootElement` are supported (the [server](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-jaxb/runtime/src/main/java/io/quarkus/resteasy/reactive/jaxb/runtime/serialisers/ServerJaxbMessageBodyWriter.java) version has the same limitation). If not annotated, the object in question is wrapped in a JAXBElement ([client implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive-jaxb/runtime/src/main/java/io/quarkus/rest/client/reactive/jaxb/runtime/ClientMessageBodyWriter.java#L49-L54)):

```java
            Object jaxbObject = o;
            Class<?> clazz = o.getClass();
            XmlRootElement jaxbElement = clazz.getAnnotation(XmlRootElement.class);
            if (jaxbElement == null) {
                jaxbObject = new JAXBElement(new QName(Introspector.decapitalize(clazz.getSimpleName())), clazz, o);
            }
```

This explains the extra `<JAXBElement>` in my generated xml above.

So my question or issue: 

Now that I can define my own JAXBContext that may include classes not annotated with `XmlRootElement`, shouldn't I be able to serialise them as well? 😃 

(As I'm porting a Camel service I checked how Camel checks if a Object is serialisable: [Camel](https://github.com/apache/camel/blob/main/components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/JaxbDataFormat.java#L204) uses `JAXBIntrospector.isElement(element)`)

### Expected behavior

Being able to generate XML based on classes in a provided JAXBContext.

### Actual behavior

Only classes annotated with `XmlRootElement` are probably supported. This is could be seen as "inconsistent" with the ability to provide your own JAXBContext.

### How to Reproduce?

If needed, I will provide a project that demonstrate the issue, but until then I think the explanation above sufficiently explains the issue.

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.16.2.Final

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/33924 should take care of this issue. @rudiger3d can you have a look just to confirm I understood correctly your issue?

**Comment by rudiger3d** [comment]
@Sgitario You understood the issue. 

I was about to make a comment about running into something similar with the [ClientJaxbMessageBodyReader implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive-jaxb/runtime/src/main/java/io/quarkus/rest/client/reactive/jaxb/runtime/ClientJaxbMessageBodyReader.java). However it doesn't seem to have similar restrictions so that's fine.

**Comment by Sgitario** [comment]
> @Sgitario You understood the issue.
> 
> I was about to make a comment about running into something similar with the [ClientJaxbMessageBodyReader implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive-jaxb/runtime/src/main/java/io/quarkus/rest/client/reactive/jaxb/runtime/ClientJaxbMessageBodyReader.java). However it doesn't seem to have similar restrictions so that's fine.
> 
> And thanks!

Great!
