### ISSUE TITLE
Vertx ConfigStores not working in native mode

### ISSUE THREAD

**Issue by trsantospt** [quarkusio/quarkus#3387]
I'm currently trying to migrate an existing application entirely made with Vertx to use Quarkus.
So far I successfully migrated to Quarkus and it's up and running in JVM mode. But when trying to run in native mode, even though it successfully builds the native runner, on execution it's raising me the following error:

```
ERROR [io.mob.gat.com.ver.bas.AbstractDeployVerticle] (vert.x-eventloop-thread-4) Error deploying verticles: java.lang.IllegalStateException: No configuration store implementations found on the classpath
        at io.vertx.config.impl.ConfigRetrieverImpl.<init>(ConfigRetrieverImpl.java:73)
        at io.vertx.config.ConfigRetriever.create(ConfigRetriever.java:52)
```
My Vertx application loads up configs from files using the Vertx ConfigStores. Apperently the following code is not returning any of the implementations:
```
ServiceLoader<ConfigStoreFactory> storeImpl =
        ServiceLoader.load(ConfigStoreFactory.class,
            ConfigStoreFactory.class.getClassLoader());
```
I suspect this is related to the classLoader for some reason. The way I'm registering the verticles is just inject the Vertx instance through Quarkus onStart. Also tried registering the ConfigStoreFactory interface and implementations for reflection but to no avail.

**To Reproduce**
1. Inject Vertx instance
2. Deploy sample verticle on that instance
3. Try to use ConfigRetriever.create(vertx) with the default config stores.

Sample source Maven project that reproduces the problem is attached.

[quarkus.vertx.config.tar.gz](https://github.com/quarkusio/quarkus/files/3452306/quarkus.vertx.config.tar.gz)

**Comment by trsantospt** [comment]
I found the solution for this.
To make it work I created a new Quarkus extension (quarkus-vertx-config) with a BuildStep to register the Vert.x configStores.

`io.quarkus.deployment.builditem.substrate.ServiceProviderBuildItem`

It now loads up configuration using pure Vertx configStores from different files and reloads just as fine!

**Comment by gsmet** [comment]
@cescoffier I wonder how we should treat this one:

1. do we want people to be able to use Vert.x Config or should we push for MP Config?
2. if yes to 1., should it be a separate extension or included in the Vert.x one?

**Comment by trsantospt** [comment]
@gsmet I think it could be supported although optional (such as persistence.xml), because it can make a huge difference for someone that's looking to migrate existing vertx applications into Quarkus as it is in our case.

**Comment by gsmet** [comment]
@cescoffier see my question above.

**Comment by svilenvul** [comment]
I also faced this issue while I tried to migrate an existing Vert.x project to Quarkus.

@trsantospt, could you share you solution? I don't have experience writing Quarkus plugins and it might be helpful to quickly check if smt else will pop up.

@gsmet, @cescoffier is it possible to move this issue forward? I think this will be useful for everybody who wants to migrate from Vert.x to Quarkus.

**Comment by cescoffier** [comment]
We should create an extension for vert.x config. It's relatively easy. However, some format would not be supported in native mode as the library used are not going to work in native.

**Comment by cescoffier** [comment]
Closing - out of date.

The config support of Quarkus has now more feature than the vert.x config. We can revisit and add support for the config store from vert.x one by one, but we would need to prioritize.
