### ISSUE TITLE
Gradle plugin does not copy all files correctly, when having parent-first-artifacts

### ISSUE THREAD

**Issue by Smudo99** [quarkusio/quarkus#33870]
### Describe the bug

I've a Quarkus project, which uses an own Jackson ObjectMapper, with that I had problems using the same ClassLoader for that lib. As a solution I added the lib to the property ```quarkus.class-loading.parent-first-artifacts```.
With Quarkus < 3.x this worked well. Now I've tried to migrate to Quarkus 3.x and I got a ClassNotFoundException.

After searching I found the reason. My lib - added via the parent-first-artifact - is copied during the build to ```build/quarkus-build/gen/querkus-app/lib/boot```, which is as expected. 
But in the next step, I would expect, that it should also be copied to ```build/quarkus-build/dep/lib/boot``` (and finally to ```build/quarkus-app/lib/boot```), but this doesn't happen. The lib is mentioned in the manifest file.

### Expected behavior

The parent-first-artifact lib is copied in the app folder.

### Actual behavior

JAR is not copied.

### How to Reproduce?

Run ```gradle build``` and the ```gson``` lib (just used as an example) was not copied to ```build/quarkus-build/dep/lib/boot```

[reproducer.zip](https://github.com/quarkusio/quarkus/files/11676041/reproducer.zip)

### Output of `uname -a` or `ver`

Darwin TMXQT47KNH 22.5.0 Darwin Kernel Version 22.5.0

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### Quarkus version or git rev

3.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by gsmet** [comment]
While not a direct answer to your question, you should be able to use your own ObjectMapper in your app without any issue.

Can you post a simple reproducer showing your initial issue (i.e. not the issue you have now but the one you had initially and that led you to parent first artifacts)?

Are you using the `quarkus-jackson` extension?
