### ISSUE TITLE
Change default value of `sql-load-script` to `no-file` in PROD mode

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3389]
While having `import.sql` imported for dev and test makes sense, I have the feeling that making it an explicit choice in PROD is likely worthwile.
What do you think @gsmet @Sanne ?

It's a restart on the question asked https://github.com/quarkusio/quarkus/pull/3368 that got unaddressed.

**Comment by gwenneg** [comment]
I'll submit a PR for this if the change is confirmed.

**Comment by gsmet** [comment]
It makes sense to me. Just wondering if we will be able to document it properly and not have people confused by the behavior.
