### ISSUE TITLE
mvn wrapper not updated with quarkus update

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33900]
### Describe the bug

we currently dont update the maven wrapper when updating causing that the new migrated project cannot build if users starts from older quarkus with non updated wrapper

### Expected behavior

do the wrapper update or at least inform the user

**Comment by gsmet** [comment]
This is now taken care of if and only if needed: meaning we update the Maven wrapper if the minimum Maven version for Quarkus has changed.
