### ISSUE TITLE
[Extension Proposal] Apache Mina SSHD extension and Bouncycastle support extension

### ISSUE THREAD

**Issue by sunix** [quarkusio/quarkus#33909]
### Description

Hello, this is a proposal to make Apache Mina SSHD https://mina.apache.org/sshd-project/ a Quarkus extension.

Probably getting inspiration from https://github.com/apache/camel-quarkus/tree/main/extensions/ssh

The extension would also required BouncyCattle support, we would need to get inspiration from https://github.com/apache/camel-quarkus/tree/main/extensions-support/bouncycastle/runtime/src/main/java/org/apache/camel/quarkus/support/bouncycastle

A draft extension had been created here: https://github.com/jkubeio/kport/tree/main/quarkus-sshd

### Repository name

quarkus-sshd

### Short description

Provide basic support of Apache Mina SSHD in Quarkus.

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/sshd

### Repository Topics

- quarkus-extension
- apache sshd
- apache mina sshd
- bouncycastle

### Team Members

- @sunix

**Comment by gastaldi** [comment]
Shouldn't BouncyCastle have its own extension? I think that would be useful for other extensions as well (eg. `quarkus-security` [declares substitutions](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/graal/BouncyCastleSubstitutions.java) for it)

**Comment by sunix** [comment]
Hello @gastaldi,
Would it be possible to add @zbendhiba to https://github.com/orgs/quarkiverse/teams/quarkiverse-sshd?
Thanks a lot !

**Comment by sunix** [comment]
> Shouldn't BouncyCastle have its own extension? I think that would be useful for other extensions as well (eg. `quarkus-security` [declares substitutions](https://github.com/quarkusio/quarkus/blob/main/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/graal/BouncyCastleSubstitutions.java) for it)

Yes, I will work on it in a second step

**Comment by gastaldi** [comment]
> Hello @gastaldi, Would it be possible to add @zbendhiba to https://github.com/orgs/quarkiverse/teams/quarkiverse-sshd? Thanks a lot !

Done in https://github.com/quarkiverse/quarkiverse-devops/pull/156

BTW you can also submit PRs to that file (don't fork it, you have push permission to create branches there) if you want to add maintainers or change anything in the repository.

**Comment by sunix** [comment]
> > Hello @gastaldi, Would it be possible to add @zbendhiba to https://github.com/orgs/quarkiverse/teams/quarkiverse-sshd? Thanks a lot !
> 
> Done in [quarkiverse/quarkiverse-devops#156](https://github.com/quarkiverse/quarkiverse-devops/pull/156)
> 
> BTW you can also submit PRs to that file (don't fork it, you have push permission to create branches there) if you want to add maintainers or change anything in the repository.

Thanks !

**Comment by zbendhiba** [comment]
thanks @gastaldi !
