### ISSUE TITLE
UnlessBuildProfile Annotation Javadoc

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus#33954]
### Description

Looking on the documentation of `@UnlessBuildProfile ` javadoc I was confused at first. Seeing the javadoc at **Quarkus 3.1.1.Final** version. I think the javadoc should be changed.

The javadoc of `@UnlessBuildProfile `annotation:

![image](https://github.com/quarkusio/quarkus/assets/20996624/3982d88b-1e4e-44c7-96e3-3035cc65a4da)

### Implementation ideas

Changing the javadoc to use `@UnlessBuildProfile` in the javadoc. Let me know if I can raise an MR or find anything like this too.

**Comment by gsmet** [comment]
Ah, good catch, yes, please open a PR.
