### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkusio/quarkus#33952]
### Description

Add PR Template so that contributors can use to describe his/her changes

**Comment by yrodiere** [comment]
Thanks for the suggestion.

cc @geoand, I think you're admin? In any case you probably know who is :)

**Comment by geoand** [comment]
For better or worse, I am not an admin :)

But @gsmet and @maxandersen are AFAIK

**Comment by gsmet** [comment]
I don't see a lot of value in this. It's one more thing to maintain and I don't think we had problems when people created PRs so far.

**Comment by shivam-sharma7** [comment]
@gsmet Np, close this
