### ISSUE TITLE
Hibernate ORM Panache for Testing

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#3395]
**Describe the bug**
The Hibernate ORM Panache methods are not injected in tests.

**Expected behavior**
The common Panache methods like `findAll`, `count`, etc. should be accessible in a JUnit5 `@Test` context to write Integration tests.

**Actual behavior**
The test fails 
```
2019-07-31 20:46:11.594 INFO  2947 --- [           main] io.quarkus                    : Quarkus 0.20.0 started in 1.845s. Listening on: http://[::]:8081
2019-07-31 20:46:11.594 INFO  2947 --- [           main] io.quarkus                    : Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-h2, mailer, narayana-jta, resteasy, resteasy-jsonb, scheduler, smallrye-metrics, smallrye-openapi, swagger-ui, vertx]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.226 s <<< FAILURE! - in io.github.jhipster.sample.web.rest.BankAccountResourceTest
[ERROR] createBankAccount  Time elapsed: 0.028 s  <<< ERROR!
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?
        at io.github.jhipster.sample.web.rest.BankAccountResourceTest.createBankAccount(BankAccountResourceTest.java:56)

2019-07-31 20:46:11.684 INFO  2947 --- [           main] io.quarkus                    : Quarkus stopped in 0.051s
```
**To Reproduce**
1. Clone https://github.com/danielpetisme/jhipster-sample-app-quarkus
2. Launch `./mvnw test`

The `BankAccount` entity is properly annotated
https://github.com/danielpetisme/jhipster-sample-app-quarkus/blob/master/src/main/java/io/github/jhipster/sample/domain/BankAccount.java#L18

**Configuration**
```properties
## configure your datasource
quarkus.datasource.url=jdbc:h2:mem:jhipstersampleapplication;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=jhipsterSampleApplication
quarkus.datasource.password=
quarkus.datasource.max-size=8
quarkus.datasource.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
~  uname -a
Darwin MacBook-Pro-de-Daniel.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
 - Output of `java -version`:
``` java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
``` 
 - GraalVM version (if different from Java): N/A since it's only jvm mode
 - Quarkus version or git rev: `0.20.0`

**Additional context**
(Add any other context about the problem here.)
This issues has ben partially adressed in #1367 . Back then the issue could be reporoduced with the quickstart example. Now, the quickstart works but my tests still don't...

Let me know how I can help.

**Comment by danielpetisme** [comment]
I think it's also a dupe of #1724...

For those interested to understand what is happening

I checked, the `BankAccount` class is loaded from `target/test-classes` and not from classes.
```
 @BeforeEach
    public void initTest() throws Exception {
ClassLoader loader = BankAccount.class.getClassLoader();
        System.out.println(loader.getResource(BankAccount.class.getName().replaceAll("\\.", "/") + ".class"));
}
````
Gives me:
`file:/Users/danielpetisme/workspace/quarkus-labs/jhipster-sample-application/target/classes/io/github/jhipster/sample/domain/BankAccount.classfile:/Users/danielpetisme/workspace/quarkus-labs/jhipster-sample-application/target/test-classes/io/github/jhipster/sample/domain/BankAccount.class`

I tried  to have a look to the `test-classes/io/github/jhipster/sample/domain/BankAccount.class`, but it's deleted as soon as the test finish.  So I dumped the file somewhere else
```
private byte[] getClassFile(Class<?> clazz) throws URISyntaxException, IOException {
        Path path = Paths.get(clazz.getClassLoader()
                .getResource(clazz.getName().replaceAll("\\.", "/") + ".class").toURI());
        return Files.readAllBytes(path);
    }

...
//in initTest()
Files.write(Paths.get("/tmp/BankAccount.class"), getClassFile(BankAccount.class));
```

Then I look to the bytecode
```
cd /tmp
javap -v -p -l BankAccount.class | grep findAll
  #126 = Utf8               findAll
  #130 = NameAndType        #126:#129     // findAll:(Ljava/lang/Class;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
  #131 = Methodref          #65.#130      // io/quarkus/hibernate/orm/panache/runtime/JpaOperations.findAll:(Ljava/lang/Class;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
  #135 = NameAndType        #126:#134     // findAll:(Ljava/lang/Class;Lio/quarkus/panache/common/Sort;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
  #136 = Methodref          #65.#135      // io/quarkus/hibernate/orm/panache/runtime/JpaOperations.findAll:(Ljava/lang/Class;Lio/quarkus/panache/common/Sort;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
  public static <T extends io.quarkus.hibernate.orm.panache.PanacheEntityBase> io.quarkus.hibernate.orm.panache.PanacheQuery<T> findAll();
         2: invokestatic  #131                // Method io/quarkus/hibernate/orm/panache/runtime/JpaOperations.findAll:(Ljava/lang/Class;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
  public static <T extends io.quarkus.hibernate.orm.panache.PanacheEntityBase> io.quarkus.hibernate.orm.panache.PanacheQuery<T> findAll(io.quarkus.panache.common.Sort);
         3: invokestatic  #136                // Method io/quarkus/hibernate/orm/panache/runtime/JpaOperations.findAll:(Ljava/lang/Class;Lio/quarkus/panache/common/Sort;)Lio/quarkus/hibernate/orm/panache/PanacheQuery;
```
That means the Panache methods are here...

So just as you mention in the other issue, it looks like JUnit is loading the class before has  been augmented. 
From there  I don't know how I can go further... Any clue on how to move forward?

**Comment by FroMage** [comment]
Well, one workaround would be to get rid of the `bankAccount` field. If your class does not have the `BankAccount` type in its method signatures and fields, it will work. It's annoying, but it's a workaround.

**Comment by danielpetisme** [comment]
Indeed it works but it only fix the symptoms not the cause... I've a weird feeling because this issue means Quarkus augmentation , as for now, can't bee properly tested without a hack...
Since this issue is a duplicate of #1724, do you want to close this one and gather all the comments/tests/solutions in the main issue?

**Comment by FroMage** [comment]
Yeah, I think we should merge it.
