### ISSUE TITLE
The repairing error message is not correct and bug of custom-quarkus-extension continue exists.

### ISSUE THREAD

**Issue by Ferrociraptus** [quarkusio/quarkus#33957]
### Describe the bug

I wrote the simple Quarkus extension to “play” with code. And after compile I receive: 
```
"You cannot invoke beanInstance() directly on an object returned from the byte code recorder, you can only pass it back into the recorder as a parameter"
```
but i don't invoke it into Recorder.
Recorder is:
```java
public class MergeableClassRecorder {

    Logger log = Logger.getLogger("org.mapins.cloud");


    void cacheMergeableClasses(MergeUtil mergeUtil, List<String> classPaths){
        log.debugf("List of mergeable items found by Quarkus deployment: %n%s", classPaths);

        classPaths.stream()
                .filter(Objects::nonNull)
                .map(
                    n -> {
                        try {return Class.forName(n);}
                        catch (Throwable ignore) { return null;}
                    })
                .filter(Objects::nonNull)
                .forEach(mergeUtil::cacheClass);

        log.infof("%n%s classes cached", classPaths);
    }
}
```
and @BuidlStep is:
```java
    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    void CacheAllMergeableClasses(List<MergeableClassCacheItem> classes,
                                  MergeableClassRecorder recorder,
                                  BeanContainerBuildItem containerItem){

        final List<String> listOfCachedClasses = classes.stream().map(e -> e.get().name().toString()).toList();

        MergeUtil mergeUtilObj = containerItem.getValue().beanInstance(MergeUtil.class);

        recorder.cacheMergeableClasses(mergeUtilObj, listOfCachedClasses);
    }
```

Earlier I try to make code by [example](https://www.baeldung.com/quarkus-extension-java) like this:
```java
    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    void createMergeUtilClass(List<MergeableClassCacheItem> classes,
                              BuildProducer<AdditionalBeanBuildItem> additionalBeanProducer,
                              BuildProducer<BeanContainerListenerBuildItem> containerListener,
                              MergeableClassRecorder recorder) {

        additionalBeanProducer.produce(
                AdditionalBeanBuildItem.builder()
                        .addBeanClass(MergeUtil.class)
                        .setUnremovable()
                        .setDefaultScope(DotNames.SINGLETON)
                        .build()
        );

        final List<String> listOfCachedClasses = classes.stream().map(e -> e.get().name().toString()).toList();

        containerListener.produce(
                new BeanContainerListenerBuildItem(
                        recorder.cacheMergeableClasses(listOfCachedClasses)
                )
        );
    }
```
and this @Recorder:
```java

@Recorder
public class MergeableClassRecorder {
    Logger log = Logger.getLogger("org.mapins.cloud");

    BeanContainerListener cacheMergeableClasses(List<String> classPaths){

        return container -> {
            log.debugf("List of mergeable items found by Quarkus deployment: %n%s", classPaths);

            MergeUtil mergeUtil = container.beanInstance(MergeUtil.class);

            classPaths.stream()
                    .filter(Objects::nonNull)
                    .map(
                            n -> {
                                try {return Class.forName(n);}
                                catch (Throwable ignore) { return null;}
                            })
                    .filter(Objects::nonNull)
                    .forEach(mergeUtil::cacheClass);

            log.infof("%n%s classes cached", classPaths);
        };
    }
}
```
but in result had other exception like:
```
Unable to serialize objects of type class org.test.mapins.MergeableClassRecorder$$Lambda$15232/0x000000080253b040 to bytecode as it has no default constructor
```

So what wrong I do?

### Expected behavior

The program compiles without exceptions and continue to run the app.

### Actual behavior

Fails with 
```
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step org.test.mapins.MergeToolResourceProcessor#CacheAllMergeableClasses threw an exception: java.lang.RuntimeException: You cannot invoke beanInstance() directly on an object returned from the bytecode recorder, you can only pass it back into the recorder as a parameter
  	at io.quarkus.deployment.recording.BytecodeRecorderImpl$3.invoke(BytecodeRecorderImpl.java:444)
  	at io.quarkus.deployment.recording.BytecodeRecorderImpl$$ReturnValueProxy107.beanInstance(Unknown Source)
  	at org.test.mapins.MergeToolResourceProcessor.CacheAllMergeableClasses(MergeToolResourceProcessor.java:112)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### How to Reproduce?

Reproducer:

1) Get code from https://github.com/Ferrociraptus/quarkus-bug-publication
2) Install application to maven local and try to use or write the simple test for quarkus extension

### Output of `uname -a` or `ver`

Linux ferri 6.2.13-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 26 20:11:01 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

https://github.com/Ferrociraptus/quarkus-bug-publication

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.7 (Red Hat, Inc. 17.0.7+7) OS:           Linux 6.2.13-100.fc36.x86_64 amd64

**Comment by gsmet** [comment]
I think the errors are descriptive enough.

`MergeUtil mergeUtilObj = containerItem.getValue().beanInstance(MergeUtil.class);` you cannot do that in a build step as stated as the CDI container is instantiated at runtime so at recorder time.

If you want to develop extensions, you really need to understand the difference between build and runtime phases in Quarkus as it is key.

As for the second example, I think your problem is with the class generated by `classes.stream().map(e -> e.get().name().toString()).toList()`. The list created is not properly serializable with our serialization mechanism.

If you try to convert it to an `ArrayList`, it might work.

@geoand @stuartwdouglas wondering if we should handle the second case case a bit better?

**Comment by geoand** [comment]
> I think the errors are descriptive enough.

Completely agreed. I think @Ferrociraptus has misread it :).

> @geoand @stuartwdouglas wondering if we should handle the second case case a bit better?

Let me see if there is a quick win here.

**Comment by geoand** [comment]
I would need a easy way to reproduce the example problem you are seeing with `Unable to serialize objects of type class ...`

**Comment by Ferrociraptus** [comment]
> I think the errors are descriptive enough.
> 
> `MergeUtil mergeUtilObj = containerItem.getValue().beanInstance(MergeUtil.class);` you cannot do that in a build step as stated as the CDI container is instantiated at runtime so at recorder time.
> 
> If you want to develop extensions, you really need to understand the difference between build and runtime phases in Quarkus as it is key.
> 
> As for the second example, I think your problem is with the class generated by `classes.stream().map(e -> e.get().name().toString()).toList()`. The list created is not properly serializable with our serialization mechanism.
> 
> If you try to convert it to an `ArrayList`, it might work.
> 
> @geoand @stuartwdouglas wondering if we should handle the second case case a bit better?

Yeah, but as I correctly understand, the runtime recorder is the class with @Recorder annotation in runtime module, so nothing as you said I didn't find in documentation. But your speech is clear and very logical.

As usual student, after I tried all documentation tips and internet recommendations, I started to try all possible variants and this sample were too:
```java
    @BuildStep
    void createMergeUtilClass(BuildProducer<AdditionalBeanBuildItem> additionalBeanProducer) {

        additionalBeanProducer.produce(
                AdditionalBeanBuildItem.builder()
                        .addBeanClass(MergeUtil.class)
                        .setUnremovable()
                        .setDefaultScope(DotNames.SINGLETON)
                        .build()
        );

    }

    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    void CacheAllMergeableClasses(List<MergeableClassCacheItem> classes,
                                  MergeableClassRecorder recorder,
                                  BeanContainerBuildItem containerItem){

        final List<String> listOfCachedClasses = classes.stream().map(e -> e.get().name().toString()).toList();

        recorder.cacheMergeableClasses(containerItem.getValue(), listOfCachedClasses);
    }
```
and this Recorder:
```java
    void cacheMergeableClasses(BeanContainer mergeUtilContainer, List<String> classPaths){
        log.debugf("List of mergeable items found by Quarkus deployment: %n%s", classPaths);

        MergeUtil mergeUtil = mergeUtilContainer.beanInstance(MergeUtil.class);
        classPaths.stream()
                .filter(Objects::nonNull)
                .map(
                    n -> {
                        try {return Class.forName(n);}
                        catch (Throwable ignore) { return null;}
                    })
                .filter(Objects::nonNull)
                .forEach(mergeUtil::cacheClass);

        log.infof("%n%s classes cached", classPaths);
    }
```
but it throws the same exception
```
You cannot invoke beanInstance() directly on an object returned from the bytecode recorder, you can only pass it back into the recorder as a parameter
```
As I clearly understand the runtime code play are in Recorders classes, but... Maybe I really not correctly understand usual English.

I hope that you help me understand my problem. Thanks.

**Comment by Ferrociraptus** [comment]
I want to prebuild the reflection cache of classes which annotated by my own. And I collect them from index on build step and try to eval cache by reflection grep in runtime into Recorder class.

> Nothing that is returned by a class annotated with `@Recorder` (i.e runtime data) can be used in a method that used `@BuildStep` (i.e build time processing). The only thing you can with this kind of data in a `@BuildStep` method is "carry" the data and pass it to another method of a `@Recorder` class.
> 
> In your code, what **exactly** are you trying to achieve? What is your **end goal**?

**Comment by Ferrociraptus** [comment]
> I think the errors are descriptive enough.
> 
> `MergeUtil mergeUtilObj = containerItem.getValue().beanInstance(MergeUtil.class);` you cannot do that in a build step as stated as the CDI container is instantiated at runtime so at recorder time.
> 
> If you want to develop extensions, you really need to understand the difference between build and runtime phases in Quarkus as it is key.
> 
> As for the second example, I think your problem is with the class generated by `classes.stream().map(e -> e.get().name().toString()).toList()`. The list created is not properly serializable with our serialization mechanism.
> 
> If you try to convert it to an `ArrayList`, it might work.
> 
> @geoand @stuartwdouglas wondering if we should handle the second case case a bit better?

I tried to remove usage of Java stream and use the ArrayList, but it doesn't help, the lambda is not serializable too:
```
Unable to serialize objects of type class org.test.mapins.MergeableClassRecorder$$Lambda$3139/0x000000080252df98 to bytecode as it has no default constructor
```

**Comment by geoand** [comment]
I don't have time to debug the code, but from what I see from the original code you pasted, you should be to do the following:

```java
public class MergeableClassRecorder {

    Logger log = Logger.getLogger("org.mapins.cloud");


    void cacheMergeableClasses(BeanContainer beanContainer, List<String> classPaths){
        log.debugf("List of mergeable items found by Quarkus deployment: %n%s", classPaths);

        var mergeUtil = beanContainer.beanInstance(MergeUtil.class);
        classPaths.stream()
                .filter(Objects::nonNull)
                .map(
                    n -> {
                        try {return Class.forName(n);}
                        catch (Throwable ignore) { return null;}
                    })
                .filter(Objects::nonNull)
                .forEach(mergeUtil::cacheClass);

        log.infof("%n%s classes cached", classPaths);
    }
}
```

and 

```java
    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    void CacheAllMergeableClasses(List<MergeableClassCacheItem> classes,
                                  MergeableClassRecorder recorder,
                                  BeanContainerBuildItem containerItem){

        final List<String> listOfCachedClasses = classes.stream().map(e -> e.get().name().toString()).toList();

        recorder.cacheMergeableClasses(beanContainer, listOfCachedClasses);
    }
```

This of course assumes that you have created `MergeableClassCacheItem` properly (i.e using only build time information)

**Comment by geoand** [comment]
> What I should prepare for represent my problem for your check?

A project (preferable Maven) when I just build it and see the problem immediately - no extra steps necessay

**Comment by Ferrociraptus** [comment]
> I don't have time to debug the code, but from what I see from the original code you pasted, you should be to do the following:
> 
> ```java
> public class MergeableClassRecorder {
> 
>     Logger log = Logger.getLogger("org.mapins.cloud");
> 
> 
>     void cacheMergeableClasses(BeanContainer beanContainer, List<String> classPaths){
>         log.debugf("List of mergeable items found by Quarkus deployment: %n%s", classPaths);
> 
>         var mergeUtil = beanContainer.beanInstance(MergeUtil.class);
>         classPaths.stream()
>                 .filter(Objects::nonNull)
>                 .map(
>                     n -> {
>                         try {return Class.forName(n);}
>                         catch (Throwable ignore) { return null;}
>                     })
>                 .filter(Objects::nonNull)
>                 .forEach(mergeUtil::cacheClass);
> 
>         log.infof("%n%s classes cached", classPaths);
>     }
> }
> ```
> 
> and
> 
> ```java
>     @BuildStep
>     @Record(ExecutionTime.RUNTIME_INIT)
>     void CacheAllMergeableClasses(List<MergeableClassCacheItem> classes,
>                                   MergeableClassRecorder recorder,
>                                   BeanContainerBuildItem containerItem){
> 
>         final List<String> listOfCachedClasses = classes.stream().map(e -> e.get().name().toString()).toList();
> 
>         recorder.cacheMergeableClasses(beanContainer, listOfCachedClasses);
>     }
> ```
> 
> This of course assumes that you have created `MergeableClassCacheItem` properly (i.e using only build time information)

I [wrote before](https://github.com/quarkusio/quarkus/issues/33957#issuecomment-1587066082) that I try this, and it wasn't work too.

**Comment by Ferrociraptus** [comment]
> > What I should prepare for represent my problem for your check?
> 
> A project (preferably Maven) when I just build it and see the problem immediately - no extra steps necessary

Ok. I'm in process.

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
The problem turns out to be that you the recorder method is package private - if you turn it into a `public` method, it works just fine.

https://github.com/quarkusio/quarkus/pull/34006 adds a warning against the type of use you are performing in order to try to nudge people towards the proper pattern usage.

**Comment by Ferrociraptus** [comment]
> The problem turns out to be that you the recorder method is package private - if you turn it into a `public` method, it works just fine.
> 
> #34006 adds a warning against the type of use you are performing in order to try to nudge people towards the proper pattern usage.

Thanks a lot!
