### ISSUE TITLE
Update: javax.transaction.xa.* should not be migrated to jakarta.transaction.xa.*

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus#33973]
### Describe the bug

It's probably incorrect to migrate `javax.transaction.xa` to `jakarta.transaction.xa`.

`javax.transaction.xa` is currently part of Java SE (see https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0.html#java-se)
(It can be simulated easily by upgrading on example https://github.com/apache/camel-quarkus-examples/tree/main/jta-jpa)

**Comment by JiriOndrusek** [comment]
Here is the configuration triggering the update: https://github.com/quarkusio/quarkus-updates/blob/main/recipes/src/main/resources/quarkus-updates/core/3alpha.yaml#L971-L994

**Comment by mmusgrov** [comment]
+1 `jakarta.transaction.xa` is not a valid package name. Note that the version of Narayana used by Quarkus has already migrated over to Jakarta so do we actually need these rewrite rules?

**Comment by gsmet** [comment]
I'm working on a fix. The one you pointed out is one of the problems but the others will be less easily fixed unfortunately.

Anyway, I will report back when fixed.

**Comment by gsmet** [comment]
@JiriOndrusek https://github.com/quarkusio/quarkus-updates/pull/38 should fix it. I tested it on the `2.16.x` branch of your project and it seems to work properly.

Let me know and I'll merge and release it.

**Comment by JiriOndrusek** [comment]
@gsmet I verified your change with my reproducer, change fixes the issue. Thanks!
