### ISSUE TITLE
Parametirized `RolesAllowed` does not work for a list of roles

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#33982]
### Describe the bug

`RolesAllowed` value can be set from the properties, see https://quarkus.io/guides/security-authorize-web-endpoints-reference#standard-security-annotations. Example, instead of `@RolesAllowed({"admin"})` it is `@RolesAllowed({"${my.roles}"})`

However, if a property such as `my.roles` is a list, instead of a single value, then  `@RolesAllowed({"${my.roles}"})` does not work

**Comment by michalvavrik** [comment]
Technically I believe SmallRye config properties are string key -> string value and whether you interpret it as a list depends on converter that is determined based on config item return type; but I agree, it should be safe to treat anything that contains list separator as a list and it is nice feature. I don't believe anyone will name their roles with comma. Working on this.
