### ISSUE TITLE
Quarkus BOM uses slf4j-api v2 and slf4j-* v1.7.x for other versions

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#33996]
### Describe the bug

The Quarkus BOM requires slf4j-api v2.0.6 but still uses v1.7 for all the implementations. This creates an issue where slf4j will ignore possible loggers:
```
SLF4J: No SLF4J providers were found.                                                                                                                                                                          
SLF4J: Defaulting to no-operation (NOP) logger implementation                                                                                                                                                  
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.                           
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.                                                                                                                       
SLF4J: Ignoring binding found at [jar:file:/home/user/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.21/be4b3c560a37e69b6c58278116740db28832232c/slf4j-simple-1.7.21.jar!/org/slf4j/impl/Sta
ticLoggerBinder.class]                                                                                 
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.                        
```

This may not immediately appear in Quarkus apps as the default logger works fine. This becomes visible if other software is built outside of Quarkus but stays in sync with versions that Quarkus wants.

### Quarkus version or git rev

3.1.0.Final

**Comment by jskillin-idt** [comment]
This is one of my lighter write-ups. Let me know if I need more information.

**Comment by gsmet** [comment]
> The Quarkus BOM requires slf4j-api v2.0.6 but still uses v1.7 for all the implementations. This creates an issue where slf4j will ignore possible loggers:

That's expected. You shouldn't use any SLF4j impl in your projects. Exclude them and use `slf4j-jboss-logmanager` to redirect slf4j calls to JBoss Logging instead.
