### ISSUE TITLE
AroundInvoke Interceptors can only modify parameters if first in chain

### ISSUE THREAD

**Issue by allertonm** [quarkusio/quarkus#34001]
### Describe the bug

If there is a chain of interceptors applied to a method call, only the first interceptor in the chain can modify the InvocationContext parameters using setParameters. Changes made by interceptors other than the first are ignored. This occurs because the 2nd and later interceptors are passed an instance of `AroundInvokeInvocationContext.NextAroundInvokeInvocationContext` whose parameters array reference is copied from the outer `AroundInvokeInvocationContext` - but if setParameters is called, the new array is not reflected back to the outer context.

This change appears to have been made in this commit https://github.com/quarkusio/quarkus/commit/0ed5b7b4a7b1102e90757b38e0f4b402173e26ed

While the comments added to this commit do suggest some limitations to the use of setParameters, in fact the actual behaviour is far more limited than suggested. This change appears to break the standard contract of `jakarta.interceptor.InvocationContext` whose comments suggest no such limitations.

This behaviour makes it effectively impossible to write an Interceptor that will work with Kotlin continuations, because in order to perform operations before the caller's continuation is resumed, we need to pass a new continuation to the callee. This requires us to be able to modify the continuation parameter in the InvocationContext, and also - if such interceptors are to be chained successfully - for interceptors further along the chain to receive the continuation set by earlier interceptors.

### Expected behavior

Changes made by InvocationContext.setParameters are reflected in both the parameters passed to the callee and to callers of InvocationContext.getParameters further down the chain.

### Actual behavior

Changes made by Invocation.setParameters only take effect if the Interceptor is the first in the chain.

### How to Reproduce?

I created a sample app that demonstrates these problems here https://github.com/allertonm/quarkus-coroutine-interceptor-example

Interceptors.kt defines three interceptors, one that does nothing, and two that perform logging actions on continuation resumption by chaining a new continuation.
ExampleResource.kt is a resource that demonstrates four different coroutine outcomes (of which `helloDeferred` is the most interesting) and by combining the interceptors on these methods (and modifying interceptor priorities.) you can see the effects of the setParameters behaviour. 

In particular: if `DoNothing` is priority 1, and `Intercept1` is priority2, then Intercept1 will not log the continuation resumption. If you switch the priorities, it will.

The desired outcome is that if you combine both Intercept1 and Intercept2 (and any other interceptors) in any priority order, then both Intercept1 and Intercept2 will log their respective continuation resumptions.

I've also provided a reflection-based workaround (commented out) which if you uncomment will show that the desired outcome can be achieved if `NextAroundInvocationContext.setParameters` writes changes back to the outer context. I would obviously much rather not have to do this.

For context, the specific use case for this code in real-life is to reproduce the behaviour of Panache's `@WithSession` and `@WithTransaction` for cases where coroutines are being used instead of `Mutiny.Uni.`

### Output of `uname -a` or `ver`

Darwin M-L10KJGH6 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.1.1.Final (also reproducible on 3.0.3)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.7 (Amazon.com Inc. 17.0.7+7-LTS) OS:           Mac OS X 13.4 x86_64

**Comment by allertonm** [comment]
After writing all this up, and spending the time looking at the AroundInvocationContext code, I realized there is a workaround for this that does not involve reflection - because provided `setParameters` has not been called, what `getParameters` returns is a reference to `AroundInvocationContext.this.parameters`. So instead of...

```
                val newParameters: Array<Any?> = ctxParameters.clone()
                newParameters[newParameters.size - 1] = chainedContinuation
                ctx.parameters = newParameters
```

I can write 
```ctx.parameters[ctx.parameters.size - 1] = chainedContinuation```

And everything works.

While this is a lot better than using reflection, this workaround is highly implementation dependent and I do still think this bug report stands - there needs to be a standard way of achieving this goal without knowledge of the internal implementation of InvocationContext.

**Comment by geoand** [comment]
cc @mkouba @Ladicek

**Comment by mkouba** [comment]
@allertonm Thanks for the report. That looks like an oversight.

@Ladicek @manovotn I'm surprised there is no TCK test for this common scenario :thinking:.

https://github.com/quarkusio/quarkus/pull/34003 should fix the problem but I'd like to verify few things first, e.g. if the current behavior was not intentional.

**Comment by manovotn** [comment]
> @Ladicek @manovotn I'm surprised there is no TCK test for this common scenario :thinking:.

Yes, I was thinking the same; I assume there will only be a trivial single interceptor case. Checking now...
