### ISSUE TITLE
RESTEasy Reactive: ContextResolver<ObjectMapper> not called/used

### ISSUE THREAD

**Issue by timonzi** [quarkusio/quarkus#34008]
### Describe the bug

When using RESTEasy Reactive (or more precise: `io.quarkus:quarkus-resteasy-reactive-jackson`) our `ContextResolver` is never called and thus the wrong `ObjectMapper` for the REST calls is used.

It works fine when using `io.quarkus:quarkus-resteasy-jackson`.

The problem was mentioned already in https://github.com/quarkusio/quarkus/issues/26152 ([comments](https://github.com/quarkusio/quarkus/issues/26152#issuecomment-1443540109))

### Expected behavior

The `ContextResolver#getContext` method should be called and the returned `ObjectMapper` should be used for de-/serializing values, like it is done using RESTEasy classic.

### Actual behavior

The `ContextResolver#getContext` method is not called at all. So the wrong `ObjectMapper` is used.

### How to Reproduce?

Reproducer:  https://github.com/timonzi/resteasy-reactive-context-resolver-reproducer

1. Execute the test (org.acme.GreetingResourceTest). This leads to an `AssertionError` as the status code is 400 instead of 200, because of the failed deserialization.
2. Change dependency `io.quarkus:quarkus-resteasy-reactive-jackson` to `io.quarkus:quarkus-resteasy-jackson`. Now the `org.acme.SampleContextResolver#getContext` method is called and the test runs successfully.

### Output of `uname -a` or `ver`

Linux nb-timonzi 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17; OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10); OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by Sgitario** [comment]
I've just found that the context resolver is only used in the RESTEasy REST client, not the server :facepalm: 
I will update the server part asap.

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/34014 should fix this issue cc @timonzi
