### ISSUE TITLE
ARC exclude-types does not work for @Provider ContainerRequestFilter/ContainerResponse Filter

### ISSUE THREAD

**Issue by Hemantkumar-Chigadani** [quarkusio/quarkus#34011]
### Describe the bug

We got a scenario where we want to use lots of beans including filters from third party library. We want to exclude one of the filter beans, to be excluded using `exclude-types` option https://quarkus.io/guides/cdi-reference#how-to-exclude-types-and-dependencies-from-discovery but it did not work.

Bean discovery from third party library: https://github.com/Hemantkumar-Chigadani/module1 using beans.xml
And this module1 is used in module2 https://github.com/Hemantkumar-Chigadani/module2 as dependency. 
Config in module2 to exclude this filter

> quarkus:
>   arc:
>     exclude-types: com.example.TestFilter

### Expected behavior

Provider filter bean should not be initialised as its excluded using https://quarkus.io/guides/cdi-reference#how-to-exclude-types-and-dependencies-from-discovery

### Actual behavior

Provider filter is initialised and executed even though its excluded from arc config.

> 2023-06-13 11:32:45,505 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Listening on: http://localhost:8080/_lambda_/2018-06-01/runtime/invocation/next
> 2023-06-13 11:32:45,504 INFO  [io.quarkus] (Quarkus Main Thread) module2 1.0-SNAPSHOT on JVM (powered by Quarkus 3.1.1.Final) started in 14.366s. 
> 2023-06-13 11:32:45,512 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
> 2023-06-13 11:32:45,512 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [amazon-dynamodb, amazon-dynamodb-enhanced, amazon-lambda, cdi, config-yaml, hibernate-validator, rest-client, rest-client-jackson, resteasy, resteasy-jackson, security, smallrye-context-propagation, vertx]
>      2023-06-13 11:32:45,614 ERROR [com.exa.TestFilter] (executor-thread-1) DO NOT WANT THIS FILTER, please exclude
> 

### How to Reproduce?

- On module1,  publish the library i.e. ./gradlew clean publishToMavenLocal
- On module2, run the app locally i.e  ./gradlew quarkusDev

Please note: I have tested non quarkus dev mode too, its same behaviour. 

### Output of `uname -a` or `ver`

Darwin Hemant-16-MacBook.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 17.0.2 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.2 (Oracle Corporation 17.0.2+8-86) OS:           Mac OS X 13.4 aarch64

**Comment by Ladicek** [comment]
I pretty sure JAX-RS providers are _not_ subject to the same rules as CDI beans. In fact, they don't even have to be CDI beans in the first place (though I'm not sure if they are or not in Quarkus).

**Comment by geoand** [comment]
Right, `quarkus.arc.exclude-types` is not meant to work in this case.

**Comment by Hemantkumar-Chigadani** [comment]
hmm, what is the best solution to exclude third party filters?

**Comment by manovotn** [comment]
The exclude filter works in preventing beans from being discovered (during bean discovery process). However they can still be added manually by various extensions. I suppose that might be the case here

**Comment by geoand** [comment]
For code you own, you can use [this](https://quarkus.io/guides/resteasy-reactive#includeexclude-jakarta-rest-classes).

@Hemantkumar-Chigadani what exactly does your use case look like?

**Comment by Hemantkumar-Chigadani** [comment]
@geoand Thanks for the quick response.
The Use case is, we got common library repo with common functionalities within it so that other microservices do not need to redefine the functionality Example: Request/Response logging filters, Authentication filters, X-ray filters etc. 

One of the requirements:
One of our microservices got a special requirement. Example: Not to log anything from Request/Response. So wanted to exclude the filter doing so and use all other filters as they are :(

**Comment by geoand** [comment]
Do you want to completely ignore the stuff in that library?

**Comment by Hemantkumar-Chigadani** [comment]
Just one filter from the library as library got lots of good stuff in it to be used.

**Comment by geoand** [comment]
You can use:

```
quarkus.class-loading.removed-resources."group.id\:artifact.id"=org/acme/test/SomeFilter.class
```

**Comment by Hemantkumar-Chigadani** [comment]
Thanks @geoand seems to be work. Cheers!
