### ISSUE TITLE
Adding headers to Kafka message does not work via Kafka UI

### ISSUE THREAD

**Issue by tsimonavicius** [quarkusio/quarkus#34038]
### Describe the bug

When using Kafka UI to send message to kafka, not able to add any headers.
- `Delete` and `Add` buttons are not working in Headers tab.
- When filling `key` and `value` in Headers tab and sending a message, no headers are present in a request payload. 
![Screenshot 2023-06-14 at 15 18 47](https://github.com/quarkusio/quarkus/assets/36206362/8b747bb9-51e9-4e14-ac4c-a00cb6950068)

### Expected behavior

Headers added as payload to `createMessage` action.

### Actual behavior

Headers are not present in a request.

### How to Reproduce?

1. Open Kafka UI
2. Select Kafka topic to send message to
3. Open dialog to create a message
4. Add message details. 
5. Add a header.
    * `Delete` and `Add` buttons are not working in Headers tab.
6. Inspect network, no kafka headers present in a request payload.

### Output of `uname -a` or `ver`

22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-39) OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

### Additional information

Browsers tried:
Opera Version:99.0.4788.65 (arm64)
Chrome Version 114.0.5735.106 (Official Build) (arm64)
Firefox 114.0.1 (64-bit)

**Comment by MikeEdgar** [comment]
I'm looking into this and a few other issues I've found in the Kafka Dev UI.
