### ISSUE TITLE
Auto-generate required properties in application.properties

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#3403]
**Description**
This is a developer joy feature when using quarkus:add-extension, quarkus:create, or even code.quarkus.io.

Some extensions have required properties to operate properly. When possible, extensions should auto-generate the required properties in application.properties. The most notable are the quarkus-jdbc-* extensions, where a datasource must be properly configured to operate properly. In some cases, reasonable property defaults can be provided, such as H2 datasource config:

```
%dev.quarkus.datasource.url=jdbc:h2:mem:test
%dev.quarkus.datasource.driver=org.h2.Driver
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate.show-sql=true
```

In cases where reasonable defaults cannot be provided, the properties should be generated with helpful "guidance":

```
# Database connection URL. Example: jdbc:postgresql://localhost:5432/example
%dev.quarkus.datasource.url=<insert JDBC connection URL>

# Driver class name. Example: org.postgresql.Driver
%dev.quarkus.datasource.driver=org.postgresql.Driver

# Datasource username. Example: demo
%dev.quarkus.datasource.username=<insert username here>

# Datasource username. Example: demo
%dev.quarkus.datasource.password=<insert password here>

# Optional: Database generation options: update, drop-and-create, (other)
#%dev.quarkus.hibernate-orm.database.generation=<insert database generation type>

# Optional: Log SQL to <console/stdout>
#%dev.quarkus.hibernate.show-sql=true
```

Note a couple of points in the above "generated" properties:
* The extension knows the database driver so automatically provide it
* Some properties are left open (either with empty right-hand-side or, as shown, some guidance).  Note, this will cause a compilation to fail, but they are required so compilation would fail anyway (unless other optimizations have been made).
* Some commonly used or very useful properties are provided but commented out. This is a balancing act. Providing too many (or all possible properties) can be overwhelming  and developers may perceive Quarkus as being complex. This balancing act is left to extension authors.

**Comment by xumk** [comment]
@maxandersen
Can I help this task?
I think to take its in work, but I don't know where to begin.
Maybe need add something like `isRequired` and 'helpComment' properties to `@ConfigItem`, so that analyze its for generate documentation (`isRequired`) and use for this task (`isRequired` and 'helpComment' ).
Also, I would like to know place, where I can add analyze for documentation. 
How I understanded, file `application.properties` can to changing in `DefaultExtensionRegistry#planInstallation` method, but I dont know how this test and debug.
Can you plese answer on my questions and so say what you about my considerations?

**Comment by geoand** [comment]
This is going to be solved in a different way by https://github.com/quarkusio/quarkus/pull/14960

**Comment by maxandersen** [comment]
Isn't this more solved by the feature of exception thrown provide link to add/fix necessary properties ?

**Comment by radcortez** [comment]
I believe DevServices is our answer to this.
