### ISSUE TITLE
Wrong SELECT Statement Generation with setMaxResults in Hibernate 6.2.4 (Oracle DB)

### ISSUE THREAD

**Issue by wwwaldemar** [quarkusio/quarkus#34044]
### Describe the bug

The transiive dependency to Hibernate 6.2.4 in Quarkus v3.1.1 has a bug in SQL Select Statement Generation for Oracle DB
The bug in Hibernate Communit is https://hibernate.atlassian.net/browse/HHH-16800

Please downgrade Hibernate to 6.2.3

### Expected behavior

correctly sql select
select * from (select distinct e2_0.tableBId c0 from TABLE_A e1_0 join TABLE_B e2_0 on e2_0.tableBId=e1_0.tableBId) where rownum<=?

### Actual behavior

wrong sql select
select * from (select distinct e2_0.tableBId c0,rownum rn from TABLE_A e1_0 join TABLE_B e2_0 on e2_0.tableBId=e1_0.tableBId) r_0_ where r_0_.rn<=? order by r_0_.rn

### How to Reproduce?

described in https://hibernate.atlassian.net/browse/HHH-16800

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing

### Quarkus version or git rev

3.1.1.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.8

**Comment by wwwaldemar** [comment]
Workaround:

seems to be working after setting db version explicitely
`quarkus.datasource.db-version=19`
otherwise only 12 was discovered as db version

**Comment by yrodiere** [comment]
I'll let @Sanne chime in when he comes back but I don't think we'll downgrade as that would imply other regressions.

Closing as this is an upstream bug, we'll track the problem at https://hibernate.atlassian.net/browse/HHH-16800 . I've added the issue to the backlog, the Hibernate ORM team will triage it.
