### ISSUE TITLE
"vert.x-eventloop-thread-" prefix in log

### ISSUE THREAD

**Issue by zuochangqin** [quarkusio/quarkus#34048]
### Description

When receiving a request, the thread prefix printed in the log is vert.x-eventloop-thread-. Can this configuration be modified? What if I think this is too long for my journal and I want to change it to a shorter one?

**Comment by geoand** [comment]
The default value of `quarkus.log.console.format` is `%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n` as shown [here](https://quarkus.io/guides/all-config#quarkus-core_quarkus.log.console-console-logging).

`%t` is what gives you thread name

**Comment by zuochangqin** [comment]
My configuration uses "%t", but it prints out with "vert.x-eventloop-thread-"

**Comment by geoand** [comment]
Where are configuring it?

**Comment by zuochangqin** [comment]
> Where are configuring it?
quarkus.log.console.format=
'%d{yyyy-MM-dd HH:mm:ss.SSS}|%p|%X{traceId}|[%t]-%s%e%n'
