### ISSUE TITLE
Quarkus extension created with 2.13 stream and Quarkus CLI 3 contains Jakarta imports

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#34089]
### Describe the bug

I create extension with Quarkus CLI 3 for my application that uses Quarkus 2.13 and module `integration tests` of generated projects contain Jakarta imports.

### Expected behavior

Generated tests should be working for Quarkus 2.13.

### Actual behavior

```
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[19,34] package jakarta.enterprise.context does not exist
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[20,21] package jakarta.ws.rs does not exist
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[21,21] package jakarta.ws.rs does not exist
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[23,2] cannot find symbol
[ERROR]   symbol: class Path
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[24,2] cannot find symbol
[ERROR]   symbol: class ApplicationScoped
[ERROR] /home/mvavrik/Downloads/tmp/ex2/quarkus-extension-abc/integration-tests/src/main/java/io/quarkiverse/extension/abc/it/ExtensionAbcResource.java:[28,6] cannot find symbol
```

### How to Reproduce?

1. `quarkus create extension extension-abc --stream=2.13`
2. `cd quarkus-extension-abc/`
3. `quarkus build`

### Output of `uname -a` or `ver`

Linux apc-ap8641-3a-d11d.mgmt.pnr.lab.eng.rdu2.redhat.com 6.3.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun  5 15:45:04 UTC 2023 x86_64 GNU/Linux 

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

2.13.8.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 and 3.8.6

**Comment by maxandersen** [comment]
i can confirm this is a problem and it does happen indeed.

@ia3andy ideas on why codestarts gets mixed up here?

**Comment by ia3andy** [comment]
We don't handle creating extensions for old streams, extensions templates are in the base codestarts, they are not platform dependent.

**Comment by maxandersen** [comment]
Any reason why not? 

In any case that does seem like a surprise to users and we should print a warning/provide info on what they should do instead.

**Comment by michalvavrik** [comment]
> We don't handle creating extensions for old streams, extensions templates are in the base codestarts, they are not platform dependent.

I followed Quarkus CLI help (and didn't find note in quarkus.io docs)

```
[mvavrik@fedora ~]$ quarkus extension create --help | grep '\-stream' -A 2
  -S, --stream=platformKey:streamId
                         A target stream, for example:
                           io.quarkus.platform:2.0
```

**Comment by ia3andy** [comment]
It's very unlikely we end up with a similar breaking situation for extensions in the future (breaking import). 
The code is supposed to be working with all the streams (Quarkus 2-3 is an anomaly because of the change of imports).

Switching to Quarkus 2 from Quarkus 3 imports shouldn't be big deal and the way forward if people still want to create 2.xx extensions (or use a 2.x version of the CLI)

You are right @michalvavrik , we should remove the `stream` option from the `extension create` this is a bug.

**Comment by gsmet** [comment]
I tend to disagree. You made all the base codestarts compatible with 2.x/3.x so I don't see why we wouldn't use the same trick for the extension codestart.
Granted you probably use the 2.13 CLI to create extensions for 2.13 but it doesn't cost us much to make sure it doesn't fail so let's be consistent and avoid the failure.

Also creating extensions for old versions perfectly makes sense in the context of RHBQ so let's not remove the option.

I will create a PR.

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/34246 should take care of it.

**Comment by ia3andy** [comment]
> #34246 should take care of it.

ok I didn't think the fix was as simple. I was worried we needed to make the codestarts to create extensions platform dependent.

Thanks @gsmet.
