### ISSUE TITLE
SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image

### ISSUE THREAD

**Issue by zuochangqin** [quarkusio/quarkus#34088]
### Describe the bug

When I was building a quarkus multi-module project with gradle, the "./gradlew clean build" command kept getting an error :SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image. If this is a quarkus version problem, please tell me which version to use, and if this is a gradle version problem, please tell me which version to use. thank you.

### Expected behavior

build success

### Actual behavior

build fail

### How to Reproduce?

[Uploading quarkus-gradle-demo.zip…]()

./gradlew clean build

### Output of `java -version`

11

### Quarkus version or git rev

2.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

打包是uber-jar,不是native

**Comment by zuochangqin** [comment]
> This is likely a problem with the configuration of the build, however I cannot verify as it seems the reproducer was not properly attached.

[quarkus-gradle-demo.zip](https://github.com/quarkusio/quarkus/files/11795219/quarkus-gradle-demo.zip)
reuploaded

**Comment by geoand** [comment]
Your sample works fine for me. I propose cleaning Gradle caches

**Comment by zuochangqin** [comment]
> Your sample works fine for me. I propose cleaning Gradle caches

./gradlew clean build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
I cleared gradle's cache and re-executed the command, but still got an error.
