### ISSUE TITLE
Remove OkHttp from  BOM ? 

### ISSUE THREAD

**Issue by lasteris** [quarkusio/quarkus#34095]
### Description

Just Recently, i've upgraded the bunch of services to Quarkus 3.1.1.Final. 
It works perfectly itself. But after including minio i realized that we can use minio-client versions only lower than 8.2.3, because versions upper do not work due to okhttp < 4.8.1 which stricted by quarkus-bom. 
After some researching i ve noticed this

https://github.com/quarkusio/quarkus/issues/29520
and this
https://github.com/quarkiverse/quarkus-minio/issues/220

and this

https://github.com/quarkusio/quarkus/pull/30798

and even that 
https://github.com/quarkusio/quarkus/pull/30396

and this https://github.com/quarkiverse/quarkus-minio/issues/144 
which references to this https://github.com/quarkusio/quarkus/pull/30480

but after reading all that i can not understand what is going on now. are we removing dependency ?  why it still here ?

Maybe we can use this Issue to aggregate status about OkHttp ?

P.S. And maybe we can ask maintainers of minio-java to implement posibility of using not just okhttp, but any other http clients such as vert.x ? (or  as example i will try PR with such kind implementation to minio-java by myself, but its just suggestion)

**Comment by lasteris** [comment]
> We still need to some more work on this - this will likely happen after Quarkus 3.2 is released

Thank you for the reply. I've just thought, maybe i could think and help with it somehow😀

**Comment by languitar** [comment]
Is the work on this tracked somewhere visibly. I was just hit by this via the meilisearch client that is dysfunctional with okhttp3 < 4.

**Comment by gsmet** [comment]
Which version are you using?

We have removed the constraint in Quarkus 3.7: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#okhttpokio-versions-not-enforced-anymore

**Comment by languitar** [comment]
Oops, seems I've generated my extension for an older version of Quarkus than I thought. Sorry for the noise.

**Comment by gsmet** [comment]
No worries :).
