### ISSUE TITLE
19.1.1 image is missing for s2i

### ISSUE THREAD

**Issue by evanshortiss** [quarkusio/quarkus#3410]
**Describe the bug**
Unable to build latest 0.20.0 quickstarts using s2i.

**Expected behavior**
Should be able to run this [s2i command from the Quarkus website](https://quarkus.io/guides/openshift-s2i-guide#deploying-the-application-as-graalvm-native-executable-in-openshift) to run getting started examples

**Actual behavior**
Build fails since the tag does not exist in quay.io. Trying to use tag 19.0.2 fails with errors reported [here](https://github.com/quarkusio/quarkus-quickstarts/issues/251).

**To Reproduce**
1. Run `oc new-app quay.io/quarkus/ubi-quarkus-native-s2i:19.1.1~https://github.com/quarkusio/quarkus-quickstarts.git --context-dir=getting-started --name=quarkus-quickstart-native`
2. An error about the tag not existing will be reported 

**Additional context**
Is there an easy table mapping Quarkus releases to Graal or the UBI tags in quay? I tried using Quarkus 0.1X.0 instead of 0.20.0 in my pom.xml with the 19.0.2 UBI but it still failed.

**Comment by gsmet** [comment]
We need to publish an image including GraalVM 19.1.1.

**Comment by evanshortiss** [comment]
@gsmet @cescoffier is there some workaround possible using an older version of Quarkus in the pom.xml that works with Graal 19.0.2?

**Comment by gsmet** [comment]
0.19.1 should work with GraalVM 19.0.2

**Comment by cescoffier** [comment]
Should be fixed by now. Can you check?

Several reasons:

* The CI didn't deploy (token expired)
* `[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.` is rather annoying...

**Comment by evanshortiss** [comment]
@cescoffier it took a while, then failed. The OpenShift console is reporting "Out of memory killed" for the Build. Here's the logs after Maven downloads complete:

```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
--
  | [INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta5
  | [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 5006ms
  | [INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /tmp/src/target/rest-json-1.0-SNAPSHOT-runner.jar
  | [INFO]
  | [INFO] --- quarkus-maven-plugin:0.20.0:native-image (default) @ rest-json ---
  | [INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit GraalVM CE 19.1.1
  | [INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /opt/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar rest-json-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
  | [rest-json-1.0-SNAPSHOT-runner:134]    classlist:  33,605.23 ms
  | [rest-json-1.0-SNAPSHOT-runner:134]        (cap):   8,009.47 ms
  | [rest-json-1.0-SNAPSHOT-runner:134]        setup:  21,889.98 ms
  | 21:39:40,238 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
  | 21:39:48,341 INFO  [org.xnio] XNIO version 3.7.2.Final
  | 21:39:49,838 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
```

I ran `oc new-app quay.io/quarkus/ubi-quarkus-native-s2i:19.1.1~https://github.com/quarkusio/quarkus-quickstarts.git --context-dir=rest-json --name=quarkus-quickstart-native`

**Comment by cescoffier** [comment]
@evanshortiss If you follow the guide (https://quarkus.io/guides/openshift-s2i-guide), you will see you need to increase the memory limit of your build. Compiling to native requires a huge amount of memory.
