### ISSUE TITLE
Add `quarkus.arc.context-propagation.enabled` to Context Progagation guide

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#34123]
### Description

After a considerable amount of effort, I finally stumbled upon `quarkus.arc.context-propagation.enabled` while broswing through the code, and it seems to have resolved my problem. I must admit, I was surprised to find that this configuration is not mentioned in the official documentation at https://quarkus.io/guides/context-propagation. As a result, I'm still uncertain about the full implications of setting it to false, which in turn requires a more extensive testing process to ensure everything continues to function as expected.

My use case for disabling `quarkus.arc.context-propagation.enabled` is that I require a new request scope when executing a uni subscriber on a different thread asynchoniously. By doing so, I can detach from the original request scope without losing crucial tenant context information.

Therefore, I propose enhancing the existing guide on [CONTEXT PROPAGATION IN QUARKUS](https://quarkus.io/guides/context-propagation) to include detailed information about the `quarkus.arc.context-propagation.enabled` property and its effects when both enabled and disabled. With this addition, the mechanisms of the context propagation will become more accessible and developers are enabled to adjust the context propagation settings more effectively.

**Comment by FroMage** [comment]
Hi, could you show us some code to explain why you need to disable this?

Note that this setting is pretty dangerous as it applies to your entire application, as opposed to finer-grained options that should have the same results for you.

**Comment by mkouba** [comment]
> Note that this setting is pretty dangerous as it applies to your entire application...

Hm, I wouldn't say it's "pretty dangerous". It should be safe to use this setting in most situations, esp. when no SmallRye Context Propagation API is explicitly used in the code.

**Comment by HerrDerb** [comment]
> could you show us some code
Hm this got me thinking, while looking for it. I think I'll review all the current cases again to check if the async side effects are really necessary 🧐 maybe it boils down to code smells. I'll come back to you.

**Comment by Ladicek** [comment]
I wouldn't call it "dangerous", but the meaning of this configuration option isn't exactly obvious either. IIRC, it disables usage of MP Context Propagation for CDI, which in turn means that the CDI request context will only be propagated across Vert.x threads and not to/from other threads. That is hardly intuitive.

My personal opinion is that we should not commit to any particular meaning of this configuration and treat it as an interim solution on the path to doing context propagation properly.

**Comment by mkouba** [comment]
>  the meaning of this configuration option isn't exactly obvious either

The current wording is: _"If set to true and SmallRye Context Propagation extension is present then enable the context propagation for CDI contexts."_. That's pretty clear IMO.

> ...which in turn means that the CDI request context will only be propagated across Vert.x threads and not to/from other threads. That is hardly intuitive.

Note that for many apps (if not the majority) this is not a problem because we use Vert.x threads everywhere.

> My personal opinion is that we should not commit to any particular meaning of this configuration and treat it as an interim solution on the path to doing context propagation properly.

+1 for interim solution but I suspect that it will be a very long-lived  interim solution...

**Comment by Ladicek** [comment]
> > the meaning of this configuration option isn't exactly obvious either
> 
> The current wording is: _"If set to true and SmallRye Context Propagation extension is present then enable the context propagation for CDI contexts."_. That's pretty clear IMO.

This is actually not very clear, because the term "context propagation" is heavily overloaded. AFAIK, the meaning is more like: _If set to true and the SmallRye Context Propagation extension is present, then SmallRye Context Propagation will propagate CDI contexts._

> > My personal opinion is that we should not commit to any particular meaning of this configuration and treat it as an interim solution on the path to doing context propagation properly.
> 
> +1 for interim solution but I suspect that it will be a very long-lived interim solution...

For sure :-)

**Comment by mkouba** [comment]
> This is actually not very clear, because the term "context propagation" is heavily overloaded. AFAIK, the meaning is more like: If set to true and the SmallRye Context Propagation extension is present, then SmallRye Context Propagation will propagate CDI contexts.

Well, if you want to be 100% clear then it should read _"... then MicroProfile Context Propagation will be enabled for CDI contexts."_ but it's IMO kind of implicit that SmallRye Context Propagation implements MP CP...

**Comment by Ladicek** [comment]
Yeah. The very fact that we store the CDI request context (1) into the Vert.x duplicated context (2), which is automatically propagated (3), means that CDI context propagation (4) works even without MP Context Propagation (5), and that all means that the words context and context propagation (I tried to number them earlier in the sentence) are very hard to reason about.

**Comment by HerrDerb** [comment]
@FroMage We do need some async stuff, like sending push messages, which are a side effect.
The current solution by switching of the propagation seems to work for me so far still.

@all You got to help me now what's the outcome of your discussion :)

**Comment by mkouba** [comment]
> @FroMage We do need some async stuff, like sending push messages, which are a side effect. The current solution by switching of the propagation seems to work for me so far still.
> 
>  You got to help me now what's the outcome of your discussion :)

So I think that we should improve the documentation of the `quarkus.arc.context-propagation.enabled` config property and make it very clear that it merely enables/disables the usage of MP Context Propagation APIs.

Let me try to submit a PR.
