### ISSUE TITLE
Add `hibernate.type.preferred_uuid_jdbc_type` as a supported property

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#34139]
### Description

I have to set that property to `CHAR` to stay compatible with how we were/are mapping UUID with Quarkus 2.16/Hibernate 5.6 and MariaDB 10.6 (which has no native UUID type yet).

Using the "unsupported" property results in a warning.

See also: https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#basic-uuid

**Comment by yrodiere** [comment]
Hello. Thanks for the report, but this is very similar to #33328:

> If we're talking about backwards compatibility, Quarkus offers its own [Hibernate ORM 5.6 compatibility switch](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#database-orm-compatibility) which, while not perfect, will cover `preferred_instant_jdbc_type` [and should cover `preferred_uuid_jdbc_type`] and much more. And it does that without opening a pandora box of exposing many configuration properties that can be combined and interact with each other, making it very difficult to cover every combination in tests.
> 
> In any event, such backwards compatibility hacks are transient in nature: they need to disappear eventually because we can't just accumulate them forever while keeping Quarkus/Hibernate ORM maintainable. So I'm reluctant to add "supported" configuration knobs for these, especially since both [Hibernate ORM 5.6 compatibility switch](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#database-orm-compatibility) and `unsupported-properties` already work fine.
> 
> Now if there's an argument for setting `preferred_instant_jdbc_type` [or `preferred_uuid_jdbc_type`] even for new applications, for reasons independent from backwards compatibility, that's a completely different discussion. But I don't think that's where you were going?

**Comment by yrodiere** [comment]
I see you want to set the property to `CHAR`, while the compatibility switch sets it to `BINARY`, and only in some cases. This means we probably need to adjust the behavior of the compatibility switch. I'll look into this.

**Comment by yrodiere** [comment]
From what I can see in [our tests](https://github.com/quarkusio/quarkus/blob/94492d0828b6fa653b332ded6e96f9ffb7a25da3/integration-tests/hibernate-orm-compatibility-5.6/mariadb/src/test/resources/db/migration/V1.0.0__orm5-6.sql#L18), a Quarkus 2 application targeting MariaDB with no specific dialect would use `binary(255)` as the SQL type for UUIDs. Which means the Hibernate ORM 5.6 compatibility switch is working fine, at least in the default case, and as far as I can see the latest Quarkus 2.x was using `MariaDB106Dialect` by default for MariaDB.

Maybe there is additional configuration in your case that changes the behavior of Hibernate ORM? Did you set an (older) dialect explicitly through `quarkus.hibernate-orm.dialect`, maybe?

**Comment by famod** [comment]
We were using:
```yaml
quarkus:
  hibernate-orm:
    dialect: org.hibernate.dialect.MariaDB106Dialect
```
Now it's:
```
quarkus:
  datasource:
    # ...
    db-version: 10.6
```
(`db-kind: MariaDB` in both cases)

What's probably more relevant though is that we are using strongly typed wrappers around a UUID field (say not just a `private UUID id;` field in a `Fruit` entity but a `private FruidId id;` instead). We call those UUID wrappers "DomainIdentifiers".
With Q2 we _had_ a "deep" integration of those types into Hibernate, via `SqlTypeDescriptor`, `AbstractSingleColumnStandardBasicType` and `TypeContributor`.
In the respective `SqlTypeDescriptor` we had:
```java
        @Override
        public int getSqlType() {
            return Types.CHAR; // MariaDBDialect lacks uuid type, map to CHAR (to be exact CHAR(36))
        }
```
And likewise, our Liquibase scripts are using `CHAR(36)` for the id columns.

Now, for the migration to Q3 we dropped that deep integration and are trying to use our DomainIdentifiers via `@EmbeddedId` ([which _should_ work in H6.2](https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/HHH-11955.20in.20context.20of.20Quarkus.203.20upgrade/near/349300090) and avoids a lot of boilerplate).
Since we don't want to migrate our id columns to binary for now (we might move to the native uuid type when/if we upgrade to MariaDb 0.11), we have to set `preferred_uuid_jdbc_type`. We could use the annotation approach instead, but we prefer a global solution.

PS: We are seeing at least two other issues in Q3/H6 w.r.t. to our (now `@EmbeddedId`) DomainIdentifiers, so expect more issues from us ("us" is @mickroll and I). :wink: 
As a last resort we'll probably have to go back to the deeper integration (and hope we don't hit other issues with that).

PPS: We are not using the compat switch for now.

**Comment by yrodiere** [comment]
Ok, so from what I understand this is indeed a feature request and not related to a migration issue.

I personally can't work on this right now, so I'll let others debate of the priority.

In the meantime, if the default behavior doesn't work for you, you will probably have to rely on `quarkus.hibernate-orm.unsupported-properties`, or `@JdbcTypeCode(...)` in each "domain identifier" type. A "deeper" integration with custom types (`UserType`) seems worse than those two solutions in every aspect IMO, but YMMV.

**Comment by yrodiere** [comment]
Closing in favor of #33328 , which would handle `hibernate.type.preferred_uuid_jdbc_type` and more.
