### ISSUE TITLE
quarkus.http.cors.exposed-headers not working in POST

### ISSUE THREAD

**Issue by bumbel42so** [quarkusio/quarkus#34131]
### Describe the bug

I set quarkus.http.cors.exposed-headers but since Quarkus 3.x they only provided in OPTIONS request, not in GET, POST, PUT request. I need this in Angular Frontend to access custom headers.

### Expected behavior

I want to get access-control-expose-headers at GET, POST, PUT Request, like in Quarkus 2.16

![image](https://github.com/quarkusio/quarkus/assets/60612641/4167e359-1afa-4c75-91c6-b85bc42e4e5b)

### Actual behavior

GET
![image](https://github.com/quarkusio/quarkus/assets/60612641/11d12b2f-8de6-45cb-8a49-68bb9a458960)

OPTIONS
![image](https://github.com/quarkusio/quarkus/assets/60612641/33202a27-6ccf-40db-abd5-063d24c7880e)
(i also need to add Access-Control-Request-Headers Request Header to get access-control-expose-headers Response Header

### How to Reproduce?

1. application.properties
```
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.exposed-headers=x-custom
```

2. send request
3. see response headers

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.3086]

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by sberyozkin** [comment]
@bumbel42so Thanks for the report, it was fixed with #33923. Sorry about it, closing now as a Duplicate
