### ISSUE TITLE
Lombok @EqualsAndHashCode conflict with Quarkus caching

### ISSUE THREAD

**Issue by roielcordero** [quarkusio/quarkus#34130]
### Describe the bug

We are using:
lombok 1.18.24
Quarkus [2.16.7.Final]

When using EqualsAndHashCode at both parent and child class, all configs that were set are ignored.

### Expected behavior

When using EqualsAndHashCode at both parent and child class, all configs already defined at config application.properties should work

### Actual behavior

When using EqualsAndHashCode at both parent and child class, all configs that were set are ignored.

### How to Reproduce?

1. Create new project with 1 endpoint
     **ShapeController**
      getShape(Circle circle)
    **ShapeService**
       @CacheResult(cacheName = "shape")
       getShape(Circle circle)

```
%dev.quarkus.cache.enabled=true
%dev.quarkus.cache.type=caffeine
%dev.quarkus.cache.caffeine."shape".initial-capacity=1
%dev.quarkus.cache.caffeine."shape".maximum-size=2
%dev.quarkus.cache.caffeine."shape".expire-after-write=1M
```
```
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class Circle extends Shapes {

private double radius;
}
```

```
@NoArgsConstructor
@Getter
@Setter
@EqualsAndHashCode
public class Shapes {
private String color;
}
```

2. Create another endpoint to retrieve the the caching keys
   **CacheController**
```
    @CacheName("shape)
    Cache cache;

    @GET
    @Path("/cache")
    @Produces(MediaType.APPLICATION_JSON)
    public Response retrieveCache() {
        return Response.ok().entity(cache.as(CaffeineCache.class).keySet()).build();
    }
```
3. Hit the endpoint for getShape 3 times with different Circle data
4. Retrieve /cache endpoint, it will return 3 keys even we already defined maximum-size=2
5. After 2 mins the /cache endpoint will still return those 3 keys even we already defined expire-after-write=1M

_When we removed the @EqualsAndHashCode at Shape class. It will work as expected but the problem is when I hit 2 times the endpoint with same color, it will create 2 keys for that color because of EqualsAndHashCode does not defined._

### Output of `java -version`

java 11.0.6

### Quarkus version or git rev

2.16.7.Final

**Comment by geoand** [comment]
Does the same problem occur with Quarkus 3.1.x? If so, please attach a sample project that demonstrates the problem

**Comment by geoand** [comment]
Closing for lack of feedback
