### ISSUE TITLE
Gradle Application Plugin missing latest versions in Maven?

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#34148]
### Describe the bug

I have custom Gradle plugins that use `classpath 'io.quarkus:gradle-application-plugin:<version>'`. But when I tried to update my application to `3.1.2`, I noticed that `gradle-application-plugin` only has up to version `3.0.0` ([Maven](https://mvnrepository.com/artifact/io.quarkus/gradle-application-plugin)).

Is this no longer supported?

### Quarkus version or git rev

3.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by geoand** [comment]
Does https://plugins.gradle.org/plugin/io.quarkus answer your question?

**Comment by mikethecalamity** [comment]
I'm guessing what you're saying is that `gradle-application-plugin` can only be retrieved from the Gradle Plugin Portal now?

**Comment by geoand** [comment]
That appears to be the case

**Comment by maxandersen** [comment]
Is There a reason why we don't publish those artifacts there anymore?
