### ISSUE TITLE
REST Client Reactive behaves differently from the classic one regarding query and body params

### ISSUE THREAD

**Issue by hbelmiro** [quarkusio/quarkus#34143]
### Describe the bug

Given the following two methods of a REST Client interface:

https://github.com/hbelmiro/complex-queryparams-demo/blob/676c920f2a3aba452e7db523843377a35181284b/src/main/java/com/thegreatapi/Client.java

```java
    @GET
    @Path("/get")
    @Produces({"application/json"})
    String get(@BeanParam Person person);

    @PATCH
    @Path("/patch")
    @Consumes({"application/json"})
    @Produces({"application/json"})
    void patch(Person person);
```

And the following class:

https://github.com/hbelmiro/complex-queryparams-demo/blob/84dddc1b308466435d5f197cf2f8ec5954770328/src/main/java/com/thegreatapi/Person.java

```java
public class Person {

    @QueryParam("id")
    private String id;

    @QueryParam("name")
    private String name;

    // getters and setters...
}
```

When using REST Client Classic, the parameters are sent as query params for the GET method and in the request body for the PATCH method.
But when switching to REST Client Reactive it doesn't work anymore. In the PATCH method, the parameters are sent as Query params.

I couldn't find anything related to this in the specification or in the docs. So, I don't know if this is a bug or if there's a better way to achieve the classic behavior.

I created a reproducer in https://github.com/hbelmiro/complex-queryparams-demo. The expected behavior is defined in the [tests](https://github.com/hbelmiro/complex-queryparams-demo/blob/84dddc1b308466435d5f197cf2f8ec5954770328/src/test/java/com/thegreatapi/ClientTest.java). When we change the dependencies to the classic ones, both tests pass.

### Expected behavior

Tests should pass.

### Actual behavior

`testPatch` fails with:

```
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
PATCH
/patch

Content-Type: application/json

{
  "id" : "42",
  "name" : "Ozzy Osbourne"
}> but was:<
PATCH
/patch?id=42&name=Ozzy+Osbourne



>
```

### How to Reproduce?

Run `mvn verify`.

### Output of `uname -a` or `ver`

Linux fedora 6.3.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun  9 15:21:11 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "20.0.1" 2023-04-18 OpenJDK Runtime Environment Homebrew (build 20.0.1) OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0

**Comment by cescoffier** [comment]
Why would patch transform the query parameters into body content? The query can be part of the resource identification, and thus should not be in the body. 

Do I miss something obvious?

**Comment by hbelmiro** [comment]
OK, we can switch from PATCH to POST. We'll have the same issue.

The scenario is the following: Given an API that has two methods POST and GET.

For the POST method, the parameters must be sent in the body
For the GET method, the parameters must be sent in the query

The question is: What can I do to use the same `Person` class as a parameter for both methods?

I'm not sure if what I did for REST Client Classic (the one that works) is correct, or if it just works by chance.

### More context
We're facing this issue in the [quarkus-openapi-generator extension](https://github.com/quarkiverse/quarkus-openapi-generator/issues/357), which generates REST Client interfaces from OpenAPI documents. The approach I mention, which I'm not sure is the right one, is the one we use in the extension to generate the REST clients.

**Comment by geoand** [comment]
To me, the behavior of RESTEasy Classic is what is wrong here... What it's essentially doing is ignoring the `@QueryParam` annotations and instead converting the entire body to json.

I am pretty sure that this behavior is not documented anywhere, and your previous code was depending on an implementation behavior.

@Sgitario WDYT?

**Comment by Sgitario** [comment]
> @Sgitario WDYT?

Indeed. Ignoring `@QueryParam` does not sound right to me...

**Comment by geoand** [comment]
So I am going to close this as won't fix

**Comment by hbelmiro** [comment]
@geoand @Sgitario 
I understand. What would be the right way to achieve the behavior I need?

**Comment by geoand** [comment]
You'll need different domain objects
