### ISSUE TITLE
[keycloak-admin-client] Keycloak Dev Service

### ISSUE THREAD

**Issue by agreedSkiing** [quarkusio/quarkus#34156]
### Description

Would it be possible to add the keycloak DevService to the `keycloak-admin-client` and `keycloak-admin-client-reactive` extensions?

Also backporting it to quarkus 2.

**Comment by geoand** [comment]
> Also backporting it to quarkus 2.

I am afraid this is out of the question if we even decide that the request makes sense

**Comment by agreedSkiing** [comment]
@sberyozkin found a workaround for my project since I only want to use the admin client integration i just added the quarkus-oidc at the test scope which quarkus:dev seems to run

**Comment by sberyozkin** [comment]
@agreedSkiing OK, thanks, yes, `quarkus-oidc` in the test scope should be fine, DevService will support the tests, do you think we can close this issue ?

**Comment by agreedSkiing** [comment]
@sberyozkin yes
