### ISSUE TITLE
OIDC: should provide configuration to suppress or allow challenges based on resource path

### ISSUE THREAD

**Issue by allertonm** [quarkusio/quarkus#34169]
### Description

When accessing an authenticated endpoint, if the OAuth tokens are present in the session cookie but have expired, the OIDC implementation will redirect to the authorization server. 

This can present a problem for single-page applications (using `ApplicationType.WEB_APP`) because this condition is most likely to happen when the application accesses a REST endpoint, and the redirect will be "eaten" by the XHR invocation, but not before setting the `q_auth` cookie, which will cause state validation failures when the user is redirected to the application's entry point.

(The workaround for this is to redirect via an unauthenticated endpoint that clears any `q_auth` cookies.)

What would be helpful here is a way to control the behaviour upon authentication failure dependent on the path being accessed - similar to the existing `quarkus.http.auth.permission` mechanism, but with the option to either deny (by returning 401) or challenge (by redirect to the auth server.)

**Comment by sberyozkin** [comment]
@allertonm I think this is already supported with:

https://quarkus.io/guides/security-oidc-code-flow-authentication-concept#single-page-applications

where SPA can intercept a challenge.

**Comment by allertonm** [comment]
@sberyozkin thanks, that looks like it will work for our case, I will look into this.

(FWIW I did search the config documents for "challenge" to see if there was an existing mechanism for this.)

**Comment by sberyozkin** [comment]
@allertonm Thanks, let me know if it works please.

**Comment by sberyozkin** [comment]
@allertonm Please also watch #33436 in case it can be relevant for your case, I did not have time to deal with it yet, but it is on the map

**Comment by allertonm** [comment]
@sberyozkin works very well - thanks!

**Comment by sberyozkin** [comment]
Thanks @allertonm
