### ISSUE TITLE
Profile on property don't work at hot deployment moment

### ISSUE THREAD

**Issue by rhuan080** [quarkusio/quarkus#3416]
**Describe the bug**
When I use a property with profile ("%dev.quarkus.datasource.password") in dev mode and Quarkus applies a hot deployment, the app take an error like this:
    Caused by: java.util.NoSuchElementException: Property quarkus.datasource.password not found

**Expected behavior**
The property should be found.

**Actual behavior**
The property was not found.

**To Reproduce**
1. Create a app using hibernate
2. Create a datasource using dev profile 
3. Start the app in dev mode
4. Make changes in your code to force the hot deployment

**Configuration**
%dev.quarkus.datasource.url = jdbc:postgresql://localhost:5432/testDB
%dev.quarkus.datasource.driver = org.postgresql.Driver
%dev.quarkus.datasource.username = admin
%dev.quarkus.datasource.password = admin
```

**Comment by gwenneg** [comment]
Hi @rhuan080 and thanks for reporting this bug!

It looks like the same issue as #3409.

**Comment by dmlloyd** [comment]
Should have been fixed by #3701 if it is indeed the same as #3409.  If the bug persists, please reopen.
