### ISSUE TITLE
Dev UI Documentation update for Security 

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#34175]
### Description

This page https://quarkus.io/version/main/guides/security-openid-connect-dev-services need to be updated to reflect Dev UI v2.

**Comment by sberyozkin** [comment]
Good catch, thanks @phillip-kruger, I can have a look at capturing a few images

**Comment by phillip-kruger** [comment]
Thanks :)

**Comment by michalvavrik** [comment]
hi @sberyozkin , this is terrible week, but I already started on this minor adjustments and I'll create PR over weekend. It is not hard work. I'll do documentation fix described here too - I knew about it, but I expected we will get feedback on issues Renarde run into while migrating (I think you mentioned something about it) - not necessary.

Please provide these image updates. Thanks

**Comment by sberyozkin** [comment]
Hi @michalvavrik Sure, do take your time please, just open a PR to tune things a bit when you get a chance, please don't spend time in the docs, I can do it and ask you to review

**Comment by michalvavrik** [comment]
Time didn't allow me to actually do what I want, sorry. I shall find time next week.

**Comment by sberyozkin** [comment]
Hi @michalvavrik Np at all, I'm just about to open a PR and I can follow up later with some minor image tuning
