### ISSUE TITLE
QuarkusApplication with Argument class/interface as a parameter

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus#34171]
### Description

Quarkus supports implementation of QuarkusApplication which has a run(String... args) method to access command line arguments, I'm thinking if the args has a interface that supports basic command line features immediately for example:

- getOptions
- getArgs

### Implementation ideas

This is an additional interface/s. Add another interface named QuarkusArgument as an example to make it as a parameter for an overloaded ' run()` method in QuarkusApplication.
Example interface

```
interface QuarkusArgument {

String[] getOptions();

String[] getArguments();

// and so on.....
}
```

So that other developers doesn't need to create their own custom methods just to manipulate the whole `String... args` argument when we can create immediately the obvious ones.

**Comment by geoand** [comment]
Thanks for reporting, but to be honest  I don't think this is necessary because our [Picocli integration](https://quarkus.io/guides/picoclihttps://quarkus.io/guides/picocli) provides far more capabilities.
