### ISSUE TITLE
Implement Jakarta RPC

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34183]
### Description
Implement Jakarta RPC (aka gRPC clients and servers with some Jakarta sauce).

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

**Comment by starksm64** [comment]
The github repo for the Jakarta RPC project is here:
https://github.com/jakartaee/rpc

The readme there calls out the spec project page and the mailing list

Project page: https://projects.eclipse.org/projects/ee4j.rpc
Mailing list: https://accounts.eclipse.org/mailing-list/jakartarpc-dev

**Comment by AngeloRubens** [comment]
hi, any news about this implementation?

**Comment by cescoffier** [comment]
No, nothing has been started. I do not believe it will be implemented in 2024. But, as always, contributions are more than welcome.

**Comment by cescoffier** [comment]
I can confirm it's not going to be implemented in 2024. 

After discussing and evaluating the community's current interests, we've decided not to implement Jakarta REST yet. The level of demand and the potential value to the broader Quarkus community has faded, and we believe our resources are better focused on other priorities. 
We can revisit this if there's renewed interest in the future.
