### ISSUE TITLE
Reactive Messaging (RabbitMQ) Can dynamic binding be supported? 

### ISSUE THREAD

**Issue by zuochangqin** [quarkusio/quarkus#34189]
### Description

Now that the binding relationship between routingkey and queue is established before startup, what if you want dynamic binding according to certain rules?For example, if you want to do consumer load balancing in rabbitmq, some services will listen to these queues, others will listen to other queues, and if the service goes offline, it will be dynamically allocated and so on.

**Comment by cescoffier** [comment]
I don't believe we can support such a use case. Note that rabbitMQ has shared queue that may work for you (and we do support this).

**Comment by cescoffier** [comment]
@ozangunalp WDYT?

**Comment by cescoffier** [comment]
Forgot to mention that you can always use the low-leval rabbitmq client if you want.

**Comment by ozangunalp** [comment]
I think there are policies you can set on RabbitMQ for such kind of automatic binding, but I am not an expert. 
It's definitely not something we can do on the connector code.
