### ISSUE TITLE
WebSocket rework

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34188]
### Description

WebSocket support needs some love:

- `onMessage` must be run on a duplicated context (#32801)
- Development model improvements such as:

    - Allows onMessage to return something that will automatically serialized to the web socket (single point of broadcast)
    - Automatically mapped the message into an object
    - Handle serialization/deserialization (text and binary)
    - Support blocking and non-blocking (Uni)

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

- [ ]  https://github.com/quarkusio/quarkus/issues/35701
- [ ] https://github.com/quarkusio/quarkus/issues/32801

**Comment by mschorsch** [comment]
Should support kotlin coroutines #29929

**Comment by geoand** [comment]
I am going to close this in favor of #38473 which has a ton more details and which formed the base of the [new](39142) websockets implementation.
