### ISSUE TITLE
OAuth2IdentityManager.verify(String id, Credential credential) - infinite loop

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3419]
OAuth2IdentityManager.verify(String id, Credential credential) has infinite loop / recursive call.

link to code: https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-oauth2/runtime/src/main/java/io/quarkus/elytron/security/oauth2/runtime/auth/OAuth2IdentityManager.java#L31

@loicmathieu should be current `return verify(null, credential);` changed to `return verify(credential);` ?

**Comment by loicmathieu** [comment]
Yes, but hopefully the code should not be called by the current implementation of the extension :)
Fixed in PR #3421
