### ISSUE TITLE
TransactionalInterceptorBase.getTransactionConfiguration(InvocationContext ic) - dead code

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3420]
TransactionalInterceptorBase.getTransactionConfiguration(InvocationContext ic) method has dead code

https://github.com/quarkusio/quarkus/blob/master/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/interceptor/TransactionalInterceptorBase.java#L84-L87

Line 86 is never executed as `ic` is not null, otherwise there would be NPE on line 84.

@loicmathieu can you look into it ?

**Comment by loicmathieu** [comment]
See it, should be if(configuration == null) ...
I do some more test and I prepare a PR for it.

**Comment by loicmathieu** [comment]
PR #3422
