### ISSUE TITLE
Quarkus Rest Reactive Client: Latency Issue

### ISSUE THREAD

**Issue by git4rputuval** [quarkusio/quarkus#34218]
### Issue
The Rest Reactive Client and/or the Rest Reactive Controller to which the rest client connects, is taking more time to perform a basic query operation. Features of this issue:

- The React client takes 10 seconds for a 70kb data. The log on the rest client shows that it called the rest controller at a particular time, but on the rest controller side, we can see the log entered 8 seconds after the rest client call.
- But if the same rest client is called again within 5 to 10 seconds, it takes less than 1 second (300ms to 600ms).
- Now wait for 15 to 20 seconds, and called the rest client again, and it takes 10 seconds. 

All the classes are ApplicationScoped.
The Rest client configuration & the rest reactive controller configurations are basic; same as provided in the quarkus guide. We had added the RBAC authorization to the rest reactive controller methods of both service and component layer. Both the layers use the same RBAC token.

### Design
A component layer takes the request from the service layer to perform the basic CRUD operation and complex transactional operations.
A service layer takes the request from a React Frontend, performs the authorization and integrity checks. It then calls all the components in sequence and parallel to perform the business logic and return the response back to the React Frontend.

The component layer and the service layer use Rest Reactive to provide the API access. The service layer uses the Rest Reactive client to connect to the component layer.

### Summary
We thought it to be a specific component issue, but then we found that all the service layers use rest client performs in the same manner, first time taking 10 seconds, while the follow-on calls takes less than a second.

### Expected behavior

Basis the subsequent calls of the rest client, all requests should take only 300ms to 600ms and not 10 seconds.

### Actual behavior

First call take 10 seconds, subsequent calls take 300ms to 600ms.
After a few seconds of no action, try the same call again and it takes 10 seconds again.

### How to Reproduce?

Quarkus Rest Reactive sample 1
Quarkus Rest Reactive sample 2
Quarkus Rest Reactive client in sample 1 calls Quarkus Rest Reactive sample 2.

### Output of `uname -a` or `ver`

ubuntu 22.04

### Output of `java -version`

11

### Quarkus version or git rev

2.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.3

**Comment by geoand** [comment]
The only way we can help on this is you provide a sample application that exhibits the behavior you mention.

**Comment by geoand** [comment]
Closing for lack of feedback
