### ISSUE TITLE
Tracing Issue in Version 3.1.2 - Spans Not Consolidated under Parent Span

### ISSUE THREAD

**Issue by cescalonso** [quarkusio/quarkus#34212]
### Describe the bug

In version 3.0.4 the spans are in the same trace but in version 3.1.2 they are not, each span is like in a distinct trace. The parent span is created from `@WithSpan` around a method.

### Expected behavior

![image](https://github.com/quarkusio/quarkus/assets/3135285/faa07e38-e1d3-4559-b82a-b93738d6f91e)
![image](https://github.com/quarkusio/quarkus/assets/3135285/2f369b16-387e-47dc-a855-64c9a32ab8e1)

### Actual behavior

![image](https://github.com/quarkusio/quarkus/assets/3135285/8a572a7e-2c5a-4df7-acd8-c993157133d7)

### How to Reproduce?
1. Run jaeger:
```
docker run --rm --name jaeger \
-e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
-e COLLECTOR_OTLP_ENABLED=true \
-p 6831:6831/udp \
-p 6832:6832/udp \
-p 5778:5778 \
-p 16686:16686 \
-p 4317:4317 \
-p 4318:4318 \
-p 14250:14250 \
-p 14268:14268 \
-p 14269:14269 \
-p 9411:9411 \
jaegertracing/all-in-one:latest
```
2. Run the sample application [sample.zip](https://github.com/quarkusio/quarkus/files/11818988/sample.zip)

**Comment by geoand** [comment]
Can you please attach a sample application that works like you say with `3.0.4` but does not with `3.1.2`?

**Comment by cescalonso** [comment]
@geoand I just updated the Issue with the sample. Hope that now it's easier to reproduce.

**Comment by geoand** [comment]
@Sgitario I have tracked this issue down to https://github.com/quarkusio/quarkus/issues/32839.

It seems like that change, context propagation for the client request is not working properly. Can you have a look please?

**Comment by gsmet** [comment]
Yes, please, let's make this a priority as it seems very problematic.

**Comment by Sgitario** [comment]
If the fix for https://github.com/quarkusio/quarkus/issues/32839 is the cause of this issue, then the problem has been always there but it happened randomly. 
Those changes made the behavior consistent, so if this now happens always, I think this is a good thing. 
I guess some context needs to be propagated when switching between contexts (I don't know which data yet), but will take a look tomorrow morning).

**Comment by geoand** [comment]
> If the fix for https://github.com/quarkusio/quarkus/issues/32839 is the cause of this issue, then the problem has been always there but it happened randomly.

I don't think this is the case as the reproducer worked consistently with every run I did in multiple versions before `3.1.0.CR1`

**Comment by Sgitario** [comment]
>
> I don't think this is the case as the reproducer worked consistently with every run I did in multiple versions before `3.1.0.CR1`
> 

Yes, I know. The first time I saw the erratic behavior was in CI (locally, everything worked fine) and to reproduce it, I had to stress my local machine out and run the client many times.

**Comment by geoand** [comment]
Interesting

**Comment by brunobat** [comment]
I wonder how this is not breaking the tests using this: 
https://github.com/quarkusio/quarkus/blob/main/integration-tests/opentelemetry/src/main/java/io/quarkus/it/opentelemetry/TracedService.java

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/34250 should fix this issue. I provided some explanation about how started failing. Let's continue the discussion in the pull request.
