### ISSUE TITLE
IsolatedRemoteDevModeMain Mutable Jar error message

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus#34230]
### Description

Misleading error message when  JAR type is not Mutable Jar in IsolatedRemoteDevModeMain.

At Line 93:

```
 if (!start.getJar().getType().equalsIgnoreCase(PackageConfig.BuiltInType.MUTABLE_JAR.getValue())) {
                    throw new RuntimeException(
                            "remote-dev can only be used with mutable applications generated with the fast-jar format");
}
```

Should it replace _fast-jar format_ to _mutable-jar format_ right?

Seeing also that in PackageConfig, mutable-jar is treated as fast-jar. But not quite sure if it should be fast-jar format since there's a dedicated FAST_JAR.

```
    public boolean isFastJar() {
        return type.equalsIgnoreCase(PackageConfig.BuiltInType.JAR.getValue()) ||
                type.equalsIgnoreCase(PackageConfig.BuiltInType.FAST_JAR.getValue()) ||
                type.equalsIgnoreCase(PackageConfig.BuiltInType.MUTABLE_JAR.getValue());
    }
```

### Implementation ideas

**Replace message to:**  "remote-dev can only be used with mutable applications generated with the mutable-jar format"

**Comment by geoand** [comment]
I can understand why this confusing, but technically it is correct. 

But maybe we should just change the message to `"remote-dev can only be used with mutable applications i.e, using the mutable-jar package type"`

**Comment by rjtmahinay** [comment]
@geoand Agree on adding the specific package type. Will open a PR on this.
