### ISSUE TITLE
grpc service not working when use-separate-server is set to false and custom http.root-path is set

### ISSUE THREAD

**Issue by SivaM07** [quarkusio/quarkus#34261]
### Describe the bug

When quarkus.grpc.server.use-separate-server=false and quarkus.http.root-path=api/v1 is set, the grpc service is not working. On removing the http root path it works. Is there any specific that needs to be added for the grpc to recognize this custom root path.

### Expected behavior

grpc service should be accessible even with custom http root path

### Actual behavior

grpc service gives 404 error when accessed

### How to Reproduce?

Steps to reproduce

- Take the grpc plaintext quickstart
- Add both use-separate-server false and custom http.root-path
- From Dev UI try to invoke the grpc service

### Quarkus version or git rev

2.16.7.Final

**Comment by cescoffier** [comment]
Oh, nice catch.

@alesj when the default http root is changed, you gRPC route is mounted under than new route, which is not right. In this case we need to mount the route or the parent router. Now the question is... do we have access to that parent router?

**Comment by alesj** [comment]
> Now the question is... do we have access to that parent router?

There is a few routers ... dunno which one is the right one ...

**Comment by cescoffier** [comment]
Yep, that's a very good question...

I believe we need to mount on the `mainRouter`.
Note that is can be `null`:

```
     * Will be {@code null} if `${quarkus.http.root-path}` is {@literal /}.
```

**Comment by alesj** [comment]
What to do then?

**Comment by cescoffier** [comment]
I guess we need to inject the two possible router. If the main router is null, mount the gRPC route on the framework router. Otherwise, on the main router. 

It should be easy to test.

**Comment by SivaM07** [comment]
@cescoffier @alesj given that we know what and where the fix is, can we get a tentative ETA on when this could be fixed? if you are busy on an another priority item, then I am happy to contribute to this fix if you can point me in the right direction.

**Comment by alesj** [comment]
@cescoffier hmmm, we actually currently use `routerBuildItem.getHttpRouter()` ... ?!

**Comment by alesj** [comment]
@cescoffier `getMainRouter` and `getFrameworkRouter` are both package protected methods ...

**Comment by alesj** [comment]
@SivaM07 
* https://github.com/alesj/quarkus/tree/i34261

**Comment by cescoffier** [comment]
@alesj  can you open a PR?

**Comment by SivaM07** [comment]
@alesj , yes that's right, I just tried to install the vertx-http and grpc from your fork. There are 5 testcase failures on vertx-http, checking the testcase failures now.

**Comment by alesj** [comment]
Hmmm, interesting -- why would vertx-http fail?
Since the (big) changes are mostly in grpc ...

**Comment by SivaM07** [comment]
@alesj , nvm the testcase failure was due to startup of test server instance under management. I am trying to build this on windows system and unfortunately 9001 (default management test port) is blocked by some windows service. Trying to work around that.

**Comment by cescoffier** [comment]
Oh gosh... 9001 cannot be used on windows? It the management port used during tests.

**Comment by SivaM07** [comment]
No need to worry, 9001 was blocked by an outdated intel graphics service. Uninstalling it fixed the issue.
For more info 
https://answers.microsoft.com/en-us/windows/forum/all/port-9001-is-not-available/256da9ed-9e1d-4882-8177-703568d6f9c2
https://community.intel.com/t5/Graphics/Intel-graphics-command-center-service-use-port-9001-how-can-I/td-p/719129

**Comment by SivaM07** [comment]
@cescoffier , the mainrouter is null in both the cases (with & without http.root-path), which seems to be due to lack of zero RouteBuildItem with ABSOLUTE_ROUTE route type. When http.root-path is present the mainrouter gets created locally before mounting the httprouter as subrouter and getting assinged to root on the vertxhttprecorder.

Is it okay to forcefully create a mainrouter when http.root-path is present as a fix ?

**Comment by cescoffier** [comment]
Yes, I think it should be created in this case.

**Comment by SivaM07** [comment]
@cescoffier @alesj , could you please review this https://github.com/quarkusio/quarkus/pull/34371
(FYI, this is my first PR, so please let me know if I have missed anything :) )
