### ISSUE TITLE
Quarkus Extension - Failed to create test instance

### ISSUE THREAD

**Issue by akil-rails** [quarkusio/quarkus#34267]
### Describe the bug

I am writing a Quarkus extension that includes a rest client (using quarkus-rest-client-reactive-jackson);  I get the following when I execute ```mvn test``` 

```
2023-06-23 12:10:48,910 INFO  [io.quarkus] (main) quarkus-custom-deployment stopped in 0.031s
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.713 s <<< FAILURE! - in io.quarkiverse.custom.test.CustomTest
[ERROR] io.quarkiverse.custom.test.CustomTest  Time elapsed: 2.713 s  <<< ERROR!
java.lang.RuntimeException: org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
....
....
Caused by: java.lang.IllegalArgumentException: Not a REST client interface: interface io.quarkiverse.custom.runtime.Client. No @Path annotation found on the class or any methods of the interface and no HTTP method annotations (@POST, @PUT, @GET, @HEAD, @DELETE, etc) found on any of the methods
	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:32)
	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:449)
```

The interface is infact annotated with both the @Path and the HTTP method
```
@Path("/todos")
public interface Client {
    @GET
    Uni<Todo> getTodo();
}

```

There is also a custom client builder
```
@Path("/todos")
public class Resource {
    private final Client client;

    public Resource() {
        this.client = QuarkusRestClientBuilder.newBuilder()
                .baseUri(URI.create("https://jsonplaceholder.typicode.com"))
                .build(Client.class);
    }

    @GET
    @Path("/todos/1")
    public Uni<Todo> getTodo() {
        return client.getTodo();
    }
}

```

### How to Reproduce?

Reproducer : https://github.com/akil-rails/quarkus-custom

```mvn test```

### Output of `uname -a` or `ver`

Darwin akil-4.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Apr 24 23:00:57 PDT 2023; root:xnu-7195.141.49.701.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584) Maven home: /Users/akhileshkataria/.sdkman/candidates/maven/current Java version: 17.0.6, vendor: Amazon.com Inc., runtime: /Users/akhileshkataria/.sdkman/candidates/java/17.0.6-amzn Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "11.7.7", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
The problem is that you have not indexed your `runtime` module of your extension (this is **not** done automatically). 

There are various ways to do that, but the easiest is to add an empty `beans.xml` file in `src/META-INF` of the `runtime` module
