### ISSUE TITLE
Null Pointer when sending mail through MailTemplate

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#34272]
### Describe the bug

When sending a mail through the MailTemplate a null pointer is thrown because no ReactiveMailer is available. Injecting a ReactiveMailer in the app, without using it, solves the issue.

### Expected behavior

Sending a mail through the MailTemplate should not require a ReactiveMailer instance to be created.

### Actual behavior

send throws a NullPointerException because no ReactiveMailer has been created

### How to Reproduce?

For the sake of the test I just modified the Quarkus rest example taken from the "start coding" section.
```
@Path("/hello")
public class GreetingResource {
    @Inject
    @Location("confirmation")
    MailTemplate confirmation;
    
    // Does work if I inject the ReactiveMailer, without using it
    //@Inject
    //ReactiveMailer reactiveMailer;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        confirmation.to("mail@fake.com")
                .subject("Welcome to the App")
                .data("name", "Tom")
                .send().await().indefinitely();
        return "Hello from RESTEasy Reactive";
    }
}
```
Add the following html template called hello.html in resources/templates
```
<html>
<head>
</head>
<div>
    <p>Hi {name}!</p>
</div>
```

### Output of `java -version`

OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)

### Quarkus version or git rev

3.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

**Comment by cescoffier** [comment]
@mkouba @gsmet I suspect it's because the mailer bean is removed. 

Can it be repeated to the multi-mailer support?

**Comment by gsmet** [comment]
Mhhh, I thought I fixed this case. I'll have a closer look.

**Comment by gsmet** [comment]
Thanks for the very detailed report. Fix is coming here: https://github.com/quarkusio/quarkus/pull/34281 .
