### ISSUE TITLE
Suggest extensions in the management interface reference

### ISSUE THREAD

**Issue by cambrian-dk** [quarkusio/quarkus#34271]
### Description

The [management interface reference](https://quarkus.io/guides/management-interface-reference) should suggest some extensions (e.g. smallrye-health, quarkus-smallrye-openapi) to install when testing the interface. This is because the management endpoints will not work properly without any extensions.

**Comment by geoand** [comment]
Thanks for reporting, but the link you pointed to does not work. Mind updating it please?

Furthermore, would you be willing to contribute the enhancement of the docs based on what you are proposing?

**Comment by cambrian-dk** [comment]
@geoand fixed it, and sure thing. I'll make a PR soon.
