### ISSUE TITLE
Spring Data API Extension Interface-based Projections occasionally throws NoSuchMethodError

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#34312]
### Describe the bug

It might have something to do with `ParentRepository1` and `ParentRepository2`. When I remove `ParentRepository2` I don't seem to get the exception (even after severeal reloads). But after I readded it, the exception starts happing again after about one to about 5 reloads. (All in dev mode reload, no restarts)

#31774 

### How to Reproduce?

Steps toreproduce:

1. Call createParent in ParentResource
2. Call getParent or getParent
3. If no error happens chnage something in your code (i changed the output from the System.out.println) so that the dev mode reloads your application and got to step 2. It can take some tries to get the error (normally not longer than 5 to 10 tries) but hopefully the error appears.

[reproducerJPAInterfaceMapping.zip](https://github.com/quarkusio/quarkus/files/11868355/reproducerJPAInterfaceMapping.zip)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/34314 fixes the issue.
With the previous version of the code, basically only one of the two repositories of your example would work at any one time.
