### ISSUE TITLE
Manually setting application name seems to be ignored in other properties

### ISSUE THREAD

**Issue by bropyro** [quarkusio/quarkus#34311]
### Describe the bug

In my application I would like to explicitly set the application name via the quarkus.application.name property.

After upgrading to Quarkus 3.1.2.Final (I previously used 2.16.6.Final) referencing quarkus.application.name with my own value in other properties does not work. Instead the gradle project name is used.

### Expected behavior

The specific definition of the application name via quarkus.application.name should be used

### Actual behavior

The value of the gradle property rootProject.name is used.

### How to Reproduce?

1. set the gradle Property rootProject.name e.g. to "app-name"
2. Add the following properties to an application.properties file:

```properties
quarkus.application.name=application-name-reproducer

quarkus.container-image.build=true
quarkus.container-image.image=${quarkus.application.name}:latest

quarkus.smallrye-openapi.info-title=Application Name Reproducer
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.info-description=${quarkus.application.name}
quarkus.smallrye-openapi.store-schema-directory=build/generated/openapi
```

Both image name and OpenAPI description will not use application-name-reproducer but app-name instead

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

The behavior is also the same with Quarkus version 3.0.1.Final

**Comment by geoand** [comment]
This seems to be a Gradle specific issue (it works as expected in Maven).

@snazy @glefloch could one of you take a look please?

**Comment by bropyro** [comment]
Hello @geoand @snazy @glefloch 
I just recognized that this has officially changed with Quarkus 3.0 (https://quarkus.io/guides/gradle-tooling#configuring-quarkus-builds)
So I think you can close the ticket as everything works as designed and sorry for not checking this before.

**Comment by geoand** [comment]
Thanks for the input @bropyro
