### ISSUE TITLE
Opentelemetry grpc test failing with protobuf error on Power

### ISSUE THREAD

**Issue by shreyakajbaje** [quarkusio/quarkus#34326]
### Describe the bug

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) on project quarkus-integration-test-opentelemetry-grpc: Quarkus code generation phase has failed: InvocationTargetException: Failed to find com.google.protobuf:protoc:linux-ppcle_64:exe among dependencies -> [Help 1]`

### Actual behavior

getting InvocationTargetException: Failed to find com.google.protobuf:protoc:linux-ppcle_64:ex even though protoc is installed. failing tests on power. kindly help to resolve this.

### How to Reproduce?

git clone git@github.com:quarkusio/quarkus.git
cd quarkus
MAVEN_OPTS="-Xmx4g" ./mvnw -Dquickly

### Output of `uname -a` or `ver`

Linux  4.18.0-372.9.1.el8.ppc64le ppc64le ppc64le ppc64le GNU/Linux

### Output of `java -version`

openjdk 17.0.7 2023-04-18 LTS OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-2) OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-2)

### Quarkus version or git rev

master

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.5.4 (Red Hat 3.5.4-5)

**Comment by brunobat** [comment]
Getting a Ppc64 computer to debug this will be very challenging. 
@shreyakajbaje what computer/cloud instance are you using to run this code?

**Comment by shreyakajbaje** [comment]
Hi @brunobat, thanks for your reply. I'm using local ppc64le(power) machine

**Comment by ghatwala** [comment]
hey @brunobat  on below ,  getting a ppc64le node/vm can be done via a opensource community based VM request form - https://osuosl.org/services/powerdev/request_hosting/ . Please put in in `Gerrit Huizenga` as the IBM Advocate while filling up the form... Please lemme know if this works to get  access to a debugging instance.

> Getting a Ppc64 computer to debug this will be very challenging.

**Comment by brunobat** [comment]
@alesj once you come from PTO, can you please take a look at this one?

**Comment by cescoffier** [comment]
Any update?

**Comment by shreyakajbaje** [comment]
Hi @cescoffier PPC64LE does not have support for GitHub actions. is it possible that we can enable Jenkins CI?

**Comment by cescoffier** [comment]
Hum, I don't think so. Let me ask @gsmet and @maxandersen, but we want to avoid having a jenkins server behind closed doors.

**Comment by brunobat** [comment]
Not sure how can we fix this issue without CI being able to run this...

**Comment by brunobat** [comment]
@shreyakajbaje Would you be able to create a PR, even if it doesn't work?
@gsmet @maxandersen @cescoffier Power support is quite important for edge computing... How do we want to handle this?
Should we create an alternative build process for power?

**Comment by shreyakajbaje** [comment]
Okay @brunobat I'll raise PR

**Comment by cescoffier** [comment]
Why would power be important for edge? ARM yes, Power not so much (or I missed some big news)

**Comment by cescoffier** [comment]
@shreyakajbaje were you able to open a PR?

**Comment by geoand** [comment]
Closing for lack of feeback
