### ISSUE TITLE
Redis key / value serializer

### ISSUE THREAD

**Issue by RomainWilbert** [quarkusio/quarkus#34329]
### Description

We should be able to customize serializers/deserializers for redis operations. This would allow to add type metadata in json (i.e. support generic objects in json).

**Comment by cescoffier** [comment]
Would having support for TypeReference be enough?

**Comment by RomainWilbert** [comment]
It would be nice to be able to configure Jackson ObjectMapper and set default typing.

**Comment by cescoffier** [comment]
you can already do that by customizing the object mapper of quarkus (https://github.com/quarkusio/quarkus/blob/main/integration-tests/jackson/src/main/java/io/quarkus/it/jackson/MyObjectMapperCustomizer.java)

**Comment by RomainWilbert** [comment]
What if you use Jackson for Redis and elsewhere to make rest calls ?

**Comment by cescoffier** [comment]
It uses the same mapper. Mapper are heavy objects. We don't want to create many of them.

**Comment by RomainWilbert** [comment]
Unfortunately you don't get to choose the payload format when you call
external systems

Le mar. 27 juin 2023, 20:32, Clement Escoffier ***@***.***> a
écrit :

**Comment by cescoffier** [comment]
So, you would need a separate mapper?

**Comment by RomainWilbert** [comment]
It would be nice to be able to configure the mapper or set a bean
serializer like Spring with RedisTemplate

Le jeu. 29 juin 2023, 07:21, Clement Escoffier ***@***.***> a
écrit :

**Comment by cescoffier** [comment]
Yes, I was thinking about that. The memory cost is annoying. I am trying to see if Jackson has some hidden gems to avoid that.

**Comment by cescoffier** [comment]
Ok... so I tried to customize the ObjectMapper, but it turned out to be a dead end. 

Thus, I implemented something I had wanted to do since day 1: custom codecs.
See https://github.com/quarkusio/quarkus/pull/34486.

You can now implement your own codec for a specific type. Implementations are beans, so it can get config values and other beans.
