### ISSUE TITLE
Observing @Initialized(SessionScoped.class) not working

### ISSUE THREAD

**Issue by tandraschko** [quarkusio/quarkus#34332]
### Describe the bug

It seems like Observing @Initialized(SessionScoped.class) is not working; My sample application is using quarkus-undertow and the myfaces quarkus extension. When you access the TestController via EL the observer should be called, currently it doesnt work (doesnt matter if the TestController is request or session scoped)

```
@Named
@SessionScoped
public class TestController {
    public void initS(@Observes @Initialized(SessionScoped.class) HttpSession httpSession) throws Exception
    {
        System.err.println("########################");
        System.err.println("Session initialized");
        System.err.println("########################");
    }
}
```

is not invoked 

### Output of `java -version`

17

### Quarkus version or git rev

3.1.1.Final

**Comment by Ladicek** [comment]
Looks like the session context implementation doesn't fire the event (as well as the `@BeforeDestroyed` / `@Destroyed` events).

**Comment by mkouba** [comment]
> Looks like the session context implementation doesn't fire the event (as well as the `@BeforeDestroyed` / `@Destroyed` events).

It doesn't. The class in question is https://github.com/quarkusio/quarkus/blob/main/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/HttpSessionContext.java.

**Comment by tandraschko** [comment]
nice, thanks!
