### ISSUE TITLE
OpenApi and SwaggerUi exposed on service port instead of management port

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#34353]
### Describe the bug

When setting `quarkus.management.enabled=true`, I expect that the`/q/swagger-ui` and `/q/openapi` endpoints will be exposed on port 9000.  Instead, they are still exposed on port 8080.

`/q/health` and `/q/metrics` are properly exposed on port 9000

### Expected behavior

`/q/swagger-ui` and `/q/openapi` should be available on port 9000. 

### Actual behavior

`/q/swagger-ui` and `/q/openapi` are available on port 8080. 

### How to Reproduce?

In application.properties set the following values:

quarkus.management.enabled=true
quarkus.smallrye-openapi.auto-add-tags=true
quarkus.swagger-ui.always-include=true

### Output of `uname -a` or `ver`

Darwin YGDMXD4XYJ.example.com 21.6.0 Darwin Kernel Version 21.6.0: Thu Jun  8 23:56:13 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c) Maven home: /opt/homebrew/Cellar/maven/3.9.2/libexec Java version: 17.0.6, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.7", arch: "aarch64", family: "mac"

**Comment by phillip-kruger** [comment]
@cescoffier - I am not sure what the rule is here ?

**Comment by geoand** [comment]
Currently, `health`,  `info` and `metrics` adapt to the management port. 
I don't know if we just forgot to add OpenAPI as well or if there were other reasons not to do so, but if it's the former, I think we should use the management port when available.

**Comment by geoand** [comment]
That's the quesion honestly :)

I am fine with it either way

**Comment by cescoffier** [comment]
Unfortunately, there are no "general answer", expect the obvious: it depends(tm). 

I think we should add the possibility (new config properties) to indicate if swagger and open API should be exposed on the management interface. 

If so, it just a matter of calling the `management()` method when the route is built.

**Comment by phillip-kruger** [comment]
I think if a user has got `quarkus.management.enabled=true` and swagger-ui in prod flag the intention is clear ? If the user want the normal port, then they would not enable management ? So I agree with this actually ... Same with GraphQL UI

**Comment by geoand** [comment]
> I think we should add the possibility (new config properties) to indicate if swagger and open API should be exposed on the management interface.

I was thinking the same

**Comment by geoand** [comment]
> I think if a user has got `quarkus.management.enabled=true` and `swagger-ui in prod` flag the intention is clear ? If the user want the normal port, then they would not enable management ? So I agree with this actually ... Same with GraphQL UI

I am not sure myself. Because what happens if the user wants the management port for the rest of the stuff but does **not**  want it for SwaggerUI? How would they opt out?

**Comment by phillip-kruger** [comment]
I guess the same goes for any of the other app. Let say they want swagger but not the other. So maybe we should introduce a new optional (array) config, that take the extensions that should apply management, with the default of all ?

**Comment by phillip-kruger** [comment]
Then they can do `quarkus.management.extensions=[health, metrics]` if they only want those and not swagger ?

**Comment by geoand** [comment]
> quarkus.management.extensions

Ah, I didn't remember we had that

**Comment by phillip-kruger** [comment]
Not sure, the extension `groupId-artifactId` ?

**Comment by geoand** [comment]
I still think it would be easier to just add a Swagger specific property since SwaggerUI seems for the time to be the only one in the gray area

**Comment by phillip-kruger** [comment]
We could do that too, so every extension that might have an exception to the rule add their own like eg `quarkus-swagge-ui-ignore-management=true` ?

**Comment by geoand** [comment]
I would propose that we only add the flag for gray area cases like this - so far the extensions seem to be pretty clear cut

**Comment by bulldog98** [comment]
For the openapi I can also imagine wanting to expose the api definition to other services, so the can do stuff dynamically, or maybe even exposing it via an ingress or something to the api user.

**Comment by phillip-kruger** [comment]
@bulldog98 yea so we have one for openapi (the api definition) and another for swagger (the ui)

**Comment by phillip-kruger** [comment]
@geoand @cescoffier I am happy to add this, should be quick. Is everyone happy with the per extension that has an exception ?

**Comment by phillip-kruger** [comment]
@cescoffier - I see that health-ui is not a management route. Should that also change now ?

**Comment by chonton** [comment]
As a side note, a single document that lists all management endpoints would be useful.  (I was unaware of health-ui)

**Comment by cescoffier** [comment]
@phillip-kruger I decided that Health-ui was not a management route like the swagger UI. However, if we add a flag for swagger, we should have the same for the health UI.

**Comment by phillip-kruger** [comment]
@cescoffier I m looking at this at the moment, but I think we need some CORS between the management interface (in the case of swagger-ui) and the REST endpoint, as the swagger ui now tests a endpoint on another port. Any hints where this should happen ?

**Comment by phillip-kruger** [comment]
@cescoffier I think for now I'll just document what needs to be configured.

**Comment by chonton** [comment]
I think it’s strange to configure the swagger-ui and openapi endpoints on separate ports. What’s the use case?

**Comment by cescoffier** [comment]
@phillip-kruger i'm thinking we should add a built item that provide cors configuration (origins). But... it can be dangerous as it adds a rule to the main application.

I'm wondering if localhost is not an exception actually. It's something we discussed with @sberyozkin not so long ago.

**Comment by phillip-kruger** [comment]
Please see PR for this fix. We set the CORS details automatically (only in Dev Mode and only if not already set)
