### ISSUE TITLE
Investigate Spring API-only deps

### ISSUE THREAD

**Issue by n1hility** [quarkusio/quarkus#3436]
We should probably think about whether its worth creating a spring API only dependency, vs the current real artifacts, that way we don't end up with issues caused by spring implementation classes conflicting with our code or inadvertently getting picked up by the native-image generation process. It also would help establish what APIs we do and don't support.

**Comment by geoand** [comment]
@n1hility I was thinking the same exact thing yesterday

**Comment by geoand** [comment]
@gytis will try and take a look at this while I am on PTO

**Comment by gytis** [comment]
@geoand we could use Maven Shade Plugin to pick the interfaces that are needed for Quarkus and release them under our own GAV name.

**Comment by geoand** [comment]
@gytis Interesting! I think Spring Framework uses gradle however - although yeah the same idea would apply I assume.
Would you like to start experimenting with this? Having this absolutely miminum dependencies would be a great benefit to reduce the footprint of Quarkus applications using the spring modules.

**Comment by gytis** [comment]
I tried it briefly a couple of weeks ago and it works fine. The main issue is to cherry-pick all the required classes and interfaces and list them in the plugin configuration. I'll try it properly on Monday.

**Comment by geoand** [comment]
Awesome, thanks!

**Comment by gytis** [comment]
@geoand take a look at the possible option for spring-di. Here's what would be changed in Quarkus: https://github.com/gytis/quarkus/commit/0c5b2b1460be52bf504fada42413d8aaea6825ec. And here's the dependency pom: https://github.com/gytis/quarkus-spring-context-api/blob/master/pom.xml.

Of course the naming, repository location and ethical aspect (we're taking parts for Spring Framework and renaming it) should be discussed. Once we agree, I could take a stab at spring-web dependencies

**Comment by geoand** [comment]
@gytis I like it!

@n1hility WDYT about the approach? How should we proceed?

**Comment by geoand** [comment]
@gytis we will also need something similar for #4038. 

@n1hility any thoughts on how to proceed with this?

**Comment by gytis** [comment]
@geoand yep, also for Spring Web. It's quite tedious and time consuming to find all the necessary interfaces and classes. That's why I only did Spring DI to see if this approach would work for everybody.

**Comment by geoand** [comment]
Makes sense @gytis. Let's see what @n1hility things before proceeding further.

Also we will need spring data jpa as well

**Comment by cmoulliard** [comment]
> APIs we do and don't support.

This is a great idea as proposed here which should also help to simplify to document, figure out the mapping/binding existing between Spring on Quarkus and Spring frameworks, ...

**Comment by cmoulliard** [comment]
> The main issue is to cherry-pick all the required classes and interfaces and list them in the plugin configuration. I'll try it properly on Monday.

If we follow this approach, that could be hard to maintain as it could be needed to review that for every new Spring project release. I would like to avoid that we have to calculate class needed as that what the case too for OSGI !

**Comment by cmoulliard** [comment]
> Of course the naming, repository location and ethical aspect (we're taking parts for Spring Framework and renaming it) should be discussed. Once we agree, I could take a stab at spring-web dependencies

Can you create a ticket/task for us @gytis in order to discuss with Legal, Naina this ethical aspect if we repackage ?

**Comment by geoand** [comment]
I don't think we would need to update for every release. The way I see it we would only update infrequently since the "API"s we use would practically never change

**Comment by gytis** [comment]
We might only need to change it for every major Spring release. However, we will need to repackage if something related in Quarkus will change.

**Comment by geoand** [comment]
@gytis If you like, please go ahead and continue the work. We will most likely include the repos inside the Quarkus group with descriptive artifactIds

**Comment by gytis** [comment]
@geoand I've pushed APIs needed for DI and Web modules to my org.
quarkus-spring-di-api: https://github.com/gytis/quarkus-spring-di-api
quarkus-spring-web-api: https://github.com/gytis/quarkus-spring-web-api
quarkus change commit: https://github.com/gytis/quarkus/commit/b9261fe73bf890b941f1026084903b3e9b8a5e5f

**Comment by geoand** [comment]
@gytis Great stuff!

@n1hility I don't think I can create repos in the quarkus org, could you do that or give me the karma to do so :)?

**Comment by ebullient** [comment]
I'd like to talk to the Spring team to see if there is a better way to do this.

**Comment by cmoulliard** [comment]
> I'd like to talk to the Spring team to see if there is a better way to do this.

@geoand @gytis What do you think about Erin proposition ? Who should be contacted ?

**Comment by geoand** [comment]
I think that @n1hility and @jclingan also need to weigh in on this. 

Of course it would be idea if the breaking up of Spring jars into API and implementation didn't have to be maintaned by us but was something that occured upsteam. 
How that could happen is something beyong my knowledge.

**Comment by geoand** [comment]
Has been implemented
