### ISSUE TITLE
No way to configure `iat` claim as optional in `oidc`

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#34365]
### Describe the bug

`quarkus-oidc` currently enforces `iat` as mandatory claim and there is no way to make it as optional:

https://github.com/quarkusio/quarkus/blob/e59f6d4a7983fa87ad217d629740813043beecd3/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java#L175

When [CIBA flow](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_server_obtains_consent) is used with Keycloak, Keycloak will call the endpoint that is specified in `--spi-ciba-auth-channel-ciba-http-auth-channel-http-authentication-channel-uri` and will pass JWT in `Authorization` header. This JWT has no `iat` claim.

> %dev.quarkus.keycloak.devservices.start-command=start --storage=chm --http-enabled=true --hostname-strict=false --hostname-strict-https=false --spi-ciba-auth-channel-ciba-http-auth-channel-http-authentication-channel-uri http://host.docker.internal:9999/ciba/callback

I got the following error:

> JWT ... rejected due to invalid claims or other invalid content. Additional details: [[3] No Issued At (iat) claim present.]

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad `iat` is a mandatory claim in OIDC. I've noticed you opened a PR to Keycloak, so that should resolve the issue, right ?

What about adding custom config that makes the claim as optional? Similar to `smallrye.jwt.time-to-live=-1`: #17622

**Comment by Eng-Fouad** [comment]
You are right. I am closing this issue.

**Comment by sberyozkin** [comment]
@Eng-Fouad Sounds good, we can revisit this issue if necessary, please re-open later if needed

**Comment by Eng-Fouad** [comment]
@sberyozkin BTW, is there a temp workaround to customize the JWT parser?

**Comment by wesleysalimansdvb** [comment]
Hi, I would very much appreciate it if the iat claim cloud become optional via config properties. Not everyone uses Keycloak but still uses the oidc dependency to verify the tokens via the public key. Now my code fails because my JWT doesn't have the iat claim (as i use nbf and exp).

rejected due to invalid claims or other invalid content. Additional details: [[3] No Issued At (iat) claim present.]
