### ISSUE TITLE
Add existsById method in PanacheBaseEntity and/or PanacheRepositoryBase

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus#34369]
### Description

Proposing a method (if possible) under the `PanacheBaseEntity ` class and `PanacheRepositoryBase `interface to return a boolean value if an entity by ID exists.

Current logic everytime we check if an entity exists:

```
public boolean isPersonExists() {
  Person p = Person.findById(1);

  return Objects.nonNull(p);
}
```

This is always the case whenever trying to check if an entity exist.

### Implementation ideas

Add a method

`boolean existsById(Id id);`

Let me know for any advice/feedback that you have!

**Comment by rjtmahinay** [comment]
@FroMage @loicmathieu let me know if you have any feedback on this or I can create a PR on this one if you agree!

**Comment by loicmathieu** [comment]
Hi @rjtmahinay I remember we previously had some discussions around it but didn't succeeded in finding them.
The small print is that adding new methods to Panache has a high cost se we usually not add them to only save one line of code.

Currently  you can do it pretty easily using `Person.findByIdOptional(id).isPresent();`, so a new method `Person.existById(id)` will only save you one method call.

**Comment by rjtmahinay** [comment]
@loicmathieu Thanks for the clarification of using Optional instead. I think that's more reasonable. Gonna close this issue!

**Comment by glains** [comment]
@loicmathieu What if `existsById` is not needed to save a line of code, but to save the whole state of the entity to be loaded in memory? From what i can tell, exists would only require:

```sql
SELECT EXISTS(SELECT 1 FROM table WHERE id = :id)
```

However, i do not know how this is delegated to hibernate and if such an improment would provide any benefit.

**Comment by loicmathieu** [comment]
@glains I'm not an hibernate expert but doing this will bypass the first-level cache which is not something we want. This can preform less than loading the entity and checking if it exists as if the entity has already been loaded in the persistence context no SQL queries will hit the database thanks to the first-level cache.
