### ISSUE TITLE
Quarkus is uing ubi8/ubi-minimal:8.6 and openjdk-17-runtime:1.15 while newer versions are available

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#34370]
### Describe the bug

Quarkus is using `ubi8/ubi-minimal:8.6` while 8.8 is available
Quarkus is using `openjdk-17-runtime:1.15` while 1.16 is available

 - https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8
 - https://catalog.redhat.com/software/containers/ubi8/openjdk-17-runtime/618bdc5f843af1624c4e4ba8

We need regular updates of these versions. Or can we use `latest` instead of concrete version?
Can quarkus bot help with reminders to update `ubi8/ubi-minimal` and `openjdk-17-runtime`?

@gsmet @cescoffier 

### Expected behavior

Latest versions to be used

### Actual behavior

Quarkus is using `ubi8/ubi-minimal:8.6` while 8.8 is available
Quarkus is using `openjdk-17-runtime:1.15` while 1.16 is available

### How to Reproduce?

Check Dockerfile.jvm and Dockerfile.native from https://code.quarkus.io/?S=io.quarkus.platform%3A3.2 sample app

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.2 / main

**Comment by cescoffier** [comment]
This needs to be applied to Quarkus images too. I didn't have the time because of graalvm 23
