### ISSUE TITLE
Spring annotation project creation

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#3437]
As mentioned [here](https://github.com/quarkusio/quarkus/pull/3432#pullrequestreview-271504287), it would be good to have Quarkus ` io.quarkus:quarkus-maven-plugin:create` generate a Spring Controller instead of a JAX-RS Resource when `spring-web` dependency is used.

**Comment by geoand** [comment]
@aureamunoz assigning to you :)

**Comment by aureamunoz** [comment]
I'm not able to assign to me

**Comment by geoand** [comment]
Yes I know, don't worry though, consider it assigned :)

**Comment by geoand** [comment]
This has already been done, closing
