### ISSUE TITLE
swagger-ui endpoint is traced by OTel

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#34376]
### Describe the bug

By default, `quarkus-opentelemetry` does not trace non-application endpoints, unless this is explicitly enabled (`quarkus.otel.traces.suppress-non-application-uris=false`)

`quarkus-smallrye-openapi` has 2 non-application endpoints:
- `/q/openapi`
- `/q/swagger-ui/`

While `/q/openapi` is by default not traced, `/q/swagger-ui/` is.

Btw. `/q/swagger-ui/` is only included in dev mode, unless stated otherwise (`quarkus.swagger-ui.always-include=true`), so maybe the tracing is intentional?

### Expected behavior

No tracing of `/q/swagger-ui/` endpoint by default.

### Actual behavior

`/q/swagger-ui/` endpoint is traced regardless of `quarkus.otel.traces.suppress-non-application-uris`, just like a regular application endpoint.

### How to Reproduce?

```
git clone https://github.com/jsmrcka/reproducers.git -b swagger-ui-otel
mvn -f ./reproducers clean verify
```

### Output of `uname -a` or `ver`

Linux 6.2.15-200.fc37.x86_64

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### Quarkus version or git rev

3.1.2.Final, 999-SNAPSHOT 2023-06-27

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.8

**Comment by geoand** [comment]
I'll take a look

**Comment by geoand** [comment]
#34510 should take care of it
