### ISSUE TITLE
Bad command in documentation

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#34385]
### Describe the bug

https://quarkus.io/guides/building-native-image#profiles says `quarkus-profile=test`. It should be `quarkus.profile=test`.

### Expected behavior

Build and run using `test` profile

### Actual behavior

project is build with `prod` prodile

`2023-06-27 22:30:29,116 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile 'prod' used to build the native image is different from the runtime profile 'test'. This may lead to unexpected results.`

### How to Reproduce?

1. Execute `mvnw verify -Pnative -Dquarkus-profile=test -Dquarkus.test.native-image-profile=test`
2. Check that log says `2023-06-27 22:30:29,116 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile 'prod' used to build the native image is different from the runtime profile 'test'. This may lead to unexpected results.`

### Output of `java -version`

 GraalVM 22.3.2 Java 17 CE (Java Version 17.0.7+7-jvmci-22.3-b18)

### GraalVM version (if different from Java)

 GraalVM 22.3.2

### Quarkus version or git rev

2.16.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

### Additional information

Related: https://github.com/quarkusio/quarkus/issues/25519

**Comment by geoand** [comment]
@gian1200 thanks for reporting!

Are you interested in providing a doc fix?

**Comment by MichalMaler** [comment]
> @gian1200 thanks for reporting!
> 
> Are you interested in providing a doc fix?

@geoand 
Hello there. I can do it. IT should be a quick one.

**Comment by geoand** [comment]
@MichalMaler Hey. I would say let's give @gian1200 a chance to fix the issue he reported if he so likes :)

**Comment by gian1200** [comment]
Done (I think). Thanks for the opportunity!

Just a quick question, is there a separate process to backport the fix to old branches (at least the ones available in the webpage)?
![image](https://github.com/quarkusio/quarkus/assets/405347/ce5bbb56-b8bf-43d6-a5a9-8091ea7782d3)

**Comment by geoand** [comment]
Thanks.

We do the backports manually
