### ISSUE TITLE
Provide possibility to run ./mvnw install with uber-jar creation, without renaming the uber-jar artefact

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#34388]
## Setup
A lot of our containerfiles do something like:

```dockerfile
...
FROM ...
...
COPY ... target/*runner.jar application.jar
...
```
Hence, our containerfiles rely on the fact that the jar to copy ends on `runner.jar`.

When we build an uber jar, a `${project.artifactId}-${project.version}.jar.original` is created, representing the jar before "uberfication".

## Problem
When we upgrade the `maven-install-plugin` to a version `>= 3.0.0`, the plugin execution fails with the following error:

```bash
$ ./mvnw clean install
...
[INFO] --- maven-install-plugin:3.1.1:install (default-install) @ install-fails ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.434 s
[INFO] Finished at: 2023-06-28T16:21:09+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.1:install (default-install) on project install-fails: The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'. -> [Help 1]
```

We can prevent this problem by removing the `-runner` suffix from the uber-jar (`./mvnw ... --define quarkus.package.add-runner-suffix=false ...`), but this would break our container builds.

## Proposal
Provide an option to remove the `.original`-suffix from the original jar, or register the `runner.jar` as main file.

## Story
**AS** a developer who relies on the `runner.jar`-suffix to build containers and wants to use `maven-install-plugin` inversion `>=3.0.0`
**WHEN** I run `./mvnw install` to build my application, a corresponding container and install the application
**THEN** I want the process to succeed.

## Acceptance criteria
1. The current containerfile still builds
2. `./mvnw clean install` succeeds

## Companion-repository and Acceptance test
Companion-repository: https://github.com/turing85/quarkus-uberjar-install
Acceptance test: run `./mvnw --define build-container clean install` in the companion repository

## Workarounds
1. Change th containerfiles, do not rely on the `runner.jar`-suffix: This might be easier said than done. Especially when other jars without the `runner.jar` suffix are created (e.g. `jar` containing the source code).
2. Add a .dockerignore to exclude other jars like source jars: this is possible, but time-consuming since we have a lot of applications, relying on the same containerfile. We would need to add the corresponding `.dockerignore` to each of them
4. Use another plugin (e.g. `maven-antrun-plugin`) to copy the `.jar.original` to just `.jar`: this is easy to implement (see [profile `fix-with-ant-plugin` in the `pom.xml` of the companion-repository](https://github.com/turing85/quarkus-uberjar-install/blob/main/pom.xml#L111)), but error-prone. We have to explicitly call the `install`-plugin in the profile, and it must be called before `maven-antrun-plugin` is called, i.e. we rely on the order of the plugins in the `pom.xml`.

**Comment by aloubyansky** [comment]
You should be able to use  `skipOriginalJarRename` parameter of the `quarkus:build` goal for that.

**Comment by geoand** [comment]
Thanks for the info @aloubyansky! I was aware of that flag. 

@turing85 if that works for you, I would suggest closing the issue.

**Comment by aloubyansky** [comment]
That parameter has been deprecated for quite some time now. But there is no actual plan to remove it either at this point because this renaming story is awkward and it seems like we haven't cleaned it up entirely.

**Comment by turing85** [comment]
> You should be able to use `skipOriginalJarRename` parameter of the `quarkus:build` goal for that.

Okay, good to know. can we then un-deprecate this feature?

**Comment by aloubyansky** [comment]
@turing85 the PR above should fix it for you

**Comment by turing85** [comment]
@aloubyansky I know that this is now reaching.... but can we register the *actual* artifact (i.e. the `-runner.jar`) as main artifact?

**Comment by aloubyansky** [comment]
You really want all the options :)
If you want to completely abandon the original JAR, I would say use `quarkus.package.add-runner-suffix=false`. To which you'll probably say that then you'd have to adjust all your container files?
I always thought the rename was a bad idea, it keep haunting us for years.

**Comment by turing85** [comment]
@aloubyansky don't tell me ^^" I am on the receiving end of this as well.

**Comment by aloubyansky** [comment]
The reason for rename, afair, was to simply end up with a single file with `.jar` suffix in the target directory to make it easy for tools looking up for a JAR in that directory. The way it was implemented was not the best.

**Comment by turing85** [comment]
Well... my stance on this should be clear :slightly_smiling_face:

**Comment by aloubyansky** [comment]
Would the above PR be it @turing85?

**Comment by turing85** [comment]
Okay, that's awesome @aloubyansky ! Thanks a lot! :smile: 
Just for the record: I do not expect you to do all the work; If you give me the go-ahead, I can implement such trivial things.
