### ISSUE TITLE
Spring Data API Extension Property Expressions with List not working

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#34395]
### Describe the bug

The method  `long countParentsByChildren_Name(String name)` throws `java.lang.IllegalStateException: Entity class java.util.List referenced by at.atc.database.entities.Parent.children was not part of the Quarkus index. Offending method is 'countParentsByChildren_Name' of repository 'at.atc.database.repository.ParentBaseRepository'.`

Same method works fine with Spring.

### How to Reproduce?

[reproducerJPAQueryMethod.zip](https://github.com/quarkusio/quarkus/files/11898682/reproducerJPAQueryMethod.zip)

**Comment by geoand** [comment]
Very interesting. Any chance you can attach the working Spring version?

Thanks

**Comment by Michael-AT-Corporation** [comment]
The function is in `ParentBaseRepository`
[SpringBootJpaTestQueryMethod.zip](https://github.com/quarkusio/quarkus/files/11903866/SpringBootJpaTestQueryMethod.zip)

**Comment by geoand** [comment]
Is there a docker command you use to launch MySQL?

**Comment by Michael-AT-Corporation** [comment]
Unfortunately not. I have one installed and added the values to the DB with MySqlWorkbench.

**Comment by geoand** [comment]
In that case, would you mind putting a breakpoint in `org.hibernate.internal.AbstractSharedSessionContract#createQuery` and reporting the value of `queryString` for the call to `ParentRepository#countParentsByChildren_Name`?

Thanks

**Comment by Michael-AT-Corporation** [comment]
Either i am doing something wrong or it is not getting called. The only createQuery Method that is being called after i called `countParentsByChildren_Name` is `<T> QueryImplementor<T> createQuery(CriteriaQuery<T> criteriaQuery)`

**Comment by geoand** [comment]
I can't really debug, but what I am looking for is what JQPL Query Spring Data JPA is generating. If you can come up with it in another way, that works for me.

**Comment by Michael-AT-Corporation** [comment]
Is this what you are looking for? 
select count(p1_0.id) from parent p1_0 left join (parent_children c1_0 join child c1_1 on c1_1.id=c1_0.children_id) on p1_0.id=c1_0.parent_id where c1_1.name=?

**Comment by geoand** [comment]
Thats looks like the actual SQL query, not the JPQL one

**Comment by Michael-AT-Corporation** [comment]
I couldn't find a way to get the JPQL string.
Would you only need a docker command to launch an MySQL? Or do you need something else to be able to debug the Spring version?

**Comment by geoand** [comment]
Yeah, if I have the proper `docker run` command I can likely find the JPQL query string myself

**Comment by geoand** [comment]
Thanks. It seems like Spring is using Criteria queries here. 

In any case this will take more work to support properly.

**Comment by geoand** [comment]
Good question... I kind of doubt it will be something I have time for for 3.3

**Comment by Michael-AT-Corporation** [comment]
Just wanted to ask for a quick update when you might have time for this.

**Comment by geoand** [comment]
I have been working full time on some high priority stuff, so issues like this have fallen to the back of the queue

**Comment by Michael-AT-Corporation** [comment]
How long is the queue rigth now? 😀
One quick question:
Is it possible to add the dependency 
```
<dependency>
     <groupId>org.springframework.data</groupId>
     <artifactId>spring-data-jpa</artifactId>
     <version>3.2.5</version>
</dependency>
```
and use for example the class `org.springframework.data.jpa.repository.query.QueryUtils` (which is excluded in the jar that quarkus provides) without getting `java.lang.ClassNotFoundException` at runtime when using this class 
Thanks for your time in advance.

**Comment by geoand** [comment]
Maybe @aureamunoz can look into it

**Comment by Michael-AT-Corporation** [comment]
Without the added dependency the class `org.springframework.data.jpa.repository.query.QueryUtils` is not present.
Because `quarkus-spring-data-jpa` only includes the classes that are rquired for it to work.
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-spring-data-jpa</artifactId>
        </dependency>
```
But when building a uber-jar or running in dev mode the class always is removed. I just don't know if quarkus is removing it or something else causes it to disappear.

**Comment by geoand** [comment]
Let's see what @aureamunoz says when she back and has time to look into it

**Comment by aureamunoz** [comment]
I'm back, I will look at this tomorrow.

**Comment by aureamunoz** [comment]
Hi,

I've reviewed the issue, and I'm currently working on a fix for the `long countParentsByChildren_Name(String name)` problem. If all goes well, I should be able to push the changes by tomorrow.

However, I'm a bit unclear on how [this comment](https://github.com/quarkusio/quarkus/issues/34395#issuecomment-2261386269) relates to the original issue. Is it a separate question? Could you clarify what you need exactly? Are you encountering a `java.lang.ClassNotFoundException` due to `org.springframework.data.jpa.repository.query.QueryUtils`? I'm having trouble connecting both points.

Thanks!

**Comment by aureamunoz** [comment]
Ah ah, ok, much clearer now. Yes, you're right. Only the classes present in our `quarkus-spring-*` dependencies are known by the application. We could add the `org.springframework.data.jpa.repository.query.QueryUtils`and avoid the ClassNotFoundException but be aware that there is no Spring Context running a no Spring class is actually used under the hood so not sure what you want to do work.

**Comment by Michael-AT-Corporation** [comment]
Thanks for the clarification.
I try to make a criteria query with `orderBy` and therefore i wanted to use `QueryUtils.toOrders` to convert the `Sort` of the spring `Pageable` to  `List<Order>` for the `orderBy`.

**Comment by Michael-AT-Corporation** [comment]
@aureamunoz 
I just tried my reproducer with 3.15.1. It is not working:
```
2024-10-18 18:28:12,888 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/rest/parents/1 failed, error id: d9553116-a59c-46b7-aea7-50a8de882ad2-5: org.hibernate.query.PathException: Plural path 'at.atc.database.entities.Parent(2).children' refers to a collection and so element attribute 'name' may not be referenced directly (use element() function)
	at org.hibernate.query.sqm.tree.domain.SqmPluralValuedSimplePath.resolvePathPart(SqmPluralValuedSimplePath.java:102)
	at org.hibernate.query.hql.internal.DomainPathPart.resolvePathPart(DomainPathPart.java:42)
	at org.hibernate.query.hql.internal.BasicDotIdentifierConsumer.consumeIdentifier(BasicDotIdentifierConsumer.java:92)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimplePath(SemanticQueryBuilder.java:5464)
        ...
```
Is this a problem on my end?

**Comment by Michael-AT-Corporation** [comment]
Sure here is the updated reproducer:
[reproducerJPAListPropertyExpression.zip](https://github.com/user-attachments/files/17463190/reproducerJPAListPropertyExpression.zip)
Just run `mvn clean test` and the test will fail
Or start the application with `mvn clean compile quarkus:dev` and call the endpoint `http://localhost:41000/test/rest/parents/1`

**Comment by aureamunoz** [comment]
Hi!
I've been looking to this today and the problem is not the same. Basically quarkus is not automatically generating correctly a method to count entities in a one-to-many relationship with a specific attribute and I need to see why.

I will create another issue and track it there.

**Comment by aureamunoz** [comment]
Let's follow in the https://github.com/quarkusio/quarkus/issues/44026
