### ISSUE TITLE
Deprecation warning for quarkus generated tasks in Gradle 9.0

### ISSUE THREAD

**Issue by jcjolley** [quarkusio/quarkus#34390]
### Discussed in https://github.com/quarkusio/quarkus/discussions/33487

<div type='discussions-op-text'>

<sup>Originally posted by **devr52** May 19, 2023</sup>
Tasks nativeTestRuntimeOnly, nativeTestImplementation, integrationTestRuntimeOnly, integrationTestImplementation are affected. 
In relation to: 
- https://github.com/quarkusio/quarkus/issues/23528
- https://github.com/quarkusio/quarkus/issues/22035

Will this affect the way quarkus do thing in relation to these tasks created by the quarkus specific sourcesets?? 

> The configuration integrationTestImplementation was created explicitly. This configuration name is reserved for creation by Gradle. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Do not create a configuration with this name. Consult the upgrading guide for further information: https://docs.gradle.org/8.1.1/userguide/upgrading_version_8.html#configurations_allowed_usage
</div>

**Comment by mschorsch** [comment]
https://github.com/quarkusio/quarkus/pull/38249

**Comment by aloubyansky** [comment]
This should be fixed by https://github.com/quarkusio/quarkus/pull/38249, thanks for creating the issue.
