### ISSUE TITLE
OIDC adapter should reuse Quarkus CORS filter

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#3441]
**Description**
Right now there are 2 CORS filters that can be used, if KC is active - the KC one has to be enabled, if not - the Quarkus one. Ideally the users should be able to use the Quarkus one with KC as well
**Implementation ideas**
Feedback from the KC experts, @pedroigor , @sebastienblanc will be welcome :-). Perhaps the KC extension can detect the Quarkus CORS capabiity and depend on it...

**Comment by sberyozkin** [comment]
@stuartwdouglas @pedroigor @cescoffier, @pmlopes FYI.
Now that the Vertx adapter is used the Quarkus CORS filter should work alongside it, while as suggested by Clement, continue to be independent.

**Comment by stuartwdouglas** [comment]
Do we need to do anything here? We already have a CORS filter, does keycloak need to be able to configure it or can this be closed.

**Comment by sberyozkin** [comment]
@stuartwdouglas I guess we just need to check Vertx adapter itself does not try to do its own CORS and that it does not start the token verification before a preflight request, @pmlopes, do you reckon some tuning is needed at the Vertx side for it ?

**Comment by sberyozkin** [comment]
@stuartwdouglas I'll update the `integration-tests/oidc` after #4376 is done with a simple pre-flight call to verify the Quarkus CORS filter can work alongside it

**Comment by pmlopes** [comment]
Vertx auth will not do any cors checks.
Cors is handled by the cors handler.

So it gives you flexibility to decide how it should behave. So if keycloack does it before nothing is needed on vertx side. Otherwise just add the cors handler before.

**Comment by sberyozkin** [comment]
@pmlopes thanks for the update

**Comment by sberyozkin** [comment]
Hi All, have to confirm and update the docs for 0.24.0 since the current Keycloak CORS doc is invalid now.

**Comment by sberyozkin** [comment]
It is looking good, will follow with the PR soon
