### ISSUE TITLE
Redis StreamCommands should provide xpending command

### ISSUE THREAD

**Issue by RomainWilbert** [quarkusio/quarkus#34411]
### Description

Today the only way to request pending messages is to use low level RedisAPI.

**Comment by cescoffier** [comment]
What's your use case? I would like to understand how you use it.

`xpending` is a complex command accepting different forms of arguments (so quite hard to map to java).

**Comment by RomainWilbert** [comment]
Mainly it is to re-run messages that failed while processing

Le jeu. 29 juin 2023, 14:50, Clement Escoffier ***@***.***> a
écrit :

**Comment by cescoffier** [comment]
Could you give me the low level command to run and how you interpret the result?

**Comment by RomainWilbert** [comment]
This is my use case "re-run messages that failed while processing" :
- xautoclaim to get pending stream entries (delivered once but not acked)
- xpending the get the message content
- re-run the message calling the listener manually
- if processing is OK, message is acked and removed from stream

**Comment by cescoffier** [comment]
@RomainWilbert Here you go: https://github.com/quarkusio/quarkus/pull/34519
