### ISSUE TITLE
Project fails to compile whenever microprofile-config-api is included on a submodule

### ISSUE THREAD

**Issue by i96751414** [quarkusio/quarkus#34421]
### Describe the bug

A maven project is failing to compile whenever microprofile-config-api is included on a submodule, however it doesn't fail if it is included on its root, only.

I've created a test project to demonstrate this.
[getting-started.zip](https://github.com/quarkusio/quarkus/files/11908609/getting-started.zip)

### Expected behavior

The project should compile.

### Actual behavior

Project fails to compile with the following error:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.1.2.Final:build (default) on project untitled: Failed to build quarkus application: SRCFG00039: The config property quarkus.test.hang-detection-timeout with the config value "10m" threw an Exception whilst being converted SRCFG00020: Failed to convert value with static method: InvocationTargetException: Text cannot be parsed to a Duration -> [Help 1]
```

**Comment by geoand** [comment]
This is a really weirdly configured Maven project so I personally don't consider it an issue, but I'll let @radcortez decide.

**Comment by i96751414** [comment]
This was made just to provide and example. I am having this issue in a real project.

**Comment by i96751414** [comment]
Just so its clear what I've made to reproduce this:
1. Create an empty project
    ```
    mvn io.quarkus.platform:quarkus-maven-plugin:3.1.2.Final:create \
        -DprojectGroupId=org.acme \
        -DprojectArtifactId=getting-started
    ```
2. Add a module to the project
3. Add microprofile-config-api to the module
    ```
    <dependency>
        <groupId>org.eclipse.microprofile.config</groupId>
        <artifactId>microprofile-config-api</artifactId>
    </dependency>
    ```
4. Compile.

**Comment by radcortez** [comment]
This is because you are applying the Quarkus plugin to a non-Quarkus module. The Quarkus plugin expects at least the core dependency in the project. You will get the same error with an empty project (without dependencies). The issue is not related to the microprofile-config-api.

My recommendation is to only add the plugin to the modules that are going to contain Quarkus applications.

**Comment by radcortez** [comment]
No worries :)
