### ISSUE TITLE
Gradle fails with missing dependency declaration

### ISSUE THREAD

**Issue by pwlan** [quarkusio/quarkus#34430]
### Describe the bug

Hi,

with the new Gradle version 8.1.1 and Quarkus 3 i get a lot of gradle tasks failing the message "...without declaring an explicit or implicit dependency..." (more details below). 
This seems to be something new with gradle. I will try to create a reproducer later. I just wanted to give early feedback in case this was a know issue.

### Expected behavior

Gradle build to run without failure

### Actual behavior

Gradle fails with the following error: 
```
Gradle detected a problem with the following location: **********
    
    Reason: Task ':graphql-quarkus-starter:quarkusGenerateCodeTests' uses this output of task ':graphql-quarkus-starter:jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':graphql-quarkus-starter:jandex' as an input of ':graphql-quarkus-starter:quarkusGenerateCodeTests'.
      2. Declare an explicit dependency on ':graphql-quarkus-starter:jandex' from ':graphql-quarkus-starter:quarkusGenerateCodeTests' using Task#dependsOn.
      3. Declare an explicit dependency on ':graphql-quarkus-starter:jandex' from ':graphql-quarkus-starter:quarkusGenerateCodeTests' using Task#mustRunAfter.
```

### Output of `uname -a` or `ver`

Darwin T000c1a990 22.5.0 Darwin Kernel Version

### Output of `java -version`

openjdk version "19" 2022-09-20

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.1.1

**Comment by pwlan** [comment]
Ok, i figured out that this is an issue on our side. 
I did have to add 

```
  project.tasks.named("compileKotlin") {
            mustRunAfter("compileQuarkusGeneratedSourcesJava")
   }
        project.tasks.named("runKtlintCheckOverMainSourceSet") {
            mustRunAfter("compileQuarkusGeneratedSourcesJava")
        }
```

but i feel this is less of a Quarkus issue, maybe?

Feel free to close the issue.

**Comment by micheljung** [comment]
Similar thing here

        Reason: Task ':app:quarkusDependenciesBuild' uses this output of task ':app:jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Fixed it with:

```kotlin

// https://github.com/quarkusio/quarkus/issues/34430
if (gradle.taskGraph.hasTask("jandex")) {
  tasks.quarkusDependenciesBuild {
    dependsOn(tasks.named("jandex"))
  }
}
```

In my case, Quarkus is applied in a convention plugin, hence the condition.

**Comment by gsmet** [comment]
Let's close, thanks for the feedback and sorry for missing it :).

**Comment by pwlan** [comment]
@gsmet thanks!

On  completly unrelated matter, my team and I are currently working on a new AI Framework for Kotlin and the JVM stack. We are using it to build one of Germanys biggest LLM powered ChatBots and have taken it opensource. 
I am currently looking at ways to make it a first class citizen on quarkus. So if you have any ideas, it would be much appreciated. Here is the link https://lmos-ai.github.io/arc/.

**Comment by gsmet** [comment]
@geoand @cescoffier @jmartisk  that might be of interest to you ^

**Comment by geoand** [comment]
🙏
