### ISSUE TITLE
CDI tries to inject variables passed to lambda function

### ISSUE THREAD

**Issue by gjeraj** [quarkusio/quarkus#3443]
The problem lies with the `quarkus-arc` extension where it tries to inject parameters passed to lambda expression. To illustrate this I've created a simple project https://github.com/gjeraj/quarkus-cdi-bug

```
@ApplicationScoped
public class EventHandler {
	@Inject
	public LambdaHandler lambdaHandler;

	public void event(@Observes String event) {
		// Fails
		lambdaHandler.process("First", (first, second) -> event + " " + second);
	}

	public void direct(String event) {
		// Works
		lambdaHandler.process("First", (first, second) -> event + " " + second);
	}
}
```
As you can see the event observer function fails to build with the following error:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.20.0:build (default) on project quark: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems:
[ERROR] [1] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
[ERROR]         - java member: com.test.EventHandler#lambda$event$0()
[ERROR]         - declared on io.quarkus.arc.processor.ObserverInfo@169f2f1b
[ERROR] [2] Unsatisfied dependency for type java.lang.String and qualifiers [@Default]
[ERROR]         - java member: com.test.EventHandler#lambda$event$0()
[ERROR]         - declared on io.quarkus.arc.processor.ObserverInfo@169f2f1b
```
Whats interesting if `event` parameter is first assigned to another variable, it also works:

```
	public void event(@Observes String event) {
		// Works
                String working = event;
		lambdaHandler.process("First", (first, second) -> working + " " + second);
	}
```

If the line is commented out, the second method `direct` builds just fine.

Using 
- `quarkus <= 0.20.0` 
- `maven 3.6.1 `

**Comment by gwenneg** [comment]
Hi @gjeraj and thanks for reporting this.

@mkouba, @manovotn: Could you take a look at this please?

**Comment by mkouba** [comment]
Hi @gjeraj, I've just tried your reproducer and it builds and runs just fine. What JDK version are you using?

**Comment by gjeraj** [comment]
Hi, I was using JDK 8, more precisely jdk1.8.0_191

**Comment by mkouba** [comment]
Interesting. Is it Oracle JDK, OpenJDK, or something else? I've also tried maven 3.6.1 and `mvn clean package` => BUILD SUCCESS.

**Comment by gjeraj** [comment]
Weird, I've just tried this on another machine and it also works fine, same maven and java. Could be some weird incompatibility with something. I'll try to investigate this tomorrow.

**Comment by gjeraj** [comment]
I figured it out, the problem is the old java version. Apparently `jdk1.8.0_131` has this issue. So if anyone else is experiencing this, update java :)

**Comment by mkouba** [comment]
Oh yes, I do remember a similar issue in Weld: http://weld.cdi-spec.org/news/2015/09/15/jdk-8u60-problem/ and even though it's a JDK issue I believe we should ignore the synthetic members as well. I'll send a PR shortly.
