### ISSUE TITLE
QuarkusApplication Simple JavaDoc

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus#34463]
### Description

There will be times that "new" developers in using Quarkus will be implementing the FunctionalInterface, `QuarkusApplication`. Seeing in the Quarkus Guides, when you put logic in the Main class, you should implement this interface.

Proposing to have just a simple class level documentation on what is `QuarkusApplication`. Since it is also a public visibility class exported API to the users.

### Implementation ideas

Add a class-level javadoc for `QuarkusApplication` interface.

Will open a PR on this one.

**Comment by geoand** [comment]
Sounds reasonable.

> Will open a PR on this one.

👍🏼
