### ISSUE TITLE
gRPC client configuration bug Quarkus 2.16.7 Final

### ISSUE THREAD

**Issue by AlekseyMay** [quarkusio/quarkus#34475]
### Describe the bug

grpc application property idle-timeout is not correcly mapped in configuration Channels class
![image](https://github.com/quarkusio/quarkus/assets/60628480/f513a26a-2591-4cac-98c6-76966fc31098)
io.quarkus.grpc.runtime.supports.Channels
![image](https://github.com/quarkusio/quarkus/assets/60628480/ea1bf4ec-7969-4cb2-bc6c-b4424f3c5d86)

It is fixed in Quarkus 3+. But that will be great to fix it in old Quarkus version.

### Output of `java -version`

17

### Quarkus version or git rev

2.16.7 Final

**Comment by geoand** [comment]
This has been fixed by https://github.com/quarkusio/quarkus/pull/32390.

I marked that for backport for whenever we do a new 2.16 release

**Comment by geoand** [comment]
Ah my bad, we had not added the proper label - I did now.
