### ISSUE TITLE
Cleanup on live reload also removes generated classes

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#3448]
**Describe the bug**
Generated classes are removed during live reload.

**Expected behavior**
Generated classes are not deleted.

**To Reproduce**
1. `git clone https://github.com/antoniomacri/quarkus-rocker-class-cleanup.git`
2. `mvn install`
3. `ll target/classes/views` ->  `HostingPage.class`
4. `mvn quarkus:dev` (+ `mvn install` + F5 on `http://localhost:8080/`)
5. `ll target/classes/views` ->  `HostingPage.class` deleted

**Environment:**
 - Output of `java -version`: 1.8
 - Quarkus version or git rev: 0.20.0

**Comment by masini** [comment]
Hi, we are using Rocker as a compile time replacement for some old JSPs, with this issue all generated Rocker classes are deleted during development.

As a quick fix we copy/pasted them, does exist a switch to disable this feature until is fixed ?

**Comment by vivynz** [comment]
An additional workaround is to launch “mvn compile quarkus:dev” instead of “quarkus:dev” only

**Comment by gsmet** [comment]
@machi1990 could you take a look? It looks related to the work you did on removing classes?

**Comment by machi1990** [comment]
@gsmet I'll take a look.

**Comment by machi1990** [comment]
@antoniomacri @masini thanks for reporting and I was able to reproduce the bug thanks to your reproducer. We have a fix in place in #3613 (could you confirm ? :-) ), but till that is merged launching the dev mode command as @vivynz suggested `mvn compile quarkus:dev` is a good workaround.
