### ISSUE TITLE
New in Platform 3.2.0.Final: Quarkus CXF

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#34512]
[Quarkus CXF](https://quarkiverse.io/quarkiverse-docs/quarkus-cxf/dev/index.html) got a part of the previous Quarkus Platform release 3.1.0.Final already, but we forgot to announce it at that time (sorry!). Quarkus CXF ports [Apache CXF](https://cxf.apache.org/) to Quarkus. It can be used for writing SOAP [WebServices](https://quarkiverse.io/quarkiverse-docs/quarkus-cxf/dev/user-guide/first-soap-web-service.html) and [Clients](https://quarkiverse.io/quarkiverse-docs/quarkus-cxf/dev/user-guide/first-soap-client.html). You can now create project stubs via [code.quarkus.io](https://code.quarkus.io/?e=io.quarkiverse.cxf%3Aquarkus-cxf&extension-search=origin:platform%20quarkus%20cxf).

With Quarkus Platform 3.2.0.Final, the status [Quarkus CXF Metrics Feature](https://quarkiverse.io/quarkiverse-docs/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-features-metrics.html) changed from experimental to stable. The extension is now properly tested both in JVM and native modes.

**Comment by gsmet** [comment]
Incorporated in the blog post.
