### ISSUE TITLE
CSRF Reactive detect CSRF token from header "X-CSRF-Token" (currently only form param)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#34513]
### Describe the bug

Currently quarkus-csrf-reactive is only looking at the form param to get the CSRF Token but it could be in the request header `X-CSRF-Token` or other.

**Comment by ia3andy** [comment]
Updated

**Comment by sberyozkin** [comment]
@ia3andy Thanks for linking to the Renarde issue - so do I understand it correctly you'd like to simplify the creation of HTMX for Renarde users, while still securing Form posts with the CSRF ?

I'm not sure we can do it, the custom header solution is only there to add CSRF protection to non Form post requests, when no `form` tag is used. Even the same cheatsheet section I linked to says:
```
If you use <form> tags anywhere in your client, you will still need to protect them with alternate approaches described in this document such as tokens.
```

**Comment by sberyozkin** [comment]
Hey @ia3andy Let me clarify - I don't mind much adding a `header` configuration property, which, if configured, will have to be available in the current request - but we can't skip the double cookie submit check if it is a form POST request.

Do you have a use case in mind where no form tag is used ? Indeed, for such a use case, it looks like
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#custom-request-headers

can help - but I have to admit I'm not sure I understand the follow up section there related to supporting this custom header check in a setup requiring the CORS check - what does allowing an access to credentials like cookies and authorization headers from JavaScript have to do with this JavaScript setting a custom header.

So, if you have the use case in mind where no form tag is used, then lets workout the mechanics of how it will work in a cross-origin setup, and then we should be able to add the header property and check the request

Thanks

**Comment by ia3andy** [comment]
@sberyozkin the idea is that this header is used with the token as value instead of the form field, the resulting check is the same AFAIK (just if the header is present and not the param it uses it).

**Comment by ia3andy** [comment]
It seems it's what Django does:
https://django-htmx.readthedocs.io/en/latest/tips.html

**Comment by sberyozkin** [comment]
@ia3andy Thanks. I'd like to understand the consequences of making a token available as an HTMX body headers attribute as opposed to a hidden form value, I'll check, if you can find some good analysis, please share a link, cheers

**Comment by FroMage** [comment]
Angular reads a CSRF token from a cookie, and sets it back as a header: https://angular.io/guide/http-security-xsrf-protection

**Comment by sberyozkin** [comment]
@FroMage Thanks, so to make it work in a cross-origin setup, CORS filter should allow accessing the credentials (CSRF cookie in this case) with `Access-Control-Allow-Credentials=true`, right ?

**Comment by sberyozkin** [comment]
I suppose we can document this requirement

**Comment by ia3andy** [comment]
> @FroMage Thanks, so to make it work in a cross-origin setup, CORS filter should allow accessing the credentials (CSRF cookie in this case) with `Access-Control-Allow-Credentials=true`, https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#custom-headers-and-cors, right ?

Yeah it seems so, I am just not sure of " (CSRF cookie in this case) " I think it's the custom header that should be allowed `X-CSRF-Token` (and maybe also the cookie)

**Comment by sberyozkin** [comment]
@ia3andy It looks like the header solution depends on HTMX and other frameworks be able to read the CSRF cookie and inject its value as a header value with HTMX post etc, so
```
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
   ...
</body>
```

means that there should be a cookie named `csrf_token` and HTMX will read it and provide the X-CSRFToken header, so CSRFFeature will then compare this header against the cookie value. But as opposed to the hidden form field, CORS filter would have to allow an access to the credentials and be specific about Origins, `*` won't work - we can doc it.

I'll open a draft PR

**Comment by ia3andy** [comment]
@sberyozkin so.. 
- from a angular perspective, yes the cookie will be read from javascript I guess (and possible CORS). 
- from an htmx perpective, this is server side rendering so there is no CORS and the token is available through the template so no problem (this is what I need currently)

**Comment by sberyozkin** [comment]
@ia3andy Interesting,

>from a angular perspective (or any SPA), yes the cookie will be read from javascript I guess (and possible CORS).

Right, yeah, this is Case 1 which I can see how CSRF feature can handle.

>from an htmx perpective, this is server side rendering so there is no CORS and the token is available through the template so no problem (this is what I need currently)

Cool, so the CORS access to the credentials would be unnecessary, I think it is all clear now

**Comment by sberyozkin** [comment]
@ia3andy It would still be necessary to have restricted Origins, for HTMX, it would work even with the wildcard, since no access to cookies would be required, but since the header value is server side rendered, having the token inlined in the produced HTML, without the CORS Origin restriction, may allow accessing this token to some scripts

**Comment by ia3andy** [comment]
@sberyozkin well in this case it is the exact same with a hidden form value (currently used by Renarde)

**Comment by sberyozkin** [comment]
@ia3andy Good point, I'll update the docs.

**Comment by sberyozkin** [comment]
I started typing some code
