### ISSUE TITLE
Quarkus Integration Tests Problem

### ISSUE THREAD

**Issue by MehmetZorlu07** [quarkusio/quarkus#34515]
Hi,

We have a project that has two integration classes, Test.java and IT.java. Test.java has the annotation @QuarkusMainTest, IT.java has the annotation @QuarkusMainIntegrationTest above the class declarations and IT.java extends Test.java class. 

We have implemented a new feature where the program checks if a file to be generated already exists in the target folder and acts accordingly. We have written some integration tests where files are generated, the feature is used to check their existence and at the end of the integration tests all files and folders get wiped out. 

The problem we have encountered is that when the integration tests run, all tests in Test.java pass followed by some tests failing in IT.java. This is because IT.java somehow first runs the parent Test.java tests again and then runs its own tests before wiping, causing unwanted files to be generated and giving wrong results. 

The current solution we have is removing the inheritance between the two classes and copy all the tests from Test.java to IT.java. By doing this we do not have the problem anymore but now every integration test needs to be duplicated in the classes.

Are there any alternative solutions to this?

(We tried following this guidelines from the original documentation: https://quarkus.io/guides/getting-started-testing#quarkus-integration-test)

**Comment by geoand** [comment]
What you are describing is standard JUnit behavior.

One way around this is what we do [here](https://github.com/quarkusio/quarkus/blob/03b7ae4f8b90d732d8d35879d266a4081d9a91f3/integration-tests/maven/src/test/java/io/quarkus/maven/it/DisableForNative.java) [here](https://github.com/quarkusio/quarkus/blob/df7445d218cda756cdfd67ad350bec2b5d83a1e4/integration-tests/maven/src/test/java/io/quarkus/maven/it/JarRunnerIT.java#L51) and [here](https://github.com/quarkusio/quarkus/blob/574d5094c927056b0b57c5fabf141ef113974c1c/integration-tests/maven/pom.xml#L136) but your mileage may varu.
