### ISSUE TITLE
How to use web.xml with Quarkus?

### ISSUE THREAD

**Issue by Curious-Bear** [quarkusio/quarkus#3457]
Using web.xml as a document descriptor is not explained in the documentation

**Comment by geoand** [comment]
I haven't tried it personally, but I think if you add `web.xml` in `src/main/resources/META-INF` it should be picked up. Can you give it a shot?

**Comment by Curious-Bear** [comment]
Thank you for the reply. That solution worked. I needed to implement my Java web application that has a web.xml configuration file using Quarkus.

**Comment by machi1990** [comment]
@Curious-Bear glad to hear that the solution worked for you. It is not documented, would like to contribute it by updating [undertow guide](https://github.com/quarkusio/quarkus/blob/581b5118acc83cdb82359e5df775577559db48bd/docs/src/main/asciidoc/undertow-reference.adoc)?

**Comment by Curious-Bear** [comment]
Sure
