### ISSUE TITLE
Invalid handling of path segments in URLs by "quarkus-resteasy-reactive"

### ISSUE THREAD

**Issue by tatu-at-datastax** [quarkusio/quarkus#34586]
### Describe the bug

It looks like path splitting by "quarkus-resteasy-reactive" is slightly broken ("quarkus-resteasy" works), for following case (explained earlier at SO https://stackoverflow.com/questions/76632028/discrepancy-between-reactive-and-non-reactive-quarkus-jax-rs-endpoints-wrt-url-d).

Endpoint like:

```
@ApplicationScoped
@Path("/path")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class PathResource
{
    @GET
    @Path("/list/{primaryKey: .+}")
    public String pathAsList(@PathParam("primaryKey") List<PathSegment> path)
    {
       return "As List/std (%d) -> %s".formatted(path.size(), path);
    }
```

when invoked with URL like:

```
http://localhost:8081/path/list/ab%2Fcd/ef%2Fgh
```

should produce `List` of 2 path elements; `"ab/cd"` and `"ef/gh"`, but actually produces 4 (for "ab", "cd", "ef" and "gh").
This would be due to first decoding the full path and then splitting by slashes; as opposed to reverse.

I have Rest-assured tests to verify behavior difference (see https://github.com/tatu-at-datastax/quarkus-demo/blob/main/src/test/java/com/fasterxml/quarkus/PathResourceTest.java) but the call looks like:

```
    @Test
    public void pathAsList() {
        given()
          .when().get("/path/list/{seg1}/{seg2}", "ab/cd", "ef/gh")
          .then()
             .statusCode(200)
             .body(is("As List/std (2) -> [ab/cd, ef/gh]"));
    }
```

Result is passing test when running against "quarkus-resteasy", but fail against "quarkus-resteasy-reactive".

### Expected behavior

Decoding of path parameter should split by non-encoded slashes first, then decode path segments; not decode full path and split by all slashes (encoded or not)

### Actual behavior

Due to what appears to be pre-mature character entity decoding, path segments are split also by encoded slashes (%2F), not only plain un-encoded ones.

### How to Reproduce?

Reproduction included in description, but there is also Github repo:

   https://github.com/tatu-at-datastax/quarkus-resteasy-reactive-34586

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### GraalVM version (if different from Java)

Not tested with graalVM

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by tatu-at-datastax** [comment]
Created

https://github.com/tatu-at-datastax/quarkus-resteasy-reactive-34586

as a minimal reproduction: fails with "quarkus-resteasy-reactive", passes if replacing dep with "quarkus-resteasy".

**Comment by geoand** [comment]
Thanks a lot. We'll have a look soon

**Comment by geoand** [comment]
@stuartwdouglas do you have some spare cycles to look into this one?
Asking because I would be starting from 0️⃣ on this one :)

**Comment by tatu-at-datastax** [comment]
Thank you @geoand !

**Comment by sberyozkin** [comment]
HI @geoand It might be simple to fix, input to the calculation of `List<PathSegment>` should be a `raw`, not `url-decoded` path component value, that will give 2 path segment values in this case

**Comment by sberyozkin** [comment]
@geoand Sure, if you can point me to the code where it is happening :-)

**Comment by sberyozkin** [comment]
@tatu-at-datastax Thanks, it does.

@geoand I'm happy to help, but I'm even less familiar with the Resteasy Reactive code base :-). It should be about propagating a raw path returned from `RoutingContext` down to the code which calculates the list of path segments, which splits right now the already url decoded path, it, keeping fingers crossed, should be all that needs to be done.
So please point me to where to start looking or open a draft PR with the main source update only and I can verify and complement it with test based on @tatu-at-datastax's reproducer. Thanks

**Comment by sberyozkin** [comment]
@tatu-at-datastax by the way, shoulld the individual path segment be decoded, what happens if it contains `%20` ? Thanks

**Comment by tatu-at-datastax** [comment]
@sberyozkin Yes I think all segments should be decoded after splitting by slash (possibly a simplified view). My example here didn't show it but in local tests I added encoded "funny character".

**Comment by geoand** [comment]
@sberyozkin I have never touched the PathSegment stuff :)

If I were you, I would start looking at where `org.jboss.resteasy.reactive.common.util.PathSegmentImpl` is created

**Comment by sberyozkin** [comment]
@geoand Sorry, security issues have come up so I'll need to prioritize on them for now

**Comment by geoand** [comment]
I'll try and have a look at this next week
