### ISSUE TITLE
AnnotationsTransformerBuildItem can't inject to ResteasyReactiveProcessor#setupEndpoints

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#34604]
### Describe the bug

This below is  a  builditem in my extension,

```java
    @BuildStep
    void addCompressed(HttpBuildTimeConfig httpBuildTimeConfig,BuildProducer<AnnotationsTransformerBuildItem> annotationsTransformerBuildItemBuildProducer) {
        AnnotationsTransformerBuildItem annotationsTransformerBuildItem = new AnnotationsTransformerBuildItem(new AnnotationsTransformer() {

            public boolean appliesTo(AnnotationTarget.Kind kind) {
                return kind == AnnotationTarget.Kind.METHOD;
            }

            @Override
            public int getPriority() {
                return DEFAULT_PRIORITY - 1;
            }

            public void transform(TransformationContext context) {
                if (httpBuildTimeConfig.enableCompression) {
                    MethodInfo method = context.getTarget().asMethod();
                    if (method.hasAnnotation(UNCOMPRESSED) || method.hasAnnotation(COMPRESSED)) {
                        return;
                    }

                    if (method.hasAnnotation(GET_ANNOTATION) || method.hasAnnotation(POST_ANNOTATION) ||
                        method.hasAnnotation(PUT_ANNOTATION) || method.hasAnnotation(DELETE_ANNOTATION)) {
                        context.transform().add(COMPRESSED).done();
                    }
                }
            }
        });
        annotationsTransformerBuildItemBuildProducer.produce(annotationsTransformerBuildItem);
    }
```

In `ResteasyReactiveProcessor`.`setupEndpoints`,`List<AnnotationsTransformerBuildItem> annotationTransformerBuildItems` is empty.

```java
            if (!annotationTransformerBuildItems.isEmpty()) {
                List<AnnotationsTransformer> annotationsTransformers = new ArrayList<>(annotationTransformerBuildItems.size());
                for (AnnotationsTransformerBuildItem bi : annotationTransformerBuildItems) {
                    annotationsTransformers.add(bi.getAnnotationsTransformer());
                }
                serverEndpointIndexerBuilder.setAnnotationsTransformers(annotationsTransformers);
            }
```

 I confirm that  `addCompressed` run before `setupEndpoints`, I had run them in debug mode.

### Expected behavior

`ResteasyReactiveProcessor`.`setupEndpoints` can get `AnnotationsTransformerBuildItem`

### Actual behavior

`ResteasyReactiveProcessor`.`setupEndpoints` can't get `AnnotationsTransformerBuildItem`

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu17.38+21-CA

### Quarkus version or git rev

2.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by Ladicek** [comment]
Can you confirm the fully qualified name of `AnnotationsTransformerBuildItem` in your code?

There are 2 classes with that name in Quarkus:

- `io.quarkus.arc.deployment.AnnotationsTransformerBuildItem`
- `io.quarkus.resteasy.reactive.server.spi.AnnotationsTransformerBuildItem`

The first produces annotation transformers used by ArC (the CDI container in), while the second produces annotation transformers used by RESTEasy Reactive. I take it you need the 2nd -- are you sure you don't accidentally have the 1st?

**Comment by naah69** [comment]
You are right! 
I had resloved my problem.
Thank you very much
