### ISSUE TITLE
Quarkus 3.1.1.Final and above ignores EntityGraph hints

### ISSUE THREAD

**Issue by garthberry** [quarkusio/quarkus#34614]
### Describe the bug

When upgrading from Quarkus 3.0.3.Final to 3.2.0.Final (POM update only, no other changes) our application started throwing exceptions similar to the following on most Rest endpoints.

`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: <class>: could not initialize proxy - no Session`

Investigating further we could update our application to 3.1.0.Final without any issue, 3.1.1.Final to 3.2.0.Final would throw the exception above. It appears as though Quarkus 3.1.1.Final and above are ignoring EntityGraph hints. A simple reproducer is attached, the test will pass with Quarkus 3.1.0.Final and fail for versions >= 3.1.1.Final.

The reproducer does not fail with exactly the same exception, however, it seems to be a similar root cause. Setting the collection fetch attribute to FetchType.EAGER will cause the test to pass for versions >= 3.1.1.Final 

[hibernate_entity_graph_reproducer.zip](https://github.com/quarkusio/quarkus/files/11985354/hibernate_entity_graph_reproducer.zip)

### Expected behavior

EntityGraph hints are applied

### Actual behavior

EntityGraph hints are ignored.

### How to Reproduce?

Reproducer attached.

**Comment by garthberry** [comment]
Hi @Sanne, Is there an alternative approach that we should be using with respect to using EntityGraph hints in Quarkus? 

I haven't seen any discussion of this issue so it seems either no one else is using EntityGraph with Quarkus or other projects are yet to upgrade to Quarkus >= 3.1.1.Final.

**Comment by Sanne** [comment]
Excellent, thanks for checking!
