### ISSUE TITLE
Support Constructor Injection in @QuarkusTest

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34619]
### Description

Currently I tried to inject beans via constructor like declaring fields in a general Kotlin class, it does not work as expected.

I have tried the following, both are failed.

```kotlin
@QuarkusTest
class MyTest(val posts: PostRepository) {}
```

```kotlin
@QuarkusTest
class MyTest @Inject constructor(val posts: PostRepository) {}
```

### Implementation ideas

I hope it is working like a simple class with constructor injection automaticially. 

```kotlin
@QuarkusTest
class MyTest(val posts: PostRepository) {}
```

**Comment by geoand** [comment]
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/34330
