### ISSUE TITLE
.onTermination() eventually() is triggered twice with gRPC client in manyToOne case

### ISSUE THREAD

**Issue by AlekseyMay** [quarkusio/quarkus#34613]
### Describe the bug

I have gRPC server and client services. Both using Mutiny gRPC generation option. The problem happens on the client side.
I am using manyToOne request, Multi as input and Uni as output (Multi -> Uni) of request.
The strange behavior is that if I use .onTermination().invoke(() -> anyAction) or .eventually(() -> anyAction) after the method call, it is triggered twice in (Multi -> Uni) scenario.
I have oneToOne (Uni -> Uni) and oneToMany (Uni -> Multi) for them everything is ok. And 'anyAction' is called only once in the same scenario.
I don`t have any manyToMany, but maybe the problem exists for such case as well.

Is it expected behavior?

### Expected behavior

anyGrpcService.manyToOne(inputMulti)
.onTermination().invoke(() -> anyAction) or .eventually(() -> anyAction) 

'anyAction' should be called only once in any gRPC case.

### Actual behavior

anyGrpcService.manyToOne(inputMulti)
.onTermination().invoke(() -> anyAction) or .eventually(() -> anyAction) 

'anyAction' called once in oneToOne (Uni -> Uni) and oneToMany (Uni -> Multi) scenario. 
Twice in manyToOne(Multi -> Uni) scenario.

Maybe twice in manyToMany.

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

**Comment by cescoffier** [comment]
Can you provide a reproducer?

I've tried the following test:

```java
 @GrpcClient
    ManyToOne service;

    /**
     * Reproduce <a href="https://github.com/quarkusio/quarkus/issues/34613">#34613</a>.
     */
    @Test
    public void testManyToOneTermination() {
        Multi<Messages.StreamingInputCallRequest> input = Multi.createFrom().items("a", "b", "c", "d")
                .map(s -> Messages.Payload.newBuilder().setBody(ByteString.copyFromUtf8(s)).build())
                .map(p -> Messages.StreamingInputCallRequest.newBuilder().setPayload(p).build())
                .emitOn(Infrastructure.getDefaultWorkerPool());
        Uni<Messages.StreamingInputCallResponse> done = service.manyToOne(input)
                .onTermination().invoke(() -> System.out.println("on termination called"));
        assertThat(done).isNotNull();
        done.await().atMost(TIMEOUT);
    }
```

And the following proto:
```proto
syntax = "proto3";

import "empty.proto";
import "messages.proto";

package grpc.testing;

option java_package = "io.grpc.testing.integration";

// A simple service to test the various types of RPCs and experiment with
// performance with various types of payload.
service ManyToOne {

  rpc ManyToOne(stream StreamingInputCallRequest)
  returns (StreamingInputCallResponse);

}
```

My service implementation is straightforward:
```java
@GrpcService
public class ManyToOneService implements ManyToOne {
    @Override
    public Uni<Messages.StreamingInputCallResponse> manyToOne(Multi<Messages.StreamingInputCallRequest> request) {
        return request.map(i -> i.getPayload().getBody().toStringUtf8())
                .collect().asList()
                .map(list -> {
                    assertThat(list).containsExactly("a", "b", "c", "d");
                    return Messages.StreamingInputCallResponse.newBuilder().build();
                });
    }
}
```

Can you spot a difference with your case?

**Comment by cescoffier** [comment]
So, it's expected, and it's how the retry works.
A retry is just another subscription.

If you do and `anyClientGrpcService` fails:

```java
anyClientGrpcService(inputMulti)
    .onTermination().invoke(() -> anyAction))
    .onFailure().retry().withBackOff(Duration.ofSeconds(2)).atMost(2)
```

If will call anyClientGrpcService for the first time, fails, invoke onTermination (because it failed) and then retry.
It will call anyClientGrpcService again, still fail, and invoke onTermination again.

To call it only once, just use:


```java
```
anyClientGrpcService(inputMulti)
    .onFailure().retry().withBackOff(Duration.ofSeconds(2)).atMost(2)
    .onTermination().invoke(() -> anyAction))
```

In this case, it will call anyClientGrpcService, fails, retry, call it again fails again (give up retrying), and call onTermination, once.

**Comment by cescoffier** [comment]
Yes, it's not related to gRPC - as explained, it's how retry works. See https://smallrye.io/smallrye-mutiny/2.0.0/tutorials/retrying/

**Comment by cescoffier** [comment]
No problem at all!

**Comment by sschellh** [comment]
Hi @cescoffier : I just came across the same observation and I wonder why onTermination is called twice, whereas onItem is only called once.
In case there is no failure and hence no retry, I would expect that the Multi / Uni only terminates once.
Isn't onTermination just a kind of "short cut" for onItem or onFailure or onCancel?

```
        Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onTermination().invoke(() -> System.out.println("onTermination is called twice"))
                .onFailure().retry().withBackOff(Duration.ofSeconds(2)).atMost(2)
                .subscribe().asCompletionStage();
```

 ```
       Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onItem().invoke(() -> System.out.println("onItem is called once (as expected)"))
                .onFailure().retry().withBackOff(Duration.ofSeconds(2)).atMost(2)
                .subscribe().asCompletionStage();
```

**Comment by cescoffier** [comment]
onTermination should always be called but only once: either upon completion, failure or cancellation.

Do you have a reproducer?

**Comment by sschellh** [comment]
Hi @cescoffier 

Please find a simple demo below using Quarkus 3.7.3.
The issue seems to be related to the `withBackOff(Duration.ofSeconds(1))` statement.

```
import io.smallrye.mutiny.Multi;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.List;

public class OnTerminationTest {

    @Test
    public void reproducer() {
        Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onTermination().invoke(() -> System.out.println("onTermination is called twice (not expected) withBackoff"))
                .onFailure().retry().withBackOff(Duration.ofSeconds(1)).atMost(2)
                .subscribe().asCompletionStage();

        Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onTermination().invoke(() -> System.out.println("onTermination is called once (expected) withoutBackoff"))
                .onFailure().retry().atMost(2)
                .subscribe().asCompletionStage();

        Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onItem().invoke(() -> System.out.println("onItem is called once (expected) withBackoff"))
                .onFailure().retry().withBackOff(Duration.ofSeconds(1)).atMost(2)
                .subscribe().asCompletionStage();

        Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onItem().invoke(() -> System.out.println("onItem is called once (expected) withoutBackoff"))
                .onFailure().retry().atMost(2)
                .subscribe().asCompletionStage();
    }

}
```

This test outputs the following. The second line is not expected.

> onTermination is called twice (not expected) withBackoff
**> onTermination is called twice (not expected) withBackoff**
> onTermination is called once (expected) withoutBackoff
> onItem is called once (expected) withBackoff
> onItem is called once (expected) withoutBackoff

**Comment by cescoffier** [comment]
(and thanks for the awesome reproducer)

**Comment by jponge** [comment]
Thanks @sschellh I'm going to have a look

**Comment by jponge** [comment]
I ran

```java
Multi.createFrom().iterable(List.of("aa", "bb", "cc"))
                .collect().asList()
                .onTermination().invoke(() -> System.out.println("onTermination is called twice (not expected) withBackoff"))
                .onFailure().retry().withBackOff(Duration.ofSeconds(1)).atMost(2)
                .subscribe().asCompletionStage();
```

On Mutiny 2.5.6 and was able to reproduce the issue.

The good news is that this has been fixed with the recent changes in the `main` branch of Mutiny, so 2.6.0 will have a fix.
I'm looking if there's an obvious backport for that specific issue.

**Comment by jponge** [comment]
Following up in Mutiny, there will be a 2.5.7 release with a fix for that bug 👍
