### ISSUE TITLE
Quarkus and continuous testing

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#3461]
**Description**
Quarkus focus Developer eXperience, the best example is `quarkus:dev` which mimics frontend livereload practice. Livereload is very efficient when you're with a client (SPA, API consumer etc.) and tends to hide the unit/integration testing practices. 

The purpose of this feature request is to propose a similar behavior with testing (why not a `quarkus:test`command.

The idea is not new, [Infinitest](https://plugins.jetbrains.com/plugin/3146-infinitest) is example of plugin for IntelliJ reducing the testing feeback loop (just as `quarkus:devs` does).

**Implementation ideas**
The trivial option would be to reuse `quarkus:dev` hook and run the Maven/Gradle test goal. The limitations I have in mind:
* How to provide an instant feedback when you have a large set of tests. One way would be to compute which tests are impacted by the update code to only run them, or more simply let the dev specify the filters to apply on  the test to be run (exclude: `com.package.integration.*`
* It's one more feature to maintain for the Quarkus team. If the `quarkus:dev` hooks could be public, this could be proposed by the community as a plugin (I don't know if it can be developed as an extension)

WDYT?

**Comment by BiggA94** [comment]
I would also love to see this feature.

For example: Jest allows adding watchPlugins where you can specify, which tests should run. [see here](https://jestjs.io/docs/en/watch-plugins).
This allows running only those tests, that are affected since the last commit via plugin.

**Comment by geoand** [comment]
Something similar was proposed on the mailing list: https://groups.google.com/g/quarkus-dev/c/qB3iW0ciLqI/m/UJAB7KbRAgAJ

**Comment by stuartwdouglas** [comment]
Done.
