### ISSUE TITLE
NPE in Mockito + Kotlin 

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34622]
### Description

Example codes: https://github.com/hantsy/quarkus-sandbox/tree/master/mongodb-kotlin-co

Given the following tests.

```kotlin 
    @Test
    fun `get post by id`() {
        val id = ObjectId()
        `when`(postRepository.findById(any(ObjectId::class.java)))
            .thenReturn(
                Uni.createFrom().item(
                    Post(id, "foo", "bar", LocalDateTime.now()),
                )
            )

        //@formatter:off
        given()
            .accept(ContentType.JSON)
        .`when`()
            .get("/posts/$id")
        .then()
            .statusCode(200)
            .log().all()
            .body( "title", `is`("foo"))
        //@formatter:on

        verify(postRepository, times(1)).findById(any(ObjectId::class.java))
        verifyNoMoreInteractions(postRepository)
    }
```

The argument `any(ObjectId::class.java))` throws a NPE exception.

```kotlin
java.lang.NullPointerException: any(ObjectId::class.java) must not be null

	at com.example.PostResourcesTest.get post by id(PostResourcesTest.kt:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

```

### Implementation ideas

I not sure how `@InjectMock` works, from the Mockito website, this could be caused by the fun that mocked is not `open`.

https://github.com/mockito/mockito-kotlin/wiki/Parameter-specified-as-non-null-is-null

**Comment by hantsy** [comment]
I have tried use Mockk and Quarkus Mockk instead, both are working well.

* https://github.com/hantsy/quarkus-sandbox/blob/master/mongodb-kotlin/src/test/kotlin/com/example/PostResourcesWithMockkTest.kt
* https://github.com/hantsy/quarkus-sandbox/blob/master/mongodb-kotlin/src/test/kotlin/com/example/PostResourcesWithQuarkusMockkTest.kt

**Comment by geoand** [comment]
> The argument any(ObjectId::class.java)) throws a NPE exception.

There is nothing Quarkus can do about this unfortunately.

**Comment by hantsy** [comment]
@geoand Ok, I move this post on stackoverflow: https://stackoverflow.com/questions/76652291/npe-exception-when-using-mockitokotlin-in-quakrus-project , and I provided comparison with Spring boot codes.

If you do not think this is a bug of Quarkus(runtime or tools), can you provide a suggestion to fix it or add a quickstart project in Quarkus quickstart repository for it?

**Comment by geoand** [comment]
I don't know why it doesn't work, but that would require debugging the mockito code

**Comment by hantsy** [comment]
@geoand I have done a basic debug, the exception is through `QuarkusTestExetion`, I think it is related to Quakrus handling. 

Similar codes, both Spring Kotlin/Kotlin Coroutines and Quarkus Java version are working.

**Comment by geoand** [comment]
Do you have any more details?

**Comment by hantsy** [comment]
@geoand Add additional `mockito-kotlin` maven module, and use the `any`/`argumentCaptor` to resovle the issue.

https://github.com/hantsy/quarkus-sandbox/blob/master/mongodb-kotlin/src/test/kotlin/com/example/PostResourcesTest.kt

I am not sure why the Mockito Java `any` is working in Spring (with a `spring` kotlin compiler plugin)
