### ISSUE TITLE
Quarkus 3.2: Native Remote-container-build does not copy .so files when necessary (awt) / GraalVM/Mandrel 17 (23.X)

### ISSUE THREAD

**Issue by knuspertante** [quarkusio/quarkus#34627]
### Describe the bug

Since Quarkus 3.2 or GraalVM/Mandrel 17 (23.X) `.so` files are are necessary when relying on awt.
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2#native-compilation---native-executables-and-so-files

`.so` files are copied to `/target` folder when using container build. But when **remote-container-build** is used no `.so` files are copied. 

The reason, no volume is mounted. Instead the runner file is explicitly copied from container.

### Expected behavior

Copy all `.so` files to `/target` folder

### Actual behavior

No `.so` files are copied.

### GraalVM version (if different from Java)

Mandrel 17 (23.X)

### Quarkus version or git rev

3.2.0.Final

**Comment by gsmet** [comment]
@Karm I think we should apply the workaround you put together to the default Dockerfile. 

And also add a note in the migration guide for 3.2.

**Comment by Karm** [comment]
Will process.
