### ISSUE TITLE
TypeNotPresentException during entity augmentation

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#3462]
**Describe the bug**
I'm seeing Maven build failures from the package phase (and later phases) due to entity class augmentation failures.

**Expected behavior**
Jar files are created for the project.

**Actual behavior**
No jar files are created.  This is failing on an entity that is catching a `NoResultException` or a `NonUniqueResultException`.  These classes are in the dependency tree of the project, and show up in the class path and constructed class loader during the build.

**To Reproduce**
Run `./mvnw clean package` on the attached example project.

**Screenshots**
```
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2155ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.066 s
[INFO] Finished at: 2019-08-08T10:03:17-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.20.0:build (default) on project getting-started: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: java.lang.TypeNotPresentException: Type javax/persistence/NoResultException not present: javax.persistence.NoResultException -> [Help 1]
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux **** 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)
```
 - GraalVM version (if different from Java): n/a (not using GraalVM)
 - Quarkus version or git rev: 0.20.0

**Additional context**
It looks like when `HibernateEnhancingClassVisitor` is constructed, it does not pass along the class loader to the new instance of `ClassWriter`.  It somehow gets a different class loader, which knows nothing about the carefully constructed class loader from Quarkus, so it throws a `ClassNotFound` exception when it processes the entity class, trying to find `NoResultException` or `NonUniqueResultException`.

**Comment by nderwin** [comment]
[quarkstart.zip](https://github.com/quarkusio/quarkus/files/3482236/quarkstart.zip)

**Comment by geoand** [comment]
@Sanne something you could look at perhaps?

**Comment by sirf** [comment]
I ran into the exact same problem and decided to give it a shot.
This simple change fixes the issue, without breaking anything else as far as I can tell: https://github.com/quarkusio/quarkus/pull/3507

**Comment by sirf** [comment]
PR #3508 seems to fix the issue.
