### ISSUE TITLE
Quarkus 3.2: Hibernate ORM configuration problem

### ISSUE THREAD

**Issue by krisztiankocsis** [quarkusio/quarkus#34628]
### Describe the bug

I'm upgrading to Quarkus 3.2 from 2.x (lates) and I need to add one new config property:

quarkus.hibernate-orm.mydatasource.mapping.timezone.default-storage=normalize

When I try to build the app with Maven package goal I'm gettting this error:

SRCFG00014: The config property quarkus.hibernate-orm.mydatasource.mapping.query.query-plan-cache-max-size is required but it could not be found in any config source

### Expected behavior

The reported configuration property is both bad (there is no "mapping" prefix") and not mandatory, so it shouldn't complain about it.

### Actual behavior

Halts the build with the mentioned error message.

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

**Comment by yrodiere** [comment]
Seems related to Smallrye-config... Can't have a look right now as I'm away but @radcortez might have some insight (maybe it's a bug in Smallrye-Config, maybe it's just a misuse of Smallrye-Config)

**Comment by radcortez** [comment]
I'll have a look

**Comment by radcortez** [comment]
The issue here is similar to what we had in mappings. A `@ConfigItem` does not support a dotted name. It requires a group for each segment.

I could probably implement that, but we want everyone to move to mappings, so we will not add new features. I've added the middle groups instead to replace the dotted names.
