### ISSUE TITLE
Quarkus 3.2.0.Final fetching build analytics remote config when disabled

### ISSUE THREAD

**Issue by soframel** [quarkusio/quarkus#34626]
### Describe the bug

Quarkus 3.2.0.Final seems to try to fetch a remote configuration for build analytics, even though build analytics are not enabled and are supposed to be opt-in. 

In addition, the warning is also using the wrong Maven logger or logger level, because we are using the Maven helper plugin in our CI/CD with options "-q –DforceStdout" to fetch project information, and this log line still appears and breaks our job in our internal CI/CD: 

`[warn] [Quarkus build analytics] Analytics remote config not received. java.util.concurrent.TimeoutException: (no message)`

(logging issue is perhaps related to #34166 ?)

In addition, I tried to force disabling the build analytics using the 2 solutions mentioned in the doc:

- JSON File in home/.redhat/io.quarkus.analytics.localconfig
- Maven param -Dquarkus.analytics.disabled=true

but I still have the same problem, so it seems like it is still trying to get a remote config. 

We didn't have this for previous versions of Quarkus, only for 3.2.0.Final

### Expected behavior

Quarkus not fetching anything for build analytics when they are disabled (which should be the default)

### Actual behavior

Quarkus tries to fetch build analytics remote configuration

### How to Reproduce?

Steps to reproduce: 

1. generate quarkus app from https://code.quarkus.io/ using Maven and Quarkus 3.2.0.Final
2. remove file io.quarkus.analytics.remoteconfig from ~home/.redhat
3. disconnect internet connection
4. run `mvn package` , or even `mvn package -q`

-> The log contains this line: 

`[warn] [Quarkus build analytics] Analytics remote config not received. java.util.concurrent.ExecutionException: java.net.ConnectException`

### Output of `uname -a` or `ver`

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (but also happens in other environments)

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

### Additional information

Note: this may not seem blocking, but the logging issue is blocking our CI/CD completely, because we are using the helper plugin to fetch project identification info, and get a log line instead.

**Comment by yrodiere** [comment]
Hey @brunobat, I believe this one is for you?

**Comment by brunobat** [comment]
I'll get this one.

**Comment by maxandersen** [comment]
@soframel that we check for analytics when the flag is not set is a bug and we'll fix that ASAP.

I'm curious to grok why the printing to the log breaks your build - can you elaborate here ?

note: we will remove that printing too by default as it is not necessary but I would like to understand why you see that as breaking your build as opposed to "just" being noise in the log?

**Comment by soframel** [comment]
Yes, of course: it is a cross-project CI/CD where we must get project coordinates before continuing, for various reasons. We are using code like this: 
`- export GAV=$(echo '${project.groupId}:${project.artifactId}:${project.version}:${project.packaging}' | mvn -N -q -DforceStdout org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate)
- PROJECT_GROUPID=$(echo $GAV | cut -d ':' -f 1)
- PROJECT_ARTIFACTID=$(echo $GAV | cut -d ':' -f 2)
- PROJECT_VERSION=$(echo $GAV | cut -d ':' -f 3)
- PROJECT_PACKAGING=$(echo $GAV | cut -d ':' -f 4)
`

**Comment by soframel** [comment]
it works well with Quarkus 3.2.1.Final, thanks !

**Comment by rupert-jung-mw** [comment]
Still not working for 3.8.4.
`quarkus.analytics.disabled` is set to false:

![image](https://github.com/quarkusio/quarkus/assets/160733883/ffc97d03-8c60-4a30-a93a-e43c28d25ecf)

Next startup:
![image](https://github.com/quarkusio/quarkus/assets/160733883/c6326a9a-9b29-4f34-9506-a19cfb7ecb2e)

Even trying to answer the question via the console is not working, the input is not scanned:

![image](https://github.com/quarkusio/quarkus/assets/160733883/a01f5007-1cd8-446a-9d33-2a1d07e4a966)

**Comment by brunobat** [comment]
@rupert-jung-mw can you please file a new bug report?
This must be a different issue from the one reported here.

**Comment by rupert-jung-mw** [comment]
@brunobat Done.
