### ISSUE TITLE
QUARKUS_INIT_AND_EXIT is currently ignored.

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#34643]
### Describe the bug

As title says `QUARKUS_INIT_AND_EXIT` is not respected.

### Expected behavior

When `QUARKUS_INIT_AND_EXIT` is set to true the Quarkus application should exit before starting (binding http port).

### Actual behavior

The application never exits.

### How to Reproduce?

Run the a quarkus application using:
```sh
QUARKUS_INIT_AND_EXIT=true java -jar target/quarkus-app/quarkus-run.jar
```

**Comment by cescoffier** [comment]
IS there anything I can do to workaround it? This is blocking the kafka and AMQP initialization jobs.

**Comment by Gutenberg70** [comment]
Just wanted to note that it also has an effect on Liquibase init containers, since they also depend on this property. 
I couldn't find a workaround neither.

**Comment by grossws** [comment]
Would it be backported into 3.2.x branch?

**Comment by grossws** [comment]
Currently I use the following workaround:

```
@Singleton
@Startup
public class InitAndExitStub {
  @ConfigProperty(name = "quarkus.init-and-exit", defaultValue = "false")
  boolean initAndExit;

  @PostConstruct
  void init() {
    if (initAndExit) {
      Quarkus.asyncExit();
    }
  }
}
```
