### ISSUE TITLE
Resteasy reactive - Interfaces are added as a Bean causing jakarta.enterprise.inject.AmbiguousResolutionException

### ISSUE THREAD

**Issue by floresmleonardo** [quarkusio/quarkus#34657]
### Describe the bug

When utilizing RESTeasy Reactive, an issue arises when multiple classes implement the same interface and, the interface has methods with the @Path annotation. In this scenario, Quarkus mistakenly registers the interface as a bean, which results in a **jakarta.enterprise.inject.AmbiguousResolutionException** due to the presence of multiple beans without a qualifier.

Note: This issue occurs specifically in the context of **RESTeasy Reactive** with Quarkus. If you change to **RESTeasy Classic**, then, it behaves as expected.

### Expected behavior

Quarkus should handle the usage of the interface correctly and avoid registering it as a bean to prevent the jakarta.enterprise.inject.AmbiguousResolutionException.

### Actual behavior

Quarkus mistakenly treats the interface as a bean, leading to the jakarta.enterprise.inject.AmbiguousResolutionException error.

### How to Reproduce?

Repo: https://github.com/floresmleonardo/quarkus-bug-resteasy-reactive

Run the application

### Quarkus version or git rev

3.2.0

**Comment by geoand** [comment]
Looks like a bug indeed but I fear that addressing this will cause other issues.

In any case, it needs some investigation.

**Comment by diogocarleto** [comment]
Hi guys, same thing here, I'm trying to migrate to resteasy reactive and the same happens, if I comment the `@Path` and `@GET/@POST` it works

**Comment by geoand** [comment]
#34888 fixes the issue
