### ISSUE TITLE
quarkus-kubernetes extension throws NullPointerException during maven test phase

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#3465]
**Describe the bug**
When compiling a very basic Quarkus application (see reproduce steps), running "mvn package" throws a NullPointerException in the test phase:

```
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
```

**To Reproduce**
1. Create a sample application using `mvn quarkus:create`
2. Run `mvn quarkus:add-extension -Dextensions="quarkus-kubernetes"`
3. Run `mvn compile package`

**Environment (please complete the following information):**
 - Output of `java -version`: 1.8.0_222
 - GraalVM version (if different from Java):  19.1.1
 - Quarkus version or git rev: 0.20.0

**Additional context**
This problem does not exist in Quarkus 0.19.1

**Comment by gwenneg** [comment]
Hi @jclingan, I just tried to reproduce this but the build worked fine, without any exception.

Is there a more detailed stacktrace in the Maven output?

**Comment by geoand** [comment]
@jclingan I was able to reproduce the problem, looking into it now

**Comment by geoand** [comment]
@jclingan I opened a PR with a fix. It should work fine for now, but it's one thing that @iocanel and I need to look into as part of the tighter Dekorate - Quarkus integration

**Comment by jclingan** [comment]
Thx @geoand. Yeah, I should have mentioned the test phase.

**Comment by geoand** [comment]
Now all we need is someone to approve my PR 😁
