### ISSUE TITLE
Create OTel IdGenerator tests

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#34668]
### Description

We are missing IdGenerator tests to prove the correct integration.
The tests were working with AWS ID Generator and we don't want that dependency on the main extension.

See: io.quarkus.opentelemetry.deployment.OpenTelemetryIdGeneratorTest

**Comment by brunobat** [comment]
We need to create an ID generator that is not AWS dependent, use it and see if it works.

**Comment by brunobat** [comment]
In relation to the AWS ID itself it would be nice to have a test project for AWS lambdas that could also use this, however, this a much bigger task.

**Comment by mskacelik** [comment]
Gonna have a look at the ID generators.
