### ISSUE TITLE
Missing org.infinispan.distribution.group.Group in infinispan-client extension

### ISSUE THREAD

**Issue by mgubaidullin** [quarkusio/quarkus#34677]
### Describe the bug

An infinispan dependency that contains org.infinispan.distribution.group.Group is missing. 
Therefore it is not possible to configure group key according to  https://infinispan.org/docs/stable/titles/configuring/configuring.html#grouping-api_clustered-caches

### Expected behavior

org.infinispan.distribution.group.Group is part of infinispan-client extension

### Actual behavior

org.infinispan.distribution.group.Group is not a part of infinispan-client extension

### How to Reproduce?

Try to import `import org.infinispan.distribution.group.Group;` and set `@Group` annotation

### Output of `uname -a` or `ver`

Darwin MacBook15.local 22.5.0 Darwin Kernel Version 22.5.0

### Output of `java -version`

openjdk version "11.0.7"

### Quarkus version or git rev

2.16.7.Final

**Comment by karesti** [comment]
@mgubaidullin are you are using Infinispan in embedded mode?

**Comment by karesti** [comment]
@mgubaidullin Group annotation is part of infinispan-core dependency, so seems like an embedded only use case. In any case this is not a Quarkus issue. Let me check with the team about this particular feature

**Comment by karesti** [comment]
@mgubaidullin I confirm this is an embedded infinispan use case. We will add additional explanations in the docs. However, we are curious about the use case you need to implement, something that might be missing from the client/server perspective. @wburns @pruivo

**Comment by mgubaidullin** [comment]
The case is simply to allows to co-locate a group of entries on the same nodes as described in [Group API](https://infinispan.org/docs/stable/titles/configuring/configuring.html#grouping-api_clustered-caches)

It requires to annotate methods in key classes:
```
// Override the location by specifying a group
   // All keys in the same group end up with the same owners
   @Group
   public String getOffice() {
      return office;
   }
```
However the org.infinispan.distribution.group.Group class in not a part of quarkus-infinispan-client, so there is no way to annotate model.

**Comment by pruivo** [comment]
@mgubaidullin but why do you want to co-locate entries? The Hot Rod client is smart enough to find where each entry is and there is no advantage in co-locating entries with the Infnispan server.

**Comment by karesti** [comment]
@mgubaidullin yes, I understand. Our question is, why would you need to do that in client/server mode?  We are trying to think of what benefits groups can have for a client. It's useful for embedded infinispan where you want colocation, but the client already sends the requests to the primary owner, we don't see any advantage of grouping keys. That's why I'm asking, if there is a benefit or use case that we might be missing

**Comment by mgubaidullin** [comment]
@karesti I agree. Looks like I misunderstood the concept of grouping. Thanks for the explanation.
Issue might be closed.
