### ISSUE TITLE
quarkus deploy --openshift ignores quarkus.openshift.deployment-kind=Deployment

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34675]
### Describe the bug

When deploying to Openshift with:

```
quarkus deploy --openshift --image-build
```

It ignores:

```
quarkus.openshift.deployment-kind=Deployment
```

This means we end up with a deployment config instead of a deployment. 
So, many features, such as metrics, are not supported (anymore). 

It may not be supported - but at least it should fail the build indicating that it's not possible to generate a deployment (which would be really sad).

**Comment by iocanel** [comment]
It seems that the option, we have in the cli for setting deploymnet kind is masking the configured value. Will convert it to `Optional`.

**Comment by cescoffier** [comment]
Ok, well, not quite...

It "works" but does not.... When used the option  in conjunction with --image-build, the image build creates an image stream and the deployment point to the projected image. So... basically, it just crash loop.

Either we clearly fail to say that this combination does not work, or we configure the deployment property to use the image stream.

**Comment by iocanel** [comment]
@cescoffier: The combination is not Illegal and it's something that used to work, by referencing the image in the internal Openshift registry. Nowdays (as of 4f6d9d8e795a02d91b627e46c38fc1348433c284) we enable image stream lookups.

I'll have a look tommorow to check what exactly is not working.

**Comment by iocanel** [comment]
@cescoffier: according to [openshift doc] the local image lookup for imagestreams only works for single segment images (e.g. my-app:1.0).

At the moment we don't enforce that, but one can configure it by setting: 

```
quarkus.container-image.group=
```

To actually deal with it, I created: #34748

[openshift doc]: https://docs.openshift.com/container-platform/4.13/openshift_images/using-imagestreams-with-kube-resources.html#images-managing-images-enabling-imagestreams-kube_using-imagestreams-with-kube-resources
