### ISSUE TITLE
quarkus.arc.exclude-types doesn't work

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#34697]
### Describe the bug

```
quarkus create app demo
# copy GreetingResource.java to Greeting2Resource.java and replace "hello" with "world"

export QUARKUS_ARC_EXCLUDE_TYPES='Greeting2Resource'
./mvnw clean package -DskipTests
java -jar target/quarkus-app/quarkus-run.jar

curl 'localhost:8080/world'
```

`/world` should report `404 Not Found`, not `200 OK`.

### Output of `uname -a` or `ver`

Darwin xxx 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by Dieken** [comment]
[demo.tar.gz](https://github.com/quarkusio/quarkus/files/12027192/demo.tar.gz)

The demo project.

**Comment by geoand** [comment]
`quarkus.arc.exclude-types` is not applicable to RESTEasy Reactive.

See [this](https://quarkus.io/guides/resteasy-reactive#includeexclude-jakarta-rest-classes) for now to disable such classes.

**Comment by Dieken** [comment]
The BuildProfile and BuildProperty annotations belong to ArC too, can we make `quarkus.arc.exclude-types` works for RESTEasy too? I wouldn’t like to mark many classes in source code, the `exclude-types` configuration is much more flexible and convenient.

**Comment by geoand** [comment]
We are unlikely to do that

**Comment by Dieken** [comment]
Found bug in the build property annotation, opened another issue: https://github.com/quarkusio/quarkus/issues/34938
