### ISSUE TITLE
After update to 3.2.0.Final native compilation throws an exception

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#34698]
### Describe the bug

Since updating to 3.2.0.Final native compile uses `quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17` to build.

### Expected behavior

It should compile like the previous `quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 ` did.

### Actual behavior

```
[1/8] Initializing...                                                                                   (26,9s @ 0,51GB)
 Java version: 17.0.7+7, vendor version: Mandrel-23.0.0.0-Final
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 3 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
[2/8] Performing analysis...  []                                                                        (32,9s @ 0,73GB)
   5.104 (47,67%) of 10.708 types reachable
   6.138 (50,75%) of 12.095 fields reachable
  21.256 (31,67%) of 67.126 methods reachable
   2.140 types,   550 fields, and 4.942 methods registered for reflection

Fatal error: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Executable.getDeclaringClass()" because "method" is null
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.SubstitutionReflectivityFilter.shouldExclude(SubstitutionReflectivityFilter.java:65)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.registerMethod(ReflectionDataBuilder.java:331)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.lambda$register$16(ReflectionDataBuilder.java:275)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
------------------------------------------------------------------------------------------------------------------------
                        3,8s (6,1% of total time) in 21 GCs | Peak RSS: 2,97GB | CPU load: 4,38
------------------------------------------------------------------------------------------------------------------------
```

### How to Reproduce?

I tried to reproduce it, but I could not find the problematic code

### Output of `uname -a` or `ver`

Linux SOMEHOST 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.19 (Ubuntu 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OS:           Linux 5.19.0-46-generic amd64
```

**Comment by gsmet** [comment]
@zakkak @galderz this looks like a GraalVM issue?
If any case, there should be a proper error message IMO. 

@bulldog98 do you think you could come up with a reproducer? We haven’t seen this issue in our tests so there must be something specific to your app? Maybe you are referencing a non existing method in a reflection config file?

**Comment by bulldog98** [comment]
@gsmet I have a custom extension that configures a substitute for `org.eclipse.paho.client.mqttv3.internal.websocket.Base64.encode` and `encodeBytes` otherwise I'm using
quarkus-kubernetes-config
quarkus-kubernetes
quarkus-container-image-docker
quarkus-vertx-http
quarkus-oidc-client
quarkus-smallrye-reactive-messaging-rabbitmq
quarkus-smallrye-health
as extensions and I only register some Pojos with `@RegisterForReflection` and in the extension I'm configuring some classes for reflection, that are unchanged, since it's an internal lib.

Maybe it's "sun.nio.ch.FileLockImpl" since I use the paho lib and also configure that? [It quite similar to the camel implementation for registering reflection](https://github.com/apache/camel-quarkus/blob/main/extensions/paho/deployment/src/main/java/org/apache/camel/quarkus/component/paho/deployment/PahoProcessor.java). 

I'm not using a reflection config file, so I do not think that's it.

Regarding reproducer, I'm not sure what is the cause and howto go isolating it.

As workaround I used `quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17` as setting and it works with that version of GraalVm

**Comment by zakkak** [comment]
> @zakkak @galderz this looks like a GraalVM issue?
> If any case, there should be a proper error message IMO.

I agree. I have opened https://github.com/oracle/graal/pull/6985 to address this upstream.

@bulldog98 if you are willing to trace this down, you can use `-Dquarkus.native.debug-build-process=true` and attach your IDE to the native image builder. Then you can set a conditional breakpoint at https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionDataBuilder.java#L275 to break the execution when `executable` is `null`. This will allow you to see what passed the `null` value, and possibly fix the issue without waiting for an upstream fix.

**Comment by bulldog98** [comment]
@zakkak I'll have a go at that tomorrow

**Comment by bulldog98** [comment]
@zakkak I can attach Idea to that build process, but I'm not finding how to add the svm.src.zip to sources I can find, not sure how to do that.

**Comment by zakkak** [comment]
@bulldog98 I don't know which IDEA you are using but if you are using IntelliJ IDEA, you need to open "Module settings" and select the "Dependencies" tab, click the `+` button and select the first option "JARs or Directories..." select the path  `/path/to/mandrel-java17-23.0.0.0-Final/lib/svm/builder` click OK and then OK again and you should be good to go.

Other IDEs should have similar ways to manually add a dependency.

**Comment by bulldog98** [comment]
> @bulldog98 I don't know which IDE you are using but if you are using IntelliJ IDEA, you need to open "Module settings" and select the "Dependencies" tab, click the `+` button and select the first option "JARs or Directories..." select the path `/path/to/mandrel-java17-23.0.0.0-Final/lib/svm/builder` click OK and then OK again and you should be good to go.

I'm using IntelliJ IDEA, I on save I get some error about "Source root 'some/path' is duplicated in module 'some-module-name'", I'll try to get that sorted and debug then, but not sure if I'll be able to do that today.

**Comment by bulldog98** [comment]
So I found the offenders, it was two kotlin data classes
```kotlin
@JvmRecord
data class SomeStuffWithFqdns(@JvmField val fqdn: String)
```
That were fired into an `Event<SomeStuffWithFqdns>` and referenced via a `@Observes`. As soon as I got rid of the `@JvmField` annotation it went through.
