### ISSUE TITLE
Make (some) build-time properties more flexible

### ISSUE THREAD

**Issue by pdolezal** [quarkusio/quarkus#34695]
### Description

There is a lot of configuration properties important for smooth integration in a deployment, for instance `quarkus.application.name`, `quarkus.http.non-application-root-path` and various properties related to metrics endpoints like `quarkus.micrometer.export.prometheus.path`. Unfortunately many of these properties are fixed at build time, which makes the integration unnecessarily inflexible.

In our particular case we have a deployment consisting of tens services implemented in a few different languages, but we strive to make them follow similar patterns like exposing metrics on the same path – this simplifies maintenance of the deployment a lot. Having the path in the confguration for all the components allows us to have fairly unified deployment templates and control such properties easily and with a unified metrics path we do not have to specify the metrics endpoint per service for Prometheus.

I wonder why these properties are fixed at build time anyway 🤔

### Implementation ideas

Make configuration properties that affect integration with other components actually configurable for a deployment rather then fixed at build time.

If fixing a property in build time brings significant benefits, it might be worth providing a general mechanism to specify if a property should be built-time or not. For instance, it might be provided as another (built-time) property like this, which would make `quarkus.application.name` not fixed at build time:

```
%%config.quarkus.application.name=runtime
```

**Comment by geoand** [comment]
> In our particular case we have a deployment consisting of tens services implemented in a few different languages, but we strive to make them follow similar patterns like exposing metrics on the same path – this simplifies maintenance of the deployment a lot. Having the path in the confguration for all the components allows us to have fairly unified deployment templates and control such properties easily and with a unified metrics path we do not have to specify the metrics endpoint per service for Prometheus.

I didn't get how having build time properties is a problem for this approach

> I wonder why these properties are fixed at build time anyway

Because it enables us to make various decisions at build time.

**Comment by radcortez** [comment]
There are no plans to change the build time configuration.
