### ISSUE TITLE
Ignored projects also ask about build analytics

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#34703]
When playing with an app that is ignored by build analytics for the first time, typically playing with a quickstart, we are asking the user if they want to enable build analytics. 

If they say yes, we display a message saying build analytics will be ignored. 

So first I thing we shouldn’t ask the user about build analytics when they’re playing with an ignored project: we don’t want to bother a user exploring Quarkus for the first time with this. Especially when we are not actually collecting data. 

Secondly, I think we shouldn’t log anything when build analytics is ignored for a project. The user really doesn’t care about it. And when I say that, I mean in all cases: even if he has enabled build analytics, telling the user this particular project won’t send any build time analytics has very little value and can be confusing. 

/cc @brunobat @maxandersen

**Comment by maxandersen** [comment]
The second part of This issue i believe is already handled in recent fixes. 

The first part - isnt it better we just ask and record the answer. Rather than we ask This when the user decides to do a real project and it then could be perceived as we are detecting more than we actually do ?

**Comment by brunobat** [comment]
We could, in theory not ask if the group id is being blocked... But it complicates the message, like Max has mentioned. 
In relation to the logs, I believe Guillaume is mentioning the analytics will be ignored one... That has not been tweaked and I'll create a PR.
