### ISSUE TITLE
OpenAPI generation content-type mismatch

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34700]
### Describe the bug

Let's consider the following endpoint (using spring compatibility, but it should not matter):

```java
    @GetMapping("/hello")
    public String hello() {
        return "hello world";
    }
```

The generated OpenAPI document has the following content:

```yaml
---
openapi: 3.0.3
info:
  title: fortune-demo API
  version: 1.0.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Hello Controller
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic

```

Two issues:

1. I didn't setup anything related to security - so why it's there?
2. the content type is wrong, it should be plain text in this case

(2) leads to be unable to use the Swagger UI as it gets a 405 HTTP response. 

### Expected behavior

It should provide the right content type and no security description.

### Actual behavior

See description.

**Comment by manofthepeace** [comment]
sorry for the ping; @MikeEdgar @phillip-kruger  would be nice if that could be looked into. This issue is still present in quarkus 3.4.1

**Comment by phillip-kruger** [comment]
I think the default content type is json ? Or is this just for jaxrs? @geoand ?

**Comment by phillip-kruger** [comment]
I'll have a look at this a.s.a.p

**Comment by geoand** [comment]
It's json in Quarkus when the return type is a POJO

**Comment by phillip-kruger** [comment]
Right, so the content type is correct even when using spring API we do this . The security is an issue though, I'll look at that

**Comment by phillip-kruger** [comment]
O wait, only when pojo, not string. So this is an issue? Might event be an issue in jaxrs?

**Comment by phillip-kruger** [comment]
This is also an issue for jax-rs. I am looking at a fix

**Comment by rsvoboda** [comment]
@cescoffier @phillip-kruger what about `Uni<String>`? Should it be treated as JSON or text?

**Comment by phillip-kruger** [comment]
Probably yes. Same for Optional I guess

**Comment by rsvoboda** [comment]
> Probably yes

Yes for JSON?

**Comment by phillip-kruger** [comment]
Sorry, no I mean text.

**Comment by rsvoboda** [comment]
It's JSON now ... Will you create a PR to adjust that?

**Comment by phillip-kruger** [comment]
Yes I will.
