### ISSUE TITLE
Interception and mutating transactions doesn't work in Quarkus 3

### ISSUE THREAD

**Issue by StanislavMakhrov** [quarkusio/quarkus#34711]
I have a problem with adding SQL command execution interceptor for adding custom SQL command on every method with my annotation. It was worked in Quarkus 2.

What am I doing and why do I need it?
I use multiregional AWS Aurora DB with one master instance in USW2 region and slave instance in EUC1 according to https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding.html
Slave instances (as I have in EUC1) region prohibited to perform write sql commands. But if will be performed the following command before SQL commands then transaction will be forwarded automatically to master region (USW2, which is able to perform write commands):

```
SET aurora_replica_read_consistency = 'EVENTUAL'
```

If I do it in console manually - all works.

If I do it via quarkus via following interceptor, it doesn't work:

```
package com.test.someapi.interceptors;

import com.test.someapi.annotations.ReactiveAuroraWriteForwarding;
import io.smallrye.mutiny.Uni;
import io.smallrye.mutiny.unchecked.Unchecked;
import jakarta.annotation.Priority;
import jakarta.inject.Inject;
import jakarta.interceptor.AroundInvoke;
import jakarta.interceptor.Interceptor;
import jakarta.interceptor.InvocationContext;

@Priority(100)
@ReactiveAuroraWriteForwarding
@Interceptor
public class AuroraWriteForwardingInterceptor {

    private static final String SET_AURORA_READ_CONSISTENCY_TEMPLATE = "SET aurora_replica_read_consistency = '%s'";

    @Inject
    io.vertx.mutiny.mysqlclient.MySQLPool client;

    @AroundInvoke
    Object writeForwardingInvocation(InvocationContext ic)throws Exception {
        Class<?> returnType = ic.getMethod().getReturnType();

        if(returnType == Uni.class){
            ReactiveAuroraWriteForwarding annotation = ic.getMethod().getAnnotation(ReactiveAuroraWriteForwarding.class);
            String setAuroraReadConsistencyQuery = String.format(SET_AURORA_READ_CONSISTENCY_TEMPLATE, annotation.auroraReplicaReadConsistency());
            return client.withTransaction(conn ->
                            conn.query(setAuroraReadConsistencyQuery).execute()
                    .onFailure().recoverWithNull()
                    .onItem().transformToUni(Unchecked.function(item -> {
                        try {
                            return (Uni<?>) ic.proceed();
                        } catch (Exception ex) {
                            throw new RuntimeException(ex);
                        }
            })));
        }
        return ic.proceed();
    }

}
```

Interceptor above works via annotation @ReactiveAuroraWriteForwarding. Interface which was created.
```
@Inherited
@InterceptorBinding
@Retention(RUNTIME)
@Target({METHOD, TYPE})
public @interface ReactiveAuroraWriteForwarding {
    @Nonbinding AuroraReplicaReadConsistency auroraReplicaReadConsistency() default SESSION;
}
```

So if I add annotation @ReactiveAuroraWriteForwarding to any method which doing persisting in DB in Quarkus 2, then it was worked. But in Quarkus 3 it doesn't work - I even don't see in logs that 
```
SET aurora_replica_read_consistency = 'EVENTUAL' 
```
was executed.

Maybe smth was changed in Quarkus 3 and there is another way to add custom command like 'SET aurora_replica_read_consistency = 'EVENTUAL' ' before commands for data persistance?

### Expected behavior

I see in logs:
```
Hibernate: 
     SET aurora_replica_read_consistency = 'EVENTUAL' 
```
Then sql commands for data persistance.

### Actual behavior

I see in logs only sql commands for data persistance.

### Output of `uname -a` or `ver`

Darwin MYPCNAME 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17.0.4+8-jvmci-22.2-b06

### Quarkus version or git rev

3.0.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by Sanne** [comment]
Could you clarify why you'd expect to see something logged by Hibernate when you're not using Hibernate?

**Comment by geoand** [comment]
Closing for lack of feedback
