### ISSUE TITLE
response body error when use brotli as compression encode

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#34719]
### Describe the bug

When I use brotli to compress response body,the response body can't be decompressed.

I  create `CompresssionHttpServerCustomizer` to enable brotli,the way is from [vertx_http_compression_algorithms](https://vertx.io/docs/vertx-core/java/#_http_compression_algorithms)

```java
    @Override
    public void customizeHttpServer(HttpServerOptions options) {
        options.addCompressor(getBrotliOptions(compressionLevel));
        options.addCompressor(getGzipOptions(compressionLevel));
    }
```

### Expected behavior

brotli compression work!

### Actual behavior

response body can't be decompred,it failed!

### How to Reproduce?

[quarkus-br.zip](https://github.com/quarkusio/quarkus/files/12036149/quarkus-br.zip)

### Output of `uname -a` or `ver`

mac-arm and x86

### Output of `java -version`

17.0.5

### Quarkus version or git rev

2.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by geoand** [comment]
Have you tried with Quarkus 3.2.0.Final?

**Comment by naah69** [comment]
> Have you tried with Quarkus 3.2.0.Final?

yes,3.2.0.Final had the same problem.

**Comment by naah69** [comment]
> Have you tried with Quarkus 3.2.0.Final?
@geoand 
Is there any progress？

**Comment by geoand** [comment]
Nope, I have a very long list of things to do

**Comment by geoand** [comment]
maybe @cescoffier knows immediately what the problem is

**Comment by cescoffier** [comment]
In native mode we disable Brotli (on purpose). However in JVM mode it should work.

**Comment by naah69** [comment]
> In native mode we disable Brotli (on purpose). However in JVM mode it should work.在本机模式下，我们（故意）禁用 Brotli。但是在 JVM 模式下它应该可以工作。

we use JVM mode,but it didn't work.

the below is my code.Can u help me to check the code is right？

[quarkus2-br.zip](https://github.com/quarkusio/quarkus/files/12036149/quarkus-br.zip)

[quarkus3-br.zip](https://github.com/quarkusio/quarkus/files/12038097/quarkus3-br.zip)

**Comment by cescoffier** [comment]
Our Brotli support only works up to 8192 (1024*8) bytes. For responses bigger than this, it corrupts the output.
It does not seem to happen when using Vert.x directly. So, it might be something we do somewhere.

CC @vietj @franz1981

**Comment by cescoffier** [comment]
I believe it's related to https://github.com/eclipse-vertx/vert.x/issues/4567.
