### ISSUE TITLE
CORS regex allowing more origins than expected

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#34718]
### Describe the bug

Regex CORS is allowing some scenarios that should be blocked

Regex: `https:\/\/(?:[a-z0-9\-]+\.)*domain\.com`

### Expected behavior

Request should fail when non valid domain is sent on origin header

Invalid origins: `https://wwwdomain.com` or `https://asdfdomain.com`

Valid origins: `https://www.domain.com` or `https://asdf.domain.com`

### Actual behavior

Request is with `https://wwwdomain.com` origin is accepted and processed.

![image](https://github.com/quarkusio/quarkus/assets/405347/393e8bc3-cc33-4d09-9847-03f76aaf9b30)

### How to Reproduce?

`application.properties:`:
```
quarkus.http.cors=true
quarkus.http.cors.methods=POST
quarkus.http.cors.origins=/https:\\/\\/(?:[a-z0-9\\-]+\\.)*domain\\.com/
```

### Output of `java -version`

openjdk 17.0.7

### Quarkus version or git rev

2.16.8.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

### Additional information

It works as expected on [Regex101](https://regex101.com/) with `https:\/\/(?:[a-z0-9\-]+\.)*domain\.com`
Marks `https://asdfdomain.com` as no match.

**Comment by sberyozkin** [comment]
@gian1200 Can you confirm Java regex matcher also fails to match `https://asdfdomain.com` ?

Listing specific origins individually is always safe if the regex does not work

**Comment by sberyozkin** [comment]
Regex is correct, so there is a bug. I'll fix it, but better avoid regex anyway

**Comment by gian1200** [comment]
Tanks for answering. I'll check with my code, but if that's the case, then there is a bug in the documentation, the docs only uses 2. Is it only for dots?

![image](https://github.com/quarkusio/quarkus/assets/405347/df588149-2d15-4f3d-82cd-8d5e6c17b217)

At least should say when (or why) it should be 4 backslashes for dots. 

https://quarkus.io/guides/http-reference#cors-filter

**Comment by gsmet** [comment]
@sberyozkin is the 4 backward slash escaping actually documented somewhere? Also it doesn't feel natural at all? Is it something that is commonly used?

I will reopen this issue for now as I want us to clarify this.

**Comment by sberyozkin** [comment]
Hi @gian1200 @gsmet I haven't worked on this feature, but giving 4 slashes actually stops `.` from treated as a reserved regex character, don't ask me why please :-), with 2 slashes it does not. 
I suppose https://stackoverflow.com/questions/54395891/why-four-backslashes-in-the-regular-expression provides a good enough explanation:
```
\\\\d is backslash-escaping-backslash, twice, +d, probably escaping the command line if you're using a shell, or if you have to pass the string through system or rsh or something
```

so in this case, when it is coming from properties, as opposed to from Java code, it has to be 4 slashes

I'm happy to fix the docs though to set 4 slashes, I missed that example

**Comment by SebastianSaipSenacor** [comment]
Hi @sberyozkin, sorry for commenting on such an old issue, but isn't the documentation on https://quarkus.io/guides/security-cors wrong, then?
Shouldn't it be 
```
%dev.quarkus.http.cors.origins=/\\.*/
```
As `\\.` translates to metadata `.`, matching any char?

**Comment by The-Funk** [comment]
I'm having difficulties getting the escaping correct when setting up CORS origins header as well. For now I don't need it, so I just set * because all of my endpoints are public anyway, but eventually I'll need to figure out the appropriate escape characters.

Are the examples correct now?

**Comment by alekennedy** [comment]
Is there any example of how to do the same config but for application.yml file? I am trying to apply regex in the CORS origins values.

**Comment by frits-v** [comment]
@alekennedy (or anyone that ends up here from google), the yaml config source does not require any additional escaping in regex, just the usual single escaping for literal meta characters. For example:
```yaml
quarkus:
  http:
    cors:
      enabled: true
      origins:
      - http://localhost:9000 # plain
      - /.*/ # regex match any
      - /^https:\/\/(?:[a-z0-9\-]+\.)*example.com$/ # regex match any example.com or any level of subdomain example.com (only the default protocol port here)
```
