### ISSUE TITLE
Unable to prevent the CLI from creating dockerfiles

### ISSUE THREAD

**Issue by bogedal** [quarkusio/quarkus#34721]
### Describe the bug

When running the `quarkus create app` it creates dockerfiles by default in `src\main\docker`

I can see that the `create` command honors the --no-code and --no-wrapper, but doesn't support --no-dockerfiles,

In the code behind the `create`  command has a property called noDockerfiles.
I have tried with `quarkus create app -Dcodegen.no-dockerfiles` but the docker files are still created.

### Expected behavior

The `src\main\docker` folder and files are not created with using --no-dockerfiles or using -Dcodegen.no-dockerfiles

### Actual behavior

The docker folder and files are created

### How to Reproduce?

Run the create app noDockerApp --no-wrapper -P io.quarkus:quarkus-universe-bom:3.2.0.Final -Dcodegen.no-dockerfiles

and see that the docker folder is created with files but the wrapper is not created

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22621 BD-PF4B4F7W 3.3.6-bec3d608-341.x86_64 2023-02-22 08:29 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2

**Comment by maxandersen** [comment]
@ia3andy I see `codegen.no-dockerfiles` in code but couldn't obviously spot how to activate it. Is there a magic trick beyond -Dcodegen.no-dockerfiles?

**Comment by bogedal** [comment]
Added a PR for support of --no-dockerfiles
https://github.com/quarkusio/quarkus/pull/34734

**Comment by bogedal** [comment]
My PR has been merged, so closing this issue
