### ISSUE TITLE
`ID token verification has failed: null` after upgrade from 3.1.0 -> 3.2.0

### ISSUE THREAD

**Issue by jteemsfi** [quarkusio/quarkus#34732]
### Describe the bug

We use Azure OIDC for an internal application that is not configured to be multi-tenant in Azure. This works in `3.1.0` but after running `quarkus upgrade` to upgrade to `3.2.0` we get an error during the auth handshake.

#### Redacted config snippet:

```
quarkus.oidc.provider=microsoft
quarkus.oidc.auth-server-url=https://login.microsoftonline.com/REDACTED-GUID
quarkus.oidc.application-type=web-app
quarkus.oidc.client-id=REDACTED-GUID
quarkus.oidc.credentials.secret=REDACTED_SECRET
quarkus.oidc.authentication.java-script-auto-redirect=false
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.authentication.scopes=profile
quarkus.oidc.roles.role-claim-path=roles
```

### Expected behavior

On version `3.1.0` I get:
```
2023-07-13 12:45:20,735 DEBUG [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-2) ID token has been verified, removing the existing session cookie if any and creating a new one
```

### Actual behavior

```
2023-07-13 12:40:28,750 ERROR [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-2) ID token verification has failed: null
2023-07-13 12:40:28,753 DEBUG [io.qua.res.run.AuthenticationCompletionExceptionMapper] (executor-thread-1) Authentication has failed, returning HTTP status 401
```

### Output of `java -version`

openjdk version "20.0.1" 2023-04-18 OpenJDK Runtime Environment Homebrew (build 20.0.1) OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)

### Quarkus version or git rev

3.2.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /usr/local/Cellar/maven/3.9.3/libexec Java version: 20.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.4.1", arch: "x86_64", family: "mac"

**Comment by sberyozkin** [comment]
@jteemsfi Can you please remove `quarkus.oidc.provider=microsoft` and see if it helps since you override key properties  ? This provider now enables token header preprocessing  which I verified but in your setup in may be causing side effects. 
Or reset it to an empty value.
If that does not work, please create a test tenant and  share a test id token.

**Comment by jteemsfi** [comment]
That did it! Thanks!
