### ISSUE TITLE
Show the active profile(s) on the console

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#34747]
### Description

1) Whenever the application starts, mvn tests are running on the console, or a one to many tests run in my IDE, I want to first see the profile(s) that are currently active. 

2) That said - it seems  - public static String getActiveProfile() was @Deprecated.
  /**
     * @deprecated This method is not suited to multiple profiles, because it returns a single string. Please use
     *             {@link ConfigUtils#getProfiles()} instead, which returns a List of profiles.
     */
   
   ConfigUtils#getProfiles() doesn't really seem to help here - AFAIK it returns a list of all possible profiles, and then for each profile, we need to ask if it is currently active. Why not directly returning a list of active profiles?

**Comment by gsmet** [comment]
Given how `isProfileActive()` is implemented, `getProfiles()` should only return the active ones or we have a bug.

I will close this for now. If `getProfiles()` is actually buggy, please reopen it.
