### ISSUE TITLE
Error: response status is 403 for simple POST REST API

### ISSUE THREAD

**Issue by poldinik** [quarkusio/quarkus#34741]
### Describe the bug

Implementing a simple POST API like this with Quarkus 2.16.5.Final | 2.16.8.Final

```
@Path("/onboarding")
@RequestScoped
public class OnboardingApi {

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/send")
    public Response onboarding(OnboardingRequest onboardingRequest){
        return Response.ok().status(Response.Status.NOT_IMPLEMENTED).build();
    }
}
```

The response inside swagger embedded inside Chrome/Safari returns

`403 Undocumented Error: response status is 403` when deployed inside container within a kubernetes cluster with ingress configuration. On localhost it works

If I rollback to Quarkus 2.9.2.Final it returns 200 OK like expected

The list of dependencies 

```
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-qute</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mailer</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mindrot</groupId>
      <artifactId>jbcrypt</artifactId>
      <version>0.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>5.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>5.2.0</version>
    </dependency>
    <dependency>
      <groupId>io.vavr</groupId>
      <artifactId>vavr</artifactId>
      <version>0.10.4</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.24</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-mysql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-scheduler</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-h2</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

### Expected behavior

200 OK Response

### Actual behavior

403 Http Status

### Output of `java -version`

openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: /opt/homebrew/Cellar/maven/3.9.2/libexec
Java version: 11.0.18, vendor: Amazon.com Inc., runtime: /Users/lorenzovannucchi/.sdkman/candidates/java/11.0.18-amzn
Default locale: en_IT, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "aarch64", family: "mac"

Dockerfile

FROM registry.access.redhat.com/ubi8/openjdk-11:1.14

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

_No response_

**Comment by sberyozkin** [comment]
@poldinik Is CORS enabled in your setup ?

**Comment by poldinik** [comment]
@sberyozkin Yes, there is a quarkus.http.cors=true. I have set to false, and now it is working. 
Having GET 200 and POST 304 when deployed on server exposed online it is the expected result?

**Comment by sberyozkin** [comment]
@poldinik The reason it was working for you only with `quarkus.http.cors=true` before was because Quarkus was enabling a wildcard Origin support by default - which did not give users who may be relying on CORS any real protection. 
Now, if you do prefer a wildcard origin support, you have to have:

```
quarkus.http.cors=true
quarkus.http.cors.origins=*
```

This is in migration notes: 

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16#no-wildcard-origin-support-by-default-for-cors-filter

(Wildcard is shown as a reg expression there, but just `*` will work)

Can you retry please ?

**Comment by sberyozkin** [comment]
@poldinik Note we have an issue related to `*` not recognized in a multi-cluster setup: #34669.

But right now I hope it is not related to your setup - so please confirm adding a wildcard works for you, then we can close this issue - and please watch #34669 afterwards

**Comment by poldinik** [comment]
@sberyozkin Hi, I have just tried with 

```
quarkus.http.cors=true
quarkus.http.cors.origins=*
```

and it is working --> 200 OK

**Comment by sberyozkin** [comment]
Thanks @poldinik

**Comment by poldinik** [comment]
@sberyozkin Thank you very much
