### ISSUE TITLE
Quarkus Redis Cluster mode gives java.lang.NullPointerException when run multiple keyCommands

### ISSUE THREAD

**Issue by ranjannraut** [quarkusio/quarkus#34742]
### Describe the bug

Configuration : 
quarkus.redis.hosts=rediss://${xyz}:6379
quarkus.redis.client-type=cluster
quarkus.redis.replicas=share
quarkus.redis.password=${passwd}
quarkus.redis.max-pool-size=100
quarkus.redis.max-pool-waiting=200
quarkus.redis.reconnect-attempts=3
quarkus.redis.reconnect-interval=3S
quarkus.redis.pool-cleaner-interval=30S

ErrorLine : 
`for (String item : items) {
				deleteTimer.record(() -> keyCommands.del(item));
			}`
Error PFA :
[redis-vertx-NPE.txt](https://github.com/quarkusio/quarkus/files/12044614/redis-vertx-NPE.txt)

### Output of `java -version`

11

### Quarkus version or git rev

2.16.4

**Comment by gsmet** [comment]
Could you assemble together a reproducer? And also try with the latest 3.2.1.Final?

**Comment by cescoffier** [comment]
Yes, we need a reproducer. It might be due to the ´cluster' type.

**Comment by geoand** [comment]
Closing as we never got a reproducer
