### ISSUE TITLE
Updating to Quarkus 3 breaks shared library Testing

### ISSUE THREAD

**Issue by kono94** [quarkusio/quarkus#34755]
### Describe the bug

Previously, with Quarkus 2.16, running `mvn test` did work when using maven dependencies that are Java wrapper for third-party .so libraries located e.g. /opt/ and that dynamically load those libraries at runtime. As well as using the License-Server-Client that is installed on the host. (mvn quarkus:test did not work tho, crashing the JVM tho)

```
 <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>2.16.5.Final</quarkus.platform.version>
      <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
```

It starts the  @QuarkusTest and the Testcontainers with base image **testcontainers/ryuk:0.3.4**.

After updating to Quarkus 3.2 (or any 3.X version) the same tests are not working anymore with a wide range of errors...   
```
 <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>3.2.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.1.2</surefire-plugin.version>
```

Maybe because the base-image of the testcontainer change to` testcontainers/ryuk:0.5.1`. **How can I set a custom base image for tests** (not the jib build stuff, that works fine)?

### Expected behavior

The tests are running fine and the third-party .so libraries are loaded correctly during runtime.

### Actual behavior

Either, the JVM is crashing with a SIGSEGV error when calling `mvn quarkus:test`. 

When running `mvn test`, I receive the folllowing error:
 `Corrupted channel by directly writing to native stream in forked JVM`
 
 When configuring surefire to `<forkCount>0<forkCount>`, I recive:
` Runtime java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)`

### Output of `uname -a` or `ver`

Linux CDE1103 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2) OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by gsmet** [comment]
I think you will have to put together a small reproducer for us to understand what’s going on.

**Comment by kono94** [comment]
This will be close to impossible. However, I found a way to use a custom base image for the testcontainer, without success. I am gonna close this bug and open another one, focusing on the `java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List` error
