### ISSUE TITLE
OpenApi does not show all methods when used in conjunction with @EndpointDisabled in native

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#34765]
### Describe the bug

Note: the root cause may be; https://github.com/quarkusio/quarkus/issues/34738, but it is weird that it still shows a method out of 2 in the same class when disabled by default.

When using `@EndpointDisabled` and having it disabled by default, OpenApi shows 1 of the 2 methods in the class whether the property to enable it is set or not.

tested with native build.

### Expected behavior

GreetingResource has 2 methods

When EndpointDisabled is active, openApi  should not show any methods for the class
When EndpointDisabled is not active, OpenApi should show both methods

### Actual behavior

starting the app with
`./target/openapi-resteasy-1.0.0-SNAPSHOT-runner` or `HELLO_ENABLED=true ./target/openapi-resteasy-1.0.0-SNAPSHOT-runner` 

http://localhost:8080/q/swagger-ui/ will show 1 of the 2 methods

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-endpointdisabled-openapi

Steps to reproduce:
1- compile a native application
2- run the app (endpointdisabled is active by default)
3- check the swagger-ui one of the method will be shown, not the other, none should actually be shown
4- run the app with `HELLO_ENABLED=true`
5- check swagger-ui, same only method will be shown, but both should.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### GraalVM version (if different from Java)

graalvm-jdk-17

### Quarkus version or git rev

3.2.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.1

**Comment by gsmet** [comment]
I'm pretty sure OpenAPI has no idea about what `@EndpointDisabled` is doing but I will let the people pinged here confirm ^.

**Comment by manofthepeace** [comment]
> I'm pretty sure OpenAPI has no idea about what `@EndpointDisabled` is doing but I will let the people pinged here confirm ^.

I thought it could relate to that; https://github.com/quarkusio/quarkus/pull/34313. Before that PR I was using a `OASFilter` to remove them manually.

**Comment by MikeEdgar** [comment]
The issue here appears to be related to the paths being slightly different between RestEasy Reactive and the OpenAPI document. RestEasy has a trailing `/` which prevents a match against the path. I'll open a PR to correct it.
