### ISSUE TITLE
Observability for HTTP Server - when http route is / then attribute 'http.route' is not sent

### ISSUE THREAD

**Issue by arik-dig** [quarkusio/quarkus#34778]
### Describe the bug

HTTP Server span does not contain required attribute named `http.route` in case the route is `/` only
seeing it for reactive routes, but maybe it happens on non-reactive as well

### Expected behavior

according to [OTEL semantic conventions of HTTP Server](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-server-semantic-conventions) the attribute `http.route` is required

### Actual behavior

the attribute `http.route` is not set , when the server route is `/` only

### How to Reproduce?

1) I open the application reactive-routes-quickstart from quickstarts:
https://github.com/quarkusio/quarkus-quickstarts/tree/main/reactive-routes-quickstart

2) I added OpenTelemetry dependency for observabilty
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>
```

3) I ran the application

4) I browsed to http://localhost:8080/ and got "hello"
I see the trace (via Jaeger) and it missing attribute `http.route`

![image](https://github.com/quarkusio/quarkus/assets/104715391/d4a7352b-5a05-40ba-bacc-f278e0c0f0ad)

5) I browsed to http://localhost:8080/hello?name=john and got "hello jon"
I see the trace and it has attribute `http.route`

![image](https://github.com/quarkusio/quarkus/assets/104715391/83c3b388-cf0e-4eb3-824b-88f2621f2bc7)

### Output of `uname -a` or `ver`

Darwin Ariks-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/34886 takes care of the issue

**Comment by radcortez** [comment]
> according to [OTEL semantic conventions of HTTP Server](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-server-semantic-conventions) the attribute `http.route` is required

While we can provide the route for this case, I would like to clarify that it may not always be the case, so it is not exactly required. It is only required if available.
