### ISSUE TITLE
[Rest Client Reactvie] Content Negotiation for Text/Plain

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34777]
### Describe the bug

I have defined the following method in rest client interface.

```java
@Path("count")
@GET
@Produces(MediaType.TEXT_PLAIN)
Uni<Long> countAllPosts(@QueryParam("q") String q);
```

And in a test I used Wiremock to serve the response.

```java
@Test
void countAllPosts() throws Throwable {
    var url = "/posts/count?q=";
    stubFor(
            get(url)
                    //.withHeader("Accept", containing("text/plain"))
                    .willReturn(
                            aResponse()
                                    .withHeader("Content-Type", "text/plain")
                                    .withBody("10")
                                    .withStatus(200)
                    )
    );

    var count = VertxContextSupport.subscribeAndAwait(() ->
            client.countAllPosts("")
                    .onItem().invoke(c -> LOGGER.log(Level.INFO, "count is: " + c))
                    .onFailure().invoke(error -> LOGGER.log(Level.INFO, "error: " + error.getMessage()))
    );

    assertThat(count).isEqualTo(10L);

    verify(
            getRequestedFor(urlEqualTo(url))
                    .withHeader("Accept", containing("text/plain"))// it is text/plain;charset=UTF-8
    );
}
```

### Expected behavior

The produces type(text/plain) in rest client should match request header `Accept: text/plain` firstly.

**The classic rest client is working as expected.**, check https://github.com/hantsy/quarkus-sandbox/blob/master/restclient-kotlin/src/test/kotlin/com/example/PostResourceClientTest.kt#L80

### Actual behavior

But the WireMock request header `Accept` must include a `charset=UTF8`to  match the request from the rest client request.

### How to Reproduce?

1. clone https://github.com/hantsy/quarkus-sandbox/tree/master/restclient-reactive
2. Modify the above `containing` to `equalTo`
3. run `PostResourceClientTest`

### Output of `uname -a` or `ver`

Windows 10 Pro

### Output of `java -version`

17

### GraalVM version (if different from Java)

not used 

### Quarkus version or git rev

3.2.0.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by geoand** [comment]
So your issue is that `;charset=UTF-8` is appended to the type?

**Comment by hantsy** [comment]
> So your issue is that `;charset=UTF-8` is appended to the type?

yes, it includes a `charset`.

**Comment by geoand** [comment]
We do that on purpose

**Comment by hantsy** [comment]
> We do that on purpose

Why the classic blocking API does not add charset?

Why `applicaiton/json` content type does not add it?

**Comment by geoand** [comment]
See 60aa2b7db8cbec25722f8cfbc609cc5bc3d3792f
