### ISSUE TITLE
Use distinct SNAPSHOT versions for LTS branches

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#34788]
### Description

https://github.com/quarkusio/quarkus/pull/30860 changed the version for the 2.16 branch from the generic `999-SNAPSHOT` to the more specific `2.16.999-SNAPSHOT`.

As discussed in https://github.com/graalvm/mandrel/issues/501 this change significantly helps in pre-release testing of [Quarkus LTS](https://quarkus.io/blog/lts-releases/) branches (e.g. `3.2`), since it allows the testing harness to adjust based on the Quarkus branch being tested.

### Implementation ideas

Ideally we would need a script that will automatically adjust the version whenever a new version branch is created based on `main`.

Manual attempts to update older branches didn't go that well, see https://github.com/quarkusio/quarkus/pull/33822 and https://github.com/quarkusio/quarkus/pull/33823

Using `udpate-version.sh` also doesn't seem enough, as can be seen in https://github.com/zakkak/quarkus/actions/runs/5575223648 where https://github.com/zakkak/quarkus/tree/2023-07-17-prefix-SNAPSHOT-version is tested.

**Comment by geoand** [comment]
cc @gsmet

**Comment by zakkak** [comment]
Known issues so far (when using `update-version.sh`):

1. The Quickstarts Compilation CI job fails because quickstarts uses `999-SNAPSHOT`, we (`update-version.sh` ?) needs to patch the job in order to run the quickstarts with the prefixed SNAPSHOT version (e.g. 3.2.999-SNAPSHOT)
2. Microprofile TCK `RESTEasy Reactive failed in the CI but it passes on my machine when run alone (if I run it with the rest of the tcks it fails, it doesn't look version-specific)
3. Gradle tests JDK 11 on windows are failing (but I see similar failures in other branches so probably unrelated?)

**Comment by zakkak** [comment]
Issue resolved for 3.2 branch in https://github.com/quarkusio/quarkus/pull/34847

Keeping open for 2.13 branch.

**Comment by gsmet** [comment]
@zakkak I have 2.13 in mind. CI was too unstable to be sure we didn't break anything but I think we fixed it (except for some Gradle failures). I will recreate the 2.13 PR tomorrow on latest 2.13 once the backports are in.

**Comment by zakkak** [comment]
2.13 PR merged https://github.com/quarkusio/quarkus/pull/38259 as well.

Thanks a lot @gsmet !
