### ISSUE TITLE
Quarkus Maven plugin is unable to resolve local deps when generating code tests

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#34787]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/34286 broke build of our tests with code test generation.

### Expected behavior

Quarkus Maven plugin should resolve artifacts from local repo. It worked with 3.1.3.Final.

### Actual behavior

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code-tests (default) on project examples-quarkus-helm: Quarkus code generation phase has failed: Failed to bootstrap application in TEST mode: Failed to resolve dependencies for io.quarkus.qe:examples-quarkus-helm:jar:1.3.1.Beta21-SNAPSHOT: Failed to collect dependencies at io.quarkus.qe:quarkus-test-core:jar:1.3.1.Beta21-SNAPSHOT: Failed to read artifact descriptor for io.quarkus.qe:quarkus-test-core:jar:1.3.1.Beta21-SNAPSHOT: Could not transfer artifact io.quarkus.qe:quarkus-test-core:pom:1.3.1.Beta21-SNAPSHOT from/to gradle-official-repository (https://repo.gradle.org/gradle/libs-releases-local/): transfer failed for https://repo.gradle.org/gradle/libs-releases-local/io/quarkus/qe/quarkus-test-core/1.3.1.Beta21-SNAPSHOT/quarkus-test-core-1.3.1.Beta21-SNAPSHOT.pom, status: 409 Conflict -> [Help 1]
```

### How to Reproduce?

Reproducer:

```bash
git clone git@github.com:quarkus-qe/quarkus-test-framework.git
cd quarkus-test-framework
# only for repeated steps, it is important to have empty .m2 QE artifacts
sudo rm ~/.m2/repository/io/quarkus/qe -R
mvn -V -B -s .github/mvn-settings.xml verify -Pframework,examples -Dvalidate-format -DskipTests -DskipITs
```

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### GraalVM version (if different from Java)

22.3.2

### Quarkus version or git rev

999-SNAPSHOT, 3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 and 3.9.3

**Comment by aloubyansky** [comment]
It's due to the default workspace loader not taking into account modules being configured in profiles.
A quick workaround would be to add `-Dquarkus.bootstrap.effective-model-builder` to the command line.

**Comment by michalvavrik** [comment]
> It's due to the default workspace loader not taking into account modules being configured in profiles.
A quick workaround would be to add -Dquarkus.bootstrap.effective-model-builder to the command line.

That did a trick, thanks!
