### ISSUE TITLE
Unable to override ~/.testcontainers.properties with a custom file in src/test/resources

### ISSUE THREAD

**Issue by twheeler128** [quarkusio/quarkus#34797]
### Describe the bug

According to my reading of the testcontainers documentation at https://java.testcontainers.org/features/configuration/, I should be able to provide a custom `src/test/resources/testcontainers.properties` (no leading 'dot'!) to set `testcontainers.reuse.enable=false`. I'm DoingThisWrong[tm] or it's not working correctly.

### Expected behavior

Expect that Quarkus will recreate a Postgres container as needed when running tests.

### Actual behavior

The `~/.testcontainers.properties` file, if it exists, takes precedence. If it does not exist, a new one is created and defaults to having `testcontainers.reuse.enable=true`.

### How to Reproduce?

1. Create a `src/test/resources/testcontainers.properties` containing `testcontainers.reuse.enable=false`. 
2. Run tests that use a Postgres container.

### Output of `uname -a` or `ver`

Darwin SWFT-XWVFJWXLG6 22.5.0 Darwin Kernel Version 22.5.0

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by geoand** [comment]
This seems to be done deliberately by testcontainers as `TestcontainersConfiguration#environmentSupportsReuse`  ends up calling `getEnvVarOrUserProperty` (as opposed to `getEnvVarOrProperty` which is the one that actually takes the user provided configuration file into account)
