### ISSUE TITLE
Getting error using value starting with $ in @ClientHeaderParam

### ISSUE THREAD

**Issue by nickhais** [quarkusio/quarkus#34796]
### Describe the bug

Once I run my Quarkus application in Docker  and trying to make a call using `MyApplicationRestClient` I am getting the error `failed java.lang.IllegalArgumentException: Failed to convert value for property ${myapp.client-header.auth.client.id} to String`. 

But if I run the same code directly in my IDE (Intelij IDEA) similar to `quarkus dev` command the same code works fine and I am able to get response.

I am using 
```xml 
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-rest-client-reactive-jackson</artifactId>
	<version>3.0.3.Final</version>
</dependency>
```

And I followed this tutorial implementing my code https://quarkus.io/guides/rest-client-reactive.

Here is a part of my `MyApplicationRestClient`
```java 
@Path("")
@RegisterRestClient(configKey = "myapp-api")
@RegisterClientHeaders(MyApplicationClientHeadersFactory.class)
@ClientHeaderParam(name = "Client-ID", value = "${myapp.client-header.auth.client.id}")
public interface MyApplicationRestClient
```

### Output of `java -version`

1.8.0_161

**Comment by geoand** [comment]
This means you that the property is not set when at runtime. 
You'll need to ensure that the property is properly set for the running container

**Comment by geoand** [comment]
> And sorry for raising this bug

No problem
