### ISSUE TITLE
Run MicroProfile TCKs

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#348]
Depends on https://github.com/jbossas/protean-shamrock/issues/206.

- [x] Config (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-config)
- [x] Health (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-health)
- [x] Rest Client (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-rest-client)
- [x] OpenAPI (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-openapi)
- [ ] Fault Tolerance
- [x] Metrics (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-metrics)
- [x] JWT (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-jwt)
- [x] OpenTracing (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-opentracing)
- [x] Reactive Messaging (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-reactive-messaging)
- [x] Context Propagation (https://github.com/quarkusio/quarkus/tree/master/tcks/microprofile-context-propagation)

**Comment by kenfinnigan** [comment]
MP JWT TCK currently blocked by https://github.com/smallrye/smallrye-jwt/issues/129

**Comment by kenfinnigan** [comment]
@jmartisk will look at OpenTracing TCK
