### ISSUE TITLE
Cannot change the test profile for `@QuarkusIntegrationTest` tests

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#34810]
### Describe the bug

I have a `@QuarkusIntegrationTest`. I need to run this test under a different profile on CI - basically I want to use testcontainers/devservices for the integration test when running locally, but not have these start on CI because the build is already in a container (and provides the needed dependencies).

When I run `./gradlew quarkusIntTest -Dquarkus.test.profile=ci -Dquarkus.test.integration-test-profile=ci`

The application starts up with the `ci` profile, but the test itself runs under the `test` profile (checked by printing the value of `ConfigUtils.getProfiles()` at the start of my test).

This prevents me from running the test itself under different profiles.

### Expected behavior

I can change the test profile for `@QuarkusIntegrationTest`.

I (naively) expected `quarkus.test.integration-test-profile` to affect the profile of both the application and the test, whereas it just seems to affect the application meaning the test and application are running separate/disconnected profiles.

Failing that (if the ability to run the application and the test under different profiles is desired) then I would expect `quarkus.test.profile` to affect the profile the integration test itself runs under.

### Actual behavior

`@QuarkusIntegrationTest` tests always seems to run under the `test` profile, regardless of configuration applied.

### Output of `uname -a` or `ver`

Darwin Kernel Version 22.5.0

### Output of `java -version`

17.0.7

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by geoand** [comment]
So it's the application itself that needs to have a specific profile, not the test.

**Comment by josephearl** [comment]
Both, the application profile doesn't determine whether dev services are started or not (as far as I can gather).
Because it is possible to change the application profile.

**Comment by josephearl** [comment]
My bad - it turns out you can change the profile `@QuarkusIntegrationTest`s run under with `quarkus.test.profile`.

When using Gradle however you need something like:

```
quarkusIntTest {
  systemProperty 'quarkus.test.profile', System.getProperty('quarkus.test.profile') ?: 'test'
}
```

Otherwise the system property specified on the command line is not passed to the forked JVM used for running tests
