### ISSUE TITLE
Extension quarkus-amazon-lambda does not consume SQS payload correctly

### ISSUE THREAD

**Issue by debae** [quarkusio/quarkus#3481]
**Describe the bug**
When we invoke our Lambda with an SQS event payload we get the events but the records are null.

The code below can be used to see the problem

`
public class ExampleLambdaSqs implements RequestHandler<SQSEvent, Void> {

    private static final Logger LOG = Logger.getLogger(ExampleLambdaSqs.class);

    @Override
    public Void handleRequest(SQSEvent input, Context context) {
        LOG.info("SQS request received");
        LOG.info(input);    
        LOG.info(input.getRecords()); // This is null    
        return null;
    }
}
`

**Expected behavior**
The data within the Records field is correctly mapped to the records field of SQSEvent.

**Actual behavior**
The records field in SQSEvent remains null

**To Reproduce**
Invoke the lambda function with sam local via the following command

`
sam local invoke -e src/test/resources/event.json
`

The contents of this event.json is 

`
{
  "Records": [
    {
      "messageId": "c80e8021-a70a-42c7-a470-796e1186f753",
      "receiptHandle": "AQEBJQ+/u6NsnT5t8Q/VbVxgdUl4TMKZ5FqhksRdIQvLBhwNvADoBxYSOVeCBXdnS9P+erlTtwEALHsnBXynkfPLH3BOUqmgzP25U8kl8eHzq6RAlzrSOfTO8ox9dcp6GLmW33YjO3zkq5VRYyQlJgLCiAZUpY2D4UQcE5D1Vm8RoKfbE+xtVaOctYeINjaQJ1u3mWx9T7tork3uAlOe1uyFjCWU5aPX/1OHhWCGi2EPPZj6vchNqDOJC/Y2k1gkivqCjz1CZl6FlZ7UVPOx3AMoszPuOYZ+Nuqpx2uCE2MHTtMHD8PVjlsWirt56oUr6JPp9aRGo6bitPIOmi4dX0FmuMKD6u/JnuZCp+AXtJVTmSHS8IXt/twsKU7A+fiMK01NtD5msNgVPoe9JbFtlGwvTQ==",
      "body": "{ \"propertyName\": \"propertyValue\"}",
      "attributes": {
        "ApproximateReceiveCount": "3",
        "SentTimestamp": "1529104986221",
        "SenderId": "594035263019",
        "ApproximateFirstReceiveTimestamp": "1529104986230"
      },
      "messageAttributes": {},
      "md5OfBody": "9bb58f26192e4ba00f01e2e7b136bbd8",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:us-west-2:594035263019:QUEUE",
      "awsRegion": "us-west-2"
    }
  ]
}
`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.20.0

**Additional context**
(Add any other context about the problem here.)

**Comment by debae** [comment]
The reason behind the field not being mapped is that the event.json had a field "Records", but the field in SQSEvent is records with a lowercase **r**.

Within the AmazonLambdaRecorder#59 , quarkus converts the inputstream to an object.
There should be some kind of configuration present to support mapping Records to the records field. 

AWS does this mapping correctly and not taking capital letters into account. 

To validate this is the issue i created this class as workaround

`
package com.ennovativesolutions.quarkus;

public class SQSEvent extends com.amazonaws.services.lambda.runtime.events.SQSEvent {
    
    @Override
    @JsonProperty("Records")
    public List<SQSMessage> getRecords() {
        return super.getRecords();
    }
}

`

The correct way to solve this would probably be adding a property like this on the ObjectMapper from Jackson 

`
objectMapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
`

**Comment by gwenneg** [comment]
Hi @debae and thanks for reporting this issue!

I think using `MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES` is a good way to solve it. Would you like to contribute to Quarkus by submitting this in a PR?
