### ISSUE TITLE
Regression: YAML Jackson Server not working anymore in Quarkus 3.2

### ISSUE THREAD

**Issue by rschumm** [quarkusio/quarkus#34817]
### Describe the bug

Sending a `yaml` File to a Quarkus Server via `HTTP POST` fails with: 

```
Suppressed: jakarta.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: interface java.util.List<class ch.schumm.stunden.input.Tag> of content type: application/yaml
            at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.throwReaderNotFound(ServerReaderInterceptorContext.java:54)
```

This used to work previous to Quarkus 3. 

### Expected behavior

Resteasy should be able to parse YAML just as it does with JSON

### Actual behavior

```
Suppressed: jakarta.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: interface java.util.List<class ch.schumm.stunden.input.Tag> of content type: application/yaml
            at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.throwReaderNotFound(ServerReaderInterceptorContext.java:54)
```

### How to Reproduce?

Reproducer Project: 

https://github.com/rschumm/quarkusyaml 

just run 
```
mvn test
```

### Output of `uname -a` or `ver`

Darwin kyburg.home 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "20.0.1" 2023-04-18 OpenJDK Runtime Environment Homebrew (build 20.0.1) OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)

### GraalVM version (if different from Java)

none

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c) Maven home: /opt/homebrew/Cellar/maven/3.9.2/libexec Java version: 20.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home Default locale: de_CH, platform encoding: UTF-8 OS name: "mac os x", version: "13.4.1", arch: "aarch64", family: "mac"

### Additional information

Discussion originated in 
https://stackoverflow.com/questions/61956772/how-do-i-return-an-object-in-jax-rs-as-yaml-using-jackson-in-quarkus/76692216#76692216

**Comment by geoand** [comment]
cc @gastaldi who answered the original StackOverflow question

**Comment by gastaldi** [comment]
@rschumm you need to use the Jakarta RS provider instead. See https://stackoverflow.com/a/76721863/862119

**Comment by rschumm** [comment]
@gastaldi George - thanks a lot for explaining and even fixing my small reproducer project (even my bad yaml 😬). also my original project is now fixed on the newest Quarkus! 
This was fun - and thanks to you all for the wonderful work on Quarkus!

**Comment by gastaldi** [comment]
@rschumm no worries, I also checked that the `quarkus update --stream=3.2` should have performed that change for you, let us knownif that's the case

**Comment by rschumm** [comment]
Hi @gastaldi - I am back from short holidays and tested the `quarkus update` as you proposed. It did not work:   
origin version: Quarkus 2.12.2   
Errors: 
```
[INFO] --- quarkus:3.2.1.Final:update (default-cli) @ schustu ---
[WARNING] quarkus:update goal is experimental, its options and output might change in future versions
[INFO] Looking for the newly published extensions in registry.quarkus.io
[ERROR] The project does not import any Quarkus platform BOM
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.783 s
[INFO] Finished at: 2023-07-30T09:25:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.1.Final:update (default-cli) on project schustu: The command did not succeed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.1.Final:update (default-cli) on project schustu: The command did not succeed.
```

I had the BOM in my old POM: 
```xml
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>18</maven.compiler.source>
    <maven.compiler.target>18</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>2.12.2.Final</quarkus.platform.version>
    <quarkus-plugin.version>2.12.2.Final</quarkus-plugin.version>
    <surefire-plugin.version>2.22.2</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```



But this might happened because my project was old and I did a lot of stuff by hand in it, so it’s not a drama it did not work.   

Nevertheless, thanks for pointing out the command `quarkus update` - I will use it in future migrations.

**Comment by rschumm** [comment]
ps: `quarkus update` from `3.2.0.Final` to `3.2.2.Final` though worked. :-)

**Comment by gsmet** [comment]
The problem is that you are using an old BOM that our update mechanism doesn't detect.

If you change the BOM to `io.quarkus.platform:quarkus-bom`, the upgrade should work.

I will check if we can improve this easily.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/35130 .
