### ISSUE TITLE
cannot build uber jar on barebones project from code.quarkus

### ISSUE THREAD

**Issue by guykatz** [quarkusio/quarkus#34823]
### Describe the bug

go to code.quarkus.io
create a java 17, Gradle, barebones (no extensions) project and download. 
try to build uver jar using ./gradlew build -Dquarkus.package.type=uber-jar (OS is windows 11)

### Expected behavior

uber jar is built

### Actual behavior

exceptions is shown as follows: 

> PS C:\dev_env\code-with-quarkus> ./gradlew build -Dquarkus.package.type=uber-jar
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task '.package.type=uber-jar' not found in root project 'code-with-quarkus'.
> 
> * Try:
> > Run gradlew tasks to get a list of available tasks.
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 821ms

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by geoand** [comment]
This is certainly not a Quarkus issue as `Task '.package.type=uber-jar' not found in root project 'code-with-quarkus'.` clearly demonstrates. 
You likely need to escape some characters in the Windows terminal
