### ISSUE TITLE
quarkus.analytics.uri.base unrecognized by build time analytics

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#34825]
### Describe the bug

`quarkus-maven-plugin` reports a warning
```
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.analytics.uri.base" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
when the `quarkus.analytics.uri.base` is provided.

The warning is issued regardless of whether the analytics are active or not.

The other analytics-related properties are fine:
```
quarkus.analytics.disabled
quarkus.analytics.timeout
```

### Expected behavior

No warning in build/app log.

### How to Reproduce?

```
quarkus create app bta-reproducer --no-code
cd bta-reproducer
quarkus build -Dquarkus.analytics.uri.base="http://fake.url"
```

### Output of `uname -a` or `ver`

Linux 6.2.15-200.fc37.x86_64

### Output of `java -version`

openjdk 17.0.7 2023-04-18

### Quarkus version or git rev

3.2.0.Final, 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.8

**Comment by geoand** [comment]
cc @brunobat

**Comment by geoand** [comment]
We will need a a ConfigMapping that maps the config property to an interface in order to avoid these warnings

**Comment by brunobat** [comment]
Yup. We have that in other cases... This one slipped away.
