### ISSUE TITLE
`quarkus.kubernetes.output-directory` is not (always) relative to project location

### ISSUE THREAD

**Issue by endrec** [quarkusio/quarkus#34827]
### Describe the bug

#31373 introduced the `quarkus.kubernetes.output-directory`, which is supposed to be relative to `projectDir`, but it seems that's not (always) the case.

### Expected behavior

Kubernetes manifests to generated in the specified output directory under the project root.

### Actual behavior

Kubernetes manifests are generated in the specified output directory under `$HOME/.gradle/workers`

### How to Reproduce?

Steps to reproduce the behaviour:
1. Create a simple app:
  `quarkus create app org.acme:k8s-demo --gradle-kotlin-dsl --extension='kotlin,kubernetes,jib'`
2. Change working directory to the app's root:
  `cd k8s-demo`
3. Build app with default settings:
  `quarkus build`
4. Observe that kubernetes manifest is created under the default build directory:
   ```
   $ ls -1 build/kubernetes/kubernetes.yml
   build/kubernetes/kubernetes.yml
   ```
5. Clean up the build:
  `rm -rf build`
6. Build app with `quarkus.kubernetes.output-directory` set:
  `quarkus build -Dquarkus.kubernetes.output-directory=k8s`
7. Observe that kubernetes manifest is created under `~/.gradle/workers` instead of the project folder:
   ```
   $  ls -1 k8s/kubernetes.yml build/kubernetes/kubernetes.yml ~/.gradle/workers/k8s/kubernetes.yml
   ls: build/kubernetes/kubernetes.yml: No such file or directory
   ls: k8s/kubernetes.yml: No such file or directory
   [$HOME]/.gradle/workers/k8s/kubernetes.yml
   ```

### Output of `uname -a` or `ver`

Darwin ip-192-168-2-68.eu-west-2.compute.internal 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

### Output of `java -version`

```
openjdk version "18.0.2" 2022-07-19 
OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR) 
OpenJDK 64-Bit Server VM Corretto-18.0.2.9.1 (build 18.0.2+9-FR, mixed mode, sharing)
```

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
------------------------------------------------------------ 
Gradle 7.6.1 
------------------------------------------------------------ 
 
Build time:   2023-02-24 13:54:42 UTC 
Revision:     3905fe8ac072bbd925c70ddbddddf4463341f4b4 
  
Kotlin:       1.7.10 
Groovy:       3.0.13 
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 
JVM:          18.0.2 (Amazon.com Inc. 18.0.2+9-FR) 
OS:           Mac OS X 13.4.1 aarch64
```

**Comment by Sgitario** [comment]
Thanks for reporting! https://github.com/quarkusio/quarkus/pull/34987 fixes this issue.
