### ISSUE TITLE
Query hint support for Panache

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#3482]
So that queries can be easily cached. Support for this was suggested in #646 but was not included there.

**Comment by yuhaibohotmail** [comment]
When will this function be implemented?

**Comment by loicmathieu** [comment]
@emmanuelbernard @FroMage Hint support has been proposed via `entity.find().withHint()` as it has been down for `withLock()`.
It is a highly demanded features as it allows to set the cache hint to cache Hibernate queries from Panache.

I have a working prototype and successfully test that using the Hibernate caching this way allow to cache a query. If I have your GO I can propose a PR :)

**Comment by FroMage** [comment]
That's fine by me.

**Comment by loicmathieu** [comment]
@emmanuelbernard WDYT ?

**Comment by emmanuelbernard** [comment]
Yep that’s good. I think we might want something better than this hidden hint approach for query caching at some point but we can let that come.
