### ISSUE TITLE
Support named queries in Panache

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#3483]
Named query invocations are missing in Panache. 

Adding named queries can make #3482 less of a priority, since hints can be directly defined in the annotated named query.

**Comment by loicmathieu** [comment]
@galderz which named queries do you want Panache to support? 

Named queries via the `@NamedQuery` annotation so someone can annotate it's entity with a query and use it in one of the find method of Panache like this:

```
@Entity
@NamedQuery(name="Country.findAll", query="SELECT c FROM Country c")
public class Country extends PanacheEntity {
    // ...
}

Country.find("Country.findAll");
// or
Country.findByQuery("Country.findAll");
```

Or adding to the existing find/list/stream/count/Delete methods an overload to allow passing a Query object ?

```
TypedQuery query = Country.getEntityManager()
    .createNamedQuery("SELECT c FROM Country c", Country.class);
List<Country> countries = Country.list(query);
```

Personaly I favor the second one, but the first one can also allow to specify hints and lockmode (there is issue #2744 to support lockmode in Panache)

**Comment by galderz** [comment]
I don't really mind which TBH, I'm happy with whatever is more idiomatic for Panache.

**Comment by nimo23** [comment]
Please support `NamedQuery`. I have a bunch of namedQueries in old jee project and want to reuse it:

For example:

// this NamedQuery also has jpa hints which must be considered in panache
`@NamedQuery(name = User.byName, query = "select distinct u from User u where u.name =:name", hints = @QueryHint(name = QueryHints.COMMENT, value = "User.name: Get User by name."))`

and use it:

`User.find("User.byName");`

**Comment by nimo23** [comment]
And please also support `@NamedEntityGraph` in Panache:

// this NamedEntityGraph also has "jpa or hibernate hints" which must be considered in panache
User.find("User.entityGraph");
// or User.query("User.entityGraph");

**Comment by brunobat** [comment]
We would also like to have this. Any idea on the ETA?

**Comment by loicmathieu** [comment]
@nimo23 for named entity graph they can be used via a query Hint `javax.persistence.fetchgraph`.
Hints are already supported via `find(query).withHint()`
