### ISSUE TITLE
Documentation about writing-native-applications-tips does not contain gradle examples

### ISSUE THREAD

**Issue by debae** [quarkusio/quarkus#3484]
**Describe the bug**
The documentation about writing-native-applications-tips only contains examples on how to achieve this via maven. 

**Expected behavior**
Gradle examples are provided as well.

**Maven setup**
```
    <additionalBuildArgs>
        <additionalBuildArg>-H:ReflectionConfigurationFiles=${project.basedir}/reflection-config.json</additionalBuildArg>
    </additionalBuildArgs>
```
**Gradle setup**
If we want to achieve the same via gradle we need to specify it like this
```
--additional-build-args='-H:ReflectionConfigurationFiles=resources/main/reflection-config.json' 
```
**Remarks**
There is some extra caveat being that the config files must end up in your 'build' (gradle's output folder) in order to have them visible when creating the native image.
We added them to src/main/resources, so they end up in build/resources/main.
This is different then with maven where the documentation states that those files should be in the root of the project.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.20.0

**Comment by gsmet** [comment]
I'm all for adding them. Could you maybe create a pull request?

**Comment by debae** [comment]
Here you go : https://github.com/quarkusio/quarkus/pull/3550

**Comment by gsmet** [comment]
Closing!
