### ISSUE TITLE
Cannot disable docker container image build when using Gradle

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#34842]
### Describe the bug

I have a Quarkus project using `quarkus-container-image-docker`. This works great when building images locally only M2 Mac.

For CI I need to use a multistage Docker build rather than a container build. In my multistage Dockerfile I build the native executable with 
```
./gradlew assemble -Dquarkus.package.type=native -Dquarkus.native.container-build=false -Dquarkus.native.remote-container-build=false -Dquarkus.container-image.build=false
```

The build fails with:
```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromNativeImage threw an exception: java.lang.RuntimeException: Unable to build docker image. Please check your docker installation
                at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromNativeImage(DockerProcessor.java:144)
```

### Expected behavior

There is a way to disable the `quarkus-container-image-docker` extension.
Docker is not used since I have specified not use a container build and the native executable is built successfully.

### Actual behavior

The build attempts to use Docker and fails because of this.

### How to Reproduce?

Add `quarkus-container-image-docker` extension.
Set default application.properties:
```
quarkus.package.type=native
quarkus.native.remote-container-build=true
quarkus.container-image.build=true
```
Create a multistage Dockerfile and build the executable in the Dockerfile with `-Dquarkus.package.type=native -Dquarkus.native.container-build=false -Dquarkus.native.remote-container-build=false -Dquarkus.container-image.build=false`

If I remove the `quarkus-container-image-docker` extension then the multistage Dockerfile builds correctly.

### Output of `java -version`

Java 17.0.7

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by josephearl** [comment]
I have just found out if I add `-Dquarkus.container-image.builder=none` to the build args then docker is not used.

However I would have expected the `-Dquarkus.container-image.build=false` to have been enough.

**Comment by geoand** [comment]
@zakkak do you plan to look into this one?

**Comment by zakkak** [comment]
I had a look and although I was able to reproduce it with gradle, I can't reproduce it with maven. So as far as I understand this is an issue with how gradle (or Quarkus when using gradle) handles the `-D` options.

Since I am not familiar with Gradle and what might be different I would prefer to leave this to someone else :)

**Comment by geoand** [comment]
> Since I am not familiar with Gradle and what might be different I would prefer to leave this to someone else :)

cc @quarkusio/devtools

**Comment by geoand** [comment]
As mentioned [here](https://github.com/quarkusio/quarkus/issues/34810#issuecomment-1643593249), Gradle doesn't pass system properties to the forked process with `-D` as Maven does.

**Comment by josephearl** [comment]
Not sure this is the same issue as that other one?
I don't see what forked process is started for `quarkus.container-image.build`, and setting `quarkus.native.container-build` works so it's not clear to me why one would work and not the other

**Comment by geoand** [comment]
I closed it based on what @zakkak found and the invalid use of the propetries in Gradle
