### ISSUE TITLE
Swagger UI @OpenAPIDefinition

### ISSUE THREAD

**Issue by Manu206** [quarkusio/quarkus#3485]
I tried to change the title of the generated oneapi documentation. However adding @OpenAPIDefinition to the Controller does not work as it is usually defined in the Application.class. In Quarkus I do not have such an class. Can you give me an example of how and where to define it?

`
@OpenAPIDefinition(info =
    @Info(title = "XXX API", version = "1.0", description = "BLABLA")
)
`

**Comment by Manu206** [comment]
Found it on the Microprofile documentation:
`
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/")
@OpenAPIDefinition(info = @Info(title = "XXX API", version = "1.0", description = "BLABLA") )
public class App extends Application {
}
`

**Comment by gsmet** [comment]
While you don't have to create an Application class in Quarkus, you can do it if you need it.

In this case, that's what I would do.

**Comment by HelvetiaAppDev** [comment]
Unfortunately I cannot get this to work. I'm on quarkus 1.0.1.Final and followed the example(s) here:
https://quarkus.io/guides/openapi-swaggerui#providing-application-level-openapi-annotations

I added a class that extends _javax.ws.rs.core.Application_ with the _@OpenAPIDefinition_ annotation, just like the ExampleApiApplication from the guide (actually exactly that code snippet). 

The endpoints and operations are correctly generated in the openapi.yml, however the metadata from _@OpenAPIDefinition_, such as the title, are not picked up (e.g. the title is still "Generated API").

Does the class extending Application need to be in a certain location?
And/Or can someone check, if that could be a bug?

**Comment by flo-ryan** [comment]
Unfortunately I cannot get this to work. I'm on quarkus 1.0.1.Final and followed the example(s) here:
https://quarkus.io/guides/openapi-swaggerui#providing-application-level-openapi-annotations

I added a class that extends javax.ws.rs.core.Application with the @OpenAPIDefinition annotation, just like the ExampleApiApplication from the guide (actually exactly that code snippet).

The endpoints and operations are correctly generated in the openapi.yml, however the metadata from @OpenAPIDefinition, such as the title, are not picked up (e.g. the title is still "Generated API").

Does the class extending Application need to be in a certain location?
And/Or can someone check, if that could be a bug?

**Comment by flo-ryan** [comment]
> 
> 
> Unfortunately I cannot get this to work. I'm on quarkus 1.0.1.Final and followed the example(s) here:
> https://quarkus.io/guides/openapi-swaggerui#providing-application-level-openapi-annotations
> 
> I added a class that extends javax.ws.rs.core.Application with the @OpenAPIDefinition annotation, just like the ExampleApiApplication from the guide (actually exactly that code snippet).
> 
> The endpoints and operations are correctly generated in the openapi.yml, however the metadata from @OpenAPIDefinition, such as the title, are not picked up (e.g. the title is still "Generated API").
> 
> Does the class extending Application need to be in a certain location?
> And/Or can someone check, if that could be a bug?

I figured out what I did wrong:
I was using the annotations from the swagger core annotations dependency rather than the ones from the microprofile (they have almost the exact same naming). 🤦‍♂
