### ISSUE TITLE
"This error is reported at image build time because classis registered for linking at image build time" error despite using --initalize-at-run-time

### ISSUE THREAD

**Issue by programmatix** [quarkusio/quarkus#34854]
### Describe the bug

I've been tasked with continuing work on getting native image support working for the Couchbase Quarkus extension (https://github.com/quarkiverse/quarkus-couchbase), currently in alpha.

I'm hitting a couple of different issues that look to have the same root cause.  One of the issues is this, hit while natively compiling a very basic Quarkus app that depends on the quarkus-couchbase extension:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.couchbase.client.java.env.ClusterEnvironment.<init>(com.couchbase.client.java.env.ClusterEnvironment$Builder)
Parsing context:
   at com.couchbase.client.java.env.ClusterEnvironment.<init>(ClusterEnvironment.java:55)
   at com.couchbase.client.java.env.ClusterEnvironment.<init>(ClusterEnvironment.java:48)
   <elided>

Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.couchbase.client.java.codec.JacksonJsonSerializer.create(com.couchbase.client.core.encryption.CryptoManager). This error is reported at image build time because class com.couchbase.client.java.env.ClusterEnvironment is registered for linking at image build time by command line
        at parsing com.couchbase.client.java.env.ClusterEnvironment.newDefaultSerializer(ClusterEnvironment.java:71)
	   <elided>

Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.couchbase.client.java.codec.JacksonJsonSerializer.create(com.couchbase.client.core.encryption.CryptoManager). This error is reported at image build time because class com.couchbase.client.java.env.ClusterEnvironment is registered for linking at image build time by command line
	   <elided>
```

The error itself makes sense.  We have some code `ClusterEnvironment.newDefaultSerializer()` that checks if the user has the Jackson library on their classpath, and initialises a `JacksonJsonSerializer` if so.  So the solution seems to be to push all this logic to runtime rather than buildtime.

So I added to native-image.properties in quarkus-couchbase `--initialize-at-run-time=<elided>,com.couchbase.client.java.codec.JacksonJsonSerializer,com.couchbase.client.java.env.ClusterEnvironment,<elided>`

And used `native-image -H:+PrintClassInitialization` to confirm the mentioned classes should be getting initialized at runtime:

```
com.couchbase.client.java.codec.JacksonJsonSerializer, RUN_TIME, from 'META-INF\native-image\native-image.properties' in 'file:///C:/dev/test-quarkus-couchbase/target/test-quarkus-couchbase-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkiverse.couchbase.quarkus-couchbase-999-SNAPSHOT.jar' with 'com.couchbase.client.java.codec.JacksonJsonSerializer'
com.couchbase.client.java.env.ClusterEnvironment, RUN_TIME, from 'META-INF\native-image\native-image.properties' in 'file:///C:/dev/test-quarkus-couchbase/target/test-quarkus-couchbase-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkiverse.couchbase.quarkus-couchbase-999-SNAPSHOT.jar' with 'com.couchbase.client.java.env.ClusterEnvironment'
```

But, I'm still getting the same error indicating the classes continue to be getting processed at image build time.

Any thoughts?  I can upload a project that replicates this if it helps.

**Comment by programmatix** [comment]
Thanks for the reply @geoand - I'll dig into that further.
But am I correct in thinking that the basic idea would be to substitute the body of the `ClusterEnvironment.newDefaultSerializer()` method so it avoids the JacksonJsonSerializer path?
If so that wouldn't be ideal for us as it's disabling some functionality that has been useful for some users.  Admittedly it is tertiary functionality and we could perhaps live without it.  But I have another similar problem related to Netty choosing a logging backend at runtime based on what's on the classpath, which I think we'd need to keep and wouldn't be able to substitute past.

**Comment by programmatix** [comment]
@geoand I'm afraid I'm not getting it...  I've read through the docs and all the examples I could find, and tried this:
```
@TargetClass(ClusterEnvironment.class)
@Substitute
public final class TargetClusterEnvironment {
    private JsonSerializer newDefaultSerializer(CryptoManager cryptoManager) {
        // ... custom body ...
    }
}
```
Is that the approach you're suggesting?  But with this I'm getting error `com.oracle.svm.core.util.UserError$UserException: target class must inherit directly from Object: class com.couchbase.client.java.env.ClusterEnvironment`.  And sure enough, `ClusterEnvironment` inherits from something else - and I don't see another suitable 'hook point' for TargetClass.

I'm also not understanding why I can't defer this logic to runtime, which is what I think I really want to do - per above the `--initialize-at-run-time` doesn't seem to be working and I'm not sure why?

**Comment by geoand** [comment]
> I'm also not understanding why I can't defer this logic to runtime, which is what I think I really want to do - per above the --initialize-at-run-time doesn't seem to be working and I'm not sure why?

It's usually not that simple, but you can try adding `RuntimeInitializedClassBuildItem` to your extension

**Comment by geoand** [comment]
> I'm afraid I'm not getting it... I've read through the docs and all the examples I could find, and tried this:

I am suggesting something like this:

```java
@TargetClass(value = ClusterEnvironment.class, , onlyWith = IsJacksonAbsent.class)
public final class TargetClusterEnvironment {
    @Substitute
    private JsonSerializer newDefaultSerializer(CryptoManager cryptoManager) {
        // ... custom body ...
    }

    public static class IsJacksonAbsent implements BooleanSupplier {

        @Override
        public boolean getAsBoolean() {
            try {
                Class.forName("com.fasterxml.jackson.databind.ObjectMapper");
                return false;
            } catch (ClassNotFoundException ignored) {
                return true;
            }
        }
    }
}
```

**Comment by programmatix** [comment]
@geoand many thanks for your help, I think that's got me past the first issue, this JacksonJsonSerializer one.

Could I also ask for help with the 2nd?  It looks similar but I haven't been able to solve it with the same approach, and I'm unclear why.

The failure is:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory.newInstance(java.lang.String)
Parsing context:
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory.newInstance(Log4JLoggerFactory.java:38)
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.useLog4JLoggerFactory(InternalLoggerFactory.java:89)
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:52)
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:111)
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:134)
   at com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:127)
   at com.couchbase.client.core.deps.io.netty.util.internal.SystemPropertyUtil.<clinit>(SystemPropertyUtil.java:31)
      <stacktrace elided>

Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.log4j.Logger. This error is reported at image build time because class com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory is registered for linking at image build time by command line
        at parsing com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory.newInstance(Log4JLoggerFactory.java:38)
      <stacktrace elided>
        
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.log4j.Logger. This error is reported at image build time because class com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory is registered for linking at image build time by command line
      <stacktrace elided>
```

This is some Netty code InternalLoggerFactory that's choosing what logging backend to use based on what's on the user's classpath.

As with JacksonJsonSerializer I've tried to push it to the runtime, without success.  I've tried both `--initialize-at-run-time` and 
```
    @BuildStep
    RuntimeInitializedClassBuildItem internalLoggerFactory() {
        return new RuntimeInitializedClassBuildItem(
                com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory.class.getCanonicalName());
    }
```

According to `-H:+PrintClassInitialization` output they are at runtime, but the compile output suggests not:

```
com.couchbase.client.core.deps.io.netty.util.internal.logging.Log4JLoggerFactory, RUN_TIME, subtype of com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory and from feature io.quarkus.runner.Feature.beforeAnalysis with 'Log4JLoggerFactory.class'
com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory, RUN_TIME, from 'META-INF\native-image\native-image.properties' in 'file:///C:/dev/test-quarkus-couchbase/target/test-quarkus-couchbase-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.quarkiverse.couchbase.quarkus-couchbase-999-SNAPSHOT.jar' with 'com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'InternalLoggerFactory.class'
```

I saw you already have Netty substitutions here: https://github.com/quarkusio/quarkus/blob/b7954d17329980baa4d0b1fc7f4fcba686df6d04/extensions/netty/runtime/src/main/java/io/quarkus/netty/runtime/graal/NettySubstitutions.java.  Unfortunately they are not getting picked up as we shadow Netty into a `com.couchbase.client.core.deps.io.netty` package.

So I copied it into the extension as:
```

@TargetClass(className = "com.couchbase.client.core.deps.io.netty.util.internal.logging.InternalLoggerFactory")
final class Target_io_netty_util_internal_logging_InternalLoggerFactory {

    @Substitute
    private static InternalLoggerFactory newDefaultFactory(String name) {
        return JdkLoggerFactory.INSTANCE;
    }
}
```

But the problem remains.

Any thoughts?

**Comment by geoand** [comment]
As you have shaded Netty, you'll need to "copy" those for the new shaded classes.

**Comment by programmatix** [comment]
Ah the last issue was user error - I had the right solution, but the file was in the wrong place (deployment not runtime).  

I now have a natively compiled app using the Couchbase Extension!  So I'll close this out and open any subsequent issues as a new ticket.  Many thanks again for all your help.

**Comment by geoand** [comment]
Glad to hear it!

**Comment by UrCoderPal** [comment]
Hi @geoand and @programmatix your conversation here was helpful, but in my case i want to substitute the org.jose4j.keys.EdDsaKeyUtil class which extends the OctetKeyPairUtil and this the KeyPairUtil class which is of 'default' access.
So now when i have to override the abstract methods of KeyPairUtil in my TargetEdDsaKeyUtil class i am restricted. I thought of creating substitutes for all three but then in my TargetKeyPairUtil the @TargetClass(org.jose4j.keys.KeyPairUtil.class) also gives an error because the value we are passing here is  inaccessible.
I intended to keep all the implementation logic intact.
What do u guys suggest?
