### ISSUE TITLE
Quarkus 3 Rest Client never timeouts

### ISSUE THREAD

**Issue by alinayebi9080** [quarkusio/quarkus#34852]
### Describe the bug

i migrate quarkus from 2.7.1 to 3.1.2 and Rest Client never timeouts after one hour. how to resolve this problem?

### Output of `java -version`

17

### Quarkus version or git rev

3.1.2

**Comment by geoand** [comment]
Which rest client are you using?

What properties are you setting?

**Comment by alinayebi9080** [comment]
i use quarkus-rest-client-jackson and client-api/mp-rest/connectTimeout=50000 and client-api/mp-rest/readTimeout=50000

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>

**Comment by geoand** [comment]
cc @jamezp

**Comment by gsmet** [comment]
@alinayebi9080 I think having a simple Maven reproducer would be useful.

**Comment by alinayebi9080** [comment]
i find that rest client hang after 30 minutes and respond after 30 minutes. why???? Response.close() not working??

**Comment by Sgitario** [comment]
I confirmed that `client-api/mp-rest/readTimeout` is working fine when injecting the client (via CDI). 
So, we definitely need a reproducer to better help here.

**Comment by geoand** [comment]
Closing as we never got a reproducer
