### ISSUE TITLE
Gradle builds include values from .env, which override defaults in application.properties, outlasting non-clean rebuilds.

### ISSUE THREAD

**Issue by Foobartender** [quarkusio/quarkus#34869]
### Describe the bug

Consider having an `application.properties` file like this:
```
greeting.message=${FOO_MESSAGE:Hello!}
```
...and a `.env` file like this:
```
FOO_MESSAGE=Hi!
```

### Expected behavior

Building the project while having the `.env` file in its root directory doesn't affect the default value provided in `application.properties`. Actually, it shouldn't affect the build output at all.

Regarding the example project, its endpoint should return "Hello!", unless there is an `.env` file with a value overriding it in its working directory,

### Actual behavior

A clean build uses the value from `.env` as default. Subsequent builds keep that value even if `.env` is updated. After cleaning and rebuilding, the updated value from `.env` is used.

### How to Reproduce?

An example project using Gradle (Kotlin) with a ConfigMapping and a RESTEasy endpoint returning `greeting.message` is provided. 
Build, copy build output to a another directory and cd into it (to get the .env file out of the way), run, check output, modify, repeat, clean, repeat... as necessary to reproduce the described actual behavior.

[quarkus-dotenv.tar.gz](https://github.com/quarkusio/quarkus/files/12101443/quarkus-dotenv.tar.gz)

### Output of `uname -a` or `ver`

Linux ***** 6.4.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 15 Jul 2023 19:25:49 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment GraalVM CE 17.0.7+7.1 (build 17.0.7+7-jvmci-23.0-b12) OpenJDK 64-Bit Server VM GraalVM CE 17.0.7+7.1 (build 17.0.7+7-jvmci-23.0-b12, mixed mode, sharing)

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

Bug was introduced sometime between 2.6.x and 3.2.0.

**Comment by gsmet** [comment]
@snazy I wonder if it's an issue specific to Gradle or if it's something that is config-related. Any clue?

**Comment by snazy** [comment]
It's probably the new mechanism to fetch the config. Let me take a look.
