### ISSUE TITLE
Quarkus build does not work since 3.2.0 with teamcity/plexus launcher

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#34875]
### Describe the bug

We have some custom extensions which use dependencies from a private repository. Since quarkus 3.2.0 the build fails while generating the test code. Up to 3.1.3 it worked fine.

```
  [INFO] --- quarkus:3.2.1.Final:generate-code-tests (default) @ database-extension-base ---
  [INFO] Artifact de.mobilexag.serviceplatform:service-parent-kotlin:pom:1.8.1 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
  Downloading from central: https://repo.maven.apache.org/maven2/de/mobilexag/serviceplatform/service-parent-kotlin/1.8.1/service-parent-kotlin-1.8.1.pom
  [INFO] No previous run data found, generating javadoc.
  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.1.Final:generate-code-tests (default) on project database-extension-base: Quarkus code generation phase has failed
```

I first thought this might be the problem, but it fails still with 3.2.1 https://github.com/quarkusio/quarkus/issues/34448

We encountered the problem on our build system teamcity. It starts maven builds via the plexus launcher. https://codehaus-plexus.github.io/plexus-classworlds/launcher.html
The quarkus maven plugin seems to ignore the settings file set via plexus. The call looks something like this:

```
java -Dmaven.repo.local=local-repo \
-Dclassworlds.conf=teamcity.m2.conf \
-Dmaven.multiModuleProjectDirectory=../code-with-quarkus \
 --add-opens \
 java.base/java.lang=ALL-UNNAMED \
 -classpath \
 "$MAVEN_HOME/boot/*:" \
 org.codehaus.plexus.classworlds.launcher.Launcher \
 -f \
 pom.xml \
 -B \
 -s \
 custom-settings.xml \
 -fae \
 -Plicense \
 -X \
 clean \
 package
```
The settings file is set via -s command on maven start.

In the reproducer, there are some scripts to start the build.

### Expected behavior

Build should work.

### Actual behavior

Build fails.

### How to Reproduce?

https://github.com/robp94/quarkus-3.2.x-maven-problem

### Output of `uname -a` or `ver`

ubuntu

### Output of `java -version`

17

### Quarkus version or git rev

3.2.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.3

**Comment by robp94** [comment]
This should not be a Kotlin issue but a maven plugin issue.

**Comment by gsmet** [comment]
Could you give us a bit more details about your setup and typically how your private repository is configured?

/cc @aloubyansky

**Comment by aloubyansky** [comment]
Thanks for reporting the issue. In case you could provide a reproducer similar to https://github.com/agseijas/maven-security-quarkus/blob/master/README.md (that one was already fixed), it would help a lot.

**Comment by aloubyansky** [comment]
Thanks a lot @robp94 I'll look into it.

**Comment by aloubyansky** [comment]
As a quick workaround you could pass `maven.settings` system property like
```
diff --git a/code-with-quarkus/maven-settings.sh b/code-with-quarkus/maven-settings.sh
old mode 100644
new mode 100755
diff --git a/code-with-quarkus/pom.xml b/code-with-quarkus/pom.xml
index b1506b3..5161ff0 100644
--- a/code-with-quarkus/pom.xml
+++ b/code-with-quarkus/pom.xml
@@ -87,6 +87,7 @@
           <systemPropertyVariables>
             <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
             <maven.home>${maven.home}</maven.home>
+            <maven.settings>${maven.settings}</maven.settings>
           </systemPropertyVariables>
         </configuration>
       </plugin>
@@ -104,6 +105,7 @@
                 <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                 <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                 <maven.home>${maven.home}</maven.home>
+                <maven.settings>${maven.settings}</maven.settings>
               </systemPropertyVariables>
             </configuration>
           </execution>

diff --git a/code-with-quarkus/teamcity.sh b/code-with-quarkus/teamcity.sh
old mode 100644
new mode 100755
index 2801ffd..e111605
--- a/code-with-quarkus/teamcity.sh
+++ b/code-with-quarkus/teamcity.sh
@@ -1,5 +1,6 @@
 mkdir -p local-repo
 java -Dmaven.repo.local=local-repo \
+-Dmaven.settings=custom-settings.xml \
 -Dclassworlds.conf=teamcity.m2.conf \
 -Dmaven.multiModuleProjectDirectory=../code-with-quarkus \
  --add-opens \
```

**Comment by aloubyansky** [comment]
I have a fix for 3.2 but the test plugin configs will need to be adjusted a bit for it to work and that's true for both 2.16 and 3.2:
```
diff --git a/code-with-quarkus/pom.xml b/code-with-quarkus/pom.xml
index b1506b3..6c497c5 100644
--- a/code-with-quarkus/pom.xml
+++ b/code-with-quarkus/pom.xml
@@ -87,6 +87,7 @@
           <systemPropertyVariables>
             <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
             <maven.home>${maven.home}</maven.home>
+            <maven.settings>${session.request.userSettingsFile.absolutePath}</maven.settings>
           </systemPropertyVariables>
         </configuration>
       </plugin>
@@ -104,6 +105,7 @@
                 <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                 <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                 <maven.home>${maven.home}</maven.home>
+                <maven.settings>${session.request.userSettingsFile.absolutePath}</maven.settings>
               </systemPropertyVariables>
             </configuration>
```

**Comment by aloubyansky** [comment]
I'll probably adjust the project generator to add the `maven.setting` property to the test plugins as well.

**Comment by robp94** [comment]
Ok, while the workaround worked for me localy, I was not able to get it to work with teamcity.

We used currently use this as a config for the test plugins:
`<maven.settings>${session.request.userSettingsFile.path}</maven.settings>`

**Comment by aloubyansky** [comment]
3.2 still requires a patch, I'll open a pr later today.
It fails before the test plugins currently.
Unless you are using source code generating plugins (grpc, avro, etc) you could also remove the generate-code goals, that's where it fails currently.

**Comment by robp94** [comment]
Thanks. I will take a look later today or on Monday again.

**Comment by aloubyansky** [comment]
I opened a PR to fix the generate-code goals, however I still haven't added the test plugin config adjustment in the project generator. I'm wondering whether we should document it or simply always pass it on to the test plugins in case the process isn't not launched using the `mvn` scripts.

**Comment by aloubyansky** [comment]
About the `maven.settings` property, I added a note in the docs in https://github.com/quarkusio/quarkus/pull/35211 for now

**Comment by robp94** [comment]
Looks good, teamcity can build again. Thanks for the quick fix :)
