### ISSUE TITLE
Quarkus 3.2.1 openjdk base image tag

### ISSUE THREAD

**Issue by rnc** [quarkusio/quarkus#34881]
### Describe the bug

It seems that in 3.2.1 the base image was changed. I _think_ this is in https://github.com/quarkusio/quarkus/blame/main/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L93 which was changed in https://github.com/quarkusio/quarkus/pull/34383 by @cescoffier / @gsmet However in https://catalog.redhat.com/software/containers/ubi8/openjdk-17-runtime/618bdc5f843af1624c4e4ba8?architecture=amd64&container-tabs=overview the latest appears to be 1.16 - 1.17 does not exist (and has not been released according to @jmtd ). I have checked with @stuartwdouglas as this has broken https://github.com/redhat-appstudio/jvm-build-service when we upgraded.

**Comment by geoand** [comment]
Super odd...

Also looping in @rsvoboda who had done some checks in the https://github.com/quarkusio/quarkus/pull/34383

**Comment by patrox** [comment]
I'm facing the same issue as you @rnc, and also concluded that the issue is with the `openjdk-17-runtime:1.17` image being absent / inaccessible, as this will work just fine:

```
docker pull registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
```

```
1.16: Pulling from ubi8/openjdk-17-runtime
Digest: sha256:9f20a3c23c9ab7947b45fb92cdf5f96a5c2e295cb7f665bcf844091bdcfa87b7
Status: Image is up to date for registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
  ```
  

while this, will fail with 404:

```
docker pull registry.access.redhat.com/ubi8/openjdk-17-runtime:1.17
```

```
Error response from daemon: manifest for registry.access.redhat.com/ubi8/openjdk-17-runtime:1.17 not found: manifest unknown: manifest unknown
```

**Comment by rnc** [comment]
It appears there is a PR https://github.com/quarkusio/quarkus/pull/34882

**Comment by cescoffier** [comment]
I just opened a pr reverting to the 1.16.
