### ISSUE TITLE
Quarkus resteasy-reactive (RestClientBuilder) HTTP2

### ISSUE THREAD

**Issue by daloji** [quarkusio/quarkus#34896]
### Describe the bug

We are in the process of upgrading our services to http2. We use the RestClientBuilder client because the url of our services are dynamic. Normally HTTP2 is supported by the restEasy-reactive client. It works when the url is static (using **@RestClient** and 
 the url is static in application.poperties. **quarkus.rest-client."org.NetworkService ".uri=http://localhost:8080**
 but if you use   **RestClientBuilder.newBuilder().baseUrl(new URL("http://localhost:8080")) .build(OurService.class)**					   

```
 quarkus.rest-client."org.NetworkService".uri=http://localhost:8080
 quarkus.rest-client.http2=true
```

```
@RestClient
NetworkService netService;

public List getNetwork() {
 return netService.getNetwork();
}
````
HTTP2 Work  

and with RestClientBuilder

```
extensionsService =  RestClientBuilder.newBuilder()
			           .baseUrl(new URL("http://localhost:8080"))
			           .build(NetworkService.class);
extensionsService .getNetwork()
```
even if  **quarkus.rest-client.http2=true** is set we always use Http1 instead of Http2

HTTP2 not work in this case

configuration application.properties

### Expected behavior

http2 enable with RestClientBuilder

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /opt/apache-maven-3.8.5

**Comment by geoand** [comment]
Does it also not work for Quarkus 3.2?

**Comment by daloji** [comment]
> Does it also not work for Quarkus 3.2?

yes same state with Quarkus 3.2

**Comment by geoand** [comment]
Good catch!

https://github.com/quarkusio/quarkus/pull/34906 fixes the issue
