### ISSUE TITLE
Provide a @TemplateDir annotations to know which folders must be scanned to collect Qute template

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#34916]
### Description

In our Qute support https://github.com/redhat-developer/quarkus-ls we hard code the templates dir with `src/main/resources/templates` to know which files must be considered as Qute templates.

You did that too in Quarkus. But when a Quarkus extension like https://github.com/quarkiverse/quarkus-web-bundler defines a new custom folder (`src/main/resources/web`) we need in our tooling to hard code that again which is not very extensible.

I wonder if you could provide a new annotation `@TemplateDir` to defines the folders to scan:

* in Quarkus it will have a new class annotated with 

```java
@TemplateDir("templates")
public class QuarkusTemplateDirProvider {

}
```

* in Quarkus Web Bundler it will have a new class annotated with 

```java
@TemplateDir("web")
public class QuarkusWebBundlerTemplateDirProvider {

}
```

The `@TemplateDir` could even customize the user tags dir:

```java
@TemplateDir(dir = "my-templates",  tags="my-tags")
public class MyQuarkusTemplateDirProvider {

}
```

to scan user tags in the `src/main/resources/my-templates/my-tags`

@mkouba @FroMage @ia3andy what do you think about this idea?

**Comment by mkouba** [comment]
> You did that too in Quarkus. But when a Quarkus extension like https://github.com/quarkiverse/quarkus-web-bundler defines a new custom folder (src/main/resources/web) we need in our tooling to hard code that again which is not very extensible.

AFAIK such a custom folder is not supported, i.e. the templates from this directory are not validated etc.

**Comment by FroMage** [comment]
Not so sure, it seems https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/java/io/quarkiverse/web/bundler/deployment/WebAssetsScannerProcessor.java#L143 will produce `QuteTagsBuildItem`, but for validation we still need either parameter declarations in the tag, or a type-safe template declaration for them.

**Comment by mkouba** [comment]
> Not so sure, it seems https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/java/io/quarkiverse/web/bundler/deployment/WebAssetsScannerProcessor.java#L143 will produce `QuteTagsBuildItem`, but for validation we still need either parameter declarations in the tag, or a type-safe template declaration for them.

I'm not talking about type-safe expressions at all. Those templates are _not analyzed_ during the build at all (param declarations or type-safe templates would not help). They are just added manually at runtime: https://github.com/quarkiverse/quarkus-web-bundler/blob/main/runtime/src/main/java/io/quarkiverse/web/bundler/runtime/qute/WebBundlerQuteEngineObserver.java#L33-L40.

I'm still not sure it's a good idea to make the set of template directories extensible. However, if we decide to support this we will probably not use an annotation but a config property/build item. Therefore, I'm closing this issue.
