### ISSUE TITLE
registry.access.redhat.com/ubi8/openjdk-17-runtime:1.17 not found

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#34915]
### Describe the bug

Hello, 

The `registry.access.redhat.com/ubi8/openjdk-17-runtime:1.17` referenced in e.g. in extensions/container-image/container-image-docker/deployment/src/test/resources/openjdk-17-runtime and elsewhere does not exist in the [registry](https://catalog.redhat.com/software/containers/ubi8/openjdk-17-runtime/618bdc5f843af1624c4e4ba8?container-tabs=gti) at the time of filing this issue.

The latest tag is 1.16-1.1687182770 (again, at the time of writing now)

This fact breaks a build for me when I upgrade from 3.2.0.Final to 3.2.1.Final.

### Output of `uname -a` or `ver`

Linux karm 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.8 2023-07-18

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.2.0.Final works, 3.2.1.Final fails

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Already fixed by https://github.com/quarkusio/quarkus/pull/34882
