### ISSUE TITLE
External link is broken in Native Build Tips documentation page

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#34929]
### Describe the bug

The link at https://quarkus.io/version/main/guides/writing-native-applications-tips#managing-proxy-classes is broken.

Current link: https://www.graalvm.org/jdk-17/reference-manual/native-image/guides/configure-dynamic-proxies/

Found:
- ~https://www.graalvm.org/22.0/reference-manual/native-image/DynamicProxy/~
- ~https://www.graalvm.org/22.1/reference-manual/native-image/DynamicProxy/~
- ~https://www.graalvm.org/22.3/reference-manual/native-image/dynamic-features/DynamicProxy/~
- ~https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/DynamicProxy/~
- https://www.graalvm.org/latest/reference-manual/native-image/guides/configure-dynamic-proxies/

~Caveat:~
~It is possible that the link will break in the future if GraalVM docs structure changes again.~

### Expected behavior

External link should load.

### Actual behavior

External link doesn't load

### Additional information

SRC: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/writing-native-applications-tips.adoc

**Comment by gian1200** [comment]
I was trying to do a PR, but the link is referencing a `graalvm-version` variable.
`https://www.graalvm.org/%7Bgraalvm-version%7D/reference-manual/native-image/dynamic-features/Reflection/`.

Not sure where it is defined or even if it should be changed or a different variable should be used (or replaced with `latest`)

**Comment by geoand** [comment]
> Not sure where it is defined or even if it should be changed or a different variable should be used (or replaced with latest)

The docs intentionally mention a specific GraalVM (same with other tools like Maven).

**Comment by geoand** [comment]
But indeed in this case GraalVM doesn't seem to have those docs in any other place other than `latest`... 
cc @gsmet

**Comment by zakkak** [comment]
Yes, I guess that's due to the transition from the old GraalVM versioning to the new "JDK versioning".

@alina-yur is there a fixed link (like jdk-17 or similar) for `latest`, like it used to for 22.3, etc.?

We don't want our docs to point to `latest`, as Quarkus has versioned docs and older versions might need to reference older GraalVM docs.

**Comment by alina-yur** [comment]
hi @zakkak. Indeed we should have links for jdk 17 & jdk 20; right now this content is under /latest/, but latest will change. WE will work on this, thanks for the ping.

**Comment by geoand** [comment]
Thanks @alina-yur!

**Comment by zakkak** [comment]
> hi @zakkak. Indeed we should have links for jdk 17 & jdk 20; right now this content is under /latest/, but latest will change. We will work on this, thanks for the ping.

Thank you for the prompt reply @alina-yur, please let us know once there is a change.

**Comment by alina-yur** [comment]
hi @zakkak, we now have https://www.graalvm.org/jdk17/docs/ & https://www.graalvm.org/jdk20/docs/ URLs (thank you @olyagpl). There will also be `jdk21` links alongside `latest` once that is released.

**Comment by geoand** [comment]
Thanks @alina-yur!

@zakkak it seems like we would need to update our adoc to include this version for the GraalVM docs links instead of what we have now (which is `jdk-17`)

**Comment by zakkak** [comment]
Correct, ideally we would do this programmatically by removing the `-` from the `graalvm-version` variable. Any ideas how we can achieve this in asciidoc?
