### ISSUE TITLE
OIDC denies authorisation on MacOS

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#34922]
### Describe the bug

I have an application, which uses `@RolesAllowed` annotation and `quarkus-oidc` to protect http endpoints. To access these endpoints, I use obtain a tocken through  `AuthzClient` and use method `auth.oauth2()` from RestAssured. This works on Fedora 38 but fails on Mac Os 12.6

### Expected behavior

Responses should have http code 200

### Actual behavior

Responses have http code 401

### How to Reproduce?

1. git clone `git@github.com:quarkus-qe/quarkus-test-suite.git` 
2. `mvn clean verify -Dquarkus.platform.version=3.2.1.Final -Psecurity-modules -pl security/keycloak -Dit.test=KeycloakOidcSecurityIT#normalUserUserResource`

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

Mac with x86_64 processor, podman 4.5.1

**Comment by sberyozkin** [comment]
@fedinskiy I'm on Fedora, my guess is that something in the test setup does not work well on MacOS, what do logs say ?

**Comment by fedinskiy** [comment]
@sberyozkin this problem seems to be related to some problems on the side of podman machine (the bug can only be reproduced after another test failed on the same instance).

**Comment by sberyozkin** [comment]
Thanks @fedinskiy for narrowing it down
