### ISSUE TITLE
@UnlessBuildProperty is ignored on PanacheEntityResource

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#34938]
### Describe the bug

```
@UnlessBuildProperty(name = foo.enabled", stringValue = "false", enableIfMissing = true)
public interface BotResource extends PanacheEntityResource<BotEntity, Long> {
}
```

```
export FOO_ENABLED=false
quarkus dev
curl http://localhost:8080/q/openapi
```

That BotResource is still there.

I guess `@IfBuildProperty`, `@IfBuildProfile`, `@UnlessBuildProfile`, `@EndpointDisabled` all have same bug,  the real RESTEasy resource is generated on build time, so maybe these annotations are dropped.

### Expected behavior

The BotResource should be disabled.

### Actual behavior

The BotResource isn't disabled.

### Output of `uname -a` or `ver`

Darwin xxx 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by Sgitario** [comment]
I would not say this is a bug, but a feature request. However, https://github.com/quarkusio/quarkus/pull/34999 adds support for the build time condition annotations (and the RESTEasy Reactive runtime annotation as well).
