### ISSUE TITLE
ObjectMapper of @CustomSerialization has no effect

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#34934]
### Describe the bug

I have a REST method with the @CustomSerialization annotation.
According to the [documentation](https://quarkus.io/guides/resteasy-reactive#completely-customized-per-method-serialization) I have implemented the static class with the apply method. This method has an ObjectMapper as the first parameter.

The problem is the objectMapper has to be reinstanciate each time the method is called.

Concretely :

The addMixIn call has no effect.

```java
return objectMapper.addMixIn(Buggy.class, NoTypes.class).writer();
```

I must do like this to customize the objectMapper : 

```java
return new ObjectMapper().addMixIn(Buggy.class, NoTypes.class).writer();
```

This is because somewhere else in the application I have this : 

```java
@Inject
    ObjectMapper mapper;

    public void buggyServiceMethod() {

        try {


            Map<String, Buggy> complexBuggyMap = new HashMap<>();
            complexBuggyMap.put("bug2", new SimpleBug("bug3"));
            Buggy complexBug = new ComplexBug(new SimpleBug("simple bug"), complexBuggyMap);

            //The bug is here! As soon as I use the injected mapper to write a !!ComplexBug!!, the @CustomSerialization requires to instanciate a new ObjectMapper(). There is absolutely NO PROBLEM if instead of writing a ComplexeBug I write a SimpleBug, and this is why this bug is really tricky!
            mapper.writeValueAsString(complexBug); //comment this line and the bug disappear
            //If here I instanciate the ObjectMapper the the @CustomSerialization will work perfectely! => new ObjectMapper().writeValueAsString(complexBug);
            //If I write a SimpleBug, the bug doesn't occur.
            //Like this :
            //mapper.writeValueAsString(new SimpleBug("bug1")); //you can uncomment this line and you will see there is no problem to use the method object mapper parameter of the apply method
            
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }
```

The bug comes from my object model. I have an interface (Buggy) and two classes that implement it (SimpleBug and ComplexeBug)

There is no problem to use the objectMapper with the SimpleBug class. But if use the objectMapper with the ComplexeBug class then I need to reinstanciate the ObjectMapper each time for my MixIn to be applied

```java
public static class MyBuggyClass implements BiFunction<ObjectMapper, Type, ObjectWriter> {

        @Override
        public ObjectWriter apply(ObjectMapper objectMapper, Type type) {

            //The addMinxIn as no effect because an object mapper has been used somewhere else in the application to write a !ComplexeBug! -> no problem with SimpleBug!
            return objectMapper.addMixIn(Buggy.class, NoTypes.class).writer();
            //To apply the MixIn I must do this :
            // return new ObjectMapper().addMixIn(Buggy.class, NoTypes.class).writer();
            // Why do I need to instanciate a new ObjectMapper() ???
        }
    }
```

### Expected behavior

I don't have to reinstanciate the ObjectMapper class each time I want to use it.

The MixIn has been correctly applied.

```json
{
    "bug2": {
        "simpleBug": {
            "name": "simple bug"
        },
        "bugs": {
            "bug2": {
                "name": "bug3"
            }
        },
        "name": "simple bug"
    },
    "bug1": {
        "name": "bug1"
    }
}
```

### Actual behavior

The objectMapper parameter of the 
```java
 public ObjectWriter apply(ObjectMapper objectMapper, Type type)
```
seems to be corrupted or I don't know what's wrong with it.

As a result the MixIn has no effect. The "class" field should not be there

```json
{
    "bug2": {
        "simpleBug": {
            "class": "serialization.SimpleBug",
            "name": "simple bug"
        },
        "bugs": {
            "bug2": {
                "class": "serialization.SimpleBug",
                "name": "bug3"
            }
        },
        "name": "simple bug"
    },
    "bug1": {
        "name": "bug1"
    }
}
```

I think the bug is tricky because of my object model. The SimpleBug class doesnt cause the bug. Only the ComplexeBug implementation. This is what I don t understand.

### How to Reproduce?

[bug.zip](https://github.com/quarkusio/quarkus/files/12137208/bug.zip)

Start the application : 

1:  mvn compile quarkus:dev -Dquarkus.http.port=8085
2: run that GET http method : http://localhost:8085/hello/bug

The response is buggy : 
```json
{
    "bug2": {
        "simpleBug": {
            "class": "serialization.SimpleBug",
            "name": "simple bug"
        },
        "bugs": {
            "bug2": {
                "class": "serialization.SimpleBug",
                "name": "bug3"
            }
        },
        "name": "simple bug"
    },
    "bug1": {
        "name": "bug1"
    }
}
```

There is 3 ways to get around the bug : 

1 : 
In BuggyService, replace the line 27 : 
```java
mapper.writeValueAsString(complexBug);
```
by 
```java 
new ObjectMapper().writeValueAsString(complexBug);
```

2: 
In BugResource line 46, replace the line 
```java
return objectMapper.addMixIn(Buggy.class, NoTypes.class).writer();
```
by
```java
return new ObjectMapper().addMixIn(Buggy.class, NoTypes.class).writer();
```

3 : 
In BuggyService, replace the line 27 : 
```java
mapper.writeValueAsString(complexBug);
```
by 
```java 
objectMapper.writeValueAsString(new SimpleBug("bug"));
```

Then run the http GET request : 

```json
{
    "bug2": {
        "simpleBug": {
            "name": "simple bug"
        },
        "bugs": {
            "bug2": {
                "name": "bug3"
            }
        },
        "name": "simple bug"
    },
    "bug1": {
        "name": "bug1"
    }
}
```

The MixIn has been applied but none of these 3 workaround is acceptable.
The MixIn should be applied without the need to reinstanciate the ObjectMapper (1 and 2) and with both SimpleBug and ComplexeBug classes. (3)

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\dev\apache-maven-3.8.2

### Additional information

I use lombok. May be you will need to install the plugin if you use and IDE

**Comment by geoand** [comment]
As is mentioned in the Javadoc of `@CustomSerialization`, you should never change the `ObjectMapper` in your `BiFunction`.

Your working example does 

```java
return new ObjectMapper().addMixIn(Buggy.class, NoTypes.class).writer();
``` 

while it's almost certainly best to do:

```java
return objectMapper.copy().addMixIn(Buggy.class, NoTypes.class).writer();
```
