### ISSUE TITLE
Concecutive calls to a Vertx endpoint fail to propagate request scope

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#34949]
### Describe the bug

I try to use a `@RoutingFilter`  to set information to a request scoped bean which I will use later e.g. during a health check. This seems to work, but only for the first call. Every consecutive call fails to propage the request scoped bean.

### Expected behavior

Every call should propagate request scoped information set within a `@RoutingFilter` as expected

### How to Reproduce?

https://github.com/HerrDerb/quarkus-issue/tree/vertx-routes-filter-issue

### Quarkus version or git rev

3.2.2.Final

**Comment by geoand** [comment]
cc @mkouba

**Comment by xstefank** [comment]
Not sure what is the issue here. We have HealthCheck (blocking) on blockingExecutor and AsyncHealthCheck (non-blocking) on vertx executor - https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/QuarkusAsyncHealthCheckFactory.java

**Comment by HerrDerb** [comment]
@xstefank Any idea why the use case of my test ist not working?
bztw.,  is the negating `!` wanted on this line? On a first look it seems odd to me. https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-health/runtime/src/main/java/io/quarkus/smallrye/health/runtime/QuarkusAsyncHealthCheckFactory.java#L40

**Comment by xstefank** [comment]
Ah, I'm so sorry @HerrDerb, I totally missed you had a reproducer linked so I could try it out. And the fix is easy enough - https://quarkus.io/guides/smallrye-health#context-propagation-into-the-health-check-invocations.

**Comment by HerrDerb** [comment]
Oh wow, easy indeed. I did not see that. Thanks for pointing out
