### ISSUE TITLE
Quarkus Cache: @CacheKey does not work on interface methods

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#34947]
### Describe the bug

When a `@CacheResult` annotated interface method has `@CacheKey` annotated parameters, Quarkus cache ignores the `@CacheKey` annotation. For example:

```
@RegisterRestClient
public interface MyRestClient {
    @GET
    @Path("/hello")
    String hello(
        @QueryParam("c") String c);

    @CacheResult(cacheName = "my-cache")
    default String hello(
        @CacheKey @QueryParam("a") String a, 
        @CacheKey @QueryParam("b") String b,
        @QueryParam("c") String c) {
        return hello(c);
    }
}
```

### Expected behavior

`@CacheKey` is respected.

### Actual behavior

`@CacheKey` is ignored.

`cacheKeyParameterPositions` in [`CacheInterceptor.getCacheKey`](https://github.com/quarkusio/quarkus/blob/000c18be66ffc8530b561f826fad03b88d69e939/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInterceptor.java#L152C20-L152C20) is empty, thus resulting in the wrong cache key being generated.

### How to Reproduce?

I have made a reproducing project here https://github.com/AndreasPetersen/quarkus-cache-key-interface/tree/main.

The project includes a `MyRestClient` interface with an annotated `@CacheResult` method with `@CacheKey` annotated parameters. In the `GreetingResource`, the cached method is called first, and then a second call is made using the Quarkus Cache programmic API, where I make a `CompositeCacheKey` that should match the `@CacheKey` annotated parameters.

A `GreetingResourceTest` is available, that verifies that the client REST endpoint is only called once, but the test fails because of the described bug.

### Output of `uname -a` or `ver`

Linux codespaces-8fce81 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Microsoft-7626293 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Microsoft-7626293 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.8.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle, see reproducer project

**Comment by geoand** [comment]
This has been fixed in #32406
