### ISSUE TITLE
[Extension Proposal] Git config source

### ISSUE THREAD

**Issue by morphy76** [quarkusio/quarkus#34942]
### Description

Hello

I would like to propose the subject extension  so that providing additional flexibility while externalizing configurations among runtime environments.

Namely, a Microprofile config source which is somehow aware of the execution environment, e.g. dev, integration or production.

So far, I know 2 major options:

* a service approach in the style of SpringBoot config server,
* or delegating packaging tools, e.g. helm templates with value files per environment.

Within the limits of my knowledge of other options, I find the server approach and the packaging tool approach a sort of workaround: the former because it adds a component to maintain, the latter because it couples configuration and deployment.

For this purpose I would like to have an extension which binds an SCM, GIT in this case, to provide an environmental aware config source, namely a config source which can bind different branches/tags of a repository to retrieve versioned property values.

Such extension would be configured according the following draft properties:

* **quarkus.git-config-source.uri** to connect to a git repository, mandatory
* **quarkus.git-config-source.credentials.*** additional properties to be authorized, optional
* **quarkus.git-config-source.tag** branch or tag representing the current execution environment, mandatory
* **quarkus.git-config-source.*-files** comma separated list of property/yaml files to load in the config source, with valuable defaults

This extension would leverage the JGit extension already available in the quarkiverse.
 
Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-git-config-source

### Short description

Microprofile config source to retrieve values form a git repository

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- externalized configuration
- cloud
- microprofile config

### Team Members

- I'm available to maintain this extension

**Comment by gastaldi** [comment]
Please add it as a new module to https://github.com/quarkiverse/quarkus-config-extensions
