### ISSUE TITLE
Unable to supply ClientHttpEngine to RestEasy Reactive Client

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#34969]
### Describe the bug

Using RestEasy client I can use the following code as documented in [RESTEasy ClientHttpEngine implementations](https://docs.jboss.org/resteasy/docs/6.2.4.Final/userguide/html/ch50.html#transport_layer):
`ResteasyClient client = ((ResteasyClientBuilder)ClientBuilder.newBuilder()).httpEngine(myEngine).build();
`

When using resteasy reactive, this code throws an exception: `java.lang.ClassCastException: class org.jboss.resteasy.reactive.client.impl.ClientBuilderImpl cannot be cast to class org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder (org.jboss.resteasy.reactive.client.impl.ClientBuilderImpl and org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder are in unnamed module of loader 'app'`

### Expected behavior

I desire to configure ClientHttpEngine with retry options

### Actual behavior

ClassCastException

### Additional information

Probably want to port the custom quarkus versions of resteasy jars back to the resteasy project.

**Comment by Sgitario** [comment]
You're trying to use internal implementations from the REST Client Classic (`((ResteasyClientBuilder)ClientBuilder.newBuilder()).httpEngine(myEngine)` in REST Client Reactive (which internally is using very different components, e.g. the Vert.x HTTP Client). 
Therefore, this is not going to work and can't be supported. 

In REST Client Reactive, you can configure the internal HTTP Client by providing a custom HTTP options instance as described in [here](https://quarkus.io/guides/rest-client-reactive#use-custom-http-options).

If what you want to achieve is to implement retries, you can annotate the REST Client interface (or the methods) with the `@Retry` annotation:

```java
@RegisterRestClient(configKey = "my-api")
@Retry(delay = 1, delayUnit = ChronoUnit.SECONDS, maxRetries = 5)
public interface MyRestClient {
 ....
}
```

You can find more information about this annotation in the Smallrye Fault Tolerance Quarkus extension: https://quarkus.io/guides/smallrye-fault-tolerance
