### ISSUE TITLE
Use gradle model instead of string parsing for manipulating gradle files

### ISSUE THREAD

**Issue by Dufgui** [quarkusio/quarkus#3497]
**Description**
Actually we use string parsing and manipulation to add extension, complete existing gradle file, or simply read gradle files. It's fragil, On maven side, we use an external model and parser. 

**Implementation ideas**
I am just dig a little more to not use string and delegate parse of model to gradle lib.
I see how eclipse do it:
https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.kotlin/build.gradle
https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.kotlin/src/main/java/org/eclipse/buildship/kotlin/internal/GradleKotlinScriptTemplateProvider.java#L80

And with ProjectConnection we can load the groovy model too, but I don't know the limitation and we need all gradle core as dependency. 

see https://github.com/quarkusio/quarkus/pull/3475#discussion_r313254631

**Comment by Dufgui** [comment]
could you add gradle label. and maybe assign to me if nobody want it.

**Comment by Dufgui** [comment]
In fact I am thinking my self, it could be interesting to have an independent project wich manage all kind of model externaly (maven, gradle, ivy , sbt ...) out of quarkus.... but for now I will manage gradle first

**Comment by gwenneg** [comment]
The Gradle Tooling API could help here, but it also has a lot of limitations. When I worked on the add extension feature, I tried to push the tooling API usage as much as I could, but it didn't help that much.

**Comment by Dufgui** [comment]
The gradle approch is based on script not on model.:
See https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java

I don't how you try to start but GradleConnector and projectConnection seems to be too limited for us.

So I think, we can choose one of this option : 

-  implement all handlers in https://github.com/gradle/gradle/tree/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl to provide a noop dsl, wich just store data and provide a dumper on it, in case of change
-  read directly the groovy (and kotlin) AST
-  ask gradle to provide it with an issue
-  any other ideas?

**Comment by gwenneg** [comment]
There's also a model approach in Gradle using the [Tooling API](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html), this is what I used. We're already using some parts of it in `quarkus-gradle-plugin`.

**Comment by Dufgui** [comment]
I see it. The connector. It seems limited

Le mar. 13 août 2019 à 20:07, Gwenneg Lepage <notifications@github.com> a
écrit :

**Comment by Dufgui** [comment]
The more I think about it, the more I think we must not integrate gradle but just the AST of groovy and Kotlin.
Groovy:
http://docs.groovy-lang.org/next/html/gapi/org/codehaus/groovy/ast/builder/AstBuilder.html
For Kotlin I will search it.

**Comment by Dufgui** [comment]
I test 2 approachs. On différent branches. I will push the gradle tooling api version. 

But we have a small limitation: we cannot get dependencies from zipped project. It’s not used. So we can go for it I think

**Comment by soberich** [comment]
@Dufgui Could we try to use 5.6 straight away? It has more in common with upcoming 6.0.I am eager for better Gradle support as now it's really a room for improvement. Can't really run non simplistic Quarkus projects with Gradle now. Great work. Any other plans for Gradle? So we can form issues/PR out of those?
