### ISSUE TITLE
Quarkus is affected by criteria query issue in Hibernate

### ISSUE THREAD

**Issue by vmuzikar** [quarkusio/quarkus#34986]
### Describe the bug

Quarkus 3.2.2 is affected by [HHH-16905](https://hibernate.atlassian.net/browse/HHH-16905). This is fixed in Hibernate 6.2.7, Quarkus needs to adopt this version.

This issue is affecting Keycloak that consumes Hibernate through Quarkus.

**Comment by geoand** [comment]
This will happen soon, see https://github.com/quarkusio/quarkus/pull/34950#issuecomment-1647764671

**Comment by Sanne** [comment]
The upgrade PR is now open: #34991

**Comment by vmuzikar** [comment]
Thanks for the fix! Will this get backported to Quarkus 3.2?

**Comment by geoand** [comment]
Yes, it will
