### ISSUE TITLE
Comments inline are not skipped in application.properties

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#3499]
**Describe the bug**
If my `application.properties` looks like:

```
# configure your datasource
quarkus.datasource.url = jdbc:mariadb://mariadb:3306/demodb # <1>
%dev.quarkus.datasource.url = jdbc:mariadb://127.0.0.1:3306/demodb # <2>
quarkus.datasource.driver = org.mariadb.jdbc.MariaDbDataSource
quarkus.hibernate-orm.dialect = org.hibernate.dialect.MariaDB103Dialect 
quarkus.datasource.username = demo
quarkus.datasource.password = password
```

Then the URL string is also the comments part `# <1>`.

**Expected behavior**
Inline comments should be skipped.

**Actual behavior**
The URL string is also the comments part `# <1>` so it makes the connection fail.

**To Reproduce**
1. Create an `application.properties` file with inline comments.
2. Start in dev mode.
**Configuration**
```properties
# configure your datasource
quarkus.datasource.url = jdbc:mariadb://mariadb:3306/demodb # <1>
%dev.quarkus.datasource.url = jdbc:mariadb://127.0.0.1:3306/demodb # <2>
quarkus.datasource.driver = org.mariadb.jdbc.MariaDbDataSource
quarkus.hibernate-orm.dialect = org.hibernate.dialect.MariaDB103Dialect 
quarkus.datasource.username = demo
quarkus.datasource.password = password
```

**Environment (please complete the following information):**
- Quarkus version: 0.20.0

**Additional context**
The workaround is to just use new line per comment.

**Comment by gsmet** [comment]
I don't think it's a bug.

AFAIK, Java property files do not support inline comments.

We fixed the callouts recently on the website to avoid this very issue.

**Comment by lordofthejars** [comment]
Yeah maybe not a bug and could be changed to feature, but maybe we could support this so `application.properties` is documentation friendly.

**Comment by gsmet** [comment]
Well, documentation is supposed to remove the callouts when copy/pasting. At least, that's what Asciidoc does.

I don't think implementing our own property files parser is a good idea.

**Comment by lordofthejars** [comment]
Yeah that's true. The problem I faced doing copy-paste directly from `adoc`. Ok nevermind probably a crazy idea of my tired mind in my last week before PTO 😆

**Comment by gsmet** [comment]
Yeah, let's close it, I don't think it's a good idea to diverge from the default properties format.
