### ISSUE TITLE
Quarkus OIDC configurable MAX_COOKIE_VALUE_LENGTH

### ISSUE THREAD

**Issue by tronez** [quarkusio/quarkus#34995]
### Description

I would like to change value of 'MAX_COOKIE_VALUE_LENGTH' via configuration file, since we are getting: 

"Session cookie length for the tenant Default is equal or greater than 4096 bytes. Browsers may ignore this cookie which will cause a new challenge for the authenticated users. Recommendations: 1. Set 'quarkus.oidc.token-state-manager.split-tokens=true' to have the ID, access and refresh tokens stored in separate cookies. 2. Set 'quarkus.oidc.token-state-manager.strategy=id-refresh-tokens' if you do not need to use the access token as a source of roles or to request UserInfo or propagate it to the downstream services. 3. Register a custom 'quarkus.oidc.TokenStateManager' CDI bean with the alternative priority set to 1."
 
 Normally i would change keycloak configuration so tokens would be a lot smaller, but for some reason no one in company can change configuration.

### Implementation ideas

BearerAuthenticationMechanism and CodeAuthenticationMechanism are only two classes that extend AbstractOidcAuthenticationMechanism. If i understood it correctly only latter class requires change since MAX_COOKIE_VALUE_LENGTH is hardcoded there and used in method processSuccessfulAuthentication().

Config name proposal
-if null it should be defaulted to 4096 bytes
-maybe it should be range? [4096-X] bytes, where X should be discussed
quarkus.oidc.authentication.cookie-session-max-size:

**Comment by sberyozkin** [comment]
@tronez It can't be controlled at the Keycloak level, this is the cookie creates by Quarkus and controlling the session cookie size can only be controlled as suggested in this log message - with one more advice added recently - disable the session cookie encryption if you'd like (`quarkus.oidc.token-state-manager.encryption-required=false`) - it will definitely decrease the session cookie size.
Please also watch #13239 (it will help with Option 3 and @michalvavrik is investigating how best to fix it).

In meantime I'll have to close this issue as Quarkus itself can't control the session cookie size - it is not something that can be configured

**Comment by sberyozkin** [comment]
@tronez 

>Normally i would change keycloak configuration so tokens would be a lot smaller

You are right - that can be an option as well :-), but indeed, you can easily enough control it at the Quarkus level, 4 options are available, cheers

**Comment by sberyozkin** [comment]
@tronez Options 1, 2 above will work, or disabling the encryption (in the safe network) - will also likely help, and soon enough - Option 3 will also work
