### ISSUE TITLE
quarkus-kubernetes Extension ignores multiple sidecars properties

### ISSUE THREAD

**Issue by theWalli** [quarkusio/quarkus#35006]
### Describe the bug

When using the quarkus-kubernetes extension and configuring it to add a side car container to the deployment spec, some of the configuration properties, that are documented under https://quarkus.io/guides/deploying-to-kubernetes, are ignored and take no effect on the generated kubernetes spec file.

Specifically, the properties

- quarkus.kubernetes.sidecars."sidecars".image-pull-policy
- quarkus.kubernetes.sidecars."sidecars".resources.limits.cpu
- quarkus.kubernetes.sidecars."sidecars".resources.limits.memory
- quarkus.kubernetes.sidecars."sidecars".resources.requests.cpu
- quarkus.kubernetes.sidecars."sidecars".resources.requests.memory

Do not result in the desired kubernetes spec output.

Example properties:
```
quarkus.kubernetes.sidecars.my-sidecar.image-pull-policy=always
quarkus.kubernetes.sidecars.my-sidecar.resources.requests.memory=200Mi
quarkus.kubernetes.sidecars.my-sidecar.resources.limits.memory=200Mi
quarkus.kubernetes.sidecars.my-sidecar.resources.requests.cpu=100m
quarkus.kubernetes.sidecars.my-sidecar.resources.limits.cpu=100m
```

### Expected behavior

An entry in the kubernetes spec file for the side car container is generated with the properties:

```
          name: my-sidecar
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
```

### Actual behavior

A sidecar container entry in the kubernetes spec file is generated missing the configured properties (imagePullPolicy is set to the default of IfNotPresent and the resources field is completely missing):

```
          name: my-sidecar
          imagePullPolicy: IfNotPresent
```

### How to Reproduce?

1. Follow the example of https://quarkus.io/guides/deploying-to-kubernetes
2. Add side car configurations from the above example
3. Run mvn package
4. Check target/kubernetes/kubernetes.yml

### Output of `uname -a` or `ver`

$ uname -a Linux NB-PF3ALRDL 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

$ java -version openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu120.04.1) OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

### Quarkus version or git rev

2.16.8.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

$ ./mvnw --version Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /home/user/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.6, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.10.102.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by Sgitario** [comment]
The property `quarkus.kubernetes.sidecars.my-sidecar.image-pull-policy=Always` was working for me in Quarkus 3.x. Can you try the latest Quarkus 3.2.2.Final?
About the resource requirements properties, https://github.com/quarkusio/quarkus/pull/35013 should fix this issue.

**Comment by theWalli** [comment]
You are right, with Quarkus 3.2.2.Final `quarkus.kubernetes.sidecars.my-sidecar.image-pull-policy=always` is working. Thank you!
