### ISSUE TITLE
`@ConfigProperty` injection semantics change when `quarkus-spring-di` is present and `@Inject` is used (regression in Quarkus 3)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#35011]
### Describe the bug

My project is using `quarkus-spring-data-jpa` which brings in `quarkus-spring-di` transitively.
Since we decided to use constructor injection where possible, we have decided to set `quarkus.arc.auto-inject-fields=false` a long time ago and so in QuarkusTests (that do not support constructor injection) we are using e.g.:
```
@Inject
@ConfigProperty("foo")
List<String> foo;
```
(notice the explicit `@Inject`)

With Quarkus 2.16.8, the following config is mapped to a two elements list, just as expected:
```
foo=bar1,bar2
```
But with Quarkus 3.2.2 I'm getting a single element list (value `bar1,bar2`).

I suppose `spring-di` gets in the way and injects the property on it's own terms without the splitting logic that normally takes place here.

This is especially confusing when you inject the same config property in a test as in the class under test that uses constructor injection -> boom, mismatch!

### Expected behavior

`@ConfigProperty` don't change just because `quarkus-spring-di` is one the classpath (which I haven't defined directly)

### Actual behavior

`@ConfigProperty` list injection breaks

### How to Reproduce?

1. extract [q_config-list-spring-di.zip](https://github.com/quarkusio/quarkus/files/12165372/q_config-list-spring-di.zip)
2. `mvn clean test`

### Quarkus version or git rev

3.2.2.Final

### Additional information

Sure, we could leave `quarkus.arc.auto-inject-fields` untouched to avoid this problem but just by choosing `quarkus-spring-data-jpa` I haven't really said: "I want Spring DI".

I checked the 3.x migration guides and found nothing on that topic.

I first thought it has something to do with yaml but the issues also occurs with vanilla properties config (as shown in the reproducer).

*Workaround*:
Inject `String` (and not a list) and split it yourself.

**Comment by famod** [comment]
Um, why is `spring-di` even there in the first place? I removed it from the runtime and the deployment module and all tests are still running ok locally, even the integration tests (haven't tried native though).
If that's the fix, I'll happily provide a PR.

**Comment by geoand** [comment]
I will have a look

**Comment by geoand** [comment]
This is caused by #31826, looking into a fix now

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/35015 should fix the issue

**Comment by famod** [comment]
@geoand cool, will give it a try!

But is spring-di even required for spring-data-jpa?

**Comment by geoand** [comment]
Not strictly, but in Spring proper you get it

**Comment by famod** [comment]
I must say I'd really prefer to not have spring-di and I guess most other users would agree that are simply looking for a repository pattern data access solution (instead of an active record pattern like panache).
Would it be possible to remove that dependency or make it optional somehow? I know it could be a breaking change for some users but if the migration guide documents to add spring-di for those cases it should be ok.

PS: I would create a separate issue for that and would try to help where I can.

**Comment by geoand** [comment]
It's too big of a breaking change and there is no other extension we could use to make it a conditional dependency, so I'm going to leave it as is

**Comment by famod** [comment]
I see. What about a kill switch for spring-di, effectively disabling the extension?

**Comment by geoand** [comment]
Sure, if you want to add some kind of build time property (and test it with the application you have in mind), I'd approve that.
