### ISSUE TITLE
Add build-time property to disable `quarkus-spring-di`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#35023]
### Description

As discussed [here (and the subsequent comments)](https://github.com/quarkusio/quarkus/issues/35011#issuecomment-1651260879), it can make sense to disable `quarkus-spring-di`, e.g. when you just want `spring-data-jpa` features without any spring injection support (which might increase the risk of issues/side effects, like #35011).

**Comment by famod** [comment]
I'll take this issue once I find some time for it.

**Comment by geoand** [comment]
👌🏼

**Comment by geoand** [comment]
I had a few minutes to spare, so [here](https://github.com/quarkusio/quarkus/pull/35082) it is.
