### ISSUE TITLE
resteasy-reactive-client does not work outside of an Arc container

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#35038]
### Describe the bug

Creating a resteasy proxy from QuarkusRestClientBuilder outside of an Arc container causes NPE.

### Expected behavior

Because I can programmatically create a QuarkusRestClientBuilder, I expected that I could use it without Arc.

### Actual behavior

NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.instance(java.lang.Class, java.lang.annotation.Annotation[])" because the return value of "io.quarkus.arc.Arc.container()" is null

	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:308)
	at io.quarkus.rest.client.reactive.runtime.QuarkusRestClientBuilderImpl.build(QuarkusRestClientBuilderImpl.java:229)
	at com.example.q4p.TrialTest.createClientBuilder(TrialTest.java:23)
```

### How to Reproduce?
```
class TrialTest {
  @Path("/test")
  public interface SaySomething {
    @GET
    @Path("hello")
    String hello();
  }

  @Test
  void createClientBuilder() {
    String resp = QuarkusRestClientBuilder.newBuilder()
        .baseUri(URI.create("http://localhost:8080")).build(SaySomething.class).hello();
    Assertions.assertEquals("hello", resp);
  }
}
```

### Output of `uname -a` or `ver`

Darwin YGDMXD4XYJ.corp.proofpoint.com 21.6.0 Darwin Kernel Version 21.6.0: Thu Jun  8 23:56:13 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn -v  Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c) Maven home: /opt/homebrew/Cellar/maven/3.9.2/libexec Java version: 17.0.6, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "12.6.7", arch: "aarch64", family: "mac"

### Additional information

- Should I be able to use resteasy-reactive-client standalone?
- Should resteasy-reactive-client be used with a different CDI?

**Comment by geoand** [comment]
What @Ladicek says

**Comment by chonton** [comment]
Could you please document this limitation.

**Comment by geoand** [comment]
That makes sense.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/35060 should hopefully clarify things
