### ISSUE TITLE
content-length header is kept in Response Header even though response size is more than 8 KB

### ISSUE THREAD

**Issue by Bonythomasv** [quarkusio/quarkus#35044]
### Describe the bug

if the size is more than 8KB , content-length header should not be present and transfer-encoding should have value of chunked. if less than 8 KB transfer-encoding should not be present , but content-length should be present. 

This is cause Nginx to reject the response and clients calling the API receives 502 error.

### Expected behavior

if the size is more than 8KB , content-length header should not be present and transfer-encoding should have value of chunked.

### Actual behavior

even with response size greater than 8 KB content-length header is coming in response header. 

### How to Reproduce?

1. create a Quakus App with 3.2.2-FINAL version 
2. create an Endpoint that returns more than 8 KB data. 
3. observer the response header, it has content-length and transfer-encoding is present. 

Fix: 
ServerSerialisers.class in rest-easy library should be removing content-length header based on this condition. but Since we are not using EqualIgnore case, it's skipping past this step.

<img width="922" alt="Screenshot 2023-07-26 at 1 49 01 PM" src="https://github.com/quarkusio/quarkus/assets/15947082/d433f4f8-ae46-47b9-9824-159d74ee3595">

### Output of `java -version`

17

### Quarkus version or git rev

3.2.2-FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.2

**Comment by geoand** [comment]
I was not able to reproduce the problem therefore I am reluctant to accept https://github.com/quarkusio/quarkus/pull/35045. Any chance you can upload a sample that behaves as you mentioned?

**Comment by Bonythomasv** [comment]
I can't upload my project, but let me work on getting sample project.,

But I've noticed that a similar implementation and Bug is reported and fixes for quarks Azure functions. and this PR uses EqualIgnoreCase.

https://github.com/quarkusio/quarkus/issues/31871
https://github.com/quarkusio/quarkus/pull/33836/files

**Comment by geoand** [comment]
A sample would be great

**Comment by tbkahuna48** [comment]
If you look at the debug code from IntelliJ for the rorg.jboss.resteasy.reactive.server.core.ServerSerialisers code :

In order to prevent the dual header problem (both content-length and transfer-encoding) for the following code 
- IntelliJ shows the actual header value {header: transfer-encoding) which is being compared to "Transfer-Encoding" and which seems to be case sensitive since the statement controlled by the if is never executed.
 It seems the fix would be to make the header collection a case insensitive collection or force both strings to the same case for the compare.

**Comment by Bonythomasv** [comment]
@geoand I'm running into some technical local issues with creating a sample app.
but here is the scenario, that's would help to reproduce the issue.
1. create one Quarks API API1 and 2nd API API2
2. Let API2 returns more than 8KB data.
3. Make API1 call API2 and Stream the response from API2 in APi1. ( simply return the Response Object). 
4. you can find that API response header has both content-length and transfer-encoding when response size is above 8 KB.

**Comment by geoand** [comment]
That's similar to what I tried and failed in reproducing it.

That's exactly why I want a sample: there might be some weird corner case we are not covering well and I would like to find it

**Comment by Bonythomasv** [comment]
These the libraries we are using, 

<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-reactive-jackson</artifactId>
		</dependency>


		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-reactive-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-reactive</artifactId>
			<exclusions>
				    <exclusion>
						<groupId>io.netty</groupId>
						<artifactId>netty-handler</artifactId>
				    </exclusion>
			</exclusions>  
		</dependency>




		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-reactive</artifactId>
			<exclusions>
					<exclusion>
						<groupId>io.netty</groupId>
						<artifactId>netty-handler</artifactId>
					</exclusion>
			</exclusions>
		</dependency>

**Comment by tbkahuna48** [comment]
Ok, let me see what we can do.

**Comment by Bonythomasv** [comment]
@tbkahuna48 did you get a chance to provide a sample project?

**Comment by Bonythomasv** [comment]
@geoand  i've created a sample application to mimic the issue.
https://github.com/Bonythomasv/code-with-quarkus --- **API that returns a JSON response of more than 8-KB** https://github.com/Bonythomasv/code-with-quarkus-Rest-client --- **Provider service that calls the 8-kb service**

<img width="1326" alt="Screenshot 2023-08-14 at 2 09 17 PM" src="https://github.com/quarkusio/quarkus/assets/15947082/f347ce60-b383-498f-9868-a2607666f742">

attached screenshot is the API that return both transfer-encoding and content-length headers.

**Comment by tbkahuna48** [comment]
The problem was with returning a response from a backend which already had thee header. Which was remediated by creating a proper response.

However, this piece of code appears to not be case insensitive and if its intention is to prevent both headers than it doesn't work.
we typically use CaseInsensitiveMap to store header KV

**Comment by Bonythomasv** [comment]
@geoand please let me know if you need anything additional to reproduce the issue. appreciate the help.

**Comment by geoand** [comment]
@Bonythomasv unfortunately I can't access the sample projects you have added.

**Comment by Bonythomasv** [comment]
[code-with-quarkus-master.zip](https://github.com/quarkusio/quarkus/files/12398287/code-with-quarkus-master.zip)
[code-with-quarkus-Rest-client-master.zip](https://github.com/quarkusio/quarkus/files/12398288/code-with-quarkus-Rest-client-master.zip)

@geoand  attaching the Zip files of both repo's here as i don't have a way to make this repo public. let me know if you need anything else from my side.

**Comment by Bonythomasv** [comment]
@geoand 
now that the PR is merged, which Version of Quarkus will have the Fix baked in?

**Comment by geoand** [comment]
Both the next versions of 3.2 and 3.3 should include the fix

**Comment by Bonythomasv** [comment]
@Geoand are you planning to release next version of 3.2.X this week?

**Comment by geoand** [comment]
Unlikely

**Comment by linktech1** [comment]
Is there any documentation or guidance on returning a Response object from external service directly from a service? The requirement is to stream external service Response through the service and not read the entire response into memory.

**Comment by geoand** [comment]
@linktech1 I would open a Github Discussion if I were you
