### ISSUE TITLE
Document supported libraries in OTel and Micrometer extension guides

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#35053]
### Description

We need to provide documentation on what libraries are supported and instrumented with OpenTelemetry and Micrometer.
There are a few places where this information can be extracted.

For OpenTelemetry:
* Check inside: https://github.com/quarkusio/quarkus/tree/main/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation
* Check extensions that use the OpenTelemtry tracer capability: https://github.com/quarkusio/quarkus/blob/df74f8644b55c087e72b5065083683bf4aa7dd39/core/deployment/src/main/java/io/quarkus/deployment/Capability.java#L105C18-L105C18

For Micrometer:
* Check folder https://github.com/quarkusio/quarkus/tree/main/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder
* Check extensions that use the METRICS capability or the MetricsCapabilityBuildItem.

Other Quarkiverse extensions might be using the capabilities and instrumenting the code if present... We should mention that but not list them.

**Comment by mskacelik** [comment]
Gonna have a look at it.

**Comment by brunobat** [comment]
Hi @mskacelik.
Any update?

**Comment by mskacelik** [comment]
Hi Bruno. I didn't notice that yesterday you were no longer PTO. When it comes to my task I have written the technologies that are actively using OTEL and micrometer, can you maybe tell me where this "documentation of consumer technologies" is gonna be displayed. And maybe what other info would you like to include (if its only the list of consumers, or some info about them, link to their documentation, maybe the version where they start to implement these technologies). On top of that If I have to write it in specific markup language.
