### ISSUE TITLE
Use of hibernate search 6.2

### ISSUE THREAD

**Issue by NoX1337** [quarkusio/quarkus#35086]
### Description

In the current version 3.2.2.Final of Quarkus hibernate-orm 6.2.0.Final is used, but not 6.2.0.Final of hibernate-search. Instead 6.1.7.Final is used for
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-hibernate-search-orm-elasticsearch</artifactId>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-elasticsearch-java-client</artifactId>
</dependency>

Manual override of the hibernate search dependencies to 6.2.0.Final is not working with the current build, as quite a few underlying 6.1.7.Final dependencies are used in the whole elastic setup of Quarkus.

Feature request: update all org.hibernate.search dependencies to 6.2.0.Final.

Reason: 6.2.0.Final of hibernate-search is significantly more powerful than older versions.

**Comment by gsmet** [comment]
Hibernate ORM and Hibernate Search are not following the same release cycles. So there's no problem using Search 6.1 with ORM 6.2. They are compatible.

Hibernate Search 6.2 will be used in Quarkus 3.3 (but ORM might be updated to 6.3 before we release, again, there's no correlation here).

**Comment by yrodiere** [comment]
To expand on Guillaume's (correct) answer, you can find information about compatiblity between Hibernate Search versions and Hibernate ORM versions:

* [here](https://hibernate.org/search/releases/#compatibility-matrix) for the latest versions
* on each series' dedicated page, e.g. [here](https://hibernate.org/search/releases/6.2/#compatibility), for a given version of Hibernate Search
