### ISSUE TITLE
Mocking Singleton does not work even when using  @MockitoConfig(convertScopes = true)

### ISSUE THREAD

**Issue by denysandriyanov** [quarkusio/quarkus#35080]
### Discussed in https://github.com/quarkusio/quarkus/discussions/35071

<div type='discussions-op-text'>

<sup>Originally posted by **denysandriyanov** July 27, 2023</sup>
I want to mock RecoveryService, it's scope is @Singleton.

Before Quarkus update i was using
@InjectMock(convertScopes=true)
and it worked

Now, with quarkusPluginVersion=3.2.2.Final I try to mock it like that

    @InjectMock
    @MockitoConfig(convertScopes = true)
    RecoveryService recoveryService;
    
    
and still getting:
Invalid use of io.quarkus.test.InjectMock - the injected bean does not declare a CDI normal scope but: jakarta.inject.Singleton

Please help.</div>

**Comment by Ladicek** [comment]
Do you have a reproducer please?

**Comment by denysandriyanov** [comment]
no, i do not have one i am afraid. Just try to mock any singleton bean

**Comment by mkouba** [comment]
It's very likely a bug on this line: https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/SingletonToApplicationScopedTestBuildChainCustomizerProducer.java#L58. It should read `!instance.target().asField().hasAnnotation(INJECT_MOCK)` instead...

Anyway, I'll modify the existing test to use `@MockitoConfig`, verify the fix and send a PR shortly.

**Comment by hnarange** [comment]
Hi, 

I updated the quarkus version but still getting below error on mocking Singleton service with  @InjectMock and @MockitoConfig(convertScopes = true) annotations.

`Invalid use of io.quarkus.test.InjectMock - the injected bean does not declare a CDI normal scope but: jakarta.inject.Singleton`

I tried with both quarkus 3.2.3.Final and 3.3.0.  
It's failing here: https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5-mockito/src/main/java/io/quarkus/test/junit/mockito/internal/CreateMockitoMocksCallback.java#L100 

Could someone please have a look?

**Comment by manovotn** [comment]
@hnarange can you please provide a reproducer?
Martin's PR fixing this issue has a test using both `@InjectMock` and `@MockitoConfig(convertScopes = true)` and that passes so we'll need more details.

**Comment by connorsadler** [comment]
If anyone else finds this thread, we have seen this issue when using a Singleton bean being produced from a factory method (bean producer method)
@InjectMock and @MockitoConfig(convertScopes = true) do not seem to work, until I mark the factory method explicitly as @Produces
(Usually you don't have to do this Quarkus, but to get @InjectMock and @MockitoConfig to work, it seems to be necessary)

This was using Quarkus 3.7.2
I have a minimal sample if the Quarkus devs need it

**Comment by manovotn** [comment]
> If anyone else finds this thread, we have seen this issue when using a Singleton bean being produced from a factory method (bean producer method) @InjectMock and @MockitoConfig(convertScopes = true) do not seem to work, until I mark the factory method explicitly as `@Produces` (Usually you don't have to do this Quarkus, but to get @InjectMock and @MockitoConfig to work, it seems to be necessary)
> 
> This was using Quarkus 3.7.2 I have a minimal sample if the Quarkus devs need it

Feel free to open new issue with the reproducer and we can look into it.
