### ISSUE TITLE
redis cache missing cacheName when use custom prefix

### ISSUE THREAD

**Issue by JackyAnn** [quarkusio/quarkus#35094]
### Describe the bug

When using custom cache.redis.prefix

The cacheName set in @CacheResult during key generation is missing
*config*
```
cache:
    redis:
      prefix: iot
      key-type: java.lang.String
      value-type: java.lang.String
```
*code*
```
package ltd.doorlink.redis;

import io.quarkus.arc.Unremovable;
import io.quarkus.cache.CacheResult;
import io.quarkus.redis.datasource.RedisDataSource;
import io.quarkus.redis.datasource.value.ValueCommands;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import java.io.Serializable;
import org.jboss.logging.Logger;
import org.junit.jupiter.api.Test;

/**
 * @author JackyAnn
 */
@QuarkusTest
public class RedisTest {
  @Inject private Logger logger;
  @Inject private RedisDataSource redisDataSource;


  @Test
  public void setAndGet(){
    RedisCacheTest redisCacheTest = new RedisCacheTest("test");
    ValueCommands<String, RedisCacheTest> commands = redisDataSource.value(RedisCacheTest.class);
    commands.set("test", redisCacheTest);
    logger.info("--->" + commands.get("test"));
    
    
    logger.info("--->" + getRedisStringCacheTest("string"));
    logger.info("--->" + getRedisObjectCacheTest("object"));


  }

  @CacheResult(cacheName = "StringResult")
  public String getRedisStringCacheTest(String key){
    logger.info("--->" + "load data");
    return "redis cache test";
  }

  @CacheResult(cacheName = "ObjectResult")
  public RedisCacheTest getRedisObjectCacheTest(String key){
    logger.info("--->" + "load data");
    return  new RedisCacheTest("test");
  }

  @Unremovable
  public static record RedisCacheTest(String name) implements Serializable {}
}


```
*result* cacheName is missing

![image](https://github.com/quarkusio/quarkus/assets/3381801/fa200dbe-0f7f-4339-af80-fc059b8117d1)

### Output of `uname -a` or `ver`

Linux fedora 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "20" 2023-03-21 OpenJDK Runtime Environment (Red_Hat-20.0.0.0.36-1.rolling.fc38) (build 20+36) OpenJDK 64-Bit Server VM (Red_Hat-20.0.0.0.36-1.rolling.fc38) (build 20+36, mixed mode, sharing)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2-rc-2

**Comment by cescoffier** [comment]
The cache name is the name of the cache (so, you need a matching redis cache (named) configuration.
When using the dev mode with the redis dev service, it uses a single redis for everything.

**Comment by grottah** [comment]
hi, I also think a prefix is not a replacement of all the caches names, if you have more than one project in the redis cache, will be nice to add a prefix like "project1". ObjectResult. Please this issue need to be addressed.

**Comment by cescoffier** [comment]
@grottah please re-open an issue explaining your use case.
