### ISSUE TITLE
User methods requiring a transaction in Hibernate ORM does not work for interfaces of Panache REST Data extension

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#35107]
### Describe the bug

This issue has been originally reported in Stack Trace: https://stackoverflow.com/questions/76790895/panacherepositoryresource-transaction-is-not-active

Having the following REST Data interface:

```java
@ResourceProperties(hal = true, paged = false, halCollectionName = "item-collections")
public interface CollectionsResource extends PanacheRepositoryResource<CollectionsRepository, Collection, String> {
    @Transactional
    @POST
    @Path("/name/{name}")
    default Collection addByName(@PathParam("name") String name) {
        Collection collection = new Collection();
        collection.id = name;
        collection.name = name;
        collection.persist();
        return collection;
    }
}
```

It fails with:
```
2023-07-31 08:12:56,638 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /collections/name/mycollection failed, error id: 07a3c279-b23b-497c-b17b-69fc85e34489-1: org.jboss.resteasy.spi.UnhandledException: jakarta.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.
```

Note that internally the REST Data with Panache extension is auto-generating a resource XX_AutoGenerated that implements the above interface CollectionsResource.

### Expected behavior

The `@Transactional` annotation should work when using it on default methods and for auto-generated resources.

### Quarkus version or git rev

999-SNAPSHOT

### Additional information

Note that this issue is very similar to https://github.com/quarkusio/quarkus/issues/34432 but for Hibernate Reactive. We fixed this issue by adding the `@WithSessionOnDemand` annotation at the class level of the auto-generated resource. 

Unfortunately, we cannot do the same for Hibernate ORM since adding the `@Transactional` annotation at the class level would imply all the methods require a transaction.

**Comment by Sgitario** [comment]
Adding @mkouba @Sanne @DavideD 

> The @Transactional annotation should work when using it on default methods and for auto-generated resources.

I'm not sure if there is a technical limitation to support the above. If so, there is any way I can register an auto-generated resource, so the transaction interceptor gets registered? Or any other workaround?

**Comment by mkouba** [comment]
> Adding @mkouba @Sanne @DavideD
> 
> > The @transactional annotation should work when using it on default methods and for auto-generated resources.
> 
> I'm not sure if there is a technical limitation to support the above. If so, there is any way I can register an auto-generated resource, so the transaction interceptor gets registered? Or any other workaround?

`@Transactional` is a CDI interceptor binding and the spec is clear that these bindings are ignored when declared on an interface.

I'm pretty sure that we do not ignore interceptor bindings declared on MP Rest Client interfaces. However, I'm not sure what kind of workaround is used there. Most probably the binding annotation is copied to a generated implementation class.

CC @Ladicek @manovotn

**Comment by Sgitario** [comment]
> > Adding @mkouba @Sanne @DavideD
> > > The @transactional annotation should work when using it on default methods and for auto-generated resources.
> > 
> > 
> > I'm not sure if there is a technical limitation to support the above. If so, there is any way I can register an auto-generated resource, so the transaction interceptor gets registered? Or any other workaround?
> 
> `@Transactional` is a CDI interceptor binding and the spec is clear that these bindings are ignored when declared on an interface.
> 
> I'm pretty sure that we do not ignore interceptor bindings declared on MP Rest Client interfaces. However, I'm not sure what kind of workaround is used there. 

In MP Rest Client, the user method is being copied into the generated resource which is something I wanted to avoid here. Will revisit it, see options and most probably will have to do the same.
