### ISSUE TITLE
@PostLoad EntityListener is not triggered for LAZY loaded referenced entity

### ISSUE THREAD

**Issue by michael-voegeli-fnt** [quarkusio/quarkus#35111]
### Describe the bug

An EntityListener for _@PostLoad_ is not triggered in case that the entity itself is loaded as _FetchType.LAZY_ related entity of another entity.

### Expected behavior

The EntityListener should always been triggered when hibernate loads the entity.

### Actual behavior

The actual result is that the entity seems to be loaded (all attributes are correctly loaded from database) but the EntityListener was not called. 

I built an example based on the **hibernate-orm-quickstart** and added there an additional entity _Rating_ that has an transient attribute _value_ that is set by the PostLoad listener. In case when loading only the _Rating_ entities the transient _value_ attribute is set, in case when loading the _Fruit_ entities that have linked the _Rating_, then the _value_ attribute is null.

### How to Reproduce?

I modified the **hibernate-orm-quickstart**, attached in ZIP file:
[hibernate-orm-quickstart.zip](https://github.com/quarkusio/quarkus/files/12213355/hibernate-orm-quickstart.zip)

1. Run quarkus:dev
2. Check localhost:8080/ratings -> there will be one rating object having a string set for the value attribute
3. Check localhost:8080/fruits -> all the fruits are listed with the linked rating object, but rating attribute _value_ is null. In this case the EntityListener _RatingListener_ was not executed.

### Quarkus version or git rev

3.2.2.Final

**Comment by marko-bekhta** [comment]
Hey @michael-voegeli-fnt , thanks for reporting the issue. I've converted your reporducer and reported it upstream. Here's a ticket if you'd want to track it https://hibernate.atlassian.net/browse/HHH-17019

**Comment by yrodiere** [comment]
Thanks. I'll close this for now as this will have to be fixed upstream, and will reach Quarkus when we upgrade to a version with the fix.
