### ISSUE TITLE
Protobuf serialization produces invalid values in native mode when built with Oracle GraalVM

### ISSUE THREAD

**Issue by nscuro** [quarkusio/quarkus#35125]
### Describe the bug

When serializing Protobuf messages in a Quarkus applications built in native mode, the produced output is invalid.

The problem manifests itself mostly through the following exception, when attempting to deserialize such values in other applications:

```
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
```

Everything works fine when the producing application is not native.

Deserialization of values produced by non-native applications also works, from what I can tell so far. It appears like it is entirely a serialization issue.

### Expected behavior

Serializing Protobuf messages in native applications should yield valid output.

### Actual behavior

Serializing Protobuf messages in native applications yields invalid output.

### How to Reproduce?

The issue can be reproduced using the example code generated for the [gRPC extension](https://quarkus.io/guides/grpc-getting-started), with [slight modifications](https://github.com/quarkusio/quarkus/discussions/33599#discussioncomment-6000070) to make it work with `@QuarkusIntegrationTest`:

1. Clone https://github.com/nscuro/quarkus-native-protobuf
2. Build native image and execute integration test:
```shell
export GRAALVM_HOME="$(sdk home java 17.0.7-graal)"
mvn clean package failsafe:integration-test failsafe:verify -Pnative
```
3. Observe the test failing due to the exception mentioned above
4. Build JVM application and execute integration test:
```shell
mvn clean package failsafe:integration-test failsafe:verify -DskipITs=false
```
5. Observe the test succeeding

### Output of `uname -a` or `ver`

Darwin devastation 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### GraalVM version (if different from Java)

java version "17.0.7" 2023-04-18 LTS Java(TM) SE Runtime Environment Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12, mixed mode, sharing)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

### Additional information

I spent quite a bit of time debugging this a few weeks ago, but ultimately failed to find a solution. It does not appear to be related to missing reflection configuration. I remember observing that Protobuf messages produced by native applications were prefixed with multiple NULL bytes. Perhaps the way Protobuf calculates message sizes does not play well native mode, but I lack low-level Protobuf experience to debug it further.

We originally ran into the issue because we use Protobuf for Kafka messages, and integration tests for native images were failing, but ran fine in JVM mode.

**Comment by cescoffier** [comment]
it's because of `quarkus.http.test-port=0` that is ignored during the native tests. USe 8081 (the default value) and everything works).

**Comment by nscuro** [comment]
Interestingly, it seems to work fine when I build the app in a Mandrel container, and run the IT against the Docker image:

```
$ mvn quarkus:add-extension -Dextensions='container-image-docker'
$ mvn clean package failsafe:integration-test failsafe:verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
...
[INFO] Running io.github.nscuro.HelloGrpcServiceIT
Aug 01, 2023 9:45:58 AM io.quarkus.test.common.DefaultDockerContainerLauncher start
INFO: Executing "docker run --name quarkus-integration-test-YZPJC -i --rm -p 8081:8081 -p 8444:8444 --net=quarkus-integration-test-sSOVt --env QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL=INFO --env QUARKUS_HTTP_PORT=8081 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:8081 --env QUARKUS_CONTAINER_IMAGE_BUILD=true --env QUARKUS_NATIVE_CONTAINER_BUILD=true nscur0/quarkus-native-protobuf:1.0-SNAPSHOT"
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.241 s - in io.github.nscuro.HelloGrpcServiceIT
```

So potentially a difference between GraalVM and Mandrel?

I will try to replicate this on a x64 Linux box, there doesn't seem to be a Mandrel distribution for ARM macOS.

**Comment by nscuro** [comment]
@cescoffier Odd indeed. What distribution of GraalVM are you running?

On an Ubuntu Linux x64 box:

```
$ uname -a
Linux ctrl 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

With Oracle GraalVM `17.0.8`:

```shell
$ "$(sdk home java 17.0.8-graal)"/bin/java -version         
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14, mixed mode, sharing)

$ "$(sdk home java 17.0.8-graal)"/bin/native-image --version
native-image 17.0.8 2023-07-18
GraalVM Runtime Environment Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)
Substrate VM Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS, serial gc, compressed references)
```

With GraalVM CE `17.0.8`:

```shell
$ "$(sdk home java 17.0.8-graalce)"/bin/java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15, mixed mode, sharing)

$ "$(sdk home java 17.0.8-graalce)"/bin/native-image --version
native-image 17.0.8 2023-07-18
GraalVM Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15)
Substrate VM GraalVM CE 17.0.8+7.1 (build 17.0.8+7, serial gc)
```

With Mandrel `23.0.1.2.r17`:

```shell
$ "$(sdk home java 23.0.1.2.r17-mandrel)"/bin/java -version         
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

$ "$(sdk home java 23.0.1.2.r17-mandrel)"/bin/native-image --version
native-image 17.0.8 2023-07-18
OpenJDK Runtime Environment Mandrel-23.0.1.2-Final (build 17.0.8+7)
OpenJDK 64-Bit Server VM Mandrel-23.0.1.2-Final (build 17.0.8+7, mixed mode)
```

The native test fails with Oracle GraalVM but succeeds with GraalVM CE and Mandrel.

This coincides with the [`graalvm/setup-graalvm`](graalvm/setup-graalvm) Action defaulting to the new Oracle GraalVM distribution since that was released a few weeks ago. Turns out our pipelines are running with the Oracle distribution without us knowing.

**Comment by nscuro** [comment]
Can confirm that switching to GraalVM CE fixes our integration tests running on GitHub Actions.

**Comment by cescoffier** [comment]
I used
```
native-image 20.0.1 2023-04-18
GraalVM Runtime Environment GraalVM CE 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)
Substrate VM GraalVM CE 20.0.1+9.1 (build 20.0.1+9, serial gc)
```

It's not the first time using the "EE" edition break a few stuff.

Maybe the @galderz, @zakkak or @Karm would know.

**Comment by zakkak** [comment]
> Maybe the @galderz, @zakkak or @Karm would know.

I personally don't, but given that the main differences between CE and "EE" are performance/optimization related I suspect something is being optimized away while it shouldn't. 

@fniephaus this is probably worth looking at.

**Comment by fniephaus** [comment]
> This coincides with the [graalvm/setup-graalvm](https://github.com/quarkusio/quarkus/issues/graalvm/setup-graalvm) Action defaulting to the new Oracle GraalVM distribution since that was released a few weeks ago.

Apologies, this actually turned out to be a bug and is now fixed.

> @fniephaus this is probably worth looking at.

Will do, thanks for bringing this to our attention.

**Comment by cescoffier** [comment]
Thanks @fniephaus !
