### ISSUE TITLE
Rest client 307 redirect doesn't keep original request headers

### ISSUE THREAD

**Issue by jdussouillez** [quarkusio/quarkus#35126]
### Describe the bug

The bug is following issue https://github.com/quarkusio/quarkus/issues/34644

With Quarkus v3.2.1+, a POST request done on an endpoint responding HTTP 307 now sends a POST request on the new URL. The problem now is that the original request headers are lost and not sent to the new URL.

It works fine with curl and Postman. Unfortunately I couldn't find any documentation about headers after redirect in the RFCs.

### Expected behavior

When sending the new request after a redirect, the HTTP method and the headers must be kept from the original request (method is OK since https://github.com/quarkusio/quarkus/issues/34644 but headers are lost).

```
-> POST /token, headers=[H1, H2]
<- HTTP 307, Location=/token2
-> POST /token2, headers=[H1, H2]
```

### Actual behavior

The headers are not sent in the request after the redirect.

```
-> POST /token, headers=[H1, H2]
<- HTTP 307, Location=/token2
-> POST /token2, headers=[]
```

### How to Reproduce?

Reproducer: https://github.com/jdussouillez/quarkus-rest-client-post-redirect-post/tree/missing-headers

*Same as https://github.com/quarkusio/quarkus/issues/34644 but use `missing-headers` branch*.

The server requires "X-Api-Version" header or will fail with "Bad request". Using curl it works fine:

![curl](https://github.com/quarkusio/quarkus/assets/5428355/01ceab64-b09f-46ea-89f6-e665cf47baae)

Using Quarkus Rest client it fails with 400 because the "X-Api-Version" header wasn't sent in the second request.

![quarkus-rest-client](https://github.com/quarkusio/quarkus/assets/5428355/7b28c73a-7c10-4d50-9ec2-c72bc156c21b)

### Output of `java -version`

openjdk version "17.0.7"

### Quarkus version or git rev

3.2.2.Final

**Comment by geoand** [comment]
I wonder what the spec says about this... I don't recall ever hearing about header handling although it does sounds reasonable

**Comment by jdussouillez** [comment]
Yeah I looked in both RFCs mentioned [here](https://github.com/quarkusio/quarkus/issues/34644#issuecomment-1628984636) but nothing says if the headers must be sent again or not.

**Comment by cescoffier** [comment]
I don't think we can forward all headers blindly. Some may contain sensible content which should not be forwarded. So, it would require a list of the headers to not forward (or a more prescriptive approach where we list the headers to forward, but that could be annoying)

**Comment by jdussouillez** [comment]
> So, it would require a list of the headers to not forward (or a more prescriptive approach where we list the headers to forward, but that could be annoying)

@geoand imagined a [more flexible solution here](https://github.com/quarkusio/quarkus/issues/34644#issuecomment-1630685085) by using an `AdvancedRedirectHandler` to customize the request sent after the redirect, using the original request and redirect response informations. I guess headers could also be overridden with this solution.

Something like:
```java
// ...
RedirectRequest of(ResteasyReactiveClientRequestContext reqContext, Response redirectResponse) {
    return new RedirectResponse() {
        @Override
        public URI uri() {
            return null; // null means the default value (redirectResponse's "Location" header value)
        }

        @Override
        public String httpMethod() {
            return null; // null means the original HTTP method (reqContext.getMethod())
        }

        @Override
        public MultivaluedMap<String, Object> headers() {
            return null; // null means the request headers here (reqContext.getHeaders()) but you can remove/add stuff here
        }
    }
}
// ...
```

**Comment by geoand** [comment]
Right, that design would allow for such a use case.

**Comment by cescoffier** [comment]
I think it's a good approach. I'm fearing we start introducing dozens of parameters to capture everything, while a single programmatic approach would work.

**Comment by geoand** [comment]
That could certainly be an option, I would personally not prefer it since it is almost certainly not what we would do if we were designing the API from scratch.

**Comment by jdussouillez** [comment]
Any updates?

**Comment by geoand** [comment]
This slipped through the cracks unfortunately

**Comment by jdussouillez** [comment]
Bumping. It would be nice to have this (to remove manual HTTP requests and use REST client instead)

**Comment by geoand** [comment]
I'll try and check this soon

**Comment by geoand** [comment]
Can you try https://github.com/quarkusio/quarkus/pull/41485?

It introduces the new `AdvancedRedirectHandler` which you can be used as shown in the new `AdvancedRedirectTest`

**Comment by jdussouillez** [comment]
@geoand Thanks, the `AdvancedRedirectHandler` works fine!

*See my reproducer's ["quarkus-v3.13" branch](https://github.com/jdussouillez/quarkus-rest-client-post-redirect-post/blob/quarkus-v3.13/client/src/main/java/com/github/jdussouillez/client/TokenApiRedirectHandler.java)*

-----

But now I see another issue: the POST body is not sent to the redirect request. Note that it is also an issue with `RedirectHandler`'s `URI handle(Response response)` method.

Is there a way to do this using the new `AdvancedRedirectHandler`? I guess it's not that easy because Vert.x `RequestOptions` does not handle body, only method, headers, URL, etc.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
> The method and the body of the original request are reused to perform the redirected request.
> [...]
> The only difference between 307 and [302](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) is that 307 guarantees that the method and the body will not be changed when the redirected request is made.

**Comment by geoand** [comment]
Is Vert'x is not handling doing this, there is not much we can do in Quarkus - see that `AdvancedRedirectHandler` is just used to setup a Vert.x object which is set to `io.vertx.core.http.HttpClientBuilder#withRedirectHandler`

**Comment by jdussouillez** [comment]
I created https://github.com/quarkusio/quarkus/issues/41751 as this issue is closed and the new feature works fine.
