### ISSUE TITLE
When using smallrye reactive messaging rabbitmq with resteasy reactive, the application doesn't listen port 8080

### ISSUE THREAD

**Issue by stephane-drogou** [quarkusio/quarkus#35133]
### Describe the bug

I have the following pom .xml :
```
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-rabbitmq</artifactId>
    </dependency>
```

Then I declare a class which managed the rabbitmq connection and a class which expose an endpoint.
The rabbitmq connection works fine but the endpoint is not accessible. 
The command curl -w "\n" http://localhost:8080 response  "curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server"
At started I didn't see the line "Listening on: http://localhost:8080"

### Expected behavior

The application manages the rabbitmq connection as configured and the application listen at port 8080

### Actual behavior

The application manages the rabbitmq connection as configured but the application doesn't listen at port 8080

### How to Reproduce?

To reproduce the behaviour you just have to :
 1 - Go in code.quarkus.com
 2 - Configure an application with SmallRye Reactive Messaging - RabbitMQ Connector and RESTEasy Reactive Jackson
 3 - Declare a rabbitmq connection and a endpoint
 4 - Start the application and see that it doesn't listen port 8080

### Output of `uname -a` or `ver`

Linux vmDev2023 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /opt/maven Java version: 17.0.7, vendor: Eclipse Adoptium, runtime: /opt/mandrel-java17-23.0.0.0-Final Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "6.1.0-10-amd64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Please attach a sample application that behaves as you describe as I was not to reproduce it

**Comment by stephane-drogou** [comment]
I put the code in this repository :[https://github.com/stephane-drogou/rabbitmq-client.git](url)

**Comment by cescoffier** [comment]
The issue is the `public Message<String> send() throws InterruptedException {` method which monopolizes the caller thread forever and does not let anything else run. It blocks the event loop used by Quarkus to run everything else. 

Work around the issue using:  `@Blocking` on the method.

**Comment by stephane-drogou** [comment]
Oh My God !
Thank you for the help and sorry for the inconvenience.

**Comment by geoand** [comment]
@cescoffier is there any way we could detect this?

**Comment by cescoffier** [comment]
@geoand not really. The Vert.x thread checker would report something if it does not make progress, but the code is done in a way where it kind of makes progress.
We will have the same issue with virtual threads: do not monopolize.

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by cescoffier** [comment]
As I mentioned to you, with a properly placed JFR event, we may be able to detect such an invalid code, but it's not going to be done tomorrow (because I will be on PTO anyway). This will require a bit of thinking and placing the events carefully not to penalize the performances.

**Comment by geoand** [comment]
I can help with that (when I'm back from PTO as well) if you like
