### ISSUE TITLE
Blocked thread checker does not monitor the executor-thread-x threads

### ISSUE THREAD

**Issue by bh-tt** [quarkusio/quarkus#35166]
### Describe the bug

The vertx blocked thread checker, designed to log warnings if a thread is blocked for too long, does not monitor threads in the default executor pool (with name `executor-thread-xxx`). However, a lot of code is executed on these threads (e.g. REST endpoints that do not return a reactive result, tasks given to the default ManagedExecutor, scheduled tasks in prod mode).

### Expected behavior

I'd expect all threads that return true for `io.vertx.mutiny.core.Context.IsOnVertxThread()` to be monitored by the blocked thread checker (with different max times for event loop and worker threads, of course).

### Actual behavior

Threads in the default executor pool are not monitored by the BlockedThreadChecker.

### How to Reproduce?

1. Run the test in the attached project
2. observe the event loop thread warnings
3. observe as no warnings are logged for the executor-thread-0 despite it being blocked for more than the 1 second configured max-worker-time

[reproducer.zip](https://github.com/quarkusio/quarkus/files/12239947/reproducer.zip)

### Output of `uname -a` or `ver`

Linux devrd0 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.20" 2023-07-18 LTS OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS) OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.0.2

### Additional information

This might end up being a Vertx issue, but my guess would be a misconfiguration in Quarkus.

**Comment by geoand** [comment]
This is expected as a worker thread pool can be used for all sorts of tasks, including ones that can be very long running

**Comment by bh-tt** [comment]
The base executor smallrye uses is from the io.quarkus.deployment.builditem.ExecutorBuildItem. I'm guessing this would require checking if vertx is present, and if so using an executor from vertx (configured with the given max time) instead of the default builtin executor. 

Alternatively we could implement similar code to the vertx thread checker but I'd prefer reusing (well-tested) vertx code.

**Comment by cescoffier** [comment]
We need to be careful. 

`max-worker-execute-time`  is used when you use executeBlocking, because you have a pending continuation. 
For regular worker tasks (computational), it's hard to come up with a good default value.
