### ISSUE TITLE
Should SafeVertxContextInterceptor define a Priority?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#35173]
When running the tests in `integration-tests/grpc-mutual-auth`, I get the following log line:

> 2023-08-02 18:05:06,718 INFO  [io.qua.arc.pro.Interceptors] (build-15) The interceptor io.quarkus.vertx.core.runtime.context.SafeVertxContextInterceptor does not declare any @Priority. It will be assigned a default priority value of 0.

Could we get rid of it?

@mkouba in the absence of @cescoffier, I'm pinging you.

**Comment by mkouba** [comment]
Ah, yes, we should add the `@Priotity(0)`. I will send a pull request shortly.

**Comment by gsmet** [comment]
It absolutely should not :)
