### ISSUE TITLE
Relax HTTPS option

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#3518]
**Description**

 I was thinking that for testing purposes it will be great to have a configuration flag that configures MP Rest client to accept any request to any https site by disabling trust manager. I think that for testing purposes this might be really helpful.

**Comment by geoand** [comment]
@michalszynkiewicz I think this would be useful for the reactive rest client

**Comment by michalszynkiewicz** [comment]
how does it differ from using `quarkus.tls.trust-all`?

**Comment by geoand** [comment]
Closing as one can easily use `quarkus.tls.trust-all`
