### ISSUE TITLE
Support multiple Hibernate dialects and pick the right one at runtime

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#352]
## general problem

Avoid DCE of databases we want to support. Maybe with a list of supported extensions (included in the POM).

For a given DB, select all dialect classes as these are small piece of code to avoid DCE and simplify configuration if needed by the suer at runtime. Can even be detected by the DB metadata info at connection time.

## related to driver driven dialect selection

I think we could use the driver to "narrow down" the set of possible dialects; we'll need to actually connect to the RDBMS to then run the usual auto-detection and make the final choice.

Shouldn't be too bad on code size, as most of these Dialects are typically entangled into an inheritance tree, so pulling in one would often pull in the whole family anyway.
   @emmanuelbernard
emmanuelbernard 4 days ago
Interesting, how would you implement that. With some code that references all these dialects? We don’t have a facility in the hibernate extension right now.
We would need it for the multi dialect anyways.
I’ll likely open a separate issue for this.
   @gsmet
gsmet 4 days ago
To avoid duplicating the effort, we might want to push some lightweight code into ORM to do that.

I know I plan to write a lightweight scanner for HV to be used by Shamrock. We will probably need to do some similar things in ORM and expose some of ORM features in a much more decoupled way.
   @emmanuelbernard
emmanuelbernard 4 hours ago
@gsmet how can you move this dialect selection code in ORM proper? It is a decision by the extension and it looks like it could also be a trick of org.hibernate.protean:hibernate-orm-protean Rememebr it's about DCEing the code or not.

**Comment by emmanuelbernard** [comment]
@Sanne should we close this as won't fix? At least not in this form?

**Comment by Sanne** [comment]
I was actually in favour of the idea of allowing a sub-set of dialects to be included; as long as:
 - the user makes an explicit list
 - people understand that the binary size will be quite larger

Also, we'll need something like this either way to be handled as we're currently lacking precise metadata from the DB: we normaly get this at connection time, now we're going with the defaults but that's not always ok.

So we'll need to explore such things either way.

**Comment by emmanuelbernard** [comment]
Ok so that means that we would prebuild metadata for each dialect and discard the useless ones at runtime. Looks like quite some work on the Hibernate extension side but would help the layered products.

**Comment by Sanne** [comment]
Right. Also, in ORM6 some changes in how Dialects are structured will help to allow some minor adjustements while not needing to fully switch D implementation.

**Comment by Sanne** [comment]
Is this still going to be needed?

**Comment by maxandersen** [comment]
didnt we end up being able to support multiple dialects with mulitple datasources? so we can mark this as done or?

**Comment by Sanne** [comment]
yes let's close this - like I asked 6 months ago :)
