### ISSUE TITLE
Make Quartz Extension configurable for clustered scheduler engine

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#3520]
**Description**
Quartz supports clustered JobStores that use JDBC and locks to synchronize between nodes:

[Configure Clustering with JDBC-JobStore](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJDBCJobStoreClustering.html)

The current Quartz extension has the RAMJobStore hardwired so this cannot be used.

**Implementation ideas**
As discussed here:

https://groups.google.com/forum/#!searchin/quarkus-dev/quartz%7Csort:date/quarkus-dev/XarQoQ8BLp4/kARhAbM9BAAJ

the current extension can consider using also the JDBCJobStore, or another extension can be written for that.

**Use case**
Our Quarkus application now uses @Scheduled to synch from external data. Having this running on multiple node can be an issue.

**Comment by rafaelszp** [comment]
I support this enhancement. Our company will move projects from old wildfly(legacy, swarm and thorntail) to quarkus soon, but the absence of this feature will cause some delays or we wont be able to migrate to this amazing framework.

**Comment by machi1990** [comment]
I can give this a go over the weekend.
