### ISSUE TITLE
Add `Flow.Publisher` support in Reactive Messaging

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#35219]
### Describe the bug

I tried to use `Flow.Publisher` instead of reactivestreams `Publisher` to bridge a outgoing channel to a SSE endpoint, 

```java

    @Inject
    @Channel("data-stream")
    Flow.Publisher<Message> stream;

    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.APPLICATION_JSON)
    public Flow.Publisher<Message> stream() {
        return stream;
    }
```

### Expected behavior

It should work as using reactiveStreams `Publisher`.

### Actual behavior

But it does not work, and throw exception like.

```bash
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.io.ByteArrayInputStream and no properties disco
vered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.quarkus.deployment.dev.testing.TestRunResults["result
s"]->java.util.Collections$UnmodifiableMap["com.example.MessageResourceTest"]->io.quarkus.deployment.dev.testing.TestClassResult["failing"]->java.util.ArrayList[0]->io.quarkus.deployme
nt.dev.testing.TestResult["problems"]->java.util.Collections$UnmodifiableRandomAccessList[0]->org.opentest4j.AssertionFailedError["suppressed"]->jakarta.ws.rs.InternalServerErrorExcept
ion[1]->jakarta.ws.rs.InternalServerErrorException["response"]->org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine$3["entity"])
        at io.quarkus.devui.deployment.menu.ContinuousTestingProcessor.lambda$registerGetResultsMethod$5(ContinuousTestingProcessor.java:198)
        at io.quarkus.dev.console.DevConsoleManager.invoke(DevConsoleManager.java:135)
        at io.quarkus.devui.runtime.continuoustesting.ContinuousTestingJsonRPCService.invokeAction(ContinuousTestingJsonRPCService.java:93)
        ... 9 more

```

### How to Reproduce?

1. Checkout https://github.com/hantsy/quarkus-sandbox/tree/master/amqp
2. run the application.

### Output of `uname -a` or `ver`

Windows 10 Pro

### Output of `java -version`

17

### GraalVM version (if different from Java)

Not used

### Quarkus version or git rev

3.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

### Additional information

Quarkus 3.0 used SmallRye Mutiny as default reactive stream proivder, JDK 9 Flow/Mutiny APIs should have a higher priority to get support in all modules.

**Comment by ozangunalp** [comment]
You should have the payload type in the generic for the return type like `Message<Payload>`.

I think we should check for that and fail at startup. Would you mind changing the subject of this issue?

**Comment by hantsy** [comment]
The `Message` here is the custom payload class in my example project.

**Comment by ozangunalp** [comment]
I am not sure of the actual serialization issue you are having but Flow APIs are supported by reactive messaging and passing it to an SSE endpoint with resteasy-reactive should just work, if you don't have an issue with the serialization of your bean. 

If nothing has changed since, you can get it working with resteasy classic but you'd need an SseEventSink.

Hope this helps, I am closing this as invalid.

**Comment by hantsy** [comment]
> I am not sure of the actual serialization issue you are having but Flow APIs are supported by reactive messaging and passing it to an SSE endpoint with resteasy-reactive should just work, if you don't have an issue with the serialization of your bean.
> 

The problem is using reactive streams `Publisher`, it is working well. And replace it with `Flow.Publisher` and I encountered this issue.

I have attached the example project to reproduce this issue. Can you tell where is wrong?

**Comment by hantsy** [comment]
[geoand](https://github.com/quarkusio/quarkus/commits?author=geoand)

**Comment by ozangunalp** [comment]
The problem you are having is the same as #30935. Resteasy Classic doesn't support Flow APIs.
