### ISSUE TITLE
Test with @QuarkusTest annotation leads to unexplainable error / behavior in a multi-module Gradle project

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#35227]
### Describe the bug

I'm trying to write test for my application, but I can't even make an empty `@Test` method working when using `@QuarkusTest`

This is my test. 
It contains two test methods that do nothing at all, as the code is commented out.

```
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

/**
 */
@QuarkusTest
class FileServiceTest {

    //@InjectSpy
    //FileService fileService;

    @Test
    void listUserFiles() {
/*
        if (false) {
            var authUser = AuthUser.of(1L);
            fileService.listUserFiles(authUser, null)
                    .log()
                    .invoke(i -> Assertions.assertEquals(0, i.size()))
                    .subscribe().withSubscriber(UniAssertSubscriber.create())
                    .assertCompleted();
        }
*/
    }

    @Test
    void downloadByAbsolutePath() {
    }
}

```

**It fails with `2 tests completed, 1 failed, 1 skipped`** - this happens even after a Gradle clean, so something might be off here

```
> Task :components:file:test

FileServiceTest STANDARD_ERROR
    Aug 06, 2023 2:33:30 PM io.quarkus.runtime.logging.LoggingSetupRecorder initializeLogging
    WARN: Root log level ALL set below minimum logging level DEBUG, promoting it to DEBUG. Set the build time configuration property 'quarkus.log.min-level' to 'ALL' to avoid this warning

FileServiceTest > listUserFiles() FAILED
    java.lang.RuntimeException at QuarkusTestExtension.java:640
        Caused by: java.lang.RuntimeException at AugmentActionImpl.java:336
            Caused by: io.quarkus.builder.BuildException at Execution.java:123
                Caused by: jakarta.enterprise.inject.spi.DeploymentException at BeanDeployment.java:1443

2 tests completed, 1 failed, 1 skipped

> Task :components:file:test FAILED

FAILURE: Build failed with an exception.
```

### Output of `java -version`

Java 20.0.2

### Quarkus version or git rev

3.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3-RC2

### Additional information

It's a Gradle multi-module project and I'm running the test with CLI (because of an IntelliJ bug) with

> ./gradlew :components:file:test --tests "com.myproject.file.provider.FileServiceTest"

Using quarkusDev, the application starts normally.

**Could anyone give me a hint what might be the cause of the test error?**

**Comment by geoand** [comment]
Any chance you can upload a sample project that exhibits this behavior?

**Comment by mklueh** [comment]
@geoand is there any chance to get more detailed logs in some way first and print the full stacktrace to at least see what bean might be affected?

**Comment by geoand** [comment]
Doesn't Gradle's `--stacktrace` give you any information?

**Comment by mklueh** [comment]
@geoand it gives me Gradle exceptions of the executor but not the actual exceptions. But I've looked into the generated report test/index.html and indeed there are more detailed exceptions with the missing bean.

I'll close the issue, thank you!

**Comment by geoand** [comment]
👍🏼
