### ISSUE TITLE
gRPC reflection service is gone when dev server hot reloads

### ISSUE THREAD

**Issue by azurvii** [quarkusio/quarkus#35229]
### Describe the bug

The gRPC reflection service seems to be removed when the dev server is hot reloading. Stopping `gradle quarkusDev` and re-running would get the reflection service back.

### How to Reproduce?

0. Go to https://code.quarkus.io, tick `grpc`, download the generated code.
1. `unzip` && `cd` && `gradle quarkusDev`
2. From another terminal:
```
$ ./grpcurl -plaintext localhost:9000 list
grpc.health.v1.Health
hello.HelloGrpc
```
4. `echo >> src/main/java/org/acme/HelloGrpcService.java` to trigger a dev server hot reload.
5. Now:
```
./grpcurl -plaintext localhost:9000 list
Failed to list services: server does not support the reflection API
```

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment (build 17.0.8+7-Debian-1) OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2.1

**Comment by alesj** [comment]
@azurvii what about your services, do they "survive" hot-reload?

**Comment by azurvii** [comment]
For the sake of completeness, since I do not know if the dev-v1 UI has used any magic, since it uses WebSockets to communicate, I wrote a little client for one of the services. The result stays the same -- the application service is working fine before and after dev server hot reload. The reflection service works only before the reload, and fails after.

**Comment by cescoffier** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/35371.
