### ISSUE TITLE
The ability to set the json format only for a specific file handler

### ISSUE THREAD

**Issue by maciekg89** [quarkusio/quarkus#35235]
### Description

Property quarkus.log.file.json is "global" - it is used by all file handlers.

But I would like to have e.g. default handler with json format, and another handler with my specific format. As far as I know, it's currently impossible.

I try such configuration:

```properties
logs.directory=../logs
quarkus.log.file.level=INFO 

quarkus.log.file.enable=true
**quarkus.log.file.json**=true
quarkus.log.file.path=${logs.directory}/json-my-service.log

quarkus.log.handler.file.MY_HANDLER.enable=true
**quarkus.log.handler.file.MY_HANDLER.json=false**   // it is not valid 
quarkus.log.handler.file.MY_HANDLER.format=[%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}] [%-5p] [%c] [%t] [%X{trace-id}] [%X{transaction-id}] [%s] [%e]%n
quarkus.log.handler.file.MY_HANDLER.path=${logs.directory}/my-service.log
quarkus.log.handlers=MY_HANDLER
```

**Comment by geoand** [comment]
Thanks for the report.

There is no such property: `quarkus.log.file.json`

Are you thinking of another property instead?

**Comment by geoand** [comment]
Closing for lack of feedback
