### ISSUE TITLE
Lack of Support for PEM Certificate Specification in Quarkus for MongoDB TLS Connection

### ISSUE THREAD

**Issue by TartanLeGrand** [quarkusio/quarkus#35233]
### Describe the bug

When trying to connect to a MongoDB instance using PEM formatted certificates, Quarkus doesn't provide a straightforward way to specify the CA file and the certificate. While the mongosh tool supports PEM certificates using --tlsCAFile and --tlsCertificateKeyFile options, Quarkus encounters an error when trying to use the same certificates via the java.net.trusted* properties. This is because it expects a JKS formatted TrustStore.

### Expected behavior

Quarkus should allow users to specify the paths for a CA file and a certificate in PEM format for TLS connection to MongoDB. This would make it compatible with the options provided by tools like mongosh.

### Actual behavior

When trying to use PEM certificates with Quarkus, an error occurs due to its expectation of a JKS TrustStore.

### How to Reproduce?

Set up a MongoDB instance with TLS enabled.
Use mongosh to successfully connect using the PEM certificates with the --tlsCAFile and --tlsCertificateKeyFile options.
Attempt to connect to the same MongoDB instance using Quarkus, specifying the PEM certificates.
Observe the error indicating an expectation of a JKS format.

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.3

**Comment by loicmathieu** [comment]
The MongoDB Java driver didn't offer such functionality, see https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/tls/

You will soon be able to customize the creation of the MongoDB driver, see https://github.com/quarkusio/quarkus/pull/36503, it will allow you to set your certificate in any way you need.

**Comment by gsmet** [comment]
Closing as per @loicmathieu 's answer.
