### ISSUE TITLE
Add `fail-on-intercepted-abstract-method`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#35237]
### Description

While migrating from Quarkus 2 to 3 we were lucky that we have test coverage of an abstract MapStruct mapping method with a interceptor binding (a custom one called `@CatchAll`).
This test showed us that Quarkus 3 ignores such bindings which seems to be in line with the spec (i.e. `@Inherited` has no effect at method level).

There is already [`fail-on-intercepted-private-method`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.fail-on-intercepted-private-method), so it would be nice to have something for abstract methods - unless I'm missing something and there are valid/working cases?!

**Comment by manovotn** [comment]
> There is already [fail-on-intercepted-private-method](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.fail-on-intercepted-private-method), so it would be nice to have something for abstract methods - unless I'm missing something and there are valid/working cases?!

You can have that method implemented in the abstract class in which case it should be intercepted unless overriden in its sublasses.
However, for purely abstract method, no use case comes to mind.

**Comment by manovotn** [comment]
While we can detect this, I am not sure it's worth it - the interceptor spec doesn't derail from standard java annotation inheritance rules in this regard so we'd essentially be detecting standard behavior, WDYT @mkouba?

**Comment by mkouba** [comment]
> This test showed us that Quarkus 3 ignores such bindings which seems to be in line with the spec (i.e. @Inherited has no effect at method level).

@famod Hm, do I understand it correctly that Quarkus 2 did not ignore this binding? I would be quite surprised if it didn't.

> While we can detect this, I am not sure it's worth it - the interceptor spec doesn't derail from standard java annotation inheritance rules in this regard so we'd essentially be detecting standard behavior, WDYT @mkouba?

I'm not sure either. The CDI spec is pretty clear that the binding should not be inherited (because an abstract method must be always overriden). However, it's not forbidden. Also we don't fail/log a warning if a binding is declared on an interface abstract method.

**Comment by famod** [comment]
@mkouba
> @famod Hm, do I understand it correctly that Quarkus 2 did not ignore this binding? I would be quite surprised if it didn't.

Correct, Quarkus 2 did not ignore this binding (acording to our QuarkusTest).

**Comment by manovotn** [comment]
I know Ladislav did a lot of corrections WRT inheritance of interceptors bindings (as part of the work to pass TCKs) so I am not as surprised we had some weird behaviors there. Regardless, it was a bug, not a feature so I am still -1 on adding any such check.

> However, it's not forbidden. Also we don't fail/log a warning if a binding is declared on an interface abstract method.

Right, and I suppose you could find more cases that follow standard behavior of java annotations where we don't check for potential misuse.

**Comment by famod** [comment]
To me it's about developer joy. It's just to easy to miss such things.

**Comment by famod** [comment]
@mkouba 
> > Correct, Quarkus 2 did not ignore this binding (acording to our QuarkusTest).
> 
> Just out of curiosity, could you share the source of the test?

Not directly, sorry - closed source. I'll see if I can extract a reproducer.

**Comment by mkouba** [comment]
> @mkouba
> 
> > > Correct, Quarkus 2 did not ignore this binding (acording to our QuarkusTest).
> > 
> > 
> > Just out of curiosity, could you share the source of the test?
> 
> Not directly, sorry - closed source. I'll see if I can extract a reproducer.

It's not necessary. I was just curious.

**Comment by mkouba** [comment]
> To me it's about developer joy. It's just to easy to miss such things.

Like I mentioned above it would be quite inconsistent if we don't do it for a binding declared on an interface abstract method. And we can't do that because there are supported use cases (e.g. MP Rest Client with MP Fault Tolerance annotations).

**Comment by famod** [comment]
I'm not familiar with MP Fault Tolerance annotations, but sure - if those are interceptor bindings then it probably goes way to far to make ArC aware of such subtleties.
Feel free to close this issue. We now have an ArchUnit test that protects us from such oversights.

**Comment by gastaldi** [comment]
Let's close it for now and revisit if necessary
