### ISSUE TITLE
Narayana automatic recovery of JDBC XA resources only works after datasources was initialized manually

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#35238]
### Describe the bug

If I want periodic recovery module to recover my failed transaction stored in JDBC object store, I need first to have datasources initialized (e.g. when I sent request or with startevent I use datasources).

### Expected behavior

When app starts, failed transactions recover.

### Actual behavior

Exception and no recovery:

```
2023-08-06 23:56:26,715 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord < resource:null, txid:< formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:17, subordinatenodename=null, eis_name=0 >, heuristic: TwoPhaseOutcome.FINISH_OK com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord@55ea0fec >
2023-08-06 23:56:26,719 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016038: No XAResource to recover < formatId=131077, gtrid_length=46, bqual_length=36, tx_uid=0:ffff0a0000b9:af1b:64d01657:11, node_name=quarkus-quickstart, branch_uid=0:ffff0a0000b9:af1b:64d01657:13, subordinatenodename=null, eis_name=0 >
```

Recovery doesn't work till I use datasources myself. @zhfeng explained to me here https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667031126 that there was changes in Agroal regarding ds initialization https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java#L28-L30.

I've tested Zheng suggestion with following code that did a trick (I do not propose use such thing! it's just for context):
https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667606419

### How to Reproduce?

Reproducer:

follow readme added here https://github.com/quarkusio/quarkus-quickstarts/pull/1311. There are steps that you need to follow, you will see that if you don't do `curl -v localhost:8080/transaction-logs/annotation-way`, transaction is never recovered and an exception is repeatedly logged.

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

Related to https://github.com/quarkusio/quarkus/pull/34545 ? Didn't check (on PTO).

**Comment by michalvavrik** [comment]
@gsmet this looks like important for Ghost, would it be possible to get it to 2.3.4.Final, please?

**Comment by michalvavrik** [comment]
btw maybe even more important fact is that application don't even start when I test quickstart with 3.2.x.Final due to exception also explain here https://github.com/quarkusio/quarkus-quickstarts/pull/1311#issuecomment-1667606419

**Comment by gsmet** [comment]
Do we actually have tests for this feature in the tree? Because it looks very broken.

As for knowing if we can get a fix in 3.2.4, we don't have a fix right now so I don't know.

**Comment by michalvavrik** [comment]
> Do we actually have tests for this feature in the tree? Because it looks very broken.

The test that is there doesn't actually test the recovery feature.

> As for knowing if we can get a fix in 3.2.4, we don't have a fix right now so I don't know.

Sorry about that, I just wanted to draw you attention to this as I don't know where is 3.2.4 happening and wanted you to know about this. 

Anyway, it feels like fixable for Narayana recorder just needs to be run when datasources can be initialized and make sure it initializes them if recovery is enabled. I presume Narayana folk will have a look @mmusgrov @zhfeng , but in unlikely case everyone is busy, let me know, I can look.

**Comment by gsmet** [comment]
Given the time frame, let's focus on getting it to work for 3.2 and let's keep https://github.com/quarkusio/quarkus/commit/3f9de0c8af37a6bf9a869af117f95b5ae206dd28 out of the loop. We will have to discuss it later.

As for 3.2, there's at least one big issue: using `addLastShutdownTask` to register the shutdown of the recovery service will make it stop AFTER ArC has been shut down. Thus there's no way for you to actually get the datasource.

I'll have a look at this this afternoon but still unsure if I will be able to get to the bottom of it.

**Comment by gsmet** [comment]
Yeah I think we need to take a step back and understand exactly what are the requirements/dependencies of the various services and then get it fixed. It's not an easy task though so let's tackle this when we're out of August.

**Comment by geoand** [comment]
I absolutely agree

**Comment by michalvavrik** [comment]
Added comments to the linked PR for 3.2, thanks.

**Comment by zhfeng** [comment]
Thanks @gsmet for taking a look at this issue!

We don't have any test for transaction crash recovery feature automatically right now and can only run it manually because it needs to crash the application at first and then restart it to watch the recovery happening. I'm not sure if it is possible to work with the quarkus test framework? e.g. restart a application after crashing?
