### ISSUE TITLE
JPA Security: allow pointing to a named persistence unit

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#35231]
### Description

Currently, `JpaIdentityProvider` is hardcoded to retrieve the default persistence unit:

https://github.com/quarkusio/quarkus/blob/03df5d57d3989da2f895d113f4bffc53c96f34ee/extensions/security-jpa/runtime/src/main/java/io/quarkus/security/jpa/runtime/JpaIdentityProvider.java#L22-L27

This means security-related data must live in the default PU and cannot live in a named PU, which seems like a likely scenario.

It would be nice to allow configuring quarkus-security-jpa to use a non-default persistence unit.

See also https://stackoverflow.com/questions/76845856/unsatisfied-dependency-with-panache-and-multiple-datasources

### Implementation ideas

AFAICS we just need some more config in the quarkus-security-jpa extension and corresponding build steps to have `JpaIdentityProvider` retrieve the `EntityManagerFactory` by name if necessary.

**Comment by yrodiere** [comment]
Note that #16700 is related, but different, as #16700 is about tenants within a given PU.

**Comment by sberyozkin** [comment]
Also CC @FroMage

**Comment by FroMage** [comment]
Yeah, probably a nice idea.

**Comment by michalvavrik** [comment]
I've tried to figure how to do this for Hibernate Reactive (JPA Security Reactive), but I don't believe it is possible to use named PU with HR. At least I didn't find any test / any example / any docs and in tests I wrote Mutiny.SessionFactory was not produced for named PU.

https://github.com/quarkusio/quarkus/pull/36728 should take care of this for Security JPA.

**Comment by yrodiere** [comment]
> I don't believe it is possible to use named PU with HR

Indeed it is not: https://quarkus.io/guides/hibernate-reactive#hr-limitations , 

> https://github.com/quarkusio/quarkus/pull/36728 should take care of this for Security JPA.

Thanks!

**Comment by michalvavrik** [comment]
> > I don't believe it is possible to use named PU with HR
> 
> Indeed it is not: https://quarkus.io/guides/hibernate-reactive#hr-limitations ,

Completely missed that line, thank you.
