### ISSUE TITLE
Native mode using Quarkus supplied GraalVM image on M1 Mac gives `exec format error`

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#35248]
### Describe the bug

When building my Quarkus command line application in native mode using the built in GraalVM docker image, the build process is successful, however the resulting executable is not usable.

The Docker image being pulled is:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking status of builder image 'quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17'
jdk-17: Pulling from quarkus/ubi-quarkus-mandrel-builder-image
Digest: sha256:bfb896cd4e6fff84c77bceeb722dd3e07d23f9e18709b01e09af0d44e9feb0f6
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 17.0.8 2023-07-18
OpenJDK Runtime Environment Mandrel-23.0.1.2-Final (build 17.0.8+7)
OpenJDK 64-Bit Server VM Mandrel-23.0.1.2-Final (build 17.0.8+7, mixed mode)
```

I get the error: `zsh: exec format error:` when trying to run the binary created.

When doing a `file` command on the executable I get:
` ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=69b7429a9c64d026f515c8b1fe25051e128ebc2f, not stripped
`

When doing a `file` command on the executable generated by the locally installed GraalVM I get:
`Mach-O 64-bit executable arm64`

### Expected behavior

Binary file should be executable on my M1 Mac like it is when using a standard locally installed GraalVM JDK.

### How to Reproduce?

Try to build a native mode application on a M1 Mac using the following command and see if you get the `exec format` error.

`mvn clean package -Pnative -Dquarkus.native.container-build=true`

### Quarkus version or git rev

3.2.3.Final

**Comment by zakkak** [comment]
Hi @tmulle, as mentioned in https://quarkus.io/guides/building-native-image#container-runtime, the builder images are solely for creating Linux executables. For creating MacOS and Windows executables one needs to use a local GraalVM installation.

**Comment by tmulle** [comment]
opps! Sorry you're right. I missed that fine point in the docs.

Do you know of a premade docker image that I can use on MacOS M1 that also has UPX installed for native binary compression?

Or instructions on installing UPX in a docker image so I can create my own GraalVM with UPX?

Thanks!

**Comment by Karm** [comment]
Closing. Linux builder image creates Linux ELF64 executables.

**Comment by galderz** [comment]
> Do you know of a premade docker image that I can use on MacOS M1 that also has UPX installed for native binary compression?

I don't.

> Or instructions on installing UPX in a docker image so I can create my own GraalVM with UPX?

I don't have those either, but I guess it's the usual thing of extending an existing base image, downloading UPX for the right architecture, adding it to the path...etc.
