### ISSUE TITLE
CDI Reference 1.1 has incomplete information for gradle

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#35258]
### Describe the bug

In the section [1.1. How to Generate a Jandex Index](https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index) the gradle information displays:
```kotlin
plugins {
    id("org.kordamp.gradle.jandex") version '{jandex-gradle-plugin-version}'
}
```

### Expected behavior

instead of `'{jandex-gradle-plugin-version}'` there should be a real version

### Actual behavior

you get `'{jandex-gradle-plugin-version}'` as version

**Comment by geoand** [comment]
cc @gsmet

**Comment by gsmet** [comment]
Yeah, I don't know. There's little chance we will be able to follow the releases of this project so a placeholder is probably the best we can do to not recommend an outdated version.

But if others feel strongly otherwise, we can change it.

**Comment by bulldog98** [comment]
Maybe explain that that is a dummy version and do a link to the plugin.gradle.org site, so users can get the version there?

**Comment by gastaldi** [comment]
I think it's okay to use 1.1.0 (released December 2022 - https://plugins.gradle.org/plugin/org.kordamp.gradle.jandex), it's not that plugin will change that much TBH. 

But maybe it's a good idea to add a link to the https://plugins.gradle.org/plugin/org.kordamp.gradle.jandex website

**Comment by gastaldi** [comment]
Actually, we already define it in here: https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L39, not sure why the property is not being picked up, investigating

**Comment by gastaldi** [comment]
Here is the fix: https://github.com/quarkusio/quarkus/pull/35300
