### ISSUE TITLE
kubernetes env var Nested environment variable not supported

### ISSUE THREAD

**Issue by matter-it-does** [quarkusio/quarkus#35260]
### Describe the bug

support  nested quarkus environment variables. 

At build time, if the env var is present like
```
QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_REST_CLIENT__EXTERNAL_SERVICE__URL__=http://example.com
```
then at runtime in the pod, the env var should be present like 
```
QUARKUS_REST_CLIENT__EXTERNAL_SERVICE__URL=http://example.com
```
this way config map etc can be sidestepped to set url for the rest client "external-service"

### Output of `uname -a` or `ver`

macos

### Output of `java -version`

17

### Quarkus version or git rev

3.1.3.Final

**Comment by Sgitario** [comment]
@radcortez can you confirm if this is supported or not? I guess what @matter-it-does is trying to achieve is to provide the following property: `quarkus.kubernetes.env.vars."quarkus.rest-client."external-service".url=http://example.com`. The problematic part is the second `."`.

**Comment by Sgitario** [comment]
> Yes, it is possible. You need to provide either combination:
> 
> ```
> quarkus.kubernetes.env.vars."quarkus.rest.client".external.service.url=
> QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_REST_CLIENT__EXTERNAL_SERVICE_URL=http://example.com
> ```
> 
> or
> 
> ```
> quarkus.kubernetes.env.vars."quarkus.rest.client".external.service."url"=
> QUARKUS_KUBERNETES_ENV_VARS__QUARKUS_REST_CLIENT__EXTERNAL_SERVICE__URL__=http://example.com
> ```
> 
> Note that you need to provide the dotted format of the environment variable name to disambiguate dynamic segments in the name. Please check: https://quarkus.io/guides/config-reference#environment-variables

Many thanks @radcortez !

**Comment by matter-it-does** [comment]
@radcortez hi! I attached a repro with both of your suggested approaches. Please take a look on why neither worked.

**Comment by radcortez** [comment]
Hum... this is how it is supposed to work, but it seems that the inner key quotes are getting discarded at some point. I need to investigate further.

For now, please use rest client names with a single segment.
