### ISSUE TITLE
Python support is broken in a strange way... native-image works, but not the maven build

### ISSUE THREAD

**Issue by jsight** [quarkusio/quarkus#35266]
### Describe the bug

To build a working binary:
```
mvn clean package -DskipTests -Dquarkus.package.type=native-sources -Pnative
cd target/native-sources/
native-image --language:python --initialize-at-run-time=com.redhat.iteai.HelloResource  $(cat native-image.args)
```

To build a nonworking binary:

```
mvn clean package -DskipTests -Pnative
```

### Expected behavior

Both behaviors should produce the same functional executable.

### Output of `uname -a` or `ver`

Linux jsightlerredhatlaptop2.redhatlaptop 6.3.8-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 01:51:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Java(TM) SE Runtime Environment Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)

### Quarkus version or git rev

3.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

Will provide a github repo link later.

**Comment by gsmet** [comment]
When building with Maven, are you sure the versions of the GraalVM artifacts are consistent?

I would start with checking the dependency tree.

**Comment by jsight** [comment]
Error:
2023-08-08 13:06:08,587 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: f477224c-c700-4a10-b813-9d858b6d5317-1: org.graalvm.polyglot.PolyglotException: ModuleNotFoundError: No module named 'platform'

**Comment by jsight** [comment]
Repo URL: https://github.com/jsight/quarkus-python-hello

**Comment by jsight** [comment]
@gsmet I'm not sure what you mean. I'm building with mvn in both cases, the only difference is whether the native-image step is part of that or something that is done separately.

**Comment by jsight** [comment]
@famod How is this completed? :)

**Comment by famod** [comment]
Oh, sorry...I blame my clumsy fingers on my mobile phone! 🤦‍♂️

**Comment by jsight** [comment]
No worries, happens to me all the time. I was just hoping that I'd overlooked a fix to try out. :)

**Comment by gsmet** [comment]
I don't think that's a use case we will have the cycles to analyze and fix given it has been open for so long.

If you end up having something working, feel free to post it here.

**Comment by maxandersen** [comment]
This should actually just work with recent graalpy / truffle releases where the classpath support was fixed
