### ISSUE TITLE
Multitenant should retry to resolve TenantConnectionResolver if Connection is closed

### ISSUE THREAD

**Issue by Willian199** [quarkusio/quarkus#35270]
### Describe the bug

I have a use case where tenants need to be created dynamically. So I implemented a custom TenantConnectionResolver and it worked as expected.
But if for some reason I have to remove a tenant, the only way I've found is to call DataSource.close(). Perhaps this still has the active tenant. When try to call again this tenant throws 
`ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-1) This pool  is closed and does not handle any more connections!`

Looking at the class [HibernateMultiTenantConnectionProvider](https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/tenant/HibernateMultiTenantConnectionProvider.java),  in the selectConnectionProvider they must validate if the ConnectionProvider.getConnection().isClosed() before returning.
In case of error or the tenant no longer exists, remove it from the Map.

### Expected behavior

Validate if the connection still working

```
@Override
    protected ConnectionProvider selectConnectionProvider(final String tenantIdentifier) {
        LOG.debugv("selectConnectionProvider(persistenceUnitName={0}, tenantIdentifier={1})", persistenceUnitName,
                tenantIdentifier);

        ConnectionProvider provider = providerMap.get(tenantIdentifier);
        //Fix
        if (provider == null || provider.getConnection() == null || provider.getConnection().isClosed()) {
            final ConnectionProvider connectionProvider = resolveConnectionProvider(persistenceUnitName, tenantIdentifier);
            providerMap.put(tenantIdentifier, connectionProvider);
            return connectionProvider;
        }
        return provider;

    }
```

### Actual behavior

It does not validate if the connection is working

```
@Override
    protected ConnectionProvider selectConnectionProvider(final String tenantIdentifier) {
        LOG.debugv("selectConnectionProvider(persistenceUnitName={0}, tenantIdentifier={1})", persistenceUnitName,
                tenantIdentifier);

        ConnectionProvider provider = providerMap.get(tenantIdentifier);
        if (provider == null) {
            final ConnectionProvider connectionProvider = resolveConnectionProvider(persistenceUnitName, tenantIdentifier);
            providerMap.put(tenantIdentifier, connectionProvider);
            return connectionProvider;
        }
        return provider;

    }
```

### How to Reproduce?

1. Clone my repo: [Github](https://github.com/Willian199/sample-multitenacy)

2. Configure a default Postgresql database and any tenant connection.

3. Uncomment the dataSource.close() at [TenantService.class](https://github.com/Willian199/sample-multitenacy/blob/master/src/main/java/br/com/will/service/TenantService.java#L82)

4. Start the server and update an existing tenant

### Output of `java -version`

20

### GraalVM version (if different from Java)

20

### Quarkus version or git rev

3.2.3

**Comment by Sanne** [comment]
> And for customers who stop using my system, I need to remove the database connection.

Hibernate ORM will not keep a connection open for any longer that it needs to; typically this translates to it closing the connection as soon as you complete or terminate the transaction.

Do that, and it will close the connection right away.

> A feature to remove tenants will works too.

Such logic belongs indeed in the `ConnectionResolver` : create a custom implementation and plug your implementation in.

**Comment by yrodiere** [comment]
> > A feature to remove tenants will works too.
> 
> Such logic belongs indeed in the `ConnectionResolver` : create a custom implementation and plug your implementation in.

Right. I suppose you could have the [`CustomTenantConnectionResolver`](https://github.com/Willian199/sample-multitenacy/blob/c61a730117195e40ef1482be04aa7d94896105eb/src/main/java/br/com/will/tenant/CustomTenantConnectionResolver.java#L64C14-L64C44) return a `ConnectionProvider` that is in fact a wrapper around `QuarkusConnectionProvider` instead of a direct reference. By keeping track of created connection providers (e.g. using a `Map` inside `CustomTenantConnectionResolver`), you could expose a method in `CustomTenantConnectionResolver` to "reset" a given connection provider (and the underlying datasource), which could be restarted lazily later.

**Comment by Willian199** [comment]
Thanks man.
I managed to do my  [CustomConnectionProvider ](https://github.com/Willian199/sample-multitenacy/blob/master/src/main/java/br/com/will/tenant/CustomConnectionProvider.java)

This issue and PR can be closed

**Comment by yrodiere** [comment]
Glad this helped! Closing.
