### ISSUE TITLE
InMemoryHandler keeps log level set in dev mode

### ISSUE THREAD

**Issue by The-Huginn** [quarkusio/quarkus#35272]
### Describe the bug

When using `InMemoryHandler` from `quarkus-junit5-internal` module for capturing logs, we discovered that running just tests and running continuous tests in dev mode yields different results.

We are creating custom test profile for our test class, where we lower the log level and try to capture these logs. We suspect it has something to do with the handler being static, thus keeping the log level from dev mode and not being recreated in tests.

### Expected behavior

Work the same running `./mvnw clean quarkus:test` and `./mvnw clean quarkus:dev` + pressing `r` for running tests, i.e. test passing

### Actual behavior

Tests having different results

### How to Reproduce?

Reproducer with readme: [https://github.com/The-Huginn/inMemoryHandlerReproducer](https://github.com/The-Huginn/inMemoryHandlerReproducer)

### Output of `uname -a` or `ver`

Linux fedora 6.4.6-200.fc38.x86_64

### Output of `java -version`

Java version: 17.0.7, vendor: Eclipse Adoptium

### GraalVM version (if different from Java)

GraalVM CE 22.3.1

### Quarkus version or git rev

3.2.3.Final

**Comment by xstefank** [comment]
This is actually by design - https://github.com/quarkusio/quarkus/issues/18330, see https://github.com/quarkusio/quarkus/issues/18330#issuecomment-872651310. So just by triggering DEBUG in dev mode by pressing 'j' once, the test starts passing in continuous testing too.

**Comment by The-Huginn** [comment]
Thanks for that, closing the issue
