### ISSUE TITLE
Quarkus 3.2.3-Final fails to build rest-easy-reactive apps with ContainerRequestContext filter implementations

### ISSUE THREAD

**Issue by madocx** [quarkusio/quarkus#35291]
### Describe the bug

Updating an app from 2.16.9.Final to 3.2.3.Final. After updating everything for Jakarta, quarkus build fails with below error.

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.3.Final:build (default) on project some-api: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveScanningProcessor#handleCustomAnnotatedMethods threw an exception: java.lang.RuntimeException: Parameter 'containerRequestContext' of method 'requestFilter of class 'org.some.api.RequestFilter' is not allowed

Based on quarkus documentation, there doesn't seem to be any reason this shouldn't work (nothing I can find indicates any kind of change with this supported functionality), and was working in previous version.

`
import jakarta.ws.rs.container.ContainerRequestContext;
import org.jboss.resteasy.reactive.server.ServerRequestFilter;

public class RequestFilter {

     @ServerRequestFilter(priority=0)
     public void requestFilter(ContainerRequestContext context) {      
          // filter
    }

}`

### Expected behavior

Expect app to build and the filter to work the same as it did in previous Quarkus verison.

### Actual behavior

Quarkus build fails when attempting to "handleCustomAnnotatedMethods" with a build validation exception it seems.

### How to Reproduce?

1. Create a resteasy-reactive-jackson project
2. Implement a request filter as shown above with ContainerRequestContext
3. Attempt to build

### Output of `uname -a` or `ver`

Liinux a-20b6iv5ait3pg 5.15.108-65.141.amzn2.x86_64 #1 SMP Tue Apr 25 05:37:13: UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version 11.0.14.1

### Quarkus version or git rev

3.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.5

**Comment by madocx** [comment]
So sorry to waste your time, I'm an idiot. My filter impl is in a jar that I must not have installed to my local mvn repo after updating for jakarta and was using an old snapshot version with javax. Its working now, and this is the only thing I can think of.

If I can make an enhancement recommendation, perhaps io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveScanningProcessor#handleCustomAnnotatedMethods can be updated to include the fully qualified name of the class in the exception? In this case, it probably would have saved me hours or time, although my own mistake.

If there's a specific place I can submit this request please let me know.

Thanks again!

**Comment by geoand** [comment]
You can submit a pull request with your enhancement if you like 🙂

**Comment by gsmet** [comment]
> If I can make an enhancement recommendation, perhaps io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveScanningProcessor#handleCustomAnnotatedMethods can be updated to include the fully qualified name of the class in the exception? In this case, it probably would have saved me hours or time, although my own mistake.

I think it makes sense given the move to the jakarta package. Could you create a pull request against this very repo?

If you can't do it, let me know, I will have a look.
