### ISSUE TITLE
CLI: test command - add an option to filter the tests

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#35292]
### Description

Add an option to filter the executed tests, i.e. an equivalent of `mvn test -Dtest=org.amce.Foo`/`gradle test --tests "org.acme.Foo"`.

This will probably require a change in continuous testing because it runs all the tests.

This issue is related to https://github.com/quarkusio/quarkus/issues/35290 in the sense that we should support filtering for both the continuous and `--once` mode.

### Implementation ideas

`quarkus test --tests "org.acme.FooTest"`

**Comment by ebullient** [comment]
I would use `--filter` or `--match` over a very redundant feeling `--tests`

**Comment by mkouba** [comment]
> This will probably require a change in continous testing because it runs all the tests.

In fact, the `quarkus.test.include-pattern` system property can be used to filter the executed tests.
