### ISSUE TITLE
Wrong links to GraalVM in Native Reference Guide

### ISSUE THREAD

**Issue by cristalp** [quarkusio/quarkus#35303]
### Describe the bug

The [Native Reference Guide](https://quarkus.io/guides/native-reference) has some links to GraalVM documentation pages, but they don't exist anymore.

https://www.graalvm.org/jdk-17/reference-manual/native-image/optimizations-and-performance/MemoryManagement
https://www.graalvm.org/jdk-17/reference-manual/native-image/debugging-and-diagnostics/JFR/

### Expected behavior

Should link to existing pages

### Actual behavior

Links to non-existing pages

**Comment by geoand** [comment]
cc @zakkak @galderz
