### ISSUE TITLE
OpenTelemetry extension is trying to export traces to localhost:4317 by default in production mode

### ISSUE THREAD

**Issue by jholleran** [quarkusio/quarkus#35306]
### Describe the bug

When upgrading to Quarkus 3 there are now `SEVERE` log messages now outputted saying that its failing to export OpenTelemetry traces to `localhost/127.0.0.1:4317` even when run in production mode.

Here is the full log message:
```
2023-08-10 10:12:50,489 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
```

This occurs when using the OpenTelemetry extension but not configuring it to connect it to external OpenTelemerry Collector. This is how we want to setup our service by default so a OpenTelemerry Collector can be configured later but by default we need this to be a no-op.

### Expected behavior

By default, the OpenTelemetry extension we expect it to not try an export traces in production mode to localhost (or anywhere else). It should be a no-op. 

### Actual behavior

The OpenTelemetry extension is trying to connect and export traces to localhost in production mode.

Previously even in Quarkus 2 when run in dev mode (quarkus:dev) this SEVERE log message was logged repeatedly and this is also the case in Quarkus 3. However in running Quarkus 2 in production mode this log message is **not** logged but it does now appears in Quarkus 3.

Quarkus version: 3.2.3.Final
![image](https://github.com/quarkusio/quarkus/assets/1751613/c471b33a-9d4d-41cd-9f65-36a6837f2eb1)

Running the application in production mode we can see the SEVERE logs:
![image](https://github.com/quarkusio/quarkus/assets/1751613/2ec96cbb-d9f5-4648-8994-ecbcd373c91b)

Rolling back to Quarkus version: 2.16.9.Final
![image](https://github.com/quarkusio/quarkus/assets/1751613/bcff2f26-9759-42a6-abf7-b6839d113aa8)

_Note:_ `jakarta.ws.rs` package names need to be reverted to `javax.ws.rs`

Building and running the application again there are no SEVERE logs. It also has a log of: `No BatchSpanProcessor delegate specified, no action taken`:
![image](https://github.com/quarkusio/quarkus/assets/1751613/923cf2ed-2b1a-47fa-bbf1-6c155e946cf6)

And just to show that even in Quarkus 2 in dev mode the SEVERE exists. This is not a problem for us in dev mode but in production mode we don't want to see this.
![image](https://github.com/quarkusio/quarkus/assets/1751613/9c2118a3-cad8-4935-8ffe-44354b461fb4)

### How to Reproduce?

This issue can be reproduce this using the https://quarkus.io/get-started/ app and adding the [OpenTelemetry](https://quarkus.io/extensions/io.quarkus/quarkus-opentelemetry) extension.

Steps to reproduce:
1. Follow steps in https://quarkus.io/get-started/ to create a simple Quarkus application
2. Add the OpenTelemetry extension: https://quarkus.io/extensions/io.quarkus/quarkus-opentelemetry
3. Build: `quarkus build`
4. Run: java -jar target/quarkus-app/quarkus-run.jar
5. Hit the home page of the app a couple of time to generate some traces

The output will look as follows that will show the SEVERE log messages:
![image](https://github.com/quarkusio/quarkus/assets/1751613/2ec96cbb-d9f5-4648-8994-ecbcd373c91b)

### Output of `uname -a` or `ver`

Linux europa 6.2.0-060200-generic #202302191831 SMP PREEMPT_DYNAMIC Sun Feb 19 23:37:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04) OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-122.04, mixed mode, sharing)

### Quarkus version or git rev

3.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /home/holleranj/.m2/wrapper/dists/apache-maven-3.9.3-bin/326f10f4/apache-maven-3.9.3 Java version: 17.0.8, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.2.0-060200-generic", arch: "amd64", family: "unix

**Comment by Mulgish** [comment]
Seeing same issue

**Comment by brunobat** [comment]
This happens per design.
Whenever you include the dependency it will work out of the box, with the defaults.
Among other things, this will allow observability dev services in the near future.

Please add this config to your `application.properties` main file:
[quarkus.otel.sdk.disabled=true](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.otel.sdk.disabled)
This will disable the OTel SDK.

In prod you just need to add the URL and set it to 
`quarkus.otel.sdk.disabled=false`

Will close the issue.

**Comment by timea-solid** [comment]
An update :
* `quarkus.otel.sdk.disabled=true` disables any JDK features and we actually make use of some. Setting this as `true` is not a solution for us.
* nor is setting `quarkus.otel.traces.exporter=none` because it cannot be turned on later on again since it is a build time var.

The expectation here is that one can simply use the JDK features without needing to export traces but still have the option to turn it on later. As such, I believe this is either a bug or a feature request. Could you further consider it?

**Comment by brunobat** [comment]
@timea-solid that is a valid use that is already predicted.
Please use a `Sampler` like in this documentation example: https://quarkus.io/guides/opentelemetry#sampler

if you set the sampler properties like this, you can turn on and off export at runtime: 
```application.properties
# build time property only:
quarkus.otel.traces.sampler=traceidratio
# On (default). All traces are exported:
quarkus.otel.traces.sampler.arg=1.0
# Off. No traces are exported:
quarkus.otel.traces.sampler.arg=0.0
```

**Comment by timea-solid** [comment]
@brunobat thanks for the input! 
I was looking into an own `Sampler`, and now you validated our idea. 👍🏻
