### ISSUE TITLE
Support Hibernate config for `hibernate.generate_statistics`

### ISSUE THREAD

**Issue by t1** [quarkusio/quarkus#35325]
### Description

I want Hibernate to collect statistics. I have a reproducer [here](https://github.com/t1/quarkus-hibernate-statistics-test-demo). Currently I have to configure:

`quarkus.hibernate-orm.unsupported-properties."hibernate.generate_statistics" = true`

As it's suggested for `unsupported-properties`, it would be nicer to have explicit support.

### Implementation ideas

 Something like this:

`quarkus.hibernate-orm.generate-statistics = true`

**Comment by yrodiere** [comment]
Hi,

There's already [`quarkus.hibernate-orm.statistics`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.statistics), so I'd recommend you use that.

I'll close this ticket as it seems to me the feature already exist. Feel free to comment if I'm wrong and we'll consider reopening.

**Comment by t1** [comment]
Thanks @yrodiere! This setting (as well as `quarkus.hibernate-orm.metrics.enabled`, which would help, too) just doesn't show up in the IDE, as it's not in the `HibernateOrmRuntimeConfigPersistenceUnit` class. I'm on 3.2.4.Final.

**Comment by yrodiere** [comment]
This is not a runtime setting, but a build-time setting. And it's scoped to the extension, so you can't configure it per persistence unit. You'll find it here:

https://github.com/quarkusio/quarkus/blob/ec5c243d4ef611c2328bbf99dd324e1f73781cfd/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java#L70

When you say it doesn't show up in the IDE, do you mean it doesn't show up through auto-completion with the Quarkus IDE plugin? If so, which IDE are you using? You might want to report this to the [relevant GitHub project](https://quarkus.io/guides/ide-tooling).
