### ISSUE TITLE
Mention that graal-sdk is no longer in 3.3 in migration guide

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#35352]
### Description

In the [migration guide for 3.3](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3) there should be a section for extension authors using `@Substitute` that they should include the `graal-sdk` artifact by themself

**Comment by geoand** [comment]
@zakkak or @galderz can you update https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.3 to address this?

**Comment by gsmet** [comment]
I will do it.

**Comment by gsmet** [comment]
So this is actually a change that went unnoticed because it's a consequence of making all the svm dependency consistently provided.

**Comment by geoand** [comment]
Thanks!
