### ISSUE TITLE
Scheduler with coroutines and hibernate-reactive does not run on worker-thread/executor-thread

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#35359]
### Describe the bug

Hello Quarkus community! I currently have an application that has a scheduled job. The job executes a database operation (to retrieve records) and returns (to test performance, mainly). The application is in Kotlin and I am attempting to leverage coroutines for this. The way I currently have it is by denoting the scheduled method type as suspend and then running a coroutine function within (the aforementioned database operation). The problem is that this operation somehow runs on the event-loop thread and therefore I encounter a lot of BlockedThreadChecker warnings since it is a long running operation. How would I be able to shift this operation to a worker thread?

Database operation:
```
suspend fun getAll(): List<SomeEntity> {
        val entities = listOf<SomeEntity>()
        val duration = measureTimeMillis {
            sessionFactory.withTransaction { session ->
                session.createNativeQuery(
                    FETCH_SOME_ENTITY_CONSTANT,
                    SomeEntity::class.java,
                ).setMaxResults(DATABASE_FETCH_SIZE).resultList.map { entities }
            }.awaitSuspending()
        }

        log.info("SomeEntity retrieval successful. Duration: $duration milliseconds")

        return entities
    }
```
Scheduled job:
```
@Scheduled(
        every = "5s",
        identity = SOME_IDENTITY_CONSTANT,
        skipExecutionIf = QuartzSkipPredicate::class,
        concurrentExecution = Scheduled.ConcurrentExecution.SKIP,
    )
    suspend fun executeJob() {
        callCoroutineDatabaseOperation()
 }
```

### Expected behavior

I should be able to run a long-running coroutine function within the Vertx worker-thread or executor-thread. 

### Actual behavior

Coroutine functions under a scheduled method run under the event-loop-thread and thus emit many BlockedThread warnings when a long-running operation is encountered.

### How to Reproduce?

1. Start a brand new project (Kotlin/Gradle/hibernate-reactive/quartz)
2. Create a scheduled function using the `suspend` type and ensure a long-running operation is invoked (preferably using hibernate-reactive's coroutines extension functions).
3. Start the application and observe logs coming in the event-loop-thread with multiple BlockedThread warnings.

### Output of `uname -a` or `ver`

Darwin C02G54SCMD6R 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

11

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

I started this same discussion over in Quarkus ZulipChat but I don't believe anyone knows how to switch from the event-loop thread to a worker-thread when dealing with coroutines in the reactive world. The last statement I got was that hibernate-reactive + coroutine support would need to be implemented first but I'm a bit unsure of what this means (without elaboration), hence why I'm asking a broader audience here.

ZulipChat Link: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/How.20to.20run.20a.20scheduled.20coroutine.20job.20on.20worker.20thread

**Comment by mschorsch** [comment]
You have to inject a managed executor (https://quarkus.io/guides/context-propagation#usage-example-for-completionstage), then use `withContext` to switch to a worker thread.

```kotlin
withContext(managedExcecutor.asCoroutineDispatcher()) {
  ....
}
```

**Comment by LazaroR94** [comment]
> You have to inject a managed executor (https://quarkus.io/guides/context-propagation#usage-example-for-completionstage), then use `withContext` ( https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-context.html) to switch to a worker thread.
> 
> ```kotlin
> withContext(managedExcecutor.asCoroutineDispatcher()) {
>   ....
> }
> ```

Thanks for the tip! However, the managed executor yields an error stating that we cannot execute hibernate-reactive's functions outside of an event-loop thread for some reason:
`java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'executor-thread-1'`

**Comment by mschorsch** [comment]
This seems a hibernate problem. Just use https://quarkus.io/guides/reactive-sql-clients. This should work out of the box with suspend functions, without switching to a worker thread.

**Comment by mkouba** [comment]
@LazaroR94 FYI it's not possible to use Hibernate Reactive on a worker thread. Is it really the DB operation that takes so much time?  If possible, I'd recommend you to split the processing into several concurrent parts.

**Comment by gsmet** [comment]
Closing for lack of feedback.
