### ISSUE TITLE
Quarkus-cli shortcut to generate an application.yaml or an application.properties file

### ISSUE THREAD

**Issue by bogedal** [quarkusio/quarkus#35375]
### Description

I'd like to be able to use --config-yaml or --config-property (default) when creating a new quarkus project using the cli.

`quarkus create app --config-yaml` should create a project with an application.yaml file
`quarkus create app --config-property` should create a project with an application.properties file
`quarkus create app` should create a project with an application.properties file

**Comment by ia3andy** [comment]
As seen with @bogedal currently the only way to achieve this is to add the quarkus-config-yaml extension, but this also comes with the codestart, so having this option would allow to just have the config yaml without the starter code.

**Comment by ia3andy** [comment]
ahh yes, I forgot the extension is actually needed...

**Comment by maxandersen** [comment]
So..have us generate yaml when the yaml extension is included and properties otherwise?

**Comment by bogedal** [comment]
@gsmet indeed the quarkus-config-yaml works in its current version.
However it also adds a GreetingConfig file and a property into the application.yaml, which I do not want.

Thus this suggestion :)

**Comment by bogedal** [comment]
@ia3andy @gsmet 
I understand your comments. It is a very low impact change. Just thought it would be nice to create a quarkus project with an application.yml file without having added samle code.

I will close this issue.
