### ISSUE TITLE
PR commenting via Idea Community does not work

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#35387]
### Describe the bug

Commenting on PRs with Idea Community does seem to be forbidden by the repository. This is a bit annoying for contributers

### Expected behavior

Works

### Actual behavior

This is what it looked like when I tried to comment
![grafik](https://github.com/quarkusio/quarkus/assets/314259/1b446be4-6eb7-4d0c-9e1f-91368d51d8dc)

**Comment by geoand** [comment]
I don't see how this can a problem in the Quarkus repo itself, so I am going to close this.

However, if someone can provide evidence that it is a result of something Quarkus does, I'll gladly reopen
