### ISSUE TITLE
OpenShiftClientProducer simplification

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#35383]
### Description

OpenShiftClientProducer creates it's own client instance, however that may lead to two clients if an application also injects  a KubernetesClient

### Implementation ideas

The OpenShiftClientProducer should inject the KubernetesClient and adapt it to an OpenShiftClient.

**Comment by geoand** [comment]
I'll leave this to @manusa and @metacosm

**Comment by metacosm** [comment]
I think this makes sense to only have one client as I don't think people would need to have 2 separate instances of the client.

**Comment by manusa** [comment]
I was actually convinced that I changed the behavior to what Steven is describing.

Yes, IMHO, this is how it should be. The OpenShiftClient bean should actually be an adaptation of the original KubernetesClient.

However, this might have implications for those who might be using 2 different clients (not sure if this is a wide-spread use-case) to connect to different clusters.

**Comment by manusa** [comment]
I was confused, I thought there was an isolated `OpenShiftConfig` bean. But there isn't, the OpenShiftClientProducer reuses the `Config` produced by the KubernetesClient extension:

https://github.com/quarkusio/quarkus/blob/4b968203b70159b97b5a767d46511994434b68d9/extensions/openshift-client/runtime/src/main/java/io/quarkus/it/openshift/client/runtime/OpenShiftClientProducer.java#L26-L39

So although there are non-standard ways to achieve it, none of them fall in any of the supported scenarios.

Replacing the bean dependencies for the producer will fix the issue with no risk.

**Comment by manusa** [comment]
I'll provide the fix for this (unless someone else is already working on it), you can assign it to me.

**Comment by geoand** [comment]
Thanks.

Assigned to you.

**Comment by manusa** [comment]
For the record, the two beans won't always be available since we have the following restriction in the KubernetesClient processor

https://github.com/quarkusio/quarkus/blob/ba2efea261fa047a63161add7e7ffbe6fafa192a/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/KubernetesClientProcessor.java#L87-L91

In any case, I'll still simplify the class by extending the OpenShiftClientProducer in #35525

**Comment by manusa** [comment]
Given https://github.com/quarkusio/quarkus/issues/35383#issuecomment-1691841780 and https://github.com/quarkusio/quarkus/pull/35525#issuecomment-1699177002 we might want to close this issue as not planned.

**Comment by geoand** [comment]
Makes sense!
