### ISSUE TITLE
Downgrade in speed for big SQL operations with reactive DB

### ISSUE THREAD

**Issue by StanislavMakhrov** [quarkusio/quarkus#35423]
### Describe the bug

I want to make 400 batch inserts to DB. If I do it manually (without Quarkus, code, etc) in DB Manager in JetBrains IDEA then in takes 3 mins.
If I do the same in 4 tabs simultaneously then  it takes 40 secs (very nice in comparison to sequential launch of queries).

So, when I want to do the same on  Quarkus + Panache + Mutiny via

```
builder.joinAll().andCollectFailures()
.onFailure().recoverWithNull()...
```

then it takes 1 min 40 secs (it's faster than sequential but slower then 4 tabs which I have tried manually).

Looks like we have some bottleneck in multithreading. Or builder.joinAll() is not a good approach for such task?

### Expected behavior

Inserts take 40 secs

### Actual behavior

Inserts take 1 min 40 secs

### How to Reproduce?

You can make simple app which makes 400 or 4000 inserts like:
INSERT INTO mydb.User (userLogin, displayName) VALUES ('user1', 'User1');
And compare time of completion with direct completion by manual (without Quarkus)

### Output of `uname -a` or `ver`

Darwin MYPCNAME 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17.0.4+8-jvmci-22.2-b06

### GraalVM version (if different from Java)

3.2.4.Final

### Quarkus version or git rev

Apache Maven 3.8.6

**Comment by geoand** [comment]
We'll need a lot more information on what your code is doing if we are to help

**Comment by geoand** [comment]
Closing for a lack of feedback
