### ISSUE TITLE
Configuring init container image (for startup tasks) requires looking into the quarkus code

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#35436]
### Describe the bug

Imagine an init task. 
You want to configure the "wait-for" image to avoid the default one (which has many issues).

So, you need to configure:

```
quarkus.kubernetes.init-tasks.<make-and-eductated-guess>.image=quay.io/cescoffi/wait-for-job
```

It's almost only possible to find the name by diving into the code of Quarkus. For me, it was: coffeeshop-service-kafka-topic-init, a mix between the application and the task name.

**Comment by gsmet** [comment]
This has been addressed by changes @iocanel made. I also improved the doc in https://github.com/quarkusio/quarkus/pull/45296 .
