### ISSUE TITLE
Unable to use init action when building on openshift

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#35430]
### Describe the bug

When having an application using the init-container / job support to pre-initialize the environment, and when deploying this application using:

```
 quarkus deploy openshift --image-build 
```

The job fails as the image is not built: 

```
coffeeshop-service-kafka-topic-init-2rwbb image pull backoff
```

### Expected behavior

The image must be built.

### Actual behavior

The image is not.

**Comment by cescoffier** [comment]
I believe the reason is the image coordinate in the descriptor:

```
image: clement/coffeeshop-service:1.0-SNAPSHOT
```

**Comment by geoand** [comment]
Is this still an issue?

**Comment by cescoffier** [comment]
I'm not sure. Let's close it, and if I get the same error again, I will open a new one. 
I've moved away from init-tasks for now, as CRD seems to become the norm.

**Comment by geoand** [comment]
👌
