### ISSUE TITLE
Application start fails with NullPointerException because of MicrometerRecorder changes (3.3.0)

### ISSUE THREAD

**Issue by holomekc** [quarkusio/quarkus#35443]
### Describe the bug

With Quarkus 3.3.0 our application cannot start anymore and fails with a NullPointerException:

```java
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "classSpecificCustomizers" is null
	at io.quarkus.micrometer.runtime.MicrometerRecorder.configureRegistries(MicrometerRecorder.java:99)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy(Unknown Source)
```

We have a custom MeterRegistry (DynatraceMeterRegistry). We configured it exactly like this:
https://quarkus.io/guides/telemetry-micrometer#create-a-customized-meterregistry

After debugging I could see that ```registryClasses```
https://github.com/quarkusio/quarkus/blob/2c6f8b84a115fbab00e562591a277dbeb8869c8d/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java#L65

Only contains two registries:
- PrometheusMeterRegistry
- JsonMeterRegistry

But in this line:
https://github.com/quarkusio/quarkus/blob/2c6f8b84a115fbab00e562591a277dbeb8869c8d/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java#L80

Quarkus finds three beans:
1. PrometheusMeterRegistryProducer...
2. JsonMeterRegistryProvider...
3. DynatraceMicrometerRegistry...

The loop over the beans with three entries then tries to find the ```classSpecificCustomizers``` for ```DynatraceMeterRegistry```:
https://github.com/quarkusio/quarkus/blob/2c6f8b84a115fbab00e562591a277dbeb8869c8d/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java#L97

This returns ```null```, which results in a ```NullPointerException``` in line:
https://github.com/quarkusio/quarkus/blob/2c6f8b84a115fbab00e562591a277dbeb8869c8d/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerRecorder.java#L99

### Expected behavior

Our application can start as usual 😉 .

### Actual behavior

See bug description.

### How to Reproduce?

See bug description.

### Output of `uname -a` or `ver`

Darwin <PC> 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.7 2023-04-18 LTS

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.2

**Comment by holomekc** [comment]
I could find that these changes are introduced here:
https://github.com/quarkusio/quarkus/commit/fbd6e522175a3ceddcde492ae76a19c12d40a7f1#diff-60163295574610b7cbe78ad23a4f19555ed7cc535df755adda53998976c6279e

because of:
https://github.com/quarkusio/quarkus/issues/32996

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
If however you can provide a sample application, we can make sure that nothing else broke as well.
