### ISSUE TITLE
Warn users if they mix RESTEasy Classic and Reactive

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#35454]
### Description

Warn users if they mix RESTEasy Classic and Reactive.

We had issue with application that was RESTEasy Reactive base but we used `resteasy-multipart-provider` for easy work with multipart form data. Starting with Quarkus 3.0 there is MultipartFormDataInput so I could migrate the app to use it.

In our case it wasn't obvious what the trouble was because native image build failed with error message about ResourceCleaner, the issue was reported on product side in https://issues.redhat.com/browse/QUARKUS-3308

Is Quarkus able to detect that an application mixes RESTEasy Classic and Reactive? If so, there could be a warning about that - during the build and maybe also during the boot.

**Comment by geoand** [comment]
We already do prevent users from mixing both extensions, but I suspect here you are adding some random RESTEasy dependency, correct?

**Comment by gsmet** [comment]
Yes, in that case, it was a random RESTEasy Classic artifact.

I wonder if we detect when RESTEasy Reactive server is used with the classic REST Client though. I remember we had people reporting cases where we didn't properly detect the conflicts.

**Comment by geoand** [comment]
I am pretty sure we can go through all dependencies and warn if a `RESTEasy Classic`  dependency is added.

**Comment by gsmet** [comment]
Yeah, using the `CurateOutcomeBuildItem`, we can definitely do that.

And it would solve the REST Client case too. Given we are pushing people towards RESTEasy Reactive, I think we could have this in the processor common to the RESTEasy Reactive server and client and throw an error if anything RESTEasy Classic is around.

**Comment by geoand** [comment]
That sounds like a good idea, but I am still on the fence of whether we should just warn or fail in the RESTEasy Reactive Server + RESTEasy Classic Client caser.

**Comment by gsmet** [comment]
Well, is it a working combination? From the reports we had, I thought it wasn't working very well. But maybe I misremember.

**Comment by geoand** [comment]
Same, I don't remember either, I would need to check :)

**Comment by geoand** [comment]
I did some tests and under some circumestances the combination works. So I think that we should be convervative and only warn for the RESTEasy Reactive Server + RESTEasy Classic Client combination.

WDYT?

**Comment by gsmet** [comment]
I dunno. Maybe we could be conservative in a few versions and raise an error after that?

I mean the first thing we will do if someone reports a bug with this combination is to ask them to be consistent, so I don't think it makes sense to support this combination long term :).
