### ISSUE TITLE
Dev Service Containers are not stopped between test classes

### ISSUE THREAD

**Issue by Aviss** [quarkusio/quarkus#35464]
### Describe the bug

When using `@QuarkusTestResource`s that are restricted to the annotated test class dev services are started for each such class. That is not an issue on its own and is probably desired behaviour. 
However, even if the test class is finished, containers are not stopped until the `maven-failsafe-plugin` execution finishes. 

In a project like ours where we have potentially dozens of such test classes this quickly leads to memory issues as the containers can easily take up up to 1GB of memory. 

Since this container duplication also happens with test classes that have the exact same annotations, I file this as a bug, as I cannot see how any of these dev services could be reused by another test class. 

Barring a fix, any advice on how to work around this issue is also greatly appreciated.

### Expected behavior

When a test class finishes, all of the dev services that are only needed for this class are instructed to stop before execution of the next test begins

### Actual behavior

Dev services that are only needed for one class persist until execution of all test classes has finished

### How to Reproduce?

Reproducer: [reproducer.zip](https://github.com/quarkusio/quarkus/files/12407447/reproducer.zip)

Steps to reproduce:
1. Run `mvn clean install`
2. Observe when containers are created and stopped during the verify step

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.3324]

### Output of `java -version`

openjdk 17.0.2 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.15.1.Final, 3.2.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\USER\.m2\wrapper\dists\apache-maven-3.8.5-bin\5i5jha092a3i37g0paqnfr15e0\apache-maven-3.8.5 Java version: 11.0.2, vendor: Oracle Corporation, runtime: D:\Build\Java\jdk-11.0.2 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
@Aviss would you be able to test https://github.com/quarkusio/quarkus/pull/35486?

**Comment by Aviss** [comment]
Can confirm, dev-services are stopped after each test finishes. The `testcontainers:ryuk` instances still stay up, but due to the low memory footprint I do not see a problem with that behaviour.

**Comment by geoand** [comment]
Wonderful, thanks for checking
