### ISSUE TITLE
3.3.0.CR1 fails to build with kotlin/gradle project

### ISSUE THREAD

**Issue by jimkont** [quarkusio/quarkus#35467]
### Describe the bug

Using the default quarkus generator for a gradle/kotlin project with the kotlin extension does not build. If you use the default gradle version (8.1.1) you get a generic error
```
* What went wrong:
Execution failed for task ':compileKotlin'.
> org/jetbrains/kotlin/incremental/IncrementalJvmCompilerRunnerKt
```
using the `7.6.1` gradle version, which I use in my project fails with

```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm', version: '1.8.22']
> Failed to apply plugin 'org.jetbrains.kotlin.jvm'.
   > Could not create an instance of type org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSet.
      > kotlin/enums/EnumEntriesKt
```

It seems to be related to this: https://youtrack.jetbrains.com/issue/KT-58021.

I attach the sample project for reference [here](https://github.com/quarkusio/quarkus/files/12408057/project.zip)

### How to Reproduce?

run `./gradlew build` in the attached project

### Output of `uname -a` or `ver`

Darwin K4V32WY17P 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 LTS

### Quarkus version or git rev

3.3.0.CR1

**Comment by geoand** [comment]
cc @ia3andy

**Comment by aloubyansky** [comment]
Updating to
```
    kotlin("jvm") version "1.9.0"
    kotlin("plugin.allopen") version "1.9.0"
```
it takes it further with Gradle 8.1.1.

**Comment by aloubyansky** [comment]
Which is how a new project is generated for 3.3.0.

**Comment by jimkont** [comment]
I confirm that with kotlin version 1.9.x the project compiles
