### ISSUE TITLE
Unable to log response time in HTTP access log

### ISSUE THREAD

**Issue by mzuber** [quarkusio/quarkus#35472]
### Describe the bug

None of the [log format attributes defined to add the time taken to process a request](https://quarkus.io/guides/http-reference#configuring-http-access-logs) to the HTTP access log seems to work for me.

Using the access log pattern

```
quarkus.http.access-log.pattern = %{REQUEST_LINE} %{RESPONSE_CODE} %D %{RESPONSE_TIME} %T %{RESPONSE_TIME_MICROS} %{RESPONSE_TIME_NANOS}
```

doesn't produce a response time in the log messages for any of the given attributes, e.g.

```
2023-08-22 16:10:48,615 INFO  [io.qua.htt.access-log] (executor-thread-1) GET /tags HTTP/1.1 200 - - - - -
2023-08-22 16:11:00,972 INFO  [io.qua.htt.access-log] (vert.x-worker-thread-1) GET /q/health HTTP/1.1 200 - - - - -
```

### Expected behavior

The response time of a request becomes part of the HTTP access log when using any of the corresponding attributes in the log pattern definition.

### Actual behavior

The response time value is always `-`.

### How to Reproduce?

Define a custom access log pattern including `%D`, `%{RESPONSE_TIME}`, `%T`, `%{RESPONSE_TIME_MICROS}`, or `%{RESPONSE_TIME_NANOS}`.

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### Quarkus version or git rev

3.2.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by mzuber** [comment]
@andrearaponi Thanks for the hint, enabling the `quarkus.http.record-request-start-time` configuration property did the trick, I now see the request times in the HTTP access logs. I will provide a PR adding a note to the documentation.

**Comment by cescoffier** [comment]
Yes, you need explicitly enable it, as it's a bit expensive (we need to track all concurrent requests).
