### ISSUE TITLE
Vertx SQL client hangs, when trying to save null or empty string into Oracle

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#35477]
### Describe the bug

I have an application, which uses vetrx sql (mutiny) client to save data into database using preparedSQL method inside a transaction.
When I use it for a statement like this: `INSERT INTO passenger (nif,name,last_name,contact_number,created_at,address_id) VALUES (null,'Walt','White','+34608554433',1692717882078,2)` or like this `INSERT INTO passenger (nif,name,last_name,contact_number,created_at,address_id) VALUES ('','Walt','White','+34608554433',1692718041072,2)` the application hangs indefinitely, but only if I use Quarkus version 3.1.0.Final or newer. In the older versions (for other databases) I receive this error: `Error Msg = ORA-01400: cannot insert NULL into ("TEST"."PASSENGER"."NIF")`. If  empty value (`nif` in this case) is replaced with an ordinary one, then everything works as expected.

### Expected behavior

The transaction should fail.

### Actual behavior

App hangs indefinitely

### How to Reproduce?

1. `git clone -b 3.2 git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `mvn clean verify -pl sql-db/vertx-sql -Dit.test=OracleHandlerIT#basketScenario -Dquarkus.platform.version=3.2.0.Final`

Use `-Dquarkus.platform.version=3.0.0.Final` to compare with other version, `-Dit.test=PostgresqlHandlerIT#basketScenario`(or `MysqlHandler`) to compare with other databases and remove this line[1] to compare with non-null string.

[1] https://github.com/quarkus-qe/quarkus-test-suite/blob/3.2/sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/spec/BasketHandlerSpec.java#L33

### Output of `uname -a` or `ver`

6.3.8-200.fc38.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### Quarkus version or git rev

3.2.0.Final, 3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by fedinskiy** [comment]
@tsegismont Could you try the same, but with 

```
POST http://localhost:8082/basket/checkout
Content-Type: application/json

{
  "id": null,
  "flight": "IB9961",
  "price": 437.52,
  "billingPassenger": {
    "id": null,
    "nif": null,
    "name": "Walt",
    "lastName": "White",
    "contactNumber": "+34608554433",
    "address": {
      "id": null,
      "street": "Avd. del Tomillaron",
      "blockNumber": "4b",
      "zipCode": "28080",
      "city": "Madrid",
      "country": "Spain"
    }
  }
}
```

The original reproducer uses null "nif" field to check, how does the database (and vertx) handle errors

**Comment by tsegismont** [comment]
Thank you for the update

**Comment by tsegismont** [comment]
Reading the release notes, it seems the major changes that could impact this area in this Quarkus release are:

- upgrade to Vert.x 4.4
- upgrade to Oracle JDBC 23

So I tried the steps above (using `null` for `nif) but forcing the JDBC driver version to 21:

```java
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
            <version>21.5.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
            <version>21.5.0.0</version>
        </dependency>
```

And then the request fails correctly:

```
HTTP/1.1 400 Bad Request
content-length: 525
content-type: application/json

{
  "msg": "[SQL INCLUDES EXPRESSIONS ADDED BY THE ORACLE JDBC DRIVER],Error : 1400, Position : 88, Sql = INSERT INTO passenger (nif,name,last_name,contact_number,created_at,address_id) VALUES (null,'Walt','White','+34608554433',1692874968119,30) RETURNING ID INTO :1 , OriginalSql = INSERT INTO passenger (nif,name,last_name,contact_number,created_at,address_id) VALUES (null,'Walt','White','+34608554433',1692874968119,30) RETURNING ID INTO ?, Error Msg = ORA-01400: cannot insert NULL into (\"TEST\".\"PASSENGER\".\"NIF\")\n"
}
```

@Sanne are you aware of any important change regarding Oracle JDBC between v21 and v23?

**Comment by tsegismont** [comment]
@fedinskiy to be clear, I suspect this is a consequence of https://github.com/quarkusio/quarkus/pull/32570

Now I need to understand what's changed in Oracle JDBC that could explain the problem. Or perhaps that's a bug in the JDBC driver.

**Comment by fedinskiy** [comment]
@tsegismont I found this issue, which may be related: https://github.com/eclipse-vertx/vertx-sql-client/issues/1343

**Comment by tsegismont** [comment]
@fedinskiy thanks. I'm back from PTO and I haven't caught yet with all GH notifications. Indeed, this looks related.

**Comment by geoand** [comment]
If https://github.com/eclipse-vertx/vertx-sql-client/issues/1343 is the culprit, we should probably close this and only track the problem upstream

**Comment by tsegismont** [comment]
@geoand fine with me
