### ISSUE TITLE
Openshift - Configure logging to not write in a file

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#355]
Because it requires specific permission in the CWD.
Ideally, this can be passed in the command line:

```
./app -Dlogfile=none
```

or something like that.

**Comment by gsmet** [comment]
@geoand do we need any action in the default ``Dockerfile``s or whatever is used in OpenShift?

**Comment by geoand** [comment]
Yes, we would need to add that to the generated Dockefiles

**Comment by geoand** [comment]
@vorburger I assume this is something we need to add to the native s2i process as well?

**Comment by vorburger** [comment]
@geoand yup, and I have proposed that in #1599 if that's the conclusion of this issue's discussion...

... but I personally actually do also think that this is the wrong approach - the default of `true` of [quarkus.log.file.enable](https://quarkus.io/guides/logging-guide) seems wrong, to me, for a "Kubernetes Native Java stack" framework... IMHO default should be console, only; and log file should be opt-in (12 Factor).

> -Dshamrock.log.file.enable=false

BTW: It's `quarkus.log.file.enable` and not `shamrock.log.file.enable`, right?? [That's what doc'd](https://quarkus.io/guides/logging-guide).

**Comment by vorburger** [comment]
We should do something similar in https://github.com/quarkusio/quarkus-quickstarts/pull/81 (non-native S2I) ?

**Comment by geoand** [comment]
@vorburger I think we should. I am going to open a PR containing a fix only to the generated Dockerfiles

**Comment by geoand** [comment]
I added PR #1600 for the generated Dockerfiles

**Comment by dmlloyd** [comment]
FWIW disabling file logging by default is OK with me.

**Comment by vorburger** [comment]
> FWIW disabling file logging by default is OK with me.

@dmlloyd I'm happy to raise the respective PR, but I have no idea where the default of `quarkus.log.file.enable` is defined in the sources... I cannot find it via a quick dumb `grep`. If you'd like to give me a hint/pointer, I could have a closer look.

**Comment by dmlloyd** [comment]
It's this line here: https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/logging/FileConfig.java#L31
