### ISSUE TITLE
OpenTelemetry vertx exporter wrongly parses the endpoint 

### ISSUE THREAD

**Issue by mazenkhalil** [quarkusio/quarkus#35501]
### Describe the bug

404 error code occur while submitting the traces to open telemetry api.

The issue is originated from `io.quarkus.opentelemetry.runtime.exporter.otlp.VertxHttpExporter`. The implementation extracts the host from the base uri and ignores the paths.
![image](https://github.com/quarkusio/quarkus/assets/21160900/d0b6fc0e-f1fd-45c0-9826-132652d0fec8)

Below a screenshot from my configurations and how it ended up in the exporter.
![image](https://github.com/quarkusio/quarkus/assets/21160900/602f8c31-829e-4e13-8a3a-eaefb10472f0)
 

### Expected behavior

I expect the client to parse the endpoint properly without ignoring paths in the URL

### Output of `uname -a` or `ver`

Darwin Mazens-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

17.0.8

### Quarkus version or git rev

3.3.0

**Comment by geoand** [comment]
Did this work properly in Quarkus 3.2?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/35503 should fix the issue

**Comment by mazenkhalil** [comment]
> Did this work properly in Quarkus 3.2?

Not sure. I was using otlp exporter before. Now switching to cdi
