### ISSUE TITLE
Automatically add Kotlin stdlib as an index dependency when using quarkus-kotlin extension

### ISSUE THREAD

**Issue by greyhairredbear** [quarkusio/quarkus#35504]
### Description

As already discussed in [this stackoverflow-post](https://stackoverflow.com/questions/76953790/warning-unable-to-register-kotlin-lazy-for-reflection-using-quarkus/76962430#76962430): 

When using Quarkus `3.1.3.Final`, the `quarkus-kotlin` extension and Gradle, the Kotlin stdlib (containing classes like e.g. `Lazy` or `Function1`) is not on the Jandex index. This leads to the following warning on startup, if any of these classes are used:

```
2023-08-22 15:13:28,401 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-4) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
    - kotlin.Lazy (source: <unknown>)
    - kotlin.jvm.functions.Function1 (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

Adding 

```
quarkus.index-dependency.kotlin.group-id=org.jetbrains.kotlin
quarkus.index-dependency.kotlin.artifact-id=kotlin-stdlib
```
to the `application.properties` file fixes that warning. 

It would be nice to have the stdlib automatically added to the Jandex index when using the `quarkus-kotlin` extension to avoid that warning and to have to manually add what I would consider boilerplate to the `application.properties` file

**Comment by geoand** [comment]
What is the warning?

**Comment by greyhairredbear** [comment]
@geoand Sorry, added some information from the referenced post to this issue. Should be understandable without having to view the post now.

**Comment by geoand** [comment]
No problem. Any chance you can give the full hierarchy?

**Comment by greyhairredbear** [comment]
Sorry, missed the `Consider [...]` part of the warning. Added it to the original post. If you're interested in the whole output of the startup: 

```
17:35:20: Executing 'quarkusDev'...

> Task :processResources UP-TO-DATE
> Task :quarkusGenerateCode UP-TO-DATE
> Task :quarkusGenerateCodeDev
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :classes UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :compileQuarkus-test-generated-sourcesKotlin NO-SOURCE
> Task :compileQuarkusTestGeneratedSourcesJava NO-SOURCE
> Task :quarkusGenerateCodeTests
> Task :compileTestKotlin UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :quarkusDev
Listening for transport dt_socket at address: 5005
Press [h] for more options>
Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
2023-08-23 17:35:23,305 INFO  [io.qua.ama.lam.run.MockEventServer] (build-32) Mock Lambda Event Server Started
2023-08-23 17:35:23,690 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-18) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- kotlin.Lazy (source: <unknown>)
	- kotlin.jvm.functions.Function1 (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-08-23 17:35:24,626 INFO  [io.quarkus] (Quarkus Main Thread) optavrp 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.1.3.Final) started in 1.774s. Listening on: http://localhost:8080
2023-08-23 17:35:24,626 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Listening on: http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next
2023-08-23 17:35:24,627 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-08-23 17:35:24,627 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [amazon-lambda, cdi, kotlin, optaplanner, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx, webjars-locator]

```

**Comment by geoand** [comment]
Hm interesting. Can you attach a small sample applicaiton that leads to this behavior? I want to see what causes these types to be including in the attempted reflection registration

**Comment by gsmet** [comment]
If in the end we have to add elements to the index, maybe we should add only the classes that make sense instead of the whole lib (if they are easy to determine).

**Comment by geoand** [comment]
My guess is that we should probably just exclude certain Kotlin classes from hierarchy traversal, but I want to see the sample first

**Comment by greyhairredbear** [comment]
Hi, I've created a sample: https://github.com/greyhairredbear/quarkus-kotlin-stdlib-jandex-sample 

Note: When creating the sample, I first tried to simply use a `lazy`-Block in a `data class` used by `ExampleResource` as an injected property. With this, I couldn't reproduce the warning. However, when using the data class within a `@PlanningEntity` from optaplanner (as I did in the project where the warning first occurred), the warning pops up. 

So it seems to me that `Lazy` is kind of transitively included for reflection registration by optaplanner (if that makes sense?)

**Comment by geoand** [comment]
Hm... the sample doesn't trigger the warning for me

**Comment by greyhairredbear** [comment]
Oh, sorry, seems like something in my git was off (maybe unstaged changes?) - I have the sample on my home laptop, so I'll update the project as soon as I get home

**Comment by geoand** [comment]
Unless I am doing something wrong, I don't see any chance

**Comment by geoand** [comment]
Got it, thanks.
