### ISSUE TITLE
CSRF extension breaks applications due to required config

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#35530]
CSRF, after https://github.com/quarkusio/quarkus/pull/34555 got merged, now requires a config value which should have a default, thus breaking the Quarkus tenet that importing an extension should not break an application by requiring things that have proper defaults.

As such, it breaks every extension user, even if they're not using headers for CSRF, so that's pretty serious.

**Comment by geoand** [comment]
We should definitely have some kind of test for this...

@FroMage are you planning on addressing this issue?

**Comment by sberyozkin** [comment]
@FroMage Can you clarify please ? What exactly is broken ?

**Comment by sberyozkin** [comment]
@FroMage Or yeah, I'll just make it optional

**Comment by sberyozkin** [comment]
@FroMage This is fixed, see the linked PR, I now recall that this property was originally optional and hence I had it configured, then we agreed it should not be optional but I forgot to remove the test configuration which is why I missed that it had no default value...
