### ISSUE TITLE
No serializer found for class org.jboss.resteasy.reactive.client.impl.ClientResponseImp

### ISSUE THREAD

**Issue by Karthikrao121** [quarkusio/quarkus#35536]
### Describe the bug

"java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.jboss.resteasy.reactive.client.impl.ClientResponseImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized\n\tat

### Output of `java -version`

11

**Comment by geoand** [comment]
We'll need a sample application that exhibits the described behavior if we are to look into this.

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by estroem** [comment]
@Karthikrao121 Were you able to figure this out? I'm having the same issue.

**Comment by estroem** [comment]
If anyone comes across this, here's a potential fix. I had some code like this:
```
Response response = // some rest call
return Response.ok().entity(response).build();
```
This tries to return and thus serialize the ClientResponseImpl object, which works in non-native builds, but not in native builds.

Fixed it by changing to this:
```
Response response = // some rest call
return Response.ok().entity(response.getEntity()).build();
```
