### ISSUE TITLE
Integration testing gRPC clients forces port 9001

### ISSUE THREAD

**Issue by Techinica** [quarkusio/quarkus#35559]
### Describe the bug

We currently have a series of integration tests where our gRPC clients are tested using a Test Resource which provides the gRPC server. The resource returns a configuration map including the host and port configuration that the client should use.

I.e.

`    @Override
    public Map<String, String> start() {
        ....
        return Map.of(
                "quarkus.grpc.clients.the-grpc-service.host", "localhost",
                "quarkus.grpc.clients.the-grpc-service.port", "4444");
    }`

As of 3.3.0, we find our tests now fail as the gRPC client is attempting to connect to port 9001 instead of the port provided in the configuration returned by the test resource. Changes to host continue to work as before.
This appears to be due to the change in Channels.java: https://github.com/quarkusio/quarkus/pull/34135/files#diff-b0b8786ccab680283d88d8779d53044d5ea3e610284890ac7350e194be3629ca

At first glance this change appears to assume that the only time a gRPC client would be under integration test within a Quarkus application is when the application itself is providing the gRPC server/service and that it is thus safe to assume the port is that of the local gRPC server.

As of now, it appears our only option is to not integration test our grpc clients and introduce unit test mocks instead.

### Expected behavior

Testing of gRPC clients within a Quarkus application should not assume the port of a local server is the correct port for the client.

### Actual behavior

Integration tests of gRPC clients where the endpoint is not provided by the Quarkus application fail as the port is incorrectly forced to that of the local server.

### How to Reproduce?

Create a QuarkusTest with a suitably implemented QuarkusTestResource that returns grpc client configuration containing a port.
Observe that the port is not used when the channel is created.

### Quarkus version or git rev

3.3.0

**Comment by alesj** [comment]
My (super) quick glance suggest we should just fix `GrpcTestPortUtils.testPort` appropriately ... so it also serves your purpose + keeps the current behavior as well.

**Comment by Techinica** [comment]
> My (super) quick glance suggest we should just fix `GrpcTestPortUtils.testPort` appropriately ... so it also serves your purpose + keeps the current behavior as well.

I'd assume the method would have to also get the GrpcClientConfiguration passed to it then make some sort of decision based on that configuration as to whether the port should be replaced or not. In our case the only thing that sticks out between the GrpcClientConfiguration and the GrpcServerConfiguration is the host (0.0.0.0 vs localhost as set by us), but that really just feels like a hack. This might need a test flag to denote that the replacement shouldn't occur, like a "test-port" on the client configuration that never gets replaced.

**Comment by cescoffier** [comment]
@alesj any update?

**Comment by alesj** [comment]
@cescoffier will have a look asap (probably today) ...

**Comment by alesj** [comment]
I'm thinking of something like this

```
    public static int clientTestPort(String name, GrpcServerConfiguration serverConfiguration) {
        // check if the client port is explicitly set, else check server test port
        Integer port = port("quarkus.grpc.clients." + name + ".port");
        return Objects.requireNonNullElseGet(port, () -> testPort(serverConfiguration));
    }
```

But this also picks-up non-test client port config ... e.g.

```
quarkus.grpc.clients.greeter.port=8888

#%test.quarkus.grpc.clients.greeter.port=8888
```

Where you would probably only want to use this if the %test prop was enabled?
@Techinica ^ ?

**Comment by Techinica** [comment]
@alesj it looks like the change should cover off the issue.

**Comment by rogerwalt** [comment]
I just found out the hard way, that during testing, the port is always set to 9001. It happens here https://github.com/quarkusio/quarkus/blob/25891df7d091fc488710c6a44d3ca6fc78d29751/extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/Channels.java#L125

What is the use of this `LaunchMode.TEST`, why does it overwrite the port?

**Comment by rogerwalt** [comment]
Ok I got it now, it's a concept that makes sense when implementing a server instead of a client: https://quarkus.io/guides/getting-started-testing#controlling-the-test-port. The same is probably done for gRPC (default port 9000, default test-port 9001).

However when you configure a client, this configuration is highly unintuitive. E.g. if you write in your `src/test/ressources/application.properties`:
```
quarkus.grpc.clients.my-client.port=1234 # this is ignored (IMHO wrong)
quarkus.grpc.clients.my-client.test-port=9000 # this is how it has to be done in order to test a grpc client
```

Any opinions?

**Comment by twessling** [comment]
I agree that having a separate config for 'test' in your `application.properties` is wrong; quarkus already supports `application-test.properties` etc for that.  This is btw also related to discussion [#40266](https://github.com/quarkusio/quarkus/discussions/40266).

**Comment by tomazic89** [comment]
> Ok I got it now, it's a concept that makes sense when implementing a server instead of a client: https://quarkus.io/guides/getting-started-testing#controlling-the-test-port. The same is probably done for gRPC (default port 9000, default test-port 9001).
> 
> However when you configure a client, this configuration is highly unintuitive. E.g. if you write in your `src/test/ressources/application.properties`:
> 
> ```
> quarkus.grpc.clients.my-client.port=1234 # this is ignored (IMHO wrong)
> quarkus.grpc.clients.my-client.test-port=9000 # this is how it has to be done in order to test a grpc client
> ```
> 
> Any opinions?

I couldn't agree more. I wasted a full day on this one. I ended up using reflection in tests to replace grpc channel with correctly configured one before I found this `test-port` config is the only thing which can drive the setting under test profile.

**Comment by rogerwalt** [comment]
> > Ok I got it now, it's a concept that makes sense when implementing a server instead of a client: https://quarkus.io/guides/getting-started-testing#controlling-the-test-port. The same is probably done for gRPC (default port 9000, default test-port 9001).
> > However when you configure a client, this configuration is highly unintuitive. E.g. if you write in your `src/test/ressources/application.properties`:
> > ```
> > quarkus.grpc.clients.my-client.port=1234 # this is ignored (IMHO wrong)
> > quarkus.grpc.clients.my-client.test-port=9000 # this is how it has to be done in order to test a grpc client
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any opinions?
> 
> I couldn't agree more. I wasted a full day on this one. I ended up using reflection in tests to replace grpc channel with correctly configured one before I found this `test-port` config is the only thing which can drive the setting under test profile.

Maybe we could use our frustration and at least create a PR to create a warning message to say that the property is ignored?

**Comment by rogerwalt** [comment]
I'm not able to reopen this issue, but provided a PR to fix it. @alesj please review and merge, thanks.
