### ISSUE TITLE
@QuarkusComponentTest seems to not start a new CDI container for each test method

### ISSUE THREAD

**Issue by arnovh** [quarkusio/quarkus#35591]
### Describe the bug

# Bug?

I am testing  a stateful @ApplicationScoped bean with a @QuarkusComponentTest. The 2nd test fails because the ApplicationScoped bean state was changed in the first test. I would assume QuarkusComponentTest would allow each test to be independent.

```
ApplicationScoped
public class InMemoryItemRepo {

  private final static String NOT_FOUND_TMPL = "Item with name %s not found";
  private final static String ALREADY_EXISTS_TMPL =
      "Item with name %s already exists";

  private final ConcurrentHashMap<String, Item> store = new ConcurrentHashMap<>();


  public Item findByName(String name) {
    Item item = (name == null ? null : store.get(name));
    if (item == null) {
      final String msg = String.format(NOT_FOUND_TMPL, name);
      throw new IllegalArgumentException(msg);
    }
    return item;
  }

  public void save(final Item item) {
    Objects.requireNonNull(item);
    if (store.containsKey(item.getName())) {
      final String msg = String.format(ALREADY_EXISTS_TMPL, item.getName());
      throw new IllegalArgumentException(msg);
    }

    store.put(item.getName(), item);
  }

}
```

### Tests

```
@QuarkusComponentTest
@org.junit.jupiter.api.TestInstance(TestInstance.Lifecycle.PER_METHOD)
public class InMemoryItemRepoTest {

  @Inject
  InMemoryItemRepo repo;


  @Test
  void saveShouldPersist() {
    // INITIALIZE : Create a big item and check it does not yet exist in the repo
    final String bigItemName = "big";
    final String bigItemDescription = "big item";
    final Item bigItem = Item.builder().name(bigItemName).description(bigItemDescription).build();
    assertThrows(IllegalArgumentException.class, () -> repo.findByName(bigItemName));

    // EXECUTE : Persist the big item in the repo
    repo.save(bigItem);

    // VALIDATE : find big item back in repo
    final Item retrievedItem = repo.findByName(bigItemName);
    assertThat(retrievedItem, is(bigItem));
  }

  @Test
  void persistExistingNameShouldFail() {
    // INITIALIZE : Create 2 big items and persist one in the repo
    final String bigItemName = "big";
    final Item bigItem1 = Item.builder().name(bigItemName).description("First big item").build();
    final Item bigItem2 = Item.builder().name(bigItemName).description("Second big item").build();
    repo.save(bigItem1);

    // EXECUTE : Also attempt to persist the second big item in he repo
    Exception exception = assertThrows(IllegalArgumentException.class, () -> repo.save(bigItem2));

    // VALIDATE : Expect second attempt failed.
    assertThat(exception.getMessage(), is("Item with name big already exists"));
  }
}

```

### Expected behavior

I expect that individual tests in a class annotated with @QuarkusComponentTest to be independent, and not share the same instance of the application scoped bean under test (@Inject-ed). 

### Actual behavior

The 2nd test fails on  repo.save(bigItem1) because an item with the same name was persisted in the first test. This can be avoided by using different item names in the second test,  still I wonder if component tests should not provide the possibility to have a clean sheet for each method, e.g. restart the container between each method.

### How to Reproduce?

Reproducer:  https://github.com/arnovh/component-test-restart-issue

Steps to reproduce:  mvn test

### Output of `uname -a` or `ver`

6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

17 (Temurin-17+35)

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

# Inconsistent documentation?

https://quarkus.io/guides/getting-started-testing#testing-components seems to say 2 conflicting things:

- "So what exactly does the QuarkusComponentTest do? It starts the CDI container and registers a dedicated [configuration object](https://quarkus.io/guides/config-reference) during the before all test phase. The container is stopped and the config is released during the after all test phase."

And later behind the info icon:

- "By default, a new test instance is created for each test method. Therefore, a new CDI container is started for each test method."

I am looking for the latter behavior, but the actual behavior seems to be the one in the first desciption.

If the behavior that I experienced is considered correct, I think it would be useful to add a (configuration) option to also allow cdi restarts for each test (method).

**Comment by mkouba** [comment]
I can confirm that the documentation is inconsistent. And TBH I'm not quite sure if the note about `@TestInstance` is just a leftover from one of the design iterations or if it's intentional and therefore there's a bug...

**Comment by Ladicek** [comment]
> By default, a new test instance is created for each test method. Therefore, a new CDI container is started for each test method.

The 2nd sentence is incorrect. It does _not_ follow from the first that the CDI container is started for each test method. The lifecycle of the test instance is completely independent from the lifecycle of the CDI container.

The CDI container must always live at least as long as all the objects it manages. For `TestInstance.PER_CLASS`, the CDI container must also be "per class". For `TestInstance.PER_METHOD`, I guess it would be possible for the CDI container to also be "per method", but I didn't give it much thought frankly.

**Comment by mkouba** [comment]
> I guess it would be possible for the CDI container to also be "per method", but I didn't give it much thought frankly.

We can explore this further but for now I think that we should fix the docs to follow the current behavior, i.e. the CDI container is started per test class. BTW I wonder if it's guaranteed that all test methods of a test class are executed sequentially in one batch (even if `TestInstance.Lifecycle.PER_METHOD` is used). If not then we have a problem...

**Comment by Ladicek** [comment]
> we should fix the docs to follow the current behavior

Agree.

> I wonder if it's guaranteed that all test methods of a test class are executed sequentially in one batch (even if `TestInstance.Lifecycle.PER_METHOD` is used). If not then we have a problem...

I'm not sure if there are any guarantees, but I feel this should be a fairly safe assumption to make.

**Comment by arnovh** [comment]
Typically tests should not rely on order: https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-methods

So when CDI is not restarted bweteen  stateful bean tests this would require:
(1)  attempt to undo the state changes after each test, OR
(2) ensure the tests do not conflict on the state changes (e.g. use different names in the example)

This is why I think restarting CDI between tests would be the right solution, because this takes away these restrictions/efforts.

**Comment by mkouba** [comment]
> Typically tests should not rely on order: https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-methods
> 
> So when CDI is not restarted bweteen stateful bean tests this would require: (1) attempt to undo the state changes after each test, OR (2) ensure the tests do not conflict on the state changes (e.g. use different names in the example)
> 
> This is why I think restarting CDI between tests would be the right solution, because this takes away these restrictions/efforts.

Well, I was not talking about ordering of methods within a test class, I was not sure whether it's guaranteed that all methods from a test class are executed in one "group". For example, if there's a test class `Foo` with methods `Foo.a()` and `Foo.b()` and a test class `Bar` with method `Bar.a()` - is it guaranteed that `Bar.a()` will never be executed between `Foo.a()` and `Foo.b()`?

And from what I read about the `MethodOrderer` and `ClassOrderer` it seems to be the case...

**Comment by Ladicek** [comment]
> Typically tests should not rely on order: https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-methods

That link also tells that order is sometimes important, for example when navigating through a state space of a stateful component :-) And as I mentioned above, we _must not_ restart the CDI container between test methods in case of `Lifecycle.PER_CLASS`.

As a workaround, I think it should be possible to destroy the bean instance e.g. in `@AfterEach`. Then, a subsequent lookup (or injection) will create a fresh new instance.

**Comment by mkouba** [comment]
> As a workaround, I think it should be possible to destroy the bean instance e.g. in `@AfterEach`. Then, a subsequent lookup (or injection) will create a fresh new instance.

Yes, and you can even use `Arc.container().getActiveContext(ApplicationScoped.class).destroy()` to destroy all existing instances.

**Comment by arnovh** [comment]
In my opinion  restart/destroy between methods would be the safest behavior when TestInstance.Lifecycle.PER_METHOD is configured (which is the default). Perhaps as indicated above this can be explored further in the future, for example via an argument of @QuarkusComponentTest.

For now, thanks for providing me the workarounds, I have tried `Arc.container().getActiveContext(ApplicationScoped.class).destroy()`
 and it works in @BeforeEach.

**Comment by siewp** [comment]
@mkouba Could you also remove the note in your blog post? https://quarkus.io/blog/quarkus-component-test/
Otherwise, there is still inconsistency 😅

**Comment by mkouba** [comment]
> @mkouba Could you also remove the note in your blog post? https://quarkus.io/blog/quarkus-component-test/ Otherwise, there is still inconsistency 😅

Good point!

**Comment by mkouba** [comment]
FTR the behavior of a `QuarkusComponentTest` changed in quarkus 3.5 (and is determined from the `TestInstance#value()`; see https://github.com/quarkusio/quarkus/pull/35768 for more details).
