### ISSUE TITLE
Openshift deployment config properties all start with `get-`/`is-`

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#35594]
### Describe the bug

In the documentation at least, it seems config properties are broken, as they all start with `get-`/`is-`:

See screenshot from the documentation of the main branch:

![image](https://github.com/quarkusio/quarkus/assets/412878/9d5267ea-fe37-46d7-839d-c05f3814a7f6)

Branch 3.3 seems affected as well, not sure about 3.2. 2.x isn't affected for sure.

I'm not sure whether this is just a documentation problem, or if configuration properties are actually broken.

### Expected behavior

No weird `get-`/`is-` prefixes.

### Actual behavior

Weird `get-`/`is-` prefixes.

**Comment by gsmet** [comment]
@radcortez that's probably another one for you?

**Comment by gsmet** [comment]
The particularity of this config is that there are getters in it. And that might conflict with the detecting of the new `@ConfigMapping` stuff.

I'll have a look to see if I can figure out how to work around it.

**Comment by yrodiere** [comment]
Note this seems to impact other, related extensions, e.g. the Kubernetes one: https://quarkus.io/guides/deploying-to-kubernetes#quarkus-kubernetes-kubernetes-config_quarkus.kubernetes.get-env.secrets

**Comment by gsmet** [comment]
Yeah, I noticed that.
