### ISSUE TITLE
Add a @Generated annotation on all generated code

### ISSUE THREAD

**Issue by michaeldimchuk** [quarkusio/quarkus#35601]
### Description

By default, coverage tools like Jacoco use the presence of a `@Generated` annotation to detect whether code has been generated or not, and skip coverage checks / requirements for that code. Here's the specific snippet where that happens: https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilter.java#L51.

When generating extension processor accessor classes (like `FruitExtensionProcessor$$accessor`, the class doesn't have a `@Generated` annotation on it, so Jacoco considers it a target for coverage checks. This is a bit inconvenient because when running Jacoco with coverage enforcement, it breaks builds unless that code is covered, which leads to redundant tests that for example check whether the instance returned by `construct` really is a `FruitExtensionProcessor`.

Other annotation processors like lombok allow for a `@Generated` annotation to be added to any generated bytecode, so would be helpful if Quarkus did so as well.

### Implementation ideas

Looking at the [code in Jacoco](https://github.com/jacoco/jacoco/blob/master/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilter.java#L51), it doesn't really care about the package, just as long as the annotation has the word "Generated" in it. To that end, can either use the [Jakarta annotation](https://jakarta.ee/specifications/annotations/2.0/apidocs/jakarta.annotation/jakarta/annotation/generated), or create one specifically for Quarkus.

**Comment by geoand** [comment]
I actually prefer #35602. Mind giving it a try?

**Comment by geoand** [comment]
I'll have a look tomorrow.

I threw this one together on the go

**Comment by cescoffier** [comment]
There is already a @Generated annotation specific to Quarkus for gRPC as the one used by gRPC Java was still using javax.

**Comment by geoand** [comment]
Right, but we can't really use it as is, we'd have to move it to the core.

**Comment by cescoffier** [comment]
Yes, it would need to be moved, and the gRPC magic trick updated if we want to have our own annotation.

**Comment by geoand** [comment]
I'll have a quick lool

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/35629 is it
