### ISSUE TITLE
Native Build Cannot Be Ran on OCP with error "exec ./application: exec format error"

### ISSUE THREAD

**Issue by chengkuangan** [quarkusio/quarkus#35612]
### Describe the bug

Create a simple Quarkus service and tried to deploy as Native apps to OCP but the POD failed to start with the above mention error.

### Expected behavior

The build native mode container should be able to run on OCP.

### Actual behavior

POD failed to start with the following error:
`exec ./application: exec format error`

### How to Reproduce?

1. Refers the sample codes [here](https://github.com/chengkuangan/hello-service)
2. Do a native build using the following command:
```quarkus build --native --no-tests -Dquarkus.native.container-build=true```
4. The output of the `runner` file shows `arm` architecture. 
```%> file target/hello-service-1.0.0-SNAPSHOT-runner
target/hello-service-1.0.0-SNAPSHOT-runner: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=881de1a5ab48d0f7c4202c64c0628247d53def8a, not stripped
```
> Note: I am not sure this should the correct architecture for OCP. I assume it should me `amd64`

5. Deploy using the provide YAML file.
```
oc apply -f yaml/hello.yaml
```
7. Pod failed to start with the following error:
```
exec ./application: exec format error
```

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 17.0.4, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home Default locale: en_MY, platform encoding: UTF-8 OS name: "mac os x", version: "13.5", arch: "aarch64", family: "mac"

### Additional information

1. Tried with `mvn clean package -DskipTests=true -Pnative -Dquarkus.kubernetes.deploy=true` with same problem, with `quarkus.native.container-build=true` uncomment in `application.properties`
2. I am using Mac M1
3. I am using rhpds/demo environment with the 'OCP 4.12.28' workshop environment.

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
When building a native executable from an M1, you get:

- if you use a local graalvm installation => an MacOS/ARM64 executable
- if you use an in-container build => A Linux/ARM64 executable

Your OpenShift runs on x86, so cannot execute these containers.

Your only hope is to use x86 emulation:

```
quarkus.native.container-runtime-options=--platform=linux/amd64
```

It only works with Docker Desktop (on Mac), so no podman. 
Also, I hope you like coffee.... because it will take ages.... without any guarantee
