### ISSUE TITLE
Quarkus 3.2: Hibernate ORM configuration problem #2

### ISSUE THREAD

**Issue by krisztiankocsis** [quarkusio/quarkus#35631]
### Describe the bug

I'm upgrading to Quarkus 3.2 from 2.x (lates) and I need to add one new config property:

quarkus.hibernate-orm.mydatasource.quote-identifiers.strategy=all

When I try to build the app with Maven package goal I'm gettting this error:

SRCFG00014: The config property quarkus.hibernate-orm.mydatasource.mapping.query.query-plan-cache-max-size is required but it could not be found in any config source

Its probably the same as https://github.com/quarkusio/quarkus/issues/34628 which is fixed now.

### Expected behavior

The configuration entry is properly accepted.

### Actual behavior

Breaks the build.

### Output of `java -version`

17

### Quarkus version or git rev

3.2.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

**Comment by yrodiere** [comment]
Thanks for the report. Yes, it seems like #34655 missed a few problematic `@ConfigItem`s. I'll send a PR shortly.
