### ISSUE TITLE
Extends ServerInterceptor not working

### ISSUE THREAD

**Issue by renyijiu** [quarkusio/quarkus#35634]
### Describe the bug

1. define an `interface`:
```java
public interface GrpcInterceptor extends ServerInterceptor, Prioritized {
  Integer TRACE_INTERCEPTOR_ORDER = 10000;
  Integer ACTIVITY_INTERCEPTOR_ORDER = 9999;
}
```

2. implements the GrpcInterceptor
```java
@ApplicationScoped
@GlobalInterceptor
public class ServerInterceptors implements GrpcInterceptor {

    private final Logger logger;

    @Inject
    public ServerInterceptors(Logger logger) {
        this.logger = logger;
    }

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        Context context = Context.current();

        String orgId = headers.get(ORG_ID_METADATA);
        logger.infof("orgId: %s", orgId);

        if (!StringUtils.isBlank(orgId)) {
            context = context.withValue(ORG_ID_CONTEXT, orgId);
        }
        return Contexts.interceptCall(context, call, headers, next);
    }

    @Override
    public int getPriority() {
        return 0;
    }
}

```

4. test with send a request, and the GrpcInterceptor not working

### Expected behavior

`GrpcInterceptor` class should work, can print the `orgId`

### Actual behavior

`GrpcInterceptor` class not working, no related methods are called

### How to Reproduce?

A demo that reproduces the problem, https://github.com/renyijiu/quarkus-jooq-issue-demo/tree/bugs/interceptors

### Output of `uname -a` or `ver`

Darwin renyijiacStudio.localdomain 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 LTS OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

### Additional information

the code can work in 3.2.5.Final, but failed in 3.3.1, i wonder if I'm overlooking some incompatible update message ?

**Comment by renyijiu** [comment]
Test cases still fail in version 3.3.2

**Comment by alesj** [comment]
I guess you see something like this?

`
2023-09-11 16:29:54,393 WARN  [io.qua.grp.dep.GrpcServerProcessor] (build-84) At least one unused gRPC interceptor found: com.alesj.qcl.app.ServerInterceptors. If there are meant to be used globally, annotate them with @GlobalInterceptor.
`

**Comment by renyijiu** [comment]
> I guess you see something like this?
> 
> `2023-09-11 16:29:54,393 WARN [io.qua.grp.dep.GrpcServerProcessor] (build-84) At least one unused gRPC interceptor found: com.alesj.qcl.app.ServerInterceptors. If there are meant to be used globally, annotate them with @GlobalInterceptor.`

Yes, there is indeed this line of warn logging, but the code has been annotated with `@GlobalInterceptor`，https://github.com/renyijiu/quarkus-jooq-issue-demo/blob/0c9bacac3ae8d617100ac487b7f8d11ca2b308fe/src/main/java/org/acme/ServerInterceptors.java#L13
