### ISSUE TITLE
Duplicate dependencies netty-all and split netty artifacts

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3563]
This gives us warnings like:

> [WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Dependencies with duplicate files detected. The dependencies [io.netty:netty-codec-socks::jar:4.1.34.Final(compile), io.netty:netty-all::jar:4.1.34.Final(compile)] contain duplicate files, e.g. io/netty/handler/codec/socks/SocksMessage.class

We should either use netty-all or the split artifacts but definitely not both.

**Comment by gsmet** [comment]
Typically, we have this warning when building:

```
INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ quarkus-integration-test-elytron-security-oauth2 ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 606ms
```

**Comment by gsmet** [comment]
`netty-all` is coming from `quarkus-http-core` whereas the Vert.x layer depends on the separate Netty components.

It needs to be fixed before the next release.

**Comment by geoand** [comment]
@gsmet I opened https://github.com/quarkusio/quarkus-http/pull/3 which should fix this issue

**Comment by gsmet** [comment]
I think we also need to ban the `netty-all` dependency from Quarkus. We already have a list of banned dependencies.

**Comment by gsmet** [comment]
Note that this ban should be a draft PR for now as we will need to upgrade `quarkus-http` first.

**Comment by geoand** [comment]
Sure thing, I'll add it

**Comment by geoand** [comment]
Draft [PR](https://github.com/quarkusio/quarkus/pull/3635) opened.

**Comment by stuartwdouglas** [comment]
This should be resolved in Alpha3
