### ISSUE TITLE
Knative deployment is broken using OpenShift extension in v3.3.0 and v.3.3.1

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#35647]
### Describe the bug

After a new project on v3.3.0 or v.3.3.1 is created with an openshift extension, the app is deployed to the OpenShift serverless. But the Quarkus serverless app never came up with the following issue:

<img width="913" alt="image" src="https://github.com/quarkusio/quarkus/assets/14066977/034d5085-51b7-4f82-8b0a-967004172054">

Knative service has an error:
<img width="1372" alt="image" src="https://github.com/quarkusio/quarkus/assets/14066977/1d80f897-21ec-41d3-8f4c-99da90c0a166">

When I created a new project based on v3.2.4.Final, it works well.

### Expected behavior

Quarkus app should run as a knative service.

### Actual behavior

The revision status is "ContainerMissing"

<img width="1372" alt="image" src="https://github.com/quarkusio/quarkus/assets/14066977/3991b600-3076-42b3-8eeb-430418461009">

### How to Reproduce?

1. quarkus create kube-native-java 
2. quarkus ext add openshift
3. Update the application.properties
quarkus.container-image.group={YOUR_PROJECT_NAME}
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=knative
quarkus.kubernetes.deploy=true
quarkus.openshift.build-strategy=docker
4. quarkus build --no-test

Be sure to install OpenShift serverless in your OpenShift cluster.

### Output of `uname -a` or `ver`

Darwin doh-mac 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

3.3.0 and 3.3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by geoand** [comment]
@iocanel has something changed in this areas in 3.3?

**Comment by iocanel** [comment]
There are some changes related to image building / handling in open shift.

I will take a look.

**Comment by danieloh30** [comment]
Thanks @iocanel

**Comment by iocanel** [comment]
I managed to reproduce the issue.
It seems that a push secret is wrongly set to the build configuration.

**Comment by iocanel** [comment]
I'll create a PR shortly.
