### ISSUE TITLE
Bump Wiremock to 3.0.0

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#35648]
### Description

New major version of Wiremock ([v3.0.0](https://github.com/wiremock/wiremock/releases/tag/3.0.0)) has been released.

The group ID and artifact ID are changed from:

> com.github.tomakehurst:wiremock-jre8
> com.github.tomakehurst:wiremock-jre8-standalone

to:

> org.wiremock:wiremock
> org.wiremock:wiremock-standalone

**Comment by geoand** [comment]
@Eng-Fouad would you like to open a PR to address this?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad would you like to open a PR to address this?

#35649
