### ISSUE TITLE
Setting quarkus.opentelemetry.resource-attributes is no longer supported in 3.2+

### ISSUE THREAD

**Issue by millerjp** [quarkusio/quarkus#35640]
### Describe the bug

In previous versions we could set this property quarkus.opentelemetry.resource-attributes to pass in attributes to our traces eg resource-attributes: "service.name=${QUARKUS_APPLICATION_NAME},service.namespace=${OPTEL_SERVICE_NAMESPACE},service.instance.id=${OPTEL_SERVICE_INSTANCE_ID},service.version=${OPTEL_SERVICE_VERSION}"

### Expected behavior

Be able to set these values dynamically as in previous versions

### Actual behavior

This is no longer possible and the values are not configurable

**Comment by mederel** [comment]
I think it is still working with a new name after the OpenTelemetry property renaming: `quarkus.otel.resource.attributes`, isn't it?
