### ISSUE TITLE
Add META-INF/io.netty.versions.properties to the uberJar ignore list

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3565]
> [WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Duplicate entry META-INF/io.netty.versions.properties entry from io.netty:netty-handler::jar:4.1.34.Final(compile) will be ignored. Existing file was provided by io.netty:netty-codec::jar:4.1.34.Final(compile)
> [WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Duplicate entry META-INF/io.netty.versions.properties entry from io.netty:netty-common::jar:4.1.34.Final(compile) will be ignored. Existing file was provided by io.netty:netty-codec::jar:4.1.34.Final(compile)
> [WARNING] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Duplicate entry META-INF/io.netty.versions.properties entry from io.netty:netty-transport::jar:4.1.34.Final(compile) will be ignored. Existing file was provided by io.netty:netty-codec::jar:4.1.34.Final(compile)

**Comment by gwenneg** [comment]
Do you need some help to submit a PR or are you already on it?

**Comment by gsmet** [comment]
Feel free to take a stab at it, I'm just collecting the issues right now.
