### ISSUE TITLE
Gradle not enabling http in native image

### ISSUE THREAD

**Issue by msmsimondean** [quarkusio/quarkus#3566]
**Describe the bug**
When using Gradle to build a native image for an AWS Lambda function, it does not enable the `http` protocol in the native image

**Expected behavior**
Native image runs successfully executes.  

**Actual behavior**
The following exception is thrown when the native image starts: 

```bash
2019-08-19 11:20:04 Mounting /private/var/folders/hn/ljd7mlxs60d6yvwbgchbm7dw2pf5my/T/tmptetu_nar as /var/task:ro,delegated inside runtime container
Exception in thread "Lambda Thread" com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the -H:EnableURLProtocols=http option to the native-image command.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:196)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:157)
	at java.net.URL.getURLStreamHandler(URL.java:62)
	at java.net.URL.<init>(URL.java:599)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaApi.invocationNext(AmazonLambdaApi.java:31)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:56)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-08-19 11:20:25 Function 'QuarkusLambda' timed out after 20 seconds
```

**To Reproduce**
1. $ git clone https://github.com/msmsimondean/quarkus-demo-apps.git
2. $ cd quarkus-demo-apps/amazon-labmda
3. $ ./gradlew buildNative --docker-build=true
4. $ ./gradlew buildZip
4. $ echo '{"firstName":"James", "lastName": "Lipton"}' | sam local invoke QuarkusLambda 

**Configuration**

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin machinename 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_222"
    OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
    OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
 - GraalVM version (if different from Java): 19.1.1
 - Quarkus version or git rev: 0.20.0

**Additional context**

**Comment by gwenneg** [comment]
Could you run the build again with `./gradlew buildNative --docker-build=true --enable-http-url-handler=true`?

**Comment by msmsimondean** [comment]
@gwenneg that worked!  I had to pass it without the `=enabled` though as it complained that `Command-line option '--enable-http-url-handler' does not take an argument`

**Comment by gwenneg** [comment]
Great! Sorry about the argument thing, I forgot it was not required for boolean Gradle options :)

Can I consider this issue fixed and close it?

**Comment by gsmet** [comment]
I don't know. I wonder if the sample project shouldn't include it, considering we do include it in the Maven project.

**Comment by gwenneg** [comment]
@gsmet Which project exactly? I don't see any quickstarts project or guide about Amazon Lambda.

**Comment by gsmet** [comment]
Don't we have something to create a Gradle project?

**Comment by msmsimondean** [comment]
The Maven plugin automatically enables HTTP.  The Gradle plugin doesn't.  

@evanchooly has an example project for the Amazon Lambda extension at https://github.com/evanchooly/quarkus-demo-apps/tree/master/amazon-lambda that uses Maven.  In his codebase he doesn't have to explicility enable HTTP as Maven is doing it implicitly.  When I ported this example codebase to use Gradle, I found that Gradle doesn't enable HTTP be default.

**Comment by msmsimondean** [comment]
It would be great if there was a guide for the Amazon Lambda extension.  It took quite a few hours to work out how to create a new codebase using the extension without the help of a guide.

**Comment by gsmet** [comment]
Sorry, I'm talking about initializing a bare Gradle project.

We have this in the Maven basic-rest template: https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/resources/templates/basic-rest/java/pom.xml-template.ftl#L99 . Was wondering if we should have the same in the Gradle one.

But TBH, I'm not even sure we have a Gradle template and a Gradle project creation tool.

**Comment by msmsimondean** [comment]
@gsmet it's all making sense now.  I notice the demo app includes the same setting in its Maven pom.xml: https://github.com/evanchooly/quarkus-demo-apps/blob/master/amazon-lambda/pom.xml#L127

**Comment by evanchooly** [comment]
@msmsimondean Those docs are coming.  the underlying mechanics of the extension are being reworked and so the configuration and usage might change.  I'm waiting on those aspects to stabilize a bit hopefully in the next month or so.

**Comment by gsmet** [comment]
Including the HTTP URL handler is now the default in the native image building process so I think this one is fixed.

**Comment by msmsimondean** [comment]
@gsmet the issue seems to still be occurring.  I'm using Quarkus `1.2.1.Final`
