### ISSUE TITLE
Surge.sh deployment fails with  `Aborted - Unable to publish. Application too large`

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#35660]
### Description

Previewing the documentation is failing in surge.sh with the following error:

   Aborted - Unable to publish. Application too large

### Implementation ideas

Move to another hosting provider?

**Comment by geoand** [comment]
Too large? Do we know any more details?

**Comment by gastaldi** [comment]
Surge has an upload limit of 400Mb if I am not mistaken and the generated docs are above this limit. Haven't investigated what caused it, but I wonder if we're not building multiple Quarkus versions in the preview?

**Comment by geoand** [comment]
I have no idea

**Comment by gsmet** [comment]
The idea of https://github.com/quarkusio/quarkus/pull/35752 was to fix this.

Let me know if it happens again in a properly rebased PR.

**Comment by gastaldi** [comment]
Let's close it now and revisit if that happens again
