### ISSUE TITLE
GraalVM 24.0/23.1: JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded fails

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#35676]
### Describe the bug

With a latest Graal master (24.0, possibly also 23.1 build) the `JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded` integration test in native fails, no longer finding `TransformerFactory` in the report. I haven't looked into the details yet.

```
Error:  io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJDKXMLParsersAreIncluded -- Time elapsed: 0.179 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'javax.xml.transform.TransformerFactory' was not found in the report in target/quarkus-integration-test-jpa-postgresql-withxml-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-withxml-999-SNAPSHOT-runner_20230901_021852.txt
```

See:
https://github.com/graalvm/mandrel/actions/runs/6044323984/job/16403307103#step:12:713

**Comment by jerboaa** [comment]
Reproduced locally. Seems like the instantiation fails with an error?

```
$ grep -n TransformerFactory reports/used_classes_quarkus-integration-test-jpa-postgresql-withxml-999-SNAPSHOT-runner_20230904_180113.txt
1165:com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
6794:javax.xml.transform.TransformerFactoryConfigurationError
```

/cc @Sanne Any pointers perhaps?

**Comment by jerboaa** [comment]
Is this known to work with JDK 21?

**Comment by zakkak** [comment]
The test passes in JVM mode with JDK 21, so it looks like a native image issue.

Tested with:

```
./mvnw -pl integration-tests/jpa-postgresql-withxml -Dtest-containers -Dstart-containers -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean verify
```

**Comment by jerboaa** [comment]
@zakkak Feel free to debug this on the native side. It looks like I won't be able to before Friday or so.

**Comment by zakkak** [comment]
The test fails here

**Comment by Sanne** [comment]
It's possible that my relatively old assertion is a bit fragile, the JDK might have made some improvements in this area
(I didn't check though, sorry I'm away).

Feel free to adapt the test: the purpose was primarily to detect the XML parser would be included in this scenario, as opposed to the other test which verifies that it gets excluded when we don't need it.

**Comment by zakkak** [comment]
Interestingly, despite `javax.xml.transform.TransformerFactory` not appearing in the  used classes report, when compiling with debug symbols generation enabled the said class is present in the debug info, as is its `newInstance` method. :eyes:

**Comment by zakkak** [comment]
Apparently `newInstance` is pretty  trivial and is getting inlined.

```
    public static TransformerFactory newInstance()
        throws TransformerFactoryConfigurationError {

        return FactoryFinder.find(
            /* The default property name according to the JAXP spec */
            TransformerFactory.class,
            /* The fallback implementation class name, XSLTC */
            "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
    }
```

Passing `-H:-InlineBeforeAnalysis` makes the test pass again. 

I suggest checking for `com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl` instead of `javax.xml.transform.TransformerFactory`. WDYT?
