### ISSUE TITLE
security-jpa: Wrong password passed to custom password provider

### ISSUE THREAD

**Issue by chrkoelle** [quarkusio/quarkus#35671]
### Describe the bug

I'm trying to get basic auth with jakarta persistence to work with a quarkus REST service. I followed the instructions on https://quarkus.io/guides/security-basic-authentication-tutorial but found a not expected behaviour with a custom password provider.

Here's the relevant code:
`
  @Entity
  @Table(name = "pwd_table")
  @UserDefinition 
  public class LoginUser {

    @Id
    @Column(name = "USERID")
    public Long userid;
    
    @Column(name = "USERNAME")
    @Username
    public String username;

    @Column(name = "PWD_CRYPT")
    @Password(value = PasswordType.CUSTOM, provider = CustomPasswordProvider.class)
    public String password;
    
    @Roles
    public String roles;
    
  }
`

`
 public class CustomPasswordProvider implements PasswordProvider {
    
    public CustomPasswordProvider() {
        
    }
    
    @Override
    public org.wildfly.security.password.Password getPassword(String pass) {
        byte[] digest = MyHash.hash(pass) // simplified code, we use SCrypt here...
        return SimpleDigestPassword.createRaw("myhash", digest);
    }
}
`

`
@GET
@RolesAllowed("backoffice")
@Path("/{myId}")
@Produces(MediaType.APPLICATION_XML)
public Response getXML(@PathParam("myId") String myId) {
...
}
`

### Expected behavior

My expectation is that the password provided in the header of the http request is passed to the getPassword method in the PasswordProvider class in order to hash this clear text password and compare it then to the hashed password that is stored in the database for the authentication process.

### Actual behavior

What happens is the the hashed password from the database is passed to the PasswordProvider and is hashed again there which makes no sense. The authentication fails of course (401 Unauthorized).

### Output of `uname -a` or `ver`

Linux pcck1 6.4.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9-ea" 2023-10-17 OpenJDK Runtime Environment (build 17.0.9-ea+4-Debian-1) OpenJDK 64-Bit Server VM (build 17.0.9-ea+4-Debian-1, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by sberyozkin** [comment]
H @chrkoelle Thank you for opening this issue, I agree it is confusing and I opened a PR, #35682, to clarify the use of `PasswordProvider`.

@FroMage has explained to me. My initial quick comment was that this provider must return the original password, which did not make sense, though given your description that the hashed password is passed, I vaguely assumed that somehow it was possible - for example, this provider knows about the original password and compares it against the hashed value and then returns the clear text one. 
@FroMage explained that the only purpose of this provider is to return a password representation as `Password`, which will inform/help the runtime to apply the correct hashing algorithm to the incoming user secret. The runtime remains in control as far as doing the actual comparison/hashing of the incoming secret.

Thanks
