### ISSUE TITLE
Let the users control CORS Preflight requests from their JAX-RS code

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#3568]
**Description**
Right now the preflight request is controlled from the filter only.

**Implementation ideas**
Add a @Preflight annotation:
```
@Options
@Preflight
pubic Response getOptions() {
}
```
This might require the Quarkus CORS filter have a configuration option instructing it to skip processing the preflights if the users know their code will do it and/or some build processing step to check this annotation for the CORS filter to notice that for a given request path a user preflight handler is available

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, what do you think of this one ? (JAX-RS applications can have Options methods in general)

**Comment by geoand** [comment]
@sberyozkin what exactly are you looking to see here?

Asking because if there is something to be done to improve the user experience, we can certainly add it to RESTEasy Reactive

**Comment by stuartwdouglas** [comment]
There is already `javax.ws.rs.OPTIONS`. It sounds like all we need is the ability to stop the filter handling options requests?

**Comment by sberyozkin** [comment]
I'm going to close it as I'm afraid that if we'll let the custom code handle preflight requests then it can cause some  unexpected side-effects. So far we haven't had a single request to support custom preflight management
