### ISSUE TITLE
Confusing documentation or behaviour for `quarkus.test.profile.tags`

### ISSUE THREAD

**Issue by FWest98** [quarkusio/quarkus#35693]
### Describe the bug

The [configurations options page](https://quarkus.io/guides/all-config#quarkus-core_quarkus.test.profile.tags) mentions that `quarkus.test.profile.tags` controls which tests will be run or not. It also mentions an environment variable name that can be used to set this value. This seems to suggest that this value can be controlled in any of the "standard" ways configuration is handled in Quarkus: through yaml files, environment variables, etc.

However, it turns out that this value is _only_ read from the system properties directly ([source](https://github.com/quarkusio/quarkus/blob/00ebf1241cecf251790c3e1142cf362cf9b5e014/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L1193)), and thus setting this value through an environment variable does not work. Additionally, for some reason, using `-Dquarkus.test.profile.tags=xyz` in my `gradle test` command also does not seem to pass this property on after the fork. So for me, the only reason to set this field now it by hardcoding it in the Gradle task configuration as outlined [here](https://quarkus.io/guides/gradle-tooling#custom-test-configuration-profile). This seems very limited and is quite inconvenient.

### Expected behavior

Ideally, based on the documentation, I would expect this configuration to work through all normal Quarkus config options. However, if that is not possible (due to startup dependencies - I can imagine), then at the very least I would expect the documentation to be more explicit about this. Ideally, then, the respective gradle property should be passed on to the test runtime JVM as well, to ease the use of this setting.

### Output of `java -version`

openjdk version "17.0.8.1"

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by edufolly** [comment]
I went through the same problem. I completely agree with what was said by @FWest98.

**Comment by gsmet** [comment]
@radcortez could you clarify this one?

**Comment by radcortez** [comment]
Relates to https://github.com/quarkusio/quarkus/issues/10233.

**Comment by radcortez** [comment]
Observing https://bugs.openjdk.org/browse/JDK-8276651 with some prototypes. Updating the JDK got rid of the issue.

**Comment by geoand** [comment]
> I see no impediment other than extra work during the test initialization. @geoand, you implemented this. Do you know any reason not to?

Yeah, that should work

**Comment by LarsSven** [comment]
I've just ran into the exact same issue where I would like to set profile tags in the config, but it just did not work. It would be really nice if the config actually listened to this.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
I had an initial proposal in https://github.com/quarkusio/quarkus/pull/42715, but that obviously didn't work. I believe that https://github.com/quarkusio/quarkus/pull/42157 should help get this right. I'll have a look.
