### ISSUE TITLE
Continuous call on /q/dev-ui/json-rpc-ws with quarkusRun

### ISSUE THREAD

**Issue by evachon** [quarkusio/quarkus#35691]
### Describe the bug

Call to /q/dev-ui/json-rpc-ws are done continuously when running the app in prod.

### Expected behavior

When the app is run in prod mode no call to the dev-ui should be done.

### How to Reproduce?

Dependencies:

```
    implementation 'io.quarkus:quarkus-rest-client-reactive-jackson:2.16.4.Final'
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson:2.16.4.Final'
```

Simple way to reproduce:

```
import io.smallrye.mutiny.Uni;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.core.Response;
import org.jboss.resteasy.reactive.RestResponse;
import org.jboss.resteasy.reactive.server.ServerExceptionMapper;

public class ExceptionMapper {

	@ServerExceptionMapper
	public Uni<RestResponse> mapProcessingException(Throwable exception,
			ContainerRequestContext requestContext) {
		System.out.println(requestContext.getUriInfo().getAbsolutePath().getPath());
		return Uni.createFrom().item(RestResponse.status(Response.Status.NOT_FOUND, "An exception" ));
	}
}
```

```
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class Hello {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }
}
```

```
./gradlew quarkusBuild
./gradlew quarkusRun
```

**Comment by phillip-kruger** [comment]
Hi @evachon 

Thanks for the issue reported. The only way I could recreate it is as follows:

1) Start the app in dev mode (quarkusDev)
2) Open the Dev UI (localhost:8080/q/dev-ui)
3) Stop the app that is running in dev mode
4) Start the app in prod mode (quarkusRun)

If the browser is still open (with the Dev UI) the Dev UI will try and reconnect (making calls to (/q/dev-ui/json-rpc-ws) .
Refreshing or closing the browser will stop that.

Is this what you are seeing ? If not can you provide more details on how to recreate the issue ?

Thanks

**Comment by evachon** [comment]
Hi @phillip-kruger 

Thanks you for your quick response.

Your are right about the cause of my problem. 

I was testing the prod release after some changes where I used the Dev UI and never tough about closing it.

Thanks again.
