### ISSUE TITLE
Grpc Server support unix domain socket

### ISSUE THREAD

**Issue by liangyuanpeng** [quarkusio/quarkus#35707]
### Description

I want to use grpc server work with unix domain socket and have not found any doc for it, so just create i feature request issue.

Remind me if i missed something,thanks!

**Comment by cescoffier** [comment]
If you use the new gRPC server, and configure the HTTP server to use domain socket, it should work OOTB:

- `quarkus.grpc.server.use-separate-server=false`
- https://quarkus.io/guides/vertx-reference#use-a-unix-domain-socket

Let us know if it does not work.

Note that to use a domain socket, you must install a native transport, and native compilation is not supported (see https://quarkus.io/guides/vertx-reference#native-transport)
