### ISSUE TITLE
[23.1] GraalVM depends on org.graalvm.home.Version which is polyglot API

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#35714]
### Describe the bug

`GraalVM` [class](https://github.com/quarkusio/quarkus/blob/f3d8f88b6d7bca7317720779c8ead67932280e49/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java#L141) depends on GraalVM's `Version` class for version parsing. See for example:

```
$ grep -rn 'org.graalvm' ./core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java
141:        final org.graalvm.home.Version version;
152:            this.version = org.graalvm.home.Version.parse(version);
```

Since GraalVM Community for JDK 21 (internal version `23.1`), the Version class will be part of the `polyglot.jar` (i.e. the `org.graalvm.polyglot:polyglot` maven artefact after the `graal-sdk` split). The intention for future versions of Quarkus would be to replace the dependency from `graal-sdk` to the future dependency `org.graalvm.sdk:nativeimage` only. See https://github.com/oracle/graal/discussions/7224

There are a couple of avenues to tackle this problem:

1. Remove the dep in Quarkus for GraalVM version parsing. It's fairly [trivial code](https://github.com/oracle/graal/blob/da0cd2fe0409fce2bd593e3aabcd7e058837f624/sdk/src/org.graalvm.home/src/org/graalvm/home/Version.java#L88) and could get moved to a Quarkus class instead.
2. When/if the `org.graalvm.sdk:graal-sdk` dependency gets reduced, it would need to get changed to require both. `nativeimage` and the `polyglot` artefact.
3. Convince upstream to make `Version` public API.
4. Keep the `graal-sdk` dependency forever (has the risk of upstream dropping the empty umbrella maven artefact, though)
5. Something else I'm probably missing.

**Comment by jerboaa** [comment]
I'm strongly in faviour of getting rid of the dependency and use a custom parser for the versions (in light of upstream no longer showing anything public about the - internal - version). So getting them to make `Version.parse()` API seems unlikely.

**Comment by zakkak** [comment]
Although, unfortunate I agree. We need to go back to doing our one parsing.

**Comment by zakkak** [comment]
This is also related to #34161
