### ISSUE TITLE
AWS Lambda extension does not pack necessary .so files when AWT is used

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#35713]
### Describe the bug

See https://github.com/quarkusio/quarkus/issues/35256#issuecomment-1705087637

The AWS Lambda extension must pack all necessary files into the function.zip.

### Expected behavior

AWS Lambda function.zip contains needed shared object (.so) dependencies. 

### Actual behavior

AWS Lambda function.zip contains just the runner executable.

### How to Reproduce?

See https://github.com/quarkusio/quarkus/issues/35256#issuecomment-1705087637

### Output of `uname -a` or `ver`

Linux 4.18.0-500.el8.x86_64

### Output of `java -version`

openjdk 17.0.8 2023-07-18

### GraalVM version (if different from Java)

OpenJDK Runtime Environment Mandrel-23.0.1.2-Final (build 17.0.8+7)

### Quarkus version or git rev

3.1, 3.2, main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

**Comment by gefloh** [comment]
Works like a charm with the new Quarkus 3.4 version @Karm. Thanks!
