### ISSUE TITLE
Since quarkus 3.3.0 a WARN message unrecognized configuration key "quarkus.kubernetes.route.expose" is logged

### ISSUE THREAD

**Issue by The-Huginn** [quarkusio/quarkus#35722]
### Describe the bug

WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.kubernetes.route.expose" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

### How to Reproduce?

Have the following property set:

`quarkus.openshift.route.expose=true`

### Quarkus version or git rev

3.3.0

**Comment by geoand** [comment]
@iocanel has anything changed in 3.3 around this Kubernetes config?

**Comment by gsmet** [comment]
@iocanel could you have a look at this one please? I also have it when deploying status.quarkus.io and it looks concerning if this config is actually ignored by the extension as it is required.

**Comment by gsmet** [comment]
I tried to update status.quarkus.io to 3.3.1 and I had a certificate error when I tried to go to the website and then it said it wasn't available.
So I suspect there is an actual issue here.

**Comment by gsmet** [comment]
I wonder if this could be related to https://github.com/quarkusio/quarkus/issues/35673 . I will try with 3.3.2.

**Comment by radcortez** [comment]
Maybe more related to https://github.com/quarkusio/quarkus/pull/34487. I'll have a look.

**Comment by gsmet** [comment]
Yeah, the problem is NOT fixed in 3.3.2. I think we really need a fix for 3.3.3 as I suspect a lot of OpenShift deployments are broken because of this.

**Comment by radcortez** [comment]
Yes, this is related with https://github.com/quarkusio/quarkus/pull/34487. I'll come up with something.
