### ISSUE TITLE
Enable native heap dump monitoring by default

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#35729]
### Description

Recent GraalVM versions allow heap dumps to be generated on demand (see [GraalVM documentation](https://www.graalvm.org/22.0/reference-manual/native-image/NativeImageHeapdump/)). To be able to generate them, the enable monitoring option for heap dumps needs to be passed in when building the native executables. From a Quarkus perspective, this means you have to pass in `-Dquarkus.native.monitoring=heapdump` at native build time.

In upcoming GraalVM for JDK 21, the heap dump monitoring option has been [enhanced](https://github.com/oracle/graal/pull/7012) to support `-XX:+HeapDumpOnOutOfMemoryError`, a very valuable flag for applications that suddenly run out of memory. Being able to pass in this option at runtime still requires heap dump monitoring to be enabled at native build time.

I'm proposing that Quarkus enables heap dump native monitoring by default. Having this option enabled by default has no real impact on startup time. It does have minimal impact on the size of the binary, which at times can be a maximum of 1% increase.

See [here](https://gist.github.com/galderz/00d65b994b378bf3e64fdba37bd29e9e) for a comparison of the native executable sizes generated by the Quarkus integration testsuite with and without heap dump monitoring.

**Comment by galderz** [comment]
Technically some startup costs are added to add a signal handler for the heap dump request, but having run [startstop tests](https://github.com/quarkus-qe/quarkus-startstop), I don't see any degradation with heap dump monitoring enabled.

Native mode | Base | Heap Dump |
-- | -- | --
REST Minimal AVG RSS | 43783 | 43484
REST Minimal AVG time to first response | 35 | 30
Full MP AVG RSS | 68786 | 68957
Full MP AVG time to first response | 40 | 36

**Comment by holly-cummins** [comment]
Is this change why I'm getting the following error if I try to build a native image using the reactive quickstart?

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GRAALVM 22.2.0 JDK 17.0.4+8-jvmci-22.2-b06
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 --features=io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,org.hibernate.graalvm.internal.GraalVMStaticFeature,io.quarkus.runner.Feature,io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https --enable-monitoring=heapdump -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json code-with-quarkus-1.0.0-SNAPSHOT-runner -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
Error: Unrecognized option: --enable-monitoring=heapdump
```

**Comment by younghoonk17** [comment]
Hey @holly-cummins, I'm running into the same error. Did you figure out if it was due to this change? Thanks

**Comment by galderz** [comment]
@holly-cummins Sorry I missed this. The minimum GraalVM version is 22.2 but in that version heap dump monitoring was not in place. Updating to the latest GraalVM version would fix this. I've created #37825 to avoid adding this flag unless it's within a GraalVM version that supports it.
