### ISSUE TITLE
OIDC logout not working for virtual callback paths, if id_token is expired but session cookie is present

### ISSUE THREAD

**Issue by sschellh** [quarkusio/quarkus#35728]
### Describe the bug

A call to the logout path `quarkus.oidc.logout.path`  fails with HTTP 404, if there is a session cookie present, but the id_token is expired. (i.e. `quarkus.oidc.authentication.session-age-extension` is larger than 0)

### Expected behavior

If the logout path `quarkus.oidc.logout.path` is called, then there is never a HTTP 404 returned. Instead, the q_session cookie is deleted (if present) and the logout process triggered.

The user is eventually redirected to `quarkus.oidc.logout.post-logout-path`. If the user is not logged in, then he is still redirected to the post-logout path.

### Actual behavior

If there is a q_session cookie, but the id_token is not valid anymore, then the application returns HTTP 404.
The problem is that as a result the q_session cookie is not deleted and other cleanups (like revoking the refresh token) are not performed, because the event `OIDC_LOGOUT_RP_INITIATED` is not triggered.

### How to Reproduce?

Settings:
quarkus.oidc.authentication.session-age-extension = PT4H
quarkus.oidc.logout.path=/logout

1. Login into your application
2. Wait for the id_token to expire
3. Call the path /logout

**Comment by sberyozkin** [comment]
@sschellh What Quarkus version is it ?

**Comment by sschellh** [comment]
It is 3.3.1 (Sorry forgot to add this information)
