### ISSUE TITLE
[Extension Proposal] Qute Web

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#35739]
### Description

As discussed on this topic https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Make.20Qute.20Server.20Page.20part.20of.20RESTEasy.20Qute

It would be good for the Qute Web story to introduce Qute Web (in Quarkus Core) in the place of Qute Server Page.

The idea would be to have:
- Qute (templating)
- Qute Web (templating for the web, if there is a template in `templates/web` serve it like currently done in QSP (`/` by default, with priority over static resources)
- If you add RESTEasy or RR then its Qute counterpart comes alongside it using conditional dependencies (and hide them from tooling)

This way for the end user "Qute Web" becomes the only extension to use Qute for the Web, whether or not you want to use it with a bean Resource (which requires RESTEasy [R] anyway).

### Repository name

quarkus-qute-web

### Short description

Qute for the Web

**Comment by maxandersen** [comment]
why do you want this in quarkus core repo? or is it some other core you are referring to?

**Comment by ia3andy** [comment]
> why do you want this in quarkus core repo? or is it some other core you are referring to?

I believe we don't really have the choice as Qute RESTEasy [R] are in core?

**Comment by ia3andy** [comment]
> > why do you want this in quarkus core repo? or is it some other core you are referring to?
> 
> I believe we don't really have the choice as Qute RESTEasy [R] are in core?

@maxandersen Aw sorry I meant part of the platform, the actual repository location doesn't matter.

**Comment by ia3andy** [comment]
@mkouba how could we plan this? I could help if needed? I think it's very important as part of the Quarkus Fullstack/Web story.

**Comment by mkouba** [comment]
Hm, but if I understand it correctly the functionality described above is basically the same as in `quarkus-qute-server-pages`, except the default value for `quarkus.qsp.hidden-templates` which would be "everything but `/web/*`"?

> If you add RESTEasy or RR then its Qute counterpart comes alongside it using conditional dependencies (and hide them from tooling)

Do you want the pages in `/web/*` to coexist with RR endpoints?

Maybe we could just rename the `quarkus-qute-server-pages` extension and change the defaults?

**Comment by ia3andy** [comment]
@mkouba yes that's pretty much it (and the conditional deps), we also have to put Qute Web in the platform @maxandersen @aloubyansky it should be ok right?

> Do you want the pages in `/web/*` to coexist with RR endpoints?

Yes that's what I do in Quinoa, maybe we could allow to configure which one has priority (I didn't in Quinoa)

**Comment by mkouba** [comment]
> and the conditional deps...

So if RR is present then add `quarkus-resteasy-reactive-qute` automatically, right?

> Yes that's what I do in Quinoa, maybe we could allow to configure which one has priority (I didn't in Quinoa)

This is also configurable with the [` quarkus.qsp.route-order`](https://docs.quarkiverse.io/quarkus-quteserverpages/dev/index.html#quarkus-qsp_quarkus.qsp.route-order) config property.

**Comment by ia3andy** [comment]
> > and the conditional deps...
> 
> So if RR is present then add `quarkus-resteasy-reactive-qute` automatically, right?
> 

Yes and the same for RC

> > Yes that's what I do in Quinoa, maybe we could allow to configure which one has priority (I didn't in Quinoa)
> 
> This is also configurable with the [` quarkus.qsp.route-order`](https://docs.quarkiverse.io/quarkus-quteserverpages/dev/index.html#quarkus-qsp_quarkus.qsp.route-order) config property.

Awesome!

I need to add the same in Quinoa

**Comment by ia3andy** [comment]
Let me know if I can help..

**Comment by mkouba** [comment]
>> This is also configurable with the [ quarkus.qsp.route-order](https://docs.quarkiverse.io/quarkus-quteserverpages/dev/index.html#quarkus-qsp_quarkus.qsp.route-order) config property.

> I need to add the same in Quinoa

@ia3andy The problem is that this config property is fixed at build time. So you can't use the `RunTimeConfigurationDefaultBuildItem`... I wonder if there's a way to set the default value of a build time config property from a different extension?

**Comment by ia3andy** [comment]
I mean I need to add a new similar config `quarkus.quinoa.route-order` for Quinoa.

Also you might need to rename the config prefix if we rename the extensions

**Comment by mkouba** [comment]
Ok, so I think that "adapting" the `quarkus-qute-server-pages` extension would be the best way.

To sum it up, we would: 

- rename the groupId from `io.quarkiverse.quteserverpages` to `io.quarkiverse.quteweb`
- rename the artifactId from `quarkus-qute-server-pages`  to `quarkus-qute-web`
- rename the config prefix from `quarkus.qsp` to `quarkus.qute-web`
- modify the defaults for:
   - `root-path` from `/qsp` to `/`
   - `hidden-templates` from `tags/.*` to something like `^(?!web/).*`
 - add conditional dependencies for `quarkus-resteasy-reactive-qute` and `quarkus-resteasy-qute`

@gastaldi I guess that it would be easier to create a new quarkiverse repository instead of modifying the existing one?

**Comment by ia3andy** [comment]
I think for the conditional dependencies, having qute-web in the platform is necessary (for RR/RC versions sync)

**Comment by ia3andy** [comment]
@gastaldi what is the procedure to have an extension added in the platform? How does the Quarkus platform bom version sync happen?

**Comment by mkouba** [comment]
> I think for the conditional dependencies, having qute-web in the platform is necessary (for RR/RC versions sync)

According to https://quarkus.io/guides/conditional-extension-dependencies the version is not necessary. But maybe I'm missing something...

**Comment by ia3andy** [comment]
@mkouba for the groupId maybe `io.quarkiverse.qute.web`

**Comment by gastaldi** [comment]
> @gastaldi I guess that it would be easier to create a new quarkiverse repository instead of modifying the existing one?

I think renaming is better given it will automatically redirect old URLs to the new one. We can rename the repository and the teams here: https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-qute-server-pages.tf#L3 (keeping the `quarkus_qute_server_pages` ID though in the script - which is not really a big deal)

> @mkouba for the groupId maybe `io.quarkiverse.qute.web` or just `io.quarkiverse.qute`?
> 
> @gastaldi would that be a problem? 👆

No, not a problem, that's up to you guys to decide 😉

**Comment by mkouba** [comment]
> > @gastaldi I guess that it would be easier to create a new quarkiverse repository instead of modifying the existing one?
> 
> I think renaming is better given it will automatically redirect old URLs to the new one. We can rename the repository and the teams here: https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-qute-server-pages.tf#L3 (keeping the `quarkus_qute_server_pages` ID though in the script - which is not really a big deal)

Would I be able to perform a bugfix release for `quarkus-qute-server-pages` 2.x afterwards?

**Comment by gastaldi** [comment]
Yes, it should still work

**Comment by ia3andy** [comment]
Maybe we should also move those to the quarkiverse?
- https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-classic/resteasy-qute
- https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-qute

Once that's done, we should mark them as `unlisted` in the metadata.

**Comment by mkouba** [comment]
> Maybe we should also move those to the quarkiverse?
> 
>     * https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-classic/resteasy-qute
> 
>     * https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-reactive/quarkus-resteasy-reactive-qute
> 
> 
> They could be in qute-web as a multi extensions repo?
> 
> Once that's done (qute-web), we should mark them as `unlisted` in the metadata.

I don't think it's a good idea... at least I don't see any benefit.

**Comment by ia3andy** [comment]
@mkouba any specific reason?

**Comment by mkouba** [comment]
> @mkouba any specific reason?

Breaks compatibility for no reason?

**Comment by ia3andy** [comment]
@mkouba AFAIK this is what we did for everything we moved to quarkiverse (right @gsmet ?)

**Comment by mkouba** [comment]
> @mkouba AFAIK this is what we did for everything we moved to quarkiverse (right @gsmet ?)

Hm, but we're not moving anything since `quarkus-qute-server-pages` is a quarkiverse project already...

**Comment by ia3andy** [comment]
> > @mkouba AFAIK this is what we did for everything we moved to quarkiverse (right @gsmet ?)
> 
> Hm, but we're not moving anything since `quarkus-qute-server-pages` is a quarkiverse project already...

I mean when we created the Quarkiverse we moved a lot of extension from core (which stayed in the platform for some of them) without real reason beside clearing core.

**Comment by mkouba** [comment]
> > > @mkouba AFAIK this is what we did for everything we moved to quarkiverse (right @gsmet ?)
> > 
> > 
> > Hm, but we're not moving anything since `quarkus-qute-server-pages` is a quarkiverse project already...
> 
> I mean when we created the Quarkiverse we moved a lot of extension from core (which stayed in the platform for some of them) without real reason beside clearing core.

I see. But since qute, RR and RC are part of the core I don't see a reason why to move the integration bits (two maven modules) into quarkiverse.

**Comment by aloubyansky** [comment]
We moved extensions out of core in a new major release though and kept relocations for a long time. It has to be thought out.

Conditional dependencies do not depend on extensions being in a platform or not.

**Comment by ia3andy** [comment]
cc @fbricon @angelozerr

**Comment by ia3andy** [comment]
@mkouba any update on this?

**Comment by mkouba** [comment]
@ia3andy No update yet. So let's [sum it up once again](https://github.com/quarkusio/quarkus/issues/35739#issuecomment-1757201931):

- create 2.1 branch in the `quarkus-qute-server-pages` repo
- rename the groupId from `io.quarkiverse.quteserverpages` to `io.quarkiverse.qute.web`
- rename the artifactId from `quarkus-qute-server-pages`  to `quarkus-qute-web`
- rename the config prefix from `quarkus.qsp` to `quarkus.qute-web`
- modify the defaults for:
   - `root-path` from `/qsp` to `/`
   - `hidden-templates` from `tags/.*` to something like `^(?!web/).*`
 - add conditional dependencies for `quarkus-resteasy-reactive-qute` and `quarkus-resteasy-qute`
 - rename the `quarkus-qute-server-pages` repo to `quarkus-qute-web`
 - rename the repository and the teams here: https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-qute-server-pages.tf#L3

If we agree on this ^ then I can start to work on it tomorrow.

**Comment by ia3andy** [comment]
Perfect (AFAIK) @gastaldi could you add your rocket to it?

**Comment by mkouba** [comment]
FYI: https://github.com/quarkiverse/quarkus-qute-server-pages/pull/49

**Comment by gastaldi** [comment]
I've created https://github.com/quarkiverse/quarkiverse-devops/pull/189 to perform the repository rename. 

@mkouba Feel free to review and merge it when you feel necessary

**Comment by mkouba** [comment]
FTR I've created https://github.com/quarkiverse/quarkus-qute-web/issues/51 for the conditional dependencies feature.

I'm not so sure about this one:
> mark quarkus-resteasy-reactive-qute and quarkus-resteasy-qute as unlisted in the metadata (see https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L15)

Mostly because quarkiverse is not part of the "platform" (at least in the code.quarkus.io UI) and so qute-web is not visible by default.

Other than that I think that we can close this issue.

**Comment by ia3andy** [comment]
> FTR I've created [quarkiverse/quarkus-qute-web#51](https://github.com/quarkiverse/quarkus-qute-web/issues/51) for the conditional dependencies feature.
> 
> I'm not so sure about this one:
> 
> > mark quarkus-resteasy-reactive-qute and quarkus-resteasy-qute as unlisted in the metadata (see https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L15)
> 
> Mostly because quarkiverse is not part of the "platform" (at least in the code.quarkus.io UI) and so qute-web is not visible by default.
> 
> Other than that I think that we can close this issue.

I think we should add qute-web to the platform

**Comment by ia3andy** [comment]
I've created for what's remaining https://github.com/quarkusio/quarkus/issues/37000

**Comment by mkouba** [comment]
> I've created for what's remaining #37000

Thanks. What a nice issue number ;-).
