### ISSUE TITLE
Unable to update status.quarkus.io to 3.3.1

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#35745]
I deployed a new version status.quarkus.io with the update to Quarkus 3.3.1 on OpenShift and I got several issues:

- https://github.com/quarkusio/quarkus/issues/35722 - and I had a weird certificate error so I suspect that the route was actually incorrectly set
- I also had a weird SmallRye GraphQL error on startup saying that there was no data in the response. Same app with 3.2.5.Final works perfectly

**Comment by gsmet** [comment]
I think the GraphQL issue might be related to another OpenShift issue: my guess is that the secrets were not properly propagated.

**Comment by iocanel** [comment]
@gsmet: AFAIR there is no direct integration point between graphql and Openshift, so I am not sure they are related.
