### ISSUE TITLE
Large files remain in /tmp after OpenShift deployments

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#35747]
I did two (successful) OpenShift deployments in a row and I ended up with the following files in my `/tmp`:

```
ls -lh /tmp/quarkus*-openshift
-rw-------. 1 gsmet gsmet 58M Sep  5 15:53 /tmp/quarkus-13320225906929738030-openshift
-rw-------. 1 gsmet gsmet 58M Sep  5 15:47 /tmp/quarkus-2335204798525672356-openshift
```

That could easily become a problem if you are deploying a lot.

Could we have a look at why these files are not properly cleaned up after the deployment?

**Comment by gsmet** [comment]
@iocanel assigning to you

**Comment by geoand** [comment]
@iocanel are you on this orr should I fix it?

**Comment by geoand** [comment]
In any case, I'm pretty sure https://github.com/quarkusio/quarkus/pull/35762 is the proper fix

**Comment by iocanel** [comment]
> @iocanel are you on this orr should I fix it?
You beat me to it! :smile:
