### ISSUE TITLE
Reconsider the precedence of Forwarded vs X-Forwarded-For

### ISSUE THREAD

**Issue by tsaarni** [quarkusio/quarkus#35751]
### Description

Previously change https://github.com/quarkusio/quarkus/pull/25117 introduced the option to set both `quarkus.http.proxy.allow-forwarded` and `quarkus.http.proxy.allow-x-forwarded` at the same time. It is rightly highlighted in the docs that this combination is not recommended and there can be security implications if used ([doc link](https://quarkus.io/guides/http-reference#reverse-proxy)). 

When both are enabled, Quarkus currently uses `Forwarded` over `X-Forwarded-*` if both headers are present. However many popular proxies like NGINX and Envoy do not seem to support `Forwarded` - they do support `X-Forwarded-*`. As a result, application that enabled both will be subject to header forging (untrusted client setting `Forwarded`), unless user of the application realizes this and explicitly re-configures the proxy to overwrite `Forwarded`.  If the order Quarkus parses the headers would be the other way around (`X-Forwarded-*` over `Forwarded`) this would not be the case. Even if user missed reconfiguring the proxy and uses the defaults, they would be safe(r).

Another reasoning for the idea: often the backwards compatibility design principles say that old functionality should take precedence over new functionality.

If you consider this idea of swapping the priority something you'd take into Quarkus, I can contribute it.

**Comment by cescoffier** [comment]
While `X-Forwarded-For` is widely used, it is not a standard.
Conversely, `Forwarded` is defined in the RFC 7239 (https://tools.ietf.org/html/rfc7239) from 2014. It's kind of sad to still have usages of `X-Forwarded-For` as `Forwarded` was defined almost 10 years ago. It is also richer than the _bare_ `X-Forwarded-For`.

So, I think the current behavior of Quarkus is correct. We prefer a standardized mechanism.

We could imagine an option to switch back the precedence, but it would need to be explicitly set.

**Comment by sschu** [comment]
I don't think an option to switch precedence would really help here. The problem is that people who don't know/don't care about these headers suddenly have an open attack surface if an attacker sends the headers with higher precedence. I am wondering if it would be better to to just not process requests if both headers are present and the values are not consistent...

**Comment by cescoffier** [comment]
I totally agree with @sschu idea.
