### ISSUE TITLE
Allow to have params propagation from Qute tags to underlying element

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#35765]
### Description

To make it easier to use and create tags (and server side components), it is important to be able to allow passing random args to any underlying element of the tag (determined by the implementation).

### Implementation ideas

gravatar.html
```html
<img src="https://www.gravatar.com/avatar/{hash}{#if size}?s={size}{/if}" {params.without("hash", "size").asHtmlAttributes()}/>
```

Usage:
```html
{#gravatar hash="ia3andy" alt="ia3andy" title="https://github.com/ia3andy" class=rounded}
```

Output:
```html
<img src="https://www.gravatar.com/avatar/ia3andy" alt="ia3andy" title="https://github.com/ia3andy" class="rounded" />
```

**Comment by ia3andy** [comment]
@FroMage I know you were also looking for something like this (for the `{#form}` for example)

**Comment by mkouba** [comment]
This should be doable. I'd prefer to use `{_args}` instead of `{params}` and the returned type could look like:

```java
interface UserTagArgs extends Map<String,String> {

   UserTagArgs skip(String... keys);

   UserTagArgs filter(String... keys);

   String asHtmlAttributes();
   
}
```

So that the usage would look like: `{_args.skip("hash", "size").asHtmlAttributes}`.

**Comment by ia3andy** [comment]
> This should be doable. I'd prefer to use `{_args}` instead of `{params}` and the returned type could look like:
> 
> ```java
> interface UserTagArgs extends Map<String,String> {
> 
>    UserTagArgs skip(String... keys);
> 
>    UserTagArgs filter(String... keys);
> 
>    String asHtmlAttributes();
>    
> }
> ```
> 
> So that the usage would look like: `{_args.skip("hash", "size").asHtmlAttributes}`.

Yeah that looks great!

**Comment by FroMage** [comment]
Woohoo, super cool!
