### ISSUE TITLE
Quarkus Cli Update downgrades project version

### ISSUE THREAD

**Issue by bumbel42so** [quarkusio/quarkus#35760]
### Describe the bug

quarkus update with Quarkus CLI version 3.3.1 downgrades project quarkus version from 3.2.2.Final to 3.1.2.Final.

> PS C:\ws\eclipse-git\Tresorreport Service Quarkus\tresorreport.rest> quarkus update
> [INFO] Error stacktraces are turned on.
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] --------------------< com.freier:tresorreport.rest >--------------------   
> [INFO] Building tresorreport.rest 2.0.0-SNAPSHOT                                  
> [INFO]   from pom.xml                                                             
> [INFO] --------------------------------[ jar ]---------------------------------   
> [INFO]                                                                            
> [INFO] --- quarkus-maven-plugin:3.3.1:update (default-cli) @ tresorreport.rest ---
> [WARNING] quarkus:update goal is experimental, its options and output might change in future versions
> [INFO] Looking for the newly published extensions in registry.quarkus.io
> [INFO] Detected project Java version: 17
> [INFO] Instructions to update this project from '3.2.2.Final' to '3.1.2.Final':
> [INFO] Recommended Quarkus platform BOM updates:
> [INFO] Update: io.quarkus.platform:quarkus-bom:pom:3.2.2.Final -> 3.1.2.Final
> [INFO]
> [INFO] Resolved io.quarkus:quarkus-updates-recipes:1.0.4 with 0 recipe(s) to update from 3.2.2.Final to 3.1.2.Final (initially made for OpenRewrite MAVEN plugin version: 4.46.0) 

### Expected behavior

quarkus update updates to quarkus version 3.3.*

### Actual behavior

Quarkus update downgrades to quarkus version 3.1

### How to Reproduce?

1. project config like:
![image](https://github.com/quarkusio/quarkus/assets/60612641/170a9f16-76ea-4c15-838a-9668dce6935e)

2. quarkus update

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)                   OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 

### Additional information

quarkus version
3.3.1

**Comment by gsmet** [comment]
This is very odd. Could you attach a project that behaves this way as a zip? I don't think we need the code, the full POM should be enough.

/cc @aloubyansky

**Comment by bumbel42so** [comment]
@gsmet 
I solved the problem, it was my own fault. Sorry :)
I used a private registry which was connected to mvncentral. But i removed the connection to other reasons, so the newest quarkus version that can be found in registry was 3.1.
Only thing you can do is to check the versions and prevent downgrading :)

**Comment by gsmet** [comment]
How did you configure your private registry? Because I looked at the log for that and only found `[INFO] Looking for the newly published extensions in registry.quarkus.io` so I'm wondering if we should adjust the message.

Or you pointed `registry.quarkus.io` to a custom registry locally?

**Comment by bumbel42so** [comment]
I configured it in settings.xml in reposotiroies

> <profiles>
>  		<profile>
>  			<id>azure</id>
>  			<repositories>
>  				<repository>
>  					<id>maven-lib</id>
>  					<url>https://pkgs.dev.azure.com/xxxx/xxxxx/_packaging/maven-lib/maven/v1</url>
>  					<releases>
>  						<enabled>true</enabled>
>  					</releases>
>  					<snapshots>
>  						<enabled>true</enabled>
>  					</snapshots>
>  				</repository>
>  			</repositories>
>  			<properties>
> 				<repo-id>maven-lib</repo-id>
> 				<repo-url>https://pkgs.dev.azure.com/xxx/xxxxxx/_packaging/maven-lib/maven/v1</repo-url>
> 			</properties>
>  		</profile>
>  	</profiles>
>  	<activeProfiles>
>  		<activeProfile>azure</activeProfile>
>  	</activeProfiles>

**Comment by gsmet** [comment]
But you had to configure Quarkus to point to the registry or am I mistaken?

**Comment by bumbel42so** [comment]
No, this is the only point where i configured my private registry

**Comment by aloubyansky** [comment]
It could have been cached in the local repo and if there was not access to the registry since that point, there wouldn't be any updates.
