### ISSUE TITLE
OIDC DevUI triggers a code grant request when user logs out

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#35775]
### Describe the bug

`qwc-oidc-provider.js` triggers `_exchangeCodeForTokens` when the user presses `Logout`.

It looks like `(QwcOidcProvider._hasCodeInUrl())` check is triggered immediately when the logout button is pressed and since the current URL does have it from the just completed login it causes a failing code grant request with the error in the logs. Then the logout completes successfully.

It looks like it is something related to the hot reload/properties update done in the script. Ideally, the code/state would be dropped down after the login but then it would require an introduction of the local storage property.

**Comment by michalvavrik** [comment]
@sberyozkin I tried to reproduce it on quarkus-quickstarts/security-openid-connect-quickstart with `quarkus.oidc.devui.grant.type=code` and can't see any logged exception even when logging is set to TRACE, nor I can see `code` in query params after logout (which would be highly strange considering we redirect to keycloak with post logout URI constructed in `_getEncodedPath` that shouldn't contain any query params.

Can you write down steps to reproduce or at least give me a hint on your config, please? I probably just miss some setting or steps, thank you.

**Comment by michalvavrik** [comment]
also @sberyozkin what browser did you use? I tried it with Firefox and Chrome. I don't think it could be related, but just in case steps to reproduce are not available, I can try other browsers.

**Comment by sberyozkin** [comment]
Hi @michalvavrik Thanks for checking - I've just confirmed as well that the issue persists with the 3.3.2 platform but is fixed for 3.4.0.CR1, I'm not sure which Dev UI related fix affected it but the good news it is no longer a problem, sorry for the noise
