### ISSUE TITLE
Template for new extensions should use the name for the docs table of contents, not a human-cased artifact ID

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#35782]
See discussion here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.22Quarkus.22.20word.20in.20Quarkiverse.20docs.20pages/near/359005952

George has done a batch change of existing extensions, but we're still generating old extensions with 'Quarkus' prefixed to the name in the docs. 

Without this change, we would have tables of contents like this, where ~50% of the words are "Quarkus". 

![image](https://github.com/quarkusio/quarkus/assets/11509290/ca2beba7-a6db-47d5-a4f6-625aaaa2b270)

**Comment by holly-cummins** [comment]
@gsmet, I think this is what you fixed the other day, do you agree?

**Comment by gsmet** [comment]
Yes, exactly, we can close!
