### ISSUE TITLE
`quarkus.rest.path` in stead of `quarkus.resteasy-reactive.path`  in REST reactive environment

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#35794]
### Describe the bug

In `application.properties` one can specify

```properties
#quarkus.resteasy-reactive.path=/api
quarkus.rest.path=/api
```

### Expected behavior

I would expect `quarkus.resteasy-reactive.path=/api` to be used. 

### Actual behavior

`quarkus.rest.path=/api` is used instead.

Also a warning is printed during the build: 
`[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.rest.path" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

### Output of `java -version`

11

### GraalVM version (if different from Java)

n.a. 

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

### Additional information

extract from `pom.xml`
```
       <!-- quarkiverse -->

        <dependency>
            <groupId>io.quarkiverse.quinoa</groupId>
            <artifactId>quarkus-quinoa</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkiverse.jberet</groupId>
            <artifactId>quarkus-jberet</artifactId>
        </dependency>

        <!-- quarkus -->

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-oracle</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-narayana-jta</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-swagger-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jaxb</artifactId>
        </dependency>
```

**Comment by geoand** [comment]
I tried both setting and they both worked as expected.

**Comment by sjaakd** [comment]
@geoand . I'll try to make a reproducer. Will take some time to strip our code. Perhaps I'll get some more insight myself as well. This is the reason I first raised the issue: perhaps you immediately see the problem.

To be sure: only the REST services need to be reactive (with their reactive maven dependency).. right? I also use the Hibernate / Panache..

**Comment by geoand** [comment]
Yup those properties are for quarkus-resteasy-reactive

**Comment by sjaakd** [comment]
Sorry guys.. problem seems to be gone when I started to take apart my production application piece by piece in order to make a reproducer. Could not reproduce when reconstructing again. So must have been something strange on my machine?

I'll check also tomorrow with a colleague of mine. Then I'll proceed to close this one.

**Comment by sjaakd** [comment]
Works as expected.
