### ISSUE TITLE
Quarkus 3 -> PanacheRepoqueries  SemanticException

### ISSUE THREAD

**Issue by dennan94** [quarkusio/quarkus#35812]
### Describe the bug

When using the chars "fk" in a package name where entities are located all queries will give:

`Unexpected exception thrown: java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: A query exception occurred [FROM org.fk.test.test.entity.Test WHERE id= ?1]`

I've tested most versions from 3.0.0.Final to 3.3.2.

Same issue when using FK in class name.

The issue occured when updating from Quarkus 2 to 3.

### Expected behavior

Entity with populated data or null 

### Actual behavior

`Unexpected exception thrown: java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: A query exception occurred [FROM org.fk.test..entity.FooEntity]`

### How to Reproduce?

Create a package structure with fk in:
org.fk.test..entity;

Create an entity

`
@Entity
public class FooEntity extends PanacheEntity {
    private String test;
}
`

Create a test:

    @Test
    @TestTransaction
    void findAll() {
        assertDoesNotThrow(() -> FooEntity.findAll().firstResult());
    }

Unexpected exception thrown: java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: A query exception occurred [FROM org.fk.test..entity.FooEntity]
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: A query exception occurred [FROM org.fk.test..entity.FooEntity]

### Output of `java -version`

17

### Quarkus version or git rev

3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew 8.3

**Comment by marko-bekhta** [comment]
Hey, thanks for reporting this. In this case, probably both ORM (https://hibernate.atlassian.net/browse/HHH-17823) and Panache could've been more forgiving to "keywords" in the package name 😃
