### ISSUE TITLE
Blaze documentation outdated for Quarkus 3

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#35835]
### Describe the bug

https://quarkus.io/guides/blaze-persistence

Gradle dependencies are outdated and there **will be no CriteriaBuilderFactory or EntityViewManager bean** to be injected.

I came up with these dependencies, adapted from

1. Their Maven Quarkus 3 example https://github.com/Blazebit/blaze-persistence/blob/main/examples/quarkus-3/base/pom.xml
2. By running `./gradlew addExtension --extensions="com.blazebit:blaze-persistence-integration-quarkus"`

```
       implementation(enforcedPlatform("${quarkusPlatformGroupId}:quarkus-blaze-persistence-bom:${quarkusPlatformVersion}"))

        implementation("com.blazebit:blaze-persistence-integration-quarkus-3")
//        implementation("com.blazebit:blaze-persistence-integration-jaxrs-jackson-jakarta") // does not exist
//        annotationProcessor("com.blazebit:blaze-persistence-entity-view-processor-jakarta") //not sure about this one

//        runtimeOnly("com.blazebit:blaze-persistence-integration-hibernate-6.2") // also not sure
```

**Comment by geoand** [comment]
cc @beikov
