### ISSUE TITLE
Replace "Java Persistence API" (obsolete)  with "Jakarta Persistence API"

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#35857]
### Description

Our community docs consistently use "Jakarta Persistence" and "Jakarta Persistence API" instead of the obsolete term,  "Java Persistence API."

Find and replace any instances of the obsolete term that slipped by previous revisions unchanged.

### Implementation ideas

Search and replace instances of the obsolete term.

**Comment by GhanshyamVaru** [comment]
Hello @rolfedh 
if anyone isn't working on it then I would like to solving this issue,
Thank you.

**Comment by gsmet** [comment]
This is indeed not an issue and should be closed.

**Comment by rolfedh** [comment]
Hi @GhanshyamVaru. 
Thank you for your interest in the Quarkus project. To learn more about contributing, please see the this [Contributing guide](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md).
If you're a new open source contributor, you might also be interested in [Hacktoberfest](https://hacktoberfest.com/), of which Red Hat is a participant. You're welcome to reach me directly at rdlugyhe (at-symbol) redhat.com and I'll show you some OpenShift documentation issues that are good for first time contributors. 
Best wishes,
Rolfe (@rolfedh)

**Comment by GhanshyamVaru** [comment]
Hi @rolfedh 
Thank you for response Actually I though that you have some work to convert javax to jakarta that's why I requested for that 😅.
