### ISSUE TITLE
Create the test structure when using `create-extension` Maven Mojo.

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#3585]
**Description**
When initializing an extension with the `create-extension` Maven Mojo it would be neat to create the `src/main/java` folders, plus create a blank test.

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

The folder and code generation works already so it's not a big deal to create the structure. The point is what test should be generate. IMHO, we should only add a test in the extensions's `deployment` module.

When generating an extension `my-extension` for instance , the mojo creates a `MyExtensionProcessor`. We could generate a `MyExtensionTest` test class with a basic

```
@RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class));
```

Given the content of the generated `Processor` the only thing we could test out of the box would be the presence of the extension in `QuarkusUnitTest`

**Comment by gwenneg** [comment]
That's a great idea! I would also add a blank dev mode / hot reload test:

```
@RegisterExtension
    final static QuarkusDevModeTest test = new QuarkusDevModeTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class));
```

**Comment by gsmet** [comment]
@machi1990 @gwenneg this one looks like a quick win? Would one of you be interested in tackling this so we can close the issue?

**Comment by machi1990** [comment]
Let me have a look.
