### ISSUE TITLE
Property to mount a container volume during container (integration) testing

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#35864]
### Description

DISCLAIMER: I am not sure if this I technical possible with all the native stuff and so on. 

I have an application that access the file system to read/write files. Testing with `@QuarkusTest` is a piece of cake as all the data is on my local fs. When It comes to containerized native integration testing this gets a bit messy. The solution I currently use is an extra API which can create  or read testdata inside of the container. 
This means I have code for testing in `main` which already is definitly not good practice. I need to secure the API in production mode, so it is not callable anymore. This is error prone and poses a risk.

So it would be nice if I could write the files directly into the container. Or into a volume mount.

### Implementation ideas

In my imagination this would be configurable somehow like this:
`quarkus.test.container.volume-mounts."C:\dev\projects\myproject"=\home\myContainerFolder`
which would lead to the docker container under test is started with `-v C:\dev\projects\myproject:\home\myContainerFolder`
Now I still can create all my testdata on my local fs and everything works as expected without any extra messy hacking.

**Comment by geoand** [comment]
We can likely have something the same way we have `quarkus.test.container.additional-exposed-ports` and `quarkus.test.container.labels`.

Would you like to take a shot at it?

**Comment by HerrDerb** [comment]
@geoand sure, I'll have look

**Comment by HerrDerb** [comment]
I've got something. I guess I would need to build it locally to try it out as there are not tests for those configs.
How can I build this colossus locally?

**Comment by geoand** [comment]
`mvn -T C1 -Dquickly -Dformat.skip=true` is the easiest way, but there are plenty of [options](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build).

**Comment by HerrDerb** [comment]
Sadly the build keeps failing at `Quarkus - Gradle Model ............................. FAILURE` with no helpfull error message.
I got gradle installed, JAVA_HOME for openjdk18 set. Does this sound familiar?

**Comment by geoand** [comment]
I personally always use Java 17 for Quarkus development.

Unless you've changed any Gradle related stuff (which this feature shouldn't require), don't worry about the Gradle stuff

**Comment by HerrDerb** [comment]
Do I miss something? When trying to start a project with my custom quarkus build, I still get
`[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.test.container.volumn-mounts" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`
Altought, when I browse the code of the dependencies the `@ConfigItem` in [`TestConfig`](https://github.com/quarkusio/quarkus/pull/35880/files#diff-f208e5120ee9061d6808f8a036632265fec0aabae9aa02b2e9e9d0eebde7dd8aR307) is there.

**Comment by geoand** [comment]
Hard to tell without seeing the code, so best open a draft PR please

**Comment by HerrDerb** [comment]
Already did: https://github.com/quarkusio/quarkus/pull/35880
