### ISSUE TITLE
Enhance Elytron Security extension to support a database as identity store

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#3586]
**Description**
(Describe the feature here.)
The goal of this feature would be to enhance the existing quarkus-elytron-security extension (which covers only a file based identity store currently) to take benefits of Elytron Security supports for Database as identity store. 

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

The discussion started here
https://groups.google.com/d/msg/quarkus-dev/fihoprhf_DE/8ZYlptFoAgAJ

**Comment by loicmathieu** [comment]
@danielpetisme the quarkus-elytron-security extension only cover basic authentication via  a user/password file or embedded in application.properties not Oauth2.
But it's the right place to add an other identity store (an IdentityManager in Elytron security).

**Comment by danielpetisme** [comment]
@loicmathieu can you provide some guidance for the DB identity store please?

What I understood:
- the feature will be hosted by the existing `quarkus-elytron-security` extension
- Provide a `DatabaseRealmConfig` with properties to define (define a datasource or reuse the one define by hibernate, define the SQL queries, etc.)
- I can look `SecurityDeploymentProcessor#configureFileRealmAuthConfig` to see how to deploy the feature

I'm good so far? Should I pain attention to other points?

**Comment by loicmathieu** [comment]
For the implementation, you should create a new identity store based on [Elytron Database Identity Store](https://docs.wildfly.org/14/WildFly_Elytron_Security.html#configure-authentication-with-a-database-identity-store) and configure it inside  `io.quarkus.elytron.security.deployment.SecurityDeploymentProcessor`.

As you said, I think it's just providing your realm like it is done in the `SecurityDeploymentProcessor#configureFileRealmAuthConfig`

For a first implementation I assume it's OK to depends on the current Datasource, be careful that you will add a dependency to agroal for this, try to make it optional.
