### ISSUE TITLE
Quoted values within .env files should be interpreted as arbitrary strings

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#35861]
### Describe the bug

Currently, if any value is quoted within a `.env` file, the quotes will be taken into consideration as part of the final value, instead of taking the value as an arbitrary string.

For instance, say a `.env` file looks like:

```properties
DATASOURCE_URL = "jdbc:postgresql://localhost/database"
DATASOURCE_USERNAME = "postgres"
```

When these are referenced in the configuration file the double quotes are preserved.

### Expected behavior

The values should not include the _escaped_ double quotes. For instance: `jdbc:postgresql://localhost/database`

### Actual behavior

Values include the escaped double quotes. For instance: `"jdbc:postgresql://localhost/database"`

### How to Reproduce?

1. Setup a project with JDBC support
2. Create a `.env` file with JDBC_URL (or some other values)
3. Set the value(s) in double quotes
4. Bind the value of the JDBC_URL environment variable into `quarkus.datasource.jdbc.url`
5. Start the application

### Output of `uname -a` or `ver`

```shell
Linux uplink 6.1.50-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 30 Aug 2023 14:44:21 +0000 x86_64 GNU/Linux
```

### Output of `java -version`

```shell
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
```

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

`2.16.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```shell
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.20.1 (Eclipse Adoptium 11.0.20.1+1)
OS:           Linux 6.1.50-1-lts amd64
```

### Additional information

N/A

**Comment by radcortez** [comment]
Unfortunately, we cannot make such a change.

We cannot arbitrarily change user-defined values, because we have no way of knowing if the quotes are meaningful for the user.

Also, if you set an Env Var as `export X="x"`, when you call `System.getenv("x")` you get exactly the value you set with the quotes. Same thing if you set a key-value pair in a properties file.

Which scenario requires you to quote the value and get rid of it in the configuration?

**Comment by x80486** [comment]
I created the issue because all the frameworks/libraries/systems I've worked with interpret the values within the double quotes as arbitrary strings when read from environment variables — so that's the behavior I was expecting from `Quarkus` as well.

The same behavior is observed when working with `.env` files in `Node.js` (`dotenv` and `env-cmd`) and `Go` (`joho/godotenv`) — values in double quotes are interpreted as strings.

Following your example, if you set an environment variable in double quotes (`Linux`, `BSD`, and `macOS`) and try to read it via `System.getenv`, you will get exactly the enclosed value **without** the quotes — because they are meant to escape special characters and such. The following example is what I mean:

```java
[x80486@uplink:~/Workshop/Development/java-contests]$ uname -a 
Linux uplink 6.1.50-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 30 Aug 2023 14:44:21 +0000 x86_64 GNU/Linux
[x80486@uplink:~/Workshop/Development/java-contests]$ export NODE_ENV1=VALUE_NO_QUOTES1
[x80486@uplink:~/Workshop/Development/java-contests]$ export NODE_ENV2="VALUE_NO_QUOTES2"
[x80486@uplink:~/Workshop/Development/java-contests]$ ./gradlew clean test --tests org.acme.EnvVarsTest 
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
...
> Task :classes
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test

BUILD SUCCESSFUL in 4s
13 actionable tasks: 6 executed, 7 up-to-date
[x80486@uplink:~/Workshop/Development/java-contests]$ cat codeabbey/src/test/java/org/acme/EnvVarsTest.java 
package org.acme;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

class EnvVarsTest {
  @Test
  void print() {
    Assertions.assertThat(System.getenv("NODE_ENV1")).isEqualTo("VALUE_NO_QUOTES1");
    Assertions.assertThat(System.getenv("NODE_ENV2")).isEqualTo("VALUE_NO_QUOTES2");
  }
}
```

Could it be that `Quarkus` is reading/managing the `.env` file like a `.properties` file? If that's the case, I think that's probably where the confusion lies.

**Comment by radcortez** [comment]
I also used `System.getenv` directly, but you need to use `'` to be able to set a quoted key with `export`:

```console
🌀 export QUOTED="quoted"
🌀 env | grep QUOTED
QUOTED=quoted
🌀 export QUOTED='"quoted"'
🌀 env | grep QUOTED
QUOTED="quoted"
🌀 jbang envs.java
"quoted"
🌀 node envs.js
"quoted"
```

And scripts:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?

import static java.lang.System.*;

public class envs {

    public static void main(String... args) {
	System.out.println(System.getenv("QUOTED"));
    }
}
```

```javascript
console.log(process.env.QUOTED);
```

**Comment by radcortez** [comment]
I believe the behavior is correct. I'm closing the issue.
