### ISSUE TITLE
GraphQL typesafe client - support for @OidcClientFilter

### ISSUE THREAD

**Issue by rmanig** [quarkusio/quarkus#35878]
### Description

Hi there!
I would like to use the graphql typesafe client in combination with oidc tokens. The current static options to set and use an (authorization) header seem to be too limited for the temporary short-lived access tokens.

Are there any plans to support the `io.quarkus.oidc.client.filter.OidcClientFilter` for example? Which would handle token refreshing as well.
```java
@GraphQLClientApi (configKey = "foo")
@OidcClientFilter ("foo")
public interface FooApi {
   //...
}
``` 

Thanks in advance!

**Comment by sberyozkin** [comment]
Hi @rmanig 

Current OidcClientFilter is HTTP centric, I believe there should be a Quarkus GraphQL specific interceptor which will do the same what what OIDC Client Reactive filter does [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client-reactive-filter/runtime/src/main/java/io/quarkus/oidc/client/reactive/filter/runtime/AbstractOidcClientRequestReactiveFilter.java) - just extend the core OIDC client code but set the token using GraphQL mechanism, except that in case of GraphQL it will be a concrete class. A non-reactive version can be created. I can help Jan or yourself to clarify the details if such an option will be implemented

**Comment by jmartisk** [comment]
I'll try to make some time for this soon and have a look.. I think we'll need a reactive as well as non-reactive variant, and create some way to pass headers into the GraphQL client config as an Uni

**Comment by sberyozkin** [comment]
Hey Jan, you can probably limit it to the preferred reactive option

**Comment by jmartisk** [comment]
Right, it will use the reactive client, but will block waiting for the token

**Comment by rmanig** [comment]
Thanks for having a look! I would love to help, but I'm not really sure if I'm able to or where to start in the graphql-client.

**Comment by jmartisk** [comment]
I'm assuming this will require a whole new extension, just like we have two extensions for the REST client filters... Unless we want to add the OIDC client as a direct dependency of the GraphQL client extension, which we probably don't.

**Comment by jmartisk** [comment]
FYI I have a working prototype but it needs a lot of polishing, and tests, if it goes well I might have some PRs ready by the end of the week
