### ISSUE TITLE
Cannot run an update query outside a transaction, but it's required with good reason

### ISSUE THREAD

**Issue by lamemind-ud** [quarkusio/quarkus#35882]
### Describe the bug

Hello,

it is documented I can run queries without transactions [here](https://quarkus.io/guides/transaction#starting-and-stopping-transactions-defining-your-boundaries) by annotating with @Transactional(NOT_SUPPORTED) or @Transactional(NEVER).

But it doesn't work. The exception is "TransactionRequiredException Executing an update/delete query"

I require to specifically run an update query w/o the transaction and get back the number of updated rows.
**Inside a transaction, the number of affected rows by an update query is only hypothetical, because at commit time, the update query could give different results**. So I really need to bypass the transaction.

I tried in different ways

- @Transactional(NOT_SUPPORTED)  / @Transactional(NEVER) , with @ActivateRequestContext
- getEntityManager().createNativeQuery()

None worked for me
I'm on 2.16.9.Final with panache repositories

maybe I'm missing something, but I googled it and found quite nothing

Many thanks in advance

### Actual behavior

TransactionRequiredException Executing an update/delete query

### Output of `java -version`

java version "17.0.1" 2021-10-19 LTS

### Quarkus version or git rev

2.16.9.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by giovannimartelli** [comment]
+1

**Comment by Naros** [comment]
Hi @lamemind-ud, could you provide a bit more detail about the JDBC driver and the database being used.  If you can also share an explicit use case of the type of update you're applying and the unexpected number of rows versus what you expected, that would be helpful.

**Comment by yrodiere** [comment]
`@Transactional(NOT_SUPPORTED)` / `@Transactional(NEVER)` indeed won't allow you to perform write operations using Hibernate ORM, because we require transactions in that case. We should probably document that better.

As to your "hypothetical number of rows", I was unsure and asked the Hibernate ORM team directly, and the more likely explanation would be some repeatable-read isolation (default on MySQL, MariaDB) that makes the numbers *seem* inconsistent in some cases where concurrent transactions are running (but they actually are correct).

Could you please provide a reproducer?

**Comment by beikov** [comment]
>Inside a transaction, the number of affected rows by an update query is only hypothetical, because at commit time, the update query could give different results. So I really need to bypass the transaction.

@lamemind-ud With SQL databases, there is no such thing as "no transaction". You either have a very short transaction implicitly for that statement (when you use autocommit), or your use an explicit transaction.

There are different transaction isolation levels that might affect the amount of rows that an update query affects, but the fact you're using a short implicit transaction doesn't change the semantics necessarily.

If you want an update query to always produce the same row count across different transaction intersections, you will have to use the repeatable read isolation level.

**Comment by lamemind-ud** [comment]
Ah yes, there's always a lot to learn.

I'm on MySQL, whose transaction isolation level is `REPEATABLE READ` by default.
That's why I was saying _"the number of rows affected by an update query is only hypothetical"_ : that was my empirical deduction. There was a concurrent task updating data after my update, but before the transaction commit.

We set up a new persistence unit, with a transaction isolation level of `SERIALIZABLE`.

Thanks for the assistance.

**Comment by yrodiere** [comment]
Thanks for letting us know!
