### ISSUE TITLE
Devmode with Gradle doesn't work when Gradle Daemon is disabled

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#35890]
### Describe the bug

Devmode with Gradle doesn't work when Gradle Daemon is disabled

User gets error message about unavailable app-dev jar, e.g. `Error: Unable to access jarfile /Users/rsvoboda/tmp/app/build/app-dev.jar`

https://quarkus.io/guides/gradle-tooling doesn't mention that Gradle Daemon is mandatory.

Full log:
```
~/tmp/app$ quarkus dev 
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 7s
7 actionable tasks: 1 executed, 6 up-to-date
Error: Unable to access jarfile /Users/rsvoboda/tmp/app/build/app-dev.jar
```

### Expected behavior

Devmode with Gradle works when Gradle Daemon is disabled.

### Actual behavior

Devmode with Gradle doesn't work when Gradle Daemon is disabled

### How to Reproduce?

Disable Gradle Daemon
 -  Run `mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties` as described in https://docs.gradle.org/current/userguide/gradle_daemon.html#disable_for_a_user, Windows example also included in the document

Run Quarkus CLI
```
quarkus create app app --gradle
cd app
quarkus dev
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle

**Comment by gsmet** [comment]
We haven't heard any complaint from the field of people actually using Gradle so I'm going to close this one.

We can revisit if someone using Gradle for their apps complain about it.
