### ISSUE TITLE
Kotlin + Live Reload + @Valid not working in DEV Mode

### ISSUE THREAD

**Issue by sbert** [quarkusio/quarkus#3591]
**Describe the bug**
If you use @Valid annotation in a rest Method, it doesn't work if hot swap is applied

**To Reproduce**
1. Generate an application with kotlin + Resteasy + quarkus-hibernate-validator
2. Create a data class with validation rules on field 
3. Create your Rest Ressource with a post and add @Valid
4.  Launch your application in dev mode : everything is Ok
5. Change something in your code to force Live Reload
6. The @Valid is ignored

**Sample Code**
You can find an exemple here : https://github.com/sbert/kotlin-valid-live-reload

**Environment (please complete the following information):**
 - GraalVM version (if different from Java): graalvm-ce-19.1.1
 - Quarkus version or git rev: 0.20.0

**Comment by geoand** [comment]
I'll try and take a look at this some time this week

**Comment by sbert** [comment]
Some extra information : 
If I remove : <option>all-open:annotation=javax.ws.rs.Path</option>
And add open to the Resource Class.
When I launch the application the @Valid is ignored

So I think that the live reload problem is the same that : #2811 

To apply @Valid you need to use the maven plugin compiler all-open and it is not used by live reload

**Comment by geoand** [comment]
Yeah, that makes perfect sense. Would you like to take a stab at it?

**Comment by geoand** [comment]
Closing since this looks like a dup of #2811
