### ISSUE TITLE
[rest-client-reactive] Make the chunkSize customizable

### ISSUE THREAD

**Issue by PierreBtz** [quarkusio/quarkus#35915]
### Description

The chunkSize used by the rest-client-reactive is currently a constant: https://github.com/quarkusio/quarkus/blob/cd3dece82a3f99ddc27ebcfca12c6b2e5018ee86/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusHttpPostBodyUtil.java#L31

There are cases (eg server not behaving properly) where being able to customize this size would help.

Would it be possible to make this field customizable?

Relevant tulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/306418-resteasy-reactive/topic/deactivate.20chunked.20mode.20on.20the.20resteasy.20reactive.20client

### Implementation ideas

Transform the code to use a config property for the chunkSize value.

**Comment by geoand** [comment]
If I understand correctly, you want to change the chunked value for data you are sending to a service, correct?

**Comment by PierreBtz** [comment]
Yes, correct :)

**Comment by geoand** [comment]
Can you attach an example application we can use for testing? 

Thanks

**Comment by geoand** [comment]
That would be great, thanks

**Comment by PierreBtz** [comment]
Here you go: https://github.com/PierreBtz/trello-quarkus-upload-attachment, explanations are available in the README, the hardest part is setting up a Trello account to query the Rest API...

**Comment by geoand** [comment]
Thanks! I'll have a look soon

**Comment by PierreBtz** [comment]
Sorry, a bit late to the party. I just tested against the latest SNAPSHOT and it works great, thanks a lot to everybody involved!

**Comment by geoand** [comment]
Thanks for checking!
