### ISSUE TITLE
Add a property to bypass cache mechanism in case of Redis failure

### ISSUE THREAD

**Issue by wilvdb** [quarkusio/quarkus#35925]
### Description

With the current implementation of Redis cache, when Redis is not available, cache mechanism fail and there is no easy way to handle the failure and perform the call. An implementation example:
```java
@Fallback(fallbackMethod = "getBooksByAuthorImpl")
@Transactional
public Books getBooksByAuthor(String author) {
    return getBooksByAuthorInternal(author);
}

@CacheResult(cacheName = "books")
Books getBooksByAuthorInternal(String author) {
    return getBooksByAuthorImpl(author);
}

Books getBooksByAuthorImpl(String author) {
    Log.info("Get books from " + author);
     return new Books(mapper.fromEntities(bookService.getBooksByAuthor(author)));
}
```

### Implementation ideas

The idea could be to add a property, for example `quarkus.cache.redis.enble-failover`, to handle exceptions coming from the connection to Redis, and continue the execution as the value is not yet in cache.

In my use case, Redis is in a standalone mode, so I suggest this property could have effect only if the client is setup in standalone mode.

**Comment by cescoffier** [comment]
#35977 will re-compute the value when a connection to Redis cannot be acquired or fails.
