### ISSUE TITLE
Unable to add additional handling when OIDC provider is not available

### ISSUE THREAD

**Issue by paroparo** [quarkusio/quarkus#35920]
### Describe the bug

I am trying to add additional handling for my app when upon startup it isn't able to connect to my OIDC provider. 
However, when trying to pass a @Observes StartupEvent, the OIDC discovery has already been performed - whether it failed or not. 
Is there a way to have this that when it isn't able to connect to my OIDC provider, I can invoke a customized handling? For example, 
sending message up to a messaging stream, customize logging or system.exit or something else...

![image](https://github.com/quarkusio/quarkus/assets/77258047/2bc7b2c0-f8fd-4975-a0c8-5ad978fb598d)

### Expected behavior

Upon getting the 'Discovery has failed' or the exception: io.quarkus.oidc.common.runtime.OidcEndpointAccessException, I should be able to have a way to catch and invoke a customized handling either sending message up to a messaging stream, customize logging or system.exit or something else...

### Actual behavior

Unable to catch the exception and attempt through @Observes StartupEvent is already after the OIDC discovery stage.

### How to Reproduce?

Reproduce:

1. Configure quarkus app that uses OIDC provider - with jwt or none. 
2. Pass in an unreachable OIDC provider url. 
3. Start app, logs will show similar to the attached image above.

### Output of `uname -a` or `ver`

22.04.1-Ubuntu

### Output of `java -version`

Oracle GraalVM 17.0.8+9.1

### Quarkus version or git rev

Quarkus 3.2.4.Final

**Comment by sberyozkin** [comment]
If the connection has failed at the start up then an attempt to recover will be made at the first request 
Having a security event though can make sense

**Comment by paroparo** [comment]
I see. At the moment, is there a way or a workaround to catch this security event? The only other way I can think of is after this discovery stage, I'll put a health checker request (to the OIDC provider) as a StartupEvent to initiate that attempt to recover.
