### ISSUE TITLE
OIDC - Keycloak: Aborting login screen and random expired tokens results in bad cookie and broken web app

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#35947]
### Describe the bug

I have a demo web application that I'm trying to get working with OIDC (Keycloak) to handle the authentication of users, etc.

I am using the Quarkus-Faces demo application and modified it to work with Keycloak (Dev Services).

Everything works fine until you abort the log in page and instead of entering your username/password you click the back button on the browser to return to the unsecure page.

Once you try to click on any secured links, instead of being asked to log in again, the website is broken with blank pages and 401s and a cookie called `q_auth_` is written to the browser.

The only way to fix the issue is to delete that cookie and then I am asked to log in properly.

Closing the browser doesn't fix it either.. 

This also happens at random times when Quarkus has trouble talking to Keycloak behind the scenes, or I've even seen it when the tokens expire and you attempt to access the secure links again. This is very random but it took me a long time to narrow it down to that one cookie.

I've attached a reproducer to this ticket.

To Test:

1. Unzip project
2. `mvn clean package`
3. `mvn quarkus:dev`
4. Go to `http://localhost:8081`
5. You should see the Primesfaces demo page (this page is not secured)
6. Click on any link on the side menu (these are secured)
7. You will be asked to login into keycloak
8. Use `bob:bob`
9. You will be brought to the page link you clicked
10. You  should now see a LOGOUT button at the top right
11. Click it and you will be properly logged out of Quarkus and Keycloak and brought back to the main page
12. Try to access a menu link again
13. Instead of logging in, click the back button on the browser
14. Look at your cookies and you will see a cookie called `q_auth_` with some characters in the name
15. Try to access any secured link again and site will fail with a blank screen and 401 in the Network traffic
16. Delete the cookie 
17. You can now access the website again

Project Files:
[quarkus-faces-bad-cookie-oidc.zip](https://github.com/quarkusio/quarkus/files/12614534/quarkus-faces-bad-cookie-oidc.zip)

Screen shots:

1. Dashboard

<img width="1870" alt="Screenshot 2023-09-14 at 8 40 39 PM" src="https://github.com/quarkusio/quarkus/assets/5183186/2265ad3d-85ce-4908-b9a9-d049446b76ed">

2. Cookies AFTER logging into Keycloak
<img width="1870" alt="Screenshot 2023-09-14 at 8 41 04 PM" src="https://github.com/quarkusio/quarkus/assets/5183186/4747820c-62d3-47ea-8103-c58663e82b21">

3. Logging out and aborting the login screen - Cookies AFTER aborting login screen (clicking back button)
<img width="1870" alt="Screenshot 2023-09-14 at 8 41 30 PM" src="https://github.com/quarkusio/quarkus/assets/5183186/34ea1e48-34e2-4a99-95cd-5aaa4808a422">

4. Trying to access secured link after aborting login
<img width="1870" alt="Screenshot 2023-09-14 at 8 41 50 PM" src="https://github.com/quarkusio/quarkus/assets/5183186/82cbe1a8-7efb-44de-aea8-f593aabc6d8c">

### Expected behavior

I would expect that if I abort the login process I would be able to restart it again.

Also, if my tokens expire and that cookie is created I shouldn't have to clean out my browser to fix it.

### Quarkus version or git rev

3.3.2

**Comment by tmulle** [comment]
@sberyozkin Thanks for the quick response.. 

Using the `quarkus.oidc.authentication.fail-on-missing-state-param=false` does indeed fix the issue with cancelling the login screen.

I tried it in both FireFox and Safari browsers and it worked as expected.

Question on the wildcard for the KeyCloak redirect, what should it be?

In the KeyCloak Dev  Service it is set to `/*` and in my real application I had it set to `/*` but you're saying that's not recommended and can also be the cause if problems?

So, what is a valid entry? would it just be something like http://localhost:8081/* ?

Thanks again..

**Comment by sberyozkin** [comment]
Hi @tmulle Thanks for the quick confirmation.

And yes, in 3.4.0 it will just work without to explicitly require it. I think if the application is running in a very sensitive setup, some users may not want to ignore the fact the orphaned state cookie on the callback path exists, so 401 would be appropriate in those setups - but it does look like for most cases people just would like to get a new re-authentication screen - which is reasonable. 

In prod, the callback must be a non-wildcard URL, allowing for the variety increases the risk that the user is redirected back to Quarkus not from Keycloak (or other providers). 

Note though if you have a requirement to restore the original request URL, after the callback, Quarkus can do it, in this case you effectively add a virtual callback path, its purpose is to get the Quarkus endpoint white-listed in the provider config, and then tell Quarkus to restore the original path after the provider redirect the user back - we can cover it in Discussions/Zulip if it can be of interest, may be better avoid it while you are starting experimenting with Quarkus OIDC.

As far as the expired tokens are concerned, I've just tested `quarkus-quickstarts/security-openid-connect-web-authentication-quickstart`, you can try too, the session lifetime is extra short there,  the demo just works for the login, `localhost:8080/tokens`. After a few seconds if you retry, the session cookie has already expired so it won't be even sent by the browser and the user is redirected to Keycloak to authenticate again.
Now another case is when one wants to return the expired id token for it to be auto-refreshed, in which case one needs to extend the session cookie age with the property - and Quarkus will auto-refresh, if needed - pro-actively while the token is still valid. All in all, the OIDC session management is its most complex part - so some tuning may be needed and if necessary, fixes. 

So, let me close this issue and look forward to you stressing OIDC more :-)

**Comment by tmulle** [comment]
Hi @sberyozkin sounds good!

Another quick question, and if this is something that should be another ticket let me know.

I'm trying to determine in my JSF page that user is logged in using the following code in my bean.

```java
public boolean isLoggedIn() {

        log.infof("Identity is logged in = %s and has roles %s", !identity.isAnonymous(),identity.getRoles() );
        return identity != null && !identity.isAnonymous();
    }
    ```
    
    Where the `identity` is 
    ```java
    @Inject
    SecurityIdentity identity;
    ```
    
    When I log into the app and visit the secure pages the log shows the user is logged in, but when I go to a public page while still being signed in (cookies in the browsers, etc), that code prints that I'm not logged in.
    
    I have my service bean as @ApplicationScoped so I would think it would be ok? I tried @SessionScoped as well and same thing. 
    
    Any ideas?

**Comment by tmulle** [comment]
Ok so update on the previous question.

Turns out it was a cookie path issue, I had set the `quarkus.oidc.authentication.cookie-path=/secure/` setting for testing the original issue I mentioned.

I noticed in the browser that when I went to the public page, the cookies were gone and came back when I went to the secured link while being signed in.

Changing it back to `/` (the default) fixes the issue.

**Comment by sberyozkin** [comment]
@tmulle Thanks for confirming as I was about to test, note though if you disable the proactive authentication then it would return anonymous identity.

OK, lets continue with other issues/discussions, thanks
