### ISSUE TITLE
Wrong bean metadata injected into interceptor using @Intercepted when using dependent scope

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#3594]
I'm trying to run MP Metrics TCK, in particular `ConcurrentGaugedClassBeanTest` [1]. I am facing an issue that when a `ConcurrentGaugeInterceptor` is being constructed during the test to intercept calls to methods of `ConcurrentGaugedClassBean` [2], wrong bean is injected into its `@Intercepted` injection point [3] - the `bean` parameter should contain the `ConcurrentGaugedClassBean` that is being called, but instead it contains the test that is being run. Therefore the interceptor can't work properly because it can't find the right metric instance which should be updated during the call.
This has something to do with the fact that `ConcurrentGaugedClassBean` has the dependent CDI scope. This issue doesn't occur if I attach any other CDI scope to `ConcurrentGaugedClassBean` in the TCK code. 

So I assume the problem is that when bean A injects a bean B that has a dependent scope, and that bean B has got an interceptor applied, and the interceptor's constructor injects the metadata of the intercepted bean using `@Intercepted`, the bean that gets injected into the interceptor's constructor is not B (the bean being injected), but A - the bean that is injecting B. This differs from the behavior I observe with Thorntail, where `@Intercepted` correctly injects the metadata of B.

How to reproduce:
- Use my branch [4]
- from `quarkus/tcks/microprofile-metrics/api`: `mvn test -Dtest=ConcurrentGaugedClassBeanTest#callCountedMethodsOnce`
You will see the test fail with `java.lang.UnsupportedOperationException` because the concurrent gauge interceptor will receive a `DoesNotHaveMetric` metric resolver, because it will try to locate the metric metadata on the test class instead of the `ConcurrentGaugedClassBean` bean

[1] https://github.com/eclipse/microprofile-metrics/blob/2.0.1/tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugedClassBeanTest.java#L120
[2] https://github.com/eclipse/microprofile-metrics/blob/2.0.1/tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugedClassBean.java
[3] https://github.com/smallrye/smallrye-metrics/blob/2.1.3/implementation/src/main/java/io/smallrye/metrics/interceptors/ConcurrentGaugeInterceptor.java#L56
[4] https://github.com/jmartisk/quarkus/commits/metrics-tck-interceptor-reproducer

**Comment by jmartisk** [comment]
@mkouba @manovotn  please look, and if something is not clear, I will try to explain further

**Comment by manovotn** [comment]
Hmm, that's interesting.
If I play around with existing [test](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/intercepted/InterceptedBeanInjectionTest.java) and try to simulate the scenario, it works just fine.

And [this class](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/InterceptedBeanMetadataProvider.java) is what should resolve the IP in case its intercepted bean metadata.

I'll poke around it some more tomorrow...

**Comment by manovotn** [comment]
@jmartisk rebase your branch against master so that you have [this PR included](https://github.com/quarkusio/quarkus/pull/3546). With that in place, the test passes for me. So by the looks of it, I already "accidentally" fixed this prior to this issue creation :-D

**Comment by manovotn** [comment]
Hmm, so the problem seems to occur only when an interceptor uses the `@Intercepted` metadata more then once - e.g. when you have `@AroundInvoke` and `@AroundConstruct` on the same interceptor.

I think it is still linked to the previously mentioned issue - #3530 
Apparently I missed post/around construct interceptors as bytecode for those is generated elsewhere and currently different instances are still used for each of those invocations. But fixing that gave me different errors. I am trying to figure out a proper fix for all that.
