### ISSUE TITLE
PathParam URL encoded in quarkus-resteasy-reactive since quarkus 3.2.x

### ISSUE THREAD

**Issue by rubensa** [quarkusio/quarkus#35960]
### Describe the bug

I have a **Resource** like:

```java
@Path("/base/{name}/objects/{key:.*}/func")
public class BaseResource {

  @GET
  @Produces({ "application/json" })
  public Response runFunc(@PathParam("name") String name,@PathParam("key") String key) {
  }
}
```

When using **quarkus-resteasy-reactive** if the **Resource** is called with a URL like:

`/base/name1/objects/path/to/my/object/func`

the content of the `key` **PathParam** is:

`path%2Fto%2Fmy%2Fobject`

instead of:

`path/to/my/object`

This is happening in **quarkus 3.2.5** and **3.3.2** but is working in **quarkus 2.16.10.Final**, **3.0.4** and **3.1.3.Final**.

On **quarkus 3.2.5** if I use **quarkus-resteasy** (no reactive) it is also working as expected (so looks like the way to parse the **PathParam**s is different).

**_NOTE_**: I also tried adding `@Encoded` annotation but the result is the same.
**_NOTE_**: [This](https://issues.redhat.com/browse/RESTEASY-3291) bug might be related but I can't find the match among [RESTeasy](https://github.com/resteasy/resteasy) code and [quarkus-resteasy-reactive](https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-reactive) code.

### Expected behavior

To not encode the **PathParam**.

### Actual behavior

The **PathParam** was encoded.

### How to Reproduce?

Look at the sample code above.

### Output of `uname -a` or `ver`

Linux nx-links.local.computer 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.5 and 3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

**Comment by rubensa** [comment]
https://github.com/quarkusio/quarkus/issues/30577 might be related to this.

**Comment by rubensa** [comment]
https://github.com/quarkusio/quarkus/issues/24974 might also be related to this.

**Comment by geoand** [comment]
@rubensa can you share a sample application with a corresponding test that behaves as you describe?

That would be super useful in pinpointing the exact version in which the change started to manifest.

**Comment by rubensa** [comment]
[Here](https://github.com/rubensa/quarkus-resteasy-reactive-bug) I prepared a sample project.

You can use it via **[VSCode](https://code.visualstudio.com/)** with the **[Remote Development](https://code.visualstudio.com/docs/remote/remote-overview)** extension pack and **[Docker](https://www.docker.com/)**, via **[GitHub Codespaces](https://docs.github.com/en/codespaces)** or locally if you have **GraalVM** installed (in the provided **Docker** container for **VSCode** and **Codespaces**, **Mandrel** 23.0 for **Java** 17 is used).

As you can see in the [README](https://github.com/rubensa/quarkus-resteasy-reactive-bug/blob/main/README.md):

> The code is configured to use Quarkus 3.4.1 version with quarkus-resteasy-reactive.
> 
> I you run the provided test it (running `./mvnw test`) it will fail.
> 
> You can check that it works if you replace `quarkus.platform.version` from `3.4.1` to `3.1.3.Final` in pom.xml.
> 
> It will also work if you keep `quarkus.platform.version` as `3.4.1` but use the non-reactive **quarkus-resteasy** by replacing `quarkus-resteasy-reactive` with `quarkus-resteasy` and `quarkus-resteasy-reactive-jackson` with `quarkus-resteasy-jackson` in pom.xml.
> 


Setting up the sample project I just realized that it does not only "URL encodes" the **PathParam** but the match for the `key` in the `@Path` is not correctly resolved.

In the sample above, If you request `/base/quarkus.test.sample/objects/data/test.txt/func`, `name` is correctly resolved to `quarkus.test.sample` but `key`is incorrectly resolved to `base%2Ftest.txt/func/base/quarkus.test.sample/objects/data%2Ftest.txt` (where it should have been resolved to `data/test.txt` or `base%2Ftest.txt` if you assume the encoding problem).


Just let me know if you need anything else.

**Comment by geoand** [comment]
Thanks a lot.

I'll be mostly off next week, so I'll likely check this the week after.

**Comment by rubensa** [comment]
Hi @geoand 

Did you have some time to check this? :thinking:

**Comment by geoand** [comment]
Hi,

Unfortunately something that requires my ful and individed attention for the few weeks (at least) has come up, so other things have been pushed down.

**Comment by rubensa** [comment]
Thanks for the info.

Hopes you have some time to check in the near future.

**Comment by rubensa** [comment]
Hi @geoand 

Any news on this?  For now I'm using **quarkus-resteasy** but I'd like to go back to use **quarkus-resteasy-reactive**.

**Comment by geoand** [comment]
I have been doing some high priority stuff lately and have not had time to look into his yet.
Hopefully soon.

**Comment by geoand** [comment]
I have not yet looked at it unfortunately. 

@rmartinc if you have a general fix in mind, by all means open a PR :)

**Comment by rmartinc** [comment]
> @rmartinc if you have a general fix in mind, by all means open a PR :)

@geoand I just sent PR https://github.com/quarkusio/quarkus/pull/37513. The idea is saving the path params encoded instead of decoded. That way the initial issue https://github.com/quarkusio/quarkus/issues/34586 can be fixed doing the decoding after the split.

**Comment by geoand** [comment]
Thanks!
