### ISSUE TITLE
SSE: Reactive SseEventSource client doesn't consume empty events

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#35966]
### Describe the bug

When using `quarkus-rest-client-reactive-*`, `InboundSseEvent`s with an empty data block aren't consumed by the `SseEventSource`. Using `quarkus-rest-client-*` (without reactive) solves this.

### How to Reproduce?

Assuming you have the following SSE stream:

```
curl localhost:8080/updates -i
HTTP/1.1 200 OK
Content-Type: text/event-stream
transfer-encoding: chunked



event: VALIDATED
data: {"test":"123"}

event: STARTED
data: {"test":"234"}

event: UPDATED
data:

event: STOPPED
data:
```

With `quarkus-rest-client-reactive-jsonb`, the following test results in only two consumed events:

```java
@Test
void test() {
    Client client = ClientBuilder.newClient();

    WebTarget target = client.target("http://localhost:8080/updates");
    SseEventSource eventSource = SseEventSource.target(target).build();

    eventSource.register(ev -> {
        System.out.println("ev.isEmpty() = " + ev.isEmpty());
        System.out.println("event: " + ev.getName() + " " + ev.readData());
    }, thr -> {
        thr.printStackTrace();
    });

    eventSource.open();

    System.out.println("opened");
    LockSupport.parkNanos(200_000_000_000L);

    eventSource.close();
    client.close();
}
```

Result:

```
opened
ev.isEmpty() = false
event: VALIDATED {"test":"123"}
ev.isEmpty() = false
event: STARTED {"test":"234"}
```

With `quarkus-rest-client-jsonb`, all the events show up as expected:

```
opened
ev.isEmpty() = false
event: VALIDATED {"test":"123"}
ev.isEmpty() = false
event: STARTED {"test":"234"}
ev.isEmpty() = true
event: UPDATED
ev.isEmpty() = true
event: STOPPED
```

### Quarkus version or git rev

3.2.0.Final

**Comment by geoand** [comment]
Thanks for reporting!

Any chance you can upload a small sample that reproduces the described behavior?

**Comment by sdaschner** [comment]
Sure, added a branch: https://github.com/sdaschner/quarkus-playground/tree/sse-issue-35966

To reproduce:

```
git clone # with branch https://github.com/sdaschner/quarkus-playground/tree/sse-issue-35967
cd .../server/
mvn quarkus:dev

# new terminal
cd .../client/
mvn clean package
java -jar target/quarkus-app/quarkus-run.jar
```

When switching the pom to use -reactive, the result shows fewer events.

**Comment by geoand** [comment]
Thanks!

https://github.com/quarkusio/quarkus/pull/35990 fixes the behavior of `quarkus-rest-client-reactive`
