### ISSUE TITLE
Jaeger extension end of life and move to Quarkiverse

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#35984]
### Description

The Jaeger extension is on end of life.
No new features will be added and it's role is now filled by `quarkus-opentelemetry'.
The extension will be removed from the Quarkus main repo and moved to Quarkiverse where it will be updated if bugs, security vulnerabilities or weaknesses are found.

This was triggered by this discussion: https://groups.google.com/g/quarkus-dev/c/C2b45e5l6l0/m/d7d-VrHpGQAJ

**Comment by gsmet** [comment]
I'll handle this as part of the effort to get rid of Okhttp in our BOM.
