### ISSUE TITLE
The new HTTP layer depends on Jackson and Jackson Databind

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3600]
- vertx-core depends on Jackson Core
- quarkus-vertx depends on Jackson Databind

so the new Vert.x web layer brings Jackson in virtually every apps.

Is it really what we want?

**Comment by soberich** [comment]
@gsmet There are couple of things which I would like to bring to your attention. 
Jackson is de facto standard and I am super happy as many others I believe that Quarkus supports it. To be honest I don't think it would've be viable to NOT to support it.
On the other hand we have this https://issues.jboss.org/browse/RESTEASY-2327
...

**Comment by gsmet** [comment]
It’s not about not supporting it: we want to support it. 

What we do not want is it being a dependency of our low level layers.

**Comment by soberich** [comment]
@gsmet Could you please comment also on the scope of the issue I raised for Resteasy (link above). I am a bit surprised that such a dependency hell is been ignored for so long (for years overall). Or am I missing something..? Maybe this is not important at all?

**Comment by geoand** [comment]
@gsmet did some initial digging and it seems hard to remove the Jackson dependency for the time being. I will do some investigation, but we might have to wait for Vert.x 4.x

**Comment by gsmet** [comment]
FWIW, the issue is that the native image requires Jackson in the classpath as the codec is registered in Vert.x.

**Comment by geoand** [comment]
Perhaps @gsmet we could use a custom `io.vertx.core.eventbus.impl.CodecManager`. But that seems very heavy handed and who know what other problems we might encounter...

**Comment by gsmet** [comment]
This has been solved.

**Comment by geoand** [comment]
Closed via #4412
