### ISSUE TITLE
Dev mode hangs when graceful shutdown active

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#36006]
### Describe the bug

With config 
```
quarkus.shutdown.timeout=PT60S
```
the application hangs for 60s when changes have been made with this message:
```
2023-09-19 09:52:01,808 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Restarting quarkus due to changes in GreetingResource.class.
2023-09-19 09:52:01,810 INFO  [io.qua.ver.htt.run.fil.GracefulShutdownFilter] (Quarkus Main Thread) Waiting for HTTP requests to complete
```

The behavior is the same on 2.14, 2.15, 2.16, 3.0, 3.1, 3.2, 3.2.

Since dev mode works by detecting changes on incoming request and restarting before the request is processed this behavior is maybe the correct behaviour.
In that case there should be a warning in [the docs](https://quarkus.io/guides/lifecycle#graceful-shutdown) or even in the console.

### Expected behavior

The application is rebuilt immediately and the request is processed. 

### Actual behavior

The application hangs until the shutdown timeout occurs.

### How to Reproduce?

* Generate a quickstart with jaxrs 
* Add `quarkus.shutdown.timeout=PT60S` to application.properties
* mvn quarkus:dev
* Run a request in the browser
* make a change in the project.
* Run another request.

### Output of `uname -a` or `ver`

linux

### Output of `java -version`

17

### Quarkus version or git rev

> 2.14.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
Very interesting indeed. 

An alternative would be to disregard `quarkus.shutdown.timeout` in dev-mode.
