### ISSUE TITLE
grpc protoc gen can not work on apple m2 chip

### ISSUE THREAD

**Issue by JackyAnn** [quarkusio/quarkus#36005]
### Describe the bug

It worked fine on my macbook air m1 chip, but didn't work on my macbook pro m2 chip

```
/Users/jacky/Workspace/work/doorlink/iot-server/service/build/io.grpc-protoc-gen-grpc-java-osx-aarch_64-exe: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':service:quarkusGenerateCode'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.CodeGenWorker
      > Failed to generate sources in the QuarkusPrepare task for ltd.doorlink:service:1.0.0 due to java.lang.reflect.InvocationTargetException
```

### Output of `uname -a` or `ver`

Darwin jacky-mac.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 Welcome to Gradle 8.3!  Here are the highlights of this release:  - Faster Java compilation  - Reduced memory usage  - Support for running on Java 20  For more details see https://docs.gradle.org/8.3/release-notes.html   ------------------------------------------------------------ Gradle 8.3 ------------------------------------------------------------  Build time:   2023-08-17 07:06:47 UTC Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5  Kotlin:       1.9.0 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          20.0.2 (Oracle Corporation 20.0.2+9-78) OS:           Mac OS X 13.5.2 aarch64

**Comment by JackyAnn** [comment]
<img width="670" alt="image" src="https://github.com/quarkusio/quarkus/assets/3381801/e4d6bfce-ba10-441c-8ade-6aad11998d43">

**Comment by cescoffier** [comment]
Unfortunately, it means that protoc is not compatible with your architecture. I would recommend opening an issue in the protoc project to ask if they can / will provide a compatible executable. 

Quarkus is just consuming the artifacts. So, we can’t do much.
