### ISSUE TITLE
Not possible to use SecurityIdentity in HttpServerMetricsTagsContributor

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#36015]
### Describe the bug

When using `HttpServerMetricsTagsContributor` to provide extra tags for http metrics, it is not possible to get hold of `SecurityIdentity` as the request context is no longer active (or looks like that) and fails with `java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1`. 

### Expected behavior

It should be possible to use SecurityIdentity to add information into the metrics such as tenant id and similar.

### Actual behavior

Fails with `java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1` while trying to access the identity which might be too early terminated as the request was authenticated.

### How to Reproduce?

Implement `HttpServerMetricsTagsContributor` that injects the security identity and retrieves principal and attribute from it.

````
@ApplicationScoped
public class SampleHttpServerMetricsTagsContributor implements HttpServerMetricsTagsContributor {

    @Inject
    SecurityIdentity identity;

    @ActivateRequestContext
    public Tags contribute(Context context) {
        List<Tag> tags = new ArrayList<>();
            if (!identity.isAnonymous()) {

            tags = Arrays.asList(
                    Tag.of("tenantId", identity.getPrincipal().getName()),
                    Tag.of("tenantName", identity.getAttribute("tenantName")));

            }
        return Tags.of(tags);
    }
}

````

Make any request to http endpoint so metics are recorded.

### Output of `uname -a` or `ver`

Darwin 22.6.0 Darwin Kernel Version 22.6.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by mswiderski** [comment]
@geoand if I am not mistaken you worked on `HttpServerMetricsTagsContributor` so would like to get you opinion if this use case makes sense or is there any other way to get this working.

**Comment by geoand** [comment]
@mswiderski this almost certainly happens because `HttpServerMetricsTagsContributor#contribute` is called when the request has been completed, so there is no actual request from which to obtain the security information.

I currently don't see a way to do this, but I'll have to think about it.

**Comment by mswiderski** [comment]
thanks @geoand let me know if I can be of any help here.

I was wondering if `RoutingContext.user()` is still there but couldn't figure out if `RoutingContext` is still available there.

**Comment by geoand** [comment]
That would have the same problem

**Comment by geoand** [comment]
There doesn't seem to be any good solution for accessing `@RequestScoped` beans. That's because the methods in `io.vertx.core.spi.metrics.HttpServerMetrics` get called outside the boundaries of where Quarkus / Arc can be used.

**Comment by geoand** [comment]
There is a very hacky way to do what you want however... 

You essentially need to set a Vert.x context local variable in some filter that runs after security (a Jakarta REST filter would be fine here) and then pull that field out of thje Vert.x local context in `contribute`.
This would also involve the very brittle downcasting from  `HttpServerRequest` to `HttpServerRequestInternal` .

FWIW, we also do a similar trick in the codebase, see the usage of `"UrlPathTemplate"` in the repo.

**Comment by geoand** [comment]
So I am going to close this one as `won't fix`

**Comment by mswiderski** [comment]
thanks @geoand for in-depth investigation. That was kind of what I was afraid of - outside of the quarkus code base to make this work. Even though there is a "way" to do it it does not seem to be safe way as these stuff can change.

I will go ahead and instead of adding extra tags to the http metrics emit my own specific metrics and rely on them instead.
once again thanks!

**Comment by geoand** [comment]
> Even though there is a "way" to do it it does not seem to be safe way as these stuff can change

It certainly can change, but it's unlikely to happen without a major Vert.x version bump.

> thanks @geoand for in-depth investigation

🙏🏼

**Comment by davidreis97** [comment]
@geoand It's been a year since this topic was mentioned, how's this looking in the current landscape?

I ask because it seems pretty limiting and counter-intuitive to me that a `HttpServerMetricsTagsContributor`, which according to the docs is meant to allow for the creation of tags on request specific information, cannot access `@RequestScoped` beans.

**Comment by geoand** [comment]
Nothing has changed AFAIK
