### ISSUE TITLE
Disable Kubernetes Extension

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#36017]
### Describe the bug

I want to disable the Kubernetes extension in the `test` profile, but I do still want it during `prod`. (It seems to be using a lot of memory and I'm not utilizing it during tests anyway.) Is there anyway to do this?

I tried:

```yaml
"%test":
  quarkus:
    kubernetes:
      enabled: false
```

But this doesn't seem to work. I would think there must be a way to disable different extensions for different profiles.

### Expected behavior

The extension is disabled

### Actual behavior

The extension is not disabled

### Output of `java -version`

17

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by geoand** [comment]
What exactly are you trying to disable?

**Comment by mikethecalamity** [comment]
The whole extension from running.

**Comment by geoand** [comment]
@gsmet didn't you have a similar request? Did we end up addressing it in Quarkus 3?

**Comment by mikethecalamity** [comment]
Looks like the Kubernetes extension doesn't kill my `@QuarkusTest` when using Quarkus 3. I'll close this and wait until my project is finished being upgraded to Quarkus 3.
