### ISSUE TITLE
AWS: amazon-lambda-rest and amazon-lambda-http extensions contain duplicate class names

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#36013]
### Description

For example, you can find the `io.quarkus.amazon.lambda.http.deployment.AmazonLambdaHttpProcessor` in the [deployment module of amazon-lambda-http](https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-http/deployment/src/main/java/io/quarkus/amazon/lambda/http/deployment/AmazonLambdaHttpProcessor.java) but also in the [deployment module of amazon-lambda-rest](https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/deployment/src/main/java/io/quarkus/amazon/lambda/http/deployment/AmazonLambdaHttpProcessor.java).

The same applies to the runtime modules. Compare https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-rest/runtime/src/main/java/io/quarkus/amazon/lambda/http/IAMPrincipal.java and https://github.com/quarkusio/quarkus/blob/main/extensions/amazon-lambda-http/runtime/src/main/java/io/quarkus/amazon/lambda/http/IAMPrincipal.java.

### Implementation ideas

Rename the packages/update the class names.

**Comment by patriot1burke** [comment]
Yeah so?  I like it that way
