### ISSUE TITLE
Dev UI: Info needs to know which git commit id selects

### ISSUE THREAD

**Issue by ramiswailem** [quarkusio/quarkus#36027]
### Describe the bug

The Git info show "Commit  [object Object]" instead of the git last commit id.

### Expected behavior

Commit fc2680156594387e0571db425ff7bc7304ed1f46

### Actual behavior

Commit  [object Object]

<img width="406" alt="Screenshot 2023-09-20 at 10 53 53" src="https://github.com/quarkusio/quarkus/assets/26059392/ecfcbe17-ca3b-4506-8dff-7a1e8fab7ee9">

### How to Reproduce?

run dev mode and goto http://localhost:8080/q/dev-ui/io.quarkus.quarkus-info/information

### Output of `uname -a` or `ver`

Darwin dev-mac 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.4.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

### Additional information

latestCommitId is a string:

[commit.put("id", latestCommitId);](https://github.com/quarkusio/quarkus/blob/e929e657765f557e1ac77ad881cabad454b54bd1/extensions/info/deployment/src/main/java/io/quarkus/info/deployment/InfoProcessor.java#L85C46-L85C46)

and when full info needed, id is a hash map:

https://github.com/quarkusio/quarkus/blob/e929e657765f557e1ac77ad881cabad454b54bd1/extensions/info/deployment/src/main/java/io/quarkus/info/deployment/InfoProcessor.java#L110

<tr><td>Commit</td><td>${git.commit.id}</td></tr>:

https://github.com/quarkusio/quarkus/blob/e929e657765f557e1ac77ad881cabad454b54bd1/extensions/info/deployment/src/main/resources/dev-ui/qwc-info.js#L125C30-L125C78

**Comment by phillip-kruger** [comment]
Thanks. I'll have a look

**Comment by ramiswailem** [comment]
Thank you @phillip-kruger 

I have this option in my 'application.properties'

`quarkus.info.git.mode=full`
