### ISSUE TITLE
Apache Camel version in io.quarkus.platform:quarkus-camel-bom is older in 3.3.3/3.4.0-RC1/main than in 3.2.6.Final

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#36028]
### Describe the bug

Hi!

Is there a reason why the version of Apache Camel is set to `4.0.0` in [quarkus-camel-bom from Quarkus 3.2.6.Final](https://github.com/quarkusio/quarkus-platform/blob/6ad953a387d10ca141e50357cb2a9396a9fd5b81/generated-platform-project/quarkus-camel/bom/pom.xml#L6360-L6364) while that same version is set to `4.0.0-RC2` in [Quarkus 3.3.3 or 3.4.0-RC1](https://github.com/quarkusio/quarkus-platform/blob/b9e07820b38e1251cf6f36070ec69df16a2214f5/generated-platform-project/quarkus-camel/bom/pom.xml#L6380-L6384) and the [main](https://github.com/quarkusio/quarkus-platform/blob/e3725c1cb84de13ec70ec0911989060f1f4fb16a/generated-platform-project/quarkus-camel/bom/pom.xml#L6379-L6383) branch?

### Expected behavior

Apache Camel version should be `4.0.0` in Quarkus `3.4.0` and in the `main` branch.

**Comment by gsmet** [comment]
No good reason. The Camel team created the 3.2 backport first and the 3.3 backport didn't get into 3.3.3 as we reduced the changes pushed to this version to the minimum due to the CVE.

I will not release any new 3.3 as 3.4 is coming today.

**Comment by gwenneg** [comment]
Quarkus 3.4.0 will still rely on Camel 4.0.0-RC2, right?

If so, will Camel be upgraded to `4.0.0` in Quarkus 3.4.1?

**Comment by gsmet** [comment]
3.4.0 won’t be released fully, it has the CVE. 

I’m currently releasing 3.4.1 which updates to Camel Quarkus 3.4.0, which probably comes with a final of Quarkus (on my phone, can’t check).
