### ISSUE TITLE
Quarkus static image building with AWT

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#36026]
### Description

Hello Quarkus Team,

i just migrated from Quarkus 2 to Quarkus 3 and have problems regarding AWT, as you may have seen from other issues i reported on the Quarkus AWT extension. But now i am a bit lost on the topic of static image building regarding AWT.
On Quarkus 2 a statically linked native image was easily built even using AWT and our service runs fine with it. But with the upgrade to Quarkus 3 and the new GRAALVM version, it seems that the static image is not statically linked against AWT anymore.

My statically linked native image with AWT Extension is building fine, but during runtime i get the following error:

```
Caused by: java.lang.UnsatisfiedLinkError: no awt in java.library.path
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136)
        at java.base@17.0.8/java.lang.ClassLoader.loadLibrary(ClassLoader.java:50)
        at java.base@17.0.8/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base@17.0.8/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop@17.0.8/java.awt.image.ColorModel$1.run(ColorModel.java:210)
        at java.desktop@17.0.8/java.awt.image.ColorModel$1.run(ColorModel.java:208)
        at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:171)
        at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop@17.0.8/java.awt.image.ColorModel.loadLibraries(ColorModel.java:207)
        at java.desktop@17.0.8/java.awt.image.ColorModel.<clinit>(ColorModel.java:220)
        at java.desktop@17.0.8/java.awt.image.Raster.<clinit>(Raster.java:172)
        ...
```

Since i dont know if this is a bug, my fault in doing something wrong or i have to do something else, i would really appreciate if you could add some documentation on the AWT extension regarding required .so or .dll files i have to put into the runtime container if i have an statically linked native image. Usually i have a scratch docker container where i put my application and it runs standalone with some config files. But now i don`t know what to exactly put in, to get it running again.

Could you please help me / add more documentation to it?

**Comment by geoand** [comment]
cc @Karm

**Comment by antonwiens** [comment]
Ok, i managed to get my backend service working with AWT and static image building without relying on quarkus AWT extension, as this was messing with the static image. I am not using visual awt features as i need awt only for pdfbox.

Thats what i did:
- Removed quarkus-awt extension
- add to build config: --initialize-at-run-time=sun.awt.X11,sun.awt.dnd,java.awt.event,com.apple.eawt,sun.awt.X11GraphicsConfig
- add a class named io.quarkus.awt.runtime.JDKSubstitutions so that quarkus does not substitute the awt classes

Thats it, now PDFbox and awt work for me in the backend service to generate pdf files without relying on quarkus-awt. 
I think this works because pdfbox is a special case in combination with static image compilation. But i am fine with it.
When building static, AWT seems to have less of a problem with relying on .so files and jni configuration.

**Comment by Karm** [comment]
Hello @antonwiens, the problem with not doing things in https://github.com/quarkusio/quarkus/blob/main/extensions/awt/deployment/src/main/java/io/quarkus/awt/deployment/AwtProcessor.java is that it could blow up at runtime if you deal with unexpected data that, e.g. trigger an exception that is instantiated from JNI.

So while your workaround might work, it could be dangerous.

Ad files: As per GraalVM's decision, graphics related libs are not statically linked any more.

Quarkus deals with that by packing them next to the created executable for you.

The result is that where you copied 1 file, you have to copy libs as well now, e.g. 
https://github.com/quarkusio/quarkus-quickstarts/blob/main/awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native#L31

**Comment by Karm** [comment]
Closing it as this is a proverbial "feature, not a bug".  I will try to find a place where to note the fact about the libs better.

**Comment by antonwiens** [comment]
Hi, i have a lot of integrationtests for everything, and in the statically linked native image everything works fine, without copying any libs to the application image. But thanks for your explanation.

**Comment by flaviodotcom** [comment]
Hey! I ran into the same problem and got it working using the camel-quarkus-pdf extension with Quarkus 3.18.

Also, make sure your .dockerignore isn’t messing things up. In my case, it was excluding the .so files needed at runtime. Here’s what worked for me:

_.dockerignore_
```
*
!target/*-runner
!target/*-runner.jar
!target/*.so
!target/lib/**
!target/quarkus-app/**
```

After that, everything worked fine in native mode inside the Docker container.



> ### Description
> Hello Quarkus Team,
> 
> i just migrated from Quarkus 2 to Quarkus 3 and have problems regarding AWT, as you may have seen from other issues i reported on the Quarkus AWT extension. But now i am a bit lost on the topic of static image building regarding AWT. On Quarkus 2 a statically linked native image was easily built even using AWT and our service runs fine with it. But with the upgrade to Quarkus 3 and the new GRAALVM version, it seems that the static image is not statically linked against AWT anymore.
> 
> My statically linked native image with AWT Extension is building fine, but during runtime i get the following error:
> 
> ```
> Caused by: java.lang.UnsatisfiedLinkError: no awt in java.library.path
>         at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136)
>         at java.base@17.0.8/java.lang.ClassLoader.loadLibrary(ClassLoader.java:50)
>         at java.base@17.0.8/java.lang.Runtime.loadLibrary0(Runtime.java:818)
>         at java.base@17.0.8/java.lang.System.loadLibrary(System.java:1989)
>         at java.desktop@17.0.8/java.awt.image.ColorModel$1.run(ColorModel.java:210)
>         at java.desktop@17.0.8/java.awt.image.ColorModel$1.run(ColorModel.java:208)
>         at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:171)
>         at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:318)
>         at java.desktop@17.0.8/java.awt.image.ColorModel.loadLibraries(ColorModel.java:207)
>         at java.desktop@17.0.8/java.awt.image.ColorModel.<clinit>(ColorModel.java:220)
>         at java.desktop@17.0.8/java.awt.image.Raster.<clinit>(Raster.java:172)
>         ...
> ```
> 
> Since i dont know if this is a bug, my fault in doing something wrong or i have to do something else, i would really appreciate if you could add some documentation on the AWT extension regarding required .so or .dll files i have to put into the runtime container if i have an statically linked native image. Usually i have a scratch docker container where i put my application and it runs standalone with some config files. But now i don`t know what to exactly put in, to get it running again.
> 
> Could you please help me / add more documentation to it?
> 
> ### Implementation ideas
> _No response_
