### ISSUE TITLE
Quarkus CLI stopped working with error "Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json"

### ISSUE THREAD

**Issue by springified** [quarkusio/quarkus#36031]
### Describe the bug

None of the quarkus CLI seems to be working. 

```
quarkus --version
[jbang] [ERROR] Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details
```

------
**Quarkus Version**
Installed version  Quarkus 3.3.3

**Java Version**
java --version
openjdk 22-ea 2024-03-19
OpenJDK Runtime Environment (build 22-ea+12-877)
OpenJDK 64-Bit Server VM (build 22-ea+12-877, mixed mode, sharing)

**Jbang Version**
jbang --version
0.110.1

**OS **
Mac OS 13.5.2 

### Expected behavior

CLI should work 

### How to Reproduce?

Enter any of the CLI 

### Output of `uname -a` or `ver`

Darwin Prabhas-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "22-ea" 2024-03-19 OpenJDK Runtime Environment (build 22-ea+12-877) OpenJDK 64-Bit Server VM (build 22-ea+12-877, mixed mode, sharing)

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

quarkus

**Comment by gsmet** [comment]
I tried to reproduce it and couldn't. Can you access https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json ?

**Comment by gsmet** [comment]
@iocanel is this download related to the plugins? If so, I don't think it should be a fatal error.

**Comment by iocanel** [comment]
The error is related to the plugins. However, I don't think that it should be fatal as it only affects the plugins coming from our jbang catalog.

**Comment by springified** [comment]
It appears the issue is sporadic. at the time of the issue, the URL (https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json ) is accessible from browser. only quarkus cli fails.  But i am not sure why the issue is not reproducible now to me as well.

**Comment by maxandersen** [comment]
@springified can you run with --verbose to get the full stacktrace ?

**Comment by iocanel** [comment]
I can't see how after https://github.com/quarkusio/quarkus/commit/927f7a851933443e8dd9662732874df87af71927 this issue can occur and I even debugged that main branch to verify that JBangCatalogService & JBangSupport are not even initialized when running standard commands.

Anyway, I'll wrap the the calls to jbang in try / catch though I am not really sure if this is the root cause.

**Comment by gsmet** [comment]
I think this can be closed.
