### ISSUE TITLE
Cannot use quarkus-resteasy-reactive together with quarkus-resteasy-qute

### ISSUE THREAD

**Issue by xalmam** [quarkusio/quarkus#36042]
### Describe the bug

I am using quarkus-resteasy-qute and want to add quarkus-resteasy-reactive. 
When using both libraries together it complains about the conflict as follows:

"(main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.CapabilityAggregationStep#aggregateCapabilities threw an exception: java.lang.IllegalStateException: 
		Please make sure there is only one provider of the following capabilities:
capability io.quarkus.rest is provided by:
  - io.quarkus:quarkus-resteasy-reactive:3.3.3
  - io.quarkus:quarkus-resteasy:3.3.3
"

exclusion did not work:

  <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-qute</artifactId>
    <exclusions>
      <exclusion>
        <artifactId>io.quarkus</artifactId>
        <groupId>quarkus-resteasy</groupId>
      </exclusion>
    </exclusions>
  </dependency>

### Expected behavior

No conflict

### Actual behavior

When starting the application, I get the following exception:
Please make sure there is only one provider of the following capabilities:
capability io.quarkus.rest is provided by:
  - io.quarkus:quarkus-resteasy-reactive:3.3.3
  - io.quarkus:quarkus-resteasy:3.3.3

### How to Reproduce?

1. Create a new project with: 
mvn io.quarkus.platform:quarkus-maven-plugin:3.3.3:create \
 -DprojectGroupId=org.tst \
 -DprojectArtifactId=rest-reactive-quickstart \
 -DclassName="org.tst.rest.client.QuteResource" \
 -Dpath="/qutes" \
 -Dextensions="quarkus-resteasy-reactive,quarkus-rest-client-reactive-jackson,quarkus-resteasy-qute"
 
2. cd rest-reactive-quickstart

3. ./mvnw quarkus:dev

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by geoand** [comment]
This is by design.

There is a RESTEasy Reactive specific Quite extension
