### ISSUE TITLE
Allow class excludes for indexing third party dependencies

### ISSUE THREAD

**Issue by tandraschko** [quarkusio/quarkus#3606]
Currently it's possible to index third party dependencies with:

quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=

it would be great to enhance this config by something like excludeClasses=**/*Tag.class,**/*Blub.class
as those classes may required unused dependencies

**Comment by loicmathieu** [comment]
It may also be interesting to be able to only index some classes (or a single classes)

**Comment by tandraschko** [comment]
Still up to date 😁

**Comment by stuartwdouglas** [comment]
This is likely addressed by https://github.com/quarkusio/quarkus/commit/54af257ec4b1a101669554744b6452fcfa3f4540
