### ISSUE TITLE
Property `quarkus.test.native-image-profile` not working correctly anymore

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#36073]
### Describe the bug

We use the property `quarkus.test.native-image-profile=test` so that for the `integrationTests` the runtime-properties are used the same as for the test profile.

In the application properties this looks as following:

```properties
%test.value.test=TESTVALUE
quarkus.test.native-image-profile=test
```
With Quarkus 3.4.1 this now fails the integration tests with follwing message:

```
2023-09-21 15:11:17,329 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile 'prod' used to build the native image is different from the runtime profile 'test'. This may lead to unexpected results.
Failed to load config value of type class java.lang.String for: value.test
```

### Expected behavior

With Quarkus 3.3.3 this worked correctly, reading the `value.test` for the integration tests.

### How to Reproduce?

Reproducer:

https://github.com/joggeli34/quarkus-demo

`gradlew quarkusIntTests  -Dquarkus.package.type=native`

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.3-java17

### Quarkus version or git rev

3.4.1

**Comment by teimyBr** [comment]
We also have this Issue. 

`Failed to load config value of type class java.lang.String for: outgoing.orders.response.topics `

3.3.2 works fine 

3.4.1 its get broken. 

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4#configuration 

Maybe related to this ?

**Comment by radcortez** [comment]
This works with the latest version 3.13.2.
