### ISSUE TITLE
Renamed configuration property to enable CORS filter not recognized

### ISSUE THREAD

**Issue by mzuber** [quarkusio/quarkus#36071]
### Describe the bug

The [Quarkus 3.4 migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.4) states that the configuration property `quarkus.http.cors` has been renamed to `quarkus.http.cors.enabled`. When renaming this configuration property accordingly after upgrading to Qkuarkus `3.4.1` our application doesn't seem to recognize the configuration property `quarkus.http.cors.enabled`.

```
> ./gradlew quarkusDev
...
2023-09-21 16:09:01,377 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.cors.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
...
```

When running tests, the error message is slightly different:
```
> ./gradlew check
...
Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
...
```

The "old" configuration property `quarkus.http.cors` works as expected.

Also, the [HTTP reference guide](https://quarkus.io/guides/http-reference#cors-filter) doesn't mention the renamed property at all.

### Expected behavior

Quarkus correctly recognizes the renamed configuration property `quarkus.http.cors.enabled`.

### Actual behavior

Using a CORS configuration like

```properties
quarkus.http.cors.enabled = true
quarkus.http.cors.origins = /.*/
quarkus.http.cors.methods = GET,PUT,POST,DELETE
quarkus.http.cors.headers = Content-Type,Content-Length,Authorization,X-Requested-With,Accept,Origin
quarkus.http.cors.exposed-headers = Content-Type,Content-Length,Authorization,X-Requested-With,Accept,Origin
quarkus.http.cors.access-control-max-age = 24H
quarkus.http.cors.access-control-allow-credentials = true
```

results in the following error message at application startup:

```
Unrecognized configuration key "quarkus.http.cors.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### How to Reproduce?

Create a fresh Quarkus project and add a corresponding CORS filter configuration to application configuration:

1. Create a fresh Quarkus project:
    ```sh
    quarkus create app my-groupId:my-artifactId \
    --extension=resteasy-reactive,resteasy-reactive-jackson \
    --gradle-kotlin-dsl
    ```
1. Add CORS configuration filter with renamed configuration property to `application.properties`:
    ```properties
    quarkus.http.cors.enabled = true
    quarkus.http.cors.origins = /.*/
    quarkus.http.cors.methods = GET,PUT,POST,DELETE
    quarkus.http.cors.headers = Content-Type,Content-Length,Authorization,X-Requested-With,Accept,Origin
    quarkus.http.cors.exposed-headers = Content-Type,Content-Length,Authorization,X-Requested-With,Accept,Origin
    quarkus.http.cors.access-control-max-age = 24H
    quarkus.http.cors.access-control-allow-credentials = true
    ```
1. Start application in development mode:
    ```sh
    ./gradlew quarkusDev
    ```
1. Run tests:
    ```sh
    ./gradlew check
    ```

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by mzuber** [comment]
While I was writing this bug report the migration guide was updated and doesn't contain the section on the renamed CORS configuration property anymore.

**Comment by sberyozkin** [comment]
@mzuber Thanks, right, yeah, I think the PR was reverted (but likely will come back in the future :-) ), I'll let Roberto close it when confirmed

**Comment by radcortez** [comment]
Yes, it was reverted, and the plan was to provide a fix before the release (so I kept the migration entry), but I could not make it.
