### ISSUE TITLE
Quarkus LTS version 3.2 is not available on code.quarkus

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#36085]
### Describe the bug

Quarkus LTS version 3.2 is not available on code.quarkus

<img width="800" alt="Screenshot 2023-09-22 at 8 11 09" src="https://github.com/quarkusio/quarkus/assets/925259/ab2f07fa-2ac6-45da-a8fa-fad82f8153e6">

### Expected behavior

Quarkus LTS version 3.2 is available on code.quarkus

### Actual behavior

Quarkus LTS version 3.2 is NOT available on code.quarkus

### How to Reproduce?

 - Open https://code.quarkus.io/
 - Click on stream selection

**Comment by rsvoboda** [comment]
CC @ia3andy @aloubyansky

**Comment by rsvoboda** [comment]
3.2 entry should probably have `(LTS)`, similar to `(RECOMMENDED)` suffix for the latest stream

**Comment by ia3andy** [comment]
this seems like a registry issue @gastaldi

**Comment by gastaldi** [comment]
Thanks for the heads up, I pinned the 3.2 stream now: https://github.com/quarkusio/quarkus-extension-catalog/commit/da69863694f214cbb796b094378f3b556accd18d

**Comment by gastaldi** [comment]
I can see the version is there now, but the LTS in the UI might need some changes in code.quarkus?

**Comment by ia3andy** [comment]
Yes I'll have a look

**Comment by mkouba** [comment]
This seems to be fixed because I can see the `3.2` version in the dropdown.
