### ISSUE TITLE
RestEasy Reactive Rest Client captures thread stack and there is no option to disable it

### ISSUE THREAD

**Issue by umutsahin** [quarkusio/quarkus#36092]
### Description

Hi,

While profiling our quarkus application, which using RestEasy reactive rest client, I have noticed it is recording thread stacks.
Checked the code but unfortunately there is no option to disable this feature.

I fear this is degrading performance for the client.

Involved classes: 
* org.jboss.resteasy.reactive.client.handlers.ClientCaptureCurrentContextRestHandler
* org.jboss.resteasy.reactive.client.impl.HandlerChain

<img width="2475" alt="Screenshot 2023-09-22 at 11 35 22" src="https://github.com/quarkusio/quarkus/assets/8646787/434cab78-f1e9-4c0f-a9e7-4a3c11a80677">

### Implementation ideas

There should be an option to disable this feature, for performance demanding applications this is crucial.

**Comment by geoand** [comment]
Thanks for reporting. I'll take care of this

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/36093 takes of the issue
