### ISSUE TITLE
[Extension Proposal] HiveMQ extension

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#36103]
### Description

Currently, there is an "unofficially"  HiveMQ [extension](https://github.com/quarkiverse/quarkus-hivemq-client) but we (HiveMQ) could not proceed because the leading developer doesn´t[ reply to any comment ](https://github.com/quarkiverse/quarkus-hivemq-client/pull/80) or PR that we have made. 

The current implementation is fine; we just want to improve the coverage and add new features, such as supporting MQTT 5 or native compilation (and also improve the documentation and the code standards). We also would like to use as few third-party libraries as possible.

My question is, do you think it would be possible to create a new extension in order to try to maintain and move forward more quickly?  

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-smallrye-hivemq-client

### Short description

Official Quarkus smallrye-hivemq client implementation

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-smallrye-hivemq-client/dev/

### Repository Topics

- quarkus-extension
- hivemq
- smallrye
- mqtt
- reactive-mqtt
- messaging

### Team Members

* Pablo Gonzalez Granados
     * Github profile: https://github.com/pjgg
     * Email: pablo.granados@hivemq.com
     * UserName: pjgg
* Jochen Mader
     * Github profile: https://github.com/codepitbull
     * Email: jochen.mader@hivemq.com
     * UserName: codepitbull
* Pablo Gutierrez
     * Github profile: https://github.com/gutmox
     * Email: pablo.gutierrez@hivemq.com
     * UserName: gutmox
 * Alvaro Yague
     * Github profile: https://github.com/ayagsan
     * Email: alvaro.yague@hivemq.com
     * UserName: ayagsan

**Comment by gastaldi** [comment]
Not sure I like the idea of having two extensions for the same purpose. What if I added you guys as maintainers of the existing https://github.com/quarkiverse/quarkus-hivemq-client/? Would that work?

**Comment by gastaldi** [comment]
@pjgg @codepitbull @gutmox @ayagsan welcome aboard! You are officially maintainers of the https://github.com/quarkiverse/quarkus-hivemq-client/ repository. Here is how to release it: https://hub.quarkiverse.io/release/ 

PS: Make sure to update it to Quarkus 3.x and 2.x in a separate branch

Go ahead and make it shine 😉

**Comment by masini** [comment]
Hi, I created this extension that is working in production without problems for 2 years now.

I have always answered to all PR and I lost only this on july.

I would find a fine behaviour to receive an email before an action to a project I mantained for years.

Now I need to push corrections related to Quarkus 3, I think I will need to create a fork.

**Comment by gastaldi** [comment]
> I would find a fine behaviour to receive an email before an action to a project I mantained for years.
> 

You mean you haven't received any notification from this issue and the existing PRs? That's weird. I see that that nothing changed in the repository anyway, so nothing really changed so far. If you think https://github.com/quarkiverse/quarkiverse-devops/pull/183 is wrong, let me know and I can revert and put up with a separate extension if you feel like it.

> Now I need to push corrections related to Quarkus 3, I think I will need to create a fork.

Why? Are the proposed changes incompatible?

**Comment by pjgg** [comment]
@masini Let's have a chat, I mean your extension is great!, we just want to move on and support you.

Please write me an email to: [pablo.granados@hivemq.com](mailto:pablo.granados@hivemq.com) and have this chat!.

**Comment by masini** [comment]
Thank you @gastaldi and @pjgg for your quick answer !

@gastaldi I don't receive emails, from time to time I check if there are some PR, in august I didn't I must admin :)

I would prefere have a push instead of a pull, but I can survive this way

@pjgg I'll write to you from my personal account, so that we can understand how to evolve the extension, which is great because the HiveMQ client is great !!!
