### ISSUE TITLE
Kotlin all-open plugin options

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkus#3612]
**Describe the bug**
Hi, by default when a Rest Kotlin Project is created, following the quarkus-maven-plugin create, the code below is added in the pom to suppress the need to open a class if a class is annotated with `@Path` and to be able to use `@Inject` in other variables. 

```
<configuration>
          <compilerPlugins>
            <plugin>all-open</plugin>
          </compilerPlugins>
          <pluginOptions>
              <option>all-open:annotation=javax.ws.rs.Path</option>
          </pluginOptions>
</configuration>
```

If I want to add other annotations to follow the same behaviour as below, it doesn't work:

```<configuration>
          <compilerPlugins>
            <plugin>all-open</plugin>
          </compilerPlugins>
          <pluginOptions>
              <option>all-open:annotation=javax.ws.rs.Path</option>
              <option>all-open:annotation=javax.enterprise.context.RequestScoped</option>
              <option>all-open:annotation=javax.enterprise.context.SessionScoped</option>
              <option>all-open:annotation=javax.enterprise.context.ApplicationScoped</option>
              <option>all-open:annotation=javax.enterprise.context.Dependent</option>
              <option>all-open:annotation=javax.ejb.Singleton</option>
              <option>all-open:annotation=javax.ejb.Stateful</option>
              <option>all-open:annotation=javax.ejb.Stateless</option>
            </pluginOptions>
        </configuration>
```

If I update the Kotlin version to 1.3.30, for example, it works but the hot-swap doesn't work well in the quarkus:dev mode

**Expected behaviour**
A class annotated with an annotation that's in the pluginOptions properties, should not be needed to open a class as bellow:

`@ApplicationScoped
open class Something`

**Actual behaviour**
Even with the annotations in the pluginOptions properties, it's necessary to open a class in order to work.

**Quarkus Version**
0.21.1

**Comment by geoand** [comment]
Kotlin has been bumped to `1.3.41` in `master` and should be present in the upcoming `0.22.0`.

The issue with dev-mode is covered by #2811

**Comment by geoand** [comment]
I am going to close this as partly addressed and partly a dup, feel free to reopen if you feel that it wasn't properly addressed
