### ISSUE TITLE
Upgrading to 3.4.1 from 3.3.3 with Gradle 8.3 causes exceptions when running @QuarkusTests via IntelliJ

### ISSUE THREAD

**Issue by Will-1** [quarkusio/quarkus#36136]
### Describe the bug

When upgrading to 3.4.1 from 3.3.3 with Gradle 8.3, test runs cause exceptions when running @QuarkusTests via IntelliJ.

IntelliJ Gradle Config:
![image](https://github.com/quarkusio/quarkus/assets/34572724/b756c00e-fcf8-4985-9b82-a8459e8aee29)

This was tried with both GraalVM CE 17 and 21 and the result was the same. 

Note the tests run without issue when running via the terminal with quarkus dev

### Expected behavior

Tests run.

### Actual behavior

Tests fail to run with the following stack trace.

`Caused by: org.gradle.api.GradleException: Could not determine the class-path for class io.quarkus.bootstrap.resolver.QuarkusModelBuildAction`

Full stack trace:
[Quarkus-test-run-stack-trace.log](https://github.com/quarkusio/quarkus/files/12715154/Quarkus-test-run-stack-trace.log)

### Output of `java -version`

21

### GraalVM version (if different from Java)

21

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by Sarquamon** [comment]
Hello @Will-1 did you happen to solve the issue? if so, can you please share how?

Thanks!

**Comment by geoand** [comment]
Closing for lack of feedback
