### ISSUE TITLE
PG Reactive Client: Cannot create Money value in Range (-1.00, 0.00)

### ISSUE THREAD

**Issue by ghubstan** [quarkusio/quarkus#36144]
### Describe the bug

I cannot create a `Money` value of -0.XX, i.e.,  a Money value greater than -1.00, and less than 0.00. Range  (-1.00 < value < 0.00)

If the integer value of the Number argument is non-zero, e.g., using `Money` constructor argument `new BigDecimal("-1.11")`  works.

If the integer value of the Number argument is zero, e.g., using a `Money` constructor `new BigDecimal("-0.11")` does not work (as expected).

I am not certain this is a bug, due to my expectation that the integerPart of a Money(-0.11) could be represented as -0.

Reproducing tests and debugger screenshots are below.

### Expected behavior

Calling `new Money(new BigDecimal("-0.11"))` results in a negative `Money(-0,11)`

The Money value represents  minus 11 cents, as expected.

### Actual behavior

Calling `new Money(new BigDecimal("-0.11"))` results in a _positive_ `Money(0,11)`

The Money value represents plus 11cents, not minus 11cents.

### How to Reproduce?

> Reproduce Expected Behaviour
1. Use a `BigDecimal` as a `Money` constructor argument.  
   `Money money = new Money(new BigDecimal("-1.11"));`

2. Examine resulting Money in debugger:
![right-money](https://github.com/quarkusio/quarkus/assets/36207203/3f27c988-8a66-444d-ac59-f7cee5a2e2a8)

3. Print resulting Money value:  `Money(-1.11)`.          As expected I see `Money(-1.11)`.

> Reproduce Unexpected Behaviour

1. Use a `BigDecimal` as a `Money` constructor argument.  
   `Money money = new Money(new BigDecimal("-0.11"));`

2. Examine resulting Money in debugger:
![wrong-money](https://github.com/quarkusio/quarkus/assets/36207203/14ecd930-48fd-4924-8b41-dd5a2127d329)

3. Print resulting Money value:  `Money(0.11)`.          I expect to see `Money(-0.11)`.

Below are some test cases.

```
 @Test
    public void testRightMoney() {
        Money money = new Money(new BigDecimal("-1.11"));
        System.out.println(money);
        assertEquals(-1, money.getIntegerPart());
        assertEquals(11, money.getDecimalPart());
    }
```

Above, as expected `assertEquals(-1, money.getIntegerPart())` passes.

```
@Test
    public void testWrongMoney() {
        Money money = new Money(new BigDecimal("-0.11"));
        System.out.println(money);
        assertEquals(0, money.getIntegerPart());
        assertEquals(11, money.getDecimalPart());
    }

```

Above, as expected `assertEquals(0, money.getIntegerPart())` passes, but I need to be able to create a Money(-0.11).

Any advice?
Thanks.

### Output of `uname -a` or `ver`

Ubuntu 22.04.3  Linux 6.2.0-33-generic x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by tsegismont** [comment]
Thanks for reporting @ghubstan

I've filed https://github.com/eclipse-vertx/vertx-sql-client/issues/1360 upstream

**Comment by ghubstan** [comment]
Thanks.  I'll report upstream, in the proper place next time.
