### ISSUE TITLE
Enable OracleOpenTelemetryJdbcInstrumentationTest

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#36141]
### Description

Test was disabled here because the supporting docker image was buggy 
https://github.com/quarkusio/quarkus/pull/36140

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by brunobat** [comment]
@vimalJD no need to write on **bold**. Please check https://github.com/quarkusio/quarkus/labels/good%20first%20issue for good first issues.

**Comment by navinyashende** [comment]
I would like to work on this. Can this be assigned to me?

**Comment by brunobat** [comment]
Sure @navinyashende, please go ahead. 
It should be simply to bring back the code that was removed in https://github.com/quarkusio/quarkus/pull/36140

**Comment by navinyashende** [comment]
Raised a PR. Would really appreciate if the hacktoberfest-accepted label can be added to the PR. Pardon me if the hacktoberfest issues are different ones

**Comment by brunobat** [comment]
Hi @navinyashende, the quarkus repo already has the label:
<img width="662" alt="Screenshot 2023-10-04 at 09 19 53" src="https://github.com/quarkusio/quarkus/assets/2318030/fc6c4b03-b865-486a-93a4-9269893a79bb">
Isn't that enough?
