### ISSUE TITLE
Allow to register JAX-RS endpoints generated by extensions

### ISSUE THREAD

**Issue by dyutiman** [quarkusio/quarkus#36151]
### Description

The JAX-RS resource produced by a Quarkus extension is not registered when using quarkus-resteasy-reactive or quarkus-resteasy-reactive-jackson.

The same is working with just quarkus-resteasy.

**Comment by geoand** [comment]
Can you elaborate a little more on this please?

**Comment by dyutiman** [comment]
I created a very simple extension to expose one JAX-RS enpoint

`package com.dyutiman.rest.extension.runtime;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

@Path("/dummy")
public class DummyResource {

    @GET
    public String get() {
        return "My resource called";
    }
}`

And I have used 'quarkus-resteasy' artifactId in my pom.xml under runtime and 'quarkus-resteasy-deployment' in deployment. I created the BuildStep to include this class.

`@BuildStep
  AdditionalBeanBuildItem resource() {
      return new AdditionalBeanBuildItem(DummyResource.class);
  }`

This is exposed perfectly when I use the extension in my project.

But, instead of 'quarkus-resteasy' and 'quarkus-resteasy-deployment', if I use 'quarkus-resteasy-reactive' and 'quarkus-resteasy-reactive-deployment' or 'quarkus-resteasy-reactive-jackson' and 'quarkus-resteasy-reactive-jackson-deployment', the endpoint does not work anymore.

Do I have to use a different BuildItem for this?

**Comment by geoand** [comment]
Try using `AdditionalResourceClassBuildItem`

**Comment by dyutiman** [comment]
Thanks for the reply. I tried the below BuildStep, but my class is not recognised.

`    @BuildStep
    void resource(CombinedIndexBuildItem index,
                  BuildProducer<AdditionalResourceClassBuildItem> additionalResourceClassProducer) {
        DotName path = DotName.createSimple(Path.class.getName());
        for (AnnotationInstance restController : index.getIndex().getAnnotations(path)) {
            AnnotationTarget annotTarget  = restController.target();
            System.out.println("got class " + annotTarget);
            if(AnnotationTarget.Kind.CLASS.equals(annotTarget.kind())) {
                ClassInfo targetClass = restController.target().asClass();
                String singlePath = restController.value("value").value().toString();
                System.out.println("PATH " + singlePath);
                additionalResourceClassProducer.produce(new AdditionalResourceClassBuildItem(targetClass, singlePath));
            }
        }
    }`
    
Do I have to make anything for my class to be included in CombinedIndexBuildItem?

**Comment by geoand** [comment]
> Do I have to make anything for my class to be included in CombinedIndexBuildItem?

Nope. We use `AdditionalResourceClassBuildItem` in our code base and it works as expected

**Comment by dyutiman** [comment]
Just to confirm my @Path class belongs to the runtime module of my extension. I hope this is fine.

**Comment by dyutiman** [comment]
Well, it started working after I added the jandex-maven-plugin to my runtime pom.xml.

`<plugin>
      <groupId>io.smallrye</groupId>
      <artifactId>jandex-maven-plugin</artifactId>
      <version>3.1.3</version>
      <executions>
        <execution>
          <id>make-index</id>
          <goals>
            <goal>jandex</goal>
          </goals>
        </execution>
      </executions>
    </plugin>`

**Comment by geoand** [comment]
👍🏼
