### ISSUE TITLE
Resteasy client does not return the same bytes if the method returns `ByteArray` or `File`

### ISSUE THREAD

**Issue by brice-laurencin** [quarkusio/quarkus#36167]
### Describe the bug

Those 3 methods somehow do not return the same bytes:

```kotlin
@GET
@Path("/produce/a/pdf")
fun getFile(): File

@GET
@Path("/produce/a/pdf")
fun getBytes(): ByteArray

@GET
@Path("/produce/a/pdf")
fun getResponse(): Response
```

### Expected behavior

Same bytes from all the 3 methods.

### Actual behavior

The resulting PDF from `getBytes` and `getResponse` are corrupted and cannot be open (correct number of pages, but all blank), the one from `getFile` is fine.

How come?
The actual endpoint I'm querying can answer either `pdf` or `zip`, so I have to use the `getResponse` variant, as I need to work differently if returns a zip.

### How to Reproduce?

I'm calling a thrid party service here.

### Output of `uname -a` or `ver`

`Linux brice-work 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

`openjdk version "17.0.7" 2023-04-18`

### Quarkus version or git rev

`3.1.1FINAL`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Gradle 8.1.1`

**Comment by geoand** [comment]
Please attach a sample project that shows this problem in action

**Comment by geoand** [comment]
Perhaps Wireshark can reveal some clues

**Comment by brice-laurencin** [comment]
the data from the """service""" is always the same, the only difference is the deserialization of the payload. I don't quite get it, but I will definitely dig into this.

Right now I moved to using Apache Tika to be able to tell the file types apart

**Comment by geoand** [comment]
> I don't quite get it, but I will definitely dig into this

Thanks

**Comment by geoand** [comment]
Closing for lack of a reproducer.

If one does become available, we can reopen the issue
