### ISSUE TITLE
Add Infinispan Embedded extension

### ISSUE THREAD

**Issue by wburns** [quarkusio/quarkus#3617]
**Description**
We need an extension that allows a user to use an embedded Infinispan cache. This would include features such as stores, off heap, clustering, querying and parsing xml files at runtime.

**Implementation ideas**
The initial extension will have minimal support to get the various features of Infinispan embedded. Later revisions can visit optimizing the native image and adding proper CDI.

**Comment by gwenneg** [comment]
There's been some discussions in #3306 about adding Infinispan as a caching provider to the Quarkus application data caching extension which is currently under review. The first development iteration is almost done and consists in an annotations-based caching implementation with Caffeine as the first and only caching provider for now. The plan is to add other providers as well as a caching API in future iterations.

Would your embedded Infinispan cache proposal fit in that extension?

cc @gsmet @galderz

**Comment by wburns** [comment]
@gwenneg Yes, we would definitely want to add Infinispan embedded as a provider. We could even discuss about having Infinispan client as a provider even. But the former should be simpler.

**Comment by rsvoboda** [comment]
Can be this issue closed ? PR was merged 13 days ago.

**Comment by gwenneg** [comment]
I'm not sure this issue is entirely covered by the PR:

> This PR only includes Infinispan core and thus querying is not yet included.

**Comment by rsvoboda** [comment]
Just asking to avoid leftovers

**Comment by wburns** [comment]
Oops, I meant to close this. The base extension is in Quarkus now. Additional features will come as different issues.
