### ISSUE TITLE
@ConsumeEvent does not work in native when returning a Uni<Set<String>>

### ISSUE THREAD

**Issue by tnmtechnologies** [quarkusio/quarkus#36172]
### Describe the bug

Quarkus 3.4.1
Redis 7.2.1

I use event bus consumer to run the redis client logic.
In JVM mode, the following piece of code works fine but with native executable, it fails with a timeout (30s default value I guess) at event bus sender side.
Thanks to the redis MONITOR command, I can see the command processed by redis.

I did some tests with Quarkus 3.2.6.Final. I have the same behavior.

    @Inject
    private ReactiveRedisDataSource rds;

      return Optional.ofNullable(nfType)
                    .map(t -> {
                        final ReactiveSetCommands<String,String> setCommands = rds.set(String.class);
                        return setCommands.smembers(toNfTypesKey(t));
                    }).orElseGet(() -> {
                        final ReactiveKeyCommands<String> keyCommands = rds.key(String.class);
                        final ReactiveKeyScanCursor<String> scanCursor = keyCommands.scan(new KeyScanArgs().match(NF_PROFILES_NAMESPACE + '*').count(Long.MAX_VALUE));
                        final boolean hasNext = scanCursor.hasNext();
                        return hasNext ? scanCursor.next() : Uni.createFrom().item(() -> Collections.emptySet());
                    }).onItem().transformToMulti(s -> Multi.createFrom().items(s::stream))
                    .select().first(limit)
                    .onItem().transform(s -> nfType != null ? s : s.substring(NF_PROFILES_NAMESPACE.length()))
                    .collect().asSet()
                    ;

### Expected behavior

The code should work in native executable as for JVM mode.

### Actual behavior

The code works in JVM mode but fails with native executable.

### Output of `java -version`

```
java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
./mvnw --version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: C:\Users\mvsz7559\.m2\wrapper\dists\apache-maven-3.9.1-bin\320285b4\apache-maven-3.9.1
Java version: 17.0.5, vendor: GraalVM Community, runtime: D:\Liberkey\MyApps\graalvm\graalvm-ce-java17-22.3.0
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by cescoffier** [comment]
So, you say that the commands are correctly executed by Redis?

**Comment by tnmtechnologies** [comment]
Here is the redis monitor output (smembers is for the mutiny map and scan for the orElseGet) for the native app:

> MONITOR
OK
1695817743.024683 [0 192.168.65.1:48609] ping
1695817753.017798 [0 192.168.65.1:48609] ping
1695817753.683625 [0 192.168.65.1:48613] hello 3
1695817753.686222 [0 192.168.65.1:48613] smembers nfTypes:NRF
1695817763.019689 [0 192.168.65.1:48609] ping
1695817773.013909 [0 192.168.65.1:48609] ping
1695817783.009533 [0 192.168.65.1:48609] ping
1695817793.021823 [0 192.168.65.1:48609] ping
1695817796.545971 [0 192.168.65.1:48614] hello 3
1695817796.548048 [0 192.168.65.1:48614] scan 0 COUNT 9223372036854775807 MATCH nfProfiles:*
1695817803.011999 [0 192.168.65.1:48609] ping
1695817813.014244 [0 192.168.65.1:48609] ping
1695817823.009855 [0 192.168.65.1:48609] ping

and the caught exception at event bus producer side (not sure it will help):

 (vert.x-eventloop-thread-0)  eventBus request e=: (TIMEOUT,-1) Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.2, repliedAddress: nnrf.nfm.GetNFInstances
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76)
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:948)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)
        at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:207)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:937)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)


The Redis monitor output is the same as above for JVM mode but as said, the code works fine, I mean it serves the expected HTTP response which it is not the case with the native app.

**Comment by geoand** [comment]
But it works properly in JVM?

**Comment by tnmtechnologies** [comment]
Yes everything works properly in JVM mode.

**Comment by cescoffier** [comment]
I would need a reproducer as a simple test (added to our ITs) works.

Also, the code can be simplified:

```
ReactiveKeyScanCursor<String> scanned = keys.scan(new KeyScanArgs().match("people:*"));
return scanned.toMulti().collect().asSet()
```

**Comment by tnmtechnologies** [comment]
Here is the reproducer project https://github.com/tnmtechnologies/quarkusRedisReactiveKeyScanCursorReproducer .


Thanks for the KEYS command. I agree it simplifies but there is a warning in [the documentation](https://redis.io/commands/keys/):
_Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases._

**Comment by cescoffier** [comment]
In your reproducer you do not mention the redis version and how many key do you have.

**Comment by tnmtechnologies** [comment]
I have updated the README file.
Redis version is 7.2.1-alpine.
I expect a few hundred keys.

**Comment by cescoffier** [comment]
The issue seems to be in the event bus, not in Redis. The redis code produce the expected output, but it looks like the event is lost on the event bus.

**Comment by cescoffier** [comment]
The issue is the usage of Set<String> as reply. The local codec does not seem to work in this case in native. We need to have a look (probably with the help of @mkouba ).

If you use something like:

```java
public static class MySet extends HashSet<String> {
        public MySet() {
            super();
        }

        public MySet(Set<String> s) {
            super(s);
        }

    }

    /**
     *
     */
    @ConsumeEvent("getIds")
    public Uni<MySet> getIds(final JsonObject message) {
        Log.infov("getIds(message={0})", message);

        final Long limit = Optional.ofNullable(message.getLong("limit")).orElse(Long.MAX_VALUE);
        final String type = message.getString("type");

        return Optional.ofNullable(type)
                    .map(t -> {
                        final ReactiveSetCommands<String,String> setCommands = rds.set(String.class);
                        return setCommands.smembers(TYPE_NAMESPACE + t);
                    }).orElseGet(() -> {
                        final ReactiveKeyCommands<String> keyCommands = rds.key(String.class);                        
                        final ReactiveKeyScanCursor<String> scanCursor = keyCommands.scan(new KeyScanArgs().match(ID_NAMESPACE + '*').count(Long.MAX_VALUE));
                        final boolean hasNext = scanCursor.hasNext();
                        System.out.println("Has next...");
                        return hasNext ? scanCursor.next() : Uni.createFrom().item(() -> Collections.emptySet());
                    }).onItem().transformToMulti(s -> Multi.createFrom().items(s::stream))
                    .select().first(limit)
                    .onItem().transform(s -> type != null ? s : s.substring(ID_NAMESPACE.length()))
                    .collect().asSet()
                    .map(s -> new MySet(s))
                    .log("user code")
                    ;
    }
```

It works

**Comment by tnmtechnologies** [comment]
Thanks a lot @cescoffier, the work around works.

**Comment by cescoffier** [comment]
@mkouba thanks for the analysis. 

In terms of UX, should we detect when a @ConsumeEvent method return an interface and log a warning in this case (if no codec for that type is found) ?

**Comment by tnmtechnologies** [comment]
@mkouba Thank you, It works.

**Comment by cescoffier** [comment]
@mkouba ah yes.... So what about just documenting it as a limitation for now?

**Comment by mkouba** [comment]
> @mkouba ah yes.... So what about just documenting it as a limitation for now?

Yes, we should extend the [Use codecs](https://quarkus.io/guides/vertx-reference#use-codecs) section and explain how the default codec is registered for a return type. And make it clear that registering a default codec for an interface is of no use. And maybe add how to register a default codec for a type + register for reflection for native image.

**Comment by mkouba** [comment]
Hm, I think that we could actually improve the UX a little bit and register a default codec selector with `EventBus.codecSelector(Function<Object, String>)` and use the `LocalEventBusCodec` by default for anything... WDYT?

**Comment by cescoffier** [comment]
Ah yes! Good idea! I forgot about the selector.
