### ISSUE TITLE
Allow for K8s Ingress tls secretName to be explicitly specified with config propertiy

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#36191]
### Description

See last line.
Currently it generates 'grpc-demo.alesj.com'.

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: d25cc2a7ee11a42ffe684e51172475528c52bb8a
    app.quarkus.io/build-timestamp: 2023-09-21 - 12:26:26 +0000
  labels:
    app.kubernetes.io/name: grpc-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: grpc-demo
  namespace: grpc
spec:
  rules:
    - host: grpc-demo.alesj.com
      http:
        paths:
          - backend:
              service:
                name: grpc-demo
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - grpc-demo.alesj.com
      secretName: grpc-demo-alesj-com-tls

### Implementation ideas

quarkus.kubernetes.ingress.tls."grpc-demo.alesj.com".secret-name=grpc-demo-alesj-com-tls

**Comment by iocanel** [comment]
Using `quarkus.kubernetes.ingress.tls.my-secret.hosts=my-host` one can specify the actual secret.

This seems to be covered by the integration test we currently have, so I am thinking that if it doesn't work in your case there are may be additional parameters that might affect the behavior.
