### ISSUE TITLE
Issue with generic bean injection

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#3619]
When there's a generic bean with an unbounded type parameter T [(example)](https://github.com/eclipse/microprofile-metrics/blob/2.0.1/tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugedMethodBean.java#L21) and an injection point that declares a particular type for T [(example)](https://github.com/eclipse/microprofile-metrics/blob/2.0.1/tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugedMethodBeanTest.java#L93), ARC blows up with `UnsatisfiedResolutionException`. I assume this setup should be valid, because the CDI [spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#assignable_parameters) says

> A parameterized bean type is considered assignable to a parameterized required type if they have identical raw type and for each parameter:
> (...)
> the required type parameter is an actual type, the bean type parameter is a type variable and the actual type is assignable to the upper bound, if any, of the type variable, or
> (...)

in our case,
- _required type parameter is an actual type_ - `java.lang.Long`
- _the actual type is assignable to the upper bound of the type variable_ - `Long` is assignable to `java.lang.Object` 

The Metrics TCKs, from which I link examples, work without changes with Weld. To make this test work with Quarkus, I had to add an upper bound for the bean (`ConcurrentGaugedMethodBean<T extends Long>`)

**Comment by jmartisk** [comment]
FYI @mkouba @manovotn 
Also @kenfinnigan this affects Metrics TCK

**Comment by manovotn** [comment]
Looking at Arc resolution, what it actually does is that it translates `T` into plain `Object` and does resolution on top of that. E.g. in time of comparison, it compares required type `ConcurrentGaugedMethodBean<Long>)` with bean that has `ConcurrentGaugedMethodBean<Object>)` and according to [CDI spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#assignable_parameters) this then falls under:

> the required type parameter and the bean type parameter are actual types with identical raw type, and, if the type is parameterized, the bean type parameter is assignable to the required type parameter according to these rules, or
