### ISSUE TITLE
Update Byte Buddy to work with Java 21 on Quarkus LTS version

### ISSUE THREAD

**Issue by Willian199** [quarkusio/quarkus#36208]
### Describe the bug

Backport to Quarkus LTS the fix made for Quarkus 3.4 in [PR #35617 ](https://github.com/quarkusio/quarkus/pull/35617)

### Expected behavior

The server starts as in Quarkus 3.4

### Actual behavior

The server throw the error:
`Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property`

### GraalVM version (if different from Java)

graalvm-jdk-21+35.1

### Quarkus version or git rev

Quarkus 3.2.6.Final

**Comment by geoand** [comment]
cc @Sanne @gsmet

**Comment by Sanne** [comment]
Sure, it's low risk. However it's also trivial to set `-Dnet.bytebuddy.experimental`, exactly like the error suggests.

It begs the question of .. do we want to imply that Quarkus 3.2 is compatible with Java 21? Since we don't make any statement about it (we didn't even test it), I'm not sure if it's preferrable to backport this - but it's certainly trivial.

**Comment by geoand** [comment]
> Since we don't make any statement about it (we didn't even test it), I'm not sure if it's preferrable to backport this

This is the critical question we need to answer - cc @maxandersen @n1hility

**Comment by Sanne** [comment]
> > Since we don't make any statement about it (we didn't even test it), I'm not sure if it's preferrable to backport this
> 
> This is the critical question we need to answer - cc @maxandersen @n1hility

Right. Posted this question on zulip too: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Should.20Quarkus.203.2E2.20.28LTS.29.20be.20made.20compatible.20with.20Java.2021.3F

**Comment by Willian199** [comment]
I was imagining the issue would go this way.

In my view, the current Quarkus LTS version should run with current Java LTS. But not necessary support all the new features.

**Comment by Sanne** [comment]
> I was imagining the issue would go this way.

Sorry :)

> In my view, the current Quarkus LTS version should run with current Java LTS. But not necessary support all the new features.

I'm inclined to agree, but in that case at very least we should be running integration tests for this branch on Java 21.
But also, the users who want a "more stable" branch (by definition the LTS branch) will not want to see a large amount of changes backported, and things like Loom are fairly disruptive, so while I think we can make it run on it I don't think we'll want to officially support this goal.
