### ISSUE TITLE
Object dependency graph 

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#3620]
**Description**
As an "extension developer", I find sometime hard to understand the hierarchy of the various steps and objects in particular when you want to re-use something created by another extension you do not master.

It would be very nice if quarkus could provide a tool to visualize the dependencies and relations between the various build steps, arc objects and so on and eventually report possible misconfiguration.

**Comment by gsmet** [comment]
@lburgazzoli did this trick work? If so maybe you could document it in the Writing extensions guide?

**Comment by lburgazzoli** [comment]
adding this to my todo list for tomorrow

**Comment by poulad** [comment]
I'm evaluating Quarkus atm. It'd be nice to have a screenshot of this dependency graph in the docs.

https://github.com/geoand/quarkus/blob/master/docs/src/main/asciidoc/writing-extensions.adoc#239-visualizing-build-step-dependencies
