### ISSUE TITLE
@RestClient injecttion is not working in service class

### ISSUE THREAD

**Issue by dyutiman** [quarkusio/quarkus#36205]
### Describe the bug

I am creating a simple application to fetch data via REST Client.

`import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

@Path("/api")
@RegisterRestClient(configKey="bored-api")
public interface BoredService {

    @GET
    @Path("/activity")
    @Produces(MediaType.APPLICATION_JSON)
    BoredActivity getBoredActivity();
}`

This one I am trying to inject in my service class

`import jakarta.inject.Inject;
import org.eclipse.microprofile.rest.client.inject.RestClient;

public class TestService {

    @Inject
    @RestClient
    BoredService boredService;

    public BoredActivity getBoredActivity() {
        return boredService.getBoredActivity();
    }
}`

And this service class I want to use in my application endpoint

`import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/test")
public class TestRestClient {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public BoredActivity getBoredActivity() {
        return new TestService().getBoredActivity();
    }
}`

But this throws NullPointerException where I am trying to use the Rest Client, at 
`return boredService.getBoredActivity();`

But if I inject the rest cleint in my TestRestClient class then it is working. Looks like the @RestClient works only with classes annotated with @Path.

Is this the only way I can inject the rest client? Lets assume I do not want to initialize the client via QuarkusRestClientBuilder.

**Comment by dvsingh9** [comment]
Can you use @ApplicationScoped like

```
@path("/api") @ApplicationScoped 
@RegisterRestClient(configKey="bored-api")
public interface BoredService {

@GET
@Path("/activity")
@Produces(MediaType.APPLICATION_JSON)
BoredActivity getBoredActivity();

}
```

and you service also

```
@ApplicationScoped 
public class TestService {

private final BoredService boredService;

@Inject
public TestService ( BoredService boredService) {
  this.boredService = boredService;
}

public BoredActivity getBoredActivity() {
    return boredService.getBoredActivity();
}

}
```

**Comment by dyutiman** [comment]
It works if I use @ApplicationScoped in TestService and @Inject it in TestRestClient.

`@Path("/test")
public class TestRestClient {

    @Inject
    TestService testService;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public BoredActivity getBoredActivity() {
        return testService.getBoredActivity();
    }
}`

I did not make BoredService @ApplicationScoped
