### ISSUE TITLE
Allow for customization of a MongoDB Connection String properties

### ISSUE THREAD

**Issue by soaresGITHUB** [quarkusio/quarkus#36210]
### Description

Hello,
In the process of migrating Spring services to Quarkus we found a configuration that could be nice to have in the configuration of Mongo Services.

In Spring Boot, we have the following property in a base MongoDB module that configures the UUID Representation:
`spring.data.mongodb.uuid-representation=standard`

This way we don't have to worry about configuring that property for all services that need it.

While trying to configure the same thing for the Quarkus projects, we found there was no property that allows this, or other configurations that could be nice to add to the Connection String, apart from a Dev Services property that I saw discussed in the following issue: https://github.com/quarkusio/quarkus/issues/27269

Is this something that is feasible and worth it to add?

Thank you!

**Comment by EduardoFer** [comment]
+1

**Comment by geoand** [comment]
@loicmathieu I think this makes sense, WDYT?

**Comment by loicmathieu** [comment]
Hi,
Yes, it makes sense. I'll provide a PR for that.

**Comment by geoand** [comment]
🙏🏼
