### ISSUE TITLE
Wiki Dev-UI-v2 is out of date

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#36217]
### Description

The Wiki Page https://github.com/quarkusio/quarkus/wiki/Dev-UI-v2 is out of date, with several incorrect details:

- It says web component templates must be in `src/main/resources/dev-ui/<extension name>/`  in the deployment module, meanwhile the correct directory is  `src/main/resources/dev-ui/` in the deployment module.
- `CardPageBuildItem` takes an argument in its constructor (`CardPageBuildItem("Cache")`) (meanwhile now it does not take an argument in its constructor.

### Implementation ideas

Make the wiki link to [Dev UI V2 Guide](https://quarkus.io/guides/dev-ui-v2) , which seems to be up to date.

**Comment by geoand** [comment]
+1 for linking to the guide.
