### ISSUE TITLE
`@Priority(1)` can not working with override default `ExceptionHandler`

### ISSUE THREAD

**Issue by OrdinarySF** [quarkusio/quarkus#36224]
### Describe the bug

I try use `@Priority(1)` define a custom `ExceptionHandler` that override the default `ResteasyViolationExceptionMapper`, but the cant not work.

### Expected behavior

default response value is `ValidationException`(JSON format). I want to override this default format.

default:
```json
{
    "exception": null,
    "propertyViolations": [],
    "classViolations": [],
    "parameterViolations": [
        {
            "constraintType": "PARAMETER",
            "path": "comment.dto.content",
            "message": "comment is not blank ",
            "value": ""
        }
    ],
    "returnValueViolations": []
}
```

i want mapper result:
```json
{
    "message": "comment is not blank"
}
```

### Actual behavior

I have made many attempts, but no any changes.

### Output of `uname -a` or `ver`

windows 11

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment GraalVM 22.3.2 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM GraalVM 22.3.2 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.2 ------------------------------------------------------------  Build time:   2023-06-30 18:02:30 UTC Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877  Kotlin:       1.8.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.7 (BellSoft 17.0.7+7-LTS) OS:           Windows 11 10.0 amd64

**Comment by nichts12** [comment]
same problem. and rbac-jwt verify exception capture cannot take effect either

**Comment by geoand** [comment]
@OrdinarySF mind adding a sample application that behaves as you describe?

**Comment by OrdinarySF** [comment]
https://github.com/OrdinarySF/quarkus-exception-mapper-demo
This is a demo. Please look `MyExceptionMapper` class.
https://github.com/OrdinarySF/quarkus-exception-mapper-demo/blob/master/src/main/java/org/acme/MyGenericExceptionMapper.java

**Comment by OrdinarySF** [comment]
@geoand I have uploaded an example. Can you help me take a look?

**Comment by geoand** [comment]
Thanks for this. 

So it turns out that this happens because this is how the JAX-RS / Jakarta REST spec works - more specific (in terms of the exception handled) exception mappers always take precedence over more general ones.

**Comment by OrdinarySF** [comment]
> Thanks for this.
> 
> So it turns out that this happens because this is how the JAX-RS / Jakarta REST spec works - more specific (in terms of the exception handled) exception mappers always take precedence over more general ones.

Thanks for you reply.

So I only add more and more spc mapper？Is there any better way? Please enlighten me.

**Comment by geoand** [comment]
If you need to handle `ValidationException` in a custom way, you provide an `ExceptionMapper` for that type.

`ExceptionMapper<Exception>` is only used as a fallback if no ExceptionMapper exists that handles any of the specific extension types being thrown.
