### ISSUE TITLE
Accept-Language header not parsed correctly for language subtags, variants, extension and private subtags

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#36227]
### Describe the bug

When using an Accept-Language header for HTTP requests that contains more than simple language or language-country forms, the parsed `Locale` does not correctly reflect the given language tag as defined in https://www.rfc-editor.org/rfc/rfc9110#section-12.5.4.

Other examples of complex tags can be found in https://www.w3.org/International/articles/language-tags/.

### Expected behavior

Language tags are parsed into a Locale that correctly reflects the given data;  examples (not sure if `zh-yue` being turned into `yue` or `ar-afb` being turned into `afb` are correct, but that's what `java.util.Locale` turns it into):

```
Accept-Language: en
         Parsed: en

Accept-Language: ast
         Parsed: ast

Accept-Language: zh-yue
         Parsed: yue

Accept-Language: ar-afb
         Parsed: afb

Accept-Language: zh-Hans
         Parsed: zh-Hans

Accept-Language: az-Latn
         Parsed: az-Latn

Accept-Language: en-GB
         Parsed: en-GB

Accept-Language: es-005
         Parsed: es-005

Accept-Language: zh-Hant-HK
         Parsed: zh-Hant-HK

Accept-Language: sl-nedis
         Parsed: sl-nedis

Accept-Language: sl-IT-nedis
         Parsed: sl-IT-nedis

Accept-Language: de-CH-1901
         Parsed: de-CH-1901

Accept-Language: de-DE-u-co-phonebk
         Parsed: de-DE-u-co-phonebk

Accept-Language: en-US-x-twain
         Parsed: en-US-x-twain
```

### Actual behavior

Simpler language tags are parsed correctly, but some of the more complex ones are not:

```
Accept-Language: en
         Parsed: en

Accept-Language: ast
         Parsed: ast

Accept-Language: zh-yue
         Parsed: zh

Accept-Language: ar-afb
         Parsed: ar

Accept-Language: zh-Hans
         Parsed: zh

Accept-Language: az-Latn
         Parsed: az

Accept-Language: en-GB
         Parsed: en-GB

Accept-Language: es-005
         Parsed: es-005

Accept-Language: zh-Hant-HK
         Parsed: zh-x-lvariant-HK

Accept-Language: sl-nedis
         Parsed: sl

Accept-Language: sl-IT-nedis
         Parsed: sl-IT-nedis

Accept-Language: de-CH-1901
         Parsed: de-CH-1901

Accept-Language: de-DE-u-co-phonebk
         Parsed: de-DE-x-lvariant-u

Accept-Language: en-US-x-twain
         Parsed: en-US-x-lvariant-x
```

### How to Reproduce?

[i18n-with-quarkus-reactive.zip](https://github.com/quarkusio/quarkus/files/12777404/i18n-with-quarkus-reactive.zip)

1. run the application with `./mvnw clean compile quarkus:dev`
2. either use the included `tests.sh` script to run some `curl` commands, or craft your own with an `Accept-Language` header for the URL `http://localhost:8080/hello`
3. note the response to see if the parsed Locale produces the same language tag as the given header

### Output of `uname -a` or `ver`

Linux laverne 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

**Comment by jamezp** [comment]
FYI I need to look into this for RESTEasy because the change causes TCK failures.
