### ISSUE TITLE
Request parameters not injected in POST/PUT REST methods

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#3624]
**Describe the bug**
When running the rest-json and hibernate-orm-resteasy quickstarts in dev mode, the `Fruit` param isn't injected, causing an NPE in the ORM example, causing null to be appended to the fruit list in the former. This only happens during dev mode, but not when running the actually built JAR. As per @gsmet, things work as expected on 0.21.1.

**Expected behavior**
The fruit parameter is injected also in dev mode.

**Actual behavior**
The fruit parameter is *not* injected  in dev mode.

**To Reproduce**
check out either example from master/develop, then run `mvn compile quarkus:dev`. Open localhost:8080/fruits.html (index.html for the ORM example) and observe how adding a fruit fails.

**Configuration**
See the repo.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by gsmet** [comment]
@stuartwdouglas as it's working properly with 0.21.1, I suspect it's an issue with the new HTTP layer.

Tagging the issue appropriately.

Reproducing it is easy:
- get the quickstarts
- cd rest-json
- mvn clean compile quarkus:dev
- go to http://0.0.0.0:8080/fruits.html
- try to add a fruit
- you end up with the following error in the log:
```
2019-08-21 17:29:07,450 SEVERE [org.ecl.yas.int.Unmarshaller] (executor-thread-1) Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
```
Looks like somehow the correct JSON input is not pushed to the unmarshaller.
