### ISSUE TITLE
Quarkus main fails to parse GraalVM version starting with GraalVM for JDK 22

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#36246]
### Describe the bug

It looks like labsJDK 22 dropped the "old" GraalVM versioning (e.g., `23.1`) from its version:

```
❯ ~/jvms/labsjdk-ce-latest-22+13-jvmci-b01/bin/java -version 
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment (build 22+13-jvmci-b01)
OpenJDK 64-Bit Server VM (build 22+13-jvmci-b01, mixed mode, sharing)

❯ ~/jvms/labsjdk-ce-21-jvmci-23.1-b15/bin/java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

As a result, Quarkus fails to detect the version of GraalVM builds based on LabsJDK 22 onwards.

### Expected behavior

Quarkus should detect the version and not crash.

### Actual behavior

Quarkus fails to detect the version and crashes.

### Additional information

Relates to https://github.com/quarkusio/quarkus/issues/34161

Possible fixes:

1. Rely on getting the value from the `release` file that accompanies the GraalVM build as discussed in https://github.com/quarkusio/quarkus/issues/34161#issue-1765317362
2. Switch to using the new versioning scheme

**Comment by zakkak** [comment]
cc @jerboaa @Karm

**Comment by jerboaa** [comment]
For reference, the native-image output of such a build looks like this:

```
$ native-image --version
native-image 22 2024-03-19
GraalVM Runtime Environment GraalVM CE 22-dev+15.1 (build 22+15-jvmci-b01)
Substrate VM GraalVM CE 22-dev+15.1 (build 22+15, serial gc)
```

```
$ grep GRAAL $GRAALVM_HOME/release
GRAALVM_VERSION="24.0.0-dev"
```

**Comment by jerboaa** [comment]
> Possible fixes:
> 
>     1. Rely on getting the value from the `release` file that accompanies the GraalVM build as discussed in
>     2. Switch to using the new versioning scheme

Could you clarify what this means? Switching to the new versioning scheme?

Option 3:

A quick-fix could also be a simple mapping by only looking at the JDK `feature()` version:

```
JDK 22 => GraalVM Community for JDK 22 => 24.0
JDK 23 => GraalVM Community for JDK 23 => 24.1
JDK 24 => GraalVM Community for JDK 24 => 25.0
JDK 25 => GraalVM Community for JDK 25 => 25.1
```

That mapping has to be done internally in Quarkus due to the maven artefacts too.

**Comment by zakkak** [comment]
> Could you clarify what this means? Switching to the new versioning scheme?

Right now Quarkus performs checks based on the "old" versioning scheme, i.e., GraalVM 22.3, GraalVM 23.1, etc.

Option 2 suggests that Quarkus starts comparing versions using the new versioning scheme GraalVM for JDK 17.0.8, GraalVM for JDK 21.0.0 etc. (after detecting these builds are using it, to avoid cases where 22.3 is seen as newer than  21.0.0)

**Comment by jerboaa** [comment]
> Option 2 suggests that Quarkus starts comparing versions using the new versioning scheme GraalVM for JDK 17.0.8, GraalVM for JDK 21.0.0 etc. (after detecting these builds are using it, to avoid cases where 22.3 is seen as newer than 21.0.0)

Quarkus still supports 23.0, which has a JDK 17 and JDK 20 variant. Imo this is more approachable once GraalVM and JDK version numbers catch up (JDK 25).
