### ISSUE TITLE
Rest client call hangs when receiving an invalid chunked response and does not release resources (e.g. Bulkhead semaphore)

### ISSUE THREAD

**Issue by tmonney** [quarkusio/quarkus#36257]
### Describe the bug

When a `RestClient` resource receives an invalid chunked response (e.g. with missing chunk length), the response is never passed to the caller: the `CompletionStage` or `Uni` is never completed, a plain response is simply blocked indefinitely.
This happens even if the remote server closes the connection.

The behavior can be simulated with Wiremock's `Fault.MALFORMED_RESPONSE_CHUNK`, which writes the `Transfer-Encoding: chunked` header, writes some garbage (and no chunk length), then closes the connection.

When using a simple Vert.x `WebClient` or `HttpClient`,  the request does not hang and the caller gets an `HttpClosedException`, as I would expect.

I also noticed that if a `@Bulkhead` is applied to the resource, each such invalid response acquires a permit from the bulkhead's semaphore and never releases it, potentially exhausting the available permits and making all requests fail until the application is restarted.

### Expected behavior

An invalid chunked response should not hang the client and resources should be properly released when the connection is closed.

### Actual behavior

The client call never completes and resources are not released.

### How to Reproduce?

See https://github.com/tmonney/mp-rest-client-malformed-chunk

### Output of `uname -a` or `ver`

Linux WL-HHDYFL3 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211) 
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

**Comment by geoand** [comment]
Thanks for the reproducer!

I'll have a look ASAP

**Comment by geoand** [comment]
Turns out this was a classic case of forgetting to do proper error handling :(

https://github.com/quarkusio/quarkus/pull/36351 fixes the issue

**Comment by tmonney** [comment]
Great, thanks a lot for the quick fix.

**Comment by geoand** [comment]
🙏
