### ISSUE TITLE
Should a dynamodb table be created automatically in dev mode?

### ISSUE THREAD

**Issue by steven-ww** [quarkusio/quarkus#36266]
### Describe the bug

I've created a lambda that connects to dynamodb to store state from a rest endpoint.

Using this in quarkus dev mode requires I add code that creates the table before I can test locally or the application fails because the table does not exist. The dynamodb is provided via localstack as provisioned by the amazon-dynamodb-enhanced extension starting when quarkus starts so I'm unable to provision the table externally to the program.

I've been using the following code to ensure the table is created

` @Inject
    TimeRecordService(DynamoDbEnhancedClient dynamoEnhancedClient) {
        timeRecordTable = dynamoEnhancedClient.table(getTableName(),
                TableSchema.fromClass(TimeRecord.class));
        timeRecordTable.createTable();
    }`

However, when deployed to AWS the table will be there (at least after the first run).

I can remove this logic and add specific code just to create the table in dev with something like the below maybe?

`  @ApplicationScoped
   @Profile("dev")
   public class DynamoDbTableCreator {
   
       @Inject
       DyanmoDbClient client;
   
       void onStart(@Observes StartupEvent ev) {
           // Create table logic here
       }
   }
`

What's the recommended way to achieve this? How does/should table provisioning work when running against a database in dev mode?

### Expected behavior

Given that quarkus dev is starting the database, I'd assume there would be a mechanism to initialize it/create the table required as part of that start-up process.

### Actual behavior

Tables aren't created. Any interaction with the database fails unless code is added to explicitly create the table.

### How to Reproduce?

- Create a basic quarkus app that uses the amazon-dynamodb-enhanced extension.
- Have the app query a table
- Start the app.
- A LocalStack version of the AWS dynamodb will spin up
- Perform any operation against the app that queries the table
- app fails as the table does not exist.

### Output of `uname -a` or `ver`

Darwin Stevens-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9) Maven home: /opt/homebrew/Cellar/maven/3.9.4/libexec Java version: 17.0.6, vendor: Azul Systems, Inc., runtime: /Users/eework/.sdkman/candidates/java/17.0.6-zulu/zulu-17.jdk/Contents/Home Default locale: en_ZA, platform encoding: UTF-8 OS name: "mac os x", version: "13.5.2", arch: "aarch64", family: "mac"

**Comment by gsmet** [comment]
Hey. Thanks for the suggestion but better ask it in the Quarkus Amazon Services extensions repository there: https://github.com/quarkiverse/quarkus-amazon-services as it's where the change will have to be done. Sébastien is usually very reactive.

Thanks!
