### ISSUE TITLE
Support http/2 and make it available

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#3626]
**Description**
It would be nice if http/2 would be made available to use, for instance, serving a rest api with it. Today, to have it working, I have to create and use a reverse proxy.

**Comment by sean-scott-lr** [comment]
Oh Bummer. I just wasted quite a bit of time trying to get https working ( will open a separate ticket ), so I could try testing http/2 performance.  I really thought I had read that http/2 was supported already. Going back through the docs, I cant find why I thought this.

**Comment by sean-scott-lr** [comment]
Adding more info to help people googling for this...
Here is what h2load says when trying to use quarkus and http2

TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
No protocol negotiated. Fallback behaviour may be activated
Server does not support NPN/ALPN. Falling back to HTTP/1.1.
Application protocol: http/1.1

**Comment by Dudecake** [comment]
I was also surprised because I saw some merged PR's mentioning ALPN.

In my fork on the `alpn` branch I've exposed the HttpServerOptions.useAlpn setting via a new property `quarkus.http.use-alpn`, but it requires one of two things to work:

- A JRE newer than 9;
- The netty-tcnative-boringssl-static dependency (only on JRE version 8).

But this might not be well received because the extra/weird dependency and the new property.

With useAlpn enabled http2 works, even over http.

**Comment by tnmtechnologies** [comment]
It would be nice to take into account the client part too.
Quickstarts would be welcome, a rest api consumed by a client in http2 and another one in http2/TLS.

**Comment by smatijasevic** [comment]
HI is there any progress on providing quarkus support for http2? I am working on project that requires http2.
If someone has some examples, please share.

**Comment by morphy76** [comment]
+1

**Comment by Dudecake** [comment]
> 
> 
> HI is there any progress on providing quarkus support for http2? I am working on project that requires http2.
> If someone has some examples, please share.

If it's just the server parts you need, you can make the changes from https://github.com/Dudecake/quarkus/commit/bce3438dccd896c8ffc5cb16b7658cd49dab7493 as long as you don't mind installing Quarkus in a local repository.

I'll see if I can turn it in a PR this week.

**Comment by gsmet** [comment]
It should be introduced in 1.4: https://github.com/quarkusio/quarkus/pull/7762 .

Maybe you could test the current snapshots and tell us if it works for you?

Our snasphots are there: https://oss.sonatype.org/content/repositories/snapshots/ .

**Comment by gsmet** [comment]
@stuartwdouglas is this an issue we can close?

**Comment by smatijasevic** [comment]
@gsmet version is 1.4.0-SNAPSHOT ?
do I need some extra credentials for that repository?

**Comment by gsmet** [comment]
Version is `999-SNAPSHOT`. No credentials needed.

**Comment by tnmtechnologies** [comment]
I work on functions of the 5G Core Network. It is based on HTTP/2 without or with TLS.
To my knowledge, the MicroProfile rest client is HTTP/1.1 only, and at producer side, HTTP/2 is only allowed with TLS (quarkus 1.10.5.Final).

It seems that gRPC extension works with HTTP/2 without TLS and with TLS.

It would be nice if the quarkus REST layer would allow HTTP / 2 with or without TLS.
