### ISSUE TITLE
ConstraintViolationExceptions thrown from REST endpoints not firing custom ExceptionMapper

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#36276]
### Describe the bug

Not sure if this is by design or not, but when I have the following signature on my rest endpoint where I want to validate the fields in the incoming bean, the validation never happens automatically.

I have to manually call `validator.validate(formData)` using the injected Validator in my class.

I didn't see anything in the docs saying I couldn't annotate a FormBean to use with the validation.
https://quarkus.io/guides/validation

The validation process doesn't happen automatically, uncommenting the validator code works and the validation happens.

*Endpoint*
```java
@POST
    @Path("/ws/orgs/files/")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public Response addOrgFile(@Valid OrgUploadData formData) {
        //Set<ConstraintViolation<OrgUploadData>> errors = validator.validate(formData);
        //if (!errors.isEmpty()) {
       //     throw new ConstraintViolationException(errors);
       // }
        ...rest of code
   }
```

*Formbean*
```java
public class OrgUploadData {

    @RestForm("orgId")
    private Long orgId;

    @RestForm("fileTitle")
    @PartType(MediaType.TEXT_PLAIN)
    @Size(max=10, message = "Title must not be more than {max} characters")
    private String fileTitle;
}
```

### Expected behavior

Validation to automatically happen

### Actual behavior

Have to manually trigger using the validator injection class

### Quarkus version or git rev

3.4.1

**Comment by tmulle** [comment]
I also forgot to mention I'm using Quarkus Renarde to handle the endpoints.
Not sure if that is a factor or not.

I have a Qute frontend calling into the backend which is protected by Renarde and the validation isn't happening automatically.

**Comment by tmulle** [comment]
So, I noticed that the @Valid annotation or even a manual throw of ConstraintViolation exception isn't firing my custom ExceptionMapper.

I'm putting together a global exception handler which formats the incoming exceptions to nicely formatted JSON output based on the type of exception being converted.

This works for other exceptions but it seems the `ConstraintViolationException` isn't being handled.

I tried both the JAX-RS way of using the `@Provider` and the `@ServerExceptionMapper` annotation as described in: https://quarkus.io/guides/resteasy-reactive#exception-mapping

I put together a demo at: https://github.com/tmulle/quarkus-validation-test

To test:

*** Normal Exception ***
1.  Call http://localhost:8080/validate/boom - Notice that the exception mapper is called and logs out to the console.

*** FORM encoded and Multipart Form ****
1. POST a form value of `name` with the contents longer that 5 characters to http://localhost:8080/validate/multipart/auto - Notice the exception mapper is NOT trigger but you get a 400 response back showing the validation error.

Response:
```
{
	"details": "Error id cc56a09b-9721-4c22-8c4e-e70dcc2c785e-1, jakarta.validation.ConstraintViolationException: name: Name cannot be greater than 5 characters",
	"stack": "jakarta.validation.ConstraintViolationException: name: Name cannot be greater than 5 characters\n\tat org.acme.GreetingResource.handleMultiFormManual(GreetingResource.java:59)\n\tat org.acme.GreetingResource$quarkusrestinvoker$handleMultiFormManual_6f1a1832a12c22edbf8d2eb7eae7d9e20ed15c7f.invoke(Unknown Source)\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)"
}```

2. POST the same data to http://localhost:8080/validate/multipart/auto and this time you get a different response back and still the exception mapper is not triggered.

```
ViolationReport{title='Constraint Violation', status=400, violations=[Violation{field='handleMultiFormAuto.request.name', message='Name cannot be greater than 5 characters'}]}```

3. POST the same date to http://localhost:8080/validate/form/auto and make sure the Content-Type of `form-url-encoded` and this is the response you get back and still no exception mapper trigger.

```
ViolationReport{title='Constraint Violation', status=400, violations=[Violation{field='handleFormEncodedAuto.request.name', message='Name cannot be greater than 5 characters'}]}
```

4. POST the same data to http://localhost:8080/validate/form/manual and this is the response and no exception mapper trigger.

```
{
	"details": "Error id cc56a09b-9721-4c22-8c4e-e70dcc2c785e-2, jakarta.validation.ConstraintViolationException: name: Name cannot be greater than 5 characters",
	"stack": "jakarta.validation.ConstraintViolationException: name: Name cannot be greater than 5 characters\n\tat org.acme.GreetingResource.handleFormEncodedManual(GreetingResource.java:30)\n\tat org.acme.GreetingResource$quarkusrestinvoker$handleFormEncodedManual_2eb48224fc1a200a215282a28abf27c800482bb1.invoke(Unknown Source)\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)"
}```



This is with Quarkus 3.4.2 and 3.4.1


This is the resource:
```java
@Path("/validate")
public class GreetingResource {

    @Inject
    Validator validator;

    @POST
    @Path("/form/manual")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.TEXT_PLAIN)
    public Response handleFormEncodedManual(HelloRequest request) {
        Set<ConstraintViolation<HelloRequest>> errors = validator.validate(request);
        if (!errors.isEmpty()) {
            throw new ConstraintViolationException(errors);
        }

        return Response.ok("Hello " + request.getName()).build();
    }

    @POST
    @Path("/form/auto")
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.TEXT_PLAIN)
    public Response handleFormEncodedAuto(@Valid HelloRequest request) {
        return Response.ok("Hello " + request.getName()).build();
    }

    @POST
    @Path("/multipart/auto")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public Response handleMultiFormAuto(@Valid HelloRequest request) {
        return Response.ok("Hello " + request.getName()).build();
    }

    @POST
    @Path("/multipart/manual")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public Response handleMultiFormManual(HelloRequest request) {
        Set<ConstraintViolation<HelloRequest>> errors = validator.validate(request);
        if (!errors.isEmpty()) {
            throw new ConstraintViolationException(errors);
        }
        return Response.ok("Hello " + request.getName()).build();
    }
    
    @GET
    @Path("/boom")
    @Produces(MediaType.TEXT_PLAIN)
    public Response throwException() {
        throw new RuntimeException("Boom!");
    }
}```

This is the bean trying to validate:

``java
public class HelloRequest {
    
    @RestForm
    @Size(max=5, message = "Name cannot be greater than {max} characters")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
}```

**Comment by tmulle** [comment]
This original issue of `@Valid` not being called in endpoints seems like it might be a Quarkus Renarde issue since the demo I put together for this ticket uses straight Quarkus and no Renarde.

I will post a ticket over there because the `@Valid` isn't being called automatically when using Renarde

**Comment by gsmet** [comment]
I think `ConstraintViolationException` are handled by `ResteasyReactiveViolationExceptionMapper` in RESTEasy Reactive so could it just be a matter of priority?

But even when defining the priority, I wonder if the most precise exception mapper won't be selected anyway.

@FroMage and @geoand might know more about this behavior.

**Comment by geoand** [comment]
> I think ConstraintViolationException are handled by ResteasyReactiveViolationExceptionMapper in RESTEasy Reactive

Correct

> But even when defining the priority, I wonder if the most precise exception mapper won't be selected anyway

Correct again, that's what the JAX-RS / Jakarta REST spec mandates - more specific (in terms of the handled exception) exception mappers always take priority over more general ones

**Comment by geoand** [comment]
> Sorry for all the changes, I went down the rabbit hole trying to find where the issue is and there seems to be 2 different issues.

Do you mind summorizing please? 
Thanks

**Comment by melloware** [comment]
Duplicate of #41102

**Comment by tmulle** [comment]
closing since this is related to #41102
