### ISSUE TITLE
Exception in JUnit Extension When Using Parameterized Test With Records

### ISSUE THREAD

**Issue by gilday** [quarkusio/quarkus#36298]
### Describe the bug

A parameterized JUnit 5 test that accepts a record as a parameter causes an exception in the Quarkus JUnit extension.

```
[ERROR] Errors: 
[ERROR]   ExampleResourceTest.testHelloEndpoint(Example)[1] » Conversion 
---- Debugging information ----
cause-exception     : java.lang.UnsupportedOperationException
cause-message       : can't get field offset on a record class: private final java.lang.String com.example.Example.message
class               : com.example.Example
required-type       : com.example.Example
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /com.example.Example/message
line number         : 2
version             : 1.4.20
-------------------------------

```

### How to Reproduce?

[quarkus-parameterized-test-records.zip](https://github.com/quarkusio/quarkus/files/12811380/quarkus-parameterized-test-records.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.localdomain 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24 OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.9.3-bin/326f10f4/apache-maven-3.9.3 Java version: 17.0.8.1, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "14.0", arch: "aarch64", family: "mac"

**Comment by vaclavsvejcar** [comment]
Hi, is there any workaround for this issue or proposed solution? I'm still facing this issue with Quarkus 3.6.5 :(
