### ISSUE TITLE
[Extension Proposal] Jimmer

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#36308]
### Description

`Jimmer` is a revolutionary ORM for `Java` and `Kotlin`, as well as a complete integrated built on top of it — including a powerful cache management mechanism.

### Repository name

quarkus-jimmer

### Short description

Jimmer is a revolutionary ORM for Java and Kotlin

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-jimmer/dev/

### Repository Topics

- quarkus-extension
- object-relational mapping

**Comment by x80486** [comment]
`GitHub` repository: https://github.com/babyfish-ct/jimmer

Jimmer's Home: https://babyfish-ct.github.io/jimmer/

**Comment by gastaldi** [comment]
@x80486 so AFAIU you're asking to lead this extension? Asking because I haven't seen your user in the `Team Members` section

**Comment by x80486** [comment]
I wouldn't know how to do this, to be honest. So I just filed it in case a smart soul wants to take it :sunglasses:

**Comment by gastaldi** [comment]
I don't think there is enough buy-in for this extension, so I'm closing for now. Let's reopen if someone is interested in leading this
