### ISSUE TITLE
Issue with Handling Date and Time Datatypes

### ISSUE THREAD

**Issue by ivantomic77** [quarkusio/quarkus#36303]
### Describe the bug

I am working with Quarkus and I noticed a bug while trying to return an object that has LocalDateTime and/or OffsetDateTime fields.

Every time I want to return some kind of time and date datatype (LocalDate, LocalDateTime, OffsetDateTime, ...) I get this error and even though I have that dependency and the object mapper is configured with it and the module is shown in the list of registered modules, it just throws that exception over and over again. (I tried a few ways to configure object mapper but it seems that it doesn't make a difference). While going through debugger I noticed that my code was right and it didn't produce that error but some other internal method in Response **.ok** part.

**ERROR**:
_Java 8 date/time type `java.time.LocalDate` not supported by default: add Module \"com.fasterxml.jackson.datatype:jackson-datatype-jsr310\" to enable handling_

### How to Reproduce?

To reproduce this issue you will just need a controller with this endpoint, when you call the endpoint you will see the error mentioned above:
```java
    @GET
    @Path("/test")
    public Response something() {
        return Response.ok(LocalDate.now()).build();
    }
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.2283]

### Output of `java -version`

java version "20.0.2" 2023-07-18

### GraalVM version (if different from Java)

GraalVM 20.0.2+9.1

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by gsmet** [comment]
Thanks for the report. This looks a bit odd, could you prepare a small Maven reproducer so that we are sure to test the same thing?

**Comment by ivantomic77** [comment]
@gsmet I created new Quarkus project and was able to reproduce it. How should I send this reproducer project?

**Comment by ivantomic77** [comment]
I think that the problem was using RESTEasy Classic instead of RESTEasy Reactive Jackson.
