### ISSUE TITLE
Integration test fails when using mongo as custom test resource instead of Dev Service

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#36300]
### Describe the bug

I defined a QuarkusTestResourceLifecycleManager that start a mongo instance and set the quarkus.mongodb.devservices.enabled to false. The test fails without even trying to start the mongo container.

### Expected behavior

Test run should start the mongo container first and then run the test

### Actual behavior

Test fails without trying to start the mongo container

### How to Reproduce?

https://github.com/iompo/mongo-custom-test-resource

### Output of `java -version`

OpenJDK Runtime Environment Temurin-11.0.16.1+1

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

**Comment by geoand** [comment]
The problem is in your `MongoResource`. 

You need to do:

```java
String connectionUrl = String.format("mongodb://%s:%s@%s:%d", USERNAME, PASSWORD,container.getContainerName().substring(1), DB_PORT);
```

instead of what you are currently doing.

**Comment by iompo** [comment]
Hi @geoand ,
I tried, but that doesn't seem to solve it. The start method is never called.

**Comment by iompo** [comment]
I've updated the reproducer with the connection url fix. The test fails but no container is started and the mongo image is never pulled from the registry.
