### ISSUE TITLE
Banner doesn't taked into account in native image

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#36328]
### Describe the bug

I customized a banner throught the file banner.txt.
it's works well for an image compiled with 'mvn clean package'
It do'esnt works for an image compiled with 'mvn clean package -Pnative'

### Expected behavior

Having my banner when i launch the executable

### Actual behavior

![image](https://github.com/quarkusio/quarkus/assets/43664834/113392cf-b440-43bc-81f1-e05e429bdb6f)

### Output of `java -version`

![image](https://github.com/quarkusio/quarkus/assets/43664834/0a62149e-3412-43e7-bc3a-3d74e746c9a6)

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

![Uploading image.png…]()

**Comment by Eng-Fouad** [comment]
You need to explicitly add `banner.txt` to be included in the generated native image: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/

**Comment by srigano** [comment]
indeed... Thanks. I need to pass the argument: -H:IncludeResources=

BTW, how can I do that from a 'mvn clean package -Pnative' ? Because I don't interact directly with graalvm.

**Comment by srigano** [comment]
I can see my property in the Log Info during the native compilation :
![image](https://github.com/quarkusio/quarkus/assets/43664834/bd3fbc6f-2164-4801-8e43-111fc3c44cfe)

but banner.txt still not taked in account.

**Comment by Eng-Fouad** [comment]
> indeed... Thanks. I need to pass the argument: -H:IncludeResources=
> 
> BTW, how can I do that from a 'mvn clean package -Pnative' ? Because I don't interact directly with graalvm.
> 
> I tried this in the application.properties, but it doesn't work ![image](https://user-images.githubusercontent.com/43664834/273464154-746f8d5e-903d-4d41-9d92-9559e4eca8b9.png)

Add new file in resources and name it `resource-config.json`. It contains something like:

```json
{
  "resources": {
    "includes": [
      {"pattern": "^banner\\.txt$"}
    ]
  }
}
```

then you can specify this config as `-H:IncludeResources=resource-config.json`.

**Comment by Eng-Fouad** [comment]
> ![image](https://github.com/quarkusio/quarkus/assets/43664834/36b8536b-7a5b-42d7-ae07-2fa606903da0)
> 
> 
> 
> &&
> 
> 
> 
> ![image](https://github.com/quarkusio/quarkus/assets/43664834/e37440a6-9247-44ca-84bd-76c94f2d452a)
> 
> 
> 
> 
> 
> result is:
> 
> 
> 
> ![image](https://github.com/quarkusio/quarkus/assets/43664834/1093637a-1d3b-4a80-8613-b4e3a3e17dd0)
> 
> 
> 
> 
> 
> (under quarkus 3.3.3)

Did you specify [quarkus.banner.path](https://quarkus.io/guides/all-config#quarkus-core_quarkus.banner.path) in application.properties?

**Comment by srigano** [comment]
it's working if i package my application without native compilation and without specifying quarkus.banner.path.
But, i just tried. 
Adding : 
![image](https://github.com/quarkusio/quarkus/assets/43664834/d4170fb0-4590-4ae9-b190-d7af115e688b)

and then it works ... : 
![image](https://github.com/quarkusio/quarkus/assets/43664834/15424e38-f262-4a5c-a4fd-d417f09b8631)

Why this property doesn't be required for classical compilation ?


BTW, is there any way to remove the mention of "Powered by Quarkus X.Y.Z" as mentionned here : 

![image](https://github.com/quarkusio/quarkus/assets/43664834/07cb1f73-ca0e-415e-ba88-add0f8d02eeb)

**Comment by zakkak** [comment]
> it's working if i package my application without native compilation and without specifying quarkus.banner.path.

That should only work if you name the banner file `default_banner.txt`. Are you sure it still worked with a different file name?

Furthermore, placing the `default_banner.txt` file under `src/main/resources` should work out of the box for both JVM and native mode without any special configuration.

If you want to use a different name you can still place it under `src/main/resources` and set `quarkus.banner.path` accordingly and it should work in both JVM and native mode without any additional configuration, e.g.:

```
❯ ls src/main/resources                           
application.properties  banner.txt
❯ mvn clean package -Dnative -Dquarkus.banner.path=banner.txt
❯ ./target/code-with-quarkus-1.0.0-SNAPSHOT-runner           
Hello

Powered by Quarkus 3.13.3
...
```

> is there any way to remove the mention of "Powered by Quarkus X.Y.Z" as mentionned here 

No, that's hardcoded in https://github.com/quarkusio/quarkus/blob/58c2eb59c7ebfc1ff34dfa72d870a042d961c08b/core/deployment/src/main/java/io/quarkus/deployment/steps/BannerProcessor.java#L69
