### ISSUE TITLE
Sending the error message top kafka topic in custom DeserializationExceptionHandler is not working 

### ISSUE THREAD

**Issue by Moustafazeinhaat** [quarkusio/quarkus#36340]
### Describe the bug

I have implemented a custom deserialization exception handler to log the deserialization error and send it to Kafka topic in KafkaStreams application. I have used Emitter, Outgoining annotation, or KafkaProducer but the error was the object in null and not injected. 
This is the code and the class is working well in the error handling that may happen in Kafka streams with and without "ApplicationScoped" but I added it to make sure the dependency injection of the emitter.
`
@Slf4j
@ApplicationScoped
public class StreamsDeserializationExceptionHandler implements DeserializationExceptionHandler {

    @Inject
    @Channel(INVALID_DESERIALIZED_MESSAGES)
    Emitter<KafkaRecord<byte[], byte[]>> emitter;

    @Override
    public DeserializationHandlerResponse handle(ProcessorContext context, ConsumerRecord<byte[], byte[]> record, Exception exception) {
        log.error("Exception happens during deserialization, taskId: {}, topic: {}, partition: {}, offset: {} and exception: {}",
                context.taskId(), record.topic(), record.partition(), record.offset(),
                exception);
        emitter.send(KafkaRecord.of(record.key(), record.value()));
        return DeserializationHandlerResponse.CONTINUE;
    }

    @Override
    public void configure(Map<String, ?> map) {
    }
}`

The below error happens once the deserialization error is being caught in the class

`Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.microprofile.reactive.messaging.Emitter.send(Object)" because "this.emitter" is null`

I am using 3.2.4.Final quarkus platform version

### Expected behavior

When the error happens, it should be sent to the kafka topic 

### Actual behavior

Null pointer exception happens in the emitter

**Comment by ozangunalp** [comment]
The `DeserializationExceptionHandler` instance is not a CDI-managed bean but is created by the Kafka Streams application, via reflection. So you cannot use CDI injection or `@Channel` annotation on that class. The workaround is to create the `KafkaProducer` instance manually as shown in here : https://kafka.apache.org/20/documentation/streams/developer-guide/config-streams.html#default-deserialization-exception-handler

**Comment by Moustafazeinhaat** [comment]
@ozangunalp  I have already implemented this work around and worked fine with me. The case here I was wondering why soe type of handlers are not being a component in Quarkus and have the CDI injection cycle. 

`@Override
    public DeserializationHandlerResponse handle(ProcessorContext context, ConsumerRecord<byte[], byte[]> record, Exception exception) {
        ProducerRecord<String, ErrorMessage>  producerRecord = new ProducerRecord<>(INVALID_DESERIALIZED_MESSAGES,
                record.topic(), new ErrorMessage(record.partition(), record.offset(), key, value,
                            exception.getMessage()));
        kafkaProducer.send(producerRecord);
        return DeserializationHandlerResponse.CONTINUE;
    }

    @Override
    public void configure(Map<String, ?> map) {
        Properties properties = new Properties();
        properties.put("bootstrap.servers", map.get("bootstrap.servers"));
        properties.put("key.serializer", StringSerializer.class.getName());
        properties.put("value.serializer", ErrorMessageSerializer.class.getName());
        kafkaProducer = new KafkaProducer<>(properties);`
