### ISSUE TITLE
Getting the remaining time in millis from AWS Lambda Context returns negative value

### ISSUE THREAD

**Issue by debae** [quarkusio/quarkus#3634]
**Describe the bug**
When you call the getRemainingTimeInMillis() method from the AmazonLambdaContext you get a negative value. 
We use this value for example when our Lambda function needs to perform an HTTP call, and we want to limit the request timeout to this value.

**Expected behavior**
Normally this should return the amount of milliseconds before the lambda stops.

**Actual behavior**
It returns a negative value, which should never be possible.

**To Reproduce**
Call the method getRemainingTimeInMillis() on AmazonLambdaContext

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.21.0

**Comment by debae** [comment]
The bug resides in AmazonLambdaContext
`
    @Override
    public int getRemainingTimeInMillis() {
        return (int) (runtimeDeadlineMs - Math.round(System.nanoTime() / 1_000_000d));
    }
`

If you look in the documentation :  https://docs.aws.amazon.com/lambda/latest/dg/java-context-object.html , it states : **Returns the number of milliseconds left before the execution times out.**
and in https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html which holds the documentation about the header **Lambda-Runtime-Deadline-Ms** – The date that the function times out in Unix time milliseconds.

I think it would be sufficient to change the code to 
`
    @Override
    public int getRemainingTimeInMillis() {
        return (int) (runtimeDeadlineMs - System.currentTimeMillis());
    }
`

Will create a pull request containing this change.

**Comment by jaikiran** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/3640
