### ISSUE TITLE
The API method KafkaStreams#cleanUp() is not applicable when use @Produces to build the topology

### ISSUE THREAD

**Issue by Moustafazeinhaat** [quarkusio/quarkus#36341]
### Describe the bug

To delete the Kafka streams application’s local state directory on any machines where the Kafka streams application instance was run. You must do this before restarting an application instance on the same machine. 

You can use this method:The API method KafkaStreams#cleanUp() in your application code.

The is issue is that the clean up process is not applicable when we use @Produces to build the topology as below:

`@Produces
    public Topology buildTopology() {
        StreamsBuilder builder = new StreamsBuilder();
 return builder.build();
    }`

The Kafka streams is created by quarkus internally and there is no any control to clean up the streams before start up.

Kafka reference: [https://kafka.apache.org/24/documentation/streams/developer-guide/app-reset-tool.html](url)

### Expected behavior

Have a separate function that can clean up the streams before start.

### Actual behavior

there is no way to clean up the kafka streams 

### Output of `java -version`

openjdk version "17.0.2" 

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by ozangunalp** [comment]
I think it is legitimate to add a CDI event that will trigger before the scheduling the KafkaStreams to start.
I am just not sure if sending KAfkaStreams in that event is sufficient.
Because in my tests cleanUp does not successfully delete the local state store directory.
@Moustafazeinhaat would you have any feedback on this?

**Comment by Moustafazeinhaat** [comment]
@ozangunalp  I have used it to clean up  Kafka streams in my test case and worked fine. I have developed three test containers based on a same embedded Kafka server and the streams failed in this case until I added the clean up function. I do think It's working in my case

**Comment by ozangunalp** [comment]
How did you add the cleanup function to the quarkus Kafka streams app?
