### ISSUE TITLE
Hibernate Reactive + Panache: deleteById doesn't seem to work

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkusio/quarkus#36350]
### Describe the bug

I'm currently implementing some code for deleting from the database for which I'm using deleteById. The problem is that even though I get true from deleteById the entity still persists in the db. I have enabled sql logging, and Quarkus is sending a select query instead of a delete query. Also, I'm using reactive PostgreSQL client.

This is a query which is send by Quarkus when calling deleteById:
```
2023-10-09 12:45:54,891 DEBUG [org.hib.SQL] (vert.x-eventloop-thread-3) 
    select
        t1_0.uuid,
        t1_0.name 
    from
        test t1_0 
    where
        t1_0.uuid=$1
Hibernate: 
    select
        t1_0.uuid,
        t1_0.name 
    from
        test t1_0 
    where
        t1_0.uuid=$1
      
```

### Expected behavior

The record with the specified id should be deleted.

### Actual behavior

The record is not deleted.

### How to Reproduce?

Reproducer: https://github.com/zZHorizonZz/quarkus-bug-deletebyid

You can just run ExampleResourceTest it will fail as a GET call after deleting returns data even though it shouldn't.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.23555.1000]

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2

**Comment by yrodiere** [comment]
Clarification: this is about Hibernate Reactive + Panache.

cc @DavideD @FroMage

**Comment by DavideD** [comment]
For CRUD operations, transactions are required.
It will work if you add the `@WithTransaction` annotation:
```java
    @POST
    @Path("/delete")
    @WithTransaction
    public Uni<Response> delete(@QueryParam("uuid") String uuid) {
        ...
    }
```

**Comment by FroMage** [comment]
Well, shouldn't it throw an exception when there's no transaction, rather than pretend everything went well?

**Comment by FroMage** [comment]
Oh, so you're saying nothing was flushed, but if it was, it would have thrown? I thought the ORM behaviour was to throw if there was a mutating operation without a TX, no? If yes, then this differs.

**Comment by DavideD** [comment]
What I'm saying is that Hibernate Reactive behaves a bit differently than ORM. We don't enforce transactions at the moment.

**Comment by FroMage** [comment]
Oh, well. OK, if that's documented, then.

**Comment by devsecops-node** [comment]
> For CRUD operations, transactions are required. It will work if you add the `@WithTransaction` annotation:
> 
>     @POST
>     @Path("/delete")
>     @WithTransaction
>     public Uni<Response> delete(@QueryParam("uuid") String uuid) {
>         ...
>     }

it's work for me, thank you
