### ISSUE TITLE
Extend kafka-avro-serializer versions supported in native mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#36372]
### Description

Extend kafka-avro-serializer versions supported in native mode

Currently the supported versions in native mode end with `7.2.x` - https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/kafka-schema-registry-avro.adoc?plain=1#L796
CC @cescoffier 

Added in https://github.com/quarkusio/quarkus/commit/203b46cd1a8ca5a7db6a5c80df1a038c03860e01

According to https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/ the latest available version of kafka-avro-serializer is 7.5.1

We tried to move to 7.5.0 and it failed in native.

We are using 7.3.1 without problems - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/pom.xml#L26

**Comment by ozangunalp** [comment]
I think there was an additional dependency to add. I'll take a look.

**Comment by ozangunalp** [comment]
@rsvoboda can you take a look if this issue can be related #35763 ? 
The issue mentions that the problem starts with kafka-avro-serializer 7.4.0.
See [my comment](https://github.com/quarkusio/quarkus/issues/35763#issuecomment-1708027767) for the fix I proposed.
If that's not the same issue I'll dig in more.

Thanks!

**Comment by rsvoboda** [comment]
Hi @ozangunalp, adding csv dataformat dependency makes the update possible.

Is there an issue on confluent side to add `com.fasterxml.jackson.dataformat:jackson-dataformat-csv` into their direct dependency tree?

I think we need update of [kafka-schema-registry-avro.adoc?plain=1#L796](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/kafka-schema-registry-avro.adoc?plain=1#L796) to mention the need for additional csv dependency when using 7.4 and 7.5 in native mode.

Will we keep listing all the "supported" versions in that doc?

**Comment by rsvoboda** [comment]
And `integration-tests/kafka-avro-apicurio2` could be bumped to 7.5 based kafka-avro-serializer

**Comment by ozangunalp** [comment]
> Is there an issue on confluent side to add `com.fasterxml.jackson.dataformat:jackson-dataformat-csv` into their direct dependency tree?

@rsvoboda now there is https://github.com/confluentinc/schema-registry/issues/2788
