### ISSUE TITLE
`quarkus.test.integration-test-profile` ignored in IT startup error message if startup fails because of ConfigValidationException

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#36376]
### Describe the bug

If I set this:

```properties
quarkus.test.integration-test-profile=integrationtest
```

and for some reason my application fails to start in integration tests, **during config resolution**, the error message looks like this:

```
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
```

... even though the profile prod is NOT active, as evidenced by the command being executed:

```
Executing "... -Dquarkus.profile=integrationtest ..."
```

### Expected behavior

```
ERROR: Failed to start application (with profile [integrationtest])
```

### Actual behavior

```
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00011: Could not expand value maven.test.data.path in property uris.quarkusio.local
        at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1001)
        at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:961)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:961)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:647)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        ... 7 more
```

### How to Reproduce?

Just adding something like this to an application should have done the trick:

```properties
quarkus.test.integration-test-profile=integrationtest
%integrationtest.hello.message=${some-unresolved-property}
```

Assuming the application also includes this:

```java
@Path("/hello")
public class GreetingResource {

    @ConfigMapping(prefix = "hello")
    public interface MyConfig {
        String message();
    }

    @Inject
    MyConfig config;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return config.message();
    }
}
```

But here's a full reproducer:

```shell
git clone -b i36376 https://github.com/yrodiere/quarkus-playground.git
cd quarkus-playground
./mvnw clean verify -Dnative
```

When build ends (it'll take a while), see how the logs are inconsistent:

```
[...]
Executing "/home/yrodiere/workspaces/testcases/quarkus-playground/target/code-with-quarkus-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/yrodiere/workspaces/testcases/quarkus-playground/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.profile=integrationtest -Dquarkus.datasource.password=quarkus -Dquarkus.datasource.db-kind=postgresql -Dquarkus.datasource.jdbc.url=jdbc:postgresql://localhost:43893/quarkus?loggerLevel=OFF -Dquarkus.datasource.username=quarkus -Dquarkus.hibernate-orm.database.generation=drop-and-create"
[...]
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
[...]
```

The first line shows `-Dquarkus.profile=integrationtest` but the error shows `with profile [prod]`.

### Additional information

I think this can only be reproduced if the startup failure happens during config resolution. That would make sense, as in that case I suspect `ConfigUtils.getProfiles()` just returns garbage that doesn't take config into account, so this would not behave properly:

https://github.com/quarkusio/quarkus/blob/700e37b6dca14771c771dc969b66e41e7c6684e0/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L196-L199

**Comment by yrodiere** [comment]
I see we have a special case for `io.quarkus.runtime.configuration.ConfigurationException`:

https://github.com/quarkusio/quarkus/blob/700e37b6dca14771c771dc969b66e41e7c6684e0/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L190-L200

Maybe we need something similar for `io.smallrye.config.ConfigValidationException`?

**Comment by geoand** [comment]
> Maybe we need something similar for io.smallrye.config.ConfigValidationException?

Seems reasonable

**Comment by dvasml** [comment]
@geoand `io.smallrye.config.ConfigValidationException` is external exception not from quarkus-core, how to catch it within ApplicationLifecycleManager ?

**Comment by dvsingh9** [comment]
@geoand io.smallrye.config.ConfigValidationException is external exception not from quarkus-core, how to catch it within ApplicationLifecycleManager ?

**Comment by MaciejDromin** [comment]
Hello @yrodiere I started investigating this issue but couldn't quite reproduce it. Also when I build my custom quarkus-core project changing ```ApplicationLifecycleManager.java``` and included it as dependency it seems that those changes did not have any effect. Do you have maybe some hints for the newcomer? :)

**Comment by yrodiere** [comment]
Hey @MaciejDromin , thanks for having a look.

I updated the issue description with a reproducer.

Note however that #37401 *might* have fixed the problem already. I'm not entirely sure, one would have to run the reproducer against a build of Quarkus on the `main` branch.

**Comment by MaciejDromin** [comment]
@yrodiere Thanks for your reply! I was able to test this with the latest code and the issue still occurs. I created PR fixing this, hope it is good enough :)
