### ISSUE TITLE
Setting base image layer and application layer cache in Jib build

### ISSUE THREAD

**Issue by elendis** [quarkusio/quarkus#36379]
### Description

The Jib `Containerizer` allows configuration of the [base image layer cache](https://github.com/GoogleContainerTools/jib/blob/440bd4897c6c427cc9a491128aa76c72378d605b/jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java#L214) and the [application layers cache](https://github.com/GoogleContainerTools/jib/blob/440bd4897c6c427cc9a491128aa76c72378d605b/jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java#L227).

Would it be possible to allow setting these values when building via Quarkus? 

We would like move these caches to a different folder on our CI system. 

### Implementation ideas

Add corresponding `ConfigItems` to [`ContainerImageJibConfig`](https://github.com/quarkusio/quarkus/blob/main/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/ContainerImageJibConfig.java) and use the values (if set) when creating the `com.google.cloud.tools.jib.api.Containerizer` in [`JibProcessor#createContainerizer`](https://github.com/quarkusio/quarkus/blob/89a01424ecfdb32378188eefc1459081bca639c9/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L271).

**Comment by geoand** [comment]
Sounds perfectly reasonable. 

Would you like to provide a PR adding this feature?

**Comment by elendis** [comment]
Sure, I can give it a go :-) This will be my first open source contribution and there is some admin stuff to sort out with my employer, so this might take a moment though...

**Comment by geoand** [comment]
No problem!

Let us know if you need any help

**Comment by elendis** [comment]
Just created a PR for this, if anythings missing or needs to be changed let me know!
