### ISSUE TITLE
quarkus-jdbc-db2: resource bundle missing

### ISSUE THREAD

**Issue by louisa-fr** [quarkusio/quarkus#36399]
### Describe the bug

I'm using quarkus-jdbc-db2 with xa-transactions (version 3.2.6.Final) + camel. 

When an exception occurs and the application executes a rollback, I can see some logs that point to a missing resource bundle: 

```
WARN: Datasource 'DB2DB': [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4201, SQLSTATE=2D521
```
```
WARN: ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:cbed:652644ec:16, node_name=quarkus, branch_uid=0:ffff7f000101:cbed:652644ec:18, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.BaseXAResource@42665326) failed with exception code ARJUNA016099: Unknown error code:0
: javax.transaction.xa.XAException: Error trying to end xa transaction: [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4228, SQLSTATE=null
```
This happens in native mode, but not in jvm mode. 

I have also found other tickets in which this behaviour is mentioned in different contexts. 
- https://github.com/quarkusio/quarkus/issues/22711#issuecomment-1007494676
- https://github.com/quarkusio/quarkus/issues/11395#issuecomment-674153928

In the first ticket, someone has posted a file where the missing resource bundles seem to be listed: https://github.com/quarkusio/quarkus/issues/22711#issuecomment-1010052100

related zulip topic: 
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Db2.20resource.20bundle

### Expected behavior

It would be good, if there were no missing resource bundle logs. 

### How to Reproduce?

Reproducer: 
https://github.com/louisa-fr/quarkus-db2-resource-bundle-reproducer
(see README of repository)

**Comment by gsmet** [comment]
@louisa-fr I created https://github.com/quarkusio/quarkus/pull/36403 that seems to resolve that particular issue. I had other issues though with your reproducer so not sure just fixing that problem will make it fully work.
Unfortunately, the Db2 driver is obfuscated and we don't have the sources so we are playing whack-a-mole here.

**Comment by gsmet** [comment]
Thanks for the awesome reproducer btw.

**Comment by louisa-fr** [comment]
Thanks for resolving this issue so quickly ! 
Yeah, I think I saw some other errors in the reproducer ,too, that didn't occur in our environment, but I thought as long as the resource bundle is triggered it's fine and I didn't want to invest too much time, but I'll definitely check
