### ISSUE TITLE
Tooltips for enum values are rendered incorrectly in documentation of configuration properties

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#36401]
### Describe the bug

See for example https://quarkus.io/guides/scheduler#scheduler-configuration-reference

### Expected behavior

All enum values should be rendered correctly.

### Actual behavior

Only the first enum value is rendered correctly, the other ones seem off:

![image](https://github.com/quarkusio/quarkus/assets/412878/e809fb30-90dc-4274-8a9d-bbc2b1397783)

**Comment by nderwin** [comment]
I think I've narrowed this down to a problem with how the `<p>` tag is being interpreted in the javadocs for the enum values - these are being replaced with 2 newlines (`\n`) when translated into the asciidoc file, but that seems to break the formatting into HTML.

Either the javadoc could be updated to remove the paragraph tags, or the parser updated to use asciidoc hard line breaks.

Thoughts?

**Comment by yrodiere** [comment]
> these are being replaced with 2 newlines (\n) when translated into the asciidoc file

Right, that's the correct translation.

> that seems to break the formatting into HTML.

> the parser updated to use asciidoc hard line breaks

I'm not sure this would make sense as I think the parser is used in other contexts. Also, if you mean `<br>`, that's not the correct translation for `<p>`.

> Thoughts?

I'm not sure why this breaks exactly so this may be irrelevant, but can't we wrap the generated asciidoc of each tooltip into an [open block](https://docs.asciidoctor.org/asciidoc/latest/blocks/open-blocks/)?

**Comment by yrodiere** [comment]
> these are being replaced with 2 newlines (\n) when translated into the asciidoc file

Right, that's the correct translation.

> that seems to break the formatting into HTML.

> the parser updated to use asciidoc hard line breaks

I'm not sure this would make sense as I think the parser is used in other contexts. Also, if you mean `<br>`, that's not the correct translation for `<p>`.

> Thoughts?

I'm not sure why this breaks exactly so this may be irrelevant, but can't we wrap the generated asciidoc for the description of each enum into an [open block](https://docs.asciidoctor.org/asciidoc/latest/blocks/open-blocks/)?

**Comment by nderwin** [comment]
No, not `<br>`, but `" +\n"` instead of `"\n"`.

I'm not sure about the open block, if it would work inside the table cell that contains the enum values, or if having multiple open blocks would work.

**Comment by yrodiere** [comment]
Only one way to find out :)

Personally I'd rather avoid changing the way <p> is translated by the parser because it would potentially affect a lot more than just these tooltips (I think?). At least open blocks can be used to wrap tooltips specifically and nothing else.

But if we really have to... whatever works and doesn't break formatting for the rest of the guides is fine to me.

**Comment by nderwin** [comment]
Good news - I created a small reproducer so the build cycle is shorter;  bad news - neither the open blocks nor the asciidoc hard line breaks seemed to help.  What did help, was to smash it all together in one line (but then I don't get the tooltips at all, probably an issue with the reproducer).

**Comment by nderwin** [comment]
`mvn clean install` in the `greeting-extension` directory;  the HTML docs are in the docs module in the `target` directory.

[greeting-extension.zip](https://github.com/quarkusio/quarkus/files/13189710/greeting-extension.zip)

**Comment by nderwin** [comment]
I did just confirm if I take the `<p>` tags out of the javadoc, then it generates the HTML without the extra noise (but I'd rather not have that as the solution either):

![image](https://github.com/quarkusio/quarkus/assets/3226831/01786a5e-7161-44d8-bee5-16fd6585588a)

**Comment by nderwin** [comment]
An updated reproducer that generates the HTML page with the same magic that quarkus.io uses, giving the tooltip hover.

It boils down to those newlines inside of the square brackets surrounding the tooltip text.  If we take those out, it'll generate the HTML nicely.  I haven't stumbled onto an asciidoc combo to allow leaving those in... yet.

[greeting-extension.zip](https://github.com/quarkusio/quarkus/files/13196202/greeting-extension.zip)

**Comment by michalvavrik** [comment]
> It boils down to those newlines inside of the square brackets surrounding the tooltip text. If we take those out, it'll generate the HTML nicely. I haven't stumbled onto an asciidoc combo to allow leaving those in... yet.

I'm only judging by your analysis and I'll be happy if you come with better solution, but if it goes down to the newlines inside tooltip description, I'd just strip it. Tooltip description is inline block and you can't expect paragraphs work there anyway.
