### ISSUE TITLE
quarkus-smallrye-graphql-client can't be configured through env vars

### ISSUE THREAD

**Issue by kovacevicm** [quarkusio/quarkus#36439]
### Describe the bug

Trying to pass in URL for the typesefe GraphQL client as an environment variable doesn't work.

Setting the url with `QUARKUS_SMALLRYE_GRAPHQL_CLIENT__(CLIENT NAME HERE)__URL` or `QUARKUS_SMALLRYE_GRAPHQL_CLIENT_(CLIENT NAME HERE)_URL` environment variables results in client throwing an error about the URL not being configured.

The behaviour is the same, whether  the client name (config key) contains hyphens or not.

### Expected behavior

`QUARKUS_SMALLRYE_GRAPHQL_CLIENT__(CLIENT NAME HERE)__URL` sets the URL of the GraphQL client with the corresponding config key, as per [quarkus.smallrye-graphql-client."clients".url](https://quarkus.io/guides/all-config#quarkus-smallrye-graphql-client_quarkus.smallrye-graphql-client.-clients-.url)

### Actual behavior

URL is not set.

### How to Reproduce?

Steps to reproduce:
1. Use https://github.com/quarkusio/quarkus-quickstarts/tree/main/microprofile-graphql-client-quickstart
2. Comment out the line https://github.com/quarkusio/quarkus-quickstarts/blob/main/microprofile-graphql-client-quickstart/src/main/resources/application.properties#L2
3. Define env var `QUARKUS_SMALLRYE_GRAPHQL_CLIENT__STAR_WARS_TYPESAFE__URL` with the URL from the previous step
4. Run the app and send a GET localhost:8080/typesafe request

**Comment by jmartisk** [comment]
Please read the warning at the end of section 1.2 here: https://quarkus.io/guides/config-reference#environment-variables

I think this is your case - clients are configured as a map, and there are some limitations for mapping such env properties bidirectionally to config properties. I assume you can work around this, as mentioned in the warning, by adding a custom config source, which tells Quarkus that the property exists, but doesn't have to provide the value. Like this:

```
public class ExtraConfigSource implements ConfigSource {

    @Override
    public int getOrdinal() {
        return 275;
    }

    @Override
    public Set<String> getPropertyNames() {
        return Set.of("quarkus.smallrye-graphql-client.star-wars-dynamic.url");
    }

    @Override
    public String getValue(String s) {
        return null;
    }

    @Override
    public String getName() {
        return "ExtraConfigSource";
    }
}
```

It should then work when you supply
```
QUARKUS_SMALLRYE_GRAPHQL_CLIENT_STAR_WARS_DYNAMIC_URL=https://swapi-graphql.netlify.app/.netlify/functions/index
```
at runtime

Can you please try this solution and tell whether it works for you?

**Comment by kovacevicm** [comment]
I've actually opted for a less involved solution by having   `quarkus.smallrye-graphql-client.star-wars-dynamic.url=${NAME_OF_MY_ENV_VAR}`.

However, the issue originates from the internal implementation of quarkus-smallrye-graphql-client (namely [here](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientsConfig.java#L23)) and I would still consider it a defect, since the behaviour is not as advertised in the configuration reference.
It's quite a gotcha.

Would reimplementing GraphQLClientsConfig in the fashion of [RestClientsConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java#L27) avoid the name mapping issue since it doesn't seem to relay on a Map at all?

**Comment by ntkoopman** [comment]
I ran into this issue today. QUARKUS_SMALLRYE_GRAPHQL_CLIENT_DEFAULT_URL is actually setting `quarkus.smallrye.graphql.client.default.url` instead of `quarkus.smallrye-graphql-client.default.url`. Adding an empty `quarkus.smallrye-graphql-client.default.url=` to `application.properties` seems to make it use the correct key. (Quarkus 3.5.3)

**Comment by gsmet** [comment]
While I wonder if we could actually fix the case just above @radcortez (as my understanding is that we have a list of the mapping around for the unknown properties so couldn't we use these mappings to improve solving the simple cases and make this map more useful?), I think it's an intrinsic limitation of mapping env vars to configuration property: you need to guide the resolution as env vars can translate to many config options.

It's especially the case with maps where the content of the map needs to be properly translated.

I'm going to close this one as there is a workaround and I'm not sure we can find something that would solve all the cases (and it would make things a bit surprising if changing the name to include a space, a dot or whatever would break things).

**Comment by radcortez** [comment]
`@ConfigMapping` automatically matches the correct env name. The `graphql` extension still uses the old `@ConfigRoot`.
