### ISSUE TITLE
Virtual-Threads Support for quarkus-reactive-routes

### ISSUE THREAD

**Issue by charleslip** [quarkusio/quarkus#36430]
### Description

At mid-Oct 2023, "quarkus-resteasy-reactive" and "quarkus-smallrye-reactive-messaging" are ready for Virtual-Threads execution.

Would Virtual-Threads support be coming to "quarkus-reactive-routes" soon?

**Comment by mkouba** [comment]
Well, a reactive route executed on a virtual thread sounds a bit like an oxymoron but it should be quite straightforward ;-). 

We would have to wrap the generated handler and execute it on the event loop. Something like this should work:

```java
public void handle(RoutingContext context) {
        Context vertxContext = VertxContext.getOrCreateDuplicatedContext(VertxCoreRecorder.getVertx().get());
        VertxContextSafetyToggle.setContextSafe(context, true);
        vertxContext.runOnContext(new Handler<Void>() {
            @Override
            public void handle(Void event) {
                VirtualThreadsRecorder.getCurrent().execute(new Runnable() {
                    @Override
                    public void run() {
                        generatedHandler.handle(context);
                    }
                });
            }
        });
    }
```

WDYT @cescoffier

**Comment by mkouba** [comment]
FTR virtual threads are also supported in [gRPC](https://quarkus.io/version/main/guides/grpc-virtual-threads) and [Scheduler](https://quarkus.io/version/main/guides/scheduler-reference#virtual_threads) extensions.

**Comment by cescoffier** [comment]
@mkouba yes, it's exactly that. We are also exposing the virtual thread scheduler as a bean (not sure it got merged). 

About the oxymoron, we may want to rename later. @geoand is working on a proposal for RestEasy reactive.

**Comment by geoand** [comment]
That's right, I should have an ADR we can discuss in the team meeting next week
