### ISSUE TITLE
Context Propagation in combination with RequestContext and PostConstruction

### ISSUE THREAD

**Issue by wglanzer** [quarkusio/quarkus#36448]
### Describe the bug

It seems, that request scoped beans get generated multiple times, if the "PostConstruct" hooks needs some time and the beans are called in multiple threads simultaneously. I think I did all "configuration" steps correctly, including using a `ManagedExecutor` and propagate the `ThreadContext.CDI` in propagated contexts.

### Expected behavior

Beans annotated via `RequestScoped` should not get generated multiple times, because this may lead to unexpected problems during parallel initialization.

### How to Reproduce?

I created a small JUnit test for this:

``` java 
@QuarkusTest
public class Demo
{
  @Inject
  private MyBean bean;

  @Inject
  @ManagedExecutorConfig(propagated = ThreadContext.CDI)
  private ManagedExecutor exec;

  @ParameterizedTest
  @ValueSource(ints = {1, 10, 100})
  void shouldInitOnce(int pParallelizationCount)
  {
    // reset inner calls
    MyBean.instances.set(0);

    // run X calls on our injected bean
    CompletableFuture.allOf(
        IntStream.range(0, pParallelizationCount)
            .mapToObj(pIdx -> CompletableFuture.runAsync(() -> bean.doSomething(), exec))
            .toArray(CompletableFuture[]::new)
    ).join();

    // check the created instances
    assertEquals(1, MyBean.instances.get());
  }

  @RequestScoped
  public static class MyBean
  {
    private static final AtomicInteger instances = new AtomicInteger(0);

    public void doSomething()
    {
    }

    @SneakyThrows
    @PostConstruct
    public void onConstruct()
    {
      instances.incrementAndGet();

      // simulate a long running task
      Thread.sleep(50);
    }
  }
}
```

There you can see, that the `MyBean#onConstruct()` is forced to take at least 50ms. This leads to test failures, if the parallelization count is larger than 1.

### Output of `uname -a` or `ver`

Darwin wglanzer-mb.home.lan 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

### Output of `java -version`

GraalVM 17.0.8

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

**Comment by wglanzer** [comment]
Hi @manovotn,

thank you for your patience! 
I was already afraid that this use case could not be covered 100%. 
Is there anything "easy" I can do and "work around" it? Do you have any idea, how I can implement such a locking by myself for specific beans?

If you do not have any idea, then I'll have to rework my code as you described - should not be too complicated anyway.
I use quarkus as a framework for a command line application, that may get refactored as a "standalone service" in the future. I use the "RequestContext" to scope a single "application call" - seems a bit strange, I know, but should be future proof :D

**Comment by manovotn** [comment]
> Is there anything "easy" I can do and "work around" it? Do you have any idea, how I can implement such a locking by myself for specific beans?

You won't be able to implement the context locking yourself.
As for workaround, you should be able to use those beans once created so make sure they are already stored in the context that you are propagating - in other words, you could have them eagerly created once the context is activated (add an observer for `@Initialized(RequestScoped.class)` into each req. scoped bean that needs this). But it's far from nice and can quickly become a nightmare :)

> If you do not have any idea, then I'll have to rework my code as you described - should not be too complicated anyway.

If it's not complicated, then I'd suggest going that way instead.

> I use quarkus as a framework for a command line application, that may get refactored as a "standalone service" in the future. I use the "RequestContext" to scope a single "application call" - seems a bit strange, I know, but should be future proof :D

Alternatively, you could end up creating a custom scope/context and use that.
However, it's far from easy to setup and context propagation cannot automatically propagate it for you; which may be fine, come to think of it - you may want to control the activation.

**Comment by wglanzer** [comment]
Thanks man, I did my refactoring, so this one is no longer a big dealbreaker for me.
The idea of an own context seems nice, I'll have a look at it tomorrow.
Feel free to close this issue, if it won't be fixed anyway 👍
