### ISSUE TITLE
Develop a tool to analyze our CI raw logs

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36449]
## Context

We sometimes (often?) have CI jobs hitting the 6 hours timeout. When it does, we have absolutely no idea what's going on:

- is it the GitHub Actions runner being slow?
- is it a particular module causing issues?

Being in the dark is detrimental to us understanding what's going on.

## Implementation ideas

In the case of the JVM builds, we do not use concurrency so we could parse the log sequentially.

Ideally, it would take the form of a JBang script that we could call to analyze a particular file, previously downloaded locally:

```
./analyzeRawLogs.java my-raw-log.log
```

The output would be:
```
name of module    | time
```
ideally properly padded and with time units.

We would also need the sum of it all at the end of the output.

Ideally we would have the ability to keep it chronological, sorted by name or sorted by duration (longer, first). The CLI needs to have options for sorting.

As the execution is sequential, we can start the counter for a given counter when we encounter a line starting with `[INFO] Building `:

```
2023-10-09T22:04:58.0208987Z [INFO] Building Quarkus - Analytics - Common 999-SNAPSHOT              [1/1057]
```

The name of the module is whatever is between building and the version. The version will be of the form numbers and dots suffixed by `-SNAPSHOT` (`999-SNAPSHOT`, `2.16.999-SNAPSHOT`).

You would then consider a module finished when the next one starts and get the duration from there.

Things are a bit more complex for the last module. I think it could be considered finished when you encounter `[INFO] --------------------------` followed by `[INFO] Reactor Summary` but you would have to take into account the timestamp of the separator line as going to the Reactor Summary line takes time.

Another option is that the last item might not be properly ended because the build timed out (and that's probably when we will have a look at the logs the most). In this case, I'm not sure what the end trigger would be but in any case, the module needs to be marked as unfinished and probably put at the top when sorted by longer. We can dig a bit more this case when we get there.

## Resources

An example of a Quarkus-powered command line JBang script can be found here: https://github.com/gsmet/quarkus-release/blob/main/prerequisites.java 

An example of raw log can be downloaded here:
- [raw-log.log](https://github.com/quarkusio/quarkus/files/12883726/raw-log.log)

An example of unfinished job raw log can be downloaded here:
- [unfinished-raw-log.log](https://github.com/quarkusio/quarkus/files/12883744/unfinished-raw-log.log)

## Additional notes

:warning: this is a good first issue but please work on it only if you think you can relatively autonomous on the coding side. The description has been made very detailed so that you have a good idea of what needs to be done. Obviously, if there are questions, don't hesitate to ask.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign it to me.

**Comment by milinddethe15** [comment]
I'm encountering a problem with inconsistent output across runs. I would greatly appreciate some assistance in resolving this issue.

**Comment by gsmet** [comment]
We would need a lot more details in order to be able to help you.

**Comment by milinddethe15** [comment]
How should I share script file with you?

**Comment by gsmet** [comment]
You can attach the script to a comment.

But describing your issue would help. Maybe you can make it work with the samples I provided and then we can discuss?

**Comment by milinddethe15** [comment]
The script:
```
//#!/usr/bin/env jbang "$0" "$@"
//DEPS info.picocli:picocli:4.6.1

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Command(name = "analyzeRawLogs", mixinStandardHelpOptions = true, version = "1.12",
        description = "Analyzes raw log files from JVM builds.")
public class analyzeRawLogs implements Runnable {

    @Parameters(index = "0", description = "Path to the raw log file.")
    private String logFilePath;

    @Option(names = "--sort", description = "Sort output by 'name' or 'duration'. Default is 'chronological'.")
    private String sortOption = "chronological";

    private static final Pattern BUILD_START_PATTERN = Pattern.compile("\\[INFO\\] Building (.*?) (\\d[\\d.]*-SNAPSHOT).*?\\[(\\d+)/(\\d+)]");
    private static final Pattern BUILD_END_PATTERN = Pattern.compile("\\[INFO\\] --------------------------");
    private static final Pattern REACTOR_SUMMARY_PATTERN = Pattern.compile("\\[INFO\\] Reactor Summary:");

    public static void main(String[] args) {
        CommandLine.run(new analyzeRawLogs(), args);
    }

    @Override
    public void run() {
        try (BufferedReader reader = new BufferedReader(new FileReader(logFilePath))) {
            String line;
            Map<String, Long> moduleDurations = new HashMap<>();
            String currentModule = null;
            long moduleStartTime = 0;

            while ((line = reader.readLine()) != null) {
                Matcher buildStartMatcher = BUILD_START_PATTERN.matcher(line);
                Matcher buildEndMatcher = BUILD_END_PATTERN.matcher(line);
                Matcher reactorSummaryMatcher = REACTOR_SUMMARY_PATTERN.matcher(line);

                if (buildStartMatcher.find()) {
                    if (currentModule != null) {
                        long duration = System.currentTimeMillis() - moduleStartTime;
                        moduleDurations.put(currentModule, moduleDurations.getOrDefault(currentModule, 0L) + duration);
                    }
                    currentModule = buildStartMatcher.group(1) + " " + buildStartMatcher.group(2);
                    moduleStartTime = System.currentTimeMillis();
                } else if ((buildEndMatcher.find() || reactorSummaryMatcher.find()) && currentModule != null) {
                    long duration = System.currentTimeMillis() - moduleStartTime;
                    moduleDurations.put(currentModule, moduleDurations.getOrDefault(currentModule, 0L) + duration);
                    currentModule = null;
                    moduleStartTime = 0;
                }
            }

            if (currentModule != null) {
                long duration = System.currentTimeMillis() - moduleStartTime;
                moduleDurations.put(currentModule, moduleDurations.getOrDefault(currentModule, 0L) + duration);
            }

            moduleDurations.entrySet().stream()
                    .sorted((entry1, entry2) -> {
                        if ("duration".equals(sortOption)) {
                            return Long.compare(entry2.getValue(), entry1.getValue());
                        } else {
                            return entry1.getKey().compareTo(entry2.getKey());
                        }
                    })
                    .forEach(entry -> {
                        System.out.printf("%-40s | %d ms%n", entry.getKey(), entry.getValue());
                    });

            long totalDuration = moduleDurations.values().stream().mapToLong(Long::longValue).sum();
            System.out.printf("Total Duration: %d ms%n", totalDuration);

        } catch (IOException e) {
            System.out.println("Error reading the log file: " + e.getMessage());
        }
    }
}
```
---
Executing the script on provided log sample.
Running `jbang analyzeRawLogs.java raw-log.log`, output:
```
.
.
.
Quarkus - WebSockets Client 999-SNAPSHOT | 0 ms
Quarkus - gRPC - API 999-SNAPSHOT        | 0 ms
Quarkus - gRPC - Code Gen 999-SNAPSHOT   | 0 ms
Quarkus - gRPC - Deployment 999-SNAPSHOT | 0 ms
Quarkus - gRPC - InProcess 999-SNAPSHOT  | 0 ms
Quarkus - gRPC - Protoc Plugin 999-SNAPSHOT | 0 ms
Quarkus - gRPC - Runtime 999-SNAPSHOT    | 0 ms
Quarkus - gRPC - Stubs for health and reflection 999-SNAPSHOT | 0 ms
Quarkus - gRPC - xDS 999-SNAPSHOT        | 0 ms
Quarkus - gRPC Common - Deployment 999-SNAPSHOT | 0 ms
Quarkus - gRPC Common - Runtime 999-SNAPSHOT | 0 ms
Quarkus - gRPC Common 999-SNAPSHOT       | 0 ms
Quarkus - gRPC parent 999-SNAPSHOT       | 0 ms
Total Duration: 3 ms
``` 
---
Again Running `jbang analyzeRawLogs.java raw-log.log`, output:
```
.
.
.
Quarkus - WebSockets Client - Deployment 999-SNAPSHOT | 0 ms
Quarkus - WebSockets Client - Runtime 999-SNAPSHOT | 0 ms
Quarkus - WebSockets Client 999-SNAPSHOT | 0 ms
Quarkus - gRPC - API 999-SNAPSHOT        | 0 ms
Quarkus - gRPC - Code Gen 999-SNAPSHOT   | 0 ms
Quarkus - gRPC - Deployment 999-SNAPSHOT | 0 ms
Quarkus - gRPC - InProcess 999-SNAPSHOT  | 0 ms
Quarkus - gRPC - Protoc Plugin 999-SNAPSHOT | 0 ms
Quarkus - gRPC - Runtime 999-SNAPSHOT    | 0 ms
Quarkus - gRPC - Stubs for health and reflection 999-SNAPSHOT | 0 ms
Quarkus - gRPC - xDS 999-SNAPSHOT        | 0 ms
Quarkus - gRPC Common - Deployment 999-SNAPSHOT | 0 ms
Quarkus - gRPC Common - Runtime 999-SNAPSHOT | 0 ms
Quarkus - gRPC Common 999-SNAPSHOT       | 0 ms
Quarkus - gRPC parent 999-SNAPSHOT       | 0 ms
Total Duration: 2 ms
```
---
Issue: problem with inconsistent output across runs. 
I found that executing same code again and again gives different total time.

**Comment by gsmet** [comment]
A couple of comments:
- the idea is to determine how much time it took to build a module, you're measuring how much time it takes to analyze it. You need to get the timestamps from the log file and calculate the duration from the timestamps
- When extracting the timestamp, you should drop it from the line and make sure the patterns are matching the beginning of the line to make sure we don't have false positives (we are building nested modules and we don't want to take them into account).

**Comment by azthec** [comment]
@milinddethe15 I have some time to take a look if you want, do you have a git repository for this script where I could work with you?

**Comment by milinddethe15** [comment]
Hi @azthec , I am not currently working on this. You can work on this with above script.

**Comment by azthec** [comment]
@gsmet You can assign this to me if you want, I have a working prototype just needs some cleaning up

**Comment by gsmet** [comment]
@azthec the easiest way to contribute this would be to create a pull request with the script hosted in the `.github` directory.

**Comment by azthec** [comment]
Alright I just haven't had time to open a pr yet, maybe tomorrow

Op wo 18 okt. 2023 15:54 schreef Guillaume Smet ***@***.***>:

**Comment by azthec** [comment]
@gsmet I've opened a functioning draft PR if you want to take a peek, it still needs cleaning up and handling a few branches (eg log ends abruptly or last module)

**Comment by gsmet** [comment]
@azthec I'll have a look as I need it already :). Thanks a lot, I'll follow up in the PR.

**Comment by gsmet** [comment]
Implemented in https://github.com/quarkusio/quarkus/pull/36574 .
