### ISSUE TITLE
Enhance OIDC token propagation filters to select named OIDC clients

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#36458]
### Description

OIDC token propagation filters, before propagating the tokens, can exchange them with the OIDC server to set the correct target service audience, with this token exchange supported by a named OIDC client. 
Right now, it is not possible to associate a specific named OIDC client with a specific REST Client annotated with the `@AccessToken` which enabled a token propagation filter for this REST Client, see #36440

### Implementation ideas

Allow to use `@AccessToken` like this:
```
@AccessToken("named-oidc-client")
interface MyRestClient {
   @GET
   String getData();
}
```

Similarly to how it can be done for `OidcClientFilter`.

Additionally it should be possible to use `@AccessToken` to customize an exchange token requirement when a default client is used as it is not really needed for named clients

**Comment by sberyozkin** [comment]
I got this enhancement request closed by mistake

**Comment by michalvavrik** [comment]
I'll have a look.

> Additionally it should be possible to use @AccessToken to customize an exchange token requirement when a default client is used as it is not really needed for named clients

@sberyozkin can you give me a hint what you meant by this - how should it be possible to customize exchange token requirement? Or at least what should be possible to do, I just need little context, link or class reference, not much. Thanks

**Comment by michalvavrik** [comment]
> I'll need to refresh my memory, what exactly I meant it can only be of interest to the default client.

Way I see it when you select `@AccessToken("client-1")` then you signal that token should be exchanged (otherwise why you bothered to specify the client anyway), however for default client you didn't specify any name, hence you should also give additional option to enable exchange per `AccessToken` annotation instance.
