### ISSUE TITLE
Vertx 3.8 and new sql client break compatibility / quickstart

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3647]
Vertx 3.8 and new sql client (introduced in https://github.com/quarkusio/quarkus/pull/3513) break compatibility / quickstart

Apps using reactive pg client can't be compiled with artifacts from master, main problem is `package io.reactiverse.axle.pgclient does not exist`. Example of such app is `using-vertx` quickstart.

Package io.reactiverse.axle.pgclient is present in smallrye-axle-postgres-client-0.0.7.jar, but not in smallrye-axle-pg-client 0.0.8 where packages changed from `io.reactiverse.*` to `io.vertx.*`.

Also noticed that PgRowSet is no longer available, RowSet must be used instead.

The last thing is that `reactive-postgres-client.adoc` still references reactiverse - e.g. `@Inject io.reactiverse.axle.pgclient.PgPool client`

This is breaking change for the apps, but https://github.com/quarkusio/quarkus/pull/3513 doesn't have any special label.
Do we want to introduce this package name change or is there a way to mitigate this issue on end-user space - e.g. do the package name trick using bytecode manipulation?

**Comment by gsmet** [comment]
No, we change the package.

Let's not pile up compatibility code while we are not 1.0 yet.

But... let's make it a noteworthy-feature so that I include a note in the announcement.

**Comment by rsvoboda** [comment]
OK, so I will prepare PR for Quickstarts + PR for reactive-postgres-client.adoc

**Comment by gsmet** [comment]
Thanks! And thanks for catching it, otherwise I would have had to fix it when releasing!

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus/pull/3648
https://github.com/quarkusio/quarkus-quickstarts/pull/259

**Comment by gsmet** [comment]
Both PRs have been merged, closing.
