### ISSUE TITLE
Native image build with Dockerfile.native-micro misses libraries

### ISSUE THREAD

**Issue by Stwissel** [quarkusio/quarkus#36478]
### Describe the bug

Created the code-with-quarkus example with Java21 and latest quarkus and tried to produce a native image:

```bash
mvn clean package -Dnative
docker build --file src/main/docker/Dockerfile.native-micro --tag native-is-fun .
docker run -i --rm -p 8080:8080 native-is-fun
```

Same issue with Dockerfile.native

### Expected behavior

```bash
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-10-13 16:36:52,119 INFO  [io.quarkus] (main) native-is-fun  native (powered by Quarkus 3.4.2) started in 0.015s. 
Listening on: http://0.0.0.0:8080
```

### Actual behavior

```bash
./application: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./application)
./application: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./application)
```

### How to Reproduce?

Reproducer:

```bash
quarkus create app
cd code-with-quarkus
mvnw clean package -Dnative
docker build --file src/main/docker/Dockerfile.native-micro --tag native-is-fun .
docker run -i --rm -p 8080:8080 native-is-fun
```

### Output of `uname -a` or `ver`

Linux stwmultipass 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15) OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

This one works:

```bash
 quarkus build --native \
    -Dquarkus.native.container-build=true \
    -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 \
    -Dquarkus.container-image.build=true
```

**Comment by zakkak** [comment]
@Stwissel when building native executables using a locally installed Mandrel or GraalVM version the native executable will get linked against the hosts libraries which in your case appear to be using a newer version than the one used in the UBI and Quarkus micro images:

```
❯ docker run --rm registry.access.redhat.com/ubi8/ubi-minimal:8.8 ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

❯ docker run --rm quay.io/quarkus/quarkus-micro-image:2.0 ldd --version                                           
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

As you rightfully point out, using the Quarkus builder image resolves this.

If you still want to build using a local Mandrel or GraaLVM installation you will need to make it use a compatible glibc version.
