### ISSUE TITLE
Panache simplfied query + CTE with

### ISSUE THREAD

**Issue by zakariafadili** [quarkusio/quarkus#36496]
### Describe the bug

Hibernate ORM panache does not recognize syntax starting with **"WITH"** according to the syntax provided in Hibernate 2.0 for enabling recursive queries (CTE). 

In fact, the query "**WITH** xxx AS (Select ...) Select * FROM xxx"  is replaced by "FROM *** WHERE **WITH**..." which is incorrect.

### Quarkus version or git rev

3.2

**Comment by StephenOTT** [comment]
+1

**Comment by vedantshetty** [comment]
+1

**Comment by FroMage** [comment]
Ah yes, this is a recent HQL change indeed, we need to fix our query parsing.
