### ISSUE TITLE
No mention of the Stork extension in Stork guides?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36507]
In the Stork guides, there is no mention of the Stork extension i.e. we don't add it to the created project.
We mention some individual Stork dependencies but not the extension.

It looks a bit off?

See https://quarkus.io/guides/stork for instance but I think all the guides have this problem.

(This issue is part of various things noted when I added the :topics: to the guides)

**Comment by cescoffier** [comment]
The stork extension comes automatically when using gRPC or the rest client.

However, we recently added a programmatic API, which means we should revisit the doc to mention the extension in this case.

**Comment by aureamunoz** [comment]
Yes the extension is added transitively by the clients. 
Yes, I agree, we have mention this a few times with Clement and maybe add an example of this use case. I will work on this.

**Comment by gsmet** [comment]
Ah OK. I think it might be worth mentioning that the extensions comes transitively.

Anyway, not worth keeping an issue around if there's no real problem, closing, thanks!
