### ISSUE TITLE
Multitenancy support using the application.properties file

### ISSUE THREAD

**Issue by victorl2** [quarkusio/quarkus#3651]
**Description**
Multitenancy is used by many apps implementing the hibernate interfaces, in order to make those applications in *the quarkus style*, would be interesting enable the possibility of using multitenancy with only **application.properties**,  avoiding the creation of a **persistence.xml** as recommended by the docs.

**Comment by victorl2** [comment]
I implemented some code using the hibernate interfaces with the persistence.xml, but is **not** well polished/integrated with quarkus. Could someone give me a **direction** on *how can i approach this implementation for the multitenancy support ?*

**Comment by machi1990** [comment]
@gsmet is this issue somehow related to https://github.com/quarkusio/quarkus/issues/2759 ?

**Comment by victorl2** [comment]
Do we have any expectation to include multitenancy in future releases ?

**Comment by loicmathieu** [comment]
@victorl2 multi-tenancy is already tracked via #2835 and #5681

Can I close this one ?
You can still subscribe to the aformentioned issue if you want.

**Comment by gsmet** [comment]
BTW, if someone wants to provide a PR with some ITs covering multi-tenancy, that might help making it a reality.

**Comment by victorl2** [comment]
@loicmathieu no problem, we can close this issue,  the two issues you listed already cover what i described.
