### ISSUE TITLE
Using Jackson support for builder pattern fails in native mode

### ISSUE THREAD

**Issue by misl** [quarkusio/quarkus#3652]
When using Jackson builder pattern support (@JsonPOJOBuilder) things work fine in JVM mode, but fail in Native mode.

Simple example of a POJO Builder:
```
@JsonPOJOBuilder(buildMethodName = "build", withPrefix = "with")
public class BeanBuilder {
    private int idValue;
    private String nameValue;
 
    public BeanBuilder(int id) {
        idValue = id;
    }
 
    public BeanBuilder withName(String name) {
        nameValue = name;
        return this;
    }
 
    public MyModel build() {
        return new MyModel(this);
    }
}
```

Both the model and builder are in a separate (reusable) jar library.

Using this library to deserialize a JSON message results in the following error (native compilation only):

```
2019-08-20 13:30:24,559 ERROR [...MessageHandler] (vert.x-eventloop-thread-0) Message failed:: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Builder class MyModel$Builder does not have build method (name: 'build')
 at [Source: (String)"{ some proper }"; line: 1, column: 1]
```
Somehow it seems native compilation makes the build() method disappear. What changes do I need to make to get native compilation to work?

A reproducer can be found [here](https://github.com/misl/quarkus-jackson-builder)

**Comment by gwenneg** [comment]
Hi @misl!

I'm not sure this will help considering the `InvalidDefinitionException` message you had, but could you try adding the `@RegisterForReflection` to the `Builder` class? I have some doubts because this annotation usually solves issues about missing classes during Jackson serialization/deserialization, but maybe this will have an effect in your case.

**Comment by misl** [comment]
Just the `@RegisterForReflection` does not help. I tried that. According to the mail thread I also need to index my model library:

```
On Wed, Aug 21, 2019 at 2:50 PM Guillaume Smet wrote:

    Hi Minto,

    Yeah, GraalVM thinks that the method is useless so the Dead Code Elimination removes it from the image.

    For now, your best bet is to mark your class with `@RegisterForReflection` (and you need to have your separate library indexed - see https://stackoverflow.com/a/55513723/5043585 ).

    But we need to address this in the Jackson extension. Could you create a GitHub issue with a reproducer?

    Thanks!

```

**Comment by misl** [comment]
I want to try and fix this one myself, but I have no clue where to start. Obviously the Jackson extension needs to be enhanced. How:

- Fix all classes annotated with Jackson's `@JsonPOJOBuilder`.
- Make sure these classes (and all of their methods) will not be eliminated

But how can I achieve this? Is these any extension that already does something similar?

**Comment by gsmet** [comment]
Yes, there are a lot of examples but it's hard to find a simple one.

The best one I could find out of my head is:
https://github.com/quarkusio/quarkus/blob/master/extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java#L134-L139
.

You need to create a @BuildStep in which you inject the Jandex index and
the reflective classes producer, look for your annotation and produce
reflective class build item for the classes.

-- 
Guillaume

**Comment by geoand** [comment]
Like @gsmet said there a lots of examples scattered throughout the codebase.
Looking at the various methods that produce a ReflectiveClassBuildItem should get you pretty far.

**Comment by misl** [comment]
Finally I managed to enhance the Jackson extension, however I noticed extensions hardly have any tests (if at all). Why is that?

I used my reproducer project for testing, so it can probably also be used for automated testing of the extension.

**Comment by geoand** [comment]
Best add an integration test project for Jackson (if there isn't one already).

**Comment by misl** [comment]
Changes have been merged, issue can be closed.
