### ISSUE TITLE
Vert.x gets blocked for ordered task execution when `quarkus.thread-pool.queue-size` is set 

### ISSUE THREAD

**Issue by ahus1** [quarkusio/quarkus#36530]
### Describe the bug

The configuration option [quarkus.thread-pool.queue-size](https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.queue-size) can be used to make the Quarkus executor thread pool reject threads. I use it for load tests of Keycloak for load shedding in an overload situation.

Due to https://github.com/eclipse-vertx/vert.x/issues/4900 this can lead to the Vert.x TasksQueue to be permanently blocked, when an ordered task is submitted and it is rejected.

This issue is for tracking the current behavior which is included in Vert.x 4.4.x in the current versions of Quarkus. It will be part of the upcoming Vert.x 4.5.0 version (https://github.com/eclipse-vertx/vert.x/pull/4904), and I've asked for backport to 4.4.x (https://github.com/eclipse-vertx/vert.x/pull/4912). 

### Expected behavior

When setting `quarkus.thread-pool.queue-size`, the task execution shouldn't stall.

### Actual behavior

The task execution is stalled until the Quarkus application is restarted as a variable is not cleared when the rejected exception is thrown.

### How to Reproduce?

See https://github.com/eclipse-vertx/vert.x/issues/4900. For Keycloak, this happend when I called `MutinyHelper.blockingExecutor(vertx)` - see https://github.com/keycloak/keycloak/issues/23919

### Quarkus version or git rev

3.2.6.Final

**Comment by cescoffier** [comment]
Unfortunately, the fix is only for Vert.x 4.5. I cannot tell when 4.5 will be integrated in Quarkus, unlikely this year.

**Comment by ahus1** [comment]
Thank you @cescoffier - that's good to know. 

I've created a backport for Vert.x 4.4.x here https://github.com/eclipse-vertx/vert.x/pull/4912 - let's see if it gets accepts and when there will be a another 4.4.x release.

**Comment by ahus1** [comment]
Update: The backport to 4.4.x has been accepted, but there is currently no planned release for a Vert.x 4.4.x release until more changes accumulate.

**Comment by cescoffier** [comment]
Closed - Vert.x has been updated.
