### ISSUE TITLE
Support load shedding for HTTP requests

### ISSUE THREAD

**Issue by ahus1** [quarkusio/quarkus#36543]
### Description

For the Keycloak project, we've been running load tests and found that load shedding increases the stability of the system when handling overload situations. Without load shedding, an overload situation could lead to Pods restarting, which would make it even harder for the system to recover.

We think this situation is similar also for other users of Quarkus, so we're asking for an enhancement in Quarkus for this.

Load Shedding is IMHO important for blocking requests as those would queue up in the system and lead to very long processing times until the request is processed. Once it is then processed, the answer might no longer be relevant to the caller, and it might have run into a timeout.

Even for non-blocking requests there is still a resource usage with the number of connections, and the number of requests in flight which could eventually overload the event loop. With Keycloak doing cryptographic operations like password hashing and token signing, this a situation that is very real. 

For that, we've been experimenting with different approaches and tried to use the things Quarkus has already to offer.

**1. The naive approach: to use `quarkus.thread-pool.queue-size`**

A first naive approach was to use `quarkus.thread-pool.queue-size` to limit the number of queued blocking requests.
Once a blocking requests exceeds the queue size, there is a rejected execution exception which by default would return a 500 (server error) and creates a lot of logs on the console. We also found that in some cases Vert.x wasn't handling this well (#36530). Also not being able to differentiate between probes (health, liveness, readiness) and metrics which were also shedded was problematic, as it would lead to pod restarts if the liveness probe was also shedded. With #36434 being implemented, probes will no longer be shedded as they will become non-blocking, but metrics will remain blocking. 

Given the drawbacks listed above, and not finding another existing Quarkus option, we started looking for something else (see below). 

**2. More sophisticated attempt: LoadSheddingHandler**

The next attempt was to implement a Handler in Vert.x which would keep count of all requests in flight, and would respond with a 503 (server unavailable) once a given limit is exceeded. 

The PR https://github.com/keycloak/keycloak/pull/23343 is an attempt to do this (see class `LoadSheddingHandler`): 

* Define a predicate which routes to be ignored (health and metrics in our case)
* Set up a semaphore to keep track of how many requests are currently processed
* Add a logging summary of how many requests were dropped
* Future enhancement: expose a metric about accepted and rejected requests

The results we got from this in our tests are quite promising, were meeting our expectations. As stated above, we think this situation is similar also for other users of Quarkus, so we're asking for an enhancement in Quarkus for this.

### Implementation ideas

The `LoadSheddingHandler` from the Keyclak PR could be a starting point for an implementation which could come bundled with Quarkus.

The configuration options for such a handler would be: 

* Number of concurrent requests allowed (threshold) - in our case we would set it to 1000 if we're running a system which usually processes up to 200 requests per second to have a maximum expected queue time of 5 seconds.
* Routes to be excluded - in our case health and metrics, might be additional endpoints in other scenarios

**Comment by vmuzikar** [comment]
This is potentially superseded by #36860

**Comment by ahus1** [comment]
Closing this one as it has been superseded by #36860 and we'll use it in Keycloak for now. Still would like to see a more fine-grained approach to differentiate between different URLs (management vs. non-management URLs). So if someone wants to see something like this, please comment here to re-open the issue and the discussion. Thanks!

**Comment by tmonney** [comment]
We have mostly the same requirement: our application is quite latency-sensitive and it's better for us to reject requests fast rather than queue them. Ideally, we would like to be able to
* distinguish management and non-management URLs
* bump the logging level to at least INFO when a connection is rejected
* expose metrics for rejected connections
* ideally, be able to register some kind of listener so that the application can be notified and/or react whenever a request is rejected.
