### ISSUE TITLE
@MailerName not working with different SMTP servers

### ISSUE THREAD

**Issue by wansors** [quarkusio/quarkus#36567]
### Describe the bug

Quarkus fails to send emails using different SMTP servers when using: @MailerName

The config is readed ok by quarkus, however the problem is that the SMTPConnectionPool returns always the same connection with the same MailConfig. Making all @MailerName to use the same connection.

![image](https://github.com/quarkusio/quarkus/assets/15862396/218fdf56-8208-4c93-b595-bf86b79089f9)

### Expected behavior

Each @MailerName should use its own SMTPConnectionPool. And send the emails using each connection

### Actual behavior

Each @MailerName share the same SMTPConnectionPool. And send the emails using only one connection

### How to Reproduce?

Use the code on:
https://github.com/wansors/quarkus-multiple-mailers-test

Try sending emails on dev using the endpoints:
`http://localhost:8080/smtp/send/1
http://localhost:8080/smtp/send/2`

One @MailerName  is using an incorrect port, however mails are send anyway because the vertex SMTPConnectionPool returns always the same config

### Quarkus version or git rev

3.4.3

**Comment by cescoffier** [comment]
Thanks for the reproducer. How do you run the smtp server?

**Comment by cescoffier** [comment]
Sorry, you are using mail pit! That's great!
