### ISSUE TITLE
Should we update S2iBaseJavaImage and OpenshiftBaseJavaImage?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36577]
I was looking for something else entirely and stumbled upon `S2iBaseJavaImage` and `OpenshiftBaseJavaImage` where I was surprised we didn't have anything more recent than JDK 11 for instance.

Maybe it's expected but I thought I should ask.

/cc @iocanel @geoand @cescoffier

**Comment by gsmet** [comment]
@iocanel pinging you again here as this is becoming problematic if we want to move to Java 17 entirely.

**Comment by cescoffier** [comment]
Hey @maxandersen @iocanel, the list of images looks very outdated. I don't believe we should recommend using these partially unmaintained images. Can you explain how these images are used and try to see how we can curate this list? Note that I don't see Java 17 and 21 in the list - which is kind of annoying... Java 11 is so 2018...

**Comment by iocanel** [comment]
I think that we can just drop them. I think that we've been migrating away from them to the point they should be no longer used

**Comment by iocanel** [comment]
Hmmm, the native one is still used.

**Comment by iocanel** [comment]
Ages ago, we introduced these to magically set things like needed env variables, paths etc based on the selected image. 
As, maintaining those was becoming an issue and also too much magic was adding confusion, we decided to move away from these. At the moment they have no effect, as the images that they reference are too old.

I'll create a PR to wipe them.
