### ISSUE TITLE
Support of Embedded and ManyToOne nested object projection + Support of @ProjectedFieldName on class fields

### ISSUE THREAD

**Issue by humcqc** [quarkusio/quarkus#36581]
### Description

1) Add support of @Embedded and @XXXToOne nested objects in panache query projection.

2) When you use Lombok for DTO, it could be helpfull to have the @ProjectedFieldName annotation available for fields instead of constructor parameters.

### Implementation ideas

Add support in CommonPanacheQueryImpl#project

**Comment by humcqc** [comment]
Proposal in PR: https://github.com/quarkusio/quarkus/pull/36594

**Comment by humcqc** [comment]
Hi @FroMage , @loicmathieu, @yrodiere 
Any chance someone can have a look?
Without this i cannot use projection and need to use mapstruct that is less efficient
Thanks

**Comment by yrodiere** [comment]
I don't have time for this, sorry. Maybe somebody else will. In any case, I'm sure @FroMage accepts pull requests :)

**Comment by humcqc** [comment]
Hello, @FroMage @loicmathieu any possible update ?

**Comment by humcqc** [comment]
Hello @yrodiere , should I add other people to have a chance for this to move forward ?  Seems @FroMage and @loicmathieu  doesn't have time to look at this. Is there anything I can do to unblock ?

**Comment by yrodiere** [comment]
> Is there anything I can do to unblock ?

Yes, you can work with the Panache maintainers (i.e. not me, but @FroMage or maybe @loicmathieu or someone else) to provide a pull request yourself.

**Comment by humcqc** [comment]
Thanks @yrodiere, @FroMage , @loicmathieu any chance to have some feedback ?

**Comment by loicmathieu** [comment]
Hi @humcqc,
Sorry for the late feedback; your PR somehow goes under my radar. I'll try to have a look this week.

**Comment by humcqc** [comment]
Thanks @loicmathieu
