### ISSUE TITLE
Unit test always succeeds in combination with hibernate-reactive & panache

### ISSUE THREAD

**Issue by sebveit** [quarkusio/quarkus#36582]
### Describe the bug

I experience an unwanted behaviour in unit testing with assertions.
I've set up a fresh app via https://code.quarkus.io/
and followed the guide on https://quarkus.io/guides/hibernate-reactive-panache.
My written unit test should/must fail but succeeds nevertheless.

The following dependencies are installed for the app:
```
// Quarkus
implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
implementation("io.quarkus:quarkus-arc")
testImplementation("io.quarkus:quarkus-junit5")
// Flyway
implementation("io.quarkus:quarkus-flyway")
implementation("io.quarkus:quarkus-jdbc-postgresql")
// Hibernate Reactive
implementation("io.quarkus:quarkus-hibernate-reactive-panache")
implementation("io.quarkus:quarkus-reactive-pg-client")
testImplementation("io.quarkus:quarkus-test-hibernate-reactive-panache")
```

### Expected behavior

final Animal animal = new Animal();
animal.name = "danger noodle";
asserter.execute(() -> animal.persist());
asserter.assertEquals(() -> Animal.count(), 2L); // Should already fail here!
asserter.execute(() -> Animal.deleteAll());
asserter.fail(); // Must definitely fail here!

### Actual behavior

Unit test always succeeds, even if I intentionally write a broken test.

### How to Reproduce?

Reproducer: https://github.com/sebveit/reproducer-quarkus-hibreactpanache-unittesting

Steps to reproduce the behaviour:
1. Check out the reproducer
2. Import the app into your IDE
3. Run unit test (make sure you have docker running on your sys)

### Output of `uname -a` or `ver`

Darwin Tfcbtujbo-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.5.0.RC1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          21 (Homebrew 21)
OS:           Mac OS X 12.7 x86_64

**Comment by DavideD** [comment]
I'm not sure I can fix it, but I will have a look and see if I can pinpoint the issue

**Comment by DavideD** [comment]
I think I've found the bug, I will try to fix it

**Comment by DavideD** [comment]
PR sent: https://github.com/quarkusio/quarkus/pull/36599
