### ISSUE TITLE
Quarkus Dev: null resource when accessing from a library

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#36591]
### Describe the bug

When accessing resources from a Java library in Quarkus Dev mode, null is returned. E.g.:

```
MyClass.class.getClassLoader().getResource("my-resource.file");
```

will return null. If the same resource is accessed in the Quarkus app itself, the resource will be returned.

On the other hand, this works just fine if running a `@QuarkusTest` or running the build fast-jar. It is only a problem in dev mode.

### Expected behavior

Accessing resources in libraries in dev mode should work

### Actual behavior

Accessing resources in libraries in dev mode returns null

### How to Reproduce?

I have created a reproducer app [here](https://github.com/AndreasPetersen/quarkus-dev-null-resource/tree/main). In the reproducer I am using [swagger-parser](https://github.com/swagger-api/swagger-parser), which will access a resource file [here](https://github.com/swagger-api/swagger-parser/blob/1656aa9f2b349e95206950bd1a9eafc32ab5648e/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ClasspathHelper.java#L18C17-L18C17). The error can also be reproduced if you publish your own library which accesses a resource.

To reproduce:

```
cd my-app
quarkus dev
```

then in another terminal:

```
curl localhost:8080/hello
```

observe an exception.

On the other hand, running tests and running the build jar works:

```
./gradlew test
```

```
./gradlew build
java -jar build/quarkus-app/quarkus-run.jar
```

followed by a REST request:

```
curl localhost:8080/hello
```

### Output of `uname -a` or `ver`

Linux codespaces-cee154 6.2.0-1014-azure #14~22.04.1-Ubuntu SMP Wed Sep 13 16:15:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24 LTS OpenJDK Runtime Environment Microsoft-8297089 (build 17.0.8.1+1-LTS) OpenJDK 64-Bit Server VM Microsoft-8297089 (build 17.0.8.1+1-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.3 ------------------------------------------------------------  Build time:   2023-08-17 07:06:47 UTC Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5  Kotlin:       1.9.0 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.8.1 (Microsoft 17.0.8.1+1-LTS) OS:           Linux 6.2.0-1014-azure amd64

**Comment by geoand** [comment]
The library should almost certainly be doing:

```java
Thread.currentThread().getResource("my-resource.file");
```

**Comment by geoand** [comment]
>  Can you explain why, or point to documentation explaining why? Why is this only a problem in dev mode

It's a typical problem in environments which do not have a flat classloader hierarchy. Unfortunately many libraries do not behave properly...
It only happens in dev-mode because that mode contains multiple classloaders in order to support fast live-reloading

> I actually want to use this 3rd party library, and can't just change it easily myself

Are you sure the library doesn't contain a method that allows you to pass in the ClassLoader?

**Comment by AndreasPetersen** [comment]
> Unfortunately many libraries do not behave properly...

When creating my own libraries, how can I make sure they have properly? Is it preferred to use `Thread.currentThread().getContextClassLoader().getResource("my-resource.file")` as suggested previously?

> Are you sure the library doesn't contain a method that allows you to pass in the ClassLoader?

In this concrete case, I can load the resource myself using `Thread.currentThread().getContextClassLoader().getResource("my-resource.file")`, and then pass the contents of the file to the library, instead of having the library load the file itself.

**Comment by geoand** [comment]
Libraries should have an option for the user to pass in the ClassLoader used to load resources.

In the absence of that, the usual approach is to first try `Thread.currentThread().getContextClassLoader()` then the ClassLoader of the class that loaded the class attempting to locate the resource.

**Comment by geoand** [comment]
🙏🏼
