### ISSUE TITLE
QuarkusSecurityTestExtension should not call CDI.current() when annotation is not present.

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#36601]
### Describe the bug

In the `QuarkusSecurityTestExtension.afterEache(...)` method, CDI is called without checking if `@TestSecurity` annotation is present. 

This prevents the usage of `quarkus.test.enable-callbacks-for-integration-tests=true` when this extension is present, even it is not used for the `@QuarkusIntegrationTest` itself.

We like to use the callbacks in the integration tests for some other custom callbacks.

### Expected behavior

The extension should do nothing on methods not annotated with `@TestSecurity`

### Actual behavior

It calls CDI which leads to errors for integration tests.

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.4.0

**Comment by Ladicek** [comment]
The `beforeEach()` method already does that check, so this should be just a matter of factoring that code out and calling it from both `beforeEach()` and `afterEach()`.
