### ISSUE TITLE
Security mailing list is not working

### ISSUE THREAD

**Issue by ivangreene** [quarkusio/quarkus#36618]
### Description

Sending mail to `security at quarkus.io` as mentioned in the security policy is not posting to the security mailing list. This is what I received in response:

>
>Hello my@example.com,
>
>We're writing to let you know that the group you tried to contact (quarkus-security) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
>* You might have spelled or formatted the group name incorrectly.
>* The owner of the group may have removed this group.
>* You may need to join the group before receiving permission to post.
>* This group may not be open to posting.
>
>If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/redhat.com/bin/topic.py?topic=25838.
>
>Thanks,
>
>redhat.com admins

**Comment by gsmet** [comment]
It's weird, we had a few reports there lately, maybe this was broken recently. We will investigate.

In the meantime, if it's urgent, can you send the report to gsmet at redhat dot com, I will forward it to the list.

Thanks.

**Comment by maxandersen** [comment]
This is now back to working. 

There was a migration of the list that unfortunately missed enabling the list. 

Thanks for letting us know it was not working!

**Comment by ivangreene** [comment]
Thanks, I have just now resubmitted my report
