### ISSUE TITLE
Custom annotation+interceptor, invalid on method

### ISSUE THREAD

**Issue by 1774298958** [quarkusio/quarkus#36615]
### Describe the bug

Custom annotations are added to the class, and the interceptor takes effect. On the method side, the interceptor fails. The code is as follows

```java
@InterceptorBinding
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface EnableModifyLog {
    
}


@Slf4j
@Interceptor
@EnableModifyLog
public class ModifyAspect {
    private final static Logger logger = LoggerFactory.getLogger(ModifyAspect.class);


    @AroundInvoke
    public Object logOperation(InvocationContext context) throws Exception {

    }
}


@EnableModifyLog(modifyType = ModifyName.GET, handleName = "查询", needDefaultCompare=true, idType = Object.class)
@POST
@Path("/jsonDataMapList")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public ResultVo queryJsonDataMap(String keys) {

}
```

### Expected behavior

Customize annotations on methods, use interceptors to intercept and perform subsequent processing

**Comment by Ladicek** [comment]
I took the liberty to fix the code block in the description.

The code in the issue report doesn't show anything wrong, and there's little detail outside of the code. We'll need more information to be able to diagnose the problem.

**Comment by geoand** [comment]
Closing for lack of feedback
