### ISSUE TITLE
Docker native image doesn't run

### ISSUE THREAD

**Issue by mraible** [quarkusio/quarkus#36619]
### Describe the bug

I created a repo and build script with simple API examples for Micronaut, Quarkus, Spring Boot, and Helidon. I added a [GitHub Action](https://github.com/oktadev/auth0-java-rest-api-examples/blob/main/.github/workflows/docker.yml) to build and publish a Docker container with the native image in it. It works for all of the frameworks except for Quarkus. Here are the specific commands I'm using:

```
./gradlew build -Dquarkus.package.type=native
docker build -f src/main/docker/Dockerfile.native -t quarkus .
docker tag quarkus:latest mraible/quarkus:latest
docker push mraible/quarkus:latest
```

### Expected behavior

This repo has a `start-docker.sh` script that works with all the other containers. The following command should work:

```
./start-docker.sh mraible/quarkus
```

### Actual behavior

```
$ ./start-docker.sh mraible/quarkus
mraible/quarkus
No response from the app in 20 seconds
21.003
Error response from daemon: Cannot kill container: c560cbb8e4c3e51978046bb3816c15c7508115d6f742eab2a9ecbd527639de19: No such container: c560cbb8e4c3e51978046bb3816c15c7508115d6f742eab2a9ecbd527639de19
```

### How to Reproduce?

```
git clone https://github.com/oktadev/auth0-java-rest-api-examples.git
cd auth0-java-rest-api-examples
./start-docker.sh mraible/quarkus
```

Use one of the other frameworks to see it working:

```
./start-docker.sh mraible/spring-boot
```

### Output of `uname -a` or `ver`

Linux ip-172-31-43-91.us-east-2.compute.internal 6.1.55-75.123.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 26 20:06:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21 2023-09-19

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by zakkak** [comment]
Hi @mraible, I can't reproduce this.

What I did:

```
git clone https://github.com/oktadev/auth0-java-rest-api-examples.git
cd auth0-java-rest-api-examples
cd quarkus
./gradlew --debug build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
docker build -f src/main/docker/Dockerfile.native -t quarkus .
cd ..
./start-docker.sh quarkus:latest
```

What I got:

```
...
quarkus:latest
0.010 seconds
```

However, when using your image with:

```
./start-docker.sh mraible/quarkus
```

I indeed see it failing. 

When running the image directly (without the `start-docker` script) I am getting the following output:

```
./application: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./application)
./application: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./application)
```

which means that the native executable was compiled with a glibc version not available in `registry.access.redhat.com/ubi8/ubi-minimal:8.8`.

Please use `-Dquarkus.native.container-build=true` when building the native executable to resolve this.

**Comment by zakkak** [comment]
Hello @mraible , the image from https://hub.docker.com/u/mraible seems to work fine.

```
❯ podman pull mraible/quarkus      
✔ docker.io/mraible/quarkus:latest
Trying to pull docker.io/mraible/quarkus:latest...
Getting image source signatures
Copying blob 8295129c4db9 done   | 
Copying blob cafce474b90d done   | 
Copying blob 4c006e7aa3ac done   | 
Copying blob f82619d9412d done   | 
Copying config 6e77a86b70 done   | 
Writing manifest to image destination
6e77a86b70a6f05b425fd71c2538100605161dbc061f69cd2493a82d8e01c674
❯ podman run mraible/quarkus 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-01-10 10:35:23,946 INFO  [io.quarkus] (main) quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 3.6.4) started in 0.031s. Listening on: http://0.0.0.0:8080
2024-01-10 10:35:23,947 INFO  [io.quarkus] (main) Profile prod activated. 
2024-01-10 10:35:23,947 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, security, smallrye-context-propagation, smallrye-jwt, vertx]
```

> I removed all Docker images on my AWS EC2 t2.micro instance with docker images purge. When I try to run it, I get the same errors as above.

Did you check the `docker images` to see if the IMAGE ID is actually the latest? Could AWS be fetching some cached image?
