### ISSUE TITLE
JPA refresh with PESSIMISTIC_WRITE ignored for lazy loaded entity

### ISSUE THREAD

**Issue by mensinda** [quarkusio/quarkus#36633]
### Describe the bug

When trying to lock a lazy loaded entity with `em.refresh(e, LockModeType.PESSIMISTIC_WRITE);`, Quarkus / Hibernate seemingly does nothing (no SQL / `select for update` is executed). 

This only happens if the entity was not accessed prior to locking / refreshing the entity. As soon as an attribute is read, the `refresh` executes as expected. This behavior makes sense for a regular refresh (the entity wasn't yet loaded after all). However, this is not what I would expect if I specifically ask JPA to lock the entity with the refresh. Here, the `select for update` should be executed unconditionally.

---

Abbreviated example from https://github.com/mensinda/quarkus-stuff/tree/lockRefresh to illustrate:

```java
@Entity
public class MainEntity {
    @Id
    private long id;

    @OneToOne(targetEntity = ReferencedEntity.class, fetch = FetchType.LAZY)
    @JoinColumn(name = "LEHRL")
    private ReferencedEntity referenced;
}

@Entity
public class ReferencedEntity {

    @Id
    private long id;

    private String status;
}

@QuarkusTest
class DoTest {
    /**
     * Does <b>NOT</b> work as expected! No `select for update`!
     */
    @Test
    @Transactional
    void refresh() {
        MainEntity m = em.find(MainEntity.class, 0);
        ReferencedEntity e = m.referenced();
        assertNotNull(e);

        // First refresh, then access
        em.refresh(e, LockModeType.PESSIMISTIC_WRITE);
        assertEquals("ok", e.status());
    }
}
```

### Expected behavior

Quarkus / Hibernate executes a `select for update` for every `refresh` with a `PESSIMISTIC_WRITE` lock mode.

### Actual behavior

NO SQL is executed for the `refresh`  (compare with `refreshAfterRead` and `lock`)

### How to Reproduce?

I have created a minimal test case for this issue: https://github.com/mensinda/quarkus-stuff/tree/lockRefresh

Steps to reproduce:
1. clone / checkout the `lockRefresh` branch of https://github.com/mensinda/quarkus-stuff/tree/lockRefresh
2. run `mvn clean verify`
3. Observe that there is no `select for update` in the `NEW TEST: refresh` section

### Output of `uname -a` or `ver`

Linux XXXXXXX 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.8.1 2023-08-24

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)

**Comment by yrodiere** [comment]
Hi,

Thanks for reporting.

Do you have reasons to think this is specific to Quarkus, or does the same problem arise if you try the same thing in the [Hibernate ORM test case template](https://github.com/hibernate/hibernate-test-case-templates/tree/main/orm/hibernate-orm-6)? If the same happens without Quarkus, you might want to [report it directly to the Hibernate ORM project](https://hibernate.atlassian.net/browse/HHH) (or look for an existing bug report there).

**Comment by mensinda** [comment]
I managed to reproduce it with just hibernate: https://hibernate.atlassian.net/browse/HHH-17395

**Comment by yrodiere** [comment]
Thanks a lot for taking the time to report and provide a reproducer upstream, @mensinda!
