### ISSUE TITLE
ManagedBeanTypesTest#testGenericHierarchyBeanTypes not compatible with Java 21

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36632]
Making progress on Java 21 CI and stumbled upon this problem (see `SequencedCollection`):

> [ERROR]   ManagedBeanTypesTest>Arquillian.run:138->testGenericHierarchyBeanTypes:80 Set [class java.lang.Object, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.SequencedCollection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class org.jboss.cdi.tck.tests.definition.bean.types.Flock] (6) does not match array [class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (5)

We are using the latest version of the CDI TCK, 4.0.12. Is there any plan to make the TCK compatible with Java 21 or should we skip this test?

**Comment by gsmet** [comment]
I checked and we are using 4.0.12 so not sure what's going on.

**Comment by manovotn** [comment]
Right, here is the TCK challenge - https://github.com/jakartaee/cdi-tck/issues/485
And the test was then excluded for 4.0 version (and fixed for the upcoming 4.1), see https://github.com/jakartaee/cdi-tck/blob/4.0.12/impl/src/main/resources/tck-tests.xml#L53-L58

But we don't seem to be using same excusion list, instead we have https://github.com/quarkusio/quarkus/blob/main/tcks/jakarta-cdi/src/test/resources/testng.xml
So I guess we need to copy the exclusion into our our list.

**Comment by gsmet** [comment]
```
   mvn dependency:tree | grep tck
[INFO] -----------------< io.quarkus.arc:arc-cdi-tck-runner >------------------
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ arc-cdi-tck-runner ---
[INFO] io.quarkus.arc:arc-cdi-tck-runner:jar:999-SNAPSHOT
[INFO] +- io.quarkus.arc:arc-cdi-tck-porting-pkg:jar:999-SNAPSHOT:compile
[INFO] |  \- jakarta.enterprise:cdi-tck-api:jar:4.0.12:compile
[INFO] \- jakarta.enterprise:cdi-tck-core-impl:jar:4.0.12:compile
[INFO]    +- jakarta.enterprise:cdi-tck-ext-lib:jar:4.0.12:compile
```

Now, maybe the tests are coming from somewhere else?

**Comment by gsmet** [comment]
@manovotn thanks, will handle it in my branch then.

**Comment by manovotn** [comment]
> @manovotn thanks, will handle it in my branch then.

No problem. We might as well do it in the `main` branch to have the two lists synced.
Note however that the TCK list I linked includes CDI Full tests that we aren't running - which is probably a reason why we have our own.

**Comment by gsmet** [comment]
I added a commit there: https://github.com/quarkusio/quarkus/pull/36284 .

Thanks for the quick feedback.

**Comment by gsmet** [comment]
> No problem. We might as well do it in the main branch to have the two lists synced.

I confirm my PR targets the `main` branch.
