### ISSUE TITLE
RESTEasy Reactive does not call method ParamConverter#toString for collection elements

### ISSUE THREAD

**Issue by timonzi** [quarkusio/quarkus#36639]
### Describe the bug

The fix in #35774 allows the definition of REST resources with a collection of parameterized types as a query parameter.

Example (from #35774):

```
@GET
@Path("/wrapperList")
public String wrapperList(@QueryParam("wrapperList") final List<WrapperClass<StatusEnum>> wrapperList) {
    // ...
}
```

The problem what I found now is that `toString` method of my `ParamConverter` implementation is not called for the collection elements. Because of this the `fromString` method gets a class reference as String value (e.g. org.acme.WrapperClass@59e082f8) instead of the expected one.

```
public class WrapperClassParamConverter implements ParamConverter<WrapperClass<?>> {

  // [...]

    @Override
    public WrapperClass<?> fromString(String value) {
        return new WrapperClass<>(Enum.valueOf(StatusEnum.class, value));
    }

    @Override
    public String toString(WrapperClass<?> wrapperClass) {
        // RESTEasy Reactive: Not called for elements of a collection.
        // RESTEasy Classic: Calls the method for every element
        return wrapperClass != null ? wrapperClass.getValue().toString() : null;
    }

}
```

So the current implementation works fine when I simply provide a String value when calling the REST resource. This is what I did when testing the fix of #35774.

But when I now use the REST client to call a resource of another service, the `toString` method should be called to serialize the value and on the other side the `fromString` method should be called. For the `fromString` this works fine, but the `toString` method is never called.

### Expected behavior

The `toString` method from parameter converters should be used like in RESTEasy Classic - so also for collections.

### Actual behavior

The `toString` method is never called for collection elements. 

### How to Reproduce?

Reproducer: https://github.com/timonzi/resteasy-reactive-wrapper-collection-elements

1. Execute tests in `ParametersResourceTest` --> `testCollectionViaClient` will fail (because of the unexpected value in the `fromString` implementation)
2. Switch to RESTEasy Classic implementation (commented dependencies are already in the `pom.xml`) --> tests will work

### Output of `uname -a` or `ver`

Linux nb-timonz 6.2.0-31-generic #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

3.2.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

The fix of #35774 is also included in 3.2.7.Final. This version is used in the reproducer.

**Comment by geoand** [comment]
Thanks for reporting.

I'll try and have a look next week

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/36885 fixes the issue
