### ISSUE TITLE
info-url in smallrye-health

### ISSUE THREAD

**Issue by matheus-meneses** [quarkusio/quarkus#3667]
**Description**
As actuator does, would be really useful exposes an url that show the application build properties, such as, build version number from build.properties. Actuator does something like that exposing our info on (GET) /info.

**Comment by geoand** [comment]
When you say actuator, do you mean the Spring Boot actuator?
And when you say `build.properties` do you mean `build-info.properties` from Spring Boot?

**Comment by matheus-meneses** [comment]
yep

**Comment by ygyg70** [comment]
I am also interested in a standard way to integrate the build version/number/date

**Comment by geoand** [comment]
I am going to close this as we now have the info endpoint
