### ISSUE TITLE
Deployment tests interfere after upgrading from Quarkus 3.5.0.CR1 to 3.5.0

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#36676]
### Describe the bug

After upgrading from Quarkus 3.5.0.CR1 to 3.5.0, I can see some deployment tests failing in Quarkus CXF core deployment module, but they still pass when I run them in isolation.

Steps to reproduce:

```
git clone git@github.com:ppalaga/quarkus-cxf.git -o ppalaga
cd quarkus-cxf
git fetch ppalaga q36676
git checkout q36676
mvnd clean install -DskipTests -Dquarkus.build.skip
cd core/deployment
mvnd clean test
...
[ERROR] ServerDevModeTest
...
[ERROR]   IncludesConflictJava2WsTest
...
[ERROR]   IncludesExcludesJava2WsTest
...
[ERROR]   WsdlNameTemplateJava2WsTest
...
[ERROR] Tests run: 49, Failures: 1, Errors: 3, Skipped: 1
```

But when the failing tests are run individually, they pass. E.g.

```
mvnd clean test -Dtest=WsdlNameTemplateJava2WsTest
...
[INFO] BUILD SUCCESS
```

**Comment by ppalaga** [comment]
Were there any changes in deployment test class loading between 3.5.0.CR1 to 3.5.0?

**Comment by ppalaga** [comment]
I can see a similar issue in a `@QuarkusTest` using a `@TestProfile`:

```
cd integration-tests/server
mvnd clean test 
...
[ERROR]   XForwardedHeadersTest.testXForwardedHostHeader
...
```

But again, when I run the same test in isolation, it is passing:

```
mvnd clean test -Dtest=XForwardedHeadersTest
...
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] BUILD SUCCESS
...
```

I do not see any apparent suspect between [3.5.1.CR1 and 3.5.0](https://github.com/quarkusio/quarkus/compare/3.5.0.CR1...3.5.0)

May be this one? https://github.com/quarkusio/quarkus/commit/91cddc603fcee915d328f3b0c0460a1eb2e9c773 
@radcortez could the above change have the described impact?

**Comment by ppalaga** [comment]
> May be this one? [91cddc6](https://github.com/quarkusio/quarkus/commit/91cddc603fcee915d328f3b0c0460a1eb2e9c773)
> @radcortez could the above change have the described impact?

No, it is not the cause of this problem. I have built quarkus 3.5.0 without that change and I still see the same failures.

**Comment by ppalaga** [comment]
I have found what is causing this issue: In the branch, where I see the failures I had a change that workarounds wrong resource precedence in native mode through setting some runtime property via `SystemPropertyBuildItem`:

https://github.com/ppalaga/quarkus-cxf/commit/a5d70250b849c7c3619e8acedc7329a4dc91dda3#diff-75da9f7e1c3e1384976a49d0ad67baf36638a284b5c6d1beafa5846d6ff55fdfR184-R188

It looks like this change breaks the test isolation. 

@radcortez is it a known problem that `SystemPropertyBuildItem` can break the test isolation?

When I change it to `NativeImageSystemPropertyBuildItem` (which still works as a workaround for the other issue), the deployment and JVM tests work as expected.

**Comment by ppalaga** [comment]
I have found what is causing this issue: In the branch, where I see the failures I had a change that workarounds wrong resource precedence in native mode through setting some runtime property via `SystemPropertyBuildItem`:

https://github.com/ppalaga/quarkus-cxf/commit/a5d70250b849c7c3619e8acedc7329a4dc91dda3#diff-75da9f7e1c3e1384976a49d0ad67baf36638a284b5c6d1beafa5846d6ff55fdfR184-R188

It looks like this change breaks the test isolation. 

@radcortez is it a known problem that `SystemPropertyBuildItem` can break the test isolation?

When I change it to `NativeImageSystemPropertyBuildItem` (which still works as a workaround for the other issue), the deployment and JVM tests work as expected.

**Comment by radcortez** [comment]
> @radcortez is it a known problem that `SystemPropertyBuildItem` can break the test isolation?

I guess it will depend on what the configuration that you set is doing. This will set whatever config from the build step, directly into SystemProperties in Quarkus main.

**Comment by radcortez** [comment]
@ppalaga is this still an issue?

**Comment by ppalaga** [comment]
Yep, if I remove `` from 

https://github.com/quarkiverse/quarkus-cxf/blob/0eb4bae0cbf30883983b3b4f3df345338b0acf65/extensions/core/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L192

Then the same tests plus one new are failing

**Comment by radcortez** [comment]
@ppalaga did my last comment help?

**Comment by radcortez** [comment]
I am closing this one for now. Please reopen if we have more information.
