### ISSUE TITLE
Database credential values cannot be set by CredentialProvider for reactive-panache-kotlin 

### ISSUE THREAD

**Issue by Tincoquesse** [quarkusio/quarkus#36690]
### Describe the bug

I'm trying to use CredentialsProvider to set credential values for a database in a reactive panache with Kotlin.

![Screenshot 2023-10-25 at 14 59 50](https://github.com/quarkusio/quarkus/assets/28060759/4e41eda5-69fc-4c1f-99cc-69ce08e972a9)

Problems arise when I associate 'quarkus.datasource.reactive.url'  in the application properties. 

![Screenshot 2023-10-25 at 14 59 04](https://github.com/quarkusio/quarkus/assets/28060759/2d539ea0-9a18-46b1-9738-dc4021a3231b)

When I build the application, I get a message that there are no configuration values for the database :
![Screenshot 2023-10-25 at 14 47 59](https://github.com/quarkusio/quarkus/assets/28060759/ecbc0c77-daff-461f-9f2a-6e4213ec6d10)

that should be handled by the CredentialsProvider implementation.

This problem does not occur in the non-reactive version with the 'quarkus.datasource.jdbc.url' property. 

LINK working JDBC example
https://github.com/DawidStuzynski/hibernate-quarkus-batching-issue/tree/imperative-credentials-provider

LINK not working reactive example
https://github.com/DawidStuzynski/hibernate-quarkus-batching-issue/tree/reactive-credentials-provider

### Expected behavior

Correctly set credential values for the database

### Actual behavior

Failed to load config value of type class java.lang.String for: quarkus.datasource.password
Failed to load config value of type class java.lang.String for: quarkus.datasource.username

### How to Reproduce?

https://github.com/DawidStuzynski/hibernate-quarkus-batching-issue/tree/reactive-credentials-provider

### Output of `uname -a` or `ver`

21.6.0 Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by adampoplawski** [comment]
Please close the issue. We cannot reproduce on 3.5.0, we all good :)

**Comment by geoand** [comment]
👍
