### ISSUE TITLE
Lombok Debug Slf4j

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkus#3669]
**Describe the bug**
Hi, I'm using Lombok and I changed the application properties to have the min log level as debug, but when trying to log something as debug, the information is not displayed. 

application.properties
`
quarkus.log.min-level=DEBUG
`

Code
`
log.debug('Some {}', "thing")
`

If I use log.info('Some {}', "thing"), it works.

I'm running it in the dev mode.

**Expected behaviour**
When I have min log level as Debug and I use log.debug('Some {}', "thing"), the log should be displayed.

**Quarkus Version**
0.21.1

**Comment by Holi60k** [comment]
Where did you see the ```min-level``` attribute?
https://quarkus.io/guides/logging-guide
This page has no attribute like this.

**Comment by lbernardomaia** [comment]
Thanks, it works that way.

I generated the application.properties from `mvn quarkus:generate-config`

I'm going to close this ticket!
