### ISSUE TITLE
Project generator on quarkus.io does not generate correct Dockerfile.jvm

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#36707]
### Describe the bug

The[ project/application generator](https://code.quarkus.io/) on [quarkus.io](url) generates a `Dockerfile.jvm` based on `registry.access.redhat.com/ubi8/openjdk-{java.version}:1.16` (see [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/13173210/code-with-quarkus.zip)) but https://github.com/quarkusio/quarkus/blob/3.5.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute says it's `registry.access.redhat.com/ubi8/openjdk-{java.version}:1.17`. 

Which ist correct? 

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

Additional hint: https://github.com/quarkusio/quarkus/blob/3.5.0/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute contains a code change from `ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"` to `ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"`. This is possibly a breacking change that is not included in the migration guide.

**Comment by mschorsch** [comment]
cc @gsmet

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
Maybe the generator didn't get updated? @ia3andy ?

**Comment by ia3andy** [comment]
Yes I'll update it today!

**Comment by ia3andy** [comment]
Those are base codestarts part of the generator as you said @cescoffier, I need to publish code.quarkus.io to update them:
https://github.com/quarkusio/code.quarkus.io/blob/main/api/pom.xml#L34

**Comment by ia3andy** [comment]
code.quarkus.io is live with the fix
