### ISSUE TITLE
code.quarkus.io Support Java 21

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#36709]
### Description
Can not select Java 21.
<img width="1344" alt="image" src="https://github.com/quarkusio/quarkus/assets/6096680/2cb44212-da62-4b2a-ad45-6c2f8f08784d">

_No response_

**Comment by gsmet** [comment]
cc @ia3andy

**Comment by ia3andy** [comment]
https://github.com/quarkusio/code.quarkus.io/issues/1245

**Comment by adampoplawski** [comment]
Also Gradle is supporting Java 21 since version 8.5 (not even released yet), and in generated projects, we have 8.1.1. Probably would be good to hide 21 if you pick Gradle until Quarkus/Gradle is not ready for Gradle 8.5

**Comment by ia3andy** [comment]
https://github.com/quarkusio/code.quarkus.io/issues/1251

**Comment by gsmet** [comment]
@adampoplawski you have Gradle 8.1.1 in projects generated with Quarkus 3.5? That looks odd.

**Comment by adampoplawski** [comment]
@gsmet now I see 8.3+3.5.0. Not sure if 2 weeks ago it was different or I had leftovers from 3.4.3

**Comment by gsmet** [comment]
Yeah, that's expected then, thanks. I'll have a look if we upgraded already to 8.4 in main and backport it in 3.5.1 if so.

**Comment by ia3andy** [comment]
This is now in production :)
