### ISSUE TITLE
Updating version of testcontainter/localstack for dev services

### ISSUE THREAD

**Issue by adampoplawski** [quarkusio/quarkus#36715]
### Description

Hello
Dev services by default are using localstack 1.4.0 (currently 2.3.2), and testcontainer 0.5.1 (currently 1.19.1). Is it intentional to keep those particular (a bit old) versions as default?

**Comment by adampoplawski** [comment]
@melloware my bad.
<img width="878" alt="image" src="https://github.com/quarkusio/quarkus/assets/24206314/8a3ca670-3a82-4e5a-a52e-33b8bbd320b3">
I have seen versions in logs and I see this is testcontainers/ryuk not testcontainers. 
Is there a reason localstack:1.4.0 is a default?
Thx for help

**Comment by melloware** [comment]
I will have to dig deeper and figure out where that is coming from. Let me look

**Comment by melloware** [comment]
@adampoplawski looks like you might have to ask the TestContainers project as LocalStack is coming from them here: https://github.com/testcontainers/testcontainers-java/blob/main/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java

It looks like Quarkus just uses TestContainers and that is one of their built in containers.

**Comment by adampoplawski** [comment]
@melloware https://docs.quarkiverse.io/quarkus-amazon-services/dev/dev-services.html according to this
<img width="1343" alt="image" src="https://github.com/quarkusio/quarkus/assets/24206314/abc90e4e-7b52-46bb-aaa0-1b4933c25f56">
It is set by Dev services for Amazon Services

**Comment by melloware** [comment]
AHHHH nice so its a Quarkiverse thing. You should report it here https://github.com/quarkiverse/quarkus-amazon-services and close this ticket.

**Comment by gsmet** [comment]
Yes, please report to https://github.com/quarkiverse/quarkus-amazon-services but IIRC there was a good reason for them to keep the old version (problems with the new one).
