### ISSUE TITLE
Persisting to Postgres jsonb column broken

### ISSUE THREAD

**Issue by vanuatoo** [quarkusio/quarkus#36730]
### Describe the bug

In order to persist to Postgresql table with the column type of jsonb, I have an JPA Entity defined as
....
@Column(name = "payload")
    @JdbcTypeCode(SqlTypes.JSON)
    public JsonObject eventPayload;
......

I use jakarta.json.JsonObject here.

### Expected behavior

When I save the arbitrary payload constructed from the code
Json.createObjectBuilder()
                .add("id", 1)
                .add("name", "Quarkus")
                .build();

I expect that it is stored properly in the database, like
{"id": 1, "name": "Quarkus"}

### Actual behavior

The payload is stored like
{"id": {"valueType": "NUMBER"}, "name": {"valueType": "STRING"}}

### How to Reproduce?

1. Create a Quarkus project
2. Create JPA Entity with the field to hold JsonObject
3. Create Panache Repo and store the JPA Entity in Postgresql database

### Output of `uname -a` or `ver`

Darwin EPGETBIW0449 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### Quarkus version or git rev

3.5.0

**Comment by vanuatoo** [comment]
The code has been working with 3.2 version of the Quarkus

**Comment by sfali16** [comment]
Hi @vanuatoo, 
I'm new to quarkus and trying to reproduce this bug to fix it - Can you point me to a standalone (full) example of code that you expect to work here ? 

I started off with a quarkus quickstart for Hibernate ORM with Panache and Rest - https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-rest-data-panache-quickstart - and have it creating a postgres database with entity, but I'm unable to get a working example of adding a jsonb column type (unsure if it's due to Hibernate or due to this bug)

Thanks !

**Comment by sfali16** [comment]
Here's a draft PR for the quarkus quickstarts showing the commits I made with an example of how to use a JsonB - this works fine on postgres:
https://github.com/quarkusio/quarkus-quickstarts/pull/1346

**Comment by sfali16** [comment]
I used a Map<String, Object> and quarkus figured out how to persist that correctly. 


    @JdbcTypeCode(SqlTypes.JSON)
    public Map<String, Object> jsonAddress;

When I tried to JsonObject it failed to find a serializer / deserializer for the class, so i would have had to provide a converter as in [link](https://www.baeldung.com/hibernate-persist-json-object), which didn't seem worth the effort when the Map works. 
See https://thorben-janssen.com/persist-postgresqls-jsonb-data-type-hibernate/ for Hibernate 6 and Hibernate 5 mechanisms to use json column.

@vanuatoo  Can you use the Map solution or provide a standalone example that reproduces the problem?

**Comment by vanuatoo** [comment]
I used Map and it works fine.

**Comment by Ordiel** [comment]
I would expect this to work with JsonObject itself
