### ISSUE TITLE
Feeding long non-ascii string into a servlet response trims it

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#3673]
When I feed a non-ascii string longer than 8192 characters into a servlet response writer, only the first 8192 characters appear in the output, no matter if I set UTF-8 encoding or don't set it at all (in which case it somehow defaults to ISO-8859-1). The workaround is splitting the large string into smaller chunks and calling `flush()` in between feeding them one by one to the writer. See https://github.com/jmartisk/quarkus/commit/2fdb1c046397119e805fcce27285d9bedae71858

@stuartwdouglas could you please have a look into this? I suppose this is something with the logic in https://github.com/quarkusio/quarkus-http/blob/3.0.0.Alpha2/servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java

**Comment by gsmet** [comment]
@jmartisk is it still an issue?

**Comment by stuartwdouglas** [comment]
It was fixed by https://github.com/quarkusio/quarkus-http/commit/d1025c5368125f294ef03330d4ca25df36978bd0
