### ISSUE TITLE
Resolve the extensions before creating the project

### ISSUE THREAD

**Issue by aureamunoz** [quarkusio/quarkus#3674]
**Description**
As mentioned [here](https://github.com/quarkusio/quarkus/pull/3492#discussion_r313299096), it would be good to resolve the extensions before creating the project so that we can have a list of the extensions that will be added.

**Implementation ideas**
The idea would be to pass a list of the active extensions to CreateProject so it can then decide what needs to be done without having to do a check (which would be pretty much the same for each new extension that needs some custom functionality) to know if a concrete extension has been added to the input.

Optionally you could complete this description, @geoand, @gsmet, @ia3andy?

**Comment by gastaldi** [comment]
@aloubyansky I think this is already provided by the Extension Registry Client API? I wonder if we can close this one

**Comment by ia3andy** [comment]
Yes we can close this.
