### ISSUE TITLE
Support Java Record for MongoDB Panache projection queries

### ISSUE THREAD

**Issue by anamak9** [quarkusio/quarkus#36756]
### Description

**New enhancement request:**
myCollection.find(query, sort, params) .range(start, end)
           **.project**(MyDTO.class) //  **Here MyDTO class can be a Java 'record' instead of a regular 'class', but it's not supported yet.**  
           .stream().toList();

**Dependencies:** 
mongdb-client:3.4.1
mongdb-panache:3.4.1
mongdb-panache-common:3.4.1

**Comment by evanchooly** [comment]
`mongodb-panache` relies on the driver for codecs so until the driver supports them, panache can't either.

**Comment by anamak9** [comment]
As per the document, such codecs driver do exist,

https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/data-formats/document-data-format-record/

I will explicitly add that driver and see if that works.

**Comment by anamak9** [comment]
Added the following dependency and tried,

<dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>bson-record-codec</artifactId>
      <version>4.11.0</version>
      <scope>runtime</scope>
    </dependency>

but it didn't work

**Comment by loicmathieu** [comment]
@anamak9 the codec will not be automatically detected as the class is not part of your application but on an external dependency.

Can you try to index the dependency so it is known to the Quarkus extension by adding these lines in your application.properties:

```
quarkus.index-dependency.bson-record-codec.group-id=org.mongodb
quarkus.index-dependency.bson-record-codec.artifact-id=bson-record-codec
```

**Comment by anamak9** [comment]
@loicmathieu 
I tried your approach but it didn't work (I'm still getting ObjectId field as 'null') . Anyway its not a blocker for me, I can live with regular POJO class approach. You may want to consider this task for any future release or else close it. 

Thanks

**Comment by loicmathieu** [comment]
Hi,
I just tested, and we can use records for both a projection and a document when using the repository pattern.
The codec is integrated by default inside the bson library so no need to add it manually.
See the following tests inside Quarkus that uses records: https://github.com/quarkusio/quarkus/pull/37624/files
