### ISSUE TITLE
MockMailbox does not work

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#36762]
### Describe the bug

The following code works fine in dev but not in testing.
I have the following class which sends type safe qute emails (`MailTemplateInstance`):

```java
class AuthService {
 public void sendVerificationEmail(String email, String token) {
          AdminEmailTemplates
                .invite(token)
                .to(email)
                .send();
 }
}
```

```java
@CheckedTemplate(basePath = "emails", defaultName = CheckedTemplate.HYPHENATED_ELEMENT_NAME)
public class AdminEmailTemplates {
    public static native MailTemplate.MailTemplateInstance invite(String token);
}
```

When i run the following test it fails with `Expected size: 1 but was: 0 in: []`
If i do not use the `AdminEmailTemplates` but use the `Mailer` or the `ReactiveMailer` it works fine.

```java
class Test {

    @Inject
    AuthService authService;


    @Test
    public void testEmail() throws Exception {
        var email = "info@iana.org";

        authService.sendVerificationEmail(email);

        List<Mail> sent = mockMailbox.getMailsSentTo(email);
        assertThat(sent).hasSize(1);
        
   }
}
```

Also if i change
```java
          AdminEmailTemplates
                .invite(token)
                .to(email)
                .send();
```

with 

```java
AdminEmailTemplates
                .invite(token)
                .to(email)
                .send()
                .await()
                .atMost(Duration.ofSeconds(10))
```
i get the following error `java.lang.IllegalStateException: No RESTEasy Reactive request in progress` (only in testing, in dev works fine)

**Comment by melloware** [comment]
@gbourant not related to this ticket but I have an extension that lets you get rid of Mock mailing altogether and use real SMTP in your Development and Unit Testing: https://github.com/quarkiverse/quarkus-mailpit

**Comment by geoand** [comment]
Can you please attach a sample application that behaves in the way this issue described?

Thanks

**Comment by gbourant** [comment]
A reproducer can be found [here](https://github.com/gbourant/email-test). 

I also reported that i get `No RESTEasy Reactive request in progress` error but this is caused by Renarde (uriabs/Router.getUriBuilder) method which it used in email templates.

**Comment by gbourant** [comment]
After further investigation, it seems that the type safe email templates use the `ReactiveMailer` under the hood so i have to use the .await(). If so we can close this one.

```java
        AdminEmailTemplates
                .invite(token)
                .to(email)
                .send().await().atMost(Duration.ofSeconds(10));
```
