### ISSUE TITLE
resteasy reactive jackson - JSON parse issue

### ISSUE THREAD

**Issue by anamak9** [quarkusio/quarkus#36765]
### Describe the bug

The module 'quarkus-resteasy-reactive-jackson' cannot parse a JSON key value pairs and covert into a java Map

### Expected behavior

The object 'Map<String, Integer> mapping' should be non null and should contains all 3 entries.

### Actual behavior

I get a HTTP 400 with an error like this,

{
    "objectName": "LinkedHashMap",
    "attributeName": "mapping",
    "line": 2,
    "column": 15,
    "value": null
}

### How to Reproduce?

Pass in a JSON like below from any HTTP REST client,

{
   "**mapping**": {
    "1": 2,
    "2": 4,
    "3": 5
 }
}
and have the API defined as, 

 @PUT
 @Path("/items")
 public Response orderItems(**Map<String, Integer> mapping**) {
}

**Comment by rysurd** [comment]
Hello ! I'll have a look.

**Comment by geoand** [comment]
To be honest, I am almost certain this is not a bug, but instead a mismatch between the provided and data and the expected model

**Comment by rysurd** [comment]
Hello again,

I reproduced your issue and just like @geoand said it's a mismatch issue. If you want to parse this specific JSON :
```
{
    "mapping": {
        "1": 2,
        "2": 4,
        "3": 5
    }
}
```

Then you need to change Map<String, Integer> to Map<String, Map<String, Integer>>. Not a bug ...

**Comment by anamak9** [comment]
You are correct, its not a bug, thanks
