### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by Gunnar-Brading** [quarkusio/quarkus#36768]
### Describe the bug

I am unable to find any docker images to use as a base for my projects, using JDK 21.
This for non-native builds. The default seems to be an image for JDK 17, and I cannot find anything else at the moment,
but I might just be searching in the wrong place?

**Comment by cescoffier** [comment]
This is because they are still not available. 
You can use https://hub.docker.com/_/eclipse-temurin for the time being.
