### ISSUE TITLE
Reactive - Different behaviour between Prod and Dev

### ISSUE THREAD

**Issue by fp-smartlogic** [quarkusio/quarkus#36779]
I've noticed that the application behaves differently for prod and dev mode. 
I am using the most recent version of Quarkus (3.5.0) and I built the application as an uber-jar.
In production, the response is flushed just after all the content is collected.
However, when I run the application in development mode, the response body is being sent every 1 second. 

I prepared a simple example:

```java
@Path("/test")
@RequestScoped
public class TestLevel {

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  public Multi<Integer> getInts() {
    return Multi.createFrom().emitter(this::emitNumbers);
  }

  private void emitNumbers(MultiEmitter emitter) {
    for (int i = 0; i < 10; i++) {
      emitter.emit(i);
      try {
        Thread.sleep(1000);
      } catch (InterruptedException e) {
        emitter.fail(e);
        throw new RuntimeException(e);
      }
    }
    emitter.complete();
  }
}
```

Illustration of the issue:
![image](https://github.com/quarkusio/quarkus/assets/42775212/585a8070-0ad5-4939-98ae-3ae9172d7dc3)

### Output of `java -version`

java 17.0.7 2023-04-18 LTS

### Quarkus version or git rev

3.5.0

**Comment by geoand** [comment]
I have never seen this happen. Is this still happening with Quarkus 3.6?

**Comment by fp-smartlogic** [comment]
@geoand, yes, it is still happening in 3.6

**Comment by geoand** [comment]
Thanks for checking

**Comment by geoand** [comment]
This has to do with blocking the event loop. If you instead produce the items in a non blocking way, everything works the same in dev and prod. 

The code would look something like:

```java
@Path("/test")
@RequestScoped
public class TestLevel {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Multi<Long> getInts() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(1)).select().first(10);
    }

}
```
