### ISSUE TITLE
Jandex re-indexing warning for narayana-jta-5.9.6.Final.jar when Quarkus starts

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#3678]
**Describe the bug**
The following warning is being displayed each time I start Quarkus in dev mode with the `narayana-jta` extension from the `master` version:
```
2019-08-23 22:54:59,516 WARN  [io.qua.dep.ind.ApplicationArchiveBuildStep] (build-13) Re-indexing /Users/Gwenneg/.m2/repository/org/jboss/narayana/jta/narayana-jta/5.9.6.Final/narayana-jta-5.9.6.Final.jar - at least Jandex 2.1 must be used to index an application dependency
```

I'm in the middle of a bug fix, I'll come back later to this ticket to add missing information.

**Comment by gsmet** [comment]
@gwenneg is this really a bug or is narayana providing an index generated with an outdated version?

**Comment by gwenneg** [comment]
@gsmet: You're right, the warning is caused by an outdated index version in `narayana-jta` and @rsvoboda asked for an update in #3705.

**Comment by ochaloup** [comment]
@rsvoboda @gsmet we are able to make the update of the jandex version for the next release of Narayana (5.9.8.Final). Would that be fine from perspective of this issue to upgrade to the latest Narayana when released?

**Comment by gsmet** [comment]
@ochaloup yes, sure, thanks for that!
