### ISSUE TITLE
Maven Tests on JDK 11 Windows get stuck for 3.2 branch

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#36797]
### Describe the bug

`Maven Tests on JDK 11 Windows` gets stuck with `Results:Terminate batch job (Y/N)? ` for 3.2 branch

See the timestamps on last two lines, there is 8 minutes nothing before termination:
<img width="1236" alt="Screenshot 2023-10-31 at 9 28 47" src="https://github.com/quarkusio/quarkus/assets/925259/c44e86da-21e6-4651-b0c7-608106dec801">

Noticed in https://github.com/quarkusio/quarkus/pull/36697 execution

Windows are the most used OS by users with enabled build time metrics.
This makes backports and CI failures investigation more painful and can hide other issues.
This needs to be investigated and fixed.

CI on main seems to pass, I have seen green light on https://github.com/quarkusio/quarkus/pull/36752
Quarkus CI / Maven Tests - JDK 11 Windows (pull_request) Successful in 16m [Details](https://github.com/quarkusio/quarkus/actions/runs/6668725595/job/18125619935?pr=36752)

### Expected behavior

`Maven Tests on JDK 11 Windows` pass

### Actual behavior

`Maven Tests on JDK 11 Windows` gets stuck 

### How to Reproduce?

Do something similar to https://github.com/quarkusio/quarkus/pull/36697

**Comment by rsvoboda** [comment]
Looking again into the log and I think the job hit `timeout-minutes: 80` as defined in https://github.com/quarkusio/quarkus/blob/3.2/.github/workflows/ci-actions-incremental.yml#L352

Upstream is using 130 minutes timeout introduced in https://github.com/quarkusio/quarkus/blob/main/.github/workflows/ci-actions-incremental.yml#L400 together with dev mode inclusion
ut even before that change, timeout was set to 100 minutes.

CC @aloubyansky

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus/pull/35132 increased the timeouts including windows tests, I think we should backport that one, added backport label to it.

**Comment by geoand** [comment]
I assume we can close this since we no longer support JDK 11

**Comment by rsvoboda** [comment]
JDK 11 is supported on 3.2 branch, but this can be closed because:

* https://github.com/quarkusio/quarkus/pull/35132 was backported to 3.2 branch so 
* Last PR in 3.2 branch (https://github.com/quarkusio/quarkus/pull/40077) was fully green

**Comment by geoand** [comment]
👌
