### ISSUE TITLE
@SecureField add expression support 

### ISSUE THREAD

**Issue by Serkan80** [quarkusio/quarkus#36804]
### Description

Currenty `@SecureField` only supports hardcoded roles and it would be nice if this could be aligned with how `@RolesAllowed` works, namely with expressions support. 

This also causes problems in combination with @RolesAllowed when the latter uses expressions and when the app is deployed on certain environments then the dynamic role is not available in SecureField. 

If implemented, then please make this also available on the LTS version. 

### Implementation ideas

This should be possible:

`@SecureField(roles=‘${maintainer.role}’, ‘roleA’)`

**Comment by michalvavrik** [comment]
> If implemented, then please make this also available on the LTS version.

Sorry, probably not possible. I think new feature like this does not qualify for backports.

**Comment by geoand** [comment]
> I think new feature like this does not qualify for backports.

I definitely agree

**Comment by Serkan80** [comment]
> > If implemented, then please make this also available on the LTS version.
> 
> Sorry, probably not possible. I think new feature like this does not qualify for backports.

I thought that security fixes & enhancements would also be backported to the LTS version ? 

Anyways, thx for the effort for implementing this feature! Very appreciated !

**Comment by geoand** [comment]
This is a new feature, not a fix for a security issue
