### ISSUE TITLE
Documentation not correct : https://quarkus.io/guides/datasource#configure-a-jdbc-datasource (DB2 driver)

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#36814]
### Describe the bug

It states that the DB2 driver is JDBC: com.ibm.db2.jcc.DBDriver

### Expected behavior

com.ibm.db2.jcc.DB2Driver

**Comment by mswatosh** [comment]
Took me reading it a few times to notice the mistake 😄 Good catch @argenstijn, I'll open a PR to correct it.
