### ISSUE TITLE
CORS Allowed-Headers shouldn't be case sensitive

### ISSUE THREAD

**Issue by brunoabdon** [quarkusio/quarkus#3681]
**Describe the bug**
CORS config `quarkus.http.cors.headers` shouldn't be case sensitive, since [HTTP headers are case-insensitive](https://tools.ietf.org/html/rfc2616#section-4.2).

**Expected behavior**
Setting  `quarkus.http.cors.headers=Content-Type` on `application.properties` should cause [pre-flight `OPTIONS` http requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) with `Access-Control-Request-Headers: content-type` to return a response with header `Access-Control-Allow-Headers: content-type`.

**Actual behavior**
Lower case allow-headers `content-type` is not returned when client asks for camel-case `Content-Type`.

**To Reproduce**
1. [Configure the Quarkus CORS filter](https://quarkus.io/guides/undertow-reference#cors-filter) with `quarkus.http.cors.headers=Content-Typet`
2. Make a pre-flight `OPTIONS` request with the header `Access-Control-Request-Headers: content-type`
3. Notice the missing `Access-Control-Allow-Headers: content-type` in the response headers.

**Configuration**
```properties
#CORS
quarkus.http.cors=true
quarkus.http.cors.headers=Content-Type
```
**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.21.1

**Additional context**
HTTP headers are case-insensitive, from [RFC 2616 -   Hypertext Transfer Protocol -- HTTP/1.1, section 4.2 - Message Headers](https://tools.ietf.org/html/rfc2616#section-4.2),.

**Comment by gwenneg** [comment]
Thanks for reporting this @brunoabdon!
