### ISSUE TITLE
config-yaml warning - unrecognized configuration file on Windows

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#36813]
### Describe the bug

An application with the `config-yaml` extension prints a warning about `Unrecognized configuration file...` on Windows, even though the YAML config `application.yml` is present, recognized and used by the application.

This happens in Quarkus 3.5.0.
Quarkus 3.4.3 is unaffected.

### Expected behavior

No `[WARNING] [io.quarkus.config] Unrecognized configuration file...` in the log.

### Actual behavior

```
...
[INFO] --- quarkus-maven-plugin:3.5.0:build (default) @ config-yaml-windows ---
[WARNING] [io.quarkus.config] Unrecognized configuration file C:\cygwin\home\hudson\reproducers\target\classes\application.yml found; Please, check if your are providing the proper extension to load the file
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 3055ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.469 s
[INFO] Finished at: 2023-11-01T13:55:52+01:00
[INFO] ------------------------------------------------------------------------
```

### How to Reproduce?

```
git clone -b config-yaml-windows git@github.com:jsmrcka/reproducers.git
mvn -f ./reproducers clean package
```

### Output of `uname -a` or `ver`

windows server 2019, windows server 2022

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18  OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)  OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by jsmrcka** [comment]
@radcortez Bringing this to your attention based on previous activity around `area/config` and `env/windows`.

cc @gsmet FYI.

cc2 @rsvoboda FYI - there is an allow-list item related to this (https://github.com/quarkus-qe/quarkus-startstop/pull/321).

**Comment by radcortez** [comment]
I'll have a look.
