### ISSUE TITLE
Nested transactions do not affect the entity cache

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#36825]
### Describe the bug

I have found following strange situation.
My app uses postgres as database, which has the read commited isolation level (default)
https://www.postgresql.org/docs/current/transaction-iso.html#XACT-READ-COMMITTED
```When a transaction uses this isolation level, a SELECT query (without a FOR UPDATE/SHARE clause) sees only data committed before the query began; it never sees either uncommitted data or changes committed by concurrent transactions during the query's execution.```

So far so good.
Not to my situation.

Service a with Transactional(Requires_new)
- calls Service b which again has a Transactional(Requires_new)
-- service b now loads an entity by id
-- service b does some funky stuff with the entity (does not matter for us).
-- In the meantime, another process deletes the entity. Thanks to read commited isolation level though, we can still fully read every part of the entity and childs
- back to service a
- service a now also load the entity by id. It can still find it
- why?

The last question, the why the entity could still be found is my main problem.

So far 2 parts out:
1) The databse transaction does not start at the point where the method of service a gets called. The DB TX only starts on the first query. Okay, I can live with that. Not surer if everyone expects this behaviour though, is this documented somewhere?

2) ORM holds the entity in some kind of cache I believe. At least the em.find in Service b and Service a both return objects with the entities identity.

### Expected behavior

I would expect that the entity cache of em is clear on a transaction boundary.

### Actual behavior

I get a half loaded entity from the cache, which fails to load its childs because they are deleted in db.

### How to Reproduce?

Reproducer: 
[pc-cache.zip](https://github.com/quarkusio/quarkus/files/13236177/pc-cache.zip)

1) mvn clean compile quarkus:dev
2) Set breakpoints in GrettingResource#hello and SomeService#doSth.
3) Open http://localhost:8080/hello
4) Notice that the MyEntity instances both have the same identity.
5) Also notice, that the entity was loaded at all, even though it gets deleted

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045

### Output of `java -version`

openjdk 17.0.4 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: C:\eclipse\tools\java\maven
Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment]
@Postremus Hm, but in the reproducer the `SomeService#doSth()` method is executed within the transaction created for `GreetingResource#hello()` because `SomeService` is annotated with `@Transactional` which implies `TxType.REQUIRED` and `GreetingResource` is annoated with `@Transactional(Transactional.TxType.REQUIRES_NEW)` which means always create a new transaction for `hello()`. Am I missing something?

**Comment by Postremus** [comment]
Interesting, I will retest this . Tanks

Martin Kouba ***@***.***> schrieb am Do., 2. Nov. 2023, 12:03:

**Comment by Postremus** [comment]
closing this, can not reproduce even in my real world app.. thanks
