### ISSUE TITLE
[Extension Proposal] OpenAI client extension

### ISSUE THREAD

**Issue by morphy76** [quarkusio/quarkus#36827]
### Description

Due to the high adoption of generative models, an higher level API could be very useful to integrate Quarkus applications to OpenAI services.

The idea is to configure, at least, few parameters, like the model to use, and inject a ready to use provider bean, something like:

```
quarkus.openai.api-key=sk-vB...4uWF
quarkus.openai.gpt.stream=true
quarkus.openai.gpt.chat.model=gpt-3.5-turbo
```

Additional configuration entries can be added furthermore from a detailed tuning of the request, like the maximum number of tokens to generate, to technical aspects, like the HTTP client pool. 

E.g. the streaming configuration of the example is optional with a valuable default to false.

```java
//...
    @Inject
    OpenAIClient aiClient;

    @GET
    @Path("/chat")
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    public Multi<? extends AbstractOpenAIResponse> chat() {
        var builderTemplate = Message.Builder.of();
        return aiClient.chat().create(List.of(
                builderTemplate
                        .withContent("As a test execution to understand if the java client API is properly working")
                        .withRole(Role.system)
                        .build(),
                builderTemplate
                        .withContent("Use very few words to limit the token consumption of OpenAI APIs.")
                        .withRole(Role.system)
                        .build(),
                builderTemplate
                        .withContent(
                                "Hello, my name is Test, tell me, in few words, a very short story with at least 2 paragraphs")
                        .withRole(Role.user)
                        .build()));
    }
//...
```

The OpenAIClient acts as a provider for each OpenAI service:

- to create chat through the chat endpoint
- moderations
- embeddings
- ...
and so on as listed by https://platform.openai.com/docs/api-reference/chat

Each service is a façade to the actual/available operations/endpoints of OpenAI services

The reactive implementation is the choice because of the current widespread programming model in quarkus, a non-reactive version could be proposed in future if the need emerges.

### Repository name

quarkus-openai-client-reactive

### Short description

Easily integrate to OpenAI services

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-openai-client-reactive/dev/

### Repository Topics

- quarkus-extension
- openai
- chatgpt
- llm

### Team Members

- I'm available to maintain this extension

**Comment by melloware** [comment]
@morphy76 maybe you can collaborate with this extension: https://github.com/quarkusio/quarkus/issues/36659

**Comment by morphy76** [comment]
My idea was to stay humble and simple :) but...
Checking out, thnx :)

**Comment by melloware** [comment]
Here is the extension: https://github.com/quarkiverse/quarkus-semantic-kernel

**Comment by maxandersen** [comment]
definitely interested in openai client - quarkus-semantic-kernel requires more than "core" Quarkus thus could be interesting with a "lighter" version. I'll check around for options.

**Comment by gastaldi** [comment]
I wonder if a reactive client is something that can be (or is already) provided in https://github.com/quarkiverse/quarkus-langchain4j. Hoping @geoand can answer that 😀

**Comment by geoand** [comment]
That extension already provides a REST Client for OpenAI that people can use.
