### ISSUE TITLE
SmallRye Config error message suggests strange enum values when a bad value is passed

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#36847]
### Describe the bug

Originally reported as https://github.com/quarkiverse/quarkus-cxf/issues/1048 by @famod:

> I'm getting the following config error when setting a nonexistent factory (by mistake), e.g. `-Dquarkus.cxf.http-conduit-factory=foo`:
>
> ```
> java.lang.RuntimeException: io.smallrye.config.ConfigValidationException: Configuration validation failed:
>	java.lang.IllegalArgumentException: SRCFG00039: The config property quarkus.cxf.http-conduit-factory with the config value "foo" threw an Exception whilst being converted SRCFG00049: Cannot convert foo > to enum class io.quarkiverse.cxf.CxfClientConfig$HTTPConduitImpl, allowed values: cxfd-efault,http-client-httpc-onduit-factory,urlc-onnection-httpc-onduit-factory,quarkus-cxfd-efault
> ...
> ```
> The "allowed values" look very odd:
>> cxfd-efault,http-client-httpc-onduit-factory,urlc-onnection-httpc-onduit-factory,quarkus-cxfd-efault

### Expected behavior

The expected values are the real values of the enum: `QuarkusCXFDefault, CXFDefault, HttpClientHTTPConduitFactory, URLConnectionHTTPConduitFactory`

We even set `@ConfigDocEnumValue("QuarkusCXFDefault")` etc. on the enum: 

https://github.com/quarkiverse/quarkus-cxf/blob/16f20f492ee68b6710c170b8b83df492fcc5c3b2/extensions/core/runtime/src/main/java/io/quarkiverse/cxf/CxfClientConfig.java#L327-L335
 
This names should be honored also in the error message.

**Comment by ppalaga** [comment]
@radcortez is there any MP Config annotation we could use to fix the strange values in the error message?

**Comment by radcortez** [comment]
> @radcortez is there any MP Config annotation we could use to fix the strange values in the error message?

No, but I'll see if I can improve the matching. `@ConfigDoc*` annotations are only used for documentation generation and don't impact the configuration at all.

**Comment by ppalaga** [comment]
> No, but I'll see if I can improve the matching. `@ConfigDoc*` annotations are only used for documentation generation and don't impact the configuration at all.

@radcortez not sure what was your plan here, the error message now renders the hyphens on more intuitive places

```
The config property quarkus.cxf.http-conduit-factory with the config value "foo" threw an Exception whilst being converted SRCFG00049: Cannot convert foo to enum class io.quarkiverse.cxf.CxfClientConfig$HTTPConduitImpl, allowed values: url-connection-http-conduit-factory,http-client-http-conduit-factory,quarkus-cxf-default,cxf-default
```

but it is still wrong: none the hyphenated values will work because the option accepts only the verbatim enum values. Could you please sketch what needs to be done so that both docs and these error messages match the reality?

**Comment by radcortez** [comment]
Hum. I've added a test in Quarkus and SR Config, which seems to work with verbatim and dashed names:

https://github.com/quarkusio/quarkus/pull/37974
https://github.com/smallrye/smallrye-config/pull/1075

Which names are not working?
