### ISSUE TITLE
ObjectMapper configuration is discarded in resteasy-reactive-jackson's JsonFactory

### ISSUE THREAD

**Issue by torbsto** [quarkusio/quarkus#36850]
### Describe the bug

When using custom (de)serializers and modules, resteasy-reactive-jackson doesn't work as expected.

Given the following classes:
```java
public record CustomSerializerDto(String title, OffsetDateTime dateTime) {
}
```
```java
public class CustomSerializerDtoSerializer extends StdSerializer<CustomSerializerDto> {

    protected CustomSerializerDtoSerializer() {
        super(CustomSerializerDto.class);
    }

    @Override
    public void serialize(final CustomSerializerDto value, final JsonGenerator gen, final SerializerProvider provider)
            throws IOException {
        gen.writeStartObject();
        gen.writeStringField("title", value.title());
        gen.writeObjectField("datetime", value.dateTime());
        gen.writeEndObject();
    }
}
```
```java
@Singleton
public class Customizer implements ObjectMapperCustomizer {
    @Override
    public void customize(final ObjectMapper objectMapper) {
        objectMapper.registerModule(new JavaTimeModule());
        final SimpleModule reproducer = new SimpleModule("reproducer");
        reproducer.addSerializer(new CustomSerializerDtoSerializer());
        objectMapper.registerModule(reproducer);
    }
}
````

When the server serializes a response with the custom serializer, it fails for `gen.writeObjectField("datetime", value.dateTime());` saying that the `JavaTimeModule` isn't registered:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
```

This happens because the JsonGenerator's codec is not properly configured. The root cause seems to be how the `JsonFactory` is copied here:
https://github.com/quarkusio/quarkus/blob/72d993c54b35f6a8bfcf048aa89d997aeeb6e5a1/independent-projects/resteasy-reactive/server/jackson/src/main/java/org/jboss/resteasy/reactive/server/jackson/JacksonMessageBodyWriterUtil.java#L29
The docs of `JsonFactory.copy()` state that
> Note that ObjectCodec reference is not copied but is set to null; caller typically needs to set it after calling this method. Reason for this is that the codec is used for callbacks, and assumption is that there is strict 1-to-1 mapping between codec, factory. Caller has to, then, explicitly set codec after making the copy.

The setting of the codec is missing in this method. As far as I can tell, copying the whole `ObjectMapper` and using its writer fixes the bug:
```java
    public static ObjectWriter createDefaultWriter(ObjectMapper mapper) {
        JsonFactory jsonFactory = mapper.getFactory();
        if (needsNewFactory(jsonFactory)) {
            ObjectMapper copy = mapper.copy();
            setNecessaryJsonFactoryConfig(copy.getFactory());
            return copy.writer();
        } else {
            return mapper.writer();
        }
    }
```

### Expected behavior

The server should serialize objects that have a registered a custom serializer and rely on other registered Jackson modules.

### Actual behavior

The server fails to serialize such objects.

### How to Reproduce?

Reproducer Repository: https://github.com/torbsto/quarkus-json-reproducer

[This test case](https://github.com/torbsto/quarkus-json-reproducer/blob/main/src/test/java/com/bakdata/reproducer/ReproducerResourceTest.java) shows that it results in an internal server error when trying to return a `CustomSerializerDto`.

### Quarkus version or git rev

3.5.0

**Comment by geoand** [comment]
Interesting, I'll have a look soon

**Comment by geoand** [comment]
@torbsto as you seem to have done a deep dive into the cause, would you like to contribute a fix?
