### ISSUE TITLE
Kafka Reactive Streams on Windows: Incoming messages comes way too long after restart

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#36862]
### Describe the bug

I have app with Kafka Reactive Streams that I run on Windows, when I start application and emit messages to channel `slow-topic`, I get incoming messages from Kafka almost immediately. However when I shutdown application and start it again right now, same procedure produce no results.

### Expected behavior

Everything works on Linux just fine. Waiting 50 seconds on Windows after restart (and after app is fully started) before I produce any messages for the topic seems to fix the issue.

### Actual behavior

When I call `org.eclipse.microprofile.reactive.messaging.Emitter#send(T)` right after app started, I can see in log:

```
16:45:21,974 INFO  [app] 16:45:21,854 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@2e538b4c to Kafka topic 'slow'
16:45:21,974 INFO  [app] 16:45:21,858 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@4470c39f to Kafka topic 'slow'
16:45:21,974 INFO  [app] 16:45:21,858 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@250d8408 to Kafka topic 'slow'
16:45:21,974 INFO  [app] 16:45:21,858 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@6df12b50 to Kafka topic 'slow'
16:45:21,974 INFO  [app] 16:45:21,859 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@6b9ecf33 to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,859 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@293095e4 to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,859 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@60d4690e to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,860 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@49b65ef to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,860 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@19e1c518 to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,860 SRMSG18209: Sending message org.eclipse.microprofile.reactive.messaging.Message$8@3453ec75 to Kafka topic 'slow'
16:45:21,975 INFO  [app] 16:45:21,899 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@2e538b4c sent successfully to Kafka topic-partition 'slow-0', with offset 0
16:45:21,976 INFO  [app] 16:45:21,901 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@4470c39f sent successfully to Kafka topic-partition 'slow-0', with offset 1
16:45:21,976 INFO  [app] 16:45:21,902 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@250d8408 sent successfully to Kafka topic-partition 'slow-0', with offset 2
16:45:21,976 INFO  [app] 16:45:21,902 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@6df12b50 sent successfully to Kafka topic-partition 'slow-0', with offset 3
16:45:21,976 INFO  [app] 16:45:21,903 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@6b9ecf33 sent successfully to Kafka topic-partition 'slow-0', with offset 4
16:45:21,976 INFO  [app] 16:45:21,904 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@293095e4 sent successfully to Kafka topic-partition 'slow-0', with offset 5
16:45:21,976 INFO  [app] 16:45:21,904 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@60d4690e sent successfully to Kafka topic-partition 'slow-0', with offset 6
16:45:21,976 INFO  [app] 16:45:21,905 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@49b65ef sent successfully to Kafka topic-partition 'slow-0', with offset 7
16:45:21,977 INFO  [app] 16:45:21,905 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@19e1c518 sent successfully to Kafka topic-partition 'slow-0', with offset 8
16:45:21,977 INFO  [app] 16:45:21,906 SRMSG18211: Message org.eclipse.microprofile.reactive.messaging.Message$8@3453ec75 sent successfully to Kafka topic-partition 'slow-0', with offset 9
```

but no incoming messages. When I wait before I emit for 50 seconds, I can see incoming messages. When I don't wait, emit immediately and then wait for 50 seconds, no incoming messages.

### How to Reproduce?

1. `git clone https://github.com/michalvavrik/quarkus-test-suite.git`
2. `cd quarkus-test-suite/messaging/kafka-streams-reactive-messaging`
3. `git checkout reproducer/win-kafka-native`
4. `mvn clean verify -Dit.test=KafkaGratefulShutdownIT#shouldWaitForMessagesWhenGratefulShutdownIsEnabled`

### Output of `uname -a` or `ver`

Windows Server 2022

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### Quarkus version or git rev

3.x && 999-SNAPSHOT (didn't try 2.x)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

Kafka Strimzi `quay.io/strimzi/kafka:0.34.0-kafka-3.4.0`
I've tried to add SmallRye Health and everything was ready expect for some issue with topology manager, but that also happens on Linux.

**Comment by cescoffier** [comment]
What is your reset strategy? Are you reusing the same broker and consumer group?

**Comment by michalvavrik** [comment]
> What is your reset strategy? Are you reusing the same broker and consumer group?

I restart by destroying the process (e.g. `java -jar ...`) and executing the command again. I am using following method https://github.com/quarkus-qe/quarkus-test-framework/blob/b3166c3478cb4a8af0734c03b89e4195cfef134b/quarkus-test-core/src/main/java/io/quarkus/test/utils/ProcessUtils.java#L21

**Comment by michalvavrik** [comment]
What I tried to say is that I don't change a thing.
