### ISSUE TITLE
Native binary generated using quarkus, graalvm and picocli trying to read from .env folder in working directory

### ISSUE THREAD

**Issue by mehab** [quarkusio/quarkus#36868]
### Describe the bug

A native binary generated using quarkus, graalvm and picocli is being executed in a directory containing a python virtual environment directory called .env 
Because of the naming convention of this folder, the executable is trying to read from this .env folder (assuming it is a .env file containing some quarkus config) which should not happen.
It would be helpful if the framework is able to differentiate between .env folder and .env file and read accordingly. 

### Expected behavior

It would be helpful if the framework is able to differentiate between .env folder and .env file and read accordingly. 

### Actual behavior

It is assuming that the .env folder is a file and trying to read it throws an IOException not a file from Quarkus.

### Quarkus version or git rev

2.13.3.Final

**Comment by mehab** [comment]
should a check here for is a directory suffice? https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/DotEnvConfigSourceProvider.java#L20 @radcortez

**Comment by radcortez** [comment]
Only partially. The Provide would still be part of the Config init, so it would require to be able to return an empty list of sources if the location is invalid.
