### ISSUE TITLE
Quarkus JTA has not needed Dependency to ejb-api

### ISSUE THREAD

**Issue by wwwaldemar** [quarkusio/quarkus#36882]
Even if Quarkus is not en EJB Container, it has ejb-api dependency in the classpath

Please remove it because we have e.g. two `@Startup` Annotations in classpath one from ejb and one from quarkus, which is error prone

[INFO] │  │  ├─ org.jboss.narayana.jta:narayana-jta:jar:7.0.0.Final (compile)
[INFO] │  │  │  ├─ org.jboss:jboss-transaction-spi:jar:8.0.0.Final (compile)
[INFO] │  │  │  ├─ jakarta.resource:jakarta.resource-api:jar:2.1.0 (compile)
[INFO] │  │  │  ├─ org.jboss.invocation:jboss-invocation:jar:2.0.0.Final (compile)
[INFO] │  │  │  ├─ jakarta.ejb:jakarta.ejb-api:jar:4.0.1 (compile)

### Expected behavior

no ejb-api in classpath

### Actual behavior

ejb-api is in classpath

### How to Reproduce?

- add narayana jta dependency
- call `mvn quarkus:dependency-tree`
- in the output find the ejb-api dependecy

### Output of `uname -a` or `ver`

maven 3.9

### Output of `java -version`

Temurin-21.0.1+12

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by marcosgopen** [comment]
Thanks for reporting this @wwwaldemar. We are going to change jakarta.ejb:jakarta.ejb-api:jar:4.0.1 scope to test. I will soon link the PR.

**Comment by mmusgrov** [comment]
@marcosgopen We should do that but it will require a release of narayana so the immediate fix is to add an exclusion in `extensions/narayana-jta/runtime/pom.xml` where we depend on org.jboss.narayana.jta:narayana-jta:

```
                <exclusion>
                    <groupId>jakarta.ejb</groupId>
                    <artifactId>jakarta.ejb-api</artifactId>
                </exclusion>

```

**Comment by marcosgopen** [comment]
> @marcosgopen We should do that but it will require a release of narayana so the immediate fix is to add an exclusion in `extensions/narayana-jta/runtime/pom.xml` where we depend on org.jboss.narayana.jta:narayana-jta:
> 
> ```
>                 <exclusion>
>                     <groupId>jakarta.ejb</groupId>
>                     <artifactId>jakarta.ejb-api</artifactId>
>                 </exclusion>
> ```

Thanks Mike! I opened the PR [here](https://github.com/quarkusio/quarkus/pull/36950).
