### ISSUE TITLE
Quarkus >= 3.3.0 can't find new MockitoConfig

### ISSUE THREAD

**Issue by dkr91** [quarkusio/quarkus#36896]
### Describe the bug

Hey, I am updating Quarkus from 3.2.6 to latest. 
In doing so i got issues replacing the old JUnit Injectmock with Arguments with the new MockitoConfig.
The Jenkis I use does not find the new Annotion despite IntelliJ saying it exitis with the same dependency file.

### Expected behavior

The new place of InjectMock and MockitoConfig gets Used as it was prior to 3.3.x

### Actual behavior

Jenkis and IntelliJ can't find the MockitoConfig annotaion

### How to Reproduce?

Update Quarkus in settings.gradle & build.gradle to 3.3.0 or above
Replace all imports with the new place of JUnit Mockito in the io.quarkus Namespace

### Output of `uname -a` or `ver`

Linux ENGBUILDVM291 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Eclipse Temurium 17.0.9.9 Docker

### Quarkus version or git rev

3.3.0+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.4

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
@dkr91 So if I understand it correctly you cannot reproduce it locally, right?

**Comment by dkr91** [comment]
I can and get the same error. I now have opted to use the 3.2.7.final Quarkus as LTS to avoid further time-wasting.

**Comment by gsmet** [comment]
Instead of closing the issue, I think it would be better to provide a small reproducer as you will have to upgrade at some point and you will be hit by that again.
