### ISSUE TITLE
Quarkus 3.4.x+ forces ASCII logging out to console instead of abiding by environment/system default as it had previously

### ISSUE THREAD

**Issue by idursto** [quarkusio/quarkus#36919]
### Describe the bug

I am not sure why, but somewhere between Quarkus 3.3.3 & 3.4.x something changed in how the logging is happening.  Prior to 3.4.x I could deploy anywhere and log to the console and it would abide by the system default encoding for the logging (for instance if I deployed to z/OS the encoding would be EBCDIC and the logs could easily be viewed through checking the console).  The same happened for logging to a file...before 3.4.x it was defaulting to EBCDIC and now it is ASCII, however I have the ability to switch the encoding on the file via the quarkus.log.file.encoding setting (https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus.log.file.encoding) and that is working.  I do not have the option of setting the console log encoding though regardless of what I have tried.  More importantly I am curious and cannot find as to what changed that is causing this.

### Expected behavior

The encoding for console logging should not have changed between Quarkus 3.3.3 & 3.4.x or at a minimum I should be able to set something to switch the console logging back to what it was.

### Actual behavior

The encoding for console logging is now always ASCII with no way to set/change it.

### How to Reproduce?

1. Deploy Quarkus 3.3.3 HelloWorld application to z/OS and note that it logs to console in EBCDIC
2. Deploy Quarkus 3.4.x HelloWorld application to z/OS and note that it logs to console in ASCII with no way of fixing/changing it

### Output of `java -version`

java version "11.0.17" 2022-10-18 IBM Semeru Runtime Certified Edition for z/OS 11.0.17.0 (build 11.0.17+8)

### Quarkus version or git rev

3.3.3 & 3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.4

### Additional information

I am confused as they are using the same slf4j and logmanager dependencies/libraries?

Quarkus 3.3.3 (Console logging encoding in EBCDIC):

[INFO] \- io.quarkus:quarkus-arc:jar:3.3.3:compile
[INFO]    \- io.quarkus:quarkus-core:jar:3.3.3:compile
[INFO]       +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]       \- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile

Quarkus 3.4.1 (Console logging encoding in ASCII):

[INFO] \- io.quarkus:quarkus-arc:jar:3.4.1:compile
[INFO]    \- io.quarkus:quarkus-core:jar:3.4.1:compile
[INFO]       +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]       \- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile

**Comment by gastaldi** [comment]
@jamezp any hints?

**Comment by dmlloyd** [comment]
Quarkus 3.4.0 was the first release to include the logmanager reunification. So, the difference probably lies either in that patch or in the diff between the forked embedded logmanager and the mainline logmanager. I'll look into it.

**Comment by dmlloyd** [comment]
There's a potential fix here: jboss-logging/jboss-logmanager#441 - it'll take a day or two though due to waiting for Maven repository synch with central for some artifacts.
