### ISSUE TITLE
OpenTelemetry Trace ID Not Available to Log4j2

### ISSUE THREAD

**Issue by mbchangellc** [quarkusio/quarkus#36931]
### Describe the bug

Using a log format that includes the OpenTelemetry trace ID, it's empty in logging statements written using Log4j2 API.  Logging statements written using JBoss Logging or SLF4J API do include the traceId running with the same configuration.  In all cases the logging backend is JBoss LogManager.  The provided reproducer illustrates the issue.

### Expected behavior

The traceId included in the logging statements when using Log4j2.

### Actual behavior

The traceId isn't included in the logging statements when using Log4j2.  The logging output is below.

2023-11-07 16:47:39,846 INFO  [exa.ExampleEndpoint] (executor-thread-1) [] Log4j2
2023-11-07 16:47:39,849 INFO  [exa.ExampleEndpoint] (executor-thread-1) [7ea31095cbdfca5684a23a088f12d5a4] Sfl4j
2023-11-07 16:47:39,849 INFO  [exa.ExampleEndpoint] (executor-thread-1) [7ea31095cbdfca5684a23a088f12d5a4] JBoss Logging
2023-11-07 16:47:39,853 INFO  [io.qua.htt.access-log] (executor-thread-1) [7ea31095cbdfca5684a23a088f12d5a4] "127.0.0.1 - - [07/Nov/2023:16:47:39 -0500] GET /example/test HTTP/1.1 204 - 25ms"

### How to Reproduce?

1. Run the reproducer by executing the quarkusDev Gradle task.
2. Send a GET request to http://localhost:8080/example/test
3. View the resulting logging output.

The logging statements written using SLF4J and JBoss Logging include the traceId but the statement written with Log4j2 doesn't.

[mdc-propagation-issue.tar.gz](https://github.com/quarkusio/quarkus/files/13289518/mdc-propagation-issue.tar.gz)

### Output of `uname -a` or `ver`

Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by brunobat** [comment]
Thanks for the reproducer @mbchangellc

**Comment by brunobat** [comment]
@mbchangellc this seems not to happen anymore. The bug cannot be reproduced since at least 3.15.2 (the current LTS).
We will not fix the issue for 3.5.0. Can you please upgrade?
