### ISSUE TITLE
Possible import script for MongoDB

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#36948]
### Description

Idea from the review of Quarkus in Action book. Maybe we could add functionality that would do static imports like we have with relation DBs in import.sql also for MongoDB? A quick search looks like it should be possible - https://stackoverflow.com/questions/19441228/insert-json-file-into-mongodb. Or we could also manually parse the file with our specific markup to allow also other operations.

**Comment by loicmathieu** [comment]
@xstefank I agree it should be, don't hesitate to open a PR to update the documentation ;)
