### ISSUE TITLE
Quarkus 3.5.1 trying to use Docker when the default profile uses a container image build even though the build is done with a different profile that disables it

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#36951]
### Describe the bug

I have a project with the following `application.properties`:

```properties
quarkus.package.type=native
quarkus.native.remote-container-build=true
quarkus.container-image.build=true
%ci.quarkus.package.type=uber-jar
%ci.quarkus.test.integration-test-profile=ci
%ci.quarkus.native.remote-container-build=false
%ci.quarkus.container-image.build=false
```

### Expected behavior

Same as Quarkus 3.5.0 - it builds an über jar without requiring a Dockerfile

### Actual behavior

When building with Quarkus 3.5.1 `./gradlew quarkusBuild -Dquarkus.profile=ci` I get an error:

```
* What went wrong:
Execution failed for task ':the-project:quarkusBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.IllegalStateException: Unable to find Dockerfile Dockerfile.jvm in /Users/josephea/Developer/the-project/src/main/docker
```

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.1.0

### Output of `java -version`

17.0.9 (Eclipse Adoptium 17.0.9+9)

### Quarkus version or git rev

3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.4

**Comment by geoand** [comment]
cc @radcortez

**Comment by josephearl** [comment]
Quarkus 3.5.2+ seems fine, closing. Thanks all, happy coding.

**Comment by geoand** [comment]
Thanks for the update!
