### ISSUE TITLE
Licensing mismatch

### ISSUE THREAD

**Issue by hyandell** [quarkusio/quarkus#36958]
### Describe the bug

I wanted to flag that the repository marks its licensing as Apache-2.0, but contains the following LGPL-2.1 licensed file:

https://github.com/quarkusio/quarkus/blob/main/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/cdi/QuarkusArcBeanContainer.java

I'm unsure if that's intended, so wanted to raise the issue.

**Comment by Sanne** [comment]
Thanks for spotting that, it's a mistake - I will fix the headers, I see there's a couple more in the Hibernate ORM extension.

This is probably caused as we work back and forth on the Hibernate codebase for such issues, and might have the wrong template enabled.
