### ISSUE TITLE
-Dquarkus.container-image.push=true used with gradle seems not to push anymore since 3.5.1

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#36969]
### Describe the bug
We use gradle.
With the io.quarkus 3.5.1 plugin, our artefact does not get pushed to our registry anymore. Reverting to 3.5.0 solves the issue.

To complete command that seems no to push the artefact to the repo anymore is:

`gradlew --warning-mode all -Dorg.gradle.jvmargs=-Xmx1g -x test :quarkusIntTest -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.registry=ourRegistry.azurecr.io -Dquarkus.container-image.tag=main-79031f8-153 -Dquarkus.native.builder-image.pull=missing`

I am not sure on how I can give you more information about this. Please let me know.

**Comment by mschorsch** [comment]
My impression is that quarkus does not honor system properties in all cases anymore since 3.5.1. This seems a gradle only problem.

**Comment by geoand** [comment]
cc @snazy @glefloch @aloubyansky

**Comment by mschorsch** [comment]
In our case, `-Dquarkus.quinao=true` is not taken into account.

**Comment by andreas-eberle** [comment]
We experience the same when just building the container. Then it should be pushed to the local docker registry but with 3.5.1 it is no longer the case.

Command: `./gradlew assemble -Dquarkus.container-image.build=true`

We are using the JIB extension.

**Comment by HerrDerb** [comment]
@aloubyansky Thank you very much 🙂👍
Is 3.6 gonna be the next release or can we include this fix in the next bugfix release 3.5.2?

**Comment by aloubyansky** [comment]
Yes, it will be backported to 3.2.9 and 3.5.2 this week.

**Comment by HerrDerb** [comment]
@aloubyansky superbe 👍
