### ISSUE TITLE
GraalVM Version parser is too strict

### ISSUE THREAD

**Issue by brunocaballero** [quarkusio/quarkus#36972]
### Describe the bug

When building a Native Image using GraalVM, Quarkus parses the version of native-image on the following class:

[https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java
)

The check fails for some custom Runtimes we are developing.

In particular Quarkus expects the runtime to be OpenJDK or GraalVM, and the vm name OpenJDK 64-Bit Server or Substrate 

`private static final String RUNTIME_NAME = "(?<RUNTIME>(?:OpenJDK|GraalVM) Runtime Environment) ";`
`private static final String VM_NAME = "(?<VM>(?:OpenJDK 64-Bit Server|Substrate) VM) ";`

### Expected behavior

I would expect to accept other runtimes.

Maybe something like:

`private static final String RUNTIME_NAME = "(?<RUNTIME>.*) Runtime Environment) ";`
`private static final String VM_NAME = "(?<VM>.*) VM) ";`

### Actual behavior

Other runtimes are currently not supported by recent version of Quarkus.

**Comment by zakkak** [comment]
Hi @brunocaballero, that makes sense.

Could you please open a PR with the necessary changes, extending the tests in https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/GraalVMTest.java to cover your case as well?

Thanks

cc @jerboaa

**Comment by jerboaa** [comment]
I think that one got fixed with https://github.com/quarkusio/quarkus/pull/37651?

**Comment by brunocaballero** [comment]
yes, fixed in https://github.com/quarkusio/quarkus/pull/37651
