### ISSUE TITLE
Mongodb OpenTelemetry tracing 

### ISSUE THREAD

**Issue by aka-peter** [quarkusio/quarkus#36971]
### Description

Hello,

I am currently trying to get OpenTelemetry in to the services of our application stack.

As the OpenTracing project is archived, is it possible to get OpenTelemetry support in the Mongodb extension instead?

Thank you!

**Comment by brunobat** [comment]
This is planned @aka-peter.
This issue is a duplicated from https://github.com/quarkusio/quarkus/issues/28473. Closing.
