### ISSUE TITLE
quarkus.container-image.push=true not working in 3.2.8

### ISSUE THREAD

**Issue by dylanenabled** [quarkusio/quarkus#36992]
### Describe the bug

In 3.2.7 running

./gradlew build -Dquarkus.package.type=fast-jar -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true

causes the container to be pushed after it has built.

In 3.2.8 it builds but does not push.

### Expected behavior

It should push the container to the repository defined, as the documentation says.

### Actual behavior

It builds but does not push.

### How to Reproduce?

Set up the application properties as in https://quarkus.io/version/3.2/guides/container-image#pushing

Use version 3.2.8

Run ./gradlew build -Dquarkus.package.type=fast-jar -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true

It doesn't push.

### Output of `uname -a` or `ver`

Linux d59818fa6fbe 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9) OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

### Quarkus version or git rev

3.2.8.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.4 ------------------------------------------------------------  Build time:   2023-10-04 20:52:13 UTC Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f  Kotlin:       1.9.10 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.9 (Eclipse Adoptium 17.0.9+9) OS:           Linux 6.2.0-1012-aws amd64

**Comment by geoand** [comment]
Seems to be related to #36969.

cc @snazy @glefloch @aloubyansky

**Comment by techorix** [comment]
thanks a lot for fixing this. i had big problems with quarkus accepting gradle parameters at all since 3.2.5. i had to use environment variables in order to overwrite my application.properties during CI/CD and couldn't use -Dquarkus.... parameters anymore.
