### ISSUE TITLE
REST client reactive should allow to instantiate clients based on (external) classes without `@RegisterRestClient` annotation

### ISSUE THREAD

**Issue by lw-mcno** [quarkusio/quarkus#37007]
### Description

During the migration from rest-client to rest-client-reactive, it has turned out, that the reactive doesn't allow to instantiate clients based on external (imported from dependencies) interface definitions (lacking the `@RegisterRestClient` annotation).

In the rest-client classic, this configuration alone is sufficient to instantiate a client bean (providing that `MyRestServiceClass` contains appropriate JAX-RS annotations):

```yaml
rest-client:
  "myPackage.MyRestServiceClass":
    scope: jakarta.enterprise.context.Singleton
    url: ${my-service.url}
```

### Implementation ideas

It was discussed in the Zulip chat, and suggested by @Ladicek, that such a functionality (automatically adding `@RegisterRestClient` during build time to classes injected into `@RestClient`-annotated slots), could be implemented using a build step.

**Comment by lw-mcno** [comment]
@cescoffier, @geoand issue created as discussed.

**Comment by geoand** [comment]
So simply using the configuration above makes the classic rest client work? Nothing else involved?

**Comment by lw-mcno** [comment]
Yes, with the same configuration, the classic client just instantiates and injects the bean, whereas the rest reactive client doesn't produce a candidate for injection (no client gets instantiated).

**Comment by geoand** [comment]
I personally think that enabling this feature from the old client makes sense.

**Comment by Serkan80** [comment]
The scope should be default Singleton imo and not required to be specified in the configuration. 

Because only ApplicationScope is needed for mocking in tests and this can already be done.

**Comment by geoand** [comment]
@lw-mcno do you have an example of this working for RESTEasy Classic that I can use?

**Comment by lw-mcno** [comment]
Hi @geoand 

I've added a simple reproducer here: https://github.com/lw-mcno/quarkus-rest-client-classic-without-registration
The client interface would normally come from a dependency, but it's located in the repository for simplicity.
If you change the dependency to `quarkus-rest-client-reactive-jackson`, it will not allow to instantiate the client.

BTW. is it allowed to have reactive (server) and classic clients? From my experiments here, it doesn't seem so. When I had resteasy and rest-client-reactive, I've gotten a message, that it is not allowed to mix classic and reactive server (sic!) components.

**Comment by geoand** [comment]
@lw-mcno thanks. 

So I just saw that the classic REST Client unconditionally registers the interface as a bean, even if there is no configuration. That is something I am not willing to add to the reactive version of the client.

However, I do see merit in the proposal to register the client as a bean when 

```
quarkus:
  rest-client:
    "org.acme.ExampleRestService":
      scope: whatever
```

is set.

**Comment by lw-mcno** [comment]
@geoand : Thanks for looking into this and great that the functionality can be extended to accomodate my our use case.
