### ISSUE TITLE
Add qute-web to the platform

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#37000]
As this is now controlling Qute RESTEasy (Classic and Reactive) and this is a very important extension for the Quarkus Web story, Qute Web should be part of the Quarkus Platform.

When it's in the platform, we should unlist Qute RESTEasy (Classic and Reactive).

**Comment by maxandersen** [comment]
will this extension be affected by the future suggested rename/change of removing reactive from names?

**Comment by aloubyansky** [comment]
if it's a single extension we could add it to the `quarkus-bom` in the platform.

**Comment by ia3andy** [comment]
@aloubyansky will that make it part of the paltform on code.quarkus.io

**Comment by aloubyansky** [comment]
Yes

**Comment by ia3andy** [comment]
ok so let's wait for the 3.0.0 of quarkus-qute-web and add it there :)

**Comment by ia3andy** [comment]
We will need to put qute-web in the platform in between the core release 3.6.0 and the platform release (because it will need to be released with 3.6.0 core).

@gsmet is there something specific to do in order to plan this?

**Comment by maxandersen** [comment]
Unlisting is just on code.quarkus ui, right?

The extension can still be referenced in cli and code.quarkus rest api ?

**Comment by ia3andy** [comment]
Yes

**Comment by ia3andy** [comment]
and also maybe for the extensions page @holly-cummins? I think it makes sense to unlist it from there to.

**Comment by ia3andy** [comment]
@maxandersen stupid question, why would it be a problem not to have it usable in CLI? Those extensions are useless by themselves as soon as we have the conditional system.

**Comment by ia3andy** [comment]
Yeah I tested quarkus-arc is not in quarkus.io/extensions (it's unlisted) which is a good thing

**Comment by mkouba** [comment]
> @mkouba it'd be done here https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L183-L197

Something like this? https://github.com/mkouba/quarkus-platform/commit/4153dc1b067076586d8aa70c78a768845c4b80c9

**Comment by maxandersen** [comment]
> @maxandersen stupid question, why would it be a problem not to have it usable in CLI? Those extensions are useless by themselves as soon as we have the conditional system. 

Only if you are on that specific version that has it - cli needs to continue to work for older versions. I don't know which extensions you are referring to as useless so can't answer your question fully.

**Comment by maxandersen** [comment]
> will this extension be affected by the future suggested rename/change of removing reactive from names?

Didn't see reply to this - any concerns/actions there ?

**Comment by mkouba** [comment]
> > will this extension be affected by the future suggested rename/change of removing reactive from names?
> 
> Didn't see reply to this - any concerns/actions there ?

I don't think so. Except that we'll have to update the conditional dependencies on resteasy integration modules...

@ia3andy WDYT?
