### ISSUE TITLE
Can't override REST API headers if configuration is not in application.properties

### ISSUE THREAD

**Issue by szatyinadam** [quarkusio/quarkus#37027]
### Describe the bug

I have created a small application which connects to a REST API and authenticate with basic auth.

If I set the configuration in application.properties everything works fine:
`quarkus.rest-client."rest-api".headers.Authorization=Basic dXNlcjpwYXNzd29yZA==`

If I remove the auth string from application.properties and set it in environment variable, it still works:
application.properties - `quarkus.rest-client."rest-api".headers.Authorization=Basic`
run command - `export QUARKUS_REST_CLIENT__REST_API__HEADERS_AUTHORIZATION=Basic dXNlcjpwYXNzd29yZA== && export QUARKUS_REST_CLIENT__REST_API__URL=http://172.16.100.23:8888/report/tig && java -jar target/quarkus-app/quarkus-run.jar`
log entry for the REST call -  `Request: GET http://172.16.100.23:8888/report/tig Headers[Authorization=Basic dXNlcjpwYXNzd29yZA== User-Agent=Resteasy Reactive Client], Empty body`

When I remove everything from the application.properties and run the application with the above run command it does not use the configuration:
log entry for the REST call - `Request: GET http://172.16.100.23:8888/report/tig Headers[User-Agent=Resteasy Reactive Client], Empty body`

The [quarkus.rest-client."config-key".headers](https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.headers-headers) is not marked as a build time property.
I expected the application should use it even when the configuration is not in the application.properties. The [quarkus.rest-client."config-key".url](https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.url) works this way.

(I am new to Quarkus and if I'm miss something and this is an expected behaviour then please point in the documentation.)

### Expected behavior

The application should use the configuration even if it is not in the application.properties file.

### Actual behavior

The application ignores the QUARKUS_REST_CLIENT__REST_API__HEADERS_AUTHORIZATION configuration but use the QUARKUS_REST_CLIENT__REST_API__URL configuration. None of them is set in the application.properties.

### How to Reproduce?

1. Create the application:  
`quarkus create app org.example:rest-client-config --extension='resteasy-reactive,quarkus-rest-client-reactive'`
2. Add demo REST client:
```java
@RegisterRestClient(configKey = "rest-api")
public interface DemoRestClient {

    @GET
    Response get();
}
```
3. Set the configuration via environment variable or system variable (I have an application with Basic auth) and start the application:  
` export QUARKUS_REST_CLIENT__REST_API__HEADERS_AUTHORIZATION=Basic dXNlcjpwYXNzd29yZA== && export QUARKUS_REST_CLIENT__REST_API__URL=http://172.16.100.23:8888/report/tig && java -jar target/quarkus-app/quarkus-run.jar`

### Output of `uname -a` or `ver`

Darwin Adams-MacBook-Pro-2.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### Quarkus version or git rev

3.4.3. 3.5.0, 3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /Users/aszatyin/.m2/wrapper/dists/apache-maven-3.9.5-bin/32db9c34/apache-maven-3.9.5 Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /Users/aszatyin/.sdkman/candidates/java/21.0.1-tem Default locale: en_HU, platform encoding: UTF-8 OS name: "mac os x", version: "14.1.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
I'll have to check this...

**Comment by cescoffier** [comment]
I think it's a config issue.  @radcortez

**Comment by radcortez** [comment]
When an environment variable with a dynamic segment is set without any additional information, following the environment variable name conversion rules, the Config system is unable to determine if `REST_API` is `rest.api`, `rest-api` (or use any other special character in between).

For this reason, you must add the dotted name property `quarkus.rest-client."rest-api".headers.Authorization` in another configuration source (it can be empty), to disambiguate the names. The Environment variable will override the variable and match the dotted name.

Please, also check https://quarkus.io/guides/config-reference#environment-variables

**Comment by szatyinadam** [comment]
Thanks for the clarification and the URL. 

It works with system parameters:
`java -Dquarkus.rest-client."rest-api".headers.Authorization="Basic dXNlcjpwYXNzd29yZA==" -Dquarkus.rest-client."rest-api".url=http://172.16.100.23:8080/report/tig -jar target/quarkus-app/quarkus-run.jar`

What is strange or not so intuitive to me is:
- The config can handle the URL environment variable, so in that case it can determine the class name which should be configured.
- I've tried to rename the config key to `restapi` (without hyphen or any separator character), start it with `export QUARKUS_REST_CLIENT__RESTAPI__HEADERS_AUTHORIZATION='Basic dXNlcjpwYXNzd29yZA==' && export QUARKUS_REST_CLIENT__RESTAPI__URL=http://172.16.100.23:8888/report/tig && java -jar target/quarkus-app/quarkus-run.jar` and it still does not use the header.
