### ISSUE TITLE
QuarkusTest does not take into consideration dependencies defined in the maven profile

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#3702]
**Describe the bug**
When running maven build with tests (`@QuarkusTest`) that requires dependencies defined in the profile that fails with Arc dependency resolution exceptions due to missing classes.

**Expected behavior**
`@QuarkusTest` should see dependencies define in the profile when the profile is active 

**Actual behavior**
Dependencies defined in the profile are not seen by `@QuarkusTest`

**To Reproduce**
1. Create a test case that expects to have bean injected from a dependency that is defined in maven profile
2. run a test with activated profile

**Configuration**
no config needed

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin mac 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "1.8.0_171"
 - GraalVM version (if different from Java): 19.2.0
 - Quarkus version or git rev: master

**Comment by mswiderski** [comment]
would be still good to allow running quarkus tests with maven profiles in my opinion

**Comment by aloubyansky** [comment]
I think I have a fix for this one.
