### ISSUE TITLE
Sse difference in empty event between non-reactive and reactive output

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#37033]
### Describe the bug

When sending event with empty data using reactive way the empty data is transformed in null. The same code using non-reactive return just empty data (which I think is correct).

 Happening with `quarkus-resteasy-reactive-*`. More info available in reproducers.

### Expected behavior

The reactive and non-reactive should have same output.

### Actual behavior

With non-reactive output is 
```
event: name=NOT EMPTY data={random data} and is empty: false
event: name=EMPTY data={} and is empty: true
```

With reactive output is
```
event: name=NOT EMPTY data={random data} and is empty: false
event: name=EMPTY data={null} and is empty: true
```

### How to Reproduce?

For non-reactive 
1. `git clone -b sse-non-reactive git@github.com:jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `mvn quarkus:dev -Dquarkus.platform.version=3.5.1`
4. `Go to http://127.0.0.1:8080/sse/client`

For reactive
1. `git checkout sse-native-method-404`
2. `mvn quarkus:dev -Dquarkus.platform.version=3.5.1`
3. `Go to http://127.0.0.1:8080/sse/client`

The output is show in actual behavior section

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/37036 fixes the issue

**Comment by michalvavrik** [comment]
https://github.com/quarkusio/quarkus/pull/35990 was backported, so I think this one should be as well

**Comment by michalvavrik** [comment]
> @michalvavrik triage/backport* labels may not be added to an issue. Please add them to the corresponding pull request.
> 
> This message is automatically generated by a bot.

sorry
