### ISSUE TITLE
Make @DefaultBean work with @Priority

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#37042]
### Description

Let's say I work on a small framework which can be used by an application by depending on several different dependencies (`framework-core` or `framework-advanced`), based on the application needs.

The `framework-core` dependency contains these two classes:
```
@ApplicationScoped
@DefaultBean
public class CoreFeature {
    // Details omitted, not relevant
}

@ApplicationScoped
public class InternalFrameworkService {

    @Inject
    CoreFeature coreFeature;

    // coreFeature is used somehow.
}
```

The `framework-advanced` dependency depends on `framework-core` and contains this class:
```
@ApplicationScoped
@DefaultBean
public class AdvancedFeature extends CoreFeature {
    // Details omitted, not relevant
}
```
Right now, when an app depends on `framework-advanced`, Arc will complain because it cannot determine which of `CoreFeature` and `AdvancedFeature` should be injected in `InternalFrameworkService`. I would like this to work using `@Priority` on `CoreFeature` and `AdvancedFeature` so that Arc injects the one with the highest priority, just like it does with `@Alternative`.

Why do I need `@DefaultBean`? Because I want the users of the framework to be able to do this:
```
@ApplicationScoped
public class UserCustomizedCoreFeature extends CoreFeature {
    // Details omitted, not relevant
}
```
Or that:
```
@ApplicationScoped
public class UserCustomizedAdvancedFeature extends AdvancedFeature {
    // Details omitted, not relevant
}
```
And override anything that comes from the framework with whatever they need to implement.

This whole thing can work without `@Priority` working with `@DefaultBean`, but the users of the framework have to use `@Alternative` alongside with `@Priority` on their class, which is something I'd like to avoid.

### Implementation ideas

Make `@DefaultBean` and `@Priority` work similarly to `@Alternative` and `@Priority`.

**Comment by Ladicek** [comment]
The feature request kinda makes sense, when you think of `@DefaultBean` as a reversed `@Alternative`. An alternative takes precedence over "normal" bean, and a "normal" bean takes precedence over "default bean".

**Comment by Ladicek** [comment]
We got rid of `@AlternativePriority` for a good reason, I wouldn't be a fan of sneaking something like that back :-)

Ah and yes, I agree vetoing `CoreFeature` is a good option for now.

**Comment by manovotn** [comment]
> Unfortunately, the framework I mentioned is not a Quarkus extension, so vetoing is not an option.

You might be able to achieve the same via CDI extension, in CDI Lite those are build compatible extensions and you can use the `@Enhancement` phase to add `@Vetoed` annotation.
