### ISSUE TITLE
Redis cache: Failed to connect to all nodes of the cluster

### ISSUE THREAD

**Issue by bartm-dvb** [quarkusio/quarkus#37041]
### Describe the bug

The Redis cache implementation fails to work in cluster mode. Under load, it will thrown an error: Failed to connect to all nodes of the cluster. This can be found in the vert.x redis client here: https://github.com/vert-x3/vertx-redis-client/blob/4.4.6/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L202

### Expected behavior

Cluster mode works.

### Actual behavior

Cluster mode throws an exception without stacktrace.

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /cat-fact failed, error id: 1cd9b164-ba80-4118-b675-ff5cfdfd93eb-869: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster
````

Setting `quarkus.redis.max-pool-size` to a higher value seems to postpone the error, but it will still eventually fail.

### How to Reproduce?

1. Clone repo: https://github.com/bartm-dvb/quarkus-redis-bug
2. Start Redis in cluster mode with `docker-compose up`
3. `./mvnw quarkus:dev` 
4. Start load test with jMeter, configuration file is in the repository.

After about 30 seconds of load testing, you should see

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /cat-fact failed, error id: 1cd9b164-ba80-4118-b675-ff5cfdfd93eb-869: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster
```

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

**Comment by cescoffier** [comment]
\CC @Ladicek

**Comment by sfali16** [comment]
I would like to help contribute to this issue. I'm able to reproduce the issue on my system, but unsure where to start. 
From what I gathered,  the load test causes the connections to fail and once the connection objects are "corrupted" (have encountered exceptions), it never recovers. 
I see a similar pattern if i shutdown the redis cluster and restart it - the exceptions continue. 

Any tips or code pointers would help as I'm familiar with java but new to quarkus and vertx.

**Comment by cescoffier** [comment]
We got a report for something similar when there is a DNS issue. It looks like the connections are not released after an error. I believe the issue is not in Quarkus but in the Vert.x Redis client. @Ladicek should know more, as he recently looked at this code. 

I think that investigating what happens when a failure happens in the Vert.x redis client code would be a first great step. There should be _exceptionHandlers_ and I suspect that they are not releasing the connection.

The Vert.x redis client code is in https://github.com/vert-x3/vertx-redis-client/tree/4.4. Select the 4.4 branch - it's the one used in Quarkus (a forward port should be possible once we find the issue). Build it using `mvn clean install -DskipTests`. Then override the version in your project, just add the dependency:

```xml
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-redis-client</artifactId>
  <version>4.4.6-SNAPSHOT</version> <!-- verify it's what you built -->
```

**Comment by luneo7** [comment]
We are having the same issue, getting the `io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster` error log... I our case we have a custom DNS (CNAME) that points to an AWS Configuration endpoint, and we are running in cluster mode there as well... dunno if it might be the DNS roundtrip, since we use our custom DNS so we are able to easy construct the Redis endpoint, and terraform takes care of creating the CNAME to the AWS Configuration endpoint... so the vert.x redis client needs to solve the CNAME and later the configuration endpoint... one interesting thing is that looking at the cluster metrics the connections there never zeroed, and after we did a restart in the service we saw that the connections bumped, so it points to a load increase as well... as if when there is a sudden increase in the utilization of the client it fails to get new connections but existing connection remains there

**Comment by Ladicek** [comment]
I agree the problem likely exists in the Vert.x Redis client, but I _guess_ it's more like an exception handler is _missing_. But I didn't have time to take a proper look yet. If someone beats me to it, that's cool :-)

**Comment by luneo7** [comment]
If you also run https://github.com/rakyll/hey with the following parameters:
```
hey -c 100 -z 30s -m GET http://localhost:8080/cat-fact
```
You will see the same thing happening... so tweaking the concurrency `-c 100` you will see when it happens... so it seems that it looks like a pool exhaustion issue...

**Comment by Ladicek** [comment]
We should be able to collect all the failures and then fail the promise with an exception that has all the collected failures as suppressed exceptions I think?

**Comment by bartm-dvb** [comment]
> If you also run https://github.com/rakyll/hey with the following parameters:
> 
> ```
> hey -c 100 -z 30s -m GET http://localhost:8080/cat-fact
> ```
> 
> You will see the same thing happening... so tweaking the concurrency `-c 100` you will see when it happens... so it seems that it looks like a pool exhaustion issue...

Can you also confirm that the connection pool doesn't recover after it's exhausted?

**Comment by cescoffier** [comment]
Based on the analysis, it seems to be a problem in the Vert.x Redis client. @Ladicek can you open an issue there?

**Comment by Ladicek** [comment]
Based on the analysis, this does _not_ seem to be a problem in the Vert.x Redis client -- baring the unhelpful exception, which really should carry the underlying exceptions (as suppressed exceptions IMHO).

The original reproducer has 10_000 concurrent users, so it either needs a connection pool of size 10_000 (most likely a bad idea), or a connection pool _queue_ that can hold 10_000 queued requests. If I add this line to the configuration of the reproducer, everything works smoothly:

```properties
quarkus.redis.max-pool-waiting=10000
```

I will submit a PR to the Vert.x Redis client to expose the underlying exceptions properly, but that's all I can think of.

Well, maybe we should document the queuing mechanism, the Vert.x Redis client documentation mentions it briefly (https://vertx.io/docs/vertx-redis-client/java/#_connection_pooling), but it seems the Quarkus Redis client documentation doesn't mention it at all.

**Comment by Ladicek** [comment]
OK, suppressed exceptions don't work all that well, as they tend to produce huge stack traces. So I think I'll go with just expanding the error message to include all underlying error messages. In the Quarkus log, that will look like:

```
2023-11-22 12:52:54,676 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /cat-fact failed, error id: 4d97804c-4cd0-42fc-b175-42eec8800bbd-5308: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster
- io.vertx.core.http.ConnectionPoolTooBusyException: Connection pool reached max wait queue size of 24
```

That should be good enough, I guess.

**Comment by Ladicek** [comment]
PRs to Vert.x:

- https://github.com/vert-x3/vertx-redis-client/pull/419
- https://github.com/vert-x3/vertx-redis-client/pull/420

PR to Quarkus:

- https://github.com/quarkusio/quarkus/pull/37267

I can't see anything else we could do here.

**Comment by bartm-dvb** [comment]
Thanks for the help! @cescoffier @Ladicek @luneo7

**Comment by sfali16** [comment]
I think there is an issue with reconnects here, let me know if i should file a new issue:

// manual reproduction that consistently reproduces the failure to reconnect:
1. Start quarkus. Start Redis (docker compose up using the docker-compose file provided in this issue). Access http://localhost:8080/cat-fact
2. a) stop redis (docker compose down)
2. b) access cat-fact again -> see the following error in the quarkus log:
`2023-11-17 22:27:36,551 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /cat-fact failed, error id: 736e1d37-7d84-43fb-8e37-2d4d34f4eda6-11: io.vertx.core.impl.NoStackTraceThrowable: Cannot connect to any of the provided endpoints"
`
3. Start redis. Access cat-fact - see above error repeat over and over until quarkus is restarted. Note if 2(a) and (3) is done without 2(b) the error never occurs. 
 
My theory is that when all endpoints of the cluster are down, the slots / endpoints being saved are incorrect and getSlots is always called with index >= endpoints.size.
