### ISSUE TITLE
Narayana-jta getting reindexed, too old Jandex used

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3705]
Narayana-jta getting reindexed, too old Jandex version used

[WARNING] [io.quarkus.deployment.index.ApplicationArchiveBuildStep] Re-indexing /Users/rsvoboda/.m2/repository/org/jboss/narayana/jta/narayana-jta/5.9.6.Final/narayana-jta-5.9.6.Final.jar - at least Jandex 2.1 must be used to index an application dependency

@ochaloup can you bump Jandex version to 2.1+ ? https://github.com/jbosstm/narayana/blob/master/pom.xml#L433

**Comment by machi1990** [comment]
Dup of https://github.com/quarkusio/quarkus/issues/3705 ?

**Comment by rsvoboda** [comment]
ah, dup of #3678.
