### ISSUE TITLE
`Provider<MongoClient>` combined with `mongo+srv` schema and gRPC results in mutiny await block error

### ISSUE THREAD

**Issue by nahguam** [quarkusio/quarkus#37052]
### Describe the bug

If one injects a `Provider<MongoClient>` where the connection string is a `mongodb+srv://` scheme into a grpc service and the `get()` method is called within a grpc service call, it will be called within a `vert.x-eventloop-thread-` thread. During initialization, The `MongoDnsClient` will attempt a `resolveTxtRequest` with the mutiny api. This results in an error.

See:
- https://github.com/quarkusio/quarkus/blob/3.5.0/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/dns/MongoDnsClient.java#L175
- https://github.com/smallrye/smallrye-mutiny/blob/2.5.1/implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniBlockingAwait.java#L30

- https://github.com/quarkusio/quarkus/blob/3.5.0/extensions/mutiny/runtime/src/main/java/io/quarkus/mutiny/runtime/MutinyInfrastructure.java#L48

### Expected behavior

No exception is thrown. DNS is resolved successfully.

### Actual behavior

```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.quarkus.mongodb.runtime.dns.MongoDnsClient.resolveTxtRequest(MongoDnsClient.java:175)
```

### How to Reproduce?

Reproducer:

1. Create starter app - `quarkus create app --extensions=grpc,mongodb-client --code`
2. Inject `MongoClient` as per below.
3. Set an appropriate connection string - `quarkus.mongodb.connection-string=mongodb+srv://...`
4. Run the test `HelloGrpcServiceTest`.

```
package org.acme;

import com.mongodb.client.MongoClient;

import io.quarkus.grpc.GrpcService;

import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import jakarta.inject.Provider;

@GrpcService
public class HelloGrpcService implements HelloGrpc {

    @Inject Provider<MongoClient> client; // (1)

    @Override
    public Uni<HelloReply> sayHello(HelloRequest request) {
        client.get(); // (2)
        return Uni.createFrom().item("Hello " + request.getName() + "!")
                .map(msg -> HelloReply.newBuilder().setMessage(msg).build());
    }

}
```

### Output of `uname -a` or `ver`

Darwin <snip> 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

17

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by cescoffier** [comment]
Unfortunately the mongo spi is synchronous. Thus we have to resolve the dns address in a blocking fashion. I have an idea to 'fix' it (in the sense it won't throw), but I'm not very happy with it.

**Comment by nahguam** [comment]
I can't replicate it now either. Let's close this. I'll reopen if I see it happening again.
