### ISSUE TITLE
poi extension Build native image error

### ISSUE THREAD

**Issue by Sparkel-wsl** [quarkusio/quarkus#37061]
### Describe the bug

In my work, I needed to export data to excel, so I adopted quarkus-poi, and there were no errors during the test. When building a local executable, "Windows AWT integration is not ready in native images and Java" is thrown. Lang. UnsatisfiedLinkError: There is no awt in java.library.path.'. But I only want to use excel related functions in poi, not AWT related functions.

### Expected behavior

Expect the behavior to build successfully because I'm not going to use the awt functionality

### Actual behavior

Building a native executable throws:'Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.'

### How to Reproduce?

1:Import the poi extension
`
<dependency>
            <groupId>io.quarkiverse.poi</groupId>
            <artifactId>quarkus-poi</artifactId>
            <version>2.0.3</version>
        </dependency>
`
2:mvnw package -Dnative

### Output of `uname -a` or `ver`

Microsoft Windows [版本 10.0.19045.3570]

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: D:\apache-maven-3.9.2
Java version: 17.0.6, vendor: GraalVM Community, runtime: D:\graalvm-ce-java17-22.3.1
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

<dependency>
            <groupId>io.quarkiverse.poi</groupId>
            <artifactId>quarkus-poi</artifactId>
            <version>2.0.3</version>
        </dependency>

**Comment by zakkak** [comment]
Hello @Sparkel-wsl please open the issue in [quarkus-poi's repository](https://github.com/quarkiverse/quarkus-poi/issues).
