### ISSUE TITLE
DuplicatedContext gets mixed when caching the response of a rest call

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#37078]
### Describe the bug

when caching the `Uni` response of a rest call, the wrong duplicated context may be reused across multiple calls.

see the details in this [conversation](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/unexpected.20reuse.20of.20duplicated.20context).

Fixed by https://github.com/quarkusio/quarkus/pull/37077

### How to Reproduce?

see https://github.com/vsevel/reproducer_dupctxlocal

### Quarkus version or git rev

3.5.1

**Comment by sberyozkin** [comment]
Hi Vincent, I believe https://github.com/quarkusio/quarkus/pull/37077 has resolved it, thanks
