### ISSUE TITLE
Metrics - Add more base metrics

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#3709]
**Description**
Currently, base metrics uses the `java.lang.management.OperatingSystemMXBean` to retrieve it's base metrics. By switching to the `com.sun.management.OperatingSystemMXBean` we can access more metrics.

**Implementation ideas**
I have a work in progress prototype that cast the `OperatingSystemMXBean` to the internal one in the sun package and add some metrics if the cast is successful.

My prototype only adds systemCpuLoad and processCpuLoad as it's what I need but I can add others metrics available in this mxbean (committedVirtualMemorySize, totalSwapSpaceSize, FreeSwapSpaceSize, ProcessCpuTime, FreePhysicalMemorySize and TotalPhysicalMemorySize).

For the record, the `com.sun.management.OperatingSystemMXBean` is not working in native mode so these extended metrics are not added when building a native image (same as for memoryPoolMetrics)

Please tell me if this PR will be considered, in this case I will open it.

**Comment by jmartisk** [comment]
I think this makes sense. +1 that these new metrics should be in the `vendor` scope.

Thinking which of these metrics actually will be useful:
- systemCpuLoad,  processCpuLoad, ProcessCpuTime, FreePhysicalMemorySize, FreeSwapSpaceSize - yes
- committedVirtualMemorySize - maybe
- totalSwapSpaceSize, TotalPhysicalMemorySize - I'd say not much as these don't typically change during runtime

Also not sure whether swap size is applicable under Windows, it's named differently there, so it depends whether the mbean actually shows something useful there :) (in the other case we should just omit it)

**Comment by loicmathieu** [comment]
@jmartisk if I understand it correctly:

- **base** metrics are system level metrics (the Jaeger extension also provides base metrics, it feels strange I would assume that Jaeger should provides vendor metrics).
- **vendor** metrics are JVM level metrics: this is where the new metrics will land
- **application** metrics are the one we delcare on our application

As you suggest, I will add the missing _yes_ ones (ProcessCpuTime, FreePhysicalMemorySize, FreeSwapSpaceSize), we can add more later if we want.

A small note on the one you advise to not include, they can typicaly be used to compute a percentage of free space ...

**Comment by jmartisk** [comment]
Jaeger extension provides metrics in `base`? In that case please report an issue, that's definitely wrong.

Base metrics should be just the ones listed in the  [MP Metrics specification](https://github.com/eclipse/microprofile-metrics/blob/2.0.1/spec/src/main/asciidoc/required-metrics.adoc). `vendor` scope is for what we add on top of the spec, so this would include your metrics and the ones from Jaeger extension. `application` is for the ones declared in an application, yes.

I see you mentioned also `ProcessCpuLoad` and that is listed in the spec as an optional metric for the `base` scope, I didn't realize that. And Quarkus currently doesn't implement it AFAIK. So if you're going to add it then this one should indeed be in the `base` scope.

**Comment by loicmathieu** [comment]
@jmartisk OK, I will add this one to base and the other one to vendor. I will open a PR soon.

I will also open an issue for the Jager metrics.

**Comment by jmartisk** [comment]
@loicmathieu great, thanks! :)
