### ISSUE TITLE
Rest client able to get full SSE event

### ISSUE THREAD

**Issue by VanKuang** [quarkusio/quarkus#37107]
### Description

I add rest-client-reactive-jackson module to my repository and using Rest client to access a SSE endpoint.

The SSE endpoint is return different type of SSE event, distinguished by "event", however I can only get the "data" from the SSE event. (Looking at the implementation [here](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java#L168))

Here is the sudo code of my rest client
```
@Path("/v1")
@RegisterRestClient
class MyRestClient {
    @GET
    @Path("/sse")
    Multi<String> getData();
}
``` 

Is there any workaround that I can get the "event" of the SSE event?

### Implementation ideas

I think if the method is returning Multi<InboundSseEvent> in rest client/interface, MultiInvoker should just propagate it to downstream? to leave the decision making to the downstream which part of data it want.

**Comment by VanKuang** [comment]
您好！我已经收到您发的邮件了。

**Comment by VanKuang** [comment]
here is the example of our sse output:

event: heartbeat
data: xxxx

event: trade
data: {"key": "value"}

heartbeat event is just to keep the connection alive, so in the client side, we just need to ignore the heartbeat event.

**Comment by geoand** [comment]
Okay I see, thanks

**Comment by VanKuang** [comment]
> Okay I see, thanks

does it make sense to propagate InboundSseEvent to downstream? Can we create a PR for it?

**Comment by geoand** [comment]
> does it make sense to propagate InboundSseEvent to downstream

I don't think so really, because it has methods that are not usable in an obvious way by consumers

**Comment by VanKuang** [comment]
> > does it make sense to propagate InboundSseEvent to downstream
> 
> I don't think so really, because it has methods that are not usable in an obvious way by consumers

Which methods you means explicitly?
Base on the doc. for [InboundSseEvent](https://github.com/javaee/jax-rs-api/blob/master/jaxrs-api/src/main/java/javax/ws/rs/sse/InboundSseEvent.java), it suppose to be use in the client side.

```
/**
 * Inbound Server-sent event.
 * <p>
 * Used on the client side, when accepting incoming Server-sent events.
 *
 * @author Marek Potociar
 * @since 2.1
 */
public interface InboundSseEvent extends SseEvent {
```

**Comment by geoand** [comment]
The `readData` methods don't make much sense

**Comment by VanKuang** [comment]
> The `readData` methods don't make much sense for a consumer

hmm, then how about wrap it into another POJO object that including id/name/comment/data/etc. and push it to downstream?

**Comment by geoand** [comment]
I need to think about it

**Comment by geoand** [comment]
The way I believe this should be done is to introduce a new type - I am just going to call it `SseEvent` for now. 
Here is what it would look like:

```java
public interface SseEvent<T> {

    String id();

    String event();

    String comment();

    T data();
}
```

Users would just use this type like so:

```java
@Path("/v1")
@RegisterRestClient
class MyRestClient {
    @GET
    @Path("/sse")
    Multi<SseEvent<String>> get();
}
```

I have not implemented it, but I think it's exactly what is needed. Hopefully I'll have some time tomorrow to look into it.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/37241 takes care of this
