### ISSUE TITLE
[Extension Proposal] Zombie detector - quarkus-business-score

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#37138]
### Description

So after reading @holly-cummins's blog [The necessary death of software systems](https://hollycummins.com/death-and-software/) I realized that Quarkus might offer a more convenient way of detecting application "zombies", i.e. applications that live/communicate but **do not produce any business value**. 

When I say "business value" I mean anything that helps to solve a problem of an application user, i.e. anything the app was build for. For example storing orders, serving content or performing computational tasks. Infrastructure stuff (logs, stats, metrics, health checks) usually does not produce a business value.

### Why not use existing extensions?

There are two extensions that seem appropriate for this task. [quarkus-smallrye-health](https://quarkus.io/guides/smallrye-health) and [quarkus-micrometer](https://quarkus.io/guides/telemetry-micrometer). The problem with `quarkus-smallrye-health` is that an application health does not necessary say anything about the business value. In other words, an application could be in excellent condition but totally useless and just consuming resources. You could define a custom health check and maintain the "business value" data in the app but that's not very convenient. `quarkus-micrometer` on the other hand is IMO too generic. The truth is that [`DistributionSummary`](https://quarkus.io/guides/telemetry-micrometer#summaries-and-timers) is almost a perfect match but it lacks a simple and intuitive API.

### The concepts

In a nutshell, the extension will manage the **business score** which is a numeric representation of the business value. Application will emit score records (increase the business score), either directly via the API or with an interceptor binding. The sum of all score records in the current time window is the **current business score**. The records are only kept for the specific amount of time - **time window**. The app defines the point at which the application is considered a zombie - **zombie threshold**. An external system or the application itself can periodically check the business score and react appropriately.

### API and usage

This extension will introduce a `BusinessScore` API like:

```java
interface BusinessScore {

    void score(int value, String... labels);
    void reset();

    // the sum of all score records in the current time window
    long getCurrentScore();

    // the point at which the application is considered a zombie, configurable 
    long getZombieThreshold();
    default boolean isZombie() {
        return getCurrentScore() < getZombieThreshold();
    }

    // the amount of time a score record is kept alive, configurable
    Duration getTimeWindow();

    List<ScoreRecord> getRecords();

    interface ScoreRecord {
        int value();
        long timestamp();
        Set<String> labels();
    }
}

```
An app could `@Inject  BusinessScore` like any other bean and increase/query the score direcly.

This extension would introduce a `@Scored` interceptor binding that could be used like:

```java
class MyService {
   
    @Scored // increate the business core by 1
    void storeOrder() {
      // ... 
    }
}
```

### Management endpoint

A management endpoint is registered automatically. HTTP GET `/q/business-score` would return something like:
```json
{
    "serverTime": "2023-11-16T09:30:19.690771661",
    "application": {
        "name": "my-app",
        "version": "1.0"
    },
    "score": 1,
    "zombieThreshold": 10,
    "timeWindow": "PT168H"
}
```

### Detecting zombies

An external system could query the mgmt endpoint. But even the app itself could be more proactive and e.g. register a scheduled method like this:
```java
class ZombieDetector {

    @Inject
    BusinessScore businessScore;

    @Scheduled(cron = "0 15 10 * * ?")
    void detect() {
       if (businessScore.isZombie()) {
          // send a notification...
       }
    }
}

```

### Repository name

quarkus-business-score

### Short description

Collects application business score and detects zombies.

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-business-score/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

-

**Comment by holly-cummins** [comment]
This is a cool idea! If we do this, I have a logo.

<img width="1250" alt="image" src="https://github.com/quarkusio/quarkus/assets/11509290/b1878bba-e4e7-4cd5-9b20-b47949ec0262">

Although maybe it needs to be in a suit, to fit better with the "business score" idea. :)

I wonder if there's anything we could do to make filling in the `// send a notification` part easier? Actually doing something useful with the information might be where the gap ends up being. If alerts go into the bin, we're in a similar situation to where we are now. Although "help! I'm a zombie!" alerts would be cute. :)

These are all much bigger lifts, but input to auto-scaling tooling is one option, or some kind of special zombie status in Backstage. Or ... ? Anything like that would probably be outside this extension, but just a potential integration to think about.

**Comment by gastaldi** [comment]
That's an interesting idea, any prototypes around?

**Comment by mkouba** [comment]
> That's an interesting idea, any prototypes around?

I prototyped something locally but I can create a public repo if you want ;-)

**Comment by gsmet** [comment]
Interesting idea. Is it something for which an email notification is a good idea or would you expect some sort of dashboard with the business value over time?

An example: you have an app that is very useful at a certain time and not useful at another time (say tax reporting for instance). Knowing that it is very useful at a point in time is probably an information you need to have before deciding it's a zombie? Especially since it  might define the strategy you will use to solve the problem.

**Comment by mkouba** [comment]
> Interesting idea. Is it something for which an email notification is a good idea or would you expect some sort of dashboard with the business value over time?

So I was thinking that this should be pluggable. The information should be available from inside the app (`@Inject BusinessScore` etc.) and from outside the app (built-in management endpoint, websocket endpoint, etc.). An email notification would be one of the ways to notify the admin. But I can imagine an external dashboard as well.

**Comment by maxandersen** [comment]
Like the idea but not sure if you really wanna (as an devops user) to have this score separate from other metrics? Is this more a pattern than a "separate" thing? 

i.e. shouldn't this businessScore just be re-exported into metrics (as least as an option) so all the need for visualization/notifications etc.  can be handled using existing infrastructure?

but +1 on having extension making it easier to implement this pattern.

**Comment by gastaldi** [comment]
https://github.com/quarkiverse/quarkus-business-score is now created. Enjoy!

**Comment by mkouba** [comment]
> https://github.com/quarkiverse/quarkus-business-score is now created. Enjoy!

Ah ok, thanks. I did not expect the Spanish Inquisition after half a year. But yes, I can push something soon ;-).

**Comment by mkouba** [comment]
For the record - the repo already contains some initial content.
