### ISSUE TITLE
Kafka broker readiness check should not be used for applications readiness check ideally

### ISSUE THREAD

**Issue by nithinbandaru1** [quarkusio/quarkus#37157]
### Description

This is just my understanding of different health checks, please correct if I am wrong here.

#### Documentation

https://quarkus.io/guides/kafka#kafka-broker-readiness-check

#### Why?

By health check definitions it does not fall under application readiness.

#### Startup Check

Kafka broker readiness check can be done here as generally a little bit time is needed for Kafka Broker to start.

#### Liveness Check

Indicate that the service is up and running. It shall not indicate whether all dependencies are running or current load on the service.

Should set it to fail only when we expect all to be fine if we restart pod.

So, this is not a suitable location for this Kafka broker readiness check.

#### Readiness Check

Indicate if the application is ready for receiving requests and this is activated after the startup check is passing.

This is not Kafka Server (Broker) and it is Kafka client, so Readiness does not feel like a suitable place for it.

Will return 404 if none of the replica is ready. It is used mostly for load balancing.

So, this is not a suitable location for this Kafka broker readiness check.

It looks like `Kafka reactive messaging health checks` https://quarkus.io/guides/kafka#kafka-reactive-messaging-health-checks follows the definitions correctly for Startup and Liveness check at-least and conflicts with readiness check.

If suppose I have like 100 services one dependent of other and the last one is Kafka. If Kafka is not ready, then I see that all services are in not ready state which makes it very difficult to see which service actually has the issue.

**Comment by cescoffier** [comment]
Very late response - but yes, your understanding was correct (better use discussions for this kind of question)
