### ISSUE TITLE
Default ExceptionMapper for Jackson's MismatchedInputException should log errors

### ISSUE THREAD

**Issue by allertonm** [quarkusio/quarkus#37167]
### Describe the bug

`resteasy-reactive-jackson` provides an ExceptionMapper for Jackson's MismatchedInputException, which causes the request to return `400`. This behaviour makes sense when Jackson is being used to unmarshal a request payload, but not so much if Jackson is being used elsewhere during the request (for example, in a JPA ArtifactConverter implementation) especially because this mapper logs nothing about the exception.

Due to the JAX-RS specified ExceptionMapper behaviour, unless you already know this mapper exists and override it specifically, many important errors will not be logged, and will return 400 when 500 should be returned.

At a minimum this mapper should log the errors (at "error" level.) It would also be good if through documentation or some other means it was possible for developers to have some visibility of the pre-defined mappers and their expected behaviour.

related issue re ExceptionMapperOrdering here https://github.com/quarkusio/quarkus/issues/34579
I chose to create a new issue for this mapper specifically because the default behaviour is IMO dangerous.

### Expected behavior

When MismatchedInputException is thrown, an error is logged.

### Actual behavior

When MismatchedInputException is thrown, no error is logged.

### How to Reproduce?

In a resource method, throw an `InvalidTypeException`

### Output of `uname -a` or `ver`

Darwin M-L10KJGH6 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 LTS OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)

### Quarkus version or git rev

3.2.4.Final

**Comment by geoand** [comment]
> or some other means it was possible for developers to have some visibility of the pre-defined mappers and their expected behaviour

Actually, the Dev UI does give you visibility into this.

> It would also be good if through documentation 

I'm always open to people making improvements in the docs based on their real world experience.

**Comment by geoand** [comment]
Closing for lack of feedback
