### ISSUE TITLE
Ambiguous dependencies for type java.util.concurrent.ExecutorService and qualifiers [@Default] when using SmallRye Context Propagation

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#3717]
**Describe the bug**
Having a bean injecting an ExecutorService `@Inject ExecutorService executorService`, an Ambiguous dependencies error is thrown:
```
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type java.util.concurrent.ExecutorService and qualifiers [@Default]
[ERROR] 	- java member: org.acme.quickstart.GreetingResource#executorService
[ERROR] 	- declared on CLASS bean [types=[org.acme.quickstart.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.quickstart.GreetingResource]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[io.netty.channel.EventLoopGroup, java.util.concurrent.Executor, java.util.concurrent.ExecutorService, java.lang.Iterable<io.netty.util.concurrent.EventExecutor>, java.lang.Object, io.netty.util.concurrent.EventExecutorGroup, java.util.concurrent.ScheduledExecutorService], qualifiers=[@Default, @Any], target=io.netty.channel.EventLoopGroup produce_io_netty_channel_EventLoopGroup_bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f(), declaringBean=io.quarkus.arc.runtimebean.RuntimeBeanProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.util.concurrent.Executor, org.eclipse.microprofile.context.ManagedExecutor, java.util.concurrent.ExecutorService, java.lang.Object], qualifiers=[@Default, @Any], target=org.eclipse.microprofile.context.ManagedExecutor getAllManagedExecutor(), declaringBean=io.quarkus.smallrye.context.runtime.SmallRyeContextPropagationProvider]
```
**Expected behavior**
The ExecutorService produced by the Context Propagation extension is used (it works in 0.21.1)

**Actual behavior**
The build fails with the stacktrace above

**To Reproduce**
1. `mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" -Dextensions="context-propagation"` 
2. Add a `@Inject ExecutorService executorService` in the `GreetingResource` class
3. `mvn clean package -DskipTests`

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ggastald-laptop 5.2.9-200.fc30.x86_64 #1 SMP Fri Aug 16 21:37:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 999-SNAPSHOT (master)

**Additional context**
Does not happen in 0.21.1

**Comment by mkouba** [comment]
There are evidently two beans that satisfy an injection point of `ExecutorService`. The first comes from SM context propagation - see `SmallRyeContextPropagationProvider` and the other one is registered by `io.quarkus.netty.deployment.NettyProcessor.createExecutors()`. And Netty is probably included because Undertow runs on top of Vertx now.

**Comment by FroMage** [comment]
Thanks @stuartwdouglas for the fix. I wonder if I should not use the `@Type` annotation to limit the injectable type to `ManagedExecutor` instead of also its supertype `ExecutorService`, in the case of MP-CP.

**Comment by mkouba** [comment]
> I wonder if I should not use the @Type annotation to limit the injectable type to ManagedExecutor instead of also its supertype ExecutorService, in the case of MP-CP.

Sounds reasonable.

**Comment by FroMage** [comment]
OK: #3729
