### ISSUE TITLE
Kafka transactional sending API behave in an unexpected way

### ISSUE THREAD

**Issue by krisztiankocsis** [quarkusio/quarkus#37172]
### Describe the bug

We are sending multiple Kafka messages within a Kafka transaction and use the code below to make in synchronous, because we have to know in that location of the code that the message is both accepted. I expected that waiting on the Uni indefinitely do this, and throws if something is not okay.

This is injected:
KafkaTransactions<MyDataRecord> messageProducer;

    private void sendMessages(
        @NotNull final ImmutableList<
            Map.Entry<MyDataRecord, MyCompletionRecord>> simulationChunks) {
        messageProducer.withTransaction(emitter -> {
                simulationChunks
                    .stream()
                    .map(Map.Entry::getKey)
                    .forEach(emitter::send);

                return Uni
                    .createFrom()
                    .voidItem();
            })
            .await()
            .indefinitely();
    }

One example is, if the message is too big, I'll later get a log message from Kafka:
The message is 95645096 bytes when serialized which is larger than 83886080, which is the value of the max.request.size configuration.

I want to be able to catch that errors here in the code, or need an other way to catch such errors in a way that I can identify the transaction - because I have to mark the related entity as "Failed to send".

Quarkus version: 3.4.3

### Expected behavior

Uni.await().indefinitely() returns only if the message is already sent.

### Actual behavior

Seem to return when the message is only enqueue inside Kafka.

### Output of `java -version`

17

**Comment by ozangunalp** [comment]
Sorry for my late response. 
This was indeed fixed on the upstream Reactive Messaging, and will be included in the next release (3.7) of Quarkus.

**Comment by cescoffier** [comment]
@ozangunalp According to your last comment, we should close this issue. Do you agree?

**Comment by ozangunalp** [comment]
Yes, let's close this. We had a second iteration of improvements to Kafka transactions since.
