### ISSUE TITLE
Support @RolesAllowed values populated to openapi schema now that 3.1.0 spec supports it

### ISSUE THREAD

**Issue by vickymicky** [quarkusio/quarkus#37199]
### Description

**Issue**:

`@RolesAllowed` annotation values are not populated to openapi schema.yaml, As a workaround, If I add 
`@SecurityRequirement(name = "BearerJWTScheme", scopes = { "roleA", "roleB" }) `I see it populated properly but it doesnt get picked automatically even with [quarkus.smallrye-openapi.auto-add-security-requirement](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.auto-add-security-requirement) property configured to true.

**Observation:**

On further analysis, I see it was allowed only for "oauth2" or "openIdConnect" security scheme due to the fact, it was not supported for other security schemes till open api 3.0.x version, as outlined in this issue, https://github.com/quarkusio/quarkus/issues/27373

**Expectation:**

Support Open API spec [3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#security-requirement-object)

As explained in spec,

Each name MUST correspond to a security scheme which is declared in the [Security Schemes](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#componentsSecuritySchemes) under the [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#componentsObject). If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution, and the list MAY be empty if authorization does not require a specified scope. For other security scheme types, the array MAY contain a list of role names which are required for the execution, but are not otherwise defined or exchanged in-band.

Sample on how it would like in [openapi spec](https://github.com/OAI/OpenAPI-Specification/pull/2515/files)

```
openapi: 3.1.0
info:
  title: Non-oAuth Scopes example
  version: 1.0.0
paths:
  /users:
    get:
      security:
        - bearerAuth:
            - 'read:users'
            - 'public'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
      description: 'note: non-oauth scopes are not defined at the securityScheme level'
```

### Implementation ideas

**Solution:**

I would like to raise a PR to fix this by removing the condition here, https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/filter/AutoRolesAllowedFilter.java#L114

Since the open api version is configurable via [quarkus.smallrye-openapi.open-api-version](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.open-api-version).

But it might affect the users who are not migrated to new open api version and they might get undesired schema output.

To fix this properly, I see two options,
1. We could check against the configured open api version and disable the condition but not sure whether quarkus team wants to maintain code to support multiple versions or 
2. Wait for [smallrye-openapi to start supporting 3.1.0 by default](https://github.com/smallrye/smallrye-open-api/blob/main/core/src/main/java/io/smallrye/openapi/api/constants/OpenApiConstants.java#L119) via issue mentioned on [microprofile-openapi](https://github.com/eclipse/microprofile-open-api/issues/333).

Looking for direction from Quarkus team on how to proceed on this ?

**Comment by sultansoy** [comment]
guys, any updates here? @EricWittmann @MikeEdgar @phillip-kruger ?

**Comment by MikeEdgar** [comment]
OAS 3.1.0 support will be coming with MicroProfile OpenAPI 4.0, which should be released shortly. We can look at supporting this functionality when updating Quarkus to use smallrye-open-api 4.0 (which has not yet been released either).

**Comment by michalvavrik** [comment]
> OAS 3.1.0 support will be coming with MicroProfile OpenAPI 4.0, which should be released shortly. We can look at supporting this functionality when updating Quarkus to use smallrye-open-api 4.0 (which has not yet been released either).

@MikeEdgar I know OpenAPI 4.0 is here already, I'd like to help with this one (if not done already?). Can you give me some very high level directions where I can set collected roles (that one I can do :-)) to OpenAPI?

**Comment by MikeEdgar** [comment]
@michalvavrik , I think you will want to change the `orElse` condition here [1] to check that the `openAPI.getOpenapi()` is greater than or equal to `"3.1.0"`. Or perhaps make that check the primary one, and "or else" check the security scheme type, which is the more complicated check.


[1] https://github.com/quarkusio/quarkus/blob/0782ecc2b63b0dc4cae1f0176cd9f2c12e243da1/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/filter/OperationFilter.java#L64-L67

**Comment by michalvavrik** [comment]
Thank you @MikeEdgar

**Comment by michalvavrik** [comment]
In my tests, the `org.eclipse.microprofile.openapi.models.OpenAPI#getOpenapi` value returned wrong value in the `io.quarkus.smallrye.openapi.deployment.filter.OperationFilter#filterOpenAPI` method. I think it is updated later, because generated scheme contains correct OpenAPI version. I simply used OpenAPI version from config inside that filter. See https://github.com/quarkusio/quarkus/pull/44407.
