### ISSUE TITLE
Support arguments passed to application after -jar 

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#372]
Add support for interpretation of arguments passed to the application after -jar.

For instance,
`java -jar target/protean-test-runner.jar -Dshamrock.http.port=8180` 
should work.

Please note that
`java -Dshamrock.http.port=8180 -jar target/protean-test-runner.jar`
works now.

**Comment by gastaldi** [comment]
You can inject the arguments using `@Inject @CommandLineArguments List<String> arguments`. Closing
