### ISSUE TITLE
Keycloak-admin-client resteasy troubles

### ISSUE THREAD

**Issue by Chris2301** [quarkusio/quarkus#37203]
### Describe the bug

Hi, 

I am trying to set up a keycloak configuration application with the following pom and a simple main app. But it fails with:

`Exception in thread "main" jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: jakarta.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: jakarta.ws.rs.core.Form$1`

I simple run `mvn clean package`  & `java -jar java-configuration.jar`

```
    public static void main(String[] args) {
        try {
            KeycloakClientBuilder keycloakClientBuilder = KeycloakClientBuilder.create(
                    "http://localhost:8080",
                    "admin",
                    "admin",
                    "master");
            Keycloak keycloak = keycloakClientBuilder.getClient();

            KeycloakConfiguration keycloakConfig = new KeycloakConfiguration(keycloak);
            keycloakConfig.configure();
        } catch (Exception all) {
            Logger.getLogger(KeycloakConfigurationApplication.class).error("Exception occurred.", all);
            throw all;
        }
    }
```

`<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>config.keycloak</groupId>
        <artifactId>keycloak-config-tryout</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>java-configuration</artifactId>

    <properties>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <resteasy.version>6.2.6.Final</resteasy.version>
        <keycloak.version>22.0.5</keycloak.version>
        <maven.jar.plugin.version>3.3.0</maven.jar.plugin.version>
        <lombok.version>1.18.26</lombok.version>

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-admin-client</artifactId>
            <version>${keycloak.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>${resteasy.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <version>${resteasy.version}</version>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-core</artifactId>
            <version>${keycloak.version}</version>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-services</artifactId>
            <version>${keycloak.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven.jar.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>config.keycloak.KeycloakConfigurationApplication</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/javax.ws.rs.ext.Providers</resource>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <outputFile>${project.build.directory}/${project.artifactId}.jar</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
`

### Expected behavior

Running and executing Rest calls to the running keycloak instance

### Actual behavior

`Exception in thread "main" jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: jakarta.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: jakarta.ws.rs.core.Form$1`

### Output of `java -version`

openjdk 17.0.9 2023-10-17 LTS

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by sberyozkin** [comment]
My guess is it is the first time a code such as 
```
KeycloakConfiguration keycloakConfig = new KeycloakConfiguration(keycloak);
keycloakConfig.configure();
```

has been tried, and it does not use JSON but the form url encoded payloads. So, probably the form provider should be registered too, CC @michalvavrik (please have a look after other issues you may be looking at right now)

**Comment by Chris2301** [comment]
I had it with the quarkus-keycloak-admin-client too, but honestly I have been hustling so many dependencies that I tried to post an example as vanilla as possible. As I interpret it, in almost all cases quarkus-keycloak-admin-client is used together with code of the quarkus-keycloak-admin-client.

E.g. if you look in the quarkus [guide](https://quarkus.io/guides/security-keycloak-admin-client) you would have the same problem with the quarkus-keycloak-admin-client in that @PostConstruct

However I concur it might be 'more' of a keycloak issue

Thanks already for pointing out it could be a registering issue.

**Comment by sberyozkin** [comment]
@Chris2301 Np, if you could have a reproducer, with only the relevant quarkus dependencies then it could help tracing it further

**Comment by sberyozkin** [comment]
@Chris2301 Let me close it now, you are welcome to reopen it if you'd like, please create a reproducer if you can
