### ISSUE TITLE
Resteasy-reactive Partial Content support (Range: bytes http header)

### ISSUE THREAD

**Issue by Maldivia** [quarkusio/quarkus#37205]
### Describe the bug

File download continuation does not work with `quarkus-resteasy-reactive` as it works with `quarkus-resteasy`.

### Expected behavior

That `quarkus-resteasy-reactive` would work the same as `quarkus-resteasy`, returning a "206  Partial Content", with the appropriate headers for continuing the download. 

### Actual behavior

`quarkus-resteasy-reactive` returns a 200.

### How to Reproduce?

Given the following test class:
```java
package org.acme.test;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Response;

import java.io.File;

@Path("/file")
public class FileResource {
  static final String PATH = "/some/path/to/large-file";

  @GET
  public Response getFile() {
    return Response.ok(new File(PATH)).build();
  }
}
```

Running: `curl -v -O -C - http://localhost:8080/file`

With `quarkus-resteasy`:
```text
* Connected to localhost (127.0.0.1) port 8080
> GET /file HTTP/1.1
> Host: localhost:8080
> Range: bytes=187170812-
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Length: 7872772309
< Content-Range: bytes 187170812-8059943120/8059943121
< Content-Type: application/octet-stream
<
```

But with `quarkus-resteasy-reactive`
```text
* Connected to localhost (127.0.0.1) port 8080
> GET /file HTTP/1.1
> Host: localhost:8080
> Range: bytes=187170812-
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< content-length: 8059943121
<
* HTTP server doesn't seem to support byte ranges. Cannot resume.
```

### Quarkus version or git rev

3.5.2

**Comment by Maldivia** [comment]
Related, but don't really know if this is a bug report here or somewhere else, but noticed when I was looking at the above PR.
 
In the docs (https://quarkus.io/guides/resteasy-reactive#returning-a-response-body) java.nio.file.Path is listed as an accepted type as well, but based on the source code, Path.toFile() is called, meaning this will only work if the Path points to a physical file on disk, meaning cannot work with other FileSystems, such as Zip FS. I guess a clarification in the docs would help here?

**Comment by geoand** [comment]
> I guess a clarification in the docs would help here?

Feel free to open a PR with this clarification
