### ISSUE TITLE
Arc - client proxy should delegate toString() to contextual instance

### ISSUE THREAD

**Issue by manovotn** [quarkusio/quarkus#3722]
According to CDI spec, methods on proxies inherited from `Object` are undefined except for `toString()`. See [this](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#client_proxy_invocation) chapter. In combination with chapter 5.4 this indirectly requires `toString()` to be delegated to contextual instances.

ATM Arc doesn't do that (in comparison, Weld does).

@mkouba @jmartisk FYI

**Comment by jmartisk** [comment]
Aha, I thought this was some kind of intentional optimization :) We already merged the workaround in Metrics TCK for Metrics 2.1, but if this gets fixed in Quarkus, we might just drop the backport to Metrics 2.0.

**Comment by manovotn** [comment]
> Aha, I thought this was some kind of intentional optimization :) 

It's not a bug, it's a feature! ;-)
