### ISSUE TITLE
Version check interprets port as version number for image-name of dev-services

### ISSUE THREAD

**Issue by bannert1337** [quarkusio/quarkus#37227]
### Describe the bug

The company uses its own registry. Several registries are provided under different ports, which is why the port must be specified. 
If a port with a colon is specified in the image name, the port is interpreted as a version number and a version mismatch occurs.
To validate the version number, Quarkus uses [Testcontainers](https://github.com/testcontainers/testcontainers-java).
The image name is split at the first colon, and the second substring is interpreted as the version number.
```
public DockerImageName(String fullImageName) {
        this.rawName = fullImageName;
        final int slashIndex = fullImageName.indexOf('/');

        String remoteName;
        if (
            slashIndex == -1 ||
            (
                !fullImageName.substring(0, slashIndex).contains(".") &&
                !fullImageName.substring(0, slashIndex).contains(":") &&
                !fullImageName.substring(0, slashIndex).equals("localhost")
            )
        ) {
            registry = "";
            remoteName = fullImageName;
        } else {
            registry = fullImageName.substring(0, slashIndex);
            remoteName = fullImageName.substring(slashIndex + 1);
        }

        if (remoteName.contains("@sha256:")) {
            repository = remoteName.split("@sha256:")[0];
            versioning = new Sha256Versioning(remoteName.split("@sha256:")[1]);
        } else if (remoteName.contains(":")) {
            repository = remoteName.split(":")[0];
            versioning = new TagVersioning(remoteName.split(":")[1]);
        } else {
            repository = remoteName;
            versioning = Versioning.ANY;
        }

        compatibleSubstituteFor = null;
    }

```
[Source](https://github.com/testcontainers/testcontainers-java/blob/696481e3dd345b9cc313dcc36c3553ab18562cd7/core/src/main/java/org/testcontainers/utility/DockerImageName.java#L92)

### Expected behavior

Version number is correctly identified.

### Actual behavior

The version number is wrongly identified, causing a version mismatch error.

### How to Reproduce?

Use a registry with port in the image name.

**Comment by melloware** [comment]
But isn't this a bug in TestContainers? Your source link is to TestContainers?

**Comment by geoand** [comment]
Closing as per @melloware 's comment
