### ISSUE TITLE
Compilation failure quarkus extension when having a converter applied to java Map values with interface type

### ISSUE THREAD

**Issue by taba90** [quarkusio/quarkus#37230]
### Describe the bug

Custom Quarkus Extension with a ConfigMapping  interface where I've defined the following configuration mapping:

`Map<String, @WithConverter(MyInterfaceConverter.class) MyInterface> myconfigvalues();`

Fails at compilation time with the following error:

> java: java.lang.ClassCastException: class com.sun.tools.javac.code.Type$ArrayType cannot be cast to class javax.lang.model.type.DeclaredType (com.sun.tools.javac.code.Type$ArrayType is in module jdk.compiler of loader 'app'; javax.lang.model.type.DeclaredType is in module java.compiler of loader 'platform')

If I replace the value type with a subclass of the interface it works eg:

`Map<String, @WithConverter(MyInterfaceConverter.class) MyInterfaceImpl> myconfigvalues();`

Exception is raised [at this line of the Config DocItemFinder](https://github.com/quarkusio/quarkus/blob/3.5.2/core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/ConfigDocItemFinder.java#L278).

Java version is 17.0.6. Quarkus version 3.5.2.

### Expected behavior

The quarkus extension succesfully compile and build.

### Actual behavior

The extension doesn't compile if the value type of the mapped java Map is an interface.

### How to Reproduce?

Steps to reproduce the behaviour:

1. In quarkus extension define an interface for some configuration properties and a smallrye  config converter for it.
2.  Define a Config mapping like this:

`   @ConfigMapping(prefix = "quarkus.prefix")
    @ConfigRoot(phase = ConfigPhase.RUN_TIME)
    public interface MyConfig {
    Map<String,@WithConverter("MyInterfaceConverter")MyInterface> someProperties();
    }
`
3. The extension fails at compilation time.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.5

### Additional information

Replacing the map value type with a subclass of the interface the compilation is successful.

**Comment by taba90** [comment]
Forgot to add the example project. Please find it below. `mvn clean install` will fail at compilation time with above error.
[greeting-extension.zip](https://github.com/quarkusio/quarkus/files/13418911/greeting-extension.zip)

**Comment by radcortez** [comment]
The `@WithConverter` and the `Converter` API, in general, require a concrete class, so there is no support for interfaces.

May I ask what is the use case here? We could make this work, but only when a single implementation is available. From my experience, I never got a use case that required multiple implementations of a converter for the same type. This would also require some sort of mechanism to select the proper concrete class.

**Comment by taba90** [comment]
Thanks for your answer @radcortez .
My use case is to have a bunch of property where part of the property name is varying with a value that is some kind of function/expression written using a "custom language" eg.
`
my.property.with.varyingname=strConcat('someString','some other string')
`
That string is parsed and the converted to an object of type `Function` where concrete classes might be `StrConcat`,'StrReplace'.
All this to provide some configurable way to remap some http request paths.
Anyway I'm now using abstract classes for the maps' values type and altough not ideal I'm fine with it.

**Comment by radcortez** [comment]
Ok, great. I am closing this then.
