### ISSUE TITLE
[Extension Proposal] code-server to embed "vscode" in dev ui

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#37245]
### Description

extension which enables to use code-server from quarkus devui.

![2023-11-21_10-11-27](https://github.com/quarkusio/quarkus/assets/54129/59dfa52c-7c6c-4412-ad52-1e5588d3cb1a)

Very much experimental for now as has bunch of issues but as the code turned out to be super trivial I thought - why not :)

### Repository name

quarkus-code-server

### Short description

allow to have access to code-server from dev ui

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-code-server/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- maxandersen

### Additional context

prototype at https://github.com/maxandersen/quarkus-code-server

**Comment by maxandersen** [comment]
Finding that quay.io/che-incubator/che-code exist - wonder if should make that an option to run.

**Comment by geoand** [comment]
Super cool!

**Comment by phillip-kruger** [comment]
Maybe this should be in the menu rather than the card? Or at least both?

**Comment by phillip-kruger** [comment]
We can also change the "open in IDE" feature to check if this extension is included, we open here ?

**Comment by maxandersen** [comment]
> Maybe this should be in the menu rather than the card? Or at least both?

Sure. What's the magic to add to the side?

**Comment by maxandersen** [comment]
> We can also change the "open in IDE" feature to check if this extension is included, we open here ?

That would be nice but unfortunately opening individual files does not currently work :/ https://github.com/coder/code-server/issues/1964#issuecomment-1714442281

...but let's say we do find a way around that...the current open in ide is currently not extendible by other extensions ... but yes would be great if it could.

**Comment by HerrDerb** [comment]
Loving it 🙂👍

**Comment by ArthurGB80** [comment]
Very good idea!!! I want it!
