### ISSUE TITLE
Incorrect path to run dockerfile.jvm

### ISSUE THREAD

**Issue by davids13** [quarkusio/quarkus#37255]
### Describe the bug

In dockerfile.jvm is saying to this:

```
# Then, build the image with:
# docker build -f src/docker/Dockerfile.jvm -t quarkus/<project> .
```

### Expected behavior

It should be with this path:

`# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/<project> .`

### How to Reproduce?

Just run:
docker build -f src/docker/Dockerfile.jvm -t quarkus/project .

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment Homebrew (build 21.0.1) OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 2.16.8.Final

**Comment by geoand** [comment]
Good catch! Would you like to contribute the fix?

**Comment by davids13** [comment]
Yes, definitely I want to contribute.

**Comment by geoand** [comment]
💪🏼

**Comment by davids13** [comment]
I've verified this issue already was fixed.
