### ISSUE TITLE
Environment variable is not read

### ISSUE THREAD

**Issue by vpaiva** [quarkusio/quarkus#37273]
### Describe the bug

When declaring an expression, it is not retrieved via Environment in native mode. 
I've been using this way since version 1.5 of quarkus.

### Expected behavior

I want my application to recognize the env property.

### How to Reproduce?

I declare the configuration in application.yaml:

quarkus:
  consul-config:
    agent:
      host-port: "${consul.host:localhost}:8500"
      
I do one export CONSUL_HOST=192.168.1.5

### Output of `java -version`

17.0.9

### Mandrel or GraalVM version (if different from Java)

mandrel

### Quarkus version or git rev

3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.4

**Comment by zakkak** [comment]
Reminds me of https://github.com/quarkusio/quarkus/issues/33321

@vpaiva can you please provide a reproducer, e.g. a gradle project including a test that fails?

**Comment by vpaiva** [comment]
@zakkak Bug reproduction follows:

https://github.com/vpaiva/quarkus-env-reproducer-gradle

**Comment by vpaiva** [comment]
@aloubyansky Is there anything you can do as an alternative to this problem? This is making it impossible to update quarkus services.

**Comment by gsmet** [comment]
Also ping @radcortez

**Comment by vpaiva** [comment]
@radcortez Is there anything you can do as an alternative to this problem? This is making it impossible to update quarkus services.

**Comment by radcortez** [comment]
You can use the actual property name instead of the expression. For instance, for the reproducer, `export QUARKUS_BANNER_ENABLED=true` works as expected.

**Comment by vpaiva** [comment]
It really works. Thanks @radcortez!

**Comment by vpaiva** [comment]
@radcortez  Is there a way to prioritize this bug?
We use many variables that are loaded via external services.
