### ISSUE TITLE
Gradle Plugin Builds started to fail on Java 11/17 and Gradle 8.3

### ISSUE THREAD

**Issue by Xnyle** [quarkusio/quarkus#37296]
### Describe the bug

For atm unknown reasons all our builds using the Gradle Plugin (in any used version up to 3.6.0.CR) fail with:
Unsupported class file major version 65
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file .gradle/caches/jars-9/29a26170a4fefd5316fa39bfac1c4ff4/h2-2.2.224.jar.

H2DB is not used by our projects, so this is a plugin only dependency.

We can temporarily fix the builds by adding the following to the gradle buildscript.dependencies block:

classpath('com.h2database:h2') {
				version {
					strictly '[2.1.0, 2.2.0['
					prefer '2.1.214'
				}
				because 'Class File targeting Java 21 inside'
}

2.1.214 has a vulnerability though.

### Expected behavior

Run gradle clean build on project using current quarkus plugin without errors on Java 17 and 11

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.6.0.CR

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

### Additional information

Questions regarding not understood behaviour:

Why is Quarkus using a library for its build that has class files inside which target Java21?
Why is the build failing just now, as the library in question (h2-2.2.224.) was released 2 months ago?
Why is the build also failing on outdated plugin versions (2.6.X), shouldn't the plugin use precisely defined dependencies?

**Comment by mschorsch** [comment]
Others seems to have similar problems with h2:
- https://github.com/jeremylong/DependencyCheck/pull/6131
- https://github.com/dependency-check/dependency-check-gradle/issues/364
- https://github.com/gradle/gradle/issues/27156

**Comment by mschorsch** [comment]
@Xnyle As described in https://github.com/gradle/gradle/issues/27156#issuecomment-1827493093 the issue seems to be fixed in Gradle 8.4.

**Comment by gsmet** [comment]
@Xnyle could you upgrade your Gradle wrapper and see how it goes?

In any case, I don't think it's something we can adjust in Quarkus itself so I'm going to close the issue.

Thanks @mschorsch for having a look.

If in the end, you have other information and it looks like a Quarkus issue, please reopen the issue.
