### ISSUE TITLE
DeploymentException: Mixing RESTEasy Reactive and RESTEasy Classic server parts is not supported

### ISSUE THREAD

**Issue by daloji** [quarkusio/quarkus#37316]
### Describe the bug

Hello
I'm trying to upgrade our quarkus version (3.2.9 -> 3.5) but I have a problem.
```[ERROR]  [error]: Build step io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor#checkMixingStacks threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Mixing RESTEasy Reactive and RESTEasy Classic server parts is not supported```

we have migrated our lib ReastEasy-classic to RestEasy Reactive
```
 <dependency>
 <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
    </dependency>
 <dependency>
<dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-multipart-provider</artifactId>
    </dependency> 
```
I think the issue is from  **resteasy-multipart-provider**  I haven't found an Reactive equivalent  

### Expected behavior

support upgrading 3.2.9 to 3.5 with **resteasy-multipart-provider** dependency

### Actual behavior

``
[error]: Build step io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor#checkMixingStacks threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Mixing RESTEasy Reactive and RESTEasy Classic server parts is not supported
	at io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor.checkMixingStacks(ResteasyReactiveCommonProcessor.java:107)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
``

### How to Reproduce?

you can reproduce with this  repository
https://github.com/daloji/Mixing-RESTEasy-Reactive-and-RESTEasy-Classic-server-parts-is-not-supported

### Output of `uname -a` or `ver`

6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "19" 2022-09-20  OpenJDK Runtime Environment (build 19+36-2238)  OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)

### Quarkus version or git rev

3.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

pache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)  Maven home: /opt/apache-maven-3.8.5  Java version: 19, vendor: Oracle Corporation, runtime: /opt/jdk-19  Default locale: fr_FR, platform encoding: UTF-8  OS name: "linux", version: "6.2.0-37-generic", arch: "amd64", family: "unix"

**Comment by mschorsch** [comment]
@daloji See here https://stackoverflow.com/questions/67675566/quarkus-reasteasy-reactive-with-multipart-extension

**Comment by daloji** [comment]
> @daloji See here https://stackoverflow.com/questions/67675566/quarkus-reasteasy-reactive-with-multipart-extension

yes but we use **resteasy-multipart-provider**   not    **quarkus-resteasy-multipart**

**Comment by gsmet** [comment]
@daloji It's exactly the same issue. `resteasy-multipart-provider` is part of RESTEasy Classic and you are using RESTEasy Reactive so this is not a supported combination.
We used to not complain about it but now we complain loudly as it can lead to unexpected behavior.

You should use the multipart support of RESTEasy Reactive and report back if you encounter issues.

**Comment by geoand** [comment]
I assume this is the same as https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Mixing.20RESTEasy.20Reactive.20and.20RESTEasy.20Classic.20server.20parts/near/404032138, correct?

**Comment by daloji** [comment]
> I assume this is the same as https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Mixing.20RESTEasy.20Reactive.20and.20RESTEasy.20Classic.20server.20parts/near/404032138, correct?

yes

**Comment by geoand** [comment]
As mentioned in the chat, RESTEasy Reactive already comes with multipart support.

**Comment by luca-bassoricci** [comment]
> [#36780 (comment)](https://github.com/quarkusio/quarkus/discussions/36780#discussion-5794288)

@geoand  I'm sorry to bother you for a closed topic, but with quarkus multipart support I lost the possibility to send a generic multipart form via RR client; which is the right way to intercept a generic form on server side and send this form to a RR client?

thanks
Luca

**Comment by gsmet** [comment]
@luca-bassoricci If I were you, I would create a small project showing what you achieved with RESTEasy Classic and can't with the Reactive one.
