### ISSUE TITLE
Index missing in quarkus-grpc-stubs

### ISSUE THREAD

**Issue by alerosmile** [quarkusio/quarkus#37312]
### Describe the bug

I'm writing a client which connects to the `grpc.health.v1.Health` service. I'd like to inject the client as follows:

```java
  import grpc.health.v1.Health;
  ...
  @GrpcClient
  Health client;
```

The generated classes are available from the `io.quarkus:quarkus-grpc-stubs` dependency but there is no index. As expected, the injection fails with the following message: 
`grpc.health.v1.Health cannot be injected into ... - only Mutiny service interfaces, blocking stubs, reactive stubs based on Mutiny and io.grpc.Channel can be injected via @GrpcClient`

**Comment by alesj** [comment]
You can workaround a bit -- inject the Channel, and @Produce the Health client with it?
And then use @Inject ...
Or wdyt @cescoffier?
Since afais, just index won't solve this ootb.

**Comment by cescoffier** [comment]
That's what I was wondering. 

@alerosmile did you try indexing the quarkus-stub jar to make sure it fixes the issue? 

You can try with:

```
quarkus.index-dependency.stub.group-id=io.quarkus
quarkus.index-dependency.stub.artifact-id=quarkus-grpc-stubs (verify the name of the artifact)
```

**Comment by alerosmile** [comment]
@cescoffier That's exactly what I've done as a workaround. That works. But shouldn't all the dependencies containing beans also include an index? I'm quite new to Quarkus so I might not understand this correctly.

https://quarkus.io/guides/cdi-reference#bean_discovery

I see that most (or all?) Quarkus dependencies do not contain such an index or beans.xml resource. How does bean discovery work in this case? What exactly is `Quarkus integration code`?

If you tell me that defining those properties in this case is the way to go, I fully accept this.

**Comment by cescoffier** [comment]
@alerosmile, thanks for the feedback.

The gRPC extension is not looking for the beans in the grpc-stubs but for the gRPC generated classes. anyway, we should produce an index.

**Comment by alerosmile** [comment]
@cescoffier Built and tested. Works! Thank you.

**Comment by cescoffier** [comment]
Thanks for the feedback @alerosmile !
