### ISSUE TITLE
2.13.9.Final regression when using domain socket, probably caused by netty upgrade

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#37319]
### Describe the bug

2.13.9.Final regression when using domain socket, probably caused by netty upgrade

I see failure of `DomainSocketIT` when updating 2.13 branch of quarkus qe test suite

The issue is probably related to the netty upgrade to 4.1.100
I found similar issue for Quarkus 3.1 - https://github.com/quarkusio/quarkus/issues/33679

CC @cescoffier / @aloubyansky / @vietj

### Expected behavior

DomainSocketIT passes

### Actual behavior

DomainSocketIT fails

### How to Reproduce?

```
git clone -b 2.13 https://github.com/quarkus-qe/quarkus-test-suite
cd quarkus-test-suite
mvn clean verify -pl http/http-advanced -Dit.test=DomainSocketIT -Dquarkus.platform.version=2.13.9.Final
````

Test passes when running with 2.13.8.Final, command: `mvn clean verify -pl http/http-advanced -Dit.test=DomainSocketIT -Dquarkus.platform.version=2.13.8.Final`.

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.13.9.Final

**Comment by cescoffier** [comment]
Unfortunately, that would require a Vert.x bump.

**Comment by cescoffier** [comment]
Out of date - it has been fixed.
