### ISSUE TITLE
Using RequestScoped inside a log filter used in async handler

### ISSUE THREAD

**Issue by rquinio1A** [quarkusio/quarkus#37334]
### Description

We were thinking of leveraging `@RequestScoped` inside a filter, to have capability of programatic registration of sensitive data, beyond pattern-based example described in #33392 

However when using async=true, we noticed the filters were not executing on the AsyncHandler but on the nested handler.
cf https://github.com/quarkusio/quarkus/blob/6048280a15e2bc25ed611a35c34b5217f5d83b08/core/runtime/src/main/java/io/quarkus/runtime/logging/LoggingSetupRecorder.java#L580-L582
 `@RequestScoped` injection doesn't work in that case. Typically one would use MDC to pass "request scope" data to the handler, but in this case it might not be a good idea to put sensitive values in MDC which is a public API.

Would it make sense to have filters execute synchronously on the AsyncHandler when in async mode ?

- Pros: filtered logs don't have to be queued.
- Cons: the filtering time blocks the request.

Our main use case is with https://github.com/quarkiverse/quarkus-logging-splunk, but I think the behavior has to be consitent with the core handlers.

**Comment by geoand** [comment]
I get where this is coming from, but there is no active request running when something gets run in another thread. Furthermore, it's not really possible to tie this async log handling to a single original request, because in the general case, the logs entries could have come from multiple requests
