### ISSUE TITLE
Docs: security-oidc-code-flow-authentication-tutorial guide

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#37333]
### Describe the bug

I identified several issues in `Protect a web application by using OpenID Connect (OIDC) authorization code flow `   guide[1]:
1. Application creation code[2] for maven fails with error `Could not find artifact io.quarkus.platform:quarkus-maven-plugin:jar:999-SNAPSHOT `. This can be fixed by changing `mvn io.quarkus.platform:quarkus-maven-plugin:999-SNAPSHOT:create` to `mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create` .
2.  [Improvement]: code example[3] get claims by name, while it can be done by `Claims` enum without a risk of typos (eg `this.idToken.getClaim(Claims.preferred_username);` instead of `this.idToken.getClaim("preferred_username");`)
3. Link to "Create keycloak realm"[4]  leads to the header of the page (probably should be https://www.keycloak.org/docs/latest/server_admin/index.html#configuring-realms instead)
4. Current example requires log-in on every page refresh. It would be nice to have a description on how to make this more permanent.

[1] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial
[2] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial#create-the-maven-project
[3] https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial#write-the-application
[4] end of https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial#start-and-configure-the-keycloak-server

**Comment by fedinskiy** [comment]
it should be https://github.com/quarkusio/quarkus/labels/area%2Fdocs probably

**Comment by michalvavrik** [comment]
About `1.` I guess this will be very common issue (not specific for this guide) as that is generated. But definitely agreed it should be fixed for the main branch.

**Comment by fedinskiy** [comment]
Update: It looks like that the need to log in on every attempt is due to the realm example file[1], which contains session length of 2 seconds, which is especially strange, given, that it also has idle session length of 30 minutes.

[1] https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-openid-connect-web-authentication-quickstart/config/quarkus-realm.json#L11

**Comment by sberyozkin** [comment]
@fedinskiy

>Current example requires log-in on every page refresh. It would be nice to have a description on how to make this more permanent.

Thanks for spotting it, I even opened a PR, 
https://github.com/quarkusio/quarkus-quickstarts/pull/1354,
but it breaks a timeout test which explains why it was set so low.

I'll add a small section explaining how it can extended in the Keycloak Admin dashboard

**Comment by sberyozkin** [comment]
@fedinskiy FYI, #37464.

Please create an independent issue to address your point 1, as @michalvavrik suggested, thanks

**Comment by fedinskiy** [comment]
The issue for maven plugin: https://github.com/quarkusio/quarkus/issues/37482
