### ISSUE TITLE
Rename the Vineflower properties ?

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#37332]
### Description

In previous versions of Quarkus, to get the decompiled code, we had to set the Fernflower property:

```
quarkus.package.fernflower.enabled=true
```

Since Quarkus 3.6, Fernflower has been dropped, and instead it uses Vineflower with the following properties:

```
quarkus.package.vineflower.enabled
quarkus.package.vineflower.version
quarkus.package.vineflower.jar-directory
```

This being an implementation detail, the property is not very easy to find. What about renaming it with `decompile` or something like that ?

**Comment by gsmet** [comment]
I'm a bit undecided on it. I can see why you would want that but then we would have a hard time making sense of  `quarkus.package.vineflower.version`?

Maybe we should have some generic options to enable the decompiler (I would go with `quarkus.package.decompiler.*`) that most people would use as they don't care about the tool and some advanced options specific to the decompiler (e.g. `quarkus.package.vineflower.version`).

Now not sure it's worth the bikeshedding, I will let @geoand decide.

**Comment by agoncal** [comment]
It was @maxandersen who [asked me to create an issue](https://twitter.com/maxandersen/status/1729161392606040427). 

As you pointed out, it's not a big of an issue. But for some advanced case, finding the property `fernflower` and now `vineflower` is tricky. You really need to remember it. And in the future you change the implementation to `sunflower` or `yetanotherflower` you would have to change the property name. 

And what about ?

```
quarkus.package.decompiler.enabled
quarkus.package.decompiler.vineflower.version
quarkus.package.decompiler.vineflower.jar-directory
quarkus.package.decompiler.fernflower.version
quarkus.package.decompiler.fernflower.jar-directory
quarkus.package.decompiler.sunflower.version
quarkus.package.decompiler.sunflower.jar-directory
```

**Comment by geoand** [comment]
> I can see why you would want that but then we would have a hard time making sense of quarkus.package.vineflower.version

That's exactly why I had a specific version.

However, it turns out it never needs to be changed, so the decompiler name is almost always useless - not to mention harder to type.

In retrospect, I should have used the simple name proposed here and not doing it only added confusion.

So +1 for the change

**Comment by mkouba** [comment]
+1 for `quarkus.package.decompiler.enabled`, `quarkus.package.decompiler.jar-directory` and removing the version completely.

I wonder if it would make sense to support different decompilers though. Probably not.

**Comment by gsmet** [comment]
> I wonder if it would make sense to support different decompilers though. Probably not.

I wouldn't spend time on that except if there is a very good reason for it.

**Comment by geoand** [comment]
Yeah, I intend to have a transition period

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/37445 takes care of it
