### ISSUE TITLE
"Additional requirements for client SSL" step not working

### ISSUE THREAD

**Issue by MichielDx** [quarkusio/quarkus#37353]
### Describe the bug

I'm trying to follow the AWS Lambda guide, but am stuck copying the GraalVM files. I ran the `docker run` command and then the `docker cp` command, but get following error: Could not find the file /opt/graalvm/lib/libsunec.so in container XXX. When going into the docker container, there is no /opt/graalvm directory, only /opt/mandrel.

https://quarkus.io/guides/aws-lambda#additional-requirements-for-client-ssl

**Comment by galderz** [comment]
That might be an oversight in the documentation. Do things work if you modify the commands to use `/opt/mandrel` instead?

**Comment by MichielDx** [comment]
That also doesn't work. These files are present in the container under `/opt/mandrel/lib`
![image](https://github.com/quarkusio/quarkus/assets/18028456/19213f39-2f8f-46e8-bec0-825249081d48)

**Comment by zakkak** [comment]
@patriot1burke it looks like the [Additional requirements for client SSL](https://quarkus.io/guides/aws-lambda#additional-requirements-for-client-ssl) section needs a refresh, could you please have a look?

**Comment by zakkak** [comment]
Closing in favor of https://github.com/quarkusio/quarkus/issues/37466
