### ISSUE TITLE
[Extension Proposal] KafkaStreams processor

### ISSUE THREAD

**Issue by flazarus1A** [quarkusio/quarkus#37358]
### Description

Quarkus extension enriching Kafka Streams topologies through decorators:
* CONTINUE error strategy and dead letter queue
* Resiliency against Punctuator errors
* Retry mechanism with Smallrye Fault Tolerance

### Repository name

quarkus-kafka-streams-processor

### Short description

Extension to easily build resilient Kafka Streams topologies based on the Processor API

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-kafka-streams-processor/dev/

### Repository Topics

- quarkus-extension
- kafka-streams
- resiliency

### Team Members

Emile De Weerd @edeweerd1A
François Lazarus @flazarus1A
Luca Martella @lmartella1
Aitor Moragas Garrido @tryasta
Romain Quinio @rquinio1A 
Kevin Viet @vietk

### Additional context

The extension relies on quarkus-kafka-streams core extension for bootstraping the KafkaStreams topology.
It only has a loose coupling with Quarkus, and could be split into a standalone library usable with another bootstrap and a Quarkus extension in the future. For now, it is only used and tested within a Quarkus project, hence the single-repository extension approach.

**Comment by rquinio1A** [comment]
@gastaldi pinging you, as you were the one to do the setup of https://github.com/quarkiverse/quarkus-logging-splunk :)

This extension would contain the work we did in the past 3 years to have stateless/stateful KafkaStreams processors (i.e. not full KStreams DSL) on Quarkus and would be primarily maintained by [Amadeus](https://github.com/AmadeusITGroup).

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-kafka-streams-processor. Enjoy!
