### ISSUE TITLE
Log doesn't have color in dev mode

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#37373]
### Describe the bug

Log on console appears only in white color

![image](https://github.com/quarkusio/quarkus/assets/405347/84b7b755-f3ab-4b84-9c49-1492045e635a)

### Expected behavior

Colorful logs when running in dev mode (quarkus:dev). 

### Actual behavior

White log. Maven appears colorful. Quarkus app is the sad one.

![image](https://github.com/quarkusio/quarkus/assets/405347/a89e9c5c-0f15-4c15-8642-bdb8c7929425)

### How to Reproduce?

Brand new Quarkus app (default) from https://code.quarkus.io/

### Output of `java -version`

openjdk version "17.0.8.1"

### Quarkus version or git rev

3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5

### Additional information

`%dev.quarkus.log.console.color=true` is a workaround, but with a deprecation warning (would be nice to have a hint of the new property).
![image](https://github.com/quarkusio/quarkus/assets/405347/d5062fee-b353-47d2-a829-8b18208155c3)

`%dev.quarkus.console.color=true` is the valid workaround but shouldn't be necessary
![image](https://github.com/quarkusio/quarkus/assets/405347/e1babbc8-bc0d-4692-a01a-ce363b95b88b)

**Comment by melloware** [comment]
Sure I don't see why not!

**Comment by gian1200** [comment]
Found the code

https://github.com/quarkusio/quarkus/blob/455ec6c4244f64b09df6b755b7e462deef1dd51b/core/runtime/src/main/java/io/quarkus/runtime/configuration/DeprecatedRuntimePropertiesRecorder.java#L26

https://github.com/quarkusio/quarkus/blob/455ec6c4244f64b09df6b755b7e462deef1dd51b/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L536

However, a more generic approach should be used. Next to the place where it's deprecated should be optionally set the new property. When that definition is set, the log can print it; when not, the log can be AS-IS (probably a new annotation next to `@Deprecated`?). Currently, the notice is commented next to the annotation (**javadoc `@deprecated` tag is not used**) , but it's not available at runtime (AFAIK).

https://github.com/quarkusio/quarkus/blob/455ec6c4244f64b09df6b755b7e462deef1dd51b/core/runtime/src/main/java/io/quarkus/runtime/logging/ConsoleConfig.java#L47

Given that it can affect a core part of Quarkus, probably it's best idea if someone else does it.

Closing the issue in favor of https://github.com/quarkusio/quarkus/issues/33877 or https://github.com/quarkusio/quarkus/issues/5665
