### ISSUE TITLE
Move Qute RR and Qute RC codestarts to qute-web repo

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#37383]
### Describe the bug

With the recent qute-web changes leading to unlisting qute RC and RR, the codestarts are useless in core.

We just need one in the qute-web repository and adapt it to qute-web (no more bean needed).

**Comment by ia3andy** [comment]
I will take care of it..

**Comment by mkouba** [comment]
@ia3andy Is this still relevant in the context of https://github.com/quarkusio/quarkus/issues/40069?

**Comment by ia3andy** [comment]
It's done already

**Comment by ia3andy** [comment]
Ah sorry it's not done, I think we can keep them for now, let's close anyway
