### ISSUE TITLE
quarkus-info extension and Quarkus Version info

### ISSUE THREAD

**Issue by zemiak** [quarkusio/quarkus#37380]
### Description

Hello,

I am probably just blind (and in this case, I truly apologise), but I cannot see where can I get the Quarkus Version information in the quarkus-info extension. I would like to see:
* quarkus version
* whether the service/app is running under jvm/native mode

Right now I am injecting the quarkus version in the application.properties in a CI/CD step, but having it available in quarkus-info would be much nicer.

Thanks,
Miroslav

Quarkus: 3.5.3
JVM: 21

**Comment by geoand** [comment]
Yeah, I think it makes sense to add

**Comment by geoand** [comment]
Would you be interesting in contributing this improvement?

**Comment by zemiak** [comment]
OK, let me check some tutorials about extensions and then I will come back

**Comment by gsmet** [comment]
@zemiak FYI the code for this extension is here: https://github.com/quarkusio/quarkus/tree/main/extensions/info

**Comment by melloware** [comment]
@zemiak this would be a good enhancement!

**Comment by zemiak** [comment]
PR merged to main, scheduled for 3.7
