### ISSUE TITLE
Update gradle to 8.5 and backport if possible to finish Java 21 dependencies

### ISSUE THREAD

**Issue by AlexKovynev** [quarkusio/quarkus#37392]
### Describe the bug

Old gradle

**Comment by gsmet** [comment]
If you would like to contribute, you can mimic this pull request: https://github.com/quarkusio/quarkus/pull/36435

**Comment by gsmet** [comment]
And I agree it would be good to backport it to 3.6.1 if CI is happy and it doesn’t involve too many changes. 

PR should be created for main. I will handle the backport myself.

**Comment by akpatternica** [comment]
@gsmet i can try. But do you know where to get sha256sum for bin?

**Comment by akpatternica** [comment]
@gsmet [#37395](https://github.com/quarkusio/quarkus/pull/37395)

**Comment by gsmet** [comment]
I see you figured it out :). Thanks for the PR!
