### ISSUE TITLE
Add arangodb client extension

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#37406]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-arangodb-client-ext

### Short description

Make the ArangodbClient configurable and accessible

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

-

**Comment by dcdh** [comment]
The extension is available in my github repository here https://github.com/dcdh/quarkus-arangodb-client-ext
Could you review and create the repository in quarkiverse ?

Thanks.

Regards, Damien

**Comment by gastaldi** [comment]
Nice!

**Comment by gastaldi** [comment]
@dcdh the https://github.com/quarkiverse/quarkus-arangodb-client was created and you are now a maintainer of this repository. See https://hub.quarkiverse.io/checklist/#after-the-repository-is-created for the next steps

**Comment by dcdh** [comment]
@gastaldi I've got a 403 response when pushing into the repository.

> 11:02:16.165: [quarkus-arangodb-client-ext] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain quarkiverse refs/heads/master:master
remote: Permission to quarkiverse/quarkus-arangodb-client.git denied to dcdh.
fatal: unable to access 'https://github.com/quarkiverse/quarkus-arangodb-client/': The requested URL returned error: 403

Could you please have a look on the repository settings ?
Regards,
Damien

**Comment by gastaldi** [comment]
I don't see your user in the Quarkiverse org. Have you accepted the invitation to join it?

**Comment by dcdh** [comment]
Sorry, I miss this action. Just done it. Many thanks.
