### ISSUE TITLE
Using ReactiveRedisDataSource Not Working

### ISSUE THREAD

**Issue by linktech1** [quarkusio/quarkus#37405]
### Describe the bug

I changed the redis-quickstart to use the ReactiveRedisDataSource and ReactiveValueCommand and it no longer stores the value. I also changed the service to store the Increment object instead of just the value.

Using the RedisDataSource and ValueCommand everything works correctly. 

### Expected behavior

ReactiveRedisDataSource and ReactiveValueCommand should work the same as using RedisDataSource and ValueCommand except work reactive

### Actual behavior

No values are stored and none can be retrieved when ReactiveRedisDataSource and ReactiveValueCommand are used.

### How to Reproduce?

Use the redis-quickstart and change the get and set methods in the IncrementService to use the ReactiveValueCommand in those methods. 

=================================================================
package org.acme.redis;

import java.util.List;

import io.quarkus.redis.datasource.ReactiveRedisDataSource;
import io.quarkus.redis.datasource.keys.ReactiveKeyCommands;
import io.quarkus.redis.datasource.value.ReactiveValueCommands;
import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;

@Singleton
class IncrementService {

    
    private ReactiveKeyCommands<String> keys;
    //private ValueCommands<String, Increment> counterCommand;
    private ReactiveValueCommands<String, Increment> reactiveCounterCommand;

    @Inject
    public IncrementService(ReactiveRedisDataSource reactiveRedisDS) {
    	
        keys = reactiveRedisDS.key();
        //counterCommand = redisDS.value(Increment.class);
        reactiveCounterCommand = reactiveRedisDS.value(Increment.class);
    }

    Uni<Void> del(String key) {
        return keys.del(key)
            .replaceWithVoid();
            
    }

    Uni<Increment> get(String key) {
        return reactiveCounterCommand.get(key);
    }

    void set(String key, Increment increment) {
    	reactiveCounterCommand.set(key, increment);
    }

    void increment(String key, int incrementBy) {
    	reactiveCounterCommand.incrby(key, incrementBy);
    }

    Uni<List<String>> keys() {
    	
        return keys.keys("*");
    }
}

**Comment by cescoffier** [comment]
set and incrBy are returning Unis. You must subscribe to them or return the Uni (and let Quarkus subscribe)

**Comment by linktech1** [comment]
I changed the set method to:

    void set(String key, Increment increment) {
		reactiveCounterCommand.set(key, increment)
		.subscribe()
		.with(
	         result -> System.out.println("inserted " + increment),
	         failure -> System.out.println("Failed " + failure));
    }

It WORKS!!!

I tried returning the UniVoid that comes back but that didn't work....

**Comment by linktech1** [comment]
It would be great if this was added to the documentation and examples!
