### ISSUE TITLE
Support and example for using bazel, preferrably with java_image

### ISSUE THREAD

**Issue by rverma-nikiai** [quarkusio/quarkus#3741]
**Description**
Tried below config 
```
java_library(
    name = "lib",
    srcs = glob(["**/*.java"]),
    resources = glob(["resources/application.properties"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "@maven//:io_quarkus_quarkus_jackson",
        "@maven//:io_quarkus_quarkus_rest_client",
        "@maven//:io_quarkus_quarkus_resteasy_jackson",
        "@maven//:io_quarkus_quarkus_smallrye_health",
        "@maven//:javax_inject_javax_inject",
        "@maven//:javax_enterprise_cdi_api_2_0_SP1",
        "@maven//:org_eclipse_microprofile_config_microprofile_config_api",
        "@maven//:org_eclipse_microprofile_rest_client_microprofile_rest_client_api",
        "@maven//:org_jboss_spec_javax_ws_rs_jboss_jaxrs_api_2_1_spec",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)

load("@io_bazel_rules_docker//java:image.bzl", "java_image")

java_image(
    name = "docker",
    runtime_deps = [":lib"],
)
```
But its missing a target to run. Can't figure out what/how pass the correct target. 

May be dependent on https://github.com/quarkusio/quarkus/issues/2143

**Comment by geoand** [comment]
I don't know anything about Bazel (and I assume I'm not the only one), but I strongly suspect this can't work.
Basically for Maven and Gradle Quarkus has a plugin that creates the final artifact - no such plugin exists for Bazel.
Now if/when Quarkus can be run from a simple `public static void main`, something like this would maybe work

**Comment by rverma-nikiai** [comment]
Do we use any annotationProcessor to generate the main class?

**Comment by geoand** [comment]
Quarkus does not use annotation processors. All the magic is done at a post compile phase

**Comment by rverma-nikiai** [comment]
Bazel doesn't have as such a plugin mechanism, however its more of a generic rule which you can define a rule, which can be a shell script, java jar, or any binary etc. Basically, if I can get a jar from maven central, and can run `java -jar /my/code/src/dir` and can generate the Main class, we can make bazel work with it :)

**Comment by rverma-nikiai** [comment]
Or as stated earlier, having the main class in code would be simplest :)

**Comment by geoand** [comment]
We'll see if the Main class thing actually happens.

**Comment by gsmet** [comment]
I'm closing this one for now. If at some point you get it to work, we will be happy to host the related documentation.

**Comment by carolosf** [comment]
I created rules_gradle in order to build quarkus apps using gradle. 

It is not ideal because it doesn't compile directly with bazel java rules and so we lose some caching but at least whatever changes are made to quarkus it is still likely to work. 

https://github.com/carolosf/rules_gradle

Example with Quarkus: https://github.com/carolosf/quarkus-bazel-gradle

Hopefully in future we will see direct support.

**Comment by thaibui** [comment]
Quarkus supports configuring a main class now so it would be nice if can someone revisit this so that we have an example of bazel rules working with Quarkus.

**Comment by Vertexwahn** [comment]
Looking forward to a Bazel Quarkus example! If anyone has something please share

**Comment by gabrielmirandat** [comment]
Any updates on this?

**Comment by tructxn** [comment]
Any updates on this ?

**Comment by kinhluan** [comment]
For anyone still looking for Bazel + Quarkus support — I've published a working implementation: [rules_quarkus](https://github.com/kinhluan/rules_quarkus)

It uses the official `QuarkusBootstrap` API to run full augmentation within Bazel, producing the same output as a Maven build. Supports Quarkus 3.20.1, Bazel 7.x, Java 21.

See #11305 for more technical details on the ClassLoader challenges and how they were resolved.

**Comment by handicraftsman** [comment]
https://github.com/clementguillot/rules_quarkus has a quarkifier tool

Maybe something like that could be done as a part of quarkus itself, but with a stable non-bazel-specific API?

Say in a way that would accept a JSON/YAML file, and perform the transformations specified there.
