### ISSUE TITLE
Docs: OpenID Connect (OIDC) and OAuth2 Client and Filters Reference Guide

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#37430]
### Describe the bug

Found issues in https://quarkus.io/version/main/guides/security-openid-connect-client-reference

- https://quarkus.io/version/main/guides/security-openid-connect-client-reference#use-oidcclient-directly . In the code sample there is import `import jakarta.inject.PostConstruct;` which does not work, IMHO it should be `import jakarta.annotation.PostConstruct;`

- https://quarkus.io/version/main/guides/security-openid-connect-client-reference#named-oidc-clients - First code sample is missing imports for `@NamedOidcClient` and `OidcClient`: 
 ```
import io.quarkus.oidc.client.NamedOidcClient;
import io.quarkus.oidc.client.OidcClient;
```

- https://quarkus.io/version/main/guides/security-openid-connect-client-reference#oidc-client-reactive-filter - First and last code samples has unused import `import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;`
- https://quarkus.io/version/main/guides/security-openid-connect-client-reference#integration-testing-oidc-client - Section about testing could use an actual test example.  It at least looks strange to have everything setup in detail but no actual test.
- Chapter "Token Propagation Reactive" is there twice, it should be unified in one:
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#token-propagation-reactive
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#reactive-token-propagation

- Code samples is several sections are missing imports for `@GET` and `@Path`:
```
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
```
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#oidc-client-reactive-filter
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#token-propagation-reactive
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#restclient-accesstokenrequestfilter
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#restclient-jsonwebtokenrequestfilter

- A lot of code samples has methods, which should return `String` but has no return statement. It it somehow bad to have an example code that cannot be compiled.
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#use-oidcclient-directly
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#inject-tokens
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#use-oidc-clients
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#named-oidc-clients
https://quarkus.io/version/main/guides/security-openid-connect-client-reference#oidc-client-filter

**Comment by jedla97** [comment]
Just note after going through guide

> A lot of code samples has methods, which should return String but has no return statement. It it somehow bad to have an example code that cannot be compiled.

In my POV I don't think this is a problem as the comments there states that this is for user modification. We can probably add just return statetments with blank string but I personaly don't like it as it don't have any added value + this is reference guide not the guide to follow code and get results. 

Otherwise other problem are adressed in PR linked ^
