### ISSUE TITLE
Injecting ConfigProperty of type Optional<List<String>> not working in the native mode

### ISSUE THREAD

**Issue by DeMol-EE** [quarkusio/quarkus#37444]
### Describe the bug

Given code:

```java
    @Inject
    @ConfigProperty(name = "stuff")
    Optional<List<String>> stuff;
```

will result in an empty optional, even when running in an environment where variable STUFF is set to a valid, non-empty value.

### Expected behavior

That the optional is not empty if the env var STUFF is set to a valid, non-empty value.

### Actual behavior

The optional is empty

### How to Reproduce?

See [reproducer](https://github.com/DeMol-EE/quarkus-reproducer-37444) README

### Output of `uname -a` or `ver`

FROM quay.io/quarkus/quarkus-micro-image:2.0

### Output of `java -version`

FROM quay.io/quarkus/quarkus-micro-image:2.0

### Mandrel or GraalVM version (if different from Java)

FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

### Quarkus version or git rev

3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

**Comment by mkouba** [comment]
FTR I was able to reproduce it locally even without docker involved; just built a native image from the reproducer, set an env variable via `export STUFF=foo,bar`, run the app and the output looks like:
```
2023-12-01 11:21:16,785 INFO  [org.acm.Filter] (vert.x-eventloop-thread-0) injected: Optional.empty
2023-12-01 11:21:16,785 INFO  [org.acm.Filter] (vert.x-eventloop-thread-0) located: [foo, bar]

```

**Comment by mkouba** [comment]
CC @radcortez

**Comment by gsmet** [comment]
@radcortez this is rather concerning as it could lead to undesired behaviors, especially since the behavior is different in native. Could you prioritize it? Thanks!

**Comment by radcortez** [comment]
I'll have a look

**Comment by mkouba** [comment]
> This is expected, because filters are initialized during static init, meaning that injected configuration is the one available during build time. When config is accessed in `filter`, the configuration is the one available at runtime.

Ah, of course. So the workaround is to obtain the config property lazily, i.e. inject `@ConfigProperty(name = "stuff") Instance<Optional<List<String>>> stuff` instead and then `stuff.get()` in the filter method. It would work for any other CDI component that is not initialized during the STATIC_INIT bootstrap phase (i.e. when the native image is built).

**Comment by radcortez** [comment]
> Ah, of course. So the workaround is to obtain the config property lazily, i.e. inject `@ConfigProperty(name = "stuff") Instance<Optional<List<String>>> stuff` instead and then `stuff.get()` in the filter method. It would work for any other CDI component that is not initialized during the STATIC_INIT bootstrap phase (i.e. when the native image is built).

Correct.

**Comment by DeMol-EE** [comment]
OK, thanks guys.

**Comment by mkouba** [comment]
> This was added in #36281, but apparently it does not work properly when there is no value to record and compare when starting up the native image.

Hm, it seems that we intentionally [do not record a missing value](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ConfigStaticInitCheckInterceptor.java#L71-L73). Maybe we should?
