### ISSUE TITLE
Subclasses of CDI Method Observers Not Invoked

### ISSUE THREAD

**Issue by gilday** [quarkusio/quarkus#37443]
### Describe the bug

CDI's [Observes](https://jakarta.ee/specifications/cdi/3.0/apidocs/jakarta/enterprise/event/observes) states that

> Observer methods are inherited by bean subclasses.

So I would expect an interface with observer methods to apply be called on implementations of this interface e.g.

```java
public interface EventListener {

  /** {@link Observes} states that "Observer methods are inherited by bean subclasses." */
  void onEvent(@Observes MyEvent event);
}

@ApplicationScoped
class EventListenerImpl implements EventListener {

  @Inject AtomicInteger counter;

  /**
   * Adding {@code @Observes} to the event parameter should not be necessary, but this does not work
   * without it.
   */
  @Override
  public void onEvent(MyEvent event) {
    counter.incrementAndGet();
  }

}
```

### Expected behavior

CDI observer methods on super types apply to subtypes.

### Actual behavior

Subtype's observer method is never called.

### How to Reproduce?

The test in this class fails, because the listener method is never called.

[cdi-event-subclass-reproducer.zip](https://github.com/quarkusio/quarkus/files/13519306/cdi-event-subclass-reproducer.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.localdomain 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9) OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)

### Quarkus version or git rev

3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.9.5-bin/32db9c34/apache-maven-3.9.5 Java version: 17.0.9, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "14.1.1", arch: "aarch64", family: "mac"

**Comment by manovotn** [comment]
This behavior is correct, the inheritance of observer methods works in a scenario where you do not override the method in the subclass. Something like this:

```
@Dependent
public class Foo {
  void onEvent(@Observes MyEvent event) {...}
}

@Dependent
public class Bar extends Foo {
  // the observer method is inherited and Bar will receive the event as well
}
```

This is rooted in [CDI specification](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#member_level_inheritance):

> Suppose a class X is extended directly or indirectly by the bean class of a managed bean Y.
> If X declares an initializer, non-static observer, @PostConstruct or @PreDestroy method x() then Y inherits x() if and only if neither Y nor any intermediate class that is a subclass of X and a superclass of Y overrides the method x(). (This behavior is defined by the Common Annotations for the Java Platform specification.)

Also note that annotation inheritance usually doesn't happen from interfaces to subclasses (at least for type-level metadata), [this section of the spec](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#inheritance) mentions it as well.

**Comment by Ladicek** [comment]
I don't think there's any exception, "usually doesn't happen" could/should be "never happens".

**Comment by manovotn** [comment]
> EDIT: in the context of CDI, of course. There's at least one specification that does permit annotation inheritance on methods and from interfaces (JAX-RS).

@mkouba I was subtly referring to this^^
I know it's outside of CDI spec but you definitely can encounter it when working with Quarkus :)

**Comment by mkouba** [comment]
I see and yes, I'm aware of JAX-RS.
