### ISSUE TITLE
Setting `quarkus.servlet.context-path` breaks `quarkus-smallrye-metrics`

### ISSUE THREAD

**Issue by greyskyy** [quarkusio/quarkus#3745]
**Describe the bug**

When the context-root is set to a non-default value, the metrics extension always returns a 500 error with the following message:
```
The expected context root of metrics is /metrics, but a request with a different path was routed to MetricsRequestHandler
```

**Expected behavior**
The `/metrics` endpoint is provided under the provided context-root (in this case /myroot/metrics)

**Actual behavior**
see description above

**To Reproduce**
1.  Create a simple quarkus application using `quarkus-resteasy` and `quarkus-smallrye-metrics`
2.  in `application.properties` set the context path to a non-default value E.g. `quarkus.servlet.context-path=/myroot`
3. start the application and navigate to `http://localhost:8080/myroot/metrics`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: windows 10
 - Output of `java -version`: 
    ```
    openjdk version "11.0.2" 2019-01-15
    OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
    ````
 - GraalVM version (if different from Java): n/a (not running native)
 - Quarkus version or git rev:  0.21.1

**Comment by gsmet** [comment]
@jmartisk @kenfinnigan what do you think about this one? Should we take the context root into account? I suppose we should try to be consistent with SmallRye Health too.

**Comment by jmartisk** [comment]
https://github.com/quarkusio/quarkus/pull/3772 should fix this

**Comment by jmartisk** [comment]
I'd say that if the whole application is under a custom context-root, then the metrics endpoint should be under it too. I tried doing this with Health and it works this way, so I guess we just need to fix Metrics

**Comment by xstefank** [comment]
From a Health perspective, this is not specified in the spec. I think that we need to take this on MP architecture call as this would concern also OpenAPI in addition to Health and Metrics. I am thinking that if we write a TCK for the respecting context roots then not all runtimes would be able to pass.
