### ISSUE TITLE
Be able to generate only `kubernetes.yml` without building the whole app

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#37468]
### Description

As per [Deploying to Kubernetes](https://quarkus.io/version/main/guides/deploying-to-kubernetes), one can generate `kubernetes.yml` by executing `./mvnw clean package`, which also happens to do additional things.

Is it possible to generate only `kubernetes.yml` without building the .jar file, or is it necessary for the yml generation?

### Implementation ideas

To be able to generate it by running mvn/mvnw with an special argument

**Comment by geoand** [comment]
Currently it is necessary to do a proper build
