### ISSUE TITLE
Docs: security-oidc-bearer-token-authentication guide

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#37463]
### Describe the bug

Going through the [security-oidc-bearer-token-authentication](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication) guide I found some issues.
1. Links:
  \- `OIDC authorization code flow authentication` should be https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial
  \- Reference `Protect service applications by using OIDC Bearer token authentication` is there 2 times and one link show 404
2. It would be nice to mention that some of the snippets are from quickstart or Quarkus tests. As this can be for user nicer to just look if they are not sure what all should be set. I will mention this in some points in this issue. My point on this is that if we have it somewhere in Quarkus managed repository it can be linked.  And part of this point is that it can be said here is quickstart and you can extend by some of these snippets.
3. [Token Claims And SecurityIdentity Roles
](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#token-claims-and-security-identity-roles) Would be nice to have some showcase for example with existing quickstart. How would the `application.properties` would look with token claims.
4. [Token scopes And SecurityIdentity permissions](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#token-scopes-and-security-identity-permissions) code snippet missing the import of List. Also missing where is the Order class , how it should look. Search it in `quarkusio` organisation and didn't find anything. [Search](https://github.com/search?q=org%3Aquarkusio+%22listOrders%22&type=code). Maybe it's not needed in this snippet at all.
5. [JSON Web Token Claim Verification](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#jwt-claim-verification) snippet missing import of `jakarta.ws.rs.core.Response`
6. [Single page applications](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#single-page-applications) snippet no longer work with keycloak 22+ see [this](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc#legacy-promise-api-removed)
7. [Testing](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing) In general I would move part of the testing to [security-oidc-bearer-token-authentication-tutorial](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication-tutorial) as some of the showcase is part of the solution for that tutorial ([quickstart for it](https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-openid-connect-quickstart/src/test/java/org/acme/security/openid/connect)). Specifically  [Dev Services for Keycloak](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-keycloak-devservices) section. Think it base on this quickstart.
8. [Wiremock](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-wiremock)
\- `BearerTokenAuthorizationTest` missing static import `org.hamcrest.Matchers.equalTo`.
\- In this section can be said that it can extended the quickstart with some modification as `application.properties`
10. [OidcTestClient](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-oidc-test-client) missing definition of `client`. Probably it should be `oidcTestClient`. After that modification I have been unable to still run this test but probably some misconfiguration on my side. Error was `io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`. 
11. [KeycloakTestResourceLifecycleManager](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-keycloak)
\- Unused import `org.hamcrest.Matchers`. 
\- The `RestAssured.given().auth().oauth2(getAccessToken("alice"))))` have more bracket then expected should be 2 less bracket at the end.
\- how should be `/api/users/preferredUserName` setup. There would be nice to have link to the [UserResource](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc/src/main/java/io/quarkus/it/keycloak/UsersResource.java) where it is setup.
12. [Local Public Key](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-public-key) for showcase purpose it would be nice to add link to [privateKey.pem](https://github.com/quarkusio/quarkus/tree/main/integration-tests/oidc-tenancy/src/main/resources) as it say to get it from `integration-tests/oidc-tenancy`.
13. [TestSecurity annotation](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-security-annotation)
\- In `TestSecurityAuthTest` snippet is import `io.quarkus.test.security.oidc.ConfigMetadata`. It's not exist, looking on older Quarkus version probably this never exist + this import is never used in snippet. 
\- Both `ProtectedResource` snippets missing some imports [1].
14. [Authentication after HTTP request has completed](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#authentication-after-http-request-has-completed)
\- `OrderResource` missing `jakarta.ws.rs.HeaderParam` import
\- In both snippets is Product class. Not exactly know what structure should this class have. It should be [this one](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/Product.java) so maybe some link to this class or link to this set of test for more info would be nice.
\- `OrderService` missing the variable name for `SecurityIdentity`.

Personally thinking that the import should be there or the snippets shouldn't have any imports. Missing them is not a big deal but mention them here. For the point number 6. there should be probably decision which keycloak to mention in docs as in some guides is mention keycloak 17+ which will be working but for example the point 6 won't be working.

[1] Missing imports
```
import io.quarkus.security.Authenticated;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
```

**Comment by sberyozkin** [comment]
@jedla97 

>1. Links:
>- OIDC authorization code flow authentication should be https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication-tutorial

This is a concept (reference) guide so it links to the same type of document, a bearer token tutorial should be linking to the code flow tutorial.

I removed the old link leading to 404.

>2. It would be nice to mention that some of the snippets are from quickstart or Quarkus tests. As this can be for user nicer to just look if they are not sure what all should be set. I will mention this in some points in this issue. My point on this is that if we have it somewhere in Quarkus managed repository it can be linked...

Not sure about it as these links over time will be offset or return 404

>3.Token Claims And SecurityIdentity Roles: Would be nice to have some showcase for example...

I added an a token fragment where a role is set inside a JSON object and showed how `quarkus.oidc.roles.role-claim-path` has to be configured to point to it. Demoing other properties there would require reworking the tutorial.

>4.Token scopes And SecurityIdentity permissions... code snippet missing the import of List. Also missing where is the Order class , how it should look. ...

Fixed it.

>5.JSON Web Token Claim Verification snippet missing import of jakarta.ws.rs.core.Response

Fixed

>6.Single page applications snippet no longer work with keycloak 22+ see [this](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc#legacy-promise-api-removed)

I did not write the original one, so I'm not too familiar with the Keycloak JS adapter, can you propose an update for that script snippet ? Also CC @michalvavrik 

>7.Testing.. In general I would move part of the testing to security-oidc-bearer-token-authentication-tutorial as some of the showcase is part of the solution for that tutorial...

Not sure, this is only a reference doc and while I copy some code from other places here, this section is only meant to offer a list of available options, as opposed to giving some comprehensive tutorials, please open enhancement requests against the tutorial if you think it is necessary

>8.Wiremock: - BearerTokenAuthorizationTest missing static import org.hamcrest.Matchers.equalTo
- In this section can be said that it can extended the quickstart with some modification as application.properties

The import is there and as I said in the previous comment I'm not too keen to link to quickstarts from here

>9. OidcTestClient missing definition of client. Probably it should be oidcTestClient. After that modification I have been unable to still run this test but probably some misconfiguration on my side.

`oidcTestClient` is right there, as far as the error is concerned, please note it is not a tutorial, it only offers a description of this option in the concept/reference guide

>10. [KeycloakTestResourceLifecycleManager](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-keycloak)....

Fixed 2 code issues, but not sure actual endpoints have to be typed, not sure how it will help understand the described this test option   

>11.[Local Public Key](https://quarkus.io/version/main/guides/security-oidc-bearer-token-authentication#integration-testing-public-key) for showcase purpose it would be nice to add link to privateKey.pem

Done

>12. TestSecurity annotation - In TestSecurityAuthTest snippet is import io.quarkus.test.security.oidc.ConfigMetadata. It's not exist, looking on older Quarkus version probably this never exist + this import is never used in snippet.

This is used right there in the code and it is tested in Quarkus.

Fixed missing imports

>13. Authentication after HTTP request has completed...

Fixed code issues.

The main remaining issue IMHO is an obsolete Keycloak JS example - since we now recommend in docs to use at least 23.0.0 - however, I'm not 100% sure it is expected to work immediately - it gives an idea as opposed to offering a ready to use fragment. @jedla97, can you consider updating that JS fragment if you'd like ?

PR is on the way

Thanks

**Comment by sberyozkin** [comment]
@jedla97 

>Can it be something like: Some usage of the test snippets can be found in [security-openid-connect-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-openid-connect-quickstart) and it can be used as starting point for try these snippets.

I'm just not sure what is missing there that we need to keep linking to some code in the tests or tutorials, we already give a lot of information, users, even the beginners, can progress without these extra links. Please add more commits to the PR proposing such links if you'd like

>My point is here more about consistency then understanding.

Fair point, but then if we try to apply to all the doc it will probably become 30% bigger, and it is already massive. Again, users, even the beginners, are well capable of figuring out how to provide some test code, given N other examples provided everywhere, please add them to the PR if you'd like though

> Oidc client 

Yeah, see it, thanks for pointing it out

+1 to having a dedicated Keycloak Js issue

thanks
