### ISSUE TITLE
Make hibernate-jpamodelgen easier to apply to Quarkus 3.7+ projects

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#37477]
### Description

In Quarkus 3.7, Hibernate ORM's "JPAModelGen" annotation processor can no longer simply be dropped into the compile path as a "provided" dependency, because it now has dependencies of its own.

See #37460 and in particular 9e072ed3720fb50b04c69eeffbd3922707a3ace3:

>  Properly apply annotation processors in Panache-Hibernate extensions
>
> Unfortunately, HHH-17362 doesn't fix the problem,
> and it's unlikely that it will ever be fixed.
> See https://hibernate.atlassian.net/browse/HHH-17362?focusedCommentId=113465
> 
> We'll have to apply annotation processors the "right" way, as explained
> in https://github.com/hibernate/hibernate-orm/blob/6.3/migration-guide.adoc

Long story short, the proper way to use this annotation processor (and, really, annotation processors in general) is to add the processor, not to the compile path, but to the annotation processor path:

```xml
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <annotationProcessorPath>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.4.0.Final</version> <!-- This is required even with a BOM! See below -->
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                    <annotationProcessors>
                        <!-- Not sure this is strictly necessary; perhaps processors can be auto-detected -->
                        <annotationProcessor>org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor</annotationProcessor>
                    </annotationProcessors>
                </configuration>
            </plugin>
```

This is fine and [this is already what we recommend in the migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#jpamodelgen).

However, as documented in the migration guide, the BOM won't be applied to Maven's `annotationProcessorPath` entry and the version of `hibernate-jpamodel` will have to be specified explicitly by every application. That's inconvenient.

This should be solved in Maven Compiler Plugin version 3.12.0 (see https://issues.apache.org/jira/browse/MCOMPILER-391), but 3.11 was released back in February 2023 and the plugin hasn't seen a release since :/

**Comment by geoand** [comment]
I personally do not unfortunately

**Comment by FroMage** [comment]
Also note that there's #29068 to make this plugin run automatically, which is sorta also blocked pending help from the IDE folks.

**Comment by adampoplawski** [comment]
Hello
We are using Qurkus with Gradle and Kotlin and cannot make jpamodelgen work. It plan for 3.7 suport also including Kotlin+Gradle?

**Comment by famod** [comment]
FYI, release vote was started yesterday evening. So I think we can expect maven-compiler-plugin 3.12.0 very soon.

**Comment by yrodiere** [comment]
maven-compiler-plugin 3.12.0 and I've got reports that dependency management indeed works fine for `annotationProcessorPath` now.

We'll need to upgrade in Quarkus, and maybe add recipes to `quarkus upgrade` so that the Maven compiler plugin gets updated automatically in existing apps.

**Comment by yrodiere** [comment]
I updated the migration guide.

Still:

> We'll need to upgrade in Quarkus, and maybe add recipes to quarkus upgrade so that the Maven compiler plugin gets updated automatically in existing apps.

**Comment by yrodiere** [comment]
> FYI, this depMgmt version lookup does not seem to support relocations: [apache/maven-compiler-plugin#180 (comment)](https://github.com/apache/maven-compiler-plugin/pull/180#issuecomment-1876921475)
> 
> Edit: I probably should have posted this in #37477 instead. cc @yrodiere

Thanks @famod ; from what I understand this could easily be solved on our end by adding dependency management for `org.hibernate:hibernate-jpamodelgen`? Is that right?

**Comment by famod** [comment]
@yrodiere
> from what I understand this could easily be solved on our end by adding dependency management for `org.hibernate:hibernate-jpamodelgen`? Is that right?

Yes, that should work. But I don't think it should be there forever, should be dropped for 4.x at the latest (whenever that will be).

**Comment by gsmet** [comment]
> from what I understand this could easily be solved on our end by adding dependency management for org.hibernate:hibernate-jpamodelgen? Is that right?

Yeah, I had the same thought the other day. Let's do it and we can drop it at some point.

**Comment by yrodiere** [comment]
Ok, so to sum up:

1. We need to add dependency management for `org.hibernate:hibernate-jpamodelgen`
2. We might want to add something to `quarkus update` to migrate people away from the `provided` dependencies to `hibernate-jpamodelgen` and use `<annotationProcessorPaths>` instead (and equivalent for Gradle)... though I'm not sure this is easy.
3. If we do 2, we probably want to backport it to Quarkus 3.2 as well, because of #32615.

**Comment by gsmet** [comment]
We could probably handle 2. by having a look at https://docs.openrewrite.org/recipes/maven/changepluginconfiguration and create a custom recipe based on this code.

One other thing I was wondering: should we provide a codestart for Hibernate ORM to contribute the annotation processor config to the POM? Or do we want it to be kept optional?

**Comment by yrodiere** [comment]
> One other thing I was wondering: should we provide a codestart for Hibernate ORM to contribute the annotation processor config to the POM? Or do we want it to be kept optional?

Personally I'd wait and see how #37044 turns out, because right now we know such annotation processors won't be run again when restarting the app in dev mode, which leads to a poor dev experience. That's true regardless of how annotation processors are defined (`provided` or `annotationProcessorPaths`).

**Comment by FroMage** [comment]
I verified in #37044 that the latest plugin uses managed versions. But I'm stuck in `DevMojo` trying to find it for DEV mode :(

**Comment by FroMage** [comment]
Works now.

**Comment by gnodet** [comment]
> Hey @gnodet ,
> 
> Do you know if it would be possible to release a new Maven Compiler Plugin version or do you know someone who could trigger a release? We are eagerly waiting for https://issues.apache.org/jira/browse/MCOMPILER-391 to be released as it's really important for the Hibernate ORM annotation processor (see the description of the issue for the details).
> 
> Thanks!

Sorry guys, I just realized I was ping'ed on this issue.  If you need anything, let me know...

**Comment by FroMage** [comment]
@yrodiere I've merged #37044 (for Maven, not Gradle).

**Comment by yrodiere** [comment]
Thanks @FroMage! That'll definitely make Quarkus easier to use.

I created #38227 to address the last remaining problem we mentioned further up.

**Comment by yrodiere** [comment]
> > Hey @gnodet ,
> > Do you know if it would be possible to release a new Maven Compiler Plugin version or do you know someone who could trigger a release? We are eagerly waiting for https://issues.apache.org/jira/browse/MCOMPILER-391 to be released as it's really important for the Hibernate ORM annotation processor (see the description of the issue for the details).
> > Thanks!
> 
> Sorry guys, I just realized I was ping'ed on this issue. If you need anything, let me know...

Thanks :) I think we're good now, as Maven Compiler Plugin 3.12.1 behaves pretty much like we need it to :)
