### ISSUE TITLE
Redis Cache ttl default value invalid setting

### ISSUE THREAD

**Issue by OrdinarySF** [quarkusio/quarkus#37479]
### Describe the bug

https://github.com/OrdinarySF/redis-cache-default-ttl

This is a example. I will set a default "expire-after-write" value, but it is not work.

**Comment by gsmet** [comment]
We would need you to explain exactly what does not work?

**Comment by OrdinarySF** [comment]
According to the documentation on Redis Cache in Quarkus, directly setting `quarkus.cache.redis.expire-after-write` should establish a default cache expiration time. Hence, [I initially set it to 1h,](https://github.com/OrdinarySF/redis-cache-default-ttl/blob/main/src/main/resources/application.properties) but strangely, this setting didn't take effect. In the redis monitor mode, I observed that the commands sent from the application to Redis lacked the configured expiration time. To resolve this, I tried a different approach by specifying `quarkus.cache.redis.hello-cache.expire-after-write=1h`, indicating a 1-hour expiration time for a cache named `hello-cache`. Surprisingly, this time the expiration configuration for `hello-cache` worked. Upon delving into the [source code](io.quarkus.cache.redis.runtime.RedisCacheImpl), I discovered that quarkus-redis-cache only checks for `quarkus.cache.redis.XXXXXXXXXX.expire-after-write=1h`. If this value is not configured, it won't incorporate ttl into the Redis command construction. In my opinion, there should be an additional check for `quarkus.cache.redis.expire-after-write`, using it to configure the ttl code.

**Comment by cescoffier** [comment]
Thanks! Definitely a bug.

**Comment by gsmet** [comment]
This will be fixed in 3.6.2.

**Comment by gsmet** [comment]
@cescoffier I added the label to the PR before adding the comment :).
