### ISSUE TITLE
Quarkus Maven Plugin doc parameters are broken

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#37488]
### Describe the bug

Currently it uses the `name` which is not the actual parameter name as defined in the [doc](https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Parameter.html#name()) (name is when configuring from the pom.xml), it should use the `property` instead:
- https://github.com/quarkusio/quarkus/blob/main/devtools/maven/src/main/java/io/quarkus/maven/UpdateMojo.java#L72C4-L72C49
- https://github.com/quarkusio/quarkus/blob/main/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java#L105C20-L105C33

Because of this the doc parameters names a wrong:
- https://quarkus.io/guides/quarkus-maven-plugin#quarkus-maven-plugin-goal-update-rewriteupdaterecipesversion
- https://quarkus.io/guides/quarkus-maven-plugin#quarkus-maven-plugin-goal-add-extension-bomartifactid

We need to make sure the `@Parameter(property=...` is used in the doc when set (I would hope that the fieldName is used if not set).

### Expected behavior

Have the right parameter names in the doc

### Actual behavior

it uses the fieldName because `name` is not the actual name of the property at all, see:
https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Parameter.html#name()

**Comment by ia3andy** [comment]
ok after a bit of investigation it's not a simple, for some reason Maven didn't provide api to access the property.
Best solution might be to align properties and names (as name is used when configuring the plugin from the pom.xml)
https://stackoverflow.com/a/34659049

**Comment by mcruzdev** [comment]
Discussion about this issue:

https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.20Maven.20Plugin.20doc.20parameters.20are.20broken
