### ISSUE TITLE
Docs: security-getting-started-tutorial guide

### ISSUE THREAD

**Issue by gtroitsk** [quarkusio/quarkus#37499]
### Describe the bug

Found issues in https://quarkus.io/guides/security-getting-started-tutorial

1. In https://quarkus.io/guides/security-getting-started-tutorial#what-you-will-build
There is {ProductName} that should be Quarkus, I suppose

2. In https://quarkus.io/guides/security-getting-started-tutorial#create-the-maven-project
It says “To create a new Maven project with the Jakarta Persistence extension, complete one of the following steps”', but in the first step provided commands will only create a new project with provided groupId and artifactId. 
For example, command creating Maven project with Hibernate ORM must include the next option  
`-Dextensions='security-jpa'`

3. In[ https://quarkus.io/guides/security-getting-started-tutorial#write-the-application](https://quarkus.io/guides/security-getting-started-tutorial#write-the-application)
Before starting writing new classes, we need to add `resteasy-reactive` as project dependency to be able to use JAX-RS features in code. IMHO ideally if we include this dependency during the app creating step.

4. I see the next sentence twice: “Implement the /api/public endpoint to allow all users to access the application”.
In the second case, it refers to admin endpoint creation, so I suggest rewriting this.
“Implement an /api/admin endpoint that can only be accessed by users who have the admin role.”

5. In[ https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity](https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity)
Please add a note for guide readers: don’t forget to set up the Panache and PostgreSQL JDBC driver, please see https://quarkus.io/guides/hibernate-orm-panache#setting-up-and-configuring-hibernate-orm-with-panache

6. In https://quarkus.io/guides/security-getting-started-tutorial#configure-the-application
In 1. point,  please remove backtick from quarkus.http.auth.basic=true’

7. In https://quarkus.io/guides/security-getting-started-tutorial#test-your-application-by-using-dev-services-for-postgresql
 
 In the code example for `JpaSecurityRealmTest` wrong package name is using, in all    places in this guide I see `org.acme.security.jpa`, here it is `org.acme.elytron.security.jpa`.

 It’s needed to add next dependency to can import `io.restassured.RestAssured` and `org.hamcrest.core` into `JpaSecurityRealmTest`
```
<dependency>
     <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
</dependency> 
```

8. In https://quarkus.io/guides/security-getting-started-tutorial#use-curl-or-a-browser-to-test-your-application
Please add copy button as it is in all other code boxes

9. In https://quarkus.io/guides/security-getting-started-tutorial#compile-and-run-the-application
When running app in Native mode the next target must be used `./target/security-jpa-quickstart-1.0.0-SNAPSHOT-runner`

10. In https://quarkus.io/guides/security-getting-started-tutorial#use-curl-or-a-browser-to-test-your-application
I am suggesting to separate curl commands and its results because basically user want to copy only command, not with result :)

11. In https://quarkus.io/guides/security-getting-started-tutorial#results
	It says “it is not assigned to the "user" role, as shown in the following shell example”. Can we remove the word “shell” from this sentence?

**Comment by gtroitsk** [comment]
Also, https://github.com/quarkusio/quarkus/labels/area%2Fdocumentation

**Comment by gtroitsk** [comment]
@sberyozkin thank you for changes. I wrote additional explanation for some points

[1]  Maybe someone from technical writers will know how to fix it. This is no big problem at know, we can continue without change.

[2]  I understand these guide steps as two separate. If you want to create new project from scratch you use `quarkus create` or if you want to extend existing project you use `quarkus extension`. This is my personal preference, but I would specify that these extensions should be added to the newly created project not just for existing one.

[3]  It is still missing resteasy-reactive extension. I see other guides are listing these extension during creating application process. For example, https://quarkus.io/guides/security-oidc-auth0-tutorial#create-a-quarkus-application

[7]  `quarkus-junit5` is in project by default, so I think adding `rest-assured` is enough

[8]  I meant that button
![copy-button](https://github.com/quarkusio/quarkus/assets/94224856/de200bfd-962e-43c4-b141-d4070b696779)

[10]  I meant that user can copy (using copy button from 8. point), for example `curl -i -X GET http://localhost:8080/api/public` and run it without deleting its result "HTTP/1.1 200 OK" etc

**Comment by sberyozkin** [comment]
@gtroitsk I believe I have fixed 2 and 3 now. 
Re the copy button (points 8, 10) - if you have an idea how to add it - let me know please

**Comment by gtroitsk** [comment]
@sberyozkin For point 8, it will work by default, as it is written the same way as other bash code blocks. I don't know how to solve it. 
For point 10, I think we can split command and result to 2 code blocks, but to make this guide style consistent with other guides, I suppose to leave this as it is. 
For other points, I am ok
