### ISSUE TITLE
[Extension Proposal] Snappy compressor native

### ISSUE THREAD

**Issue by MarcAnB** [quarkusio/quarkus#37510]
### Description

I wrote this extension to enable the use of Snappy compressor in native environment.
Snappy compressor can be use in Mongo, Kafka or Parquet for example.

### Repository name

quarkus-snappy

### Short description

Snappy compressor in native environment

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-snappy/dev/

### Repository Topics

- quarkus-extension
- snappy-native

### Team Members

- @MarcAnB

### Additional context

Sources are here for now:
https://github.com/MarcAnB/quarkus-snappy

I am already using it and it works for me.

**Comment by gastaldi** [comment]
There is already support for Snappy in Kafka as in https://quarkus.io/guides/kafka#using-snappy-for-message-compression, but I believe this extension is for other use cases, right?

**Comment by gastaldi** [comment]
@MarcAnB repository created in https://github.com/quarkiverse/quarkus-snappy. For the next steps, see https://hub.quarkiverse.io/checklist/#after-the-repository-is-created.

**Comment by MarcAnB** [comment]
> There is already support for Snappy in Kafka as in https://quarkus.io/guides/kafka#using-snappy-for-message-compression, but I believe this extension is for other use cases, right?

Yep I use it in parquet files for example
https://www.javadoc.io/doc/org.apache.parquet/parquet-hadoop/1.10.1/org/apache/parquet/hadoop/codec/SnappyCodec.html

**Comment by MarcAnB** [comment]
I got code from Kafka extension to enable snappy but the integration tests are failing, not sure it is the right place to ask..

In Kafka extension there is a property that disable snappy for tests I think, how should I do here? Introducing a property doesn't really make sense to me since, if you use the extension, it is implicit that we want to load snappy.
