### ISSUE TITLE
Quarkus Jakarta Validation Bug / Unexpected behaviour

### ISSUE THREAD

**Issue by DudekJakub** [quarkusio/quarkus#37525]
### Describe the bug

Reproduction of jakarta validation bug.

Following page: https://quarkus.io/guides/validation

I copied most of the stuff from above page to check how Jakarta validation works. Seems like I stumble upon some unexpected behaviour where expected validation does not work. 

Please, give me some feedback if there is something I don't understand and therefor I'm making some silly mistake?

### Expected behavior

Controller 'BookResource' should not accept invalid dto 'Book' which all fields ought to be validated properly.

### Actual behavior

Given controller despite exptected validation (which seems to be working only for @NotNull annotation) accepts invalid dto 'Book'. Annotations such as @Valid, @NotBlank, @Size, @Min are being ignored.

### How to Reproduce?

Repository: [jakarta-validation-bug-reproducer](https://github.com/DudekJakub/jakarta-validation-bug-reproducer/tree/main)

Run the app and hit it's endpoints with:
a) INVALID dto:
{
  "title": "",
  "author": "",
  "pages": 0.0,
  "publishers": [
    {
      "name": "Scribner"
    }
  ]
}

b) VALID dto:
{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "pages": 180.0,
  "publishers": [
    {
      "name": "Scribner"
    },
    {
      "name": "Penguin Books"
    }
  ]
}

Also there are 2 IT written in /test, can check it as well.

### Output of `java -version`

java 17.0.8 2023-07-18 LTS

### Quarkus version or git rev

3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.4

**Comment by mschorsch** [comment]
I have seen that you are using Kotlin with data classes. To validate the fields you have to put the annotation on the field and not on the getter. 

Example: `@Valid` becomes `@field:Valid`.

Then everything should work.

see also https://quarkus.io/guides/kotlin#kotlin-jackson

**Comment by geoand** [comment]
What @mschorsch says 👌

**Comment by DudekJakub** [comment]
> I have seen that you are using Kotlin with data classes. To validate the fields you have to put the annotation on the field and not on the getter.
> 
> Example: `@Valid` becomes `@field:Valid`.
> 
> Then everything should work.
> 
> see also https://quarkus.io/guides/kotlin#kotlin-jackson

Thank you! My issue has been solved. Closing then :)

**Comment by mschorsch** [comment]
> @mschorsch could you contribute it? I'm not familiar enough with Kotlin to write something meaningful.

Yes. I will give it a try.
