### ISSUE TITLE
Docs: security-authorize-web-endpoints-reference Guide

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#37540]
### Describe the bug

Going through the [security-authorize-web-endpoints-reference](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference) guide I found some issues.

1. There is sentence `For more information, see Path Resolution in Quarkus.` which lead to Quarkus blog post from 2021. Not saying it's bad thing or problem, but blog can contain outdated information (I didn't read it). This blog post mentioning Quarkus 1.12.
2. There is `In the following example, SecurityIdentity is customized to add the same` where link is as this `` `SecurityIdentity` is customized``. It's not wrong but it seems kinda weird to have link with 2 colors. This is also in title of this section [Map SecurityIdentity roles](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#map-security-identity-roles).
3. The [Custom HttpSecurityPolicy](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#custom-httpsecuritypolicy) contains unresolved method `customRequestAuthorization`. It can't be said how this method should look. Similar method I found is in [CustomNamedHttpSecPolicy.java](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/security/CustomNamedHttpSecPolicy.java)
4. [Authorization using annotations](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#standard-security-annotations) second snippet of `SubjectExposingResource` class have unused `DenyAll` and `PermitAll` imports.
5. [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation) 
\- `LibraryService` missing import of `LibraryPermission.Library`.
\- `LibraryResource` don't have any import as only snippet in docs.
\- `MediaLibraryPermission` have unused imports.
\- `LibraryPermission` I understand this is long snippet so I agree to skip some content using `...` but I think that would be better use comment in sense `here override Permission methods and can implement your own`. Just for more guidance for reader.
6. [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation) maybe it would be nice to add command/test to show how to check if it's work.
7. [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation)  same part but it's better to be one point. After explaining the first property there is point `#4` which start `You can also specify a custom implementation of the java.security.Permission class`, in next paragraph it start with `You can also create a custom java.security.Permission class` and after we jump after the snippet there is `There must be exactly one constructor of a custom Permission class.` which is also mentioned in point `#4`. These 3 say lots of similar things which I don't say it's wrong but personally I would not use `also` in second occurrence.
8. [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation) last thing for this section is  when set `CRUDResource` by guide with the property `quarkus.http.auth.policy.role-policy2.permission-class=org.acme.crud.CRUDResource.CustomPermission` the Quarkus not start and throw error NoClassWasFound. I had package name correctly and tested it with Library example and when use `public static class <ClassName> extends Permission` inside of another class it still fail. So maybe this is bug or just not accepted solution.

**Comment by michalvavrik** [comment]
Good catch about unused imports, thanks.

> There is In the following example, SecurityIdentity is customized to add the same where link is as this  `SecurityIdentity` is customized. It's not wrong but it seems kinda weird to have link with 2 colors. This is also in title of this section [Map SecurityIdentity roles](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#map-security-identity-roles).

That's because the `SecurityIdentity` is code reference, I think we might need expertize of @quarkusio/documentation here, because I'm fine with it (that's why I wrote it that way).

> The [Custom HttpSecurityPolicy](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#custom-httpsecuritypolicy) contains unresolved method customRequestAuthorization. It can't be said how this method should look. Similar method I found is in [CustomNamedHttpSecPolicy.java](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/deployment/src/test/java/io/quarkus/vertx/http/security/CustomNamedHttpSecPolicy.java)

Because it depends on user how the method looks like. **I'll leave it to others to judge.** I wrote it this way to give a hint, it is not supposed to provide full implementation because in my eyes it's only a noise... it is supposed to tell you that you can do there something.

> 5. ...

I genuinely leave out imports and method implementations for brevity, docs could be really huge if we implement there everything. However in past days I read so many complains about this from QE team as I'm starting to think this view is probably not shared.

> [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation) maybe it would be nice to add command/test to show how to check if it's work.

I don't understand this part, can you elaborate? It works if endpoint is secured, so you can call it with / without credentials. That is same for all the security.

> [Permission annotation](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#permission-annotation) last thing for this section is when set CRUDResource by guide with the property quarkus.http.auth.policy.role-policy2.permission-class=org.acme.crud.CRUDResource.CustomPermission the Quarkus not start and throw error NoClassWasFound. I had package name correctly and tested it with Library example and when use public static class <ClassName> extends Permission inside of another class it still fail. So maybe this is bug or just not accepted solution.

We have tests for these examples (well, I sometimes renamed these classes and methods etc. but I created test for each example), maybe example needs to be updated, can you create reproducer please?

**Comment by jedla97** [comment]
> can you create reproducer please?
@michalvavrik Here is a reproducer:

1. `git clone -b permision-class-not-found git@github.com:jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `mvn clean quarkus:dev`

After testing it when the permission class is not nested but standalone it start without problem.

**Comment by jedla97** [comment]
> That's because the SecurityIdentity is code reference ...

Yes I understand. I mainly write what I spot while reading it. I personally don't have problem leave it as it is now.

>  genuinely leave out imports and method implementations for brevity, docs could be really huge if we implement there everything. However in past days I read so many complains about this from QE team as I'm starting to think this view is probably not shared.

In my POV it's more about consistency. I wouldn't have problem drop them all and don't have them across all guides. But believe when the imports are including they should be all included. Maybe this is point for future discussion. What I think when the imports are useful is when there are multiple implementation from different dependencies.

> I don't understand this part, can you elaborate? It works if endpoint is secured, so you can call it with / without credentials. That is same for all the security.

I know the authentication with request depends what type of security running in background but for example how would curl request looked like on some of the endpoint of `LibraryResource`. For example something like `curl -X PUT <add your header for authentication> <the actual data>`, where `<add your header for authentication>` would be on reader but `<the actual data>` would be in guide. I personally tried it (using keycloak) and fully not figured out what to send as data. Must say I have view of less experienced user so with this regard I maybe missing something.
I know this is it easier to say then done and show.

**Comment by michalvavrik** [comment]
> There is In the following example, SecurityIdentity is customized to add the same where link is as this  `SecurityIdentity` is customized. It's not wrong but it seems kinda weird to have link with 2 colors. This is also in title of this section [Map SecurityIdentity roles](https://quarkus.io/version/main/guides/security-authorize-web-endpoints-reference#map-security-identity-roles).

again, `SecurityIdentity` is reference to the class (code), so I'm not sure this should be changed, unless @quarkusio/documentation team shouts, I'll let it as it.

**Comment by michalvavrik** [comment]
> I know the authentication with request depends what type of security running in background but for example how would curl request looked like on some of the endpoint of LibraryResource. For example something like curl -X PUT <add your header for authentication> <the actual data>, where <add your header for authentication> would be on reader but <the actual data> would be in guide. I personally tried it (using keycloak) and fully not figured out what to send as data. Must say I have view of less experienced user so with this regard I maybe missing something.
I know this is it easier to say then done and show.

I understand what you mean now. This is not dependent on auth mechanism, your `SecurityIdentity` either has roles that you map to permissions or not. It's valid point though, I'll try something.
