### ISSUE TITLE
NullPointerException for request with empty Host header

### ISSUE THREAD

**Issue by querdenker2k** [quarkusio/quarkus#37554]
### Describe the bug

NPE when calling with Header "Host: "

### Expected behavior

No NPE

### Actual behavior

NPE is thrown inside vert.x

### How to Reproduce?

Create a Quarkus application and call with curl
`curl -iv -H "User-Agent:" -H "Accept:" -H "Host:" http://localhost:3186/q/health/live`

### Additional information

see https://github.com/quarkusio/quarkus/issues/36234

**Comment by mschorsch** [comment]
@cescoffier

**Comment by cescoffier** [comment]
Can you report this issue in Vert.x Core? Not much we can do here.

**Comment by querdenker2k** [comment]
Ok, done
https://github.com/eclipse-vertx/vert.x/issues/5011

**Comment by vietj** [comment]
that's actually missing host header in vert-web https://github.com/vert-x3/vertx-web/pull/2536

**Comment by querdenker2k** [comment]
@vietj thanks for the quick fix
