### ISSUE TITLE
Update smallrye-reactive-messaging to 1.0.3

### ISSUE THREAD

**Issue by nderwin** [quarkusio/quarkus#3758]
**Description**
A newer version of the library has been released and it would be great to take advantage of the changes, especially the new config item for using SSL for the AMQP connection.

**Implementation ideas**
Change the version property in the bom from 0.0.10 to 1.0.3.

**Comment by gwenneg** [comment]
The `smallrye-reactive-messaging` version was changed to `1.0.3` in #3746 a few days ago. Is there something to do in the extension code to take advantage of the new smallrye features?

**Comment by nderwin** [comment]
It doesn't look like anything specific would need updated, but it wouldn't hurt to get another opinion.

**Comment by kenfinnigan** [comment]
Closing as we're now on 1.0.8
