### ISSUE TITLE
Retrieving AMQP Messages returns 1000 messages and stops consuming

### ISSUE THREAD

**Issue by ArvinUbhi** [quarkusio/quarkus#37585]
### Describe the bug

When configuring the AMQP client and retrieving messages from the non-destructive AMQP queue using the @Incoming tag, it retrieves the first 1000 messages and then stops consuming. The amqp queue has more than 50k messages.

When trying the same mechanism in .Net, I am able to set the AMQP Source Distribution Mode to 'copy' which then allows me to retrieve all the messages from the AMQP queue. 

What is the best way to retrieve all messages from AMQP and if possible, how do I set the distribution mode attribute to the AMQP client configuration to 'copy'?

### Expected behavior

All messages from the queue are consumed and processed.

### Actual behavior

The first 1000 messages are consumed and processed and no more messages are received. 

### Output of `java -version`

17

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.2

**Comment by ArvinUbhi** [comment]
resources/application.properties

```
server.qdeamqusername=${QDE_AMQ_USERNAME:username}
server.qdeamqpassword=${QDE_AMQ_PASSWORD:password}
server.qdeamqhost=${QDE_AMQ_HOST:hostlink}
server.qdeamqport=${QDE_AMQ_PORT:443}
server.qdeamqsslenabled=${QDE_AMQ_SSL_ENABLED:true}
server.qdeamqreconnectattempts=${QDE_AMQ_RECONNECT_ATTEMPTS:100}
server.qdeamqreconnectinterval=${QDE_AMQ_RECONNECT_INTERVAL:1000}
server.qdeappsenvironment=${QDEFO_QDEAPPS_Environment:dev02-local}
# Configure the AMQP connector to read from the `queueDeal` queue
mp.messaging.incoming.queueDeal-in.connector=smallrye-amqp
mp.messaging.incoming.queueDeal-in.address=${QDE_LIVE_GRID_CASE_ADDRESS:bp-goil-fo-livegridqueue::bp-goil-fo-livegridqueue}
mp.messaging.incoming.queueDeal-in.batch=true
mp.messaging.incoming.queueDeal-in.failure-strategy=release
mp.messaging.incoming.queueDeal-in.durable=true
mp.messaging.incoming.queueDeal-in.client-options-name=qde-named-options
quarkus.tls.trust-all=true
```

**Comment by ArvinUbhi** [comment]
@cescoffier I have created a small repo to demonstrate this and included reproduction steps in the README. The code demos a small amqp consumer (MessageProcessor class) which feeds into a second class (MessagePostProcessor class). 

The MessagePostProcessor class counts the number of received messages from the amqp queue and prints the count. 

### Link to the repo: 
[AMQP Bug Repo](https://github.com/ArvinUbhi/amqpbug)

### Example output:
![image](https://github.com/quarkusio/quarkus/assets/117295982/50f3c790-4c35-40ca-96ba-fd90629533bb)

As you can see, the very last print of the count is 1000.

**Comment by cescoffier** [comment]
The repo does not explain which broker you use and how you insert the 1000+ messages.

**Comment by cescoffier** [comment]
Tried with:
```
 @Channel("sender")
    MutinyEmitter<String> emitter;

    public void init(@Observes StartupEvent event) {
        for (int i = 0; i < 2000; i++) {
            emitter.sendAndAwait("Hello");
        }
    }
```

No problem.

**Comment by ArvinUbhi** [comment]
@cescoffier I have added more information on the issue and steps to reproduce in the README. 

Just to reiterate, the issue surrounds **consuming** more than 1000 messages from an AMQP Artemis broker. 

Regarding how to load over 1000 messages, you could use your code above to load 2000/3000 messages beforehand.

**Comment by cescoffier** [comment]
It's what I did, I added 2000 messages in a queue, and then consumed them without any issue. I used the Artemis dev service.

**Comment by cescoffier** [comment]
Please explain how you configure Artemis. That might be the problem.

**Comment by cescoffier** [comment]
Can you update the reproducer with:

- how you configure and start Artemis
- avoid using TLS as it does not had anything (simpler the better)

**Comment by ArvinUbhi** [comment]
@cescoffier I noticed that the difference in the queue that I was consuming from is non-destructive. Messages in this queue are only removed once they expire. 

Please could you try and set up a non-destructive queue in your broker and try again. 

I believe the fix could be related to setting the distribution mode attribute but I am unsure how to do this in Quarkus.

**Comment by cescoffier** [comment]
I would need the proper instruction to do that (sorry, I'm not an Artemis expert).

**Comment by ArvinUbhi** [comment]
Sure @cescoffier - how are you configuring your Artemis queue? Are you doing it through a properties file (broker properties, address properties or address configurations) or are you using the AMQP UI?

Example of AMQP UI:
![image](https://github.com/quarkusio/quarkus/assets/117295982/feee352c-4c4a-4a64-a83e-4df8586daf17)

**Comment by cescoffier** [comment]
I started an artemis broker, configured the queue (anycast, durable) from the UI, sent 2000 messages to the queue (the UI confirmed they were there), and then, started the consumer - it got the 2000 messages. However, I didn't find how to configure a non-destructive queue (meaning that once consumed, the messages are gone).

Both my address and queue are marked anycast.

**Comment by ArvinUbhi** [comment]
@cescoffier Try to create a multicast nondestructive durable queue instead. 

With a non-destructive queue, messages are not removed when you acknowledge them. Messages usually would have an expiry and are removed by expiring. 

Here is the config that I have used (you'll have to change the address name and queue name):
```
   - addressConfigurations.addressName.queueConfigs.queueName.routingType=MULTICAST
   - addressConfigurations.addressName.queueConfigs.queueName.purgeOnNoConsumers=false
   - addressConfigurations.addressName.queueConfigs.queueName.durable=true
   - addressConfigurations.addressName.queueConfigs.queueName.nonDestructive=true
   - addressConfigurations.addressName.queueConfigs.queueName.redeliveryDelay=25000
   - addressConfigurations.addressName.queueConfigs.queueName.maxConsumers=-1
```

If you are doing this through a UI, you can set these settings when creating an address/ queue.

**Comment by cescoffier** [comment]
Hum, I can't setup non-destructive from the UI:

![image](https://github.com/quarkusio/quarkus/assets/402301/a10db74a-5630-40cd-9236-5dbd2151676b)


Then with the following configuration:

```
mp.messaging.incoming.incoming-queue.address=address-name::queue-name
mp.messaging.incoming.incoming-queue.failure-strategy=release
mp.messaging.incoming.incoming-queue.durable=true
```

I got everything consumed.

**Comment by cescoffier** [comment]
Pinging @gemmellr - any idea why we would be limited at 1000 in this case?

**Comment by ArvinUbhi** [comment]
@cescoffier If you create an AMQ queue through the UI you can select non-destructive.
First, select amq-broker:
![image](https://github.com/quarkusio/quarkus/assets/117295982/d68b9434-2d06-46ea-8277-589f884a2801)
Then, select Operations:
![image](https://github.com/quarkusio/quarkus/assets/117295982/2df5806c-57fa-4f20-bba3-1191f9499584)
Scroll down and select createQueue:
![image](https://github.com/quarkusio/quarkus/assets/117295982/a3f52964-881f-4f30-b42d-fb637e605978)
Add the queue details, and **select the non-destructive checkbox**:
![image](https://github.com/quarkusio/quarkus/assets/117295982/1cca3118-d050-48de-b5ad-fa18331177b6)

**This should be a multicast, durable, non-destructive queue.**

You can also select autoCreateAddress if needed. 

You can then load this queue with 2k/3k messages and try to reproduce the same steps.

**Comment by cescoffier** [comment]
Ok... so you need to invoke jmx action to setup that queue.

**Comment by ArvinUbhi** [comment]
Nope this could be set up in broker properties before starting the broker using the config I provided yesterday:
```
   - addressConfigurations.addressName.queueConfigs.queueName.routingType=MULTICAST
   - addressConfigurations.addressName.queueConfigs.queueName.purgeOnNoConsumers=false
   - addressConfigurations.addressName.queueConfigs.queueName.durable=true
   - addressConfigurations.addressName.queueConfigs.queueName.nonDestructive=true
   - addressConfigurations.addressName.queueConfigs.queueName.redeliveryDelay=25000
   - addressConfigurations.addressName.queueConfigs.queueName.maxConsumers=-1
```

OR if you have started your broker you can do it in the way I showed in the last message.

**Comment by gemmellr** [comment]
> Pinging @gemmellr - any idea why we would be limited at 1000 in this case?

I dont know, no, I've never used this functionality. I'd have to guess the broker is deciding not to send more for some reason or other. Maybe its failing to account for the 'non consuming' acknowledgement properly or something.

The original post notes also using a .net consumer with copy distribution mode...i.e specifically a 'queue browser' that is known not to consume. They didnt say what happens when they dont use copy distribution with the .net consumer. If its the same it could again point to the broker, not handling 'non broswers' as is being expected (whether its meant to, im not sure). That you seem to see different behaviour could again poing to the broker as its not clear the broker versions are the same.

**Comment by geoand** [comment]
Closing as we never got a reproducer that demonstrates the problem in action

**Comment by ArvinUbhi** [comment]
Hi @cescoffier @gemmellr - We have experienced this issue several times since I first raised it. This has happened in production and we have had to restart AMQ and our quarkus app to fix this. 

To reiterate, we have a quarkus service which drains a non-destructive AMQ queue. This service is not getting all of the messages. 

When we consume from a .net application, we are able to set the distribution mode property to copy and drain all of the messages from the queue. Without this property being set, we are getting the same number of messages as the quarkus application. 

This means that if we are able to set this property in our Quarkus AMQP reciever, we will be able to drain all messages.

For further infomation, the number of messages recieved by the quarkus app isnt always 1000, its any arbituary number eg 595. 

Please let me know if theres any more details that you think are important

**Comment by cescoffier** [comment]
Without a minimal standalone reproducer, I don't believe we will be able to understand the problem and fix it. 

I have tried reproducing it several times without any luck.
