### ISSUE TITLE
Native build fails with "Error: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl not loaded" with Quarkus 3.6.1

### ISSUE THREAD

**Issue by mdvcgn** [quarkusio/quarkus#37606]
### Describe the bug

Upgrading Quarkus from 3.5.3 to 3.6.1 with dependencies on `io.quarkus:quarkus-smallrye-reactive-messaging-kafka` and `io.strimzi:kafka-oauth-client` breaks native build with the following error message:

> [1/8] Initializing...                                                                                    (0.0s @ 0.11GB)
> Error: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
> com.oracle.svm.core.util.UserError$UserException: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
>	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1074)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:373)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:351)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1029)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:907)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:590)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
>	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)

This seems to originate from or has something to do with class `HasStrimzi` in dependency `io.quarkus:quarkus-kafka-client`

### Expected behavior

Build finishes successfully as before with Quarkus 3.5.3.

### Actual behavior

Native builds breaks with error message

> Error: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.

### How to Reproduce?

Steps to reproduce:

1. Create starter project with reactive Kafka client (quarkus-smallrye-reactive-messaging-kafka)
2. Add dependency `io.strimzi:kafka-oauth-client`
3. Conduct native build

### Output of `uname -a` or `ver`

Linux runner-a-j4vpp6-project-.....-concurrent-0t669r 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed Apr 27 20:34:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

MANDREL 23.1.1.0 JDK 21.0.1+12-LTS

### Quarkus version or git rev

3.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

**Comment by mdvcgn** [comment]
Thanks @ozangunalp for pointing this out, the workaround fixed my problem 👍

**Comment by cescoffier** [comment]
Closing this one here - as it's an upstream issue.
