### ISSUE TITLE
Skip performing content negotiation twice 

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#37637]
### Description

https://github.com/quarkusio/quarkus/blob/af6d3d75f882fe3a9969162bbd0ecc85450c7da6/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ClassRoutingHandler.java#L131

And

https://github.com/quarkusio/quarkus/blob/af6d3d75f882fe3a9969162bbd0ecc85450c7da6/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/FixedProducesHandler.java#L47

Both seems to verify that Accept and (some) mediaType matches, but the former just to send back a proper response (if unmatched), while the other to find the appropriate writer. 

### Implementation ideas

Probably would be better to merge them in one pass (on class routing) and just save somewhere the matched one, to allow the subsequent to pick it as a starting point to make faster verifying if the writer is fine.

Moreover, a first pass in the matching logic can be to find for wildcard types on accept, to skip any subsequent op.

**Comment by franz1981** [comment]
@geoand

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
I am trying  a change now

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/37646 should do the trick

**Comment by franz1981** [comment]
@geoand I think that's fine, buddy, thanks for looking into it: I'll answer in the PR than
