### ISSUE TITLE
Docs: security-authentication-mechanisms Guide

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#37645]
### Describe the bug

Going through the [security-authentication-mechanisms](https://quarkus.io/version/main/guides/security-authentication-mechanisms) guide I found some issues.

[Form-based authentication](https://quarkus.io/guides/security-authentication-mechanisms#form-auth) I personally thing this section can be improved. For me it wasn't perfectly clear if the client side verification by javascript was executed automatically when send request or it should be some kid of function/method which will connected to some kind of form. It should not clear from that example. Maybe point to some resource where it's possible to get more info about form base authentication. 
There would be nice to show like "traditional" way with form in html. 

Just small thing the link to [Duration#parse() javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)) should probably point to java 17 as Quarkus move to java 17.

Rest of the guide seems good and don't see any problem as more info about other mechanisms have own guide. Also I know that form base authentication is not primary type of authentication but for some smaller/entry project this can be go to type of authentication.

**Comment by jedla97** [comment]
> I don't understand this. The example shows login function that will be triggered by "onClick" Javascript event (for example).
This generally answering my question. So I know more how it works now.

For the PR thing. Yes I'll create it later this week.

**Comment by michalvavrik** [comment]
> > I don't understand this. The example shows login function that will be triggered by "onClick" Javascript event (for example).
> > This generally answering my question. So I know more how it works now.
> 
> For the PR thing. Yes I'll create it later this week.

Thanks!

**Comment by sberyozkin** [comment]
@jedla97 I've assigned to you, but if you'd like please remove this assignment, I've only done it because you said here you'd look at creating a PR

**Comment by melloware** [comment]
@jedla97 Are you going to submit a PR?

**Comment by jedla97** [comment]
@melloware sorry I forgot this issue. Now PR should be created.
