### ISSUE TITLE
Maps in ConfigMappings, that reference other ConfigMappings  

### ISSUE THREAD

**Issue by nicolaideffremo** [quarkusio/quarkus#37641]
### Describe the bug

When I define two ConfigMappings, where one references the other, maps are only parsed into one of the two config objects. 

The same works for primitives, lists and nested config interfaces.

### Expected behavior

Both config objects injected in the application contain equal value in their maps. 

### Actual behavior

One of the two configs only contains an empty map. It is not consistent which one. At least I could not find a pattern. 

### How to Reproduce?

I created a small [reproducer](https://github.com/nicolaideffremo/QuarkusConfigMappingReproducer) 

There are a few tests comparing the configuration values between the plain config and and another one referencing the plain config.   

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 LTS

### Quarkus version or git rev

3.6.1, but also tested with 3.2.9.Final, 2.16.9.Final and 2.13.9.Finall

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by rysurd** [comment]
Hello ! I'll have a look at it.
