### ISSUE TITLE
View cache Data in quarkus dev-ui (quarkus-cache)

### ISSUE THREAD

**Issue by guyruisseau** [quarkusio/quarkus#37642]
### Description

Hi,

 it is possible to visualize data cached from quarkus cache extension in the quarkus dev-ui ? I can visualiaze the count ouf elments but no the element cached. I found nothing about it in the documentation or i missed something...
I tried whith jVisualVm but I also found nothing

Thanks Guillaume

### Implementation ideas

Visualize data cache in the dev-ui

**Comment by mkouba** [comment]
I suppose that you want to show the cached keys and not the values, right?

**Comment by cescoffier** [comment]
Because the values can be complex objects, I'm not sure we can display anything.
Keys - no problem.

**Comment by guyruisseau** [comment]
The both :) But if you can't display value (as Json text for example), keys should be very usefull to start

**Comment by mkouba** [comment]
Yes, I'm working on a PR for keys...

**Comment by guyruisseau** [comment]
thank you, you are super efficient :)
