### ISSUE TITLE
Serialisers.findWriters primitive wrapper lookup performance

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#37656]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/37646's da11e0fa0ecb61cf8b295c1a6b2dcd66321f624f has by accident made quarkus to search for the writers in the hot path, making evident a possible performance improvement

![image](https://github.com/quarkusio/quarkus/assets/13125299/ab6e79ec-81c9-47e4-b45b-bd29558e0643)

Probably this is not supposed to be an hot path, but in case it will, it "could" be addressed at 

https://github.com/quarkusio/quarkus/blob/3c1d1a07967ed0ce99711c93e0d0b162980c0b44/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ServerSerialisers.java#L90

where's https://github.com/quarkusio/quarkus/blob/3c1d1a07967ed0ce99711c93e0d0b162980c0b44/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/core/Serialisers.java#L50

could be replaced by some different mechanism eg a chain of equality check guarded by Class::isPrimitive, which is an intrinsic.

**Comment by geoand** [comment]
I am also wondering if `findResourceWriters` can be improved while maintaining the semantics...
