### ISSUE TITLE
Clarify behavior of interceptors/alternatives without @Priority

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#3767]
We do state that the contents of a `beans.xml` file is ignored. However, we don't say what happens if your app contains a interceptor/alternative without `@Priority`.

The current behavior is:
- an interceptor without `@Priority` is enabled and has a default priority of value `0` - `javax.interceptor.Interceptor.Priority.PLATFORM_BEFORE`
- an alternative bean without `@Priority` is not an alternative, but is considered a regular bean

I'm not quite sure whether this behavior makes sense though. From compatibility POV we should probably ignore such interceptors and disable such alternatives. From usability POV it could make sense to keep the interceptors behavior but disable such alternatives.

@manovotn ideas?

In any case, we should add some tests to cover this use case.

**Comment by manovotn** [comment]
To sum up the discussion from Zulip:

I proposed to fail fast (throw exception) on finding alternatives/interceptors without priority.
Martin thought that might be too strict (at least for interceptors) and therefore we could keep the default behaviour as is and log a warning to user in order not to promote this approach.
