### ISSUE TITLE
Support mounting host file/directory to devservices containers

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#37684]
### Description

[Testcontainers](https://java.testcontainers.org/) has API to copy/mount file/directory to containers:

```java
continer.withCopyFileToContainer(MountableFile.forHostPath("/mappable-resource/"), directoryInContainer);
```

See: [Testcontainers for Java: Files and volumes](https://java.testcontainers.org/features/files)

---

One possible usage is to add Keycloak extension to Keycloak devservices by copying the extension jar files to `/opt/keycloak/providers`.

### Implementation ideas

It can be added to app configurations, something like:

```properties
quarkus.keycloak.devservices.mount=./extension/jars:/opt/keycloak/providers
```

**Comment by geoand** [comment]
I think it makes sense. WDYT @sberyozkin?

**Comment by sberyozkin** [comment]
@geoand Sure, makes sense

@Eng-Fouad As far as the Keycloak dev service is concerned,

FYI, in this PR, https://github.com/quarkusio/quarkus/pull/36508/files#diff-67404a43520250b1ebd5a0c945e070e60d70d4a3ba06b15e3fac747f820320ccR541

I'm attempting to attach a specific classpath or file system file to a required container location (there a generated policy jar has to be coped), can that help with your requirements ? Note I'm using 2 maps there, one creates aliases to the local resources, another maps these aliases to container locations - I'm not 100% sure having a single Map to map for ex a Windows path to the container resource can work without resorting to various escape tricks...

**Comment by Eng-Fouad** [comment]
> @geoand Sure, makes sense
> 
> @Eng-Fouad As far as the Keycloak dev service is concerned,
> 
> FYI, in this PR, https://github.com/quarkusio/quarkus/pull/36508/files#diff-67404a43520250b1ebd5a0c945e070e60d70d4a3ba06b15e3fac747f820320ccR541
> 
> I'm attempting to attach a specific classpath or file system file to a required container location (there, a generated policy jar has to be copied), can that help with your requirements ? Note I'm using 2 maps there, one creates aliases to the local resources, another maps these aliases to container locations - I'm not 100% sure having a single Map to map for ex a Windows path to the container resource can work without resorting to various escape tricks...

Yes, this seems what I am looking for.

**Comment by sberyozkin** [comment]
@Eng-Fouad OK, thanks, let me have that PR to fix this issue on its completion.
I guess we will be easily able to map the whole directories if it will be necessary as a follow up to that PR
