### ISSUE TITLE
Documentation refers to old quay.io/strimzi/kafka images

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#37687]
### Describe the bug

Documentation refers to old quay.io/strimzi/kafka images

For example it is referring to [quay.io/strimzi/kafka:0.22.1-kafka-2.7.0](http://quay.io/strimzi/kafka:0.22.1-kafka-2.7.0) which is almost 3 years old. And there is even older version mentioned in kafka-streams.adoc for example.

```java
git grep "strimzi/kafka"
docs/src/main/asciidoc/kafka-reactive-getting-started.adoc:    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
docs/src/main/asciidoc/kafka-reactive-getting-started.adoc:    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
docs/src/main/asciidoc/kafka-schema-registry-avro.adoc:    image: quay.io/strimzi/kafka:0.22.1-kafka-2.7.0
docs/src/main/asciidoc/kafka-schema-registry-avro.adoc:    image: quay.io/strimzi/kafka:0.22.1-kafka-2.7.0
docs/src/main/asciidoc/kafka-streams.adoc:    image: strimzi/kafka:0.19.0-kafka-2.5.0
docs/src/main/asciidoc/kafka-streams.adoc:    image: strimzi/kafka:0.19.0-kafka-2.5.0
docs/src/main/asciidoc/kafka.adoc:        @ResourceArg(name = "strimzi.kafka.image", value = "quay.io/strimzi/kafka:0.28.0-kafka-3.0.0"), // Image name

integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/KafkaKeycloakTestResource.java:        this.kafka = new StrimziKafkaContainer("quay.io/strimzi/kafka:latest-kafka-3.0.0")
```

CC @scholzj, is there a plan/activity on the Strimzi side to look into the Quarkus/Strimzi story with some guarding of the used versions and images?

### Expected behavior

Users should be pointed to the newer versions of strimzi/kafka images

### Actual behavior

Documentation point to quite a legacy versions of strimzi/kafka images

### How to Reproduce?

`git grep "strimzi/kafka"` in Quarkus main

### Quarkus version or git rev

Quarkus main

**Comment by scholzj** [comment]
> @scholzj, is there a plan/activity on the Strimzi side to look into the Quarkus/Strimzi story with some guarding of the used versions and images?

To be honest, I'm not aware that these things are used across Kafka documentation (or, well, I was not aware of it until this issue). So there is no plan.

The Test Container is an official part of the Strimzi project. @see-quick is the main owner of it. That can probably be easily updated.

The Docker Compose is not part of Strimzi - it is likely based on my [personal experiment](https://github.com/scholzj/strimzi-compose-up). I think it is easy to just update the versions and the docker compose part should work. It would be probably more time-consuming to test all the related docs around it. But they should probably not break as Kafka clients have a good backwards compatibility.

**Comment by scholzj** [comment]
I opened https://github.com/quarkusio/quarkus/pull/37953 to update the images. There is one test that seems to use an old image to test the OAuth authentication in Kafka. That is currently not supported by the Strimzi Test Container. I opened https://github.com/strimzi/test-container/issues/63 to fix this, but that can be updated only once it is implemented in Strimzi.

**Comment by rsvoboda** [comment]
Thanks @scholzj!
