### ISSUE TITLE
Docs: security-jdbc guide and security-jdbc-quickstart

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus#37682]
### Describe the bug

I went through https://quarkus.io/version/main/guides/security-jdbc and found the following issues:

1. In the "Configuring the Application" section, a clear-text password is used in the INSERTS command SQL script. There is a note reminding us not to store clear-text passwords in production environments. Additionally, it is mentioned that the elytron-security-jdbc offers a built-in bcrypt password mapper. However, it would be great to show how to implement this or link to another source demonstrating the process.
2. It would be beneficial to mention in the "Testing Application" section how to start the database. For example, using a docker-compose YAML file and then executing docker-compose up would be a helpful addition.
3.  It seems the quickstart example has some updates and slightly differences between the example guide, for instance the SQL script (https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-jdbc-quickstart/import.sql) has got this added lines: 
`CREATE ROLE quarkus WITH LOGIN PASSWORD 'quarkus';
CREATE DATABASE elytron_security_jdbc;
GRANT ALL PRIVILEGES ON DATABASE elytron_security_jdbc TO quarkus;
\c elytron_security_jdbc`

and the docker-compose.yml to start the database (as I mentioned in the point 2)

**Comment by jcarranzan** [comment]
Also,[ area/documentation](https://github.com/quarkusio/quarkus/labels/area%2Fdocumentation)

**Comment by michalvavrik** [comment]
> In the "Configuring the Application" section, a clear-text password is used in the INSERTS command SQL script. There is a note reminding us not to store clear-text passwords in production environments. Additionally, it is mentioned that the elytron-security-jdbc offers a built-in bcrypt password mapper. However, it would be great to show how to implement this or link to another source demonstrating the process.

There is an example https://es.quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity and this guide is linked from the guide you reviewed.

> It would be beneficial to mention in the "Testing Application" section how to start the database. For example, using a docker-compose YAML file and then executing docker-compose up would be a helpful addition.

That's Quarkus job, starting database would lower user experience. No action is required.

**Comment by jcarranzan** [comment]
From my point of view, placing the link you mention (https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity) right where security is discussed with the built-in bcrypt password assigner would be appropriate.

**Comment by michalvavrik** [comment]
> From my point of view, placing the link you mention (https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity) right where security is discussed with the built-in bcrypt password assigner would be appropriate.

Sure, I agree, please create PR and place link there. Thanks!

**Comment by michalvavrik** [comment]
> It would be beneficial to mention in the "Testing Application" section how to start the database. For example, using a docker-compose YAML file and then executing docker-compose up would be a helpful addition.

Database is started by Dev Services for PostgreSQL in case of this quickstart.

**Comment by jcarranzan** [comment]
> > It would be beneficial to mention in the "Testing Application" section how to start the database. For example, using a docker-compose YAML file and then executing docker-compose up would be a helpful addition.
> 
> Database is started by Dev Services for PostgreSQL in case of this quickstart.

ok but in the quickstart example, but not follow the guide doc steps from scratch, because of that I've edited it in the description of the bug.

**Comment by michalvavrik** [comment]
> > > It would be beneficial to mention in the "Testing Application" section how to start the database. For example, using a docker-compose YAML file and then executing docker-compose up would be a helpful addition.
> > 
> > 
> > Database is started by Dev Services for PostgreSQL in case of this quickstart.
> 
> ok that is in the quickstart example, but not follow the guide doc steps from scratch, because of that I've edited it in the description of the bug.

thanks

**Comment by jcarranzan** [comment]
> > From my point of view, placing the link you mention (https://quarkus.io/guides/security-getting-started-tutorial#define-the-user-entity) right where security is discussed with the built-in bcrypt password assigner would be appropriate.
> 
> Sure, I agree, please create PR and place link there. Thanks!

PR created https://github.com/quarkusio/quarkus/pull/37771

**Comment by jcarranzan** [comment]
According comments above this could be closed.
