### ISSUE TITLE
Extra INFO log in Hibernate ORM HHH10005004: Stopping BeanContainer : %s

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#37735]
### Describe the bug

This log appears at least in some cases when stopping the application (in my case when config validation fails on native startup):

```
Dec 14, 2023 11:34:05 AM org.hibernate.resource.beans.container.spi.AbstractCdiBeanContainer stop
INFO: HHH10005004: Stopping BeanContainer : %s
```

It's pointless, and badly formatted. We should drop it, or at least make it a DEBUG log.

### How to Reproduce?

I guess this happens with just about any app using Hibernate ORM, but here's where I noticed it: https://github.com/yrodiere/quarkus-playground/tree/i36376
Just change the Quarkus version to 999-SNAPSHOT and run `mvn clean verify -Dnative`.

**Comment by gsmet** [comment]
Probably a good idea to add it to the filter list here: `HibernateLogFilterBuildStep`.

**Comment by Sanne** [comment]
I'll add it to the filter and fix in ORM
 - https://hibernate.atlassian.net/browse/HHH-17659

**Comment by Sanne** [comment]
Actually, it's already in the filters since a couple of years, odd:
 - https://github.com/quarkusio/quarkus/blob/7736c2ed4b479900f7697e50563f0817c90bc32f/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateLogFilterBuildStep.java#L29

Might not be as trivial as I thought :) Anyway, fixed ORM upstream.

**Comment by yrodiere** [comment]
Maybe `LogCleanupFilterBuildItem` applies to a sepecific logger, not all loggers with the given prefix?

Anyway... thanks Sanne. This should be fixed in Quarkus when https://hibernate.atlassian.net/browse/HHH-17659 gets fixed, which I *think* should be in Hibernate ORM 6.4.3.

**Comment by yrodiere** [comment]
> Anyway... thanks Sanne. This should be fixed in Quarkus when https://hibernate.atlassian.net/browse/HHH-17659 gets fixed, which I _think_ should be in Hibernate ORM 6.4.3.

Update: this is going to ORM 6.5.
