### ISSUE TITLE
Native Build vs. Runtime Profiles Mismatch and Doubled-Up Using Parent Profile

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#37747]
### Describe the bug

Performing a native build using `mvn package -Pnative -Dquarkus.profile=prod,kubernetes` seems to add the parent profile and doubles it when running.

It seems to be related to profiles that have a `parent` profile because running single profiles does not produce the warning.

As far as I can recall this only started recently because we have not seen the warning before in the logs.

```
2023-12-14 09:50:53,973 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile '[kubernetes, cluster, prod]' used to build the native image is different from the runtime profile '[kubernetes, cluster, prod, cluster]'. This may lead to unexpected results.
```

### Expected behavior

That the runtime would use the same profiles as build time and produce a message more like:
`2023-12-14 10:04:17,979 INFO  [io.quarkus] (main) Profile prod activated.`)`

### Actual behavior

A warning on startup appears when a profile seems to use a parent profile.

```
2023-12-14 09:50:53,973 WARN  [io.qua.run.con.ConfigRecorder] (main) The profile '[kubernetes, cluster, prod]' used to build the native image is different from the runtime profile '[kubernetes, cluster, prod, cluster]'. This may lead to unexpected results.
```

### How to Reproduce?

**To get the warning:**
1. `mvn package -Pnative -Dquarkus.profile=prod,kubernetes`
2. Run the generated native executable in the target folder.
3. Has the warning

**Not getting the warning:**
1. `mvn package -Pnative -Dquarkus.profile=prod`
2. Run the generated native executable in the target folder.
3. No warning (`2023-12-14 10:04:17,979 INFO  [io.quarkus] (main) Profile prod activated.`)

[code-with-quarkus2.zip](https://github.com/quarkusio/quarkus/files/13674965/code-with-quarkus2.zip)

### Output of `uname -a` or `ver`

ubuntu

### Output of `java -version`

17

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9

### Additional information

It is not harming anything just appears in our logs

**Comment by geoand** [comment]
cc @radcortez
