### ISSUE TITLE
Optaplanner Platform BOM missing for 3.5+

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#37754]
### Describe the bug

I don't see any entries (nor can I pull them) for `io.quarkus.platform:quarkus-optaplanner-bom` in Maven. Maybe this was planned, but I see no documentation about it in https://quarkus.io/blog/quarkus-3-5-0-released or https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5.

**Comment by ge0ffrey** [comment]
Possible related issue: https://github.com/quarkusio/quarkus/pull/36412

Also, OptaPlanner was forked as [Timefold](https://timefold.ai/blog/2023/optaplanner-fork).
The `timefold-solver-quarkus` extension works on the latest version of Quarkus.

**Comment by gsmet** [comment]
Yeah, agreed, you'd better use Timefold now but the OP has a point that I should have documented this. It was done in the Platform thus why I missed adding it to the migration guide.

Will do.

**Comment by gsmet** [comment]
Done!

**Comment by ge0ffrey** [comment]
@gsmet Thank you. Any chance you would consider adding a Timefold guide? See this PR: https://github.com/quarkusio/quarkus/pull/36588 - I understand if you don't.

**Comment by gsmet** [comment]
> Any chance you would consider adding a Timefold guide?

Ah, yes, sorry, I completely forgot to answer you there. Ideally, I would prefer if you were publishing the doc on your side and if we added a link to it. Maintaining external guides in our doc has been a bit tedious.

I think we can do that (add a link), at least we could but things have changed since I added this feature. I will check and get back to you.

**Comment by ge0ffrey** [comment]
> I would prefer if you were publishing the doc on your side and if we added a link to it. Maintaining external guides in our doc has been a bit tedious.

@gsmet That's sounds good - that way we don't have to duplicate the guide. Our Quarkus guide is here: https://timefold.ai/docs/timefold-solver/latest/quickstart/quarkus/quarkus-quickstart
