### ISSUE TITLE
GarbageCollector not working properly after update to Quarkus 2.13.3.Final

### ISSUE THREAD

**Issue by mbrembilla** [quarkusio/quarkus#37756]
### Describe the bug

The application is a simple micro-service that exposes some REST endpoints to query a MongoDB.

I'm experiencing a strange GC behaviour in my application after updating to Quarkus 2.13.3.Final.
After some time from the start of the application, the GC triggers and I can see the CPU usage increase.
Unfortunately it seems that it get stucks because the memory isn't freed and the cpu usage remains high.
Eventually the heap size exceed its limit and the pod (I'm deploying my app on Kubernetes) exit with code 137 (OOM).

I added -XX:+PrintFlagsFinal to java command and noticed this interesting difference btw the two versions:
| Quarkus | 1.2.1.Final | 2.13.3.Final |
|--------|--------|--------|
| ParallelGCThreads | 1 | 4 |

Here's some screenshots to better understand what I'm talking about:

<img width="1348" alt="cpu" src="https://github.com/quarkusio/quarkus/assets/32509418/00505ec4-7d3c-46c9-bd34-ede100095222">
<img width="1361" alt="memory" src="https://github.com/quarkusio/quarkus/assets/32509418/29f47161-bf78-4a50-a8ca-fbbc8c99eda7">
GC Time Total
<img width="1457" alt="base_gc_time_total" src="https://github.com/quarkusio/quarkus/assets/32509418/7100266b-6af1-436d-94de-e11c0ed0ab94">

I update many "aspects" of my application recently:
| Name | From | To |
|--------|--------|--------|
| Quarkus | 1.2.1.Final | 2.13.3.Final |
| Java | 8 | 11 |
| Maven Wrapper | 3.6.3 | 3.8.6 |

I hope the issue is clear
If you need further information I will gladly provide them

### Expected behavior

The GC should keep the heap size small

### Actual behavior

The GC starts running using CPU but it seems that is doesn't free memory

### Output of `uname -a` or `ver`

Linux <PODNAME> *.*.*.*.amzn2.x86_64 #1 SMP <DATE> x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
Did you also update Java versions?

**Comment by mbrembilla** [comment]
Yes, as I wrote in the recap table I update Java from 8 to 11

**Comment by gsmet** [comment]
It's far too early to know if it's a Quarkus problem, something in your app or related to the Java upgrade.

First, upgrade to the latest 2.13 which is 2.13.9.Final.

Then, it is probably a good idea to:
- do a heap dump when the memory usage is high or use `-XX:+HeapDumpOnOutOfMemoryError` and inspect it with VisualVM for instance
- it might also be an allocation issue and in this case https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md might help. There is a paragraph about allocation profiling (but you need to do the prerequisites first).

Start with the heap dump as it's the easiest and go from there.

If it ends up being a Quarkus problem (it might be!), you can reopen this issue and provide us with the information and we will be happy to have a look. But for now, it could also be a problem with your app or anything else.
