### ISSUE TITLE
Rest client does not support other primitive response types when filter like OIDC client filter is used after optimization of primitive checks

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#37776]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/37655 causes problems when our reactive REST client is also `@OidcClientFilter`  as return type `boolean` is not supported for `text/plain` anymore.

### Expected behavior

`boolean` is valid `text/plain` response type as is when `@OidcClientFilter` is not used

### Actual behavior

An exception is thrown `jakarta.ws.rs.ProcessingException: Response could not be mapped to type boolean for response with media type text/plain;charset=UTF-8`

### How to Reproduce?

1. `git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite`
3. `mvn clean verify -f security/keycloak-oidc-client-reactive-extended/ -Dit.test=OidcRestClientIT#testAutoAcquireToken`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by michalvavrik** [comment]
fyi @sberyozkin

**Comment by geoand** [comment]
So I assume that before https://github.com/quarkusio/quarkus/pull/37655 was included the test worked just fine?

**Comment by franz1981** [comment]
I'm using a smaller reproducer with this

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/greetingTrue}")
    public boolean greetingTrue() {
        return true;
    }

```
To see what's changed, because maybe it's my friday brain but I cannot see why is behaving differently from the original one

**Comment by michalvavrik** [comment]
> So I assume that before #37655 was included the test worked just fine?

Yes, I tried hard to find actual cause, not to point to random PR :-)

**Comment by geoand** [comment]
Thanks for pinpointing it!

I can have a look on Monday

**Comment by geoand** [comment]
I am pretty sure I know what the problem is, but I have to drop early today so this will have to wait until Monday (or if I am lucky, Sunday)

**Comment by franz1981** [comment]
@michalvavrik before calling the day I've verified the test is passing with the pr at https://github.com/quarkusio/quarkus/pull/37778,  which is indeed my wrong interpretation of the original code behaviour

**Comment by michalvavrik** [comment]
> @michalvavrik before calling the day I've verified the test is passing with the pr at #37778, which is indeed my wrong interpretation of the original code behaviour

Thanks for super quick fix! And for letting me know, I won't disable tests on our side then.

**Comment by geoand** [comment]
I'm going to take a closer look on Monday

**Comment by michalvavrik** [comment]
closing as fixed by https://github.com/quarkusio/quarkus/pull/37788
