### ISSUE TITLE
Scheduler start-mode enum not shown properly in scheduler config reference

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#37818]
### Describe the bug

In this page; https://quarkus.io/guides/scheduler-reference. The text of [quarkus.scheduler.start-mode](https://quarkus.io/guides/scheduler-reference#quarkus-scheduler_quarkus.scheduler.start-mode) is not shown properly

### Expected behavior

tooltip should be shown when we hover over the type, only the first element of the enum seems to show ok.

### Actual behavior

tooltip text shown not be shown unless item is hovered on.

### How to Reproduce?

n/a

**Comment by mkouba** [comment]
CC @michalvavrik

**Comment by michalvavrik** [comment]
looks like #37202 didn't work for some case, I'll check what is wrong
