### ISSUE TITLE
Performance on MacBook pro

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#3782]
Hi,
I was wondering what is the throughput you're getting when using quarkus on MacOS?
When I was using full blown application server on my old Ubuntu desktop, with simple JAX-RS GET method returning "hello", I got to 3-4k res/sec (but I could go higher with different configuration).

I get much lower response times (~200 res/sec) on my MacBook pro. Did anyone experience the same results? Did you do anything to solve it ?

**Comment by machi1990** [comment]
localhost lookup can be slow on mac, have you added a /etc/hosts entry ? See https://thoeni.io/post/macos-sierra-java/ for details.

**Comment by FreifeldRoyi** [comment]
Unfortunately it didn't work 😭

**Comment by emmanuelbernard** [comment]
We have had no such report and quite a few of us are on macOS. I don't know what it is but I'd argue for a specificity of your OS setup. You said you tried on two different MBP? Also how you inject and measure might have a glitch

**Comment by FreifeldRoyi** [comment]
> We have had no such report and quite a few of us are on macOS. I don't know what it is but I'd argue for a specificity of your OS setup. You said you tried on two different MBP? Also how you inject and measure might have a glitch

Old desktop Ubuntu, and my current MBP.
I used (in both cases) JMeter & Apache Bench. They run from the same computer the application server or quarkus were running on

**Comment by stuartwdouglas** [comment]
How old is the MBP and what are you doing to drive the load? I can get 40k+ on my 2015 model, even 3-4k is not very good for such a simple endpoint.

**Comment by FreifeldRoyi** [comment]
2016 MBP.
jmeter with 10 threads looping forever

**Comment by FreifeldRoyi** [comment]
what are the ulimit values set on your computer?

**Comment by jaikiran** [comment]
I'm pretty sure this has something to do with the "localhost" host mapping entries. I have had similar issues (not just with Quarkus but with Java apps in general on my spare MacBook) and I had to sort out my `/etc/hosts` entries to get past it. Can you show us your `/etc/hosts` entries and also the output of the following command, both from your MacBook pro:

```
hostname
```
