### ISSUE TITLE
grpc server closing connection with GOAWAY

### ISSUE THREAD

**Issue by firdy94** [quarkusio/quarkus#37826]
### Describe the bug

When the grpc client is communicating with the grpc server, the connection gets closed prematurely with the following exception: 
![image](https://github.com/quarkusio/quarkus/assets/70014203/1291040c-dff3-4b2c-ab3e-a0e8ccc5321c)
RESOURCE_EXHAUSTED: Connection closed after GOAWAY. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings. Seems to be happening sporadically, and unable to determine the cause of this. Thank you for your time!

### Expected behavior

The connection should be closed normally.

### Actual behavior

Connection getting closed prematurely by grpc server and no response being received.

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

17

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.6.1

**Comment by cescoffier** [comment]
Hard to say without a reproducer.
Any way to can tell us more about your setup and provide a simple reproducer?

**Comment by geoand** [comment]
Closing for a lack of a reproducer
