### ISSUE TITLE
Http 2 Authority's URI validation in the hot path

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#37835]
Currently HTTP 2 perform malformed authority URI checks and multiple headers lookups in the request handling's hot path

This is currently addressed by https://github.com/eclipse-vertx/vert.x/pull/5038

This turn to be one of the most relevant costy behaviours between Http 1.1 and Http 2, although in quarkus we do perform URI validation [as well (per-request!)](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L148), but with a significant difference: we only check the request's uri eg on `http://localhost:8080/hello` just the `/hello` part.
In HTTP 2 instead, the check is performed with a more complex part ie the whole authority `localhost:8080` which "trigger" a more costy behaviour on `java.net.URI`.

The pull requests referenced is addressing this by:
- making the validation so cheap that is fine to always perform it (kudos to @vietj for it)
- reducing the amount of lookups in the Http 2 headers map, which are not cheap and "hidden" under stealhy API surface which make them to appear as normal field lookups

This issue is one of the reason behind the performance diff between Http 1 vs 2 and is very specific of Vertx, that's why other servers based on Netty couldn't hit it.

Just for reference, URI validation in Http 1.1 is just a nop, in term of cost, while for a simple plaintext hello world endpoint it looks like this (the check is in violet):

![image](https://github.com/quarkusio/quarkus/assets/13125299/06eaedb0-5117-47fc-ad57-6fc2fc2e9bad)

which is about 8-10% of the overall cpu usage, compared to ~0% for http 1.1

The same applies if the payload to send is ~4K (which is quite big):

![image](https://github.com/quarkusio/quarkus/assets/13125299/e56ec666-ae09-4ea2-b317-eaa7dcdc6efc)

In which case is approx 5%.

The pr mentioned above is fixing/improving stream setup/creation as well, still affected by the cost of accessing pseudoheaders more than necessary.

Although the gain in term of percentage seems tiny, they should be considered for the parts Quarkus/Vertx is responsible for ie the green part. In such case the relative cost make them important enough that worth to be fixed, given that they actually translate in cpu cycles which could be used with more profit elsewhere (or just scarse, because in containers).

This issue is partially related to https://github.com/quarkusio/quarkus/issues/34473

**Comment by franz1981** [comment]
@geoand 
This is a separate question: while performing this investigation I've found strange that we perform just `uri` validation for HTTP 1.1: we do have other checks which validate against the hole authority as well?

**Comment by geoand** [comment]
Which existing check are you referring to?

**Comment by franz1981** [comment]
This one at https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L148

**Comment by geoand** [comment]
That's all we do AFAIR

**Comment by cescoffier** [comment]
This is only for benchmarking. You want the URI validation in "prod", as it can be an attack vector.

**Comment by franz1981** [comment]
Yeah, what I have found is that we don't fully do it, instead...we just verify the path on the annotation, not the full authority.

**Comment by cescoffier** [comment]
ah yes, we do not validate the full URL (with the authority).

**Comment by franz1981** [comment]
Yeah, that was my concern, so atm http 2 is "safer" than http 1.1 in relation of this...we are not prone to CVE because of this?

**Comment by cescoffier** [comment]
Not totally sure, it would be minor. But yes, might be better to do a full validation.

**Comment by franz1981** [comment]
Closing this since is fixed on vertx.
