### ISSUE TITLE
registry.quarkus.io/maven returns 404 and "quarkus create" fails

### ISSUE THREAD

**Issue by samardeca** [quarkusio/quarkus#37831]
### Describe the bug

1. D0ownloaded quarkus using SDKMAN following instructions on your website. 
2. Tried to run "quarkus create" 
3. Got the following error:

[WARN] 🔥  Configured Quarkus extension registries appear to be unavailable at the moment. It should still be possible to create a project by providing the groupId:artifactId:version of the desired Quarkus platform BOM, e.g. 'quarkus create -P io.quarkus.platform:quarkus-bom:3.5.0.CR1'
[ERROR] ❗  Unable to create project: Failed to resolve the Quarkus extension registry descriptor of registry.quarkus.io from registry.quarkus.io (https://registry.quarkus.io/maven)

**When i tried to go to "registry.quarkus.io/maven" it throws 404 forbidden.  
I added the registry using "quarkus registry add registry.quarkus.io" to make sure its available in my .m2 folder.** 

### Expected behavior

"quarkus create" should work out of the box! The onboarding experience should be very smooth for new users.

### Actual behavior

Got an error while trying to create a new project using the cli "quarkus create"

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### Quarkus version or git rev

3.5.0.CR1

**Comment by gastaldi** [comment]
> I added the registry using "quarkus registry add registry.quarkus.io" to make sure its available in my .m2 folder.

So this made it work? Just to be clear

**Comment by samardeca** [comment]
> > I added the registry using "quarkus registry add registry.quarkus.io" to make sure its available in my .m2 folder.
> 
> So this made it work? Just to be clear

No this did not make it work still. I had to use the suggestion in the **warning** given in the output. So, I had to do this:
**quarkus create -P io.quarkus.platform:quarkus-bom:3.5.0.CR**

**Comment by gastaldi** [comment]
Can you try with the latest 3.6.3 instead of 3.5.0.CR1?

**Comment by samardeca** [comment]
> Can you try with the latest 3.6.3 instead of 3.5.0.CR1?

Same error with 3.6.3

**Comment by gastaldi** [comment]
I uninstalled my Quarkus CLI and tried to reproduce the issue using the steps you described but it works for me. Can you try removing your `~/.m2/repository/io/quarkus/registry` and trying again?

**Comment by gastaldi** [comment]
Registry.quarkus.io/maven is meant to return 404, because it's not a valid URL without the GAV in the path.

**Comment by samardeca** [comment]
> I uninstalled my Quarkus CLI and tried to reproduce the issue using the steps you described but it works for me. Can you try removing your `~/.m2/repository/io/quarkus/registry` and trying again?

I installed it fresh on another laptop and it worked fine. Maybe it had something to do with my corp firewall.

**Comment by gastaldi** [comment]
That's a good indication. Can you confirm if your `~/.m2/settings.xml` has the proxy settings correctly configured?

**Comment by aloubyansky** [comment]
In case you have a corporate Artifactory or Nexus proxies/mirrors configured, make sure registry.quarkus.io/maven is enabled as a snapshot repository.

**Comment by samardeca** [comment]
I checked with the IT support, they said no outgoing url is blocked. Maybe some installation issue. Please close this ticket for now. I will check later with a fresh install.
