### ISSUE TITLE
TestScopeManager. tearDown() calls setup() instead of tearDown()

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#3784]
The tearDown() method of TestScopeManager calls TestScopeSetup.setup() instead of tearDown():
https://github.com/quarkusio/quarkus/blob/2a3e3c6993d0530f512457bef5cc4ee85234c36f/test-framework/common/src/main/java/io/quarkus/test/common/TestScopeManager.java#L25-L29

I did not see any bad behaviors associated with that mistake though.

**Comment by gsmet** [comment]
@vsevel can you create a separate PR for this?

**Comment by vsevel** [comment]
fixed by https://github.com/quarkusio/quarkus/pull/3789
