### ISSUE TITLE
[Extension Proposal] Quarkus Kiota extension

### ISSUE THREAD

**Issue by andreaTP** [quarkusio/quarkus#37843]
### Description

Currently, the code is in this repository: https://github.com/kiota-community/kiota-java-extra under the `quarkus` folder.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

quarkus-kiota

### Short description

A Quarkus extension to generate client code/SDKs for OpenAPI specifications leveraging [Kiota](https://github.com/microsoft/kiota).

### Repository Homepage URL

https://github.com/kiota-community/kiota-java-extra/blob/main/docs/modules/ROOT/pages/index.adoc

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- @andreaTP

### Additional context

I would prefer to keep the repository under its current organization, if possible.

**Comment by gastaldi** [comment]
@andreaTP an extension proposal issue means that you're asking for a repository under the https://github.com/quarkiverse org. If you want to keep the extension in the original repository, then perhaps you just want to list it in our tooling? See https://hub.quarkiverse.io/checklist/#after-the-repository-is-created

**Comment by andreaTP** [comment]
@gastaldi I opened the issue mostly for visibility purposes but yes:

> perhaps you just want to list it in our tooling?

I'll go through it, thanks for the link!

**Comment by gastaldi** [comment]
I'm closing as the other PRs were already merged

**Comment by melloware** [comment]
@andreaTP Kiota looks super slick. However I understand what it does I haven't seen any examples of Java code using the generated Fluent API so I am struggling to wrap my brain around how it looks.     Right now I used OpenAPI Generator Quarkus extension with the native Java HTTP Client so I will be interested how this looks!

**Comment by andreaTP** [comment]
Hi @melloware and thanks for your interest in Kiota, if you want a simple example you can look in the [integration-tests of the Quarkus extension](https://github.com/kiota-community/kiota-java-extra/blob/b68864ea2010c54334bc125b4313e1a677f77bd2/quarkus/integration-tests/basic-vertx/src/test/java/io/kiota/quarkus/it/QuarkusKiotaResourceTest.java#L30-L39), but for a more real-world example the [Apicurio Registry test suite](https://github.com/andreaTP/apicurio-registry/blob/0a42927b2147468191a0039a87fb559b87470590/app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java#L155-L160) is more interesting (pointing you to a branch as in `main` we still have the old async version).
Feel free to reach out for any additional information!
