### ISSUE TITLE
Unable to start quarkus with spring data jpa dependencies

### ISSUE THREAD

**Issue by naushadamin** [quarkusio/quarkus#3785]
Getting following error during start:
Caused by: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
	- org.springframework.data.domain.Auditable
	- org.springframework.data.domain.Persistable
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.discoverModelAndRegisterForReflection(JpaJandexScavenger.java:93)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Added jandex plugin inside pom.xml, empty META-INF beans.xml with no success.

Attempted to add the following in application properties:
quarkus.index-dependency.spring-data-jpa.group-id=org.springframework.data
quarkus.index-dependency.spring-data-jpa.artifact-id=spring-data-jpa

Still same error:

Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
	- org.springframework.data.domain.Auditable
	- org.springframework.data.domain.Persistable
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.

**Comment by geoand** [comment]
Hi,

what version of Quarkus are you using?

**Comment by naushadamin** [comment]
0.21.1

**Comment by geoand** [comment]
Thanks for the info.

This has been fixed in `master` and will be present in `0.22.0`, so I'll take the liberty to close this.

**Comment by r-uu** [comment]
Hi,

the empty META-INF/beans.xml (really empty) and the maven plugin (version 1.0.8) options both do not work with quarkus 1.6.1.final and 1.6.0.final. The configuration in application.properties succeeded for me with quarkus 1.6.1.final.

**Comment by geoand** [comment]
@r-uu do you have an example of that?

**Comment by r-uu** [comment]
Yes, I prepared an extremely simple example, see attached file. It contains a maven multi module project with one module (User.java) using a type (BaseEntity.java) from another module as base class for an entity. If you start the server in dev mode and send a trivial request quarkus complains:

```
2020-07-26 15:28:38,157 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
        - sandbox.quarkus.security.jpa.BaseEntity

```
You can see that there is a completely empty META-INF/beans.xml but no target/classes/META-INF/jandex.idx is generated in my environment (even not after starting and accessing the server).

There also is the jandex-maven-plugin in the pom of the using module. This module creates target/classes/META-INF/jandex.idx but on the first request quarkus complains the above message.

Finally this time also the quarkus.index-dependency settings in application.properties do not work either.

Anything I am missing?
[sandbox.zip](https://github.com/quarkusio/quarkus/files/4977774/sandbox.zip)

**Comment by geoand** [comment]
@r-uu you need to move the jandex plugin configuration to `quarkus.security.jpa-used.module`.
