### ISSUE TITLE
[Extension Proposal] Quarkus Reactive Messaging NATS JetStream extension

### ISSUE THREAD

**Issue by kjeldpaw** [quarkusio/quarkus#37859]
### Description

Quarkus Reactive Messaging NATS is a Quarkus extension that brings in support for NATS JetStream for Reactive Messaging.

I'm working on an extension that makes it easy to integrate with NATS.io JetStream (https://docs.nats.io/nats-concepts/jetstream). The extension is based on reactive messaging (https://github.com/smallrye/smallrye-reactive-messaging). I would like to donate my work and help making the extension even better.

Code example:
```
@Channel("data")
Emitter<String> emitter;

@Incoming("data-consumer")
public Uni<Void> data(Message<String> message) {
    return Uni.createFrom().item(message)
            .onItem().invoke(this::handleData)
            .onItem().ignore().andContinueWithNull();
}

```

Properties:
```
mp.messaging.outgoing.data.connector=quarkus-jetstream
mp.messaging.outgoing.data.subject=data
mp.messaging.outgoing.data.stream=test

mp.messaging.incoming.data-consumer.connector=quarkus-jetstream
mp.messaging.incoming.data-consumer.subject=data
mp.messaging.incoming.data-consumer.stream=test

quarkus.reactive-messaging.nats.servers=${nats.server}
quarkus.reactive-messaging.nats.username=${nats.username}
quarkus.reactive-messaging.nats.password=${nats.password}
quarkus.reactive-messaging.nats.ssl-enabled=false
quarkus.reactive-messaging.nats.auto-configure=true
```

### Repository name

quarkus-reactive-messaging-nats-jetstream

### Short description

Easily integrate to NATS.io JetStream

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- nats.io
- jetstream
- reactive-messaging
...

### Team Members

- @kjeldpaw

**Comment by gastaldi** [comment]
https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream created! See https://hub.quarkiverse.io/checklist/#after-the-repository-is-created for the next steps. Enjoy!

**Comment by flashpixx** [comment]
Hello, I'm working on a project with NATS, so it would be nice if there is a pre-version available, so I can test it directly with my code and I can offer some feedback as well.

**Comment by kjeldpaw** [comment]
Hi @flashpixx  I'm on Christmas holiday but I will start committing my code after Christmas

**Comment by kjeldpaw** [comment]
Hi @flashpixx I'm still working on committing my source to the repo. You can find my work on this branch: https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/tree/feature/jetstream-connector

**Comment by flashpixx** [comment]
Can you show a minimal example to receive / send messages? I can compile it and use the runtime library, but it is a little bit difficult to understand it
