### ISSUE TITLE
In Open-Api yaml generation tags are note indented

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#37861]
### Describe the bug

When a resource is annotated with '@Tag'  under http://localhost:8080/q/openapi  quarkus-smallrye-openapi generates a yaml output with tags not intended properly:
```
---
openapi: 3.0.3
info:
  title: openapi-demo API
  version: 1.0.0-SNAPSHOT
tags:
- name: public
paths:
  /hello:
    get:
      tags:
      - public
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string

```

### Expected behavior

tags list should be indented

### Actual behavior

tags not indented

### How to Reproduce?

[openapi-demo.tar.gz](https://github.com/quarkusio/quarkus/files/13724864/openapi-demo.tar.gz)
unpack and execute ./mvnw test
or hit http://localhost:8080/q/openapi

**Comment by phillip-kruger** [comment]
I think this is correct ? @MikeEdgar ?? w.d.y.t ?

**Comment by MikeEdgar** [comment]
Yes, this is valid YAML. See the 1.1 YAML spec, section 10.1.2 [1]

> People read the “-” character as part of the [indentation](https://yaml.org/spec/1.1/#indentation%20space/). Hence, block sequence entries require one less space of [indentation](https://yaml.org/spec/1.1/#indentation%20space/), unless the block sequence is nested within another block sequence

[1] https://yaml.org/spec/1.1/#id931893

**Comment by phillip-kruger** [comment]
@ennishol any more context ? Why do you say it's invalid?

**Comment by ennishol** [comment]
ok. maybe it is also valid, but all APIs yamls I've seen use indentation. See also

https://swagger.io/docs/specification/grouping-operations-with-tags/

Open-api generator plugins also do indent when generating a yaml.
Intellij 'fixes' missing whitespace on paste.

**Comment by phillip-kruger** [comment]
Ok, so this does not create an issue for you? Can we close ?

**Comment by ennishol** [comment]
@phillip-kruger  since it is valid yaml, I'm ok
