### ISSUE TITLE
The ImageMetricsITCase failing with RH Mandrel

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#37882]
### Describe the bug

The `ImageMetricsITCase` was introduced. But it's failing with RH mandrel (registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0) as it's bigger then then expected compared to the upstream (tried even older mandrel builds quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.0.2.1-Final-java17-2023-10-28 it passed without problem).

### Actual behavior

Test is failing with this output: 
```Expected image_details.total_bytes to be within range [78626464 +- 3%] but was 81149928 ==> expected: <true> but was: <false>```

### How to Reproduce?

I using this command to verify
`mvn -f integration-tests/pom.xml clean dependency:tree verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g -U -V -B -fae -Denforcer.skip=true -Dtest-containers -Dstart-containers -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0-16 -pl jpa-postgresql -Dpostgres.image=postgres:14`

### Output of `uname -a` or `ver`

Havving it on RHEL 8.9 and Fedora 39

**Comment by jedla97** [comment]
@zakkak As you add this new test can you look at it please. I know it can be skipped by `export QUARKUS_NATIVE_IT_SKIP_VERIFY_IMAGE_METRICS=true` but this would be also nice to have see the difference with RH build

**Comment by zakkak** [comment]
The differences I see between upstream and RH Mandrel are:

```diff
diff --git a/upstream-mandrel-image-metrics.properties b/rh-mandrel-image-metrics.properties
index dd835c7a730..60d8d3e6b9c 100644
--- a/upstream-mandrel-image-metrics.properties
+++ b/rh-mandrel-image-metrics.properties
@@ -1,11 +1,11 @@
 # Properties file used by ImageMetricsITCase
-image_details.total_bytes=79228920
+image_details.total_bytes=81162216
 image_details.total_bytes.tolerance=3
 analysis_results.types.reachable=19441
 analysis_results.types.reachable.tolerance=3
-analysis_results.methods.reachable=96417
+analysis_results.methods.reachable=96410
 analysis_results.methods.reachable.tolerance=3
-analysis_results.fields.reachable=27131
+analysis_results.fields.reachable=27129
```
which are bellow the 3% threshold.

The differences with the metrics stored in the Quarkus repository are:

```diff
diff --git a/integration-tests/jpa-postgresql/src/test/resources/image-metrics/23.0/image-metrics.properties b/rh-mandrel-image-metrics.properties
index 8dd4994f234..60d8d3e6b9c 100644
--- a/integration-tests/jpa-postgresql/src/test/resources/image-metrics/23.0/image-metrics.properties
+++ b/rh-mandrel-image-metrics.properties
@@ -1,21 +1,21 @@
 # Properties file used by ImageMetricsITCase
-image_details.total_bytes=78626464
+image_details.total_bytes=81162216
 image_details.total_bytes.tolerance=3
-analysis_results.types.reachable=19172
+analysis_results.types.reachable=19441
 analysis_results.types.reachable.tolerance=3
-analysis_results.methods.reachable=95204
+analysis_results.methods.reachable=96410
 analysis_results.methods.reachable.tolerance=3
-analysis_results.fields.reachable=27139
+analysis_results.fields.reachable=27129
 analysis_results.fields.reachable.tolerance=3
-analysis_results.types.reflection=5939
+analysis_results.types.reflection=6060
 analysis_results.types.reflection.tolerance=3
-analysis_results.methods.reflection=4401
+analysis_results.methods.reflection=4484
```

which are slightly above the 3% threshold.

For the time being I will just update the reference metrics in the test and later try to understand the differences between upstream and RH builds.

**Comment by rsvoboda** [comment]
> later try to understand the differences between upstream and RH builds.

@zakkak Should we create issue for that follow-up?

**Comment by zakkak** [comment]
> @zakkak Should we create issue for that follow-up?

:+1: https://github.com/graalvm/mandrel/issues/654
