### ISSUE TITLE
--initialize-at-run-time flag ignored if -march=compatibility enabled

### ISSUE THREAD

**Issue by aron-airgraft** [quarkusio/quarkus#37896]
### Describe the bug

My organization is building some lambda functions with native images hosted on AWS runtime `provided.al2`. One of our lambdas fails at compile-time when we add the following line to application.properties:

`quarkus.native.additional-build-args=-march=compatibility
`

This lambda is the only one we currently have that uses an `--initialize-at-run-time` flag, snippet from pom.xml below.

`            <properties>
                <quarkus.native.additional-build-args>--initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl</quarkus.native.additional-build-args>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>`

During compilation, the following error occurs despite the flag marking it for later initialization:

`Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. Try avoiding to initialize the class that caused initialization of the object.
The culprit object has been instantiated by the 'org.apache.http.impl.auth.NTLMEngineImpl' class initializer with the following trace:
        at java.security.SecureRandom.<init>(SecureRandom.java:331)
        at java.security.SecureRandom.getInstance(SecureRandom.java:391)
        at org.apache.http.impl.auth.NTLMEngineImpl.<clinit>(NTLMEngineImpl.java:103)
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.apache.http.impl.auth.NTLMEngineImpl.RND_GEN
    at org.apache.http.impl.auth.NTLMEngineImpl.access$000(NTLMEngineImpl.java:51)
  parsing method org.apache.http.impl.auth.NTLMEngineImpl.access$000(NTLMEngineImpl.java:51) reachable via the parsing context
    at static root method.(Unknown Source)`

Our compile argument is `mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true `

### Expected behavior

The expected behavior is for the lambda to successfully compile, as NTLMEngineImpl has been flagged for runtime initialization instead of compile-time.

### Actual behavior

With the `-march=compatibility` flag, the initialize flag is ignored or bypassed, and the native image compilation fails. Removing the flag allows the image to compile successfully.

### How to Reproduce?

Unable to provide a minimum reproducer, and the affected lambda contains proprietary code

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64 | additionally occurs in Github Actions with runs-on: ubuntu-latest

### Output of `java -version`

java version "21.0.1" 2023-10-17 Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

graalvm-jdk-21.0.1+12.1

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

**Comment by zakkak** [comment]
@aron-airgraft how are you setting `quarkus.native.additional-build-args=-march=compatibility`, you can't set `quarkus.native.additional-build-args` twice, it will only keep the last value passed to it. Instead you need to set it once passing all the options to it, e.g.:

``` 
<properties>
  <quarkus.native.additional-build-args>
--initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl,-march=compatibility
  </quarkus.native.additional-build-args>
  <quarkus.package.type>native</quarkus.package.type>
</properties>
````

**Comment by aron-airgraft** [comment]
> @aron-airgraft how are you setting `quarkus.native.additional-build-args=-march=compatibility`, you can't set `quarkus.native.additional-build-args` twice, it will only keep the last value passed to it. Instead you need to set it once passing all the options to it, e.g.:
> 
> ```
> <properties>
>   <quarkus.native.additional-build-args>
> --initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl,-march=compatibility
>   </quarkus.native.additional-build-args>
>   <quarkus.package.type>native</quarkus.package.type>
> </properties>
> ```

This seems to have resolved my issue, thanks.
