### ISSUE TITLE
quarkus dev broken for command mode arguments

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#37921]
### Describe the bug

using quarkus dev with command mode seem to have regressed.

do this:

`quarkus create app -x picocli whoops`

then run:
`quarkus dev this is my name`

and it will print out "this is my name" and in bottom line have:

`Press [space] to restart, [e] to edit command line args (currently 'this is my name'), [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>`

now press 'e' to edit and notice that you are shown an empty line. Type in `something else completely` and press enter and you get:

`Unmatched arguments from index 1: 'completely', 'different'
Usage: greeting [-hV] <name>
      <name>      Your name.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.`

but the line still shows:

`Press [space] to restart, [e] to edit command line args (currently 'this is my name'), [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>`

so multiple issues in the above:

1) `quarkus dev whatever i put` the latter part gets passed in as *one* string ("whatever i put") rather than actual individual arguments. It should be an array of strings ("whatever", "i", "put") rather than one big string. 
   note: `quarkus dev "whatever I put"` should give you one string and not an array of string.
   the edit command actually seem to do this correct. its just the passing of parameter that is wrong
2)  the line at bottom does not show the current command line arg but what was passed in originally
3) the edit does not actually let you edit the command line. just give you blank line. Sometimes characters are not even shown when typing.

**Comment by MaciejDromin** [comment]
Hey @maxandersen I started looking into this issue, was able to fix already the second issue You pointed out. I will continue work on this in the upcoming days :)

**Comment by maxandersen** [comment]
Awesome. 

Remember it's just as fine fixing smaller subparts in multiple prs as that often makes it easier to fix and review.

**Comment by MaciejDromin** [comment]
> Remember it's just as fine fixing smaller subparts in multiple prs as that often makes it easier to fix and review.

You are right. In this case this pr is ready for review, it fixes the second pointed out issue

**Comment by MaciejDromin** [comment]
Regarding point 3, I did some investigation and I'm afraid it's impossible to provide a string to be edited from the command line.
What I suggest as an alternative is to print some prompt at the beginning: ```Current args: arg1 arg2 >```
What do You think?

**Comment by maxandersen** [comment]
> > Remember it's just as fine fixing smaller subparts in multiple prs as that often makes it easier to fix and review.
> 
> 
> 
> You are right. In this case this pr is ready for review, it fixes the second pointed out issue

Which pr is it? Got a link?

**Comment by maxandersen** [comment]
> Regarding point 3, I did some investigation and I'm afraid it's impossible to provide a string to be edited from the command line.
> 
> What I suggest as an alternative is to print some prompt at the beginning: ```Current args: arg1 arg2 >```
> 
> What do You think?

Makes sense.

**Comment by MaciejDromin** [comment]
> Which pr is it? Got a link?

Yes, there you go [Fix quarkus dev broken...](https://github.com/quarkusio/quarkus/pull/37961)

**Comment by MaciejDromin** [comment]
> Makes sense.

Here is new PR which fixes this issue from point 3. [Display current args...](https://github.com/quarkusio/quarkus/pull/37968)

**Comment by maxandersen** [comment]
Awesome. I'm back working on Monday so hope to get to this as soon as possible.

**Comment by MaciejDromin** [comment]
> Awesome. I'm back working on Monday so hope to get to this as soon as possible.

Alright thanks. I'm looking forward for the feedback

**Comment by maxandersen** [comment]
sorry for the delay! first off - awesome contributions @MaciejDromin - these greatly improve the devmode experience with cli based commands.

#37961 - spot on! LGTM.
#37968 - better, but still having weird behavior. Please check if you see it too.
#38058 - spot on! LGTM (special case we can look at improving in future)

**Comment by MaciejDromin** [comment]
Thanks for the feedback @maxandersen!
if [#37961](https://github.com/quarkusio/quarkus/pull/37961) and [#38058](https://github.com/quarkusio/quarkus/pull/38058) look good I think they can be merged :) Regarding the special case maybe it would be good to create a new Issue for improvement?
[#37968](https://github.com/quarkusio/quarkus/pull/37968) - I will try to look into this hopefully tomorrow
