### ISSUE TITLE
Improvement in the table structure

### ISSUE THREAD

**Issue by arunsak04** [quarkusio/quarkus#37930]
### Describe the bug

visit this website https://docs.quarkiverse.io/quarkus-web-bundler/dev/config-reference.html 
1. The table structure is going out of the screen  like the table is expanded
2. Footer copy right sentence is not center 
   1. image
![Screenshot 2023-12-25 220926](https://github.com/quarkusio/quarkus/assets/128994108/786eb85a-2c69-42b4-9090-1f3abd848cf7)
   2. image 
![Screenshot 2023-12-25 220953](https://github.com/quarkusio/quarkus/assets/128994108/1776e551-b666-4c4a-9568-14a686be170d)

**Comment by gastaldi** [comment]
Thanks for the issue. I believe it belongs to https://github.com/quarkiverse/antora-ui-quarkiverse

**Comment by gastaldi** [comment]
Kamino closed and cloned this issue to [quarkiverse/antora-ui-quarkiverse](https://github.com/quarkiverse/antora-ui-quarkiverse/issues/65)
