### ISSUE TITLE
Records with polymorphic types sent from native clients received with no data

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#37942]
### Describe the bug

Sending records that include polymorphic types from a native Quarkus app using rest-client to a jvm Quarkus app contains empty data.

The data model uses `com.fasterxml.jackson.annotation.JsonSubTypes` and `com.fasterxml.jackson.annotation.JsonTypeInfo` to handle polymorphism, and the types in the reproducer look like this:

```java
public record MammalFamily(Collection<Mammal> mammals) {}

@JsonTypeInfo(use = NAME, include = PROPERTY)
@JsonSubTypes({
    @JsonSubTypes.Type(value=Elephant.class, name = "Elephant"),
    @JsonSubTypes.Type(value=Whale.class, name = "Whale"),
})
public interface Mammal {}

public record Elephant(int hornLength, String continent) implements Mammal {}

public record Whale(double swimSpeed, String color) implements Mammal {}
```

### Expected behavior

Records with polymorphic subtypes should contain all the information when received by the server. E.g.

```
2023-12-27 12:42:28,586 INFO  [org.acm.ser.MammalResource] (executor-thread-1) Received mammal family:
MammalFamily[mammals=[Whale[swimSpeed=30.0, color=white], Elephant[hornLength=10, continent=africa]]]
```

### Actual behavior

Records with polymorphic subtypes are received by the server but they contain no data:

```
2023-12-27 12:47:43,323 INFO  [org.acm.ser.MammalResource] (executor-thread-1) Received mammal family:
MammalFamily[mammals=[Whale[swimSpeed=0.0, color=null], Elephant[hornLength=0, continent=null]]]
```

### How to Reproduce?

1. Checkout [reproducer](https://github.com/galderz/mendrugo/tree/main/subtype-in-record)
2. Run the JVM mode Quarkus server with `mvn install -DskipTests && mvn quarkus:run -pl server`
3. Build the native mode Quarkus client and run it with `mvn install -DskipTests -Dnative -pl client && ./client/target/client-1.0.0-SNAPSHOT-runner`
4. When the server receives the records from the client, they contain empty information:

```
2023-12-27 12:47:43,323 INFO  [org.acm.ser.MammalResource] (executor-thread-1) Received mammal family:
MammalFamily[mammals=[Whale[swimSpeed=0.0, color=null], Elephant[hornLength=0, continent=null]]]
```

In contrast, if the client is running in JVM mode, it all works as expected:

1. Checkout [reproducer](https://github.com/galderz/mendrugo/tree/main/subtype-in-record)
2. Run the JVM mode Quarkus server with `mvn install -DskipTests && mvn quarkus:run -pl server`
3. Run the Quarkus client in JVM mode with `mvn quarkus:run -pl server -pl client`
4. The server receives the records from the client with the expected information:

```
2023-12-27 12:41:29,965 INFO  [org.acm.ser.MammalResource] (executor-thread-1) Received mammal family:
MammalFamily[mammals=[Whale[swimSpeed=30.0, color=white], Elephant[hornLength=10, continent=africa]]]
```

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)

### Quarkus version or git rev

3.6.4

### Additional information

Avoiding polymorphism can be a temporary workaround if the application supports it.

**Comment by galderz** [comment]
FYI @geoand

**Comment by geoand** [comment]
Thanks! I'll have a look next week

**Comment by geoand** [comment]
#37993 fixes the issue
