### ISSUE TITLE
PortSystemProperties sets wrong properties for HTTPS

### ISSUE THREAD

**Issue by rob-spoor** [quarkusio/quarkus#37944]
### Describe the bug

The correct properties for setting the HTTPS port are `quarkus.http.ssl-port` and `quarkus.http.test-ssl-port`. However, these are not those being overridden by `PortSystemProperties`. It instead sets `quarkus.https.port` and `quarkus.https.test-port`.

### Expected behavior

When `quarkus.http.test-ssl-port` is set to 0, injecting the port using `@ConfigProperty(name = "quarkus.http.test-ssl-port")` should result in the correct random port. Similarly, using `@TestHTTPResource(value = "/some-path", ssl = true)` should result in a URL object with the correct random port.

### Actual behavior

`@ConfigProperty(name = "quarkus.http.test-ssl-port")` results in 0, and `@TestHTTPResource(value = "/some-path", ssl = true)` results in `https://localhost:0/some-path`.

### How to Reproduce?

Run the following JUnit test class:
```java
@QuarkusTest
@TestProfile(PortTest.PortTestProfile.class)
class PortTest {

    @ConfigProperty(name = "quarkus.http.port")
    int httpPort;

    @ConfigProperty(name = "quarkus.http.ssl-port")
    int httpsPort;

    @ConfigProperty(name = "quarkus.http.test-port")
    int httpTestPort;

    @TestHTTPResource(value = "/some-path", ssl = false)
    URL httpTestUrl;

    @ConfigProperty(name = "quarkus.http.test-ssl-port")
    int httpsTestPort;

    @TestHTTPResource(value = "/some-path", ssl = true)
    URL httpsTestUrl;

    @Test
    void testHttpPort() {
        assertNotEquals(0, httpPort);
        assertNotEquals(8080, httpPort);
    }

    @Test
    void testHttpsPort() {
        assertNotEquals(0, httpsPort);
        assertNotEquals(8443, httpsPort);
    }

    @Test
    void testHttpTestPort() {
        assertNotEquals(0, httpTestPort);
        assertNotEquals(8081, httpTestPort);
    }

    @Test
    void testHttpTestUrl() {
        assertNotEquals(0, httpTestUrl.getPort());
        assertNotEquals(8081, httpTestUrl.getPort());
    }

    @Test
    void testHttpsTestPort() {
        assertNotEquals(0, httpsTestPort);
        assertNotEquals(8444, httpsTestPort);
    }

    @Test
    void testHttpsTestUrl() {
        assertNotEquals(0, httpsTestUrl.getPort());
        assertNotEquals(8444, httpsTestUrl.getPort());
    }

    public static class PortTestProfile implements QuarkusTestProfile {

        @Override
        public Map<String, String> getConfigOverrides() {
            return Map.of("quarkus.http.test-port", "0", "quarkus.http.test-ssl-port", "0");
        }
    }
}
```
This currently has 3 passing tests (for `httpPort`, `httpTestPort` and `httpTestUrl`) and 3 failing tests (for `httpsPort`, `httpsTestPort` and `httpsTestUrl`).

If I use the debugger to change the property on https://github.com/quarkusio/quarkus/blob/7d153339fe7c6eb8ca9dbe152220aae4e6f085d1/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PortSystemProperties.java#L19 and https://github.com/quarkusio/quarkus/blob/7d153339fe7c6eb8ca9dbe152220aae4e6f085d1/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PortSystemProperties.java#L26 these tests succeed.

Note that https://github.com/quarkusio/quarkus/blob/7d153339fe7c6eb8ca9dbe152220aae4e6f085d1/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/PortSystemProperties.java#L34 should probably be changed as well.

For backwards compatibility the old incorrect properties should probably be set as well, otherwise projects that use workaround like `ConfigProvider.getConfig().getOptionalValue("quarkus.https.test-port", Integer.class)` will fail.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.3803]

### Output of `java -version`

openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
Thanks for reporting!

Since you have already found the places in the code where the fixes should go, would you like to contribute a PR?

**Comment by rob-spoor** [comment]
I'll see if I can make some time this week.

**Comment by geoand** [comment]
💪🏼

**Comment by rob-spoor** [comment]
I found some time today already, and I've just finished the PR: https://github.com/quarkusio/quarkus/pull/38006
