### ISSUE TITLE
missing way to enable logging of websocket traffic

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#37947]
### Description

rest has nice logging of request/response - seems websocket does not have a way to reliably have similar logging enabled.

making it hard to debug.

**Comment by geoand** [comment]
Is this about the client or server part?

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by maxandersen** [comment]
missed it - it was for both and definitely for the client.

**Comment by geoand** [comment]
@mkouba something to consider for Websockets Next

**Comment by mkouba** [comment]
> rest has nice logging of request/response

@maxandersen Are you talking about `io.restassured.response.ValidatableResponseOptions.log()`, or some other tool/technology/feature? 

I know that in JAX-RS you can have a logging `ContainerRequestFilter`. In the context of WS Next, you could have a logging CDI interceptor. But since there are no metadata sent along with a message in WS the logged output would be rather "poor" :shrug:.

**Comment by maxandersen** [comment]
@mkouba I know it would be "poor" but not having *anything* logged is worse when trying to figure out why content doesn't match or which was my case that I got no response but just a "bye" from the protocol.

only found out by adding breakpoints to every entry point I could think of instead of being able to go through logs to spot the "bye".

**Comment by mkouba** [comment]
> @mkouba I know it would be "poor" but not having _anything_ logged is worse when trying to figure out why content doesn't match or which was my case that I got no response but just a "bye" from the protocol.

Well, if you add `quarkus.log.category."io.quarkus.websockets.next".level=DEBUG` to your `application.properties` you can see a bunch of DEBUG messages for every endpoint invocation.
 
> 
> only found out by adding breakpoints to every entry point I could think of instead of being able to go through logs to spot the "bye".

Again, are you talking about the client logging (`io.restassured.response.ValidatableResponseOptions.log()`) or server logging (`ContainerRequestFilter` or something coming from Vert.x)?

**Comment by mkouba** [comment]
> I was hoping for sometihng like the rest client and server logging we have - for vert.x I didn't spot a way to get meaningful (high-level) messages.

Ok, for rest client I found [this in the docs](https://quarkus.io/guides/rest-client#logging-traffic) but for the server I did not find anything built-in. In any case, we could try to add something similar.
