### ISSUE TITLE
ServerRequestFilter and ServerResponseFilter with accesing to a non-existent URL

### ISSUE THREAD

**Issue by chiroito** [quarkusio/quarkus#37940]
### Describe the bug

ServerRequestFilter and ServerResponseFilter seem to behave strangely when accessing a non-existent URL.

ServerRequestFilter is not executed, only ServerResponseFilter is executed.

In this case, the return value of `serverRequestContext.getReactiveResourceInfo()` is null in ServerResponseFilter.

### Expected behavior

Both ServerRequestFilter and ServerResponseFilter are executed. Or, both are not executed.

If both are executed, the return value of `serverRequestContext.getReactiveResourceInfo()` is not null.

### Actual behavior

ServerRequestFilter is not executed, only ServerResponseFilter is executed.

In this case, the return value of `serverRequestContext.getReactiveResourceInfo()` is null in ServerResponseFilter.

### How to Reproduce?

Copy the following two Java files, run them in Dev mode, and access the following URL.

http://localhost:8080/favicon

ExampleResource.java
```
package org.example;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class ExampleResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
}
```

Filter.java
```
package org.example;

import jakarta.inject.Inject;
import org.jboss.resteasy.reactive.server.ServerRequestFilter;
import org.jboss.resteasy.reactive.server.ServerResponseFilter;
import org.jboss.resteasy.reactive.server.spi.ServerRequestContext;

public class Filter {

    @Inject
    ServerRequestContext serverRequestContext;

    @ServerRequestFilter
    public void requestFilter() {
        System.out.println("Enter Server Request Filter : " + (serverRequestContext.getResteasyReactiveResourceInfo() == null));
    }

    @ServerResponseFilter
    public void responseFilter() {
        System.out.println("Enter Server Response Filter : " + (serverRequestContext.getResteasyReactiveResourceInfo() == null));
    }
}
```

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
That's actually how the JAX-RS spec defines filters.

If you want the request filter to always be executed, you need to use `@ServerRequestFilter(preMatching=true)`
