### ISSUE TITLE
After upgrade to quarkus 3.5.3 from 2.16.Final seeing the following "Unable to execute the validation check for the default DataSource: Acquisition timeout while waiting for new connection"

### ISSUE THREAD

**Issue by ngarg-panw** [quarkusio/quarkus#37948]
### Describe the bug

Getting the following exception after updating quarkus to 3.5.3. It works fine with 2.16.Final:

```
SmallRyeHealthReporter INFO[io.smallrye.health.SmallRyeHealthReporter.reportHealth()216]: SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Reactive MySQL connections health check","status":"DOWN","data":{"<default>":"timed out, unable to obtain connection to perform healthcheck of datasource"}},{"name":"Database connections health check","status":"DOWN","data":{"<default>":"Unable to execute the validation check for the default DataSource: Acquisition timeout while waiting for new connection"}},{"name":"Report Generation Service Readiness health check","status":"UP"}]}

2023-12-27 19:49:36 [vert.x-eventloop-thread-1] QuarkusContextStorage WARN[io.quarkus.opentelemetry.runtime.QuarkusContextStorage.close()78]: Context in storage not the expected context, Scope.close was not called correctly. Details: OTel context before: {spanId=1468fbfa2d70ef8b, traceId=e59f02f65ef45f6d7146bb8b0ef2d39c, sampled=false}. OTel context toAttach: {spanId=5c2b78907a414ba8, traceId=f81ef0ab47a8181f15d67e51ec5d52d4, sampled=false}
2023-12-27 19:49:41 [vert.x-eventloop-thread-0] ReactiveDatasourceHealthCheck WARN[io.quarkus.reactive.datasource.runtime.ReactiveDatasourceHealthCheck.operationsError()100]: Error obtaining database connection for healthcheck of datasource '<default>': io.netty.channel.ConnectTimeoutException: connection timed out:
```

I do have the following entry in my application.yml

  ```
datasource:
    db-kind: mariadb
    username: ${memsql.username}
    password: ${memsql.password}
    jdbc:
      url: jdbc:mariadb://${memsql.host}:${memsql.port}/${memsql.database}
    reactive:
      url: vertx-reactive:mysql://${memsql.host}:${memsql.port}/${memsql.database}
hibernate-orm:
  database:
    generation: none
  log:
    sql: true
```

### Expected behavior

The pods come up successfully without database healthcheck failures.

### Output of `java -version`

8

### Quarkus version or git rev

3.5.3

**Comment by DavideD** [comment]
Would you be able to provide a test case we can run?

**Comment by ngarg-panw** [comment]
Hard to extract out the test case. I have two repos and both have liveliness check and readiness check. The difference is that in one of the repo I am checking for database connection whereas in another I am not. In the one in which I am not checking, quarkus upgrade is successful. But in the one I am checking, it fails with the above mentioned error. 
I tried commenting the database check part but no luck. It still fails. Here is the helm and readiness check file for the repo for which Quarkus Upgrade is failing:

           livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.report_generation_std.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.report_generation_std.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.report_generation_std.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.report_generation_std.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.report_generation_std.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.report_generation_std.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.report_generation_std.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.report_generation_std.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.report_generation_std.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.report_generation_std.readinessProbe.failureThreshold }}
```

The class for readiness check (after removing all the DB calls/checks, it still fails):


@Readiness
@ApplicationScoped
public class ReadinessHealthCheck implements HealthCheck {

  @Override public HealthCheckResponse call() {
    return HealthCheckResponse.up("Report Generation Service Readiness health check");
  }
}
```

Have already shared the application.yml. Please let me know if I am missing any datapoint which might be causing the issue.

**Comment by ngarg-panw** [comment]
Another thing to notice is that its trying to connect to wrong port for memsql

`AgroalEventLoggingListener WARN[io.quarkus.agroal.runtime.AgroalEventLoggingListener.onWarning()83]: Datasource '<default>': Socket fail to connect to host:address=(host=child.memsql.app-sam105882.sam.prismacloud.io)(port=11994)(type=primary). connect timed out`

The port for memsql should be 3306 but it is trying to connect to a random port everytime a port a restarted. i.e in above error its `11994`. Not sure if that can be the root cause of the issue. Cannot find that port defined anywhere. Infact, in the code I have hardcoded MEMSQL_PORT=3306 everywhere.

**Comment by ngarg-panw** [comment]
Update: There was a code section in our codebase where we were generating random memsql ports for testing pipelines. Due to some env variable assignment issue, that block of code was getting executed even for the production memsql port generation and hence causing the connection issue. 

Closing this since its not quarkus issue.
