### ISSUE TITLE
Reactive RestClient used within the Security layer of Quarkus times out and doesn't propagate headers in reactive HeadersFactory

### ISSUE THREAD

**Issue by WollfieGitHub** [quarkusio/quarkus#37945]
### Describe the bug

I am trying to use a reactive `RestClient` within a `SecurityIdentityAugmentor` to fetch roles. However, the request times out, and I see using the logging of the `ReactiveClientHeadersFactory` that the `incomingHeaders` argument is empty in this case.

I also noticed that the RESTEasyReactive request context isn't active in this scope, which I figure can be part of the problem.

Bug reproduction available here: [https://github.com/WollfieGitHub/test_quarkus_rest_client_security_layer](https://github.com/WollfieGitHub/test_quarkus_rest_client_security_layer)

### Expected behavior

The request to the RestClient should propagate the headers and receive a response.

Expected output from the reproducer project (obtained via the same call but from a resource endpoint body):
```
2023-12-27 17:09:08,278 INFO  [com.exa.ClientDelegate] (vert.x-eventloop-thread-0) Call to no-auth...
2023-12-27 17:09:08,296 INFO  [com.exa.ClientHeadersFactoryImpl] (vert.x-eventloop-thread-0) Incoming headers size: 3
2023-12-27 17:09:08,344 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Request: GET http://localhost:8080/ping/no-auth 	Headers[Accept=text/plain;charset=UTF-8 User-Agent=Resteasy Reactive Client], Empty body
2023-12-27 17:09:08,360 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Response: GET http://localhost:8080/ping/no-auth, Status[200 OK], 	Headers[content-length=4 Content-Type=text/plain;charset=UTF-8], Body: pong
2023-12-27 17:09:08,364 INFO  [com.exa.ClientDelegate] (vert.x-eventloop-thread-0) Response from no-auth endpoint: "pong"
2023-12-27 17:09:08,365 INFO  [com.exa.ClientDelegate] (vert.x-eventloop-thread-0) Call to authorized...

```

### Actual behavior

The request to the RestClient times out and the headers are empty in the headers factory.

Actual output from the reproducer project:
```
2023-12-27 17:11:21,172 INFO  [com.exa.ClientDelegate] (vert.x-eventloop-thread-1) Call to no-auth...
2023-12-27 17:11:21,172 INFO  [com.exa.ClientHeadersFactoryImpl] (vert.x-eventloop-thread-1) Incoming headers size: 0
2023-12-27 17:11:21,175 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-1) Request: GET http://localhost:8080/ping/no-auth 	Headers[Accept=text/plain;charset=UTF-8 User-Agent=Resteasy Reactive Client], Empty body
```

### How to Reproduce?

A reproduction is available here: [https://github.com/WollfieGitHub/test_quarkus_rest_client_security_layer](https://github.com/WollfieGitHub/test_quarkus_rest_client_security_layer)

### Output of `java -version`

openjdk version "20.0.2"

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by sberyozkin** [comment]
@WollfieGitHub Hi, looks like this issue may be invalid, `context.runBlocking` must be used when remote calls are used to augment the identity, please see https://quarkus.io/guides/security-customization#security-identity-customization

**Comment by WollfieGitHub** [comment]
Hi, I tried this before and it gives the same result (timed out + headers not propagated), if this is what you meant.
```java
return context.runBlocking(() ->
  clientDelegate.tryCall()
	  .replaceWith(nextIdentity)
	  .await()
	  .indefinitely()
  );
```
Also, it looks like the solution should be closer to something like the "SecurityIdentitySupplier" from the link you provided (same as blocking example but below) and yet, this doesn't seem to work either.

**Comment by sberyozkin** [comment]
@WollfieGitHub Oh, so the issue is really about https://github.com/WollfieGitHub/test_quarkus_rest_client_security_layer/blob/master/src/main/java/com/example/ClientHeadersFactoryImpl.java having no effect, right ? FYI, RequestContext is not active in the augmentor, so if activating it explicitly does not work then I'm not sure what else can be done.

Is it only about the Reactive RestClient incoming header propagation, does the call goes through with the custom header factory temporarily removed ? 

CC @michalvavrik @geoand

**Comment by WollfieGitHub** [comment]
No, it seems the request gets blocked either way, even with the `@RegisterClientHeaders` commented out. I figured since two weird thing happening at once, it might be related so I mentioned empty headers too.

If I add 
```java
.invoke(() -> 
  Log.infof("Request context active: %s, RESTEasy Reactive Request: %s",
  Arc.container().getActiveContext(RequestScoped.class), CurrentRequestManager.get()
))
```
on the `tryCall()`, it logs:
```
2023-12-27 21:07:26,093 INFO  [com.exa.ClientDelegate] (vert.x-worker-thread-2) Request context active: io.quarkus.arc.impl.RequestContext@7a004800, RESTEasy Reactive Request: null
```
Which I don't have enough knowledge about the framework to say if it's normal or not, so I'm mentioning it.

**Comment by michalvavrik** [comment]
1. You have enabled proactive authentication, which means that authentication is always going to happen. So path `/ping/no-auth` is also authenticated. Please find out more here https://quarkus.io/guides/security-proactive-authentication and try  `quarkus.http.auth.proactive=false` if and only if that is safe for your use case.
2. Have you not mentioned how many self calling requests is `curl -v http://localhost:8080/ping/no-auth` triggering? It's a circle, that is why it times out.

> headers are empty in the headers factory

I can see that your `ReactiveClientHeadersFactory` implementation is invoked and you don't set any headers there. I don't see any `io.quarkus.rest.client.reactive.HeaderFiller` so I don't understand why do you expect any headers there.

**Comment by WollfieGitHub** [comment]
1. I agree that removing the authentication may solve the problem but the reason I want to get the headers is to pass an Authorization for the rest client call so it wouldn't be feasible in my case.
2. Yes, but should it form a circle ? Shouldn't it answer with 401 ? (I don't know much but it seems unintuitive to me which is why I'm asking)

About the headers: I couldn't find any documentation on how to use the `HeaderFiller`, but looking at `io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientRequestFilter`, the `HeaderFiller` only has access to the client request context, which does not contain the correct headers (contains outgoing and not incoming). The only source for `incomingHeaders` seems to be:
```java
// line 58
HeaderContainer headerContainer = Arc.container().instance(HeaderContainer.class).get();
if (headerContainer != null) {
    incomingHeaders = headerContainer.getHeaders();
}
```
which works fine when the rest client is called from a rest endpoint's body (headers are: `[Host=[localhost:8080], User-Agent=[...]]` in the `ClientHeadersFactory`) but turns out empty when called in the identity augmentor.

**Comment by michalvavrik** [comment]
@WollfieGitHub yes, that is because `HeaderCapturingServerFilter` is only applied when RESTEasy Reactive processing has begun, but as you are using proactive authentication, call to your augmentor is happening before any Jakarta REST filter is invoked.

I don't agree this is bug, but we should document this.

**Comment by michalvavrik** [comment]
@WollfieGitHub let's try

```
RoutingContext ctx = identity.getAttribute(RoutingContext.class.getName());
		if (ctx != null) {
			var headers = ctx.request().headers();
		}
```

**Comment by WollfieGitHub** [comment]
Within the augmentor, ctx is null apparently :/

**Comment by WollfieGitHub** [comment]
According to https://quarkus.io/guides/security-architecture, the HttpAuthMechanism might be the only thing that has access to the request context before the augmentor is invoked, so one ugly workaround would be to do a capture-all, fails-always (with `Uni.createFrom().nullItem()` so it delegates to the actual auth mechanism) authentication mechanism and within `authenticate`:

```java
@Inject CustomHeaderContainer headerContainer;

@Override
public int getPriority() {
  return Integer.MAX_VALUE;
}

@Override
@ActivateRequestContext
public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
  headerContainer.register(context);
  return Uni.createFrom().nullItem();
}

@Override
public Set<Class<? extends AuthenticationRequest>> getCredentialTypes() {
  return Set.of(
	AnonymousAuthenticationRequest.class,
	BaseAuthenticationRequest.class,
	CertificateAuthenticationRequest.class,
	TokenAuthenticationRequest.class,
	TrustedAuthenticationRequest.class,
	UsernamePasswordAuthenticationRequest.class
  );
}
// CustomHeaderContainer.java:

@Alternative
@Priority(Integer.MAX_VALUE)
@RequestScoped
public class CustomHeaderContainer
	extends HeaderContainer
{
	private RoutingContext requestContext;

  public CustomHeaderContainer() {
  }

  public void register(RoutingContext requestContext) {
    this.requestContext = requestContext;
  }

	@Override
	public MultivaluedMap<String, String> getHeaders() {
		return new MultivaluedHashMap<>(
			this.requestContext.request().headers().entries().stream().collect(Collectors.toMap(
				Map.Entry::getKey, Map.Entry::getValue
			))
		);
	}
}

```
But it's really ugly :/

After trying it, it works with @ApplicationScoped on the CustomHeaderContainer but not with the @RequestScoped for which the getHeaders() seems to be invoked on another instance...

**Comment by michalvavrik** [comment]
> Within the augmentor, ctx is null apparently :/

In your case, it is only `null` because your identity is anonymous, but if you send correct credentials it should not be null. I have PR that fixes it for anonymous identity https://github.com/quarkusio/quarkus-security/pull/40 but it is probably a long shot.

> After trying it, it works with @ApplicationScoped on the CustomHeaderContainer but not with the @RequestScoped for which the getHeaders() seems to be invoked on another instance...

I think it's overkill. You don't need to do any of this with disabled proactive authentication, but here we are far away of bug, so I'll leave you to your experiments.

Glad you have workaround.

**Comment by WollfieGitHub** [comment]
I've noticed a new problem, which is linked to this one, should I open a new issue or develop it here ?

**Comment by michalvavrik** [comment]
> The problem is that this check doesn't involve the HeaderFactory at any point and thus, it fails based on the current identity of the app, and not the identity the HeaderFactory would have provided through an Authorization header it seems.

Yes, please create a separate issue with reproducer. I can't imagine how could that happen.
