### ISSUE TITLE
Missing "extension-status" tag in guides

### ISSUE THREAD

**Issue by albers** [quarkusio/quarkus#37941]
### Describe the bug

Two guides have an unresolved `extension-status` variable:
- https://quarkus.io/guides/cache
- https://quarkus.io/guides/security-oauth2

leading to this output
> This technology is considered {extension-status}.

This happens because the template `extension-status.adoc` is included without the variable `extension-status` being defined.

The two docs seem to be the only ones suffering from this problem:
```shell script
$ grep -Fl 'include::{includes}/extension-status.adoc[]' docs/src/main/asciidoc/*.adoc | xargs grep -L ^:extension-status:
docs/src/main/asciidoc/cache.adoc
docs/src/main/asciidoc/security-oauth2.adoc
```

### Expected behavior

The variable is resolved to an output such as _This technology is considered experimental._
Status specific information from the included template is displayed.

### Actual behavior

The variable is not resolved.
The included template content collapses to its minimal output.

### How to Reproduce?

Follow the links to the docs and take a look at the text right to the first blue info icon.

### Additional information

If someone could be so kind to provide the correct extension status here, I can provide a PR with a fix.

**Comment by melloware** [comment]
cc @holly-cummins

**Comment by geoand** [comment]
Thanks for spotting this!

@sberyozkin what is the status of `security-oauth2`?

**Comment by geoand** [comment]
Nevermind, #37999 takes care of it
