### ISSUE TITLE
Feature Request - Integration of Sa-Token with Quarkus for Reactive Applications

### ISSUE THREAD

**Issue by ByteByteBrew** [quarkusio/quarkus#37951]
### Description

Dear Quarkus Team,

  I am an enthusiastic user of Quarkus and extensively use it in my projects. Currently, I am exploring the integration of Sa-Token into Quarkus to provide authentication and authorization capabilities in my applications.
  
  I have successfully implemented a preliminary integration of Sa-Token with the non-reactive version of Quarkus. However, recognizing the importance of the reactive programming model in Quarkus for modern application development, I am keen to see full support for Sa-Token in this paradigm.
  
  Due to my technical limitations in implementing the reactive version, I have not been able to complete this part. Hence, I would like to propose a feature request for the Quarkus official team to consider integrating Sa-Token as part of the reactive applications support. Such integration would greatly enhance Quarkus's capabilities in handling modern, high-performance applications and provide more authentication and authorization options to the community users.
  
  I believe this integration would not only benefit my personal projects but also add value to the wider Quarkus developer community.
  
  Thank you for considering my request. I look forward to the possibility of this feature in future versions of Quarkus and am willing to provide any possible assistance and feedback.

### Implementation ideas

https://github.com/dromara/sa-token

**Comment by gastaldi** [comment]
We already have https://github.com/quarkiverse/quarkus-sa-token, maybe open a PR there if something is missing?

**Comment by sberyozkin** [comment]
@ByteByteBrew I believe you have to create a dedicated Quarkiverse extension for this project.
I'd also like to encourage you to review the existing Quarkus security features related to OIDC and OAuth2 support, authorization control, and see if some of the ideas from Sa-Token can be used to improve some of its features

**Comment by maxandersen** [comment]
Is that not what https://github.com/quarkiverse/quarkus-sa-token does or something different ?

**Comment by sberyozkin** [comment]
Great, thanks @gastaldi,  looks like it is the one.

**Comment by sberyozkin** [comment]
@maxandersen Yes, indeed

**Comment by gastaldi** [comment]
Closing according to the above comments

**Comment by sberyozkin** [comment]
Thanks @gastaldi @maxandersen, yes, I tried to use  the `Transfer issue`  option to move it  to https://github.com/quarkiverse/quarkus-sa-token, but it is not possible to transfer to Quarkiverse hosted repositories, it would be great if it were possible to enter complete repository URL (may be restricted to the Quarkiverse domain, though not sure if it can be done)

@ByteByteBrew Please continue in https://github.com/quarkiverse/quarkus-sa-token.

FYI, I haven't been aware of this project but I've looked at https://github.com/quarkiverse/quarkus-sa-token/blob/main/quarkus-sa-token-main/quarkus-sa-token-resteasy/integration-tests/src/main/java/io/quarkiverse/satoken/resteasy/it/integrate/LoginResource.java, may be this is something that you may want to re-implement as `HttpAuthenticationMechanism` . Similarly for https://github.com/quarkiverse/quarkus-sa-token/blob/main/quarkus-sa-token-plugins/quarkus-sa-token-sso/integration-tests/quarkus-sa-token-sso-server/src/main/java/io/quarkiverse/satoken/sso/SsoServerController.java

thanks
