### ISSUE TITLE
quarkus 2.7.x also encountered the "Rest client call hangs when receiving an invalid chunked" issue

### ISSUE THREAD

**Issue by Mhuang77** [quarkusio/quarkus#37950]
### Describe the bug

same issue as the https://github.com/quarkusio/quarkus/issues/36257

### Expected behavior

An invalid chunked response should not hang the client and resources should be properly released when the connection is closed.

### Actual behavior

The client call never completes and resources are not released.

**Comment by Mhuang77** [comment]
Can this patch be backported to the 2.7.x series?

**Comment by geoand** [comment]
2.7 is no longer supported.

Is there a reason you can upgrade to newer versions?
