### ISSUE TITLE
RabbitMQ Memory leak due to reconnection

### ISSUE THREAD

**Issue by Dosexe** [quarkusio/quarkus#37960]
### Describe the bug

After facing a rabbitmq reconnection `RabbitMQ connection shutdown! The client will attempt to reconnect automatically`
```java
com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - Node was put into maintenance mode, class-id=0, method-id=0)
  at com.rabbitmq.client.impl.AMQConnection.startShutdown:985
  at com.rabbitmq.client.impl.AMQConnection.shutdown:975
  at com.rabbitmq.client.impl.AMQConnection.handleConnectionClose:913
  at com.rabbitmq.client.impl.AMQConnection.processControlCommand:868
  at com.rabbitmq.client.impl.AMQConnection$1.processAsync:265
  at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand:182
  at com.rabbitmq.client.impl.AMQChannel.handleFrame:114
  at com.rabbitmq.client.impl.AMQConnection.readFrame:719
  at com.rabbitmq.client.impl.AMQConnection.access$300:47
  at com.rabbitmq.client.impl.AMQConnection$MainLoop.run:666
  at java.lang.Thread.run:829
```
Rabbitmq has a successful reconnection and then in a short period of time app goes out of memory due to either publishing or consumption problems after reconnection.
I believe this issue is fully or partially related to this one [https://github.com/quarkusio/quarkus/issues/33698](url).
The symptoms are the same. Messages are stuck in `io.vertx.rabbitmq.impl.RabbitMQPublisherImpl` in `pendingAcks` ArrayDeque
![image](https://github.com/quarkusio/quarkus/assets/26384615/b0f5e9fa-ab85-4d23-8597-3684105896a8)

### Expected behavior

After the rabbitmq reconnection app continues to work as usual.

### Actual behavior

Application goes out of memory

### How to Reproduce?

Should be the same as here [https://github.com/quarkusio/quarkus/issues/33698](url). However this time I was not able to easily reproduce that in `RabbitMQPublisherImpl`.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Homebrew (build 11.0.12+0) OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.4

**Comment by cescoffier** [comment]
Fixed already 

Please re-open if not (with a reproducer)
