### ISSUE TITLE
Add docker to windows build machine in quarkus-ci

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#3796]
**Description**
docker does not seem to be available on the quarkus-ci windows machine: https://github.com/quarkusio/quarkus/pull/2897#issuecomment-503878094
this limits the ability to do testcontainers style integration tests, such as:
https://github.com/vsevel/quarkus/blob/master/extensions/vault/deployment/src/test/java/io/quarkus/vault/VaultTestExtension.java#L110
as a result I had to disable those tests when running on windows for the vault extension.
it would be nice to have docker support on windows as well.

**Comment by loicmathieu** [comment]
:+1: same issue for the soon-to-be-merged-I-hope MongoDB with Panache extension.
