### ISSUE TITLE
Can't specify custom quarkus.profile when running tests

### ISSUE THREAD

**Issue by bitsofinfo** [quarkusio/quarkus#37962]
### Describe the bug

Neither `./gradlew -Dquarkus.profile=my-profile test` nor `QUARKUS_PROFILE=my-profile ./gradlew test` will run my tests using my configuration as defined in `src/main/resources/application-my-profile.yml`. It ignores this and just loads the `test` profile all the time. I can't get this to work in my IDE either when specifying these VM args or ENV vars and running there (intellij). How can I acheive this?

### Expected behavior

`./gradlew -Dquarkus.profile=my-profile test` should load my config located in `src/main/resources/application-my-profile.yml`

### Actual behavior

see above

### How to Reproduce?

see above

### Output of `uname -a` or `ver`

Darwin mn 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

latest

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------  Build time:   2023-11-29 14:08:57 UTC Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  Kotlin:       1.9.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.1 (Amazon.com Inc. 21.0.1+12-LTS) OS:           Mac OS X 14.2 aarch64

**Comment by bitsofinfo** [comment]
the only way I can acheive anything like this w/ unit tests is by using `@TestProfile` with a `getConfigProfile()` override that returns `my-profile`

**Comment by radcortez** [comment]
To use a different profile for testing, you should use `quarkus.test.profile`. This does work in Maven, but it seems that the Gradle worker is not getting this property correctly.

**Comment by bitsofinfo** [comment]
I'm using gradle. In intellij for my test run config, I specify VM args of `-Dquarkus.test.profile=test-mock` 

this doesn't work, it still just uses the default `test` profile no matter what

**Comment by bitsofinfo** [comment]
If I set the ENV var `QUARKUS_TEST_PROFILE=test-mock`  it does work.

**Comment by radcortez** [comment]
Yes, because both the main runner and the worker run in the same shell with the same env variables.

**Comment by bitsofinfo** [comment]
https://github.com/quarkusio/quarkus/issues/38424
