### ISSUE TITLE
Testing OIDC service with OidcWiremock section is not clear that it can not be used with Keycloak Authorization

### ISSUE THREAD

**Issue by appiepollo14** [quarkusio/quarkus#37967]
### Describe the bug

Following this [guide](https://quarkus.io/guides/security-oidc-bearer-token-authentication#integration-testing), I would like to use the OidcWiremockTestResource.class. However, when executing the test which is displayed in the guide, I get a 404 error:

```
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 404 / Not Found / Response from server: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
GET                                                        | GET
/auth/realms/quarkus/.well-known/openid-configuration      | /auth/realms/.well-known/uma2-configuration         <<<<< URL does not match
                                                           |
                                                           |
----------------------------------------------------------------------------------------------------------------------- 
```

### Expected behavior

Getting a 200 when executing the test.

### Actual behavior

Getting a 404 as mentioned.

### How to Reproduce?

Reproducer: 
[keycloak.zip](https://github.com/quarkusio/quarkus/files/13804939/keycloak.zip)

1. Run the UsersResourceTest

### Output of `uname -a` or `ver`

Darwin mn 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by sberyozkin** [comment]
@appiepollo14  Thanks for trying it. The reason this issue is not bug is because we have never documented that testing Keycloak authorization with the wiremock is possible. 

However I totally agree it would be a useful feature to have,  see #16276, and there was an attempt to complete it with the linked PR .

So, I believe we should close this issue.

In meantime,  I'd like to encourage you to give it a try and complete that PR linked to from #16276
Thanks

**Comment by appiepollo14** [comment]
@sberyozkin hmm, the link I've sent, point to a header with specified how to use WireMock for testing OIDC. So how is this not documented then?

**Comment by sberyozkin** [comment]
@appiepollo14 Fair enough, I'll close this issue by updating that section with a note that testing OIDC service applications with OidcWiremock is not possible when Keycloak authorization is required

**Comment by appiepollo14** [comment]
I understand the difference now! Thanks.
