### ISSUE TITLE
Kafka Devservices Redpanda expose Pandaproxy/Http Proxy

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#37970]
### Description

Redpanda ships with [pandaproxy](https://docs.redpanda.com/current/develop/http-proxy/), a http proxy to access topics, produce events and so on. The proxy is enabled by default on port 8082, but not exposed through the Testcontainers implementation (see [here](https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/RedPandaKafkaContainer.java#L95)).

The http proxy could be useful for scripted setups, debugging or e2e testing with third party tools.

### Implementation ideas

Expose port 8082 for the [RedPandaKafkaContainer](https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-client/deployment/src/main/java/io/quarkus/kafka/client/deployment/RedPandaKafkaContainer.java#L20C30-L20C30), port could be made configurable.

**Comment by ozangunalp** [comment]
Thanks for bringing this up. Would you want to contribute to that? @stephan-strate

**Comment by stephan-strate** [comment]
> Thanks for bringing this up. Would you want to contribute to that? @stephan-strate

Sure. What do you think about the config parameter naming?
`quarkus.kafka.devservices.redpanda.proxy-port` with default random?
