### ISSUE TITLE
Add graal vm to build machines

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#3797]
**Description**
when running the native integration tests, my understanding is that we need to add the graal libraries when exercising tls communications.
If graal was available on the build machine, we could refer to its libraries from the GraalITCase tests.

**Implementation ideas**
for the vault extension, I created a VaultTestLifecycleManager that [adds the java.library.path to the runner](https://github.com/quarkusio/quarkus/blob/master/test-framework/vault/src/main/java/io/quarkus/vault/test/VaultTestLifecycleManager.java#L28).
by default the vault native tests do not use tls (which requires the libs). to enable it, one has to explicitly use system property `vault-test-extension.use-tls` and set it to true.
this allows running tests from a quarkus native app and a service (eg: vault) using tls.
if graal was available on the build machine, then we could always tls between the vault test app and vault, which is better setup to test against.
see also [VaultTestExtension](https://github.com/quarkusio/quarkus/blob/master/test-framework/vault/src/main/java/io/quarkus/vault/test/VaultTestExtension.java#L239-L241) and [pom.xml](https://github.com/quarkusio/quarkus/blob/master/integration-tests/vault-app/pom.xml#L147-L152)

**Comment by sberyozkin** [comment]
@vsevel Can you please update the links, thanks

**Comment by vsevel** [comment]
@sberyozkin done
