### ISSUE TITLE
Provide a way for applications to contribute to the `/info` enpoint

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#37994]
### Description

As of now, the only way to contribute to the `/info` endpoint offered by the quarkus-info extension is to create an extension that can produce `InfoBuildTimeContributorBuildItem`. 

It woud be great to be able to contribute to the endpoint without having to create an extension.

If the extension scan for application defined `InfoContributor` classes, anyone could contribute to the endpoint, kind of how it's done for smallrye-health.

I can try to provide an MR if you like.

**Comment by geoand** [comment]
I think that when there are beans of this class, should include them automatically

**Comment by jtama** [comment]
yes it should not be hard to implement with an `ApplicationIndexBuildItem`. I can provide a PR if you want

**Comment by geoand** [comment]
That would be nice!

**Comment by melloware** [comment]
This is great I would definitely use this for QuarkusFaces to expose the JSF version information.

**Comment by jtama** [comment]
@melloware QuarkusFaces beeing an extension you already can by providing a build item.
