### ISSUE TITLE
integration-tests/kafka-sasl-elytron tests modify files in src/test/resources

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#38002]
When executing the tests in `integration-tests/kafka-sasl-elytron`, we end up with the following `git status`:

```
On branch main
Your branch and 'origin/main' have diverged,
and have 623 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/test/resources/client.keytab
	modified:   src/test/resources/kafkabroker.keytab
```

Resources committed to the Git repository shouldn't be modified by the tests, this needs fixing.

**Comment by gsmet** [comment]
@ozangunalp could you have a look at this? I fear it might end up breaking some workflow somewhere.

**Comment by ozangunalp** [comment]
@gsmet ok! I think I know the fix, let me look at this asap.
