### ISSUE TITLE
Missing security requirement on operation level, declared @RolesAllowed in implementing class derived from a generated openapi java interface

### ISSUE THREAD

**Issue by luechtdiode** [quarkusio/quarkus#38026]
**Describe the bug**

With a `@RolesAllowed` annotated class, that implements a openapi rest java-interface, there is no `security` defined in the generated `openapi.yaml`:
```yaml
openapi: 3.0.3
paths:
  /secured/foo:
    get:
      responses:
      ...
components:
  securitySchemes:
    oidc_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: redacted
          tokenUrl: redacted
          refreshUrl: redacted
          scopes:
            openid: openid
```

**Expected behavior**
[quarkus.smallrye-openapi.auto-add-security-requirement](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.auto-add-security-requirement) specifies, that

_This will automatically add the security requirement to all methods/classes that has a RolesAllowed annotation._

```yaml
openapi: 3.0.3
paths:
  /secured/foo:
    get:
      responses:
      ...
      security:
      - oidc_auth: []
components:
  securitySchemes:
    oidc_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: redacted
          tokenUrl: redacted
          refreshUrl: redacted
          scopes:
            openid: openid
```

**How to reproduce**
Quarkus 3.6.1 with jdk 17 quarkus-starter project.
```bash
Installed features: [cdi, config-yaml, hibernate-validator, micrometer, oidc, rest-client, rest-client-jackson, resteasy, resteasy-jackson, security, smallrye-context-propagation, smallrye-health, smallrye-openapi, swagger-ui, vertx]
```
Implementation
```java
import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;
import org.eclipse.microprofile.openapi.annotations.security.SecurityScheme;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

@ApplicationPath("/")
@SecurityScheme(ref = "oidc_auth")
public class ApplicationContext extends Application {}

@Path("/secured/foo")
public interface FooAPI {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    Response getFoo();
}

@RolesAllowed("RoleXY")
public class FooRessource implements FooAPI {
    @Override
    public Response getFoo() {
        return Response.ok("ok").build();
    }
}
```
No overrides in `application.properties` about [quarkus.smallrye-openapi.auto-add-security-requirement](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.auto-add-security-requirement), which defaults to `true`.

**Probably affected code**
Probably, the code here should be enhanced to take care of Rest endpoints declared on interface-level:
https://github.com/quarkusio/quarkus/blob/2e6fe10c0ed051e94ebe52325b3bbb6be5fa5916/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L610-L637
https://github.com/quarkusio/quarkus/blob/3.6.4/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L610-L638

**Workaround**
My current workaround is to write a `OASFilter` implementing `public Operation filterOperation(Operation operation)` that adds the missing security-scheme.

**Comment by psini** [comment]
I have the same issue but not with the generated code, on quarkus 3.8.3 it works, but upgrading to 3.9.2 it's broken . 
I have an interface where i define my endpoints so i can use it also as a client, and RolesAllowed in the implementing class. 
When I call it i get a forbidden request (my default policy is deny). 
In debug i saw that in EagerSecurityFilter 
https://github.com/quarkusio/quarkus/blob/510e89e20516ee7fc5d535c6758a777d53838bcc/extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/EagerSecurityFilter.java#L71-L80
at line 73 the   var description contains the interface and not the implementation class.

**Comment by phillip-kruger** [comment]
@psini seems like you have a different issue. Please log a separate bug with a reproducer
