### ISSUE TITLE
Move the static file support to Vert.x

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3802]
**Description**
When undertow is not present, we need to serve static files using Vert.x (Static File Handler from Vert.x Web).

It includes:

* [ ] - Detecting when undertow is not available and register the static file handler
* [ ] - Chain the static file handler in hot reload mode
* [ ] - Share a common configuration (such as `http.file` between the undertow and vert.x to configure the locations, cache, compressed media types...
* [ ] - Move the code registering the file into the native executable to the Vert.x extension

**Comment by gsmet** [comment]
This has been done.
