### ISSUE TITLE
Quarkus OIDC extension - Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#38037]
### Describe the bug

Trying to navigate to the home page of a webapp using the OIDC extension raises `We are sorry: invalid parameter: redirect_uri`. The given URL is `redirect_uri=http%3A%2F%2Flocalhost%3A8082%2F` i.e. `redirect_uri=http://localhost:8082/` which is also the webapp's context root. 

The keycloak server is listening on `http://localhost:8080`. The properties which trigger the exception are:

    quarkus.http.auth.permission.authenticated.paths=/*
    quarkus.http.auth.permission.authenticated.policy=authenticated

Commented them out, the exception disappear but, of course, there is not authentication neither.

### Expected behavior

The expected behaviour would be that the Keycloak login scree be displayed and let the user authenticate, after which to go back to the webapp's home page.

### Actual behavior

The Keycloak login screen isn't displayed and the mentioned exception appears.

### How to Reproduce?

It's complicated to provide a reproducer as this involves a keycloak server, with a specific realm, in addition to a webapp.

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-91-generic", arch: "amd64", family: "unix"

**Comment by sberyozkin** [comment]
@nicolasduminil I'm not sure there is a bug issue here, the properties which you have listed enforce the authentication, they don't trigger the exception. Quarkus OIDC creates an authentication challenge leading to the redirect to Keycloak, and if you do not configure `quarkus.oidc.authentication.redirect-path` then `redirect_uri` is set to the current request url, for example, if you accessed Quarkus with `http://localhost:8082` then it will become a `redirect_uri` (callback) parameter passed to Keycloak.

Looks like you have not configured Keyloak - you should configure the client redirect properties to accept  `http://localhost:8082/`

**Comment by nicolasduminil** [comment]
I'm not sure neither whether this is a bug but the behavior that I got in my test.
"... they don't trigger the exception." Well, they do since the exception appears as long as the properties are defined and when they are removed the exception disappears.
"... if you do not configure `quarkus.oidc.authentication.redirect-path` then `redirect_uri` is set to the current request url ...". I don't configure `quarkus.oidc.authentication.redirect-path` and the `redirect_uri` is set, as a matter of fact, to the current URL which is, in fact, what I want. Do you mean that I have to configure `quarkus.oidc.authentication.redirect-path` ? Probably not. I any case, the question is: if the `redirect_uri` is set to the current URL (here http://localhost:8082), why do I get `invalid parameter: redirect_uri` ? The `redirect_uri` parameter isn't invalid since it's the webapp context root.
"Looks like you have not configured Keycloak ..." Not sure what exactly do you mean.
"You should configure the client redirect properties ...". Not sure what client are you referring to as this is an webapp and, hence, the client is the browser. Would you mind to mention exactly what are the client redirect properties that have to be configured ?

**Comment by nicolasduminil** [comment]
Ah, I see, by "client" you probably mean the Keycloak client, right ? In this case the client is configured as shown in the file below:

[fe-client.json](https://github.com/quarkusio/quarkus/files/13833146/fe-client.json)

**Comment by sberyozkin** [comment]
@nicolasduminil It should be `*` I believe if you'd like to set allowed redirect URIs to a wildcard value - at least this is what Keycloak Dev Service has. 
Give it a try please - I have to close this issue as Quarkus behaves correctly, FYI, it acts as a confidential OIDC client application - you have come to the right conclusion, thanks.

**Comment by sberyozkin** [comment]
@nicolasduminil Just one clarification,

>why do I get invalid parameter: redirect_uri ? The redirect_uri parameter isn't invalid since it's the webapp context root.

One important point is that Quarkus does not control how Keycloak or indeed any other OIDC providers checks the validity - Quarkus's job is to provide the correct callback/redirect URI as far as the Quarkus application is concerned - but it is a Keycloak administration task to make sure such redirect URIs are accepted.

HTH, ping me please on Discussions/Zulip if I can be of further help, thanks

**Comment by nicolasduminil** [comment]
Yes, this was it, changing the following line:

    "redirectUris" : [ "/*" ]

by the one:

    "redirectUris" : [ "*" ]

in the Keycloak client JSON definition file, solves the issue.

Many thanks for your help and support.

Kind regards,

Nicolas

**Comment by sberyozkin** [comment]
@nicolasduminil Indeed, glad you made it work, thanks
