### ISSUE TITLE
Thread locked with optimize-contexts and @Startup bean

### ISSUE THREAD

**Issue by lucaspouzac** [quarkusio/quarkus#38040]
### Describe the bug

Since migration to quarkus 3.6.x, our application don't startup because a thread is locked.

It's related to this feature : https://github.com/quarkusio/quarkus/pull/36626

If we set `quarkus.arc.optimize-contexts=false`, the application start correctly.

### Expected behavior

If we set `quarkus.arc.optimize-contexts=true`, the application start correctly.

### How to Reproduce?

Attached, an application with 2 tests.

- 1 test that works correctly: **OptimizeContextsDisabledTest**
- 1 test that fails: **OptimizeContextsEnabledTest**

[optimize-contexts.tar.gz](https://github.com/quarkusio/quarkus/files/13833172/optimize-contexts.tar.gz)

**Comment by mkouba** [comment]
> @mkouba could you check it's the same issue that you already solved or if it's different?

I can confirm that it's the same kind of problem and I've just verified that https://github.com/quarkusio/quarkus/pull/37982 fixed this problem. In this particular case, an external service is called in the bean constructor (the rest client offloads the execution to a different thread ) which has the same effect as if it was called in a `@PostConstruct` callback a la #37958.

**Comment by mkouba** [comment]
@lucaspouzac another workaround is to use a `@Startup` method or an observer method instead of the bean constructor:
```java
@ApplicationScoped
public class BootService {
    private final ConfigService configService;

    @Inject
    public BootService(@RestClient ConfigService configService) {
        this.configService = configService;
    }

    @Startup
    void onStart() {
       // Sync for startup
       updateCache().await().atMost(Duration.ofSeconds(1));
    }

    Uni<Void> updateCache() {
        return configService.getConfiguration().chain(item -> Uni.createFrom().voidItem());
    }
}
```

**Comment by mkouba** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/37982 and backported in https://github.com/quarkusio/quarkus/pull/38069.
