### ISSUE TITLE
gRPC client over TLS not working

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#38067]
### Describe the bug

I'm using a gRPC client and setting the following to connect to a gRPC service which is behind TLS/HTTPS:

```properties
quarkus.grpc.clients."client-name".use-quarkus-grpc-client=true
quarkus.grpc.clients."client-name".host=somehost
quarkus.grpc.clients."client-name".port=443
quarkus.grpc.clients."client-name".plain-text=false
```

When I do this the gRPC request fails. If I remove `quarkus.grpc.clients."client-name".use-quarkus-grpc-client=true` (or set it to `false`), then things start working.

**Comment by alesj** [comment]
@edeandrea how do you configure the server side in this case?
Or how should I to reproduce this?

**Comment by edeandrea** [comment]
This is in the quarkus superheroes sample application. The gRPC client (`rest-fights`) does not use the gRPC server. It only makes calls to the `grpc-locations` service.

The client config is in https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/main/resources/application.properties. You'll notice in there that I've commented out the `use-quarkus-grpc-client`.

When grpc-locations is deployed behind https is when this breaks.

See https://github.com/quarkusio/quarkus-super-heroes/blob/6ae423fee41420a54b57a1c06fe2526960d11215/scripts/deploy-to-azure-containerapps.sh#L383_L395

This script is used when we deploy the system into Azure Container Apps. In that case, if `use-quarkus-grpc-client==true` then the client fails to connect.

**Comment by alesj** [comment]
#38092 should fix this, imho

**Comment by edeandrea** [comment]
Would you like me to try it and let you know?

**Comment by alesj** [comment]
Yeah, that would be great, tnx.

**Comment by edeandrea** [comment]
I can confirm this does fix the problem
