### ISSUE TITLE
Quarkus build compatible with Github Codespaces

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#38074]
### Description

When we fork quarkus to contribute the project takes forever in Github Codespaces with 4 core 16GB Ram. Is there anything to be done to make it build successfully in github codespaces. Most of the time the initial project load in vscode timeout with memory constraints.

### Implementation ideas

Provide steps to control the initial Quarkus setup in github codespaces for contributers in https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md

**Comment by maxandersen** [comment]
Open smaller portions is the way to go. That is unfortunately not something Github Codespaces does well.
