### ISSUE TITLE
Upcoming 6.10 version of Fabric8 Kubernetes client breaks native builds

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#38098]
### Describe the bug

Seems like the update that was made to commons-compress causes new code paths to be looked at and triggers build issues. See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Native.20build.20issue.20with.20Fabric8.206.2E10.20snapshot for more details.

/cc @manusa 

### Actual behavior

The issue can be seen in https://github.com/quarkiverse/quarkus-operator-sdk/actions/runs/7154496787/job/19482088987#step:9:554 for example.

**Comment by metacosm** [comment]
Looks like the issue is gone.

**Comment by manusa** [comment]
This might be related to this specific issue:

https://github.com/eclipse/jkube/pull/2532#issuecomment-1893115225
