### ISSUE TITLE
quarkus-mongodb-client ReactiveMongoCollection expose the Updates with Aggregation Pipeline method

### ISSUE THREAD

**Issue by kuoche1712003** [quarkusio/quarkus#38114]
### Description

I want to use the mongo client with the [findOneAndUpdate](https://github.com/mongodb/mongo-java-driver/blob/master/driver-reactive-streams/src/main/com/mongodb/reactivestreams/client/MongoCollection.java#L1318) method.

I have observed that the quarkus-mongodb-client [ReactiveMongoCollection](https://github.com/quarkusio/quarkus/blob/main/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/reactive/ReactiveMongoCollection.java#L1171C12-L1171C28) currently does not expose the method.

I've noticed that none of the methods related to updates in the quarkus-mongo-client ReactiveMongoCollection include the Updates with Aggregation Pipeline functionality.

### Implementation ideas

The ReactiveMongoCollection interface adds methods related to Updates with Aggregation Pipeline and implements them.

```java
...

    Uni<T> findOneAndUpdate(Bson filter, List<? extends Bson> update);
    
    Uni<T> findOneAndUpdate(Bson filter, List<? extends Bson> update, FindOneAndUpdateOptions options);

    Uni<T> findOneAndUpdate(ClientSession clientSession, Bson filter, List<? extends Bson> update);

    Uni<T> findOneAndUpdate(ClientSession clientSession, Bson filter, List<? extends Bson> update,
                                           FindOneAndUpdateOptions options);
...                                           
```

**Comment by kuoche1712003** [comment]
@loicmathieu Thank you for your help.

Acutal the updateOne and updateMany have some problem.

```java
    Publisher<UpdateResult> updateOne(Bson var1, List<? extends Bson> update);

    Publisher<UpdateResult> updateOne(Bson filter, List<? extends Bson> update, UpdateOptions options);

    Publisher<UpdateResult> updateOne(ClientSession clientSession, Bson filter, List<? extends Bson> update);

    Publisher<UpdateResult> updateOne(ClientSession clientSession, Bson filter, List<? extends Bson> update, UpdateOptions options);

    Publisher<UpdateResult> updateMany(Bson filter, List<? extends Bson> update);

    Publisher<UpdateResult> updateMany(Bson filter, List<? extends Bson> update, UpdateOptions options);

    Publisher<UpdateResult> updateMany(ClientSession clientSession, Bson filter, List<? extends Bson> update);

    Publisher<UpdateResult> updateMany(ClientSession clientSession, Bson filter, List<? extends Bson> update, UpdateOptions options);
```

**Comment by loicmathieu** [comment]
@kuoche1712003 which problem? DO you mean those methods are also missing?

**Comment by kuoche1712003** [comment]
@loicmathieu yes,  those methods are also missing

**Comment by loicmathieu** [comment]
OK, I'll add them also then

**Comment by loicmathieu** [comment]
PR updated, I check and that all methods that was added in Mongo 4.2 so we should be OK now.
Thanks for listing them.
