### ISSUE TITLE
Allow for creation of non-compressed jars

### ISSUE THREAD

**Issue by mavstuff** [quarkusio/quarkus#38128]
### Description

Please add option to tune uber-jar compression

**Comment by geoand** [comment]
Could you please elaborate a little more about what you have in mind?

**Comment by mavstuff** [comment]
> Could you please elaborate a little more about what you have in mind?

I have a Quarkus project that produces *-runner.jar  and I was trying to disable compression for this jar to make some experiments. I found that setting _compress=false_ for [maven-jar-plugin](https://stackoverflow.com/questions/1032685/how-to-turn-off-jar-compression-in-maven) does not affect the -runner.jar. The compression is set by [quarkus-fs-util ](https://github.com/quarkusio/quarkus-fs-util/blob/main/src/main/java/io/quarkus/fs/util/ZipUtils.java)and is not adjustable.

**Comment by mavstuff** [comment]
> Maybe I ask what the use case for an uncompressed jar is?

test the processing speed on a low-resource platform

**Comment by geoand** [comment]
Understood. 

I guess we could have a version of `ZipUtils.newZip` that allows the call site to pass in a custom `env` and we could populate that when building the jars (if necessary).

WDYT @aloubyansky? 

@Sanne this is something you might  interested in as well.

**Comment by aloubyansky** [comment]
Sounds good to me, thanks!

**Comment by geoand** [comment]
Cool, I'll take care of this this week.

**Comment by geoand** [comment]
#38136 adds this capability
