### ISSUE TITLE
Changing Accept Header in PreMatching filter doesn't affect routing

### ISSUE THREAD

**Issue by myroch** [quarkusio/quarkus#38130]
### Describe the bug

After the switch to resteasy reactive my request filters don't work anymore.

### Expected behavior

Accept Header set in the **pre-matching** request filter shall decide the routing to the resource.

### Actual behavior

Setting the Accept Header inside the pre-matching request filter doesn't affect routing.

### How to Reproduce?

Having following filter:
```java
@PreMatching
@Provider
public class SetAcceptHeaderFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) {
        requestContext.getHeaders().putSingle(HttpHeaders.ACCEPT, MediaType.TEXT_PLAIN);
    }
}
```
and following Resource:
```java
@Path("/hello")
public class GreetingResource {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response helloText() { return Response.ok("correct").build(); }

    @GET
    @Produces(MediaType.TEXT_HTML)
    public Response helloHtml() { return Response.ok("shall not happen").build(); }
```
Try to call it from the browser.

### Output of `java -version`

java 17.0.9 2023-10-17 LTS

### Quarkus version or git rev

2.6.12.Final and 3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

Do you know some workaround to this issue? Such a thing shall be pretty common. I'm trying to implement CXF's __type_ Query Parameter,

**Comment by geoand** [comment]
Thanks for reporting. https://github.com/quarkusio/quarkus/pull/38131 fixes the issue
