### ISSUE TITLE
dynamic feature applies to microprofile rest clients as well

### ISSUE THREAD

**Issue by sostrich** [quarkusio/quarkus#38142]
### Describe the bug

Jakarta specs say about DynamicFeature "[Dynamic feature is used by JAX-RS runtime to register providers that shall be applied to a particular resource class.](https://jakarta.ee/specifications/restful-ws/3.0/apidocs/jakarta/ws/rs/container/dynamicfeature)"

So it should be applied to resource classes, not to a rest client  - not sure what that would even look like :)

Haven't had the chance to look, is it simply because it checks for @Path annotations?

### Expected behavior

DynamicFeature#configure(ResourceInfo resourceInfo, FeatureContext context) should not be called for microprofile rest clients

### Actual behavior

DynamicFeature#configure(ResourceInfo resourceInfo, FeatureContext context) is called for microprofile rest clients:
![image](https://github.com/quarkusio/quarkus/assets/82578679/ae07d16b-dd38-441f-8dad-3e0b3a9635f2)

### How to Reproduce?

https://github.com/sostrich/quarkus-dynamicfeature-bug-reproducer/blob/main/src/test/java/org/acme/GreetingResourceTest.java

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by geoand** [comment]
Very interesting! 

I'll have a look

**Comment by sostrich** [comment]
Thanks! fyi: in the reproducer the rest client is a nested class of a resource, but the behaviour was the same if it was it's own class, so that's not the problem.

**Comment by geoand** [comment]
I don't see anywhere it being mentioned that `DynamicFeature` is only for the server, so I am not going to change anything around it's handling.

However in your case the solution is easy, just add

```
@ConstrainedTo(RuntimeType.SERVER)
```

to `MyDynamicFeature`

**Comment by sostrich** [comment]
fascinating, then I had a different understanding based on the sentence above I quoted in the bug description. But I will happily accept yours, and thanks for providing the solution for it.

**Comment by geoand** [comment]
👌
