### ISSUE TITLE
Quarkus returns rest client response instead of resource response when rest client calls the another endpoint in the api

### ISSUE THREAD

**Issue by sostrich** [quarkusio/quarkus#38140]
### Describe the bug

If you call a rest resource with an endpoint ENDPOINT_1 and inject a rest client, which calls another endpoint ENDPOINT_2 in the same API (i.e. "localhost:8081/...), the resource does not return the response specified in ENDPOINT_1, but returns the response the rest client got from endpoint 2

### Expected behavior

the response specified in ENDPOINT_1  should be returned

### Actual behavior

the response specified in ENDPOINT_2 is returned

### How to Reproduce?

https://github.com/sostrich/quarkus-recursive-restclient-bugreproducer/blob/main/src/test/java/org/acme/GreetingResourceTest.java

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by geoand** [comment]
I see in your test does:

```java
@Test
    //this fails as the response from the endpoint called by the api internally is returned
    void testSelfCall() {
        given()
          .when()
                .accept(MediaType.TEXT_PLAIN)
                .get("/hello/self-call")

          .then()
             .statusCode(200);
    }
```

and the endpoint hit is:

```java
    @GET()
    @Path("self-call")
    @Produces(MediaType.TEXT_PLAIN)
    public Response callOwnApi() {
        try (var restClientResponse = restClient.selfCall()) {
            //do nothing with it
        }

        return Response
                .status(200).build();
    }
```

while the client is:

```java
    @RegisterRestClient(baseUri = "http://localhost:8081")
    public interface ExampleRestClient {
        @GET
        @Path("/hello/402")
        Response selfCall();
    }
```

The test is **not**  correct because the client is calling an endpoint that does **not** exist, so an exception is thrown.

**Comment by sostrich** [comment]
@geoand Thanks for the quick response! but... there are two endpoints in the resource in my reproducer.

[link to second endpoint that is called by the rest client in the first endpoint](https://github.com/sostrich/quarkus-recursive-restclient-bugreproducer/blob/153cf374686db035ef36cc302392e1f88ddc00d9/src/main/java/org/acme/GreetingResource.java#L47C1-L47C1)

And I'm getting a 402 status code back in the test in intellij.  If the endpoint really didn't exist, then I wouldn't get back the 402.
![image](https://github.com/quarkusio/quarkus/assets/82578679/8274e7e1-0cd4-4d15-a16e-dee4a30bce68)

**Comment by geoand** [comment]
Oh sorry, I didn't see 

```java
    @GET
    @Path("402")
    public Response return402() {
        return Response.status(402).entity("{}").build();
    }
```

at all.

I'll have another look

**Comment by geoand** [comment]
So what happens here in that the REST Client thrown an exception when a non 2xx response code is returned.
You essentially need to use an `ResponseExceptionMapper` to handle the exception

**Comment by geoand** [comment]
That is likely due to how RESTEasy handles things... 

If you use `quarkus-resteasy-reactive` and `quarkus-rest-client-reactive` (which is the stack we are focusing our efforts on), you won't have that problem

**Comment by sostrich** [comment]
understood, thanks!

**Comment by geoand** [comment]
🙏🏼
