### ISSUE TITLE
Using http filter config is disabling CORS options

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#38155]
### Describe the bug

When using a filter, it doesn't add the CORS headers anymore.

```properties
quarkus.resteasy-reactive.path=/api

quarkus.http.filter.api.header."X-Content-Type-Options"=nosniff
quarkus.http.filter.api.header."X-Frame-Options"=deny
quarkus.http.filter.api.header."Strict-Transport-Security"=max-age=31536000; includeSubDomains
quarkus.http.filter.api.header."Content-Security-Policy"=default-src 'none';
quarkus.http.filter.api.matches=/api/.+
quarkus.http.filter.api.order=1

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
```

### Expected behavior

The cors headers (**or any header that is set up elsewhere**) should be added in addition to the other headers

### Actual behavior

The cors headers are removed

### How to Reproduce?

Clone this and start https://github.com/ia3andy/reproducer-cors with `quarkus dev`

Use this in you browser console (on a tab with a different domain opened):
```javascript
fetch("http://localhost:8080/api/hello").then(r => r.text()).then(console.log)
```
It fails with CORS error.
Remove the filter from the properties and it works.

<img width="774" alt="image" src="https://github.com/quarkusio/quarkus/assets/2223984/4c069955-69cd-4560-b0fb-11db65e6125c">

### Quarkus version or git rev

3.5+

**Comment by ia3andy** [comment]
any page

**Comment by geoand** [comment]
I tried with Chrome and it only worked on localhost:8080 whether the filter was active or nor

**Comment by ia3andy** [comment]
Ok so sorry, I thought it was any page but no, you need to test it from a page with another domain:
<img width="788" alt="image" src="https://github.com/quarkusio/quarkus/assets/2223984/bf5a8ff0-cea7-43eb-b72d-4f2f4d5eeb5d">

On the screenshot, first request is with the filter, the second without

**Comment by ia3andy** [comment]
cc @sberyozkin

**Comment by ia3andy** [comment]
@geoand did you reproduce?

**Comment by ia3andy** [comment]
this is a nasty bug

**Comment by geoand** [comment]
Yeah, I'll have a fix soon

**Comment by sberyozkin** [comment]
Thanks @ia3andy @geoand, I was on PTO
