### ISSUE TITLE
First access to static resource yields 404

### ISSUE THREAD

**Issue by cruftex** [quarkusio/quarkus#38174]
### Describe the bug

When a static resource is configured according to the manual, like this:

````
public class StaticResources {

    void installRoute(@Observes StartupEvent startupEvent, Router router) {
        router.route()
                .path("/static/*")
                .handler(StaticHandler.create("static/"));
    }
}
````

The file that is requested first yields a 404, even if it exists.

### Expected behavior

````
$ wget localhost:8080/static/1
--2024-01-13 15:46:31--  http://localhost:8080/static/1
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK

$ wget localhost:8080/static/2
--2024-01-13 15:46:33--  http://localhost:8080/static/2
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
````

### Actual behavior

````
$ wget localhost:8080/static/1
--2024-01-13 15:37:06--  http://localhost:8080/static/1
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 404 Not Found

$ wget localhost:8080/static/2
--2024-01-13 15:37:07--  http://localhost:8080/static/2
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
````

### How to Reproduce?

1. Configure static resources like above
2. Place files in `resources/static`: file `1` and file `2`
3. A minimal application can be found at: https://github.com/cruftex/quarkus-static-resources
4. Package and run
5. Request `/static/1` yields 404, request to `/static/2` is okay

### Output of `uname -a` or `ver`

Linux solid 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.6

### Additional information

The problem is caused by different path interpretation when the Vert.x filesystem cache is initially empty.
The problem can be mitigated by either:

1. Change line `.handler(StaticHandler.create("static/"));` to `.handler(StaticHandler.create("static"));`
2. Or access the Vert.x filesystem during startup, like `vertx.fileSystem().exists("static/1")`

**Comment by mkouba** [comment]
Interesting. Two things. Firstly, I was not able to reproduce the problem in the dev mode. Secondly, it's not only the first access - I get 404 for every HTTP GET `localhost:8080/static/1` in case of it's accessed first. If I try to access `localhost:8080/static/2` first then I get 404 for the every GET `static/2`.

**Comment by cruftex** [comment]
@mkouba 
That's correct. Your results are consistent with my observations.

I assume the dev mode is scanning the jar contents, so at first request it is already unpacked and cached on vert.x file system level.

>  I get 404 for every HTTP GET localhost:8080/static/1 in case of it's accessed first.

That is because there is another cache layer on top which also does negative caching, so it caches that the file is not existent.

**Comment by cescoffier** [comment]
I was not able to reproduce it with 4.15.1 (using the reproducer).
Please re-open with an updated reproducer if the issue happens again.
