### ISSUE TITLE
3.6: Broken links in security-oidc-bearer-token-authentication-tutorial

### ISSUE THREAD

**Issue by mcollovati** [quarkusio/quarkus#38172]
**Describe the bug**

The `security-oidc-bearer-token-authentication-tutorial` guide contains a couple of broken links to other Quarkus guides.
For example, in the [Run the application in dev mode](https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial#keycloak-dev-mode) there are links to `Dev Services for Keycloak` and `Dev UI` pages whose links are:

https://quarkus.io/guides/%7Bquarkusio-guides%7D/security-openid-connect-dev-services
https://quarkus.io/guides/%7Burl-quarkusio-guides%7Ddev-ui

The issue seems to be the usage of the `{quarkusio-guides}` and `{url-quarkusio-guides}` variables to create the links.

https://github.com/quarkusio/quarkusio.github.io/blob/11827a0dab55be25ce5fd54f5fd9513dd44f319c/_guides/security-oidc-bearer-token-authentication-tutorial.adoc?plain=1#L265-L266

**Which pages**

https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/security-oidc-bearer-token-authentication-tutorial.adoc

https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial

**Comment by gsmet** [comment]
@quarkusio/documentation `{quarkusio-guides}` and `{url-quarkusio-guides}` should never be used anymore. You need to use `xref:security-openid-connect-dev-services.adoc` (or whatever the name of the guide is) and let the downstream magic rewrite the link.

Could you make sure we don't have these things anymore in the guides?

Thanks!

**Comment by gsmet** [comment]
@mcollovati thanks for the detailed report. I moved the issue to the main Quarkus repository where the fixes will happen.

**Comment by sheilamjones** [comment]
Hi @mcollovati thanks for raising this issue and @gsmet for your feedback.
Shall review and address these fixes today.
Kind regards,
Sheila

**Comment by sberyozkin** [comment]
Thanks @rolfedh, @sheilamjones, for checking I already fixed that (with thanks to @jedla97). I've updated  the bug name a bit to reflect that, FYI, @gsmet is planning the final 3.6 maintenance release on Wed, so please cherry-pick the required fixes by the end of Tuesday

**Comment by sheilamjones** [comment]
Hi @sberyozkin,
I have implemented a fix to version 3.6 to correct these broken links on that version. The fixes are cherry-picked from PR https://github.com/quarkusio/quarkus/pull/37522. I would appreciate your review and sign-off of the changes. Many thanks @rolfedh for your investigation and help with this.
Regards,
Sheila

**Comment by sberyozkin** [comment]
Fixed by #38220
