### ISSUE TITLE
Keycloak admin client combined with devservices

### ISSUE THREAD

**Issue by appiepollo14** [quarkusio/quarkus#38176]
### Description

Keycloak authorization has devservices, which will start a container running keycloak and configure the Application properties needed to connect to the instance. 

The keyclient admin client extension don't behave that way. Especially combined with keycloak authorization, that's a hassle as the admin client endpoint will change everytime quarkus is restarted. 

### Implementation ideas

Implement the logic from the devservices for keycloak authorization in the keycloak admin client as well.

**Comment by sberyozkin** [comment]
@appiepollo14 I think the comment at #35390 provides a solution, I missed that comment, so I'll doc it, thanks for reminding
