### ISSUE TITLE
"All build items" guide in Quarkus documentation doesn't render javadoc correctly

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#38187]
### Describe the bug

See https://quarkus.io/guides/all-builditems

### Expected behavior

Javadoc should be rendered correctly as HTML. In particular, Javadoc tags such as `@link` should be rendered at the very least as plain text, ideally as HTML links.

### Actual behavior

`@link` tags are apparently removed during processing. See `CombinedIndexBuildItem`; the javadoc is as follows:

```
 * An index of application classes which is built from archives and dependencies that contain a certain marker file.
 * These files include but are not limited to - beans.xml, jandex.idx and config properties.
 * Additional marker files can be declared via {@link AdditionalApplicationArchiveMarkerBuildItem}.
 * Alternatively, you can index a dependency through {@link IndexDependencyBuildItem}.
```

and is rendered as follows (see how `AdditionalApplicationArchiveMarkerBuildItem` is omitted):

![Screenshot from 2024-01-15 09-36-00](https://github.com/quarkusio/quarkus/assets/412878/56d8b692-0830-4469-b80b-a0107868badc)

Same goes for `@see` tags in `NativeImageAllowIncompleteClasspathAggregateBuildItem`, though I doubt those are correct (can `@see` be used between `{`/`}` in javadoc?):

```
 * Do not use directly: use {@see io.quarkus.deployment.builditem.nativeimage.NativeImageAllowIncompleteClasspathBuildItem}
 * instead.
```

![image](https://github.com/quarkusio/quarkus/assets/412878/fdbdd646-0a4d-4272-95df-72d4886e831c)

### How to Reproduce?

See https://quarkus.io/guides/all-builditems.

**Comment by poorvaja-sathasivam** [comment]
Hello! I'm interested in working on this issue. Can it be assigned to me?

**Comment by Minecon724** [comment]
looks like this has been fixed

**Comment by gsmet** [comment]
Ah, thanks for reviving this! Closing.
