### ISSUE TITLE
Cannot  build master, Docs, asciidoctor:, datasource-guide.adoc: line 228: include file not found

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#3818]
Build fails on Documentation build: 
```
./mvnw install

[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (output-html) @ quarkus-documentation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] Rendered /home/karm/workspaceRH/quarkus/docs/src/main/asciidoc/getting-started-knative-guide.adoc
[INFO] asciidoctor: ERROR: datasource-guide.adoc: line 228: include file not found: /home/karm/workspaceRH/quarkus/docs/src/main/asciidoc/generated/quarkus-agroal.adoc
[INFO] Rendered /home/karm/workspaceRH/quarkus/docs/src/main/asciidoc/datasource-guide.adoc
[ERROR] asciidoctor: ERROR: datasource-guide.adoc: line 228: include file not found: /home/karm/workspaceRH/quarkus/docs/src/main/asciidoc/generated/quarkus-agroal.adoc
[INFO] ------------------------------------------------------------------------

```
**Environment:**
Linux, Java 11, Quarkus git HEAD: 7404e8e

**Comment by gsmet** [comment]
@machi1990 is this expected?

**Comment by machi1990** [comment]
@gsmet Yes, generated docs were  git-ignored: I am not sure if it was good idea from my end. 


@Karm A fresh (re-)build of the whole project with `mvn clean install -DskipTests -DskipiTs` is required, at least run it once to generate the docs.

**Comment by gsmet** [comment]
> Yes, generated docs were git-ignored: I am not sure if it was good idea from my end.

That's a good call, we don't want to commit generated docs... but that might become a pain when we just want to quickly generate the documentation.

**Comment by machi1990** [comment]
> @Karm A fresh (re-)build of the whole project with `mvn clean install -DskipTests -DskipiTs` is required, at least run it once to generate the docs.

Okay, maybe document this behaviour somewhere in the contributing guide?

**Comment by gsmet** [comment]
@machi1990 looks like we could use `opts=optional` as in:
```
include adoc.content[opts=optional]
```

That's probably the best course of action for now.

**Comment by machi1990** [comment]
Sure, let's do it.
