### ISSUE TITLE
ExceptionMapper doesn't work with Response entity of POJO or record in native mode

### ISSUE THREAD

**Issue by ivangreene** [quarkusio/quarkus#38203]
### Describe the bug

When running a native executable, and using an ExceptionMapper whose entity is an instance of a POJO or a record, the request doesn't match dev/jar mode

### Expected behavior

The ExceptionMapper should work the same in both dev/jar mode and native mode: it should pass the entity as the body

### Actual behavior

The response is converted to a 500 with a body like `{"details":"Error id 4a9257a9-de38-4222-881c-5e56a7b87ce3-1","stack":""}`

### How to Reproduce?

Reproducer: https://github.com/ivangreene/quarkus-quickstarts/tree/ig/exception-mapper-native/rest-json-quickstart
(branch `ig/exception-mapper-native`, subdir `rest-json-quickstart`)
Commit: https://github.com/ivangreene/quarkus-quickstarts/commit/d6f33d9fd14339c6d8376f0853610bc707677092

Steps to reproduce:
1. Run in dev mode: `quarkus dev`
2. Curl: `curl -v http://localhost:8080/fruits`
3. Output:
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /fruits HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Type: application/json;charset=UTF-8
< content-length: 34
<
* Connection #0 to host localhost left intact
{"message":"HTTP 400 Bad Request"}
```
4. Native build: `quarkus build --native --no-tests`
5. Run the executable: `./target/rest-json-quickstart-1.0.0-SNAPSHOT-runner`
6. Curl: `curl -v http://localhost:8080/fruits`
7. Output:
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /fruits HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< content-type: application/json; charset=utf-8
< content-length: 72
<
* Connection #0 to host localhost left intact
{"details":"Error id 4a9257a9-de38-4222-881c-5e56a7b87ce3-1","stack":""}
```

### Output of `uname -a` or `ver`

Darwin Ivans-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Homebrew (build 17.0.6+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.6+0, mixed mode, sharing)

### Mandrel or GraalVM version (if different from Java)

graalvm-ce-java17

### Quarkus version or git rev

3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/ivangreene/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.6, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.5.2", arch: "aarch64", family: "mac"

**Comment by ivangreene** [comment]
A workaround: use `Map<String, String>` as the entity. You can see this commented out in my reproducer

**Comment by geoand** [comment]
There is no way Quarkus can deduce the information necessary to make this work automatically in native-mode.

The easiest thing to do is to annotate `ErrorResponse` with `@RegisterForReflection`

**Comment by ivangreene** [comment]
@geoand thanks. This worked. Is there any way I can have this error surfaced more readily in the future when something like this happens? What does the Error id correspond to and is there a way to look it up?
