### ISSUE TITLE
With RESTEasy Reactive @QueryParam、@PathParam、@HeaderParam makes POST with JSON not work

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#38210]
### Describe the bug

We use 2.13.4.Final now. @QueryParam、@PathParam、@HeaderParam and Json work.

We can't get data  of the class from json when we upgrade to 2.16.12.Final.

It is not compatible when the version greater than or equal to 2.14.x

<img width="1133" alt="image" src="https://github.com/quarkusio/quarkus/assets/25682169/fc881d8c-3f26-489a-ac14-1d7c7ca075b0">

### Expected behavior

we can get data of the class from json with @QueryParam、@PathParam、@HeaderParam 

### Actual behavior

<img width="321" alt="image" src="https://github.com/quarkusio/quarkus/assets/25682169/d914763b-e746-4f53-82de-d87cbdd725ca">

### Quarkus version or git rev

greater than or equal to 2.14.x

**Comment by geoand** [comment]
`@QueryParam`、`@PathParam`、`@HeaderParam` are not automatically deserialized from JSON.

The `@Consumes` annotation is used for the body of the HTTP request, nothing more.

**Comment by naah69** [comment]
> `@QueryParam`、`@PathParam`、`@HeaderParam` are not automatically deserialized from JSON.
> 
> The `@Consumes` annotation is used for the body of the HTTP request, nothing more.

@geoand But it  automatically deserialized from JSON now ！！！！

**Comment by geoand** [comment]
Add a sample application please that exhibits the behavior you describe and I'll take a quick look.

**Comment by naah69** [comment]
https://github.com/quarkusio/quarkus/issues/32429

how to disable @BeanParam is implicit?

<img width="1009" alt="image" src="https://github.com/quarkusio/quarkus/assets/25682169/e5deb8e5-acbb-46a3-b5ee-b98f3f2f382c">

**Comment by naah69** [comment]
> Add a sample application please that exhibits the behavior you describe and I'll take a quick look.请添加一个示例应用程序，以展示您描述的行为，我将快速浏览一下。

@geoand 
[code.zip](https://github.com/quarkusio/quarkus/files/13946635/code.zip)

if @QueryParam in TaskDTO, all field in TaskDTO is null
it work if remove @QueryParam

request body:
```json
{
    "batchId": "695609413641441280",
    "jobId": "695610094889205760",
    "taskId": "695610094885273600",
    "projectId": "674023643430531072",
    "workflowId": "695609739088244736",
    "workflowTransferId": "695610097493221376",
    "type": "TOOL_TIME"
}
```

**Comment by geoand** [comment]
I think you are mixing both handling of the HTTP body and query params in the same POJO. That is simply not supported.
I propose removing all the `@QueryParam` fields from `TaskDTO` and making them either as method params of `addTimeConsuming`, or introduce a new POJO which will act as a `@BeanParam`

**Comment by naah69** [comment]
> I think you are mixing both handling of the HTTP body and query params in the same POJO. That is simply not supported. I propose removing all the `@QueryParam` fields from `TaskDTO` and making them either as method params of `addTimeConsuming`, or introduce a new POJO which will act as a `@BeanParam`

@geoand 

That's not the point.

The key point is that it will implicitly add @BeanParam after 2.14.x.

This results in json having a lower deserialization priority than the deserialization of these annotations

Whether to provide a switch to turn off the implicit addition of @BeanParam in order to be compatible with the original logic

**Comment by naah69** [comment]
@geoand 
We should explicitly add @BeanParam to the method's parameters to reduce misunderstandings and incompatibilities

**Comment by geoand** [comment]
> That's not the point.

It is, because what you are trying to do is simply not supported and if it worked in the past it was by accident.

**Comment by naah69** [comment]
> > That's not the point.
> 
> It is, because what you are trying to do is simply not supported and if it worked in the past it was by accident.

@geoand 

Why force the user to never use annotations in the class？

Use @BeanParam as a switch to determine whether to parse, which is more friendly

**Comment by geoand** [comment]
As I said, we never explicitly supported mixing paramers coming from HTTP body deserialization with other HTTP parameters (like query, path, etc). 
The fact that it might have worked in the past was an accident and the remedy is very simple (as I mentioned earlier).

**Comment by naah69** [comment]
> As I said, we never explicitly supported mixing paramers coming from HTTP body deserialization with other HTTP parameters (like query, path, etc). The fact that it might have worked in the past was an accident and the remedy is very simple (as I mentioned earlier).

Yes, we understand,

We don't need these two features to work together, we just want to disable @BeanParam for now.

When we don't explicitly specify @BeanParam, it doesn't need to take effect! But now it's automatic.

![image](https://github.com/quarkusio/quarkus/assets/25682169/cd289a70-59d1-40b6-a31a-ff8dc39fbcc3)

**Comment by geoand** [comment]
> We don't need these two features to work together, we just want to disable @BeanParam for now.\

What for? So you can deserialize the rest of the fields using the HTTP request body? 
If that's the case, it's not supported and you should really remove the fields as there is no good reason to be mixing different things into the same POJO.

**Comment by naah69** [comment]
@geoand 

For reasons that were not explicitly forbidden before, we do not know if this use will lead to disaster in the future.

We sometimes use a common POJO to accept arguments for compatibility with get and post methods, but we don't use @BeanParam with JSON.

When we use @BeanParam, we usually use the GET method, in other cases, we just use the POJO to parse the JSON

The implicit addition of @BeanParam now prevents us from using POJOs to parse JSON in scenarios other than the GET method

We will need to check many many code,if the feature can't disable by config.

It is probelly that we won't upgrade version ,because the cost is too large.

**Comment by geoand** [comment]
> It is probelly that we won't upgrade version ,because the cost is too large.

Well, in this case even if we did add what want (which in any case we likely won't), I can assure you we will **not** backport it to 2.13 as this only received critical bug fixes.

**Comment by naah69** [comment]
@geoand 
OK，whether the probably add the feature that disable implicit add @BeanParam

**Comment by naah69** [comment]
@FroMage can u help me？

**Comment by naah69** [comment]
@geoand @FroMage 

If add @BeanParam implicitly is necessary.

Why we need @BeanParam？

Why not remove annotation  @BeanParam in jaxrs?

**Comment by FroMage** [comment]
Sorry, you should split your inputs between `@*Param` (and related) and body entity parameters, they have to be separate.

I don't think we will re-enable mixing the two together in the future, it was really by accident that it ever worked, and not by design.

**Comment by naah69** [comment]
@FroMage 

I still think the key point of problem is that @BeanParam shouldn't be added implicitly.

@BeanParam should be controlled by people, not automatically

**Comment by FroMage** [comment]
Well, we _could_ introduce a `@Body` annotation to force your class to be deserialised via JSON, but that will mean that all your `@*Param` are `null` and not working. I am not sure that would be better.
