### ISSUE TITLE
Nested @CacheResult doesn't work with redis

### ISSUE THREAD

**Issue by sebastian639559** [quarkusio/quarkus#38219]
### Describe the bug

Calling foo results in a time-out from the endpoint calling foo:

```
    @CacheResult(cacheName = "my-cache-1", keyGenerator = MyCacheKeyGenerator.class)
    public String foo(@CacheKey String signId) {
        log.info("1 caching");
        faa("asdf");
        log.info("3 caching");
        return "something-here";
    }


    @CacheResult(cacheName = "my-cache-2", keyGenerator = MyCacheKeyGenerator.class)
    public String faa(@CacheKey String signId) {
        log.info("2 caching");
        return "something-here";
    }

```

This is possibly because quarkus is not able to keep two connections the a redis instance open at once? 

### Expected behavior

The code should work, not crash/timeout 

### Actual behavior

The endpoint calling foo() timesout. 

### How to Reproduce?

quarkus version 3.3.3
Java version 17

**Comment by cescoffier** [comment]
I would need a reproducer.

However, if both keys are not hosted on the same node, it could be a problem.

**Comment by cescoffier** [comment]
Also, I need to know if you are using optimistic locking.

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by dirkbolte** [comment]
In case someone stumbles upon this: https://github.com/quarkusio/quarkus/pull/42540 fixes a similar (same?) issue for me (Quarkus 3.13.3)
