### ISSUE TITLE
Add the mapping to a Map<String, ConfigObject> in the documentation.

### ISSUE THREAD

**Issue by sekaijin** [quarkusio/quarkus#38226]
### Description

Add the mapping to a Map<String, ConfigObject> in the documentation.
Getting a Map<String, ConfigObject> in the documentation. is not clearly defined and is a source of errors and questions.

`@ConfigMapping(prefix = "server")
public interface Servers {

    @WithParentName
    Map<String, Server> allServers();
}`

### Implementation ideas

https://github.com/quarkusio/quarkus/blob/main/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceRuntimeConfig.java

in line 419 add

Mapping can also be done as a `Map` of objects.

[source,java]
----
@ConfigMapping(prefix = "server")
public interface Servers {

    @WithParentName
    Map<String, Server> allServers();
}

@ConfigGroup
public interface Server {

    String host();

    int port();

    String login();

    String error();

    String landing(); 
}
----

.application.properties
[source,properties]
----
server."my-server".host=localhost
server."my-server".port=8080
server."my-server".login=login.html
server."my-server".error=error.html
server."my-server".landing=index.html
----

In this case the `allServers()` `Map` will
contain one `Server` element with the keys `my-server`.
[config-mappings.adoc.zip](https://github.com/quarkusio/quarkus/files/13952326/config-mappings.adoc.zip)

**Comment by tharendra** [comment]
Hi, I would like to take a look at this as my first contribution. 
I will do some research first and update soon if that's all right.

**Comment by arvind-vignesh** [comment]
Hey I would like to take this issue up and contribute. Can someone mark me as the assignee for this?

**Comment by tarishij17** [comment]
I see the PR is merged, is this issue still open?

**Comment by radcortez** [comment]
Fixed by #39162 38226
