### ISSUE TITLE
Adding a decorator causes bytecode error

### ISSUE THREAD

**Issue by mkwapisz** [quarkusio/quarkus#38236]
### Describe the bug

I tried to add a decorator for a JPA repository component. Simple project to reproduce the problem is attached 

I have created alternative implementation of GameRepository that is not based on JPA and without @Transactional. It works perfectly.

### Expected behavior

There should be no bytecode error and the decorator method should be executed

### Actual behavior

When the JpaGameRepositoryTest is run the following exception is thrown:

pl.kurs.JpaGameRepositoryTest#add(JpaGameRepositoryTest.java:19) JpaGameRepositoryTest#add() Method expects a return value
Exception Details:
  Location:
    pl/kurs/JpaGameRepository_Subclass$$function$$1.apply(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @26: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2cc0 000c b900 1001 0003 324e 2ab4 0012
    0000010: c000 142d c000 16b6 001a b1

### How to Reproduce?

Run tests for attached project
[decorator.zip](https://github.com/quarkusio/quarkus/files/13960004/decorator.zip)

### Output of `java -version`

openjdk 21 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 21, vendor: Oracle Corporation, runtime: D:\DevTools\Java\jdk-21 Default locale: en_US, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkwapisz** [comment]
The problem is more general, you can not attach any interceptor and decorator to the same component

**Comment by flazarus1A** [comment]
Same issue witnessed with decorators over a Kafka Streams processor: most of our decorated processors start fine, but our Kafka to REST processor (in which we inject a `@RestClient`) fails with this error.

Quarkus 3.2.9.Final on temurin17
