### ISSUE TITLE
OIDC authentication for discovery endpoints

### ISSUE THREAD

**Issue by 01epa** [quarkusio/quarkus#38246]
### Description

I want to make oidc authentication in Quarkus service where auth service is Kubernetes. 

So, i want to send a service account token to my quarkus service, validate it using public key (retrieved from OIDC endpoints), extract roles from token and perform authorization.

But when i tried to access well-know configuration endpoint I got 403 UnAuthorized. To access it I have to provide a service account token of my own service.

Kubernetes has a support of [OIDC endpoints](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) but they are closed with [authentication](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#without-using-a-proxy)

>The recommended way to authenticate to the API server is with a [service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) credential.

Can you provide some way to set authorization header?

Probably it is better to add custom header interceptors to a client or some client customizer.

Here is a place where client created via `new` and later it is passed `OidcCommonUtils.discoverMetadata()` method
https://github.com/quarkusio/quarkus/blob/e5b9477aa380a603d19ae71e6e9499abe605654f/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L474

**Comment by sberyozkin** [comment]
@01epa This is now can be supported easily with the custom `OidcRequestFilter`, https://quarkus.io/guides/security-openid-connect-client-reference#oidc-client-filters, works for `quarkus-oidc` as well.

Specifically, this shows how to intercept discovery requests only:

https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-wiremock/src/main/java/io/quarkus/it/keycloak/OidcDiscoveryRequestCustomizer.java

Can you try it and close the issue once you confirm it works ?

**Comment by sberyozkin** [comment]
@01epa 3.7.0.CR1 which will have this annotation feature is about  to be released, but you can test even in 3.6.x, in 3.6.x one needs to check manually if the current request targets the discovery endpoint

**Comment by 01epa** [comment]
I checked what you suggested. This is exactly what I wanted. Thanks. ALso i saw your MR with specifing endpoints to apply filter. Will wait next Qurkus release as well.

**Comment by sberyozkin** [comment]
@01epa FYI, 3.7.0.CR1 has just been released by @gsmet
