### ISSUE TITLE
Qute: Parse error in template if there is dot in tag name

### ISSUE THREAD

**Issue by maria212** [quarkusio/quarkus#38243]
### Describe the bug

We want to name the tag "chip.tag"
portal-application/src/main/resources/templates/tags/chip.tag.html

`
{#chip.tag}
                    {myContent}
                {/chip.tag}
`

According to the docs it must work because of requirements only to start name https://quarkus.io/guides/qute-reference#identifiers

### Expected behavior

Should be rendered correct

### Actual behavior

Got error "no section helper found"
![image](https://github.com/quarkusio/quarkus/assets/40321004/5d2a253b-6206-47c2-8f6d-5d6347a35222)

### Quarkus version or git rev

3.2.8.Final

### Additional information

For We want to name the tag "chip"
portal-application/src/main/resources/templates/tags/chip.html
all work correct

**Comment by mkouba** [comment]
> We want to name the tag "chip.tag"

This is not supported and we should throw an exception if a similiar tag name is used. 

A tag name should have similar restrictions to namespaces, i.e. consist of alphanumeric characters and underscores. I'll send a PR to report the error during the build.

**Comment by maria212** [comment]
> > We want to name the tag "chip.tag"
> 
> This is not supported and we should throw an exception if a similiar tag name is used.
> 
> A tag name should have similar restrictions to namespaces, i.e. consist of alphanumeric characters and underscores. I'll send a PR to report the error during the build.

Would be good to include this answer in docs. Thanks!

**Comment by mkouba** [comment]
> > > We want to name the tag "chip.tag"
> > 
> > 
> > This is not supported and we should throw an exception if a similiar tag name is used.
> > A tag name should have similar restrictions to namespaces, i.e. consist of alphanumeric characters and underscores. I'll send a PR to report the error during the build.
> 
> Would be good to include this answer in docs. Thanks!

Definitely +1

**Comment by mkouba** [comment]
Just for the record - you can have a tag like `portal-application/src/main/resources/templates/tags/chip.tag.html` but the suffix is always stripped from the tag name, i.e. the tag can be used with `{#chip}`. Moreover, you would need to add `tag.html` to the set of supported suffixes with the [quarkus.qute.suffixes](https://quarkus.io/guides/qute-reference#quarkus-qute_quarkus.qute.suffixes) config property.
