### ISSUE TITLE
Incorrect web links Quarkus Hibernate Reactive Rest Data Panache

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#38247]
### Describe the bug

Quarkus Hibernate Reactive Rest Data Panache is providing the incorrect web link self relation urls. 

The following snippets taken from the example entities of the reproducer project [quarkus-issue-38247](https://github.com/bpasson/quarkus-issue-38247) produce incorrect rel=self web links.
```
@Entity
@Table(name="double_ids")
public class TestRecordOne extends PanacheEntityBase {

    // marked tid as the pk for this object and not the id field to show
    // the LinkProcessor uses the id field to render self link and not the
    // tid value.
    @Id
    @Column(name="tid", columnDefinition = "BIGINT", nullable = false)
    private Long tid;
    @Column(name="id", columnDefinition = "BIGINT", nullable = false)
    private Long id;

    @Column(name="name", columnDefinition = "TEXT", nullable = false)
    private String name;    
    ...
```

```
@Entity
@Table(name="annotation_only")
public class TestRecordTwo extends PanacheEntityBase {

    // field not named 'id' to force LinkProcessor to use the @Id annotation
    // which is then not used for the id path param, but stored as tid path param
    // and no value is rendered in the self link.
    @Id
    @Column(name="tid", columnDefinition = "BIGINT", nullable = false)
    private Long tid;
    @Column(name="name", columnDefinition = "TEXT", nullable = false)
    private String name;
   
    ....
}
```

### Expected behavior

When running the ReproducerTest cases the following is expected for each test case:

* shouldGetCorrectSelfLinkForRecordOne is expected to render the link http://localhost:8081/api/one/1
* shouldGetCorrectSelfLinkForRecordTwo is expected to render the link http://localhost:8081/api/two/2
 

### Actual behavior

When running the ReproducerTest cases the following is actually happening for each test case:

* shouldGetCorrectSelfLinkForRecordOne is rendering the link http://localhost:8081/api/one/10
* shouldGetCorrectSelfLinkForRecordTwo is rendering the link http://localhost:8081/api/two/%7Bid%7D

### How to Reproduce?

To reproduce this clone https://github.com/bpasson/quarkus-issue-38247 and run `./mvnw clean verify` and see the failing testcases.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.6

**Comment by bpasson** [comment]
@DavideD added it just now, I had to create the issue first to get the number.

**Comment by bpasson** [comment]
@DavideD I will also open a PR for to fix the issue. Just creating the issue here to have a PR reference it.

**Comment by DavideD** [comment]
Ok, thanks.
I guess I checked this too quickly :)
