### ISSUE TITLE
Checking for `it` exists in a Qute User tag is failing

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#38252]
### Describe the bug

foo.html
```html
<div>
 Hello {#if it}{it}{/if}
</div>
```

### Expected behavior

It should work with or without param `{#foo 'bar'/}` or `{#foo /}`

### Actual behavior

There is an error when `{#foo /}`

### Quarkus version or git rev

3.6.5

**Comment by mkouba** [comment]
FTR you could also use a parameter declaration with a default value:
```
{@String it=''}
<div>
 Hello {#if it}{it}{/if}
</div>
```

NOTE: Unfortunately, it seems that we don't support `{@String it=null}` at the moment.
