### ISSUE TITLE
Using Qute `asHtmlAttributes` is escaping the quotes in the output

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#38251]
### Describe the bug

Using Qute `asHtmlAttributes` is escaping the quotes in the output:
```html
<form action="{it}" method="{method ?: 'POST'}" {_args.skip('method', 'it').asHtmlAttributes}>
 {#authenticityToken/}
 {nested-content}
</form>
```

The workaround is to use: `asHtmlAttributes.safe`

### Expected behavior

```html
<form action="/HtmxApp/save/6" method="POST" hx-put="/HtmxApp/save/6" hx-swap="&quot;outerHTML&quot;" hx-target="this">
```

**I believe the value (inside the quote) should be escaped**

### Actual behavior

```html
<form action="/HtmxApp/save/6" method="POST" hx-put="&quot;/HtmxApp/save/6&quot;" hx-swap="&quot;outerHTML&quot;" hx-target="&quot;this&quot;"
">
```

### Quarkus version or git rev

3.6.5

**Comment by mkouba** [comment]
The is straightforward, except that we must change the return type of the `UserTagSectionHelper.Arguments.asHtmlAttributes()` method from `String` to `RawString`. As a consequence, a user will need to use `{_args.asHtmlAttributes.value}` to access the `String` methods... which I believe is not a big deal.

**Comment by ia3andy** [comment]
@mkouba you need to update the doc

**Comment by mkouba** [comment]
Oh yes, we could mention that the values are always escaped but other than that the docs is IMO ok.

**Comment by ia3andy** [comment]
> Oh yes, we could mention that the values are always escaped but other than that the docs is IMO ok.

@mkouba I mean for the `{_args.asHtmlAttributes.value}`

**Comment by mkouba** [comment]
> > Oh yes, we could mention that the values are always escaped but other than that the docs is IMO ok.
> 
> @mkouba I mean for the `{_args.asHtmlAttributes.value}`. See https://quarkus.io/guides/qute-reference#arguments

Well, I think that 99% of users will never need `{_args.asHtmlAttributes.value}` but it wouldn't hurt to be more specific.

**Comment by ia3andy** [comment]
@mkouba so _args.asHtmlAttributes actually works as it is? I just misunderstood what you mean before by "to use it as a String", if that's the case, you can ignore my comment :)

**Comment by mkouba** [comment]
> @mkouba so _args.asHtmlAttributes actually works as it is? I just misunderstood what you mean before by "to use it as a String", if that's the case, you can ignore my comment :)

Yes, it does. But you get a `RawString` instead. So for example `{_args.asHtmlAttributes.toUpperCase}` would not work but it used to work before...
