### ISSUE TITLE
Add details about relocations into README and/or CONTRIBUTING

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#38274]
### Description

I don't see in Quarkus [README](https://github.com/quarkusio/quarkus/blob/main/README.md) or [CONTRIBUTING](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md) documents any suggestion to use relocations profile.

This can be handy for people working with Quarkus main. Especially after https://github.com/quarkusio/quarkus/pull/38190 change and with the upcoming https://github.com/quarkusio/quarkus/blob/main/adr/0002-reactive-rename.adoc changes.

CI is building Quarkus main with relocations:
 - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/.github/workflows/ci.yml#L25
 - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/.github/workflows/daily.yaml#L27

CC @gsmet @geoand

**Comment by geoand** [comment]
I am not exactly sure what you would like to have documented around this. Who do you envision will be helped by such documentation and how?

**Comment by rsvoboda** [comment]
`Building with relocations` section in https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#workflow-tips

**Comment by maxandersen** [comment]
same question as @geoand - not following what the usecase is? isn't that profile not only to use when publishing - and not needed elsewhere?

**Comment by rsvoboda** [comment]
I created https://github.com/quarkusio/quarkus/pull/38341 to show my idea.

This is the main trigger: https://github.com/quarkus-qe/quarkus-test-suite/pull/1617#issuecomment-1896146196
We are working on test development in main branch of qe test-suite and we backport bulks to 3.2 / 2.13 branch.
Thus we want to keep main branch compatible with 3.2 as much as possible (at least till 3.8 is out).

**Comment by michalvavrik** [comment]
Makes sense, thanks for the context.

**Comment by rsvoboda** [comment]
@maxandersen ok, so it's intentionally hidden and this should be closed (together with my PR)?
