### ISSUE TITLE
TestAuthController can only be used in tests

### ISSUE THREAD

**Issue by florian-gustin** [quarkusio/quarkus#38303]
### Describe the bug

When starting the application and making a simple Try out with swagger for any endpoint :

I receive an error : 

java.lang.RuntimeException: TestAuthController can only be used in tests redirecting to the quarkus test security pkg

    @PostConstruct
    public void check() {
        if (LaunchMode.current() != LaunchMode.TEST) {
            throw new RuntimeException("TestAuthController can only be used in tests");
        }
    }
    
    
    I just want to be able to use my endpoints but this piece of code is blocking me.
    
    I checked on the web about and there is nothing at all.

Can someone help please ?
    
    

### Output of `java -version`

17

### Quarkus version or git rev

3.6.4

### Additional information

pom.xml : 

...

    
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-jwt</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-jwt-build</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.microprofile.jwt</groupId>
      <artifactId>microprofile-jwt-auth-api</artifactId>
    </dependency>

    
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
    </dependency>

    
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>mongodb</artifactId>
      <version>1.18.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>4.6.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-security</artifactId>
    </dependency>
...

Method inside the controller : 

    @Authenticated
    @Override
    public Uni<Response> sendWelcomeEmail(String email, String username, String language) {
        try{
            return Uni.createFrom().completionStage(emailingService.sendWelcomeEmail(email, username,language)).onItem().transform(v -> Response.noContent().build());
        }catch (Exception e){
            return Uni.createFrom().item(ControllerExceptionHandler.toHttpResponse(e));
        }
    }
    
 Endpoint test working: 
 
     @TestSecurity(authorizationEnabled = false)
    @Test
    void testSendWelcomeEmailSuccess() {
        Mockito.reset(emailingService);

        Mockito.when(emailingService.sendWelcomeEmail(Mockito.anyString(), Mockito.anyString(), Mockito.anyString())).thenReturn(CompletableFuture.completedFuture(null));

        QuarkusMock.installMockForType(emailingService, EmailingService.class);

        given()
                .queryParam("email", "florian.gustin.barriera@gmail.com")
                .queryParam("username", "florian")
                .queryParam("language", "fr")
                .when()
                .post("http://localhost:10021/api/v1/emailing/welcome")
                .then()
                .statusCode(204);
    }

**Comment by sberyozkin** [comment]
@florian-gustin No problems, you should have a `<scope>test</scope>` added

```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-test-security</artifactId>
</dependency>
```

Let me close the issue as not a bug, thanks

**Comment by sberyozkin** [comment]
@florian-gustin Please re-open if you'll continue having difficulties with making it work

**Comment by florian-gustin** [comment]
@sberyozkin 

Thank you it worked
