### ISSUE TITLE
spring-data-jpa repository save exception with multiple persistence units

### ISSUE THREAD

**Issue by fladdimir** [quarkusio/quarkus#38319]
### Describe the bug

When using multiple, non-default persistence units and saving a detached entity via the quarkus-spring-data-repository `save` method, an IllegalStateException is thrown.

### Expected behavior

The `save` should successfully persist the current state of the detached entity using the correct (non-default) persistence-unit.

### Actual behavior

The following exception is thrown:

```text
java.lang.IllegalStateException: The default datasource has not been properly configured.
See https://quarkus.io/guides/datasource#jdbc-datasource for information on how to do that.
 at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.getEntityManager(AbstractJpaOperations.java:64)
 at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.getEntityManager(AbstractJpaOperations.java:89)
 at com.example.demo.p1.DemoRepository1_c8b4c34d8e0db77ef33ab6b006a416fba4b02b90Impl.save(Unknown Source)
[...]
```

### How to Reproduce?

https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/src/test/java/com/example/demo/QuarkusMultiplePersistenceUnitsSpringDataRepositoryTest.java#L22

### Output of `uname -a` or `ver`

x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by fladdimir** [comment]
It seems that the generated repository implementation does not retrieve the correct EntityManager before merging (decompiled generated repository implementation):

```java
   @Transactional
   public DemoEntity1 save(DemoEntity1 var1) {
      if (var1.getId() != null) {
         return (DemoEntity1)((AbstractJpaOperations)JpaOperations.INSTANCE).getEntityManager().merge(var1); // <- retrieves default EntityManager
      } else {
         ((AbstractJpaOperations)JpaOperations.INSTANCE).persist(var1);
         return var1;
      }
   }
```

(<https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/generated/DemoRepository1Impl.java.txt#L36>)

This could be fixed by retrieving the correct EntityManager depending on the entityClass (as it is done at most other places):

```java
   @Transactional
   public DemoEntity1 save(DemoEntity1 var1) {
      if (var1.getId() != null) {
         Class var2 = this.entityClass; // <- used to retrieve the correct EntityManager
         return (DemoEntity1)((AbstractJpaOperations)JpaOperations.INSTANCE).getEntityManager(var2).merge(var1);
      } else {
         ((AbstractJpaOperations)JpaOperations.INSTANCE).persist(var1);
         return var1;
      }
   }
```

(<https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/generated_fixed/DemoRepository1Impl.java.txt#L36>)

(Changing this part of the byte-code generation could be done by making the `entityClassFieldDescriptor` available <https://github.com/quarkusio/quarkus/compare/main...fladdimir:quarkus:main#diff-c84b59922f133b2d09025afecd5392cc77f9fda79df760148ca619d311587468R240-R246>)

---

Apparently, there are a few more places where the default EntityManager is used without taking the entityClass into account:
[`getOne`](https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/src/test/java/com/example/demo/QuarkusMultiplePersistenceUnitsSpringDataRepositoryTest.java#L37), [`deleteAll`](https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/src/test/java/com/example/demo/QuarkusMultiplePersistenceUnitsSpringDataRepositoryTest.java#L31), and [paged queries](https://github.com/fladdimir/quarkus-test-spring-data-multiple-pus/blob/master/src/test/java/com/example/demo/QuarkusMultiplePersistenceUnitsSpringDataRepositoryTest.java#L52) (all throwing a similar exception).

In all cases the entityClass is already available, so that could be simple to fix (e.g. here <https://github.com/quarkusio/quarkus/compare/main...fladdimir:quarkus:main#diff-25c83264c299e026d3b9b0236d4e392a250417367492a79c2dd0ceed0d7cc999R45>).

Is the analysis correct? And does it make sense to submit a PR?

**Comment by geoand** [comment]
@fladdimir the analysis does seem correct! Feel free to open a PR with your suggested changes.
