### ISSUE TITLE
SSE RESTEasy Reactive if an error occurs, cannot retrieve the body

### ISSUE THREAD

**Issue by xtof974** [quarkusio/quarkus#38325]
### Describe the bug

My Quarkus application is a client that calls a Server-Sent Event (SSE) endpoint. I followed the recommendations of the documentation specific to SSE. It works as long as there is no error. 
If an error occured, RESTEasy Reactive throws a WebApplicationException. I have register an exceptionMapper and a ClientExceptionMapper to catch the Response object. It works but I have to read the body of the error response 400 to do specific stuffs
Unfortunately, the entity or streamEntity return allways null.

How manage this kind of usecase ? 

### Expected behavior

a way to retrieve the body error

### Quarkus version or git rev

3.6.6

**Comment by geoand** [comment]
What version of Quarkus are you using?

**Comment by xtof974** [comment]
@geoand I'm using the version 3.6.6

**Comment by geoand** [comment]
Thanks.

Can you share what approxitely the data looks like and what class you trying to deserialize it to?

I am just trying to get a more complete understanding of the problem you are facing.

**Comment by xtof974** [comment]
I have a service A that calls a service B that calls the SSE endpoint via the interface C.

**service A** :

`Multi<ChatMessagesSseResponse> chatMessageResponse = this.proxyChatMessageResource.callChat(chatMessageRequest)
                .onItem()
                .transform(res -> {
                    ChatMessagesSseResponse chatMessagesSseResponse = new ChatMessagesSseResponse();
                    try {
                        if (!res.contains("[DONE]")) {
                            ChatMessagesAzureSseResponse chatMessagesResponse = objectMapper.readValue(res, ChatMessagesAzureSseResponse.class);
                            if (chatMessagesResponse.choices().get(0).delta().content() != null && chatMessagesResponse.id() != null) {
                                chatMessagesSseResponse = new ChatMessagesSseResponse(chatMessagesResponse);
                            }
                        }
                    } catch (JsonProcessingException e) {
                        throw new RuntimeException(e);
                    }
                    return chatMessagesSseResponse;
                })
                .onFailure().invoke(t ->
                        logger.info(String.format("Oh no! We received a failure: %s",
                                t.getMessage())));
        return chatMessageResponse
                .select().where(message -> message.getId() != null);
    }`

**service B** :

`@RestClient
    AzureOpenAiApi apiAzure;
	
    public Multi<String> callChat(ChatMessagesAzureRequest chatMessageRequest) {
        logger.info("callChat External API");
            return this.apiAzure.processGenerativeAIWithChatMessageSse(this.apiKey,
                    this.deploymentId,
                    this.apiVersion,
                    chatMessageRequest)
                    .onFailure().invoke(t ->
                    logger.info(String.format("Oh no! We received a failure: %s",
                            t.getMessage()))
            );
    }@RestClient
    AzureOpenAiApi apiAzure;
	
    public Multi<String> callChat(ChatMessagesAzureRequest chatMessageRequest) {
        logger.info("callChat External API");
            return this.apiAzure.processGenerativeAIWithChatMessageSse(this.apiKey,
                    this.deploymentId,
                    this.apiVersion,
                    chatMessageRequest)
                    .onFailure().invoke(t ->
                    logger.info(String.format("Oh no! We received a failure: %s",
                            t.getMessage()))
            );
    }`

**interface C** :

`@RegisterRestClient(configKey = "azure-api")
@RegisterProvider(WebApplicationExceptionRequestFilter.class)
@RegisterProvider(ResponseContainerRequestFilter.class)

@Path("/openai/deployments")
public interface AzureOpenAiApi {

    @POST
    @Path("/{deploymentId}/chat/completions")
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    Multi<String> processGenerativeAIWithChatMessageSse(@HeaderParam("api-key") String apiKey,
                                                                              @PathParam("deploymentId") String deploymentId,
                                                                              @QueryParam("api-version") String apiVersion,
                                                                              ChatMessagesAzureRequest chatMessagesAzureRequest);
`

**Comment by geoand** [comment]
In the case you are tying to use SSE for consuming the OpenAI APIs, you are in luck - see our [langchain4j extension](https://github.com/quarkiverse/quarkus-langchain4j) which already provides all you need.

If you really want to see how things have been implemented on the SSE side, checko out [this](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java).

**Comment by xtof974** [comment]
I have a **service A** that calls a **service B** that calls the SSE endpoint via the **interface C**. The way below.
The **interface C** returns Multi<string> to the **service B**  that returns it to service A. The latter transforms it to Multi<ChatMessagesSseResponse>. I specify again that all this works well (without error > 400 return by **interface C**) 

**service A** :


```java
Multi<ChatMessagesSseResponse> chatMessageResponse = this.proxyChatMessageResource.callChat(chatMessageRequest)
              .onItem()
              .transform(res -> {
                  ChatMessagesSseResponse chatMessagesSseResponse = new ChatMessagesSseResponse();
                  try {
                      if (!res.contains("[DONE]")) {
                          ChatMessagesAzureSseResponse chatMessagesResponse = objectMapper.readValue(res, ChatMessagesAzureSseResponse.class);
                          if (chatMessagesResponse.choices().get(0).delta().content() != null && chatMessagesResponse.id() != null) {
                              chatMessagesSseResponse = new ChatMessagesSseResponse(chatMessagesResponse);
                          }
                      }
                  } catch (JsonProcessingException e) {
                      throw new RuntimeException(e);
                  }
                  return chatMessagesSseResponse;
              })
              .onFailure().invoke(t ->
                      logger.info(String.format("Oh no! We received a failure: %s",
                              t.getMessage())));
      return chatMessageResponse
              .select().where(message -> message.getId() != null);
}
```

**service B**  :

```java
@RestClient
   AzureOpenAiApi apiAzure;

   public Multi<String> callChat(ChatMessagesAzureRequest chatMessageRequest) {
       logger.info("callChat External API");
           return this.apiAzure.processGenerativeAIWithChatMessageSse(this.apiKey,
                   this.deploymentId,
                   this.apiVersion,
                   chatMessageRequest)
                   .onFailure().invoke(t ->
                   logger.info(String.format("Oh no! We received a failure: %s",
                           t.getMessage()))
           );
   }
```


**interface C** :

```java
@RegisterRestClient(configKey = "azure-api")
@RegisterProvider(WebApplicationExceptionRequestFilter.class)
@RegisterProvider(ResponseContainerRequestFilter.class)

@Path("/openai/deployments")
public interface AzureOpenAiApi {

    @POST
    @Path("/{deploymentId}/chat/completions")
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    Multi<String> processGenerativeAIWithChatMessageSse(@HeaderParam("api-key") String apiKey,
                                                                              @PathParam("deploymentId") String deploymentId,
                                                                              @QueryParam("api-version") String apiVersion,
                                                                              ChatMessagesAzureRequest chatMessagesAzureRequest);
```

**Comment by geoand** [comment]
See my comment above :)

**Comment by xtof974** [comment]
```url
{
    "error": {
        "message": "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766",
        "type": null,
        "param": "prompt",
        "code": "content_filter",
        "status": 400
    }
}
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/38369 fixes the problem
