### ISSUE TITLE
Issue with mp.messaging.incoming."channel-name".health-enabled property in Quarkus 2.4  and above

### ISSUE THREAD

**Issue by Kris3264** [quarkusio/quarkus#38329]
### Describe the bug

Previously, I had multiple incoming channels with the property mp.messaging.incoming."channel-name".health-enabled: false, which disabled health checks for those specific channels. However, this property no longer seems to function as intended in Quarkus version 2.4. It was working fine in version 2.3, but ceased to work after version 2.4.

### Expected behavior

The mp.messaging.incoming property. "channel-name".health-enabled should disable health checking for the specified incoming channel

### Actual behavior

The mp.messaging.incoming property. "channel-name".health-enabled seems to have no effect after Quarkus 2.4.

**Comment by cescoffier** [comment]
Which connector are you using?

**Comment by cescoffier** [comment]
Note that Quarkus 2.4 is very outdated.

**Comment by Kris3264** [comment]
I'm using the current one now, but the problem persists.

**Comment by cescoffier** [comment]
Can you provide a reproducer?

**Comment by Kris3264** [comment]
https://github.com/quarkusio/quarkus/issues/13920 This discussion has the same error with the example. The solution proposed there does not suit me

**Comment by cescoffier** [comment]
The discussion is different as it's for all channels.

Any chance to provide a reproducer?

**Comment by cescoffier** [comment]
I tried with the Kafka quickstart, and it works as expected. It uses Quarkus _main_ (999-SNAPSHOT), but we haven't changed anything related to that.

For example, my app has two channels:

- quotes
- quote-requests

I added to my `application.properties` file:
```
mp.messaging.incoming.quotes.health-enabled=false
```

And now, my health report contains only the `quote-requests`:

```json
{
    "status": "UP",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "UP",
            "data": {
                "quote-requests": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "quote-requests": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - startup check",
            "status": "UP",
            "data": {
                "quote-requests": "[OK]"
            }
        }
    ]
}
```

If I remove the property, I get both channels:

```json
{
    "status": "UP",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - liveness check",
            "status": "UP",
            "data": {
                "quotes": "[OK]",
                "quote-requests": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "quotes": "[OK] - no subscription yet, so no connection to the Kafka broker yet",
                "quote-requests": "[OK]"
            }
        },
        {
            "name": "SmallRye Reactive Messaging - startup check",
            "status": "UP",
            "data": {
                "quotes": "[OK] - no subscription yet, so no connection to the Kafka broker yet",
                "quote-requests": "[OK]"
            }
        }
    ]
}
```

Please reopen with a reproducer.

**Comment by bcluap** [comment]
FYI As of 3.7.0.CR1 this property no longer turns off smallrye messaging health checks: quarkus.health.extensions.enabled=false

I've now had to add mp.messaging.incoming.XXX.health-enabled=false to disable the health checks. This was kinna a breaking change for us as our latest deployment failed as ECS saw our services as down on nodes that we had intentionally not set up valid connection info to rabbit for (but had the extension installed)

**Comment by bcluap** [comment]
In fact even mp.messaging.incoming.XXX.health-enabled=false has issues. It does not report a failed channel as unhealthy at first, but if for example it cannot connect to Rabbit at all, then after 10m of being up and healthy, they respond as unhealthy. BanknodeScanToPayBankReplyListener uses @Incoming("banknode-replies") and we have mp.messaging.incoming.banknode-replies.health-enabled=false

```
{
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "application-com.ukheshe.services.banknodescantopay.BanknodeScanToPayBankReplyListener#consume": "[KO] - Connection refused"
            }
        }
```

So both quarkus.health.extensions.enabled=false and mp.messaging.incoming.XXX.health-enabled=false are no longer preventing health checks from failing due to rabbit being down.

**Comment by cescoffier** [comment]
That sounds like a rabbitmq issue. I will have a look. Again providing a reproducer would make a big difference.

**Comment by Kris3264** [comment]
I have found a solution to this issue

`    // We came to this decision:

    @Incoming("channel-in.dead-letter.events")
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    public Uni<Void> consumeDeadLetter(Message<String> msg) {

        return Uni.createFrom().voidItem()
                .map(empty -> {
                    try {

                        var message = extractMessage(msg); // An exception may be thrown!

                        return operation.process(message)
                                .flatMap(unused -> convertCompletionStageToUni(msg.ack()))
                                .onFailure(WarningServiceException.class)
                                .recoverWithUni(ex -> {
                                    // Step 1: OK
                                    return convertCompletionStageToUni(msg.ack());
                                })
                                .onFailure()
                                .recoverWithUni(ex -> {
                                    // Step 1: FAIL
                                    // For this exception will be added record in health-check: 'channel-in.dead-letter.events': [KO]
                                    return convertCompletionStageToUni(msg.nack(ex));
                                });

                    } catch (Throwable ex) {
                        return convertCompletionStageToUni(msg.nack(ex));
                    }
                })
                .onFailure()
                .invoke(ex -> log.error("Error: " + ex))
                // ! Step 2: Need to catch upstream exceptions
                //  Without this recover, vert.x-eventloop-thread will be created: 'application.project...KafkaConsumer#consumeDeadLetter' : [KO]
                //  And health-check will return DOWN
                // Solution:
                .onFailure()
                .recoverWithNull();
    }
`
But I don't understand why this is happening? Why in step 2 does the error go to the helf check? And why does it always happen 2 times? Is there some kind of setting for this?

**Comment by cescoffier** [comment]
it's because if you do not handle it, the failure is propagated downstream until reactive messaging catches it and reports it as an application failure.
