### ISSUE TITLE
Support image from local docker daemon for jib build base image 

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#38320]
### Description

Jib supports the usage of a local docker base image already since a while: https://github.com/GoogleContainerTools/jib/issues/1468#issuecomment-531373394

It seems that the same does not work when using the quarkus property to point to a local docker image `quarkus.jib.base-native-image=docker://my-customquarkus-native-image:latest`

It would be neat if quarkus would also support this, as we build the base image within the git workflow and would like to omit the push

**Comment by geoand** [comment]
Thanks, can you give #38324 a try?
