### ISSUE TITLE
Support @InjectMock on test constructor arguments

### ISSUE THREAD

**Issue by michaeldimchuk** [quarkusio/quarkus#38336]
### Description

For background, typically when I setup a project, I setup a `lombok.config` file with `lombok.fieldDefaults.defaultPrivate` and `lombok.fieldDefaults.defaultFinal` options set to `true`, making all fields in every class `private final` by default, mostly to reduce boilerplate and keep things a bit cleaner.

One difficulty with this is using `@QuarkusComponentTest` with `@InjectMock`, which due to its reliance on field injection, wouldn't work with final fields. I can work around it by adding `@FieldDefaults(makeFinal = false)` on the class, but I'd prefer to keep everything consistently final across the board if possible.

It would help if `@QuarkusComponentTest` would identify that an injectable constructor exists (whether by the presence of an `@Inject` annotation, a non-empty constructor or usages of `@InjectMock` on the arguments), and use that for initializing the class instance, injecting mocks as necessary.

### Implementation ideas

The `MockitoExtension` is a decent example of how something like this can be achieved: https://github.com/mockito/mockito/blob/main/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java#L208.

It supports constructor injection of mocks with `@Mock` on the arguments, though not the mockito version of `@InjectMocks`. When using this extension, I would typically setup Lombok with `lombok.copyableAnnotations += org.mockito.Mock`, which will copy the annotations from the fields the constructor generated by `@RequiredArgsConstructor`.

Something along those lines would be helpful with the Quarkus `@InjectMock`, which would need to be allowed to be declared on constructor arguments in addition to fields.

**Comment by mkouba** [comment]
Unfortunately, this would not match the default lifecycle with `org.junit.jupiter.api.TestInstance.Lifecycle.PER_METHOD`, where  the CDI container is started "before each" test and stopped during the "after each" phase. And even for `TestInstance.Lifecycle.PER_CLASS` the container is started after the test instance is created. In other words, we would not be able to obtain the injected beans...

**Comment by michaeldimchuk** [comment]
It should be possible if using the `TestInstancePreConstructCallback` and `TestInstancePreDestroyCallback`  instead of `BeforeEachCallback` and `AfterEachCallback` to setup the CDI context.

`TestInstancePreConstructCallback` is called before parameters are resolved, which would still allow for a per method CDI context and constructor injection.

**Comment by mkouba** [comment]
> It should be possible if using the `TestInstancePreConstructCallback` and `TestInstancePreDestroyCallback` instead of `BeforeEachCallback` and `AfterEachCallback` to setup the CDI context.
> 
> `TestInstancePreConstructCallback` is called before parameters are resolved, which would still allow for a per method CDI context and constructor injection.

That is a good point! I was not aware of these callbacks. I will try to adopt this API and send a PR if possible...

**Comment by mkouba** [comment]
Hm, it seems that the test method is not available when the `TestInstancePreConstructCallback` is invoked (i.e. `ExtensionContext.getTestMethod()` returns an empty optional) and this causes troubles when a `@io.quarkus.test.component.TestConfigProperty` is used on a test method. Note that we need to process this information before the container is started...

**Comment by mkouba** [comment]
> What can be interesting (and feasible) is injection of params of a test method 🤔...

A draft PR is here: https://github.com/quarkusio/quarkus/pull/38379

**Comment by michaeldimchuk** [comment]
Did a bit of digging and looks like that's essentially expected: https://github.com/junit-team/junit5/issues/1568#issuecomment-417859532.

Since test instance creation extensions are scoped to the class, they're explicitly never allowed to have access to the test method itself, so the scenario of using test method annotations to configure a CDI container meant to construct the test instance itself, is not truly in line with the design of JUnit 5, though post-processing an instance and injecting mutable fields is.

Interestingly enough, it seems that constructor level parameter resolution is also scoped to the class level lifecycle rather than test method lifecycle like method parameter resolution is: https://github.com/junit-team/junit5/issues/3445, though this is something the JUnit team may be re-evaluating. 

I'll see if the JUnit team is open to re-open that original issue as at least to me, it makes sense to be able to apply method level configurations to the instance creation process given that the PER_METHOD lifecycle exists. 

That being said though, being able to use `@InjectMock` on test method parameters would kinda improve that situation, and adds some interesting flexibility to `@QuarkusComponentTest`, very convenient to be able to mock something out specifically on a test by test basis.

**Comment by mkouba** [comment]
> Did a bit of digging and looks like that's essentially expected: [junit-team/junit5#1568 (comment)](https://github.com/junit-team/junit5/issues/1568#issuecomment-417859532).
> 
> Since test instance creation extensions are scoped to the class, they're explicitly never allowed to have access to the test method itself, so the scenario of using test method annotations to configure a CDI container meant to construct the test instance itself, is not truly in line with the design of JUnit 5, though post-processing an instance and injecting mutable fields is.
> 
> Interestingly enough, it seems that constructor level parameter resolution is also scoped to the class level lifecycle rather than test method lifecycle like method parameter resolution is: [junit-team/junit5#3445](https://github.com/junit-team/junit5/issues/3445), though this is something the JUnit team may be re-evaluating.
> 
> I'll see if the JUnit team is open to re-open that original issue as at least to me, it makes sense to be able to apply method level configurations to the instance creation process given that the PER_METHOD lifecycle exists.

Ok, we'll see.

> 
> That being said though, being able to use `@InjectMock` on test method parameters would kinda improve that situation, and adds some interesting flexibility to `@QuarkusComponentTest`

:+1: 

> very convenient to be able to mock something out specifically on a test by test basis.

This should be possible even now. However,  test methods parameter injection would make it IMO more clear and more readable. Currently it's not exactly clear that injected fields are reinjected for each test method if `Lifecycle.PER_METHOD` is used.

**Comment by mkouba** [comment]
> That being said though, being able to use @InjectMock on test method parameters would kinda improve that situation, and adds some interesting flexibility to @QuarkusComponentTest, very convenient to be able to mock something out specifically on a test by test basis.

Test method parameter injection was implemented in 3.9.0.CR1. 

I'm going to close this issue because it seems that `TestInstancePreConstructCallback` still cannot be used for our use case.
