### ISSUE TITLE
query error in ftsearch() when trying to use Redis-search

### ISSUE THREAD

**Issue by stephane-drogou** [quarkusio/quarkus#38330]
### Describe the bug

Hello,

When I call ftSearch(index, query) function the client response an error instead of the result of the query.

The error is "java.util.concurrent.CompletionException: Syntax error at offset 1 near voie" as if I forgot he "@" caracter.

### Expected behavior

I expect to receive the result of corresponding FT.SEARCH command in redis-cli.

### Actual behavior

An error is sent corresponding to an error in the query, but when I send the exact same query in redis-cli it's working.

### How to Reproduce?

Reproducer:

1. Start a Redis stack docker instance
2. In this instance create an index: "ft.create idx:voiture on hash prefix 1 voiture:dyn: schema pk numeric sortable voie tag sortable"
3. In this instance create several datas corresponding to this index: 
- hmset voiture:dyn:001 pk 10 voie c8l2
- hmset voiture:dyn:002 pk 22 voie c8l2
- hmset voiture:dyn:003 pk 10 voie c9l2
- hmset voiture:dyn:004 pk 14 voie c8l2
4.  In this instance test a ft.search : ft.search idx:voitre "@voie:{c8l2} @pk:[8 16]"
Redis well answer with voiture:dyn:001 and voiture:dyn:004
5. Write a client which do this search: 
```
@Singleton
public class RedisOperation {

    private final HashCommands<String, String, String> hashc;
    private final SearchCommands<String> searchc;

    public RedisOperation(RedisDataSource ds) {
        hashc = ds.hash(String.class);
        searchc = ds.search(String.class);
    }

    public String get(String key, String field) {
        String retour;
        retour = hashc.hget(key, field);
        log.info("La commande a renvoyé : "+retour);
        return retour;
    }

    public String getIndex(String idVoie,Integer pkDebut,Integer pkFin) {
        String index = "idx:voiture";
        String query = "\"@voie:{"+idVoie+"} @pk:["+pkDebut+" "+pkFin+"]\"";
    
        StringBuilder retour = new StringBuilder("");

        log.info("On envoie la demande de recherche sur "+index+" lavec la query : "+query);
        SearchQueryResponse result = searchc.ftSearch(index, query);
        
        log.info("la requête est passée");
        log.info("La réponse est : "+result.toString());
        for (Document doc : result.documents()) {
            log.info("Trouver : "+doc.key());
            retour.append(" ").append(doc.key());
        }
        return retour.toString();
    }
}
```
6. When I execute this code, I received the following error:

> 024-01-22 12:00:23,181 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /referentiel/check failed, error id: 7aca9804-3363-4a06-a677-2cd6ff885a9b-1: java.util.concurrent.CompletionException: Syntax error at offset 1 near voie
> 	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
> 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
> 	at io.quarkus.redis.runtime.datasource.BlockingSearchCommandsImpl.ftSearch(BlockingSearchCommandsImpl.java:116)
> 	at org.acme.data.RedisOperation.getIndex(RedisOperation.java:38)
> 	at org.acme.endpoint.ReferentielControl.check(ReferentielControl.java:33)
> 	at org.acme.endpoint.ReferentielControl$quarkusrestinvoker$check_64c0cbd5ef6d0fa67060dba6907356b2ebacb7b5.invoke(Unknown Source)
> 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
> 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
> 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
> 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
> 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: Syntax error at offset 1 near voie

### Output of `uname -a` or `ver`

Linux vmDev 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/sdrogou/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /home/sdrogou/.jbang/cache/jdks/17 Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "5.10.0-21-amd64", arch: "amd64", family: "unix"

### Additional information

As I work on this feature for several days, I described the issue in stackoverflow :
https://stackoverflow.com/questions/77845421/how-to-use-ftsearch-command-with-redisdatasource-in-quarkus/77858435

All the source code used can be found on this github depot : 
https://github.com/stephane-drogou/redis-search-example.git

**Comment by cescoffier** [comment]
Can you provide a minimal reproducer including:

- the index/schema definition
- the problematic code

**Comment by stephane-drogou** [comment]
Hello,

As described in the issue : 
    index/schema definition is : 
            ft.create idx:voiture on hash prefix 1 voiture:dyn: schema pk numeric sortable voie tag sortable
            
            I provided some examples of datas : 
            hmset voiture:dyn:001 pk 10 voie c8l2
            hmset voiture:dyn:002 pk 22 voie c8l2
            hmset voiture:dyn:003 pk 10 voie c9l2
            hmset voiture:dyn:004 pk 14 voie c8l2
            
            and the query search I run in the redis-cli : 
            ft.search idx:voitre "https://github.com/voie:{c8l2} @pk:[8 16]

problematic code can be found in the https://github.com/stephane-drogou/redis-search-example.git repository
The function which sends the ft.search command which is problemetic is the following : 
```
public String getIndex(String idVoie,Integer pkDebut,Integer pkFin) {
        String index = "idx:voiture";
        String query = "\"@voie:{"+idVoie+"} @pk:["+pkDebut+" "+pkFin+"]\"";
    
        StringBuilder retour = new StringBuilder("");

        log.info("On envoie la demande de recherche sur "+index+" lavec la query : "+query);
        SearchQueryResponse result = searchc.ftSearch(index, query);
        
        log.info("la requête est passée");
        log.info("La réponse est : "+result.toString());
        for (Document doc : result.documents()) {
            log.info("Trouver : "+doc.key());
            retour.append(" ").append(doc.key());
        }
        return retour.toString();
    }
```

**Comment by cescoffier** [comment]
Do you have the exact CLI command that works? So, I can compare what's happening on the wire.

**Comment by stephane-drogou** [comment]
To test in redis-cli you have to perform the following commands : 
ft.create idx:voiture on hash prefix 1 voiture:dyn: schema pk numeric sortable voie tag sortable
hmset voiture:dyn:001 pk 10 voie c8l2
hmset voiture:dyn:002 pk 22 voie c8l2
hmset voiture:dyn:003 pk 10 voie c9l2
hmset voiture:dyn:004 pk 14 voie c8l2
ft.search idx:voiture "@voie:{c8l2} @pk:[8 16]"

In this case the result in the cli is the following : 
1) (integer) 2
2) "voiture:dyn:001"
3) 1) "pk"
   2) "10"
   3) "voie"
   4) "c8l2"
4) "voiture:dyn:004"
5) 1) "pk"
   2) "14"
   3) "voie"
   4) "c8l2"

I let you check by yourself

And thank you for your help :)

**Comment by stephane-drogou** [comment]
I just realize that in my example the id are in french (sorry for that). Here the same commands with ids in english : 

ft.create idx:car on hash prefix 1 car:dyn: schema kp numeric sortable lane tag sortable
hmset car:dyn:001 kp 10 lane c8l2
hmset car:dyn:002 kp 22 lane c8l2
hmset car:dyn:003 kp 10 lane c9l2
hmset car:dyn:004 kp 14 lane c8l2
ft.search idx:car "@lane:{c8l2} @kp:[8 16]"

**Comment by cescoffier** [comment]
You got the query wrong:

```java
        String query = "@voie:{"+idVoie+"} @pk:["+pkDebut+" "+pkFin+"]";
```

I removed the wrapping "".

With that code, you get:

```
 voiture:dyn:001 voiture:dyn:004
 ```
 
 
A few things you may like:

- You can use the Redis stack as dev service, just remove the redis URL and add `quarkus.redis.devservices.image-name=redis/redis-stack:latest` to your `application.properties`
- You can add an `import.redis` in `src/main/resources` with the following content:
```
ft.create idx:voiture on hash prefix 1 voiture:dyn: schema pk numeric sortable voie tag sortable
hmset voiture:dyn:001 pk 10 voie c8l2
hmset voiture:dyn:002 pk 22 voie c8l2
hmset voiture:dyn:003 pk 10 voie c9l2
hmset voiture:dyn:004 pk 14 voie c8l2
ft.search idx:voiture "@voie:{c8l2} @pk:[8 16]"
```
It runs that script during the redis initialization.

**Comment by stephane-drogou** [comment]
Hello,

I am really sorry, but I added the wrapping "" because it doesn't work without. Without it, I have the following erreor : 

> 2024-01-22 17:37:21,981 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /referentiel/check failed, error id: db7fc026-00e5-420a-9db9-0c2ecc57c541-1: java.lang.RuntimeException: Multi is a Map
> 	at io.vertx.redis.client.impl.types.MultiType.get(MultiType.java:114)
> 	at io.vertx.mutiny.redis.client.Response.get(Response.java:189)
> 	at io.quarkus.redis.runtime.datasource.ReactiveSearchCommandsImpl.decodeSearchQueryResult(ReactiveSearchCommandsImpl.java:188)
> 	at io.quarkus.redis.runtime.datasource.ReactiveSearchCommandsImpl.lambda$ftSearch$7(ReactiveSearchCommandsImpl.java:181)
> 	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
> 	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
> 	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
> 	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
> 	at io.quarkus.redis.runtime.client.ObservableRedis.lambda$send$1(ObservableRedis.java:54)
> 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 	at io.vertx.core.impl.future.Eventually$1.onSuccess(Eventually.java:44)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
> 	at io.vertx.core.impl.future.Eventually.onSuccess(Eventually.java:41)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 	at io.vertx.core.impl.future.Transformation$1.onSuccess(Transformation.java:63)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
> 	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
> 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:44)
> 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
> 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
> 	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
> 	at io.vertx.redis.client.impl.RedisStandaloneConnection.handle(RedisStandaloneConnection.java:417)
> 	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:296)
> 	at io.vertx.redis.client.impl.RESPParser.handleMulti(RESPParser.java:262)
> 	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:102)
> 	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:24)
> 	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:101)
> 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
> 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
> 	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:402)
> 	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
> 	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)
> 	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:378)
> 	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
> 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

May be I forgot something else

**Comment by cescoffier** [comment]
Which redis version are you using? Redis 7.2 (if I am not mistaken) changed the formatting. You would need to use a more recent version of Quarkus to get the new format.

**Comment by stephane-drogou** [comment]
> Which redis version are you using? Redis 7.2 (if I am not mistaken) changed the formatting. You would need to use a more recent version of Quarkus to get the new format.

I checked and you're right !!! I used a 7.2.4 server. I tried with a 6.2.6 and it works !!!!

Thanks a lot !!!!!!!
