### ISSUE TITLE
ArtemisTestResource available

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#3833]
**Description**
Artemis integration test has an `ArtemisTestResource` https://github.com/quarkusio/quarkus/pull/2930/files#diff-76fa3fe6358cacc251f9cb4d29ae82ac to manage the lifecycle of an embedded Artemis instance for testing purposes.

The problem is that this class is not available for all users, I think that this kind of utilities should be available for any user because the way we test these integrations might be used by any dev.

So I think that this class should be moved to either an `artemis-test` artifact or in a place that can be used by anyone.

Generally speaking, I think that any util used in our integration tests should not be implemented in the integration tests itself but in a place that could be used by anyone, because at the end our necessities for testing probably are going to be the same for anyone writing test for Quarkus.

**Comment by uaihebert** [comment]
Hello, I create a PR for this issue. Let me know what should be improved.
