### ISSUE TITLE
ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-1) {} Connection reset

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkusio/quarkus#38335]
### Describe the bug

We are occationally getting the following error in our service logs:

```
ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-1) {} Connection reset
```

or

```
ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) {} Connection reset
```

1 or more of these logs may appear at the same time. It may be the same eventloop thread, or different threads that are logged multiple times at the same time.

These is nothing else in our metrics or traces that suggest that any requests are failing. Everything seems to be working as normal.

We are observing this error in Quarkus 3.6.6 and 3.6.1, but not 3.4.3 with the following dependencies:

```groovy
implementation 'io.quarkus:quarkus-smallrye-openapi'
implementation 'io.quarkus:quarkus-rest-client-reactive-jackson'
implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
implementation 'io.quarkus:quarkus-smallrye-fault-tolerance'
implementation 'io.quarkus:quarkus-arc'
implementation 'io.quarkus:quarkus-smallrye-context-propagation'
implementation 'io.quarkus:quarkus-smallrye-health'
implementation 'io.quarkiverse.micrometer.registry:quarkus-micrometer-registry-otlp:3.2.4'
implementation 'io.quarkus:quarkus-opentelemetry'
implementation 'io.opentelemetry:opentelemetry-extension-trace-propagators'
implementation 'io.quarkus:quarkus-smallrye-jwt'
implementation 'io.quarkus:quarkus-cache'
```

### Expected behavior

No error log, since there seems to be no actual errors

### Actual behavior

```
ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-1) {} Connection reset
```

is being logged

### How to Reproduce?

We don't know what is causing this, and there are no other logs along with the error. I'm hoping you can help us with ideas on how to enable additional logging, that might hint at the cause.

### Output of `uname -a` or `ver`

Linux wealth-items-service-8455646c6-wmbc5 5.14.0-284.41.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 9 13:57:27 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -XX:+UseG1GC -XX:+UseContainerSupport -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 openjdk 17.0.9 2023-10-17 LTS OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS) OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

See description

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2.1

**Comment by geoand** [comment]
I kind of doubt that we will be able to do much without a way to reproduce the problem

**Comment by cescoffier** [comment]
Connection reset is generally "normal", as least expected. It happens when the client or something in between (like a proxy) cuts the connection abruptly (often to recycle it or after a period of inactivity (generally 10s)). 

The request is not failing (well, most of the time - if the cut happens during the processing, sure), because it often happens after the request has been processed. The connection is kept open (keep-alive:true), and is then cut because of inactivity. or client decision.

**Comment by cescoffier** [comment]
If it happens during the processing you would get an exception as you would not be able to write the response.

About the warning, you might be able to configure the log level of the logger.

**Comment by AndreasPetersen** [comment]
Great, thanks for the insight @cescoffier

**Comment by Chrisx0385** [comment]
So if the 

> Connection reset is generally "normal",

it would be nice if it wouldn't be logged as error. Wouldn't INFO or WARN be a better level for such a message?
Setting the logger severity above ERROR would mean switching this logger category off completely.
