### ISSUE TITLE
Documentation for quarkus.test.profile not mentioning multi-profile support?

### ISSUE THREAD

**Issue by marcelstoer** [quarkusio/quarkus#38345]
### Describe the bug

https://quarkus.io/guides/continuous-testing#configuring-continuous-testing currently documents `quarkus.test.profile` as not having multi-profile support.

> The profile (dev, test or prod) to use ...

> Type: string

Since Quarkus now accepts `quarkus.profile` to be a comma-separated list of profiles, I expected the same support for `quarkus.test.profile`. And indeed, running Quarkus using `-Dquarkus.test.profile=foo,bar` does seem supported. 

> Profiles bar,foo activated.

Yet, the documentation still lists `quarkus.test.profile` as being a single string.

**Comment by marcelstoer** [comment]
Oh, same situation here for `quarkus.profile`: https://quarkus.io/guides/config-reference#configuration-reference.

**Comment by geoand** [comment]
Would you like to propose an improvement?

**Comment by marcelstoer** [comment]
Sure, I was just waiting for a confirmation that this indeed is a docs bug rather than a misunderstanding on my behalf 😄

**Comment by marcelstoer** [comment]
At first I was really confused how the implementation can be so inconsistent with your documentation, knowing that your reference docs is generated from code.

After some digging and grepping in your code to find the correct classes I found this https://github.com/quarkusio/quarkus/blob/71f320066de23e137fd9eaeeb02fa8b70d13b386/core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestConfig.java#L16 and this https://github.com/quarkusio/quarkus/blob/71f320066de23e137fd9eaeeb02fa8b70d13b386/core/runtime/src/main/java/io/quarkus/runtime/ConfigConfig.java#L13-L17 

It all makes sense now 🤓 It explains why I found no references to those `profile()` methods. This in turn confirms that I can change the types from `String` to `List<String>` without breaking anything.
