### ISSUE TITLE
Quartz extension issue with parameters batchTriggerAcquisitionMaxCount  and batchTriggerAcquisitionFireAheadTimeWindow

### ISSUE THREAD

**Issue by sebdet** [quarkusio/quarkus#38356]
### Describe the bug

These parameters are not taken into account by the quartz extension (in version 2.X and version 3.X), the values are always set to 1 for batchTriggerAcquisitionMaxCount  and 0 for batchTriggerAcquisitionFireAheadTimeWindow, even if I put some values in the application.properties or if I define env var.
I have investigated the code and I have debugged the code, it seems the problem is located here:
https://github.com/quarkusio/quarkus/blob/3.6/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzSchedulerImpl.java  line 517 & 518
```
        props.put(StdSchedulerFactory.PROP_SCHED_BATCH_TIME_WINDOW, runtimeConfig.batchTriggerAcquisitionFireAheadTimeWindow);
        props.put(StdSchedulerFactory.PROP_SCHED_MAX_BATCH_SIZE, runtimeConfig.batchTriggerAcquisitionMaxCount);
```

This must be replaced by:
```
        props.put(StdSchedulerFactory.PROP_SCHED_BATCH_TIME_WINDOW, ""+runtimeConfig.batchTriggerAcquisitionFireAheadTimeWindow);
        props.put(StdSchedulerFactory.PROP_SCHED_MAX_BATCH_SIZE, ""+runtimeConfig.batchTriggerAcquisitionMaxCount);
```
So that the values in well defined in String in the properties object and the QUartz scheduler is able to convert them to int.
Thank you

### Expected behavior

These parameters batchTriggerAcquisitionMaxCount  and batchTriggerAcquisitionFireAheadTimeWindow, when defined in the application.properties or defined in the env var must be taken into account and propagated to QUartz.

### Actual behavior

These parameters batchTriggerAcquisitionMaxCount  and batchTriggerAcquisitionFireAheadTimeWindow are obviously not set in QUartz, instead they are respectively defined to 1 and 0.

### How to Reproduce?

Just set quarkus.quartz.batch-trigger-acquisition-fire-ahead-time-window or quarkus.quartz.batch-trigger-acquisition-max-count to a value in application.properties

**Comment by mkouba** [comment]
@sebdet would you care to send a pull request?

**Comment by mkouba** [comment]
> @sebdet would you care to send a pull request?

Nevermind, I'll send a PR shortly..
