### ISSUE TITLE
REST endpoint containing a @Gauge annotation will not work properly

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#3838]
The problem is that we've recently started  [adding a @Dependent annotation](https://github.com/quarkusio/quarkus/blob/5fd1a57eb423fd95e3045feecf39ccb7a284dccd/extensions/smallrye-metrics/deployment/src/main/java/io/quarkus/smallrye/metrics/deployment/SmallRyeMetricsProcessor.java#L124)  to classes where we find metric annotations and they don't have any explicit CDI scope, this is to enable them as CDI beans so that the metrics will work on them. Unfortunately it turns out that if we do this for a REST endpoint, so it turns into a `@Dependent` bean, for every HTTP request a new instance will be created, but there is a Gauge in the bean and gauges are allowed to exist only for beans that create only one instance (so when a new instance is being created, the gauge is attempted to be re-registered, and that is forbidden).

The effect that a REST endpoint is turned into a `@Dependent` scoped bean is also undesirable

**Comment by mkouba** [comment]
> for every HTTP request a new instance will be created

There was a discussion that this should be actually the default behavior, at least from JAX-RS spec POV. However, `@Singleton` is still the default in quarkus: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L126 

> and gauges are allowed to exist only for beans that create only one instance

Do we validate a gauge declared on a `@Dependent` bean?

> The effect that a REST endpoint is turned into a @Dependent scoped bean is also undesirable

I agree. The question is how to detect a JAX-RS resource without the dependency on JAX-RS/resteasy extension? A simple workaround would be to ignore types annotated with `DotName.createSimple("javax.ws.rs.Path")`. This would probably cover 99% of use cases.

**Comment by jmartisk** [comment]
> Do we validate a gauge declared on a @Dependent bean?

We allow it right now, but it might be a good idea to throw an error if this is detected. Metrics spec allows throwing a validation error (but does not require it - theoretically there might be cases when such dependent bean will still only have one instance, in which case the gauge would work correctly - it breaks once a second instance is being built).

> The question is how to detect a JAX-RS resource without the dependency on JAX-RS/resteasy extension? 

Yeah I've been wondering about the same thing. Is there any option in Quarkus how to turn a bean into a REST endpoint other than annotating it `@Path` in a way that we will see it in the Jandex index?

**Comment by mkouba** [comment]
> Is there any option in Quarkus how to turn a bean into a REST endpoint ...

There is. An extension can produce an `AdditionalJaxRsResourceDefiningAnnotationBuildItem`. But it seems that it's currently only used in the `spring-web` extension to turn a class annotated with `@RestController` into a resource.
