### ISSUE TITLE
quarkus cli not remembering installed plugs 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#38391]
### Describe the bug

running `quarkus kill` ask me to install quarkus cli.
I say Yes.

.quarkus has recorded the installation and `quarkus help` shows the kill comman.

But run `quarkus kill` again and it asks me again.

### Expected behavior

should not keep asking me to install what is already installed.

**Comment by iocanel** [comment]
Fixed with: https://github.com/quarkusio/quarkus/pull/38435
