### ISSUE TITLE
webauthn.js for WebAuthn returns errors only with statusText, but instead should return full response/`res` so UI can capture more detailed error responses

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#38400]
webauth.js for WebAuthn returns errors only with statusText, but instead should return full response/`res` so UI can capture more detailed error responses

https://github.com/quarkusio/quarkus/blob/f418d11516af7681a7aea10d54c8f18eca8da1d1/extensions/security-webauthn/runtime/src/main/resources/webauthn.js#L126

**Comment by StephenOTT** [comment]
This change should be made in the 4 methods in webauthn where statusText is being bubbled instead of the `res`

**Comment by StephenOTT** [comment]
cc @FroMage

**Comment by FroMage** [comment]
Apparently, in JS, errors should always have a message, but we could add the response as a `cause`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#options

**Comment by StephenOTT** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#omitting_options_argument

could we do something from the examples: `const error3 = new Error("Error message", { details: "http error" });`

except we do something like `const error3 = new Error("Error message", { details: res });` where res is the http response

**Comment by StephenOTT** [comment]
because `cause` appears to be supposed to be used to show the nested `Error` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause

**Comment by FroMage** [comment]
> The value of cause can be of any type. You should not make assumptions that the error you caught has an Error as its cause, in the same way that you cannot be sure the variable bound in the catch statement is an Error either

It goes on to show an example of a struct as a cause :)

**Comment by StephenOTT** [comment]
!! did not scroll down far enough https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause :) 👍

**Comment by FroMage** [comment]
:)

**Comment by FroMage** [comment]
JS is surprising to anyone not familiar with it, me first.
