### ISSUE TITLE
Make cookie names for WebAuthN configurable

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#38401]
### Description

https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnController.java#L27-L29

These cookie names are currently hardcoded. 

### Implementation ideas

Would be nice if they were configurable as part of the webAuthn config https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java

**Comment by sberyozkin** [comment]
@StephenOTT Please see #38351

**Comment by StephenOTT** [comment]
@sberyozkin apologies.  I missed that one!
