### ISSUE TITLE
application-test.yml is not utilized during tests executed during gradle build

### ISSUE THREAD

**Issue by bitsofinfo** [quarkusio/quarkus#38424]
### Describe the bug

I run ./gradlew build, the tests run, but they don't use the "test" profile settings as defined in application-test.yml. 

### Expected behavior

I run ./gradlew build, the tests run and properly utilize my"test" profile settings as defined in application-test.yml. 

### Actual behavior

I run ./gradlew build, the tests run, but they don't use the "test" profile settings as defined in application-test.yml.

**Comment by bitsofinfo** [comment]
Even `./gradlew test` doesn't utilize my application-test.yml file

The only way I can get `./gradlew test` to use it is by defining

```
test {
    systemProperty "quarkus.test.profile", "test" 
}
```

**Comment by radcortez** [comment]
The profile property `quarkus.profile` or `quarkus.test.profile` cannot be set from within a profile aware file. We need the profile to be known to load the profile-aware files.

Also, a profile-aware file is only loaded if the unprofiled `application.properties` (or equivalent) is also available in the same location and the file extension matches between the files. This is required to keep a consistent loading order and pair all the
resources together.

I've updated the docs to clarify this part.
