### ISSUE TITLE
`quarkus.oidc-token-propagation-reactive.enabled-during-authentication` does not work correctly in the code flow

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#38431]
### Describe the bug

As reported by the user, if this property is used with the code flow, then given that both ID token and access token are `TokenCredential` instances, ID token is propagated, probably due to a random selection.

This is not a problem in the code flow when the token propagation is initiated  with the REST Client in the endpoint - indeed we have many tests and demos confirming it - it works because `AccessTokenCredential` CDI producer has a higher priority than `IdTokenCredential`  - looks like this priority is not enforced with the `quarkus.oidc-token-propagation-reactive.enabled-during-authentication` solution, #34933

**Comment by abhishekS14** [comment]
Hi @sberyozkin, I am interested in working on this. But I have a few doubts regarding the issue. 

> It works when using a REST client - does this imply that it has been handled in case of REST calls, but while calling the java API it has to be checked? 
> If that is the case, the REST calls may have been intercepted and handled on the filter level, also I can see that in the `OidcTokenCredentialProducer ` class, priority has been set. Could you let me know if I'm heading in the right direction here?

**Comment by sberyozkin** [comment]
@abhishekS14 Hi, thanks, lets wait till @michalvavrik, the author of the solution, is back in a week or so (Michal, do take your time please). In meantime, you are welcome to investigate if you'd like, thanks

**Comment by sberyozkin** [comment]
@michalvavrik I'll tweak a bit how the token is set on the duplicated context, setting it as TokenCredential does not work, I'll probably need to use a string property

CC @abhishekS14

**Comment by sberyozkin** [comment]
@abhishekS14 FYI, the PR is here #38442. We'll be happy to see you contributing, if you'd like, add a test to the PR, similarly to how Michal did in in the original PR but using OIDC `web-app`, but it has to be done quite fast for the fix to make it to the next maintenance release - I'll look at it probably on Tue if you won't have time to open a PR before that. Or please pick up other OIDC security issue if it is what you are interested in, thanks

**Comment by nelsongraca** [comment]
Tested the fix in my environment, seems to be ok.

**Comment by sberyozkin** [comment]
@nelsongraca Sounds good, thanks, I've just added a test
@abhishekS14 Np at all, I thought it would be tricky to add this test for new contributors so I decided to add it today

Look forward to your contributions, thanks
