### ISSUE TITLE
Reloading page in some guides leads to the list of configuration properties being hidden

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#38443]
### Describe the bug

In some guides, pressing CTRL+R (on Firefox) to reload the page leads to configuration properties no longer appearing in the page.

### How to Reproduce?

Go to https://quarkus.io/guides/hibernate-search-orm-elasticsearch#configuration-reference-coordination-outbox-polling
See how the list of properties is there
Reload the page (CTRL+R on Firefox)
See how the list of properties is now empty (though subsections are still there)

### Additional information

This might be related to the Javascript that hides content when we type text in the search box? I didn't use it, but maybe there's some misconfigured Javascript event handler in there...

Also, this page has configuration properties from two distinct extensions, so this might be related.

**Comment by geoand** [comment]
I could not reproduce this. Can you @yrodiere ?

**Comment by yrodiere** [comment]
Nope, can't reproduce anymore. Thanks to whoever fixed this :)

Reload doesn't work correctly if you have something in the search field, but... I suppose that's a different problem, and much less important.

Closing.

**Comment by geoand** [comment]
👌🏼
