### ISSUE TITLE
Remove workaround for HHH-17683 in Panache

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#38451]
### Description

In https://github.com/quarkusio/quarkus/pull/38427 we had to workaround a bug in Hibernate ORM: https://hibernate.atlassian.net/browse/HHH-17683 
See also https://github.com/quarkusio/quarkus/issues/38378#issuecomment-1911702314 for more details.

When HHH-17683 gets fixed, we'll need to remove the workaround.

Simply upgrading to a version of Hibernate ORM that fixes the problem, then reverting commit e745fe32569010f7a0a5e1eedf0b4dcdffa881e6 should do the trick.

**Comment by FroMage** [comment]
I have a fix for that in https://github.com/hibernate/hibernate-orm/pull/7599 to make the metamodel generator treat Panache entities differently. But I'm stuck on how to write tests for Gradle.

**Comment by FroMage** [comment]
I wanted to add the same comment on the JIRA issue but I can't seem to get permission to add a comment :(

**Comment by yrodiere** [comment]
> I wanted to add the same comment on the JIRA issue but I can't seem to get permission to add a comment :(

I added a comment on the Jira issue. I'd suggest you talk to Sanne or Steve (our Jira admins) to get your permission problem sorted out.

**Comment by yrodiere** [comment]
Also, thanks for the fix! Though I hope it's not specific to Panache, since according to my reproducer, it could hit basically any app.

**Comment by FroMage** [comment]
Well, it could indeed hit apps where they have a session getter in a superclass. But I think my fix is specific to Panache, since most entities don't have such a getter.
