### ISSUE TITLE
Add Slack to the list of supported OIDC providers 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#38462]
### Description

Slack offers a good OIDC integration and it is a popular platform

**Comment by patrox** [comment]
Hey @sberyozkin, if this task is free I would like to do it, as I'm also a Slack user.
I suppose the change would be similar to what you did in the past in the scope of: https://github.com/quarkusio/quarkus/issues/37839 ?

**Comment by sberyozkin** [comment]
Hi @patrox Apologies for missing your comment. I've been thinking, it is time to look at it and noticed your comment.

Sure, if you are still interested, please go ahead. It should be similar to the LinkedIn I guess, since it looks like it provided a good OIDC support. 

Thanks

**Comment by patrox** [comment]
No problem @sberyozkin, I've started to look at this issue and wrote some code to support this type of integration. 

Now when I have your blessing, I'll try to wrap it up.

**Comment by sberyozkin** [comment]
Great, thanks @patrox

**Comment by sberyozkin** [comment]
Hey @patrox, are you still planning to go ahead with the PR ? I hope so :-)

**Comment by michalvavrik** [comment]
I am working on this. Docs is very nice but when granting rights to my Slack app then Slack app keeps redirecting me to legacy `/oauth/v2/authorize` so I'm not quite sure if I'll be able to finish this. I'll try tomorrow again.
