### ISSUE TITLE
No proper failure message when ConfigMap is not found

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#38481]
### Describe the bug

I have an application, which works on openshift and uses configmaps.
I use apps logs to verify, if it started successfully and check for failures, eg if there is no configmap.

For older versions (up to 3.6.8), I could check for "ERROR: Failed to start application (with profile [prod])" in logs to verify, that the app indeed failed to start. But for newer SNAPSHOT versions, there is no such message in the logs.

Is this expected?

### Expected behavior

logs look like this:

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
INFO running in /deployments
<omitted for brevity>
Jan 30, 2024 3:29:57 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
<stacktrace>
```

### Actual behavior

```
INFO exec -a "java" java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
INFO running in /deployments
Jan 30, 2024 3:44:28 PM io.quarkus.config
WARN: Unrecognized configuration key "quarkus.smallrye-openapi.management.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
ConfigMap 'absent-config-map' not found in namespace 'fd-test'
java.lang.RuntimeException: Failed to start quarkus
<stacktrace>
```

### How to Reproduce?

1. ` git clone git@github.com:fedinskiy/reproducer.git -b openshift-no-error`
2.  `cd reproducer`
3.  `oc new-project my-project`
4. `mvn -Popenshift package -Dquarkus.container-image.group=my-project`
5.  `oc get pods` + `oc logs pod/name`

### Output of `uname -a` or `ver`

4.18.0-513.9.1.el8_9.x86_64

### Output of `java -version`

11.0.21, vendor: Red Hat, Inc.

### Quarkus version or git rev

36b6a6735a398907329db8ea8995d9612320ead4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
> git clone git@github.com:fedinskiy/reproducer.git -b openshift-no-error

The branch does not seem to exist

**Comment by fedinskiy** [comment]
@geoand sorry, you can check it now

**Comment by geoand** [comment]
The stacktrace is however the same in both cases, correct?

**Comment by fedinskiy** [comment]
I can not recheck it right now (so I am not sure of line-to-line comparisons), but both had the same underlying errors

**Comment by geoand** [comment]
Then this works as expected

**Comment by fedinskiy** [comment]
@geoand could you elaborate, please? What changed in Quarkus and why this error is not throw anymore for ConfigMaps? I can see, that it is still in the code: https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L198
