### ISSUE TITLE
Alpn property not work in rest client reactive

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#38499]
### Describe the bug

When setting the `quarkus.rest-client.alpn=true`, the http/1.1 is used and not http2.  By https://quarkus.io/guides/rest-client-reactive#http2-support I would expect it work same/similar if the server have enabled http2.

This happen also when the single rest client is used (`quarkus.rest-client.config-key.alpn=true`,)

### Expected behavior

I would expect when using `RestClientBuilder` that the default http will be http/2. The result should be same as when using `quarkus.rest-client.http2=true`.

### Actual behavior

When `RestClientBuilder` use alpn it using http/1.1 not http/2

### How to Reproduce?

1. `git clone -b alpn-client git@github.com:jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `mvn clean verify  -Dquarkus.platform.version=3.7.0.CR1`

or

3. `mvn quarkus:dev -Dquarkus.platform.version=3.7.0.CR1`
4. `Go to http://127.0.0.1:8080/test-https`

You can see which http version is used. Client is created when the endpoint is called (see method GreetingResource#httpsClient or GreetingResource#httpClient ). 

### Output of `uname -a` or `ver`

Linux fedowa 6.6.11-200.fc39.x86_64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### Quarkus version or git rev

3.7.0.CR1, probably others

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

Alternatively when the `QuarkusRestClientBuilder` is used and the options are set to use alpn the http/2 is used (see GreetingResource#quarkusHttpsClient). 

By [this code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/ClientBuilderImpl.java#L213) I would expect that it will behave same as http2.

Maybe this is partially vertex fault as `new HttpClientOptions().setUseAlpn(true).setAlpnVersions(Arrays.asList(HttpVersion.HTTP_2, HttpVersion.HTTP_1_1));`
not use h2c but use http/1.1 (maybe in this I missing something but it's not scope of this issue)

**Comment by jedla97** [comment]
@geoand thanks for quick fix! I can confirm it's work.

Maybe it would be nice to add note that `quarkus.rest-client.alpn=true` not choose `http/2` when using plain http (I can create that note to docs) or it can be bug in vert.x so it would be better to create issue there?

**Comment by geoand** [comment]
> Maybe it would be nice to add note that quarkus.rest-client.alpn=true not choose http/2 when using plain http (I can create that note to docs) or it can be bug in vert.x so it would be better to create issue there?

That's for @cescoffier to answer

**Comment by cescoffier** [comment]
In "Maybe this is partially vertex fault as new HttpClientOptions().setUseAlpn(true).setAlpnVersions(Arrays.asList(HttpVersion.HTTP_2, HttpVersion.HTTP_1_1));
not use h2c but use http/1.1 (maybe in this I missing something but it's not scope of this issue)"

Do you set the http version? I'm also surprised it uses http 1.1 and not 2

**Comment by jedla97** [comment]
I set `quarkus.http.http2=true` and `quarkus.rest-client.alpn=true` and by my understanding it should establish h2c with [this example](https://github.com/jedla97/quarkus-reproducers/blob/alpn-client/src/main/java/org/acme/GreetingResource.java#L25) 

When setting HttpClientOptions the example is [here](https://github.com/jedla97/quarkus-reproducers/blob/alpn-client/src/main/java/org/acme/GreetingResource.java#L57) which have alpn enable and http version as list. If I set `etProtocolVersion` to specific version so it's no need for alpn

**Comment by cescoffier** [comment]
quarkus.http.http2 is server side. You need `quarkus.rest-client.http2=true`
