### ISSUE TITLE
3.6.8 is not marked as default in SDKMAN repository

### ISSUE THREAD

**Issue by vanuatoo** [quarkusio/quarkus#38493]
### Describe the bug

please see the details here
https://github.com/sdkman/sdkman-cli/issues/1275

**Comment by gsmet** [comment]
Ah and maybe not... Default might be 3.6.9 right now as I had issues releasing 3.6.9 and it ended up being released after 3.7.1 in the end without it being declared a minor release.

I just fixed it using the SDKMan! API so we should be all good now.
