### ISSUE TITLE
Improvements for 404

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3851]
I got confused as I tried to reach a html page and got a Resource Not found page which showed me REST endpoint options
took me a while to figure that out. Here is what I propose to improve it:

- ~clearly show 404 in the page~ (done here: https://github.com/quarkusio/quarkus/pull/3854)
- ideally display the list of static resources if we know them
- ~give an intro before the list of rest endpoints "If you're looking for your REST resources, here are the ones we discovered:" soemthing like that~ (done here: https://github.com/quarkusio/quarkus/pull/3854)

**Comment by gsmet** [comment]
> clearly show 404 in the page

I have a PR in the works for that

> ideally display the list of static resources if we know them

not sure it's a good idea, it will be very verbose

> give an intro before the list of rest endpoints

PR coming too

**Comment by emmanuelbernard** [comment]
you can start lsiting static resources and stop at 1000 with a ...

**Comment by emmanuelbernard** [comment]
below the rest endpoints

**Comment by Dufgui** [comment]
I start a PR on it. It's works. I must add the limit of number of files displayed

**Comment by ivanjunckes** [comment]
Heys guys I am getting "Resource not found" and the page exists... it is an UI route from angular.

Any idea why every UI I try to call it gives this error.
