### ISSUE TITLE
Split package usage found in 'smallrye-reactive-messaging-api' and 'smallrye-reactive-messaging-health'

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#38518]
### Describe the bug

Since Quarkus 3.7.1 we receive the following warning:

```bash
Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.smallrye.reactive.messaging.health" found in [io.smallrye.reactive:smallrye-reactive-messaging-api::jar, io.smallrye.reactive:smallrye-reactive-messaging-health::jar]
```

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by ozangunalp** [comment]
This is an upstream issue in smallrye reactive messaging.

**Comment by gsmet** [comment]
@ozangunalp I let you document it there? I will close the Quarkus issue.
