### ISSUE TITLE
[Extension Proposal] Rockstar language support

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#38530]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

This extension allows people to run their [Rockstar](https://codewithrockstar.com/) programs with Quarkus. Although I don't expect that this will be something many people need in production, it is useful as an demonstration/example of how to implement extensions.

The code is currently living at https://github.com/holly-cummins/bon-jova-rockstar-implementation/, but Quarkiverse hosting would be beneficial. 

### Repository name

quarkus-bon-jova-rockstar

### Short description

An implementation of Rockstar as a JVM language 

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/quarkus-bon-jova-rockstar/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- @holly-cummins 
[- @hannotify](https://github.com/hannotify)

### Additional context

See also https://hollycummins.com/rockstar-jfokus/

Since this is an [existing repo](https://github.com/holly-cummins/bon-jova-rockstar-implementation) that I'm hoping we can bring over, that might affect the creation process?

**Comment by maxandersen** [comment]
just make sure to mark it as experimental in its status :)

**Comment by aloubyansky** [comment]
Why? :) as long as it does whatever is it is supposed to do it can be stable.

**Comment by holly-cummins** [comment]
> just make sure to mark it as experimental in its status :)

Done -> https://github.com/holly-cummins/bon-jova-rockstar-implementation/pull/102

As it happens, I can please both @aloubyansky and @maxandersen on this one, because the code has ... um .. a few bugs and gaps. It turns out writing a whole language implementation is hard! So experimental status fits perfectly. :)

**Comment by aloubyansky** [comment]
Looks like the best project ever. Even bugs and gaps appear to please everyone.

**Comment by gastaldi** [comment]
There you go: https://github.com/quarkiverse/quarkus-bon-jova-rockstar

Enjoy!
