### ISSUE TITLE
Overwriting application configuration does not work with .env File

### ISSUE THREAD

**Issue by Jeansen** [quarkusio/quarkus#38557]
### Describe the bug

If I would like to overwrite or set application configuration value - e.g. user/password - with the help of environment variables, then it succeeds with environment variables set directly, but not in a .env file present in the root of my project.

In the latter case - with the same variable - I get something like: Unrecognized configuration key "quarkus.container.image.group" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

### Expected behavior

Values set through environment variables should work with .env File and when manually exporting them.

### Actual behavior

Manually set environment variables work. Environment variables set in .env files do not. In my case, I get:
```
Unrecognized configuration key "quarkus.container.image.group" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.registry" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.password" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.username" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> Task :quarkusAppPartsBuild FAILED
```

My .env File looks like this (I only replaced the values with some dummy content):

```
QUARKUS_CONTAINER_IMAGE_GROUP=quarkus
QUARKUS_CONTAINER_IMAGE_PASSWORD=a
QUARKUS_CONTAINER_IMAGE_REGISTRY=b
QUARKUS_CONTAINER_IMAGE_USERNAME=c
```

### How to Reproduce?

- Clone https://github.com/Jeansen/cert-operator
- create an .env File in the root folder with e.g. the following content:
```
QUARKUS_CONTAINER_IMAGE_GROUP=quarkus
QUARKUS_CONTAINER_IMAGE_PASSWORD=a
QUARKUS_CONTAINER_IMAGE_REGISTRY=b
QUARKUS_CONTAINER_IMAGE_USERNAME=c
```
- Build the project with: gradle build

You should get something like this:

```
Unrecognized configuration key "quarkus.container.image.group" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.registry" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.password" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Unrecognized configuration key "quarkus.container.image.username" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
> Task :quarkusAppPartsBuild FAILED
```

- Remove the .env file or empty it and set these variables manually in a terminal, e.g:

```
export QUARKUS_CONTAINER_IMAGE_GROUP=quarkus
export QUARKUS_CONTAINER_IMAGE_PASSWORD=a
export QUARKUS_CONTAINER_IMAGE_REGISTRY=b
export QUARKUS_CONTAINER_IMAGE_USERNAME=c
```

If using IntelliJ, you can also set them in the run configuration.

- Build again with: gradle build.
- Now, there should be now warnings! In my specific case it builds ans pushes the image to my local registry.

### Output of `uname -a` or `ver`

Linux omph-laptop 6.6.13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1 (2024-01-20) x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.5

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
It seems the issue is related to the Gradle plugin. This works as expected with Maven.

**Comment by Jeansen** [comment]
Oh great! Kudos to @radcortez and everyone else involved!
