### ISSUE TITLE
RESTEasy extension should throw a build error if consuming or producing JSON without any JSON body writer/reader

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3856]
This is an idea of @emmanuelbernard and it looks interesting from a user experience perspective.

**Comment by sberyozkin** [comment]
@gsmet, hi, as long as JSON is not consumed as String or InputStream directly in the user code, it should indeed help the users.

**Comment by uaihebert** [comment]
I was checking this ticket and I came across this piece of code:
ResteasyCommonProcessor:152

```
        if (!capabilities.isCapabilityPresent(Capabilities.RESTEASY_JSON_EXTENSION)) {

            boolean needJsonSupport = restJsonSupportNeeded(indexBuildItem, ResteasyDotNames.CONSUMES)
                    || restJsonSupportNeeded(indexBuildItem, ResteasyDotNames.PRODUCES);
            if (needJsonSupport) {
                LOGGER.warn(
                        "Quarkus detected the need of REST JSON support but you have not provided the necessary JSON " +
                                "extension for this. You can visit https://quarkus.io/guides/rest-json for more " +
                                "information on how to set one.");
            }
        }
```

I think this piece of code already does what is required. Or did I misunderstood this?

**Comment by rsvoboda** [comment]
I tried rest-json-quickstart and applied following diff:
```diff
-      <artifactId>quarkus-resteasy-jsonb</artifactId>
+      <artifactId>quarkus-resteasy</artifactId>
```

When running `mvn clean package` I can see

2020-01-26 15:05:07,014 WARN  [io.qua.res.com.dep.ResteasyCommonProcessor] (build-6) Quarkus detected the need of REST JSON support but you have not provided the necessary JSON extension for this. You can visit https://quarkus.io/guides/rest-json for more information on how to set one.

The same message appears in dev mode when I omit `-jsonb` from the artifactId.

**Comment by rsvoboda** [comment]
Closing. If this is not sufficient please reopen.
