### ISSUE TITLE
Add a dead simple way to do basic auth in REST Client

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#38565]
### Description

Basic Auth is more complicated than it has too be, let's change that

**Comment by FroMage** [comment]
How complicated does it look ATM?

**Comment by Serkan80** [comment]
May I make a recommendation? :)

`
@ClientBasicAuth(username=“${username}”, password=“${password}”)
`

or

`
@ClientHeaderParam(name=“Authorization”, value=“${username:password}”, isBasicAuth=true)
`
