### ISSUE TITLE
Maven wrapper breaks when updating Quarkus

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#38569]
### Describe the bug

Not sure if it's a Quarkus or a Maven bug

By using `./mvnw io.quarkus.platform:quarkus-maven-plugin:3.7.1:update -N` on Windows, it fails with the following log:

```log
[INFO] Executing:
C:\Users\<user>\Documents\<path-to-project>\mvnw.cmd -B clean process-sources
[INFO]
[INFO] Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised.
[INFO] Investigate or delete C:\Users\<user>\Documents\<path-to-project>\.mvn\wrapper\maven-wrapper.jar to attempt a clean download.
[INFO] If you updated your Maven version, you need to update the specified wrapperSha256Sum property.
[ERROR] Get-FileHash : The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable 
[ERROR] program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[ERROR] At line:1 char:13
[ERROR] + &{ $hash = (Get-FileHash "C:\Users\<user>\Documents\<fragment-path-to-project>\ ...
[ERROR] +             ~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], CommandNotFoundException
[ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
[ERROR]
```

the `maven-wrapper.properties` file get's updated:

Before: 
```sh
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar
```

After:
```sh
distributionUrl=https\://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.zip
wrapperUrl=https\://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar
distributionSha256Sum=83aaf914c785c9faed661f223000a92d1de9553f5c82d3b4362e66d9c031625f
wrapperSha256Sum=e63a53cfb9c4d291ebe3c2b0edacb7622bbc480326beaa5a0456e412f52f066a
```

After that, any call to `./mvnw` fails
As a workaround, by removing the new 2 lines, it start working again (distributionSha256Sum and wrapperSha256Sum).

### Expected behavior

Quarkus update should complete successfully

### Actual behavior

Quarkus update fails, and Maven wrapper get's broken

### How to Reproduce?

1. Update Quarkus from `3.6.6` to `3.7.1` with `./mvnw io.quarkus.platform:quarkus-maven-plugin:3.7.1:update -N` command

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.8.1+1

### Quarkus version or git rev

3.7.1

### Additional information

POM.xml

Before:
```xml
<compiler-plugin.version>3.11.0</compiler-plugin.version>
<quarkus.platform.version>3.6.6</quarkus.platform.version>
<surefire-plugin.version>3.1.2</surefire-plugin.version>
```

After:
```xml
<compiler-plugin.version>3.12.1</compiler-plugin.version>
<quarkus.platform.version>3.7.1</quarkus.platform.version>
<surefire-plugin.version>3.2.3</surefire-plugin.version>
```

**Comment by gian1200** [comment]
Not sure if this should be associated to this or a separate issue.
- It seems that the updater doesn't remove the old maven-wrapper.jar
- When manually removing it, it fails because it doesn't like the new `\:` escaping. This escaping broke the compiling execution on Windows and on our Linux (ghcr.io/graalvm/graalvm-ce:ol8-java17-22) pipeline with the following error:

```
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

**Comment by gian1200** [comment]
Since `maven-wrapper.jar` is not versioned, it's a little bit hard to provide the exact pre-update of `.mvn` folder. And since the recipe was updated/disabled, I'm unable to replicate it.

However, I can provide 2 folders from other projects that I haven't updated, yet. Also, did my best effort to undo all my local fixes to the post-update one

Pre-update:
Quarkus 2.16.12.Final: [.mvn-3.8.8.zip](https://github.com/quarkusio/quarkus/files/14181105/default.mvn-3.8.8.zip)
Quarkus 3.6.8: [.mvn-3.9.5.zip](https://github.com/quarkusio/quarkus/files/14181120/default.mvn-3.9.5.zip)

Post-update:
Quarkus 3.7..1: [.mvn-3.9.6.zip](https://github.com/quarkusio/quarkus/files/14181309/default.mvn-3.9.6.zip)

**Comment by gsmet** [comment]
Cool, thanks for your efforts, I will try to have a look soon.

**Comment by gsmet** [comment]
I had a look and the interesting thing is the following output you had at the very beginning:

```
[ERROR] Get-FileHash : The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable 
[ERROR] program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[ERROR] At line:1 char:13
[ERROR] + &{ $hash = (Get-FileHash "C:\Users\<user>\Documents\<fragment-path-to-project>\ ...
[ERROR] +             ~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], CommandNotFoundException
[ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
```

The problem is that somehow `Get-FileHash` used in `mvnw.cmd` is not recognized by your Powershell version.
Are you using an old Windows version?

@jorsol does it ring a bell?

You didn't have the problem before because you didn't have the checksums in your property files so they weren't checked.

Everything else is not a problem:
- the encoding for properties is not an issue
- it's normal, your `maven-wrapper.jar` was not updated as it was already 3.2.0, which is the latest (the versioning is different from the Maven versioning)

**Comment by jorsol** [comment]
> 
> @jorsol does it ring a bell?
> 
Yes: https://issues.apache.org/jira/browse/MWRAPPER-103

The hash validation on Windows depends on PowerShell, the issue is that there are many versions of PowerShell (eg. PowerShell vs PowerShell Core) that might not be compatible between them, I don't know which version was used to develop that feature, nor have access to a Windows machine, so I can't help with that, but my current recommendation is to remove `wrapperSha256Sum` from the property file (if _Windows_ is used 😕). The `distributionSha256Sum` hash validation is done on Java so it will work just fine.

This is added by openrewrite recipe (https://docs.openrewrite.org/recipes/maven/updatemavenwrapper) but it seems there is no option to disable the hash being added to the property file.

**Comment by gian1200** [comment]
Hi, it's the last Powershell version (PowerShell 7.4.1)

By running `Get-FileHash` manually, it finds it; so as you mentioned, its probably how it's being called inside `mvnw.cmd`.
```
PS C:\Users\<user>> Get-FileHash

cmdlet Get-FileHash at command pipeline position 1
Supply values for the following parameters:
Path[0]:
```

**Comment by gsmet** [comment]
@gian1200 if you can experiment with the `mvnw.cmd` script and see if you can make it work, that would be awesome.

**Comment by gsmet** [comment]
Ah I saw there was a workaround proposed in the Maven Wrapper issue but it's probably a bit brittle.

**Comment by gsmet** [comment]
@jorsol maybe the wrapper check should be dropped on Windows given it's unreliable? Because removing it from the property file makes it unsafe for everyone (and you usually expect the wrapper to be portable).

Or maybe it could print a small warning instead, saying that `Get-File-Hash` is not available and that the checksum hasn't been checked?

/cc @timtebeek you might find this discussion useful.

**Comment by gian1200** [comment]
~They mentioned this workaround. Will give a try https://github.com/PowerShell/PowerShell/issues/18108#issuecomment-1545956950~ Yes

> the encoding for properties is not an  issue

Did you refer to the escaping? `\:` I had to remove it to make the download work. I got an error with the `\`.

**Comment by gian1200** [comment]
2 things:
First was the 2 lines issue, which workaround is to remove the 2 lines.

For the sake of testing I tried removing the jar that was already downloaded (to download it again). When I did that, there was an issue downloading it. The workaround was to remove the escaping. This download issue happened on my windows local and on the Linux pipeline.

**Comment by timtebeek** [comment]
Hi! Chiming in from OpenRewrite here; the UpdateMavenWrapper recipe should maybe not add this property on Windows is what I'm getting from this thread. [The logic to add the property is here](https://github.com/openrewrite/rewrite/blob/cce995320d5fcd5c33ea6000fc18a5fb3d98fece/rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java#L447-L454). Perhaps we can look at the `OperatingSystemProvenance` marker to exclude Windows, as indeed there's perhaps too much variability in Windows systems to be able to use that property reliably, so then best not to add it explicitly there.

**Comment by gian1200** [comment]
Sounds a reasonable workaround. If I understand correctly, the only scenario where this might still not get fixed is the following one, correct?

1 Project created/updated on non-Windows machine
2. Versioned on git
3. Git-pulled on a Windows Machine
4. Wrapper will fail because `maven-wrapper.properties` will have the hash lines, correct?

**Comment by timtebeek** [comment]
Yes that sounds correct to me; so any mixed-OS team will have to battle it out on whether to have that wrapper checksum property, or ensure their Windows colleagues use a shell that supports hashing.

**Comment by gsmet** [comment]
I think it’s probably safer to remove the property until there is a workaround/fix.

Being portable is one of the reason why the Maven wrapper is used.

**Comment by gsmet** [comment]
I posted my WIP here: https://github.com/openrewrite/rewrite/pull/3989

**Comment by gsmet** [comment]
This has been solved.
