### ISSUE TITLE
QuarkusTest runs before Quarkus starts

### ISSUE THREAD

**Issue by damian-burda** [quarkusio/quarkus#38571]
### Describe the bug

From time to time our application's builds on GitHub fail for unknown reason. After investigating and adding quarkus.debug properties I was able confirm, that test starts before all startup tasks are executed:

```posh
2024-01-31T06:44:19.1042853Z 2024-01-31 06:44:19,023 Build step VertxBinderProcessor.setVertxConfig completed in: 0ms
2024-01-31T06:44:19.1043845Z 2024-01-31 06:44:19,028 Build step SmallRyeHealthProcessor.processSmallRyeHealthRuntimeConfig completed in: 4ms
2024-01-31T06:44:19.1044869Z 2024-01-31 06:44:19,028 Build step NarayanaJtaProcessor.startRecoveryService completed in: 0ms
2024-01-31T06:44:19.1045768Z 2024-01-31 06:44:19,029 Build step ConfigBuildStep.registerConfigClasses completed in: 0ms
2024-01-31T06:44:20.4565746Z [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 29.03 s <<< FAILURE! -- in org.acme.XYZTest
2024-01-31T06:44:20.4567511Z [ERROR] org.acme.XYZTest.testMethod -- Time elapsed: 0.013 s <<< ERROR!
2024-01-31T06:44:20.4569988Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2024-01-31T06:44:20.4571167Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
2024-01-31T06:44:20.4572491Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
2024-01-31T06:44:20.4573552Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
2024-01-31T06:44:20.4574322Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-31T06:44:20.4575216Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-31T06:44:20.4576342Z Caused by: java.lang.RuntimeException: Failed to start quarkus
```

and the ApplicationImpl looks like this:

```java
...
((StartupTask)(newVertxBinderProcessor.setVertxConfig325991315())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newSmallRyeHealthProcessor.processSmallRyeHealthRuntimeConfig1687788508())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newNarayanaJtaProcessor.startRecoveryService1748449850())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newConfigBuildStep.registerConfigClasses1377682816())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newMicrometerProcessor.configureRegistry477897979())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newFlywayProcessor.startActions2099152139())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newInitializationTaskProcessor.startApplicationInitializer180820092())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newConfigBuildStep.validateConfigValues1665125174())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newResteasyStandaloneBuildStep.boot1529468817())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newSmallRyeOpenApiProcessor.handler804903610())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newHibernateOrmProcessor.startPersistenceUnits1868654632())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newWebJarProcessor.processWebJarDevMode1534459532())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newSmallRyeHealthProcessor.registerHealthUiHandler1098457609())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newSwaggerUiProcessor.registerSwaggerUiHandler1166208104())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newVertxHttpProcessor.initializeRouter938601780())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newVertxHttpProcessor.finalizeRouter2040953008())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newLifecycleEventsBuildStep.startupEvent1144526294())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newVertxHttpProcessor.openSocket189362710())).deploy(var2);
StepTiming.printStepTime(var2);
((StartupTask)(newShutdownListenerBuildStep.setupShutdown1209845420())).deploy(var2);
StepTiming.printStepTime(var2);
ExecutionModeManager.running();
...
```

The test fails since hibernate schema validation fails as flyway migration was not run yet.

### Expected behavior

Startup tasks are run before unit tests are run.

### Actual behavior

Unit tests are run before startup tasks finish and Quarkus app is started.

### Output of `java -version`

17

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.6

**Comment by mkouba** [comment]
I think that we will need more information. Ideally, a small reproducer app/project that would demonstrate the problem. I know that this could be tricky so I would start with an empty project using the same quarkus version, then add all extensions from the problematic project and finally add some minimal code and try to reproduce the issue.

**Comment by damian-burda** [comment]
Hi @mkouba . I was thinking about some way to reproduce it. We have like 30+ repos and probably hundreds of build weekly and one or two fail this way. It can be that there is something wrong with configuration in our runners. Do you maybe know if there is a way to see if the Quarkus gets killed during start and for what reason? If it gets killed for some reason it would be easier to create a reproducer. Does Quarkus log something or leaves a message when it is killed for some reason. We have a really simple setup with not too many extensions. Nothing special. This also started happening after a long time of using Quarkus and this build setup. This makes me thinking what could be wrong, but I have no clue and where to investigate further. Any ideas?

**Comment by damian-burda** [comment]
I checked the log again. Maybe it really was not killed, as I can see that our own ConfigSourceProvider logged again that it was called. This was but logged between mockito unit tests running, for no reason. This is also strange, because in a positive run, this log is not there. Our ConfigSourceProvider is called only once it the test phase. Something strange happened, that forced it to be called again.

**Comment by mkouba** [comment]
> I checked the log again. Maybe it really was not killed, as I can see that our own ConfigSourceProvider logged again that it was called. This was but logged between mockito unit tests running, for no reason. This is also strange, because in a positive run, this log is not there. Our ConfigSourceProvider is called only once it the test phase. Something strange happened, that forced it to be called again.

Is your `ConfigSourceProvider` annotated with `@io.quarkus.runtime.annotations.StaticInitSafe`? If so then I think that it's excepted - see [the docs](https://quarkus.io/guides/config-extending-support#configsource-init).

**Comment by damian-burda** [comment]
> > I checked the log again. Maybe it really was not killed, as I can see that our own ConfigSourceProvider logged again that it was called. This was but logged between mockito unit tests running, for no reason. This is also strange, because in a positive run, this log is not there. Our ConfigSourceProvider is called only once it the test phase. Something strange happened, that forced it to be called again.
> 
> Is your `ConfigSourceProvider` annotated with `@io.quarkus.runtime.annotations.StaticInitSafe`? If so then I think that it's excepted - see [the docs](https://quarkus.io/guides/config-extending-support#configsource-init).

The documentation only mentions `ConfigSource` and not `ConfigSourceProvider` but I can try this out.

**Comment by mkouba** [comment]
> > > I checked the log again. Maybe it really was not killed, as I can see that our own ConfigSourceProvider logged again that it was called. This was but logged between mockito unit tests running, for no reason. This is also strange, because in a positive run, this log is not there. Our ConfigSourceProvider is called only once it the test phase. Something strange happened, that forced it to be called again.
> > 
> > 
> > Is your `ConfigSourceProvider` annotated with `@io.quarkus.runtime.annotations.StaticInitSafe`? If so then I think that it's excepted - see [the docs](https://quarkus.io/guides/config-extending-support#configsource-init).
> 
> The documentation only mentions `ConfigSource` and not `ConfigSourceProvider` but I can try this out.

No, I mean if it's not annotated with `@StaticInitSafe` then it should not be used during the `STATIC_INIT` bootstrap phase.

**Comment by geoand** [comment]
Closing for a lack of a reproducer.
If one becomes available, we can certainly reopen
