### ISSUE TITLE
Ability to enable the C2 compiler in Dev mode

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#38575]
### Description

Currently, for faster startup times, the C2 compiler of the JVM is disabled with no option to enable it in Dev mode.
This is done by the following piece of code:
https://github.com/quarkusio/quarkus/blob/ddcb1448911c645952954197b14b8eccf204f093/core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java#L344-L348
Unfortunately, this make Dev mode unsuitable for testing changes related to performance; I observed performance numbers being at least five times slower when using `mvn quarkus:dev` compared with `mvn quarkus:run`.
By default, the C2 compiler should remain disabled since it can improve startup times, but it should have the option to be enabled so `quarkus:dev` can be used to test a wider variety of changes.
Additionally, the disabling of the C2 compiler should be mentioned in https://quarkus.io/guides/dev-mode-differences.

### Implementation ideas

Spring also by default disables the C2 compiler for `spring-boot:run`, but allows it to be enabled by setting `optimizedLaunch` to false:
```xml
<configuration>
  <optimizedLaunch>false</optimizedLaunch>
</configuration>
```
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#run.run-goal.parameter-details.optimized-launch
Ideally, an identical setting for the quarkus maven and gradle plugins would exist.

**Comment by geoand** [comment]
Quarkus dev-mode should **never** be used to test performance changes as there are too many things about that could affect performance.
The only valid target for performance testing against a Quarkus application is the production artifact (jar, native-binary, container)

**Comment by geoand** [comment]
> Additionally, the disabling of the C2 compiler should be mentioned in https://quarkus.io/guides/dev-mode-differences.

Good idea! [This](38635) takes care of it.
