### ISSUE TITLE
Openapi not working when quarkus.swagger-ui.path is "/"

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkus#3857]
**Describe the bug**
Hi, not sure if is a Quarkus or a MicroProfile issue, but when I have the config bellow in the application.properties, the OpenApi endpoint doesn't work. I've attached a PrintScreen and there isn't error in the logs

application.properties:
`
quarkus.swagger-ui.path=/
`

**Expected behaviour**
The OpenApi endpoint should work independently of quarkus.swagger-ui.path config

![Screenshot from 2019-09-04 15-05-11](https://user-images.githubusercontent.com/11513050/64264348-0bcb6a80-cf29-11e9-8d41-fd1f45b4b447.png)

**Comment by stuartwdouglas** [comment]
I don't think we should allow a path of / for swagger UI. Swagger takes complete control of quarkus.swagger-ui.path so if it is set of / then nothing else can be served.

**Comment by lbernardomaia** [comment]
Ok, closing the issue!

**Comment by machi1990** [comment]
> I don't think we should allow a path of / for swagger UI. Swagger takes complete control of quarkus.swagger-ui.path so if it is set of / then nothing else can be served.

Good candidate of https://github.com/quarkusio/quarkus/issues/2489.
