### ISSUE TITLE
Quarkus native building using third party library

### ISSUE THREAD

**Issue by AleDiggio** [quarkusio/quarkus#38585]
### Describe the bug

Hi everyone, 

I'm finding some issues trying to build a native executable using Quarkus native-image plugin on GRAALVM 23.0 JDK 17.
Shortly i'm implementing a jwt authentication in my Quarkus application using another alredy working library (also written by me) doing all the logic through io.jsonwebtoken dependecies (jjwt-impl, jjwt-api, jjwt-jackson). The native building process succeed without any errors or warning but when i run the executable it throws the exception: 

`2024-02-05 14:52:33,296 INFO  [it.pnt.net.qua.han.ExceptionHandler] (executor-thread-1) Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.  Have you remembered to include the jjwt-impl.jar in your runtime classpath`

### Expected behavior

Everything works fine as expected

### Actual behavior

Throwing of an exception

**Comment by galderz** [comment]
A reflection registration for `io.jsonwebtoken.impl.DefaultJwtBuilder` is probably missing, but there could be other issues. Unless Quarkus offers an extension to support io.jsonwebtoken JWT, I would look at [existing JWT support in Quarkus](https://quarkus.io/guides/security-jwt) and see if your use case can be achieved with that.

@sberyozkin Any further thoughts?

**Comment by AleDiggio** [comment]
@galderz I've tried to register that class for reflection using the proper annotation, but the problem is that the error persits with another missing class. It seems that it doesn't bring all the mandatory dependency.

My question is about using an existing library, i know that i can use the quarkus library but if i'm working on existing projects it means to rewrite tons of code. 

Let me know if you have any other ideas, thank you

**Comment by geoand** [comment]
@AleDiggio what you are experiencing is pretty standard when trying to get non-trivial libraries working on GraalVM that don't already contain a Quarkus extension or the necessary GraalVM metadata files

**Comment by PabloDelBarrioArnanz** [comment]
Hi! Maybe it's a bit late, but yes it's possible to make it work.

Apply this config
1) Set this like on application.properties file
quarkus.native.additional-build-args=--initialize-at-run-time=io.jsonwebtoken.impl.security.Randoms
2) Add this 2 files under /src/main/resources/META-INF/native-image/io/jsonwebtoken/jjwt-api
[reflect-config.json](https://github.com/user-attachments/files/17637858/reflect-config.json)
[resource-config.json](https://github.com/user-attachments/files/17637859/resource-config.json)
3) Add this dependencies
`
    implementation("io.jsonwebtoken:jjwt-api:${jsonWebToken}")
    implementation("io.jsonwebtoken:jjwt-impl:${jsonWebToken}")
    implementation("io.jsonwebtoken:jjwt-jackson:${jsonWebToken}") // This can be replaced by gson
`
4) On your parser specify the deserializer implementation like this
`
Jwts.parser()
         .json(JacksonDeserializer())
`
Let me know if works also for you :)
