### ISSUE TITLE
Queue creation using AWS SqsClient and localstack does not work for Quarkus 3.7.1

### ISSUE THREAD

**Issue by Tincoquesse** [quarkusio/quarkus#38584]
### Describe the bug

After upgrading our application to Quarkus 3.7.1 from version 3.5.3, we have observed a problem with queue creation using awssdk SqsClient for our tests that causes them to crash. We are using testContainers and localStack dependecies. 

![Screenshot 2024-02-05 at 15 43 09](https://github.com/quarkusio/quarkus/assets/28060759/a16e93c6-e6af-411b-af7d-544486ac1b70)

>Caused by: software.amazon.awssdk.services.sqs.model.SqsException: Service returned HTTP status code 500 (Service: Sqs, Status Code: 500, Request ID: null)

This seems to be related to a newer version ("software.amazon.awssdk:sqs"). Quarkus 3.5.3 uses v2.21.17 and this connection works stably. Quarkus 3.7.1 uses v2.23.0 and we assume that this change is the cause of the failure.

Downgrading the version of the client itself in quarkus-amazon-services-bom is a workaround that works but cannot be the ultimate solution. We assume that the problem occurs in conjunction with similar issues:
[https://stackoverflow.com/a/77476794](url)
[https://github.com/aws/aws-sdk-java-v2/issues/3972](url)

I add a small reproducer to illustrate the problem. 
On the **_main_** branch, the test fails when quarkus 3.7.1 is used. 
Branch _**downgraded-dependency**_ ->  the test succeed when quarkus 3.7.1 is used but, awssdk:sqs is overwriten to v2.21.17.
Branch  _**downgraded-quarkus**_  -> the test succeed when quarkus 3.5.3 is used.

Let us know if the solution to the problem lies with you, or if we will have to wait until the people responsible for lockalstack development adapt it to the newer aws sdk.

### How to Reproduce?

https://github.com/Tincoquesse/aws-sdk-sqs-localstack-reproducer

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.5

**Comment by geoand** [comment]
This should probably be reported to https://github.com/quarkiverse/quarkus-amazon-services
