### ISSUE TITLE
Config property expects to have hyphen before digit

### ISSUE THREAD

**Issue by mannukalra** [quarkusio/quarkus#38582]
### Describe the bug

While trying to update Quarkus from 3.2.9.Final to 3.6 onwards have come across following issue related to config-
Config property expects to have hyphen before digit, 
Example in config java file-

```
public interface ParenttConfig {
  interface Id {
          String id();
  }
  interface XChannels {
          Id acrossB2b();
  }
  ..........
}
```
config yaml-
```
parentt:
    x-channels:
        across-b2b:
            val: xxxxxx
```
 throws an exception on start-up
 ```
java.util.NoSuchElementException: SRCFG00014: The config property parentt.x-channels.across-b-2b.val is required but it could not be found in any config source
```

### Expected behavior

'acrossB2b' in java should be accepted as 'across-b2b' from yaml.

### Actual behavior

'acrossB2b' in java is expecting to have 'across-b-2b' from yaml.

### How to Reproduce?

Custom Yaml config file with a number in the key name, occurs on application start-up.

### Output of `java -version`

17.0.7

### Quarkus version or git rev

3.6.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

**Comment by geoand** [comment]
cc @radcortez

**Comment by mannukalra** [comment]
Thanks for the prompt actions, if possible please help with the expected release date for 3.7.2?

**Comment by radcortez** [comment]
We may still be a few days away.

To move forward, you can manually update the SmallRye Config version, which fixes the issue:

```xml
<dependency>
  <groupId>io.smallrye.config</groupId>
  <artifactId>smallrye-config-common</artifactId>
  <version>3.5.4</version>
</dependency>
<dependency>
  <groupId>io.smallrye.config</groupId>
  <artifactId>smallrye-config-core</artifactId>
  <version>3.5.4</version>
</dependency>
```

**Comment by gsmet** [comment]
3.7.2 will be released today if the release gods are with us.
