### ISSUE TITLE
Native testing expects the executable to be OS specific: docker build based executable fail

### ISSUE THREAD

**Issue by gnodet** [quarkusio/quarkus#3859]
On OSX for example, the native build default to using docker, which ends up building a linux-based native executable.  However, in the testing phase, docker isn't used so we end up with an error `Caused by: java.lang.RuntimeException: Unable to start native image in 60s`.

**Comment by machi1990** [comment]
@gnodet can you try to increase the timeout to two minutes or mote timeout with `-Dquarkus.test.native-image-wait-time=120` and see if the tests start successfully? By default it is 60s.

**Comment by gnodet** [comment]
The problem afaik is that the build produces a linux exectuable on OSX, but the tests don't use docker to start the executable. I think I can raise the timeout to whatever, it would still fail.

**Comment by gwenneg** [comment]
@gnodet Are you using Maven or Gradle?

**Comment by gnodet** [comment]
@gwenneg maven, is there anything to turn on ? I just tested without any additional change with a locally compiled version of the `0.21` branch, but the results are the same

**Comment by gnodet** [comment]
@gwenneg I think you did misunderstood my problem.
When defining the required properties to make the native build happen on docker using
```
        <native-image.docker-build>true</native-image.docker-build>
        <native-image.container-runtime>docker</native-image.container-runtime>
```
for example, the tests will always fail because the generated native executable is run on the host and not in the docker container.  In my case, host = OSX so the compiled executable can not be run at all.

**Comment by gwenneg** [comment]
Oh yes, I got your first message wrong, sorry. There must be something wrong in `NativeImagePhase`. I'll try to run a native build with Docker on a Mac tomorrow and see what happens.

**Comment by gnodet** [comment]
@gwenneg I don't think the `NativeImagePhase` has any problem, but it's more the testing framework which should leverage the same mechanism and also start the compiled native binary using docker if docker was used to build the image.

**Comment by emmanuelbernard** [comment]
Guillaume is right, we should look at the docker-build and container-runtime to make sure we run the native executable from the right OS. But then this raises the question of which port to open and which Docker image to use.

Essentially, we nee to ask the user to do the following steps or have convention over configuration to do the same

Have a dockerfile

```
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

esp the port number if it has changed


Build an image `docker build -f src/main/docker/Dockerfile.native -t quarkus-quickstart/getting-started .`

Run that image `docker run -i --rm -p 8080:8080 quarkus-quickstart/getting-started`

Start the tests

**Comment by geoand** [comment]
Could we perhaps leverage the container that created the native executable to also start the application and run the tests against it instead of needing a new docker image and container?

**Comment by emmanuelbernard** [comment]
you still need to define the right port openin

**Comment by geoand** [comment]
But for tests that is `8081` (configurable via a property of course). So couldn't we just use that? 
I think it would work, although I might be missing something

**Comment by wglanzer** [comment]
Is there any progress on this topic? I just ran into the same issue with 1.4.2.Final.

**Comment by geoand** [comment]
I am going to close this as `@QuarkusIntegrationTest` supersedes `@NativeImageTest` and can execute containers when a user requests container builds (for the native application or not).
