### ISSUE TITLE
Provides an opt-in for jaxb support in resteasy-server-common extension

### ISSUE THREAD

**Issue by gnodet** [quarkusio/quarkus#3860]
**Description**
The resteasy-server-common extension provides a `@BuildStep JaxbEnabledBuildItem` which forces the support and inclusion of jaxb.  However, JAXB is not mandatory and when compiling to native, it forces the whole jaxp+jaxb stack to be included while it may not be used.

**Implementation ideas**
Make the build item to be provided only when opting-in with a configuration property somehow.  Also, I'm not even sure where this is needed as the resteasy-jaxb-provider is not even in the dependency tree, so maybe remove the JaxbEnabledBuildItem completely.

**Comment by gnodet** [comment]
I can provide a patch once a direction is agreed.

**Comment by gnodet** [comment]
The whole point is that `resteasy-server-common` is used in almost all testing, and it raises the native compilation time by a huge factor (to a point it's nearly impossible to turn on native testing during a full build) while maybe only a few integration tests would actually use jaxb.

**Comment by gsmet** [comment]
Yes that’s something that’s on my (long) list for a while. I think we enable JAXB far too often. That’s definitely something we need to improve.

**Comment by gnodet** [comment]
@gsmet fwiw the build and tests works fine with the PR which removes the jaxb enabled build item

**Comment by gsmet** [comment]
OK, that's understandable.

**Comment by gsmet** [comment]
This has been fixed with the introduction of the `quarkus-resteasy-jaxb` extension.
