### ISSUE TITLE
QuarkusComponentTest: @TestConfigProperties not applicable to method (override multiple config properties)

### ISSUE THREAD

**Issue by wiebeck** [quarkusio/quarkus#38602]
### Description

I just stumbled upon the fantastic Quarkus component test feature. It just has one flaw: While it's totally fine to set multiple config properties via `@TestConfigProperty` on the test class itself the same is not possible on test methods:

![image](https://github.com/quarkusio/quarkus/assets/61313842/b2ba9b58-3cf6-4d16-9e36-5adc9ac2d8d9)

Unfortunately I like to override multiple values in a specific test method. The current workaround is to create another test class with the config I need.

### Implementation ideas

I'm not sure if setting `@Target({ TYPE, METHOD })` on `io.quarkus.test.component.TestConfigProperty.TestConfigProperties` is enough but I'm pretty sure that adding this feature cannot be hard.

**Comment by mkouba** [comment]
> @mkouba I assume this is a simple oversight?

Oh, it is...

> 
> If so, I think it's a good candidate for @wiebeck to contribute the fix proposed :)

:+1: Plus it would be nice to add a test ;-).

**Comment by mkouba** [comment]
> I'm not sure if setting `@Target({ TYPE, METHOD })` on `io.quarkus.test.component.TestConfigProperty.TestConfigProperties` is enough but I'm pretty sure that adding this feature cannot be hard.

It should be enough - the `QuarkusComponentTestConfiguration.update(Method)` method should handle repeatable annotations correctly.

**Comment by wiebeck** [comment]
> > @mkouba I assume this is a simple oversight?
> 
> Oh, it is...
> 
> > If so, I think it's a good candidate for @wiebeck to contribute the fix proposed :)
> 
> 👍 Plus it would be nice to add a test ;-).

Here you go....: https://github.com/quarkusio/quarkus/pull/38655
