### ISSUE TITLE
Guidance for testing a Liquibase fix for quarkus-liquibase extension

### ISSUE THREAD

**Issue by tati-qalified** [quarkusio/quarkus#38614]
### Description

Hi! I'm part of the Liquibase team, and recently we've received some tickets regarding your quarkus-liquibase extension. 
They're related to some changes on our side, so we're interested in fixing them.

Looking into the extension, the only way we've found to test our fixes is:
1. Build a jar file for our fix
2. Import it locally to the extension source code
3. Build the jar file for the extension
4. Create a project that uses quarkus-liquibase
5. Import the custom jar file

We worry that there are many possible points of failure, mainly considering the version compatibility for multiple dependencies.

Is there a way we could simplify the process?

Thank you,
Tatiana

**Comment by geoand** [comment]
Hello,

First of all, thanks for reaching out.

If I were you, here is how I would go about testing my fixes:

1. Enhance the liquibase integration test with the currently failing cases
2. [Update](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L174) the version of Liquibase used in Quarkus to some snapshot version of Liquibase I am working on
3. Make my liquibase changes and install them locally (I assume `mvn install ...` is all you need)
4. Run the integration test (`mvn verify -f integration-tests/liquibase -Dnative`) to see whether it now passes
5. Repeat 3-4 as needed

Does this make sense?

**Comment by gsmet** [comment]
I would `mvn install` the BOM after 2 to be sure it's taken into account.

**Comment by MalloD12** [comment]
> Hello,
> 
> First of all, thanks for reaching out.
> 
> If I were you, here is how I would go about testing my fixes:
> 
> 1. Enhance the liquibase integration test with the currently failing cases
> 2. [Update](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L174) the version of Liquibase used in Quarkus to some snapshot version of Liquibase I am working on
> 3. Make my liquibase changes and install them locally (I assume `mvn install ...` is all you need)
> 4. Possibly make changes to the Quarkus liquibase extension (`mvn install -f extensions/liquibase`)
> 5. Run the integration test (`mvn verify -f integration-tests/liquibase -Dnative`) to see whether it now passes
> 6. Repeat 3-5 as needed
> 
> Does this make sense?

Hi @geoand,

On step 1, do you mean creating integration tests for `liquibase-quarkus` extension? At the moment, we don't support that extension in Liquibase.

Thanks,
Daniel.

**Comment by geoand** [comment]
Hi,

My point about `1` is that if your goal is to fix issues in the Quarkus + Liquibase integration, then you first need to have a way to reproduce the current problems - the integration test in Quarkus is an easy way to do so.

**Comment by geoand** [comment]
Is there anything more to do around this?

**Comment by geoand** [comment]
Closing for lack of feedback
