### ISSUE TITLE
quarkus-reactive-pg-client extension fails to pull pg-client-deployment dependency during build

### ISSUE THREAD

**Issue by tsfullman** [quarkusio/quarkus#3861]
**Describe the bug**

When I pull in the quarkus-reactive-pg-client extension using gradle and quarkus-bom version 0.21.1 and try to ./gradlew quarkusBuild, it fails to pull in all of the dependencies and throws an error that it was unable to resolve quarkus-reactive-pg-client-deployment-0.21.1.jar. On version 0.21.0, it fails to pull in io.quarkus:quarkus-undertow-common-substitutions-deployment:0.21.0. On version 0.20.0, the build passes successfully

**Expected behavior**

The quarkusBuild to successfully pull in all dependencies and pass the build using version 0.21.1 and the quarkus-reactive-pg-client extension

**Actual behavior**

Execution failed for task ':quarkusBuild'.
Could not find quarkus-reactive-pg-client-deployment.jar (io.quarkus:quarkus-reactive-pg-client-deployment:0.21.1).

**To Reproduce**

1. Pull in quarkus-reactive-pg-client extension with quarkus bom 0.21.1
2. Try to ./gradlew quarkusBuild

**Code Snippet**
```
dependencies {
    implementation enforcedPlatform('io.quarkus:quarkus-bom:0.21.1')
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-smallrye-metrics'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    
    implementation 'io.quarkus:quarkus-vertx'
    
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jsonb'
    
    //postgres extension
    implementation 'io.quarkus:quarkus-reactive-pg-client'
    
    implementation 'io.quarkus:quarkus-smallrye-reactive-messaging'
    implementation 'io.quarkus:quarkus-smallrye-reactive-messaging-amqp'
}
```

**Environment (please complete the following information):**

Running non-natively with jdk 11.0.2

**Comment by gwenneg** [comment]
Hi @tsfullman! I just tried to reproduce your issue without success.

Could you provide a minimal reproducer and also tell me which version of Gradle you're using?

**Comment by tsfullman** [comment]
Hi, It seemed to start working on quarkus 0.21.1 but I'm not sure why. It also works on 0.21.2 now that that has been released. However, it does still have the same error as mentioned above when building with 0.21.0. The gradle version is 5.5.1
