### ISSUE TITLE
Quarkus kubernetes extension does not register CustomResources from dependent packages

### ISSUE THREAD

**Issue by Javatar81** [quarkusio/quarkus#38657]
### Describe the bug

Error in native executable when CustomResource is not registered for reflection. 

`cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized`

### Expected behavior

CustomResources should be registered for reflection although they are part of an external dependency.

### Actual behavior

CustomResources are not registered for reflection if they are part of an external dependency. You have to add @RegisterForReflection

### How to Reproduce?

1. Create a new Quarkus project A using the kubernetes extension and optionally the quarkus-operator-sdk extension
2. Create another maven project B.
3. Create a class in project B that extends `io.fabric8.kubernetes.client.CustomResource`. 
4. Add B as a dependency to the Quarkus project A.
5. Index B by setting `quarkus.index-dependency.model.group-id` and `quarkus.index-dependency.model.artifact-id` to point to project 
6. Build project B.
7. Build project A with -Pnative
8. If you try to deserialize a CustomResource, e.g. as part of an operator, you will get the error described above

### Output of `uname -a` or `ver`

OpenShift

### Output of `java -version`

17

### Mandrel or GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.0-jdk-17

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
I assume that the [Java Operator SDK extension](https://github.com/quarkiverse/quarkus-operator-sdk) handles this, right @metacosm?

**Comment by metacosm** [comment]
Actually, this is what #38586 is supposed to fix.

**Comment by Javatar81** [comment]
I found that this is already solved by this PR: https://github.com/quarkusio/quarkus/pull/38586.

**Comment by geoand** [comment]
Gotcha, thanks
