### ISSUE TITLE
Configure a REST Client ClientLogger vía CDI

### ISSUE THREAD

**Issue by leaqui** [quarkusio/quarkus#38658]
### Description

At [Using the REST Client - Logging traffic](https://es.quarkus.io/guides/rest-client-reactive#logging-traffic) states:

> REST Client Reactive utilizes a default ClientLogger implementation. You can modify this by supplying a custom ClientLogger instance via CDI or when programmatically creating your client.

But this can't be achieved through CDI, see [Quarkus REST client - How to configure a different ClientLogger](https://stackoverflow.com/questions/77954730/quarkus-rest-client-how-to-configure-a-different-clientlogger?noredirect=1#comment137431761_77954730)

I aim to create a ClientLogger that omits logging headers, as bearer tokens are transmitted through them.

**Comment by geoand** [comment]
Actually, I think I was wrong, looking at the our code, if you annotate an implementation of `ClientLogger` with `@Singleton` or `@ApplicationScoped`, it should be used by all (I don't like this) REST Clients in the application.

Can you give it a try please?

**Comment by leaqui** [comment]
Yes, using `@Singleton` or `@ApplicationScoped` results in:

```log
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:364)
Required type: interface org.jboss.resteasy.reactive.client.api.ClientLogger
Required qualifiers: [@jakarta.enterprise.inject.Default()]
Removed beans:
	- CLASS bean  [types=[class package.WithoutHeadersClientLogger, interface org.jboss.resteasy.reactive.client.api.ClientLogger], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================
```

**Comment by geoand** [comment]
Can you try adding `@Unremovable` to the class as well?

**Comment by leaqui** [comment]
`CDI: programmatic lookup problem detected` disappeared from logs but same behavior

**Comment by geoand** [comment]
Can you attach a sample project so I can see what is going on?

**Comment by geoand** [comment]
We should not require `@Unremovable`, so I'll fix that soon
