### ISSUE TITLE
UI doesn't work correct with umlauts

### ISSUE THREAD

**Issue by doublelong2000** [quarkusio/quarkus#38650]
### Describe the bug

Hello everyone,

By the tests with the Kafka Dev UI following problems where observed:

Special characters like ÄÖÜ will be wrong transferred (Ack) -> 
�������!�
In some cases the messages with the special characters cannot be processed -> com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xc1
The same JSONs are absolut normally used in the tests and can be sent over IntelliJ Kafka client

Kind regards
Andrei

### Expected behavior

Special characters like ÄÖÜ cam be entered in the message and will be correctly written in the Kafka topic

### Actual behavior

Characters are written in the wrong encoding like �������!�

### How to Reproduce?

create Kafka topic, start app with Quarkus Dev UI, open Dev UI Kafka, select topic, add message 

### Output of `java -version`

mandrel-java17-23.0.1.2-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------  Build time:   2023-11-29 14:08:57 UTC Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  Kotlin:       1.9.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          11.0.2 (Oracle Corporation 11.0.2+9) OS:           Windows 10 10.0 amd64

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/38653 to fix it.

I would be either interested in a small Maven reproducer to check it myself or that you try to build my PR following (roughly) the instructions here: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main .

**Comment by doublelong2000** [comment]
Hi,
unfortunately it hasn't fixed the issue. Maybe, as a hint, some input:
Original test message:
{"issueText": "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü1234567890ß!\"§$%/()=?`´{[]}+*~#',.-;:_| ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕ"}
If I send it through the Dev UI client, than it is shown in the Dev UI as:
{"issueText": "ABCDEFGHIJKLMNOPQRSTUVWXYZ\xC4\xD6\xDCabcdefghijklmnopqrstuvwxyz\xE4\xF6\xFC1234567890\xDF!\x5C"\xA7$%/()=?`\xB4{[]}+*~#',.-;:_| \xC0\xC1\xC2\xC3\xC4\xC5\xC6\xC7\xC8\xC9\xCA\xCB\xCC\xCD\xCE\xCF\xD0\xD1\xD2\xD3\xD4\xD5"\x0A }
and shown in the IntelliJ Kafka consumer like:
{"issueText": "ABCDEFGHIJKLMNOPQRSTUVWXYZ���abcdefghijklmnopqrstuvwxyz���1234567890�!\"�$%/()=?`�{[]}+*~#',.-;:_| ����������������������"}
If I send it through the IntelliJ Kafka Producer, then it is shown as: 
issueText": "ABCDEFGHIJKLMNOPQRSTUVWXYZ\xC3\x84\xC3\x96\xC3\x9Cabcdefghijklmnopqrstuvwxyz\xC3\xA4\xC3\xB6\xC3\xBC1234567890\xC3\x9F!\x5C"\xC2\xA7$%/()=?`\xC2\xB4{[]}+*~#',.-;:_| \xC3\x80\xC3\x81\xC3\x82\xC3\x83\xC3\x84\xC3\x85\xC3\x86\xC3\x87\xC3\x88\xC3\x89\xC3\x8A\xC3\x8B\xC3\x8C\xC3\x8D\xC3\x8E\xC3\x8F\xC3\x90\xC3\x91\xC3\x92\xC3\x93\xC3\x94\xC3\x95"\x0A }
and shown in the IntelliJ Kafka consumer like:
{"issueText": "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü1234567890ß!\"§$%/()=?`´{[]}+*~#',.-;:_| ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕ"}

Hope it helps.
Kind Regards
Andrei

**Comment by doublelong2000** [comment]
Created small demo project https://github.com/doublelong2000/demoBug.git

**Comment by gsmet** [comment]
OK, I can reproduce the issue with the reproducer.

@phillip-kruger I'm not exactly sure where the problem is but we probably need you to have a look. At some point, we have something in the Dev UI transport layer transforming the UTF-8 content to something else.

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by doublelong2000** [comment]
Thanks a lot
