### ISSUE TITLE
ContainerRequestContext.getUriInfo().getMatchedURIs() IndexOutOfBoundsException

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#38663]
### Describe the bug

See https://github.com/keycloak/keycloak/issues/26799 - Keycloak users are effectively setting the quarkus.http.root-path to a value that does not end in a slash (as documented), then when accessing that path see an IndexOutOfBoundsException

### Expected behavior

The filter logic should succeed.

### Actual behavior

ContainerRequestContext.getUriInfo().getMatchedURIs() results in an IndexOutOfBoundsException

### How to Reproduce?

- Set quarkus.http.root-path=/foo
- Install a filter that accesses getMatchedURIs():
```
    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
            throws IOException {
        System.out.println(requestContext.getUriInfo().getMatchedURIs());
        return
    }
```
- Access /foo in the browser

### Quarkus version or git rev

at least versions 3.2 - 3.7

### Additional information

The logic in ResteasyReactiveRequestContext.getPathWithoutPrefix is allowed to resturn an empty string when stripping the prefix, but logic like ResteasyReactiveRequestContext.saveUriMatchState assumes that the path is at least a single character - presumably /.

**Comment by geoand** [comment]
I could not reproduce this, so I am guessing that there is some additional complication that is causing the problem.

**Comment by geoand** [comment]
Hm...

In that case I have no idea how we can solve it

**Comment by shawkins** [comment]
> In that case I have no idea how we can solve it

It just seems to be a bug with the logic in resteasy reactive. The logic backing UriInfo.getMatchedURIs appears like it will always fail in the case when accessing the relative root - is that not generally possible? Could something like ResourceLocatorBaseResource / ResourceLocatorTest be modified to reproduce this?

**Comment by geoand** [comment]
If that's the case, then I don't see how it works for the cases I tried

**Comment by shawkins** [comment]
Ok, the next issue is likely that NormalizeRootHttpPathConverter is not running via Keycloak - in which case the non-normalized /foo is being used as the root path instead.

**Comment by shawkins** [comment]
@geoand had to delete my previous update - it was based upon an incorrect observation. I am able to reproduce this: https://github.com/quarkusio/quarkus/compare/main...shawkins:quarkus:iss38663?expand=1 - if testRoot is run with -Dquarkus.http.root-path=/root you will see the index exception.

**Comment by geoand** [comment]
Thanks! I'll have a look later on today

**Comment by geoand** [comment]
Hm...

When I make the same change to `io.quarkus.resteasy.reactive.server.test.resource.basic.ResourceLocatorTest`  I don't see a failure

**Comment by shawkins** [comment]
@geoand and that's even when you specify quarkus.http.root-path=/foo

**Comment by geoand** [comment]
You are right, I had missed that!

Now I can reproduce it, but the problem is I have zero ideas on how to fix it, as I never understood the subresource crap in JAX-RS...

**Comment by shawkins** [comment]
@geoand it could just be that this logic should not be allowed to return an empty string: https://github.com/quarkusio/quarkus/blob/8012cf53931cc02f4ba95eb78f4ec2e66143bbc2/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/ResteasyReactiveRequestContext.java#L438

It should likely return / instead of empty.

**Comment by geoand** [comment]
Feel free to propose a change and we can see if CI likes it or not
