### ISSUE TITLE
Improve Quarkus testing framework

### ISSUE THREAD

**Issue by teoincontatto** [quarkusio/quarkus#3867]
Currently the annotation `@QuarkusTest` start the application under testing. The problem with that is that I have some IT where stop and restart of the application is required to check the application works as expected.
The only option I had was to copy code from `QuarkusTestExtension` and to use outside of the Quarkus JUnit extension. I think this could be easily improved by implementing an parameter annotation with an interface that allow to start and stop the application from inside a test.

**Comment by geoand** [comment]
This has mostly been solved by https://quarkus.io/guides/getting-started-testing#testing_different_profiles
