### ISSUE TITLE
OpenAPI does not fill roles in SecurityScheme in schema

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#38676]
### Describe the bug

After the PR https://github.com/quarkusio/quarkus/pull/38231 extension `quarkus-smallrye-openapi` does not fill roles `SecurityScheme` in generated OpenAPI scheme.

e.g. for endpoint specified as:
```
 @GET
 @Path("/admin")
 @RolesAllowed("admin")
 public String admin() { ... whatever ...}
```
It should generate entry in openapi.json(yaml)
`... /admin.get.security.SecurityScheme : [ "admin "]`

But generates only:
`... /admin.get.security.SecurityScheme : [  ]`

This happens for all endpoints, no matter the which roles are allowed.

### Expected behavior

Required access role should be filled in openAPI schema, e.g:
`... /admin.get.security.SecurityScheme : [ "admin "]`

### Actual behavior

Required access role is empty:
`... /admin.get.security.SecurityScheme : [  ]`

### How to Reproduce?
Use https://github.com/quarkus-qe/quarkus-test-suite
`cd security/keycloak-oidc-client-extended`
`mvn clean verify -Dit.test=OpenApiStoreSchemaIT` 
(possibly enable this test, if it is disabled)

### Output of `java -version`

opendjk 17.0.9

**Comment by MikeEdgar** [comment]
@mocenas are you using OIDC?

**Comment by mocenas** [comment]
> @mocenas are you using OIDC?

Yes it's with OIDC

**Comment by MikeEdgar** [comment]
Thanks @michalvavrik , found the problem. I'll get a PR up later today.
